### ISSUE TITLE
Content updates in caregiver react widget

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10000]
## Issue Description
We need to make 2 minor copy updates in the  caregiver-content-toggle react widget that was created for this issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8853.

The updates should be made to the "application on" state of the widget.

---
## Tasks
- [ ] Update the content as reflected in the image below (update to text and update to button highlighted).

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/4576177c-db14-427f-bb92-41157df39438)
- [ ] Add the following code to the button so that screen readers read the full program name:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/a077b500-5090-4570-a079-6de4c2d1c3c3)

## Acceptance Criteria
- [ ] Copy will be updated in the react widget
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ncksllvn @kelsonic. I'm hoping this is a pretty simple request, but please let me know if it's not! And thank you in advance for your help.

FYSA @stephorkandatx

**Comment by kelsonic** [comment]
PR is up, please give it a spot check to make sure all content changes are done as expected when you can! 🙂 https://github.com/department-of-veterans-affairs/vets-website/pull/13099/files

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic. Looks great. Thanks so much for the quick turnaround on this!

**Comment by kelsonic** [comment]
Of course! I'll let you know once it's merged! 🙂

**Comment by kelsonic** [comment]
PR merged! Ticket ready for validation + closing following tomorrow's deployment 🙂

**Comment by stephorkandatx** [comment]
@DanielleThierryUSDSVA when you get a moment, are you able to validate the change? Asking before closing this out
