### ISSUE TITLE
[Pre-release] Separate the app & content assets in different buckets

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#10001]
## Current state

Right know we have one s3 bucket which contains the webpack output (`.js`, `.css`, font files) in the `/generated` folder, and the content output is at the root nested in a bunch of different folders with `index.html` files.

## Desired state

We want to add two new s3 buckets; one for the webpack output (AKA application build) and one for the content output. Having the webpack output in one bucket, the content build output in another, in addition to the original bucket, will help with separating the content build from `vets-website`. That way, we minimize the risk of disrupting the current system. 

## Background

We have a separate `content-build` repo for `vets-website` that isn't connected to anything right now. We want to be able to run the isolated content build and have it sync the results to s3 without disturbing the files that are synced as a result of the webpack build.

Once this is finished we can have the standalone content-build repo update the proper s3 bucket, which makes for a simpler transition

## Testing & Rollout

- We will first [add the new buckets for the dev environment](https://github.com/department-of-veterans-affairs/devops/blob/0aebe2afe65849297d554b3ee7ad1b60ffde4e53/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-dev.yml#L5-L12) to this config so it can be used by nginx. (Let's say they're called `content_proxy_url` and `apps_proxy_url`)
- Next, we will add a `proxy_pass` directive to [this dev-specific config](https://github.com/department-of-veterans-affairs/devops/blob/0aebe2afe65849297d554b3ee7ad1b60ffde4e53/ansible/deployment/config/revproxy-vagov/templates/nginx_revproxy.conf.j2#L347-L371) that resembles this:

```
location ~ ^/.*\.html$ {
    proxy_pass {{ web_server.content_proxy_url }}$request_uri;
}
```

- We will also need to either modify [the deploy script](https://github.com/department-of-veterans-affairs/devops/blob/0aebe2afe65849297d554b3ee7ad1b60ffde4e53/ansible/deployment/roles/deploy-vets-website/files/vets-website-deploy.sh) and associated configs so that it can have branching logic for deploying to dev, or we will need to write a new deploy script specific to the dev environment that we can later expand to all environments.

---
## Tasks
- [x] Create two new s3 buckets; one for the output of the content build, and one for the output of the application build
- [ ] Write a script to deploy the content build out to the content bucket
- [ ] Write a script to deploy the webpack out to the webpack bucket
- [ ] Update the reverse proxy so that content is proxied to the content bucket
- [ ] Update the reverse proxy so that application is proxied to the application bucket

## Acceptance Criteria
- [ ] The website has webpack output in one s3 bucket, content build output in another, and the original is untouched

**Comment by billfienberg** [comment]
@bkjohnson, as it's currently written, this ticket seems to indicate that the application build will stay in the existing bucket, and the content build will go in the bucket. 

IIRC, during our meeting with Megan and Rian earlier today, our latest plan is to leave the current bucket untouched, and create two new additional buckets; one for the content build and one for the application build. 

Does that sound correct? If so, should we update this ticket to reflect that plan?

**Comment by billfienberg** [comment]
From Taylor S.

> k we got these buckets up:
> ```apps.dev.va.gov
> apps.sandbox.va.gov
> apps.staging.va.gov
> apps.www.va.gov
> content.dev.va.gov
> content.sandbox.va.gov
> content.staging.va.gov
> content.www.va.gov```

https://dsva.slack.com/archives/CJYRZK2HH/p1597873544205500?thread_ts=1597775615.150700&cid=CJYRZK2HH

**Comment by jhouse-solvd** [comment]
@billfienberg - Is there still active work or support needed on this from the Ops team? Let us know so that we can help out if needed, or if this ticket can be closed / moved. Thank you!

**Comment by meganhkelley** [comment]
@billfienberg is this complete?

**Comment by meganhkelley** [comment]
Write a script to deploy the content build out to the content bucket - PR open for this now (#7971)
Write a script to deploy the webpack out to the webpack bucket - TO DO (#7978)
Update the reverse proxy so that content is proxied to the content bucket - TO DO (ticket for each environment, dev is #11914)
Update the reverse proxy so that application is proxied to the application bucket - TO DO (ticket for each environment, same as dev for content bucket #11914)

**Comment by meganhkelley** [comment]
Closing ticket as it is duplicative (see comment above)
