### ISSUE TITLE
Build PCPG (CH36) Eligibility Wizard

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10015]
## User Story
As a Veteran looking for Career assistance, I want to check and see if I am eligible for the PCPG program before applying so I know that I will be accepted and get the help and benefits I need.

## Goal
Establish the frontend experience for this eligibility wizard given the considerations below, and the prototype produced by Design.

## Considerations
- Eligibility wizard should take the format of the "Can I file my claim online?" wizard at https://www.va.gov/disability/eligibility/ per this Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9665
- When complete, the link to the prototype will be here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10011
- [Wizard flowchart](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design)

## Tasks
- [ ] Build the wizard as shown in the prototype
- [ ] Workflow is represented based on the prototype to filter out those Veterans that are not eligible.

## Acceptance Criteria
- [ ] An eligibility wizard is residing on the intro page and behaves as expected per the prototype
- [ ] A PR has been requested for merging

**Comment by micahchiang** [comment]
Recent PR that puts the 526 wizard on the intro page - https://github.com/department-of-veterans-affairs/vets-website/pull/13963/files
