### ISSUE TITLE
Retrieve Initial Feedback on Contact Center report on Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#10019]
## Issue Description
VSP Analytics & Insights has been sharing the monthly contact center report as Excel files on Slack (#vfs-analytics) since November. Almost 8 months later, we transferred the process over to Domo with a 1:1 in terms of data visualization. How might we understand how users have been reading the reports, if they have been, and react to this change so that we can better serve users with this transition?

---
## Tasks
- [x] Track usage
- [x] Create survey and/or conversation guide
- [x] Send survey to users
- [x] Synthesize feedback
- [x] Share feedback with team & determine next steps

## Acceptance Criteria
- [ ] VSP Analytics & Insights understands current Contact Center report user sentiment & can determine next steps

**Comment by clantosswett** [comment]
These were the questions we asked when we published the first contact center report back in November. I think we might want to add some additional questions to gauge whether people like accessing the report on DOMO. 

Did you find this report helpful? (Yes, Somewhat, No)

If you answered no, please explain why you did not find the report to be helpful.

What are you going to do with the information in this report?

Is there feedback you would like to provide to improve this report?

**Comment by joanneesteban** [comment]
@amycesal to Slack the login for Optimal Workshop (to implement the survey and remain consistent with the rest of VSP).

**Comment by clantosswett** [comment]
@joanneesteban Can we get information on the usage of the contact center report since it was shared (6/10)? And @amycesal do you have any suggestions for additional questions to include in the survey? Here are a few things I would be interested in learning but not sure how to best phrase it:

- Do they like the DOMO dashboard better than the excel spreadsheet format? Why or why not?

- Was there something they were unable to find/do when looking at the report? I want to know if a lack of familiarity with DOMO prevents someone from using the report fully. 

- What part of the report was most helpful? Which part was least helpful? 

Did you find this report helpful? (Yes, Somewhat, No)

If you answered no, please explain why you did not find the report to be helpful.

What are you going to do with the information in this report?

Is there feedback you would like to provide to improve this report?

**Comment by Kimberley2019** [comment]
Draft survey has been created and will be reviewed by @amycesal 

https://adhoc.optimalworkshop.com/questions/5p040tyr

**Comment by joanneesteban** [comment]
@Kimberley2019 - can you Slack us the PW for this survey?

**Comment by Kimberley2019** [comment]
@joanneesteban I put it in Slack yesterday but will Slack again so that it's more current.  Private channel of course.

**Comment by Kimberley2019** [comment]
The link for the survey questionnaire results can be found [here](https://app.optimalworkshop.com/questions/adhoc/contact-center-domo/shared-results/b8rkc5f10q264p7e3xwsdy0f5yec0wtb).

The synthesis can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/teams/vsp/teams/insights-analytics/contact-center/domo-monthly-report-survey-synthesis.md)

**Comment by Kimberley2019** [comment]
@joanneesteban and @clantosswett 
Please review links above and advise if any additional details need to be provided.
