### ISSUE TITLE
Audit GTM Filters

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#10013]
## Issue Description
VSP Analytics & Insights needs to audit the filters on GTM to ensure we're not losing any data due to programmatic changes on the FE side.

---
## Tasks
- [x] Audit filters on each View in GTM
- [x] Document on the Github issue the results of the audit
- [x] Fix any filters that need to be updated
- [x] Recommend new filters that should be added

## Acceptance Criteria
- [x] Audit is completed & documented
- [ ] Insights understands how much
---
## Links
[Post-Mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2020-05-28-variance-direct-deposit-data.md)

**Comment by bmcgrady-ep** [comment]
I have audited the Filters for all the Views from All VA.gov through Personalization Tools Modernized.

**Comment by bmcgrady-ep** [comment]
I've reviewed the data in Non-Production Views and started adding the following filters to the views:
- Global - Add trailing slash
- Global - Lowercase all URI for consistency

**Comment by bmcgrady-ep** [comment]
I added Global - Convert Site Search to All Lower Case to the following views:
- Facility Locator
- WBC - va.gov Modernized

Added following terms to the Exclude URL Query Parameters list:
- next (Disability and Claims Modernized; WBC - va.gov Modernized)
- feature (ebenefits.va.gov)

**Comment by bmcgrady-ep** [comment]
I created 2 test views in the VA Production Property for adding filters and assigning an order to the filters. These views will be used to compare key metrics: pageviews, users, and sessions between the current Production Views and the Test Production Views. The 2 views that are being tested for a 24 hour period are All VA.gov Website Data [Production] and WBC - VA.gov Modernized Content.

The filter order for the Test View of All VA.gov Website Data [Production] has changed by adding these filters to the top of the filter order:
1. Global - Add Trailing Slash if missing
2. Global - Lowercase all URI for consistency 

The Test View of WBC - VA.gov Modernized Content has changed by adding the **Global - Lowercase all URI for consistency** filter and changing the filter order with **Global - Add Trailing Slash if missing** as the 4th filter and **Global - Lowercase all URI for consistency** as the 5th filter.

Also, after meeting with @jonwehausen and @bsmartin-ep, it was decided not to add any parameters to the Exclude URL Query Parameters list as the terms mentioned above may be useful in BigQuery reporting.

**Comment by bmcgrady-ep** [comment]
QA for GA Filters
GA View | Real View Data | Test View Data | Test Status
------------ | ------------- | -------------
All VA.gov Website Data [Production] | http://c2n.me/484ozO8
![image](https://user-images.githubusercontent.com/66263904/86974109-90c77780-c12a-11ea-83ae-6157e6bba5d9.png) | 
![image](https://user-images.githubusercontent.com/66263904/86974162-ae94dc80-c12a-11ea-90a9-517af38e2600.png) | ✔️ **PASS**

**Comment by bmcgrady-ep** [comment]
QA for GA Filters
GA View | Real View Data | Test View Data | Test Status
benefits.va.gov | Real View Data
![image](https://user-images.githubusercontent.com/66263904/87323012-0a70b400-c4e3-11ea-978e-332f960cbd73.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87323242-5de30200-c4e3-11ea-9f75-b17779916367.png)
 | ✔️ PASS

Burials Modernized View | Real View Data
![image](https://user-images.githubusercontent.com/66263904/87324625-355c0780-c4e5-11ea-9964-51cf00cdcf2b.png)
 | Test View Data
![image](https://user-images.githubusercontent.com/66263904/87324661-43118d00-c4e5-11ea-8fca-4ecfccbd0466.png)
 | ✔️ PASS

**Comment by bmcgrady-ep** [comment]
Each Production View has now had a Test View created in Production with the correct filters and filter order in place. The Test Views will be monitored over the next 24-48 hours and the Production Views will be updated according to the accuracy of the Test View data.

**Comment by bmcgrady-ep** [comment]
Cut over the filters and filter order for benefits.va.gov View and Burials Modernized View in Production. I will continue to monitor the data to make sure that it looks correct over the next few days.

**Comment by bmcgrady-ep** [comment]
QA for GA Filters
GA View | Real View Data | Test View Data | Test Status
developer.va.gov | 
![image](https://user-images.githubusercontent.com/66263904/87697174-9f271c00-c746-11ea-98b0-a8c10b3f8901.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87697206-aa7a4780-c746-11ea-8b77-0a525a340f61.png)
 | ✔️ PASS

Disability and Claims Modernized | 
![image](https://user-images.githubusercontent.com/66263904/87697497-0513a380-c747-11ea-9113-c53a6f01d148.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87697550-1361bf80-c747-11ea-94ab-fad38e5e5f79.png)
 | ✔️ PASS

ebenefits.va.gov | 
![image](https://user-images.githubusercontent.com/66263904/87697662-3b512300-c747-11ea-86d0-86f2f58ca67e.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87697702-4b690280-c747-11ea-8df8-b432f8d2c060.png)
 | ✔️ PASS

Facility Locator Modernized View | 
![image](https://user-images.githubusercontent.com/66263904/87698165-f4aff880-c747-11ea-81a5-28d101b1e371.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87698203-01cce780-c748-11ea-90de-f9f1e2e60456.png)
 | ✔️ PASS

Health Care Modernized | 
![image](https://user-images.githubusercontent.com/66263904/87698478-65571500-c748-11ea-8038-19efb3450fc6.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87698553-7ef85c80-c748-11ea-9146-604983033c67.png)
 | ✔️ PASS

myhealth.va.gov | 
![image](https://user-images.githubusercontent.com/66263904/87700107-ad773700-c74a-11ea-9ca3-184ec87d07b6.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87700150-bcf68000-c74a-11ea-8dce-bacb7779ee21.png)
 | ✔️ PASS

Personalization Tools Modernized | 
![image](https://user-images.githubusercontent.com/66263904/87700392-1b236300-c74b-11ea-8100-d5ec9ce82d91.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/87700426-25ddf800-c74b-11ea-8340-83be6ccc072f.png)
 | ✔️ PASS

**Comment by bmcgrady-ep** [comment]
GA View | Real View Data | Test View Data | Test Status
Employment Modernized View | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/3cabe33a-e437-4220-8294-1bb5e5878f70) | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/67583df3-4164-4ea9-9e7e-666e5bd08aea) | ✔️ PASS

**Comment by bmcgrady-ep** [comment]
GA View | Real View Data | Test View Data | Test Status
Exclude Internal Dept. of VA ISP | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/8773cb21-3a8e-4363-a535-88fd7fdffba0) | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/75fe368f-c6c2-478d-96d5-cb74d2ac472e) | ✔️ PASS

Housing Modernized | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/4465c9aa-fe2d-449c-bc54-d169433c0283) | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/18d450d1-8ffe-4681-8821-76fff08a7e6f) | ✔️ PASS

Pension Modernized | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/4a15e765-7874-4fc8-a305-de583af96eac) | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/460adc76-e7aa-4bb3-a282-41dd7139c2b9) | ✔️ PASS

Records Modernized | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/bcb5c145-4b83-4b8c-8ea3-edba34d7f439) | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/92d0a85f-cb14-4f4d-9f52-48c8a6b9f335) | ✔️ PASS

Insurance Modernized | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/da68ad7a-3180-47c8-be58-ea4b73cae65c) | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/ee63f9bd-8d7a-4e51-960d-558096a1bbe8) | ✔️ PASS

**Comment by bmcgrady-ep** [comment]
I cut over the filters to each one of the Views after QA of the Test View Filter data and the Production View Filter data.
