### ISSUE TITLE
Determine Domo Filing/Naming Structure

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#10022]
## Issue Description
We need to figure out how name or create a filing system with dashboards on Domo as we expand the creation so that we can scale dashboarding while minimizing confusion and making clear which dashboards belong to which product and use case.

---
## Tasks
- [ ] Amy & Joanne meet to discuss needs & potential solutions
- [ ] Decide on filing/naming structure
- [ ] Document decision
- [ ] Share with team 

## Acceptance Criteria
- [ ] VSP Analytics & Insights can expand dashboards on Domo while minimizing crowding & enabling readability and consistency

**Comment by joanneesteban** [comment]
Filing structure determined. Moving onto changing the structure in Domo. Closing.
