### ISSUE TITLE
Setup deployer to work in playground

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#10020]
## Issue Description
Get vsp-infra-deployer running fully functional in the playground environmnet.

---
## Tasks
- [ ] deployer pushes images to ECR
- [ ] deployer permissions setup in nomad
- [ ] app alb is publicly avaiable so github webhooks can reach deployer
- [ ] deployer config setup in vault
- [ ] 

## Acceptance Criteria
- [ ] vsp-infra-deployer running in nomad in playground
- [ ] vsp-inra-deployer can deploy itself and other apps like loki
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
