### ISSUE TITLE
Add PACT verification task as part of the CircleCI build 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#10029]
## Issue Description

This task involves creating a job or step as part of the CircleCI vets-api build process which verifies against the “stable” pacts. For now the term “stable” refers to the vets-website pact-search branch as this is in the testing phase. Later this will be changed to pacts tagged as prod and master. Eugene is working on implementing the [tagging piece](https://docs.pact.io/pact_broker/advanced_topics/using_tags/#1-automatically-tag-with-branch-name-when-pact-is-published-recommended) on the frontend

Our [PACT broker](https://vagov-pact-broker.herokuapp.com/) is currently hosted on Heroku

The be-tools/pact-search branch has the CircleCI config/ build job with the PACT verification step pushed up to the branch, but it's currently failing in CI with a Search 400 error. [Failing Circle PACT verification task step](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-api/1789/workflows/549ab11b-9ad0-4de7-a2f8-4dd11f2860d3/jobs/1742)

## Tasks
- [ ] Add a build step to the test job in CircleCI that runs the rake pact:verify task (see pact-search/be-tools branch) -- This could later be broken into separate jobs, but a "step" is ok as the first implementation piece

### PACT checklist
[PACT setup checklist](https://docs.pact.io/pact_broker/set_up_checklist)

## Acceptance Criteria
- [ ] Verification task is part of the vets-api circle build
- [ ] Verification step passes in Circle
---
## Additional Info
- Run "docker-compose rake pact:verify" or "bundle exec rake pact:verify" locally to run verification task. This will verify the pacts running on our heroku hosted broker
- The rake pact:verify task spins up dynamic rspec tests to verify the contracts
- docker-compose rake pact:verify runs in the development environment locally 
- Issue currently in Circle where Search throws a 400 error when it calls out to external search service
- [Failing Circle PACT verification task step](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-api/1789/workflows/549ab11b-9ad0-4de7-a2f8-4dd11f2860d3/jobs/1742)
- [Lindsey's personal Circle and PACT notes](https://hackmd.io/P7zMmK_8Rz-55q96575s5Q?both)

## Helpful Links
[PACT search vets-api branch](https://github.com/department-of-veterans-affairs/vets-api/tree/be-tools/pact-search)
[PACT Search example](https://github.com/department-of-veterans-affairs/vets-website/pull/12505)
[Pact HCA example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/3a8f4953b5e77edcbd39fd3db073232cdaca0ea0/teams/vsp/teams/tools/frontend/2019-11-13-consumer-driven-contract-testing-with-pact.md)
[PACT design doc](https://github.com/department-of-veterans-affairs/va.gov-team/pull/8073/files#diff-f2abf33f91ea32d2168228610ba56d37R209)
[PACT gem](https://github.com/pact-foundation/pact-ruby)

**Comment by f1337** [comment]
EOB yesterday I pushed [changes](https://github.com/department-of-veterans-affairs/vets-api/commit/5d13899e744b4d1ef9025a4a4e6fb1f3b140d71f) which make VCR work as desired w/ BE PACT. AFAIK, this unblocks all PACT work, including this issue.

**Comment by f1337** [comment]
This week I pushed changes which should unblock this and all other PACT tickets, AFAIK:

https://github.com/department-of-veterans-affairs/vets-api/commit/b9a37dd32e588712b28a273baf4f06620ad434fa
https://github.com/department-of-veterans-affairs/vets-api/commit/5d13899e744b4d1ef9025a4a4e6fb1f3b140d71f
