### ISSUE TITLE
Determine VSP Strategy for Medallia

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#10021]
## Issue Description
With Medallia implementation starting 6 months after initial estimations, VSP & VSA have matured and strategies have shifted. How might we align on a strategy for coming up with and implementing surveys on VA.gov?

---
## Tasks
- [ ] Meet with VSP and VSA leads
- [ ] Determine responsibilities
- [ ] Document any updates

## Acceptance Criteria
- [ ] VSP & VSA understand responsibilities around Medallia, and VFS teams understand how to add a Medallia survey to their product.
