### ISSUE TITLE
 BDD: Schema Updates

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#10032]
## Issue Description
We met with EVSS and they have stated that we need to conform to their schema.  We should be able to attach it to this story.  The conversation centered around separation location code but there may be other things we are missing or sending in the wrong regex, etc.

We may need a FE story to match this.
## Tasks
- [ ] _What work is necessary for this story to be completed?_
## Acceptance Criteria
- [ ] Back end submission matches EVSS schema.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
