### ISSUE TITLE
Standardize Breadcrumbs for events, news releases and stories

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10030]
## What happened?
There are several issues occurring with breadcrumbs for Events, News Releases and Stories. This issue is to **standardize the existing experience** between the three categories. 

A separate conversation is needed to address the intended behavior going forward. 

**1. When a Veteran opens an individual Event, News Release or Story from the relevant page, there is a breadcrumb at the top which should navigate back to "see all" Events, News Releases and Stories.** This works as expected for Events but the breadcrumb is not hyperlinked for News Releases or Stories.

![events breadcrumb hyperlink.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/69661710-d5d7-4aad-ae56-b2ae475eae6f)

![New releases breadcrumb hyperlink.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/3f5a59c5-f242-4d15-af2a-100e6aa0c3b6)

![stories breadcrumb hyperlink.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/a14c107f-8e32-4541-b0eb-fc057ef99d87)

**2. Only Events pages have a carat and breadcrumb for the individual event.** This needs to be standardized for News Releases and Stories as well. The name may need to be truncated. 

![events breadcrumb hyperlink2](https://user-images.githubusercontent.com/55411834/84296332-1a266280-ab09-11ea-9abb-da2174c08058.png)

![stories breadcrumb hyperlink2](https://user-images.githubusercontent.com/55411834/84296293-1266be00-ab09-11ea-80d9-e885ac2a04de.png)

![New releases breadcrumb hyperlink2](https://user-images.githubusercontent.com/55411834/84296308-1561ae80-ab09-11ea-8629-cea7139cb043.png)

**3. Breadcrumbs for individual Events appear to use the url, resulting in an awkward breadcrumb in all lower case, separated by hyphens**

![image](https://user-images.githubusercontent.com/55411834/84296562-6a052980-ab09-11ea-8ed8-5706023ffbcb.png)

**As listed in layouts, the following liquid layout templates are not part of VAMC sites and should not be impacted by our Breadcrumb changes:**

- page.drupal
- landing page.drupal
- home.drupal
- office.drupal

## Specs:
- Browser: Chrome

## Tasks
- Evaluate impact of making changes to breadcrumbs for Events, News Releases and Stories 
- Create standardized experience for stories, news releases and events, until final intended breadcrumb behavior is determined
- Ensure an appropriately named breadcrumb and carat are in place for individual events, news releases and stories
- Ensure all breadcrumbs are hyperlinked in appearance and function
- Ensure breadcrumb links to "see all" Events, News Releases and Stories from the respective individual items. 

## Acceptance criteria
- When viewing stories, news releases and events, 
   - [ ] Individual items have appropriately named breadcrumb
   - [ ] Breadcrumb is hyperlinked in appearance and function
   - [ ] When breadcrumb is selected, the Veteran is returned to "see all" Events, News Releases and Stories.
- Functionality on Non-VAMC pages is maintained and is not impacted by these changes. 
- Experience is consistent in mobile or desktop

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by kevwalsh** [comment]
Some of these issues have been addressed, like the casing and dashes in the last breadcrumb item. Vet Centers and Vet Center Location Pages still have a problem. 
<img width="1137" alt="Screenshot_2022-06-16__11_24_AM" src="https://user-images.githubusercontent.com/643678/174104887-569f1ef6-eaed-47ab-82cf-aaa7858899ec.png">

**Comment by davidmpickett** [comment]
The issues in this ticket have been addressed. The spinoff ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13532 addresses related, but separate, concerns
