### ISSUE TITLE
[Front End] Debt Letters - 508 for .pdf docs 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10043]
## Issue Description
_As a veteran I will have the option to download debt letters online that I received in the mail in .pdf format from dFolders. Once downloaded the .pdf has to be 508 compliant 

---
## Tasks
- [ ] _Once a letter is downloaded, it has to be readable by screen readers devices
- [ ] _provide Jen a sample copy of letter and get direction of what needs to be done to make .pdf 508 compliant.
_

## Acceptance Criteria
- [ ] _Download a letter or use sample letter from eFolders
- [ ] _Verify that it is 508 compliant 
- [ ] _Sign off from Jen

_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mr0sari0** [comment]
Hi @jenstrickland, I was wondering if we could meet up on this to ensure the correct steps are taken to make these pdfs 508 compliant.

**Comment by jenstrickland** [comment]
Thank you for asking, @mr0sari0 ! 🏆 

Do you have the base form PDF?

Have you generated a sample, yet? 

Feel free to put time on my calendar.

Some history: so far, I've noticed that these generated PDFs append data to a "shell" PDF of the form. If we ensure that shell is compliant (and the Additional Information shell), it looks like the generated PDF will be, too. If the shell isn't compliant, then all the generated PDFs won't be, too.

cc @leahkeeler fyi

**Comment by mr0sari0** [comment]
@bradl3yC do you know if there's a base form PDF or sample PDF for this yet?

**Comment by bradl3yC** [comment]
@mr0sari0 no - we do not generate the PDFs - they are (or will) be delivered directly to us from the VBMS API and passed on as a direct download link to the user.

**Comment by jenstrickland** [comment]
Has a sample PDF been provided? 

Those PDFs should be 508-compliant. We should require that whoever is responsible for those provides compliant PDFs, so that BAM2 provides a compliant set of work.

**Comment by leahkeeler** [comment]
HI @jenstrickland - Here is the thing, those .pdf's in question are generated by some mainframe that sends the actual print jobs and is uploaded to eFolders. I am not sure there is "whoever" that can change anything. What are yoru suggestions for next steps? We want to make sure we do all the due diligence here

**Comment by jenstrickland** [comment]
Hi @leahkeeler — do you have a sample PDF, or can you map out ownership of mainframe, data, and eFolder?

If the PDF is not compliant, whoever is responsible at the mainframe should address their workflow to ensure they deliver compliant PDFs. That would be outside BAM2's responsibility.

Is this the correct flow?

1. Mainframe team generates a PDF and stores in eFolder
1. BAM2 Debt Letters receives a list of PDFs in the eFolder < is there additional data the team receives?
1. BAM2 Debt Letters displays the content from the eFolder


The VA 508 Office scans product work as a whole. The compliance rating is shared with Congress.

We need to determine if the eFolder is considered as within the BAM2 Debt Letters work. If it is scanned within BAM2's work, that will include those PDFs in the report and lower the compliance rating for the team's work. If the mainframe and eFolder are other groups' responsibilities, then we should document that.

**Comment by leahkeeler** [comment]
Thanks Jen. We have no control over eFolders or things that are uploaded or downloaded from there. Our requirements were simply to provide the Veteran the ability to download the letters they receive in the mail. There is no one from the vbms team that is working with us directly, the have an api to access the documents stored there and that is about it. Does this help? 

Are there any next steps that @mr0sari0 needs to take with you or your team?

**Comment by jenstrickland** [comment]
This is helpful! 

Would it be possible to add documentation to the Product Outline, so that it is clear that the PDFs are outside the scope of this work responsibility? I'll want to be sure to document that when we send the work to the VA 508 Office for their review.

**Comment by leahkeeler** [comment]
@jenstrickland Great point and Thank-you, I will add to product guide. Is there anything our team can do here with the constraints we have, that we are simply using an api to download something we have no control over? please let us know on how best to proceed.

**Comment by jenstrickland** [comment]
Since the team follows established processes to ensure accessibility and compliance in deliverables, y'all should be in good shape. There was lack of clarity around the PDFs, as some teams are generating a PDF as part of their work. It's helpful to clarify ownership so there won't be any confusion. Thanks so much for the clarification! 🤩

**Comment by leahkeeler** [comment]
Thank-you for your help @jenstrickland - all good stuff to know going forward. You are a wealth of knowledge!!!

**Comment by mr0sari0** [comment]
@leahkeeler @leahkeeler After adding the documentation to the product outline, can this ticket be closed?

**Comment by leahkeeler** [comment]
Closing this ticket - documentation added to product outline
