### ISSUE TITLE
Content Review from BAM1 for BDD

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10040]
## Why you're here
- Content support for authenticated application or tools

## Steps to complete intake request
- [x] Submit this request when VSA Public Website team intervention is required
- [x] Provide detailed information of your request to help us understand our role in completing your request 
- [x] Link to this issue in #vsa-public-websites in Slack, tag @Selina Cooper 

### Background
*Provide a background of your tool/functionality.*

Our BDD form is based on the 526 form that has been out there for a long time.  However, there are a number of places where there are some differences and we would like to do a content review in preparation for release.  We have vetted the content with the stakeholder to make sure it addresses the business needs but we do need to ensure that the content is accessible and plain language.  The two areas are Exams and STRs (Service Treatment Records).

![BDD-gating-exam-wording.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/c952b31a-5ff6-4f63-8b84-1e2933e84558)

![Screen Shot 2020-06-08 at 2.33.46 PM.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/e7510442-d396-4589-9e1b-1890168b3423)

### Request Type
- [x] **Content support for authenticated app/tool.** 
   * Word document with draft if available, or link to the URL where the draft content appears:
      * See attached screen shots
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * Part of the form system, main user flow
   * Scope: How many screens? (Or messages, etc.) 
      * Two, currently.
      

### Desired/target implementation date
Our initial go live date is slated for June 24th

### Requestor info
- Team name: BAM1
- DEPO product owner: Andrea Schneider
- Product manager: Luke Majewski
- Designer: Kevin Stachura
- FE engineer: Nick Sprinkle
- Product/team Slack channel: #vsa-benefits-memorial

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by peggygannon** [comment]
Hi, @luke-gcio I have a question about the first screen: 

--When will users see that message? Is it part of the disability wizard? 
--When a user clicks the green CTA button, where will that take the user?

**Comment by peggygannon** [comment]
@luke-gcio 

Please see below for content recommendations for these alerts. 

A couple of questions/note about the first alert:
1. the heading above says "You *are* eligible, but the body of the alert says *you may be* eligible.. is there a reason the message body says *may*? If so, i will need to tweak my recommendation below.  Please advise

2. I move the sentence about the 45 days for VA claim higher in the message body b/c I felt like that is important information for BDD eligibility. 

3. Is this the first time an applicant might hear about the BDD program? I ask b/c we use the acronym in the header of this alert and they might not be familiar with it. If so, I will need to tweak my recommendation below.  Please advise.

**You’re eligible to file a BDD claim**
You’re eligible to file a disability claim under the Benefits Delivery at Discharge (BDD) program. This program allows service members to apply for disability benefits before they leave the military. You’ll need to be available for 45 days after you submit your claim for a VA exam. 

Based on your separation date, you have [TK] days left to file a BDD claim. 

[Learn more about the Benefits Delivery at Discharge program] (where does this link take users?)

{CTA button} File a Benefits Delivery at Discharge claim

-----

**We recommend you submit your service treatment records**

Your eligibility for the BDD program could expire if there is a delay in getting your service treatment records. 
You don’t have to turn in your records now. But we recommend that you submit them with this application. If you decide to submit them later, please do so as soon as possible.

**Comment by kevinstachura** [comment]
Hi @peggygannon! Thanks for your patience and apologies for the late response on this. Here are some answers to your questions:

_--When will users see that message? Is it part of the disability wizard?_

Correct, this message will be seen when users are completing the disability wizard, and there will actually be 3 different types of messages that show, depending on the separation date response:

**If a user enters a date that is 'too far out' from the BDD eligibility window:**

<img width="773" alt="Screen Shot 2020-06-19 at 11 09 14 AM" src="https://user-images.githubusercontent.com/54544300/85147815-61090c00-b21d-11ea-98ea-ddc59b43793f.png">

**If a user enters a date that falls within the BDD eligibility window (180 days out - 90 days out from separation) :**

<img width="640" alt="Screen Shot 2020-06-19 at 11 11 17 AM" src="https://user-images.githubusercontent.com/54544300/85148002-9ada1280-b21d-11ea-883c-9747af9b7f65.png">

**If a user enters a date that is less than 90 days from separation (out of BDD eligibility window):**

<img width="706" alt="Screen Shot 2020-06-19 at 11 13 10 AM" src="https://user-images.githubusercontent.com/54544300/85148214-dffe4480-b21d-11ea-8279-42aa2b906ea0.png">

**We do have an error state, if the user enters a separation date occurring in the past:**

![BDD-sep-date-error](https://user-images.githubusercontent.com/54544300/85148422-1dfb6880-b21e-11ea-90c8-b22a5cdec5b9.png)


_--is this the first time applicants are potentially hearing about "BDD" ?_

It could be - however our qualitative research indicated that many Service Members were made aware of BDD via the TAP program - a class that Service Members are offered before separation. Benefits Delivery at Discharge (otherwise known as a 'pre-discharge claim') is covered in that class, and a handful of our participants identified the BDD program as a topic that was covered in that class.


_--When a user clicks the green CTA button, where will that take the user?_

If signed out, it will take the user to this page: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421577781

If signed in, it will take the user to this page:

https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421577782

_--what does the days left to file refer to? in the example above does it mean that the user is 16 days away from leaving the military?_

The 16 days remaining means that the Service Member has 16 days left in the eligibility window to file a BDD claim. 

In short, a BDD claim is a claim that Service Members can file before leaving the military. It's only available for SMs that are 180 days - 90 days out from their separation date. If they are 89 days from their separation date, they cannot file a BDD claim (they would instead file a regular 526 original claim). If they are more than 180 days out from their separation date, they are not able to file a BDD claim nor any other type of disability claim at that time. 

It's certainly a bit confusing - I've found this video to be really helpful in breaking down how BDD works: https://www.youtube.com/watch?v=DTSujFDP-58

_A couple of questions/note about the first alert:

the heading above says "You are eligible, but the body of the alert says you may be eligible.. is there a reason the message body says may? If so, i will need to tweak my recommendation below. Please advise_

This was more of a 'catch all' type of explainer. As we are relying on the Service Member to provide an accurate separation date, we thought the explanatory body of text might elaborate that you _may_ be eligible based on the info you provided. However, I think perhaps the preface of 'based on the information you provided' is already there, we could probably remove the 'may' from the explainer text in the alert messaging body. Up to you!

_I move the sentence about the 45 days for VA claim higher in the message body b/c I felt like that is important information for BDD eligibility._

This is important info, so thank you for this rec!

_Is this the first time an applicant might hear about the BDD program? I ask b/c we use the acronym in the header of this alert and they might not be familiar with it. If so, I will need to tweak my recommendation below. Please advise._

Our research indicated that they are aware of a program where they are able to apply for disability benefits prior to discharge, but I would not confidently say that the participants we spoke with were certain of the name of this program. It may be safer to spell it out for them.

_It's hard for me to provide accurate content without knowing what users see before this message and after._

Totally understand this and our apologies for being vague - please use this BDD Invision mockup to see how the app flows: 

https://vsateams.invisionapp.com/share/8GXOG91ZWNJ

Specifically, we asked about the alert for uploading your service treatment records. Here is the exact screen where that occurs:

https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421404547

Would you also please take a look at another content area where we felt like the info was really concise and helpful, but maybe you could improve?

<img width="513" alt="Screen Shot 2020-06-19 at 11 37 19 AM" src="https://user-images.githubusercontent.com/54544300/85150998-3f118880-b221-11ea-96c9-6a1296797423.png">

It's located here in the app flow: 
https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421397838

Again Peggy, thank you so much for your patience and please let me know if you need any other details to assist us in improving the language for the BDD filing process!

**Comment by peggygannon** [comment]
Hi, @kevinstachura ok, thank you for the further clarifications. I will take a look at the additional screenshots/ content you provided above. 

Thank you also for the additional user feedback on this accordion  'what happens if I miss a phone call?'  I will offer up some recommendations to make it sounds less harsh, but you should run any updated content by the VA/BDD stakeholder to make sure the Veteran can call and reschedule.

**Comment by kevinstachura** [comment]
Thanks so much @peggygannon! And we will certainly follow up with the stakeholder to understand what the process of rescheduling would look like.

**Comment by luke-gcio** [comment]
@peggygannon Are you still working on the content review? We moved this into the next sprint in case you are.

**Comment by peggygannon** [comment]
Hi, @kevinstachura and @luke-gcio Yes, I'm still working on this. I've completed content for the wizard alerts (see below). 

I will drop in content recommendations for the other screenshots by end of day today. 

WIZARD alerts
**You’re eligible to file a BDD claim**
Based on your separation date, you can file a disability claim under the Benefits Delivery at Discharge (BDD) program. This program allows service members to apply for disability benefits 180 to 90 days before they leave the military. You’ll need to be available for 45 days after you submit your claim for a VA exam.
You have [TK] days left to file a BDD claim.

[Learn more about the BDD program] (where does this link take users?)

{CTA button} File a Benefits Delivery at Discharge claim (where does this take users? )

-----

More than 180 days:
**You’re not eligible to file a BDD claim right now**
Since you have more than 180 days left on active duty, you can’t file a BDD claim at this time. You can only file a BDD claim if your separation date is within the next 180 to 90 days.
Please return in [TK] days to file a BBD claim. 

[Learn more about the BDD program] (where does this link take users?)

------

Less than 90 days
**You’re not eligible to file a BDD claim**
Since you have less than 90 days left on active duty, you can’t file a BDD claim. You can only file a BDD claim if your separation date is within the next 180 to 90 days.

However, you can start the process to file a standard disability claim.

{CTA} File a disability compensation claim (goes to https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction)

---
In-line validation error

Your separation date must be in the future

**Comment by peggygannon** [comment]
@luke-gcio and @kevinstachura followup note, I would like to look at the mockup again once the alert content has been updated.

**Comment by kevinstachura** [comment]
Hi @peggygannon! Thank you so much for providing these recommendations. I have implemented these changes. Here are where they all exist in the context of the app flow:

---

**WIZARD alerts**

You’re eligible to file a BDD claim: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421391044

More than 180 days: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421391045

Less than 90 days: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421391043

In-line validation error: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/423854062

---

We recommend you submit your service treatment records: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421404547_BDD_-_Supporting_Evidence_-_STR_Upload_Question_-_No

---

Place of anticipated separation: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421397838_BDD_Military_History_-_Filled_-_Sep_Date_Details

---

What happens if I miss a phone call: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421410781_BDD_New_Conditions_18_

Note: We will make sure to run the last sentence by our SME to ensure that it is accurate

---

Thanks again, Peggy! Please let me know if you believe any edits should be made after seeing all of the updated copy in context.

**Comment by peggygannon** [comment]
thanks, @kevinstachura I will take a look at this today!

**Comment by peggygannon** [comment]
Hi @kevinstachura I have some additional content thoughts  on the WIZARD alerts (see below). The content for the other messages look good! Let me know if you want to discuss more in on a call. Thx! 

------

1. For the first wizard alert, please make sure the content matches what I posted above. 

"You are" should be: You’re eligible to file a BDD claim

And for the CTA button, we should capitalized the program name: 

{CTA button} File a Benefits Delivery at Discharge claim (goes to BDD claim introduction page )

-----

2. For the More than 180 days alert, is this the first time a Veteran will hear about a BDD claim? Will there be a question in the wizard asking users it they **want** to file a BDD claim? 

If not, seeing this alert in context I recommend recasting this information letting them know they **will be eligible** in the future and about what the BDD program is. 

**You may be eligible to file a BDD claim**
Based on your separation date, you may be eligible to file a disability claim under the Benefits Delivery at Discharge (BDD) program. This program allows service members to apply for disability benefits 180 to 90 days before they leave the military. 
Since you have more than 180 days left on active duty, you can return in [TK] days to file a BBD claim.

[Learn more about the BDD program] (where does this link take users?)

------

3.  If there isn't a question on the wizard asking users if they **want** to file a BDD claim, do we need to even to show an alert for uses who have less than 90 days left? 


------


4. For the validation error, please capitalize the Y in "Your" separation date must be in the future

**Comment by kevinstachura** [comment]
Thanks @peggygannon! These changes should now be reflected in the Invision designs. 

In response to this:

>If there isn't a question on the wizard asking users if they want to file a BDD claim, do we need to even to show an alert for uses who have less than 90 days left?

Right, it's probably unnecessary to show an alert here. When the Service Member is less than 90 days away from separation, It's handled as a standard claim, so the user does not really need to be informed about BDD since they missed the BDD window anyhow. I can see how it may be jarring to say 'you're not eligible to file a BDD claim' and thus immediately assuming you cannot move forward, then seeing a button that states you can indeed continue with another category of 526 disability claim. 

Thanks again Peggy! We appreciate all of your hard work on this. :)
