### ISSUE TITLE
[Tech-Debt] Add new design and Suicide prevention alert to existing pages.

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10068]
## Issue description
The display of information on the [suicide prevention detail page](https://www.va.gov/pittsburgh-health-care/suicide-prevention/) is duplicative, poorly formatted and inconsistent with the design system. The crisis hotline number is displayed three separate ways. Erie has added an image for the crisis line. We need to standardize this national content for ease and risk mitigation. 

<details> 
<summary> Page screenshot </summary>

![mental health phone bug.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b102e360-71de-40eb-bf9b-52d28bb058b8)

</details>

Most content is nationalized, with the exception of some facilities which add local content for Behavioral health or community care under ongoing support. 

<details> 
<summary> Example from Erie </summary>

![erie](https://user-images.githubusercontent.com/55411834/94721908-c20fa800-0313-11eb-8c4c-5d3c52c24bf0.png)

</details> 

## Tasks
- Delete content and replace with react widget for "How do I talk to someone right now?"
- Stan will provide Clone to Pittsburgh
- [x] Altoona VA Medical Center
- [ ] (Butler)Abie Abraham VA Health Care Center (HCC)
- [x] Coatesville VA Medical Center
- [x] Erie VAMC
- [x] Lebanon VA Medical Center
- [ ] Pittsburgh VA Medical Center-University Drive 
- [x] Corporal Michael J. Crescenz VA Medical Center
- [x] Wilkes-Barre VA Medical Center
- [x] Wilmington VA Medical Center

## Acceptance Criteria
- Add Alert for How do I speak to someone now- VISN4  
- Pittsburgh/VISN 4 pages will be cloned and will have source Content added.

**Comment by mpelzsherman** [comment]
@mmiddaugh - can we get a little more detail on exactly what is needed here?

Offhand it looks to me like we should remove the “1-” before all phone numbers, since it messes with our formatting, and dialing “1" isn’t necessary any more.

The content for this page is almost entirely in Drupal, so someone with permission could go in and remove the "1-", or we could do that in our Javascript code. Would that be enough, or is there something else that needs to be done here?

**Comment by mpelzsherman** [comment]
The AC as written are already met. I am moving this back to "needs grooming" since I don't know how to proceed with it.
