### ISSUE TITLE
[Frontend] MDT - Order submission failed

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#10066]
## Issue Description
_When a Veteran places an order for hearing aid batteries and/or accessories, there is a chance that the order may not go through. We need to design a solution that alerts Veterans that their order has not been submitted and provide next steps for placing an order._

The [alert's design](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/420949180_Submission_Error) can be viewed on InVision. Additionally, you may reference MDT's GH documentation for [the alert's content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-confirmation-screen.md#description-1).

---
## Tasks
- [ ] _The alert provided in the InVision mockup is implemented to replace the confirmation screen if an attempt to submit an order results in a server error_
- [ ] _Either sync with a BaM2 designer to review the alert or provide the correct test user for the designer to view the work in staging_

## Acceptance Criteria
- [ ] _The alert is implemented and matches the styling in the provided InVision mockup_
- [ ] _A BaM2 designer has reviewed and approved the alert styling_

---

**Comment by mr0sari0** [comment]
The PR for this is ready. https://github.com/department-of-veterans-affairs/vets-website/pull/13346.  This will have to be revisited once @camerontesterman is back, to make sure I'm grabbing the correct error props.

**Comment by mr0sari0** [comment]
Working with @camerontesterman to implement the correct error data properties.
