### ISSUE TITLE
[Frontend] MDT - Empty states for hearing aid batteries and accessories on the order review screen

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10075]
## Issue Description
Some Veterans may only need to order either hearing aid batteries or accessories, so we need to provide empty states on that portion of the review screen if they don't select items for both categories. Another empty state variation should also be shown if a Veteran hasn't selected any items from each category because they are ineligible to do so.

**Invision prototypes:**
[Empty states for when a Veteran is eligible to order within their categories](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/421066122_C3-_Review_-_Supply_Empty_State-_Eligible)
[Empty states for when a Veteran is not eligible to order within their categories](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/421066123_C3-_Review_-_Supply_Empty_State-_Ineligible)

---
## Tasks
- [ ] _Create the empty states for both ineligible and eligible products on the review screen
- [ ] _Either sync with a BaM2 designer to review the empty states or provide the correct test user for the designer to view the work in staging_

## Acceptance Criteria
- [ ] _The empty states are implemented and matches the styling in the provided InVision mockup_
- [ ] _A BaM2 designer has reviewed and approved the empty state styling_
---

**Comment by mr0sari0** [comment]
Hey @rebeccawalsh , I'm having trouble viewing your link for empty states for when a Veteran is not eligible to order within their categories. [Is this the correct mockup](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/421066123) for that case? Also what is supposed to happen when you click on add batteries/accessories to your order?

**Comment by rebeccawalsh** [comment]
@mr0sari0 Yes. And to be clear, a user should never see both of those 'You can't add ____ to your order due to ineligibility' messages at the same time, they're just together to illustrate both messages.

**Comment by mr0sari0** [comment]
@rebeccawalsh Got it!  And about the links to adding the product? Will that be similar to the edit button where it displays all of the products?

**Comment by rebeccawalsh** [comment]
@mr0sari0 Yes!

**Comment by mr0sari0** [comment]
@rebeccawalsh Is the redundancy needed for a certain reason?

**Comment by rebeccawalsh** [comment]
@mr0sari0 It's to make the path to adding products a little more obvious and it is consistent with empty states on other parts of the site, where it has a link to "Add" something.

**Comment by mr0sari0** [comment]
@rebeccawalsh The PR for this is created. Just let me know how you want to review.

**Comment by mr0sari0** [comment]
Received design team approval. This PR has been merged to `master`.
