### ISSUE TITLE
[Frontend] MDT - Combine battery and accessory selection pages into one

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10108]
## Issue Description
In order to prevent users from submitting empty orders, we need to combine all supplies onto a single page. The goal is to prevent Veterans from proceeding if no supplies are selected on both the initial form page and the Review page.

*Proposed design:*
![combined-supplies.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/09068743-5ca6-4a9b-a960-4c7df45f4dcb)

---
## Tasks
- [ ] Combine the two pages and make minor content adjustments
- [ ] Confirm work with designers

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
