### ISSUE TITLE
Medical devices: Create Drupal pages with approved URLs and IA placement

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#10110]
## Issue Description
The current page, https://www.va.gov/health-care/order-hearing-aid-batteries-prosthetic-socks/, will be split into two (one for ordering hearing aid supplies and the other for prosthetic socks). The new hearing aid supplies page will point to the new static landing page for Form 2346 (ordering hearing aid supplies) currently in staging.

**Relevant Documentation/Mockups**
- [Unauthenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077289_Content_Page_-_Unauthenticated_-_Desktop)
- [Authenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077290_Content_Page_-_Authenticated_-_Desktop)
---
## Tasks
- [x] _Create Order Prosthetic Socks page_
- [x] _Create Order Hearing Aid Batteries and Accessories page_
- [x] _Include react widgets and correct cross links on pages_
- [x] _Send drafts to Copy Editor for review_
- [x] Move menu links (after publishing)

## Acceptance Criteria
- [x] _Drupal pages have been created_
- [x] _Cross links and react widget are validated as working correctly_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Here are the draft drupal pages:
- http://preview-prod.vfs.va.gov/preview?nodeId=5681
- http://preview-prod.vfs.va.gov/preview?nodeId=36

Awaiting Danielle's review.

**Comment by leahkeeler** [comment]
Hi, Is there any update on this? coordinating launch date :) Thanks! Leah

**Comment by lunascoop** [comment]
Hi @leahkeeler we are in the process of creating the react widgets for the page. Then, I'll update pages. We can schedule a meeting to review everything. Do you have a projected launch date?

**Comment by MickinSahni** [comment]
Carryover to sprint 25 as we're waiting for DLC approval

**Comment by MickinSahni** [comment]
> Carryover to sprint 25 as we're waiting for DLC approval

@lunascoop are we still waiting for feedback? if so, can you add the label back on?

**Comment by leahkeeler** [comment]
@MickinSahni Yes still waiting for go-live. They are running network tests with promise to let me know by noon tomorrow - they do think they solved the problem.

**Comment by lunascoop** [comment]
The majority of the work for this ticket is completed. We have to wait until the page is published before moving the menu links. New launch date is 07/15.

**Comment by MickinSahni** [comment]
moving this to PW Sprint 26 to coincide with the new launch date

remaining work: the menu links (which is dependent on the page being published)

**Comment by MickinSahni** [comment]
@lunascoop can you add a blocker ticket to this one (prob the redirect that we talked about)

**Comment by MickinSahni** [comment]
moving to sprint 26 to account for blocker

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @lunascoop. As you probably saw in PW channel, Leah confirmed that we can publish these pages for tomorrow's (7/15) deploy. Could you please publish and coordinate redirect? Thank you!

FYSA @MickinSahni

**Comment by RLHecht** [comment]
@lunascoop @leahkeeler @DanielleThierryUSDSVA These two pages were published and the menu links and URLS updated. Should be live by late this afternoon after the deploy. Moving ticket to validate.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much, @RLHecht!

**Comment by lunascoop** [comment]
Pages were published on 07/15 with proper IA placement.
