### ISSUE TITLE
Remove vanity number from education pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#10117]
## User story
As a content editor I need to make sure all content adheres to the VA.gov style guide.

## Issue Description
A vanity number appears at the bottom of the [REAP](https://www.va.gov/education/other-va-education-benefits/reap) and in the [Post-9/11 GI Bill Statement of Benefits](https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/index.html) pages. 

## Tasks
- [x] Delete vanity number from REAP page
- [x] Delete vanity number from Statement of Benefits page

## Acceptance Criteria
- [x] Regular phone number appears on live site.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpotts I found a vanity number while searching through pages for VR&E info. Created this issue just to document it. Moving to validate. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
Changes validated on live site. Closing ticket. FYSA @stephorkandatx
