### ISSUE TITLE
Cap the word Program in Yellow Ribbon Program link on Opt out of information page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#10113]
## User Story

As a content editor on Public Websites I need to ensure all copy adheres to the VA.gov style guide.

## Issue Description
Yellow Ribbon Program should be capitalized per our style guide. "Program" was lowercased in the link on the [Opt out of sharing education benefits information](https://www.va.gov/education/opt-out-information-sharing/) page.

---
## Tasks
- [x] Capitalize Program in link on page

## Acceptance Criteria
- [x] Program is capitalized on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpotts Found a style guide error while searching for VR&E content. I updated the page and am moving to validate. Created this ticket just to document it. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
Changes validated on live site. Closing ticket. FYSA @stephorkandatx
