### ISSUE TITLE
[Discovery] Logged-in homepage: Review journey maps

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10120]
## Background

Now that project discovery is complete, Tressa needs to get onboarded to all that we learned! Among other things, I think it would super helpful to review some of the journey maps we uncovered in our past research review to create the context for some of the logged-in homepage use cases.

## Tasks

[Journey maps are here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/previous-research-review.md#journey-maps).

- [x] Review Veteran Journey Map.
- [x] Review VA patient experience map.
- [x] Review Disabilities claim process map.
- [x] Review Education benefits map.
- [x] Review Pension journey map.

## Acceptance criteria

- [x] All maps have been reviewed and Tressa feels like she has a grasp of these veteran experiences.
