### ISSUE TITLE
[Discovery] Content model: Jobs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10128]
## Issue Description
There is an opportunity to harden the content model for Jobs content displayed on VAMC pages

View https://www.altoona.va.gov/careers/index.asp: the content displayed within the VA Job Applications and Forms box is all national, including the 7 PDFs which are currently replicated across hundreds of sites. There may be an opportunity to direct toward one page which houses the forms at a VISN level. 

Creation of a forms detail page is currently in progress with CMS. In the future, Drupal could serve up this page in response to a search and create a landing page. Content could reference/link to this VISN specific landing page. 

---
## Tasks
- [ ] Jobs content structure POC 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
Jobs have not been hardened, still valid.
