### ISSUE TITLE
Update to remove IRIS from hub right rail, detail pages & FAQs

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10125]
## Issue Description
IRIS is going away at the end of the June, 2020. 
We currently link to IRIS on VA.gov in various content - in all the hubs' right rail components ("Ask a Question" link), Coronavirus FAQs, and various benefit detail pages. This list may not be exhaustive.

Note: for the Coronavirus FAQs, Danielle will do the work & Randi to review

~~Note: please reach out to Chante to see if they have a place where they want to redirect people, for links that we may not be able to catch~~ (Update 06/17/2020: Chante responded in Slack that there is no replacement, and at the moment the answer is 'no'. People will have to call the contact center that handles their specific problem)

**Example hub right rail:**
![image (8)](https://user-images.githubusercontent.com/63361321/84689396-88529700-af06-11ea-8a6f-0875c83376be.png)

**Example global utility 'contact us' menu:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/3dba6301-af3a-4240-aac5-05b16515b26f)

When it is time, we will need to make content updates to remove links for IRIS, so that we do not provide users to a system that is no longer in use.

---
## Tasks
- [x] Create a list of IRIS links on VA.gov - this should become our checklist of touchpoints
- [ ] Remove IRIS links from found areas of site, minus Coronavirus FAQs (Anne)
- [ ] Remove IRIS link(s) from Coronavirus FAQs (Danielle, Randi)
- [ ] Remove IRIS link from global utility 'contact us' menu dropdown <-- added 6/23 see screenshot
- [ ] Remove "Ask a question" IRIS link in global footer <-- added 6/24
- [ ] Before go-live, reach out to Chante to confirm the list of changes and ensure Contact Center is aware, ready for the changes
- [ ] Publish pages that have been updated (Randi)

## Acceptance Criteria
- [ ] Links to IRIS have been removed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
Here are my search results for this -

| Page | Search term (includes non-visible HTML) |
| ---| --- |
| /careers-employment/ | iris.custhelp.va.gov |
| /records/ | iris.custhelp.va.gov |
| /life-insurance/ | iris.custhelp.va.gov |
| /service-member-benefits/ | iris.custhelp.va.gov |
| /housing-assistance/ | iris.custhelp.va.gov |
| /burials-memorials/ | iris.custhelp.va.gov |
| /pension/ | iris.custhelp.va.gov |
| /decision-reviews/ | iris.custhelp.va.gov |
| /family-member-benefits/ | iris.custhelp.va.gov |
| /disability/ | iris.custhelp.va.gov |
| /change-address/ | iris.custhelp.va.gov |
| /education/ | iris.custhelp.va.gov |
| /coronavirus-veteran-frequently-asked-questions/ | iris.custhelp.va.gov |

**Comment by AnneHurley** [comment]
@bethpottsVADEPO  @stephorkandatx @ncksllvn - CMS team is standing by to take the reference out of all the hub right rails - all the pages listed above except the Coronavirus FAQ . I'll check in with Chante on June 28 or 29 to see if we have the green light to remove them, and as soon as she gives it, the team can push pages live w/o it.
@jenniferlee-dsva  FYSA

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx @ncksllvn @clantosswett - Updated ticket with 1 more location where IRIS link needs to be removed. It's a global utility nav, so requires FE engineering to update I believe... but not 100.

**Comment by jenniferlee-dsva** [comment]
Please also see new related[ ticket 10592 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10592)

**Comment by stephorkandatx** [comment]
For the global utility nav, I'll get this reviewed today to determine the support we need for the update

**Comment by jenniferlee-dsva** [comment]
Note - I didn't see the footer link identified above, so just added it as one of the places that also need to have IRIS link removed. 

- [ ] Remove "Ask a question" IRIS link in global footer <-- added 6/24

@stephorkandatx @ncksllvn @clantosswett

**Comment by stephorkandatx** [comment]
@ncksllvn and @AnneHurley how soon can we remove these links? Discussion in the related ticket indicates we can stagger. I am not sure we would be able to make today's deploy window but would love your thoughts on when we'd be able to make the changes.

Other ticket's comment at https://github.com/department-of-veterans-affairs/va.gov-team/issues/10592#issuecomment-649583475

FYSA @clantosswett

**Comment by ncksllvn** [comment]
We can probably have them removed in today's deploy if we act soon

**Comment by bethpottsVADEPO** [comment]
@clantosswett I wanted to confirm with you, since there are two tickets going and I don't want anything to get lost, that we should remove all IRIS links 6/26. That's what I see in your comment in https://github.com/department-of-veterans-affairs/va.gov-team/issues/10592#issuecomment-649583475

@stephorkandatx @ncksllvn Who will own these two tasks that @jenniferlee-dsva added to the top of the ticket (Tasks). Currently they don't have an owner:

- Remove IRIS link from global utility 'contact us' menu dropdown <-- added 6/23 see screenshot
- Remove "Ask a question" IRIS link in global footer <-- added 6/24

**Comment by stephorkandatx** [comment]
@bethpottsVADEPO the two tasks in question ^^ are FE items, and @ncksllvn would need to set that up for us.

**Comment by ncksllvn** [comment]
Oof, so there are more references to Iris in the frontend code than I anticipated. I should have done a search sooner. 

## Claims and Appeals 

![image](https://user-images.githubusercontent.com/1915775/85744262-c142f680-b6d2-11ea-8b6b-0e899cfd06d3.png)


## Letters
![image](https://user-images.githubusercontent.com/1915775/85744301-c99b3180-b6d2-11ea-9489-4f3b7e5b7397.png)


## Profile

### Military info
 
![image](https://user-images.githubusercontent.com/1915775/85744376-d9b31100-b6d2-11ea-9cb0-09542600e5fd.png)

### SSN error (appears several times)
![image](https://user-images.githubusercontent.com/1915775/85744473-ed5e7780-b6d2-11ea-967b-2949540f76d2.png)

**Comment by stephorkandatx** [comment]
@ncksllvn can you confirm that you'll be removing from the detail pages, right rail as well as global util nav + footer? talking to Anne, sounds like those are also FE tasks. If we can remove them all via FE that would be great

**Comment by ncksllvn** [comment]
@stephorkandatx Yep! Removing from the util nav, footer, right rail, and instances across the frontend applications - https://github.com/department-of-veterans-affairs/vets-website/pull/13181

**Comment by AnneHurley** [comment]
@ncksllvn @stephorkandatx @RLHecht  - Have found 1 instance of IRIS in body of a Drupal page, and it's now removed, and saved as draft. Ready for copyedit, Randi. Holding off on publish till Chante gives @bethpottsVADEPO  the heads up.

http://preview-prod.vfs.va.gov/preview?nodeId=709

Was the 2nd bullet in CHAMPVA section, now removed.

**Comment by RLHecht** [comment]
@AnneHurley This looks OK to me. Just let me know when we should publish.

**Comment by clantosswett** [comment]
@jenniferlee-dsva @bethpotts @ncksllvn Chiming in to confirm that it would be ideal for links to IRIS to be removed on Friday 6/26 along with the publishing of the redirect page. What is most important is that the redirect page is live so that even if the links are still available, users will not be taken to IRIS. If it would help the team to push back the link removals to a later date, just let me know so I can notify stakeholders of this and confirm this isn't a problem.

**Comment by bethpottsVADEPO** [comment]
@clantosswett Thanks for the confirmation! @ncksllvn can correct me if I'm wrong, but when he and I spoke this morning, it seemed like he'd be able to get the FE work done for deployment tomorrow. And Anne has found only that once instance in running text on a drupal page. @RLHecht, can you make sure that publishes on Friday? So we should be good to go for getting all the links removed tomorrow.

**Comment by bethpottsVADEPO** [comment]
@stephorkandatx @jenniferlee-dsva @ncksllvn @RLHecht @DanielleSoCompany @clantosswett The relevant folks involved in this work have been on calls this morning, but just confirming here too that we  are pressing pause on removing links to IRIS until we know for sure the program is getting retired at the end of June. There is the possibility the contract will be extended. Thanks, everyone!

**Comment by MickinSahni** [comment]
Removing from sprint 24

**Comment by MickinSahni** [comment]
Keeping in Icebox until we're able to groom or close cuz we're not going to do it.

**Comment by RLHecht** [comment]
Closing this very old ticket as the new one #26562 carries over the work still needed to be done.
