### ISSUE TITLE
[Discovery] Logged-in homepage: Review discovery findings

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10121]
## Background

Now that project discovery is complete, Tressa needs to get onboarded to all that we learned! 

## Tasks

- [x] Review the [user research write up](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/user-research/findings-summary.md).
- [x] Review the [final discovery write up](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/discovery-summary.md).

## Acceptance criteria

- [x] Tressa feels familiar with both of the docs above.
