### ISSUE TITLE
Facility Locator API Audit

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10129]
## Issue Description
Following a meeting today with representatives from VSP, Lighthouse, VAOS and Facilities teams, it has been requested that all traffic go through vets-api rather than directly from front end. This is so that traffic flows through the VA.gov filter and monitoring.

---
## Tasks
- [ ] Audit the calls made by Facility Locator to determine which items are not going through vets-api (ie Mapbox) 

## Acceptance Criteria
- [ ] Documentation of calls made by Facility Locator and their endpoints
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
All endpoints are documented in the [Facility Locator Technical diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/technical%20documentation.md#technical-diagrams)
