### ISSUE TITLE
Coronavirus in-body alert update on Claim exams page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10132]
# User story

As a Veteran who has submitted a claim for disability or pension benefits, I need to know how to complete my claim exam during the coronavirus pandemic.

# Details

## Issue description
We need to update the existing alert on the Claim exam page to link Veterans to the latest information about claim exams during the pandemic.

---
## Tasks
- [x] Edit alert content from VBA (Danielle)
- [x] Work with Sandy Tadeo to get alert content approved (Danielle)
- [x] Update alert content in Drupal (Danielle)
- [x] Check and publish alert in Drupal (Randi)

## Acceptance Criteria
- [x] Updated alert is validated on live site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I've added the approved alert (as shown below). But in the preview, it's appearing twice. Could you please take a look and a) make sure the content has no errors and b) help me figure out why it's appearing twice? Thank you!

preview-prod.vfs.va.gov/preview?nodeId-914

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/0fce90de-942f-4da2-83a5-6624c7fc21f0)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This is now fixed. Turns out you had two alerts in there.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht! Can you show me the details? I ask because I kept trying to figure out if I had two in there and was only seeing one in the editing view.

**Comment by DanielleThierryUSDSVA** [comment]
Validated on site.
