### ISSUE TITLE
[Analytics] Research and load coordinator workbook w/ Staff profiles for VA Sheridan health Care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10141]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local providers/caregivers information in the health service programs, so I know who to contact to start my healthcare journey.

## Goal
_Highlight the Individual points of contact for each Health Service Program_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Caregiver/POC Roster-spreadsheet](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[Cargiver/Coordinator Workbook](https://drive.google.com/drive/folders/1Aric8sLU7iq465_20MDlBa9ruwMOHCm9)

## Tasks
_Compile staff profiles needed to load into Drupal/CMS related Staff-Profile content pages_
- [ ] Leadership [Can simply list URL if needed]
- [ ] Caregiver-support
- [ ] Homeless-Veteran-Care
- [ ] LGBT-Veteran-Care
- [ ] Mental-Health_Care
- [ ] Minority-Veteran-Care
- [ ] Patient-Advocates
- [ ] Returning-Service-Member-Care
- [ ] Suicide-Prevention
- [ ] Women-Veteran-Care
* Spreadsheet must highlight the main areas of information, THAT will BE TRANSFERRED TO Profile page_
* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program, but only have to be loaded in Staff Profile once!

## Acceptance Criteria
Staff Profiles for the (Minimum of one profile) have been recorded in related system sheet so they can be loaded into CMS/Drupal Staff profile page (See Data-Load Story) for the following areas:
* Caregiver-support
* Homeless-Veteran-Care
* LGBT-Veteran-Care
* Mental-Health_Care
* Minority-Veteran-Care
* Patient-Advocates
* Returning-Service-Member-Care
* Suicide-Prevention
* Women-Veteran-Care
