### ISSUE TITLE
[DATA-LOAD] Load all data collected for  "VA Salt Lake City" facilities pages into related Facility pages in CMS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10147]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties page, so that it highlights travel, parking, lodging, local amenities, hours of operation, health services, and non-health services offered. 

## Goal
_Highlight the Individual FACILITY'S Page with veteran needed information_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 4 System Playbooks and Facility Data](https://drive.google.com/drive/folders/126o9eJ4IRDAQb30So1LqE5tWV6T9lHkC)

## Tasks
_Complete load of data from spreadsheet to CMS related facilities listed below:_
- [x] Elko VA Clinic
- [x] George E. Wahlen VA Medical Center
- [x] Idaho Falls VA Clinic
- [x] Ogden VA Clinic
- [x] Orem VA Clinic
- [x] Pocatello VA Clinic
- [x] Price VA Clinic
- [x] Roosevelt VA Clinic
- [x] St. George VA Clinic
- [x] Weber County VA Clinic
- [x] Western Salt Lake VA Clinic
- * Spreadsheet will highlight the main areas of information, THAT MUST BE TRANSFERRED TO Facilities detail page
- [x] Parking
- [x] Transportation
- [x] Confirm social media accounts (facebook, twitter, etc)  
*If facebook, twitter are not listed or are not correct, update this on main system page (i.e.'System page')

## Acceptance Criteria

* Accordions are created with correct title listed in data.
* Load data from spreadsheet into facility page.
* Facebook and twitter are updated
