### ISSUE TITLE
[DATA-LOAD] Load data for all "Eastern Colorado" facilities pages into related Facility pages in CMS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10142]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties page, so that it highlights travel, parking, lodging, local amenities, hours of operation, health services, and non-health services offered. 

## Goal
_Highlight the Individual FACILITY'S Page with veteran needed information_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 4 System Playbooks and Facility Data](https://drive.google.com/drive/folders/126o9eJ4IRDAQb30So1LqE5tWV6T9lHkC)

## Tasks
_Complete load of data from spreadsheet to CMS related facilities listed below:_
- [x]  Alamosa VA Clinic
- [x]  Eastern Colorado VA Medical Center
- [x]  Aurora VA Clinic
- [x]  Burlington VA Clinic
- [x]  Denver VA Clinic
- [x]  Denver CRRC VA Clinic
- [x]  Golden VA Clinic
- [x]  Jewell VA Clinic
- [x]  La Junta VA Clinic
- [x] Lamar VA Clinic
- [x]  PFC Floyd D. Lindstrom Dept. of Veterans Affairs Clinic
- [x]  PFC James Dunn VA Clinic
- [x]  Salida VA Clinic
- [x]  York Street VA Clinic
- * Spreadsheet will highlight the main areas of information, THAT MUST BE TRANSFERRED TO Facilities detail page
- [x] Parking
- [x] Transportation
- [x] Confirm social media accounts (facebook, twitter, etc)  
*If facebook, twitter are not listed or are not correct, update this on main system page (i.e.'System page')

## Acceptance Criteria

* Accordions are created with correct title listed in data.
* Load data from spreadsheet into facility page.
* Facebook and twitter are updated
