### ISSUE TITLE
[DATA-LOAD] Load all data for all "Western Colorado" facilities pages into related Facility pages in CMS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10143]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties page, so that it highlights travel, parking, lodging, local amenities, hours of operation, health services, and non-health services offered. 

## Goal
_Highlight the Individual FACILITY'S Page with veteran needed information_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 4 System Playbooks and Facility Data](https://drive.google.com/drive/folders/126o9eJ4IRDAQb30So1LqE5tWV6T9lHkC)

## Tasks
_Complete load of data from spreadsheet to CMS related facilities listed below:_
- [x]  Western Colorado VA Medical Center
- [x]  Glenwood Springs VA Clinic
- [x]  Grand Junction VA Mobile Clinic
- [x]  Major William Edward Adams Department o Veterans Affairs Clinic
- [x]  Moab VA Clinic
- [x]  Montrose VA Clinic

- * Spreadsheet will highlight the main areas of information, THAT MUST BE TRANSFERRED TO Facilities detail page
- [x] Parking
- [x] Transportation
- [x] Confirm social media accounts (facebook, twitter, etc)  
*If facebook, twitter are not listed or are not correct, update this on main system page (i.e.'System page')

## Acceptance Criteria

* Accordions are created with correct title listed in data.
* Load data from spreadsheet into facility page.
* Facebook and twitter are updated
