### ISSUE TITLE
CT: Improve Text Search Functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10151]
As a Comparison Tool user, I need to be able to find institutions that I am looking for when using common aliases (ex. UCLA) or have slight misspellings so that I have a better user experience when using the tool.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DSVA and EDU.

## Acceptance Criteria
1. All linked stories have been implemented and tested

## VSP Collaboration Cycle.
- [x] Project Kickoff - #11028
- [x] Design Intent Collaboration - #10996 
- [x] Usability Testing Prep - #11707 
- [x] Research Plan Review - Completed 07/30
- [ ] ~Information Architecture (IA) Request~
- [ ] ~Analytics Request~
- [ ] ~Contact Center Review~
- [ ] ~Staging Review~
- [ ] ~Privacy and Security Review~
- [ ] ~Full Accessibility and 508 Office Audit~
- [ ] ~Post-launch Check-in~

## Supporting Artifacts

**Comment by dneel-bah** [comment]
All necessary collab points have been completed based on project kickoff discussions.
