### ISSUE TITLE
CT: Improve Filtering Functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10155]
As an Comparison Tool user, I would like to filter on additional attributes about an institution (similar to the college scorecard) so that I can make a more informed decision about where I would like to use my education benefits.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work follows the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Acceptance Criteria
1. All linked stories have been implemented and tested.

## VSP Collaboration Cycle.
- [x] Project Kickoff - #11028
- [x] Design Intent Collaboration - #10996 
- [x] Usability Testing Prep - #11707 
- [x] Research Plan Review Completed 07/30
- [ ] ~Information Architecture (IA) Request~
- [ ] ~Analytics Request~
- [ ] ~Contact Center Review~
- [ ] ~Staging Review~
- [ ] ~Privacy and Security Review~
- [ ] ~Full Accessibility and 508 Office Audit~
- [ ] ~Post-launch Check-in~

## Supporting Artifacts
1. TBD

**Comment by dneel-bah** [comment]
All necessary collab points have been completed based on project kickoff discussions.
