### ISSUE TITLE
[Design] Logged-in homepage: Plan for LOA3 use cases

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10162]
## Background

One of the biggest challenges about designing for the logged-in homepage will be making sure we properly account for all of the use cases we plan to include in V1. I think the easiest way to make sure everything is accounted for is to make a list or spreadsheet of how we plan to handle all use cases. This doesn't need to involve any design; it's more of an outline to make sure that when design starts, we know exactly what needs to be included and what doesn't, and we can make sure we aren't leaving our FE devs with holes in the code.

### Starting with LOA3

The LOA3 use case is going to be much more complex than the LOA1 use case, so let's start here. In fact, the LOA1 use case will probably take a good portion of it's design from elements of the LOA3 design, so that will be 90% figured out once all the LOA3 use cases are outlined.

### What we need to define

I see this as an artifact that works something like this:

- Define the use cases we've scoped for V1 of the logged-in homepage.
- Based on those use cases, define how we'll handle the UI.

Here are a couple examples:

Example 1

As a user who has a disability rating, I expect to see:
- My overall disability rating.
- A link to view all ratings. 

As a user who does not have a disability rating, I expect to see:
- A link to file a claim.

Example 2

As a user who has prescriptions at the VA, I expect to see:
- A list of in-progress prescriptions.
- Messaging if I have no prescriptions in progress.
- A link to view all of my prescriptions.

As a user who does not have prescriptions at the VA, I expect to see:
- Nothing about prescriptions.

## Tasks

- [x] Create a list of all the use cases we plan to handle for V1 of the logged-in homepage for LOA3 users.
  - Make sure to handle all error cases, too.
  - Make sure to handle what to do if someone has no benefits/no apps or claims in progress.
- [x] For each use case, make a list of how we will handle that use case in the UI based on user expectations (as outlined above).
- [ ] Review list with team.
- [ ] Refine as necessary.
- [ ] Save final copy of this list in [the project's design folder on Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia).

## Acceptance criteria

- [ ] All LOA3 use cases have been outlined, documented, and saved in the project folder on Github.

**Comment by Samara-Strauss** [comment]
@tressaellen @callen2563 @sshein @mshea0606 

[This is my ideal plan for V1 of the logged-in homepage](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/v1-plan.md). Take a look, and let me know your questions.

What I think we should do from here:

- Review this list. We can review together if you have questions.
- Start working **together** on user stories before creating a spreadsheet that details data points or conditionals for each feature. I'd love to help you get started with this in a collaborative meeting. I think if we can put into human language what people expect, things will be a lot clearer for you both.
- THEN, once we have expectations put into human language, it'll be much easier for you all to create a spreadsheet of data points and conditionals.

How does this sound? I'll ping you all in Slack and we can figure out a time to get on the calendar to start defining user stories.

**Comment by tressaellen** [comment]
[User Story Mural Board](https://app.mural.co/t/vsa0499/m/vsa0499/1597156877591/25248822b34df6bbf8041a9b11b3150974e51efb)

**Comment by tressaellen** [comment]
[LOA3 Use Cases](https://docs.google.com/spreadsheets/d/1fO3VxUj8U2M268GnpmNmlL8Jdl8E1as33SzuwoTneV8/edit#gid=2042293003)

[Mural Board](https://app.mural.co/t/vsa0499/m/vsa0499/1597156877591/25248822b34df6bbf8041a9b11b3150974e51efb)

**Comment by tressaellen** [comment]
I dropped everything into [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/LIH%20data%20points.md)
