### ISSUE TITLE
[Design] Logged-in homepage: Plan for LOA1 use cases

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10164]
## Background

One of the biggest challenges about designing for the logged-in homepage will be making sure we properly account for all of the use cases we plan to include in V1. I think the easiest way to make sure everything is accounted for is to make a list of how we plan to handle all use cases. This doesn't need to involve any design; it's more of an outline to make sure that when design starts, we know exactly what needs to be included and what doesn't, and we can make sure we aren't leaving our FE devs with holes in the code.

## LOA1

This is going to be a lot easier than the LOA3 use case we're tracking in #10162 since the LOA1 use case is so limited. Also, some of the use cases will have already been figured out with the LOA3 plan (eg. what to show users with applications in progress).

## Tasks

- [ ] Create a list of all the use cases we plan to handle for V1 of the logged-in homepage for LOA1 users.
  - Make sure to handle all error cases, too.
  - Make sure to handle what to do if someone has no apps or claims in progress (remember we won't be able to detect if they have benefits or not at this level).
- [ ] For each use case, make a list of how we will handle that use case in the UI based on user expectations (as outlined above).
- [ ] Review list with team.
- [ ] Refine as necessary.
- [ ] Save final copy of this list in [the project's design folder on Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia).

## Acceptance criteria

- [ ] All LOA1 use cases have been outlined, documented, and saved in the project folder on Github.

**Comment by tressaellen** [comment]
[LOA1 Use Cases](https://docs.google.com/spreadsheets/d/1fO3VxUj8U2M268GnpmNmlL8Jdl8E1as33SzuwoTneV8/edit#gid=970982254)

[Mural Board](https://app.mural.co/t/vsa0499/m/vsa0499/1597156877591/25248822b34df6bbf8041a9b11b3150974e51efb)

**Comment by tressaellen** [comment]
I dropped everything into [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/LIH%20data%20points.md)
