### ISSUE TITLE
Zeitwerk Inflections & PR break out

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#10165]
## Issue Description
By default, Rails camelizes constants to know which constant a given file or directory name should define. Ex: VA vs Va(would be the rails default). With the heavy usage of acronyms across the platform, many files and directories within vets-api do not get inflected as we'd like them to. This requires defining custom inflections for acronym usage. 

The goal for this ticket is to break out the inflection work related to the [Zeitwerk PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4379). This will allow for the various concepts of the PR to be broken into smaller pieces for developer understanding and easier rollback if an issue were to occur upon deployment. 

---
## Tasks
- [x] Separate Inflection work into a new PR from the [Zeitwerk PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4379)
- [x] Define VA acronyms used in vets-api as custom inflections
- [x] Review PDF issues with VA vs Va Inflection

## Acceptance Criteria
- [x] Specs pass
- [x] Inflection pieces of the Zeitwerk PR are broken into a smaller PR

**Comment by erluti** [comment]
From working through this a the first time, a couple "gotchas" I found...
1 - Do `VAOS` before `VA` (and list them in the inflections file in that order)
2 - Zeitwerk doesn't consider a number as the start of a "word" unless it is after an `_`, so it confused some inflections and for example form_profiles files had to be renamed like this: `app/models/form_profiles/va0993.rb → app/models/form_profiles/va_0993.rb`

**Comment by erluti** [comment]
VAOS is already an inflection, but some files are not inflected https://github.com/department-of-veterans-affairs/vets-api/pull/4379/commits/873fbe524e43986965b9d232d5a04c4776466373

**Comment by erluti** [comment]
> VAOS is already an inflection, but some files are not inflected [department-of-veterans-affairs/vets-api@873fbe5](https://github.com/department-of-veterans-affairs/vets-api/commit/873fbe524e43986965b9d232d5a04c4776466373)

It looks like those VAOS changes were unnecessary.  Reverting them doesn't stop tests from passing
