### ISSUE TITLE
[PM] Logged-in homepage: Define scope for V1

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10176]
## Background

Now that we are past discovery, it's time to settle on what is in and out of scope for V1. I have an idea of this and will present it to the team, get feedback, and refine the list as necessary.

[V1 plan]()

## Tasks

- [x] Present plan to auth exp team.
- [x] Present plan to DEPO team. #10177
- [x] Review with Chris J.
- [x] Refine as necessary.

## Acceptance criteria

- [x] We have a general list of features that are in-scope and out-of-scope for V1 (note: some specifics may be pending further technical discovery).

**Comment by Samara-Strauss** [comment]
The plan has been reviewed with the auth exp team, DEPO, and Chris J, and all have approved it. [This is the high-level initial plan pending discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/README.md#june-2020).
