### ISSUE TITLE
PR for adding Internal/External namespacing to exceptions in lib

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#10173]
## Issue Description
Zeitwerk mode uncovered many namespacing issues in relation to the vets-api codebase. In particular, many of our Common Exceptions were namespaced within Internal/External namspaces, but were missing the namespacing logic to include ::Internal/::External across the codebase. In order for Zeitwerk mode to autoload correctly, the namespacing updates are necessary. 

This PR details why namespacing is an important concept and therefore it should be broken into it's own PR from the [Zeitwerk PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4379)

[Example](https://github.com/department-of-veterans-affairs/vets-api/pull/4379/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eR71)

---
## Tasks
- [ ] Break Internal/External Namespacing changes into a separate PR
- [ ] Define the Internal and External Namespacing within the lib directory
- [ ] Update calls to the common exception classes to include the new namespacing
- [ ] Check out Rakelib

## Acceptance Criteria
- [ ] Specs pass
---

**Comment by erluti** [comment]
The `lib/common/exceptions` file was used to load all the different exceptions, so when doing this for the first zeitwerk attempt I used this file to create the module namespace and used `Dir` to load all the child exceptions

Code here:
https://github.com/department-of-veterans-affairs/vets-api/blob/43bf85115375935d43e4a109eb681c8a9440581d/lib/common/exceptions.rb
