### ISSUE TITLE
[ANALYTICS] Research and document Facility page information for "VA Western Colorado" health care facilities

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10188]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties page, so that it highlights travel, parking, lodging, local amenities, hours of operation, health services, and non-health services offered. 

## Goal
_Highlight the Individual FACILITY'S Page with veteran needed information_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 19 System Playbooks and Facility Data](https://drive.google.com/drive/folders/18c9fpui7dMr5LRnkhziw1GPXw9NoXAWT)

## Tasks
_Complete research of data for the following facilities listed below:_
- [ ] Glenwood Springs VA Clinic
- [ ] Grand Junction VA Medical Center
- [ ] Major William Edward Adams VA Clinic
- [ ] Moab VA Clinic
- [ ] Montrose VA Clinic

* Load data in spreadsheet and highlight the main areas of information, 
- [ ] Parking (Confirm Free, ADA access, any Special)
- [ ] Special non-health services (Chaplain, etc)
- [ ] Confirm social media accounts (facebook, twitter, etc)

## Acceptance Criteria

* Parking (Confirm Free, ADA access, any Special)
* Special non-health services (Chaplain, etc)
* Confirm social media accounts (facebook, twitter, etc)
