### ISSUE TITLE
Stop autoloading lib directory

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#10181]
## Issue Description
Standard Rails practice is to not autoload the lib directory.  Since we do, it causes some disruption in switching over to zeitwerk.  So we're going to do the work to keep in step with Rails convention and have less configuration.

This code can be removed from `config/application.rb`:
```
paths_name = Rails.env.development? ? 'autoload' : 'eager_load'
config.public_send("#{paths_name}_paths") << Rails.root.join('lib')
config.eager_load_paths << Rails.root.join('app')
```

perhaps a helpful reference is the [first attempt at using zeitwerk](https://github.com/department-of-veterans-affairs/vets-api/pull/4379)

---
## Tasks
- [ ] remove autoloading of lib directory
- [ ] require lib files manually in places that use them

## Acceptance Criteria
- [ ] tests pass without autoloading the `lib` directory
---

**Comment by erluti** [comment]
duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/10170
