### ISSUE TITLE
[ANALYTICS] Research and document Facility page information for "VA Salt Lake City" health care facilities

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10194]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties page, so that it highlights travel, parking, lodging, local amenities, hours of operation, health services, and non-health services offered. 

## Goal
_Highlight the Individual FACILITY'S Page with veteran needed information_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 19 System Playbooks and Facility Data](https://drive.google.com/drive/folders/18c9fpui7dMr5LRnkhziw1GPXw9NoXAWT)

## Tasks
_Complete research of data for the following facilities listed below:_
- [ ] Elko VA Clinic
- [ ] George E. Wahlen VA Medical Center
- [ ] Idaho Falls VA Clinic
- [ ] Ogden VA Clinic
- [ ] Orem VA Clinic
- [ ] Pocatello VA Clinic
- [ ] Price VA Clinic
- [ ] Roosevelt VA Clinic
- [ ] St. George VA Clinic
- [ ] Weber County VA Clinic
- [ ] Western Salt Lake VA Clinic

* Load data in spreadsheet and highlight the main areas of information, 
- [ ] Parking (Confirm Free, ADA access, any Special)
- [ ] Special non-health services (Chaplain, etc)
- [ ] Confirm social media accounts (facebook, twitter, etc)

## Acceptance Criteria

* Parking (Confirm Free, ADA access, any Special)
* Special non-health services (Chaplain, etc)
* Confirm social media accounts (facebook, twitter, etc)
