### ISSUE TITLE
Connected apps authenticated/unauthenticated content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10207]
# User story

As a Veteran who has connected apps, I need to easily find information about disconnecting, reporting, or understanding errors when using my connected apps. As a Veteran who doesn't have connected apps, I may be interested in learning more about this feature and how to connect my VA.gov profile to an app.

# Details

## Issue Description
Lighthouse, public websites, authenticated experience, platforms teams are working together to align connected apps content across the authenticated and unauthenticated experiences.

---
## Tasks
- [x] Write content for new approach (Danielle)
- [x] Finalize content for collaborative working session (Danielle, Peggy)
- [x] Revise content based on working session outcomes (Danielle, Peggy)
- [x] Working session to go over content
- [x] Work with Lighthouse team to finalize content for handoff to authenticated experience team and assignment to PW team (Danielle, Peggy)
- [x] Add approved content to [implementation issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10327)

## Acceptance Criteria
- [x] Finalized content for authenticated experience handed off to authenticated experience team 
- [x] FAQs assigned to PW team for implementation in Drupal

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
**Notes:**

- First draft provided for review 6/9
[Draft content_connected apps help info & faqs_6.8.20](https://app.zenhub.com/files/133843125/6198fda6-3c94-4811-b8ff-771bf1eb2f80/download)
- Meeting held 6/10 with Danielle Thierry, Carey Otto, Peggy Gannon, Samara Strauss, Andrew Fichter, Mark Greenburg, and Tressa Furner. Notes:
  - We'll go with "third-party (non-VA)" on first mention, then "third-party"
  - We want to include the question about missing/wrong info in both the connected state and the unauthenticated faqs
  - Danielle to track copy back to Carey's original faqs to double check technical accuracy (looks like some variations got introduced in version sent internally to DT for review)
  - We want to help users report apps they need to report without being overly alarming; look at different placements for this info
  - Authenticated experience team needs the structure locked down by Monday 6/15, and copy by end of that week
- Updated draft send to team for final review 6/11
[Draft content 2_connected apps help info & faqs_6.11.20](https://app.zenhub.com/files/133843125/bdb840aa-7b8a-4002-a076-c11305b1c8a7/download)

**Comment by DanielleThierryUSDSVA** [comment]
@stephorkandatx Quick update for sprint planning. I'm meeting with connected app team tomorrow to finalize one question. So I think this piece should be complete soon. I will create a new issue for next sprint for a content writer to implement the FAQs piece of this content. Authenticated experience team will handle the authenticated content pieces.

**Comment by DanielleThierryUSDSVA** [comment]
**Authenticated content:** [Connected apps_authenticated content updates 6.17.20](https://app.zenhub.com/files/133843125/53cec7a1-1956-4afc-a892-9a5b107f66d9/download)

**Unauthenticated content:** [Draft content 3_connected apps help info & faqs_dt_6.17.20](https://app.zenhub.com/files/133843125/9a8f734f-b876-4171-8f19-448bac296511/download)

**Comment by DanielleThierryUSDSVA** [comment]
This issue is complete. Closing. FYSA @stephorkandatx
