### ISSUE TITLE
VAOS online scheduling tool: content review

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10206]
# User story
As a Veteran who wants to manage my appointments online, I need clear direction on how the online scheduling tool works and whether I can use it.

## Issue Description
Danielle asked to review content for the new VAOS online scheduling tool and work with Peggy and VAOS team to edit in preparation for upcoming changes.

---
## Tasks
- [x] Meeting with VAOS team
- [x] Sync with Peggy for further information
- [x] Review Peggy's edited version of content
- [x] Finalize with Peggy for handoff to VAOS team

## Acceptance Criteria
- [x] Handed off to VAOS team
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
My edits provided to Peggy 6/13/20.
[VA mobile apps VAOS copyV1_dt](https://app.zenhub.com/files/133843125/b1b41b9a-4e43-444c-9796-7f38bb0910a8/download)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @stephorkandatx

**Comment by DanielleThierryUSDSVA** [comment]
@stephorkandatx Adjusted this for tasks to end at handoff to VAOS team so we can close this out this sprint. This was a request to me from another team. Thanks!
