### ISSUE TITLE
Coronavirus chatbot: Week of 6.8.20/6.15.20 changes

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10205]
# User story
As a Veteran or family member, I need the latest information about how the coronavirus may impact my VA health care and benefit services. As a Veteran with low or no vision, I need phone numbers to be coded in a way that makes them accessible.

## Issue Description
We need to do 2 things:
- Update the chatbot messages and main info flow with the latest information based on the coronavirus FAQs
  - New questions for VA health insurance and protecting against scams
  - Updated question for claim exams
- Update the source coding for phone numbers (including TTY numbers) to align with the new content style code entry on accessible phone numbers

---
# Details

## Tasks
- [x] Update chatbot messages with new/updated FAQs (Danielle)
- [x] Update chatbot copy doc with new FAQs (Danielle)
- [x] Update draw.io decision tree with new FAQs (Danielle)
- [x] Update messages and copy doc with new phone number coding (Danielle)
- [x] Review messages and copy doc for errors (Randi)
- [x] Communicate handoff to dev team (Danielle)
- [x] Validate in staging
- [x] Validate on live site

## Acceptance Criteria
- [x] New and updated FAQs are validated on live site
- [x] All phone numbers are coded correctly for accessibility **update:** coding handed off to dev team; they can't accommodate now but will address in near-term iteration.

## Documentation for reference

- PR for review: https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/274
- Latest FAQs: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/
- Phone number guidance in content style guide: https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This is the request I mentioned on Friday that I'm hoping you can make your priority on Monday morning 6/15. 

I've made the updates to both the questions and the phone number source coding. Could you review for errors and omissions before I hand off to dev team? Thank you!

- Chatbot messages GitHub file: https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/6.12-content-updates/content/chatbot-messages.md
- Chatbot copy GitHub file: https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/6.12-content-updates/content/chatbot-copy.md

**Comment by DanielleThierryUSDSVA** [comment]
**NOTE:** I've validated the questions content on staging and prod. The dev team wasn't able to accommodate the new source coding. So they pulled it out of the PR and will address separately. Closing this ticket, as the work is complete for now on our end.

FYSA @stephorkandatx
