### ISSUE TITLE
PACT Integration Testing

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#10204]
# Overview

**[Design Document] Integration Testing with CDCT #8073**

Applications currently lack true integration test coverage.
- The closest we get to integrated testing is with our **existing end-to-end (E2E) tests**. The E2E tests run in [Nightwatch](https://nightwatchjs.org), a Node.js E2E testing framework. They are browser-based tests that simulate user flows in the application being tested.
- **No BE developers or systems have any role in these tests.** Any API responses expected in the course of a test are stubbed in the tests themselves by the FE developer writing the test. Response stubs are managed with a simple stub server that was developed in-house.

There are some problems with relying only on the current set of E2E tests as integration tests.
- **The E2E tests don't actually incorporate the API.** The stubbed responses are not validated and don't necessarily reflect reality, so the tests don't give us confidence that we're testing the right thing.
- FE developers are entirely responsible for coming up with stubbed API responses, but aren't accountable for *validating those responses*.
- Without involving the BE developers maintaining the endpoints, FE developers are **prone to making invalid assumptions** about systems that they don't work on themselves.

# Steps

[The following checklist is from Pact's doc site.](https://docs.pact.io/pact_broker/set_up_checklist)

## Basic

This will get you to the stage where your consumer and provider have a pact that is generated and verified automatically, with a set up that allows you to introduce changes without breaking the provider build.

### Anyone

-    [x] Set up an instance of the Pact Broker

### Consumer team

-    [x] Write tests for the consumer that use the Pact mock provider (these generate the pact)
-    [x] Add a task that only runs on the CI to publish the generated pacts to the Pact Broker (the Pact implementation for your language will provide this)
-    [x] Configure the pacts to be published with a tag that is the dynamically determined name of the git/svn branch (eg. master, feat-foo)

### Provider team

-    [x] Add a pact verification test to the provider build
-    [x] Configure the verification test to verify the pacts with the tag master (or whatever the "main line" of development is called)
-    [x] Configure the pact verification task to publish verification results only when run on the CI.
-    [x] Create a separate CI job that just does the pact verification/results publishing steps. It should accept the URL of the changed pact as a parameter (see the webhooks page for more information on this).
-    [x] Create a webhook that triggers the pact verification CI job when a pact changes, and use the webhook template parameters to pass the URL of the changed pact into the CI job (see the webhooks page for more information on this).

## Advanced

This set up will ensure that you can only deploy compatible versions of your consumer and provider to a given environment.

### Consumer team

~~-    [ ] Ensure the Pact Broker knows which application versions are in each environment by adding a step to the deployment process to tag the relevant consumer version with the name of the environment (eg. test, prod)~~ [Moved to ticket #22102](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22102)
-    [x] Check that you are safe to deploy to a given environment by adding a call to can-i-deploy before deploying.

### Provider team

~~-   [ ] To ensure backwards compatibility between the production consumer and the latest provider, add the name of the tag for the production environment (eg. prod) to the list of tags that the provider verifies.~~ [Moved to ticket #22101](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22101)
~~-    [ ] Add a step to the deployment process to tag the relevant provider version with the name of the environment (eg. test, prod)~~ [Moved to ticket #22103](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22103)
-    [x] Check that you are safe to deploy to a given environment by adding a call to can-i-deploy before deploying.

**Comment by holdenhinkle** [comment]
This item listed above (one for consumer and one for provider) is half complete--"Check that you are safe to deploy to a given environment by adding a call to can-i-deploy before deploying." `can-i-deploy` is called but it's not blocking.
