### ISSUE TITLE
Discovery Research Epic

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#10213]
## High Level User Story
As a Veteran, I need complete pre-visit documentation so I can inform my care team of my most current health information.

## Goals
_What outcome(s) do we want to see?_ 

## Issues to create within this Epic
 

- [x]  Create research plan
- [x]  Recruit for research sessions/Schedule research sessions
- [x]  Create conversation guide
- [x]  Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- [x]  Discovery Synthesis - should be conducted as a team, led by designer.
- [x]  Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. 

Designers should also plan to do research readouts at the end-of-sprint demo.)

## How to configure this issue
- [ ] **Labeled with `discovery` and `research` and `team-name`**
