### ISSUE TITLE
Update post authentication URLs to address GA goal funnel issue

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#10221]
## Update Post Authentication URLs on VA<span/>.gov

As noted in #9398, VA.gov redirects users to the exact same Page URL after authentication.  This causes issues with any URL-based Google Analaytics goals that have funnels:  

https://support.google.com/analytics/answer/1116091?hl=en#identical

Google's recommended fixes won't work...

- _Set up event tracking to track flows like this._

Custom funnels with events only allow 5 steps.  Many of our applications are >5.

- _Use an event goal instead of a destination goal._

Event tracking only tracks completion and not the preceding funnel steps - which we need.

------
### We are asking that the post-authentication URL has a query parameter appended to allow us to differentiate pre and post authentication.

These URLs have a  `next` query parameter.  Examples:

- /index.html?next=/my-va
- /index.html?next=/track-claims/your-claims
- /index.html?next=/track-claims/
- /index.html?next=/my-va/
- /index.html?next=/track-claims
- /index.html?next=/change-address
- /index.html?next=/education/gi-bill/post-9-11/ch-33-benefit/status

## Tasks
- [ ] Select URL parameter to denote authenication.  This should be new and descriptive.  Suggestions: `auth=1` `postLogin=true` (Jon and Brian)
- [ ] Have developer update staging.va.gov to append URL parameter to all `?next=` URLs 
- [ ] QA existing goal funnels (Jon and Brian)
- [ ] If necessary, update existing goal funnels with additional step with new URL (Jon and Brian)
- [ ] Deploy to production

--------
## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by rianfowler** [comment]
About implementation [from](https://dsva.slack.com/archives/CBU0KDSB1/p1594240014449300?thread_ts=1594235910.443900&cid=CBU0KDSB1) @jholton :

> I took a quick look at the linked issue, and I think this is just a FE task.
I think what they need is for the FE to append a querystring parameter (e.g. postLogin=true , per the GH issue) to the redirectUrl [here](https://github.com/department-of-veterans-affairs/vets-website/blob/540689998ea7de8fada72c2fc1a4b0b903562194/src/applications/auth/containers/AuthApp.jsx#L131-L138) (at least for redirectUrls that contain a next querystring parameter).
Correct me if I’m wrong. (edited)

**Comment by jonwehausen** [comment]
Hey @rianfowler and @jholton , 

Thank you both! 

Yes, it would be great if we could move forward with getting the param added universally to the `/introduction` pages of forms post-authentication **in staging only.** 

From there, we can make changes to our GA Non-Prod account views and validate our hypothesis there before we move forward with production.

**Comment by bsmartin-ep** [comment]
@theodur / @jonwehausen -

As discussed, we think we need a change to this.

We asked Theo to only append the `postLogin` parameter to the URL when the `next` parameter is present.  However, it appears that parameter is only present when a user is deep linked to a URL that requires authentication.  If a user goes to a form intro page, clicks the button to login, and authenticates, it does not use the `next` parameter and therefore no `postLogin` parameter.

@theodur -

Please update your code to append the `postLogin` parameter for **all** return URLs.  As discussed, you may want to test if the `next` URLs require any sort of encoding to make sure the parameter is passed along to the end page.

Thanks.

**Comment by mnorthuis** [comment]
BAM2 team will be the first team working on implementing the "How to apply" wizard to the first page of applications.  The first form they are working on is the 1990 in education.  Leah Keeler is the PM on that team.

**Comment by jonwehausen** [comment]
@bsmartin-ep / @bmcgrady-ep 

This [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13558) has moved into staging with the feature flag. 

I have now setup 3 test goal funnels in each of their respective view for the following forms: 
- Education 1995
- Disability 526EZ
- Health Care 1010EZ

Each of these goals are mirrored from their original with the addition of a second step to include `postLogin=true` on the `/introduction` page. 

We will want to execute a few scenarios with various test users for each and compare with results with the original funnel and the new post auth funnel. 

If I could have one of you lead the charge in executing those tests that would be great.

**Comment by joanneesteban** [comment]
For our own reporting purposes:
 
For the month of June, these were the following funnel conversion rates in step 1:
 
Form | Conversion Rate | Predicted Discrepancy: Hypothesized Actual Conversion Rate
---- | ---- | ----
Submit Burial (Form 530) | 38.08% | 46.67% (+8.59%)
Preneed Submission | 48.15% | 54.22% (+6.07%)
Submit Form 1990 | 64.43% | 72.81% (+8.38%)
Submit Form 1990e | 60.78% | 66.06% (+5.28%)
Submit Form 1990n | 53.41% | 58.16% (+4.75%)
Submit Form 1995 | 62.26% | 65.07% (+2.81%)
Submit Form 5490 | 62.75% | 68.85% (+6.1%)
Submit Form 5495 | 66.22% | 69.79% (+3.59%)
Submit Health Care Application (Form 1010EZ) | 18.33% | 36.14% (+17.81%)
Submit Pension Application (Form 527EZ) | 26.97% | 36.74% (+9.77%)
GI Bill Feedback Tool | 31.63% | 40.4% (+8.77%)
Disability Increase Submit (Form 526EZ) | 0% | 8.32% (+8.32%)
Discharge Upgrade Guidance | 38.33% | 46.33% (+8%)

**Comment by bsmartin-ep** [comment]
@joanneesteban / @jonwehausen -

I've wrapped up my testing and have some recommendations.

---------------------------

1.  All Destination (URL) goal types that are an **EXACT** match should be changed to **BEGINS_WITH** or **REGEX**.  I believe this is a necessity to make sure existing goal funnels will work with the addition of a `postLogin=true` URL parameter.  Also, this should help ensure all goal funnel steps are counted for any other URL parameters.

The following goals will need to be updated:

View Name|Goal Name
--|--
va<span></span>.gov - Test View	|	Submit Pension Application (Form 527EZ)
Burials Modernized View	|	Submit Burial (Form 530)
Pension Modernized View	|	Submit Pension Application (Form 527EZ)
Education Modernized View	|	Submit Form 1990
Education Modernized View	|	Submit Form 1990e
Education Modernized View	|	Submit Form 1990n
Education Modernized View	|	Submit Form 1995
Education Modernized View	|	Submit Form 5490
Education Modernized View	|	Submit Form 5495
Education Modernized View	|	Submit Form 0993
Education Modernized View	|	GI Bill Feedback Tool
Education Modernized View	|	Submit Form 22-0994 [VET TEC]
WBC - va<span></span>.gov Modernized Content	|	Submit Burial (Form 530)
WBC - va<span></span>.gov Modernized Content	|	Submit Form 1990
WBC - va<span></span>.gov Modernized Content	|	Submit Form 1990e
WBC - va<span></span>.gov Modernized Content	|	Submit Form 1990n
WBC - va<span></span>.gov Modernized Content	|	Submit Form 1995
WBC - va<span></span>.gov Modernized Content	|	Submit Form 5490
WBC - va<span></span>.gov Modernized Content	|	Submit Form 5495
WBC - va<span></span>.gov Modernized Content	|	Submit Health Care Application (Form 1010EZ)
WBC - va<span></span>.gov Modernized Content	|	Submit Pension Application (Form 527EZ)
WBC - va<span></span>.gov Modernized Content	|	GI Bill Feedback Tool

---------------------------

2.  All **REGEX** goal types should start with a `^` character to make sure the correct URL is matched (and not in a `next=` parameter for instance).

The following goals will need to be updated:

View Name|Goal Name
--|--
VA<span></span>.gov - Test View	|	Disability Claims Submitted (Form 526EZ v2)	
Facility Locator Modernized View	|	Facility Details Viewed	
Health Care Modernized View	|	VA Online Scheduling	
Education Modernized View	|	GIBCT Facility Profile Viewed	
Disability and Claims Modernized View	|	Claims Details Viewed	
Disability and Claims Modernized View	|	Disability Increase Submitted (Form 526EZ v1)	
Disability and Claims Modernized View	|	Appeals Status Viewed	
Disability and Claims Modernized View	|	Disability Claims Submitted (Form 526EZ v2)	
Disability and Claims Modernized View	|	Rated Disabilities Status Viewed	
WBC - VA<span></span>.gov Modernized Content	|	Claims Details Viewed	
WBC - VA<span></span>.gov Modernized Content	|	GIBCT Facility Profile Viewed	
WBC - VA<span></span>.gov Modernized Content	|	Facility Details Viewed	
WBC - VA<span></span>.gov Modernized Content	|	Disability Increase Submit (Form 526EZ)	
z Filter Test 10 - Health Care Modernized View	|	VA Online Scheduling	

---------------------------

3.  A unique issue I found is the [VA Online Scheduling goal funnel](https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184318975/_.goalOption=5).  The RegEx on the first step is too lenient and will match all other step URLs.  I will create a separate issue for this onne.

**Comment by bsmartin-ep** [comment]
`postLogin=true` URL param has been enabled on production va.gov.  We will monitor the modified funnels.  Closing.
