### ISSUE TITLE
[PM] Logged-in homepage: Plan for how to incorporate stakeholders

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10230]
## Background

We need to figure out how to effectively work with both DEPO and non-DEPO stakeholders to review and approve logged-in homepage work.

## Tasks

- [x] Talk with Chris J to figure out how to incorporate non-DEPO stakeholders.
- [x] Figure out at what cadence to review work with the DEPO team (probably in Thursday meetings and as needed).

## Acceptance criteria

- [x] Some light documentation on how we plan to incorporate both groups.

**Comment by Samara-Strauss** [comment]
Regrouping with Chris J on 6/29.

**Comment by Samara-Strauss** [comment]
This was actually pretty simple to figure out. Cadence and more formal details will probably be figured out as we go along:

- Initially, reach out to VEO and set up a time to talk to them and get them on board. Meet with them as needed.
- For the broader VA group, I'll start going to digital modernization counsel meetings as needed once we have some designs to share.
