### ISSUE TITLE
Create Reusable Sidebar Component for Use in VSP Platform

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#10239]
## Background
On the rated disabilities project we noticed that there was a 'sidebar' pattern used in many places on VA.gov. This sidebar is currently not a reusable component and has to be built from scratch each time. Since the basics of the pattern don't seem to change much we had the idea to create a reusable sidebar component at the platform level. When building Rated Disabilities we purposely built the sidebar in a way that it can be turned into a reusable component, so this ticket is just to do the work of turning it into a reusable component with the following tasks - 

## Tasks
- [x] Move the code for the sidebar component into the veteran-facing-services-tools repo
- [x] Adjust unit tests to account for more use cases of the sidebar component
- [x] Move PR through the approval process

## Acceptance Criteria
- [x] Move code into veteran services repo via PR
