### ISSUE TITLE
[Build] [Engineering] SSO Cerner Implementation (FE) + Chalmers rollout

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10240]
## Issue Description
Engineering implementation for the SSO Cerner Support, VA.gov Health Pages. This will create new alert boxes for an authenticated experience, and revised copy for unauthenticated experience.

These are updates to alert boxes, static content on VA.gov health pages (prescription, test results, messaging, etc.) to direct users who are patients at Cerner facilities to the right place.

Users who are marked on the backend as being patients at a facility that will start using Cerner for health tools, will start seeing the new pattern.

Engineering knowledge pick-up took place in ticket #9696 
Goal: by end of June 2020 to have this on staging

UX POC: Bridget Hapner (connect with Liz first)
PM POC: Alexis James
Engineering POC: Dan Hinze

---

## Acceptance Criteria
- [ ] Code complete
- [ ] Available for review on staging

---

## Links
Electronic Health Record Modernization (EHRM) Spokane Mann Grandstaff  IOC: Veterans receiving care at VA Medical Centers who have converted to EHRM will have the following functionality:

**View, direct book, cancel, request, and manage appointments (Scheduling)**
VA.gov: Schedule and View Appointments
* Link to this in Staging My VA Health: https://ehrm-va-test.patientportal.us.healtheintent.com/pages/scheduling/upcoming
* Link to this in PROD My VA Health: https://patientportal.myhealth.va.gov/pages/scheduling/upcoming

**Exchange secure messages with health care team**
VA.gov: Send a Secure Message to your health care team/Use Secure Messaging
* Link to this in Staging My VA Health: https://ehrm-va-test.patientportal.us.healtheintent.com/pages/messaging/inbox
* Link to this in PROD My VA Health: https://patientportal.myhealth.va.gov/pages/messaging/inbox

**View, download, and transmit health information to manage health care**
VA.gov: View your VA lab and test results online
* Link to this in Staging My VA Health: https://ehrm-va-test.patientportal.us.healtheintent.com/pages/health_record/results/labs
* Link to this in PROD My VA Health: https://patientportal.myhealth.va.gov/pages/health_record/results/labs

**Submit health information updates and answer custom questions via Clipboards**
Submit medication refill and prescription renewal requests
VA.gov: Refill and track your prescriptions
* Link to this in Staging My VA Health: https://ehrm-va-test.patientportal.us.healtheintent.com/pages/medications/current
* Link to this in PROD My VA Health: https://patientportal.myhealth.va.gov/pages/medications/current

 
Centralized Scheduling Solution (CSS): Veterans at Chalmers P. Wylie VA Ambulatory Care Center, Columbus OH (757) will utilize scheduling only functionality.  My VA Health will be contextually aware of the Veteran and only present the following functionality:

View, book, request, and cancel appointments online  

Manage appointments: Add to Calendar, View Instructions, Print Details

Appointments booked online for VA Medical Centers converted to CSS are visible for staff in Cerner and in VistA Scheduling

VA.gov: Schedule and View Appointments

* Link to this in Staging My VA Health: https://ehrm-va-test.patientportal.us.healtheintent.com/pages/scheduling/upcoming
* Link to this in PROD My VA Health: https://patientportal.myhealth.va.gov/pages/scheduling/upcoming

## Documentation
Desktop Invision: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409123884_Unauthenticated_Pages

Mobile Invision: https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/409260607_M-Authenticated_Pages_-_Alerts

Product Outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/sso

Handoff document: https://docs.google.com/document/d/11OGKfLk0fKd08pqCKT0Wvrt9ze2vZW_PSEn2kJdK714/edit#

Dan has a github branch in progress to review with us.

---
## Complexities or points of consideration

* There may be some complexity to manage in the future when new Cerner facilities roll out (ex: what happens if a user is a patient at multiple facilities - how would that impact the alert box?)

---

## Tickets to create/groom 
@MickinSahni 
- [x] Review content created [by Kelson] - Danielle (#11154)
- [x] Update pages to replace with React components (potentially via Flipper) (#11153)
- [ ] Write e2e tests for scheduling

**Comment by hinzed1127** [comment]
Here's the current tickets describing updates required in the front-end.

**Content updates**: These are the changes that require moving 5 pages from the CMS. Each page will exist as a standalone react application (as things currently work in vets-website). The main need for this is to dynamically render certain content depending on 2 conditions:

1. Is the user currently logged in, AND
2. Are they a cerner patient? 

Further down the road there will probably be a need to differentiate between patients that are exclusively using Cerner's application vs a mixture of that and MHV, but for now that's not a distinction that's required.

**Related Tickets for Page Updates (split between authenticated/unauthenticated content)**
These tickets pretty much cover what the invision links above show but in a more granular page-by-page breakdown for each ticket.

#5839 / #5745 - Scheduling
#5837 /#5743 - Medical Records
#5838 / #5744 - Test Results
#5836 / #5381 - Messaging
#5835 / #5741 - Prescriptions

**Alert Box Updates**: For all of the pages mentioned above, there are specific call to action widgets that also need to display conditional logic based on what facilities they have medical records at (Cerner vs non-Cerner). 

I have an existing branch with WIP for this under `sso-alert-box-updates`, but @kelsonic and I discussed a more dramatic pulling apart of the CTA widget, which currently has accumulated a lot of technical debt/complexity that could be greatly reduced if the alert boxes for these pages were to be pulled out into their own separate widget.

**Related Tickets**
also by page, but from an implementation perspective, this is all contained in a single CTA React widget
#5384 - Scheduling
#5390 - Medical Records
#5387 - Test Results
#5381 - Messaging
#5378 - Prescriptions

I think that's everything, but let me know if I missed anything!

**Comment by stephorkandatx** [comment]
@kelsonic and @DanielleThierryUSDSVA : I have added links (staging, production) c+p from a Cerner email. Kelson, please review & share questions you have with Danielle. We can hop on a call as well if that is faster. We will need to get questions over to the right people quickly.

**Comment by kelsonic** [comment]
Merged in authenticated + unauthenticated content for Cerner pages (not live yet of course) 🎉  Posting what each page looks like compared to current + design spec below:



### Get Medical Records Page ([current live URL](https://www.va.gov/health-care/get-medical-records/))

**Unauth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405228622

**Unauth** Implementation Screenshot:

![get-medical-records-page--unauth](https://user-images.githubusercontent.com/12773166/85934710-3ade0e80-b8a4-11ea-8e3a-33a90498d249.png)

**Auth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405228559

**Auth** Implementation Screenshot:

![get-medical-records-page--auth](https://user-images.githubusercontent.com/12773166/85934711-416c8600-b8a4-11ea-974e-9e1d0c1c0a23.png)

### Refill Track Prescriptions Page ([current live URL](https://www.va.gov/health-care/refill-track-prescriptions/))

**Unauth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404897006

**Unauth** Implementation Screenshot:

![refill-track-prescriptions-page--unauth](https://user-images.githubusercontent.com/12773166/85934713-4af5ee00-b8a4-11ea-84d0-81dd13754f47.png)

**Auth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404897044

**Auth** Implementation Screenshot:

![refill-track-prescriptions-page--auth](https://user-images.githubusercontent.com/12773166/85934716-4fbaa200-b8a4-11ea-8a4a-1a9bc12a0d76.png)

### Schedule View VA Appointments Page ([current live URL](https://www.va.gov/health-care/schedule-view-va-appointments/))

**Unauth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881624

**Unauth** Implementation Screenshot:

![schedule-view-va-appointments-page--unauth](https://user-images.githubusercontent.com/12773166/85934717-53e6bf80-b8a4-11ea-9130-b921399788e5.png)

**Auth** Design Specs: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778 and https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/412116795

**Auth** Implementation Screenshot:

![schedule-view-va-appointments-page--auth](https://user-images.githubusercontent.com/12773166/85934718-577a4680-b8a4-11ea-9108-75db3014a375.png)

### Secure Messaging Page ([current live URL](https://www.va.gov/health-care/secure-messaging/))

**Unauth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404425133

**Unauth** Implementation Screenshot:

![secure-messaging-page--unauth](https://user-images.githubusercontent.com/12773166/85934721-5b0dcd80-b8a4-11ea-8afb-29e075b20d8d.png)

**Auth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404880626

**Auth** Implementation Screenshot:

![secure-messaging-page--auth](https://user-images.githubusercontent.com/12773166/85934724-5ea15480-b8a4-11ea-81a7-9bf8d97352fe.png)

### View Test and Lab Results Page ([current live URL](https://www.va.gov/health-care/view-test-and-lab-results/))

**Unauth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405217796

**Unauth** Implementation Screenshot:

![view-test-and-lab-results-page--unauth](https://user-images.githubusercontent.com/12773166/85934726-6103ae80-b8a4-11ea-95e7-cb9cd83f8549.png)

**Auth** Design Spec: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405218216

**Auth** Implementation Screenshot:

![view-test-and-lab-results-page--auth](https://user-images.githubusercontent.com/12773166/85934727-63fe9f00-b8a4-11ea-8e91-7a11f2c4d564.png)
