### ISSUE TITLE
[FE] Logged-in homepage: Investigate showing upcoming appointments

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10247]
## Background

As features on My VA transitions to the logged-in homepage, we plan to still show a block for "scheduling an appointment." At minimum, it would work as it does now — simply a link off to the tool itself. A nice to have would be to show the next upcoming appointment a veteran has. We need to investigate if we have access to this information to gauge the feasibility of showing this on the logged-in homepage, either now or in the future.

## Tasks

- [ ] Investigate what information we have access to re: upcoming appointments.
- [ ] Document the following (and any other relevant info) in this ticket:
  - Do we have access to upcoming appointment info? Or, do we only know about appointments scheduled through VA.gov? 
  - Where does this info come from?
  - How is the data structured (eg. appointment name, location, date, etc)?
  - Can we tell whether something is the next appointment?
  - Do we have reason to believe there may be appointment info we don't have access to (eg. we know about some appointments but not others, which might cause confusion if the veteran expects to see an appointment we don't know about)?
- [ ] Make a recommendation as to whether you think we can reliably and (relatively) easily show upcoming appointment information on the logged-in homepage.

## Acceptance criteria

- [ ] We have determined whether showing upcoming appointments will be part of phase 1 or not.

**Comment by erikphansen** [comment]
We currently show upcoming appointments at https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/

Will check with the VAOS team to see feasibility of showing current appointments. Do they have a component we could drop into place?

**Comment by erikphansen** [comment]
To get the full appointment data you need to:
1. Get the community cares appointments (ex: `GET https://staging-api.va.gov/vaos/v0/appointments?start_date=2020-08-07&end_date=2021-09-07&type=cc`)
2. Get the VA appointments (ex: `GET https://staging-api.va.gov/vaos/v0/appointments?start_date=2020-08-07T07:00:00.000Z&end_date=2021-09-07T07:00:00.000Z&type=va`)
3. Get facility info by calling the facility API with the facility IDs from call #2 (ex: `GET https://staging-api.va.gov/v1/facilities/va?ids=vha_552,vha_442,vha_442GC,vha_442GD,vha_442HK,vha_442GB,vha_552GD`)

Examples of what appointment cards look like on https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/:

**CONFIRMED**
![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/1de046b3-7b16-426d-ba31-55f4558c2199)

**CANCELED**
![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/f5d75ab3-b018-48c6-af09-1ea08a583402)

**PENDING**
![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/500b4771-ec92-449f-86aa-ffafad6e902e)

**VIDEO CONNECT and COMMUNITY CARE**
![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/68502913-a13e-4a32-81c1-c9b32e30395a)

**Comment by Samara-Strauss** [comment]
Thank you for this! Anything else that needs to be documented here?

**Comment by erikphansen** [comment]
At this point I think we can call this one done.

**Comment by Samara-Strauss** [comment]
Great! I'll close it out.

**Comment by Samara-Strauss** [comment]
cc/ @tressaellen and @callen2563 for awareness. There are images above of the different states for scheduled appointments.
