### ISSUE TITLE
[FE] Logged-in homepage: Investigate level of effort for showing overall disability rating

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10249]
## Background

During user research, overall disability rating was named as the top disability-related feature that people expected to see when they logged in to VA.gov. This information was added to VA.gov earlier this year, so we now have access to it on the site (which we did not during the original design in 2018). Given user's expectations with seeing this information, we should investigate the level of effort for us to pull in people's overall disability rating to the logged in homepage.

## Tasks

- [ ] Investigate level of effort for pulling in someone's overall disability rating.
- [ ] Make a recommendation (can be in this ticket) as to whether you think this can be part of V1 of the logged-in homepage or should be pushed to a future phase.

## Acceptance criteria

- [ ] We have determined whether or not we want to show overall disability rating on the logged-in homepage.

**Comment by erikphansen** [comment]
Next step:
- [ ] try hitting `GET /v0/disability_compensation_form/rating_info` with user 228

**Comment by erikphansen** [comment]
Was able to get this back from the `GET https://staging-api.va.gov/v0/disability_compensation_form/rating_info ` endpoint using user 228:

```json
{
    "data": {
        "id": "",
        "type": "evss_disability_compensation_form_rating_info_responses",
        "attributes": {
            "user_percent_of_disability": 100
        }
    }
}
```

and this from user 226:

```json
{
    "data": {
        "id": "",
        "type": "evss_disability_compensation_form_rating_info_responses",
        "attributes": {
            "user_percent_of_disability": 70
        }
    }
}
```

That doesn't quite match the response the [swagger docs](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getRatingInfo) specify, but the bottom line is that it seems simple enough to get a user's disability rating.

**Comment by erikphansen** [comment]
Closing this. We can easily get the overall disability rating.

**Comment by Samara-Strauss** [comment]
Awesome, that's what I expected. Thanks! This is really exciting and will go a long way in matching user expectations.
