### ISSUE TITLE
[FE] Logged-in homepage: How are we going to build the logged-in homepage?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10256]
## Background

The goal of this project is to personalize the current logged-in homepage and retire the existing My VA dashboard. This means we need to figure out how to handle some technical complexity, including:

- Since the logged-out homepage is on Drupal, but logged-in tools are not, what tools are we going to use to build the logged-in homepage?
- What happens to the logged-out view when people log-in URL-wise? How should we handle this?
- How can we make it so that the logged-in view doesn't slow down or otherwise adversely affect the logged-out view?
- How can we make sure emergency banners are visible in the logged-in view (since they are powered by Drupal)?

....and any other foundational questions you think we should answer.

## Tasks

- [ ] Investigate the issues listed above.
- [ ] Create a plan for how we can build the logged-in homepage.
- [ ] Document that plan in [the project's Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign/build).

## Acceptance criteria

- [ ] We have a plan for how to handle build of the logged-in homepage.

**Comment by sanlouise** [comment]
This is a document where we can share different approaches to creating the logged-in home page.

https://docs.google.com/document/d/1QIAXCaeL5PYPITizshvTzKZI_5fohU0c57ZnO_XYDiM/edit?usp=sharing

**Comment by sanlouise** [comment]
@Samara-Strauss @erikphansen We should be able to close this ticket.

I created [a follow-up ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12881) to implement a very basic skeleton for the authenticated homepage that should allow us to answer the questions asked in this ticket better. We should also wait with adding documentation of a plan until we are a bit further ahead, as in this new ticket we'll be testing out a couple of possible approaches. Getting our hands dirty in the code will make it so that the pros and cons of each approach are clearer.
