### ISSUE TITLE
COVID-19 screening tool: Veteran appointment reminder letter

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10269]
# User story

As a Veteran going for an in-person appointment at my local VAMC, I need to know how to prepare for my visit. This includes being prepared for symptom screening, face covering policies, and other new changes due to the coronavirus pandemic.

## Issue Description
We need to develop a letter that VAMCs can send to Veterans to help them prepare for their appointments.

---
## Tasks
- [x] Review/edit draft from VEO team
- [x] Communicate back to VEO team
- [x] Finalize letter and hand off for JTF review
- [x] Incorporate any JTF changes and hand off to VEO team for dissemination

## Acceptance Criteria
- [x] Letter is finalized and sent to VEO for dissemination
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
