### ISSUE TITLE
[Discovery] Learning Center (MVP) Usability Study Research Plan

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10270]
## User Story or Problem Statement
As a UX Designer, I need to create a research plan so I can document the research's purpose, goals, hypothesis, and usability testing recruitment needs. 

Our usability study should answer the following questions:

- Is information easy to find using this search-focused, tag-based navigation?
- Is the proposed IA (taxonomy, categorization, labels, nomenclature) effective for Veteran and other audiences?
- Are the template labels (ex: FAQs, Checklist, Media List) useful to users?
- What do users see as the difference between the learning center and overall site search?
- Do users understand that information they don't find in the benefit hub might be in the learning center?
- Do users understand that information they don't find in the learning center might be in the benefit hub?

[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp)
[Status, Decisions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md)

## Goal
_A completed research plan sent to Perigean for user testing recruitment_

## Objectives or Key Results this is meant to further
- _User testing to validate the MVP Learning Center design(s) and/or uncover gaps, improvements, and pain points_

## Tasks
- [x] _Create research plan
- [x] _Review research plan with design team_
- [x] _Obtain approval from ~Andrea Schneider~_ Lauren Alexanderson
~- [ ] _Send research plan to Perigean_~ (Lauren will send to Perigean)
- [x] _Add research plan to GH_

## Acceptance Criteria
- [x] Research plan created and uploaded to GH

**Comment by stephorkandatx** [comment]
**Initial list of questions or areas of interest, for user research**

The findability, navigation of content using this search-focused, tag-based navigation. Is the information easy to find using this new method?
The taxonomy, IA of categories. Is the chunking of the categories and labels the best way to begin this? For Veteran and other audiences, in terms of taxonomy and nomenclature, is this effective?
The labels of the types of templates, and if they affect what the user chooses to read (ex: FAQs, Checklist, Media List). We think it is useful for users. Do we test without the labels to gauge if including is an improvement or not?
Based on the thoughts regarding Tier 1 and Tier 2 content: is there a way we can find out with users how comfortable they are with the distinction between Tier 1 and Tier 2 content - or do they even care, as long as they can find what they need? Does it matter if something is in benefit hubs or learning center? How frequently do they go bak and forth?

**Comment by andaleliz** [comment]
@jenniferlee-dsva FYI: I've updated the description at the top of this issue with the specific questions our research plan will answer, based on the meeting today:

- Is information easy to find using this search-focused, tag-based navigation?
- Is the proposed IA (taxonomy, categorization, labels, nomenclature) effective for Veteran and other audiences?
- Are the template labels (ex: FAQs, Checklist, Media List) useful to users?
- What do users see as the difference between the learning center and overall site search?
- Do users understand that information they don't find in the benefit hub might be in the learning center?
- Do users understand that information they don't find in the learning center might be in the benefit hub?

**Comment by andaleliz** [comment]
[Created research plan file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/research-plan.md), currently in draft status

**Comment by andaleliz** [comment]
I've updated the research plan and taken it about as far as I can without the prototype. I'd love to review with the team once we have the prototype ready, and before we submit for approval. 

Some specific questions we'll need to address, and I'd like input on:

- Have I sufficiently captured the project background?
- Review of research questions. I added `Where would the most useful place be to provide links to the Learning Center?`. I don't think we need to make a specific task around this, but I'm hopeful can gain insight into answering this, which will be helpful for the next phase.
- Review of hypothesis. Have I missed anything?
- Do we need any specific participant criteria related to the content we'll be testing? E.g. people who have an account, familiarity with burial benefits, etc
- How will we recruit for the card sort?
- Appropriate amount of participants for the card sort?
- Timeline.  I have PTO in July; may impact timeline or we can get someone else to facilitate.
- Observer list includes everyone invited to the kick off meeting. Anyone else?

**Comment by andaleliz** [comment]
@jenniferlee-dsva (or maybe @DanielleThierryUSDSVA knows?)

I'm thinking through how we will answer the research question:

>Is the proposed IA (taxonomy, categorization, labels, nomenclature) effective for Veteran and other audiences?

Are any of the [topic or audience tags](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#topic-tags) open to change based on what we learn from users?  There are a few things we can test, and different approaches depending on exactly what we want to dig into.

Below are some examples of some things we could look at. Some of them make more sense than others, depending on what's open to change.  I'd love to hear any more specifics you have (if any) about what you want to learn from users regarding the proposed IA.

- What kinds of content would Veterans expect to find under the topics, if they saw a list of topics?
- What topic headings would Veterans come up with if they saw a list of articles?
- How do the topic and audience labels resonate with content authors who will be applying them?
- Whether or not people can find articles if they are grouped under audience and topics in the way we are proposing
![Screen Shot 2020-06-25 at 2.11.51 PM.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/7f2c3838-66a1-4919-a629-5b764c9d55d7)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. I'll let @jenniferlee-dsva speak to how much openness to changing topics/audiences there might be, as that work happened before I joined. But I think your questions above are good ones to learn more about. Will think about other possibilities as well.

**Comment by jenniferlee-dsva** [comment]
@andaleliz - I provided edits to your research draft. Feel free to refine further. Also added as a PR comment one design learning I'd love to get user input on. It's too granular for the research plan, but maybe more for convo guide.

> * Do we need any specific participant criteria related to the content we'll be testing? E.g. people who have an account, familiarity with burial benefits, etc

The diverse Veteran criteria you have is good. Since we're launching with VA.gov account topic for MVP, I would also add, people who have a VA.gov online account, MHV account, or eBenefits account. 

> * How will we recruit for the card sort?

Have confirmation that we have done unmoderated card sorts before and that we recruited via MHV email list. That was however for health specific topic, so unclear if we can use MHV route. I'm meeting with Jeff Barnes next week to discuss unmoderated card sort route. 

> * Appropriate amount of participants for the card sort?

I defer to folks in the research community on this or to taxonomy/IA experts, Mikki and Meg.

> * Timeline.  I have PTO in July; may impact timeline or we can get someone else to facilitate.

NP. We will work with it. 

> * Observer list includes everyone invited to the kick off meeting. Anyone else?
I added additional observers. 

RE - audience/topic tags: 

>open to change based on what we learn from users?

Of course. Depending on how it affects the overall landscape, we may incorporate right away, or use for the next iteration. We just have to stay committed to starting with a small  list and not launching with too many. Remember that most of this content will be authored by VA SMEs, not the content team.

The governance of labels  at VA is extremely challenging, and more labels have not been more useful. Rationale for the [purpose of tags are here in the repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

The goal for tag category labels in my mind is really: 

- Are these labels broad enough to capture most of the content people are looking for? 
- If the information they're looking for isn't in one of these categories, what's missing? 
- Can people still find what they need through search? (And in the after launch future: Through a combination of tag filtering and keyword search - e.g., I search by a keyword, then I filter results by audience?)

**Comment by andaleliz** [comment]
Adding a comment from Jen on the PR she submitted to ensure this doesn't get lost, since we haven't built out the conversation guide yet:

>There is one thing that Ryan and I def wanted to get user input on. It's a little granular, so maybe more for the conversation guide than the research plan. When users click on the 'View all articles...' link, we currently just take them to the search results page with a list of all of the LC articles tagged with that benefit category (and user may have to paginate if there are lots of articles in the future).

> We'd love to learn if that's usable for users or if they expect/prefer/need to see a list of articles as a link farm - just a list of text links, all on one page. We didn't design for this because we just weren't sure what would be more useful to people. The concern is whether users find it hard to scan and find the for topic they're looking for when it's given as a search results display of "tagged" content.

**Comment by andaleliz** [comment]
>The goal for tag category labels in my mind is really:
Are these labels broad enough to capture most of the content people are looking for?
If the information they're looking for isn't in one of these categories, what's missing?
Can people still find what they need through search? (And in the after launch future: Through a combination of tag filtering and keyword search - e.g., I search by a keyword, then I filter results by audience?)

@jenniferlee-dsva, got it. Are there any other specific aspects of the IA you want to test with this round of research? Just want to be sure that we that cover what was discussed in our 6/11 meeting when we added this to our research questions:
>The taxonomy, IA of categories. Is the chunking of the categories and labels the best way to begin this? For Veteran and other audiences, in terms of taxonomy and nomenclature, is this effective?

**Comment by andaleliz** [comment]
Research plan submitted for review.
