### ISSUE TITLE
Persist Form 10-10CG Submissions (Research + Implementation)

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#10280]
**Implementation**: 
- [x] Create `form1010cg_submissions` table [PR #5444](https://github.com/department-of-veterans-affairs/vets-api/pull/5444)
- [x] Create additional index on `carma_case_id` [PR #5444](https://github.com/department-of-veterans-affairs/vets-api/pull/5444)
- [x] Create additional index on `claim_guid` [PR #5444](https://github.com/department-of-veterans-affairs/vets-api/pull/5444)
- [x] Update the data type for claim_guid (mistakenly set the column as String vs UUID). https://github.com/department-of-veterans-affairs/vets-api/pull/5459
- [x] Merge migrations first
- [x] Create factory for new model [PR #5447](https://github.com/department-of-veterans-affairs/vets-api/pull/5447)
- [x] Update Models (`CaregiversApplicationClaims`, `Form1010CGSubmissions`) [PR #5447](https://github.com/department-of-veterans-affairs/vets-api/pull/5447)

**Draft Implementation**:
https://github.com/department-of-veterans-affairs/vets-api/compare/draft_attachment_job_implementation?expand=1
https://github.com/department-of-veterans-affairs/vets-api/pull/5460

**Questions**:
- Do we want to store the metadata generated?
  - **Yes** `t.json :metadata # The raw json send to CARMA as metadata on the submission req `
- Do we want to store the transformed-data/request-payload submitted to CARMA, for record-keeping
  - **No** entire request payload not needed and these all should be deleted right after processing is completed.
- Do we want to store the request payload and headers from the client POST request
  - If so this should be an added feature of SavedClaim and other forms doing this would need to migrate their data over the saved_claims table once the column is added.
  - **No**. These records are not intended to be stored for longer than needed to process so storing information without a direct need to reference it for processing should not be done. 

**Considerations**:
- ✅ We should always use the claims `guid` as the reference on the `form_1010cg_submissions` table since all claims are deleted after (i believe) 60 days.
- ✅ We should also update the CARMA data contract to have us send the `guid` of the claim vs the `id`.
  - Completed: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11204
- ✅ Avoid having a `claim` without a `submission`, and a `submission` without a `claim`
  - This is accomplished with the associations above and the `dependent: :destroy` argument. Just be sure to associate the related model before saving the target one, this will save both in a single transaction.
    - Example:
    ```rb
      submission.claim = claim # an unsaved claim and submission
      submission.save # both saved in single transaction
    ```
- ✅ Avoid database errors from bubbling up to the user if a claim successfully made it to CARMA 
  - We will only persist the claim and submission when firing the background task(s) to send attachments. Both records will be deleted when done. We will still send the submission itself to CARMA within the req/res cycle and not present an error to users if persistence fails (to avoid false negatives).
    - Example:
    ```rb
      # in application thread
      submission.claim = claim # unsaved claim and submission
      submission.save # both saved in single transaction
      # NOTE: #save! could still raise an error (i.e. `PG` exception), consider keeping this in a `begin; rescue;`  block
      Form1010cg::DeliverAttachmentsJob.perform_async(claim.guid)
    ```
    ```rb
      # in worker thread
      def perform(claim_guid)
        submission = Form1010cg::Submission.find_by!(guid: claim_guid)
        # ... send attachments
        submission.destroy! # destroys both claim and submission in single transaction
      end
    ```

**Code Snippets**
```rb
# db/migrate/*_create_form1010cg_submissions.rb

class CreateForm1010cgSubmissions < ActiveRecord::Migration[6.0]
  def change
    create_table :form1010cg_submissions do |t|
      # Salesforce record IDs are 15 or 18 characters long
      # The 18 digit ID is case insensitive whereas the 15 digit ID is case sensitive
      t.string :carma_case_id, null: false, limit: 18
      t.datetime :accepted_at, null: false
      # Other relations are not storing FKs. So rather than `t.reference :saved_claim`, store and index the claim's guid, then add relations in the ActiveRecord models
      t.uuid :claim_guid
      t.json :attachments # can save as null and update if we send one attachment at a time
      t.json :metadata # debating null: false

      t.timestamps null: false
    end
  end
end
```
```rb
# db/migrate/*_index_form1010_cg_submissions_on_claim_guid.rb

class IndexForm1010CgSubmissionsOnClaimGuid < ActiveRecord::Migration[6.0]
  disable_ddl_transaction!

  def change
    add_index :form1010cg_submissions, :claim_guid, unique: true, algorithm: :concurrently
  end
end
```
```rb
# db/migrate/*_index_form1010_cg_submissions_on_carma_case_id.rb

class IndexForm1010CgSubmissionsOnCarmaCaseId < ActiveRecord::Migration[6.0]
  disable_ddl_transaction!

  def change
    add_index :form1010cg_submissions, :carma_case_id, unique: true, algorithm: :concurrently
  end
end
```
```rb
# spec/factories/form1010cg/submission.rb

# frozen_string_literal: true

FactoryBot.define do
  factory :form1010cg_submission, class: 'Form1010cg::Submission' do
    claim_guid { build(:caregivers_assistance_claim).guid }
    carma_case_id { Faker::Alphanumeric.alphanumeric(number: 15) + 'CAK' }
    accepted_at { DateTime.now }
  end
end
```
```rb
# app/models/form1010cg/submission.rb
class Submission < ApplicationRecord
    self.table_name = 'form1010cg_submissions'

    belongs_to :claim, class_name: 'SavedClaim::CaregiversAssistanceClaim',
                       foreign_key: 'claim_guid',
                       primary_key: 'guid',
                       inverse_of: :submission,
                       dependent: :destroy

    # This allows us to call #save with a nested (and unsaved) claim attached.
    # Tt will persist both models in one transaction
    accepts_nested_attributes_for :claim

    # TODO: Add validations
```
```rb
# app/models/saved_claim/caregivers_assistance_claim.rb
class SavedClaim::CaregiversAssistanceClaim < SavedClaim
  has_one :submission, class_name: 'Form1010cg::Submission',
                       foreign_key: 'claim_guid',
                       primary_key: 'guid',
                       inverse_of: :claim,
                       dependent: :destroy

  accepts_nested_attributes_for :submission

  def submitted?
    submission.present?
  end
```

**Comment by kevinmirc** [comment]
Completed.
