### ISSUE TITLE
Add react widget to caregiver program page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10285]
## Issue Description
We need to add the new react widget to the caregiver program page. We should do this **after** the URL change is complete on the published page.

---
## Tasks
- [x] Add react widget (details in this ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8853). Save as draft.

## Acceptance Criteria
- [x] React widget added to draft page, and ready to be published when we get the go-ahead from the caregiver team that application is ready to go.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
The react widget was added to this page but saved as a draft. Waiting till Monday 6/22 for Nick to turn the flipper on to screenshot the widget in the page, as well as then publishing this page.

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Widget is on and published now, right? Moving to validate, but feel free to move back if it's not published yet.

**Comment by RLHecht** [comment]
Widget is on the live page. Closing ticket. FYSA @stephorkandatx @DanielleThierryUSDSVA
