### ISSUE TITLE
Sentence case on Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10289]
## Issue Description
We need to address the capitalization for the first search parameter within the Facility locator search box to be consistent with the [style guide](https://design.va.gov/patterns/form-labels)

## Current behavior on Facility Locator search page
`Search by city, state or postal Code`

![image](https://user-images.githubusercontent.com/55411834/84801479-77fcf380-afbc-11ea-987b-026777b1e444.png)

Phone number labels should also be sentence case: 
- `Main number`, rather than `Main Number`
- `Mental health`,  rather than `Mental Health`
![image](https://user-images.githubusercontent.com/55411834/85316988-e2110f00-b47a-11ea-8fe0-d16731282299.png)

Need to add space between the end of "Can’t find what you’re looking for?" and "Try using our other tools to search." 
![image](https://user-images.githubusercontent.com/55411834/86399902-0b911e00-bc65-11ea-9286-7bdbac22c8af.png)

## Current behavior on Facility Locator detail pages
![image](https://user-images.githubusercontent.com/55411834/85316798-965e6580-b47a-11ea-9f52-fea16ef2c295.png)

---
## Tasks
Facility Locator Search page: 
- [x] Change `Search by city, state or postal Code` to `Search by city, state or postal code`
- [x] Add space between `Can’t find what you’re looking for?` and `Try using our other tools to search.`

On search result cards
- [x] Change `Main Number` to `Main number`
- [x] Change `Mental Health` to `Mental health`

Facility Locator Detail pages
- [x] Change `Main Number` to `Main number`
- [x] Change `Mental Health` to `Mental health`
- [x] Change `Hours of Operation` to `Hours of operation`
- [x] Change `View on Map` to `View on map`

## Acceptance Criteria

When a Veteran visits https://www.va.gov/find-locations, sentence case will appear for all search parameter field labels, including

- [x] `Search by city, state or postal code`

When a Veteran visits https://www.va.gov/find-locations, 
- [x] there will be a space between `Can’t find what you’re looking for?` and `Try using our other tools to search.`

For **all** facility types, any reference to phone number, map or hours of operation on the search results card or detail page will use sentence case, including: 
- [x] `Main number`
- [x]  `Mental health`
- [x]  `Hours of operation`
- [x]  `View on map` 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Added additional areas for edit based on feedback from Peggy in [#9984](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9984) https://github.com/department-of-veterans-affairs/va.gov-team/issues/9984#issuecomment-646236184
