### ISSUE TITLE
Web Performance - Real User Monitoring for VA.gov users

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#1028]
## High Level User Story

As a VA.gov or VSP engineer I want to track actual user data in addition to synthetic monitoring. 

### Problem Statement
As a VA.gov engineer, I have no means of tracing user performance per session or any other active details for real data traffic.

We should investigate if any other teams are working on this and/or what options are available to us in this regard. Google Analytics may give us a set of useful informations.

### Background

[Synthetic testing](https://raygun.com/blog/synthetic-testing/)
[Real User Monitoring](https://en.wikipedia.org/wiki/Real_user_monitoring)

## Hypothesis/(es)
If we can use RUM effectively on VA.gov we will understand more closely how our users experience our site, in real-time, and potentially unlock session tracing and other datapoints.

## Goals
More data-driven understanding of VA.gov users.

## Objectives
This work supports O2 and O4:

> O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.
> VA.gov user satisfaction

> O4: All of the Platform's KPIs are easily measured and shared openly.

## Definition of Done
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Epic`**
