### ISSUE TITLE
Create React Widgets for Hearing Aid and Prosthetic Socks pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#10282]
## Issue Description
_The current page, https://www.va.gov/health-care/order-hearing-aid-batteries-prosthetic-socks/, will be split into two (one for ordering hearing aid supplies and the other for prosthetic socks). The new hearing aid supplies page will link to the static landing page for Form 2346 (ordering hearing aid supplies). React widget need to be created for each page based on the mockups provided below. Contact @lunascoop or @leahkeeler for any questions._
- [Unauthenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077289_Content_Page_-_Unauthenticated_-_Desktop)
- [Authenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077290_Content_Page_-_Authenticated_-_Desktop)

Also, here are the current draft drupal pages if it helps:

- http://preview-prod.vfs.va.gov/preview?nodeId=5681
- http://preview-prod.vfs.va.gov/preview?nodeId=36

---
## Tasks
- [ ] _Create React widget for Ordering prosthetic socks page_
- [ ] _Create React widget for Ordering hearing aid supplies page_

## Acceptance Criteria
- [ ] _React widget for Ordering prosthetic socks page should take user to eBenefits_
- [ ] _React widget for Ordering hearing aid supplies page should take user to online tool_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
PR is open -

## Unauthenticated state
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/e649d67e-4dac-4b9a-8eb1-f0838e032dac)

## Auth state
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/4a6ecfe7-c6d9-440f-97e3-61d4fa5d3ea8)

**Comment by ncksllvn** [comment]
A thing to note is that the button text under Auth State is proper case instead of sentence case. I think this is shared behavior for all call-to-action prompts after login. We can change this if we want to although I'd prefer to do that separately.

**Comment by ncksllvn** [comment]
This is ready! 

In Drupal, the React widget type is `cta` (call-to-action) and second field is (I think called the `app-id`) is `hearing-aid-supplies`. The widget at `/change-direct-deposit/` is an example of how to set this up.

**Comment by MickinSahni** [comment]
Landing pages are complete in Drupal draft form
