### ISSUE TITLE
On-Site Search: Implement typeahead prototype on Staging

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#10291]
## Issue Description
To integrate and further test and refine the new Search.gov Type-Ahead feature on VA.gov, we are ready to build a __Staging-only prototype.

Once this is in place, we will:
- Schedule upfront accessibility review with the Platform team
- Determine and implement any final UX refinements.  Initial observations and suggestions from @andaleliz are outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9486)
- On a parallel track, we are working with Search.gov to address open issues related to the quality of the Type-ahead search suggestions.

## Tech details
We have a rough implementation preserved in this [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/12975). That work made the assumption that we [needed an API key](https://github.com/department-of-veterans-affairs/vets-website/pull/12975/files#diff-69cccdbf50d4763248d30ee5d30b0281R37), but we do not, so the references can be removed. The search.gov API is completely public and after some conversation, it seems best to hit the API route directly.

The work in that branch shows how a quick prototype could be implemented, but it was built off of some of our current implementations of type-ahead which are semi-old, so we could probably improve considerably -

1. The UX and markup should be improved
    - See this convo - https://dsva.slack.com/archives/C011K1VSTC3/p1592853360008800
1. Should we even use `<Downshift/>`? I'm not sure I see the advantages besides consistency in the project.
1. Lots of separate SCSS that probably isn't necessary 

## Tasks
- [ ] Collaborate with a back-end engineer to execute the work
- [ ] Implement search.gov type-ahead method into Vets-API

---
## Acceptance Criteria
- [ ] Search.gov Type Ahead feature is available for testing and refinement on staging.va.gov

**Comment by ncksllvn** [comment]
Huh, wow, I just edited this issue description and was about to follow up with more detailed technical info when I learned that the API key is actually _not_ required for this. I was confused why the [admin docs](https://search.usa.gov/sites/7378/type_ahead_api_instructions) didn't mention the API key at all. All of this time I was working like it was a required parameter...but it is not 😮 

So hm, I have to think about this - on one hand, we don't need to build a new API route because we can hit the search.gov API from the browser directly. On the other hand, the front-end typically only engages directly with the API and not any other services. So I feel like the API route should still be built, but I'm gonna think about this a bit longer.

**Comment by ncksllvn** [comment]
Docs from search.gov admin - 

---------

<div class="api-instruction">
<p>This API exposes the type-ahead suggestions that usually appear below your search box as searchers enter their search terms.</p>

<h2>Resource URL</h2>

<p>The endpoint is <code>https://search.usa.gov/sayt</code>.</p>

<h2>Required Parameters</h2>

<p>Two parameters are required: <code>name</code> and <code>q</code>.</p>

<p><code>https://search.usa.gov/sayt?name=va&amp;q={YOUR_SEARCH_TERM}</code></p>

<ul>
<li>The value for the name parameter is your site handle on the <a href="/sites/7378/setting/edit">Settings</a> page.</li>
<li>Replace {YOUR_SEARCH_TERM} with a word or phrase of your choice.  A minimum of 2 characters term is required.</li>
</ul>

<h2>Responses</h2>

<p>You will see an array of suggestions. Suggestions are derived from the searches performed on your website.</p>

<p>Up to five suggestions related to your visitors' search term are returned and are updated in near real time.</p>

<p>A given term/phrase must be searched 10 times in a 24 hour period to appear as a suggestion. Suggestions will drop from the list if they don't maintain the 10 times per 24 hour period threshold.</p>

<p>If you want a given term to always appear as a suggestion, please contact our team.</p>

<p>Note: inappropriate terms are filtered by our system and will not be presented as suggestions.</p>

<h2>Terms of Service</h2>

<p>By using this API, you agree to our <a href="https://search.gov/tos">Terms of Service</a>.</p>


</div>

**Comment by ncksllvn** [comment]
Just to close the thread above, after a convo with other engineers, it seems like the best route is to hit the search.gov API directly because it's intended to be hit every keystroke, so it'll be more performant without a middleman in vets-api.

**Comment by johnhashva** [comment]
And per my Slack message, believe the remaining sequence here as a prototype are:

- [ ] Get on staging
- [ ] Review with Design/UX (@rtwell and @andaleliz] week of 6/29 for final alignment on any styling/functional changes
- [ ] Request accessibility review

In parallel, we are working with Search.gov to resolve "quality of suggestions" issues.

**Comment by ncksllvn** [comment]
Crosslinking to Slack thread containing design/markup suggestions - https://dsva.slack.com/archives/C011K1VSTC3/p1592853360008800

**Comment by johnhashva** [comment]
Per convo with @ncksllvn today -- since the "as is" implementation of Search.gov type-ahead is not optimal, we want to limit the exposure of the feature on staging.va.gov by limiting the feature to one page of the site.   As a follow-on, we talked about possibility deploying with a feature flag/flipper to expose 1% of the VA.gov audience to the feature to gauge user insight.

**Comment by ncksllvn** [comment]
This is merged and will be on staging later today! The feature flag is two-fold - typeahead will render on only the __homepage__ of dev or staging

**Comment by ncksllvn** [comment]
Typeahead!

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/5ffa229d-2027-4872-b40c-ebcc16917974)
