### ISSUE TITLE
[Launch] BDD: UAT Testing for Benefits Delivery at Discharge

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10298]
## User Story
After staging review we will be ready for UAT.

We have prepared a UAT plan and have been waiting to pull the trigger on scheduling.

This story is capturing the work to do the UAT as well, not just the creation of the plan.

## Tasks
- [ ] Final test users and test script defined
- [ ] Schedule UAT with Perigian

## Acceptance Criteria:
- [ ] 5-6 users UAT'ed

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
10 real users will be invited to go through BDD flow (and normal claim flow).

**Comment by chrvalla** [comment]
External UAT testing planned for September 8 and 9. Only 2 participants have been located so far. Blocker.

**Comment by luke-gcio** [comment]
We are going with plan B, we did the UAT testing we were planning on doing for the moderated UAT.
