### ISSUE TITLE
Synthesize user research on facility operating status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10295]
## User Story
As a Veteran, I need to know when a facilities access or services have been impacted by an emergency so that I can adjust my plan to visit.

## User research
Veteran sessions were conducted during the week of June 8 and June 15, with the goals of validating our assumptions about communicating facility operating status.  

---
## Tasks
**Considering the questions below,**
- [x] **Provide top line findings to inform next steps** 
- [x] **Create research readout with synthesis from user sessions**

--- 

- How well do Veterans understand the current messaging/categorization of statuses? 
    - What does the "Closed" operating status mean to Veterans?
    - What does the "Limited Services" operating status mean to Veterans?
    - What does the "Facility Notice" operating status mean to Veterans?
    - Do the labels make sense? 

- How do Veterans expect virtual services/telehealth to be represented? 
- What new categories need to be added, if any?
- What additional information do Veterans need regarding changes in facility availability? 
- What changes could be made short-term and long-term to better prepare Veterans to visit a facility or receive services?

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
Research Findings:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/facility-status/research-findings.md

Topline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/facility-status/topline-summary.md
