### ISSUE TITLE
[POST 686 LAUNCH] Optimize Load Times

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10308]
## Goal
The overall page load time for VA.gov could probably be improved and we want to see if there are any things we can do to our feature that would allow pages to load faster and potentially pass those ideas on to other teams to imbue the site with faster load times.

## Tasks
- [ ] Create a list of potential problem areas for our feature (and perhaps VA.gov)
- [ ] Create a list of solutions that map to those areas 

## Acceptance Criteria
- [ ] A list of solutions has been documented and potentially implemented via a PR
