### ISSUE TITLE
Adjust 686 FE for VA File Number Check

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10304]
## Goal
One of the outcomes from our discussions on how to best implement the VA file number check was to pass a boolean value as opposed to an actual numeric value that might be associated with personal info.

## Tasks
- [ ] Collaborate with the BE and learn how best to proceed
- [ ] Implement the change in the check

## Acceptance Criteria
- [ ] The VA file number check uses a `TRUE / FALSE` passed from the backend instead of the actual number.
- [ ] A PR has been requested for merging.
