### ISSUE TITLE
Debt Letters MVP Content Support from Benefits & Memorials 2

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#10315]
## Why you're here
- Content support for static public website pages
- Content support for authenticated application or tools

## Steps to complete intake request
- [x] Submit this request when VSA Public Website team intervention is required
- [x] Provide detailed information of your request to help us understand our role in completing your request 
- [x] Link to this issue in #vsa-public-websites in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Background
*Provide a background of your tool/functionality.*

When Veterans become indebted to the VA, they receive multiple letters notifying them of their debt and how to resolve their debt. Legislation passed in 2017 that requires the VA to provide Veterans access to these letters online.
* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
   * BaM2 is building functionality that will provide Veterans with an overview of their debt, their debt history, access to letters and statuses associated with their debt, and next steps to resolve that debt. 
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp)
   * [Discovery research readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/research-readout.md)
   * [Wireframes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md)
   * [Current VA Debtman site](https://www.va.gov/debtman/)

### Request Type
*Select all applicable and provide details behind your request* 

- [X] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * Word document with draft if available, or link to the URL where the draft content appears:
      * Please reference [the current VA Debtman site.](https://www.va.gov/debtman/). We'd like to create a new hub to reimagine Debtman in a more empathetic and user-friendly format. 
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * < design context >
   * Scope: How many screens? (Or messages, etc.) 
      * Unsure how many screens; would like content guidance since we're creating a new hub for VA debts/debt letter access. 
      
      
- [X] **Content support for a static public website page**
   * Is this to update existing static content? 
      * N
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * Y
   * Provide a list of URL/s that need to be reviewed or updated. 
      * [Current VA Debtman site](https://www.va.gov/debtman/)
   * If it's a small copy section, list what the new info should be and what it is replacing.
      * < list of new info >

- [ ] **New URL or Redirect Requests**
   * Have you vetted this request by the VSP IA team?
      * < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * Link to VSP IA Redirect Request ticket
      * < Github issue link >
      

   
- [ ] **Implementation of REACT sign in widgets**
   * Full spec including different states and behaviors
      * < link to spec >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*

* <Desired/target implementation date>
Would be nice to have for usability testing in early July (not yet firmly scheduled), but completely understandable if the work cannot be completed in time. @leahkeeler may be able to provide a target implementation date. 

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: Benefits & Memorials 2
- DEPO product owner: Matthew Self
- Product manager: Leah Keeler
- Designer: Riley Orr, Rebecca Walsh
- FE engineer: Brad Conley, Mahariel Rosario
- Product/team Slack channel: vsa-bam-2

--- 
#### Acceptance Criteria
- [x] Convert this request into a Zenhub epic
- [x] Follow-up with requestor to address any lingering questions/concerns
- [x] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by lunascoop** [comment]
Hi @mnorthuis I'm not sure if there is an associated IA ticket for this request, but I think we need to meet to discuss this w/ @DanielleThierryUSDSVA and @peggygannon. We're looking to meet next Tuesday at 1-2pm. @DanielleThierryUSDSVA will be sending out an invite.

**Comment by DanielleThierryUSDSVA** [comment]
**Debt-related health care pages for reference:**

https://www.va.gov/health-care/pay-copay-bill/
https://www.va.gov/health-care/pay-copay-bill/dispute-charges/
https://www.va.gov/health-care/pay-copay-bill/financial-hardship/

**Comment by mnorthuis** [comment]
Connecting this to the IA request:  https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/9686

**Comment by DanielleThierryUSDSVA** [comment]
# Notes from 6.23.20 meeting

**Attendees:** 
@lunascoop, @DanielleThierryUSDSVA, @peggygannon, @mnorthuis, @bethpotts 

**Discussion:** 
- We'll have a standard tool landing page that will drive to the authenticated experience.
- We're not aiming to consolidate the full Debt Management site into our benefit hubs.
- Landing page will likely like at the root level or within Records. Mikki to determine final IA placement.
- We need to assess the volume of FAQ content to determine how to best handle. Will likely include some relevant FAQs on the tool landing page and some relevant FAQs within the authenticated experience.
- We'll need to align on content across authenticated/unauthenticated content.
- We'll need to assess how this page will cross link with the debt content within health care.
- We'll need to assess entry points to this page within benefit hubs.

**Next steps:**
- [ ] Danielle to create issue for content FAQ list
- [ ] Selina to review Debt Management site pages and compile potential FAQs list (aiming for EOD 6.25.20)
- [ ] Beth, Danielle, Peggy, Selina to meet and agree upon FAQs for unauthenticated vs. authenticated content (aiming for 6.26.20)
- [ ] Once we've determined FAQs for unauthenticated vs. authenticated, PW team will develop full content for unauthenticated page (and Peggy will work with team on authenticated content)
- [ ] Selina to review Debt Management site

**Comment by DanielleThierryUSDSVA** [comment]
# Notes from 7.1.20 meeting

**Attendees:**
- Product team (Becca , Matt, Leah, Riley)
- PW team (Beth, Danielle, Selina)
- Platforms team (Mikki, Peggy)

**Discussion:**

**- Reviewed unauthenticated content approach mockup/FAQs.** Standard tool landing page for MVP (with high-level FAQs that link off to the relevant pages on the Debt Management site for more details). Post-MVP launch, Platforms IA (Mikki) and PW content strategy (Danielle) will work to explore/propose approaches for fully migrating Veteran-facing debt information from the current Debt Management site into the modernized VA.gov experience.

**- Confirmed details/approach:**
  - Overall approach works for MVP.
  - Only Veterans can use this tool at this time (not spouses, dependents, or survivors who may have debt)
  - We may need to remove and/or change the wording of the bullets around getting the current status of, and next steps for resolving, benefits. This will depend on final features of tool at launch. Product team will keep PW team updated.
  - Veterans need an LOA3 account to use this tool since it shows financial information. We'll include the standard react widget approach to sign in on this page.
  - We do want information around calling about debt questions to be prominent, as this is an important option for Veterans to have especially when trying to fill out their financial status report.
  - Health care debt is not included in this tool at this time. We'll go with the PW recommended approach of providing related links to health care debt info on VA.gov.
- **For usability test week of July 13:** 
  - We need main content for the unauthenticated landing page (full content within accordions not needed at this time)
  - We want to test whether Veterans understand this page and can successfully get into the tool as well as whether the questions in the accordions are a) covering all key high-level topics and b) worded in a way that Veterans know which to choose to answer their questions.
  - We want to also test which FAQs we might need within the authenticated experience.

**Immediate next steps:**
- [ ] Danielle and Peggy to align on authenticated content and needed FAQs (7.2.20)
- [ ] Danielle to update unauthenticated landing page mockup, and suggested authenticated FAQs, and provide to product team for usability testing. (7.10.20)
- [ ] Product team to invite PW and platforms representatives to usability testing (week of 7.13.20)

**Future next steps involving our team (dates tbd):**
- [ ] Selina to work on content within accordions and build Drupal page
- [ ] Danielle/Beth to edit accordion content  
- [ ] PW team to incorporate findings from usability testing into unauthenticated content
- [ ] PW/platforms/product teams to continue to align on content across unauthenticated > authenticated experience
- [ ] Teams to present content for SME and collaboration cycle review
- [ ] PW team to incorporate final edits and publish Drupal page

**Comment by leahkeeler** [comment]
Hi @DanielleThierryUSDSVA @MickinSahni Do we have a timeline for when this work will be completed? I am working on setting a release date. Much appreciated - Leah

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. We have the timeline through delivering content for usability testing (today). We're on track for that, and will send over this afternoon.

We'll then work with you on timeline for finalizing content and building out the page, based on the release date. If you can let us know the date, we can work together to work backwards from there to figure out when content needs to be completed and reviewed with SMEs. Thanks!

**Comment by leahkeeler** [comment]
Thank-you @DanielleThierryUSDSVA - I will update you on release date for iteration 1 late tomorrow afternoon. Appreciate your help - Leah

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA - wanted to give you a heads-up. We have a tech meeting this Friday that will provide (hopefully)_ some clarity around ability to tie DMC - vbms, stay tuned to release date-- "it's always about the data" right?

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @leahkeeler!
