### ISSUE TITLE
[Backend] Urgent care mash-up

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10318]
## Issue Description
Research feedback: Veterans want to see all facility types in single result list when the Facility type = Urgent care searches

---
## Tasks
- [ ] Build backend endpoint which will return results from VA controller and CCP controller together

## Acceptance Criteria
- [ ] Backend endpoints can support urgent care search results from 

1. CCP controller **ONLY** or
2. VA controller **ONLY** or 
3. **BOTH** VA controller **AND** CCP controller

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
