### ISSUE TITLE
Build Out Fields/Components for VRE (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10316]
## Goals 
Now that the initial page and folder structure are in place, we need to start filling in the larger components and fields on the frontend so we can get this closer to staging.

## Tasks
- [ ] Check in with the backend and see if there is anything they can tell us ahead of time as far as what what the data structure might look like, else create some placeholders for now
- [ ] Based on provided [mockups/prototypes](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526674), fill in the fields and components needed.

## Acceptance Criteria
- [ ] The feature more closely resembles what is intended from Design
`is this in staging or local?`
