### ISSUE TITLE
PPMS Down Status Notification

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10319]
## Issue Description
How can we make Veterans aware that community care searches are temporarily unavailable? Because we have the ability to flip off PPMS searches in the event of a bug, we should provide information about the downtime. 

---
## Tasks
- [ ] Determine best method for notifying Veterans about temporary search disruptions

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@swirtSJW Can we use a Sitewide Banner on Facility Locator? That might cover this use case
