### ISSUE TITLE
Migrate "View Rated Disabilities" from eBenefits to va.gov

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#1032]
# View Rated Disabilities

Issue brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/issue-briefs/profile-rated-disabilities.md

Link in staging: https://staging.va.gov/disability/view-disability-rating/rating

[Current Mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/)

## Story

As a Veteran I want to see a list of my rated disabilities and my total disability rating so that I can review it to check VA data, and make sure I'm getting the care and benefits I deserve.

## Considerations

- This should exist as a single web page at https://www.va.gov/disability/view-disability-rating/rating, but we should coordinate with authd-exp to see if it should also be a dashboard widget
- On eBenefits a representative can see a Veteran's list of rated disabilities. We will not have the capacity to do this until va.gov supports user roles and relationships.
- eBenefits shows both current and pending ratings; is this part of the same service? Or all there two separate service calls?

## Definition of Done

- [x] A logged in LOA3 user with rated disabilities in CorpDB can see a list of their own current and pending rated disabilities on va.gov
- [x] A logged in LOA3 user viewing their rated disabilities on va.gov can see their total disability rating

## Pilot Tasks

- [x] Investigate and understand how the Electronic Veterans Self Service (EVSS) rated disability service is already integrated into the va.gov stack
- [x] Investigate whether "pending" ratings are provided in the same or a different service
- [x] Investigate how the total rating is calculated, or whether that calculation is delivered as part of the service
- [x] Build a simple prototype page that calls the EVSS rated disability service for the current user and renders the list(s) & calculation to the front end
- [x] Handle exceptions for user-not-found, no-ratings-found, etc
- [x] Design and conduct light usability on the lists & calculation
- [x] Add "View My Rated Disabilities" link and description to https://www.va.gov/disability/ (likely under "Manage your Veterans disability benefits")

## Further Tasks

- [x] Understand why users access this list and what their further tasks might be. Develop working theories about potential useful pathways. 
- [x] Determine whether other information might fit correctly on this page, or whether this application might be better integrated into e.g. Claim Status/ Appeal Status
