### ISSUE TITLE
Implement connected apps content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10327]
## Issue Description
Once we've finalized content with the Lighthouse team, we'll need to flow the approved content into the Sign in FAQs page. 

---
## Tasks
- [x] Flow approved content into page (Content writer)
- [x] Review for errors and omissions (Randi)
- [x] Keep as **draft** until Profile 2.0 launches (Danielle to create calendar reminder to sync with Samara on publish date)

## Acceptance Criteria
- [x] Approved content in Drupal and saved as draft
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here's content for a new subsection of the Sign in FAQs page (https://www.va.gov/sign-in-faq/). 

Before we assign this to a content writer to implement in Drupal, could you give the doc a look just for typos/omissions? Thank you!

[Draft content 3_connected apps help info & faqs_dt_6.17.20](https://app.zenhub.com/files/133843125/046e4c11-8eee-4def-8325-678aa3db1b2e/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here's my edited copy. Just a few copy tweaks.
[connected third party apps faqs-RH edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4801098/connected.third.party.apps.faqs-RH.edit.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht! I've accepted your edits and made one additional edit. 

@stephorkandatx This is now clean and ready for a content writer to implement.  We should save in **draft** until profile 2.0 launches.

[connected.third.party.apps.faqs.final.6.23.20](https://app.zenhub.com/files/133843125/703d4fab-26e0-4341-b93e-b6398c45f978/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Do you think you could work with one of the content writers who has some time to implement this? Want to make sure we're doing: content writer implements, copy editor reviews to maintain best practice. 

If we can do this in time for end of sprint, great. If it needs to be pushed to early next sprint, that's okay too. And we should save as draft until Profile 2.0 launches.

Thanks!

**Comment by lunascoop** [comment]
Hi @RLHecht I added the section and tweaked a few things (which you may want to undo):

- I unbolded  some of the content.

- I was having issues w/ the aria labels for the phone numbers. The code is showing up in the preview (not sure if it should) and it seems the TTY number isn't working. I referred to the coding in the content style guide.

http://preview-prod.vfs.va.gov/preview?nodeId=713

**Comment by RLHecht** [comment]
@lunascoop I reviewed this and fixed the issues you mentioned above. I put back in the bold copy and fixed the aria labels. Not sure what the issue was. Had you selected "Source" before typing it in?

Also, could you change the accordions that have numbered steps in it into process lists? Then I'll review it again.

**Comment by lunascoop** [comment]
@RLHecht I changed the numbered steps into process lists. It's ready for review.

**Comment by RLHecht** [comment]
@lunascoop This looks great, thank you! @DanielleThierryUSDSVA This is ready to go when we are. I'll move this to validate and we can publish when Profile 2.0 launches.

**Comment by MickinSahni** [comment]
Can be closed out
