### ISSUE TITLE
Synchronize Payment History Design with Frontend

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10322]
## Goal
In order to move payment history further along, we need to match the frontend with what we have in frontend

## Considerations
[Prototype](https://preview.uxpin.com/546893e0b210374a0734240e0ca9fccc2e02ed11#/pages/129039987)

## Tasks
- [x] Add/remove some items
- [x] Logic/sorting (separate ticket?)
- [x] change padding spacing

## Acceptance Criteria
- [x] The frontend matches as close as possible with what we have in the prototype from design
- [x] The changelog has been updated _({feature-name/research-design/changelog/README.md})_
