### ISSUE TITLE
Finalize Mobile View of "View payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10323]
## Goal 
In order to get this feature moved along we need to nail down the mobile (responsive) design that frontend will need to build.

## Tasks
- [x] Complete design screens that will show how this feature will look on a mobile device.
- [ ] Reach out to Ryan T, if needed

## Acceptance Criteria
- [x] The design has been updated and shared with the FE
- [x] The changelog has been updated _({feature-name/research-design/changelog/README.md})_

**Comment by sporeboy** [comment]
Revisions made and links posted to Slack. Table elements revised using elements from VA sketch library; will forego Ryan T review.
