### ISSUE TITLE
Disable Community Care Facility detail pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10324]
## Issue Description
There are a number of issues impacting facility detail pages for Community Care providers (in VA's network):

- There are discrepancies between the name displayed on detail pages compared with the name displayed in search results
- Provider details may or may not be populated 
- Provider details may or may not have value for Veterans
- Some services have missing descriptions
- Duplicate IDs for providers practicing at more than one location causes the display of incorrect details for a selected provider

As a result, we will hide facility detail pages specifically for Community care providers. 

NOTE: Determining how to handle existing bookmark links to detail pages for community care providers is a separate request, based on analytics [#11133](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11133)

---
## Tasks
- [ ] Hide detail pages for **all** community care providers
- [ ] Remove links from search results to detail pages for community care providers

## Acceptance Criteria
- [ ]  When facility type = Community care providers (in VA's network): 
Community care search results cards will not have links to Facility Detail pages 
- [ ] Existing functionality for VA facility detail pages is maintained (for each VA facility type: health, benefits, cemetery, Vet Centers)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
@mmiddaugh Is this task part of this ticket, or a separate one? 

> Determine how to handle existing bookmark links to detail pages for community care providers (separate request, based on analytics)

**Comment by mmiddaugh** [comment]
Good question, @mpelzsherman 
I put the analytics in a [request for input on redirects](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11133) but forgot to link it to this issue.

**Comment by mmiddaugh** [comment]
Validated this is behaving as expected. Thanks!
