### ISSUE TITLE
Implement PPMS 8.1 changes to PlaceOfService function

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10326]
## Issue Description
PPMS 8.1 includes changes to the PlaceOfService fucntion which were intended to improve performance and streamline queries. 

**New fields**
- Addition of POS codes for each response _(this means we will not need to make a second call for urgent care)_
- Geowarning field for confidence intervals related to lat/long

Optional functionality
- Can select subset of fields to be returned
- Removed requirement to pass every parameter in query
- Can pass lat/long for address parameter

---
## Tasks
- [ ] Adjust urgent care query to request all desired fields in one call, including POS codes
- [ ] Remove drive time as a parameter
- [ ] Determine which fields facility locator should send in query for Urgent Care providers
- [ ] Determine which fields are desired in PlaceofService Locator Response
- [ ] Make query adjustments as needed

## Acceptance Criteria
- [ ] Urgent care search functionality is maintained: search results include both 17 and 20 
- [ ] Search functionality for Community care providers 9in VA's network) is maintained
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate
