### ISSUE TITLE
[ANALYTICS] Research and document DAV-VAN information for VA Cheyenne health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10343]
## Story
As a Veteran web user, I need to know the transportation options via DAV-VANs page for my VAMC system.. 

## Goal
_Compile all the Contact Data and related information for DAV-VANS for the VAMC System_

## Objectives or Key Results this is meant to further
- _Reduce click through count_
- _Document pages that can be created in a scalable manner_

## Resources - Tools - Documentation
[VISN-4 DAV](http://eriehealthcare.web.demo.ci.cms.va.gov/erie-health-care/)

## Tasks
_Compile System/local information, contact information and addresses as required on the following pages:_
- [ ] Compile Transportation locations and Phone numbers
- [ ] Organize for areas within the System (VISN if associated)
- [ ] Validate with DAV-VANS corporate site
- [ ] Prioritize by area

## Acceptance Criteria
_Confirm all have been reviewed and updated in the Top Task spreadsheet "See Resources Above"_
* Compile Transportation locations and Phone numbers
* Organize for areas within the System (VISN if associated)
* Validate with DAV-VANS corporate site
* Prioritize by area
