### ISSUE TITLE
[ENGINEER] Map out and Create Admin and Editorial Menus for VISN-19 Systems [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10341]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Instructions to set up Menus for VAMC](https://docs.google.com/document/d/1fz-m_4Eo4Ib7g4s_3pk7Hz4N3uaNnCD1lAppp6KDMrk/edit?ts=5ee3aae7)

## Tasks
_Creation of the following Drupal types/menus Sections_
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado (Grand Junction) health care
- [ ]  VA Montana health care
- [ ] Complete Cheyenne process as only name was created

## Acceptance Criteria
_Validation that all pages are at least created and ready to accept content from Copy editor and/or Front-End engineer_
- [ ] Create Sections in Prod
- [ ] Sync DB to local
- [ ] Create menus locally
- [ ] Edit content types to each System
- [ ] Organize VAMC admin menu for VISN 4 and VISN 19
- [ ] Create PR and commit to Steve Wirt and Kevin Walsh
