### ISSUE TITLE
AE-Sprint 24

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10352]
# Priorities
1. Finish remaining Profile 2.0 design/FE tickets
2. Schedule QA/508 reviews
3. Put together release plan
4. Call Center Product Guide

### PM
Submit requests for QA/508 reviews, Create the Call Center Product Guide, Put together the release plan

- [ ] Submit request for QA review #10764 (Still adding required artifacts)
- [ ] Submit request for 508 review #TBD
- [x] [PM] Put together Profile 2.0 Pre-Launch Release Plan #10354

### Design
Finish remaining design tickets, work on Call Center Product Guide and UAT plan

- [x] Complete Profile 2.0 IA review #9752 
- [ ] Update content and link in Change Address page #8420
- [x] [Design/PM] - Figure out UAT needs for the release plan #10351
- [x] [Design] Profile: Create a generic error state for when direct deposit is down #5959

### Call center

- [ ] Create Call Center Product Guide #7561

### Build
Finish Build/bug fixes and team verifies in staging things are working correctly before beginning official QA

#### Current
- [x] [FE] Build alert for if a user tries to edit multiple pieces of contact information #9433 (2)
- [x] [FE] Build alert for when a user tries to leave page without saving #9436 (3)
- [x] [FE] Contact Info - In the mobile numbers box, remove second unnecessary message #10035 (1)
- [x] [FE] Remove `profile_show_receive_text_notifications` feature flag from FE #9781 (1)
- [x] [FE] Direct Deposit 2.0 does not handle server errors #9819 (1)

#### New
- [ ] [FE] Add integration tests to Profile 2.0 #9563 
- [x] Make sure Profile 2.0 handles upcoming and current downtime #10160
- [x] [FE] Update "We can't access your military information" message in the profile #10246
- [x] [FE] Update connected apps #10330
- [x] [FE] Build state in Direct Deposit where user hasn't set up but is eligible #10312
- [x] [FE] - Contact Info - bump the messaging up to be inline with 'Home' #10049
- [x] [FE] - Create an alert for when user cancels their edit attempt [personal info] #10397
- [x] [FE] - Create an alert for when user cancels their edit attempt [direct deposit] #10398
- [x] [FE] - alert when user navigates away from Direct Deposit entirely without saving changes #10399
- [x] UAT planning with Matt

#### Unplanned
- [x] Remove "what's my routing number?" from Direct Deposit #10540
- [X] Profile blows up when formatting addresses with `stateCode === null` #10571
- [X] [FE] Add grey title on personal information section #10721

### PM (Samara)
- [x] Present work to DEPO team #10177
- [x] Define scope for phase 1 #10176
- [x] Finish OKR and KPI planning #9181
- [ ] Plan for how to incorporate stakeholders #10230
- [x] Metrics conversation with VAOS team #10740
