### ISSUE TITLE
Implement Phase 0 of VA 311 Roll Out Plan

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#10362]
## Issue Description
Work with the VEO Tier 1 Contact Center to implement the tasks outlined for phase 0 of the VA 311 number roll out on VA.gov

---
## Tasks
- [x] Identify phase I-III locations for adding VA 311 number messaging 
- [ ] Draft IVR content for VA.gov line
- [x] Add new telephony line to account for point of origin/call type and skill group (must be completed by VEO)
- [x] Stretch: VA.gov fields available in Salesforce

## Acceptance Criteria
- [x] A spreadsheet that identifies the locations for the VA311 number and tracks which phase content will go out for these locations.
- [ ] New IVR script for VA.gov routing of issues. 
- [x] New telephony line for VA.gov issues (created by VEO)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Created an outline of the places where we would want to add VA 311 messaging. Identified the sign in modal and the profile as the starting place for phase 1 messaging. Still haven't heard back from the VEO group if they are okay with this. 

[VA 311 Messaging Roll Out.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4826575/VA.311.Messaging.Roll.Out.xlsx)

**Comment by clantosswett** [comment]
Chante needs to review and update old documentation and resend out to the contact center team for review. Will upload updated materials once that has occurred.

**Comment by clantosswett** [comment]
Updated roll our plan and spreadsheet with locations for each phase and sent to the VEO tier 1 team for review and feedback. 

[VA 311 Messaging Roll Out.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4985371/VA.311.Messaging.Roll.Out.xlsx)

[VA 311 VA.gov Rollout plan.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4985372/VA.311.VA.gov.Rollout.plan.pptx)

**Comment by clantosswett** [comment]
We remain stuck on this issue because we aren't getting movement from the VEO Tier 1 Contact Center group. When we met on Friday they said they needed to take another week to get more information about the upcoming VA411 campaign and figure out how this might affect them. Moving forward, we are going to start looking at the various help messages that have incorrect messaging in regards to who they should call, and work with the public websites and appropriate VSF teams to write up  new messaging and make a timeline for rolling it out.

**Comment by clantosswett** [comment]
Reviewed phase 1 locations and have identified the places where we should add messaging about the VA311 number. Updates can be found on the attached spreadsheet. Next step will be to draft the content and provide to VA public websites team for review and updating. 

[VA 311 Messaging Roll Out.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5084584/VA.311.Messaging.Roll.Out.xlsx)
