### ISSUE TITLE
[Frontend] Remove ineligible info alerts when products are shown in their product section

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10363]
## Issue Description
Now that all of the products are on a single screen, users won't be directed to a form page without any interaction. Because of this, we will remove *both* alerts that are generated when products are listed but ineligible (for batteries and accessories sections):

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/a58a4c07-5dde-4889-b3de-5b80b48d33f5)

**Note: DO keep the alerts when no products are listed below it, example:**
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/ec927428-f150-458d-8fe8-a72842bf4584)

---
## Tasks
- [ ] Remove the two informational alerts noted above
- [ ] Confirm with designers

## Acceptance Criteria
- [ ] Informational alerts noted
- [ ] Staging user where informational alerts can be viewed noted in ticket
