### ISSUE TITLE
[Analytics] Document Pages and services not migrated in VISN-4 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10364]
## Story
As a Veteran Administrator and PAO,  I need to know the content, pages, and items not included in our migration to the VAMC-upgraded webpages.

## Goal
_Compile and document all pages, health services, and nodes that are not migrated to new VAMC system web sites.._

## Objectives or Key Results this is meant to further
- _Reduce click through count_
- _Document pages that can be created in a scalable manner_

## Resources - Tools - Documentation
[VISN 4 Playbooks](https://drive.google.com/drive/folders/1WygUuvMetcaCm43woL6rfTursUVUyGeO)
* Sites to be included in Comparison:
- [x] https://www.altoona.va.gov/
- [x] https://www.butler.va.gov/
- [x] https://www.coatesville.va.gov/
- [x] https://www.erie.va.gov/
- [x] https://www.lebanon.va.gov/
- [x] https://www.philadelphia.va.gov/
- [x] https://www.wilkes-barre.va.gov/
- [x] https://www.wilmington.va.gov/

## Tasks
_Compile System/local information, contact information and addresses as required on the following pages:_
- [x] Review VISN-4 documents
- [x] Confirm and highlight areas that are not included
- [x] Review and List all pages in Original VISN-4 System site
- [x] Create comparison from Original Site to new System Site
- [x] Highlight all differences

## Acceptance Criteria
_Confirm all have been reviewed and updated in the Top Task spreadsheet "See Resources Above"_
* Comprehensive document of highlighted differences
* Comprehensive comparison with highlighted differences
* Document is stored in SharePoint under VISN-4 By System
