### ISSUE TITLE
Validate Workflows/ Cassettes

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10370]
## Goal
There are many different errors that are possible and we need to validate the workflows and cassettes to ensure they are passing correctly.

## Tasks
- [x] Refine the error handling for the workflows
- [x] Define the different errors for later triage

## Acceptance Criteria
- [x] Workflows have been validated and initial errors have been identified.

**Comment by digitaldrk** [comment]
I have validated and created all flows and cassettes _EXCEPT_ the main one where we fire off everything from the service.

The insertBenefit call is not working 

I have emailed Linda and we're going back and forth about it. I am blocked until this issue is resolved.

**Comment by digitaldrk** [comment]
😎

![image.png](https://images.zenhubusercontent.com/5e62b7b08eb909e3dc9d38f7/cf9d30c4-cd60-4d61-8004-f2aaed71dea9)
