### ISSUE TITLE
Send Newly Created PDF to the eFolder

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10374]
## Goals
One of the major steps in the submission process is to create a PDF from frontend submitted data and send it to the Veterans eFolder via VBMS.

## Tasks
- [x] Send a fresh PDF to the eFolder
- [x] Verify that it has been saved in the eFolder by VBMS
  - Logging into EBN staging where it can be seen `or` ask Steve to check VBMS staging

## Acceptance Criteria
- [x] The PDF has been tested and seen in the eFolder

**Comment by kathleencrawford** [comment]
Notes: We are not able to view the uploaded documents in eBenefits PINT2 environment.  There is some instability going on there - sometimes the My Documents link isn't even available on the dashboard.  It could also be that eBenefits PINT2 is pointing to a different VBMS environment.

Steve was able to log into VMBS UAT environment and confirm that the uploaded documents can be seen for our test user.  We were also able to confirm that we could view the PDF using a URL with an ID generated by VBMS.

Will need to follow up to determine if there is more to do on our end regarding viewing the documents in eBenefits...perhaps find out which environments are mapped to each other or if there is more to be done to view the documents in the "My Documents" folder in eBenefits.
