### ISSUE TITLE
[Analytics] Knowledge Share with VSA, DEPOT, Facilities regarding the research of Health Services [BA] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10376]
## Story
Facilities, VHA, and VSA need better insights into the Challenges, pain points, and obstacles to how VAMC currently collects the data for the health and facility services

## Goal
To find improvements, options to collect data in advance, data mining, and best understand pain/friction points in the data collection methods
* Scalability, and use of existing data sources to pull data

## Resources
[VAMC Analytics Drive](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## Tasks
- [ ] Set up 2 - 2 hour Discovery meeting to include Facilities, Product Owners, BA Team members & Product manager
- [ ] Determine scalability of data provided from RAPIDS system, (Services list) and determine usefulness
* Parse and review relationship, reliability of data, and associated appointments/health services at facilities
- [ ] Quickly present data collection process with System and Facility Health services
- [ ] Highlight points of data collection and friction, pain points, and areas of highest possible errors
- [ ] Present possible improvements

## Definition of Done
- [ ] Document presentation
- [ ] List of action items to improve the process
- [ ] New Story presented to capture the improvements and implement them in future VISNs
