### ISSUE TITLE
[Design] MDT - Create an alternate confirmation screen for Veterans who submit an empty order

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10373]
## Issue Description
Since we will not be able to stop users from submitting empty orders, we must design an alternate confirmation screen for the use case of an empty order submission.

---
## Tasks
- [x] Design an alternate confirmation screen for the use case of an empty order submission
- [x] Upload to invision
- [x] Link invision / documentation to this ticket
- [x] [Update engineering ticket ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10375)with design direction

## Acceptance Criteria
- [x] Design / documentation linked to this ticket
- [x] [Engineering ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10375) updated

**Comment by rileyorr** [comment]
[The mockup has been added to InVision](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/422126004_Empty_Order_Submission) and the confirmation screen's [GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-confirmation-screen.md) has been updated.

**Comment by rileyorr** [comment]
I've updated the frontend engineering ticket, so it should be ready to build!
