### ISSUE TITLE
Strategize Larger PR Submission with Platform

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10371]
## Goal
The submission payload PR for the 686 is extremely large and we want to ensure we have the right game plan for submitting this per Platforms instructions and give some awareness to what is coming.

## Considerations
- Everything is made up and maybe we can get an exception for a one time larger merge
- Include Steve 

## Tasks
- [x] Schedule and attend a meeting with someone from Platform (JP perhaps?) that can give some guidance on a PR of this magnitude.
- [x] While smaller might be better, larger could potentially be an option in some cases saving time.

## Acceptance Criteria
 - [x] A meeting has been conducted and a path forward established.

**Comment by digitaldrk** [comment]
Spoke w/ JP, I submitted a [draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4515/files) and he looked it over. We are going to break up the PR and the reason for this is because this feature spans across a few 'layers', a change requested in one place could cascade changes elsewhere and then we get into a vicious circle.

Here is our plan of attack:
1. Submit PR w/ proper Gem version installed with new name and new calls.
2. Submit PR with lib code
3. Submit PR with app code

This keeps code and reviews in the same place of the stack. We should be able to move faster like this.

**Comment by jason-gcio** [comment]
Sounds like a plan, thanks Derek.  Excited to see how it goes! 👍
