### ISSUE TITLE
[Frontend] MDT - Create an alternate confirmation screen for partially-submitted orders

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10379]
## Issue Description
Because orders can be partially submitted (i.e. 1 out of 3 items in the order _could_ fail), we must code an alternate confirmation screen to inform the user that their order will not be complete.

---
## Tasks
- [ ] Code a submission page variant for partial order submissions
- [ ] Confirm result with designers

## Acceptance Criteria
- [ ] Result confirmed with designers

**Comment by mr0sari0** [comment]
Hey @rebeccawalsh, are there any mockups associated with the partially submitted orders yet?

**Comment by rebeccawalsh** [comment]
@mr0sari0 @rileyorr has been working on this, and said yesterday in grooming that she doesn't believe this is a real case we need to design for, since we're not allowing users to select products that aren't available to them in the form itself. I think this is back burnered while she confirms her assumption completely.

**Comment by rileyorr** [comment]
Thanks for providing that clarification, @rebeccawalsh!! Yeah, I'm still waiting to hear back from Kevin about what happens in their database when an item is discontinued/replaced. Depending on their answer, I may work with Cam to get those items tagged so Veterans are aware when their items are discontinued/replaced

**Comment by rileyorr** [comment]
@mr0sari0 based on this afternoon's conversation, I've created [a design for if at least one item is not submitted](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/423013061_At_least_one_item_couldn-t_be_ordered). I've updated [the GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-confirmation-screen.md#use-case---full-order-could-not-be-submitted-partial-submission) to reflect the alert and its content. Please let me know if you have any questions!

**Comment by mr0sari0** [comment]
The PR for this is ready. https://github.com/department-of-veterans-affairs/vets-website/pull/13346.  This will have to be revisited once @camerontesterman is back, to make sure I'm grabbing the correct error props.
