### ISSUE TITLE
[Frontend] MDT - Create an alternate confirmation screen for Veterans who submit an empty order

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10375]
## Issue Description
Since we will not be able to stop users from submitting empty orders, we must code an alternate confirmation screen for the use case of an empty order submission.

[The design can be found on InVision](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/422126004_Empty_Order_Submission) and [the alert's content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-confirmation-screen.md) can be copied from the GH documentation.

---
## Tasks
- [ ] Code a submission page variant for empty order submissions
- [ ] Confirm result with designers

## Acceptance Criteria
- [ ] Result confirmed with designers

**Comment by rileyorr** [comment]
@mr0sari0 I've updated this ticket's description so you can reference the alert's styling on InVision and copy the alert's content from the GH documentation. Let me know if you have any questions!

**Comment by bradl3yC** [comment]
@rileyorr this one is assigned to me :-P

**Comment by rileyorr** [comment]
Oops, my bad! Mahariel has been working on so much MDT stuff I just assumed he was taking this one. :^ )

**Comment by mr0sari0** [comment]
@rebeccawalsh @rileyorr The PR for this has been created. Please let me know how you want to review.
