### ISSUE TITLE
[Frontend] MDT - Allow Veterans to print their order confirmation

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#10378]
## Issue Description
_The Caregiver team recently added functionality that allows Veterans to [print form confirmation screens](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/412943896) with standardized print styling. To follow print styling best practices and provide consistency across products, the "print screen" functionality should be added to MDT's confirmation screen_

---
## Tasks
- [x] _Reach out to the Caregiver team's frontend engineer for the "print screen" functionality_
- [ ] _Add the functionality to MDT's confirmation screen_
- [ ] _Test the "print screen" styling. It should look similar to [this mockup](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/403659915_Print_Screen_v-02)._
- [ ] _Reach out to a BaM2 designer to review the confirmation screen and print styling_

## Acceptance Criteria
- [ ] _"Print screen" functionality has been added to MDT's confirmation screen_
- [ ] _UI changes have been approved by a BaM2 designer_

---
