### ISSUE TITLE
[Design] MDT - Create an alternate confirmation screen for partially-submitted orders

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10380]
## Issue Description
Because orders can be partially submitted (i.e. 1 out of 3 items in the order _could_ fail), we must design an alternate confirmation screen to inform the user that their order will not be complete.

---
## Tasks
- [x] Design an alternate confirmation screen for the use case of a partial order submission
- [x] Upload to invision
- [x] Link invision / documentation to this ticket
- [x] [Update engineering ticket ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10379)with design direction

## Acceptance Criteria
- [x] Design / documentation linked to this ticket
- [x] [Engineering ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10379) updated

**Comment by rileyorr** [comment]
I've created a couple potential alternatives for the confirmation page, but I want to uncover the root of why partial orders would occur. I've emailed Kevin and am waiting on a response before I finalize the design

**Comment by rileyorr** [comment]
I've adjusted [my design](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/423013061_At_least_one_item_couldn-t_be_ordered) based on our conversation with the DLC folks this afternoon. I've updated [the GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-confirmation-screen.md#use-case---full-order-could-not-be-submitted-partial-submission) to reflect the alert and its content. I'll move this ticket over after I update the frontend ticket!
