### ISSUE TITLE
Add thorough testing for the reverse proxy

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#10389]
## Issue Description

Right now we [are using nginx as a reverse proxy](https://github.com/department-of-veterans-affairs/devops/blob/467a2c90d5f993fdeef3487e93c492e43b18e749/ansible/deployment/config/revproxy-vagov/templates/nginx_revproxy.conf.j2).  There is also a [testing file](https://github.com/department-of-veterans-affairs/devops/blob/467a2c90d5f993fdeef3487e93c492e43b18e749/testing/revproxy.py) that is designed to test some of the redirects, but this doesn't encompass all that the reverse proxy is doing.

## Goal

Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/10001, we plan to make changes to the reverse proxy to account for changing the S3 bucket structure.  Before this is done we would like to have testing place to ensure that the server we are proxying to will give us the expected results.

---
## Tasks
- [ ] Write a node script that will make requests against a list of URLs and ensure that the correct HTTP status is returned (likely 200) and possibly validate that the content in the proxied location matches what we expect
  - This could be as simple as checking to see if the title of the response body matches the expected value for the URL
- [ ] Have a CI pipeline that runs this script each time a change to the reverse proxy would be made

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by wyattwalter** [comment]
Pasting some notes that I made while evaluating choices for testing this. I went ahead and added basically what is in number 4 in the approaches list as a prototype. It works and has a basic framework for now and gets us a lot further.

# Revproxy Testing

## Testing approaches

It gets tricky because we do a few things in the build to adjust paths - specifically a symlink at /etc/nginx to point at the openresty config. This is maybe easy enough to get past since we're executing in the docker container we want to use as a test.

In order to test things, you really need two things:

- a running openresty server
- a list of redirects or the business logic in some consumable format

In order to get to a fully running openresty instance as it exists today, I see a few paths:

1. CircleCI has the ability to spin up a machine in Vagrant. We could do that if we are comfortable with the private keys being loaded by CircleCI and stored on disk. It would be relatively straightforward to get the VM spun up, but we'd need multiple of them and this might take a while especially on each CI run (read: 30-45 minutes to test all iterations of dev + staging + sandbox + prod).
2. Adapt or fork the ansible/deployment/update.yml playbook to write out the files that it would render and send to S3. We could then pick up the file copy bits from BRD to write them out and test openresty that way.
3. Create a "primary" Docker image for Amazon Linux with Ansible installed and something like https://github.com/kolypto/j2cli to render the templates out locally to test. - this won't work because Ansible has custom Jinja filters that are not available to other tools.
4. Similar to #3, but use full on Ansible for it.

All of these approaches kind of necessitate us to modify the configuration quite a bit to make it more testable.

To make things more testable:

- Remove as much of the variable passing as we possibly can -- use regexes where possible or remove environment differences
	- For example: The nginx_revproxy.conf file includes an ssl_certificate directive like `/usr/local/openresty/nginx/ssl/{{ nginx_config_developer_server_name }}.chained.crt`.. this could just be `/usr/local/openresty/nginx/ssl/developer.chained.crt` or something similar and all environments just drop the correct cert in place. The file name does _not_ have to include the hostname in any way. (I think this construct came from when we needed to start supporting multiple hostnames during the va.gov re-launch.)
- Establish a naming convention around the services we operate and split up the big config file based upon it. This is already in-flight, but not a well-supported endeavor outside of Brooks right now.
- Get rid of the symlinking and other things we do that aren't stock openresty

## Cleanup

I think a bunch of the configuration could be cleaned up to enable easier mocking and testing of the setup. In general this would also help with the overwhelming nature of the config as it stands today as well.

### General

There's some kind of funkiness with our paths and trying to use a stock openresty container image. In a new world order, logs probably go to STDOUT/STDERR, so hopefully that's solved easily, but the cache directories are in a custom directory named after nginx. We also run openresty as the nginx user whereas default openresty wants nobody.

### variables

- can we just statically set the list of trusted referrer addresses?
- update the nginx_config_csp_report_url (and _js_ equivalent) to use the vfs.va.gov addresses

### nginx.conf

- template is used to set set_real_ip_from addresses
- set `deployment_env` used for Prometheus -- unsure that this is really necessary

If those two above can be made static then the main config file becomes not a template.

### nginx_revproxy.conf

- ideally should be split up into separate files to make failures in CI a bit more obvious and just generally easier to read. This would also enable a split later on down the line.
- I think api.vets.gov is the only vets.gov address that's still in use without redirects. The revproxy logs hostnames, it should be relatively easy for us to figure out if that address is used by any consumers. The only concern would be around Lighthouse I think. If so, we could drop some of the complexity in this config file around the API vhost.

### Review instance config

- Uses template for react route pathing, otherwise is static
- The react route pathing could be split into a separate template to be shared between the prod revproxy config and review instance

**Comment by wyattwalter** [comment]
# Revproxy Testing Future Work

Outlining some work that I'd do to make the revproxy testing work more robust and give us much better coverage.

## Internal improvements

- Reduce the modifications from the stock openresty installer. These would reduce the needs for extra setup steps by Jenkins
	- I'd move the cache directories to a directory already created by the stock openresty installer. (Directories like /var/cache/nginx in the build process and config)
	- Change the logging directive for the revproxy to reference /usr/local/openresty/nginx/logs rather than the symlinked path in /var/log/nginx.
- The build process adds an nginx user, but it appears to never actually be utilized by anything except to assign ownership of files. That's totally unnecessary as the default is for openresty to start as root and then spawn worker processes as nobody. That'll get rid of warnings during the setup phase.

## Testing

There's a _lot_ that we can test for, I'd focus on things like:

- site redirects work as expected
- ideally a sample react route or possibly the whole list, but that could take a lot of time
- the default servers on port 80 should redirect to https.. this might be something we just migrate to the ALB instead
- you can't make a request to the vets-api hosts with the current setup, I'd probably setup a built-in health endpoint that's applied to all vhosts so you can have a stable test for things like checking out security headers
- this is already mostly done, but make sure the DHS-required security headers are present on all hostnames (Strict-Transport-Security) and make sure the includeSubdomains is NOT on for `va.gov` which is kind of a special case

Checking for things like the EWIS proxy settings is going to be challenging since it's pretty tied into VA internals and how things work. This deserves some thought, but I don't have many good ideas there.

In general, there's a test suite that I wrote a while back using the python unittest library that iterates through the list of redirects to check that the server configuration matches what we had. I liked that tool, but swap it out for whatever language/framework makes sense for the team overall. I think you could probably resurrect that fairly easily and adapt it to make a more robust thing than the placeholder script that's in there.

The sandbox hostnames were really funky. Several of them were using internally signed certificates and the public openresty container image doesn't trust them. I don't know the history there on why that is or have a great suggestion on how to adjust it going forward.
