### ISSUE TITLE
Update Dependency Claims Per Usability Sessions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10383]
## Goal
Appropriate changes can be made to dependency claims ahead of launch once documented.

## Tasks
- [x] Implement changes into 686 mockups 
- [x] Touch base with Peggy once finalized

## Acceptance Criteria
- [x] Changes have been put into the mockup
- [x] The changelog has been updated _({feature-name/research-design/changelog/README.md})_

**Comment by sporeboy** [comment]
Reached out to Peggy regarding review of 686 via mockups; will follow-up. 

Punchlist represents changes required indicated by usability testing; new location pattern included: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0720.md

**Comment by sporeboy** [comment]
Heard back from Peggy... She will have time to start reviewing static mockups this week. I've given her the links.

**Comment by sporeboy** [comment]
No comments from Peggy as yet. The changes are in the punchlist above. This is done for now--content changes will be captured in another ticket.
