### ISSUE TITLE
[Design] DL - Content Audit for Code Catalog

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10382]
## Issue Description
We need to begin work going through the code catalog to understand what codes currently exist, which are relevant for users, and what our plan can be for incorporating debt history into our 

---
## Tasks
- [x] Look over codes catalog and formulate questions for DMC
- [x] Create a plan for incorporating more codes in after v1

## Acceptance Criteria
- [x] High-level analysis of total codes complete and documented in GH
- [x] Plan for incorporating codes in the future outlined in GH

**Comment by rebeccawalsh** [comment]
Here's the draft of the audit: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/discovery/jun20-codes-audit.md

This content was presented to the DMC Jun 29, where it was deemed feasible and appropriate. This document will be looked at by DMC SMEs and a follow up meeting will be had.
