### ISSUE TITLE
[VAMC] Develop comprehensive POC list from list of PAOs for VISN-19 [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10388]
## Story
As a VAMC team member, I need to have a comprehensive list of Points of Contacts for Public Affairs offices in VISN-19

## TASKS
- [ ] List of Names, titles, e-mail, System, Phone for each of the following sites
*List at lease one POC for each of the following systems\
- [ ]  VA Cheyenne health care
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado (Grand Junction) health care
- [ ]  VA Montana health care
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care

## Acceptance Criteria
* Full listing of VISN-19 with Webmasters is loaded in Google Drive
* Full listing of VISN-19 with Webmasters is loaded in SharePoint Drive
