### ISSUE TITLE
[Design] Research plan for Debt Letters MVP Usability Test

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#10385]
## Issue Description
_As the team inches towards conducting a usability study for Debt Letters MVP, we need to [prepare a research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) to send Perigean for recruiting._

---
## Tasks
- [x] _Create a research plan for Debt Letters MVP Usability Test using the provided template_
- [x] _Send research plan to Shawna for review (We may want to hold off on this until convo guide is created?)_

## Acceptance Criteria
- [x] _Research plan is uploaded to GH and linked to this ticket_

**Comment by rileyorr** [comment]
I've added [the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/research-plan.md) to GH. We'll send that over with the conversation guide next sprint.
