### ISSUE TITLE
[Design] Claims Status: Usability Study #1

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10409]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
_Plan Research_
_Recruit 8-10 participants_
_Execute research_ 
_Synthesize and summarize research_

---
## Tasks
- [x] _Finish Research Plan_
- [x] _Finish Conversation Guide_
- [x] _Finish Mural board for Co-design session_
- [x] _Finish Invision Prototype of current Claim Status Tool_

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- [x] _Research planning is completed_
- [x] _Recruiting is completed_
- [x] _Research is completed_

All documents are here: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research/co-design-usability-June

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research/co-design-usability-June

**Comment by chrvalla** [comment]
This completed. 

All documents can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research/co-design-usability-June
