### ISSUE TITLE
Urgent care search - All Facilities

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10402]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Veteran, I want to view a list of facilities where I can receive urgent care, regardless of facility type so I can select the best location for me.

## Hypothesis or Bet
**If** return all urgent care facilities, regardless of facility type **then** we expect Veterans to seek urgent care more efficiently. 

## Plan
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)
- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
- [ ]  **[Discover] IA Request** - #(ticket)
- [ ] **[Discover] Analytics Request** - #(ticket)
- [ ] **[Build] Contact Center Review** - #(ticket)
- [ ] **[Build] Privacy/Security Review** - #(ticket)
- [ ] **[Build] Pre-Staging Review activities**
  - [ ] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=staging-review-accessibility-checklist.md&title=%3CInitiative%3E+x+Staging+Accessibility+Checklist) - #(ticket)
  - [ ] Compile QA test cases - #(ticket)
  - [ ] Release plan - #(ticket)
  - [ ] Submit QA test plan request - #(ticket)
- [ ] **[Build] Staging Review** - #(ticket)
  - [ ] Resolve Staging Review findings - #(tickets)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
  - [ ] Complete accessibility checklist in Prod - #(ticket if necessary)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Convert to an Epic**  
- [ ] **Labeled with Team**  
*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
