### ISSUE TITLE
Service Drop-Downs and Displays should (mostly) be Sentence Case

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#10418]
## Issue Description

Facility Locator should use sentence case (for the most part) for Service Selection/Displays for VA Services

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/690a6c6b-3204-4d58-b109-646db0e11654)

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/1efa16cc-e406-4776-ab4d-2d62d03bb537)

---
## Tasks
- [x] Collect list of current options for VA services
- [x] Validate list for any changes
- [x] Convert list to sentence case
- [x] Implement updated lists in drop downs on Facility Locator
- [x] Update service listings on Facility Detail Pages
- [x] Update `Vet centers` in VA facility type drop down to `Vet Centers` 

## Acceptance Criteria
- [ ] When a Veteran selects a facility type from the drop-down, the list of options is displayed as sentence case, except for `Vet Centers`
- [ ] When a Veteran searches for facility type = VA health, all service types listed in the drop-down are displayed in sentence case. 
- [ ] When a Veteran searches for facility type = VA health and clicks on the name of the facility to view the detail page, the list of service offerings are displayed in sentence case. 
       - As an acronym, IDES is the exception
- [ ] When a Veteran searches for facility type = VA benefits, all service types listed in the drop-down are displayed in sentence case. 
       - As an acronym, IDES is the exception
- [ ] When a Veteran searches for facility type = VA benefits and clicks on the name of the facility to view the detail page, the list of service offerings are displayed in sentence case. 
- [ ] When a Veteran searches for facility type = Vet Centers and clicks on the name of the facility to view the detail page, the list of service offerings are displayed in sentence case. 
- [ ] All other functionality is maintained. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@mpelzsherman looks like the sentence case still needs to be addressed in service displays on the detail pages for VA health and VA benefit locations (viewed in Prod): 


![image](https://user-images.githubusercontent.com/55411834/88839162-e629fe00-d197-11ea-9b6c-fea5f44da735.png)

---


![image](https://user-images.githubusercontent.com/55411834/88839438-4a4cc200-d198-11ea-9882-8d97a9712e7e.png)
