### ISSUE TITLE
Split reverse proxy configuration up by environment

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#10413]
## Issue Description

Our devops repo is set up in a way that the deploy script has its own environment config, and essentially every other config is broken down by environment.  The [reverse proxy](https://github.com/department-of-veterans-affairs/devops/blob/2c0c824673cf5141a8b15a99cbd8f0cd7c860373/ansible/deployment/config/revproxy-vagov/templates/nginx_revproxy.conf.j2) is not the same. We have a different reverse proxy for each environment, but they all use the same nginx config:

- [sandbox](https://github.com/department-of-veterans-affairs/devops/blob/2c0c824673cf5141a8b15a99cbd8f0cd7c860373/ansible/deployment/config/revproxy-vagov-sandbox.yml#L73)
- [dev](https://github.com/department-of-veterans-affairs/devops/blob/2c0c824673cf5141a8b15a99cbd8f0cd7c860373/ansible/deployment/config/revproxy-vagov-dev.yml#L73)
- [staging](https://github.com/department-of-veterans-affairs/devops/blob/2c0c824673cf5141a8b15a99cbd8f0cd7c860373/ansible/deployment/config/revproxy-vagov-staging.yml#L73)
- [prod](https://github.com/department-of-veterans-affairs/devops/blob/2c0c824673cf5141a8b15a99cbd8f0cd7c860373/ansible/deployment/config/revproxy-vagov-prod.yml)

Having a config file for each environment where each file uses the `include` directive to load shared configs would make it easier and less risky to test out changes to the reverse proxy.  We could try something out in the dev environment knowing for certain that that configuration wouldn't appear in the prod environment.

---
## Tasks
- [ ] Have nginx config scripts for each environment
- [ ] Update the ansible configuration files to point to the new nginx config files

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by dginther** [comment]
Ooh, this is great. I love this idea.

**Comment by billfienberg** [comment]
I think this ticket was completed by https://github.com/department-of-veterans-affairs/devops/pull/7262, and can therefore be closed. 

Specifically, the template file that is linked to this PR's description is `ansible/deployment/config/revproxy-vagov/templates/nginx_revproxy.conf.j2`. That file (`templates/nginx_revproxy.conf.j2`) file was deleted in https://github.com/department-of-veterans-affairs/devops/pull/7262.

**Comment by bkjohnson** [comment]
Yeah, there was a bit of a pivot in the PR Bill linked.
