### ISSUE TITLE
[Discovery] CST and 526: Upload and File extension errors

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#10427]
## Issue Description
EVSS is rejecting a lot of document uploads during the ancillary forms submission for having bad file extensions.  We need to investigate this error and see if we can lower the rejection count.

```
[{"key"=>"EVSS_15005", "text"=>"We were unable to complete your upload because the 
content of your file did not match the file extension. Please verify that the file 
extension is valiad with the file content.  If you still have problems, call the 
VA at 1-800-827-1000 (711, if you use a TDD) for assistance. When you call, 
provide the following erro code: EVSS_15005.", "severity"=>"ERROR"}]
```

Example error
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/?query=upload

The goal of this story is to prepare some info for EVSS so they can investigate.  5 examples to start sounds like a reasonable place to start.

## Tasks
- [ ] Prepare package for EVSS with several examples of file upload issues along with actual files so they can explore why they are erroring out

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
About 80 times a day we fail up upload documents because EVSS doesn't agree what the type is.  Maybe this is a document issue or maybe this is an EVSS validation issue. Either way, we should make sure that we successfully get the document to EVSS or let the user know that it didn't happen.
<img width="317" alt="Screen Shot 2020-06-26 at 11 09 36 AM" src="https://user-images.githubusercontent.com/19188/85872338-94a7e100-b79d-11ea-98da-2a9d9e61abce.png">

**Comment by annaswims** [comment]
[grafana metrics ](http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?viewPanel=19&orgId=1&from=now-14d&to=now)![Screen Shot 2020-08-25 at 3.45.47 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/07b7c3da-822d-4a2f-9599-fdf2d9d3f8ba)

**Comment by annaswims** [comment]
To be continued/edited...

| Sentry issue | va_eauth_service_transaction_id | file type | file name | 
|--------------|---------|---------|----------|
|http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/events/7536160/ |  vagov-3e39be18-b768-4bff-9e30-41154d9dea4e | ASCII text, with CRLF line terminators | right_knee.txt |

**Comment by annaswims** [comment]
created https://github.com/department-of-veterans-affairs/va.gov-team/issues/13209

**Comment by annaswims** [comment]
Note to self: [uploads location 
](https://console.amazonaws-us-gov.com/s3/buckets/dsva-vetsgov-prod-evss/evss_claim_documents/?region=us-gov-west-1&tab=overview)

**Comment by annaswims** [comment]
created https://github.com/department-of-veterans-affairs/va.gov-team/issues/13293

**Comment by annaswims** [comment]
It seems like the CST has many more errors than form526.  We should take a look at how the FE validations differ between form 526 and CST

**Comment by annaswims** [comment]
another issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/13664

**Comment by annaswims** [comment]
it seems that the problems are on our side.  no need to involve EVSS
