### ISSUE TITLE
[VAMC] Created and present Kick-off Presentation for VAMC-upgrade to VISN-19 Meeting 1 [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10429]
## User Story or Problem Statement
As a VISN-19 PAO, I need a understanding of the changes to VAMC system web pages, so I can quickly determine my level of support and availability to provide feedback.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Eastern Oklahoma VA Medical Center legacy Site](https://www.muskogee.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-19 Content Folders](https://drive.google.com/drive/folders/1KVjgw4Z56Zm3m1TVTDktpKk9aKVpP9ms)

## Tasks
_Review content pages created for below_
*Create a new copy of the document and call it "REVIEW", turn on "Track Changes" and update with comments.  Save document in word for full review
- [ ]  VA Cheyenne health care
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado (Grand Junction) health care
- [ ]  VA Montana health care
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care

## Acceptance Criteria
* Presentation to VISN-19 PAOs
* POC list is obtained for VISN-19
* Questions answered for VISN-19
