### ISSUE TITLE
[Discovery] - Create conversation guide for Learning Center MVP usability study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#10432]
Complete the conversation guide for our research study for the learning center MVP

## Tasks
- [x] _Create [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)_
- [x] _Review conversation guide with team_
- [x] _Update based on feedback_
- [x] _Add guide to GH_

## Acceptance Criteria
- [x] Conversation guide created and uploaded to GH

**Comment by andaleliz** [comment]
Started [draft of conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/conversation-guide.md)

**Comment by andaleliz** [comment]
@jenniferlee-dsva, @bethpotts, and @DanielleThierryUSDSVA 
I put a **_rough_** draft together of the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/conversation-guide.md#first-task-find-article-on-a-specific-topic---x-minutes) to capture tasks and get answers to the research questions we've defined for the learning center.  

This is by no means final (e.g. there's not a script here yet), but intended to give us an outline of appropriate tasks. My hope is that we can use this to evaluate how many screens we'll need for each task.

While working through this, I realized we don't have any research goals/questions around different template types. If that's still something we'd like to explore, let's define those goals.  Right now it's very focused on searching and finding info.

**Comment by jenniferlee-dsva** [comment]
Adding @rtwell  @JeffBarnesUSDS @mnorthuis  for their input also on the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/conversation-guide.md#first-task-find-article-on-a-specific-topic---x-minutes) as they were part of the original brainstorming design workshop. 

(If you wish - not required!)

**Comment by jenniferlee-dsva** [comment]
Hi Liz - I'd like to add one more UX to test for in addition to the ones you already have in the conversation guide: 

A. **Navigability between related learning center articles** - Can users move easily from a LC article to related LC articles okay without getting confused? 
- Example: From a 'How to change your address' LC article to another related LC article like Sign in FAQs or 'How to create a VA.gov account' LC article. 

B. **Navigability from topic X to topic Y inside the LC** - Can users jump from LC topic to topic okay, whether it's via tags or via LC search (or even site search)? 
- Example: User is reading about Camp Lejeune contamination LC article and then wants to learn about how to sign in or create a VA.gov account.

**Comment by jenniferlee-dsva** [comment]
Plus ^ - a clarification on task 1 in the convo guide... 

>First Task: Find article on a specific topic - X minutes
Imagine you are looking for information on [VA account topic]. Talk me through how you'd find the answer.
Start on the home page of learning center. Scroll and talk me through how you'd find that information from here.
Enter search term

The ^ assumes that the user will use the search bar from the LC homepage. However, it's also possible that they might use the 'View all article about X' link, and I'd like to make sure that that's available if the user wants to click on that. 

Currently in the designed UX, that 'View all' link goes to a LC search results page with just those topic articles. One of the things Ryan and I are very interested in learning is if that is expected and sufficient for users?  Or do they expect another landing page with just a list of topic content links? 

We didn't design this type of interstitial topic-only landing page, and we'd like to understand if that would be helpful (i.e., if not having that makes it weird or hard for users).

**Comment by andaleliz** [comment]
@jenniferlee-dsva, makes sense. In response to:

**your first comment** 
I like the idea of seeing how users navigate from article to article.  Looking at the templates, it seems like the ways users would do this, for both navigation questions you outlined, is via the `related information` box at the bottom of a page, or by another search via the search bar at the top. 

Is that correct? 

**your second comment**
For task 1 in the convo guide, when the participant scrolls through and talks about how they'd find that information, they would have the opportunity to say if they would use the `view all articles about X` link, or possibly use the `Audience` boxes...something other than search. 

If they say "I would just search" right away, I'd still encourage them to scroll and talk through the entire page, prior to having them enter a search term to move onto the search results page.

If their primary response is to click on that `View all` link, it sounds like we need 1 more page, that hasn't yet been designed. That page would be the result a user would see if they clicked `View all VA account and profile articles` from the homepage, and ask participants to comment on how it lines up with their expectations.   

1. Is that correct?  
2. And if so, how is it different from the results page a user would get if they clicked on a "VA account and profile" topic tag?

**Comment by andaleliz** [comment]
We answered the above questions in a meeting this AM:
- other ways users might get to related articles include CTAs and content links, but those are subject to the content authors decisions
- correct that we need another page for topic search results
- the results aren't different than if a user clicked on a topic tag

**Comment by andaleliz** [comment]
Screen needs based on meeting this AM:
- Task 1: Learning center homepage
- Task 2: `View all VA account and profile articles` page 
  - Should include 10 search results
  - Page should include some results that have similar titles so we can see if the template labels are effective in helping users choose a relevant search result
- Task 3
  - Sign in FAQs 
  - Change your address on file with VA 
  - How to change your address online 
- Task 4 
  - Exposure to hazardous materials page from benefit hub
  - Agent Orange LC page w/ CTAs leading back to hub, with Vietnam War Veterans (to tee up next task)
  - How to file or apply page from benefit hub
- Task 5: Vietnam War Veterans search results page

**Comment by mpeterz** [comment]
Some thoughts/suggestions after reading through the conversation guide and the comments above. :) @andaleliz @jenniferlee-dsva @mnorthuis 

Learning center strategy:
— What content goes in a learning center?
— Let's take a stab at defining this before the kickoff; then we can use feedback from users in this round of testing (on what a learning center is) to refine our strategy.  

For this round of testing, I offer these thoughts/suggestions… 

“Learning center” label:
— What do veterans think is in a “learning center”?
— If “learning center” doesn’t make sense, what is a good name for this area of VA.gov? 

Search:
— To find what they are looking for, do users *know* whether to go with the default “Search learning center” or use “Search VA.gov”?
— Do users get confused between the search link in the top nav (which opens to a search box) and the in-page search with the radio buttons?

Search results:
For each individual search result, is this the right visual format?

Article pages: 
— On article pages, do users realize topic and audience tags are clickable? 
— If so, do they use them? 
— If they don’t use them, why not? 

Navigation: 
— Per the comments above ^ about the need for a topic landing page (and single topic pages), the breadcrumb should include topic (not audience).  
— Did users navigate easily between the benefit hub and learning center? 
— Did they understand where they were and how to get back?

After this user research, we should iterate by testing and refining on the content-owner side with VA staff:
— Do VA staff know what content belongs in a learning center (versus a benefit hub or somewhere else)? 
— Do VA staff put content in the right place (audience, topic)?

**Comment by andaleliz** [comment]
Thanks for these thoughtful comments @mpeterz ! I'll reply to those I can, and let @jenniferlee-dsva weigh in on others.  I'll also add any questions you asked to the `Things to watch for` section of each task if they aren't already captured.

>Learning center strategy

My understanding is that tier 2 content goes into the learning center, but @jenniferlee-dsva can offer much more insight into that.

>“Learning center” label

I'm glad you brought this up. I think it'd be good to ask about what they might expect to see in something called a `learning center` in the warm-up, and then revisit what the right name/title would be in the post-task interview.  We can also ask something along these lines at the end of our card sort.  

Personally, I'm not sure that it needs a formal name, but even if we don't give it one, understanding what Veterans would call It could help us determine an appropriate label in the nav, or wherever we provide access to it.

> Search 

I think we'll get the insights you bring up here in task 1.  I have a specific post-task interview question to address site search vs LC search if it hasn't come up in the session

> Search results

This is something we have as a `thing to watch out for` , and I'll make an update to the guide to be sure to specifically ask if it's not commented on.

> Article pages

Tasks 3 and 5 should elicit these insights, but I'll add a note to myself to ask these specific questions in case it doesn't come up naturally.

>  Navigation

Task 4 is dedicated to answering these questions

> After this user research, we should iterate by testing and refining on the content-owner side with VA staff

We're doing a card sort with content owners to better understand how they might apply the audience labels. Since our topics are already informed by research (done during the transition), we didn't think it was necessary to revisit those.

In terms of what content belongs in the learning center - @jenniferlee-dsva can speak to that better than I can.

> Also, what are our plans for testing mobile?

I'm so glad you asked, as this is something I wanted to ask about too.  Mobile plans haven't been discussed yet that I'm aware of. I'm sure @jenniferlee-dsva can share insights to this.

**Comment by andaleliz** [comment]
Guide completed and submitted to Lauren.
