### ISSUE TITLE
Expand Automated tests for Community care searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10448]
## Background
We need to create end-to-end tests specifically for Community Care searches which can be used to regression test in lower environments. 

## Tasks

- [x] Write end-to-end tests to ensure existing functionality is maintained for the following Facility Locator searches:

       > Facility type = Community providers (in VA's network) and service type is specified (such as Dentist or Podiatrist, etc)
       > Facility type = Urgent care **and** Service type = Community urgent care providers (in VA's network)
       > Facility type = Urgent care pharmacies (in VA's network)
       > Facility type = Community providers (in VA's network) **and** Service type = Clinic/Center- Urgent care

- [x] Conduct end-to-end testing
- [ ] ~Work with VSP to make sure these get into the regression suite (if applicable)~ Per VSP, there is no regression suite of e2e tests, nor any plans to create one.

## Acceptance Criteria:

End-to-end tests are present to test the following: 

**When Facility type = Community providers (in VA's network) **and** Service type is specified (such as Dentist or Podiatrist, etc)**
- [x] Search result cards for all scenarios above contain the following:
      > Alpha icon correlating to map pin
      > Distance
      > Facility type
      > ~Services~
      > Name of group/provider
      > Address
      > Functional Directions hyperlink
      > Phone number
- [ ]  ~Results will be relevant to the location and service type specified~
- [x] Search results cards include the following: _If you don’t have a referral, contact your local VA medical center._ - - Covered by LocationPhoneLink unit test
- [ ] ~Search results cards include "Services"~ Services have been removed
- [ ]  ~**NO** alert displays below search box~ This alert was deleted entirely.
- [x] There is no link to a facility detail page (this change in [#10324](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10324))

**When Facility type = "Urgent care" and Service type = "Community urgent care providers (in VA's network)", then**
- [x] Search result cards for all scenarios above contain the following:
      > Alpha icon correlating to map pin
      > Distance
      > Facility type
      > ~Services~
      > Name of group/provider
      > Address
      > Functional Directions hyperlink
      > Phone number
- [ ]  ~Results will be relevant to the location and service type specified~
- [ ] ~Results should include only VA Community Care (In Network) locations (PPMS Place of Service 17 and 20)~
- [x] Search results cards do not reference need for referral
- [ ] ~Alert displays below search box~ Alert was deleted in a previous story
- [x] There is no link to a facility detail page

**When Facility type = Urgent care pharmacies (in VA's network), then** 
- [ ] Search result cards for all scenarios above contain the following:
      > Alpha icon correlating to map pin
      > Distance
      > Facility type
      > ~Services~
      > Name of group/provider
      > Address
      > Functional Directions hyperlink
      > Phone number
- [ ] ~Results will be relevant to the location and service type specified~
- [ ] ~Results should include only VA Community Care (In Network) pharmacy locations (PPMS Place of Service Code 1)~
- [x] Search results cards do not reference need for referral - Covered by LocationPhoneLink unit test
- [ ] ~Alert displays below search box~ Alert was deleted in a previous story
- [x] There is no link to a facility detail page

**When Facility type = "Community providers (in VA's network)" and Service type = "Clinic/Center- Urgent care", then**
 - [x] Search result cards for all scenarios above contain the following:
      > Alpha icon correlating to map pin
      > Distance
      > Facility type
      > ~Services~
      > Name of group/provider
      > Address
      > Functional Directions hyperlink
      > Phone number> Results will be relevant to the location and service type specified
- [ ] ~Results should include only VA Community Care (In Network) locations (PPMS Place of Service 17 and 20)~
- [x] Search results cards do not reference need for referral
- [ ] ~Alert displays below search box~ Alert was deleted in a previous story
- [x] There is no link to a facility detail page

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
I've crossed the AC items related to checking the results of the API calls. We are using mock data, so we can't do that, but even if we were using live data, it's the API's responsibility to provide correct data.

We are already testing our query params in the `api-url-parameters.unit.spec.js` suite.

attn @mmiddaugh
