### ISSUE TITLE
Clone historic 2018 Disability - Special Monthly Compensation rates tables

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10450]
# Issue Description:
In order to retire legacy pages with historic disability rates, we need to clone our current rates pages in Drupal and input the 2018 rates information.

# Tasks:
- [x] Clone current Disability - Special Monthly Compensation rates page in Drupal. Anne
- [x] Copy over rates from legacy historic page, https://www.benefits.va.gov/COMPENSATION/resources_comp0217.asp . Anne
- [x] Copy edit and doublecheck rates and new math examples. Randi

Epic: #10435

Preview: http://preview-prod.vfs.va.gov/preview?nodeId=5687

# Acceptance criteria:
- [x] Page cloned, numbers checked and reviewed

**Comment by AnneHurley** [comment]
@RLHecht  - This new 2018 historical 2018 SMC rates page is ready for you. Happy for us to go over together as we have in the past. 
SMC 2018 historical rates: http://preview-prod.vfs.va.gov/preview?nodeId=5687

Main SMC rates page with new link to new 2018 rates page: http://preview-prod.vfs.va.gov/preview?nodeId=991

@bethpottsVADEPO @stephorkandatx  @jenniferlee-dsva  FYSA

NOTE: One rate number on the chart looks off to me (it's higher than the 2019 number) so am checking with Sandy and Elana. 6/21

**Comment by RLHecht** [comment]
@AnneHurley this page looks good to me. We went over the numbers together and I just took another look at the page.

**Comment by MickinSahni** [comment]
Next step: dry-run of delivering rates (via spreadsheet) for 2018 with stakeholders

Carrying to sprint 25

**Comment by AnneHurley** [comment]
> Next step: dry-run of delivering rates (via spreadsheet) for 2018 with stakeholders
> 
> Carrying to sprint 25

@MickinSahni  The spreadsheets for rates are a different project, and apply only to future rates tables.

**Comment by AnneHurley** [comment]
@RLHecht  Can you review this again: http://preview-prod.vfs.va.gov/preview?nodeId=5687

The N 1/2 rate for Veteran, 1 spouse, 1 parent, 1 child is $5,575.47. This is now fixed.

**Comment by AnneHurley** [comment]
@RLHecht @bethpottsVADEPO  FYI the new ticket that addresses the number fixes from stakeholders for 2019 and 2020 rates is #10934

**Comment by RLHecht** [comment]
@AnneHurley This number looks OK to me. This page is ready to go whenever we start publishing. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
The work in this ticket is complete. Work from SME approval to publishing is now reflected in ticket #11171. FYSA @MickinSahni
