### ISSUE TITLE
[FE] Logged-in homepage: Beta/opt-in technical discovery/scoping

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10476]
## Background

In the fall of 2019, our team had intended to build a beta/opt-in feature but ultimately got sidetracked by other work. This kind of feature would be great to have in place for the logged-in homepage redesign; however, whether we actually pursue this work depends on whether we have the capacity to do so. In theory, the design phase for the LIH work will take a couple of months, during which we could be implementing and testing an opt-in feature. My hope would be that beta/opt-in would be done before we needed to start build on the logged-in homepage itself and would be a good way to keep Sandra/Erik busy while they were waiting for LIH designs to come down the pipeline.

What I'm hoping to accomplish: I'm not willing to sign up our team for this work if we don't reasonably think we could finish the effort in a couple of months. 

Let's use this ticket to:

- Review the opt-in functionality that was used for personalization 1.0 on vets.gov.
- Explore what we think the level of effort would be for us to implement a beta/opt-in feature on VA.gov.
- Determine whether we'd like to pursue this work (if the answer is no, that's OK!).

Note: Ultimately, I think this work would be owned by the platform. 

## Tasks

- [ ] Take a look at the code re: the beta functionality that was used on vets.gov https://github.com/department-of-veterans-affairs/vets-website/blob/1f6bb701cd54dd3b4f0493f9d37423165a536522/src/applications/beta-enrollment/README.md
- [ ] Determine the level of effort for the following:
  - What it would take to allow users to self-select into a beta feature (ie. something behind a feature flag)
  - What it would take to allow users to opt-out of a beta they had selected into and go back to the original version of the feature
  - Where a beta/opt-in page might live
  - How we might handle multiple betas going on at once (note: this likely wouldn't be MVP functionality)
- [ ] Make recommendation as to whether we pursue this alongside the logged-in homepage work.

## Acceptance criteria

- [ ] We have determined whether we'd like to pursue a beta/opt-in feature.

**Comment by erikphansen** [comment]
@Samara-Strauss I'm reading this and had a clarifying question. My memory of when we talked about this last year the idea was basically "now that Flipper is a thing, can we re-do the beta opt-in feature to allow users to add themselves to the list of users who have access to a feature gated by Flipper?" Does that sound right to you?

**Comment by annaswims** [comment]
In the back end we have a `BetaRegistrationsController` that will show/create/destroy beta registrations.  I think it hasn't been used for a while but can be used for this. 

BetaRegistration model has the attributes id, user_uuid, feature, created_at, updated_at

Then, in flipper.rb

Flipper.register(:beta_user_for_foo_feature) do |user|
  puts "is #{user.uuid} a beta user"
  user.respond_to?(:uuid) &&  BetaRegistration.where(feature: "beta_user_for_foo_feature", user_uuid: user.uuid).present?
end

Then, enable the group beta_user_for_foo_feature in the flipper interface.

**Comment by annaswims** [comment]
As far as the front end goes, I think there's some code for [Beta Enrollment](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/beta-enrollment/README.md) that is still good.  The front end just needs to call 

GET/POST/DELETE                     /v0/beta_registration/beta_user_for_foo_feature.

**Comment by Samara-Strauss** [comment]
> My memory of when we talked about this last year the idea was basically "now that Flipper is a thing, can we re-do the beta opt-in feature to allow users to add themselves to the list of users who have access to a feature gated by Flipper?" Does that sound right to you?

@erikphansen yes, that is correct. We had talked about the idea of allowing people opt-in/opt-out to a beta feature without additional manual work from anyone on our team.

I do want to call attention to what @annaswims posted above, though. I didn't realize until recently that some sort of beta functionality was apparently used on Vets.gov or for the Vets.gov --> VA.gov transition. Will you take a look into that code and create some brief documentation on what that existing code does/doesn't do?

- Does it allow users to opt-in and opt-out without our intervention?
- If we wanted to use the functionality as-is, how much work would it take to make this available on VA.gov?

**Comment by annaswims** [comment]
Ah, I was writing at the same time @erikphansen was.  What I was describing was a combination of the old "beta enrollment" with the new Flipper feature toggle.  

If you make a "group" in flipper, it can be "anyone who has clicked beta enrollment".  Flipper looks for any of the conditions to be true.  So, you could to a rollout with a few beta users, and an additional "x% of users".

**Comment by Samara-Strauss** [comment]
Thanks @annaswims!!

**Comment by erikphansen** [comment]
@annaswims that's super helpful. I'm not seeing Swagger docs for the `beta_registration` endpoints. Are those APIs still active, just not documented? Based on the FE work that uses the beta registration feature, it looks like we don't use the GET endpoint at all (at least not directly); instead doing a POST adds that feature name to list of available services that come back from the `GET user/` call. Which is fine, but whatever code is being used to add data to the available services can probably stop doing that.

 @Samara-Strauss we could pretty easily try this out for Profile 2.0. Anna laid out the BE technical requirements pretty clearly. We'd just need to decide where to put a button for a user to opt in/opt out of Profile 2.0. It might be worth doing this is the most barebones way possible and actually hide it behind a feature flag. So meta.

**Comment by annaswims** [comment]
I think it's been quite a while since we've used beta_registration, but it looks like the code is still there and it's just not documented in swagger.

**Comment by erikphansen** [comment]
@Samara-Strauss I think it's safe to close this. We can regroup and talk about next steps to implement Anna's ideas for a test feature flag.
