### ISSUE TITLE
Inflection rename from MVI to MPI

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#10472]
## Issue Description
MVI (Master Veteran Index) was renamed to MPI/MasterPersonIndex. An autoloading issue for MVI was introduced when enabling Zeitwerk mode when the lib MVI name-spaced classes were referenced before the MVI model. In this case, the model wasn't defined as inheriting from Common::RedisStore. We renamed the MVI namespacing from MVI to MasterVeteranIndex, but since MVI was renamed to MPI, we should define the proper inflection and namespacing across the codebase. 

We've decided to not include the MPI rename with the Zeitwerk changes, as this introduces another concept that isn't specifically related to Zeitwerk. Zeitwerk is also blocking Rack and Sidekiq upgrades, so we'd like to get the Zeitwerk changes released as soon as we can. 

See [MVI rename PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4411) for reference

---
## Tasks
- [ ] Confirm that the correct service name is now MPI (Master Person Index)
- [ ] Rename MVI Inflection to MPI
- [ ] Rename MasterVeteranIndex namespacing to MasterPerson Index

## Acceptance Criteria
- [ ] Specs pass
- [ ] Confirm rake tasks still function properly
---

**Comment by erluti** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/4521
closing this story because it was decided the MPI rename should be part of zeitwerk changes, follow the story here https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10178
