### ISSUE TITLE
[FE] Defined Tech Stack 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#10485]
Define the technical stack we plan using. 

The Current tech stack makes the most sense, right now. 

Creating this issue to earmark this decision once the requirements become clearer. 

## Descriptions
- Create diagrams to define the current systems and how we are integrating with various endpoings
- Create documentation for how we are doing integrations

## Tasks
- [ ] Questionnaire form type and questions as a service so that we can build a tool for form builder at a later date.
- [x] Create tech architecture for our questionnaires and integration points with other systems - [WIP diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/assets/Questionnaire%20System%20Diagram.png)

## Acceptance criteria
- [ ] Findings documented in the team directory on Github
- [ ] Get team buy-in from reviews and meetings

**Comment by abuckley3385** [comment]
@mdewey - per backlog can you break this into individual tickets. ie va.gov, mobile, .etc

**Comment by abuckley3385** [comment]
Blocked until we land scope of solution.

**Comment by abuckley3385** [comment]
I'd like to add this for sprint 27 - @mdewey @massrb  please put an estimate on this ticket and add additional tasks/acceptance

**Comment by mdewey** [comment]
My reasoning for a 5 is that since this also includes an architecture definition, I want to make sure we put the time and resources into and not rush it.

**Comment by abuckley3385** [comment]
Per Retro - we discussed this ticket is a combined FE and BE collaboration given the different sources we are leveraging.  Both @massrb  and @mdewey  are owners and responsible for progress towards completion in Sprint 29

**Comment by mdewey** [comment]
Started doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/architecture-diagram.md

**Comment by mdewey** [comment]
Doc needs a tech team reviewed. 

@massrb Can you look over [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/architecture-diagram.md#L24) and let me know what you think?

**Comment by massrb** [comment]
@mdewey, it looks good. Where is the drawing.io doc stored ? That looks like an image derived from it

**Comment by mdewey** [comment]
The image is the assets folder

**Comment by mdewey** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/assets/architecture.v1.png

**Comment by mdewey** [comment]
Created eary diagrams for Questionnaire as a service : https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/questionnaire-as-a-service.md

**Comment by mdewey** [comment]
Created a meeting for Sept 4th, 2020 with the team to review.

**Comment by mdewey** [comment]
To wrap up this ticket, the forms library is very limiting right now, with the forms having to be hardcoded. The forms platform team is aware of this limitation and the effort to possibly add those features is in the very early stages

see tickets: 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12804
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12796
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12769

**Comment by mdewey** [comment]
Feedback was given and tech diagram was updated
