### ISSUE TITLE
[Analytics Support] Update post authentication URLs to address GA goal funnel issue

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10480]
## Update Post Authentication URLs on VA<span/>.gov

Copied from story #10221, but used for BAM1 tracking.  Will likely update acceptance criteria etc but using the other story content as a placeholder for now.

As noted in #9398, VA.gov redirects users to the exact same Page URL after authentication.  This causes issues with any URL-based Google Analytics goals that have funnels:  

https://support.google.com/analytics/answer/1116091?hl=en#identical

Google's recommended fixes won't work...

- _Set up event tracking to track flows like this._

Custom funnels with events only allow 5 steps.  Many of our applications are >5.

- _Use an event goal instead of a destination goal._

Event tracking only tracks completion and not the preceding funnel steps - which we need.

------
### We are asking that the post-authentication URL has a query parameter appended to allow us to differentiate pre and post authentication.

These URLs have a  `next` query parameter.  Examples:

- /index.html?next=/my-va
- /index.html?next=/track-claims/your-claims
- /index.html?next=/track-claims/
- /index.html?next=/my-va/
- /index.html?next=/track-claims
- /index.html?next=/change-address
- /index.html?next=/education/gi-bill/post-9-11/ch-33-benefit/status

## Tasks
- [ ] Select URL parameter to denote authenication.  This should be new and descriptive.  Suggestions: `auth=1` `postLogin=true` (Jon and Brian)
- [ ] Have developer update staging.va.gov to append URL parameter to all `?next=` URLs 
- [ ] QA existing goal funnels (Jon and Brian)
- [ ] If necessary, update existing goal funnels with additional step with new URL (Jon and Brian)
- [ ] Deploy to production

--------
## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by Mottie** [comment]
This issue has a more global focus. It's not specific to any of our forms.

**Comment by jonwehausen** [comment]
Closing this per completion in different GH issue
