### ISSUE TITLE
Insert Critical Veteran Information into Backend

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10515]
## Goal
In checking and presenting the Veteran information before accessing the form, we ended up stripping that data out.  Those fields are needed to successfully submit the form but don't have to be part of the initial payload.  The plan is to call that static information and insert it directly into `vets-api` keeping the payload size as small as possible and inserting hardened, known info into the submission.

## Considerations
Here is a list of the returned fields in the call:
```
{
  :brthdy_dt,
  :cmptny_decn_type_cd,
  :cmptny_decn_type_nm,
  :death_hist_ind,
  :email_addr,
  :fid_decn_categy_type_cd,
  :fid_decn_categy_type_nm,
  :file_nbr,
  :first_nm,
  :first_nm_key,
  :gender_cd,
  :ins_file_nbr,
  :last_nm,
  :last_nm_key,
  :middle_nm,
  :middle_nm_key,
  :mlty_person_ind,
  :ptcpnt_dto,
  :ptcpnt_id,
  :ssn_nbr,
  :ssn_vrfctn_status_type_cd,
  :station_of_jurisdiction,
  :svc_nbr,
  :termnl_digit_nbr,
  :vet_ind
}
```
- This will change how data is inputted into the PDF creation process.

## Tasks
- [x] Address the call that brings this info (VA file number)
- [x] Insert the needed info into `vets-api` on behalf of the Veteran's 686 submission

## Acceptance Criteria
- [x] All fields needed to submit are included in the form submission
- [x] All fields are also shown in the newly created PDF, as needed

**Comment by digitaldrk** [comment]
I think I might have this one in a good place. I added the va file number call to the 686 submission process yesterday.

Just an FYI so there's no re-work

**Comment by kathleencrawford** [comment]
We are getting most of the critical veteran information from the user object and using that to populate the PDF.  Derek has added a call to get the va file number for the 686 submission, so when we chain the two actions together for the submit 686 (submitting to bgs and generating the pdf) we will populate the file number on the pdf then, so we don't have to make another call to BGS.
