### ISSUE TITLE
[Design] Logged-in homepage: Plan for how/when to conduct user testing

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10518]
## Background

For the logged-in homepage work, we should strive to conduct user testing more than once in the design phase given how heavily trafficked the homepage currently is. We need to make sure our updates help users and don't hinder them, and I think we can best do that by designing --> testing --> designing --> testing etc.

## Tasks

- [x] Tressa/Cassandra regroup.
- [x] Review with Matt/Samara.
- [ ] General approach for user testing is set.

## Acceptance criteria

- [ ] General approach for user testing is set.

**Comment by Samara-Strauss** [comment]
I think this was mostly done [as part of the design plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md) for this project. @tressaellen @callen2563 is this right?:

- User testing during phase 2: Health care and Claim status
- User testing during phase 3: Design Education, Records, Applications in progress, Discover additional benefits sections
- User testing is all of phase 5: We'll test finalized mockups for all LOA3 and LOA1 use cases

If this is accurate, this is good to close. If not, can you document the user testing plan in this ticket?

**Comment by tressaellen** [comment]
@Samara-Strauss This is correct! We're good to close this ticket.
