### ISSUE TITLE
[Design] Plan for how to work with the platform team

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10516]
## Background

A big part of the logged-in homepage will involve creating new patterns for the design system that more effectively and efficiently display personalized/tool information on the new logged-in homepage. Since the general approach of this team is to add to the design system sparingly, this should be something we work closely with the platform team on so everyone feels that the changes and updates we make are an overall improvement to the design system.

## Tasks

- [x] Tressa/Cassandra regroup.
- [x] Regroup with members of the platform team.
- [x] Document whatever process we've decided will help guide this work.

## Acceptance criteria

- [x] Tressa/Cassandra and platform team feel confident with how we'll develop and review design throughout the LIH project.

**Comment by Samara-Strauss** [comment]
@tressaellen @callen2563 I am thinking we might want to move this ticket to next sprint, since that's when you'll be starting explorations and having initial convos with the platform team. How does that sound? I know the [design plan is outlined here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md), but I still think having a convo with platform folks around expectations around check-ins (and documenting expectations) should happen before we close out this ticket. What do you think?

**Comment by tressaellen** [comment]
@Samara-Strauss that sounds good to me. @callen2563, thoughts?

**Comment by callen2563** [comment]
Yes, I agree I think we can hold off.




Cassandra Allen 
Senior Interactive Designer 
| office (310) 728-0046
| e. callen@governmentcio.com 
GovernmentCIO
website | media | services | jobs | map
    
Confidentiality Note: This email may contain confidential and/or private information. 
If you received this email in error please delete and notify sender.

**Comment by Samara-Strauss** [comment]
Great! Moving to next sprint. cc/ @mshea0606

**Comment by mshea0606** [comment]
@tressaellen and @callen2563  would like to move this to next sprint and include it as part of the design-intent review. I'm ok with that. 

 @Samara-Strauss what do you think?

**Comment by Samara-Strauss** [comment]
Yep, let's move to next sprint

**Comment by Samara-Strauss** [comment]
This was established in yesterday's platform review. We'll be meeting with them weekly for the duration of the design phase.
