### ISSUE TITLE
[Development] BDD: Add "Are you a VA employee"

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10523]
## Issue Description

EVSS requires this information to be provided.

## Tasks

- [ ] Add "Are you a VA employee" question from all-claims.

## Acceptance Criteria

- [ ] Submit a VA employee value on BDD submission

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
