### ISSUE TITLE
Font size on Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10527]
## Issue Description
Per Design feedback on [#10442](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10442),  the font-weight of the letters in the pins doesn't match the original design spec. If possible, increase the font-weight to match the design spec to increase readability

---
## Tasks
- [ ] Make font sizes on Facility Locator consistent with design spec

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This from staging review: [#10442](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10442)

**Comment by davidmpickett** [comment]
@thejordanwood Confirm if this is still relevant?

**Comment by thejordanwood** [comment]
@davidmpickett I can't find the original designs for this, but the font weight of the letters in the pins looks consistent with the design system. I'm going to go ahead and close this.
