### ISSUE TITLE
[Epic of Epics] Decision Review Requests and Appeals Digital Experience

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#1052]
# Decision Review Requests and Appeals Digital Experience

_Also known as AMA Forms or Appeals Online_

Product Docs: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Global/Decision%20Reviews

## Story

As a Veteran or claimant who has received a decision about my VA benefits, I want to file an appeal (or decision review request) on va.gov so that I don't have to constantly re-enter information that the VA already knows about me and my decisions.

## Considerations

- The pilot project is for a higher-Level review against a well-formed EVSS-present Compensation decision issue.
- HLRs can then expand across business lines (to encompass non-rated issues)
- The experience can then expand to Supplemental Claims and Board Appeals

## Definition of Done

- [ ] A logged in LOA3 user can submit a valid AMA-defined decision review request on va.gov

## Pilot Tasks

- [ ] Create Epic and initial stories for HLR pilot project
  - [ ] Perform initial integration with API team Caseflow Intake endpoint
  - [ ] Build first iteration of HLR Compensation decision review request application
- [ ] Create Epic and initial stories for non-VBMS HLR
- [ ] Create Epic and initial stories for Notice of Disagreement
- [ ] Create Epic and initial stories for Supplemental Claim

## Further Tasks

- [ ] Expand pilot to nonrated issues
- [ ] Expand pilot to all AMA forms
