### ISSUE TITLE
Update CC preference question & add FL copy/link

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10520]
As a Veteran who wants to request a Community Care appointment, I need to be able to look up my provider information from the approved facility locator list. 

### Tasks to complete:
- [x] Design to define where best to place these directions and Facility Locator link -- link to use: https://www.va.gov/find-locations/?facilityType=cc_provider
- [x] Content to assist in copy for directions and input on location of copy/link

### Acceptance criteria:
- [ ] Update question - "Do you have a referral or a preferred community care provider..." to _"Do you have a community care referral or a preferred VA-approved community care provider?"_
- [ ] If user selects "yes" - user is shown copy - _"Use the [facility locator](https://www.va.gov/find-locations/?facilityType=cc_provider) to find your preferred community care provider. Copy and paste their name and address below."_
- [ ] The FL link opens in new tab with 'Community Care' selection prefilled (prefilled link: https://www.va.gov/find-locations/?facilityType=cc_provider)
- [ ] If your selects "no" user can continue in the flow without the CC information

## Design (note: copy in design does not reflect latest copy updates. See AC above)
![Screen Shot 2020-06-26 at 11.48.29 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/aa93bda5-f7d1-43fb-a3da-8e39a4814024)

**Comment by rtwell** [comment]
I'm not 100% on the placement on this because if a user answers "no" to the referral question…shouldnt they be able to make 3 suggestions?

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/588a5969-bdf6-4912-91f3-87bfe24b5a47)

**Comment by lenaecb** [comment]
@rtwell - I agree. I would have the copy/link outside of the actual form. 

@lalexanderson-dsva - can you concur?

**Comment by peggygannon** [comment]
Hello, @rtwell @lenaecb 

Looking at this, I recommend we break out the questions as we're asking Veterans two different questions. 

If they already  have a referral for CC provider, then they wouldn't need to see the question or link asking them if they want to choose a provider from our approved list.   Please let me know if I am understanding that correctly. See recommendation below:

Do you have a referral or a preferred VA-approved community care provider? 
Yes
No/I don't know

{If no}
Would you like to select a community care provider from our approved list? 
Yes
No

{If yes}
Use the [VA facility locator] to find an approved community care provider.

**Comment by lenaecb** [comment]
I feel torn about this. I like the suggestion, but hate that we can't allow for the Veteran who doesn't have a referral/approved CC provider will have to jump out of the app to get to the list (vs. it being exposed in app which we will do in the future when we figure out provider selection/PPMS data needs) 

@lalexanderson-dsva - thoughts?

**Comment by lalexanderson-dsva** [comment]
there are 2 conditions under which a veteran would need to enter an address for a CC provider: 
1. If they have a referral 
2. if they want to pick a provider in the area from the locator. 

If Veterans have a referral, they may not have all of the information they need from their provider and may still need to look at the locator. The name and address are important. As @davidconlon showed me recently - a community care provider might have multiple offices, and one might be very convenient for the Veteran and one might not be. (Think of providers in the DC metro area who spend some days in Maryland, some in DC, and some in Virginia - I would prefer to see the Virginia provider, but if i put write the provider's name, the scheduler might get an appt for me in Maryland, unless i specify). 

@davidconlon was going to give us a URL that presets the locator for community providers.

**Comment by lenaecb** [comment]
@lalexanderson-dsva - thanks for that additional insight. Based on what you described here then, we want to continue with the implementation that Ryan designed above (exposing the copy/FL link only after the Veteran has selected 'yes'). Correct?

Thanks!

**Comment by lalexanderson-dsva** [comment]
I like Peggy's phrasing

Do you have a community care referral or a preferred VA-approved community care provider?
Yes
No/I don't know

then if yes:

Use the [facility locator](https://www.va.gov/find-locations) to find your preferred comm care provider. Copy and paste their name and address below.

**Comment by davidconlon** [comment]
@lalexanderson-dsva  Pre-set for Community Care:
https://www.va.gov/find-locations/?facilityType=cc_provider

**Comment by lenaecb** [comment]
@peggygannon - we're going to keep the question to one question since even if you have the referral or have a preferred provider, you need to cross check with the approved list. 

Do you have feedback on our direction here?

Question: Do you have a community care referral or a preferred VA-approved community care provider?

Yes
No/I don't know

if {yes}

Copy: Use the facility locator (link) to find your preferred community care provider. Copy and paste their name and address below.

**Comment by peggygannon** [comment]
hello! @lenaecb thank you. I have no further edits. this looks good.

**Comment by narin** [comment]
Verified change on staging.  Closing out.
