### ISSUE TITLE
[Analytics] complete Sitemap scan of VISN-4 Legacy sites to complete comparison of URL to URL [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10521]
## Story
Analytics and PAO require the original legacy site mapping to use as a comparison, so they can better understand what is being used, improved, and left behind in the VAMC-upgrade transition.

## Resources
[Comparison Spreadsheet](https://drive.google.com/drive/folders/1WygUuvMetcaCm43woL6rfTursUVUyGeO)

## Tasks
- [x] Find tool that will pull all URLs from Legacy Sites
- [x] List all URLs in Spreadsheet for the following sites
* VISN-4 Legacy Sites:
- [x] https://www.altoona.va.gov/
- [x] https://www.butler.va.gov/
- [x] https://www.coatesville.va.gov/
- [x] https://www.erie.va.gov/
- [x] https://www.lebanon.va.gov/
- [x] https://www.philadelphia.va.gov/
- [x] https://www.wilkes-barre.va.gov/
- [x] https://www.wilmington.va.gov/

## Acceptance Criteria
* Use tool to list all URLs in separate tabs for each system in spreadsheet for the following sites
* VISN-4 Legacy Sites must be included in tabs for review.
* https://www.altoona.va.gov/
* https://www.butler.va.gov/
* https://www.coatesville.va.gov/
* https://www.erie.va.gov/
* https://www.lebanon.va.gov/
* https://www.philadelphia.va.gov/
* https://www.wilkes-barre.va.gov/
* https://www.wilmington.va.gov/

**Comment by SgardnerPMP** [comment]
Tool used: https://www.xml-sitemaps.com/   Allowed review and xml sheet if downloaded for creation of Google site map.
