### ISSUE TITLE
Add FE Sentry Code for Error Handling

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10535]
## Goal
Sentry is a tool that monitors and reports errors thrown that we are interested in - we want to make sure our feature is hooked up into this system so that we can watch for errors and address them quickly as they happen.

## Considerations
- For order of operations, 686 code needs to be pushed into an environment that can be seen by Sentry first - this ticket may go at the same time
- There is another ticket to be mindful of from the BE: #9369

Sentry Sentry should be notified:
- After a failed submission, investigate what happens after job for notification?
- VA File Check (fail or no)
- docu upload (fail or no)

## Tasks
- [x] Look at the Form System to see what controls are in place
- [x] Implement FE code as needed
- [x] Brainstorm how Sentry will be used from the FE's perspective

## Acceptance Criteria
- [x] Sentry is poised to capture and monitor errors for the 686 and when Sentry should be notified

**Comment by cohnjesse** [comment]
@micahchiang @digitaldrk @kathleencrawford Just wanted to clarify a couple of things on this ticket. It looks like for a form submission there really is no place for us to put Sentry code for a form submission other than in our custom `transformForSubmit` function and that function does not receive anything from the backend when it submits so there is no way for us to log a failed submission. Furthermore, the form system has Sentry events built into it so we should not need to add anything for that.

Also with the file upload, there is no place for us to put Sentry code since we just use a file upload UI field and that does not give us access to any callback to fire a Sentry event. Also, it doesn't get a response from the API so we could not log a failed upload. Does this all make sense?

**Comment by micahchiang** [comment]
Thanks for looking into that, @cohnjesse! I think if we wanted to, we could create a custom submit function and pass it in to the formConfig object, something like `submit: customSubmitWithSentry`. I did some poking around and it looks like that's what's being done with the 526 [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/config/submitForm.js).  However, doing something like that definitely bumps the points of this ticket way up, and may fall outside the scope of what we want to do for this ticket. 

It looks like the fileUploadUI has some stuff in the background that handles sentry itself, so yeah, no need for anything there. It sounds like the only thing we need to worry about then is the va file number check. Sentry messages can probably be captured and sent in the action that handles va file number check.
