### ISSUE TITLE
Clone historic 2018 rates page for Disability - Birth Defects benefits

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10544]
# Issue description: 
In order to retire legacy pages with historic disability rates, we need to clone our current rates pages in Drupal and input the 2018 rates information. 

# Tasks:
- [x] Clone current Disability -Disability - Birth Defects rates page in Drupal. Anne
- [x] Copy over rates from legacy historic page, https://www.benefits.va.gov/COMPENSATION/sb2017.asp . Anne
- [x] Copy edit and doublecheck rates and new math examples. Randi

Attached to epic: #10435
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=6189

# Acceptance criteria:
- [x] Pages cloned, numbers checked and reviewed

**Comment by AnneHurley** [comment]
@RLHecht This page is ready for your copyedit: Because this is a shorter/simpler rates page, we probably don't need to go over it together, but if you want, I'm happy to. Just let me know.
2018 Historical Birth Defects rates page: http://preview-prod.vfs.va.gov/preview?nodeId=6189

@bethpottsVADEPO FYSA

**Comment by RLHecht** [comment]
@AnneHurley This page has been copyedited and the rates have been checked again the legacy page. All good! FYSA @bethpotts

**Comment by RLHecht** [comment]
@AnneHurley I modified this ticket so when the cloning work is done and reviewed, we can close this out. I captured the work for SME approval and publishing in ticket #11171
