### ISSUE TITLE
[Provider locator] Duplicate providers and data quality

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10546]
## Issue description

<details>
<summary> Some locations are returned more than once in Community urgent care search results due to providers reported by both CCN and TriWest. </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b6e3ba7c-062f-4baf-a071-7041d8d50766)

</details>

 In the following example, there is also phone number difference. (This is related to a separate issue which occurred during the V0 -> v1 transition)

     
`curl -X GET --header 'Accept: application/json' 'https://dws.ppms.va.gov/v1.0/PlaceOfServiceLocator?address=polson%2C%20MT&radius=50&posCodes=17%2C20&maxResults=10'`

`https://dws.ppms.va.gov/v1.0/PlaceOfServiceLocator?address=polson%2C%20MT&radius=50&posCodes=17%2C20&maxResults=10`

<details> 
<summary> Data for the Bigfork Medical clinic example (several other examples exist in this particular set of search results) </summary>

      "Miles": 33.474,
      "Minutes": 48.333,
      "ProviderName": "Kalispell Regional Medical Center Inc",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "Bigfork Medical Clinic",
      "CareSiteAddress": "8299 MT Highway 35 Bigfork, MT 59911",
      "CareSiteAddressStreet": "8299 MT Highway 35",
      "CareSiteAddressCity": "Bigfork",
      "CareSiteAddressState": "MT",
      "CareSiteAddressZipCode": "59911",
      "CareSitePhoneNumber": "4068375541",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      **"ProviderNetwork": "TriWest - Choice",**
      **"NetworkId": 4,**
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1164726428",
      "Latitude": 48.066891,
      "Longitude": -114.081302,
      "GeoWarning": null,
      "POSCodes": [
        "20"
      ],
      "Telehealth": null,
      "SubServices": []
    },
    {
      "Miles": 33.474,
      "Minutes": 48.333,
      "ProviderName": "KALISPELL REGIONAL MEDICAL CENTER INC",
      "ProviderSpecialty": "Multi-Specialty",
      "SpecialtyCode": "193200000X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "Bigfork Medical Clinic",
      "CareSiteAddress": "8299 MT Highway 35 Bigfork, MT 59911",
      "CareSiteAddressStreet": "8299 MT Highway 35",
      "CareSiteAddressCity": "Bigfork",
      "CareSiteAddressState": "MT",
      "CareSiteAddressZipCode": "59911",
      "CareSitePhoneNumber": "9999999999",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      **"ProviderNetwork": "CCN Region 4**",
      **"NetworkId": 40,**
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1871716936",
      "Latitude": 48.066891,
      "Longitude": -114.081302,
      "GeoWarning": null,
      "POSCodes": [
        "20"
      ],
      "Telehealth": false,
      "SubServices": []
    },
    {
      "Miles": 33.525,
      "Minutes": 49.25,
      "ProviderName": "Kalispell Regional Medical Center Inc",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "Bigfork Medical Clinic",
      "CareSiteAddress": "8299 MT Highway 35 Bigfork, MT 59911",
      "CareSiteAddressStreet": "8299 MT Highway 35",
      "CareSiteAddressCity": "Bigfork",
      "CareSiteAddressState": "MT",
      "CareSiteAddressZipCode": "59911",
      "CareSitePhoneNumber": "4068375541",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      **"ProviderNetwork": "CCN Region 4",**
      "NetworkId": 40,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1164726428",
      "Latitude": 48.06684833,
      "Longitude": -114.080895,
      "GeoWarning": null,
      "POSCodes": [
        "20"
      ],
      "Telehealth": false,
      "SubServices": []
    },
   
</details>

## Steps to Reproduce

- URL: https://www.va.gov/find-locations
- Location = Polson, MT 
- Facility type = Urgent care + Community urgent care providers (in VA's network)

## Desired behavior
Search results should include unique locations only...no duplicate results

## Task
- Add dedup logic to account for Network

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by darkbushido** [comment]
we are de-duplicating off the following attributes
```
  attribute :acc_new_patients, String
  attribute :address, Hash
  attribute :address_city, String
  attribute :address_postal_code, String
  attribute :address_state_province, String
  attribute :address_street, String
  attribute :care_site, String
  attribute :caresite_phone, String
  attribute :contact_method, String
  attribute :email, String
  attribute :fax, String
  attribute :gender, String
  attribute :id, String
  attribute :latitude, Float
  attribute :longitude, Float
  attribute :main_phone, String
  attribute :miles, Float
  attribute :name, String
  attribute :pos_codes, String
  attribute :provider_identifier, String
  attribute :provider_name, String
  attribute :provider_type, String
  attribute :specialties, Array
```
