### ISSUE TITLE
Upgrade Haproxy or Change Haproxy Prometheus Exporter

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#10545]
## Issue Description
The newest version of the prometheus/haproxy-exporter docker image is unable to read haproxy metrics most likely because the uid in docker image has changed.

There are multiple possible solutions:
- change the permissions so the image can get metrics
- update haproxy and use the native exporter
- use http endpoint to scrap metrics instead of unix socket

I'm not sure which is the best option. It make take a little investigation to see what upgrading haproxy to 2.0 looks like and weighing that against these other options. If you find a better option then rock and roll.

---
## Tasks
- [ ] _communicate out so people know this is coming_
- [ ] _upgrade Haproxy_
- [ ] _switch to build in exporter for Haproxy_

## Acceptance Criteria
- [ ] Haproxy prometheus exporter works on newer version or haproxy upgraded
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
@tskinn I didn't see this issue when I spun up #11271 - I'm going to defer to you to close, but the PR [here](https://github.com/department-of-veterans-affairs/devops/pull/7341) is presumably going to fix this.

**Comment by kfrz** [comment]
Closing, dupe'd and fixed [here](https://github.com/department-of-veterans-affairs/devops/pull/7341).
