### ISSUE TITLE
Facility Locator to accept 'type' param for community care

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10557]
## Issue Description
Implement changes to Facility Locator front end to accept 'type' param for community care from v1 ccp controller. This is necessary to support the urgent care mashup. 

response will include 2 types
- 'type': 'cc_provider' -> 'type': 'provider' 
- 'type': 'cc_pharmacy' -> 'type': 'pharmacy' 
- 'type': 'cc_urgent_care' -> 'type': 'urgent_care'
---
## Tasks
- [ ] Ensure front end can support types
- [ ] Add end to end tests for these type params

## Acceptance Criteria
- [ ] Ensure front end can support 'type': 'cc_provider' and  'type': 'provider' 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate
