### ISSUE TITLE
Misc namespacing updates

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#10563]
## Issue Description
The concerns within the common/client/concerns directory need to be namespaced within the ::Concerns namespace in to be in compliance with autoloading and namespacing for Zeitwerk

The MDOT ServiceException needs to be namespaced within the MDOT::Exceptions::ServiceException namespace in order to be compliant with autoloading for Zeitwerk

---
## Tasks
- [x] Add the ::Concern namespace 
- [x] Update/Add MDOT::Exceptions::ServiceException 

## Acceptance Criteria
- [x] Passing specs
- [x] No rake task issues
