### ISSUE TITLE
Compile list of potential debt management FAQs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10560]
## Issue Description
We need to compile a list of potential FAQs to include on the tool landing page and/or in the authenticated experience.

---
## Tasks
- [x] Review pages on debt management site
- [x] Put together a list of potential FAQs we may want to include in the unauthenticated and/or authenticated content

## Documentation and files

**Pages to review for content:**
- https://www.va.gov/DEBTMAN/Most_Frequently_Asked_Questions.asp (may have content that overlaps with the other pages)
- https://www.va.gov/debtman/If_You_Owe_VA.asp
- https://www.va.gov/debtman/Payment_Options.asp
- https://www.va.gov/debtman/Submit_A_Waiver_Request.asp
- https://www.va.gov/debtman/Financial_Status_Report.asp
- https://www.va.gov/debtman/Debt_Referral.asp
- https://www.va.gov/debtman/Submit_Compromise_Offer.asp
- https://www.va.gov/debtman/Whom_To_Call.asp
- consider link to this tool? https://www.va.gov/ogc/apps/accreditation/index.asp

## Acceptance Criteria
- [ ] List of potential FAQs created for review and next steps
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA I've reviewed the debt management pages and included my findings in the Google spreadsheet (I can download/convert as an excel file if needed). Based on my findings, I'm not really sure that the FAQs need to be divided up based on unauthenticated/authenticated experience. The FAQs on the spreadsheet are organized according to a logical flow of questions (my opinion of course!).

I also took a screenshot of the wireframe the team provided and commented my recommendation on placement of content.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much for this, @lunascoop! Looking forward to going over this together in our call.

**Comment by lunascoop** [comment]
[Mapping Recommendations for Debt Management FAQs - Unauthenticated_Authenticated(1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4838834/Mapping.Recommendations.for.Debt.Management.FAQs.-.Unauthenticated_Authenticated.1.xlsx)
