### ISSUE TITLE
Travel pay page: Updates requested by SMEs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10591]
## Issue Description
We've received a request from the Beneficiary Travel team to update how to file a claim information based on process updates.

---
## Tasks
- [x] Review provided document (Danielle)
- [x] Incorporate updates into page and edit for plain language/structure (Danielle)
- [x] Sync with Mikki on structure of page (Danielle)
- [x] Send to Jeff Grandon for OK/feedback
- [x] Copy edit (Randi)
- [x] Send preview link to SMEs (Danielle)
- [x] Incorporate any SME feedback (Danielle)
- [x] Do final proof and set to publish (Randi)
- [x] Validate on live site (Danielle, Randi)
- [x] Communicate published changes to SMEs (Danielle)

## Documentation

[Update to VA Website for Submitting a Travel Claim](https://app.zenhub.com/files/133843125/74cd46b6-735e-49b3-a018-187fd209992a/download)

## Acceptance Criteria
- [x] Changes are on live site
- [x] SMEs are aware of published changes

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
**Current status 7.2.20:**

- Sent preview link with summary of changes/rationale to Jeff 7.2
- Sent status check-in to larger SME group with note that we'll send preview to larger group midweek next week

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This is ready for your review:  http://preview-prod.vfs.va.gov/preview?nodeId=2431.

Let me know if you have questions while reviewing - thank you!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This has been copyedited with the tweaks we discussed in slack. I also fixed the anchor links in the TOC and for the eligibility requirements.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks very much, @RLHecht!

**7.8.20 update:**
- Approved by Jeff Grandon 7.7.20
- Sent to travel pay team 7.8.20 (email below for records). Received all positive initial feedback from Tom C. He and his team will socialize and provide any additional feedback. Also waiting on 508-compliant instruction guide.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/0104c333-d227-47c9-bdb3-7d138eca56fe)

**Comment by RLHecht** [comment]
Page reviewed and published. Moving to validate.

**Comment by RLHecht** [comment]
These changes are validated on the live site. @DanielleThierryUSDSVA can you notify stakeholders and then we can close out the ticket. Thanks! FYSA @MickinSahni

**Comment by DanielleThierryUSDSVA** [comment]
SMEs notified day of publishing. Closing ticket now. Thanks!
