### ISSUE TITLE
[FE] - Profile Content Edits

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#10596]
## Tasks

**Personal and Contact information**

- [x] Zip code needs to be sentence cased  (Zip code, not Zip Code)
![Screen Shot 2020-06-23 at 1.55.58 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/7fd5e4e1-df80-4c9e-bc9d-5f7f7474925a)

- [x] Add period to end of this sentence:
I live on a United States military base outside of the United States.

- [x] Phone numbers should be in this format: xxx-xxx-xxxx
- [x] In mobile phone number, update text message reminder content to:
We’ll send VA health care appointment text reminders to this number
![Screen Shot 2020-06-24 at 9.10.30 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/6aaf33de-c7ec-4918-8174-b0faa1350e13)

- [x] Contact email - ...'where you manage your log in' ...should say 'sign in', not 'log in'
- [x] Update link language to: Update sign-in email address on [name of account]
![Screen Shot 2020-06-24 at 11.10.02 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/af5a100b-3ae4-4af6-93a9-c7eaeb3a7988)

- [x] Update this link "Which of my benefits will use this contact information?"
TO
How will you use my contact information?
We’ll use this information to contact you about certain benefits and services, like disability compensation, pension benefits, and claims and appeals. If you’re enrolled in VA health care, we’ll send your prescriptions to your mailing address. Your health care team may also use this information to contact you.
![Screen Shot 2020-06-23 at 2.02.26 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/fdb79062-ff18-4582-9356-32c779f8e4fe)

- [x] “We’re unable to retrieve” alert (Personal or contact info)
Please update this alert to:
We can’t access your [section]
We’re sorry. Something went wrong on our end. Please try again later.
![Screen Shot 2020-06-24 at 9.18.07 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/84b07cab-cb2d-454e-a441-7834f55d04aa)

<hr /> 

**Military information**

No changes

<hr />

**Direct Deposit**

- [x] Under Education Benefits box: Please make these boldface: **Premium DS Logon, My HealtheVet** and **ID.me**
- [x] 'Bank information' should be 'Disability compensation and pension benefits'
- [x] Please update this sentence to: Please enter your bank’s routing and account numbers and your account type.
 
![Screen Shot 2020-06-24 at 9.28.38 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/66e67c53-47d8-4ac3-9b96-09a0c59a529e)

<hr />

**Account Security**

- [x] Sign in address content: please update to reflect change we made on the contact information screen
Instead of “go to the account” please change to “go to the website where you manage your settings and identify information….”
- [x] Update link language to: Update sign-in email address on [name of account]
![Screen Shot 2020-06-24 at 11.09.45 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/a394e52b-2f06-44e5-a1fc-c2cbb16f5e86)

- [x] LOA1 Screen Green CTA button content should be updated to: ![Screen Shot 2020-06-24 at 11.14.07 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/39257add-eaf9-40fe-a084-e953f74ecd5a)Verify my identity

- [x] Update content in alert: **We can’t match your information with our Veteran records**

We’re sorry. We can't give you access to health and benefit tools until we can match your information with our records and verify your identity.

If you’d like to use these tools on VA.gov, please contact your nearest VA medical center to verify and update your records.
[Find your nearest VA medical center]

![Screen Shot 2020-06-24 at 11.15.31 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/52cde6c9-62d3-48bd-ada5-1833d8a307bd)

**Comment by sanlouise** [comment]
For consistency's purposes, we keep the (xxx) xxx-xxx formatting for phone numbers, but we do want to remove the international prefix. Confirmed with Tressa.
