### ISSUE TITLE
Conduct Usability Testing Prep of "View Payment History"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10597]
## Goal
Once we have laid down our bets for what we think this feature should be doing, we would like to get the latest version of what we have in front of users so that we can be sure that we are headed in the right direction.

## Considerations
- Don't forget to set a meeting with VSP

## Tasks
We will need:
- [ ] Link to product outline 
- [ ] Link to or attach prototype or mockups
- [ ] Link to or attach artifact with copy (if separate from prototypes/mockups)
- [ ] Link to research plan and conversation guide (script)
- [ ] Link to regression test plan (learn more) (if there isn't already a regression test plan for this feature in TestRail) for QA practice area review
- [ ] Link to test cases/test plan in TestRail (learn more) (even if just a draft) for QA practice area review
- [ ] Complete [the request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#usability-testing-prep)

## Acceptance Criteria
- [ ] A meeting with VSP has been scheduled
- [ ] A meeting with VSP has been conducted
