### ISSUE TITLE
Connect review instances with vets-api/ppms

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10604]
## Issue Description
We need the review instances to be connected to vets-api/PPMS so we can use them for QA. 

---
## Tasks
- [ ] Connect Facility Locator review instances with vets-api/PPMS (staging)

## Acceptance Criteria
- [ ] PPMS staging data is available in review instances and is consistent with Swagger

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
Since we are moving to Cypress for all new e2e tests, can I assume this issue pertains only to Cypress tests?

**Comment by mpelzsherman** [comment]
@mmiddaugh @davidconlon - please see this comment from @U-DON in Slack:

https://dsva.slack.com/archives/CBU0KDSB1/p1593120905382400?thread_ts=1593113381.350300&cid=CBU0KDSB1

Sounds like this ticket conflicts with the platform team's plans for end-to-end tests. They intend to use https://pact.io/ instead. Let's discuss!
