### ISSUE TITLE
Pre-Launch Text Changes for 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10601]
## Goal
Before launch, there might be some late text changes that need to be implemented coming from internal findings, recommendations from research, and Peggy's feedback.

## Unknowns
- Extent of recommendation 
- Peggy's feedback

## Tasks
- [x] Address any text changes we have
- [x] Triage recommended changes from research
- [ ] Sync with Peggy and get her feedback

## Acceptance Criteria
- [x] Changes have been addressed and a list of changes has been shared with the FE
- [x] A new punch list of changes that are considered for pre and post launch

**Comment by sporeboy** [comment]
Punchlist is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0720.md

Need to triage list. Most items are text revisions.

**Comment by sporeboy** [comment]
Text revisions align with Nick's recommendations. Have not connected with Peggy--would like these changes in-place before her review. 

Many of these text changes will basically resolve some of the QA mis-matched text bugs if implemented.

**Comment by sporeboy** [comment]
Form organization, updates and feature improvement recommendations are not included in this ticket.
