### ISSUE TITLE
[Content] Research and write Intern and Fellowship program Part 2 pages for Salt Lake City Health Care [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10609]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Salt Lake VA Medical Center legacy Site](https://www.saltlakecity.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-19 Content Folders](https://drive.google.com/drive/folders/1KVjgw4Z56Zm3m1TVTDktpKk9aKVpP9ms)

## Tasks
_Review content pages created for below_
*Create a new copy of the document and call it "REVIEW", turn on "Track Changes" and update with comments.  Save document in word for full review
* The following pages will have to be reviewed:
- [x] Post-Baccalaureate Nurse Residency Program
- [x] Post-Graduate Primary Care Nurse Practitioner (PC NP) Residency Program
- [x] Post-Graduate Psychiatric Nurse Practitioner Residency

## Acceptance Criteria
* Completed Content Review is saved in Word Document format "REVIEW"
* Post-Baccalaureate Nurse Residency Program
* Post-Graduate Primary Care Nurse Practitioner (PC NP) Residency Program
* Post-Graduate Psychiatric Nurse Practitioner Residency

* Page must be saved in Content folder on Google Drive under Page reference name
* Save final reviewed copy with all tracking removed in Google Drive with System Name with "FINAL" in title.
