### ISSUE TITLE
[Backend] Create test  users/use case scenarios for DMC data 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10603]
## Issue Description
_Create test users with applicable use use scenarios for veterans who have debt and do not have debt (paid off)  

---
## Tasks
- [ ] _Identify all applicable use cases for user testing
- [ ] _provide  data to DLC with assocaited test user accounts

## Acceptance Criteria
- [ ] _This is an input for FE qa _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by camerontesterman** [comment]
Created a PR to add in the user with the chapter 33 debt. Need to confirm the details once we have access to a test user with ch 33 debt.
