### ISSUE TITLE
Create a Conversation Guide for "View your VA payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10600]
## Goal
We want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users we will be communicating with.

## Considerations
Conversation guides are usually incorporated into Research Plans but because they are large enough, we separate them.  Both are considered deliverables.

## Task
- [x] Coordinate with Shawna on some of the questions to ask in the conversation guide
- [x] Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-convo-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
## Acceptance Criteria
- [x] Conversation Guide has been sent to Shawna for review

**Comment by sporeboy** [comment]
Link to guide provided. Convo guide (and research plan) will need updates when usability testing is scheduled.

The convo guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/research-design/payment-history-convo-guide.md
