### ISSUE TITLE
Update getting access documentation to account for changes to github access flow

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#10616]
## Issue Description
Work with Ops team to nail down the process for new VFS teams/team members to get write access to the va.gov-team repo during orientation so we can guide VFS teams on how to get write access when they start. 

---
## Tasks
- [ ] Work with DEPO to figure out what their new process is
- [ ]Work with OPs team to figure out how we want to use github teams for access

## Acceptance Criteria
- [ ] A new process has been nailed down and documentation is updated. 
---
