### ISSUE TITLE
686 Remaining Punch List items

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#10627]
## Description
[686 Punch List](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0420.md)

Some items on the punch list remain incomplete because we agreed they would be done post-launch. Since then, the launch date for the 686 has been postponed, and these things can be completed. 

## Considerations
1. Checkbox order change requires a change in `vets-json-schema`. 
1. Triage items in [QA Results](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10096)

## Tasks
Items remaining:
- [x] Update labels with bold text, see punch list
- [x] Change order of task wizard checkboxes. This involves a change to our schema in `vets-json-schema`
- [x] Add paragraph to review screen, see punch list
- [x] Deselect radio button in stepchild workflow
- [x] Submission failure button

## Acceptance Criteria
- [ ] TBD
