### ISSUE TITLE
[Frontend] DL-Create Debt Details Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10626]
## Issue Description
_Create Debt Summary page per [design](https://preview.uxpin.com/305eb36ed6ec2e5f2bc1dd91659b70ef961ab269#/pages/129743302/simulate/sitemap?mode=i). As a veteran who is authenticated on va.gov I want to see my deb summary that contains the information I received in debt letter in the mail 

---
## Tasks
- [ ] _Design page per provided designs
- [ ] _Display back end data from API of betamocks if local 
- [ ] _Run axe for 508 
- [ ] _Write and run Unit tests
- [ ] _Ask Designer to QA page prior to merging 

## Acceptance Criteria
- [ ] _Page matches design and designers agree
- [ ] _Unit tests pass
- [ ] _for a given test user, the data returned matches API response
- [ ] _No 508 errors
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
