### ISSUE TITLE
686 Load Testing

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#10624]
## Description
The 686c uses up to 4 endpoints in vets-api:
1. VA file number check
1. Save in progress (platform?)
1. Document upload (platform?)

When the 686 gets submitted it kicks off a job that handles the rest of the payload submission in the background. The question remains whether or not load testing needs to be done for this scenario. 

## Considerations
- Load test research [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/LOADTEST.md)

## Tasks
1. Verify whether or not load testing is necessary when a job is used to handle payload submission to bgs
1. Load test VA file number check and the other two endpoints, SIP, doc upload if available
 - Writing locus test
- Generate a README.md with results

## Acceptance Criteria
- [ ] VA file number check has been adequately load tested. 
- [ ] Locus test have been written
- [ ] A README.md file has been created

**Comment by micahchiang** [comment]
PR for the va file number check load test here - https://github.com/department-of-veterans-affairs/devops/pull/7246
