### ISSUE TITLE
[Frontend] MDT - Remove 'Need help' component from screens that only return alerts 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#10637]
## Issue Description
_I noticed that the 'Need help?' component is included on screens that are returning error alerts (404, 500, etc). The 'Need help?' component isn't included on other forms displaying these types of alerts, so we should remove that component from our form to align with VA.gov design patterns._

To reference an existing error alert w/o the 'Need help' component, [sign into the 526-ez form](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction) with `vets.gov.user+1@gmail.com`

---
## Tasks
- [ ] _Remove the 'Need help' component from alerts returned on the introduction screen (deceased veteran, all items ineligible, veteran not in database, error 500, no orders played within the past 2 years) and the confirmation screen (submission error, empty order submission). Reach out to a designer with any questions about which alerts apply._
- [ ] _Provide screenshots of the appropriate alerts without the 'Need help' component to validate w/ design team_

## Acceptance Criteria
- [ ] _The 'Need help' component has been removed from returned error alerts on the introduction and confirmation screens_
- [ ] _Design team has been notified of the changes_
---

**Comment by mr0sari0** [comment]
With many hours of discovery, lots of experiments, and searching through previous threads in the platform-support channel like this [one](https://dsva.slack.com/archives/CBU0KDSB1/p1578340698175600?thread_ts=1578339207.168300&cid=CBU0KDSB1), I will say that the `formConfig `object is built to remain static so we could not dynamically remove the footer by updating the object later on in the app or anything else on the `formConfig` for that matter.

It appears 526-ez has the _only_ existing way to do this within the forms-library. 

The way 526-ez  is displaying an alert while hiding the footer is by conditionally rendering the `RoutedSavableApp` component on its `Form526EZApp` file if no issues happened and rendering the alerts instead if there was a problem. 

From what I see so far, the steps involved for us to do the same will be:

- Update our `App` file to render the `RoutedSavableApp` component if no errors are present
- Move all of our error state UI from the `IntroductionPage` component to the `App` component

I'll update this if anything changes.

**Comment by mr0sari0** [comment]
Updating the estimate for this task to match the effort required.

**Comment by mr0sari0** [comment]
Assigning to @bradl3yC to explore further solutions.
