### ISSUE TITLE
Analytics Tracking - Hard Refresh Capabilities - Mobile Users

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#10633]
## What happened?
_At times, Google Analytics data can be affected by mobile users caching an old version of the site (and inherently Google Tag Manager) for several days. Similar to what we saw on #10420 -- if a bug is raised, and that bug is corrected within a deployment, if the user still has a cached version of the site still open on their mobile browser (a common occurrence in today's digital landscape) from when the bug existed, the buggy data will still live on. _

## Example Screenshot
- Here is an example of a user who visited the tool originally when the bug existed, and again yesterday since the issue has been resolved on the GTM & FE sides. 

![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/d36ef65e-8af8-4efd-9db2-8074e6048419)

## Specs:
- Device: Mobile

## Expected Results
_The analytics and insights team would like to explore capabilities for hard refreshing of mobile users. We would like to ensure cross-team this isn't an issue we are completely at the mercy of the user to resolve_

## Acceptance Criteria
- [ ] _Tracking corrects as a result of hard refresh_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jonwehausen** [comment]
#10420

**Comment by jonwehausen** [comment]
Closing in light of documenting post mortem here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/130
