### ISSUE TITLE
Clone historic 2018 rates page for Disability - Special Allowance benefits

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10635]
# Issue description
In order to retire legacy pages with historic special allowance rates, we need to clone our current rates pages in Drupal and input the 2018 rates information.

# Tasks:
- [x] Clone current Disability - Special Allowance rates page in Drupal. Anne
- [x] Copy over rates from legacy historic page, https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2017.asp
- [x] Copy edit and doublecheck rates and new math examples. Randi

# Acceptance criteria:
- [x] Pages cloned, numbers checked and reviewed

Epic: #10544
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=6190

**Comment by AnneHurley** [comment]
@RLHecht 
Special benefit allowance 2018 historic rates page: http://preview-prod.vfs.va.gov/preview?nodeId=6190

Ready for copyedit/validate
@bethpottsVADEPO  FYSA

**Comment by RLHecht** [comment]
@AnneHurley @bethpottsVADEPO I reviewed this page but I put it in Blocked because we are awaiting stakeholder feedback on the rate dates. We currently list October 10 and December 12 for when rates start but the legacy page mentions October 1 and December 1. The later dates are also on the current rates page so Beth is checking with stakeholders next week to determine if there's an error or these dates have changed. FYSA @MickinSahni

**Comment by RLHecht** [comment]
@AnneHurley I've updated the criteria of this ticket to reflect it's complete when we have input new numbers and reviewed the page. Please note that we still have it as "blocked" while we await the correct dates for rates from the stakeholders. I captured the work for SME approval and publishing in ticket #11171 FYSA @MickinSahni

**Comment by RLHecht** [comment]
The work on this ticket is now complete. SME feedback shows dates should be October 1 and December 1 so I've changed them in this page (as well as on the current page). Closing ticket.
