### ISSUE TITLE
Expand test coverage for mobile experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10650]
## Background
We need to expand the test suite specifically for the mobile experience

## Tasks

**1. Ensure the following user stories are covered by existing tests**

<details>
  <summary>When a Veteran uses a mobile device to visit https://www.va.gov/find-locations (expand) </summary>

All search fields and associated drop-down lists are visible.
All buttons are visible.  
All content, including the map, is visible. 
No content gets focused off screen or is hidden from view.

</details>

<details>
  <summary>When a Veteran views the detail page of a selected VA facility with a mobile device (expand) </summary>

All search fields are visible.
All buttons are visible.  
All content, including the map, is visible. 
No content gets focused off screen or is hidden from view.

</details>

---

**2. Correct any existing tests if intended functionality has changed since the tests were created.**

---

**3. Write additional tests to expand coverage for existing functionality.** 

---

**5. Conduct testing to ensure tests are correct.**

---

## Acceptance Criteria:

- [ ] Tests cover the mobile experience
- [ ] Tests pass with current functionality. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Note: during grooming today, the team decided to implement mobile responsiveness checks into the VA health facility E2E test suite. Because all VA facility type detail pages have the same layout and content, we can cover the similar functionality for VBA, NCA and Vet Centers while checking VA health-specific areas for services, appointment wait times and satisfaction scores.

**Comment by brangi** [comment]
merged
