### ISSUE TITLE
Create Team Charter Documentation

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#10661]
[Create Team Charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/health-products/healthcare-experience/team-charter.md) 

---
## Tasks
- [x] Create team folder 
- [x] Team Mission Statement
- [x] Team North Star
- [x] Finalize Charter document for Team norms 

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by abuckley3385** [comment]
@LEHigley Im adding you to this issue so we can draft a team Mission and North Star statements. The rest of the charter has been reviewed and complete.
