### ISSUE TITLE
[MINI] Authenticated form flow: Make decision on whether to show Bio info in static component, or allow authenticated user to manage Bio fields

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#10671]
## User Story
As a Veteran, I want to know what info is changeable and how to do that so that I can ensure my record is up to date and represents my situation accurately.

## Goal 
Figure out which path we will implement for displaying static unchanging info.  If the Veteran is shown two different forms that one allows for a change in data, and another does not, we need to ensure there is ample messaging as to what steps need to be taken and why.

## Considerations
- In the first two flows of [this workflow](https://xd.adobe.com/view/0c64c9ff-aba2-422e-4d6e-be1ec4cab845-7a55/), there is BIO info shown in a static component (where the Veteran needs to call a person to change it) and in the other, the authenticated user can manage the BIO fields "normally" by simply completing the form.
  - There should be some consideration to whether the business has the capacity to update the static, hardened info as it comes through in our application
- How do we communicate to the Veteran that either a) they can change this with a person over the phone, or b) they can change these prefilled fields and then:  
  - Communicate what happens next: new data will be saved globally vs ONLY USED in that form application's instance.
- There could be ripple effects of these decisions to other features.

## Tasks
- [x] Bring both patterns to platform design practice for feedback
  - [x] Schedule  and attend a meeting with design folks (Monday, June 29 @ 1 pm ET)
  - [x] Schedule  and attend a meeting with eBenefits Team to present views
- [x] Record decision in decision docs
- [x] Make it so 

## Acceptance Criteria
- [x] A path forward has been established, documented and shared with the team.

`Next Steps`
- Create a proposal for one way or the other based on what we want to do, share that with Shawna
- Take a stab at content
- Share with Peggy
- Come back to team
