### ISSUE TITLE
STEM Scholarship content request from BAH Education Team

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10670]
## Why you're here
- Content support for static public website pages
- Content support for authenticated application or tools
- For specific copy editing tasks
- Support for redirects that have **first been vetted by the VSP IA team**
- Engineering support for implementation of REACT sign in widgets

## Steps to complete intake request
- [x] Submit this request when VSA Public Website team intervention is required
- [x] Provide detailed information of your request to help us understand our role in completing your request 
- [x] Link to this issue in #vsa-public-websites in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Background
The Rogers STEM Scholarship is an education benefit available to Chapter 33, Post-9/11 Veterans and Fry Scholars.  Because STEM degrees often require more time to complete than Chapter 33 benefits cover, the Rogers STEM Scholarship provides additional education benefits (up to $30,000) and housing allowance for qualified applicants who are finishing up a STEM degree or who have a STEM degree and are pursuing a teaching certification.   

Content which provides background information on the Rogers STEM Scholarship, including details on qualifications and approved STEM degrees, currently lives on orphaned pages on benefits.va.gov and is not indexed in VA.gov search.  This request is to bring that content into VA.gov, align it with VA.gov content styles, and ensure that it’s accessible via Google and VA.gov site search.  

Currently, the Rogers STEM Scholarship can be applied for via the existing VA Form 22-1995 on VA.gov. The 22-1995 is generally used for Change of Program or Place of Training.  The scholarship application functionality was incorporated into that form in late July 2019, as a temporary solution. By September 10, 2020 we plan to launch a brand new, independent STEM Scholarship application on VA.gov, VA Form 22-10203. 

The launch of the new stand-alone application likely will have minimal impact on any associated VA.gov content. 

* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
There is currently supporting content on VA.gov related to the STEM Scholarship that needs to be updated to reflect the current and future status of the application. 
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * 22-1995 form with STEM form product documentation: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/stem 

   * STEM Standalone form product documentation: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/stem/stem-standalone-10203 

       * Research Readout for STEM Standalone form (note this will be helpful from a content perpsective because it highlights the difficult people face when attempting to navigate to the existing Scholarship application on VA.gov: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/research/22-10203-RogersSTEMScholarship-TestingReadout-20200611.pdf 

### Request Type
*Select all applicable and provide details behind your request* 

- [x] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * Word document with draft if available, or link to the URL where the draft content appears:
     * Existing Content that needs to be moved to VA.gov and updated in collaboration with Education Services: https://benefits.va.gov/gibill/fgib/stem.asp 
     * Approved STEM degree programs PDF https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf   
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * < design context >
   * Scope: How many screens? (Or messages, etc.) 
      * < scope > 
      
      
- [x] **Content support for a static public website page**
   * Is this to update existing static content? 
      * < Y >
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * < y/n >
   * Provide a list of URL/s that need to be reviewed or updated. 
      * https://benefits.va.gov/gibill/fgib/stem.asp 
         * Approved STEM degree programs PDF https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf   

- [ ] **New URL or Redirect Requests**
   * Have you vetted this request by the VSP IA team?
      * < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * Link to VSP IA Redirect Request ticket
      * < Github issue link >
      

- [ ] **Implementation of REACT sign in widgets**
   * Full spec including different states and behaviors
      * < link to spec >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*
* Standalone STEM Form will launch between 08/31/20 and 09/10/20 

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: BAH Education Application team - VA.gov  
- DEPO product owner: Matt Self 
- Product manager: Darrell Neel 
- Designer: Amy Knox 
- FE engineer: Dan Shawkey 
- Product/team Slack channel: bah-team 

--- 
#### Acceptance Criteria
- [x] Convert this request into a Zenhub epic
- [x] Follow-up with requestor to address any lingering questions/concerns
- [x] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by lunascoop** [comment]
Thanks @desireeturner. I'll review.

**Comment by desireeturner** [comment]
Hi @lunascoop... Wanted to check in on the progress of this request. Do you need any more information or have an estimate on when this content will be ready to go live? Thank you!

**Comment by lunascoop** [comment]
Hi @desireeturner do you have some time today or tomorrow to review this request? I just want to make sure everything is covered. It seems that this may involve IA and possibly a bit of FE engineering for a react widget. My schedule is pretty open today and tomorrow.

**Comment by desireeturner** [comment]
@lunascoop how does 2-2:30PM work for you tomorrow afternoon? If that works I can set it up... just let me know what email address to include for you. Thank you!

**Comment by lunascoop** [comment]
@desireeturner that works for me. My email is scooper@governmentcio.com. I noticed that an IA ticket was open with relation to this form (#11284). Perhaps it may be helpful to include Mikki, if she's free.

**Comment by MickinSahni** [comment]
Requests include:
- react widget
- built-out drupal page
- unauth content 
- IA

**Comment by amyknox** [comment]
@lunascoop @mnorthuis @DanielleThierryUSDSVA & @MickinSahni We met with the Education Service team (Luke Tickner et al.) and they're on board with moving forward with the effort to migrate STEM Scholarship content to VA.gov

What's our next step?

**Comment by DanielleThierryUSDSVA** [comment]
That's great - thank you, @amyknox! Next step will be IA/content strategy. Will circle back with @mnorthuis and @lunascoop to put together thoughts on timing as well, and will be in touch soon. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @bethpottsVADEPO

**Comment by amyknox** [comment]
> That's great - thank you, @amyknox! Next step will be IA/content strategy. Will circle back with @mnorthuis and @lunascoop to put together thoughts on timing as well, and will be in touch soon. Thanks!

Hey @DanielleThierryUSDSVA - do you have an idea of the timing for connecting with the Education Service team for this process? We have a mtg with them this afternoon and I'd like to give them an idea of what to expect next and when.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @amyknox. Apologies! I didn't see the above in time. Feel free to slack me directly if you need a quick answer on anything in the future.

I connected with Mikki on IA, and since this is pretty straightforward in terms of IA, we don't think we need to have a meeting with SMEs to go over IA. So, the first step with SMEs would be us sharing a preview of the reworked page on VA.gov (the page their existing page would redirect to) and asking for their feedback.

To support being able to have everything in place by 9/1/20, we would aim to share a preview of the page with SMEs by 8/19/20. And we'd ask for any feedback by 8/26/20.

Let me know if you have any questions about this!

**Comment by mnorthuis** [comment]
@amyknox as FYI, from an IA perspective, the STEM content page and application will very likely live within the "Other education benefits" section that exists today.  I do not like using "other" buckets, but that is what exists now so we will utilize that.  It will likely require a little rework of that existing "other benefits" landing page to make sure things are identified and highlighted appropriately.

**Comment by amyknox** [comment]
@mnorthuis - the "Other education benefits" page seemed like the location most users would look for info on the STEM scholarship. 

Do you have an ETA on the final answer for the location?  Our breadcrumbs and URL are contingent upon this decision.

**Comment by mnorthuis** [comment]
@amyknox Finalized IA would come once research is complete and it validates or changes any IA.   I will post draft IA info, that includes the breadcrumbs and URLs to work from in the IA ticket for reference.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @desireeturner @amyknox. I'm going to be OOO next Mon-Wed, so just checking in with a quick status update. We'll have the STEM page (and related tweaks to Other education benefits & education hub page teaser) in Drupal ready to share with SMEs by 8/19, as noted above. Will aim to have ready by 8/17 to share with you all just to make sure we're aligned before it goes to SMEs. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @amyknox @desireeturner. Here's a link to the preview page:  http://preview-prod.vfs.va.gov/preview?nodeId=6860.

We're going to do a little more finalizing of copy tomorrow, and then this will be ready to go to SMEs. Please let me know if you have any questions or concerns as we're finalizing. 

Also, a note & a question for you:

1.  Note: We have the button linking to the invision form for now. 
2.  Question: We have included instructions for mailing the pdf form or bringing the pdf form in person to a local VA regional office, as this is our typical approach to applications. Will there be a pdf form for the STEM scholarship? If yes, is that available yet? If no, we'll remove those instructions. 

Thanks!

**Comment by amyknox** [comment]
HI @DanielleThierryUSDSVA 

Thanks for pinging us on this. I can't seem to access the preview-prod page... could you send a screenshot? Or is there another way to preview it? 

In response to your questions...
1. OK.
2. There will not be a PDF form. This is an online application, only. 
3. Is this question about the preview / content page? If so, that screenshot will help us understand.  Generally, you're right about the eligibility criteria, though... we definitely want people to read that and confirm they're eligible before clicking into the form so that's why we've not be overly generous with the location of the "start the application" button on our pages.  =)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @amyknox. Thanks for answering the Qs above!  Here's a pdf of the page. You need to be signed into the VA network to view the preview, so that may be the issue.  

[stem scholarship page](https://app.zenhub.com/files/133843125/d22359d0-3538-41b7-bac3-17b1a21ad47a/download)

The button doesn't appear right in the pdf. It will look like this on the page:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/7e9c9eb6-f9ff-4669-add1-21468af3e1d4)

**Comment by amyknox** [comment]
@DanielleThierryUSDSVA - got the visual this time, thanks! 

No concerns at all about where the button appears.  You're on the right track with the thinking that we want people to at least have to scroll past the eligibility criteria before they apply.  

Curious...
1. what level of input you're looking for from the Booz team?
2. are you sharing with SMEs or is that something we'd do?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @amyknox!

1. Primarily just want to make sure we're aligned in approach based on usability research, etc. and there are no big concerns so that the user has a consistent experience from unauthenticated to authenticated (and Peggy on Platforms team will help with this as well in her review of the actual form content). But always welcome any thoughts for consideration.

2. We've been working this out on a team-by-team basis, based on established relationships with the SMEs. Our team does have a relationship with education SMEs, so we can send this over for review. Or, if you'd prefer to send over and cc us since you've been the primary group working on STEM to date, that works too. Just let me know and I can either send or provide notes for the email. Thanks!

**Comment by amyknox** [comment]
@DanielleThierryUSDSVA - The content looks solid - it hits all the eligibility criteria and answers several questions we get regularly. 

It'll be faster for you to handle the content review & updates directly with your SME contacts.  Our team has a standing meeting with Education Service today.  To support the content creation effort, we'll share the PDF content with them and point them to this story if they have input. LMK if that works for you.

**Comment by DanielleThierryUSDSVA** [comment]
Here's the preview link and a pdf of the updated **Other education benefits** page.

preview-prod.vfs.va.gov/preview?nodeId=945
[other education benefits](https://app.zenhub.com/files/133843125/74dd61f4-6cc9-4f77-b5af-582f7187fa29/download)

**Comment by DanielleThierryUSDSVA** [comment]
**Status update:** Launched targeted for 9/10/20. Education SMEs will provide any pre-launch feedback by 9/9/20.

**Comment by desireeturner** [comment]
@DanielleThierryUSDSVA Are we good to close this out post-launch? We're all good from the BAH perspective. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @desireeturner. Thanks for checking! All good on the BAH side. We just have one open ticket re: adding a few cross links on other education pages. As soon as we've completed that, I'll go ahead and close this. Thanks!
