### ISSUE TITLE
Compile Resources for Privacy and Security Review (Dependency Claims)

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#10673]
## Description
One of the final steps in the collaboration cycle is scheduling a privacy and security review with VSP to ensure an application meets platform standards before going to production. 

## Considerations
- [Collab Cycle meeting description](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)
- all artifacts need to be compiled two days prior to the review meeting [per collab cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review).

### Backend
1. Architecture diagram showing involved systems and data flow.
    - [Example here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8179) (Backend)
1. Description of any new publicly exposed endpoints
1. Description of any new interactions with 3rd party services
1. Description of any other security hotspots you're concerned about   
### Product
1. Link to the release plan for your application (To be addressed by Product [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10825))
    - [Release Plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)

## Tasks
- [x] Compile all above artifacts into the [Privacy and Security GitHub folder under the Dependency Claims feature](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/privacy-and-security)
- [x] Ask Jason to create a request per [these instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)

## Definition of done
- [x] All artifacts have been provided and stored in github

**Comment by digitaldrk** [comment]
![686c-674_lib_submission_process.png](https://images.zenhubusercontent.com/5e62b7b08eb909e3dc9d38f7/b353ab99-f678-4d75-90ab-9b7cf424c49e)


@jason-gcio How is this for an architecture diagram?

**Comment by jason-gcio** [comment]
Hmm its tough to read for me...can you walk me through it real quick?

**Comment by jason-gcio** [comment]
There is this too: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8179

**Comment by digitaldrk** [comment]
[https://app.zenhub.com/files/133843125/51e0cd98-24d8-4ee6-b1bf-2da94faa1b86/download](https://app.zenhub.com/files/133843125/51e0cd98-24d8-4ee6-b1bf-2da94faa1b86/download)

**Comment by digitaldrk** [comment]
The only exposed endpoint is `https://va.gov/v0/dependents_applications`. This is a `POST` that receives data from the 686 form for processing. This endpoint is guarded by authentication looking for a valid `api-session` in the header.
