### ISSUE TITLE
Review right rail "Connect with us" main links

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10678]
## Issue Description
Right rail "Connect with us" links aren't consistent and one redirects to Va.gov. Need to do quick audit/check that the right resources are in place, and/or consider removing them altogether, as the Records page doesn't have one at all.

---
## Tasks
- [x]  Identify all the hub pages with these right rail links. Anne
- [ ] Discuss appropriate strategy to apply to these links. Danielle, Beth, Anne.
- [ ] Rewrite and/or remove these links. Nick/front-end, with Anne.Randi overseeing.

Pages in question:
#
-- | -- | --
/careers-employment/ | -- Veterans Benefits Administration
/records/	| No link 
/life-insurance/	| Veterans Benefits Administration
/service-member-benefits/	| Veterans Affairs (home page VA.gov)
/housing-assistance/	| Veterans Benefits Administration
/burials-memorials/ | National Cemetery Administration 	
/pension/ | -- 	Veterans Benefits Administration
/decision-reviews/	| Veterans Benefits Administration
/family-member-benefits/	| Veterans Affairs (home page VA.gov)
/disability/	| Veterans Benefits Administration
/change-address/	| No link (but would it need one, with no right rail?)
/education/	| Veterans Benefits Administration

**Comment by mnorthuis** [comment]
The "Connect with us" 

My recommendation would be to remove the "Connect with us" box from the `/family-member-benefits` and `/service-member-benefits` hub pages. All other hubs should remain as they are. 

Background info:
- box on the hub pages should be specific to the administration that owns that benefit - so all VBA benefits should have VBA links, Health care should have VHA links and burials should have NCA links.  
- The records hub (`/records/`) is not specific to an administration and therefore does not have administration links.
- The `/change-address/` page is not a hub page and should not have a right rail.

Here are some analytics on click events for the family member and service member hubs.  The clicks are extremely low. 

![image](https://user-images.githubusercontent.com/20994159/86175879-b086ec00-bae9-11ea-95c4-e90e7a9749aa.png)

**Comment by DanielleThierryUSDSVA** [comment]
Yes, agree on most hubs remaining as they are. And yes, change address isn't a hub so no right rail at all.

I'm not sure this was framed accurately. We don't want these to be consistent - they're specific to their respective hubs.

I think the only question we really had here was whether on 2 specific hubs we should remove the "Veterans Affairs" links from the service member and family member hubs since those links send the user to our homepage.

@mnorthuis will defer to you on this, but I kind of like leaving the "Connect with us" boxes on those 2 hubs and just removing the "Veterans Affairs" link. Definitely don't feel strongly about it though. Thanks!

**Comment by mnorthuis** [comment]
Keep in mind that the remaining items (all global) are all linked to in the footer, and given how low the clicks are on all of those items, I'm not sure if they provide alot a value to this page.  

I would be open to leaving the box and removing the "Veterans Affairs" link, but would like to see the analytics checked again later this year and if it continues to be low volume, it may be more distracting than helpful.

**Comment by jenniferlee-dsva** [comment]
Is there a particular reason why the "Veterans Affairs" link should be removed? On same page as Danielle -  I don't  feel strongly either way, but I had always been informed that these right rail links are mainly to appease VA business requirement -- bc we basically scrambled the 'content-organized-by-administration' model to veteran-facing model, and the administrations were anxious about losing 'branding' re what administration owns what. But I don't know this first hand; it was always just something that was part of WBC history/story telling.

**Comment by mnorthuis** [comment]
The "Veterans Affairs" link just links to the home page of va.gov, which really doesn't provide a helpful experience at all.   The family/service member hubs were well after the WBC and not as connected to specific administrations, so we have a bit more elbow room to modify.  The primary contact information is important, but the other items are global to VA, not specific benefits.

**Comment by mnorthuis** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA Would you like to pursue this still, or should we close out?

**Comment by DanielleThierryUSDSVA** [comment]
Oh wow, this is an oldie, @mnorthuis! 

I'm not opposed to thinking about this again at some point, but I also don't think it's by any means a priority. So I'm wondering if we close this ticket and fold this work into broader work that we want to do when we look at the family and service member hubs. For example, when we get to the family member hub work we've talked about, we could address this question as part of that effort.

Thoughts?

**Comment by mnorthuis** [comment]
Completely agree
