### ISSUE TITLE
Investigate and discover more of the underlying stacks for how EVSS works and with the vets-api integration

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1068]
As a Veteran user of VA.gov, I would like to be able to view my Rated Disabilities so I can manipulate them as is done currently in eBenefits. 

Let’s assume, for now, that the stand up route for rated disabilities will be https://www.va.gov/disability/my-rated-disabilities/.  Last string should be the page file name.

### Considerations
- There are 3 repos that may be impacted
  1. vets-website (frontend) 
  2. va.gov-content (many markdown files are stored)
  3. dev-ops repo (?)
- EVSS stands for Enterprise Veterans Self Service and is a web service to BGS which stands for Benefits Gateway Service and points to CorpDB which is a database for the VA.
also:
- Enterprise Military Information Service (eMIS) - VA/DOD Identity Repository (VADIR)  - Defense Enrollment Eligibility Reporting System (DEERS)
- Swagger docs are for EVSS rated disabilities: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Platform/EVSS%20Integration
----
### Research
- [x] Frontend deep dive
  - [x] Coordinate with an AdHoc FE or Nick Sullivan
- [x] Partner with an existing engineer to feel out the workflow
  - [x] Coordinate with Chris Valarida and set up a time to chat
- [x] Reach out to Silvio and see if you can get 10-15 minutes for some EVSS intro

**Notes - What have we learned?**
- vets-api repo already contains a number of endpoints that plug into EVSS
-   

----
### To-do's
- [x] Render vets-website locally
- [x] Investigate the data pull with another eng
- [x] Continue discovery with other engineers (Chris Valarida)
- [x] Document any hangups
- [x] Login with test account
----
### Definition of Done
- [x] Discovery of the environments feels complete enough to move forward
- [x] Define needs for development

**Comment by micahchiang** [comment]
created [1068-ebenefits-rated-disabilities-page](https://github.com/department-of-veterans-affairs/vets-website/tree/1068-ebenefits-rated-disabilities-page) to capture the work of this issue.

**Comment by micahchiang** [comment]
Frontend Deep Dive Scheduled for next week with Bill Tran
