### ISSUE TITLE
Write Unit Tests for Responsive Table on View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#10695]
## Background
Since we have built a custom version of the table component from the design system to make it responsive, it does not use the unit tests for the existing table component.

## Tasks
- [ ] Write unit tests for the responsive table code

## Acceptance Criteria
- [ ] The unit tests for the responsive table showing payments to the Veteran are complete
- [ ]  The unit tests for the responsive table showing payments returned from the Veteran are complete
