### ISSUE TITLE
Meet with GA re: Events to "View Payments"

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#10697]
## Goal
We want to meet with the Google Analytics Team to establish what events we want to fire for the this feature.

## Tasks
- Connect with the GA/Insights Team (over either Slack or Zoom) to share what function and features this product is involved with, and a recommendation for what events they might be interested in tracking.
- We then need to add the code to fire those events.
- Ask if there is a formula to how event names are developed

## Acceptance Criteria
- [ ] The GA/Insights Team has been met with
- [ ] We have shared our feature and discussed its basic functionality

### Next steps
-  [ ] Code provided by the GA/Insights Team has been shared with us, to be inserted into our feature

**Comment by micahchiang** [comment]
Meeting was held last Friday, so closing for now.
