### ISSUE TITLE
Add Sorting to View Payments Table Columns

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#10693]
## Goal
Currently, the tables on the View Payments page are not sortable yet. The tables themselves provide an interface to connect sorting logic to but we still need to create that logic.

## Tasks
- [x] Create logic that uses the `onHeaderClick` prop of the table to sort on whatever header is clicked in either Ascending or Descending order
- [x] Ensure that the logic toggles between ascending and descending sort when clicked multiple times
- [x] Test the newly implemented sorting functions

## Acceptance Criteria
- [x] Columns on the view payments feature is behaving as expected and a PR has been requested for merging
  - [x] Column headers are able to sort in ascending order
  - [x] Column headers are able to sort in descending order
  - [x] When one column header is selected other arrows are not shown
  - [x] The column that is selected has the corresponding arrow shown next to it
  - [x] When a table gets reset, the user is taken back to page 1
