### ISSUE TITLE
Write Unit Tests for Redux on View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#10696]
## Goal
The Redux implementation we have added to View Payments needs to be unit tested to ensure it works as intended. 

## Tasks
- [ ] Adjust data structure per BE
- [ ] ~Write and conduct unit tests that cover ascending sorting~
- [ ] ~Write and conduct unit tests that cover descending sorting~
- [ ] Write and conduct unit tests that cover pagination
- [ ] Write and conduct unit tests that cover the reducers in the Redux code.

## Acceptance Criteria
- [ ] ~The unit tests for ascending sorting are complete~
- [ ] ~The unit tests for descending sorting are complete~
- [ ] The unit tests for pagination are complete
- [ ] The unit tests for Redux reducers are complete
