### ISSUE TITLE
"Community care providers" disappears from the "Choose a VA facility type" drop down

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10698]
## What happened?
<details>
 <summary>"Community care providers" disappears from the "Choose a VA facility type" drop down </summary>

![image (38).png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/99fe868e-abf5-498c-b46d-456f2ea43077)

</details>

This is intermittent and will be difficult to replicate. It resolves on its own, without changing browsers. It may or may not be resolved by refreshing the page. 

Could be related to Flipper logic (nodes request Flipper status every three minutes). Logs show Flippers sometimes fail. We display this optionally but it is always on. 

We'd prefer to keep CCare on flipper due to data issue which sometimes arise. 

## Tasks
- [x] Get logs for VSP to demonstrate flipper failure
- [x] Create new flipper with correct labels (Change Flipper to "suppress" community care (rather than enabling it) and leave it off.)
- [x] Remove old Flipper
- [x] Front end change 
- [x] Flipper should be set to "off" 

## Specs:
- Browser: has been observed in Chrome and IE

## Desired behavior
<details>
 <summary> "Community care providers" is present in the "Choose a VA facility type" drop down </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/4cc811d3-91f4-4ac7-84be-9d70aaa3da2d)

</details>

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
@mpelzsherman - I am going to start working on this one.

**Comment by brangi** [comment]
merged
