### ISSUE TITLE
Adjust the Mobile Card View of Tables on "View Payments"

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#10694]
## Goal
When we originally built the View Payments page it was ahead of design finishing the mobile mockups of the page. We have received a set of updates for the mobile mockups and although they are not the finished state for the mobile view of the page we can make some of those updates to get the page closer to what it's end state on mobile will be.

## Tasks
- Adjust the payment view table per feedback from Design System Council
  - [x] Add horizontal rules between rows on mobile
  - [x] Uncap data labels
  - [x] Adjust padding for less space
  - [x] Adjust alignment for right alignment

## Acceptance criteria
- [x] Dividing lines have been added between table rows on mobile
- [x] Labels for the data have been adjusted so that they are not in all caps
- [x] Padding has been adjusted so that there is less space between the data on mobile
- [x] Alignment has been adjusted so that all text aside from numeric rows are right-aligned
