### ISSUE TITLE
[ENGINEER] Create and/or Clone nodes outside of Menu for VA Cheyenne System and associate all facility pages [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10701]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Clonable Website](prod.cms.va.gov)

## Tasks
_Creation of the following Drupal types and pages_
* Next Section: Items not in Menu
- [x] Make an Appointment (Clone from Erie VA health care)
- [x] Register-for-Care (Clone from Erie VA health care)
- [x] Billing-insurance (Clone from Erie VA health care)
- [x] DAV-vans (Clone from Erie VA health care)
- [x] Medical-records-office (Clone from Erie VA health care)
- [x] Operating-status (Clone from Erie VA health care)
- [x] Pharmacy (Clone from Erie VA health care)
* Next Section: Caregiver
- [x] Caregiver-support (Clone from Erie VA health care)
- [x] Homeless-veteran-care (Clone from Erie VA health care)
- [x] LGBT-veteran-care (Clone from Erie VA health care)
- [x] Mental-health-care (Clone from Erie VA health care)
- [x] Minority-veteran-care (Clone from Erie VA health care)
- [x] Patient-advocates (Clone from Erie VA health care)
- [x] Returning-service-member (Clone from Erie VA health care)
- [x] Suicide-prevention (Clone from Erie VA health care)
- [x] Women-veteran-care (Clone from Erie VA health care)
* Next Section:
- [x] Campus Map (Clone from Erie VA health care)
- [x] Champlain Services (Clone from Erie VA health care)

## Acceptance Criteria
- [x] Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [x] Validate that pages are read to take data load information
- [x]  All system pages listed above have been created
