### ISSUE TITLE
RD: Review usability of the current lists & calculations

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1070]
### Tasks
- Establish a baseline for current layout of features

### Considerations
- How can we apply best practices?  
- Are those best practices predetermined?
- What do we estimate the ease of integration to be?

### Definition of Done
- [x] Estimate the current page for complexities (1, 2, 3, 5, 8 ->too complex?)
  - [x] Document any high level thoughts

### Notes
- What did we learn?
- How did we get to this page?
- How was navigation within the page?
- [ ] Any notes for the Call Center should be uploaded to `feature/$feature-name/call-center` in GitHub

**Comment by arickalewis1** [comment]
![eBenefits VA Touchpoints](https://user-images.githubusercontent.com/54509359/65444731-46bd1180-ddf6-11e9-93ec-8a5858b42fa5.png)

I'm considering the workflow of viewing pending claims (that lead to the Claim Status tool) from the Rated Disabilities page. Attached is the current workflow to view Rated Disabilities compared with a proposed workflow that somewhat mimics the eBenefits workflow on VA.gov.
