### ISSUE TITLE
Coronavirus chatbot: Week of 6.29.20 updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10704]
# User story
As a Veteran or family member, I need the latest information about how the coronavirus may impact my VA health care and benefit services. As a Veteran with low or no vision, I need phone numbers to be coded in a way that makes them accessible.

## Issue Description
We need to update the chatbot with newly approved content from the VA.gov coronavirus FAQs.
- 6.29.20: Add new VGLI extension question

---
# Details

## Tasks
- [x] Update chatbot messages with new/updated FAQs (Danielle)
- [x] Update chatbot copy doc with new FAQs (Danielle)
- [x] Update draw.io decision tree with new FAQs (Danielle)
- [x] Review messages and copy doc for errors (Randi)
- [x] Communicate handoff to dev team (Danielle)
- [x] Validate in staging
- [x] Validate on live site

## Acceptance Criteria
- [x] Content validated on live site

## Documentation for reference

- PR for review: https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/274
- Latest FAQs: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/
- Phone number guidance in content style guide: https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
