### ISSUE TITLE
[Development] 526: Nicely Prevent Users with Invalid Military History Dates

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#10703]
## Issue Description
The 526 form should not allow users to enter military history service end dates that are greater than 89 days from now. This is because if the date is between 90 and 180 days from now, the user should fill out a BDD form. If the date is greater than 180 days out, the user is unable to fill out either form. 

Currently, if the user enters any date in the future for military history service end date, the form will present the user with several warnings including one alert that says the user cannot fill out the form, but still allows the user to hit the continue button and completely fill out the form. See #10405 for more details on the messages. 

As explained in [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10405#issuecomment-650278930) comment, most of the messaging can be removed. The page that needs to stay and be adjusted is this:

![image](https://user-images.githubusercontent.com/53942725/86003263-8a752500-b9df-11ea-9071-93d7dc36e68d.png)

This page is the next page that appears after the user enters a military history service end date in the future. As explained in the comment, this question should be required. If the user selects no, we route them back to the military history page, as we do now. If the user selects yes, depending on when the future date entered is, we either show an alert to link the user to BDD or we show an alert explaining that the user cannot fill out the 526 form. Whatever the case, we do not let the user continue the form. 

After deploying this change, the back end should no longer receive consistent upstream EVSS errors related to service end dates in the future without a separation location.

## Tasks
- [ ] Remove unnecessary alert pages/add them to single Yes/no page (this includes removing the alert on the actual military history page that conditionally appears, see linked ticket for issues with this alert)
- [ ] Do not allow users to continue the 526 form if one of their military history service end dates is in the future
- [ ] Direct users to the BDD form who enter a date 90 to 180 days from now (staging for now)

## Acceptance Criteria
- [ ] Users are properly alerted and cannot continue the 526 form if one of their military history service end dates is in the future
