### ISSUE TITLE
[Content] HLR: Content review of contestable issue endpoint responses

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10713]
## Issue Description

We need content review for the Higher-Level Review introduction page. We made it show messages to the user concerning the get contestable issues API endpoint:

- When the API endpoint is unavailable, we need to show a message to the user that they will need to try again later

  <details><summary>Click to see error mock up example</summary>

  
  ![HLR-get-contestable-issue-error](https://user-images.githubusercontent.com/136959/86028948-2c087080-b9f8-11ea-8294-04220ee514ed.png)</details>
- When the API returns an empty list of contestable issues, we need to inform the user that they are not able to proceed; And maybe add a link or more information about what comprises a contestable issue.

  <details><summary>Click to see message about the user not having any contestable issues</summary>

  
  ![HLR-no-contestable-issues](https://user-images.githubusercontent.com/136959/86029137-683bd100-b9f8-11ea-9280-6ab12a1a6ef1.png)</details>

## Tasks

- [ ] Update network error alert content
- [ ] Update no contestable issues message content

## Acceptance Criteria

- [ ] Content has been reviewed & changed shared

**Comment by luke-gcio** [comment]
@peggygannon are you ok with us putting it into the current sprint (starting today July 1)?

**Comment by peggygannon** [comment]
@luke-gcio Yes, i can slot this into this sprint.

**Comment by luke-gcio** [comment]
Hi Peggy - is this still on your radar for this sprint?

**Comment by peggygannon** [comment]
hi, @luke-gcio Yes, I'm working on these alerts today.

**Comment by peggygannon** [comment]
hello, @luke-gcio Here are updated error messages and one clarifying question about the second message:

For the second message: What is the next step we want to give the user? I want to write to the message so the users has a next step.
Should we have them call VA benefits or  is there a page we can send users to to learn about what comprises a contestable issue.

1. API endpoint is unavailable

**We can’t load your contestable issues**
We’re sorry. We’re having some connection issues on our end. Please refresh this page to try again.  

2. API returns an empty list of contestable issues

**We don't  have any contestable issues for you**
Our records show that you don’t have any issues eligible for a Higher Level Review. If you think this is an error, please call..... OR give users a link to learn more...

**Comment by Mottie** [comment]
@peggygannon I'm included screenshots in the pull request - https://github.com/department-of-veterans-affairs/vets-website/pull/13501

- The unavailable endpoint error includes the actual error message between the two sentences.
- The empty contestable issues alert includes the telephone & an additional info dropdown (copied from the contestable issues page) with more info, since there isn't a specific page that neither Kevin nor I could find with that information.

**Comment by peggygannon** [comment]
thank you @Mottie I'll be taking a look at these today!

**Comment by Mottie** [comment]
I'm not sure why this was closed... we only recently received the feedback, which is now incorporated into this design - https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/429218501_Signed_In_-_File_An_HLR_-_No_Contested_Issues_Found

**Comment by Mottie** [comment]
Sadly, this work can't be tested on staging yet... the backend isn't in sync with the frontend. We're waiting on an update before they work smoothly together.

**Comment by peggygannon** [comment]
@Mottie ok, thank you for the update. Please let me know when ready to validate in staging.

**Comment by luke-gcio** [comment]
@peggygannon @Mottie we are ready for you to validate on staging!

**Comment by peggygannon** [comment]
@luke-gcio OK, thank you. I'm trying to find a link to take me to these errors. Is there a staging link or a certain test user that will allow me to view these?

**Comment by Mottie** [comment]
URL: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction
Test users: https://dsva.slack.com/archives/C5AGLBNRK/p1601069567024300

**Comment by peggygannon** [comment]
Hi,@mottie, thank you.. Looks good.

**Comment by luke-gcio** [comment]
Hi @peggygannon are you saying this is good to go on our end?

**Comment by peggygannon** [comment]
Hi, @luke-gcio yes, look good.. thanks for checking back!
