### ISSUE TITLE
Update question language per latest CDC language

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10719]
## Issue Description
We're updating question language per latest CDC language:

- Adding "or difficulty breathing" to cough/shortness of breath question
- Adding new symptoms/reordering to match CDC in past 3 days symptoms question
- Removing "sore throat" from current symptoms questions (since it's already covered in past 3 days symptoms question)

---
## Tasks
- [x] Update content in json file and create PR
- [ ] Review/merge PR request

## Acceptance Criteria
- [ ] Screening tool updated with revised question content

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mchelen-gov @stephenBarrs Added you as reviewers on this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13305. Just let me know if you have any questions. Thanks!

FYSA @batemapf

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf Word doc with tracked changes/comments
[VA.gov_COVID-19 screening tool 6.29.20](https://app.zenhub.com/files/133843125/3c50c66f-aabd-4348-ad8e-548d37e30716/download)
