### ISSUE TITLE
Create cloned 2018 historic rates for DIC - parents 

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10718]
# Issue description:
In order to retire legacy pages with historic DIC rates for parents, we need to clone our current rates pages in Drupal and input the 2018 rates information.

# Tasks:
- [x] Clone current DIC rates - parents rates page in Drupal. Anne
- [x] Copy over rates from legacy historic page, https://benefits.va.gov/PENSION/rates_parents_DIC_pen17.asp - Anne 
- [x] Copy edit and doublecheck rates and new math examples. Randi

Epic: #10435
Preview:
 http://preview-prod.vfs.va.gov/preview?nodeId=6266

# Acceptance criteria:

- [x] Pages cloned, numbers checked and reviewed

**Comment by AnneHurley** [comment]
@bethpottsVADEPO  - if you have some time today/tomorrow I wanted to doublecheck the rates. We changed how we group the income limits in the va.gov page. In every accordion group after the first one, we have the same rate for 2 different income levels. 
![image.png](https://images.zenhubusercontent.com/5c6313e20f871b64caae9909/6e91c0a6-c46d-4e80-9661-fa11c7f0ce14)

**Comment by bethpottsVADEPO** [comment]
@AnneHurley Here's the problem...

@DanielleSoCompany and I tracked this back in the revision history. You were asked by the SME to change the accordions from starting with, for example, $1,901 to starting with $1,900.
You did this. However, you updated only the income limit, and not the corresponding rate. (That second column needed updating too, not just the first column)
$1,901 rate = $2,000 rate because $1,901 is below $2,000 but above $1,900.
$1,899 rate = $1,900 rate because $1,899 is below $1,900 but above $1,800.
So with the changed accordions, the rate in the last row of each table is the same as the rate in the first row of the next table.
$1,899 rate = $575
$1,900 rate = $575
We need to fix this asap, as we currently have the wrong rates for the first row in each table.

![image](https://user-images.githubusercontent.com/66026798/87176047-5d9df900-c28e-11ea-88d8-c95925775850.png)

**Comment by AnneHurley** [comment]
@bethpottsVADEPO  I will make these fixes. FYI @peggygannon reviewed the changed charts, and Angie Smith approved them as they are now. I agree that ^ makes sense however.
@RLHecht  FYSA

**Comment by RLHecht** [comment]
DIC rates strikes again! This was a months-long bear of a ticket @AnneHurley and I both worked on. Very sorry that I missed fixing this figure when we adjusted the accordions. Anne, let me know when you have the new numbers in and we can hopefully get this published before today's deploy.

**Comment by AnneHurley** [comment]
@RLHecht New numbers in the top row are in the 2020 page. They repeat the last numbers in the previous accordions. 
@bethpottsVADEPO @DanielleThierryUSDSVA 
Preview:  http://preview-prod.vfs.va.gov/preview?nodeId=1012

**Comment by RLHecht** [comment]
These changes have been reviewed and the page published. Do we need to capture this in a separate 2020 DIC rates ticket or OK to keep here?

**Comment by AnneHurley** [comment]
@RLHecht  - was going to ask that myself - @bethpottsVADEPO  OK to keep the 2020 page updates in this ticket?

**Comment by bethpottsVADEPO** [comment]
@RLHecht Would you create a new issue for that 2020 work? Thank you.

**Comment by RLHecht** [comment]
@AnneHurley I updated the info in this ticket above to reflect that the work is complete once we've reviewed the numbers. All the work to get SME approval and publish is now captured in ticket #11171. Can you remind me if you and I went over these numbers together? I think I only looked at the 2020 page with you so we still need to check these numbers. FYSA @MickinSahni

**Comment by AnneHurley** [comment]
@RLHecht This is the last 2018 rate table I am creating, today. Will let you know as soon as it's done. FYSA @MickinSahni

**Comment by RLHecht** [comment]
This math has been checked and updated. FYSA @MickinSahni
