### ISSUE TITLE
Create cloned 2018 historic rates page for DIC - spouse and children

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10717]
# Issue description
In order to retire legacy pages with historic DIC rates, we need to clone our current rates pages in Drupal and input the 2018 rates information.

# Tasks:
- [x] Clone current Disability - DIC rates for spouses and children rates page in Drupal. Anne
- [x] Copy over rates from legacy historic page, Anne ***NOTE question about child rate at top of page***
https://www.benefits.va.gov/COMPENSATION/rates_DIC_pen17.asp. Anne
- [x] Copy edit and doublecheck rates and new math examples. Randi
- [x] Review rates tables to decide whether every table needs its own "All rates in $US dollars" so we need to decide if they should. Beth *NOTE* This decision will apply to 2020 page and to 2019 historical rates page

Attached to epic: #10435
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=6203

# Acceptance criteria:
- [x]  Page cloned, numbers checked and reviewed - Anne, Randi

**Comment by AnneHurley** [comment]
@RLHecht  This is ready for copyedit. I'm happy to tag team on this as it's pretty dense. I also want to understand where the "after January 1003 / child with no surviving spouse" rate comes from on the legacy page. Maybe we can quickly sort it together. 
@bethpottsVADEPO  FYSA

**Comment by RLHecht** [comment]
This has now been copyedited and the numbers checked with Anne, though we are waiting for confirmation on one figure, which is noted above. FYSA @bethpottsVADEPO @AnneHurley

**Comment by bethpottsVADEPO** [comment]
@AnneHurley I'm not understanding which "child with no surviving spouse" rate you have a question about. Where is that? Can you drop a screen shot here? Thanks!

**Comment by bethpottsVADEPO** [comment]
@AnneHurley Please add the drupal preview link to all the tickets, maybe under the list of tasks where it says what epic this is attached to. Thanks!

**Comment by AnneHurley** [comment]
@bethpottsVADEPO Re your first question above, yes - attached is the email of screenshots I sent you yesterday. Let me know if anything is unclear.
And yes I'll add all preview links - have been waiting until we have last questions ironed out. I will add them but just note that not all copy may yet be finalized.
[Email to Beth - DIC rates question.docx]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4897834/Email.to.Beth.-.DIC.rates.question.docx)

**Comment by bethpottsVADEPO** [comment]
![image.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/4a16f161-bd31-4f93-97f1-9e7f826ae104)

**Comment by RLHecht** [comment]
@AnneHurley I've updated this ticket to reflect that work is completed when we've input the new numbers and reviewed the page. Once the last item above is done (deciding if all tables need the US dollars info) we can close it out. I've captured the work for SME approval and publishing in ticket #11171 FYSA @MickinSahni

**Comment by RLHecht** [comment]
@bethpottsVADEPO I've updated all the charts with our new way of writing "in U.S. $). I also restyled the historic rates links at the bottom for consistency. This ticket can now be closed and we can use #11171 for sharing with SMEs and publishing. FYSA @MickinSahni
