### ISSUE TITLE
[Front End] DL - Download letters from eFolders 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10720]
## User Story 
_As a veteran who is viewing my debts as were communicated in the debt letter(s) and on the summary page, I would like the ability to download the debt letters in .pdf as provided in the 'download' link. Due to potential constraint on vbms - all the letters will be listed on a page in reverse chronological order. 

---
## Tasks
- [ ] _connect to vbms endpoint 
- [ ] _download letter as provided in the link on FE page 

## Acceptance Criteria
- [ ] _For a test user with one debt but >1 letter ability to download all letters
- [ ] _For a test user with >1 debt and >1 letter for each debt ability to download all letters 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
Brad, the requirements here have changed. All the debt letters will be listed out in chronological order - ticket updated.
