### ISSUE TITLE
Project Kickoff: Campaign Landing Page (Template)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#10739]
## Steps to complete Project Kickoff
- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Product Outline  is [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates#campaign-landing-page-template-mvp-10---product-outline).
- Explanation of the problem space:

**Problem statement**
Many benefit-adjacent tier 2 content are not support/learning/help, product, or evergreen office (administrative) content. Some tier 2 content are more similar to marketing or engagement content.
- It may also have audiences other than Veterans (for example: local governments, Congress, VSOs, medical researchers).
- It may also be time based in nature, like a particular campaign (#BeThere) or a new legislation change (MISSION Act).
This category of tier 2 content could be better served as a campaign landing page.

**Purpose**
The purpose of this template is to enable an easy way for PW content team and VA businesses to create and manage this type of content in campaign landing page template in the new CMS, Drupal.

- Any other artifacts you have so far
  - Super Epic, with detailed designs is [here](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4621) {Note: **The Design Intent step has been completed!**}
  - Note: The CMS team led by @kevwalsh has conducted a preliminary review/LOE of the requirements

- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Mickin Sahni @MickinSahni **
- DEPO Product Lead (required): **John Hashimoto @johnhashva **
- Entire VFS team (recommended): **names**

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** No, it is a self-contained new Drupal/CMS template that will be used by VA business stakeholders.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

**Comment by meganhkelley** [comment]
Hi @johnhashva just let me know when you are ready for us to schedule this! Thanks :)

**Comment by johnhashva** [comment]
@meganhkelley have two options for this so welcome your input here:

- Option 1: Schedule a "everyone involved" project kickoff, including the key players from Platform/Collab Cycle.  
OR
- Option 2: Schedule a smaller session for Platform/Collab Cycle -- and separate one for the implementation team -- CMS, Public Websites.

In both cases, next week looks more feasible for scheduling at this point (lots of folk OOO by Thursday).

Thoughts?

**Comment by meganhkelley** [comment]
Per conversations in Slack, we scheduled a Campaign Landing Pages "regroup" for 7/8 @ 10:30 AM
