### ISSUE TITLE
Debt Letters Notifications - eMail | texts 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10738]
## High Level User Story/ies
As a veteran who has incurred debt with the VA and has received a debt letter, I would like to be notified by email, text or both that I have an outstanding debt and where to go on va.gov to get additional details 

## Hypothesis or Bet

Letters are often ignored and thrown away and do not provide the kind of information a veteran may require to understand next steps, or status of their debt. Also, the veterans are a mobile population and may have never received the letters if the va does not have the correct address on file. The hypothesis is if a veteran receives email and/or texts the veteran can get additional information on va.gov and take action on their debt 
## OKR
_Increase traffic to va.gov where the veteran can take action
Decrease the amount of debt that is written off which effects veteran's credit negatively  

## Definition of done
- [ ] The veteran is notified by email and/or text of a debt AFTER they should have received the debt letter 
- [ ] Design for email template 
- [ ] The email and/or text is written in plain language and is empathetic to the veteran
- [ ] Notification method captures bounce-back, unreachable states (bad email, bad cell number) 
- [ ] Notification contains the correct link to take veteran to landing/log in page 
- [ ] 508 accessibility considerations for text/email 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
