### ISSUE TITLE
[PM] Logged-in homepage: Metrics conversation with disability ratings team

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10745]
## Background

As we started setting OKRs & KPIs (#9181) for the logged-in homepage work, we realized we needed to align our success metrics with the teams that own the tools we will be featuring. Our KRs /success/conversion metrics should reflect what they consider to be most important about their tools.

## Tasks

- [x] Regroup with Steve and Jason about disability ratings tools.
- [x] [Document notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/meeting-notes/7.7.20%20metrics%20chat%20about%20disability%20rating.md).

## Acceptance criteria

- [x] We have an idea of next steps for disability rating related metrics.
