### ISSUE TITLE
Identify and Support all BGS Unsupported Workflows

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10742]
## Background
Currently, we fire all VNP calls for all workflows. After speaking to BGS, it was brought to our attention that this is sub-optimal.  

## Considerations
Per Linda, these are "new" sections:
- Section VIII: Veteran/Claimant Reporting a SchoolChild Over 18 Has Stopped Attending School  and,
- Section VI:  Veteran/Claimant Reporting Death of a Dependent

## Description
- If **Removing a (step-?) child due to death** is requested, we need to skip VNP calls and run `insertBenefitClaim`
- If **Child is leaving school early** is requested, we need to skip VNP calls and run `insertBenefitClaim`

## Tasks
- [x] Ensure we fire the proper calls for these workflows.  

## Acceptance Criteria
- [x] Calls have been addressed and updated to handle unsupported workflows (**Removing a (step-?) child due to death**)
- [x] Calls have been addressed and updated to handle unsupported workflows (**Child is leaving school early**)

**Comment by digitaldrk** [comment]
I can't find code that supports `SchoolChild Over 18 Has Stopped Attending School`

Skipped code for child death
