### ISSUE TITLE
[PM] Logged-in homepage: Metrics conversation with VAOS team

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10740]
## Background

As we started setting OKRs & KPIs (#9181) for the logged-in homepage work, we realized we needed to align our success metrics with the teams that own the tools we will be featuring. Our KRs /success/conversion metrics should reflect what they consider to be most important about their tools.

## Tasks

- [x] Regroup with Lauren and Lenae about VAOS and other healthcare tools.
- [x] [Document notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/meeting-notes/6.29.20%20metrics%20chat%20with%20VAOS%20team.md).

## Acceptance criteria

- [x] We have an idea of next steps for VAOS/health care related metrics.
