### ISSUE TITLE
Post-launch enhancements: MVP 1.0 Find a VA form search page and results

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10758]
**Related Epics:** [Find VA Forms Search - MVP](#1632) 

### Post-launch enhancements: MVP 1.0 Find a VA form search page and results

The modern forms search has launched. But there are some forms search updates that are currently blocked until the search functionality cuts over from the API web scrape to the Drupal forms meta data. (For example: Updating the results display design to include the new custom fields once search switches to pull from the Drupal form meta data instead of the web scrape.) 

This epic is to organize those MVP post-launch iterations until the full MVP 1.0 experience of the search and form detail pages with custom data fields are both fully launched. 

**Acceptance criteria:** 

- [ ] Forms search page has completed [post-launch 508 test, per ticket 8694](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8694). 
- [x] Forms search results can display the custom data fields from Drupal. (Screenshot below.)
- [ ] Accessibility bugs are fixed. 
- [ ] Backlog items are completed.

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/8c95bc61-b6eb-459e-9a5e-aeab309fcc5e)

**Reference:** 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/design/VA-Form-search-landing-results.pdf

**Please note:** 
"Revision date" field is now "Form last updated:" and shows the most recently modified form date. 

### Tickets to create 
- [x] Iterate search results to handle new available fields - #11453
- [x] Updating to our public API route to document the new properties
- [x] updates to service to consume deleted info

**Comment by jenniferlee-dsva** [comment]
@MickinSahni - Added details for the second checkbox in original description above. ^  I tried to move this to backlog but can't seem to do that without affecting the 'epic' flag. 

I think we can work on this after Lighthouse team makes the change swtiching over to pulling from Drupal (instead of web scrape). Per Andrew, they'll start work Monday, July 13, and take about a week, per this thread: https://dsva.slack.com/archives/CUB5X5MGF/p1594394779439800

**Comment by jenniferlee-dsva** [comment]
Adding @johnhashva - as his new search products team may use some or all of these post-launch tasks as onboarding activities. John, wrt any items needing content review, please work directly with me. I've been trying to not overburden the content team and just send very close to final things for a final, easy check with them. There are also numerous backend things that drive a lot of the FE, including content, and they're not fully aware of all the many  CMS, API, and FE logic that impacts design and copy.

**Comment by MickinSahni** [comment]
Swapping team labels

**Comment by jenniferlee-dsva** [comment]
@johnhashva new team is taking these post-launch activities to onboard new FE and forms PM.

**Comment by brianalloyd** [comment]
@MarciMcGuireGCIO looping you in the post-launch enhancements for Find a VA form MVP 1.0.

**Comment by jenniferlee-dsva** [comment]
Not sure why, but I can't add this ticket to the new product label: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15241  < -- fysa @MarciMcGuireGCIO @johnhashva

**Comment by denisecoveyduc** [comment]
@jenniferlee-dsva I just removed the earch and discovery label and added the decision tool label to the above- #15241  

@johnhashva can we remove the search and discovery label from this one? Assuming @MarciMcGuireGCIO will pick it up.

**Comment by MarciMcGuireGCIO** [comment]
Outstanding VA accessibility review and 508 issues have been captured in separate tickets.  Closing this Epic.
