### ISSUE TITLE
SSO/Login: Implement final content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10756]
## Issue Description

Implement final content.

---
## Tasks
- [x] Implement content changes (Kelson)
- [x] Validate content changes in staging against final Word docs (Randi, Danielle)
- [ ] Validate content changes in prod against final Word docs  (Randi)

## Acceptance Criteria
- [ ] Final content live in production

---
### For the authenticated content

- **Changes to content in on-page text (changes highlighted in blue):** [SSO_authenticated.content_for.implementation_7.28.20](https://app.zenhub.com/files/133843125/45c4021d-25bb-4738-8f82-51618e11a6e1/download)
- **Content within the alert boxes:** https://vsateams.invisionapp.com/share/4XY0MRMVE56#/screens

Note: On the schedule appointments screen (https://vsateams.invisionapp.com/share/4XY0MRMVE56#/screens/425317822/), the 2nd button should change from "Use My HealtheVet for appointments" to "Use the VA appointments tool"

### For unauthenticated content

Changes highlighted in blue: [SSO_UNauthenticated.content_final for implementation_7.28.20](https://app.zenhub.com/files/133843125/06e8d94f-34ac-4c5a-b52f-8da034024971/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic. Here are the documents for implementing content review changes. Let me know if it would be helpful to have a call to walk through these before you start. Thanks!

### For the authenticated content

- **Changes to content in on-page text (changes highlighted in blue):** [SSO_authenticated.content_for.implementation_7.28.20](https://app.zenhub.com/files/133843125/45c4021d-25bb-4738-8f82-51618e11a6e1/download)
- **Content within the alert boxes:** https://vsateams.invisionapp.com/share/4XY0MRMVE56#/screens

Note: On the schedule appointments screen (https://vsateams.invisionapp.com/share/4XY0MRMVE56#/screens/425317822/), the 2nd button should change from "Use My HealtheVet for appointments" to "Use the VA appointments tool"

### For unauthenticated content

Changes highlighted in blue: [SSO_UNauthenticated.content_final for implementation_7.28.20](https://app.zenhub.com/files/133843125/06e8d94f-34ac-4c5a-b52f-8da034024971/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni Content review complete so this is now unblocked. Thanks!

**Comment by kelsonic** [comment]
Awesome! Thanks @DanielleThierryUSDSVA! 🎉

**Comment by kelsonic** [comment]
Bumping to a 5 due to 1) amount of content changes and 2) format of content changes since we have to convert from Word doc to React code, should probably brainstorm ways to optimize the format for easier implementation in the future 🙂

**Comment by kelsonic** [comment]
PR merged and ready for content validation on staging tomorrow following the daily deploy! CC @DanielleThierryUSDSVA @RLHecht

**Comment by RLHecht** [comment]
Kelson created ticket #12446 to track all the changes that need to be made. I've added all my comments in there. FYSA @DanielleThierryUSDSVA
