### ISSUE TITLE
[Development] HLR: Add e2e testing

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#10759]
## Issue Description

Add Cypress e2e tests for the Higher-Level Review form in anticipation of the form going into production. End-to-end tests only run on production-available pages, so once complete these tests will be disabled until HLR is available in production.

## Tasks

- [ ] Implement HLR e2e testing

## Acceptance Criteria

- [ ] Cypress e2e tests all passing in a local environment
- [ ] Cypress e2e tests are disabled once merged, until the form is available in production
