### ISSUE TITLE
[Drupal] Facility Health service address content modeling

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10751]
##  Description
How can we standardize Facility Health service address content and make it a reusable component?

## Tasks
- Create content model/format for the address content within Location and contact information area of VAMC facility health services.
- Work with CMS team to determine format for street address, number/order of lines and labels for use in new content model
- Get data input from VAMC-upgrade team

## Acceptance Criteria
- [ ] Facility Health service address schema is available in Drupal Prod

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
