### ISSUE TITLE
SSO/Login: Finalize VA.gov health tools content for implementation

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10757]
## Issue Description

Finalize content for implementation.

---
## Tasks
- [ ] Finalize alignment with Peggy (Danielle)
- [ ] Review content with Lauren (Danielle)
- [ ] Get My VA Health contact info from Cerner (Danielle)
- [ ] Finalize approach to handling facility vs. system names in authenticated content (Danielle with @kelsonic and team)
- [ ] Finalize content based on Lauren's review and info above (Danielle)
- [ ] Final copy edit (Randi)

## Acceptance Criteria
- [ ] Final content handed off to @kelsonic for implementation in issue #10756

---
## Documentation

[will add final content docs here when ready]

**Comment by DanielleThierryUSDSVA** [comment]
Duplicate ticket - closing
