### ISSUE TITLE
SSO/Login: VA.gov health pages unauthenticated content review

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10755]
## Issue Description

Review content and provide edits to Peggy for alignment.

---
## Tasks
- [x] Danielle to review content and provide tracked edits
- [x] Danielle to share questions with Peggy to ensure content alignment
- [x] Randi to copy edit
- [x] Danielle to add html
- [x] Danielle to hand off to Kelson

## Acceptance Criteria
- [x] Content changes handed off to Kelson

---
## Documentation

Desktop Invision: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409123884_Unauthenticated_Pages

Mobile Invision: https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/409260607_M-Authenticated_Pages_-_Alerts

Usability testing summary: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/alerts/research-summary.md

Usability discussion guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/alerts/discussion-guide.md

Product Outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/sso

Handoff document: https://docs.google.com/document/d/11OGKfLk0fKd08pqCKT0Wvrt9ze2vZW_PSEn2kJdK714/edit#

---

**Comment by DanielleThierryUSDSVA** [comment]
@MickinSahni Same as authenticated content ticket, this will need to carry over into next sprint. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here's the document for your review. I'm tracking and highlighting all changes to help Kelson see them easily for implementation. Feel free to slack me with any questions. Thank you!
[SSO content review_UNauthenticated content_for implementation_7.21.20](https://app.zenhub.com/files/133843125/00495ea5-526b-43c9-9649-7a9a4bf3e2e6/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here is the document with my edits. I had one question but the rest were small tweaks.
[SSO content review_UNauthenticated content_for implementation_7.21.20-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4960361/SSO.content.review_UNauthenticated.content_for.implementation_7.21.20-RH-edit.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic. Here are the changes for the **un**authenticated state of the Cerner content.

Couple of notes:

- Changes are highlighted in blue
- I've added the html for changed content so it's easy to pick up _(note: I didn't add html for other content that's not changing)_

If you have any questions while implementing this, please of course feel free to reach out anytime. Thank you!

[SSO_UNauthenticated.content_final for implementation_7.22.20](https://app.zenhub.com/files/133843125/83645de3-f36d-4eb5-8a49-26d302c7e7d3/download)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @MickinSahni
