### ISSUE TITLE
Agent Orange consolidation: Implement content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10765]
**Related ticket: [Agent Orange consolidation: Socialize with SMEs #10862](#10862)**

## Issue Description
We need to implement the Agent Orange consolidation strategy.

This will involve:

- Updating the existing main Agent Orange page within the Disability Benefits hub, eligibility section

Drupal Node ID: preview-prod-vfs.va.gov/preview?nodeId=874

---
## Tasks

- [x] Post finalized content in this issue (Danielle)
- [x] Flow content into this page in Drupal and save as **draft**: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/ (Laura
- [x] Ensure Drupal page matches Word doc and do final copy edit (Randi)

**Save as draft: We won't publish until approved by SMEs.**

## Acceptance Criteria
- [x] Consolidated content is in Drupal and saved as draft, ready for SME review

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This is the content that needs to be flowed into the existing Agent Orange page. Could you work with a content writer to implement this and then also give it a final copy edit? I'd had Beth look it over, but then I made some updates so want to make sure I didn't introduce any errors. Thank you!

[Agent Orange for implementation](https://app.zenhub.com/files/133843125/073cf4da-b7e5-45d6-8aa9-e417e9a1ea4a/download)

**Comment by RLHecht** [comment]
@lwalsh617 Here's the ticket I slacked you about. The Word doc is in Danielle's comment above and I've added the Node ID to the top of the ticket. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lwalsh617 @RLHecht. I realized I didn't update the TTY in this when I grabbed the copy to work with. Uploading version with that updated and highlighted in blue. Thanks![Agent Orange for implementation](https://app.zenhub.com/files/133843125/2fa7d90e-b6ce-4b51-901c-938cffb7e8ac/download)

**Comment by lwalsh617** [comment]
@RLHecht -- Here it is in Drupal:
http://preview-prod.vfs.va.gov/preview?nodeId=874

**Comment by RLHecht** [comment]
Thanks, @lwalsh617 @DanielleThierryUSDSVA I reviewed this as well and it's ready for next steps. Do you want to look at this before I close the ticket out?

**Comment by DanielleThierryUSDSVA** [comment]
I think we're good to close out. Thanks, @RLHecht and @lwalsh617!
