### ISSUE TITLE
Staging Review [Profile 2.0]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10764]
---
Name: Staging Review
About: Request a VSP staging review
Title: Staging Review [Profile 2.0]
Labels: product support, content-ia-team, collaboration-cycle, staging-review
Assignees: andreahewitt-odd, meganhkelley

---

## Steps to complete Staging Review: 

- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)
- [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md) 
- Access information for the Profile 2.0 in staging can be found in the va.gov-team-sensitive repo under products -> identity personalization

### QA
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/196)
    - [Coverage for References (Cases)](https://dsvavsp.testrail.io/index.php?/reports/view/122)
    - [Summary (Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/123)

**accessibility test cases**
Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.
  
    Required:
    - [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
    - [x] Conduct axe browser scan, and document or address issues found 
    - [x] Ensure end-to-end tests - including the axe check, pass 
    - [x] Check color pairing for proper contrast 
    - [x] Check for colorblindness issues 
    - [x] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
    - [x] Repeat for 300% 
    - [x] Repeat for 400% 
    - [x] Navigate all pages and core functionality with keyboard only 
    - [x] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox 
    
    

Known issues:
* [Screen reader & Axe browser check](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11273)
* []()
* []()
* []()
* []()

## Meeting attendees from **requesting team**
- Product Manager (required): **Matt Shea**
- DEPO product lead (required): **Samara Strauss**

## Scheduling
[x]  Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
[x]  Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
 - Monday August 3rd

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by mshea0606** [comment]
I'm still working on getting the artifacts for this

**Comment by meganhkelley** [comment]
Great @mshea0606 ! Just give us a shout when you're ready to schedule :)

**Comment by mshea0606** [comment]
thanks @meganhkelley! im putting together the following:

Link to product test cases/test plan in TestRail with test execution logs

Link to your Coverage for References and Summary(Defects) reports in TestRail for QA practice area review

Link to your accessibility test cases

**Comment by meganhkelley** [comment]
FYI @mshea0606 the staging review template has been updated since you created this and the accessibility instructions have changed (same requirements, updated documentation) — you can check that info out here if it helps https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md

**Comment by mshea0606** [comment]
@meganhkelley @andreahewitt-odd @tzelei I've submitted this ticket. @tzelei I've attached the use cases we discussed adding to test rail in a google document in this ticket. Please let me know if you have any questions or need additional information. Thanks!!

**Comment by mshea0606** [comment]
@meganhkelley @andreahewitt-odd we would like to schedule this review for next sprint if possible. Thanks!

**Comment by meganhkelley** [comment]
Scheduled

**Comment by jenstrickland** [comment]
@mshea0606 Hi Matt, thanks for pulling together the requirements. 

There's this one thing: "Link to your accessibility test cases"

I realize it looks like it's for Tze and QA, but this is really about accessibility. I recommend replacing those two bullet points with the following: 

```html
Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.
  
    Required:
    - [ ] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
    - [ ] Conduct axe browser scan, and document or address issues found 
    - [ ] Ensure end-to-end tests - including the axe check, pass 
    - [ ] Check color pairing for proper contrast 
    - [ ] Check for colorblindness issues 
    - [ ] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
    - [ ] Repeat for 300% 
    - [ ] Repeat for 400% 
    - [ ] Navigate all pages and core functionality with keyboard only 
    - [ ] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox 
    
    Recommended:
    - [ ] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) 
    - [ ] Add keyboard end-to-end tests in CI/CD test runs 
    - [ ] Conduct axe-coconut browser scan, document or address issues found 
    - [ ] Test with [WAVE tool](https://wave.webaim.org/) 


Known issues:

* []()

* []()

* []()
```
--------
More info: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-test-cases-checklist.md

**Comment by tlei123** [comment]
@pjhill , I've added TestRail test plan & report links above in the main Description.

NOTE: A few test-cases are currently blocked/untested \[see the yellow cells in my [QA test-cases Google Sheet](https://docs.google.com/spreadsheets/d/1XQiqBSol6BhQxnRpjuohblsNBLQx4SLDYbr9NJflCtM/edit?usp=sharing)].  Once @mshea0606 gets the answers to those yellow-cell "loose-ends," I'll run the remaining test-cases and generate final reports for you.

Feel free to ping me on Slack if you have further questions/issues.

Thx much!

**Comment by Samara-Strauss** [comment]
Done a while ago. Closing now.
