### ISSUE TITLE
Consider adding  "After you apply" consistently to hub pages

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#10773]
## Issue Description

Va.gov users visiting hub pages need to know that there's a tool for checking their claim/appeal status, and that, if they get a claim decision they disagree with, there's a course of action for them. 

As part of the work on [8276 Decision Review pages entry points](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8276), IA recommended that we consider adding an "after you apply" section to hub pages where it doesn't currently appear, so that: 
- We are consistent in having that content on all hub pages. 
- It could potentially house claim status tool and a link to decision reviews 

## Details
- [ ] _Review all pages where this section currently appears to ascertain its primary purpose, i.e., do we only add it when there is a "after you apply" page to link to, etc.
- [ ] _Consider whether "after you apply" effectively tees up a link to "decision reviews," or if it belongs elsewhere (where the context is "after you get a decision" rather than "after you apply")
 - [ ] _Consider: [Disability > DIC page] Decision review page and Claim status tool
For consistency across hubs, consider adding an "After you apply" content section that includes links to claim status and decision reviews
  - [ ] _Consider: How to Apply page. https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/
Location: - Add text and a link to claim and appeal status tool under the "What happens after I apply" section to be consistent with other similar content.
Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/
 - [ ] _Consider: How to Apply page. https://www.va.gov/pension/how-to-apply/
Location: - To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.
Label and link: Request a decision review or appeal https://www.va.gov/decision-reviews/ Copy: Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for careers and employment benefits, you can request a decision review. You can also manage any review requests or appeals you already filed.
 - [ ] _ Consider: https://www.va.gov/pension/aid-attendance-housebound/
Location: - - To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.
  - [ ] _Consider: https://www.va.gov/pension/survivors-pension/
Location: -To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.
- [ ] _ Consider: https://www.va.gov/housing-assistance/home-loans/how-to-apply/
Location: To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.
 - [ ] _ Consider: https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/
Location: To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.
 - [ ] _Consider: https://www.va.gov/burials-memorials/veterans-burial-allowance/
create an "after I apply" section that includes links to the decision review content and the claim status tool.
Label and link: Request a decision review or appeal https://www.va.gov/decision-reviews/ Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/
 - [ ] _Consider Life insurance detail pages
To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.

---
## Tasks
- [ ] _PW (Laura) writes up recommendations for each page (yes/no on whether to add "after you apply" and location for claim status tool and decision review links)
- [ ] _IA (Mikki) reviews recommendations
- [ ] _DEPO (Beth) reviews recommendations and provides feedback
- [ ] _PW (Laura)updates Drupal pages per Beth's feedback
- [ ] _PW (Randi) copy edits content
- [ ] _DEPO (Beth) reviews Drupal preview links and provides feedback to Laura, who makes any updates
- [ ] _DEPO (Beth) shares recommendations and Drupal preview links with SMEs, then provides SME feedback to PW 
- [ ] _PW (Laura) updates content in Drupal per SME feedback
- [ ] _PW (Randi) copy edits content 
- [ ] _DEPO (Beth) approves Drupal pages for publishing
- [ ] _PW (Randi) publishes pages 

---
## Acceptance Criteria
- [ ] _All relevant hub pages include content that:
- Shows users they can check claim status online anytime
- Assures users that if their claim is denied, they have a course of action

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by FranECross** [comment]
Will ask Jill about this one. It appears that it was moved to the product backlog in Benefit-Management tools a few months ago.

**Comment by mnorthuis** [comment]
This is really old direction.  Content has evolved since then and will continue to.  Closing issue.
