### ISSUE TITLE
Updating Eligibility h3 question to be consistent across all hubs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#10787]
## User story

As a content team member I need to ensure our content is consistent across all hubs.

## Issue Description
Currently we have different wordings for the H3 at the top of our eligibility section asking Veterans if they are eligible for specific benefits. We should be consistent with our language going forward as well as what is currently on the site. It should read as follows:

H3 Am I eligible for [X benefits]?
You may be eligible for [X benefits] if you meet [all/both/at least one] of the requirements listed below.

See example here: ![Screen Shot 2020-06-30 at 2.46.55 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/59ed7140-b16e-4626-9c14-f6446f243355)

## Tasks
Update published eligibility pages with the above wording (Selina).

- [x] Careers and employment 
- [x] Life insurance
- [x] Health care
- [x] Housing
- [x] Education
- [x] Disability
- [x] Burials and memorials
- [x] Pension
---
- [x] Review updated content (Randi)
- [x] Publish updated page (Randi)

## Acceptance Criteria
- [x] New copy appears on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
Spun off bug ticket #13480

**Comment by lunascoop** [comment]
I have updated the eligibility h3 question for the benefit hubs.

**Careers and employment**
- Eligibility for Veteran Readiness and Employment: http://preview-prod.vfs.va.gov/preview?nodeId=726
- Educational and Career Counseling (VA Chapter 36): http://preview-prod.vfs.va.gov/preview?nodeId=720 (no change needed)
- Get support for your Veteran-Owned Small Business: http://preview-prod.vfs.va.gov/preview?nodeId=722
- Employment benefits for dependent family members: http://preview-prod.vfs.va.gov/preview?nodeId=719
- VetSuccess on Campus (VSOC): http://preview-prod.vfs.va.gov/preview?nodeId=724
- Resources for military and Veteran family members: http://preview-prod.vfs.va.gov/preview?nodeId=721

**Life insurance**
- Servicemembers’ Group Life Insurance (SGLI): http://preview-prod.vfs.va.gov/preview?nodeId=767
- Family Servicemembers’ Group Life Insurance (FSGLI): http://preview-prod.vfs.va.gov/preview?nodeId=765
- Traumatic Injury Protection (TSGLI): http://preview-prod.vfs.va.gov/preview?nodeId=768
- Veterans’ Group Life Insurance (VGLI): http://preview-prod.vfs.va.gov/preview?nodeId=769
- Service-Disabled Veterans Life Insurance (S-DVI): http://preview-prod.vfs.va.gov/preview?nodeId=766
- Veterans’ Mortgage Life Insurance (VMLI): http://preview-prod.vfs.va.gov/preview?nodeId=770

**Health care**
- Eligibility for VA health care: http://preview-prod.vfs.va.gov/preview?nodeId=31
- VA Dental Insurance Program (VADIP): http://preview-prod.vfs.va.gov/preview?nodeId=491
- CHAMPVA benefits: http://preview-prod.vfs.va.gov/preview?nodeId=9
- The Program of Comprehensive Assistance for Family Caregivers (technically not health care hub): http://preview-prod.vfs.va.gov/preview?nodeId=10
- VA Prescription Refill and Tracking:* http://preview-prod.vfs.va.gov/preview?nodeId=27 technically not an h3, but made changes in draft mode
- VA Secure Messaging: * http://preview-prod.vfs.va.gov/preview?nodeId=38 technically not an h3, but made changes in draft mode
- Schedule and view VA appointments online:* http://preview-prod.vfs.va.gov/preview?nodeId=37 (content blocks seems to be within the react widget. Would need to reach out to Kelson or Nick if we wanted to update the eligibility language on this page.)
- View your VA lab and test results online: * http://preview-prod.vfs.va.gov/preview?nodeId=40 technically not an h3, but made changes in draft mode
- Order hearing aid batteries and accessories from VA: http://preview-prod.vfs.va.gov/preview?nodeId=36 
- Get your VA medical records online: * http://preview-prod.vfs.va.gov/preview?nodeId=33 technically not an h3, but made changes in draft mode

**Housing:** For the first page listed, the eligibility language template may not work. "Eligible" is kind of used back to back so it may sound off. Perhaps we can change it to its acronym (COE). I'll leave it to you to decide. Included a screenshot below.
- Eligibility requirements for VA home loan programs: http://preview-prod.vfs.va.gov/preview?nodeId=753
- Interest rate reduction refinance loan: http://preview-prod.vfs.va.gov/preview?nodeId=757
- Native American Direct Loan: http://preview-prod.vfs.va.gov/preview?nodeId=758
- Cash-out refinance loan: http://preview-prod.vfs.va.gov/preview?nodeId=756 (no change needed)
- Purchase loan: http://preview-prod.vfs.va.gov/preview?nodeId=759
- VA home loan programs for surviving spouses: http://preview-prod.vfs.va.gov/preview?nodeId=760
- VA help to avoid foreclosure: http://preview-prod.vfs.va.gov/preview?nodeId=761

<img width="756" alt="Screen Shot 2020-09-11 at 10 38 35 AM" src="https://user-images.githubusercontent.com/42546515/92938930-288f5d80-f41b-11ea-9044-6f38bdf88d9d.png">

**Education:** The first page listed below does not include an eligibility blue box (screenshot of current version below). I assume this is because the content required its own page, which is linked at the bottom of the section. I updated the blue eligibility box on the linked page (Post 9/11 GI Bill).

- GI Bill and other education benefit eligibility: http://preview-prod.vfs.va.gov/preview?nodeId=942
- Post 9/11 GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=935
- Yellow Ribbon Program: http://preview-prod.vfs.va.gov/preview?nodeId=936
- VA education benefits for survivors and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=984
- Fry Scholarships: http://preview-prod.vfs.va.gov/preview?nodeId=951
- Survivors’ and Dependents’ Educational Assistance: http://preview-prod.vfs.va.gov/preview?nodeId=950
- Edith Nourse Rogers STEM Scholarship: http://preview-prod.vfs.va.gov/preview?nodeId=6860
- Veterans technology education courses: http://preview-prod.vfs.va.gov/preview?nodeId=930 (no change needed)
- Montgomery GI Bill Active Duty (MGIB-AD): http://preview-prod.vfs.va.gov/preview?nodeId=932
- Montgomery GI Bill Selected Reserve (MGIB-SR): http://preview-prod.vfs.va.gov/preview?nodeId=934
- Foreign programs: http://preview-prod.vfs.va.gov/preview?nodeId=925
- Accelerated payments for high-technology programs: http://preview-prod.vfs.va.gov/preview?nodeId=917
- Correspondence training: http://preview-prod.vfs.va.gov/preview?nodeId=919
- Tutorial assistance: http://preview-prod.vfs.va.gov/preview?nodeId=928
- Non-college degree programs: http://preview-prod.vfs.va.gov/preview?nodeId=922
- Flight training: http://preview-prod.vfs.va.gov/preview?nodeId=921
- Entrepreneurship training: http://preview-prod.vfs.va.gov/preview?nodeId=920
- Work study: http://preview-prod.vfs.va.gov/preview?nodeId=931
- Co-op training: http://preview-prod.vfs.va.gov/preview?nodeId=918
- On-the-job training and apprenticeships: http://preview-prod.vfs.va.gov/preview?nodeId=923
- Tuition Assistance Top-Up: http://preview-prod.vfs.va.gov/preview?nodeId=927
- National Call to Service program: http://preview-prod.vfs.va.gov/preview?nodeId=946
- Veterans’ Educational Assistance Program (VEAP): http://preview-prod.vfs.va.gov/preview?nodeId=948
- Transfer your Post-9/11 GI Bill benefits: http://preview-prod.vfs.va.gov/preview?nodeId=952
- Post-9/11 GI Bill Statement of Benefits: http://preview-prod.vfs.va.gov/preview?nodeId=3007 Did not edit this page yet, but wasn't sure if I should since it's an h2.

<img width="1071" alt="Screen Shot 2020-09-11 at 10 42 54 AM" src="https://user-images.githubusercontent.com/42546515/92939917-6771e300-f41c-11ea-94d1-7c62e4aa3888.png">

**Disability**
- Eligibility for VA disability benefits: http://preview-prod.vfs.va.gov/preview?nodeId=871
- Benefits for former prisoners of war (POWs): http://preview-prod.vfs.va.gov/preview?nodeId=872
- VA disability compensation for PTSD: http://preview-prod.vfs.va.gov/preview?nodeId=891
- Disabilities that appear within 1 year after discharge: http://preview-prod.vfs.va.gov/preview?nodeId=890
- Exposure to specific environmental hazards: http://preview-prod.vfs.va.gov/preview?nodeId=889
- Agent Orange exposure: http://preview-prod.vfs.va.gov/preview?nodeId=874 (major content updates to page recently, may want to hold off on publishing)
- Veterans asbestos exposure: http://preview-prod.vfs.va.gov/preview?nodeId=882
- Mustard gas or lewisite exposure: http://preview-prod.vfs.va.gov/preview?nodeId=887
- Camp Lejeune water contamination health issues: http://preview-prod.vfs.va.gov/preview?nodeId=883
- Ionizing radiation exposure: http://preview-prod.vfs.va.gov/preview?nodeId=886
- Exposure through Project 112 or Project SHAD: http://preview-prod.vfs.va.gov/preview?nodeId=888
- Gulf War Illnesses linked to Southwest Asia service: http://preview-prod.vfs.va.gov/preview?nodeId=885
- Gulf War Illnesses linked to Afghanistan service: http://preview-prod.vfs.va.gov/preview?nodeId=884
- VA Agent Orange Registry exam: http://preview-prod.vfs.va.gov/preview?nodeId=877
- Agent Orange exposure in Vietnam or Korea: http://preview-prod.vfs.va.gov/preview?nodeId=879
- Agent Orange exposure on Navy or Coast Guard ships: http://preview-prod.vfs.va.gov/preview?nodeId=876
- Agent Orange exposure on Thailand military bases: http://preview-prod.vfs.va.gov/preview?nodeId=881
- Agent Orange exposure from C-123 aircraft: http://preview-prod.vfs.va.gov/preview?nodeId=875
- Agent Orange testing and storage outside Vietnam: http://preview-prod.vfs.va.gov/preview?nodeId=880
- VA automobile allowance and adaptive equipment: http://preview-prod.vfs.va.gov/preview?nodeId=893
- Birth defects linked to Agent Orange: http://preview-prod.vfs.va.gov/preview?nodeId=894
- VA clothing allowance: http://preview-prod.vfs.va.gov/preview?nodeId=895
- Temporary disability rating after surgery or cast: http://preview-prod.vfs.va.gov/preview?nodeId=897
- Increased disability rating for time in a hospital: http://preview-prod.vfs.va.gov/preview?nodeId=898
- VA temporary disability (prestabilization rating): http://preview-prod.vfs.va.gov/preview?nodeId=899
- VA Title 38 U.S.C. 1151 claims: http://preview-prod.vfs.va.gov/preview?nodeId=892
- VA Individual Unemployability if you can't work: http://preview-prod.vfs.va.gov/preview?nodeId=900
- Pre-discharge claim: http://preview-prod.vfs.va.gov/preview?nodeId=911
- View your VA disability ratings: http://preview-prod.vfs.va.gov/preview?nodeId=2408

**Burials and memorials**

- [Eligibility for burial in a VA national cemetery](https://www.va.gov/burials-memorials/eligibility/): http://preview-prod.vfs.va.gov/preview?nodeId=856 Updated the current language to fit the eligibility language template.
- How to apply for a Veterans burial allowance: http://preview-prod.vfs.va.gov/preview?nodeId=864
- [Veterans headstones, markers, and medallions](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/): The current language is not written in such a way that would fit the eligibility language template.
- Burial flags to honor Veterans and Reservists: http://preview-prod.vfs.va.gov/preview?nodeId=858
- Presidential Memorial Certificates: http://preview-prod.vfs.va.gov/preview?nodeId=860
- Bereavement counseling: http://preview-prod.vfs.va.gov/preview?nodeId=854

**Pension**
- Eligibility for Veterans Pension: http://preview-prod.vfs.va.gov/preview?nodeId=585
- VA Aid and Attendance benefits and Housebound allowance: http://preview-prod.vfs.va.gov/preview?nodeId=584
- VA Survivors Pension: http://preview-prod.vfs.va.gov/preview?nodeId=590

**Comment by bethpottsVADEPO** [comment]
@DanielleThierryUSDSVA for awareness. This will tamp down our use of "get" (Can I get) and address the current inconsistencies.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks! Randi and I have touched base about this.

@lunascoop @RLHecht Just a note that you don't have to worry about the Agent Orange pages since those are going away with the consolidation work in that section. Thanks!

**Comment by RLHecht** [comment]
These pages have all been reviewed and published except for a few, which I also slacked @bethpottsVADEPO about. For these, the new wording seemed awkward and I wasn't sure if we should keep as is or update in a different way. Beth was going to review. These are the pages:

http://preview-prod.vfs.va.gov/preview?nodeId=753
http://preview-prod.vfs.va.gov/preview?nodeId=760
http://preview-prod.vfs.va.gov/preview?nodeId=761 (No lead in sentence for our bulleted list)
http://preview-prod.vfs.va.gov/preview?nodeId=925
http://preview-prod.vfs.va.gov/preview?nodeId=919
http://preview-prod.vfs.va.gov/preview?nodeId=920
http://preview-prod.vfs.va.gov/preview?nodeId=931 (I think this one should stay as it was)

FYSA @brianalloyd @MickinSahni 
http://preview-prod.vfs.va.gov/preview?nodeId=918
http://preview-prod.vfs.va.gov/preview?nodeId=952

**Comment by DanielleThierryUSDSVA** [comment]
Just noting that Beth and I will be reviewing these together on Thursday.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Beth and I reviewed some of these. Here's guidance on the ones we got through today:

Please revert back to the "Can I get" language for:

http://preview-prod.vfs.va.gov/preview?nodeId=753 (we did this one, please just check for errors)
http://preview-prod.vfs.va.gov/preview?nodeId=760
http://preview-prod.vfs.va.gov/preview?nodeId=761 

Let's use "Can I use my VA education benefits..." and "You may be able to use your education benefits for..." for:

http://preview-prod.vfs.va.gov/preview?nodeId=925
http://preview-prod.vfs.va.gov/preview?nodeId=919

Will update with others soon. Thanks!

**Comment by RLHecht** [comment]
Changes to the pages above have been made and published.

**Comment by DanielleThierryUSDSVA** [comment]
Beth/Danielle content planning meeting 11.4.21:
- Reassess which pages still need review and updating (based on the nuance of some needing eligibility and others needing can I get/can I use language per notes above)
- Also address heading levels in featured content component

**Comment by bethpottsVADEPO** [comment]
@RLHecht Here are the remaining oddball headers that you'd identified above:
http://preview-prod.vfs.va.gov/preview?nodeId=920 (please review my edit to "can I get...")
http://preview-prod.vfs.va.gov/preview?nodeId=931 (Agree that this one should stay as it is)

Randi, these are the 2 you called out for Mickin and Brian (I don't remember what they would have been assessing). The first one (918) looks ok to me--do you know what the issue was? For the second one below, I edited in drupal.
http://preview-prod.vfs.va.gov/preview?nodeId=918 (no change)
http://preview-prod.vfs.va.gov/preview?nodeId=952 (please review my edit to the header and first line of text)

Here's the related work that you can either use this ticket for or create a new ticket for:
1/ Make all blue box headers H2s. Some are currently H3s.
2/ Fix the start of each bulleted item so each line of text can stand-alone (add a subject, and remove that subject from the bold lead-in line above the list.

**LIKE THIS:**
**At least one of these must be true:**
- You got sick or injured while serving in the military—and can link this condition to your illness or injury (called an inservice disability claim), **or**
- You had an illness or injury before you joined the military—and serving made it worse (called a preservice disability claim), **or**
- You have a disability related to your active-duty service that didn’t appear until after you ended your service (called a postservice disability claim)

**NOT LIKE THIS:**
**At least one of these must be true. You:**
- Got sick or injured while serving in the military—and can link this condition to your illness or injury (called an inservice disability claim), **or**
- Had an illness or injury before you joined the military—and serving made it worse (called a preservice disability claim), **or**
- Have a disability related to your active-duty service that didn’t appear until after you ended your service (called a postservice disability claim)

**Comment by RLHecht** [comment]
Work in this ticket is now complete. I opened a new ticket (#32659) to do the work of changing H3s to H2s and adjusting the language in bulleted lists so that the subject is in each item.
