### ISSUE TITLE
Debt management: Develop unauthenticated content for usability testing

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10781]
## Issue Description
Develop content for unauthenticated debt management page.

---
## Tasks
- [x] Draft unauthenticated content based on compiled FAQs; identify which FAQs may also work for authenticated content (Selina)
- [x] Review/edit content (Danielle)
- [x] Share with Mikki (IA) and debt management product team (Selina, Danielle)
- [x] Update page based on meeting (except accordion content) (Danielle)
- [x] Edit (Beth)
- [x] Send content to product team for usability testing (Danielle)

## Acceptance Criteria
- [x] Content sent to product team for usability testing

## Documentation

[Mapping.Recommendations.for.Debt.Management.FAQs.-.Unauthenticated_Authenticated)[https://app.zenhub.com/files/133843125/84b6b822-99de-4ad7-9cd3-e8a5a8b17472/download]

[Debt.Management.Wireframe.Recommendation](https://app.zenhub.com/files/133843125/7ee94ec7-969e-4dbf-a1a7-cb55a898640c/download)

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @DanielleSoCompany here is a draft version for review.
[View your VA debt Copy.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4854733/View.your.VA.debt.Copy.docx)

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO Would love your editing eyes on this version that I'm prepping to send over to the team for usability testing. Thanks!

[https://app.zenhub.com/files/133843125/64cf805e-54a2-4036-83bc-1937e538a625/download](https://app.zenhub.com/files/133843125/64cf805e-54a2-4036-83bc-1937e538a625/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler @rebeccawalsh @rileyorr @mattpointzxer0. Here's the content for usability testing. 

As discussed, this doesn't include the content within each accordion. We'll continue building that out as the prototype goes through usability testing. Thanks!

[Manage your VA debt_unauthenticated tool landing page_content for usability testing_7.9.20](https://app.zenhub.com/files/133843125/83b52a51-2e25-4917-9cdd-41eddc88b635/download)

**Comment by leahkeeler** [comment]
Thank-you @DanielleThierryUSDSVA We are planning to launch MVP which is just the landing page, debt summary and a list of debt letter without doing usability. Iteration 2 to follow MVP release will be preceded by usability study. Does this impact your timelines?

**Comment by DanielleThierryUSDSVA** [comment]
@leahkeeler and I chatted in slack. Adding dates below:

- Build out full content in Drupal by 7.24

- Get SME feedback/approval by 7.31

**Comment by rebeccawalsh** [comment]
@DanielleThierryUSDSVA Hey there, we had a question from Shawna and was hoping to give her a little more than our assumptions. Can you explain a little more about how you chose which content would be in FAQ accordions and which would not? What is the process for figuring out what goes where?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rebeccawalsh. Sure, of course! We did a content audit of the debt management website to determine questions/info needs, then consolidated into high-level FAQs that will provide key info (and link off to debt management site for more in-depth details for now). And then as we'd talked about in our meeting, we'll reevaluate the debt management website in full following our full IA/content strategy process for migrating content beyond tool landing pages. Thanks!

**Comment by sshein** [comment]
thanks all :) I just was curious because on the page we have some key questions and their answers. Then I see a header that says "Frequently asked questions about VA debt" and I had a moment of confusion, thinking, "wait, wasn't I just reading FAQs about VA debt? I made me wonder what the difference was and if I was missing something

**Comment by DanielleThierryUSDSVA** [comment]
Ah, gotcha, @sshein. Yeah, the key questions above are about the tool, and the FAQs are about the debt in general. (Exception being the "Who can I call for help..." which we'd discussed putting in the FAQs, but decided not to because we want it to remain prominent since a lot of people call).

That said, I can totally see the cognitive pause there. So I think we could add "More" to the accordion header ("More frequently asked questions about VA debt") just to acknowledge that we do have Qs above. Thanks!

**Comment by sshein** [comment]
ohhh I see. sounds good :)
