### ISSUE TITLE
[Design] DL - User Research Conversation Guide Draft 1

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10799]
## Issue Description
Create a conversation guide 

---
## Tasks
- [x] Complete the conversation guide template found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/conversation-guide.md)
- [x] Share with designer

## Acceptance Criteria
- [x] Convo guide in GH

**Comment by rileyorr** [comment]
I've uploaded [the initial conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/conversation-guide.md) to GH so our work prior to the MVP/research pivot is documented this sprint.
