### ISSUE TITLE
[LOAD-DATA] Load compiled VISN-19 Data into respective Health Service Programs, Entities, and Facilities Detail pages [Data Tech]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10792]
## VAMC - Product Outline
[VAMC-upgrade Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)

## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional information in plain language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## VAMC-Upgrade KPI met with this EPIC
_These tasks support the load of CONTENT from legacy to NEW web systems prior to Milestone date for VISN 19._

## Definition of Done 
- [x] _All required Data compiled for Facilities, Top Tasks, Action Pages, and Health Service Programs have been loaded for all 8 remaining VISN 19 Health Systems to include:_
- [x]  VA Cheyenne health care
- [x]  VA Eastern Colorado health care
- [x]  VA Western Colorado health care
- [x]  VA Montana health care
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care

- [ ] _Preview URL has been provided to specific System PAO for review.
