### ISSUE TITLE
[ENGINEER] Create and/or Clone all nodes required for VA Western Colorado (Grand Junction) WITH NO MENU [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10803]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Clonable Website](prod.cms.va.gov)

## Tasks
_Creation of the following Drupal types and pages_
* Next Section: Items not in Menu
- [ ] Make an Appointment (Clone from Erie VA health care)
- [ ] Register-for-Care (Clone from Erie VA health care)
- [ ] Billing-insurance (Clone from Erie VA health care)
- [ ] DAV-vans (Clone from Erie VA health care)
- [ ] Medical-records-office (Clone from Erie VA health care)
- [ ] Operating-status (Clone from Erie VA health care)
- [ ] Pharmacy (Clone from Erie VA health care)
* Next Section: Caregiver
- [ ] Caregiver-support (Clone from Erie VA health care)
- [ ] Homeless-veteran-care (Clone from Erie VA health care)
- [ ] LGBT-veteran-care (Clone from Erie VA health care)
- [ ] Mental-health-care (Clone from Erie VA health care)
- [ ] Minority-veteran-care (Clone from Erie VA health care)
- [ ] Patient-advocates (Clone from Erie VA health care)
- [ ] Returning-service-member (Clone from Erie VA health care)
- [ ] Suicide-prevention (Clone from Erie VA health care)
- [ ] Women-veteran-care (Clone from Erie VA health care)
* Next Section:
- [ ] Campus Map (Clone from Erie VA health care)
- [ ] Champlain Services (Clone from Erie VA health care)

## Acceptance Criteria
- [ ] Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [ ] Validate that pages are read to take data load information
- [ ]  All system pages listed above have been created
