### ISSUE TITLE
[Design] Update Documentation

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10806]
## Background
Prior to launching Profile 2.0 we would like to have all documentation up to date.

## Tasks
- [x] Update design sections of the product outline  
- [x] Add most up-to-date sketch file to Github
- [x] In design README, add links to the InVision prototypes
- [x] If you were a designer onboarding to this product, what documentation would you want?
