### ISSUE TITLE
Add new text to 2 decision review pages **[NEEDS TO PUSH TO PROD 7/6, NOT EARLIER]**

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#10801]
## Issue Description
_The following language needs to be added to these 3 decision review pages. This needs to go live July 6._

ADD TO THESE PAGES
https://www.va.gov/decision-reviews/after-you-request-review/
https://www.va.gov/decision-reviews/supplemental-claim/
https://www.va.gov/decision-reviews/higher-level-review/

NEW TEXT
If you’ve filed a request for a decision review, we may randomly select you to receive an email with a short, optional survey. If selected, you’ll get a survey within 10 days of the date on your notification letter. You aren’t required to fill it out, but your feedback will help us improve the new decision reviews process. It takes about 3 minutes to answer the questions. Please review your VA.gov profile to make sure we have your most recent email address. Find out how to update your email address.

**Here's how it fit in on the after-you-request-review page (first one listed above), within the existing "What happens next?" section:** <p>
(For the other two pages, it's a similar fit but those pages are slightly different. For both of the other two pages, the new text goes at the end of that section called "What happens next?" After the blue button on the third page.)

**What happens next?**

Find out what happens after you request a decision review

You don’t need to do anything while you wait, unless we send you a letter asking for more information. If we schedule exams for you, be sure not to miss them.

If you’ve filed a request for a decision review, we may randomly select you to receive an email with a short, optional survey. If selected, you’ll get a survey within 10 days of the date on your notification letter. You aren’t required to fill it out, but your feedback will help us improve the new decision reviews process. It takes about 3 minutes to answer the questions. Please review your VA.gov profile to make sure we have your most recent email address. Find out how to [update your email address](https://www.va.gov/change-address/).

If you requested a decision review and haven’t heard back from VA yet, please don’t request another review. Call VA at 800-827-1000.

---
## Tasks
- [ ] _Add the text to the 3 pages listed above in the Decision Reviews section._
- [ ] _Create the text link in the paragraph of new text. It should go to: https://www.va.gov/change-address/ _
- [ ] _Copyedit by Randi_
- [ ] _Set to go live July 6_
- [ ] _Validate on prod July 6_
- [ ] _Notify stakeholder that it's live_

## Acceptance Criteria
- [ ] _Text as outlined above goes live on 3 pages on July 6._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AnneHurley** [comment]
Production links for preview:
1. After you request a review: http://preview-prod.vfs.va.gov/preview?nodeId=3008

**Comment by bethpottsVADEPO** [comment]
7/2 Received word back from stakeholder that I should tailor the first sentence of the new paragraph we added to Supplemental Claims and Higher-Level Reviews to reflect those two types of decision reviews rather than using the more general term "decision review" as we have it on "After you request a review" page. So: 

If you’ve filed a request for a Supplemental Claim, we may randomly select you to receive an email with a short, optional survey. 

AND

If you’ve filed a request for a Higher-Level Review, we may randomly select you to receive an email with a short, optional survey. 

@RLHecht This is ready for a proofread. Can you let me know if there are any edits since it has already been through stakeholder review and is about to go live? Thanks!

**Comment by RLHecht** [comment]
These pages have now all been published. FYSA @bethpotts @AnneHurley @MickinSahni Moving to validate.
