### ISSUE TITLE
AE - Sprint 25

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10804]
# Priorities
1. **Be ready for QA by next sprint**
2. Call Center Product Guide
3. Update documentation for Profile 2.0 (**Only move on to this if call center guide is done**)
4. If time, move on to logged-in homepage work

### PM
Submit/Finalize requests for QA/508 reviews, Finish Call Center Product Guide, Update documentation
- [x] Submit request for Staging review #10764 
- [ ] [PM] Update Profile 2.0 documentation #10818
- [x] (Samara) Profile: Refine OKRs and KPIs #10887

### Design
Finish remaining design tickets, work on Call Center Product Guide and update documentation ( only if Product Guide is finished)
- [x] Update content and link in Change Address page #8420
- [x] [Design] Connected apps error states #10684 
- [ ] Pre-launch - Update relevant parts of the product outline/project folder #10806
- Update design sections of the product outline , Add most up-to-date sketch file to Github,  In design README, add links to the InVision prototypes, If you were a designer onboarding to this product, what documentation would you want?

### Call center
- [ ] Create Call Center Product Guide #7561

### Build
Finish build items needed to go to QA, review pre-QA
- [x] Make sure Profile 2.0 handles upcoming and current downtime #10160
- [ ] [FE] Update Profile Mobile Sub navigation #9729
- [x] [FE] Refocus the "please add your..." CTA link when exiting profile edit mode #9774
- [x] [FE] Profile 2.0 not properly gated for logged-out users #10386 
- [x] [FE] BUG: Input field reverts in the middle of a contact info field update #10771
- [x] [FE] Hide Military History section for non-Vets #10422
- [x] [FE] Build connected apps errors #10687
- [x] [FE] BUG: "you have unsaved edits" sometimes shown when it shouldn't be #10776

## Logged-in Homepage
PM
- [x] Plan for how to incorporate stakeholders #10230
 - [x] Metrics conversation with disability ratings team #10745
 - [x]  Metrics conversation with claim status team #10746

**Moving to these a later sprint**

Design
- [x]  Review journey maps #10120
- [x]  Review discovery findings #10121

Dev
- [ ] Beta/opt-in technical discovery/scoping #10476 (**Only if there's time. OK if we move this back a sprint.**)
