### ISSUE TITLE
Usability Testing Prep Debt Letters MVP

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#10800]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt @Mandi Lipka
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp)
- [Link to UXPin Prototype](https://preview.uxpin.com/4355a6c97a71ddaf1069ec43e5dfc0ae46b79869#/pages/130133417/simulate/sitemap?mode=d)
  - [All statuses](https://preview.uxpin.com/4355a6c97a71ddaf1069ec43e5dfc0ae46b79869#/pages/130984017/simulate/sitemap?mode=i)
- [Link to research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/research-plan.md)
- [Link to conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/conversation-guide.md)
- [Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from BaM2
- Product Manager (required): Leah Keeler
- DEPO product lead (required):  Matt Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): Riley Orr, Rebecca Walsh

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite: **July 27th @ 3:30**

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by meganhkelley** [comment]
Scheduled as requested!

**Comment by meganhkelley** [comment]
Rescheduled per VFS team request

**Comment by rebeccawalsh** [comment]
@mandifrances Hi there! We have our stuff together and updated above. Can we swing in and grab that Monday, July 27 @3:30 slot? Please let me know if any further clarification is needed. Thank you.

**Comment by mandifrances** [comment]
Hi @rebeccawalsh I was able to get you scheduled for Tuesday, July 28th @ 11:30am EST. Thank you.

**Comment by jenstrickland** [comment]
Brad reached out to me as he was developing the mockup he was provided, shown here. I didn't see this design in the prototype. Is there somewhere I should look for additional design components/layouts?

![Screen Shot 2020-07-23 at 2 55 41 PM](https://user-images.githubusercontent.com/57469/88391195-b2aa3680-cd87-11ea-83da-cb7baf6273ff.png)


Note: The icon shown in the screenshot below should be added for downloads, and we ideally also want to communicate file size when possible. If this design can be adjusted, I have recommendations to document for making it clearer for cognition and screen readers.

![Screen Shot 2020-07-23 at 3 11 15 PM](https://user-images.githubusercontent.com/57469/88391074-6bbc4100-cd87-11ea-8a87-b99d9cad5596.png)

**Comment by pjhill** [comment]
@rebeccawalsh There do not appear to be any quality assurance artifacts attached for review. Has work on a test plan verifying the user stories, regression testing, and load testing begun?

**Comment by rebeccawalsh** [comment]
@jenstrickland That table can be seen here: https://preview.uxpin.com/4355a6c97a71ddaf1069ec43e5dfc0ae46b79869#/pages/130778050/simulate/sitemap?mode=i -- I like the inclusion of the icon and PDF in the title, but I feel the icon needs to be much larger for legibility. Thoughts? 

@pjhill No QA artifacts are attached because we don't have anything to regression test against, similar to MDOT. Leah has worked with Tze to work out the details of QA, I believe. We will have to QA during UAT testing. Leah and Mandi discussed this topic in this (obscure) thread recently: https://dsva.slack.com/archives/CBU0KDSB1/p1593552484085700

**Comment by jenstrickland** [comment]
@rebeccawalsh Thanks! Is that page part of the flow in the conversation guide? 

I agree it would be great to reconsider the icon size — that's a much larger conversation. This is using the icons as they are in the VA design system, so we've gotta use that.

**Comment by jenstrickland** [comment]
@bradl3yC @rebeccawalsh This morning I made an adjustment to the [documentation link guidance](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340). Tl:dr: removed the title attribute, this change is probably only of interest for Brad.

**Comment by tlei123** [comment]
@camerontesterman , as a "baby-step" for Regression Test Planning...

Do we have any [load testing](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/load-testing) being planned for the API endpoints?

This is not a hard requirement right now, but even though DL is a brand-new product on the front-end side, @pjhill mentioned that maybe some API load testing would be a good idea, just to measure impact on the existing API endpoint(s) \[IF you have the time to coordinate/collaborate w/ DevOps and/or VFS Platform Support].

**Comment by mandifrances** [comment]
Recording to meeting: https://zoom.us/rec/share/u9RLIL6spl9IS6vK2gLPUJEQRarFX6a8hCJN-PdfmusC3Vy-QZPdSnVvp89DJ1s

Pswd: 0S*EFiv5
