### ISSUE TITLE
[PM] Update Profile 2.0 documentation

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10818]
## Background 
Prior to launching Profile 2.0, we want to have all documentation complete and updated.

## Tasks
- [ ] Update product outline
- [x] Update items in product folder
- [x] Update use cases/TestRail documentation
