### ISSUE TITLE
Draft proposal for display of bio data in forms

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10814]
### User story
As a user of VA.gov forms, I need to see what VA knows about my biographical info, and what to do if there are errors, so that I can address incorrect info in my record.

### Situation
The  VA.gov form system has three ways to display/collect biographical data about a user:
- Blank fields for unauthenticated users
- Static, uneditable info for authenticated users
- Pre-filled, editable info for authenticated users

There are several factors governing which of the two authenticated scenarios are used. VSA will present a proposal outlining best-practices, and acceptable alternatives/fallbacks for sub-optimal situations. Various use cases have been explored and a diagram exists as a basis for proposing solutions.

### Goal
Provide design guidance to all VSA teams regarding the display and collection of known biographical info within the VA form system.

### Considerations
- See this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10671)
- Existing [diagram](https://xd.adobe.com/view/0c64c9ff-aba2-422e-4d6e-be1ec4cab845-7a55/)
- Background [Slack conversation] (https://dsva.slack.com/archives/CLY6Q69RV/p1593119293361900)

### Tasks
- [ ]  Draft proposal for best-practices for the display/collection of known biographical data
- [x]  Collect input/feedback from the team
- [ ]  Present draft to Shawna for review

### Acceptance criteria
- [ ] An MD document is produced and shared outlining design best practices

**Comment by sporeboy** [comment]
WIP MD doc is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/bio-info-form-data-discovery.md

Working on data sources and recommendations.

**Comment by sporeboy** [comment]
Initial draft done and shared with Shawna. The MD doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/personal-contact-form-data-proposal.md

The XD doc: https://xd.adobe.com/view/0c64c9ff-aba2-422e-4d6e-be1ec4cab845-7a55/

**Comment by sporeboy** [comment]
New link to Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/personal-contact-form-data-proposal.md

XD diagrams and mockups: https://xd.adobe.com/view/0c64c9ff-aba2-422e-4d6e-be1ec4cab845-7a55/

**Comment by jason-gcio** [comment]
Haha this link looks the same to me
