### ISSUE TITLE
Implement File Upload

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10817]
## Goal 
We need to have document/ file upload implemented into the 686 so that files from the Veteran can be uploaded and attach to their submission.

## Tasks
- [x] Check with BAM1 to see if the frontend code needs to change, find someone to talk to
- [x] Consider checking in again with platform
- [x] Create an endpoint for uploading files
- [x] Implement the file upload tasks

## Acceptance Criteria
- [x] File upload is working locally 

`FE will need to plugin url when they get it`

**Comment by kathleencrawford** [comment]
File upload is done and draft PR created.  I need to add some spec tests for coverage.  Also, we need to make a final decision on form ID (21-686c vs 686c-674).  

File upload will not work locally running docker.  Platform is working on a fix for this, but it does work locally with native setup and works in staging.

**Comment by jason-gcio** [comment]
🎉
