### ISSUE TITLE
[Backend] DL- DLC API Debt must match letter in VBMS - Story Modified    

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10811]
## Issue Description
A veteran can have one or many debts that are passed in DMC API to be displayed on Summary Page. A veteran will have the ability to download the debt letter that is associated with a specific debt summary. 

---
## Tasks
- [ ] _Identify data element in DMC API  that is tied to specific debt letter in vbms
- [ ] _Work with DMC to modify API , if needed 
_ [ ] _ add variable in API  get 

## Acceptance Criteria
- [ ] _As a veteran who is viewing a debt summary and clicks on download letter associated with that debt, I expect to be able to download that letter 
- [ ] _For any given test user the downloaded letter matches the debt summary 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
This use story is modified due to the vbms technical constraints. 

New Story: For a given unique user, I want the ability to see a list of all my debt letters in reverse chronologic order and have the ability to click on a link to view and download the debt letter"

**Comment by camerontesterman** [comment]
Done.
