### ISSUE TITLE
Review 10-10CG revisions/expansion for regulatory changes

### ISSUE THREAD

**Issue by psanders86** [department-of-veterans-affairs/va.gov-team#10820]
## Issue Description
I want to document the differences between the current and revised version of the paper 10-10CG form, identify how the 10-10CG online form will be affected by program expansion and regulatory changes.

---
## Tasks
- [x]  Review revised version of the paper form and document differences
- [x]  Create a spreadsheet that outlines affected portions of the online form
- [x]  Make content recommendations that meet Plain Language guidelines and comply with VA.gov style.

## Acceptance Criteria
- [ ] Caregiver team will have an understanding of how the 10-10CG online version is affected by the revised paper version and the scope of work involved to bring the MVP up to date.
---

**Comment by psanders86** [comment]
There are five significant proposed changes to the 10-10CG that would affect either the 10-10CG online form, or the existing introduction page that is managed by the public websites team.

There are also several other minor changes, many of which have been addressed already on the online form.

## Major change 1 ##

The proposed paper version deletes definitions of family member, primary family caregiver and secondary family caregiver, while adding a new definition of family caregiver: "An individual who is approved and designated by VA as the Primary Family Caregiver or Secondary Family Caregiver."

#### Impact of this change on the online form: ####
On Section 2 Primary Family Caregiver information, we should replace the “What’s a Primary Family Caregiver” dropdown that includes legalese. 
![1010cg file 1.PNG](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/fef8169b-3caa-47a7-b542-4f5ad70b1491)

#### Proposed new language: ####
**What’s a family caregiver?**
Family caregivers are people approved and designated by VA to provide personal care services to a Veteran.

## Major change 2 ##

The proposed paper version deletes definitions of family member, primary family caregiver and secondary family caregiver, while adding a new definition of family caregiver: "An individual who is approved and designated by VA as the Primary Family Caregiver or Secondary Family Caregiver."

#### Impact of this change on the online form: ####

On Section 3 Secondary Family Caregiver information, we should delete the definition in the dropdown for secondary family caregiver. The family caregiver definition was already published earlier in the form and does not have to be repeated here.
![1010cg file 2.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/44d20850-6cd1-4072-9143-0beb5429b9f3)

#### Proposed new language: ####
None

## Major change 3 ##

The proposed paper version changes the selections for veterans and caregiver applicants to declare their gender. It deletes “Unknown” and replaces it with “Prefer Not to Answer.”

#### Impact of this change on the online form: ####

On each of the four places where we collect applicant gender information, we should change the online form to match the proposed changes to the paper form.
![1010cgfile3.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/6096e245-734b-416b-9fd9-8e69e25243dc)

#### Proposed new language: ####

- Female 
- Male 
- Prefer not to answer



## Major change 4 ##

The proposed paper version deletes separate yes/no questions that ask the primary family caregiver candidate if they are enrolled in Medicaid, Medicare, Tricare, CHAMPVA or other health insurance, and replaces it with a single question: “Do you have health care insurance (i.e., private insurance, CHAMPVA, Medicare, Medicaid or Tricare?” 

#### Impact of this change on the online form: ####

In Section 2, we should delete the lengthy series of questions on health care, including the four definitions of Medicaid, Medicare, Tricare and CHAMPVA. 

![1010cgfile4.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/e9273fd6-0b3b-4d8b-830d-b6bacf13d4b9)

#### Proposed new language: ####

Does the Primary Family Caregiver applicant have health insurance, including Medicaid, Medicare, CHAMPVA, Tricare, or private insurance?

- Yes
- No

## Major change 5 ##

The proposed change to the paper form also reflects a significant change to the Veteran’s eligibility, adding language that Veterans must have a disability rating from the VA of 70% or more for a service-connected disability incurred or aggravated on or after Sept. 11, 2011 or before May 7, 1975, or effective two years after certification date, after 5/7/75 and before 9/11/2001. That change would most likely need to be reflected on the existing landing page that is managed by the Public Websites team. https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/

## Minor changes to address on the online form ##

Three other proposed revisions to the paper form can also be made on the online 10-10CG form to bring it into alignment with the paper version. 

| Item | Recommendation |
| :------------- | :----------: |
|  Veteran information heading | Change to "Veteran information"   |
|  Primary Family Caregiver heading | Change to "Primary Family Caregiver applicant information"   |
|  Secondary Family Caregiver heading | Change to "Secondary Family Caregiver applicant information"   
|

## Changes with no impact on the online form ##

There are numerous other proposed changes to the paper form that incorporate language that already appears on the online form, or have previously been rewritten for the online form to comply with Plain Language and VA.gov style guides.

| Location on paper form | Note |
| :------------- | :----------: |
|  Global | Adds PCAFC acronym |
|  Global | Uses the full program name on the top of each page |
|  Global | Changes “caregiver” to “caregiver applicants” throughout |
|  Global | Deletes references to servicemember throughout |
|  Page 1 introduction | Clarifies that Veterans must be eligible to get benefits |
|  Page 1 introduction | Changes the structure explaining where applicants can get help |
|  Page 1 introduction | Changes “appointed” to “requested” |
|  Page 1 definitions | Changes language in header |
|  Page 2 | Rewrites language under “Getting Started” |
|  Paperwork Reduction Act | Clarifies that completion of the form is a requirement for PCAFC |
