### ISSUE TITLE
686 Punch List - Form Field Title Updates

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#10828]
## Description
There are some remaining items on the 686 punch list that require bolded words in different form field titles of the 686. These should be completed and checked off the punch list in this ticket. 

## Considerations
- Bolding individual words in a form field title may require custom title components. 
- [Punch list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0420.md)

## Tasks
- [x] Update all items on the punch list that require bolded words in the title.
  - [x] Bold "**or**" in labels under the "Where were you married?" section
  - [x] Bold "**your spouse**" in the label, "Was your spouse married before?"
  - [x] Bold "**or**" in labels under the "Place of marriage to former spouse" section
  - [x] Bold "**or**" in labels under the "Place marriage with former spouse ended"
  - [x] Bold "**you**" in "Were you married before?"
  - [x] Bold "**or**" in labels under the "Child's place of birth" section
  - [x] Bold "**or**" in "Kind of training or educational program"
  - [x] Bold "**or**" in labels under the "Place of death" section
  - [x] Bold "**or**" in labels under the "Where did this marriage end?" section

## Acceptance Criteria
- [x] All titles listed on the punch list have been updated.

**Comment by jason-gcio** [comment]
These have been updated in the larger doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0420.md
