### ISSUE TITLE
[Design] Review the 'Letter Details' document as the data available to display on the Debt Letters MVP tool

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#10839]
## Issue Description
_Given that the team learned that the only data we'll be receiving through the API is in the 'Debt details' document, we need to dig into that document to understand what's available to display on the frontend._

---
## Tasks
- [x] _Review the 'Letter details' document_
- [x] _If necessary, compile a list of questions and/or information about the letters that need to be discussed with the DMC team_
- [x] _Create a list of use cases the team would like mock API responses of_
- [x] _Create a first pass at writing content for letters that don't need followup with DMC_

## Acceptance Criteria
- [x] _A list of questions about the data is generated and documented in GH_
- [x] _A list of use cases the team would like mock API responses of is generated and documented in GH_
- [x] _An Excel document (or WIP Google Doc) with a first pass at writing the content for letters that don't need followup with DMC is created_
- [x] _Documents are provided in this ticket as a comment_
---

**Comment by rileyorr** [comment]
So many deliverables!
- [A Google spreadsheet containing scenarios](https://docs.google.com/spreadsheets/d/1jAHuCsoEAqIyJTW4D7VL4guwvFdxCJMHQZZ-egv6jPU/edit#gid=493964559)
- [Working list of questions and notes I've compiled while looking through the doc](https://docs.google.com/document/d/1nuu4G6l7mmwIELRzE9id7T3iaqGZp3ZdwAx9CshUhBk/edit)
- [Bucketed list of status codes to display in the UI (currently being reviewed by DMC)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/discovery/jun20-codes-audit.md)
