### ISSUE TITLE
[Design/Research] Claims Status: Synthesize Usability Study #1

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10837]
## Issue Description
_As a UX Researcher I need to write Synthesize my research after the research is complete. The requirement is to create a Topline Summary and a Research findings report. All will be posted in GitHub_

## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
_Synthesize and summarize research_
_Specifically create a Topline summary and a Research findings report.

---
## Tasks
- [x] _Finish Mural board synthesize. 
- [x] _Finish Topline Summary_
- [x] _Finish Research findings report_

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- [x] _Mural board synthesize completed_
- [x] _Finish Topline Summary_
- [x] _Finish Research Findings report_

All documentation is located here: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research/co-design-usability-June

**Comment by chrvalla** [comment]
This is complete and the documentation is all located here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research/co-design-usability-June
