### ISSUE TITLE
Form Submission Load Testing (FE and BE)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10834]
## Goal
We need to determine what happens for load testing from both FE and BE perspective.

## Considerations
- What are our limits in general?
- What are the limits wrt: jobs
- Can this be a platform service?

## Tasks
- [x] Connect with BAM1 on what gets done from a load testing perspective with kicking off `n` number of jobs
- [x] Ask platform on recommended procedures: is it necessary to do this?
- [x] Ask BGS again about load testing procedures, user constraints
- [x] Document in GH what happens and next steps

## Acceptance Criteria
- [x] Next steps and/ or findings have been documented in GH (Micah and Derek to write)

`Next steps`
potentially execute

**Comment by digitaldrk** [comment]
Got a cool link from Anna Carey:
https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest#load-testing

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/LOADTEST.md
