### ISSUE TITLE
[Initiative] Same-day requests (Express Care)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10840]
## Product Initiative Outline:
**Idea:** Create initial MVP of same day telehealth/screening requests in VAOS (aka - Express Care) using existing data flow currently used in legacy implementation of Express Care. 

**Problem Statement:** 
Veterans have medical needs that may either be resolved without an in-person appointment and/or want guidance about how to seek additional care for a medical concern, yet may not demand a trip to the ER. For various reasons, the Veteran may not be able to go into a physical location for this care. In both cases, however, the Veteran _needs to talk to a medical professional today._

**Users:**
1**. Veterans who:**
  - want to minimize potential exposure (eg COVID-19)
  - have limited access to transportation / funds for transportation
  - have medical questions that can be triaged either via phone or telehealth appointment
  - in our research all Veteran interviews indicated they would use a same day, telehealth appointment option

2. **Internal VA staff** _(this is the staff managing the Schedule Manager queue for EC requests)_
  - MSAs (Medical Support Staff) & NPs (Nurse Practitioners)
 - LIPs (Licensed Independent Practitioner)

**Hypothesis:**
We believe that by providing Veterans with option to request same day consultation/telemedicine for specific symptoms, we can either get them the care they need without f2f visit. 

We also believe that this option is going to become a desirable feature for Veterans that helps them lessen the burden of coming into to VAMC for care that can be triaged over the phone/telehealth video visit. 

**Assumptions:**
- this offering will be to a low number of users as it's being piloted in SF and soon Wilmington, NC
- we expect to see low overall usage numbers, but we hope to see high usage numbers for facilities that have enabled this option
- we assume there is no substantial data changes necessary to implement this feature
- we will need to take into consideration current EC implementation since it's based on specific stakeholder direction

**Potential EC Flow:**
**Step 0.** Can user use this - meaning is Veteran registered at a facility offering EC (Y/N) -> if no don't see EC prompt; if YES - user sees EC prompt, goes to Step 1

**Step 1.** Are you having a medical or mental health emergency --> If YES, bail out to 911 or VCL (using OUR VCL language and link to our tools) If NO--> Step 2

**Step 2.** This is what express care is. This is roughly what you can expect. Here are some examples of conditions that are appropriate for express care. Does this describe your current situation? 
      --> NO, let me submit a regular appt--> VAOS Reg; 
      --> NO let me see my facility number so i can call them --> FL; 
       or YES, that's me--> Step 3

**Step 3.** EC request flow

**Options:**
- veterans who log in to new VAOS and are registered at facility who has enable of EC in VATS, Veteran can see EC prompt on the appts homepage
- veterans can also reach this feature directly without ever seeing the appts homepage (ex. get dropped into EC flow in new VAOS if they click link on specific VAMC website that's promoting EC)

## Existing implementation on legacy VAOS:
![conditions list.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/b7edbe63-8120-4517-a16e-e29736f95917)

## Plan
- [x] Define/Planning Kickoff-Intent 
- [x] Define Design intent 
- [x] Discover Usability Testing Prep 
- [x] Discover Research Plan Review 
- [ ]  Discover IA Request  
- [ ] Discover Analytics Request 
- [ ] Build Contact Center Review  
- [ ] Build Privacy/Security Review 
- [ ] Build Staging Review  
- [ ] Validate Post-launch checkin 
- [ ] Validate/Launch Full A11y Review

## Definition of Done
- Veteran sees the EC prompt on appts homepage to start EC flow if eligible when they log in to VAOS
- Veteran is dropped into EC flow if they navigate from specific VAMC website, MHV, or other VA sites with a specific EC url to new VAOS without seeing appts homepage
- Veteran is provided path to seek emergency assistance
- Veteran is provided brief, informative overview on what EC
- Veteran who is eligible for EC can opt out of EC and go to regular scheduling flow at any time
- Display prominently the start and end times for EC for specific facility & that submission will be processed within 1 hour
- Veteran registration & facility eligibility:
   - If Veteran is registered at one VAMC & that facility has EC turned on and available for today then display EC prompt on Appts homepage
   -  i'm registered at a site that offers it and a site that does not - "Express care is a pilot feature currently available for Veterans in San Francisco. Is San Francisco where you primarily receive your VA care? Y/N"
   - registered at 2+ places and those 2+ places also have EC enabled and available today, then they'll need to pick.

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)

## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team**
