### ISSUE TITLE
Profile 2.0 launch: Publish related updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10858]
## Issue Description
We need to publish relevant updates to support Profile 2.0 launch when we get the go-ahead from the authenticated experience team.

---
## Tasks
- [x] Publish updates to Change your address page
- [x] Publish updates to Sign in FAQs page (addition of connected accounts FAQs)

## Acceptance Criteria
- [x] Change your address and Sign in FAQs pages are updated on live site

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I just published 1 of the 2 pages above (sign in to add the connected apps faqs). Just noting for your awareness. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Complete
