### ISSUE TITLE
Change address: Update Drupal page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10857]
## Issue Description

We need to update the content on this page to support Profile 2.0 launch: https://www.va.gov/change-address/

**This will include:**

- Removing the subway map under this question: How do I change my address in my VA.gov profile?

- Adding this content beneath the question: 

You can change your mailing and home addresses in your profile's **Personal and contact information** section. To do this, you need to be signed in to VA.gov with a verified account.

-  Adding the react widget being built in [issue #10853](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10853)

---
## Tasks
- [ ] Update content and insert react widget in Drupal page (content writer)
- [ ] Review and save as **draft** (do not publish with this issue)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht No action needed on this for now. Assigning us both just to keep on our radars for Sprint 26. Thanks!

FYSA @MickinSahni

**Comment by Samara-Strauss** [comment]
Hello! Looping myself, @mshea0606, and @tressaellen in for visibility. Can you keep us posted when these changes are up on staging? We can look things over and make sure everything looks a-ok then. 

Also, we are targeting launch to UAT users not next sprint but probably the sprint after (end of August). Will this be ready by then?

Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @Samara-Strauss! I think so, yes. Just checked in with Nick and Mickin in the react widget ticket re: timing.

**Comment by Samara-Strauss** [comment]
Awesome — keep us posted. I'll let you know of an official start date for UAT when we have one.

**Comment by RLHecht** [comment]
@lunascoop This is now ready to be worked on. Can you please implement the changes and I will review? Thanks! FYSA @MickinSahni

**Comment by lunascoop** [comment]
@RLHecht I made the changes and added the react widget to the change address page. It is ready for review.

- http://preview-prod.vfs.va.gov/preview?nodeId=709

**Comment by RLHecht** [comment]
Thanks @lunascoop all looks good. @DanielleThierryUSDSVA this is reviewed and ready. Should we close this ticket?
