### ISSUE TITLE
Break Sentry alerting out of the generic revproxy monitoring alerts and create custom thresholds for Sentry

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#10872]
## Background/context/resources
As described in this [slack discussion](https://dsva.slack.com/archives/CTYQL39FE/p1593709116295100), there was an alerting event that took place in the oncall channel. The root cause was due to a spike in Sentry. 

We could probably help mitigate this going forward by removing Sentry from the "95% of http requests served in under 2 seconds" metric/alarm and creating a custom metric specifically for Senty (perhaps 95% under 5 seconds or a higher threshold since we don't care _as_ much about this metric for Sentry as we would about the actual va.gov site or production services).
## Technical notes
Referenced alert is set in [this config file](https://github.com/department-of-veterans-affairs/devops/blob/e197820732e305102bdfc8e6f7eda2653103cd80/ansible/deployment/config/prometheus/rules/site.rules#L28)

---
## Tasks
- [ ] Exclude Sentry from existing alert
- [ ] Create custom metric for Sentry
- [ ] Monitor custom metric for Sentry

## Definition of Done
- [ ] Ideally, higher http wait for Sentry would not fire an alert for the "site"

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jbritt1** [comment]
I think judging by [tonight's oncall alerts](https://dsva.slack.com/archives/C30LCU8S3/p1602025749049800) this may already be done. @kfrz, is my assumption there correct? Or am I confusing / mixing up two different bodies of work?

**Comment by jhouse-solvd** [comment]
According to @tskinn - this is still a bit of a pain point for oncall support personnel. We will prioritize and decide on when is best to do this.

**Comment by jhouse-solvd** [comment]
A lot has changed with the provisioning and deployment of Sentry since it was moved to EKS. 

The Platform Operations team is in the process of setting up monitoring and alerting for Sentry using Datadog, Slack, and PagerDuty. 

This ticket can be closed.
