### ISSUE TITLE
Upgrade / update dsva-sentry-utility RDS instance

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#10873]
## Description
Upgrade and update the dsva-sentry-utility RDS instance. 

## Background/context/resources
As described in this [slack discussion](https://dsva.slack.com/archives/CTYQL39FE/p1593709116295100), there was an alerting event that took place in the oncall channel. The root cause was due to a spike in Sentry. 

One option could be to upgrade the RDS to the next instance size in order to provision some additional resources in hopes of mitigating what we saw going forward. While looking into this option it was also observed that this RDS instance is running on magnetic storage as well as an older version of Postgres.
## Technical notes

If we are going to use this DB long-term, we should upgrade the instance to the next size up, change the storage type to SSD, and probably upgrade the db engine version (currently running Postgres 9.5.15, but Postgres 11.1 is currently available).

---
## Tasks
- [ ] Outside of business hours, we would need to stop the DB instance, make the configuration changes, reboot the instance, verify connections are working as intended. 
 * when we do this we need to alert BE tools and oncall. 
 * Needs to be a DB m4 XL or R5/ R4, need look at Sentry docs to see what they recommend. 
## Definition of Done
- [ ] Make necessary updates / upgrades outlined above. 
---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by annaswims** [comment]
You might consider throttling sentry.  If there's a sudden spike in errors thousands of logged errors are no more useful than hundreds of errors. 

[This](http://sentry.vfs.va.gov/organizations/vets-gov/stats/) makes it look like someone needs to triage vets-website and eliminate the common errors

**Comment by jbritt1** [comment]
> You might consider throttling sentry. If there's a sudden spike in errors thousands of logged errors are no more useful than hundreds of errors.
> 
> [This](http://sentry.vfs.va.gov/organizations/vets-gov/stats/) makes it look like someone needs to triage vets-website and eliminate the common errors

All good info! Thank you Anna for contributing some more detail as well additional options!

**Comment by ricetj** [comment]
This work is no longer needed, if issue come back up we will open another ticket.
