### ISSUE TITLE
Facility Locator Monitoring

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10870]
## Problem
How might we implement monitoring and notifications for the data streams consumed by the Facility Locator? 

## Goal
Minimize impact of data disruptions on Veterans
Identify opportunities to improve performance

## Tasks 
Update serializer to FastJSON for faster object serialization
Get monitoring working so we know when PPMS is down / slow
Get Alerting working for PPMS downtime / slow responses

## Plan
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)
- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
- [ ]  **[Discover] IA Request** - #(ticket)
- [ ] **[Discover] Analytics Request** - #(ticket)
- [ ] **[Build] Contact Center Review** - #(ticket)
- [ ] **[Build] Privacy/Security Review** - #(ticket)
- [ ] **[Build] Pre-Staging Review activities**
  - [ ] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=staging-review-accessibility-checklist.md&title=%3CInitiative%3E+x+Staging+Accessibility+Checklist) - #(ticket)
  - [ ] Compile QA test cases - #(ticket)
  - [ ] Release plan - #(ticket)
  - [ ] Submit QA test plan request - #(ticket)
- [ ] **[Build] Staging Review** - #(ticket)
  - [ ] Resolve Staging Review findings - #(tickets)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
  - [ ] Complete accessibility checklist in Prod - #(ticket if necessary)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Convert to an Epic**  
- [ ] **Labeled with Team**

**Comment by davidmpickett** [comment]
all issues complete
