### ISSUE TITLE
[ANALYTICS] Create "NEW" Health Services content Template for "HS LIST & PLAYBOOK"  [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10881]
## User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 8 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Update Playbook and List of HS, so it better fits the new model in CMS Facility Health Services and .csv files moving forward

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Playbook templates](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: See below list of Stories
- [x] Change Facility information to reflect what the PAO will need to validate the fields in the NEW Facility pages moving forward
- [x] Provide a single list of Health Service common conditions instead of using it on every page
- [x] Work in conjunction with new DATABASE that will output a A-Z to 95 Health Service Cross reference table and import that into the Fields.
- [x] Create two excel tabs that will auto generate the data needed for the final two .csv files for upload into CMS

## Definition of Done 
- [x] New Playbook that has related fields to CMS
- [x] New Lists that can be pulled down by DB and populated into Excel
- [x] New tabs that will pull data over from all tabs with simple changes of scope and auto populate required fields for .csv file
- [x] Process document to help analysts walk through the steps to complete the playbooks.
