### ISSUE TITLE
Refine Styling in Tables for View Payment History

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10889]
## Goal
There are some minor changes that need to be implemented for the View Payments' tables.

## Tasks
- [ ] Implement the items as shown below, breaking them into individual tickets as needed.

## Changes
**Simple Responsive List Table**
- All caps should be upper lower
- "Displaying page 1 - 5 of 12" should be in Bitter (Regular 20 px) typeface, not Source Sans
- Need a horizontal rule under "Display..." text

**Borderless Table**
- ~Icons for sorting are showing (arrows)~
- "Displaying page 1 - 5 of 12" should be in Bitter (Regular 20 px) typeface, not Source Sans
- `<td>` should be vertical align top
  - Payment amount ($4,321), and Account (1234567890) should be top aligned  
- `<th>` should be vertical align bottom
  - Column headers should be aligned to the bottom in case they ever go to two lines or something

Example
![EBN-tables_v3](https://user-images.githubusercontent.com/53826255/86409073-2f189080-bc86-11ea-8765-955986daec1b.jpg)

## Acceptance Criteria
- [x] All caps are no upper case/ lower case
- [x] Display text is in Bitter typeface and 20 px for borderless table
- [x] Display text is in Bitter typeface and 20 px for responsive table list
- [x] A horizontal rule under "Display..." text is shown
- [x] `<td>` is vertically top aligned
- [x] Payment amount is top aligned
- [x] Account number is top aligned
- [x] `<th>` is vertically bottom aligned
- [x] Column headers are vertically bottom aligned
