### ISSUE TITLE
Migrate maintenance/homepage banners into Formation

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#10885]
To add governance and guidelines, we'd like to document the homepage and maintenance banners on www.va.gov through design.va.gov. Currently, the banners are stored in the frontend repo, vets-website, so the styles can't be used on design.va.gov. So, we need to port the banner styles from vets-website into [Formation](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools). This way a new section be added onto https://design.va.gov/components/ for the maintenance banner.

### Tasks
- [x] update class names to reflect design system
- [x] merge code into Formation
- [x] update npm module 
- [x] delete old vets-website code and update npm module
- [x] update tests

### Acceptance criteria
- Banner styles and component are available through Formation (design system) 

---
### questions
- How is this different from other banners? 
  - homepage emergency banner (OPIA) vs. sitewide downtime banner in Design System (which is this ticket)

**Comment by MickinSahni** [comment]
2020-07-10 Standup
Question: how best to name the component going into Formation?
Consideration: style between home page and maintenance banner are the same
Answer: <conclusion documented here cc @ncksllvn>
Update: met with Ryan T. this morning, likely to have follow-up

**Comment by kelsonic** [comment]
PRs are up for this ticket! 🙂 

`vets-website` updates: https://github.com/department-of-veterans-affairs/vets-website/pull/13474

`formation` and `formation-react` updates: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/329

**Comment by MickinSahni** [comment]
Waiting for design system council's go-ahead, added a blocker label.

**Comment by MickinSahni** [comment]
moving out of blocked and resolving a npm issue

**Comment by MickinSahni** [comment]
double-checking design system docs are updated as well

**Comment by kelsonic** [comment]
Emergency Banner: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/emergencybanner/

Maintenance Banner: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/maintenancebanner/

You'll notice the Emergency Banner is rendering `[Object object]` but that's just due to the documentation site, sending up a PR for this now 🙂 https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/352
