### ISSUE TITLE
Express Care - v1 - Veteran only registered at 1 VAMC

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10899]
As a Veteran who is registered at one VAMC and that facility has Express Care enabled and available today, I will be able to request an express care appointment in VAOS. 

## Acceptance Criteria:
- [ ] Veteran sees Express Care request option on VAOS appointments homepage when they log in
- [ ] If Veteran chooses to use Express Care, they will be prompted with "How EC works" description and emergency alert. If Veteran chooses to 'continue' Veteran taken to 'reason for EC request' page
- [ ] To make make an EC request, Veteran must select from 'approved' conditions list and is able to provide description with request
- [ ] Veteran will see different status for request based on its evolution in SM
- [ ] Veteran can Cancel EC request up until it's escalated, and Canceled EC requests will display even if appointment is for today
- [ ] Veteran will see Completed EC requests once request has 'resolved' status
- [ ] Veteran can navigate directly into new VAOS EC flow from other VA websites (specific VAMC site or MHV)

## Notes about this v1.0.0:
- [ ] If 2+ sites have EC enabled at the same time and Veteran is registered at both sites, currently v1 accounts for this by defaulting to first available facility with EC enabled. (First available means = first express care enabled facility we get back from the database)

## Prototype of EC v1 here: 
https://vsateams.invisionapp.com/share/BVY4QCOJM4U#/screens/425790746

## Tasks:
- [x] Need mock for EC prompt on appts homepage
- [x] Need mock for EC inactive prompt on appts homepage
- [x] Need mock screen for 'emergency'
- [x] Need mock screen for explaining EC and steps to use
- [x] Need mock screen for selecting EC conditions and submitting request
- [x] Need (potentially) mock for 'Confirmed' EC appointments
