### ISSUE TITLE
IA/content strategy for consolidating pages within Disability How to File section

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10896]
## Issue Description
We want to reassess the disability how to file section to look at whether we can:

- Bring the "When to file" information into the main "How to file" page. This would eliminate "When to file" and bring "Predischarge claim" up a level.
- Bring the "File while overseas" page up into "Predischarge claim" to eliminate the deepest level in this section.

---
## Tasks
- [x] Audit and assess pages (Mikki and Danielle)
- [x] Rework content into working draft for further IA/content strategy discussion (Danielle)
- [x] Finalize approach and recommendations (Mikki and Danielle)

## Acceptance Criteria
- [x] Finalized approach to IA/content strategy in this section
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis Rough draft of content reconfiguration for these pages. Let's set up a time to discuss next week. Thanks!

[Consolidating Disability how to file and BDD sections](https://app.zenhub.com/files/133843125/ad0adaad-e4a4-4959-b242-161246391c7c/download)

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA  It is my understanding, that with the launch of the BDD claim, there will no longer be any claims filed on eBenefits, all will be filed via va.gov.   Given this, I recommend a couple of additional things:
1. A review of all "How to file" pages to ensure we no longer reference utilizing eBenefits to claim.  I think we are good here, but may not hurt to do a check. 
2. Retire legacy page [FDC walkthrough](https://www.benefits.va.gov/FDC/walkthrough.asp) - this page is literally a walkthrough of the eBenefits experience with screenshots, which will not exist once BDD is launched.  This should be redirected to the "How to apply" page. 
3. Retire legacy page [FDC checklist](https://www.benefits.va.gov/FDC/checklist.asp) - this is really a version of our Fully Developed Claim page, so I scanned through it for parity and everything seems to be covered with the exception of some content at the very bottom that tells users to scan their files in ahead of time and potentially in small batches. I'm not sure if we want to prepare people to do that before they start, or if we are assuming everyone has their documents electronically already.

**Comment by mnorthuis** [comment]
Based on the changes detailed above, the structure of the "How to file" section changes as shown:

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/7ac274b9-89bf-416a-b73f-02ba12e4b3f2)

**Comment by mnorthuis** [comment]
FYI, Final IA based on the above is here:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-benefits-at-discharge.md

**Comment by mnorthuis** [comment]
Updated the IA info based on follow up conversations around what work is needed to best support the BDD launch and what can be postponed.  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-benefits-at-discharge.md
