### ISSUE TITLE
Remove NewRelic instrumentation

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#10924]
With DataDog on the horizon *and* with NewRelic no longer offering us even the free tier of service, its time to remove the bits and pieces of code added to support the NewRelic integration:

Vets-api
- [x] NewRelic gem department-of-veterans-affairs/vets-api#4484
- [x] newrelic.yml file department-of-veterans-affairs/vets-api#4484

Devops
- [x] Deploy configuration for staging (devops repo) department-of-veterans-affairs/devops#7217
- [x] Deploy configuration for production (devops repo) department-of-veterans-affairs/devops#7217 
- [x] credstash license removal

Config
- [x] Disable NewRelic account

**Comment by johnpaulashenfelter** [comment]
$ credstash delete vets_api.newrelic.license
Deleting vets_api.newrelic.license -- version 0000000000000000001
$ credstash get vets_api.newrelic.license
Item {'name': 'vets_api.newrelic.license'} couldn't be found.

**Comment by johnpaulashenfelter** [comment]
Deleted all users and apps.
