### ISSUE TITLE
Update Fry Scholarship figure on Education Benefits for Survivors and Benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#10936]
## User Story
As a Veteran I need to know the most up-to-date figures for the Fry Scholarship tuition.

## Issue Description
Per stakeholder Tammy Hurley's request, we need to update the Fry Scholarship tuition amount on this page: https://www.va.gov/education/survivor-dependent-benefits/

The correct amount is now **$25,162.14**. 

![Screen Shot 2020-07-06 at 6.43.37 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ad7ad610-3c14-4b0d-be5e-7428de666061) 
---
## Tasks
- [x] Update amount in chart to $25,162.14. (Laura)
- [x] Proofread change (Randi)
- [x] Publish page (Randi)
- [x] Validate change on live site (Randi/Beth)
- [ ] Email stakeholder that page is live (Beth)

## Acceptance Criteria
- [x] Correct figure of $25,162.14 showing on live page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@lwalsh617 Please make this change so we can publish the page by tomorrow's (7/7) deploy. Thanks!

**Comment by lwalsh617** [comment]
@RLHecht @bethpotts -- I made the change to the table. Also, just to make sure I wasn't supposed to change it elsewhere, I did a search in Drupal and on the live site. The only other place that the old figure ($23,671.94) appears is on a legacy page referring to 2018 rates, so I think we're good. 
Here's the Drupal preview link: http://preview-prod.vfs.va.gov/preview?nodeId=984

**Comment by RLHecht** [comment]
Thanks, @lwalsh617! This page is now published and moved to validate. I'll close after today's deploy. FYSA @bethpottsVADEPO @MickinSahni

**Comment by RLHecht** [comment]
This has been validated on the live site. @bethpotts can you please let Tammy know? Thanks! Closing ticket. FYSA @MickinSahni
