### ISSUE TITLE
Updates to Special Monthly Compensation rates - 2020 and 2019 historic

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10934]
# Issue description
When cloning the 2020 Special Monthly Compensation rates page, we discovered that one number in the table was incorrect. We need to input the new figure and publish the page. 

# Tasks

- [x] Asked stakeholders to review numbers for the N/2, Veteran + 1 parent + 1 spouse + 1 child for 2018, 2019, and 2020. Anne asked Elana
- [x] Received correct numbers 7/6. Anne
- [x] Change number on 2018 rates on its separate ticket #10450, Anne
- [x] Change 2019 and 2020 with correct numbers. Anne
- [x] Copyedit and review. Randi.
- [x] Publish 2020 rates page (Randi)

- [x] Validate 2020 rates page on live site (Anne/Randi)

# Acceptance criteria

- [x] 2020 Special monthly compensation rate page is published with new correct figure
- [x] New correct figures are put into 2018 and 2019 historic rates pages and showing in Drupal preview

**Comment by AnneHurley** [comment]
Note this ticket arose when creating 2018 historic rates, #10450 .

**Comment by AnneHurley** [comment]
2019 N 1/2, Veteran, 1 child, 1 parent, 1 spouse: $5,575.47
2020 N 1/2 Veteran, 1 child, 1 parent, 1 spouse:

**Comment by RLHecht** [comment]
@AnneHurley these have both been reviewed and OK. I published the 2020 one last night with the correct number (without the links to our new historical pages).

**Comment by RLHecht** [comment]
@AnneHurley I updated this ticket to reflect that work is completed once we publish the fix for the 2020 page and the 2018 and 2019 work will be finished with ticket #11171. Please validate that the correct number is on the live site as well as check the acceptance criteria before closing out this ticket. FYSA @MickinSahni

**Comment by AnneHurley** [comment]
@RLHecht Numbers are updated and correct, but I added a new sentence to the subway map to be clear about which table we are pulling the example numbers from. That needs to be verified and I can do that w you in the morning.

**Comment by RLHecht** [comment]
This work is now all complete. Closing ticket. FYSA @MickinSahni
