### ISSUE TITLE
OS-Check job likely needs improvement on the task that grabs instances to be listed

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#10947]
## Description
The OS-Check job(s) likely need a round of improvement. Specifically, the task that alerts on detached instances. It currently detects instances that are detached from an ASG and older than 7 days. However, it compiles a list of instances based on the "Name" tag key and that value was set to `*-asg`. We recently added to this to make it `*-asg*` in order to catch detached instances with altered names. This may still not be good enough to always catch these particular instances as it still relies on "-asg" being part of the name of the instance.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
A small pull request was created to wildcard the end of the tag to catch instances that were detached and users perhaps added an identifier to the end of the name (i.e. foo-asg-JBRITT-TESTING). This could still be improved to perhaps filter by subnets or something besides the naming of the instance(s).

---
## Tasks
- [ ] Come up with a recommendation on how these should be handled - Research needed 
- [ ] We should be looking to implement a solution that will not miss instances in the future due to a naming change. We should be aware of all older instances so they are not forgotten and we are not continuing to pay for / run them so that we may be more cost-efficient. 

## Definition of Done
- [ ] Solution implemented that ensures we catch ALL instances detached from an ASG that are over a week old, regardless of naming convention. 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic
