### ISSUE TITLE
DLC Production API Integration

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#10941]
## Issue Description
Need to configure some things in devops repo in preparation for the DLC prod integration.

---
## Tasks
- [x] Setup `fwdproxy` to connect to the DLC Production API
- [x] Add the `fwdproxy` to the `settings.yml` file so that vets-api can make the connection.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
