### ISSUE TITLE
Adding contextual headers to introduce options for returning documents

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#10944]
## User Story
As a user going through the process of submitting a form, application or other document, I need to clearly understand that I can select one of several options for submission (by mail, fax or in peson). I also need to quickly understand when I'm being presented with an address where I can mail a specific document, such as a compensation claim. 

If I'm a non-sighted user relying on a screenreader, it's crucial that I hear this information read as a list of several options I can select from. (Currently, the information can be misinterpreted, leading me to believe I must mail the form which can be a burdensome task for non-sighted Veterans.)

## Issue Description
Currently, we do not always utilize a header such as, "Submit your application by mail, in person, or by fax," to tee up the various options a user can choose from. 
In addition, we use the header "Compensation" above the address, which is less clear than language such as "Mail compensation claims to..." 

---
## Tasks
- [ ] _PW provides recommendations in the form of screenshots of numerous occurrences along with call-outs of proposed language. (Goal is to have language that can be used universally while also providing context.)
- [ ] _PW populates checklist below of all pages where changes will be made 
- [ ] _DEPO reviews recommendations and provides feedback/final language
- [ ] _PW implements final language in 3-5 sample occurrences for SME review
- [ ] _DEPO presents sample occurrences to SMEs
- [ ] _DEPO provides PW with SME feedback and/or final approval to implement
- [ ] _PW content team member begins implementation, providing Drupal preview links
- [ ] _PW copy editor reviews preview links
- [ ] _PW publishes updates

## Acceptance Criteria
New copy appears on live site on the following pages.
CHECKLIST TBD

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@lwalsh617 Here are the 2 pages I was talking about on our call:

http://preview-prod.vfs.va.gov/preview?nodeId=5681

http://preview-prod.vfs.va.gov/preview?nodeId=36
