### ISSUE TITLE
Learning center x Collab Cycle Plan

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10953]
## Product Outline
[Learning center templates MVP product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)

### 1.0
- [x] [Define] Kickoff-Intent - We had a PW + CMS project kickoff.
- [x] [Define] Design intent 
  - [Ticket: #10955 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10955)
  -  Asynch review for step-by-step #13626 (completed 9/22)
  -  Asynch review for responsive tables #13825 
- [x] [Discover] Usability Testing Prep - Ticket #10965 
- [x] [Discover] Research Plan Review - usability test submitted to Lauren on 7/16
- [x] Contextual inquiry research study - IRIS authors 
- [x]  [Discover] IA Request  [Ticket #14445](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14445)
- [x] 1.0 BUILD COMPLETE (ALL 1.0 LAYERS) - **~10/12**
- [x] INTERNAL QA 
  - [X] **SPIN UP SEPARATE QA [DEMO ENVIRONMENT](http://learningcenter.demo.ci.cms.va.gov/admin/content/learning-center)**
  - [x] VALIDATE - [Link any bug tickets to LC bugs epic #15270](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15270undefined)
- [X] EXTERNAL QA REQUEST [#14582](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14582)
- [x]  Analytics Request 
  - VSP REQUEST https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196
  - TBD PW INTERNAL ANALYTICS WORK - #ticket #14408 
- [x] [Build] Contact Center Review  - [Ticket #14966 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14966)
  - [Product Guide ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/resources-and-support-product-guide.pdf)
- [x] **[Build] Pre-Staging Review activities**
  - [x] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=staging-review-accessibility-checklist.md&title=%3CInitiative%3E+x+Staging+Accessibility+Checklist) - [14774](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14774)
  - [x] [Compile QA test cases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=product-use-cases.md&title=%3CProduct%2FInitiative%3E+Use+Cases) - #11581
  - [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=product-release-plan.md&title=%3Cproduct%2Finitiative%2Ffeature%3E+x+Release+plan) - [#14415](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14415)
  - [x] Request QA test plan - #14582
- [x] **Beta launch LC 1.0 - DRUPAL DEMO SITE - DATE: Oct 23 -28**
- [x] **Beta launch LC 1.0 - PROD VA.GOV - DATE: Oct 29 - Nov. 5**
- [x] SEARCH.GOV STARTS INDEXING - #epic-ticket
- [x] **Launch LC 1.0 - PROD VA.GOV - SEARCH - DATE**

### 1.1
- [x] [Build] Staging Review [ all of these templates will be built in Drupal cms.prod environment] - #ticket

### Icebox
- [ ] [Validate] Launch Full A11y Review - **of all 2020 LC (1.0 + 1.1)** bc content addition will be ongoing 
- [ ] [Validate] Post-launch checkin
- [ ] [Build] Privacy/Security Review

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)

## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of? [MVP mini learning center w/VA.gov account topic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10111)
- [x] **Labeled with Team**  

* HIGH LEVEL PROCESS
  1. CMS CREATES COMPONENTS
  1. RANDI ADDS SAMPLE CONTENT TO PROD
  1. RANDI COPIES ALL CONTENT INTO DEMO
  1. BATCH PUBLISH IN DEMO AND CONTENT RELEASE
  1. VALIDATE FE IN DEMO

**Comment by mnorthuis** [comment]
@jenniferlee-dsva I know you did a kick-off with the CMS team, but the VSP team wasn't there for that.  It may be difficult for them to come into the design intent or other VSP meetings without any background info on the LC.

**Comment by jenniferlee-dsva** [comment]
I'm happy to provide them with the same overview - their ticket says we don't need to provide a presentation though.

**Comment by mnorthuis** [comment]
Presentations for kick-offs are definitely not necessary, usually its just a run through of the product outline at a high level so the team has background, which is really helpful to getting up to speed on the whats and whys. 

Given the design intent is scheduled for Friday, I went ahead and gave the VSP team a VERY high level overview of what the LC is so they have some information coming in on Friday.   I couldn't answer many of their questions, but its something.

**Comment by jenniferlee-dsva** [comment]
@brianalloyd - I added approximate dates, working backward from the desired prod beta launch date. See ^. 

If you haven't started the release plan, I'll start a draft, but would really love for you to own delivery of the launch plan. 

Updated above: 
- [ ] **Beta launch LC 1.0 - DRUPAL DEMO SITE - DATE: Oct 23 -28**
- [ ] **Beta launch LC 1.0 - PROD VA.GOV - DATE: Oct 29 - Nov. 5**

**Comment by jenniferlee-dsva** [comment]
Contact center request submitted with completed product guide per Chante's guidance: #14966

**Comment by jenniferlee-dsva** [comment]
Most steps completed **but still pending:** 

1. Analytics implementation
2. Submitting RS for indexing
3. Linking to RS from footer

**Comment by jilladams** [comment]
Learning Centers are launched, and no open follow up items apart from #11143 which appears to be addressed & has been inactive for 2.5 years. Closing epic.
