### ISSUE TITLE
Usability Testing Prep [learning center MVP template]

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10965]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt @ Mandi Lipka
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)
- [Template content requirements - FE and CMS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md)
- [Mural mockups](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
- [Epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10111)
- [Prototype](https://vsateams.invisionapp.com/share/YJXZTKC6CN4)
- ~Link to or attach artifact with copy (if separate from prototypes/mockups)~
- Research plan and script in [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research)
- ~Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_~
- ~Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_~

## Meeting attendees from **Public Website team**
- Product Manager (required): ** @MickinSahni (interim) - Please include @jenniferlee-dsva for continuity**
- DEPO product lead (required): ** @jenniferlee-dsva **
- Anyone else from your team who significantly contributed to the artifacts provided (required): ** @andaleliz, research lead**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
  - **Preferred time slot 7/23 @ 1:30 EST**
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by jenniferlee-dsva** [comment]
@andreahewitt-odd @meganhkelley - no need to respond yet on this. Still filling out all the artifiacts part.

**Comment by jenniferlee-dsva** [comment]
@andaleliz - placeholder ticket for usability test prep. Let's sync offline re ETA.

**Comment by andaleliz** [comment]
Pinged VSP in slack to request meeting, sent placeholder meeting to @MickinSahni and @jenniferlee-dsva

**Comment by jenniferlee-dsva** [comment]
This is all filled out and @andaleliz has submitted research plan to Lauren for review. Is there any other steps that PW team needs to take on this ticket @andreahewitt-odd / @meganhkelley ?

**Comment by pjhill** [comment]
@andaleliz and @jenniferlee-dsva 

I noticed that the QA artifacts have been struck through for this collaboration point.  It's my understanding that Learning Center is a new product, so regression tests are likely irrelevant, but an overall test plan and load testing preparation should still be possible. What is the rationale for striking through the QA artifacts?

**Comment by andaleliz** [comment]
Hey @pjhill, I'm writing to acknowledge that I saw your comment, but I don't have the answer. I didn't strike that out. @jenniferlee-dsva can likely speak to that.  

Also commenting here that I just realized the designer, @rtwell, wasn't listed as an attendee. I'm going to forward the invite to him since he significantly contributed to the artifacts provided and he wants to / is able to attend.

**Comment by pjhill** [comment]
@andaleliz -- Understood, since we don't have QA artifacts to review at this time, VSP will not be able to provide feedback regarding quality assurance efforts for this meeting.

**Comment by jenniferlee-dsva** [comment]
I believe this is an old ticket that's completed. We are doing QA as part of the Demo, not during usability. (Demo QA in flight now in fact.)
