### ISSUE TITLE
Remove references to fax numbers and fax numbers on 3 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#10971]
## Issue Description
Per stakeholder Sandy Tadeo's request, we need to remove the fax numbers and any reference to faxing on three of VA.gov's pages:
- https://www.va.gov/pension/pension-management-centers/
- https://www.va.gov/decision-reviews/supplemental-claim/
- https://www.va.gov/disability/add-remove-dependent/

Sandy did the edits in Drupal; they just need to be reviewed and published.

## Tasks
- [x] Review Sandy's edits to three pages listed above in Drupal (Randi)
- [x] Publish page (Randi)
- [x] Notify stakeholder that page will go live (Beth/Randi)
- [x] Validate page on live site (Beth/Randi)

## Acceptance Criteria
- [x] Fax numbers are removed on pages on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
Created this ticket after the changes were made so we could track the work. I'll close ticket once validated on live site. FYSA @MickinSahni

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @bethpottsVADEPO @MickinSahni
