### ISSUE TITLE
Revamp Implementation of Facility Locator Search Tracking - Convert to Events

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#10987]
# Google Analytics Implementation

## Description
- We would to refactor our current implementation of facility locator search tracking -- currently, we are tracking according to user timing, we would like to refactor this to be events
- We are currently suspect to a GA limitation on user timing functionality that samples the search volume we can collect up to 1% of total pageviews -- [see resource here](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings#limiting_the_number_of_hits_sent). 
- Making this change will inherently give us all accurate unsampled search data and flexible reporting to tailor more specifically to their insights

- Who is this request for?

    - `Michelle Middaugh` -- recommendation for improvement by Analytics & Insights team
- What team/project is this work for?
    _Facility Locator_
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _PII includes specific address components passed in search box_
    
## Acceptance Criteria
- [ ] Facility locator searches are now captured as events rather than user timing tags
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
### Notes from Pointing Session
1) Establish a DL (containing no PII)
  > Jon to reach out to Michelle on scheduling
  > Connect with developers on opportunities for pushing map data into DL
- Convert existing user timing tracking to event tracking
- Maintain the current dropdown and timing components we're capturing today
- Increment a total count custom metrics for each search
- Replace chart on Facility Locator KPI dashboard with new event taxonomy

**Comment by jonwehausen** [comment]
## DataLayer Specification - Work in Progress

@mmiddaugh / @brangi / @mpelzsherman - Want to thank you all again for your time on monday. 

This comment is a drafted dataLayer specification to track some of the various components we had discussed from Monday. This is a work in progress as we comb through and refine the structure. 

### On Search
- We currently have an existing event `fl-search-results` being pushed to the dataLayer with each search. 
- We would like to propose the addition of the following dataLayer variables with that search event to be included to unveil and enhance our insight
- Please see each variables name with its intended purpose / data to store

DataLayer Variable | Example Value | Description
------------ | ------------- | ------------- 
`'fl-facility-type-filter'` | `'VA health'` | The facility type the user used to filter on search, `undefined` if not used
`'fl-service-type-filter'` | `'Primary Care'` | The service type the user used to filter on search, `undefined` if not used
`'fl-allowed-location'` | `true` `//false` | if the user used the allow location functionality to auto-search, `true` if so, `false` if not
`'fl-results-returned'` | `true` `//false` | `true` if the search returned ANY results, `false` if no results returned
`'fl-total-number-of-results'` | `101` | Contains the full number of results returned ,
`'fl-total-number-of-result-pages'` | `5` | Stores the total number of result pages returned for the search
`'fl-zip-code'` | `'55555'` | Contains the zip code of the search IF the user's search had a zip code, otherwise used `undefined`,
`'fl-city'` | `'seattle'` | Contains the city of the search IF the user's search had a city, otherwise `undefined`,
`'fl-state'` | `'washington'` | Contains the state of the search IF the user's search had a state, otherwise `undefined` 
`'fl-country'` | `'united states of america'` | Contains the country of the search IF the user's search had a country, otherwise `undefined`
`'fl-closest-result-distance-miles'` | `32.4` | Stores the top result's distance
`'fl-time-to-return-results'` | `4023 //in milliseconds` | Stores the total time taken to return the search results <br> We do currently have a GTM-only solution for this, however, if a relatively low lift to get within the DL, we would like to repurpose to push with this event  

### Clicks on Map Pin Clicks & Letter 
Event / DataLayer Variable | Example Value | Description
------------ | ------------- | -------------
`'event'` | `'fl-map-pin-click'` | Event push with each map pin-specific click
`'fl-facility-type'` | `'VA Health'` | Facility type of the facility clicked
`'fl-facility-classification'` | `'VAMC'` | Classification of facility clicked on
`'fl-facility-id'` | `'vha_688'` | Facility ID of facility clicked on
`'fl-facility-facility-name'` | `'Charlotte Hall VA Clinic'` | Facility name of facility clicked on
`'fl-facility-distance-from-search'` | `32.4` | Distance of facility clicked on from search params

### Clicks to Zoom In/Out on Map
Event / DataLayer Variable | Example Value | Description
------------ | ------------- | -------------
`'event'` | `'fl-map-zoom-in' //or 'fl-map-zoom-out'` consistently this value for each interaction type | Event push with zoom ins and zoom outs

### Clicks on Search Result Facilities
Event / DataLayer Variable | Example Value | Description
------------ | ------------- | -------------
 `'event': 'fl-results-click'` | consistently this value | Event push on ANY search result click
 `'fl-facility-name'` | `'Charlotte Hall VA Clinic'` | Store the name of the facility 
 `'fl-facility-type'` | `'VA Health'` | Store the type of facility 
 `'fl-facility-id'` | `'vha_688GD'` | Store the facility ID 
 `'fl-facility-classification'` | `'Primary Care CBOC'` | Store classification of facility
 `'fl-result-page-number'` | `4 //if on the 4th result page` | Store the result page number user is currently on (pagination number)
 `'fl-result-position'` | `5 //if the 5th result on the page` | Store the search result position in the list 

Outstanding / Follow-up Questions: 
- @brangi / @mpelzsherman Please let us know if there is anything in each of these items that will be a more difficult lift to surface or you have any other clarifying questions with
- @bsmartin-ep @bmcgrady-ep when one of you has some free time -- if you could take a look at this and let me know any adjustments / improvements you see or items I potentially missed that we should include

**Comment by jonwehausen** [comment]
### Follow-up and Spec Adjustments

@mmiddaugh @mpelzsherman @brangi @joanneesteban Thank you again all for your time today. As a follow-up to some of the adjustments / enhancements we discussed, please see the below notes: 

### On Search - @brangi & @mpelzsherman 
- Understanding this is going to take a few different iterations of dataLayer work, and trying to cut-down on parse-out code necessary -- we can begin with the approach of taking and utilizing (_what we can_) of what the API gives us directly in its raw unstructured nature. We can cleanse the data on our side in accordance with PII best practices for Google Analytics. 
- Leveraging [this documentation](https://docs.mapbox.com/api/search/#geocoding-response-object), the fields we can use to start with are `query`, `place_type`, and `place_name` for the response returned that is most relevant according to Mapbox (**_top result with a `relevance` of closest to 1_**). 
- **We can ignore the original variables [from above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10987#issuecomment-658822435) for each itemized (i.e `fl-city`) address piece specifically in lieu of this format below.** 

DataLayer Variable | API Value | Example Screenshot
------------ | ------------- | ------------- 
`'fl-searched-query'` | `"query"` | ![image](https://user-images.githubusercontent.com/48527022/88317091-c8b3ea80-cce6-11ea-84e5-c08153f0295d.png)
`'fl-mapbox-returned-place-type'` | `"place_type"` | ![image](https://user-images.githubusercontent.com/48527022/88317176-e7b27c80-cce6-11ea-8444-a03fb4f1e368.png)
`'fl-mapbox-returned-place-name'` | `"place_name"` | ![image](https://user-images.githubusercontent.com/48527022/88317273-0b75c280-cce7-11ea-9344-c26e4a8889c9.png)


### On Tracking Map (Double Click or Hand Click-and-Drag) Movements 
- It looks like the map does indeed render a new search with even the smallest of mouse movement or double click, so in order to normalize this data and increase data quality & meaning -- **We could try to set a threshold value the map must be moved from point A to point B (i.e previous coordinate or searched location to newly moved coordinate) before we write the code to record the dataLayer `'event'`. @mmiddaugh we would of course leave it up to you for what that threshold should be and priority for writing the logic to ** Perhaps a miles threshold? 
- It may be helpful to capture at time of map move search completion the user's zoom depth at this point as well to understand proximity, view and overall scale of what the user is actually seeing on the map as well -- that could give us a better sense at time of insight of it perhaps made sense for that user to use the map based on how much they were zoomed in. This also gives us a better way to understand mobile users who naturally have smaller real estate to work with and zoom more often. Interested to hear @brangi and @mpelzsherman your feedback on this, open to your suggestion. 
- For each map movement of significant threshold, **we can push the event `fl-map-movement-search`, along with the following variables:** 

DataLayer Variable |  Example Value
------------ | ------------- 
`'fl-map-miles-moved'` | `'300 miles` `//output of point A to point B calculation`  <br> _open for discussion based on what's available, whether qualitative or quantitative_ 
`'fl-map-zoom-depth'`  | `'<current_zoom_depth>'`<br> _also open for discussion based on what's available, whether qualitative or quantitative_ 

### Follow-up Items to consider - @mmiddaugh 
- We can add/remove variables that are unneccessary or don't feel like they provide additional value and help reduce scope / testing etc. 
- Certainly open to your teams priorities and scheduling for how we want to structure the timeline: 
  - Perhaps we try to do the search results returned spec and the search result clicks during 1 sprint and the map movements and zoom interactions during another. What are your thoughts there? Happy to break-out into separate issues as well. 
- Last Question: Could you all provide for us any further documentation you all may have on your planned upcoming auto-complete type search functionality?

**Comment by jonwehausen** [comment]
ccing @bsmartin-ep and @bmcgrady-ep for visibility.

**Comment by mmiddaugh** [comment]
@jonwehausen @brangi @mpelzsherman for what it's worth, I spoke with Dave about the 'fl-facility-classification' and there may be value to this data in the future. 

I'll tag this with our "needs-grooming" label so we can start thinking about how to break this apart and prioritize.

**Comment by mmiddaugh** [comment]
@jonwehausen here is more info on the [Predictive GeoLocation discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/PredictiveGeolocation.md). Please note we haven't defined our next steps or timeline yet.

**Comment by jonwehausen** [comment]
Thank you for this @mmiddaugh we will take a look at this! 

Also appreciate you asking about the classification data. 

We are free to work at your teams pace & priorities from this point forward.

**Comment by jonwehausen** [comment]
### Next Steps
- @bmcgrady-ep to perform QA + documentation of dataLayer
- @bsmartin-ep to stage GTM implementation of dataLayer specification + determine areas where hit volume should be mitigated prior to tag testing

**Comment by jonwehausen** [comment]
## QA
ccing you both here: @brangi @mpelzsherman 

### On Search
Description of Interaction | Data Layer Screenshot | Test Status | Notes
------------ | ------------- | -------------  | ------------- 
Search performed | ![image](https://user-images.githubusercontent.com/48527022/93813389-0cf93380-fc21-11ea-9286-790f969bfcea.png) | ❌ **DOES NOT PASS** | • Similar to how the correction on the `fl-map-pin-click` event causing multiple messages, each of these separate messages containing Data layer variables should all be sent with the `fl-search-results` event <br><br> • Once we get this corrected we can take a more thorough look at the Data Layer as in the examples below

### On Search Results Click
Description of Interaction | Data Layer Screenshot | Test Status | Notes
------------ | ------------- | -------------  | ------------- 
Click on **first** search result in results list | ![image](https://user-images.githubusercontent.com/48527022/93815146-8560f400-fc23-11ea-82c8-15b2594384bf.png) | ✔️ **PASS** | N/A
Click on **third** result on **first** page of search results list | ![image](https://user-images.githubusercontent.com/48527022/93816150-213f2f80-fc25-11ea-8289-8a2d345f983d.png) | ✔️ **PASS** | N/A


### Map Pin Click
Description of Interaction | Data Layer Screenshot | Test Status | Notes
------------ | ------------- | -------------  | ------------- 
Click on 'E' in map | ![image](https://user-images.githubusercontent.com/48527022/93817909-9f043a80-fc27-11ea-9890-de950361add8.png) | ✔️ **PASS** | N/A

### Map Zoom In/Out
- Per @mpelzsherman [comment here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12137#issuecomment-689140397), perhaps a better approach to help conserve GA hit volume is to include both `'fl-map-miles-moved'` and something like `'fl-current-zoom-depth'` along with the event `fl-search` to conserve traffic volume

Description of Interaction | Data Layer Screenshot | Test Status | Notes
------------ | ------------- | -------------  | ------------- 
Zoom In | ![image](https://user-images.githubusercontent.com/48527022/93819732-1dfa7280-fc2a-11ea-8367-6bcde3b890eb.png) | ❌  **DOES NOT PASS** | • See comment above in this section, consider pivot
Zoom out | ![image](https://user-images.githubusercontent.com/48527022/93820059-97926080-fc2a-11ea-89a4-f6323fe83ee8.png)  | ❌ **DOES NOT PASS** | Same issue as described prior

**Comment by brangi** [comment]
@jonwehausen thank for this feedback. On request.

> ### On Search Results Returned
> Description of Interaction	Data Layer Screenshot	Test Status	Notes
> Search results returned	![image](https://user-images.githubusercontent.com/48527022/93813389-0cf93380-fc21-11ea-9286-790f969bfcea.png)	❌ **DOES NOT PASS**	• Similar to how the correction on the `fl-map-pin-click` event causing multiple messages, each of these separate messages containing Data layer variables should all be sent with the `fl-search-results` event
> 
> • Once we get this corrected we can take a more thorough look at the Data Layer as in the examples below

Would it be possible for you to specify with a screenshot or a list the exact ` messages containing Data layer variables should all be sent ` ?

**Comment by jonwehausen** [comment]
Hi @brangi , 

Here are the full data layer samples of each event..each event should be pushed simultaneously along with their respective variables. All of the variables you see below should be pushed along with the same `recordEvent()` for each interaction. 

From what we could see, the variables were populating with the correct values, but they were all being pushed as separate messages. When these variables are pushed together, it allows us to reference the metadata in accordance with each event to implement tracking. 

### When ALL search results are returned
```javascript
'event': 'fl-search-results',
'fl-facility-type-filter':
'fl-service-type-filter':
'fl-allowed-location':
'fl-results-returned': 
'fl-total-number-of-results':
'fl-total-number-of-result-pages':
'fl-searched-query':
'fl-mapbox-returned-place-type':
'fl-mapbox-returned-place-name':
'fl-closest-result-distance-miles':
'fl-time-to-return-results':
```

### On Map Pin Clicks
```javascript
'event': 'fl-map-pin-click'
'fl-facility-type'
'fl-facility-classification'
'fl-facility-id' | 'vha_688'
'fl-facility-facility-name'
'fl-facility-distance-from-search'
```

### On Search results clicks
```javascript
'event': 'fl-results-click' 
'fl-facility-name' 
'fl-facility-type'
'fl-facility-id'
'fl-facility-classification'
'fl-result-page-number'
'fl-result-position'
```

**Comment by brangi** [comment]
thanks, @jonwehausen, I think it's going to be challenging to gather all those messages for `event': 'fl-search-results',` at the same time, because of the way our API calls are designs (for vetsAPI and then for MapBox). But let me see what I can do.

**Comment by jonwehausen** [comment]
Okay @brangi, thanks for this -- We want to try to conserve our hits but provide as much metadata as we can where we can, keep us posted on the complexity here and if we need to pivot to an alternate solution. Thanks again

**Comment by jonwehausen** [comment]
This is now ready for thorough QA
cc: @bsmartin-ep @bsmartin-ep

**Comment by bsmartin-ep** [comment]
@jonwehausen -

### QA of [this workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000368)

Interaction|Data Layer|Tag|Notes
--|--|--|--
Search|![image](https://user-images.githubusercontent.com/62304138/94872014-72b39f80-0419-11eb-886d-4dcde38665be.png)|![image](https://user-images.githubusercontent.com/62304138/94872392-83184a00-041a-11eb-95bd-e325850cda62.png)
Search Results|![image](https://user-images.githubusercontent.com/62304138/94872794-8bbd5000-041b-11eb-8136-eb042952e061.png)|![image](https://user-images.githubusercontent.com/62304138/94872828-a4c60100-041b-11eb-86a3-a172270467ac.png)|Missing `fl-service-type-filter` and `fl-allowed-location`
Pin Click|![image](https://user-images.githubusercontent.com/62304138/94872670-35501180-041b-11eb-929d-147eb7b2f610.png)|![image](https://user-images.githubusercontent.com/62304138/94872698-48fb7800-041b-11eb-9879-b8e721e0bcb9.png)|Looks like we're missing `fl-facility-id`.  Remove that?
Zoom Out|![image](https://user-images.githubusercontent.com/62304138/94873263-b78d0580-041c-11eb-839f-0da9d47f7086.png)|![image](https://user-images.githubusercontent.com/62304138/94873305-cf648980-041c-11eb-8bc8-6070c48e0df4.png) ![image](https://user-images.githubusercontent.com/62304138/94873439-308c5d00-041d-11eb-9eae-d977073fbc5d.png)
Zoom In|![image](https://user-images.githubusercontent.com/62304138/94873355-ed31ee80-041c-11eb-926b-b54bd1b3ac02.png)|![image](https://user-images.githubusercontent.com/62304138/94873374-fc18a100-041c-11eb-870e-086572a4f724.png) ![image](https://user-images.githubusercontent.com/62304138/94873417-1e122380-041d-11eb-8390-988bc0740f2c.png)
Results Click|![image](https://user-images.githubusercontent.com/62304138/94873513-69c4cd00-041d-11eb-98a9-2bfd2fa357fc.png)|![image](https://user-images.githubusercontent.com/62304138/94873541-7fd28d80-041d-11eb-83f8-f2464c622a98.png)
Map Move|![image](https://user-images.githubusercontent.com/62304138/94873664-cfb15480-041d-11eb-83c6-16f93a80e5bc.png)|![image](https://user-images.githubusercontent.com/62304138/94873687-e2c42480-041d-11eb-8f5a-c5e75cbbd9c9.png) ![image](https://user-images.githubusercontent.com/62304138/94873706-f40d3100-041d-11eb-98e3-2b712a01e4f5.png)

@jonwehausen - would it be possible for the developer to clear the `fl-map-miles-moved` dataLayer variable after it is set?  Otherwise, I'm having trouble differentiating between the regular search and the map move from the dataLayer alone.

**Comment by jonwehausen** [comment]
@brangi Please see @bsmartin-ep comment ⬆️

**Comment by jonwehausen** [comment]
Thanks for doing the QA here, @bsmartin-ep really appreciate it...A couple things here:

1) It would be great if we can have at least a couple days of live data flow into staging to get a taste of volume / data quality before we go live (will probably help identify where we can clean things up further too)
2) This should help also give us an indicator on what type (if any) throttling we need to do

**Comment by mmiddaugh** [comment]
Capturing adjustment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14453)
This issue will be brought into new sprint starting tomorrow (10/7)

**Comment by jonwehausen** [comment]
@mmiddaugh Thank you very much! We appreciate it.

@bsmartin-ep #14453 will include the adjustment you requested -- let's keep an eye on our staging data as this change rolls in.

**Comment by jonwehausen** [comment]
cc: @bsmartin-ep 

This has been published to production as of 10/12 2:20pm EST. 

Let's continue to monitor production utilization.

**Comment by jonwehausen** [comment]
@bsmartin-ep @mmiddaugh closing this implementation ticket per demo last week

Please find ticket to setup the BigQuery view at #15000 

cc: @joanneesteban for visibility
