### ISSUE TITLE
Design intent Collaboration: Comparison Tool Ratings

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#10995]
## Steps to complete Design Intent Collaboration
- [ X ] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> **requesting team** design intent collaboration meeting completed
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/product-outline.md)
- Lo-fi mockups: Includes several views of ratings on search results page for schools and VET TEC, some displaying full-width institution names.  Also includes ratings displays on school profile pages - both in the institution heading and within a "School ratings" accordion which appears lower on the profile pages.
https://bahdigital.invisionapp.com/share/PRIAEG9HDNS

## Meeting attendees from **requesting team**
- Designer(s) (required): **Amy Knox, Cindy Cruz, Jen Jones**
- Product Manager (optional): **Darrell Neel (in absentia)**
- DEPO design lead (required as applicable): **Matt Self**
- Also invite: **Delivery Lead - Will McCormack, Scrummaster - Desiree Turner**

## Scheduling
1:30 PM Thursday, July 16

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by rtwell** [comment]
Please include me in this meeting (Matt Self is the DEPO lead for this project, while I am the DEPO design lead)—thank you!

**Comment by CrystabelReiter** [comment]
Scheduled 1:30 PM Thursday, July 16

**Comment by ccruzgra** [comment]
@emilywaggoner and @CrystabelReiter Here are some initial concepts we've put together: https://bahdigital.invisionapp.com/share/PRIAEG9HDNS

We include several views of the search results page for both IHLs and VET TEC, some displaying full-width institution names, as well as an alternate view of the profile page.

**Comment by amyknox** [comment]
IA Input from Mikki #11347
