### ISSUE TITLE
App Deployment Platform - Implement isolated deployment/"micro frontends"

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#1099]
## Problem Statement 

VFS teams all use the same repository for the FE apps `vets-website`, which means that there are a significant number of interdependencies between more than a dozen teams working in the same repo. For example, when one team's unit test fails, the entire website deploy is blocked.

How might we reduce interdependencies between VFS teams and enable them to work more autonomously?

## Hypothesis or Bet
*How will this initiative impact the quality of VFS or VSP teams' work?*
*How will this initiative be easy for VFS or VSP teams? Or how will it be easier than what they did before?*

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by rianfowler** [comment]
[module federation](https://github.com/sokra/slides/blob/master/content/ModuleFederationWebpack5.md)

**Comment by rianfowler** [comment]
https://rushjs.io/pages/intro/welcome/

**Comment by billfienberg** [comment]
> [module federation](https://github.com/sokra/slides/blob/master/content/ModuleFederationWebpack5.md)

@rianfowler, Module Federation requires Webpack 5, correct? I believe [we're currently on version 4](https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json#L247). Do we have a ticket/plan to [upgrade from Webpack 4 to Webpack 5](https://webpack.js.org/migrate/5/)?

**Comment by rianfowler** [comment]
ticket for upgrading to [webpack 5 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11510)

**Comment by rianfowler** [comment]
These changes should be applied to the VFS Tools repo as well

**Comment by meganhkelley** [comment]
Content build separation: #2719

**Comment by meganhkelley** [comment]
Updating template to current VSP initiative template. Previous contents of ticket body:

# User Story
As a VFS team I want as much independence in building, deploying and testing my application so that my development is now slowed by VSP bottlenecks.

# Hypothesis
- VFS teams are on the platform but they should not be tied directly to the deploy process
- VFS teams making FE changes should be able to build and test without the need for BE code to be involved.

# VSP Q1 + Q2 2020 OKRs 
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

# Pain Points:  
VFS Teams - Build Process is too rigid and not frequent enough to support rapid development and iteration of apps.

# Steps

- [ ] [Separate content and website builds to alleviate dependencies for apps on static content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2719)

## We will know we're done when
- ... ? VFS teams launching w/reduced volume of questions? (for example)

**Comment by meganhkelley** [comment]
Closing in favor of #22335
