### ISSUE TITLE
[Migrate-Data]  Migrate Legacy data for Events, Stories, News Releases Part 1 for VISN-19 to VAMC Legacy website [Content]to VAMC-Upgrade Website page [Data]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11008]
## User Story or Problem Statement
As a Veteran Web user, I need the latest news, stories, and events, so I know what is happening in my local VAMC system.

## Goal
_Highlight one story, event and News Release for each listing page.

## Objectives or Key Results this is meant to further
- _Allow for training opportunity of PAO in each area._
- _Reduce Click through count by_Highlighting top stories._

## Tasks
_Complete Migration of Stories and Media for the following three areas and four Systems in VISN_
* Migrate most recent data, not to exceed 2 years old, and to best fit the Drupal format and highlight the feature story, primary media picture and information.  
* Events
* Story
* News Release
Only ONE 1 on each page for the following sites:
- [x]  VA Cheyenne health care
- [x]  VA Eastern Colorado health care
- [x]  VA Western Colorado (Grand Junction) health care
- [ ]  VA Montana health care

## Acceptance Criteria
Data and media are migrated for  the following areas:
- [ ] Events
- [ ] Story (Featured)
- [ ] News Release
* Media must be saved and reusable in Drupal.
