### ISSUE TITLE
[Epic] CLP x Collab Cycle 

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11004]
## Product Outline
[State of Product / Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/state-of-product.md)

## Plan
- [x] **[Define] Kickoff-Intent** 
- [x] **[Define] Design intent** 
- [x] **[Discover] Usability Testing Prep**
- [x] **[Discover] Research Plan Review** 
- [x]  **[Discover] IA Request**  
- [x] **[Discover] Analytics Request** 
- [x] **[Discover] Analytics KPI Dashboard Request**
- [x] **[Build] Contact Center Review**  
- [x] **[Build] Privacy/Security Review** 
- [x] **[Validate] Internal UAT**
- [x] **[Build] Staging Review**  Completed 03/4/2021
- [ ] **[Validate] Post-launch checkin** 
- [ ] **[Validate] Launch Full A11y Review**

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)

## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team**

**Comment by jilladams** [comment]
CLP launched, no open items, team transition; closing.
