### ISSUE TITLE
Implement Feedback from Design Council (View Payments)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11007]
## Goal 
Feedback was given from the Design Council that needs to be implemented in to our feature for "View your VA payment history."

## Considerations 
- [Link](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/203#issuecomment-654949408) to feedback to be implemented
- [Link]() to mockups/ prototype

## Tasks
- [ ] Incorporate feedback into FE
- [ ] Share results with team

## Acceptance Criteria
- [ ] All required feedback has been addressed

**Comment by jason-gcio** [comment]
Double check these:
## Changes
**Simple Responsive List Table**
- All caps should be upper lower
- "Displaying page 1 - 5 of 12" should be in Bitter (Regular 20 px) typeface, not Source Sans

**Borderless Table**
- Icons for sorting are showing (arrows)
- "Displaying page 1 - 5 of 12" should be in Bitter (Regular 20 px) typeface, not Source Sans
- `<td>` should be vertical align top
  - Payment amount ($4,321), and Account (1234567890) should be top aligned  
- `<th>` should be vertical align bottom
  - Column headers should be aligned to the bottom in case they ever go to two lines or something
