### ISSUE TITLE
Seek Feedback from PCPG (CH36) Stakeholders

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11009]
## Goal
We want to ensure that we have captured all the required functionality from stakeholders so that we can deliver the right feature for them.  We should be in a place where we can show our interpretation of what they are looking for before launch, especially now that we know about the eligibility wizard and have put that together as well.

## Considerations
- [Link](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/130194084/simulate/sitemap) to prototype
- [Link](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) to staging
- Let Steve know

## Tasks
- [ ] Schedule a meeting with CH36 stakeholders for feedback
- [ ] Conduct a demonstration with CH36 stakeholders
- [ ] Share feedback with the team

## Acceptance Criteria
- [x] Team is fully aware of any changes and/ or feedback from stakeholders

**Comment by jason-gcio** [comment]
No feedback at this time
