### ISSUE TITLE
Incorporate Feedback from Design Council for "View Payments" into Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11005]
## Goal 
Feedback was given from the Design Council that needs to be implemented in to our mockup and prototype for "View your VA payment history."

## Considerations 
[Link](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/203#issuecomment-654949408) to feedback to be implemented

## Tasks
- [x] Incorporate feedback into prototype
- [x] Update the link to design artifacts in {feature-name}/research-design folder in GH (or product outline)
- [x] Include revisions for Returned Payments section in the prototype
- [x] Share results with FE 

## Acceptance Criteria
- [x] All required feedback has been addressed
- [x] Links have been updated
- [x] Results have been shared

**Comment by sporeboy** [comment]
Updates made to prototype/sorting functionality removed: https://preview.uxpin.com/546893e0b210374a0734240e0ca9fccc2e02ed11#/pages/129039987

Changelog updated: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/research-design/README.md
