### ISSUE TITLE
COVID-19 Contact Center Content Review

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#11016]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] Identify Contact Center working group to conduct review of covid-19 content.
- [ ] Compile data to be reviewed for accuracy and information
- [ ] Conduct review with input from Veteran Facing Covid Group

## Acceptance Criteria
- [x] Contact Center working group established
- [x] JTF/Veteran Facing content approved content deployed to all call center KMs. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Chante has completed.  After discussion, this ticket can be closed.
