### ISSUE TITLE
[Migrate-Data]  Migrate Legacy data for Events, Stories, News Releases Part 2 for VISN-19 to VAMC Legacy website [Content]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11017]
## User Story or Problem Statement
As a Veteran Web user, I need the latest news, stories, and events, so I know what is happening in my local VAMC system.

## Goal
_Highlight one story, event and News Release for each listing page.

## Objectives or Key Results this is meant to further
- _Allow for training opportunity of PAO in each area._
- _Reduce Click through count by_Highlighting top stories._

## Tasks
_Complete Migration of Stories and Media for the following three areas and four Systems in VISN_
* Migrate most recent data, not to exceed 2 years old, and to best fit the Drupal format and highlight the feature story, primary media picture and information.  
* Events
* Story
* News Release
Only ONE 1 on each page for the following sites:
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care

## Acceptance Criteria
Data and media are migrated for  the following areas:
- [x] Events
- [x] Story (Featured)
- [x] News Release
* Media must be saved and reusable in Drupal.
