### ISSUE TITLE
Create content groups for products

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11015]
## Issue Description
Follow up with [7988](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/7988) to group content by products.

---
## Tasks
- [x] Ben, Jon, & Joanne meet to determine product criteria
- [ ] Ben buckets the groups per product

## Acceptance Criteria
- [ ] Content grouping is grouped by products (starting with Education) in addition to benefit hub so that VFS teams can use this for their VFSs
- [ ] Expand benefit hubs to the 3 additional live benefits from VA.gov

**Comment by jonwehausen** [comment]
### Follow-up / Next Steps
1) @bmcgrady-ep Begin setup within GTM to bucket products of `Education` found on current [Product Health MVP](https://docs.google.com/spreadsheets/d/1-1GYhR5RFItrYee2Yki_nuMW3XKYrWVzoZ8dppS3hb4/edit#gid=991352533). Create a new lookup table (or repurpose existing) to include the relevant page paths coupled with the Product Name, can also use existing Product Used custom dimensions for guidance as well. 
2) Research if there is an opportunity to do a sub-content grouping functionality within our current benefit hubs, or if not a sub-content grouping functionality determine how we will be able to report on the content grouping relationship between Hubs > Products
3) Stage and turn on within Non-Production WBC property and review data with Jon/Joanne early next week.

**Comment by bmcgrady-ep** [comment]
I researched to see if there is an opportunity to do a sub-content grouping, but it appears that there is not. The current strategy is to prefix each product with the name of the benefit hub it is in. This will help with reporting and analysis in GA.

I began setup within GTM to bucket products based on the current Product Health MVP. I completed the Education section and started on the Claims section.

**Comment by joanneesteban** [comment]
@bmcgrady-ep are these going into their own content grouping bucket?

**Comment by bmcgrady-ep** [comment]
@joanneesteban no, there is not a way to bucket the products into their own content grouping. What I am doing is using a prefix to describe what area the product is in.
![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/a7fee5e4-a7b4-467b-a6c4-ea597feafe2e)

**Comment by bmcgrady-ep** [comment]
Added Careers & Employment, Housing Assistance, and Life Insurance to the "Benefit Hubs" content group and published to Non-Production staging.

**Comment by bmcgrady-ep** [comment]
Description of Interaction | Screenshot | Test Status
------------ | ------------- | -------------
Housing Assistance | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/40a1501c-56d7-4a39-882b-04c1cdbb5621) | ✔️ **PASS**
Life Insurance | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/5e17e9b8-56b3-4df0-9b11-b6f4402e0f69) | ✔️ **PASS**
Careers and Employment | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/bf54cfe1-d60f-420a-9da5-3c92ecd547e1) | ✔️ **PASS**

**Comment by bmcgrady-ep** [comment]
Name of Product | Test Results

**Comment by bmcgrady-ep** [comment]
QA for Products Content Grouping
Product Name | Test Results

Education - Education Benefits Application (1990) | 
![image](https://user-images.githubusercontent.com/66263904/87992186-957e1b00-ca9c-11ea-8c40-588a43c94bab.png)

Education - Call to Service Program (1990n) | 
![image](https://user-images.githubusercontent.com/66263904/87992457-31a82200-ca9d-11ea-9760-d8e1e744955a.png)

**Comment by bmcgrady-ep** [comment]
Published GTM container with updates to Products - Content Grouping and turned on the product group within GA WBC View and All VA.gov View.

**Comment by bmcgrady-ep** [comment]
Updated the content grouping to include the rest of the products from the Product Health MVP and published changes to staging.

**Comment by bmcgrady-ep** [comment]
QA for Products Content Grouping
Product Name | Test Results

Claims - Viewed Details | 
![image](https://user-images.githubusercontent.com/66263904/88971779-5e142900-d269-11ea-90fd-b24c9a5833ae.png)

Education - GIBCT Profile Viewed | 
![image](https://user-images.githubusercontent.com/66263904/88972128-e98dba00-d269-11ea-9ef4-66e810ed16ca.png)

Personalized Tools - Saved my Benefits Preferences | 
![image](https://user-images.githubusercontent.com/66263904/88972483-79cbff00-d26a-11ea-92b9-937714c30ae7.png)

Personalized Tools - Successful Profile Updates | 
![image](https://user-images.githubusercontent.com/66263904/88972833-0080dc00-d26b-11ea-8904-42ca068115de.png)

Health Care - Submit Health Care Application (1010EZ) | 
![image](https://user-images.githubusercontent.com/66263904/88972994-49389500-d26b-11ea-8d1e-6dfcf4a93742.png)

Burial & Preneed - Submit Burial (Form 530) | 
![image](https://user-images.githubusercontent.com/66263904/88973377-da0f7080-d26b-11ea-8994-26e2646c7f12.png)

Burial & Preneed - Preneed Submissions (Form 40-10007) | 
![image](https://user-images.githubusercontent.com/66263904/88973751-75084a80-d26c-11ea-87e0-025539342684.png)

Pension - Submit Pension Application (Form 527EZ) | 
![image](https://user-images.githubusercontent.com/66263904/88974841-19d75780-d26e-11ea-93ac-0a5354ea746f.png)

Discharge - Discharge Upgrade Guidance | 
![image](https://user-images.githubusercontent.com/66263904/88974931-3a071680-d26e-11ea-8966-ec8f74e611cb.png)

Discharge - Download a Letter | 
![image](https://user-images.githubusercontent.com/66263904/88975043-6cb10f00-d26e-11ea-9f9e-ee8f77456299.png)

Discharge - Veteran ID Card (VIC) Submission | 
![image](https://user-images.githubusercontent.com/66263904/88975146-910ceb80-d26e-11ea-91bc-6c737ee84983.png)

Unauthenticated Experience - Facility Details Viewed | 
![image](https://user-images.githubusercontent.com/66263904/88975311-d16c6980-d26e-11ea-827e-382147d98866.png)

**Comment by bmcgrady-ep** [comment]
Moved all the changes to production. Will continue to monitor the data.
