### ISSUE TITLE
Automate DOMO Data Sharing

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#11011]
## Issue Description
Work with Aaron Barth to explore how we can automate COVID reports we are currently entering manually into DOMO.
---
## Tasks
- [ ] Introduce automated reporting to VEO contact center
- [x] Work with Kaeli Yuen to work with MHV team to explore automation of report
- [x] Reach out to Brian and the Annie team to see if this is also possible for Annie report
- [ ] Reach out to NCC group to see if we can automate the NCC report for COVID/Contact Center report

## Acceptance Criteria
- [ ] Identify one viable MVP for this effort 
- [ ] Gain necessary credentials and access to identified system 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Reached out to Kaeli last week and Brian from Annie. So far I haven't heard anything back. I am holding out on speaking with the VEO. I think I'd like to bring it up during our sync this Friday.

**Comment by Kimberley2019** [comment]
After discussion, we could bring this up in the coming months to VEO but don’t want to do that until we have established some of the other work we have going on with them.

**Comment by Kimberley2019** [comment]
@clantosswett any updates on this to your knowledge?  I am moving this to Icebox.
