### ISSUE TITLE
Create screen shots and document steps to sign in for LC "change your address"

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#11022]
## Issue Description
_Change your address is one of the research topics for Learning Center. We need to help set up this page for testing by providing screen shots of:
- First CTA on Change your address page
- The steps to sign in and identity verification
---
## Tasks
- [x] _Screen shot of the main CTA: How do I change my address in my VA.gov profile?_
- [x] _Screen shots of sign in steps_

## Acceptance Criteria
- [ ] _Share screen shots with Liz Lantz_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
![image.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/0c45d311-135f-4623-8240-9d735b0a5dbd)

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva I think this is the info you wanted--see above screen shots. There are a number of steps to sign in. Waaaaaay more than 1 step! Let me know when you'd like to talk about what's needed next content-wise or if you want me to share this with Liz.

**Comment by jenniferlee-dsva** [comment]
The images render broken to me, so et me look off VA network.

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO - I get a 'denied' message when I click on the image files above to download them. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/d491e688-f45f-4523-9d2b-78fb5a236190)

Any way you can just drop these screenshots in a word doc and upload the word doc here? Or  email me if too big for GH?

**Comment by bethpottsVADEPO** [comment]
[https://app.zenhub.com/files/133843125/eeb325e8-175e-4f1c-b23d-7fc3f55bf6ee/download](https://app.zenhub.com/files/133843125/eeb325e8-175e-4f1c-b23d-7fc3f55bf6ee/download)

**Comment by jenniferlee-dsva** [comment]
That works - thanks @bethpottsVADEPO

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva Do you still need the info in this ticket or can I close this now?

**Comment by jenniferlee-dsva** [comment]
Done!
