### ISSUE TITLE
Update PDF link on SGLI life insurance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11025]
## User story
As a Veteran I need the most up-to-date information on how to convert my SGLI life insurance to a commercial policy.

## Issue Description
The current PDF we have linked to on [this page](https://www.va.gov/life-insurance/options-eligibility/sgli/) is outdated and needs to be replaced with the one below provided by a stakeholder:

https://www.benefits.va.gov/INSURANCE/forms/SGL_133_ed2020-07.pdf

See here for where on the page it should be placed: ![Screen Shot 2020-07-08 at 1.34.47 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d46ff270-d779-415e-bc99-19537c23f6f6)

---
## Tasks
- [x] Update PDF on SGLI life insurance page (Laura)
- [x] Review change made (Randi)
- [x] Publish page (Randi)
- [x] Alert stakeholder change will go live (Beth/Randi)
- [x] Validate change on live site (Beth/Randi)

## Acceptance Criteria
- [x] New PDF is linked to on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@lwalsh617 I just slacked you the same thing but hold off on putting in this change. We are waiting from verification from the stakeholder on the right page to link to. Once we hear back I'll let you know. Thanks! FYSA @bethpottsVADEPO

**Comment by lwalsh617** [comment]
@RLHecht - This link has been updated. Here's the preview link:
http://preview-prod.vfs.va.gov/preview?nodeId=767

**Comment by RLHecht** [comment]
Thanks, @lwalsh617 This page has been published. Moving to validate and will close later this afternoon. @bethpottsVADEPO I'll email the stakeholder and let them know. FYSA @MickinSahni

**Comment by RLHecht** [comment]
This work is complete and validated on live site. Closing ticket. FYSA @MickinSahni @bethpottsVADEPO
