### ISSUE TITLE
Build Wizard in Prototype for Veteran Readiness and Employment (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11021]
## Goal
Now that the wizard is known, we can build it out in the prototype to share with stakeholders/ team.

## Tasks
- [x] Complete the CH31 prototype with wizard

## Acceptance Criteria
- [x] A prototype for the CH31 feature is complete and includes the eligibility wizard.
- [x] A link has been shared with the team

**Comment by sporeboy** [comment]
Initial pass at prototype built for CH31... Link to page: https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/130773489

**Comment by jason-gcio** [comment]
LGTM!
