### ISSUE TITLE
Discovery Sprint 26 Priorities (07/15-07/28)

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11032]
Determine list of priorities that the team will focus on for sprint 26 

1. Research plan for stakeholder interviews
2. Product documentation for initial draft of Epics based on sessions todate
3. Engineering technical spikes for APIs and or other data interfaces into both EHR's - Complete Tech Feasibility Documentation

Product

- [x] Initial Epics complete in Product Outline #10664
- [ ] Discovery -Job Map #10214
- [ ] Paper - Current State Workflows #10219
- [ ] Product Owner - Interviews #10222
- [ ] Stakeholder Interviews #11037
- [ ] Discovery Readout #10629

Research/Design

- [x] Discovery - personas and journey map #10716
- [x] Create a Conversation Guide for Stakeholder Interviews #11160

Engineering

- [x] Complete Discovery Tech Feasibility Documentation #11027
- [x] Research API's Available from EMR's #10223
- [x] Laurence/Mark Onboarding
