### ISSUE TITLE
Analytics KPI dashboard request for Benefits & Memorials 2 - Medical Device Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11044]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Submit this ticket as an epic
- [ ] Add your team label to follow progress

### KPIs
[Medical Device Reordering KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md#okrs-kpis)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by joanneesteban** [comment]
This is a duplicate of [11069](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11069). Closing this issue.
