### ISSUE TITLE
Draft a KPI Dashboard for Medical Device Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11045]
## Issue Description
Draft V1 of the Medical Device Ordering KPI dashboard.

---
## Tasks
- [ ]  Groom analytics for technical feasibility
- [ ]  Document data sources for each metric
   - [ ]  Document unavailable vs. available metrics
   - [ ]  If any, add implementation issue for additional necessary implementation
- [ ]  Draft dashboard on Domo
- [ ]  Pipe available metrics to Domo
- [ ]  Add appropriate team members to dashboard

## Acceptance Criteria
- [ ] B&M 2 can easily track their KPIs for the Medical Device Tool
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[V1 Medical Device Tool KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md#okrs-kpis)

**Comment by joanneesteban** [comment]
Remaining AC:

- [ ] Switch over datasets to Prod
- [ ] Add goals where possible
- [ ] Add Date Ranges where it's unclear (the date range isn't a part of the axes) - look into dynamic titles

**Comment by joanneesteban** [comment]
@bsmartin-ep 
We actually have a couple of follow ups for Medical Device Reordering KPIs from user research:
- [ ] Abandonment rates & segmented by browser & device type
- [ ] Traffic segmented by browser & device type

@amycesal 
- [ ] Online orders viewable by month

**Comment by amycesal** [comment]
Per month with the goal is added 

![Screen Shot 2020-08-05 at 9.21.34 AM.png](https://images.zenhubusercontent.com/5b2ab6f42f27e82b33e6b789/b0d39f12-e579-4655-8e72-6d499d2c902a)

**Comment by joanneesteban** [comment]
Once the browser/device type cards are added, we can close this ticket.

**Comment by bsmartin-ep** [comment]
@joanneesteban / @amycesal -

I updated the BAM2 events dataset to include `browser` and added a new dataset for BAM2 traffic (with `browser` and `device category`) in users and pageviews.

https://va-gov.domo.com/page/1133411197

Any thoughts on line graph vs bar on this one?  Are day-to-day numbers useful or is it better to have an overall segmentation?

![image](https://user-images.githubusercontent.com/62304138/91451740-b7ad4a80-e84b-11ea-84c1-b094fbf17416.png)

**Comment by joanneesteban** [comment]
Defer to you, @amycesal . The bar graph is easier to read, but the line graph is better to understand trends. Would probably look pretty convoluted if broken down by browser, though.

**Comment by joanneesteban** [comment]
Medical Device Reordering Tool KPI dashboard is live. Any iterations or updates will receive a new ticket. Closing this ticket.
