### ISSUE TITLE
[Design] DL - Conversation Guide Final Draft

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11047]
## Issue Description
Create a conversation guide final draft

---
## Tasks
- [x] Complete the conversation guide template found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/conversation-guide.md)
- [x] Share with Shawna for feedback

## Acceptance Criteria
- [x] Convo guide in GH
- [x] Share with Shawna for feedback
- [x] Start VSP process

**Comment by rileyorr** [comment]
I've uploaded [the finalized conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/conversation-guide.md) to GH and sent to Shawna for feedback. @rebeccawalsh Becca is wrapping up final touches on the UXPin prototype and then she will update [the usability test prep ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10800) with all the required documents.
