### ISSUE TITLE
[Design] DL - Conversation Guide Final Draft

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11049]
## Issue Description
Create a conversation guide final draft

---
## Tasks
- [ ] Complete the conversation guide template found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/conversation-guide.md)
- [ ] Share with Shawna for feedback

## Acceptance Criteria
- [ ] Convo guide in GH
- [ ] Share with Shawna for feedback
- [ ] Start VSP process
