### ISSUE TITLE
[Data-Load] Load Data for 'VA Eastern Colorado' Health Services Program Intros, information and Staff Profiles from data collected [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11059]
## User Story or Problem Statement
As a Veteran Web user, I want to be able to get accurate points of contact for my Health Service Programs, so I may quickly contact a support caregiver to help me on my health care journey. 

## Goal
_Highlight system Health Service PROGRAM pages and Points of Contact/Caregivers for each program_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN-19 Caregiver Spreadsheet](https://drive.google.com/drive/folders/1Aric8sLU7iq465_20MDlBa9ruwMOHCm9)
[Eastern Colorado Legacy Site Pages: ](https://www.denver.va.gov/services/caregiver/index.asp)

## Tasks
_Complete the following tasks for completion of this story:_
* All Health Service Program "Intro" Content must be loaded and caregivers/points of contacts added as **Content Block-Staff Profiles:**
- [x] All Staff Profiles will have already been loaded on previous stories.  If not, return to earlier profile stories and complete those first.
* The following system level information on these pages must be complete:
- [x] Caregiver
- [x] Homeless Veteran Care
- [x] LGBT-Veteran-Care
- [x] Mental Health-care
- [x] Minority Veteran Care
- [x] Patient-advocates (Customer Service)
- [x] Returning-service-member
- [x] Suicide-prevention
- [x] Women-veteran-care
- [x] Leadership (listing page)

## Acceptance Criteria
All local system content and staff profiles must be loaded and visible for the following pages:
* Caregiver
* Homeless Veteran Care
* LGBT-Veteran-Care
* Mental Health-care
* Minority Veteran Care
* Patient-advocates (Customer Service)
* Returning-service-member
* Suicide-prevention
* Women-veteran-care
- [x] Cross Check completed
