### ISSUE TITLE
[Design] DL - Wireflows

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11050]
## Issue Description
In order to accommodate new constraints with VBMS and DMC data, we will revisit our wireflows and make the appropriate adjustments for V1 release and usability testing.

---
## Tasks
- [x] Collaborate with designer on new wireflows
- [x] Share wireflows with team to confirm direction and feasability
- [x] Export wireflows and update GH

## Acceptance Criteria
- [x] Export included in GH

**Comment by rebeccawalsh** [comment]
This ticket was added to sprint 24 due to a pivot that pushed the prototype and conversation guide out of the sprint.

**Comment by rebeccawalsh** [comment]
Designs were collaborated on by design and shared to the team in Grooming. GH has been updated with all 3 steps of the design [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md).
