### ISSUE TITLE
Deduplicate Community care results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11051]
## Issue Description
Community care providers do not necessarily have unique IDs. Duplicate IDs may cause
- incorrect details to be displayed for a selected provider 
- some providers not to be returned in the search results. 

We have addressed this issue by creating new IDs for community urgent care providers and need to extend the logic to all providers in PPMS. [#4388](https://github.com/department-of-veterans-affairs/vets-api/pull/4388)

The suppression of community care facility detail pages is addressed in [#10324](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10324)

---
## Tasks
- [ ] Assign different ID for provider locator results (impacting all community care providers).
- [ ] **Feature flag? (TBD)**

## Acceptance Criteria
- [ ] All locations meeting the search criteria will be returned as unique result. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
