### ISSUE TITLE
Analytics KPI dashboard request for BAM 2 - Medical Device Reordering Tool 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11069]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Submit this ticket as an epic
- [ ] Add your team label to follow progress

## VFS Information

Goals: To migrate Veterans from off-line to online channel. Currently only 7k of orders re online, the objective is to migrate more users to online ordering system. This will be supported by changing the signage in audiologist's offices, sending promo flyers and changing the IVR recordings. 

### KPIs
KPIs
Number of online orders
Order abandonment rate
Baseline KPIs
Online orders - 7k per month
Offline orders - 180k per month
Percentage of orders online - 3.8%
Objectives and Key Results
Number of online orders: 2020 goal - 9k/month
Percentage of orders online: 2020 goal - 5% of all orders, 2021+ goal - 5% QoQ
Abandonment Rate - <10%
Increase online orders by 5% QoQ

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by joanneesteban** [comment]
Thanks, @leahkeeler ! To ensure quality, could you please add the veteran/user goals for your KPIs?

**Comment by leahkeeler** [comment]
Done! Thanks

**Comment by joanneesteban** [comment]
@leahkeeler - do you have goals for these metrics? We can add them to the dashboard we're creating!

**Comment by leahkeeler** [comment]
I sure do: Here you go

Baseline KPIs
Online orders - 7k per month
Offline orders - 180k per month
Percentage of orders online - 3.8%
Objectives and Key Results
Number of online orders: 2020 goal - 9k/month
Percentage of orders online: 2020 goal - 5% of all orders, 2021+ goal - 5% QoQ
Abandonment Rate - <10%
Increase online orders by 5% QoQ

**Comment by leahkeeler** [comment]
This looks great1 The only question I have is - how s abandon rate tracked? are the ineligible states being filtered out -- so if a veteran is not eligible to order because it is too soon, this should not be considered abandon. Only veterans that are eligible and do not complete order should be considered abandoned.  Thanks! Leah

**Comment by bsmartin-ep** [comment]
@leahkeeler -  The conversion rate is currently:

`SUM(Events = bam-2346a--submission-successful)`

divided by

`SUM(Events = login-successful-start-form)`

So we would want to exclude users with an error key like these?

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184318975/explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&explorer-table.secSegmentId=analytics.customDimension57&explorer-table.advFilter=%5B%5B0,%22analytics.customDimension57%22,%22RE%22,%22%5E(batt%7Cacc)%22,0%5D%5D&explorer-segmentExplorer.segmentId=analytics.eventLabel

**Comment by leahkeeler** [comment]
@bsmartin-ep added @bradl3yC to the ticket, I can't see the error ur referencing. I imagine another way to accomplish the same goal is to track the page where the user abandoned - which should mostly be the eligibility page when they get the message with eligibility date. Whatever y'll think is hte best approach. Thanks! Leah

**Comment by bradl3yC** [comment]
@bsmartin-ep We just want to make sure that users that have both no eligible batteries or accessories are not included in the abandon rate - they cannot progress through the form if both are ineligible

**Comment by bsmartin-ep** [comment]
Sounds good @leahkeeler and @bradl3yC .

I will build a segment to exclude users who receive both of these errors from the abandonment rate.

```
bam-error | accessories_bam-ineligibility-no-prescription
bam-error | batteries_bam-ineligibility-no-prescription
```

**Comment by leahkeeler** [comment]
Hi - One more request, can we look at abandon rates by device type- I am wondering if we are getting high abandon rates from phones

**Comment by bsmartin-ep** [comment]
@leahkeeler -

Order completion by device category (mobile, tablet, desktop) has been added to KPI dashboard:

https://va-gov.domo.com/page/1133411197

All graphs and funnels should be excluding users with both ineligibility errors.

Closing this issue, but please don't hesitate to contact us if you have any questions or additional requests.
