### ISSUE TITLE
Benchmark Lat/Long impact

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11087]
## Issue Description
In [#7056](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7056), we adjusted the PPMS query to pass Lat/Long directly and put it on a flipper, in anticipation of the release of PPMS 8.1. 
[Pull request](https://github.com/department-of-veterans-affairs/vets-api/pull/4107)
The functionality is currently not enabled due to a delay in the release. 
Before we enable this change, we need to benchmark the existing performance so we can evaluate the impact of this change. 

---
## Tasks
- [ ] Establish benchmark performance for PPMS queries
- [ ] Remove flag from Lat/long functionality
- [ ] Evaluate performance again 

## Acceptance Criteria
- [ ] Impact of change to pass lat/long is measurable. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
