### ISSUE TITLE
Form Detail Pages x Collab Cycle

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11083]
## Product Outline
[Find VA Forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md)

## Plan
- [x] **[Define] Kickoff-Intent** 
- [x] **[Define] Design intent** [Completed here #2691](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2691)
- [x] **[Discover] Usability Testing Prep** [Not needed, per #8990](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8990)
- [x] **[Discover] Research Plan Review** [Not needed]
- [x]  **[Discover] IA Request** [ #3836](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3836)
- [x] **[Discover] Analytics Request** [#4552](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/4552) `submitted 7/28 MS`
- ~[ ] **[Build] Contact Center Review**~  [Not needed - we're just replacing existing form detail pages with new ones]
- ~[ ] **[Build] Privacy/Security Review**~ [Not needed - forms data is public info]
- [x] **[Build] Pre-Staging Review activities**
  - [x] [Accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#required-accessibility-checklist-for-staging-review) - #11332
  - [x] Fix any accessibility checklist findings - #(tickets)
  - [x] Compile QA test cases and submit QA request i.e. Tze's ticket - #11335 (targeting 8/20)
  - [x] Release plan - #11311
  - [x] Link to vsa-qa ticket (Tze) - #11335 \[Use-Cases ticket - the QA discussions are there. I didn't open a Test Plan ticket]
  - [x] Product Guide - #12616
  - [x] Analytics implementation - #12757
- [x] **[Build] Staging Review**  [Content lives on Drupal prod, so not sure about this.][Potential asynch with VSP since we're not going to be in a staging env] [#13285](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13285)
  - [x] Resolve Staging Review findings - #(tickets)
- [x] **[Launch]**
     - [x] Batch 1 hidden launched - #11155 
     - [x] UAT review and resolutions completed - #13126 
     - [x] Batch 2 hidden launched - #12213 
     - [x] Basic auth and noindex removed - [#12242](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12242)
     - [x] Redirects implemented - [#5549](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5549)
- [x] **[Validate] Post-launch checkin** 
- [x] **[Validate] Launch Full A11y Review**
  - [ ] [Complete accessibility checklist in Prod](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#required-accessibility-checklist-for-staging-review) - #(ticket if necessary)
  - [ ] Submit request

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)

## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team**

**Comment by MarciMcGuireGCIO** [comment]
Thank you, Brian! I got the others also.  I appreciate you sending these.
