### ISSUE TITLE
Implement UI for predictive geolocation prototype

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11090]
## Issue Description
- This is a follow-up to the Predictive geolocation discovery work done in #9410. 
- Documentation is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/PredictiveGeolocation.md).  
- As noted, many of the original concerns were addressed by simply turning off the autocomplete option. Our first step in any follow-up should be to re-evaluate our current solution with this new, improved behavior.

<details>
<summary> Current behavior </summary>
- There is a single text field in which the user is prompted to “Search by city, state or postal Code”
- When the page is loaded, we try to find the user's location using the browser’s native geolocation support. This location is used as a fallback if no MapBox-geocoded locations are found.
- There is no auto-completion of the user input. Input is not evaluated at all until the form is submitted.
- The function that performs the geocoding is genBBoxFromAddress. It calls the MapBox Javascript API’s forwardGeocode function, which “allows you to look up a single location by name and returns its geographic coordinates” - a bounding box array in the form [minX,minY,maxX,maxY]. These coordinates are passed to the search API and used to filter the matching facilities that fit inside the coordinates.
- We are using the @mapbox/mapbox-sdk npm package, v. 0.10.0, which supports predictive/interactive geolocation. This was released 3 months ago. It appears we are keeping this up to date via dependabot. We should be vigilant about automated updates to this package, but it seems very unlikely that MapBox will introduce breaking changes to this core functionality.
- There is currently no opportunity for the user to interact with the geocoding results from MapBox and make a selection. The location string is sent to MapBox "behind the scenes", and we just take the first match. We could improve this fairly easily by using “predictive search”, showing the list of matching place names in a scrolling div under the text field. MapBox returns a maximum of 10 locations. This limit can be adjusted lower if needed.
</details>

<details>
<summary>Accessibility considerations</summary>

- If we decide to implement predictive search, we should use the Autocomplete component from the VSP design team. However, this component has known 508 compliance issues, which should be addressed, perhaps by the VSP team. Screen readers will speak every character typed, then the full word, which may collide with the speaking of the search results. It’s unclear to me at this time what, if anything, can be done about this.
- Expected behavior: Screen-reader users are notified when the list of suggestions appears and that they can enter the list and select an option using the keyboard.

For what it's worth, I found a few resources on addressing accessibility
- [Aria autocomplete](https://accessibility.huit.harvard.edu/technique-aria-autocomplete): One solution is to use an ARIA live region to announce when autocomplete options are available, and to create a listbox containing the options that appear as the user types, which is controlled with the up and down arrow keys. 
- [Building an accessible autocomplete control](https://adamsilver.io/articles/building-an-accessible-autocomplete-control/)
</details>

<details>
<summary>Functional considerations </summary>

We need to determine desired behavior for the following:
- Should we use MapBox's“proximity bias” feature?
   - This feature would favor results that are closer to a specific geographic location. This could be helpful if the user searches for a city with a common name, (e.g. “Bloomington”). We are not using proximity bias currently. Most users probably know to enter a state to disambiguate their city.
- Favor results based on search popularity or population?
- How many characters will need to be entered before results are suggested?
  - Mapbox allows only one character to trigger a search, if we want.
  - Should be increased to 3-4 characters
- How are results restricted (limited to state? Country?)
   - We currently limit search results to the US and territories (Puerto Rico, Guam, etc.) 
   - GA shows over 95% of users are from US. 
- How will parameters be impacted by user interaction with map?
   - Currently the search results are updated as the map is panned/zoomed. We do not update the search field. 
   - Updating the search field will be difficult and may not be desirable from user experience. 
- What if no results match? Can that happen?
- Do we force the user to choose from the list or can he/she override and force the search using free text?
- Design
   - What does list of locations look like -> renders a list below the field
   - Will we show the full suggestion or will it be truncated?
   - How is this displayed on mobile?
</details>

Backend support for this effort in [#12722]

## Tasks
- [ ] Implement UI
- [ ] Trigger `genBBoxFromAddress` on every change to the search location field. (May want to throttle this?)

## Acceptance criteria
- [ ] If the Veteran attempts to trigger a search before selecting a location, an error message `Please select an item in the list` is displayed. 
- [ ] The Veteran is prompted to enter a value in the field before a search can be triggered
- [ ] The Veteran can view Mapbox's top 10 list of possible results based on search text
- [ ] The Veteran can select a location from the displayed list
- [ ] The Veteran's selection is displayed in the search field
- [ ] The Veteran can edit location to initiate a new search
- [ ] ~~Functionality is created with "Is Production" flag to keep in staging for review with accessibility/usability~~
- [ ] This behavior is only triggered if the `facilities_predictive_search` flag is set to true

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Blocking this issue with Design Discovery

**Comment by mmiddaugh** [comment]
Per @davidconlon, we may want to do a POC which can be reviewed with Jennifer for accessibility

**Comment by jilladams** [comment]
@mmiddaugh does this seem like a plan / feature that may revive, or this could be closed?

**Comment by jilladams** [comment]
Parent epic is closed, FL is now ticketed in va.gov-team repo. Closing orphaned tickets, as we are iterating FL separately.
