### ISSUE TITLE
[Analytics] Health Service Data Call - VISN-4 Facility Health Services questions [LT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11097]
## Story
As a VAMC product owner I need clarification on facility health services input, so I can better understand the process, data, and input to develop some hypothesis for hardening of the data.

## Resources
[VISN-4 Analytics spreadsheets](https://drive.google.com/drive/folders/1WygUuvMetcaCm43woL6rfTursUVUyGeO)

## Tasks
Respond to the following inquiries:
- [ ] Is there a case where, for a specific service at a specific facility, there were no hours provided? (e.g should this be required?) If yes, do you know where?
- [ ] Is there a case where, for a specific service at a specific facility, there was no phone number? (e.g should this be required?If yes, do you know where?)
- [ ] Is there a case where, for a specific service, a referral is needed at one facility within a health care system but not another. (e.g. Referral needed for X service at Erie VAMC, but not Crawford County Clinic in the same health care system) If yes, do you know where?
- [ ] Is there a case where, for a specific service, a Walk In is accepted at one facility within a health care system but not another. (e.g. Walk-ins OK for X service at Erie VAMC, but no walk-ins for the same service at Crawford County Clinic in the same health care system) If yes, do you know where?
- [ ] Is there a case where, for a specific service, any appointment phone numbers are different between two facilities facilities within a single health care system? If yes, do you know where?

## Acceptance Criteria
Provide written examples and responses to the above questions:
- [ ] Provide document or slack with answers
- [ ] Provide summary of items for better understanding
- [ ] If required set up a meeting to go over information
