### ISSUE TITLE
Drupal Audit

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11092]
## Issue Description
How might we improve identification/organization of liquid templates? 

## Background 
CMS (Drupal) also currently supports

- VAMC system pages
- Benefits hubs (eg www.va.gov/health-care and 10 other benefits hubs)
- Homepage and Global UX elements such as the header, footer, and homepage alerts
- Benefits outreach hub

## Problem Statement 
The Facilities team is relatively new to the VAMC system product and still building knowledge on liquid templates. It is often difficult to know the correlation between templates and pages, increasing both level of effort and the risk for unintended consequences. Understanding which pages could be impacted by template changes will also focus the scope of testing, ensuring coverage without overkill. 

---
## Tasks
- [ ] Determine a method for easier identification/organization of liquid templates

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
