### ISSUE TITLE
Life Insurance: Batch 1:  SEO Keyword review and copy adjustments for DEPO review

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#11118]
## Issue Description
SEO keywords (that were included in tickets for individual life insurance pages) reflect SEO research completed well over a year ago. Before we share pages with SMEs, we need to go back and revisit keywords either confirming their relevance and replacing. If replacing, copy changes will be required. 
---
## Tasks
- [ ] _PW: run SEO keywords from closed ticket #8365 (Life insurance rewriting batch 1: Convert to a commercial policy) through Moz keyword explorer. Adjust keywords and copy as needed. 
- [ ] _PW: run SEO keywords from closed ticket #8439 (Life insurance rewriting batch 1: Calculate your needs) through Moz keyword explorer. Adjust keywords and copy as needed. 
  - [ ] _PW: run SEO keywords from closed ticket #8542 (Life insurance rewriting batch 1: Uninsurable health issues) through Moz keyword explorer. Adjust keywords and copy as needed. 
- [ ] _PW: run SEO keywords from closed ticket #8548 (Life insurance rewriting batch 1: Life insurance rewriting batch 1: Insurance plans) through Moz keyword explorer. Adjust keywords and copy as needed in Drupal. 
- [ ] _PW: Send updated Drupal preview links to DEPO

## Acceptance Criteria
- [ ] _All four Batch 1 pages have been updated in Drupal and DEPO has been alerted and provided with Drupal preview links for review.

**Comment by lwalsh617** [comment]
Closing ticket.
