### ISSUE TITLE
[VSA-QA] Report vets-website automated test file counts

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#11113]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
This is not a VSA Product, but rather an internal reporting feature.
The feature is intended to automate reporting of the number automated-test-files in vets-website applications.

## High Level User Story/ies
As VSA Engineering Lead, I want to see/report the total number of automated tests files in vets-website applications every month.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect to relieve Engineers from manually finding/counting/reporting automated test file counts to VSA Engineering Lead_.

## OKR
_Which Objective / Key Result does this epic push forward?_ [TBD; will get from VSA Engineering Lead]

## Definition of done
NOTE: The following items may change as research/discovery gets underway.
- [ ] Test-file-counts NodeJS file added to vets-website repo.
- [ ] Script call added to package.json.
- [ ] package.json script-call auto-triggered at appropriate step in build/deploy pipeline.
- [ ] Test-file-counts console-output made accessible by VSA Engineering Lead.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by tlei123** [comment]
Closing now.  No longer a valid requirement.
