### ISSUE TITLE
[development] Add fullyDevelopedClaim to form526 BDD

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#11119]
## Issue Description
this question in "all claims" should also be asked in BDD
<img width="1188" alt="Screen Shot 2020-07-10 at 11 47 56 AM" src="https://user-images.githubusercontent.com/19188/87175365-87631a00-c2a6-11ea-9268-67117bf99630.png">

---
## Tasks
- [ ]  add fullyDevelopedClaim question to BDD
if it helps at all, fullyDevelopedClaim is added to all claims here https://github.com/department-of-veterans-affairs/vets-website/pull/8880
- [ ] `standardClaim` attribute is always sent to BE

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
