### ISSUE TITLE
Move View Payments to Staging

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11135]
## Goal
We need to move the latest iteration of View Payments to staging so that we can get more collaborators to see it and provide feedback.

## Considerations
- The backend may not be completely finished or wired up yet.

## Tasks
- [ ] Manually add View Payments to registry.json
- [ ] Adjust View Payments entry file (name change)

## Acceptance Criteria
- [ ] The feature can be accessed in staging
