### ISSUE TITLE
[Engineer] Create and associated remaining VISN-19 Systems, system pages to Governance drop down [BE}

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11131]
## Story
As a editor of the Drupal environment, I need access to all VISN-19 governance drop downs, so I can complete cloning of all system pages.

## Goal
Provide governance drop down for all editorial users

## Tasks
Associate drop downs for the following systems:
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma City health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care

## Acceptance Criteria
- [ ] Assure that system pages are loaded
- [ ] Provide screenshot and confirm that all above systems show up in the Governance Drop down list
