### ISSUE TITLE
[Design] DL - Mid-complexity hifi prototype

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11138]
## Issue Description
Create a high fidelity prototype in UXPin for one of the following concepts:

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/2bc7c190-b1d3-438f-b0e7-01a4d898cc7d)

OR

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/436dddb1-3e16-425e-b8c1-72963c3955b2)

## Tasks
- [ ] Create the high fidelity design in UXPin, in it's own project
- [ ] Share with designer
- [ ] Update GH documentation and share with the team

## Acceptance Criteria
- [ ] Designs up in GH and shared with team for feedback
