### ISSUE TITLE
[Engineer] Clone and create new System (HOME) Pages for remaining VISN-19 systems [PM}

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11132]
## Story
As a editor of the Drupal environment, I need access to all VISN-19 governance drop downs, so I can complete cloning of all system pages.

## Goal
Provide governance drop down for all editorial users

## Tasks
Create System pages so that governance drop downs can be created for the following systems:
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma City health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care

## Acceptance Criteria
- [ ] Assure that system pages are loaded
- [ ] Provide screenshot and confirm that all above systems show up in the Governance Drop down list
