### ISSUE TITLE
[Design] DL - Debt letter table only hifi prototype

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11137]
## Issue Description
Create a high fidelity prototype in UXPin for the following concept:

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/91ff1a41-201c-47fb-bd8c-e355bb951ae1)

---
## Tasks
- [x] Create the high fidelity design in UXPin, in it's own project
- [x] Share with designer
- [x] Update GH documentation and share with the team

## Acceptance Criteria
- [x] Designs up in GH and shared with team for feedback

**Comment by rileyorr** [comment]
I've created the prototype in UXPin and [updated the GH documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/prototypes.md) to include a link to the prototype.
