### ISSUE TITLE
Updating SSL Certs  

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11140]
## Description
_We have a few certs that are expiring in 30+ days, we need to update them_

## Background/context/resources
SOP for renewing certs: https://github.com/department-of-veterans-affairs/devops/blob/1f4038077791652a2162fc3ec3164c9b325e0648/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md#renew-an-existing-certificate 

and 

https://github.com/department-of-veterans-affairs/devops/blob/1f4038077791652a2162fc3ec3164c9b325e0648/docs/StandardOperatingProcedures/CreatingVASignedSSLCertificate.md

## Technical notes
SSL certificate scan result: https://dsva.slack.com/archives/C37M86Y8G/p1594655775068700

---
## Tasks
- [x] _Update the SSL cert for vetsgov-evss-prod-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-int-cert.pem_
- [ ] _Update the SSL cert for vetsgov-mvi-pint-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-preprod-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-prod-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-qa-cert.pem_
- [x] _Update the SSL cert for gids-saml-dev-cert.pem_
- [x] _Update the SSL cert for gids-saml-prod-cert.pem_
- [x] _Update the SSL cert for gids-saml-staging-cert.pem_
- [x] _Update the SSL cert for vetsgov-evss-prod-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-int-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-preprod-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-prod-cert.pem_
- [x] _Update the SSL cert for vetsgov-mvi-qa-cert.pem_
- [x] _Update the SSL cert for vetsgov-vic-dev-cert.pem_
- [x] _Update the SSL cert for vetsgov-vic-prod-cert.pem_
- [x] _Update the SSL cert for vetsgov-vic-staging-cert.pem_
- [x] _Update the SSL cert for staging.va.gov_
- [x] _Update the SSL cert for dev.va.gov_
- [x] _Update the SSL cert for staging-api.va.gov_
- [x] _Update the SSL cert for dev-api.va.gov_

## Definition of Done
- [ ] _All the above certs are updated and confirmed_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by ricetj** [comment]
updated scan: https://dsva.slack.com/archives/C37M86Y8G/p1595865376132100

looks like this one is under 30 days: URGENT: /ansible/deployment/config/vets-api/vetsgov-vic-dev-cert.pem expires in less than 30 days: 2020-08-17T18:21:44+00:00
URGENT:…

**Comment by dginther** [comment]
I have followed the process for the internal certs, and requested all of them via the PKI website.

Taylor is creating a ticket to get the pending certificates in SSLmate attended to by the admin@va.gov overlords.
