### ISSUE TITLE
Disable Facility health service status UI in Prod

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11148]
## Issue Description
v1 for the UI display for the facility health service operating status was built as part of [#9449](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9449).

Currently, the health service status data does not exist in the API and may not be included in the near future due to the difficulty of that data call and competing priorities. However, in the event this data does become available, we don't want the UI effort to be outdated. 

---
## Tasks
- [ ] Add flipper to this code
- [ ] Move to production with feature disabled. 

## Acceptance Criteria
- [ ] UI display of health service status is available in Production but is disabled. 
- [ ] All other functionality is maintained. 
<details>
  <summary>When the Veteran clicks the hyperlinked facility name, a facility detail page for the selected facility is displayed (expand)</summary>

The Facility Detail page contains the following information about the selected facility

- Name of Facility 
- Alert box with operating status information  (if normal, no alert is displayed)
- Facility type displayed as VA HEALTH
- Address
- Main Number
- Mental Health Number (if available)
- Functional Hyperlink to Website
- Functional Hyperlink to Directions
- "Current as of" date
- List of Services
- Appointments "Current as of" date
- New patient wait times
- Wait times for each specialty
- Existing patient wait times
- Wait times for each specialty
- Veteran-reported Satisfaction Scores "Current as of" date
- % for Urgent care/Primary care 
- % for Urgent care/Specialty care 
- % for Routine care/Primary care
- % for Routine care/Specialty care
- Static map
- Hours of Operation displayed by day

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@kevwalsh @davidconlon I'll leave this with you to determine priority and timing. 
@ethanteague
