### ISSUE TITLE
Add # of results to FL results header (3b)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11149]
## User Story or Problem Statement
As a Veteran, I need to know how many results are returned for my search so I can find the location I seek. 

## Background
This functionality was previously implemented but was [hidden](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6775) when it was determined that the number of results was incorrect and misleading to Veterans. 

A general header was implemented in [#7555](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7555)

Total results is available from Lighthouse and PPMS  (separate methods) : Backend will expose total number of results to Facility Locator front end #31521

---

## Tasks
- [ ] Add the number of results to the header expressed as (x) results for `"facility type"` , `"service type",` near `"geographic search parameters"` (i.e. (x) results for "VA health", "All VA health services" near "Spokane, Washington 99224" above the list of results. 
-  [ ] If there are 17 results, and 10 displayed, the header should say something like "Showing 1-10 of 17 results for urgent care..." etc. When the user flips to page 2, it should say "showing 11-17 results..."
-  [ ] For results of less than ten, the header can say "Showing 1-x results for ..."
- [ ] Update existing tests as needed

## Acceptance Criteria

- [ ] When the user goes to different page of results, the display number updates 
- [ ] If the user initiates a new search, the display number updates 
- [ ] Veterans using screen readers understand the context of the search results list

The following existing functionality is maintained 
- [ ] Heading includes user search criteria (Search results for <VA facility type> near "location parameters")
- [ ] Heading updates with new search criteria if new search is initiated
- [ ] Only the standard error displays if no search results are found (no heading displays)
- [ ] Results summary header displays when search results are returned. 
- [ ] Results summary header does not prematurely load (No heading is seen while a search is in progress)
- [ ] Heading levels do not skip
- [ ] Ensure focus goes to results summary header consistent with user flow

**Comment by AngelaFowler82** [comment]
If there are 17 results, and 10 displayed, the header should say something like "Showing 1-10 of 17 results for urgent care..." etc. When the user flipps to page 2, it should say "showing 11-17 results..."
