### ISSUE TITLE
Fix to monthly rate figures in 2020 DIC Rates-Parents page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11144]
## User Story
As a surviving parent of a Veteran I need to know the most up-to-date monthly DIC rates based on my income range

## Issue Description
When migrating over the 2020 DIC rates information to Drupal (completed February 2020), we altered the income range within each accordion per the stakeholder's request. However, the monthly rate figure in the first row of each accordion was never adjusted, resulting in an incorrect amount.

We need to adjust the monthly rate figure at the top of each accordion (except the first accordion in each category) to match the monthly rate figure in the bottom row of the accordion above it. 

VA.gov page: https://www.va.gov/disability/parent-dic-rates/
Drupal node ID: preview-prod.vfs.va.gov/preview?nodeId=1013

See ticket #10718 for more info.

## Tasks
- [x] Update monthly rate figure in first row of each accordion to match the figure in the bottom row of the accordion above (Anne)
- [x] Review changes (Randi)
- [x] Publish page (Randi)
- [x] Validate on live site (Anne/Randi)

## Acceptance Criteria
- [x] Correct monthly rates are showing on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These changes have been made and the page published. Created ticket to track work. Moving to validate. FYSA @bethpottsVADEPO @MickinSahni

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni
