### ISSUE TITLE
Review content in Cerner React components

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11154]
## Issue Description
Given we've created the Cerner pages as React widgets
I want to validate the content is accurate before publishing.

---
## Tasks
- [ ] Review authenticated content across all pages against final Word doc to make sure it matches
- [ ] Review unauthenticated content across all pages against final Word doc to make sure it matches
- [ ] Review alerts across all pages against final mockups to make sure they match 
- [ ] Create follow-up frontend ticket(s) to adjust content based on reviews

## Acceptance Criteria
- Validate Cerner content created as React components are accurate against final mockups (for alerts) and Word docs (for full page content)

**Comment by MickinSahni** [comment]
Hey @DanielleThierryUSDSVA can you check the description/acceptance criteria and groom/add any dependencies?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. Added dependencies of the 2 content review issues. Not sure if we have an issue for @kelsonic to update the content based on those reviews yet? If not, we can create a ticket for that and that will also be a dependency for this one. Thanks!

**Comment by MickinSahni** [comment]
> Hi @MickinSahni. Added dependencies of the 2 content review issues. Not sure if we have an issue for @kelsonic to update the content based on those reviews yet? If not, we can create a ticket for that and that will also be a dependency for this one. Thanks!

Created https://github.com/department-of-veterans-affairs/va.gov-team/issues/11239
@kelsonic feel free to groom/estimate as needed.
