### ISSUE TITLE
Verify integration with updated Forms API

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11156]
## Issue Description
Given the Lighthouse team is updating the Forms API to point at Drupal
I want to verify the existing Forms Search experience continues to work as expected.

---
## Tasks
- [ ] **As needed,** create follow-on middlelayer dev tickets to handle LIghthouse's integration with Drupal (e.g. versioning, backward compatibility)
-  ~[ ] Validate in Review instance  {added per [Michael Bastos slack message](https://dsva.slack.com/archives/CUB5X5MGF/p1594436954447100?thread_ts=1594394779.439800&cid=CUB5X5MGF)}~
- [ ] ~Validate search results in Staging~
- [ ] Validate search results in Prod

Removing the review and staging checks as the LH team cutover without notice. Please report any bugs/issues below.  [Edited 7/28 JL]

## We'll  use the following to test/validate that the search is still functioning ok/not worse than legacy experience: 
| Query | Modernized web scrape results | API-based results |
| --- | ---- | ---|
| disability | [8 includes 526ez](https://www.va.gov/find-forms/?q=disability) | 9 includes 526ez |
| compensation | [15 includes 526ez](https://www.va.gov/find-forms/?q=compensation) | 15 includes 526ez |
| disability compensation | [20 includes 526ez](https://www.va.gov/find-forms/?q=disability+compensation) | 21 includes 526ez |
| disability application | [91 includes 526ez](https://www.va.gov/find-forms/?q=disability+application) | 93 includes 526ez |
| 526ez | [1](https://www.va.gov/find-forms/?q=526ez) | 1 |
| 1010ez | [0] | 0 |
| 10-10ez | [3](https://www.va.gov/find-forms/?q=10-10ez) | 3 | 
| caregiver | [1 includes 10-10CG](https://www.va.gov/find-forms/?q=caregiver+) | 1  |
| care giver | [22 includes 10-10CG](https://www.va.gov/find-forms/?q=care+giver) |  21 includes 10-10CG| 
| intent to file | [93 includes 21-0966](https://www.va.gov/find-forms/?q=intent+to+file) | 91 includes 21-0966  |
| supplemental claim | [43](https://www.va.gov/find-forms/?q=supplemental+claim) |  42 includes 20-0995 |
| aid and attendance | [89 includes 21-2680](https://www.va.gov/find-forms/?q=aid+and+attendance) | 109 includes 21-2680  |
| housebound | [1 includes 21-2680](https://www.va.gov/find-forms/?q=housebound) | 1 includes 21-2680 after manual override of bad form db name entry ~0 - [see comment below]~(https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11156#issuecomment-665232979) |

## Acceptance Criteria
- We've successfully handled Lighthouse's integration with Drupal service

**Comment by MickinSahni** [comment]
@jenniferlee-dsva tagging you on this to add any details re: how we'd like to verify everything's working as expected e.g. test results.

**Comment by jenniferlee-dsva** [comment]
Hi @MickinSahni - I'm trying to find the list of forms and keywords that @ncksllvn and I used as the validation criteria when Nick was first establishing the forms search page for the soft launch. I can't seem to find it in the list of epic tickets, but I think that would be good to use for validating the the web scrape swap with Lighthouse forms api. 

@ncksllvn - Might you remember where we compared the list of forms and keywords (legacy vs. modern) to validate the soft launch?

**Comment by ncksllvn** [comment]
@jenniferlee-dsva I think this is it? https://github.com/department-of-veterans-affairs/va.gov-team/issues/5693#issuecomment-592075548

**Comment by jenniferlee-dsva** [comment]
That's it! Thanks @ncksllvn . Will add details as AC in ticket @MickinSahni .

**Comment by MickinSahni** [comment]
Dependent on Lighthouse completing their switch

**Comment by MickinSahni** [comment]
Won't be actionable rest of this sprint, pulling into next preemptively

**Comment by MickinSahni** [comment]
Had a call with the Lighthouse team, who may have further questions for us. Will reach out to check-in

**Comment by ncksllvn** [comment]
Integration verified. We've already received the new fields on public API route, https://api.va.gov/v0/forms. Do a cmd+f search for `form_tool_intro` to see an example of a new field.

We'll still need to do a tiny bit of updating to our public API route to document the new properties but that's not a blocker for using these on the FE.

**Comment by jenniferlee-dsva** [comment]
>Do a cmd+f search for form_tool_intro to see an example of a new field.

What does this mean @ncksllvn ? (emoji: Homer Simpson)

**Comment by jenniferlee-dsva** [comment]
@ncksllvn  @MickinSahni

I checked all of the criteria items above. All looks good except the last item. 

- Previously, when you searched "housebound," the search brought back 1 form, the 21-2680. 
- Now, "housebound" brings back 0 results. This is not acceptable.

I did try a variation - "house bound" - with a space in between, and this brings back 3 results, one of which is the 21-2680. This is good. 

I noticed that when I opened up the actual PDF form, the form name is "...Housebound Status," but it appears that the form manager entered "Household" Status for the form name. I went into the CMS to manually override this for the FE. I'm not sure if that will resolve this issue - the API would need to pick up manually entered form name changes that are made in the CMS. 

Can we check this after tomorrow's migration/api refresh to see if my CMS change comes through? 
If not, I think we need the API itself to address this somehow. 

(I'm not able to @ Charly and Michael for awareness here for some reason.)

**Comment by ncksllvn** [comment]
> Can we check this after tomorrow's migration/api refresh to see if my CMS change comes through?

Exactly what I was thinking, because I _think_ your override should do the trick but I'm not sure. If it doesn't work, we can figure something out to make the API's search use some of the new fields from the CMS.

**Comment by jenniferlee-dsva** [comment]
I just checked @ncksllvn and the manual form name override works! I was even wondering if the corrected text would show up and it does! I'll go up and update the audit ^ and think we can close this as validated. fysa @MickinSahni 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/e4f335b8-15b2-4f13-b4c3-6e2e43dd505d)

**Comment by MickinSahni** [comment]
BIG DEAL. So you made the change ~3:30p ET? Wonder when Lighthouse picks up changes 🤔
