### ISSUE TITLE
Conduct and synthesize user research for urgent care mashup

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11150]
## Issue Description
Conduct and synthesize user research based on [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care-mashup/research-plan.md)

---
## Task 1
- [ ] Conduct user research sessions

## Task 2
- [ ] Synthesize results of user research 

## Output
- [ ] Research readout
- [ ] Revised design ready for front end implementation

## Acceptance Criteria
Revised design to include: 
- [ ] Defined color palette for all elements (foreground, background and fonts)
- [ ] Defined states 
      - Enabled vs disabled 
      - Hover vs active 
      - Focus
- [ ] Defined margin and padding spacing
- [ ] Defined fonts and sizes
- [ ] Defined iconography, as appropriate
- [ ] Field labels
- [ ] Error messaging, as appropriate
- [ ] References to style guide/design system components
- [ ] Link words and urls
- [ ] Responsiveness breakpoints
- [ ] Expected interactive behavior

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
[Link to research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care-mashup/research-findings.md)
