### ISSUE TITLE
[FE] Update order in Account Security section for a11y needs, sign in email content update

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#11169]
## Background

Jen Strickland pointed out that in the Account Security section we need to have all of the sections with an icon lined up.  If the icons are broken up then it's potentially difficult to read for people with cognitive issues.

We also updated the sign in email address content in the P&C section, we need to make the same update here for consistency.

## Specs

![Screen Shot 2020-07-13 at 11.46.02 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/cfd3c983-0916-48d0-b65f-cd93ae1dfb18)

**Sign in email address content:** To view or update your sign in email, go to the website where you mange your account information. Any email updates you make there will automatically update on VA.gov.

## Tasks

- [ ] Update section order
- [ ] Update sign in email address content

## Acceptance criteria 

- [ ] Matt/Tressa has reviewed and approved

**Comment by erikphansen** [comment]
Do we also have a ticket for the work to change the alignment of the check marks?

**Comment by tressaellen** [comment]
@erikphansen I think that must've slipped through the cracks...I can make that now. That's a more involved ask, correct? Like it should be its own ticket?

**Comment by tressaellen** [comment]
Related to #11196
