### ISSUE TITLE
Determine Form ID for Dependency Claims

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#11178]
## Goal
We need to make a final decision about which form name we are going to use prior to launch: "21-686C" or "686c-674" so that we can be consistent with how this form lives and functions in the current and future environments.

## Considerations
This is used as a form ID in several places in the code.  The older (rainbows) code that existed was using "21-686C" so when we started experimenting we used "686c-674".  Now there is code that exists for both.  We are at a crucial point now where we need to make a final decision on which one we are going to use going forward.

FE Implications
- Lowest level of effort, leave it as is?
- Archive the other 686 application
- Pre-fill
- How the data gets submitted
- `vets-JSON-schema` should match

## Tasks
- [x] As a team (do we need a meeting?), get together and discuss the merits of either one 
- [x] Identify all applicable locations
- [x] Make a decision

## Acceptance Criteria
- [x] The Form ID has been decided on by the team
- [x] Next steps have been documented and set in motion via a ticket

### Next Steps
- Incorporate this change

**Comment by kathleencrawford** [comment]
We have decided to use 686C-674 going forward and revisit removing/archiving the old rainbows code at a future date.  Tickets have been created for both FE and BE to update existing code and use 686C-674 for our current implementation.
