### ISSUE TITLE
Consider - review of Scafolding proces to stub out System with required nodes, determine best process moving forward

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11170]
## Tasks
- [ ] Document stub out process in github
- [ ] Set up time to reviewing this process and LOE to complete
- [ ] Determine better actions and possibility of Automation of this process moving forward.

## Acceptance criteria
* Process is documented in Github - VAMC-Upgrade
* Review of process is complete with Product owner and Product Manager to determine LOE and next actions
* Set story(ies) into Zenhub to accomplish next actions.
