### ISSUE TITLE
Share Payload for VRE (CH31) with Stakeholders

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11179]
## Goal
We want to share the output from the frontend of the CH31 feature in a JSON file that so that they can adapt it for an API they are putting together.  We can then more likely integrate with their system(s) and deliver structured data more effectively.

## Considerations
- This request is directly from the stakeholders
- It should be reiterated that this data structure is subject to change

## Tasks
- [ ] Create a simple JSON file that captures all the possible data fields that are involved with the CH31 feature:
  - [ ] Load the form, fill it out, and copy out the data structure from the Redux Chrome Extension
  
## Acceptance Criteria
- [x] A JSON file has been created that contains all the available data fields from the CH31 feature
- [x] The JSON file has been shared with the stakeholders or a member of the team that can share it
