### ISSUE TITLE
Get SME approval and publish 2018 and 2019 historic Disability rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11171]
## Issue Description
The cloned historic rates pages for 2018 and 2019 disability pages need to be approved by SMEs and published in order to retire the legacy historic rates pages. Several pages also need to have these historic rates pages linked to from their pages.

## Tasks
- [x] Send batch of 2018 and 2019 disability rates pages to SMEs (Beth)
- [x] Make any changes to pages based on SME requests (Selina)
- [x] For the group of stacked links at the bottom of the page: Update the 2018 and 2019 links there to point to our new modern page rather than to the legacy page (Selina)
- [x] Review pages (Randi)
- [x] Publish pages (Randi)
- [x] Add pages to left nav (Randi)
- [x] Validate pages on live site (Anne/Randi)

**Historic rates pages to be reviewed and published:**
- [ ] 2018 DIC Parents http://preview-prod.vfs.va.gov/preview?nodeId=6266
- [ ] 2018 DIC Spouse and Children http://preview-prod.vfs.va.gov/preview?nodeId=6203
- [x] 2018 Birth Defect rates http://preview-prod.vfs.va.gov/preview?nodeId=6189
- [x] 2018 Special Allowance rates  http://preview-prod.vfs.va.gov/preview?nodeId=6190
- [x] 2018 Special Monthly Compensation rates  http://preview-prod.vfs.va.gov/preview?nodeId=6190
---

## Acceptance Criteria
- [ ] Historic rates pages live on site and links from other pages to new pages all work
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
The rates pages checked off above have all been published and added to the left nav. Links to these pages have also been put on the corresponding 2020 rates pages in the historic links section. Still to review are the two DIC pages. FYSA @MickinSahni

**Comment by RLHecht** [comment]
Closing this ticket. I captured the DIC rates pages work that still needs to be completed in a new ticket #12347 FYSA @MickinSahni @bethpottsVADEPO

**Comment by bethpottsVADEPO** [comment]
Reopening to ask @RLHecht to switch the order of 2018 and 2019, so that 2019 comes first for all 4 disability rate types.
<img width="279" alt="Screen Shot 2020-08-11 at 7 59 26 AM" src="https://user-images.githubusercontent.com/66026798/89913847-0cdd3100-dba9-11ea-8c0d-ab108b27ab45.png">

**Comment by bethpottsVADEPO** [comment]
After this left nav issue is fixed, let's close this ticket and open a separate on for the remaining two SME approvals for DIC pages, which need to go to the pension SME (not the disability SME). @RLHecht could you create that ticket so we can close this one? @MickinSahni FYSA

**Comment by RLHecht** [comment]
Just made these left nav fixes. Will validate later this afternoon.

**Comment by bethpottsVADEPO** [comment]
Thanks, @RLHecht !! We'll survive the rates work, I know we will.

**Comment by RLHecht** [comment]
Left nav is showing correctly now. Closing ticket!
