### ISSUE TITLE
[Development] BDD to 526: Copy BDD Components and Form Logic to 526

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#11183]
## Issue Description
The current BDD form is to be merged into the 526 form. This ticket is for the steps of copying all the custom BDD components into 526 and for adding new `depends` logic for the various pages based on the military history separation date entered. All custom BDD components will need to be shown and their 526 counterparts will need to be hidden when in the BDD flow, and all 526 components not in the current BDD flow will need to be hidden when in the BDD flow. Again, being in the BDD flow will be determined by the most recent military history separation date. When custom BDD components are copied, they will need to have their file names changed (add BDD to the end?) as the 526 components share the file names. This ticket is not for deleting the current BDD form, that will happen at a later date.

## Tasks
- [ ] Copy custom BDD components to all-claims
- [ ] Add `depends` logic based on most recent military history separation date for all necessary components

## Acceptance Criteria
- [ ] BDD can be completed in the 526 form flow
