### ISSUE TITLE
[Development] BDD to 526: Introduction Page Changes

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#11188]
## Issue Description
This ticket is to insure that the introduction page for 526 properly covers all information for both BDD and 526. This will be necessary once the BDD form flow lives inside the all-claims form. I believe that minimal changes, if any, will be required for this as the two introduction pages are already very similar. It may be necessary to connect with a designer on this, but there will likely be future changes once gating moves to the introduction page. Once this is the case, we can conditionally show introduction pages based on gating.

## Tasks
- [ ] Verify that the introduction page for 526 covers all appropriate information for BDD and 526

## Acceptance Criteria
- [ ] The introduction page for 526 covers all necessary information from the BDD introduction page in addition to the current 526 introduction page

**Comment by kevinstachura** [comment]
A few things about this ticket:

- Public Websites is going to be [condensing the information on some disability claim pages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-benefits-at-discharge.md) to 'live' on the /how-to-file-claim/ page. Not sure what that looks like exactly, but the assumption is that they will be adding BDD-specific info and 526 general info to that page.
- To my understanding, the 'wizard' is intended to live on its own intermediary page, between the /how-to-file-claim/ page and the actual intro page for the form. Feel free to let me know if I may have interpreted that incorrectly.
- The introduction page (after you get through the gating) should be either 526 disability claim or BDD specific, right? That way we can provide more specific information to that target audience after they have gone through the wizard questions.

This all said, I think we're probably fine on our end, but it's worth knowing what Public Websites has planned for the change of content on the /how-to-file-claim/ page. @luke-gcio do we have any insight on this as of right now?

**Comment by kevinstachura** [comment]
Ok, so I did make a small change to the BDD intro page: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421577781_Introduction_BDD_-_Unauthenticated_-_1

Before we were not expecting that the user would be uploading their service treatment record. I have worked that into the first bullet within the 'prepare' step.

**Comment by Mottie** [comment]
I'm working on this now, with some additional tasks:

- [ ] Update BDD content within the intro page
- [x] Update form title based on all-claims vs BDD flow
- [ ] Update breadcrumb & document title based on flow
