### ISSUE TITLE
[Development] BDD to 526: Remove BDD Form Code

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#11190]
## Issue Description
This issue is meant to happen once all other BDD to 526 tickets are complete and the BDD form can be completely filled out inside the 526 flow. All references to the separate BDD form (not the BDD flow inside of 526) should be removed.

## Tasks
- [ ] Remove all separate BDD form references
- [ ] Copy over Cypress test data (maximal one, minimal too)

## Acceptance Criteria
- [ ] The separately created BDD form is removed from vets-website and only the BDD form flow remains inside of 526
