### ISSUE TITLE
[Development] 526 Military History Save Button

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#11191]
## Issue Description
This is a discovery ticket for determining if adding a "Save" button is possible for the military history page in the all-claims form. Currently, there is no way to escape "edit mode" without adding another service period or going to the next page and then going back a page.

## Tasks
- [ ] Determine if it is possible to add a "Save" button to the military history page in the all-claims form
- [ ] If adding the button is possible, either create a follow up ticket or add the button if it is a quick enough solution

## Acceptance Criteria
- [ ] A follow up ticket is created for work if applicable or a solution is implemented

**Comment by cvalarida** [comment]
Is the idea here to just change the view mode of the last item in the array? Would "save" do anything fancy with save in progress or submitting stuff early?

**Comment by Mottie** [comment]
Yes, when you return to a page with already entered data, the card is in "edit" mode. We wanted the card to be collapsed once he user finishes editing. The "save" button is still the default behavior, it just wanted appearing in the last entry.

**Comment by Mottie** [comment]
Added in https://github.com/department-of-veterans-affairs/vets-website/pull/13585
