### ISSUE TITLE
[Development] 526 New Condition Auto-suggest Error Message

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#11192]
## Issue Description
Discover if it is possible to change the auto-suggest error message for adding a new condition in the all-claims form. If it is possible, create a follow up ticket or implement the solution if it is simple enough. Consult with design on what the updated error message should say.

## Tasks
- [ ] Determine if it is possible to change the auto-suggest error message for adding a new condition in the all-claims form
- [ ] If possible, create a follow up ticket for the work or implement the solution if simple enough

## Acceptance Criteria
- [ ] A follow up ticket is created for the work or a solution is implemented

**Comment by ndsprinkle** [comment]
This is the error message that needs to be changed: 
![image](https://user-images.githubusercontent.com/53942725/88302249-9fd62a00-ccd3-11ea-8b6a-9a2f95636ba9.png)
