### ISSUE TITLE
[DISCOVERY] Vet Center service taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11198]
## Issue Description
We need to develop a taxonomy for the services offered at Vet Centers. 
The taxonomy will be used to:

- Standardize names for Vet Center services 
- Make services recognizable and easy to search by Veterans and families of enlisted

## Goal
Map the services offered at Vet Centers to Veteran-facing plain language

---
## Tasks
- [ ] Work with Meg to define the process for creating a service naming convention for Vet Centers

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
closing as duplicate to #9962

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/vet-centers.md
