### ISSUE TITLE
[Development] 526: Remove Redundant New Conditions Question

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#11193]
## Issue Description
In the all-claims form, we ask the user twice if they have any new conditions they want to add to their claim. In some situations, the question is only asked once, but this question is still unnecessary as the user has to select Yes to continue the form. This boolean question should be removed, but it is important to identify and adjust all the locations where this boolean is referenced so that they check a different value.

## Tasks
- [ ] Remove the unnecessary boolean question that asks users if they have any new conditions they want to add to their claim
- [ ] Adjust the places where the boolean is referenced to check another value that represents the same thing

## Acceptance Criteria
- [ ] The "Do you have any new conditions..." question is removed from the all-claims form
