### ISSUE TITLE
Prep for Vet Center Discovery

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11195]
## Issue Description
Prep for Vet Center Discovery in Sprint 27

## Tasks
- Quick discussion to brief Leyda on existing HS taxonomy and how it relates to the plan to map to Vet Center services
- Connect with Jessica and set up meetings for the first week in August
- Connect with Meg and set up meetings for the first week in August

## Acceptance Criteria
- [x] Meeting scheduled for foundation on HS taxonomy
- [x] Initial meeting scheduled for Discovery with Jessica
- [x] Initial meeting scheduled for Taxonomy with Meg 
- [x] Project kickoff with VSP requested

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Foundation on HS taxonomy on July 24, 2020
