### ISSUE TITLE
Rename CH31 Feature to Veteran Readiness and Employment (Design)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11208]
## Story
Given changes shared with us from stakeholders, we need to change the name of the VRE CH31 feature from Vocational Rehabilitation and Employment to Veteran Readiness and Employment in as many places it appears so that we can deliver an up to date product that aligns with the stakeholders vision.

## Tasks
- [x] Rename the title in the product outline and within the body text, as needed
- [x] Rename the title in the mockups, user flows and prototypes, as needed
- [ ] Where else?

## Acceptance Criteria
- [x] The title has been updated in the product outline, and within the body text, as needed
- [x] The title has been updated in the mockups, user flows and prototypes, as needed

**Comment by sporeboy** [comment]
Revisions made to CH31 prototype: https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526673

CH36 prototype wizard checked: https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/130194084

No XD mockups have CH31 text.

**Comment by sporeboy** [comment]
Went through Github--I think I changed all instances.
