### ISSUE TITLE
[DISCOVERY] Community Care Taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11207]
## Issue Description
How might we make searching for community care providers (in VA's network) more intuitive and Veteran friendly?

## Current behavior
Veterans searching for community care providers (in VA's network) now must use a typeahead feature which is populated with hundreds of possible services and specialties based on NUCC codes.

<details> 
  <summary>There may be multiple representations of a single type of care, which may return different results. </summary>

For example:
Podiatrist
Podiatrist, General Practice
Podiatrist, Public Medicine
Podiatrist, Primary Podiatric Medicine
Podiatrist, Radiology
Podiatrist, Sports Medicine
Podiatrist, Foot & Ankle Surgery
Podiatrist, Foot Surgery

</details>

There are obscure service offerings which may not offer results when searched,

<details> 
  <summary>Some common specialties are not represented. For example, "cardiology" is not an option, except for the following:
</summary>

Advanced Heart Failure and Transplant Cardiology
Interventional Cardiology
Nuclear Cardiology
Pediatric Cardiology
Technician, Cardiology
Specialist/Technologist Cardiovascular

</details>

Most of the names are not Veteran facing plain language

There is an existing Health Services Taxonomy which could be used to flatten this list into something more friendly and intuitive.

## Tasks
- [ ] Identify which services will be implemented first in VAOS -> could be our MVP for this work
- [ ] Meet with Meg about her Q3 2020 priorities to set expectations for this work

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
VAOS Top 5 =

1. Audiology (and hearing aid support)
2. Nutrition/food
3. Podiatry
4. Primary Care
5. Optometry
