### ISSUE TITLE
[ENGINEER] Map out and Create Admin and Editorial Menus for VISN-1 Systems [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11201]
## User Story or Problem Statement
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Instructions to set up Menus for VAMC](https://docs.google.com/document/d/1fz-m_4Eo4Ib7g4s_3pk7Hz4N3uaNnCD1lAppp6KDMrk/edit?ts=5ee3aae7)

## Tasks
_Creation of the following Drupal types/menus Sections_
- [ ] VA Bedford health care
- [ ] VA Boston health care
- [ ] VA Central Western Massachusetts health care
- [ ] VA Connecticut health care
- [ ] VA Maine health care
- [ ] VA Manchester health care
- [ ] VA Providence health care
- [ ] VA White River Junction health care
*Complete the following process (In alignment with the Menu creation document):
- [ ] Create Sections in Prod
- [ ] Sync DB to local
- [ ] Create menus locally
- [ ] Edit content types to each System
- [ ] Organize VAMC admin menu for VISN 1
- [ ] Create PR and commit to Steve Wirt and Kevin Walsh

## Acceptance Criteria
_Validation that systems are available in prod.cms.va.gov for creation/stub out of nodes:
- [ ] Correct Systems are available in drop down menu in Prod.cms.va.gov
- [ ] PR has been accepted and Merged with Master by CMS team
- [ ] Menu items are now available in VACMS admin content drop down
