### ISSUE TITLE
[BUG] 686c - Deselected Option Does Not Get Removed From Flow with SIP Data

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#11200]
## Description
In staging there's a bug where loading a 686c that has been saved in progress will not remove a workflow from the form if the option is deselected in the wizard. 

## Steps to reproduce
1. Go to staging.va.gov and log in with **vets.gov.user+1**
2. Go to [https://staging.va.gov/view-change-dependents/add-remove-form-686c/686-options-selection](https://staging.va.gov/view-change-dependents/add-remove-form-686c/686-options-selection)
3. Deselect the add-child workflow
4. Progress bar does not update to three steps, instead stays at 4. 
5. Select another workflow, such as report the marriage of a child. 
6. Traverse the form.
7. You should see the additional evidence page for add-child (a page from the removed workflow). 

## Expected behaviour
1. Logging in with SIP data and then deselecting an option should update the progress bar to reflect the removed flow. 
2. No orphaned pages should be present from a workflow that was deselected. 
3. All associated SIP data should be removed from `formData` on workflow deselect. 

## Possible solutions
1. SIP data loads into the frontend via a `loadedData` property on the state form object. This loaded data is used when the form is initially rendering. We need to figure out how to make sure a workflow's data is removed from `formData` and `loadedData` when it is brought in from SIP data and then removed on the options selection page.  

## Tasks
- [ ]  Ensure add-child additional evidence page is removed if the option is deselected.
- ~~[ ]  Make sure formData is updated properly when a flow is deselected. (This could mean removing the data from state).~~

## Acceptance Criteria
- [ ] The progress bar updates when option is deselected
- [ ] Pages are no longer orphaned
- [ ] All associated Save in Place data should be removed from `formData` on workflow deselect

**Comment by micahchiang** [comment]
Finding:  All unchecked workflows get removed from the final payload, so it seems we just need to handle removing the additional evidence pages when an option gets deselected. This just involves an update to the `depends()` function in the formConfig object.
