### ISSUE TITLE
[Content] Translate and update VA Oklahoma City Legacy pages to fit within new VAMC-upgrade template pages [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11218]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Oklahoma City Medical Center legacy Site](https://www.oklahoma.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-19 Content Folders](https://drive.google.com/drive/folders/1KVjgw4Z56Zm3m1TVTDktpKk9aKVpP9ms)

## Tasks
_Review content pages created for below_
*Work from Legacy page to New Drupal page and update page with new content and system name information.  In some cases cut and paste and then review and update.
*Include the following pages for update: 
- [x] System Home page 
- [x] Mission and Vision page
- [x] Chaplain page
- [x] Policies page (Focus on Visitor, system access information section only)

## Acceptance Criteria
* All Drupal pages will be updated in the system and ready for review by outside source.
* System Home page 
* Mission and Vision page
* Chaplain page
* Policies page (Focus on Visitor, system access information section only)
* Page must be updated in CMS/Drupal.
* An archive page can be saved to Google drive in Word Document for review, but is not required.

**Comment by kimmueller1** [comment]
Includes 6 chaplain staff profiles.
