### ISSUE TITLE
686c - Form workflows should appear in the same order as the options selection screen

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#11212]
## Description
Recently, the order of the options on the selection screen was updated. The order of the workflows in the form should be in the same order they appear in options selection screen. 

## Considerations
- e2e tests may need to be updated  

## Tasks
1. Reorder the chapters in the `form.js` file of the 686  
1. Reorder the flows of the 686 e2e tests  
1. Conduct 2e2 test  

## Acceptance criteria
- [ ] Chapter order has been updated  
- [ ] e2e tests have been updated  
- [ ] e2e test s have been completed  
- [ ] Pull request has been merged
