### ISSUE TITLE
Board appeals pages consolidation

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#11229]
## Issue Description
There are two board appeal pages on VA.gov

**Current:
Board Appeals**

<https://www.va.gov/decision-reviews/board-appeal/>

- Lives within decision reviews

- Part of the current decision review process

**Legacy:**

**Board of Veterans' Appeals (BVA)**

<https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/>

- Lives within disability

- Part of the legacy appeals process

To avoid confusion between the two pages, PW had explored retiring the legacy page. Fred Somers (AMO) and Elizabeth Murphy (the Board) objected, citing that:

- Many Veterans remain in the legacy process (some possibly for years) and need information that only appears on the legacy page

- Redirecting this page to the decision reviews board appeal page takes the Veteran to step 1 of downloading VA Form 10182. This could mislead users--who have been waiting for years for a hearing with a BVA judge--into thinking they need to reapply/start the process over again.

There are links to this page in at least two locations:

[Manage a legacy VA appeal page](https://www.va.gov/disability/file-an-appeal/):
![image.png](https://images.zenhubusercontent.com/5d41d21a6db71633490a2764/25916369-de54-4d5c-bf71-1244e228155c)

[Board Hearings with a Veterans Law Judge page](https://www.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing/):
![image.png](https://images.zenhubusercontent.com/5d41d21a6db71633490a2764/ce1ba92b-62c1-46ed-b123-022e2a481580)
---
## Tasks
- [ ] PW (Laura) to evaluate two possible solutions.
1) Create more differentiation between the two pages:
- - Revisit the h1s
- - Revisit page content
2) Merge the legacy page content into the decision reviews page (Elizabeth Murphy suggested we consider this, so it already has some SME support):
- - Merge content effectively so users looking for either page can easily find the content they need
- - Find any links to the legacy page (in addition to the two identified above) and redirect to decision reviews page
- [ ] DEPO (Beth) chooses the best path forward
- [ ] PW (Laura) provides a Word doc capturing revised content
- [ ] DEPO (Beth) reviews Word doc and provides feedback
- [ ] PW (Laura) makes changes in Drupal
- [ ] PW (Randi) reviews/copy edits
- [ ] PW (Laura) provides preview link(s) to DEPO
- [ ] DEPO (Beth) provides preview link(s) to SMEs for review, and provides documented SME feedback to PW
- [ ] PW (Laura) revises content per SME feedback
- [ ] PW (Randi) reviews/copy edits
- [ ] DEPO (Beth) secures SMEs' final approval
- [ ] PW (Randi) publishes page(s)

## Acceptance Criteria
- [ ] _Final board appeal page(s) is/are live on VA>gov_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
FYI, you will need a redirect regardless of whether you keep 2 pages or merge them.  Either we move the legacy page to a new URL or we retire it and will need to consider where we redirect it to.

**Comment by mnorthuis** [comment]
@bethpottsVADEPO just want to check in on this...do we want to move the legacy page from Disability to Decision Reviews for now until we can work on any writing work?  It would involve a Drupal URL change along with adding it to the left nav,  and a FE redirect.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis I just haven't had time to take action on this one. I will carve out time on Friday to figure out next steps. I haven't been in touch with the stakeholders yet about it.

**Comment by mnorthuis** [comment]
@bethpottsVADEPO Checking in on the status of this one.  Are we ready to move this into the decision reviews area?

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Can we meet to discuss the URL?

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Putting this here for us to work on... 

These are the H1s for the two existing board of appeals pages that need to be considered/differentiated:

https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/
Board of Veterans' Appeals (BVA) hearing

https://www.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing/
Board hearings with a Veterans Law Judge

When we move the legacy BVA page that currently lives in the disability hub, it'll be a child page under:
https://www.va.gov/decision-reviews/legacy-appeals/

Suggested new URL: https://www.va.gov/decision-reviews/legacy-appeals/TKTKTK
Suggested new  H1: Board hearings TKTKTK

**Comment by mnorthuis** [comment]
Tagging this ticket to use as the IA request for the collab cycle touchpoint for this work.

**Comment by mnorthuis** [comment]
@bethpottsVADEPO, it looks as though for legacy/older appeals, there are 2 things they can still do, 1) request a priority review and 2) request a board hearing. 

These 2 items are both linked to from the main legacy appeals page and will also appear in the left nav, so I'm going to include both of them below just to show the full picture.   I want to bring some consistency into our current link labels with H1s and URLs, so I'm suggesting one change in addition to the work to bring the legacy board page into this area.  Let me know your thoughts.


**"Request priority review" page:**
This page already exists and is in the right place, but the entry point links do not all match. 

- URL (NO CHANGE): https://www.va.gov/decision-reviews/legacy-appeals/priority-review/
- H1 (NO CHANGE): Request a priority review 
- Left nav (NO CHANGE): Request a priority review
- Breadcrumb (NO CHANGE): Request a priority review
- In-line link: Learn how to request the Advanced on Docket status - this is on the [legacy appeals page](https://www.va.gov/decision-reviews/legacy-appeals/) (step 6)
  - **Recommendation:** I recommend the link text be updated to match the leading terminology of the H1, left nav and URL; example:   "Learn how to request a priority review, or Advanced on Docket status." 


**Legacy request board hearing page:**
- URL (PROPOSED): https://www.va.gov/decision-reviews/legacy-appeals/board-hearings/
- H1: Board hearings for older decisions
  - **Recommendation:**   I would add "Request a" to the beginning of this, to be consistent with the priority review page - "Request a Board hearing for older decisions"
- Left nav (PROPOSED): Request a board hearing
- Breadcrumb (PROPOSED): Request a board hearing
- In-line link: Learn more about hearings at the Board - this is on the [legacy appeals page](https://www.va.gov/decision-reviews/legacy-appeals/) (step 7)
  -  **Recommendation:** I recommend adding the action language into the link for consistency; example "Learn more and request a board hearing"

**Comment by mnorthuis** [comment]
@bethpottsVADEPO just checking on on our favorite ticket :-)

**Comment by mnorthuis** [comment]
@bethpottsVADEPO Here's what I think we have left to do:

- [ ] align on recommendations above so we know what needs to be changed
- [ ] Submit [security & privacy review issue](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=f1337%2C+joeniquette&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)
- [ ] Submit a [redirect issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- [ ] Make necessary content changes
- [ ] Move page in Drupal and implement redirect
- [ ] Implement left nav changes (remove from Disability, add to Decision Reviews)

I can submit the tickets needed above as soon as we align on changes.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis The other piece to this is connecting with OAR/decision review SMEs to get their buy-in. Every time I've tried to set up that meeting, I've heard crickets from their side. So first, let's align in a quick 15-minute meeting about the H1, etc. Then one of us can reach out to them with an outline about what's changing and just say we'll be moving ahead with this and to let us know if they want a call.

**Comment by mnorthuis** [comment]
Holding on this work for stakeholder review of all legacy appeal content and whether content is still applicable.

**Comment by mnorthuis** [comment]
@bethpottsVADEPO Did we hear back from stakeholders on this?  Can we move forward?
