### ISSUE TITLE
Debt management: Build out full content page in Drupal

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#11221]
## User Story
As a Veteran who owes money to VA, I need to have easy access to information about my VA debt and how to resolve it.

## Issue Description
We need to build out the full Drupal landing page to support the new debt management tool.

---
## Tasks
- [x] Write the content for the identified accordions (Selina)
- [x] Edit accordion content (Danielle, Beth)
- [x] Build page in Drupal (Selina)
- [x] Review page in Drupal and keep as **draft** until launch (Randi)

## Acceptance Criteria
- [x] Page is built in Drupal and ready to share with SMEs: **Deadline of 7.24.20**

## Documentation

- **Content with accordions identified:** [Manage your VA debt_unauthenticated tool landing page_content for usability testing_7.9.20](https://app.zenhub.com/files/133843125/51b7b1e1-8909-4a53-bbf3-10b1f8411def/download)
- **Accordion FAQ content so far:** [Selina's work to date on accordion FAQs](https://app.zenhub.com/files/133843125/4f7f086f-3c87-4030-bc26-809bcf56cb94/download)

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @MickinSahni

**Comment by lunascoop** [comment]
Hi @DanielleThierryUSDSVA here's the copy I drafted for the identified accordions.
[Manage VA Debt page copy - added accordion copy.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4961597/Manage.VA.Debt.page.copy.-.added.accordion.copy.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @lunascoop! Reviewing and will have edited version ready to flow into Drupal today.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop @RLHecht . I've made my edits, but wanted to run by Beth as well for a 2nd look on our end. Will be sending to you this afternoon to flow into the page. If we could have the page ready by EOD, that would be much appreciated. Please let me know if you foresee any problems with that. Thanks!

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA that should work. I've already created the Drupal page w/react widget. All that's left is to input the content into the accordions.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome. Thanks very much, @lunascoop!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop @RLHecht. Per slack, this morning is good for finalizing this. Doc with edits/notes attached. Note there are a few edits to content on page outside of accordions as well. Feel free to reach out with any questions. Thanks![Manage.VA.Debt.page.copy.updates.7.28.20](https://app.zenhub.com/files/133843125/dadf4b45-7727-4416-bb05-acffb4472d54/download)

**Comment by lunascoop** [comment]
Hi @RLHecht the page is ready for review. I had trouble formatting some copy in the "What happens if I don't pay my debt" FAQ. Specifically, there's non-bulleted text below the "90 days" bullet point that needs to be aligned/indented to match the "90 days" bullet point. I wasn't sure how or if that's possible.

Here's the node link: http://preview-prod.vfs.va.gov/preview?nodeId=6521

**Comment by RLHecht** [comment]
@lunascoop @DanielleThierryUSDSVA I've reviewed the page. Some minor copy tweaks and I also updated all numbers to include aria labels. For that bullet point, I just did a soft return. Let me know if that's what you meant for the alignment.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you both! Closing this issue, since this portion of the work is complete.
