### ISSUE TITLE
Debt management: Socialize with SMEs and incorporate any changes

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#11222]
## User Story
As a Veteran who owes money to VA, I need to have easy access to information about my VA debt and how to resolve it.

## Issue Description
We need to review the Drupal page with SMEs and incorporate changes to be ready for launch.
---
## Tasks
- [x] Shared with team for sharing with SMEs
- [ ] Incorporate any changes into Drupal page: **Targeted deadline: July 31** 

## Acceptance Criteria
- [ ] Page reviewed and approved by SMEs 

## Documentation

- **Content with accordions identified:** [Manage your VA debt_unauthenticated tool landing page_content for usability testing_7.9.20](https://app.zenhub.com/files/133843125/51b7b1e1-8909-4a53-bbf3-10b1f8411def/download)
- **Accordion FAQ content so far:** [Selina's work to date on accordion FAQs](https://app.zenhub.com/files/133843125/4f7f086f-3c87-4030-bc26-809bcf56cb94/download)

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @MickinSahni. This is due July 31 so putting in sprint 26 for now. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. We'll have the full page built out in Drupal and ready to share with SMEs as a preview by tomorrow morning. Would you be able to send along with a request for feedback by EOD July 31 (or August 3 if we want to give full week)? Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler @mattpointzxer0 @rileyorr @rebeccawalsh Here's a preview link to the page to share with SMEs: [preview-prod.vfs.va.gov/preview?nodeId=6521](preview-prod.vfs.va.gov/preview?nodeId=6521). You need to be signed into the VA network to view. If you anticipate any issues with SMEs being able to view, please just let me know and we can provide a pdf as well.

**A few notes:**

- Added 1 additional FAQ (the first one around why do I have debt)
- For the most part, this content is based on the existing content on the debt management subdomain. I did include some info around late fees after 30 days and what happens if you don't pay after 60, 90, 120 days on a combination of the debt management site and my understanding of debt from writing the health care debt section. So I'd like to ask the SMEs to please specifically make sure that info is 100% accurate in this context and provide any needed accuracy updates.
- We do ask for factual feedback and not voice/tone from SMEs since we're writing in the established VA.gov voice and tone and following plain language/web writing best practices. If you'd like me to walk SMEs through any of this content, just let me know.

Thanks!

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA I cannot get to the preview link - I can share this ahead of our standing meeting tomorrow morning. Thanks, Leah

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. Is it working now that you're on the network?

**Comment by DanielleThierryUSDSVA** [comment]
FYSA while I'm out next week (Mon-Wed) @MickinSahni @bethpottsVADEPO 

**Status update 8.7.20:**

- SMEs are reviewing the content. Leah and I have an email thread going with them, and they're aware that I'm out Mon-Wed next week and will respond to any questions/feedback when I return. Shouldn't be any action needed on content while I'm out.
- Leah had asked about if we could use a feature flag to publish the page just for UAT testing users. I raised this in PW channel and a discussion with Nick started there. I've created a ticket to begin tracking the work: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12250.

**Comment by leahkeeler** [comment]
Thanks @DanielleThierryUSDSVA I will f/u on content changes with DMC and give them a deadline. Thanks again for all your help

**Comment by leahkeeler** [comment]
Here is the feedback from the DMC SMEs 


Under “What types of debt can I check with this tool?”
Can we include the Burial, Voc Rehab debts?
The home loan debt can be tricky. We are talking internally about this.
 

Under “Who can I call for help with my debt questions?”
“Paying a debt or completing a Financial Status Report” does not adequately cover the reasons why they should contact DMC
Why are the best times to call between Tuesday and Thursday from 11:30-1:15 (or 10:30-12:15 central)? That is when a quarter of the agents are off the phone taking lunches… Our lunches are split into 4 times from 11:00am – 1pm central. Would 10:30 – 12 eastern (930- 11central be better) be a better time to offer? The afternoon timeframe is good.
 

Under the FAQ “If I can’t pay all or part of my debt, what should I do?”
 

For the 4 options, can we list benefits offset first as that is our preferred method of repayment and would be taken in lieu of cash payments if they are active.
 

Under FAQ “If I disagree with my debt statement, what should I do?
Can we list the 30 day criteria at the top? It almost seems misleading that we say right away that if you disagree, we will stop collections… We will but it has to be within 30 days… I know we mention this below but people seem to never read the entire write-up, just stop when they get the information they are wanting.
Do we want to provide how to submit waiver requests electronically in addition to the fax and mailing address?
Under FAQ “How do I complete the FSR?”
Do we want to include how to submit the FSR electronically in addition to the fax and mailing address?

@lunascoop are you writing the content? LMK if this makes sense

**Comment by leahkeeler** [comment]
Here are two additional comments: 

There is a “note” listed that alludes to this so if we add any language about balance I suggest we add it here.
 

“…We’ll confirm the amount you owe so you don’t overpay as the balances shown are not real-time.”
Use IRIS for contact us, only use the ops box for areas to submit items (like FSR, Waiver)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. Here are notes re: incorporating feedback. These changes will go live in this afternoon's deploy (so around 3:30/4:00 p.m.). Please let me know if there are any follow-up changes and/or if the SMEs would like to talk through anything. Thanks! 

_Under “What types of debt can I check with this tool?”
Can we include the Burial, Voc Rehab debts?
The home loan debt can be tricky. We are talking internally about this._
- Added "burial and memorial expenses" and "vocational rehabilitation services (VR&E)"; left 
"home loans" for now until we have confirmation to remove.

_Under “Who can I call for help with my debt questions?”
“Paying a debt or completing a Financial Status Report” does not adequately cover the reasons why they should contact DMC_
- Added "Paying or managing a debt" to broaden that category (and had to remove specific VA Form number to accommodate the extra characters and stay within our >70 character limit for H2s and H3s). If SMEs can provide further direction around what else might be missing here, we can adjust further. 

_Why are the best times to call between Tuesday and Thursday from 11:30-1:15 (or 10:30-12:15 central)? That is when a quarter of the agents are off the phone taking lunches… Our lunches are split into 4 times from 11:00am – 1pm central. Would 10:30 – 12 eastern (930- 11central be better) be a better time to offer? The afternoon timeframe is good._
- We picked up this messaging about timing from the debt management site. I just double checked, and it looks like we missing converting the 12:15 p.m. to ET...so the debt management site says "10:30 a.m. to 12:15 p.m." and ours should then have read "11:30 to 1:15 p.m." But it sounds like that's not the latest info anyway, so I've changed to "10:30 a.m. to 12:00 noon" per this note. If this needs to change again, just let me know.

_Under the FAQ “If I can’t pay all or part of my debt, what should I do?”
For the 4 options, can we list benefits offset first as that is our preferred method of repayment and would be taken in lieu of cash payments if they are active._
- Yes, no problem. Moved offsets to Option1. 

_Under FAQ “If I disagree with my debt statement, what should I do?
Can we list the 30 day criteria at the top? It almost seems misleading that we say right away that if you disagree, we will stop collections… We will but it has to be within 30 days… I know we mention this below but people seem to never read the entire write-up, just stop when they get the information they are wanting._
- Yes. Moved this to the top. Also adjusted the language around the other timing of when you need to submit your waiver request for consideration so that the transition between the 2 timing messages is clear. Now reads:

You can submit a waiver request to ask us to stop collection on your debt. If we receive your request within **30 days** of when we sent your debt letter, we’ll stop collection until we make a decision on your request.

To have your waiver request considered, you must submit it within a certain period of time from when you received your first debt notification letter. If we receive your request after 30 days, we won't stop collection while we make a decision.

**You must submit a waiver request within:**

- 180 days for disability, education, or pension debt

- One year for home loan debt

If we accept your request, you won’t have to pay the amount waived.

_Do we want to provide how to submit waiver requests electronically in addition to the fax and mailing address?_
- We can, yes. We picked up the instructions for how to submit from the debt management site. In the instructions on that site, I only see mail and fax. If SMEs can provide info for submitting electronically, we can add. Thanks!

_Under FAQ “How do I complete the FSR?”
Do we want to include how to submit the FSR electronically in addition to the fax and mailing address?_
-We can, yes. Same note as above. Thanks! 

_There is a “note” listed that alludes to this so if we add any language about balance I suggest we add it here.
…We’ll confirm the amount you owe so you don’t overpay as the balances shown are not real-time._
- I'm not sure what this comment is asking us to do. We have the following note re: balances. **Note:** Are you paying the full balance of a debt or do you receive monthly VA benefit payments? Please call us at 800-827-0648 (or 1-612-713-6415 from overseas) before making a payment. We’ll confirm the amount you owe so you don’t overpay.

Is this note asking us to add "the balances shown are not real-time"? If yes, I would recommend adding the follow language (shown below in italics for emphasis only - would not be italics on site). 
**Note:** Are you paying the full balance of a debt or do you receive monthly VA benefit payments? Please call us at 800-827-0648 (or 1-612-713-6415 from overseas) before making a payment. We’ll confirm the amount you owe so you don’t overpay. _Balances listed in your debt letters may not reflect the most up-to-date amount._

_Use IRIS for contact us, only use the ops box for areas to submit items (like FSR, Waiver)_
- I'm not sure what this comment is asking us to do. What is the "ops box"? We provide phone, fax, and address as ways to contact and submit items. Can SMEs provide more context?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Would you be able to check my updates on this page for any errors, and set to publish ahead of today's deploy? https://github.com/department-of-veterans-affairs/vets-website/pull/13882#event-3660083392

Thank you!

**Comment by rileyorr** [comment]
Hi @DanielleThierryUSDSVA! Thanks for providing an update on this work :) 

> Under “What types of debt can I check with this tool?”
Can we include the Burial, Voc Rehab debts?
The home loan debt can be tricky. We are talking internally about this.
Added "burial benefits" and "vocational rehabilitation services"; left
"home loans" for now until we have confirmation to remove.

This tool's iteration doesn't include burial, vocational rehab debts, or home loan debt. So, I don't think it makes sense to include those debt types under "What types of debt can I check with this tool?" since folks won't actually be able to check those debt types. I apologize that this didn't come up sooner!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rileyorr. Thank you for letting me know! This was a request from the SMEs passed along to us so thank you for clarifying!! If it's not available in the tool, we definitely shouldn't add.

**Comment by RLHecht** [comment]
These changes have all been reviewed and published. FYSA @DanielleThierryUSDSVA
