### ISSUE TITLE
[FE] Connected apps - disconnected app placement/spacing

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#11226]
## Background 

Related to: #11225

We noticed some spacing issues in Connected apps. There should be more space between the content and the disconnected app notification box. The notification is also in the wrong place, it should be above the text. This screenshot is from staging:

![Screen Shot 2020-07-14 at 4.06.40 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/cf44b7eb-62f3-4b9c-8ce7-b31dad0cd083)

It should look like this. (You can ignore the text above, that's for if there is still another connected app):

![Screen Shot 2020-07-14 at 4.13.13 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f25dcc6a-b773-4f5f-a11f-49adf2af3f53)

## Tasks

- [ ] Fix spacing issues
- [ ] Fix placement issue

## Acceptance criteria

- [ ] Matt/Tressa has reviewed and approved
