### ISSUE TITLE
Life insurance rewriting batch 2: Content Review

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#11234]
## Issue Description
Review of batch 2 pages that have been built in Drupal.

---
## Tasks
**1) PW Initial copy editing in Drupal (Randi):**
- [x] [Comparing VGLI to other insurance](http://preview-prod.vfs.va.gov/preview?nodeId=769)
- [x] [TSGLI schedule of losses](http://preview-prod.vfs.va.gov/preview?nodeId=6204)
- [x] [File a VA life insurance claim](http://preview-prod.vfs.va.gov/preview?nodeId=6210)
- [x] [VA beneficiary counseling and online wills] (http://preview-prod.vfs.va.gov/preview?nodeId=6335)

**2) DEPO Review of Drupal preview links below. Documentation of feedback in attached Word document (Danielle and/or Beth)**:
- [ ] Comparing VGLI to other insurance http://preview-prod.vfs.va.gov/preview?nodeId=769
- [ ] TSGLI schedule of losses http://preview-prod.vfs.va.gov/preview?nodeId=6204
- [ ] File a VA life insurance claim http://preview-prod.vfs.va.gov/preview?nodeId=6210
- [ ] VA beneficiary counseling and online wills http://preview-prod.vfs.va.gov/preview?nodeId=6335

Word Document:  
[life-insurance-rewriting-phase2-v0.1-071420.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4922482/life-insurance-rewriting-phase2-v0.1-071420.docx)

## Acceptance Criteria
- [ ] _Feedback/edits provided on all pages either in the form of: 
Notes made in the attached Word document, **or**
Edits made to Drupal pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lwalsh617** [comment]
On hold until I apply batch 1 changes to these pages.

**Comment by lwalsh617** [comment]
@RLHecht -- I applied batch 1 feedback to these and also made sure there were no accessibility flags. Beth said there's no need to wait until all 4 are done, but to ping she and Danielle as each page is ready. Just let me know if there's anything I need to fix first. Thanks a heap!

**Comment by RLHecht** [comment]
I've read through all four pages above and made copy edits. Ready for next steps. FYSA @bethpottsVADEPO @lwalsh617

**Comment by lwalsh617** [comment]
Moving this to icebox where it will be ready for @bethpottsVADEPO to pick up again whenever we restart this. Next steps at that point will be for Beth to review and me to edit to get it ready for SME review.

**Comment by laurwill** [comment]
Closing and continuing this work in new epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49916
