### ISSUE TITLE
Load Test File Upload for 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11232]
`kathleen and/or micah?`

## Goal
While we are using an existing endpoint but simply modifying them for our purposes, we want to test it against the backend file upload systems.

## Tasks
- [ ] Write a load test that checks the boundaries of the file upload process: concurrency, file size, and type

## Acceptance Criteria
- [ ] A load test has been created to test the concurrency of file uploads for the 686
- [ ] A load test has been created to test the file size limits of file uploads for the 686
- [ ] A load test has been created to test the file types of file uploads for the 686

**Comment by jason-gcio** [comment]
After exploration and an attempt, it was shown that the load testing for this ticket will end up being redundant against the same load test that matches its components.
