### ISSUE TITLE
Meet with GA re: Events to "VRE (CH31)"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11236]
## Goal
We want to meet with the Google Analytics Team to establish what events we want to fire for the this feature.

## Tasks
- Connect with the GA/Insights Team (over either Slack or Zoom) to share what function and features this product is involved with, and a recommendation for what events they might be interested in tracking.
- We then need to add the code to fire those events.

## Acceptance Criteria
- [ ] We have connected with the GA/Insights Team and 
- [ ] We have shared our feature and discussed its basic functionality

### Next steps
-  [ ] Code provided by the GA/Insights Team has been inserted into our feature

**Comment by micahchiang** [comment]
Meeting was held last friday, so closing for now.
