### ISSUE TITLE
Contact Perigean re: Test Users

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11233]
## Goal
Given that UAT is nearly upon us and our first step will be to invite Veterans to use our newly deployed 686 application, we want to get in touch with Perigean to see if they can solicit some users that had a need to add or remove any dependents using the 686.

## Considerations 
- Some potential use cases that we would be interested in are:
  - add a spouse
  - report a divorce
  - add a child under 18
  - report that a step-child has left the household
  - report that a child (over 18) has left school
  - report a death

## Tasks
- [x] Check in with Lauren Alexanderson, then if able
- [ ] Write an email to Perigean asking if they can get share with us up to 10 Veterans that need to make a change to their dependency claims, any of which might applicable from the list above.

## Acceptance Criteria
- [ ] Perigean has been contacted 
or  
- [x] Another path forward has been determined
- [ ] doc in GH 

### Next steps
- [ ] Their response has been shared with the team

**Comment by sporeboy** [comment]
Contacted Lauren Alexanderson regarding process for UAT users. Must created Plan and Convo guide to submit to her, then Perigean.

**Comment by sporeboy** [comment]
Direction received from Shawna/confirmation from Lauren. Research plan and convo guide required.

Guidance on UAT planning provided: https://dsva.slack.com/archives/CLY6Q69RV/p1594831436026100

**Comment by jason-gcio** [comment]
@sporeboy - While I know you know all this, I am going to codify it so we have it written down.

Per Laurens note in slack...It seems like this is a non-conventional use case but if we are clear with our intent, we might be ok.  The intent for the research plan is obviously to get user acceptance with a (or some) real Veterans that have a legit need for this form: they need to take action on of the workflows in the 686.  The convo guide will also be pretty light - I am not even really sure we want to see live Veteran data being entered.  Maybe we can just listen in case they have a question or something but the conversation guide should probably just set them up with what we are looking for.  Perhaps we can agree that we will look for their name after successful submission after a few check in points like: 1) VA File Check, 2) Pre-Fill, 3) Save to Draft and Continue, etc.

What do you think?  Let's chat Monday...have a great weekend!
