### ISSUE TITLE
Load Test 686 Submission Against `vets-api`

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11230]
## Goal
We want to ensure that our code does not have a negative impact on `vets-api` as the Veteran submits the 686 form; one way to check for this impact is to load test against the interaction with `vets-api`.  Some things to check for would be concurrency of submissions before an error is thrown, like a 500.

## Considerations 
- Part of the GTM strategy that has been discussed is a SMS notification sent out to a large number of potential users.
- This is for staging servers, not local

## Tasks
- [ ] Discuss with any peers or members of platform that have launched any other large scale applications about their experience (discuss limits, constraints, restrictions)
- [ ] Write a test that automates the submission process and records the response back from `vets-api`
- [ ] Note any findings and document them in GH

## Acceptance Criteria
- [ ] A test has been written that automates and captures the response from `vets-api` indicating the number of concurrent users that can submit at one time before the api returns an error, like a 500.

**Comment by jason-gcio** [comment]
This seems to be out of scope for this team, at this time.  Closing for now.
