### ISSUE TITLE
AE-Sprint 26

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11242]
# Priorities
**Conduct QA/508 (platform team)**
1. Finish Call Center Guide
2. Complete Pre-Staging-review 508 tests/scans
3. Call Center Video
4. Complete UAT research plan
5. Complete UAT conversation guide
6. Schedule Contact Center and Privacy/Security reviews
7. Pre-Launch: Update documentation

### PM
Finish CC product Guide, Call center video, schedule CC and Privacy/Security reviews, update documentation
- [x] Submit request for Staging review #10764 (still needs 508 tests/scans done)
- [x] [PM] Update Profile 2.0 documentation #10818
- [ ] [PM] Create call center video #11246
- [ ] Create Call Center Product Guide #7561 **(90% done)**
- [ ] [PM] Submit request for Contact Center Review #[11573](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11573)
- [x] [PM] Submit request for Privacy and Security review [#138](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/138) - Andrew Gunsch gave the OK to skip this review, will close once his note is in the ticket

### Design
Finish CC product guide, Research plan, Conversation guide, update documentation
- [x] [Design] Create UAT Research plan #11244
- [x] [Design] Create UAT conversation guide #11245
- [ ] Pre-launch - Update relevant parts of the product outline/project folder #10806
- [x] [Design] Accessibility checks required for staging review #11279 

### Build
Finish build items, update documentation, implement and run tests for Profile 2.0, assist Matt with review artifacts/scans/requests. 
- [ ] Add integration tests to Profile 2.0 #9563
- [x] [FE] - Create documentation regarding how to setup/use feature flags #10791
- [ ] [FE] - Update Profile 2.0 Documentation #11243
- [x] [FE] Update Profile Mobile Sub navigation #9729
- [x] [FE] Align checkmark icons in Account Security #11196
- [x] [FE] Accessibility checks required for Staging review - Axe Scans in E2E testing #11275 (Erik)
- [x] [FE] - Accessibility checks required for staging review - Axe scans in daily development - Screenreader test #11273 (Sandra)

## Platform
- [x] QA - Conduct QA
- [x] 508 - Conduct 508 review

#### Unplanned
- [x] [Bug] Profile 2.0: LOA1 profile showing "Personal and contact information" and "Connected apps" in side nav #11291
- [X] It's too hard to click the address validation "Edit Address" CTA link #9780
- [X] [FE] Connected apps error in the wrong screen #11333
- [X] Ensure GA events are tracked properly on Profile 2.0 #11567
- [x] Add Cypress tests to check Profile routes are properly gated/redirects work properly #11569
- [x] Hide the entire ProfileHeader if we cannot fetch the Vet's full name #11604
- [X] Fix connected apps time stamp issue #11626

## Onboarding

- [ ] Onboard Cassandra #11348
