### ISSUE TITLE
Adjust VA File Number Call 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11258]
## Description
We want to do a check before the submission job and the PDF creation job runs so that we can save unnecessary job runs.

## Tasks
- [x] Create a service that:
  - [x] Calls VA file number  
  - [x] Fires job with file number for pdf
  - [x] Fires job with file number for submission
- [x] Ensure VA file number call runs before submission job AND PDF job

## Acceptance Criteria
- [x] A service is created that calls the VA File Number
- [x] A job gets fired with that number for PDF creation
- [x] A job gets fired with that number for submission
- [x] VA file number call runs before submission job
- [x] VA file number call runs before PDF job

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4585

☝🏻That is a PR that calls the PDF code. We'll possibly have to break it into 2 smaller PR's

**Comment by digitaldrk** [comment]
This is now blocked because the submission PR/code is still in review

**Comment by digitaldrk** [comment]
Here's where the va_file number goes in: https://github.com/department-of-veterans-affairs/vets-api/pull/4673/files#diff-23fbad49e83e80f682302d5048858fecR19
