### ISSUE TITLE
Clinical Reminders Research

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11259]
## Epic User Story
- Amanda to enter
- from Dr. Byrne: [The national clinical reminders can be found here](https://vaww.va.gov/reminders/) Most of the reminders are national although some are still locally developed and maintained but nearly all of the screening questionnaires in primary care clinics are national.  

---
## Tasks

- [x] [Clinical Reminders Initiative Outline.](https://github.com/department-of-veterans-affairs/va.gov-team/new/master/products/health-care/questionnaire/product/initiatives#clinical-reminders-initiative-outline.md)
- [x] Research each questions that trigger the clinical reminder and determine if any are positive if the questions can they be included in pre-visit documentation. [Initiative Priorities ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/product/initiatives)& [Questions to consider](& Questions to consider)
- [ ] Consider wording of the questions to ensure they are consumer friendly
- [x] Document user stories and features that will build out the initiative. 

## Acceptance Criteria
- [x] each clinical reminder has been reviewed and a documented understanding of how we could leverage the questions/reminder in our intake workflow
