### ISSUE TITLE
[Design] Run content for contestable issues endpoint by AMO/Fred

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#11255]
We need to ensure that the language used for the contestable issues endpoint is accurate by getting SME feedback from Fred Somers and the AMO team.

Current work from @Mottie on the alert messaging can be found in ticket #10713 

### Tasks

- [x] Send communication (with mockup) to Fred Somers to review alert box content/language

### Acceptance Criteria

- [ ] Fred Somers / AMO has responded with SME feedback on alert box content/language
- [ ] Changes from the above criteria have been implemented in design mockup

**Comment by kevinstachura** [comment]
Sent to Fred Somers for review on 7/22.

**Comment by luke-gcio** [comment]
@kevinstachura Did you hear back?

**Comment by kevinstachura** [comment]
We have not yet heard back from Fred. I will follow up on this today.

**Comment by kevinstachura** [comment]
These changes have been implemented and can be viewed here:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/404527932_HLR-Contested-Issues-Default-Info-Expanded

and here:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/429218501_Signed_In_-_File_An_HLR_-_No_Contested_Issues_Found

The comments from Fred and Peggy have been implemented into the designs.
