### ISSUE TITLE
686 Submission PR's (lib code)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11260]
## Goal
This is the larger piece needed for the submission of the 686

## Considerations
This keeps code and reviews in the same place of the stack. We should be able to move faster like this.

## Tasks
- [x] Submit PR w/ proper Gem version installed with new name and new calls.
- [x] Submit PR with lib code
- [ ] Submit PR with app code (in another 5 point ticket)

## Acceptance Criteria
- [ ] PR with lib code is merged

**Comment by digitaldrk** [comment]
Found a bug (not really a bug) regarding the bgs-ext gem. 

Turns out BGS breaks camel case convention in the vnpBenefitClaimCreate call.

Submitted PR to gem repo to mutate payload we send them

https://github.com/department-of-veterans-affairs/bgs-ext/pull/24

**Comment by digitaldrk** [comment]
I spoke with The OG reviewer of the `/lib` PR yesterday afternoon. She has approves of all her requested changes and told me she does not think it is necessary to break up the PR.

It is moving on to another reviewer now.

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4546

**Comment by digitaldrk** [comment]
First of smaller PR's: https://github.com/department-of-veterans-affairs/vets-api/pull/4599
