### ISSUE TITLE
Test 686 Flipper Component

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11265]
## Goal 
Test Flipper component within Public Websites 

## Considerations
- #8068
- #8057
- http://preview-prod.vfs.va.gov/preview?nodeId=869
  - Daily deploy is set for 3:30 pm ET
- [Latest flipper ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11652)

## Tasks
- [x] Ensure the second component has been implemented with PubWeb
- [x] Via the VA network, check both states
  - [x] Enable for one user, check results
  - [x] Disable for another user, check results

## Acceptance Criteria
- [x] For enabled user, Flipper shows correct content for both Flipper component
- [x] For disabled user, Flipper shows correct content for both Flipper component

**Comment by jason-gcio** [comment]
Making a note: Getting weirdness when browsing to https://staging.va.gov/view-change-dependents/view/ on user 228.
