### ISSUE TITLE
(PM) Sprint 26 Checklist

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11261]
### Week 1
 - [x] Quarterly Sprint Planning - [Sprint 26 Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/quarterly-sprint-planning.md#sprint-26---discovery-readout)
 - [x] [Create Epic - Sprint 26 Priorities #11032](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11032)
- [x] [Status & Decisions - July 17th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/status-and-decisions.md#july-17th-2020) 
- [x] [Issues & Risk - July 20th](https://docs.google.com/spreadsheets/d/1KbzAQQQt6_eXoxJws4tumVvjqfTsIntT0tu72xt-jNs/edit?usp=sharing)
- [x] [VSA Shared Support Needs Product Update](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [x] [ToT Deck - July 21st](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

**Sprint Planning Readiness**
- [x] Sprint 26 Planning Ceremony
- [ ] ~~Feature Doc Review Complete- N/A~~
- [ ] ~~Design Review Complete - N/A~~
- [ ] ~~Research/Testing Complete-  N/A~~
- [ ] ~~Epics Updated with tickets linked-  N/A~~
- [ ] ~~Test case tracing to Feature Doc and Issue #'s-  N/A~~

### Week 2
- [x] [Status & Decisions - July 24th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/status-and-decisions.md#july-24th-2020)
- [x] Sprint 27 Grooming Ceremony - Backlog with at least 2 sprints planned
- [x] [VSA Shared Support Needs Product Update](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [x]  [Retrospective Action Items- July 28th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/retrospective/sprint-28.md)
- [ ] [Sprint 26 Report- July 28th](https://docs.google.com/document/d/1BmB1z4-9pdnbtQ9LqYOQREpc7MGpdVMNS-VkfVvYeKM/edit?usp=sharing)
- [x] [Sprint 26 Demo Deck - July 26th](https://docs.google.com/presentation/d/1J0nGCNzL1QlyW-CydeQVznsl98g9uj8j3lpQ452ESyA/edit#slide=id.g865f6d892d_0_0)
- [x] Quarterly Roadmap Status updates to priorities
- [x] [ToT Deck - July 28th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

Others need to identify how often need updates?
 - [ ] VSA Initiative Impact Review ?
 - [ ]  Platform Collaboration Tracker ? 
**Collaboration Checkpoints where applicable**
- [ ] ~~Accessibility - N/A~~
- [ ] ~~QA-  N/A~~
- [ ] ~~Design/User Testing Approval-  N/A~~
- [ ] ~~Security-  N/A~~
- [ ] ~~Analytics-  N/A~~
