### ISSUE TITLE
[FE] Scroll management updates

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11269]
## Background
We need to better manage the scroll focus on Profile 2.0

Turn this into an epic
- include address validation ticket

## Tasks
- [ ] When errors show up in "edit view" make sure we scroll up to that error alert
- [ ] Come up with multiple scenarios during QA session (check mobile)
- [ ] Come up with screen videos
- [ ] Make updates

**Comment by mshea0606** [comment]
change to epic once we find more bugs/issues

**Comment by erikphansen** [comment]
I'm closing this one. I couldn't find any other glaring issues.
