### ISSUE TITLE
[Design] DL - Compile "Status Buckets" data requirements

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11272]
## Issue Description
We need to compile the data requirements for the "Status buckets" to give to Jill

---
## Tasks
- [x] Mock up each of the status buckets
- [x] Compile expected list of data from those mocks
- [x] Share with team
- [x] Send to Jill

## Acceptance Criteria
- [x] Data expectations sent to Jill
