### ISSUE TITLE
686 Submission PR's (app code)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11282]
## Goal
This is the controller for the submission process.

## Considerations
This keeps code and reviews in the same place of the stack. We should be able to move faster like this.

## Tasks
- [x] Submit PR w/ proper Gem version installed with new name and new calls.
- [x] Submit PR with lib code (in another large point ticket)
- [x] Submit PR with app code 

## Acceptance Criteria
- [x] PR with app code is requested for merging

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4668
