### ISSUE TITLE
Vet Centers 1.0

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11294]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/feature-brief.md)

## High Level User Story/ies
- As a Veteran, I need to search for services so that I can successfully transition from military to civilian life or after a traumatic event.
- As a family member of an active duty service member, I need to find supportive services for military-related issues.

## OKR
By discovering Veteran facing taxonomy for services offered at Vet Centers during 3Q 2020, we can support our long term goal of establishing an online presence for Vet Centers and increasing Veteran use of these services. 

4Q2020 Key Result: Vet Center MVP design is ready to hand off to engineers by December 31, 2020. 
Ready = 

1. has been validated with Veterans
2. Collab cycle milestone are fulfilled
3. Stakeholders have signed off 

## Tasks

Develop Taxonomy: 
- Work with Vet Center **Central Office** to validate the existing list of services 
- Learn the current process used to maintain hours/locations. 
- Work with **vet centers (field)** to validate the nuances of the services offered locally 
    - What does your Vet Center call this service?
    - Who can use the service?
    - How is it different than _xyz_ offered at the VAMC?
- Talk to Veterans about why and how they use Vet Centers.
   - Do Vet Centers offer the services they expect? If not, what services do they expect? 
   - Who goes to Vet Centers for what services? (Veteran or the family)
   - Do Veterans know Vet Centers offer specific services? 
   - Would they use those services?  
- Usability test the service names.

Create web presence based on interviews with Outreach specialists

### Define
**Project Kickoff**
- [x] Request project kickoff [#12988](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/12988)
- [x] [Product Outline](link)

**Design Intent Collaboration**
- [x] Request Design Intent Collaboration [#13284](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/13284)
- [x] Create initial design prototypes [#12952](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/12952)
- [ ] List of relevant design components and patterns (with URLs)
- [x] Address design feedback 

### Discover
**Usability Testing Prep** #15846
- [ ] Create regression test plan
- [ ] Create test cases
- [x] Request research plan review
- [x] Create research plan & kickoff recruiting [#13780](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13780)
- [x] Create conversation guide [#13780](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13780)
- [x] Conduct user testing #13780
- [ ] Create report readout #14411

**Information Architecture (IA)**
- [x] Request IA review #15819 

**Analytics Review**
- [x] Determine analytics approach #15820
- [ ] Request analytics review
- [ ] Finalize OKRs

### Build 
**Engineering**
- [ ] Write end-to-end (e2e) tests with good axe checks, including hidden content
- [ ] Run axe checks using the Chrome or Firefox browser plugin(s)

**Staging Review**
- [ ] Request Staging Review
- [ ] Create release plan
- [ ] Create full pre-launch checklist
- [ ] Test for color contrast and color blindness issues
- [ ] Zoom layouts to 400% at 1280px width
- [ ] Navigate using the keyboard only
- [ ] Test with 1 or 2 screen readers 
- [ ] Address QA/508 feedback
- [ ] Address design feedback

**Privacy and Security Review**
- [ ] Request privacy and security review

**Contact Center Review**
- [ ] Create Product Guide 
- [ ] Request contact center review

### Validate
**Full Accessibility and 508 Office Audit**
- [ ] Request Full Accessibility and 508 Office Audit
- [ ] Resolve Priority 0/1 defects

**Post-launch Check-in**
- [ ] Create slides for VSA Initiative Impact Review
- [ ] Complete post-launch section of Release plan

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by mmiddaugh** [comment]
Updated description with notes from meeting with Meg Peters
