### ISSUE TITLE
Update top nav and health care hub page links for hearing aid supplies and prosthetic socks pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#11293]
## Issue Description

1. As an amputee Veteran, I need easy access to information on how to order prosthetic socks.
2. As a Veteran who has been prescribed hearing aids or other hearing assistive devices by my VA audiologist, I need easy access to information on how to order hearing aid supplies.

On 07/15, the page, https://www.va.gov/health-care/order-hearing-aid-batteries-prosthetic-socks/, split into two (one for ordering hearing aid supplies and the other for prosthetic socks). The top nav and health care hub links need to be updated to reflect this change.

---
## Tasks
- [x] _ Top nav link to the former hearing aid and prosthetic socks page needs to be updated. This page has split into two, a hearing aid supplies page and a prosthetic socks page._ (screenshot below for reference)
<img width="1094" alt="Screen Shot 2020-07-15 at 6 08 05 PM" src="https://user-images.githubusercontent.com/42546515/87606152-43b64900-c6c8-11ea-8027-d63ac6122d02.png">

- [x] _ Link on the health care hub page also needs to be updated. The page has split into two, a hearing aid supplies page and a prosthetic socks page._ (screenshot below for reference)
<img width="731" alt="Screen Shot 2020-07-15 at 6 08 45 PM" src="https://user-images.githubusercontent.com/42546515/87606161-47e26680-c6c8-11ea-8589-b142eed52717.png">

## Acceptance Criteria
- [x] _Determine if the top nav and health care hub page should include links to both the hearing aid supplies and prosthetic socks page_
- [x] _Update top nav links and confirm they are working_
- [x] _Update copy for health care hub page links_
- [x] _Update health care hub page links and confirm they are working_
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @RLHecht I have updated the health care hub page and saved as a draft. Here's the link: http://preview-prod.vfs.va.gov/preview?nodeId=67

**Comment by RLHecht** [comment]
@lunascoop The hub page text has been reviewed and published and the top nav has been changed as well. Can be validated after today's deployment. FYSA @mnorthuis @MickinSahni

**Comment by lunascoop** [comment]
These updates have been published and validated. Closing ticket.
