### ISSUE TITLE
Sprint 27 - Define Q3 Priorities  7/29/2020 - 7/28/2020

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11299]
Determine [list of priorities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/quarterly-sprint-planning.md#sprint-27---sprint-theme-name) that the team will focus on for sprint 27

| Goal/Objective | Epic/Issue#	|
|-|:-:|
| Stakeholder Interviews & Paper - Current State Workflows 	 	|  #11037 & #10219	|
| Define and document end of Q3 priority initiatives	 	| #11646| 
| Research plan for Veteran prioritization of focus areas	  	| #11544|
| Scheduling - Vets API	 	| #11514| 
| Tech Arch diagram and form Questions as a Service | #10485 |

Product
- [x] Define and document end of Q3 priority initiatives#11646

**Continue Priorities to unblock issues**
- [x] Paper - Current State Workflows #10219
- [ ] Stakeholder Interviews #11037

Research/Design
- [x] Research plan for Veteran prioritization of focus areas #11544

Engineering

- [x] Scheduling - Vets API #11514
- [ ] Tech Arch diagram and form Questions as a Service #10485
- [ ] Defined Tech Stack #10485
- [ ] [Backend] Investigate how to get Chief Complaint into CPRS as discrete data or PDF #11664
- [ ] [Backend] VA.gov and Lighthouse oAuth Strategies #11669
- [ ] Investigate Clinical Reminders #10741

- [ ] Determine analytics#10488
