### ISSUE TITLE
(PM) Sprint 28 Checklist

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11304]
### Week 1
 - [x] Quarterly Sprint Planning - [Sprint 28 Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/quarterly-sprint-planning.md)
- [x] Roadmap Project Plan Updates
- [x] [Status & Decisions - 14th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/status-and-decisions.md) 
- [x] Issues & Risk - 17th
- [x] [VSA Shared Support Needs Product Update](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [x] [ToT Deck - 18](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

**Sprint Planning Readiness**
- [x] Sprint Planning Ceremony
- [x] Feature Doc Review Complete
- [x] Design Review Complete
- [x] Research/Testing Complete
- [x] Epics Updated with tickets linked
- [N/A ] Test case tracing to Feature Doc and Issue #'s

### Week 2
- [x] [Status & Decisions - 21st](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/status-and-decisions.md)
- [x] Sprint Grooming Ceremony - Backlog with at least 2 sprints planned
- [x] [VSA Shared Support Needs Product Update](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [x]  [Retrospective Action Items- date](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/retrospective/sprint-28.md)
- [x] [Sprint Report- 20th](url)
- [x] [Sprint Demo Deck - 19th](url)
- [x] [ToT Deck - 19th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

Others need to identify how often need updates?
 - [ ] VSA Initiative Impact Review ?
 - [ ]  Platform Collaboration Tracker ? 
-  [ ]  Collaboration Checkpoints #Epic ticket Number
