### ISSUE TITLE
(PM) Sprint 27 Checklist

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11303]
### Week 1
 - [x] Quarterly Sprint Planning - [Sprint 27 Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/quarterly-sprint-planning.md#sprint-27---sprint-theme-name)
 - [x] [Create Epic - Sprint 27 Priorities #11299](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11299)
- [X] Quarterly Roadmap Update- NA
- [X] [Status & Decisions - July 31st](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/status-and-decisions.md#status---july-31st-2020) 
- [X] [VSA Shared Support Needs Product Update - Jul 30th](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [X] Issues & Risk -8/3 
- [x] [ToT Deck - Aug 4th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

**Sprint Planning Readiness**
- [x] Sprint 27 Planning Ceremony
- [x] Feature Doc Review Complete
- [x] Design Review Complete
- [x] Research/Testing Complete
- [x] Epics Updated with tickets linked
- [x] Test case tracing to Feature Doc and Issue #'s

### Week 2
- [x] Sprint 28 Grooming Ceremony Aug 5th - Backlog with at least 2 sprints planned
- [x] [Status & Decisions - Aug 7th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/status-and-decisions.md#status---August-7th-2020)
- [x] [VSA Shared Support Needs Product Update Aug 6th](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [x]  [Retrospective Action Items- Aug 10th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/retrospective/sprint-27.md)
- [ ] [Sprint 26 Report-Aug 12th](url)
- [x] [Sprint 27 Demo Deck -Aug 11th](url)
- [x] [ToT Deck - Aug 11th](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

Others need to identify how often need updates?
 - [ ] VSA Initiative Impact Review ?
 - [ ]  Platform Collaboration Tracker ? 
-  [ ]  Collaboration Checkpoints #Epic ticket Number
