### ISSUE TITLE
Update PDF on Burials Headstones Markers Memorials page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11308]
## Issue Description
Stakeholder Brett Lee updated a PDF at the bottom of the [Veterans Headstones, Markers, and Medallions](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/) page. We need to review the update and publish page in Drupal.

## Tasks
- [x] Review SME update to PDF on Burials page: http://preview-prod.vfs.va.gov/preview?nodeId=859 (Randi)
- [x] Publish page (Randi)
- [x] Alert stakeholder change was made and published (Beth/Randi)

## Acceptance Criteria
- [x] New PDF linkable on live site 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This change was reviewed and published. Created ticket to track work. Will close after validating later this afternoon. FYSA @MickinSahni

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket. FYSA @bethpottsVADEPO
