### ISSUE TITLE
(PM) Sprint 29 Checklist

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11305]
### Week 1
 - [x] Quarterly Sprint Planning - [Sprint 29 Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/quarterly-sprint-planning.md#sprint-29---land-proof-of-concept-designs-and-data-services)
- [x] Quarterly Roadmap Updates
- [x] [Status & Decisions - date](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/status-and-decisions.md#august-28th-2020) 
- [X] Issues & Risk - 8/31
- [x] [VSA Shared Support Needs Product Update](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [x] [ToT Deck - date](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

**Sprint Planning Readiness**
- [ ] Sprint 29 Planning Ceremony
- [ ] Feature Doc Review Complete
- [ ] Design Review Complete
- [ ] Research/Testing Complete
- [ ] Epics Updated with tickets linked
- [ ] Test case tracing to Feature Doc and Issue #'s

### Week 2
- [ ] [Status & Decisions - 9/4](url)
- [x] Sprint 30 Grooming Ceremony - Backlog with at least 2 sprints planned
- [ ] [VSA Shared Support Needs Product Update](https://docs.google.com/document/d/1tfpnbrx7adaGD6Kui4JTW33rN0I3mgIagKJPoJokdog/edit?ts=5f10b4bf#)
- [ ]  [Retrospective Action Items- date](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/retrospective/sprint-29.md)
- [ ] [Sprint 29 Report- date](url)
- [ ] [Sprint 29 Demo Deck - date](url)
- [ ] [ToT Deck - date](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/meeting-notes/team-of-teams.md)

Others need to identify how often need updates?
 - [ ] VSA Initiative Impact Review ?
 - [ ]  Platform Collaboration Tracker ? 
-  [ ]  Collaboration Checkpoints #Epic ticket Number
