### ISSUE TITLE
Run CMS build and find errors

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11315]
## Issue Description
I tried to run the content build using the CMS export after fixing up the existing transformers, but ran into a lot of errors. Some were due to transformers that don't yet exist, but others were due to inconsistencies between the GraphQL output and the CMS export output. I think it mostly had to do with child entities that were undefined, which may be due to unpublished entities (though this would be odd, I think, since the GQL system worked fine) or https://github.com/department-of-veterans-affairs/va.gov-team/issues/11312.

## When to work on this issue
- After all transformers have been completed
- After we get the "missing" fields from https://github.com/department-of-veterans-affairs/va.gov-team/issues/11312

---
## Tasks
- [ ] Run the content build to determine what the inconsistencies are
    - Potentially, we can log the assembled `pages.json` equivalent and compare the individual nodes to the `pages.json` we get from the GraphQL build
    - Dror wrote a script to parse out that `pages.json` into individual node files for easy comparison
- [ ] If there are few inconsistencies, fix them
- [ ] If there are a lot, write tickets for them to break the work down
