### ISSUE TITLE
[Frontend] Debt Letters MVP UI - Debt Letters Table

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11321]
## Issue Description
_In order to quickly provide functionality allowing Veterans to access and download their VA debt letters, the MVP has pivoted to display a list of these letters as a table and provide content for resolving VA debts._

---
## Tasks
- [ ] _Update the frontend with [the new Debt Letters MVP UI](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130705210/simulate/no-panels?mode=i)_
- [ ] _Share the updated UI with the design team for feedback/approval_
- [ ] - integrate with debt_letters route of vets-api

## Acceptance Criteria
- [ ] _Debt Letters MVP frontend matches the UXPin's design_
- [ ] _UI has been approved by design team_

**Comment by bradl3yC** [comment]
![Screen Shot 2020-07-17 at 2.56.45 PM.png](https://images.zenhubusercontent.com/5450f83c7c6ccc6277a5c4b7/92413e57-d15b-4fef-9d97-01b62109c607)

![Screen Shot 2020-07-17 at 2.58.32 PM.png](https://images.zenhubusercontent.com/5450f83c7c6ccc6277a5c4b7/cd299d38-847a-4af5-bb45-8facbf20b58c)
