### ISSUE TITLE
Welcome Kit PDFs: Migrate into Drupal and point page links to the nodes

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11320]
## Welcome Kit PDFs: Migrate into Drupal and point page links to the nodes

**Business user story:** 
As a PW content team member, I want VEO to be able to update their PDFs on the Welcome Kit page as many times as they want--even 10 Xs a week--without us having to upload PDFs for them and without VEO accessing and rewriting the Welcome Kit page.

**See details in this Slack thread:** 
https://dsva.slack.com/archives/CDHBKAL9W/p1590595360071200

**Subtasks/tickets needed:** 

- [ ]  Socialize with Tim Hudak and Erin Siminerio in VEO

- [ ]  Have Tim Hudak upload the Welcome Kit page PDFs into the CMS outreach library. 

- [ ]  When ^ is done, update the [Welcome Kit page](https://www.va.gov/welcome-kit/) PDF links to point to the pdf nodes in Drupal.

This is not a priority and can be pulled in anytime. Long term, this will help reduce churn caused by VEO's needs for updating PDFs usually without any advance notice or ability to wait.

**Comment by bethpottsVADEPO** [comment]
@bethpottsVADEPO will ask the analytics team for updated data on the Welcome Kit page. We want to: determine if people are using 1/ this page and 2/ the PDFs on this page.
- Non-VA network traffic to this page: https://www.va.gov/welcome-kit/
- Organic search traffic
- PDF download rates - all the PDFs on this page
- Referrals (are ppl coming from emails, social media, other VA.gov pages?)

They may be able to suggest other relevant metrics for our purpose.

Ask for data that compares last year with this year (because this year's data is somewhat artificially skewed by all the Coronavirus 'marketing' they did, and may not reflect normal/typical traffic).

**Comment by brianalloyd** [comment]
Close out, was an initial ticket.
