### ISSUE TITLE
686 State Field Validation

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11338]
## Description
Currently there is a disconnect between what we collect for the state and country (per the form) and what BGS takes in and accepts.

## Goal
We need to align what is currently in staging with what is a more acceptable text pattern for BGS to pick up and use.  The current goal is to use 2 digit codes for the state and country codes, specifically [ISO 3166-1 alpha 2](https://en.wikipedia.org/wiki/ISO_3166-2) when the Veteran is outside the US.  Within the US, we can provide the state drop down and pass in the known 2 letter abbreviation.

## Considerations
- The only dropdown will be for "State" or "Country"; City or County will be written in

## Tasks
- [x] Update the `vets-json-schema` repo to include a checkbox that asks "This occurred outside the U.S." 
- [x] Updagte the `vets-json-schema` repo to include a `country` text field
- [x] Modify the `vets-json-schema` to have `State` field be a 50 state drop down instead of a text field
- [x] Unit tests for `vets-json-schema`=

## Acceptance Criteria
- [x] vets-json-schema repo has been updated with field changes
- [x] vets-json-schema repo has had package.json updated to bump version number
- [x] A PR has been submitted with the changes
