### ISSUE TITLE
Allergies - Collab Cycle Plan

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11330]
## Initiative Outline
[Allergies Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/allergies-initiative-outline.md)

## Plan
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)
- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
- [ ]  **[Discover] IA Request** - #(ticket)
- [ ] **[Discover] Analytics Request** - #(ticket)
- [ ] **[Build] Contact Center Review** - #(ticket)
- [ ] **[Build] Privacy/Security Review** - #(ticket)
- [ ] **[Build] Pre-Staging Review activities**
  - [ ] [Accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#required-accessibility-checklist-for-staging-review) - #(ticket if necessary)
  - [ ] Fix any accessibility checklist findings - #(tickets)
  - [ ] Compile QA test cases - #(ticket)
  - [ ] Release plan - #(ticket)
  - [ ] QA test plan - #(ticket)
- [ ] **[Build] Staging Review** - #(ticket)
  - [ ] Resolve Staging Review findings - #(tickets)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

**Comment by julieadair1** [comment]
@jparker0425 is this something we need to worry about?
cc: @batemapf

**Comment by jparker0425** [comment]
@julieadair1 closing this out. No items are included and if this comes up in the future for Check-in we can create an epic specific to that work at that time.
