### ISSUE TITLE
Find VA Form - Detail Pages x Staging Review Accessibility Checklist

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11332]
## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [x] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - Conduct axe browser scan, and document or address issues found
  - [x] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [x] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
  - [x] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [x] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [x] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- [ ] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Attach to Collab Cycle Epic**
- [ ] **Labeled with Team**

**Comment by MickinSahni** [comment]
@ncksllvn i have this slotted for sprint 28 but if you think it can be picked up before then or have questions, please lmk.

**Comment by MickinSahni** [comment]
Removing from sprint until PDF error and in-body alert tickets are completed

**Comment by ncksllvn** [comment]
Checklist was added here, .https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/accessibility-checklist.md

**Comment by ncksllvn** [comment]
My only concern is screenreader support when a PDF is found invalid and we show the alert box informing the user per https://github.com/department-of-veterans-affairs/va.gov-team/issues/12181. I'll need to test this to make sure the screenreader reads out the PDF-invalid message.

**Comment by ncksllvn** [comment]
It doesn't look like the screenreader reads the invalid-PDF message. It's an edge case so no big deal (not part of the "happy path"), but we may want to add a ticket for this.

**Comment by MickinSahni** [comment]
👍 `Created Screenreader support for invalid PDF message` #12958 in this epic `Post-soft-launch: Form detail pages iterations` #11378
