### ISSUE TITLE
686 Silent Failures: User Journey Maps

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11340]
## Goal 
Given the new information we have learned about what a better user experience would be for a Veteran when submitting an application with confirmation of either success or failure.

A positive notification is important so that the Veteran can take action as needed based on the outcome and per the email's potential instruction.

We want to ensure we have fully illustrated and have shared understanding among the team as to what the steps to take are and when.

## Tasks
- [x] Create user journey maps or thumbnail workflows that describe the different outcomes that can occur.

## Acceptance Criteria
- [x] A user journey map has been shared with the team clearly describing the different outcomes: 
  - [x] Success and the subsequent email, including what next steps to take, like a phone number or url to check
  - [x] Failure and the subsequent email, including what next steps to take, like a phone number or url to check

**Comment by sporeboy** [comment]
Initial diagram created: https://xd.adobe.com/view/5948ec18-3dc7-4dde-7d9b-6c7e9aea86d1-2f79/

**Comment by sporeboy** [comment]
686/674 Failure Email

Subject line: We can't process your application to add or remove dependents

You recently submitted an application to add or remove dependents from your VA benefits (VA Form 28-686c/674) on VA.gov.

We’re sorry. Your application didn’t go through because of a technical problem on our end. You'll need to go back and apply again (link to form into or Dependents landing page).

Because of the problem, we won't be able to retrieve your application. If you have general questions about adding or removing dependents, you can call our toll-free hotline at 800-827-1000. We’re here Monday through Friday, 8:00 am to 9:00 pm ET.

Note: This is an automated message, so we won’t get reply email.

**Comment by jason-gcio** [comment]
Thanks Jim.
For the last line, can we start with this?
`Note: This is an automated message sent from an unmonitored email account.`

**Comment by sporeboy** [comment]
686/674 Success Email

Subject line: Your application to add or remove dependents was received.

You recently submitted an application to add or remove dependents from your VA benefits (VA Form 28-686c/674) on VA.gov.

Your application was received, and will be processed. We’ll send you a packet by U.S. mail that includes details of the decision on your claim. If you check your status online (link to claim status tool) and see a decision, please allow 7 to 10 business days for your packet to arrive before contacting us.

For questions about adding or removing dependents, you can call our toll-free hotline at 800-827-1000. We’re here Monday through Friday, 8:00 am to 9:00 pm ET.

Note: This is an automated message, so we won’t get reply email.

**Comment by sporeboy** [comment]
For, "Note: This is an automated message sent from an unmonitored email account..."

OK, but I'm sure it will get knocked back to plain language when the content folks see it.

**Comment by jason-gcio** [comment]
True, but "we" implies that there is someone on the other end of the line and there isn't.  At least that's how I read it and seemed confusing; you are prolly right though.

**Comment by jason-gcio** [comment]
BTW - did you end up circling back to this whole journey map with fresh eyes apart from your initial effort?  This seems closable.
