### ISSUE TITLE
686 Silent Failures: Determine Success for a Submission

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11341]
`convert to success email receipt`

## Description
In the event that failures occur where we might be able to expose to the user that either the submission has been successfully shared into the vnp tables or if a failure has occured after the Veteran has had their VA file number checked on entry and when the submission is sent on.

## Goal
There are two possibilities that need to be defined and shared with the frontend:
- Success is indicated when there is a return copy of the sent payload back from `vnpProcUpdate`
  - We can safely send an email to the Veteran that their message has been successfully sent.
- Failure is indicated when we confirm the following during the submission process:
  - We can safely send an email to the Veteran that their message was unfortunately unable to be completed and that they should either try again or call this number.
  - Is there a possibility that we could share more details about what failed exactly and relay that in the email to the Veteran?

## Tasks
- [ ] Confirmation has been determined for what indicates a failed submission between the time the Veteran comes into the form and before their submission is sent to the `vnp` tables for processing.
- [ ] An artifact is produced that fires one of two possible emails to the Veteran; success or failure.

## Acceptance Criteria
- [ ] Confirmation as to whether the Veteran has had a successful event or not has been established
Potential tickets?
- [ ] An email event is created for success, and sent*
- [ ] An email event is created for failure, and sent*
* separate ticket?
