### ISSUE TITLE
Cassandra's Onboarding Checklist

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#11348]
### Docs to review

**Authenticated experience docs**

- [x] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/charter.md)
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/product-outline.md#north-star-objectives)
- [x] [Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap.md)

**General docs**

- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/README.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [x] Review the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to learn the syntax for formatting documents in GitHub
- [x] [VSA Team Structure](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit)
- [x] [Trying out tools as a Staging User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)

### Folks to meet with

**Authenticated experience team**

Set up a 30 minute meeting with the following people on our team:

- [x] Intro with Samara (VA team lead)
- [x] Intro with Matt Shea (PM)
- [x] Intro with Tressa (Designer)
- [x] Intro with Erik and Sandra (Frontend developers)
- [x] Intro with Lihan (Backend developers)

### Project onboarding

**Profile 2.0**
- [x] Review [profile 2.0 product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/README.md)
- [x] Set up session to go over this work with Tressa
- [x] Review the [profile guide for the VA call center](https://docs.google.com/document/d/1XNHpYOP73so_bnnEjplx_zG_ybGarGenG2V0E6-N-CA/edit) (this will help you get familiar with how the profile works)

**Logged-in homepage**
- [x] Review [logged-in homepage product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/README.md)
- [x] Review [logged-in homepage discovery summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/discovery-summary.md)
- [x] Set up session to go over this work with Tressa
