### ISSUE TITLE
686 State Field Validation Mockups

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11357]
## Description
Currently there is a disconnect between what we collect for the state and country (per the form) and what BGS takes in and accepts.

## Goal
We need to update the mockups for the 686 where these new fields will live and how they will operate.

## Considerations
[Example of pattern](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/images/checkbox-dropdown-field-validation.png)

## Tasks
- [x] Define all locations or workflows where this new pattern will exist
- [x] Put the new pattern in place
- [x] Share locations and mockups with frontend team

## Acceptance Criteria
- [x] Mockups are updated with new state/country pattern to allow for dropdowns
- [x] Pattern locations are explicitly called out and shared with frontend
