### ISSUE TITLE
Update Form ID for 686: Backend

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11369]
## Description
Given that we have picked up this work from a previous team in the past, the form names have some disparity.  We want to consolidate these form IDs so they are consistent across the current and any future platforms they may exist in.  This will also allow for other work to proceed.

## Frontend Considerations
- Move forward with `686c-674`
- Ensure Pre-fill is not negatively impacted
- Any impact to how data gets submitted
- `vets-JSON-schema` matches where it needs to

## Backend Considerations
- Attaching docs should the new form ID
- PDF creation should use the new form ID
- `vets-JSON-schema` matches where it needs to

## Tasks
- [x] Determine all locations where `21-686c` currently exists (for current implementation, not rainbows code)
- [x] Update those form IDs to be `686c-674` 
- [x] Archive previous form, or set a date to sunset it
- [x] Address the file upload process

## Acceptance Criteria
- [x] All locations have been addressed
- [x] A date has been considered for sunsetting, noted in this ticket
- [x] Address the file upload process

**Comment by kathleencrawford** [comment]
We haven't set a specific date for sunsetting the old form id (rainbows code) but we did decide as a team that it is something we will do post-launch and after UAT and integration testing, etc.

**Comment by jason-gcio** [comment]
Hi Kathleen! Did this have a PR attached to it?  Just looking to close it if its done...

**Comment by kathleencrawford** [comment]
There were 2 PRs that were related to changing the form ID, but more specifically one PR was for document upload and the other was for PDF gen:

https://github.com/department-of-veterans-affairs/vets-api/pull/4525

https://github.com/department-of-veterans-affairs/vets-api/pull/4504
