### ISSUE TITLE
Review stakeholder date change to Disability page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11379]
## Issue Description
Per Sandy Tadeo we had an incorrect date on [this disability page](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-southwest-asia/). He updated in Drupal and we needed to review and publish. 

Text that is changing: 

All of these must be true of your chronic illness or other condition. It:

- Started while you were on active duty or before December 31, 2016 **change to 2021**,

Node ID: http://preview-prod.vfs.va.gov/preview?nodeId=885

---
## Tasks
- [x] Review stakeholder change (Randi)
- [x] Publish Drupal page (Randi)
- [x] Alert stakeholder of live updated page (Beth/Randi)

## Acceptance Criteria
- [x] Updated date on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
Work completed and closing ticket. This ticket was created after the fact to track the work. FYSA @MickinSahni
