### ISSUE TITLE
[Frontend] Debt Letters MVP - Empty state if no letters are on a Veteran's record

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11375]
## Issue Description
_In order to quickly provide functionality allowing Veterans to access and download their VA debt letters, the MVP has pivoted to display a list of these letters as a table and provide debt summary details. As part of this MVP, we need to provide an empty state if a Veteran accesses the tool and doesn't have any debt_

---
## Tasks
- [ ] _Update the frontend with [the empty state](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130748284/simulate/no-panels?mode=i)_
- [ ] _Share the updated UI with the design team for feedback/approval_

## Acceptance Criteria
- [ ] _Debt Letters empty state frontend matches the UXPin's design_
- [ ] _UI has been approved by design team_

**Comment by rileyorr** [comment]
@bradl3yC I'm going to need to update the empty state alert's content given that we've added back debt summary. Is it cool if I just update this ticket or do you want me to create a separate one to capture the new version?

**Comment by bradl3yC** [comment]
@rileyorr feel free to update this ticket

**Comment by rileyorr** [comment]
@bradl3yC just updated the design so it should be good to go! LMK if you have any questions :)
