### ISSUE TITLE
[Design] DL - Create empty state for debt letter download table

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11371]
## Issue Description
Create an empty state for the debt letter download table for when there are no debt letters in VBMS for a Veteran.

---
## Tasks
- [x] Create an empty state for the debt letter download table
- [x] Share with designer
- [x] Update documentation
- [x] Create dev ticket

## Acceptance Criteria
- [x] Documentation updated and linked in the comments
- [x] Dev ticket created and linked in the comments

**Comment by rileyorr** [comment]
I've added a link to [the empty state's UXPin prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130748284/simulate/no-panels?mode=i) in [the GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/prototypes.md)

Created [a ticket for frontend implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11375).

**Comment by rileyorr** [comment]
Note: I had to make updates to this design's content based on adding debt summary back to the MVP. I've let Brad know the changes :^ )
