### ISSUE TITLE
[Analytics]  Review and clean up of Wilkes-Barre Facility health Services for Migration [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11377]
## Story
As a Drupal engineer, data provided on the playbook must be an exact match to data listed in Drupal, so that migration of the playbooks will succeed without a mis-match error.

## Tasks
- [x] Review and update WILKES-BARRE VISN-8 Playbooks for accurate Health service titles that support both System and Facility health services.  
- [x] Remove all Duplicates from services, relocate services to correct designation if there are duplicates that must be moved.
- [x] Provide updated document to Engineer so he can update for migration.

## Acceptance Criteria
* All health services are correct and unique for each of the facilities under Wilkes-Barre and have been updated with exact match to Source of truth in Drupal Health Services drop down.
* File has been submitted to Engineer with any information required to clean it up further for submission in Migration script.
