### ISSUE TITLE
Create 2019 DIC Parents Rates page in Drupal

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11372]
## User story

As a surviving parent of a Veteran I need to know the 2019 DIC rates I am entitled to.

## Issue Description
As a continuation of our effort to retire legacy rates pages, we need to create in Drupal a DIC Parents rates page for 2019 by cloning an already built DIC Parents page and entering the correct figures for 2019.

Legacy page for info: https://benefits.va.gov/PENSION/rates_parents_DIC_pen18.asp

---
## Tasks
- [x] Clone the 2018 DIC Parents rate page: http://preview-prod.vfs.va.gov/preview?nodeId=6266 (Selina)
- [x] Rework the cloned page with all the correct information for 2019 DIC Parents rates, which can be found on the 2019 legacy page (Selina)
- [x] Review page and check figures against legacy page (Randi)

## Acceptance Criteria
- [x] All figures are correct and page is ready for SME approval
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @RLHecht the 2018 and 2019 pages are ready for review and include the additional changes discussed.

- 2018: http://preview-prod.vfs.va.gov/preview?nodeId=6266 
- 2019: http://preview-prod.vfs.va.gov/preview?nodeId=6797

**Comment by RLHecht** [comment]
This is all good, @lunascoop. The only thing I needed to update for 2019. was the Aid and Attendance figure and with that I readjusted some of the calculations. Closing out this ticket. Using ticket #11171 for sharing with SMEs. FYSA @bethpottsVADEPO @MickinSahni
