### ISSUE TITLE
[Design] DL - Create 404 states for Debt Letters MVP

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11374]
## Issue Description
There are multiple ways a 404 could be returned in the Debt Letters MVP tool:
- VBMS API returns a 404
- DMC API returns a 404
- Both APIs return a 404
We need to create designs to display on the frontend for these errors.

---
## Tasks
- [x] Create mockups for the 3 possible 404 returns listed above
- [x] Share with designer
- [x] Update documentation
- [x] Create dev ticket

## Acceptance Criteria
- [x] Documentation updated and linked in the comments
- [x] Dev ticket created and linked in the comments

**Comment by rileyorr** [comment]
I've updated [the documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/prototypes.md) to include links to prototypes for all 3 use cases. 
I've also created [a frontend ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11502).
