### ISSUE TITLE
Prepare for full VSP team kickoff

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#114]
# Description

Prepare for full VSP team kickoff (incl logistics + briefing team on strategy, approach, team missions)

# AC

- [x] Determine planning logistics: ZenHub, sprint planning, documentation locations
- [x] Set up initial documentation for each sub-team
- [x] Establish (create or re-use) per-team Slack channels
- [x] Document org-chart for leadership + team membership ([org chart deck](https://docs.google.com/presentation/d/1tIn0Bsqgc7yNtqUhhNXpt4wS9m6Xam4OEgh5HWwJcZE/edit#slide=id.g33cc3b02a5_0_67))
- [x] Determine meeting cadences for VSP overall + individual teams
- [x] Finalize staff onboarding for members joining VSP

**Comment by gunsch** [comment]
Slack channels in DSVA (decisions from me + @rtluu):
* Analytics & Insights: #vsp-analytics
* Content & IA: will leave to create if they want one
* Tools & Improvements: #vsp-tools
* Product Support: #vsp-platform-support (team), #vfs-platform-support (actual support)
* Operations: #vsp-operations
* Triage: #vsp-triage

**Comment by gunsch** [comment]
Meeting cadences:
* Joanne to set up for Analytics & Insights
* Ryan to set up for Tools + Product Support
* Andrew to set up for Operations
* Triage and Content & IA TBD

**Comment by gunsch** [comment]
Org chart: https://docs.google.com/presentation/d/1tIn0Bsqgc7yNtqUhhNXpt4wS9m6Xam4OEgh5HWwJcZE/edit#slide=id.g33cc3b02a5_0_49 (@gunsch WIP)

**Comment by gunsch** [comment]
Documentation for Platform teams now lives here (decision me + @rtluu):
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Platform/Teams

**Comment by gunsch** [comment]
Overall meeting cadence was decided here (joint with DSVA): https://docs.google.com/document/d/1qNauUPuyTvrkZDSmdPy9CQ_kz0LlbD8Rwt-TQFBVack/edit#

TODO this (me)

**Comment by gunsch** [comment]
Documentation for VFS teams should continue in [vets-external-teams](https://github.com/department-of-veterans-affairs/vets-external-teams) (decision me + @rtluu)
