### ISSUE TITLE
[FL] Backend pagination metadata

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11409]
## Issue Description
Facilities api V1 returns different attributes in meta.pagination object compared to V0. Common library for pagination exists. 

This issue follows a [DISCOVERY effort](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11364) 

Link to [Slack discussion thread](https://lighthouseva.slack.com/archives/CJ162GDDJ/p1595012467429600)

---
## Tasks
- [x] Update the vets-api backend components sitting between FL web application and LH Facilities API to add the pagination metadata that FL is expecting (use common library)

## Acceptance Criteria
- [ ] Pagination should be visually consistent with design systems.
- [ ] Page indicators should reflect the actual page of results being displayed.
- [ ] Page indicator should reflect only one page at a time.
- [ ] Page indicator should update when "Next" is clicked.
- [ ] Results list should advance with page.

---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
