### ISSUE TITLE
Create React Widget for Manage your VA Debt page

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#11414]
## User Story
As a Veteran who owes money to VA, I need to have easy access to view and manage my VA debt.

## Issue Description
We are building out the full Drupal landing page to support the new debt management tool and need a react widget that allows the user to sign in (unauthenticated) or directly connects to the tool if the user is already signed in to Va.gov (authenticated).

## Relevant Documentation

- **Content with React widget copy:** [Manage your VA debt_unauthenticated tool landing page_content for usability testing_7.9.20](https://app.zenhub.com/files/133843125/51b7b1e1-8909-4a53-bbf3-10b1f8411def/download)

- [Wireframes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md)

---
## Tasks
- [ ] _Create react widget_

## Acceptance Criteria
- [ ] _React widget should take user to online tool (staging version)_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
@lunascoop PR merged! Following today's deploy we should give it a try! 🙂

**Comment by MickinSahni** [comment]
TypeID: manage-va-debt

**Comment by MickinSahni** [comment]
Tested this and the CTA leads to a sign-in modal, which is correct. 
What's remaining is leading the user back to the product after sign-in (which is a new ticket to be created @lunascoop)
