### ISSUE TITLE
Analytics KPI dashboard request for Caregivers

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#11424]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [x] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [x] Your KPIs are clearly linked back to Veteran outcomes
- [x] Link your KPIs below (KPIs should be in your Product Outline)
- [x] Submit this ticket as an epic
- [x] Add your team label to follow progress

### KPIs
[Team KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md#kpis)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by joanneesteban** [comment]
Initial pass at the KPIs. Ready to groom & draft in Sprint 31. (@bsmartin-ep, @bmcgrady-ep )

Caregiver KPI | Metric | Source | Go/No Go
------------ | ------------- | ------------- | -------------
How many applications are submitted (harder to find) | Offline metric | PA&I - Caregiver | Future iteration, ⭕  No Go
How many applications are submitted online | Caregiver application successful submissions | Google Analytics (BigQuery) | ✔️  Go
How many online applications are successful vs. unsuccessful | Caregiver application successful vs. unsuccessful submissions | Google Analytics (BigQuery) | ✔️  Go
Why applications are unsuccesful (for failures, what triggered them) | (Will need additional digging) | Probably links to Prometheus or Sentry | Future iteration, ⭕  No Go
Average time to complete (online application) | Time to complete online form | BigQuery | Future 🔶  Go
Qualitative metrics on the application process and overall experience | Free text feedback | Medallia & Contact Centers | Manual requests, future 🔶  Go
Customer satisfaction (application process, caregiver program in general, etc.) | CSAT (future: other Medallia info) | ForeSee/Medallia | ForeSee to be requested, ✔️ Go
Call Center reports | Caregivers issue sums | Contact Center Report | Currently don't see this in the report, have to check with @clantosswett or @Kimberley2019, maybe future 🔶  Go

**Comment by joanneesteban** [comment]
Appended `Why applications are unsuccesful (for failures, what triggered them)` in the grooming chart. Waiting on sources.

**Comment by joanneesteban** [comment]
@ala-yna do you have links or APIs to the `Why applications are unsuccesful` metrics?

1) Veteran is found in MPI, successful 
2) Veteran is not found in MPI, unsuccessful 
3) Technical failure (unsuccessful)

**Comment by ala-yna** [comment]
We don't, yet, but here's the ticket! https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12089

**Comment by jonwehausen** [comment]
@joanneesteban @amycesal 

Please find the dataset that supports the caregivers funnel [here](https://va-gov.domo.com/datasources/015db778-ddbf-4bb7-9558-02db484ee20c/details/cards) and the [card (funnel chart) here ](https://va-gov.domo.com/kpis/details/2049359877).

Data has been configured to run daily. Ready for visualization optimization and can include on dashboard following viz work. Thanks in advance

**Comment by jonwehausen** [comment]
ccing @bmcgrady-ep and @bsmartin-ep for visibility

**Comment by joanneesteban** [comment]
First iteration of the dashboard has been created. Closing this ticket.
