### ISSUE TITLE
[Design] DL - Incorporate current debt API data into the debt table page for V1

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11428]
## Issue Description
Incorporate API data for current debt into V1 of the debt table page and adjust the content on the page to reflect these changes.

---
## Tasks
- [x] Update the UXPin V1 prototype to include debt information
- [x] Share with designer / team
- [x] Create a ticket for front end work

## Acceptance Criteria
- [x] Prototype updated and linked in comments
- [x] Ticket for FE linked in comments

**Comment by rileyorr** [comment]
I finished [incorporating the debt summary into the MVP's design](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/no-panels?mode=i) and sent it to Brad to confirm that we are able to combine the separate CH 33 debts into one card. He doesn't have any mock data to confirm my design against, so we are currently blocked until Jill responds with mock data.

**Comment by rileyorr** [comment]
Received confirmation from Brad that there are programmatic issues with combining the three separate CH 33 debts (tuition/fees, housing, and books/supplies) into a single card. We'll have to split the debts up for a later iteration anyway, so I've updated the design to display separate debts. 

I've also created [a ticket for frontend implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11576).
