### ISSUE TITLE
Agent Orange consolidation: Implement consolidation 

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#11421]
## Issue Description
We need to implement the Agent Orange consolidation strategy.

This will involve:
- Updating the existing main Agent Orange page within the Disability Benefits hub, eligibility section
- Retiring/redirecting all sub pages within the existing Agent Orange page (see issue #10768 for details).
- Updating related crosslinks

---
## Tasks

- [x] Incorporate SME feedback into drupal (Danielle)
- [x] Edit/sync (Beth)
- [x] Send final preview to SMEs with 3-day heads up re: publishing (Danielle/Beth)
- [x] Incorporate any final SME edits (Danielle)
- [x] Final review and publish (Randi)
- [x] Update related menus and related links (Content writer, Randi)
- [x] Coordinate redirects with issue #10768 (Content writer, Randi)

## Documentation
To be added when feedback received from SMEs (ETA **8/3/20**)

## Acceptance Criteria
- [x] Consolidated content is live on site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Danielle will be uploading the Word doc with the edits to be made in drupal this week. We'd like this work to be incorporated into the next sprint. There's an extra content team task here of "red lining" (or comparing the Word doc edits to the drupal edits and making sure they have all been accurately incorporated into drupal. This is necessary when there's a large quantity of edits. The room for error with inputing edits increases when there are a lot of edits. So there will be two content team members needed for this. 

This is a lower priority than IRIS work and higher priority than rates.

Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht Change of course! We don't need two content team members involved since Danielle said there are so many edits that the best approach will be to copy and paste whole paragraphs/chunks of text. That's an easier task and less room for error, so just one content team member to do that task and a copyedit to follow would be great. Still work it into the next sprint, please!

**Comment by DanielleThierryUSDSVA** [comment]
FYSA for sprint planning @MickinSahni @RLHecht 

I'll have the doc ready at some point next sprint. Will tag @RLHecht in this issue when it's ready. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bethpottsVADEPO. Here's link to preview with SME edits incorporated: http://preview-prod.vfs.va.gov/preview?nodeId=874

And here's the marked-up doc from SMEs. Please review for general copy editing, and also let me know if you see anything that you think I haven't incorporated but should consider. Thanks!

[Agent Orange Page 7.27.20](https://app.zenhub.com/files/133843125/61a7f009-780e-488f-9687-a3bd497c34f6/download)

**Comment by bethpottsVADEPO** [comment]
Edited in drupal. It looks great! I think we're ready to share with stakeholders? @DanielleThierryUSDSVA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @randihecht. This page is approved by SMEs and is now ready to be published:  http://preview-prod.vfs.va.gov/preview?nodeId=874. 

Could you publish and then work with @lunascoop and team to move forward with the redirect request in this issue? https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10768

Please let me know if you have any questions. Thank you!

@bethpottsVADEPO CC'ing you because I know you have also been working with Selina on redirects and notifying SMEs in advance. Since I've been working directly with these SMEs, they're aware of the upcoming redirects. But never hurts to give them another heads up if you'd like to - thanks!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This is now published. Will keep this ticket open until we handle the redirects and crosslinks portion. FYSA @MickinSahni @brianalloyd

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!

**Comment by MickinSahni** [comment]
Confirm cross-links are handled @RLHecht

**Comment by mnorthuis** [comment]
Hi all, wondering when the left menu links will be removed ?  Redirects have been implemented, so now we have several left nav links that are redirecting to the same page you are on.   
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/

**Comment by RLHecht** [comment]
@mnorthuis This is going to be done tomorrow. We were worried about doing it the same day as the redirects for fear there would be broken links.

**Comment by RLHecht** [comment]
@mnorthuis  I disabled the menu links for all of those Agent Orange pages. This is what the left nav will now look like. Confirming this is good. FYSA @DanielleThierryUSDSVA. Should be live after today's deployment.

<img width="290" alt="Screen Shot 2020-10-01 at 9 44 17 AM" src="https://user-images.githubusercontent.com/48728214/94817121-b03d0c00-03ca-11eb-9973-dd22b2ba8595.png">

**Comment by RLHecht** [comment]
@mnorthuis Done!

**Comment by RLHecht** [comment]
Left nav work has been validated on live site. Closing ticket. FYSA @brianalloyd @MickinSahni
