### ISSUE TITLE
Fix Ansible Linting issue

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#11437]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The Ansible linter reporting is broken and not alerting us to syntax problems, which can result in a syntax error getting committed and possibly breaking deploys.
https://dsva.slack.com/archives/CJYRZK2HH/p1594861587258000

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
The Ansible linter reporting should be fixed, by resolving the parsing problem.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
If there is a linting error, the CI build should fail.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
The error being thrown is this:

```
15:58:32  Running in /home/jenkins/workspace/testing_devops_master/ansible
15:58:32  [Pipeline] { (hide)
15:58:32  [Pipeline] sh
15:58:33  + bash -c 'source venv/bin/activate && ansible-lint -p --exclude=encrypt-ami-base.yml --exclude=roles/vendor/ *.yml build/*.yml release/*.yml deployment/*.yml > ansible-lint.txt || true'
15:58:38  Traceback (most recent call last):
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/bin/ansible-lint", line 11, in <module>
15:58:38      sys.exit(main())
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansiblelint/__main__.py", line 187, in main
15:58:38      matches.extend(runner.run())
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 264, in run
15:58:38      for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 171, in find_children
15:58:38      for child in play_children(basedir, item, playbook[1], playbook_dir):
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 222, in play_children
15:58:38      fail_on_undefined=False)
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 190, in template
15:58:38      **dict(kwargs, fail_on_undefined=fail_on_undefined))
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 78, in ansible_template
15:58:38      return templar.template(varname, **kwargs)
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 572, in template
15:58:38      ) for v in variable]
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 584, in template
15:58:38      disable_lookups=disable_lookups,
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 572, in template
15:58:38      ) for v in variable]
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 584, in template
15:58:38      disable_lookups=disable_lookups,
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 539, in template
15:58:38      disable_lookups=disable_lookups,
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 804, in do_template
15:58:38      res = j2_concat(rf)
15:58:38    File "<template>", line 12, in root
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib/python2.7/site-packages/ansible/plugins/filter/core.py", line 71, in to_nice_yaml
15:58:38      transformed = yaml.dump(a, Dumper=AnsibleDumper, indent=indent, allow_unicode=True, default_flow_style=False, **kw)
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib64/python2.7/site-packages/yaml/__init__.py", line 293, in dump
15:58:38      return dump_all([data], stream, Dumper=Dumper, **kwds)
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib64/python2.7/site-packages/yaml/__init__.py", line 281, in dump_all
15:58:38      dumper.represent(data)
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib64/python2.7/site-packages/yaml/representer.py", line 29, in represent
15:58:38      node = self.represent_data(data)
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib64/python2.7/site-packages/yaml/representer.py", line 68, in represent_data
15:58:38      node = self.yaml_representers[None](self, data)
15:58:38    File "/instance-storage/jenkins/workspace/testing_devops_master/ansible/venv/local/lib64/python2.7/site-packages/yaml/representer.py", line 251, in represent_undefined
15:58:38      raise RepresenterError("cannot represent an object", data)
15:58:38  yaml.representer.RepresenterError: ('cannot represent an object', AnsibleUndefined)
15:58:38  [Pipeline] }
15:58:38  [Pipeline] // dir
15:58:38  Post stage
15:58:38  [Pipeline] script
15:58:38  [Pipeline] {
15:58:38  [Pipeline] }
15:58:38  [Pipeline] // script
15:58:38  [Pipeline] dir
15:58:38  Running in /home/jenkins/workspace/testing_devops_master/ansible
15:58:38  [Pipeline] {
15:58:38  [Pipeline] recordIssues
15:58:38  [Ansible Lint] [-ERROR-] Skipping file 'ansible-lint.txt' because it's empty
15:58:38  [Ansible Lint] Searching for all files in '/home/jenkins/workspace/testing_devops_master/ansible' that match the pattern 'ansible-lint.txt'
15:58:38  [Ansible Lint] -> found 1 file
15:58:38  [Ansible Lint] Skipping post processing
15:58:38  [Ansible Lint] No filter has been set, publishing all 0 issues
15:58:38  [Ansible Lint] Using reference build 'testing/devops/master #5028' to compute new, fixed, and outstanding issues
15:58:38  [Ansible Lint] Issues delta (vs. reference build): outstanding: 0, new: 0, fixed: 0
15:58:38  [Ansible Lint] No quality gates have been set - skipping
15:58:38  [Ansible Lint] Health report is disabled - skipping
15:58:38  [Ansible Lint] Created analysis result for 0 issues (found 0 new issues, fixed 0 issues)
15:58:38  [Ansible Lint] Attaching ResultAction with ID 'ansiblelint' to run 'testing/devops/master #5029'.
15:58:38  [Pipeline] }
15:58:38  [Pipeline] // dir
15:58:38  [Pipeline] }
15:58:38  [Pipeline] // stage
15:58:38  [Pipeline] stage
```

It's throwing a stack trace that I'm not quite sure to to track down the source of error on because it's a generic parsing error on some playbook and then the Ansible Lint reporting tool is just ignoring the empty file and moving on.

**Comment by jbritt1** [comment]
Narrowed the issue down to two playbooks within the ansible directory in the devops repo, `review-instance-configure.yml` and `review-instance-deploy.yml`. The issue was brought up in the ansible-lint repo, but was dismissed as being ignored due to the team no longer support Python2.7 https://github.com/ansible/ansible-lint/issues/776#issuecomment-638990642.

**Comment by jbritt1** [comment]
Easiest fix for this wound up being to downgrade the version of PyYAML being used. More info in #7331.
