### ISSUE TITLE
[Design] Determine Technical Discovery items for CST

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#11438]
We need to understand what worthwhile information we are looking to gather in a technical discovery of the claim status tool - and communicate that to the developers who will be looking into the code base to gather said information.

### Tasks

- [ ] Create a list of the data we would like to find via technical discovery

### Acceptance Criteria

- [ ] List has been created
- [ ] List has been shared with frontend or backend developers

**Comment by luke-gcio** [comment]
Replaced by #11803
