### ISSUE TITLE
[Design] Social Listening of Veteran Concerns around CST

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#11439]
We need to gather information as to what pain points may exist in the claim status tool. Specifically, we are looking for general usability issues that we can turn into bug tickets. We will do this via a website where veterans seek help on navigating va.gov - called hadit.com.

### Tasks

- [x] Create a Mural board with notes of issues voiced by veterans
- [x] Categorize issues in Mural board
- [x] Create list of QA issues to test on the claim status tool

### Acceptance Criteria

- [x] QA issue list has been generated

**Comment by kevinstachura** [comment]
We have begun aggregating our social listening items into a Mural board:

https://app.mural.co/t/vsa8243/m/vsa8243/1595864403602/96c4f03aa6e7730b3dd48c3485d64659d02c47ca

**Comment by kevinstachura** [comment]
@chrvalla has generated a summarized list of issues from the aggregated social listening snippets. It can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/CST-social-listening/Summary.md

We can use this as our list of 'known' QA issues and work with the developers to finalize a list from there.
