### ISSUE TITLE
Generate Technical Discovery Topics - Learning Center

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11435]
## Issue Description
Complete technical discovery on Learning Center initiative

---
## Tasks
- [ ] Background call with Jen
- [ ] Document questions and answer
- [ ] Meetings with experts e.g. IA/Mikki (week of 7/27)
- [ ] Create follow-on engineering discovery/implementation tickets
- [ ] As necessary, architectural diagrams

## Acceptance Criteria
- Engineers have started discovery of Learning Center technical approach to inform solutioning

------------

**Current tickets with possible FE impact - does not include CMS implementation tickets:**

#6708 COPE FAQs
#11490  Mobile LC homepage
#11491 Tags on mobile displays
~#11495 Print feature~ CLOSED
#11497 Video progressive display/load
#11498 Back to top based on page height
#11499 Tables
#11624 keyword search vs tag filtered search results

**Topics we'd like to explore, Questions we need to answer**
- Best way to test against CMS environment?
- How will LC search functionality work with tags? (User clicks on a tag, gets a list of search results of articles tagged with that  label.) 
- Is this using search.gov search or does it need to be something different? 
- What IA impacts/considerations should we evaluate?
- Engineered components (vs. Drupal)
- Search functionality and scope of search on LC (and IA considerations) (see #11254)
- What would be needed in order to provide the kind of structured search results display, per current design? 
- Influence/impact of usability on implementation
- Not all of these would probably need to be templates, some of which can just be a react app right?
- Investigate: Create question link IDs for COVID 19 FAQs #7523

---
Q3 priorities for Q4 launch:

**References:**
[CMS team's Learning Center notes/status decisions](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/cms)
[CMS teams's Learning Center sprint backlog](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/board?epics=154174777_1975&filterLogic=any&repos=154174777)
[Learning Center MVP product repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp)
[Mural of WIP designs](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
[Learning Center wip template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#learning-center-template-requirements)

**Comment by MickinSahni** [comment]
Hey @ncksllvn @kelsonic - created this ticket to capture any questions/topics for you to explore as you get up to speed on Learning Center. 

@jenniferlee-dsva's going to add specific technical things to dive deep on

**Comment by jenniferlee-dsva** [comment]
I updated original ticket ^ with an "Example technical questions/topics."

**Comment by jenniferlee-dsva** [comment]
LMK when @ncksllvn @kelsonic (CC @MickinSahni ) you'd like a background call to get started. This CMS team demo is a great place to start - the first 15 minutes or so is all learning center CMS build. 

https://dsva.slack.com/archives/C0173CAJ7A6/p1596463897066300?thread_ts=1596460715.064900&cid=C0173CAJ7A6

**Comment by MickinSahni** [comment]
**Engineering discussion - NS, KA, JL, MS - 2020-08-06**
MVP - Oct/Nov 2020
* Avoid VDay Launch
* Through staging and perhaps hidden in prod (if possible given potential limitations)
* 1 audience type - Veterans
* 2 topics/categories: VA Profile and General resources/help
* Designs will look different
  * no find articles by audience
  * not every find articles by topic
* Includes search results
* Templates that will be included: LC HomePage, Search Results, View all X articles, Single FAQ, Multiple FAQ, Step-by-step, COPE reusable FAQs infra
* Tags to be included: `Veterans` `VA Profile` `General resources/help` Exact nomenclature is TBD

MVP 1.1 December 2020
* Additional tags
* Additional topics
* Was this helpful component? 
* CRM integration
* Additional templates: LC HomePage Iteration, LC Search Results, About, Videos, Images
* Tags: Other audiences and topics

MVP 1.2 January-March
* CRM integration
* Onboarding authors, governance hardening

Questions
* Are we seeing trends in search usage?
* Is there an opp to deviate between these iterations?
* What will view all articles look like?
  * likely as search results

**Comment by ncksllvn** [comment]
Doing a quick scroll those issues and will follow up with more info as I work through the issue...

> #6708 COPE FAQs

I think this one requires knowledge of a CMS engineer to define the best solution. I love the idea of FAQ content being modeled like reusable alerts though. 

We _could_ have a dedicated step in our website build that would sort of configure the data for the Learning Center, such as defining the FAQs as shared content. We do this on some pages such as under Pittsburgh Health Care. This has some caveats though - it can be complex technically, and pages that are configured from another page's data may not work easily with the preview server. This is an option though if we're sure we want this and end up not having a better solution.

> #11490 Mobile LC homepage

I don't think the mobile designs are there yet, but I don't anticipate any major difficulties.

> #11491 Tags on mobile displays

From the conversation there, the dev work looks like it'll be straightforward and won't be difficult to change if necessary.

> #11497 Video progressive display/load

The base requirement `Base experience: Link the title of the video as a view video link with the play icon` seems straightforward. I don't think we should try to do anything too sophisticated as far as driving the title of the video off of the video on YouTube.

For the video itself, the most basic thing we could do is just mirror what the GIBCT does for its embedded YouTube video, https://www.va.gov/gi-bill-comparison-tool/ -> `Know Before You Go.`

> #11498 Back to top based on page height

This will entail some (probably minimal) JavaScript work. It looks like this is part of the MVP? 

This should be easy. Basically, when the user scrolls a certain % of the vertical viewport, we show the "Back to top" link. When clicked, set the scrollbar to position zero. I don't think we need to worry about a scroll animation/duration because IIRC that is unfriendly towards users with accessibility needs.

> #11499 Tables

We'll need more info on this. It refers to ` new responsive table component` that presumably is in or will be in the design system but I don't see it yet. I think this new design is in an app already (IIRC it was shared during a demo day) but I don't think it has been contributed to the design system. This comment basically mirrors what Liz said on that issue, https://github.com/department-of-veterans-affairs/va.gov-team/issues/11499#issuecomment-663247539.

> #11624 keyword search vs tag filtered search results

I think this is too early to do a tech evaluation. There are too many variables as far as tags/search/design etc.

**Comment by ncksllvn** [comment]
>How will LC search functionality work with tags? (User clicks on a tag, gets a list of search results of articles tagged with that label.)

I suspect we will need a custom API to power search, designed similarly to the Find Forms API, where a nightly migration moves Drupal Learning Center data into an API database intended for real-time access. Then we could just tailor the API to our exact needs. For example, this page `www.va.gov/learning-center/search?tags=burials&20and%20memorials` would send an API request to `api.va.gov/v0/learning-center?tags=burials&20and%20memorials` to pull the results.

There are some technical concerns here and it would be more ideal to have the ability to hit Drupal directly rather than needing to do a migration, but we have essentially done this before on Find Forms so it wouldn't be inventing anything new.

> Is this using search.gov search or does it need to be something different?

I think it will need to be something different for a few reasons -

1. All of the pages we are interested in potentially showing up in search results would need to live under the same path for Learning Center to have its own standalone search function - `/learning-center/page-a`, etc. The reason for this is that search.gov would need to use this path as a top-level filter for searching.
1. Even if the former were true, search.gov returns search results in a standard formation - page title, description, etc. whereas we may be interested in other fields about that page. For example, on '/find-forms/`, we are interested in the form no, title, revision date, related hubs, etc. We need the data in a structured format in order to show those fields in the UI. In this case of Learning Center, we need the page type, title, description, topics, audience, etc. to show the data in each result. I don't think search.gov would include these individual fields.
1. I believe search.gov accepts only keywords as its search criteria; no tags or other search factors.

Note - This is what I suspect to be true but as always I could be wrong. We _may_ want to double check with the search.gov team for exact concrete answers but I feel confident about this.

> What IA impacts/considerations should we evaluate?

Hm, I am not sure. We should decide the relationship of the Learning Center to the homepage since they seem to have some overlap in terms of listing top tasks. We may also want to consider how the properties such as topics, audience, tags, etc. could relate to a page's metadata or if that is purely metadata for the Learning Center and shouldn't affect be written to the page itself. 

> Engineered components (vs. Drupal)

First instinct here is that the Learning Center search results is a simple React application. The rest look like template changes to me.

> Search functionality and scope of search on LC (and IA considerations) (see #11254)

Similar to the above answers about search.gov. Using search.gov would be cool because we wouldn't need to write our own search API and search.gov automatically handles indexing and weighting search results. However, there are limitations as well (see above.)  

> What would be needed in order to provide the kind of structured search results display, per current design?

Per above, I think we would need our own search API. It seems like we have very specific needs in terms of search filters and response structure.

**Comment by jenniferlee-dsva** [comment]
This is an amazing summary of initial thoughts and findings [re search](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11435#issuecomment-671507045) - thank you @ncksllvn .  (CC @johnhashva )

- What would a hybrid approach look like? (Using the search capabilities already available in search.gov + adding FE template search logic) 
- Or would that not even be worth it because the LC results are just so structured (like forms)?

**Comment by ncksllvn** [comment]
On a call with @johnhashva I decided to double check myself on whether search.gov supports tags and there is some really interesting information - https://search.gov/manual/filter-tags.html. This requires a feature known as [i14y](https://search.gov/developer/i14y.html) so that would be a new thing for us as well, but it does look promising. I think this is worth exploring but I believe the point above "search.gov returns search results in a standard formation" would still stand, so we would have less flexibility in terms of design versus an in-house solution.

**Comment by MickinSahni** [comment]
iirc i14y wasn't the recommended route which means it might be deprecated at some point in the future. 

regardless, it will require a new index is created for us that we'd manually maintain via API. 
i suppose we can just send the contents of our sitemap + any tags we might want. 

i would like to understand the specific problem tags intends to solve.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - that's great news - thanks for finding that search.gov info! 

And v good points, @MickinSahni . To answer your question or concern... 

> i would like to understand the specific problem tags intends to solve.

[The purpose of tags,](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center) as documented in the template requirements on tags, is to provide another way to browse and explore articles related to that tag. So, when @rtwell and I were thinking and designing tags, we looked at numerous sites that use tags - Medium, The Atlantic, Food52, Guardian, New Yorker, as well as commerce sites. 

What we observed is that content sites use tags as a way to take people to other articles/content in X category. Whereas commerce sites tended to use tags like faceted (or augmented) search - layering filters to narrow down. 

Because we are dealing with a content product and because we want to go out with the simplest possible common functionality, we designed tags to act like content site tags -- not faceted search, but just another way to view other articles for a particular category. We are not going to enable layered tag based searches with MVP. **_And we may never do that, if in the real world, people are able to get to the information they want without additional complex functionality._** 

> [Purpose of tags in the learning center](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center)
> Tags are not meant to be a substitute search in the learning center, but a way of filtering the ocean into a lake. Content relevance based on keyword-driven search will be the primary way users can quickly find content in the learning center.
> 
> For MVP, we will implement tag filtering by one tag at a time (not combinations of tags or layered search+tag). Future iterations should consider making tags work in a more sophisticated way, based on user data including what terms users search for most frequently inside the learning center.

FYSA @oksana-c  ^

**Comment by andaleliz** [comment]
@ncksllvn I'm trying to determine what design changes, if any, are needed for the search results pages for the learning center MVP. [Here are some questions](https://dsva.slack.com/archives/C0173CAJ7A6/p1598284599002700?thread_ts=1598284437.002200&cid=C0173CAJ7A6) I posed to John earlier today.

>we would have less flexibility in terms of design versus an in-house solution.

Do the current designs reflect what we'd get using search.gov? I agree that it'd be nice not to have make a custom search API if we can leverage search.gov.  It's not clear to me _where_ search.gov pulls the text snippet from that's currently displaying under the linked article title, or if we can do the `...` pattern to truncate the text.  Any additional info or insights you can share would be super helpful! We can also talk thru it on a call if that's easier.  Thanks!

**Comment by andaleliz** [comment]
@ncksllvn I see your thumbs up to my comment, but not sure exactly what that means...

Do the current designs reflect what we'd get using search.gov, or do we need to discuss further and make some design changes?

**Comment by ncksllvn** [comment]
@andaleliz sorry, I just meant that as an acknowledgement that I read your comment and need to respond. Sorry will respond by EOD

**Comment by ncksllvn** [comment]
> Do the current designs reflect what we'd get using search.gov?

I cannot say with absolutely certainty as I would need to do a deep dive into search.gov's concept of tags (referenced above), but based on our current search.gov integration visible on `ww.va.gov/search?query=anything`, my answer would be no. The current designs do not reflect what we'd get using search.gov. 

These are the LC designs I am looking at - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-Search-results.pdf. Each search results includes a location, page-type (faq, checklist, etc), title, description, topics, and audience. 

Here is a search result for our standard global on-site search -

![image](https://user-images.githubusercontent.com/1915775/91232264-c3d6c200-e6fc-11ea-83d9-d085d610b855.png)

Each search result there only includes a location, title, and description.

**Comment by andaleliz** [comment]
@ncksllvn thank you - that makes sense.  

Looking at our search results (e.g. [disability benefits search](https://www.va.gov/search/?page=1&query=disability+benefits)), I can't quite figure out the rhyme or reason to the description under the titles. For sure, none are using an `...` at the end to truncate (like the LC design), adding a `read full article` link or anything like that.

But, some _start_ with an `...`, others seem to be pulling in some kind of menu (eBenefits), and others start with a complete sentence.  This doesn't appear to be consistent on any single domain (I thought maybe it was driven by a domain's search.gov instance).  I'm also not seeing any obvious logic (e.g. # of characters) to why the descriptions get cut off when they do.

![Screen Shot 2020-08-26 at 9 46 05 AM](https://user-images.githubusercontent.com/55992116/91311760-718bb480-e781-11ea-9d3f-f7c536d76106.png)

Any idea what is driving that, and how much control we can have over the description with their API?  I suspect your answer will be that those questions are part of the deep dive you referenced. If that's the case, is there a specific ticket for that (I think this is one is an issue to generate more issues)?  

One of the design priorities is to [update the search results page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12863), and I would like to be able to link the two issues since the tech discovery is blocking the design work.

**Comment by ncksllvn** [comment]
Everything there - the title, the description, etc. - all comes from search.gov's API from last time our pages were indexed/crawled. There are many factors taken into account when a search engine is determining the best description, but it doesn't always work out because it's a complicated task. 

We _do_ control the title/descriptions and even what shows under `Our top recommendations for you`. We manually manage those pages and frequently run into issues where we forgot to update one.

However, the rest of the results are just generated and could be anything on va.gov. For example, see the result for `Manage Your Health Care - VA/DoD eBenefits` and the underlying data we receive from search.gov. `...here` is part of the "snippet", which we show as the page description. I suspect there is something strange about the HTML of that page, so the search.gov crawler did the best it could.

![image](https://user-images.githubusercontent.com/1915775/91314516-a51c0e00-e784-11ea-8784-2c934cb1828f.png)

**Comment by andaleliz** [comment]
FYI I'm going to add [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11435#issuecomment-670083837) to our [status/decisions doc ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md) for more visibility.

**Comment by andaleliz** [comment]
@jenniferlee-dsva, question about the templates we're launching with for MVP 1.0 described above:
>Templates that will be included: LC HomePage, Search Results, View all X articles, Single FAQ, Multiple FAQ, Step-by-step, COPE reusable FAQs infra

What is the `COPE reusable FAQs infra` template?

**Comment by jenniferlee-dsva** [comment]
>What is the COPE reusable FAQs infra template?

@andaleliz - COPE reusable FAQs is actually not a template. It will be CMS infrastructure that lets us treat a `question/answer ` unit as reusable content that can be published in multiple Drupal nodes (or pages). It allows us to create and edit that question/answer in one place, the FAQs library; while different authors can display that question/answer text on multiple Drupal pages without manually recreating that content on each of those pages.

**Comment by andaleliz** [comment]
Thanks @jenniferlee-dsva that is helpful. Trying to determine what all we're launching with to prioritize mobile versions of designs.

**Comment by jenniferlee-dsva** [comment]
In end of October 1.0, we're launching with these templates: 

About
Multiple FAQs
Single Question/Answer
Step-by-step

In addition to the ^ templates, we will launch with these pages which are not technically templates: 
a. LC homepage
b. LC search results page
c. LC 'view all X articles' page / LC articles tagged X page  

I think b. and c. are technically the same design.

**Comment by andaleliz** [comment]
Ah, okay. I thought it was odd that About wouldn't be available until 1.1.  Updated the status and decisions doc accordingly.

**Comment by jenniferlee-dsva** [comment]
completed and closing
