### ISSUE TITLE
Enable 2 Factor Auth on GTM

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11449]
## Issue Description
To increase security on pushing GTM to prod, we would like to enable 2 factor authentication. We currently do not have this enabled.
---
## Tasks
- [ ] Discover what it will take to enable 2 factor authentication
- [ ] Enable 2 factor authentication
- [ ] Add this to our documentation

## Acceptance Criteria
- [ ] Ensure that devs are _deliberately_ pushing to prod on GTM

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonwehausen** [comment]
@bsmartin-ep 2-Factor enabled?

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Yes - it has been enabled at the account level for all VA GTM properties.

![image](https://user-images.githubusercontent.com/62304138/98736863-66552780-2373-11eb-89ef-68f52ac72cdf.png)

Closing.
