### ISSUE TITLE
Update and Improve SOCKS Documentation 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11443]
## Description
Now that other users besides developers are using SOCKS to access things like Review instances, Grafana, Jenkins, ect. The current documentation doesn't suit the audience. We have received a few different pain points around how confusing and frustrating this can be. 

How Might we provide a more straight forward documentation (or other solution) for users that need SOCKS access, but are not familiar with this process? 

Ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11172, https://dsva.slack.com/archives/CL181NRJQ/p1595253611046600

## Background/context/resources
There where a few different conversations around the current SOCKS documentation and how it is not very user friendly. We will need to take a look at this from the user perspective and see how we can improve the process for everyone using SOCKS proxy. 

Additionally, the docs are out of data in some areas and need updating. An example of this is references to vets.gov instead of VA.gov.

Documentation  in question: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] _Update the documentation around SOCKS access_
- [ ] _Get feedback from users on the changes and go from there_
- [ ] _Possbility get feedback from content and IA_

## Definition of Done
- [ ] _Documentation is updated, tested by 3 users, and feedback is incorporated_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by mchelen-gov** [comment]
Thanks for looking into this! A couple recent updates have been made that hopefully improve things, but there is still a lot more that would be helpful. Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/pull/10957
- https://github.com/department-of-veterans-affairs/va.gov-team/pull/11442
- https://github.com/department-of-veterans-affairs/devops/pull/7293

**Comment by jbritt1** [comment]
@ricetj, this one seems to have stalled a bit. Should we close this for now and reopen if/when necessary?

**Comment by jbritt1** [comment]
Going to close this one for now. Glad to revisit if/when necessary.
