### ISSUE TITLE
508 PDF Accessibility Errors

### ISSUE THREAD

**Issue by mandifrances** [department-of-veterans-affairs/va.gov-team#11446]
### High Level User Story/ies
As a veteran I need all automated PDF's to be compliant with accessibility so that I am able to use any of the accessibility tools if I needed to. 

### Problem Statement 
This effects veterans using the site. 

The PDFs that are auto created on www.va.gov aren't currently passing accessibility checks. This needs to be corrected.

The current plan is to have the accessability team identify and document all the different unique errors and define how each can be remediated. 

### OKR
O2: Teams building products for Veterans meet or exceed VA.gov's standards for security, consistency, and quality.

### Success metrics 
90% decrease in errors once the teams have utilized the report that documents remediation by error type.

### We will know we're done when...

- [ ] Create remediation plan based on error type and cleared 508 office

- [ ] Assign teams to different groupings of PDF's

- [ ] Each PDF has been cleared of errors based on remediation plan.

### Additional Details/Notes (optional)
*Any other relevent information about this project not already listed above*

### Artifacts
- [Tracking spreadsheet](https://docs.google.com/spreadsheets/d/1ECh6a3D2kOh3wgRpOkYr5D2ttJ3BAApTLXK7gXj_qt0/edit?usp=sharing)

### Communication
- Product Support 
- Content and IA may also be a contributor

**Comment by shiragoodman** [comment]
hi @1Copenut  - please be sure to create issue tickets for the 5 PDF errors still remaining. Thanks!

**Comment by 1Copenut** [comment]
@shiragoodman 5 issues added to the epic and filed under Upcoming Initiatives. LMK if we need them in a different swim lane.

**Comment by humancompanion-usds** [comment]
Improving PDFs that are hosted on VA.gov is not a Design System Team task. The Veteran-facing Forms team has an initiative to look into this process and to try and make improvements: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49748
