### ISSUE TITLE
Implement Newly Added Questions Into VRE CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11452]
## Background
Given the latest iteration from the LOB that works on Veterans Readiness and Employment, we want to fold in some new questions they are adding to the Form and the online application at VA.gov.

## Goal
Once we have the mockups fully up to date we can move this work over to the frontend for implementation.

## Considerations. 
There are two yes/ no questions and one time-of-day question. Proposed text to be put into the form is:  

**Text**  
VR&E uses an Electronic Virtual Assistant (e-VA) tool to allow service members and Veterans to schedule and reschedule VR&E appointments, text and email their VR&E counselor, and submit documentation. All of this can be done privately and securely from a smartphone, tablet, or computer. Using e-VA is optional and requires accepting the e-VA tool.  
**Question**   
Would you be interested in using e-VA to communicate with your VR&E counselor?  
**Answers**
Yes / No, not at this time
**Text**   
VR&E uses virtual communication tool to host Tele-counseling sessions between service members and Veterans and their VR&E counselor. Tele-counseling, which is accessible on any device with a webcam and microphone, increases VA’s responsiveness to Veterans’ needs, reduces travel costs and time for both Veterans and VRCs, and improves Veterans’ access to necessary VR&E services. Tele-counseling does not require the service member or Veteran download any software or create a username or password.  
**Question**  
Would you be interested in using Tele-counseling to meet with your VR&E counselor?  
**Answers**  
Yes / No, not at this time. 
**Text**   
VR&E would like to know the best times for you to meet with your VR&E counselor. While we cannot guarantee these hours will be met, VR&E will make every effort to assign a counselor who is available during your preferred hours.
**Question**  
Which of these times are generally best for meeting with your VR&E counselor?  
**Answer (should be multiselect)**  
Mornings (0600 to 1000) / Midday (1000 to 1400) / Afternoon (1400 to 1800) / Other (specify)

## Tasks
- [x] Implement these questions into the CH31 feature prototype

## Acceptance Criteria
- [x] The prototype has been updated with these latest questions
- [x] The prototype has been shared with the team

**Comment by sporeboy** [comment]
I have my initial layout and re-write available here: https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/131223448

Considerations/issues:

- Will need new section of form
- Need intro/table-setter copy for section
- Will need some instructions regarding follow-up on selections; something like, "we'll call or email you..."
- If a user can put-in any time they want, why give them other checkboxed options?

**Comment by sporeboy** [comment]
I have a few questions regarding the new additions to the 1900:

- Are the new questions required?
- How will business follow-up with applicants who opt-in on e-VA and Tele-counseling?
- What are acceptable inputs for "other" times
- Are "other" time ranges actually acceptable? (e.g. 11:00 p.m. to midnight, 3:00 a.m., etc.)

I have edited-down the copy to about half. It could use further reduction--all out research seems to show more words lead to more confusion... :-)

**Comment by jason-gcio** [comment]
I believe these are the answers so far:
- Are the new questions required?
Yes
- How will business follow-up with applicants who opt-in on e-VA and Tele-counseling?
Not sure, but for now we can assume a manual follow up
- What are acceptable inputs for "other" times
Going to be an open text field
- Are "other" time ranges actually acceptable? (e.g. 11:00 p.m. to midnight, 3:00 a.m., etc.)
We might get future clarification but for now it should be ok
