### ISSUE TITLE
Urgent care mashup internal UI design review

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11459]
## Goal
To insure front end implementation is consistent with specifications from designer, style guide and design system. 

---
## Tasks
- [ ] Review front end implementation to ensure alignment with intended design
- [ ] Discuss differences with engineering team

## Acceptance Criteria
Implementation reflects intended design with regard to 
- [ ] Defined color palette for all elements (foreground, background and fonts)
- [ ] Defined states 
      - Enabled vs disabled 
      - Hover vs active 
      - Focus
- [ ] Defined margin and padding spacing
- [ ] Defined fonts and sizes
- [ ] Defined iconography, as appropriate
- [ ] Field labels
- [ ] Error messaging, as appropriate
- [ ] References to style guide/design system components
- [ ] Link words and urls
- [ ] Responsiveness breakpoints
- [ ] Expected interactive behavior

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Feedback from team review has been added in a comment on #11460
