### ISSUE TITLE
Adjust Generic Location UI Pattern

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11455]
## Goal
To try to keep silent failures from happening on the 686c-674 we need to adjust the location UI so that instead of a text field for the state we provide a drop-down with two-digit state codes as BGS will reject anything longer than two digits. 

## Tasks
- [x] add isOutsideUS checkbox to switch from state to country fields
- [x] create a reusable component to house new UI and copy in current UI
- [x] change state field to be a drop down
- [x] Add `hideIf` logic so that the state drop down can be hidden when isOutsideUS checkbox is checked
- [x] Add country field as well as `hideIf` logic so that it shows when isOutsideUS checkbox is checked
- [x] adjust logic so that we can pass in an `index` if the reusable component is inside a list loop
- [x] Replace all instances of location UI
- [x] update unit tests for each workflow where new reusable location UI is used
- [x] Submit a PR for the work

## Acceptance Criteria
- [x] All instances of the State field in the location UI used in the 686c-674 are changed to 50 state drop downs
- [x] Country text field has been added to all instances of the location UI
- [x] A new location UI has been created with an isOutsideUS checkbox
- [x] When the isOutsideUS checkbox is checked the State dropdown is hidden and the Country text field is shown
