### ISSUE TITLE
[CONSIDER] Community care referral language on search results card

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11467]
## Issue Description
Facility Locator search result cards for Community providers (in VA's network) contain referral language which is important to display but is currently duplicated on each card. 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/5099ff44-f1e5-4113-874c-a86f85872652)

There may be an opportunity to align with the urgent care mashup design and use of alerts to display the referral language in a different way. 

---
## Tasks
- [ ] consider options for displaying the referral information
- [ ] review search results cards created by Ryan for VAOS
- [ ] Determine need for Veteran research on this topic

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@thejordanwood to review if still relevant
