### ISSUE TITLE
Support VBA with name changes

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11469]
## Issue Description
There is an initiative to make facility names consistent across VBA and our team may assist with SQL/data entry efforts. 

For example: (WIP)
Existing name -> New York Regional Office at Albany VAMC Hicksville
Name logic for Regional Office -> [Regional Office Name] at [official VHA facility name]
New name -> New York Regional Office at Samuel S. Stratton Department of Veterans Affairs Medical Center

---
## Tasks
- [ ] Understand naming logic to be implemented
- [ ] Identify specific facility ids which require updating

## Acceptance Criteria
- [ ] New facility names appear in Facility Locator search results when parameters match impacted facilities
- [ ] Facility names are displayed with correct case and style
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate
