### ISSUE TITLE
Groom metrics for VSA Accessibility Dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11478]
## Issue Description
How might we automate the VSA Accessibility dashboard so that we reduce weekly manual effort?

[VSA Accessibility Dashboard](https://sites.google.com/d/1TaKZ5-By8oAv9M-HBhyylpw14-3UXDdp/p/1doeOzfSq_zSeBl7_iBzezsaNJWqUgsDy/edit)

---
## Tasks
(Sprint 31)
- [ ] Groom analytics for technical feasibility
- [ ] Document data sources for each metric
- [ ]  Document unavailable vs. available metrics
- [ ]  If any, add implementation issue for additional necessary implementation

---
(Sprint 32)
- [ ]  Draft dashboard on Domo
- [ ]  Pipe available metrics to Domo
- [ ]  QA dashboard for data quality, content
- [ ]  Add appropriate team members to dashboard

## Acceptance Criteria
- [ ] VSA Accessibility has an easy to read, easy to update accessibility dashboard on Domo

**Comment by joanneesteban** [comment]
## First Steps

@joanneesteban - take initial stab at grooming.

**Comment by joanneesteban** [comment]
@bsmartin-ep @bmcgrady-ep I believe you've been added to the Accessibility dashboard linked above.

**Comment by joanneesteban** [comment]
Metrics Grooming: based off of the current dashboard.

Dashboard Name | Metrics | Source | Go/No Go
--- | --- | --- | ---
2020 508 Issues Tracking | Number of issues by label, date, and open/closed | Github | ✔️  Go
Tracking 508-defect issues | Number of issues by label, date range, and open/closed | Github | ✔️  Go
VSA a11y issues per team | Number of issues by label, milestone, and open/closed | Github | ✔️  Go
VSA Accessibility Champions | Written content | User created | 🔶  Maybe, given Domo limitations
Tracking VSP a11y issues affecting VSA teams | Label name, issue name, other labels, link to issue | Github | 🔶  Maybe, can we link to the issues themselves? The PDFs tab is also user created

**Comment by joanneesteban** [comment]
Met with Jennifer on 7/27.

## Next Steps:
- [ ] Determine feasibility of collecting Github data so that we can view the data in points in time
- [ ] Draft & test `2020 508 Issues Tracking` chart on Domo
- [ ] User feedback from Jennifer, and determine if we should move forward with a full dashboard

**Comment by bmcgrady-ep** [comment]
When trying to pull the GitHub label data into DOMO, we are running into a timing out issue in DOMO when trying to import the GitHub data. I have up submitted a DOMO support ticket and will update here as I receive updates from DOMO. The DOMO support ticket number is 05765944.
