### ISSUE TITLE
Research feedback on Domo usage

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11479]
## Issue Description
Now that VFS teams have been using Domo for ~1 month, how might we understand how are they using it, how they're not, and how they want to use it?

---
## Tasks
- [ ] Determine research plan for Domo users
- [ ] Schedule research session where necessary
- [ ] Conduct research sessions
- [ ] Collect user research from Domo users

## Acceptance Criteria
- [ ] VSP Anaytics & Insights has usable data on Domo user sentiment and how we can improve our services on Domo

**Comment by amycesal** [comment]
**[Research Plan](https://docs.google.com/document/d/1BKggLQlJmUlUBfzj78pmnxJRylYRMzZjoUK5qoW7_Yc)**

**[Research Survey Results](https://app.optimalworkshop.com/a/adhoc/questions/results/f771c6c9-d168-4340-8471-e6a2daccd250#/t/results/analysisTools/participants)**

**Comment by joanneesteban** [comment]
Thanks for your work on this, Amy! Closing this ticket.
