### ISSUE TITLE
Iterate on Caregivers KPI dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11477]
## Issue Description
How might we automate metrics in one place so that Caregivers can see their KPIs as they roll out and maintain the Caregivers form?

---
## Tasks
- [ ] Groom analytics for technical feasibility
- [ ] If any, add implementation issue for additional necessary implementation
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard
- [ ] QA dashboard for content, data quality

## Acceptance Criteria
- [ ] VSA Caregivers has an easy to read KPI dashboard on Domo so that they can track their launch and the success of their product

**Comment by bmcgrady-ep** [comment]
Set up the dataset for the GA successful and failed events. The data is coming from WBC Modernized Non-Production. I also did a few manual dataLayer pushes to have the correct data in WBC Modernized Non-Prod for setting up the cards.

**Comment by joanneesteban** [comment]
@amycesal to create dashboard skeleton. @bmcgrady-ep to add cards to dashboard.

**Comment by joanneesteban** [comment]
@bmcgrady-ep fyi this is in Prod now. Please move into your queue when you get the chance.

**Comment by joanneesteban** [comment]
@bmcgrady-ep can you check this dashboard? It looks like it's only pulling 12 hours of data.

Settings error:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/541cc7a2-0133-477f-a555-179ce62777bc)

**Comment by bmcgrady-ep** [comment]
@joanneesteban - yes, I am looking at this now.

**Comment by bmcgrady-ep** [comment]
@joanneesteban - I re-ran the dataset and it updated successfully. I believe there was an error because no caregivers events happened over the weekend.

Also, the reason the dashboard is showing only 1 day's worth of data is due to the `caregivers-10-10cg--submission-successful` events only happening in Production on 8/20 and 8/21. The dashboard is showing all-time data by day, which means it is starting on 8/20 and ending on 8/21. This [report](https://analytics.google.com/analytics/web/#/savedreport/UdlxG0_FREaZjukMkYVKtg/a50123418w177519031p176188361/_u.date00=20200818&_u.date01=20200823&_.advseg=&_.useg=&_.sectionId=&_r.dsa=1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22caregivers-10-10cg--submission-successful%22,0%5D,%5B0,%22analytics.pagePath%22,%22RE%22,%22%5Ewww.va.gov~2Ffamily-member-benefits~2Fapply-for-caregiver-assistance-form-10-10cg.*%22,0%5D%5D) should show this in further detail.

**Comment by joanneesteban** [comment]
That makes sense! Thanks for checking that, @bmcgrady-ep .

This may be something for @amycesal to help check out then - when there isn't data coming in (and we'll assume that there may not be for a bit since this is a rollout), can the charts still show dates until the present? Otherwise, it's unclear if there isn't haven't been submissions or because there's an error.

**Comment by joanneesteban** [comment]
@amycesal @bmcgrady-ep 

## Follow Up on this Dashboard:

- [ ] Clean up titles (remove go/no go, put future metrics in appendix
- [ ] Add data source links (to Google Analytics) so that PM can dive deeper into the metrics
- [ ] Clean up both submissions charts (maybe a table) so that it doesn't look like the days with 0 submissions have submissions
- [ ] Add a note on the dashboard that data will not update if no successful submissions in the immediate previous days
- [ ] Add a dashboard description at the top (Alayna will send us their mission/objectives)
- [ ] Successful vs. Unsuccessful submissions chart is kind of strange - do we need all 3 of these lines? Also, the lines blend together

Time to Complete & Medallia customer satisfaction should go to bottom until this data is filled this month.

**Comment by joanneesteban** [comment]
@amycesal the final piece of the caregivers dashboard for now is the `time to complete` visualization. Is a line chart the best way to visualize this? Or are there better methods?

**Comment by jonwehausen** [comment]
@amycesal @joanneesteban 

Created a quick funnel visual here: https://va-gov.domo.com/kpis/details/820722690 that showcases the percentage of total. 

See slack thread here: https://dsva.slack.com/archives/CKCRMLGAC/p1602679487082600 for additional details on the domo config adjustments. 

Also removed the underscores form the step name: 

![image](https://user-images.githubusercontent.com/48527022/95992163-a5876b80-0dfb-11eb-93a5-b6caf7a58843.png)

**Comment by jonwehausen** [comment]
Resurfacing slack thread here for visibility: https://dsva.slack.com/archives/CMJ2V70UV/p1602799062256200

**Comment by amycesal** [comment]
@jonwehausen can you add a simple bar chart showing the percent of users that get each confirmation message on the last page? 
<img width="1269" alt="Screen Shot 2020-10-20 at 9 36 55 AM" src="https://user-images.githubusercontent.com/1656046/96602225-699b4d00-12b8-11eb-9acd-37e5936d74cc.png">

I also added in a table so the team can have all the numbers for the funnel. 
<img width="1260" alt="Screen Shot 2020-10-20 at 9 40 30 AM" src="https://user-images.githubusercontent.com/1656046/96602230-6a33e380-12b8-11eb-9182-3a71179ab329.png">

**Comment by joanneesteban** [comment]
Bar chart (100% bar chart of how many people received the confirmation message vs. error message)
@bmcgrady-ep

**Comment by bmcgrady-ep** [comment]
@amycesal - I added a bar chart of the confirmation vs error messages on the last page. Can you take a look? Thanks!

**Comment by amycesal** [comment]
<img width="1280" alt="Screen Shot 2020-10-21 at 9 23 55 AM" src="https://user-images.githubusercontent.com/1656046/96742123-29a39b00-1388-11eb-872a-c048ac9b561c.png">

I adjusted a few things. Looks good!

**Comment by amycesal** [comment]
@jonwehausen or @bmcgrady-ep the new labels from Alayna


URL | Current Step Name | New Step Name
-- | -- | --
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction/ | Intro | Apply for the Program
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/vet-1/ | Vet_1 | Veteran - identification
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/vet-2/ | Vet_2 | Veteran  - contact
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/vet-3/ | Vet_3 | Veteran - medical care
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/primary-1/ | Primary_1 | Primary Caregiver - identification
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/primary-2/ | Primary_2 | Primary Caregiver - contact
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/primary-3/ | Primary_3 | Primary Caregiver - Health care
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/secondary-one-1/ | Secondary_1 | Secondary caregiver - yes or no
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/secondary-one-2/ | Secondary_2 | Secondary caregiver - identification
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/secondary-one-3/ | Secondary_3 | Secondary caregiver - contact
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/secondary-two-1 |   | Secondary caregiver (2) - identification
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/secondary-two-2 |   | Secondary caregiver (2) - contact
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/review-and-submit/ | Review_Submit | Review
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/confirmation/ | Confirmation | Confirmation

**Comment by bmcgrady-ep** [comment]
@amycesal - Thank you! I will update the funnel step names.

**Comment by bmcgrady-ep** [comment]
@amycesal - The funnel has been updated. Can you look at the funnel table as the additional steps removed the color scheme you had set up?
![image](https://user-images.githubusercontent.com/66263904/97338503-b1811d80-183e-11eb-9df1-abe920d003bd.png)

**Comment by amycesal** [comment]
The funnel and the table have the appropriate labels and color scheme. 
<img width="965" alt="Screen Shot 2020-11-09 at 4 15 58 PM" src="https://user-images.githubusercontent.com/1656046/98602965-e2ce0480-22a6-11eb-9b37-58d976474244.png">

**Comment by jonwehausen** [comment]
@bmcgrady-ep @bsmartin-ep Please reference ticket above for updating dashboard to include `-failed-client` events per Alayna's request: 

> Both [Domo ](https://va-gov.domo.com/page/1905395623?userId=1492182741) and the pie chart in this [Google Analytics dashboard](https://analytics.google.com/analytics/web/#/dashboard/u4Zg-ougQpq-87e5dGIH_w/a50123418w177519031p184624291/_u.date00=20201101&_u.date01=20201116/) are not counting "caregivers-10-10cg--submission-failed-client" as an unsuccessful submission. Both sources should reflect that event as an unsuccessful submission.

**Comment by bmcgrady-ep** [comment]
@ala-yna - Both Google Analytics and Domo have been updated to include the `-failed-client` events. Let me know if you have any more questions!

**Comment by ala-yna** [comment]
Thanks @bmcgrady-ep! Could you explain to me quickly what the -failed-client event is, and if it's separate from -failed events? Is one a subset of the other or do they represent different things?

**Comment by bmcgrady-ep** [comment]
@ala-yna - We are still investigating the difference between failed and failed-client events, as it predates Jon, Brian, and I's time on the project. However, I do know that failed-client events fire when something fails on the user-end (like loses internet connection).

**Comment by ala-yna** [comment]
Hi @joanneesteban , @amycesal , @bmcgrady-ep , @jonwehausen and team!

We updated the flow of the 10-10CG to ask a yes or no before the Primary Family Caregiver info, so that Veterans could apply with only a Secondary Family Caregiver. We would like the [Domo funnel](https://va-gov.domo.com/page/1905395623/kpis/details/2049359877) to be updated to track the new URLs - I highlighted the changes below. Thank you and let me or @mlighdc know if you have any questions! 

URL | Current Step Name | New Step Name
-- | -- | --
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/primary-1/ |Primary Caregiver - identification | Primary Caregiver - yes or no
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/primary-2/ |  Primary Caregiver - contact | Primary Caregiver - identification
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/primary-3/ | Primary Caregiver - Health care | Primary Caregiver - contact
www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/primary-4/ |didn't exist | Primary Caregiver - Health care

**Comment by bmcgrady-ep** [comment]
@ala-yna - The funnels have been updated in Domo to reflect this change.

@amycesal - Can you add the correct color to the Primary Caregiver - yes or no step? Thanks!

**Comment by amycesal** [comment]
<img width="653" alt="Screen Shot 2020-11-24 at 4 53 24 PM" src="https://user-images.githubusercontent.com/1656046/100160660-a0472300-2e75-11eb-818e-4265202b9655.png">
All sorted!

**Comment by bmcgrady-ep** [comment]
@ala-yna - Is there anything else you need in regards to this ticket? If not, I will close it out. Thanks!

**Comment by mlighdc** [comment]
Thanks @bmcgrady-ep. Can you hold off until next week? @ala-yna is OOO.

**Comment by bmcgrady-ep** [comment]
> Thanks @bmcgrady-ep. Can you hold off until next week? @ala-yna is OOO.

Will do!

**Comment by ala-yna** [comment]
Hi @bmcgrady-ep - would love to keep this ticket open as it's helpful to track changes over time. Here's another query, from @mlighdc:

> We would really like the count of the number of people who did submit their feedback via Foresee. It looks like adding the count removed the average Foresee scores or we just experienced quite a big drop in user satisfaction as of the week of October 25. Can you please take a look? I don't remember our satisfaction scores being so low for the last couple of weeks in October and the beginning of November.

Thanks!

Additional question: is there anyway to visualize the funnel based on when the URL changed? IE, currently it shows that 22,000+ people went past the "Secondary Caregiver - yes or no" question. However, only ~1000 people have submitted the form since these changes went in on 11/23.

**Comment by joanneesteban** [comment]
@bsmartin-ep - I changed the ForeSee chart on there to try to show the count of survey submissions as well as the average, and accidentally ended up just showing the count. I've changed it back if you want to double check.

Still trying to figure out how to best visualize the average while showing the count (which is pretty low right now). That work is here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16627

**Comment by joanneesteban** [comment]
@ala-yna @mlighdc 
Hello! For CSAT scores in your KPIs moving forward, are you looking for just Caregiver scores, or to also compare the Caregiver scores to other 5 star scores on VA.gov?

For comparison, this is what we recommend (@bmcgrady-ep to visualize):

2 separate charts:

1 - ForeSee Average Scores: Caregiver vs. All VA.gov Week over Week (Bar Chart)

2 - ForeSee Count of Scores: Caregiver vs. All VA.gov Week over Week (Line Graph)

---

Depending on your comfort level, Alayna and Ming, we could also do a `variance line bar` chart, which would be the above 2 charts overlapping. We don't currently recommend this, since it would show two different axes with very different scales, which can be easy to misinterpret.

**Comment by bmcgrady-ep** [comment]
@joanneesteban - Updated the dashboard with the 2 separate cards, one for average scores and one for count of scores.

**Comment by joanneesteban** [comment]
Thanks, @bmcgrady-ep ! @ala-yna @mlighdc do the CSAT charts help?

Also, would you be able to clarify what you're hoping to see for the funnel URL change?

**Comment by joanneesteban** [comment]
@ala-yna @mlighdc following up here to see if you might be able to clarify the changes you're looking for on the funnel visualization.

**Comment by joanneesteban** [comment]
@ala-yna @mlighdc hello! We're moving this to our backlog. Let us know if you're looking for additional iterations.
