### ISSUE TITLE
Test analysis of current contact center data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11476]
## Issue Description
How might we understand why the monthly contact center report isn't being widely used, and how might we determine how it can be used, if at all?

Background: [hypothesis meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/research/call%20center%20data/monthly_report_research.md)

---
## Tasks
- [x] Determine 1 or 2 teams or products to use as personas
- [x] Determine usage goals for these teams/products (i.e. "I want to improve x, y on my product)
- [x] Analysis on these teams/products
- [x] Recommendations for teams/products
- [ ] Hypethesis for missing data
- [ ] Synthesize our results to determine next steps (probably further user research)

## Acceptance Criteria
- [ ] VSP Analytics & Insights has a better internal understanding of how current contact center could be used, if at all
- [ ] VSP Analytics & Insights has a better internal understanding of what contact center data is missing, if any
---

**Comment by clantosswett** [comment]
Kimberley and Chante discussed which teams to use as personas and determined that we will use Benefits and Memorial 1 and the Education team as the personas for this objective. 

We will set up another meeting for first thing next week to strategize next steps.

**Comment by clantosswett** [comment]
Chante conducted an analysis on the disability claims tool and @Kimberley2019 completed one for the claims status tool. We will be meeting tomorrow morning (8/6) to review the analysis and complete the final two tasks of this issue and move forward with validating with the Benefits and Memorial 1 team.

**Comment by clantosswett** [comment]
@Kimberley2019 adding my analysis of contact center issues for the disability claim application tool for review tomorrow and synthesis. 

[Disability Claim Application Contact Center Metrics Analysis.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5032003/Disability.Claim.Application.Contact.Center.Metrics.Analysis.docx)

**Comment by Kimberley2019** [comment]
@clantosswett here is my analysis for the claim status.  
[https://app.zenhub.com/files/133843125/e994af48-1eb2-41be-8ea3-f003cc0e3d9e/download](https://app.zenhub.com/files/133843125/e994af48-1eb2-41be-8ea3-f003cc0e3d9e/download)

**Comment by Kimberley2019** [comment]
Below is the Google Doc for the combined data.

https://docs.google.com/document/d/1Y1XHqb2mSgzANmFAMFQU9St3f10vD1W8/edit

**Comment by joanneesteban** [comment]
Analysis linked above. Closing this ticket.
