### ISSUE TITLE
Create Product Outline for Analytics Playbook

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11484]
## Issue Description
How might VSP and other stakeholders understand the Analytics Playbook strategy?

[Playbook Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1594841359041/f077b4271ccb555a402a694c1a370bdc74f7baea)

---
## Tasks
- [ ] Determine vision & user goals
- [ ] Draft executive summary
- [ ] Draft assumptions & risks
- [ ] Determine success measurements
- [ ] Draft Product Outline
- [ ] Share Product Outline

## Acceptance Criteria
- [ ] VSP Analytics & Insights has a shareable product outline for the Analytics Playbook

**Comment by joanneesteban** [comment]
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/analytics-playbook/analytics-playbook-product-outline.md) drafted on 8/2 and shared in Platform's Product folder.
