### ISSUE TITLE
Add CSAT as a secondary metric for B&M2

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11480]
## Issue Description
How might we share the Medical Device Reordering CSAT with the B&M2 team so that they can monitor customer satisfaction?

[ForeSee implementation issue](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10943)
---
## Tasks
- [ ] Add a chart with relevant ForeSee data to Domo
- [ ] Create 'secondary metrics' dashboard for Medical Device Reordering
- [ ] QA for data quality & content
- [ ] Share with B&M2 team

## Acceptance Criteria
- [ ] B&M2 can see their Medical Device Reordering CSAT on Domo

**Comment by bmcgrady-ep** [comment]
@joanneesteban - I added the CSAT scores to the Medical Device Reordering Tool. Let me know if anything else is needed for this. Thanks!

**Comment by joanneesteban** [comment]
Thanks, @bmcgrady-ep ! Would you be able to make this a weekly view?

**Comment by bmcgrady-ep** [comment]
> Thanks, @bmcgrady-ep ! Would you be able to make this a weekly view?

@joanneesteban - Just updated it to weekly. Let me know if you need anything else.

**Comment by joanneesteban** [comment]
Thanks!
