### ISSUE TITLE
Draft a User Journey or Service Blueprint of the Analytics flow

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11486]
## Issue Description
How might we determine the pain points throughout the entire analytics journey? How might we determine the missing pieces for a VFS user to go through the entire analytics journey?

[Blueprint Sheet](https://docs.google.com/spreadsheets/d/1JCoMpdXisEEqe0I8dkq7rPDuYwO_duS4pDW9598AI8U/edit#gid=2115517494)

---
## Tasks
- [ ] Complete content in the blueprint Sheet
- [ ] Work with Service Blueprint to visualize a blueprint or user journey

## Acceptance Criteria
- [ ] VSP Analytics & Insights can easily visualize and see the analytics journey pain points

**Comment by joanneesteban** [comment]
@joanneesteban to complete any content that needs to be added before PTO on 8/10. Meeting with Naomi on Friday, 8/7.

**Comment by joanneesteban** [comment]
Met with Naomi on 8/7. 

### Next Steps
@naomimarcussen will get back Joanne & @amycesal about what type of framework we can start with to visualize the blueprint sheet. Amy will work on the visualization S32 or S33.

cc: @jchasia-adhoc

**Comment by joanneesteban** [comment]
[Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1597338577356/b96be506d35e40384251e62c08931698722bb5ba) that Naomi started for us!

We can just pop in the content from the Sheet.

Use this to help with Team Initiatives ideas & Analytics Playbook QA.
