### ISSUE TITLE
Determine Medallia VSP Strategy

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11482]
## Issue Description
How might VFS teams request a Medallia user survey on va.gov from VSP Analytics & Insights?

---
## Tasks
- [x] Determine bank of recurring questions
- [x] Segment bank between Forms, Content, etc.
- [x] Determine how the feedback button will be shown
- [x] [Stretch] Determine how an intercept will be created
- [x] Determine how data might roll up into benefit hubs & all va.gov
- [x] Publish process

## Acceptance Criteria
- [x] VFS teams understand what kind of Medallia surveys they can request & how to request them.

**Comment by joanneesteban** [comment]
## Meeting with Mickin & Shawna
#### Attendees:
- Joanne
- Mickin
- Shawna

### Next Steps

- Insights create defaults (questions + how the forms would actually be prototyped)
- VSP designs question template & survey prototypes
- Send over to Shawna & Mickin & relevant VFS teams for testing & feedback

#### Information for next steps
Testing on form vs. content vs. tools - can stagger
- Content: @mickin and @shawna will find an example service
- Form: 526ez or 1010ez
- Tools: GI Bill Comparison Tool
- Form in progress

### Decisions

- Session form flow can be a part of the optional part of the flow (on the confirmation page after they submit vs. embedded on the confirmation page)
- Tools or Forms
  - there’s a thing at the top like zappos.com (potential component at the top of the page)
  - Future: intercept users who are leaving forms before they leave.
  - Future: Or users who have stayed on pages & a % of these types of users
- Restrict to defaults until it goes through multiple services

**Comment by jwoodman5** [comment]
This was all done. We have moved on to new initiatives and the evolving strategy.
