### ISSUE TITLE
Determine Rollout of Analytics Playbook

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11483]
## Issue Description
How might we roll out the Analytics Playbook?

[Playbook on Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1594841359041/f077b4271ccb555a402a694c1a370bdc74f7baea)

---
## Tasks
- [ ] Document rollout strategy for the Analytics Playbook

## Acceptance Criteria
- [ ] VSP Analytics & Insights & VSP understands how the Analytics Playbook will be rolled out to VFS teams
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[Rollout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/analytics-playbook/analytics-playbook-rollout.md) added to Github folder on August 4th. Closing this ticket.
