### ISSUE TITLE
[QA]:[FE] Profile 2.0 - Direct Deposit - Fraud Note copy does not match design prototype (High priority)

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#11489]
## What happened?
On Staging Profile page, Direct Deposit section, the Note about fraud has a TTY number that did not match the one in the design prototype.

## Tasks
- [ ] Determine correct phone number
- [ ] Update design prototype or staging profile

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User: vets.gov.user+226@gmail.com

## Steps to Reproduce
1. Got to https://staging.va.gov/profile/direct-deposit -- sign in as **```vets.gov.user+226@gmail.com```** (Johnnie).
1. In main-content (right column), below **Disability compensation and pension benefits** section, in the **Note** about fraud, observe that the TTY number is 711.

**Screenshot**
![Screen Shot 2020-07-21 at 9 53 25 PM](https://user-images.githubusercontent.com/587583/88136394-fe998780-cb9d-11ea-864e-f78f182978a2.png)

## Desired copy
TTY number should be 800-829-4833.

**[Design prototype](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/420471560) screenshot**
![Screen Shot 2020-07-21 at 10 01 56 PM](https://user-images.githubusercontent.com/587583/88136359-e6296d00-cb9d-11ea-9ea7-786ba7bf7e66.png)

## Acceptance Criteria
\[see **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tressaellen** [comment]
Here is the correct phone number from Peggy.

<img width="709" alt="Screen Shot 2020-08-04 at 1 10 03 PM" src="https://user-images.githubusercontent.com/58752772/89448786-8df97b80-d704-11ea-864b-89f477d3cf84.png">

**Comment by tressaellen** [comment]
Here is the correct number from Peggy

<img width="833" alt="Screen Shot 2020-08-05 at 12 21 03 PM" src="https://user-images.githubusercontent.com/58752772/89449342-6525b600-d705-11ea-93d3-c62854dcc70e.png">

**Comment by peggygannon** [comment]
HI, @tzelei I'm trying to track down how this number changed and I learned that the Public website dev team did a  sweep of tty numbers recently, updating them all to 711 because I think TTY is almost always 711 now. 

do you know if this TTY should be an exception? I haven't been able to track anything down to validate that.

**Comment by tlei123** [comment]
> do you know if this TTY should be an exception?

@peggygannon , should we both ask around and compare notes next week? [I bark up the Engineering tree while you bark up the Design/Content tree?]

Sorry, no -- I don't know if this longer TTY number spec is a legit. exception to the general TTY 711.  This Bug only means Staging did not match Design (here's the [prototype link](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/420471560) again), which is why my Defects always say "...did not match design..." instead of "...is incorrect...".  IF the Design spec turns out to be incorrect, then this Bug can be Closed as a false-positive.

I do see many more Design prototypes spec'ing TTY 711; this particular prototype is the first exception I've encountered.

Lemme know how I can help further.

**Comment by sanlouise** [comment]
@peggygannon No rush at all, but do you have any updates on the desired TTY number?

**Comment by peggygannon** [comment]
Hi, @sanlouise 711 is the desired TTY number.

**Comment by sanlouise** [comment]
@mshea0606 This ticket can be closed as the displayed phone number is the desired phone number. The design had outdated copy.

**Comment by tlei123** [comment]
thx, @sanlouise !  closing.
