### ISSUE TITLE
Create MVP of the Analytics Playbook

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11485]
## Issue Description
What might a first iteration of the Analytics Playbook look like? This would be something that is shareable & testable, but does not necessarily have to the be the final product.

[Playbook Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1594841359041/f077b4271ccb555a402a694c1a370bdc74f7baea)

---
## Tasks
- [ ] Draft Content
- [ ] Gather available links
- [ ] Determine missing components for future iterations
- [ ] Design the book

## Acceptance Criteria
- [ ] Analytics Playbook has a workable, testable draft

**Comment by joanneesteban** [comment]
[Playbook Content draft](https://docs.google.com/document/d/1Z8GaBtH9R3eLdv7p_XLdxnBxOXNffoV_QSA8e5GeR7k/edit)

**Comment by joanneesteban** [comment]
I think we should also consider a specific framework to end each section/chapter. 

Ideas:
- Do/Try/Consider - this is going to be used by the Collab Cycle
- Checklist
- Questions to consider
- Before/During/After
- Easy/Moderate/Advanced <- probably not user friendly

**Comment by joanneesteban** [comment]
### Feedback for where to put the Playbook

- [ ] Access: where is the friendliest, most accessible location?
- [ ] Usability: can people interact with it? Click links, view images, easily distinguish sections 
- [ ] Iterability: can we iterate on the playbook while ensuring that users receive the updated content?
- [ ] Analytics: where can we track if people are viewing and interacting with it?

**Comment by joanneesteban** [comment]
[Analytics playbook V1 draft](https://docs.google.com/document/d/1Z8GaBtH9R3eLdv7p_XLdxnBxOXNffoV_QSA8e5GeR7k/edit) is complete. Moving onto user feedback & phase 1 rollout.
