### ISSUE TITLE
Update ForeSee data on Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11481]
## Issue Description
How might we update and create processes for updating ForeSee data on Domo?

---
## Tasks
- [ ] Update Facility Locator CSAT dataset to [All ForeSee dataset](https://va-gov.domo.com/datasources/d466aac9-96a8-47f3-8a79-b47be8aed2d7/details/overview)
- [ ] Establish weekly process for updating ForeSee data until the dataset is migrated to Medallia

## Acceptance Criteria
- [ ] VSP Analytics & Insights has a documented cadence for updating 5 star comment card ForeSee data on Domo until the datasets are migrated to Medallia

**Comment by joanneesteban** [comment]
@bsmartin-ep When I try to switch the dataset on Facility Locator over to the All URLS one, I get this message:

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/b2ea05d1-4c94-4fb7-9502-59c7d87a4dbb)

I'm filtering the URL by `facility` and haven't updated the dataset yet.

**Comment by bsmartin-ep** [comment]
@joanneesteban -

Does this look OK?

https://va-gov.domo.com/analyzer?cardid=340674209

Looks like it's mostly matching a parameter in URLs that start with `/find-locations/`.

**Comment by joanneesteban** [comment]
Ahh, that should work. Thanks, @bsmartin-ep ! So for updating the data, is the easiest way to append the excel doc?

**Comment by bsmartin-ep** [comment]
Correct @joanneesteban - the data set should append:

![image](https://user-images.githubusercontent.com/62304138/88806093-f339f380-d17d-11ea-8694-a8339d4e6e12.png)

I was unable to upload an actual .XLSX file (with 2000+ rows) but converting it to a CSV worked immediately.

**Comment by joanneesteban** [comment]
Cadence for ForeSee data updates on Domo - append weekly (Monday-Sunday) data on Mondays.
