### ISSUE TITLE
Debt Letters - UAT/QA Study 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11492]
## Issue Description
In order to QA integration between DMC endpoint and vbms we need to test with real users the have debt and have received debt letters since there is no concept of test accounts in prod environment. 

They UAT process will validate: 
1-Authenticated user will see debt summary 
2-Authenticated user will see the debt letters that they received in the mail and have ability to download and confirm
---
## Tasks
- [x]  Research plan
- [x]  Conversation guide 

## Acceptance Criteria
- [x] Research plan and conversation guide have been uploaded to GH and attached to this ticket
- [x] Research plan and conversation guide have been sent to Shawna for review 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
Working on the research plan and conversation guide. IMO I don't think scheduling should be included as a task because we're not responsible for scheduling the interviews. Might also be a good idea to have a separate ticket for conducting the interviews in case this ticket floats into the next sprint if development isn't completed this sprint

**Comment by rileyorr** [comment]
@leahkeeler I've uploaded the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/uat-aug20/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/uat-aug20/conversation-guide.md) to GH. 
Things that still need to be added to the research plan:
- Session dates/times - Do we have an idea when we'll be conducting UAT?
- Moderator - This depends on when we'll be conducting UAT
- Additional participant info - I added the requirement that participants need to be comfortable with us providing their first and last name and last four digits of their SSN to the DMC/VBMS teams, but I may update this with additional info based on Julie's response to your email 

I'm also going to update this ticket's acceptance criteria to align with the tasks because I think we forgot to during backlog grooming.

**Comment by leahkeeler** [comment]
Thanks @rileyorr

**Comment by rileyorr** [comment]
Sure thing, @leahkeeler! Also, my question may have gotten buried in my response but do we have an idea when we'll be conducting UAT?

**Comment by leahkeeler** [comment]
@rileyorr sorry, I didn't think that was a question. We want to conduct it ASAP - so whenever veterans can be recruited. Both FE and BE are ready

**Comment by rileyorr** [comment]
It's all good! We still have tickets for [the updated empty states](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11639) and [the covid alert](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11578) which will require additional frontend work (albeit I don't expect a lot of additional frontend work). After that we should be ready to test!
