### ISSUE TITLE
[Design] - MVP learning center - Print styles + button for Checklist template

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11495]
- Explore the print styles for this template. The example in the mock-ups is a one-off and the majority are not like that.
- Explore adding a print button
  - maybe shows up when there's not a PDF, or 
  - PDF button gets priority, or it's just in a note.

## Acceptance Criteria

- [ ] check with other VSA teams about recent work w/ print styles + print buttons
- [ ] Create mockup of checklist template with print button
- [ ] Create mock-up of checklist template w print styles applied
- [ ] @rtwell, @jenniferlee-dsva and @andaleliz to review
- [ ] Review w @jenstrickland 

## Background
This is a subtask of Accessibility feedback - Design intent collaboration - Public Websites [MVP learning center templates]
#11386

![image](https://user-images.githubusercontent.com/12564977/88178180-fa01bd00-cbf7-11ea-8b2f-fa0ade0e3618.png)

### Original feedback from design intent epic #10955 
1. Consider a print button
2. Because the check boxes are interactive, consider caching this page so that if a user leaves the page, when they come back, it remember's which boxes have been checked

**Comment by andaleliz** [comment]
I like the idea of caching the page so people can come back and use this as their "to do".

I don't feel strongly either way about a print button. I suppose it can't hurt for folks who want to use it? IMO the PDF is sufficient, people can just print that, or print the web page however they normally would.

**Comment by andaleliz** [comment]
-  need to explore the print styles for this template.  The example in the mock-ups is a one-off and the majority are not like that.

- print button: maybe shows up when there's not a PDF, or PDF button gets priority, or it's just in a note.

Look into how other teams have handled this, recent work done on print styles.

**Comment by jenniferlee-dsva** [comment]
Per discussion w/Ryan - we won't provide 'print' feature for LC mvp. Closing this ticket.
