### ISSUE TITLE
[BE] Connect to prod DMC API endpoint 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11500]
## Issue Description
In order ot test with live users, app needs to be connected to prod DML API endpoint 

---
## Tasks
- [ ] After privacy and security review, connect to prod DMC API endpoint

## Acceptance Criteria

- [ ] Veteran is able to log in and see their debt summary in prod environment 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by camerontesterman** [comment]
client_id and secret have been configured in prod. fwdproxy is configured.
