### ISSUE TITLE
[BE] Connect to vbms prod environment 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11501]
## Issue Description
Connect to prod vbms API endpoint after privacy and security review is completed 

---
## Tasks
- [ ] _connect to vbms prod in order to conduct live user testing and to release 

## Acceptance Criteria
- [ ] _An authenticated veteran is abel to see a list of debt letters contained in eFolders 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by camerontesterman** [comment]
Prod connection to VBMS is already established. No action required.
