### ISSUE TITLE
[Frontend] 404 states for Debt Letters MVP

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11502]
## Issue Description
There are multiple ways a 404 could be returned in the Debt Letters MVP tool. Designs to display on the frontend have been created for the following use cases:

- [VBMS API returns a 404](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130821989/simulate/no-panels?mode=i)
- [DMC API returns a 404](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130822746/simulate/no-panels?mode=i)
- [Both APIs return a 404](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130823985/simulate/no-panels?mode=i)

---
## Tasks
- [ ] _All 3 designs are implemented for the use cases listed above_
- [ ] _Review UI updates with a designer_

## Acceptance Criteria
- [ ] _UI has been updated to display a 404 alert depending on which API(s) is down_
- [ ] _UI for all 3 use cases has been approved by a designer_
