### ISSUE TITLE
Migrate GA Domo datasets to BigQuery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11513]
## Issue Description
How might we switch over GA Domo datasets to BigQuery?

---
## Tasks
- [x] Set up accounts
- [x] Use Domo connector
- [x] Write queries
- [x] Test queries
- [x] Write out BigQuery<>Domo schema for GA
- [x] Backup current Domo charts
- [ ] Processes are documented

- [x] Migrate charts from GA to BigQuery

## Acceptance Criteria
- [ ] Understand how to switch over GA Domo datasets to BigQuery
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
## Sprint 32 Tasks

In conjunction with [#6356](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/6356)
- [ ] Rename the titles or work with Amy to clearly indicate maintenance of dashboards/pages
- [ ] Document testing plan/updates
- [ ] Document what ETL funnels might look like
- [ ] Draft template for ETL funnels
- [ ] Document how time to complete might look like
- [ ] Document any other change
- [ ] Test with recurring monthly reports
  - [ ] VEO
  - [ ] OMB
  - [ ] DMC
- [ ] Stretch: Continue testing with Covid dashboard (DO NOT do this on Thursday or Friday!)
- [ ] Further Stretch (Please reach out to the relevant PM & PO before testing on their KPI dashboards. Also put a maintenance flag before testing) Continue testing with:
  - [ ] Facility Locator
  - [ ] Chatbot
  - [ ] Medical Device Reordering
  - [ ] VAOS

**Comment by jonwehausen** [comment]
### Update 8/12
- Maintained existing copies of VEO Dashboard using Google Analytics connector
- Created a separate VEO dashboard utilizing ONLY BigQuery connectors
- Setup the following datasets that can be reused where appropriate: 
  - `BQ - All Transaction Events by Day`
  - `BQ - All Login Events by Day
  - `BQ - All Product Form Events by Day`
  - `BQ - Generic - Overall PV's Sessions, Users, Bounces by Day`

## Next Steps
- Continue to identify ways where datasets can be generic / big enough to be reused across multiple dashboards
- Configure query to only query for the previous days data to eliminate the need to do full query scans each time
- Continue to document naming convention adjustments and tagging convention adjustments

**Comment by jonwehausen** [comment]
[Google Sheet Tracking Migration Items](https://docs.google.com/spreadsheets/d/1RCJmoFjQxZ4XdNf7zWBGp2lOriKXu2TP6UIyfhLpejc/edit#gid=1674744126)

**Comment by joanneesteban** [comment]
@jonwehausen @bsmartin-ep do we have updates on:
> Document what ETL funnels might look like
> Document how time to complete might look like

and if we can do them for the KPI dashboard switchovers next sprint? It looks like Caregivers has one of these metrics.

**Comment by bsmartin-ep** [comment]
[Monthly - OMB Dashboard](https://va-gov.domo.com/page/1475431113) has been migrated to BigQuery,

The ETL process that creates the final output table used in all the cards [has been updated to use three components](https://va-gov.domo.com/datacenter/dataflows/14/graph):

- The existing _Vets.gov Historical Events by Month and Year_ archive dataset
- A new created dataset of VA.gov VEO-related events up to June 2020 called _[HISTORICAL] VEO-related Va.gov WBC Modernized & Website Data by Month and Year_
- A new BQ dataset called _BQ - All VEO-related events by month and year_ that loads all VEO-related events for the entire previous month.  This has been scheduled to run on the 1st of every month and will trigger the ETL process to run.

**Comment by jonwehausen** [comment]
Thank you @bsmartin-ep! 

Also side point / update for @joanneesteban: For prior needs to Magic ETL before BigQuery for things like data type changes, scrubbing, parsing, etc, we're able to do more of these basic ETL needs within our SQL queries directly, so the data is ready to go when pulled into DOMO. Of course this assumes the use of those functions doesn't create a major cost inflation, which we have yet to see.

**Comment by joanneesteban** [comment]
Thank you for the updates, @bsmartin-ep @jonwehausen ! Can we test out the time to complete ETL with Caregiver on Staging?

> assumes the use of those functions doesn't create a major cost inflation, which we have yet to see.

Would like to see if effort levels are lower, data integrity is there, and ^cost isn't incredibly inflated.

Also, idea for super low-lift (and by super low-lift, I mean, just one metric instead of many, so who knows) Prometheus MVP would be the one "system availability" metric on the OMB dashboard.

**Comment by bsmartin-ep** [comment]
[Card 'Total Pageviews'](https://va-gov.domo.com/analyzer?pageId=1817321505&cardid=2062967103) on the [VEO dashboard](https://va-gov.domo.com/page/1817321505) has been switched over to the `BQ - Generic - Overall PVs, Sessions, Users, Bounces by Day` dataset.

I added a Beast Mode field to filter the datatable to anything before the previous month so that we don't display incomplete month data erroneously as a drop.

```
(CASE
  	WHEN
  		YEAR(`DATE`) < YEAR(CURRENT_DATE()) OR
  		(YEAR(`DATE`) = YEAR(CURRENT_DATE()) AND MONTH(`DATE`) < MONTH(CURRENT_DATE()))
	THEN 'Y'                                  
	ELSE 'N'
END)
```

**Comment by bsmartin-ep** [comment]
@jonwehausen -

2 x Total Pageviews and 2 x Users cards (OMB and Monthly Council) have been migrated from dataset [Va.gov & Vets.gov PVs and Users](https://va-gov.domo.com/datasources/8b98a85a-873e-4ab1-9c24-58a7eae2d793/details/overview).

This required creating a [modernized BQ dataset](https://va-gov.domo.com/datasources/6d0dd635-41bf-4ee4-9866-c49e8d701870/details/overview) and a Beast Mode field (dataset-scoped) to only show data before the previous month.

Pageviews look pretty close.

Users are dramatically different as you'd expect going from GA --> BQ

### Users

Before:
![image](https://user-images.githubusercontent.com/62304138/90661452-3800f980-e215-11ea-8ddf-4e9bd0cb0ffe.png)

After:
![image](https://user-images.githubusercontent.com/62304138/90661527-4cdd8d00-e215-11ea-90ef-f14f582e207c.png)

I think that's it for these old GA datasets...

- [[HISTORICAL] Vets.gov Pageviews and Users ](https://va-gov.domo.com/datasources/e39fd08e-f4d3-481e-88b0-272bd011c4ee/details/overview)
- [VA.gov - WBC Modernized and All Website Data Views - Pageviews and Users](https://va-gov.domo.com/datasources/f391d07e-e1d4-4e27-b6f0-3be4bca40ca9/details/overview)

**Comment by joanneesteban** [comment]
That is a very dramatic difference...is that also after de-duping?

**Comment by bsmartin-ep** [comment]
@joanneesteban / @jonwehausen -

Cards have been updated to new monthly BQ datasets.  Looking a lot closer now.

[Old](https://va-gov.domo.com/page/1475431113/kpis/details/291701415)|[New BQ](https://va-gov.domo.com/page/1587068891/kpis/details/970194194)
---|---
![image](https://user-images.githubusercontent.com/62304138/91200986-e3a2c180-e6cd-11ea-91ef-29a497074646.png)|![image](https://user-images.githubusercontent.com/62304138/91200967-dab1f000-e6cd-11ea-83ca-119c17c09505.png)

Also updated the pageview cards.

[Old](https://va-gov.domo.com/page/1475431113/kpis/details/1817968585)|[New BQ](https://va-gov.domo.com/page/1587068891/kpis/details/1364064994)
--|--
![image](https://user-images.githubusercontent.com/62304138/91201222-2ebcd480-e6ce-11ea-8625-569572c43029.png)|![image](https://user-images.githubusercontent.com/62304138/91201281-4005e100-e6ce-11ea-92ab-85961791d271.png)

Not quite the exact match on Pageviews I was expecting, but curiously our "new" number matches the July 2020 numbers more closely:

![image](https://user-images.githubusercontent.com/62304138/91201422-69bf0800-e6ce-11ea-9617-6beec4f1e581.png)

(89.93M vs the new 92.39M)

**Comment by joanneesteban** [comment]
Great!  Thanks, @bsmartin-ep ! Do you know why the July numbers for page views would have changed more than the others?

@amycesal , since these reports will start to go out next week, if we're ready to switch over the datasets to BigQuery let's start thinking about how to add annotations that display what the changes are and the value.

**Comment by bsmartin-ep** [comment]
> Do you know why the July numbers for page views would have changed more than the others?

I think I figured out the issue with pageviews @joanneesteban.  The old GA report is configured to run on the **last day of the month** minus one day (and not the first of the next month like it should probably be).  So we've been truncating the last day of pageview data from our monthly total.

HOWEVER - it's also re-fetching **all data back to 2018 every time it runs**, so when the report runs, it fixes the last day of the previous month.

**Comment by joanneesteban** [comment]
## Audit to do

- [ ] Annotate July numbers for September export
- [ ] Audit last month numbers on other reports

**Comment by bsmartin-ep** [comment]
@joanneesteban - 

Pageview dataset has been fixed and back-filled to correct July 2020.

![image](https://user-images.githubusercontent.com/62304138/91452779-fd1e4780-e84c-11ea-9876-9bfae0322d10.png)

I also adjusted the scheduling and back-filled this one:

- [Claims Views Details Only](https://va-gov.domo.com/datasources/d36dd4e7-04c7-4ed9-84c4-ddbc2d584357/details/overview)

This one also had the issue, but I don't think it should be running anymore.  It's pointing to the old vets.gov site and is only (somehow) contributing a few ambient pageviews every month.  Maybe a cached copy on archive.org?

- [[HISTORICAL] Vets.gov Pageviews and Users ](https://va-gov.domo.com/datasources/e39fd08e-f4d3-481e-88b0-272bd011c4ee/details/settings)

**Comment by joanneesteban** [comment]
Thanks, @bsmartin-ep ! Yes, if that's grabbing vets.gov info, cached copy is probably better.

**Comment by bsmartin-ep** [comment]
Dashboard Name|Type|Old|New BQ
---|---|---|---
COVID-19 - VA.gov Response|	COVID|	https://va-gov.domo.com/page/1872052027|	https://va-gov.domo.com/page/2077110052
Auth Experience - KPIs - WIP|	KPIs|	n/a	| https://va-gov.domo.com/page/492918243
Caregivers - KPIs - WIP|	KPIs|n/a		| https://va-gov.domo.com/page/1905395623
COVID Chatbot - KPIs|	KPIs|	https://va-gov.domo.com/page/62901069|	https://va-gov.domo.com/page/986858114
eBenefits - KPIs - WIP|	KPIs|	https://va-gov.domo.com/page/177811372|	https://va-gov.domo.com/page/1726972169
Facility Locator - KPIs|	KPIs|	https://va-gov.domo.com/page/444997301	|
Medical Device Reordering Tool - KPIs|	KPIs|	https://va-gov.domo.com/page/1133411197|	https://va-gov.domo.com/page/737992383
VAOS - KPIs|	KPIs|	https://va-gov.domo.com/page/565662008|	https://va-gov.domo.com/page/1769944412
Monthly- Digital Modernization Council Dashboard|	Recurring|	https://va-gov.domo.com/page/95303793|	https://va-gov.domo.com/page/42290444
Monthly- OMB dashboard|	Recurring|	https://va-gov.domo.com/page/1475431113	|https://va-gov.domo.com/page/1587068891
Monthly- VEO Dashboard|	Recurring|	https://va-gov.domo.com/page/1817321505|	https://va-gov.domo.com/page/730309340

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

eBenefits is ready for your QA.

Dashboard Name|Type|Old|New BQ
---|---|---|---
eBenefits - KPIs - WIP|	KPIs|	https://va-gov.domo.com/page/177811372|	https://va-gov.domo.com/page/1726972169

### Some important things...

1.  The old datasets were running (maybe incorrectly) as a rolling 60 day REPLACE.  I fixed them to start appending a few days ago.  Nontheless, the BQ and GA datasets may have different overall date ranges.  Pretty close (especially if you filter down to a matching data range at the card level) but not exact.

2.  The bounce rate will be dramatically lower on the BQ dashboard due to the artificially high bounce rate of the dedicated eBenefits GA view we were using.  The more comparable bounce rate would be if you filter pages in the All View to just these pages and looked at the Bounce rate for them:

```
    AND REGEXP_CONTAINS(
            hits.page.pagePath,
            r'^(eauth\.va\.gov|www\.ebenefits\.va\.gov)'
    )
    AND NOT REGEXP_CONTAINS(
        hits.page.pagePath,
        r'(/mhv-portal-web|/web/myhealthevet/)'
    )
```

Thanks and let me know what you find.

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep - Overall, QA looks good.
Few things to note:
1. BQ card for PDF Downloads does not have a summary for Total PDF Downloads like the GA version does ([screenshot](https://screenrec.com/share/IpeJajfHsb))
2. I filtered down to just this week for the Outbound Links cards and the data doesn't match super close. Maybe just confirm that it is correct?

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

1.  Fixed
2.  Look OK after I back-filled?

Can you also note if these look OK?

- Monthly- Digital Modernization Council Dashboard 
- Monthly- OMB dashboard 
- Monthly- VEO Dashboard

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

VAOS dashboard ready for your review.  Thanks!


Dashboard Name | Type | Old | New BQ
-- | -- | -- | --
VAOS - KPIs | KPIs | https://va-gov.domo.com/page/565662008 | https://va-gov.domo.com/page/1769944412

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

**BAM2 Medical Device dashboard** is also ready for your review.  Thanks!

Dashboard Name | Type | Old | New BQ
-- | -- | -- | --
Medical Device Reordering Tool - KPIs | KPIs | https://va-gov.domo.com/page/1133411197 | https://va-gov.domo.com/page/737992383

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep 
VAOS Dashboard Review 
- Number of weekly appointments attempted/started - missing summary number
- Number and frequency of Veterans returning to VAOS (03/11/2020 to 09/06/2020) - data isn't matching closely

**Comment by bmcgrady-ep** [comment]
BAM2 Medical Device Dashboard Review
- Traffic by Device Type in Users - there is a blank part in the pie chart
- Appendix cards are not matching

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

Both ready for re-review.

#### VAOS

1. Fixed
2. This needed backfilled and attached to the correct segment.  Looks a lot better!

#### BAM2

1. Fixed
2. I got these closer.  The conversion funnel stuff will be a bit different since it's re-built in BQ.  Thoughts?

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep
VAOS - The _Number and frequency of Veterans returning to VAOS_ card in the GA dataset looks to be double counting. 

BAM2 - The Appendix still looks a little off

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep  - 

Chatbot KPI dashboard ready for your review:

Dashboard Name|Type|Old|New BQ
---|---|---|---
COVID Chatbot - KPIs|	KPIs|	https://va-gov.domo.com/page/62901069|	https://va-gov.domo.com/page/986858114

Thanks!

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

FYI - I'm blocked on the Facility Locator KPI page, so nothing to review on that yet.

1. We don't have the same site search keyword stuff on the All View, so we can't do a direct migration to that.  I think _% of sessions with more > 1 search_ is a good replacement metric, but we need those events recording first.
2. We should switch to the BigQuery time-to-complete stuff in lieu of the (over-sampled) GA user timing.  That's also dependent on the new `fl-` events. 
3. We have a card tracking certain _CTA - Button_ clicks for an event that stopped recording in August.  Checking with Michelle on that. 

Moving this issue to QA now.  Thinking with all this new data (and our blockers) it might be a good idea to kick off a redesign of the FL KPI page.

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep 
**COVID Chatbot Review**
- Inbound traffic to chatbot from external sources with greater than 5 users (April 22, 2020 - Present)  - this data doesn't closely match the GA dataset.
- Percentage of mobile Chatbot Users who clicked telephone Links - this data is doesn't closely match the GA dataset
- The left chart in the Appendix is not matching the chart in the GA dataset.

**Comment by bsmartin-ep** [comment]
Thanks for reviewing @bmcgrady-ep.

#### Inbound

Looks good (other than the scale getting bumped up) now that I backfilled the GA one.

![image](https://user-images.githubusercontent.com/62304138/94216315-0c74cd00-fead-11ea-912d-aae368f7b7b3.png)
vs
![image](https://user-images.githubusercontent.com/62304138/94216326-17c7f880-fead-11ea-8575-e32d6833eb0b.png)

#### Percentage of mobile

Forgot to restrict it to mobile and modified the query to look at the immediate next event.  Looking good!

![image](https://user-images.githubusercontent.com/62304138/94216435-52ca2c00-fead-11ea-8258-f6fe25fab1f2.png)
vs
![image](https://user-images.githubusercontent.com/62304138/94216453-5e1d5780-fead-11ea-929d-8a7291871662.png)


#### Left chart

This one? What differences are you seeing?

![image](https://user-images.githubusercontent.com/62304138/94216486-81480700-fead-11ea-88f6-f26c6528a273.png)
vs
![image](https://user-images.githubusercontent.com/62304138/94216498-8d33c900-fead-11ea-9e9c-d954c60387f7.png)

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep - Okay now the Left chart is looking good. Sorry for the delayed response.
Are there any other dashboard you need reviewed?

**Comment by jonwehausen** [comment]
@bsmartin-ep Wanted to get in writing thoughts / next steps on our current solution to overcome our daily export / query timing discrepancy issue, here are potential next steps: 

**_As a quicker win to our end goal, we could first_:** 
1) Add this snippet to all of our current queries in domo
```
IF (
  SELECT
    COUNT(1) > 0
  FROM
    `vsp-analytics-and-insights.176188361.__TABLES__`
  WHERE
    table_id = CONCAT('ga_sessions_', FORMAT_DATE(
        '%Y%m%d',
        DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
    ))
) IS FALSE THEN
  RETURN;
ELSE
```
2) Adjust the scheduling in domo to be "Advanced" for every 30 minutes beginning at `7:45` am EST

**_Following, we could_**
1) Convert and save all of our current queries to views in BQ
2) Write a stored procedure to do the IF-ELSE check in BigQuery first
3) Adjust the queries in DOMO to query each view (simplify the DOMO query) 
4) Verify advanced scheduling is still configured to every :30 minutes beginning at 7:45 am

cc: @joanneesteban

**Comment by joanneesteban** [comment]
Thanks for the work on this! Closing this ticket.
