### ISSUE TITLE
Gate View Payments Behind Required Login

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11515]
## Goal
Now that "View your VA payment history" is in staging, we want to put it behind authentication so that we can login with test users and ensure the different use cases are covered as designed and developed.

## Tasks
- [x] Establish the View payments behind authentication
- [x] Wrap in downtime time notification (requires BGS)

## Acceptance Criteria
- [x] The feature requires a login to access
- [x] The feature is wrapped in down time notification

### Next steps
- move to service written by backend to pick up data from users, instead of hardcoding
