### ISSUE TITLE
Scheduling - Vets API

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11514]
## Issue Description
Research and Document the Vets API for Scheduling that VAOS is leveraging.
---
## Tasks
- [x] Research data fields returned
- [x] Get status indicators and states of an appointment
- [x] Contact information in VAOS saved to appt. 
- [x] When is the encounter created and ID
- [x] Reason for Visit text field
- [x] VeText notification
- [x] meeting scheduled with PO and Tech team from VAOS

## Acceptance Criteria
- [ ] _Document outcomes and findings in the [Tech Feasibility Doc](#11027)

---

#### Current VAOS findings
 [VAOS research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vaos.md)

[Fields and Data from backend/VAOS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/data%20from%20VAOS.md)

**Comment by massrb** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vista-chief-complaint.md#VAOS

**Comment by mdewey** [comment]
Research findings for VeText: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/engineering#vetext-integration

**Comment by mdewey** [comment]
Laurence (@massrb )

I have a couple of questions for you 

```
- [x] Research data fields returned
  - I see you have the Vets API endpoints mapped out, but to take it one step further, What endpoints are VOAS using to communicate with VAMF?
  - What data fields is VAMF returning (is that the mock data you provided?) and is the VOAS system doing any manipulation of the data (adding fields, removing fields, changing the structure, etc)?
    - More specifically, what VAMF endpoints allow us to get an appointments `reason for visit`?
- [x] Get status indicators and states of an appointment
  - See you have mentioned that an appointment has `a status field with values such as: "status": { "description": "F", "code": "FUTURE" }`. What are the other possible values? 
  - Also I see `type": "REGULAR",` and you mention it is `a type field with values such as "SERVICE CONNECTED", "REGULAR", "ORGAN DONORS", "COMPENSATION & PENSION"`. Is that all the values? and what do those values mean? 
```

**Comment by massrb** [comment]
I don't know the answer to:
`a type field with values such as "SERVICE CONNECTED", "REGULAR", "ORGAN DONORS", "COMPENSATION & PENSION"`. Is that all the values? and what do those values mean?
