### ISSUE TITLE
Rename Branches from Master to Main

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11527]
## Description
We want to change the name from master to main on the branches. 

## Background/context/resources
We will need to work with Teams so they understand and know that the changes coming. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Rename Ops branches_
- [ ] _Talk with other teams so they know this change is coming_
 - Eng meeting, TOT, Multi channels ect
- [ ] _Rename Other braches as well_

## Definition of Done
- [ ] _All branches are renamed to Main_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
AFAIK, there is no pressing desire/need to do this. But, will re-visit if it's something that the platform decides to do. will require careful consideration and coordination across the platform and development teams. we would likely discuss moving to a specific branching strategy and naming conventions that would be part of a larger change. 

Closing.
