### ISSUE TITLE
Design Doc - Logging Solution (Loki)

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11529]
## Description
Let's capture our proposed solution design for logging on the platform using Loki.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Complete a Design doc and ask for feedback_

## Definition of Done
- [x] _Design doc is created_
- [x] _Team and leadership provides feedback _
- [x] _Doc is updated_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by dginther** [comment]
Draft here: https://docs.google.com/document/d/17sF7L_-TwRwwDXp938Mv3wA8nNv6tC85MW9q8LNeKH8/edit#heading=h.ql5zxv5qycy

**Comment by jhouse-solvd** [comment]
Based on our conversation with @pnwstevan and @dginther today, we're going to take another pass on this doc and refine it with our latest understanding of the proposed design and implementation. 

I've moved the ticket back into current sprint and we will groom / assign tomorrow as needed.

**Comment by jhouse-solvd** [comment]
@dginther - is the draft suitable to be put in the Operations space in Confluence? We can always figure out what else to add and where to publish it as we work through documentation inventory over the next month.

**Comment by jbritt1** [comment]
Is this one good to close?

**Comment by jbritt1** [comment]
Think we have a more complete design doc for Loki at this time: https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594437/Loki

**Comment by jhouse-solvd** [comment]
Hmmm, not sure that a doc describing deploying Loki to Kubernetes is quite the same as a "Centralized Logging" solution design doc that we're looking for. There's a draft word version, which I think we can put in confluence, as you'll see in the conversation above.

**Comment by jbritt1** [comment]
Oops, had linked the wrong doc. Here is the one I meant to link: https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593902/Centralized+Logging+using+Loki+and+Grafana

**Comment by jhouse-solvd** [comment]
@jbritt1 - Agreed. that one is perfect! 

Closing.
