### ISSUE TITLE
Project Kickoff - VSP Collaboration Cycle: Healthcare Experience - Questionnaires

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11526]
## Steps to complete Project Kickoff
- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline [Healthcare-Questionnaires](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)

**Overview**
Our goal is to improve the in-person and online pre- and post-appointment experiences for Veterans, contribute to physical distancing efforts in VA facilities, and better integrate Veteran-provided data in VA workflows by **providing Veterans with a digital option to complete pre- or post-appointment questionnaires and screeners**.

**Problem Statement**
Veterans are unable to consistently share and update current health status and medical history that is leveraged in their care across the VA and community providers

- [Team Charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/health-products/healthcare-experience/team-charter.md)
- [Initiatives for Prioritization](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/product/initiatives)
- [Tech Feasibility](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/README.md)
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): Amanda Buckley
- DEPO Product Lead (required): Lacey Higley
- Entire VFS team (recommended): [All team-members names/emails listed here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/health-products/healthcare-experience/team-charter.md#who-we-are)

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES

## Scheduling
- Wed 29th 11-11:30 Preferred Calendar Block

**Comment by mandifrances** [comment]
Hi, based on your ticket it looks like you only want yourself and Lacey invited. Is this correct?

**Comment by abuckley3385** [comment]
@mandifrances I have updated the ticket with the link to the members to invite

**Comment by mandifrances** [comment]
@abuckley3385 They have all been added. Thank you.
