### ISSUE TITLE
[CONSIDER] Add ability to "copy" facility information from search results card

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11525]
## Issue Description
As a Veteran, I would like to easily copy the facility information from he search results card so that I could easily paste it into a form elsewhere on VA.gov. (ie: VAOS)

Current flow from VAOS sends Veterans to find a facility on the Locator and then return to the appointment scheduling flow and enter the facility name/address manually. 

Also consider: add Google analytics event to action

---
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
VAOS flow has changed since this issue was created. Closing
