### ISSUE TITLE
[BE] Figure out why it appears we are sending more direct deposit confirmation emails than there are direct deposit submissions

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#11528]
## Background

We just became aware of the analytics in GA around the direct deposit email. [We can see those here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_r.drilldown=analytics.eventCategory:email,analytics.eventLabel:direct-deposit-update&explorer-table.plotKeys=%5B%5D/).

When looking at them, I noticed that the number of completed email is **more** than the number of successful submissions for direct deposit in the same time period. [We can see that in this report](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p176188361/) and calculate successful submits by subtracting failed submissions from total submissions.

For the period of July 15 - July 21, we see:

- 2398 successful direct deposit submissions
- 3169 emails shown as "completed"

Why are the analytics showing almost 1000 **more** emails sent than there are submissions?

Furthermore, we should document exactly what "open," "completed," and "failed" mean. From Slack, @lihanli said:

- Completed = Send
- Failed = Failed

We still need to determine what "open" is, and confirm that our understanding of "completed" and "failed"is correct.

## Tasks

- [ ] Figure out why it appears we are sending more emails than there are successful direct deposit submissions. Is this an issue with how the analytics set up? Our understanding of what the analytics mean? Something else? 
- [ ] Determine if anything needs to be fixed or updated with regards to how we are tracking either direct deposit submissions or the govdelivery email analytics.
- [ ] Confirm the definition of "open," "completed," and "failed" as it pertains to direct deposit emails and GA.

## Acceptance criteria

- [ ] We understand why there is such a large discrepancy in the analytics between emails sent and successful submissions for direct deposit.
- [ ] We can define "open," "completed," and "failed."

**Comment by lihanli** [comment]
completed: Email has been successfully sent to the user.
failed: Email couldn't be sent to the user.
open: Email has been opened and viewed by the user. Not sure why there are more open events than completed events, maybe gmail has a bot that scans all links in the email for malware before it's sent to the user.

The reason there are more completed events than successful submits is probably because users that have adblock on aren't tracked when they update their DD details. Also if a user has more than one email, they will record more than one "completed" event every time they update their DD. If a user updated their email on the profile page then they will have more than one email, one email for the email account they used to login with, and one email for the updated email.

I looked at the backend statistics for July 22 - July 29 (stats from more than 2 weeks ago are not available), and there were 3030 successful DD updates logged. For the same time period there were 3456 completed email events logged in GA. Users that have more than one email could explain the discrepancy between the GA analytics and the backend statistics, also the way the email events are logged could cause some small differences along with time zone differences, because every day at 1am eastern events for the previous day's emails are sent to GA, if your time range includes 1am then it has a whole day of email events, otherwise it's missing the whole day's events.

**Comment by Samara-Strauss** [comment]
Thanks for this, Lihan. A few thoughts:

> The reason there are more completed events than successful submits is probably because users that have adblock on aren't tracked when they update their DD details.

Is there any way to confirm this? I could see this being the case for a few people, but not a few hundred or more people.

> Also if a user has more than one email, they will record more than one "completed" event every time they update their DD.

Do we send the direct deposit email to both the sign in email address and the address in the profile? It's ok if we do — I just don't remember and want to confirm before documenting that. This makes sense as a security measure.

> I looked at the backend statistics for July 22 - July 29 (stats from more than 2 weeks ago are not available), and there were 3030 successful DD updates logged. For the same time period there were 3456 completed email events logged in GA

Wanted to check in about where you got the number of 3030 successful DD updates. I see the 3,456 emails sent in the analytics, but for successful DD updates, I see a much lower number — 2483, which is the form submits (3145) minus the failures (662):

<img width="399" alt="Screen Shot 2020-08-04 at 11 35 27 AM" src="https://user-images.githubusercontent.com/34068740/89313682-d3f00a00-d646-11ea-8a47-4d02a471803e.png">

@lihanli where did you get 3030 successful updates? Was that from GA or from sentry? If there's a big difference between GA and sentry, we might want to check why the numbers in GA are much lower.

> also the way the email events are logged could cause some small differences along with time zone differences

This makes sense, but I would imagine it also doesn't account for the huge discrepancy we're seeing.

**Comment by lihanli** [comment]
> Is there any way to confirm this? I could see this being the case for a few people, but not a few hundred or more people.

Not sure how to confirm it for sure but it seems likely based on the discrepancy between backend statistics and GA stats. According to [this site](https://www.statista.com/statistics/351862/adblocking-usage/) 27% of Americans use adblock, and there is an 18% difference between the number of updates recorded by the backend (3030) and the number recorded by GA (2483).


> Do we send the direct deposit email to both the sign in email address and the address in the profile? It's ok if we do — I just don't remember and want to confirm before documenting that. This makes sense as a security measure.

Yes we are currently doing that https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/ppiu_controller.rb#L53

> @lihanli where did you get 3030 successful updates? Was that from GA or from sentry? If there's a big difference between GA and sentry, we might want to check why the numbers in GA are much lower.

The 3030 number is from grafana and recorded by the backend when we send an api request to update DD. 
![Screenshot_2020-08-04_15-58-38](https://user-images.githubusercontent.com/830084/89353524-673b3680-d66b-11ea-92f5-b33af120c88c.png)

**Comment by Samara-Strauss** [comment]
> Not sure how to confirm it for sure but it seems likely based on the discrepancy between backend statistics and GA stats. According to this site 27% of Americans use adblock, and there is an 18% difference between the number of updates recorded by the backend (3030) and the number recorded by GA (2483).

Totally makes sense, and thank you for letting me know these stats!

> Yes we are currently doing that https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/ppiu_controller.rb#L53

Awesome, I'll make sure this is updated in our documentation so it causes less confusion in the future.

> The 3030 number is from grafana and recorded by the backend when we send an api request to update DD.

Any idea why the number in grafana is so different than the number in GA?

**Comment by lihanli** [comment]
> Any idea why the number in grafana is so different than the number in GA?
I'm not exactly sure why, I think it's because of adblock. We could add a new GA event sent from the backend triggered by DD updates to make sure.

**Comment by Samara-Strauss** [comment]
Thanks @lihanli. I'm gonna pull @bsmartin-ep into the convo to see if he has any thoughts from a GA perspective.

@bsmartin-ep — We are seeing drastically different numbers for direct deposit updates in Google Analytics vs. Grafana. For the week of July 22 - July 29, there were 3030 successful DD updates logged in Grafana. 

![Screenshot_2020-08-04_15-58-38](https://user-images.githubusercontent.com/830084/89353524-673b3680-d66b-11ea-92f5-b33af120c88c.png)

However,  for the same time period, I only see 2483 successful updates in GA (form submits (3145) minus the failures (662)):

<img width="399" alt="Screen Shot 2020-08-04 at 11 35 27 AM" src="https://user-images.githubusercontent.com/34068740/89313682-d3f00a00-d646-11ea-8a47-4d02a471803e.png">

Lihan thinks this discrepancy might have to do with adblock not recording certain submissions/updates in GA, but I wanted to see if you had any additional thoughts from the GA perspective. Does anything come to mind that might be causing this discrepancy, or anything we can look into to figure this out?

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

From what I see in the code:

https://github.com/department-of-veterans-affairs/vets-website/blob/dd54734f805dff6387ca5c0a19f014ecf057efdb/src/applications/personalization/profile360/actions/paymentInformation.js#L124

...the `Profile - Form Submit - direct-deposit-information` event (the 3,145) is only fired when the Direct Deposit save is successful.

The bottom number (event `Profile Save Failure - Direct Deposit Information`) is only fired when the save fails.

So (unless I am really misreading this), the top number is what you would compare to Grafana.

And looking at this [time frame in GA](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200722&_u.date01=20200729&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22(Profile%20Save%20Failure%20-%20Direct%20Deposit%20Information%7CProfile%20-%20Form%20Submit%20-%20direct-deposit-information)%22,0%5D%5D/), the Unique Events looks pretty close to Grafana:

![image](https://user-images.githubusercontent.com/62304138/89723812-160fa780-d9c9-11ea-944d-004486aa7682.png)

**Comment by Samara-Strauss** [comment]
Ah, ok, @bsmartin-ep — thank you, that makes sense. I think we need to change the label of that so it is clear that is successful saves and not just attempted submissions. That was totally unclear to me and we've been thinking the actual amount save was submitted minus failed for pretty much the whole time we've had the dashboard. But we can do that in a separate ticket. 

Looks like we have all the information we need. Closing.
