### ISSUE TITLE
Explore different Options for Accessing CM controls

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11522]
## Description
We need to access CM controls for ATO that are not addressed yet. There are a few tools we could use or things we could do this address these so we need to do some discovery around which is right for us. 

## Background/context/resources
controls:
CM-3(5) - automated response if baseline changes in an "unauthorized manner"
CM-5(3) - signed components -- we do this where possible, but we don't do any signing between CI and when things get launched into production afaik
CM-6(2) - respond to unauthorized changes
CM-7(4) and CM-7(5) - unauthorized/authorized software list enforcement (this may be a policy-only control)
CM-11(1) - alerts for unauthorized installations

Some ideas for Options:
https://www.fugue.co/product
 https://github.com/dginther/terraform-drift

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Explore the different options and come up with a recommendation_

## Definition of Done
- [ ] _Present a recommendation to the group and create a ticket for implementation_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by ricetj** [comment]
wrong repo
