### ISSUE TITLE
Document key findings from clinician interviews

### ISSUE THREAD

**Issue by arickalewis1** [department-of-veterans-affairs/va.gov-team#11542]
## Tasks
- [x] Review team notes from clinician interviews
- [x] Create [simplified readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/key-findings.md) for findings

## Acceptance Criteria
- [ ] Github file documenting top findings and takeaways from clinician interviews
