### ISSUE TITLE
[BE] Edu/GI bill direct deposit: Determine level of effort for integrating with BGS CH33 DDEFT Services

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#11545]
## Background

As part of the eBenefits migration into VA.gov, we need to move over the direct deposit feature for Education/GI Bill benefits. We have been told that BGS has an endpoint available for us to do this work, but we need to investigate exactly what the current set up is so we can determine next steps forward.

## Tasks

We need to determine whether the BGS CH33 DDEFT services allow the user to view and update their CH33 direct deposit information. Understanding that, create a technical plan for calling those services from vets-api, whether working through the Lighthouse BGS gem or some other way. Identify any obvious trouble areas.

BGS has two methods for CH33 on BenefitClaimWebService. The method names have been redacted below, please reach out for more info. From the BGS service catalog:

```
BenefitClaimServiceBean/ BenefitClaimWebService

Methods
- [redacted] – Finds a Ch33 DD/EFT address from BDN.
- [redacted] - Checks that the transaction for a potential fraud and then calls tptodmiv to update the Ch33
DD/EFT address on BDN.

http://bepdev.vba.va.gov/BenefitClaimServiceBean/BenefitClaimWebService?WSDL
```

## Acceptance Criteria

- [x] Confirm that `the view method` allows the user to view their direct deposit information
- [x] Confirm that `the update method` allows the user to update their direct deposit information
- [x] Create issues in the issue tracker (on Epic #11537) for integrating with the BGS services, assuming vets-api will pass along a payload similar to the one generated by C&P direct deposit

**Comment by Samara-Strauss** [comment]
Endpoint that was shared on the meeting:

https://vbacrpapp2.vba.va.gov:39581/services <https://vbacrpapp2.vba.va.gov:39581/services>  

This may not be a BGS endpoint. We're not sure what the BGS endpoints do and need to reach out for more clarification on what the endpoints they gave us do.

We should also reach out to VBA to see what the endpoints above link to.

There was also something about the SoapUI project that Mike Walker posted in the chat CH33_DD-EFT_updates_soapui-project.xml.

Mike is going to share some resources with Lihan via email.

**Comment by Samara-Strauss** [comment]
Latest [update from Slack](https://dsva.slack.com/archives/C909ZG2BB/p1599146975106700?thread_ts=1599146715.106200&cid=C909ZG2BB). Steve says:

> We've been cycling with BGS about getting a particular service added. Lihan, looks like the last email from them yesterday indicates that they've added the correct thing finally.

So sounds like discovery on this is ready to continue.

**Comment by lihanli** [comment]
i'm no longer getting the `TuxedoServiceFoundButWrongApp` error, so it looks like the service is working now

**Comment by Samara-Strauss** [comment]
Great! @lihanli — do you have a good sense of what you should be doing from here?

**Comment by lihanli** [comment]
yes, i will try to test both endpoints based on the example requests that mike walker provided

**Comment by lihanli** [comment]
@steve-gov i was able to test both APIs using the bgs gem and they both seem to be working

**Comment by mshea0606** [comment]
issue #13286 created
