### ISSUE TITLE
Research plan for Veteran prioritization of focus areas

### ISSUE THREAD

**Issue by arickalewis1** [department-of-veterans-affairs/va.gov-team#11544]
## Tasks
- [x] Determine plan for sort and mockup testing
- [x] Create card sort study
- [x] Create conversation guide
- [x] Create static mockup - see content for form questions #11646 
- [x] Review mockup with VSP

## Acceptance Criteria 
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/veteran-prioritization/research-plan.md) documenting criteria for recruitment and goals of study
- [x] Supplemental research study setup (i.e. tools, conversation guide)

**Comment by abuckley3385** [comment]
@arickalewis1 before we close this ticket I'd like to have the card sort and mockups in a space that can be accessed by the team outside github comments.  Please post your CardSort link or Screen shot and the mockups that were shown to veterans in the study.

**Comment by arickalewis1** [comment]
Attached are the screens shown to Veterans in the study. 
![Veteran info 1](https://user-images.githubusercontent.com/54509359/90037970-71bc8800-dc8a-11ea-8231-fd70b1f50059.png)
![reason for visit](https://user-images.githubusercontent.com/54509359/90037980-741ee200-dc8a-11ea-8a31-b4048f5ee19c.png)

**Comment by arickalewis1** [comment]
@abuckley3385 done, link in acceptance criteria
