### ISSUE TITLE
Map conditional questions 

### ISSUE THREAD

**Issue by arickalewis1** [department-of-veterans-affairs/va.gov-team#11541]
Map out scenarios using the conditional questions provided in the Clinical Reminders documents

## Tasks
- [ ] Research each area and understand question relationships
- [ ] Conduct prioritization research study to inform 
- [ ] Create flows for each clinical reminder

## Acceptance Criteria
- [ ] A comprehensive flow/map documenting all possible paths for Clinical Reminders

**Comment by julieadair1** [comment]
@jparker0425 are you familiar with this?  Is it something we need to prioritize?
cc: @dillo
