### ISSUE TITLE
Content Edit from Public Websites (for How To Apply Wizards)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#11550]
## Why you're here
- Requesting Content support for static public website pages -- in particular, the pages where the How to Apply Wizards will now be placed as part of a strategic move.   The Product Outline with more details about the overall initiative is [here](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665).
- The first Wizard implementation is for [Education Benefit](https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction) and the Benefits team is seeking guidance on the following content components, which are reflected [in this mockup](https://xd.adobe.com/view/17b9e3b9-abb2-4c17-6619-adcc54353687-6188/screen/fef961ac-020e-4da8-a1de-a0fdeacc7cfd/):  H1, H2 and paragraphs

Please reach out Mahariel Rosario @mr0sari0 to finalize the copy requirements.

## Steps to complete intake request
- [X] Submit this request when VSA Public Website team intervention is required
- [X] Provide detailed information of your request to help us understand our role in completing your request 
- [X] Link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Background
*Provide a background of your tool/functionality.*

* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
   * Yes, the How to Apply Wizards which enable veterans to determine in a few easy steps whether they are eligible for a specific benefit -- and/or which benefit is right for them.
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Product Outline](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665)

### Request Type
*Select all applicable and provide details behind your request* 

- [ ] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * Word document with draft if available, or link to the URL where the draft content appears:
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
   * Scope: How many screens? (Or messages, etc.) 

      
      
- [X] **Content support for a static public website page**
   * Is this to update existing static content? 
      * Yes
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * No
   * Provide a list of URL/s that need to be reviewed or updated. 
      * /education/apply-for-education-benefits/application/1990/introduction
   * If it's a small copy section, list what the new info should be and what it is replacing.
      * H1, H2 and intro paragraph(s)

- [ ] **New URL or Redirect Requests**
   * Have you vetted this request by the VSP IA team?
      * < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * Link to VSP IA Redirect Request ticket
      * < Github issue link >
      

   
- [ ] **Implementation of REACT sign in widgets**
   * Full spec including different states and behaviors
      * < link to spec >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*
- In next 5 business days, if possible.

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: Public Websites
- DEPO product owner: John Hashimoto
- Product manager: Leah Keeler
- Designer: Liz Lantz
- FE engineer: Mahariel Rosario
- Product/team Slack channel: #va-how-to-apply-wizards

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [X] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @johnhashva!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva. @peggygannon and I are looking at this now, and we're a little confused. From the product outline and your note above re: the first wizard being for education benefit, it sounds like the wizard should be for the 1990. But the mockup you shared above is for 28-8832 (personalized career planning and guidance). Can you clarify? Thanks!

**Comment by johnhashva** [comment]
@DanielleThierryUSDSVA my mistake on the link.  I will Slack you the link to a video of the in dev version -- which is in fact the 1990.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva  @mr0sari0. Please see attached for our changes to the page content.

[Apply for education benefits_wizard_7.27.20_dt & pg review.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4984139/Apply.for.education.benefits_wizard_7.27.20_dt.pg.review.docx)


We also had 2 questions about the content within the wizard. That content will need to go to Peggy for platforms review:

- If the user's answers lead to the 22-1990 not being the right form, will there be messaging or an alert that will let users know we're directing them to another form?
- The "Are you sure?" alert in the mockup needs a content review. But again, Peggy will need to see the full wizard content.

**Comment by mr0sari0** [comment]
Hi @DanielleThierryUSDSVA, to answer your first question,

> If the user's answers lead to the 22-1990 not being the right form, will there be messaging or an alert that will let users know we're directing them to another form?

Depending on the path the user takes, either an alert or a button to go to the right form will be displayed. [See this flow chart ](https://app.mural.co/t/vsa8243/m/vsa8243/1583339328670/26c12cb441183d0cccb2c0f38d1fb28dff4454f9)for more info.
