### ISSUE TITLE
[Business Optimization] Create Devshop/DEMO instance for "System" and associate it to Production [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11563]
## Story
Learn how to create, associate, and name a new system test instance in Devshop/DEMO, so that all production content can be shared and viewed by stakeholders

## Tasks
- [ ] Create new Devshop instance for System
- [ ] Record and document how the system is created so it can be repeated

## Acceptance Criteria
- [ ] New System is created and viable
- [ ] System is connected to Production and can be rebuilt to bring down content
- [ ] Test that CMS instance of demo works once first rebuild is created.
