### ISSUE TITLE
Test forms endpoints with PACT

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#11564]
## Issue Description
Test the forms endpoints and set up the necessary provider states for PACT contract to pass successfully

---
## Tasks
- [ ] Green verification result when running rake verification task

## Acceptance Criteria
- [ ] Green verification result when running rake verification task
- [ ] Use spec tests as a base starting point
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
WIP branch [here](https://github.com/department-of-veterans-affairs/vets-api/tree/be-tools/pact-forms). Waiting on frontend changes for the forms contracts (contract responses not matching what's being returned in specs)
