### ISSUE TITLE
Create the first draft of documenation/guides for PACT

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#11566]
## Issue Description
Create a draft of PACT guidelines describing PACT implementation details and relevant background info

---
## Tasks
- [x] Create a first draft
- [x] Use PACT search as an example

## Acceptance Criteria
- [x] Have team members review
---

**Comment by LindseySaari** [comment]
Draft PR [here](https://github.com/department-of-veterans-affairs/va.gov-team/pull/11833/files?short_path=4ba53af#diff-4ba53afd2d1c4678cd706a029dd304df)

**Comment by alexpappasoddball** [comment]
@LindseySaari Is this complete?
