### ISSUE TITLE
Test auth'd endpoint with PACT

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#11565]
## Issue Description

For POC, we need to test an auth'd endpoint to verify that PACT can successfully test endpoints that require authenticated users.

---
## Tasks
- [ ] authenticate a user in the provider state
- [ ] set the api_session cookie

## Acceptance Criteria
- [ ] A passing verification result via pact rake task
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
WIP PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/4615)
