### ISSUE TITLE
Search - VA COVID Testing Results on Google (via Castlight)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#11568]
## Issue Description
Google and Apple Maps are displaying VA facilities COVID-19 testing info sourced from [Castlight](https://my.castlighthealth.com/corona-virus-testing-sites/) a third-party health info aggregator.  Those listings, as is, are being interpreted by members of the public as inferring "anyone" can get a COVID test at a VA facility when in fact testing is strictly limited to Veterans, with additional requirements.  In summary per @lalexanderson-dsva: 

- To get a test at a VA facility Veterans must be enrolled in VA health care and registered at that facility/in that system.
- They DO have to have an appointment for testing (no walk-ins).
- Veterans who are exhibiting symptoms of COVID-19 can get a test. The best way to find out if they can get a test or to get an appt is to contact the facility or their provider.

The rigid content/data model used by Castlight and then extrapolated by Google and Apple does not allow for customized information.  Nor does Google strictly adhere to Castlight's data/content model. 
The Google listing format is as follows:

Appointment required (Y/N)
Referral required (Y/N)
Tests limited to certain patients (Y/N)

<img width="358" alt="Google_Search_Raleigh_VA_C19_Testing" src="https://user-images.githubusercontent.com/63107147/88297737-4b7c7b80-ccce-11ea-8ce1-452fa88ce057.png">

Google has incorrectly listed VA facilities as **Referral not required** and we are working with Castlight/Google to change this to **Referral required** to ensure all VA listings display appropriate requirements and selectivity.

---
## Tasks
- [X] Need the VA COVID-19 testing data from Castlight to determine what information the aggregator has compiled and to ensure it is (a) comprehensive and (b) accurate, in that it reflects VA national policy re: COVID testing.
- [ ] Need to determine with @davidconlon and key VHA stakeholders if VA wants to modify (e.g. add more VA facilities) and correct the Castlight data set.
- [X] If VA does want to modify the Castlight (and thus, the Google and Apple Maps) data, determine how this will be accomplished (e.g. update the source spreadsheet provided by Castlight using exported data from the [VA facilities API](https://developer.va.gov/explore/facilities) and by who.

## Acceptance Criteria
- [x] VA facilities information about COVID-19 testing will be accurately reflected in the Castlight data set which feeds the (a) Castlight test site finder page, (b) Google local COVID-19 testing search results and (c) Apple Maps

## Screenshots for reference

Castlight Listing: VA COVID Testing in Raleigh, NC (Wake County)
<img width="452" alt="Castlight_Wake_Cnty_VA" src="https://user-images.githubusercontent.com/63107147/88299326-3b659b80-ccd0-11ea-86d7-a4024c900ee2.png">
Google Listing: VA COVID Testing in Raleigh, NC (Wake County)
<img width="340" alt="Google_VA_Wake_County" src="https://user-images.githubusercontent.com/63107147/88299252-27ba3500-ccd0-11ea-8b8b-666bf65cb27d.png">

## Key Documentation

Castlight VA Data Source
[US_Dept_of_VA_Bulk Data Upload Castlight COVID-19 Test Finder (1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4966683/US_Dept_of_VA_Bulk.Data.Upload.Castlight.COVID-19.Test.Finder.1.xlsx)

Castlight Data Sheet Instructions for Updates
[Bulk Data Upload Castlight COVID-19 Test Finder Instructions.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4966691/Bulk.Data.Upload.Castlight.COVID-19.Test.Finder.Instructions.docx)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
@johnhashva Health Facilities data in XLS extracted from Lighthouse (https://developer.va.gov/explore/facilities/docs/facilities?version=current)

[VHA Facilities-20200723.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4969404/VHA.Facilities-20200723.xlsx)

**Comment by johnhashva** [comment]
Thanks Dave.  Following up with Jennifer/Jeff today.  Do you want to continue to be included in threads and/or meetings on this topic?

**Comment by johnhashva** [comment]
Status Update 7/31:

- Call held with VHA's Jennifer Heiland-Luedtke & Jeffrey Grandon and @davidconlon to review state of play (attached PDF).
- Decision made to determine if VHA leadership would be willing to add all VHA facilities to Castlight listings (and thus Google search, Apple maps) with same information/data about COVID-19 testing -- e.g. Appointment required, Referral required, Tests limited to certain patients with detailed instructions.
- Dave is following up by (a) working with @DanielleThierryUSDSVA to draft instructions (guidelines) text and (b) he and Jenny will share this with VHA/JTO leadership for decisioning.

[DEPO_VA_COVID_Testing_Listings_07292020-compressed.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5007204/DEPO_VA_COVID_Testing_Listings_07292020-compressed.pdf)

**Comment by johnhashva** [comment]
Update:

- With VHA/JTO approval a new uniform content approach to VA listings information was created/authored (using the Castlight datasheet/fields--attached here) and provided to Castlight for import/implementation. This will replace all the data/info that Castlight has independently acquired via phone calls.

- Castlight has been instructed to contact Dept of Veterans Affairs Veteran’s Health Administration Central Office (VHADigitalMedia@va.gov) before making any changes to this data/information . 

- Castlight expects the new data/info to be available via their public [COVID 19 Test Finder tool](https://my.castlighthealth.com/corona-virus-testing-sites/) by COB 8/14 -- and says new data tends to get indexed by Google w/in 5-7 days.

- @johnhashva will validate these changes before closing this ticket.

[VA_COVID-19_Test_Sites_Data_Castlight-REVISED.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5076367/VA_COVID-19_Test_Sites_Data_Castlight-REVISED.xlsx)

**Comment by johnhashva** [comment]
9/1 Confirmed/validated that the VA-approved listings changes have been updated at Castlight, and Google (see attached screenshots PDF) -- and closing this ticket, as a result.

[VA_COVID_19_Testing_Listings_09012020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5157611/VA_COVID_19_Testing_Listings_09012020.pdf)

**Comment by johnhashva** [comment]
Reopening issue to reflect new updates in process.

**Comment by johnhashva** [comment]
10/20 Update: Working with Jeffrey Grandon this week to formalize testing site updates process going forward, including:

- Use of a new, simplified Castlight spreadsheet for VA COVID-19 Test sites list management
- Weekly workflow for sending -- via email -- updates to Castlight (Jeff and Digital Media to manage)

   - Throughout the week the VA add to the worksheet any new data (Remove, Add, Update)
   - By Friday at 3pm Eastern, Castlight will receive via email from the VA Digital Media team the shared sheet and ingest any edits/additions/removals into our database. This job will be run Friday evening, all changes will be reflected late Friday night/early Saturday morning.
    - Castlight will then upload a new clean file, Monday by 12pm Eastern.

**Comment by denisecoveyduc** [comment]
@johnhashva on our last grooming call you said this was was ready to close, is that indeed the case?

**Comment by johnhashva** [comment]
Yes,

**Comment by denisecoveyduc** [comment]
Closing as per John's confirmation.
