### ISSUE TITLE
Design for Completed PDF of the 10-10CG

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#11574]
## Issue Description
When Veterans and caregivers attempt to submit the 10-10CG form and cannot be verified due to MPI lookup (or other reasons) users will receive an error message. Due to security concerns, the error message cannot specify which fields cannot be verified and the user is directed to print, sign and mail a PDF of the 10-10CG. A completed 10-10CG PDF will ease the burden of having to complete the form 

---
## Tasks
- [X] _Update content in designs_
- [X] _Consult with @kevinmirc regarding UX after button is clicked_
- [x] _Consult with platform over placement of print PDF button_

## Acceptance Criteria
- [ ] _User will be able to generate a completed PDF of the 10-10CG_
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
Addressed [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10588)
