### ISSUE TITLE
Spinner Customization  

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#11575]
## Issue Description
When a Veteran or caregiver submit the 10-10CG, it can take 15-30 seconds of processing time, making for poor user experience. A customized message with the spinner (to indicate processing) seems likes a possible solution.    

---
## Tasks
- [ ] _Discover if the spinner  **content** is a customizable (with design and engineering)_
- [ ] _Explore if this is the best solution as typically the spinner is used for indeterminate time

## Acceptance Criteria
- [ ] _Discover the possibilities around customizing the spinner content_
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
