### ISSUE TITLE
Cerner Health Pages x Staging Review Accessibility Checklist

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11579]
## Pages to audit

https://staging.va.gov/cerner-staging/appointments/
https://staging.va.gov/cerner-staging/messaging/
https://staging.va.gov/cerner-staging/prescriptions/
https://staging.va.gov/cerner-staging/records/
https://staging.va.gov/cerner-staging/results/

## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [x] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - Conduct axe browser scan, and document or address issues found
  - [x] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [x] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
  - [x] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [x] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [x] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- [x] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Attach to Collab Cycle Epic**
- [ ] **Labeled with Team**

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/91194520-75520500-e6b5-11ea-89ab-5c27abb1e45a.png)

On this page: http://localhost:3001/cerner-staging/records/

Two links are going to the same destination and have close proximity/context to one another:

![image](https://user-images.githubusercontent.com/12773166/91195890-aed74000-e6b6-11ea-94de-8fe4e5c778bd.png)

**Comment by kelsonic** [comment]
## On this page: https://staging.va.gov/cerner-staging/results/

Can't fix this since this is a common CTA widget and it will mess up the heading levels on all other pages where CTA widgets are used.

![image](https://user-images.githubusercontent.com/12773166/91196328-3ae96780-e6b7-11ea-974c-a3c5885e77d1.png)

**Comment by kelsonic** [comment]
PR is up for fixing some a11y issues found during the staging review 🎉 Once this is merged, then this ticket will be ready for validation + closing! CC @MickinSahni

**Comment by MickinSahni** [comment]
Validated, closing!
