### ISSUE TITLE
Search for and remove links to 2 VA forms on benefit pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11577]
## Issue Description
Per stakeholder Adam Kinder, as of August 1 VA Form 24-0296 and VA Form 24-0296a are being discontinued. Therefore we need to search for where we link to them on our benefit pages and remove the links.

## Tasks
- [x] Do a search on Vets.gov and Drupal for VA Form 24-0296 and VA Form 24-0296a (Kelson)
- [x] Remove links to and mentions of these forms on benefit pages; list pages below (Laura)
- [x] Review and publish pages (Randi)

**Pages where forms are mentioned:**
- [x] https://www.va.gov/change-direct-deposit/

## Acceptance Criteria
- [x] Form names removed from live pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
On vets-website, `24-0296` is mentioned only once in a unit test:

https://github.com/department-of-veterans-affairs/vets-website/blob/6fdb678459ea65b179816fbbed8ac83ad393f4ac/src/platform/forms/tests/forms.unit.spec.js#L75

On a drupal build, I'm actually not seeing any instances of it (this may be due to a technical error in our script but pretty sure there aren't any instances).

**Comment by lwalsh617** [comment]
@RLHecht -- Removed one reference in copy and in a download link Form 24-0296. (Did not find any reference to 0296a).
Screenshot attached of occurrences I removed. 
Drupal link: http://preview-prod.vfs.va.gov/preview?nodeId=710 ![Screen Shot 2020-07-24 at 11.55.54 AM.png](https://images.zenhubusercontent.com/5d41d21a6db71633490a2764/72e5a66c-f030-4b24-afb0-7aacd81bf30d)

**Comment by RLHecht** [comment]
Thanks @lwalsh617 ! This has been reviewed and published. Moving to validate. FYSA @bethpottsVADEPO @MickinSahni

**Comment by RLHecht** [comment]
This update is live on the site. Closing ticket. FYSA @MickinSahni @bethpottsVADEPO
