### ISSUE TITLE
[Frontend] Debt Letters MVP - Incorporate Debt Summary into UI 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11576]
## Issue Description
_The Debt Letter MVP is going to include both a section detailing a debt summary and a section including a table of all debt letters on a Veteran's file with links to download. We need to incorporate the debt summary portion of the tool into the UI._

---
## Tasks
- [ ] _Create a debt summary section to display information about a debt aligning with [the Debt Letters MVP design](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/no-panels?mode=i)_
- [ ] _Share the UI with the design team for feedback_

## Acceptance Criteria
- [ ] _The UI aligns with the provided design_
- [ ] _The design has been approved by a designer_
