### ISSUE TITLE
Claims Status and Disability Claim Application Tier 3 Follow Up

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#11570]
## Issue Description
The contact center team has outstanding Tier 3 issues related to claims status and the disability claim application. We will be working with the BaM 1 team to follow up to confirm that the issue is still affecting these users and facilitating any follow up sessions to investigate persistent issues. 

---
## Tasks
- [x] Develop email template to send out to users with outstanding tier 3 issues. 
- [x] Send out email and track responses 
- [x] Follow up with users who still have issue and include BaM 1 team
- [ ] Monitor BaM1 to ensure investigation on issues take place

## Acceptance Criteria
- [ ] Complete outreach to all users with issues
- [ ] Confirm follow up meetings are scheduled with end users with persisting issues. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Below is the email template that Chante and I have agreed will go out as a follow up email for users that have outstanding issues with VA.gov.

Good Afternoon,

Thank you for your service.

We understand that you were experiencing an issue on VA.gov some time ago and we are following up to inquire if it is persisting.  There were recent modifications which may have solved your issue(s).
Please try taking the steps below before attempting your task again:
•	Clear your Internet browser's cookies and cache. Depending on which browser you're using, you'll usually find this information referred to as “Browsing Data,” “Browsing History,” or “Website Data.”
•	Make sure you have cookies enabled in your browser settings. Depending on which browser you're using, you'll usually find this information in the “Tools,” “Settings,” or “Preferences” menu.
•	If you're using Internet Explorer or Microsoft Edge, and clearing your cookies and cache doesn't fix the problem, try using Google Chrome or Mozilla Firefox as your browser instead. 

–	Google Chrome 
–	Internet Explorer 
–	Mozilla Firefox 
–	Microsoft Edge 
–	Safari 

•	If you're using Chrome or Firefox and it's not working, make sure you've updated your browser with the latest updates.

After taking the steps above, are you still experiencing this issue?  If yes, we will need more information about your issue to investigate the problem and find a solution. Please respond to this email with answers to the below questions. Please provide as much detail as you can: 
•	Please copy and paste the URL or web address you were on when you experience the issue.
•	If you saw an error message, please copy and paste the exact text of the error message.
•	What type of device are you using (i.e. dell laptop, MacBook, iPhone, etc.)?
•	Try a different browser (i.e. Internet Explorer, Firefox, Chrome, etc.). Does the issue occur on all of these browsers?
•	What account do you use to sign into VA.gov (DS Logon, Myhealthevet, ID.me)?

Once we receive the requested information above, we will provide that to the proper team in order to move forward.  Please allow us at least three to five business days to provide next steps.  We look forward to working with you in order to resolve this matter.

Thank you in advance for your patience.

Kind Regards,

The VA.gov Technical Support Team
