### ISSUE TITLE
[Design] Treatment for Covid Debt Hold 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11578]
## Issue Description
_DMC is not collecting any outstanding debt in 2020. An alert needs to be created alerting the veteran. 

---
## Tasks
- [x] _Create alert to notify veterans that debt collection is suspended through end of 2020 

## Acceptance Criteria
- [x] _Veteran will see messaging that debt collection is suspended in 2020 due to covid-19
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
I created a [design for the COVID-19 alert in UXPin](https://app.uxpin.com/edit/8667244#?id_page=130777997). 

I've already created a [ticket for Peggy to review this alert's content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11935). I'll add a ticket for frontend implementation after incorporating her feedback!

**Comment by rileyorr** [comment]
Still waiting on feedback from Peggy. I've added [a ticket for frontend implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11989) so we can move ahead with UAT.

**Comment by sshein** [comment]
Riley can you put a public share link for your COVID-19 alert so I can see it?

**Comment by sshein** [comment]
oh never mind found it :) https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/comment/no-panels?mode=i

**Comment by rileyorr** [comment]
@sshein the link in my original comment wasn't public? That's strange! I've noticed that sometimes people are able to access my UXPin links and other times they aren't. I've just been selecting the 'preview' button and copying that URL. I'll have to look into that

**Comment by rileyorr** [comment]
Peggy's given me [her feedback for this alert](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11935). Going to forward these updates to Brad

**Comment by leahkeeler** [comment]
Moving ticket to Sprint 28 since this will require rework - the message was not approved

**Comment by rileyorr** [comment]
Updated [the alert](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/sitemap?mode=i) based on the content approved by the DMC SMEs. Was a little confused by the feedback's layout in the email so I linked the design in Peggy's feedback ticket to confirm that it aligns with what she was thinking.

**Comment by rileyorr** [comment]
Peggy's approved the final design & I've updated the corresponding frontend ticket.
