### ISSUE TITLE
Contact Center Coordination Matrix

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#11571]
## Issue Description
Develop a job aide matrix for NCC, HRC, VEO contact centers to help agents understand which issues are handled by which contact center. 

---
## Tasks
- [x] Develop first draft matrix documentation 
- [ ] Receive feedback and suggestions from contact center teams
- [ ] Update and finalize matrix documentation with incorporated feedback

## Acceptance Criteria
- [ ] Final matrix documentation that is disseminated to agents at HRC, NCC, VEO contact centers.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Created NCC/HRC/VEO matrix to break down of issues handled by each contact center for disability related tools and application. Sent out to the contact centers and awaiting feedback. Will follow up later this week if I don't hear anything. 

[VA.gov Issue Routing Matrix NCC.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4985379/VA.gov.Issue.Routing.Matrix.NCC.xlsx)

**Comment by Kimberley2019** [comment]
@clantosswett this is pretty old and you have completed the work.  Are you comfortable closing this issue?

**Comment by ATMiddleton** [comment]
New issue # 90993
