### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#11583]
## Background

Slack alerts can be configured by teams to alert (via Slackbot) when a certain set of criteria are met. 

See:  https://dsva.slack.com/archives/CJRQ85PQB/p1603213672329300

## Tasks 

- [ ] DSVA Slack administrator needs to set up a [new app in Slack](https://develop.sentry.dev/integrations/slack/#create-a-slack-app)
- [ ] Add values from the new app to credstash
- [ ] Modify Sentry configuration to inject the Slack configuration values during build/deploy
- [ ] Configure initial integration via Sentry UI
- [ ] Investigate and document requirements for setting up a Sentry team or project's Slack alerts. 
- [ ] Draft documentation (in Confluence?)

**Comment by kfrz** [comment]
https://www.hostedgraphite.com/docs/integrationguide/ig_sentry.html

**Comment by kfrz** [comment]
## 2020-10-27

I met with @KevinMHoffmanUSDS on 2020-10-22, during which time he was able to create a new Slack bot and add it to the DSVA workspace. The credentials are available in that dashboard as well as on-disk in the Sentry instance. 

We will need to continue this integration, which will require adding the values to credstash, validating configuration files include the values, and then finally configuring the integration as described [here](https://develop.sentry.dev/integrations/slack/#create-a-slack-app).

**Comment by jeff2d2** [comment]
@f1337 You had mentioned at the beginning of the quarter that you'd like to take this one on as a pet project. Just curious on current status, or if this is something we still desire to do?
