### ISSUE TITLE
Learning Center MVP - Use Cases

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11581]
## Acceptance Criteria
- [x] Make a copy of the [Product Use Cases Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) and add to your product folder if one does not already exist
- [x] Add/update the various [use cases for your product](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/product-use-cases-template.md)
- [x] (Optional) Submit along with your QA test plan request

## Tasks
- Consider breaking down the use cases between: 
  - Authoring experience (AX) use cases
    - Content fields (accounted for in FE code)
      - Defaults
      - Required/optional
  - VA.gov experience use cases
    - Search
    - Tags
    - Templates
      - some templates pull certain fields, whereas others don't
    - Article links
    - Home page
    - Article list

## How to configure this issue
- [x] **Labeled with Team**

**Comment by jenniferlee-dsva** [comment]
I added a few more use cases, so I think we have enough to submit to Tze. I can't really think of any more.

**Comment by jenniferlee-dsva** [comment]
Is this okay to close, as I have completed the use cases for Tze's test plan?
