### ISSUE TITLE
Update community care requests

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11588]
## Issue Description
Update community care requests to align with v1 move

---
## Tasks
- [x] Update path: v0/facilities/services to v1/facilities/ccp/specialties 
- [x] change type parameter in request: v1 facilities ccp provider search uses `provider` for type (renaming path)
- [x] move all community care requests through v1 controller (urgent care, pharmacy and provider)

Separate issues: 
- Lance: update Swagger docs for v1 facilities [#11603](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11603)
- Lance: expand unit testing for thin models [#11605](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11605)
- update client for PPMS 9.0 [#11607](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11607)
- Lance: refactor into own engine for code ownership (JP) [#11608](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11608)
- Gibran/Michael: for mashup: provide attributes needed for community urgent care and lighthouse (VA) urgent care to Lance [#12085](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12085)
- clean up request to remove specialties from search results since they aren't used in front end [#11609](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11609)
- remove old paths [#11610](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11610)
- deprecate v0 [#8736](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8736)

## Acceptance Criteria
- [x] All requests use v1 controller
- [x] Typeahead for community care services still works
- [x] Confirm specialties/services data displayed on front end align with data in API
- [x] All facility locator search & display functions still work as they do in production, **except that the services and facility type will no longer display on the search results card**

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by darkbushido** [comment]
The response from `v0/facilities/services` looks like
```
[
  {
    "SpecialtyCode": "400VATAICX",
    "Name": "Complementary and Integrative Healthcare Services CIHS - TaiChi ",
    "Grouping": "Other VA Service Provider",
    "Classification": "Complementary and Integrative Healthcare Services CIHS",
    "Specialization": "TaiChi",
    "SpecialtyDescription": "CIHS Other VA Service Provider approved by VA Leadership.  Description: Tai Chi They involves certain postures and gentle movements with mental focus, breathing, and relaxation. The movements can be adapted or practiced while walking, standing, or sitting. Delivered by a certified Tai Chi instructor"
  }
]
```

The response from `v1/facilities/ccp/specialties` looks like
```
{
  "data": [
    {
      "id": "400VATAICX",
      "type": "specialty",
      "attributes": {
        "classification": "Complementary and Integrative Healthcare Services CIHS",
        "grouping": "Other VA Service Provider",
        "specialization": "TaiChi",
        "specialty_code": "400VATAICX",
        "specialty_description": "CIHS Other VA Service Provider approved by VA Leadership.  Description: Tai Chi They involves certain postures and gentle movements with mental focus, breathing, and relaxation. The movements can be adapted or practiced while walking, standing, or sitting. Delivered by a certified Tai Chi instructor"
      }
    }
  ]
}
```

**Comment by mpelzsherman** [comment]
@darkbushido As we've noted, the "name" field is missing from the v1 API. Can we get an ETA on the fix for that?

**Comment by mpelzsherman** [comment]
@mmiddaugh - are you sure we need the flipper support for the v1 API? This will make the code a fair bit more complex since the shape of the data is significantly different (see above). Also, we've seen issues with the flipper mechanism being unreliable, so I would suggest we avoid it whenever possible.

**Comment by mmiddaugh** [comment]
Based on changes  to the data structure, getting the specialties for display on the search results card has become more complex. This can be accommodated, but the team has discussed moving away from displaying the information on the search results card in favor of including it in the results subhead. 

As a result, we've decided to just make the shift now (rather than doing more work today only to prune it out tomorrow)

**Comment by mmiddaugh** [comment]
[Subhead issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11877)
