### ISSUE TITLE
Translation | New Request for Pages in  Spanish & Tagalog

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#11599]
## Product Outline
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/spanish-translation/coronavirus-mvp/product-outline.md)

### Immediate 

**As a Veteran or caregiver with low English proficiency,** I need information about COVID-19 and my essential benefits and services in the language most comfortable to me. This will allow me to understand important and evolving changes and help ease my stress in an already stressful time. 

**As a VA leader,** I need to demonstrate to Congress that VA is taking steps to provide essential COVID-19 in languages other than English.

### Long-term 

**As a VA employee or contractor responsible for providing translated content,** I need a sustainable solution that allows me to provide clear, accurate, timely, and compassionate content.

**As a CTO's office team member,** I need to help ensure that VA has the information needed to fully understand and evaluate the scope, level of effort, and costs of a broader, longer-term translation solution.

## Hypothesis or Bet
**If** we provide translated COVID-19 content, we can both provide critical information now and gather data to help inform a recommendation for a sustainable long-term solution for localized web content.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

- [ ] These pages are translated into Spanish and Taqalog:
  - [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/)
  - [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)

- [ ] We have a process in place for how to maintain translations on these pages

- [ ] Pages meet accessibility requirements

- [ ] Refined design toggles are in place on pages

- [ ] Analytics (including in-language user surveys) are in place on pages

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by SKasimow** [comment]
Adding in this older ticket with links to Usability Testing and Research for reference:https://github.com/department-of-veterans-affairs/va.gov-team/issues/60

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. I updated my original descriptions in this issue to reflect the evolving nature of the work and to scope it to just the COVID-19 content. Feel free, of course, to update further!
