### ISSUE TITLE
[EPIC] VA.gov On-Site search discovery & support

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#115994]
### User Story or Problem Statement

As the Public Websites Team we need to investigate and understand the architecture of site search in order to support the feature and ensure performance.

### Affected users and stakeholders

* Public Websites team

### Hypothesis

We know that robots.txt determines visibility of search results, and need to explore that structure to maintain ongoing updates. We also know that the sitemap factors in, but unclear currently how it's built, responsibility between PW & Platform teams, and how to improve it for better results.

## Acceptance Criteria
- [ ] Understand and document or update documentation about the behavior, API calls, and infrastructure of site search
- [ ] Understand and document or update documentation about the use of robots.txt & propose governance for future updates

### Change management triage

No change management implications as of drafting

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
