### ISSUE TITLE
IA Feedback - Usability Testing Prep - Learning Center MVP

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#11590]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description

This issue describes IA feedback based on the conversation guide and prototype presented in the Usability testing prep meeting. 

**Must**
- None at this time

**Should**
1) For task 4 (navigating between LC articles), there isn't really a question that may prompt them to try and go back to the previous screen or find a related article.  This may happen organically, however it is important to know that users can move around between articles in the LC, especially given there may be many similar articles.  One idea, is while they are on an article, ask a question like "what if you thought one of the other articles you saw in the list would be better information, how do get to that information?"  Do users go to the breadcrumb, the back button, or look for content/link on the page?

2) Navigating between the hubs and the LC will be critical for users that are looking to learn and apply - if their learning process takes them out of the hub, ensuring they have an easy and understandable way to get "back" into the hub where they were to continue exploring/applying for the benefit without getting too lost in the LC and having to start over.  
  - For task 5, what if we give them a topic that is more broad, like understanding their eligibility for disability compensation - do they look in the LC, or do they go to the benefits menu?
Then link them to the eligibility page in the disability hub and give a sub-task specific to agent orange information - they would need to drill into the exposure page and then click on the agent orange page which would go to the LC article. 
The final task would be to go back to the core eligibility information as though they wanted to look and learn more. 
  - Another, more simple option, would be to ask them a question while they are on either the LC page or the hub page that would prompt them go back to the other page, hoping that they don't just use the back button.     

**Consider**
- None at this time

## Definition of Done
- [x] Feedback is reviewed and acknowledged by team 
- [x] Decisions and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by andaleliz** [comment]
Thanks for this feedback @mnorthuis! My comments:

**Task 4**
Added "what if you thought one of the other articles you saw in the list would be better information, how do get to that information?" to convo guide.

**Task 5**
We went back and forth between the wording: 
'Imagine you need to find out how to get compensation for a Veteran who has been exposed to Agent Orange` and
`Imagine you need to find out if a Veteran who has been exposed to Agent Orange can get disability compensation.`

I meant to change it back to the first before the review, and clearly forgot! Thank you. I think the first wording is more likely to elicit the Hub > LC > Hub flow.  I also updated the guide - when the user is on the LC article page, they're asked:
> - Based on this information, what would you do next?

If they do not express intent to click on the CTA, then ask (basically repeating the task):
>Okay, now imagine you wanted to take it a step further and see how you would go about getting that compensation. What would you do?

To encourage, without leading too much.

**Comment by mnorthuis** [comment]
Thank you @andaleliz!   For task 5, I'm looking for more than just the CTA interaction, but the full ability to get back and forth while learning and exploring of the benefit.  Its a lot to get to in one study, so just want to keep an eye on whether users really understand where they were taken and how they can get back if they need to.

**Comment by andaleliz** [comment]
@mnorthuis that makes sense, thanks for clarifying.

Any further action needed from me, or can we close this?

**Comment by mnorthuis** [comment]
Yep!  All feedback has been discussed, closing issue.
