### ISSUE TITLE
Connected apps: Update FAQ to remove reference to MHV for missing records

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#11593]
## Issue Description
Veterans can no longer get their records quicker from MHV. So we need to remove the reference to this in our soon-to-be published connected apps FAQs.

---
## Tasks
- [x] Remove reference to MHV for missing records
- [x] Review (Randi)
- [x] Confirm content accuracy with @markgreenburg 

## Acceptance Criteria
- [x] Content updates confirmed and saved in draft
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @markgreenburg. I've updated the FAQ to remove reference to MHV. Could you let me know if this is accurate? Also, did you also coordinate updating the authenticated content with Tressa or would you like me to do that? I'm happy to coordinate if that's easier. Thanks!

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/aa14c989-eaa4-4fb1-be94-8d1f89bfe38b)

**Comment by markgreenburg** [comment]
That sounds right to me. One thing I wonder about is whether it would make sense to explain why records take 3 days, and perhaps that it isn't specific to connected apps but rather a blanket policy. Something like 'It can take up to 3 days for new health records to show. This is to give your VA health care team time to discuss any results with you before making them available for viewing online.' Or...something to that effect. Thoughts? CC @careyotto

**Comment by markgreenburg** [comment]
@DanielleThierryUSDSVA – also, I haven't coordinated with Tressa on auth'd content. I think it would make sense to use the same content in both places, once finalized. Let me know if you need me to circle back with her on that, otherwise I'll assume you two have connected. Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @markgreenburg! I like the idea of providing the reason. Do we know that's the reason for it taking 3 days or do we need to confirm that first?

**Comment by markgreenburg** [comment]
@DanielleThierryUSDSVA – yes, the hold is to ensure that clinicians have time to relay sensitive diagnoses to Veterans rather than Veterans finding out about the diagnosis online first. Though I don't know that we need _that_ level of specificity. Up to the content experts :)

**Comment by DanielleThierryUSDSVA** [comment]
thanks, @markgreenburg! Will update this.

@MickinSahni We can leave this in in progress for sprint 28. thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Complete and closing.
