### ISSUE TITLE
Update the client for PPMS 9.0

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11607]
## Issue Description
Related to our migration to v1, we need to update the client for PPMS 9.0

DWS 9.0 Integration Testing Dates:

- 8/6, Thursday:  Start of Integration Testing in Non-Prod/INT 
- 8/10, Monday:  Target date to report testing issues.
- 8/11, Tuesday:  Retesting, if needed.
- 8/12, Wednesday: Downstream Application Sign-Off.

Changes:

The 14 DWS end-points are CHANGING in PPMS 9.0.  These end-points will have ADDITIONAL FIELDS for TeleHealth and Sub Service in the JSON output.  No fields are being removed from the output and no existing field names are changing.  An optional input parameter has been added to 4 of the end-points for TeleHealth search functionality.  

<details>
<summary>More information </summary>

![image](https://user-images.githubusercontent.com/55411834/89584085-b6fb3880-d7f8-11ea-8762-ba9db527ea66.png)
</details>

 

---
## Tasks
- [ ] update the client for PPMS 9.0

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
