### ISSUE TITLE
Generate new v1 engine

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11608]
## Issue Description
Moving PPMS into a Rails engine would allow Facilities team to have code ownership 

## Tasks
Convert all code to exist within the engine 

## Acceptance Criteria
- [ ] No loss of functionality 
- [ ] Facilities team code ownership
- [ ] Updated documentation
- [ ] No dependency on front end to make changes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
