### ISSUE TITLE
Remove specialties from api response

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11609]
## Issue Description
Following our migration to v1 and the ccp controller, how can we clean up our request and remove specialties from search results since they aren't used in front end

---
## Tasks
- [ ] Remove specialty data from api response
- [ ] Confirm Pact tests do not expect specialities

## Acceptance Criteria
- [ ] Specialty data is gone, nothing breaks

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
