### ISSUE TITLE
Audit for number of pdfs on our benefit pages

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#11616]
## Issue Description
We want to know how many and what kind of pdfs are on our benefit pages.
- How many are fillable forms provided as printable alternatives to online applications? 
- How many are fact sheets, guides, brochures, or other assets provided for users to download and print?

---
## Tasks
- [ ] Audit benefit hubs to locate pdfs
- [ ] Record benefit page url and pdf url
- [ ] Identify type of pdf: factsheet, form, etc.
- [ ] Share with Chris J

## Acceptance Criteria
- [ ] All pdfs accounted for and categorized.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
Ignore me if this is not helpful, but Patrick's crawl of all VA.gov/{blah} paths surfaced: 

total va.gov/ paths: ~62099
total va.gov/ paths that are PDFs: ~18552 

I know this doesn't show the narrow 'on the benefit pages' count, so maybe not usable. 

FYSA: He's currently running a crawl of subdomains for me, so we'll have more complete picture later. (It's a lot, so could take a week +).

**Comment by bethpottsVADEPO** [comment]
Health care:
Total number of PDFs: 23
Breakdown:
- 14 forms
- 9 other (handbook/factsheet/program guide/catalog/patient statement)

https://www.va.gov/health-care/eligibility/
Spanish-language 10-10EZ

https://www.va.gov/health-care/how-to-apply/
Spanish-language 10-10EZ (appears 3 times)

https://www.va.gov/health-care/after-you-apply/
* -	Download a sample handbook: https://www.va.gov/healthbenefits/vhbh/publications/vhbh_sample_handbook_2014.pdf
* -	In accordion “How do I update my personal information?”: https://www.va.gov/vaforms/medical/pdf/vha-10-10ezrfill.pdf

https://www.va.gov/health-care/family-caregiver-benefits/champva/
* -	In accordion: “An 18-to-23-year-old dependent child of a Veteran
https://www.va.gov/COMMUNITYCARE/docs/pubfiles/factsheets/FactSheet_01-15.pdf
* -	In accordion: A primary family caregiver of a Veteran with injuries and/or disabilities
https://www.va.gov/COMMUNITYCARE/docs/pubfiles/factsheets/FactSheet_11-01.pdf
* -	A CHAMPVA beneficiary who’s 65 years old or older—or who qualifies for Medicare at any age
https://www.va.gov/COMMUNITYCARE/docs/pubfiles/factsheets/FactSheet_01-12.pdf
* -	What benefits do I get with CHAMPVA
https://www.va.gov/COMMUNITYCARE/docs/pubfiles/programguides/champva_guide.pdf
* -	How do I get CHAMPVA benefits?
https://www.va.gov/vaforms/medical/pdf/vha-10-10d-fill.pdf
https://www.va.gov/COMMUNITYCARE/docs/pubfiles/factsheets/FactSheet_01-15.pdf
* -	What happens after I apply?
https://www.va.gov/COMMUNITYCARE/docs/pubfiles/factsheets/FactSheet_01-03.pdf

https://www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/
* -	“Order by mail”:
https://www.va.gov/vaforms/va/pdf/VA2346a.pdf
* -	What hearing aid accessories can I order?:
https://www.va.gov/opal/docs/nac/dlc/catalogBatteries.pdf

https://www.va.gov/health-care/order-prosthetic-socks/
“Order by mail”:
https://www.va.gov/vaforms/va/pdf/VA2345.pdf

https://www.va.gov/health-care/get-medical-records/
* -	“How do I opt out?”: https://www.va.gov/vaforms/medical/pdf/10-10164-fill.pdf
* -	“If I opt out, how can I opt back in?”:
https://www.va.gov/vaforms/medical/pdf/10-10163-fill.pdf


https://www.va.gov/health-care/update-health-information/
“How do I use this form to update my information?”:
https://www.va.gov/vaforms/medical/pdf/vha-10-10ezrfill.pdf

https://www.va.gov/health-care/pay-copay-bill/
“If you need help understanding your patient statement”: https://www.va.gov/HEALTHBENEFITS/resources/publications/IB10-691-understanding_your_VA_patient_statement.pdf

https://www.va.gov/health-care/pay-copay-bill/financial-hardship/
* -	“Fill out an Agreement to Pay Indebtedness”: https://www.va.gov/vaforms/va/pdf/VA1100.pdf
* -	“Fill out a Financial Status Report”: 
https://www.va.gov/vaforms/va/pdf/VA5655.pdf
* -	“Fill out a Request for Hardship Determination”:
https://www.va.gov/vaforms/medical/pdf/vha-10-10HS-fill.pdf

https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
* -	At the end of Option 1: “Download our guide for more instructions”:_files_2020-07_Veterans_User_Guide_BTSSS_20200622%2520508%20(1).pdf (opens in a new tab)
* -	Option 2: “Fill out a claim for reimbursement for each appointment”: https://www.va.gov/vaforms/medical/pdf/vha-10-3542-fill.pdf
* -	“How do I file a claim for special mode transportation expenses? (appears twice): https://www.va.gov/vaforms/medical/pdf/vha-10-3542-fill.pdf

**Comment by FranECross** [comment]
@bethpotts It appears that a listing of PDFs was obtained? May I close this ticket? Thanks!

**Comment by bethpottsVADEPO** [comment]
@FranECross Good to close this! Thank you.
