### ISSUE TITLE
ForeSee Survey Request for Caregivers

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#11620]
# Request the ForeSee Survey

## What this form is for
Use this template to request adding the ForeSee Survey to your product.

ForeSee FAQ [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/foresee-readme.md)

## Description
Application for the Program of Comprehensive Assistance for Family Caregivers (PCAFC), a benefit for family caregivers.

### Launch Date
Targeting a soft launch in April.

### Staging URLs
https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/

### Production URLs
*Please provide Production URLs* (not yet available)
https://va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/ 

Question - does it make sense to have ForeSee on the first page of the application, or on this page: https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/?

Similarly, wouldn't it make sense to have it at the end of the form?

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the ForeSee Comment Card

**Comment by joanneesteban** [comment]
@ala-yna - per:

> does it make sense to have ForeSee on the first page of the application, or on this page:

and

> Similarly, wouldn't it make sense to have it at the end of the form?

It would depend on the feedback that you're trying to glean/the user goals you have in mind. Keep in mind that these are opt-in 5 star comment cards, and not extensive surveys (until we switch over to Medallia, and that will be a separate conversation). We can have the feedback button to track all of the Caregiver pages, and then zone in on your product goal in your KPI dashboard.

https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/? - Feedback here would come from if you want to see feedback on how you're piping users onto your application page. 

https://va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/ - this would give you feedback on your form onboarding process

End of form - this would give you feedback on your form process

Let me know, and I can add the button to staging!

**Comment by ala-yna** [comment]
Thanks Joanne!

I agree, it makes sense to add it to the information page:
https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/

and the confirmation page at the end of the world (after success)

and maybe the form intro page, if you think that's necessary

Does that work?

**Comment by joanneesteban** [comment]
The feedback button has been applied to the following URLs in staging:

- staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/review-and-submit
- staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/confirmation
- staging.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/

Here's what it looks like on the information page:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/10cdb31c-2008-42e9-bfe1-6f7d7255d6a0)
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/7f2243cb-ad81-4af6-8647-ff8fc6e7551a)

@ala-yna I can't see the confirmation and review & submit pages, but once your team tests that the feedback button shows up on your pages correctly, I can push these to the production URLs whenever I get your okay!

**Comment by joanneesteban** [comment]
@ala-yna - when I get your confirmation, I can go ahead and push this to prod

**Comment by joanneesteban** [comment]
# Pilot the Medallia VFS specific survey

## Description
Test the Medallia VFS specific survey with 1010-cg. 

Other info: ForeSee data is pulled into Domo manually every Monday. Medallia data will also be pulled into BigQuery/Domo manually until the Medallia<>BigQuery ATO is completed.

### Staging URLs
*Please provide staging URLs*

### Production URLs
*Please provide Production URLs*

### Tasks
- [ ] VSA Caregiver provides URL(s) where feedback button should appear
- [ ] VSP Analytics & Insights to remove ForeSee staging URLs if these are the same
- [ ] Both VSP and VFS teams test, provide feedback if any, and approve
- [ ] VSP Analytics & Insights to remove ForeSee production URLs if these are the same
- [ ] VSP Analytics & Insights push Medallia survey to production
- [ ] Both VSP and VFS teams test, provide feedback if any

## Acceptance Criteria
VFS team and VSP can retrieve user survey information from 
- [ ] Survey tested and approved by both VSP and VFS teams in staging
- [ ] Survey pushed to production

---
### Screenshot of survey:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/95f3c511-a9fa-443b-9ed0-7dce67e4f347)

**Comment by joanneesteban** [comment]
### Update - 09-08-2020

**Staging URLs removed from ForeSee:** 
- *staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/review-and-submit
- *staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/confirmation
- *staging.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/

The feedback button on ForeSee is still appearing on Staging for me on another test. @ala-yna  could you check on your end to see if this is also the case for you? I might need to open a case with ForeSee before we can add in Medallia.

**Comment by joanneesteban** [comment]
@ala-yna Fysa added the Medallia button to the staging URLs. We're still working on tweaking the design a bit, but will let you know when it's ready to test.
