### ISSUE TITLE
Order Descending Dates in Debts Response

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#11621]
## Issue Description
Debts should be returned in a descending response in the `GET /v0/debts` response, ordered by their dates.

---
## Tasks
- [ ] Add logic to order the dates by a descending response.

## Acceptance Criteria
- [ ] Dates are returned in a descending order.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
