### ISSUE TITLE
Review Instances (RIs) - useability challenges

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#11629]
## Issue Description

We've received some feedback lately that review instances are difficult for those without engineering backgrounds to get into due to having to configure the SOCKS proxy. This is reducing their value as a development and review tool because some folks have been relying on developers to send updated screenshots or finding other mean to share their early-stage work.

We've toyed with some ideas around making them publicly accessible through some means, but no concrete decision has been made. I think at a minimum, we should come up with a decision doc around why they can't be if that ends up being the call.

Thinking through solutions briefly, what I can think of:
- spend some time to make SOCKS easier to configure and use
- expose publicly and put some sort of extra auth in front of them.. this may not be easy policy- or process-wise
- migrate to vfs.va.gov domain and expose them to CAG/GFE (this should probably be done anyway)
- use a tool like ngrok to toggle access on/off?

---

## Acceptance Criteria
- [ ] _Do some discovery on what underlying issues might be and decide on path forward.. I'd expect the result of this ticket to be a plan which might just be an epic_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
We need to think a bit more about the where review instances are hosted (network segment(s)) and how they are accessed. There may be way to solve this by changing this setup. per @dginther

**Comment by mchelen-gov** [comment]
renamed because "accessibility" often refers to functionality for users with disabilities

**Comment by mpelzsherman** [comment]
I thought there was an agreed-upon solution for this (using Github authentication).

See https://vfs.atlassian.net/wiki/spaces/VI/pages/976781382/Tool+Logins

**Comment by mchelen-gov** [comment]
> I thought there was an agreed-upon solution for this (using Github authentication).
> 
> See https://vfs.atlassian.net/wiki/spaces/VI/pages/976781382/Tool+Logins

@mpelzsherman that page covers general tool auth guidance, which is really helpful. the actual implementation still needs to take place for RIs. there might be other networking issues that need to be resolved in addition to auth, per @jhouse-solvd:

> We need to think a bit more about the where review instances are hosted (network segment(s)) and how they are accessed. There may be way to solve this by changing this setup. per @dginther

**Comment by mpelzsherman** [comment]
Thanks for the reply, @mchelen-gov .  I'm not invested in the specifics of the solution, just hoping to see some progress.

**Comment by jhouse-solvd** [comment]
@mchelen (shared w/ @mpelzsherman on #16350 as well) - Ops is working w/ Dror on a Spike to see if we can move RIs into a different env, and what else might be necessary to make these things more easily accessible. 

see here for more details: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22545

**Comment by mchelen-gov** [comment]
@jhouse-solvd awesome thanks for the link! added it to this epic

**Comment by rmtolmach** [comment]
The QA Standards team is doing discovery for review instances. This can be closed.
