### ISSUE TITLE
[Design] Debt Letters MVP - Updated Empty States 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11639]
## Issue Description
With the updated MVP including both debt summary and a list of downloadable letters on the same screen, we need to create empty states for the following use cases:
- If a veteran accesses the tool and they've never had a debt; i.e. no debts or debt letters on their record
- If a veteran accesses the tool and they don't have any _current_ debts but they have resolved debts; i.e. no debts but letters from past debts are available to download
- If a veteran received a debt after March 2020 they will have current debts but no letters to download

---
## Tasks
- [x] _Update [the UXPin prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130748284/simulate/no-panels?mode=i) to include empty states for the use cases mentioned above_
- [ ] _Get feedback on the proposed designs from team members_
- [x] _Update GH documentation to include the updated designs_
- [x] _Create a ticket for frontend implementation_

## Acceptance Criteria
- [ ] _Designs have been reviewed and accepted by the team_
- [x] _GH documentation is updated_
- [x] _Designs are linked as a comment_
- [x] _Ticket for frontend implementation is created_

**Comment by rileyorr** [comment]
I've created designs for all three use cases and have linked the UXPin prototypes in [the Debt Letters MVP design GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/prototypes.md). 

I've also created [a ticket for Peggy to review the content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11902) for these empty states. I'll create the ticket for frontend once I've incorporated her feedback :)

**Comment by rileyorr** [comment]
Still waiting on content feedback from Peggy, but I went ahead and made [a ticket for frontend development](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11986) for these empty states so we can move ahead with UAT.

**Comment by leahkeeler** [comment]
moving to sprint 28 per above

**Comment by rileyorr** [comment]
Peggy provided me final content for the covid empty state, and Brad's already implemented it :)
