### ISSUE TITLE
Add section to style guide about when and how to use bold text

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11636]
## Issue Description
We need to add an entry to the VA.gov style guide about how and when to use bold text on our pages. This will better help content team members follow our voice and style as they write and edit pages. 

Beth's draft to add to style guide: 
[https://app.zenhub.com/files/133843125/08d978e8-107e-4d12-b420-cb23cdce34c9/download](https://app.zenhub.com/files/133843125/08d978e8-107e-4d12-b420-cb23cdce34c9/download)

Branch to work on: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/Randi-bold-text-entry/src/_content-style-guide/bold-text.md
Pull request: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/278

---
## Tasks
- [x] Review Beth's copy in Word (Randi)
- [x] Add copy to style guide in new branch (Randi)
- [x] Review file in GH (Beth)
- [x] Approve PR and merge branch (Beth)

## Acceptance Criteria
- [x] New entry added to VA.gov style guide
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpottsVADEPO I've added your entry to the style guide as a new branch, which I put above. I also found a page as an example for the third bullet point. Let me know if you think there's a better one we should use.

**Comment by bethpottsVADEPO** [comment]
@RLHecht That's exactly the right example that you chose. Thank you. And can you change the very last line from:
Adverbs that emphasize a point being made in the text, like “only if”

To (change bolded just so you can see where the change is...):
**Words used to** emphasize a point being made in the text, like “only if”

**Comment by RLHecht** [comment]
This is updated. Also changed the the URLs to hyper links.

**Comment by RLHecht** [comment]
This is now live in the style guide. Closing ticket. FYSA @MickinSahni @bethpottsVADEPO
