### ISSUE TITLE
[SD] Discovery - Search Research Epic

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#11638]
## High Level User Story
As a Veteran, I need to find relevant search results quickly so I can get the information I need and move on with my life.

As a product owner, I need to understand the problems Veterans have with search so I can implement improvements.

## Goals
_What outcome(s) do we want to see?_ 

- [ ] Identify existing problems Veterans have finding information on VA.gov
- [ ] Identify existing problems Veterans have with site search on VA.gov

**Update 8/11/20**
- Research goal will be **How to improve VA.gov site search**
- Issues created.

------------------
### To start:
- Recommend methods for 2 potential research goals:
  1. Broader, general problems Veterans have finding information on VA.gov (organic search, site search, etc)
  2. How to improve VA.gov site search

### Discovery Tasks

- [x] Create research plan #12331  
- [x] Complete social media research #16189 
- [x] Request Medallia on-site survey #16186
- [x] Collect Approvals for Research Plan  #16822 
- [x] Review Research Plan with VAPOs #16902
- [x] Create an analytics research plan #16823
- [x] Create Conversation Guide #12333 
- [x] Collect Approvals for Conversation Guide #16886
- [x] Comparative analysis research #16936 
- [x] Send S+D Team the research plan link in Slack for final review
- [x] Practice Usability Study Conversation with Veteran on Staff (Brian - Jan 14)
- [x] Submit Research Plan to Lauren (est. Jan 15- subject to change)
- [x] Recruit for research sessions (Perigean) [will take ~ 1 week  (caveat that the req are more important than timing- estimated  Jan 22- Jan 27 (subject to change)]
- [x] Conduct Pilot Session with Perigean 
- [x] Schedule research sessions (Perigean) - [Timeline for scheduling: within 1-2 weeks; Estimated: Jan 25-Feb 5 subject to change. Scheduling Window is 11am - 4pm)
- [x] Recruit session notetakers #12334 [Perigean will take notes and there will be recordings for any direct quotes,Laurel may take notes as well)
- [x] Conduct Discovery Research Sessions (8-10 sessions estimated) (at a minimum, the team lead, PM, designer, content person should join these sessions). #12332
- [x] Discovery Synthesis - should be conducted as a team, led by designer. #12336
- [x] Create a topline summary #12335
- [x] Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
- [x] Stakeholder Readout #20438
- [x] Integrate findings and next steps into Product Roadmap Planning with help of PM #20435

**Comment by andaleliz** [comment]
Meeting today with myself, @johnhashva, @sshein and @MickinSahni. Determined research scope will be to VA.gov site search (rather than broader Veteran search behavior) as we feel we can make a more meaningful impact on Veteran UX with a narrower focus.

This research is going to be on hold per team priorities until other UX efforts are completed.

Updated description + created appropriate tickets so we can run when we're ready!

**Comment by denisecoveyduc** [comment]
All associated issues for the epic have been completed and research findings have been integrated into backlog issues for prioritization.
