### ISSUE TITLE
Project Kickoff: Move How To Apply Wizards

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#11645]
## Steps to complete Project Kickoff
- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts 
- [Product Outline](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665)
- Explanation of the problem space
  - Veterans learn about benefits and eligibility requirements from detailed content pages. These pages may include pre-requesite questions potential applicants can answer before initiating the "actual" application process. Answers to these questions help determine where applicants are taken in order to apply i.e. which form or online tool is most appropriate.
  - Veterans typically land on these content pages while researching benefits. However, these pages may not always make it easy for Veterans to find these helpful in-content wizards -- and consequently some veterans are filling out the wrong forms -- e.g. there is a high rate of ineligible applications submitted online.
## The Solution
We are moving/consolidating these pre-requisite Wizard steps with the application tool landing page in order to:

1/ Make the Veteran experience of starting their online application more seamless. (Today, they have to find the Wizard on a content page, and from there, fill out the wizard and then are sent to the tool landing page.)

2/ Make apply online CTAs from tier 2 content and other content outside of the benefit hubs more clear and direct. Example: from our mvp form detail landing pages or from the modernized mvp form search results.

## Meeting attendees from **requesting team**
- Product Manager (required): Mickin Sahni @MickinSahni & Leah Keeler @leahkeeler & Luke Majewski @luk 
- DEPO Product Lead (required): John Hashimoto @johnhashva 
- Entire VFS team (recommended): **names**

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

**Comment by mandifrances** [comment]
Hi @johnhashva do you have a preferred date in mind for scheduling? In the scheduling section of the ticket is a link to the calendar that shows available days.

**Comment by johnhashva** [comment]
Let me work with @MickinSahni to align with @leahkeeler and @luke-gcio on best day/time for us.

**Comment by mandifrances** [comment]
Scheduled for Friday at 2pm ET

**Comment by FranECross** [comment]
@HeatherWidmont Does this epic belong to Benefit Management Tools instead of the Public Websites Team? I'll remove the PW label if so...

**Comment by HeatherWidmont** [comment]
Hi @FranECross! This is not a Benefits Management Tool epic

**Comment by FranECross** [comment]
Closing old epic; if this topic arises again, new tickets/research will occur.
