### ISSUE TITLE
Add (PDF) to end of links that send users to a PDF

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11649]
## Issue Description
Per our style guide, there should be a (PDF) at the end of any link that takes users to a PDF. The below pages need this added.

**Pages to add (PDF)**
- [x] https://www.va.gov/health-care/get-medical-records/ (After the links to the two forms)

---
## Tasks
- [x] Add (PDF) to end of link

## Acceptance Criteria
- [x] Correct style is showing on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This change was made. Moving to validate and will close when live this afternoon. FYSA @MickinSahni

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thank you! I was just looking at this ticket last week, and wasn't sure we'd add anything more to it, so thank you for making that decision!

**Comment by RLHecht** [comment]
No problem, @bethpottsVADEPO I figured if we find more, we can always reopen this ticket or create a new one. There shouldn't be too many out there but you never know!

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni
