### ISSUE TITLE
Define and document end of Q3 priority initiatives

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11646]
## Issue Description
Based on the stakeholder and research done to date the Unmet Needs and Initiatives have been created in the Product outline.  This issue is to work with the PO to prioritize what are the "top 3" we want to begin design and development on for Q3 deliverable.  

---
## Tasks
- [x] Create [Initiatives and features documentation for priority form fields](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/this-visit.md) to define the scope of the solution
- [x] Update [Q3 Release Plan with Scope and Go To market strategy ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/release-plan/2020/q3-2020-target-launch.md)

## Acceptance Criteria
- [x] Create Github tickets to be ready for sprint 28 design/dev
- [x] Determine with UX if we require user testing before development #11544 
- [ ] Determine with Engineering estimate on time to complete the features to 
- [x] Collaboration Step (unknown)

**Comment by abuckley3385** [comment]
@LEHigley @arickalewis1  see link above for Initiatives and features documentation for our Q3 priorities fields to be used in #11544 research mockup

**Comment by abuckley3385** [comment]
Will work through engineering estimates in sprint 28 once full feature docs are complete
