### ISSUE TITLE
Loki Logging: Initiative Checklist

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11647]
## Is this service / tool / feature...  
 This new tool is part of an initiative/service of logging. We are redoing how our logging works. 

## ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### Required Artifacts

* **Usability test**: \<link to GitHub issue, or provide reason for skipping>
* **Manual QA**: \<link to GitHub issue or documented results>
* **Automated tests**: \<link to tests, or "N/A">

## ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _This is falls under the Logging product_
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    - [ ] ... including happy paths, and how you'll react to unhappy paths
    * _Note: this Product name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-brief-template.md) exists for this product/feature tool
    - [x] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a User Guide (_TODO: link_) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the Product Brief
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### Required Artifacts

* **Product Name**: `Logging`
* **Product Outline**: \<https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/logging/product_outline.md>
* **Product Brief**: \<https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/logging/readme.md>
* **User Guide**: \<link to User Guide>

### Required Artifacts

* **Success metrics**: \<https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/logging/product_outline.md%3E>
* **Release plan**: \<https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/logging/release_plan.md>

### Additional Doc 
* **Logs by Service**: \<https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/logging/logsByService.md >

**Comment by ricetj** [comment]
Will add comments about the format here:
- Is the intent to add text under each area?

**Comment by gunsch** [comment]
Thanks for the feedback! Couple responses, I'm making some changes to the checklist based on your feedback too.

> Is the intent to add text under each area?

Just checkboxes, plus text in the "Required Artifacts" sections. Is there another label / explanation that would make that clearer?

> We also include how to manage doc int the internal section.

I don't understand this comment, can you say more about that?

> for success metrics, the template asks for a link to the location for these. Should this be a separate doc now or just a link to the Product Outline

Product Outline is fine, I'll add some clarifying text to the template

> Can we provide more info around this "including happy paths, and how you'll react to unhappy paths", I'm assuming this is if customers are going to the wrong location to access your tools? Documentation? both?

TBH I think I'm going to scratch that one; I think "what should be in the Product Outline" ought to be covered by the Product Outline template and explained there, not in this checklist

> Could this be added to the super epics instead of a separate issue?

Interesting idea! Andrea and I chatted about this, I think maybe yeah at some point in the future once this process gets a little more stable / better integrated into our overall product process.

**Comment by jhouse-solvd** [comment]
Please see [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17389)

Closing.
