### ISSUE TITLE
[Analytics]  Review and test all links and lines of data Coatesville in Stakeholder review document VISN-4 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11654]
## Story
As a web maintainer and stakeholder I need to have a complete list of links and pages that I will review, so I can best provide feedback and ask questions regarding the pages.

## Resources
[Stakeholder Review documents](https://drive.google.com/drive/folders/1fmlCo1VJ3YB8npVSg4jVu1nBTHHoTDxo)

## Tasks
* Review each URL link in Work document to confirm it is working, correct those that need correction, and confirm if any pages or areas are missing or should be included in stakeholder review.
- [x] First pass, confirm which URLs work or not
- [x] Second pass, using Prod.cms.va.gov try and confirm what may be wrong with URL and test
*document results
- [x] For URLs that cannot be resolved, no more that 10 minutes should be spent on any one URL issue before it is simply documented for PM to troubleshoot at a higher level.

## Acceptance Criteria
- [x] All URLS have been tested and confirmed working or not
- [x] URLS that do not work have been troubleshooted and if not able to resolve in 10 minutes, documented and passed back to PM to resolve or remove.
