### ISSUE TITLE
Update historic rates section on current rates pages with new linking style

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11656]
## Issue Description
The content team has now standardized the way historic rates should be listed at the bottom of our current rates pages. Previously, the wording could be confusing because rates for a given year are often effective starting toward the end of the previous year. Other times rates are payable only after the year we are showing the rates for. If we are not explicit, the user could be confused as to what year of rates they need to look up.

The new standardized language:

[2019 rates](https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/historic-rates-2019/) (effective December 1, 2018)

Note that only the year's rates are linked and the parenthetical information is not.

For the [2020 special benefit allowance rates](https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/) we need to update the link language to the following:

[2019 rates](https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/historic-rates-2019/) (effective October 1, 2018, for automobile allowance; effective December 1, 2018, for clothing allowance and medal of honor pension)

## Tasks
- [x] Update 2020 benefit allowance rates pages with this new link language as shown above Node ID: preview-prod.vfs.va.gov/preview?nodeId=990 (Selina)
- [x] Update other 2020 Disability rates pages with correct language and by removing the parenthetical information from the links-[compensation rates](https://www.va.gov/disability/compensation-rates/veteran-rates/), [special monthly compensation rates](https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/), [birth defect rates](https://www.va.gov/disability/compensation-rates/birth-defect-rates/), [Parent DIC rates](https://www.va.gov/disability/parent-dic-rates/), [Survivor DIC rates](https://www.va.gov/disability/survivor-dic-rates/) 
- [x] Review work completed (Randi)
- [x] Publish pages (Randi)

## Acceptance Criteria
- [x] Live rates pages show correct links language for historic rates
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht these pages have been updated and are ready for review.

**Comment by RLHecht** [comment]
I reviewed these pages and all looks good. I am holding off on publishing most of them for now because i'm waiting on the CMS team to see if there's a way to fix the way the table headers break where we've added "(in U.S. $). FYSA @MickinSahni @bethpottsVADEPO

**Comment by RLHecht** [comment]
All these pages except the DIC Parents and Survivor DIC rates have been published. @bethpottsVADEPO

**Comment by RLHecht** [comment]
2020 Parents and Survivor DIC rates pages have been published. Moving to validate. FYSA @MickinSahni @bethpottsVADEPO

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing ticket. FYSA @MickinSahni
