### ISSUE TITLE
Project Kickoff COVID-19 Vaccine Trials Content and Tooling

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#11666]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Patrick Bateman**
- DEPO Product Lead (required): **Patrick Bateman**
- Entire VFS team (recommended): **Martha Wilkes, Stephen Barrs, Danielle Thierry, Mike Chelen, Ryan Thurlwell, Kaeli Yuen, Glen Holcomb**

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** 
YES

## Scheduling
- Ideally, tomorrow, Tuesday, July 28th @ 11am ET. But that is less than two biz days away. So if that doesn't work, then...
- Wednesday, July 29th @ 11:30am ET. Still less than two business days, but pretty darn close.

**Comment by mandifrances** [comment]
Hi @batemapf My spot for tomorrow (Wednesday) is already booked. It got booked last week. Should show that in the calendar link. That being said, I've got Thursday or Friday at 2pm ET. Will either of those times work for you?

**Comment by mandifrances** [comment]
Meeting scheduled for Thursday @ 2pm ET.

**Comment by batemapf** [comment]
I've got various pieces of writing about this work. This one is the most pertinent (I think) for this meeting: 
https://github.com/department-of-veterans-affairs/digital-experience-products/issues/207

In addition, please see this more robust narrative Slack Post: https://dsva.slack.com/files/T03FECE8V/F016QJL7KC6?origin_team=T03FECE8V

This work has been evolving very quickly, so both of those resources will be mildly dated. They should still give you a sense of the problem space.

**Comment by batemapf** [comment]
Planning on conducting usability research next week. Artifacts for that:

Convo guide (approval pending): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/covid-vaccine-trials/research/conversation-guide-study-1.md

Research plan (approval pending): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/covid-vaccine-trials/research/research-plan.md

**Comment by batemapf** [comment]
Prototypes of "registration" form are below. Some future iteration of these will be likely tested next week (as opposed to something on staging)

Mobile single page: https://preview.uxpin.com/5521dc071a06a238c2efffd575d5d79a3694f2fa#/pages/131029738

Desktop single page: https://preview.uxpin.com/5521dc071a06a238c2efffd575d5d79a3694f2fa#/pages/131072483

Mobile multi-page: https://preview.uxpin.com/5521dc071a06a238c2efffd575d5d79a3694f2fa#/pages/131117660
