### ISSUE TITLE
[Backend] Investigate how to get Chief Complaint into CPRS as discrete data or PDF

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11664]
## Issue Description
EPIC - (2B) As a Veteran, I want to only provide updates to my health information that is affecting me now, changed since last time, or due for screening, so that I save time documenting my information and my care team can focus on the changes to my treatment plan and whats important to me.

---
## Tasks
- [x] Research how to get a data element (text blob) into CPRS as patient entered data
- [x] Research both unauthenticated forms and authenticated so we know what fields we need to have if we want to put the blob on the patients chart to be seen by their care team
- [x] Research how we could instead put a PDF in CPRS as patient generated and both unauth and auth
- [x] Determine if CPRS is the correct place for PGD to live and if not then investigate other places where teams have stored PGD data to be viewable by clinical care teams. (In any format: discrete, pdf, or clinical notes)  

## Acceptance Criteria
- [ ] Document research in Tech Feasibility document
- [ ] Have a good understanding of complexity and tech architecture to pass via an interface into a source system for clinicians to view our questionnaire

---
#### Current findings

[Putting Chief Complaint into CPRS/VistA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vista-chief-complaint.md)

---
