### ISSUE TITLE
[PM] Rebuild and publish all updates for VISN-4 systems ready for Stakeholder review

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11667]
## Story
As a PAO and web maintainer I need access to the most recent build of my site, so I can review all pages and updates and provide feedback.

## TASK
- [x] rebuild all sites in DevShop
* Publish the following systems
- [ ] Altoona
- [ ] Butler
- [ ] Coatesville
- [ ] Erie
- [ ] Lebanon
- [ ] Philadelphia
- [ ] Wilkes-Barre
- [ ] Wilmington

## Acceptance Criteria
- [x] All sites have been rebuilt
- [ ] All sites have been published and tested (Access)
