### ISSUE TITLE
MVP of Deployment process for the new infra. 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11668]
## Description
_We need to come up with a MVP for how we are going to handle deploys in the new ifra. There are a few ways we can do this using far gate/ ECS and we want to have a prototype to see how things will run._

## Background/context/resources
Terraform module repo: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-fargate-service
Loki Repo: https://github.com/department-of-veterans-affairs/vsp-infra-loki

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Create a protype of how we want the deployments to look like._

## Definition of Done
- [ ] _Create Protype_
- [ ] _Test Protype_
- [ ] _share Protype with team and interate_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by ffafara-tw** [comment]
VANotify team has a working deployment pipeline to ECS Fargate (using github actions).
You can take a look at our code:
https://github.com/department-of-veterans-affairs/vanotify-infra
https://github.com/department-of-veterans-affairs/notification-api

I am also happy to jump on a call and discuss our CI/CD.
