### ISSUE TITLE
Change date style in 2018 and 2019 special benefit allowance rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11665]
## Issue Description
We need to update the way we give the effective date information on our historical rates pages for special benefit allowances to match what we have on the 2020 rates page. We also need to correct what the effective dates are. On our current page we give an effective date in the chart:
 ![Screen Shot 2020-07-27 at 1.27.04 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b6852477-fed9-4f18-8f30-0ce478781321)

On our historic pages, we give an effective date range: ![Screen Shot 2020-07-27 at 1.27.50 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4934297d-b26b-4511-b8c7-63db1ff1073f)

All pages should be consistent with only an effective date (this is also consistent with what is on other rates pages). The effective dates should be October 1 and December 1 (not October 10 and December 12 as currently written).

2018 rates page: preview-prod.vfs.va.gov/preview?nodeId=6190
2019 rates page: preview-prod.vfs.va.gov/preview?nodeId=5035

---
## Tasks
- [x] Update the 2018 and 2019 special benefit allowance rates pages in Drupal to give just an effective date in the far right column of the table. The heading for the column also needs to be updated to "Effective date." (Selina)
- [x] Change the effective dates to October 1 and December 1 (Selina)
- [x] Review work and read over page (Randi)
- [x] Publish pages (Randi)

## Acceptance Criteria
- [x] Live pages are showing only an effective date instead of an effective date range
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. Links are in description

**Comment by RLHecht** [comment]
@lunascoop these look good, thanks! FYSA @bethpottsVADEPO I am going to publish the 2019 one since it's already on the site just with the wrong language. I'll hold off of publishing the 2018 one until we publish all the 2018 rates pages together.

**Comment by bethpottsVADEPO** [comment]
Sounds good, thank you.

**Comment by RLHecht** [comment]
These pages have both been published. Moving to validate. FYSA @MickinSahni

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni
