### ISSUE TITLE
Design intent Collaboration COVID-19 Vaccine Trials Content and Tooling

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#11672]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [ ] VSP <> **requesting team** design intent collaboration meeting completed
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Sketches
- Lo-fi mockups

## Meeting attendees from **requesting team**
- Designer(s) (required): **Martha Wilkes, Ryan Thurlwell**
- Product Manager (optional): **Patrick Bateman**
- DEPO design lead (required as applicable): **Martha Wilkes**
- Accessibility: **Jennifer Strickland**

## Scheduling
- Requesting Tue, August 4, 11am – 12pm. Will submit artifacts by COB on Friday, 7/31.

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled August 4, 11-11:30 AM EST 

Thanks!

**Comment by CrystabelReiter** [comment]
Morning @batemapf just checking in if there are any design artifacts we can attach to the ticket?

**Comment by batemapf** [comment]
👋 morning! going to stick with the artifacts we used at our kickoff on thursday:

Prototypes of "registration" form are below. The "single page" variant is what we're current building using VA.gov forms system/library. That work might be on staging or a review instance in time for the meeting tomorrow. If so, will share a link.

Mobile single page: https://preview.uxpin.com/5521dc071a06a238c2efffd575d5d79a3694f2fa#/pages/131029738

Desktop single page: https://preview.uxpin.com/5521dc071a06a238c2efffd575d5d79a3694f2fa#/pages/131072483

Mobile multi-page: https://preview.uxpin.com/5521dc071a06a238c2efffd575d5d79a3694f2fa#/pages/131117660

cc @artsymartha68 anything else to add?

**Comment by artsymartha68** [comment]
Nothing else to add, I will tweak these prototypes based on updated questions from @DanielleThierryUSDSVA but as @batemapf says we'd like to use the real code for user research sessions next week.

**Comment by mnorthuis** [comment]
@batemapf is there also a landing page and/or faq page that will be part of the study?

**Comment by artsymartha68** [comment]
We're not sure if we'll include the landing page in the study, but here is the draft thanks to @DanielleThierryUSDSVA 
http://preview-prod.vfs.va.gov/preview?nodeId=6785
