### ISSUE TITLE
Update related link info for fraud information on two Pension pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11679]
## Issue Description
Per stakeholder Angie Smith, we need to change the related link on two of our Pension pages so they direct to the FTC and not the CFPB. It is the last related link on the [main Pension](https://www.va.gov/pension/) page and the [Survivors Pension](https://www.va.gov/pension/survivors-pension/) page:
![Screen Shot 2020-07-27 at 2.20.57 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/157cbd23-2c6e-43ae-9cfc-eb75e9562ef6)

**New link:** https://www.ftccomplaintassistant.gov/?utm_source=takeaction#crnt&panel1-1
**New teaser text:** 

**Drupal pages to work in:**
preview-prod.vfs.va.gov/preview?nodeId=73
preview-prod.vfs.va.gov/preview?nodeId=590
 
## Tasks
- [x] Write new teaser text (Beth)
- [x] Update link and teaser text on main Pension and Survivors Pension pages 
- [x] Review work (Randi)
- [x] Publish pages (Randi)

## Acceptance Criteria
- [x] New FTC link is appearing on live pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Hi @RLHecht here's the teaser. Please replace the "Federal consumer protection tips on avoiding fraud" link and teaser with this:

**FTC complaint assistant for reporting fraud** 
LINKS TO: https://www.ftccomplaintassistant.gov/?utm_source=takeaction#crnt&panel1-1

TEASER: If you’ve been the victim of fraud, you can file a complaint with the Federal Trade Commission (FTC).

**Comment by RLHecht** [comment]
These changes have been made and pages set to publish. Moving to validate. FYSA @MickinSahni

**Comment by RLHecht** [comment]
These changes are live on site. Closing ticket!
