### ISSUE TITLE
Update 2020 DIC Parents rates page with new table and historic links styling

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#11685]
## Issue Description
We need to be consistent across our pages on how we style our content. In the 2020 Parents DIC rates tables, we need to update the info in the table headers to show that all rates are in U.S.$. We need to remove the line above each table that says: All yearly income limits and beginning monthly rates are in $ U.S. dollars

We also need to update the styling for the historic links so the parenthetical information is not linkable.

The copy for the first column header should be: 
**Yearly income limit (in U.S. $) 
Your total income for the year must be less than or equal to this amount**

The copy for the second column header should be: 
**Beginning monthly rate (in U.S. $)**

Drupal page to work in: preview-prod.vfs.va.gov/preview?nodeId=1013

## Tasks
- [x] Update headers for all charts on page (Randi)
- [x] Update language for historic links (Randi)
- [x] Review work (Beth)
- [x] Publish page (Randi/Beth)

## Acceptance Criteria
- [x] Updates are visible on live page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpottsVADEPO I did these updates on Friday but just created a ticket so we can track the work. Let me know if all looks good and we can publish the page. The Drupal preview is listed above.

**Comment by bethpottsVADEPO** [comment]
@RLHecht This looks great! Thank you, and go ahead and publish.

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close later this afternoon.

**Comment by RLHecht** [comment]
Page looks good on live site. Closing ticket. FYSA @MickinSahni
