### ISSUE TITLE
Usability Testing Prep: CT Search & Filters

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#11707]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to product outline
  - [Search Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/search-enhancements_product-outline.md)
  - [Filter Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/filter-enhancements_product-outline.md)
- Link to or attach prototype or mockups
  - [Prototype](https://bahdigital.invisionapp.com/share/QNIAEHO8BH2)
  - [CT on Staging](https://staging.va.gov/gi-bill-comparison-tool)
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/research/search-filter-research-plan.md) and [discussion guide / script]()  
- [Link to starter regression test plan & starter test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/574)  

## Meeting attendees from **Booz Allen**
- Product Manager (required): **Darrell Neel**, Neel_Darrell@bah.com
- DEPO product lead (required): **Matt Self**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Amy Knox (Knox_Amy@bah.com), Cindy Cruz (Cruz_Cindy@bah.com), Jen Jones (Jones_Jennifer2@bah.com), Desiree Turner (Turner_Desiree@bah.com), Dan Shawkey (Shawkey_Daniel@bah.com), Adam Sonntag (Sonntag_Adam@bah.com), Michael Delli-Gatti (Delli-Gatti_Michael@bah.com)**

## Scheduling
Preferred time: Tues., Aug. 4, 11:30 am. 
Backup: Wed., Aug. 5, 11:30 am

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by mandifrances** [comment]
Scheduled for Tuesday, Aug 4th @ 11:30am ET

**Comment by peggygannon** [comment]
@amyknox here is VSP content feedback for CT Search and Filters. 


*Should* please format these in sentence-case per VA.gov style: 

--Historically Black colleges and universities (HBCU)
--Christian churches and churches of Christ

Question:
Under "Religious affiliation" label the dropdown only shows ALL as an option and doesn't give a list of  options for religion. Is this the desired behavior?  I would like to see the full list if there is one.

**Comment by ccruzgra** [comment]
@peggygannon You may need to refresh the page to see all of the options for religious affiliation. That fixed it on our end!

**Comment by CrystabelReiter** [comment]
No feedback from the VSP design side!

The tags look great. Good luck on testing! looking forward to hearing how it goes.

**Comment by pjhill** [comment]
VSP QA Feedback:
Great job having a test plan in place and executed to verify the prototype in staging! Since you are ahead of the game, you may want to consider using an [exploratory test charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/manual-testing/exploratory-charter.md) to uncover some of the defects that may be hidden in edge cases.

**Comment by mnorthuis** [comment]
**IA feedback:**

Consider:
- Gathering feedback on the labels of the filters and user's understanding of what the filter means prior to utilizing - i.e. What do they expect to see under "housing allowance" and "military details", as well as "institution type" vs "institution categories"
- Gather insights on whether automatically applying filters impacts the UX - Does the response times for applying filters impact users when they try to apply more than 1 filter? Do users expect to click "apply" after making selections?
