### ISSUE TITLE
[Analytics] Transform all health service and facility health service playbooks for listed systems in VISN-19 into .csv file in prep for automated load [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11714]
## Story
As a Drupal engineer, I need the palybook/health service data to be provided in an approapriate .csv file, so I can load the data into Drupal prod.cms.va.gov via the Pull Request and migration script.

## Resources
[See example .csv files provided by BE]

## TASKS
* Complete migration steps to transform data from playbooks into correct .csv file format to include the following sites:
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care
* For each of the following selections:
- [ ] System health Services list
- [ ] Facility level service list

## Acceptance criteria
* Each system has a listing for:
- [ ] System level health service list 
- [ ] Facility level service list
