### ISSUE TITLE
Flipper false when true

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11710]
## Issue Description
"Community care providers" disappears from the "Choose a VA facility type" drop down intermittently which we believe is related to the timing of node request for flipper status. 

Front end companion issue  [#10698](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10698)

---
## Tasks
- [ ] Discover why flipper acts false when it is true.

## Acceptance Criteria
- [ ] Test case to present to VSP as evidence of larger issue

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Script is running but we haven't observed any occurrence. Flipper logic is changed so the risk to Veterans is mitigated.
