### ISSUE TITLE
[Engineer] Create new Devshop/DEMO systems for VISN-19 [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11726]
## Story
As a web maintainer/Stakeholder, I need access to Devshop so I can review and provide feedback to the VAMC team. 

## TASK
* create the following Devshop systems:
- [x]  VA Cheyenne health care
- [x]  VA Eastern Colorado health care
- [ ]  VA Western Colorado health care
- [ ]  VA Montana health care
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care

## Acceptance
* the following sites are complete in Devshop:
- [ ]  VA Cheyenne health care
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado health care
- [ ]  VA Montana health care
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care
