### ISSUE TITLE
[Automation] Migrate all "Facility" Health Services for Systems listed into CMS [BE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11732]
##  Story
As a back-end engineer, I must utilize automation and migration scripts to load health service data, so I can accelerate velocity of data loading of critical and repetitive data.

## Resources
[Playbook files transformed into .csv files](https://drive.google.com/drive/folders/1MrWq9CTZqBPIXtfrmAJwvE81WMiAPPFN)

## Tasks
* using playbook .csv files, compile and migrate the following System health services by these systems:
- [ ]  VA Cheyenne health care
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado health care
- [ ]  VA Montana health care
- [ ] Cross check that System health services are loaded correctly in prod.cms.va.gov

## Acceptance Criteria
* Health services are loaded in prod.cms.va.gov in each of the following sites:
- [ ]  VA Cheyenne health care
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado health care
- [ ]  VA Montana health care
* Cross check and confirm Health Services match .csv folders and playbook files
