### ISSUE TITLE
[Development] Relax restriction in 526 schema

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#11731]
## Description

The `bankRoutingNumber` account number may include `*` in the save-in-progress data, and will eventually resubmitted back to the API unchanged (if the user does nothing).

The current JSON schema only accepts a 9-digit number per this regular expression (`^\\d{9}$`). This value should be relaxed so as to not cause validation errors after submission.

## Tasks

- [ ] Relax regular expression restriction of only accepting a 9-digit number
- [ ] Ensure all current tests still pass in both the vets-json-schema & vets-website repos.

## Acceptance Criteria

- [ ] Reduce 526 submission error rates
