### ISSUE TITLE
[DATA-LOAD] Load all DAV-VAN transportation data information Part 2 - VISN-19 [BA]Content]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11739]
## Story
As a Veteran, I need to have access to transportation information, so I can find the best route/travel access to my VAMC health location

## Resources
[DAV-VAN and transportation data](https://drive.google.com/drive/folders/1wcdnbjXHbJZepvT2iTpsmnYiXAcHzBYA)

## TASK
* Using the cloned page update the page information with the local DAV-VAN, VTS, and shuttle information provided in DAV-VTS information spread sheet for the following systems:
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care
* The following page will be complete for each section:
- [x] DAV-VAN, VTS, Shuttle, and Other information are loaded for the appropriate system. 
- [x] Must have contact and phone information for regional DAV, Shuttle, and/or transportation

## Acceptance criteria
* DAV-VAN page is updated with correct System information for the following sites:
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma City health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care
