### ISSUE TITLE
[Content]  Review copy edit and content for VA Salt Lake City content pages prior to publishing [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11737]
## Story
As a Veteran, I need content written in plain language that clearly defines the page and content of the page, so I can quickly determine how best to use the page for my benefit

## Resources
[VISN-19 Final Content pages](https://drive.google.com/drive/folders/1KVjgw4Z56Zm3m1TVTDktpKk9aKVpP9ms)
[Production pages](prod.cms.va.gov)
[Page review document](https://drive.google.com/drive/folders/1tKNuiKjRUVV2trwjKvN16RHW1HJAFfGw)

## TASK
Quick review of the pages via devshop or production previews and determine if the content reads correctly, follows style and content guidelines and provide feedback on word document for review.  For the following pages only:
- [x] Home intro
- [x] About us
- [x] Work with us
- [x] Jobs and Careers
- [x] Internship and Fellowship
- [x] Volunteer and Donate
- [x] Chaplain 
- [x] Policies page

## Acceptance Criteria
* note any issues in structure
* Report any page issues or cluttered pages that will need to be fixed
* Report any immediate content issues for repair.
