### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Cheyenne VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11742]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Resources
[VISN-19 Playbook](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Coatesville VA has a total of 61 Facility health services**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
VA Cheyenne health care

- [x]  Cheyenne VA Medical Center
- [x]  Fort Collins VA Clinic
- [x]  Loveland VA Clinic
- [x]  Rawlins VA Clinic
- [x]  Sidney VA Clinic
- [x]  Sterling VA Clinic
- [x]  Torrington VA Mobile Clinic
- [x]  Wheatland VA Mobile Clinic
- [x]  Laramie Mobile Telehealth Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.

**Comment by ltrombley** [comment]
Task #11742 - Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Cheyenne VA Health care system facilities is Complete and moved to Validate.
