### ISSUE TITLE
[REVIEW] Internal Review, test, and clean-up of all pages for "VA Montana"  [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11747]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VA Montana Review list](https://drive.google.com/drive/folders/1Fi1J24nQ0o_85DW_JkA-ZkYs0tEWr_mL)
[Drupal Production](prod.cms.va.gov)

## Tasks
_Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] Anaconda VA Clinic
- [x] Benjamin Charles Steele VA Clinic
- [x] Bozeman VA Clinic
- [x] Cut Bank VA Clinic
- [x] David J. Thatcher VA Clinic
- [x] Fort Harrison VA Medical Center
- [x] Glasgow VA Clinic
- [x] Glendive VA Clinic
- [x] Great Falls VA Clinic
- [x] Hamilton VA Clinic
- [x] Kalispell VA Clinic
- [x] Lewistown VA Clinic
- [x] Merril Lundman VA Outpatient Clinic
- [x] Miles City VA Medical Center
- [x] Plentywood VA Clinic

- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
