### ISSUE TITLE
[Clean-up] Prepare "VA Salt Lake City" for Stakeholder review  [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11758]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Using review document, clean up all areas in prod (Not already fixed)

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Tasks
_Complete all fixes in Review document prepare document for Stakeholders
- [ ] Update a copy of review document
- [ ] Rebuild Devshop instance
- [ ] Publish web pages
- [ ] Send e-mail communication to Stakeholders to begin review

## Acceptance Criteria
* All updates are implemented or documented on review document
* Website has been rebuilt and is published in Devshop and can be reached.
