### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for VA Montana Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11756]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Resources
[VISN-19 Playbook](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.

**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**

VA Montana health care 
- [x] Anaconda VA Clinic
- [x] Benjamin Charles Steele VA Clinic
- [x] Bozeman VA Clinic
- [x] Cut Bank VA Clinic
- [x] David J. Thatcher VA Clinic
- [x] Fort Harrison VA Medical Center
- [x] Glasgow VA Clinic
- [x] Glendive VA Clinic
- [x] Great Falls VA Clinic
- [x] Hamilton VA Clinic
- [x] Kalispell VA Clinic
- [x] Lewistown VA Clinic
- [x] Merril Lundman VA Outpatient Clinic
- [x] Miles City VA Medical Center
- [x] Plentywood VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.
