### ISSUE TITLE
[REVIEW] Internal Review, test, and clean-up of all pages for "VA Sheridan" [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11750]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VA Sheridan Review list](https://drive.google.com/drive/folders/1Fi1J24nQ0o_85DW_JkA-ZkYs0tEWr_mL)
[Drupal Production](prod.cms.va.gov)

## Tasks
_Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] Afton VA Clinic
- [x] Casper VA Clinic
- [x] Cody VA Clinic
- [x] Evanston VA Clinic
- [x] Gillette VA Clinic
- [x] Riverton VA Clinic
- [x] Rock Springs VA Clinic
- [x] Sheridan VA Medical Center
- [x] Worland VA Clinic

- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
