### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for VA Sheridan Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11759]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Resources
[VISN-19 Playbook](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Coatesville VA has a total of 61 Facility health services**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
VA Sheridan health care

- [x] Afton VA Clinic
- [x] Casper VA Clinic
- [x] Cody VA Clinic
- [x] Evanston VA Clinic
- [x] Gillette VA Clinic
- [x] Riverton VA Clinic
- [x] Rock Springs VA Clinic
- [x] Sheridan VA Medical Center
- [x] Worland VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.

**Comment by ltrombley** [comment]
Task #11759 - Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for VA Sheridan Health care system facilities is complete and moved to Validate.
