### ISSUE TITLE
Life Insurance Batch 1: Staging Review Accessibility Checklist

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#11768]
Content-only accessibility review of four pages:

- [x] preview-prod.vfs.va.gov/preview?nodeId=5590

- [x] preview-prod.vfs.va.gov/preview?nodeId=5581

- [x] preview-prod.vfs.va.gov/preview?nodeId=5582

- [x] preview-prod.vfs.va.gov/preview?nodeId=5678

## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [x] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - (Manual axe scan):Conduct axe browser scan, and document or address issues found
  - [x] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [x] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
  - [x] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [x] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [x] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- [x] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [x] **Attach to Collab Cycle Epic**
- [x] **Labeled with Team**

**Comment by MickinSahni** [comment]
cc @RLHecht

**Comment by MickinSahni** [comment]
hey laura, placing a 5 on this as it's the first one you and randi will be doing. feel free to update

**Comment by lwalsh617** [comment]
@MickinSahni @DanielleThierryUSDSVA -- The staging review accessibility check is complete. Before I close this ticket, is there a next collaboration-cycle step that needs a new ticket--or is this now ready for SME review? Thanks
FYSA @bethpottsVADEPO @RLHecht

**Comment by MickinSahni** [comment]
Spinning up a separate batch 2 and 3 internal accessibility checklist ticket - @lwalsh617

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 @MickinSahni I'm going to create a ticket for myself to review the final batch 1 pages since there were pretty extensive revisions and then corresponding edits entered into drupal. I'm doing this for two reasons: 1/ When there have been extensive edits made into the files, there's more room for error, and 2/ We're trying to move toward Danielle stepping away from VBA work and transitioning it to me, but she has stayed involved in this work since she started this rewriting effort way back when and is really knowledgeable about it and invested. Sooooo, this pass on my part is a way for me to familiarize with this content and add another layer of quality QA. JFYI.
