### ISSUE TITLE
AE-Sprint 27

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11772]
# Priorities
1. Complete Reviews (Staging, Call Center, QA, 508)
2. Finish leftover tickets
3. Design/Dev tickets that come out of QA
4. Direct Deposit (integration discovery and emails issue)
5. LIH discovery tickets (design/dev)
6. Update documentation
7. Cassandra's onboarding

### PM
Determine comms plan for profile 2.0, CC review, Staging review
- [x] [PM] Determine communications plan for Profile 2.0
- [x] [PM] Create call center video #11246
- [ ] [PM] Complete Contact Center Review #11573

### Design
Finish updating documentation, finish any remaining tickets, anything that comes out of QA
- [x] Pre-launch - Update relevant parts of the product outline/project folder #10806

### Build
Finish build items, update documentation, tickets that come out of QA
- [x] Add integration tests to Profile 2.0 #9563
- [x] [FE] - Update Profile 2.0 Documentation #11243
- [x] Add integration tests to Connected Apps on Profile 2.0 #11683
- [x] [FE] Scroll management updates #11269
- [x] UI should scroll to alert when Address Validation screen appears #11552
- [x] Tell user they are blocked from accessing their Direct Deposit info #11606
- [x] Show generic message when a Profile-related endpoint fails #11602

## Platform
- [x] Complete QA
- [x] Complete Staging Review
- [ ] Complete Call Center Review
- [x] Complete Privacy Review

##### Cassandra
- [x] Onboard Cassandra #11348
- [x] [Design] Tressa to introduce Cassandra to the LIH project #11818
- [x] Review discovery findings #10121 (we can create new tickets for Cassandra)
- [x]  Review journey maps #10120 (we can create new tickets for Cassandra)
##### Tressa & Cassandra
- [ ]  Investigate how banners/alerts work on the logged out homepage and in the navigation #8836
- [x] My VA tools audit #10123

### Dev
- [x] Investigate showing upcoming appointments #10247
- [x] Investigate level of effort for showing overall disability rating #10249
- [x] Investigate level of effort for showing GI Bill benefits balance #10255

## Direct deposit
- [x] Figure out why it appears we are sending more direct deposit confirmation emails than there are direct deposit submissions #11528

## Unplanned/QA/508/Bug fixes
- [X] [Copy] Copy is confusing in 'Learn more about military base addresses' FAQ (P&C section) #11043
- [X] Scroll to alert in Direct Deposit #12011
- [X] [Bug] Profile 2.0: After saving direct deposit info, the page doesn't scroll back up to the top to show the newly saved info #12019
- [X] [FE] Update the visual design of the additional info components in the "connected apps" section #12045
- [X] [FE] In mobile account security, Terms and Conditions and Sign-in Email overlap #12018
- [X] [Design] Update the visual design of the additional info components in the "connected apps" section to match others in the Profile #12044
- [ ] [Bug] Profile 2.0: Weird alignment of Delete button in Phone number field on mobile #12014
- [x] [Bug] Profile 2.0: Extra white space in the mobile profile menu #12017
- [ ] Profile 2.0 - Direct Deposit - Fraud Note copy does not match design prototype #11489 (high priority)
- [x] [FE] Checked/unchecked U.S. Military base address bug #12021
- [x] [FE] FAQ dropdown spacing in Personal and Contact Information is cramped #12022
- [x] [IA] [FE] The link from the direct deposit page should take the user directly to the profile/direct-deposit #12032
- [x] Focus not managed correctly when Connected Apps section appears #12349
- [x] Profile mobile sub nav sits above main site nav #12346
- [x] Add tests for "work in progress" modals #11984

**Comment by Samara-Strauss** [comment]
Can we close this out?

**Comment by mshea0606** [comment]
@Samara-Strauss closed
