### ISSUE TITLE
[Design] Build out remaining debt detail pages

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11784]
## Issue Description
Build out remaining detail pages (5) for the usability test with unique content.

---
## Tasks
- [x] Create 5 versions of the detail pages
- [ ] "QA" the prototype to ensure that it's working as intended

## Acceptance Criteria
- [ ] Fully working usability prototype
