### ISSUE TITLE
Finalize UAT Session Research Plan and Conversation Guide for Dependency Claims

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11789]
## Goal
In order to get Perigean informed of what type of users we need, we need to complete and submit a research plan and conversation guide to Lauren Alexanderson.

## Tasks
- [x] Complete UAT specific Research Plan and Conversation Guide sans launch date

## Acceptance Criteria
- [x] A Research Plan and Conversation Guide are documented in GH
- [ ] A Research Plan and Conversation Guide are ready for submission

**Comment by sporeboy** [comment]
Initial draft of UAT plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/uat/686-uat-research-plan.md

**Comment by sporeboy** [comment]
I have a few questions about how we might help participants before and after UAT:

- Do we provide pre-test guidance regarding instructions or uploads?
- Will we drop them on the home page or provide a direct link?
- Will we need to have 'stand-by plans" for catastrophic failure?
- Can we give assurances or follow-up paths?
- Will we shepherd the application through and connect with the LOB?
- Will we offer support for failed submissions?
- Who would run point on problems generated by the form process?

Etcetera...

**Comment by sporeboy** [comment]
Convo guide revised... Link: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/uat/686-uat-convo-guide.md

**Comment by sporeboy** [comment]
Shawna has link to RP and CG. Just need stakeholder feedback regarding questions above. Otherwise, these are ready for review.

**Comment by sporeboy** [comment]
Recruiting criteria changed per guidance from design/research leads. Plan and guide are complete pending review by leads, and guidance from LOB.
