### ISSUE TITLE
QA environment to test Form Detail Pages 

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11787]
## Issue Description
Given we want to conduct UAT for Form Detail Pages
I want a separate environment to test in
so that we can links, CTAs, etc. on form detail pages are accurate.

---
## Tasks
- [x] Create a QA environment of the CMS 
- [x] Share urls for the nodes
- [x] Account for an invalid PDF scenario - Update: This use case will be accounted for outside of the QA demo with Nick's recording of the error message use case[ per ticket #12181](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12181)

## Acceptance Criteria
- We are able to conduct UAT of form detail pages with links available to other nodes as well as publicly available urls

**Comment by MickinSahni** [comment]
Blocked until Jen gives the 👍 that we can take a snapshot of the CMS and create the new env for QA

**Comment by jenniferlee-dsva** [comment]
I've validated the top forms, so they are ready for QA environment. @swirtSJW @MickinSahni

**Comment by MickinSahni** [comment]
Thanks, Jen. Removed the `blocker` label. @swirtSJW

**Comment by MickinSahni** [comment]
@swirtSJW checking in on when this can be created

**Comment by MickinSahni** [comment]
Closing out as QA env is available cc @swirtSJW @jenniferlee-dsva
