### ISSUE TITLE
[Design] DL - Usability testing 

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11785]
## Issue Description
Conduct usability testing on the UXPin prototype with 8-10 users. 

- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/conversation-guide.md)

---
## Tasks
- [x] Complete usability testing with 8-10 users
- [x] Upload scrubbed transcripts to GH

## Acceptance Criteria
- [x] Testing completed
- [x] Transcripts uploaded to GH and linked in the comments

**Comment by leahkeeler** [comment]
usability study extended due to no shows - moving to sprint 28

**Comment by rebeccawalsh** [comment]
Notes uploaded here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/July%20usability%20notes.xlsx
