### ISSUE TITLE
[Design] Conduct pt 2 & 3 diary code workshops w/ DMC

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#11788]
## Issue Description
Conduct diary code workshops w/ DMC

---
## Tasks
- [x] Conduct p2 - Thursday, Jul 30
- [x] Conduct p3 - Friday, Jul 31
- [ ] ~Consolidate decisions made and upload to GH~
- [ ] Make a ticket for the final parts of the workshop

## Acceptance Criteria
- [x] Workshops conducted
- [ ] ~Decisions documented in GH~
- [ ] Ticket made and linked in this ticket

**Comment by rebeccawalsh** [comment]
Because we were not able to complete the exercise in these meetings, no documentation has been done. Instead, look at the[ Miro board progress here](https://miro.com/app/board/o9J_koiaiGk=/).

We will be holding the final (2) parts of the workshop once Dawn returns on the week of the 10th.

**Comment by rebeccawalsh** [comment]
Ticket for final workshops can be found here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11979
