### ISSUE TITLE
Conduct Content Review with Peggy (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11793]
## Goal
We want to ensure that every piece of content we put in front of a Veteran is at the highest standard, so we need to get Peggy to take a look and verify what we have in place or provide suggestions.

## Tasks
- [x] Provide Peggy with a link to the latest staging, prototype or mockup
- [x] Request a review of the content

## Acceptance Criteria
- [x] Feedback has been requested

### Next steps
- Implement changes before or after launch as needed.

**Comment by sporeboy** [comment]
Requested review and provided link to content: https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/130194084/comment/sitemap
