### ISSUE TITLE
Set up BigQuery to Domo Connector

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11799]
## Issue Description
Connect BigQuery to Domo so that we have a framework to work on for switching Google Analytics datasets to BigQuery and to start connecting other non-GA datasets from BigQuery to Domo.

---
## Tasks
- [x] Set up BigQuery with Domo
- [x] Research documentation
- [ ] Narrow down process for switching datasets

## Acceptance Criteria
- [x] VSP Analytics & Insights _can_ set up datasets from BigQuery to Domo and understands the initial work that will make those dataset connections happen

**Comment by jonwehausen** [comment]
### Update 8.3.2020

- DOMO<>BigQuery connection has been tested with our live production dataset [here](https://va-gov.domo.com/datasources/6fca6029-6e53-4a81-90f4-501cb65a41f9/details/overview). This is an example of what we will want to configure each time we execute a query and for the process of cutting over charts to use BQ. 
- Documentation has been updated [here ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/bigquery-sql-templates.md) to reflect some of the sample queries we know we will often use, we can continue to expand on this document over time as use cases evolve.
