### ISSUE TITLE
Conduct Content Review with Peggy (View Payments)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11794]
## Goal
We want to ensure that every piece of content we put in front of a Veteran is at the highest standard, so we need to get Peggy to take a look and verify what we have in place or provide suggestions.

## Tasks
- [x] Provide Peggy with a link to the latest staging, prototype or mockup
- [x] Request a review of the content

## Acceptance Criteria
- [x] Feedback has been requested

### Next steps
- Implement changes before or after launch as needed.

**Comment by sporeboy** [comment]
Gave Peggy our timeline and links to the screens. Can't log into staging today, so I provided the URL to the prototype: https://preview.uxpin.com/546893e0b210374a0734240e0ca9fccc2e02ed11#/pages/129039987

**Comment by peggygannon** [comment]
Hello! @sporeboy please see content recommendations for the View Payments tool. Please let me know if you have any questions. I have a few questions for you, so let me know if you want to discuss those on a call sometime next week. 

cc @jason-gcio 

------

Feedback key:
Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

---------

View payments tool staging review
Tool URL: https://www.va.gov/va-payment-history/payments

Breadcrumb:  Looks like mikki suggested "Payments" in her I/A review. I need to sync to confirm the breadcrumb. So H1 might change slightly depending on that sync. 

 
*Should*
- Suggest updating H1 TO: Your VA payments (to avoid repeating static page H1)

- Suggest updating intro TO: You can check the status of your VA disability, pension, and education payments. You can also find information about any payments you returned.

- Update content TO: We pay benefits on the first day of the month for the previous month. If the first day of the month is a weekend or holiday, we pay benefits on the last business day before the 1st.  For example, if May 1 is a Saturday, we’d pay benefits on Friday, April 30.

- Fix misspelling of Compensation

- Update content TO: 
**Note:** Some payment details might not be available online. For example, direct-deposit payments less than $1 or check payments less than $5, won’t show in your online payment history. Gross (before deductions) payments and changes will show only for recurring and irregular compensation payments. 
If you have questions about payments made by VA, please call the VA Help Desk at 800-827-1000

- *Question*, what is the correct place to send users for questions? This above number is for VBA benefits assistance, not the help desk. 

- *Question* : What does "Payments returned" mean? does this refer to when a user got a double payment?

- Update this content TO: 
**What if I find a check that I reported missing?**
If you reported a check missing and found it later, you must return the original check to the U.S. Department of the Treasury and wait to receive your replacement check.  If you endorse both the original and replacement check, you'll get a double payment. If this happens, VA Debt Management Center will contact you about collection.  

*Should*
Please update this content to the below to align with content best practices: 

- Users will already be signed in, correct? If so, please see content update below:  
UPDATE: 
**What if I need to change my direct deposit or contact information?**
Go to your profile to make updates to your contact and direct deposition information. Any changes you make in your profile will update across your disability compensation, pension, claims and appeal, VR&E, and VA health care benefits.  
Update link TO: [Go to your profile]

-UPDATE
**What if I’m missing a payment?**
Please wait 3 business days (Monday-Friday) before contacting us to report that you haven’t received a payment. We can’t trace payments before that time.  

To report a missing payment, contact us at 800-827-1000 (make this a link). Please have the following information ready for the call: your address, Social Security number or VA claim number, and your bank account information, if you receive payments through direct deposit. 

- **What if I have questions?**
You can call us at 800-827-1000(link). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by jason-gcio** [comment]
@peggygannon - thank you!
