### ISSUE TITLE
Conduct Content Review with Peggy (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11792]
## Goal
We want to ensure that every piece of content we put in front of a Veteran is at the highest standard, so we need to get Peggy to take a look and verify what we have in place or provide suggestions.

## Tasks
- [ ] Provide Peggy with a link to the latest staging, prototype or mockup
- [x] Request a review of the content

## Acceptance Criteria
- [x] Feedback has been requested

### Next steps
- Implement changes before or after launch as needed.

**Comment by sporeboy** [comment]
Gave Peggy our timeline and links to the screens.

**Comment by sporeboy** [comment]
Provided link: https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/130773489/comment/sitemap

**Comment by jason-gcio** [comment]
@sporeboy - Have the feedback changes been explicitly listed out in a changelog?  Sorry if I missed that

**Comment by sporeboy** [comment]
No changes yet... Just asked to get on her calendar.
