### ISSUE TITLE
Configure Error Status Code Sentry Logging for Debts

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#11791]
## Issue Description
HTTP error status codes need to be captured and logged via Sentry. Will need to write the logic to capture these events and log them appropriately.

---
## Tasks
- [x] Add error handling logic

## Acceptance Criteria
- [x] Errors will be appropriately logged.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
