### ISSUE TITLE
Adjust Dependency Claims with New Location Pattern

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11822]
## Goal
Now that the new location pattern is inplace on the frontend, we need to update the BE and how data gets moved around into the payload and the PDF.

## Considerations
- FE kept state the same: only now is a 2 digit code
- BE: Account for international locations (for example: marriage and others)
- Adjust for the upcoming data for going from 3 to 2
- Adjust PDF to display the right data

## Tasks
- [x] Adjust the BGS payload to account for the changes in number of letters
- [x] Verify the conversion is being properly executed
- [x] Adjust PDF to account for the new country field

## Acceptance Criteria
- [x] The 3 to 2 conversion is behaving as expected
- [x] The PDF reflects the change appropriately
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Does this PR need to be poked?

**Comment by kathleencrawford** [comment]
No, it has gotten eyes on it, but is going through a feedback/update loop.

**Comment by kathleencrawford** [comment]
This has been approved and merged.
