### ISSUE TITLE
Create Service in  `vets-api` for View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11828]
## Goal
With the new BGS gem method in place, we can properly create a service for `vets-api` to get payment data and use it.

## Tasks
- [x] Create a service that uses the new gem method to get payments
- [x] Add test(s) for the service

## Acceptance Criteria
- [x] A Service has been written that when tested behaves as expected
- [x] Unit tests are complete
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4630
