### ISSUE TITLE
Adjust Location UI to Have Country Dropdown Instead of Text Field

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11831]
## Goal 
When we built the new location UI we built it with a plain text field for the country in order to save time. The standard across VA.gov is to use a country drop down so we need to swap out the text field in the location UI for a country drop down.

## Tasks
- [x] Adjust generic location in vets-json-schema and build new schema
- [x] Adjust unit test in vets-json-schema
- [x] Submit and merge a PR for adjusted generic location in vets-json-schema
- [x] Bump version number in package.json in vets-json-schema
- [x] Adjust location UI in vets-website
- [x] Update commit hash from vets-json-schema in vets-website
- [x] Submit a PR for vets-website

## Acceptance Criteria
- [x] `vets-json-schema` has been updated so that the `genericLocation` schema uses a country drop down
- [x] The location UI has been updated so that it uses a country drop down
- [x] Backend has been notified of this completion

**Comment by jason-gcio** [comment]
@kathleencrawford & @digitaldrk - This has been completed and should be ready for you 🙏
