### ISSUE TITLE
Create a Controller for View Payment Data

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11830]
## Goal
A controller is needed in order to route information properly to and from the different points in the View Payments pipeline.

## Tasks
- [x] Write or create a controller (and action/method) that will better manipulate the endpoints as they need in order to retrieve and display data to and from the frontend.
- [x] Add swagger docs
- [x] Add tests

## Acceptance Criteria
- [x] A controller has been created
- [x] Swagger docs have been created and saved in `vets-api` 
- [x] Tests have been written
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/4798
