### ISSUE TITLE
[BE] Conduct regression testing on prescription refills widget on My VA dashboard in staging

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#11836]
## Background

On 7/28/20, we got the following email:

> From: "Bhamidipaty, Satish (By Light)" <Satish.Bhamidipaty@va.gov>
>  
> Mobile team and VA.gov team,
>  
> I wanted to let you know that there are changes in Rx Pharmacy backend services that will accommodate new VistA patch (additional) fields to be processed properly within MHV application. These changes should not have any impact to our API clients but would like to request Mobile and VA.gov SQA team to perform their functional tests in the lower SQA/Systest environment to ensure that these MHV changes did not break any current interfaces.
>  
> Praneeth (SQA) will send out an email once it is ready for SQA to perform tests.
>  
> Thanks
> Satish

I wrote back with some questions, and Satish asked us to do some regression tests on the prescription refill widget we have on the My VA dashboard in staging to make sure that their updates didn't break anything. The updates have not launched to prod yet, so we only need to test staging for now. We'll test in prod at the end of August when their updates launch to prod.
 
> Yes, the changes to MHV backend services are done and are in SQA/Systest environment. We are currently in SQA testing and bug fixes stage. MHV SQA team member (Praneeth) will notify you when it is ready for your team testing.
>  
> We would greatly appreciate if your team can do regression testing in the lower environment to ensure that our changes did not break the current interfaces.
>  
> Our changes are planned to go live into PROD on August 26th.

## Tasks

- [ ] Conduct regression tests on the prescription refill widget on My VA **in staging only**
- [ ] If there are issues, let Samara know so we can circle back with Satish
- [ ] If there are no issues, you can just close the ticket

**Comment by Samara-Strauss** [comment]
@lihanli we finally have a staging user for testing (cc/ @mshea0606 for awareness). The user is vets.gov.user+377@gmail.com with our standard staging password. 

However, when you log in to to staging and check My VA, you'll see secure messages but not prescriptions. When I emailed the people who helped us set up the staging user, they assured me that this user has active prescriptions, and sent this screenshot from MHV:

![Screen Shot 2020-08-11 at 5.02.35 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/e157bc38-e81f-4ca0-81b4-5c063f95c0ca)

You can also check this in MHV yourself if you log in with user Kristie ([info is in the last row of this table](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/reference_documents/MHV/mhv-lower-env-test-accounts.md)). She indeed should have prescriptions showing up on My VA.

So we know this user should have prescriptions showing up, but we are not seeing them, and I am wondering if this is an issue that's occurring as a result of the updates that Satish outlined (above) in his email. Can you conduct the regression testing and let me know if you find any problems? If not, can you look into why these prescriptions aren't showing up?

**Comment by lihanli** [comment]
@erikphansen @sanlouise  when i go to https://staging.va.gov/my-va/ with user vets.gov.user+377@gmail.com, i see that the `/v0/prescriptions/active` api is returning results but the frontend is still saying "You don’t have any prescriptions being refilled. If you’ve refilled a prescription within the last 30 days, it may be out for delivery and not showing up here." any idea why the results aren't appearing?

**Comment by erikphansen** [comment]
I'll have to look into it. Thanks @lihanli

**Comment by sanlouise** [comment]
@lihanli @Samara-Strauss @erikphansen I believe the issue is that we're filtering the prescriptions on the frontend by their status.

On line 103 of `src/applications/personalization/dashboard/containers/PrescriptionsWidget.jsx` we're filtering the existing prescriptions and are only interested in those prescriptions that have a `refillStatus` of `refillinprocess' or `submitted` whereas user 377 only has prescriptions with the status `active`, which is why they don't show up. 

```
prescriptions = prescriptions
      // Filter by status
      .filter(p => statuses.has(p.attributes.refillStatus))
      // Filter by date
      .filter(
        p =>
          moment(p.attributes.refillSubmitDate).isAfter(thirtyDaysAgo) ||
          moment(p.attributes.refillDate).isAfter(thirtyDaysAgo),
      );
```

**Comment by Samara-Strauss** [comment]
@sanlouise thank you for this! I will reach out to the team that manages this and have them update the statuses to `refillinprocess` and `refillStatus`.

**Comment by sanlouise** [comment]
To be clear, the `refillStatus` should be either `refillinprocess` or `submitted` 😄

**Comment by Samara-Strauss** [comment]
Ah, that makes much more sense — thanks for clarifying!

Also, the changes were made and it looks like everything is working now in staging.

<img width="671" alt="Screen Shot 2020-08-18 at 1 33 14 PM" src="https://user-images.githubusercontent.com/34068740/90545963-6d471200-e157-11ea-9a0f-c1bdada9445a.png">

**Comment by Samara-Strauss** [comment]
@lihanli is the regression testing done? If so, we can close this out.

**Comment by lihanli** [comment]
Yes, looks like it's working now
