### ISSUE TITLE
Usability Testing Prep Questionnaires MVP Priorities

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11838]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to product outline [Healthcare - Questionnaires](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md#healthcare-experience---questionnaires-product-outline)
- Link to or attach prototype or mockups
- Link to or attach artifact with copy [Visit Intro](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- Link to [research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/veteran-prioritization/research-plan.md) and [card sort](https://adhoc.optimalworkshop.com/optimalsort/j2b7m7j5/sort)
- Link to [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/veteran-prioritization/conversation-guide.md)

- ~~Link to regression test plan- N/A~~
- ~~Link to test cases/test plan in TestRail - N/A~~ 

## Meeting attendees from **requesting team**
- Product Manager (required): Amanda Buckley
- DEPO product lead (required): Lacey Higley
- Anyone else from your team who significantly contributed to the artifacts provided (required): Aricka Lewis and Shauna Hein

## Scheduling
- Wed 5th 10:30AM

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by abuckley3385** [comment]
@arickalewis1 when you get a chance please link above to the card sort and the mockups for the Collab Cycle Review.

**Comment by arickalewis1** [comment]
![1Veteran info 1](https://user-images.githubusercontent.com/54509359/89230840-bae54b80-d5a9-11ea-831e-53f797030ac2.png)
![2Veteran info 2](https://user-images.githubusercontent.com/54509359/89230846-bd47a580-d5a9-11ea-814d-5202ed71eeaf.png)
![3reason for visit](https://user-images.githubusercontent.com/54509359/89230850-be78d280-d5a9-11ea-93f7-b9b3b3de9110.png)
![4concerns](https://user-images.githubusercontent.com/54509359/89230853-bf116900-d5a9-11ea-8642-95993ca970f3.png)
![5questions](https://user-images.githubusercontent.com/54509359/89230854-bf116900-d5a9-11ea-835b-7c4f162db8b8.png)

**Comment by arickalewis1** [comment]
@abuckley3385 done!

**Comment by arickalewis1** [comment]
A note: the content shown is straight from the design library. I will do more edits post-review to fine-tune these pages.

**Comment by mandifrances** [comment]
Hi @abuckley3385 any chance you could go for the spot on the 6th at 1:30 or 2PM ET? We like to give 2 full days for reviews especially on busy weeks like this one?

**Comment by abuckley3385** [comment]
@mandifrances our PO @LEHigley is going on vacation after wednesday and I'd really like her to attend.  I was hoping since I submitted this early today and our meeting is mid day wednesday that could work for your team and the 2 day window.

**Comment by arickalewis1** [comment]
Attaching screens

![1Veteran info 1](https://user-images.githubusercontent.com/54509359/89235428-c2a9ed80-d5b3-11ea-8fc4-f088d0614f64.png)
![2Veteran info 2](https://user-images.githubusercontent.com/54509359/89235430-c3428400-d5b3-11ea-8b14-7987406c66ae.png)
![3reason for visit](https://user-images.githubusercontent.com/54509359/89235431-c3428400-d5b3-11ea-99f4-ab6ebe803f9d.png)
![4concerns](https://user-images.githubusercontent.com/54509359/89235432-c3428400-d5b3-11ea-9c74-cf856260113b.png)
![5questions](https://user-images.githubusercontent.com/54509359/89235434-c3db1a80-d5b3-11ea-9e35-c09f40cef1c5.png)
![6review](https://user-images.githubusercontent.com/54509359/89235435-c3db1a80-d5b3-11ea-9473-ffe00a8852e1.png)

**Comment by arickalewis1** [comment]
![1Veteran info 1](https://user-images.githubusercontent.com/54509359/89235616-246a5780-d5b4-11ea-82ad-49a33de17714.png)
![2Veteran info 2](https://user-images.githubusercontent.com/54509359/89235622-26341b00-d5b4-11ea-991e-572f000c144a.png)
![3reason for visit](https://user-images.githubusercontent.com/54509359/89235623-26ccb180-d5b4-11ea-9cd9-69a6ad1a0498.png)
![4concerns](https://user-images.githubusercontent.com/54509359/89235626-27654800-d5b4-11ea-9445-299f13693e0c.png)
![5questions](https://user-images.githubusercontent.com/54509359/89235628-27fdde80-d5b4-11ea-9b18-854a880205cb.png)
![6review](https://user-images.githubusercontent.com/54509359/89235629-27fdde80-d5b4-11ea-8ca7-1261a6da806f.png)

**Comment by mandifrances** [comment]
@abuckley3385 this has been scheduled for Thursday (6th) at 1:30pm ET

**Comment by peggygannon** [comment]
@abuckley3385 @arickalewis1 Hello! I have a couple of content-related questions about this project. Please let me know if you have any questions about my questions! thx

1. Do the screenshots above reflect the full WIP flow ? 

2. Do you have an editable Word or Github outline with the content? 

3. Will this questionnaire have a "confirmation" page that appears after the user hits the Submit button to confirm their completed application or questionnaire has been successfully submitted?

4. Will this questionnaire have an "introduction" page that gives users information about the questionnaire (how to fill it out, who will review it, what this information will be used for?)

**Comment by arickalewis1** [comment]
@peggygannon Hi! 

1. They do not represent the entire flow -- we will be adding intro and confirmation screens after the study. For context, we are not testing the prototype and will be getting feedback on static screens from Veterans regarding the content of the questions/labels.

2. Here's a [document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/design/proof-of-concept/content-v1.md) I created with my attempt at content.

3. Yes, there will be a confirmations screen

4. Yes, there will be an introduction screen

Thanks for the questions!

**Comment by arickalewis1** [comment]
Hi all, I've been working on these since uploading the version above. I'm attaching another iteration here: 
![Veteran info 1](https://user-images.githubusercontent.com/54509359/89467848-f7e14780-d73b-11ea-95d8-5257dd45e686.png)
![reason for visit - no additional](https://user-images.githubusercontent.com/54509359/89467856-fadc3800-d73b-11ea-9c6d-7eaef9eed76b.png)

![reason for visit](https://user-images.githubusercontent.com/54509359/89467875-ff085580-d73b-11ea-8b3a-768673a19fd5.png)

**Comment by mnorthuis** [comment]
No big IA feedback at this point since it is very early on.  I am very interested in learning how users expect this flow to happen and how/if VA.gov is part of that.  If possible, I would not lead with the idea that it may be on VA.gov, I would like to learn if they would even think of going there as part of this process or if they see it as something separate.

**Comment by abuckley3385** [comment]
@mnorthuis please see the Product Outline -[ Veteran Pain Points ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md#research-key-findings---pain-points)and [Unmet needs section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md#veteran) as the question of where do veterans expect this type of workflow to occur was already asked and answered in our discovery research . As discussed in the call please see our [Initiative - Visit Intro strategy document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)and Workflow diagram to better layout our modes for veterans accessing the forms.

**Comment by abuckley3385** [comment]
@tlei123 per your question in the feedback meetings "...can you add a label to better search for the Epics for our product."  Yes, I can add a label of product or mvp but also please see that our [Initiative - Visit Intro: Issue Tracking section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md#issue-tracking) has all Epics listed that will apply to this proof of concept so you shouldn't have to search for any Epics or features.  I am just now getting them all put in github so some are just outlined at this point.

**Comment by shiragoodman** [comment]
2nd usability testing prep: https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/16955
