### ISSUE TITLE
Add a URL to the Jenkins job in the SSL Cert Expiry scanner

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#11854]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
devops/auditor/certs/Jenkinsfile runs the SSL certificate scanner, but when the job runs and reports to Slack, there is no URL or indication where more information can be found. Add a URL to the output.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Add a URL to the slack report of the Cert Expiry scanner

## Definition of Done
- [ ] URL to jenkins job is included in Slack output

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
