### ISSUE TITLE
[PM] Update all documents and data points in VA/product/VAMC/Github REPO [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11864]
## Story
Documents need to be archived in the correct github REPO

## TASKS
- [ ] Product outline
- [ ] Updated data milestones
- [ ] Archive documents
- [ ] New Milestones
- [ ] New Goals, OKR, BETS

## Acceptance Criteria
- [ ] Product outline
- [ ] Updated data milestones
- [ ] Archive documents
- [ ] New Milestones
- [ ] New Goals, OKR, BETS
