### ISSUE TITLE
Update alert on schedule appointment page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#11878]
## Issue Description

This page (https://www.va.gov/health-care/schedule-view-va-appointments/) now lives in a react app as part of the Cerner SSO work.

We need to update the content in this alert across all react states on this page based on user and contact center feedback. 

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/ae9f1273-eb3d-4f9e-b5ca-a1d7fb475eef)

[header] Due to COVID-19, we'll need to contact you to confirm your appointment

[copy] You can still use our online appointments tool to request an appointment. We'll then contact you to confirm the date, time, and location.

---
## Tasks
- [ ] Update and publish content

## Acceptance Criteria
- [ ] Updated content is live on the site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic. Do you think you could possibly get to this in next few days? The contact center is getting some calls from people who are confused about this alert so we need to make some updates to the published content. Please let me know if you have any questions/concerns. Thank you!

**Comment by kelsonic** [comment]
Hey Danielle, so production is still showing the legacy content, if you're looking for the correct widget to show with the Cerner updates you'll have to check out https://staging.va.gov/cerner-staging/appointments/

**Comment by kelsonic** [comment]
If you want I can make it so that in production there is no legacy content shown for the https://www.va.gov/health-care/schedule-view-va-appointments/ page and instead it will be the new content we created when a user is unauthenticated.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @kelsonic. So for now, I need to update the legacy content that's showing in production. (We also need to update this widget across all states...but the need for right now is to update content in production).

Production can still show legacy content. I just need to update the content within the alert. How can we do that?

**Comment by kelsonic** [comment]
Oh got it! I can do that now 🙂

**Comment by DanielleThierryUSDSVA** [comment]
Yay! Thank you so much, @kelsonic. I really appreciate it!

**Comment by kelsonic** [comment]
Of course! 🎉

**Comment by kelsonic** [comment]
PR is up! @DanielleThierryUSDSVA Would you mind taking a glance at the files changed to see if the copy looks right? https://github.com/department-of-veterans-affairs/vets-website/pull/13673/files

**Comment by kelsonic** [comment]
PR is merged! Should be deployed for today's deployment 👍

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @kelsonic!! And apologies, was in a meeting taking notes and didn't see request to look at PR until now.

**Comment by kelsonic** [comment]
Oh no worries! It's just the exact content that's in the ticket description, so we should be good! 🎉

**Comment by MickinSahni** [comment]
@DanielleThierryUSDSVA flagging this for your validation!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @MickinSahni! Looks great in production. Closing ticket. Thank you again, @kelsonic!
