### ISSUE TITLE
Enter sample data for use in validating template front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11884]
## Issue Description
As part of the move to use the new content models to populate the facility health service information, we'll need sample data for validating the information renders as expected. 
 
---
## Tasks
- [ ] Enter sample data for University Drive for FE devs

## Acceptance Criteria
- [ ] Data is available for validation

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
