### ISSUE TITLE
Content freeze and migration

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11887]
## Issue Description
As part of the move to use the new content models to populate the facility health service information, we'll need to work with CMS to freeze content creation during migration.

## Tasks
- [ ] Coordinate with CMS to hide/unhide fields to prevent the entry of new data during the migration process

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@davidconlon I'm not sure there is any work required from the Facilities team on this. Can you confirm?
