### ISSUE TITLE
Unit Test Payments Component for View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11924]
## Background
On the View Payments page, each of the responsive tables is wrapped in a `<Payments />` component that is responsible for all of the logic for pagination. We have unit tested the responsive tables themselves but need to write unit tests for the pagination logic, this means writing unit tests for the `<Payments />` component. 

## Tasks
- [ ] Set up mock data in the test file for Payments component
- [ ] Write unit tests to 80% coverage
- [ ] Create a PR for the unit tests

## Acceptance criteria
- [ ] All of the pagination logic for the responsive tables is unit tested
- [ ] The `<Payments / >` component is unit tested to 80% coverage
- [ ] A PR has been submitted for review
