### ISSUE TITLE
Unit Test Payments Lists Component on View Payments page

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11925]
## Background
On the View Payments page the `<Payments />` components which house the pagination logic and the responsive tables are housed in a wrapper component that displays both `<Payments />` components as well as some text that is dynamically built. 

## Tasks
- [x] Set up mock data in test file for `<ViewPaymentsLists />`
- [x] Fully test the component
- [x] Submit a PR for review

## Acceptance criteria
- [x] The `<ViewPaymentsLists />` component isfully unit tested
- [x] A PR has been submitted for review
