### ISSUE TITLE
Unit Test App Component for View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11926]
## Background  
The View Payments page is rendered by the App component and while this component does not contain any logic **it needs to be unit tested to make sure it renders correctly**. Likewise, the Header component on the View Payments page does not contain any logic but **it needs to be unit tested to 80% coverage**.

## Tasks
- [ ] Set up test files
- [ ] Unit test both components to 80% coverage
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] Both the `<App />` component and the `<ViewPaymentsHeader />` components have been unit tested to 80% coverage
- [ ] A PR has been submitted for review
