### ISSUE TITLE
Proof of concept Wireframe

### ISSUE THREAD

**Issue by arickalewis1** [department-of-veterans-affairs/va.gov-team#11937]
## Tasks
- [x] Wireflow for questions/steps
- [x] Set up development handoff process

## Acceptance Criteria
- [x] Review design & content with product team
- [x] Proof of concept mockups uploaded to appropriate source of truth tool ([Zeplin](https://zpl.io/aNepDW9))

**Comment by abuckley3385** [comment]
@arickalewis1 Do you mind if I change the estimate on this ticket as 5 points means this will take you 5 days to complete the mockup...as a rough estimate. maybe a 1-3 given it is just the couple questions?

**Comment by arickalewis1** [comment]
@abuckley3385 this one is for after the research when we will need the process flushed out - I hadn't gotten around to adding acceptance criteria just yet. Thinking ahead!

**Comment by abuckley3385** [comment]
gotcha- i pulled it into this sprint thinking it was for the research I'll move it back out. Thanks for the clarification!! Honestly you had way too many points this sprint so I was concerned.

**Comment by abuckley3385** [comment]
This ticket will continue as we need a wireframe story board flow and a prototype. Reassigning to Kristen.

**Comment by kristenmcconnell** [comment]
@abuckley3385 I created a wireflow (instead of a storyboard), since we are farther along in the process. The draft can be viewed within our Zelpin file under a Webflow section: https://zpl.io/VOOek8j. Please review and let me know what you think. We can definitely meet after you have reviewed it. I have a few outstanding questions on it (within blue boxes). I will check with some design team members on implications of links within forms.

**Comment by kristenmcconnell** [comment]
Removing click through prototype from story, since another story has been created for that.

**Comment by kristenmcconnell** [comment]
Added in the final deliverable Zeplin link. 

Copy image of final deliverable.
![Q3 and Q4 Scope.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9d125fc9-e28f-4699-96d5-4ca773398d63)
