### ISSUE TITLE
Analyze card sort research findings

### ISSUE THREAD

**Issue by arickalewis1** [department-of-veterans-affairs/va.gov-team#11936]
## Tasks
- [x] Complete research study (wrap EOD Tuesday, August 11)
- [x] Create analysis spreadsheet 
- [x] Create [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/veteran-prioritization/research-findings.md) document

## Acceptance Criteria
- [x] Complete research findings document
- [x] Actionable recommendations for work prioritization

**Comment by abuckley3385** [comment]
@arickalewis1 Is there a way to get this card sort to our clinical stakeholders at LomaLinda and Hawaii without having to do an in-person session?  @LEHigley

**Comment by arickalewis1** [comment]
I will make a separate link that we can send them so we have a a way to discern the data @abuckley3385. They can do it remotely in their own time.

**Comment by abuckley3385** [comment]
@arickalewis1 I do not see the link updated in the findings for the mockups/cardsort that was shown in the study (the link is not correct) Once you add that we can mark this as complete. 

I haven't see the doc/link come across for how to review the card sort with our stakeholders per our comments above on Aug 5th and in [slack thread. ](https://dsva.slack.com/archives/C0136TS768M/p1597425836285500) fyi @LEHigley

**Comment by arickalewis1** [comment]
I just updated the links so they should be working now -- 

With the stakeholder sort, we didn't resolve how we could send the link unmoderated and get the results you were looking to obtain. I can add it to the ramp up document for the next designer to create a research plan tailored to the stakeholder study -- seems like moderated sessions would be the only way to replicate what we did with Veterans.
