### ISSUE TITLE
Staging Review Debt Letters MVP 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11930]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/new%20product_outline.md) 
- Link to [[release plan]](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/Debt_Letters_Release.md)
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
[STAGING LINK](https://staging.va.gov/manage-va-debt/your-debt/) - Please use Greg Anderson (user 1)
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more]
**Please Note** Debt Letters is one page, listing out the Veteran's debt and a table with links to Debt Letters. Because a Veteran needs to log in to see this, the only way to test is moderated release with live veterans. @tlei123 will be sitting in on a few sessions as part of QA process 

- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_

**Required:**

- [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
- [x] Conduct axe browser scan, and document or address issues found 
- [x] Ensure end-to-end tests - including the axe check, pass 
- [x] Check color pairing for proper contrast 
- [x] Check for colorblindness issues 
- [x] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
- [x] Repeat for 300% 
- [x] Repeat for 400% 
- [x] Navigate all pages and core functionality with keyboard only 
- [x] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox 
    
**Recommended:**

- [ ] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) 
- [ ] Add keyboard end-to-end tests in CI/CD test runs 
- [ ] Conduct axe-coconut browser scan, document or address issues found 
- [ ] Test with [WAVE tool](https://wave.webaim.org/) 

- List of known issues (with links to tickets when applicable)

## Meeting attendees from **requesting team**
- Product Manager (required): **Leah K @leahkeeler **
- DEPO product lead (required): **Matt Self @mattpointzxer0 **
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Brad C @bradl3yC, Cameron @camerontesterman  **

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by mandifrances** [comment]
@leahkeeler What day are you hoping to do this meeting? There is nothing in the schedule section.

**Comment by leahkeeler** [comment]
@mandifrances - any time that works for y'll is fine with us - we try to be easy.

**Comment by mandifrances** [comment]
@leahkeeler this has been scheduled for Thursday at 2pm ET.

**Comment by tlei123** [comment]
@jenstrickland , CMS preview of DL langing-page: http://preview-prod.vfs.va.gov/preview?nodeId=6521

**Comment by jenstrickland** [comment]
> Please Note Debt Letters is one page, listing out the Veteran's debt and a table with links to Debt Letters. Because a Veteran needs to log in to see this, the only way to test is moderated release with live veterans. @tlei123 will be sitting in on a few sessions as part of QA process

Normally, accessibility would also review any variations of the screen (such as error states). Since this isn't possible, would you prefer I sit in on a few sessions as Tze is? @leahkeeler

**Comment by leahkeeler** [comment]
Hi Jen - that would be great! I will add you to invites, there are plenty to chose from
