### ISSUE TITLE
[Design] Debt Letters - Conduct usability test synthesis

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11947]
## Issue Description
_Synthesize data gathered from Debt Letters usability test_

---
## Tasks
- [x] _Synthesize data gathered from Debt Letters usability test_
- [x] _Create a research readout document_
- [x] _Upload research readout to GH_
- [x] _(Optional / If applicable) Create a short deck for demoing research readout_

## Acceptance Criteria
- [x] _Research readout is uploaded to GH and linked in this ticket_

**Comment by rebeccawalsh** [comment]
- [Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/usability-readout.md)
- [Presentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/Debt%20Letters%20Usability%20Test.pptx)
