### ISSUE TITLE
IA feedback - Staging review - Profile 2.0

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#11968]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback for Profile 2.0 implementation in Staging

**MUST**
- Once signed in, the link from the [direct deposit page](https://staging.va.gov/change-direct-deposit/) should take the user directly to the profile/direct-deposit. 

**SHOULD**
- There is a link to /sign-in-faqs on the account security and connected apps pages, but the links are labeled very differently and sort of seem to refer to very broad "va.gov faqs".  I recommend working with Peggy on this to label these faqs consistently, potentially link to an anchor on the page for specific faqs, and ensure they they are represented as faqs specific to authentication and not just general faqs. 

**CONSIDER**
- Once signed in, the link from the [change address page[(https://staging.va.gov/change-address/) should link directly to the personal information page, not just the top level /profile page.  Currently this is not required since the /profile page is essentially a pass-through to the /personal-information page, but as profile evolves, the landing page may evolve and be a separate page.   

## Definition of Done
- [ ] Feedback is reviewed and acknowledged by team 
- [ ] Decisions and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

## Tickets
- [x] [FE] The link from the direct deposit page should take the user directly to the profile/direct-deposit #12032
- [ ] [FE] - Update FAQ link labeling #12035 #12037
- [ ] [FE] Update "change address" link to go directly to personal information section of the profile #12100

**Comment by mshea0606** [comment]
@mshea0606 divide into three tickets

**Comment by erikphansen** [comment]
Regarding the `MUST` item above, we could change the link right now if we wanted to. Due to how client-side routing works, a link to `https://www.va.gov/profile/direct-deposit` would just render the old Profile, even right now. But when Profile 2.0 is on prod, that same link would correctly load the Direct Deposit page.

**Comment by mshea0606** [comment]
[FE] The link from the direct deposit page should take the user directly to the profile/direct-deposit #12032

**Comment by mshea0606** [comment]
[FE] - Update FAQ link labeling #12035 #12037

**Comment by tressaellen** [comment]
Regarding the 'should' section - Peggy has covered this in her content recommendations tracked in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11972).
