### ISSUE TITLE
Remove HAProxy exporter container

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#11977]
## Description

[This issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11271) and [associated PR](https://github.com/department-of-veterans-affairs/devops/pull/7341) upgraded HAProxy and added a Prometheus exporter. 

The extra exporter container can now be removed.

## Tasks
- [x] Remove configuration for haproxy exporter container in [ansible/build/roles/fwdproxy/tasks/main.yml](

## Definition of Done
- [x] haproxy exporter no longer deployed

---

### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
