### ISSUE TITLE
Name field for Community care providers (PPMS)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11987]
## Issue Description
When a Veteran searches for a Community care provider (in VA's network), he/she needs the basic information to be returned as search results. All relevant fields for these providers must be included in the API. 

---
## Tasks
- [ ] Add name field from PPMS 

## Acceptance Criteria
- [ ] All relevant fields are included in API response
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
