### ISSUE TITLE
[Frontend] Debt Letters MVP - COVID debt suspension alert

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11989]
## Issue Description
Our team recently learned that all [VA debt collection is suspended through the end of 2020 due to the COVID-19 pandemic](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/no-panels?mode=i). An alert has been added to the tool's UI informing the user about this debt suspension. 

**Note:** The content in these empty states may be updated [pending Peggy's feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11935).

---
## Tasks
- [ ] _Update the Debt Letters MVP UI to include the alert in the provided mockups_
- [ ] _Review the updated UI with a designer_

## Acceptance Criteria
- [ ] _The UI has been updated to include the provided alert_
- [ ] _The UI has been approved by a designer_
