### ISSUE TITLE
[Frontend] Debt Letters MVP - Updated Empty States

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11986]
## Issue Description
With the updated MVP including both debt summary and a list of downloadable letters on the same screen, we need to create additional empty states. I've provided UXPin prototypes for the following empty state use cases:
- [If a veteran accesses the tool and they've never had a debt](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130748284/simulate/no-panels?mode=i); i.e. no debts or debt letters on their record
- [If a veteran accesses the tool and they don't have any _current_ debts but they have resolved debts](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174953/simulate/no-panels?mode=i); i.e. no debts but letters from past debts are available to download
- [If a veteran received a debt after March 2020 they will have current debts but no letters to download](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174235/simulate/no-panels?mode=i)

**Note:** The content in these empty states may be updated [pending Peggy's feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11902). 

---
## Tasks
- [ ] _Update the UI with the provided empty states_
- [ ] _Review updated UI with a designer_

## Acceptance Criteria
- [ ] _Empty states have been updated to match the provided designs_
- [ ] _UI has been approved by a designer_

**Comment by rileyorr** [comment]
Update on Peggy's feedback: the first two empty states have been reviewed and updated, but I'm still waiting on content feedback for the third empty state
