### ISSUE TITLE
Assist BE tools via Terraform to get a Redis for sidekick 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11980]
## Description
Sidekick needs a new Redis as part of its migration. BE tools started this work, but now needs ops help in Terraform to see it through. 

Linked issue department-of-veterans-affairs/va.gov-team#8149

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 
Quite a while ago, @wyattwalter and I took a look and it seemed like the most likely name to stay with conventions was `vagov-prod-vets-api-sidekiq` but I don't think it really matters. Just passing on the note.

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Copy the production Elasticache Redis configuration in Terraform to support a second cluster
- [ ] Provide an independent configuration (size of cluster, number of nodes, type of instance, etc)

## Definition of Done
- [ ] A second Elasticache Redis cluster dedicated to Sidekiq is available in the production VPC

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by johnpaulashenfelter** [comment]
@ricetj i *think* we likely want one of these on staging too, but i don't see the need for it on dev or sandbox.

**Comment by ricetj** [comment]
this work is done.
