### ISSUE TITLE
Adjust table fields and right align classes to reflect actual data from BGS

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11998]
# Overview
When we built the View Payments page we set up the table using the columns from the mockup. The table columns are built from a `fields` object we pass to the table. Since we will need to adjust the table to show actual data coming from BGS we will need to adjust the fields object, and thus the columns, to reflect the actual data. 

We also set up the table so that numeric fields are right-aligned. The right alignment is done by specifying the index of the numeric fields inside the fields object. Since the data we are using will be adjusted to the actual data coming from BGS rather than mock data we set up for building the View Payments page we will need to adjust which columns are right-aligned.

## Tasks
- [ ] Slack or meet with back end to get the actual data structure that will be returned by the back end
- [ ] Collaborate with design to determine which columns of data we want to show from the real BGS data
- [ ] Adjust the `fields` object to reflect the fields we want to show from the actual BGS data
- [ ] Adjust the right alignment classes to target the correct columns from the actual BGS data
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The front end has been adjusted so that the tables on view payments reflect actual BGS data structure
- [ ] A PR has been submitted for review
