### ISSUE TITLE
Adjust data structure to reflect actual data from BGS

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11995]
# Overview
When we created the View Payments page we set up the mock data in Redux to be the most simple data structure possible to meet the needs of the page however this data structure does not reflect how the data will come from the back end. We need to work with the back end engineers to identify the actual data structure as it will come back from them and adjust this and the code that accesses the data on the front end.

## Tasks
- [ ] Slack or meet with back end to get actual data structure as it will come from the back end
- [ ] Collaborate with design to figure out which fields in the data structure we want to show in the tables
- [ ] Adjust the mock data in Redux in View payments
- [ ] Adjust Redux so that it accesses the correct data attributes
- [ ] Adjust unit tests for Redux accordingly

## Acceptance criteria
- [ ] The front end now uses the correct data structure for View Payments
- [ ] All unit tests pass
- [ ] A PR has been submitted for review
