### ISSUE TITLE
Unit Test View Payments Sidebar

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#11991]
Doing this ticket might be deprioritized in favor of more substantial tests

## Background
On the View Payments page, there is a simple sidebar that renders static content. In keeping with VA.gov standards, we need to unit test the sidebar to achieve our 80% coverage.

## Tasks
- [ ] Set up test file
- [ ] Unit test sidebar to 80% coverage
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The View Payments page sidebar has been unit tested to 80% coverage
- [ ] A PR has been submitted for review
