### ISSUE TITLE
Connect Redux to BE for View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12000]
# Overview
When we set up the View Payments page we built the Redux code so that it would be able to be connected to the API endpoint set up by back end. We need to connect Redux on View Payments to the endpoint that has been set up.

## Considerations
- [Swagger docs](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/profile/getPaymentHistory)
- One call but with two arrays

## Tasks
- [ ] Adjust Redux action so that it hits a real URL and returns the data
- [ ] Adjust Redux reducer so that it accesses the correct data
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] Data for View Payments is now being pulled from the back end instead of a static file in the front end
- [ ] A PR has been submitted for review
