### ISSUE TITLE
Wrap View Dependents and Form 686c-674 in Downtime Notification for BGS

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#12005]
## Description
It's common practice for applications relying on external systems to be wrapped in `<DowntimeNotification />` to alert users when they may experience incoming down time or service outage. View Dependents and Form 686c-674 need to be wrapped in this component so users are alerted to upcoming service outage.

## Considerations
- BGS needs to be added to [this config file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/DowntimeNotification/config/externalServices.js)
- devops repo already has an entry for BGS [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L385), not sure if anything else needs to happen to make it usable other than adding it to the file mentioned in point one

## Tasks
- [ ] Add BGS to downtime notification config
- [ ] Wrap view dependents in <DowntimeNotification />
- [ ] Wrap Form 686c-674 in <DowntimeNotification />

**Comment by jason-gcio** [comment]
Preferably done before launch, but should be simple to do
