### ISSUE TITLE
e2e Testing for View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12003]
# Overview
In order to make sure that the View Payments page functions as it should we need to write end to end tests the full user journey.

## Tasks
- [ ] Set up test file
- [ ] Write e2e test for user login, pagination, and server data
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The main user path for View Payments has been e2e tested
- [ ] A PR has been submitted for review
