### ISSUE TITLE
Wrap View Payments in RequiredLogin Component

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12008]
# Overview
In order to make building View Payments as simple as possible, we skipped requiring a login to view the page. We need the `<RequiredLogin />` component added so that a login is required to view the page.

## Tasks
- [ ] Ensure the user profile data is accessed from Redux in mapStateToProps
- [ ] Import and configure `<RequiredLogin />` component
- [ ] Submit a PR for review

## Acceptance Criteria
- [ ] A login is needed to view the View Payments page
- [ ] A PR has been submitted for review
