### ISSUE TITLE
Internal Accessibility Audit for View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12001]
# Overview
To get out ahead of the 508 accessibility audit on the [Form Name] form we need to conduct our own internal accessibility audit to attempt to find as much as we can and address it. 

## Tasks
- [x] open the page in Axe Coconut and list out any issues to be addressed
- [x] Review the [accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/accessibility/508-checklist-wip.md) and list out any issues to be addressed 
- [x] Create tickets for any issues to be addressed

## Acceptance criteria
- [x] An internal accessibility audit has been completed for View Payment History
- [x] Any issues that need to be addressed have tickets created for them

## Acceptance criteria
- [x] Tickets have been created for accessibility items to be addressed on View Payments

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/508/Internal_accessibility_audit.md
