### ISSUE TITLE
Unit Test Veteran Information (pg 2) for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12028]
# Background
In order to make sure that the Veteran Information behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Veteran Information page.

## Tasks
- [ ] Set up test file
- [ ] Write unit tests for Veteran Contact Information page
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The Veteran Information page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
