### ISSUE TITLE
Unit test for Veteran Information on Chapter 31 VRE

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12026]
# Background
In order to make sure that the Veteran Information page behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Veteran Information page.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for Veteran Information page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Veteran Information page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
