### ISSUE TITLE
Add reverse fields to node-health_care_region_page

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#12020]
## Issue Description
The `node-health_care_region_page` GraphQL query uses a number of `reverseField*` sub-queries. These are added to "new" fields on the node. The transformer for this bundle needs to mimic this.

Additionally, other transformers will make use of the `reverseField*` fields to construct unique fields on their child `node-health_care_region_page`s, so these `reverseField*` fields will need to be made available. (Hopefully this doesn't lead to any circular reference loops we can't resolve. :grimacing: )

### Required fields
- `newsStoryTeasers` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L16))
- `allNewsStoryTeasers` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L16))
- `eventTeasers` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L17))
- `allEventTeasers` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L17))
- `reverseFieldRegionPageNode` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L73))
  - I think? Should verify that the result of this sub-query gets assigned to the `reverseFieldRegionPageNode` property)
- `allPressReleaseTeasers` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L81))
- `mainFacilities` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L104))
- `otherFacilities` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L104))
- `eventTeasersAll` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L120))
  - Should figure out if this is necessary or if we can use `allEventTeasers` :roll_eyes: 
  - There's another `reverseFieldListingNode` inside here ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L123))
- `eventTeasersFeatured` ([Source](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js))
  - There's another `reverseFieldListingNode` inside here ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L164))
- `newsStoryTeasersFeatured` ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L202))
  - There's another `reverseFieldListingNode` inside here ([Source](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L205))

---
## Tasks
- [ ] Add the `reverse_field_*` fields to the `node-health_care_region_page` input schema
- [ ] Add the missing fields to the `node-health_care_region_page` transformer
- [ ] Add the missing fields to the `node-health_care_region_page` output schema
- [ ] Add the `reverseField*` fields to the transformer and output schema

**Comment by cvalarida** [comment]
**Note:** This is blocked until we get the `reverse_field_region_page` (or whatever it ends up being called) in the CMS export to re-create the `reverseFieldRegionPageNode` GraphQL sub-query.

**Comment by theodur** [comment]
This ticket is blocked at the moment as `reverse_field_region_page` is only present in some of the entities, and the ones it is present for are blank arrays.

**Comment by theodur** [comment]
Merged in https://github.com/department-of-veterans-affairs/vets-website/pull/13915.
