### ISSUE TITLE
Add New Questions to CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12025]
# Background
Since building the initial fields of the chapter 31 form there have been some fields added through design reviews. We need to add the **3 new communication preferences** to the form page as shown below in the prototype.

## Consideration
- [Mockup](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/131223448/simulate/sitemap)
- Design's [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11452)

## Tasks
- [ ] Update UI schema in `vets-website` for chapter 31
- [ ] Submit PR in `vets-website`

## Acceptance criteria
- [ ] The front end now reflects the added questions for the chapter 31 form
- [ ] A PR has been submitted for review in `vets-website`

-----------------------
**(In another ticket)**
- [ ] Add new fields to `vets-json-schema` for chapter 31
- [ ] Bump the version number for chapter 31 in `vets-json-schema`
- [ ] Submit a PR in `vets-json-schema`

- [ ] Update `vets-api` bundle
- [ ] Submit PR in `vets-api`
