### ISSUE TITLE
Meet with Analytics Team to Get Event Prefix and Any Custom Event Names for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12036]
## Goal
In order to track the success metrics for the Chapter 31 form we need to get Google Analytics events set up that speak to those metrics. So that the analytics team has a chance to establish those event names and what they are for we need to meet with them either in person or over Slack.

## Considerations
- Other than what comes baked into the Form System
- Mention the orientation content and the skip link
- Can we measure how far into the video progression before they drop off and just skip? Video "continue" buttons could be unique and show all the steps.  Like scrolling.  "How can we measure as much as possible to show the effectiveness of this content."

## Tasks
- [ ] Connect with the GA/Insights Team (over either Slack or Zoom) to share what function and features this product is involved with, and a recommendation for what events they might be interested in tracking.
- [x] Document what events will be provided by the analytics team

## Acceptance Criteria
- [x] We have connected with the GA/Insights Team 
- [x] We have a document (ticket or otherwise) that has all of the GA events needed for Chapter 31

### Next steps
-  [x] Code provided by the GA/Insights Team has been inserted into our feature

**Comment by micahchiang** [comment]
Dropping this here so we have it for future reference, whenever we add events to chapter 31 wizard - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md
