### ISSUE TITLE
Unit Test Communication Preferences for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12034]
# Background
In order to make sure that the Communication Preferences page on Chapter 31 behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Communication Preferences page.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for Communication Preferences page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Communication Preferences page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
