### ISSUE TITLE
Location Error in non-US Country Selection

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12038]
## Background
When a user selects the checkbox for outside the US, and then selects a country from the dropdown, their location is stripped out from the payload after submission.

## Considerations
More information about this issue is currently developing (see comments)
- Workflows affected: add spouse, add child, report death, report divorce.
- Does not affect locations within the US (checkbox is not selected, state dropdown is used). 

## Tasks
- [ ] Locate the error 
- [ ] Ensure the country selection is passed into the payload and stays there
- [ ] Checkbox label and country dropdown are not mapped correctly when used inside a list loop. (ONLY in marriage history loops)
<details><summary>Example</summary>

<img width="610" alt="Screen Shot 2020-08-04 at 4 21 29 PM" src="https://user-images.githubusercontent.com/15097156/89342331-a455f780-d670-11ea-9c73-e32f7c8fe0cc.png">
</details>

## Acceptance Criteria
- [ ] The error has been identified
- [ ] The payload is made whole on submission
- [ ] A PR with a resolution has been submitted for merging

**Comment by micahchiang** [comment]
We have a custom transformForSubmit that uses a platform-provided `stringifyFormReplacer` function, which is stripping out the country field as it prepares our payload for its journey to vets-api. A quick fix may be to change the property name in location from `country` to `countryName` (used in addressSchema) or something else, such as `countryCode`.

**Comment by micahchiang** [comment]
PR here - https://github.com/department-of-veterans-affairs/vets-website/pull/13722
