### ISSUE TITLE
Implement GA Event Names for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12039]
## Goal
Now that we have met with the Google Analytics Team on the Chapter 31 form and they have shared what the event names are going to be for it, we need to insert them into the code.

## Tasks
- [ ] Insert event names into the code for Chapter 31
- [ ] Submit PR for review

## Acceptance Criteria
- [ ] Code/event names provided by the GA/Insights Team has been inserted into the Chapter 31 form for tracking
- [ ] A PR has been submitted for review
