### ISSUE TITLE
Unit Test Education Information on Chapter 31 Form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12031]
# Background
In order to make sure that the Education Information page behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Education Information page.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for Education Information page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Education Information page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
