### ISSUE TITLE
Unit Test Veteran Info for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12048]
# Background
In order to make sure that the Dependent Information page on Chapter 36 behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Applicant Information page.

## Tasks
- [x] Set up test file
- [x] write unit tests for Dependent Information page
- [x] submit a PR for review

## Acceptance criteria
- [x] The Dependent Information page is unit tested it 80% coverage
- [x] A PR has been submitted for review
