### ISSUE TITLE
Unit Test Schema for CH36 in vets-json-schema

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12047]
# Overview
When we set up the form fields for the Chapter 36we added a schema into `vets-json-schema`. All schemas in `vets-json-schema` need to be unit tested to ensure they accept the correct data as well as reject incorrect data. We need to add unit tests for our schema.

## Tasks
- [ ] Set up test file
- [ ] Write unit tests for Chapter 36 schema in `vets-json-schema`
- [ ] Submit a PR in `vets-json-schem` for review

## Acceptance criteria
- [ ] The schema for Chapter 36 in `vets-json-schema` has been unit tested to 80% coverage
- [ ] A PR has been submitted to `vets-json-schema` for review
