### ISSUE TITLE
First Pass to Build Out Fields for CH36 (Veterans)

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12046]
# Background
When we initially set up the chapter 36 form we did not build out all of the fields for the form. Now that we are farther along we need to add the fields for the form. 

## Considerations
- This is a first pass at building these fields and IF this form includes more complicated UI then we should break that into a separate ticket.
- This is just the form fields, wizard work is in another ticket
- [Prototype](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/130194084/simulate/sitemap)
- [Workflows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/ch36-user-flows.md)

## Tasks
- [x] Build out for fields for chapter 36 form in `vets-website` from **Veteran perspective** vs the Veteran's dependent perspective
- [x] Submit PR to `vets-website` for review

## Acceptance criteria
- [x] All form fields in the latest mockup have been added to the chapter 36 form
- [x] A PR has been submitted to `vets-website` for review
