### ISSUE TITLE
Internal Accessibility Audit for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12040]
# Overview
To get out ahead of the 508 accessibility audit on CH31 we need to conduct our own internal accessibility audit to attempt to find as much as we can and address it. 

## Tasks
- [ ] Open the page in Axe Coconut and list out any issues to be addressed
- [ ] Review the [accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/accessibility/508-checklist-wip.md) and list out any issues to be addressed 
- [ ] Create tickets for any issues to be addressed

## Acceptance criteria
- [ ] An internal accessibility audit has been completed for CH31
- [ ] Any issues that need to be addressed have tickets created for them

**Comment by micahchiang** [comment]
Findings document here - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/engineering/INTERNAL_508_CHECK.md
