### ISSUE TITLE
Unit Test Contact Information for CH36 (pg 1)

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12053]
# Background
In order to make sure that the Contact Information pages on the Chapter 36 behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Contact Information pages.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for Contact Information pages
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Contact Information pages are unit tested it 80% coverage
- [ ] A PR has been submitted for review

**Comment by jason-gcio** [comment]
dupe?
