### ISSUE TITLE
Internal Accessibility Audit for Chapter 36 form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12057]
# Overview
To get out ahead of the 508 accessibility audit on the Chapter 36 form we need to conduct our own internal accessibility audit to attempt to find as much as we can and address it. 

## Tasks
- [x] open the page in Axe Coconut and list out any issues to be addressed
- [x] Review the [accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/accessibility/508-checklist-wip.md) (and our [previous internal audit work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/508)) and list out any issues to be addressed 
- [x] Create tickets for any issues to be addressed

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/508/README.md

## Acceptance criteria
- [x] An internal accessibility audit has been completed for the Chapter 36 form
- [x] Any issues that need to be addressed have tickets created for them

**Comment by cohnjesse** [comment]
The only issue called out by Axe-coconut was the phone numbers listed on the site as the phone numbers in the aria tags for them do not match the text in the links. Jenn S and Trevor P are aware of this issue and are working with Axe to get their chrome extension updated.
