### ISSUE TITLE
Unit Test Additional Information for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12050]
# Background
In order to make sure that the Additional Information page on the Chapter 31 form behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Additional Information page.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for Additional Information page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Additional Information page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
