### ISSUE TITLE
Meet with Analytics team to get event prefix and any custom event names for the Chapter 36 form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12054]
## Goal
In order to track the success metrics for the Chapter 36 form we need to get Google Analytics events set up that speak to those metrics. So that the analytics team has a chance to establish those event names and what they are for we need to meet with them either in person or over Slack.

## Tasks
- [ ] Connect with the GA/Insights Team (over either Slack or Zoom) to share what function and features this product is involved with, and a recommendation for what events they might be interested in tracking.
- [ ] Document what events will be provided by the analytics team

## Acceptance Criteria
- [ ] We have connected with the GA/Insights Team 
- [ ] We have a document (ticket or otherwise) that has all of the GA events needed for the Chapter 36 form

### Next steps
- [ ] Code provided by the GA/Insights Team has been inserted into our feature
