### ISSUE TITLE
Unit Test Military History for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12051]
# Background
In order to make sure that the Military History page on Chapter 31 behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Military History page.

## Tasks
- [ ] Set up a test file
- [ ] write unit tests for Military History page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Military History page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
