### ISSUE TITLE
e2e Test Dependent Workflow

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12059]
# Overview
In order to make sure that workflow for a dependent filling out the CH36 form is fully e2e tested.

## Tasks
- [x] Set up test file
- [x] Write e2e test for the Chapter 36 form
- [x] Submit a PR for review

## Acceptance criteria
- [x] The main user path for the Chapter 36 form has been e2e tested
- [x] A PR has been submitted for review
