### ISSUE TITLE
E2E Testing for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12056]
## Overview
In order to make sure that the Chapter 31 form functions as it should we need to write end to end tests the full user journey.

## Considerations
- Auth and non-auth'd
- Use Cypress instead of Nightwatch

## Tasks
- [x] Set up test file
- [x] Write e2e test for the Chapter 31 form
- [x] Submit a PR for review

## Acceptance criteria
- [x] The main user path for the Chapter 31 form has been e2e tested
- [x] A PR has been submitted for review
