### ISSUE TITLE
Add GA Events for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12055]
## Goal
Now that we have met with the Google Analytics Team on the Chapter 36 form and they have shared what the event names are going to be for it, we need to insert them into the code.

## Tasks
- [ ] Insert event names into the code for the Chapter 36 form
- [ ] Submit PR for review

## Acceptance Criteria
- [ ] Code/event names provided by the GA/Insights Team has been inserted into the Chapter 36 form for tracking
- [ ] A PR has been submitted for review

**Comment by jason-gcio** [comment]
All events are fully comprised in the Form System, no need for this ticket
