### ISSUE TITLE
Synthesize Domo User Feedback

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12062]
## Issue Description
How might VFS PMs/POs receive cleaner, more useful Domo dashboards as we continue to create KPI dashboards for them?

Enable iterations of our dashboarding process through user research.

---
## Tasks
- [x] Write up overall summary of user research
- [x] Organize any themes that came up
- [x] Organize any 'went wells' and 'to improves'

## Acceptance Criteria
- [ ] VSP Analytics & Insights can understand what went well and what can be improved for Domo dashboards based off of user research
---
[Research issue](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/11479)

**Comment by amycesal** [comment]
Miro Board: https://miro.com/app/board/o9J_knKtwsw=/

![Screen Shot 2020-08-17 at 11.26.25 AM.png](https://images.zenhubusercontent.com/5b2ab6f42f27e82b33e6b789/4c8d06db-5b48-4664-925f-605f7b38505f)

PDF: 
[https://app.zenhub.com/files/133843125/a00becf1-2d7e-418f-9adf-3de6be415efe/download](https://app.zenhub.com/files/133843125/a00becf1-2d7e-418f-9adf-3de6be415efe/download)

**Comment by joanneesteban** [comment]
Synthesis for Domo research is above and was presented in Demo. Closing this ticket.
