### ISSUE TITLE
Integrate new search result card templates with back end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12064]
## Issue Description
Part of the urgent care mash-up
This issue for the integration of the new search result card styling and behavior with the ccp controller. 

---
## Tasks
- [ ] Integrate front and back end
- [ ] When VA facility type = Urgent care, the VA service type drop down includes
      - All urgent care
      - VA urgent care
      - Community urgent care providers (in VA's network)
- [ ] When VA facility type = Urgent care, the VA service type drop down defaults to "All urgent care"

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
merged
