### ISSUE TITLE
[POST 686 LAUNCH] Total Combined Disability Rating Messaging Updates

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12068]
## Background
Part of the eligibility for getting dependents awarded is having a 30% total combined disability rating; below that dependents cannot be attached to an award.

## Goal
With the 686 in place in production, one of the first things we need to is run a check of a Veterans disability rating and either allow them in or communicate that their rated disability rating was not high enough.

## Considerations
- ~~It might be a good time and place to merge this in with the VA File Number check and include messaging that accounts for the inadequate TCDR found and possibly some links to the Rated Disabilities app and the Claim Status Tool for more information.~~
- ~~This effort might enhance the future effort of converting Rated Disabilities to BGS from EVSS.~~
- The LoB may advise that if someone is in the process of getting a TCDR then they would like to have the Veterans 686 application so they can effectuate the claim as well.

## Tasks
- [ ] ~~Obtain the Veterans TCDR at login~~
- [ ] ~~Allow them to proceed or let them know what happened.~~
**OR**
- [ ] Check: does RBPS REJECT or can we set to manual?
- [ ] Draft some explanation language that informs the Veteran of what is possible based on their TCDR: "we noticed you don't have a disability rating"
- [ ] Determine a potential location the language

## Acceptance Criteria
- [ ] ~~The 686 is gated with the TCDR value~~
- [ ] ~~The Veteran is well informed of the outcome or simply allowed to enter the form.~~
- [ ] A few sentances are prepared to be shared with Steve to be shared with Paul Shute.

**Comment by sporeboy** [comment]
Initial draft and mock up is here: https://xd.adobe.com/view/057055ba-4c2b-4367-667b-7d7034cb43b4-7341/screen/2a28677f-8c31-48d7-a04b-5cf288069787
