### ISSUE TITLE
[DISCOVERY] Facility health services design

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12076]
## Issue Description
The content model for Facility health services location and contact information has been changed from a single blobby area to individual components. The area needs to be designed to incorporate these components, including a new layout for hours of operation.

---
## Tasks
- [ ] Become familiar with the layout of the VAMC pages, with focus on the Facility Health Services location and contact information section
- [ ] Review design system for relevant components
- [ ] Collaborate with Ryan on design
- [ ] Talk with Gibran, Michael and Ethan about data/components, particularly hours of operation

## Acceptance Criteria
- [ ] Preparation for design
- [ ] Understand any research needs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
