### ISSUE TITLE
Synthesize existing forms library research & prioritize roadmap

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#12074]
## User Story

As a VSP team member, I need to know what feedback customers have recently given us about the forms library, so that I can prioritize a future roadmap accordingly to best serve the needs of VFS teams. 

## Details 

VSP receives a lot of feedback about the forms library from VFS teams. The forms library is a big priority for the VSP FE Tools team to iterate on and improve. How might we harness existing customer feedback in order to help prioritize a future roadmap for forms library work? 

## Definition of Done 
- [X] Existing customer research/known pain points of forms library are synthesized
- [X] Opportunity areas identified 
- [ ] Opportunity areas prioritized
- [ ] Roadmap determined
- [ ] Roadmap shared with VSP leadership
- [ ] Roadmap shared with VFS customers

**Comment by meganhkelley** [comment]
Synthesis MURAL board https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1595033064125/ca9b639f28e977620e341af4df719b61a3c16f7b

**Comment by meganhkelley** [comment]
Prioritization voting spreadsheet: https://docs.google.com/spreadsheets/d/1XFsuMFjZ-yx0jK7u0ql739t-GhM1ai7GS6-mmdCeqBM/edit#gid=443295151

**Comment by meganhkelley** [comment]
This is on hold as we finish up some short term forms library tasks including review page refactor and accessibility bugs. Moving to `Ready` for now.
