### ISSUE TITLE
[POST 686 LAUNCH] Select Dependents Directly for Removal

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12070]
## Background
One of the functions that was contemplated early on was the ability to directly select the dependent for removal, as opposed to inserting all their information over again.

## Considerations
- It might be best to include this functionality on the View Dependents page with an easy to understand mechanic that allows for confirmation and submission to remove a dependent by selecting them.
- Is there a preferred way this is conveyed to the stakeholders? Or is taking the selection and picking up their data and creating a payload based on that ok.
- This may be converted into an epic for issues to be attached to

## Tasks
- [x] Research endpoints; this may require some prep (may be the same call for VD?)
  - FE: will need to figure out a way to fill data on button click / or simply submit on their behalf and avoid the form system
  - BE: this may require some prep (may be the same call for VD?)
- [x] Gather as a small group and discuss data throughput and strategize a best path forward
- [x] Identify the best place to place a selection mechanic for direct dependent removal

## Acceptance Criteria
- [x] A solution for a dependent to be directly selected for removal with limited effort by the Veteran has been established.
- [x] If needed, mockups are updated to reflect new state

**Comment by sporeboy** [comment]
Created new XD with ALT selection screens for remove dependent scenarios...

https://xd.adobe.com/view/8293c660-56c7-4230-b86a-fc235f7b3cf0-d7c0/

**Comment by jason-gcio** [comment]
See product decisions doc for this feature for more info
