### ISSUE TITLE
[Design] Write content for the detail page additional info components

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#12078]
## Issue Description
Write content for the 'Additional info' components that detail why someone could have each type of debt for: 
- 30 - Compensation & pension debt
- 41 - Chapter 34 education debt
- 44 - Chapter 35 education debt
- 71 - Post 9/11 GI Bill debt for books and supplies
- 72 - Post 9/11 GI Bill debt for housing
- 74 - Post 9/11 GI Bill debt for tuition
- 75 - Post 9/11 GI Bill debt for tuition (school liable)

---
## Tasks
- [x] Draft content for each deduction code
- [x] Confirm content required w/ DMC
- [ ] Send revised content drafts to Peggy for editing / approval
- [ ] Create ticket for FE

## Acceptance Criteria
- [ ] Content written and approved
- [ ] FE ticket created and linked in this ticket
