### ISSUE TITLE
Update disability pages with number of days it takes VA to make a decision in July

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12079]
## Issue Description
Stakeholder Sandy Tadeo updated two disability pages in Drupal with the number of days it takes VA to make a decision for the month of July. These need to be reviewed and published. The two pages are:

- [How to file a claim](https://www.va.gov/disability/how-to-file-claim/)
- [The VA claim process after you file an appeal](https://www.va.gov/disability/after-you-file-claim/)

New number of days: 124.8
Change month from April to July

---
## Tasks
- [x] Review pages in Drupal (Randi)
- [x] Publish pages (Randi)
- [x] Notify stakeholders when page will be live (Beth/Randi)

## Acceptance Criteria
- [x] Pages are live with July numbers.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These changes were already made. Creating ticket for tracking purposes. FYSA @MickinSahni

**Comment by RLHecht** [comment]
These changes are live on the site. Closing ticket. FYSA @MickinSahni
