### ISSUE TITLE
Staging Review: STEM Standalone Form 22-10203

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12084]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- [STEM 22-10203 Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/10203_product_outline.md)
- [STEM 22-10203 release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/10203_release_plan.md)
- Access information for the tool or feature in staging
   1. The new form can be accessed on staging at the following link: https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction
   2. The form requires authentication and any existing staging ID.me accounts can be utilized right now. 
   _We are waiting on new test accounts that have both entitlement data as well as enrollment data from EVSS to be able to test the entitlement feature on the introduction screen, chapter 3, and the summary screen._
- [Test Cases/Test Plan in TestRail with test execution logs](https://dsvavsp.testrail.io/index.php?/plans/view/495_
- [Coverage for References reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/125)
- Link to verification that accessibility checks are complete:
  -  [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/plans/view/495)
- List of known issues (with links to tickets when applicable)
  - STEM: Update breadcrumb of 10203 application #9755 (waiting on final content/IA)
  - STEM: Update Google Analytics for the 22-10203 #11706 (in progress)
  - STEM: Update SCO email content to reflect the final version recevied from EDU on 07/24 #11713 (in progress)
  - STEM: Send confirmation email to applicant #11809 (in progress)
- List of blocked issues (waiting on EVSS test account referenced above): 
  - STEM: Email SCO on form Submission #10790
  - STEM: Update 10203 Intro based on user testing updates#10958
  - STEM: Pre-fill 10203 chapter fields#10549
  - STEM: Add Entitlement Remaining alert to 10203 introduction page#10774
- [Defect Report](https://dsvavsp.testrail.io/index.php?/reports/view/126)

## Meeting attendees from **requesting team**
- Product Manager (required): Darrell Neel
- DEPO product lead (required): Matt Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): Amy Knox, Cindy Cruz, Jen Jones, Dan Shawkey, Desiree Turner, Will McCormack, Adam Sonntag, Michael Delli-Gatti

## Scheduling
**Preferred Time Slots** 
- Friday 08/07 anytime after 11AM
- Monday 08/10 (Free from 10AM-2PM or after 3PM)

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by mandifrances** [comment]
This has been scheduled for Monday, August 10th @ 3:30pm ET. @desireeturner

**Comment by desireeturner** [comment]
The usability issue that BAH brought up on the call that @emilywaggoner is going to follow up on with the front end tools team is #12185

**Comment by pjhill** [comment]
QA Feedback:

1. Several defects were discussed during the course of the staging review meeting, but I don't see any link between the test executions in TestRail and the creation of defects in GitHub. Your [Summary Defects](https://dsvavsp.testrail.io/index.php?/reports/view/126) report shows no defects. In the future, when you create a bug report please populate the defect field with the relevant GH issue for example -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/12185

1. It may be prudent to indicate the targeted testing environment in your TestRail test plans. If you did this, and I didn't see it somewhere then I apologize.

**Comment by desireeturner** [comment]
All feedback is now complete, so this can be closed.
