### ISSUE TITLE
Remove sentence from MGIB-SR page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12080]
## Issue Description
Per stakeholder Tammy Hurley we need to remove a sentence from the [MGIB-SR](https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/) education page because the 14-year delimiting date was rescinded.

We need to remove the sentence "If you stay in the Selected Reserve, you’ll be eligible for 14 years after you started your first 6-year obligation."

![Screen Shot 2020-08-05 at 10.24.10 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8b6b4af3-32a1-425a-8fa1-28021f1aa005)

---
## Tasks
- [x] Remove sentence from Drupal page. (Randi)
- [x] Publish page (Randi)
- [x] Alert stakeholder that page will be live (Beth/Randi)
 
## Acceptance Criteria
- [x] Page is live with change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
The work was done for this already. Creating ticket for tracking purposes. FYSA @MickinSahni

**Comment by RLHecht** [comment]
This is validated on live site. Closing ticket. FYSA @MickinSahni
