### ISSUE TITLE
[POST 686 Launch] Migrate 686 nightwatch e2e tests to Cypress

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#12083]
## Description
VSP recently announced that Cypress has been green lighted. While nightwatch tests will still continue to run for the time being, teams should migrate existing nightwatch tests to cypress in anticipation of nightwatch being completely retired. 

## Considerations
- Some teams are already using Cypress (BAM1 & 2). Should check to see what they've done as a reference. 
- Walk through 686c-674 for all existing e2e test workflows, copy json payload at the end of it. 
- Create Cypress e2e tests using test helper for each flow
- remove nightwatch tests. 

## Tasks
- [ ] Migrate all 686 nightwatch tests to cypress

## Definition of done
- [ ] All tests have been migrated to cypress and pass successfully. 
- [ ] PR into vets-website has been created and merged.
