### ISSUE TITLE
Attributes for community urgent care

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12085]
## Issue Description
As part of the urgent care mashup and migration of v1 to ccp controller, we need to ensure all necessary data is included in the query request/response

---
## Tasks
- [x] Provide attributes needed for community urgent care and lighthouse (VA) urgent care to Lance (BE)

## Acceptance Criteria

- [x] Lance has all the attributes needed for community and VA urgent care

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
[Facility Locator Attributes for Community Care Providers and VA Facilities](https://docs.google.com/spreadsheets/d/1jhUwU2jRbnoKW0C0Kp1EZSsCNbSlRONwkYViDyuS1Lg/edit#gid=0)

@darkbushido - for your review

**Comment by mpelzsherman** [comment]
Provider (v1/facilities/ccp) |  
-- | --
Attribute Key | Where Used (under src/applications/facility-locator)
id | containers/FacilityLocatorApp.jsx
type |  
attributes: |  
access | components/AppointmentInfo.jsx
accNewPatients | unused - only used on Provider Detail page, which has been removed
activeStatus | unused
address | components/search-results/LocationAddress.jsx
mailing |  
physical |  
street, city, state, zip |  
caresitePhone |  
email |  
fax |  
gender | unused - only used on Provider Detail page, which has been removed
lat/long | LocationDirectionsLink
name |  
phone | unused
posCodes | unused - only used on Provider Detail page, which has been removed
prefContact | unused - only used on Provider Detail page, which has been removed
uniqueId | unused - only used on Provider Detail page, which has been removed
visn | unused - only present in mock data
relationships |  
specialties | used in service type dropdown and results header

**Comment by mpelzsherman** [comment]
Facility (v1/facilities/va) |  
-- | --
Attribute Key |  
id |  
type |  
attributes: |  
access |  
activeStatus | unused
address |  
mailing |  
physical |  
zip, city, state, address1, address2, address3 |  
classification |  
facilityType |  
feedback |  
health |  
effectiveDate |  
hours (monday, tuesday... etc.) |  
id |  
lat/long |  
mobile | unused
name |  
operatingStatus |  
code |  
phone |  
main |  
mentalHealthClinic |  
fax | unused
pharmacy | unused
afterHours | unused
patientAdvocate | unused
enrollmentCoordinator | unused
services |  
uniqueId | unused
visn | unused
website |
