### ISSUE TITLE
Allow resubmission on 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#12099]
Given that we want to allow users to resubmit if they get a failure upon initial submission
_Especially_ if the error was *not* an internal server error
How might we update the content, design, front-end, and backend to allow resubmission?

- [ ] Platform enhancement (not owned by team)
- [ ] Update error message
- [ ] Map user experience
     - Cutoff after x number of tries?
     - Only if data is edited?
- [ ] Frontend updates
- [ ] Adjust Google Analytics (?)
- [ ] Update product guide

**Comment by ala-yna** [comment]
Closing in favor of #19610
