### ISSUE TITLE
Set up research session with Claims for Contact Center reporting

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12093]
## Issue Description
How might we get user feedback on what contact center data is useful, what isn't, and what data we need to retrieve from contact centers, if any?

---
## Tasks
- [ ] Schedule time with B&M1
- [ ] Prepare session materials
- [ ] Prepare session strategy (@joanne or @amycesal to help review)
- [ ] Go through research session
- [ ] Document feedback
- [ ] Synthesize feedback (what we learned, themes, next steps)

## Acceptance Criteria
- [ ] We have user research on contact center data usage.

**Comment by Kimberley2019** [comment]
Meeting Notes with Luke: https://docs.google.com/document/d/1YxrIYvNVTG_9IZMp5v8CLwBNrJTPHzFtcCpouKeN_LQ/edit

Analysis: https://drive.google.com/file/d/1Y1XHqb2mSgzANmFAMFQU9St3f10vD1W8/view?ths=true
