### ISSUE TITLE
Create script to automate traffic

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12094]
## Issue Description
The traffic goes from the Rails app to an HAProxy through the Trusted Internet Gateway (TIC) to go from GovCloud West to GovCloud East then through another TIC to get to the Gov Azure instance. If PPMS needs to make a call to Bing it may also be going from the Gov Azure instance to another TIC to get over there. Monitoring is limited because all of the traffic is encrypted in transit (VPNs) 

---
## Tasks
- [ ] create a script to to automate generating traffic to force the issue
- [ ] analyze fields to determine performance drains 

## Acceptance Criteria
- [ ] Reproducible example of performance spike
- [ ] cost/benefit analysis of including fields

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
