### ISSUE TITLE
Create a Model for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12092]
## Background
With almost all forms on VA.gov we need to set up a model in Rails that will handle saving data to the `vets-api` database. These models act as the glue between the controller and the database and are used not only for retrieving data but also for things like sorting data or filtering data which we will not be doing much of for the Chapter 31 form. In order to submit a model in a PR to `vets-api` we also need to unit test it to 90% coverage so this ticket includes that work as well.

## Tasks
- [x] Determine what model methods are needed
- [x] Set up a model file
- [x] Build model methods
- [x] Unit test model to 90% coverage
- [x] Submit a PR to `vets-api` for review

## Acceptance Criteria
- [x] Draft PR submitted with scaffold code in place for later use

**Next steps**  
- [x] A model with all needed methods for the Chapter 31 form has been created
- [x] The model for Chapter 31 has been unit tested to 90% coverage or better
- [x] A PR has been submitted to `vets-api` for review

**Comment by digitaldrk** [comment]
![image.png](https://images.zenhubusercontent.com/5e62b7b08eb909e3dc9d38f7/cbf08267-251b-4c05-85af-493e629a44e9)

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5209
