### ISSUE TITLE
Create a Model for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12105]
# Background
With almost all forms on VA.gov we need to set up a model in Rails that will handle saving data to the `vets-api` database. These models act as the glue between the controller and the database and are used not only for retrieving data but also for things like sorting data or filtering data which we will not be doing much of for the Chapter 36 form. In order to submit a model in a PR to `vets-api` we also need to unit test it to 90% coverage so this ticket includes that work as well.

## Tasks
- [x] Determine what model methods are needed
- [x] Set up a model file
- [x] Build model methods
- [x] Unit test model to 90% coverage
- [x] Submit a PR to `vets-api` for review

## Acceptance criteria
- [x] A model with all needed methods for the Chapter 36 form has been created
- [x] The model for Chapter 36 has been unit tested to 90% coverage or better
- [x] A PR has been submitted to `vets-api` for review

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4950

**Comment by digitaldrk** [comment]
I have a larger PR going with other things like the controller FWIW
