### ISSUE TITLE
PACT Search POC

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#12104]
## Issue Description
For POC, we need to verify pact contract testing via the search endpoint to confirm that PACT can successfully pass and produce a green status, publishing results back to the [broker](https://vagov-pact-broker.herokuapp.com/). The search endpoint is a simple endpoint that requires no auth.

### Additional Info
Due to Thor dependency issues with the pact and pact-mock_service gems, forks of both repos are required for the time being. We are using Thor 1.0 with vets-api and pact-ruby and pact-mock_service have strict requirements for thor '~> 0.19'. Tickets are opened to move the forked repos from @f1337 to department-of-veterans-affairs. pact-ruby change repo request and pact-mock_service change repo request.

PRs to bump the versioning requirements are opened in pact and pact-mock_service and once merged/approved, the forks can be removed.

---
## Tasks
- [x] Set up the search provider state and corresponding vcr cassette
- [x] Configure VCR in the pact helper
- [x] Configure rspec in pact helper
- [x] define a pact makefile target

## Acceptance Criteria
- [x] A passing verification result via pact rake task
- [x] Specs pass
---
