### ISSUE TITLE
Create Controller for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12101]
# Background
The Chapter 36 form will be submitting to central mail. Submitting a form to central mail within VA.gov means we need to set up a controller on the back end to receive the payload from the front end and call the CentralMail service. In order to submit a PR to `vets-api` we also need our controller to be unit tested to 90% coverage so this ticket includes that work as well.

## Tasks
- [x] Set up controller file (including unauth)
- [x] Define methods in the controller to handle the payload from the front end
- [x] Create unit tests for this controller file up to 90% coverage
- [x] Add Swagger docs if necessary
- [x] Submit a PR to `vets-api`

## Acceptance criteria
- [x] We have an API endpoint set up to accept payload from the front end and submit to central mail
- [x] A PR has been submitted for review

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4939
