### ISSUE TITLE
CH31 Staging Disentanglement

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12116]
## Goal
Right now, CH31 is being redirected to `/careers-employment/vocational-rehabilitation/` which is a static page.  This needs to be:

**Static landing page:** https://www.va.gov/careers-employment/vocational-rehabilitation/
**Start application:** https://www.va.gov/careers-employment/vocational-rehabilitation/apply

## Considerations
- Is this a greedy redirect? (Perhaps Nick S, or Kelson might know?)
- `TIMEBOX:` 1 hour

## Tasks
- [x] Check with Nick and/or Kelson
- [x] See if the redirect is being greedy
- [ ] If not, investigate the entanglement further
- [x] Adjust url to `https://www.va.gov/careers-employment/vocational-rehabilitation/apply`

## Acceptance Criteria
- [x] The reason for disentanglement has been discovered
- [ ] If able to resolve, a PR has been requested for merging
- [ ] If not, document the reason in GH for a dedicated ticket
- [x] url has been adjusted to `https://www.va.gov/careers-employment/vocational-rehabilitation/apply`
