### ISSUE TITLE
Scaffold Wizard for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12113]
## Goal
Now that we have the wizard content nailed down, we need to start building the wizard so that we can complete all the necessary components for delivery.

## Considerations
- There is work done in the [Design System](https://design.va.gov/patterns/wizards) as well as the [code](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/disability-benefits/wizard) and [here](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/disability-benefits/wizard) that shows what is entailed, where Education Wizard is used as an example.
- While we can see what is needed there is still a fair amount work to do to complete this BUT [this](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/static-pages/wizard) might help..
- A prototype is [here](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/130773489/simulate/sitemap). 
- Create a simpler implementation and see if we can have it be the first example as the others are seemingly more complicated than they need to be given what we know today.  We should note the differences (like how we aren't needing to use Redux)

## Tasks
- [x] Setup a [widget](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-widget)  
  - [x] Build out the initial set of questions  
- [ ] [STRETCH] Cookie the user `*`

## Acceptance Criteria
- [x] The CH31 wizard is scaffolded and ready for next steps
- [x] A PR has been submitted for merging

### Next steps `*`  
- [ ] Unit tests   
- [ ] GA event names  
- etc per [our format](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/engineering/product-templates/simple-form)
