### ISSUE TITLE
Create a Sidekiq Job for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12141]
`consider closing and whether we need to wait for the pdf to be generated`
`not critical for submission`

# Background
When we set up services in `vets-api` we set up sidekiq jobs to keep us decoupled from the API we are submitting to. For Chapter 31 we need to set up a sidekiq job for submitting to central mail so that we don't need to wait for a response from central mail.

## Tasks
- [ ] Set up sidekiq job file
- [ ] Write `perform` methods
- [ ] Submit a PR to `vets-api` for review

## Acceptance criteria
- [ ] A Sidekiq job for the Chapter 31 form is set up and working as expected
- [ ] A PR has been submitted to `vets-api` for review
