### ISSUE TITLE
[Engineer] Create Listing pages for VISN-19 Systems to include Events, Stories, Leadership, News Releases [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12145]
## Story
As a web writer developer, I need to have listing pages to place all stories, events, and news releases, so our customer can see them in Devshop.

## Task
Create new listing pages for each of the following systems:
- [x]  VA Cheyenne health care
- [x]  VA Eastern Colorado health care
- [x]  VA Western Colorado health care
- [x]  VA Montana health care
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care

## Acceptance Criteria
- [x] All Event, Story, News Release listing pages and Operating status page have been created for each VISN-19 system.
