### ISSUE TITLE
Create Sidekiq Job for Ch36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12142]
# Background
When we set up services in `vets-api` we set up sidekiq jobs to keep us decoupled from the API we are submitting to. For Chapter 36 we need to set up a Sidekiq job for submitting to central mail so that we don't need to wait for a response from central mail.

## Considerations
- [FEs ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12826)

## Tasks
- [ ] Set up sidekiq job file
- [ ] Write `perform` methods
- [ ] Submit a PR to `vets-api` for review

## Acceptance Criteria
- [ ] A Sidekiq job for the Chapter 36 form is set up and working as expected
- [ ] A PR has been submitted to `vets-api` for review

**Comment by jason-gcio** [comment]
This ticket was not needed, per Derek
