### ISSUE TITLE
Create eFolders Controller and Route

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#12159]
## Issue Description
Add the controller and route for eFolders. There needs to be an index method to shows all of the letters in a JSON format, there will also need to be a route that shows the contents of each document.

## Tasks
- [x] Index Controller action
- [x] Show Controller action
- [x] Index Route
- [x] Show Route
- [x] Serializer

## Acceptance Criteria
- [ ] Will be able to get a valid response from GET /v0/efolder & GET /v0/efolder/{:id}
