### ISSUE TITLE
User Docs - Logging Solution (Loki)

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#12152]
## Description
Before we can launch Loki to our customers we need to have documentation in place so users can understand how to use it.  

## Background/context/resources
Following our [initiative tracking](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11647) and [product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/logging/readme.md) we will need users docs around the following:
- user docs about logging from FE + BE
  - How do you log things from FE and how do you log things from BE
  - how do you view/search logs in our logs UI ( more for the general audience)  

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _draft docs and then present them to users for testing and feedback (work with TJ to find users)_
- [ ] _Make iterations on docs after user feedback_
- [ ] _publish doc and work with TJ to ensure they are communicated out_

## Definition of Done
- [ ] _Doc are created, approved and communicated out about_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by pnwstevan** [comment]
I've generated some pretty comprehensive documentation in Confluence here:

https://vfs.atlassian.net/wiki/spaces/VI/pages/edit-v2/619119010

**Comment by jhouse-solvd** [comment]
Please see [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17389) where we are tracking against the initiative / launch checklist which includes making sure relevant documentation is available.
