### ISSUE TITLE
COVID-related refill prescription updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#12154]
## Issue Description
We need to emphasize that Veterans should refill prescriptions no later than 10 days before they'll need more medication.

---
## Tasks
- [ ] **On coronavirus FAQs page (node 3014):** Move prescription question up to be 2nd question in health care section, and emphasize the 10 days messaging by a) bolding "10 days" and b) making that sentence its own paragraph. Also revising mentions of "run out of your prescription" to "need more medication" to remove idiom from page (in both of the questions about prescriptions). 
- [ ] **On refill prescriptions page (node 27):** Add an informational alert with relevant messaging and an anchor link over to the prescription question on the FAQs page. Also need to remove global coronavirus alert from this page now that we'll have an in-body alert. Also revising mentions of "run out of your prescription" to "need more medication" to remove idiom from page.

**Steps to completion**

- [x] Update FAQs page per above (Danielle)
- [x] Create alert and add to prescription refill page per above (Danielle)
- [x] Update prescription refill page per above (Danielle)
- [x] Remove global alert from prescription page (Randi)
- [x] Copy edit FAQs page and alert/prescription page, and set both to publish (Randi)

## Acceptance Criteria
- [x] Updates live on site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These pages have both been published. Moving to validate.

**Comment by RLHecht** [comment]
These changes are live on the site. Closing ticket. FYSA @DanielleThierryUSDSVA @MickinSahni

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!
