### ISSUE TITLE
Design Doc for new Deployment pipeline 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#12151]
## Description
We need a place in the open to present and talk through our ideas for the new deployment pipeline in the new infra.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Complete a Design doc and ask for feedback_

## Definition of Done
- [ ] _Design doc is created_
- [ ] _Team and leadership provides feedback _
- [ ] _Doc is updated_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
