### ISSUE TITLE
Change school year range in YR tool intro paragraph

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12167]
## Issue Description
On this page:
https://www.va.gov/education/yellow-ribbon-participating-schools/

We need to update the years to reflect the new school year in the intro paragraph on the YR tool page.

Change the last sentence in the intro (after the two linked bullet points) to this:
Search for schools participating in the current academic year, August 2020 through July 2021.

---
## Tasks
- [ ]  Replace last sentence of intro with the above.
- [ ] Do ^^ also for the description text after searching.

## Acceptance Criteria
- [ ] Correct school year dates for the current school year appear on the YR tool page.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
