### ISSUE TITLE
10-10CG Error on Review Page - Submit Button 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#12179]
## Issue Description

When Veterans and caregivers attempt to submit the 10-10CG form and cannot be verified due to MPI lookup or other reasons (e.g. typo in certain fields) users will receive an error message. Due to security concerns, the error message cannot specify which fields cannot be verified and the user is directed to print, sign and mail a PDF of the 10-10CG.

The submit button disappears on the Caregiver form when error message is triggered.

- Can we assume that the business team would want the user to be able to resubmit upon failure?
- Is this the intended/desired behavior of VSP - [see ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11594)

## Tasks
- [ ] Document current behavior of error message 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [X] **Attached to a Milestone** (when will this be completed?)
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
[Ticket #11594 for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11594)
