### ISSUE TITLE
[Centralized Logging] Usage metrics for Loki 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#12180]
## Description
Loki has two ways you can access logs: 
- via Grafana (which has Google Analytics?), we there are metrics that can be gathered when users Loki logs through the UI
- via Loki's command line. As of right now, we aren't sure how to measure this? 

## Background/context/resources
In order to see if customers are using the new logging pipeline or where we can improve we first need to measure. 

## Technical notes
Idea: Loki has an API that is being used, so maybe something there we can look into. 
The number of Queries is something to maybe look into. 

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _We can see when people are using Loki via the command line_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by pnwstevan** [comment]
Will create metrics/KPIs on API usage per Loki environment.

**Comment by jhouse-solvd** [comment]
This is still a pretty relevant need.

**Comment by jhouse-solvd** [comment]
Some metrics exists here: 

https://app.datadoghq.com/dashboard/lists?q=loki

We will expand on this in the future as needed. Closing.
