### ISSUE TITLE
Point all content builds to prod CMS

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#12197]
## Issue Description
I talked with @swirtSJW and we couldn't think of a reason to not. Prod will always have the latest content. There are some issues in the lower environments that make building with CMS export infeasible. Something about missing nodes...I'm not clear on the details.

---
## Tasks
- [x] Point the lower environments to the prod CMS [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/constants/drupals.js#L29-L31)
    - I think this is all that's needed to make the switch over
- [x] Verify that a local build still works, but fetches prod content
    - Maybe do a local build first, `cp build/localhost/ build/previous-localhost/`, change :point_up:, build again, then `diff -qr build/previous-localhost build/localhost` to verify that stuff changed

## Acceptance Criteria
- [x] The lower environments pull from the production CMS

**Comment by jhonnyoddball** [comment]
Done!
