### ISSUE TITLE
Copay-related COVID-19 updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#12198]
## User story

Veterans need to understand what's going on with their copays during the pandemic, and what to expect when they start getting billing statements again in January 2021.

## Issue Description
We need to:
- Update the FAQs
- Update the chatbot (GH files: https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/master/content/chatbot-copy.md and https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/master/content/chatbot-messages.md)
- Add an alert to the in-progress debt management tool page

---
## Tasks
- [x] Write FAQ content (Danielle)
- [x] Revised per SME feedback (Danielle)
- [x] Send to JTF (Lauren)

**When we receive JTF approval via Lauren**
_FAQ_
- [x] Update content in FAQ (Peggy/Randi)
- [x] Review FAQ content for errors/omissions and set to publish (Peggy/Randi)
_Chatbot_
- [x] Update content in chatbot (Peggy/Randi)
- [x] Review chatbot content for error/omissions and alert @rumyeahs on dev team that it's ready (Peggy/Randi)
_alert_
- [x] Share approved alert copy with debt management team (Peggy)

## Acceptance Criteria
- [x] Updated content is live on site

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Files that went to JTF for review (**not** final, approved files).

[Copay FAQ for jtf review 8.6.20](https://app.zenhub.com/files/133843125/f3f378da-4c10-45bc-9b63-86716e8d3326/download)

[Coronavirus FAQ page_testing content updates_for jtf review_8.7.20](https://app.zenhub.com/files/133843125/fd570a7b-59a0-40a8-89b4-a4be56fe0191/download)

[COVID alerts for Debt Management tool](https://app.zenhub.com/files/133843125/dbb63bbe-cc87-4438-a48c-eda7896f5667/download)

**Comment by peggygannon** [comment]
**8/11/2020 update** JTF has not approved the copay copy. Lauren is thinking of other options for this.

**Comment by DanielleThierryUSDSVA** [comment]
We received approval and published these updates. Closing ticket. Thanks, all!

FYSA @MickinSahni @brianalloyd
