### ISSUE TITLE
Project Kickoff eFolders Migration 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12194]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/eFolders_Migration) 
- Explanation of the problem space

This is a forklift migration of eFolders from eBenefits to va.gov. The scope of this MVP iteration is to replicate feature, functionality of eFolders. We plan to iterate on improving UX experience in later iterations. 

- Any other artifacts you have so far
You an see the current eFolder here: 
https://pint.ebenefits.va.gov/domain1/mock-csp/index.jsp * 
choose Jaime Brooks to see the most documents uploaded 
https://sqa.eauth.va.gov/ebenefits/myDocuments -- URL for eFolders after choosing test user. 

The main question we do not have an an answer to is where on va.gov eFolders will be. Can you please have someone from IA (we love @mnorthuis so much) at this meeting. 

## Implementation Team (BAM2)
|Name|Role|eMail | Github
|----|----|----|---|
|Matthew Self| DSVA Lead| matthew.self2@va.gov|@mattpointzxer0 
|Leah Keeler | Product Manager|lkeeler@governmentcio.com|@leahkeeler
|Cameron Testerman | BE Engineer|cameron@oddball.io|@camerontesterman 
|Brad Conley | FE Engineer|bconley@governmentcio.com|@bradl3yC 
|Mahariel Rosario | FE Engineer|mrosario@governmentcio.com|@mr0sari0 
|Riley Orr | Designer|riley@amida.com|@rileyorr 
|Becca Walsh | Designer|rebecca.walsh@adhocteam.us|@rebeccawalsh 

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** Yes, potentially 

## Scheduling -8/13 if possible 
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

**Comment by mandifrances** [comment]
@leahkeeler scheduled for the 13th @ 1:30pm ET

**Comment by leahkeeler** [comment]
![eFolders .png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/94ff1538-7cd2-4c92-93aa-2c65c2d9ee82)![eFolders .png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/31bfada4-00a2-4820-b1b3-3d9d9674b56c)![2020-08-10_11-29-32.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/70285888-ac0a-41f9-9456-0c7d91555b0d)![2020-08-10_11-29-42.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/53a53dd6-7cfb-420b-95ba-7adc6c3e0bac)
