### ISSUE TITLE
[Automation]  Review and confirm all VISN-19 playbooks index pages are set up correctly for migration [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12219]
## Story
As a Migration engineer, I need all of the VISN playbooks to reference the system health services by facility location so I can sort out all unique instances of the health service by system.

## Resources
[Analytics VISN-19 Playbooks](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
- [x] Review each of the VISN-19 playbooks for Index and review for accuracy with facilities
- [x] Update and repair Index to include all System health services by the facility
- [x] Create a filter and test that the filter can break up the index by facility an show the information

## Acceptance Criteria
* All indexes are in tact for each system
* All indexes can be filtered and use for Migration purposes
