### ISSUE TITLE
[DISCOVERY] Design for predictive geolocation

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12226]
## Issue Description
Implementing “predictive search” is a planned enhancement to the search on Facility Locator. This will allow us to show the list of matching place names in a scrolling div under the text field. MapBox returns a maximum of 10 locations. 

## Questions

- How is the list displayed? 
   - Rendered below the field?
   - Sizing relevant to the other fields
- Will we show the full suggestion or will it be truncated?
- How is the suggestions display on mobile?
- Differences in display at major breakpoints?
- How many results should be returned?

---
## Tasks
- [ ] Determine approach for implementation of predictive geolocation

## Acceptance Criteria
- [ ]  Design specs for the major breakpoints, limited to the predictive geolocation enhancement
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
