### ISSUE TITLE
[Automation] Create Access/Excell sheet that will parse data from Playbooks into .csv data format [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12237]
## Story
As a Migration engineer, I need all of the VISN playbooks to reference the system health services by facility location so I can sort out all unique instances of the health service by system.

## Resources
[Analytics VISN-19 Playbooks](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
- [x] Create automated process to parse and consolidate data System health Services into .csv file
- [x] export data into appropriate System HS .csv file
- [x] document repeatable process to provide .csv file for System Health Services migration

## Acceptance Criteria
* .csv file can be used for System Health services VISN-19
* Access db is accessible to team
* Process is documented.
