### ISSUE TITLE
Analytics Reporting Request for Public Affairs presentation (Lauren A. & Chante L-S)

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12247]
# Metrics Reporting Request

## Description
Who is this request for?

Lauren A & Chante L-S for the Public Affairs presentation

**Due before close of business on Wednesday 8/12/20**
    
## Timeframe for Analytics Requested
March 2020 - July 2020

(Beginning of Covid - end of July)

## Tasks
- [ ] Chante to oversee final result & overall framework
- [ ] Jon/Brian/Ben ensure that data quality is clean and updated
- [ ] Team to add any potential notes/talking points
- [x] Amy to create PowerPoint
- [x] Amy to make any necessary visualization changes
- [x] Amy to export charts/visuals/text 
- [x] Amy/Chante to send final presentation

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users in editable Powerpoint.

## Definition of Done
- [ ] All AC completed

---
### Slide 1 - Overall rational for doing this type of tracking/Why
- Potential content: Improve the impact of our services through data-informed decision making and multiple data sources
- Potential talking points: 
  - As covid started breaking out, we wanted to pull together information to help inform us 1) what information veterans were trying to get from the VA in order to better understand their needs, and also 2) if the digital services and initiatives related to our covid efforts were working or if they needed to change
  - It was important to pull in information from multiple sources of the VA to understand the breadth of the situation and veteran needs and to ensure that we had a holistic view of the user experience. This was especially true as the events in the nation were rapidly changing.

### Slide 2 - Overall examples
- Graph: Contact Center Covid-related Volume Per Week
- Graph: Page view comparison
- Graph: July synthesis
- Potential talking points: Each week, we’re able to run through the latest trends and correlate why certain behaviors are occurring. Through traffic analysis and veteran feedback, we’re able to synthesize the type of information veterans are looking for and determine the causes for specific spikes to covid-related VA.gov sites or applications. These views highlight which content to prioritize, which applications to build or put fewer resources into, when during the week or during the pandemic we might see more covid-related traffic, etc. We have data from call centers, va.gov site pages, applications, and other sources to ensure that we're not looking at just one piece of the puzzle, but that we're taking every part of the veteran experience into consideration.

### Slide 3 - Contact Centers
- Graph: Contact Center Covid-related Volume Per Week
- Graph: VEO calls by issue
- Potential talking points: 

### Slide 4 - VA.gov content
- Graph: Page view comparison
- Graph: FAQ themes/questions
- Potential talking points: We’re able to see which parts of the website are used the most and how it’s used. We can look to the contact center data to determine which covid-related questions veterans are asking, and ensure that we’re answering and prioritizing those same questions on our website content. Being able to compare this data to the other sources and see historical trends also allows us to prepare for large traffic spikes on specific pages or the site in general, understand if we're directing veterans to the right places, and focus our efforts on where veterans are trying to go most.

### Slide 5 - App data
- Graph: Screener tool
- Graph: MHV appointment requests
- Graph: Chatbot usage
- Potential talking points: As in-person services were closing and we were trying to drive certain behaviors like going to our online tools, we’re able to track the usage and helpfulness of those tools themselves. We want to ensure that facilities are using the screener tool so that facility reopenings are happening safely, that veterans are still requesting the medications they need, and that folks are using the chatbot according to our original hypotheses. We can see this all in the same place and check that our other Covid-related services are still being utilized.

### Slide 6 - Social Media
- Graph: Latest themes card
- Potential talking points: While anecdotal, our qualitative data on veteran feedback allows us to hear the voice of the veteran. These themes reflect our quantitative data (reveal if the data is or isn't reflecting their voice) and give us context why this work is important.

**Comment by joanneesteban** [comment]
@lalexanderson-dsva @KevinMHoffmanUSDS for awareness

**Comment by jonwehausen** [comment]
@bmcgrady-ep Could I task you with the following items related to this 

- [ ] Do a full audit of the metrics above and just make sure the components being asked for are in fact surfaced within the dashboard, identify any gaps in what's being requested and what we're currently showing
- [ ] QA current numbers for accuracy against GA, determine any historical backfills that we should execute
   - [ ] For those that do need a backfill, configure DOMO to do so within the settings and of the connector and execute, or schedule the execute

**Comment by ricetj** [comment]
This is being pushed back by a week per conversations in slack: https://dsva.slack.com/archives/CKCRMLGAC/p1597062982488700

**Comment by joanneesteban** [comment]
**Due today!**

It's go time for this one!

@amycesal This needs to be visualized in a PPT. The proposed graphs and talking points for each slide is in the description above.

@bmcgrady-ep @jonwehausen Is the data in the graphs ready to go? We shouldn't need completely up-to-date data, just the points that Jon outlined above.

@clantosswett 
- Are the talking points in the description okay, or are you looking for other things as well? I didn't add anything to  the contact center one since I figured you'd have specific insights you wanted to share for that 😬 But let me know if you want points added there as well! 
- Do you need a conclusion slide that talks about where the dashboard is going and where we're hoping it will take us? (Essentially, 1) continuous iteration to reflect the goals and questions being asked during the pandemic and the changes during the pandemic, and 2) an open data culture where we can eventually get to places like using A/B testing for experimentation and move towards predictive and prescriptive analytics.

**Comment by amycesal** [comment]
I'm actually going to have @jonwehausen do the ppt export since he has the ppt plugin. Using the plugin makes more things live text rather than screenshots, which I think will be helpful.

**Comment by amycesal** [comment]
this was delivered in Slack: https://dsva.slack.com/archives/C010AJ1L2EN/p1597867385001800
