### ISSUE TITLE
Collab Cycle: Wizards

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12245]
- [ ] Kickoff
- [ ] Design Intent
- [ ] Information Architecture (IA) Request  #12244
- [ ] Research Plan Review
- [ ] Analytics Request #12317
- [ ] Midpoint Review
- [ ] Contact Center Review
- [ ] Staging Review
- [ ] Privacy and Security Review
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in
