### ISSUE TITLE
Update to bulleted text on MST page in health care

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12246]
## Issue Description
This is a stakeholder maintenance update. There are two changes to make, one is an edit to bullets and the other is to update the link that points to a pdf.

Both changes are under the question: 
**Can I get disability compensation (monthly payments) or other benefits from VA?**

Here's the text submitted by stakeholder (has been edited in drupal, so differs from this):
- Reading our fact sheet to learn about disability compensation for other conditions related to MST. 
Read the MST fact sheet (PDF) REPLACE THIS URL WITH NEW ONE BELOW
- Talking to an MST outreach coordinator at your nearest VA regional office. You can ask to talk to the female or male coordinator
Find an MTS outreach coordinator near you RETAIN THIS LINK AS IS

Here's the new pdf url:
https://www.benefits.va.gov/BENEFITS/factsheets/serviceconnected/MST.pdf

---
## Tasks
- [x] Edit bullet text as outlined above.
- [x] Replace URL for pdf in one of the bullets. 

## Acceptance Criteria
- [x] Updates appear on the MST page.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht This was the maintenance request I took care of myself that I mentioned to you on our call. Thank you for copyediting. Let me know if you have any changes.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Hold off publishing until I hear back from the SME. I cc'd you on the email I sent her, so you'll see the response too. There may be some conversation needed about our lowercasing of occupational titles.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I don't know the background on this but for the sentence "You can talk to the male or female coordinator" is there only one of each at a regional office or there are many coordinators? If it's many, we should change it to "You can talk to **a** male or female coordinator."

**Comment by bethpottsVADEPO** [comment]
@RLHecht I haven't heard back from the stakeholder. I may still get a mail about this tomorrow, but let's set it to publish on Tuesday. We can revise later if need be.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Re: your question above, yes, as we discussed, please do change "the" to "a"

**Comment by RLHecht** [comment]
I published this page. Moving to validate and will close later this afternoon. @bethpottsVADEPO If we get any new info back from stakeholders we can reopen and make changes.

**Comment by RLHecht** [comment]
This is validated on live site. @bethpottsVADEPO do you want to let the stakeholders know? Closing ticket. FYSA @MickinSahni
