### ISSUE TITLE
COVID-19 testing content: Update FAQs and chatbot

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#12255]
## User story

Veterans need to understand if and how they can get tested for COVID-19.

## Issue Description
We need to:
- Update the FAQs
- Update the chatbot (GH files: https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/master/content/chatbot-copy.md and https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/master/content/chatbot-messages.md)

---
## Tasks
- [x] Write FAQ content (Danielle)
- [x] Revised per SME feedback (Danielle)
- [x] Send to JTF (Lauren)

**When we receive JTF approval via Lauren**
_FAQ_
- [x] Update content in FAQ (Peggy/Randi)
- [x] Review FAQ content for errors/omissions and set to publish (Peggy/Randi)
_Chatbot_
- [x] Update content in chatbot (Peggy/Randi)
- [x] Review chatbot content for error/omissions and alert @rumyeahs on dev team that it's ready (Peggy/Randi)

## Acceptance Criteria
- [x] Updated content is live on site

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
File sent to jtf (**not** final, approved version):
[Coronavirus FAQ page_testing content updates_for jtf review_8.7.20](https://app.zenhub.com/files/133843125/5d06a253-80df-4a56-9041-8467a77d9886/download)

**Comment by peggygannon** [comment]
@RLHecht this version above was approved by JTF today (with no changes!). this is ready to be updated in drupal and chatbot.

**Comment by RLHecht** [comment]
@peggygannon I updated the question in the FAQs. Please review and publish if all looks good.
preview-prod.vfs.va.gov/preview?nodeId=3014

**Comment by rumyeahs** [comment]
@peggygannon @RLHecht Whenever you are ready to make the content changes on Chatbot, can you please make them on a branch as opposed to on master. It is easier for the team to review and merge changes. 
cc: @shefalinayak FYI

**Comment by peggygannon** [comment]
Hi, @rumyeahs Yes, will do! We'll make the updates on a branch.

I will let you and @shefalinayak know when they are ready to merge.

**Comment by RLHecht** [comment]
@rumyeahs @shefalinayak I just reviewed Peggy's changes and approved it. It's ready to merge.

**Comment by RLHecht** [comment]
The FAQ changes have been validated on the live site. @peggygannon can we close this ticket?

**Comment by peggygannon** [comment]
hello! @RLHecht the chatbot isn't yet updated, so let's wait until that change is live, then we can close this ticket.

**Comment by rumyeahs** [comment]
@peggygannon and @RLHecht We have these content changes up on staging at https://staging.va.gov/coronavirus-chatbot/
Can you please take a look and let us know if this is good to push to prod. We will change the Last Updated Date to 11 Aug 2020, to keep it consistent with the FAQ page. 
Thank you!

cc: @shefalinayak

**Comment by peggygannon** [comment]
HI, @rumyeahs and @shefalinayak Updated chatbot looks good. Thank you! We're good to push this to PROD

**Comment by peggygannon** [comment]
Closing. Chatbot and FAQ updates are live.
