### ISSUE TITLE
Update related pages to support STEM page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#12252]
## Issue Description
We need to update the related pages to support the new STEM page.

---
## Tasks
- [x] Revise Education hub page teaser to be more general and include mention of stem (Danielle)\
- [x] Update Other education benefits page to be a straightforward link list not associated with "if you don't qualify for post-9/11; move GI Bill comparison tool & accredited rep links to related links section; revisit REAP note (Danielle)
- [x] Add crosslinks from post-9/11, fry scholarship, and undergrad degree pages (Danielle)
- [x] Copy check & publish (Beth or Randi)

## Acceptance Criteria
- [ ] Content on live site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @MickinSahni for sprint planning: This issue will mostly be me. I'll be asking Randi or Beth for an edit/review. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mnorthuis. Can you let me know if this feels right based on our IA/content strategy discussions? Thank you! http://preview-prod.vfs.va.gov/preview?nodeId=945

**Comment by mnorthuis** [comment]
This reads a lot better!   2 small thoughts:
1) I still think its a bit odd that MGIB is listed here prominently but its not where it lives. I'm not sure what the alternative is right now, but is something I'd like to look at down the line. 
2) The note about REAP looks like it is attached to the VEAP program.  Is that intentional?  Are we also going to retire the VEAP content page?

**Comment by DanielleThierryUSDSVA** [comment]
Yay!

1) I agree. I honestly don't know what the original intention behind this "other" page was...but it feels like our instinct is to whittle down the list of programs...which then makes me think we should just:

- Put STEM Scholarship within GI Bill
- Add a page for National Call to Service
- Maybe convert "Other" programs to "Older" programs and have it just house VEAP and REAP and move it to Resources?? Or maybe VEAP is in "Manage benefits" since you can still use it? Definitely feels weird to have REAP still in Get Benefits if you can no longer actually get that benefit (and we need to update that page...I will create a ticket for that)...and VEAP you can _use_ still but you can't _get_
it...you would've had to have put $$ into it a long time ago.
2) Not intentional. Will relook at that. I don't think we have plans to retire VEAP page.

**Comment by mnorthuis** [comment]
1.  Good thoughts...GI Bill is the active program, so that's why MGIB actually live within GI Bill section...but how do we separate the primary benefit from the secondary benefits in this  hub?  There are soooo many options.  I think there's a lot to rework here, so I'd advocate for leaving it as is for now, but maybe put some content strategy work in our backlog for this - a complete revamp of the education hub is likely in order.

**Comment by DanielleThierryUSDSVA** [comment]
Hello @mnorthuis. I think we likely have another entry point into the STEM page here: https://www.va.gov/education/about-gi-bill-benefits/ 

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/2deb70c9-5b3b-42ef-aaef-851a442b6af3)

Do you agree? If yes, I'll add a link/description. Thanks!

**Comment by mnorthuis** [comment]
Agreed!  Thank you @DanielleThierryUSDSVA !

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Would love your final copy eyes on a few things before we hopefully publish for today's deploy (I am checking in w/ the product team at 12 noon just to make sure we're all good to publish).

http://preview-prod.vfs.va.gov/preview?nodeId=945
**Note:** Would love just a final eye (it's had editing, but still good!).

http://preview-prod.vfs.va.gov/preview?nodeId=71
**Note:** Just updated the "Other educational assistance programs" description. 

http://preview-prod.vfs.va.gov/preview?nodeId=6860
**Note:** I've incorporated some SME feedback and would just love a final eye to make sure I didn't introduce any errors.

Note for @mnorthuis I need to turn my attention to other things now so am going to add the crosslinks to the other pages tomorrow. Thanks!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA These pages all look good. I made one small fix on the "Other VA education benefits" page. The comma in the date under the VEAP section was in the wrong place. No other changes anywhere else. Let me know if you need me to set these to publish or you will.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA These pages have been published. Moving to validate and can close after today's deploy.

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Sorry, I'm just going to reopen until we add the additional crosslinks. Just want to keep the reminder here for myself :)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I've added crosslinks to these 3 pages. Could you review and publish when you have time? This is not urgent. Once we've validated, we can close this ticket and the associated epic.  

http://preview-prod.vfs.va.gov/preview?nodeId=7809
http://preview-prod.vfs.va.gov/preview?nodeId=915
http://preview-prod.vfs.va.gov/preview?nodeId=935

@mnorthuis 2 things: 1) I did not include a crosslink on the undergraduate/graduate degree page as we'd originally talked about. You can't use STEM for grad school, and my understanding is that this has been a source of confusion so I think we don't want to add to that. And I don't think we lose anything by not having it on that page.

@RLHecht @mnorthuis @bethpottsVADEPO I feel like, especially on the GI Bill page, we could look at the groupings of links more and improve. Not a priority, but wanted to raise for awareness at some point.

FYSA @brianalloyd

**Comment by RLHecht** [comment]
These have been validated on the live site. Closing ticket. FYSA @brianalloyd @MickinSahni
