### ISSUE TITLE
Enable UAT testing visibility only for Manage debt page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#12250]
## Issue Description
We have a request from the debt management team to make it so that we can publish the Manage your debt landing page so it's only visible to UAT testing users.

Link to slack discussion: https://dsva.slack.com/archives/C52CL1PKQ/p1596747953165200

I'm opening this and assigning everyone from the slack thread as a placeholder to begin tracking this work. Please feel free to edit issue as needed. 

@leahkeeler Can you confirm timing need for this? Thank you!

---
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] Page is published and visible only for UAT testing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @MickinSahni

**Comment by leahkeeler** [comment]
We will need this in place by 8/14 for moderated UAT, earlier to show to stakeholders, if at all possible

**Comment by MickinSahni** [comment]
TBD when we're able to complete (sprint planning this week). This is slotted for our next sprint (8/12-8/25) and will consider against other priorities.

**Comment by ncksllvn** [comment]
What is the URL of the page we want to gate for UAT?

**Comment by bradl3yC** [comment]
@ncksllvn  https://va.gov/manage-va-debt/

**Comment by leahkeeler** [comment]
@ncksllvn Will we be able to get this in place for UAT testing this Friday ?

**Comment by ncksllvn** [comment]
This is ready, https://www.va.gov/manage-va-debt
