### ISSUE TITLE
[Metrics] Claims Status: Get Metrics for Average Number of Claims, Type of Claims for CST

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#12256]
We need to gather a few quantitative metrics around claims in the Claim and Appeals Status Tool. By doing so, we can better understand if there is value in having filters. If so, what types of filters make sense from a usability perspective?

Note: If this report would be gigantic, I will add some sort of range on it, just let me know.

### Tasks

- [ ] Find the average number of items (claim and appeals) per user in the Claim Status Tool
- [ ] Find the average number of appeals per user in the CST
- [ ] Find the average number of claims per user in the CST
- [ ] Determine how varied the claims are (mostly disability? a lot of other types of claims showing up?)
- [ ] Determine how many closed vs active claim statuses there are per user (on average)

### Acceptance Criteria

- [ ] The above task/questions have been answered and the results are shared as a comment in this ticket
