### ISSUE TITLE
[UI] UX Design Demographics

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12259]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Demographics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/demographics.md)

## User Story/ies

* **Use Case:** Veterans need the ability to see the demographic information that is on record to ensure accuracy and be able to verbally with the care team or through a digital edit experience update for the most up to date information.  
---
## Tasks
- [x] See demographic feature outline for fields and valuation
- [x] Create detailed mockups and callouts of demographic page

## Acceptance Criteria
- [x] UI review with team for feature capabilities and engineering callouts
- [x] published to [Zeplin](https://zpl.io/2p9EOr8)
