### ISSUE TITLE
[Frontend] Display Demographics 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12257]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Demographics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/demographics.md)

## User Story

Veterans need the ability to see the demographic information that is on record to ensure accuracy and be able to verbally with the care team or through a digital edit experience update for the most up to date information.  

---
## Tasks
- [x] See demographic feature outline for fields and valuation
- [x] Create demographic page per mockup/prototype (link) 
- [x] Determine if there is a re-usable demographic component/API that holds all fields in feature outline so our team is not owning the UI display.  
![image.png](https://images.zenhubusercontent.com/5ede4fb2cea2fa1db922bc7f/1b3013e0-234f-4156-9653-bd682ab81f5f)

## Acceptance Criteria
- [ ] UI review with product for feature capabilities 
- [ ] UI review and sign off from design for layout and callouts
- [ ] published to staging environment, behind a feature flag

**Comment by mdewey** [comment]
@abuckley3385  or @arickalewis1  Question on the mock-up, is that `home phone` or `mobile phone` ?

**Comment by abuckley3385** [comment]
Both are coming from the demographics API?  Is there a phone preference flag in that API?  i think we have to show both if there is not a pref flag and only show if it has an entry.  Let me know whats in the api and I can update the feature outline.

**Comment by mdewey** [comment]
@abuckley3385  and @arickalewis1 

Here is all the profile information I have on a user 
```
user: {
    login: {
      currentlyLoggedIn: true,
      hasCheckedKeepAlive: false
    },
    profile: {
      userFullName: {
        first: 'HECTOR',
        middle: 'J',
        last: 'ALLEN'
      },
      email: 'vets.gov.user+0@gmail.com',
      dob: '1932-02-05',
      gender: 'M',
      accountType: 3,
      loa: {
        current: 3,
        highest: 3
      },
      verified: true,
      mhvAccount: {
        accountLevel: null,
        accountState: null,
        errors: null,
        loading: false,
        termsAndConditionsAccepted: false
      },
      vet360: {
        email: {
          id: 100,
          emailAddress: 'veteran@gmail.com'
        },
        mobilePhone: {
          areaCode: '503',
          countryCode: '1',
          createdAt: '2018-04-21T20:09:50Z',
          effectiveEndDate: '2018-04-21T20:09:50Z',
          effectiveStartDate: '2018-04-21T20:09:50Z',
          extension: '0000',
          id: 123,
          isInternational: false,
          isTextable: true,
          isTextPermitted: null,
          isTty: true,
          isVoicemailable: true,
          phoneNumber: '5551234',
          phoneType: 'MOBILE',
          sourceDate: '2018-04-21T20:09:50Z',
          updatedAt: '2018-04-21T20:09:50Z'
        },
        homePhone: {
          areaCode: '503',
          countryCode: '1',
          createdAt: '2018-04-21T20:09:50Z',
          effectiveEndDate: '2018-04-21T20:09:50Z',
          effectiveStartDate: '2018-04-21T20:09:50Z',
          extension: '0000',
          id: 123,
          isInternational: false,
          isTextable: false,
          isTextPermitted: false,
          isTty: true,
          isVoicemailable: true,
          phoneNumber: '2222222',
          phoneType: 'HOME',
          sourceDate: '2018-04-21T20:09:50Z',
          updatedAt: '2018-04-21T20:09:50Z'
        },
        workPhone: null,
        faxNumber: null,
        temporaryPhone: {
          areaCode: '503',
          countryCode: '1',
          createdAt: '2018-04-21T20:09:50Z',
          effectiveEndDate: '2018-04-21T20:09:50Z',
          effectiveStartDate: '2018-04-21T20:09:50Z',
          extension: '0000',
          id: 123,
          isInternational: false,
          isTextable: false,
          isTextPermitted: false,
          isTty: true,
          isVoicemailable: true,
          phoneNumber: '5555555',
          phoneType: 'MOBILE',
          sourceDate: '2018-04-21T20:09:50Z',
          updatedAt: '2018-04-21T20:09:50Z'
        },
        mailingAddress: {
          addressLine1: '1493 Martin Luther King Rd',
          addressLine2: 'Apt 1',
          addressLine3: null,
          addressPou: 'CORRESPONDENCE',
          addressType: 'DOMESTIC',
          city: 'Fulton',
          countryName: 'United States',
          countryCodeFips: 'US',
          countryCodeIso2: 'US',
          countryCodeIso3: 'USA',
          createdAt: '2018-04-21T20:09:50Z',
          effectiveEndDate: '2018-04-21T20:09:50Z',
          effectiveStartDate: '2018-04-21T20:09:50Z',
          id: 123,
          internationalPostalCode: '54321',
          province: 'string',
          sourceDate: '2018-04-21T20:09:50Z',
          stateCode: 'NY',
          updatedAt: '2018-04-21T20:09:50Z',
          zipCode: '97062',
          zipCodeSuffix: '1234'
        },
        residentialAddress: {
          addressLine1: 'PSC 808 Box 37',
          addressLine2: null,
          addressLine3: null,
          addressPou: 'RESIDENCE/CHOICE',
          addressType: 'OVERSEAS MILITARY',
          city: 'FPO',
          countryName: 'United States',
          countryCodeFips: 'US',
          countryCodeIso2: 'US',
          countryCodeIso3: 'USA',
          createdAt: '2018-04-21T20:09:50Z',
          effectiveEndDate: '2018-04-21T20:09:50Z',
          effectiveStartDate: '2018-04-21T20:09:50Z',
          id: 124,
          internationalPostalCode: '54321',
          province: 'string',
          sourceDate: '2018-04-21T20:09:50Z',
          stateCode: 'AE',
          updatedAt: '2018-04-21T20:09:50Z',
          zipCode: '09618',
          zipCodeSuffix: '1234'
        }
      },
      savedForms: [],
      prefillsAvailable: [
        '21-686C',
        '40-10007',
        '22-1990',
        '22-1990N',
        '22-1990E',
        '22-1995',
        '22-1995S',
        '22-5490',
        '22-5495',
        '22-0993',
        '22-0994',
        'FEEDBACK-TOOL',
        '22-10203',
        '21-526EZ',
        '21-526EZ-BDD',
        '1010ez',
        '21P-530',
        '21P-527EZ',
        '686C-674',
        '20-0996',
        'MDOT'
      ],
      loading: false,
      services: [
        'facilities',
        'hca',
        'edu-benefits',
        'form-save-in-progress',
        'form-prefill',
        'evss-claims',
        'add-person',
        'user-profile',
        'appeals-status',
        'identity-proofed'
      ],
      signIn: {
        serviceName: 'idme',
        accountType: 'N/A'
      },
      multifactor: true,
      veteranStatus: 'NOT_FOUND',
      status: 'OK',
      facilities: [
        {
          facilityId: '648',
          isCerner: false
        }
      ],
      vaPatient: true,
      mhvAccountState: 'NONE'
    }
  },
```

**Comment by mdewey** [comment]
We have multiple addresses and phone numbers. Each of which has no indication of which one is preferred

**Comment by mdewey** [comment]
Unblocked and re-scoping this ticket to just displaying the data with the knowledge that the source might change later,

**Comment by mdewey** [comment]
Created test for the happy path, need to create tests for edge cases 

Working Branch: https://github.com/department-of-veterans-affairs/vets-website/tree/healthcare-12257-display-demographics

**Comment by mdewey** [comment]
Added some tests, need to add a few more, specifically for missing data and submit for review 
working branch: https://github.com/department-of-veterans-affairs/vets-website/tree/healthcare-12257-display-demographics.

**Comment by mdewey** [comment]
In pull request

**Comment by mdewey** [comment]
pull request merged, need to verify in staging

**Comment by mdewey** [comment]
Verified in staging. 

To verify: 
1. go to http://staging.va.gov/
2. Sign in with any user
3. Navigate to https://staging.va.gov/healthcare/questionnaire/
4. Start the form
5. You should see the current user's demographics, being pulled from the user's profile. 

@abuckley3385, Can you verify and tag anyone who needs to verify?

**Comment by abuckley3385** [comment]
@kristenmcconnell  and @abuckley3385 should be the verification of acceptance

**Comment by abuckley3385** [comment]
@mdewey Feedback in [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1599154743088/3e545eb990e506c11327dca2d9cd4b53a8a91687)

**Comment by kristenmcconnell** [comment]
@mdewey I added my current feedback to Amanda's mural. I'm still going to try and find a user with multiple addresses.

**Comment by mdewey** [comment]
@kristenmcconnell  and @abuckley3385  Thanks for the feedback I will wait till a few things are confirmed until I address them :-)

**Comment by kristenmcconnell** [comment]
@mdewey I was able to confirm everything. I added all the final outcomes to the Mural. I also updated the Zeplin file. I'll work with Amanda tomorrow on getting the feature outline up-to-date.

**Comment by kristenmcconnell** [comment]
@mdewey Can you send me a screenshot of a user with multiple addresses, since you can see it and I can't log in as that user in staging? I'll make sure that I review it right away.

**Comment by mdewey** [comment]
![Screen Shot 2020-09-08 at 10 59 08 AM](https://user-images.githubusercontent.com/1793923/92493309-5b8ae480-f1c2-11ea-9ea3-b153fe957443.png)

**Comment by mdewey** [comment]
I got the feedback, will get started on that today

**Comment by kristenmcconnell** [comment]
Thanks for the multiple addresses screenshot. No additional comments beyond what I already sent you.
