### ISSUE TITLE
Update Silent Failure Email Copy

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12265]
## Goal
With the final word on the email copy from Peffy, we can use that text in the email that goes to Veterans when a failure has occurred and they need to be notified in order to take action.

## Tasks
- [x] Take the content from Peggy's [feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11874) and insert it into the ruby mailer file.
- [x] Fire the emailer when there is a failure

## Acceptance Criteria
- [x] The new copy is used in the emails
- [x] The emailer fires as expected
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4709
