### ISSUE TITLE
Migrate Review instances to vfs.va.gov

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#12264]
## Description
Review instances are a key part of the testing experience on Va.gov. Right now the only way to access them is by using the SOCKS proxy. If we migrated them to vfs.va.gov users could access them on the internal Va network. 

## Background/context/resources
review instances are in vetsgov VPCs FYI. 
## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Mirgrate review instances to vfs.va.gov_
- [ ] _Test to confirm they are accessible via CAG or GRE_

## Definition of Done
- [ ] _User can access review instances via CAG or GFE_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
please see #22545 for up-to-date version of this effort.

closing
