### ISSUE TITLE
[BE] Interface for Demographics

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12262]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Demographics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/demographcs.md)

## User Story/ies

* **Use Case:** Veterans need the ability to see the demographic information that is on record to ensure accuracy and be able to verbally with the care team or through a digital edit experience update for the most up to date information.  
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] See demographic feature outline for fields and valuation
- [ ] Create detailed data flow diagram demographic page

- [ ] Pull demographic data for view only from MPI or Profile

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] Data flow and validation review with product for feature capabilities 
- [ ] UI review with FE engineering for validation
- [ ] published to ABC environment.

**Comment by abuckley3385** [comment]
On hold until we verify that authentication gets us all person demographics for the Veteran.  @mdewey @massrb

**Comment by julieadair1** [comment]
@jparker0425 , @dillo - do we still need this?  Can this epic be closed?
