### ISSUE TITLE
[UI] Intro Page

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12279]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Landing Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/landng-page.md)

---
## Tasks
- [x] See landing page feature outline for fields and valuation
- [x] Create detailed mockups and callouts of landing page. Available on [Zeplin](https://zpl.io/bWeqwke) 

## Acceptance Criteria
- [x] Accessibility review
- [x] UI review meeting with product for feature capabilities 
- [x] UI review and callouts meeting with engineering for layout and callouts
- [x] published to [Zeplin](https://zpl.io/bWeqwke). 
- [x] Add final deliverable to product documentation and engineering story.

**Comment by abuckley3385** [comment]
@kristenmcconnell I know its late but i was reviewing our mocks and our intro page is soooooo very long where the user doesn't see what the form is about until they scroll all the way through all the warning messages.  What are your thoughts on moving the _Follow the steps section_ before the _Can I sue this ques.... and How will my personal health info sections._  

I totally realize why you have them first but Im a bit worried/ we need to validate this in user testing that when they see the page for the first time its really not immediately clear why they got a link to fill something out until they read through allot of text to the last section.  Honestly, my guess most would click the first Sign in blue button and not read any of the below as its the first thing it instructs the user to do. 

@mlighdc @LEHigley

**Comment by kristenmcconnell** [comment]
Great idea for our test.
