### ISSUE TITLE
Life insurance rewriting review: Batch 1

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12275]
## Issue Description
As VBA lead, Beth needs to do a final pass on Life Insurance pages.
[life-insurance-rewriting-phase1-v04-08-06-20-master.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5036899/life-insurance-rewriting-phase1-v04-08-06-20-master.docx) 
---
## Tasks: Review these pages
- [x] [Insurance plans](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8548)
- [x] [Calculate your needs](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8439)
- [x] [Uninsurable health issues](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8542)
- [x] [Convert to a commercial policy](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8365)

## Acceptance Criteria
- [x] VBA content lead sign off.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Closing this. My review is complete and after I get the answer to one question about an H1 change, these 4 pages will be ready to go to stakeholders for review.

This was the original H1 for one of these pages: Life insurance with uninsurable health issues
Now it is: Life insurance if you have pre-existing conditions

The URL is: /life-insurance/uninsurable-medical-conditions/

Need to align with Danielle and Mikki on this.
