### ISSUE TITLE
Life Insurance Batch 3:  Staging Review Accessibility Checklist 

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#12271]
Content-only accessibility review of the following batch 2 pages: 

-   Complete required accessibility checklist items for staging review:
    -   [ ]  Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
    -   [ ]  [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
        -   (Manual axe scan):Conduct axe browser scan, and document or address issues found
    -   [ ]  [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
        -   Ensure end-to-end tests - including the axe check, pass
    -   [ ]  [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)
        -   Check color pairing for proper contrast
        -   Check for colorblindness issues
    -   [ ]  [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
        -   Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
        -   Repeat for 300%
        -   Repeat for 400%
    -   [ ]  [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
        -   Navigate all pages and core functionality with keyboard only
    -   [ ]  [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
        -   Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
-   [ ]  Check off items as they are completed

Reference
---------

-   [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
-   [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

How to configure this issue
---------------------------

-   [ ]  Attach to Collab Cycle Epic
-   [ ]  Labeled with Team
