### ISSUE TITLE
[Frontend] Display Landing Page

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12282]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Questionnaire Manager](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## Wireframes
- [Overall wireframes](https://zpl.io/VOOek8j)
- [Unauthenticated landing page](https://zpl.io/aBLymzk)
- [Authenticated landing page](https://zpl.io/bWegKnj)
_Design note: the "How will my personal health information be protected and shared if I use this questionnaire?" section is still not finalized. Story #13786 is finalizing this wording._ 

## User Story/ies

* **Use Case:**  Need to insert
---
## Tasks
- [ ] See landing page feature outline for fields and valuation
- [ ] Create landing page per mockups [link] 

## Acceptance Criteria
- [ ] UI review meeting with product for feature capabilities 
- [ ] UI review and callouts meeting with designer for layout and callouts
- [ ] published to Staging environment.  [link]
- [ ] Meet with Accessibility to review

**Comment by mdewey** [comment]
@abuckley3385 , Image of what we get "for free" as a landing page : 
![screencapture-localhost-3001-healthcare-questionnaire-introduction-2020-08-19-16_04_08](https://user-images.githubusercontent.com/1793923/90684241-db620680-e235-11ea-8f75-f3e83925e6c6.png)

**Comment by mdewey** [comment]
did: 
- content pulled in and HTML are done
- updated a platform feature to better suit our needs concerning the `Respondent burden`, seen in this [pull request](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/441)

need to: 
- styling
- submit PR
- bump version to include the fix when the tooling is updated. 

Questions for @kristenmcconnell / @abuckley3385 
1. For the blue alert box, There is extra verbiage that we are getting out of the box. 
![Screen Shot 2020-09-24 at 4 54 14 PM](https://user-images.githubusercontent.com/1793923/94199308-9cebe700-fe86-11ea-8d3a-77d741446e16.png) and 
2. For `Douglas VA Medical Center` that is the facility name or clinic name? And I assume that comes from the appointment data?
3. For the OBM information, what is our control number and expiration date? 


RISK THAT MIGHT SLOW THIS TICKET: I had to make a change to a platform piece to not duplicate code. That is a pull request.  It shouldn't affect anything, but I am noting here in case I need to eat my words later.

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mdewey 

**Regarding the "Save time..." banner that appears prior to authentication...**
- I see some potential problems for the user if we use the out of the box wording:
--The second bullet with the 60 days information is incorrect in our instance. Our timetables are based on the appointment time/date and have nothing to do with that start of the application.
-- We aren't an application, so I would want to change that wording.
--The note about signing in and not be able to save work that the user completed prior to signing in isn't applicable in our case. The user has to be signed in to start our questionnaire.
From a UX perspective, I believe that we need to make change to this alert.

**Regarding the "You can save this application in progress..." banner that appears after a user is logged in...**
-  I think that out of the box solution is ok, except for the word "application." We aren't an application. However, I don't see it super negatively impacting the user in anyway compared to what I designed in the wireframes. We aren't showing wrong information unlike the other alert.
- Just FYI...the wording that I originally designed does exist in a few places on the site. For example, it is part of the disability form workflow (See image).

![Screen Shot 2020-09-25 at 1.26.36 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/da66ae47-e204-41f8-bb8b-f025c4bfce9f)

**Comment by mdewey** [comment]
- In pull request, waiting for review. 
- Spun off [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14175) to fix some new accessibility issues. 
- Looking to chat with the team about the top alert. 


All items done except for the top alert.

**Comment by mdewey** [comment]
Chatted with platform and there seems to be a way. I am going to try that this afternoon

**Comment by mdewey** [comment]
Updated content, in PR, waiting for checks and reviews.

**Comment by mdewey** [comment]
Merged, waiting for staging deployment

**Comment by mdewey** [comment]
Feedback spun off into [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14387)
