### ISSUE TITLE
Iris Q&As: Define work process

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#12287]
## Issue Description
IRIS includes approximately 928 faqs that will be used to provide Q&A content for the new VA.gov learning center. We need a process that maps to the October launch of the learning center MVP (which includes account and profile as well as "general" Q&As only--no benefit-related ones) and the goal of having all remaining IRIS faq content migrated to VA.gov by the end of 2020. 

## Tasks
- [ ] PW to create draft work plan (Laura) 
- [ ] DEPO to approve work plan (Beth)

## Acceptance Criteria
- [ ] A two-phase work plan (in the form of a Word document and accompanying spreadsheet) is approved by DEPO. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 @RLHecht I added to the issue description above the "general" category. The LC MVP includes all non-benefit Q&As, which is account and profile as well as general/other/we need a good name for these. And if there's an obvious third or fourth category that's not benefit-related, we can add that too. That's part of what the audit should surface.

**Comment by bethpottsVADEPO** [comment]
This and the other issues you create for the rest of the work should be linked to the super epic MVP Learning Center, so I also did that here!
