### ISSUE TITLE
[BE] Reason for Visit data Integration

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12285]
## User Story
**As** a Veteran
**I want** to provide my care team with my Reason for Vist
**So that** I can obtain relevant care for my problem

## Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - This Visit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)

## Tasks
- [ ] See This Visit feature outline for RFV and valuation
- [ ] Retrieve Reason for Visit for display in the front end per mockups [link] 
- [ ] Create an architecture flow diagram of the service connecting to source systems. 

## Acceptance Criteria
- [ ] conduct a data review meeting with the product manager for feature capabilities and get their approval
- [ ] conduct a with the designer and FE engineer regarding the layout and API callouts
- [ ] published to ABC environment.  [link] <- What is this?

**Comment by massrb** [comment]
Laurence Guild  1:36 PM
@Stephen Barrs,  I told Amanda that VAOS has /appointments and /appointment_requests. The appointment requests have a reason4visit field, but she thought it must be the appointments and not the appointment requests or that it's a different field. I have no way of knowing. There doesn't appear to be a different field that it could be. From a different conversation, I had the impression that appointment requests where possibly just another appointment type of record rather than a request for an appointment. If you have any insights into this, please let me know

Stephen Barrs  2:55 PM
Appts and Appt Requests are different.  VAOS Appts are written to VistA, and Appt Requests are written to an Oracle DB in VAMF called VARDB.  I think you are correct in the reason for visit field is only included in the appt request and is used by the scheduling clerk who works the request and makes the actual appointment.  I can logon to VAOS and we can look at the API calls and see what data we get back for appts and appt requests, but dont really have time until tomorrow at 1115 AM ET.

2:57
This is the VAOS backend service API (non FHIR) - https://veteran.mobile.va.gov/var/VeteranAppointmentRequestService/v4/rest/

**Comment by abuckley3385** [comment]
We do not want Appt Request Endpoints. We do want Appts booked endpoints.  See Swagger for what is coming back.

**Comment by massrb** [comment]
I added a blocked dependency because 12404 needs a connection to staging and the task "Retrieve Reason for Visit for display in front end per mockups" needs that staging connection

**Comment by abuckley3385** [comment]
@massrb is there any documentation for this ticket other than needing the staging environment? I was thinking there was test scripts and investigating on what we are calling to get the appt. details.- need to link that here in the acceptance criteria.

**Comment by abuckley3385** [comment]
@massrb See last comment posted on Monday - do you have any details to add?

**Comment by massrb** [comment]
This document explains some technical details about the health quest service which will be updated with more details as needed. Currently everything it does is the same basically as VAOS for appointments. Those aspects of VAOS we have documented 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/HealthQuest%20Service.md

**Comment by abuckley3385** [comment]
thanks for adding this doc to the ticket.  Lets plan on you reviewing this during our engineering sync tomorrow morning. We have asked for the need to diagram this out to show what this service is connecting to.  the descriptions are helpful but Im not clearly understanding and everyone a visual of the systems and service is critical to ensure we are on the same page.  Im adding a task right now for a diagram to be worked on first thing this sprint.

**Comment by abuckley3385** [comment]
@massrb  please add an estimate. tx

**Comment by dillo** [comment]
We think this is duplicating the features which will be built in the feature as a result of resolving the spikes in progress. Moving to the closed lane.

**Comment by abuckley3385** [comment]
@dillo with the above comment can you post what story this is a duplicate of so we can trace where the RFV will be done.
