### ISSUE TITLE
[BE] Data interface for Landing Page

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12283]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Landing Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/landng-page.md)

## User Story/ies

* **Use Case:**  Need to insert
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] See landing page feature outline for fields and valuation
- [ ] Create landing page per mockups [link] 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] data review meeting with product for feature capabilities 
- [ ] data review meeting with designer/FE engineer for layout and callouts
- [ ] published to ABC environment.  [link]
