### ISSUE TITLE
[FE] This Visit Questions

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12281]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - This Visit ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)

## User Story/ies

* **Use Case:** 
---
## Tasks
- [ ] See This Visit feature outline for fields and valuation
- [ ] Follow detailed mockups and callouts of This Visit Questions page [link] 

## Acceptance Criteria
- [ ] UI review meeting with product for feature capabilities 
- [ ] UI review meeting and callouts with designer for layout and callouts
- [ ] published to staging environment, behind a feature flag

**Comment by mdewey** [comment]
Edit was updating the link for feature doc to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md

**Comment by mdewey** [comment]
Completed the first three fields, not pre-filling, created the basic multi-question implementation. 

Got some feedback and direction from Kristen. 

Going to add some tests and then into a PR (Hopefully soon :-) ). 

RISK: Made some changes to the form system to get this to work better. That might cause some slowdown, if it does, I will pull it out to a different ticket/PR .

**Comment by mdewey** [comment]
Unit tests are completed, working through e2e testing. 

side note: really not liking the built-in multi-questions stuff.

**Comment by mdewey** [comment]
Pull request is ready, waiting for reviews. 

Was requested to pull out some quality of life features for the multiple questions. I pulled them out and just submitted the "vanilla" experience of the forms library. 

We should chat about what the next steps are in regards to the multiple questions. We have a choice

A) Work with VSP to update the the existing solution. 
B) Create our own custom solution. 

I have feels, but I want to hear from the team first. 

@abuckley3385 @kristenmcconnell @LEHigley

**Comment by kristenmcconnell** [comment]
I talked to Jennifer Strickland this afternoon and she found an implementation of the list loop that better matches our use case. It is part of filing for disability. On this page, it would just require us to switch where we display our actual question "Do you have any other additional questions...?" I think that it would improve the user experience and be more consistent with another example on the site.

![Screen Shot 2020-09-16 at 12.52.13 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/2f25fc9c-017b-4b02-acd2-0875b862e89e)

![Screen Shot 2020-09-16 at 12.53.14 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/a551a145-a37c-4560-9198-efa3ac86ead5)

To see the example in staging: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction

@mdewey @abuckley3385

**Comment by mdewey** [comment]
Merged in master, waiting for validation in staging 


@kristenmcconnell  Going to spin the feedback into a different ticket.

**Comment by mdewey** [comment]
This is in staging, you can start the form at https://staging.va.gov/healthcare/questionnaire/introduction

@kristenmcconnell  and @abuckley3385  can you review and give feedback?

**Comment by kristenmcconnell** [comment]
All of my feedback for things to change relates to things that we already have tickets for (i.e. wording and the list loop). I think that in the scope of this story, it is good.
