### ISSUE TITLE
[UI] This Visit Questions 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12280]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - This Visit ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)

## User Story/ies

* **Use Case:** 
---
## Tasks
- [x] See This Visit feature outline for fields and valuation
- [x] Create detailed [mockups](https://zpl.io/aBMrDXQ) and callouts of landing page

## Acceptance Criteria
- [x] UI review meeting with product for feature capabilities 
- [x] UI review meeting and callouts with engineering for layout and callouts
- [x] published to [Zeplin](https://zpl.io/VOOek8j)

**Comment by kristenmcconnell** [comment]
@mdewey and @abuckley3385 Final wireframes have been linked to in this story and added to the Feature-This Visit document. https://zpl.io/VOOek8j
