### ISSUE TITLE
[Product] Demographics Feature Outline

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12296]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Demographics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/demographics.md)

## User Story/ies

* **Use Case:** Veterans need the ability to see the demographic information that is on record to ensure accuracy and be able to verbally with the care team or through a digital edit experience update for the most up to date information.  
---
## Tasks
- [x] Create demographic feature outline for fields and valuation
- [ ] Based on mockups  and technical api investigation for demographic page

## Acceptance Criteria
- [ ] UI review with entire team for feature capabilities 
- [ ] published documenation - [Feature - Demographics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/demographcs.md)

**Comment by abuckley3385** [comment]
All the demographics feature outline linked above is ready for review.  I still need updated visuals and info from Mark on the API.  In addition any other feedback or things we should document on this page for future considerations or implementation.  I'll set up time to review this outline and the appt. details to get feedback and signoff.

**Comment by arickalewis1** [comment]
@abuckley3385 just took a look! Who/where is the fourth product feature coming from? 

> 4. All subsequent pages in the questionnaire must show 3 patient identifiers on the screen.
is this part of the va.gov framework?
Name, DOB, Gender
Is this a re-usable framework component

**Comment by abuckley3385** [comment]
From my experience in healthcare - all pages that have health information shown and edited must have patient identifiers on them.  I will need to go look up the policy on this for patient portals if there is a questions on validity.
