### ISSUE TITLE
[FE/BE] Tech Spike - Unauth and Auth Pros and Cons

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12291]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Authentication ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/authentication.md)

## User Story/ies

- insert.
---
## Tasks

- [x] See Authentication feature outline for fields and valuation - This is a Tech investigation Research issue not implementation
- [x] Determine what data we get from logging in that we will not get from the Appointment details.
- [ ] How will we populate a form or data back to clinicians if any specific patient identifiers are missing.
- [x] What can and can't we do with an unauthenticated form? 
- [x] Take into consideration VeText as we want to send the person that scheduled the appt. a link to the unauth and or auth form 

## Acceptance Criteria
- [ ] published findings in technical document that includes an architecure diagram 
- [ ] Team can understand scope and estimate point complexity of both strategies
- [ ] Meeting held to present findings.

**Comment by abuckley3385** [comment]
@mdewey please add an estimate to this issue

**Comment by mdewey** [comment]
Added initial findings and thoughts to [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/auth-vs-unauthed.md)

@massrb and @abuckley3385   I need to you help me answer some questions: 

- Can @massrb confirm that by using VAMF, we can get the details (demographics, the reason for visit, facility, contact information) for an appointment?
- @massrb, Is there a way to use VAMF to listen for new appointments? This could be an endpoint like, "give me all appointments for a facility". If not, what data sources do we have? I know that VeText has ideas around this.
- @abuckley3385 , What level of verification for a user do we need? Who can answer that question?
- @abuckley3385  What data is required to make a new appointment? With or without VAOS.

**Comment by massrb** [comment]
>> Can we confirm that by using VAMF, we can get the details (demographics, the reason for visit, facility, contact information) for an appointment?

The appointment_requests endpoint gives us some of this information. It does not give gender. It gives a phone number, patient id.name, SSN, reasonForVisit, facility information. To get more information such as gender or address, possibly another endpoint would need to be accessed. I will ask Stephen Barrs. What other fields do we need

"patientIdentifier": {
          "uniqueId": "1012845331V153043",
          "assigningAuthority": "ICN"
        },

..

"facility": {
          "name": "CHYSHR-CHEYENNE VAMC",
          "type": "M&ROC",
          "facilityCode": "983",
          "state": "WY",
          "city": "CHEYENNE",
          "address": "2360 EAST PERSHING BLVD",
          "parentSiteCode": "983",
          "objectType": "Facility",
          "link": []
        },


"patient": {
          "displayName": "MORRISON, JUDY",
          "firstName": "JUDY",
          "lastName": "MORRISON",
          "dateOfBirth": "Apr 01, 1953",
          "patientIdentifier": {
            "uniqueId": "1259897978"
          },
          "ssn": "796061976",
          "inpatient": false,
          "textMessagingAllowed": false,
          "id": "1259897978",
          "objectType": "Patient",
          "link": []
        },

       "email": "Vilasini.reddy@va.gov",
        "textMessagingAllowed": false,
        "phoneNumber": "(555) 555-5555",

**Comment by mdewey** [comment]
Meeting summary: 

- For now, we will stick with forcing a user to log in
- More research needs to be done for an unauthenticated experience and what data we can/can not display and where we can write.
