### ISSUE TITLE
[Product] Landing Page feature documentation

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12300]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
[Feature - Questionnaires List ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## User Story/ies

* **Use Case:** Display Visit Intro landing page to kick off the form and let the Veteran know expectations
---
## Tasks
- [X] Create Landing page feature outline for fields and valuation
- [ ] Based on mockups and technical api investigation for Landing page

## Acceptance Criteria
- [ ] UI review with entire team for feature capabilities 
- [ ] published documentation - [Feature - Questionnaire Manager](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)
