### ISSUE TITLE
[Product] This Visit Questions Feature Outline

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12303]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - This Visit Questions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)

## User Story/ies

* **Use Case:** insert
---
## Tasks
- [x] Create This Visit feature outline for fields and valuation
- [x] Based on mockups and technical api investigation for This Visit Fields -

## Acceptance Criteria
- [ ] UI review with entire team for feature capabilities 
- [x] published documentation - [Feature - This Visit ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)
