### ISSUE TITLE
VA.gov Product Dev Wardley Map

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#12327]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] Inventory of inputs to VA.gov product development process
- [ ] Generate wardley map
- [ ] Plan for recs

## Acceptance Criteria
- We understand how individual components of the VA.gov product dev process are relatively optimized
