### ISSUE TITLE
Facility visitation policy - COVID-19 updates

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12337]
## User story

Veterans need to know about changes in VA facility visitation policy during COVID-19.

## Tasks
- [x] Update visitation FAQ content (Peggy)
- [x] Revised per SME feedback (Peggy)
- [x] Send to JTF (Lauren)

## Issue Description
Once FAQ is approved, we need to:
- [ ]  Update the FAQ in drupal
- [ ] Update the chatbot (GH files: https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/master/content/chatbot-copy.md and https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/master/content/chatbot-messages.md)

**Comment by peggygannon** [comment]
@RLHecht per JTF feedback, we are going to keep the original Visitation FAQ, but we need to make this minor edit below to current content: 

Can you update drupal and I will do the chatbot? 

**Can I visit a patient at a Department of Veterans Affairs facility?**
We’re currently following CDC guidelines and limiting visitors for patients receiving care in a VA facility, including a hospital, nursing home, or spinal cord injury and disorder center. Limiting outside visitors helps us protect older Veterans and those who already have health issues.

We do make an exception for Veterans who qualify as a “compassionate case.” ~This means the Veteran is in their last stage of life in a hospice unit and you can only visit that Veteran’s room.~ We know this is difficult for families, but we’re taking these precautions to protect the most vulnerable patients from community spread of the coronavirus.

Learn about the steps we’re taking to protect Veterans in nursing homes.

Visit the CDC website for more tips on stopping community spread.

**Comment by RLHecht** [comment]
@peggygannon These has now been updated in FAQs. Ready for your review.

**Comment by peggygannon** [comment]
Closing this ticket. Chatbot and FAQ updates are live
