### ISSUE TITLE
[Discovery] - Recruit notetakers + schedule debrief sessions for VA.gov sitewide search usability study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12334]
This issue covers supporting tasks needed to get set up for our research study

**Tasks**
- [x]  Recruit notetakers (option perigean, SD members) 
- [x] create a spreadsheet of top of mind questions 
- [x] Share conversation guide with notetakers and Search and discovery team members (.md file in gh to capture notes)
- [x] Have notetakers added to research session calendar invite
- [x] Schedule daily debrief sessions, if helpful to team/researcher
