### ISSUE TITLE
[Discovery] - Topline summary for VA.gov sitewide search usability study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12335]
**Tasks**
Use [this template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/topline-summary-template.md) to create a topline summary for research findings immediately following last session.

**Acceptance criteria**

- [x] Create summary (published in research folder)
 - [x] Share with team (John, Denise, Sam, Megan)
 - [x] Capture team feedback

**Comment by mgleo** [comment]
[Topline Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/research-study-jan-2021/topline-summary.md)
