### ISSUE TITLE
Get SME approval and publish 2018 and 2019 DIC Parents and Spouse and Children rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12347]
## Issue Description
The cloned historic DIC Parent and DIC Spouse and Children rates pages for 2018 and 2019 need to be approved by SMEs and published in order to retire the legacy historic rates pages. The 2020 DIC rates pages also need to have the historic rates pages added as links to the bottom of their pages.

## Tasks
- [x] Send 2018 and 2019 DIC Parents and Spouse and Children rates pages to SMEs (Beth)
- [x] Make any changes to pages based on SME requests (Selina)
- [x] For the group of stacked links at the bottom of the page: Update the 2018 and 2019 links there to point to our new modern page rather than to the legacy page (Selina)
- [x]  Review pages (Randi)
- [x]  Publish pages (Randi)
- [x]  Add pages to left nav (Randi)
- [x]  Validate pages on live site (Selina/Randi)

## Acceptance Criteria
- [x] Historic rates pages live on site and links from other pages to new pages all work
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht The tables we discussed this morning have been moved to the "on or after 1993" section of the page.

- http://preview-prod.vfs.va.gov/preview?nodeId=1012

- http://preview-prod.vfs.va.gov/preview?nodeId=6799

- preview-prod.vfs.va.gov/preview?nodeId=6203

**Comment by RLHecht** [comment]
Thanks @lunascoop @bethpottsVADEPO Can you look at one of these to make sure we moved everything that should be and in the right position? If they are good, they're ready to send to SMEs for next steps. FYSA @MickinSahni

**Comment by bethpottsVADEPO** [comment]
**Update:**

SME approved the spouses and dependents DIC pages (new 2019 and 2018 pages as well as restructuring of 2020 one so the charts are in the right place). Randi will set to go live week of 9/8.

Next step is to send the SME the parents DIC rates pages.

**Comment by RLHecht** [comment]
Just published the 2020, 2019 and 2018 DIC spouses parents pages. Will be live this afternoon and can validate. I'll keep this ticket where it is until we complete the same for the DIC Parents pages.

**Comment by bethpottsVADEPO** [comment]
Validated on the live site! Yay!!! Thanks so much for this work, @lunascoop and @RLHecht. We're getting there.

**Comment by RLHecht** [comment]
**Update:** SME approved parent DIC past rates pages. I will set this to go live for Monday 9/14

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. @bethpottsVADEPO and I have been working through these rates tables a bit more and have landed on the following approach:

$1,900 or less
$2,000 to $2,900
$3,000 to $3,900
$4,000 to $4,900
$5,000 to $5,900
$6,000 to $6,900
$7,000 to $7,900
$8,000 or more

I've updated the first few tables in 2019 (https://prod.cms.va.gov/past-rates-2019-va-dic-rates-for-parents) to show how we need to restructure, and left notes on others in the first batch. Could you and Selina please take this approach through to updating all tables across all sections on this page? Also, could you please double check the numbers in the tables I updated to make sure I didn't introduce any errors?

Then let @bethpottsVADEPO know, and she'll take to SME for feedback before we update the pages for other years. Let us know if you have any questions. And thank you!

**Comment by RLHecht** [comment]
@bethpottsVADEPO I finished updating the tables in the 2019 DIC page: preview-prod.vfs.va.gov/preview?nodeId=6797 and checked Danielle's work. This is ready to send to the stakeholders again.

**Comment by lunascoop** [comment]
@RLHecht cc: @bethpottsVADEPO Here are the Parents DIC rates pages for review.

- 2021 rates: http://preview-prod.vfs.va.gov/preview?nodeId=1013 (previously the 2020 rates page. I just updated the existing "2020 current rates" node since there are legacy redirects tied to this URL.
- 2020 rates: http://preview-prod.vfs.va.gov/preview?nodeId=11013 (cloned page from the current rates page)
- 2019 rates: http://preview-prod.vfs.va.gov/preview?nodeId=6797
- 2018 rates: http://preview-prod.vfs.va.gov/preview?nodeId=6266

**Comment by lunascoop** [comment]
@RLHecht cc: @bethpottsVADEPO Here are the DIC spouses and dependents pages I finished last night (and reviewed again after Angie's latest email):
2021: http://preview-prod.vfs.va.gov/preview?nodeId=1012 (previously the 2020 rates page. I just updated the existing "2020 current rates" node since there are legacy redirects tied to this URL.
2020: http://preview-prod.vfs.va.gov/preview?nodeId=11018 (cloned page from the current rates page)

**Comment by RLHecht** [comment]
All of these DIC rates pages have been reviewed and are ready to publish on Monday (Beth needs to confirm math on two of the 2019 and 2018 Parents rates pages).

Reminders to myself before publishing:
- Update URLs for both 2020 past rates
- Add new past rates pages to left nav

**Comment by bethpottsVADEPO** [comment]
@RLHecht 
**Past rates: 2021**, the example isn't correct--see below. And please add back the link to the 2017 legacy page under the stack of past rates. We can't roll it off the page yet, I realized until stakeholders know that'll happen. So we'll leave it there until that conversation happens. 
Use this:
For example: Let's say you're the eligible parent, living with the Veteran's other parent or a current spouse. For this example, click on the $7,000 or more income range directly above. If you earn $7,153 a year, you make more than $7,100, and less than $7,200. So you would use the $7,200 income limit. Your beginning monthly rate would be $7.

**Past rates: 2020** is correct for the example

**Past rates: 2019** -- Did you check to see if all the rows are in that $7,000 or more chart? Add any rows that are missing and change the example to say: "For example: Let's say you are the eligible parent, living with the Veteran's other parent or a current spouse. For this example, click on the $7,000 or more income range directly above. If you earn $7,053 a year, you make more than $7,000, and less than $7,100. So you would use the $7,100 income limit. Your beginning monthly rate would be $13.

**Past rates: 2018** -- Same as above, please check that all rows are there and add missing ones. 
Change the example to say: 
For example: Let's say you are the eligible parent, living with the Veteran's other parent or a current spouse. For this example, click on the $7,000 or more income range directly above. If you earn $7,053 a year, you make more than $7,000, and less than $7,100. So you would use the $7,100 income limit. Your beginning monthly rate would be $12.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made all the updates above. Could you or @lunascoop please double check my math on 2019 and 2018 because I had to readjust it with the change in the example. These are now all ready to publish once we confirm that there aren't any rows missing in 2019 and 2018.

**Comment by RLHecht** [comment]
These pages have been published. Moving to validate.

**Comment by RLHecht** [comment]
These are all live on the site including the parents DIC rates page. Closing ticket.
