### ISSUE TITLE
[Design] Debt Letters UAT 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#12348]
## Issue Description
_In order to validate that the data we're receiving from the DMC matches what we're expecting on the frontend, we need to conduct UAT _

---
## Tasks
- [x] _Moderate UAT sessions from August 14th - 19th_
- [x] _Complete [the UAT spreadsheet](https://docs.google.com/spreadsheets/d/1lqrm8cMcwwNsaA2WZSyVR2pHkP2J_w8JaMnxM5oN7do/edit#gid=0) to keep track of tested use cases_

## Acceptance Criteria
- [x] _All UAT sessions have been completed_
- [ ] _The base use cases are tested_
- [x] _The UAT spreadsheet is completed_

**Comment by rileyorr** [comment]
Added Brad to this ticket since he'll be sitting in on the sessions in case there's bugs :)

**Comment by rileyorr** [comment]
Since UAT is extended, I'm going to create a separate ticket for the followup sessions so Brad and I have an accurate representation of our completed workload for Sprint 28.

**Comment by bradl3yC** [comment]
> Since UAT is extended, I'm going to create a separate ticket for the followup sessions so Brad and I have an accurate representation of our completed workload for Sprint 28.

🦾
