### ISSUE TITLE
Create remaining parent DIC rates spreadsheet for CSV upload

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12357]
## Issue Description
To maximize efficiency and accuracy, we're asking stakeholders to send us a spreadsheet with the new rates, when they change. On our end, we take the info from each tab and upload the numbers into drupal. There is already one created and stored by Selina for when it's needed, for this page: https://www.va.gov/disability/survivor-dic-rates/

**For awareness**, the SME for this content is Angie Smith (her email address uses her full name: Alfreda Smith). She oversees the two DIC rates categories of survivors and parents, as well as burial allowance. So the burial allowance rates will need updating too on a yearly basis. But the charts are not as straightforward for our burial allowance page: https://www.va.gov/burials-memorials/veterans-burial-allowance/ because there's text in the cells. So I don't think there's a way to use the CSV process for this info, but @lunascoop I'd like to confirm with you on this.

---
## Tasks
- [ ] Create spreadsheet for https://www.va.gov/disability/parent-dic-rates/

## Acceptance Criteria
- [ ] Spreadsheet is complete and ready to share with SME.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Here is the GitHub location of the blank spreadsheet for Parent DIC rates: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/content-team-processes/benefit-rates-updating-process/Parents%20DIC%20rates%20-%20Blank.xlsx
