### ISSUE TITLE
[DISCOVERY] Vet Center Process

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12356]
## High Level User Story
As the Facilities Team, we need to understand the services provided at Vet Centers so we can build pages to display information about them that are meaningful to our users. 

## Goals
- To build a foundation for understanding Vet Centers in preparation for future conversations with SMEs and research sessions with Veterans
- Begin to validate [assumptions](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers#assumptions-and-early-discussions) and [Andy's product plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers#what-we-need-to-do)
   - Consider what we have learned from the VAMCs since Andy's plan was created

## Tasks

- [ ] Learn the current process used to maintain hours/locations.
- [ ] Research software/tool options for use in collecting/maintaining data

## Output
- Document/validate understanding about the process of creating/maintaining information offered at Vet Centers
    - Who creates/maintains this information?
    - What is the process?
    - What technology/software is used/available?
    - What is the frequency for updating? 

- Recommendation for software/tool to use in collecting/maintaining data

Documentation can be housed in this [Discovery folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/discovery)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@lildziner @mpeterz summarizing the goals/expected outcome of the interviews with outreach specialists:
Understanding of the role of a Vet  Center's outreach coordinator
Understanding of the typical "clients" (Veterans, active service members/loved ones) served at Vet Centers and the services those clients typically receive
....with the goal of developing the personas we will use going forward

**Comment by mmiddaugh** [comment]
Information specifically related to the Vet Center data collection process is documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/data-process.md)

**Comment by mmiddaugh** [comment]
At this point in the project, the output intended from this issue was satisfied by outreach specialist discovery.
