### ISSUE TITLE
[DISCOVERY] Vet Center Field 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12355]
## High Level User Story
As the Facilities Team, we need to understand the services provided at Vet Centers so we can build pages to display information about them that are meaningful to our users. 

## Goals
- To build a foundation for understanding Vet Centers in preparation for future conversations with SMEs and research sessions with Veterans
- Begin to validate [assumptions](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers#assumptions-and-early-discussions) and [Andy's product plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers#what-we-need-to-do)
   - Consider what we have learned from the VAMCs since Andy's plan was created

## Tasks
- [ ] Work with vet centers (field) to validate the nuances of the services offered locally
       - Does your vet center offer all of these services?
       - What does your Vet Center call this service?
       - What services does your vet center offer that isn't on the list? 
       - Who can use the service?
       - Is this offered everywhere or location specific?
       - What is the nature of the service? (Is it triage/crisis/assessment and referral? How is it different that what is offered at the VAMC?)
       - What is the overlay of benefits? 

---
### Output
[ ] Continue to document/validate understanding about the services offered at Vet Centers: 

1. What services are offered?
2. Who can receive the services (Veteran? Families of active enlisted?)
3. Why would Veteran/families be looking for the service?
4. Where do the services fit into the journey?

[ ] List of questions (What don't we know?)
[ ] Begin to consider topics for research sessions focused on Vet Center Facility Page content 

Documentation can be housed in this [Discovery folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/discovery)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
At this point in the project, the output intended from this issue was satisfied by outreach specialist discovery.
