### ISSUE TITLE
[Content] Create list of Best of the Best (Examples) for PAOs (From all previous systems) [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12373]
## Story
As a PAO or Web master I need to have best practices and examples of pages I need to create, so I can use them as ideas, templates, and examples for my new pages.

## Resources
[Listing of VISN-4 URLs to review](https://drive.google.com/drive/folders/1Juw7qXdDtzXHm-yPPwaJNUaYZkCFD9B-)
[Listing of VISN-19 URLs to review](https://drive.google.com/drive/folders/1Fi1J24nQ0o_85DW_JkA-ZkYs0tEWr_mL)
[Final page writing WORD docs](https://drive.google.com/drive/folders/1KVjgw4Z56Zm3m1TVTDktpKk9aKVpP9ms)

## TASK
Determine two "Best Examples" from the previous VISN-4 and VISN-19 System pages to provide to PAO for the following pages:
- [x] History Page
- [x] Mission and Vision
- [x] Internship and Fellowship
- [x] Directions / Campus Map
- [x] Volunteer and Donate

## Acceptance Criteria
* provide 2 examples of each of the pages that can be reviewed and determined to be "Good examples" to provide to PAO and webmasters:
- [ ] History Page
- [ ] Mission and Vision
- [ ] Internship and Fellowship
- [ ] Directions / Campus Map
- [ ] Volunteer and Donate
