### ISSUE TITLE
AE-Sprint 28

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12395]
# Priorities
1. Complete Call Center review
2. UAT Go/No-go, submit request if possible
3. High priority staging review updates/fixes
4. Direct Deposit (integration discovery)
5. LIH - Design and Dev tickets
6. Profile 2.0 Bug fixes and tests coverage
7. My VA Rx regression testing

### PM
- [x] [PM] Complete Contact Center Review #11573
- [x] [PM] UAT - Go/No Go #12397

### Design
- [x] Pre-launch - Update relevant parts of the product outline/project folder #10806
- [x] UAT Submit request (if we are able to proceed after UAT go/no-go)
- [x] [IA] [Design] - Update FAQ link labeling #12035
- [x] 508-defect-4 [MOBILE DESIGN] Consider abutting mobile subnav to the top of viewport #11890
- [x] [Design] update profile header when no military info is available #11532

### Build
- [x] [QA]:[FE] Profile 2.0 - Direct Deposit - Fraud Note copy does not match design prototype (High priority) #11489
- [x] 508-defect-1 ❗[SCREENREADER]: On page load, focus MUST be set on the h1 (High Priority) #11907
- [x] 508-defect-2 [SCREENREADER, MOBILE DESIGN] Page MUST contain a level-one heading #11888
- [x] [IA] [FE]-Update FAQ link labeling #12037
- [x] [FE] at some medium-width screen sizes, contact info editing is cramped #11695
- [x] [FE] Update Direct Deposit fraud phone number #12125
- [x] [IA] [FE] Update "change address" link to go directly to personal information section of the profile #12100
- [x] [FE] - Update "learn more about military base addresses' section #12217
- [x] Profile 2.0 - Direct Deposit - Fraud Note copy does not match design prototype #11489 (high priority)
- [x] [Bug] Profile 2.0: Weird alignment of Delete button in Phone number field on mobile #12014
- [x] Do not auto-exit edit mode when an error occurs #12012
- [x] Profile delete confirmation alert bug #12002
- [x] Add tests for SMS appointment reminders checkbox #11982
- [x] Add tests to confirm phone numbers can be deleted #11981
- [ ] Add tests for updating addresses #11983
- [x] Update GA for connected apps #12399
- [x] Profile mobile sub nav sits above main site nav #12346

## Platform
- [x] [PM] Complete Contact Center Review #11573

### Design
- [x] Investigate how banners/alerts work on the logged out homepage and in the navigation #8836
- [x] Plan for LOA3 use cases #10162
- [x] Plan for LOA1 use case #10164

### Dev (If all profile work is done and all LIH ticket from sprint 27)
- [x] [FE] Logged-in homepage: How are we going to build the logged-in homepage? #10256
- [x] [FE] Beta/opt-in technical discovery/scoping #10476

## Direct deposit
- [ ] Determine level of effort for integrating with BGS CH33 DDEFT Services #11545

## My VA Rx issue
- [x] Conduct regression testing on prescription refills widget on My VA dashboard in staging #11836

## Unplanned/QA/508/Bug fixes
- [x] Update 'Cancel' links to buttons #12565
- [X] Update GA for connected apps #12399
- [X] Ensure all requested copy changes are addressed per Staging Review #12677
- [ ] [FE] Add 'I live on a United States military base outside of the country.' checkbox to the Home address #12374
- [x] Under certain conditions, a user can be shown Profile sections in the sub-nav but be blocked from accessing them #12727
