### ISSUE TITLE
Figure out how questionnaire data should flow through our systems to a veterans clinical care team

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#12406]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Patient Generated Data Integration](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/pgd.md)

## User Story/ies

As a Veteran, I want my questionnaire data I enter to be viewable by the clinical care team when I arrive for the visit. 

## Tasks
- [ ] Determine if a fhir client can be used or if endpoints need to be accessed directly
- [ ] Determine how the getCare API would be used and if this negates the need for the fhir client
- [ ] Determine endpoints if applicable
- [ ] Determine authentication requirements

## Acceptance Criteria
- [ ] Document findings
- [ ] Review documented findings

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/fhir%20based%20questions.md

**Comment by abuckley3385** [comment]
@massrb  can you please describe the feature that this ticket goes with?  The FHIR client you are looking into is for what fields/features.  Please link to the EPIC and estimate the ticket.

**Comment by abuckley3385** [comment]
VIPER- intake for product - typical project charter - need work done- getting access to an API. per Stephen should be a convo and potentially not need formal VIPER. With Stephen until he finds out more. Uncertain if PGD and funding (not clear).

**Comment by massrb** [comment]
From our discussion with Stephen Barrs:

There is a VAMF FHIR Sandbox for PGD. It is unrelated to appointments or scheduling

GetCare uses the same PGD that Health Quest would use. We would not go through GetCare. GetCare uses some VAMF endpoints that do not appear to be fhir based but Stephen also said that the PGD sandbox is FHIR based which would presumably means it is a smart fhir API

It is important to note that when VCM connects to the PGD, that connection is based on an encounter ID. Stephen currently is unaware of how the encounter ID is obtained

**Comment by massrb** [comment]
Stephen Barrs is working on setting up a MAP based FHIR PGD sandbox and helped us to understand the dashboard and what he is doing a little better. He created a namespace of 'vagovtest' to work with


https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/meetings/20100831%20-%20Access%20notes.md

**Comment by abuckley3385** [comment]
@massrb please fill out the [external service form ](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/external-service-template.md )needed for Stephen to get Keys for Sandbox

**Comment by massrb** [comment]
External service sheet:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/health%20quest%20service%20external%20service.md

**Comment by massrb** [comment]
Stephen has said that the User Service is running in the PGD sandbox but we have no access keys. I have been studying the user_service code and the JWT docs for MAP

**Comment by massrb** [comment]
I added a task related to getCare research since it was mentioned that Stephen thinks we need to use the getCare API

**Comment by dillo** [comment]
Removing `[Spike]` from the title after moving the card to the Epics column.
