### ISSUE TITLE
Get SME approval and publish 2018 and 2019 historic pension rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12403]
## Issue Description
Cloned 2018 and 2019 pension rates pages need stakeholder approval before publishing. This ticket captures us getting approval, making changes and publishing with correct URLs.

2018 Survivors Pension rates: http://preview-prod.vfs.va.gov/preview?nodeId=6859
2019 Survivors Pension rates: http://preview-prod.vfs.va.gov/preview?nodeId=6861
2018 Veterans Pension rates http://preview-prod.vfs.va.gov/preview?nodeId=6882
2019 Veterans Pension rates http://preview-prod.vfs.va.gov/preview?nodeId=6881
2018 Protected Pension rates http://preview-prod.vfs.va.gov/preview?nodeId=6926
2019 Protected Pension rates http://preview-prod.vfs.va.gov/preview?nodeId=6925

## Tasks
- [x] Confirm correct URLs with Micki (Randi)
- [x] Update content within each to refer to "past rates" instead of "historic/historical rates" (Selina)
- [x] Review content changes (Randi)
- [x] Send 2018 and 2019 Pension rates pages to stakeholder for approval (Beth)
- [x] Make any changes when returned (Selina)
- [x] Add links of these pages to bottom of 2020 Pension rates page (Selina)
- [x] Review, update URL and menu items, and publish pages (Randi)
- [x] Add historic rates pages to left nav (Randi)

## Acceptance Criteria
- [ ] 2018 and 2019 Pension rates pages live on site

**Comment by RLHecht** [comment]
@bethpottsVADEPO These historic rates pages are now all ready to be shared with the stakeholders. Preview links are at the top of the ticket.

**Comment by RLHecht** [comment]
@mnorthuis These are another set of historic rates where we should adjust the URLs to be more consistent with plain language. We haven't set these up yet with any URL since they aren't published. Should these follow the same structure as the disability ones, ending the URL with /past-rates-2018/ for each one? Please let us know. 

@lunascoop I've added a new task above to update the content with "past rates" instead of "historic" like you did throughout the disability pages. Once that's finished I can review again before we send to SMEs for their review.

FYSA @bethpottsVADEPO

**Comment by lunascoop** [comment]
@RLHecht the content on the the pages listed in the description, along with the current 2020 versions listed below have been updated.

-2020 Survivors benefit pension: http://preview-prod.vfs.va.gov/preview?nodeId=589
-2020 VA pension rates: http://preview-prod.vfs.va.gov/preview?nodeId=591
-2020 Protected: http://preview-prod.vfs.va.gov/preview?nodeId=5090

**Comment by mnorthuis** [comment]
@RLHecht yes, they will follow the same pattern.  URLs for these pages will be:


/pension/veterans-pension-rates/past-rates-2019/
/pension/veterans-pension-rates/past-rates-2018/

/pension/survivors-pension-rates/past-rates-2019/
/pension/survivors-pension-rates/past-rates-2018/

/pension/protected-pension-rates/past-rates-2019/
/pension/protected-pension-rates/past-rates-2018/

**Comment by bethpottsVADEPO** [comment]
Update:
SME (Angie) would like to revise the existing content in the first Q&A on the past and current pages for both Veterans Pension and Survivors Pension to this:

**What’s the net worth limit to qualify for a Veterans Pension?**
On October 18, 2018, VA established new requirements for evaluating net worth.  Net worth means the sum of a claimant’s or beneficiary’s assets and annual income. A Veteran’s assets include the assets of the veteran as well as the assets of his or her spouse, if the veteran has a spouse. Example of net worth calculation.  For purposes of this example, presume the net worth limit is $129,094.  A claimant’s assets total $121,000 and annual income is $14,000.  Therefore, adding the claimant’s annual income to assets produces net worth of $135,000.  This amount exceeds the net worth limit of $129,094. 

The net worth limit to qualify for VA Pension as of December 1, 2019, is $129,094.

I followed up on 12/2/20 with this text that adheres to our VA.gov style, voice, and plain language standards (and now waiting to hear back from her):

**What’s the net worth limit to qualify for a Veterans Pension?**

As of December 1, 2020, the net worth limit to qualify for a Veterans Pension is $130,773.

In 2018 we changed the way we assess net worth to make the pension entitlement rules more clear. Net worth includes the total of these amounts for you or your beneficiary:
•	Assets (like a house, car, or investments)
•	Annual income (money earned in a year from a job, including pay, bonuses, commissions, overtime, and tips)
•	Spouse's assets and annual income

You should report all of your net worth or your beneficiary’s net worth. 

Example: If you had $121,000 in assets and $14,000 in annual income, then your net worth would be $135,000. This is more than the net worth limit of $130,773. So you would not qualify for a Veterans Pension.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Is it possible to fit this work in this week?

Angie and I came to agreement on this new content for the Q&A "What's the net worth limit to be eligible for a Veterans pension?" I've made the changes on the 2021 Veterans pension page in drupal. The same changes need to be made on the 2021 Survivors pension page (with a minor edit to account for the fact that this is the survivors not the veterans page--where it says "your and your spouse's assets"). Then this set-worth-limit section needs to be similarly updated on these pages:

/pension/veterans-pension-rates/past-rates-2019/
/pension/veterans-pension-rates/past-rates-2018/

/pension/survivors-pension-rates/past-rates-2019/
/pension/survivors-pension-rates/past-rates-2018/

Here is the new text:

H2: **What’s the net worth limit to be eligible for a Veterans Pension?**

As of December 1, 2020, the net worth limit to be eligible for Veterans Pension benefits is $130,773.

In October 2018, we changed the way we assess net worth to make the pension entitlement rules clearer. Net worth includes your and your spouse’s assets and annual income. When you apply for Veterans Pension benefits, you’ll need to report all of these assets and income.

**Note:** If your child's net worth is more than the net worth limit, we don't consider them to be a dependent when we determine your pension.

Read our definitions below:

H3: **Assets**
Assets include the fair market value of all your real and personal property, minus the amount of any mortgages you may have. “Real property” means any land and buildings you may own. Your personal property assets include any of these items:

- Investments (like stocks and bonds)
- Furniture
- Boats

**Assets don’t include:**

- Your primary residence (the home where you live most or all of the time)
- Your car
- Basic home items like appliances that you wouldn’t take with you if you moved to a new house

[Read more about how we define "assets"](https://www.ecfr.gov/cgi-bin/text-idx?SID=40dea8cb19546b52be72d830a97cf55c&mc=true&node=se38.1.3_1275&rgn=div8)

H3: **Annual income**
Annual income is the money earned in a year from a job or from retirement or annuity payments. It includes any of these:

- Salary or hourly pay
- Bonuses
- Commissions
- Overtime
- Tips

We'll subtract certain expenses from your annual income. We call these applicable deductible expenses. They include:

- Educational expenses
- Medical expenses you’re not reimbursed for

[Read more about how we define “annual income”](https://www.ecfr.gov/cgi-bin/text-idx?SID=194406e7c3f9f3c415c132a29cd9849c&mc=true&node=se38.1.3_1271&rgn=div8)

H3: **An example of net worth and eligibility**

If you had $121,000 in assets and $14,000 in annual income, then your net worth would be $135,000. This is more than the net worth limit of $130,773. So you wouldn’t be eligible for Veterans Pension benefits.

**Comment by RLHecht** [comment]
@bethpottsVADEPO These pages are all updated with the new language and dates. All the nodes I changed are listed here:

Veterans Pension:
preview-prod.vfs.va.gov/preview?nodeId=6882
preview-prod.vfs.va.gov/preview?nodeId=6881
preview-prod.vfs.va.gov/preview?nodeId=11019

Survivors Pension:
preview-prod.vfs.va.gov/preview?nodeId=6859
preview-prod.vfs.va.gov/preview?nodeId=6861
preview-prod.vfs.va.gov/preview?nodeId=11020

**Comment by RLHecht** [comment]
These pages have all been published. Updated 2021 Veterans and Survivors rates pages as well as all historic rates pages 2020-2018. Moving to validate.

**Comment by RLHecht** [comment]
@lunascoop Could you please add links to the past rates pages at the bottom of the 2021 pages like we do on other rates pages? Thanks!

**Comment by RLHecht** [comment]
The last updates to the Survivors Pension have been done and published and the new links to the past rates pages are in there as well. @lunascoop will need to set up the redirects.

**Comment by RLHecht** [comment]
Protected pension rates are now published too!

**Comment by bethpottsVADEPO** [comment]
Final content is live. Closing this ticket. This is where we landed:

**What’s the net worth limit to be eligible for Veterans Pension benefits?**

From December 1, 2020, to November 30, 2021, the net worth limit to be eligible for Veterans Pension benefits is $130,773.
On October 18, 2018, we changed the way we assess net worth to make the pension entitlement rules clearer. Net worth includes your and your spouse’s assets and annual income. When you apply for Veterans Pension benefits, you’ll need to report all of these assets and income.

**Note:** If your child's net worth is more than the net worth limit, we don't consider them to be a dependent when we determine your pension.

Read our definitions below:

**Assets**
Assets include the fair market value of all your real and personal property, minus the amount of any mortgages you may have. “Real property” means any land and buildings you may own. Your personal property assets include any of these items:

* Investments (like stocks and bonds)
* Furniture
* Boats

Assets don’t include:

* Your primary residence (the home where you live most or all of the time)
* Your car
* Basic home items like appliances that you wouldn’t take with you if you moved to a new house

Read more about how we define "assets" LINK

**Annual income**

Annual income is the money earned in a year from a job or from retirement or annuity payments. It includes any of these:

* Salary or hourly pay
* Bonuses
* Commissions
* Overtime
* Tips

We'll subtract certain expenses from your annual income when we assess net worth. We call these applicable deductible expenses. They include:

* Educational expenses
* Medical expenses you’re not reimbursed for

Read more about how we define “annual income” LINK

**Comment by mnorthuis** [comment]
@RLHecht @bethpotts @brianalloyd 

Hi all, just checking in to verify a couple of things:
- I am not able to see the protected pension rates for 2019 and 2018, I can't go directly to the pages and they are not linked int he left nav.  Were these launched as well? 
- The past rates links on the bottom of current rates page for all 3 rate types still appear to link to the legacy pages rather than the new ones
- I noticed that the protected pension rates pages have a "More resources" gray box at the bottom on the current and the past rates pages, none of the other rates pages have this, so not sure if that was intentional, or if its missing from the other pages.

**Comment by RLHecht** [comment]
there was an issue with deployment on Friday but the past rates are now showing live on the site. I've also updated the links t historic rates at the bottom of the current page and that will be live this afternoon (forgot to set to publish on Friday!)
