### ISSUE TITLE
[BE] Service for Retrieving Appointment Details 

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#12404]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Appointment Details ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/appt-details.md)

## User Story/ies
As a Veteran I want to know when completing a questionnaire which appointment I have upcoming that the questionnaire is for so I can put the appropriate information in for the clinicians to focus on during the visit. 

## Tasks
- [x] Determine mock data implementation and create some mock data
- [x] Create Endpoints to mocked data
- [x] Create Spec tests to test endpoints
- [x] a service similar to VAOS to connect to VAMF
- [x] Document the [ABC] service and the fields that are available for view in the front end display and other meta data associated with the booked appointment.

## Acceptance Criteria
- [x] Documentation in Swagger for API 
- [ ] ~Service available for front end to retrieve appointment details and map to the questionnaire front in visual display~ Creating a new ticket for viewing in front end. 
- [x] Pushed to separate code branch to Master
- [x] Code review by platform and approved

**Comment by abuckley3385** [comment]
@massrb what backend service is this for...can you please associate a Epic and give a description of what this back end service is expected to achieve. Also please estimate this ticket.

**Comment by massrb** [comment]
I have coped over some functionality from VAOS and then copied some of the VAOS tests to test these modules. There's a few tests and one of them I had a problem with which fails in faraday for some peculiar reason

 I have been putting this code onto a separate branch

**Comment by massrb** [comment]
In VAOS when you schedule an appointment, you can select 4 options

vds appointments booking note
type (one of 4 options) and reason for visit


"vdsAppointments": [
    {
      "bookingNote"
    } .. ]
"vvsAppointments": []

**Comment by abuckley3385** [comment]
@stephenBarrs we are looking for encounter ID that we can tie to the questionnaire and the appointment that has been booked. @massrb  and @mdewey will followup to review

**Comment by massrb** [comment]
@Stephen Barrs,

 I want to ask about using that staging environment if that is possible or what needs to happen, when etc. I think if I create a certain type of pull request, I can get into the staging environment tho haven't done that. In the settings we have this for VAOS which has no real key in dev as shown here.

va_mobile:
  url: 'https://veteran.apps.va.gov'
  mock: false
  key_path: /fake/client/key/path
  timeout: 15

I added this to my branch, assuming the health quest service is going to have it's own key, unless I should use the same setting that VAOS uses which is the va_mobile setting above ?

hqva_mobile:
  url: 'https://veteran.apps.va.gov'
  mock: false
  key_path: /fake/client/key/path
  timeout: 15

**Comment by massrb** [comment]
I am trying to understand how VAOS stubs the Faraday::Connection in the test environment

**Comment by abuckley3385** [comment]
@massrb  can you please update the pGD and appt. details tickets with the info Stephen provided us this morning in regards to the staging environment and the team member (didn't catch his name) that is working on our access PGD

**Comment by massrb** [comment]
This backend service has 17 of 18 tests that pass. There is a problem with the v1/appointment endpoint in that one of the tests fails. It is not clear if this endpoint however will be useful after speaking with Mark

**Comment by massrb** [comment]
The 18 tests for appointments all pass. I am building a draft pull request on the health quest code branch

**Comment by mchelen-gov** [comment]
slack thread: https://dsva.slack.com/archives/C019EATUKN2/p1598537574004700

**Comment by massrb** [comment]
I added the endpoint health_quest/v0/appointments/:id.  and added tests for that endpoint.
 
 I added tests for the HealthQuest::Middleware::Response::Errors class. This class was basically copied from VAOS but since not everything was copied a situation occurred where there was not enough test coverage for the class so I added specific tests for that class. The reason for this is that if there is not adequate test coverage, then the jenkins build will fail.

**Comment by mchelen-gov** [comment]
@massrb can we import the class from VAOS instead of copying it?

**Comment by massrb** [comment]
@mchelen-gov I think that would mean that we would be calling their code which they didn't want us to do, but I do realize that it is a bit ugly

**Comment by massrb** [comment]
Added a fhir service test so that I have 50 tests, I need to add a few more to make the simple coverage gem have so that jenkins will build

**Comment by mchelen-gov** [comment]
@massrb ah ok, can you point me to the PR on that or any discussions? i don't really understand how metrics would be involved

**Comment by massrb** [comment]
@mchelen-gov, it has been a lot of comments from Kam Kashenas. I am not sure I have all the discussions but these seem to be some of them 

https://dsva.slack.com/archives/CLXEU7Z17/p1596067872239800

https://dsva.slack.com/archives/CLXEU7Z17/p1596067906240700

**Comment by mchelen-gov** [comment]
@massrb ah ok i think i see what they are saying. can you link your current PR or the path for the VAOS module/engine that you are copy+pasting?

**Comment by massrb** [comment]
@mchelen-gov 
https://github.com/department-of-veterans-affairs/vets-api/pull/4784

**Comment by massrb** [comment]
The tests all show to have adequate coverage locally. When I build in jenkins there is an test failut that occurs that does not occur locally which is puzzling but I am trying to figure that out

**Comment by massrb** [comment]
The draft pull request for the service fails in jenkins build because of a danger gem crash. Derek has taken a look at it and it is an unusual problem. I am trying a couple of approaches to create other branches to see if it will build 

https://dsva.slack.com/archives/CBU0KDSB1/p1598968625042600

**Comment by abuckley3385** [comment]
once pull request is working then we are needing 3 keys for access to staging

**Comment by massrb** [comment]
my verizon ISP seems to be intercepting peculiar http urls. I need to call them, it is preventing me from getting to the PR staged instance

https://dsva.slack.com/archives/CBU0KDSB1/p1599081785236600?thread_ts=1599060685.176000&cid=CBU0KDSB1

**Comment by massrb** [comment]
I am able to see the staged PR instance now mentioned previously. 

 I am working on breaking up the commits into separate pull requests because a PR can not be more than 1000 lines of code based on various rules in place. This means breaking up the code into smaller parts but also involves the challenge that each of those parts needs to have at least 90% code coverage. That means pulling in test code which also adds to the line count. Often there are code dependencies, once piece of code can not exist without another piece so other pieces have to be brought in, also increasing the line count. 

 I have the first PR of this type but it has not built because some other code in vets-api unrelated to the health quest code has been failing

**Comment by massrb** [comment]
I created a PR but it needs more work, see: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13160

**Comment by massrb** [comment]
I have a PR currently with 362 lines of code that is inline with what VSP has asked for

**Comment by massrb** [comment]
A PR has been created for the Swagger API documentation so this ticket should be completed

**Comment by massrb** [comment]
Current swagger JSON:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/health-quest-service-swagger.md
