### ISSUE TITLE
Design Intent Collaboration for IRIS (Team Orchid)

### ISSUE THREAD

**Issue by katieho-va** [department-of-veterans-affairs/va.gov-team#12400]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and Team Orchid attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> Team Orchid design intent collaboration meeting completed
- [x] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Sketches
- Lo-fi mockups

## Meeting attendees from Team Orchid
- Designer(s) (required): Rachel Murray rachel.murray@thoughtworks.com
- Product Manager (optional): Ramya Ramesh ramyar@thoughtworks.com
- DEPO design lead (required as applicable): Chante Lantos-Swett chante.lantosswett@va.gov (?)

Additional attendee: (Project Manager) Katie Ho kho@thoughtworks.com

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Crystabel will reach out as needed_

UPDATED: **Tuesday, August 18th 11-11:30am ET**

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

## Design Work

**_Updated in line with some of the feedback from folks on the call in response_**

** BACKGROUND AND SCOPE**

- Here's the original [story](https://app.zenhub.com/workspaces/orchidiris-5f29c3a0250c8f001f1397ac/issues/department-of-veterans-affairs/orchid/45) for reference and the current state for [IRIS](https://iris.custhelp.va.gov/app/ask).  
- As you'll see from the [product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/iris/IRIS-product-brief.md), and we're also incorporating the content from multiple forms (including the GI Bill contact us form and the myHealtheVet form; we're meeting with those teams to get their requirements as well).

**WIREFRAMES**

- Note I'm 'playing the card' as written, and we'll be adding footer elements and breadcrumbs etc. in future stories, and when we determine login I'll go back and add the 'save time by logging' block.  

- We met with Trevor on  8.17.20 and will now be going back and revising these to address accessibility flaws - we'd love any guidance in particular on the best example of a form to use as our North Star.

- Some of the components in Sketch aren't displaying properly (the drop down menus, and one of the required fields is cut off in mobile) so will look into this; I had to use an older copy of Sketch (51.3).   Note in older versions of the Sketch library file there isn't actually the 'templates', which is why I didn't see the mobile type on there.

**DESIGN DECISIONS**

- COPY: 
For type of inquiry, I revised 'service complaint' to 'complaint'.  I'm trying to simplify the content but want to work to ensure this is accurate.
Called Veteran Service Info ‘Branch of service’
Called it ‘I am asking about benefits for…’ (current state) rather than Veteran Role (Self/Family member, etc.) as written in the card.
Used sentence case capitalization as per design standards 
This may be revised to Contact Us rather than Ask a Query - meeting with the IA team to discuss this.

_**ACTIONS: will have larger content discussion with IA team**_

- DROP DOWNS: Alphabetized all drop downs

- SINGLE PAGE: Going with single page for now until we determine all required content - then we'll be able to break this up into form chapters as necessary, as we're still working with stakeholders to understand all required fields.  Getting a wireframe for that started; will be using [this page ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md)on Github as a good starting point for the chunking.  Note I think we're still determining if this is an official form or not

**_ACTIONS: Emily noted this is likely a form and will need the multiple pages in the Form Builder, and we'll do chapters_**

**QUESTIONS**

- CONTENT STRATEGY: do we want to capture biographical first and then inquiry? That would likely be more personal but would love some guidance on content strategy. do we want ‘I want to be contacted by…’ vs. preferred communication?  Need to also think through the Contact Us vs. Ask an Inquiry vs. Submit a question in light of multiple functions

**_ACTIONS: we're meeting with the IA team_**

- DROP DOWN MENUS: should we use ‘select’ or select an option as the text for it? These are going to be the challenge - our stakeholders are going through to cull the options, and currently we have three levels.  In this story we're getting the basics of the form down and will tackle multiple drop downs (compensation then user triggers the next level down) next. Would love Trevor's feedback on what is most accessible.  We'll also have Conditional Drop Down depending on answers - hopefully use the instructions [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines#conditional-form-fields)

**_ACTIONS: Revisit this with Trevor as we build out the logic_**

- FORM BUILDER: I think we're still trying to identify if this is an official form and will need the full number of screens that the [Form Builder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/49d19a3db2cf8ace47c6df06f95b828eaac73463/teams/vsa/design/getting-started-with-va.gov-forms.md) uses (intro, form, review etc.)

**_Actions: Emily: yes, this will need the form builder.  We should revisit the instructions/first page of that flow though - does it make sense to still have it?  For example, on this [form](https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction) for VA Education Benefits, there's a Prepare/Apply/VA Review/Decision process.  For this form, I think it's more 'submit form, get response'.  Does it make sense to have this page still?**

- HEADERS AND CHAPTERS: On the existing [IRIS form](https://iris.custhelp.va.gov/app/ask) there are lot of headers ('what is your question', 'preferred response type' etc.).  I'd like to remove some of them, but am uncertain of the accessibility requirements for headers  - how many is too many. If we have chapter titles (the 1 of 2) can we use those in lieu of actual H2s asking preferred response type?

**_ACTIONS: Trevor: yes, need headers for screenreaders.  @1Copenut do we have a idea of which headers we need for screen readers? The current state on IRIS seems to have one for every bit of content ('Preferred Response Type' - should I am to have more than less?)  _**

- MOBILE: what are good standards for typography in particular for mobile? Trying to understand the standards in light of this page about [typography](https://github.com/department-of-veterans-affairs/va.gov-team/blob/eb501542f3b13c794b4483eb6c8b7359069b027b/teams/vsa/design/patternLibraryInitiatives/headings.md).  I've not focused on the accuracy of the header text sizes for this draft.

**_ACTIONS: Emily: see Sketch file_**

- REQUIRED FIELDS: We're going with current state for now; in discussion with the MyHealtheVet folks they may have a different set of required, so this is still a draft.

**_ACTIONS: none at this time_**

- SIZE OF TEXT BOX: no component in Sketch library for it.  Any examples of larger text boxes to use? I've left space to the right of the box because we may need the explainer text ('no PII in here' text)

**_ACTIONS: Will revisit when we play the story with help_**

- SKETCH FILE: What from the design pattern library in Sketch has been tested (i.e. do we need to test for color blindness etc.via get stark if the VA team has already done it, and don’t break any patterns? What for screenreaders etc.?)

TBD - believe I read it's accessible.

- TYPE AHEAD: Can we do type ahead/autosuggest for countries? (i.e. Dropdown with autosuggest?)

**_ACTIONS: on roadmap - will have US be first choice on top by default; added to card_**

**WIREFRAMES**

![Story_45_IRIS_ask_a_query](https://user-images.githubusercontent.com/68248352/90278362-593ca100-de35-11ea-8351-399428f7dd45.png)

![Story_45_IRIS_ask_a_query_mobile](https://user-images.githubusercontent.com/68248352/90278375-5cd02800-de35-11ea-86b3-49985a23be72.png)

![Story_#45_drop_down_options](https://user-images.githubusercontent.com/68248352/90536408-05d69580-e14a-11ea-83e6-145a534ea113.png)

**Comment by CrystabelReiter** [comment]
Scheduled August 17 3:30-4 pm. Thanks!

**Comment by katieho-va** [comment]
@CrystabelReiter Sorry, just updated to Tuesday timeslot if that works instead?

**Comment by CrystabelReiter** [comment]
that still works! @katieho-va I'll update

**Comment by katieho-va** [comment]
@murrayra to add designs here, after internal ThoughtWorks team review

**Comment by murrayra** [comment]
Will also add a few notes on the design decisions that shaped the creation of the wireframes, and specifically any questions or areas where we'd love some feedback.

**Comment by murrayra** [comment]
Hi Everyone,

Here's the first story for IRIS. Here's the original [story](https://app.zenhub.com/workspaces/orchidiris-5f29c3a0250c8f001f1397ac/issues/department-of-veterans-affairs/orchid/45) for reference.

**WIREFRAMES**

- Going with single page for now until we determine all required content - then we'll be able to break this up into form chapters as necessary, as we're still working with stakeholders to understand all required fields
- Some of the components in Sketch aren't displaying properly (the drop down menus) so will look into this.  
- Note that there's a document on the TW Google drive that has some questions we should take into the Design Intent meeting internally.

**DESIGN DECISIONS**

- Alphabetized all drop downs
- For type of inquiry, I revised service complaint to complaint
- Called Veteran Service Info ‘Branch of service’
- Called it ‘I am asking about benefits for…’ (current state) rather than Veteran Role (Self/Family member, 	etc.) 
- Used sentence case capitalization as per design standards 
- Going with single form without breaking up into chapters yet

**QUESTIONS**

- Size of text box field - no component in Sketch library for it.  Any examples of larger text boxes to use? I've left space to the right of the box because we may need the explainer text ('no PII in here' text)
- Content strategy: - do we we want ‘I want to be contacted by…’ vs. preferred communication?  Need to also think through the Contact Us vs. Ask an Inquiry vs. Submit a question in light of multiple functions - we're meeting with the IA team as well
- Drop down menus: should we use ‘select’ or select an option? Drop downs are going to be the challenge - our stakeholders are going through to cull the options, but wonder if we can do type ahead for countries, and possible multiple drop downs (compensation then triggers a sub menu or something)

**WIREFRAMES**

![Story_45_IRIS_ask_a_query.png](https://images.zenhubusercontent.com/5f0f19227da4a53e35057f6e/6bc6ad34-5dcc-41c9-bbe3-b5c6cb4e2966)

![Story_45_IRIS_ask_a_query_mobile.png](https://images.zenhubusercontent.com/5f0f19227da4a53e35057f6e/9086defa-1ab4-4c00-a0de-34c18317a149)

![Story_#45_drop_down_options.png](https://images.zenhubusercontent.com/5f0f19227da4a53e35057f6e/7c217891-2951-4326-99ae-e3540565dde6)

Look forward to meeting and working with you!

- Rachel
