### ISSUE TITLE
Content Revisions for CH31's Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12409]
## Goal 
Given feedback, we need to implement the latest content changes for CH31 so the feature is copy complete and ready to go.

## Tasks
- [x] Take the [recommendations](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11434) ([Crystabel's](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11440), [Mikki's](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11441) as well) and update the features' prototypes

## Acceptance Criteria
- [x] The prototypes are updated with the latest recommendations, as needed

### Next steps
- Peggy's changes to be implemented

**Comment by sporeboy** [comment]
Reviewed all feedback for CH31 ahead of Content review. Design punchlist created:

Mikki IA/#11441
- [ ] Must review intent of wizard and placement on intro
- [ ] Consider removing the final question on the wizard: do you want VRE.

Jennifer 508/#11434
- [ ] Make label and input clickable in prototypes
- [ ] Also all other form inputs
- [ ] Do not repeat accordion heading on review screen
- [ ] Must confirm email address
- [ ] Increase size of phone number inputs
- [ ]  Link spacing on landing page must be 24px
- [ ]  Consider styling radio buttons as buttons for mobile and small viewports
- [ ]  Eliminate all caps in static name

Crystabel design/#11440
- [ ]  On landing screen, the primary button label should be sentence case
- [ ]  For the success background alert, a checkmark icon is commonly used if you’re using a green background alert
- [ ]  For the address portion of the form, the focus state stays on Street after clicking other form fields
- [ ]  Submit button label on the review page is Source Sans 14px instead of 16px
- [ ]  The "continue" button on the additional info page is Source Sans 14px instead of 16px
- [ ]  On the additional info page, the address that appears has Line 2 repeated instead of Line 3 after Line 2

Some of these items are outside CH31 scope, or may be too difficult to execute with the current prototyping tool, but I will attempt to address everything in the lists.

**Comment by sporeboy** [comment]
Design review feedback completed. Content feedback pending.
