### ISSUE TITLE
Research plan for vaccination service

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12405]
## Issue Description
How might we support Veterans searching for vaccination services?

## Goals of research
Learn the Veteran mental models for vaccination within the health service taxonomy, primarily for VAMCs
- Where in the VHA taxonomy do Veterans expect vaccination services to be found?
  - For example, do they expect to find it under primary care, with pharmacy (related to "medication"), under a particular specialty; or within a taxon named "Vaccination" (or similar)? 
- What words do Veterans use when searching for vaccination-related services? 

What words do Veterans use when searching - such as
- Vaccine/vaccination  vs immunization vs shot 
- Flu or influenza 
- Coronavirus vs COVID

- Does the expectation change based on the type of vaccination?
   - Age-based (such as shingles or pneumococcal)
   - Risk-based (such as pneumococcal)
   - Seasonal flu
   - COVID vaccination/testing

May use card sort to understand where Veterans expect vaccination services to be categorized

Reference [Health services](https://www.va.gov/pittsburgh-health-care/health-services/) listing on the Pittsburgh site 
<details>
<summary> Screenshot of page </summary>

![image](https://user-images.githubusercontent.com/55411834/100786027-c49f8400-33ce-11eb-9326-03f89565a4dd.png)

</details>

---
## Tasks
- [x] Create a research plan for learning the Veteran mental models for vaccination-related services

## Acceptance Criteria
- [x] Approved research plan ready for recruitment
- [x] Resource available to support research (Optimal sort, for example)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrisdlogan** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vaccination-taxonomy/research-plan.md
