### ISSUE TITLE
Create prototype for search/appoint representative (VSO) 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12419]
### Background
We need to review and refine the current Search Rep mockups. A functioning prototype is needed for usability testing and capturing latest design/508/IA/content feedback.

### Considerations
Prototype will need to be built using UXPin. Mobile layout should be used.

### Tasks
- [x] Incorporate latest design feedback
- [x] Implement 508 feedback
- [x] Address IA and content feedback
- [x] Ensure latest design elements are implemented
- [x] Build flow functionality to accommodate testing

## Acceptance Criteria
- [x] Prototype has been created

**Comment by sporeboy** [comment]
Prototype in-progress here: https://preview.uxpin.com/61c3ebf323d3662f44e38a8cbb28a7d326533703#/pages/140612526

**Comment by sporeboy** [comment]
Search Rep tool will leverage the VA.gov form system to step through the feature. The screens will be revamped (nearly) 1-for-1 from the existing layout to the form system equivalent:

Adobe XD reference: https://xd.adobe.com/view/3d1a7b7d-3240-44cb-9a19-45408805b48c-6849/

- Landing page lead-in (for flow)
- Introduction
- Search parameters
- Search results

**Comment by candy-gcio** [comment]
UXPin prototype: https://preview.uxpin.com/61c3ebf323d3662f44e38a8cbb28a7d326533703#/pages/140612526

Complete:
- Basic page layouts
- Interactions to link from page to page

TBD:
- Incorporate variables 
- Some text needs to be updated (anything that references online form submission)
- Alt design removing some form elements
