### ISSUE TITLE
Content Revisions for CH36's Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12410]
## Goal 
Given feedback, we need to implement the latest content changes for CH31 so the feature is copy complete and ready to go.

## Tasks
- [x] Take the [recommendations](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11794) and update the features' prototypes

## Acceptance Criteria
- [x] The prototypes are updated with the latest recommendations
- [x] Prototypes are shared with FE

**Comment by sporeboy** [comment]
Starting point for layout revisions to 28-8832

From Jennifer S. 508 feedback/#11434
- [ ] Make label and input clickable in prototypes
- [ ] Also all other form inputs
- [ ] Must confirm email address
- [ ] Increase size of phone number input
- [ ] Eliminate all caps in static name

**Comment by jason-gcio** [comment]
Jim, is this ready to be closed or would you like to leave it open for a little longer? It looks like you might add some steps shortly...
