### ISSUE TITLE
Content Revisions for View Payment's Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12411]
## Goal 
Given feedback, we need to implement the latest content changes for CH31 so the feature is copy complete and ready to go.

## Tasks
- [x] Take the [recommendations](#) and update the features' prototypes
- [x] Update the changelog in {feature-name}/research-design

## Acceptance Criteria
- [x] The prototypes are updated with the latest recommendations, as needed
- [x] Prototypes are shared with FE

**Comment by sporeboy** [comment]
Peggy's feedback can be found in the comment section: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11794

**Comment by sporeboy** [comment]
XD mocks updated here: https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/

**Comment by sporeboy** [comment]
UXPin prototype updated here: https://preview.uxpin.com/546893e0b210374a0734240e0ca9fccc2e02ed11#/pages/129039987
