### ISSUE TITLE
Create Schema File for Chapter 36 in vets-json-schema

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12424]
# Background
Now that we have created all the fields in the Chapter 36 form we need to copy the schema for those fields into `vets-json-schema`.

## Considerations
- Meet with BE as well

## Tasks
- [x] Build out for fields for chapter 36 form in `vets-json-schema`
- [x] Bump version number in package.json in `vets-json-schema`
- [x] Update commit hash in package.json in `vets-website`
- [x] change the commit hash in `vets-website`
- [x] Run `bundle update vets_json_schema` in `vets-api`
- [x] Submit PR to `vets-api` for review

## Acceptance Criteria
- [x] The full schema for chapter 36 has been created in the `vets-json-schema` repo
- [x] The commit hash in `vets-website` has been updated
- [x] The `vets-api` repo has been updated accordingly
- [x] PRs have been submitted for review
