### ISSUE TITLE
Write Unit Test for Static Veterans Information Page (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12421]
## Background
In order to make sure that the Static Veterans Information page behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Additional Information page.

## Tasks
- [ ] Set up test file
- [ ] Write unit tests for Static Veterans Information page
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The Additional Information page is unit tested it 80% coverage
- [ ] A PR has been submitted for review

**Comment by micahchiang** [comment]
Including #12471 in the PR that will go out for this ticket.
