### ISSUE TITLE
Introduce New Communication Preferences into `vets-json-schema` for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12420]
# Background
Now that we have created the pages and fields for the Chapter 31 form we need to move all of the schemas into the `vets-json-schema` repo.

(A new section of the form that indicates how the Veteran would like to be contacted.)

## Tasks
- [ ] Add new fields to `vets-json-schema` for chapter 31
- [ ] Bump the version number for chapter 31 in `vets-json-schema`
- [ ] Add unit tests for schemas in `vets-json-schema` 
- [ ] Submit a PR in `vets-json-schema`
- [ ] Import the schema from `vets-json-schema` into `vets-website`
- [ ] Update `vets-api` bundle
- [ ] Submit PR in `vets-api`

## Acceptance Criteria
- [ ] The full schema for Chapter 31 has been moved into `vets-json-schema`
- [ ] The schema from `vets-json-schema` is being used inside `vets-website`
- [ ] Three PRs have been created for review
