### ISSUE TITLE
[MINI] Dependency Claims Internal Testing

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12425]
## Background
Given that all the PRs are complete, BE needs to do internal testing to see how and where anything needs to be adjusted for the submission process.

## Tasks
- [x] Discover and implement existing codebase to reflect the requirements of RBPS
  - [x] Split 686 and 674 to separate forms upon submission
    - [x] Split the model
    - [x] Split higher ed services 
    - [x] Split the job to submit
- [x] Test initial workflows to find out where RBPS is not able to accept a submission automatically
  - [x] VNP table updates
  - [x] Adding required fields per BGS 
  - [x] Add SSN and DOB
  - [x] Add regional office lookup by zip code
  - [x] Use a second regional office call to now get the location ID (updated call per BGS)
  - [x] Add DEPCHG to update calls
  - [x] Add Participant ID to form submission
  - [x] Add Station of Jurisdiction to 686 Submission
  - [x] Timezone date conversion issue (from last "report a divorce" workflow)
  - [x] Check if adjustment is needed (from last "add a spouse" workflow)
- [x] Discover through small group testing what other requirements BGS needs
- [x] Establish a workflow to be accepted in to RBPS automatically
- [ ] Continue BGS partner testing each workflow
- [x] Then test using Sidekiq jobs on FE
- [ ] Double check for confirmation within VBMS

## Acceptance Criteria
- [ ] Testing has provided a list of next steps
- [ ] Results of testing have been shared with the team
- [ ] Outcomes for testing have been codified in GH

**Comment by kathleencrawford** [comment]
Testing is ongoing but so far these PRs have been submitted and merged based on results from testing:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/12692

https://github.com/department-of-veterans-affairs/va.gov-team/issues/12730

I will be creating another ticket for updating location ID based on veteran's postal code.  

We are still waiting for some feedback from BGS related to these fields: `vnpProcTypeCd` and `vnpPtcpntVetId`.

**Comment by jason-gcio** [comment]
As of today, the latest change to the Regional Office that BGS requires has resulted in this ticket to be drafted, groomed and made ready for pulling into Sprint 36
**Add SOJ to 686 Submission:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/16696
