### ISSUE TITLE
Vet Center Taxonomy - research plan

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12441]
## Issue Description
We need to validate our proposed Vet Center service taxonomy to confirm the descriptions and language used for the MVP pages align with Veterans 

<details>
<summary> **Taxonomy structure** </summary>

- Service name: Mental health care (National)
- Patient-friendly name: Behavioral counseling  (National)
- Common conditions:  (National)
- Description: 
If you're struggling with issues like depression, grief, anger, or trauma, we offer counseling and other support. All Vet Centers offer same-day help. 
At (Vet Center) we offer individual and group counseling. We also provide referral to VA counseling resources and therapy resources in your community. Specialty care at our center includes:  (National)
- Bullet points for specific local offerings (Local)

</details>

## Goal of research
Validate new taxon accordions (areas in need of Veteran input) with a focus on the national content:
( Local bullets for "how ABC Vet Center provides this service" are not within scope.)
- Name of service
- Veteran facing name
- Common conditions
- Intro description 
Ensure our assumptions about content align with Veteran expectations (without seeding them by revealing content)
Gather additional "words" as expressed by Veterans

## Hypothesis
Veterans understand what to expect within 

- Whole health 
- Returning Service member
- Education and training
- Couples/Family counseling
- Veteran connections

## Questions 
Do the service names and descriptions make sense?
Do they represent the Veteran expectation of services accurately/completely? 

---
## Tasks
- [x] Determine a method for validating the national content areas of Vet Center service taxonomy with Veterans (and service members and families of enlisted, if possible). Target participation with general population Veterans (they do not need to have been Vet Center clients or previous participants of mental health counseling services)

## Acceptance Criteria
- [ ] Approved research plan and conversation guide to recruit ~10-15 Vet Center clients representing a mix of urban/rural, Vietnam/GWOT eras, male/female

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as a duplicate to [#13780](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13780)

**Comment by lildziner** [comment]
[Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/services-taxonomy/taxonomy-study/research-plan.md)
OptimalSort [study layout in Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1615484762327/0a1d9d3a4e906166357a07521fd3d3eb958f4567) in lieu of conversation guide reviewed by Lauryl Z and Lauren A.
