### ISSUE TITLE
Analytics KPI dashboard request for Profile 2.0 (Authenticated Experience)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12449]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [x] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [x] Your KPIs are clearly linked back to Veteran outcomes
- [x] Link your KPIs below (KPIs should be in your Product Outline)
- [x] Submit this ticket as an epic
- [x] Add your team label to follow progress

### KPIs

For the profile 2.0 project, our [OKRs and KPIs for this project are documented here](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=666840712).

**OKR: Reduce the amount of searches for direct deposit by 20%.**

In 6 months, of ~13K searches for "direct deposit", ~2K are initiated from the account page, and ~1400 are initiated from the profile itself, even though the feature lives on this page. We can expect those search numbers to go down now that we are consolidating Profile and Account and have "Direct deposit" in the profile side nav.

- **KPI**: Overall searches for "direct deposit"
- **KPI**: Searches for "direct deposit" initiated from the profile
- **KPI**: Searches initiated from the profile

**OKR: Reduce % of users who visit /account before updating direct deposit from about 33% to 0.**

Right now, we can see that about 1/3 of users who update their direct deposit information go to the account page before doing so. By combining the profile and account pages, and therefore removing "Account" from the navigation, we can simplify the path to this feature and reduce the number of users who make an extra step before going to the profile from 1/3 of users to 0.

- **KPI**: Pages visited before the profile.

**OKR: Reduce time on the profile by 10% (about 20 seconds based on first six months of 2020).**

Note: This will need to consider the new URL structure.

With improvements like the new side nav and tightened up visual design (which should both result in less scrolling), we think that users will need to spend less time in the profile overall to do the tasks they came to do. However, should we see a reduction in time spent on the profile, we should make sure we do not see markedly fewer interactions with sections like Contact information and Direct deposit. 

- **KPI**: Time spent on profile

**OKR: Increase average user satisfaction (ForeSee score) from ~2.4 to 3.4.**

Currently, the profile satisfaction score is pretty low. My hypothesis is that people give it a bad rating if they get there and can't find what they are looking for. With the combination of combining profile and account, updating the design, and adding a side nav, we are hopeful we can raise the average Foresee rating by about a point. We think we could raise this score even higher with the addition of features users may expect to see in the profile (eg. DD214).

- **KPI**: Foresee score

**One more thing...**

Of note — these are the KPIs for the Profile 2.0 redesign only, not the entire profile and all of its features. We are still tracking the metrics for individual profile features, but since most of the features in the profile are not changing beyond a visual redesign for this project, they are not reflected in the OKRs and KPIs for this project. The OKRs and KPIs listed above aim to track the impact of the Profile 2.0 work only, not the overall health of all the profile features. Let me know if you have any questions about this.

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [x] Groom analytics for technical feasibility
    - [x] Document data sources for each metric
    - [x] Document unavailable vs. available metrics
- [x] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [x] Draft dashboard on Domo
- [x] Pipe available metrics to Domo
- [x] Add appropriate team members to dashboard

## Definition of Done
- [x] KPIs have been groomed and connected to Domo
- [x] Dashboard has been shared back with the VFS team

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 for awareness

**Comment by Samara-Strauss** [comment]
Closing. This dashboard was handed off last week.
