### ISSUE TITLE
Vet Center data/artifact request

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12442]
## Issue Description
There may be data or other artifacts which can be collected by the Vet Centers while we develop the Vet Center service taxonomy. Some items may be time-sensitive, based on budget or weather (for building photography, for example). 

---
## Tasks
- [ ] Determine what information can be collected during this phase of the process

## Acceptance Criteria
- [ ] List of artifacts with relevant details (ie: photo size, etc) to be provided to Jessica and team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@davidconlon based on my review of the VAMC pages, I see a few items which could be requested:

- Location and contact information
- Photo of location
- Parking info
- Transportation services (DAV vans, shuttle services or other local transportation options)
- Campus/Bldg map, as appropriate
- Visitor policies
- Recurrent events?

**Comment by mmiddaugh** [comment]
Recommendations from forthcoming user guide per Kevin Walsh:

Users provide image which is 1000 pixels or wider, in jpg or png.
Image can be full color
Users are able to specify the crop in the CMS, but if they don’t, the CMS will crop it for them. 

The front end uses the 7:2 aspect ratio, displays the image at 1050 pixels and applies the blue treatment with CSS.

**Comment by mmiddaugh** [comment]
User feedback from Ryan Stubblebein: 

> The sizes of cropping are not intuitive. 
> 7:2 ratios are not a normal ratio and creates major issues for us to identify best imaging.

We should consider explaining the rationale for the requested specification to users who might find the requests weird or difficult (In the case of system photos, the aspect ratio has been chosen to get our content higher on the page. Other images are closer to the 2:1 ratio.)

There are no standards for images on the web as far as ratios go, per Ryan T.

**Comment by mmiddaugh** [comment]
Low hanging fruit is Location and Contact information. Will follow up with Jessica or during outreach specialist interviews to learn if any of this information has been gathered for the creation of brochures (as referenced in the Brand Analysis report). We may be able to tap into that work without going back to the individual Vet Centers.
