### ISSUE TITLE
[FE] Create Submission Confirmation Page

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12453]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Feature: PGD Data Integration)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/pgd.md)

## User Story

 

---
## Tasks
- [x] See Feature: PGD Data Integration feature outline for capabilities and feature specifications.
- [x] Update PGD Data Integration feature outline with technical specifications (ie. API's, Analytics, Implementation details.etc)
- [x] Create Confirmation page per mockup/prototype (mobile and desktop) _(link to design in feature outline)_ 
- [x] Accessibility and Security considerations per feature outing
- [x] Create Testing plan
- [x] Analytics to apply per feature outline

## Acceptance Criteria

_Validation = comment in ticket acknowledged review_
- [x] Validation of testing plan with UT
- [x] Page shows successful and error messages for saving of the form
- [ ] UI review meeting scheduled with product for feature capabilities 
	- [ ] Validation to mark complete from Product 
- [ ] UI review  meeting scheduled with design for layout and callouts
	- [ ] 	Validation to mark complete from Product 
- [ ] Published to [ABC] environment, behind a feature flag 
	- [ ] Validation to mark complete from Product and Design they can access with test user

**Comment by mdewey** [comment]
This is the current submission confirmation page. As you can see , its pretty much a blank canvas for us. 

![screencapture-localhost-3001-healthcare-questionnaire-confirmation-2020-08-24-16_39_38](https://user-images.githubusercontent.com/1793923/91094211-7ab53e00-e628-11ea-90c9-e421a03f37f4.png)

**Comment by abuckley3385** [comment]
@kristen - its in blocked right now but should be pulled in @mdewey  did we miss this one?

**Comment by mdewey** [comment]
HTML and CSS are complete, Dummy Endpoint is created and will be turned over to BE.

**Comment by mdewey** [comment]
UI is complete, accessibility checks are passing in axe, need to add unit tests and PR

**Comment by mdewey** [comment]
[Pull request is created](https://github.com/department-of-veterans-affairs/vets-website/pull/14490), need to created unit tests

**Comment by kristenmcconnell** [comment]
UX review comments and questions.
![Confirmation page comments.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9723e1a7-079d-45cd-961f-ab759988029d)

**Comment by mdewey** [comment]
I should be able to fix that spacing no problem. 

@kristenmcconnell  Can you confirm that the name is still missing? I just tried it and the name shows up for me. 
![Screen Shot 2020-10-13 at 4 47 53 PM](https://user-images.githubusercontent.com/1793923/95914531-d9b74980-0d73-11eb-9871-a776aea7329e.png)

**Comment by kristenmcconnell** [comment]
I also see the Veteran's name now.

**Comment by mdewey** [comment]
In PR, waiting for approval and checks to run

**Comment by mdewey** [comment]
@abuckley3385  and @kristenmcconnell  The latest updates are [in staging.](https://staging.va.gov/healthcare/questionnaire)

**Comment by kristenmcconnell** [comment]
@mdewey Its good on my end.

**Comment by abuckley3385** [comment]
The header is getting the orange focus and this doesn't' happen on the rest of our pages can this be removed and I'd assume it will be on our buttons once we add them to the page?
![image](https://user-images.githubusercontent.com/65729813/96306702-cac7d580-0fc5-11eb-84b8-f503a0fdac61.png)

**Comment by mdewey** [comment]
Yes! Once we get other buttons on the page the focus still be on them.
