### ISSUE TITLE
[Product] Saving Questionnaire as PGD

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12454]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - PGD Integration]()

## User Story/ies

---
## Tasks
- [ ] Create PGD feature outline for fields and valuation
- [ ] Based on mockups  and technical api investigation for pgd page

## Acceptance Criteria
- [ ] UI review with entire team for feature capabilities 
- [ ] published documentation - [Feature - PGD Integration](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/demographcs.md)
