### ISSUE TITLE
Automate list of facilities offering services as displayed at system level

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12462]
## Issue Description

A list of facilities offering a particular health service is displayed at the system level. This list may change over time and should be automated for accuracy and ease of maintenance. 

<details>

<summary> For example </summary>
![image.png]
(https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c577842f-e15b-4baa-8c16-6e8b04a9a108)

</details>
---
## Tasks
- [ ] Facilities front end team: TBD
- [ ] CMS team: TBD

## Acceptance Criteria
- [ ] If `Facility X` offers `Service Y`, then `Facility X` **should be** included in the list of facilities offering `Service Y` as displayed at the system level (i.e.: https://www.va.gov/pittsburgh-health-care/health-services/)
- [ ] If `Facility X` **no longe**r offers `Service Y`, then `Facility X` should **not** be included in the list of facilities offering `Service Y` as displayed at the system level. (i.e.: https://www.va.gov/pittsburgh-health-care/health-services/)
- [ ] If `Facility X` offers `Service Y`, then the health service content **should be** included on `Facility X` 's page. (i.e: https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/)
- [ ] If `Facility X` **no longer** offers `Service Y`, then the health service content should **not** be included on `Facility X` 's page. (i.e: https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
