### ISSUE TITLE
Create CH31 PDF for Eventual Submission to VBMS

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12463]
## Background
The VRE CH31 feature does not have a backend like some other features where structured data is being sent to a lower environment or system for data processing; Central Mail acts like a PDF depository.  Once a pdf has been created, it can then be sent to Central Mail likely accompanied by certain requisite data pieces that help identify who the PDF belongs to and its final destination.  These metadata will most likely be in another PR.

## Goal
We need to ensure that the PDF is created (from form data) first so it can be later sent to Central Mail (in another ticket/PR).

## Tasks
- [x] Obtain the blank PDF and sample payload from the FE
- [x] Insert the sample payload into the the PDF
- [x] Update PDF test specs to include CH31

## Acceptance Criteria
- [x] A CH31 PDF has been created from form data
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
Due to some changes in CH31 deadlines and shifting priorities, this task is currently put on hold.  All changes in progress so far have been committed to the `ch_31_vocational_readiness_form` branch in vets-api.  The pdf generation file is here:  `/lib/pdf_fill/forms/vba281900.rb`.  

Some things to note: 
- Most of the pdf is already being generated using a payload json file (meaning not currently hooked up to FE).  
- The cell phone field is not being populated...I'm not sure if we are asking this on the FE.  
- The address fields are currently the ones needing the most work at this time.  The FE form passes standard address fields (address line 1, city, state, etc) but on the PDF we just have 3 large block lines for address information.  So some logic needs to be added to convert all the address fields from the FE to the space allowed on the form.  See screenshot below for reference.
- There needs to be a discussion with the FE regarding the education level field.  Currently FE is passing something like "Bachelors" but the pdf form is only expecting a 2 digit number.  So conversion needs to be done there as well, whether it is on the FE or BE - we need to map the name fields on the FE with a number on the BE.

Here is a screenshot of what is currently being generated on the PDF:
![Screen Shot 2020-08-24 at 1.22.38 PM.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/6585bdad-913c-42aa-afdf-fd7874d27bfa)

**Comment by jason-gcio** [comment]
VRE may be creating this pdf since they are getting the structured data

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5282
