### ISSUE TITLE
Add optional email address field for contact (VAMC) 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12476]
## Issue Description
We need the ability to add an email address (optional, not required), in addition to phone number

Examples: 

<details>
<summary> Registry exams at Pittsburgh VA Medical Center-University Drive </summary>

![image](https://user-images.githubusercontent.com/55411834/90214000-78471e80-ddb4-11ea-9dff-02b5d68a0efc.png)

</details>

---

<details>
<summary> Minority Veterans Program </summary>

![image](https://user-images.githubusercontent.com/55411834/90214026-901ea280-ddb4-11ea-8df5-36359a6f3d5c.png)
</details>

---
## Tasks
- [ ] Add optional email field for contact

## Acceptance Criteria
- [ ] User has ability to add email address to contact information 
- [ ] Email address has appearance and functionality of link

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
This functionality exists for VAMC Services per Service Location.
![Screenshot 2023-04-26 094338](https://user-images.githubusercontent.com/51967950/234612711-36e9504a-2ae7-4fd5-9aa3-fbd6f251a747.png)
