### ISSUE TITLE
Implement Flipper Component for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12473]
## Background
With the launch of the CH31 very quickly approaching, we need to ensure there is plenty of time for implementation and testing of the flipper component on the current [landing page](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/).

## Goal
Create the initial components needed for the Flipper functions, button labels

## Considerations
- This landing page is in prod and we will be flipping around the buttons for EBN and the new online application in VA.gov.
- There are a few entrances to the CH31 application:
  - [VR&E Reemployment track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/reemployment/)
  - [VR&E Rapid Access to Employment track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment/)
  - [VR&E Self-Employment track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment/)
  - [VR&E Employment Through Long-Term Services track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/long-term-services/)
  - [VR&E Independent Living track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/independent-living/)
  - [How to apply for Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/) 👈 No "**Ready to apply?**" text above button
  - [Eligibility for Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/) 👈 No **subway map** currently for eBenefits traffic

If possible, we should implement a consistent legacy path back to eBenefits (with a subway map) and "**Ready to apply?**" title over each button, if needed, and the new button to the new application.

<details>
<summary>Screenshot of legacy pathway example</summary>

![EBN-CH31.png](https://user-images.githubusercontent.com/53826255/97230259-045fc400-17b0-11eb-9c05-06a0b986b61c.png)

</details>

<details>
<summary>Screenshot of new pathway example</summary>

![VA-CH31](https://user-images.githubusercontent.com/53826255/97230320-1d687500-17b0-11eb-8f89-001a3dc06303.png)

</details>

## Tasks
- [ ] Add the feature name to `vets-api` (in snake case) by updating [config/features.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml)
- [ ] Add the feature toggle name to vets-website by updating [featureFlagNames.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/feature-toggles/featureFlagNames.js)

## Acceptance Criteria
- [ ] Feature name has been added to `vets-api` in snake case in [config/features.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml)
- [ ] Feature toggle name has been added to `vets-website`  [featureFlagNames.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/feature-toggles/featureFlagNames.js)
- [ ] A PR has been requested for merging for each of the items above

**Comment by jason-gcio** [comment]
Design coming soon
