### ISSUE TITLE
Enable urgent care pharmacy searches in Facility Locator 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12478]
**This change needs to go to Prod on 9/1/2020. No earlier.** 

## Description

OCC has resolved their business processes impacting urgent care pharmacy networks and asked that we enable urgent care pharmacy searches in Facility Locator 

## Tasks
- [ ] Unhide the urgent care pharmacy option in the Facility type dropdown
- [ ] Ensure the datalayer for tracking searches is in place
- [ ] Remove flipper 

Acceptance Criteria
- [ ] Veterans visiting Facility Locator can select Urgent care pharmacies (in VA's network) from the Facility type dropdown. 
- [ ] Urgent care benefit call to action is displayed within the search results card
- [ ] Metrics will be available for the number of users selecting this facility type for searches
