### ISSUE TITLE
Adjust Submit URL for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12471]
# Background
Now that the BE controller has been set up for the VRE Chapter 31 form we need to change the URL that the front end submits data for to that new URL. 

`veteran_readiness_employment_claims`

## Tasks
- [ ] Adjust `submitURL` to URL provided by BE
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The submission URL for the VRE Chapter 31 form has been updated to the URL for the BE controller
- [ ] A PR has been submitted for review

**Comment by jason-gcio** [comment]
Hold for VRE API urls
