### ISSUE TITLE
Create disability special monthly compensation rates spreadsheet for CSV upload

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12494]
## Issue Description
To maximize efficiency and accuracy, we're asking stakeholders to send us a spreadsheet with the new rates, when they change. On our end, we take the info from each tab and upload the numbers into drupal. We need to provide the stakeholder with this empty spreadsheet to fill in and send us.

Page to create spreadsheet for: https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/

---
## Tasks
- [x] Create empty spreadsheet for stakeholder to fill in.
- [ ] Share with Beth to take to stakeholder.

## Acceptance Criteria
- [ ] Spreadsheet created.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Here is the blank version for the stakeholder to fill in: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/content-team-processes/benefit-rates-updating-process/Special%20Monthly%20Compensation%20rates%20-%20Blank.xlsx

**Comment by bethpottsVADEPO** [comment]
Sent this to stakeholder Elana Sztulwark on Friday, 8/21. I'll close this ticket since I'll track the approval in a different ticket.
