### ISSUE TITLE
Iteration 1 - Checklist, Videos, Images: Enter sample LC content in CMS, so FE engineers have something to test FE template work

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#12537]
### Acceptance criteria
- We need to enter sample learning center content into  CMS templates that are currently in progress. 
- The sample text is needed so the FE engineers can start building the FE template and connecting to the CMS LC content fields and test that the FE mapping is working. 

**Sample WIP learning center content:** 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy/for-prototype-test

**The CMS templates in this ticket are:**

- [x] Checklist - Checklist content type is available for test data entry - https://prod.cms.va.gov/node/add/checklist prod.cms.va.gov/node/6924
- [x] Videos template prod.cms.va.gov/node/6950
- [x] Images template prod.cms.va.gov/node/6954

`Note: The CMS templates currently don't include the sandwich bread layers:`
```
- Tags taxonomy
- Need more help
- Was this useful
- Related info/articles
```

## Acceptance criteria
- Sample content added to Drupal for the new templates

**Comment by jenniferlee-dsva** [comment]
@RLHecht @bethpottsVADEPO - let's sync on a call before you dig into this ticket, esp re sample images and videos content.

**Comment by RLHecht** [comment]
@oksana-c Are there templates set up in the CMS for the videos and photos? I'm going to start on the checklist one.

**Comment by oksana-c** [comment]
@RLHecht , Video and Image lists are in progress, not available on prod yet. 
Connecting here for tracking:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2456 
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2455

**Comment by RLHecht** [comment]
@oksana-c I've put in the sample text for the checklist template. Here's the node: prod.cms.va.gov/node/6924

Two issues I found:

1. Can there be text underneath the section header that is not a checklist item? Here's a screenshot of a draft in github: ![Screen Shot 2020-08-26 at 3.38.27 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d2c7de19-d0ec-4673-917d-86fe1fa6485a)

The template doesn't allow for me to enter that first line without it being one of the items in the checklist.

2. In the sample layout the "Note" part of the intro is in a smaller font but I can't do that in the Drupal WYSIWYG field:

![Screen Shot 2020-08-26 at 3.44.45 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/078d7ccc-b06e-455b-8274-fa27c96b931d)

**Comment by oksana-c** [comment]
@RLHecht , @jenniferlee-dsva , there's currently no option to add text above the checklist items. Before we go ahead and add it, I'd like to confirm these assumptions with you.

1. text field should be available in locations shown on the scheenshot below.
1. text field max length = 300 chars
1. plain text format is used, which doesn't allow entry of links or bold/italics text, etc.

<img width="583" alt="Screen Shot 2020-08-31 at 8 11 38 AM" src="https://user-images.githubusercontent.com/16477724/91734326-0d456800-eb68-11ea-8963-8f7bee7042d6.png">


---

> 2. In the sample layout the "Note" part of the intro is in a smaller font but I can't do that in the Drupal WYSIWYG field:

@jenniferlee-dsva , I recall a decision to open up limited rich text format for page intro fields and agreed to skip the "small font size" option. Based on that decision, all text within the field will be displayed in same font size on FE.

Please confirm all the above. Thanks

**Comment by jenniferlee-dsva** [comment]
Easy one first: 

>  2. In the sample layout the "Note" part of the intro is in a smaller font but I can't do that in the Drupal WYSIWYG field:
> @jenniferlee-dsva , I recall a decision to open up limited rich text format for page intro fields, where we agreed to skip the "small font size" option. Based on that decision, all text within the field will be displayed in same font size on FE.

Correct. There will be just the regular intro text font - please ignore the design example with the smaller font. We do allow paragraphs, bolding, ital, so on, per the limited rich text WYSIWYG. 

Correction in your first Q - the intro text is NOT plain text. It should use the **_limited rich text WYSIWIG_**, so it DOES allow bolding, ital, hyperlinks, paragraphs, up to 1,000 characters. I think the only thing that we're disabling are headings bc that's part of the full rich text functionality, not limited rich text.

**Comment by jenniferlee-dsva** [comment]
2nd part: 

> @RLHecht , @jenniferlee-dsva , there's currently no option to add text above the checklist items. Before we go ahead and add it, I'd like to confirm these assumptions with you.
> 
> text field should be available in locations shown on the scheenshot below.
> text field max length = 300 chars
> plain text format is used, which doesn't allow entry of links or bold/italics text, etc.

@oksana-c - I did not capture that in the requirements, but great Q. Yes, please enable optional plain text under the headers. Please enable 300 characters including spaces for that plain text field. The checklist item text is also 300 chars. 

The section headers - for all templates, if they have section headers enabled - should be hard limited to 70 characters max with spaces. I don't think I included that in the MD file, and I will add that. (FWIW, 70 chars for section headers is what we currently have in the design system, but we don't hard set this anywhere in the CMS. In the LC, we will hard set this.)

**Comment by oksana-c** [comment]
thanks @jenniferlee-dsva. Documented in #2814

**Comment by RLHecht** [comment]
@oksana-c @jenniferlee-dsva I've added the sample copy for all three of these page types and put the node IDs at the top next to each one. I also added alerts. Let me know if I should keep this ticket open for when I can put in the plain text above the checklist or if that's captured on a different ticket. Moving to validate for now. FYSA @MickinSahni

**Comment by oksana-c** [comment]
@RLHecht @jenniferlee-dsva , heads up - plain text intro fields for checklist component are going out with today's deploy.
