### ISSUE TITLE
Staging Review Benefits Delivery at Discharge

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12544]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/disability-compensation-claim/bdd/README.md)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/disability-compensation-claim/bdd/release-plan-bdd.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Access information for the tool or feature in staging:
  - Staging link: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
  - Account 1: vets.gov.user+250@gmail.com
  - Account 2: vets.gov.user+261@gmail.com
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more]
  - We have [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/UAT-August-2020) ready but need to translate into TestRail: 
- QA [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/214) \[Test Cases are list under Test Runs there]:
  - [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/131)
  - [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/132)

#### Required:

- [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
- [x] Conduct axe browser scan, and document or address issues found 
- [x] Ensure end-to-end tests - including the axe check, pass 
- [x] Check color pairing for proper contrast 
- [x] Check for colorblindness issues 
- [x] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
- [x] Repeat for 300% 
- [x] Repeat for 400% 
- [x] Navigate all pages and core functionality with keyboard only 
- [x] Test all pages and core functionality happy path with MacOs Safari + VoiceOver and/or NVDA+Firefox 
    
#### Recommended:

- [x] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) 
- [ ] Add keyboard end-to-end tests in CI/CD test runs  
- [x] Conduct axe-coconut browser scan, document or address issues found 
- [x] Test with [WAVE tool](https://wave.webaim.org/) 

- Link to verification that accessibility checks are complete: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11024

- List of known issues (with links to tickets when applicable)
  - [Development] BDD: Monitor BDD Claims #10675
  - [Development] BDD: Cache servicelocation (Post Launch) #10275
  - [Tech Debt] BDD: Ensure We Check for Real Zip Codes #12538
  - [Tech Debt] Link to swagger docs for evss in 526 documentation #8528
  - [Tech Debt] BDD: Can We Prefill Separation Date from Military History Information #10842

## Meeting attendees from **requesting team**
- Product Manager (required): Luke Majewski
- DEPO product lead (required): Andrea Schneider (last day is 8/21)
- Anyone else from your team who significantly contributed to the artifacts provided (required): Christian Valla, Kevin Stachura, Robin Garrison

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar]
  - Thursday, August 20 - 1:30pm – 2:30pm

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by mandifrances** [comment]
@luke-gcio these meetings are typically only 30 mins. Do you need longer?

**Comment by mandifrances** [comment]
@luke-gcio this has been schedule for 8/20 @ 1:30pm ET

**Comment by tlei123** [comment]
@mandifrances , QA artifacts will be late\* and QA review would have to be Async.  Couldn't find any Design tickets this afternoon for updated design screens for the new BDD flow.  There're some copy/layout quirks for which I'm reluctant to log defect w/o checking w/ Design first.

Will chat with Designer @kevinstachura tmrw (Tue) to hunt down updated screens (if any). Barring any other documentation issues, should hopefully complete test-runs and provide QA artifacts by end of Wed.

P.S.  Is Nancy Smith on GitHub?  I found [six Nancy Smith users](https://github.com/search?q=nancy+smith&type=Users) but none of them looks like the our VSP Program Manager.

cc @pjhill

**Comment by mandifrances** [comment]
@tzelei yes Nancy does have a Github username it's @nsmith1982

**Comment by jenstrickland** [comment]
@luke-gcio or @Mottie — Would you please add a staging link above where the test users are listed? Thanks!

**Comment by Mottie** [comment]
@ndsprinkle would have the most up-to-date list

**Comment by ndsprinkle** [comment]
@annaswims Are the users listed [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11892#issuecomment-671517357) still valid test users or will we need to set up more?

**Comment by jenstrickland** [comment]
@ndsprinkle @Mottie @annaswims — The reviewers need the staging url to use.

**Comment by ndsprinkle** [comment]
@jenstrickland I have updated the original comment to include the link. It's the same link we use for the 526 disability benefits form, but will ask slightly different questions if a BDD separation date is provided on the military history page.

**Comment by jenstrickland** [comment]
@ndsprinkle **Thank you!** I didn't have the 526 link, either! I ought to make a table of all the VSA products and links to them. :)

**Comment by ndsprinkle** [comment]
@jenstrickland You are welcome :) Yeah a table like that would be helpful for me too haha

**Comment by tlei123** [comment]
@ndsprinkle @kevinstachura , do we have updated design screens (maybe BDD v4)?

I have "[BDD v3](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens)", but that's for when BDD was its own form, and I heard that BDD's been incorporated into the main Disability Claim flow.

Pls. let me know.  Thx!

**Comment by tlei123** [comment]
@luke-gcio , just to clarify, @pjhill (VSP-QA) expects my QA test-artifacts (from Staging Manual UI testing), not UAT (which I don't think VSP requires for Staging Review).  I've updated the main Description above, keeping your UAT link just in case @nsmith1982 would like to look at that.

Not that UAT is not testing, nor am I saying it's never gonna be part of QA either.  It's just that currently VSA-QA is not staffed to regularly cover that or other test-types for VSA Product Teams.

P.S.  I've suggested to VSP an explicit "QA test artifacts" subhead to be added to the ticket template, just to clear up confusion.  That said, I know VSP needs to keep this template one-size-fits-all (and such an update may be too VSA-specific to be made).

**Comment by nsmith1982** [comment]
thanks @tlei123!  I was able to review the UAT items as well.  Thanks for keeping it, understanding this is not in place of the QA test artifacts.

**Comment by kevinstachura** [comment]
Hi @tlei123 - just chatted with @ndsprinkle about this and I think these screens have been added since you last took a look:

**1. 'Did you serve in a combat zone after September 11, 2001?'**

How to get this screen to show: Select a military history date that ends after 2001.

**2. 'Have you ever been a POW?'**

This screen shows up by default, in the disabilities step right after 'what caused this service-connected disability'.

**3. 'Homelessness'**

This screen shows up by default, in the additional info step right after adding your bank info.

**4. 'Are you terminally ill?'**

This screen shows up by default, in the additional info step right after homelessness.

**5. 'Are you a VA employee?'**

This screen shows up by default, in the additional information step after 'are you terminally ill'.

**6. 'Fully developed claim program'**

This screen shows up by default, in the additional info step right after 'are you a VA employee'.


At this point, we still need to add some of these screens back into the Invision flow, but they are all represented in the staging environment which is accessible. Please let me know if you need help in accessing the staging environment and I would be more than happy to point you in the right direction. Thanks @tlei123 !

**Comment by tlei123** [comment]
Thx, @kevinstachura !  I'll update test-cases based on new screens above.

I'm hoping to start test-runs this evening \[got Public-Websites's SSO-Cerner Health Pages to test right now], shooting for completion by end of (or evening of) tmrw (Wed).

**Comment by tlei123** [comment]
Test runs completed.  QA artifact links added above in main Description.

**Comment by nsmith1982** [comment]
@tlei123 all QA artifacts have been reviewed by me.  Is there a plan to resolve the minimal defects noted?

**Comment by mnorthuis** [comment]
There is no IA feedback related to the application changes.  Please make sure you are following up with the public websites team on supporting content changes to make sure they are clear on launch dates and can launch any supporting content in the timeframe needed.

**Comment by pjhill** [comment]
> @tlei123 all QA artifacts have been reviewed by me. Is there a plan to resolve the minimal defects noted?

Taking a look at the defects of today (8/26/2020), they all appear to be closed -- hooray!
