### ISSUE TITLE
Remove broken link from Wellness Programs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12559]
## Issue Description
There is a broken link on this [health care page](https://www.va.gov/health-care/wellness-programs/). The Community Care program pulled the page down while making changes, but it is unclear when it is going back up. Therefore we should remove the link for **VA retail immunization care coordination program**
until it's working again. Once the page is working again, we will set up a new ticket to add the information back to this page.

![Screen Shot 2020-08-17 at 4.47.32 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4e16c10a-bb14-4025-b018-559eed707986)

URL: https://www.va.gov/health-care/wellness-programs/

---
## Tasks
- [x] Remove link and text on wellness programs page (Selina)
- [x] Review change and publish page (Randi)

## Acceptance Criteria
- [x] Teaser text and link no longer on wellness programs page
---

**Comment by lunascoop** [comment]
Hi @RLHecht I removed the link teaser for  VA retail immunization care coordination program in draft mode, and the page is ready for review and publishing.

- http://preview-prod.vfs.va.gov/preview?nodeId=41

**Comment by RLHecht** [comment]
Thanks, @lunascoop This looks great. I published the page and am moving this ticket to validate. FYSA @DanielleThierryUSDSVA @MickinSahni

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni @DanielleThierryUSDSVA
