### ISSUE TITLE
Back end fix report_divorce Data Stripping Issue in 686

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12558]
# Background
Originally the way we were submitting data to the BE was resulting in the data for `reportDivorce` being stripped out of the payload because the option in the wizard is named the same as the data object in the payload. This resulted in the data object being stripped out as a duplicate. To correct this we need to changed the payload so that the options in the wizard are wrapped inside an object of their own, we need to adjust the back end to accept and process this change.

## Tasks
- [x] Change the back end to look for the wizard options to be wrapped in an object
- [x] Submit a PR to `vets-api` for review

## Acceptance criteria
- [x] The report divorce data is getting accepted by the back end
- [x] PRs have been submitted for review

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4729
