### ISSUE TITLE
Frontend Fix `report_divorce` Data Stripping Issue in 686

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12557]
# Background
Originally the way we were submitting data to the BE was resulting in the data for `reportDivorce` being stripped out of the payload because the option in the wizard is named the same as the data object in the payload. This resulted in the data object being stripped out as a duplicate. To correct this we need to change the payload so that the options in the wizard are wrapped inside an object of their own, this will keep the data objects from being stripped out.

## Tasks
- [x] Change the front end to skip the function call that pulls the wizard options and puts them on the root of the payload
- [x] Submit a PR to `vets-website` for review

## Acceptance criteria
- [x] The wizard options for the 686 are getting sent to the back end wrapped in an object named for the view field
- [x] PRs have been submitted for review
