### ISSUE TITLE
[Tech Debt] 526: Better Translate EVSS Errors to Human Readable

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12584]
## Issue Description
1. Make a list of what we want to do for each error (retry, better error messaging)
2. Translate the error message to human/veteran readable

This will likely require some convo about what is "good enough" since we don't have a definitive list (I believe) of all of the EVSS errors possible out there.  We should probably time box this for now.

## Tasks
1. One of the latest ones was banking info and separation location - no reason why it ends up with non-specific errors
2. File upload issues (need this back from EVSS)
3. 13 year olds should not be allowed to continue down the validation path.
4. Duplicate disabilities fail

## Acceptance Criteria
- [ ] Try and reduce the number of generic errors and translate EVSS lingo to veteran-friendly lingo.
- [ ] Spin off the front end tickets related to validation (pre submission)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by edmangimelli** [comment]
this looks like it could be multiple tickets. Ex: (Task 3) "13 year olds should not be allowed to continue down the validation path" <-- could be a FE validation ticket
