### ISSUE TITLE
Add custom users to the htpasswd file for caregiver beta

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#12594]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
@kevinmirc has requested we add three users to the htpasswd file in dev/staging/prod.
The usernames are: caregiverbeta001, caregiverbeta002, caregiverbeta003
The passwords for each should be unique in each environment, and randomly generated.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 
https://github.com/department-of-veterans-affairs/devops/pull/7422
https://dsva.slack.com/archives/CBU0KDSB1/p1597680499074300

## Technical notes
_Notes around work that is happening, if applicable_
htpasswd file is in credstash: revproxy.<env>.htpasswd_basic_auth 
We will need to retain the veterans user that is there, and add these three user/password combinations to each
This will be needed temporarily. Passwords should be communicated to @kevinmirc via secure channel when they are created
A new ticket should be created to remove these user/passwords from the htpasswd after 30 days or whenever @kevinmirc is done with them.
---
## Tasks
- [x] _Create htpasswd format user:pass combinations for three users in each environment_
- [x] _Add these user/pass combinations to the existing credstash entry_
- [x] _Deploy the configuration changes to dev/staging_
- [x] _Test basic auth_
- [x] _Deploy to Prod_
- [x] _Test basic auth in Prod_
- [x] _Create ticket to remove the passwords in 30 days_

## Definition of Done
- [x] _Basic auth is enabled on the required page in dev/staging/prod_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jbritt1** [comment]
Ticket to remove users created: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12609
