### ISSUE TITLE
Usability Testing Prep: Comparison Tool School Ratings

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#12607]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [ ] Mandi to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/product-outline.md)
- Link to prototypes
  - [Task 1 & 2](https://bahdigital.invisionapp.com/share/KYIAERSZNVP)
  - [Task 3](https://bahdigital.invisionapp.com/share/PGIAEQXWMQ7) 
- Link to [content doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/design/content-doc.md)
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/research/research-plan2.md) and [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/research/discussion-guide2.md)

There's no near-term development effort for CT School Ratings so these items are N/A at this time
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from **requesting team**
- Product Manager (required): **Darrell Neel**
- DEPO product lead (required): **Matt Self**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Cindy Cruz, Michael Delli-Gatti, Jen Jones. Amy Knox, Adam Sonntag**
- Optional attendees: **Will McCormack, Daniel Shawkey, Desiree Turner**

## Scheduling
Tuesday, 8/25, 11am ET

- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by CrystabelReiter** [comment]
You're all good from the VSP design side! No feedback needed since we discussed testing explorations

**Comment by peggygannon** [comment]
Hello! No content changes from VSP content, but something to consider below: 

-Possibly add some language about how ratings show up only after school has *x* or more ratings.  Something like (in bold below)  

**About ratings**
We ask Veterans to rate schools they’ve attended on a scale of 1-5 stars, with 5 being the best rating.
We reach out to Veterans who’ve received a Certificate of Eligibility (COE) for benefits, when they transfer into or out of a school, or when they graduate to provide a rating.

If a school asks us which Veterans rated their school, we'll provide a list of all individuals who've submitted ratings for that school. However, those ratings won't be tied to the Veteran and we won’t share the individual ratings the students provided. **A school's rating is shown only after we've received [*x* or a *certain*] number of reviews.**

**Comment by mnorthuis** [comment]
Hi - No additional IA feedback.  Looking forward to seeing results!

**Comment by amyknox** [comment]
Thanks @CrystabelReiter ! 
Thanks @mnorthuis !
Thanks @peggygannon ! Great point on the additional content. We're still working on what the threshold would be for aggregate ratings display.  We'll keep your suggestion in mind.
