### ISSUE TITLE
Update Yellow Ribbon Program page with stakeholder changes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12606]
## Issue Description
Per stakeholder Tammy Hurley we need to make a few changes to the eligibility section of the Yellow Ribbon Program page because of 508 compliance.

Page to update: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/

![Screen Shot 2020-08-18 at 4.17.13 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8d0f4515-13d4-4861-847d-d58911909475)

Changes to make:

- [x] Remove the third bullet (Received a Fry Scholarship on or after August 1, 2018, or)
- [x] Replace last bullet with the following: Are a [Fry Scholar](https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/) (eligible for the Yellow Ribbon Program on or after August 1, 2018)

## Tasks
- [x] Update bullets in eligibility section with info above (Selina)
- [x] Review and publish page (Randi)
- [x] Notify stakeholder (Beth/Randi)

## Acceptance Criteria
- [x] Updates appear on live site

**Comment by lunascoop** [comment]
Hi @RLHecht I made the changes in draft mode, and the page is ready for review and publishing.

- http://preview-prod.vfs.va.gov/preview?nodeId=936

**Comment by RLHecht** [comment]
Thanks, @lunascoop I just published the page. @bethpottsVADEPO You can let Tammy know that the changes should be live late this afternoon. FYSA @MickinSahni

**Comment by bethpottsVADEPO** [comment]
Thanks @lunascoop and @RLHecht for the quick turn around!

**Comment by bethpottsVADEPO** [comment]
Validated, notified stakeholder, and closing ticket.
