### ISSUE TITLE
Remove caregiverbeta001, caregiverbeta002, and caregiverbeta003 users from dev, staging, and prod

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#12609]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12594
## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Remove users from htpasswd files in credstash for dev, staging, and prod. 
- [ ] Update the htpasswd_plaintext_values_all_envs entry in credstash to also drop these user passwords

## Definition of Done
- [ ] Temp users listed in title are removed from htpasswd configs in credstash and revproxy is deployed to reflect config changes

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed - n/a
- [ ] Please connect to an epic

**Comment by pnwstevan** [comment]
`caregiver001` was removed 9/17 per request from @kevinmirc; thread: https://dsva.slack.com/archives/CBU0KDSB1/p1600364969037200

Announcement of deploy: https://dsva.slack.com/archives/CJYRZK2HH/p1600375608333700

Apparently this caused issues with UAT for other teams, see this thread:
https://dsva.slack.com/archives/CBU0KDSB1/p1600368350063500

CC @jenniferlee-dsva 

`caregiver002` and `caregiver003` are still in place and need to be removed.

**Comment by kevinmirc** [comment]
Hi all, can we schedule to remove these credentials **and** take off the basic auth for **/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg** on the morning of **Tuesday 09/29** for all **environments**?

Please be aware, before removing basic auth we must set the `:allow_online_10_10cg_submissions ` feature flag to "Disable for Everyone".

This is part of the production release plan for online 10-10CG (details here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12984)

**Comment by jbritt1** [comment]
Users removed from all htpasswd configuration files and protection removed from path. Rolling out to all environments as requested.

**Comment by kevinmirc** [comment]
Thanks, @jbritt1 !

**Comment by jbritt1** [comment]
> Thanks, @jbritt1 !

Anytime!
