### ISSUE TITLE
Synthesize contact center research findings

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12618]
## Issue Description
Now that we have done an initial analysis of contact center data and met with the B&M1 team, how might we understand what it all means for our internal reporting and how we collect contact center information? 

---
## Tasks
- [x] Synthesize analyses and user feedback
- [x] Recommend next steps and a vision for a future state of contact center reporting
- [x] Share findings with team

## Acceptance Criteria
- [ ] VSP Analytics & Insights has a "roadmap" or a way forward for contact center reporting.

**Comment by joanneesteban** [comment]
X-check "Help Desk (Contact Centers)" part of the Playbook outline with the actual analysis and recommended way to analyze contact center data. https://docs.google.com/document/d/1Z8GaBtH9R3eLdv7p_XLdxnBxOXNffoV_QSA8e5GeR7k/edit

**Comment by Kimberley2019** [comment]
Below is the completed synthesis.

https://docs.google.com/document/d/16Au_atvmVLvMXSbuRp9m9nLZQc8EBOIl5fa_oeNAW9Q/edit

**Comment by joanneesteban** [comment]
Closing this ticket. The synthesis is above.
