### ISSUE TITLE
CONSIDER: Navigation for VAMC facility operating status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12611]
## Issue Description
As a Veteran, I want to easily learn more about a facility's operating status so that I can be prepared to visit. 

The status alone does not provide enough information to prepare a Veteran for a visit. Veterans need to view details related to "Facility Notice" or "Limited services and hours". 

<details>
<summary>Currently, a facility's operating status is visible within the Location and Contact information page (assuming the location has a status). </summary>

![image](https://user-images.githubusercontent.com/55411834/90570187-70003200-e16c-11ea-92fa-640a2a0ee03e.png)

</details>

<details>
<summary>To learn more about the status, the Veteran needs to go to the Operating status page (currently linked through the COVID banner) and scroll past the situation update. </summary>

![operating status page](https://user-images.githubusercontent.com/55411834/90570367-bfdef900-e16c-11ea-834b-90d8b64113fb.png)

</details>

---
## Tasks
- [ ] Determine a more direct/appropriate navigation for learning more about a facility's operating status. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
Keep, @davidmpickett to add context.
