### ISSUE TITLE
Update pharmacy search experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12612]
## Issue Description
There are (at least) three distinct reasons a Veteran can visit a local retail pharmacy: 

- Scenario 1: Filling a prescription following an urgent care visit
- Scenario 2: Filling a limited (14 day) prescription following a visit to a community care provider
- Scenario 3: Flu shots

Facility Locator currently displays an alert for urgent care benefit information relevant to Scenario 1. 

The legacy search path of Facility type = `Community providers (in VA's network)` + Service type = `Pharmacy: Community/Retail Pharmacy` returns community pharmacy results without the alert and with "Call for services and hours" text. 

---
## Tasks
- [ ] Replace drop-down label/language from `Urgent care pharmacies (in VA's network)` with `Community pharmacies (in VA's network`
- [ ] Remove the Urgent care pharmacy alert for all pharmacy searches
- [ ] Remove referral language displayed in results for searches in which Facility type = `Community providers (in VA's network)` + Service type = `Pharmacy: Community/Retail Pharmacy`
- [ ] Ensure a consistent pharmacy search experience for all paths:
       - Facility type = `Community providers (in VA's network)` + Service type = `Pharmacy: Community/Retail Pharmacy`
       - Facility type = Community pharmacies (in VA's network)
- [ ] Maintain existing urgent care search functionality

## Acceptance Criteria
- A Veteran is able to perform a search for `Community pharmacies (in VA's network)`
- A Veteran is not able to perform a search for `Urgent care pharmacies (in VA's network)` 

- When a Veteran has entered a location and selected `Community pharmacies (in VA's network)` as a facility type, 
   - The search results will include only pharmacy locations
   - Search result cards do not include an alert 
   - Search result cards do not include referral language
   - Search results display "Call for services and hours"

- When a Veteran has entered a location and Facility type = `Community providers (in VA's network)` + Service type = `Pharmacy: Community/Retail Pharmacy`, 
   - The search results will include only pharmacy locations
   - Search result cards do not include an alert 
   - Search result cards do not include referral language
   - Search results display "Call for services and hours"

- When a Veteran has entered a location and Facility type = `Urgent care` + Service type = `All urgent care`
   - The search results include VA and Community care locations in a single result list, organized by ascending distance
   - "In-network urgent care benefit" alert displays only on cards for community urgent care providers 
   - "In-network urgent care benefit" alert links to https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent_Care.asp

- When a Veteran has entered a location and Facility type = `Urgent care` + Service type = `Community urgent care providers (in VA's network)`
   - The search results include only Community urgent care locations, organized by ascending distance
   - "In-network urgent care benefit" alert displays on cards f
   - "In-network urgent care benefit" alert links to https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent_Care.asp

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
