### ISSUE TITLE
Collect feedback on the VA.gov KPI framework

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12619]
## Issue Description
Before we move forward with recommending a KPI framework for VA.gov PMs/POs to use as guidance, how might we understand if this aligns with VA goals and how might we determine what connects with business and user goals from the VA perspective?

---
## Tasks
- [ ] Schedule research sessions or asynchronous feedback from DEPO stakeholders
- [ ] Meet with or retrieve asynchronous feedback
- [ ] Synthesize feedback

## Acceptance Criteria
- [ ] VSP Analytics & Insights understands the goals that VA stakeholders have of VA.gov applications and services and how that fits in the KPIs.

**Comment by joanneesteban** [comment]
### Feedback for KPI Framwork

- [ ] DO: Retrieve feedback from Chris J, Jeff B
- [ ] TRY: Retrieve feedback from Dave C, John H, Jenn L, Matt S, and Steve K
- [ ] Feedback session ideas:
  - 45 minute Zoom - 15 minute walk through, 15 minute Q&A, 15 minute discussion/free form feedback
  - 45 minute Zoom - 15 minute walk through, 15 minute Optimal Workshop feedback, 15 minute discussion/free form feedback
  - Asynchronous Feedback: Send an accessible, comment friendly doc (PR?) to ask for notes
  - Asynchronous Feedback: Send an optimal workshop
  - Asynchronous Feedback: Send optimal workshop or doc, share a meeting invite for deadline
  - Both - Send optimal workshop or doc, share a meeting invite for "office hours" to do the survey then and we can be on the Zoom for questions or direct feedback
