### ISSUE TITLE
Discovery on additional BigQuery connections

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12622]
## Issue Description
How might we connect BigQuery to other data sources, like Speedcurve, Circle CI, Prometheus, and Data Dog, so that we have a better understanding of the data available for VA.gov and can get closer to an internal performance dashboard? We'll need to start out with conversations and review our [design sprint](https://www.google.com/url?sa=t&rct=j&esrc=s&source=appssearch&uact=8&cd=0&cad=rja&q&sig2=P9yXTuNOXHSgDAINnedUog&ved=0ahUKEwjx-JaKw6frAhWC3-kKHVBYCIA4ABABKAAwAA&url=https://drive.google.com/a/adhocteam.us/open?id%3D1zX5PRJyY5o5EJ_vPjCrt60J7Xb1Ov-IYHNa-iNbAjog%26usp%3Dchrome_omnibox&usg=AOvVaw3y-rEufM4VkFP062CYPepP) documentation on what's available, what is most important to connect (the quality standards), and what those connections might look like.

---
## Tasks
- [ ] Review quality standards from design sprint
- [ ] Sync with Gretchen on Content/IA on quality standard research
- [ ] Sync with FE on Speedcurve/Circle CI
- [ ] Sync with BE on Prometheus/DataDog
- [ ] Synthesize information found through discussions and research

## Acceptance Criteria
- [ ] Understand how to move forward with the additional BigQuery connections

**Comment by jonwehausen** [comment]
Closing as old and is now to being spearheading by Jason iteratively.
