### ISSUE TITLE
Draft KPI Dashboard for Auth Exp 

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12621]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Acceptance Criteria
- [ ] The requesting VFS team has access to and can use an MVP KPI dashboard on Domo

---
## QA Checklist

**GA Reporting Specialist:**
  - [ ] For user/session based metrics, create shared GA segment
  - [ ] Stable automated connection to data source, BigQuery where possible
  - [ ] Data is structured in a convenient way to meet the metric with little manual effort
  - [ ] QA data sources to ensure data accuracy & cleanliness
  - [ ] Non line graphs have date ranges (dynamic text boxes)
  - [ ] Cross-team: work with designer to ensure the data is explained
  - [ ] Cross-team: work with designer to ensure each "card" has a data source that is clearly linked & that the link works

**Designer:**

  - [ ] Content is not "too long" so that export is possible
  - [ ] All graphs are logically grouped in layouts so exporting works and feels logical
  - [ ] Each graph and table has appropriate titles & labels
  - [ ] Each graph has appropriate date ranges
  - [ ] Set goal lines
  - [ ] Cross-team: work with GA Reporting Specialist to ensure that data is explained ([metric definitions reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/google-analytics-cheat-sheet.md))
  - [ ] Cross-team: work with GA Reporting Specialist to ensure each "card" has a data source that is clearly linked & that the link works

**Contact Center Lead:**

  - [ ] Ensure accuracy of contact center data
  - [ ] Contact center data has appropriate dimensions, descriptions, and sources

**Product Manager:**

  - [ ] Groom descriptions for grammar, date ranges, & accuracy
  - [ ] Groom titles for grammar, date ranges, & accuracy
  - [ ] Groom notes for grammar, date ranges, & accuracy
  - [ ] Groom dashboard and charts for flow & usability
  - [ ] Schedule onboarding with VFS PM/PO/Stakeholder
