### ISSUE TITLE
[VAMC-Upgrade] Provide report and feedback to stakeholders and document information for future use [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12627]
## Story
As a VAMC - stakeholder I need clear responses to questions and information, so I can successfully take over administration and maintenance of the new VAMC-system website.

## Goal
Provide updated information from reviews, meetings, and feedback to all stakeholders.

## Task
- [x] Provide minutes/report from Bi-weekly open table meeting
- [x] Provide documents and links discussed in open table report
- [x] List attendees and items still outstanding for completion of review and updates to VISN-4 systems

## Acceptance Criteria
- [x] Report from open table sent out to all stakeholders
- [x] Documents provided for stakeholders
- [x] List of attendees and FAQ's documented for future use.
