### ISSUE TITLE
FE Tweak for View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12629]
## Background
If using `display:block`, would it be possible to add `role="table"`, `role="row"`, `role="columnheader"`, and `role="cell"` to the markup when it switches to `display:block`?

This should resolve a future concern with accessibility folks.

We will add the role tags so that they are always there, they do not hurt anything when the table is in `display: table`

## Tasks
- [x] Add aria role tags to table
- [x] submit a PR to `vets-website` for review

## Acceptance Criteria
- [x] Aria tags have been added to the responsive tables on View Payments
- [x] A PR has been submitted for review
