### ISSUE TITLE
Style guide updates: add term to word list and update error messaging link

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12626]
## Issue Description
We have two updates to the style guide that need to be made:
- Adding Fourth Mission as a proper noun to word list. This refers to VA's mission of improving the nation's preparedness for war, terrorism, national emergencies, and natural disasters. 
- Updating the sitewide system downtime messaging link
---
## Tasks
- [x] Add Fourth Mission to word list (Randi)
- [x] Create ticket for notification (Randi)
- [x] Update sitewide system downtime messaging link (Peggy)
- [x] Add these updates to the What's New section of style guide along with any other recent updates (Randi) 
- [x] Review changes and merge PR (Jen)

Branch to work in: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/tree/Randi-fourth-mission-add
PR:  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/289
## Acceptance Criteria
- [x] Updates showing on live site
---

**Comment by RLHecht** [comment]
@peggygannon I created a branch for the addition I made to the word list. Not sure if you want to work in there or create your own for your work but I'm finished.

**Comment by peggygannon** [comment]
ok, thank you for the update @RLHecht. I'm still working on my update, but will keep you posted.

**Comment by peggygannon** [comment]
HI, @RLHecht I updated your PR with the changes to the downtime banner link.

**Comment by RLHecht** [comment]
Jen just merged this PR. Will close ticket when changes are live on style guide. FYSA @MickinSahni

**Comment by RLHecht** [comment]
These changes are now live. Closing this ticket and will send out the GovDelivery email in another ticket. FYSA @MickinSahni
