### ISSUE TITLE
Groom analytics for Auth Exp KPI dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#12620]
## Issue Description
Groom analytics for technical feasibility.

---
## Tasks
- [x]  Document data sources for each metric
- [x]  Document unavailable vs. available metrics
- [x]  If any, add implementation issue for additional necessary implementation

## Acceptance Criteria
- [x] We understand what can be added to the KPI dashboard, what will need more sourcing, and what it takes to get there

**Comment by bmcgrady-ep** [comment]
Auth Experience KPI | Metric | Source | Go/No Go
------------ | ------------- | ------------- | -------------
Overall searches for "direct deposit" | Total Unique Searches of "direct deposit" | Google Analytics | ✔️ Go
Searches for "direct deposit" initiated from the profile | Total Unique Searches of "direct deposit" | Google Analytics | ✔️ Go
Searches initiated from the profile | Total Unique Searches | Google Analytics | ✔️ Go
Pages visited before the profile | Previous page before va.gov/profile/index.html | Google Analytics | ✔️ Go
Time spent on profile | Average time on page for profile | Google Analytics | ✔️ Go
ForeSee score rating | ForeSee score data | ForeSee | Future 🔶 Go

**Comment by bmcgrady-ep** [comment]
Published GTM workspace changes to production.

**Comment by joanneesteban** [comment]
## Final Touches!
@amycesal @bmcgrady-ep 

Not much left, looks really good so far!

- [ ] Asked Matt if he has rollout goals. We should add these goal lines if they do.
- [ ] "OKR"s should be "KR"s
- [ ] Pages visited before the profile: it looks like we need to work through this visualization. It also looks like the `previous page path` isn't concatenating the data? Also, what's the date range for this?
- [ ] Time spent on profile pages: it ooks like we need to work through this visualization as well. Is it possible to add their goal?  
- [ ] ForeSee data needs to get switched to include `/profile` instead of all. Should this be a bar chart or a line graph?

Stretches
- [ ] Overall searches for "direct deposit": working with the team to find out the baseline so we can add a goal line for 20% reduction

**Comment by joanneesteban** [comment]
^ForeSee data won't have anything until after they launch

**Comment by joanneesteban** [comment]
Added Quick FIlters to the ForeSee chart so they can distinguish between the different URLs.

**Comment by bmcgrady-ep** [comment]
@joanneesteban - Will they have ForeSee data once they launch to 25% or 100%?

cc: @mshea0606

**Comment by jonwehausen** [comment]
### QA of Auth Experience Dashboard - BigQuery

Description of QA Effort | Screenshot | Status & Notes
------------ | ------------- | -------------
Verified _Overall searches for "direct deposit"_ card is configured for explictly the strings "direct deposit" or direct deposit | ![image](https://user-images.githubusercontent.com/48527022/93369982-24e64700-f81e-11ea-8c9a-a52385f5ef5c.png) <br><br> ![image](https://user-images.githubusercontent.com/48527022/93371951-2b29f280-f821-11ea-8f82-be97fb4cdd25.png) | :heavy_check_mark **PASS** <br><br> Total searches is **not** a metric that directly lives within GA so doesn't have an exact report equivalent, that said -- the portion of the query defining total and unique searches look in accordance with best practices <br><br> _this could be expanded to include anywhere where direct deposit is said in the whole search query simply by changing this filter at the card level to CONTAINS_  
Verified _Searches for "direct deposit" initiated from the profile_ card is configured to include each of the relevant `/profile` pages and for "direct deposit" search keyword | ![image](https://user-images.githubusercontent.com/48527022/93372471-ef435d00-f821-11ea-995f-c3615e7a9e10.png) <br><br> ![image](https://user-images.githubusercontent.com/48527022/93372537-03875a00-f822-11ea-93e1-1e1db197b856.png) <br><br>![image](https://user-images.githubusercontent.com/48527022/93373684-b0160b80-f823-11ea-99b6-fddafd91e1b7.png) | This dataset is the same dataset as the one above (leverages the same select statement lines for total and unique searches) <br><br> Total searches initiated from profile is a metric we are creating via SQL that doesn't have an exact GA equivalent. That said filtering on `previous_page_path` of `/profile` as in the screenshot will get us a close estimate of searches initiated from `profile
Verified _Searches initiated from the profile_ is configured to filter for `previous_page_path` of all relevant `/profile` pages | ![image](https://user-images.githubusercontent.com/48527022/93373464-5f061780-f823-11ea-915d-f4d8751f4058.png)  | This dataset is the same dataset as the other two above (leverages the same select statement lines for total and unique searches) <br><br> Again, total searches initiated from anywhere profile is a metric we are creating via SQL that doesn't have an exact GA equivalent. That said filtering on `previous_page_path` of `/profile` as in the screenshot will get us a close estimate of total searches initiated from `profile
Verified _Pages visited before the profile_ is configured to filter on a `page_path` of direct deposit pages (i.e `www.va.gov/profile/direct-deposit`) and a `previous_page_path` of `/account` | ![image](https://user-images.githubusercontent.com/48527022/93377641-4ac51900-f829-11ea-957c-47a2cef4a539.png) <br><br> ![image](https://user-images.githubusercontent.com/48527022/93377697-60d2d980-f829-11ea-90e2-f379087b39b2.png) <br><br> ![image](https://user-images.githubusercontent.com/48527022/93376984-6a0f7680-f828-11ea-8d28-abf7ebb14bc7.png) | :heavy_check_mark **PASS** <br> This dataset specifically grabs previous page paths relating to profile. <br><br> Numbers were tested against 9/7 matching GA precisely. 
Verified _Average time spent on profile_ is accurately depicting average time on a weekly basis (no card filtering needed) | ![image](https://user-images.githubusercontent.com/48527022/93379308-a55f7480-f82b-11ea-8bfd-241e7c09b920.png) | :heavy_check_mark **PASS** This calculation will not match GA exactly as BigQuery produces a more precise average time on page based on the average of all page paths. <br><br>In this example, we can see the number in the chart is a representation of the true average (average of all of the average time on page associated with profile) <br><br> This was tested by tallying up the averages of each of the profile pages and manually performing the average calculation (as BigQuery is doing)

**Comment by joanneesteban** [comment]
Feedback

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/9a5c8715-2591-431a-944a-a5d019fdacec)

**Comment by joanneesteban** [comment]
@bmcgrady-ep were you able to work through the spike issue in your call with Matt & Samara? They were looking to get an average without accounting for the spike. (One of the workarounds is to look at the Median instead of the Average of the dataset.)

Let me know what the update was there, and we can close this issue if that was addressed.

**Comment by bmcgrady-ep** [comment]
@joanneesteban - It doesn't look like DOMO allows us to use Median instead of Average, due to this being a Beast Mode Calculation. However, I found a way to smooth out the outliers and insert the average. Above what number would you consider to be an outlier? I currently have 300.

**Comment by joanneesteban** [comment]
@bmcgrady-ep right now, 255.92 is the outlier. Is there a way for them to easily export the data and do the calculations outside Domo? Otherwise, what would smoothing out the outliers and inserting the avg look like? If we remove the outliers, we need to explicitly call that out and ask if that's what they want for a long term dashboard since we're also looking to see spikes and dips.

**Comment by bmcgrady-ep** [comment]
@mshea0606 - would you rather have the spikes in `Average Time on Profile` or would you rather it be smoothed out to average?

**Comment by bmcgrady-ep** [comment]
@joanneesteban In [this conversation](https://dsva.slack.com/archives/D01B658BRB3/p1602168639002900) with Matt, he said that spikes are okay to include in `Average Time on Profile`.

**Comment by mshea0606** [comment]
hey @bmcgrady-ep, per our discussion, could you please change the Foresee score visual from quarterly to weekly on the Profile 2.0 Domo dashboard? 

Also, could you add a total interactions by page metric/visual to the dashboard? (by week)
Example:
Count of **Personal and Contact Information** interactions
Count of **Direct Deposit** interactions
Count of **Account Security** interactions
Count of **Direct Deposit** interactions

Related to key result: Increased profile engagement/interactions

**Comment by Samara-Strauss** [comment]
☝️ I think we can close this issue once Matt's questions above are addressed.

**Comment by bmcgrady-ep** [comment]
@mshea0606 - Made the updates to the Profile 2.0 dashboard as requested. For the total interactions by page metric section, each one of the charts has the total interactions for each page. I can change that to only include updates for each page but wanted to get your input.

**Comment by Samara-Strauss** [comment]
Sorry, I know I said we could prob close this out, but I have another question — is it possible to set up a segment of people who have *access* to the Direct Deposit feature in the profile (so they can access the feature but don't necessarily have to have visited the page in a session)? We show this section conditionally based on whether you are eligible for direct deposit payments or not, so not everyone sees it.

Why I'm asking: I was pretty shocked to see that searches for "direct deposit" from the profile have actually not gone down since launch. In fact, they've gone up some weeks! This doesn't make any sense — direct deposit is clearly in the side navigation *if* you have access to the feature. There's no way people with access to the feature are missing it. 

So, that led me to a new hypothesis: maybe the issue was not that we weren't clearly elevating direct deposit in the old profile, but that there were people who thought they should see this feature that were not seeing it. I'm trying to figure out a way to prove out this hypothesis. By looking at popular search terms, I can't tell whether the people initiating those searches can actually see direct deposit or not (I'm guessing no), but if I can determine that the reason people are searching is because they are not seeing that feature, then I've got something to move forward with. Let me know if you have any ideas on if we can set up a segment of some sort — whether it's people who have access to direct deposit (not sure that's possible) or something else.

**Comment by Samara-Strauss** [comment]
And sorry, the above request is for a segment in GA — no need to update Domo now, though this might lead to a Domo update.

**Comment by Samara-Strauss** [comment]
☝️ giving this a gentle nudge. Any thoughts?

**Comment by bmcgrady-ep** [comment]
Hi @Samara-Strauss - thanks for the nudge! Looking into this, I want to make sure I am understanding this correctly and have a quick question. Do all authenticated users have access to the Direct Deposit part of the profile? I assume this is true, but want to make sure.

**Comment by Samara-Strauss** [comment]
>  Do all authenticated users have access to the Direct Deposit part of the profile?

No, they do not.  

- All authenticated users have access to the profile.
- If you are LOA1, you only have access to the Account Security page.
- If you are LOA3, you have access to Personal Information, Military Information, and Connected Apps by default.
- If you are LOA3 **and** receive disability compensation & pension payments from the VA, you see the Direct Deposit section. If you do not receive disability compensation & pension payments from the VA, you do **not** see the Direct Deposit section even if you are LOA3.

Let me know if you have questions about that.

**Comment by Samara-Strauss** [comment]
So, basically I need a segment either of people who can see the direct deposit section, or if that's not possible, we can use people who update direct deposit and people who do not update direct deposit as proxies.

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - [Here](https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a50123418w177519031p176188361/explorer-table.secSegmentId=analytics.searchStartPage&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.searchStartPage%22,%22PT%22,%22www.va.gov~2Fprofile~2F%22,0%5D,%5B0,%22analytics.searchKeyword%22,%22EQ%22,%22direct%20deposit%22,0%5D%5D&_.useg=builtin1,userorWeTmoUSXqfr7rJha2ldA,userwYD725JgTj6y8W_l8Oox0A) is a report showing "direct deposit" searches on `/profile` pages. There are two custom segements applied - 1 for authenticated users who updated direct deposit in the session and 1 for authenticated users who did not update direct deposit in the session.

**Comment by Samara-Strauss** [comment]
Hey @bmcgrady-ep, am I missing something? I didn't see any segments in the report when I clicked that link:

<img width="1280" alt="Screen Shot 2020-10-23 at 4 05 49 PM" src="https://user-images.githubusercontent.com/34068740/97049495-cf523800-1549-11eb-9bc9-9a06350328ad.png">

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - I believe I need to share the segments with you:

1. [ Authenticated Users Direct Deposit Updates Segment](https://analytics.google.com/analytics/web/template?uid=x40nj8V8S3WaBE8GkUeCBA)
2. [Authenticated Users No Direct Deposit Updates Segment](https://analytics.google.com/analytics/web/template?uid=VOt8brYvQJuDiYfS8P7Mlg)

**Comment by Samara-Strauss** [comment]
Should I select the WBC view or All data view, or does it not matter?

**Comment by bmcgrady-ep** [comment]
I would select the All data view

**Comment by Samara-Strauss** [comment]
I have a question: I checked out the results for the direct deposit segments mentioned above on searches made from /profile/personal-information (the first page of the profile) and was surprised to see that people who do update direct deposit and people who do not update direct deposit somehow don't make up 100% of searches from the profile. This is puzzling to me, because people either do or do not take this action from the profile; there's no middle ground. However, a third group — "all users" — rounds out the search counts (screenshots below) for searches made from /profile/personal-information. 

I'm wondering if there is something wrong with the segments. For users who visit the profile, you either do or do not update direct deposit, and everyone should fit into one of those two categories. Why are we seeing "all users" round out the search count from the profile? What is that capturing that the direct deposit segments are not?

Let me know if you have questions. I can hop on a quick call if this is unclear.

<img width="1280" alt="Screen Shot 2020-10-26 at 11 18 12 AM" src="https://user-images.githubusercontent.com/34068740/97191996-d9f51300-177d-11eb-8080-2583837eb077.png">

<img width="1280" alt="Screen Shot 2020-10-26 at 11 18 23 AM" src="https://user-images.githubusercontent.com/34068740/97192024-e24d4e00-177d-11eb-9c18-cdc4c96b4b54.png">

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - I had the two segments set at session-level and have now switched them over to user-level segments. This more accurately segments the users into two distinct groups - 1 group who has updated their direct deposit and 1 group who has not updated their direct deposit. [Here](https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a50123418w177519031p176188361/explorer-table.secSegmentId=analytics.searchStartPage&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.searchStartPage%22,%22PT%22,%22www.va.gov~2Fprofile~2F%22,0%5D,%5B0,%22analytics.searchKeyword%22,%22EQ%22,%22direct%20deposit%22,0%5D%5D&_.useg=userorWeTmoUSXqfr7rJha2ldA,userwYD725JgTj6y8W_l8Oox0A/) is the GA report with the two segments. Let me know if this helps!

**Comment by bmcgrady-ep** [comment]
Per discussion with @mshea0606, here are a few updates to the Profile 2.0 KPI dashboard to be made:
- Add Total Submissions to the "Increase Profile Engagement/Interactions" section
- If it is possible add weekly count of survey submission card for Foresee data.

**Comment by mshea0606** [comment]
We are also going to add in "Total profile submissions" by week to help determine profile engagement

**Comment by bmcgrady-ep** [comment]
@mshea0606 - Thanks for taking the time to meet with me. I added the `Total Interactions on Profile` chart by week and the `Total Profile Submissions`.

**Comment by Samara-Strauss** [comment]
What is "Total profile submissions"? I have assumptions, but want to make sure I'm clear.

**Comment by bmcgrady-ep** [comment]
> What is "Total profile submissions"? I have assumptions, but want to make sure I'm clear.

Total Profile Submissions are any profile saves. I can change the name if you and @mshea0606 have a different name you would like to use.

**Comment by Samara-Strauss** [comment]
Thanks! That's what I assumed. No need for a name change.

**Comment by bmcgrady-ep** [comment]
@mshea0606 - I updated the KPI dashboard to show the number of ForeSee survey submissions by week. Let me know if there is anything else you need!

**Comment by Samara-Strauss** [comment]
I'm going to close this. You all have been wonderful. We can open a new ticket if we have any additional requests.
