### ISSUE TITLE
[Product] Notifications Feature Outline

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12638]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/notifications.md)

## User Story/ies
4C- As a Veteran, I want to be notified in advance of my health care visit that a questionnaire is needed to be completed, so that I don't have to fill it out in the waiting room and can complete when convenient and relevant for me.

4D - As a Veteran, I want to be notified in a similar or the same appointment reminder that I receive today, so that the questionnaire is in context of the visit I am planning to attend.
* **Use Case:** 
---
## Tasks
- [ ] Create notifications feature outline for fields and valuation
- [ ] Based on mockups  and technical api investigation for notifications

## Acceptance Criteria
- [ ] UI review with entire team for feature capabilities 
- [ ] published documentation - [Feature - notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/notifications.md)
