### ISSUE TITLE
Update Post Launch Content Changes

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12630]
## Story
As a Veteran, I need clear, concise instructions so that I can easily add or remove a dependent from my disability claim.

## Background
After a content review, there is a set of non-critical text changes that need to be implemented across the 21-686c instructions, alerts, form and confirmation. 

## Considerations
[Punchlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0720.md)

## Tasks
- [x] Update current punchlist
  - [x] Include header to show latest update 
- [x] Indicate general changes in changelog as applicable
- [ ] Notify Peggy Gannon when changes are implemented in staging or production
- [x] Address pension disparities

## Acceptance Criteria
- [x] All text revisions are updated in mockups
- [ ] Share changes with Peggy

**Comment by sporeboy** [comment]
Punchlist updated: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0720.md
