### ISSUE TITLE
Revise View Representative

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12631]
## Goal
Revise View Representative tool to remove "right-rail" pattern. Follow Design Council direction for "view" tools.

### Considerations
Thread regarding [Design Council feedback](https://dsva.slack.com/archives/C019M1004LW/p1598892456001500). Summary:

1. Identify the top questions veterans would want answered while interacting with the tool itself
2. Integrate these questions/answers into the list tool "in context" as much as possible, either with the "additional info" component or on the page
3. If there are still questions/answers that don't make sense to be integrated into context, include these below the tool lists themselves with an "on this page" component
4. Include a "Get help" prefooter component above the footer for all tool pages

## Tasks
- [x] Remove the right rail for View Rep
- [x] Address Council feedback in new screen design

## Acceptance Criteria
- [x] Mockups have been updated
- [x] New design made available to team

**Comment by sporeboy** [comment]
Redesign guidance here: https://dsva.slack.com/archives/C019M1004LW/p1598892509002400

**Comment by sporeboy** [comment]
Initial redesign here: https://xd.adobe.com/view/e27b7e71-d920-4bcd-9e81-dc62a9665d5e-b728/

**Comment by jason-gcio** [comment]
This is now ready Design Intent Review
