### ISSUE TITLE
[Product] Authentication Feature Outline

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12637]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Authentication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/authentication.md)

## User Story/ies

* **Use Case:** 
---
## Tasks
- [ ] Create authentication feature outline for fields and valuation
- [ ] Based on mockups  and technical api investigation for unauth/auth state

## Acceptance Criteria
- [ ] UI review with entire team for feature capabilities 
- [ ] published documentation - [Feature - Authentication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/Authentication.md)
