### ISSUE TITLE
Restructure and incorporate edits for DIC pages 2020, 2019, and 2018

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12645]
## Issue Description
We discovered that charts for children's rates on this page were misplaced. They all need to be brought up into the after 1993 section (this work has already been done in drupal), which necessitates reorganizing that whole section (the "after" section that's the first part of the page). The new groupings within "after" will be by spouse (addressed first in that section) and then by child (which has 3 subsections within it). The attached Word doc shows exactly what should be done. There are some minor edits/rewriting that aren't tracked, so please copy and paste from the Word doc rather than going with the existing text in drupal. I've highlighted two changes to be aware of specifically, one is the only edit I made in a chart. The other is a number that's currently wrong on the live site. But there are other edits to the text that are not highlighted or tracked. Thus my suggestion to copy and paste from the Word doc.

**Note:** The second and third H2 sections have not changed at all, except the work Selina already did, removing the misplaced charts from the "before 1993" section.

[https://app.zenhub.com/files/133843125/d019e7cb-ffe1-4cc7-8271-7e4359201b04/download](https://app.zenhub.com/files/133843125/d019e7cb-ffe1-4cc7-8271-7e4359201b04/download)

---
## Tasks
- [x] Use Word doc to rearrange the 2020 page and input reworked text.
- [x] Update the 2020 page.
- [x] Update the 2019 page in the same way.
- [x] Update the 2018 page in the same way.

## Acceptance Criteria
- [x] This content will be up to date and accurate on all 3 DIC pages, for 3 years.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @RLHecht these pages are ready for review. I spoke w/ @bethpottsVADEPO last Friday re: some of the headers in the Word doc for "Added amounts" "Monthly payment rates" etc. In the Word doc they're just bolded, but it didn't look right in some instances in the preview. I changed them to Header 4 as a possible alternative per my discussion w/ Beth. @bethpotts @RLHecht let me know your thoughts on the headers.

- 2018: http://preview-prod.vfs.va.gov/preview?nodeId=6203

- 2019: http://preview-prod.vfs.va.gov/preview?nodeId=6799

- 2020: http://preview-prod.vfs.va.gov/preview?nodeId=1012

**Comment by bethpottsVADEPO** [comment]
@RLHecht Before I take a look, can you do a pass to compare against the Word doc Selina was working from for placement accuracy, and to copyedit?

**Comment by RLHecht** [comment]
These look OK to me. @bethpottsVADEPO I went into the 2020 page and also made the changes to the historic rates section we chatted about earlier (deleting the fourth historic rate and making the Historic rates and Full title 38 regulations two separate sections).

**Comment by RLHecht** [comment]
Closing this ticket. Next steps for this work are tracked in #12347. FYSA @MickinSahni
