### ISSUE TITLE
[VAMC]  System Data Calls - (Prototype) - (Facility Health Services) [BA] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12640]
## Story
As a business analyst how do I best retrieve "Facility Health Service information", so we can best update Drupal using .csv file and automated migrate process.

## Resources
[Facility - Prepare for your visit data call document](Google drive)

## Task
- [ ] Review of data call template with (VHA/Depo) stakeholders
- [ ] Confirm list of POCs for distribution
- [ ] Establish Time box to have information returned
- [ ] Monitor receipt and response to data call (By system)
- [ ] Escalation procedure (RACI) for information return (VHA)
- [ ] Final review of data returned (Complete) 
- [ ] Feedback loop from stakeholders (Did this request work? How can we make this better?)(Consider: Best to migrate into Drupal, ultimately migrate Automate, is template still viable?, engage writer as required.)

## Acceptance Criteria
- [ ]  VHA/Digital media approves/confirms format of Data call sheet
- [ ] POC distribution is validated (100% coverage) (No bounce backs/rejections)
- [ ] Escalation documented (Archived in SharePoint)
- [ ] All data is either returned and reviewed OR is in escalation
