### ISSUE TITLE
Updates to change direct deposit page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12655]
## Issue Description
Delete mention of, and existing link to pdf of, form to change direct deposit to paper checks for receiving monetary benefits. And promote direct deposit by introducing a program that introduces Veterans to banks that can help them get an account and set up direct deposit.

---
## Tasks
- [x] Update the direct deposit page. 
- [x] Add link to Veterans Benefits Banking Program.

## Acceptance Criteria
- [x] Updates deployed.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Work is complete. Validated.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Reopening this ticket for you to copyedit the latest SME edits that I just made. Do you think you can take a look and set to publish for tomorrow's deployment? I forgot to put a note in drupal about what I did. But I'll forward you the email and you can see. It is very minor. An edit to one sentence and adding the initialism in two places.

**Comment by RLHecht** [comment]
Changes look good and I've published this for today's deployment. Moving to validate.

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni
