### ISSUE TITLE
Add Prefill to CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12669]
## Background
With the chapter 31 form we figured out how to set up prefill on forms since we needed to pass a specific piece of data letting the front end know if the user was logged in or not. We now need to add prefill to the chapter 36 form as well as add the piece of data for if the user is logged in or not. This data will be used on the front end to hide/ show pages and components based on if the user is logged in or not.

## Tasks
- [x] set up prefill files in `vets-api`
- [x] Add data we need prefilled, these can be added to later if needed
- [x] Submit a PR for review to `vets-api`

## Acceptance criteria
- [x] Prefill is set up on the back end and is passing a true/ false value for if the user is logged in or not
- [x] A PR has been submitted to `vets-api` for review

**Comment by jason-gcio** [comment]
Waiting confirmation from Lihan about the address pre-fill component
