### ISSUE TITLE
Homepage - print their individual appointments in VAOS

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12679]
## Background
Currently to print in VAOS means printing the full homepage of all the upcoming appointments. This isn't practical, especially for some Veterans who have a long list of appointments. 

## Description
Instead, as part of us improving details about appointments, we should enable the ability to print individual appointments.

## Tasks
- [ ] VA 
- [ ] CC
- [ ] VVC

## Acceptance Criteria

- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag

- [ ] Print link appears on confirmed appointment detail pages

- [ ] When user clicks/taps Print link, open default browser dialog box

- [ ] Printable page does not include navigation links (breadcrumb, go back)
![print default.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/9ceb63bf-c369-4d9d-849b-8e335b18b972)

- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
- VA - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/WKROK1n#Inspector
- CC - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/QbaZbAx#Inspector
- VVC - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/Kv9bDLV#Inspector
![VA PRINT SCOPE.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/e4464021-e4d6-4145-8eee-61688ce5b45a)  ![CC PRINT SCOPE.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/abb57d8d-748e-413e-9411-34983d4cb4b2)  ![VVC PRINT SCOPE.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/22e75e1f-1c63-4367-a553-b7be7ac54f94)

**Comment by laurenernest** [comment]
Default + remove breadcrumb links, back to appts link
