### ISSUE TITLE
[Automation/Data_Formatting] Collect, standardize, consolidate, and reformat all date for System Health Services for VISN-19 [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12686]
## Story
As a data analyst/engineer, I need to collect standardize and consolidate all of the incoming data into a new format to meet the requirements of the CMS team, so CMS can easily migrate the FHS data into Drupal in one simple PR with little to no failures.

## Goals
Create proces and procedure to take data from Playbooks and health services and standardize this process to be repeatable with little to no effort.

## Task
- [ ] Review playbooks and remove all non-essential data
- [ ] Standardized headers needed for data table
- [ ] import all data from playbooks into a single table that can be standardized across the VISN.
- [ ] Gather data into appropriate query pulling essential .csv headers and data.
- [ ] Export and or Concatenate data in place to include html scripts into a single blobby (Understanding that this will all go away in phase II)
- [ ] .csv has unique Facility ID + Health services identifier
- [ ] Export into .csv file format and confirm content in text and .xlsx
- [ ] Modify any script delimiters that are not exported.
- [ ] Provide a test script to validate with CMS prior to export of all 64 facilities
- [ ] Validate and document process steps

## Acceptance Criteria
- [ ] ALL VISN-4 Data has been pulled and validated into data table for future use.
- [ ] .csv has unique "System"Owner" + "Health services" identifier
- [ ] .csv provides unbroken and html format tested correctly in test.
- [ ] .csv provided to CMS for PR and modified to satisfy fully compliant migration
- [ ] Feedback is captured and process is documented for future reuse.
- [ ] Migration process completes successfully or has been escalated in new issue.
