### ISSUE TITLE
Add links to guides to GI Bill pages

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12694]
## Issue Description
Education Service would like to add links to GI Bill guides on VA.gov pages. I'm assessing where might be appropriate.

Preview link shared with SME (sample of the work on one of the 3 pages): http://preview-prod.vfs.va.gov/preview?nodeId=935

Adding these guides, in this order:
https://benefits.va.gov/gibill/docs/gibguideseries/chooseyoureducationpathway.pdf
https://benefits.va.gov/gibill/docs/gibguideseries/chooseyoureducationbenefits.pdf
https://benefits.va.gov/GIBILL/docs/gibguideseries/FurtherYourCareer.pdf
 
To the "Get more information" section on these 3 pages, bottom of page (would have to create a "Get more information" section on MGIB-AD page):
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/
https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/

Update on 9/16:
Thumbs up from stakeholders to proceed with the above approach.

---
## Tasks
- [x] Align with SME Tammy Hurley on where to add links to these guides
- [x] Input edits
- [x] Copy edit
- [x] Notify Beth to review
- [x] Set to publish
- [x] Validate and notify SME

## Acceptance Criteria
- [x] Links and surrounding text goes live.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you assign this work out? Thanks! Let me know if there are any questions, and let me take a look before you publish.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Is there any update on this? Or questions about how to implement?

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review:

- http://preview-prod.vfs.va.gov/preview?nodeId=935

- http://preview-prod.vfs.va.gov/preview?nodeId=932

- http://preview-prod.vfs.va.gov/preview?nodeId=934

**Comment by RLHecht** [comment]
@bethpottsVADEPO These pages have been copyedited and are ready for you.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you remove the two instances of single bullet points? It should just be a normal ol' flush left line of text for those two scenarios where there isn't already a bulleted list. Thanks!

http://preview-prod.vfs.va.gov/preview?nodeId=934

**Comment by RLHecht** [comment]
I made this fix and the pages have all been published. Moving to validate. FYSA @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
These have been validated on the live site. Closing ticket. FYSA @MickinSahni @brianalloyd
