### ISSUE TITLE
[Review-clean-up] Input stakeholder feedback into Altoona-health-care where applicable [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12697]
## Story
As a web maintainer and stakeholder I need my feedback and updates reviewed and implemented, so my webpages will meet our system standards and I can take over maintenance after training. 

## Resources
[Stakeholder Review documents](https://drive.google.com/drive/folders/1fmlCo1VJ3YB8npVSg4jVu1nBTHHoTDxo)

## Tasks
* Review each URL link in Work document to confirm it is working, correct those that need correction, and confirm if any pages or areas are missing or should be included in stakeholder review.
- [x] Review feedback from Stakeholder and implemente changes where they can be implemented.
- [ ] Documented changes as "Implemented" or with description to "WHY" they cannot be implemented (i.e. Not in alignment with Style guide, Issue is under review by VHA, or CMS for implementation.)
*document results
- [x] Save copy of the review document as Implemented (FINAL)

## Acceptance Criteria
- [x] All pages have been updated per stakeholder feedback.
- [x] Final page has been returned to stakeholders with documented changes.
