### ISSUE TITLE
[UI] Review page

### ISSUE THREAD

**Issue by arickalewis1** [department-of-veterans-affairs/va.gov-team#12693]
---
## Tasks
- [x] Evaluate other review screens from form system
- [x] Create detailed mockup 

## Acceptance Criteria
- [x] UI review meeting with product for feature capabilities
- [x] UI review meeting and callouts with engineering for layout and callouts
- [x] published to [Zeplin](https://zpl.io/VOOek8j)

**Comment by kristenmcconnell** [comment]
@abuckley3385 and @mdewey Final wireframes have been linked to in this story. Also, found here...https://zpl.io/VOOek8j

**Comment by kristenmcconnell** [comment]
Peggy Gannon responded with [updated text for the emergency messaging](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13355). The wireframes have been updated accordingly.
