### ISSUE TITLE
Update 2020 Protected pension rates page with our new styling

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12702]
## Issue Description
In order to keep our rates pages uniform in style, we need to update our 2020 protected pension rates page with the new styling of our table headers. Instead of showing dollar signs throughout, the header should show (in U.S. $) at the top. 

---
## Tasks
- [x] Update all table headers on page with new styling (Selina)
- [x] Review and copy edit page (Randi)
- [x] Publish page (Randi)

## Acceptance Criteria
- [x] New styled page appears live on site
---

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. I un-bolded the effective dates and reformatted the historic rates section. I did not add the "in U.S. dollars" to the table headers as agreed since the rates are in sentence format.

- http://preview-prod.vfs.va.gov/preview?nodeId=5090

**Comment by RLHecht** [comment]
I reviewed this page and it's good to go. @bethpottsVADEPO Is this OK to publish or do you want to take a look through it first? I had slacked you a question about the 2019 in the table headings but I think that's the correct info based on the old closed ticket I sent you.

**Comment by bethpottsVADEPO** [comment]
If you've reviewed, I don't think I need to. Thanks! You can publish.

**Comment by RLHecht** [comment]
Published this page with the fixes to the table headers we discussed yesterday (with dependents and without need to be swapped). Will close after today's deployment. FYSA @MickinSahni

**Comment by RLHecht** [comment]
Validated. Closing ticket. FYSA @MickinSahni
