### ISSUE TITLE
Clone historic 2018 and 2019 Protected pension rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#12701]
## Issue Description
In order to retire legacy pages, we need to create 2018 and 2019 protected pension rates pages in Drupal by cloning our 2020 page and updating it with the correct numbers. We also need to change the style of our table headers to show (in U.S. $) at the top of each instead of using dollars throughout. 

Current URL: https://www.va.gov/pension/protected-pension-rates/
2019 Legacy page: https://www.benefits.va.gov/PENSION/protected_pension_rate_tables_pen18.asp
2018 Legacy page: https://www.benefits.va.gov/PENSION/protected_pension_rate_tables_pen17.asp

---
## Tasks
- [x] Create 2019 rates page (Selina)
- [x] Create 2018 rates page (Selina)
- [x] Check numbers and math examples and copy edit (Randi)

## Acceptance Criteria
- [x] 2018 and 2019 rates pages ready for SME approval

**Comment by lunascoop** [comment]
Hi @RLHecht these pages have been created and are ready for review. The meta title tag exceeded the character limit and I attempted to shorten it. You may want to change it.

- 2018: http://preview-prod.vfs.va.gov/preview?nodeId=6926

- 2019: http://preview-prod.vfs.va.gov/preview?nodeId=6925

Another thing
CC: @bethpottsVADEPO In looking at the historic rates, I'm fairly sure that the rates listed in the first two tables on the current page are incorrect. Specifically, the rates for **w/dependents** is actually for **w/o dependents** and vice versa. I've made those changes to the page in draft mode.

- 2020: http://preview-prod.vfs.va.gov/preview?nodeId=5090

**Comment by bethpottsVADEPO** [comment]
Thank you for noticing that @lunascoop !!

**Comment by lunascoop** [comment]
@RLHecht I made those changes to all the pages and they are ready for review.

**Comment by RLHecht** [comment]
The 2018 has been checked and looks good. But I think I found an error on the legacy page for 2019. In the Veterans with dependents table, for the Special Aid and Attendance Allowance, we say "if your income is more than $20,732." However, that number on all the other legacy pages matches the yearly income limit for a basic monthly payment. I think the number should really be $20,692. I've looked back at a lot of the legacy pages and they all match except this one. Here's a screenshot of what we currently have: 
<img width="840" alt="Screen Shot 2020-08-28 at 3 15 46 PM" src="https://user-images.githubusercontent.com/48728214/91607116-5b2c5700-e941-11ea-86a0-72c47408663f.png">

@bethpottsVADEPO Would you be able to ask Angie for the source material for 2019 so we can confirm?

**Comment by RLHecht** [comment]
The source material Angie provided shows the same number we have above, so no changes need to be made. These pages are now ready to be shared with stakeholders @bethpottsVADEPO . I am going to close this ticket and the work will continue in #12403 for sharing with stakeholders and publishing. FYSA @MickinSahni
