### ISSUE TITLE
Incorporate stakeholder updates to Tuition Assistance Top-Up page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12719]
## Issue Description
Update this page with edits from Tammy Hurley in Education Service:
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/

Tammy's track changes (to be assessed for our style and PL):
[https://app.zenhub.com/files/133843125/e39187ff-f370-4551-b485-72f679aa29cf/download](https://app.zenhub.com/files/133843125/e39187ff-f370-4551-b485-72f679aa29cf/download)

Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=927

---
## Tasks
- [x] Edit page. (Beth)
- [x] Copyedit. (Randi)

## Acceptance Criteria
- [x] Updates go live.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please copyedit this whole page. I had to rearrange the content and rewrite a bit, so it needs a full copyedit. When you're done, please set it to publish! SMEs have given their approval. Just make sure there aren't typos. I forwarded you that email from Tammy. Thanks very much.

**Comment by RLHecht** [comment]
This page has been reviewed and published. The link for the fact sheet at the bottom of the page was invalid so I reached out to Tammy and put in the correct one. Moving to validate and will close after today's deploy. FYSA @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. fysa @MickinSahni @brianalloyd
