### ISSUE TITLE
Pagination for Community Care results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12715]
## Issue description
As reported by OCC, the results presented on page 2 are not consistent with the original parameters or the preceding page of results.

**Background:**  PPMS does not provide a result count and does not support paginated queries.

**Solution**: We know from Veteran research that the most important parameter is proximity. As such, the first results in the list (representing the closest locations) are most interesting to Veterans and they are unlikely to click into subsequent pages. 

## Task
- [ ] Remove pagination from Community Care searches (FE engineers)
      - Community urgent care (in VA's network)
      - Community care providers (in VA's network)
      - Community pharmacies (in VA's network)
- [ ] Ensure results are limited to 10/page (FE Engineers)
- [ ] Review analytics to understand how often Veterans look beyond the first page to make sure our long term solution is consistent with their needs. (Michelle)

**Comment by mpelzsherman** [comment]
Per @darkbushido - PPMS does not provide a result count and does not support paginated queries.

**Comment by mmiddaugh** [comment]
Working through a bug in [#13291] otherwise, good to go.
