### ISSUE TITLE
FL: Disable Autosearch 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12710]
## Issue Description
This issue to address the current behavior in which the map continues to autosearch, looking for results

## Task
- [ ] Disable autosearch

## Acceptance Criteria

**Note: the addition of a "search this area" (or similar) function to allow Veterans to trigger a new search after adjusting the map is outside the scope of this issue but must be merged to Prod together.** 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
will be addressed with Mapbox upgrade
