### ISSUE TITLE
Build backend support for predictive geolocation prototype

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12722]
## Issue Description
- This is a follow-up to the Predictive geolocation discovery work done in #9410. 
- Documentation is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/PredictiveGeolocation.md).  
- As noted, many of the original concerns were addressed by simply turning off the autocomplete option. Our first step in any follow-up should be to re-evaluate our current solution with this new, improved behavior.

## Tasks
- [x] Build support to make request to Mapbox and populate Redux store

## Acceptance Criteria
- [x] Locations matching user's input are populated in Redux
- [x] Behavior can be toggled by feature flag

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
