### ISSUE TITLE
Jenkins Deployments - Write better documentation for out-of-band deploys of vets-api, and/or Jenkins in general

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#12728]
## Description
Jenkins jobs are somewhat confusing, and the gitref to use for certain deploys, whether it should be the devops gitref or the vets-api or vets-website gitref, for instance, is not clear.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/deployment-policy.md#step-by-step-process-for-deployment

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Write some better documentation_
- [ ] _Improve the Jenkins job parameter fields_

## Definition of Done
- [ ] _More clarity or better documentation on doing out-of-band deploys_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by ricetj** [comment]
Lack of info on what job to run, so it is a bit of a guess right now. more docs on what the jobs do. ie more technical documentation for folks that need to do a rollback as an example.

**Comment by jhouse-solvd** [comment]
@tskinn and @omgitsbillryan - If y'all have come up with any clarified procedures or documentation for Jenkins deploys in relation to your recent work, can you please share here?

**Comment by omgitsbillryan** [comment]
Better late than never I suppose. I threw together some quick doc here: https://vfs.atlassian.net/wiki/spaces/OT/pages/2034204681/Perform+Off-Cycle+Deploy+of+vets-api

**Comment by omgitsbillryan** [comment]
I suppose I'll go ahead and close this issue. Feel free to re-open, I won't be around to tell you otherwise 😭
