### ISSUE TITLE
FL: Required fields must be marked in the UI

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12729]
## Issue Description
The Facility Locator requires Veterans to input city, state or zip + choose a facility type from the dropdown box. The service type field is required for certain facility types. 

Veterans should be able to identify which fields are required before triggering a search. Currently only the service type field displays `(*Required)`

![image](https://user-images.githubusercontent.com/55411834/90940056-c10d6180-e3ca-11ea-83f1-8f447d896f90.png)

---
## Tasks
- [ ] Ensure all mandatory fields in the Facility Locator search box are marked `(*Required)`
- [ ] Ensure all mandatory fields in the Facility Locator search box have an error message which displays if the Veteran attempts to search before populating the field. 

## Acceptance Criteria
- [ ] The _City, state or postal code field_ is labeled with `(*Required)`.
- [ ] An error message is displayed if a Veteran attempts to search without entering a value into the _City, state or postal code field_. 
- [ ] The _Choose a facility_ dropdown is labeled with `(*Required)`.
- [ ] An error message is displayed if a Veteran attempts to search without entering a value into the _Choose a facility_field_. 
- [ ] If facility type = Community providers (in VA's network), _Service type_ field is labeled with `(*Required)`.
- [ ] An error message is displayed if a Veteran attempts to search without selecting a value from the list displayed for _Service type__. 
- [ ] Design is consistent for all `(*Required)` labels
- [ ] Design is consistent for all displayed error messages. 

---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
@mmiddaugh this is merged but tomorrow after the release can be validated
