### ISSUE TITLE
[Architecture][Tech Spike] Data Source and Data flow plan

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#12720]
## Problem
We are seeing data being duplicated in multiple resources (ex: demographics or facility information). We need to define what/where/how the data is coming from.  This came from a discussion in our slack channel. 

## Description
Create diagrams, flow charts, and a resource guide to define what data is coming from which API. This should be based on the latest mockups from the UX team. 

## Tasks
_define == document in [tech feasibility guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/engineering)_

- [x] Define what data is needed to start the form
- [x] Defined what data is needed to be loaded when the form begins
- [x] Define sources for the data from the first two tasks
- [ ] Decide which data source is the source of truth
- [x] Create and defined Vets API endpoint needs.  

## Acceptance Criteria
- [ ] fully documented, with diagrams in the [discovery/engineering folder]
- [ ] Review and buy-in from the team (including meetings and reviews)

**Comment by mdewey** [comment]
The first pass is here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/data-flow.md

Not quite there yet still need to confirm API endpoint data from VAMF.

**Comment by mdewey** [comment]
Update with a draft ready for review. Set meeting for Friday 8/28/2020

**Comment by mdewey** [comment]
Had a meeting with the team and the team bought in. 

Actions items: 
- Lacey will follow up for PCIU
- Amanda will decide on the source of truth, 
- Mark will add comments about trigger and create tickets for engineering tasks
