### ISSUE TITLE
Incorporate SME stakeholder edits to VET TEC page to call out the VET TEC Employer Consortium

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12721]
## Issue Description
Tammy Hurley, SME in Education Service, requested updates to the VET TEC page or a new page to house this info about the consortium. This may be not be tier-1 content, so we'll have to consider if it goes in LC.

Mockup to pull content from:
[https://app.zenhub.com/files/133843125/50c94462-19c2-47cc-ba20-61d0f4dbcf6c/download](https://app.zenhub.com/files/133843125/50c94462-19c2-47cc-ba20-61d0f4dbcf6c/download)

---
## Tasks
- [ ] Assess whether this is Veteran-facing and should be added to existing page. 
- [ ] Respond to stakeholder about direction.
- [ ] Incorporate edits if appropriate for tier-1 content. 
**UPDATE:** The SME provided the above mockup, which she thought would be a separate page, but on 9/17 we discussed that the new content about the employer consortium could be incorporated into our existing page: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/

## Acceptance Criteria
- [ ] Content addition to existing page goes live.
- [ ] Follow up with stakeholder when it's been published.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
SME and I had an email exchange about how to incorporate the employer consortium info onto our page. This work is on hold until I hear back from Tammy that her leadership wants to proceed with the suggested placement.

**Comment by FranECross** [comment]
Closing old, obsolete ticket.
