### ISSUE TITLE
CH31 - Add Prefill to `vets-api`

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#12739]
## Description
The frontend for Chapter 31 relies on pre-fill working properly in `vets-api`. There's an [existing pull request](https://github.com/department-of-veterans-affairs/vets-api/pull/4757) into `vets-api` that sets pre-fill up, but it requires updates to `vets-json-schema` first. 

## Considerations
- `vets-json-schema` needs to be updated first. 
- [How pre-fill works between FE and BE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/prefill_setup.md)

## Tasks
- [x] Update (or consider restarting) and merge this pull request - https://github.com/department-of-veterans-affairs/vets-api/pull/4757

## Definition of done
- [x] Prefill works properly on the frontend
- [x] Jenkins successfully builds `vets-api` branch after schema updates
