### ISSUE TITLE
Re-format the DIC spouses and dependents spreadsheet for stakeholders

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#12737]
## Issue Description
_In #12645, we moved some parts around on the DIC spouses and dependents rates pages and the spreadsheet needs to be updated to reflect those changes. Two tasks for this ticket: 1/ the tabs should match the order the charts appear on the page. 2/ Strip out the numbers so the cells where the rates go are blank (right now, the cells are populated with rates._

---
## Tasks
- [x] _Reorder spreadsheet tabs to match the updated order that the rates charts as they appear on the DIC page._
- [x] _Strip out the numbers so the cells where the rates go are blank (right now, the cells are populated with rates._

## Acceptance Criteria
- [ ] Spreadsheet tabs will match order of rates charts as they appear on the DIC page
- [ ] Rates amounts on the spreadsheet should also be blank and ready to be filled-in by stakeholder

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Here is the location of the revised spreadsheet: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/content-team-processes/benefit-rates-updating-process/Spouses%20Dependents%20DIC%20rates%20-%20Blank.xlsx
