### ISSUE TITLE
CH31 - Add Schema to vets-json-schema

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#12738]
## Description
The schema used in vets-website needs to be transferred to vets-json-schema so it's available for use in `vets-api`. 

## Considerations
- [ ] Once this lives in `vets-json-schema` it will need to also be included in `vets-website` as well (separate ticket)

## Tasks
- [ ] Add schema to `vets-json-schema`
- [ ] Remove schema from `vets-website`
- [ ] Submit pull request to `vets-json-schema`, `vets-website`, and `vets-api`

## Definition of done
- [ ] Schema has been added to `vets-json-schema`
- [ ] Schema has been removed from `vets-website`
- [ ] A PR has been requested for merging
