### ISSUE TITLE
Need auto-cleaning for base-encrypted AMIs

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#12741]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Base encrypted ami bake job has been failing for a little while now. Upon digging in, the reason suspected became the attempt of the automation to save an AMI named "pre-bake". This is okay, unless there is an attempt to save a new one named this while an old one still exists. The AWS API responds with a duplicate ami name error as AMI names have to be unique. We will implement a fix to allow the job to resume working that will append a timestamp to the name to keep it unique, but will need an automated job to clean these created AMIs up.
## Background/context/resources
_Any additional context for the reader to know, if applicable_ 
- https://dsva.slack.com/archives/CTYQL39FE/p1598279293065700
- https://dsva.slack.com/archives/CTYQL39FE/p1598279539067100
## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] auto cleaning of AMIs created by base encrypted jobs

## Definition of Done
- [ ] base encrypted job is in working order and old AMIs are auto-purged on a set schedule, threshold amount, or some team-defined metric/trigger

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
