### ISSUE TITLE
PW Analytics implementation for Form Detail Pages

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#12757]
## Issue Description
Given we've received GA Data Layer requirements from the Platform Analytics 
I want to use them to implement analytics tracking for Form Detail Pages
so we can measure success of our product and make informed decisions. 

---
## Tasks
- [x] Review DL requirements from Platform team - https://github.com/department-of-veterans-affairs/va.gov-team/issues/4552#issuecomment-677799170
- [x] Implement analytics tracking
- [x] Give Platform team a heads up (#4552)

## Acceptance Criteria
- Platform Analytics team can generate a GA dashboard for Form Detail Pages
