### ISSUE TITLE
[Development] BDD: Make the title of the form dynamic

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#12767]
## Issue Description

Form 526 title needs to change from "File for disability compensation" for both original- and all-claims; but needs to be set as "File for Benefits Delivery at Discharge" for BDD flows.

## Tasks

- [ ] Allow `config/form` title to accept a function to allow dynamically updating the content
- [ ] Add unit tests
- [ ] Update documentation

## Acceptance Criteria

- [ ] Form title can be dynamically updated
