### ISSUE TITLE
[FE] My VA: Fix the Cerner update to "Schedule an appointment" and launch to prod

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12762]
## Background

The VA is adding a new health care platform — Cerner — to its ecosystem. This is a portal, like MyHealtheVet, where people can manage their health care information. I believe the VA's goal is eventually to move all health care functionality so it is supported by Cerner, but this roll out will take years. The VA is launching to one facility at a time and in the meantime, VA.gov has to exist in a world where it points people to Cerner or MHV depending on which facility they go to.

The initial Cerner launch for Columbus, OH occurred last night. This is relevant to our team because an update to My VA was supposed to go out with it, but it didn't. This update was supposed to work as follows:

- For people who go to the Columbus, OH facility, they will see an alert under "Schedule an appointment" that looks like this:

<img width="567" alt="Screen Shot 2020-08-24 at 4 23 28 PM" src="https://user-images.githubusercontent.com/34068740/91092708-6c662280-e626-11ea-954e-be45fb3d7198.png">

- For people who do not go to the Columbus facility, they will see **no changes** on their My VA dashboard to "Schedule an appointment." They will still see that section as it appears now:

<img width="666" alt="Screen Shot 2020-08-24 at 4 26 43 PM" src="https://user-images.githubusercontent.com/34068740/91092854-9fa8b180-e626-11ea-8986-00fdaec0baeb.png">

The work that was done in April — back when Cerner was supposed to launch, but was delayed — in #7286. There was a PR — https://github.com/department-of-veterans-affairs/vets-website/pull/12049 — where this work was supposed to be pushed to staging, but I just checked the staging user this is supposed to be working for and the functionality is not showing up. 

We need to 

- Investigate what is going wrong and why the new messaging for "Schedule an appointment" is not showing up.
- Fix whatever is wrong and get the new messaging to show up.

**Staging user credentials**: https://dsva.slack.com/archives/CU9KYKMM5/p1596219870127100?thread_ts=1596217577.125000&cid=CU9KYKMM5

## Tasks

- [x] Samara to first confirm design and copy is accurate and doesn't need to be updated.
- [x] Investigate what is going wrong and why the new messaging for "Schedule an appointment" is not showing up.
- [x] Fix whatever is wrong and get the new messaging to show up.
- [ ] Have Samara verify everything is working on staging.
- [ ] Launch to prod.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss. Adding latest design/content here as well. Thanks!

![image](https://user-images.githubusercontent.com/62957278/91207399-b0b0fb80-e6d6-11ea-8eb6-bc93636e7839.png)

**Comment by Samara-Strauss** [comment]
Thanks for this! Can you copy/past the copy in plain text here for easier handoff to FE?

**Comment by Samara-Strauss** [comment]
Sorry, forgot to @-you. @DanielleSoCompany ☝️

**Comment by erikphansen** [comment]
This ticket links to a Slack thread that says `ssoissoetesting+mhvcss3@gmail.com` and `ssoissoetesting+mhvcss4@gmail.com` are Cerner patients. But:
- while user `ssoissoetesting+mhvcss3@gmail.com` does have facility 757 listed in their array of facilities, the ESR endpoint is not showing them as being enrolled in health care so the appointment widget is not shown.
- same with user `ssoissoetesting+mhvcss4@gmail.com`. The `GET v0/health_care_applications/enrollment_status` call is not showing them as being enrolled in health care.

In both cases this is the response from ESR:
```
{
  "applicationDate": null,
  "enrollmentDate": null,
  "preferredFacility": null,
  "effectiveDate": null,
  "parsedStatus": "none_of_the_above"
}
```

**Comment by Samara-Strauss** [comment]
So this is basically an issue with staging users not having the right data? I'm going to move this to Slack and tag you in the conversation.

**Comment by erikphansen** [comment]
@Samara-Strauss based on the Slack convo, it sounds like the "fix" for this is to update the `GET enrollment_status` response for these two users who are patients at facility 757.

I can make the alert copy changes that @DanielleThierryUSDSVA requested. But for now are we keeping this alert text static? ie, do we not need to worry about customizing the text based on what Cerner facility they are a patient at?

**Comment by Samara-Strauss** [comment]
> @Samara-Strauss based on the Slack convo, it sounds like the "fix" for this is to update the GET enrollment_status response for these two users who are patients at facility 757.

Yes, going to see if Josh Faulkner can help us.

> I can make the alert copy changes that @DanielleThierryUSDSVA requested. But for now are we keeping this alert text static? ie, do we not need to worry about customizing the text based on what Cerner facility they are a patient at?

@DanielleSoCompany — is Cerner live only for the Chalmers P. Wylie facility, or is the facility name conditional and needs to account for other facilities in the Columbus region?

**Comment by Samara-Strauss** [comment]
@DanielleThierryUSDSVA — I accidentally @-ed your old Github name above ☝️. We've got a question for you to review.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss. Just checked in with Lauren and we believe it's conditional for Chalmers P. Wylie and the 4 community-based outpatient clinics listed here: https://www.va.gov/directory/guide/cboc.cfm?parm=Chalmers%20P.%20Wylie%20Ambulatory%20Care%20Center&id=34.  

Also, I see the request for the copy above too. Here it is!

### Your VA health care team may be using our new My VA Health portal

#### Our records show you’re registered at:

**[facility name]** (Now using My VA Health)

Please choose a health management portal below, depending on the facility for your appointment. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the same account you used to sign in on VA.gov. 

#### Manage appointments at:

**[facility name]**
[button] Go to My VA Health

*Another VA health facility**
[button] Go to My HealtheVet

**Comment by Samara-Strauss** [comment]
Thank you, @DanielleSoCompany!

@erikphansen — updated/final copy is above.

Also, the facility DOES need to be conditional. It could be one of the following:

- Chalmers P. Wylie
- Grove City Community Based Outpatient Clinic
- Marion Community Based Outpatient Clinic
- Newark Community Based Outpatient Clinic
- Zanesville Community Based Outpatient Clinic

**Comment by erikphansen** [comment]
I'm not sure we'll be able to that :( As I recall, when we get the facilities that someone is a patient at, we are really getting the _system_ ID that they are a patient in. In this case all five of these facilities share the same system ID, 757. So we won't be able to tell just from the system ID which is their preferred facility. I'll ask around to confirm this.

**Comment by erikphansen** [comment]
Confirmed that there does not appear to be a way to get all of the _facility_ IDs someone is a patient in, we can only get the _system_ IDs. Yes, we get an array of "facilities" from the `GET user/` API, but those are actually systems.

The good news is that there is an API to look up facility and system information. So, as more systems become Cerner systems, we can show the correct name in the new alert.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @erikphansen. I'm just talking with Kelson and he confirmed this as well. 

So users registered at any of these facilities will get Chalmers as the name.  Sorry about that! There's been a lot of confusion around this.

**Comment by erikphansen** [comment]
No problem at all! I wonder if this is confusing for  Vets, too. If they normally go to one of the other facilities on that list will they be confused when they see messaging about Chalmers?

**Comment by erikphansen** [comment]
Does anyone know when another system will become a Cerner system? ie, when do we need to make this alert flexible and have it look up other system names based on the system ID that we have?

**Comment by DanielleThierryUSDSVA** [comment]
@erikphansen Yes, I think that's a great point that it could be confusing to Vets. Wondering if maybe we should including something like "and certain outpatient clinics" or "and related outpatient clinics" in the name. I'll follow up with a few folks on this and post more thoughts here.

The next facility transitioning to Cerner is Mann-Grandstaff VAMC in Spokane, Washington (and its 4 related community-based outpatient clinics). That will occur in October, and will be for multiple health tools (schedule appointments, refill prescriptions, manage health records, view lab + test results, secure messaging).

**Comment by Samara-Strauss** [comment]
Thanks for clearing this up, @DanielleThierryUSDSVA. Let us know if we need if we need to update the copy at all so it's more clear for vets that go to a facility besides Chalmers P. Wylie.

As for the October update, we can make appropriate updates when the time comes. We'll look to you all for guidance on what to do then.

**Comment by erikphansen** [comment]
For now I'll proceed with keeping this alert hard-coded with the info for Chalmers and we'll make it dynamic next month.

**Comment by erikphansen** [comment]
PR for this is up at https://github.com/department-of-veterans-affairs/vets-website/pull/14089. @DanielleThierryUSDSVA feel free to confirm that the attached screenshot looks good.

**Comment by erikphansen** [comment]
@Samara-Strauss the updated alert should be in staging within 30min. When it's approved I'll make a PR to release this all to prod

**Comment by Samara-Strauss** [comment]
Thanks! I'll check it out once it's in staging.

**Comment by Samara-Strauss** [comment]
This mostly looks good, but the "Schedule an appointment" heading is missing. This prompt should appear under that heading, not in place of it. That's because people are still managing RXs and messages on MHV, and they are only managing appointments on Cerner right now (I know, it is so confusing).

<img width="778" alt="Screen Shot 2020-09-03 at 10 35 44 AM" src="https://user-images.githubusercontent.com/34068740/92129347-63691400-edd1-11ea-8089-0434c7fea4b5.png">

**Comment by erikphansen** [comment]
@Samara-Strauss thanks, looks like that as part of the original implementation from many months ago. It seemed wrong and I should have asked. I'll fix it.

**Comment by erikphansen** [comment]
@Samara-Strauss fixed:
![image](https://user-images.githubusercontent.com/20728956/92131292-ab307100-edba-11ea-9fdc-efd659b9b208.png)

**Comment by erikphansen** [comment]
@Samara-Strauss can you check this on staging again? We might be able to get this out to prod today :-D

**Comment by Samara-Strauss** [comment]
Looks great! I think we can close this and push to prod today.

<img width="724" alt="Screen Shot 2020-09-03 at 1 31 04 PM" src="https://user-images.githubusercontent.com/34068740/92147912-c1095a80-ede9-11ea-8291-ef74b46f00a7.png">

**Comment by erikphansen** [comment]
Merged and released! I'm closing this. I know you validated it in staging and I don't think we can test it in prod.
