### ISSUE TITLE
BGS Lookup Location ID for Veteran by Postal Code for 686

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#12763]
## Background
We need to call the BGS (Regional Office) RO Routing Service to determine the location id based on the Veteran's postal code so that, presumably, the person looking at it is closest to the Veteran.

## Considerations
- The RO Routing Service is designed to publish regional office related oracle packages, procedures and decouple Lines of Business from oracle related packages, procedures. 
- This service doesn’t use tuxedo services.

## Tasks
- [x] Use the method: `GetRegionalOfficeByZipCode` (Retrieve all the regional offices based on the zip code search criteria for each Line of Business.)
- [x] Other tasks use urls that may be deemed sensitive; check email for those details
- [x] Potentially update another ticket with the update of the BGS gem, to be written

## Acceptance Criteria
- [x] Write a test for coverage
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
Draft PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/4948

This is still in draft because our tests will fail until the BGS gem code has been approved and merged.
