### ISSUE TITLE
Spike: VSP Support Thread Tracker

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#12787]
This spike request is the outcome of a meeting yesterday between @a-chappelear, @jchasia-adhoc, @naomimarcussen, @f1337, and @alexpappasoddball, re: tracking support requests.

## Timebox

Limit the initial spike effort to appx 10 hours development effort, and appx 2 weeks calendar time.

## Goals

- Track customer support history
- Measure customer support impact
- Identify trends
- Improve the customer experience
- Improve the support engineer experience

## Action Items:
- [ ] Michael, with help from Andrea, will spike on a very simple Slack app for tracking support requests. The following are ideas:
  - [x] Command to mark a thread as a support thread: `@support track!`
  - [ ] Command to get a list of all support threads marked for a time period: `@support list 2w` . The output will be copied and pasted into a support spreadsheet (for now).
  - [ ] Command to categorize a support thread: `@support category Something`
- [ ] Andrea will review the existing support categories for revision, if needed

**Comment by alexpappasoddball** [comment]
@f1337 is this something we still need on our board?  Or can this be closed or moved to another board you are working off of?

**Comment by f1337** [comment]
It's basically done. And at this point needs to become a maintenance project for a team. Probably product support? We're still discussing that part. Anyhoo, closed!
