### ISSUE TITLE
Design intent Collaboration [Address Project Form 10-10EZ]

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#12789]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [X] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [X] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [X] VSP <> **requesting team** design intent collaboration meeting completed
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product [outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/project-outline.md)

**10-10EZ Flow**
- [Flows 10-10EZ.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5132906/Flows.10-10EZ.pdf)

**Flows for four use cases**
- [Flow Unathenticated.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5143470/Unathenticated.pdf)
- [Flow Profile Complete.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5143479/Profile.Complete.pdf)
- [Flow Authenticated-Partial-filled.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5143482/Authenticated-Partial-filled.pdf)
- [Flow Authenticated-Blank-Address.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5143487/Authenticated-Blank-Address.pdf)

**Mockups**
- Initial [Unauthenticated mockups](https://vsateams.invisionapp.com/share/RPYKB0VNA68#/429844356_Unathentictaed-Mailing-Address-V-1)

- Initial [Authenticated mockups-Profile complete](https://vsateams.invisionapp.com/share/RPYKB0VNA68#/429934942_Athenticated-Profile-Complete)

- Initial [Authenticated mockups-Partially filled](https://vsateams.invisionapp.com/share/RPYKB0VNA68#/429935810_Athenticated-Profile-Partially-Filled)

- Initial [Authenticated mockups-Empty profile](https://vsateams.invisionapp.com/share/RPYKB0VNA68#/429936412_Athenticated-Blank-Profile)

## Meeting attendees from **requesting team**
- Designer(s) (required): **Jonathan Nelson**
- Product Manager (optional): **Alayna Abel**
- DEPO design lead (required as applicable): **Kevin Hoffman**

## Scheduling
- [X] Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- [x] Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now 

- [X] Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite

**Monday, August 31st 3:30 PM EST**

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled for August 31 3:30 PM EST

**Comment by jonathanjnelson** [comment]
Thank you all for the feedback! 

Here is screen cap of Profile: 

<img width="593" alt="Screen Shot 2020-08-31 at 4 01 46 PM" src="https://user-images.githubusercontent.com/58444931/91762454-61217280-eba3-11ea-8b1d-98c04ebe8a49.png">
