### ISSUE TITLE
Updating Sign In FAQ and Sign In Modal

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#12785]
## Issue Description
Now that VA.gov has a fully dedicated contact center to handle VA.gov technical issues, we need to update the sign in modal and and sign in FAQ page to point people to the contact center if they are in need to support. _Note:_ we will be removing the sign in issue form. This is because we currently staff that with one person and the volume is too much to answer these questions in a timely manner.

---
## Tasks
- [ ] Draft new language for sign in FAQ page
- [ ] Remove sign in issue form from sign in modal

## Acceptance Criteria
- [ ] Sign in issue form will be removed from sign in modal
- [ ] Sign in FAQ content will be changed to direct users to the MyVA311 number for additional help
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
