### ISSUE TITLE
Modify Lighthouse Developers Group to allow access for various job-related services

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#12793]
## Description
It seems that the main services that Lighthouse devs need access right away, are services in AWS. This means they would need limited AWS access (only to CodeBuild) as soon as they are onboarded in order for them to start working.

## Background/context/resources
Ref: 
- https://dsva.slack.com/archives/CJYRZK2HH/p1598369837054900
- https://dsva.slack.com/archives/CJRQ85PQB/p1598370787061800

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] _Create a IAM group for Lighthouse devs so they can access CodeBuild_
- [ ] _update docs around access to ensure others know this new flow_

## Definition of Done
- [x] _Group is tested out and access limited_
- [x] _connect with Demian and TJ_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by ricetj** [comment]
Doc will be updated as part of the clean up.
