### ISSUE TITLE
10-10CG Signature page (two check boxes) 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#12794]
## Issue Description
As a CSC,
I would like to see a PDF that indicates whether the Primary Family Caregiver is:

An immediate family member
Not an immediate family but currently lives with the Veteran full time or will do so upon to approval to the PFAFC
Note: designs are still in progress, and it's possible we might not need to make any front end changes.

---
## Tasks
- [X] Redesign signature page 
- [X] Present recommendations to stakeholder  
- [ ] Implement change in front end 

---
## Current design

**For awareness**

<img width="489" alt="Screen Shot 2020-10-13 at 12 13 48 PM" src="https://user-images.githubusercontent.com/58444931/95887250-9ba72f00-0d4d-11eb-9e3c-f467fd66a716.png">

## Recommendations

**Option 1: No form changes**

- Currently collect Caregiver’s relationship with Veteran (used to determine family member or non-family member)
- Caregiver is certifying they reside, or will reside with Veteran on signature page
- Can use info gathered to check box on the PDF that gets sent to CARMA

**Option 2: Radio within signature box**

<img width="487" alt="Screen Shot 2020-10-13 at 12 13 22 PM" src="https://user-images.githubusercontent.com/58444931/95887336-b5e10d00-0d4d-11eb-8795-feb3b11298d8.png">

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
Team presented **Option 1** and **Option 2** to stakeholders October 9, 2020. 

Cari noted that they were going to think about options and let the team know.

**Comment by jonathanjnelson** [comment]
The Caregiver program team would like the user to make a selection on the signature page 

**Current design**

![Screen Shot 2020-10-20 at 4 38 30 PM](https://user-images.githubusercontent.com/58444931/96647504-64a7bf00-12f3-11eb-8cfe-ec0a1fd6d0d4.png)

**Redesign**

![Screen Shot 2020-10-20 at 4 38 12 PM](https://user-images.githubusercontent.com/58444931/96647644-aafd1e00-12f3-11eb-8135-594738cb5e2b.png)

**Comment by jonathanjnelson** [comment]
Hi @LinnJS  

Here are the[ updated mockups for signature page ](https://vsateams.invisionapp.com/share/WCZ0WFY7DJ3#/433727791_Signature_-_Replacement_) I also shared the InVision file with you. Let me know if you want me to put screen caps of updated designs in this ticket and if you have any questions. 

**Current Design**

- [ ] Remove "I certify that I am a family member of the Veteran named in this application or I reside with the Veteran, or will do so upon designation as the Veteran's Primary Family Caregiver." 

- [ ] Replace "or his" with (or designee) 

- [ ] Add radio options

![Screen Shot 2020-10-21 at 8 37 45 AM](https://user-images.githubusercontent.com/58444931/96727480-b3e40300-1378-11eb-99c3-500660730d00.png)
