### ISSUE TITLE
Security Review for Direct Deposit Functionality #17530

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1280]
Context: 

- [x] Review looking for potential technical security issues, vulnerabilities, focusing particularly  on frontend-backend interactions, anything involving certificates or cookies, and any new interactions with dependent backends. 

Acceptance Criteria
- [x] This has been completed. No technical security issues or vulnerabilities are present with dependent backends. 

------------------------------------------------------------------------------------------
- [x] **Email notifications should go to all addresses on file** [ #1731](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1731)
i.e. the identity address, not just the Vet360 one --- concern about attacker changing Vet360 address before updating direct deposit info

- [x] **Ensure that “LOA3 & multi-factor” are enforced at vets-api level** [#1732](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1732)
Make sure this is explicitly enforced in vets-api

- [x] **Sentry field names: everything needs to be sanitized ** [#1733](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1733)
Looks like only account_number is currently sanitized

- [x] **Confirm we're filtering same data from other (non-Sentry) logging** [#1734](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1734)
Should be OK because whitelist, but please confirm

- [x] **File a ticket to investigate what happens to Sidekiq failures** [ #1735](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1735)
Doesn't have to be followed up on before launch

**Comment by Justin-Pickett** [comment]
This review was completed 9/9/19. There are some items that need to be completed before launch but nothing blocking launch.

**Comment by lihanli** [comment]
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19647

**Comment by lkoenigsberg** [comment]
Security review was completed on 9/10 where 5 issues were identified to be fixed prior to launch and two future changes.  These are all documented in the ticket references above.

@Justin-Pickett will create tickets for each of the issues, assigning the 5 for launch to @lihanli 
 in sprint 4.

This ticket can be closed once the 5 vulnerabilities are completed.

**Comment by Justin-Pickett** [comment]
corresponding security review tickets have been created. Closing this ticket.

**Comment by Justin-Pickett** [comment]
@gunsch can you validate that the recommended changes from the Direct Deposit security review have been completed. I have listed the 5 items that needed to be corrected before launch above. Once you've verified the items have been completed (PR's have been merged) can you respond back to this ticket that they have. Thank you.

**Comment by gunsch** [comment]
Confirming they've been completed (and I checked off the AC boxes above). Thanks for organizing things this way, this was pretty easy to follow.

I reopened https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1735 because that was intended to be a conversation starter --- not blocking launch, but probably a few things we ought to investigate / follow up on in the future.

I'm OK with the state of this launch from security perspective. Good luck!
