### ISSUE TITLE
Adjust the Step-Child Leaving Household Workflow In Submission

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12815]
## Background
After testing internally, it was noticed that some of the information that gets passed for the step-child as they leave needed an expanded relationship with the child and the guardian.  (Like spouses and former spouses)

## Considerations
- Check Derek's whiteboard
- Clear test users's EP
- This will have two PRs (`lib` and `bgs_dependents`)

## Tasks
- [ ] Write code
- [ ] Write tests for coverage

## Acceptance Criteria
- [ ] A PR has been requested for merging into `lib`
- [ ] A PR has been requested for merging into `bgs_dependents`

**Comment by digitaldrk** [comment]
`models/bgs_dependents` 
https://github.com/department-of-veterans-affairs/vets-api/pull/4791
