### ISSUE TITLE
[Frontend] Debt Letters - Update content in the coronavirus empty state

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#12811]
## Issue Description
_Peggy provided updated content for the coronavirus empty state in the Debt Letters tool. [The content can be found in this UXPin prototype.](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174235/simulate/no-panels?mode=i)_

---
## Tasks
- [ ] _Update the coronavirus empty state with the new content_
- [ ] _Review updated alert with designer_

## Acceptance Criteria
- [ ] _The content on the frontend matches the content in the UXPin prototype_
- [ ] _The updated UI has been approved by a designer_
