### ISSUE TITLE
Adjust SSN and DOB for 686 Workflows

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12826]
## Background
In performing the partner integration testing we have identified that we need to add a field to the front end for the 686. So far we know we need to add a SSN field to the workflows, we may need to add more fields but that is still to be determined at this time.

## Considerations
There are 5 workflows:
1. Remove divorced spouse
1. Remove stepchild
1. Remove deceased dependent
1. Remove married child
1. Remove child left school

## Tasks
- [x] Remove the logic for combining report a divorce and adding a spouse workflow as the RBPS requirements need more specificity
- [x] Add SSN and DOB field to 686c-674 schema in `vets-json-schema`
- [x] Bump version number for 686c-674 schema in `vets-json-schema`
- [x] Submit a PR for `vets-json-schema`
- [x] Add SSN and DOB field uiSchema to config file for the workflows
- [x] Change the commit hash for `vets-website`
- [x] Adjust unit tests for 686c to still pass
- [x] Adjust e2e test for the workflows workflows to still pass
- [x] Submit PR for review to `vets-website`

## Acceptance Criteria
- [x] SSN and DOB field has been added to `vets-json-schema`
- [x] Version number for 686c-674 schema in `vets-json-schema` has been bumped
- [x] A PR for `vets-json-schema` has been requested for merging
- [x] SSN and DOB field uiSchema to config file for the workflows has been added
- [x] Commit hash for `vets-website` has been added
- [x] Unit tests for 686c to still pass
- [x] e2e test for the workflows to still pass
- [x] PR for review to `vets-website` has been requested for merging
