### ISSUE TITLE
Logic for facility health services 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12822]
## Issue Description
The VAMC health services content structure has changed from blobby content to discrete reusable components in Drupal. We need to update the front end to accommodate this new data structure. 

<details>
<summary> Current UI </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b0a2f750-f45e-4941-96bc-88d206de7608) 

</details>

The first step to implementing this new structure is to get logic in place and ensure no content is left behind. 

---
## Tasks
- [ ] Get logic in place for facility health service components
- [ ] Confirm additional design modifications (beyond hours) are not needed 

## Acceptance Criteria
- [ ] No data is lost in implementation. Facility health service location and contact info area still contains:

- Intro text
- Location information (including building, suite, wing, room, etc)
- Link to campus map
- Main phone number (minimum)
- Hours of operation
- Appointments
- Referral
- Wait time/satisfaction scores
- Care we provide at (facility) with text intro and list of services

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
