### ISSUE TITLE
Add logic for showing/ hiding the Static Veteran Information page based on if the user is logged in or not for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12829]
# Background
We need to add the logic to either hide or show the Static Veteran Information page based on if the user is logged in or not. This same logic will most likely be used in a separate ticket to also hide and show the dependent information pages based on if the user is logged in or not since at this point if you are logged in then you are not a dependent of a Veteran.

## Tasks
- [ ] Pull in prefill data using the `isLoggedIn` flag
- [ ] Add the `isLoggedIn` flag from the formData to the helper function for `isVeteran`
- [ ] Add another helper function that used the `isLoggedIn` flag to hide the Static Veteran page
- [ ] Submit a PR to `vets-website` for review

## Acceptance criteria
- [ ] The Static Veteran Information page hides if the user is logged in
- [ ] A PR has been submitted for review
