### ISSUE TITLE
New VFS Team onboarding next steps: VAOS

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1282]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [ ] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist
- [ ] Attend general onboarding meeting
- [ ] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [ ] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [ ] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [ ] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [ ] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md)
- [ ] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [ ] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [ ] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/DigitalModernizationStrategy.pdf)
- [ ] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/The-new-VA.gov-briefing-2019-07.pdf) documentation
- [ ] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [ ] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md)
  - [ ] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [ ] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [ ] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [ ] Designers: Attend breakout session
- [ ] Engineers: Attend breakout session
- [ ] Full team: Attend the Discovery and Logistics Workshop
- [ ] Front-end Engineers: Attend deep-dive session
- [ ] Back-end Engineers: Attend deep-dive session
- [ ] PM, Designers and Content Writer(s): Request content and IA intro with @mnorthuis @peggygannon @thatmattjohnson 
- [ ] PM and Front-End Engineers: Request analytics intro
- [ ] PM Request 508 intro with @1Copenut 
- [ ] PM and Engineers: Request load testing, privacy, and security intro (include content around working in a public repo) with @peterhill-oddball 
- [ ] PM and Engineers: Request ATO intro

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [ ] Assign the issues to individual(s) to complete
- [ ] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [ ] Attach the issues to this Epic

**Comment by rroueche** [comment]
Updated the title of this epic so that it's different from VSP's epic to actually onboard VAOS.

**Comment by mnorthuis** [comment]
Updated the links above. These all changed with the updates to the va.gov-team repo last week.

**Comment by andreahewitt-odd** [comment]
@markgreenburg Hey can you fill out this epic so we can identify any gaps?

**Comment by lenaecb** [comment]
@andreahewitt-odd - I am reviewing this epic now as part of my onboarding as well as prepping for our MVP phased rollout. Is there any way to get the issue updated with the new links? All the links to the resources are broken. 

Thanks!
