### ISSUE TITLE
Connect FE to BE for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12834]
# Background
Now that the backend has been set up for CH36 we need to adjust the Redux code to use the actual API endpoint set up for it.

## Considerations
- Using this in the url: `/education_career_counseling_claims/`

## Tasks
- [x] Change submit URL for CH36 form
- [ ] ~Adjust data structure based on data that comes back from the API endpoint~
- [x] Submit a PR for `vets-website` for review
- [x] change `dependentAddress` to `claimantAddress` so military base works. 

## Acceptance criteria
- [x] The submit URL on CH36 has been updated to match the BE
- [x] A PR has been submitted for review
