### ISSUE TITLE
Write Unit Test for Static Claimant Information Page (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12833]
# Background
In order to make sure that the Static Claimant Information page behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the static claimant info page.

## Tasks
- [ ] Set up test file
- [ ] Write unit tests for Static claimant Information page
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The static Information page is unit tested it 80% coverage
- [ ] A PR has been submitted for review

**Comment by jason-gcio** [comment]
Dupe of #12833?
