### ISSUE TITLE
Unit Test Claimant Address on CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12831]
# Background
In order to make sure that the Dependent Address page on Chapter 36 behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Claimant Address page.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for Dependent Address page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Dependent Address page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
