### ISSUE TITLE
e2e test Veteran workflows for both NOT logged in for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12835]
# Overview
In order to make sure that workflows for a Veteran that is logged in and for one that is NOT logged in filling out the CH36 form is fully e2e tested.

## Tasks
- [x] Set up test file
- [x] Write e2e test for the Veteran workflows
- [x] Submit a PR for review

## Acceptance criteria
- [x] These user paths for the Chapter 36 form has been e2e tested
- [x] A PR has been submitted for review
