### ISSUE TITLE
[Business Optimization] Work with VHA to find why systems are not in VAST and HOW to get them added ASAP [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12838]
## Story
_As a VAMC System administrator, I need all facilities that are not listed in VAST updated, confirmed, and listed, so that I can properly host and associated those facilities to the correct system and VISN.

## Resources
[facility locator updates](https://vaww.va.gov/WEBCOM/VAMC_Facility_Location_Updates.asp)

## Tasks
- [x] List all facilities not in VAST/CMS_
- [x] Provide list to VHA team to get confirmed
- [x] Help facilitate VHA or VAMCs to update VAST using Facility locator updates

## Acceptance Criteria
- [x] Facility discrepancies have been provided to VHA
- [x] Solution to have issues submitted or awareness that they need to be listed have been provided to VHA and VAMC teams.
- [x] If no action can be taken, the issue is escalated
---

**Comment by SgardnerPMP** [comment]
Had issues with MAC approval. Met with VHA on 9/10/2020
