### ISSUE TITLE
Unit test Veteran Address on Chapter 36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12832]
# Background
In order to make sure that the Veteran Address page on Chapter 36 behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the Veteran Address page.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for Veteran Address page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The Veteran Address page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
