### ISSUE TITLE
Add Logic For Showing/ Hiding Dependent Information and dependent address pages based on if user is logged in or not for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#12830]
# Background
We need to add the logic to either hide or show the Dependent Information page and Dependent Address page based on if the user is logged in or not.  

## Considerations
- If you are known to the VA, you can log in with ID.me (or DSLogin) and I will have prefillable data base on my profile, and there is no telling whether you are a Veteran or a dependent, etc.
- Selection screen will always be available, at this point until roles and relationships are better established.

## Tasks
- [ ] Pull in prefill data using the `isLoggedIn` flag
- [ ] Add the `isLoggedIn` flag from the formData to the helper function for `isDependent`
- [ ] Submit a PR to `vets-website` for review

## Acceptance criteria
- [ ] The Dependent Information page and Dependent Address page hides if the user is logged in
- [ ] A PR has been submitted for review
