### ISSUE TITLE
[VAMC] Create new System pages for all VISN-6 Systems so Owner/Governance can be created by CMS [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12841]
## Story
_As a CMS engineer, I require System pages to be created, so I can associate an owner and governance to a system.

## Resources
---
## Tasks
- [x] _Create the following System pages:
- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care
* Create following in CMS Support Channel & Slack Kevin Walsh/Steve Wirt
- [x] Request to have all of the above Owner/Governance created in drop down

## Acceptance Criteria
- [x] _Full list of systems needing to be added to governance has been submitted to CMS Support Channel.
---
