### ISSUE TITLE
[VAMC-Scaffolds] Create or Clone all required pages for VA Hampton health care in VISN 6 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#12842]
## User Story 
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required VAMC-upgraded va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Clonable Website](prod.cms.va.gov)

## Tasks
_Creation of the following Drupal types/menus and pages_
* All pages are cloned or created, the System name, Related office or Health Care system, Owner, Meta title, Meta Description, and Menu items are updated.

- [x] Go to System Page (Already Created) for VA Hampton health care
    * Add System page in Menu below VA Hampton health care
    * Remove all previous Facility Ids and then link the following Facility pages to Main System 
- [x] vha_590	Hampton VA Medical Center
- [x] vha_590GB	Virginia Beach VA Clinic
- [x] vha_590GC	Albemarle VA Clinic
- [x] vha_590GD	Chesapeake VA Clinic

* Next Section
- [x] Health Services Listing Page (Clone from Montana VA health care)
    * Add to Menu just below System page
- [x] Location Listing Page (Clone from Montana VA health care)
    * Add to Menu Just Below Health Services

* Next Section:
- [x] About us Page (Clone from Montana VA health care)
    * Add to Menu under About VA Hampton
- [x] Mission-Vision (Clone from Montana VA health care)
    *  Add to Menu under About us 
- [x] History (Clone from Montana VA health care)
    * Add to Menu under About us 
- [x] Performance Page (Clone from Montana VA health care )
    * Add to Menu under About us 
- [x] Leadership Listing Page (Clone from Montana VA health care)
    *  Add to Menu under About us 
* Next section:
- [x] Work with Us Page (Clone from Montana VA health care)
    * Add to Menu under About VA Hampton
- [x] Jobs and Careers (Clone from Montana VA health care )
    * Add to Menu under Work with Us
- [x] Internship and Fellowship (Clone from Montana VA health care)
    * Add to Menu under Work with Us
- [x] Volunteer and Donate (Clone from Montana VA health care)
    * Add to Menu under Work with Us
* Next Section:
- [x] Policies Page (Clone from Montana VA health care Montana VA health care )
    * Add to Menu under About VA Hampton
- [x] Contact us (Clone from Montana VA health care)
    * Add to Menu under About VA Hampton

* Items below do NOT need menu items associated to them
- [x] Make an Appointment
- [x] Register-for-Care
- [x] Billing
- [ ] Contact-us		
- [x] Dav-vans
- [x] Medical-Records
- [ ] Operational Status
- [x] Pharmacy
- [x] Caregiver
- [x] Homeless
- [x] LGBT
- [x] Mental
- [x] Minority
- [x] Patient
- [x] Returning Service member
- [x] Suicide prevent
- [x] Women-vet
- [x] Campus Map
- [x] Champlain Services

## Acceptance Criteria
- [x] Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [x] Validate that all menu pages show up in Menu and are visible in the correct order on the menu
- [x] Validate that pages are ready to take data load information
- [x] All system pages listed above have been created

**Comment by lealester** [comment]
Operational status not required; contact us listed twice
