### ISSUE TITLE
AE-Sprint 29

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12854]
# Priorities
1. Validate/get update on Profile 2.0 analytics
2. Kick off UAT recruiting
4. Conduct UAT
5. LIH initial design work/Technical discovery
6. Direct Deposit integration discovery
7. MyVA Cerner Update

### PM
- [x] [PM] Regroup with analytics to regarding profile 2.0 #12856
- [x] [PM] Schedule UAT user set up meeting #12857

### Design
- [x] Kick off UAT recruiting
- [x] [Design] Conduct UAT #12859
- [x] 508-defect-4 [MOBILE DESIGN] Consider abutting mobile subnav to the top of viewport #11890
- [ ] [Design] Connect with VAOS team to go over appointments #12896

### Build
- [x] Add tests for SMS appointment reminders checkbox #11982
- [x] Add tests for updating addresses #11983
- [x] [FE] Launch Profile 2.0 to production behind a feature flag #12860
- [ ] Profile does not properly handle a contact field update without any changes #12632
- [x] Inconsistent "cancel" button styling #12010
- [ ] Appointment reminders via SMS checkbox does not handle a failure to create transaction #12751

### Design
- [x] Discuss a plan and start initial design iterations/explorations #12861
- [ ] Track the documentation from the LOA3/LOA1 use case/data point exercise in Github #12862
- [x] Plan for how/when to conduct user testing #10518

### Dev 
- [x] How are we going to build the logged-in homepage? #10256
- [x] Investigate what data we have access to for prescriptions on the My VA dashboard #12902
- [x] [FE] Logged-in homepage: How are we going to build the logged-in homepage? #10256

## Direct deposit
- [x] Determine level of effort for integrating with BGS CH33 DDEFT Services #11545

## My VA: Cerner update
- [x] Fix the Cerner update to "Schedule an appointment" and launch to prod #12762

## Unplanned/QA/508/Bug fixes
- [x] Profile 2.0 bug: Direct deposit isn't working #12977
