### ISSUE TITLE
[PM] Regroup with analytics to regarding profile 2.0

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12856]
## Background

We need to regroup with the analytics team to get an update on where things are and confirm that the data we requested will be included and get an overview of the metrics/labels and their meanings.

## Tasks
- [x] Set meeting with analytics team
- [x] Get update on when profile analytics will be ready
- [x] Get quick walk through on analytics terms to ensure we know what we are looking at and what each metric label means
- [x] Review the proposed organization of Profile analytics
- [x] Determine any required next steps
