### ISSUE TITLE
Separate Terraform 'modules' directory in devops repo into discrete module repositories

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#12865]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
In order to have proper versioning for Terraform modules, we need to separate them each into their own github repository.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 
Some modules depend on one another, so we will need to make sure to update those dependencies or merge modules when appropriate.

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Each module should be moved to it's own repository._

## Definition of Done
- [ ] _All TF modules live in their own repo._

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
