### ISSUE TITLE
[Design] My Documents - Dropdown search filter (mobile) 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#12866]
## Issue Description
_In order to provide Veterans the ability to quickly search for the documents they need, we're going to explore a search filtering component._

---
## Tasks
- [ ] _Research existing search filtering functionality (tip: Facility Locator tool)_
- [ ] _Design a concept for a mobile search filtering component in the My Documents UXPin prototype_
- [ ] _Present mobile search filtering component to team & at the design intent check-in_
- [ ] _Link the UXPin prototype with the component to this ticket_

## Acceptance Criteria
- [ ] _A design for the search filtering component is created and shared for feedback_
- [ ] _UXPin prototype is linked in this ticket_
- [ ] _Ticket(s) for additional iterations and/or frontend development are created and linked to this ticket_
