### ISSUE TITLE
Investigate EVSS Submission Process for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12879]
## Background
As an interim step, we might want to use EVSS to submit CH31 until the VRE API is ready.

## Tasks
- [ ] Discover what is required to submit using EVSS 
- [ ] Discuss the cost/benefits of implementing in EVSS as opposed to waiting until the VRE API is ready to go.

## Acceptance Criteria
- [ ] A decision can be made surrounding which direction to take

**Comment by steve-gov** [comment]
Looked into it, no good path forward. Will be integrating with VR&E's custom CMS API instead.
