### ISSUE TITLE
Adjust 686 Mockups with New Information

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12872]
## Goal
We want to ensure that the prototypes for 686 are reflecting the latest info from stakeholders so that we can share the list of changes more directly with the FE and the BE.

## Considerations
While these fields are not asked for on the form, they are required for BGS-RBPS.

## Tasks
- [x] Add required SSN and DOB fields to these workflows
  - [x]  "Report a Divorce" 
  - [x] "Married Child"
  - [x] "Step-Child leaves Household"
  - [x] "Death of a dependent"
  - [x] "Child leaves school"
- [ ] ~~Add Guardian to "Step-Child leave household" when they are not living with the Veteran~~
  - [ ] ~~First name, Last name~~
  - [ ] ~~Address~~

## Acceptance Criteria
- [x] The changes above have been implemented into the mockups
- [x] A concrete list of changes has been shared with FE

**Comment by sporeboy** [comment]
Fields added to mockups:

- Remove stepchild -- https://xd.adobe.com/view/f683f361-0a0d-4b7e-796e-49d0a8265195-80b2/
- Dependent's death --  https://xd.adobe.com/view/1506a12d-12af-49d2-4137-97bb5a06fa11-6337/
- Report divorce, Child marriage & Student left school -- https://xd.adobe.com/view/7c724f92-3619-4c7f-5fa8-c355bb2e85c9-0a43/

**Comment by jason-gcio** [comment]
Great, thanks for catching these docs up.
