### ISSUE TITLE
IRIS Q&As: Batch 1 

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#12886]
All account, profile and other general (or not benefit-specific) faqs need to be migrated out of IRIS and into Drupal for the October launch of the learning center MVP. Because learning center templates are not yet available in Drupal, copyediting will be done in Word doc form. 

### Tasks

- [x] PW to pull faqs into Word doc (Laura)

- [x] PW to develop draft copy (Laura)

- [x] PW to create new GH ticket for content review (Laura)

- [ ] PW to assign front-end tags (max of 4 for MVP launch) and back-end categories to each Q&A (Laura)
Reference material for background on this task: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md (Also, see info below checklist)

**Front-end topic tags (probably these will be the 2 tags you'll use for all MVP Q&As)**
VA account and profile
Other topics and questions (formerly "General")

**Front-end audience tags (not sure you'll use these for MVP launch of acct and profile/other topics and questions)**
- All Veterans - Content author can select the broad category "All Veterans" or one of the sub-Veteran tags:
- Veterans age 65+
- Former prisoners of war
- Gulf War Veterans
- Incarcerated Veterans
- Korean War Veterans
- LGBTQ Veterans
- Minority Veterans
- Native American Veterans
- Vietnam War Veterans
- Women Veterans
- World War II Veterans

- Family members and caregivers
- Service members

### Acceptance Criteria

- [x] First draft copy deck attached to ticket 13354 (https://github.com/department-of-veterans-affairs/va.gov-team/issues/13354)

**Comment by lwalsh617** [comment]
Opened content review ticket and closing this one.
