### ISSUE TITLE
Debt Letters - Workshop #6

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12899]
## Issue Description
Conduct diary code workshop w/ DMC

---
## Tasks
- [x] Conduct the final diary code workshop on 8/26/2020
- [x] Consolidate decisions made and upload to GH

## Acceptance Criteria
- [x] Workshop conducted
- [ ] Decisions documented in GH

**Comment by rebeccawalsh** [comment]
Workshop board can be found here: https://miro.com/app/board/o9J_koiaiGk=/
Consolidated workshop Excel sheet has been sent as an .xlsx to be iterated upon ([Google drive version here](https://docs.google.com/spreadsheets/d/1MyExcHJu-c2yvDb2MLkrnLmNrGM0b6BVObrYFCqni7c/edit#gid=0))

Holding off on actually adding these to GH as they will likely change a ton.
