### ISSUE TITLE
[Design] My Documents Conversation Guide 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12895]
## Issue Description
_To kick off discovery research for My Documents, we need to write a research plan using [the provided template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)._

---
## Tasks
- [x] Write a conversation guide for the My Documents discovery research
- [x] Send the completed conversation guide to Shawna for feedback
- [x] After the conversation guide is approved by Shawna, send the document to Lauren to kick off the recruiting process.

## Acceptance Criteria
- [x] Shawna has approved the conversation guide
- [x]  The conversation guide is uploaded to GitHub and linked to this ticket
- [x] The conversation guide is sent to Lauren

**Comment by rileyorr** [comment]
Got a draft of the conversation guide [here](https://docs.google.com/document/d/1mFup8fYnhKHLynCWhmOslCw8aIzpEVVlTIV1UD4WCAA/edit?usp=sharing). Gonna clean it up a bit tomorrow and send to Becca for feedback & so she has a chance to add additional questions she wants asked during the study :)

**Comment by rileyorr** [comment]
I've added [the conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/eFolders_Migration/research/discovery-sept20/conversation-guide.md) to GH and am waiting for Shawna's feedback/approval. I'm likely going to push the research dates by 1 day to account for Shawna's review time and give Perigean the required full week for recruiting.

**Comment by rileyorr** [comment]
Incorporated Shawna's feedback and sent the research plan + convo guide to Lauren
