### ISSUE TITLE
[Design] My Documents Discovery Research Plan 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12894]
## Issue Description
_To kick off discovery research for My Documents, we need to write a research plan using [the provided template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)._

---
## Tasks
- [x] _Write a research plan for the My Documents discovery research_
- [x] _Send the completed research plan to Shawna for feedback_
- [x] _After the research plan is approved by Shawna, send the document to Lauren to kick off the recruiting process._

## Acceptance Criteria
- [x] _Shawna has approved the research plan_
- [x] _The research plan is uploaded to GitHub and linked to this ticket_
- [x] _The research plan is sent to Lauren_

**Comment by rileyorr** [comment]
Got a draft goin' [here](https://docs.google.com/document/d/1UlpAeWwXGlcZRTO39ia9YsPsGJAjqbOlYbv270hLqng/edit). Waiting on feedback before finalizing :)

**Comment by leahkeeler** [comment]
Hey @rileyorr Can the participants be qualified on 1-If they have ever logged into MyFolders on eFolders and b) If they have more then a certain amount of documents there -- if they have like 2 sorting and filtering won't be of much use.

**Comment by rileyorr** [comment]
Hi, @leahkeeler! Thanks for providing feedback about the research plan :) 

> If they have ever logged into MyFolders on eFolders

Just to clarify, do you mean if folks have logged into eBenefits to use the My Documents tool?

I'm not sure folks will be able to pick out the tool's name in a screener question, so I can add a requirement that participants have used eBenefits to look for PDF documents in the past. 

> If they have more then a certain amount of documents there -- if they have like 2 sorting and filtering won't be of much use

Since documents are generated when Veterans added to VA's system, it sounds like folks will have multiple documents anyway (there's 1,164 unrestricted document types in the Excel spreadsheet Cam sent us). I just reached out to Cam about this; however, if there's no way for us to determine how many Service Personnel Records are on every Veteran's file then we can add a requirement that folks have submitted a benefit claim or use VA healthcare since those benefits seem to generate a lot of documents.

**Comment by rileyorr** [comment]
Okay, so I reached out to Cam and it turns out we're not receiving all the unrestricted documents in the Excel sheet he provided. We're receiving a subsection of that spreadsheet, but there's no way to determine what's contained in that subsection. Fun times!

I'll include the requirement that some folks have submitted a benefit claim since that has a greater chance for multiple documents. However, I don't think that should be a requirement for every participant because we'll also want to see how many documents people have on average.

**Comment by leahkeeler** [comment]
fun fun times - makes sense - it will be interesting to see if it's pages and pages

**Comment by rileyorr** [comment]
I've added [the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/eFolders_Migration/research/discovery-sept20/research-plan.md) to GH and am waiting for Shawna's feedback/approval. I'm likely going to push the research dates by 1 day to account for Shawna's review time and give Perigean the required full week for recruiting.

**Comment by rileyorr** [comment]
Incorporated Shawna's feedback and sent the research plan + convo guide to Lauren
