### ISSUE TITLE
Audit VA.gov for account and profile content to pull into LC for MVP launch

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12892]
## Issue Description
Assess root-level pages and others for inclusion in LC within the account and profile grouping of FAQs. What should move over?

List of pages to assess:

![image](https://user-images.githubusercontent.com/53535663/92013471-d6b04e80-ed1b-11ea-9623-8308026a46bf.png)

---
## Tasks
- [ ] Assess VA.gov root-level pages for account & profile and general categories content
- [ ] Assess other pages for account & profile and general categories content (talk to Beth about what else might move)

## Acceptance Criteria
- [ ] Completed list of account-and-profile-related pages in tier 1 content

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
team to meetup next week to see what content can be added to LC and drive users to appropriate tools

**Comment by bethpottsVADEPO** [comment]
**These 2 pages are in consideration for partial move to LC** (i.e., keep them at the root level with the tool/widget intact on that existing page, but move some of the Q&As on them over into LC). This is still a bit up in the air, but this is the current thinking:

https://www.va.gov/change-direct-deposit/
https://www.va.gov/claim-or-appeal-status/

**This page will have all of it's content moved to LC and it's url will be redirected:**
https://www.va.gov/sign-in-faq/

**This page will remain intact as is in tier 1** at the root level (and a step-by-step page will be created for LC):
https://www.va.gov/change-address/

**Comment by bethpottsVADEPO** [comment]
Closing this ticket as the R&S side of the work has been done. I'll create a separate ticket for the changes needed to the remaining root level pages once R&S launches to account for the content that needs to be removed from them because we've brought it over into new R&S articles.
