### ISSUE TITLE
Create CH36 PDF for Eventual Submission to Central Mail

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12901]
## Background
The VRE CH36 feature does not have a backend like some other features where structured data is being sent to a lower environment or system for data processing; Central Mail acts like a PDF depository.  Once a pdf has been created, it can then be sent to Central Mail likely accompanied by certain requisite data pieces that help identify who the PDF belongs to and its final destination.  These metadata will most likely be in another PR.

## Goal
We need to ensure that the PDF is created (from form data) first so it can be later sent to Central Mail (in another ticket/PR).

## Considerations
- [Link to form and info](https://www.va.gov/careers-employment/education-and-career-counseling/)

## Tasks
- [x] Obtain the blank PDF and sample payload from the FE
- [x] Insert the sample payload into the the PDF
- [x] Update PDF test specs to include CH36

## Acceptance Criteria
- [x] A CH36 PDF has been created from form data
