### ISSUE TITLE
Revise Chapter 36 (28-8832) prototype workflows to account for signed-in dependent

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#12913]
## Background
The Chapter 36 prototype was built with the assumption that only Veterans would access the form signed-in. In fact, other types of users--dependents and active-duty service members--can access the form signed-in.

The UXPin prototype needs to accommodate the signed-in non-Veteran accessing the form.

## Tasks
- [ ] Adjust mockup to include the status selection screen in authenticated workflows
- [ ] Create static step-by-step screens to outline the the four workflows (military-authenticated, dependent-authenticated, military-unauthenticated, dependent-unauthenticated)

## Acceptance criteria
- [x] Prototype updated
- [x] Diagram created
- [x] Files shared with team

**Comment by sporeboy** [comment]
Revised prototype here: https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088566

**Comment by sporeboy** [comment]
Simplified user flow here: https://xd.adobe.com/view/0bfd10fc-c184-4d65-bee2-26498f854cfc-5eae/
