### ISSUE TITLE
[Bug] 526: File Upload Corrupted on the Way to VBMS

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12915]
## Issue Description
EVSS had an issue with their file uploads being corrupted.

1. Is it possible to do something with the files from S3?
2. Can we use their auth headers and retry the failed jobs?
---
## Tasks
- [x] Get list of errored out submissions from VBMS
- [x] Discover whether we can do something with the files in S3

## Acceptance Criteria
- [ ] Understand whether there is anything we can do
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Did some research on this. We can just re-run the EVSS upload job, once EVSS tells us what files were corrupted.

**Comment by annaswims** [comment]
Also, spent some time with @johnpaulashenfelter on Friday and learned how to use Sidekiq admin in prod.  I recorded the session in Zoom.

**Comment by luke-gcio** [comment]
Question: Did the corrupted files make it to VBMS and will there now be "duplicates" of which one is totally busted?

**Comment by annaswims** [comment]
Slack discussion: https://dsva.slack.com/archives/C8R3JS8BU/p1598892487029300?thread_ts=1598480686.020600&cid=C8R3JS8BU

**Comment by annaswims** [comment]
I have the list of saved_claim_id's that we need to resubmit file upload for and I'll run the rake task after it's reviewed and in prod.

**Comment by luke-gcio** [comment]
What is required to review the claim ids?

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4862 was merged.  I've re-submitted all files associated with 526 forms that had claim id's on the list.  It's looking like that isn't all the files though, so I'm looking to see if some of them may have come from the Claim Status tool.

**Comment by annaswims** [comment]
conclusion: about half of the files could be re-uploaded but the others came from lighthouse/CST where we don't persist in a usable format which files were uploaded and associated with a claim.

**Comment by annaswims** [comment]
no additional comment from EVSS after a week.  Closing. https://dsva.slack.com/archives/C8R3JS8BU/p1600281994046500
