### ISSUE TITLE
[Design] Incorporate Debt Letters usability study recommendations

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#12927]
## Issue Description
_The team needs to review the recommendations that came out of the Debt Letters usability study and incorporate the approved short-term recommendations._

---
## Tasks
- [x] _Present the usability test findings to the team_
- [x] _Discuss and decide which short-term recommendations will be included_
- [x] _Incorporate the approved short-term recommendations into the UXPin prototype_
- [x] _Create followup tickets for recommendations that can't be immediately incorporated_

## Acceptance Criteria
- [x] _A list of recommendations to incorporate is finalized_
- [ ] _Short-term design recommendations are incorporated in the prototype_

**Comment by rebeccawalsh** [comment]
Our feedback from usability included many short and long-term recommendations:

*Short term*
- Ensure that phone recommendations are clear to support what kind of debt a Veteran has as well as the kind of help they need.
- Explore confirmations when a debt is repaid with the option to save and print for their records.
- Place VA debts under the future Profile or Logged in Homepage, but also supply links underneath each of the hubs.
- Include more directly-worded buttons into the tool from the unauthenticated content page.
- Be as specific as possible with ‘Next steps’ and statuses, provide dates or timelines where possible.
- Adjust the debt cards to more closely pair status and date updated.
- Provide a clearer navigation back to the debt list from the letter download page.

*Long term*
- Provide as much self-service as possible, including online FSR.
- Allow access to historical/past debts.
- Consolidate all debt types into this tool, especially Medical Copay debts.
- Incorporate debt letters into the debt detail pages.
- Implement email or text notifications regarding debt updates.
- Incorporate payment history into debt details.

*Delivering feedback*
- [IA feedback delivered here](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9686)
- Content feedback delivered to Danielle Thierry
