### ISSUE TITLE
Add Eric Oliver to Pager Duty

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#12932]
## Description
Add Eric Oliver to Pager Duty. I will put him on the right schedule etc. Just need him added. 

eric.oliver@agile6.com

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

https://dsva.slack.com/archives/CBU0KDSB1/p1598478099373900 (internal)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _What things need to happen?_
Add Eric Oliver to Pager Duty. 

## Definition of Done
- [ ] _What is the expected outcome of this issue?_
Eric Oliver is added to Pager Duty. 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic - N/A

**Comment by dginther** [comment]
Invited.
