### ISSUE TITLE
[DESIGN] Low-fi prototype for Vet Center

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12952]
## Issue Description
Based on existing Vet Center research and interviews with outreach specialists, we believe the services taxonomy will best be fine-tuned in the context of a webpage prototype.

---
## Tasks
- [x] Create a low-fi design informed by research findings, the existing detail page and new VAMC pages which can be used in discussions with the Vet Center stakeholders and in Veteran research. 

## Acceptance Criteria
- [x] Available prototype including the minimum components:
       - Intro (What is a Vet Center?)
       - Location information
       - Hours of operation
       - Service list
       - More - TBD
- [x] Seek feedback during Design intent collab meeting

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
![VetCenter-Wireframe-Draft-V1.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/c0c36035-0ef7-4c60-9508-54a64df8f7eb)

**Comment by lildziner** [comment]
[Mural board with latest wireframe iteration](https://app.mural.co/t/vsa8243/m/vsa8243/1599673587082/4caed61844c4e3665e9592e2b9467d0eaec8dc6d?wid=0-1600125104061&outline=open)
