### ISSUE TITLE
Iteration on Location/Facility Selection experience

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12951]
## User need/problem
When a Veteran is going through VAOS scheduling flow for VA requests/self schedule and they reach "Select a location" page they do not immediately recognize the options we are presenting them. These options at are the parent site level and do not include city/state.

From user testing, Veterans did not immediately know what to do or what to select if they didn't recognize the names.

Every Veteran participant that interacted with VAOSR (12; 80%) had more than one VAMC affiliated with their account and 100% of these Veterans struggled to find the location where they wanted to schedule an appointment.

## Outcome/goals
- Improve user understanding of facilities they are seeing (and why)
- Decrease user dropoff in scheduling flow on facilities page

## Hypothesis
We believe that by flattening the selection list to just the child facilities and display that list sorted based on location, we will improve usability/findability of a Veteran's preferred facility and decrease dropoff. 

## Strategy for release/testing hypothesis:
- We have some key unknowns relating to this work - namely how many facilities will (on avg) get displayed to Veterans using this new design
- With that in mind, we'll set this iteration behind a feature toggle
- Once we have this iteration released, we are going to release feature to sub-set of users using the 'percent' feature toggle mechanism
- based on that we'll observe whether or not we see dropoff improvements on this page
- we'll also setup some quick veteran testing rounds

## Options
- Sort facility list based on Veteran location
- When location not possible, sort list alphabetically

## Definition of Done
- [ ] Veteran can use their home address to sort their facility list
- [ ] Veteran can use their current address to sort their facility list
- [ ] Facilities being shown: are only for the care type selected (don't show facilities that don't support type of care)
- [ ] Provide way for Veteran to reach out to facility if they don't see the one they are looking for

### Current iteration of mockups:
![Screen Shot 2020-08-31 at 4.38.37 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/4e2faa85-25c8-4359-8344-6cc3eb86fc76)

**Comment by lenaecb** [comment]
Release to 50% on 10/23 for v2. Holding at 50% until 10/27.

If we are seeing positive results, move to 100% EOD 10/27.
