### ISSUE TITLE
Dynamic query to build left nav (VAMC)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12970]
## Issue Description
The VAMC upgrade team discovered a bug in the DevShop build process in which new facility instances were built without the left nav. Root cause was determined to be the hardcoding of `FACILITY_MENU_NAMES` in src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

Given the intent to dramatically speed up the volume of new VISNs which are onboarding, we need a long term sustainable process to build left nav, such as a dynamic query. 

**This issue will become a blocker for the VAMC-upgrade team in future roll-outs.** 

May need discovery to determine where else the string is used

---
## Tasks
- [x] Create endpoint to add `FACILITY_MENU_NAMES` array during build (Ethan)
- [x] Take Ethan's logic to grab system menu names from graphql endpoint across the finish line (Michael) - this work is initiated in [PR for VACMS-12970](https://github.com/department-of-veterans-affairs/vets-website/pull/14488)

## Testing
- [x] automated tests pass (we have a [cypress test](https://github.com/department-of-veterans-affairs/vets-website/blob/0e37736407289a7a0d41afffc9770decf912f604/src/platform/site-wide/side-nav/tests/e2e/sideNav.cypress.spec.js) for the presence of side nav on `/pittsburgh-health-care` specifically. We could add more.
- [ ] Confirm side navs appear correctly on static pages after building locally, and in the review environment (DevShop)

## Acceptance Criteria (post merge)
- [x] All facilities will be returned, regardless of published state
- [x] Side nav will be available in Dev shop environments

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
I have no idea how to get this data dynamically from Drupal. I'll need help from @ethanteague to assess level of effort.

**Comment by mpelzsherman** [comment]
Need to determine what criteria would be for populating FACILITY_MENU_NAMES. 

e.g. "all _published_ facilities"?

**Comment by ethanteague** [comment]
@mpelzsherman @brangi @mmiddaugh I have two prs in place. The first is in the drupal repo, and it creates the menus list endpoint: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3110 - this one needs to make it to prod before we merge in the frontend pr that switches from the hardcode method to the new endpoint consumption method: https://github.com/department-of-veterans-affairs/vets-website/pull/14488 - I set it to draft status to prevent accidental merge prior to new cms endpoint task being complete.

**Comment by mmiddaugh** [comment]
@mpelzsherman please see the [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1602274930354300)

**Comment by mpelzsherman** [comment]
We had to roll back the PR for this ticket because of a deploy error:

```
15:11:09  + node script/drupal-aws-cache.js --buildtype=vagovprod
15:11:10  (node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
15:11:10      at Object.<anonymous> (/application/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js:67:21)
```

See [Slack Thread](https://dsva.slack.com/archives/C01512KN35G/p1603741114018400) for more info.

**Comment by mpelzsherman** [comment]
This issue is blocked due to issues with deploying the review environments. See [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1604350562389600) for details.

**Comment by mpelzsherman** [comment]
@ElijahLynn [confirmed](https://dsva.slack.com/archives/CT4GZBM8F/p1605039035457200?thread_ts=1605032055.433600&cid=CT4GZBM8F) that the side nav is still working in DevShop environments. Closing!

**Comment by mpelzsherman** [comment]
Re-opening because the PR had to be rolled back due ongoing issues with the review environments.

The RI’s do not have network access to the Drupal API, so this was causing the builds to fail (or was at least one of the causes).

**Comment by mpelzsherman** [comment]
@U-DON - you made a [comment](https://dsva.slack.com/archives/CBU0KDSB1/p1606865186369500?thread_ts=1605557619.162400&cid=CBU0KDSB1) in Slack about needing to refactor the dynamic side-nav code so it could use the CMS cache. Can you elaborate please?

**Comment by U-DON** [comment]
I just mapped out the relationship between the cache and the side nav [in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16401#issuecomment-738214046) in department-of-veterans-affairs/va.gov-team#16401. Hope that clarifies things.

**Comment by U-DON** [comment]
I think that's one way we could do get it to work. The cache key would work as long as it doesn't need to make a request to the CMS.

We've been talking about populating a cache that just uses the latest content, which would supercede the use of a specific hash for the key in most cases. Still figuring that out.

Meanwhile, is there a way to refactor the query to not require two round trips? If not, maybe we can refactor the query so that it can have an "uncompiled" form that can be used as a cache key, and the fully compiled form would be what we issue as the query to the CMS. Don't know if that makes sense.

**Comment by mpelzsherman** [comment]
Thanks. Part of the problem is I don't understand how the cache gets populated. lt also seems like we might have gone a bit overboard in our approach to solving the problem.

The whole point of the dynamic queries is simply populate the hard-coded FACILITY_MENU_NAMES array with a list pulled from drupal via GraphQL.

Is there some way we can just publish that list to an AWS server and pull it from there?

**Comment by mmiddaugh** [comment]
closing this as we've created a [Discovery issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17256) which will inform the new solution/issue
