### ISSUE TITLE
Dedicated Content Editor support from BAM2

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12978]
## Why you're here

- Content support for authenticated application or tools

## Steps to complete intake request
- [ ] Submit this request when VSA Public Website team intervention is required
- [ ] Provide detailed information of your request to help us understand our role in completing your request 
- [ ] Link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

## Background
*Provide a background of your tool/functionality.*
Debt Letters Iteration 2- Building on MVP this iteration will provide the veteran debt details and summarize  about 250 debt codes into easier to understand categories which will have content about what the status of the debt is

* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Design ](https://preview.uxpin.com/305eb36ed6ec2e5f2bc1dd91659b70ef961ab269#/pages/130719464/simulate/sitemap?mode=i)
   * [Usability ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/usability-readout.md)
---

## Request Type
*Select all applicable and provide details behind your request* 

### Content
- [ X] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * **Word document with draft if available, or link to the URL where the draft content appears:** 
     - < link > 
   * **Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?):** 
     - < design context >
   * **Scope: How many screens? (Or messages, etc.):** 
     - < scope > 
      
      
- [ ] **Content support for a static public website page**
   * **Is this to update existing static content?** 
     - < y/n >
   * **Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.):**  
     - < y/n >
   * **Provide a list of URL/s that need to be reviewed or updated.** 
      * < URL list >
   * **If it's a small copy section, list what the new info should be and what it is replacing.**
      * < list of new info >

### Frontend  
- [ ] **New URL or Redirect Requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA Redirect Request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*

* <Desired/target implementation date>

---

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: BAM2
- DEPO product owner: @mattpointzxer0 Matt S. 
- Product manager: @leahkeeler Leah K. 
- Designer: @rebeccawalsh @rileyorr Becca W. Riley O. 
- FE engineer: @bradl3yC Brad C. 
- Product/team Slack channel: #vsa-bam-2

--- 
#### Acceptance Criteria
- [x] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. I'd like to schedule a call to go over the details of this work. @peggygannon should be included in that call as well, as we'll be working together on this. Also, do you have a target timeline yet? An estimate will help us prioritize the work. Thanks!

**Comment by leahkeeler** [comment]
Hi Danielle - Thanks!!!! I will schedule for later this week, I do have a high level timeline to share

**Comment by FranECross** [comment]
Closing old/obsolete ticket.
