### ISSUE TITLE
Create "Contact us" page to replace the soon-to-be-retired IRIS page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#12986]
## Issue Description
Help users find contact information that currently lives on the IRIS main page: https://iris.custhelp.va.gov/

Consider this information:
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1597851188988/2ee72198710ac9e2ef6cae04d97fecb20fcdae08

---
## Tasks
- [x] Create page in drupal.
- [x] IA sync.
- [x] Copyedit page. 
- [x] Check phone numbers in chart against right rail on hub pages (Randi)
- [x] Verify hours of operation in chart (Randi)

## Acceptance Criteria
- [x] Page is ready to go live before IRIS retires at the end of the year.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Adding notes from our working session on this:

- Preview - http://preview-prod.vfs.va.gov/preview?nodeId=7809
- Goal for first iteration is to keep it simple with a featured content component for ask a question (encouraging use of resources and support first), helpful phone numbers, and helpful online tools

**Comment by DanielleThierryUSDSVA** [comment]
Preview of 2nd iteration discussed at content/IA 10.28.20 sync: http://preview-prod.vfs.va.gov/preview?nodeId=8472

Notes:
- Discussed whether or not to keep blue box. Decided to keep as a way to keep R&S visually distinct from ways to actually contact us.
- Beth and Danielle will do another sweep of phone numbers to make sure these are the #s we want to surface here, and will add a link to the phone number directory article in R&S for more numbers.
- Will direct the ask a question online link to IRIS for now, until we have new form.
- Per Mikki and Meg, URL will be va.gov/contact-us.

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO Could you give this a look on Monday morning so we can publish? General look + double check phone numbers, hours, links. Thanks! http://preview-prod.vfs.va.gov/preview?nodeId=8472

**Comment by bethpottsVADEPO** [comment]
@RLHecht Added two tasks for you in tasks list above.

@DanielleThierryUSDSVA I reworked some of the language and H2s, and added a chart for the phone numbers. Take a look when you have a chance.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I confirmed all these phone numbers as well as their hours of operation. No changes needed.

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO @RLHecht This is launched, so I'm closing ticket.
