### ISSUE TITLE
Public Release Checklist for 10-10cg

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#12984]
**Pre-Release (t - 4 days)**
- [x] [Flipper] Disable `:allow_online_10_10cg_submissions` flipper for all in prod (this will end beta testing)
- [x] [DevOps] Remove password protection on `/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg` for all environments
  - [x] [DevOps] Delete the login credentials from credstash
  - relates to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12609

**Pre-Release (t - 3 days)**
- [x] [Front-end] Connect the "Apply Now" button (widget) to `:allow_online_10_10cg_submissions`
  - more details here: https://dsva.slack.com/archives/C52CL1PKQ/p1598636900216800?thread_ts=1598635019.204000&cid=C52CL1PKQ
  - revert this code: https://github.com/department-of-veterans-affairs/vets-website/pull/14051
- [x] [Flipper] Ensure `:allow_online_10_10cg_submissions` is cookie based
- [x] [Front-end] Deploy the front-end changes

**Pre-Requisite (t - 1 days)**
- [x] [Flipper] Make sure `:stub_carma_requests` flipper is disabled for all!
- [x] [Flipper] Allow `:allow_online_10_10cg_submissions` for all in staging
- [x] [Test] Check that the website show the "Apply" button
- [x] [Test] Ensure you can reach the form
- [x] [Test] Complete a submission

**Release Day (t - 0 days)**
- [x] [Flipper] Change `:allow_online_10_10cg_submissions` high percentage.
- [x] [Test] Check that the website show the "Apply" button
- [x] [Test] Ensure you can reach the form
- [x] [Flipper] Lower `:allow_online_10_10cg_submissions` to desired public access percentage

**Comment by kevinmirc** [comment]
We launched!
