### ISSUE TITLE
Content Request for How to Apply Wizards from Public Websites Team

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#13028]
## Why you're here
- [X] Content support for static public website pages

## Steps to complete intake request
- [X] Submit this request when VSA Public Website team intervention is required
- [X] Provide detailed information of your request to help us understand our role in completing your request 
- [ ] Link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Selina Cooper 

---

## Background

We want to [move/consolidate these pre-requisite Wizard steps](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9665) with the application tool landing page in order to:

1/ Make the Veteran experience of starting their online application more seamless. (Today, they have to find the Wizard on a content page, and from there, fill out the wizard and then are sent to the tool landing page.)

2/ Make apply online CTAs from tier 2 content and other content outside of the benefit hubs more clear and direct. Example: from our mvp form detail landing pages or from the modernized mvp form search results.

The three benefits pages impacted by this change:

Disability
https://va.gov/disability/eligibility
https://va.gov/disability/how-to-file-claim
--> Moving to: https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction

Higher Level Review
Invision mockup of new Wizard in development
https://www.va.gov/decision-reviews/higher-level-review/
--> Moving to: URL TBD

Education
https://va.gov/education/eligibility
https://va.gov/education/how-to-apply
--> Moving to: https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction

Personalized Care & Planning Guidance (Form 28-8832)
Of note, a new "gating wizard" is also being introduced on the new PCPG page. Here is a [flow diagram](https://xd.adobe.com/view/879cf230-f3ce-4204-79ba-c3453b0bcc09-f1ad/screen/28f5d3f7-c2c1-49c0-bfa1-3791dba4dd7e/).

### Content Focus 

The Education Wizard change [is now on staging](https://staging.va.gov/education/apply-for-education-benefits/application/1990/introduction) as is the Disability Wizard [change ](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction).

- Collab Cycle/Platform review has been completed for the Education Wizard with feedback outlined here:
   - [IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12244) 
   - [Content](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12243)

---

## Request Type
*Select all applicable and provide details behind your request* 

### Content

      
- [X] **Content support for a static public website page**
   * **Is this to update existing static content?** 
     - Yes
   * **Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.):**  
     - No
   * **Provide a list of URL/s that need to be reviewed or updated.** 
      * Above
   * **If it's a small copy section, list what the new info should be and what it is replacing.**
      * Content that navigates users to and through the Wizard(s)

### Frontend  
- [ ] **New URL or Redirect Requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA Redirect Request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
* Education and Disability Wizards: Late September
* HLR: October

---

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: Public Websites
- DEPO product owner: John Hashimoto
- Product manager: Leah Keeler and Luke Wajewski
- Designer: Liz Lantz
- FE engineer: Craig Wheeler and Robin Garrison
- Product/team Slack channel: #va-how-to-apply-wizards

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by mnorthuis** [comment]
Closing this old issue - this work is being handled by each team as they deprecate the wizard and move to a sub-task pattern.
