### ISSUE TITLE
Update VBA Facility Naming Conventions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13026]
## Issue Description
Naming convention is established to standardize all 600 facilities. 
We need to help VBA update facility names 

- All facilities in single table (VBA_facilities) in single database
- No dependencies between facilities
- Sandy informs CDW when he makes changes. 
- Update pushed every 24 hours
- Reference ID -> update name

Cloud recording of demo: https://zoom.us/rec/share/FCqx4ATFULtXTutn_gC4yZrNG0abkOTSVqH74sEu94JLWww2r4B4xMUkprHu6Uvc.tvhWdJqjSwm3gTAx Passcode: n=2L3^u5

If there's time Meg will look at the non-VA facility and supply that, but not critical path.

Assuming A -> B replacement with no duplicate names

## Prereqs

- [x] Need confirmation of naming convention
- [x] Get list from Meg for naming based on new rubric
- [ ] ~Gain access to Systems (from Sandy)~
- [x] Demo from Sandy on process
- [x] Identify testing process and/or get [copy of table from Sandy](https://github.com/department-of-veterans-affairs/va.gov-team/files/5318351/vba_facilities-10012020.xlsx)

## Tasks

- [x] Meg to review the VA facility naming conventions and follow up with Dave on any questions 
- [ ] Create script to update facility names in CDW (Central Data Warehouse) with brief instructions 
       VBA_Facility_Names in Column A need to be replaced with Proposed Names in Column D.

**Comment by mmiddaugh** [comment]
Michelle will record demo from Sandy on the process before we groom

**Comment by mmiddaugh** [comment]
Meg will be DEPO POC during Dave's vacation, if needed.

**Comment by mpelzsherman** [comment]
I don't think this should be assigned to the facilities team. Updating the CDW isn't something we can do, is it?

**Comment by mpelzsherman** [comment]
We need a sandbox environment to test the SQL statement before we do it live.

**Comment by mmiddaugh** [comment]
Data file: 
[vba_facilities-10012020.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5318351/vba_facilities-10012020.xlsx)

**Comment by mmiddaugh** [comment]
@darkbushido here is the first set of names which need to be changed (VBA_Facility_Names in Column A need to be replaced with Proposed Names in Column D). A smaller set of locations have pending questions and will need to be added to this process once the names are finalized. They will still have the same pattern (replacing VBA_Facility_Names be replaced with Proposed Names). 
[VBA Facility Names_no_questions.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5425219/VBA.Facility.Names_no_questions.xlsx)

**Comment by davidconlon** [comment]
@darkbushido Simplified and cleaned this up a bit.
There are now two columns: Primary Key (Facility ID--that's the unique identifier) and the New Name.

Let me know if you have any questions.


[Benefits Facility Names - Simplified.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5430589/Benefits.Facility.Names.-.Simplified.xlsx)

**Comment by darkbushido** [comment]
https://gist.github.com/darkbushido/0dbd748fffcc3f61046a56ec20091628

**Comment by darkbushido** [comment]
we should run
```
select Facility_Name, Facility_Number, count(*) from vba_facilities group by Facility_Number having count(*) > 1;
```
And
```
select *
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='vba_facilities'
```
Or
```
sp_help vba_facilities
```

**Comment by darkbushido** [comment]
```
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'awesome_print'
  gem 'csv'
  gem 'pry'
  gem 'tty-command'
  gem 'tty-exit'
  gem 'tty-option'
end

class Command
  include TTY::Exit
  include TTY::Option

  option :input,
    arity: 1,
    long: '--input FILENAME',
    default: 'vba_facilities.csv',
    desc: 'The name of the input file',
    convert: :pathname,
    validate: ->(file) { file.exist? }

  option :output,
    arity: 1,
    long: '--output FILENAME',
    default: 'transform.sql',
    desc: 'The name of the output file',
    convert: :pathname

  option :group,
    arity: 1,
    long: '--group SIZE',
    default: 5,
    desc: 'How many UPDATE statements will be inside QUOTED_IDENTIFIER',
    convert: :int

  flag :help,
    short: '-h',
    long: '--help',
    desc: 'Print usage'

  def run
    binding.pry
    exit_with(:usage_error, params.errors.summary) unless params.valid?
    if params[:help]
      print help
    else
      generate
    end
    exit
  end

  private

  def generate
    csv_rename_data = CSV.foreach(
      params[:input],
      headers: true,
      header_converters: :symbol
    )

    group_size = params[:group]

    File.open(params[:output], 'w+') do |file|
      csv_rename_data.each_slice(group_size) do |rows|
        update_statements = []
        update_statements << "SET QUOTED_IDENTIFIER OFF;"
        rows.each do |row|
          key = row[:facility_number]
          name = row[:facility_name].gsub('"', '\'')
          update_statements << "UPDATE [VBA_facilities].[vba].[Facility]"
          update_statements << "  SET [VBA_facilities].[vba].[Facility].[Facility_Name] = \"#{name}\""
          update_statements << "  WHERE [VBA_facilities].[vba].[Facility].[Facility_Number] = '#{key}'"
        end
        update_statements << "SET QUOTED_IDENTIFIER ON;"
        file << update_statements.join("\n") << "\n\n"
      end
    end
  end
end

cmd = Command.new
cmd.parse
cmd.run
```
