### ISSUE TITLE
Adjust chapter 36 form based on prototype updates

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#13047]
# Background
After discussions in our grooming meeting, we decided that some changes needed to be made to the workflows within the chapter 36 form. The prototype has now been updated to reflect these changes and we need to update the front end code to match the prototype.

## User Story
As a Veteran I want the most up to date and streamlined workflow when filling out the Chapter 36 form so that I can get the VRE benefits I need as quickly and as easily as possible.

## Tasks
- [x] rename files and properties with `claimant` where needed
- [x] Move pages in workflows to match prototype
- [x] Submit a PR to `vets-website` for review

## Acceptance criteria
- [x] the front end of the chapter 36 form has been updated to match the prototype
- [x] A PR has been submitted for review
