### ISSUE TITLE
Request to set up Google Cloud Domain Organization

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13064]
## Issue Description
We will need to set up a domain organization so that we can tie projects together and create more consistency in our Google products. This will affect SEO and others using Google products. How might we claim a domain via DNS and add an organization to GCP?

---
## Tasks
- [ ] Jon/Brian to write up the tasks, effort levels, or other VA groups this may affect
- [ ] Joanne to send to Nancy or DEPO

## Acceptance Criteria
- [ ] VSP understands what it might take to set up a domain organization

**Comment by bsmartin-ep** [comment]
As noted in another ticket @michelle-dooley, it doesn't look like this is a possibility for the VA:

https://cloud.google.com/resource-manager/docs/creating-managing-organization#:~:text=An%20Organization%20resource%20is%20available%20for%20Google%20Workspace%20and%20Cloud%20Identity%20customers%3A
