### ISSUE TITLE
Military information

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13067]
# User Story
As a user, I can view the following information from my VA.gov profile:
- Branch of service
- Periods of service
# Tasks
- [ ] Any necessary optimizations to endpoints are determined and discussed with team
- [ ] Any necessary optimizations are made in vets-api 
- [ ] Endpoints are tested
- [ ] Endpoints are documented 
- [ ] Hand off to frontend
# Prototype
https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427924942
