### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13071]
# User Story
As a user, I can log in to the app using my ID.me, MHV, or DS Logon credentials.

# Tasks
- [x] Convo with engineering about user flow for LOA 1 vs LOA 3 users 
- [x] ID potential solves for restricting LOA 1 users
- [x] Convo to understand the possibilities for alert types (Jonathan talking to IAM team about this today)
- [x] UX/UI flow for needing to up level a LOA 1 user to LOA 3
- [x] Determine empty state or what the LOA 1 users will see if they don't up level

**Comment by srmyers17** [comment]
Set up diagram of auth + team discussing today

**Comment by bridgethapner** [comment]
# Proposed approach for LOA1 UX: 

- LOA1 users can't manage claims or appointments, and it looks like they can't view/edit their profile either. So we want to throw up a gate once LOA1 users login to the app that prevents them from actually accessing the app features.
- We also want to throw up a modal that users must interact with _before_ sign in (step 2 below) to give LOA1 users a chance to not have to go through auth if they can't use the app anyway. Knowing that sign in can be a big pain point, we want to let users know as early as possible, before sign in, if they won't be able to access the app.

# Sign in steps
1. User clicks ‘Sign In’ on the unauth app home screen. 
2. _[Users who are signing in for the first time only]_ In-app modal displays to explain to users that identity verification is required to use this app. Users must dismiss or acknowledge this modal to continue forward in sign in. 
3. User briefly sees sqa.auth & api.idme redirects that are part of the SSOe UX.
4. User hits MHV, ID.me or DS Logon and signs in there; completes 2FA if necessary.
5. User briefly sees SAML round trip redirects that are part of the SSOe UX. 
6. LOA3 and LOA1 users UX branch here: 
    - _[LOA1 users only]_: User lands on gate screen that explains they need to identity proof to use the app. Screen provides CTA to launch ID proofing flow. 
    - _[LOA 3 users only_]: User lands on regular app home screen, can use the app as normal.

# UX next steps
1.  Research what language around ID proofing is helpful to users to reflect in intercept modal (step 2). 
2. Create wireframes for steps2 and 6a. 
3. Being part of ongoing conversations 

# Tech next steps
1.  Discovery around if launching the ID proofing flow in a web view would allow the user to remain signed in (step 6a).
2. Ongoing conversations with Patrick to investigate other use cases we may need to consider

**Comment by srmyers17** [comment]
Link to login takeaways and next steps: https://app.mural.co/t/adhocvasu2804/m/adhocvasu2804/1599682646895/7cf34f5861dceab7b068c93f125179fc51d89e86

**Comment by bridgethapner** [comment]
Uploading screenshots of the alerts a LOA1 user sees. 

# Profile: 
![Screen Shot 2020-09-10 at 1.02.06 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/f44357b4-72c2-4aba-be0c-f51585e417bc)
![Screen Shot 2020-09-10 at 1.02.13 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/f105fc62-e71f-496d-902a-ca47bba0454f)

# Claims:
![Screen Shot 2020-09-10 at 1.03.54 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/8789e9e5-c612-4044-b456-679cdfbccb67)

# Appointments:
![Screen Shot 2020-09-10 at 1.02.44 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/1bd13763-87e0-4321-976d-feabb3ad5342)

**Comment by bridgethapner** [comment]
@smyers17 Circling back on this one. Do we know who is making the final decision on if the gate off LOA1 users vs handle gating on a case by case basis?

**Comment by bridgethapner** [comment]
The decision on Auth -- [LOA 3 required to enter app; show a simple single-screen CTA to send LOA 1 users to VA.gov for up-proofing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/tech-research/Authentication%20decisions.md#decision-3).

## UX Work 
- Create 1 screen that users will land on after they authenticate to be redirected to VA.gov if they are LOA 1. 

## Assumptions
- Only LOA1 users will see this screen. 
- They will not be able to get past this screen into the app.

**Comment by srmyers17** [comment]
@lexicalninja Let's sync next week to clarify what screens we need to design from a UX perspective.

**Comment by lexicalninja** [comment]
@srmyers17 Sounds good. I am still working with the IAM team on an issue with what happens immediately after upping level in id.me to see if we need a fallback for that process. 

Once we have a chance to run through the paces on MHV we can see if there are any issues there. Hopefully both of these are much more clear by next week

**Comment by bridgethapner** [comment]
Per [Significant Decision 8](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/significant%20decisions.md#decision-8-only-users-with-logon-credentials-at-level-of-assurace-loa-3-will-be-allowed-to-use-the-app): 
- Users who are LOA1 won't get back to the app, they'll get handed off to Verify Identity flow in ID.me. We don't need a home screen gate design for LOA1 users. 

**MVP solve** (cc @lexicalninja @jjulian) 
- Create an interstitial screen after a user hits Sign In on the unauth home screen that explains they'll need to verify to use the app if they're not yet verified. Use some language from the VA.gov sign in modal for this.
- From this screen, users can continue on to sign in which they'll do first before verification. 
- **Pros of this:** Telling users rules around app access
- **Cons of this:** Users may be confused about verification and if they need to do it
- Our UX approach is to include this screen for MVP & do further usability testing pre-app store launch

**Qs we're still figuring out:** 
- Can MHV basic/advanced users verify via ID.me? If not, we'll revisit this approach.

**Comment by bridgethapner** [comment]
Took the first pass at what a screen could look like. Users would hit this screen after selecting "Sign In" and would need to select one of the 2 CTAs on this page to continue. This language is pulled from VA.gov sign in FAQs. The one thing I don't understand is why these FAQs don't say anything about ID.me.

![LOA1-gate.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/a47948c0-0a43-4378-9cc2-4d00e6b68066)

**Comment by srmyers17** [comment]
@lexicalninja  to review with @bridgethapner

**Comment by bridgethapner** [comment]
Here's [the screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433563910) to flag the need to identity verify in the prototype flow. I edited it a bit to cut down on text as much as possible. 

I'm moving this ticket to **Design Review** b/c I want to review this with @artsymartha68 tomorrow in our UX check-in so she's aware of the auth gating UX. We can open new smaller tickets for any follow-up UX work.

**Next steps:**
- I scheduled a follow-up w/ @lexicalninja tomorrow to revisit auth/see where else UX help might be needed. 
- Document auth UX (created #14540 for this)
- We've noted this is a place we need content help in the content help ticket - hopefully we can get some guidance here!

**Comment by bridgethapner** [comment]
- Work with the content on language (shorten if we can...)
- Welcome message?
- Simplify messaging around LOA1/LOA3 to the minimum we need to say to help folks make a decision

**Comment by bridgethapner** [comment]
**Process:** 
- Tuesday touch bases between Patrick & Bridget re auth to discuss what we've learned in that week / what we want to take to IAM
- Once app is released on Test Flight, I can test the auth flow in different creds to understand the UX flow and give feedback on
- Patrick will record sign-in in the emulator and send a GIF for Bridget to review


**Re the LOA1 gate:** 
- Decision made re LOA1 gate: we'll only show once

**Comment by bridgethapner** [comment]
I have reworked the LOA1 gating UX. It can be triggered by clicking "Sign In" here: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432863239

I am moving this to Design Review to get design review (and hopefully content help) moving on the LOA1 gating. We can open new, discrete tickets for auth related UX work down the line.

**Comment by bridgethapner** [comment]
Notes 
- Change the language of CTAs to be more general on both screens

**Comment by bridgethapner** [comment]
- Can we use a version of va.gov/sign-in and have a valid SAML request for MVP?

**Comment by bridgethapner** [comment]
@bessgreen In case it's helpful to reference, I captured the UX decisions for MVP auth here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/ux-design/mvp-auth-pov.md

**Comment by bridgethapner** [comment]
**MVP:** 
- Link to call center with context from LOA gating screens?
- Consider adding value prop of app features?

**Post-MVP**
- Look at including LOA users - letting them sign in, and "locking" features they can't access

**Comment by bridgethapner** [comment]
**Per 11/12 UX check-in:** 

- The LOA gating screen is moving ahead to VSP content review
- MVP integration has been reviewed by team and we've identified a few more opportunities to improve the UX that we'll communicate to the IAM team (#16171 and #16172). 

Closing this ticket.
