### ISSUE TITLE
Bottom navigation toolbar 

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13074]
# User Story
As a user, I can access the following screens using the bottom toolbar navigation:
- Home
- Claims
- Appointments
- Profile

# Tasks
- [x] High fidelity prototype of navigation in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

# Prototype
[The navigation is in the prototype](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636866). 

# Other documentation
- We'll need to include attribution to these icons in the app somewhere. This is captured in #13961.

**Comment by srmyers17** [comment]
Incorporating feedback from Martha + Ryan. Fine tunning discussion guide

**Comment by srmyers17** [comment]
Remove facility locator from bottom nav.

**Comment by bridgethapner** [comment]
We are using Font Awesome icons for the bottom navigation. I've downloaded svg files for the icons, but we need a standard license to complete the navigation design so we can download outlined + solid styles for each icon to correspond with active and inactive states. 

I asked in the DSVA #design channel is there's a pro Font Awesome license that we have, and wasn't able to get an answer.

**Comment by rtwell** [comment]
fysa, I reached out to Kevin H about this, and he's digging into it.

**Comment by bridgethapner** [comment]
Thank you @rtwell! For now, I have switched to a combination of Icons8 and Font Awesome because it's been hard to find solid + outlined SVGs for the 4 items we need in one icon set. Looking forward to hearing Kevin's perspective.
