### ISSUE TITLE
Direct deposit

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13073]
# User Story

- [ ] As a user, I can view and edit the following information direct deposit information for Disability Benefits
- [ ] As a user, if I have problems locating my banking numbers, I can view a help image explaining where to find my banking information

# Tasks
- [x] High fidelity prototype of screens in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing, as needed) UI for a range of devices we are supporting, Android-specific designs

# Security 
- When a user taps direct deposit information to edit it, they should not see direct deposit information for security reasons. Each time a user taps into edit, they will see a blank screen and need to edit new information.

# Character Limits and Requirements
- All 3 fields are required.
- The Routing number can be no more than 9 digits.
- The Account number can be no more than 17 digits. 

# Keyboard and Pickers
- Both the Routing and Account number fields should bring up the numerical keyboard when a user taps into them.
- Account Type should open a picker with the following options:
     - Savings
     - Checking

# Saving
- The 'Save' CTA in the upper right shouldn't activate until a user has entered all 3 fields and has no error messages. 

# Prototype
- [Wireframe, empty state](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432050367)
- [Wireframe, edit state - empty](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636876)
- [Wireframe, edit state - completed](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432050369)
- [Wireframe, full direct deposit](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432050367)

# Click to Call
- On the Direct Deposit screen, there will be a click to call phone number at the bottom.

**Comment by srmyers17** [comment]
Usability feedback
- Explanatory text about where updates will go (va.gov)

**Comment by bridgethapner** [comment]
# Relevant wireframes

[- Direct deposit screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636875)
[- Edit state](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636876)
[- Open accordion for help finding account and routing number](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636877) (we will need to get this image from the VSA team, it's a screenshot for now)

# Notes
- We will need to add a confirmation screen to meet WCAG standards, ticket #13649 is for this work. When that is designed there may be small changes to this screen.
- VA.gov's privacy policy doesn't allow users to fully view their information once they enter and save it. If a user already has direct deposit info saved in the app, once they open it to edit it, they will see blank fields.

**Comment by artsymartha68** [comment]
Looks great. A couple things:

1. Maybe: "when you make updates in this app"? I assume eventually we'll have an actual app name instead of "VA mobile app". 
2. Does BANK NAME get automatically pulled from the data once they enter the routing number?

**Comment by bridgethapner** [comment]
1. I captured this text as a place we'd like Content help from VSP on #14031. 

2. Yes - Bank name does get auto-updated once they enter the routing number. I revisited VA.gov this morning and updated our Direct Deposit to match the field labels on VA.gov 1:1 to reflect this.
