### ISSUE TITLE
Unauthenticated homescreen

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13080]
## User Story
As a user, when I download the app, I can sign in, access the VCL or the facility locator.

## Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting, Android-specific design as needed

## Links
- The **Veterans Crisis Line** CTA should go to the VCL screen within the app. From that screen, the back button should return users to the unauthenticated home screen. 
- The **Find a VA Location** CTA should go to the Facility Locator in-app web view. From that screen, the back button should return users to the unauthenticated home screen. 
- The **Sign In** CTA should open the in-app web view of the auth flow. Once users complete sign in, they should be returned to the app's authenticated home screen. If a user cancels out of the sign-in flow, they should land back on the unauthenticated home screen.
