### ISSUE TITLE
Home screen multiple appointment card

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13091]
# User Story
- When I have multiple appointments upcoming within 7 days, I will see a reminder card on my homescreen. 
- I can tap that card to view all my upcoming appointments.
- I can dismiss this card.
# Tasks
- [ ] Talk to VAOS to understand the average number of upcoming appointments and what makes the most sense for this card given the most common scenarios
- [ ] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Anroid
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting
