### ISSUE TITLE
Groom eBenefits KPIs for KPI dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13105]
## Issue Description
Groom team KPIs for technical feasibility. There's currently an [eBenefits KPI dashboard](https://va-gov.domo.com/page/177811372) on Domo that will need to be reconfigured.

---
## Tasks
- [ ] Groom analytics for technical feasibility
- [ ] Document data sources for each metric
- [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

## Acceptance Criteria
- [ ] VSP Analytics & Insights understand which KPIs are feasible, how to retrieve them, and has a documentation of blockers for additional KPIs

---

KPIs in Epic.

**Comment by bmcgrady-ep** [comment]
@jason-gcio - I am grooming the KPIs for the eBenefits KPI dashboard and have a couple of questions. In regards to this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/README.md#okrs--kpis), what does RBPS mean in terms of the metrics? Also, where does this data live?

**Comment by bmcgrady-ep** [comment]
eBenefits KPI | Drilldown | Data Source | Go/No Go
------------ | ------------- | ------------- | -------------
Page views on Manage Dependents unauthenticated content | Page contains `/disability/add-remove-dependent`/ | BigQuery | ✔️ Go (in staging)
Successful application submissions  | event label = `disability-21-686c--submission-successful`  | BigQuery | ✔️ Go (in staging)
Number of auto-approved applications by Rules Based Processing Service (RBPS)  | N/A  | Regular Report or API | ❌ No Go (don't currently have the data from RBPS)
Time to manually process submissions  | N/A  | Offline | ❌ No Go (offline metric)
% of Dependency Claims that go thru RBPS / manual processing  | `Total Dependency Claims / (RBPS claims processed + Offline claims processed)`   | Regular Report or API | ❌ No Go (don't currently have the data from RBPS)
Time to complete Form 686c  | N/A  | BigQuery | ✔️ Go (in staging)
% of submitted vs. draft RBPS submissions  | N/A  | Regular Report or API | ❌ No Go (don't currently have the data from RBPS)
Number of Dependency Claims processed within n days of submission regardless of approval method  | N/A  | Regular Report or API | ❌ No Go (don't currently have the data from RBPS)
% of people who land on wizard and start the application  | Goal Funnel: 1. event label =  `cta-primary-button-click`  on page: `/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction`  2.  event label = `login-successful-start-form` or `no-login-start-form`  on page: `/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction` | BigQuery | Future 🔶 Go (once implemented)
% of people who abandon (Abandonment Rate)  | Goal Funnel for Form 28-8832  | BigQuery | Future 🔶 Go (once implemented)
% of people who complete the form  | Goal Funnel for Form 28-8832  | BigQuery | Future 🔶 Go (once implemented)
Customer Satisfaction (CSAT)  |  N/A  | CSAT data | Future 🔶 Go (once implemented)


Note: Per [slack conversation](https://dsva.slack.com/archives/D015SND5F7G/p1600797454005700) with Jason Wolf, we are waiting on data for the RBPS metrics. Also, the dataLayer for CH36 (Form 28-8832) still needs to be implemented.

**Comment by bmcgrady-ep** [comment]
Hi @jason-gcio! Do you have an update on the RBPS data or is there someone you can put the Analytics & Insights team in contact with that can get us the RBPS data?

**Comment by jason-gcio** [comment]
Hey @bmcgrady-ep - no update as of yet, but I asked again just now.

**Comment by bmcgrady-ep** [comment]
@jason-gcio - Thank you for following up with them. Please let us know when you hear from them. Thanks!

**Comment by bmcgrady-ep** [comment]
Hi @jason-gcio - We currently have the following metrics available (in staging) for a dashboard: `Page views on Manage Dependents unauthenticated content`, `Successful application submissions`, and `Time to complete Form 686c`. Are these metrics alone useful (in decision-making) for a dashboard for your team?

**Comment by jason-gcio** [comment]
Yes, definitely.  I hope to get a hold of actual submission data soon.
Thanks!

**Comment by bmcgrady-ep** [comment]
@jason-gcio Good to know, thanks! 
Also, can you provide an update on when 686c will be live? Thanks!

**Comment by jason-gcio** [comment]
Its in prod now actually while we move through integration testing and UAT.

**Comment by johnny-jesensky-adhoc** [comment]
Dashboard is still listed as WIP in Domo closing this ticket.
