### ISSUE TITLE
Analytics KPI dashboard request for 10203

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13102]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Submit this ticket as an epic
- [ ] Add your team label to follow progress

### KPIs
[10203 KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/10203_product_outline.md#kpis)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [x] KPIs have been groomed and connected to Domo
- [x] Dashboard has been shared back with the VFS team

**Comment by bmcgrady-ep** [comment]
Here is the 10203 DOMO Dashboard (WIP) - https://va-gov.domo.com/page/558555603.

Also, per [conversation with Amy Knox](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13103#issuecomment-696981700), we need the COE (certificate of eligibility) data from the team in Buffalo to complete the Valid Submission KPI card.

**Comment by bmcgrady-ep** [comment]
Per [this](https://dsva.slack.com/archives/D01BQRSK8R0/p1601570659001200) slack conversation with Amy, the new ask is for 2 more goal funnels.

_From Amy_:
A funnel with successful submissions of just eligible users (applicants don't see "initial confirm eligibility" page nor " STEM confirm eligibility" page)?
A funnel with successful submissions of all ineligible users (users see "STEM confirm eligibility" page and submit anyway)?

**Comment by bmcgrady-ep** [comment]
@amyknox - The funnels have been added to the [DOMO dashboard](https://va-gov.domo.com/page/558555603). Let me know what you think.

**Comment by amyknox** [comment]
@bmcgrady-ep 
Thank you - this is looking promising!  Curious about a couple things... 

1. Confirming that 
**10203 - Eligible Applicants Goal Funnel** is: A funnel with successful submissions of just eligible users (applicants don't see "initial confirm eligibility" page nor " STEM confirm eligibility" page)?
**10203 - Ineligible Applicants Goal Funnel** is: A funnel with successful submissions of all ineligible users (users see "STEM confirm eligibility" page and submit anyway)?

2. Is it possible to include the description of the various funnels within the dashboard so the distinction between the 4 funnels is clear? 

3. What's the date range for the various funnels - and how can you tell? 

4. What does "Sum of step number" mean in the lower funnels?

5. What would be the LOE of moving funnels and graphs around the dashboard?  Based on what we have now, we may want to flip the whole thing... 
 **10203 - Eligible Applicants Goal Funnel**  and **10203 - Ineligible Applicants Goal Funnel** at the top.
**Form 10203 - Open Funnel** and **Form 10203 - Closed Funne**l in the middle 
**10203 Successful Submissions vs 1995 Successful Submissions** at the bottom. It's going to become less relevant as time passes so we may eventually want to eliminate it. 

My goal is to share this internally with the BAH team tomorrow morning and with Education tomorrow afternoon. I'll let you know if they have any additional input or questions.

**Comment by bmcgrady-ep** [comment]
@amyknox To answer your questions:
1. 10203 - Eligible Applicants Goal Funnel is: A funnel with successful submissions of just eligible users, however these users could see the "initial confirm eligibility" page. We can change that, but can't an eligible user see the "initial confirm eligibility" page and still be **eligible** as long as they don't see the "STEM confirm eligibility" page?
2. Yes, that is the case for the second Goal Funnel.
3. The Goal Funnels are starting from September 1st - Present. Let me know if you want a different date range. Also, I added the date range to the cards.
4. I believe it was an irrelevant calculation in DOMO, but I removed it from the funnels.
5. I went ahead and moved these around.

**Comment by amyknox** [comment]
Thanks for the quick turnaround on those Qs.  Responses with a couple follow-ups: 

1. 10203 - Eligible Applicants Goal Funnel:  The "Initial confirm eligibility" page is triggered when an applicant has selected a non-Ch33 benefit on the Education Benefit Page.  So if they see "Initial confirm eligibility", they're ineligible.  Those applicants will (should!!) also see the STEM Confirm Eligibility page as a 2nd notice that they're ineligible. 

2. Great!

3. The form launched early Sept. so I'm ok with starting 9/1/20.  Curious if the date range will be static for the dashboard or if it increments forward like in Google Analytics?   

3b. What are the date parameters for the "10203 Successful Submissions vs 1995 Successful Submissions" chart? Will that be static - always starting 1/1/2020 or will that increment? 

4. Thank you.

5. Excellent! I like it.  Also like the placeholder for the 22-10203 valid submissions + approved applications API at the bottom of the page.

**Comment by bmcgrady-ep** [comment]
@amyknox 
1. This has been updated to remove the "initial confirm eligibility" page.
3. The date range updates every morning with the previous day's data, so it will increment forward like in Google Analytics.
3b. The date parameters for the "10203 Successful Submissions vs 1995 Successful Submissions" chart are January 1 - Present. They also update each day and increment forward.

**Comment by amyknox** [comment]
This is so good! Just 2 more questions:  

1. Could we swap the top 2 funnels so we have Eligible Applicants funnel on the left & Ineligible on the right? 

2. In the 10203 - Ineligible applicants... triple checking these applicants may or may not see "Initial Confirm Eligibility" but definitely see " STEM Confirm eligibility"? 

If it's only showing the applicants who see "Initial Confirm Eligibility", we are only seeing those who are ineligible due to their benefit and not those ineligible due to exhaustion of Ch33 &/or field of study. All ineligible users will see STEM Confirm eligibility so if that's how the data is being pulled, we're good.

**Comment by bmcgrady-ep** [comment]
Hi @amyknox - 
1. Just swapped the top 2 funnels. 
2. Yes, those are applicants who definitely see the "STEM Confirm eligibility" page.

**Comment by bmcgrady-ep** [comment]
Hi @amyknox - does the dashboard look good? Let me know if we need to change anything, thanks!

**Comment by amyknox** [comment]
@bmcgrady-ep the dashboard looks great. I'll confirm with stakeholders on Thursday that all is a-ok, then we can close this. Thank you for all your help with this effort.

**Comment by joanneesteban** [comment]
@amyknox let us know if you need anything else!

**Comment by amyknox** [comment]
@joanneesteban - @bmcgrady-ep and I were chatting about refining the 22-10203 funnel so we can track eligible submissions vs. all submissions and be able to look at those numbers for specific periods of time. 

Eligible submissions are not the same as successful submissions.
* Successful submissions are applications that successfully make it through to the Confirmation page.
* Eligible submissions are applications where no eligibility alerts were triggered. 

LMK if that work should be done here or in a new story.

**Comment by bmcgrady-ep** [comment]
@amyknox - Thank you for your patience here. After looking into this, the goal funnels in DOMO are for 9/1 - Present (the day before current day). We are not able to filter for the date of the funnels due to funnels being for the entire time period. However, if you want a specific date range for a funnel, I can create a separate funnel for you to use for that date range. 

Also, I created these 2 segments for you eligible 10203 submissions vs ineligible 10203 submissions in Google Analytics. Here are the segments:

- [Education - Ineligible 10203 Submissions](https://analytics.google.com/analytics/web/template?uid=9KHHHB08RVWOnHmkyJhhIg)
- [Education - Eligible 10203 Submissions](https://analytics.google.com/analytics/web/template?uid=RP8kUJ1hTKe1J1ehdeYEWw)

Just copy and paste the links into your browser and then select which view you want to import the segments into. Let me know if you need anything else!

**Comment by amyknox** [comment]
Hi Brian - I can't get those segments to work for me. The eligible applicants segment is showing the same submission rate as all applicants and there are no ineligible applicants which I know is not the case.  

Just a reminder; 
Eligible applicants do not see either of the eligibility alerts.
Ineligible applicants see one or both of the eligibility alerts.  If it makes the work on you end easier, if an applicant sees the 1st alert (Initial confirm eligibility), they will also always see the 2nd alert (STEM Confirm eligibility).  So for the segment, if it makes it easier, we really only need to track the 2nd alert and if they see that and submit, they're an ineligible applicant. 


![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/490d78b0-fa38-40bc-961c-7532014833ea)

**Comment by bmcgrady-ep** [comment]
Hi @amyknox - It should be working now, I had to update the URL structure to the segments. Let me know if you have any issues with getting the segments to work.

**Comment by amyknox** [comment]
Hey @bmcgrady-ep - those are still not working for me.  I reloaded them and then applied the new ones to the goal URL report and still getting the same results as in the screenshot above.  Suggestions?

**Comment by bmcgrady-ep** [comment]
@amyknox - I believe I needed to reshare the updated segments with you. Here they are:
- [Education - Ineligible 10203 Submissions](https://analytics.google.com/analytics/web/template?uid=cPz32eahSAmlh5bqIxsC5w)
- [Education - Eligible 10203 Submissions](https://analytics.google.com/analytics/web/template?uid=Es9kZ89FTaKgHZ5xo8DqPg)

**Comment by amyknox** [comment]
Hey @bmcgrady-ep - Somethings night right.  These look too good.  We used to have a 90% rejection rate due to ineligible applicants and now we have a 99.9% eligible rate, per Google Analytics. 

Also, checking against DOMO from 9/1, we have 147 ineligible applicants but GA segments say 40 for the same time period (pic below).  And then... when you look at just October, the number of ineligible applicants for that shorter period of time more than doubles to 84 (2nd pic). ??

![image](https://user-images.githubusercontent.com/41081945/98742094-d4055180-237b-11eb-98f7-43f7b1570235.png)

![image](https://user-images.githubusercontent.com/41081945/98742114-d9fb3280-237b-11eb-8635-d0fdb0631cbe.png)

**Comment by bmcgrady-ep** [comment]
@amyknox - Which view are you looking at the segments in? I am looking in the Education View and [this](https://analytics.google.com/analytics/web/#/report/conversions-goals-uri/a50123418w177519031p184334251/_u.date00=20200901&_u.date01=20201111&_.goalOption=14&_.useg=builtin1,userDMHO769BTESNeHi92VYkmA,usercd7wBgawSwiyECkOmRKpVg) is the result I get with the segments, which closely matches the numbers in [DOMO](https://va-gov.domo.com/page/558555603).
![image](https://user-images.githubusercontent.com/66263904/98983961-c3212100-24de-11eb-9aa0-2d90447449c8.png)

**Comment by amyknox** [comment]
I don't know what was happening Tuesday.  My numbers look like yours today.  However... wanting to confirm this 1 more time: 
Ineligible applicants = applicants who see this page: https://www.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/benefits/confirm-eligibility

I know it seems redundant to keep asking this but it is the make-or-break for the 22-10203 and I want to be sure we're on the same page (literally)! 

![image](https://user-images.githubusercontent.com/41081945/98989944-ce347b00-24f7-11eb-958e-5884ef11ed00.png)

**Comment by bmcgrady-ep** [comment]
@amyknox - Yep! This is the page that I have filtered out on the segment - `/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/benefits/confirm-eligibility`.

**Comment by amyknox** [comment]
That's the page you filtered out on the "**Eligible 10203 Submissions**" segment?

**Comment by bmcgrady-ep** [comment]
No, that's the page that I am filtering for ineligible 10203 submissions - a user who lands on that page and submits the 10203 form would be an ineligible submission.

**Comment by amyknox** [comment]
Whew! I was using "filtering" in a different way.  Glad we're on the same page.  I think we're all good and... can CLOSE THIS STORY!!

Thank you so much for working through this.

**Comment by bmcgrady-ep** [comment]
Happy to help! Feel free to reopen if you have any more questions!

**Comment by amycesal** [comment]
The colors are matched across funnels:
<img width="660" alt="Screen Shot 2020-11-13 at 12 48 56 PM" src="https://user-images.githubusercontent.com/1656046/99109609-b4a23a80-25ae-11eb-9a7a-6ef3e49f758f.png">

**Comment by joanneesteban** [comment]
Thanks for the tunnel fix, @amycesal Let's also add the tunnel table to be able to see the percentage dropoff.

**Comment by amyknox** [comment]
@bmcgrady-ep The numbers in my GA reports aren't mapping correctly to the DOMO reports.  I'm also seeing an issue with the number of  submissions increasing when I make the timeframe shorter.  

22-10203 Submissions – Sept. 1 – Nov. 16, 2020
https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goals-uri/a50123418w177519031p184334251/_u.date00=20200901&_u.date01=20201116&_.goalOption=14&_.useg=builtin1,userzXgjk_0KTD6wipY8EsCSZw,userYWEd4_fEQcqVU3Sk9jXzdw/ 
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/04226257-ee48-43a9-aa1c-7611e06ec820)
 

22-10203 Submissions – Sept. 10 – Nov. 16, 2020 (updated start date only – observe how number of all submissions is greater despite the shorter timeframe)
https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goals-uri/a50123418w177519031p184334251/_u.date00=20200910&_u.date01=20201116&_.goalOption=14&_.useg=builtin1,userzXgjk_0KTD6wipY8EsCSZw,userYWEd4_fEQcqVU3Sk9jXzdw/ 
 
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/1b07776a-cb3d-4f73-8ef5-a3af295e2d3d)

**Comment by bmcgrady-ep** [comment]
@amyknox - I confirmed that the Goal Conversion is working correctly. The difference in the numbers has something to do with data sampling in Google Analytics.

**Comment by bmcgrady-ep** [comment]
@amyknox - If you remove the **All Users** segment from your analysis, this should give you normal numbers (when you narrow the date range the goal conversions go down). 

Here is a screenshot of the results that I got when removing the **All Users** segment: 

**Date Range: September 1 - November 16**
![image](https://user-images.githubusercontent.com/66263904/99422502-deb07100-28bc-11eb-9f39-a96631b91bc5.png)

**Date Range: September 10 - November 16**
![image](https://user-images.githubusercontent.com/66263904/99422678-03a4e400-28bd-11eb-97f3-42f4b7101478.png)

**Comment by amycesal** [comment]
<img width="636" alt="Screen Shot 2020-11-17 at 3 00 10 PM" src="https://user-images.githubusercontent.com/1656046/99462000-71bacc80-28f8-11eb-9577-ab63f32a644c.png">

@bmcgrady-ep The data for the closed funnel doesn't include the percentage change. I can't include it in the table if it's not in the data. Let me know when it's fixed. Thanks!

**Comment by bmcgrady-ep** [comment]
@amycesal - I updated the data to include Percent Change. I had to create a new dataset, so can you update the table colors?

**Comment by amycesal** [comment]
All the funnels! 
<img width="440" alt="Screen Shot 2020-11-24 at 4 48 20 PM" src="https://user-images.githubusercontent.com/1656046/100160304-ebad0180-2e74-11eb-81a6-e6cbc9fdfd1a.png">

**Comment by bmcgrady-ep** [comment]
@amyknox - Is there anything else you need in regards to this ticket? If not, I will close it out.

**Comment by amyknox** [comment]
@bmcgrady-ep Thank you & the rest of the team for your great work on this.  Looks good to me to close!

**Comment by bmcgrady-ep** [comment]
@amyknox - Glad we can help! Feel free to reopen if there is anything else you need!
