### ISSUE TITLE
Analytics KPI dashboard request for eBenefits

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13104]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Submit this ticket as an epic
- [ ] Add your team label to follow progress

### KPIs
[Dependency Claims KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/README.md#okrs--kpis)
[28-8832 KPIs (WIP)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/README.md#kpis-okrs)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by jonwehausen** [comment]
## Remaining Updates

### Context
- Here is the [groomed metrics ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13105) 
- Here is the existing [eBenefits KPI Dashboard](https://va-gov.domo.com/page/1726972169). This dashboard involves Form 21-686c, View Payment History & Chapter 36 (Form 28-8832) products. 
- @JasonTheBearded the remaining KPI dashboard updates here involve Chapter 36 (screenshot above) -- it's form 28-8832
- Launches for view payment history will be happening over the coming days and chapter 36 occurred on Monday Jan 4, 2021
- The remaining dashboard updates for chapter 36 are screenshot below (also in groomed metrics ticket) 
![image](https://user-images.githubusercontent.com/48527022/103688651-1c965100-4f60-11eb-8b52-73b033beece6.png)

### Updates 
- Create a dataset for an Open & Closed Funnel for 28-8832, reflect conversion and abandonment rates
- Leverage existing form events datasets to surface submissions, has a `careers-employment` prefix
- Please see [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14537) for the latest and next steps on view payment history updates

**Comment by jonwehausen** [comment]
@JasonTheBearded see above
