### ISSUE TITLE
Parallelize specs in CircleCI

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#13107]
## Issue Description
CircleCI allows for specs to be run in parallel by specifying a parallelism key. By combining this key along with CircleCI's test splitting algorithm, specs can be run in parallel across multiple containers, significantly speeding up the spec job run time. 

---
## Tasks
- [ ] Research/Test the most efficient way to split the tests (by filename, timing, filesize)
- [ ] Ensure that specs run 

## Acceptance Criteria
- [ ] Spec job runs in Circle across multiple containers
---
