### ISSUE TITLE
Pilot Medallia Survey with Facility Locator

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13101]
# Pilot the Medallia VFS specific survey

## Description
Test the Medallia VFS specific survey with Facility Locator. 

Other info: ForeSee data is pulled into Domo manually every Monday. Medallia data will also be pulled into BigQuery/Domo manually until the Medallia<>BigQuery ATO is completed.

### Staging URLs
*Please provide staging URLs*

### Production URLs
*Please provide Production URLs*

### Tasks
- [ ] VSA Facility Locator provides URL(s) where feedback button should appear
- [ ] VSP Analytics & Insights to remove ForeSee staging URLs if these are the same
- [ ] Both VSP and VFS teams test, provide feedback if any, and approve
- [ ] VSP Analytics & Insights to remove ForeSee production URLs if these are the same
- [ ] VSP Analytics & Insights push Medallia survey to production
- [ ] Both VSP and VFS teams test, provide feedback if any

## Acceptance Criteria
VFS team and VSP can retrieve user survey information from 
- [ ] Survey tested and approved by both VSP and VFS teams in staging
- [ ] Survey pushed to production

---
### Screenshot of survey:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/95f3c511-a9fa-443b-9ed0-7dce67e4f347)

**Comment by joanneesteban** [comment]
@mmiddaugh Do you want to start out with the same pages that are being tracked on ForeSee? We can also start out with VAMC instead!

**Comment by mmiddaugh** [comment]
yes, please! I think that would be a good place to start. I'll talk with @davidconlon about if/when/where to start with the VAMC pages but in the meanwhile, Facility Locator could use the feedback.

**Comment by joanneesteban** [comment]
### Update - 09-08-2020

**Staging URL removed from ForeSee:** *staging.va.gov/find-locations

The feedback button on ForeSee is still appearing on Staging for me. @mmiddaugh could you check on your end to see if this is also the case for you? I might need to open a case with ForeSee before we can add in Medallia.

**Comment by mmiddaugh** [comment]
I just checked staging and I do not see the Foresee feedback button @joanneesteban 
Could it be blocked for me as a pop-up or appearing due to caching for you?

**Comment by joanneesteban** [comment]
@mmiddaugh hm, it might be blocked as a pop up for you. I cleared my cache, tested in incognito, and on other browsers

**Comment by joanneesteban** [comment]
@mmiddaugh let me know if this is appearing on your end as well. I'm speaking with ForeSee about how to take it out.

**Comment by mmiddaugh** [comment]
I still don't see it....even in an incognito window

**Comment by joanneesteban** [comment]
@mmiddaugh thanks! Fysa added the Medallia button to the staging site. We're still working on tweaking the design a bit, but will let you know when it's ready to test.

**Comment by mmiddaugh** [comment]
@joanneesteban based on a conversation with Dave recently, we won't be implementing Medallia on VAMC pages quite yet. Timing will be contingent on the number of VISNs rolled out and availability of instant publishing. (Right now only one system has rolled out although two VISNs are very close)

 I created [#13724] to keep it on our radar

**Comment by joanneesteban** [comment]
@mmiddaugh sounds good, thanks for creating that! 

How are y'all feeling about the current question flow? (3 questions without logic)

**Comment by mmiddaugh** [comment]
Since this is consistent with the implementation across VA.gov, no objection! Thank you

**Comment by joanneesteban** [comment]
@mmiddaugh we're working on some design and code fixes, which may be several days. Apologies for the delay.

**Comment by joanneesteban** [comment]
fysa @mmiddaugh design work is being tracked on #[13287](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13287) .

**Comment by joanneesteban** [comment]
@mmiddaugh the Medallia pilot is ready to test on staging.va.gov/find-locations

Let me know if you have any questions!

**Comment by jwoodman5** [comment]
Pilot was a success.
