### ISSUE TITLE
STEM Form 22-10203: Remove basic authentication for STEM form URL

### ISSUE THREAD

**Issue by shawkey-daniel** [department-of-veterans-affairs/va.gov-team#13111]
## Issue Description
The STEM Form 22-10203 is set to go live with a limited production rollout on September 2, 2020. Basic authentication should be removed to allow limited rollout access in production.

The STEM Form 22-10203 can be found here: [STEM Form 22-10203](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [X] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Configuration updated and manually deployed to dev, staging, and prod.
