### ISSUE TITLE
window.sideNav is missing

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#13113]
## Issue Description
The `window.sideNav` is missing in the CMS build for the following node types:

- event_listing
- full_width_banner_alert
- health_care_local_facility
- health_care_region_detail_page
- leadership_listing
- person_profile
- press_releases_listing
- story_listing
- vamc_operating_status_and_alerts

## Example:
```
window.sideNav = {"links":[]};
```

## Example File
`/pittsburgh-health-care/events/index.html`

## Tasks
- [x] Figure out why the `window.sideNav` field is blank.
- [x] Resolve issue, and verify the output matches the GraphQL content build.

## Fix all transformers

- [x] event_listing
- [x] full_width_banner_alert
- [x] health_care_local_facility
- [x] health_care_region_detail_page
- [x] leadership_listing
- [x] person_profile
- [x] press_releases_listing
- [x] story_listing
- [x] vamc_operating_status_and_alerts

**Comment by swirtSJW** [comment]
window.sideNav looks like it may be a subquery of data that does not exist on the node itself.

**Comment by swirtSJW** [comment]
Multiple sub queries it looks like https://github.com/kevwalsh/vets-website/blob/b65c1531ff9334f567ffcac3da087c04b8897aa5/src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js#L19
We might have to reqroup on the best way to obtain this from the CMS Content Export.

**Comment by indytechcook** [comment]
@jhonnyoddball can you provide the full GraphQL query for the call to `GetLatestPageById`. We can then look at making sure that info is on the CMS export.

**Comment by jhonnyoddball** [comment]
## Issue Discovery

### Facts
- This is coming directly from GraphQL
- Verified that it is working for other transformers but not for some
- Problem seems to be field_office = null. This is only caused when there is a circular reference

### Tested transformer `health_care_region_detail_page`
**transformer**: src/site/stages/build/process-cms-exports/transformers/node-health_care_region_detail_page.js
```
  fieldOffice:
    entity.fieldOffice[0] &&
    !ancestors.find(r => r.entity.uuid === entity.fieldOffice[0].uuid)
      ? { entity: entity.fieldOffice[0] }
      : null,
```
I debugged both cases below and confirmed that the one without SideNav the `ancestor.entity.uuid === entity.fieldOffice[0].uuid`

### With SideNav working
**node**: `node.00f8a6a5-37a6-478c-b5d0-4eaa87b5bdd1.json`
**path**: `/pittsburgh-health-care/medical-records-office`
**field_office**: `node.2bddb1a7-6fb1-4503-838d-9c2fcb51c46a.json`

### Without SideNav working
**node**: `node.d04f8842-cc3a-46ef-b021-0b70c248f224.json`
**path**: `/pittsburgh-health-care/policies`
**field_office**: `node.2bddb1a7-6fb1-4503-838d-9c2fcb51c46a.json`

**Comment by jhonnyoddball** [comment]
### Issue Tracing

1. The `window.sidebarNav = sidebarData` line can be found - [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/navigation/facility_sidebar_nav.drupal.liquid#L14).
2. `sidebarData` is defined in the parent template's include - [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/health_care_region_detail_page.drupal.liquid#L79).
  - Note that the `entityUrl.path != "/outreach-and-events"`, so it's the else branch
3. This is where I lose it a little bit, but I think the next step up is where the `facilitySidebar` is `defined` - [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/page.js#L292)
4. Follow that to the `getFacilitySidebar` function, and we see this little gem - [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/page.js#L246-L247)
5. This will be returned if:
  a) The `if` statement is [false](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/page.js#L215-L219), OR
  b) The `nested if` statement is [false](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/page.js#L241-L243)
6. In this case, we know that
  a)  `facilityPage` is false because `page.fieldOffice` is `null` (or even undefined by the time the transformer is done)
  b) `localFacilityPage` is false because `page.fieldRegionPage` is undefined
  c) `page.entityBundle !== 'health_care_region_page'` because it's actually `health_care_region_detail_page`

## The fix
Don't return `null` for the `fieldOffice` when we encounter a circular reference. Instead, only return the pieces that are needed in [this function](https://github.com/department-of-veterans-affairs/vets-website/blob/8064865b4c89c085115bb62287cc0f669f77810b/src/site/stages/build/drupal/page.js#L204).

**Comment by jhonnyoddball** [comment]
Fixed
