### ISSUE TITLE
Personal & contact information

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13120]
# User Story
- [ ] As a user, I can view my date of birth and gender
- [ ] As a user, I can view and edit all addresses in /v0/user endpoint, all phone numbers in /v0/user endpoint, fax number, and mail address
- [ ] As a user, when editing my addresses, I can select "I live on a United States military base outside of the United States.". This selection will update the form fields on the page to reflect different input values.
- [ ] As a user, I cannot delete my mailing address once it's entered.
- [ ] As a user, I can delete my other addresses besides mailing, my phone numbers, and my email.
- [ ] As a user, I can view informational text for "How do I update my personal information?" and navigate to pre-populated views of Find a VA Location in an in-app web view of VA.gov.
- [ ] As a user, I can view informational text for "How will you use my contact information?".

# Tasks
- [x] High fidelity prototype of screens in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing, as needed) UI for a range of devices we are supporting, Android-specific designs

# Prototype
- [Wireframe, Personal and Contact Information default screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636868)
- [Wireframe, Input of Domestic address](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636869)
- [Wireframe, Input of Military Base address](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431899953)
- [Wireframe, Input of phone number](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636870)
- [Wireframe, "How do I update my personal information?"](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636872)
- [Wireframe, "How will you use my contact information?"](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636871)

# Content documentation (including required fields and character limits)
- [Link to content documentation](https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit#gid=0)

# Keyboards
- In the edit state for phone and fax numbers, the numerical keyboard should come up when users tap into the fields. 
- In the edit states for address and email, the alphabetic keyboard some come up when users tap into the fields.
- In the edit states where information is already entered in the field, when a user tabs into a field to edit information, they should see a clear CTA on the righthand side of the field. 

# Saving
- The 'Save' CTA in the upper right corner should not active until a user has entered the required information. 

# API Tagging
[Profile API tagging](https://www.figma.com/proto/0SGZH6YNbMAPsdaHC4xIjl/API-Data-Tagging?node-id=1%3A2&scaling=min-zoom)

**Comment by bridgethapner** [comment]
@artsymartha68 Hi there - Per our work session earlier today, I've tweaked the UI to align more strongly with HIG. I have maintained some usage of Source Sans and Bitter, loosely setting the rule of tables & edit states using iOS default styles, but keeping VA styles elsewhere. Would love your feedback here on how this balance / multiple font usages feels to you!

[Prototype link](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636868_Personal_And_Contact_Information)

**Comment by bridgethapner** [comment]
Notes for Erik (who I cannot tag): 

Personal & Contact Information is near finalized. The way we wrote UX stories is broad, and since I'm not sure if you might want to break down the front end stories into finer detail, I want to outline here everything that is going on here on this screen: 

# UX Summary

1. As a user, I can view my date of birth and gender
2. As a user, I can view and edit my addresses, phone numbers, and email address
([relevant wireframe](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636868))

---

3. As a user, when editing my addresses, I can select "I live on a United States military base outside of the United States.". This selection will update the form fields on the page to reflect different input values. 
([relevant wireframe 1](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636869), [relevant wireframe 2](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431899953))

4. As a user, I cannot delete my mailing address once it's entered. 

5. As a user, I can delete my other addresses besides mailing, my phone numbers, and my email. 

---

6. As a user, I can view informational text for "How do I update my personal information?" and navigate to pre-populated views of Find a VA Location in an in-app web view of VA.gov. 
- **Find your nearest VA medical center** should link to: https://www.va.gov/find-locations/?facilityType=health
- **Find your nearest VA regional office** should link to: https://www.va.gov/find-locations/?facilityType=benefits
([relevant wireframe](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636871))

---

7. As a user, I can view informational text for "How will you use my contact information?". 
([relevant wireframe](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636872))

**Comment by erikbreedlove** [comment]
@bridgethapner

**Comment by artsymartha68** [comment]
I sign off on the main UX features for MVP. These are super nit-picky wording things:

1. On Personal Info screen: Maybe "when you edit information in this app"? Definitely need a content designer's final edits here.
2. Mailing address: "US" instead of "United States" twice? Need to be consistent throughout

**Comment by bridgethapner** [comment]
Thanks @artsymartha68! 

- I added Personal Info screen to ticket #14031 to asl for a Content review later. 
- Not sure about #2, let's talk in our touch base :)
