### ISSUE TITLE
Create Flipper Component for CH36 Unauthenticated Landing Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13129]
## Background
Part of the phased rollout requires the ability to granularly control who sees the new application we are building on VA.gov as opposed to eBenefits so that we can control who accesses it.

## Considerations
- Due to the feature size and the looming deadline, should we skip the feature toggle and use basic auth for moderated and just open it for unmoderated? (Like what we did for Rated Disabilities)
  - With a minimal footprint on the unauth landing page, we can ask for the flipper component to be inserted pretty cleanly

<details>
<summary><b>Expand to see flipper state for old path:</b> Go back to eBenefits, keep the subway instructions</summary>

![EBN-oldv2](https://user-images.githubusercontent.com/53826255/92036918-f4db7600-ed3e-11ea-8929-afd22eb2f970.JPG)

</details>
<details>
<summary><b>Expand to see flipper state for new path:</b> Go on to the new VA.gov application, just need the button</summary>

![VA-new](https://user-images.githubusercontent.com/53826255/92036653-944c3900-ed3e-11ea-8249-6656f1e9ab0c.JPG)

</details>

## Tasks
- [ ] Discuss with PW about what we intend to change in the flipper component
- [ ] Create a flipper component to be shared with the Public Websites folks for implementation
  - [ ] Include the subway map for the old path
  - [ ] Allow the button to change from "Go to eBenefits to apply" to "Apply for career counseling"
- [ ] Config feature toggle for profile

## Acceptance Criteria
- [ ] A flipper component has been shared with the PW team
