### ISSUE TITLE
[Bug] Profile 2.0: Address validation — We are getting an error if someone tries to override address validation, but only if there are multiple confirmed suggestions

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#13121]
## Background

We are getting a "something went wrong error" for address validation, but only if there are address suggestions. If there are not suggestions, override works just fine.

Steps to duplicate:

1. Sign in to Profile 2.0. I used user 226, but it probably doesn't matter.
2. Edit the mailing address. First try :

1510 Park, Washington, DC, 20017

3. You'll go through the address validation flow. Select Update Address. This *should* save and close the form.
4. Now edit the mailing address again. Try this:

575 20th, San Francisco, California, 94122

5. You'll get the the address validation flow again, but this time, you'll have suggested addresses. **Choose the address you originally entered under "You entered", and try to save it**. This should cause an error, like so:

![Screen Shot 2020-09-02 at 11.24.20 AM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/6e15be51-523c-4fc4-b75f-540c0c5b453a)

**However**, if you choose a suggested address, it should save just fine.

**Desired functionality**: A person should be able to override address validation even if there are suggested addresses.

## Tasks

- [ ] Investigate why we are preventing override for address validation when there are suggestions.
- [ ] Implement a fix so that people can override address validation whether there are suggestions or not.

**Comment by erikphansen** [comment]
@Samara-Strauss This is a great find. It seems to only happen when you try to force through the address that you entered _if you get back more than one valid suggestion_. Which is super rare. But:
- VA Profile should accept that user-entered address since we are passing along a validation key
- Our FE should handle the error to create the transaction more gracefully

More notes below:

Tried to save this address:
```
{
  "address": {
    "id": 192573,
    "addressLine1": "575 20th",
    "addressType": "DOMESTIC",
    "city": "San Francisco",
    "countryCodeIso3": "USA",
    "stateCode": "CA",
    "zipCode": "94122",
    "addressPou": "RESIDENCE/CHOICE"
  }
}
```

got this back from the validation API:
```
{
  "addresses": [
    {
      "address": {
        "addressLine1": "575 20th St",
        "addressType": "DOMESTIC",
        "city": "San Francisco",
        "countryName": "United States",
        "countryCodeIso3": "USA",
        "countyCode": "06075",
        "countyName": "San Francisco",
        "stateCode": "CA",
        "zipCode": "94107",
        "zipCodeSuffix": "4345"
      },
      "addressMetaData": {
        "confidenceScore": 100.0,
        "addressType": "Domestic",
        "deliveryPointValidation": "CONFIRMED",
        "residentialDeliveryIndicator": "BUSINESS"
      }
    },
    {
      "address": {
        "addressLine1": "575 20th Ave",
        "addressType": "DOMESTIC",
        "city": "San Francisco",
        "countryName": "United States",
        "countryCodeIso3": "USA",
        "countyCode": "06075",
        "countyName": "San Francisco",
        "stateCode": "CA",
        "zipCode": "94121",
        "zipCodeSuffix": "3122"
      },
      "addressMetaData": {
        "confidenceScore": 100.0,
        "addressType": "Domestic",
        "deliveryPointValidation": "CONFIRMED",
        "residentialDeliveryIndicator": "RESIDENTIAL"
      }
    }
  ],
  "validationKey": -1717050336
}
```

forced through the user-entered "bad" address with the validation key:
```
{
  "id": 192573,
  "addressLine1": "575 20th",
  "addressType": "DOMESTIC",
  "city": "San Francisco",
  "countryCodeIso3": "USA",
  "stateCode": "CA",
  "zipCode": "94122",
  "addressPou": "RESIDENCE/CHOICE",
  "validationKey": -1717050336
}
```

got back this error:
```
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_address_transactions",
    "attributes": {
      "transactionId": "0f7bd0c2-3ccb-4d90-8c45-44a2c9d5c216",
      "transactionStatus": "COMPLETED_FAILURE",
      "type": "AsyncTransaction::Vet360::AddressTransaction",
      "metadata": [
        {
          "code": "ADDRVAL206",
          "key": "addressBio.MultipleAddressError",
          "retryable": null,
          "severity": "ERROR",
          "text": "Multiple matches found for this address"
        }
      ]
    }
  }
}
```

and then we started to endlessly poll the update endpoint `GET 0f7b0c2...` (which we shouldn't call at all since the previous transaction creation call failed!)
```
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_address_transactions",
    "attributes": {
      "transactionId": "0f7bd0c2-3ccb-4d90-8c45-44a2c9d5c216",
      "transactionStatus": "COMPLETED_FAILURE",
      "type": "AsyncTransaction::Vet360::AddressTransaction",
      "metadata": [
        {
          "code": "ADDRVAL206",
          "key": "addressBio.MultipleAddressError",
          "retryable": null,
          "severity": "ERROR",
          "text": "Multiple matches found for this address"
        }
      ]
    }
  }
}
```

- [ ] why does VAP respond with `ADDRVAL206` even though we sent a validationKey?
- [ ] why doesn't our FE handle the `COMPLETED_FAILURE` response? we should not be polling for updates! we shouldn't check for updates at all.

**Comment by erikphansen** [comment]
Current status is that the VA Profile team are going to move forward with requesting that ADDRVAL206 be made an overridable error. We'll check in periodically for updates/progress. So we don't need to do anything on our side other than wait and check in on this again.

**Comment by Samara-Strauss** [comment]
Removed Sprint 30 milestone since we can't do anything about this until VA Profile updates how they handle ADDRVAL206. Adding blocked label as well.

**Comment by erikphansen** [comment]
This is still an issue that VA Profile needs to resolve. Will ping them on Slack to get an update.

**Comment by Samara-Strauss** [comment]
[Per Ian McEwan in Slack](https://dsva.slack.com/archives/C7TE0PFTL/p1609868613233900), the ADDRVAL206 fix to allow override when there are 2+ suggestions is already live in the lower environments, and I confirmed it worked in staging. This should go out to production in their 1/11 release.

**Comment by Samara-Strauss** [comment]
Confirmed that this is now working in production. Is there anything else we need to do here? If not, we can close.

**Comment by erikphansen** [comment]
Nice! I think we can close it.
