### ISSUE TITLE
Confirm page

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#13131]
---
## Tasks
- [x] Evaluate other review screens from form system
- [x] Create detailed mockup 

## Acceptance Criteria
- [x] UI review meeting with accessibility
- [x] UI review meeting with product for feature capabilities
- [x] UI review meeting and callouts with engineering for layout and callouts
- [x] Published to [Zeplin](https://zpl.io/bWeqwke)

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mdewey Same as the other story. What engineering story will the confirmation page be reviewed? I'll add the wireframes to that story once I know.

**Comment by kristenmcconnell** [comment]
Adding this back. @abuckley3385 @mdewey Do we have a story to review the confirmation page in code and make any necessary changes to the out-of-the-box implementation?
