### ISSUE TITLE
[DISCOVERY] Pagination for PPMS

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13138]
## Issue description
PPMS does not provide a result count and does not support paginated queries.

On September 2, 2020 OCC reported an issue in the results presented on page 2 following the list returned on page 1

<details>
<summary> Page 1 for zip 22314 </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/0e18e77c-89f3-48cd-87f7-2f42dce2a127)

</details>

<details>
<summary> Page 2 for zip 22314 </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/e23be79d-5dcc-47c1-9da5-8ce1e469aa0a)

</details>

Because we know from Veteran research that the most important parameter is proximity, we assume the first results in the list (representing the closest locations) are most interesting to Veterans and they are unlikely to click into subsequent pages. (We will confirm with analytics). We chose to remove pagination from Community care searches in [#12715](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12715) and restrict the results to a list of 10 to optimize performance as much as possible. 

Now that the query has been optimized, we can revisit pagination and determine the best solution

## Task
 - Determine **front and backend** options for returning pagination, specifically for any PPMS searches (for urgent care, urgent care mash-up, pharmacies and providers)

## Acceptance criteria

Document options for returning pagination
1. If PPMS makes changes 
- [ ] required tasks for front end and back end
- [ ] level of effort
- [ ] what changes need to be requested from PPMS (such as handling order and offset parameters)

2. If PPMS makes no changes: 
- [ ] required tasks for front end and back end
- [ ] level of effort

**Comment by mmiddaugh** [comment]
Blocked pending PPMS single query change (ETA - November)

**Comment by darkbushido** [comment]
## PPMS Adds Support for Pagination
### PPMS needs the following
  - Defined sort order
  - page number
  - page size
### Back-end needs to do the following (3pts)
  - sort parameter
  - page size
  - page number
### Front-end tasks (3pts)
  - page number
  - page size

## Front-end pagination
### Front-end tasks
  This needs to apply to all facility queries not just PPMS
    (FE doesn't want to support multiple pagination methods)
  This may have a negative effect on mobile devices
  - pull results into Redux State (8pts)
  - create a new pagination component to query Redux State (13pts)
### Back-end tasks
  - increase max request size if more than 50 are needed

## Back-end pagination
### Front-end tasks (3pts)
  - page number
  - page size
### Back-end tasks
#### Multiple requests route (3pts)
  may not have consistent sort order
  - request page number * page size
  - return last page of results
#### API Caching route (13pts)
  - make a single large request
  - cache it in redis
  - return results from cache

**Comment by saneshark** [comment]
If I could weigh in on this a little bit. The problem with duplication almost seems to make any effort at allowing pagination somewhat useless unless there is a way to request no duplicates from PPMS. In other words they would need to support proper pagination without duplicates for us to realize any real performance improvement. Outside of that it gets to be a little messy. 

If I were to approach the problem as it currently stands:

Basically to de-dupe and return X number of results, you need to request X+N number of results where N is some buffer such that you can remove pairs (perhaps N=(x/3), but then when you fetch your subsequent page you’d need a cache of the previous page to ensure you’re not including the results from the previous page (cache key could be a checksum of the requested parameters as part of thee query sans the current page parameter). Since you’re doing this variety of short-lived caching, it kind of begs the question whether or not it’s really worth it to paginate at all from a performance standpoint. It might be negligible in actual practice.

**Comment by mmiddaugh** [comment]
Given level of effort and associated risks, a change request for PPMS support of pagination parameters and dedup logic will be submitted.
