### ISSUE TITLE
500 error in Community Care searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13132]
## Issue Description
We’ve observed some searches inaccurately return no results. On the query side, we receive 500 error for some, but not all, searches.

For example, this query - 
https://api.va.gov/v1/facilities/ccp?address=6935%20Olive%20Damsel%20Court,%20Hughesville,%20Maryland%2020637,%20United%20States&bbox%5B%5D=-78.89282226562501&bbox%5B%5D=36.681636065615216&bbox%5B%5D=-75.20690917968751&bbox%5B%5D=40.87614141141369&type=pharmacy&page=1&per_page=10&trim=true

resulted in `{"errors":[{"title":"Internal server error","detail":"Internal server error","code":"500","status":"500"}]}`

**Background:** Because we need to perform two queries to get the full provider information, if one of the results fails on the second query, the entire result set fails and no results are returned. This situation also occurred during a previous data loading period and resolved once the data was completely refreshed (approximately 12 hours later).

**Solution:** We’re making a change today to protect Veterans from this occurrence. The risk to our change is that the name displayed for the failing provider result will default to the name returned in the first response. Again, we believe this issue will only be present until the data is fully refreshed.

---
## Tasks
- [ ] Remove the second query for the provider which fails so that the result list can be returned. 
- [ ] Default name to the value returned in the initial response. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
After this issue, 
1. Facility Locator will check for and log errors which occur when the Provider Locator is not in sync with Provider Details (a rare occurrence based on PPMS data refresh)
2. Make a naming decision so that the results list does not fail
