### ISSUE TITLE
[FE] Save questionnaire in progress 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13148]
## User Story
* **Use Case:**  Provide updates when convenient and relevant with the device and location of choice
When
(1A) As a Veteran, I want the flexibility to decide how far in advance of an appt. with my care team to update health information, so I can take the time needed to thoroughly prepare by locating and completing all information needed

* Description: Questionnaires that have been in progress will leverage the Save in Progress feature of the forms library providing the ability to save data until the user selects to complete and send the questionnaire.
* Consider potential to re-submit the form if the veteran wants to make changes after submission 

## Related Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
[Feature - Questionnaires List ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## Description
Finish integration with the existing Save in-progress feature.  Though mostly already built, it needs some tweaking to work with our form.

## Tasks
- [x] Change the wording on the Buttons
- [x] Change the wording for the Save in Progress message
- [x] Change wording for the message at bottom of the form
- [x] Answer questions 

## Questions
- [x] When does the data expire
- [x] If the above labels can't change, what is the level of effort to change them

## Acceptance Criteria
- [ ] All questions have been answered
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by dillo** [comment]
@mdewey adding myself to this issue for the moment so that I can learn more about this before attempting to decompose it to several user stories.

**Comment by dillo** [comment]
I understand that we want to deal with some sort of "Save in progress." However, in the interest of conveying a more rounded idea of what we're looking to accomplish at a glance, could we re-title this? Perhaps "Save appointment questionnaire in progress?"

**Comment by abuckley3385** [comment]
I don't think we need the **appointment** (as we would need that on all our tickets and its not added info we need) in the title but if adding Questionnaire helps the readability of the title i don't see an issue but again our product is a questionnaire so its a bit self explanatory.

**Comment by dillo** [comment]
I agree with you that adding certain domain level words to the title and body and being verbose can be redundant and obvious to team members. However, my suggestion would be to try and find a balance so that new team members like myself or another member from a different team can look at the story and understand what's being asked even if the implementation details are not clear. In my experience this practice will actually contribute to stories being small in the long term and also has the good chance of eliminating the overhead of questions/lag/answers cycle that we see sometimes while stories are in flight(being coded).

I think it's a positive that we can get to discuss scope during our backlog refinement meetings. It leaves "things" fresh in our minds when starting a sprint. However, in my experience, some epics are better analyzed/decomposed into basic stories in the "Epics" column(after we've had architecture meetings around them) so that the stories that come out of those epics will only need details/fleshing-out/estimation/prioritization during the refinement meetings. Just something we could try if the team is willing. What are your thoughts on this?

**Comment by abuckley3385** [comment]
I create a base EPIC for all the major product features and from there we have created additional EPICs where needed to break down further - so yes this is our current approach but could be used more than it has been. 
Since this specific ticket is Front end ticket only, Mark did a very nice job early on [doing spikes for the Save in Progress the forms library provides](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/engineering#forms-discovery) so I'd assume the team should be able to understand the scope already with the documentation and the "prototype" already implemented and come to back log prepared with the appropriate scope in the ticket for discussion.

**Comment by kristenmcconnell** [comment]
@peggygannon  I meet with engineering yesterday to review all of the save in-progress UI features (as shown in the attached image). Most of the wording doesn't exactly apply to our use case, since we are a questionnaire and not an application. I took a crack at updating all of the wording/UI elements to match are use case better. I wanted to run the changes by you as well. However, engineering is slated to begin this work in two days, so I don't know if that would work with your priorities. Please, let me know if you have any questions.

![Save in-progress.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/014f5619-20b4-4616-874b-47afa609bc0e)

**Comment by kristenmcconnell** [comment]
@mdewey Screenshot in the above comment was just updated based upon our Questionnaire Manager discussion.

**Comment by mdewey** [comment]
EDIT: spelling mistakes.

**Comment by mdewey** [comment]
Labels can change easily, hiding the second `in progress` message requires either a custom text or a change to platform.

**Comment by mdewey** [comment]
` When does the data expire` 30 days since last data changed.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell Hello,  I'm just able to take a look today. These are global form elements, so I recommend you check  with VSP Design System team before updating them.  I believe these are hard coded messages, so I recommend reaching out to Chris Valardia to see if there is anything that needs updating in the code.

**Comment by kristenmcconnell** [comment]
@peggygannon - @mdewey confirmed that around 90% of these suggested changes are easily doable within the variables set forth by VSP. I was hoping to get your feedback earlier, so we could all be in alignment before requesting changes from VSP. I don't want to ask for a change, then learn that you disagree or suggest something else. Thoughts?

If need be, @mdewey - can you fill us in more on the 10% that require a change from VSP?

**Comment by mdewey** [comment]
Yes! It the second line in `Option 1 ` has to be a message, we can config it to be a message, but I am seeing if
the platform team will let me add some config to hide it
![Screen Shot 2020-10-23 at 1 50 36 PM](https://user-images.githubusercontent.com/1793923/97047745-68cc1a80-1547-11eb-8d4f-8455bc7bcb7f.png)

**Comment by peggygannon** [comment]
ok, great @kristenmcconnell and @mdewey Here's what I recommend for the message. I want to avoid repeating the header  in the body of the content. Let me know if this would work? 

**Your questionnaire is in progress**

You can continue answering questions now, or come back later to finish. Your questionnaire will expire on [Month, date, year]. 

{button} Continue questions

**Comment by mdewey** [comment]
Do you still want the `last saved at ` message in there?

**Comment by kristenmcconnell** [comment]
My vote is yes.

**Comment by mdewey** [comment]
@abuckley3385  The team has completed they save in-progress research tasks, and need to do a tech spike.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/save-in-progress/README.md#L12

I will schedule a meeting to review.

**Comment by peggygannon** [comment]
Yes, sorry, i overlooked that!!

**Your questionnaire is in progress**
Your questionnaire was last saved on {date} at {time}. You can continue answering questions now, or come back later to finish. Your questionnaire will expire on [Month, date, year].

{button} Continue questions

**Comment by mdewey** [comment]
Cool deal @peggygannon , that is the change I am looking to make with Platform, I will see have that goes :-)

**Comment by mdewey** [comment]
Merged in wording changes, need to get the platform to approve the hiding or make a decision around that issue.

**Comment by mdewey** [comment]
Found bug, fixed bug in a PR (https://github.com/department-of-veterans-affairs/vets-website/pull/14740/files) waiting for merge

**Comment by mdewey** [comment]
Every is comlet

**Comment by kristenmcconnell** [comment]
When signing in as user 34. 
I don't seem to be able to see the green save in-progress box at the bottom of the questionnaire.

When signing in as user 8, 
1. I see the green save in-progress box, but it is missing a period after "Questionnaire has been saved."
![Screen Shot 2020-10-30 at 4.50.02 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/320ec57b-eb2b-4194-9845-39aa38624ef3)

2. I got the sign-in box, when I was already signed-in. However the button at the bottom of the page was "Start the questionnaire."
![Screen Shot 2020-10-30 at 4.48.45 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/b207e94f-9a63-4679-a3d1-0800c82766e8)

3. When I clicked "Finish this questionnaire later," I saw this (which I think is another spot that we original didn't account for)...
![Screen Shot 2020-10-30 at 4.49.54 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9f2c68ef-c78d-46cb-baa6-85b72558160f)

We should change the first sentence from "Your appointment questionnaire application has been saved." to "Your questionnaire has been saved." The "Start a new application" button should also be removed here.

Maybe the above #3 and hiding the duplicated line should be a new ticket.

**Comment by mdewey** [comment]
Great catches! I see 4 action items

1. Green not showing up for user 34
2. Signed but not showing the resume button, instead of showing the login button
3. Missing Period in the message
4. "Finish later flow" 


I can not reproduce #1 and #2. Can you try again and then we can screen share if it's still doing it. 

For #3 and #4 I will add to #15521 

How does that sound?

**Comment by abuckley3385** [comment]
im good!

**Comment by mdewey** [comment]
As for the extra message: https://github.com/department-of-veterans-affairs/vets-website/pull/14697#issuecomment-721276444

Platform is treating it like a bug and changing how it is handled.

**Comment by mdewey** [comment]
The bug for the inProgress message was fixed and now will be implemented on #15521
