### ISSUE TITLE
Create sharable MVP design library in Sketch

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13140]
As a VA designer, I can use the mobile design library to design future pages and understand what elements support my screen.

# Tasks
- [x] Localize all symbols from HIG/Material/Formation into a Sketch Library
- [x] Set up style sheets for Sketch library.
- [ ] Light vs Dark mode?

**Comment by bridgethapner** [comment]
Setting up common fonts, colors, icons, and general rules for MVP is captured in #14461 so I am editing this ticket to speak to setting up a cleaner, more sharable **Sketch Library**.

**Comment by srmyers17** [comment]
By creating style sheet, we are creating components and documenting them in a low-fi way for git.

**Comment by srmyers17** [comment]
Replace HIG elements with universal, React Native library that jives with style sheet.

**Comment by bridgethapner** [comment]
Starting this morning to be able to share a draft with Melissa for the next sprint

**Comment by srmyers17** [comment]
- Started this AM; working on sharable file with components 
- Plan is to complete before new sprint

**Comment by bridgethapner** [comment]
Have the first draft of a Sketch file with all our elements, will share with Meli so she can start some UX work next sprint.
