### ISSUE TITLE
[UI] Questionnaire List 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13147]
# Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
[Feature - Questionnaires List ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## User Story/ies

* Use Case: Veterans need the ability to manage their questionnaire list on va.gov in addition to receiving a notification to complete the form.

* Description - Forms List - Completed forms page to show the form that was completed and others that have not been completed or in progress
## Tasks
- [x] See Questionnaire Manager feature outline for fields and valuation
- [X] Create mockups of [Questionnaire List](https://zpl.io/VOOek8j) *Viewable within the Questionnaire List section of the linked Zeplin file.

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities 
- [x] Schedule [accessibility review](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14385)
- [x] Engage content for a review (Peggy Gannon)

**Comment by kristenmcconnell** [comment]
@abuckley3385 - The wireframes are still a work in-progress with multiple variations depicting one requirement, but I came up with a few questions that I thought we should/could collaborate on now. All of my questions are shown as comments in the Zeplin file: https://zpl.io/VOOek8j. 

I also added comments that explain what the page is displaying and how the pages differ from the other pages. So, if you have any general feedback on some of the wireframes that would be great too. These haven't been reviewed by anyoner yet. I've been gathering patterns from across the site/different teams and ideating. I just touched base with the caregiver team on their print designs (I'll work on that next), so that is missing from the current wireframe iteration.

**Comment by kristenmcconnell** [comment]
Note: The the debt letter design proposal was an example reviewed when creating this design (https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263526/simulate/sitemap?mode=i).

**Comment by kristenmcconnell** [comment]
Draft print wireframes added to Zeplin.

**Comment by kristenmcconnell** [comment]
@peggygannon - Can you review the content on the following [wireframes](https://zpl.io/VOOek8j)? Only look at the Questionnaire List section. I think that I gave you the correct access to the Zeplin to make comments. Let me know if you have trouble. In particular, I would love feedback on the lead text under the page title. This is the Questionnaire List feature, where a Veteran can view/complete/print all of their healthcare questionnaires.

**Comment by kristenmcconnell** [comment]
Sent reviews to Jennifer Strickland and Peggy Gannon. I will incorporate their feedback into [#14312](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14312). Closing out this story.

**Comment by kristenmcconnell** [comment]
@peggygannon Closing out this story. I'll ping you in the new story that will continue this work.
