### ISSUE TITLE
[FE] Questionnaire List UI updates

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13149]
## User Story
 As a Veteran, if my appt. has been canceled or moved I need to know if I am still needing to complete a questionnaire for the visit and when its due. 

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
[Feature - Questionnaires List ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)
- [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/600080c76d298d2157a8c5dc)

## Description

Display the status of the questionnaire display and/or show the veteran the information provided has been saved for their reference but not being viewed by the care team

## Tasks
- [x] Update Card UI layout, content, and labels changed/moved to match Mock up
- [x] Appt. Status Label
- [x] H2 -title updated
- [x] Fix the empty message on the to-do section. 

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
@kristenmcconnell , Here are the screenshots with update. Let me know if I missed anything.

![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-to-do-2021-02-02-14_05_55](https://user-images.githubusercontent.com/1793923/106649731-fb755000-655f-11eb-85b7-ef8ae8de69b3.png)
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-completed-2021-02-02-14_06_05](https://user-images.githubusercontent.com/1793923/106649736-fca67d00-655f-11eb-87a7-450673945070.png)
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-completed-2021-02-02-14_06_15](https://user-images.githubusercontent.com/1793923/106649746-ff08d700-655f-11eb-8891-ba8ca011987a.png)
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-to-do-2021-02-02-14_06_21](https://user-images.githubusercontent.com/1793923/106649755-0334f480-6560-11eb-8842-199f1b928b3a.png)

**Comment by kristenmcconnell** [comment]
Here are a few items that I noticed...

To-do tab
1. The in-progress status (label component) needs to be hyphenated.
2. The text within the canceled card isn't correct. The part where is says "for your canceled of rescheduled appointment at..." It should be "canceled or rescheduled" not "canceled of rescheduled." Some of the text repeats.

Completed tab
1. The text within the canceled card isn't correct. The part where is says "for your canceled of rescheduled appointment at..." It should be "canceled or rescheduled" not "canceled of rescheduled." 

Questions
1. What's the breakpoint that VAOS has their buttons go full-width? I'm looking at the "tablet" version and the buttons seem huge and the text so small. If it copies VAOS, then keep it. I know that we talked about that last time, but double-checking.

**Comment by mdewey** [comment]
For your question, I know we are mirroring what VAOS does. We chatted about it at some point and are using their breakpoints. I can't find the ticket, but I know we did it that way.

**Comment by mdewey** [comment]
Also good catch on the typos!

**Comment by mdewey** [comment]
This is in staging. @kristenmcconnell  and @abuckley3385 can you verify?

**Comment by kristenmcconnell** [comment]
The cards look great. However, what happened to the Need Help? section? I logged in as user 34 (my favorite).

<img width="1120" alt="Screen Shot 2021-02-09 at 11 53 34 AM" src="https://user-images.githubusercontent.com/66287082/107398578-c328c100-6acd-11eb-84fe-116b21dcfba5.png">
<img width="320" alt="Screen Shot 2021-02-09 at 11 53 16 AM" src="https://user-images.githubusercontent.com/66287082/107398584-c4f28480-6acd-11eb-99bf-1f528f5a6714.png">

**Comment by mdewey** [comment]
Fixes in PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15989

**Comment by abuckley3385** [comment]
this looks really good and clean!

**Comment by kristenmcconnell** [comment]
I see the Need Help section again. Looks good.
