### ISSUE TITLE
[FE] Download PDF 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13146]
## User Story

As a veteran, I should be able to print a PDF of my answers so I can have them for my own records

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Hook up the printing button to open the pdf in a new window. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Load PDF from API 
- [x] Open PDF in new window
- [x] Create user tests
- [x] Create e2e tests
- [ ] remove mock after validation 

## Acceptance Criteria

> when is the ticket done

- [ ] Work from Questionnaire List
- [ ] works form confirm page
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

_[Referenced design ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19347)._

**Comment by abuckley3385** [comment]
need to determine where saving and how before we can point story

**Comment by kristenmcconnell** [comment]
@mdewey Here is the caregiver example of what they are doing when submitting their application takes a long time. We should follow this pattern for when a user clicks "View and print answers" and it take a little bit for the PDF of their completed questionnaire to be created.

![Screen Shot 2021-04-15 at 2.12.30 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/f4825d0b-7335-428f-b7a8-6523fdeecfd9)

Please add our loading indicator above the button similar to caregivers. @DanielleThierryUSDSVA What are your thoughts on the wording underneath our loading indicator?

I was thinking...
"We're creating a PDF of your completed questionnaire. Please don't refresh your browser."

Our button would utilize the disabled styling, but our text should read "Downloading..." The D should be capitalized. @DanielleThierryUSDSVA Unless you think that we should use another word. We will be opening the PDF within another tab.

I think there is animation on the ellipsis within the button, but I'm not 100% sure. Follow what caregivers does.

@mdewey I'm assuming a browser refresh would mess up this process, but just wanted to confirm. 

I don't think we provide an estimated time in the loading indicator wording like caregivers. If we find load time are really high, then we can change the wording.

Mark  - let me know if you have any questions.

**Comment by mdewey** [comment]
Looks good to me, When @DanielleThierryUSDSVA shares some knowledge I will get started.

**Comment by DanielleThierryUSDSVA** [comment]
Sorry, @kristenmcconnell. Read through this again and did have a thought:

I think we should align the button language and the explanatory language. So:

[button} Downloading PDF

[explanation] We're downloading a PDF of your completed questionnaire. Please don't refresh your browser.

OR

[button} Creating PDF

[explanation] We're creating a PDF of your completed questionnaire. Please don't refresh your browser.

Also, do we want to let them know the PDF will open in a new tab? If yes, we could add:

When your PDF is ready, it will open in a new browser tab.

**Comment by kristenmcconnell** [comment]
I like the "Creating PDF..." wording that Danielle proposed, since our button says "View and print questions" and a user will probably have to take another step to actually download the file. Let's add this wording too: "When your PDF is ready, it will open in a new browser tab."

@mdewey I think that should be everything that you need then. Let me know if it isn't.

@DanielleThierryUSDSVA Just so you are aware, I think this is something that could use more documentation in the design system. I created the following [Design Council ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/432), because I found three different implementation solutions to solve something similar.

**Comment by mdewey** [comment]
Closing this ticket, any more changes will be new tickets

- Linking #23459, for PDF down message update
