### ISSUE TITLE
[FE] Review Page

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13159]
# Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
[Feature - Questionnaires List ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## Wireframes
[Overall Zeplin](https://zpl.io/VOOek8j)
[Collapsed view](https://zpl.io/bPkw18y)
[Expanded view](https://zpl.io/VkjgW3M)
[Expanded and editing view](https://zpl.io/25WdDR3)

## User Story/ies

* **Use Case:** Display Review page to confirm the information the veteran has provided in the questionnaire before completing the form to sent to their care team.  Also allow for edit any areas that need updates.  
---

## Tasks
- [x] See Questionnaire Manager outline for fields and valuation
- [x] Follow detailed mockups and callouts of feature outline [link] 
- [x] Review with Accessibility and feedback incorporated or documented for team review 
- [x] Engineering -what is process for pushing custom code up to platform to own.
- [x] Reverting to standard layout. 

## Acceptance Criteria
- [ ] UI review meeting with product for feature capabilities 
- [ ] UI review meeting and callouts with designer for layout and callouts
- [ ] published to staging environment, behind a feature flag
- [ ] Access-ability review complete

**Comment by mdewey** [comment]
@abuckley3385  and @kristenmcconnell 

RISK: The review page section for the list of question customization is limiting without changes to the platform code. I am not opposed to doing but might slow down a little, and could be a separate ticket/PR.

**Comment by mdewey** [comment]
RISK: The question title for the list of questions (`FILL ME IN`) is not going to display on the page unless we modify Platform. As Always, I am not opposed to doing but might slow down a little, and could be a separate ticket/PR.

**Comment by kristenmcconnell** [comment]
@mdewey We could move the question (Do you have any other additional questions...), so it displays multiple times though? See the attached image that I threw together (or it could replace the "New Question" wording if what I drew isn't correct?). I think multiple times is better than not showing at all.  I think this repeat wording pattern is what is actually intended for this component from the other examples that I have seen.

![Screen Shot 2020-09-11 at 3.13.29 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ac146cf5-c057-4278-aa3d-538268fa87f0)

We are spending a lot of time on this one component. I'm wondering if it would be better to just make it a text area instead of this list loop.

@abuckley3385  - Thought you should way in, since the LOE for these two solutions list loop versus text area is very different. I believe that either list loop or text area would satisfy our original intention for this question, which is to better prepare for a VA medical appointment.

**Comment by abuckley3385** [comment]
Quick question first- this ticket isn't in our current sprint- is there a reason we working on it - Do we need to pull it in?

**Comment by abuckley3385** [comment]
Second if we put it in a big text box it will just all run together and I'd like to be able to have a defined list for the clinician to view instead of a blurb of text that we "hope" the veteran formats in a readable way.  We are on day 3 of the sprint I don't think we are spending too much time on this so far.

**Comment by kristenmcconnell** [comment]
Totally makes sense @abuckley3385. I just wanted to mention the other option.

**Comment by mdewey** [comment]
Reach out to Trevor RE:title not being there for the "this visit" section

**Comment by mdewey** [comment]
@abuckley3385  You added Accessibility review for the ticket acceptance criteria, Can you elorate on that? Is that using automated tools or actually meeting with the Accessibility team?

**Comment by abuckley3385** [comment]
Meeting with Access-ability before you start coding as Jennifer wants a checkpoint to review the approach and provide feedback

**Comment by mdewey** [comment]
@kristenmcconnell / @abuckley3385  

Questions about the demographics on the review page. For the address/phone information, How do you want the labels to look like? Should we follow the labels on the demographics page? For example, on the [demographics page](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f515f029a6f787e61606880) `Mailing Address` is called out, but on the [review page](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f40072098ca0432d34e0691), its called `Street Address`

Do you want to keep the naming consistent? or use what is in the mocks ups?

**Comment by mdewey** [comment]
Having some odd accessibility issues with the array list components. Need to look at it with fresh eyes.

**Comment by kristenmcconnell** [comment]
@mdewey If it is easy to make it consistent with the demographics page (Mailing Address), then let's do that. Consistency will always win in my book. Mock-ups were based on apparently incorrect forms library knowledge. Therefore, thank you for asking.

**Comment by mdewey** [comment]
Blocked until accessibility gets back to me. but other than that, ready for PR

**Comment by mdewey** [comment]
The accessibility team got back to me, and said the best course forward is to create a custom component. [link to thread](https://dsva.slack.com/archives/C0136TS768M/p1601660302045200).

@abuckley3385  @kristenmcconnell Since creating a custom component for this feature is outside the scope of this ticket,  I am going to suggest to create a ticket just for that.  This new ticket would be a custom component just for the review page. And it will handle editing as well as displaying the information.  

Thoughts?

**Comment by mdewey** [comment]
Just to round out the ticket and to answer: `what is the process for pushing custom code up for platform to own.`

The process is to create a separate branch just for that feature with tests, and send a PR and go through the approval process.

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mdewey I'm torn, because that would still be creating a custom component for a design that I believe is not the best design. Can we make this "out-of-the-box" work?

Can we just add the header "Ranked questions for your provider" (as shown in the below snapshot from the wireframes)?
![Screen Shot 2020-10-05 at 1.07.51 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ee38f252-def0-41f5-8c6f-d78983a77ef4)

We can leave the "Question" wording as shown in the below screenshot from staging. With that one change, we wouldn't need the extra ticket then, correct? 
![Screen Shot 2020-10-05 at 1.07.45 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/458b05d0-78ab-44c9-913f-48b05eefe462)

**Comment by abuckley3385** [comment]
Im not clear where the feedback from Access-ability is located the link to the thread is not showing me much.  what is the issue?

**Comment by mdewey** [comment]
@abuckley3385  The issue(s) are: 
1. that the "out of the box" solution for the ranked questions, does not match the mockups; the core problem being focused around the position and weight of the headers. 
2. We were told that the Accessibility team had a technical workaround for problem #1, but that workaround turned out to be unknown (that was in the thread) 
3. To address problem #1, we were again pointed back at making custom components that follow the styling of the review page. 

@kristenmcconnell in order to do add the header, it would be a (small) platform change, which I am not opposed to doing but it won't get in this sprint.

**Comment by kristenmcconnell** [comment]
I'm good with whatever is easier. Adding the header or the custom component.

**Comment by mdewey** [comment]
I will create the ticket for the platform update. I think that would be easier.

**Comment by mdewey** [comment]
Created a ticket for the review title: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14454

**Comment by mdewey** [comment]
![Screen Shot 2020-10-07 at 11 27 26 AM](https://user-images.githubusercontent.com/1793923/95352688-779ca700-0890-11eb-8856-6e3ca51bba86.png)

Latest in staging!

**Comment by kristenmcconnell** [comment]
Some questions and comments...

1. In the above image from staging, the first address doesn't have an associated state or zip code displayed. What if the two addresses are in different zip codes?

2. When I currently click the Veteran Information section in staging to expand it open, this is what I see. The entire main content area disappears. I was logged in around 1:30 pm today and used user 34.
![Screen Shot 2020-10-08 at 1.25.11 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/109e6fab-008b-4a9b-acac-8d8c4f42bc04)

3. Lastly, some notes and questions about spacing are provided below. I wrote them on top of a screenshot from staging.
![Spacing.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/31413328-296c-4855-bb03-d711a1be2b6c)

**Comment by kristenmcconnell** [comment]
1. I also just ran into the below error state when I was clicking around through staging. Can we change the word "application" to "questionnaire"? 

2. I just realized the section title is "Step 3 of 3: Review Application." In the wireframes, it was just "Review." Can we easily make that change? "Review Questionnaire" is also acceptable.

![Screen Shot 2020-10-08 at 2.04.12 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/93dcc6f4-35f3-4976-ae28-84c2d29400de)

**Comment by mdewey** [comment]
To answer your questions @kristenmcconnell : 

`In the above image from staging, the first address doesn't have an associated state or zip code displayed. What if the two addresses are in different zip codes?` 
This is a problem with the data. That specific user (number 22) is missing the zip code and state from their address. That leads to the question, What are the minimum fields to show, even if we don't have data for those fields? 

`When I currently click the Veteran Information section in staging to expand it open, this is what I see. The entire main content area disappears. I was logged in around 1:30 pm today and used user 34.`

I can not reproduce this error, can you verify its still an issue, and if it is, let's hop on a call :-) 

`Lastly, some notes and questions about spacing are provided below. I wrote them on top of a screenshot from staging.`

I believe this is out of my control, I _could_ add some spacing to the top of the footer but that would the spacing on all pages of the form. 

`I also just ran into the below error state when I was clicking around through staging. Can we change the word "application" to "questionnaire"?`

Maybe. I will look into that. 

`I just realized the section title is "Step 3 of 3: Review Application." In the wireframes, it was just "Review." Can we easily make that change? "Review Questionnaire" is also acceptable.`

Maybe. I will look into that.

**Comment by kristenmcconnell** [comment]
About "What are the minimum fields to show, even if we don't have data for those fields?," I will ask around to the other designers.

I was also unable to reproduce the expanding problem that I ran into before. I logged in as user 34 and it was perfect.

About the spacing at the bottom of the page (near the footer), take a look at "Apply for education benefits" and file a disability claim. Their spacing is more in a line with what I was thinking.

Image from disability workflow
![Screen Shot 2020-10-13 at 9.57.42 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/898729b8-1049-482a-ad8c-9347a16bd922)

**Comment by mdewey** [comment]
Addressed the following feedback in PR
- Added the extra spacing 
- Changed wording from `application` to `questionnaire` in the config. Any place where it still says `application` is going to be a platform change. 

Will move to a separate ticket: 
- What to show/hide
- If we see `application` anywhere else

**Comment by kristenmcconnell** [comment]
Spacing still looks the same to me, but overall it isn't bad. Great about changing application to questionnaire. Though we will have to look through Peggy's suggestions after this usability test, because she was recommending "Questions" in some places. So I would wait for any further changes until after this usability round.

 ![Screen Shot 2020-10-15 at 2.36.57 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/1ff92c44-22e5-4dfe-bc3c-96f7f75f0083)

**Comment by mdewey** [comment]
It doesn't look like the changes are deployed yet. I will let you know (@kristenmcconnell  and @abuckley3385 ) when they are live.

**Comment by mdewey** [comment]
@abuckley3385  and @kristenmcconnell  The latest updates are [in staging.](https://staging.va.gov/healthcare/questionnaire)

**Comment by kristenmcconnell** [comment]
@mdewey The spacing looks much better. Mobile looks good. The scope of this story is good by me.

**Comment by abuckley3385** [comment]
When editing our questions on the review page the update button doesn't seem right? one is update and one is update page.  Is it just wording inconsistency? 
![image](https://user-images.githubusercontent.com/65729813/96306322-14fc8700-0fc5-11eb-84e2-51d23b7e0214.png)

**Comment by abuckley3385** [comment]
the focus is not set correctly on the questions input button when selecting Add Another Question - it is on the button and should be in the text box to start typing.  this is the same when in the form as on the review when editing
![image](https://user-images.githubusercontent.com/65729813/96306477-5e4cd680-0fc5-11eb-9720-0402a98f85a6.png)

**Comment by abuckley3385** [comment]
Does our Submit Questionnaire button have to wrap...looks like we have other buttons that grow horizontally with the text. 
![image](https://user-images.githubusercontent.com/65729813/96306550-7ae90e80-0fc5-11eb-9b31-50b29f157985.png)

**Comment by kristenmcconnell** [comment]
@abuckley3385 I looked into other examples on va.gov, because I thought the "Submit Questionnaire" button should grow horizontally as well. This seems to be standard. I saw it in a few other places (a disability and education benefits form).

**Comment by abuckley3385** [comment]
can we double check what other forms are doing with these links. I don't like how this one navigates away from our form with no warning to the chat in same browser tab...which could make the veteran loose their work if they don't hit submit or save for later.  I would think this should ask for safe for later if they want to continue away... also goes same for the text as its a popup but still leaving the page. 
![image](https://user-images.githubusercontent.com/65729813/96307039-8a1c8c00-0fc6-11eb-80e2-7b5ef12f8acd.png)

**Comment by abuckley3385** [comment]
@kristenmcconnell  but the Add Another Question is the same character spacing ie, 20 characters with spaces and it doens't wrap. this should be consistent and button wrapping is always weird,

**Comment by kristenmcconnell** [comment]
@abuckley3385 I agree. However, Peggy recommended changing it to "Submit questions" and so far no one has complained in usability testing. I don't think that it will wrap like that with "questions." How should we address that, since testing isn't complete?

**Comment by kristenmcconnell** [comment]
@abuckley3385 About the confidential chat link, here are some examples that I found...
1. VAOS doesn't have the confidential chat option listed in their scheduling form. They do have a link to "Find your nearest VA medical center," which opens in a new browser tab. They also don't list the text option. ![Screen Shot 2020-10-16 at 5.26.07 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/7e7ac158-a566-43bc-ad57-d8dd5cf64836)

2. This example isn't in a form, but https://staging.va.gov/health-care/secure-messaging/ functions the same way that our questionnaire currently does.

**Comment by mdewey** [comment]
Thanks, @abuckley3385 / @kristenmcconnell  I see 4 points of feedback here.

1. `update` vs `update page` - As Kristen mentioned, the `update` is updating just the item in the loop, while `update page` is updating the entire page (the ranked questions, the reason for visit, and life events question).
2. focus on list loop - solved by other teams by [creating custom component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/components/ArrayField.jsx#L23) This is covered by tickets [13416](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13416) and [14175](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14175)
3. wrapping button - the cause is `questionnaire` being too long and the container the button is in too small. There is no easy way to change container sizes.  I would recommend changing it to only be `questions`. This can be updated with other feedback if any from the usability test. 
4. links to other pages - Whatever you all decide, lets put that on a [new ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14988)

I do not see any action items for this ticket. If I missed something let me know :-)

**Comment by mdewey** [comment]
If no more actions items, I vote to close this issue.
