### ISSUE TITLE
Content for This Visit Questions 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13154]
---
## Tasks
- [x] Revise the verbiage for the questions and review with content person
- [x] Update wireframes with any updated verbiage

## Acceptance Criteria
- [x] UI review meetings
- [x] [Published to Zeplin](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/dashboard)

**Comment by kristenmcconnell** [comment]
@peggygannon We would like your help in reviewing the main questions within our "Reason for Visit clipboard." These questions will help both the Veteran and clinician better prepare for an upcoming appointment. The three main questions for review are highlighted by stars within the attached image. 

In particular, we would like the second question to be better balanced, so Veterans will enter information about other health concerns and life events affecting their health. For the third question, do you have any wording suggestions that would combine ranking and enter questions into one sentence?

![Form - Reason for visit - Reason and concerns - Logged in - Desktop .jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/f1ab159b-0827-4e65-b620-86a88d70a7e6)

**Comment by kristenmcconnell** [comment]
@peggygannon After some review, we think the three question will look more like this when implemented.

![Form - Reason for visit - Reason and concerns - Logged in - Desktop .jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/7f6f606a-8359-4984-ba09-65145a2666ec)

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell See my content feedback and a few questions below: 

2nd question
*re: we would like the second question to be better balanced, so Veterans will enter information about other health concerns and life events affecting their health.*

Can you explain what you mean by better balanced?  are you wanting to removing the content in the parenthentical? Here's my recommendation, but I can amend based on your answer. 

Are there any other health concerns  or changes in your life that are affecting you or your health? 

-----

3rd questions
*re: For the third question, do you have any wording suggestions that would combine ranking and enter questions into one sentence?*
Per VA.gov style , we  keep sentence short and break them down into simple sentences so it easier for users to understand. 

Here's my recommendation for this sentence:

Do you have other questions you want to ask your provider? Please list them in order of importance.


----

Also, can you tell me why certain words are bolded? per our style, we try to keep bolding to a minimum as it can be harder to read than normal text, especially for accessibility reasons.

**Comment by kristenmcconnell** [comment]
About the 2nd question...
We would like to include some examples of life events. We believe it helps with understanding what types of information we are looking for. We just don't want the examples to overpower the sentence, so we don't get other health concerns feedback as well. I hope that helps clarify the help we are looking for.

Your third question wording sounds great. I will also remove the bold formatting to help with accessibility.

Thank you.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell Ok, thanks for the additional clarification. Here's an update. Let me know what you think: 

Are there any other concerns or changes in your life that are affecting you or your health? (For example, a marriage, divorce, new baby, or change in your job)

**Comment by abuckley3385** [comment]
updated description with link to Zeplin fiile for source of truth designs

**Comment by kristenmcconnell** [comment]
@peggygannon We also want them to mention important health diagnoses and not just life events. What about this?

Are there any other concerns or changes in your life that are affecting you or your health? (For example, a marriage, divorce, new baby, change in your job, or other medical conditions)

**Comment by peggygannon** [comment]
hi, @kristenmcconnell Yes, this works! thank you. That update looks good.
