### ISSUE TITLE
[Spike] Read Questionnaire data from the PGD sandbox

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#13156]
## User Story
**In order** to use the upcoming appointment questionnaires feature on the va.gov website
**As a** Veteran
**I want**  the website engineers to be able to test and verify the appointment questionnaires feature thoroughly in a sandbox environment so that the component is defect-free when I start using it on the va.gov website

## Related Documents

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/connecting%20to%20PGD%20sandbox.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/fhir%20client%20with%20pgd%20and%20cerner.md
- https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12778

## Description
Document the requirements/steps needed to make HTTP calls to the PGD sandbox so that we can access the questionnaire and questionnaire response data. Information and knowledge gained through these documents will be used to build the parts that are necessary for the production-ready feature.

## Questions to Answer
- [x] How can we get mock questionnaires and questionnaire responses data into the PDG sandbox?
- [x] Do we have a Ruby FHIR client to use with the Health Quest module?
- [x] What authentication mechanism must an HTTP client use in order to establish a session with the PGD sandbox?
- [x] What endpoints do the PGD sandbox provide to access questionnaires data?
- [x] What endpoints do the PGD sandbox provide to access questionnaire responses data?
- [x] What user accounts do we need to access the PGD sandbox?
- [x] How is this data accessed in Staging?

## Acceptance Criteria
- [x] Code written for this spike must be testable from the instructions provided in the Related Documents section.
- [x] Health Quest must implement the JSON Web Tokens(JWT) internet standard to safely read data from the PDG sandbox.
- [x] Must be able to read Questionnaire and QuestionnaireResponse data from the PGD sandbox using an interface(Command line).

**Comment by massrb** [comment]
Using a fhir client or any means possible, once the access to the sandbox is obtained, we need to be able to write and read questionnaire and questionnaire response records

**Comment by abuckley3385** [comment]
- [X] @Stephen to shared how to get data into pGD.  Sent zip file to Mark and Laurence
- [ ] Add JWT to this ticket for acceptance criteria
- [ ] Stephen is going to own this and take the lead on investigating how the docs in the zip file would allow us to populate the sandbox.  @massrb  and @mdewey  please review zip file as well to get up to speed on the investigation.

**Comment by abuckley3385** [comment]
@massrb last week in backlog and this Tuesday in sprint planning we discussed this story not have tasks/acceptance nor estimate.  I stressed the importance of this so we are accurately planning the workload for the sprint and to know what it means to mark this ticket as done.  If there any reason this can't be completed, please let me know and provide an update by the EOD today. FYI

**Comment by massrb** [comment]
Setting this to blocked for now. The latest message from T. Skinner on https://dsva.slack.com/archives/CBU0KDSB1/p1598969124044100 was:

>> I'm not sure if someone is going to be able to grab it this sprint. I can post it. It is at the top of the list though

**Comment by massrb** [comment]
We where able to connect to the PGD sandbox by establishing a user session

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/connecting%20to%20PGD%20sandbox.md

**Comment by massrb** [comment]
I was able to connect to the PGD sandbox with the ruby fhir client and also the cerner sandbox. The PGD sandbox still has no data however. I have described how I did that here

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/fhir%20client%20with%20pgd%20and%20cerner.md

**Comment by massrb** [comment]
Chris Johnson posted in the clipboard channel that he was working on getting the appropriate teams to generate the keys. This should also help get #12404 moving

**Comment by massrb** [comment]
This ticket is a duplicate but may have other related information in the comments
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12778

**Comment by massrb** [comment]
Stephen had mentioned previously that there was one set of keys that will cover PGD/appointments. He recently gave a technical answer with regards to keys, though it appears that is in regards to the keys for PGD. 

 The current status is that we are able to connect to the MAP PGD sandbox with a user session because Stephen created temporary keys. Stephen is still working on getting data into the sandbox. Other than the PGD sandbox user session, there is no other access available currently 

Question:
>> its our understanding that the above mentioned temporary keys have been generated for MAP- PGD but we do not have temp keys for MAP-Vista Appt. service - can you confirm this is correct and if so are we able to create temp keys the same as PGD or do we need to wait for official ones? 

Answer
>> The keys are for all services in MAP.  We use the private key to sign a token that we then pass to MAP User-Services.  User-Services (which has our public key and thus can verify the token we signed with our private key), generates a MAP JWT and returns it to us.    All subsequent calls into MAP (to PGD, Appts, etc) will include that MAP JWT in the x-vamf-jwt header.      So there is no PGD key or ApptSrvc key - just one key for all of our MAP Sandbox.
However, there is not an easy way to setup MAP Sandbox to support the appt services.  Once I have PGD working with test data in MAP Sandbox, I plan to see if i can make this work now, but in the past it was not possible.

**Comment by massrb** [comment]
I have created endpoint in the health quest service to read a questionnaire and a questionnaire response given an id. These are dummy endpoint currently and I can't check the code into the master branch in that state

**Comment by massrb** [comment]
I can not get data from the PGD sandbox using a typical user. The only way to see the data that Stephen put in the sandbox is to use particular users and credentials that he gave me to run from my machine

Update from Stephen:
>> MAP PGD is up and running and I am able to run scripts against it to populate various types of data, and to pull data out.  These scripts use a JWT that is generated on the fly; an Admin scoped JWT is used to POST resources and a Non-Admin scoped JWT is used to GET resources. We were not able to use the JWT returned from the JWT Exchange to GET the resources. I am still investigating what the difference is, but suspect the Non-Admin JWT has more access than a standard JWT like the one were are getting back and thus we will also need to supply Patient ID to the query.     I have shared the simple script to GET data with @Laurence Guild and he is able to run it and see Questionnaire resources.  Currently it has credentials hardcoded so I will not share it here, but will pull those into params next week so anyone can run and see data.

**Comment by massrb** [comment]
This document shows how using the Ruby FHIR Client it is possible to read a questionnaire from the PGD sandbox. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/fhir%20client%20with%20pgd%20and%20cerner.md

Stephen believes that until some forms are filled out regarding the FHIR data we will be using, it may not have the permissions to write to the sandbox as the write attempts have failed.

 Until we can write to the sandbox from the Ruby side, this ticket can't be complete but we can read from the sandbox

**Comment by massrb** [comment]
This ticket is complete for reading records and for connecting with a JWT but writing to the PGD has not been possible because of permissions and problems that Stephen has been researching

**Comment by dillo** [comment]
Splitting this card into two separate tickets:

- Changing the title to `Read FHIR Questionnaire and QuestionnaireResponse records from PGD sandbox` to reflect the split-off responsibility
- TODO::Changing the tasks and acceptance criteria list to match the "Read" only functionality of the ticket.

**Comment by dillo** [comment]
Original task and acceptance criteria for reference.
```
## Tasks
- [x] Verify that JWT in health quest / VAOS can be used for the PGD access
- [ ] Determine an unorthodox way if possible that from a draft PR instance health quest can be leveraged to write Questionaire and questionnaire responses to the PGD

## Acceptance Criteria
- [ ] Be able to write questionnaire/Questionnaire responses to the sandbox and verify that it was written. These records don't need to be meaningful. We are just proving that we can write to the PGD
- [ ] The code to do this can be on a separate code branch
```

I've modified the AC to reflect what the spike is asking for so that a reader of the ticket is not confused as to the nature of the work that was done.

**Comment by dillo** [comment]
Simplifying the title to: `[Spike] Read Questionnaire data from the PGD sandbox` so that anyone can easily understand what the spike is about.
