### ISSUE TITLE
Enable GitHub integration for Sentry

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#13158]
## Issue Description

As an engineer using Sentry to track errors, I can leverage GitHub integration features to track repository changes and link GitHub issues to errors.

---

## Tasks
- [x] Create a GitHub application and transfer to the DSVA organization (requires ticket to be filed [here](https://github.com/department-of-veterans-affairs/github-user-requests))
- [x] Put these credentials into credstash, and [rename from `*.testbed`](https://github.com/department-of-veterans-affairs/devops/blob/43841a9263ded8484718999c08402cb701ab7326/ansible/build/roles/sentry10/templates/config.yml.j2#L79)
- [x] Configure the deployment playbook to inject configuration values into `config.yml.j2` 
- [x] Test build locally with `CONFIG="sentry10-utility" APP="sentry10" OPTIONS="-vv" vagrant up --provision`, `vagrant ssh` confirm config is present
- [ ] Build new AMI with `ansible-playbook -e ref=$REF -e app=sentry10 -e rebuild=true -i inventory build/create.yml`
- [ ] Test deployment in Jenkins

## Acceptance Criteria
- [ ] `sentry10.vfs.va.gov` is running
- [ ] Configuration wizard for GitHub integration works in Sentry UI

---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This came up during a Sentry review meeting today. What's the latest status on this integration @alexpappasoddball ?

**Comment by alexpappasoddball** [comment]
@mmiddaugh From our side, we are waiting for the Ops team to complete the minor upgrade (which they have already started and are actively working on).  From there, Backend tools will finish the configuration to allow for GitHub integration and Slack Integration.  Don't have an exact time frame for you yet, but it shouldn't be long now!

**Comment by mpelzsherman** [comment]
Any updates on this?

**Comment by jeff2d2** [comment]
Blocked until #15175 is complete

**Comment by jeff2d2** [comment]
According to [this Slack thread](https://dsva.slack.com/archives/CE4304QPK/p1624475390220900?thread_ts=1624465768.214600&cid=CE4304QPK), GitHub integrations were installed during the upgrade to Sentry 20, and so this work should be complete.

@mleclerc00 can you double confirm for us here please?

**Comment by mleclerc00** [comment]
The github integration has always been installed as far as I know even prior to the update to 20.x/migration to kubernetes.  The oauth and github integration are both managed through the same github-app "vsp-sentry10-github"

**Comment by mpelzsherman** [comment]
Getting an error when I try to link a Sentry issue to GitHub:

![Screen Shot 2021-06-28 at 4 45 39 PM](https://user-images.githubusercontent.com/80267/123701803-528e0100-d830-11eb-8e6d-60905cac1cbc.png)


![Common__Exceptions__BackendServiceException__Common__Exceptions__BackendServiceException_-_vsp_-_platform-api](https://user-images.githubusercontent.com/80267/123701686-2a9e9d80-d830-11eb-9372-6d141c5e5da6.png)

**Comment by mpelzsherman** [comment]
BTW, loading data takes a lot longer now than it used to...

**Comment by mleclerc00** [comment]
I will look into the github integration.  This predates me and I am not a owner on the app so I have no insight into any of the configurations.  When doing the update/migration I merely copy and pasted the configurations that were already there. Though it seems that this never worked?  I have reached out to github admins to see if I can get this straightened away. As for the performance issues.  We are aware and will be trying to tweak the deployment in order to improve said latency/errors.

**Comment by mleclerc00** [comment]
I was able to get one of the two integration installs to work.  Not quite sure why there are 2 but I am hesitant to delete the other one.  As of right now that particular app only has vision into 3 of the repositories.  If that needs to change we will need to speak with a github admin to do so.  I haven't actually tried to link a issue but it seems like the rest of the process should work.

![image](https://user-images.githubusercontent.com/76792875/123710300-5bc4a100-d823-11eb-9a76-268c644367ff.png)

![image](https://user-images.githubusercontent.com/76792875/123709834-8e21ce80-d822-11eb-8697-f8ebfcf6231c.png)
