### ISSUE TITLE
Configure release tagging for the Sentry 10 BRD

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#13161]
## Issue Description

As an engineer in order to deploy and tag Sentry 10, releases should be tagged and configured as appropriate for the VSP BRD cycle.
---

## Tasks
- [ ] Update the Ansible playbooks to tag releases for Sentry 10 builds

## Acceptance Criteria
- [ ] Sentry 10 builds and releasees are appropriately tagged

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
