### ISSUE TITLE
merge health quest service to main branch

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#13160]
## Tasks
- [x] Copy code from VAOS and get the tests to all pass at 90% rate or better
- [x] break the code up into smaller PRs as required by VSP and get those into the master branch

## Acceptance Criteria
- [x] The code for appointment endpoints and supporting code is pushed to the master branch
- [x] All Spec tests for the health quest service pass

**Comment by massrb** [comment]
The code has to be broken up into smaller pull requests because it's 2054 lines and a pull request can only be 1000 lines

**Comment by massrb** [comment]
I created a pull request with 852 lines but the backend review group wants it broken down further. This could mean I have to write more tests

**Comment by abuckley3385** [comment]
@massrb last week in backlog and this Tuesday in sprint planning we discussed this story not have tasks/acceptance nor estimate. I stressed the importance of this so we are accurately planning the workload for the sprint and to know what it means to mark this ticket as done. If there any reason this can't be completed, please let me know and provide an update by the EOD today.

**Comment by massrb** [comment]
Currently the second pull request has built and will be awaiting approval from VSP

**Comment by massrb** [comment]
The third and last PR is waiting for approval for merging to the main branch. These PRs constitute the appointment endpoints copied from VAOS

**Comment by massrb** [comment]
This has been completed and pushed to the main branch. The v1 appointments where not brought over from VAOS but we do't need those.

**Comment by massrb** [comment]
This ticket should be able to be closed but it is in validate for the time being
