### ISSUE TITLE
Unit Test Schema for CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#13172]
# Background
Now that we have built the schema for the chapter 36 form we need to unit it. Unit testing these schemas is a standard practice in VA.gov as it makes sure the schemas function as they should

## Tasks
- [ ] Add a schema test file
- [ ] Import common tests
- [ ] Test chapter 36 schema
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The schema for the chapter 36 form has been unit tested
- [ ] a PR has been submitted for review
