### ISSUE TITLE
Edit address before letter download

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13184]
# User Story
As a user, I can confirm or edit my address before downloading any letter.

# Tasks
- [ ] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific designs as needed

# Prototype
[Screen link](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636878)

**Comment by srmyers17** [comment]
Q: Difference between viewing the letter vs. downloading it?
A: When it is generated, a PDF is created, you can't view it inline in browser

Decision: Allow users to view letter (via display PDF) before they having to download it. 
Next: Talk to DF about this and see what their recommendation is. 
Note: If this is async, we may need to alert user that it will take time to request and view
