### ISSUE TITLE
Plain language fix for "historic" and "historical" for past rates in disability/DIC/pension

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#13189]
## Issue Description
To address the lack of plain language when referring to the past rates tables, eliminate the words "historic" and "historical." Instead use "past."

---
## Tasks
- [x] Update URLs in drupal: /past-rates-2019 and /past-rates-2018
- [x] Notify Mikki when URLs are updated
- [x] Adjust language on all disability/DIC/pension pages with either "historic" or "historical" (and make sure there aren't other places other than what's listed below in this task list)
- [x] Fix H1s for 2019 and 2018: "Past rates: 2019 Veterans disability compensation rates" and "Past rates: 2018..."
- [x] Remove "historical" from the intro paragraph.
- [x] Fix left nav: "Past rates: 2019" and "Past rates: 2018"
- [x] Fix breadcrumb: "Past rates: 2019"
- [x] Fix subhead that precedes the 3 links at the bottom of the 2020 page: "Past rates"

![Screen Shot 2020-09-03 at 7.40.04 AM.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/58079ea3-7349-44bf-8694-f54f9c7d3fad)

![Screen Shot 2020-09-03 at 7.40.16 AM.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/9acdb915-0723-475f-953d-e56c2a9e0371)

![Screen Shot 2020-09-03 at 7.39.40 AM.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/db38947d-32f6-42cb-ae34-c4b9c907ea2f)

![Screen Shot 2020-09-03 at 7.39.24 AM.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/bd8216b7-3c2a-401a-a0b8-60fbb172a502)

## Acceptance Criteria
- [x] No more instances of "historic" or "historical"
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht @bethpotts I've changed the H1 header to past rates and any references to historical to past in the page introduction. I've also changed the sub-header that precedes the 3 links at the bottom of the 2020 page. These pages are all in draft mode.

**Birth defect**
2020: http://preview-prod.vfs.va.gov/preview?nodeId=993
2019: http://preview-prod.vfs.va.gov/preview?nodeId=5062
2018: http://preview-prod.vfs.va.gov/preview?nodeId=6189

**DIC rates for parents** (no mention of "historical" in intro paragraph)
2020: http://preview-prod.vfs.va.gov/preview?nodeId=1013
2019: http://preview-prod.vfs.va.gov/preview?nodeId=6797
2018: http://preview-prod.vfs.va.gov/preview?nodeId=6266

**DIC rates for spouses and dependents** (no mention of "historical" in intro paragraph)
2020: http://preview-prod.vfs.va.gov/preview?nodeId=1012
2019: http://preview-prod.vfs.va.gov/preview?nodeId=6799
2018: http://preview-prod.vfs.va.gov/preview?nodeId=6203

**Veterans disability compensation rates**
2020: http://preview-prod.vfs.va.gov/preview?nodeId=986
2019: http://preview-prod.vfs.va.gov/preview?nodeId=4714
2018: http://preview-prod.vfs.va.gov/preview?nodeId=6793

**Special monthly compensation**
2020: http://preview-prod.vfs.va.gov/preview?nodeId=991
2019: http://preview-prod.vfs.va.gov/preview?nodeId=4917
2018: http://preview-prod.vfs.va.gov/preview?nodeId=5687

**Special benefits allowances**
2020: http://preview-prod.vfs.va.gov/preview?nodeId=990
2019: http://preview-prod.vfs.va.gov/preview?nodeId=5035
2018: http://preview-prod.vfs.va.gov/preview?nodeId=6190

**Comment by RLHecht** [comment]
These have all been updated and published. Moving to validate and will close after today's deployment. FYSA @bethpottsVADEPO @mnorthuis

**Comment by RLHecht** [comment]
The disability rates pages are all live with the correct language. The Pension and DIC pages are also all updated but just not published. Closing this ticket as the acceptance criteria is complete. Will follow up with publishing of DIC and pension rates pages in other tickets. FYSA @MickinSahni
