### ISSUE TITLE
Instructions for editing personal & contact information

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13181]
# User Story
As a user, I can view instructions for what to do when my Date of bith or Gender are wrong in my VA.gov profile.

# Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Anroid
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

**Comment by bridgethapner** [comment]
This has been implemented with #13120, closing this ticket in favor of #13120.

**Comment by bridgethapner** [comment]
This has been implemented with #13120, closing this ticket in favor of #13120.
