### ISSUE TITLE
[Business Optimization] Input all stakeholder feedback into prod and republish Devshop [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13186]
## Story
_As a CMS engineer, I require System pages to be created, so I can associate an owner and governance to a system.

## Resources
---
## Tasks
- [ ] _update all system pages as detailed in Stakeholder feedback documents for:
- [x] VA Altoona health care
- [ ] VA Butler health care
- [x] VA Erie health care
- [ ] VA Lebanon health care
- [ ] VA Wilkes-Barre health care
- [x] VA Wilmington care
* Update all of the feedback forms with "Actions Taken" and resubmit to stakeholders
- [ ] Republish all system sites in Devshop

## Acceptance Criteria
- [ ] All sites are tested in Devshop
- [ ] All documents have been returned to stakeholders with instructions and update.
