### ISSUE TITLE
Please generate Public/Private Key pairs for Clipboard Questionnaire app integration with MAP 

### ISSUE THREAD

**Issue by stephenBarrs** [department-of-veterans-affairs/va.gov-team#13188]
## Issue Description

The Clipboard Questionnaire app will make calls into the Mobile Application Platform (MAP) environment. Authentication is handled by a `JWT Exchange` service endpoint in MAP, which requires a public/private key exchange. We will need three sets of keys for each environment we will connect to: Sandbox, Staging and Production.

---
From the MAP `user-service JWT Exchange` documentation:

> You must generate RSA 2048- or 4096-bit keypairs to be used in each environment- sandbox, staging, and production. Once that is completed, you must submit all 3 generated public keys and a desired reverse DNS-style issuer ID (e.g. gov.va.system.v1)

@massrb is the backend developer for this product.  As I understand it, the private keys will be stored in `credstash`. Not sure if Operations puts them there or if @massrb would securely receive the private key and add to `credstash`.  

This key exchange is identical to the VAOS key exchange for their MAP integration, if we want to see an example of how this has been previously implemented.  

Here is the PR for the Questionnaire app [External Service Integration Form](https://github.com/department-of-veterans-affairs/devops/pull/7541)

## Tasks
- [ ] Creation of Sandbox keys and delivery of public key to stephen.barrs@va.gov
- [ ] Creation of Staging keys and delivery of public key via encrypted email to lynne.case@va.gov
- [ ] Creation of Production keys and delivery of public key via encrypted email to lynne.case@va.gov

## Acceptance Criteria
- [ ] All public keys have been generated and delivered securely to the relevant contact 
---
## How to configure this issue
- [x] **Labeled with Team** ( `operations`)
- [ ] **Labeled with Practice Area** (`backend`)

**Comment by ricetj** [comment]
@tskinn to add info  on adding a backend

**Comment by jhouse-solvd** [comment]
@stephenBarrs - This is an older ticket, but can you confirm whether or not your team got everything that was needed here?

**Comment by jhouse-solvd** [comment]
I believe this is done. We can re-open if anything else is needed. 

Closing.
