### ISSUE TITLE
Claims and appeals overview screen

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13201]
## User Story
- [x] As a user, I can see all my open and closed Disability Claims and Appeals.
- [x] As a user, if I don't have any active claims, I see a screen with that message.

## Tasks
- [x] High fidelity prototype of screens in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting; Android-specific design as needed

## Prototype
- [Claims and Appeals overview](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432345659)
- [Claims and Appeals overview (closed claims)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432345982)
- [Claims and Appeals overview (user has no active claims)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432463354)

## Titles
**For claims:** 
- Titles should follow this formula: "Claim for [type] updated on [Month X, XXXX]"
- Subtitles should follow this formula: "Submitted Month XX, XXXX"

**For Board Appeals:** 
- Titles should follow this formula: "[Type] appeal updated on [Month XX, XXXX]"
- Subtitles should follow this formula: "Submitted Month XX, XXXX"

**For Higher Level Reviews:**
- Titles should follow this formula: "Higher-level review for [type] updated on [Month XX, XXXX]"
- Subtitles should follow this formula: "Submitted Month XX, XXXX"

**For Supplemental Claims:**
- Titles should follow this formula: "Supplemental claim for [type] updated on [Month XX, XXXX]"
- Subtitles should follow this formula: "Submitted Month XX, XXXX"
