### ISSUE TITLE
Analytics Support - Publish Process for Engaging with VSP Analytics & Insights

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1320]
## High Level User Story
As a VFS member, I need to understand how VSP Analytics & Insights can support me in analytics so that I can know which parts of analytics (GA, Call Center, Surveys, etc.) I need to implement on my products and how VSP can support my efforts.

## Hypothesis/(es)
**If** _we create a robust Rules of Engagement and documentation_ **then** _we expect teams to be self-sufficient in analytics tasks and to work with analytics in a smooth process_.

## Assumptions
- VFS teams understand that the Github Platform folder is the source of truth for working with VSP teams

## Goals
Create rules of engagement documentation so that VFS teams know how to engage with VSP Analytics & Insights and VFS teams can implement analytics within their own processes for increased self-sufficiency and support.

## Details & Notes
This body of work focuses on how VFS teams can _currently_ engage with VSP Analytics & Insights.

### Links
[Current Google Tag Manager/Google Analytics documentation for VFS consumption](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/google-analytics)
[Current Call Center documentation for VFS consumption](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/call-center)

### Product Outline
Data Dictionary TBD
[VSP Analytics & Insights Team Charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-insights-team-charter.md)

### Areas for Discovery
VSP Analytics & Insights needs to determine how to engage VFS teams on Call Center issues, Medallia implementation, KPI tracking, and using the Product Success Tool.

### VSP Objectives
`O5: All customers comply with the Platform's standards.`

### VSP Key Results
- Reduction in non-compliance across VA.gov products for at least 5/10 practice areas.

## KPIs
- Number of requests from VFS teams to clarify Insights processes
- % customers meeting analytics standards
- Customer NPS

**How we will track the KPIs** - Requests tracked on Github, analytics standards tracking is on #1336 , and Customer NPS tbd. Analytics standards TBD.

## Definition of Done
- [ ] VSP Analytics & Insights standards have been determined & published

Process for the following have been updated and shared:
- [x] Engaging with ad hoc reporting requests
- [x] Requesting Google Tag Manager implementation
- [x] Onboarding with Call Centers
- [x] Engaging with Call Center reported bugs
- [ ] Requesting Medallia
- [x] Setting up KPIs
- [ ] Tracking KPIs
- [ ] Requesting Access to the Product Success Tool

**Comment by joanneesteban** [comment]
The remaining Acceptance Criteria for this super epic are rules of engagement for:
- KPI Tracking
- Medallia
- Requesting access to the Product Success Tool

Each of those items are dependent on _current super epics in the Now column for VSP Analytics & Insights_. 

**VSP Analytics & Insight's _current_ products and services have a Rules of Engagement in place for VFS teams.** 

Closing this super epic, as the remaining work outlined can be attached to other super epics or can be redirected to a new super epic down the road.
