### ISSUE TITLE
File request alert

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13204]
## User Story
As a user, if I have file requests from VA, I will see an alert message communicating that on my claim status tab. Tapping that alert will take me to the files tab.

## Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Android
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

## Prototype
[Screen link](https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427924944)

**Comment by bridgethapner** [comment]
Per testing feedback we're bringing the file upload CTA up to the status screen. Closing this in favor of #13202.
