### ISSUE TITLE
Board Appeals: Status

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13207]
## User Story
For any appeal, I can see the following information: 
 
- [x] Date appeal was received
- [x] Date/time appeal was last updated
- [x] Past events for appeal & their dates
- [x] Current status of the appeal
- [x] Text explaining where the Veteran is in the docket line (if data exists in API) 
- [x] Veterans Affairs Benefits and Services phone number
- [x] Link to VA.gov to get more details on the appeal

## Tasks
- [x] Find a staging account with an active appeal 
- [x] Determine data elements for screens in session with Steve
- [ ] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Wireframe
Matches the design of #13244

**Comment by srmyers17** [comment]
Got access to an appeal to view, working data points into mockups.

**Comment by bridgethapner** [comment]
Thanks to Steve's searching + Anna's help, I was able to get screenshots of a user with an active HLR and updated the user story accordingly. Would like to review with Steve next sprint planning before starting the UX/UI work.

**Comment by srmyers17** [comment]
Next step:
- Session with Steve to align on AC before starting design work.

**Comment by bridgethapner** [comment]
**- Decision: show past events, current status, place in the docket line IF that data exists, link out to VA.gov for everything else.** 

- People can add evidence to Board Appeal and SC, but it's not known if that's a feature on VA.gov. Let's not do evidence upload for MVP. 
- Context: steps can happen in rapid succession - e.g. 3 steps in a day. Max 7-8 steps. 
- VA.gov does show the 3 appeal types today if that data exists in Caseflow. 
- Simple UI! No subway map for MVP. Start with a simple list/icon and we can see going forward if we want to/can do something more complex.
