### ISSUE TITLE
View letters and documents

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13200]
## User Story
As a user, for each letter or document, I can see:
- A description of the letter or document
- An alert from VA informing me about changes to how this letter and document can be used, if one exists
- A preview of the letter itself in the app, which I can save to my phone via my phone's share sheet. 

## Tasks
- [x] High fidelity prototype of screens in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific designs as needed

## Prototype
- [View a letter's description and alerts](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636880)
- [View a letter preview](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636881)
