### ISSUE TITLE
Claim status information

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13202]
## User Story

**As a Veteran, I can see the following status information for any active claim:** 
- Date my claim was submitted to VA
- Title of my claim
- Step out of 5 my claim is currently on
- File requests for my claim IF my claim has them
- Title of my current step
- Estimated completion date
- Help content (FAQs)
- Phone number for claims assistance

**I can see the following status information for any closed claim:** 
- Date my claim was submitted to VA
- Title of my claim
- Informational text communicating the claim's closure and the closure date
- Help content (FAQs)
- Phone number for claims assistance

## Tasks
- [x] High fidelity prototype of screens in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting; Android-specific wireframes as needed

## Wireframes
- [Claim status screen (claim on step 3, has file requests)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432345660_Claim_Status-Step_3)
- [Claim status (the claim is closed)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432579848)

**Comment by srmyers17** [comment]
small changes based on what we learned for appeals

**Comment by bridgethapner** [comment]
Simplified this design a bit to maximize the content we have, avoid writing new content, and incorporate some edits suggested in VSP Design Office hours

**Comment by bridgethapner** [comment]
Post-MVP: notifications and personalized homescreen will lead to action items

**Comment by bridgethapner** [comment]
- Will want voice over to speak to claims steps as a list with X items and clarify where user is in the list

**Comment by bridgethapner** [comment]
@lexicalninja @jperk51 Hi guys -- here is the ticket that writes out all the information we'd like to show for Open and Closed claims. I realize this does not call out what fields we want how they are named in the API & there may be duplicate data lingering, but wanted to flag this ticket in case it's helpful in the API design work.
