### ISSUE TITLE
e2e Testing - Add login to e2e testing

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#1321]
## Goals
_What outcome(s) do we want to see?_ 

## Objectives

_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`, `Automation + Instrumentation`, `Support`, `Capacity-building`)

## How to configure issues within this Super Epic:
- [x] **Labeled with Team**:  `tools-improvements`
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Release** `Automated Tests Bet`

## VSP Q1 + Q2 2020 OKR
O3: Stability and resiliency of the Platform's systems and teams continue to improve.
