### ISSUE TITLE
[QA] Help QA and team access SOCKS through Microsoft Internet Explorere 11 or newer [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13210]
## Issue Description
_As a QA tester, I need access through SOCKS for all web browsers including Firefox, Chrome, and IE 11.

---
## Tasks
- [ ] _Test and document SOCKS set up for IE if possible.

## Acceptance Criteria
- [ ] _Access to web enabled programs through all Browsers

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
