### ISSUE TITLE
Mismatched width and height for story_listing

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#13215]
## Issue Description
Mismatched img width and height attributes. The GraphQL output seems to be using the thumbnail dimensions while the CMS export seems to be using the full dimensions

## Example File
`/pittsburgh-health-care/stories`

### GraphQL build
```
<img class="news-img" 
src="/img/styles/2_1_medium_thumbnail/public/2020-08/shutterstock_636100784_plasma.jpg" 
alt="Tubes of blood in a centrifuge used to separate the plasma." title 
width="480" height="240">
```
### CMS Build
```
<img class="news-img" 
src="public://2020-08/shutterstock_636100784_plasma.jpg" 
alt="Tubes of blood in a centrifuge used to separate the plasma." title 
width="4487" height="3342">
```

## Tasks
- [x] Figure out why there is a mismatched in width and height.
- [x] Resolve issue, and verify the output matches the GraphQL content build.
- [x] Document where hardcoded changes need to be made if CMS adds or alters image styles.

**Comment by jhonnyoddball** [comment]
Tracked down the media node that is reflected on page
`media.6b2cf7fb-6ced-4b20-988a-e962a5b571f0.json`

It clearly reflects the current dimensions:

```
    "image": [
        {
            "alt": "Tubes of blood in a centrifuge used to separate the plasma.",
            "title": "",
            "width": 4487,
            "height": 3342,
            "target_type": "file",
            "target_uuid": "de3b0da7-1ec0-4cf0-8626-97ac1c77cbcb"
        }
    ]
```

**Comment by jhonnyoddball** [comment]
Based on liquid template `src/site/teasers/news_story_page.drupal.liquid`

```
{% assign image = node.fieldMedia.entity.image %}
<img class="news-img" src="{{ image.derivative.url }}" alt="{{ image.alt }}" title="{{ image.title }}" width="{{ image.derivative.width }}" height="{{ image.derivative.height }}">
```

**Comment by swirtSJW** [comment]
@jhonnyoddball The main difference is that the Graph query  is asking for a specific image style (thumbnail) that is defined in the query, vs the content export is just providing the raw size and knows nothing about what image style is needed for a given rendering of the content.
We have a ticket that I am working on right now ( https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2757) , to make it so that the media entities will have paths for each available image style.   I think to solve this particular issue, it would be a matter of the transformer for story_listing to know that the the template is expecting the style `2_1_medium_thumbnail` and provide the url for that image style derivative.  Thereby transforming
``` 
public://2020-08/shutterstock_636100784_plasma.jpg
```
into 
```
/img/styles/2_1_medium_thumbnail/public/2020-08/shutterstock_636100784_plasma.jpg
```

**Comment by swirtSJW** [comment]
@jhonnyoddball 
When complete 2757 would add a "styles" element like this to the media export file 
```
"styles": [
        {
            "raw": "2020-08/shutterstock_636100784_plasma.jpg",
            "2_1_medium_thumbnail": "/img/styles/2_1_medium_thumbnail/public/2020-08/shutterstock_636100784_plasma.jpg",
            "1_1_square_medium_thumbnail": "/img/styles1_1_square_medium_thumbnail/public/2020-08/shutterstock_636100784_plasma.jp"
        }
],
```

**Comment by swirtSJW** [comment]
@jhonnyoddball   
here are the corresponding dimensions
```
_1_1_SQUARE_MEDIUM_THUMBNAIL
  w: 240
  h: 240
_21MEDIUMTHUMBNAIL
  w: 480
  h: 240
_23MEDIUMTHUMBNAIL
  w: 320
  h: 480
_32MEDIUMTHUMBNAIL
  w: 480
  h: 320
_72MEDIUMTHUMBNAIL
  w: 1050
  h: 300
LARGE
  w: 480
  h: 480

```

What I am not clear on is that the derivative style in the query seems to be using local constants, which then map to the actual machine name of the style.   That creates some confusion that we may want to resolve
example: `_1_1_SQUARE_MEDIUM_THUMBNAIL` is really the CMS style machine name of `1_1_square_medium_thumbnail`


It is the actual machine name that is going to be used in the path pattern for the url of the image.
`/img/styles/[style_machine_name]/[src]`

sample: 
`url: "/img/styles/2_1_medium_thumbnail/public/2020-08/shutterstock_636100784_plasma.jpg",`

**Comment by swirtSJW** [comment]
Just noting the other item that was discussed on  the call, that we will know if there is a failure in this method because the gathering of the images would fail if the images were unavailable at build time and fail the build appropriately.

**Comment by swirtSJW** [comment]
I just updated the two comments up to add the actual machine names of the styles.

**Comment by jhonnyoddball** [comment]
## Documentation

### History
Mismatched img width and height attributes. The GraphQL output seems to be using the thumbnail dimensions while the CMS export seems to be using the full dimensions

### Solution
a new function `getImageCrop` and const `mediaImageStyles` were implemented to take care of this situation

Both are found in `/src/site/stages/build/process-cms-exports/transformers/helpers.js` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/414c15293190d9c5edcb2b77387e60c9e5d0793a/src/site/stages/build/process-cms-exports/transformers/helpers.js#L7)

### Next steps

Add function `getImageCrop` to all `field_media` fields in the transformers that use `media-image`

Ex: `{ entity: getImageCrop(entity.fieldMedia[0], '_21MEDIUMTHUMBNAIL') }`

**Comment by jhonnyoddball** [comment]
New hard-coded dimension can be added [here](https://github.com/department-of-veterans-affairs/vets-website/blob/414c15293190d9c5edcb2b77387e60c9e5d0793a/src/site/stages/build/process-cms-exports/transformers/helpers.js#L7)
