### ISSUE TITLE
[Design] Synthesize My Documents discovery research findings

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#13227]
## Issue Description
_In order to understand what Veterans expect in VA.gov's version of the My Documents tool, we need to uncover their successes and pain points with the eBenefits version of the tool._

---
## Tasks
- [x] _Synthesize data gathered from My Documents research study_
- [x] _Create a research readout document_
- [x] _Upload research readout to GH_
- [x] _(Optional / If applicable) Create a short deck for demoing research readout)_

## Acceptance Criteria
- [x] _Research readout is uploaded to GH and linked in this ticket_

**Comment by rileyorr** [comment]
The research readout is complete and available [here on GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/eFolders_Migration/research/discovery-sept20/research-readout.md)
