### ISSUE TITLE
[Design] Conduct My Documents discovery research

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#13226]
## Issue Description
_In order to understand what Veterans expect in VA.gov's version of the My Documents tool, we need to uncover their successes and pain points with the eBenefits version of the tool._

---
## Tasks
- [x] _Conduct user research sessions_
- [x] _Upload transcripts (scrubbed of PII) to GH_
- [x] _Upload a topline summary to GH_

## Acceptance Criteria
- [x] _User research sessions are completed_
- [x] _Transcripts have been scrubbed of PII and uploaded to GH_
- [x] _A link to the topline summary has been provided as a comment on this ticket_

**Comment by rileyorr** [comment]
All the [transcripts have been added to a notes folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/eFolders_Migration/research/discovery-sept20/notes) on GH. Additionally, the [top takeaways from each session have been compiled into a single document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/eFolders_Migration/research/discovery-sept20/topline-summary.md) that can be considered the topline summary.
