### ISSUE TITLE
Test an MVP Prometheus<>BigQuery connection

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13230]
## Issue Description
In order to understand the performance of products on VA.gov, we need historical data from Prometheus or Data Dog so that we can more easily compare backend data to other performance data. How might we test an initial connection from Prometheus to BigQuery so that we can understand what these queries and automation might look like?

Use the "system availability" data point as a starting MVP. 

**Background:** We share out the VA.gov "system availability" metric from Grafana as a measurement for external stakeholders. Can we automate this, and use this as a first rollout metric of the BigQuery<>Prometheus connection?

[System availability Grafana link.](http://grafana.vfs.va.gov/d/000000088/ww-uptime-report-draft?orgId=1&from=now-1M%2FM&to=now-1M%2FM) 

[Link to the Office of Management and Budget dashboard](https://va-gov.domo.com/page/1475431113) - how we share this metric with stakeholders. We filter by the last 30 days, manually updated at the beginning of each month.

---
## Tasks
- [ ] Research what it might take to ETL the "system availability" metric.
- [ ] Query this metric to BigQuery.
- [ ] Document ETL process.

## Acceptance Criteria
- [ ] VSP has a tested Prometheus<>BigQuery connection. Nice to have: this connected metric can be used in a report.

**Comment by jonwehausen** [comment]
Closing as historical
