### ISSUE TITLE
LOA Pathway Options

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13248]
## Tasks

- [ ] Identify different pathway options, draft in diagram 

- [ ] Review w/Patrick to make sure it is correct

- [ ] Review w/Steve to decide which ones we will support + how we will handle the ones we don't support

- [ ] Talk to IAM team about how to handle the users we will vs. won't support
