### ISSUE TITLE
[Design] Profile - make it more clear that we only support US phone numbers

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13246]
## Background

**Updated 3/30/21**
We thought we needed to change the display of international phone numbers somehow since we are totally ignoring the country code at the moment. We've determined that what we actually need to do is make it more clear to people that we only support U.S. numbers at this time.  

See [slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1599226764172300?thread_ts=1599169576.163500&cid=C909ZG2BB) and comments on this issue.

### Why
There are some countries (e.g. Belize) that have 10 digits including the area code, so someone could save an international number to their profile, and not realize that their country code was actually being saved in the DB as their area code.

## Tasks
- [x] Produce a mockup that:
-  removes the info box telling people we only accept US phone numbers 
- adds the helper text about only accepting US phone numbers to the label field.
- makes the field label more specific (currently just says `number`)
- [x] Produce a mockup with the new proposed error copy for invalid phone numbers.
- [x] Work with content to produce final copy before handoff to FE.

**Comment by mshea0606** [comment]
@sanlouise @tressaellen  Deferring this ticket until international numbers are accepted

**Comment by Samara-Strauss** [comment]
This is an old screenshot from Profile 1.0, but this solution might work. Since we only accept US phone numbers for now, we could show a grayed-out US country code like so:

![Screen Shot 2021-03-17 at 1.54.33 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/0e63746c-ce36-47e1-869c-f96742179c70)

**Comment by andaleliz** [comment]
I need some clarity on the design problem I'm trying to solve with this issue.  If a user can not input an international phone number, and VA Profile rejects international phone numbers, it seems that there isn't an international display to change or format through design. 

@erikphansen this came out of a scenario where someone appeared to have a Belize country code. Do we have reason to believe international phone numbers are getting through somewhere else other than our interface, and then sent to us? VA Profile said they reject international numbers so I don't see how it could be coming from there.

That being said, I think we can offer a bit more clarity in the error message by updating it to "Please enter a valid 10-digit U.S. phone number" or use the error message on our other forms "Please enter a 10-digit phone number (with or without dashes)".  Also, in the spirit of an improved mobile UX, I'd swap to the background-only alert for the info message.

cc @sanlouise in case you have any thoughts to share around this.

**Comment by erikphansen** [comment]
I think it's _possible_ there could be some non-USA phone numbers coming from VA Profile. They are clearly blocking new ones from getting added, but it seems possible that some intl phone numbers made it into VA Profile at some point. Unless we can actually find some cases in staging (or better yet in prod) where users actually do have intl phone numbers showing up in their profile, I'm really not sure what work we can or should do for this ticket. There are lots of potential formatting options for international phone numbers. I just looked at four countries on Apple Maps and came up with four different formatting options:

+33 1 53 71 53 71 France
+31 20 599 41 00 Netherlands
+7 (702) 426-01-02 Kazakhstan
+81 3 3408 2605 Japan

This ticket is sort of feeling like trying to fix a problem we don't _really_ have?

I do think that doing something to make it even clearer that we only accept US phone numbers would be helpful.

**Comment by erikphansen** [comment]
Oh! Did more Slack digging and found that it's staging user `judy.morrison@id.me` that has the Belize phone number on file. It has a country code of 501 and phone number of 6220000, and an empty area code because Belize does not have area codes. And since we ignore country codes (we assume they are all just `1`) the phone number is not formatted like a normal ten-digit number. I have no idea how this phone number got into the staging DB.

So how to handle formatting this number? ¯\_(ツ)_/¯ We _could_ add logic to look for country codes and if it's something other than `1` we'd prefix it with a `+`. And then list the rest of the phone number in an unformatted fashion. So, this Belize number would show up as `+501 6220000` in the Profile.

As I pointed out above, every country seems to format their phone numbers differently. And figuring out how to deal with that is probably far outside the scope of this 2 point ticket.

**Comment by andaleliz** [comment]
Thanks @erikphansen! Excellent info and sleuthing. 

>And since we ignore country codes (we assume they are all just 1) the phone number is not formatted like a normal ten-digit number.....We could add logic to look for country codes and if it's something other than 1 we'd prefix it with a +. And then list the rest of the phone number in an unformatted fashion. So, this Belize number would show up as +501 6220000 in the Profile.

Maybe a dumb question but how does the data come in so that we know this is a country code and not an area code? Why is it not (501)622-0000? I'd be curious to see how that's structured, just for my own knowledge.  I see in staging her number is `null622000` - is the 501 still somewhere in the database that we're just not exposing? 

>As I pointed out above, every country seems to format their phone numbers differently. And figuring out how to deal with that is probably far outside the scope of this 2 point ticket.

Yes, I agree - this is beyond a 2 point ticket if we do indeed need to figure out how to handle formatting for the world of international phone numbers.   I'm not convinced this is something we really need to do at this point if we have just this one example in the staging DB. How can we find out if there are any instances of this in production?

**Comment by erikphansen** [comment]
Where are you seeing `null622000` on staging? I see it show up as `6220000`.

The raw data for this phone number is below (note the `countryCode`):
```json
{
  "areaCode": null,
  "countryCode": "501",
  "createdAt": "2019-03-07T02:51:09.000+00:00",
  "extension": null,
  "effectiveEndDate": null,
  "effectiveStartDate": "2020-07-17T19:07:51.000+00:00",
  "id": 54215,
  "isInternational": true,
  "isTextable": null,
  "isTextPermitted": null,
  "isTty": null,
  "isVoicemailable": null,
  "phoneNumber": "6220000",
  "phoneType": "HOME",
  "sourceDate": "2020-07-17T19:07:51.000+00:00",
  "sourceSystemUser": null,
  "transactionId": "3a8e5bb8-ceef-4d68-a0a3-75d150aece90",
  "updatedAt": "2020-07-17T19:07:51.000+00:00",
  "vet360Id": "63807"
}
```

FWIW you can view this data by checking your browser's network tab and inspecting the response from the `GET user` API call. I'm happy to help with that if needed.

We could probably ask VA Profile to do a query of their database to see if they have any instances where a saved phone number has a country code that is something other than `1`.

**Comment by andaleliz** [comment]
It shows up as `null` when you open it in edit mode:
![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/46df0bb4-e43d-41e5-bc77-522072ca8e6b)

Thanks for the tip on the network tab, that's cool! 

I think that'd be worthwhile to ask VA Profile so we can see if this is really a problem or some random one-off instance in our staging DB.  I see there's also an `isInternational` attribute - any idea how that impacts things?  E.g. what would happen if there was a US number that incorrectly had `isInternational: true`? or a country code other than one but `isInternational: false`?

I'm not sure if there is a formal way to ask them to do this but I can start by posting in their slack channel.

**Comment by erikphansen** [comment]
Ohhh... that ☝️ is a bug I didn't know about. Can you make a ticket for that? Something like "edit phone number form does not handle prefilling `null` area codes"

I'll ask VA Profile if they can run that query. I do suspect that this is likely a non-issue in prod.

**Comment by Samara-Strauss** [comment]
> I need some clarity on the design problem I'm trying to solve with this issue. If a user can not input an international phone number, and VA Profile rejects international phone numbers, it seems that there isn't an international display to change or format through design.

Sorry, this ticket was poorly defined in the first place. I'm actually wondering if we need any design on this problem at all given the following:

- People can not save an international phone numbers in our profile, and we (1) already tell them that and (2) reject phone numbers that aren't 10 digits (US area code + 7-digit phone number). So, while we could add some sort of non-editable country code placeholder like shown in the screenshot I included a few comments above, there's really no risk that someone could save an international phone number in our profile.
- [Based on this Slack thread](https://dsva.slack.com/archives/C7TE0PFTL/p1617033280027000), there is likely a very outlier use case where an old international phone number could get pulled into the profile that existed in a system before VA Profile was created and didn't allow international numbers. My guess is this is pretty rare, so I don't know that it's worth putting a lot of design time into figuring out how to handle this. Unless we hear back from VA Profile that this is a bigger issue than we think, we can just treat international phone numbers that get pulled in like any other data — if the veteran sees the phone number is incorrect, they can update it to a non-international number.

Do either of you see a different path forward that involves updates on our end? If so, let me know.

**Comment by erikphansen** [comment]
It _is_ possible someone could enter a 10 digit international phone number. Belize has a country code of 501 and does not have area codes. So 5015551234 might be a valid phone number in Belize that our system would accept; it would just set the area code as 501 (which is in Arkansas).

Just throwing that out there!

**Comment by Samara-Strauss** [comment]
> It is possible someone could enter a 10 digit international phone number. Belize has a country code of 501 and does not have area codes. So 5015551234 might be a valid phone number in Belize that our system would accept; it would just set the area code as 501 (which is in Arkansas).

Got it. Then I think we could potentially add a read-only country code as an additional signal to users, but I don't know if there's any way to make the profile totally fool-proof against this edge case without potentially making things more confusing to our main users (people with US phone numbers). Admittedly, I haven't thought through all potential design solutions, so let me know if you can think of an elegant way to prevent this that wouldn't interfere with the primary use case of people entering US phone numbers.

**Comment by andaleliz** [comment]
I noticed in other areas of the profile we offer hint text in parentheses within the label - how about something like that here?  I do like the read only example (especially compared to some of the other solutions I've seen in the wild), but there are some a11y considerations that might make things a little more complicated we need to for this particular problem.   Having this information with the label leaves little room for ambiguity for those using AT, are super zoomed in, or who have cognitive issues.

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/b2a27c63-4351-4c46-849f-02ccd45d8b24)

This route would also be consistent w/ how we handle phone numbers across the site (note the updated label from `number` to `home phone number`); there aren't any other phone fields with the read-only `+1`.

Couple of other thoughts:
- the alert becomes redundant if we have the hint text. `Check back later` isn't exactly the most helpful guidance.  I don't know the history of how this came to be, but if it wasn't out of user feedback, perhaps we can consider getting rid of that.
- we can also update the error message to clarify we're looking for a U.S. number `Please enter a valid 10-digit U.S. phone number` if people try to enter more than 10 digits.  Maybe also if they start the string with a `+`?

Also @erikphansen, i opened that bug defect: [#22312](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22312)

**Comment by Samara-Strauss** [comment]
> I noticed in other areas of the profile we offer hint text in parentheses within the label - how about something like that here?

I'd be open to that! 

> the alert becomes redundant if we have the hint text. Check back later isn't exactly the most helpful guidance. I don't know the history of how this came to be, but if it wasn't out of user feedback, perhaps we can consider getting rid of that.

These are all really good points. If we add the in-label helper text, I think we can safely get rid of the alert box above the form.

> we can also update the error message to clarify we're looking for a U.S. number Please enter a valid 10-digit U.S. phone number if people try to enter more than 10 digits. Maybe also if they start the string with a +?

This also sounds good to me!

Unless @erikphansen has any objections, these all sound good to me, and I think we can update the first comment in this ticket to reflect the new objectives 😃

**Comment by erikphansen** [comment]
Yeah that all sounds fine. I think that the static `+1` at the front of the input field would be extra cool, but I'm not even sure how I'd do that within the confines of the form system.

**Comment by andaleliz** [comment]
@erikphansen glad you're good with this - added you as an assignee.  Do we need to update the estimate, or should the FE work be it's own ticket? I have spent 2 points on this already.

**Comment by Samara-Strauss** [comment]
@andaleliz I removed @erikphansen as an assignee. This is still yours for now. Please do the following (and I have updated the top comment to reflect this):

- Produce a mockup that removes the info box telling people we only accept US phone numbers AND adds the helper text about only accepting US phone numbers to the label field.
- Produce a mockup with the new proposed error copy for invalid phone numbers.
- Work with content to produce final copy before handoff to FE.

From there, we will create a separate ticket for frontend implementation.

**Comment by Samara-Strauss** [comment]
Also, @andaleliz, I did see you already had put some new stuff in the top comment (thank you), but I still modified. I think the final mocks can be clearer, and we should work with content before handing anything off to FE.

**Comment by andaleliz** [comment]
Sounds good- we have our suite content office hours on Thursday, so I'll review this with them there and then update the mock-ups (thought I had added some above, but maybe removing them was part of your modification? Or they didn't save properly?).  Thanks @Samara-Strauss !

**Comment by Samara-Strauss** [comment]
Sounds good! And yes, I removed the initial mock to remove any confusion that it wasn't totally finalized. Hope that's OK. Feel free to add it back if it helps you track your progress.

**Comment by andaleliz** [comment]
@bethpotts and @DanielleThierryUSDSVA, we're making this update to profile and would appreciate your input on the content.  I'll bring this up in office hours on Thursday, but wanted to give you a heads up now in case you have time to review and give it some thought in preparation for that meeting.  

Here's the current status of a phone number section in profile (edit mode). This shows you the alert, field label, and error message:
![image](https://user-images.githubusercontent.com/55992116/113014553-af532000-914a-11eb-87ef-219629e67ce9.png)

Proposed changes:
- use hint text instead of the alert to clarify we only support U.S. phone numbers
- improve specificity of field label and error to better align w/ other forms on VA.gov and reduce ambiguity

![Screen Shot 2021-03-30 at 10 26 24 AM](https://user-images.githubusercontent.com/55992116/113013928-263be900-914a-11eb-9bf5-6ae9b8184045.png)
![Screen Shot 2021-03-30 at 10 26 09 AM](https://user-images.githubusercontent.com/55992116/113013933-26d47f80-914a-11eb-904e-5b2ca73ad583.png)

**Comment by andaleliz** [comment]
Reviewed w/ content team today and they are good with these changes.

**Comment by Samara-Strauss** [comment]
Sounds great! Can you work with @ajakabcin to create a ticket for this work for frontend implementation? Thanks!

**Comment by ajakabcin** [comment]
Created #22533 for FE implementation

**Comment by ajakabcin** [comment]
I believe we can close this out now that we have the FE ticket created. Following up with Liz tomorrow to make sure that ticket has all the right details in it tomorrow.
