### ISSUE TITLE
Higher Level Review: Status

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13244]
## User Story

For any higher-level review, as a user I can see the following information:
- [x] Title of the higher-level review, the date it was received
- [x] Date it was last updated
- [x] Past events for the higher-level review and their date
- [x] Current status (title and description)
- [x] Text explaining where the Veteran is in the docket line (if data exists in API) 
- [x] Veterans Affairs Benefits and Services phone number
- [x] Link to VA.gov to get more details on the appeal

## Tasks
- [x] Find a staging account with an active HLR
- [x]  Determine data elements for screens in session with Steve
- [x]  High fidelity prototype of screens in iOS
- [ ]  Usability test as needed, refine as needed
- [ ]  (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## [Wireframe](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433579258)

**Comment by srmyers17** [comment]
At this point we have not been able to see one of these. Perhaps because Appeals API is broken in staging. BAM team will likely start working on it again when they work on the CST. 

Talking to CST team next Friday. Follow up with Steve on what to do in order to see what data is available on this screen.

**Comment by srmyers17** [comment]
What we can see in the Appeals API may not be helpful because when we look at Claims API we see things that aren't necessarily on the screen, so we need to make sure we are viewing the right data points.

**Comment by srmyers17** [comment]
Working on hunting down an Appeals account

**Comment by bridgethapner** [comment]
Thanks to Steve's searching + Anna's help, I was able to get screenshots of a user with an active HLR and updated the user story accordingly. Would like to review with Steve next sprint planning before starting the UX/UI work.

**Comment by srmyers17** [comment]
Next steps:
- Discuss AC w/Steve

**Comment by bridgethapner** [comment]
This design will follow the same as Board Appeals per 10/2 session w/ Steve.
