### ISSUE TITLE
Internal redirects: Disability "past" rates pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#13245]
## Issue Description

In ticket #13189, we updated past rates tables to address the lack of plain language. Specifically, we eliminated the words "historic" and "historical," and replaced with "past." This change extends to the URL names for these pages, which needs to be redirected to the newer name.
---
## Tasks
- [ ] Publish pages listed below (Randi)
- [ ] Implement redirects for the pages listed below (Nick or Kelson)
- [ ] Validate that the URLs are live and working as intended (Randi or Selina)

**Note:** To avoid broken links, don't set a page to publish and redirect on the same day.

---
## Redirects needed

currently | revise to
-- | --
/disability/compensation-rates/birth-defect-rates/historical-rates-2018/ | /disability/compensation-rates/birth-defect-rates/past-rates-2018/
/disability/compensation-rates/birth-defect-rates/historical-rates-2019/ | /disability/compensation-rates/birth-defect-rates/past-rates-2019/
/disability/compensation-rates/special-benefit-allowance-rates/historic-rates-2018/ | /disability/compensation-rates/special-benefit-allowance-rates/past-rates-2018/
/disability/compensation-rates/special-benefit-allowance-rates/historic-rates-2019/ | /disability/compensation-rates/special-benefit-allowance-rates/past-rates-2019/
/disability/compensation-rates/special-monthly-compensation-rates/historic-rates-2018/ | /disability/compensation-rates/special-monthly-compensation-rates/past-rates-2018/
/disability/compensation-rates/special-monthly-compensation-rates/historic-rates-2019/ | /disability/compensation-rates/special-monthly-compensation-rates/past-rates-2019/
/disability/compensation-rates/veteran-rates/historical-rates-2018/ | /disability/compensation-rates/veteran-rates/past-rates-2018/
/disability/compensation-rates/veteran-rates/historical-rates-2019/ | /disability/compensation-rates/veteran-rates/past-rates-2019/

## Acceptance Criteria
- [ ] _URLs are live and working as intended_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
Redirects outside of Drupal are not needed for these given they are such low volume and were not live for very long.  The URLs just need to be changed before we redirect the legacy pages to them.

**Comment by lunascoop** [comment]
Closing this ticket per Mikki's comment above. The effort for changing the URLs in Drupal is already tracked in ticket #13189. cc: @MickinSahni @bethpotts @RLHecht @kelsonic @ncksllvn
