### ISSUE TITLE
[Design] Whiteboarding/Wireframing 2-3 high-level concepts

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13251]
## Background
Part of LIH phase 1
See [LIH outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md)

## Tasks
- [x] Whiteboarding 
- [x] Wireframing (2-3 high level concepts) 
- [x] Review with team and pick preferred concept
- [x] Matt to schedule VSP Design/Intent checkpoint

**Comment by tressaellen** [comment]
Screens can be seen in [this ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13330)
