### ISSUE TITLE
[Design] My Documents usability test conversation guide

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#13268]
## Issue Description
_To kick off usability testing for My Documents, we need to write a research plan using [the provided template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)._

---
## Tasks
- [ ] _Write a conversation guide for the My Documents usability test study._
- [ ] _Send the completed conversation guide to Shawna for feedback._
- [ ] _After the conversation guide is approved by Shawna, send the document to Lauren to kick off the recruiting process._

## Acceptance Criteria
- [ ] _Shawna has approved the conversation guide._
- [ ] _The conversation guide is uploaded to GitHub and linked to this ticket._
- [ ] _The conversation guide is sent to Lauren._
