### ISSUE TITLE
[Design] My Documents usability test research plan

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#13266]
## Issue Description
_To kick off usability testing for the My Documents MVP, we need to write a research plan using [the provided template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)._

---
## Tasks
 - [ ] _Write a research plan for the My Documents MVP usability test study_
- [ ] _Send the completed research plan to Shawna for feedback_
 - [ ] _After the research plan is approved by Shawna, send the document to Lauren to kick off the recruiting process._

## Acceptance Criteria
- [ ] _Shawna has approved the research plan_
- [ ] _The research plan is uploaded to GitHub and linked to this ticket_
- [ ] _The research plan is sent to Lauren_
