### ISSUE TITLE
[Design] Conduct My Documents usability testing sessions

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#13270]
## Issue Description
_In order to validate that the My Documents design is intuitive to our user base, we need to a conduct task-based usability study to verify the UI and uncover opportunities for improvement._

---
## Tasks
- [ ] _Conduct usability test sessions_
- [ ] _Upload transcripts (scrubbed of PII) to GH_
- [ ] _Upload a topline summary to GH_

## Acceptance Criteria
- [ ] _Usability test sessions are completed_
- [ ] _Transcripts have been scrubbed of PII and uploaded to GH_
- [ ] _A link to the topline summary has been provided as a comment on this ticket_
