### ISSUE TITLE
Send SSN and DOB to BGS

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13273]
## Background
Given what we have learned with the extra fields being required for submission in BGS, we needed to ensure that when removing dependents we also had those fields in place as well.  Now that SSN and DOB are in place on the FE

## Considerations
- There are 5 workflows:
    - Remove divorced spouse
    - Remove stepchild
    - Remove deceased dependent
    - Remove married child
    - Remove child left school
- May need to update tests

## Tasks
- [x] Get params (SSN and DOB) out of the payload
- [x] Update each workflow and set the parameter to be sent to BGS
- [x] Update test(s) as needed

## Acceptance Criteria
- [x] Parameters are determined
- [x] Each workflow is addressed
- [x] Tests are passing given new information 
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/4877
