### ISSUE TITLE
Localization | Discovery | Accessibility Initial Conversation

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13274]
## Issue Description

We need to identify, discuss, and document potential accessibility issues and solutions in preparation for localization MVP.

---
## Tasks
- [x] Discuss and document concerns and solutions

## Acceptance Criteria
- [x] Accessibility concerns and solutions discussed and documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@1Copenut @youngfreezyVA Notes from our conversation today are here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/spanish-translation/coronavirus-mvp/accessibility-considerations.md. Feel free to add anything I may have missed. And thank you both for joining!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @batemapf @artsymartha68. Not sure if our COVID-19 screener has aria label or sr-only content, or if it's already been addressed in the Spanish translation. But just in case, I wanted to share these notes from my conversation with Trevor with you. Thanks!

- Google Translate (and other machine translations) won't automatically translate hidden content that's only for screen readers. And if human translators are only reviewing the visible content on a page, they'll miss it as well. Therefore, we need to incorporate into our translation process a step to check the template/source content and update all aria label and sr-only content.
- We'll also want to make sure that aria labels contain full phrases so that the text translates accurately. For example, if a button's visible text is "Enroll now," the aria label text should include "Enroll now in VA health care."
- Accessibility experts can provide more guidance for how to make translated content successful for screen readers.
- We can also wrap individual pieces of translated content in "lang-es" so that screen readers will use the right pronunciation to read the translated text. We are going to try this in a test environment for the block of helper text on va.gov/health-care/how-to-apply.
