### ISSUE TITLE
Questionnaire Title/Appointment Details

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#13279]
---
## Tasks
- [x] Finalize the questionnaire title and appt details locations, layout and content
- [x] Update wireframes

## Acceptance Criteria
- [x] Review with accessibility
- [x] UI review meeting with product
- [x] UI review meeting with engineering
- [x] Published to [Zeplin](https://zpl.io/VOOek8j)

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mdewey What engineering story will these changes be implemented? I'll add the wireframes to that story once I know.

**Comment by abuckley3385** [comment]
@kristenmcconnell @mdewey @massrb @dillo I am now realizing that the title says Upcoming appointment questionnaire - I think this will be fine for our MVP but this design and field needs to be a bit more dynamic.  We need to know the appt. type ie. New Patient, Established Patient, Followup, Adult Physical..etc. and then the appt. header should be specific to the appt. type.  These names are super cryptic so the idea is that we could have a mapping to allow for a display as in patient friendly speak.
