### ISSUE TITLE
Determine any needed tech approvals

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13275]
## Issue Description
As the team implementing a translation widget on the coronavirus FAQs page, we need to understand and obtain any needed approvals prior to implementation.
---
## Tasks
- [ ] Get understanding of needed approvals
- [ ] Obtain needed approvals

## Acceptance Criteria
- [ ] All approvals in place prior to launch
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @batemapf. Wondering if you might have time today or tomorrow to talk through the question of what approvals we might need to add a translation widget?

**Comment by batemapf** [comment]
happy to! will DM for time

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA - hi can this be closed?
