### ISSUE TITLE
Host Medallia CSS

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13287]
## Issue Description
In order to make specific design changes on Medallia surveys, we have to add our own custom CSS. This needs to get hosted on VA.gov and then we (VSP Analytics & Insights) can add it to the Medallia web portal to change the design. 

I have our code below (it hasn't been tested, so please make any updates if it's needed!)

---
## Tasks
- [ ] Update CSS code block below/confirm accuracy as applicable
- [ ] Host CSS on Staging
- [ ] Provide CSS URL
- [ ] VSP Analytics & Insights tests design on Staging
- [ ] Host CSS on Prod

## Acceptance Criteria
- [ ] VSP has a hosted CSS so that we can customize the Medallia surveys
---
## CSS
```
/*
  Title: VA.gov Custom CSS file
  Date: 09/01/2020
  Version: 1.0
*/

/* Fonts */
#liveForm .ng-binding, #liveForm div > span {
  font-family: 'Source Sans Pro' !important; }

/* Remove 'Powered by Medallia' */
#liveForm .kpl-form-footer.ng-scope {
  display: none; }

/* Radio buttons background color */
.neb-content md-radio-group div.radio md-radio-button ._md-on {
  background-color: #0071BC !important; }
```

**Comment by meganhkelley** [comment]
@joanneesteban if you can annotate a screenshot for us showing what colors go where, etc, we can update the CSS block here and get this implemented

**Comment by joanneesteban** [comment]
@meganhkelley thank you!

So this is updating the Ratings question. The [Medallia documentation for this is linked here](https://docs.medallia.com/digital/digital/index.html#Help/Digital/Administration_guide/CSS/CSS_Library/Rating_scales.html) (also screenshot below), because you have to [sign up for the documentation site](https://dsva.slack.com/archives/C015PF52YFL/p1593715880005100?thread_ts=1593701055.004700&cid=C015PF52YFL)

The button colors should be: #0071BC
And the "very" and "satisfied" should be aligned with the 5. 

Here's the original:
![image](https://user-images.githubusercontent.com/48964695/92811233-3fd33a00-f38c-11ea-83f6-29dc3934b595.png)


Here's the intended design: 
![image (19)](https://user-images.githubusercontent.com/48964695/92789607-03e2a980-f379-11ea-9a11-54cab79258b5.png)

---
### Medallia documentation screenshots:
![image](https://user-images.githubusercontent.com/48964695/92790743-0bef1900-f37a-11ea-8219-2aca2cc58b8c.png)
![image](https://user-images.githubusercontent.com/48964695/92790815-1ad5cb80-f37a-11ea-9d58-2a679ecde92a.png)

**Comment by rianfowler** [comment]
- VSP to host the CSS override in the core site CSS instead of providing a file link for the survey injection script to add to the page 
  - This is the approach we've used in the past. 
  - The CSS file names change on every deploy and we need to modify the build process to build a separate file for the injection script to use 
- This will be easier to maintain at the cost of a very small negative impact to site performance since the overrides will be added to every page regardless if the survey is present. We can revisit this when we start examining how to improve site load performance. (e.g. when we figure out how we want to modularize or dispose the CSS)

**Comment by billfienberg** [comment]
The [PR to remove the hash from the Medallia CSS](https://github.com/department-of-veterans-affairs/vets-website/pull/14312) file has been merged and deployed to staging. 

Here's a link to the hash-less Medallia CSS file on S3:
https://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/va-medallia-styles.css

**Comment by billfienberg** [comment]
@joanneesteban, y'all should be able to test on staging now. 

FYI, when y'all are done testing on staging and ready to go to prod, it will require another deploy, and updating the link.

Reference:

- [Slack thread](https://dsva.slack.com/archives/CQH357ZTP/p1601591911069700?thread_ts=1601586099.060800&cid=CQH357ZTP)

**Comment by joanneesteban** [comment]
Thanks, @billfienberg ! So I added the CSS to Medallia, but the design of the ratings question doesn't look like it's lining up:

Actual:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/ec479ae9-fa82-4df6-a036-3f1b78864078)
Proposed Design:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/6a408eb8-3950-440f-ad78-89531f3fb84d)

---

Also, @CrystabelReiter @emilywaggoner - changing the font to Source Sans Pro shrinks the font size, and removing the Medallia powered logo removes the padding at the bottom. Can you recommend design changes here? Bill is helping us fix the design on the CSS side.

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/d67fb46c-6dfe-4c39-bc5f-44523fa8476c)

---

Testing the survey on staging.va.gov/find-locations

**Comment by CrystabelReiter** [comment]
The Source Sans Pro font size looks alright to me. I'm wondering if there's accessibility reasons we should change the font to make it bigger @emilywaggoner 

Do we have to remove the Medallia logo? If we can't add more padding at the bottom then I suggest adding it back in

**Comment by joanneesteban** [comment]
Thanks, @CrystabelReiter ! @emilywaggoner let us know if we should make the font size bigger.

@billfienberg , any chance we can add padding to the bottom as well?

**Comment by billfienberg** [comment]
It looks like the number ratings elements are actually background images, and not HTML:
https://resource.digital.voice.va.gov/resources/dist/assets/images/kampyle/icons/rating/0-10_circle.png

![image](https://user-images.githubusercontent.com/6130520/95129191-4604ce00-0720-11eb-8482-bebad32d5932.png)

![image](https://user-images.githubusercontent.com/6130520/95129302-75b3d600-0720-11eb-9704-be2207d5d8f4.png)

**Comment by joanneesteban** [comment]
Oh no... @billfienberg does that mean we can't align the "Very Satisfied" at the bottom?

**Comment by billfienberg** [comment]
@joanneesteban, I'm still experimenting to see what is/isn't feasible. 

Right now, I'm more curious why the font styles weren't being applied. I just merged a change to add the padding, and hopefully update the `font-family`. I'll let you know once that's deployed, and I have more info.

**Comment by billfienberg** [comment]
@joanneesteban, the padding and font updates are on [staging](https://staging.va.gov/find-locations). I'll do a little more exploration to see what are options are with the rating elements that use background images. 

![image](https://user-images.githubusercontent.com/6130520/95207896-02f13c00-07ae-11eb-908b-83d7a86c7169.png)

**Comment by billfienberg** [comment]
@joanneesteban, after some investigation, I don't think it will be feasible to style the rating elements because of the background images. 

If my understanding is accurate, you want some additional space between the **Very Dissatisfied** and **Very Satisfied** labels below the rating elements so they're not scrunched together, correct? 

If so, one simple option is shrinking the font-size from 11px to 10px. For example:
![image](https://user-images.githubusercontent.com/6130520/95371120-60b18100-089f-11eb-9b93-09e7b152ba90.png)

Another option is making the **Very Dissatisfied** and **Very Satisfied** labels wrap so each label takes up two lines. 

What other CSS changes did you have in mind?

**Comment by joanneesteban** [comment]
Thanks, @billfienberg for investigating that. What would the label wrapping for 2 lines look like? I think cleaning up the ratings question (the question we're currently working on) should be last part of this. Thoughts, @CrystabelReiter ?

**Comment by CrystabelReiter** [comment]
@joanneesteban @billfienberg I'd also like to see what the label wrapping to 2 lines look like. I don't think we should go any lower in font size

**Comment by billfienberg** [comment]
@joanneesteban @CrystabelReiter, here is what the wrapping text would look like with two different text-alignment options.

Left-aligned wrapping text and right-aligned wrapping text:
![image](https://user-images.githubusercontent.com/6130520/95382239-f274ba80-08ae-11eb-8c46-ae49ea2b1581.png)

Center-aligned wrapping text:
![image](https://user-images.githubusercontent.com/6130520/95382345-1e903b80-08af-11eb-87e1-44b18d7938ae.png)

**Comment by joanneesteban** [comment]
Left- & right-aligned look more usable to me than center or no alignment. @CrystabelReiter ?

**Comment by CrystabelReiter** [comment]
@joanneesteban @billfienberg I agree with left and right aligned looks more usable

**Comment by billfienberg** [comment]
Cool. I'll start drafting a PR for the left and right aligned option. Sorry the rating element styles turned out to be infeasible.

If y'all have other ideas for style improvements, feel free to share, and I'll do my best to accommodate.

**Comment by joanneesteban** [comment]
@billfienberg also, it doesn't look like the Intro & Thank You pages are inheriting the Font style:

![image](https://user-images.githubusercontent.com/48964695/95481591-286f7880-095b-11eb-9daf-e800e20d0987.png)

**Comment by billfienberg** [comment]
> also, it doesn't look like the Intro & Thank You pages are inheriting the Font style:
> 
> ![image](https://user-images.githubusercontent.com/48964695/95481591-286f7880-095b-11eb-9daf-e800e20d0987.png)

@joanneesteban, I see what you're talking about on the Thank You page. But I'm not seeing an Intro page on [staging](https://staging.va.gov/find-locations).

![no-medallia-intro-page](https://user-images.githubusercontent.com/6130520/95494867-3675c700-0964-11eb-8781-c934e04bd7ce.gif)

**Comment by joanneesteban** [comment]
"Always On" survey added to https://staging.va.gov/find-locations/facility/vha_691
Feedback button has been removed from this page for testing purposes, and will be readded after this test.

This has an invite page and thank you page.

Another edit, @billfienberg is that the "Powered by Medallia" logos and padding will need to be edited in the same way on these pages as well.

And the text that users fill in on the survey itself isn't inheriting the font, but should be.

Thank you!

**Comment by billfienberg** [comment]
@joanneesteban, this is the text with the incorrect font that you're referring to on https://staging.va.gov/find-locations, correct?

![medallia-update-textarea-font](https://user-images.githubusercontent.com/6130520/95604780-ac8a3480-0a1d-11eb-8c99-cf9ea7ac0505.gif)

**Comment by joanneesteban** [comment]
@billfienberg yup!

**Comment by billfienberg** [comment]
List of current style updates and current states
| URL | Survey Page| Requirement | Status |
| - | - | - | - |
| https://staging.va.gov/find-locations | Survey | no 'Powered By' | ✅  |
| https://staging.va.gov/find-locations | Survey | Text has Source Sans Pro font | ✅  |
| https://staging.va.gov/find-locations | Survey | `textarea` has Source Sans Pro font | PR |
| https://staging.va.gov/find-locations | Thank You | no 'Powered By' | ✅  |
| https://staging.va.gov/find-locations | Thank You | Text has Source Sans Pro font | ✅  |
| https://staging.va.gov/find-locations/facility/vha_691 | Intro | no 'Powered By' | PR |
| https://staging.va.gov/find-locations/facility/vha_691 | Survey | no 'Powered By' | PR |
| https://staging.va.gov/find-locations/facility/vha_691 | Thank You | no 'Powered By' | PR |

**Comment by billfienberg** [comment]
The updated styles from the [most recent PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14523) have been deployed to [staging](https://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/va-medallia-styles.css), and they're being loaded on `/find-locations`, but not on `/find-locations/facility/vha_691`. 🤔 

![image](https://user-images.githubusercontent.com/6130520/95769345-5adfe500-0c7d-11eb-973c-1122bac09c80.png)

**Comment by billfienberg** [comment]
@joanneesteban and I just finished pairing, and here are some notes from the pairing meeting:

- 🤔  The custom style file for `/find-locations/facility/vha_691` was surprisingly already updated from [`va-vets-custom-styles-v5.css`](http://medallia.s3.amazonaws.com/Vets/va-vets-custom-styles-v5.css) to [`va-medallia-styles.css`](https://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/va-medallia-styles.css)
- 😃  The `va-medallia-styles.css` style file is being loaded in the iframe
   - ![image](https://user-images.githubusercontent.com/6130520/96472794-7c4d4d80-11f6-11eb-968d-a4659c46a702.png)
- ✅  At least one of the selectors from the `va-medallia-styles.css` style file successfully matches an element in the iframe
   - `.ng-scope .footerCls`
   - ![image](https://user-images.githubusercontent.com/6130520/96473080-d1895f00-11f6-11eb-8d94-19322fbb991e.png)
- 😦  The CSS from the `va-medallia-styles.css` style file is not being applied to the elements in the Medallia iframe

**Comment by billfienberg** [comment]
I suspect there is some type of caching happening when using CAG because we saw the old style file (`va-vets-custom-styles-v5.css`) being loaded when using CAG, but saw the new style file (`va-medallia-styles.css`) being loaded outside of CAG.

**Comment by meganhkelley** [comment]
Current status: on hold until VSP FE Tools hears more from VSP Analytics/Insights cc @joanneesteban

**Comment by billfienberg** [comment]
PR to remove the content hash from the prod version of the Medallia custom CSS file: https://github.com/department-of-veterans-affairs/vets-website/pull/16111

Staging CSS URL: https://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/va-medallia-styles.css

Prod CSS URL: https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/va-medallia-styles.css

**Comment by meganhkelley** [comment]
@jwoodman5 @JoeTice @billfienberg I removed FE Tools label from this ticket, not sure if ticket is still relevant or can be closed

**Comment by billfienberg** [comment]
My gut says this can be closed.

**Comment by jwoodman5** [comment]
I agree and closing :) Thanks!
