### ISSUE TITLE
Staging Review - Find VA Forms: Detail Pages

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13285]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [ ] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt 
- [ ] Andrea to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- [Product outline: Find VA Forms - Search & Detail Landing Pages](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign#product-outline-find-va-forms---search--detail-landing-pages)
- [Release Plan - Find VA Form (Detail Pages)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/release-plan.md) 
- Unauthenticated feature so no user credentials necessary. The feature is available behind basic auth in staging and prod.
  - ~Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_~
- [product test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/605):
  - [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/137)
  - [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/138) -- both defects closed.
- Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/accessibility-checklist.md).
- List of known issues (with links to tickets when applicable)
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/12958
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/13565

## Meeting attendees from VSA PW
- Product Manager (required): Mickin Sahni
- DEPO product lead (required): Jen Lee
- Anyone else from your team who significantly contributed to the artifacts provided (required): Nick Sullivan, Brian Lloyd

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by MickinSahni** [comment]
@andreahewitt-odd could an asynch staging review be appropriate for this initiative? 
We're in prod now (behind basic auth) and have our prereqs nearly complete ☝️. 
Hopefully we can save some time on our schedules by doing it offline (rather than a meeting) 🤞.

**Comment by MickinSahni** [comment]
👋 @andreahewitt-odd ping on this and whether we could/should do this asynch.

**Comment by tlei123** [comment]
@pjhill , Coverage for References (Cases) report and Summary (Defects) report links now up in main Description, under Test Plan/Case link.

@MickinSahni already added Test Plan/Cases link before I got here.

**Comment by mnorthuis** [comment]
@MickinSahni  Can you please provide a list/links of what form detail pages we are reviewing as part of this staging review?

**Comment by peggygannon** [comment]
Hi, @MickinSahni I don't see a staging link in this ticket, so can you please confirm that  ticket below is what we should be reviewing for this staging review? 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/11155

cc @andreahewitt-odd

**Comment by mnorthuis** [comment]
I reviewed all of the pages listed in issue #11155 and talked through a few questions with Jen and do not have any additional feedback from an IA perspective.  If there are more or different pages that we should be reviewing other than what is in #11155, additional time will be needed to continue my review.

**Comment by MickinSahni** [comment]
Hey team, that was an oversight. Sorry about that. Here's a list of prod urls for "top forms":


https://www.va.gov/find-forms/about-form-21-4138/
https://www.va.gov/find-forms/about-form-22-1995/
https://www.va.gov/find-forms/about-form-21-526ez/
https://www.va.gov/find-forms/about-form-21-2680/
https://www.va.gov/find-forms/about-form-10-7959c/
https://www.va.gov/find-forms/about-form-10-10d/
https://www.va.gov/find-forms/about-form-21-22/
https://www.va.gov/find-forms/about-form-10-5345/
https://www.va.gov/find-forms/about-form-20-0995/
https://www.va.gov/find-forms/about-form-21-686c/
https://www.va.gov/find-forms/about-form-10-0137/
https://www.va.gov/find-forms/about-form-21-0781/
https://www.va.gov/find-forms/about-form-21-0966/
https://www.va.gov/find-forms/about-form-21-0845/
https://www.va.gov/find-forms/about-form-22-5490/
https://www.va.gov/find-forms/about-form-26-1880/
https://www.va.gov/find-forms/about-form-10-2850c/
https://www.va.gov/find-forms/about-form-21-4142/
https://www.va.gov/find-forms/about-form-21p-0969/
https://www.va.gov/find-forms/about-form-21p-534ez/
https://www.va.gov/find-forms/about-form-10-10ez-pdf/
https://www.va.gov/find-forms/about-form-10-3542/
https://www.va.gov/find-forms/about-form-22-1990e/
https://www.va.gov/find-forms/about-form-22-1990n/
https://www.va.gov/find-forms/about-form-22-1990/
https://www.va.gov/find-forms/about-form-22-5495/
https://www.va.gov/find-forms/about-form-va40-10007/
https://www.va.gov/find-forms/about-form-21p-530/
https://www.va.gov/find-forms/about-form-21p-527ez/
https://www.va.gov/find-forms/about-form-10-10cg/
https://www.va.gov/find-forms/about-form-21-22a/
https://www.va.gov/find-forms/about-form-21-674/
https://www.va.gov/find-forms/about-form-21p-509/
https://www.va.gov/find-forms/about-form-10-0137-espanol/
https://www.va.gov/find-forms/about-form-10-0137a/
https://www.va.gov/find-forms/about-form-21-0781a/
https://www.va.gov/find-forms/about-form-21p-527/
https://www.va.gov/find-forms/about-form-21p-534/
https://www.va.gov/find-forms/about-form-10-10ez/
https://www.va.gov/find-forms/about-form-10-10ezr/
https://www.va.gov/find-forms/about-form-21-0779/

**Comment by pjhill** [comment]
QA Feedback:
QA artifacts look great! Both defects have been resolved and test coverage looks sufficient given the scope of the product (almost entirely content / copy).  Great job with the artifacts, thanks!

**Comment by mnorthuis** [comment]
Thank you @MickinSahni - I'm assuming this is batch 1 and matches what is in #11155, correct?  I didn't match them up 1 for 1 but looks like the same list.  I reviewed based on #11155. 

A couple of items:

- 'https://www.va.gov/find-forms/about-form-10-10ez-pdf/` was updated to 'https://www.va.gov/find-forms/about-form-10-10ez-espanol/  `.  The live URL is actually correct, it is just wrong in the list above. 
- `https://www.va.gov/find-forms/about-form-va40-10007/` should be updated to `https://www.va.gov/find-forms/about-form-40-10007/` - remove the extra "va" in the URL, it is not part of the breadcrumb, H1 or meta title
- Do we need the accent mark over the "n" in "espanol" in our content?

**Comment by MickinSahni** [comment]
Thanks, Mikki. Yep; it's the same list. 

---

> 'https://www.va.gov/find-forms/about-form-10-10ez-pdf/` was updated to 'https://www.va.gov/find-forms/about-form-10-10ez-espanol/ `.

updated, thanks

> https://www.va.gov/find-forms/about-form-va40-10007/ should be updated to https://www.va.gov/find-forms/about-form-40-10007/ - remove the extra "va" in the URL, it is not part of the breadcrumb, H1 or meta title

yep, follow-up ticket for us to address from UAT here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13751

> Do we need the accent mark over the "n" in "espanol" in our content?

I would think so, but not seeing "espanol" on the page. Also not seeing on [content style guide](https://design.va.gov/content-style-guide), but could be missing it. Thoughts, @peggygannon?

**Comment by emilywaggoner** [comment]
@MickinSahni These look great design-wise, good to go!

**Comment by jenstrickland** [comment]
@MickinSahni @brianalloyd 

Since this work is currently in the VA preview environment, I do not have access to the tools needed to run an accessibility review. I spoke with @ncksllvn and @kelsonic yesterday and they said it is going into production behind a flag soon. I propose conducting this staging review then, so that I can use the axe browser scan and various screen readers currently unavailable in the VA preview environment. 

In the interim, if the team sees any accessibility issues in the top light blue bar, those should be addressed before an accessibility review. 

PS - I have a request into Enterprise Support to have NVDA and the Chrome axe extension added to my virtual machine, and they said it could be a while. 

@andreahewitt-odd @1Copenut — is this okay with VSP?

**Comment by ncksllvn** [comment]
I think there was a miscommunication between the form detail pages and the Learning Center. The form detail pages are already launched in production behind basic authentication - example, https://www.va.gov/find-forms/about-form-10-10ez/. I think we already did staging review for this.

**Comment by 1Copenut** [comment]
@jenstrickland 
I agree that a staging review will have to be done in production behind the basic authentication, given the limitations of the preview environment.

/cc @andreahewitt-odd

**Comment by MickinSahni** [comment]
> I think there was a miscommunication between the form detail pages and the Learning Center. The form detail pages are already launched in production behind basic authentication - example, https://www.va.gov/find-forms/about-form-10-10ez/. I think we already did staging review for this.

Re-upping Nick's message ☝️ 

This staging review is for Find VA Forms - Detail Pages, which is already in prod behind basic auth.

**Comment by jenstrickland** [comment]
@ncksllvn — The staging review was scheduled for 9/18, and originally I was provided a list of va preview pages. It looks like the request was updated on the date of the review with prod links, which I didn't have in the accessibility epic for the review. 

So, the accessibility staging review was not completed, and I could start now.

**Comment by ncksllvn** [comment]
Deferring to @MickinSahni @brianalloyd and @jenniferlee-dsva

**Comment by MickinSahni** [comment]
Ok, so looks like we're good to go now with prod behind basic auth 👍
