### ISSUE TITLE
[Frontend] Debt Letters V2 feedback 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#13292]
## Issue Description
_This ticket contains UI feedback on Debt Letters v2 as it appears in staging. I tried to categorize by page, but let me know if you have questions about anything!_

### General (across all pages)
- [ ] All the pages are missing the COVID alert
- [x] The breadcrumbs don't match [the breadcrumbs in Mikki's documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-letters.md). For example, when I click on a debt details button, the breadcrumbs don't change from `Home > Manage your VA debt > Your VA debt` to `Home > Manage your VA debt > Your VA debt > Details`

### Your VA debt (page)

- [x] Remove “home loan” from the subtitle, “Check the details of VA debt you might have related to your education, disability compensation, pension, or home loan benefits.“ - Home loan debts aren’t currently included in the tool 
- [x] Subtitle should have a line-height of 1.7
- [x] “On this page” should be h3 utility (Bitter bold 20px); it’s currently h4 (Bitter bold 17px)
- [x] "On this page" links - the arrow icons should be larger
- [x] "On this page" link padding should be increased to 16px on both sides (this is our bad, but an accessibility consideration!)

#### Current debts
- [x] Padding between the debt name (ex. Post-9/11 GI Bill debt for books and supplies) and “Updated on [Date]” should be 8px
- [x] “What if I don’t see a debt” should be an H4 utility (Bitter bold 17px); it’s currently h3 (Bitter bold 20px)
- [x] Padding between “For medical co-payment debt, please go to Pay your VA copay bill to learn about your payment options.” and “Download debt letters” header should be 32px
- [x] “Download debt letters” should be an h2; it’s currently an h3

#### FAQs
- [x] “How do I pay my VA debt?” should be an h2; it’s currently an h3
- [x] “How do I get financial help?” should be an h2; it’s currently an h3
- [x] “How do I dispute a debt?” should be an h2; it’s currently an h3

### Debt details (page)
- [x] Currently the title says "debt debt" 
- [x] Is “Updated on September 18, 2012” in Bitter regular? Looks kinda bold, but could just be me
- [x] Need 8px margin between “Date of first notice”, “Original debt amount”, and “Current balance”
- [x] “On this page” should be h3 utility (Bitter bold 20px); it’s currently h4 (Bitter bold 17px)
- [x] "On this page" links - the arrow icons should be larger
- [x] "On this page" link padding should be increased to 16px on both sides (this is our bad, but an accessibility consideration!)

#### Debt letter history
- [x] Is “Debt letter history” an h2? It looks the same as “Download debt letters” but the latter is an h3. It should be h2
- [x] Padding looks a little funky between “Debt letter history” h2 and “You can view the status or download the letters for this debt.”. Should be 16px
- [x] Padding between “Note: The content of the debt letters below may…” paragraph and the letter history table should be 32px
- [x] Padding between the debt letter history table and “Download debt letters” should be 32px (this was a mistake in the prototype - my bad!)

#### FAQs
- [x] “How do I pay my VA debt” should be h2
- [x] Padding between “How do I pay my VA debt” and “You can pay your debt online, by phone,…” should be 16px
- [x] Padding between the paragraph under “By mail” and “How do I get financial help?” should be 32px

### Download debt letters (page)

![Screen Shot 2020-09-08 at 2.54.08 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/92c3a26f-ab55-48d5-97d3-c14989f9ab61)
- [x] The breadcrumbs are missing
- [x] Should be Home > Mange your VA debt > Current VA debt > Download debt letters
- [x] Is “Download your debt letters, learn your payment…” subtitle in Bitter regular? Looks kinda bold, but could just be me
- [x] The container width for everything on the page looks off compared to the other pages. Looks way too wide. Should be consistent with the other pages
- [x] Missing “Your debt letters” h2 above the letter table
- [x] Is there still work to be done updating the letter file names? Still says “Letter (1)” when I download a letter
- [x] There’s no way for me to tell if it’s in reverse chronological order because all the dates are the same
- [x] The sorting by date and type aren’t working. Was there a limitation preventing us from adding  that feature to the table?
- [x] Padding between the table and “What if I don’t see the letter I’m looking for?” should be 40px
- [x] Content under “What if I don’t see the letter I’m looking for?” is incorrect and is displaying strangely. It should read:
- [x] If you’ve received a letter about a VA debt, but don’t see the letter listed here call the Debt Management Center at 800-827-0648. You can also call the Debt Management Center to get information about your resolved debts.
- [x] For medical copay debt, please go to pay your VA copay bill to learn about your payment options.
- [x] The “Return to your list of debts.” link is missing
- [ ] Table isn’t turning into a list when in mobile-view. Please refer to the responsive table design the eBenefits team uses for the correct styling on mobile

---
## Tasks
- [ ] _Split this ticket into additional tickets as needed (Optional)_
- [ ] _Work with design team to incorporate feedback_
- [ ] _Review incorporated feedback with design team_

## Acceptance Criteria
- [ ] _Feedback has been discussed and incorporated_

**Comment by rileyorr** [comment]
@bradl3yC did you incorporate the feedback from the **Download debt letters** screen? I noticed none of the feedback from that section was checked off so I want to double-check that nothing was missed among my abundance of feedback :)

**Comment by bradl3yC** [comment]
@rileyorr nope - I will move this back to inprogress and get that going
