### ISSUE TITLE
Recalculate bounding box

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13299]
## Issue Description
When search  results are presented, the map often requires the user to zoom to get meaningful information. Informal searches show the default zoom level = 4 which is rather high level. This may results in many locations piled up or absence of street level detail. 

<details>
<summary> Rural example </summary>

![image](https://user-images.githubusercontent.com/55411834/92533493-d4ecfc00-f1ef-11ea-995f-68f64c12c656.png)

</details>

<details>
<summary> Many location example </summary>

![image](https://user-images.githubusercontent.com/55411834/92533662-2bf2d100-f1f0-11ea-8d47-a5b56971a2fc.png)

</details>

We learned from an experiment [#14792](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14792) that the ideal initial zoom level for one facility type may not be ideal for others. We also observed a bug which caused the number of locations displayed on the map to be different than the number of locations on the search results list. See screenshots from the review instance in [the comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14792#issuecomment-713705853)

Fit to bounds was implemented with Mapbox GL but does not completely optimize the map. 

---
## Tasks
- [ ] Recalculate bounding box after the results are delivered
- [ ] Apply to fit to bounds

## Acceptance Criteria
- [ ] Map is optimized based on search results
- [ ] All results are visible within map display
- [ ] Number of results is the same in list and on map
- [ ] Veterans can differentiate between one location and another by viewing map (map pins are not presented in overlapping pile)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
@mmiddaugh will update to reflect fitToBounds functionality
