### ISSUE TITLE
[Design] Review 404 alerts in Debt Letters v2 design

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#13296]
## Issue Description
_With Debt Letters v2 approaching release, the design team needs to review the second iteration to determine where/how 404 alerts will display now that the pages are being broken out._

---
## Tasks
- [x] _Review the Debt Letters v2 UI to determine where the 404 alerts should display_
- [x] _Create a ticket for frontend implementation including documentation for the 404 alerts_

## Acceptance Criteria
- [x] _Designs have been updated for the 404 alerts as needed_
- [x] _A ticket for frontend implementation has been created and linked to this ticket_

**Comment by rebeccawalsh** [comment]
- [x Update the 404s and empty states for the debt list and debt letter table pages.
    - [x] [No current debts](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263630/specification/sitemap?mode=i)
    - [x] [DMC API 404 (can't get current debts)](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263797/specification/sitemap?mode=i) 
    - [x] [No debt letters found](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132264910/specification/sitemap?mode=i)
    - [x] [VBMS API 404 (can't get debt letters)](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263542/specification/sitemap?mode=i)
- [x] [Frontend ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13857)
