### ISSUE TITLE
[Automation] Create system detail pages for VISN-16 so CMS can create Governance drop down association [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13307]
## Issue Description
As a CMS engineer, I need System detail pages created, so I can finalized all governance drop downs to be used in future page creation and stub out of nodes.

---
## Tasks
- [x] _Create new System pages for the following VISN 16 systems
- [x] VA Alexandria health care
- [x] VA Central Arkansas health care
- [x] VA Fayetteville Arkansas health care
- [x] VA Gulf Coast health care
- [x] VA Houston health care
- [x] VA Jackson health care
- [x] VA Shreveport health care
- [x] VA Southeast Louisiana health care

## Acceptance Criteria
_The above system pages are loaded with:
- [x] System name
- [x] Meta title and tag
- [x] Location text & First Location id
- [x] Gov delivery Emergency #
- [x] Gov delivery News
- [x] All available social media URLs
- [x] Menu Location
- [x] Correct URL manually set for use.
