### ISSUE TITLE
[CONTENT] Translate all Legacy VISN 6 Web Pages into New plain language for new VAMC-upgrade [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13303]
## VAMC - Product Outline
[VAMC-upgrade Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)

## High Level User Story/ies
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 19 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## VAMC-Upgrade KPI met with this EPIC
_Total of 3 KPIs are utilized in this EPIC: Reduction of: Word Count, Page, Count, and increase in plain language on page._

- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care

TASKS: See below list of Stories

## Definition of done
- [ ] _All required Web Pages (containing content) have been created for all 8 remaining VISN 19 Health Systems to include:_
* About
* Work with Us
* Jobs and Careers
* Volunteer and donate

- [ ] _Content has been provided to Copy Editor and is in Progress of being input into Drupal
