### ISSUE TITLE
[CONTENT] Translate legacy VA Houston health care web pages to new VAMC-upgrade format [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13320]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Houston VA Medical Center legacy Site](https://www.houston.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-16 Content Folders](https://drive.google.com/drive/folders/1nZGwqeMIgMoPJCjOMIHfUN8edR7GgnOR)
[Analytics Playbook](https://drive.google.com/drive/folders/1jFQJM1NcnIcXsmKu6XhyHoFFCpOYfD9y)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
* Completed Content is written in Word Document format (Template can be found in Google Drive) and is saved referencing Medical Facility Name & Web Page Name in folder of the VA [System] Name_
* The following pages will have to be researched and created using the templates created:
- [x] About
- [x] Work With Us
- [x] Jobs & Careers
- [x]  Volunteer and Donate
*Facility Intros for the following sites:
- [x] 580	Michael E. DeBakey VA Medical Center
- [x] 580BY	Beaumont VA Clinic
- [x] 580BZ	Charles Wilson VA Outpatient Clinic
- [x] 580GC	Galveston County VA Clinic
- [x] 580GD	Conroe VA Clinic
- [x] 580GE	Katy VA Clinic
- [x] 580GF	Lake Jackson VA Clinic
- [x] 580GG	Richmond VA Clinic
- [x] 580GH	Tomball VA Clinic
- [x] 580GJ	Texas City VA Clinic

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing System Name & Page Name_
- [x] Pages have been cross checked by peer content writer for each of the following:
* About
* Work With Us
* Jobs & Careers
* Volunteer and Donate
* Facility Intros.

* Page must be saved in Content folder on Google Drive under Page reference name

**Comment by psanders86** [comment]
Uploaded into Google Drive
