### ISSUE TITLE
[Business Optimization] Create and populate Facility Health Service Playbooks for all VISN-6 Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13321]
## Story
As a PAO stakeholder, I need a easy to use health service and prepare for your visit guide, so I can accurately fill out all the facility health services and facility amenities in an easy format to be loaded in to draft VAMC-upgrade sites.

---
## Tasks
- [ ] _Create updated Facility Health Service playbooks and prepare for your visit documents to send to PAOs for the following:
- [ ] Include the A-Z listing and A-Z index to New Health services information.
VA Asheville health care
- [x] 637	Charles George Department of Veterans Affairs Medical Center
- [x] 637GA	Franklin VA Clinic
- [x] 637GB	Rutherford County VA Clinic
- [x] 637GC	Hickory VA Clinic

VA Durham health care
- [ ] 0??	Blind Rehabilitation Outpatient Clinic (Need to add to VAST)
- [x] 558	Durham VA Medical Center
- [x] 558GA	Greenville VA Clinic
- [x] 558GB	Raleigh VA Clinic
- [x] 558GC	Morehead City VA Clinic
- [x] 558GD	Durham County VA Clinic
- [x] 558GE	Hillandale Road VA Clinic
- [x] 558GF	Wake County VA Clinic
- [x] 558GG	Raleigh III VA Clinic
- [x] 558QA	Brier Creek VA Clinic
- [ ] 0??	Clayton-East Raleigh VA Clinic (Need to add to VAST)

VA Fayetteville Coastal health care
- [x] 565	Fayetteville VA Medical Center
- [x] 565GA	Jacksonville VA Clinic
- [x] 565GC	Wilmington VA Clinic
- [x] 565GD	Hamlet VA Clinic
- [x] 565GE	Robeson County VA Clinic
- [x] 565GF	Goldsboro VA Clinic
- [x] 565GG	Lee County VA Clinic
- [x] 565GH	Brunswick County VA Clinic
- [x] 565GL	Cumberland County VA Clinic
- [x] 565QA	Robeson Street VA Clinic
- [x] 565QD	Raeford Road VA Clinic

VA Hampton health care
- [x] 590	Hampton VA Medical Center
- [x] 590GB	Virginia Beach VA Clinic
- [x] 590GC	Albemarle VA Clinic
- [x] 590GD	Chesapeake VA Clinic

VA Richmond health care
- [x] 652	Hunter Holmes McGuire Hospital
- [x] 652GA	Fredericksburg VA Clinic
- [x] 652GB	Fredericksburg 2 VA Clinic
- [x] 652GE	Charlottesville VA Clinic
- [x] 652GF	Emporia VA Clinic

VA Salem health care
- [x] 658	Salem VA Medical Center
- [x] 658GA	Tazewell VA Clinic
- [x] 658GB	Danville VA Clinic
- [x] 658GC	Lynchburg VA Clinic
- [x] 658GD	Staunton VA Clinic
- [x] 658GE	Wytheville VA Clinic

VA Salisbury health care
- [x] 659	W.G. (Bill) Hefner Salisbury VA Medical Center
- [x] 659BY	Kernersville VA Clinic
- [x] 659BZ	South Charlotte VA Clinic
- [x] 659GA	North Charlotte VA Clinic

## Acceptance Criteria
- [x] FHS Playbook has been created for each System listed above
- [x] Each playbook has tabs for each of the facilities in each system
- [x] Index is laid out by Health services
---
