### ISSUE TITLE
Use redesigned "In this section" button for triggering sidebar on mobile devices across benefit pages

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#13325]
## Issue Description
The VAMC pages (/pittsburgh-health-care) and the Profile 2.0 use a redesigned trigger button for revealing the sidebar on mobile devices. This trigger button contains the text "In this section" and a hamburger icon.

User research shows the design of this trigger button currently in use on benefit pages is ineffective, so we should follow the VAMC pages by switching to the redesigned mobile button.

Relevant thread, https://dsva.slack.com/archives/C52CL1PKQ/p1599589601362100

### Old trigger button
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/61ac9fd6-6aa0-4132-ae90-9f620af311f3)

### New trigger button
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/fff309cb-babd-4f55-8faa-0ea0b866b8c1)

---
## Tasks
- [ ] References to old sidebar button are updated to use the new sidebar button
- [ ] FE pull request merged

## Acceptance Criteria
- [ ] Benefit hub landing pages (eg `/health-care`) and pages within each hub (eg `/health-care/eligibility`) are using the redesigned button.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sshein** [comment]
perfect. Thanks!

**Comment by erikphansen** [comment]
Is this a simple styling change? In Slack is sounded like the behavior would also change (the button will no longer be sticky) which would mean two of the problems described in https://github.com/department-of-veterans-affairs/va.gov-team/issues/8256 would no longer exist.

**Comment by sshein** [comment]
I actually forget if the new styling is meant to be "sticky." I know it's **not** sticky on the pittsburg pages https://www.va.gov/pittsburgh-health-care/ but is that intentional, @rtwell ?

**Comment by sshein** [comment]
oh I just found this in slack
![Screen Shot 2021-01-13 at 1 23 16 PM](https://user-images.githubusercontent.com/3856611/104512093-863ade80-55a2-11eb-904c-1e7dc9ac4e4e.png)

**Comment by erikphansen** [comment]
Okay so I'm just gonna swap the button out. Behavior will remain the same. Which means #8256 will remain valid 👍

**Comment by sshein** [comment]
ok. Maybe you can show myself and @rtwell what it looks like once you swap the visual out and keep it sticky to make sure it's however he imagined it :)

**Comment by erikphansen** [comment]
@brianalloyd Feel free to validate and close when you get a chance!

**Comment by brianalloyd** [comment]
Closing per validation.  Solid work @erikphansen, thanks again for the assist this sprint.
