### ISSUE TITLE
[Business Optimization] Create and populate Facility Health Service Playbooks for all VISN-16 Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13322]
## Story
As a PAO stakeholder, I need a easy to use health service and prepare for your visit guide, so I can accurately fill out all the facility health services and facility amenities in an easy format to be loaded in to draft VAMC-upgrade sites.

---
## Tasks
- [x] _Create updated Facility Health Service playbooks and prepare for your visit documents to send to PAOs for the following:
- [x] Include the A-Z listing and A-Z index to New Health services information.
VA Alexandria health care
- [x] 502	Alexandria VA Medical Center
- [x] 502GA	Jennings VA Clinic
- [x] 502GB	Lafayette VA Clinic
- [x] 502GE	Lake Charles VA Clinic
- [x] 502GF	Fort Polk VA Clinic
- [x] 502GG	Natchitoches VA Clinic
- [x] 502QB	Lafayette Campus B VA Clinic

VA Central Arkansas health care
- [x] 598	John L. McClellan Memorial Veterans' Hospital
- [x] 598A0	Eugene J. Towbin Healthcare Center
- [x] 598GA	Mountain Home VA Clinic
- [x] 598GB	El Dorado VA Clinic
- [x] 598GC	Hot Springs VA Clinic
- [x] 598GD	Mena VA Clinic
- [x] 598GE	Pine Bluff VA Clinic
- [x] 598GF	Searcy VA Clinic
- [x] 598GG	Conway VA Clinic
- [x] 598GH	Russellville VA Clinic

VA Fayetteville Arkansas health care
- [x] 564	Fayetteville VA Medical Center
- [x] 564BY	Gene Taylor Veterans' Outpatient Clinic
- [x] 564GA	Harrison VA Clinic
- [x] 564GB	Fort Smith VA Clinic
- [x] 564GC	Branson VA Clinic
- [x] 564GD	Ozark VA Clinic
- [x] 564GE	Jay VA Clinic
- [x] 564GF	Joplin VA Clinic

VA Gulf Coast health care
- [x] 520	Biloxi VA Medical Center
- [x] 520BZ	Pensacola VA Clinic
- [x] 520GA	Mobile VA Clinic
- [x] 520GB	Panama City Beach VA Clinic
- [x] 520GC	Eglin Air Force Base VA Clinic

VA Houston health care
- [x] 580	Michael E. DeBakey VA Medical Center
- [x] 580BY	Beaumont VA Clinic
- [x] 580BZ	Charles Wilson VA Outpatient Clinic
- [x] 580GC	Galveston County VA Clinic
- [x] 580GD	Conroe VA Clinic
- [x] 580GE	Katy VA Clinic
- [x] 580GF	Lake Jackson VA Clinic
- [x] 580GG	Richmond VA Clinic
- [x] 580GH	Tomball VA Clinic
- [x] 580GJ	Texas City VA Clinic

VA Jackson health care
- [x] 586	G.V. (Sonny) Montgomery VA Medical Center
- [x] 586GA	Kosciusko VA Clinic
- [x] 586GB	Meridian VA Clinic
- [x] 586GC	Greenville VA Clinic
- [x] 586GD	Hattiesburg VA Clinic
- [x] 586GE	Natchez VA Clinic
- [x] 586GF	Columbus VA Clinic
- [x] 586GG	McComb VA Clinic

VA Shreveport health care
- [x] 667	Overton Brooks Veterans' Administration Medical Center
- [x] 0704V	Shreveport, LA Veterans Service Center
- [x] 667GA	Texarkana VA Clinic
- [x] 667GB	Monroe VA Clinic
- [x] 667GC	Longview VA Clinic
- [x] 667QA	Knight Street VA Clinic
 

VA Southeast Louisiana health care
- [x] 629	New Orleans VA Medical Center
- [x] 629	New Orleans Veterans Medical Center
- [x] 629BY	Baton Rouge VA Clinic
- [x] 629GA	Houma VA Clinic
- [x] 629GB	Hammond VA Clinic
- [x] 629GC	Slidell VA Clinic
- [x] 629GD	St. John VA Clinic
- [x] 629GE	Franklin VA Clinic
- [x] 629GF	Bogalusa VA Clinic

## Acceptance Criteria
- [x] FHS Playbook has been created for each System listed above
- [x] Each playbook has tabs for each of the facilities in each system
- [x] Index is laid out by Health services
---

**Comment by ltrombley** [comment]
Task complete, pending reply regarding Index.
