### ISSUE TITLE
[PM] Schedule and conduct Go/No-go

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13326]
## Background
Schedule Go/No Go for the week of 9/14 once Erik is back

## Tasks
- [x]  Conduct go/no go for Profile 2.0
- [x] Notify Micking/Tressa of the Go/No-go date
- [x]  Ensure everything is ready to go and their are no outstanding issues or potential blockers
