### ISSUE TITLE
Explore Google translate code & capabilities

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13324]
## Issue Description
We want to better understand how to integrate the Google translate widget and options for customizing.

**Questions to start:**

- Can we add widget at the page level (we believe this is no problem)?
- Can we choose to translate only into one specific language (Spanish)?
- Can we customize the button?
- Will we have any ability to edit the translated content?

---
## Tasks
- [x] Sign up via Google to get access to widget 
- [ ] Review widget instructions

## Acceptance Criteria
- [ ] TBD
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @batemapf @mchelen-gov Following up on our conversations re: the widget, here's what I received from Google when I signed up for access:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/7c0c910a-7ae5-4579-b4f7-14215038189c)

**Comment by batemapf** [comment]
Got it, thanks @DanielleThierryUSDSVA. If you recall when you signed up, did you have provide specific domains where the widget was going to be used? Or is that something you can configure on translate.google.com?

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf It asked for domain of website.

**Comment by batemapf** [comment]
Got it, noting for future debugging if needed. Hopefully it treats `staging.va.gov` and `dev.va.gov` the same as just `www.va.gov` (it should...but you never know...).

**Comment by mchelen-gov** [comment]
@DanielleThierryUSDSVA Are you interested in testing this on https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ ?
Also wondering if you learned more about the "Improve translation" feature

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mchelen. Yes, we definitely need to test. I have a ticket for that, but put it on hold due to resourcing. Do you have time to help out with that? I just recently found out that the PW team is getting an engineer on 10/5 who I can pull in to help with this, so if not I can wait until then. Thanks! 

Kelson and I explored the widget a bit. We can customize the language we want to show (so we can set for Spanish only for now) and the presentation and placement, but we can't improve the translation with the widget. The API offers more capabilities around training the machine translation, etc., but that would be a next step. 

So for now, I'm working on assessing the quality of the widget translation so we can optimize the English version as much as possible.

Widget is definitely not the long-term vision. So as we move forward on the widget, I'm also working on write-ups around the broader issue (ie, quality, different approach options) so we can continue exploring along with our VHA partners. Will post a link to that when it's ready.

**Comment by DanielleThierryUSDSVA** [comment]
Update: It looks like there may be a way to edit w/ widget. Will need to explore further.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @brianalloyd @youngfreezyVA. This is the first issue that Fareez and I can work together on re: localization.  Fareez, I look forward to bringing you up to speed on this effort and working with you on this!

**Comment by youngfreezyVA** [comment]
agreed! let's sync up on this tomorrow.

**Comment by mchelen-gov** [comment]
has this been resolved or moved someplace else? if it's resolved, what was the outcome?

**Comment by youngfreezyVA** [comment]
@mchelen-gov i accidentally closed it, sorry about that!

**Comment by mchelen-gov** [comment]
@youngfreezyVA np! was wondering if any more info was found about how to edit / customize translation with translate widget?

**Comment by DanielleThierryUSDSVA** [comment]
hi @mchelen-gov. as we've been looking into the options more, we're thinking we should move away from the widget in general. one reason is that we want to have the spanish page have a unique url so it's findable via search. this will help us gather analytics to inform next steps.

i think we can go ahead and close this ticket now. 

Here are a couple of tickets with @youngfreezyVA's work with toggle and google api to check out: 

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15728

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15970 

also, fysa - i just added you to #localization-mvp slack channel. thanks!
