### ISSUE TITLE
Write and send out GovDelivery email with recent style guide updates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#13333]
## Issue Description
We need to send out a GovDelivery email to inform everyone of the newest style guide updates. These currently include:
- Fourth Mission added to word list
- Bold text topic added
- Aria labels for phone numbers added as subtopic
- Updates to the error messaging dictionary

## Tasks
- [x] Draft GovDelivery email (Randi)
- [x] Review email (Jen/Beth/Danielle)
- [x] Send out email (Randi)

## Acceptance Criteria
- [x] GovDelivery email is sent

**Comment by RLHecht** [comment]
@jenniferlee-dsva @bethpottsVADEPO @DanielleThierryUSDSVA I wrote a new GovDelivery email and sent you each a test copy for your input. Please let me know if you didn't get it.

**Comment by jenniferlee-dsva** [comment]
replied via email

**Comment by RLHecht** [comment]
Update 9/22: Danielle reviewed the coronavirus section and I made all updates. One link isn't working so she reached out to Lauren to ask about it. Going to carry this over to the next sprint. FYSA @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Has Lauren gotten back to you on the COVID link that isn't working in this?

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Ah, apologies. I think I dropped this one. On it now!

**Comment by RLHecht** [comment]
Email was sent out 10/6. Closing ticket.
