### ISSUE TITLE
Write test case for deleted forms

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13331]
## Issue Description
When a user clicks an outdated link, or returns to a saved bookmark to a form that has been removed from the VA forms database, they should be presented with an informative message as described in issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/11625 rather than a generic "not found".  

---
## Tasks
- [x] Create a test case for deleted forms in TestRail - see **https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&group_id=187**

## Acceptance Criteria
- [x] Deleted forms test case will be written
- [x] Deleted forms test case will be used to in a manual test for a use case in which a form has been deleted

**Comment by MarciMcGuireGCIO** [comment]
@MickinSahni - might you have some background on this issue?  Appears to be a placeholder, but not sure what it's meant to capture.  Thx! 
cc: @johnhashva

**Comment by MarciMcGuireGCIO** [comment]
There needs to be a test case written for deleted forms. https://dsvavsp.testrail.io/index.php?/cases/view/3951&group_by=cases:section_id&group_order=asc&group_id=824
