### ISSUE TITLE
[EPIC] VSA Auth Experience - Pact setup

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#13336]
### High level user story/ies
As a VFS team, I need to test the integration between the FE and BE of the app I am developing, so that I do not introduce bugs into production & so that I understand the impact that global site changes will have on my app. 

As a VSP team, I need to get feedback from VFS on our Pact setup and documentation, so that I can fill gaps in our setup and training before rolling this tool out to all teams.

### Description
This ticket represents the body of work for completing setup of integration testing (using Pact) for a given app on VA.gov. This work is being completed in collaboration with VSP FE & BE Tools as part of VSP’s phased rollout of Pact. 

VFS teams will be introduced to the new Pact framework as part of an effort to better the end-to-end testing between vets-website and vets-api. As part of this process, VFS teams will be given a link to the [developer pact documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/integration-testing/how-to-use-pact-for-integration-testing.md). 

Note: following VSP's full release of Pact (ETA late September 2020), Pact tests will be required for new apps, no matter if they introduce new or utilize existing endpoints, to ensure confidence that apps are not broken when changes are introduced. 

### Guidelines for feedback meeting
VFS team: please attend the scheduled VFS <> VSP feedback session with the following questions in mind. No need to prepare anything in advance, but this is what we'll be reviewing (draft! specific Qs subject to change. There will also be plenty of time for open discussion.)

- What questions do you have for VSP about Pact integration testing, how to set it up, etc? 
- When you were working on setting up Pact for your app, what was confusing to you? Were any parts of the documentation unclear? 
- (If you got Pact set up and verified on broker already) how long did it take you to set up Pact for your app? 
- Overall, how would you describe the experience of setting up Pact for your app? 
- VSP will soon require that all new UIs on VA.gov, and new endpoint integrations set up Pact. Do you have any feedback on that policy? 

### Steps to complete this ticket 
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/integration-testing/how-to-use-pact-for-integration-testing.md) is sent to VFS team
- [x] VFS team read through Pact documentation
   - [x] Note questions/points of confusion/feedback on documentation as you go
- [ ] PACT is implemented for VFS team product(s)
- [x] FE code changes/contracts pushed to broker
- [x] BE implements provider states and configurations
- [ ] VFS team's Pacts are [verified on broker](https://vagov-pact-broker.herokuapp.com/)
- [ ] VFS team meets with VSP team for questions and feedback (re: Pact and documentation) 

AE Tickets
- [x] [FE] - Write Pact test #14233
- [x] [BE] - Setup Pact test #14234
- [x] Meet with Platform team to discuss Pact work #13790

**Comment by meganhkelley** [comment]
Converted this back to an issue & added full implementation details here. Closed associated (now redundant) issues.

**Comment by meganhkelley** [comment]
Documentation added above: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/integration-testing/how-to-use-pact-for-integration-testing.md

**Comment by Samara-Strauss** [comment]
@erikphansen @sanlouise @lihanli please review this ticket when you have a chance, and let @meganhkelley know if you have any questions (let's thread here instead of Slack). If there's a lot of confusion, we can coordinate a meeting with Megan to discuss.

cc/ @mshea0606

**Comment by Samara-Strauss** [comment]
Next steps:

- Schedule a review with the platform team for next Thursday or Friday (October 1 or 2).
- Erik/Sandra to regroup with Lihan

**Comment by mshea0606** [comment]
@mshea0606 split into smaller tickets and assign estimates

**Comment by meganhkelley** [comment]
Feedback/troubleshooting meeting held on 10/9. Notes: https://dsva.slack.com/files/T03FECE8V/F01BWESQ4CF?origin_team=T03FECE8V
