### ISSUE TITLE
[Discovery] Technical approach for more scalable Cerner roll-out

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13347]
## Tasks
- [ ] Meet internally to discuss roll-out requirements
- [ ] Document answers here and/or markdown 
- [ ] Create follow-on implementation tickets as needed

## Acceptance Criteria
- Confirm expectations of next Cerner facility roll-out

## Timeline
- discovery and start implementation (sprint 31, ending 10/6)
- complete implementation (sprint 32, ending 10/20)
- roll-out (10/24)

## Questions
- confirm this is a phased roll-out of Cerner pages (appts, Rx refills, secure messaging, etc.) through Cerner facilities i.e. not every facility has the same pages turned on at the same time
  - Impact: tbd
   - Flipper, Auth exp, VAOS, facility look-up table
   - **Decision** this is a full Cerner roll-out for this particular facility (Spokane)
- Does each facility need separate feature toggling?
- What's the probability next Cerner facilities will be partial vs. full roll-outs?
  - Unknown. Chalmers was outlier bc it was one of 3 facilities that doesn't use online scheduling. 
- As we build the logic for future rollouts, how flexible will the roll-out plans be? (Question for Lauren)

**Comment by ncksllvn** [comment]
@MickinSahni What is the date that Cerner is planning to integrate into the next facility?

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA just told me this morning that the next one is planned for October 24th! 😬 Not sure yet which facility + facilityID CC @jbalboni @sanlouise @erikphansen

**Comment by kelsonic** [comment]
We have a meeting to discuss scalable implementation strategies tomorrow morning at 8:30am MST, will post outcomes here! 🙂

**Comment by erikphansen** [comment]
Can I be a fly on the wall at that meeting?

**Comment by DanielleThierryUSDSVA** [comment]
Absolutely, @erikphansen! I'll add you to the invite.

**Comment by kelsonic** [comment]
Takeaways from this morning's meeting:

1. @DanielleThierryUSDSVA to confirm that the next Cerner facility releases will be **staged** (e.g. Chalmers only went live on the https://www.va.gov/health-care/schedule-view-va-appointments page, not the other Cerner pages. Our hypothesis is that other Cerner facilities will release to only some of the Cerner pages at a time).
2. If Cerner facility releases will be staged, create a ticket to add a Cerner lookup table keyed off by `facilityID` in `vets-website` that maintains what Cerner pages each Cerner facility has enabled. Modify current feature toggle for Chalmers to be more broad (e.g. `cernerPagesEnabled` or something like that) or remove it altogether.
3. If Cerner facility releases won't be staged, create a ticket to make it so that Chalmers is the only exception with their staged release. (I don't find this very probable so I haven't thought this through as much, so it might require further discussion on what we want to do)

CC @brianalloyd @MickinSahni @ncksllvn @erikphansen @jbalboni

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic @ncksllvn. Updates below:

- Mann-Grandstaff will be transitioning to My VA Health (Cerner) across the following pages: 
  - [Refill prescriptions](https://www.va.gov/health-care/refill-track-prescriptions/)
  - [Secure messaging](https://www.va.gov/health-care/secure-messaging/)
  - [Schedule appointments](https://www.va.gov/health-care/schedule-view-va-appointments/)
  - [View lab and test results](https://www.va.gov/health-care/view-test-and-lab-results/)
  - [Get your VA medical records online](https://www.va.gov/health-care/get-medical-records/)

- We should assume that future facilities will also transition to My VA Health across all tools at the same time (like Mann-Grandstaff and _not_ like Chalmers).

- After Mann-Grandstaff, the anticipated date for the next facility is January 2021. At this time, Chalmers will likely also transition to My VA Health across all health tools. Lauren will share the latest roll out schedule as soon as she has it.

CC @brianalloyd @MickinSahni @erikphansen @jbalboni

**Comment by kelsonic** [comment]
Perfect, thanks @DanielleThierryUSDSVA for the update! So this means we'll need a ticket to make it so that Chalmers is the only exception with their staged release since Mann Grandstaff + future facilities will be wanting all Cerner pages at once as they go live.

**Comment by kelsonic** [comment]
Boilerplate ticket created and put in Ready column: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14203

CC @MickinSahni @brianalloyd

**Comment by MickinSahni** [comment]
Closing as implementation ticket is captured in #14203
