### ISSUE TITLE
[Discovery] - Create conversation guide for IRIS contact center authoring, initial convo

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13342]
Complete the conversation guide for our first round of calls with IRIS contact center folks

## Tasks
- [x] _Create conversation guide_
- [ ] _Review conversation guide with team_
- [ ] _Update based on feedback_
- [x] _Add guide to GH_

## Acceptance Criteria
- [ ] Conversation guide created and uploaded to GH

**Comment by andaleliz** [comment]
@jenniferlee-dsva [Here's my conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/contact-center-interview-1-conversation-guide.md) for the calls starting next week.  I think the most important chunk for you to review is where I set the stage for why we are meeting.  Let me know if I'm misspeaking here.

>I've invited you here today to better understand content processes in the context of your contact center's customer service, and IRIS content creation.  My hope is that by the end of this hour together we'll have an understanding of 
- who participates in content creation on your team, 
- get a high-level overview of the process, and 
- identify individuals we can speak to more in-depth during a second round of interviews.
 
> Since IRIS content will eventually be published in the learning center, it's important that we take your workflows and processes into consideration so we can support you moving forward.

**Comment by jenniferlee-dsva** [comment]
Hi Liz - See edits/clarifications here: https://github.com/department-of-veterans-affairs/va.gov-team/commit/418189a2b09de2ff8c15877a3c1ee017755e714a#diff-24eb916ab54397c95c8aa98e79455ae3

One thing I want to add - we've never gotten a super clear answer on how content is maintained in IRIS. (And in fact, that's an assumption we've made, so we need them to validate that.) The one thing that we do know for sure is that IRIS is used as a ticketing system for web email inquiries. (Ticketing is used by the contact center reps, not the content teams.)

**Comment by jenniferlee-dsva** [comment]
I want to make sure we are not closing the door during this first touch point for an observational based round 2. I understand you want to go in without a set plan, but it is really important to me as the business and to VEO and DEPO to actually validate what this user journey is like in real time, and preferably via recording of a screen share.

**Comment by andaleliz** [comment]
Hi Jen, thank you! I really appreciate the clarifications, and will update our research questions in the plan accordingly (that'll help w/ synthesis).

I'll also add some notes to the convo guide to ensure it better reflects my intention to ask about our observational round of research. Thanks for reiterating how important this is to you - I'm confident we can get a better understanding of this journey  through this research.
