### ISSUE TITLE
PPMS response analysis

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13356]
# Issue description
Following [changes to the PPMS query](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7782), we are prepared to look at the impact of parameters in the response. 

## Tasks
- Perform analysis on the data elements included/necessary in the response to understand the impact of these parameters on performance. 

## Acceptance Criteria
- [ ] Document impact of response parameters on performance. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**
