### ISSUE TITLE
Add counter to PPMS queries

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13353]
## Issue Description
Since we know the biggest performance impact is from the second query which is required to determine provider type for naming, we need to evaluate the number of providers requiring this logic

---

## Tasks
- [ ] Add counter to group/solo provider query

## Acceptance Criteria
- [ ] The Facilities team is able to evaluate the number of providers which require the naming logic

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
We will also need to add unit tests to the provider model, which adds significantly more work to this item. As it is not a high priority for the sprint, moving it back to ready.

**Comment by mmiddaugh** [comment]
No longer needed now that we have a single query
