### ISSUE TITLE
Wizard migration - UX deliverables for disability flow

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13378]
Create hi-fi mock-ups and documentation based on Mikki's [disability wizard flow](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31?wid=0-1599585553758)

**Outstanding questions**
- Is our proposed change to the wizard behavior feasible? Wizard is skipped only when sent to new form after completing it.  Once you navigate away, you will need to repeat the wizard. 
- Should this page get a skip link?
- What is the difference in content needed across all of the education forms?

**Tasks**
- [x] Create hi-fi for `/introduction` page
   - any variations between mobile/desktop need to be considered?
   - include skip link if appropriate
   - include examples showing messaging indicated which form the user will be directed to
- [x] Create hi-fi for subsequent view when user is on the 526 form, showing subway map
   - Add content/link to "start over"
   - Provide guidance/visuals for interaction going between views
- [x] Create hi-fi for subsequent view when user is on the BDD form, showing subway map
   - Add content/link to "start over"
   - Provide guidance/visuals for interaction going between views

**Comment by andaleliz** [comment]
Per Robin, via Slack, re whether or not to put a skip link on the BDD page:
>We also have the user enter a separation date for BDD, but it's not as essential since they have a chance to enter it on a their military history page. The wizard would prefill it for them.

**Comment by andaleliz** [comment]
@johnhashva @peggygannon @mnorthuis Here's a prototype for the disability form wizard flow. I know there are some pending changes/questions about the integration with HLR, so I left off any scenario including the question `What’s the date of VA’s decision?`

1. [Start screen](https://preview.uxpin.com/e8c5c39f8978d9c1a3f9bd200db25376170a6860#/pages/133183067/simulate/sitemap?mode=i) (wizard start)
2. Wizard outcome to [apply to 526ez](https://preview.uxpin.com/e8c5c39f8978d9c1a3f9bd200db25376170a6860#/pages/133183066/simulate/sitemap?mode=i) for a Veteran's new claim or worsening condition.
3. Wizard outcome if [eligible for BDD](https://preview.uxpin.com/e8c5c39f8978d9c1a3f9bd200db25376170a6860#/pages/133183065/simulate/sitemap?mode=i), using [copy from VSP content review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12248#issuecomment-689865584)
4. Wizard outcome if [more than 180 days from discharge](https://preview.uxpin.com/e8c5c39f8978d9c1a3f9bd200db25376170a6860#/pages/133183064/simulate/sitemap?mode=i), using copy from VSP content review (same as above)
5. [Intro (step list) page for 526](https://preview.uxpin.com/e8c5c39f8978d9c1a3f9bd200db25376170a6860#/pages/133183063/simulate/sitemap?mode=i)
6. [ Intro (step list) page for BDD](https://preview.uxpin.com/e8c5c39f8978d9c1a3f9bd200db25376170a6860#/pages/133183062/simulate/sitemap?mode=i)

**Pending items**
- Any flows including the question `What’s the date of VA’s decision?`
- Link to benefit hub under CTA on 2nd screen above (Apply online with VA from 22-526EZ)
- If copy from VSP content review has changed, need updated copy

@kevinstachura  is going to tackle the HLR mock-up/flow, so I / we need to coordinate anything moving from the disability wizard to HLR wizard with him.

**Comment by andaleliz** [comment]
@peggygannon and @mnorthuis, can you please review [this prototype](https://preview.uxpin.com/e8c5c39f8978d9c1a3f9bd200db25376170a6860#/pages/133183067/simulate/no-panels?mode=i) and let me know if any changes are required? I believe this reflects the latest content document, and I just updated the `h1` elements on the intro pages.

I _think_ any outstanding questions with HLR will be addressed via that effort w/ Kevin.

If everything looks good, I'll close this out.

**Comment by peggygannon** [comment]
Thanks, @andaleliz!  a couple of things from me now that I see the content in prototype form. Thank you for updating the H1s. :

1. For the BDD flow 1 {if between 180-90 days} the alert should say "a disability claim" vs. disability compensation

{alert} Based on your separation date, you can file a disability claim under the Benefits Delivery at Discharge (BDD) program. 
[Learn more about the BDD program](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/)
{CTA button} File a BDD disability claim 
{end alert} 


2. For BDD flow 3  {if less than 90 days out}, it looks like the separation date needs to be updated to **Nov 7 2020**

3. Now that I see it in prototype, I think we should add "online" to the CTA buttons, so users better understand that this button take them to online option (and the link under the button, take them to "other ways" to apply. 

{cta button} File a disability claim online
{cta button} File a BDD disability claim online

4. Also.  I think we should swap positions of this content, so the eligibility link comes first and "Answer questions" come right above the questions. 

Not sure you’re eligible for VA disability benefits? [Find out if you’re eligible for disability compensation] (https://www.va.gov/disability/eligibility/)

Answer a few questions to get started.

**Comment by andaleliz** [comment]
Nice catch on the date, and great suggestions @peggygannon! I'll make these updates.  

Question on flow 1:
>{alert} Based on your separation date, you can file a disability claim under the Benefits Delivery at Discharge (BDD) program.
Learn more about the BDD program
{CTA button} File a BDD disability claim
{end alert}

Should I remove the "Learn about other ways you can file a disability claim" link currently under the button?
![image](https://user-images.githubusercontent.com/55992116/96757108-fe7a7500-13a2-11eb-8695-11c7ba6b2402.png)

**Comment by peggygannon** [comment]
hi, @andaleliz Yes, I think you can remove that link under the button, as we have a link to "Learn more about the BDD program".

**Comment by mnorthuis** [comment]
I'm curious if we can actually change the breadcrumb and H1 between the general comp claim and the BDD claim?  Technically it is the same form, so we may want to check with them on that.  This is different than education where each scenario is a separate form.

**Comment by andaleliz** [comment]
@mnorthuis I modeled those after what is available in staging.  Who is the "them" I should check with?  Thanks!

**Comment by mnorthuis** [comment]
If its available in staging, then I guess that answers my question :-)!  Carry on!

**Comment by andaleliz** [comment]
Sounds good! Will close this out - thanks all :)

**Comment by mnorthuis** [comment]
The breadcrumb does have a typo on the BDD intro page.  It should be "Benefits **Delivery** at Discharge".
