### ISSUE TITLE
Wizard migration - create consistent alerts, and provide messaging to indicate where the user is going across wizards

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13379]
Currently, our wizard pattern doesn't tell people where they're being routed.  This makes it hard for people to know where to go back to if they navigate away from wherever the wizard sent them.

The alert patterns being used across the wizards is also inconsistent. How can we remedy this?

We need to tell users where the wizard is sending them, and do it consistently.  

Consider UX on desktop and mobile!

**Tasks**

- [x] create info pattern
- [x] create warning pattern
- [x] are there other scenarios?
- [x] review w/ Mikki, Peggy
- [x] submit for design intent review update
- [ ] submit for design system adoption consideration?

**Comment by peggygannon** [comment]
@andaleliz document below shows screenshots for current messaging on Edu wizard. will drop in disability BDD next.... 

[https://app.zenhub.com/files/133843125/5c60d43f-cbff-458b-a17b-6c8a36a8294d/download](https://app.zenhub.com/files/133843125/5c60d43f-cbff-458b-a17b-6c8a36a8294d/download)

**Comment by andaleliz** [comment]
Reached out to VSA UX design team to review, since this impacts multiple products and other designs have reviewed this in the past. Asked them to provide feedback by 1pm tomorrow, with the hope I can make any tweaks and submit for design intent review ASAP.

@mnorthuis I know you'll just be getting back from PTO, but would love to get your input on this too. I'll wait for your review before submitting for design intent.   [Here's a link](https://preview.uxpin.com/66480d02dbf9bd2fc54639b82281d17911d89e6d#/pages/132759132/documentation/no-panels?mode=i) to the prototype, which has 5 mobile screens and 1 desktop.  This doesn't include all of Peggy's final content, so please keep that in mind.  I'm looking for feedback on the alert inside the wizard, not the questions or surrounding content (that'll be addressed later). I included documentation to provide context into the use cases the examples represent, and my general thought process about the design choices I made. 

I synced with Peggy on these and she felt this is a good direction to go. She'll be working on paring down a lot of the copy.

**Comment by andaleliz** [comment]
this has been submitted into the design intent review queue. Not going to submit for adoption into design system until we can test with users.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/14104
