### ISSUE TITLE
[Design] - MVP Caregiver, Medical Coverage Screen Redesign 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#13387]
## Issue Description
As part of the October 1, 2020 updates to the 10-10CG, the Caregiver program team is requesting that questions are removed from the _Health care coverage_ page. 

---
## Tasks
- [X] Remove intro sentence 
- [X] Remove questions: Medicaid, Medicare, Tricare, CHAMPVA
- [X] Rework content and question, _Is the Primary Family Caregiver enrolled in health care insurance?_
- [X] Update designs

## Current design
![Caregiver health coverage](https://user-images.githubusercontent.com/58444931/93106704-40165280-f676-11ea-917f-1563398afaa8.png)

## Updated design
![Caregiver-health coverage-update](https://user-images.githubusercontent.com/58444931/93106911-879cde80-f676-11ea-9ccd-4e9b176ce307.png)

For awareness
 
[InVision link ](https://vsateams.invisionapp.com/share/U4YJL36QA35#/431576923_Caregiver_Health_Coverage_)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
Updated with desired content: 

<img width="436" alt="Screen Shot 2020-09-23 at 12 25 45 PM" src="https://user-images.githubusercontent.com/58444931/94047632-f3c6c300-fd97-11ea-95f7-8abea3e362a1.png">

For awareness: [Mockups](https://vsateams.invisionapp.com/share/XBYROF0SC3U#/431613300_Caregiver_Health_Coverage_)
