### ISSUE TITLE
[Design] - 10-10 EZ Address Project 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#13389]
## Issue Description

Ask: Collect mailing address and residential address on the 10-10EZ 

Problem: Currently business only collects one address, but if mailing address and residential are different business needs both because they determine VAMC and benefits based on residential and notifications based on mailing. Currently today business is forced to do manual follow-ups to clarify.

Business requirements: both fields should be filled out regardless, so if they are the same ideally we autofill the second field for them

_Create designs to collect both mailing and home address on the 10-10EZ_

## Tasks
- [x] _Design intent_
- [x] _Revisions/Show to team_
- [ ] Align with Content_ 
- [ ] Alert after submission if address do not match_ 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
Current wire flows can be seen here: [10-10EZ - Address Addition 2.0.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5271547/10-10EZ.-.Address.Addition.2.0.pdf)

- Need to update flows for Authenticated - Mailing and Home complete in Profile (but different/same to have radio options. 

- Some kind of alert after submission if

**Comment by jonathanjnelson** [comment]
[Mockups can be seen here](https://vsateams.invisionapp.com/share/NJYZ5YSYF8Q#/433719998_Unathenticated-Blank_-v-2-1)
