### ISSUE TITLE
Wizard migration - UX deliverables for Chap 31 and Chap 36

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13381]
Create hi-fi mock-ups and documentation based on Mikki's [chap 36](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31?wid=0-1599586518589) and [chap 31](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31?wid=0-1599601365658) flows.

I'm not sure what development/design stage these are in, my mock-ups may not be necessary (documentation would suffice).

**Outstanding questions**
- Do these wizards have outcomes where a user is guided to another form, or is it just eligible/not eligible?
- Do they get a skip link?

**Tasks**
- [ ] Create hi-fi for `/introduction` page for Chap 36
   - include skip link if appropriate
   - include examples showing messaging indicating the outcome
- [ ] Create hi-fi for subsequent view when user is on the Chap 36 form, showing subway map
   - Add content/link to "start over"
   - Provide guidance/visuals for interaction going between views
- [ ] Create hi-fi for `/introduction` page for Chap 31
   - include skip link if appropriate
   - include examples showing messaging indicating the outcome
- [ ] Create hi-fi for subsequent view when user is on the Chap 31 form, showing subway map
   - Add content/link to "start over"
   - Provide guidance/visuals for interaction going between views

**Comment by andaleliz** [comment]
Checking w/ Jim to see if he wants to work on this or if I should.

**Comment by FranECross** [comment]
Closing as obsolete; new tickets will be created if needed.
