### ISSUE TITLE
Resolve Form Detail Page Urls 

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13396]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

### Reference
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/11155#issuecomment-687399670
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/11155#issuecomment-690347457

---
## Tasks
- [x] Determine URLs for Spanish form
- [x] Publish forms with new URL pattern
- [x] Publish 10-10ez form without PDF at end

## Acceptance Criteria
- [x] Correct URLs on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@mnorthuis Could you let us know what the uniform URL will be for Spanish-language forms? Jen thought it would end in -espanol but we wanted you to confirm before we made any changes. For example, the Spanish version of the 10-10ez would be /find-forms/about-form-10-10ez-espanol FYSA @lunascoop

**Comment by jenniferlee-dsva** [comment]
fysa - we won't be able to start stakeholder UAT until these urls are resolved. please slack me as soon as this is okay to share with form stakeholders for UAT.

**Comment by RLHecht** [comment]
These pages have now been published. Will close after today's deployment.

**Comment by RLHecht** [comment]
These pages are now live with the new corrected URLs. Closing ticket. FYSA @jenniferlee-dsva
