### ISSUE TITLE
Staged Rollout for Debt Letters MVP https://www.va.gov/manage-va-debt

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13401]
## Why you're here
Staged Rollout  for Debt Letters MVP with the following treatments: 

![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/f56e1789-fdb2-45ac-8916-8b759c231cf1)

Flipper name - debtLettersShowLetters 

URL https://www.va.gov/manage-va-debt

## Steps to complete intake request

- [ ] Submit this request when VSA Public Website team intervention is required
- [ ] Provide detailed information of your request to help us understand our role in completing your request 
- [ ] Link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry 

__When to submit a request__

- **For apps tool content, landing pages, or engineering support to support new tools:** Please submit your request before your project kicks off so we can provide more effective and collaborative support. If your project has already kicked off, submit your request as soon as possible.

- **For smaller editing needs:** Please submit your request at least **2 weeks** before your targeted launch.  

---

## Background
*Provide a background of your tool/functionality.*

* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
   * < description >
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## Request Type
*Select all applicable and provide details behind your request* 

### Content
- [ ] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * **Word document with draft if available, or link to the URL where the draft content appears:** 
     - < link > 
   * **Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?):** 
     - < design context >
   * **Scope: How many screens? (Or messages, etc.):** 
     - < scope > 
      
      
- [ ] **Content support for a static public website page**
   * **Is this to update existing static content?** 
     - < y/n >
   * **Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.):**  
     - < y/n >
   * **Provide a list of URL/s that need to be reviewed or updated.** 
      * < URL list >
   * **If it's a small copy section, list what the new info should be and what it is replacing.**
      * < list of new info >

### Frontend  
- [ ] **New URL or Redirect Requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA Redirect Request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*

* <Desired/target implementation date>

---

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: *enter name*
- DEPO product owner: *enter name*
- Product manager: *enter name*
- Designer: *enter name*
- FE engineer: *enter name*
- Product/team Slack channel: *enter*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by kelsonic** [comment]
[Given the conversation yesterday](https://dsva.slack.com/archives/C52CL1PKQ/p1599756869413700), it sounds like the only task here is to remove basic auth from the content page https://www.va.gov/manage-va-debt and throttle the redirects to the homepage from the tool landing page which @bradl3yC is doing! 🙂 Going to move this to closed as I don't think you guys need our help anymore. We can always reopen it in the future if something comes up! CC @brianalloyd @MickinSahni @leahkeeler

**Comment by MickinSahni** [comment]
PW intervention is complete. (However, this experience is not set to launch until the new year)
