### ISSUE TITLE
Updating contact info on Schedule an appointment page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13417]
## Issue Description
The contact center is getting calls about appointments, so we want to update the content to address.

---
## Tasks
- [x] Update content in react (Danielle)
- [ ] Review PR (Kelson)

## Acceptance Criteria
- [ ] Content updates live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lenaecb. Tagging you for awareness. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic . Could you review this PR when you have a moment? Let me know if you have any questions. I moved a couple of pieces of content around so there's a high likelihood I missed something in formatting.

https://github.com/department-of-veterans-affairs/vets-website/pull/14301

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lenaecb. Just letting you know this is resolved and published. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Screenshots for validation confirmation:

**Unauthenticated/authenticated no Cerner**
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/75765261-9694-41d9-bdd8-76b0a259de3f)

**Authenticated yes Cerner**
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/eeb98085-8f2f-4ea8-b0fa-0f3d3d68afe6)

FYSA @brianalloyd @MickinSahni
