### ISSUE TITLE
[FE] Updates to Demographics UI

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#13418]
## User Story
As a Veteran, 
I should see a cohesive and accessible demographics page
so I can verify my information. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214c66caff64c73f44ba)

## Description
Update demographics page from research and accessibility

## Tasks
- [ ] remove bolding
- [ ] update mailing and home address labels
- [ ] Update home/moible/work phone number

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Waiting for flaky tests to pass before merging

**Comment by mdewey** [comment]
Merged, waiting ro be deployed to staging

**Comment by abuckley3385** [comment]
how do i get to the demographics page when my form is in progress?  it goes right to the this visit page?

**Comment by kristenmcconnell** [comment]
That is a feature of the save in-progress feature. It jumps you to the last page that you were working on. You will just have to hit the back button.
