### ISSUE TITLE
Design intent Collaboration[Logged-in Homepage]

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#13415]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **Authenticated Experience** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> **requesting team** design intent collaboration meeting completed
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign)
- [LIH timeline and outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md)
![v1 desktop](https://user-images.githubusercontent.com/58752772/93923244-95c6ac80-fcbf-11ea-9385-634f0d876f7b.jpg)
![v2 desktop 1](https://user-images.githubusercontent.com/58752772/93923253-97907000-fcbf-11ea-926d-3044a49a358e.jpg)
![v2 desktop 2](https://user-images.githubusercontent.com/58752772/93923255-98290680-fcbf-11ea-865e-f6f1e2aeb571.jpg)
![v3 desktop](https://user-images.githubusercontent.com/58752772/93923256-98c19d00-fcbf-11ea-9630-ff3b9fa431b2.png)
![v3 mobile 2](https://user-images.githubusercontent.com/58752772/93923258-995a3380-fcbf-11ea-8ccf-c8b8d578d552.png)
![v3 mobile 3](https://user-images.githubusercontent.com/58752772/93923259-995a3380-fcbf-11ea-8359-20586ab01fb5.png)

## Meeting attendees from **requesting team**
- Designer(s) (required): **Tressa Furner, Cassandra Allen**
- Product Manager (optional): **Matt Shea**
- DEPO design lead (required as applicable): **Ryan Thurlwell**

## Scheduling
- We prefer to be scheduled on September 22 at 11 am EST.

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
@tressaellen that time is available for scheduling! Could you make sure to add the sketches/mockups to the ticket by September 17 so that reviewers can review before the meeting?

**Comment by mpeterz** [comment]
I'm filling in for Mikki. Here's the feedback I shared during the meeting:
* Think about how to handle complexities like disability ratings (overall rating + ratings for specific things). For example, is a specific rating related to a specific benefit or group of benefits? 
* Consider integration points like My HealtheVet and (short term) eBenefits. 
* This is exciting work. :)
