### ISSUE TITLE
Content update to NADL page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#13412]
## Issue Description
Per stakeholder Raleigh Contreras, we need to make a content update on the [NADL](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page. 

Their request:

Under **“Why might I want to get a NADL?”** the fourth bullet, we would like to change the fourth bullet:
From: **A low-interest, 30-year fixed mortgage** (a fixed mortgage means your interest rate will stay the same over the full life of the loan)
To: **A low-interest, 30-year fixed mortgage** (a fixed mortgage means your interest rate will stay the same over the full life of the loan). VA is currently originating NADLs at **3%**. Please contact the VA Regional Loan Center for your state to confirm your interest rate and begin your loan application.

Beth will edit for Plain Language and then Randi will copyedit and publish.

Preview: http://preview-prod.vfs.va.gov/preview?nodeId=758

---
## Tasks
- [x] Add new content and edit for Plain Language (Beth)
- [x] Copyedit and publish (Randi)
- [ ] Notify stakeholder of update (Beth)

## Acceptance Criteria
- [x] New content is live on site
---

**Comment by bethpottsVADEPO** [comment]
**Update:** Send PL edits to Raleigh for review on 9/15. Waiting to hear back if the following gets a thumbs up:

The current VA interest rate for NADLs starts at 3%. You can contact your state’s VA Regional Loan Center to find out what your interest rate will be and to get help starting your loan application.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I got approval from the SME on my PL edits/rewriting. I've input the edits and it's ready for your copyedit. Please set to publish when you're done!

**Comment by RLHecht** [comment]
This page has been reviewed and published. Will validate later this afternoon when live on the site. FYSA @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
This is now live. @bethpottsVADEPO you can let the stakeholder know it's up there if you haven't already. Closing ticket. FYSA @MickinSahni @brianalloyd
