### ISSUE TITLE
Edit address before letter download

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13460]
## User Story
As a user, I can confirm or edit my address before downloading any letter.

## Tasks
- [ ] Any necessary optimizations to endpoints are determined and discussed with team
- [ ] Any necessary optimizations are made in vets-api 
- [ ] Endpoints are tested
- [ ] Endpoints are documented 
- [ ] Hand off to frontend

## Prototype
[Link to screens](https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427927553)

**Comment by srmyers17** [comment]
Need to confirm this will update in Vet360.

**Comment by srmyers17** [comment]
- This will leverage the address work that is @kreek is working on as part of the Profile implementation.

**Comment by jperk51** [comment]
After researching letters, it turns out this will just use the existing user address update and is pulled in by a deeper backend service so no work is required for this inside mobile letters.
