### ISSUE TITLE
Express Care Appointment

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13466]
## User Story

As a user, I can see the following information for any confirmed upcoming Express Care appointment:
- Date, time, and time zone
- Appointment status
- Appointment type (VA, Community Care, Express Card, VA Video Connect)
- [???]
- [???]

## Tasks
- [ ] Determine what data points are available and decide which ones to include
- [ ] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Android
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

## Notes
- Need access to a test account that has an upcoming Express Care appointment
- What is the timeline for Express Care appointments being confirmed after they're requested?

**Comment by srmyers17** [comment]
Notes from 9/14 call with Lenae (VAOS):
- Essentially Express Care is an appt request
- One of the stages, is someone actually booking
- Are we showing only booked appointments vs. appointment requests
- Only 1 VAMC has this enabled
- Piloted in SF then Wilmington, from this they will see how VAMCs are using this
- Call back w/in hr is the standard they want to keep; will require business process changes
