### ISSUE TITLE
Appointments overview screen

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13463]
## User Story
- [ ] As a user, I can see all my confirmed upcoming appointments and my past appointments. 
- [ ] As a user, if I don't have any appointments, I see a screen with that message.
- [ ] As a user, I see a message explaining the scope of Appointments features within the app. 

## Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Prototype
- [Appointments overview screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432442341)
- [Appointments overview screen (viewing past appointments)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432457679)
- [Appointments overview screen (user has no appointments)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432581200)

#### Title formula in list view: 
Line 1: **[Day], [Month X, XXXX]**
Line 2: **[00:00 p.m. E.T.]** Note: the time zone will pull from the API and match the VA Medical Center's time zone

#### Subtitle formula in list view: 
- For VA Appointments: **Title of the VA Facility**
- For Community Care Appointments: **Community Care Facility Name**
- For VA Video Connect Appointments: **VA Video Connect at a VA location, VA Video Connect using a VA device, VA Video Connect at an ATLAS location, or VA Video Connect at home**

#### Canceled appointments
- If an upcoming or past appointment has been canceled, it should still display in the overview list and display the status as 'Canceled'. 
- Upcoming appointments that have been canceled should stay in the upcoming appointments list view. 

#### On the 'past' state of the Appointments Overview screen, users should be able to filter their view by 3-month chunks like this:
  - Past 3 months
  - April - June 2020
  - Jan. 2020 - March 2020
  - Oct. 2019 - Dec. 2019
  - All of 2020

This echos the current design of VAOS on VA.gov. These filters should dynamically update based on the month.

**Screenshot of filtering on VAOS:** 
![Screen Shot 2020-09-23 at 5.54.44 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/3965af6a-b40e-4da2-84d2-911ebd740b28)

**Comment by srmyers17** [comment]
Will require working w/VAOS and Ryan

**Comment by bridgethapner** [comment]
A couple of changes from today's check-in with Ryan: 
1. Call out specific appointment type (e.g. VA Video Connect at home) in list view
2. Include Community Care practice area rather than "Community Care" for CC appointments

**Comment by bridgethapner** [comment]
- Put time on another line, remove comma 
- Finalize filtering after talking to Jeff
- Next steps: talk to FED team about the pagination effort, perhaps create another ticket for the backlog
