### ISSUE TITLE
VAVC Appointment

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13465]
## User Story

**Note: There are 4 different types of VAVC Appointments.** 

----

### VAVC appointment at home

As a user, I can see the following information for any confirmed upcoming **VAVC appointment at home**: 
- Appointment type (VA Video Connect at home)
- Date, time, and time zone
- CTA to add the appointment to my calendar
- Instructions for joining the virtual session'
- CTA to join the virtual session (This should only display within 30 minutes before the appointment. Earlier than that, replace CTA with text reading "You'll be able to join your session from your mobile device") 
- Help link "Prepare for video visit" (click to view informational text on a subsequent screen) 
- Message to cancel on VA.gov (click to visit VA.gov)

As a user, I can see the following information for any canceled **VAVC appointment at home**: 
- Appointment type (VA Video Connect at home)
- Appointment stats (Canceled)
- Date, time, and time zone
- Message to call VA or visit VA.gov to make a new appointment 

#### Wireframes - VAVC appointment at home
- [VAVC appointment at home](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432775466)
- [VAVC appointment at home (Canceled)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432868109) 

----

### VAVC appointments at an ATLAS location

As a user, I can see the following information for any confirmed upcoming **VAVC appointments at an ATLAS location**:  
- Appointment type (VA Video Connect at an ATLAS location)
- Date, time, and time zone
- CTA to add the appointment to my calendar
- Instructions for joining the appointment
- Facility address
- CTA to get directions to the facility (opens location in default Maps app)
- Appointment code & joining instructions
- Message to cancel on VA.gov (click to visit VA.gov)

As a user, I can see the following information for any canceled **VAVC appointments at an ATLAS location**: 
- Appointment type (VA Video Connect at an ATLAS location)
- Date, time, and time zone
- Appointment stats (Canceled)
- Facility address
- CTA to get directions to the facility (opens location in default Maps app)
- Message to call VA or visit VA.gov to make a new appointment 

#### Wireframes - VA Video Connect at an ATLAS location
- [VA Video Connect at an ATLAS location](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204195)
- [VA Video Connect at an ATLAS location (Canceled)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204197) 

----

### VA Video Connect at a VA location

As a user, I can see the following information for any confirmed upcoming **VA Video Connect at a VA location**:  
- Appointment type (VA Video Connect at a VA location)
- Date, time, and time zone
- CTA to add the appointment to my calendar
- Instructions for joining the appointment
- Provider name
- Clinic name, VA Facility name, Address
- CTA to get directions to the facility (opens location in default Maps app)
- CTA to call facility (click to call) 
- Message to cancel on VA.gov or call (click to call, click to visit VA.gov)

As a user, I can see the following information for any canceled **VA Video Connect at a VA location**: 
- Appointment type (VA Video Connect at a VA location)
- Date, time, and time zone
- Appointment stats (Canceled)
- Provider name
- Clinic name, VA Facility name, Address
- CTA to get directions to the facility (opens location in default Maps app)
- CTA to call facility (click to call) 
- Message to call VA or visit VA.gov to make a new appointment 

#### Wireframes - VA Video Connect at a VA location
- [VA Video Connect at a VA location](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204498)
- [VA Video Connect at a VA location (Canceled)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204500) 

----

### VA Video Connect using a VA device 

As a user, I can see the following information for any confirmed upcoming **VA Video Connect using a VA device**:  
- Appointment type (VA Video Connect using a VA device)
- Date, time, and time zone
- CTA to add the appointment to my calendar
- Instructions for joining the appointment
- Message to cancel on VA.gov (click to visit VA.gov)

As a user, I can see the following information for any canceled **VA Video Connect using a VA device**: 
- Appointment type (VA Video Connect using a VA device)
- Date, time, and time zone
- Appointment status (Canceled)
- Message to call VA or visit VA.gov to make a new appointment

#### Wireframes - VA Video Connect using a VA device
- [VA Video Connect using a VA device](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433303803)
- [VA Video Connect using a VA device (Canceled)](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433303805) 

----

## Tasks
- [x] Identify information for the screens 
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

**Comment by srmyers17** [comment]
Notes from 9/14 Call with Lenae (VAOS): 

Types of VAVC Appointments:
1. Change appt to VAMC (eg, due to COVID)
2. Group video appointments
3. Virtual appointments while at VAMC with another VAMC
4. Atlas site: Veterans w/o internet access can go to VFW, Walmart, etc to have a virtual appt there
