### ISSUE TITLE
Veterans Crisis Line

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13462]
## User Story
Users can: 
- Launch their phone app to call the VCL 
- Launch their phone app to call the VCL (+TTY) 
- Launch their texting app to text VCL 
- Link to VCL website 

## Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Prototype
- [Link to screen design](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432348084)

## Other documentation
- The CTAs to call should launch the user's phone app
- The CTA to text should launch the user's messaging app
- The link to confidential chat is: https://www.veteranscrisisline.net/get-help/chat
- The link to more resources is: https://www.veteranscrisisline.net/
- Since this screen is reachable only from in-page CTAs and accessible from the unauthenticated home screen, we should not display the bottom navigation here.
