### ISSUE TITLE
Community Care Appointment

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13473]
## User Story
As a user, I can see the following information for any **confirmed upcoming Community Care appointment**: 
- Appointment type (Community Care)
- Date, time, and time zone
- CTA to add the appointment to my calendar
- Community Care facility name and address
- CTA to get directions to the facility (opens location in default Maps app)
- CTA to call facility (click to call) 
- Special instructions
- Message to cancel on VA.gov or call (click to call, click to visit VA.gov)

As a user, I can see the following information for any **canceled upcoming Community Care appointment**:
- Appointment type (Community Care)
- Date, time, and time zone
- Community Care facility name and address
- CTA to get directions to the facility (opens location in default Maps app)
- CTA to call facility (click to call) 
- Message to call VA or visit VA.gov to make a new appointment 

## Tasks
- [x] Determine what data points are available and decide which ones to include (fields selected in 9/29 work session with Ryan)
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Wireframes
- [Upcoming Community Care appointment](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433202201)
- [Canceled Community Care appointment](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433202203)
