### ISSUE TITLE
Build FE Template for Content Type: Images 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#13499]
### Issue Description
Given CMS templates have been built for the "Multiple Q/A" component
I want to begin building the FE template so that this component is successfully used on VA.gov
Separating these into three separate ticket based on content type component. i.e. checklist, video, images.

### The CMS templates for this ticket:
Images (Related CMS ticket #2453 )

### Tasks 
- [ ] What work is necessary for this story to be completed?

### Acceptance Criteria
- [ ] This layer of the FE template (meat layer) is complete for this content type
- [ ] Needs to groom, review and estimate

### Design

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-Media-list.png

**Comment by kelsonic** [comment]
I have all the info we need from the CMS to build this:

![image](https://user-images.githubusercontent.com/12773166/93498028-79e19600-f8ce-11ea-8109-b67706590631.png)

However, it's not super clear to me how we should go about implementing:

1. Pagination, and 
2. Search functionality

You can see them here in the [design spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-Media-list.png):

![image](https://user-images.githubusercontent.com/12773166/93498141-98e02800-f8ce-11ea-8091-23d5e8e4b61c.png)

![image](https://user-images.githubusercontent.com/12773166/93498163-a09fcc80-f8ce-11ea-9778-09e15f365bd0.png)

CC @MickinSahni @brianalloyd @ncksllvn

**Comment by jenniferlee-dsva** [comment]
@kelsonic - LMK if this helps:

Pagination, and  `This should use the normal pagination component that we currently use - kind of the way we do pagination for videos. For images, it would be: 'Show pagination when more than 10 images.'`

~Search functionality~  `You can ignore the image search. The design spec above is outdated and we are not launching 1.0 or 1.1 with article level filtering/searching. `

**Comment by kelsonic** [comment]
PR merged and ready for validation 🎉 🚀

**Comment by ncksllvn** [comment]
To be clear, this is a very barebones not-even-MVP implementation. It's basically just scaffolding so we can have a starting point going forward. I would almost describe the acceptance criteria for this as "As a content author, I can successfully preview pages of the  "Media List - Images" content type."

**Comment by kelsonic** [comment]
PR can be validated here: http://preview-staging.vfs.va.gov/preview?nodeId=6954

Closing as AC were completed! 🎉
