### ISSUE TITLE
Build FE template for content type: Video

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#13498]
### **Issue Description**
Given CMS templates have been built for the "Multiple Q/A" component
I want to begin building the FE template so that this component is successfully used on VA.gov
Separating these into three separate ticket based on content type component. i.e. checklist, video, images. 

### The CMS templates for this ticket:

Videos (Related CMS ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2454)

### **Tasks**

- [ ] What work is necessary for this story to be completed?

### Acceptance Criteria
- [ ] This layer of the FE template (meat layer) is complete for this content type
- [ ] Need to groom, review and estimate 

### Design

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-Media-list-Video.png

**Comment by kelsonic** [comment]
Hmm, we seem to be missing the `length` for videos, which is present in the [design spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-Media-list-Video.png):

![image](https://user-images.githubusercontent.com/12773166/93496985-21f65f80-f8cd-11ea-83e7-cd33ffa17311.png)

![image](https://user-images.githubusercontent.com/12773166/93496959-19058e00-f8cd-11ea-9f79-f21002d3c721.png)

Who should I ask on the CMS side for this do you think @ncksllvn @MickinSahni? 🙂

**Comment by jenniferlee-dsva** [comment]
@kelsonic The video title, video blurb , video length and the publication date stamp should all be pulled from the YouTube source. I'm not sure if the CMS is pulling those in and then passing onto the FE though. You could validate  in the learning center channel with Oksana or Steve Wirt.

**Comment by ncksllvn** [comment]
We need to adjust the video sources for the various YouTube links. I'm getting a security that says the browser refuses to display the YouTube videos as they stand now. We need to use the "embed" links.

Example embed link -> `https://www.youtube.com/embed/Z1ttkv9oRI4`
Links that do _not_ work -> We have a link to `https://youtu.be/GdoqPObM8dg` which is a shortcut to  `https://www.youtube.com/watch?v=9bSkspOd_uo&feature=youtu.be`. This produces a security error.

![image](https://user-images.githubusercontent.com/1915775/93821941-610a1500-fc2d-11ea-931d-f156a9272e07.png)

**Comment by ncksllvn** [comment]
Per the associated [CMS ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2454#issuecomment-672880268) -

> The duration, date and description are maintained by YouTube.

This means that this iteration on the template will be very barebones and implement those additional properties at a later date.

**Comment by kelsonic** [comment]
PR validated here: http://preview-staging.vfs.va.gov/preview?nodeId=6950

Moving to closed! 🎉
