### ISSUE TITLE
WIP and pending pact features

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#13503]
## Issue Description
When verifying pacts, the verification task can be configured to include all "work in progress" pacts (as well as by tag, like master or prod). This allows any new pacts to be automatically verified without the provider team having to make configuration changes. When using this feature, it is best to also turn on the pending pacts feature, so that any failures caused by the WIP pacts do not cause the build to fail.

---
## Tasks
- [x] Configure the pact helper/verification task to use the WIP pacts feature
- [x] Configure the pact helper/verification task to use the pending pacts feature
- [x] Update the pact gem to 1.53.0 or higher
- [x] 1 or more pacts with the consumer tag of master exist in the broker

## Acceptance Criteria
- [x] Verification tasks pass in CI
- [x] Pacts are pushed to the broker with the Consumer version tag of master

**Comment by LindseySaari** [comment]
https://docs.pact.io/implementation_guides/ruby/verifying_pacts/
