### ISSUE TITLE
CT Redesign: Comparison Tool Usability and Redesign

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13502]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/ct-redesign-discovery_product-outline.md)

## High Level User Story
As an Education Development team member, I need to review the Comparison Tool with the appropriate stakeholders and users so that a redesign plan can be proposed that will ensure that the tool meets the needs of the users.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work follows the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Acceptance Criteria
1. A User Centered Design (UCD) readout is created and attached to this story.
2. A Technical proposal for a new GIBCT is created and attached to this story.
3. An initial prototype is create and attached to this story.

## VSP Collaboration Cycle.
- [x] Project Kickoff - #14570
- [x] Design Intent Collaboration - #16546 (open issues attached)
- [x] Usability Testing Prep - #18610
- [x] Research Plan Review - Requested via slack on 2021-01-28
- [x] ~Information Architecture (IA) Request~ Not doing - this is now part of content review (during staging)
- [ ] Analytics Request - #27074
- [ ] Staging Review - #28682
- [ ] Privacy and Security Review - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/316
- [ ] Contact Center Review
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in

## Supporting Artifacts:
1. N/A

**Comment by dneel-bah** [comment]
Closing this story as the work is being transitioned to the Digital GI Bill project.  All information has been #29855 and this issue has been referenced for historical purposes.
