### ISSUE TITLE
Content Request from Community Care Team (CAEC)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#13500]
## Background

The VHA Office of Community Care is launching a new communication portal that will allow Community Providers and veterans to use a public facing website and transmit information over to the VA for processing community care ER notifications/care.

The team responsible for the portal -- Office of Community Care -- would like the VA.gov public websites team to provide guidance as to the possibility/rationale of linking to this new portal through on-site links/CTA's.

Reference link: https://www.va.gov/COMMUNITYCARE/providers/info_EmergencyCare.asp

## Request Type
- VA.gov site cross-links/CTAs request

### Content
- Under consideration:
  - Best Bet/Top Recommendation link
  - Health Care Hub link 

### Desired/target implementation date
* Late September

---

### Requestor info
- Michael Dewey, Program Manager - Clinical and Network Management
- Chris Cox, VHA OCC

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by johnhashva** [comment]
Per @DanielleThierryUSDSVA we will recommend the following to support this portal launch:

- Create a VA.gov Best Bet/Top Recommendation with the following keywords:
  - provider notification
  - emergency care notification

<img width="567" alt="Screen Shot 2020-09-14 at 9 08 19 AM" src="https://user-images.githubusercontent.com/63107147/93119813-752f9e80-f690-11ea-8cc0-b51b7bbdeedc.png">

- Explore/consider a "Not a Veteran?" component for the health care hub page -- but put in our backlog for now due to other priorities.

**Comment by johnhashva** [comment]
Closing because Stakeholders received our recommendations and are satisfied.
