### ISSUE TITLE
Meet with Analytics Team for GA events on View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#13512]
`Attempt to do this asynchronously first, save the meeting`

## Goal
In order to track the success metrics for the View Payments app we need to get Google Analytics events set up that speak to those metrics. So that the analytics team has a chance to establish those event names and what they are for we need to meet with them either in person or over Slack.

## Tasks
- [x] Connect with the GA/Insights Team (over either Slack or Zoom) to share what function and features this product is involved with, and a recommendation for what events they might be interested in tracking.
- [ ] Document what events will be provided by the analytics team

## Acceptance Criteria
- [x] We have connected with the GA/Insights Team 
- [x] We have a document (ticket or otherwise) incoming that has all of the GA events needed for View Payments

### Next steps
-  [ ] Code provided by the GA/Insights Team has been inserted into our feature ([in another ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13513))
