### ISSUE TITLE
Add GA Events to View Payments App

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#13513]
## Goal
Now that we have met with the Google Analytics Team on the View Payments application and they have shared what the event names are going to be for it, we need to insert them into the code.

## Tasks
- [ ] Insert event names into the code for View Payments
- [ ] Submit PR for review

## Acceptance Criteria
- [ ] Code/event names provided by the GA/Insights Team has been inserted into the View Payments app for tracking
- [ ] A PR has been submitted for review

**Comment by jason-gcio** [comment]
Checking with Jon about fail/success load event names

**Comment by jason-gcio** [comment]
Jon has this at the page level
