### ISSUE TITLE
School Ratings: Title Case Research

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13533]
## Tasks
- [x] Discuss approach to Title case with UXBA 
- [x] Investigate research on All caps vs. Title Case  
- [x] Reach out to Liz @ VSP on YR tool to gather additional info 
- [x] Discuss source of data & opportunities to refine w EDU 
- [x] Recommendations for title case 

## Acceptance Criteria: 
1. Recommendations for title case have been made

**Comment by ccruzgra** [comment]
The approach was mentioned during UXBA sync, and it was agreed to bring up the issue with EDU. EDU said they will look into how the data is managed.

**Comment by ccruzgra** [comment]
Mural to capture research: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1600183554382/ad8327db9d3a45a8ea2557c747a3073d84bc6859

**Comment by amyknox** [comment]
From 9/14 EDU mtg re: data source for institution names and locations

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/e00cf3a9-0af4-4d4c-96dc-2bf05f5a0749)

**Comment by amyknox** [comment]
For background, Defect 10511 re: use of all-caps in CT: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10511

**Comment by ccruzgra** [comment]
@JenLJ and I worked on researching all caps and title casing in general, then consolidated findings based on everything we learned.

**Comment by ccruzgra** [comment]
Today we met with Liz to discuss her experience with lettercasing and the Yellow Ribbon Tool. We noted highlights in the research mural.

**Comment by amyknox** [comment]
Met with DEPO designers during office hours.  DEPO designers have strong pro-Title case feelings.

**Comment by ccruzgra** [comment]
Also talked to Trevor Pierce this morning, the VSP accessibility expert, and he advised against all caps for a number of reasons. He had suggestions for how we could handle parts of speech that we don't want capitalized within a school name (the a/an, of).
