### ISSUE TITLE
School Ratings - UX Staging Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13537]
## Tasks
- [x] Review final dev work on staging 
- [x] Report any issues to QA team 
- [x] Work with QA team to resolve to satisfaction
