### ISSUE TITLE
CT Site Search: Enhancements - EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13541]
## Tasks
- [x] Review current round of updates with EDU - Housing allowance (question & functionality) 
- [x] Updated SRP w new button, labels 
- [x] Updated mobile SRP w new button, results on See filters button

**Comment by ccruzgra** [comment]
Reviewed updates with EDU yesterday, 9/14/20.

**Comment by amyknox** [comment]
From EDU 

> No comments or issues with what is in the Additional CT updates document.
> 
> Luke 
> 
> Lucas S. Tickner
> Education Service
>

**Comment by ccruzgra** [comment]
@amyknox This can be closed.
