### ISSUE TITLE
CT Redesign: Discovery Prep

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13556]
## Tasks
- [x] Create outline of Discovery & Design timeline 
- [x] UX Team collaboration to identify key research activities, methods and approach 
- [x] Identify high-priority individuals for initial kick-off interviews

**Comment by ccruzgra** [comment]
Mural for discovery prep: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1600376509169/ef6ddf5aef1fab297cdaa8b800048d8fb4df4ef7

**Comment by amyknox** [comment]
**Another Discovery Prep Mural...** this one specific to UX brainstorming, question identification, ideation

https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1600450361158/9b5a08b206680bbb0d9461d413d203e58467e210  

The Discovery mural Cindy noted above may be used for PI Planning
