### ISSUE TITLE
CT Site Search: Enhancements - UX Staging Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13553]
## Assumptions
-  Pull in when work is on staging

## Tasks
- [ ] Review final dev work on staging 
- [ ] Report any issues to QA team 
- [ ] Work with QA team to resolve to satisfaction
