### ISSUE TITLE
CT Redesign: Research Roundup

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13557]
## Tasks
- [x] Scan past research on CT 
- [x] Identify key findings & requests for new functionality 
- [x] Capture in easy-to-digest format 
- [x] Share with team & discuss

**Comment by amyknox** [comment]
[List of CT research quick hits](https://app.zenhub.com/files/133843125/f0441b23-63ff-4b49-b8cc-76eda7f9683a/download)
