### ISSUE TITLE
Update submit event to merge workflow data for GA on the 686c

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#13560]
# Background
Once the analytics team began testing our submission of the 686c they noticed that we have two separate events firing on submission, one that comes baked in with the form system, and a second custom event that we set up that tells what workflow the user chose at the beginning of the form. The standard practice is to merge our workflow data with the submit event that comes baked in with the form system rather than firing two separate events. We need to adjust the 686c to use the `submitForm` function to merge the workflow data in with the standard form system submission event.

## Considerations
- [Here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/1995/submitForm.js) is an example of how this is being accomplished on the education 1995 form
- [GA's ticket that shows two other changes:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7560#issuecomment-692360454)
  - `Missing - as delimitter`
  - `Add additional - to -submission-successful and -submission-failed`
- [Primary button click event name change](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6830#issuecomment-692690928)
  - `The full event name should be cta-primary-button-click`

## Tasks
- [x] Create a custom `submitForm` event and pass it into the form config file
- [x] Pull the workflow data out of the form data object and merge it with the standard submission event data
- [x] Change the tracking prefix on the 686c form to end with a `-` so that all events match other forms
- [x] Change the event that fires on View Dependents when the green button is clicked
- [x] Test that the events fire as expected
- [x] Submit a PR for review

## Acceptance criteria
- [x] The form submission event is being fired as one event with the workflow data attached
- [x] The SIP and other form events are now prefixed correctly
- [x] The green button on the View Dependents page now fires the event `cta-primary-button-click` 
- [x] A PR has been submitted for review

**Comment by jonwehausen** [comment]
Thanks @cohnjesse and @jason-gcio , going to begin validating these now
