### ISSUE TITLE
Research plan/conversation guide for interviews with community care provider schedulers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13583]
## Issue Description
The Facilities and VAOS teams need better understanding of the process for searching for community care providers to inform the PPMS taxonomy work and to improve the Veteran search experience. We want to understand how and where Community Care Request managers search for type of care/specialties and providers.

## Goals

- Understand the current data & process that a community care request manager uses to process Veteran's community care requests
- Understand/gather feedback (where possible) about the VAOS requests for community care coming into Community Care request manages

## Links to other relevant info
[VAOS Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14658)
[VAOS Training slide deck](https://dsva.slack.com/archives/CMNQT72LX/p1602875896186000)
[VAOS (VA online scheduling)](https://www.va.gov/health-care/schedule-view-va-appointments/)

## Questions to answer:

Based on VAOS specialties (suggest Food/Nutrition/Dietary, Primary Care and Audiology) and non-VAOS specialties (suggest Chiropractor and Dermatology): 

- How does a community care request get processed by Request managers once it is received in Schedule Manager?
   - What are the different systems a Scheduler uses to process a community care request?
- What type of data is a Request manager looking for from a Veteran when processing community care requests?
- What information do you see from the VAOS request? Of that information, what do you use? What is helpful?
- How do you search for type of care/specialities? Where do you search for that data + providers?
   - What words/categories are used by the schedulers when searching?
   - Which specialties are the most commonly searched? Rarely searched? Never searched?
- What search parameters do they use to identify the appropriate community care provider?
   - What are their expectations for search results (such as the number of results and distance/drive time)?
   - What happens if no providers meet the criteria?
- How do they handle naming ( individual provider name vs group practice name)?
- If you could change anything about community care online scheduling through VAOS what would it be?
- If the schedulers are able to share anecdotal experience, we'd love to know what factors are important to a Veteran so that we can present Facility Locator Community care provider search results accordingly.
 
---
## Tasks
- [x] Create research plan and conversation guide to be used in interviews with community care provider schedulers 
- [x] Coordinate with VAOS team

## Acceptance Criteria
- [ ] Research plan and conversation guide are approved by both Facilities and VAOS teams

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrisdlogan** [comment]
URL to research folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/community-care
