### ISSUE TITLE
[CONTENT] Translate legacy VA Southeast Louisiana health care web pages to new VAMC-upgrade format [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13589]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Southeast Louisiana VA Medical Center legacy Site](https://www.neworleans.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-16 Content Folders](https://drive.google.com/drive/folders/1nZGwqeMIgMoPJCjOMIHfUN8edR7GgnOR)
[Analytics Playbook](https://drive.google.com/drive/folders/1jFQJM1NcnIcXsmKu6XhyHoFFCpOYfD9y)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
* Completed Content is written in Word Document format (Template can be found in Google Drive) and is saved referencing Medical Facility Name & Web Page Name in folder of the VA [System] Name_
* The following pages will have to be researched and created using the templates created:
- [x] About
- [x] Work With Us
- [x] Jobs & Careers
- [x]  Volunteer and Donate
* Facility Intros for the following sites:
- [x] 629	New Orleans VA Medical Center
- [x] 629BY	Baton Rouge VA Clinic
- [x] 629GA	Houma VA Clinic
- [x] 629GB	Hammond VA Clinic
- [x] 629GC	Slidell VA Clinic
- [x] 629GD	St. John VA Clinic
- [x] 629GE	Franklin VA Clinic
- [x] 629GF	Bogalusa VA Clinic

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing System Name & Page Name_
- [x] Pages have been cross checked by peer content writer for each of the following:
* About
* Work With Us
* Jobs & Careers
* Volunteer and Donate
* Facility Intros added to additional page and filed.

* Page must be saved in Content folder on Google Drive under Page reference name

**Comment by larrywest52** [comment]
The playbook lists 8 clinices, the legacy site lists only 7. I've used the playbook as the more recent and relevant source, but we'll need to confirm this with the VAMC during our discussion and revise if needed. 

All pages written and sent for cross-check.

**Comment by larrywest52** [comment]
All pages revised and posted to the team's Google Drive as FINAL.
