### ISSUE TITLE
[Business Optimization] Create and populate Facility Health Service Playbooks for all VISN-2 Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13592]
## Story
As a PAO stakeholder, I need a easy to use health service and prepare for your visit guide, so I can accurately fill out all the facility health services and facility amenities in an easy format to be loaded in to draft VAMC-upgrade sites.

---
## Tasks
- [x] _Create updated Facility Health Service playbooks and prepare for your visit documents to send to PAOs for the following:
- [x] Include the A-Z listing and A-Z index to New Health services information.

VA Albany health care
- [x] 528A8	Samuel S. Stratton Department of Veterans Affairs Medical Center
- [x] 528G2	Westport VA Clinic
- [x] 528G3	Bainbridge VA Clinic
- [x] 528G6	Fonda VA Clinic
- [x] 528G7	Catskill VA Clinic
- [x] 528GT	Glens Falls VA Clinic
- [x] 528GV	Plattsburgh VA Clinic
- [x] 528GW	Schenectady VA Clinic
- [x] 528GX	Troy VA Clinic
- [x] 528GY	Clifton Park VA Clinic
- [x] 528GZ	Kingston VA Clinic
- [x] 528QK	Saranac Lake VA Clinic

VA Finger Lakes health care
- [x] 528A5	Canandaigua VA Medical Center
- [x] 528A6	Bath VA Medical Center
- [x] 528G4	Elmira VA Clinic
- [x] 528G8	Wellsville VA Clinic
- [x] 528GE	Rochester VA Clinic (Calkins?)
- [x] 00000	Rochester VA Clinic (Westfall?)
- [ ] 528QC	Clinton Crossings VA Clinic
- [x] 528QE	Coudersport VA Clinic
- [x] 528QF	Wellsboro VA Clinic

VA Syracuse health care
- [x] 0	Auburn VA Clinic
- [x] 528A7	Syracuse VA Medical Center
- [x] 528G9	Tompkins County VA Clinic
- [x] 528GL	Massena VA Clinic
- [x] 528GM	Donald J. Mitchell VA Outpatient Clinic
- [x] 528GN	Binghamton VA Clinic
- [x] 528GO	Watertown VA Clinic
- [x] 528GP	Oswego VA Clinic
- [x] 528QN	Watertown 2 VA Clinic

VA Western New York health care
- [x] 528	Buffalo VA Medical Center
- [x] 528A4	Batavia VA Medical Center
- [x] 528GB	Jamestown VA Clinic
- [x] 528GC	Dunkirk VA Clinic
- [x] 528GD	Niagara Falls VA Clinic
- [x] 528GK	Lockport VA Clinic
- [x] 528GQ	Lackawanna VA Clinic
- [x] 528GQ01	Springville Community Based Outpatient Clinic
- [x] 528GR	Olean VA Clinic

VA Bronx health care
- [x] 526	James J. Peters Department of Veterans Affairs Medical Center
- [x] 526GA	White Plains VA Clinic
- [x] 526GB	Yonkers VA Clinic
- [x] 526GD	Thomas P. Noonan Jr. Department of Veterans Affairs Outpatient Clinic

VA Hudson Valley health care
- [x] 620	Franklin Delano Roosevelt Hospital
- [x] 620A4	Castle Point VA Medical Center
- [x] 620GA	New City VA Clinic
- [x] 620GB	Carmel VA Clinic
- [x] 620GD	Goshen VA Clinic
- [x] 620GE	Port Jervis VA Clinic
- [x] 620GF	Monticello VA Clinic
- [x] 620GG	Poughkeepsie VA Clinic
- [x] 620GH	Eastern Dutchess VA Clinic

VA New Jersey health care
- [x] 561	East Orange VA Medical Center
- [x] 561A4	Lyons VA Medical Center
- [x] 561BZ	James J. Howard Veterans' Outpatient Clinic
- [x] 561GA	Hamilton VA Clinic
- [ ] 561GB	Elizabeth VA Clinic
- [x] 561GD	Hackensack VA Clinic
- [x] 561GE	Jersey City VA Clinic
- [x] 561GF	Piscataway VA Clinic
- [x] 561GH	Morristown VA Clinic
- [x] 561GI	Tinton Falls VA Clinic
- [x] 561GJ	Paterson VA Clinic
- [x] 561GK	Sussex VA Clinic

VA New York Harbor health care
- [x] 630	Manhattan VA Medical Center
- [x] 630A4	Brooklyn VA Medical Center
- [x] 630A5	St. Albans VA Medical Center
- [x] 630GA	Harlem VA Clinic
- [x] 630GB	Staten Island Community VA Clinic

VA Northport health care
- [x] 632	Northport VA Medical Center
- [x] 632GA	East Meadow VA Clinic
- [x] 632HA	Valley Stream VA Clinic
- [x] 632HB	Riverhead VA Clinic
- [x] 632HC	Bay Shore VA Clinic
- [x] 632HD	Patchogue VA Clinic

## Acceptance Criteria
- [x] FHS Playbook has been created for each System listed above
- [x] Each playbook has tabs for each of the facilities in each system
- [x] Index is laid out by Health services

**Comment by ltrombley** [comment]
Removed 463GC Mat-Su VA Clinic from Albany System (VISN-2) as it is located in Alaska.
