### ISSUE TITLE
[Business Optimization] Create and populate Facility Health Service Playbooks for all VISN-23 Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13591]
## Story
As a PAO stakeholder, I need a easy to use health service and prepare for your visit guide, so I can accurately fill out all the facility health services and facility amenities in an easy format to be loaded in to draft VAMC-upgrade sites.

---
## Tasks
- [x] _Create updated Facility Health Service playbooks and prepare for your visit documents to send to PAOs for the following:
- [x] Include the A-Z listing and A-Z index to New Health services information.

VA Black Hills health care
- [x] 568	Fort Meade VA Medical Center
- [x] 568A4	Hot Springs VA Medical Center
- [x] 568GA	Rapid City VA Clinic
- [x] 568GB	Pierre VA Clinic
- [x] 568HA	Newcastle VA Clinic
- [x] 568HB	Gordon VA Clinic
- [x] 568HF	Pine Ridge VA Clinic
- [x] 568HH	Scottsbluff VA Clinic
- [x] 568HJ	Mission VA Clinic
- [x] 568HP	Winner VA Clinic

VA Central Iowa health care
- [x] 636A6	Des Moines VA Medical Center
- [x] 636GC	Mason City VA Clinic
- [x] 636GD	Marshalltown VA Clinic
- [x] 636GK	Fort Dodge VA Clinic
- [x] 636GM	Carroll VA Clinic
- [x] 636GR	Knoxville VA Clinic
- [x] 0       	Des Moines VA Mobile Clinic
- [x] 0       	Fort Dodge North VA Clinic

VA Fargo health care
- [x] 437	Fargo VA Medical Center
- [x] 437GA	Grafton VA Clinic
- [x] 437GB	Bismarck VA Clinic
- [x] 437GC	Fergus Falls VA Clinic
- [x] 437GD	Minot VA Clinic
- [x] 437GE	Bemidji VA Clinic
- [x] 437GF	Williston VA Clinic
- [x] 437GI	Grand Forks VA Clinic
- [x] 437GJ	Dickinson VA Clinic
- [x] 437GK	Jamestown VA Clinic
- [x] 437GL	Devils Lake VA Clinic

VA Iowa City health care
- [ ] 636  (See Nebraska)
- [x] 636A8	Iowa City VA Medical Center
- [x] 636GF	Quad Cities VA Clinic
- [x] 636GG	Quincy VA Clinic
- [x] 636GH	Waterloo VA Clinic
- [x] 636GI	Lane A. Evans VA Community Based Outpatient Clinic
- [x] 636GJ	Dubuque VA Clinic
- [x] 636GN	Cedar Rapids VA Clinic
- [x] 636GS	Ottumwa VA Clinic
- [x] 636GT	Sterling VA Clinic
- [x] 636GU	Decorah VA Clinic
- [x] 636GW	Coralville VA Clinic

VA Minneapolis health care
- [x] 618	Minneapolis VA Medical Center
- [x] 618BY	Twin Ports VA Clinic
- [x] 618GA	St. James VA Clinic
- [x] 618GB	Hibbing VA Clinic
- [x] 618GD	Maplewood VA Clinic
- [x] 618GE	Chippewa Valley VA Clinic
- [x] 618GG	Rochester VA Clinic
- [x] 618GH	Hayward VA Clinic
- [x] 618GI	Northwest Metro VA Clinic
- [x] 618GJ	Shakopee VA Clinic
- [x] 618GK	Albert Lea VA Clinic
- [x] 618GM	Rice Lake VA Clinic
- [x] 618GN	Lyle C. Pearson Community Based Outpatient Clinic
- [x] 618QB	Ely VA Clinic
- [x] 00000	Fort Snelling VA Clinic
- [x] 00000	Minneapolis VA Clinic

VA Nebraska-Western Iowa health care
- [x] 636	Omaha VA Medical Center
- [x] 636A4	Grand Island VA Medical Center
- [x] 636A5	Lincoln VA Clinic
- [x] 636GA	Norfolk VA Clinic
- [x] 636GB	North Platte VA Clinic
- [x] 636GL	Bellevue VA Clinic
- [x] 636GP	Shenandoah VA Clinic
- [x] 636GQ	Holdrege VA Clinic
- [ ] 636GV	O'Neill VA Clinic

VA Sioux Falls health care
- [x] 438	Royal C. Johnson Veterans' Memorial Hospital
- [x] 438GA	Spirit Lake VA Clinic
- [x] 438GC	Sioux City VA Clinic
- [x] 438GD	Aberdeen VA Clinic
- [x] 438GE	Wagner VA Clinic
- [x] 438GF	Watertown VA Clinic

VA St Cloud health care
- [x] 656	St. Cloud VA Medical Center
- [x] 656GA	Brainerd VA Clinic
- [x] 656GB	Montevideo VA Clinic
- [x] 656GC	Max J. Beilke VA Outpatient Clinic

## Acceptance Criteria
- [x] FHS Playbook has been created for each System listed above
- [x] Each playbook has tabs for each of the facilities in each system
- [x] Index is laid out by Health services

**Comment by ltrombley** [comment]
Added Des Moines VA Mobile Clinic, need VAST #
Added Fort Dodge North VA Clinic, need VAST #

**Comment by ltrombley** [comment]
Added Fort Snelling VA Clinic to Minneapolis VA Medical Center, Need get VAST #
