### ISSUE TITLE
[FE] Set up Google Analytics

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#13597]
## User Story

As a development team, 
We would see basic analytics, 
to better fuel our decision. 

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description

Start setting up google analytics. This only setting up the details such as access, data flows, and infrastructure. There will be another ticket for the events. 

## Tasks

- [x] Engage with the analtyics  team 
- [x] set up GA account
- [x] Record 1 event 
- [ ] Determine all events we want to track 

## Acceptance Criteria

- [ ] Team members have access to GA
- [ ] 1 event is being recorded

**Comment by mdewey** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22136

**Comment by mdewey** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1616681971147500

**Comment by mdewey** [comment]
Want to get this PR in staging to test the events and go from there

**Comment by mdewey** [comment]
new tasking: https://dsva.slack.com/archives/CBU0KDSB1/p1617721726370500

**Comment by mdewey** [comment]
created ticket : https://github.com/department-of-veterans-affairs/va.gov-team/issues/22828

**Comment by mdewey** [comment]
Closing this ticket, tracking details now on #22828
