### ISSUE TITLE
[Business Optimization] Create and populate Facility Health Service Playbooks for all VISN-21 Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13590]
## Story
As a PAO stakeholder, I need a easy to use health service and prepare for your visit guide, so I can accurately fill out all the facility health services and facility amenities in an easy format to be loaded in to draft VAMC-upgrade sites.

---
## Tasks
- [x] _Create updated Facility Health Service playbooks and prepare for your visit documents to send to PAOs for the following:
- [x] Include the A-Z listing and A-Z index to New Health services information.

VA Central California health care
- [x] 570	Fresno VA Medical Center
- [x] 570	Fresno VA Medical Center
- [x] 570GA	Merced VA Clinic
- [x] 570GB	Tulare VA Clinic
- [x] 570GC	Oakhurst VA Clinic

VA Northern California health care

- [x] 0	McClellan VA Dental Clinic
- [x] 612A4	Sacramento VA Medical Center
- [x] 612B4	Redding VA Clinic
- [x] 612BY	Oakland VA Clinic
- [x] 612GD	Fairfield VA Clinic
- [x] 612GE	Mare Island VA Clinic
- [x] 612GF	Martinez VA Medical Center
- [x] 612GG	Chico VA Clinic
- [x] 612GH	McClellan VA Clinic
- [x] 612GI	Yuba City VA Clinic
- [x] 612GJ	Yreka VA Clinic
- [x] 612QB	Twenty First Street VA Clinic
- [x] 0	        Sierra Foothills VA Clinic

VA Pacific Islands health care
- [x] 459	Spark M. Matsunaga VA Medical Center
- [x] 459GA	Maui VA Clinic
- [x] 459GB	Hilo VA Clinic
- [x] 459GC	Kailua-Kona VA Clinic
- [x] 459GD	Lihue VA Clinic
- [x] 459GE	Guam VA Clinic
- [x] 459GF	Faleomavaega Eni Fa'aua'a Hunkin VA Clinic
- [x] 459GG	Leeward Oahu VA Clinic
- [x] 459GH	Saipan VA Clinic
- [x] 459QA	Lanai VA Clinic
- [x] 459QB	Molokai VA Clinic

VA Palo Alto health care
- [x] 640	Palo Alto VA Medical Center
- [x] 640A0	Palo Alto VA Medical Center-Menlo Park
- [x] 640A4	Palo Alto VA Medical Center-Livermore
- [x] 640BY	San Jose VA Clinic
- [x] 640GA	Capitola VA Clinic
- [x] 640GB	Sonora VA Clinic
- [x] 640GC	Fremont VA Clinic
- [x] 640HA	Stockton VA Clinic
- [x] 640HB	Modesto VA Clinic
- [x] 640HC	Major General William H. Gourley VA-DoD Outpatient Clinic

VA San Francisco health care
- [x] 662	San Francisco VA Medical Center
- [x] 662GA	Santa Rosa VA Clinic
- [x] 662GC	Eureka VA Clinic
- [x] 662GD	Ukiah VA Clinic
- [x] 662GE	San Bruno VA Clinic
- [x] 662GF	San Francisco VA Clinic
- [x] 662GG	Clearlake VA Clinic

VA Sierra Nevada health care
- [x] 654	Ioannis A. Lougaris Veterans' Administration Medical Center
- [x] 654GB	Carson Valley VA Clinic
- [x] 654GC	Lahontan Valley VA Clinic
- [x] 654GD	Diamond View VA Clinic
- [x] 0       	North Reno VA Clinic

VA Southern Nevada health care
- [x] 0	Mike O'Callaghan Military Medical Center
- [x] 593	North Las Vegas VA Medical Center
- [x] 593GC	Pahrump VA Clinic
- [x] 593GD	Northwest Las Vegas VA Clinic
- [x] 593GE	Southeast Las Vegas VA Clinic
- [x] 593GF	Southwest Las Vegas VA Clinic
- [x] 593GG	Northeast Las Vegas VA Clinic
- [x] 593GH	Master Chief Petty Officer Jesse Dean VA Clinic

## Acceptance Criteria
- [x] FHS Playbook has been created for each System listed above
- [x] Each playbook has tabs for each of the facilities in each system
- [x] Index is laid out by Health services

**Comment by ltrombley** [comment]
Added Sierra Foothills VA Clinic to VA Northern California health care system.

**Comment by ltrombley** [comment]
Added North Reno VA Clinic to VA Sierra Nevada Health Care System - Need VAST #

**Comment by ltrombley** [comment]
Task Complete.  See comments above regarding additions to lists.
