### ISSUE TITLE
IRIS Q&As: Batch 2, Service member benefits

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#13598]
### Issue
For the launch of Learning Center MVP 1.1, service  member benefit content needs to be developed based on the following:

- IRIS service member benefits faqs
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

- [x]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

 - [x] PW to develop draft copy (Laura)

 - [ ] PW to assign tags (Laura)

 - [x] PW to copyedit draft (Randi)

 - [x] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [x] Copy deck ready for DEPO review and attached to a content review GH ticket.

**Comment by lwalsh617** [comment]
@RLHecht -- Only a single faq for this one, ready for your review. 
[lc-mvp-servicemembers-faqs-copy-v0.1-100520.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5330850/lc-mvp-servicemembers-faqs-copy-v0.1-100520.docx)

**Comment by RLHecht** [comment]
@lwalsh617 Here is the the Word doc with my tracked changed. Let me know if you have any questions.
[lc-mvp-servicemembers-faqs-copy-v0.1-100520-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5335333/lc-mvp-servicemembers-faqs-copy-v0.1-100520-RH-edit.docx)

**Comment by RLHecht** [comment]
Closing ticket. Content review being tracked in ticket #14568
