### ISSUE TITLE
Swagger for Health Quest Service

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#13596]
## Tasks
- [ ] Research swagger generation and how other modules/engines swaggers work
- [ ] Generate swagger for the health quest service, make sure it is accessible and can be updated

## Acceptance Criteria
- [ ] The swagger is accessible from vets-api 
- [ ] check the code into the main branch
- [ ] Have M. Dewey review it.

**Comment by dillo** [comment]
Here's the PR that was started by Laurence for the Health Quest swagger docs: https://github.com/department-of-veterans-affairs/vets-api/pull/4937
