### ISSUE TITLE
Make revisions to the 28-8832 (CH36) wizard

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#13605]
## Story
As a Veteran, I want assurance that the 28-8832 is the correct form, so I can apply for career planning and guidance.

### Goal
Quickly address the confusion created by one question in the CH36 wizard. Review and update the CH36 wizard flowchart, prototype, research plan and conversation guide.

### Considerations
Veterans can potentially apply for and receive **both* Chapter 36 and Chapter 31 benefits. The initial draft of the CH36 wizard flow and questions introduced confusion on this point. To quickly address this, a question will be removed and text will be added to help clarify the crossover of CH36 and CH31 eligibility.

### Tasks
- [x] Update all affected deliverables:
    - The text and flow of the CH36 wizard
    - The presentation, copy, flow and functionality of the CH36 prototype
    - The details of the CH36/CH31 research plan and conversation guide

### Acceptance criteria
- [x] All deliverables are updated so users have a path to apply for both CH36 and CH31 benefits.
- [x] Changes are documented in GH and shared with the team.

**Comment by sporeboy** [comment]
Deliverables updated to new wizard flow: 

- [Flowchart](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088565)
- [Prototype](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088565)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-convo-guide.md)
