### ISSUE TITLE
Update Status Messaging for View Payment History Null-data and Error States

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#13600]
## Story
As a Veteran, I want a clear indication if there is no data or an error occurs when I view my VA payment history.

### Goal
Update View Payment History mockups to reflect the latest styling for alerts and messaging. Revise text to be clear and concise, aligning with VA.gov plain language guidance.

### Considerations
Since the View Payment History screens were initially laid-out, design system styling and language and been refined. Null-data and error states for the VPH feature are in active development. Design-debt (and technical debt) will be reduced if current design styling can be implemented.

### Tasks
- [x] Update mockups to reflect current styling for several data and error states: 
     - Data with no payments
     - Data with no returns
     - No data available
     - Error retrieving data

### Acceptance criteria
- [x] View Payment History screens are updated to reflect current messaging/alert styling
- [x] Changes are documented and shared with the Team

**Comment by jason-gcio** [comment]
Referencing the files here: https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/338e991f-d104-4bf4-b040-ced7f18617a0/
