### ISSUE TITLE
Post Women's Quick Start Guide

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13603]
## Issue Description

VEO has asked us to post a new pdf to the https://www.va.gov/welcome-kit/ page. They would like this posted **asap**, but need it posted **by Monday, 9.21 latest**.

### Details for posting

**Placement:** In this section, beneath "Get started with mental health services (PDF)"

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/0d858c2b-060a-48b6-afd3-e02be6e8b2b2)

**Link label:** Get started with health services for women Veterans (PDF)

**Link should be:** va.gov/women-veterans-health-services-quick-start-guide.pdf

**PDF for uploading:** [VAWK_QSG__Women_Veterans_Health_Services_2020_Final_508](https://app.zenhub.com/files/133843125/61386e45-1a28-45e6-8b2d-024fd14698c0/download)

## Details for accessibility
VEO provided the following accessibility compliance reports for us, for our records.

[Women Veteran Health Services Acrobat Accessibility Report](https://app.zenhub.com/files/133843125/a19f5473-21da-4544-81a8-ace93dcfc210/download)

[Women Veterans Health Services CommonLook Compliance Report](https://app.zenhub.com/files/133843125/852b091c-389f-4472-86f0-779f720adcdc/download)

---
## Tasks
- [x] Upload PDF
- [x] Add link to PDF on page
- [x] Validate in preview, set to publish
- [x] Validate on live site

## Acceptance Criteria
- [x] PDF is available on live site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht, could you work with team to get this posted? 

@mnorthuis, I followed the standard for these pdfs for the link (in details section above). Please let me know if you think it needs to change.

@jenstrickland, VEO provided accessibility compliance reports (in details section above) so I think this is set. But please let us know if there are any accessibility issues.  

FYSA @bethpottsVADEPO since I know you're working on auditing pdfs. 
FYSA @MickinSahni @brianalloyd for product management.

Thanks!

**Comment by RLHecht** [comment]
@kelsonic Could you please upload the PDF that's listed at the top of this ticket into the assets folder so I can add it to the Welcome Kit page? Thanks much!

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA Do we generally have assets at the root level or are they organized within an asset type folder somewhere?  I don't what other files we are storing in Drupal at this time and is this something we are planning to continue to do?

**Comment by RLHecht** [comment]
@mnorthuis This is being stored in the Github assets folder: https://github.com/department-of-veterans-affairs/vagov-content/tree/master/assets. We haven't brought any of these over to Drupal yet.

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis Good question. It's an assets folder, but not in Drupal. I was basing url off of the existing ones (ex. https://www.va.gov/mental-health-quick-start-guide.pdf).

**Comment by jenniferlee-dsva** [comment]
As a follow on to this, would be great to start this epic, so we can get out of the business of uploading pdfs for them: [epic #11320. ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11320)

**Comment by kelsonic** [comment]
Added! 🙂 https://github.com/department-of-veterans-affairs/vagov-content/blob/master/assets/women-veterans-health-services-quick-start-guide.pdf

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA this is now on the page. The link won't work until the deploy but you can take a look for placement. preview-prod.vfs.va.gov/preview?nodeId=716.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @RLHecht and @kelsonic ! Looks great.

**Comment by jenstrickland** [comment]
## Accessibility review of PDF

There are two issues to be resolved based on an accessibility check (perhaps there were edits after the VEO generated their report):

1. The first checklist should be properly tagged.

![Screen Shot 2020-09-16 at 12 16 46 PM](https://user-images.githubusercontent.com/57469/93364416-85718600-f816-11ea-9080-48154ea2b29c.png)


2. The number 2 should be properly tagged.
![Screen Shot 2020-09-16 at 12 12 36 PM](https://user-images.githubusercontent.com/57469/93363974-fcf2e580-f815-11ea-9fa1-37ad49c98fd1.png)


## Implementation accessibility guidance

1. The list of downloads **should** be presented using a list `ul`. <br/>_Why it matters:_ Using a paragraph means screen reader users will hear "link, Apply for VA health care (PDF) link, Get started with mental health services (PDF) link, Understanding community care (PDF)…" instead of a list of the links which is cognitively clearer.

1. PDF download links **should** use the [pattern used on VA.gov](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340), ([the PR with more info](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/369)). **This is likely to need a new CMS component.** This file currently downloads as `61386e45-1a28-45e6-8b2d-024fd14698c0.pdf`. <br/>_Why it matters:_ The `download` attribute will provide a user-friendly experience by:
    - providing a file name users will be able to identify as the downloaded file; 
    - the icon will provide a visual cue that this link behavior is different from other links; 
    - the type attribute tells the browser how to handle this link.

### Current page code
```
<p>
	<a href="/health-care-quick-start-guide.pdf">Apply for VA health care (PDF)</a><br>
	<a href="/mental-health-quick-start-guide.pdf">Get started with mental health services (PDF)</a><br>
	<a href="https://www.va.gov/community-care-quick-start-guide.pdf">Understanding community care (PDF)</a><br>
	<a href="https://www.va.gov/urgent-care-quick-start-guide.pdf">Accessing urgent care (PDF)</a><br>
	<a href="/disability-quick-start-guide.pdf">Apply for a disability rating (PDF)</a><br>
	<a href="/education-quick-start-guide.pdf">Apply for education benefits (PDF)</a><br>
	<a href="/burials-and-memorials-guide.pdf">Apply for burial in a VA national cemetery and for memorial products (PDF)</a><br>
	<a href="/decision-reviews-guide.pdf">Understanding the modernized decision review process (PDF)</a>
</p>
```

### Recommended code
```
<ul>
	<li>
	  <a href="/health-care-quick-start-guide.pdf" 
	  	download="Apply for VA health care.pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Apply for VA health care (PDF)
	  </a>
	</li>
	<li>
	  <a href="/mental-health-quick-start-guide.pdf" 
	  	download="Get started with mental health services.pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Get started with mental health services (PDF)
	  </a>
	</li>
	<li>
	  <a href="https://www.va.gov/community-care-quick-start-guide.pdf" 
	  	download="Understanding community care.pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Understanding community care (PDF)
	  </a>
	</li>
	<li>
	  <a href="https://www.va.gov/urgent-care-quick-start-guide.pdf" 
	  	download="Accessing urgent care.pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Accessing urgent care (PDF)
	  </a>
	</li>
	<li>
	  <a href="/disability-quick-start-guide.pdf" 
	  	download="Apply for a disability rating.pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Apply for a disability rating (PDF)
	  </a>
	</li>
	<li>
	  <a href="/education-quick-start-guide.pdf" 
	  	download="Apply for education benefits.pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Apply for education benefits (PDF)
	  </a>
	</li>
	<li>
	  <a href="/burials-and-memorials-guide.pdf" 
	  	download="Apply for burial in a VA national cemetery and for memorial products.pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Apply for burial in a VA national cemetery and for memorial products (PDF)
	  </a>
	</li>
	<li>
	  <a href="/decision-reviews-guide.pdf" 
	  	download="Understanding the modernized decision review process..pdf" 
	  	type="application/pdf">
	  	<i** aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
	  	Understanding the modernized decision review process (PDF)
	  </a>
	</li>
</ul>
```

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jenstrickland. Thank you for your review! VEO has updated the pdf based on your recommendations. Here's the updated version if you don't mind confirming.

[VAWK_QSG__Women_Veterans_Health_Services_2020](https://app.zenhub.com/files/133843125/0279447e-83cf-4852-b08b-71231c15a052/download)

@RLHecht @kelsonic Assuming the pdf is good to go, could we get this in for tomorrow's deploy?

Also, @RLHecht, could you create a ticket re: Jen's implementation accessibility review above to capture that work? Thank you!

**Comment by jenstrickland** [comment]
@DanielleThierryUSDSVA — 👍  The PDF passes an a11y check now.

**Comment by kelsonic** [comment]
You got it, I'll upload it right now, should VAWK_QSG__Women_Veterans_Health_Services_2020 take the place of https://github.com/department-of-veterans-affairs/vagov-content/blob/master/assets/women-veterans-health-services-quick-start-guide.pdf with the name `women-veterans-health-services-quick-start-guide`? 🙂

**Comment by RLHecht** [comment]
Yep, you can replace the old PDF with this new one, @kelsonic .

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @kelsonic @RLHecht @jenstrickland, for being so responsive with this.

**Comment by kelsonic** [comment]
PR is open! https://github.com/department-of-veterans-affairs/vagov-content/pull/720 🙂

**Comment by kelsonic** [comment]
Merged! 🎉 Could you confirm this looks good? https://github.com/department-of-veterans-affairs/vagov-content/blob/master/assets/women-veterans-health-services-quick-start-guide.pdf

**Comment by DanielleThierryUSDSVA** [comment]
Looks great - thank you, @kelsonic!

**Comment by RLHecht** [comment]
Published page. Will validate after tomorrow's deployment. FYSA @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
PDF up on live site. Closing ticket.
