### ISSUE TITLE
[Automation] Create system detail pages for VISN-21 so team can stub out pages [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13613]
## Issue Description
As a Business analyst, I need System detail pages created, so I can finalized owner ship for all detail pages using governance drop downs in creating pages and stubbing out of nodes.

---
## Tasks
_Create System and Operating Status Pages for each of the following systems:
- [x] VA Central California health care
- [x] VA Northern California health care
- [x] VA Pacific Islands health care
- [x] VA Palo Alto health care
- [x] VA San Francisco health care
- [x] VA Sierra Nevada health care
- [x] VA Southern Nevada health care

## Acceptance Criteria
_The above system pages are loaded with:
- [x] System name
- [x] Meta title and tag
- [x] Load media image (if available)
- [x] Location text & First Location id
- [x] Gov delivery Emergency #
- [x] Gov delivery News
- [x] All available social media URLs
- [x] Menu Location
- [x] Correct URL manually set for use.
- [x] Operating status page
