### ISSUE TITLE
[Automation] Create system detail pages for VISN-23 so team can stub out pages [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13614]
## Story
As a Business analyst, I need System detail pages created, so I can finalized owner ship for all detail pages using governance drop downs in creating pages and stubbing out of nodes.

## Tasks
* Create System page and Operating Status page for the each of the below VISN 23 Systems:
- [ ] VA Black Hills health care
- [ ] VA Central Iowa health care
- [ ] VA Fargo health care
- [ ] VA Iowa City health care
- [ ] VA Minneapolis health care
- [ ] VA Nebraska-Western Iowa health care
- [ ] VA Sioux Falls health care
- [ ] VA St Cloud health care

## Acceptance Criteria
_The above system pages are loaded with:
- [ ] System name
- [ ] Meta title and tag
- [ ] Location text & First Location id
- [ ] Gov delivery Emergency #
- [ ] Gov delivery News
- [ ] All available social media URLs
- [ ] Menu Location
- [ ] Correct URL manually set for use.
