### ISSUE TITLE
Fix First Page of CH36 Form Redirecting to `/introduction`

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#13612]
## Background
In the form system when a form is loaded it loads the pages within that specific form. When the first page of the form is dynamic, either shown or hidden based on some condition, the function that loads the pages can often fail. The platform team created a function called `getEligiblePages()` that can run through the pages first and determine what pages are to be shown or hidden, then build a static list of those pages and pass them to the function that loads the pages. This will fix the issue with our form redirecting back to the /introduction page.

## Tasks
- [x] Import `getEligiblePages` from `platform/forms-system/src/js/routing`
- [x] Pass the page list to `getEligiblePages` like [we did on chapter 31](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vre/28-1900/containers/IntroductionPage.jsx)
- [x] Test to ensure fix
- [x] Submit a PR for review

## Acceptance criteria
- [x] The chapter 36 form no longer intermittently redirects back to the `/introduction` page
- [x] A PR has been submitted for review
