### ISSUE TITLE
Revise Copy and Flow of the CH36 Wizard

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13618]
## Background
Given the latest feedback from members supporting our team, we need to revise the wizard so that it maintains clarity and cohesiveness with the other Chapter feature on our roadmap.

## Considerations
- Here is the [XD doc](https://xd.adobe.com/view/879cf230-f3ce-4204-79ba-c3453b0bcc09-f1ad/) that outlines the latest changes
- Removing some branching logic

## Tasks
- [ ] Revise the content and workflow

## Acceptance Criteria
- [ ] The wizard is updated to reflect the latest changes
- [ ] A PR has been requested for merging
