### ISSUE TITLE
[Automation] Create system detail pages for VISN-2 so team can stub out pages [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13615]
## Issue Description
As a Business analyst, I need System detail pages created, so I can finalized owner ship for all detail pages using governance drop downs in creating pages and stubbing out of nodes.

---
## Tasks
- [x] VA Albany health care
- [x] VA Finger Lakes health care
- [ ] VA Syracuse health care
- [ ] VA Western New York health care
- [x] VA Bronx health care
- [x] VA Hudson Valley health care
- [x] VA New Jersey health care
- [ ] VA New York Harbor health care
- [ ] VA Northport health care

## Acceptance Criteria
_The above system pages are loaded with:
- [ ] System name
- [ ] Meta title and tag
- [ ] Location text & First Location id
- [ ] Gov delivery Emergency #
- [ ] Gov delivery News
- [ ] All available social media URLs
- [ ] Menu Location
- [ ] Correct URL manually set for use.
