### ISSUE TITLE
Add Google translate widget to Coronavirus FAQs page (no-production) for testing only

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13619]
## Issue Description
We want to begin working with the Google translate widget on this page to see how it can work and what we can customize for it. 

---
## Tasks
- [ ] Review previous design work on this and check in with Ryan and Jen on designs.
- [ ] Add translate widget to this page, set to non-production. Customize to Spanish only and to match design below if possible.
- [ ] Review functionality and design internally. 

## Acceptance Criteria
- [ ] Widget implemented, set to non-prod
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Placement of language option in original Spanish language MVP for reference.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/a4439919-15db-4492-aacf-a2ae952eb112)

**Comment by DanielleThierryUSDSVA** [comment]
**Update:** Due to capacity issues for PW engineering, looking at DEPO resourcing.

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf Design example above
