### ISSUE TITLE
[UI] [Research] Create MVP Prototype for Research

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#13627]
Delighter for sprint 31.- will pull in if time allows

## Tasks
- [x] Get UX Pin access 
- [x] Create complete [Proof of Concept prototype in Mobile](https://preview.uxpin.com/a15205c1bedcdfc8fe46fed26c22fa731cab8ae0cvhidm)
- [x] Create complete [Proof of Concept prototype in Desktop](https://preview.uxpin.com/e9e0dc597bb076e74db05f77d35306496a89fca2cvhidm)

## Acceptance Criteria
- [x] Prototype/Questions review meeting Pilot (~13th) with product and engineering
- [x] Send prototype link to Lauren Alexanderson to review and approval to proceed with recruiting of participants (update: added to the conversation guide, which was emailed to Lauren on 10/5)
- [x] See Collab Usability Prep Ticket 
- [x] Published to UX Pin

**Comment by kristenmcconnell** [comment]
@abuckley3385 See the above prototype links, which can be added to the Collab Usability Prep Ticket. I still have some refinement to do, but the mobile and desktop prototypes work the whole way through (like the breadcrumbs imported weird, etc). They are set up, so the participant can enter two additional questions. I updated the conversation guide to reflect that and bring it up at the appropriate point during the test.

**Comment by kristenmcconnell** [comment]
VSP Usability Testing Prep occurred on the afternoon of 10/9/2020. Waiting for final feedback from Peggy and Crystalbel to incorporate into the prototype.

**Comment by kristenmcconnell** [comment]
All feedback incorporated into the prototype (except for the new "in case of emergency don't use this form" design within the review page of the desktop prototype). This one small exclusion shouldn't impact our testing feedback. I will incorporate it after testing.
