### ISSUE TITLE
[Ongoing Service] Customer Support Tracking - Logging and Categorization of Support Requests

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#13622]
## Problem Statement 
Without a better understanding of how VSP teams' time is spent on customer support work, it is difficult to identify areas to focus on to make improvements that enable VFS teams to find answers or get unblocked on their own.  We started using a spreadsheet to capture support requests but our research found manually logging Slack requests in the spreadsheet was a pain point for VSP teams.

How might we create an automated process for logging and tagging customer support requests across VSP teams so that we have consistent data to prioritize roadmap initiatives that provide VFS teams the documentation and self-service tools they need while enabling VSP support to scale?

## Hypothesis or Bet
By creating a standardized process for tracking customer support requests across VSP teams, we expect to identify “problem areas” with high burdens of manual support to be prioritized in future VSP initiatives.

## We will know we're done when... ("Definition of Done")
- [ ] Customer support request logging and categorization standards are implemented for all VSP teams.
- [ ] Support requests can be logged by VSP team members in approximately 2 minutes or less (GitHub/Slack integration)

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: `products/platform/customer-support-tracking/`
* **Product Outline**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/customer-support-tracking/product-outline.md
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/customer-support-tracking/product-outline.md
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14613

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by KevinMHoffmanUSDS** [comment]
@jcosta-gcio This looks like a massively beneficial super epic. A few questions: 

> Customer support request logging and tagging standards are implemented for all VSP teams.

How will this account for variances between VSP team types? E.g. some VSP teams are customer facing, some are not. Some VSP teams are Slack based (FE, BE, Ops), others primarily Github based (Analytics, Content and IA) and some are "meeting based" (product support.) Will these tagging standards and logging apply to all of the above, or only certain flavors of support? 

> Support requests can be logged by VSP team members in approximately 2 minutes or less (GitHub/Slack integration)

Same question as above. I just want a better sense of how big of bite of this we are trying to take in the 4th quarter.

**Comment by rebekahickey** [comment]
- Posted October metrics to the Platform [Customer Support Dashboard Reports page in Confluence](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1571323928/Customer+Support+Dashboard+Reports)

**Comment by rebekahickey** [comment]
On 11/10, posted the Platform Slack Customer Support Report for Sprint 64 to the [Platform Customer Support Dashboard Reports page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1571323928/Customer+Support+Dashboard+Reports) and to #platform-team in Slack

**Comment by rebekahickey** [comment]
Posted November metrics to the [Platform Customer Support Dashboard Reports page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1571323928/Customer+Support+Dashboard+Reports) in Confluence

**Comment by rebekahickey** [comment]
On 12/8/21, posted the Platform Slack Customer Support Report for Sprint 66 to the [Platform Customer Support Dashboard Reports page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1571323928/Customer+Support+Dashboard+Reports) and to #platform-team in Slack
