### ISSUE TITLE
Design intent Collaboration - Step-by-step template for Learning Center MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13626]
## Context

Requesting an async review  (per Slack) for some changes I'm proposing to improve mobile UX in the learning center.

This particular ticket is for mobile UX for the `Step-by-Step` template.  [Here's Ryan's desktop design](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b?wid=0-1588252879737). The learning center is leveraging our subway map component, and also giving content authors the new ability of being able to add 1 image per step in the subway map. 

The work I'm asking to be reviewed shows the mobile ux, which essentially boils down to a few key changes:
- reduce left margin on submay map to maximize available width on small screens
- each step in the subway map gets a variation of our additional info component (variation is to remove the blue border)
- placing a `show all` above the list to expand/collapse all steps at once

**Note:** I also have some designs for a responsive table that include another variation of the additional info component, where the blue border is under the button (instead of along side of it), and the expanded content.  Just an FYI as you consider whether or not variations of a component are okay.

## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [ ] Crystabel and Emily to determine how much time reviewers have to provide feedback
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)
- [Mock-ups](https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132512748/documentation/no-panels?mode=i)
  - 2 screens to review at the link above
  - Should open to `documentation` view, where you'll see notes and comments

## Meeting attendees from **requesting team**
Feedback to be provided async.  

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled feedback on 9/21 at 3:30 pm ET. Thanks Liz!

**Comment by andaleliz** [comment]
I'm on PTO Monday, but I thought this was going to be an async review?

**Comment by CrystabelReiter** [comment]
Hey! This will just be when feedback is officially due. I wrote it in the
description

**Comment by CrystabelReiter** [comment]
@andaleliz I just scheduled when the reviewers are required to give feedback so that this is on their radars. Apologize for the confusion

**Comment by andaleliz** [comment]
@CrystabelReiter got it! Thank you - didn't even think to see if the description is updated.

**Comment by mnorthuis** [comment]
No IA-related feedback for this change. Thanks!

**Comment by jenstrickland** [comment]
Since VSA accessibility specialist collaborated extensively with Liz and Ryan on this design, I have no additional feedback at this time. cc @1Copenut for review

**Comment by CrystabelReiter** [comment]
VSP design doesn't have any outstanding feedback to implement:

- The show all/hide all links would be a cool mobile pattern to propose for the subway maps on VA.gov. The Booz Allen team had a similar link style in their GI Bill comparison tool and it tested well
- The additional info component with no blue bar is alright depending on the situation. I found that if the additional info bar nests with other bars the page looks hectic. I’ve seen it without the blue bar in some situations like in the profile and in the hub page: https://www.va.gov/service-member-benefits/)

**Comment by andaleliz** [comment]
@CrystabelReiter thank you!  I'll go ahead and close this out then.

**Comment by 1Copenut** [comment]
@andaleliz Hello there! I've been a bit behind on reviews, and wanted to add two small additions for accessibility / accessible design:

1. The breadcrumbs visually change to a "back by one" at mobile size. So we'd just expect to see "< Learning center" as a blue underlined link on these views.
2. The expand/collapse accordions nested inside the subway map LIs should be tested for semantic HTML and axe validation as early as possible. There should be no issue, but sometimes certain elements upset the axe algorithm when nested.

LMK if you want to discuss either of these points!

**Comment by andaleliz** [comment]
Thanks @1Copenut ! Sorry to close the ticket before you got to comment; I misunderstood Crystabel's comment and thought everyone had provided feedback.

Those are excellent points; updated the mock-up breadcrumbs and passed along point #2 to our FE devs.

**Comment by jenstrickland** [comment]
For clarity, if it isn't in the design documentation, the plan for the expand/collapse pattern is to use the gov.uk implementation as a model. @1Copenut is absolutely correct, that our axe checks should include validation for this — including specific updates in the e2e tests to validate hidden content. As we are in the design intent stage, are we moving to build this next, or finalize designs?  cc @andaleliz

**Comment by andaleliz** [comment]
The documentation does refer to the gov.uk implementation, and this feedback doesn't suggest any changes are needed so this is going on to build, @jenstrickland.
