### ISSUE TITLE
[Development] Include exact text in auto-suggest

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#13639]
## Issue Description

During UAT testing for our BDD form, a Veteran entered a new condition from a prepared list. The condition listed did not exactly match any labels within our internal list of disabilities. The Veteran spent some time trying to search for the exact match, and ended up selecting a condition with extra descriptive text that may not have been related, or intended.

For example, entering `PTSD` would show the following options: `PTSD personal trauma`, `PTSD (post traumatic stress disorder)`, `Post Traumatic Stress Disorder (PTSD) Combat - Mental Disorders` and `Post Traumatic Stress Disorder (PTSD) Personal Trauma - Mental Disorders`; but no plain `PTSD` choice.

This issue is about discovering if it would be necessary and how difficult it would be to add the exact content entered into the input as one of the dropdown choices. There may need to be a minimum character limit before including it.

## Questions

- Would this be a helpful change?
- Should this be behind a specific auto-suggest option setting, since this would be a global change?

## Related issues

UAT testing: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10298

## Tasks

- [ ] Discuss adding option with VSP
- [ ] Determine how much work it would be to add this enhancement

## Acceptance Criteria

- [ ] Have an implementation plan

**Comment by luke-gcio** [comment]
Moving to Sprint 36 - next design committee meeting on Friday Dec 4.

**Comment by CrystabelReiter** [comment]
Final decision from Design System council meeting on 12/4/20:
- We need to look into fuzzy search options
- Short term solution: Clarify in the copy that they can enter their own thing. Close the suggestion box when what they’re typing is not in the list. It should also closes if person pauses typing if enough time passes by 
Related content ticket:  :https://github.com/department-of-veterans-affairs/va.gov-team/issues/16489

**Comment by CrystabelReiter** [comment]
@Mottie Can you add this ticket info as a ticket on the design system issue board? So we can channel into our backlog

**Comment by luke-gcio** [comment]
After reviewing with design council, we decided to not implement this and make content changes instead.
