### ISSUE TITLE
Review and publish stakeholder link update on Burial at Sea page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#13634]
## Issue Description
Stakeholder Brett Lee updated a broken link on the [Burial at Sea](https://www.va.gov/burials-memorials/eligibility/burial-at-sea/) page. The content team needed to review and publish the page in Drupal.

The link that was changed was to "Learn more about the Navy's Burial at Sea program"

## Tasks
- [x] Review Drupal preview link: preview-prod.vfs.va.gov/preview?nodeId=2347 (Randi)
- [x] Publish page (Randi)
- [x] Alert stakeholder of published page (Randi)
- [x] Validate page on live site (Randi)

## Acceptance Criteria
- [x] Link working on live site

**Comment by RLHecht** [comment]
@MickinSahni @brianalloyd This was work that a stakeholder emailed Beth and I about this morning. It was a quick review and I spun up this ticket afterward to track it. I'll close later this afternoon once it's live on the site.

**Comment by brianalloyd** [comment]
Thanks @RLHecht for spinning up a ticket for this. @MickinSahni do we also want to identify this as an "in-take" request?

**Comment by RLHecht** [comment]
This is live on the site. Closing ticket. FYSA @MickinSahni @brianalloyd
