### ISSUE TITLE
[UI] [Research] Research plan and discussion guide for MVP prototype testing

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#13632]
## Tasks
- [x] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/mvp-usability/research-plan.md) and [discussion guide ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/mvp-usability/conversation-guide.md)
- [x] Check to see if Collab cycle Usability Prep meeting is needed and if so we need to PM will schedule 

## Acceptance Criteria
- [x] research materials review with product
- [x] send research materials to Lauren Alexanderson to review and for coordination with participant recruiter

**Comment by kristenmcconnell** [comment]
@abuckley3385 - I checked with Shawna and the VSP Usability Test Prep meeting is needed. I will need to make a prototype. I added some information about possible timelines in my draft Research Plan (drafts linked above).

**Comment by kristenmcconnell** [comment]
I just sent the research plan and conversation guide to Lauren, so I'm closing out this story.
