### ISSUE TITLE
Map contact center data for the Covid dashboard redesign

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13641]
## Issue Description
We need to understand what the data model for contact center will look like with the redesigned Covid dashboard. HMW determine what needs to change, if any, and ensure we're doing so in a way that reduces or maintains manual effort?

---
## Tasks
- [x] Chante: add mapping of contact center topics to overall topics in [Slack request](https://dsva.slack.com/archives/C010AJ1L2EN/p1600189276015200)
- [ ] Determine changes with contact center data input, if any - communicate any changes to Chante
- [ ] Determine any new ETLs for contact center data

## Acceptance Criteria
- [ ] We understand what the contact center data input needs to be for the redesigned Covid Dashboard

**Comment by jonwehausen** [comment]
## Update
- Currently, we have contact center data living in separate tables for each contact center
- We would like to propose to consolidate each of these into 1 single master webform for all COVID-relevant contact centers (IVR, VEO, NCC)
- Please see [this link](https://va-gov.domo.com/datasources/92581ecb-cd1b-4a65-94f6-ade5a00f36f9/details/data/table) for the current mockup
- This structure would give us more flexibility by allowing us to aggregate across dates, call topics, covid topics and limit the amount of locations needing to update weekly call center data
- One caveat here -- **For NCC specifically**, since that data is provided with a weekly range, the `date` column in the dataset here should only be the single start date of the week range

@clantosswett @joanneesteban @amycesal @bsmartin-ep Let us know your thoughts here and we can discuss next steps

**Comment by jonwehausen** [comment]
@Kimberley2019 @clantosswett to QA numbers from individual Contact Center datasets into Master and check for accuracy.

**Comment by clantosswett** [comment]
@jonwehausen where do we stand on this? We did the QA for the contact center data and have been adding new contact center data to the master contact center form.

**Comment by jonwehausen** [comment]
Thanks @clantosswett! Our work here is complete and we can close this.
