### ISSUE TITLE
Iterate on covid dashboard redesign

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13643]
## Issue Description
We have a proposed redesign for the Covid Dashboard. HMW build this out in a usable state on Domo?

---
## Tasks
- [x] Create datasets 
- [x] Dashboards are created & visualized
- [x] Charts are created & visualized
- [x] Data is QA'd
- [ ] Visualization & Content is QA'd

## Acceptance Criteria
- [ ] Overview Page
- [ ] Topics
- [ ] Content
- [ ] Tools
- [ ] Experiments

**Comment by jonwehausen** [comment]
Clean-up areas: 
- [ ] Search data scrubbing and fine-tuning visualization
    - [ ] i.e Adjusting PPE logic to only include ppe as it relates to covid (exclude appeals) 
- [ ] Top pages for covid-pageviews verified 
- [ ]  Adjust mapping of source to say "Chatbot", "FAQ Page", or "Call Center" 
- [ ] Other areas where percent change should be displayed

**Comment by jonwehausen** [comment]
@bsmartin-ep @amycesal @joanneesteban 

The covid research volunteer sign-up form launch yesterday -- we are still waiting for the complete data layer we provided to be implemented, that said the product did launch as of 9/30. 

The [card here](https://va-gov.domo.com/datasources/245eda9d-5cd2-49bd-a604-573ae4b672e0/details/cards) has been staged to show total successful submissions of the form. 

Once visualized -- can be included on the Tool Usage page per design.

**Comment by joanneesteban** [comment]
@jonwehausen @bsmartin-ep 
Another request was around vaccination research. What data do we have around this?

After getting information back from Lauren (will be asking what her goals are for this data), do we have the data we need to provide those goals. We'll need to determine if that data fits in the current dashboarding IA or if it should go into the Exploratory page, and what it should be visualized as.

@amycesal

**Comment by joanneesteban** [comment]
### Vaccination research 

Data Questions:

- How are Veterans finding the vaccination content (either the landing page or the form - i.e. where are they coming from?)
- How many Veterans are coming to the form?
- How many Veterans are compleeting the form?
- What is the % dropoff?

[Data Studio dashboard](https://datastudio.google.com/reporting/2d72fd71-9e1f-4434-87ef-f28d58105e10/page/pyqiB) & [Slack link](https://dsva.slack.com/archives/C010AJ1L2EN/p1601933286008100?thread_ts=1601393662.001400&cid=C010AJ1L2EN).

### VEText

Data Questions:
- How is VEText marketing affecting our digital service usage related to Covid?

[Power BI Dashboard](
https://app.powerbigov.us/groups/me/apps/edb20dd9-adff-4cdb-9e08-35ecc7e2ea94/reports/4cfba121-b0c0-4327-aacc-750900383076/ReportSection2e80d07522783d3cc621) & [JSON](https://vetext-data.r01.med.va.gov/api/IMHSummary)

**Comment by joanneesteban** [comment]
New iterations will have additional tickets opened. Closing this ticket.
