### ISSUE TITLE
Map the BigQuery data model for Covid dashboard data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13640]
## Issue Description
We need a clean way to pull data for the new Covid dashboard redesign. HMW document and map how we'll be pulling this data from BigQuery?

---
## Tasks
- [ ] Create data model
- [ ] Document process for reproduction and debugging
- [ ] ETL data (FAQ<>Topic Mappings)
- [ ] Share with design

## Acceptance Criteria
- [ ] VSP Analytics & Insights understand what data needs to be pulled and how for the Covid Dashboard

**Comment by joanneesteban** [comment]
@joanneesteban reach out to Danielle about FAQ mapping.

**Comment by jonwehausen** [comment]
Per @bsmartin-ep and I's discussion this morning:

## Next Steps
- We will setup a 1-to-1 mapping table of FAQ<>COVID Topic to live in BQ
- This will allow us to then write `JOIN` statements to merge this mapping table with each of our event taxonomies (FAQ clicks, accordions, chatbot, etc)  
- This will shrink the amount of ETLing we need to do to only merge in contact center data

_See #13641 for update on contact center ticket for potential data model improvement_

**Comment by jonwehausen** [comment]
Hi @bsmartin-ep: 

Per our conversation regarding contact center data updates: 
- Rather than have a master webform like [COVID - Contact Center - Master - 2.0](https://va-gov.domo.com/datasources/92581ecb-cd1b-4a65-94f6-ade5a00f36f9/details/data) -- to help speed up the manual update process, let's pivot to allow for Chante to continue to update the old tables as she has been, and we will DOMO ETL into a master output table that mirrors the current "COVID - Contact Center - Master - 2.0" for use on the COVID dashboard
- The tables that should be getting ETL'ed and aggregated as part of this: 
   - COVID - Contact Center - NCC
   - COVID - Contact Center - VEO
   - COVID - Contact Center - IVR My VA311
   - COVID - Contact Center - VCL

**Comment by bsmartin-ep** [comment]
@jonwehausen -

ETL created:
https://va-gov.domo.com/datacenter/dataflows/73/graph

Just NCC, VEO, IVR VA311 as discussed.

OUTPUT:
https://va-gov.domo.com/datasources/6a0e9d9c-7a03-42bd-8e80-c6dd52a08723/details/overview

A few notes:

- I'm using the new Dynamic Unpivot to turn multiple columns into covid_topic and total_calls columns.
- Converting dates like '3-Mar-2020' doesn't seem to be possible with the regular column type tile.  I had to use STR_TO_DATE and DATE with a format string.

How should we QA this?

**Comment by jonwehausen** [comment]
@bsmartin-ep Thanks for this! 

Next steps: 
- Replicate charts on new output dataset
- Thinking we can QA by comparing the output dataset new charts with each respective contact center dataset and ensure covid_topics still align with their respective call topics

**Comment by bsmartin-ep** [comment]
@jonwehausen -

These datasets have been updated to have true DATE columns. I removed the now unused ETLs and OUTPUT tables, and pointed all cards and ETLs to these datasets.  The Contact Center master ETL has been streamlined now that we don't need to convert the dates.

- [Covid - VCL Metrics (Call Center)](https://va-gov.domo.com/datasources/15fb1102-7155-4f51-8874-a6d943928212/details/overview)
- [Covid - My VA311 IVR (Call Centers) 
](https://va-gov.domo.com/datasources/b285c230-896d-49c3-af5f-13f1ebe582fe/details/overview)
