### ISSUE TITLE
Add new charts to Burials allowance page, update rates on existing charts, correct info that's wrong

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#13652]
## Issue Description
This page needs updating: https://www.va.gov/burials-memorials/veterans-burial-allowance/

We need to: 
- Update the rates in the charts on this page based on this source page: https://www.benefits.va.gov/PENSION/resources-burial.asp
- Add a new chart that's missing from the existing page (use the same source page)
- Correct some info in the third chart (use the same source page)

---
## Tasks
- [x] Update the rates on the page. Note: please add missing 2019 info. (Selina)
- [x] Under the horizontal line, the H2 is: Burial allowance amounts. Please add another H2 at the bottom of the page, following the 3 existing charts. New H2: Headstone or marker allowance amounts. Then create a new chart from the info on the source page listed above. (Selina)
- [x] In the third chart, fix the top 3 statuses and their maximum burial allowances. They are all wonky with incorrect info. (Selina)
- [x] Review changes (Randi)

## Acceptance Criteria
- [x] Page is updated with new rates.
- [x] Incorrect info is corrected.
- [x] New chart has been added for headstones and markers.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @RLHecht this page is ready for review. I did add the additional years noted on the legacy page. http://preview-prod.vfs.va.gov/preview?nodeId=864

**Comment by bethpottsVADEPO** [comment]
1/ In the chart for Veterans who were hospitalized by VA at the time of their death, the second row has an incorrect rate, please correct.
2/ The last two rows in this chart have 2 incorrect years, please correct: "What are the burial allowance amounts for a non-service-connected death?"

@lunascoop I neglected to attach the 2020 source page. Doing that here, but please create a separate ticket for doing those 2020 updates, so it can happen on October 1. Thank you.

Also, I'm asking the SME if we should have those additional years added. I'm not sure that's relevant that far back, but will double check and get back to you.[https://app.zenhub.com/files/133843125/9f6bbd04-b549-4aa5-819d-c183571cc834/download](https://app.zenhub.com/files/133843125/9f6bbd04-b549-4aa5-819d-c183571cc834/download)

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. I also created ticket #13787 to update page with Oct 1 2020 allowance amounts.

**Comment by bethpottsVADEPO** [comment]
I'm waiting to hear back from the SME about how far to go back with the rates--how many years back. Hold on publishing please.

**Comment by RLHecht** [comment]
Work completed on this. Closing ticket.
