### ISSUE TITLE
Update caregiver content for 10.1 launch of new regulations & form

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13654]
## Issue Description
We need to update the content on these 2 pages to reflect changes in regulations to support the 10.1 launch of the new 10-10CG form and the start of expanded access and regulations:
https://www.va.gov/family-member-benefits/
https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/

Details of what areas need to change detailed in these 2 pdfs:

[family member benefits page_10.1 changes](https://app.zenhub.com/files/133843125/2189278b-7f0e-4a2f-a571-be36dd1832cd/download)

[caregiver program page_10.1 updates](https://app.zenhub.com/files/133843125/f6b372a8-8064-4e58-a519-e7602f81b9f1/download)

---
## Tasks
- [x] Initial sync with caregiver program team (Danielle)
- [x] Update page & word doc (Danielle)
- [x] Align w/ internal 10-10CG team (Danielle)
- [x] Copy edit word doc (Randi)
- [x] Send to caregiver program team (Danielle)
- [x] Make any final changes and publish (Danielle/Randi)

## Acceptance Criteria
- [x] Updated pages are live on site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht - doc to edit. thank you!
[Caregiver program updates for 10-1-20](https://app.zenhub.com/files/133843125/69188187-2373-4250-9d7c-582df8411f1f/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This copy looks good. I just added a comma after one of the dates listed.
[Caregiver program updates for 10-1-20-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5277852/Caregiver.program.updates.for.10-1-20-RH-edit.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Final content for reference: [Caregiver program page updates for 10-1-20_revised](https://app.zenhub.com/files/133843125/d7b65602-ad56-4ec7-a9d2-95e85df618df/download).

Work completed and published on 10.01.20. Closing issue.
