### ISSUE TITLE
Sentry Integration with Slack and GitHub

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#13665]
## Problem Statement 

Sentry 20 has been released to VSP/VFS teams.  However, the integrations to GitHub or Slack need to be set up and configured for use.  These two integrations are requested by both sides and should be available for use by the teams who want to utilize their functionality.

## Hypothesis or Bet
* By integrating with these two platforms, it will help facilitate the initial investigation and organize alerts.
* By utilizing integrations, it will be one less platform that a team needs to monitor to ensure the platform, or their application is not causing issues.

## We will know we're done when... ("Definition of Done")
* GitHub integration is configured and the relevant repositories are linked and the Sentry teams are syncing with the GitHub teams.
* Slack integration is configured and sentry alerts can be sent to the DSVA slack channels in close to real time.

### Is this service / tool / feature...

Tool

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Error Monitoring
* [**Product Outline**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/error-monitoring/sentry10_product_outline.md)
* [**Design Doc**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2020-06-02-Sentry10.md)
* [**Platform User Guide**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/backend/sentry/vsp-sentry-configuration.md)
* [**VFS User Guide**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-configuration.md)
* **README**: _link to VFS-facing README for your product_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by annaswims** [comment]
For sentry 9 we added a slack id here https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/sentry.conf.py.j2#L282

**Comment by holdenhinkle** [comment]
Check with Jesse about this. Are notifications being sent to Slack? Is this done? Are emails still going out? Emails might be better than Slack.

**Comment by rmtolmach** [comment]
We decided to not move forward with this. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/60254 and [these tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue%20slack%20integration%20sentry%20-label%3Aplatform-tech-team-support%20label%3Aplatform-reliability-team) for details. 
I found one team that might have gotten it to work. See: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75251
