### ISSUE TITLE
[FE] Investigate This Visit Feedback

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#13666]
## Description: 

We received the following from @kristenmcconnell  about a different possibility to use the built-in libraries. 

I talked to Jennifer Strickland this afternoon and she found an implementation of the list loop that better matches our use case. It is part of filing for disability. On this page, it would just require us to switch where we display our actual question "Do you have any other additional questions...?" I think that it would improve the user experience and be more consistent with another example on the site.

![Screen Shot 2020-09-16 at 12.52.13 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/2f25fc9c-017b-4b02-acd2-0875b862e89e)

![Screen Shot 2020-09-16 at 12.53.14 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/a551a145-a37c-4560-9198-efa3ac86ead5)

To see the example in staging: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction

[Zeplin](https://zpl.io/VOOek8j) has been updated to bring our form's design closer to the disability use case. 

## Tasks: 
- [ ] Determine how viable the solution above is
- [ ] If it is, the implement the above idea
- [ ] If implemented, review with the team 

## Acceptance Criteria
- [ ] Team is on board with results
- [ ] Deployed fix to staging 
- [ ] Adjust any testing if needed.

**Comment by kristenmcconnell** [comment]
I added the [Zeplin](https://zpl.io/VOOek8j) link with the updated wireframes to the description.

**Comment by mdewey** [comment]
After investigation, that team went completely custom with their implementation. That is tied to the [custom component ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13416)

**Comment by mdewey** [comment]
Here is [their custom code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/components/ArrayField.jsx#L24). A comment calls out that this was mostly copied from platform. 

Here is the current looks like a little closer to their design
![ezgif-6-e9917cc82507](https://user-images.githubusercontent.com/1793923/93913622-57d38380-fcd3-11ea-961f-f65f889e7ec5.gif)

**Comment by mdewey** [comment]
Resolution: 

- Not customizing
- Rearranging wording
- going to submit fix for scrolling

**Comment by kristenmcconnell** [comment]
@mdewey 
Wording updated in Zeplin. Use that when rearranging the wording. Let me know if there is another ticket that I should attach this comment to.

**Comment by mdewey** [comment]
@kristenmcconnell  https://github.com/department-of-veterans-affairs/va.gov-team/issues/14085
