### ISSUE TITLE
Documentation Site — Execute Confluence pilot

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#13660]
## Problem Statement 

Due to the constraints of: 

- storing our documentation in many spots — GitHub (va.gov-team and other repos), the Gatsby Site, design.va.gov, and more — and,
- much of that documentation being unclear, incomplete, out-dated, duplicatative, or non-existent

... VFS teams struggle to find documentation to answer their questions, which blocks them from developing on VA.gov.  This leads to VSP team members manually fielding questions that could otherwise be answered in the documentation. 

_HMW pilot Confluence as a documentation site to improve the findability of documentation for VFS teams?_

_HMW leverage Confluence to provide a better overall documentation experience?_

## Hypothesis or Bet

If we launch a well-architected Confluence documentation site, then VFS teams will be able to find answers to their questions without engaging VSP team members.

If we use Confluence, we can access improved insights and metrics, then enabling us to improve the contents of our documentation & provide a better overall experience.

## We will know we're done when... ("Definition of Done")

- [x] We have identified which content will be migrated first (which constitutes the pilot).
- [x] We have released a preliminary pilot for feedback.
- [x] We have iterated on the pilot to address crucial stakeholder feedback.
- [ ] We have compiled a pilot-based list of best practices and insights that will inform our content + IA strategy for broader release.

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/product-outline.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Internal documentation in [/products/platform/documentation-site/](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/documentation-site)
* **Product Outline**: [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/product-outline.md)
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide a reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: 
  - [Documentation site KPIs listed in product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/product-outline.md#key-performance-indicators-kpis)
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14251

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by KevinMHoffmanUSDS** [comment]
This is so exciting, @lianilychee! One thing that I'm missing from this description - how will you develop analytics models to help inform documentation usage? I think stakeholder feedback is good, but I'm more interested in user feedback (unless your counting users as stakeholders?) Regardless, something to the definition of done as defining baseline measures for documentation engagement would be great so as we grow, we can track improvement.

**Comment by lianilychee** [comment]
For posterity - conversation continued in VSP Roadmap (Google Sheets).

**Comment by vbellissimo** [comment]
Cancelling/old task.
