### ISSUE TITLE
[FE] Pre-fill Data on the "This visit" screen 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#13669]
## Decription 

After the appointment is loaded from the API and stored locally. Once the user navigates to the "this visit" page they should see the booking note and visit type. This is the parsing of the booking note

## Tasks
- [ ] Using the data from Redux, populate the `reason-for-visit` and  `chief complaint` fields
- [ ] Add the user to the edit  and expand on the  `chief complaint` field
- [ ] Use should not be able to edit `reason-for-visit`
- [ ]  THis should follow the parsing rules set up [this mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f3efded02033a2cd371f099)

## Acceptance  Criteria
- [ ] When present, the correct values should be displayed. 
- [ ] Parsing should be tested and

**Comment by mdewey** [comment]
Duplicate of #13670
