### ISSUE TITLE
[CONSIDER] Replace content with "Talk to someone" modal

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13671]
## Tasks
- [ ] Evaluate "How do I talk to someone right now" modal as option for content within suicide prevention health service accordion and [suicide prevention system page](https://www.va.gov/pittsburgh-health-care/suicide-prevention/)  (and possibly others)

## Current functionality 

![image](https://user-images.githubusercontent.com/55411834/93510196-0e9fc000-f8de-11ea-90de-da7f5e40e6ac.png)

## Modal 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/efa93fa7-e062-4a26-b03f-a4cfa7155298)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This will be addressed by VAMC upgrade team [#10068](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10068)
