### ISSUE TITLE
Collaboration Cycle - Custom Tracks 

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#13672]
## Problem Statement 
Currently, the VSP Collaboration Cycle is one size fits all, which creates unneeded barriers for VFS teams to launch in some cases and isn't scalable for VSP to closely support all initiatives as more teams/projects come onto platform. 

How might we improve upon the VSP Collaboration Cycle to enhance the experience for VFS teams allowing them to have leaner paths through the Collaboration Cycle with minimal support from VSP?

## Hypothesis or Bet

If we create tracks for the VSP Collaboration Cycle based on project/team characteristics, then VFS teams will encounter less barriers to launch and VSP teams will be able to provide appropriate levels of support across all VFS teams as additional projects/teams come onto the platform. 

## We will know we're done when... ("Definition of Done")
- [ ] we can support a process at scale that removes unnecessary barries for VFS teams. 

## Acceptance Criteria
- [X] We have identified a subset of project/team tracks as well as what collaboration points exist in each track.
- [X] We have identified a method for easily identifying what track is appropriate for a project/team.
- [x] We have released an MVP to a subset of VFS teams to test and validate our assumptions.
- [ ] If assumptions have been validated, we have developed a product for VFS teams to identify their own track on their own time.
- [x] If assumptions have been validated, we have remove Project Kickoff from the Collaboration Cycle.
- [ ] We have built a solution for measuring customer satisfaction.
- [x] We have identified criteria to determine if Design Intents, Usability Testing Preps and Staging Reviews can be held asynchronously.
- [ ] We have identified a way to size Staging Reviews to better plan for accessibility testing at staging.
- [ ] We have added Full Accessibility & 508 Office Audit and Post-Launch Check-in to the Custom Tracks.

Other Notes:
We overlap our feedback at reviews. Would be nice to have a unified front.
We share "no feedback" at staging reviews which can make us look unprepared.
QA check at staging? - no need to include IA (or any practice area) if all boxes checked

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _[link to Collaboration Cycle Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/vsp-collaboration-cycle/collaboration-cycle-product-outline.md), [link to Custom Tracks Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/vsp-collaboration-cycle/custom-tracks-product-outline.md)_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _[link to User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**:[ _link to Release Plan ticket_](https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/17278)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by shiragoodman** [comment]
Hypothesis #1 - These questions could replace Project Kickoff.
#2 - Teams can answer these off the cuff - they don't need advanced noticed.
#3 - teams can answer these questions as early as kickoff.
#4 - the questions we choose to ask don't encourage waterfall thinking 
#5 - in answering these questions, teams buy-in to the process
#6 - this process results in significant amount of teams having leaner paths through CC (at least 30%?)
