### ISSUE TITLE
Add COVID-19 screening tool to homepage

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13679]
## User Story
As a user, I can access [the COVID-19 screening tool](https://www.va.gov/covid19screen) from the app's homepage.

## Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific designs as needed

## Other documentation
- This should be an out of app webview that opens in the user's browser.
