### ISSUE TITLE
[FE] Pre-fill Data on the "This visit" screen 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#13670]
## User Story
- As veteran, I expect to see the data the current system has for me, so I do have provide the same information again

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 

## Description 

After the appointment is loaded from the API and stored locally. Once the user navigates to the "this visit" page they should see the booking note and visit type. This is the parsing of the booking note

## Tasks
- [x] Change  `chief complaint` naming to `reason-for-visit-description`
- [x] Using the data from Redux (mock data), populate the `reason-for-visit` field
- [x] Using the data from Redux (mock data), populate the `reason-for-visit-description` field
- [x] Allow the user to the edit  and expand on the  `reason-for-visit-description` field
- [x] Use should not be able to edit `reason-for-visit`
- [x]  THis should follow the parsing rules set up [this mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f3efded02033a2cd371f099)

## Acceptance  Criteria
- [x] When present, the correct values should be displayed. 
- [x] Parsing should be tested
- [ ] Team should see pre-filling of Mock data in staging

**Comment by mdewey** [comment]
Note for changing the styling.

**Comment by mdewey** [comment]
EDIT: refactored tasks to better suit engineering needs.

**Comment by mdewey** [comment]
Currently: https://github.com/department-of-veterans-affairs/vets-website/compare/healthcare-13670-prefill-from-redux?expand=1

- Renamed the field in the code for consistency 
- Created the `bookingNote` parsing logic with unit tests 
- using the new parsing logic for the reason to visit.

**Comment by mdewey** [comment]
EDIT: applied template

**Comment by mdewey** [comment]
In Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/14620, waiting for checks to happen

**Comment by mdewey** [comment]
@abuckley3385. This is in staging. You should see the appointment type and a prefilled text box on the "Prepare for Your Appointment" screen. It's filling from local mock data. but will work with all of the know appointment types and follows the [parsing logic established in the mocks up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f3efded02033a2cd371f099) and has [tests to verify that](https://github.com/department-of-veterans-affairs/vets-website/blob/1753de261827ce2abcbcad2185755b05d36378db/src/applications/healthcare/questionnaire/tests/unit/util-tests/utils.unit.spec.js)
 
<img width="739" alt="Screen Shot 2020-10-20 at 9 05 25 AM" src="https://user-images.githubusercontent.com/1793923/96589916-66519280-12b3-11eb-944f-8f3782ed7418.png">

Let me know if it looks good to you!

**Comment by abuckley3385** [comment]
prefill looks good.  @kristenmcconnell or @mdewey  is there a reason the Ranked questions for your provider font is blue? vs. our other headers are dark grey?

**Comment by mdewey** [comment]
I see what you mean, but I checked a few things, and it's not a different color according to my eyes and the code. I think it's just the screengrab.

**Comment by abuckley3385** [comment]
ok ill log in and see what it looks like in the code vs screen grab - its definitely a different color per graphics program and my super good eyes, :)

**Comment by mdewey** [comment]
Good idea on the on graphics program, I just check one on my end, and they're slightly different. The other titles are `#323a45` while the ranked questions are `#112e51` I am not sure why they are different like that, it'se all out of the box styling and colors.  I will add a note to a list loop ticket to look into that. Good catch :-)

**Comment by kristenmcconnell** [comment]
@abuckley3385 Good catch.
@mdewey I checked the wireframes. It should be #323a45.

**Comment by mdewey** [comment]
Adding the color update here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14085
