### ISSUE TITLE
VSP Command Line Interface (CLI) Toolkit MVP

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#13676]
## Problem Statement 

VSP does not have an easy way to automate certain developer focused tasks in a centralized and controlled manner.  This often results in multiple ways to perform certain tasks or unclear methods.

This includes tasks associated with getting started developing on the platform, and also includes troubleshooting in an effort to support those development activities.  The platform would benefit from having one tool that automated as many as these tasks, in a manner that is consistent with development practices, to improve the speed and accuracy in which we develop and support the platform and the applications being build on the platform.

For example, a VFS team that requests support from VSP doesn't have a quick and automated way to ensure they have the correct SOCKS configuration present and that they are connected successfully to the correct development environment in which they believe the issue to present.

## Hypothesis or Bet
* By automating the first steps to development, the platform team will have great control of implementing standards and increase the speed to which a team can start building on the platform.
* By automating tasks simple to complex troubleshooting tasks, it will decrease the amount of support and time the platform will need to provide to VFS teams.
* By creating an automated tool, it will reduce the dependency on searching through documentation to find answers and will provide real time feedback to common errors developers might encounter.
* By including common setup tasks it will decrease the the time it takes a developer to get started building on the platform.

## We will know we're done when... ("Definition of Done")
[ ] There is a minimum set of automated tasks developer through scripts that can be executed through a command line.
[ ] Tutorial is documented on each of the tools the CLI is capable of

### Is this service / tool / feature...

Tool

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### Measuring Success 

The current plan to measure the success of this product is using one already available metric and utilizing a custom commit message that can be searched and compared.

##### Tracking Ruby Gem Installs
Ruby gems are tracked automatically and this toolkit can be tracked using the following URL:
https://rubygems.org/gems/vtk
Actual success metrics are TBD, but a steady growth of the numbers of installs will imply that users are actively using the toolkit.

##### Tracking through Commit messages

We are going to be building in a custom commit message that will create an initial commit that can be easily searched in GitHub that will show us how many time a module was generated through the Toolkit.

There will be 3 separate tasks that will be tracked
* Creating Initial File Structure
* Creating a controller
* Creating a model

Link to GitHub Search query for creating Initial file structure
Link to GitHub Search query for creating a new controller
Link to GitHub Search query for creating a a new model

### Documentation
* **`PRODUCT_NAME`**: VSP CLI Toolkit
* [**Product Outline**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/vsp_cli_toolkit/vsp_cli_toolkit_product_outline.md)
* [**Design Document**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/backend/Product/cli-toolkit-research/design-doc.md)
* [**README**](https://github.com/department-of-veterans-affairs/vtk/blob/master/README.md)

### Measurement

[Ruby Gem Tracking](https://rubygems.org/gems/vtk)
[**Release plan**:](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/18490)

**Comment by alexpappasoddball** [comment]
@LindseySaari When you get the actual language you are planning on adding to the commit message, let me know so I can update our success metrics section to include what it will be, and include a GitHub link to the search query!
