### ISSUE TITLE
Feature Definition: COVID-19 features

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13681]
# User Story
As a product manager, designer, or engineer on VA mobile app, I want to understand how the app can best support COVID-19 related features so we can plan our work accordingly. 

We are aware of the following features:
- "I am here" SMS tool
- COVID screening tool
- VSA health screening tools
- COVID chatbot

### Questions
- Are more COVID features useful in our app? Why or why not?
- Technically, what COVID features can our app feasibly offer?

# Tasks
- [ ] UX/Product discovery
- [ ] Technical discovery
- [ ] Determine what COVID related features could be included in the mobile app 
- [ ] Write user stories for implementation work

**Comment by bridgethapner** [comment]
Adding "COVID Vaccine Passport" here as something to look into -- @srmyers17 do you know if there's a specific person/team we should stay in touch with about Passport?

**Comment by bridgethapner** [comment]
@ayushchak Would appreciate your input and decision making here. What features related to COVID-19 do you think the mobile app to have at the time of launch?

**So far the app has:** weblinks for Coronavirus FAQs & the Covid screener

We probably can add more stuff but that would require more discovery work / might affect the launch date.

**Comment by bridgethapner** [comment]
Closing this since we've decided on our COVID features for launch, all in web views: 
- FAQs
- Screener
- KMI

We can open new tickets as needed for new features.
