### ISSUE TITLE
COVID-19

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13683]
# Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product%20outline.md)

# High Level User Story
As a user, I want to keep up to date about how COVID-19 is impacting VA and understand what I need to do to meet VA's COVID policies.

# Hypothesis or Bet
If we make it possible for Veterans to view COVID-19 information and access simple COVID-related tasks from the app, that will reduce the burden on Veterans to navigate COVID and VAMC employees who are serving Veterans in person.

# OKR
_Veterans can view COVID-19 information from VA
_Veterans can access short, simple COVID-related tasks from VA

# Definition of done
What must be true in order for you to consider this epic complete?
- [ ] Opportunities to integrate COVID-related features identified by VA mobile app team
- [ ] Screens designed and developed
- [ ]  Accessibility overlays built and enhanced
- [ ]  Profile API optimized for mobile
- [ ]  Screens built and integrated with Profile API
- [ ]  QA and testing completed

**Comment by ayushchak** [comment]
This remains unknown - pending feedback from Leanna
