### ISSUE TITLE
Implementation accessibility review of new PDF for Welcome Kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#13686]
## Issue Description
VEO has created a new PDF on women's health to put on the Welcome Kit page. Before we can do that, we need to ensure there are no accessibility issues. 

**Note:** This ticket was created after Jennifer Strickland did the accessibility check and determined a few issues. Details below.

Original PDF: VAWK_QSG__Women_Veterans_Health_Services_2020_Final_508
New accessible PDF: VAWK_QSG__Women_Veterans_Health_Services_2020

Jen's work is captured [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13603#issuecomment-693520151) in ticket #13603

## Tasks
- [ ] Perform accessibility check (Jen)
- [ ] Update PDF to resolve any issues (VEO)
- [ ] Confirm new PDF meets accessibility criteria (Jennifer)

## Acceptance Criteria
- [ ] PDF passes accessibility check
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenstrickland** [comment]
PDF accessibility issues identified in an audit: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13603#issuecomment-693520151 Comment includes issues aside from the PDF items.

Validation of PDF issues remediation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13603#issuecomment-694457188
