### ISSUE TITLE
[CONSIDER] Search button width in Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13692]
## Issue Description
Recommendation from Jennifer Strickland in [#8414](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8414): 

> Form controls in the [VA Design System](https://design.va.gov/components/form-controls) have a max-width of 46rem. Although the buttons documentation does not specify a max-width, it would be best practice that buttons would also have this max-width so that they appear actionable. 

Also, it was noted that the title attribute should not be present. Instead, the class should be `<class="usa-input">`

![image](https://user-images.githubusercontent.com/55411834/93537099-d7460900-f907-11ea-8030-8888ad03cc44.png)

This issue was not called out during the validation of [#11121](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11121) and is not a design requirement in the form component but can be considered in future iterations. Impact on usability should also be observed during research. 

---
## Tasks
- [ ] Review current design and best practice recommendation above. 
- [ ] Remove title attribute and change to  `<class="usa-input">`

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@thejordanwood to review if still relevant

**Comment by davidmpickett** [comment]
Closing as not planned. We addressed this in the Facility Locator redesign and worked with the Design System to implement
