### ISSUE TITLE
Determine VAMC alert governance

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13691]
## Issue Description
The number of content editors with access to Drupal will increase as more VISNs roll out their VAMC pages. The Pittsburg pilot has demonstrated how alerts can be used and misused. 

A governance policy for alerts should be determined to ensure they are used appropriately, including: 
- Which types (and how many) are available to **national** editors?
- Which types (and how many) are available to **local** editors?

---
## Tasks
- [ ] Determine governance policy for alerts
- [ ] Determine editorial experience for alerts related to goveranance
- [ ] Determine communication plan

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This is the subject of a larger effort Initiative - Iteration on VAMC operating status and VAMC banner alerts#1392
