### ISSUE TITLE
All facilities/providers returned in Facility Locator search results must contain phone number

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13690]
## Issue Description
As A Veteran, I want to call a community provider/location to confirm the hours and services as recommended in the Facility Locator search results card so that I can ensure they are open and able to serve me.  

The Facility Locator consumes provider and facility information for Community providers (in VA's network), Community pharmacies (in VA's network) and Community urgent care providers (in VA's network) from the PPMS system (and therefore do not have control over the data). Occasionally, there is a provider or facility without this basic data element. The Office of Community Care agrees that any location without this basic data element can be removed from the search result display. 

---
## Tasks

- [ ] Add logic to check for the presence of the phone number. 
- [ ] Display search result only if it includes a phone number 

## Acceptance Criteria
- [ ] All search result cards displayed for any facility type search will include the phone number. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
