### ISSUE TITLE
[Bug] Event Tracking of COVID link clicks removed

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#13707]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Beginning on September 17, the dataLayer code supporting our covid FAQ page link click tracking was removed -- causing GTM/GA tracking to break on these events

![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/725ed173-a289-4f9f-a953-20fd04b2e516)

- The following taxonomy is expected per our original dataLayer implementation [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7890):

```javascript
    'event': 'nav-covid-link-click', 
    'faqText': '<full_faq_question>', //'What's VA doing to deal with COVID-19?'
    'faqSection': '<faq_section_header>' //'Coronavirus-specific concerns'
```

## Acceptance Criteria
- [ ] Datalayer specification above has been reinstated for all covid link clicks within the content body
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@ncksllvn I've included you here but please let us know who else we should loop-in here. 

In addition to correcting this issue -- we were hoping that we could also institute our convention on the links contained within expanded accordions. Please let us know if you would prefer us open a seperate ticket for this request. 

The variable `faqText` should populate with the question contained on the accordion itself and the `faqSection` should still populate with the top level section header. Here is an example: 

Description & Screenshot | Data Layer Example
------------ | -------------
Click on the link 'CDC website' <br><br> ![image](https://user-images.githubusercontent.com/48527022/93599594-5d0b9800-f98c-11ea-8210-4283560bd364.png)  | `'event': 'nav-covid-link-click',`<br>`'faqText': 'Do I need to wear a mask when I go to a VA hospital or other location?'`<br>`'faqSection': 'Health care, appointments, and more'`

**Comment by ncksllvn** [comment]
cc @brianalloyd @MickinSahni this is done now so we should add this to our sprint

**Comment by jonwehausen** [comment]
Confirmed this tracking was reinstated on Friday afternoon. Thank you @ncksllvn
