### ISSUE TITLE
Google Analytics:  GA4 Implementation Planning

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13704]
## Problem Statement 
Google will be sunsetting Universal/360 Analytics in October 2023 and will discontinue any tracking and historical data management at that time.  Their new tool Google Analytics 4 (GA4) will replace their current product and will change how events and parameters work on Google Analytics. We need to understand what changes we will need to implement in order to keep up with accurately reporting user metrics and keeping VFS teams informed of any analytics changes that may occur.

How might we integrate Google's latest Google Analytics4/Google Tag Manager updates safely and accurately?

## Hypothesis or Bet
If we research and implement Google Analytics 4 updates, then we can get more scalable GA data to VFS teams.

## We will know we're done when... ("Definition of Done")
We have migrated from Google UA/360 are actively utilizing GA4 to all data tracking, tagging and reporting.

This ticket only includes the planning portion of this work, additional tickets will be created each step of the implementation.

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by michelle-dooley** [comment]
Project planning session scheduled for 1/25 to further define, outline and assign tasks for the quarter.

**Comment by michelle-dooley** [comment]
@raywangoctova here is the link to confluence with details/findings to data...
https://vfs.atlassian.net/wiki/spaces/AT/pages/1928495134/WIP+-+GA4+discovery

**Comment by michelle-dooley** [comment]
Closing this Q2 epic, the GA4 migration work will continue in Q3 with [ticket 42199](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42199)
