### ISSUE TITLE
Platform Orientation - Launch new experience to support future scale

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#13709]
## Problem Statement 
Our orientation is almost exactly the same as it was when we kicked off VSP. The current problems orientation faces are the following:

1. VFS teams struggle with retaining information shared in Orientation.
2. ~~There is no reliable process for Platform to be notified of new VFS team members.*~~
3. ~~It is challenging to keep the content in the slide decks up to date.*~~
4. ~~Not having separate platform processes for new teams vs. new team members is inefficient.~~
5. ~~Platform team members spend a significant amount of time hosting 1:1 orientation meetings.~~
6. Content that VFS teams would find valuable is not included in orientation.
7. ~~The current orientation process is not scalable.~~
8. ~~VFS teams struggle to find information shared in orientation.*~~
9. (assumption) VFS teams get too much information too quickly.
10. ~~(assumption) VFS teams don't know what VA.gov is and how it works prior to general orientation.*~~
11. VFS Product Owners are not familiar with Platform processes and policies.

How might we improve the orientation process to better prepare VFS teams to develop on VA.gov?

*Priority problems to be solved for in MVP

## Hypothesis or Bet 
Each hypothesis is mapped to the problem statements above

1. 
2. If we build a reliable process for VFS to notify Platform of new team members, then we can ensure all new team members receive orientation and have the information they need to build on VA.gov.
   If we create a process for new teams and/or new team members to follow that is accessible from Platform Website, then Platform can ensure all new teams and new team members are oriented consistently.
3. If we publish the current slide decks on Platform Website, they we will create accountability with Platform teams to ensure they keep their slide decks up to date.
   If we modify internal Platform processes to be cognizant of Platform Orientation documentation, then we will have more reliable/less outdated Platform orientation content.
4. If we split out new team orientation from new team member orientation, then Platform team can use our resources effectively and continue to ensure new VFS teams are getting the necessary information.
5. If we create a Platform Orientation site that is self-service, the Platform team members will not be burdened by hosting multiple orientation sessions and can support future scale.
6. If we build a solution based off existing research from VFS teams and input from Platform teams, then Platform Orientation will include more content that VFS teams need/want to see.
7. If we create a Platform Orientation site that is self-service, the Platform team members will not be burdened by hosting multiple orientation sessions and can support future scale.
8. If we publish the current slide decks on Platform Website, then VFS teams will have access to all information shared during orientation.
9. 
10. If we integrate a VA.gov overview into our orientation process, then new team members will have a better understanding of the site and be more prepared to develop on VA.gov.
11. 

## Potential Topics to be covered.

- Collaboration Cycle 
- Introduction to Design tools/services (Design System),
- introduction to  VA website (hub pages, right rail, etc.)
- different teams across VA.gov, OCTO-DE organization 
- overview on the products
- Demos, Team of Teams, other meetings
- office hours across teams
 - practice area specific Slack channels
 - tool/app user guides (for example, Zenhub. Not Platform responsibility to educate, but can still locate and share guidance created by tool/app owner)

## Improvement opportunities identified from Platform Orientation - Current State Service Blueprint

1. ~~Communication of new team/team member varies depending on program (AKA no consistent form of intake).~~
   - To be resolved in this ticket: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/29919
2. VFS users need GitHub read/write access to view/complete the orientation ticket. Platform is no longer provided with the VFS user's GitHub handle, so new users are not reliably being assigned the ticket.
3. ~~Because many new VFS users aren't seeing the GitHub orientation ticket, they aren't signing up for other orientation sessions other than General orientation.~~
4. Currently General orientation is a pre-req to Design & all other orientations. We may need to be flexible now that orientation sessions are offered monthly.
5. ~~There is not a replacement process for notifying Platform teams to schedule role-based orientation sessions (design, FE, BE, etc.) for a new VFS user, so users are likely not attending them.~~
   - To be resolved in this ticket: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/29920
6. ~~Platform doesn't have a process for adding new VFS users to the roster during orientation. They do have an off-boarding process to remove users from the roster.~~
   - To be resolved in this ticket: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/33198
   - and this ticket: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/33197
7. Should Platform General Orientation be mandatory before granting vets-gov-write access?  VFS users can't be assigned the ticket if they don't have access.

## We will know we're done when... ("Definition of Done")
- [ ] We have synced with all Platform teams to ensure their content is included in orientation.
- [ ] We have a solution that can support the future scale of VFS teams building on VA.gov.
- [ ] We have implemented a solution that helps Platform keep guidance/documentation up to date.
- [ ] We have tested and verified our solution with VFS teams.

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _[link to Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/orientation/product-outline.md)_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by cmaeng** [comment]
The current CMS onboarding process has some overlaps that may be more efficient to do together:

- VA.gov historical context
- OCTO-DE context (who's who, landscape of different teams we work with)
- Platform's code of conduct
- USDS playbook and principles
- GitHub repo structure for vets-website and va.gov-team

Could the CMS team piggy-back off of the Platform's version of these so that the information is coming from the source? Or at least collaborate together on what information Platform deems important for all folks working in the ecosystem to know, so that we ensure it gets covered?

Would love to do some sort of review on where overlaps may exist.

**Comment by shiragoodman** [comment]
Current Orientation process: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1621540297622/94e7421ea7c560ea7dcaa1ca54cd6920731f48ae

**Comment by shiragoodman** [comment]
idea: include in Initiative Launch checklist - will this work need to be included in Platform Orientation?

**Comment by shiragoodman** [comment]
idea: 2 processes/solutions. 1) face-to-face process for brand new teams. 2) self-service site on PLatform Website available to individual newcomers (and all)

**Comment by shiragoodman** [comment]
Getting Started Workshop: https://docs.google.com/document/d/1S6w7mZHtI6m51JicYKkQWJSOft4ZTChXsKZUIKeoDEQ/edit
