### ISSUE TITLE
Selection information for Benefit Summary and Service Verification Letter

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13705]
# Story
As a user, I can select the information I'd like to include within my Benefit Summary and Service Verification Letter. I can choose to include or exclude the following: 

- Military service information (1 selection)
- VA Benefit and Disability information, (4 selections)
    - Current monthly award and active change date
    - Combined service-connected rating
    - Permanence
    - Number of disabilities

# Tasks
- [x] High fidelity prototype of screens in iOS
- [ ]  Usability test as needed, refine as needed
- [ ]  (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

# Prototype
[Screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636882)
