### ISSUE TITLE
[FE][SPIKE] FHIR Questionnaire into a form

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#13711]
## Description 
**Current State for MVP** We are storing a static FHIR questionnaire that needs to be mirrored va.gov. This mirroring is a manual process that goes through the engineering team. 

**To fix that that** Eventually we want to create a questionnaire in va.gov using[ FHIR Questionnaire](https://www.hl7.org/fhir/questionnaire.html) spec. Using the current form system, we have found that is impossible/very hard. This would be creating a dynamic form without the form system to see exactly what has to be done in a perfect world

## Tasks
- [ ] Create a small demo using React to create a form that is generated from a FHIR Questionnaire JSON object not using the form system 
- [ ] Identity what deltas are needed for the current forms system. 
- [ ] the Stretch goal is that this exists in va.gov

## Acceptance Criteria 
- [ ] Successfully create a small demo that is shown to the team. 
- [ ]  Document findings
- [ ] Validate that the forms team understands the features needed

**Comment by julieadair1** [comment]
@mdewey is this something that still needs to be done?
cc: @jparker0425

**Comment by julieadair1** [comment]
Per @mdewey this can be closed. :)
