### ISSUE TITLE
Test User Account Dashboard MVP

### ISSUE THREAD

**Issue by christine-dillman** [department-of-veterans-affairs/va.gov-team#13714]
## Problem Statement 

We do not have a scalable solution for the challenges teams face with test user accounts while performing tests and demos on VA.gov.  Currently, testers cannot find test user accounts that are viable for the scenarios they need.  Test user accounts regularly have inaccurate data, expired passwords, used by multiple testers, and are not in the right state to test a feature.

How might we: 
•	Create new test user accounts for an app.
•	Delete test user accounts for an app.
•	Reset test user accounts for an app.
•	Ensure data integrity of test accounts for an app.
•	Manage/log Changes to test user accounts associated with an app.
•	Read the list of existing test accounts associated with an app.
•	Change the name or password for a test user.
•	Change permissions a test user granted to an app.
•	Log in as an unauthenticated test user.
•	Log in as an authenticated test user with proper account verification information
•	Allow for test user accounts to be checked-in/out for use.
•	Provide a user-friendly UI to manage test user accounts

## Hypothesis or Bet

The current set of staging test user accounts will meet teams’ QA and demo needs if we do the following:
-Make it easier to find the right test account for a user scenario
-Ensure the state of those accounts can be managed and maintained

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*
- [x] Assess state of existing test user accounts
- [x] Gather requirements
- [x] Define limitations
- [x] Users can view an accurate list of test user accounts available on staging.
- [x] Users can filter test user accounts based on different categories
- [x] Users can view details about a specific test user account's credentials
~~- [ ] Users can perform CRUD operations on new/copied test user accounts~~ (Out of scope for MVP)
- [x] Users can "check out" a test user account to log into staging with it
- [x] Users can authenticate to TUD with basic auth
- [x] Users can authenticate to TUD with GitHub OAuth

### Is this service / tool / feature...
Tool
### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end ([Planned for post-MVP](https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/32935)), [manual QA](https://dsvavsp.testrail.io/index.php?/projects/overview/48), [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [x] ([Planned for post-MVP](https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/32935)) New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [Platform Products and Services](https://vfs.atlassian.net/wiki/spaces/PPS/overview?homepageId=1391067357)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1982955542/Test+User+Dashboard+Product+Outline) 
- [x] External-facing: [VFS-facing documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-the-Test-User-Dashboard.1910702416.html) exists for this product/feature tool
- [x External-facing: a [Document](https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-the-Test-User-Dashboard.1910702416.html) exists for this product/feature/tool, and is updated for changes from this initiative

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Test User Dashboard
* **[Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1982955542/Test+User+Dashboard+Product+Outline)**
* **User Guide**: [Using the Test User Dashboard](https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-the-Test-User-Dashboard.1910702416.html)

### Testing

* **Usability test**: Executed by previous team -- TBD
* **Manual QA**: [TestRail Project Overview](https://dsvavsp.testrail.io/index.php?/projects/overview/48)
* **Automated tests**: [GHA Unit Test Execution Example
](https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/runs/4119146116?check_suite_focus=true)
### Measurement

* **Success metrics**: [Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1982955542/Test+User+Dashboard+Product+Outline)
* **Release plan**: [Release Plan](https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/32865)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by emilywaggoner** [comment]
Here is a link to the Test Account prototype from last fall: https://projects.invisionapp.com/share/TRUYL8CFEWP#/screens/394670563?browse

**Comment by nsoutouras** [comment]
Transitioned to TTT

**Comment by pjhill** [comment]
All tasks related to MVP have been completed.

**Comment by JoeTice** [comment]
Wasa scan not required - Initiative marked as closed
