### ISSUE TITLE
[BE] Adjust API url 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#13731]
## Description 
After using the endpoints created, The engineering team is seeing they need to be adjust a little. 

In order to re-use the existing integration between the front and back, the URLs for the endpoints need to use a specific pattern of 

```
{domain}/{version}/{service_name}/the/rest/of/the/url
``` 
The existing endpoints created are 
```
{domain}/{service_name}/{version}/the/rest/of/the/url
```
need to be changed to the standard format of 
```
{domain}/{version}/{service_name}/the/rest/of/the/url
```
## Tasks

- [ ] update the appointments and PGD endpoints to follow the correct schema

## Acceptance Criteria
- [ ] The API endpoints are the correct schema
- [ ] The front end team can pull you branch down and make a successful call to the API endpoints using the built in system, 
- [ ] Merged to master

**Comment by mdewey** [comment]
I think this is fine, I was able to the current endpoints. No action needed.
