### ISSUE TITLE
[FE] Intergration with Get appointment API

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#13732]
## Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - This Visit ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)

## Description
Currently, we are using mock API calls to show data on the screen. We need to update the form to actually call the API in the correct environments ( production and staging). Once the API is created and deployed, we can start to use that for our data instead. This will still display mock data, but the mock data will come from the API. What we gain is that when the back end is ready to go, the integration will be easier. 

## Tasks
- [ ] Help in anyway to complete [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13731)
- [ ] Update the API calls to use the API request in staging and production 
- [ ] update and tests accordingly

## Acceptance Criteria 
- [ ] API calls are firing in staging
- [ ] Tests pass
- [ ] Data from the API is stored in Redux
- [ ] UI review meeting with product for feature capabilities 
- [ ] UI review meeting and callouts with designer for layout and callouts
- [ ] published to staging environment, behind a feature flag

**Comment by mdewey** [comment]
Blocked by [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13731)

**Comment by mdewey** [comment]
[from #137076] The API endpoint is giving a 500 error: 

![Screen Shot 2020-09-21 at 1 23 56 PM](https://user-images.githubusercontent.com/1793923/93799838-b6cec500-fc0d-11ea-8cbf-61759e09762b.png)

**Comment by mdewey** [comment]
After working with the team. This is not ready yet, Front End was under the assumption that there was dummy data being returned from the endpoint `/health_quest/v0/appointments/`. Instead, that endpoint fails since it is hooked up to the real data, but fails since we don't have access. 

This is ticket is `blocked` since this relies on the API serving mock data.

**Comment by mdewey** [comment]
Successfully hit endpoint in a branch on the vets-api ( `14991_mock_appt_from_api` ) when that is merged, this can be moved to the ready column

**Comment by dillo** [comment]
The mock appointment endpoint in the vets-api is now available on the master branch. https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14991 is ready to be pulled down, evaluated, and then closed. cc: @mdewey

**Comment by mdewey** [comment]
<img width="1435" alt="Screen Shot 2020-11-12 at 2 01 04 PM" src="https://user-images.githubusercontent.com/1793923/98983948-827dd380-24ef-11eb-910e-2eea0ce8eca0.png">

Verified in staging
