### ISSUE TITLE
Infrastructure Recommit - Develop Centralized Logging solution (Loki)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#13744]
## Problem Statement 
Right now logging is not a  great experience on VA.gov.  All the logs are within cloud watch logs in AWS which requires AWS consul access to view. That process can take months and even after getting access it is not a full logging experience. Another method that is being used is Sentry, which is not meant to be a logging tool. This leads to confusion and having logging all over the place and hard to access. It also has been identified as a top pain point for both VSP and VFS teams.

How might we create a  better logging experience on  VA.gov that can make logging easy, accessible, and scalable? 

## Hypothesis or Bet
Having better logging will improve the quality and velocity of all teams working on VA.gov. 
Having logging with Loki in Grafana will be an easy familiar place for developers. 

## We will know we're done when... ("Definition of Done")
We are ready to deploy Loki in various environments, beginning with Staging (Q2, 2021), and the Production (Q3, 2021) 

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/logging) exists for this product/feature tool
    - [x] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [x] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [x] ... and should be linked from the VFS-facing README for your product
    - [x] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it

- [x] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### Documentation
* **`PRODUCT_NAME`**: Centralized Logging
* **Product Outline**: [Centralized Logging - Log Collection, Aggregation, Search, Query, & Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/818d278fb0b9d96b31f2ebef13a14f0fdadf5795/products/platform/centralized-logging/centralized-logging-product-outline.md)
* **README**: [Logging](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/logging#readme) (will be moving to Centralized Logging)
* **User Guide**: [Centralized Logging with Loki - User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/818d278fb0b9d96b31f2ebef13a14f0fdadf5795/platform/logging/centralized-logging-user-guide.md)

### Testing

* **Usability test**: Skipping - using mostly out of the box solution 
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: [Centralized Logging - Log Collection, Aggregation, Search, Query, & Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/818d278fb0b9d96b31f2ebef13a14f0fdadf5795/products/platform/centralized-logging/centralized-logging-product-outline.md)
* **Release plan**: See product outline, above

**Comment by jhouse-solvd** [comment]
_from a conversation w/ Kam & @pnwstevan :_ 

- need to consider impact of simultaneous logging, ie getting data into CloudWatch and Loki at the same time 
- Understanding the dependencies, ie are there other reports like the one that Kam provided that other teams are doing?

**Comment by jhouse-solvd** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/logging/logsByService.md

**Comment by jhouse-solvd** [comment]
@pnwstevan - can you add your high-level notes for what needs to be addressed here?

**Comment by pnwstevan** [comment]
@jhouse-solvd We can break down work items tomorrow, but specifically for Sprint 36 I think reasonable goals would be:

- Complete inventory for all environments
- Get all hosts/apps in Dev logging to Loki Dev via promtail
- Some architecture R&D/spikes in staging specific to microservices deployment
- Demo Loki to VSP at end of next spring (Michael Fleet asked for this)

Let me know thoughts!  CC: @dginther

**Comment by jhouse-solvd** [comment]
basic r&d 
Design doc
implementation 
after inventory doc, we will mostly be done on the pre-planning phase and documentation 

work through dev and prove a lot of the assumptions in the design doc 


Major tasks / Stories 

- [ ] Pre-planning research and documentation (create epic) 
- demian's design doc and corresponding story / task - probably one to update this a little bit, move out fluentd stuff, etc
- there is a ticket that is currently in review state, let's move this one back to in progress 
- implementation question doc, this is pretty much done, so let's create a ticket and link to doc and close 
- inventory which is in progress, link to ticket above 
- customer research ie 2-3 key use cases (such as convo that we had with Kam who is doing custom reports), circulate this with teams external to operations 
- terraform module for fargate is a pre-requisite for deploying loki into the new infrastructure (demian ticket?) 
- product outline for loki logging implementation (should be already linked to this epic) 
- once design doc is cleaned up, create a nice diagram that reflects our specific architecture 

- [ ] Deploy and set up Loki development environment 
- big tasks for dev, most of which is done, is stand up FG cluster in dev for Loki (done, ticket?)
- stand up an FG cluster using terraform module 
- get all default log groups working in dev (standard linux logs, add'l logs from docker containers, etc) 
- get everything that is currently logging in CW logging in Loki Dev
- get some of the AWS service logs into Loki (there may be some architecture considerations here) 
- DEMO LOKI LOGGING VSP DEMO :) 

- [ ] Deploy and set up in staging environment (EPIC)
- one of the big things will deploying Loki in a microservices mode (this is likely it's own EPIC)

- [ ] Deploy and set up in production environment 

- [ ] Operationalize - 
- DOCS, DOCS, DOCS! 
- Failover and reliability testing 
- Story for metrics dashboards and alerts 
- wiring up alerts to Loki from Loki logs - something related to shipping data/events to Datadog - early warning signals

- [ ] Long-term life of logging system / recovery scenarios / auditing / compliance 
- log archival and retention / old log retrieval - consider and understand better what happens when dynamoDB explodes, how do we make use of log chunks

**Comment by jhouse-solvd** [comment]
@pnwstevan OR @dginther - Can one of you provide a link to the "implementation question doc"? ( this was discussed as a component of the pre-planning phase and I believe is mostly done, just want to link up, create a ticket, close it out! :)

**Comment by jhouse-solvd** [comment]
Need to finalized the initiative checklist, and then this can be closed.

**Comment by jhouse-solvd** [comment]
Please see [HERE](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17615) for the current initiative to deploy Centralized Logging with Loki in production. 

This initiative can be closed. 

Closing.
