### ISSUE TITLE
[Ongoing Service] Clean up of AWS [Access management, Deployment Templates, etc]

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#13747]
## Problem Statement 
Old, irrelevant configurations in AWS can lead to confusion, lack of consistency, and duplication of information, resulting in the platform being harder to operate and maintain 

How might we clean up access management configurations and infrastructure deployment templates to ensure consistency and smooth operation for operations and development teams? 

## Hypothesis or Bet
If we clean up irrelevant configurations in AWS, VSP teams will be able to develop faster
If we clean up irrelevant configurations in AWS, there will be less risk for adding infrastructure services in the future

## We will know we're done when... ("Definition of Done")
Only relevant and actively needed configurations remain in AWS

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
from @jsev-io: 

Can we create a new ops slack channel for security alerts? Especially during testing, this will help with ensuring sanity / clarity around what's needed / not-needed from a security configuration and access management perspective.

**Comment by jhouse-solvd** [comment]
consider changing title to "platform infrastructure maintenance"; see this issue as an example for how this was tracked previously: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4202

_also, see if you can close ^^ that issue down_ 

I still like the idea of creating a new "ongoing service" ticket per quarter, so that we can look at concrete maintenance tasks completed during that quarter, and potentially quantify the effort / resources needed on a quarterly basis.

**Comment by jhouse-solvd** [comment]
This is defunct, please see: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4202

Closing.
