### ISSUE TITLE
Observability Tools: Infrastructure Monitoring - Ensure metrics for all environments are readily available (using Datadog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#13748]
## Problem Statement 
The platform currently leverages Prometheus & Grafana for monitoring. However, the tool in its current implementation is outdated, lacks clean alerting, and is difficult to use due to the query language and limited data retention. Additionally, there is not an adequate solution for instrumentation that could provide Application Performance Monitoring (APM. This creates a pain point for developers because they are unable to gain deeper visibility into the platform's infrastructure services.

How might we provide better monitoring tools that increase observability for developers? 
How might we offer a better infrastructure monitoring experience for those developing on Va.gov?
How might we ease the administrative burden of managing the service (ensuring the most up-to-date application is readily available)? 

## Hypothesis or Bet
Providing a more modern and user-friendly monitoring tool will make it easier to gather and consume metrics, helping to drive adoption for the platform observability solution. 

## We will know we're done when... ("Definition of Done")
When all of the metrics that are currently available in Prometheus are available in Datadog, and platform crew developers can access the new monitoring tool. 

Note: The goal is not to re-create all of the dashboards that currently exist in Prometheus, but rather to provide access to the tool so that others can begin using it. 

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] ~~External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool~~ 
  - [x] Does not apply because Datadog is _currently only available to platform crew teams_
- [ ] ~~_(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)~~
  - [x] Post to #platform-team for communication about this change to Platform Crew developers

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: Monitoring
* **Product Outline**: [Monitoring using Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593917/Monitoring+using+DataDog)
* **User Guide**: [Get acquainted with Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1775435805/Get+acquainted+with+Datadog)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by jhouse-solvd** [comment]
High-level capture of next steps and considerations: 

- Modify common os role on the AMI, then this role would get included, and over the next week or so, that would install the agent on every instance 
- Ansible variable in for the API key will determine whether or not DD will be enabled on the instance 
- Need to determine which type of instances we will install the DD agent on 
- In order to control which instances this run on, we will put settings in Ansible deployment config, and yaml files will pass variables into the build of the instance to determine the apps to "activate" 
- No particular preference for which instances, but perhaps we want to quantify how many instances are in DEV environment, mostly just EC2 instances 
- We can also use Loki as a guinea pig for rolling this out on ECS instances 
- We have ~17 running EC2 instances in dev
- vets-api {service, worker}, revproxy, fwdproxy, gids, cms {cms,-test} (16 instances) 
- instances needs to have va certificates on it, but those are already there
- what is the baseline of metrics that get sent? 
- what are the additional metrics? 
- filtering by tags, indices 
- can further filter based on add'l annotations that DD provides 
- would be great if we have the same set of tags across Loki<->DD

**Comment by jhouse-solvd** [comment]
from @drorva: 

"Can you please put together a rough roadmap of how and when VFS teams will start using datadog. My understanding is that the sequence is:
Ops teams
BE teams
VFS teams
and maybe include some links and info on how datadog is going to be useful for them."

**Comment by jhouse-solvd** [comment]
quick note from today's ops all hands: identify what we want to monitor from prometheus

**Comment by jhouse-solvd** [comment]
Need to shore up artifacts and documentation for what's been done so far. 

In essence, we have DataDog working conceptually but are awaiting add'l licensing, which will be tied in with #23513

**Comment by jhouse-solvd** [comment]
This is ready to go for platform crew developers for the purposes of infrastructure monitoring. 

We're going to open up access to the tool so that they can [get acquainted](https://vfs.atlassian.net/l/c/17tGwrz5) and begin configuring metrics and dashboards, though asking that folks hold off on configuring alerts at this time. 

Please check #platform-team slack channel for an announcement.

**Comment by jhouse-solvd** [comment]
This initiative can be completed once all of the checklist items have been addressed and supporting artifacts and documentation have been linked.

**Comment by jhouse-solvd** [comment]
@f1337 - Could use help on the section above titled "Is this service/tool/feature...tested? Happy to discuss.

**Comment by jhouse-solvd** [comment]
Please see ["Monitoring using Datadog"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593917/Monitoring+using+DataDog) for links to important information. 

Datadog is not yet available to VFS teams but is being considered as part of #33081. 

This issue can be closed.
