### ISSUE TITLE
686c - Change `vagovprod` From False to True

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#13749]
## Description
In order to conduct UAT for the 686c, it needs to be in production.

## Tasks
- [x] Update the entry in `registry.json` needs to have the `vagovprod` flag updated from `false` to `true`. 
- [x] Request on off-cycle deploy
- [x] Log in to Flipper and update the toggle

## Acceptance Criteria
- [x] The 686 application is in prod
