### ISSUE TITLE
Platform Website — Launch frontend developer documentation on Platform Website

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#13756]
## Problem Statement 
Frontend developer documentation is spread across multiple locations (Confluence, the Gatsby site, va.gov-team). Developers are rarely sure which docs are the source of truth, and as a result they rarely self-serve to find answers to their questions (those answers often don't exist in the docs anyway). Platform receives negative feedback about docs every quarter. 

How might we iterate on frontend developer docs to provide a cohesive, comprehensive, trustworthy experience for VFS teams? 

## Hypothesis or Bet
If we consolidate and update frontend developer docs, then VFS developers will self-serve info and troubleshooting before asking for Platform support.

## We will know we're done when... ("Definition of Done")
- [ ] Frontend developer docs owned by FE Tools team are launched on Platform Website
- [ ] Legacy docs are deprecated

## Known Blockers/Dependencies 
* Migration to Confluence will depend on guidance from Content & IA team 
* Risk: some FE developer docs are owned by other teams (such as forms library documentation, owned by Design System team which is not on Platform crew)

## Projected Launch Date
* September or October 2021

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: See Content & IA team's [Platform Website product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/team-documentation/team-documentation-product-outline.md)
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: see [Platform Website product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/team-documentation/team-documentation-product-outline.md) for Content & IA team's approach and success metrics
   * Additionally, FE Tools will measure the success of this initiative by: 
      * FE developer sentiment on docs
      * Avg number of Platform docs updated by FE Tools team per month
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
