### ISSUE TITLE
Update SGLI life insurance page with new info from stakeholder

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#13772]
## Issue Description
Per a stakeholder request, we need to update information on the [SGLI](https://www.va.gov/life-insurance/options-eligibility/sgli/) life insurance page. The current premium is 6 cents per $1,000 instead of 7 cents per $1,000. 

The information needs to be corrected under the question "How much will I pay for these benefits?"
![Screen Shot 2020-09-21 at 11.00.24 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c441a855-559b-470e-9122-d1f4474aa824)

While we are making changes to this page, we also need to update the table to our new styling of using (in U.S. $) in the table headers instead of a dollar sign with each monetary figure.

## Tasks
- [x] Change 7 cents to 6 cents (Randi)
- [x] Update table headers with (in U.S. $) (Randi)
- [x] Review and publish page (Randi)
- [ ] Alert stakeholder change has been made (Randi/Beth)

## Acceptance Criteria
- [x] Changes are live on site

**Comment by RLHecht** [comment]
These changes have been made. Will validate after today's deployment. @bethpottsVADEPO You can let the stakeholder know it should be live after 4 today. FYSA @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket. FYSA @MickinSahni @brianalloyd
