### ISSUE TITLE
Update Burial Allowance page w/ Oct 2020 amounts

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#13787]
## Issue Description
This page needs updating: https://www.va.gov/burials-memorials/veterans-burial-allowance/

We need to: Update the rates in the charts on this page based on this 2020 source page so it can happen on October 1. https://app.zenhub.com/files/133843125/9f6bbd04-b549-4aa5-819d-c183571cc834/download

---
## Tasks
- [x] _Update the rates in the charts on this page based on the 2020 source page (Selina)_
- [x] _Review page (Randi)_
- [x] _Publish updated page (by Oct 1st) (Randi)_

## Acceptance Criteria
- [x] _Page is published with Oct 1 2020 rates_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht This page is ready for review. Node 864

**Comment by RLHecht** [comment]
This page has been reviewed and published. We still need to add the 2020 rate for headstones/markers so I'll leave this ticket open in hopes we get it soon. FYSA @brianalloyd @MickinSahni

**Comment by lunascoop** [comment]
@Randi this page has been updated with the 2020 headstone marker rate and is ready for review. 
http://preview-prod.vfs.va.gov/preview?nodeId=864

**Comment by RLHecht** [comment]
This page has been reviewed and published. Will close after today's deploy. FYSA @brianalloyd

**Comment by RLHecht** [comment]
This update is live. Closing ticket.
