### ISSUE TITLE
Conduct User Interviews

### ISSUE THREAD

**Issue by yarogit** [department-of-veterans-affairs/va.gov-team#1379]
## User Story
As a Designer/Researcher, I need talk to the Veteran Users of the Caregiver Intake Form so I can fold their concerns and experiences into our development requirements.

## Goal
A Caregiver Intake experience that is simple and intuitive to aid Vets and Caregivers in entering the Caregiver Program.

## Acceptance Criteria
Interview a sufficient number of potential users to develop a user friendly set of requirements.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)

09/03/2019

- [ ] **Attached to an Epic** (what body of work is this a part of?)

Conduct User Interviews

- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)

Caregiver Discovery

- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

Research

- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

Research, Documentation
