### ISSUE TITLE
Content structure: Contact us

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13792]
## Problem Statement
How might we change the structure of the "Contact us" content so that
- some content can be reusable
- national content cannot be edited locally
- the risk of introducing errors is reduced
- the editorial experience is enhanced and efficient

## OKR
Decrease the amount of national content which is locally editable 

## Definition of done

- [ ] Content structure changes
- [ ] Front end mapped to new data structure
- [ ] Pages render as expected 
- [ ] Editorial experience review with CMS
- [ ] Content model review with CMS
- [ ] Feedback session with VAMC upgrade team 
- [ ] Migration plan
- [ ] Testing plan

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Note to remember to incorporate [Leyda's findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/communication-audit-research-findings.md) about the number of methods to communicate with VHA/labels, etc when we harden this page

**Comment by mmiddaugh** [comment]
Related:
VAMC system "Contact Us" page content type and governance #3045
Contact Us accordions are not contained within the same group #12087
VAMC Detail Page: Contact Us: Accordions render even if empty #13076

**Comment by mmiddaugh** [comment]
For context:
Contact us pages were viewed 1,207,386 times between Jan 1- May 18, 2023. (504,954 unique views)
System level health service pages received 1,238,243 pageviews (439,545 unique views) during the same period
