### ISSUE TITLE
[FE] Logged-in homepage: Technical comparative analysis

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#13796]
## Background

In our 9.17.20 meeting to talk about the logged-in homepage approach, it was discussed that it might be worthwhile to do some comparative analysis on how other websites (eg. Amazon; bank or health care portals) handle having a logged-out and logged-in homepage.

- How are these pages built to accommodate the two different pages?
- Are the URLs for the logged-out and logged-in homepage the same or different?
- What can you learn from how these pages are built that we might be able to apply to the new VA.gov logged-in homepage?

## Tasks

- [ ] Pick a few sites on which to conduct this comparative analysis ([here is the design comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/comparative-analysis.md) if you need ideas, but you do not have to look at the same sites as Liz did)
- [ ] Conduct comparative analysis
- [x] Document notes and learnings in the [logged-in homepage Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign/build) (does not need to be terrible formal, but please make sure they are clear for other team members)

**Comment by erikphansen** [comment]
just putting an arbitrary 3 so we don't spend more than a couple of days on this.

**Comment by sanlouise** [comment]
Some initial findings (WIP)

Most corporations do not have a different homepage experience at the same root url for logged in users, in those instances it is not necessarily helpful to compare how those companies have implemented their homepage since they perform a redirect to a dashboard style page.

Foe example, Wells Fargo does not have an authenticated homepage per se - it redirects the user to an authenticated dashboard at a subdomain. When the authenticated user goes back to the homepage, they do not see any different content than unauthenticated users do and they are prompted to log in again.

Chase treats authenticated users similarly. When going to the homepage, the user is promoted to log in and thereafter are redirected to a subdomain to be presented with an authenticated dashboard.

**Comment by Samara-Strauss** [comment]
Thanks for this.

How does Amazon (or similar companies) handle this use case?

**Comment by erikphansen** [comment]
Amazon barfs product recommendations all over the home page. If you are logged in they are more specific to you. It's hard to know what tech they use to do this. My hunch is that it's all server-side. Amazon is probably the closest parallel to what we plan to do with VA.gov. In both cases the sites are trying to surface what is important to the user and they serve up very different content to logged in users vs logged out users.

**Comment by Samara-Strauss** [comment]
So nothing we can really learn from their approach? OK if not, just asking.

I'll let you two determine when this ticket is done. If you feel like you've learned some things but aren't really finding anything helpful out there, then it's up to you to decide whether you'd like to keep looking for examples or not. Once you're done with the research, please summarize your notes in Github and link here so we have record of your findings.

**Comment by erikphansen** [comment]
Closing this. Doc updated [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/build/README.md)
