### ISSUE TITLE
Analyze DAV van content for hardening 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13797]
### Problem Statement
How might we change the structure of [DAV van page content](https://www.va.gov/pittsburgh-health-care/dav-vans-transportation-for-veterans/) so that
- some content can be reusable
- national/regional content cannot be edited locally
- the risk of introducing errors is reduced
- the editorial experience is enhanced and efficient

Before we can decide the best hardening approach, we need to analyze the content currently available and determine the governance (national? regional?)

---

## Tasks
- [ ] Identify **regional** content which can be standardized on [Pittsburgh DAV-VANS](https://www.va.gov/pittsburgh-health-care/dav-vans-transportation-for-veterans/)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
For context: 
Between Jan 1- May 18, 2023

- health-care/dav-vans-transportation-for-veterans/ pages were viewed 116,380 times (43,132 unique views). 
- System level health service pages received 1,238,243 pageviews (439,545 unique views) during the same period
