### ISSUE TITLE
Data layer tweaks

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13804]
## Issue Description

Some tweaks need to be made to data layer implementation from [#10987](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10987) based on feedback [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10987#issuecomment-696368880) 

---
## Tasks
- [ ] **On Search Results Returned:** Push dataLayer variables along with the event, rather than individually

<Details>
<summary> information from comment </summary>

Description of Interaction | Data Layer Screenshot | Test Status | Notes
------------ | ------------- | -------------  | ------------- 
Search results returned | ![image](https://user-images.githubusercontent.com/48527022/93813389-0cf93380-fc21-11ea-9286-790f969bfcea.png) | ❌ **DOES NOT PASS** | • Similar to how the correction on the `fl-map-pin-click` event causing multiple messages, each of these separate messages containing Data layer variables should all be sent with the `fl-search-results` event <br><br> • Once we get this corrected we can take a more thorough look at the Data Layer as in the examples below

</details>

---

- [ ] **For Map Zoom In/Out:** include both 'fl-map-miles-moved' and something like 'fl-current-zoom-depth' along with the event fl-search to conserve traffic volume

<Details>
<summary> information from comment </summary>

- Per @mpelzsherman [comment here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12137#issuecomment-689140397), perhaps a better approach to help conserve GA hit volume is to include both `'fl-map-miles-moved'` and something like `'fl-current-zoom-depth'` along with the event `fl-search` to conserve traffic volume

Description of Interaction | Data Layer Screenshot | Test Status | Notes
------------ | ------------- | -------------  | ------------- 
Zoom In | ![image](https://user-images.githubusercontent.com/48527022/93819732-1dfa7280-fc2a-11ea-8367-6bcde3b890eb.png) | ❌  **DOES NOT PASS** | • See comment above in this section, consider pivot
Zoom out | ![image](https://user-images.githubusercontent.com/48527022/93820059-97926080-fc2a-11ea-89a4-f6323fe83ee8.png)  | ❌ **DOES NOT PASS** | Same issue as described prior

</details>

## Acceptance Criteria
- [ ] Sign off from analytics team (@jonwehausen @bmcgrady-ep @bsmartin-ep) 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
merged
