### ISSUE TITLE
[Design] Conversation Guide for Usability Testing of EDU Direct Deposit

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13808]
## Story  
As a design researcher, I want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users I will be communicating with.

## Considerations
- Conversation guides are usually incorporated into Research Plans but because they are large enough, we separate them.  Both are considered deliverables.
- **Ask Samara:** will frontend be ready or do we need a prototype? (We could adjust the mockup to suffice with limited functionality)

## Tasks
- [ ] Coordinate with Samara on some of the questions to ask in the conversation guide, if needed
- [ ] Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/discovery-conversation-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
## Acceptance Criteria
- [ ] Conversation Guide has been started to later be sent to Shawna for review

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing

**Comment by sporeboy** [comment]
Here is the link to the initial draft of the convo guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing/dd-edu-convo-guide.md
