### ISSUE TITLE
Conduct Discovery and Research for EDU Direct Deposit

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13802]
## Background
The work for the Education section's direct deposit functionality is ready to be migrated out of eBenefits and into VA.gov.  We want to perform discovery and research on what the current landscapes, use cases, functionality and stakeholder objectives might be to better inform a first version mockup or prototype.

## Potential Use Cases
1. As a Veteran receiving payments, I want to be able to clearly view the direct deposit information so I can be sure the at funds are going to the right place securely and accurately.
1. Add new direct deposit account for the Veterans EDU payments
1. Change their direct deposit information for the Veterans EDU payments
1. Turn off direct deposit information for the Veterans EDU payments
1. Access a link to view payments

## Considerations from original C&P work
- [Epic](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17530)
- [Usability](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18452)
  - [Test plan](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18499)
  - [Conversation Guide](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18593)

## Tasks
- [x] Review and create thumbnail walkthrough of feature in eBenefits; [save in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/add-update-EDU-direct-deposit/research-design)
- [x] Summarize findings and initial questions in an [.md file in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/add-update-EDU-direct-deposit/research-design/README.md)
- [ ] Discuss with stakeholders any questions that arise
```diff
+ Luke Tickner (sp?): Who should we reach out to? Who are the points of contact?
- Can we review the BE endpoints to know if there is a different service call? Can we chat with Lihan for a few?
- (Would like to learn how the transaction flows/ data structured)
```
 **Next Steps:**
- [ ] Draft initial mockups for review, to be shared with Auth Exp Team (2 of 3)
- [ ] Prepare and conduct usability sessions after getting approval of Research Plan and Conversation Guide (3 of 3)

## Acceptance Criteria
- [x] A thumbnail walkthrough of steps to take, as found in discovery, is created and shared with the Auth Exp Team
- [x] Notes summary is drafted and made available in .md file in [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/add-update-EDU-direct-deposit/research-design/README.md)
- [ ] A meeting has been scheduled with stakeholders to ask questions compiled in the notes/summary .md file (above), if needed

**Comment by Samara-Strauss** [comment]
One thing I don't see captured here which we need: as best we can, a list of what education benefits get updated when direct deposit for edu gets updated. You can include that here, or create a separate ticket (I would recommend a separate ticket). Let me know if you have any questions about that.

**Comment by Samara-Strauss** [comment]
@sporeboy now that it's officially the new sprint, keep me posted for how this goes as you're working on it. When you're ready, I'll reach out to Luke Tickner to see who we can talk to about the questions we have.

**Comment by sporeboy** [comment]
Reviewed feature in eBenefits and pulled screen caps. Stubbed-out [research/design page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/add-update-EDU-direct-deposit/research-design/README.md) and [discovery/flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/add-update-EDU-direct-deposit/research-design/dd-edu-user-flows.md).

**Comment by Samara-Strauss** [comment]
@sporeboy I clicked through a bunch of links in those docs and don't see notes on the current feature in eBenefits. Apologies if I'm overlooking something obvious. Can you clarify where these notes are?

**Comment by sporeboy** [comment]
I have a WIP discovery doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/edu-dd-discovery.md

@Samara-Strauss sorry--I somehow missed your question 9/24. Monday and Tuesday were eaten up by usability sessions. I dropped some of my notes/screens/diagram into the link above.

**Comment by sporeboy** [comment]
Questions from discovery doc:

- Do potential users of this feature include **dependents**?
- So, does direct deposit info include **dependents’** C&P, education and DIC payments?
- Does direct deposit cover Special Monthly Payments (SMC) made to veterans?
- Where is the C&P/EDU direct deposit crossover (did not find this in initial pass)?
- How often do users choose different bank for C&P vs. EDU deposits?
- How long does it take to initially enroll in and set up direct deposit; how long to see a change take effect?
- How are user's entry errors handled (e.g. incorrect account type or number)?
- Account info confirmation was required in eBenefits; why is that absent on VA.gov?
- Are payment recipients allowed to use paper forms (e.g. the 29-0309)? Are they discouraged from this?
- What other common questions might be better answered on the DD form screen itself vs. the landing page (e.g. timeframe when enrolling)?

**Comment by sporeboy** [comment]
Added uses cases to discovery doc; may add use case flow diagram if time permits.
