### ISSUE TITLE
Clear wizard flag on form restart

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#13814]
### Background

With the form wizard being moved to the introduction page, a session storage flag is set to indicate whether the page should render the wizard or intro page content. Once the wizard is complete, the session flag is set and the intro page content is rendered (subway map, etc).

Once the form is started, a "Finish this application later" link is displayed under the form's "Back" and "Continue" button. If used, the user will be redirected to a `/form-saved` page - rendered by the `FormSaved` and `FormStartControls` components.

### The problem

The user is given a choice to start the form over

![Screen Shot 2020-09-21 at 4 46 50 PM](https://user-images.githubusercontent.com/136959/93827628-3ae57480-fc2f-11ea-90b3-f1dfd39c3701.png)

The second choice of "Start a new application" opens a modal to confirm, then immediately sends the user to the first page of the form. It bypasses the introduction page, and more importantly the wizard. Form 526, needs the wizard to save a user's separation date and Form 0996 (HLR) will need to save a Veteran's claim type. The HLR value will be essential when submitting the form. This also occurs with the educational benefits forms where the choice of forms is not reset.

Flow diagram (step 4): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md#userpage-flows-

 ### What needs to be done

The "Start a new application" needs to either preserve the stored wizard form data, or restart the form from the introduction page, _and_ reset the wizard "completed" flag so the wizard is again revealed.

## Tasks

- [ ] Update `FormStartControls` component to reset the form completion flag & return the user to the introduction page; but only if the form includes a wizard
- [ ] Ensure the correct form completion flag is reset (at the time of this writing, the reset is _always_ global) once the code is in place

## Acceptance Criteria

- [ ] Using "Start a new application" sends the user to the appropriate destination: wizard or first page of form

**Comment by Mottie** [comment]
State of forms that need to be updated:
- [x] 526/BDD
- [x] HLR
- [ ] Education VA Form 1990
- [ ] Education VA Form 1990N
- [ ] Education VA Form 1990E
- [ ] Education VA Form 1995
- [ ] Education VA Form 5490
- [ ] Education VA Form 5495
- [ ] Education VA Form 10203
- [ ] Education VA Form 0994
- [ ] VRE Chapter 31 (VA Form 28-1900)
- [x] VRE Chapter 36 (VA Form 28-8832)
- [ ] FSR VA Form 5655

Will contact appropriate teams - instructions for updating can be found here - https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/wizard - once the document page updates.
