### ISSUE TITLE
Create Initial Mockup for EDU Direct Deposit

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13810]
## Goal
Based on research findings and existing product documentation, we want to create an initial mockup of the feature to start iterating.

## Considerations
There may be more than 1 mockup to show various states, but the intent will be to share this (these) with the Authenticated Experience Team. Mockups will incorporate existing UI elements/patterns from previous DD feature.
- [ ] Content page may need updates - how should this change? (may be another ticket)

## Tasks
- [ ] Create mockups for this feature based on existing research, so that FE engineering can make a first product pass.
- [ ] Include "Edit" state  
- [ ] May need "Add " state  

## Acceptance Criteria
- [ ] A mockup has been created and shared with the Auth Exp team.

**Comment by sporeboy** [comment]
Initial screen layouts done: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/

- Initial state
- Edit state
- Edit state field errors

Other states need to be identified. Content and design needs refinement per stakeholder input and team feedback.
