### ISSUE TITLE
Conduct Usability Sessions for EDU Direct Deposit

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13812]
## Goal
Conduct usability sessions for Direct Deposit for EDU to understand how a Veteran is currently interacting with this feature holistically so that we can create a more accurate description of what needs to be further developed or iterated upon.

## Considerations
- Use a research plan and conversation guide (included in previous delivery, linked below)
- Conduct a usability session that answers pain point questions and informs the team what the best thing to build might be
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)
- Estimated to start Monday after Thanksgiving, November 30, 2020

## Tasks
- [x] Incorporate feedback from usability testing prep for research plan
- [x] Kickoff recruiting with Lauren
- [x] Coordinate sessions with user research partner (Perigean), asking them to take notes 
- [x] Use the [research plan](#), and included [conversation guide](#) to conduct sessions

## Acceptance Criteria
- [x] Usability study has been conducted 
`(Initial synthesis due 7 days from last session)`

**Next steps:** draft tickets for topline summary and research analysis ✔

**Comment by sporeboy** [comment]
Research plan and convo guide submitted 11/20. Sessions scheduled 12/2 to 12/7.

**Comment by jason-gcio** [comment]
@sporeboy, @Samara-Strauss - I propose we move this to the next sprint and replace it with a ticket that reflects what has been done this sprint

**Comment by Samara-Strauss** [comment]
That's fine with me. No need to create any other tickets unless there's additional work that hasn't been documented.

**Comment by sporeboy** [comment]
First five sessions conducted; two more will follow to ensure at least one female participant.

**Comment by sporeboy** [comment]
Sixth and final session conducted 12/7/20.

**Comment by Samara-Strauss** [comment]
Great! We can close this.
