### ISSUE TITLE
View Dependents - Change `vagovprod` From False to True

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13828]
## Description
In order to conduct UAT for the View portion of the app, it needs to be in production, once we see the application is working properly.

## Tasks
- [ ] Update the entry in `registry.json` needs to have the `vagovprod` flag updated from `false` to `true`. 
- [ ] Update breadcrumb urls, as needed - re-add the breadcrumb for the 686c that points to view-dependents
- [ ] ~~Request on off-cycle deploy~~
- [ ] Log in to Flipper and update the toggle

## Acceptance Criteria
- [ ] The View task is in prod
