### ISSUE TITLE
Design intent Collaboration - learning center responsive tables for About template

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13825]
## Context

Requesting an async review  (per Slack) for some changes I'm proposing to improve mobile UX in the learning center.

This particular ticket is to make tables responsive for the `About` template.  [Here's Ryan's desktop design](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b?wid=0-1588252971615). The learning center is leveraging the existing table component in our CMS, but it's not responsive.

We've explored many different solutions, including a straight implementation of what is [being considered for adoption](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/203) into the design system.  I worked closely with Jennifer Strickland on this, and she identified some a11y improvements to that concept, which are reflected in the mock-ups below.

**What we are NOT doing now**

*including this for clarity, since there has been a lot of back-and-forth on this work*

- Providing solutions for comparison table use cases.  [We have concepts for these](https://app.mural.co/t/vsa8243/m/vsa8243/1599058756286/389fe124296d14b2ceee7ea532497e8e12c3aaad?wid=0-1599236806339) but want to learn from this MVP responsive version and understand how tables are used in the learning center before we take those concepts further

- Implementing sticky headers or sticky functionality.  We started to explore this and identified some complexities that need to be solved for, and wouldn't be in scope for an MVP solution.

- Submitting this for review to be adopted globally, or into the design system.

  

## Steps to complete Design Intent Collaboration

- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to determine how much time reviewers have to provide feedback
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts

- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)
- Mock-ups
  - [Screen 1](https://preview.uxpin.com/e7717d3fa019146277f28d799d247b820140d1b5#/pages/132642759/documentation/no-panels?mode=i) - shows what we **hope** can be implemented completely by the FE (no CMS updates required), for MVP 1.0
    - includes a show/hide functionality that collapses columns 2-12, for tables that have 3 or more columns.  
    - Includes a variation on the additional info component
    - This may not be MVP 1.0 if it requires CMS work.
    - There is documentation about a required `<caption>` element - this is the one piece I suspect needs CMS changes to implement.
  - [Screen 2](https://preview.uxpin.com/e7717d3fa019146277f28d799d247b820140d1b5#/pages/132642760/documentation/no-panels?mode=i) 
    - shows what this would look like if a cell was expanded
    - contains some additional documentation.
  - [Screen 3](https://preview.uxpin.com/e7717d3fa019146277f28d799d247b820140d1b5#/pages/132642765/documentation/no-panels?mode=i) - shows 2 things:
    - What a 2 column table would look like (doesn't get show/hide) AND
    - The pattern our responsive table can follow if the show/hide functionality turns out to be out of scope for MVP 1.0

## Meeting attendees from **requesting team**

Feedback to be provided async.  

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled feedback for EOD Thursday 9/24 Thanks @andaleliz !

**Comment by jenstrickland** [comment]
## VSA Accessibility Feedback

Since the VSA accessibility specialist was heavily involved in the design and documentation of this component, I don't plan to document additional specific feedback for this MVP component. 

- I did message Liz to request that we **should** document at what viewport width we plan to collapse columns 2–12, so that we have all the info and are in agreement.
- Developers **should** coordinate a dev intent review with the VSA accessibility specialist before beginning development (have already contacted Mickin and Brian about this, Liz let Kelson and Nick know).
- Development **should** use the [semantic markup provided](https://codepen.io/jenstrickland/pen/YzqejpG) by the accessibility specialist
- Designer **should** document focus management for when the collapsed row is expanded/collapsed. It is expected it would behave the way the additionalinfo component does (where focus remains on the `button` that expands/collapses).

cc @1Copenut for review

**Comment by mpeterz** [comment]
IA feedback:
Looks great! Understand this is MVP. Looking forward to seeing comparison tables to help Veterans make decisions by comparing info across rows in a table. 

+1 with @jenstrickland on documenting at what viewport width we plan to collapse columns 2–12.

**Comment by andaleliz** [comment]
Thanks @jenstrickland and @mpeterz - [created an issue for myself](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13972) so this documentation gets done, and pinged the devs so they know it's coming. They're not building this template yet, so I will prioritize this once they have the green light to move forward.

**Comment by CrystabelReiter** [comment]
@andaleliz The way you designed the tables looks good from the VSP design side! Thanks for looping us in

**Comment by andaleliz** [comment]
Thanks so much @CrystabelReiter! I'll wait for @1Copenut to chime in before closing this out.

**Comment by andaleliz** [comment]
@1Copenut do you have anything to add before I close this out?

**Comment by 1Copenut** [comment]
@andaleliz && @jenstrickland I agree with the [VSA accessibility feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13825#issuecomment-697014817) with one consideration for the table HTML structure.

What do you both think about making the first `<td>` into a `<th>` and remove the inner DFN tag? In my screen reader testing, having the first cell marked up as a `th[scope="row"]` announces that row "header" when I move asynchronously. For instance, if I'm on the third column of row two, then jump directly to the third row, third column, the third row heading will be read out for context.

Léonie Watson uses this markup pattern in her new article [How screen readers navigate data tables](https://tink.uk/how-screen-readers-navigate-data-tables/).

No other feedback from me. Thank you!

**Comment by andaleliz** [comment]
@1Copenut Thank you! I'll close this out. The mark-up in the codepen example is @jenstrickland's suggestion, so I'll defer to her to consider that. It sounds reasonable to me.  I'm in support of whatever mark-up we need to provide the best screenreader experience possible.

**Comment by jenstrickland** [comment]
I can see the point of using a `<th scope="row">` for the first column of each row. We would need to retain the `<dfn>` to communicate the data — as we went through quite a bit in our collaboration sessions when I tried to move the info to the heading.

**Comment by 1Copenut** [comment]
@jenstrickland So if I'm understanding correctly, a row in the table body could look something like this?

```html
<tr role="row">
  <th role="cell" sope="row">
    <dfn>SMC-K</dfn>
  <th>
  <td role="cell">110.31</td>
  <td role="cell">If you qualify for SMC-K...</td>
</tr>
<!-- additional table rows -->
```
If that's your understanding, we are 💯 If you've got a different idea, we can review outside of this design intent ticket.

**Comment by jenstrickland** [comment]
The markup would look like this:

```diff
                <tbody>
                    <tr role="row">
+                        <th role="rowheader" scope="row> <!-- add rowheader role; set scope of th to row -->
                            <dfn>SMC letter designation</dfn> <!-- provides the column heading for mobile, but hides in desktop view -->
                            <span>SMC-K</span> <!-- the value of the row header -->
                          </th>
                        <td role="cell"><dfn>Monthly payment (in&nbsp;U.S.&nbsp;$)</dfn><span class="currency">110.31</span></td>
                        <td role="cell"><dfn>How this payment variation works</dfn><span class="paragraph">If you qualify for SMC-K, we add this rate to your basic disability compensation rate for any disability rating from 0% to 100%. We also add this rate to all SMC basic rates except SMC-O, SMC-Q, and SMC-R. You may receive 1 to 3 SMC-K awards in addition to basic and SMC rates.</span></td>
                    </tr>
```

**Comment by 1Copenut** [comment]
@jenstrickland thank you! I'll refer to this for the GIBCT responsive table. It's in staging, but needs the role updated and the `<dfn>` added to restore headings at mobile size. Much appreciated.
