### ISSUE TITLE
Automated, scheduled deploys of Jenkins master

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#13823]
## Issue Description
Work was done in [this pull request](https://github.com/department-of-veterans-affairs/devops/pull/7369) to make the OS Check jobs not rely so heavily on naming as it was missing instances that did not include the "-asg" portion of a `Name` tag. With that merged however, the OS Check for the utility environment fails daily due to how long it has been since Jenkins master has been deployed. This will continue to be a daily failure for that particular job until an automated method or even scheduled manual method is implemented to ensure the deployed master does not reach an age of >14 days.

---
## Tasks
- [ ] Team should decide on whether automated method is worth the time and effort in light of eventually sunsetting Jenkins or if we need manual intervention to hold us over a bit longer
- [ ] Team stand by decision and ensure Jenkins is deployed anew before the 14 day mark going forward

## Acceptance Criteria
- [ ] A process / solution in place to prevent Jenkins from being the cause of OS Check failures in the utility environment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/CJYRZK2HH/p1631279782326600

**Comment by jhouse-solvd** [comment]
Let's leave this in the icebox and either schedule some new monthly deploys, or decide to put in the work to do this.

**Comment by jbritt1** [comment]
Should we close this? I think our intention is to continue to move towards sunsetting Jenkins vs spending time on more automation around it.
