### ISSUE TITLE
Add translation disclaimer to Coronavirus FAQs page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13824]
### User story
As a user seeking coronavirus-related information from VA in Spanish, I need to understand the limitations of the provided translation.

---
## Tasks
- [x] Review disclaimers on other government websites using the Google translate widget
- [x] Create disclaimer
- [x] JTF review
- [x] Determine placement + add to page

## Acceptance Criteria
- [x] Disclaimer is live on page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
**Update:** May not need this is we go another route. Iceboxing for now.

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow Just noting that I'm closing this. Final result: We added a disclaimer about timeliness of translated content based on the CDC COVID-19 website disclaimer. Thanks!
