### ISSUE TITLE
[FE] My VA: Cerner go-live updates for Spokane facilities on 10/24

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#13832]
## Background

Design and content in #13831.

We've got another Cerner update. This time, facilities in Spokane, WA (Mann-Grandstaff) goes live on 10/24. We need to update the My VA dashboard as follows to account for people who are now going to be using Cerner for medical tools.

### Design & Copy

![Screen Shot 2020-09-29 at 1.30.10 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/3b752ef4-5c83-4764-8557-99049d966f42)

## Send or receive a secure message

_[alert]_

#### Our records show you’re registered at:

**Mann-Grandstaff VA Medical Center** (Using VA My Health)

Please choose a health management portal below, depending on your provider’s facility. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Send a secure message to a provider at:

**Mann-Grandstaff VA Medical Center**

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to My HealtheVet

_[end alert]_

![Screen Shot 2020-09-29 at 1.30.15 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/1420341a-f454-4ca5-8fac-9cbde52b7a1c)

## Refill and track prescriptions

_[alert]_

#### Our records show you’re registered at:

**Mann-Grandstaff VA Medical Center** (Using VA My Health)

Please choose a health management portal below, depending on your facility. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Refill prescriptions from:

**Mann-Grandstaff VA Medical Center** 

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to My HealtheVet

_[end alert]_

![Screen Shot 2020-09-29 at 1.30.21 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b63eebf5-3579-4d69-b2b7-4f691b9cf6a3)

## View, schedule, or cancel an appointment 

_[alert]_

#### Our records show you’re registered at:

**Mann-Grandstaff VA Medical Center** (Using VA My Health)

Please choose a health management portal below, depending on the facility for your appointment. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Manage appointments at:

**Mann-Grandstaff VA Medical Center**

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to the VA appointments tool

_[end alert]_

![Screen Shot 2020-09-29 at 1.30.36 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/88c88130-3243-454e-a49b-43b0a52b64ac)

## View, schedule, or cancel an appointment (both facilities) 

_[alert]_

#### Our records show you’re registered at:

**[Facility 1]** and **[Facility 2]** (Using VA My Health)

Please choose a health management portal below, depending on the facility for your appointment. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Manage appointments at:

**[Facility 1]** or **[Facility 2]**

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to the VA appointments tool

_[end alert]_

### Specs

- The messages under "Refill prescriptions" and "Secure messages" should only show if someone is detected to be a patient in Spokane (Mann-Grandstaff). You **do not** need to also show any prescriptions or messages that we might detect.
- For "Schedule an appointment," we have three possible scenarios:
  - Someone is a patient in Columbus, OH (Chalmers P. Wylie). **Show the block for Columbus that is already live**
  - Someone is a patient in Spokane, WA (Mann-Grandstaff). **Show the block for Spokane shown above**
  - Someone is detected as having been a patient in both Columbus, OH (Chalmers P. Wylie) and in Spokane, WA (Mann-Grandstaff). This is likely to be very rare, but not totally impossible. **Show the block above that mentions both facilities**
- **If someone is not detected to be a patient at either facility, there are no changes to My VA. The functionality we have no should stay the same.**

### Staging user credentials

https://dsva.slack.com/archives/CU9KYKMM5/p1596219870127100?thread_ts=1596217577.125000&cid=CU9KYKMM5

## Tasks

- [ ] Update My VA dashboard to point Spokane patients to Cerner.
- [ ] Validate this works with staging users.
- [ ] Gate this to go live with the other 10/24 updates.

**Comment by tressaellen** [comment]
@erikphansen - question on the last screenshot [View, schedule, or cancel an appointment (both facilities)], is it possible to detect if a user has used more than one facility in Cerner?


Here is all the content for these alerts:

![Screen Shot 2020-09-29 at 1.30.10 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/3b752ef4-5c83-4764-8557-99049d966f42)

## Send or receive a secure message

_[alert]_

### Your VA health care team may be using our new My VA Health portal

#### Our records show you’re registered at:

**Mann-Grandstaff VA Medical Center** (Using VA My Health)

Please choose a health management portal below, depending on your provider’s facility. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Send a secure message to a provider at:

**Mann-Grandstaff VA Medical Center**

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to My HealtheVet

_[end alert]_


![Screen Shot 2020-09-29 at 1.30.15 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/1420341a-f454-4ca5-8fac-9cbde52b7a1c)

## Refill and track prescriptions

_[alert]_

### Your VA health care team may be using our new My VA Health portal

#### Our records show you’re registered at:

**Mann-Grandstaff VA Medical Center** (Using VA My Health)

Please choose a health management portal below, depending on your facility. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Refill prescriptions from:

**Mann-Grandstaff VA Medical Center** 

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to My HealtheVet

_[end alert]_


![Screen Shot 2020-09-29 at 1.30.21 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b63eebf5-3579-4d69-b2b7-4f691b9cf6a3)

## View, schedule, or cancel an appointment 

_[alert]_

### Your VA health care team may be using our new My VA Health portal

#### Our records show you’re registered at:

**Mann-Grandstaff VA Medical Center** (Using VA My Health)

Please choose a health management portal below, depending on the facility for your appointment. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Manage appointments at:

**Mann-Grandstaff VA Medical Center**

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to the VA appointments tool

_[end alert]_

![Screen Shot 2020-09-29 at 1.30.36 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/88c88130-3243-454e-a49b-43b0a52b64ac)

## View, schedule, or cancel an appointment (both facilities) 

_[alert]_

### Your VA health care team may be using our new My VA Health portal

#### Our records show you’re registered at:

**[Facility 1]** and **[Facility 2]** (Using VA My Health)

Please choose a health management portal below, depending on the facility for your appointment. You may need to disable your browser’s pop-up blocker to open the portal. If you’re prompted to sign in again, use the  same account you used to sign in on VA.gov. 

#### Manage appointments at:

**[Facility 1]** or **[Facility 2]**

_[button]_ Go to My VA Health

**Another VA health facility**

_[button]_ Go to the VA appointments tool

_[end alert]_

**Comment by erikphansen** [comment]
@tressaellen I'm giving a soft "yes" to if we can show multiple facilities in the alert. We should get all the facilities they are registered in. So we could show the names of all the Cerner facilities that they are patients at.

**Comment by tressaellen** [comment]
@erikphansen okay, I think that should work. Thank you!

**Comment by erikphansen** [comment]
@tressaellen based on the approach I'm taking for this we will be able to show _all_ the Cerner facilities someone is a patient in. This goes for all the Cerner widgets. For example: if they are a patient at two facilities that offer Rx, we could show both facility names in the Cerner Rx widget.

Question for you: do you want to cap the number of facility names we show? Or just show them all? Right now there are only two Cerner facilities, and at this point one of them only offers appointments so this isn't a concern. But in the future, in theory, a user might be a patient at more than 2 facilities that have Rx capabilities through Cerner. My thought is we should show all the qualifying facility names. Less edge-casey code and it seems very unlikely that someone will be a patient in a ton of Cerner facilities. And if they _are_ we would have no good way to determine which facilities to show and which to not show.

**Comment by tressaellen** [comment]
@erikphansen - that sounds good to me. I agree, I don't think the chances of someone being a patient a ton of facilities is very high. Let's go ahead and show all of them and if there seems to be a problem with that, then we can re-assess.

**Comment by erikphansen** [comment]
@tressaellen In the current version of the Cerner appointments alert, the second CTA button is labeled `Go to the VA appointments tool` and links to `/health-care/schedule-view-va-appointments/`.

- [ ] Are these mocks correct that the button should now read: `Go to My HealtheVet`? 
- [ ] Where should the `Go to My HealtheVet` button link to?

**Comment by Samara-Strauss** [comment]
> Are these mocks correct that the button should now read: Go to My HealtheVet

Ah good catch — they should go to the VAOS tool. @DanielleThierryUSDSVA  what should the CTA say for appointment CTA say for non-Cerner patients? The mock says "Go to My Healthevet" but scheduling is (obviously) done in VAOS now. Should we change to something like "Schedule an appointment"?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss. CTA button should say "Go to the VA appointments tool" Thanks!

**Comment by Samara-Strauss** [comment]
Thank you! @erikphansen — "Go to the VA appointments tool" for that CTA instead, please 😄

**Comment by erikphansen** [comment]
Okay, so the text is right (and matches what we use), the mock is just slightly wrong. Thanks!

**Comment by erikphansen** [comment]
What about the other two `Go to My HealtheVet` buttons on the Rx alert and the Secure Messaging alert? Where do those link to?

**Comment by Samara-Strauss** [comment]
Those should link to My HealtheVet — whatever URLs we link to now for the Secure Messages and Rx tools (should be in the code).

**Comment by erikphansen** [comment]
So now that a PR for this work is up, @sanlouise had a great question which is essentially: should we be showing the `Another  VA health facility` text and its button when a user is only shown as being a patient at a Cerner facility? Or, put another way, why are we inviting them to manage appointments, messages, and/or prescriptions at non-Cerner facilities if they are only a Cerner patient?

**Comment by Samara-Strauss** [comment]
> So now that a PR for this work is up, @sanlouise had a great question which is essentially: should we be showing the Another VA health facility text and its button when a user is only shown as being a patient at a Cerner facility? Or, put another way, why are we inviting them to manage appointments, messages, and/or prescriptions at non-Cerner facilities if they are only a Cerner patient?

I don't have a good reason for this, only a bad one — we copied the pattern for unauthenticated content pages, on which I don't think they're checking to see if someone is part of one facility or another. I think this is a really good point, and we can figure out how to take a more precise approach with the My VA 2.0 work.

**Comment by erikphansen** [comment]
I _wonder_ if it's possible for:
(a) the facility data we get might not be correct 100% of the time so the might also be a patient at a non-Cerner facility
(b) there to be a valid reason for someone to make an appointment at a non-Cerner facility even if they are not currently a patient there

🤷

**Comment by erikphansen** [comment]
Assuming we trust the list of facilities that we get for each user, we absolutely could be more granular about what we show users: Cerner content only, non-Cerner content only, or both Cerner and non-Cerner content, in case you did want to change things up in the future.

**Comment by Samara-Strauss** [comment]
> (a) the facility data we get might not be correct 100% of the time so the might also be a patient at a non-Cerner facility
> (b) there to be a valid reason for someone to make an appointment at a non-Cerner facility even if they are not currently a patient there

Yeah, not sure about this. I think we can leave things as-is for now.
