### ISSUE TITLE
[Spike] Formulate strategy for accessing appointments data via MAP in dev/staging/production environments

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#13834]
How can access to the MAP sandbox be accomplished in the staged environment or in a draft PR through the health quest service ? 

This ticket is related to administration and has no related coding requirements or that should be very minimal if anything

The Health Quest Service uses a similar configuration in settings as VAOS does. Here is what VAOS looks like. As you can see, in the dev environment there is nothing there because VAOS in Dev has no connection whatsoever: 

```
va_mobile:
  url: 'https://veteran.apps.va.gov'
  mock: false
  key_path: /fake/client/key/path
  timeout: 15
```

The Health Quest has the same type of configuration derived from how VAOS does this, but the release process for staging and production would need to take this into account or would need to know about it. This example shows the use of a locally stored private key to access the sandbox

```
hqva_mobile:
  url: 'https://veteran.apps.va.gov'
  mock: false
  # key_path: /fake/client/key/path
  key_path: /Users/laurenceguild/my-play-certs/sandbox_rsa
  timeout: 15
```

## Tasks
- [ ] Determine how can we access the sandbox in each environment for staging/dev
- [ ] Determine if the requirements have changed because of the need to use getCare API
- [ ] Determine what the release process needs to add

## Acceptance Criteria
- [ ] Document findings

**Comment by abuckley3385** [comment]
@stephenBarrs @massrb  please see title/description of this ticket _Figure out staging strategy for appointments and PGD_ it was my impression we are good on MAP PGD for sandbox data and access (once myself and PO provide FHIR mapping). The need for this ticket discussed in planning today was only for appointments - did i misunderstand and its both?

**Comment by massrb** [comment]
@abuckley3385 , they both work the same way PGD/Appointments using the same settings 


I added this document 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/connection-to-sandbox.md

**Comment by massrb** [comment]
I had to add a new task: 

> Determine if the requirements have changed because of the need to use getCare API

**Comment by massrb** [comment]
Stephen indicated that the use of GetCare only is related to the actual fhir record structures and not to any speciic GetCare api or any changes to access so that we will still be using the fhir client approach

@Stephen Barrs, Are we going to use the same api as GetCare for the PGD ? I think that might mean that using a fhir client won't be how it will work or that we will go through that GetCare API for everything for PGD related requests ?

> Stephen Barrs  10:30 AM
We will still go directly to the PGD FHIR API.  The only thing shared will be the initial Q/QR structure in the PGD.

**Comment by stephenBarrs** [comment]
The URLs for MAP are:

- Sandbox: https://vagovtest.mapsandbox.net
- Staging: https://veteran.apps-staging.va.gov
- Prod: https://veteran.apps.va.gov

Each MAP environment will have a key pair associated with it.  
- The Private key will be stored in vets-api CredStash and will be used to sign the originating token that will be passed to MAP/User-Service/JWT Exchange.  
- The public key will be configured in each MAP environment as a Consul variable used by User-Service.  These public keys will be delivered to Lynne Case who will create Jira tickets to have the public keys added.

**Comment by massrb** [comment]
ok, great so do you have to open a ticket for that at the appropriate time ? If myself or someone else can't do it then I will note that specifically in the document.


> Stephen Barrs  11:07 AM
Lynne will receive the public keys from vet-api devops team.  Once she has them and we have an approved FHIR mapping she will open the Jira tickets and add the keys to Staging and Prod.

**Comment by massrb** [comment]
There is enough in the document now that you could call this ticket about done. The only question I had was who sets up the small config/setting.yml change in the staging and prod environments which is a minor detail

**Comment by dillo** [comment]
This is a duplicate of https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12776. Closing.
