### ISSUE TITLE
Upgrade Cypress to 6.2.1

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#13849]
# Description
Cypress 5.x got a retry mechanism and some UI improvements, but we held off on upgrading due to some performance concerns.

Those performance issues have been resolved in 5.2.0, so we should be able to upgrade now.

# Tasks
- [x] Analyze [changelog ](https://docs.cypress.io/guides/references/changelog.html#6-0-0)for potential pitfalls to upgrading
- [x] Create vets-website branch to install and test upgrade
- [x] [Create documentation in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/testing/end-to-end) that lists all actions that teams will need to take in order to migrate their tests from Cypress 4 to Cypress 6.
- [x] Notify teams that the upgrade is coming and where our documentation is

# Acceptance Criteria
- [x] Verify there are no regressions to existing Cypress tests
- [x] Verify changes in dependencies are dealt with gracefully

**Comment by pjhill** [comment]
Per discussion between testing team and FE tools, testing team will own the task of maintaining Cypress going forward.

**Comment by U-DON** [comment]
As of today, [Cypress has gone up to 6.0.0](https://docs.cypress.io/guides/references/changelog.html#6-0-0).

**Comment by pjhill** [comment]
> As of today, [Cypress has gone up to 6.0.0](https://docs.cypress.io/guides/references/changelog.html#6-0-0).

We're too slow!  Thanks, I think we will be doing this next sprint.

**Comment by erikphansen** [comment]
Oh 6.0.1 came out an hour ago so it's definitely ready for prime time now!

**Comment by pjhill** [comment]
Cypress 4.8 run:
![Cypress-4-8.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/04ea9b9d-daf3-42f2-bb5e-00fb1adb444c)

Cypress 6.0.1 run:
![Cypress-6-0-1.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/758a9f3e-8070-46fc-93fd-1753501e7cef)

**Comment by pjhill** [comment]
The common list of failing tests are -

1. applications/facility-locator/tests/e2e/search.cypress.spec.js
2. applications/gi/tests/e2e/03-vet-tec.cypress.spec.js
3. applications/gi/tests/e2e/04-dea.cypress.spec.js
4. applications/gi/tests/e2e/05-ojt.cypress.spec.js
5. applications/gi/tests/e2e/07-gibct-mobile.cypress.spec.js

**Comment by erikphansen** [comment]
Is that time difference for running the full suite for real? From ~22min to ~12min?!

**Comment by pjhill** [comment]
[Cypress 6.0 migration guide](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-6-0)

[Cypress 5.0 migration guide](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-5-0)

**Comment by pjhill** [comment]
> Is that time difference for running the full suite for real? From ~22min to ~12min?!

Yes, I noticed that nice little speed increase as well! It probably warrants running a few times and averaging to get a more accurate number, but I think we can be confident that the upgrade is headed in the right direction as far as execution speed goes.

**Comment by JoeTice** [comment]
Moving to future initiatives till after holiday code freeze, will plan to execute this on Jan 4 2021

**Comment by pjhill** [comment]
@JoeTice 
- [ ] Check for platform guidance around VFS team notification of upgrades affecting teams -- news letter? standard warning time?

**Comment by pjhill** [comment]
It looks like CircleCI is attempting to install the wrong/old version of Cypress in the upgrade branch -- weird.

https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-website/20119/workflows/fcf942e5-7e10-4546-8b0b-afe879130071/jobs/170914/steps

> `URL: https://download.cypress.io/desktop/4.12.1?platform=linux&arch=x64`
>` Error: Corrupted download`

We need to resolve this issue before we go live with the upgrade.

**Comment by pjhill** [comment]
PR merged, and it's looking like we shaved ~2 minutes off CI test execution runs -- hooray!
