### ISSUE TITLE
[DO NOT PUBLISH UNTIL JANUARY] Edits to VA.gov pages that mention chapter 36 benefits 

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#13842]
## Issue Description
**Note:** Updates to the main page (https://www.va.gov/careers-employment/education-and-career-counseling/) are already in draft state in drupal.

Update surrounding pages that have mentions.
- [ ] careers-employment/index.html  (Lowercased "educational and career counseling" and rewrote ch. 36 teaser)
- [ ] service-member-benefits/index.html  (Rewrote ch. 36 teaser)
- [ ] careers-employment/careerscope-skills-assessment/index.html  (In the bullet at the bottom of page, I lc'd the benefit name; rewrote the link label)
- [ ] careers-employment/dependent-benefits/index.html  (Edits throughout this page. Please copyedit the whole page, and refer to the live page if you need to for context for some of the movement of content block. I also need your help reinstating the green button that's now appearing as a text link for some reason: "Go to eBenefits to apply")
- [ ] education/eligibility/index.html  (Edits to 4th and 7th Q&As; revised text and link language in the note at the bottom of the page)
- [ ] education/how-to-apply/index.html (Edited the text in the note and in the chapter 36 teaser)
- [ ] education/index.html
- school-administrators/index.html

Implement changes to the above pages from the track changes in this Word doc: 
[https://app.zenhub.com/files/133843125/8fd54d69-2761-4ffc-9e2d-0dc62781c5d6/download](https://app.zenhub.com/files/133843125/8fd54d69-2761-4ffc-9e2d-0dc62781c5d6/download)

---
## Tasks

**Note:** Mikki's IA summary/suggestions, for reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt36.md

- [x] Incorporate edits in drupal to the above listed pages. 
- [ ] In every node where you make edits, please lowercase the name (so it's de-branded) in the meta description and title tag where necessary (anywhere you see the "old" name Educational and Career Counseling).
- [x] Add a link in the top nav to https://www.va.gov/careers-employment/education-and-career-counseling/. The link should be placed in the left "Get benefits" column and placed immediately after "How to apply".
- [x] Left nav update under Careers and employment left nav header--can be seen from this page: https://www.va.gov/careers-employment/education-and-career-counseling
- [ ] Left nav addition on the same page: https://www.va.gov/careers-employment/. Add link to left nav to "Apply now": www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/. The link will be a child of the Career planning and guidance option.
- [x] Alert Beth to review.
- [x] Hold on publishing until stakeholders give us the signal.
- [x] Publish all above listed pages.
- [x] Publish main page: /education-and-career-counseling/
- [x] Publish left nav and mega menu updates

## Acceptance Criteria
- [x] All the above listed pages get updated.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Update from Steve Kovaks: Go live date for this is now Jan 4 2021.

@RLHecht We probably want to hold off on this work now until after the first round of LC content for MVP has been entered into drupal. Do you agree? So content in draft state isn't sitting there for months.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I agree. @lunascoop has any work been done on any of these pages yet? I don't think so, but if so, can we take out the edits so that we don't have to worry about pages getting accidentally published early?

**Comment by lunascoop** [comment]
No, I haven't done anything yet. I saw Beth's message so I didn't move forward on this task.

**Comment by bethpottsVADEPO** [comment]
Latest agreed upon text with the stakeholder:

**Educational and career counseling (VA Chapter 36)**  @RLHecht as an fyi, because this is now used generically referring to the benefit rather than the program, I'm lowercasing.

Personalized Career Planning and Guidance (PCPG), or VA Chapter 36, offers free educational and career guidance, planning, and resources to Veterans and their dependents who are eligible for a VA education benefit. Find out how to apply for this program if you’re leaving active service soon or have been discharged within the past year.

@RLHecht Please copyedit, and then wait to hear from the stakeholder/me that we can publish. Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht Per confirmation from the stakeholder, we're good to publish this today. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lunascoop I'll handle these edits and @RLHecht can copyedit. Go ahead with the main page, and I'll let you know when I'm done with the surrounding pages.

**Comment by bethpottsVADEPO** [comment]
@RLHecht You can start editing the first 4 pages under "Issue Description" where I added checkboxes. As I finish editing the rest of the surrounding pages, I'll add checkboxes to those too. Please ignore the tasks section for now until I have a chance to revisit those. We may not get through all of them for the build on Monday, and that's fine. Let's focus on the edits to the surrounding pages first. 

If you have time, could you use a test user account and log into eBenefits to see if the fourth step in our subway map for these two pages matches what's in eBenefits? In other words, have they updated it with the new PCPG name, in which case we'd need to update our No. 4:
https://www.va.gov/careers-employment/dependent-benefits/
https://www.va.gov/careers-employment/education-and-career-counseling/

**Comment by bethpottsVADEPO** [comment]
@RLHecht The tasks section is now ready for you to complete! There's one left nav item that can't happen until the form is fully launched--add a link to the form. But other tasks you can proceed with. Let me know if you have any questions. It's ok with me if we keep this ticket open until January 4. But if you want to close this one out and create a new ticket, fine by me.

**Comment by RLHecht** [comment]
The work on this was completed except for one left nav item, which is now moved to ticket #17188. Closing ticket. FYSA @brianalloyd @bethpottsVADEPO
