### ISSUE TITLE
[VAMC-upgrade] Consider and determine Q4-2020 OKR and BETS, review Q3-2020 outcomes [Team]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13851]
## Issue Description
As a VAMC team member I need to better understand my Objectives and Key results for Q4, so I can assure my stories, efforts and accomplishments align and support the teams goals.

## Resources 

---
## Tasks
- [ ] Review outcomes from Q3
- [ ] Flush out OKRs that will continue into Q4
- [ ] Determine measurable OKRs, and determine BETS that will support.
- [ ] Create actionable items for team to own results.

## Acceptance Criteria
- [ ] Cleare OKRs have been determined and outlined
- [ ] Optional BETS are associated
- [ ] OKRs are prioritized for transfer into Project roadmap
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
