### ISSUE TITLE
[Frontend] DL v2 - Update 404 and empty state messages

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#13857]
## Issue Description
Update the 404s and empty states for the debt list and debt letter table pages.

---
## Tasks
- [ ] Update the 404s and empty states for the debt list and debt letter table pages.
    - [ ] [No current debts](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263630/specification/sitemap?mode=i)
    - [ ] [DMC API 404 (can't get current debts)](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263797/specification/sitemap?mode=i) 
    - [ ] [No debt letters found](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132264910/specification/sitemap?mode=i)
    - [ ] [VBMS API 404 (can't get debt letters)](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263542/specification/sitemap?mode=i)

## Acceptance Criteria
- [ ] Messages match for the following use cases:
    - [ ] [No current debts](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263630/specification/sitemap?mode=i)
    - [ ] [DMC API 404 (can't get current debts)](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263797/specification/sitemap?mode=i) 
    - [ ] [No debt letters found](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132264910/specification/sitemap?mode=i)
    - [ ] [VBMS API 404 (can't get debt letters)](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263542/specification/sitemap?mode=i)

**Comment by LinnJS** [comment]
@craigwheeler and I are unaware of the work around this ticket and are unsure if this is still needed. @rebeccawalsh do you happen to know?

**Comment by denisecoveyduc** [comment]
@rileyorr any idea what Becca might have been referring to here? Otherwise maybe this one can be closed out?
