### ISSUE TITLE
Create test for VAMC Related links box on required health service pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13853]
## Issue Description
Related links areas are displayed on required health services detail pages, such as suicide prevention and LGBT. A bug impacting these areas as resolved in [#13688] but indicated a gap in testing. This issue was created to close that gap. 

Required detail pages include:

- [Caregiver support](https://www.va.gov/pittsburgh-health-care/caregiver-support/)
- [Homeless Veteran care ](https://www.va.gov/pittsburgh-health-care/homeless-veteran-care)
- [LGBT Veteran care](https://www.va.gov/pittsburgh-health-care/lgbt-veteran-care)
- [Mental health care](https://www.va.gov/pittsburgh-health-care/mental-health-care)
- [Minority Veteran care](https://www.va.gov/pittsburgh-health-care/minority-veteran-care)
- [Patient advocates](https://www.va.gov/pittsburgh-health-care/patient-advocates)
- [Returning service member care](https://www.va.gov/pittsburgh-health-care/returning-service-member-care)
- [Suicide prevention](https://www.va.gov/pittsburgh-health-care/suicide-prevention/)
- [Women Veteran care](https://www.va.gov/pittsburgh-health-care/women-veteran-care)

## Tasks
- [ ] Add automated test to check for presence of "Other resources" box with links on required health services detail pages 

## Acceptance Criteria
Automated tests are present to confirm `Related links`/"Other resources" area contains links and appears on 
- [ ] Caregiver support 
- [ ] Homeless Veteran care
- [ ] LGBT Veteran care
- [ ] Mental health care
- [ ] Minority Veteran care
- [ ] Patient advocates
- [ ] Returning service member care
- [ ] Suicide prevention
- [ ] Women Veteran care

**Comment by mpelzsherman** [comment]
This probably should have been a 3...
