### ISSUE TITLE
[Business Optimization] Associate all VISN-6 facilities to the correct System [PM] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#13869]
## Story
As a PAO I need all of the facilities associated to the correct system, so I can manage the pages correctly under my System in VA.CMS

## Tasks
Move all facilities out of root menu by associating the to the correct system in VA.CMS:
VA Asheville health care
- [ ] 637	Charles George Department of Veterans Affairs Medical Center
- [ ] 637GA	Franklin VA Clinic
- [ ] 637GB	Rutherford County VA Clinic
- [ ] 637GC	Hickory VA Clinic

VA Durham health care
- [ ] 0	Blind Rehabilitation Outpatient Clinic
- [ ] 558	Durham VA Medical Center
- [ ] 558GA	Greenville VA Clinic
- [ ] 558GB	Raleigh VA Clinic
- [ ] 558GC	Morehead City VA Clinic
- [ ] 558GD	Durham County VA Clinic
- [ ] 558GE	Hillandale Road VA Clinic
- [ ] 558GF	Wake County VA Clinic
- [ ] 558GG	Raleigh III VA Clinic
- [ ] 558QA	Brier Creek VA Clinic

VA Fayetteville Coastal health care
- [ ] 565	Fayetteville VA Medical Center
- [ ] 565GA	Jacksonville VA Clinic
- [ ] 565GC	Wilmington VA Clinic
- [ ] 565GD	Hamlet VA Clinic
- [ ] 565GE	Robeson County VA Clinic
- [ ] 565GF	Goldsboro VA Clinic
- [ ] 565GG	Lee County VA Clinic
- [ ] 565GH	Brunswick County VA Clinic
- [ ] 565GL	Cumberland County VA Clinic
- [ ] 565QA	Robeson Street VA Clinic
- [ ] 565QD	Raeford Road VA Clinic

VA Hampton health care
- [ ] 590	Hampton VA Medical Center
- [ ] 590GB	Virginia Beach VA Clinic
- [ ] 590GC	Albemarle VA Clinic
- [ ] 590GD	Chesapeake VA Clinic

VA Richmond health care
- [ ] 652	Hunter Holmes McGuire Hospital
- [ ] 652GA	Fredericksburg VA Clinic
- [ ] 652GB	Fredericksburg 2 VA Clinic
- [ ] 652GE	Charlottesville VA Clinic
- [ ] 652GF	Emporia VA Clinic

VA Salem health care
- [ ] 658	Salem VA Medical Center
- [ ] 658GA	Tazewell VA Clinic
- [ ] 658GB	Danville VA Clinic
- [ ] 658GC	Lynchburg VA Clinic
- [ ] 658GD	Staunton VA Clinic
- [ ] 658GE	Wytheville VA Clinic

VA Salisbury health care
- [ ] 659	W.G. (Bill) Hefner Salisbury VA Medical Center
- [ ] 659BY	Kernersville VA Clinic
- [ ] 659BZ	South Charlotte VA Clinic
- [ ] 659GA	North Charlotte VA Clinic

## Acceptance Criteria
- [ ] All facilities show up in System search by VAMC facility
