### ISSUE TITLE
Vet Center prototype iteration

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13887]
## Issue Description
Based on initial lo-fi prototype, feedback from design intent meeting and initial veteran research, create next iteration of Vet Center prototype

[Link to Mural board with latest wireframe iteration](https://app.mural.co/t/vsa8243/m/vsa8243/1599673587082/4caed61844c4e3665e9592e2b9467d0eaec8dc6d?wid=0-1600125104061&outline=open)

<details>
<summary> Accessibility feedback from Design Intent </summary>
**Must**
- Explore mobile design, which should clarify hierarchy and the starting point for progressive enhancement.

**Should**

- Include mobile users in research, and especially non-WiFi. In order to test cellular data connectivity, it may be necessary to use team members, since we don't want to impact anyone with limited data plans.
- Define a performance budget for these pages, if possible; this would limit the number of images and scripts, thereby delivering an empathetic, useful page load time.
- Use progressive enhancement to deliver an experience that is useful regardless of device or connectivity, and enhance as appropriate. Defer loading and use responsive image techniques.
- Collaborate frequently with your VSA accessibility specialist as design and research plans evolve.

**Consider**

1. Event listings - Providing events as a .ics attachment. I love this as an experience design bonus, clicking on a link and having it offer to add to my calendar.
2. Content length -- Page may be very long. Consider using the "On this page" navigation component to "skip" and move asynchronously.
3. Visual transitional cues will be important. When I zoom way out and squint at the screen, the page has white/gray banding that may just be wireframe artifacts, or may be cues for background colors. I'd encourage the team to keep these visual divides and offer 1-2 different mechanisms for dividing the page. This can create visual interest and create cognitive distinctions. Color blocks could be used for "big" idea changes, for instance, and horizontal rules or the decorative star + line treatment for "small" idea changes or supporting idea sections.
- One note about the full-width color bleeds: the current design system prevents implementing these full-width background colors; in order to do this, it would require revisiting the margin and padding styles associated with the <main> element, and then adjusting the margin/padding for child elements.
- There is interest in modifying the styling as indicated above, specifically for mobile in order to maximize space available and expand design options.
- Logistical information is super important. I'd recommend this be coded in such a way to maximize SEO. Bonus points for microdata or JSON-LD that enables the smart Google search results for Vet Centers.
4. Interested in seeing how the "Areas we serve", "Map", and "Parking" buckets develop as these wireframes become full designs. I agree these will be very beneficial and necessary information.
- What does "Areas we serve" represent? Is this things like neighborhood, city, county, state?
- Are there techniques or UI that could be used to bucket services besides accordions? This creates a challenge for screen readers, those who search by keywords, and possibly SEO for finding service descriptions or more detailed information. It might be as simple as adding a second line that offers the keywords for each service, or exploring other means like two-column short paragraph blurbs about each service and a learn more > link or a responsive table.
</details>

---

<details>
<summary>  IA feedback from Design Intent </summary>
**QUESTIONS**
- Will these facilities require an operating status page similar to the health facilities?
- Are any of the "highlight" blocks on the page clickable?  If so, will they go to existing content pages or would they be additional content for this specific facility?

**MUST**
- Show breadcrumb within design (it may be accounted for in the mast head, but it is an element that will need to be figured out as part of this work)

**SHOULD**
- Start to think about how users will arrive at and navigate out of these pages - should they be part of the facility locator tool or do they live as independent pages that FL just links to (like vamcs).  This will help formulate entry points, URLs and breadcrumbs. 
- Work through a mobile version of the wireframe to create a content hierarchy and structure - this is another way of exploring whether content needs to be broken up into supporting pages or can be fully contained in a single landing page. 
 
**CONSIDER**
- As you work through content needs and determine if there may/should be more than 1 page, please reach out so we can work through what a core "site template" might look like, which will help define what a potential left nav component and breadcrumb implementation. 

</details>

---

<details>
<summary> Design feedback from Design Intent </summary>
**Should:**
Lay out the content on mobile to see what layout adjustments might be needed, especially for the sections where there are horizontal rows of components.

**Consider:**
That it’s possible that not all Vet Centers will have images, for the section “What other veterans say…” you could try right aligning the image instead of left aligning to avoid any awkward alignment of the text if images aren’t provided ex: the locations section of https://www.va.gov/pittsburgh-health-care/

For the horizontal groups of 3 across the page, you could use the “featured story” card available in the sketch library. Example under frequently used forms: https://www.va.gov/find-forms/ or in the spotlight : https://www.va.gov/pittsburgh-health-care/health-services/

In case the pages get long you can use the “on this page” component available in the navigation section of the sketch library. In use here: https://www.va.gov/pittsburgh-health-care/health-services/

...OR consider borrowing the left nav from the Pittsburgh VAMC site and breaking the sections into their own pages if you decide to go that route in collaboration with Mikki and IA discussions.

</details>

---
## Tasks
Iterate on Vet VCenter prototype, incorporating 
- [ ] "must" feedback ( at a minimum) from Design intent meeting
- [ ] Veteran research
- [ ] Feedback from Ryan Thurlwell

## Acceptance Criteria
Iteration on v1 prototype includes
- [ ] Breadcrumb within design 
- [ ] Exploration of mobile design to clarify hierarchy
- [ ] Starting point for progressive enhancement
- [ ] Veteran feedback [TBD]

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)- [ ] Breadcrumb within design
- [ ] Exploration of mobile design to clarify hierarchy 
- [ ] Starting point for progressive enhancement.
- [ ] Veteran feedback [TBD]
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by james-costa** [comment]
@davem-va 👀
