### ISSUE TITLE
IRIS Q&As: Health care 

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#13904]
### Issue
For the launch of Learning Center MVP 1.1, health care content needs to be developed based on the following:

- IRIS health care benefits faqs
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks

- [ ] SC to identify IRIS faqs to migrate (Laura)

- [ ] SC to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Danielle)

- [ ] SC to develop draft copy and review against content checklist  (Danielle)

- [ ] DEPO to review (Beth)

- [ ] SC to copyedit draft (Randi)

- [ ] DEPO to get SME approval (Beth)

- [ ] SC to build Drupal page(s) (Selina, Randi or Laura)

- [ ] SC to proof Drupal page(s) (Randi)

- [ ] DEPO to approve Drupal page(s) (Beth)

- [ ] SC to publish pages (Randi)

- [ ] DEPO to alert SMEs that pages are live (Beth)

- [ ] SC to update R&S status document (Laura)

**Acceptance Criteria**

- [ ] Page live

**Up-to-date content here**

Please post most up-to-date content (whether copy deck, Drupal link, or live url) here rather than in comments below.

**Comment by brianalloyd** [comment]
Moving this into Sprint 34.

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA -- I had put some Service Dog content in a disability copy deck. Beth asked me to paste it here for you to pick up in health care. LMK if you have questions or if I can help.   

Template:  Multiple faqs

Tags:  Disability, Health care, All Veterans

VA guide dogs and service dogs
==============================

Guide dogs and service dogs can help Veterans with certain kinds of disabilities lead more active, independent lives. VA benefits pay for veterinary and equipment costs related to owning a guide or service dog. Learn more about these benefits and how to find out if you qualify.

BUTTON LABEL

Apply for guide and service dog benefits

https://www.prosthetics.va.gov/serviceandguidedogs.asp

What can a guide or service dog do?
-----------------------------------

Here are some of the tasks that working dogs have been trained to do:

- Pick up objects

- Open and close doors

- Turn lights on and off

- Guide people with visual impairments

- Alert people with hearing impairments to sounds

- Pull a wheelchair

- Remind a person to take medications

- Calm a person with posttraumatic stress disorder (PTSD) during an anxiety attack

Sources: <https://www.va.gov/HEALTHPARTNERSHIPS/docs/CCIServiceDogFactSheet.pdf>, https://www.prosthetics.va.gov/serviceandguidedogs.asp, https://www.vetdogs.org/AV/getaservicedog/AV/DogPrograms/getaservicedog.aspx?hkey=d285bc4c-8089-4569-a7c6-46f60f48cb4d

What's the difference between a guide dog and a service dog?
------------------------------------------------------------

Guide dogs are trained to help people with visual impairments. Service dogs are trained to help people with hearing impairments or who have low mobility due to physical impairments or mental health issues.

Sources: IRIS 3049,  <https://www.vetdogs.org/AV/getaservicedog/AV/DogPrograms/getaservicedog.aspx?hkey=d285bc4c-8089-4569-a7c6-46f60f48cb4d>, https://www.prosthetics.va.gov/serviceandguidedogs.asp,

How can VA benefits help with a guide or service dog?
-----------------------------------------------------

If you qualify for these benefits, VA will connect you with a non-VA agency that specializes in training working dogs. Once you become the owner of a guide or service dog, VA Prosthetics and Sensory Aids pays for your dog's veterinary care and any special equipment you may need. VA does not pay for routine expenses such as food, boarding or grooming.

Sources: IRIS 3049,  https://www.prosthetics.va.gov/serviceandguidedogs.asp

Do the dogs come directly from VA?
----------------------------------

No. VA does not provide guide or service dogs. We work with non-VA programs that specialize in training working dogs.

Sources:  IRIS 3049, https://www.prosthetics.va.gov/serviceandguidedogs.asp,

How much will I have to pay for the dog?[[LW1]](#_msocom_1) 
------------------------------------------------------------

It may cost you little or nothing to get the guide or service dog.  Most of the programs that we work with have donors and funders who help cover costs. Some programs ask for application fees, travel, or other fees. If you're assigned to a program, you can ask what your costs will be, and if there's any assistance available to help you cover those costs.

Source: https://assistancedogsinternational.org/

How do I find out if I qualify for guide or service dog benefits?
-----------------------------------------------------------------

To qualify, first, you have to be enrolled in VA health care. Then, talk to your clinical care provider or mental health provider. Your provider will refer you to a specialist who will work with your medical team to understand your challenges and figure out if a guide or service dog can help.

Sources: IRIS 3049, https://www.prosthetics.va.gov/serviceandguidedogs.asp

**Will someone teach me how to work with my dog?**

Yes. If you're accepted into the program, the working dog program will help you learn what the dog has been trained to do, and how your dog can help you. Once you've learned how to work well with your dog, it belongs to you.

Source: IRIS 3049[[LW2]](#_msocom_2) 

**Related information**

Are service dogs allowed in VA facilities?

https://www.va.gov/resources/are-service-dogs-allowed-in-va-facilities/

* * * * *

 [[LW1]](#_msoanchor_1)Beth, we need an SME's help on this question in particular. There's no mention in IRIS or https://www.prosthetics.va.gov/serviceandguidedogs.asp. I based this answer on info on the Assistance Dogs International website. (FYI, in case the term "assistance dogs" caught your eye like it did mine -- technically, assistance dog is the preferred generic term, with guide dog, service dog, hearing dog falling under it. However, per keyword search on Moz, "assistance dog" is not an effective keyword, so I stuck with "guide or service dog" though, technically, "assistance dog" is more accurate.   )

 [[LW2]](#_msoanchor_2)Could not confirm via a second source.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @lwalsh617! Jen had also drafted some content around this topic that's on my list of content to edit and move through approvals. So I'll take a look at this as part of that overall effort. Thanks again!

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht A few more ready for you in the morning:

- How to get help with concerns at a VA health facility (http://preview-prod.vfs.va.gov/preview?nodeId=36779)
- What's a Veteran Health ID Card (VHIC) and how do I get one? (http://preview-prod.vfs.va.gov/preview?nodeId=36778)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!
