### ISSUE TITLE
Match main form screen to JTF submission doc

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13900]
## Issue Description
Match main form screen to JTF submission doc.

Here's a pdf with the marked-up changes. [Coronavirus research_volunteer list form_9.22.20 updates_screen 1](https://app.zenhub.com/files/133843125/34691956-e105-4ca7-8a7c-fc89f0d2e6eb/download)

---
## Tasks
- [ ] Review main form screen against JTF submission doc
- [ ] Update form to match JTF submission doc

## Acceptance Criteria
- [ ] Screen updated to reflect changes
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @batemapf @stephenBarrs. I looked at the form against the JTF submission and marked up pdfs with needed updates. Let me know any questions. Thanks!

**Comment by batemapf** [comment]
Made most of the updates:
[screencapture-localhost-3001-coronavirus-research-volunteer-review-and-submit-2020-09-23-14_12_23.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5270155/screencapture-localhost-3001-coronavirus-research-volunteer-review-and-submit-2020-09-23-14_12_23.pdf)
[screencapture-localhost-3001-coronavirus-research-volunteer-sign-up-2020-09-23-14_11_15.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5270156/screencapture-localhost-3001-coronavirus-research-volunteer-sign-up-2020-09-23-14_11_15.pdf)

outstanding are:

- [ ] Re-order health history so "Compromised immune system" is after "Cancer"
- [ ] Add "Carpool or vanpool" to work transportation options
- [ ] Add "Non-binary" to gender options

**Comment by mnorthuis** [comment]
Breadcrumb updated in IA documentation per above: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/cto-covid-trials.md

**Comment by batemapf** [comment]
Updates made in [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/14357) and [vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/520):

- [x] Re-order health history so "Compromised immune system" is after "Cancer"
- [x] Add "Carpool or vanpool" to work transportation options
- [x] Add "Non-binary" to gender options

To get everything working together, need to get the [vets-api conforming change](https://github.com/department-of-veterans-affairs/vets-api/pull/4969) merged in.
