### ISSUE TITLE
IRIS Q&As: Batch 4, Disability benefits

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#13908]
### Issue
For the launch of Learning Center MVP 1.1, disability benefits content needs to be developed based on the following:

- IRIS disability benefits faqs
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

- [x]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

 - [x] PW to develop draft copy (Laura)

 - [x] PW to assign tags (Laura)

 - [ ] PW to copyedit draft (Randi)

 - [ ] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [ ] Copy deck ready for DEPO review and attached to a content review GH ticket.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO and @RLHecht -- Here is the first draft for disability content. Am flagging you both as I'm not sure who wants to review first--so you can duke it out. 😉
[rs-1.1-disability-v1-112420.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5609349/rs-1.1-disability-v1-112420.docx)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 You can revise the tasks above--just remove Randi's step--since I'll review before Randi's pass. Go ahead and create a ticket for me for a substantive review and close this one out!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 And be sure to attach the deck to my ticket. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- If you made changes to the copy deck attached to my comment above, can you please attach the latest copy deck to ticket [18871](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18871) and close this ticket? Thanks!
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18871

**Comment by bethpottsVADEPO** [comment]
Closing this ticket. Laura will add more disability articles to the two here ("two" since we're moving the service dogs article to be reviewed with HC content), and then I'll review all together. Just going to attach this deck with the 2 to #18871.
