### ISSUE TITLE
[Design] Healthcare: Refill and track your prescriptions 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13919]
## Background
See [Design plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md)

Note: Shown conditionally if someone has prescriptions

## Tasks
- [ ] Wireframes for all states
- [ ] Visual design exploration
- [ ] High fidelity mockups
- [ ] Appropriate stakeholder reviews and approvals have been completed

**Comment by tressaellen** [comment]
@Samara-Strauss please review. :)

**Comment by Samara-Strauss** [comment]
> Note: Shown conditionally if someone has prescriptions

This should be "show conditionally if someone has health care" since we will still show this block even if they don't have any active prescriptions.

> Order shipment date
> Submission date
> Refill date 

Are refill date and shipment date effectively the same thing? I would imagine a prescription is refilled and then shipped at the same time, but we should confirm exactly how this data is handled in the code. I am not sure about my assumption and it definitely needs to be double checked.

Otherwise, this looks good to me. Also, I think I handed off #12902 to you @tressaellen @callen2563, but in case I did not, I had Sandra confirm exactly what we get or can get in the code via the API for prescriptions. **We can not link to individual prescriptions**, which I think I already let you know, but re-stating just to make sure all bases are covered.

----

Also, we are going to have to handle the annoying Cerner/MHV split on the new logged-in homepage (this work that we are doing now for My VA in #13831). However, I do not want you to focus on that at first. I want you to design and get the major use cases in a good place, and then we can go back and figure out how to handle the Cerner annoyingness later. I'll create a ticket to do that so we don't forget about it. Mostly, I wanted to flag that as something that is not represented here but also something that I don't want us to handle yet.

**Comment by tressaellen** [comment]
> Are refill date and shipment date effectively the same thing? I would imagine a prescription is refilled and then shipped at the same time, but we should confirm exactly how this data is handled in the code. I am not sure about my assumption and it definitely needs to be double checked.

I'm honestly not sure about this - but I'll look into it once we start on this section.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen Here is what we have for prescriptions with edits via feedback.
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95266212-998e1f00-07e7-11eb-9012-4b3d003ad4e8.jpg)
![LIH - Desktop - Healthcare - Unahppy Path :(](https://user-images.githubusercontent.com/68560244/95266227-9eeb6980-07e7-11eb-9f42-21a038626d68.jpg)

**Comment by Samara-Strauss** [comment]
Closing. We've done a lot of exploration of this section, so I am considering this ticket done. [Here's where the design stands as of now](https://cassandraallen738782.invisionapp.com/console/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/ckgb2sajy019u01as9gd12s97/play#project_console). We'll open new tickets as needed for any updates or copy work.
