### ISSUE TITLE
IRIS Q&As: Batch 5, Education & training

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#13913]
### Issue
For the launch of Learning Center MVP 1.1, education & training benefits content needs to be developed based on the following:

- IRIS education & training benefits faqs
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

- [ ]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

 - [ ] PW to develop draft copy (Laura)

 - [ ] PW to assign tags (Laura)

 - [ ] PW to copyedit draft (Randi)

 - [ ] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [ ] Copy deck ready for DEPO review and attached to a content review GH ticket.

**Comment by lwalsh617** [comment]
Attaching education seo research here. 
[Education SEO.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5750828/Education.SEO.docx)

**Comment by lwalsh617** [comment]
Closing this ticket because we ended up batching the education work by topic and are using those tickets to track this work.l
