### ISSUE TITLE
IRIS Q&As -- Pension

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#13910]
### Issue
For the launch of Learning Center MVP 1.1, pension benefits content needs to be developed based on the following:

- IRIS pension benefits faqs
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/contact-center/vfs-product-guides)

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks

- [x] SC to identify IRIS faqs to migrate (Laura)

- [x] SC to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

- [x] SC to develop draft copy and review against content checklist  (Laura)

- [ ] DEPO to review (Beth)

- [ ] SC to copyedit draft (Randi)

- [ ] DEPO to get SME approval (Beth)

- [ ] SC to build Drupal page(s) (Selina, Randi or Laura)

- [ ] SC to proof Drupal page(s) (Randi)

- [ ] DEPO to approve Drupal page(s) (Beth)

- [ ] SC to publish pages (Randi)

- [ ] DEPO to alert SMEs that pages are live (Beth)

- [ ] SC to update R&S status document (Laura)

**Acceptance Criteria**

- [ ] Page live

**Up-to-date content here**

Please post most up-to-date content (whether copy deck, Drupal link, or live url) here rather than in comments below.
[rs-1.1-pension-1-042121.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6351802/rs-1.1-pension-1-042121.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- The pension content is ready for your review. See Word doc attached to the top of this ticket. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO

There are 3 pension articles to review:

**The difference between VA compensation and pension**
I built this in Drupal, addressing your feedback from Slack.
http://preview-prod.vfs.va.gov/preview?nodeId=36110
**Can I get VA pension back pay?**
Please review in attached Word doc, pages 2-3 and confirm whether to build in Drupal and if you agree with single QA template.
**How does VA determine my net worth?**
Please review in attached Word doc, pages 4-5 and confirm whether to build in Drupal and if you agree with single QA template.
Thank you!
[rs-1.1-pension-1-092921.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7253111/rs-1.1-pension-1-092921.docx)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 We'll move forward with the first 2 of these, but not the third one, which we have covered on these pages: https://www.va.gov/pension/veterans-pension-rates/
https://www.va.gov/pension/survivors-pension-rates/

On your chart, please note that this IRIS ID (about net worth) is covered in tier 1 on these pages. Thanks!

You can move forward with building the back pay article in drupal and I'll edit it there.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Are there any other pension IRIS FAQs that are high PV that we should consider rewriting?

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - 
[Can I get VA pension back pay?](http://preview-prod.vfs.va.gov/preview?nodeId=36481) is ready for you to review in Drupal. 
As for additional pension articles to consider (per your comment ^) the IRIS faq with the highest page views that is not addressed in the two R&S articles we're already developing, and is not a tier 1 topic is the following:
FAQ #929
179 Page views
**If the VA increases my disability rating or adds another disability, when will my increased benefits be effective?**
(IRIS tags this under Pension as well as Disability. It's not included in disability articles per Paul Shute, so I could see making it a pension article. However, at 179, page views aren't staggering. I went back through the page views spreadsheet and cannot find a more promising candidate.)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Randi copyedited the disability v. pension article. I believe the next step is to share with SMEs? http://preview-prod.vfs.va.gov/preview?nodeId=36110

**Comment by bethpottsVADEPO** [comment]
I'm thinking this should actually be simply a single Q&A. @lwalsh617 It feels like the H1 and first H2 are too similar. So would you do this: 
1/ Keep the multiple FAQ "alive" for now just in case SMEs want to add a bunch of text and we need to revert back to that template.
2/ Consolidate into a single Q&A by adding a "Note" under the bullets that will account for the second Q&A:

**Note:** You can't get VA pension payments and VA disability compensation at the same time. If you apply for and are eligible for both, VA will pay you whichever benefit is the greater amount. 

3/ Add all the related links to the single Q&A that are currently on the multiple FAQ--I added survivors pension there.
4/ Also add to the related links: helpful phone numbers article and the Get help with your claim tier 1 page.
5/ Under "Need help?" choose disability.

Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 That existing one should be the single Q&A that was a part of the FAQ. You don't need to create a new Q&A, just use that one. Am I understanding correctly?

**Comment by bethpottsVADEPO** [comment]
@RLHecht I got some feedback from SMEs that I've incorporated into http://preview-prod.vfs.va.gov/preview?nodeId=36106. Would you proofread this? It's really to publish after you run through your pre-pub checklist. Make sure it's tagged for both disability and pension. Once we have a couple more pension articles, we'll add that category to the landing page too!

**Comment by RLHecht** [comment]
This article is published and added to the resources and support page. @bethpottsVADEPO Let me know if you think we should take out one of the related links from [this page](https://www.va.gov/resources/your-intent-to-file-a-va-claim/) and add this instead. My suggestion would be to take out the Eligibility for VA disability benefits one.

**Comment by lwalsh617** [comment]
Dropping a note about the back pay article. VA had it tagged as disability and pension. We had it as a disability article. That SME said not to migrate, so it became a pension article. Beth checking with pension SME to confirm if there is indeed pension back pay. Also checking with disability SME: Considering the high page views, whether we want to bring this back as a disability article.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Since the only article left in play from this ticket is the one about back pay, and the pension SMEs are now pulling together some info for us to use for it, I'm going to close this ticket. Would you open a new one with the title: Get SME input on back pay article for disability comp and pension benefits (IRIS rewrite). Include the preview link for the article: http://preview-prod.vfs.va.gov/preview?nodeId=36481

Also please note in the ticket that we may want to revisit the H1. Thanks!
