### ISSUE TITLE
[Design] Healthcare: Send a secure message to your health care team

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13920]
## Background
See [Design plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md)
Note:  (shown conditionally if someone has messages)

Must include:

**If a user has messages:**
- [x] From
- [x] Subject Line
- [x] Date
- [x] View all secure messages (Link to MHV)

**If a user does not have any messages:**
Messaging is as follows(can be changed):
You don’t have any unread messages from your health care team
- [x] View all past secure messages (if applicable) (Link to MHV)

[Current error messaging](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/my-va/design/Dashboard-03-errors.png)

## Tasks
- [x] Determine what information needs to be included on the dashboard
- [x] Wireframes for all states
- [x] Visual design exploration if a user has messages
- [x] Visual design exploration if a user does not have messages
- [x] High fidelity mockups if a user has messages
- [x] High fidelity mockups if a user does not have messages
- [ ] Appropriate stakeholder reviews and approval along the way

**Comment by tressaellen** [comment]
@Samara-Strauss please review. :)

**Comment by Samara-Strauss** [comment]
Looks good to me!

Also, for documentation purposes even though I already mentioned this in #13919, we need to handle the Cerner/MHV split use case for health care information, but we do not need to handle that for this initial round of design.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen We will be reviewing these designs at our check in on Wednesday but wanted to post progress so far.
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95236558-f07dff00-07bb-11eb-9f51-73ebae1ec21b.jpg)
![LIH - Desktop - Healthcare - Unahppy Path :(](https://user-images.githubusercontent.com/68560244/95236562-f378ef80-07bb-11eb-8ccd-8760a6f4f5f1.jpg)

**Comment by Samara-Strauss** [comment]
Everything is looking really amazing so far! [I consolidate all of my design feedback in this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/samara-design-feedback.md). Let me know if you have any questions!!

**Comment by callen2563** [comment]
Great! This is so good to hear that we are on the right track so far! 👍🏼 I have made the edits you mentioned in the feedback document and will work on adding some iconography next and a treatment for the new number of messages, appointments etc
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95266212-998e1f00-07e7-11eb-9012-4b3d003ad4e8.jpg)
![LIH - Desktop - Healthcare - Unahppy Path :(](https://user-images.githubusercontent.com/68560244/95266227-9eeb6980-07e7-11eb-9f42-21a038626d68.jpg)

**Comment by tressaellen** [comment]
@Samara-Strauss Here's where we are so far with the Healthcare section. I added in the side navigation, and I've included the profile link (which is up for discussion).  Also, I removed the 'You have (3) upcoming appointments' from the appointments section.  I think that line is confusing. If you think we need to add it back in for consistency, we can work with copy to hopefully make that clearer.

![Healthcare.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/bc281070-e1c6-489f-b939-9e294aba1905)![Healthcare no info.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/ce2cbc8d-e727-4447-92ce-54522b3d814a)![Healthcare mobile.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/9ad035fc-1a01-45cd-9adc-2ef108718fa6)

**Comment by sshein** [comment]
is the idea that folks can click on individual appointments or messages or not?

**Comment by Samara-Strauss** [comment]
@tressaellen @callen2563 [here is my latest feedback from today](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/samara-design-feedback.md#feedback-10920). Among other things, don't forget to add in the new health care overview section Cassandra mocked up!

> is the idea that folks can click on individual appointments or messages or not?

@sshein I know that we can not link to individual prescriptions because we don't get that data from the API. I think we need to confirm on appointments and secure messages.

**Comment by sshein** [comment]
everything looks pretty "floaty" to me visually in this latest round. Once all the content / links are decided on it might be fun to do some kind of visual design "hackathon" with the VSA design team or a few people to try to get things looking nice and clean. let me know if that sounds interesting to you T+C

**Comment by tressaellen** [comment]
@Samara-Strauss and @sshein  - here's the latest round of revisions, hopefully this is a little less 'floaty'. I bumped up the 'View your lab and test results' to live under 'prescriptions' - maybe we can change the title of that to encompass both of those features. 

Also, I compared notes with the mobile app team for what to include on appointments and that's reflected here as well (I can also add that to the appointments ticket if we want to track that there). 

![Healthcare.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/ee469bae-ada6-4824-bf73-ea86e3a3cb5d)

**Comment by Samara-Strauss** [comment]
This is looking really good! Overall, I think things are moving in the right direction. [Here is my latest feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/samara-design-feedback.md#feedback-101320).

Wondering if we should get Ryan Thurlwell to take a look and see if he has any design ideas/feedback. I'm gonna reach out.

**Comment by tressaellen** [comment]
@Samara-Strauss thanks for feedback, we'll keep working on it. And that's a good idea to loop in Ryan - I'm happy to send stuff to him as well if you want. @callen2563 and I are working on cleaning up details of each section right now, so we'll have some more for you to look at soon.

**Comment by Samara-Strauss** [comment]
I've talked to @rtwell and encouraged him to leave feedback here!

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen Hey ladies, here are the latest mocks. I've added a table header on desktop and went though and cleaned up some areas and incorporated the latest feedback. Let me know if I missed any thing. Thanks!
https://cassandraallen738782.invisionapp.com/overview/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/screens
https://cassandraallen738782.invisionapp.com/overview/HP-mobile-logged-in-ckeyhydog01kz01xd3tao5pcj/screens

**Comment by Samara-Strauss** [comment]
Great! I like some of the changes you made to this version a lot. [Here is my latest feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/samara-design-feedback.md#feedback-101420), but I also am posting it below. Some of these are questions and not necessarily things to change, so just let me know the answers to those questions, or if you have any thoughts/ideas about anything else:

## Feedback 10.14.20

**Name tag**

This is all same as yesterday.

- Why do you have "VA appointment" under the "Appointments" heading? This feels redundant. What happened to the facility OR doctor name?
- Also, maybe "Appointments" should be "Next Appointment" since there is only one appointment there.
- Do we show data in XX/XX/XXXX format, or is always written out in words? This is something to check with content (and if we just have too much info to put in this block, we can revisit it altogether).

**Health care header**

Same as yesterday.

- Can you right align "Learn more about your VA health benefits"?

**Appointments**

- I really like this treatment.
- Same question about date — per the content style guide, I would check in with Peggy or someone about acceptable formats if you have not already. We need to make sure XX/XX/XXXX is acceptable and that it does not need to be written out in words.


**Lab and test results**

Same as yesterday.

- This treatment still doesn't work. What else can you do? Create a heading-copy-button section for lab and test results? Add a link to View lab and test results in the health care header area? Something else? 

**General**

- I REALLY like the header row for the tables. It's so much cleaner. However, then it's weird to have the header row be gray and then one of the rows in the table be gray. It makes the header/the row feel related, and obviously they aren't. I would probably just not have the second row of the table be gray.
- Please confirm with Erik and Sandra that we can actually show "Showing 1 -3 of X." Also, you need to be careful about that because it could be confusing. For example, is it 1 - 3 of 5 active prescriptions being refilled? Or is 5 all prescriptions? Is 1 - 3 of 5 all secure messages, or only new secure messages? Same with appointments — are those upcoming, does that include canceled/pending, etc. It might be easier to leave that out and to use more descriptive headings instead. "Upcoming appointments" and "Prescription refills" might be clearer for those two categories; "Secure messages" is probably clear as-is.

**Comment by Samara-Strauss** [comment]
Closing. We've done a lot of exploration of this section, so I am considering this ticket done. [Here's where the design stands as of now](https://cassandraallen738782.invisionapp.com/console/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/ckgb2sajy019u01as9gd12s97/play#project_console). We'll open new tickets as needed for any updates or copy work.
