### ISSUE TITLE
[Design] MyVA Dashboard initial explorations: Create Research Plan

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13925]
## Background

Epic #13924

This research plan is for the round of research we will be doing on the initial dashboard explorations we are working on in #15115.

## Tasks

- [ ] Determine research goals
- [ ] Create research plan
- [ ] Review research plan with Samara

**Comment by callen2563** [comment]
### Notes for rough plan for A/B test on both mobile and desktop:

Link to research handbook: http://ccftp.scu.edu.cn:8090/Download/efa2417b-08ba-438a-b814-92db3dde0eb6.pdf

- Will need more than 10 participants.
- Having users switch modes from desktop to mobile will bias their method of interaction.
- 4 participants for test A mobile, 4 for test B mobile, 4 for test A desktop, 4 for test B desktop (16 total). 

**Mix the order of A/B and devices used. For example:**
P1 (participant 1), A Mobile -> A Desktop
P2, A Desktop -> A Mobile
P3, B Mobile -> B Desktop
P4, B Desktop -> B Mobile
P5, A Mobile -> B Desktop
P6, B Desktop -> A Mobile
P7, A Desktop -> B Mobile
P8, B Mobile -> A Desktop and so forth

**Comment by tressaellen** [comment]
Here is the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research/MyVA%20Research%20Plan.md)

**Comment by Samara-Strauss** [comment]
Great work! Here's my feedback on [the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research/MyVA%20Research%20Plan.md).

**Goals**

- One of the major goals for this research should be to determine if we hit the right information balance (which I see as a bit different than can they *find* the information they are looking for, which sounds more like a goal around navigation). I see some questions around this under the "Questions" section (eg. is there enough relevant information for the dashboard to be valuable?) and think it would be worth calling out as a goal.

**Questions**

> Do users expect to see more information on a desktop view?

This might be kind of hard to assess. We can't outright ask it (not that you're suggesting that) since people are always like "yeah, sure!!" whenever you ask if they want something. We can try to get at this, but let's be careful. I'm more interested as to whether there is info missing in the current designs or not.

**Participants and Recruitment**

- Just curious: why 12 people? I would think 10 is enough, but if there is strong a reason you went with 12, feel free to stick with that.
- For 10 - 12 people, I would ask for at least 2 people of color/women/people under 35. It doesn't need to be 50/50 or anything, but Perigean takes these guidelines very literally, eg. if you if you ask for only one person under 35, you'll get only 1 and the rest will be older veterans (since that's how the population skews). 
- I'm curious about why we need some of these criteria, specifically the following. Can I ask why we included these requirements?:
  - At least one person who lives in a rural or remote area
  - At least one person who lives in a major metropolitan area
- Also, we should have a requirement that we have at least one person that receives VA health care, since they'll be able to more accurately assess the health care section.

Recruitment requirements

> All participants must use a mobile device.

Do we plan to have people use a mobile device during testing? If so, how would that set up work re: conducting the call and screensharing? If need be, we can have people test on a desktop, but show them a mobile prototype in InVision.

**General thoughts on creating the convo guide**

I think you all are in good shape to get started! A few thoughts I've had on the script/research structure:

- I think we should alternate which design people see first, so people aren't always seeing one design before the other. So for P1, show design A first, then B. For P2, show design B first, then A. That way, we can be sure that people's preferences aren't just a primacy bias.
- There's going to be a careful balance between open ended, high level questions and more specific questions to assess each design. More so than with a more fully-developed design, we'll probably need to let the veterans' comments lead where the conversation goes, but we should still have a high level list of things we want to touch on. 
- Given that this is more about evaluating information balance and IA, we don't need to focus on specific copy, BUT I would be curious to ask people what they would call this page. We've actually stayed away from calling it a "Dashboard" in a veteran-facing context, so I'm curious as to whether that term means anything to people or whether it's the right thing to call the page.

**Comment by tressaellen** [comment]
@Samara-Strauss thank you for the feedback! I've made updates to the research plan, and have some answers for you below. :)

> Just curious: why 12 people? I would think 10 is enough, but if there is strong a reason you went with 12, feel free to stick with that.

This was based on a previous recommendation when we were thinking about including desktop, now that we're doing just mobile I think we'd be fine with just 8. 

> I'm curious about why we need some of these criteria, specifically the following. Can I ask why we included these requirements?:
At least one person who lives in a rural or remote area
At least one person who lives in a major metropolitan area

The thought here is to get a wider range of participants since we're testing such a small sampling of people. This was based off a recommendation from an Ad Hoc researcher.

> Do we plan to have people use a mobile device during testing? If so, how would that set up work re: conducting the call and screensharing? If need be, we can have people test on a desktop, but show them a mobile prototype in InVision.

The plan is to have participants use their phones, I reached out to a few designers who have done mobile-only studies to see if they had any technical issues/issues at all and they all said they ran fairly smooth. If we end up having issues, then I think we can still do the test on desktop using the mobile prototype. We'll be sure to prep for if a user can't get things to work on their phones.

> I think we should alternate which design people see first, so people aren't always seeing one design before the other. So for P1, show design A first, then B. For P2, show design B first, then A. That way, we can be sure that people's preferences aren't just a primacy bias.

This sounds like a great idea.

> Given that this is more about evaluating information balance and IA, we don't need to focus on specific copy, BUT I would be curious to ask people what they would call this page. We've actually stayed away from calling it a "Dashboard" in a veteran-facing context, so I'm curious as to whether that term means anything to people or whether it's the right thing to call the page.

I'm also curious about this, we'll add in a question maybe at the end of the study.

**Comment by tressaellen** [comment]
Also, just in case any one is curious, here is the [Mobile Research Guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/mobile-research-guidelines.md)

**Comment by Samara-Strauss** [comment]
> I think we'd be fine with just 8.

Great! 8 sounds like plenty. On that note, we're asking for more participant requirements than we are participants, so I would further encourage you to maybe remove the location requirements and strongly consider which of the other requirements are important for testing. I'm *not* saying we shouldn't get a diverse pool (we should!), but think about what is really important for our research vs. what might have been right for someone else's.

> I reached out to a few designers who have done mobile-only studies to see if they had any technical issues/issues at all and they all said they ran fairly smooth. 

This is awesome!! I'm so excited to hear that!!

> Also, just in case any one is curious, here are the Mobile Research Guidelines

Which screensharing method are we going to use? I forget if you already did this, but if not, remember to include in the research requirements that people need to have Zoom downloaded **on their phones** before research starts.

Otherwise, great work!! Is this all done? If so, we can close. Looking forward to seeing the convo guide when it's ready.

**Comment by tressaellen** [comment]
Yep I think we're good to close this! We just need to update the dates/times when we figure out when we're actually running sessions.

**Comment by Samara-Strauss** [comment]
> We just need to update the dates/times when we figure out when we're actually running sessions.

Once you complete the conversation guide, we can figure out exact dates and times. I'll close this since that can easily be updated later.
