### ISSUE TITLE
[Design] Healthcare: Healthcare application status

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13923]
## Background
This should be done first.

See [Design plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/LIH-outline-and-timeline.md)

**If a user has healthcare, we must include:**
- [ ] Form number
- [x] Enrollment Status
- [x] Application date
- [x] Enrollment Date
- [x] Learn more about your VA health benefits: https://staging.va.gov/health-care/about-va-health-benefits/#health-about-basic

[Current error state](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/design/mockups/Dashboard_HCA%20errors.png)

**If a user does NOT have healthcare, we need to include**:
- [x] Messaging on how to apply/enroll
- [x] Link to apply for healthcare https://staging.va.gov/health-care/apply/application

**If a user has submitted a health care application, but it is either incomplete, rejected, or closed, we need to include**:
- [ ] Application status

## Tasks
- [x] Wireframes for all states
- [x] Visual design explorations for a user with healthcare
- [x] Visual design explorations for a user without healthcare
- [x] High fidelity mockups for a user with healthcare
- [x] High fidelity mockups for a user without healthcare
- [ ] Appropriate stakeholder reviews and approvals have been completed

**Comment by tressaellen** [comment]
@Samara-Strauss feel free to look over this ticket - I changed the title of the ticket to include the state for when a user does have healthcare

**Comment by Samara-Strauss** [comment]
@tressaellen what I don't see represented here is the state for when a user has submitted an application for health care and either that application is in the process of being evaluated/the application needs more information, the application was rejected or denied, or the application was closed (submitted but not complete applications get closed after a year).

I have some thoughts on how we might be able to handle that in a more streamlined way than we are handling it now, so let's talk about that. But, I do want to make sure that is reflected here since that is very much a use case we need to handle.

**Comment by tressaellen** [comment]
@Samara-Strauss I just added an 'application status' checkbox to account for this use case.

**Comment by Samara-Strauss** [comment]
@tressaellen I adjusted it in the first comment above to clarify when we'd show application status.

> **If a user has submitted a health care application, but it is either incomplete, rejected, or closed, we need to include**:
> 
>  - [ ] Application status

**Comment by tressaellen** [comment]
Looks good to me!

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen We will be discussing these designs in your Wednesday check in meeting but wanted to post progress so far. 
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95235942-1b1b8800-07bb-11eb-98db-c87f7e41dbf6.jpg)
![LIH - Desktop - Healthcare - Not Enrolled](https://user-images.githubusercontent.com/68560244/95235947-1ce54b80-07bb-11eb-963d-c9defc05b5fa.jpg)

**Comment by Samara-Strauss** [comment]
Everything is looking really amazing so far! [I consolidate all of my design feedback in this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/samara-design-feedback.md). Let me know if you have any questions!!

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
Great! This is so good to hear that we are on the right track so far! 👍🏼 I have made the edits you mentioned in the feedback document and will work on adding some iconography next and a treatment for the new number of messages, appointments etc
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95265970-1bca1380-07e7-11eb-8b36-e4c316b8654f.jpg)
![LIH - Desktop - Healthcare - Not Enrolled](https://user-images.githubusercontent.com/68560244/95265978-208ec780-07e7-11eb-98d8-7aadf0d7e24c.jpg)

**Comment by Samara-Strauss** [comment]
Thanks for these updates! [More feedback in this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/samara-design-feedback.md#feedback-10720)

**Comment by callen2563** [comment]
@Samara @tressaellen Here are the design updates to these screens:
https://cassandraallen738782.invisionapp.com/overview/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/screens

**Comment by Samara-Strauss** [comment]
@callen2563 @tressaellen [latest design feedback here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/samara-design-feedback.md#feedback-10820)!

**Comment by Samara-Strauss** [comment]
Closing. We've done a lot of exploration of this section, so I am considering this ticket done. [Here's where the design stands as of now](https://cassandraallen738782.invisionapp.com/console/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/ckgb2sajy019u01as9gd12s97/play#project_console). We'll open new tickets as needed for any updates or copy work.

**Comment by Samara-Strauss** [comment]
Closing. We've done a lot of exploration of this section, so I am considering this ticket done. [Here's where the design stands as of now](https://cassandraallen738782.invisionapp.com/console/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/ckgb2sajy019u01as9gd12s97/play#project_console). We'll open new tickets as needed for any updates or copy work.
