### ISSUE TITLE
[Design] Healthcare: Schedule and view your appointments

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13921]
## Background
See [Design plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md)
note: shown conditionally if someone has health care in general

Stakeholders: VAOS team (Lauren/Lenae)

The information shown is up for debate, we can decide this as part of this ticket. This will (potentially) include:

- [ ] Status of appt
- [x] Date
- [x] Time
- [x] Provider information
- [ ] Directions
- [ ] Phone
- [x] Link to manage appointments: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/

If a user does not have any appointments the following messaging will be shown (can be changed if need be):
Find out how to make a doctor’s appointment with a member of your VA health care team online or by phone.

## Tasks
- [x] Determine what information should be displayed on the dashboard
- [x] Wireframes for all states
- [x] Visual design explorations for user with no appointments
- [x] Visual design explorations for user with appointments
- [x] Visual design explorations for user with no appointments
- [x] High fidelity mockups for user with appointments
- [x] High fidelity mockups for user with no appointments
- [ ] Appropriate stakeholder reviews and approvals have been completed

**Comment by tressaellen** [comment]
@Samara-Strauss please review. :)

**Comment by Samara-Strauss** [comment]
> If a user does not have any appointments the following messaging will be shown (can be changed if need be):
> Find out how to make a doctor’s appointment with a member of your VA health care team online or by phone.

Is it safe to assume this will link to the VAOS tool?

Also, for documentation purposes even though I already mentioned this in #13919, we need to handle the Cerner/MHV split use case for health care information, but we do not need to handle that for this initial round of design.

**Comment by tressaellen** [comment]
@Samara-Strauss yep - this will link to the VAOS tool

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen We will be reviewing these designs on Wednesday but wanted to post progress so far.
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95237090-9cbfe580-07bc-11eb-81dd-650452a5b6bf.jpg)
![LIH - Desktop - Healthcare - Unahppy Path :(](https://user-images.githubusercontent.com/68560244/95237099-9fbad600-07bc-11eb-97e8-a67ff6a927d0.jpg)

**Comment by callen2563** [comment]
Great! This is so good to hear that we are on the right track so far! 👍🏼 I have made the edits you mentioned in the feedback document and will work on adding some iconography next and a treatment for the new number of messages, appointments etc
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95266212-998e1f00-07e7-11eb-9012-4b3d003ad4e8.jpg)
![LIH - Desktop - Healthcare - Unahppy Path :(](https://user-images.githubusercontent.com/68560244/95266227-9eeb6980-07e7-11eb-9f42-21a038626d68.jpg)

**Comment by Samara-Strauss** [comment]
Thanks for these updates! [More feedback in this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/samara-design-feedback.md#feedback-10720)

**Comment by Samara-Strauss** [comment]
Hey all, I added some [design feedback here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/samara-design-feedback.md#feedback-10820) but wanted to also post a suggestion for appointments in here:

Could I see a treatment here where the appointment data appears stacked and not across a row? To me, it would be much more natural to view appointment information like so.

**Next appointment**

Dr. Shakatullah Shah Ansari
Wednesday, October 1, 2020
2:00 pm EST 

I realize I'm not the user, and we should validate everything, but I would love to at least see how you might handle this in a mockup.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen Hey ladies, here are the latest mocks. I've added a table header on desktop and went though and cleaned up some areas and incorporated the latest feedback. Let me know if I missed any thing. Thanks!
https://cassandraallen738782.invisionapp.com/overview/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/screens
https://cassandraallen738782.invisionapp.com/overview/HP-mobile-logged-in-ckeyhydog01kz01xd3tao5pcj/screens

**Comment by Samara-Strauss** [comment]
All of my feedback is in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13920#issuecomment-708414228) of the secure message ticket. Not going to repost here, so you can go there or [check the feedback doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/samara-design-feedback.md#feedback-101420).

**Comment by tressaellen** [comment]
Here is the [slack conversation](https://dsva.slack.com/archives/C018V2JCWRJ/p1602276146228000) with the mobile app team around this.

**Comment by Samara-Strauss** [comment]
Closing. We've done a lot of exploration of this section, so I am considering this ticket done. [Here's where the design stands as of now](https://cassandraallen738782.invisionapp.com/console/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/ckgb2sajy019u01as9gd12s97/play#project_console). We'll open new tickets as needed for any updates or copy work.
