### ISSUE TITLE
AE: Sprint 31 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13931]
# Priorities
**Team Happy Hour**
1. Profile 2.0: Launch to 50% of users
2. Remaining Sprint 30 tickets
3. Profile 2.0: FE backlog tickets
4. Logged-in homepage: Design intent checkpoint/plan for working with platform team
5. Logged-in homepage: Start design for "Healthcare" section
6. Logged-in homepage: Technical comparative analysis (how do other sites handle logged in/out pages)
7. Direct Deposit for Edu: Design and BE tickets
8. My VA: Cerner go-live updates for Spokane facilities on 10/24
9. Helping platform team: PACT work

### PM
- [x] Launch to 50% of users #13386
- [x] [PM] Create list of staging users we need for logged-in homepage QA #8385
- [ ] Matt to start maintaining the logged-in homepage project epic
- [x] [PM] Review Direct Deposit feature on eBenefits #13937

### Design
- [x] Determine date for Redirect Request: Account page #10688 (Oct 1st)
- [x] [Design] Error alert when we cant verify a person is a veteran/info is not available #13224 (Design->FE) 
- [x] [Design][Content] Show different error alert text when we cannot connect to MPI #12817
- [x] [Design] Error alert for when Veterans are not showing up as Veterans with military information in the system #13224 (Design->FE)(Mostly done)

### Build
- [x] Profile does not properly handle a contact field update without any changes #12632
- [x] Appointment reminders via SMS checkbox does not handle a failure to create transaction #12751
- [x] [FE] Profile 2.0 bug: The profile does not properly handle a contact field update without any changes #12632
- [ ] Delete confirmation alert should scroll into view #12013
- [x] No longer gate users from Military Information #13391
- [x] [FE] [MOBILE DESIGN][508] - Consider abutting mobile sub-nav to the top of viewport #12873
- [x] Better handling of entering bad email addresses #12004
- [x] Fix z-index issue mobile profile menu #12015
#### UAT issues
- [x] [FE] Build error alert for when Veterans are not being reported as Veterans #13225
- [x] [FE] "Invalid date" on Military History period of service #13130
- [x] [FE] Match error messages with VA Profile codes #12923

### Design
- [x] Prep/plan for the design-Intent collaboration checkpoint meeting #13329
- [x] Design intent Collaboration[Logged-in Homepage] #13415
- [X] [Design] LIH Navigation#14360
- [x] Plan for how to work with the platform team #10516
- [x] Track the documentation from the LOA3/LOA1 use case/data point exercise in Github #12862

#### Healthcare Design
- [ ] [Design] Healthcare: Design Healthcare Overview section #13918
- [ ] [Design] Healthcare: Refill and track your prescriptions #13919
- [ ] [Design] Healthcare: View your lab and test results #13922
- [ ] [Design] Healthcare: Apply now for VA healthcare #13923

### Dev 
- [x] [FE] Logged-in homepage: Technical comparative analysis #13796

## Direct deposit for Edu
- [ ] [BE] Create BGS CH33 DDEFT Service integration #13286
- [x] **Jim Adams** Conduct Discovery and Research for EDU Direct Deposit #13802
- [x] **Jim Adams** EDU Benefits Impact List #13960

## MyVA Cerner Go-live updates
- [x] [Design/Content] My VA: Cerner go-live updates for Spokane facilities on 10/24 #13831

## Pact work
- [ ] VSA Auth Experience - Pact setup for [product name] #13336
- [x] Meet with Platform team to discuss Pact work #13790
- Matt to break out into smaller tickets following meeting with Platform team
 
## Unplanned/QA/508/Bug fixes
- [ ] Remove Profile 2.0 feature flag mentions #14289
- [x] [BE] Configure SOCKS proxy for use with Sentry 10 #14319
- [ ]  [FE] Built 'Can't connect to MPI' error alert (#13996)
