### ISSUE TITLE
[Feature] - Add Static Claimant Information to the Review Page on CH36

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#13934]
## Description
As a user, I want to review my information one more time before submitting the form to ensure it is accurate. 

## Considerations
<details><summary>Current review page</summary>

![Screen Shot 2020-09-23 at 10.05.03 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/9d473d6f-3047-4a12-84de-66c4aeb23e54)
</details>

- [Mockup](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088577/simulate/sitemap)
- There is some ambiguity around how best to hide the edit button on the review page, since there isn't any provided functionality to do so without also hiding the section header. 
- May have to use a custom review field, or read the url to toggle the static info component between two different view states. 
- This *might* need to be a `nice to have` given the constraint of our timeline to launch

## Tasks
- [ ] Investigate feasibility of review field for static claimant information
- [ ] Implement review display

## Acceptance Criteria
- [ ] Form reflects mockups accurately
- [ ] Pull request has been submitted and merged
