### ISSUE TITLE
Add FAQs to style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#13932]
## Issue Description
We need to add the term FAQs to the style guide word list since we follow a different rule than AP, which does not use an "s" at the end. 

PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/318

## Tasks
- [x] Update style guide with new entry in word list (Randi)
- [x] Review/merge PR (Danielle, Beth, Jen)

## Acceptance Criteria
- [x] New entry in live style guide

**Comment by RLHecht** [comment]
Added to word list and sent up PR for review and merge. FYSA @DanielleThierryUSDSVA @bethpottsVADEPO

**Comment by RLHecht** [comment]
PR was approved and merged. Moving to validate and will close after today's deployment. FYSA @brianalloyd @MickinSahni

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni @brianalloyd
