### ISSUE TITLE
[Bugfix] Entering Veteran SSN Overrides Claimant SSN in CH36

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#13930]
## Description
If a user is filling out the Chapter 36 form and identifies themself as a **dependent** of a veteran, the form then asks them to enter the name and SSN of the veteran they are associated with. Currently, entering the SSN for the veteran overrides the SSN entered for the claimant. **This occurs when using the form as an unauthenticated user**. 

## Screenshots
<details><summary>Claimant Information</summary>

![Screen Shot 2020-09-23 at 9.12.22 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/77131f4d-93cd-46f3-8c06-f6a7f0106455)
</details>

<details><summary>Veteran Information</summary>

![Screen Shot 2020-09-23 at 9.12.52 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/4e9757a5-34b4-4245-82fe-8c14f0696a35)
</details>

<details><summary>Review Page</summary>

![Screen Shot 2020-09-23 at 9.13.02 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/b77e17df-f53b-4d96-977e-10b9c75100f6)
![Screen Shot 2020-09-23 at 9.13.09 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/6f3fd8ac-d3e0-45a9-871f-c849deed6081)
</details>

## Steps To Reproduce
1. On staging, navigate to https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction
1. Fill out the wizard
1. On the form intro page, click the link to begin the form without logging in
1. Enter in claimant information, click next, enter in claimant address information
1. Select the option `Spouse of a veteran or service member`
1. Fill out veteran information (you'll notice SSN is pre-filled with the claimant's SSN)
1. Verify on the review page that the SSN for the claimant has been changed and is the same as the SSN for the veteran. 

## Explanation
Even though the schema for chapter 36 has nested properties that include the different SSNs, this is not reflected on the frontend, where the SSN for claimant and veteran are both top level schema properties. This results in a flat object where declaring two properties with the same identifier only results in one actual property. 

## Solution
- Form data currently looks like this:
```
    data: {
      status: 'isSpouse',
      fullName: {
        first: 'James',
        last: 'Doe'
      },
      ssn: '555334444',
      firstName: 'John',
      lastName: 'Doe',
      dateOfBirth: '1991-01-03',
      claimantAddress: {
        'view:livesOnMilitaryBase': true,
        'view:livesOnMilitaryBaseInfo': {},
        countryName: 'USA',
        addressLine1: '123 athome dr',
        city: 'APO',
        stateCode: 'AA',
        zipCode: '12321'
      },
      claimantPhoneNumber: '1231231234',
      claimantEmailAddress: 'test2@test1.net',
      claimantConfirmEmailAddress: 'test2@test1.net'
}
```
- Form data should be modified so respective SSNs are nested. Proposed object structure:
```
    data: {
      status: 'isSpouse',
      veteranInformation: {
           fullName: {
              first: 'James',
              last: 'Doe'
          },
          ssn: '123121234'
      },
      ssn: '555334444',
      fullName: {
          firstName: 'John',
          lastName: 'Doe',
          },
      dateOfBirth: '1991-01-03',
      claimantAddress: {
        'view:livesOnMilitaryBase': true,
        'view:livesOnMilitaryBaseInfo': {},
        countryName: 'USA',
        addressLine1: '123 athome dr',
        city: 'APO',
        stateCode: 'AA',
        zipCode: '12321'
      },
      claimantPhoneNumber: '1231231234',
      claimantEmailAddress: 'test2@test1.net',
      claimantConfirmEmailAddress: 'test2@test1.net'
}
```

## Tasks
- [ ] Modify payload so properties are safely nested or renamed
- [ ] Use schema properties for claimant information (schema is still currently declared on the frontend)

## Acceptance Criteria
- [ ] Payload is properly nested or renamed
- [ ] A PR has been requested for merging
