### ISSUE TITLE
Build FE template for Content Type: About

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13963]
### Issue Description
Given CMS templates have been built for the "About" component
I want to begin building the FE template so that this component is successfully used on VA.gov

### The CMS templates for this ticket:
About (Related CMS ticket: TBD )

### Tasks 
- [ ] What work is necessary for this story to be completed?

### Acceptance Criteria
- [ ] This layer of the FE template (meat layer) is complete for this content type
- [ ] Needs to groom, review and estimate

**Comment by ncksllvn** [comment]
GraphQL query to get us started...

```
{
  nodeQuery(limit: 10000, offset: 0, filter: {conditions: [{field: "type", value: ["support_resources_detail_page"]}]}) {
    entities {
      entityId
      entityBundle
      ... on NodeSupportResourcesDetailPage {
        
      }
    }
  }
}

```

**Comment by andaleliz** [comment]
Passing along feedback RE: tables in this template that came out of the [design review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13825):
- Developers should coordinate a dev intent review with the VSA accessibility specialist before beginning development (have already contacted Mickin and Brian about this, Liz let Kelson and Nick know).
- Development should use the [semantic markup provided](https://codepen.io/jenstrickland/pen/YzqejpG) by the accessibility specialist

I'll be [adding some documentation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13972) to the [design mock-ups](https://preview.uxpin.com/e7717d3fa019146277f28d799d247b820140d1b5#/pages/132642759/documentation/no-panels?mode=i) regarding focus management and the width at which the desktop view should kick in.

**Comment by andaleliz** [comment]
@kelsonic and @ncksllvn lmk if you have any questions about the documentation for the tables in this template.

**Comment by kelsonic** [comment]
Hey @RLHecht! Could you let me know when a `support_resources_detail_page` is created? Once that happens I can start work on this 🙂

**Comment by RLHecht** [comment]
@kelsonic I'm working on that today! I'll let you know when it's done!

**Comment by kelsonic** [comment]
Awesome!! 🎉 Thanks!

**Comment by RLHecht** [comment]
@kelsonic Sample text added here: prod.cms.va.gov/node/7910 Let me know if you need anything else!

**Comment by kelsonic** [comment]
Thank you! 🔥

**Comment by kelsonic** [comment]
Hey @jenstrickland, do you have time to meet with @ncksllvn and I early next week to discuss a11y before we begin implementation for the about template? I believe you and @andaleliz made an effort to incorporate a11y early in the process, so just want to make sure we continue that effort into development! 🙂

**Comment by jenstrickland** [comment]
@kelsonic — Sure, put some time on our calendars, please. Will the scope of the meeting be to review the responsive table component for the page or the entire About page? 

@andaleliz Here is [documentation for keyboard navigation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/accessibility/learning-sessions/abc02-getting-started-with-keyboard-navigation-and-screen-readers). 

Also, Liz, will the About page use the regular non-collapsible lookup table or the collapsible one shown in the mockup link above?

**Comment by kelsonic** [comment]
@jenstrickland Perfect! I believe we could scope it to just the responsive table component for that template 🙂 I'll message you both early Monday to schedule a time, have a great weekend!

**Comment by andaleliz** [comment]
The tables in the learning center should reflect what is shown of screens 1 and 2 (collapsable) in the prototype, unless that is out of scope for MVP 1.0 due to the LOE required to implement that.  I included screen 3 as a "if we **really** can't do this for 1.0, then this is better than nothing" option.

**Comment by andaleliz** [comment]
Thanks @jenstrickland for the keyboard navigation documentation.  I hope that will also help @kelsonic and @ncksllvn understand how to get people **_inside_** the additional info component, as folks will need to get into the table cells to access links.

**Comment by kelsonic** [comment]
Validated + closing (mobile table needs a new ticket CC @brianalloyd @MickinSahni):

![preview-prod vfs va gov_preview_nodeId=7910](https://user-images.githubusercontent.com/12773166/95487819-0ae9e100-0952-11eb-825d-570287da3a58.png)
