### ISSUE TITLE
Resolve Form Detail Page Urls from Batch #2 Publishing

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#13964]
## Issue Description
_We published batch #2 of VA form detail pages in ticket #12213 . We need to change the URL names for the URLs listed below to be consistent w/ Mikki's URL schema. See comment here (https://github.com/department-of-veterans-affairs/va.gov-team/issues/12213#issuecomment-697676577).

- https://va.gov/find-forms/about-form-21p-0512s-1spanish/
- https://va.gov/find-forms/about-form-21p-0517-1spanish/
- https://va.gov/find-forms/about-form-21p-0519s-1spanish/
- https://va.gov/find-forms/about-form-5655blank/ (Hold off on this one since it seems to be a duplicate of another form (https://github.com/department-of-veterans-affairs/va.gov-team/issues/12213#issuecomment-697684435)
- https://va.gov/find-forms/about-form-21p-0516-1-spanish/
- https://va.gov/find-forms/about-form-21p-0514-1spanish/
- https://va.gov/find-forms/about-form-21p-0510spanish/
- https://va.gov/find-forms/about-form-21p-0518-1spanish/
- https://va.gov/find-forms/about-form-21p-0519c-1spanish/
- https://va.gov/find-forms/about-form-21p-0513-1spanish/

---
## Tasks
- [x] _Update the URL names of the URLs above and publish_

## Acceptance Criteria
- [x] _Page are published with the appropriate URL schema_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
The URLs have been changed and will be validated after today's deployment.

**Comment by jenniferlee-dsva** [comment]
Thx @lunascoop 

The form manager removed the duplicate `5655blank` form, so we can remove it from urls to fix. After today's deployment, this form page should no longer be live. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/e8265f98-a341-45f8-a8e3-3d196d758add)

**Comment by jenniferlee-dsva** [comment]
I don't think any of the above changing form page urls are on the 1:1 redirect list, but could you check on this redirect spreadsheet and confirm for @mnorthuis ? 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/redirects/form-detail-landing-pages-cutoff-for-redirects-080520.xlsx

If any of them are, please update the spreadsheet with the corrected URL and upload the new version in that "redirects" form landing pages folder, and please let me and Mikki know via her redirect ticket #5549

**Comment by lunascoop** [comment]
I have validated that these URL changes are published.

@jenniferlee-dsva @mnorthuis While none of the form changes above are not on the 1:1 redirect list, I have updated the URL listed for VA form 40-10007 to remove "VA" per UAT change ticket #13751 (which will be published today). With the change to VA form 40-10007 in mind, shouldn't the URLs for these other forms on the 1:1 redirect list be changed (listed below)? In looking at the PDF versions of the forms, they technically do not include a "VA" before the form name.

- VA Form VA-5655
- VA Form VA-10091
- VA Form VA-10182
- VA Form VA-3288
- VA Form VA-9
- VA Form VA-40-1330

Here's the updated spreadsheet w/ the forms listed above highlighted. 
[form-detail-landing-pages-cutoff-for-redirects-092520.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5283521/form-detail-landing-pages-cutoff-for-redirects-092520.xlsx)
