### ISSUE TITLE
DebtRes FSR Preliminary Research 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13973]
## Issue Description
_Prior to conducting interviews with SMEs from the DMC who are familiar with the FSR (VA form 5655), the design team needs to research the form and document questions/notes._

---
## Tasks
- [x] _Create an inventory of the FSR (VA form 5655)_
- [x] _Document questions/notes about the form_

## Acceptance Criteria
- [x] _A link to a document containing the FSR's inventory and questions/notes_

**Comment by rebeccawalsh** [comment]
Document containing FSR preliminary research can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report/research).
