### ISSUE TITLE
Review transformer tool/documentation 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13970]
## Issue description
The Facilities team needs to provide feedback on the Transformer tool and documentation before knowledge transfer can occur. 

## Tasks
- [x] Do a first pass evaluation of the transformer tool and documentation. 
- [x] Document questions and gaps in understanding

## Acceptance Criteria
- [x] Documentation of questions to be answered and areas in the documentation which needs clarification
- [x] Readiness to evaluate changes made to graphQL since the diff was taken to determine need for transformer: this work will be in separate issue(s)
