### ISSUE TITLE
Correct state abbreviation on decision reviews pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#13986]
## Issue Description
We have the wrong abbreviation for Nebraska listed on decision reviews pages where we mention finding addresses for other benefit types. Instead of NB it should be NE. See screenshot below:

![Screen Shot 2020-09-23 at 3.55.45 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c9f26046-6d11-4f42-936a-695e2e373c05)

Pages this is on:

- https://www.va.gov/decision-reviews/higher-level-review/
- https://www.va.gov/decision-reviews/supplemental-claim/

## Tasks
- [x] Change NB to NE (Selina)
- [x] Review change and publish page (Randi)

## Acceptance Criteria
- [x] Correct abbreviation showing on live pages.

**Comment by lunascoop** [comment]
@RLHecht Overlooked this ticket. I have made this change and is ready for review/publishing.

- http://preview-prod.vfs.va.gov/preview?nodeId=3011
- http://preview-prod.vfs.va.gov/preview?nodeId=3003

**Comment by RLHecht** [comment]
Thanks, @lunascoop Just reviewed and published. Moved to validate.

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket. FYSA @brianalloyd
