### ISSUE TITLE
Key word analysis for FL

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13982]
## Issue Description
To inform future conversations about optimizing facility search results, we need to do search analysis

---
## Tasks
- [ ] Do search analysis to determine top ~10 key words 

## Acceptance Criteria
- [ ] Data is available to inform future conversations

---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Results for Jan 1, 2020 - September 23, 2020 = 3,499,749% total unique searches
| Search Term | Unique Searches | Percent of total unique searches | 
|-- | -- | -- |
| health | 2,139,413 | 61.13% | 
| benefits | 364,373 | 10.41% | 
| urgent_care | 320,347 | 9.15% | 
| vet_center | 194,329 | 5.55% | 
| all | 187,342 | 5.35% | 
| cc_provider | 113,924 | 3.26% 
| cemetery | 79,000 | 2.26% | 
| pharmacy | 51,005 | 1.46% |
| provider | 41,866 | 1.20% | 
| cc_pharmacy | 7,656 | 0.22% |

**Notes**
- Searches for "All" dropped dramatically at the end of January when that option became unavailable. 
- Searches for "Pharmacy" were unavailable for much of the period, except for a period in March and then returning in September. 


Site Search Category | Total Unique Searches | % Total Unique Searches
-- | -- | --
| (not set) | 2,952,523 | 84.36%
| NonVAUrgentCare | 173,836 | 4.97%
| PrimaryCare | 66,459 | 1.90%
| 261QU0200X (urgent care) | 35,770 | 1.02%
| EmergencyCare | 35,260 | 1.01%
| 261QP2300X (primary care) | 17,505 | 0.50%
| UrgentCare | 16,341 | 0.47%
| DentalServices | 15,000 | 0.43%
| MentalHealthCare | 13,987 | 0.40%
| ApplyingForBenefits | 11,852 | 0.34%
