### ISSUE TITLE
[DO NOT PUBLISH UNTIL JANUARY] PCPG update to the coronavirus FAQ page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14001]
## Issue Description
The Chapter 36 name change to PCPG happens on October 26. Most edits are tracked in #13842. Since the coronavirus pages have specific approvals that need to happen, we'll do these changes separately, with a final review by Danielle. 

**Note:** Please don't implement the changes in drupal until October 23. This is because of the other regular updates made to this page. 

**Page to update:** https://www.va.gov/coronavirus-veteran-frequently-asked-questions/index.html

---
## Tasks
- [x] Under "What if I had or need an in-person appointment for VA benefits or services?": Change the second bullet point to, "Personalized Career Planning and Guidance (Chapter 36)"
- [x] Request Danielle Thierry's approval.
- [ ] After approval, set to publish on October 26.

## Acceptance Criteria
- [ ] This update goes live.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc

**Comment by bethpottsVADEPO** [comment]
@DanielleThierryUSDSVA We're ready to implement changes to chapter 36 references in the coronavirus FAQ.  Is it ok if Randi goes into the file to do that now? I'll let you two work out timing, but the sooner the better.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I made this change on the FAQs page. Could you just let me know if it looks OK to publish? Thanks!

**Comment by RLHecht** [comment]
Closing this ticket. We decided not to make the change on FAQs since we didn't change the H1 to the new name.
