### ISSUE TITLE
LC MVP 1.0: Claim/appeal status articles -- CONTENT REVIEW

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#14004]
Copy for the [claims/appeal STATUS articles for mvp 1.0 LC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13617) has been drafted and copyedited, and is ready for DEPO/Beth's review. 
Here's the copy deck: 
[https://app.zenhub.com/files/133843125/5f014975-8caf-428d-8a53-d3e4c4958510/download](https://app.zenhub.com/files/133843125/5f014975-8caf-428d-8a53-d3e4c4958510/download)

@clantosswett -- Content is based on the weekly call report you provided and knowledge base info. Could you please take a look and flag any topics you feel should be added or expanded on to ensure we're helping to decrease phone inquiries?

### Tasks
- [x] DEPO to review copy (Beth)
- [x] Chante to review to ensure common call center topics are addressed

 ###Acceptance Criteria
- [ ] Copy deck ready for SME review

**Comment by bethpottsVADEPO** [comment]
Reviewed, closing now.
