### ISSUE TITLE
Change path for /v0/facilities/va

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14018]
## Issue Description
Based on a review of logs, VSP determined we are still hitting /v0/facilities/va. All endpoints should have been moved to v1 as v0 is outdated, can be inaccurate and is about to be deprecated. 

An audit revealed one v0 query that needs to be updated: [BasicFacilityListWidget](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/facilities/BasicFacilityListWidget.jsx#L20)

## Tasks
- [ ] Add `{apiVersion: v1}` to optionalSettings argument to `apiRequest` call in `BasicFacilityListWidget` `componentDidMount`
- [ ] Add a unit test to confirm that the correct endpoint is called when the component is mounted

## Acceptance Criteria
- [ ] Functionality is maintained with v1 endpoint data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
