### ISSUE TITLE
Bring the Error Handling Guide into the VSP ecosystem

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1401]
## User Story:

As a VFS Team, I need to follow standards and best practices for building helpful error messaging into my solution to best help my users.

---

## Goal

Take the existing error handling standardization work that has been done and well-documented here:
https://github.com/department-of-veterans-affairs/vets.gov-team/tree/b07556070d6f3a21f3ecd08ed5abd6bdd1276acc/Products/Platform/Design%20System/Guidelines/Error%20handling

And figure out the best way to work this into the "portal" haha. Whether that's incorporating parts of it into Design System, or storing the per-product error messaging info in the GH Product folders, or some other solution.

---

## Acceptance criteria
- [ ] All useful parts of the existing error messaging guide are in new, intuitive / logical homes
- [ ] This info is easy to find and use (maybe it's included in onboarding materials? maybe it's cross-linked strategically from within va.gov-team repo?)
- [ ] VFS Teams are aware of this info

**Comment by meganhkelley** [comment]
@peggygannon can this epic be closed? my understanding is that we have brought error messaging guidelines into the design system, and further iterations on those are tracked in `Iterate on error message and downtime banner guidelines per VSP findings` #3915

**Comment by peggygannon** [comment]
@meganhkelley Yes, I think this can be closed.
