### ISSUE TITLE
[VAMC-upgrade] - Provide questions regarding Standards in VAMC template to VHA for review and answering [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#14023]
## Issue Description
As a PAO, I need answers to template and design questions, so I can better understand my product.

---
## Tasks
- [ ] Provide list of questions to VHA from Open tables and reviews to provide to regional PAOs and their leadership 
- [ ] Provide Answers from VHA to all VISN-PAOs in FAQs and answers.

## Acceptance Criteria
- [ ]  FAQ page and direct e-mails are sent out to VISNs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
