### ISSUE TITLE
[Analytics] Profile 2.0 dashboards: Fixes to detail reports

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14036]
## Background

As I've been more readily using the Profile 2.0 reports now that Profile 2.0 is launched, I've noticed some issues with the detail reports that link from the direct deposit analytics dashboard and main account security analytics dashboard.

**Direct deposit report**

https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/

- When I click into all of the detailed reports from this dashboard, they are filtered to September 16th. Can you remove that time range so they filter to the default range of the last 7 days?

**Account security report**

https://analytics.google.com/analytics/web/?authuser=0#/dashboard/AuydfL6WR7WS_nXqNhC5GA/a50123418w177519031p176188361/

- Links for “Verify Your Identity Clicks” and “Terms and Conditions for Health Tools Clicks” filter to September 16th. Can you remove that time range so they filter to the default range of the last 7 days?
- The detailed reports for “Set Up 2-Factor Authentication Clicks” and “Go to VA.gov FAQ Clicks” have no data in them. Can you fix this?

## Tasks

- [x] Direct deposit dashboard: Remove September 16th date filter for all detailed reports
- [x] Account security dashboard: Remove September 16th date filter for “Verify Your Identity Clicks” and “Terms and Conditions for Health Tools Clicks” detailed reports
- [x] Account security dashboard: Fix “Set Up 2-Factor Authentication Clicks” and “Go to VA.gov FAQ Clicks” detailed reports so that data populates them

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 for awareness

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - Confirming receipt. I will be reaching out to you when the fixes are complete. Thanks!

**Comment by Samara-Strauss** [comment]
Great, thanks!

**Comment by bmcgrady-ep** [comment]
Hi @Samara-Strauss - The GA dashboards are updated and fixed. Let me know if you need anything else!

**Comment by Samara-Strauss** [comment]
Everything looks good now. Thank you!
