### ISSUE TITLE
IN-PROGRESS: VSA accessibility feedback for accessibility dev intent review for PW [Learning Center CMS page templates]

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#14030]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This epic contains the VSA accessibility feedback for the accessibility dev intent review for Public Websites [Learning Center CMS page templates]. Feedback/guidance for each component of the template will be documented in an individual issue ticket.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

### For reference

**VSA Development Review** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review)

## Team Name

Public Websites

## Product/Feature Name

Learning Center

## Product description

Creates an IA and content design for tier 2 content that's benefit learning, knowledge, help, and support content categories.

## Review stage

- [x] **Development intent review** (Review design to discuss approach to take with development, identify what components and semantic HTML would be appropriate, identify any accessibility issues and how to address) - This would happen as designs are passed to development, before development begins.

- [x] **Spot check review** (Review and follow the steps in the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md) first.) This happens well before launch, so that the 508 office can review and any issues addressed *before* launch.

- [ ] **Other:** Please indicate what you're requesting

## Preferred times for dev intent checkpoint

Monday, 9/28 11-11:30a ET
Tuesday, 9/29 3-3:30p ET

## Staging URL and credentials

Reference: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12365

**MVP 1.0 list (~October)**
1. ✅   step_by_step: http://preview-staging.vfs.va.gov/preview?nodeId=6899
1. ✅   q_a: http://preview-staging.vfs.va.gov/preview?nodeId=6889
1. ✅   faq_multiple_q_a: http://preview-staging.vfs.va.gov/preview?nodeId=6898
1. ✅   About page

**1.1 (~December)**
* checklist: http://preview-staging.vfs.va.gov/preview?nodeId=6924
* media_list_images: http://preview-staging.vfs.va.gov/preview?nodeId=6954
* media_list_videos: http://preview-staging.vfs.va.gov/preview?nodeId=6950

Designs: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b

## Test plan

Don't have this quite yet.

**Comment by jenstrickland** [comment]
Thanks, @MickinSahni ! Would it be possible to link to designs?

**Comment by MickinSahni** [comment]
> Thanks, @MickinSahni ! Would it be possible to link to designs?

Yep, added. And Kelson shared some Drupal preview links for us

**Comment by jenstrickland** [comment]
@MickinSahni Which design version is this dev intent for? Should I use the list of VA environment previews to determine what to document?

![Screen Shot 2020-09-25 at 2 36 42 PM](https://user-images.githubusercontent.com/57469/94303911-a2a40400-ff3c-11ea-83ae-ff18eef43220.png)

**Comment by jenstrickland** [comment]
@MickinSahni @brianalloyd Hey there! Chatting with @ncksllvn @kelsonic — and want to make sure I know the priority of Learning Center items to provide dev intent guidance. We have this list, would you confirm if this is correct for MVP?

1. step_by_step: http://preview-staging.vfs.va.gov/preview?nodeId=6899
2. q_a: http://preview-staging.vfs.va.gov/preview?nodeId=6889
3. faq_multiple_q_a: http://preview-staging.vfs.va.gov/preview?nodeId=6898

TBD: checklist: http://preview-staging.vfs.va.gov/preview?nodeId=6924
TBD: media_list_images: http://preview-staging.vfs.va.gov/preview?nodeId=6954
TBD: media_list_videos: http://preview-staging.vfs.va.gov/preview?nodeId=6950
TBD: About page

**Comment by MickinSahni** [comment]
> Which design version is this dev intent for? Should I use the list of VA environment previews to determine what to document?

This is for version 2 - MVP 1.0. 

> want to make sure I know the priority of Learning Center items to provide dev intent guidance. We have this list, would you confirm if this is correct for MVP?

The About page is the 4th item in the MVP 1.0 list (~October). The remaining is 1.1 (~December).

**Comment by jenstrickland** [comment]
@andaleliz 👋  Are there mobile views available for these four items? I'm adding screenshots to the issues for each of the MVP 1.0 & MVP 1.1, to provide guidance for each. 

1. VSA dev intent: Learning center, MVP 1.0 - About page

1. VSA dev intent: Learning center, MVP 1.0 - step_by_step

1. VSA dev intent: Learning center, MVP 1.0 - Q & A

1. VSA dev intent: Learning center, MVP 1.0 - faq_multiple_q_a

**Comment by andaleliz** [comment]
@jenstrickland We have [mobile versions for the step-by-step](https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132512748/documentation/no-panels?mode=i).  I originally started exploring those designs for the step-by-step **with images**, but I think that accordion pattern makes sense even if there aren't images in a step.

There aren't any screens for the rest. Since those rely strictly on existing design system components, @rtwell and I didn't think it was necessary to create mobile screens.  [These are the screens we thought mobile versions would be most useful for](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md#090120).

**Comment by jenstrickland** [comment]
Thanks, @andaleliz! I went through that link, followed the details, and tried to add to the issues for the individual components. Before I continue with the dev intent documentation, would you 👀  those issues to see if I have the correct information, please? I want to avoid creating more confusion by having the wrong designs.

**Comment by andaleliz** [comment]
@jenstrickland I'd be happy to help but I'm not sure what you're asking me to do. I don't see anything added by you to the open issues.  If an issue is closed, it'd be most helpful not to add anything to to it.  Sorry to be dense, let me know how I can help :)

**Comment by jenstrickland** [comment]
@andaleliz Sorry for the confusion! I meant the issues for the individual components that are in this epic. I got lost trying to find the right things in the link for "These are the screens we thought mobile versions would be most useful for," and worried I'd select the wrong things.

**Comment by jenstrickland** [comment]
@MickinSahni @brianalloyd The dev intent a11y guidance is complete for MVP 1.0. I marked each complete one with a ✅ .

Once the designs are ready for MVP 1.1 I can document feedback for those (which I started…).

**Comment by brianalloyd** [comment]
Thanks @jenstrickland for the update and support. Tracking on 1.1 TY.

**Comment by 1Copenut** [comment]
@brianalloyd Do you have any additional context on this ticket? A11y specialists are reviewing our open items and this one came up on my list. Thank you!

**Comment by brianalloyd** [comment]
@1Copenut I think we can close this ticket as I believe all the items have been resolved (via different ticket).  This was for the dev intent review which we've already cleared and have launched.  Let me know what you think and I can close this ticket out in support.

**Comment by 1Copenut** [comment]
Thank you @brianalloyd . I'll close it now.
