### ISSUE TITLE
Past VAVC Appointment 

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14041]
## User Story

**Note: There are 4 different types of VAVC Appointments.**

---

### VAVC appointment at home

As a user, I can view the following information for any past **VAVC appointment at home**:
- Appointment type (VA Video Connect at home)
- Date, time, and time zone
- Message to call VA or visit VA.gov to make a new appointment
_- If the appointment was canceled, the appointment status (Canceled) should display. If the appointment was not canceled, do not display the appointment status._

#### [Wireframe - Past VAVC appointment at home](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432868108)

---

### VAVC appointments at an ATLAS location

As a user, I can view the following information for any past **VAVC appointments at an ATLAS location**:
- Appointment type (VA Video Connect at an ATLAS location)
- Date, time, and time zone
- Facility address
- CTA to get directions to the facility (opens location in default Maps app)
- Message to call VA or visit VA.gov to make a new appointment 
_- If the appointment was canceled, the appointment status (Canceled) should display. If the appointment was not canceled, do not display the appointment status._

#### [Wireframe - Past VA Video Connect at an ATLAS location](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204196)

---

### VA Video Connect at a VA location

As a user, I can view the following information for any past **VA Video Connect at a VA location**:
- Appointment type (VA Video Connect at a VA location)
- Date, time, and time zone
- Provider name
- Clinic name, VA Facility name, Address
- CTA to get directions to the facility (opens location in default Maps app)
- CTA to call facility (click to call) 
- Message to call VA or visit VA.gov to make a new appointment 
_- If the appointment was canceled, the appointment status (Canceled) should display. If the appointment was not canceled, do not display the appointment status._

#### [Wireframe - Past VA Video Connect at a VA location](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204499)

---

### VA Video Connect using a VA device

As a user, I can view the following information for any past **VA Video Connect using a VA device**:
- Appointment type (VA Video Connect using a VA device)
- Date, time, and time zone
- Message to call VA or visit VA.gov to make a new appointment
_- If the appointment was canceled, the appointment status (Canceled) should display. If the appointment was not canceled, do not display the appointment status._

#### [Wireframe - Past VA Video Connect using a VA device](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433303804)

---

## Other documentation
- The top bar for all types of past appointments should read "Past Appointment"

## Tasks

- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing, as needed) UI for a range of devices we are supporting, Android-specific wireframes
