### ISSUE TITLE
Closed Higher Level Review

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14042]
## User Story
For any closed Higher Level Review, I can see the following information: 
- [x] Date Higher Level Review was received
- [x] Date/time Higher Level Review was last updated
- [x] Past events for Higher Level Review & their dates
- [x] Message that the Higher Level Review is closed
- [x] Veterans Affairs Benefits and Services phone number
- [x] List of issues for the Higher Level Review

## Tasks
- [ ] Find a staging account with a closed HLR
- [x] Determine data elements for screens
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## [Wireframe](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433749016)

**Comment by bridgethapner** [comment]
Question: does the data for each appeal step come from the API?
