### ISSUE TITLE
Facility Locator: Mobile test coverage 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14048]
## Issue Description
Facilities team needs to expand our test coverage of Facility Locator mobile features/functionality 

**Tests should check for presence of all required components and responsive design. To the extent possible, testing should include checks to be done on mobile devices**

## Tasks
- [ ] Identify gaps in mobile coverage (such as Map is visible and interactive in mobile)
- [ ] Add tests to test suite to address gaps

## Acceptance Criteria
- [ ] Test suite is expanded for mobile coverage of Facility Locator

**Comment by mpelzsherman** [comment]
Existing test coverage is sufficient. New functionality will require new tests.
