### ISSUE TITLE
Past Community Care Appointment

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14040]
## User Story

As a user, I can see the following information for any **past Community Care appointment**: 
- Appointment type (Community Care)
- Date, time, and time zone
- Community Care facility name and address
- CTA to get directions to the facility (opens location in default Maps app)
- CTA to call facility (click to call) 
- Message to schedule a new appointment on VA.gov

## Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing, as needed) UI for a range of devices we are supporting, Android-specific wireframes

## Wireframes
- [Past Community Care appointment](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433202202)
