### ISSUE TITLE
Closed Appeal

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14043]
## User Story
For any closed appeal, I can see the following information: 
- [ ] Date appeal was received
- [ ] Date/time appeal was last updated
- [ ] Past events for appeal & their dates
- [ ] Message that the appeal is closed
- [ ] Veterans Affairs Benefits and Services phone number
- [ ] List of issues for the appeal

## Tasks
- [x] Find a staging account with a closed appeal (+226) 
- [x] Determine data elements for screens
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Wireframe
Follows the design of #14042.

**Comment by srmyers17** [comment]
F/w mtg with Steve
