### ISSUE TITLE
Mobile map post-mortem

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14050]
## Issue Description
Post-mortem for [Facility Locator Mobile map bug](map https://github.com/department-of-veterans-affairs/va.gov-team/issues/14046)

---
## Tasks
- [x] Determine root cause for mobile map breakage
- [x] Develop a plan to monitor/prevent in the future

## Acceptance Criteria
- [x] Facilities team understands root cause, has identified dependencies (if appropriate) and has implemented a plan to avoid this occurrence in the future. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
@mmiddaugh @mpelzsherman - I have spent some time testing on releases to check here was the mobile map broken and I have found that it was broken in this release - https://github.com/department-of-veterans-affairs/vets-website/releases/tag/vets-website%2Fv0.1.1047

For specifically this change - https://github.com/department-of-veterans-affairs/vets-website/commit/d8ec8cd3a748b132f9601a68504794b1c6934663

**Comment by mpelzsherman** [comment]
Thanks @brangi. This one was on me then, though I do not see what changes would have caused the issue. We've written a Cypress test that confirms the map is visible on mobile, and I will make sure to check the mobile map whenever making changes.

Hiring additional QA staff might also be something for VSA to consider, but again, mea culpa.

**Comment by mmiddaugh** [comment]
[Post Mortem](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/post-mortem/mobile-map-not-rendering.md) documentation
