### ISSUE TITLE
Mapbox support for IE 11 ending

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14052]
## Issue Description
Mapbox announced on August 13 a plan to remove support for Internet Explorer 11 in a future release of GL JS later this year. 
We are not currently using GL JS but may evaluate it for the future. 

## GA analytics for Internet Explorer
**Between 1/1/2020 and 10/5/2020, Internet Explorer was the 3rd most popular browser** 

| Browser | Percent of total users | Percent of sessions |
| -- | -- | -- |
| Chrome | 39.26% users | 40.24% sessions |
| Safari | 23.99% users | 20.47% sessions |
| Internet Explorer | 21.14% users | 23.66% of the sessions |

**Top search term (Facility type) searched by Internet Explorer users**
| Category | Number of users | Percent of total users | 
| -- | -- | -- |
| health | 312,126 | 52.51% |
| urgent_care | 95,366 | 16.04% |
| benefits | 32,970 | 5.55% |
| all | 30,816 | 5.18% |
| vet_center | 27,121 | 4.56% |
| cc_provider | 24,606 | 4.14% |
| pharmacy | 11,014 | 1.85% |
| cemetery | 7,959 | 1.34% |
| provider | 7,606 | 1.28% |

**Top search category (Service type) searched by Internet Explorer users**
| Category | Number of users | Percent of total users | 
| -- | -- | -- |
| (not set) | 378,368 | 61.89% |
| NonVAUrgentCare | 74,925 | 12.26% |
| PrimaryCare | 19,414 | 3.18% |
| EmergencyCare | 14,400 | 2.36% |
| 261QU0200X (Clinic/Center - Urgent Care) | 12,661 | 2.07% |
| UrgentCare | 10,384 | 1.70% |
| MentalHealthCare | 3,761 | 0.62% |
| DentalServices | 3,054 | 0.50% |
| 261QP2300X (Clinic/Center - Primary Care) | 2,882 | 0.47% |

---
## Tasks
- [ ] Identify risks to Facility Locator functionality in IE 11

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing
Please see 
Upgrade to Mapbox GL JS [#14786](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14786)
Merged in [#14660](https://github.com/department-of-veterans-affairs/vets-website/pull/14660)
