### ISSUE TITLE
[Spike] Research strategy for supplying mock appointments data

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#14051]
We need a strategy for dummy data for appointments because the MAP API interface is not ready. This should use betamocks which is
different than the VCR_cassette mock data.

Since we have no API access and neither does VAOS for the dev environment, we have a non typical problem to solve which is explained here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/dummy-data.md

If betamocks is a problem for some reason then we need a different strategy but hopefully that won't be necessary 

## Tasks
- [ ] Determine strategy for how betamocks can be used either by recording for VAOS in some staged area or creating the mock files from scratch
- [ ] document how mocked data gets created
- [ ] document how we will return mocked data and how to switch between mocked data mode and regular functionality

## Acceptance criteria
- [ ] Demonstrate how betamocks data is created and used and put this in the document
- [ ] document is written and complete

**Comment by massrb** [comment]
No one I asked had any idea how to use betamocks for this particular problem, but using monteblank as a proxy I was able to 
demonstrate how to get dummy data working for an endpoint in the health quest service:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/map-api-proxy.md

**Comment by dillo** [comment]
Use betamocks and vets-api-mockdata to accomplish this.
