### ISSUE TITLE
Best Bet change for licensing and certification

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14074]
## Issue Description
When you search on va.gov for licensing and certification, this url is the top search result, and you get a 404 when you click: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/licensing-certification-fees/

It needs to be removed. It's a nonexistent page. This should come up instead:
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/

---
## Tasks
- [ ] Get the invalid URL out of best bets. 

## Acceptance Criteria
- [ ] This page no longer surfaces in search results: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/licensing-certification-fees/
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
@bethpottsVADEPO this is now fixed with the new URL.  Do you want to add any descriptive text?  Would this work:

The GI Bill covers more than just tuition. You can use part of your entitlement to cover the cost of certain tests you need to take to become a licensed or certified professional—or to apply for college or a training course.

**Comment by bethpottsVADEPO** [comment]
@johnhashva Let's use the meta description we already have:
Find out how you can get reimbursed for registration fees, admissions tests like the GRE, GMAT, or LSAT, and specialized tests if your job requires a license or certification. Learn what forms you'll need to submit when applying for this benefit.

Is the title tag good for you to have too?:
Get Paid Back For Test Fees | Veterans Affairs

**Comment by johnhashva** [comment]
@bethpottsVADEPO  just added the meta description.  As for Title Tag -- little unclear to me which one is preferred.  I know using "Testing and Certification" as the title ensures those will be the keywords for the Best Bet.  Do you mind asking Danielle what's the typical approach for title?  From what I can tell, there's been a mix of titles.![Screen Shot 2020-09-25 at 5.42.28 PM.png](https://images.zenhubusercontent.com/5e934f0aea31042a586982e7/8b0952ee-c791-495d-a099-1c9062d54570)

**Comment by bethpottsVADEPO** [comment]
@johnhashva I wanted to reopen this ticket so I can follow up about the title. We should use the same title for Best Bets as we have for the title tag: Get paid back for test fees. I checked with Danielle. 

Once you make this change, will it get rid of the repeat in search results?:

<img width="964" alt="Screen Shot 2020-10-07 at 8 46 24 AM" src="https://user-images.githubusercontent.com/66026798/95354966-e3bfe080-0879-11eb-8a76-03ca61931f2c.png">

**Comment by johnhashva** [comment]
@bethpotts Made the title change and did not see this broken page URL  https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/licensing-certification-fees/ show up in the searches I conducted for _licensing and certification_ and _test and fees_.  But to be sure, we should create a redirect from that page to the new one.  That would be the only way to ensure users don't end up there.

<img width="758" alt="Screen Shot 2020-10-07 at 1 22 16 PM" src="https://user-images.githubusercontent.com/63107147/95365656-6fe4fe80-08a0-11eb-86d6-8e1cc39c0112.png">

<img width="763" alt="Screen Shot 2020-10-07 at 1 21 53 PM" src="https://user-images.githubusercontent.com/63107147/95365668-73788580-08a0-11eb-9695-8cc9082ea30d.png">

**Comment by johnhashva** [comment]
@bethpotts LMK if we can close this one.  TY.
