### ISSUE TITLE
[FE] Update Ranked questions verbage

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#14085]
## User Story
As a user, I should see wording that makes sense to me so I can fill out the form effectively 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [latest mock](https://camo.githubusercontent.com/5d0723a31874bb68dc36b8045bcbec85d17505a3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566343430353563363561356335346637636665353932382f39323165356366332d343461332d346132622d613234612d303162356334623837366165)

## Description:
To better utilize the built-in forms system. Update the wording for the ranked question.

## Tasks
- [ ] Update wording to match mockups
- [ ] Update header color

## Acceptance Criteria
- [ ] Have changes PR'd and merged in master
- [ ] The team sees the changes in staging.

**Comment by kristenmcconnell** [comment]
Wording updated in Zeplin. Use that when rearranging the wording.

**Comment by kristenmcconnell** [comment]
@mdewey This is actually the most up-to-date design. It includes feedback from Peggy (content). Please use this for this story. 
![Reason and concerns - Two question.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/921e5cf3-44a3-4a2b-a24a-01b5c4b876ae)

**Comment by mdewey** [comment]
@kristenmcconnell  and @abuckley3385  this in staging. Any feedback can go on this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/15521

**Comment by kristenmcconnell** [comment]
I'll add my feedback here. Because for the This visit page, it looks good to me. Color looks good.

**Comment by abuckley3385** [comment]
looks good
