### ISSUE TITLE
Update Breadcrumb on the 686 Application

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14080]
## Background
Given IA recommendations and feedback, the breadcrumb for the 686 application tool page should be clearly focused on the task the Veteran is expecting to take and not include the View task for the application. While similar and having opportunities for crossover, this should not be done via the breadcrumb.

## Tasks
- [ ] Update the breadcrumb for the 686 application too page to be:
**686 form:** `Home > View or change your dependents > Add or remove dependents form 21-686c`
- [ ] If needed, update the breadcrumb for the view page to be:
**View tool:** `Home > View or change your dependents > View your dependents`

## Acceptance Criteria
- [ ] The breadcrumb for the 686 application is updated
- [ ] If needed, the breadcrumb for the view dependents feature has also been updated
- [ ] A PR has been requested for merging these changes
