### ISSUE TITLE
Mobile API Design Doc: Push Notifications 

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14083]

**Comment by srmyers17** [comment]
## Tasks

- [ ] Get design docs from VEText

- [ ] Create design doc for VEText API integration into vets-api

**Comment by srmyers17** [comment]
### Possibilities for notifications:

**1. VEText powers them**

- [ ] Get API documentation from them and integrate their API into vets-api

- [ ] Give VEText certs (either from Test Flight app or VA account)

- [ ] VEText enables appointment notifications

**2. Local reminders for VAVC appointments
3. Claims status notifications that are powered by a server we build into vets-api that checks whether a user has had any changes to their status in the last 24hr**

### Next step:
- [ ] Need to confirm VA's prioritization with Steve, knowing that user prioritization wasn't high for MVP

**Comment by srmyers17** [comment]
- Ongoing collab with VEText
- Feature will be post-MVP
- @jjulian will add design

**Comment by srmyers17** [comment]
- @jjulian created PR on Friday for this

**Comment by jjulian** [comment]
External API is merged; work on VEText integration has not been started
