### ISSUE TITLE
Back translation check of coronavirus FAQs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14093]
## Issue Description
As part of our quality check of the potential for using the Google Translate widget to translate the coronavirus FAQs page from English to Spanish, we need to do back translation of the questions on the page (English > Spanish, then Spanish > English using translate.google.com) and check for inaccuracies.

---
## Tasks
- [x] Pull current FAQs into a spreadsheet (Danielle)
- [x] Add translations into spreadsheet (Danielle/Randi/Selina)
- [x] Compare original English version with final back-to-English version and highlight differences in final (Danielle/Randi/Selina)

## Documents
[Coronavirus FAQ page_Google translate_wip](https://app.zenhub.com/files/133843125/89c2e9d7-c9ed-4220-bf2e-5f5132c71841/download)

## Acceptance Criteria
- [x] Spreadsheet is filled out with translations and comparisons
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This is the small task we talked about briefly via slack last week. I've completed pulling the FAQs into the spreadsheet and translating some of them (you'll see that some translations are blank - these are newly or soon to be updated questions). Hoping that you and @lunascoop can help to finish this effort.  

What's needed is to translate & back translation those Qs that still need that, and then to highlight the differences in the final English version.

I put a 3 for the full effort, but I'd say this last part is probably more like a 1 or 2.

Thank you both in advance for your help with this!

FYSA @brianalloyd @MickinSahni

**Comment by lunascoop** [comment]
I've added the additional back to English translations to the spreadsheet and highlighted the translation difference.
[Back translation check - Coronavirus FAQs.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5307583/Back.translation.check.-.Coronavirus.FAQs.xlsx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @lunascoop!
