### ISSUE TITLE
Update ATO Control SOPs (info, location, etc.)

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14094]
## Issue Description
Taylor and I have reviewed each of the controls and have them in a "ready for submission" state. We wanted to take another pass at the SOPs for each of the controls to ensure relevance, proper placement, etc. This is the ticket to track that body of work.

---
## Tasks
- [ ] Updated SOPs. 

## Acceptance Criteria
- [ ] SOPs properly placed and contain proper information.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
