### ISSUE TITLE
Design intent Collaboration - Public Websites [Wizard migration effort, alerts in wizards]

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#14104]
## Context

Requesting a review for some changes I'm proposing to improve the alert UX in the wizards that route users to various forms.  Hoping this can be done async since this is a small part of the wizard migration effort, and we're not an an active collaboration cycle with this work.

Currently, these forms have a variety of alerts contained with in them. Many use our alert component, which is not optimized for mobile.   Examples of current state can be seen in a Mural board:

- [Education forms](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31?wid=0-1600888279547)
- [Higher Level Review](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31?wid=0-1600888562377)
- [Disability](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31?wid=0-1600888438837)
- [Chapter 31/36](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31?wid=0-1600889096451)

We'd like to introduce a lightweight, more mobile-friendly pattern to inform the user where they are being routed to when the wizard sends them to a form, and use a consistent pattern across all the wizards.  Peggy is working on content for these wizards, and we don't anticipate the need for as many `warning` alerts as we see today.  

[Here's a link to the prototype](https://preview.uxpin.com/66480d02dbf9bd2fc54639b82281d17911d89e6d#/pages/132759132/documentation/no-panels?mode=i), which has 5 mobile screens and 1 desktop.  I included documentation to provide context into the use cases the examples represent, and my general thought process about the design choices I made.  I've reviewed these with other VSA designers who have worked on the forms specific to their products, and they're on board with this approach.

**What we are NOT doing via this request**

- Asking for review of the content/design *surrounding* the wizard. Each benefit area needs a unique approach (though there will be similarities), and we're moving onto those next, once we're sure these alerts are in a good place.
- Asking for review of the questions inside the wizard.
- Submitting this for review to be adopted into the design system wizard pattern, since we haven't tested with users yet.

  

## Steps to complete Design Intent Collaboration

- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [ ] Crystabel and Emily to determine how much time reviewers have to provide feedback
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts

- [Link to product epic](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665)
- [Here's a link to the prototype](https://preview.uxpin.com/66480d02dbf9bd2fc54639b82281d17911d89e6d#/pages/132759132/documentation/no-panels?mode=i), which has 5 mobile screens and 1 desktop.  

## Meeting attendees from **requesting team**

Feedback to be provided async.  

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled feedback for EOD 9/30. Thank you!

**Comment by mnorthuis** [comment]
No IA feedback on this work.  

FWIW, I favor v2 of the "ineligible, soft next step", where the link is incorporated into the box with the message.  It seems clearer to me that the link is related to learning more about the message I'm getting in the box and gives me a place to go.

**Comment by peggygannon** [comment]
Hi, @andaleliz No major content feedback from me at this stage. I'm also in favor of incorporating the link into the box to tie it to the next step. I'm writing the alert with this in mind.

**Comment by andaleliz** [comment]
Thanks @mnorthuis and @peggygannon ! I appreciate the feedback. I think that option is clearer as well, so we'll move forward with that.

**Comment by CrystabelReiter** [comment]
@andaleliz 

We like this approach because it definitely saves a lot of space. The one piece of feedback we had on the consider level was to possibly stack the icon on top of the content instead of on the side. (Saves more horizontal space). Definitely submit a design system proposal if this tests well with users :) ! 

also thanks for being specific about the feedback request!

**Comment by jenstrickland** [comment]
**VSA Accessibility Feedback**

1. Agree with the decisions regarding styling of the "alertbox" and removal of the icon. In addition to saving horizontal space, reducing vertical height is also important to ensure relevant content is in view for mobile devices.

1. Regarding the heading order concern and approach of using bolded paragraph, **consider** potential semantic markup to leverage a `<fieldset>` element for this container, and a `<legend>` for the "Based on the info you've provided the right for for you is VA Form 22-1990.", with the button. This can also be used for the Ineligible soft next step v2 with the legend and link. See Potential markup examples included.

1. The Apply Now button **should** have text to be explicit about the action. While this "Apply Now" meets **MUST** criteria ([WCAG 2.4.4 Level A](https://www.wuhcag.com/link-purpose-in-context/)), best practice states the link/button text **should** make sense out of context, such as when a screen reader user navigates by focusable elements alone ([WCAG 2.4.9 Level AAA](https://www.wuhcag.com/link-purpose-link-only/)), such as with a screen reader and the keyboard.

1. Download PDF links **should** use the [download PDF link pattern](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340), which are to be [added to the design system](https://dsva.slack.com/archives/C0NGDDXME/p1600871794002700?thread_ts=1600871128.002400&cid=C0NGDDXME).

1. When the alert icon is used, it **should** be paired with screen reader only text indicating this is an alert. Was the [warning alert box](https://design.va.gov/components/alertboxes#warning) considered? It has the `role="alert"` included, so it is unnecessary to provide screen reader only text.

**Potential markup examples**
```
  <fieldset>
    <legend>Based on the info you've provided the right for for you is VA Form 22-1990.</legend>
    <button type="submit">Apply using VA Form 22-1990</button>
    <!-- if there is resistance to this label, here's an alternative: <button type="submit">Apply Now <span class="vads-u-visibility--screen-reader">using VA Form 22-1990</span></button> -->
  <fieldset>
```

```
  <fieldset>
    <legend>You'll need to submit a paper copy of VA Form 20-0996 to request a Higher-Level Review</legend>
    <p>If you have a decision date before… <!-- etcetera --></p>
    <button type="button" class="additional-info-button va-button-link" aria-expanded="false" aria-controls="tooltip-1"><span class="additional-info-title"><!-- react-text: 5 -->Read more<!-- /react-text --><i class="fas fa-angle-down"></i></span></button>
    <a 
  href="link-to-form.pdf" 
  download="VA Form 20-0996.pdf" 
  type="application/pdf">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
      Download VA Form 20-0996<dfn><abbr title="Portable Document Format">PDF</abbr> (96<abbr title="Kilobytes">kb</abbr>)</dfn>
</a>
  </fieldset>


```


cc @1Copenut for VSP review

**Comment by 1Copenut** [comment]
My only comment for VSP accessibility is to follow on what @jenstrickland said about the alert icon. It'd be better if this was a warning than an alert. Reading through this text, it might be very out of context if it announced to screen reader users immediately on page load.

No further comments!

**Comment by jenstrickland** [comment]
@1Copenut 

 In the design system, for the warning example the alert icon is used with the `role="alert"`. For "ineligible soft next step v1," the mockup shows an alert icon rather than an info icon, and would appear on the page after a couple of radio input selections, which is when the `role="alert"` would announce that there's an alert, not on page load. This behavior seems to be correct for this use case. Am I missing something?

![Screen Shot 2020-10-01 at 6 22 11 AM](https://user-images.githubusercontent.com/57469/94797672-752cdf80-03ae-11eb-8c9d-1d77f64466a5.png)

![Screen Shot 2020-10-01 at 6 21 55 AM](https://user-images.githubusercontent.com/57469/94797679-78c06680-03ae-11eb-9bf2-5e8d271d57a6.png)

**Comment by andaleliz** [comment]
@jenstrickland and @1Copenut thanks for the feedback!  My comments:

---

>consider potential semantic markup to leverage a `<fieldset>` element for this container, and a <legend> for the "Based on the info you've provided the right for for you is VA Form 22-1990.", with the button. 

I didn't hadn't thought of the `fieldset` element since there's not really a `set` or any inputs here. Thanks for the suggestion.

--- 

>The Apply Now button should have text to be explicit about the action. 

Based on the examples I saw on the page you linked to (first two bullets under "What to do" section), and the [WCAG doc examples](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html#navigation-mechanisms-refs-examples-head), we are good with what we have, since we have contextual text preceding the link. I'll additional recommend screenreader-only context be added to the buttons/links so it's ultra-clear

---

>Was the warning alert box considered?

Yes it was.  We feel strongly that a more lightweight solution than our large alert pattern is more appropriate in these form-gating wizards.

**Comment by andaleliz** [comment]
@CrystabelReiter thanks for the feedback! In terms of stacking the icon on top of the content instead of on the side - I'll explore that and see if it works better.

**Comment by jenstrickland** [comment]
> > The Apply Now button should have text to be explicit about the action.
> 
> Based on the examples I saw on the page you linked to (first two bullets under "What to do" section), and the [WCAG doc examples](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html#navigation-mechanisms-refs-examples-head), we are good with what we have, since we have contextual text preceding the link.

The best practice of the WCAG 2.4.9 Level AAA criteria recommends the explicit label, if that wasn't clear. It's not a **must** but a **should**.  It will make it clearer for those who navigate by screen reader and keyboard and focusable elements instead of reading everything on the page. It also supports those with cognitive considerations by being explicitly clear.

**Comment by andaleliz** [comment]
@jenstrickland, I need to check an assumption.  I'm assuming you'd prefer to see something like "Complete form VA 22-1990 to apply now" on the button. Is that correct?

**Comment by jenstrickland** [comment]
@andaleliz Sure, possibilities might be:

- Complete VA Form 22-1990
- Apply with VA Form 22-1990

**Comment by andaleliz** [comment]
Thanks, that helps!  I tried examples like during the design process. It causes the button text to wrap onto 2, sometimes 3 lines depending on the call to action. It takes up more vertical space, and isn't necessary, in my opinion, considering the a11y mark-up for the alert container this button will be in, and the contextual text immediately following the button.

I understand this suggestion as a **should**, and not a **must**, and would like to close this issue with the designs as they are.  Let's hop on a call if any further discussion is needed.

**Comment by jenstrickland** [comment]
Agreed, it's a **should**, and the VA 508 Program Office indicated in the last two monthly meetings that it encourages teams to meet the should (and the WCAG 2.1 & 2.2 criteria). The above option is 26 characters, where "Sign in to start your application" is 33 characters, so I didn't realize there would be an issue.

**Comment by andaleliz** [comment]
It's all good on desktop, but on mobile that the text starts to wrap when a button is in an alert.  Even with the reduced padding in my designs, more explicit button labels wrap onto multiple lines.

**Comment by andaleliz** [comment]
@jenstrickland clarified for me that VSA designers are **required** (not simply encouraged) to follow, **should** recommendations, so we will add explicit information to the buttons after all. cc @peggygannon as this impacts the calls to action on our buttons.  Jennifer's recommendations were:
- Complete VA Form 22-1990
- Apply with VA Form 22-1990

**Comment by peggygannon** [comment]
thanks, @andaleliz I'll be sharing my recommendations for the button language on our sync today.
