### ISSUE TITLE
Audit & upgrade outdated gems

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#1411]
NOTE: Dependabot might do most of this work for us.  See #116

Review the gems in our Gemfile 

Top priority should be our explicitly-required gems that are at least one major version behind. 
`bundle outdated --filter-major --only-explicit`
## Acceptance criteria
- [ ] Documentation on what features/changes might we benefit from and is it worth the effort to upgrade?
- [ ] For gems that justify an upgrade if the effort is really low, upgrade the gem, otherwise make an issue to upgrade the gem in a future sprint.
- [ ] Remove duplicated gems (investigate `pdftk` etc)
- [ ] Annotate and cleanup gemfile with comments

**Comment by kfrz** [comment]
Some notes to extract from [here]https://hackmd.io/iPaMR_bvSnG23m7TYZYjbA)

**Comment by kfrz** [comment]
[VCR](https://github.com/department-of-veterans-affairs/vets-api/pull/3583)
[awrence](https://github.com/department-of-veterans-affairs/vets-api/pull/3585)

**Comment by annaswims** [comment]
I'm hoping that we can [use dependabot](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/1146) to nudge us toward upgrades.  I like the idea of some sort of automated reminder, but I don't think CI or git hooks are necessarily the right places. 

I'm not sure about git hooks either.   If we add more noise to git hooks I'd expect people to disable them.

**Comment by annaswims** [comment]
the output of `bundle outdated --filter-major --only-explicit`
>

Outdated gems included in the bundle:
  * aasm (newest 5.0.6, installed 4.12.0) in groups "default"
  * activerecord-postgis-adapter (newest 6.0.0, installed 5.2.2, requested ~> 5.2.2) in groups "default"
  * [awrence](https://github.com/department-of-veterans-affairs/vets-api/pull/3585) (newest 1.1.0, installed 0.1.0) in groups "test"
  * carrierwave (newest 2.0.2, installed 0.11.2, requested ~> 0.11) in groups "default"
  * config (newest 2.0.0, installed 1.4.0) in groups "default"
  * faker (newest 2.8.1, installed 1.6.3) in groups "test"
  * [holidays](https://github.com/department-of-veterans-affairs/vets-api/pull/3634) (newest 8.0.0, installed 5.4.0) in groups "default"
  * oj (newest 3.10.0, installed 2.18.2) in groups "default"
  * olive_branch (newest 3.0.0, installed 2.0.0) in groups "default"
  * openid_auth (newest 1.0.2, installed 0.0.1) in groups "default"
  * pg (newest 1.1.4, installed 0.19.0) in groups "default"
  * pundit (newest 2.1.0, installed 1.1.0) in groups "default"
  * rack-attack (newest 6.2.1, installed 5.0.1) in groups "default"
  * rails (newest 6.0.1, installed 5.2.3, requested ~> 5.2.3) in groups "default"
  * redis (newest 4.1.3, installed 3.3.5) in groups "default"
  * restforce (newest 4.2.1, installed 3.0.0) in groups "default"
  * shrine (newest 3.1.0, installed 2.16.0) in groups "default"
  * sidekiq (newest 6.0.3, installed 4.2.10, requested ~> 4.2) in groups "development, test"
  * sidekiq-ent (newest 2.0.1, installed 1.6.1) in groups "production"
  * sidekiq-pro (newest 5.0.1, installed 3.7.0) in groups "production"
  * sidekiq-scheduler (newest 3.0.0, installed 2.2.2, requested ~> 2.0) in groups "default"
  * swagger-blocks (newest 3.0.0, installed 2.0.0) in groups "default"
  * [vcr](https://github.com/department-of-veterans-affairs/vets-api/pull/3583) (newest 5.0.0, installed 3.0.3) in groups "test"
  * web-console (newest 4.0.1, installed 3.7.0) in groups "development"

**Comment by annaswims** [comment]
## Merged PR's
Bump memoist from 0.15.0 to 0.16.2  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3669 
Bump dry-types from 1.1.0 to 1.2.2  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3660 
Bump rack from 2.0.7 to 2.0.8  dependencies security  https://github.com/department-of-veterans-affairs/vets-api/pull/3666 by dependab
Bump shrine from 2.16.0 to 2.19.3  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3662 
Bump rubocop-junit-formatter from 0.1.3 to 0.1.4  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3658 
Bump aasm from 4.12.0 to 5.0.6  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3659 
Bump iconv from 1.0.4 to 1.0.8  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3653 
Bump faker from 1.6.3 to 2.9.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3690 
Bump activerecord-import from 1.0.1 to 1.0.4  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3717 
Bump request_store from 1.4.1 to 1.5.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3714 
Bump addressable from 2.5.2 to 2.7.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3712 
Bump faraday_middleware from 0.12.2 to 0.13.1  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3716 
Bump sidekiq-scheduler from 2.2.2 to 3.0.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3696 
Bump rubocop-rails from 2.3.2 to 2.4.1  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3702 
Bump rubocop from 0.77.0 to 0.78.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3679 
Bump fastimage from 2.1.0 to 2.1.7  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3697 
Bump pdf-reader from 2.0.0 to 2.4.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3709 
Bump liquid from 4.0.0 to 4.0.3  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3700 
Bump redis-namespace from 1.5.3 to 1.7.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3688 
Bump ox from 2.8.2 to 2.12.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3689 
Bump dry-struct from 1.0.0 to 1.2.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3703 
Bump mail from 2.6.6 to 2.7.1  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3651 
Bump pdf-forms from 1.1.1 to 1.2.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3678 
Bump betamocks from `23ac096` to `f9800a7`  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3682 
Bump mini_magick from 4.9.4 to 4.9.5  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3681 
Bump statsd-instrument from 2.1.2 to 2.6.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3654 
Bump oj from 2.18.2 to 3.10.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3661 
Bump rubocop from 0.74.0 to 0.77.0  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3655 
Bump rspec_junit_formatter from 0.2.3 to 0.4.1  dependencies  https://github.com/department-of-veterans-affairs/vets-api/pull/3670 


## Approved but not merged yet
Bump rails from 5.2.3 to 5.2.4.1  dependencies https://github.com/department-of-veterans-affairs/vets-api/pull/3710 
Bump pg from 1.1.4 to 1.2.0  dependencies https://github.com/department-of-veterans-affairs/vets-api/pull/3701 
Bump aws-sdk-s3 from 1.9.0 to 1.60.1  dependencies https://github.com/department-of-veterans-affairs/vets-api/pull/3698 
Bump aws-sdk-sns from 1.1.0 to 1.21.0  dependencies https://github.com/department-of-veterans-affairs/vets-api/pull/3691
