### ISSUE TITLE
Add and coordinate with initial VFS Sentry 10 Admin Users

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14123]
## Background

As part of Sentry 10 rollout, we will want to "seed" the VFS/VSA teams with their respective admin users so they can modify project settings to allow their team members to be assigned to projects.

## Tasks

For each team enumerated below, we'll need to identify and assign a team admin in Sentry 10 (typically the PM):
- [x] #vfs-authenticated-experience
- [ ] #vfs-benefits-memorials-1
- [ ] #vfs-benefits-memorials-2
- [x] #vfs-caregiver
- [ ] #vfs-covid-bot
- [ ] #vfs-ebenefits
- [x] #vfs-facilities
- [x] #vfs-public-websites
- [ ] #vfs-ssoe
- [x] #vfs-vaos
- [x] #vsp-tools-be
- [x] #vsp-tools-fe
- [x] #vsp-identity
- [ ] #vsp-insights-analytics
- [x] #vsp-operations
- [x] #vsp-va-notify

**Comment by alexpappasoddball** [comment]
@kfrz One place to start is the GitHub teams that already exist.  We can use what is already in there (if any) for each of those teams.  The VSP teams should be straight forward, let me know which teams you don't have any good admin options for and I can run them down.

**Comment by alexpappasoddball** [comment]
@kfrz @thilton-oddball is this in a spot where we can close it?  We have enough admins to support the initial launch is all we should be shooting for here at this point I would think.  If there are needs that come up we can support adding them down the road.  Thoughts?

**Comment by thilton-oddball** [comment]
Designated admins where we were able to. Put final notification is #vfs-all-teams that gives directions for teams who do not yet have an admin.
