### ISSUE TITLE
[Spike] Create experimental endpoint to query mock appointments data via Mountebank

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#14142]
It was demonstrated that using the mountebank gem and server that mock data could be returned using a proxy:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14051

## Tasks
- [ ] Write test code that can proxy more than one endpoint using monteblank predicates
- [ ] document how to run the proxy
- [ ] save the code someplace

## Acceptance

- [ ] code written
- [ ] code tested
- [ ] documentation written

**Comment by abuckley3385** [comment]
@Dillo can we get a short user story for the functionally why we need the mock appt. data from Monteblank

**Comment by dillo** [comment]
@abuckley3385 Sure. I think the intent here is to unblock the FE on their development efforts by supplying them with mock data when they hit a specific endpoint; appointments related I presume. I will confirm this theory with all those involved and write up the story as you requested.

**Comment by dillo** [comment]
We will be using betamocks and vets-api-mockdata instead of mountebank. Closing issue.
