### ISSUE TITLE
Feature flag for pharmacies option

### ISSUE THREAD

**Issue by brangi** [department-of-veterans-affairs/va.gov-team#14154]
## Issue Description

FE needs a feature flag to toggle pharmacies option on/off

---
## Tasks
- [ ] Add feature flag `facilities_ppms_suppress_pharmacies`

## Acceptance Criteria
- [ ] Flag should appear on flipper dashboard 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
