### ISSUE TITLE
Project Kickoff - AuthXp [Direct Deposit for Education Benefits]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#14167]
## Steps to complete Project Kickoff
- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Attach all relevant artifacts to the ticket
- [X] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] Shira will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed and [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
**Link to rough draft of product outline:**
[Direct Deposit for Edu Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md) 

**Explanation of the problem space:**
Direct deposit for edu functionality still lives on eBenefits. Since we moved direct deposit for comp & pen to VA.gov last year, this means that Veterans now need to update their direct deposit info in two different places.

Historically, eBenefits has has issues around fraud + direct deposit. This is one of the major reasons we moved over direct deposit for comp & pen to VA.gov last year — VA.gov has greater security and requires 2FA for all users. With direct deposit for edu still on eBenefits, we're leaving that feature vulnerable.

EBenefits is eventually going away, so we need to migrate all functionality over to VA.gov. Direct deposit for edu is still an outstanding project.

## Meeting attendees from **requesting team**
- Product Manager (required): **Matt Shea**, **Jason Wolf**
- DEPO Product Lead (required): **Samara Strauss**
- Entire VFS team (recommended): **Sandra Hallie, Erik Hansen, Tressa Furner, Cassandra Allen, Lihan Li, Jim Adams**

Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages? **YES**/NO

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**PREFERRED TIME: Wed, October 14, 11:30am – 12:00pm**
