### ISSUE TITLE
Check meta descriptions for VR&E name change

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14168]
## Issue Description
When we changed references to the VR&E program from "Vocational Rehabilitation" to "Veteran Readiness," we should have also changed this in the meta descriptions. We need to look in each Drupal node where we made changes to confirm the meta descriptions are correct as well. 

Note that this change should only be made when Vocational Rehabilitation is used as a proper name. 

VR&E main page to start from: https://www.va.gov/careers-employment/vocational-rehabilitation/

---
## Tasks
- [x] Check meta descriptions for Veteran Readiness
- [x] Update any meta descriptions that have incorrect language 
- [x] Review changes and publish pages (Randi)

## Acceptance Criteria
- [ ] Correct meta descriptions are on published pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These pages have all been checked. The only change that needed to be made was adding an **&** into the VR&E name in the meta description for the How to Apply page. Otherwise all the other titles and descriptions already contained the new name. FYSA @bethpottsVADEPO 

This ticket can be closed.
