### ISSUE TITLE
Add types to the forms library

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14162]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a _____, I need _____ so I can _____.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by cvalarida** [comment]
## Prerequisites
- The forms library is a node package in `package.json`
  - The design doc for this is being written ([ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13987))

## Tickets to write
- [ ] Write a build command for the forms library
  - Includes using the `dist/` for the output of the library
- [ ] Use `tsc` to transpile the forms library
- [ ] Add the form config types
  - [ ] `formConfig`
  - [ ] Chapter
  - [ ] Page
  - [ ] Field
    - [ ] Object
    - [ ] Number
    - [ ] String
    - [ ] Array
    - **Note:** These may need to be broken down by field & widget; I'm not sure yet

**Comment by caw310** [comment]
Closing as this is an old ticket and Forms library is being rebuilt.
