### ISSUE TITLE
Usability Testing Prep - eBenefits [CH36]

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14172]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt 
- [x] Andrea to schedule meeting with VSP reviewers and **eBenefits Team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **eBenefits Team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **eBenefits Team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling)
- [Link to or attach prototype or mockups](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088565/simulate/sitemap) there is some overlap in part of the eligibility wizard that corresponds with the[ future CH31 work](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526673)
- ~~Link to or attach artifact with copy (if separate from prototypes/mockups)~~
- [Link to research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-research-plan.md) and [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-convo-guide.md)  
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_ 👇
- [Link to test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/3&group_by=cases:section_id&group_order=asc&group_id=209) _for QA practice area review_

## Meeting attendees from **requesting team**
- Product Manager (required): **Jason Wolf**
- DEPO product lead (required): **Steve Kovacs**
- Designer/Researcher (required): **James Adams**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite: **Thu, October 1, 1:30pm – 2:30pm ET**
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by pjhill** [comment]
Hey -- I forgot to leave formal comments in addition to the meeting.

1. Your test cases are forming up very well -- looks great!
1. Now is the time to work on gathering existing test users with appropriate test data or creating new test users with the data that you need in staging. We can discuss this in greater depth in the #vfs-test-accounts channel on Slack.
