### ISSUE TITLE
Fix broken link on On-the-Job Training page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14177]
## Issue Description
Per stakeholder Tammy Hurley there is a broken link at the bottom of the [on-the-job training and apprenticeships page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/). This should be updated with the following link: https://www.benefits.va.gov/BENEFITS/factsheets/education/OJT.pdf

![Screen Shot 2020-09-29 at 11.55.47 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/1cbe4a7f-00d5-411f-b6cd-f9b9c6644ddd)

---
## Tasks
- [x] Change link to new one provided by stakeholder (Randi)
- [x] Review and publish page (Randi)
- [x] Email stakeholder that change has been made (Randi)

## Acceptance Criteria
- [x] Link working on live page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This work was just completed this morning. Creating ticket for tracking purposes. FYSA @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
Change is live on site. Closing ticket. FYSA @bethpottsVADEPO
