### ISSUE TITLE
Update content on On-the-job training page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14178]
## Issue Description
Per stakeholder Joseph Welton, we need to change a line of content on the [on-the-job training and apprenticeships page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/). Under the question "How do I get these benefits?" the new text should be as follows: 

You’ll need to make sure the program is approved for VA education benefits.
Use the [GI Bill Comparison Tool](https://www.va.gov/gi-bill-comparison-tool/) to find out if the program is approved.

Screen shot of current content: ![Screen Shot 2020-09-29 at 12.49.02 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ccc78a5e-aee4-4c13-bb0e-05780a8352fd)
---
## Tasks
- [x] Update content on page (Randi)
- [x] Review and publish page (Randi/Beth)
- [x] Alert stakeholder that change has been made (Randi/Beth)

## Acceptance Criteria
- [x] Updated content appearing on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
Change has been made. Moving to validate and will close after Wednesday's deployment. FYSA @brianalloyd @MickinSahni

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @brianalloyd @MickinSahni
