### ISSUE TITLE
Remove alert about suspended funding from VET TEC page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14184]
## Issue Description
We currently have an alert on the [VET TEC page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/) explaining that funding is suspended until October 2020. Per stakeholder Tammy Hurley this can be removed now. She will follow up with new funding information at a later date.

Remove this alert: ![Screen Shot 2020-09-29 at 1.59.12 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/29919b87-e0f7-4ffd-910b-c9534034e4e8)

## Tasks
- [x] Remove alert from page in Drupal (Randi)
- [x] Review change and publish page (Randi)
- [x] Alert stakeholder that change has been made (Randi/Beth)

## Acceptance Criteria
- [x] Alert no longer showing on page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This change has already been made. Creating ticket for tracking purposes. FYSA @MickinSahni @brianalloyd Will close after today's deployment.

**Comment by RLHecht** [comment]
Change is live on site. Closing ticket. FYSA @bethpottsVADEPO
