### ISSUE TITLE
Update `vets-api` for View Payments

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#14196]
## Goal
Update`vets-api` to use a different BGS call to return the Veteran's payment history.  As directed by EVSS and BGS, we should now be using `retrievePaymentSummaryWithBDN` to retrieve the payment information.

## Tasks
- [x] Add a new service call that uses the new gem method to get payments
- [x] Add other attributes 
- [x] Update the current controller and serializer to return the correct payload
- [x] Add/update swagger and test(s) for the service

## Acceptance Criteria
- [x] The service, controller, and serializer have been updated to implement the new `retrievePaymentSummaryWithBDN` method.
- [x] Other attributes are added
- [x] Unit tests are complete
- [x] Swagger docs are complete
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
Draft PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5033

Waiting on the BGS gem PR to be merged in before I can submit this PR, that is why it is still a Draft PR for now.
