### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14198]
## User Story
As a user, I can see something while the app is loading. 

## Tasks
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting, Android-specific design as needed

## [Wireframe](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433329858)
