### ISSUE TITLE
Establish Ongoing Communication VRE API Team

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14206]
## Background
The VRE Team is writing a new API that we need to connect to so that we can send them structured data and to send things to Central Mail.

## Tasks
- [x] VRE + eBenefits figure out the API schema (Steve to share updated JSON)
  - [ ] via email, introduce BE team to and get a regular touch point with them (Steve)
  - [x] Get a list of their needs and get them what they need (Steve)

**Next Steps**
- [ ] Establish authentication points between BE and VRE; how we are going to connect to them?
- [ ] Test data connection

## Acceptance Criteria
- [x] Updated JSON has been shared

**Next Steps**
- [ ] An introductory email has been sent
- [ ] Authentication credentials have been requested
- [ ] A successful test

**Comment by steve-gov** [comment]
Here's a JSON payload that includes some of the things they asked for:
- particpant_id (pid) if we have it
- vet360_id if we have it
- edipi if we have it
- whether the application came from an authenticated user or not
- a specific bool for whether the address is military or foreign (think we could negotiate on this)
- answers to the three communication preference questions

I dropped in a few extra addresses so they could get a sense of how each use case would work.

```
data: {
      educationLevel: 12,
      useEva: true,
      useTelecounseling: true,
      meetingTime: 'early afternoon',
      isMoving: true,
      isAuthenticated: true,
      newAddress: {
        isForeign: true
        isMilitary: false
        countryName: 'AGO',
        addressLine1: '123 angola dr',
        addressLine2: 'address line 2',
        addressLine3: 'address line 3',
        city: 'Angola City',
        province: 'State Province Region',
        internationalPostalCode: 'ABC 123'
      },
      veteranAddress: {
        isForeign: false
        isMilitary: false
        countryName: 'USA',
        addressLine1: '123 at home dr',
        addressLine2: 'address line 2',
        addressLine3: 'address line 3',
        city: 'San Francisco',
        stateCode: 'CA',
        zipCode: '94122'
      },
      veteranAddress: {
        isForeign: false
        isMilitary: true
        addressLine1: '123 at home dr',
        addressLine2: 'address line 2',
        addressLine3: 'address line 3',
        city: 'APO',
        stateCode: 'AA',
        zipCode: '09045'
      },
      veteranAddress: {
        isForeign: true
        isMilitary: true
        addressLine1: 'USCGC HAMILTON',
        addressLine2: 'address line 2',
        addressLine3: 'address line 3',
        city: 'FPO',
        stateCode: 'AP',
        zipCode: '96667'
      },
      mainPhone: '1231231234',
      cellPhone: '1213213211',
      emailAddress: 'johnjacobdoe@email.org',
      veteranInformation: {
        fullName: {
          first: 'John',
          middle: 'Jacob',
          last: 'Doe',
          suffix: 'Jr.'
        },
        ssn: '*********',
        VAFileNumber: '*********',
        pid: '*********',
        edipi: '*********',
        vet360ID: '*********',
        dob: '1991-04-01'
      }
    },
```
