### ISSUE TITLE
[Research] Upcoming Appointment Questionnaire Usability Test Sessions

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#14208]
**Reference Materials**
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

**Tasks**
- [x] Make sure all participant sessions are scheduled
- [x] Create notes doc for team to use
- [x] Invite Clipboard team members (should anyone else be invited?) to participant sessions

**Acceptance Criteria**
- [x] Run the sessions with all participants
- [x] Gather notes from notetakers
- [x] Download participant videos from Perigean website

**Comment by kristenmcconnell** [comment]
Observers are going to send me their notes by Wednesday, October 21, so I'm going to close this ticket.
