### ISSUE TITLE
[POST LAUNCH] Limit Line Length for Address Lines 1, 2, and 3

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14207]
## Background
BGS limits characters in the address fields to 20 characters and we need a better way to manage them to separate lines .

## Tasks
- [ ] Write a helper method that checks line length and if over 20 chars, append to next line (address_line_2)
- [ ] Do not break words, like word wrap

## Acceptance Criteria
- [ ] Tests show that address lines are moving to the next lines appropriately
- [ ] A PR has been requested for merging
