### ISSUE TITLE
[Research] Upcoming Appointment Questionnaire Usability Analysis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#14219]
**Reference Materials**
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

**Tasks**
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

**Acceptance Criteria**
- [x] Create [research reports](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/mvp-usability/research-findings.md)/readout documents of findings
- [x] Update the [research history](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md) document
- [x] Deal with recordings once analysis is complete
- [x] Create necessary issues/tickets that address findings in coordination with Amanda
- [x] Schedule readout sessions with stakeholders, team, Demos, UX weekly(?)

**Comment by kristenmcconnell** [comment]
[PDF Research Report](https://app.zenhub.com/files/133843125/57b2ee9c-5d37-4e4f-a52c-457f7252b275/download)
