### ISSUE TITLE
[FE] Remove redundant Profile 1 logic after Profile 2.0 is launched

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#14218]
## Description

On September 30th 2020 we launched Profile 2.0 to all users. We need to clean up all unneeded components/logic that are no longer needed to support Profile 2.0.

Pay extra attention to the `MailingAddress` and `ResidentialAddress` components as they might be used in other applications.

This is ticket 2 of the steps to remove Profile 1.

Ticket 1 - Remove profile 2 feature flag
Ticket 2 - Identify dead code related to profile 1 and remove it
Ticket 3 - Reused code of profile 1 in profile 2 needs to be moved to the profile 2 folder && renaming of components/logic where needed

## Tasks
- [x] Validate that any Profile 1 logic is not shared with other applications
- [x] Move any shared logic with Profile 2.0 underneath the Profile 2.0 folder
- [x] Remove all unused components
- [x] Remove all unused reducers/actions/constants/utils/assets
- [x] Remove all related unit and e2e tests

**Comment by sanlouise** [comment]
There is nothing to validate on your end @mshea0606 since this was a code cleanup.

**Comment by mshea0606** [comment]
Thanks @sanlouise !
