### ISSUE TITLE
Closed Supplemental Claim

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14216]
## User Story
For any closed Supplemental Claim, I can see the following information: 
- [ ] Date Supplemental Claim was received
- [ ] Date/time Supplemental Claim was last updated
- [ ] Past events for Supplemental Claim & their dates
- [ ] Message that the Supplemental Claim is closed
- [ ] Veterans Affairs Benefits and Services phone number
- [ ] List of issues for the Supplemental Claim

## Tasks
- [x] Find a staging account with a closed Supplemental Claim
- [x] Determine data elements for screens
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Wireframe
Follows the design of .#14042
