### ISSUE TITLE
Update `vets-website` to Account for Changes

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14210]
# Background
Whenever we make an update to the `vets-json-schema` repo we also need to make a corresponding update to the `vets-website` repo to use the update from `vets-json-schema`. The update that will need to be made is that the commit hash in `vets-website` needs to be updated to the commit that merged the update for `vets-json-schema` into the master branch. Once that is done we need to submit a PR for the update to `vets-website`

## Tasks
- [ ] Update the commit hash in `package.json` for `vets-website`
- [ ] Submit a PR for review

## Acceptance Criteria
- [ ] The commit hash in `vets-website` now includes the latest changes to `vets-json-schema`
- [ ] A PR has been submitted for review
