### ISSUE TITLE
Refactor: "Not applicable" value for facility health service

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14220]
## Issue Description
There are updates to data fields within the facility health service content model which will require refactoring. 

1. CMS has changed the possible values for facility health service `referral `and `walk-in`

| Previous values | New values |
| --- | --- |
| Yes | Yes |
| No | No|
| Null | Not applicable |

<details>
<summary> Screenshot from https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/ </summary>

![image](https://user-images.githubusercontent.com/100468/105404311-6ed9a200-5bef-11eb-9006-e2cdef95b8e5.png)

</details>

---
## Tasks
- [ ] Refactor the facility health services template with regard to null -> Not applicable

## Acceptance Criteria
- [ ] When the value for `referral `and `walk-in` is `not applicable` or `null`, the front end does not say anything about walk-ins (for example)--the whole line is removed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
@ethanteague Do we need to change the query, or simply modify the template to display "Not applicable" when the value is null?

**Comment by mpelzsherman** [comment]
@mmiddaugh Can you please add a screen shot showing where the `referral` and `walk in` values are displayed?

**Comment by ethanteague** [comment]
> @ethanteague Do we need to change the query, or simply modify the template to display "Not applicable" when the value is null?

Yeah, query won't change, @mpelzsherman - just a template update.

**Comment by mpelzsherman** [comment]
If this is a new "hardended" field, we need to know where and how to display.

**Comment by mpelzsherman** [comment]
Confirmed that the fields are already in the graphql query:

https://github.com/department-of-veterans-affairs/vets-website/blob/80653f8e3e4f1509c2d1b1faf9a1a220f9f9ea9d/src/site/stages/build/drupal/graphql/file-fragments/appointmentItems.graphql.js#L8-L9

**Comment by mmiddaugh** [comment]
@mpelzsherman 
<details> 
<summary> Here's an example from University Drive Psychology </summary>

![image](https://user-images.githubusercontent.com/55411834/95506963-ef8ccf00-096d-11eb-8719-af368420e93a.png)

</details>

**Comment by mpelzsherman** [comment]
@mmiddaugh To avoid confusion, let's be careful not to mis-use the term "refactor".

Refactoring code means changing the implementation without changing the behavior.

In this case we changed the behavior of the template.

For more info, see https://refactoring.com/.
