### ISSUE TITLE
Design intent Collaboration [MVP VA Mobile App]

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14222]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [ ] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [ ] VSP <> **requesting team** design intent collaboration meeting completed and [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809)is updated
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/product%20outline.md)
- [High-fi prototype in Invision](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636866)

## Meeting attendees from **requesting team**
- Designer(s) (required): **Bridget Hapner**
- Product Manager (optional): **Sophie Myers**
- DEPO design lead (required as applicable): **Martha Wilkes**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now: 
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Crystabel will reach out as needed_

**Tue, October 6, 11am – 12pm** 

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

**The MVP VA Mobile App team is part of an experiment with the VSP Collaboration Cycle. Per guidance from VSP leads, we are going through parts of the cycle where appropriate and not going through others where mobile-specific support isn't available. For design, we are following iOS and Android design styles merged with styles from the VA.gov design library. We are setting up this meeting to stay in touch and set up a future post-MVP design effort for success. We understand the VSP design team has limited availability and we don't expect tons of mobile-specific support, but would just like to create this touchpoint so that the mobile app design team is in touch with VSP.** 

**Note: We have accessibility experts on our front-end partner team working on accessibility.**

**Note: We are relatively far in our design process already.**

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
@bridgethapner I know that you noted that you are relatively far in your design process already. Are there any artifacts you'd like VSP to review?
