### ISSUE TITLE
Content update for facility locator 

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14239]
## Issue Description
We need to make a minor content tweak to align with our updated references to masks vs. face coverings. We can also update the link to go directly to that question on the faqs page.

---
## Tasks
- [ ] Change "a cloth face covering" to "a mask that covers their mouth and nose" 
- [ ] Update link to go to the question about masks: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#more-health-care-questions

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/87cd9a62-636e-455b-a302-bbde5d893f98)

## Acceptance Criteria
- [x] Content updated on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mmiddaugh. This is the ticket that @davidconlon mentioned. Feel free to reach out with any questions. Thanks!

**Comment by brangi** [comment]
Content updated and merged
