### ISSUE TITLE
Update CH36 PDF to Account for New Schema Changes

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#14232]
## Goal
We need to ensure that the PDF is updated with the latest CH36 schema changes.

## Tasks
- [x] Obtain the blank PDF and sample payload from the FE
- [x] Insert the sample payload into the the PDF
- [x] Update PDF test specs to include latest changes

## Acceptance Criteria
- [x] A CH36 PDF has been created from form data
