### ISSUE TITLE
[FE] - Write Pact test

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#14233]
### Description
This ticket represents the body of work for completing the frontend setup of integration testing (using Pact) for a given app on VA.gov.

### Tasks 
- [x] Read [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/integration-testing/how-to-use-pact-for-integration-testing.md)
- [x] Sandra and Erik write at least 1 Pact test each for an endpoint related to the profile
- [x] FE code changes/contracts pushed to broker
