### ISSUE TITLE
IRIS Q&As: Batch 1, eBenefits

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#14242]
### Issue
For the launch of Learning Center MVP 1.0, IRIS eBenefits faqs must be edited and migrated. 

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

 - [x] PW to develop draft copy (Laura)

 - [x] PW to assign tags (Laura)

 - [x] PW to copyedit draft (Randi)

 - [x] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [x] Copy deck ready for DEPO review and attached to a content review GH ticket.

**Comment by lwalsh617** [comment]
Hi Randi,
This is ready for you to review. 
Thanks!
[lc-mvp-eBenefits-faqs-copy-v0.1-100220.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5330599/lc-mvp-eBenefits-faqs-copy-v0.1-100220.docx)

**Comment by RLHecht** [comment]
@lwalsh617 Here's the doc with my edits. I had a question about the Basic/Premium accounts that I put into the 
[lc-mvp-eBenefits-faqs-copy-v0.1-100220-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5335238/lc-mvp-eBenefits-faqs-copy-v0.1-100220-RH-edit.docx)
comments. Let me know if you have questions!

**Comment by RLHecht** [comment]
Closing ticket. Content review being tracked in ticket #14567
