### ISSUE TITLE
Fix Addt'l Batch #2 Form Detail Page URLs 

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#14248]
## Issue Description
We published batch #2 of VA form detail pages in ticket #12213 . We need to change the URL names for the URLs listed below to be consistent w/ Mikki's URL schema (remove "va" from URL). Ex: from /about-form-va0710/ to /about-form-0710/

- VA Form VA1107
- VA Form VA1100
- VA Form VA10101
- VA Form VA21a
- VA Form VA21
- VA Form VA2793
- VA Form VA2130
- VA Form VA2345
- VA Form VA2346a
- VA Form VA4597
- VA Form VA40-0895-6
- VA Form VA40-0895-8
- VA Form VA40-0895-7
- VA Form VA40-0895-11
- VA Form VA40-0895-10
- VA Form VA40-0895-17
- VA Form VA40-0241
- VA Form VA40-0895-12
- VA Form VA40-0247
- VA Form VA40-10190
- VA Form VA40-0895-9
- VA Form VA40-0895-13
- VA Form VA40-0895-15
- VA Form VA40-0895-3
- VA Form VA40-0895-14
- VA Form VA4939
- VA Form VA40-4970
- VA Form VA40-0895-16
- VA Form VA4597a
- VA Form VA40-0895-2
- VA Form VA4597b
- VA Form VA6298
- VA Form VA8824i
- VA Form VA0896a
- VA Form VA0904
- VA Form VA0730b
- VA Form VA0730a
- VA Form VA0120
- VA Form VA0730i
- VA Form VA0730h
- VA Form VA0220
- VA Form VA0710

---
## Tasks
- [x] Update the URL names of the URLs above and publish

## Acceptance Criteria
- [x] Page are published with the appropriate URL schema
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
These URLs have been updated and published. Closing ticket.
