### ISSUE TITLE
Address Unit Test Resiliency for View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14259]
## Background
It appears that some of the unit tests we have created for "View my VA payment history" (specifically `ViewPaymentsLists`) are intermittently failing for other teams and we are not sure why.  These need to be more resilient.

## Tasks
- [x] Examine the unit tests for this feature 
- [x] Establish what is causing the flakiness of the feature
- [x] Recreate the test as needed

## Acceptance Criteria
- [x] The unit tests for view payments are more resilient and don't intermittently fail

**Comment by micahchiang** [comment]
Further investigation revealed the probable cause of these tests failing consistently as to do with the improper implementation of `async/await` on some elements, per this conversation - https://dsva.slack.com/archives/C5HP4GN3F/p1602779915162300?thread_ts=1602778986.158600&cid=C5HP4GN3F

The expect statements in these tests should be updated to this type of syntax - 
`expect(await screen.findByText(/Payments you received/)).to.exist;`

**Comment by jason-gcio** [comment]
Is there a PR for this? Just making sure its ok to close.

**Comment by micahchiang** [comment]
PR here - https://github.com/department-of-veterans-affairs/vets-website/pull/14621
