### ISSUE TITLE
Transitioning from app to another app (eg, VA Video Connect)

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14256]
## User Story
As a user, I want to go from VA mobile app to another app in order to complete a transaction. 

## Potential Use Cases
- Get Care
- VA Video Connect

## Tasks
- [ ] Identify which apps we want VA mobile app to hand off to

- [ ] Map out hand offs 

- [ ] Identify any changes we want the other apps to make as a result of confusing UI, etc.
