### ISSUE TITLE
Datadog - Customize to capture application-specific metrics

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14267]
## Issue Description
Ensure that indices, labels, and annotations have been properly configured so that all application-specific metrics are being captured and pushed by the Datadog agent to the UI. 

Background: We want to ensure that the metrics available in Datadog are on parity with what is currently available in Prometheus.

---

## Acceptance Criteria
- [ ] Application-specific metrics are being captured by Datadog
- [ ] Application-specific metrics are observable through Datadog UI 
- [ ] Feedback from app teams to ensure that expected metrics are captured & available 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
(good question here from Rachael regarding how our taxonomy of data will affect the ability to tell good stories in other tools outside of DataDog)

**Comment by jhouse-solvd** [comment]
Will add additional tickets as needed to ensure that applications not owned by the Operations team have metrics captured per that teams needs and expectations.

**Comment by jhouse-solvd** [comment]
Please see https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16919 for our more recent incarnation of this effort.
