### ISSUE TITLE
Create Ansible role that will install Datadog agent

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14265]
## Issue Description
Create the Ansible role that will install the datadog agent onto selected instances (in development environment only for now)

---
## Tasks
Ansible variable in for the API key will determine whether or not DD will be enabled on the instance
Yaml files will pass variables into the build of the instance to determine the apps to "activate/monitor"

## Acceptance Criteria
Ansible role checked in and ready to be installed on various instances in development environment. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mydesignrocks** [comment]
- [x] **Ansible role created to install DD agent and merged as per PR # 7640**
- [x] **AWS account integration with new IAM user**
- [ ] **Jenkins pipeline testing - WIP**

**Comment by jhouse-solvd** [comment]
Completed. Closing.
