### ISSUE TITLE
Install Datadog agent on selected DEV instances

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14266]
## Issue Description
Install the Datadog agent on selected instances in the development environment 
---
## Tasks
Determine which instances we will install the DD agent on, based on type and priority 
vets-api {service, worker}, revproxy, fwdproxy, gids, cms {cms,-test} (16 instances)

## Acceptance Criteria
Agent installed on ~16 running EC2 instances in development environment: 
vets-api {service, worker}, revproxy, fwdproxy, gids, cms {cms,-test} (16 instances)

## Extra Credit
We can also use Loki as a guinea pig for rolling this out on ECS instances
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
PR is in, awaiting approval, then will install agent on DEV instances. Once merged, will deploy automatically.

**Comment by jhouse-solvd** [comment]
Closing.
