### ISSUE TITLE
App Directory Included in the Learning Center from Lighthouse/End-User-Experience-team

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#14279]
### Content support for:
- Unauthenticated (static) VA.gov pages;
- Apps or tools
- Other writing or editing requests

### Engineering support for:
- Redirects that have **first been vetted by the VSP IA team**
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [ ] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   *<The App Directory is a place for users to go to find out more info on the different applications they can connect their data to in order to help the veterans with various things in life. Right now there is only a static list on the Profile that displays the different apps a user can connect. After a few conversations, the App Directory is slotted to be included in the LC using an about template.  We have already done our own separate reviews and collaborations cycle checks evidence can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9238), but am confirming this as we speak. All we need to do now is work to remove some features from our current widget, provide an updated mockup of the app directory in the learning center (spoke with Jenn Lee about this), and incorporate it in the learning center.

Here is the draft [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14149), but will need to be updated per guidance and requirements for the learning center.>
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < Most of our info is on lighthouse Confluence, but this link will have the info but is going to be out of date, because of the transition to the learning center: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9238 >

---

## About your support needs
*I spoke with Jenn Lee and she directed me to this form, but our team will need to work with the public website team to include the app directory into the learning center. As stated above we may need some engineering guidance, but the widget is complete and just needs to confirm to the learning center's requirements.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

 We already have this in place and will not need support. It also has been approved. The only static content will be the lead into the widget for the list of applications. The content in the widget itself will be persisted from an API. 

- [ ] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * < URL list >
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * < list of new info >
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * < list of new info >

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

We may need some help with incorporating what is made into the learning center, but our widget is already made.  We also may need help having a demo environment for testing/ presenting. Will have @LeKeve provide more info when he comes back from paternity leave.

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * In short our team will need doing the following to get ready to incorporate the app directory in the LC.
- remove the filter feature form the widget to confirm to the LC requirements. 
- create a mockup for the app directory now in the LC using the about template. 
- We completed the checks for the collaboration cycle but will double-check if there is anything that needs to happen here. This is separate from the Learning center checks. At the very least we may need to update the call center before the launch. 
- incorporate a CTA in the widget to conform to the LC guidelines. 

We may need some guidance from engineering. Please let me know if there is any other information that is needed. 
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* <launch with the 1.0 beta launch of the LC>

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *End User experience team* with Lighthouse
- DEPO product owner: *Andrew Fichter*
- Product manager: *TJ Rice*
- Designer: *Carey Otto*
- FE engineer: *Kevin Lee*
- Product/team Slack channel: *We don't have a channel in DSVA slack, but will use this ticket as the source of truth*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ricetj @LeKeve. Just wanted to connect on this and see if you're ready to chat more about this from a public websites standpoint? Thanks!

**Comment by ricetj** [comment]
> Hi @ricetj @LeKeve. Just wanted to connect on this and see if you're ready to chat more about this from a public websites standpoint? Thanks!

Hello @DanielleThierryUSDSVA happy to chat more about this anytime. We are still reworking our mockups, but have met and done most of the checks for VSP. I know that @LeKeve has been working with Nick and Kelson as well. And I chatted with Jenn a bit about the URL structure, but I did see in your channel the new update for that here: https://dsva.slack.com/archives/C0173CAJ7A6/p1602882483358100

Once of the things we are still thinking through is what we want our url/ h1 header to be. 

Let me know if there are things you need anything from us besides what mentioned so far. I want to ensure we are good to launch in the learning center when the learning center launches.

**Comment by LeKeve** [comment]
> > Hi @ricetj @LeKeve. Just wanted to connect on this and see if you're ready to chat more about this from a public websites standpoint? Thanks!
> 
> Hello @DanielleThierryUSDSVA happy to chat more about this anytime. We are still reworking our mockups, but have met and done most of the checks for VSP. I know that @LeKeve has been working with Nick and Kelson as well. And I chatted with Jenn a bit about the URL structure, but I did see in your channel the new update for that here: https://dsva.slack.com/archives/C0173CAJ7A6/p1602882483358100
> 
> Once of the things we are still thinking through is what we want our url/ h1 header to be.
> 
> Let me know if there are things you need anything from us besides what mentioned so far. I want to ensure we are good to launch in the learning center when the learning center launches.

@DanielleThierryUSDSVA To add on to what @ricetj has said, an initial POC for the app directory widget has been completed and is ready to be integrated into any demo environments that the Learning Center spins up.

The mockups that are currently being worked on will meet some additional requirements for the Learning Center (call to action button, removing filter functionality, etc).

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @ricetj and @LeKeve! This is all great. I'll check in with Beth today, as she's the closest to the Learning Center progress, and get back to you on next steps for integrating. Thanks again!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ricetj @LeKeve. Met with Beth on this. Can you add the following to this issue so we can create a Drupal article for Resources & Support (formerly Learning Center)? Thanks!

- H1 (URL will autogenerate from this)
- Brief intro (we're happy to write this if needed)
- React widget we should add to the article 
- call to action for button

**Comment by ricetj** [comment]
> Hi @ricetj @LeKeve. Met with Beth on this. Can you add the following to this issue so we can create a Drupal article for Resources & Support (formerly Learning Center)? Thanks!
> 
> * H1 (URL will autogenerate from this)
> * Brief intro (we're happy to write this if needed)
> * React widget we should add to the article
> * call to action for button

Hello @DanielleThierryUSDSVA, the mock up that we are currently working on will have all:
- the H1 
- Brief intro (this was worked on before and may change a little depending on the mock up) 
- Call to action button 

When we have this mock up we can make the last few changes to the widget and also give you that as well. I do have a question for you though. Do you know the target launch date for the beta release of the Resources & Support (formerly Learning Center)?

CC: @careyotto, @LeKeve

**Comment by DanielleThierryUSDSVA** [comment]
I believe it's November 4. And then we'll continue adding articles as they're ready. So just let me know when you're ready with the mockup and widget and we can add. Thanks!

**Comment by ricetj** [comment]
> @ricetj I believe it's November 4. And then we'll continue adding articles as they're ready. So just let me know when you're ready with the mockup and widget and we can add. Thanks!

Hello @DanielleThierryUSDSVA does that mean we can still be added even after the launch date?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ricetj. Yes, I confirmed with @bethpottsVADEPO that we can add post-launch. Thanks!

**Comment by ricetj** [comment]
@DanielleThierryUSDSVA here is the mockup 
![image (9)](https://user-images.githubusercontent.com/49173478/98261557-94d99980-1f52-11eb-98f9-e29941538ce4.png)

**Comment by careyotto** [comment]
Missing from the designs above are the "Last updated: ___" message in the footer. FE devs tell me that's part of the code template and doesn't need to be in the design.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @ricetj and @careyotto! Will get our team started on bringing this into Resources & Support and will have them reach out with any questions. And that's correct on "last updated" - thanks!

**Comment by jenniferlee-dsva** [comment]
I think this has been completed. Okay to close it? (Feel free to repen if it's still in progress but I'm 99% sure I saw this live. :-)
