### ISSUE TITLE
VAMC Transformer knowledge transfer

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14286]
## Issue description
To prepare to support VAMC templates going forward, the Facilities team needs to understand how to create/update Transformers as the content structure changes. This knowledge transfer is governed by [VSA Scope in CMS Transformer Migration](https://docs.google.com/document/d/1Tne_KtVLNe2BR3RawCMGWVmkdJjK-eU3bEGRPdLQ6oA/edit)

Reference the epic [CMS Export Build [v1] — Transition from GraphQL to CMS Export + transformers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5989)

## Tasks

- [x] Use process from [CMS export documentation](https://vfs.atlassian.net/wiki/spaces/VP/pages/567541772/CMS+Export) to recreate an existing transformer [#14037](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14037)
- [x] Identify gaps in VSP's documentation
- [x] Review existing VAMC-related transformers and double check for drift [#14380](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14380)
- [x] Attend working session meetings which are focused on evaluating the transformer 

## Risks
- Traceability from HTML output to CMS is challenging

**Comment by mpelzsherman** [comment]
Closing since all linked issues and tasks have been completed.
