### ISSUE TITLE
Remove crosslinking to REAP page, redirect and archive

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14282]
## Issue Description

A SME contacted PW about this. Tammy Hurley said they would like to archive the page now that this benefit is no longer active. We discussed this at our IA/content weekly, and we agree that we should proceed with archiving. 

Related ticket for redirect: #14704

---
## Tasks
- [x] Gather analytics to support this decision. (Mikki)
- [x] Decide where to leave a mention of it and which mentions and cross linking to remove. (Mikki/Beth)
- [x] Implement changes to surrounding pages. (Beth)
- [x] Determine redirects. (Mikki/Beth)
- [x] Put in place redirects. (Mikki)
- [x] Archive REAP page. (Beth)

## Acceptance Criteria
- [x] REAP page gets archived and surrounding changes made.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
Here is analytics on page traffic.  The pageviews doc shows unique pageviews, time on page and bounce rate.  The nav-summary doc shows previous page info to help identify where we link to REAP.  

Traffic is lower, but still gets ~1700 views/month, so I would recommend a redirect for this URL so users do not get a 404 error.  It sounds as though the Post-9/11 GI Bill page (https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) is the benefit that those veterans would now need to apply for, so that is likely the best destination.

**Comment by bethpottsVADEPO** [comment]
**@RLHecht Here are the pages/edits to remove REAP crosslinks and mentions.** 
- [ ] https://www.va.gov/careers-employment/dependent-benefits/  Remove bullet point from blue box
- [ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/flight-training/  Remove the mention from the first bullet point and the two mentions (subhead and text link) under "What benefits can I get?"
- [ ] Left nav

**This will require product team to fix:** [@RLHecht to track down dev or designer who can help with this--it's possible there isn't a mention, but since it came up in Mikki's list of "previous page paths" we need to make sure.]
/education/apply-for-education-benefits/application/1990/benefits-eligibility/benefits-relinquishment/

**Mentioning all the pages with REAP mentions here, for @RLHecht 's awareness (nothing to do here):**
https://www.va.gov/education/other-va-education-benefits/index.html  Keep this REAP reference that points to Post-9/11 GI Bill
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/  I'm checking with Tammy about this REAP reference that points to Post-9/11 GI Bill
https://www.va.gov/education/other-va-education-benefits/veap/  Only left nav mention of REAP
https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/  Only left nav mention of REAP
https://www.va.gov/education/other-va-education-benefits/stem-scholarship/  Only left nav mention of REAP


**@mnorthuis I couldn't find a REAP reference or link from these pages that were listed in your analytics nav summary. Is there anything to do on these pages?:**
https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/
https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/
https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/
https://www.va.gov/education/about-gi-bill-benefits/
https://www.va.gov/education/
https://www.va.gov/education/how-to-apply/
https://www.va.gov/education/survivor-dependent-benefits/
https://www.va.gov/education/benefit-rates/
https://www.va.gov/education/eligibility/
https://www.va.gov/
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/
https://www.va.gov/careers-employment/vocational-rehabilitation/
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning/
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/
https://www.va.gov/education/change-gi-bill-benefits/
https://www.va.gov/disability/dependency-indemnity-compensation/

**Beth to check with Tammy about whether this should stay or go (keeping for now):**
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
Note: If you’re a member of the Reserves who lost education benefits when the Reserve Educational Assistance Program (REAP) ended in November 2015, you may qualify to receive restored benefits under the Post-9/11 GI Bill.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I removed the REAP mentions on those two pages and I disabled it in the left nav. Those changes should be life after today's deploy. I reached out to Peggy to find out the product team for the application and am waiting to hear back.

**Comment by RLHecht** [comment]
The changes I made earlier today are now visible on the live site. I reached out to Matt Self about that application page. Can close this once I hear back from him. FYSA @bethpottsVADEPO @brianalloyd

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Is there anything to do with that list above where I couldn't find any mentions or links to REAP?

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Also, should the redirected/soon to be archived REAP page be taken out of the sitemap?

**Comment by mnorthuis** [comment]
@bethpotts 

The pages that don't have links in the content likely just have the left nav link available, so that will need to be removed. 

Yes, it should also be removed from the xml sitemap.

**Comment by mnorthuis** [comment]
@bethpotts also need to make sure it is not in the search best bets.

**Comment by RLHecht** [comment]
I've archived this page. Will close ticket after today's deploy. FYSA @brianalloyd @mnorthuis

**Comment by RLHecht** [comment]
This work is completed. Closing ticket.
