### ISSUE TITLE
Higher Level Review: Issues

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14297]
## User Story

For any Higher Level Review, I can see: 
- List of issues currently on appeal 

## Tasks
- [x] Find a staging account with an active appeal 
- [ ] Determine data elements for screens in session with Steve
- [ ] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed
