### ISSUE TITLE
[Validate] - Launch search experience on LC

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14296]
## Issue Description
_Launch Search EXP on LC_

---
## Tasks
- [ ] _Validate all tasks have been closed_
- [ ] _Set up independent GA dashboard to validate metrics with search exp._

## Acceptance Criteria
- [ ] _Successful launch with measurable metrics as we work 1.1 release components_
---
## Launch DTG
TBD

**Comment by brianalloyd** [comment]
Completed
