### ISSUE TITLE
Adjust Validation Error for VA file Number on CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#14294]
# Background
When you go through the CH36 form in an unauthenticated state there is an optional field for `VA File Number`. When you type something incorrect in that field the validation message shows `does not match pattern "^[cC]{0,1}\\d{7,9}$"` We need to update this to be an error message that makes sense to the user.

## Tasks
- [ ] update the validation message to be `This field should be at least 4 character(s)` like the form 686c
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The validation message on the VA file number input on CH36 has been updated
- [ ] A PR has been submitted for review

**Comment by micahchiang** [comment]
https://design.va.gov/patterns/messaging-dictionary - Using this guide, the error message should be updated to `Please enter a valid VA file number`.
