### ISSUE TITLE
Board Appeal: Issues

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14295]
## User Story

For any appeal, I can see: 
- List of issues currently on appeal 

## Tasks
- [x] Find a staging account with an active appeal 
- [x] Determine data elements for screens
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Wireframe
This is the same design as #14297.
