### ISSUE TITLE
Supplemental Claim: Issues

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14299]
## User Story

For any Supplemental Claim, I can see: 
- List of issues currently on appeal 

## Tasks
- [ ] Find a staging account with an active Supplemental Claim  
- [x] Determine data elements for screens in session with Steve
- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Wireframe
This is the same design as #14297.
