### ISSUE TITLE
Product Guide and Video Version Control Process

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#14318]
## Issue Description
The Contact Center Team maintains a library of product guides and demo videos that are used by the contact center for training and job aides. To ensure the product guides are up to date and that the contact center is aware of the last training and communication on products, a version control process needs to be implemented. 

---
## Tasks
- [x] Review of current process
- [x] Identify updates to the process or documentation that take version control into account
- [ ] Confirm with VEO Tier 1 contact center group new process and tools work with their processes.

## Acceptance Criteria
- [ ] Identified process for how make updates to product guides
- [x] Identified locations for storing product guides for contact center team, VEO Tier 1 Group, and VSF teams. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
After speaking with VEO Team on 10/7/2020, they have stated that they do not not have access to GitHub (which was known) and Google Drives were not discussed.
They do have a SharePoint site, and have provided access to @clantosswett and I.  We are able to add the product guides to this location for housing.  However, the issue remains on how to properly update product guides, notate and track the updates.  

One suggestion is adding in a glossary or some sort of notation reflecting the origination date, modification details and date.  This will ensure that the Contact Center trains their agents accordingly.  Other suggestions are welcome.  We will discuss during our Thursday sync and discuss.

**Comment by starlow00** [comment]
@clantosswett and @Kimberley2019  Thought I attached this Friday, but I don't see it here. [https://app.zenhub.com/files/133843125/cb22a496-cdaf-451c-8138-cd360a03e99f/download](https://app.zenhub.com/files/133843125/cb22a496-cdaf-451c-8138-cd360a03e99f/download)

**Comment by starlow00** [comment]
Contacted Kimberley for meeting re. this ticket.

**Comment by Kimberley2019** [comment]
@starlow00 and I met on 1/12/2020 and decided the following process:

1.  Kimberley will log onto the VA side in order to verify access to the VEO Sharepoint site.  If access is available, gather the current list of product videos and guides and version dates to provide to Steven.

2. Provide Steven the collected information.

3.  During our call tomorrow, we will check with VEO to determine if they have a preference on how guides and videos are uploaded to the site.

4.  Once that has been finalized, then documentation will be uploaded to GitHub for this process if necessary.

**Comment by Kimberley2019** [comment]
This is the current draft of the SharePoint Upload process.  This should be finalized by EOW, depending on the response time from VEO.

https://docs.google.com/document/d/1merXujj9Kz1jTiglWgL7q58oJRaq_4PGGiC-CWMTE5Y/edit

**Comment by Kimberley2019** [comment]
The process has been sent over to VEO Contact Center as of today for their review.  Once we receive feedback, we will move forward accordingly.

**Comment by Kimberley2019** [comment]
Below is the SalesForce Upload Process 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/salesforce-upload-process.md
