### ISSUE TITLE
[BE] Configure SOCKS proxy for use with Sentry 10

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14319]
## Background

On 10.1.20, @thilton-oddball posted in vfs-all-teams that as of October 6th, we'll be upgrading to Sentry 10 and all issues will be sent there. **Before October 6th, we need someone from our team to login and verify we can access Sentry 10**.  @lihanli seems to be the best person to do this work. 

- [Here is Travis' original post in Slack](https://dsva.slack.com/archives/CE4304QPK/p1601585113063900)
- [Here is the internal tool setup documentation linked from Slack](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md)

Travis is the point person for questions and can triage as needed if there are other people who can help.

## Tasks

- [x] Read through Travis' Slack post
- [x] Read through internal tools documentation
- [x] Configure SOCKS proxy for use with Sentry 10 as necessary
- [x] Login to http://sentry10.vfs.va.gov to verify we can access Sentry 10

**Comment by lihanli** [comment]
completed

**Comment by Samara-Strauss** [comment]
Awesome, thank you so much!!
