### ISSUE TITLE
COVID-19 Dashboard Contact Center Data Validation

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#14317]
## Issue Description
Review and validate that the data in the new contact center data form is correct and accurate.

---
## Tasks
- [x] Review data and make any changes when necessary. 

## Acceptance Criteria
- [x] Final data set that is correct and accurate. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Reviewed the Master Contact Center COVID-19 data sheet and it is correct with no needed change. Tagging @jonwehausen and @Kimberley2019 for awareness.

**Comment by jonwehausen** [comment]
@clantosswett Thank you so much here! Really appreciate you working through. Will close this 😄
