### ISSUE TITLE
[FE]/[BE] Engineer Ramp Up 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#14311]
## Descption 

Help Dillo's onboarding... 

## Tasks

- [x] Schedule 1-on-1 meetings for MWF
- [x] Get local dev env working
- [x] Create status of current tickets
- [x] Get a few tickets ready for Dillo for next sprint
- [x] Create a Road map for engineering for between now and end of Q4

**Comment by mdewey** [comment]
We are feeling good, the team feels like the ramp-up is as complete as it can be.
