### ISSUE TITLE
[UI] Complete Questionnaire List Design

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#14312]
# Product Documentation
[Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
[Feature - Questionnaires List ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## User Story/ies

* Use Case: Veterans need the ability to manage their questionnaire list on va.gov in addition to receiving a notification to complete the form.

* Description - Forms List - Completed forms page to show the form that was completed and others that have not been completed or in progress
## Tasks
- [X] Finalize detailed mockups and callouts of Questionnaire Manager page [https://zpl.io/VOOek8j] 
- [x] Review with [Accessibility](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14385) and feedback incorporated or documented for team review 
- [x] Review with content

## Acceptance Criteria
- [x] UI review meeting and callouts with engineer for layout and callouts
- [x] published Link and updated product feature outline 
- [x] Accessibility review complete
- [x] Incorporate content feedback into designs

**Comment by kristenmcconnell** [comment]
@peggygannon - Can you review the content on the following [wireframes](https://zpl.io/VOOek8j)? Only look at the Questionnaire List section. I think that I gave you the correct access to the Zeplin to make comments. Let me know if you have trouble. In particular, I would love feedback on the lead text under the page title. This is the Questionnaire List feature, where a Veteran can view/complete/print all of their healthcare questionnaires.

**Comment by kristenmcconnell** [comment]
Outstanding questions for the Questionnaire Manager page:

1. @abuckley3385 @mlighdc @LEHigley Is this the correct information for getting help on this page? It is the same information that we are displaying within our MVP questionnaire. Would the numbers shown even really be helpful in the context of this page? Are there any other phone numbers or contacts that should be listed?
![Screen Shot 2020-10-08 at 3.03.54 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/5eb355a1-91f2-4d62-ad14-5f6d370a7040)

2. @abuckley3385 We never decided (that I remember) about the read-only view of the questionnaire, which would be accessible from the completed tab. Do we want to explore the technical feasibility of that? or just limit our scope for now to the print view from the completed tab? I believe that the read-only view would be a "nice to have" from a user perspective, but the print view could probably serve the same purpose.

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mlighdc @LEHigley I thought of one more outstanding question...
It relates to the use case of: there are no questionnaires to display in the Questionnaire Manager. The current design is shown at the bottom of the attached image. It is the grey box that says "You don't have any questionnaires."

It is encouraged to give Vets a next step if they see nothing. Other va.gov features have given Veterans a number to call if they think it is wrongly empty.

What would be our next step be? Does one phone number exist that could handle this and provide more information to the Veteran? Should we show the VAMC's phone number where the Veteran has their scheduled appointment? Some other idea?

![Screen Shot 2020-10-09 at 10.34.06 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/aee421ae-d3f2-4c02-bbc7-6070d6bcec43)

**Comment by mlighdc** [comment]
@kristenmcconnell I am hesitant to add a phone number because how would a veteran know if they should have a questionnaire or not? @abuckley3385 @LEHigley did you get any indication in your previous research regarding if the veteran will know ahead of time if they have a questionnaire or not to fill out? I believe for the eScreener they do call the veterans directly.

**Comment by kristenmcconnell** [comment]
@mlighdc That is kind of why I was asking. I wanted to have the discussion. It is good to provide next steps, but those steps need to be meaningful. We can leave the design as is until we work out the full workflow.

**Comment by mlighdc** [comment]
Thanks for asking the question and planning ahead @kristenmcconnell!

**Comment by peggygannon** [comment]
HI, @kristenmcconnell Finally, reviewing this! 

Can you tell me where the questionnaire list screen will appear on VA.gov, and how users will find it? (will it live within VAOS?) 

I'm tweaking intro a bit and it would be helpful to understand how users will find this page.  thanks!

**Comment by kristenmcconnell** [comment]
@peggygannon We don't know yet. I'm asking about it in our current usability testing session. We plan to engage IA next sprint too. We also discussed the need for a landing page prior to this page, which "sells" this feature (but nothing is designed yet). Let me know if you have any further questions.

**Comment by kristenmcconnell** [comment]
@peggygannon Would it just be the lead text that you would change based upon where this is located?

**Comment by peggygannon** [comment]
ok, thanks @kristenmcconnell , Yes, where this page lives within the questionnaire flow would affect the page title and intro. I will make some recommendations today, but know that we will need to continue to tweak as we determine I/A for this page.

**Comment by kristenmcconnell** [comment]
That makes complete sense. Thank you.

**Comment by peggygannon** [comment]
Hello, @kristenmcconnell 

Here is initial content feedback for this screen. H1 and intro are very much a WIP, as this still needs an I/A review to determine where this screen will live in the questionnaire workflow.

also, I didn't see an option on this screen for users to "print" their questionnaire. If this is mentioned in the intro, then we should have this functionality on this page. 



WIP H1: **Your health care questionnaires**
Intro: Review and keep track of your completed health care questionnaires and any you need to fill out before your upcoming appointment. You can also print a copy of questionnaires you've completed. 


*To consider* 
maybe have 3 tabs? otherwise user will have to scroll though "To do" list to find "in progress" ones...
To do
In progress  
Completed 

{cards}
**Questions for your upcoming appointment** (I recommend we change to  better match header on the questionnaire)
{CTA button} Answer questions (to match CTA button on questionnaire)


**Questions for your upcoming appointment**
{CTA} Finish questions


{alert} 
**We don’t have any health care questionnaires in our records for you right now**
If you think this is an error, [what would be the CTA to give users????]

**Comment by kristenmcconnell** [comment]
@peggygannon Check out the "Completed" questionnaire page too. zpl.io/2vwJm35
Veterans will only be able to print questionnaires that they completed. Three tabs is interesting, but at this time, we don't expect Veterans to have a very long list of new/in-progress questionnaires. Three tabs is definitely something that we will need to keep an eye on as we add use cases and gather some analytics.

Thank you for the feedback.

**Comment by kristenmcconnell** [comment]
Peggy's feedback incorporated into the designs. Engineering callouts added. Published to Zeplin and added to the product feature document. I just need to have review meetings with product and engineering.
