### ISSUE TITLE
Write, build and publish LC step-by-step article for how to apply for Specially Adapted Housing

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14310]
## Issue Description
The content team needs to write and build a step-by-step article for the learning center on how to apply for Specially Adapted Housing. This will be done post MVP launch and should be grouped with other housing-related questions. We should pull from the content from this [IRIS question](https://iris.custhelp.va.gov/app/answers/detail/a_id/1815/kw/How%20do%20I%20submit%20an%20application%20for%20Specially%20Adapted%20Housing%20(SAH)%2F%20Special%20Housing%20Adaptation%20(SHA)%20benefits%20on%20the%20eBenefits%20website%3F). 

---
## Tasks
- [ ] Write content for a step-by-step LC article including screenshots of the steps (Laura)
- [ ] Copy edit doc (Randi)
- [ ] Review content (Beth)
- [ ] Build Drupal page (Selina/Randi)
- [ ] Review page (Randi/Beth)
- [ ] Publish page (Randi/Beth)

## Acceptance Criteria
- [ ] Step-by-step article published within learning center
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpottsVADEPO I created this ticket under the LC super epic but I didn't see an epic yet for content that's post-launch.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - This IRIS faq only gets about 20 pages views a month, so I didn't add it to the high priority list we sent to Raleigh. I have it captured on my post-October list. Can I close this ticket?

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Can you confirm that due to low page views referenced above, we are not doing this article and can close this ticket? 
FYSA @RLHecht

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Yes, thank you. We have a tier 1 page on this topic: https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/
