### ISSUE TITLE
Refactor CH36 Payload

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#14325]
## Description
The payload for Chapter 36 needs to be refactored so it better aligns with business rules used to PDF forms as well as rules used in Central Mail. 

## Considerations
1. Wrap claimant information in `claimantInformation` object and remove `claimant` prefix
1. Change `veteranInformation.ssn` to `veteranSocialSecurityNumber` and make top level
1. Change `countryName` to country
1. Always force `postalCode` over `zipCode`
1. Remove `veteranInformation` wrapper object and make `veteranFullName` top level
1. [Optimal data model to use for PDF and Central Mail](https://github.com/department-of-veterans-affairs/vets-api/blob/6ce7a8b23935820d9d3ccc7eba92a274579706b2/spec/fixtures/pdf_fill/28-8832/kitchen_sink.json)
1. Potentially use an adapter during `transformForSubmit` if it's the easier way to go. 

## Tasks
- [x] Update payload using a `transformForSubmit` function
- [x] Submit PR for review

## Acceptance Criteria
- [x] Payload is formatted as needed by Back End
- [x] A PR has been submitted for review
