### ISSUE TITLE
Input reviewed IRIS batch 1 content into Drupal for LC

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14323]
## Issue Description
We need to start adding content into Drupal for our LC MVP launch, starting with the IRIS batch 1 copy deck that Laura completed. 
This ticket is just for the implementation in Drupal (not publishing) using single and multiple Q&A templates. Randi will do a walk-through with Selina of the different templates and components before getting started. 

Note that the sandwich layers of the templates are still being built, so we will start with the main body copy and go back into nodes to add other elements as they are available. We may need to create a new ticket for those other layers depending on when they are ready. 

Word doc to grab content from: 
[https://app.zenhub.com/files/133843125/fc6bc1a4-d23a-452c-b69f-494c9a29a17f/download](https://app.zenhub.com/files/133843125/fc6bc1a4-d23a-452c-b69f-494c9a29a17f/download)

## Tasks
- [x] Add main copy to single Q&A templates (Selina)
- [x] Build out multiple Q&As based off the copy deck (Selina)
- [x] Review nodes and compare to copy deck (Randi)

## Acceptance Criteria
- [x] All IRIS questions from the batch 1 copy deck are added into Drupal.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks for opening ticket! I added the Word doc to this, above.

**Comment by RLHecht** [comment]
@lunascoop This is the ticket to start adding the first batch of IRIS Q&As to the new learning center templates. Let me know when you have time to do a call and we can walk through it together in Drupal. The templates look a little different from our benefit detail pages and we'll need to put content in at different stages since not all the elements are available just yet.

**Comment by lunascoop** [comment]
I've entered the IRIS batch 1 content into Drupal (minus Related info links and content, which need copy for). Here are the nodes for review and notes:

## Signing in to VA.gov: https://prod.cms.va.gov/node/8222
### How to sign in to VA.gov
- How do I sign in to VA.gov? https://prod.cms.va.gov/node/8208
- Why did I get an email from ID.me asking to confirm my email address? https://prod.cms.va.gov/node/8209
- I didn’t get a confirmation email from VA.gov. What should I do? https://prod.cms.va.gov/node/8211

### Common issues with signing in to VA.gov

- What if I see an error message when I try to sign in to VA.gov? https://prod.cms.va.gov/node/8213
- What if I can't sign in to VA.gov because my password doesn't work? https://prod.cms.va.gov/node/8214

## Verifying your identity on VA.gov: http://preview-prod.vfs.va.gov/preview?nodeId=8233
### How to verify your identity on VA.gov

- How do I verify my identity online? https://prod.cms.va.gov/node/8223
- Can I verify my identity in person? https://prod.cms.va.gov/node/8224
- Can I verify my identity by phone? https://prod.cms.va.gov/node/8225

### Common issues with verifying your identity on VA.gov
- How else can I verify my identity other than through ID.me? https://prod.cms.va.gov/node/8226
- I don’t have a smartphone. How do I verify my identity through ID.me? https://prod.cms.va.gov/node/8227
- What if my credit is frozen and I’m trying to verify my identity? https://prod.cms.va.gov/node/8228
- What address should I use to verify my identity if I live overseas? https://prod.cms.va.gov/node/8229
- What if I’m having trouble answering the ID.me security questions? https://prod.cms.va.gov/node/8230
- What if I answered the security questions, but I'm still not verified? https://prod.cms.va.gov/node/8231 link for "now" needs to be adjusted to jump to accordion item 4 per the Word doc
- I don’t want to add 2-factor authentication. Do I have to? https://prod.cms.va.gov/node/8232

## Privacy and security on VA.gov: http://preview-prod.vfs.va.gov/preview?nodeId=8249
### How we keep your personal information safe
- Why should I trust VA.gov? https://prod.cms.va.gov/node/8234
- Why do I need to verify my identity to use advanced tools on VA.gov? https://prod.cms.va.gov/node/8240
- What’s ID.me, and why should I trust it? https://prod.cms.va.gov/node/8241
- What information does ID.me collect, and is it shared with anyone? https://prod.cms.va.gov/node/8242
- What’s the 6-digit security code that ID.me is asking me for? https://prod.cms.va.gov/node/8243

## Managing your VA.gov profile: http://preview-prod.vfs.va.gov/preview?nodeId=8259
### How to update your military or personal information

- What if my military information is wrong in my VA.gov profile? https://prod.cms.va.gov/node/8255
- What if I need to change my personal information on VA.gov? https://prod.cms.va.gov/node/8258

**Comment by lunascoop** [comment]
Changes to question titles: 
1. Why did I receive an email from ID.me asking to confirm my email address?
Changed to: Why did I get an email from ID.me asking to confirm my email address?
1. I didn’t receive a confirmation email from VA.gov. What should I do?
Changed to: I didn’t get a confirmation email from VA.gov. What should I do? (This actually wasn't too long, but I changed it to be consistent with the accordion title change we previously discussed: Why did I receive an email from ID.me asking to confirm my email address? to Why did I get an email from ID.me asking to confirm my email address?)
2. When I try to sign in to VA.gov, I see an error message that something went wrong. What should I do?
     Changed to: What if I see an error message when I try to sign in to VA.gov?
3. What should I do if I can’t sign in to VA.gov because my password isn’t working?
    Changed to: What if I can't sign in to VA.gov because my password doesn't work?
4. ~~What if I’ve tried the steps to fix the problems above, but I still can’t sign in to VA.gov?
Changed to: What if I still can’t sign in to VA.gov?~~ Deleted per this [Slack comment](https://dsva.slack.com/archives/G018JLSB4A2/p1602373431004100)
5. If I can’t or don’t want to verify my identity through ID.me, what are my other options?
Changed to: How else can I verify my identity other than through ID.me?
6. What should I do if my credit is frozen and I’m trying to verify my identity? 
Changed to: What if my credit is frozen and I’m trying to verify my identity?
7. I’m having trouble answering the ID.me security questions. What should I do?
Changed to: What if I’m having trouble answering the ID.me security questions?
8. I can’t verify my identity by answering the security questions. What should I do now? 
Changed to: What if I answered the security questions, but I'm still not verified? 
9. Why do I need to verify my identity to use advanced tools and services on VA.gov?
Changed to: Why do I need to verify my identity to use advanced tools on VA.gov?
10. What information does ID.me collect, and do they share it with anyone else?
Changed to: What information does ID.me collect, and is it shared with anyone?
11. What if I need to change my name or other personal information on VA.gov?
Changed to: What if I need to change my personal information on VA.gov?

**Comment by RLHecht** [comment]
I've reviewed all of these articles and made a few minor copy tweaks. @bethpottsVADEPO Should I close this ticket and create a new one for your review of all of these or leave it open since we still need to deal with related info?

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please close this issue after you copy and paste the titles and nodes into this ticket I created for Mikki to review buttons and related links: #14979

**Comment by RLHecht** [comment]
Nodes have been copied into the other ticket for Mikki. Closing this ticket.

**Comment by RLHecht** [comment]
New nodes created for the following articles (we took them out of the Verifying ID)

Premium DS Logon preview-prod.vfs.va.gov/preview?nodeId=8503
Sign up for a Premium My HealtheVet preview-prod.vfs.va.gov/preview?nodeId=8507
