### ISSUE TITLE
EPIC: Full Accessibility & 508 Office Audit [Facility Locator]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14321]
## Steps to complete the Full Accessibility & 508 Audit: 
- [ ] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts when you request a full review_
- Access information for the tool or feature: [Production Facility Locator](https://www.va.gov/find-locations). No credentials needed. 
- [Link to your accessibility test plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13384)
  - Complete/check-off the required items here:
    - [x] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - [x] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - [x] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - [x] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - [x] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - [x] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)

## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

The Facilities team requests this full review after resolving most high-severity defects, with the exception of issues marked with `508-issue-leaflet-mapbox`. **Please note:** A [discovery effort](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8535) is slated for Sprint 32 (beginning 10/7) to evaluate the Mapbox version options and associated level of effort and value.

**Comment by mmiddaugh** [comment]
@jenstrickland since our mapbox upgrade is in progress, I wonder if it makes sense to hold this off a bit longer?

**Comment by jenstrickland** [comment]
@mmiddaugh Experience tells me that is a good idea. Even though I convey the scope limits of the work sent over, too often I see the reviewer do the entire thing. Wise to sidestep that. Ping when ready! 😄

**Comment by 1Copenut** [comment]
Hi @mmiddaugh . We're working through the backlog as our new VSA specialist comes online and this one is near the top of the list. Reading through the ticket is looks like the full audit should focus on the form, results list, and profile views. Should we add the map also, or review it as a separate work item?

**Comment by mmiddaugh** [comment]
@1Copenut Historically, we've avoided the map because of leaflet but now that we've upgraded, it's a non-issue. We're making a few tweaks to focus for the new "clear the input" feature and are updating error messages with Josh's input during this sprint (which ends 3/9). I think after these two updates, the FL will be in a good place for an accessibility review, if that timing will work.

**Comment by 1Copenut** [comment]
@mmiddaugh Thank you for this context! Angela added three items to the audit backlog, two are labeling items and one is related to the map search radius. We'll be happy to take a look after your sprint end on 3/9 at the clear the input feature. Please let Angela or I know if you have questions.
