### ISSUE TITLE
Military Information - Error State

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14338]
## User Story

As a user, I want to see an error message when my military information is incorrect or cannot be displayed. 

## Tasks

- [x] Technical analysis: What error states are in vets-api today?

- [ ] UX analysis: Of what is available today, which error states do we need to account for in the mobile app? Are there any additional error states?

- [ ] Product: Define AC based on analysis

- [ ] UX design of screen(s)

- [ ] Usability testing if needed

**Comment by srmyers17** [comment]
Expected Error States:

![Screen Shot 2020-10-08 at 1.18.27 PM.png](https://images.zenhubusercontent.com/5de7efc226120baf54e97f2e/2102448b-2da8-484b-8236-76a012c7deb8)
