### ISSUE TITLE
Profile - Error States

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14341]
## User Story

As a user, I want to see an error message when my contact info is incorrect or cannot be displayed. 

## Tasks

- [x] Technical analysis: What error states are in vets-api today?

- [ ] UX analysis: Of what is available today, which error states do we need to account for in the mobile app? Are there any additional error states?

- [ ] Product: Define AC based on analysis

- [ ] UX design of screen(s)

- [ ] Usability testing if needed

**Comment by srmyers17** [comment]
Per: https://htmlpreview.github.io/?https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/docs/index.html

Expected Error States:
![Screen Shot 2020-10-08 at 1.20.15 PM.png](https://images.zenhubusercontent.com/5de7efc226120baf54e97f2e/65cdf1fc-8e20-40a1-af0c-26c2c8862621)

**Comment by srmyers17** [comment]
Expected Error States for ADDRESS:

![Screen Shot 2020-10-08 at 1.21.38 PM.png](https://images.zenhubusercontent.com/5de7efc226120baf54e97f2e/caec7c89-1d6d-4b71-a481-7a76b97e867c)

**Comment by srmyers17** [comment]
Error States for PROFILE UPDATES:

[Uploading... Screen Shot 2020-10-08 at 1.22.46 PM.png ]
