### ISSUE TITLE
Appointments - Error state

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14344]
## User Story

As a user, I want to see an error message when my appointments are incorrect or cannot be displayed. 

## Tasks

- [ ] Technical analysis: What error states are in vets-api today?

- [ ] UX analysis: Of what is available today, which error states do we need to account for in the mobile app? Are there any additional error states?

- [ ] Product: Define AC based on analysis

- [ ] UX design of screen(s)

- [ ] Usability testing if needed
