### ISSUE TITLE
Analytics Reporting for Product Health MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#14353]
## Issue Description
We currently share out the Analytics Weekly "Product Health MVP" to #vfs-analytics that product decision makers use to check on submission errors or success. New VFSs have launched this year that have not been added to this weekly report, and we need to update the report so that new products have the same level of visibility.

---
## Tasks
- [x] Add newly tracked forms onto the weekly "Product Health MVP" Google Sheet
    - [x] 22-10203 -- Application for STEM Scholarship (Education Product)
    - [x] 10-10CG -- Caregiver Application (Family Member Benefits Product <- new section)
    - [x] 1995 -- GI Bill Comparison Tool (Education Product)
    - [x] Medical Device Reordering Tool (Health Care Product)
- [ ]  STRETCH  - Add the data from the Sheets dashboard to Domo, to be redesigned at a later time

## Acceptance Criteria
- [ ] Product Managers and Product Owners can understand their weekly submissions updates in our "source of truth" weekly Google Analytics share out.

**Comment by jonwehausen** [comment]
@bmcgrady-ep to update existing spreadsheet with the additional forms needed

**Comment by jonwehausen** [comment]
@joanneesteban @bmcgrady-ep 

New form additions and changes have been QAed and have been confirmed to mirror GA numbers. 

All that remains is to replicate these changes on the Monthly report.

**Comment by joanneesteban** [comment]
Closing this ticket. Weekly MVP is updated, Monthly sheet is hitting query limits. We're asking folks to click into GA to see the monthly numbers.
