### ISSUE TITLE
Design of appointment cancellations

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14364]
## User Story
As a user, I want to cancel an appointment. 

## Use Case
- [ ] Display a cancel button & design flow for VA appts only
- [ ] Display "Call your medical center to cancel"  instructions card where can offer either phone number or online cancellation 
- [ ] Display "cancel" flow that will be incorporated backend that automatically pulls information if specific VA location does not allow cancelation.
- [ ] Display reschedule appointment flow after cancellation (later User story)

## Questions:
- is the cancelation of the appointment the same as the cancel request? Are we going to consider this within this story?
- VAOS team shared that you can only cancel in person, video, and cc appointments can’t be canceled online so should we also create a flow for those we cant cancel in person?
- how does backend handle  "we can’t tell which appointments those are in advance that may be canceled"
- does the user manually move from pending to appt or the call center?

## Tasks
- [ ] UX for cancel appointment flow for all appointment types
- [ ] Usability testing as needed
- [ ] Style sheet documentation, as needed
- [ ] consult with VAOS/VSP for content language

**Comment by srmyers17** [comment]
Note, for now, we won't update the prototype card that captures what users should do to cancel right now (ie, go to VA.gov)

**Comment by bridgethapner** [comment]
@msmanak :wave: Re your questions, I have a couple of answers I can share from prior VAOS discovery: 

is the cancelation of the appointment the same as the cancel request? Are we going to consider this within this story? -- Cancelations of appointments and requests are different, but we only need to worry about one. To make appointments, Veterans need to put in a request on VAOS & have it manually approved. For MVP we will only include confirmed appointments, so we don't need to consider canceling requests in this story. Lmk if you have more Qs about this! 

VAOS team shared that you can only cancel in person, video, and cc appointments can’t be canceled online so should we also create a flow for those we cant cancel in person? -- My POV is we should copy the VAOS feature. I dug in a little bit to see how VAOS is handling this now & see they have solves for both scenarios: 

If they can cancel on VAOS: 
![Screen Shot 2020-12-10 at 8.29.00 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/dde27656-50c4-41e6-93ac-55960d2acf21)

If they need to cancel by phone:
![Screen Shot 2020-12-10 at 8.35.56 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/c5e48979-694f-4c4c-b948-976b19ebb0d1)


My initial thought is maybe we replace the [Need to cancel? card at the bottom of each appointment screen](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432457680) with either: 
1. [If online cancellation is available] A cancel button that launches a confirmation step
2. [If online cancellation is not available] Text and a phone number to call to cancel 
 
does the user manually move from pending to appt or the call center? -- We don't need to worry about this for MVP since we aren't dealing with requests. But to answer the Q I think the Medical Center approves each request which moves an appt from Pending to Confirmed.

**Comment by msmanak** [comment]
posting this for reference.`title={`We couldn't cancel your ${typeText}`}
    >
      {isBadRequest ? (
        <p>
          We're sorry. You can't cancel your {typeText} on the VA appointments
          tool. Please contact your local VA medical center to cancel this
          appointment:
        </p>
      ) : (
        <p>
          Something went wrong when we tried to cancel this {typeText}. Please
          contact your medical center to cancel:
        </p>
      )}
      <p>
{facility ? (
          <>
            <strong>{facility.name}</strong>
            <br />
          </>
        ) : null}
        {!!facility && <FacilityAddress facility={facility} />}
        {!facility && (
          <>
            <a target="_blank" rel="noopener noreferrer" href="/find-locations">
              Find facility contact information
            </a>
          </>
        )}
      </p>`

**Comment by msmanak** [comment]
![Screen Shot 2020-12-22 at 3.09.48 PM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/9e2b64a9-c55a-425d-bd9a-c140fc1fd0a8)

**Comment by msmanak** [comment]
![Slice-cancelation.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/1fc577e5-eab7-4113-b41e-62ccae4f2b65)

**Comment by bridgethapner** [comment]
Just looking at this & have one small suggested change -- I think we can remove "Ok" from the left-most screen & just offer a consistent card with phone information that users can't dismiss. And same for the second screen in, we can have one CTA here, I don't think we need 'No, take me back' since we're not doing an overlay like the web is doing. 

![Cancel-Apts-UX-update.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/4cacdd66-2f5c-42c2-b6c1-61719240dc9e)
