### ISSUE TITLE
[Accessibility] [UI] VSA A11y Design Review - Healthcare [Questionnaire List]

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#14385]
**What is the Questionnaire List?**
A page that listed all questionnaires that the Veteran needs to complete as well as previously completed questionnaires.
- [x] Review the [feature doc.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

**Tasks**
- [x] Complete an accessibility review of the [Questionnaire List wireframes.](https://zpl.io/VOOek8j)
_Only review the Questionnaire List section (3 screens) of the Zeplin._
_I just sent you an invite, Jennifer, so you should be able to open with this link, then add comments to the document._

**Acceptance Criteria**
- [x] Add accessibility comments to the [Zeplin](https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780) file.

**Comment by jenstrickland** [comment]
1. For the tabs, I am currently only familiar with the tabs used in the mobile view of Facility Locator, although I've also seen AuthXp team exploring the use of tabs. This is something to check with VSA Design (Shawna) and VSP Design (Emily, Crystable).

2. If this moves into development, the tabs should use semantic markup similar to the following:

    ```
    <ul role="tablist">  
      <li role="presentation">
        <a role="tab" href="#section1" id="tab1" aria-selected="true">To do</a>
      </li>
      <li role="presentation">
        <a role="tab" href="#section2" id="tab2">Completed</a>
      </li>
    </ul>  
     ```
    - Please review the developer guidance for additional details, including responsive development and JavaScript to manage focus: https://inclusive-components.design/tabbed-interfaces/

3. Since Completed is a link, **consider** making the text on the tab link blue and underlined to cue that it is a link.


![Screen Shot 2020-10-05 at 12 35 14 PM](https://user-images.githubusercontent.com/57469/95106952-3d53ce00-0707-11eb-955e-3190759dff59.png)

**Comment by kristenmcconnell** [comment]
Shawna actually suggested tabs, since it is only two items. It mimics the tab design on VAOS (mobile and desktop).

**Comment by jenstrickland** [comment]
## STILL IN PROGRESS

1. Heading order indicated in enclosed screenshot

2. Recommend using a description list for the list of questionnaires, with a `dt` for each of the questionnaires

```html
  <h1>Healthcare questionnaires</h1>

  <p class="va-introtext">Check to see if you have any… </p>

  <ul role="tablist">  
    <li role="presentation">
      <a role="tab" href="#section1" id="tab1" aria-selected="true">To do</a>
    </li>
    <li role="presentation">
      <a role="tab" href="#section2" id="tab2">Completed</a>
    </li>
  </ul>  

  <h2>To do questionnaires</h2>

  <dl>
    <dt class="vads-u-font-size--h3">Upcoming appointment questionnaire</dt>
    <dd>
      <dfn>Due date: </dfn> 
      Wednesday, August 14, 2020
      12:30 p.m. ET
    </dd>
    <dd>
      <dfn>Appointment details: </dfn> 
      <dfn class="vads-u-visibility--screen-reader">Location: </dfn>Douglas VA Medical Center
      <dfn class="vads-u-visibility--screen-reader">Date: </dfn>August 15, 2020
    </dd>

    <dt class="vads-u-font-size--h3">Another questionnaire</dt>
    <dd>
      <dfn>Due date: </dfn> 
      Tuesday, September 29, 2020
      2:30 p.m. ET
    </dd>
    <dd>
      <dfn>Appointment details: </dfn> <!-- etcetera -->
```



![Screen Shot 2020-10-05 at 12 49 09 PM](https://user-images.githubusercontent.com/57469/95119204-96c4f880-0719-11eb-8a3c-d04e1263387c.png)

**Comment by jenstrickland** [comment]
Feedback complete! @kristenmcconnell — let me know if anything is unclear. 😃

**Comment by kristenmcconnell** [comment]
@jenstrickland: No questions. Changed serif to sans-serif - good design feedback. All feedback incorporated into wireframes for engineering.

**Comment by jenstrickland** [comment]
@kristenmcconnell **I cannot thank you enough!** 💐
