### ISSUE TITLE
[Epic] LC Home Page - MVP 1.0

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14388]
## High Level User Story/ies
As a Veteran, I need to view LC articles so I can find more information about a benefit or service I'm interested in.

## Product Outline
This is WIP and may evolve based on user research and technical findings.

Final name: Resources and support.

- [ ] H1: Resources and support for your VA benefits and services
- [ ] Lc homepage will include search option prominently. It will include both LC and 'all va' options.
- [ ] Must enable search error messages and standard system error messages.
- [ ] LC homepage must allow full width banner alert component
- [ ] LC homepage must allow in-body alert component (reusable or non-reusable) - TBD ux recommendation: below the search bar
- [ ] LC homepage CMS governance - owned and managed by PW. - Up to 5 articles can be displayed per category and then a link to see all of the articles in that category - 'Go to all articles' (in this category).
- [ ] On 1.0 and 1.1 launch, the PW content team should have the ability to curate which 5 articles to surface on the homepage under each category. (In the future, we'd like this curation to be automated based on analytics, such as what article users view most often each month or X timeframe TBD.)
- [ ] The categories in the 'Find articles by topics' should appear alphabetically by the category name, with the exception of the 'Other' category which should always be the last category.
- [ ] The audience labels under the beneficiary vs. non-beneficiary boxes should appear in alpha list. Up to 5, and then expand link to show more.
- [ ] Must enable default analytics tracking

## Hypothesis or Bet
**If** _update LC Homepage_ **then** _LC articles can be accessible to a large veteran audience_.

## OKR
_TBD_

**Comment by jenniferlee-dsva** [comment]
1.0 completed, and closing
