### ISSUE TITLE
[CONSIDER] Enhance editorial experience for adding PDF links (VAMC)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14386]
## Issue Description
From Ryan Stubblebein: 
As a local VAMC content editor, I need to manage links within WYSIWYG content so that I can efficiently update pages. 

**Background:** 
Some pages such as  [Animal Research](https://www.va.gov/pittsburgh-health-care/research/safety-security/animal-research/) has many  links to pdfs which are needed by current and prospective researchers at the site. Currently, the majority of the pdfs use a direct link to a file (link to file or video), but a few of the links are hyperlinked from the rich text section of a WYSIWYG. File listings within the WYSIWYG use qualifiers (i.e. who the document is intended for; how to fill out the form; etc.)

- Linked documents need to be downloadable outside of the VA firewall (difficult with simple link)
- Editors want to be able to make numbered lists of links so they are easier to organize. 
- Editors need an easy way to manage the links (rather than individually)
- Editors want to add a brief description to links to make them more identifiable. 

  

---
## Tasks
- [ ] _[TBD]

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
