### ISSUE TITLE
[FE] Address Feedback on Landing Page

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#14387]
## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d5e01a9b85b431a14)

## Description
Update the UI from user research 

## Tasks
- [x] Intro page- All new content needs updated for unauth. and auth
- [x] Intro page- Moving button to bottom and Remove the top button
- [x] Intro page- Button name update
- [x] Fix the login bug.
- [x] Hide the in progress message. 

## Acceptance Criteria
- [x] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
EDIT: updated work from this PR : https://github.com/department-of-veterans-affairs/vets-website/pull/14802

**Comment by mdewey** [comment]
In staging, can you verify @kristenmcconnell and @abuckley3385? 

I am going to set a meeting for us to review all the UI research implementations

**Comment by kristenmcconnell** [comment]
I can see the "Continue questions" button state, which was an excellent catch on your part. But, I can't see the "Answer questions" button state to visually verify that.  
 
Everything else looks good.

**Comment by kristenmcconnell** [comment]
Also confirming that this says "questionnaires" instead of "questions" (as in the wireframes) due to the variable controlling that wording. I'm assuming that variable is also what displays in the in-progress messaging, etc. If so, it totally makes sense and let's run with questionnaires. 

![Screen Shot 2020-11-16 at 3.35.46 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8e0e2ca2-d5e5-4228-84ef-098e09ade553)

**Comment by abuckley3385** [comment]
looks good

**Comment by mdewey** [comment]
@kristenmcconnell  Good catch! I do have control over that and will address it in the [new ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16278)
