### ISSUE TITLE
Review map enhancement discovery

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14392]
## Issue Description
Creating a new Facility Locator user search experience is a 4Q2020 priority. 
There are a number of problems which need to be solved for our Veterans users, including:

- An upcoming data limitation which will impact the search radius
- When a Veteran initiates a search, the map continues to zoom out until results are found. If no results are found, we display a general error message.
- The Facility Locator actively searches and re-searches as the user interacts with the map. The user does not have a way to stop this process or indicate that the map is set for a search.
- Veterans are not given information in all scenarios to understand why the search failed or how to be more successful.
- Implementing “predictive search” is a planned enhancement to the search on Facility Locator. This will allow us to show the list of matching place names in a scrolling div under the text field.

Leyda has done comparative analysis of how other modern websites are handling these scenarios. We need to fine-tune our solution approach with Veteran research. 

### Comparative analysis of searches limited to 250 miles [#12635](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12635)
- [Analysis in Google Sheets](https://docs.google.com/spreadsheets/d/1sIqiSYLL6JXqaQJ3iGUnBYYjOxFLTmn0TRWeN0HcDbM/edit?usp=sharing)
- [Recommendations with supporting visual examples](https://docs.google.com/presentation/d/1FNvhu7peex3EfufXeNWZYIA4F2cZs2RuArdaBOwT9zg/edit?usp=sharing)

 ### Comparative analysis for map interaction  [#13568](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13568)
- Link to [competitive analysis in a Google Sheet](https://docs.google.com/spreadsheets/d/1sIqiSYLL6JXqaQJ3iGUnBYYjOxFLTmn0TRWeN0HcDbM/edit?usp=sharing)
- Link to [competitive analysis in PDF](https://app.zenhub.com/files/133843125/315c0bd6-e7c8-4144-9222-19670e7b25e2/download)
- Link to [recommendations in Google Slides](https://docs.google.com/presentation/d/1FNvhu7peex3EfufXeNWZYIA4F2cZs2RuArdaBOwT9zg/edit?usp=sharing)
- Link to [recommendations in PDF](https://app.zenhub.com/files/133843125/c4cfa450-1831-4e8a-a79e-7453fa26d507/download)

### Comparative analysis for predictive search [#13567](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13567)
- [Comparative map analysis](https://docs.google.com/spreadsheets/d/1sIqiSYLL6JXqaQJ3iGUnBYYjOxFLTmn0TRWeN0HcDbM/edit?usp=sharing)

### Related issues
[#13229](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13229) for map display when zooming
[#9498](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9498) for supporting users when no results are found
[#5201](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5201) for proposed 250 mile limitation
[#13299](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13299) for optimizing map view

---
## Tasks
- [ ] Review issues linked above to understand problems which need to be solved
- [ ] Review comparative analysis artifacts for discovery findings
- [ ] Formulate list of areas to research/questions to answer

## Acceptance Criteria
- [ ] Designer/Researcher is prepared to participate in Map enhancement solutioning workshop
- [ ] List of areas to research/questions to answer

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Was created as initial issue for new team member. No longer needed
