### ISSUE TITLE
Finalize additional tags for LC MVP based on IRIS Q&As

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14399]
## Issue Description
We need to consider additional tags based on the content we now know we're moving forward with for 1.0.

---
## Tasks
- [ ] Danielle, Mikki, and Beth to review this list.

## Tags for Account and profile
- **sign in**

## Tags for other topics and questions (removed direct deposit, which we'd been considering)
- **claims and appeals status**
- **payments and debt**

## For consideration (maybe not for 1.0)
- **contact information** (for 1.0 there's only 1 article, with a wall of phone numbers. But in the future there will be VSOC counselors list of email addresses, etc.)
- **ID cards** (IRIS questions about both the VIC and military retiree card)

**Note:** There are only articles about direct deposit at this stage, none about other payment-related or debt-related topics, so for MVP we don't need a "payments and debt" tag. In addition, when it comes time to revisit tags as Resources and support expands, we agree that it makes sense to separate "payment" from "debt" since they are very different types of content--one is funds coming to the Veteran (yay!) and the other is funds owed to VA (not so much yay!).

## Question:
What to do as far as tagging articles about My HealtheVet, DS Logon, eBenefits, and ID.me? Would all of those have a sign in tag? Will they already be in the account and profile category?

## Acceptance Criteria
- [ ] Final list of tags agreed upon.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Summary of convo with Danielle and Mikki:
We have concerns about getting too granular with tags where there are only a small handful of articles. We could quickly get to tag overload if we take this approach, making it difficult for content authors to do a good job choosing tags--resulting in content not getting appropriately surfaced. That said, if we plan to revisit and adjust our tagging strategy post-1.0 or post-1.1, we can go out with the above list.

**Comment by mnorthuis** [comment]
General recommendations for you to review:

- Keep tags high level when possible, super granular tags may create an experience where content providers and users have too many choices and content will not be tagged consistently.
- Remove "VA" from account and profile tag since all articles in LC are about VA.
- "Contact information" tag label could be too vague and confused with "my contact information". This may be a place where you would want to use "VA"..."VA contact information"
- "Payments" tag having only direct deposit content could be misleading/misunderstood.  Potentially eliminate this tag since there is only 1 article, or make it more specific to direct deposit initially.

**Comment by jenniferlee-dsva** [comment]
I think the tags above are too granular as well, and also some of them are redundant of the category. creating a tag that's too close to a category will be too confusing because ppl can already find category articles by clicking on the category breadcrumb and/or clicking on the 'go to all articles in: Xcategoryname' link.

**Comment by jenniferlee-dsva** [comment]
I think tags should be between high level and granular. Our categories are super high level. so we want something a little more granular than, say, "Account and profile" or "Disability."  But agree, we should also not be too granular -- UNLESS we have a ton of user searches on something very very granular.

**Comment by jenniferlee-dsva** [comment]
- sign in
- ~other topics~  <-- this is totally redundant of the Other questions category label
- claims and appeals status < -- would add `status` here bc 'claims' is super broad and a lot of veterans think of almost anything wrt VA as a claim. If you don't like `status` please provide an alternative idea. 
- ~direct deposit~ <-- let's not add this until we know that we have either A. a ton of support content for DD or B. this is a frequent user searched term.  
- payments and debt  <-- this was a phrase that came out of the card sort, and we know from call centers that this is common issue. if you don't like this phrase, please provide an alternative, but it should be something that addresses the problem that we have payment and debt issues that don't all fit under direct deposit. (e.g.,, late payments, over payments (VA debt), incorrect benefit payments, wrong tuition payments, retroactive benefit payments)

**Comment by jenniferlee-dsva** [comment]
@mnorthuis 

Remove "VA" from account and profile tag since all articles in LC are about VA.
- I'm not sure about this and would like more thought on this from the team. LC will have content about ebenefits, MHV, DS Logon -- these are not per se VA although they are used for VA or with VA -- and at least some of these will continue to exist in parallel until they get fully consolidated and retired (e.g., eBenefits). 
- With so many VA brands, might it not be helpful to be clear?

**Comment by mnorthuis** [comment]
Open to other opinions for sure.  My thought, was that MHV, eBenefits are all still VA entities...everything you do there is for VA benefits.  They are not va.gov, but they are part of VA.  DS Logon is a service used by VA, but ultimately they are using in for VA purposes.  In the benefits content, the only time we us "VA" is where there needs to be clarity around what is VA and what is not VA - i.e. in health care we us "VA health care" so it is not confused with health care outside of VA.

**Comment by bethpottsVADEPO** [comment]
OK, based on this convo, I've revised the top of this ticket. @jenniferlee-dsva now I think we're ready for a call to finalize.

**Comment by jenniferlee-dsva** [comment]
Confirming post-call, so I don't forget:

1.0 tags:

- Sign in
- Claims and appeals status
- Payments and debt
- All Veterans
