### ISSUE TITLE
[Design] Claims: Overall disability rating

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#14400]
## Background
See [Design plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md)

## Tasks
- [ ] Visual design exploration for users with all information included
- [ ] Visual design exploration for empty states
- [ ] Work with copy to approve messaging
- [ ] High fidelity mockups
- [ ] Review with Samara/Matt
- [ ] Appropriate stakeholder reviews and approvals have been completed

**Comment by Samara-Strauss** [comment]
Closing, since we are no longer thinking of this as a separate section.
