### ISSUE TITLE
Synthesize Vet Center research (related to client experience)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14411]
**Due to the volume of information gathered during this research, synthesis will be broken into parts**

## Issue Description
Synthesize Vet Center research findings from sessions conducted in October 2020. 

**Goal of research**
The goal of this study is to understand a Vet Center client’s experience, impression and relationship with Vet Centers.

**Research questions**
How do Veterans and service members first learn about Vet Centers?
What is the client experience for different demographics?
What services, resources or activities are most valuable to Veterans, service members and their families?
How long do clients typically engage with Vet Centers and does their engagement or opinion of Vet Centers change over time?
What information do Veterans and service members want or expect to see on a website?

---
## Tasks
- [x] Synthesize findings of research **_as it relates to the client experience_**

## Acceptance Criteria
- [x] Research readout
- [x] Recommendations for next iteration of design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
[Veteran Client Interviews - Research Findings - PDF](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/veteran-interviews/Vet-Centers-Client-Research-Findings.pdf)

[Veteran Client Interviews - Research Findings - Text](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/veteran-interviews/research-findings.md)

[Opportunities/Recommendations Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1603629469594/94d7825c23f0eff800a5271bf396293535ef5de7?wid=0-1603629481483&outline=open)
