### ISSUE TITLE
Adjust PaymentsLists Component to Show Correct Alert

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#14426]
## Background
When a payment table in View Payments does not have payments to display we are showing the Alertbox with the blue line along the left side. Design has indicated that we are to remove this blue line and instead use the Alertbox style that shows when there are no payments for either table. The logic for the Alertbox showing should also be moved from the <Payments /> component up into the <PaymentsLists /> component so that the <Payments /> component is only rendering content.

## Tasks
- [x] Adjust the logic in <PaymentsLists /> component to account for no payments
- [x] Adjust the Alertbox shown when a table has no payments
- [x] Submit a PR for review

## Acceptance criteria
- [x] The logic that renders the no payments Alertbox for a table has been moved to the <PaymentsLIsts /> component
- [x] The Alertbox that is shown when a table has no payments does not have the blue line on the left-hand side
- [x] A PR has been submitted for review
