### ISSUE TITLE
Best Bets updates week of 10.05.20

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14441]
## Issue Description
We need to update some Best Bets.

### STEM

**Edith Nourse Rogers STEM Scholarship**
https://www.va.gov/education/other-va-education-benefits/stem-scholarship/
The Rogers STEM Scholarship allows some eligible Veterans and dependents in high-demand fields to extend their Post-9/11 GI Bill or Fry Scholarship benefits. Find out if you’re eligible for added benefits and how to apply.

Our SEO primary & secondary keywords for this page are: edith nourse rogers stem scholarship, gi bill stem extension

Variations on these (like "stem scholarship" or "rogers stem scholarship") are also relevant.

### Caregiver

full title (if it fits character limit):
The Program of Comprehensive Assistance for Family Caregivers

shortened title if not: 
Comprehensive Assistance for Family Caregivers

**The Program of Comprehensive Assistance for Family Caregivers**
https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/
This program offers support and services for family caregivers of eligible Veterans who were seriously injured in the line of duty during certain time periods and meet other eligibility requirements. Learn about eligibility and how to apply.

Some relevant SEO keywords include: caregiver program, caregiver pay, caregiver stipend, veteran caregiver

### Foreign programs

I came across this one, and the link seems to be throwing an error. 

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/c31ee9b1-0801-46b4-b095-fa8926e4aa18)

Let's update to:

**Foreign programs**
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/
If you plan to study at a foreign school, find out how you can use VA benefits to cover your tuition and fees.

### Coronavirus FAQs

Could we check on this one just to make sure it's set to a Best Bet for all relevant keywords?
https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

The other day, Lauren and I found that it wasn't coming up for coronavirus/covid. It looks like it is now, so maybe it was just a glitch, but want to check in case. Also would be great to update the description to the below.

**Coronavirus FAQs: What Veterans need to know**
https://www.va.gov/coronavirus-veteran-frequently-asked-questions/
Get the latest information about how COVID-19 may impact your VA health care and other VA benefits and services.

---
## Tasks
- [ ] Update Best Bets for the pages above
- [ ] Validate on live site

## Acceptance Criteria
- [ ] Updated Best Bets live on site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
@DanielleThierryUSDSVA I believe I notched all of the changes.   Here you go (and please feel free to check on live site if you want to validate before closing ticket).

<img width="703" alt="Screen Shot 2020-10-06 at 9 40 20 AM" src="https://user-images.githubusercontent.com/63107147/95209510-6ed8a200-07b8-11eb-948c-583e7ddf4925.png">

<img width="797" alt="Screen Shot 2020-10-06 at 9 40 06 AM" src="https://user-images.githubusercontent.com/63107147/95209526-7304bf80-07b8-11eb-954e-df0530fe81f0.png">

<img width="763" alt="Screen Shot 2020-10-06 at 9 38 20 AM" src="https://user-images.githubusercontent.com/63107147/95209544-7730dd00-07b8-11eb-88c3-93f369f0146d.png">

<img width="554" alt="Screen Shot 2020-10-06 at 9 34 03 AM" src="https://user-images.githubusercontent.com/63107147/95209552-7ac46400-07b8-11eb-9193-7d312a53d2e4.png">


<img width="769" alt="Screen Shot 2020-10-06 at 9 33 00 AM" src="https://user-images.githubusercontent.com/63107147/95209563-7dbf5480-07b8-11eb-9fe5-602f13ce462c.png">

**Comment by DanielleThierryUSDSVA** [comment]
Everything looks perfect, @johnhashva. Thanks so much!

FYSA @brianalloyd @MickinSahni Closing this ticket.
