### ISSUE TITLE
Adjustment in data layer for FL map events

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14453]
## Issue Description
[Feedback from QA of data layer implementation ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10987#issuecomment-702454252)

We need to make a small adjustment to allow differentiation of events

---
## Tasks
- [ ] Clear the fl-map-miles-moved dataLayer variable after it is set `window.dataLayer.push({'fl-map-miles-moved': undefined});`

## Acceptance Criteria
- [ ] Analytics can differentiate between the regular search and the map move from the dataLayer alone

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
validated by analytics folks already and merged
