### ISSUE TITLE
[FE]/[BE] Create Pact Tests

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#14464]
## User Story
**In order** to experience a bug-free va.gov experience with high availability and as little downtime as possible
**As a** Veteran
**I wan**t the systems behind the website to communicate with little to no errors by implementing a contract with each other using the Pact technology

## Description
In order to better communicate requirement and awareness to when features changes, platform team is making all teams start doing Pact tests. These tests help solidify the contract between the front and back end. 

## Tasks
- [ ] Create Pact test for getting Appointments
- [ ] Create Pact test for posting Questions Responses

## Acceptance criteria
- [ ] Get sign off from engineering team 
- [ ] have tests merged in master via a successful PR.

**Comment by julieadair1** [comment]
@dillo - is this something we still need to plan on doing?
cc: @jparker0425
