### ISSUE TITLE
Product Roadmap - Monitoring Solution (DataDog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14465]
## Issue Description
_Put together a rough roadmap to inform VSP / VFS teams of how and when they may begin to use Datadog_

Current sequence of teams that will gain access to this tool: 
1. Ops teams
2. BE teams
3. VFS teams

---
## Tasks
- [X] Document the timing and phases of implementation for Datadog
- [X] Provide useful links and other relevant information that will benefit teams in understanding capabilities and usage of the tool

## Acceptance Criteria
- [x] Teams are informed about Datadog in advance of the launch
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Notes for high-level roadmap: 
- install on dev
- be tools access
- customization of fwdproxy - main gateway for all respective downstream apps
- be tools SLO/SLA reports
- onboard platform engineering (Ops, BE Tools, FE Tools) 
- onboard other VSP teams (...)
- onboard VFS teams

**Comment by jhouse-solvd** [comment]
This is defunct. We are on hold for licenses and will resume this mid-2021. Please see parent epic for more up-to-date information.
