### ISSUE TITLE
Usability Testing Prep - Healthcare [Questionnaires - Proof of Concept ]

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#14473]
## Steps to complete Usability Testing Prep: 
- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt 
- [x] Andrea to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to product outline [Questionnaires](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- Link to Initiative [Visit Intro- Proof of Concept](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- Link to Feature [Questionnaire Manager](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)
- Link to Feature [Demographics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/demographics.md)
- Link to Feature [This Visit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)
- Link to or attach prototype or mockups
 Create complete [Proof of Concept prototype in Mobile](https://preview.uxpin.com/a15205c1bedcdfc8fe46fed26c22fa731cab8ae0cvhidm)
 Create complete [Proof of Concept prototype in Desktop](https://preview.uxpin.com/e9e0dc597bb076e74db05f77d35306496a89fca2cvhidm)
- Link to [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/mvp-usability/research-plan.md) and [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/mvp-usability/conversation-guide.md)
- Link to regression test plan **- N/A**
- Link to test cases/test plan in TestRail **- N/A**

## Meeting attendees from **Healthcare Questionnaire**
- Product Manager (required): **Amanda Buckley**
- Design/Researcher (required): **Kristen McConnell**
- DEPO product lead (required): **Lacey Higley & Ming Ligh**

## Scheduling
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite: Friday 9th 2PM

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by pjhill** [comment]
I see that the QA artifacts have been omitted for this collaboration cycle meeting. After reading through the product outline, I think I have some guesses as to why they are being omitted here. Would you please provide a formal explanation for the exclusion of QA artifacts?

**Comment by abuckley3385** [comment]
@pjhill - we have not started any of our test cases/test plan in TestRail so what artifacts would QA be looking for for a Usability Test of a prototype?

**Comment by pjhill** [comment]
> @pjhill - we have not started any of our test cases/test plan in TestRail so what artifacts would QA be looking for for a Usability Test of a prototype?

Indeed, it is very early in the process to be considering quality assurance. For the Usability Testing Prep meeting we ask teams to consider relevant test scenarios and begin creating drafts of test cases and a test plan.  Obviously, these cannot be finalized at this point.

Additionally, we ask that teams consider the product that they are replacing or enhancing in order to ensure that there are no unintentional regressions in the functionality offered by the replaced or existing product. Those regression considerations should manifest in a regression test plan draft.

Additional information about each QA artifact and which collaboration cycle point it is relevant for is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md).

**Comment by kristenmcconnell** [comment]
@abuckley3385 I completed the feedback survey. If you haven't, then can you check the last checkbox above when you have?

**Comment by mnorthuis** [comment]
I am sooooo sorry, I just realized that I never posted my feedback from the meeting last week!

I didn't have any specific feedback for you, although would love to land on a breadcrumb for the purposes of the research.    I'm thinking that for this initial round we could do something like this:
 Home > Health care > Schedule and view VA appointments > VA online scheduling  > Questions for your upcoming appointment

I believe this matches the H1 feedback that @peggygannon gave, but we will need to continue to work on this as we define out the rest of the experience. 

Coming out of research, I would love to 
- hear where users would look to find this if they were to go to the site to review what they submitted or to see if there are other forms to fill out
- set up time for a discussion to look at the full flow/experience that includes the pages leading into these forms - start getting the full experience structured

**Comment by kristenmcconnell** [comment]
@mnorthuis Thank you. We already started testing and are gathering feedback on where Veterans think this should live. I absolutely plan to reach out to you following testing. I have story #14848 already created to work on this.

**Comment by mnorthuis** [comment]
Thank you @kristenmcconnell!  Would you be willing to go ahead and create the[ IA issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=product+support%2C+content-ia-team%2C+collaboration-cycle&template=ia-request.md&title=IA+Request+%5BFeature-Name%5D)?  I can use that to track any work/conversations we have.
