### ISSUE TITLE
Change instances of "/person-mdm-cuf-person-hub/sba/health" to "/contact-information-hub/sba/health" in INT, QA, PRD environments

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14480]
## Background

When discussing #14188 with the VA Profile team, they brought up another request to update the following endpoint:

- **Old endpoint (currently in use)**: /person-mdm-cuf-person-hub/sba/health
- **New endpoint (to replace the old endpoint)**: /contact-information-hub/sba/health
- **Environments (env)**: INT, QA, PPD, PRD

Why this matters: Updating this endpoint will help resolve some instances of multiple identity records for veterans that are a result of organizational mix ups. When people are detected to have multiple IDs, they are not able to be validated in MVI and therefore can not use most of the VA.gov features that require identity proofing. Updating this endpoint would resolve this in some instances, allowing an additional 9,000 veterans to update their information online.
 
## Tasks

- [ ] Migrate to /contact-information-hub/sba/health URL 
- [ ]  Test in lower environments and report issues, if any, to VA Profile OM Group:  VAProfileOM@va.gov 
- [ ] Make URL change in PROD if no issues are encountered in the lowers
- [ ]  Inform Samara/VA Profile when this is complete

**Comment by Samara-Strauss** [comment]
@tskinn could your team help us with this issue? It's similar to #14188.

**Comment by tskinn** [comment]
Hey! I'm so sorry this got lost! In the fwdproxy we use that path as a health check endpoint. It kind of sounds like this is something we need to change in vets-api too right?
