### ISSUE TITLE
Improve or remove map view of facility locator on mobile

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/va.gov-team#14484]
## Issue Description
- In our mobile month study, we found that veterans were not interested in using the map view of facility locator. They preferred the list view. We recommend considering improving or removing the map view of the facility locator on mobile. 
---
## Tasks
- [ ] Run research to determine how to remove or improve the map view on mobile
- [ ] Design and implement

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by mmiddaugh** [comment]
Duplicated in https://github.com/department-of-veterans-affairs/va.gov-team/issues/5761
