### ISSUE TITLE
[VAMC-Scaffolds] Create or Clone all required pages for VA Central Iowa health care in VISN 23 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#14499]
## User Story 
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required VAMC-upgraded va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Clonable Website](prod.cms.va.gov)

## Tasks
_Creation of the following Drupal types/menus and pages_
* All pages are cloned or created, the System name, Related office or Health Care system, Owner, Meta title, Meta Description, and Menu items are updated.

**1st Step: Go into Manage, Content, and click on Menus**
_find VA [SYSTEM NAME] (listed alphabetically) that you are cloning in the menu list and select "Edit"
_using the blue button "+add link" add the following <nolink> menu link titles:
- [x] SERVICES AND LOCATIONS (Link: <nolink> / uncheck "enabled checkbox")
- [x] NEWS AND EVENTS (Link: <nolink> / uncheck "enabled checkbox")
- [x] ABOUT VA "Short System Name" (e.g.:ALTOONA) (Link: <nolink> / uncheck "enabled checkbox")

** Items below do NOT need menu items associated to them**
- [x]  Make an appointment
- [x]  Register for care
- [x]  Billing and insurance
- [x]  Dav-vans
- [x]  Medical records
- [x]  Pharmacy
- [x]  Campus map
- [x]  Chaplain services
** Items below do need menu items associated to them**
* Add to Menu under Health Services
- [x]  Caregiver support
- [x]  Homeless Veteran care
- [x]  LGBT Veteran care
- [x]  Mental health care
- [x]  Minority Veteran care
- [x]  Patient advocates
- [x]  Returning service member care
- [x]  Suicide prevention
- [x]  Women Veteran care

**Items below DO require menu items associated to them**
- [x] Go to System Page (Already Created) for VA ********* health care
      *In System page, add the following facility IDs in locations:
- [x] 636A6	Des Moines VA Medical Center
- [x] 636GC	Mason City VA Clinic
- [x] 636GD	Marshalltown VA Clinic
- [x] 636GK	Fort Dodge VA Clinic
- [x] 636GM	Carroll VA Clinic
- [x] 636GR	Knoxville VA Clinic

**NEW SECTION:(BEST BET instructions)**
**(Clone from [System Name] VA health care)**
- [x]  About us Page
    * Add to Menu under About VA
- [x]  Work with Us Page 
    * Add to Menu under About VA 
- [x]  Jobs and Careers 
    * Add to Menu under Work with Us
**(Clone from VA Sierra Nevada health care)**
- [x]  History 
    * Add to Menu under About us 
- [x]  Mission-Vision 
    *  Add to Menu under About us 
- [x]  Internship and Fellowship 
    * Add to Menu under Work with Us
- [x]  Volunteer and Donate 
    * Add to Menu under Work with Us

**NEW SECION - Listing pages**
**(Clone from VA Sierra Nevada health care)**
- [x] Event Listing Page
    * Add to Menu under NEWS AND EVENTS
- [x] News Releases Listing Page 
    * Add to Menu under NEWS AND EVENTS
- [x] Stories Listing Page 
    * Add to Menu under NEWS AND EVENTS

**Next Section**
**(Clone from [System Name] VA health care)**
- [x]  Health Services Listing Page
    * Add to Menu just below System page
- [x]  Location Listing Page 
    * Add to Menu Just Below Health Services
**Next Section:**
**(Clone from [System Name] VA health care )**
- [x] Performance Page
    * Add to Menu under About us 
- [x]  Leadership Listing Page
    *  Add to Menu under About us 
**Next Section:**
**(Clone from [System Name] VA health care)**
- [x]  Policies Page
    * Add to Menu under About VA 
- [x]  Contact us 
    * Add to Menu under About VA 

## Acceptance Criteria
- [x]  Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [x]  Validate that all menu pages show up in Menu and are visible in the correct order on the menu
- [x]  Validate that pages are ready to take data load information
- [x]  All system pages listed above have been created

**Comment by ltrombley** [comment]
Task complete.
