### ISSUE TITLE
[VAMC-Scaffolds] Create or Clone all required pages for VA St Clound health care in VISN 23 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#14505]
## User Story 
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required VAMC-upgraded va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Clonable Website](prod.cms.va.gov)

## Tasks
_Creation of the following Drupal types/menus and pages_
* All pages are cloned or created, the System name, Related office or Health Care system, Owner, Meta title, Meta Description, and Menu items are updated.

**1st Step: Go into Manage, Content, and click on Menus**
_find VA [SYSTEM NAME] (listed alphabetically) that you are cloning in the menu list and select "Edit"
_using the blue button "+add link" add the following <nolink> menu link titles:
- [x] SERVICES AND LOCATIONS (Link: <nolink> / uncheck "enabled checkbox")
- [x] NEWS AND EVENTS (Link: <nolink> / uncheck "enabled checkbox")
- [x] ABOUT VA "Short System Name" (e.g.:ALTOONA) (Link: <nolink> / uncheck "enabled checkbox")

** Items below do NOT need menu items associated to them**
- [x]  Make an appointment
- [x]  Register for care
- [x]  Billing and insurance
- [x]  Dav-vans
- [x]  Medical records
- [x]  Pharmacy
- [x]  Campus map
- [x]  Chaplain services
** Items below do need menu items associated to them**
- [x]  Caregiver support
- [x]  Homeless Veteran care
- [x]  LGBT Veteran care
- [x]  Mental health care
- [x]  Minority Veteran care
- [x]  Patient advocates
- [x]  Returning service member care
- [x]  Suicide prevention
- [x]  Women Veteran care

**Items below DO require menu items associated to them**
- [x] Go to System Page (Already Created) for VA ********* health care
      *In System page, add the following facility IDs in locations:
- [x] 656	St. Cloud VA Medical Center
- [x] 656GA	Brainerd VA Clinic
- [x] 656GB	Montevideo VA Clinic
- [x] 656GC	Max J. Beilke VA Outpatient Clinic

**NEW SECTION:(BEST BET instructions)**
- [x]  About us Page (Clone from [System Name] VA health care)
    * Add to Menu under About VA [System name]
- [x]  History (Clone from VA Sierra Nevada health care)
    * Add to Menu under About us 
- [x]  Mission-Vision (Clone from VA Sierra Nevada health care)
    *  Add to Menu under About us 
- [x]  Work with Us Page (Clone from [System Name] VA health care)
    * Add to Menu under About VA [System name]
- [x]  Jobs and Careers (Clone from [System Name] VA health care)
    * Add to Menu under Work with Us
- [x]  Internship and Fellowship (Clone from VA Sierra Nevada health care)
    * Add to Menu under Work with Us
- [x]  Volunteer and Donate (Clone from VA Sierra Nevada health care)
    * Add to Menu under Work with Us

**NEW SECION - Listing pages**
- [x] Event Listing Page (Clone from VA Sierra Nevada health care)
    * Add to Menu under NEWS AND EVENTS
- [x] News Releases Listing Page (Clone from VA Sierra Nevada health care)
    * Add to Menu under NEWS AND EVENTS
- [x] Stories Listing Page (Clone from VA Sierra Nevada health care)
    * Add to Menu under NEWS AND EVENTS

**Next Section**
- [x]  Health Services Listing Page (Clone from [System Name] VA health care)
    * Add to Menu just below System page
- [x]  Location Listing Page (Clone from [System Name] VA health care)
    * Add to Menu Just Below Health Services
**Next Section:**
- [x] Performance Page (Clone from [System Name] VA health care )
    * Add to Menu under About us 
- [x]  Leadership Listing Page (Clone from [System Name] VA health care)
    *  Add to Menu under About us 
**Next Section:**
- [x]  Policies Page (Clone from [System Name] VA health care)
    * Add to Menu under About VA [System Name]
- [x]  Contact us (Clone from [System Name] VA health care)
    * Add to Menu under About VA [System Name]

## Acceptance Criteria
- [x]  Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [x]  Validate that all menu pages show up in Menu and are visible in the correct order on the menu
- [x]  Validate that pages are ready to take data load information
- [x]  All system pages listed above have been created

**Comment by ltrombley** [comment]
Task #14505 - VA St Cloud Health Care System is complete.
