### ISSUE TITLE
[AUTOMATION] Creation of new .csv file to upload VISN-21 System and Facility Health Services to CMS [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#14512]
## User Story or Problem Statement
As a Data Tech, I need an optimized way to load .csv of System and facility health services, so I can load existing list to system and facility pages for inspection and confirmation of PAO web maintainers.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase pages/nodes completed in a quarter_

## Resources - Tools - Documentation
[Review System and facility spreadsheet](https://dvagov.sharepoint.com/:f:/s/VHADigitalMedia/vamc-upgrade-project/Ej33rnb0EAZDkvT2A-696qUBx40SHv8dOusH-nP810orTg?e=3JLBLQ)

## Tasks
_Creation of the following .csv files
- [x] System Health services unique to the each System in VISN-21
* System Health service includes: (HS= to cell with Health services, SN = System Name, FI = Facility ID, FN=Facility name)
Id (Health services + "-" + System Name) USE "=CONCAT(HS," - ",SN)
Health Services (Health Services +"at" + System Name)  "=CONCAT(HS," at ",SN)
Full Upload (blank)
Health System
Owner
- [x] Listing of Facility Health services unique to each Facility
* Facility Health Service includes:
ID (Facility ID + "-" + Health Services)  USE "=CONCAT("vha_",FI, " - ", HS)
Facility Name
VAMC System Health Service (Health Services +"at" + Facility name)  "=CONCAT(HS," at ",FN)
Facility description of services (blank)
Owner

## Acceptance Criteria
_Validate outcome of pushing content to existing page_
- [ ] Completed System Health service for all Systems in VISN
* System will have unique Id equal to Health service name + "-"  system
- [ ] Complete Facility Health Services for all Facilities in VISN
* Facility health service will have unique ID equal to facility ID + "at" Health service title
- [ ] System is tested in .csv and Excel
- [ ] Facility is tested in .csv and Excel

**Comment by lealester** [comment]
moved into validate 10/21/2020 (10:03 am ET)
