### ISSUE TITLE
Walk through step-by-step LC articles to confirm accuracy

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14521]
## Issue Description
The content team has created step-by-step articles for the learning center with images guiding users through a process. Before publishing we need to confirm that all the steps are correct with nothing missing or out of order, and the screen shots show all the information needed. 

A content team member should walk through each of these articles, following the steps and looking at the screen shots, to confirm accuracy.

List of step-by-step articles:
- [x] Steps to changing your VA.gov profile address step-by-step preview-prod.vfs.va.gov/preview?nodeId=8417
- [x] Steps to changing your VA education direct deposit information preview-prod.vfs.va.gov/preview?nodeId=8474
- [x] Steps to changing your VA disability or pension direct deposit info preview-prod.vfs.va.gov/preview?nodeId=8434
- [ ] Premium DS Logon step-by-step preview-prod.vfs.va.gov/preview?nodeId=8503
- [x] Steps to checking your VA claim or appeal status onlinehttp://preview-prod.vfs.va.gov/preview?nodeId=8520
## Tasks
- [x] Follow directions in each step of article 
- [ ] Flag any issues or inaccuracies in this ticket and open new ticket to track work of individual articles

## Acceptance Criteria
- [x] Step-by-step articles have been reviewed for accuracy

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This ticket can be closed. The DS Logon step by step was already written so OK not to confirm steps.
