### ISSUE TITLE
Split 686 Submission for 674 Endpoint

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14529]
## Background
In order to ensure the 674 submission gets to the right people for approval, we need to split the submission and label it accordingly based on what was selected.

## Tasks
- [x] Create a 674-specific job
- [x] Do a check to see if a 674 workflow was selected, and if found, kick off that other job that applies the correct proctype cod, EP code, BenefitClaimType`*` code to the split submission.
- [x] Move code around the service/lib file
- [x] Pretty comprehensive redo of lib tests

`*` - check

## Acceptance Criteria
-  [x] A large(r) PR has been created that is now ready to be massaged per the guidelines of platform for further merging

**Comment by digitaldrk** [comment]
PR submitted. LOC isn't too bad 😎
https://github.com/department-of-veterans-affairs/vets-api/pull/5119
