### ISSUE TITLE
Need persisted bot token for CMS bot

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14522]
## Issue Description
An attempted updated build rollout for Jenkins did not work out last night. We then reverted to the old build for Jenkins. Everything seems to have came back the way we had it, except a bot token for the CMS bot to be able to kick off builds. We should try to find a way to persist the token so new deploys of Jenkins do not break this functionality every time it is deployed.

---
## Tasks
- [ ] Research on how to persist the token
- [ ] Persist token
## Acceptance Criteria
- [ ] New deploys of Jenkins no longer break the CMS bot being able to kick off builds
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
See here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/24039

Closing.
