### ISSUE TITLE
AE: Sprint 32

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#14520]
# Priorities
1. Remaining Sprint 31 tickets, bug fixes and enhancements
2. LIH Phase 2 Design: Healthcare and Claims
3. VA Profile bogus addresses issue
4. 10/24 Spokane Cerner Update
5. Direct Deposit for Edu
6. Pact Work
7. Preferred Facility Discovery
8. VA Profile Remove instances of Vet360 (DevOps issue)

### PM
 Continue to maintain the logged-in homepage project epic
- [x] [PM] Create needed LIH design tickets for healthcare and claims sections #14933
- [x] Create list of staging users we need for logged-in homepage QA (#8385)

### Design
- Will be focused on MyVA Dashboard design

### Build
- [x] Delete confirmation alert should scroll into view #12013
- [x] Remove Profile 2.0 feature flag mentions #14289
- [x]  [FE] Built 'Can't connect to MPI' error alert #13996
- [x] [FE] Remove redundant Profile 1 logic after Profile 2.0 is launched #14218
- [x] Remove Profile 2.0 feature flag mentions #14289
- [x] [FE] Don't show profile error when the user is a non-vet and the call to /service_history fails #14012

#### Healthcare Design
- [x] [Design] Healthcare: Design Healthcare name tag section #13918
- [x] [Design] Healthcare: Refill and track your prescriptions #13919
- [x] [Design] Healthcare: Send a secure message to your health care team #13920
- [x] Schedule and view your appointments #13921
- [x] [Design] Healthcare: View your lab and test results #13922
- [x] [Design] Healthcare: Apply now for VA healthcare #13923
- [x] [Design] Healthcare: Healthcare application status #13923

### Dev 
- [x] **TBD**

## Direct deposit for Edu
- [ ] [BE] Create BGS CH33 DDEFT Service integration #13286
- [x] Project Kickoff [Direct Deposit for Education Benefits] #14167
- [x] Refine and Augment Direct Deposit-EDU Mockups #14557
- [x] Design-intent VSP checkpoint #14824

## MyVA Cerner Go-live updates
- [x] [FE] My VA: Cerner go-live updates for Spokane facilities on 10/24 #13832
- [x] [FE] Coordinate with public websites to determine how we will determine Cerner facility capabilities #14533

## Pact work 
- [x] VSA Auth Experience - Pact setup #13336
- [x] [BE] Setup Pact test #14234
- [x] [FE] Write Pact test #14233 
reference: #13790

## VA Profile: Issue with bogus addresses being saved
- [x] Critical: Investigate VA Profile issue to determine whether veteran account has been hacked #175
- [x] Add address form field validation to prevent users from entering web URLs #14471

## VA Profile: Remove instances of "Vet360"
Note: This is a DevOps tickets, and I am figuring out who can work on it. However, keeping it here since Lihan may be helping in come capacity and since I have to make sure it gets done.

- [x] [BE/DevOps] Change instances of "https://env.vet360.va.gov/" to "https://env.vaprofile.va.gov/" in INT, QA, PPD, PRD environments #14188

## Preferred Facility discovery
Samara to continue trying to get additional information to determine next steps

## Unplanned/QA/508/Bug fixes

- [x] Discuss new project plan now that we've pivoted from LIH redesign --> My VA redesign #14608
- [x] Create Cypress tests in lieu of Nightwatch for profile 2 #14851
