### ISSUE TITLE
Adjust the Wizard on CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14539]
`Hold on this; this looks like a component in the library issue`

## Background
On the wizard for CH36 there is a space between the first line of the first question and the top of the wizard. This is caused by the styles that come from the platform for the fieldset group inside the Wizard component. We need to add custom styles to adjust this so that there is no space at the top.

## Considerations
- Given that the wizard was created some time ago, we need to verify the content is updated as well with the [prototype](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526675/simulate/sitemap).
- A place to start might be [Errorable Radio Buttons](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/errorableradiobuttons)
  - Share this solution with John Hashimoto and see if he wants to take it upstream to platform to address it for everyone

<details> 

<summary>From Jennifer</summary>

![Screen-Shot-2020-10-06-at-10 22 03-AM](https://user-images.githubusercontent.com/53826255/100801520-14457600-33f6-11eb-8964-89b65051b6fa.png)

![Screen-Shot-2020-10-06-at-10 22 08-AM](https://user-images.githubusercontent.com/53826255/100801613-3a6b1600-33f6-11eb-8452-0af86debd632.png)

![Screen-Shot-2020-10-06-at-10 22 17-AM](https://user-images.githubusercontent.com/53826255/100801737-64243d00-33f6-11eb-85d1-70ea31b040ee.png)

</details>

## Tasks
- [ ] Add a custom style declaration that removes the gap near the top of the wizard
- [ ] Submit a PR for review

## Acceptance Criteria
- [ ] There is no gap near the top of the wizard above the first question
- [ ] A PR has been submitted for review
