### ISSUE TITLE
Move `clear-SIP` to Post Successful Submission

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14538]
## Background
It might be best if the clear function only clears _after_ a successful submission so the Veteran doesn't lose their entries.

## Considerations
- This ticket refers to the 686 but might be useful for other forms
- We fire off 3 jobs: 686. 674, and the pdf so where does SIP need to get cleared
- Idea:
1. in job, copy in progress data
2. clear in progress
2. If we hit an exception, either create a new in progress record and add the copied data or update the cleared in progress with the data we copied

## Tasks
- [ ] Establish where the form should have its SIP data cleared
- [ ] Move the clear process to that point

## Acceptance Criteria
- [ ] SIP data is cleared at an appropriate point that allows the Veteran the most flexibility with getting back into a more completed form in the event of a mishap.
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
After some investigation, we need more information about when jobs will be finished in order to deem it safe to remove the SIP data.  Once we have a stronger definition as to submission timings in real world examples we can revisit this.

Moving it back into the Ready column for now.

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5901
