### ISSUE TITLE
Draft View Payment History KPI dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#14537]
## Issue Description
Draft a Product KPI Dashboard for View Payment History, under eBenefits.
[KPIs link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-payment-history#kpis-and-okrs)

---
## Tasks
- [ ] Groom [metrics](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14181) for feasibility & ETL approach
- [ ] Draft dashboard with appropriate charts in Domo
- [ ] Visualize charts to fit with appropriate success measurements
- [ ] Review dashboard for data quality, content, & design

## Acceptance Criteria
- [ ] eBenefits has an automated way to track their success measurements

**Comment by jonwehausen** [comment]
@JasonTheBearded @bsmartin-ep @bmcgrady-ep 

### Context
- View payment history is launching on January 4
- Took a stab at creating a view within staging that joins `view-payment-history-successful` events with `/va-payment-history/payments` pageviews by session ID and calculates the time to complete for each session. This can be found within the staging dataset (`17688421`) with table name `TESTVIEW_viewPaymentHistory_timeToComplete`
- From there, I built a query that groups by date to average each time diff to get the average per day. You can find that within the [DOMO dataset here](https://va-gov.domo.com/datasources/e20fc8f5-9546-4d69-a44b-feb4f38681e9/details/settings). 
- There are other examples of time to complete done all in one query between two events, such as the [dataset here ](https://va-gov.domo.com/datasources/5d56f3db-f5d0-4bea-a931-1fe21340eae7/details/settings)...I had difficulty getting this framework to work between pageviews and events but feel free to restructure if you feel this is a better approach. 
- Created a visual for this [here](https://va-gov.domo.com/kpis/details/126550841) and added to our ebenefits KPI dashboard [here](https://va-gov.domo.com/page/1726972169)

### Next Steps
- [ ] I QAed the average for one day of values (date of `'20201207'`) and was accurate -- that said would be great to have another set of eyes 
- [ ] Setup a BigQuery dataset to meet KPI#1 - Understanding % of traffic for ebenefits compared to VA.gov

**Comment by JasonTheBearded** [comment]
QA'd results and they looked good. Worked with @jonwehausen to refine the query. Created Prod dataset in DOMO with name, 'BQ - View Payment Completion Time'. 

Will start work on step 3.

**Comment by JasonTheBearded** [comment]
@jonwehausen Dataset set up for KPI#1, https://va-gov.domo.com/datasources/9d6cf509-8de8-4030-b8b7-4f488ed634da/details/overview
let me know if that meets the needs

**Comment by jonwehausen** [comment]
@JasonTheBearded This looks great! Pageviews + Users were compared against GA for January 18 (screenshot below) 

![image](https://user-images.githubusercontent.com/48527022/105262598-2de57d00-5b5e-11eb-9b37-d76520791ef4.png)

I _think_ in this case we can ignore `postLogin=true` as you currently have

**Comment by jonwehausen** [comment]
@JasonTheBearded Correct me if I'm wrong but this guy should be ready for final review?

**Comment by JasonTheBearded** [comment]
@jonwehausen Is the dataset I provided being referenced on your dashboard? I haven't made any changes to it since your last comment so feel free to start working off of it.
