### ISSUE TITLE
Adjust heading tags on View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#14546]
## Background
On View Payments when payment data is loaded there are two H3s that show up, this makes the heading tags on the page skip from H1 to H3. We need to adjust these heading tags so that they are H2s but keep the same styling they have now.

```HTML
<h3 id="paymentsRecievedHeader" class="vads-u-font-size--xl">Payments you received</h3>
```
```HTML
<h3 id="paymentsReturnedHeader" class="vads-u-font-size--xl">Payments returned</h3>
```
The h3 used above the payments tables when payments are present need to be changed to an h2 so that the Heading levels on the page do not skip from h3 to h1 

## Tasks
- [ ] Adjust the heading tags to H2s
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The heading tags now increment by one on View Payments
- [ ] A PR has been submitted for review

**Comment by micahchiang** [comment]
I'm not sure if this ticket is necessary. When the tables load and the `H3` tags are rendered, there is already an `H2` that comes before them in the DOM tree, as seen in the screenshot. 

<img width="1317" alt="Screen Shot 2020-10-12 at 2 13 58 PM" src="https://user-images.githubusercontent.com/15097156/95778186-95557c00-0c95-11eb-8cb9-b60456bed411.png">

**Comment by jason-gcio** [comment]
Code has an H2 so lets not fret.
