### ISSUE TITLE
Loki - Get everything that is currently logging in CloudWatch logging in DEV

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14549]
## Issue Description
Ensure that any current logs for DEV currently being sent to CloudWatch, as defined by Log Groups `dsva-vagov-dev` are being sent to a DEV Loki environment ([link](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logs:prefix=dsva-vagov-dev)).  This ensures parity with existing logging in place.

---
## Tasks
- [X] _Anything required to reach parity with CloudWatch (defined in separate tickets/stories); this is essentially a goal/end-state_

## Acceptance Criteria
- [X] _All logs from `dsva-vagov-dev`Log Groups defined CloudWatch are being shipped to Loki DEV_ [proof](http://grafana.vfs.va.gov/explore?orgId=1)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pnwstevan** [comment]
This is complete except for a few gaps:

- network-status-exporter - not included for now. It is a Docker container and only used by fwdproxy, and the current configuration has this defined as a role at build time so we can't abstract out separate container configurations per environment.
- content_preview - similar to above, runs as a Docker container configured as a build role so unable to configure separately per environment.  Regardless, not configured to log in dev anyways so there aren't any logs to ship.
- AWS Service logs - the only one in DEV is the VPC flow logs; per Slack discussion with @dginther ([thread](https://dsva.slack.com/archives/CTYQL39FE/p1602020093288500)), punting on this for now.



As discussed with @dginther in Slack (thread here
