### ISSUE TITLE
As a Sentry user I should see the request user IP in Sentry issue

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14542]
## Issue Description

The nginx proxy_pass configuration is not passing through the actual client IP because the requests are viewed by Sentry
as coming from the local host.

See [this](https://dsva.slack.com/archives/CBU0KDSB1/p1601930770132700) thread for originating comment. 

[This](https://github.com/getsentry/onpremise/issues/554) Sentry issue has more details.

---
## Tasks
- [ ] Update [this](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry10/nginx.conf) config to forward the client IP with `$proxy_add_x_forwarded_for` instead of `$remote_addr`
- [ ] Redeploy Sentry 10 to ensure changes are caught in the template

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
