### ISSUE TITLE
Unit Test Redux for View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#14543]
# Background
In order to make sure that Redux in View Payment behaves as expected we need to write unit tests for it. We need to Unit test both the action and reducer file.

## Tasks
- [ ] Set up test file for Redux actions
- [ ] write unit tests for Redux actions
- [ ] Set up test file for Redux reducers
- [ ] write unit tests for Redux reducers
- [ ] submit a PR for review

## Acceptance criteria
- [ ] Both the Redux actions and reducers are unit tested
- [ ] A PR has been submitted for review
