### ISSUE TITLE
IRIS Q&As -- Careers and Employment

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14548]
## Issue Description
Resources and support articles need to be developed based on Careers and Employment IRIS faqs. 

**Tasks**

- [ ] SC to identify IRIS faqs to migrate (Laura)

- [ ] SC to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

- [ ] SC to develop draft copy and review against content checklist  (Laura)

- [ ] DEPO to review (Beth)

- [ ] SC to copyedit draft (Randi)

- [ ] DEPO to get SME approval (Beth)

- [ ] SC to build Drupal page(s) (Selina, Randi or Laura)

- [ ] SC to proof Drupal page(s) (Randi)

- [ ] DEPO to approve Drupal page(s) (Beth)

- [ ] SC to publish pages (Randi)

- [ ] DEPO to alert SMEs that pages are live (Beth)

- [ ] SC to update R&S status document (Laura)

**Acceptance Criteria**

- [ ] Page live

**Up-to-date content here**

Please post most up-to-date content (whether copy deck, Drupal link, or live url) here rather than in comments below.

**Comment by lwalsh617** [comment]
This is on hold until 2021 per @bethpottsVADEPO due to the need to identify the SME responsible for this content and to find out what website to send users to for federal employment info.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -

There are 5 faqs updated in 2015 or later. 2 of those cover content that is on our Tier 1 VR&E pages.

I looked at those tier 1 pages to see if there's content that is actually tier 2 and therefore should be moved to R&S. The only content that's not directly benefits-related is the "Get more info" section, which is repeated on each of the program tracks pages. It's really a list of links that are helpful to have, so I wouldn't move it to R&S.

That leaves 2 2015-or-later IRIS faqs. Here are the page views:

1120:  347 page views

1058: 27 page views

1489: 69 page views

The content in these 3 faqs is covered on https://www.vaforvets.va.gov/ and  <https://www.va.gov/jobs/> which we do link to from our tier 1 pages.

Next, I searched the page views document for any faqs updated before 2015 with high page views, but didn't find any.

All that said, I think that due to the 347 page views for faq 1120 ("Where do I find information about jobs and employment opportunities?) and the fact that there isn't any other careers and employment content that makes sense to include in R&S, we should keep the article already written and attached here. If you agree, I'll do SEO research and edit headers as needed, then build it in Drupal. It's written as a multiple faq. If you'd rather it be an About article, I can do it that way. Just let me know how to proceed. Thanks!
[rs-careersemployment-v3-111620.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7468199/rs-careersemployment-v3-111620.docx)
