### ISSUE TITLE
Content review for IRIS Q&As Batch 2, life insurance

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14544]
## Issue Description
First-draft copy of batch 2 Life Insurance Q&As needs to be reviewed by DEPO before building in Drupal.

Copy deck to review: [https://app.zenhub.com/files/133843125/0a22801f-a6a3-4c3a-b30b-313e73854cce/download](https://app.zenhub.com/files/133843125/0a22801f-a6a3-4c3a-b30b-313e73854cce/download)

## Tasks
- [x] DEPO to review copy (Beth)
- [x] Create ticket to input content into Drupal (Laura/Randi)

## Acceptance Criteria
- [x] Copy deck reviewed and ready to be input into Drupal

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO Quick note re: the "Closed programs" page (http://preview-prod.vfs.va.gov/preview?nodeId=5588). 

I think this is one to actually ask the SMEs if we need at all. It looks like the legacy page hasn't been updated since 2013. 

If we do need the info somewhere on the site, I would recommend removing the "Policies still in force" and "Average age of policyholders" fields under each program. It's very outdated For example, there are no WWI Veterans still alive today (though it's possible a younger spouse could be a policyholder?) and WWII Veterans are now typically in their late 80s and 90s. And it will quickly become outdated again, even if we were to update it to reflect 2020 info.

**Comment by bethpottsVADEPO** [comment]
When I share the 2 IRIS questions with the stakeholder, I'll also ask her to review these rewritten pages that we worked on previously but had put on pause. 
http://preview-prod.vfs.va.gov/preview?nodeId=5581
http://preview-prod.vfs.va.gov/preview?nodeId=5582
http://preview-prod.vfs.va.gov/preview?nodeId=5587

And yes, @DanielleThierryUSDSVA will specifically ask whether it makes sense to publish the info in 5588.

**Comment by lwalsh617** [comment]
Hi @bethpottsVADEPO and @RLHecht 
Here's the complete copy deck for life insurance. For ease of reviewing/commenting, I put everything in the Word doc rather than having some articles in Drupal and others in Word.
@bethpottsVADEPO -- Do you want to have a look before Randi does an edit?

  [https://app.zenhub.com/files/133843125/dba9654c-4815-4192-9999-ae6d34659a0a/download](https://app.zenhub.com/files/133843125/dba9654c-4815-4192-9999-ae6d34659a0a/download)

**Comment by bethpottsVADEPO** [comment]
Uploading the most recent deck here with track changes that will need to be made in drupal. @RLHecht @lwalsh617 please wait on making these edits for now, as some things will change with the SME review. You can do all the edits at once when I receive her feedback. I just wanted to make sure my edits were captured here. 

I'll resolve edits on the copy that I send to the SME for review: [https://app.zenhub.com/files/133843125/2a59535e-971a-4456-a4a9-4eb02bc2191c/download](https://app.zenhub.com/files/133843125/2a59535e-971a-4456-a4a9-4eb02bc2191c/download)

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop My edits are attached here. You can incorporate into drupal and copyedit in whichever order makes sense to you. Probably copyedit last since there are a fair number of edits for Selina to put into drupal.

@lwalsh617 for awareness of edits made.

I'm waiting for Lori's feedback still. At that point there may be more edits. @RLHecht Can you create a ticket now for the stakeholder review stage, including a task for incorporating Lori's feedback? Thanks!

**Comment by bethpottsVADEPO** [comment]
Actually attached this time: 

[https://app.zenhub.com/files/133843125/5c27bc84-54bd-4b65-8dcb-087fddcc02ba/download](https://app.zenhub.com/files/133843125/5c27bc84-54bd-4b65-8dcb-087fddcc02ba/download)

**Comment by RLHecht** [comment]
Closing this ticket out. Next steps are reflected in #17646.
