### ISSUE TITLE
FSR - Conversations with VSOs

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#14554]
## Issue Description
_During interviews with DMC SME's, the team uncovered that if Veterans need assistance filling out the FSR (VA Form 5655), they're redirected to their local VSO. In order to understand the pain points Veterans face while completing the form, the team is going to speak with VSOs._

---
## Tasks
- [x] _Conduct conversations with VSOs_
- [x] _Upload the notes from each session to GH_

## Acceptance Criteria
- [x] _All notes have been uploaded to GH and the folder has been linked to this ticket_

**Comment by rileyorr** [comment]
[Notes & topline summaries](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report/research/oct-2020/vso-conversations) for all VSO conversations have been added to GH
