### ISSUE TITLE
Refine and Augment Direct Deposit-EDU Mockups

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#14557]
### Story
As a VA payment recipient, I need a simple way to change my direct deposit information so that payments are deposited in the correct bank account.

### Goals
Refine/understand use cases and states of DD-EDU so that mockups are complete and accurate.

### Considerations
- [DD-EDU discovery; stakeholder questions at bottom](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/edu-dd-discovery.md)
- [DD-EDU Mockups (Adobe XD)](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/)

### Tasks
- [x] Meet with business stakeholders
- [x] Collect clarification/feedback from team and stakeholders
- [x] Add any additional required states to mockups
- [x] Revise content and design as needed across mockups

### Acceptance criteria
- [x] All required states for DD-EDU reflected in mockups
- [x] Content changes made per clarification/feedback

**Comment by Samara-Strauss** [comment]
Putting some of my design feedback in writing, even though Jim and I discussed in on a call:

- There needs to be white space/separation between each block:
  - Direct deposit for comp & pen
  - Direct deposit for edu
  - Payment history
- The Payment history block needs to be designed like the others — the link to View payment history should not be in the gray block.
- We need an "add" state for direct deposit for edu. An example of this can be found in Tressa's Sketch files.
- People will fall into one of the categories. We need to make sure we have mockups that communicate this to FE developers so they know how to conditionally show/not show each block:
  - No direct deposit of any kind (we don't show that section)
  - Direct deposit for comp and pen only
  - Direct deposit for edu only
  - Direct deposit both for comp and pen AND edu

**Comment by sporeboy** [comment]
I have updates to the mocks here: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/

I think I hit everything. There's an "add DD" box on screens that have only one--or none--of the DD benefits set up.

**Comment by Samara-Strauss** [comment]
Nice, thank you! 

Question — for the "add" state, was the "If you'd like to set up direct deposit..." copy something you added, or was it something you saw in Tressa's design files somewhere? I *think* the "add" state is just the field label and "Please add your bank information" link in production, so we should be consistent there.

**Comment by sporeboy** [comment]
The copy was on me. I was looking to provide context. If you simply say "add your bank info" without establishing that a user needs to be receiving EDU or C&P payments, you could invite users to casually add and submit info.

With two DD features presented together, it may be a good idea to review the copy for greater clarity.

**Comment by Samara-Strauss** [comment]
> The copy was on me. I was looking to provide context. If you simply say "add your bank info" without establishing that a user needs to be receiving EDU or C&P payments, you could invite users to casually add and submit info.

We don't show the direct deposit for comp & pen block at all if you are not eligible to receive payments. In theory, we can hopefully do the same for edu.

**Comment by Samara-Strauss** [comment]
OK, final changes, and then we can close this out:

1. Please take out the "If you receive [x] benefit payments and you'd like to set up direct deposit" copy. We only show direct deposit for comp & pen if we detect they are eligible, so the additional clarifier copy isn't necessary because people who don't receive comp & pen payments will never see this block. It *should* work the same for edu (where we only show the block if you are eligible for payment), so we also don't need the extra copy there. If we discover that for some reason we can't show an "add" state based on whether people are eligible for edu payments or not, then we can consider adding the copy back or just not showing the edu block to people who don't already have edu set up (which would be the preferred approach).
2. There's some extra space between the section title and the direct deposit for comp & pen block in some of the wireframes. Can you clean that up?

Otherwise, this looks great!! Nice work!

**Comment by sporeboy** [comment]
Revisions made... The weird gap is gone (oops!), and the explanatory text was removed. Should be set!

**Comment by Samara-Strauss** [comment]
Looks great! I think we can close this out.
