### ISSUE TITLE
Loki - Demonstrate current status/capabilities at upcoming End of Sprint Demo

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14553]
## Issue Description
_In order to help socialize our implementation of Loki, we will demonstrate current status and capabilities at the upcoming End of Sprint demo. This may also help us to gain some feedback and inform the upcoming phases of implementation that are taking place in Q4 2020._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _Latest work towards implementation of Loki will be shared with external teams during End of Sprint Demo_
- [ ] _Visual assets and/or walkthroughs will provide insight into work done so far_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
