### ISSUE TITLE
Confirm Attachment Submission Endpoint in BGS

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14556]
## Background
We want to ensure that the attachments that we are sending in the 686 submission are getting to the right place for consideration.

## Considerations
- [x] Do they simply go to VBMS? (JW) **Yes**
- [x] What happens in EVSS now? (KC)
- [x] Can we check in our GFE? (KC)
- [x] Would Linda at BGS know? (JW) **She shared some info in email/Teams**
- [ ] Would RBPS have a say in that? (JW)

## Tasks
- [x] Assuming things with attachments are sent to manual, they might just go to VBMS where the manual check is taking place

## Acceptance Criteria
- [x] A solution or location has been identified, noted here in this ticket for now

**Next Steps:** 
- [ ] Implement that location as the new destination for attachments of evidence

**Comment by kathleencrawford** [comment]
Email correspondence with the EVSS team confirmed that all attachments associated with a 686 form are sent to the VBMS eFolder.

Considerations:
- Currently, EVSS converts the document to a PDF.  Does `vets-api` need to do this or can the doc stay in its original format?
- The document then gets stamped and renamed.  Need to research naming convention.
- How does the manual reviewer know which doc in the eFolder is associated with the 686 submission.  Is it by file name?
