### ISSUE TITLE
Pre-select facility locator drop downs

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14559]
## Tasks

- [ ] Define business logic for pre-selecting fields

- [ ] Decide whether these should be built into the web-app version or natively

- [ ] If the web-app version, work with Facilities team on implementation
