### ISSUE TITLE
FSR - Discovery research synthesis

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#14555]
## Issue Description
_Once completing research with DMC SMEs and VSOs, the design team needs to synthesize and uncover themes learned about how Veterans interact with the FSR (VA Form 5655)_

---
## Tasks
- [x] _Synthesize research sessions with DMC SMEs and VSOs_
- [x] _Write a research readout containing the top takeaways_

## Acceptance Criteria
- [x] _The final research readout is uploaded to GH and linked to this ticket_
- [x] _(Optional) A deck is created to present findings to the team and/or at demo_

**Comment by rileyorr** [comment]
Uploaded [the research readout deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/oct-2020/vso-conversations/FSR-SME-VSO-discovery-readout.pdf) that I presented to the DMC stakeholders to GH
