### ISSUE TITLE
FSR - SME feedback on wireflows (iteration 1)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#14566]
## Issue Description
_Our team needs to present the FSR (VA Form 5655) wireflows to the DMC SMEs to verify that the UI covers all business requirements. Additional insights/constraints may be uncovered during the review that need to be incorporated into another iteration._

---
## Tasks
- [x] _Present FSR wireflows (iteration 1) to DMC SMEs for feedback_
- [x] _Document feedback in GH_
- [x] _Incorporate feedback as needed_

## Acceptance Criteria
- [x] _Feedback has been documented in GH_
- [x] _Feedback has been incorporated into the wireflows as needed_

**Comment by rileyorr** [comment]
The [FSR wireflows change log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/design/wireflows-change-log.md) includes the DMC SME feedback from when the designs were presented at a weekly check-in. The feedback is being incorporated into the hi-fi prototypes.
