### ISSUE TITLE
FSR - Wireflows (Iteration 1)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#14563]
## Issue Description
_Once the team completes the FSR ideation session, the design team will create wireflows of the FSR (VA Form 5655) prior to prototyping._

---
## Tasks
- [x] _Create wireflows for the FSR_
- [x] _Present wireflows to the team and confirm with development team that the UI is technically feasible with the form system_

## Acceptance Criteria
- [x] _Wireflows are uploaded to GH and linked to this ticket_
- [x] _Wireflows are presented to the team and any feedback is documented in GH_
- [ ] _(Optional) If feedback needs to be incorporated, a separate ticket is created to incorporate that work_

**Comment by rileyorr** [comment]
The [first iteration wireflows](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report/design) have been uploaded to GH :)
