### ISSUE TITLE
Update number of days to complete a disability related claim for September

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14569]
## Issue Description
The number of days it takes to complete a disability-related claim changes each month. We need to update the number on two of our pages given to us by stakeholder Sandy Tadeo.

Pages to update: https://www.va.gov/disability/after-you-file-claim/ and https://www.va.gov/disability/how-to-file-claim/

![Screen Shot 2020-10-07 at 3.54.24 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/1269de57-3ca0-41f6-a3ce-a7a591d0cc06): 

New information should read: 131.5 days for September 2020

## Tasks
- [x] Update info with new number and month written above (Randi)
- [x] Review and publish pages (Randi)
- [x] Alert stakeholder that change has been made (Randi/Beth)

## Acceptance Criteria
- [x] September information is live on the site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@brianalloyd I didn't have a chance to write this ticket before planning but it will be a quick one to close out this sprint.

**Comment by RLHecht** [comment]
Changes made. Moving to validate and will close after today's deploy. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
Changes validated on live site. Closing ticket.
