### ISSUE TITLE
Analysis/Readout of CH36/31 Usability Test Findings

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#14561]
### Story
As a Veteran, I need a simple, clear way to determine if I'm eligible under CH36/CH31, so I can apply for benefits. **And...** As a Veteran, I need a simple, easy form, so I can apply for CH36/CH31 benefits.

Usability testing of the CH36 and CH31 wizards and form was conducted between 9/24 and 10/1. There were seven sessions. 

### Goals
Create a detailed analysis of usability testing findings so that:

- All research questions are answered
- User needs are accurately captured
- Next steps are determined so the design and flow of the feature is improved

### Considerations
- [CH36/CH31 Usability Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-research-plan.md)
- [CH36/CH31 Usability Convo Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-convo-guide.md)
- [Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-topline-summary.md)

### Tasks
- [x] Create MD document outlining analysis of usability test findings
- [x] Create PPT presentation of formal analysis

### Acceptance criteria
- [x] Research analysis available in GH
- [x] Formal presentation deck created and made available

**Comment by sporeboy** [comment]
MD doc available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-synthesis.md
