### ISSUE TITLE
Content review for IRIS Q&A Batch 2 Service member benefits

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14568]
## Issue Description
First-draft copy of IRIS batch 2 service member benefits Q&As needs to be reviewed by DEPO before building in Drupal.

Copy deck to review: [https://app.zenhub.com/files/133843125/fc4bf383-7d91-4cb0-9b08-2f77bbfc00cc/download](https://app.zenhub.com/files/133843125/fc4bf383-7d91-4cb0-9b08-2f77bbfc00cc/download)

## Tasks
- [ ] DEPO to review copy (Beth)
- [ ] Create ticket to input content into Drupal (Laura/Randi)

## Acceptance Criteria
- [ ] Copy deck reviewed and ready to be input into Drupal

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Rework answer to take into account this and others you find:
https://www.va.gov/health-care/eligibility/active-duty/

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I spent a little time with this today. 
- Your main CTA (button) would be to the tier 1 page: https://www.va.gov/service-member-benefits/
- You can see the above page for how to frame your answer, specifically the section with the H2 "Time-sensitive VA benefits to consider when separating or retiring." Then, also cover in your answer info that will link to https://www.va.gov/health-care/eligibility/active-duty/#enhanced-eligibility-for-retur
- For a related link, you could point to http://www.oefoif.va.gov

Let me know if this makes sense or if you want to talk it through before you revise your answer for this Q&A, to make sure you're going down the right path!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO @RLHecht --  Here's a revised copy deck per Beth's feedback above. LMK if you have feedback. Thank you!
[rs-1.1-servicemembers-v2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5631564/rs-1.1-servicemembers-v2.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- You mentioned awhile back that you made edits to the copy deck attached to my comment above. Can you share that deck for me to work from? 
Also, for https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vs[…]de-content/resources-and-support-planning/iris-status-092021.md can I list it as an article under review that's titled 
![image](https://user-images.githubusercontent.com/53535663/134379552-a9203a1c-87b5-4a24-978c-df8df5d746e3.png)
Thanks!
