### ISSUE TITLE
FSR - Ideation workshop

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#14560]
## Issue Description
_The BaM2 team needs to come together to discuss ideas for how we might present the form to users and discuss technical complexity and any technical limitations with proposed UI ideas._

---
## Tasks
- [x] _Set up a Mural board with necessary activities for ideation_
- [x] _Conduct ideation session(s) with team members as needed_

## Acceptance Criteria
- [x] _A Mural board containing workshop activities, team members' sketches, and notes about limitations and/or functionality to research is linked to this ticket_

**Comment by rileyorr** [comment]
The ideation board can be found [here](https://app.mural.co/t/vsa8243/m/vsa8243/1602530749582/3eb0ac4ef1e9c0d6be86978a62166bd6c9db7e09) :)
