### ISSUE TITLE
Content review for IRIS Q&As Batch 1 eBenefits

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14567]
## Issue Description
First-draft copy of batch 1 eBenefits Q&As needs to be reviewed by DEPO before building in Drupal.

Copy deck to review: [https://app.zenhub.com/files/133843125/bb9ba445-c06c-4422-b99e-a8deec5364d7/download](https://app.zenhub.com/files/133843125/bb9ba445-c06c-4422-b99e-a8deec5364d7/download)

## Tasks
- [ ] DEPO to review copy (Beth)
- [ ] Create ticket to input content into Drupal (Laura/Randi)

## Acceptance Criteria
- [ ] Copy deck reviewed and ready to be input into Drupal

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Moving to backlog since we had to pause this to assess the duplication of information with our DS Logon FAQ.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Can we close this ticket? I believe you decided that we do not need to include eBenefits questions, correct?

**Comment by bethpottsVADEPO** [comment]
Moving to icebox.

**Comment by jilladams** [comment]
Closing. Learning centers is long in the past, now in Drupal and tracked as Resources & Support.
