### ISSUE TITLE
FSR - Modify conversation guide for VSO conversations

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#14565]
## Issue Description
Modify the conversation guide for VSO conversations so that we are asking the most relevant questions 

---
## Tasks
- [x] Modify the conversation guide 
- [x] Upload guide to GH

## Acceptance Criteria
- [x] Guide uploaded in GH and linked to ticket

**Comment by rileyorr** [comment]
Uploaded [the modified convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/oct-2020/vso-conversations/vso-conversation-guide.md) to GH
