### ISSUE TITLE
Migrate DVP projects to Sentry 10

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14571]
## Description

There are additional projects that live in Sentry 9 that are outside of VSP project ownership. We need to reach out to the teams responsible for the sections listed below to ensure they are still needed and the plan to move them to the new Sentry.

- If they want to use Sentry 10 we'll need to migrate their projects
- This could include code changes in their repo, might not be 1:1 w/ `vets-api` 
- Will require configuration of `environment` setting as well `SENTRY_ENVIRONMENT=$environment`
- Where $environment is one of `'development', 'staging', 'sandbox', 'production'`

### DVP Projects

- [ ] [Developer Portal](http://sentry.vfs.va.gov/vets-gov/developer-portal-production/)
- [ ] [Developer Portal - API](http://sentry.vfs.va.gov/vets-gov/developer-portal-backend-production/)
- [ ] [OAuth Proxy](http://sentry.vfs.va.gov/vets-gov/oauth-proxy/)
- [ ] [SAML-Proxy](http://sentry.vfs.va.gov/vets-gov/saml-proxy/)

### Tasks 

- [ ] Update `SENTRY_DSN` configuration for project
- [ ] Add `SENTRY_CURRENT_ENV` configuration for project with current environment string

**Comment by alexpappasoddball** [comment]
@kfrz @ericboehs lets break this ticket out into the 4 different tasks.

**Comment by kfrz** [comment]
Closing in favor of the individual issues. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/14857
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14859
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14862
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14863
