### ISSUE TITLE
FE implementation of CMS new date/time zone fields 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14578]
## Issue Description
Current date fields don't support time zones. 
This impacts events, ~new releases~ and situation updates for VAMC pages.

From [#2811](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2811)
- New date and or daterange fields have been added as per the [#2811](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2811)
- `field_datetime_range_timezone` has been added to event and ~news release~ content type. Default is set to ET for both. (Note from Kevin Walsh - backend for field related to news releases will be removed in the next sprint)
- `field_datetime_range_timezone` has been added to Situation update paragraph type
- Field remains hidden on node and paragraph forms, and in node and paragraph proofing (view mode) experience, for now (they'll be "released" in #2860)

## Blocking

- This is a blocker for VISN 19 rollout as all times currently default to ET. 
- This work (and the subsequent transformer) blocks CMS deprecation of old date time fields and update to editorial experience for new fields.

## Related issues: 
[CMS Epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2813)
[Issue to coordinate with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2859)

---
## Tasks
- [x] Update Events, ~News Releases~, Situation Update graphql queries to pull in the `fieldDatetimeRangeTimezone` field.
- [x] Update the liquid templates that use this field:
  - src/site/teasers/event.drupal.liquid
  - ~src/site/layouts/press_releases_listing.drupal.liquid~
  - src/site/components/situation_updates.drupal.liquid
- [x] use ET as the default time zone when fieldDatetimeRangeTimezone.timezone is null

In non-production environments, to support testing:
- [x] If `fieldDatetimeRangeTimezone` is empty, fall back to `fieldDate`.
The non-production check will be removed after testing is complete.

The non-production checks and fallback code will be removed after testing is complete.

Test data will be added by @kevwalsh 

## Acceptance Criteria
- [x] Events, ~News Releases~, Situation Update dates published in Drupal with time zones other than ET are shown with the correct time zone on the website.

Sample pages:
Events: https://staging.va.gov/outreach-and-events/events/tele-townhall-live-in-california-with-under-secretary-for-benefits-0/

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
AFAICT, there isn't any work that needs to be done on the front end here. The timezone should be part of the date string, and we can just display it like we do already.

**Comment by mmiddaugh** [comment]
Coordinate with Public websites on events

**Comment by kevwalsh** [comment]
## Event nodes with this data

![Edit_Event_Tele-Townhall_Live_in_California__with_Under_Secretary_for_Benefits__Paul_Lawrence___VA_gov_CMS](https://user-images.githubusercontent.com/643678/96888646-dac33780-1453-11eb-8316-840e19493fc3.jpg)

![Edit_Event_MCEC_Education_Summit_2020___VA_gov_CMS](https://user-images.githubusercontent.com/643678/96888716-e9115380-1453-11eb-8730-c19294011f4f.jpg)

## News release node with this data

![Edit_News_Release_VA_Pittsburgh_Physician_receives_2020_David_M__Worthen_Rising_Star_Award___VA_gov_CMS](https://user-images.githubusercontent.com/643678/96889951-22968e80-1455-11eb-8940-2eb38b5bee73.jpg)


## Situation update with this data

@kevwalsh will post this later.

**Comment by mmiddaugh** [comment]
Example urls from Pittsburgh
[Events](https://www.va.gov/pittsburgh-health-care/events/)
[News releases](https://www.va.gov/pittsburgh-health-care/news-releases/)
[Situation Update](https://www.va.gov/pittsburgh-health-care/operating-status/)
[Outreach Hub events](https://www.va.gov/outreach-and-events/events/)

**Comment by mmiddaugh** [comment]
@kevwalsh are you able to add Situation Update data for testing timezone? (see comment above)

**Comment by mmiddaugh** [comment]
@kevwalsh question about the [news release example](https://www.va.gov/pittsburgh-health-care/news-releases/va-pittsburgh-physician-receives-2020-david-m-worthen-rising/) above....I don't see a time displayed at all - just a date. Should we expect this to change with the new field implementation? 
![image](https://user-images.githubusercontent.com/55411834/97898601-4d0a0680-1cf5-11eb-99f0-13e2de385872.png)

**Comment by kevwalsh** [comment]
@mmiddaugh On the press release, i guess i had no idea that the time was not posted on the front end. It may have been, in the original design, but then got dropped? Our time zone work was just targetting all fields that had HH:MM in it, so this got included.

**Comment by kevwalsh** [comment]
I just had a thought, there may have been an idea to allow for the scheduling of the publication of a press release, based on the time indicated in the time field.

**Comment by kevwalsh** [comment]
@mmiddaugh @mpelzsherman i just added time zone data to the two Situation updates that are on node 6922 (a VAMC system banner alert), which are embedded in node 1010, which is an operating status page,(www.va.gov/pittsburgh-health-care/operating-status)

**Comment by mpelzsherman** [comment]
I’ve confirmed the one Event provided by the CMS team is showing PST on staging.
