### ISSUE TITLE
DebtRes FSR - Hi-fidelity prototypes (iteration 1)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#14575]
## Issue Description
_Once wireframes are reviewed and feedback is incorporated, the design team can move into high-fidelity prototyping the FSR (VA Form 5655)._

---
## Tasks
- [ ] _Create hi-fidelity prototypes in Sketch_
- [ ] _Port Sketch files to UXPin and add interactive states as needed_

## Acceptance Criteria
- [ ] _UXPin prototype is linked in this ticket_
