### ISSUE TITLE
Loki - Deploy and set up in STAGING environment

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14589]
## Product Outline
[Logging product outline)[https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/logging/product_outline.md]

## High Level User Story/ies
As an ops team member, I need deploy Loki logging in STAGING so that we can prepare for validate that the solution is ready for production.

## Hypothesis or Bet
**If** _we validate our implementation in STAGING_ **then** _we expect Loki logging to become ready for production_.

## OKR
_Q4 '20 - O2: Make it easier and more satisfying to build and operate the DEPO Platform_

### What must be true in order for you to consider this epic complete?
- [x] Loki running in STAGING
- [x] Loki capturing all system and application logs per [logging inventory ](https://docs.google.com/spreadsheets/d/1LMmK6hV0uTqApgh-rMGRMzf0QJ5XjA5FZVAMUVgNlsE/edit#gid=82168139)

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jhouse-solvd** [comment]
- [ ] [Deploy and set up in STAGING environment (EPIC)](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14589)
- [R&D for microservices](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/15370)
- [Deploy into Fargate with module in Microservices](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/15371)
- [Microservices cluster infrastructure / dependencies ](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15391)#1
- [Capture system and application logs](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/15372)
- [Docker logs via Loki Docker Driver](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/15373)
- [Cloudwatch Parity](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15392)

**Comment by jhouse-solvd** [comment]
Although some of the requirements and endstate have changed, we do have Loki running in STAGING and have made it accessible as a data source to developers via Grafana. 

Closing.
