### ISSUE TITLE
Loki - Capture Docker logs in DEV

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14583]
## Issue Description
_Figure out how to capture Docker container logs for debugging and monitoring containerized applications and services_

Configuration/code will be used for future environment deploys.

For DEV this includes:
- gids (gi bill data service)
- vets-api-server
- vets-api-worker
- content preview
- fwdproxy (network_status_exporter)

---
## Tasks
- [X] _Determine the best way to capture Docker Logs_ (Decided on [Loki Docker Driver](https://grafana.com/docs/loki/latest/clients/docker-driver/))
- [X] _Infrastructure code to install Docker Logging Driver on any hosts that need it_ [PR](https://github.com/department-of-veterans-affairs/devops/pull/7736)
- [X] _Infrastructure code to configure DEV docker containers to ship logs to Loki DEV_ [PR](https://github.com/department-of-veterans-affairs/devops/pull/7757) and [PR](https://github.com/department-of-veterans-affairs/devops/pull/7736)

## Acceptance Criteria
- [X] _Loki DEV is ingesting / receiving logs with appropriate tags for any app that uses Docker containers_ [proof](http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki-Dev%22,%7B%22expr%22:%22%7Bcontainer_name%3D%5C%22gi-bill-data-service%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pnwstevan** [comment]
This is complete except for :

- network-status-exporter - not included for now. It is a Docker container and only used by fwdproxy, and the current configuration has this defined as a role at build time so we can't abstract out separate container configurations per environment.
- content_preview - similar to above, runs as a Docker container configured as a build role so unable to configure separately per environment. Regardless, not configured to log in dev anyways so there aren't any logs to ship.
- statuspage-alert_forwarded - this repo appears to have been archived, so no changes can be made to the log configuration
