### ISSUE TITLE
[Product] How do we guide people to the new My VA dashboard?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14581]
## Background

**Overview**

On 10.7.2020, we made the decision to not continue pursuing a logged-in homepage redesign and pivoted to redesigning the My VA dashboard. 

**Problem**

We don’t really guide people to My VA right now. As a result, this page gets significantly less usage than the homepage (8% vs. 50% of users), but ideally, this page would be someone’s launchpad for their VA.gov experience when they log in. This, in theory, would be a first step in freeing up the homepage to do other jobs besides being the primary router for tasks on the website (note: we’d probably need to make additional changes to My VA to make that fully possible).

**Potential solutions**

If we want My VA to effectively be people’s “logged in homepage”, we have to guide them to this page. There are a few potential ways we could do this:

- **After the new My VA launches, show pop-up or anchored alert upon login when people sign in from the homepage** - These would be largely temporary, but they would nudge people to check out the updated page.
- **Show My VA in the navigation in a logged-out state** — This could either directly link to the sign in page, or this could be a page of its own that explains what the dashboard is and then prompts people to sign in. 
- **Redirect people who log-in from the homepage to My VA** — This may be something we eventually do, but I think we should hold off on this until there is a more unified strategy between the homepage and My VA.

**Samara's thoughts re: auth experience**

I think adding My VA to the unauth nav is the best approach for a few reasons:

- While a pop-up or anchored alert would likely nudge people to My VA at first, that solution is temporary and goes away as soon as those alert styles need to be used for something else.
- Adding My VA to the unauth nav allows us to set expectations on what a user will see when they log in, and incentivize them to do so.
- Adding My VA to the unauth nav is a relatively low lift. Whatever exists on that page in the logged out state will be standard for all logged out users (in contrast to the highly personalized functionality the page offers when you log in).
- It will be easy to test whether adding My VA to the unauth nav is (1) a good idea in the first place and (2) whether it actually changes user behavior in both the logged in and logged out experiences. If we observe that this change doesn’t make a difference or somehow makes things worse, we can easily remove My VA from the unauth nav. 

## Tasks

- [ ] Meet with Public Websites/IA/digital health modernization teams to discuss approach
- [ ] Determine approach for guiding people to My VA
- [ ] Determine next steps and create tickets accordingly

**Comment by sshein** [comment]
if we choose the redirect method, I'd be curious how it would be done (what the user would see). I know we redirect folks to tools sometimes when they're logged in and on the landing page for the tool and it's pretty confusing because the landing page starts to load and then it redirects to the tool so it makes you think you've "missed something." I'm not a fan of partially loading a page, then automatically redirecting the user without them making the choice to move on

**Comment by Samara-Strauss** [comment]
Good point @sshein. I'm unsure if we would or would not have that issue since the user would be going to a totally different page instead of essentially staying on the same page. It's something we can look into as we get to a place to talk about this.

**Comment by Samara-Strauss** [comment]
We're having a DEPO conversation about whether we should show My VA in the logged out navigation. This could either take people directly to sign in, or to a version of My VA that describes what the page is and prompts people to sign in. We should work with Meg/Mikki (IA) and the public websites team to talk about how we should make this happen.

**Comment by Samara-Strauss** [comment]
I am removing this from sprint 39. We are not going to be able to solve this in the two remaining days of the sprint, and this needs to be a larger discussion with a few teams. We can continue the conversation, but I'm not planning on this being part of the next round of user testing we do.

**Comment by Samara-Strauss** [comment]
@tressaellen @callen2563 I am taking you two off of this ticket and pivoting it to a product-only ticket. I'm going to work with the public websites/IA/digital health modernization teams to figure out what approach is best, and once we've determined that, we can work to get design tickets together as necessary. cc/ @mshea0606

**Comment by Samara-Strauss** [comment]
**Notes from My VA unauth nav chat | 2.1.21** 

- Everybody is in agreement that we should add My VA to the unauth nav.
- We will **not** be adding My Health to the unauth nav that this time.
- Concern: Will people even know what My VA is?
  - Probably not, but also "My [x]" is a common convention across websites, so it shouldn't be too much of a leap. We can gather information on this in user testing and iterate from here if people are really confused.
- Flow specifics:
  - In the unauth nav, we will show a link to **My VA**. This will automatically trigger sign in and **not** a content page for My VA, as research has shown people are frustrated by landing on content pages when they expect to land on tools.
  - If someone logs in from the **homepage**, they will still land on the homepage at this time. We may redirect them to My VA later on pending further discussion, but not right now.
  - If someone logs in from anywhere else on the website, eg. the claims tool, they stay where they are in the flow that they're in.

**Comment by Samara-Strauss** [comment]
Design updates will happen in #19356. Closing!
