### ISSUE TITLE
Loki - Capture system & application logs in DEV

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14584]
## Issue Description
_We want to capture system and application logs so that they can be used for debug and analysis_

Additionally, this is the baseline configuration for all future Loki deployments.

Scope is tracked in [this spreadsheet](https://docs.google.com/spreadsheets/d/1LMmK6hV0uTqApgh-rMGRMzf0QJ5XjA5FZVAMUVgNlsE/edit#gid=754863553) (DEV only); scope EXCLUDES Docker which is tracked in a [separate issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14583).

---
## Tasks
- [X] _Decide HOW we will capture and ship logs to Loki for host/system/apps_ (decided on [Promtail](https://grafana.com/docs/loki/latest/clients/promtail/) after R&D/testing)
- [X] _Infrastructure code to setup and deploy Promtail on all hosts_ [code](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/common/promtail)
- [X] _Infrastructure code to configure labels per inventory/design doc_
- [X] _Infrastructure code to configure system logs to capture/ship_
- [X] _Infrastructure code to configure which app logs to capture/ship_

## Acceptance Criteria
- [X] _System and application logs are available in Grafana for all apps/hosts in DEV_ [proof](http://grafana.vfs.va.gov/explore?orgId=1)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
