### ISSUE TITLE
Update `vets-api` View Payments Functionality to Work with Mock Data 

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#14595]
## Goal
Update`vets-api` VIew Payments functionality to work with the mock data that has been added to `vets-api-mockdata`.

While adding the mock data for View Payments to the `vets-api-mockdata` repo, it was discovered that one of the calls being used is not currently set up to work with the mock data services.  The method in `vets-api` needs to be updated to pass in the required information in order for the mock services to work.  The method that needs to be updated is the `find_person_by_ptcpnt_id` method in the people service.

## Tasks
- [x] Update the View Payments method to pass in the user's identifier to work with mock data services
- [x] Update the BGS gem version after the BGS gem PR has been approved and merged into master

## Acceptance Criteria
- [x] The `vets-api` call to `find_person_by_ptcpnt_id` has been updated to pass in the user's identifier.
- [x] BGS gem version has been bumped to match the latest `bgs_ext` version
- [x] Unit tests are updated if needed
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5079
