### ISSUE TITLE
Update address on birth defects page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14594]
## Issue Description
Per stakeholder Paul Shute the address on the [birth defects](https://www.va.gov/disability/eligibility/special-claims/birth-defects/) page under the "By mail" section needs to be updated to the centralized Claims Intake Center address. 

The new address is:

Department of Veterans Affairs
Claims Intake Center
PO Box 4444
Janesville, WI 53547-4444

## Tasks
- [x] Update address on birth defects page with the one above (Randi)
- [x] Review and publish node (Randi)
- [x] Notify stakeholder that change has been made (Beth/Randi)

## Acceptance Criteria
- [x] New address showing on live page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This change has been made. Moving to validate and will close after Thursday's deploy. @bethpottsVADEPO you can let Paul know this has been fixed. FYSA @brianalloyd

**Comment by RLHecht** [comment]
Change validated on live site. Closing ticket.
