### ISSUE TITLE
Change VA311 phone number

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14609]
## Issue Description

The VA311 phone number is changing from **844-698-2311** to **800-698-2411**. This change is scheduled for **October 31, 2020.** On that date, we'll need to update this number across:

- The Contact Us dropdown (Randi & Selina)
- The footer (Randi & Selina)
- The coronavirus FAQs page (Danielle & Randi) 
- The coronavirus chatbot (Danielle & Randi)
- Any site pages where it currently appears (Randi & Selina)
- Promos - coronavirus page, check others (Randi, Selina, Danielle)
- MHV as noted below (Randi & Selina)
- Tools pages (Peggy & teams)
- Learning center (needs to be updated here: https://prod.cms.va.gov/va-central-office/call-va311-for-help - Randi & Selina)

We're confirming whether or not we'll shift branding to "VA411" (with the full number as well) or whether we'll simply provide the full number. I'll update here once confirmed.

---
## Tasks

- [x] Update number in footer
- [x] Update number in contact us drop down
- [x] Update number in chatbot
- [x] Update number across all live pages
- [x] Update number in promos - coronavirus FAQs page, check others (Randi, Selina, Danielle)
- [ ] Update number in draft "Contact us" page
- [ ] Update number https://prod.cms.va.gov/va-central-office/call-va311-for-help (not sure this is a page we control - checking into this)
- [x] Publish all Drupal changes
- [x] Deploy PR
- [ ] Validate on live site

## Acceptance Criteria

- [ ] New number live on the site in all relevant locations
---
## How to configure this issue

- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
**Notes:**

- I've set this for Sprint 33, but the specific anticipated deadline for the switch over to this new number is 10/31/20 so a few days ahead of the close of Sprint 33.
- @ncksllvn @kelsonic I've added you to this issue since I know you've helped in the past with searching for phone numbers that need to change. 
- @RLHecht Let me know when you have time to check in on content for this. Also, I threw in a 5 for estimate. Feel free to adjust.

FYSA @brianalloyd @MickinSahni @bethpottsVADEPO @jenniferlee-dsva

**Comment by DanielleThierryUSDSVA** [comment]
Hi @peggygannon. Tagging you on this ticket so we can connect on tool updates.

**Comment by peggygannon** [comment]
Hi, @danielle, a question about this. For the tools/app, this number mainly appears in the application's *Need help* footer and in (maybe) some error states 
 1. I want to confirm if we'd use "VA411" as part of this update, or just the 800-698-2411 ?
2. TTY is not change and is still 711? 
3. Is there any standard language that the static pages will use around this change. (for example, do pages refer to it as the "general VA.gov  number"? )

**Comment by meganhkelley** [comment]
Hello from VSP FE Tools! Rian did a quick search and it looks like most of these changes should be handled by Public Websites or triaged to other VFS teams. Based on the files [in his screenshot](https://dsva.slack.com/archives/CQH357ZTP/p1603228733230800?thread_ts=1603228549.230400&cid=CQH357ZTP), I can tell you that y'all should coordinate with ... (I'm referencing the [codeowners file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/CODEOWNERS) primarily to make this list)

* eBenefits team cc @jason-gcio 
* Authenticated Experience team cc @mshea0606 

Tagged folks, please take a look at the screenshot linked above — these are files that your teams own (I believe) that will need content updated re: the phone number change in this ticket. Please coordinate with Danielle & Public Websites team regarding timing of these changes. 

I'm following up on the one MHV file, that might be a VSP thing (maybe Identity team?), not positive 👀 

Thanks all, let me know if you have questions!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @peggygannon. To answer your questions:

1 and 3: I'm working out now how we want to specifically reference this number. Will update here this week.

2: Correct, TTY remains the general 711.

Thanks!

**Comment by meganhkelley** [comment]
@DanielleThierryUSDSVA @brianalloyd after attempting to track down the owner of the MHV file included in the screenshot I linked above, I think it makes most sense for Public Websites to own changing that instance. 

Related to MHV ownership: https://dsva.slack.com/archives/CE4304QPK/p1603377835200200

And from Corey Trimm: "Identity does not own MHV. [...] Looking at the history of changes in that validate-mhv-account folder, Identity has made changes to SSOe related authentication logic, not the actual HTML that gets rendered on that page. Kelson, Nick, and others have changed more of the client facing code."

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Here's the direction for the content team from our call:

### Header

Change to:

Call us: 800-698-2411

### Right rails on benefit hub pages 

Change to:

VA411 information line:
800-698-2411

### Footer 

TBD - refining direction on this as part of IA/content strategy exercise. Will post final decision on this this week.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ncksllvn @kelsonic. I think we need your help updating the header and footer. Is that correct? If yes, is that something you could help us do for Friday's deploy? I know you have a ton on your plate.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @lunascoop @jason-gcio @mshea0606.

@clantosswett just got word that we need to refer to "MyVA411" rather than just "VA411." Please see comment above with revised verbiage to use for this update. Thank you!

**Comment by ncksllvn** [comment]
It’s easy to update the header and footer. No problem @DanielleThierryUSDSVA.  Just keep us posted about tool pages or other places we may need to update.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @ncksllvn! @RLHecht and @lunascoop, please let Nick and Kelson know other places where you may need their help.

**Comment by meganhkelley** [comment]
@DanielleThierryUSDSVA @ncksllvn Rian pulled a list that I will attach here (it's also linked above). 

Between Public Websites, eBenefits, and Auth Experience, you should be able to catch them all. Not sure how you want to coordinate. @brianalloyd I would recommend confirming and coordinating with @jason-gcio and @mshea0606. 

![Screen Shot 2020-10-20 at 17 18 22](https://user-images.githubusercontent.com/54412366/97578739-9a216c00-19c7-11eb-9c3a-efcb168de669.png)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @meganhkelley! @jason-gcio connected via slack. @mshea0606, please let @brianalloyd and I know if we're good on your end or if you need anything further from us. Thank you!

**Comment by jason-gcio** [comment]
@meganhkelley - Here is our PR for Rated Disabilities, we should be good to go. Thanks for your help coordinating :)
https://github.com/department-of-veterans-affairs/vets-website/pull/14765

**Comment by meganhkelley** [comment]
Hi @jason-gcio! You should coordinate directly with Public Websites on this one (cc @brianalloyd @ncksllvn @DanielleThierryUSDSVA ) — VSP isn't conducting the orchestra on this one 😉

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Chatbot PR is ready for your review this morning, and then I'll hand off to ThoughtWorks team: https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/335.

Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lunascoop Looks like the coronavirus faqs promo (prod.cms.va.gov/block/6) was updated. I just added "our" and removed an extra period . @RLHecht if you could take a final look and the set to publish, that would be great.

Also looks like you're actively working on the coronavirus FAQs page. Quick note that there are a couple of instances of the old number on that page that aren't labeled as "VA311" so we'll just need to make sure they also get updated. Thanks!

**Comment by lunascoop** [comment]
@RLHecht @DanielleThierryUSDSVA I've updated instances of MyVA311 on the right rail, coronavirus faqs promo, and other instances. I've also updated other instances of the old number @DanielleThierryUSDSVA mentioned on the coronavirus FAQs page. I'll search for other instances where the old number without the "VA311" label is mentioned. In the meantime, here are some pages for review:

**Right rail instances**

- VA health care -http://preview-prod.vfs.va.gov/preview?nodeId=67 (Changing the right rail on this page also changed these pages:
  - VA benefits for spouses, dependents, survivors, and family caregivers - http://preview-prod.vfs.va.gov/preview?nodeId=810
  - VA records -http://preview-prod.vfs.va.gov/preview?nodeId=79
  - VA disability compensation-http://preview-prod.vfs.va.gov/preview?nodeId=68
  - Careers and employment - http://preview-prod.vfs.va.gov/preview?nodeId=72
  - VA life insurance-http://preview-prod.vfs.va.gov/preview?nodeId=77
  - VA benefits for service members-http://preview-prod.vfs.va.gov/preview?nodeId=809
  - VA pension benefits - http://preview-prod.vfs.va.gov/preview?nodeId=73
  - VA burial benefits and memorial items -http://preview-prod.vfs.va.gov/preview?nodeId=78
  - VA housing assistance -http://preview-prod.vfs.va.gov/preview?nodeId=74
  - VA education and training benefits - http://preview-prod.vfs.va.gov/preview?nodeId=71
  - VA decision reviews and appeals-http://preview-prod.vfs.va.gov/preview?nodeId=3071

**Other instances**

- Coronavirus FAQs: What Veterans need to know - http://preview-prod.vfs.va.gov/preview?nodeId=3014
- Frequently asked questions (FAQs) about signing in to VA.gov -http://preview-prod.vfs.va.gov/preview?nodeId=713
- Download VA benefit letters -http://preview-prod.vfs.va.gov/preview?nodeId=471
- Promo: COVID-19 and VA health care https://prod.cms.va.gov/block/6?destination=/admin/content/promos

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @lunascoop!!

@ncksllvn @kelsonic Had to update footer slightly. It's now updated above and ready to go. Thanks!

**Comment by kelsonic** [comment]
PRs open, pending reviews + merging

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @lunascoop I've published all the drupal pages Selina noted above as well as the the covid promo on the health care page.

**Comment by kelsonic** [comment]
PR merged, pending off-schedule deploy, feel free to follow it here: https://dsva.slack.com/archives/CBU0KDSB1/p1604088483317000?thread_ts=1604082038.296400&cid=CBU0KDSB1

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @kelsonic!

**Comment by brianalloyd** [comment]
Has the PR been merged for this?  If so can we close this out?

**Comment by DanielleThierryUSDSVA** [comment]
@brianalloyd Yes. But need to confirm with @RLHecht @lunascoop that they've updated in R&S as well before we close. Thanks!

**Comment by RLHecht** [comment]
Yep, @DanielleThierryUSDSVA I updated it on the two places in R&S where we mentioned it in content so we are all good. FYSA @brianalloyd

**Comment by brianalloyd** [comment]
Thanks for the update @RLHecht, I'm closing this out in support.
