### ISSUE TITLE
Remove extra commas from address section in style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#14604]
## Issue Description
The "Like this" box in the address section of the style guide currently has a comma after the state abbreviation, which should not be there.

![Screen Shot 2020-10-08 at 11.01.16 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d0bb601f-2969-4cce-958e-cd8c38cf237d)

PR to work on: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/321
## Tasks
- [x] Remove comma after "DC" and "NY" (Randi)
- [x] Review and merge PR (Danielle/Beth)

## Acceptance Criteria
- [x] Commas no longer showing on style guide

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
I made this change. @DanielleThierryUSDSVA or @bethpottsVADEPO could you please review and merge the PR when you get a chance? Thanks!

**Comment by RLHecht** [comment]
Work done and PR merged. Moving to validate and will close after today's deploy. FYSA @brianalloyd

**Comment by RLHecht** [comment]
Changes on live site. Closing ticket.
