### ISSUE TITLE
[Design] My VA redesign: Discuss new project plan now that we've pivoted from LIH redesign --> My VA redesign

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14608]
## Background

As of 10.7.20, it was determined that we would not be redesigning the logged in homepage. Instead, we are pursuing this project as a My VA redesign and will be leaving the homepage alone. 

Therefore, our plans of what we need to handle on My VA are now different since we don't have to accommodate all of the homepage content. Here is an updated list of what is in scope/out of scope for this work:

**In scope**

- Redesign the following content on My VA:
  - Your applications (Applications in progress).
  - Disability-related content (claims, your rating, prompts to get started if you don't have disability benefits).
  - Health care-related content (overview, application status, Rx, messages, appointments, prompts to get started if you don't have health care).
- Revisiting the profile "name tag" area.
- Basic on-page navigation and information architecture.
  - (Nice to have/not required) Incorporate Profile into this navigation.
- A very basic first-time user experience that will account for users who have no benefits and no applications in flight.
- LOA1 experience.

**Out of scope**
 
- Moving over education links from the homepage. (**Should we link off to the education hub?**).
- Moving over records links from the homepage.  (**Should we link off to the records hub?**).
- Any consideration of the current "Find VA Benefits" functionality (note: we **will** intro users who have no benefits or applications to benefits they could apply for).

## Tasks

With these new guidelines in mind, let's discuss how this will change [the current project plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/LIH-outline-and-timeline.md) both in terms of what needs to get designed and how we will handle research.

- [x] Review the new list of proposed in scope/out of scope work for this project.
- [x] Regroup to discuss:
  - How this affects the design plan.
  - How this affects the user research plan.
- [ ] Update documentation accordingly.

**Comment by Samara-Strauss** [comment]
Scheduled a regroup for tomorrow, October 9 at 3:15 ET (right after standup).

**Comment by Samara-Strauss** [comment]
Meeting complete! We can close this after @tressaellen and @callen2563 update [the project plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/LIH-outline-and-timeline.md).

**Comment by tressaellen** [comment]
The project plan is updated, so I am closing this ticket
