### ISSUE TITLE
Add Phone Number to 5655 Schema

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#14617]
## Issue Description
Phone number will need to be prefilled for the 5655 save in progress form. Will need to add this to the schema as well as the backend prefill code.

---
## Tasks
- [ ] Add phone number to schema
- [ ] Add phone number to prefill

## Acceptance Criteria
- [ ] Phone number added to 5655 form
