### ISSUE TITLE
[FE] Clean up `isVeteran` and `veteranStatus` and `servedInMilitary` in redux store

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#14610]
## Description
The values `isVeteran` and `veteranStatus` and `servedInMilitary` are duplicated in the redux store and we need to clean this up. This work needs to be done carefully so not to break any logic dependent on these values.

To see the redux store issue, log into staging with user +36. Screenshot added.
![image.png](https://images.zenhubusercontent.com/5e9d15aab51cccb259a8a6c7/1793cf0d-d02d-4a1c-86b1-fdfd531ea2a2)

## Tasks
- [ ] Decide on proper `veteranStatus` structure in store
- [ ] Ensure no applications are breaking due to the change
- [ ] Modify any dependent tests

**Comment by sanlouise** [comment]
I will close this ticket myself - this was a code cleanup, and there is nothing to validate on Product's side
