### ISSUE TITLE
Suggestions for additional FL test coverage

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14612]
## Issue Description

This feedback from #13779 in response to a request for a review of recently expanded test coverage 

Tze made the following suggestions "must" for remediation before next Platform Usability Test Prep for this product. 

#### Vet arrives... [initial load]

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Facility-type default-option
- [ ] Facility-type options-list
- [ ] Search not initiated unless:
  - [ ] Location info entered [geolocation disabled/denied]; and
  - [ ] Facility-type selected

</details>

#### VA health facility-type selected

\[This feedback combines the 2 separate search Use Cases provided above (with the same title)]

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Service-type default-option
- [ ] Service-type options
- [ ] Alert below search-box
- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Distance
  - [ ] Address
  - [ ] Operating status? [cover IF you're mocking (and thus have control over) the data response]

</details>

#### VA benefits facility-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Facility-type default-option
- [ ] Facility-type options-list

</details>

#### VA benefits / Vet centers / VA cemeteries facility-type selected

<details>
<summary>Specific coverage gaps: [expand]</summary>

- [ ] Alert below search-box
- [ ] Results: \[see results-related gaps listed in **VA health facility-type selected** above, EXCEPT no need to cover Mental health number here]

</details>

#### Community providers facility-type, Dentist/Podiatrist service-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Alert hidden below search-box
- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Distance
  - [ ] Address
  - [ ] Directions
  - [ ] Main number
  - [ ] Referral text
- [ ] No Detail-page link

</details>

#### Community pharmacies facility-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Distance
  - [ ] Facility-type
  - [ ] ~~Services~~
  - [ ] Address
  - [ ] Directions
  - [ ] Phone number
  - [ ] Test to call to confirm hours and service
- [ ] No Detail-page link

</details>

#### Community care facility-type, Pharmacy - Community/Retail service-type selected

Entire Use Case not covered.

#### Urgent Care facility-type, All urgent care service-type selected

Entire Use Case not covered

#### Urgent Care facility-type, Community urgent care service-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Service-type default
- [ ] Service-type options
- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Facility-type
  - [ ]~~Services~~
  - [ ] Name of group/provider
  - [ ] Distance
  - [ ] Address
  - [ ] Directions
  - [ ] Phone number
- [ ] No Detail-page link

</details>

#### Community providers facility-type, Clinic/Center - Urgent Care service-type selected

Entire Use Case not covered

### Mobile

Test spec-file: [mobile.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js)

Detail-page Use Case not covered

### Overall feedback

**Context**: Unlike unit-test code-reviews in pull-requests, E2E-test coverage/results review audiences will likely expand to include non-technical & higher-level reviewers/stakeholders.

While much of the feedback below revolves around improvements to enable easy reviews by non-technical personnel, it should hopefully also facilitate test-code maintainability.

<details>
  <summary>Test suite and test structures/descriptions [expand]</summary>

- [ ] Test-Suites & Tests should be closely related to Use Cases and expected results, in terms of structure and descriptions:
  - [ ] Managers should easily determine which use cases passed/failed when checking test results
  - [ ] Engineers should easily determine which suites/tests to update when use cases change
  - [ ] Where separate Use Cases actually belong to a common User-flow, they're corresponding tests can be combined into a single suite/sub-suite. See suggested code-block below.

```javascript
describe('Facility search', () => {
  ...
  describe('Initied load', () => {
    it('should not auto-initiate search', () => {
      // assert empty location-input [geolocation disabled]
      // assert facility-type non-selection
    })

    it('should have expected facility-type dropdown default/options', () => {
      // assert default
      // assert options
    })
  })

  describe('VA health facility-type selected', () => {
    it('should have expected svc-type dropdown status/default/options'), () => {
      // assert enable/disabled status
      // assert default option
      // assert options list
    })

    it('should have/not have alert below search-box', () => {...})

    it('should have expected result-cards info', () => {
      // assert alert show/hide
      // assert map-icon
      // assert facility-name link
      ...
    })

    it('should have expected Detail-page contents', () => {...})
  })

  describe('VA benefits facility-type selected', () => {...})

  ...
})
```

</details>

<details>
  <summary>Selectors [expand]</summary>

- [ ] Selectors should target **data-testid** attributes wherever possible \[see [Cypress Best Practice](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements)]. Semantic values should be used for these attributes, to relate closely with expected-results (e.g., `data-testid="facility-link"`, etc.).
- [ ] With semantic `data-testid` attributes added:
  - [ ] These specific elements (currently targeting `.facility-result a`) should be asserted separately:
  - [ ] Facility-name link
  - [ ] Directions link
  - [ ] Main number link
  - [ ] Mental health number link
  - [ ] Other already-covered elements (currently targetting non-semantic selectors) should also target semantic `data-testid` attributes instead.

</details>

## Consider -- Suggested negative tests

- [ ] Invalid location inputs:
  - [ ] Invalid zip
  - [ ] Spaces only
  - [ ] Garbage? (e.g., '@&#\*%')

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@jtmst @maxx1128 - Can you review to see if the suggestions here were covered by your work on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9486 or if there's anything else here worth preserving in our backlog?
