### ISSUE TITLE
[FE] VA Profile: Consider changing the amount of time we cache an address

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14626]
## Background

On 10.8.20, Mike Richard from the VA Profile team posted the following in Slack:

> Also, I need to submit a ticket for your back log to review the VA.gov Cache period.  Data from our ticket Below  (https://vajira.max.gov/browse/VAPROOPS-291)
> During VA Profile Release 13.1.1, it was discovered that VA.Gov is caching the Veteran Contact Information. Slack Chat Log below.
> Result,
> 
> 1. Veteran logs in, contact information retrieved.
> 2. Veteran updates, changes flow to other systems Corp, ES, etc.
> 3. Updates made in Corp or ES and changes propagated to VA Profile and other systems.
> 4. Veteran refreshes VA.gov, most recent changes not visible.
> 5. Veteran Logs out of VA.gov and logs back in. No Change to address
> 6. Veteran logs into VA.gov from a different machine, No Change to address.
> 7. Veteran makes change in VA.gov, data is refreshed.
> 8. The write action busted the cache and triggered a refresh. Confirmed in chat log from VA.gov that they do cache Contact Info data for 24hrs.  
> 
> This is inconsistent with prior testing results where we have performed the test sequences and step 4 above usually has updated data within 5 minutes.

We need to determine why we are caching addresses for so long, and if there is not a good enough reason for us to be caching them for so long, we need to change the amount of time we are caching addresses.

## Tasks

- [ ] Review Mike's comments.
- [ ] Determine why the cache time is so long.
- [ ] Determine if other folks need to be brought in to this discussion. Is this in our purview to change?
- [ ] (Assuming this is in our purview to change, reduce the amount of time we are caching addresses
- [ ] Regroup with Mike to let him know these changes have been made
