### ISSUE TITLE
Adjust the `vnp_ptcpnt_vet_id` Record

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14624]
## Background
We need to pass in `vnp_ptcpnt_vet_id` to the `vnp_benefit_update_call` so that our test submissions will be accepted by RBPS.

## Considerations
`def vnp_benefit_claim_update(vnp_benefit_params)`
https://github.com/department-of-veterans-affairs/vets-api/blob/dc8ab576a974cf3e609feeb25549442da86b72ec/lib/bgs/service.rb#L135

## Tasks
- [x] Pass in `vnp_ptcpnt_vet_id` to the `vnp_benefit_update_call`

## Acceptance Criteria
- [x] The call is updated to include the above
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5085
