### ISSUE TITLE
Generate swagger docs for the Health Quest Service

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#14625]
## User Story
**In order** to use the va.gov site and all its features in a productive and efficient manner, now and in the future.
**As a** Veteran
**I want** the website developers to have a good understanding of how everything works under the hood by clearly documenting how the individual systems communicate with one another

## Description
Generate swagger docs for the **Health Quest** module so that the backend devs can use the documentation to design and build the REST endpoints like appointments, questionnaires, questionnaire responses, etc. The frontend devs can use the generated swagger docs to understand how the endpoints work and can consume data from them as a result and provide the customer with value.

## Tasks
- [x] Research swagger generation and how other modules/engines swaggers work
- [x] Generate swagger for the health quest service, make sure it is accessible and can be updated

## Acceptance Criteria
- [x] The swagger is accessible from vets-api 
- [x] check the code into the main branch
- [x] Have M. Dewey review it.

**Comment by mdewey** [comment]
This LGTM. Good Work Dillo!
