### ISSUE TITLE
FE Tweaks for CH31 Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14634]
## User Story
As a Veteran or general user of VA.gov, I want to be able to see where I am within the CH31 application, or the site in general, so that I can easily navigate to another part of the pages that are related to the task I am currently working on.

## Considerations
- Content changes for both the application and the wizard may be incoming at some point

## Tasks
- [x] Insert the breadcrumbs into the CH31 feature using the breadcrumb component
- [x] Alter the H1 title to match the mockup, change to: "**Apply for Veteran Readiness and Employment**"
- [x] Email addresses should be set to required
- [x] Add the privacy policy box to the end (see comment below)

## Acceptance Criteria
- [x] The breadcrumbs are inserted 
- [x] The H1 title has been updated to: " **Apply for Veteran Readiness and Employment**"
- [x] Email addresses are required
- [x] Privacy policy box with language has been added
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Subway steps look a tiny bit different, should they be matched from staging vs prototype?
https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526675/simulate/sitemap
vs
https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/veteran-information
"steps" vs blue circle on page

**Comment by jason-gcio** [comment]
Years of education: do we need to specify whether this includes high school or not?  Also, the field sizes are different and might need to be matched up.
https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/additional-information
vs
https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526678/simulate/sitemap

**Comment by jason-gcio** [comment]
Is the required privacy policy box with accompanying language missing?
![privacy](https://user-images.githubusercontent.com/53826255/95929959-4ee64700-0d93-11eb-8a7b-5fa4e7eb1164.PNG)
