### ISSUE TITLE
Move the Wizard onto the Intro Page for CH31 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14633]
## Background
There was some discussion about where the wizard for these features (including the CH36) would live; the unauth landing page or on the intro page.  For now it looks like it has been determined that the intro page is probably best.

## Considerations
- Might need to adjust how it initializes to exist on the intro page

## Tasks
- [ ] Move the wizard onto the intro page

## Acceptance Criteria
- [ ] The wizard has been moved onto the intro page
- [ ]  A PR has been requested for merging
