### ISSUE TITLE
[Analytics] My VA redesign: GA reports request

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14649]
## Background

I am in the process of putting together our [OKRs and KPIs for the My VA redesign](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=1242119200) (formerly the logged-in homepage redesign -- we've pivoted!), and I need help with a specific report to help me more accurately determine how I want to set one of the KPIs.

Back in April, Nedie and @bsmartin-ep helped us get [this report, which shows the percentage of users that use My VA](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20200402&_.useg=builtin1,userDatUa-iUR--ymOCPRsvErg,userTBuj9_dPSF-sBQQO9Srv-g/). This report is awesome and super helpful, but I have a couple requests:

- Is there any way we can make it so this report shows a longer period of time than 3 months? Things change by a few percentage points quarter to quarter, so I'd love to be able to see this data year to year (or year to date for 2020).
- Is there any way to add one more metric to this report? I would love to have a comparison of what percentage of users view the homepage **from a logged-in state**. Comparing page views of My VA to the homepage in general is not quite an accurate comparison, since people can view the homepage when they are logged out. I would love to be able to see how usage of My VA and the homepage differ for logged-in users only.

Thank you!

## Tasks

- [ ] Confirm receipt of this ticket
- [ ] Let Samara know what is/isn't possible (and thank you in advance no matter what)
- [ ] Make updates to the GA report
- [ ] Send Samara updated report

**Comment by Samara-Strauss** [comment]
Duplicate of #14651. Not sure how that happened.
