### ISSUE TITLE
Move app generator to vets-website

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14644]
## Issue Description
Having the app generator live outside `vets-website` creates some unnecessary overhead when an update is needed.

---
## Tasks
- [ ] Move the generator code to `vets-website`
- [ ] Remove the dependency from `package.json`
- [ ] Update the `new:app` NPM script
- [ ] Archive the generator repo

## Acceptance Criteria
- [ ] Updates to the generator code require no NPM publishing or dependency upgrading in `vets-website`
- [ ] Updates to the generator code can be made in the same PR as the code that introduces the need to update the generator

**Comment by timwright12** [comment]
Going to leave this in a separate repo as to not bloat vets-website anymore
