### ISSUE TITLE
[Analytics] My VA redesign: GA report request

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14651]
## Background

I am in the process of putting together our [OKRs and KPIs for the My VA redesign](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=1242119200) (formerly the logged-in homepage redesign -- we've pivoted!), and I need help with a specific report to help me more accurately determine how I want to set one of the KPIs.

Back in April, Nedie and @bsmartin-ep helped us get [this report, which shows the percentage of users that use My VA](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20200402&_.useg=builtin1,userDatUa-iUR--ymOCPRsvErg,userTBuj9_dPSF-sBQQO9Srv-g/). This report is awesome and super helpful, but I have a couple requests:

- Is there any way we can make it so this report shows a longer period of time than 3 months? Things change by a few percentage points quarter to quarter, so I'd love to be able to see this data year to year (or year to date for 2020).
- Is there any way to add one more metric to this report? I would love to have a comparison of what percentage of users view the homepage **from a logged-in state**. Comparing page views of My VA to the homepage in general is not quite an accurate comparison, since people can view the homepage when they are logged out (there is no logged out view of My VA). I would love to be able to see how usage of My VA and the homepage differ for logged-in users only.

Thank you!

## Tasks

- [ ] Confirm receipt of this ticket
- [ ] Let Samara know what is/isn't possible (and thank you in advance no matter what)
- [ ] Make updates to the GA report
- [ ] Send Samara updated report

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

Unfortunately, GA restricts us to 90 days on all user-based segments.  _Session-based_ segments don't have his restriction if we want to consider converting these.  Another option is converting this over to a BQ / DOMO query where we don't have this limit (or a limit on segments).

> Is there any way to add one more metric to this report?

Something like this?

https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20200402&_.useg=builtin1,userDatUa-iUR--ymOCPRsvErg,userTBuj9_dPSF-sBQQO9Srv-g,useroZx0HcxxRpWtuNYX7IFkHA/

**Comment by bsmartin-ep** [comment]
Also @Samara-Strauss  - is this a duplicate of #14649?

**Comment by Samara-Strauss** [comment]
> Also @Samara-Strauss - is this a duplicate of #14649?

Yes, not sure how that happened! I closed #14649 

> Unfortunately, GA restricts us to 90 days on all user-based segments. 

Ah, thanks for letting me know. I think I already knew this but was in denial :)

> Session-based segments don't have his restriction if we want to consider converting these. 

Is this effectively the same thing as % of users?

> Another option is converting this over to a BQ / DOMO query where we don't have this limit (or a limit on segments).

Depending on how good of a proxy sessions are for users, we might want to do this.

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

> Is this effectively the same thing as % of users?

That's a tough question to answer.  It really depends on the conditions and sequences in the segment and I guess **why** a user would return to the same funnel.  Date range would factor in too.

Best bet would be to recreate these as session segments and see how they compare.

Want me to take care of that?

**Comment by Samara-Strauss** [comment]
> Best bet would be to recreate these as session segments and see how they compare.
> 
> Want me to take care of that?

Yes, but after you do that, I might need some help understanding what I'm looking at and how the two are different.

Thank you so much for all your help!

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

Here is your original time-frame with the user-based segments....

https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20200402&_.useg=builtin1,userDatUa-iUR--ymOCPRsvErg,userTBuj9_dPSF-sBQQO9Srv-g,useroZx0HcxxRpWtuNYX7IFkHA/

...and now with session versions of those same segments (same timeframe)...

https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20200402&_.useg=builtin1,userDatUa-iUR--ymOCPRsvErg,userTBuj9_dPSF-sBQQO9Srv-g,useroZx0HcxxRpWtuNYX7IFkHA/

...and a longer time-frame (now possible with session based segments):

https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20200402&_.useg=builtin1,userDatUa-iUR--ymOCPRsvErg,userTBuj9_dPSF-sBQQO9Srv-g,useroZx0HcxxRpWtuNYX7IFkHA/

**Comment by joanneesteban** [comment]
@mshea0606 @Samara-Strauss please let us know if you need anything else! Closing this ticket.
