### ISSUE TITLE
Consolidate SiP config into a single object

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14690]
## Issue Description
The configuration for Save in Progress (SiP) is scattered among a handful of `formConfig` options:
- savedFormMessages
- prefillEnabled
  - Though I think we can have pre-fill without SiP, technically
- customText

This makes it difficult to understand when these configuration options should be used and when they can be ignored.

These configuration options should be consolidated into a single config object for clarity.

---
## Tasks
- [ ] Determine all the `formConfig` options used for SiP
- [ ] Group them all in a single `saveInProgress` object
- [ ] Update the components and functions which use these options

## Acceptance Criteria
- [ ] All the SiP options are in a single place in the `formConfig`

**Comment by taylorkaren** [comment]
Forms Library Team Ticket: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/86.
