### ISSUE TITLE
Less public requests to remove users from DSVA Slack workspace

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14713]
## Issue Description
Recently, a request to remove an offboarding user from DSVA Slack was made to a public Slack channel using the `@admins` handle. This can cause an issue if the timing is off. In an attempt to be proactive, the request was made to remove the user from Slack. However, the user's team, stakeholders, etc. had not yet been made aware of this user being offboarded. We should perhaps find a better way to still be proactive for this action, without such a wide vector / broadcast.

---
## Tasks
- [x] Find a sustainable, automated solution that still gets this task handled, but perhaps with a bit less visibility. 
- [x] Implement solution.

## Acceptance Criteria
- [x] Proactive actions taken to remove offboarded users, without the public broadcast.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Work was completed to give the users who view and work with the offboarding template the ability to automatically request user Slack account removal via a slash command. One can now comment on the offboarding ticket with `/request firstName lastName` and a request will automatically be sent to the Slack admins. 

Relevant info / items:
 - [GitHub Action](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/slackRemovalRequest.yml)
 - [Note added to template to inform users how to use it](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/offboarding-request.md)
 - [Example of usage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15524)
