### ISSUE TITLE
Ensure that vets.gov cert is renewed and certificates are properly installed on all endpoints

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14711]
## Issue Description
_The *.vets.gov public cert is expiring Nov 12._

---
## Tasks
- [ ] _Ensure that the public certificate is renewed_
- [ ] _Ensure that the public certificate is shared with parties so that it is properly installed on public facing endpoints

## Acceptance Criteria
- [ ] _The certificate is properly renewed_
- [ ] _The certificate is shared to teams that will install it on endpoints_
- [ ] _There is no interruption of service_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
@tskinn - please add any additional relevant notes here as needed. especially, can you include information relating to the teams that we need to pass the certificate to, and relevant endpoints that it needs to be installed on?
