### ISSUE TITLE
Letters: Empty State

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14720]
## User Story 
As a user, if I have no VA letters or documents, I will see a message saying that. 

## Tasks
- [x] Identify test account with no letters, pull content from there 
- [x] High fidelity prototype of screens in iOS
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

## Assumptions

**Ideal UX**
Ideally, I would like to check for letters when a user clicks into "VA Letters and Document" from the Profile menu. That way a user wouldn't get hit with the check your mailing address flow only to find there are no letters.

**Ok for MVP**
If this is not possible, it's fine to serve up this screen only after a user has hit the 'View Letters' CTA on [this screen](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/431636878).
