### ISSUE TITLE
Improve Lighthouse Developer IAM Group Policy

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14736]
## Issue Description
Mike Lumetta discovered need for additional permissions within AWS. This sparked a conversation with Gabriel Olavarria who then worked with Tom Dugan to create an improved permission set that all general Lighthouse Developers (meaning not just privileged users) will need.

Requested additional permissions:

```
### CodeBuild:
* List all
* Read all
* RetryBuild
* StartBuild
* StopBuild
* UpdateProject
​
### IAM
​
iam:PassRole
​
### ECR
* All describe actions
* All Get actions
* All List actions
* All Start actions
​
### ECS
* All describe actions
* All List actions
* RegisterTaskDefinition
* RunTask
* StartTask
* StopTask
* UpdateContainerInstancesState
```

---
## Tasks
- [x] Improve upon the existing `lighthouse-developers` [IAM group](https://console.amazonaws-us-gov.com/iam/home?region=us-gov-west-1#/groups/lighthouse-developers) to include the additional permissions requested. 

## Acceptance Criteria
- [x] All Lighthouse Developers have the permissions required to complete daily tasks and functions.
- [x] Relates to / will close: #14139

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
This is possibly being addresses by work that @jsev-io is already doing with IAM cleanup. Please add additional info as needed.

**Comment by jsev-io** [comment]
Mike Lumetta Confirmed he could access as expected. Closing this issue.

**Comment by jhouse-solvd** [comment]
@jsev-io or @jbritt1 - there is one task and one acceptance criteria not yet checked above. can we either check those off, remove if irrelevant, or re-scope to make clear and then check off? then, I will go ahead and close this one out.

**Comment by dginther** [comment]
comments in the ticket indicate that the task and acceptance criteria can be checked. checked them, and closing.
