### ISSUE TITLE
Office of Community Care pharmacy content strategy

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14745]
## Issue Description
When a veteran searches for a Community Pharmacy (in VA's network) we want to provide a single place where a veteran can learn (or be directed) to learn about the different services they can get from a Community Pharmacy (in VA's network). OCC is looking for suggestions on how to make that happen

---
## Tasks
- [ ] Do a content audit/analysis of OCC pages with prescription content
- [ ] Put together recommendations/content guidance
- [ ] Align internally w/ facilities team
- [ ] Provide recommendations to OCC

## Acceptance Criteria
- [ ] Recommendations provided to OCC
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
