### ISSUE TITLE
Claims file upload: Upload password-protected PDF

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14749]
## User Story
As a user, I can upload a password-protected PDF to the VA mobile app from my phone and share the password with VA as part of the upload.

## Background 
Per 10/12 comment from Anna Carey: "We're going to start letting users upload password-protected PDF along with the password. We're finding that the DOD provides service treatment records by email in a password-protected pdf."

## Tasks
- [ ] Determine how common service treatment record uploads are (do we need to account for this in the app?)
- [ ] Technical discovery of password upload (where does this go? Upload API?)
- [ ] UX/UI updates

**Comment by ayushchak** [comment]
This is part of a broader claims file upload discovery required - closing ticket in favor of that one.
