### ISSUE TITLE
Analyze Interview Data 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#1474]
## User Story
As a researcher, I need to analyze the data gathered during the Conduct User Interviews Epic. 

## Goal
Organize gathered data from interview sessions into meaningful categories to gain insights that will impact the synthesis. 

## Acceptance Criteria
- [ ] _What needs to happen or be created?_
A spreadsheet needs to be created to track categorization of data. Designers need to then organize the data into meaningful categories to create themes from the sessions.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)

Sprint 1

- [ ] **Attached to an Epic** (what body of work is this a part of?)

Analyze Interview Data

- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)

VSA Caregiver

- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

Research

- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

Discovery, Documentation
