### ISSUE TITLE
Feature Discovery: Disability Rating

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14759]
# User story
As a user of the VA mobile app, I want to view my disability rating.

### Research support
User research in September 2020 supports that many users would find it valuable to view their disability rating. 2/8 users specifically asked for this and the Logged-In Homepage team is exploring including this per their research. 

> "I would add a breakdown of disabilities: current disabilities, current rating, service-connected percentage amount, and permanence." [Link to the research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/usability-testing/round-1/research-summary.md#overall-participants-were-satisfied-with-the-content-they-saw-in-our-prototype-we-got-consistent-feedback-on-what-else-participants-would-like-to-see-in-profile-past-what-we-showed).

### What we know about disability rating today
We think this lives on VA.gov now and has recently become available there. 

#### Technical
- What endpoint is this information in?
     - Can we access/use it?

#### Product & UX
- What information gets displayed for the rating (is it just a %? Or does this data point include service-connected percentage, permanence, etc in how it's displayed on VA.gov today?)
- Does the web display one overall rating, multiple ratings, or both?
- What happens if the information can't load - what does the error message look like?
- **Where** is this displayed on the web (e.g. Profile, My VA dashboard, elsewhere)? 
- Is there help content displayed with the rating (e.g. a phone number, should the rating be incorrect and the user needs help)?

# Tasks
- [ ] UX/product discovery
- [ ] Technical discovery 
- [ ] Define the scope of the feature for mobile app
- [ ] Write user stories for design work
- [ ] Write user stories for engineering work

**Comment by bridgethapner** [comment]
Not from 2/1 sync with the My VA Team: Disability rating is included in My VA 2.0 which is undergoing testing/launching soon - maybe the app replicates how My VA displays this? cc @ayushchak

**Comment by bridgethapner** [comment]
Closing this discovery-focused ticket in favor of the implementation epic just opened for Disability Rating #27397.
