### ISSUE TITLE
Design intent Collaboration - BAM2 [Debt Resolution FSR Form #5655]

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#14769]
## **We would like to request that the PM and/or SME for forms system is at this meeting as well **

10/19 3:30 ET for meeting time 

## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [ ] VSP <> **requesting team** design intent collaboration meeting completed and [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809)is updated
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to [product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/FSR-Product-Outline.md)
- [Sketches](https://app.mural.co/t/vsa8243/m/vsa8243/1602530749582/3eb0ac4ef1e9c0d6be86978a62166bd6c9db7e09)
- [10-10CG signature component](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/412943895) to reference as we discuss what standardized digital signature gathering may look like
- Lo-fi mockups

## Meeting attendees from **requesting team**
- Designer(s) (required): **Riley, Becca **
- Product Manager (optional): **Leah *
- DEPO design lead (required as applicable): **Matt*

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Crystabel will reach out as needed_

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Hi @leahkeeler the 10/20  11-11:30 time slot is currently filled. Is there another time that works best for the team? Also please attach artifacts 2 days before the meeting.

**Comment by CrystabelReiter** [comment]
Scheduled for 10/19 at 3:30 pm ET. Please make sure that artifacts are attached by tomorrow 10/15 by 3:30 pm ET. @leahkeeler @rebeccawalsh @rileyorr

**Comment by rileyorr** [comment]
Hi @CrystabelReiter! I provided links to both a Mural board our team used for an ideation workshop that contains some sketches and a signature/authorization component that the 10-10CG contains. Unfortunately, Becca has been out the past couple days and I'm trying to wrap up discovery research and create a readout deck for a stakeholder meeting tomorrow so I don't think I'll hit the 3:30 pm EST deadline for lo-fi mockups. Please let me know if that's a blocker for this meeting!

**Comment by CrystabelReiter** [comment]
@rileyorr If you feel comfortable presenting sketches and receiving feedback on them on Monday's meeting then it's totally fine. Let me know if you'd like to move the meeting in case you want to do lofi mockups as well. 

Good luck on your meeting tomorrow!

**Comment by mnorthuis** [comment]
IA Feedback:

Hey all, I have more questions than feedback as we learn more about this process and trying to determine how it relates to the actual FSR form flow versus the larger debt management/resolution flow.  Posting my questions here FYSA. Looking forward to continuing to refine this process!
- At what point do they indicate which debt they are submitting the FSR for and what type of resolution they are requesting (i.e. monthly payments, waiver, compromise, etc)?
- Is there different information needed on the FSR based on the type of debt or type of resolution they are submitting for?
- Are we saving the FSR once they submit it for reference for any additional debts, or do they need to submit a new one for each debt?
- As we think about how Veterans flow into this form, we will need to make sure we accommodate the possibility that someone lands here to resolve their health care copays and will need to direct them back.

**Comment by peggygannon** [comment]
HI, there. @rebeccawalsh @rileyorr @leahkeeler 

Content feedback on FSR design intent: 
- similar to Mikki's question on the call, will there be a question on form asking users what type of resolution they are asking for? 

- I recall there being a letter that users can write explaining in more detail why they are filing a FSR. Will this letter be included in form workflow? 

- Confirmation page content: do you have any information at this point about what happens after a user submits an FSR? I advise getting confirmation page and introduction page content into the usability mockup to be included  for user testing.

**Comment by rileyorr** [comment]
Thank you for the feedback, @mnorthuis! 

> At what point do they indicate which debt they are submitting the FSR for and what type of resolution they are requesting (i.e. monthly payments, waiver, compromise, etc)?

We're currently exploring both of those actions right now - apologies they weren't included in the initial flow. Right now we've placed "debt selection" towards the beginning of the form right after the Veteran verifies their personal info (name, SSN, DOB). I think it's important to include information about the types of debt resolution available in this section because this form isn't required for disputes, but it seems beneficial for Veterans to know their remaining monthly funds before determining the resolution option that's best for their financial situation. 

We've placed the "resolution selection" after the monthly household expenses are input, but before information about adjudicated bankruptcy. I've attached screenshots of both screens. I hope that helps! 

<img width="386" alt="Screen Shot 2020-10-22 at 11 42 46 AM" src="https://user-images.githubusercontent.com/46329147/96896660-c71bcf00-145b-11eb-9685-177fe1ae9956.png">
<img width="1179" alt="Screen Shot 2020-10-22 at 11 43 06 AM" src="https://user-images.githubusercontent.com/46329147/96896663-c71bcf00-145b-11eb-8d6c-8327a715104a.png">


> Is there different information needed on the FSR based on the type of debt or type of resolution they are submitting for?

From what we gathered while we talked to SME's, the only different information needed is additional context about the Veteran's financial situation if they're requesting a waiver or a compromise offer. The DMC calls this additional info a "letter", but line 36 in the FSR is can be used to provide that additional context. We're currently exploring a text field and the ability to attach a file. 


> Are we saving the FSR once they submit it for reference for any additional debts, or do they need to submit a new one for each debt?

On the DMC's side, FSRs are archived for up to 6 months to be applied to additional debts. I think it would be extremely helpful for us to save it for that reason. @camerontesterman is that something we'll be able to do? 

> As we think about how Veterans flow into this form, we will need to make sure we accommodate the possibility that someone lands here to resolve their health care copays and will need to direct them back.

Absolutely! I know @rebeccawalsh is working on a wizard that would redirect the Veteran if they're looking to resolve medical copayments or request a dispute.

**Comment by rileyorr** [comment]
Thanks for the feedback, @peggygannon! 

> similar to Mikki's question on the call, will there be a question on form asking users what type of resolution they are asking for?

I answered this q in my response to Mikki's feedback! Let me know if you have additional questions :) 

> I recall there being a letter that users can write explaining in more detail why they are filing a FSR. Will this letter be included in form workflow?

 Yup! I provided info about this in my response to Mikki's feedback. We're exploring a couple options with the "letter". It's basically just additional context about the Veteran's financial situation and why they're requesting a waiver/compromise. 

> Confirmation page content: do you have any information at this point about what happens after a user submits an FSR? I advise getting confirmation page and introduction page content into the usability mockup to be included for user testing.

Yup, we will absolutely have an intro and confirmation page included in the usability mockup! A few things can happen after a user submits an FSR: 
- If a user selects "yes" to the adjudicated bankruptcy question, the form is sent to a bankruptcy team that looks into the bankruptcy. DMC cannot process the form until the bankruptcy team is finished looking into the user's bankruptcy history 
- If a user selects a compromise or waiver, the form is sent to a council that processes those requests 
- Once the form is processed, DMC sends out a letter approving or denying the requested resolution
