### ISSUE TITLE
Design notifications UX

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14762]
## User Story
This story is to decide and document the following: 
- What notification types we will be able to send for MVP (assuming just appointments)
- What notification channels (push, SMS, email) will we include for MVP (assuming just push)
- What content can/should these notifications include (assuming we'll follow VEText team's notifications) 

## Assumptions
- We will not have an activity feed for MVP. Notifications will get sent to users and deep-link to the app, but they will not be stored in an activity feed that users can return to.

## Tasks
- [x] Connect with Jonathan re notifications API documentation
- [x] Determine MVP notification types
- [x] Determine MVP notification channels
- [ ] Determine MVP notification content
- [x] Determine if we want to use local notifications. If yes, where do we want to use them and what is their content. 
- [ ] Document MVP notifications UX, upload to GitHub

**Comment by bridgethapner** [comment]
Bridget + Jonathan meeting this week to discuss

**Comment by bridgethapner** [comment]
### UX of Notifications for MVP 

**We will send push notifications for:** 
- Appointment reminders

**Details of how notifications will work:**
- The interval will be controlled by VEText (either morning of or 24 hours prior, it will be off schedule from the SMS to prevent overloading users with notifications at the same time). 
- Notifications will deep-link to the relevant appointment screen.
- In the case of us sending a notification for multiple appointments coming up on the same day in the same clinic, the notification will deep-link to the appointments overview screen.

**Notification content:**
This is up to us to write and we want to keep it general and free of PII. We see a couple scenarios that will need different text:
1. Single appointment
2. Multiple appointments

**User control:** 
We will include a toggle to turn notifications on/off in **Settings**.

### Still to-do here for UX work (Bridget to pick up w/o 11/30): 
1. Write content for notifications
2. Add Notifications on/off toggle to Settings page

**Comment by bridgethapner** [comment]
Just getting back to this ticket. 

**Content idea:** 
- Single appointment: "Your VA appointment is coming up soon" 
- Multiple appointments: "Your VA appointments are coming up soon"

**Comment by bridgethapner** [comment]
Opened #17331 to handle the last piece -- the copy writing for notifications, closing this ticket.
