### ISSUE TITLE
Learning Center MVP 1.0 x Staging Review Accessibility Checklist

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14774]
## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [x] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - Conduct axe browser scan, and document or address issues found
  - [x] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [x] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
  - [x] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [x] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [x] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- [x] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [x]  [Learning Center Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10953)

**Comment by ncksllvn** [comment]
Axe scans will be conducted across all of these pages during regular development as part of our Continuous Integration (CI). I ran the tests on my local machine a bit ago on every LC page, and it didn't produce any issues. We've been paying close to attention to the blue bar that shows at the top of the screen when there are accessibility issues found during a page preview, and the LC search was designed to be efficient with screen readers as well with some of our takeaways from Find Forms and Yellow Ribbon.

**Comment by jenstrickland** [comment]
Thanks, @ncksllvn! Do you know if your e2e tests open all hidden content, for example the accordions, and then run the axe scans?

**Comment by ncksllvn** [comment]
> Thanks, @ncksllvn! Do you know if your e2e tests open all hidden content, for example the accordions, and then run the axe scans?

They don't 😞 But off the top of my head, I don't think we have any accordions 🤔 We have support for accordions on the articles of type "FAQs" (a list of QAs) but last I checked no articles had the accordion-display enabled

**Comment by jenstrickland** [comment]
This would be a good thing to raise with Trevor. It is part of VSP's requirements for axe checks in the e2e tests. He can probably advise how to implement it.

**Comment by brianalloyd** [comment]
@ncksllvn and @jenstrickland based on staging review this looks to be complete, can I go ahead and close this out in support?

**Comment by jenstrickland** [comment]
@brianalloyd I agree this can be closed, although I do ask that the team connect with @1Copenut for guidance on ensuring all accordions and other hidden content are unhidden and axe scans run on them in the e2e tests.
