### ISSUE TITLE
Modify addressUI to allow validation to not validate on state when state is not required

### ISSUE THREAD

**Issue by jgacek** [department-of-veterans-affairs/va.gov-team#14773]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
I want to be able to leave state as blank even while country is required. AddressUI is being used which is defined in the vets-website repo at ```src/platform/forms/definitions/address.js```. Below are some screenshots showing the specific problem being tackled
<img width="494" alt="Screen Shot 2020-10-13 at 12 35 31 PM" src="https://user-images.githubusercontent.com/9095250/95911249-db2e4500-0d66-11eb-8fe6-77f07ed43b5d.png">
<img width="520" alt="Screen Shot 2020-10-13 at 12 35 44 PM" src="https://user-images.githubusercontent.com/9095250/95911269-e2ede980-0d66-11eb-8e22-d0cdaba09b36.png">

## Tasks
- [ ] _What work is necessary for this story to be completed?_

- [ ] Remove validation from state when state is not required

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

- [ ] When country is required but state is not required then state should not be validated
- [ ] When other address fields (City, Street, Zip) have input then they should still be validated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`frontend`)
- [ ] **Labeled with Type** (`request`)
