### ISSUE TITLE
[CONSIDER] Add filter to allow Veteran to specify radius: Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14789]
## Issue Description
As a Veteran, I need to be able to define the area I want to search so that the results are relevant to my location. 

---
## Tasks (TBD based on design prototype)
- [ ] Add mileage filter based on design prototypes
- [ ] Ensure max radius for any facility type search = 250 miles. 

## Acceptance Criteria (TBD based on design prototype)
- [ ] Veteran can use filter to limit search parameters.
- [ ] Veteran can specify mileage between x and 250 miles. 
- [ ] Results for search conform to search parameters

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@thejordanwood I know this was already a factor you looked at

**Comment by jilladams** [comment]
Parent epic is closed, FL is now ticketed in va.gov-team repo. Closing orphaned tickets, as we are iterating FL separately.
