### ISSUE TITLE
Upgrade to Mapbox GL JS

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14786]
## Issue Description
Switching Mapbox to GL JS library in tandem with the other map behavior changes we want to make will allow us to maintain Facility Locator functionality, give access to accessibility plug-ins, and implement planned enhancements more permanently. 

---

## Tasks
- [ ] Update to GL JS library
- [ ] Create method to restrict from Prod
- [ ] Test in review instance

## Acceptance Criteria

Following existing functionality will be maintained
- [ ] Search within existing parameters is successful, including return of no results
- [ ] Pins for locations
- [ ] "I am here" indicator
- [ ] Uses existing 80 mile bounding box

---

- [ ] Performance within acceptable parameters
- [ ] Mobile experience maintained
- [ ] Changes are restricted from Prod
- [ ] FL does not autosearch if not results are found within 80 miles 

This is 13 level of effort which cannot be broken into smaller tasks

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
