### ISSUE TITLE
Decrease initial zoom radius 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14792]
## Issue Description
As a Veteran, I want the initial search results to be presented within an hour's drive so that I can find the closest appropriate location for my needs. 

---
## Tasks
- [ ] Decrease initial zoom radius from 80 miles to ~40 miles (translated into zoom level = ~9)

## Acceptance Criteria
- [ ] For any facility type, the initial search results returned conform to a 40 mile radius. 
- [ ] When the facility search does not return results within 40 mile radius, the appropriate error message is displayed. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Decided to hold this change due to unintended consequences. Reducing the initial zoom benefited searches with high number of locations in small area (such as pharmacies). However, we identified a bug which caused the number of locations between results list to be different from those displayed on the map. Determined a better solution will be to fit the zoom to bounds, which we will implement after the mapbox upgrade.
