### ISSUE TITLE
Implement second chunk of acct and profile content in drupal

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14791]
## Issue Description
Content needs to be placed in R&S templates for MVP 1.0.
---
## Tasks
- [x] Use the content in this Word doc and enter it into the templates.

[https://app.zenhub.com/files/133843125/1a8e7407-d8b7-4275-a552-b4304f3aee72/download](https://app.zenhub.com/files/133843125/1a8e7407-d8b7-4275-a552-b4304f3aee72/download)

**Note:** All components are not present yet, like related info and buttons, but I did try out some related info so we can see how it works when rendered in preview. 

**Randi:** There are some step by step articles for you to create with this chunk of the content. You'll see where I've indicated that.

## Acceptance Criteria
- [x] Content uploaded into Drupal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
I have entered the content into Drupal. Here are the node links and additional notes.

**How do I change my address on file with VA?:** https://prod.cms.va.gov/node/8416 The related info (link to step-by-step node) needs to be added. 

**Direct deposit:** http://preview-prod.vfs.va.gov/preview?nodeId=8423

- What’s direct deposit?: https://prod.cms.va.gov/node/8418
- What if I don’t have a bank account, but I want to use direct deposit?: https://prod.cms.va.gov/node/8419
- How do I change my VA direct deposit information?: https://prod.cms.va.gov/node/8420 links need to be added to step-by-step nodes

**Connected Apps:** http://preview-prod.vfs.va.gov/preview?nodeId=8471

- What are connected apps and why might I want to use them?: https://prod.cms.va.gov/node/8421
- How are connected apps different from My HealtheVet or VA mobile apps?: https://prod.cms.va.gov/node/8422
- What third-party apps can I connect to my profile?: https://prod.cms.va.gov/node/8424
- How do I connect an app to my VA.gov profile?: https://prod.cms.va.gov/node/8428
- I don’t have a smartphone. Do I need one?: https://prod.cms.va.gov/node/8425
- What should I do if my records in an app are wrong or out of date?: https://prod.cms.va.gov/node/8426
- Can I stop sharing my VA information with an app?: https://prod.cms.va.gov/node/8429

**Comment by RLHecht** [comment]
I've built the article for the phone numbers list: preview-prod.vfs.va.gov/preview?nodeId=8427

- We need button text and a link
- I changed the header to a non-question but not sure if what I have is good.
-  I added a line of text above the table, which was required, but I didn't put a header for the table. 
- I went with the default info for the contact info and benefit hubs

**Comment by RLHecht** [comment]
Address step-by-step node: preview-prod.vfs.va.gov/preview?nodeId=8417

**Comment by RLHecht** [comment]
Laura's step by steps: 

Steps to changing your VA education direct deposit information preview-prod.vfs.va.gov/preview?nodeId=8474
Steps to changing your VA disability or pension direct deposit info preview-prod.vfs.va.gov/preview?nodeId=8434

**Comment by RLHecht** [comment]
The work in this ticket is now complete. List of nodes are in ticket #14979 for adding related info and buttons. Closing ticket.
