### ISSUE TITLE
Add Cerner react widgets to Drupal health tool pages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14816]
## Issue Description
We need to add the Cerner react widgets to the Drupal health tool pages to get ready for the 10/24 go-live.

---
## Tasks
- [x] Add react widget to Refill prescriptions
- [x] Add react widget to Secure messaging
- [x] Add react widget to View lab and test results
- [x] Add react widget to Get your VA medical records online

- [x] Validate in CMS & publish Refill prescriptions
- [x] Validate in CMS & publish Secure messaging
- [x] Validate in CMS & publish View lab and test results
- [x] Validate in CMS & publish Get your VA medical records online

## Acceptance Criteria
- [ ] Content changes live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic @ncksllvn. Could you confirm the names of each of the 3 react widgets to add to these pages? Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @kelsonic! Also, question since it's been a while since we did this for the schedule appts page: If we publish these pages with the react widget today, all users will just see the unauthenticated version, correct? So basically, we won't mess anything up if we publish, right?

**Comment by kelsonic** [comment]
That's correct, on production they are set to false which means they will see the legacy content:

![image](https://user-images.githubusercontent.com/12773166/96004929-33ae2280-0df9-11eb-939c-140fdbefb691.png)

![image](https://user-images.githubusercontent.com/12773166/96005095-5b9d8600-0df9-11eb-8ea5-a4acda55065b.png)

**Comment by DanielleThierryUSDSVA** [comment]
excellent - thank you @kelsonic !!

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Would you mind reviewing these pages for me and just confirming that all looks good before I publish?

They should all now be structured similar to this page, in that they have the intro text and then everything else is replaced by the page's respective react widget (as listed above): https://prod.cms.va.gov/health-care/schedule-view-va-appointments

**Pages to review:**

- https://prod.cms.va.gov/health-care/get-medical-records
- https://prod.cms.va.gov/health-care/refill-track-prescriptions
- https://prod.cms.va.gov/health-care/secure-messaging
- https://prod.cms.va.gov/health-care/view-test-and-lab-results

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA These have all been reviewed and published. As discussed on slack we can follow up with another ticket for small content fixes.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @kelsonic. I checked these on the live site and looks like content is now appearing as react widgets so we should be good here.
