### ISSUE TITLE
Limit Facility Locator searches to 500 mile radius

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14819]
## Product Outline
[Product Brief - WIP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/map-enhancements/phase-1-limit-search-to-250-miles/product-brief.md)

## Issue description
PPMS will be limiting the search distance with an update expected 11/5/2020. 

## Goals

1. Veterans can find a Community care provider beyond the limit of the original search parameters 
2. User satisfaction increases
3. Veteran understands how search parameters impact results

## OKR
Key Result: Veterans can find a Community care provider beyond the limit of the original search parameters 

## Solution - overview of approach
 
1. Update Mapbox to JS GL and layer on the following enhancements [#14786]
2. Turn off auto-zoom [#12710]
   -  Limit all facility searches to 500 miles 
   -  Update the center point automatically based on user changes
3. ~Decrease initial zoom radius from 80 miles to 40 miles [#14792]~
   Optimize map view [#13299](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13299)
4. Create search UX wireframes [#14818]
5. Finalize search UX design [#14867]
6. ~Add filter to allow Veteran to specify radius [#14789]~
7. ~Add some sort of visual indicator of search area [#14795]~

## Issues to create within this Epic
- [x] **[Define] Kickoff-Intent** - [#14874](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14874)
- [x] **[Define] Design intent** - [#15072](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15062)
- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
  - [ ] Create research plan and conversation guide - #(ticket)
  - [ ] Conduct research - #(ticket)
  - [ ] Research synthesis/read-out - #(ticket)
- [ ]  ~**[Discover] IA Request** - #(ticket)~
- [x] **[Discover] Analytics Request** - [#14969](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14969)
- [x] **[Build] Contact Center Review** - [#17718](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17718)
- [x] ~**[Build] Privacy/Security Review**~ [#190](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/190)
- [x] **[Build] Pre-Staging Review activities**
  - [x] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=staging-review-accessibility-checklist.md&title=%3CInitiative%3E+x+Staging+Accessibility+Checklist) - #(ticket)
  - [x] Compile QA test cases - #(ticket)
  - [x] Release plan - #(ticket)
  - [x] Submit QA test plan request - #(ticket)
- [x] **[Build] Staging Review** - [#16921 (https://github.com/department-of-veterans-affairs/va.gov-team/issues/16921)
  - [x] Resolve Staging Review findings - #(tickets)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
  - [ ] Complete accessibility checklist in Prod - #(ticket if necessary)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
