### ISSUE TITLE
[BUG] - View Payments - Page numbers do not show up in pagination

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14810]
## Story
As a Veteran or general user of VA.gov, I want to be able to see where all the payments I have received or had returned, so that I can know exactly where I stand with those payments.

## Considerations
- This might get rolled into another part of the site's IA as larger financial features are bubbled up
- PR process might have more people involved depending on where this needs to merge in

## Screenshots
![Screen Shot 2020-10-14 at 9 58 51 AM](https://user-images.githubusercontent.com/15097156/95999960-66a9e380-0e04-11eb-8417-4d1d632ccea4.png)

## Tasks
- [x] Adjust the payment pagination to reflect the pages accurately
- [x] Adjust the display amount from 5 rows to 6 

## Acceptance Criteria
- [x] The pagination correctly conveys what page the Veteran is on
- [x] The number of rows shown is 6 per page
- [x] A PR has been requested for merging

**Post Launch:** Consider allowing the user to pick how many rows per page are shown

**Comment by jason-gcio** [comment]
note: what does it look like when there is payment history but no returned payments? Need screenshot
