### ISSUE TITLE
[DESIGN] Create search UX wireframes (Facility Locator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14818]
## Issue Description
Changes to the Facility Locator will
1. Limit the search distance to a maximum of 250 miles 
2. Decrease the initial default search radius from 80 miles to 40 miles. 

As a result, we need to adjust the search experience. 

## Problems to be solved
Determine the Veteran experience for the following scenarios

**Scenario 1**
No results are found within ~40 mile initial search 

**Scenario 2**
After receiving results of initial search, the Veteran wants to adjust the center point or zoom level of the map. (No adjustment to facility/service type)

## Goals
The Veteran understands the outcome of the search in the context of the search area.
The Veteran can adjust centerpoint of the map via search box and/or map interaction
The Veteran has an accessible way to adjust zoom level (via search box and/or map interaction)
The Veteran has a way to initiate search after adjusting search area (not facility/service type)

---
## Tasks

- [x] Review design system for relevant components
- [x] Consult with Ryan for relevant content across VA.gov
- [x] Create lo-fi wireframes for use in Collab cycle review and team discussion

## Acceptance Criteria      
Lo-fi wireframes include
- [x] Mobile and desktop 
- [x] Interactions/expected behavior
- [x] Appropriate error messaging

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrisdlogan** [comment]
I have uploaded lo-fi wireframes to address future versions of the map where results don't automatically update without Veterans' expressed intent. Also, I have included what could be a temporary fix for allowing Veterans who use screen readers to control the zoom function. This may not be necessary if we are updating the map soon, but I felt it was worth exploring and sharing out to the team. 

Lastly, I have included a Search box layout exploration which re-aligns all the UI elements into one row. I'm not sure if this is feasible from a development standpoint but thought I would share. Let me know if anyone would like me to set up time to walk through these - otherwise feel free to review and send me feedback and suggestions. 

**Wireframes added for review**
- Provide Veterans a way to control how search results are updated in Facilities map for desktop
[Facilities Map Update Issue - Desktop.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5418551/Facilities.Map.Update.Issue.-.Desktop.pdf)
- Provide Veterans a way to control how search results are updated in Facilities map for mobile
[Facilities Map Update Issue - Mobile.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5418560/Facilities.Map.Update.Issue.-.Mobile.pdf)
- Provide an alternative way to zoom in and out of map by use of a selector for desktop
[Search Distance Selector - Desktop.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5418563/Search.Distance.Selector.-.Desktop.pdf)
- Exploration for how to decrease height of search box for desktop
[Realign Search Box UI - Desktop.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5418569/Realign.Search.Box.UI.-.Desktop.pdf)
