### ISSUE TITLE
Design intent Collaboration - AuthXp [Direct Deposit for Edu Benefits]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#14824]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [ ] VSP <> **requesting team** design intent collaboration meeting completed and [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809)is updated
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product outline [Direct Deposit for Edu Procuct Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md)
- [Discovery docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/edu-dd-discovery.md)
- [Mockups](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/)

## Meeting attendees from **requesting team**
- Designer(s) (required): **Jim Adams**
- Product Manager (optional): **Matt Shea**
- DEPO design lead (required as applicable): **Samara Strauss**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite

## ** Preferred time**
Monday, 10/19 at 3:30pm

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by mshea0606** [comment]
@mshea0606

**Comment by CrystabelReiter** [comment]
Scheduled for Friday at 2pm ET. @mshea0606 do we mean Jim Adams and not Jim Allen?

**Comment by jenstrickland** [comment]
The Discovery Docs link above returns a 404. Are there discovery documents to review?

**Comment by shiragoodman** [comment]
@sporeboy can you please fix the link for the Discovery Docs?

**Comment by sporeboy** [comment]
Apologies for the delay. I fixed the link above. The discovery doc is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/edu-dd-discovery.md

**Comment by mnorthuis** [comment]
No IA feedback at this time.  Just a friendly reminder to connect with the Public Websites team on the static landing page for direct deposit (https://www.va.gov/change-direct-deposit/) to ensure the content and link into profile is updated for education.   They are also working on moving some content over to Resources and support (formerly known as Learning Center), so a timing conversation may be helpful.  Thank you!

**Comment by jenstrickland** [comment]
**VSA Accessibility Feedback**

Great job on the Discovery doc! I love how you included the screenshots of the existing solution.

Comments provided in the AdobeXD prototype. Please let me know if anything needs discussion or more detail.

Regarding the alt text for the check, would you please share that with me so I can check to see if it follows best practices?

cc @1Copenut for VSP review

**Comment by CrystabelReiter** [comment]
Since everyone is posting their feedback on this ticket, design will do the same! 

All these pieces of feedback are in the consider category: 
- Consider automatically opening the additional info component with the check image when a user is first adding their DD info, close up additional info component when the user is going back to update. 
- Consider for the account dropdown, to use radio buttons since it’s less than 5 options
- Consider adding a black round checkmark icon to the light green background alert “Your bank account information for ...benefits has been updated” (Note: if it doesn’t have a checkmark anywhere else in the profile, you can disregard this feedback)

Thanks and great work~

**Comment by 1Copenut** [comment]
@jenstrickland Feedback looks great. I added 3 small consideration items.

**Comment by Samara-Strauss** [comment]
This was completed months ago. Closing.
