### ISSUE TITLE
More VA.gov Links for Outreach and Events page from VEO

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#14826]
## Why you're here 
VEO has requested that DEPO provide steps for driving additional visibility, usage and utility to/on the VA.gov [Outreach & Events page](https://www.va.gov/outreach-and-events/events/).

### Content and IA support for:
- Unauthenticated (static) VA.gov pages
- Possibly, global nav (e.g. Footer, Top Nav)

### Engineering support for:
- Implementation of agreed upon solution (e.g. site links to page)

## About your request

While there a host of potential solutions to addressing this perceived issue, this ticket outlines what we will tackle in order of priority and level of effort, with desired timing:

- Q4 2020

  - [ ] Link to Outreach and Events page from the VA.gov global footer and/or the About VA mega menu.   This will require input from @mnorthuis ]

- Q1/Q2 2021

  - [ ] Enhancements to the Outreach and Events page -- e.g. filter events, on-page search, etc.  (requires input from @mnorthuis and @DanielleThierryUSDSVA)

## Background

On October 6, 2020, Chris Johnston shared background communication he had with the VA stakeholder Melissa Rebstocks of VEO regarding this request. 

**Problem 1: Not enough people register for events**
Potential cause: Too few people visit the events page

- Google analytics last month indicates that this page sees about 6,500 unique visitors per day on average. (This is much higher than I would have expected.) That traffic is sporadic, indicating that it is generated, as expected, by outbound marketing activity, where traffic spikes a day or two and then settles back down to about 1,000 per day.

- Potential solutions include:

- Make the page more visible on VA.gov (suggestion below)

  - Add events from local medical centers to the national events page (suggestion below – this might be complicated due to the different CMS’s used)
  - Increase and improve outbound marketing activity (more frequent posts, sharing via FB, Twitter, and Instagram, etc.)
  - Improve onsite and offsite search
    - For onsite search, the Outreach and Events page is already featured as a Best Bet (updated in Sept. 2020)
    - For offsite search, the page is a top result in Google Search

<img width="702" alt="Screen Shot 2020-10-14 at 9 58 17 AM" src="https://user-images.githubusercontent.com/63107147/96009914-3582e080-0e0f-11eb-8e7f-3142e0727be6.png">

- Potential success measures:
   - Increase event registration increases by or to X
   - Increase traffic to the page increases by or to X

**Problem 2: Users can not find a relevant event**

With fewer than two dozen events on 2 pages, this seems an unlikely problem, and many of the suggestions below are overkill, given the volume. I would suggest doing some user research on this topic that includes the common user funnel and what we expect people to do.

- Potential solutions:
  - Add filters (the suggestion below)
  - Provide on-page search

- Success measures:
   - Increased registration (?)

**Problem 3: Users are confused about when an event occurs**

Question: is there evidence to support this?

- Suggested solutions:
  - Add All time zones (not a UX best practice)
  - List each day for multi-day events

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

- [x] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * VA.gov [Outreach & Events page](https://www.va.gov/outreach-and-events/events/)
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * < list of new info >
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * < list of new info >

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

- Q4, 2020 for footer and/or global nav change
- Q1/2, 2021 for any changes to the Outreach & Events page

* <Desired/target implementation date>

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Public Websites
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: Liz Lantz
- FE engineer: Nick Sullivan/Kelson Adams
- Product/team Slack channel: #vsa-public-websites
--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by johnhashva** [comment]
Note: Ticket for IA and placement in global nav here #14468

**Comment by johnhashva** [comment]
Closing this ticket as it is redundant to #14468
