### ISSUE TITLE
Draft KPI tracking template

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#14834]
## Issue Description
Draft a template for tracking VFS KPIs by product.

---
## Tasks
- [ ] Create draft
- [ ] See if we can connect it to Domo
- [ ] Run by leadership

## Acceptance Criteria
- [ ] We have an MVP tracker where it's easy to update & see which VFS teams need to set or update KPIs.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
https://docs.google.com/spreadsheets/d/1jyIxQAystapzDZ8gRkN4yBtruUsnRKvpjovLatHwgr4/edit#gid=0
