### ISSUE TITLE
Verify Collab Cycle review GitHub templates are up to date and accurate.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#14831]
## Issue Description
The templates used by VFS teams to request Collaboration Cycle reviews may include incorrect names, tag the wrong people, apply incorrect labels and/or be added to the wrong pipeline. The templates need to be updated to reflect the correct information.

---
## Tasks
Complete review of the following templates:
- [x] [Project Kickoff ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=product+support%2C+content-ia-team%2C+collaboration-cycle&template=project-kickoff.md&title=Project+Kickoff+%5BFeature-Name%5D)issue template
- [x] [Design Intent Collaboration](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+crystabelreiter%2C+emilywaggoner&labels=product+support%2C+collaboration-cycle&template=design-intent-collaboration.md&title=Design+intent+Collaboration+%5BFeature-Name%5D) issue template
- [x] [Usability Testing Prep](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=product+support%2C+content-ia-team%2C+collaboration-cycle&template=usability-testing-prep.md&title=Usability+Testing+Prep+%5BFeature-Name%5D) issue template
- [x] [IA Request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+meganhkelley%2C+mnorthuis&labels=product+support%2C+content-ia-team&template=ia-request.md&title=IA+Request+%5BFeature-Name%5D)issue template
- [x] [Analytics Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+jonwehausen%2C+nedierecel&labels=analytics-insights%2C+analytics-request&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BProduct%5D) issue template
- [x] [Contact Center Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Kimberley+Daniels%2C+Chante+LantosSwett&labels=contact+center%2C+analytics-insights%2C+analytics-request%2C+collaboration+cycle&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTool%5D) issue template
- [x] [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+Shiragoodman&labels=product+support%2C+content-ia-team%2C+collaboration-cycle%2C+staging-review&template=staging-review.md&title=Staging+Review+%5BFeature-Name%5D) issue template
- [x] [Privacy and Security Review](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=gunsch%2C+f1337&labels=product+support%2C+collaboration-cycle&template=privacy-and-security-review.md&title=Privacy+and+Security+Review+%5BFeature-Name%5D) issue template
- [x] [Full Accessibility and 508 Office Audit](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+jenstrickland&labels=508%2FAccessibility%2C+product+support&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BFeature-Name%5D) issue template

## Acceptance Criteria
When VFS teams use these templates:
- [x] The correct labels are applied - "vsp-product-support" "collab-cycle-review"
- [x] The correct people are assigned.
- [x] The title is updated to include team name and feature name.
- [x] The language in the template is correct and references the right people.
- [ ] The new issue is added to the correct pipeline.
- [x] The Collaboration Cycle markdown file is updated to link to the right template.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
possibly create a new label for collab cycle review meetings (and apply to all templates) so they are easily located/filtered within zenhub

**Comment by shiragoodman** [comment]
@1Copenut I'd like your assistance updating the Full Accessibility and 508 Office Audit issue template. Let me know when you have 5 min.
