### ISSUE TITLE
Adjust Name Display Logic on CH36 Confirmation Page

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#14856]
## Background
Currently on the confirmation page at the end of the CH36 form, we are trying to display the name of the veteran that the form was for.  Currently, we have logic there to show the veteran's name if they are not logged in or the claimant's name if they are not logged in but we need to add logic to handle if the user is logged in. 

This means grabbing the profile data from Redux, which we are already using on this page, and displaying the name from there If the user is logged in.

## Tasks
- [x] Add logic that uses the redux to tell if the user is logged in
- [x] If the user is logged in, pull the name from the profile object in redux for the confirmation page
- [x] Submit a PR for review

## Acceptance criteria
- [x] The correct name is always displayed on the confirmation page for all workflow scenarios on CH36
- [x] A PR has been submitted for review

**Comment by micahchiang** [comment]
Completed in this PR - https://github.com/department-of-veterans-affairs/vets-website/pull/14931/files#diff-cd5b49960339bb98ae019c78f3b300baab48af3a6f04cd2a17acf5cbec4d7a9bR29
