### ISSUE TITLE
[FE] Review Page - Showing and Hiding data that is not present

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#14861]
## User Story
- As a veteran, I should only see the appropriate data on the Review screen and know what needed data is missing so I can update and address the missing data if needed

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Feedback from ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13159)

## Description
On the review page, for demographics, what details should be shown when they are empty, and what details are hidden when they are empty. 

## Tasks
- [ ] Hide fields that should be hidden
- [ ] Always should fields that should be shown.
- [ ] Update e2e tests 
- [ ] Update Unit tests

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe.
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by kristenmcconnell** [comment]
@mdewey I had this thread going on in the #design channel about what to show and what to hide: https://dsva.slack.com/archives/C0NGDDXME/p1602695524082800

Ryan Thurwell's answer was probably the most applicable response. 
![Screen Shot 2020-10-15 at 2 35 57 PM](https://user-images.githubusercontent.com/66287082/96172032-c7fcb000-0ef3-11eb-9b7b-8621adbb0952.png)

**Comment by kristenmcconnell** [comment]
@mdewey After reviewing the Slack thread that I mentioned in my last comment as well as checking with some designers, we should display the label. Therefore, we would still show the label "Home phone" if we didn't actually have a home phone number to display.

**Comment by julieadair1** [comment]
@mdewey , @kristenmcconnell - is this something that still needs to be addressed?
cc: @jparker0425

**Comment by kristenmcconnell** [comment]
@julieadair1 We will need this when health questionnaires are added to the pre-check-in workflow and the forms get longer. Then, we will have to add a review page and take this into account. It was from previous health questionnaires work, but will still be applicable. I'm not sure if platform will feel that we need a review page now that I think of it. Last time I talked to Ryan, he didn't think we did, since our form was so short.
