### ISSUE TITLE
[DESIGN] Search UX (250 mile limitation)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14867]
## Issue Description
Finalize search UX design based on Collab cycle and team feedback on [wireframes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14818) 

---
## Tasks
- [ ] Finalize new search experience design to solve the problems from scenarios: 
**Scenario 1:** No results are found within ~40 mile initial search
**Scenario 2:** After receiving results of initial search, the Veteran wants to adjust the center point or zoom level of the map. (No adjustment to facility/service type)
- [ ] Incorporate feedback from Collab cycle and team review

## Acceptance Criteria
"Ready to build" design specs which include details/requirements for
- [ ] mobile
- [ ] desktop 
- [ ] font 
- [ ] color palette
- [ ] spacing/padding
- [ ] reference to design system component, as appropriate
- [ ] active and focus states
- [ ] relevant accessibility considerations 
- [ ] expected interaction/behaviors

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
