### ISSUE TITLE
 Migrate SAML Proxy project to Sentry 10 

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14863]
## Issue Description
https://github.com/department-of-veterans-affairs/vets-saml-proxy/tree/master/saml-proxy

The [SAML Proxy](http://sentry.vfs.va.gov/vets-gov/saml-proxy/) lives in Sentry 9. We need to reach out to the teams responsible for the sections listed below to ensure they are still needed and the plan to move it to the new Sentry.

- If they want to use Sentry 10 we'll need to migrate their projects
- This could include code changes in their repo, might not be 1:1 w/ `vets-api` 
- Will require configuration of `environment` setting as well `SENTRY_ENVIRONMENT=$environment`
- Where $environment is one of `'development', 'staging', 'sandbox', 'production'`
- `revproxy` `proxy_pass` needs updating for the React-like apps, see [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_developer_server.conf.j2)

---
## Tasks
- [ ] Update `SENTRY_DSN` configuration for project
- [ ] Add `SENTRY_CURRENT_ENV` configuration for project with current environment string
- [ ] Update [dev revproxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-dev.yml#L44) to point to `sentry10-internal` domain
- [ ] Update [staging revproxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-staging.yml#L44) to point to `sentry10-internal` domain
- [ ] Update [sandbox revproxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-sandbox.yml#L44) to point to `sentry10-internal` domain
- [ ] Update [prod revproxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-prod.yml#L44) to point to `sentry10-internal` domain
- [ ] Redeploy [revproxy](http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-staging/) in all environments to push changes

## Acceptance Criteria
- [ ] Errors are visible from SAML Proxy in [Sentry 10](http://sentry10.vfs.va.gov/organizations/vsp/projects/saml-proxy/)
---
## How to configure this issue
- [ ] ~**Attached to a Milestone** (when will this be completed?)~
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
## 2020-10-27

This will likely require some help from the Lighthouse team, I'm not entirely sure where the environment variables are set from looking at the existing deploy configuration.

**Comment by kfrz** [comment]
Next step, getting Slack configuration back in action for this team's projects.
