### ISSUE TITLE
[UI] Update Design Based Upon Usability Test Results

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#14865]
## User Story
> As a veteran I need to complete the upcoming appointment questionnaire. 

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
> Update [wireframes](https://zpl.io/VOOek8j) based upon the MVP usability test
> Discuss changes with the team

## Tasks
- [x] Update [wireframes](https://zpl.io/VOOek8j) in Sketch and Zeplin
- [x] Finalize documentation and comments for engineering in Zeplin.
- [x] Meet with product and engineering
- [x] Update relevant documentations with links to mockups

## Acceptance Criteria
> when is the ticket done 
- [x] FE Engineer has signed off on feature
- [x] Product owner/manager has signed off feature
