### ISSUE TITLE
[DISCOVERY] Mapbox Accessibility 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14872]
## Issue Description
We need to re-evaluate the accessibility defects which had been present with the leaflet implementation following the upgrade to Mapbox GL JS. 
The new version will allow us to leverage the accessibility plug-in, if necessary. 

## Relevant Accessibility Issues
- #515 
- #6104 
- #6897 
- #6158 
- #2754 
- #6911 
- #6103 

---
## Tasks
- Evaluate the new implementation with regard to the desired behavior below. 
  - If the defect is still present, determine if the accessibility plug-in will resolve the issue. 
- Investigate options for presenting [keyboard elements for interaction](https://docs.mapbox.com/mapbox-gl-js/api/handlers/#keyboardhandler)
- Evaluate options for displaying a preview of the information/search result card when a  pin selected on mobile.
- Document changes that need to be made in #16027

### Desired behavior
- [ ] When the map receives keyboard focus, each pin should be treated as a paragraph, presenting information from the result card (`aria-described by`)
- [ ] When a pin is selected, the corresponding search result card receives focus and the screenreader presents information from the result card (`aria-described by`)
- [ ] Speech input users can interact with the map controls by speaking the visible text labels ("zoom in/zoom out")
- [ ] Zoom in/zoom out buttons are styled as interactive links
- [ ] The interface can be intuitively navigated by keyboard. 
- [ ] Screen reader users can hear the attribution content separately from the map interactive controls.
- [ ] Screen reader users can interact with the relevant content on the page and easily recover from mistakenly accessing less or not relevant content (such as technology attribution links). 
- [ ] Screen reader users know what the keyboard shortcuts are to interact with the map but the information is not always displayed on the screen. 
- [ ] Mapbox attribution info is always visible (or can be toggled), rather than available only on hover
- [ ] Mapbox info is styled as interactive links
- [ ] When the button appears (after the Veteran has interacted with the map), it receives focus and is announced to screenreaders.
- [ ] Button uses the` role=alert`
- [ ] After the search is triggered by the "Search this area button", the focus moves to the subhead. 
- [ ] Following a search triggered by the "Search this area button" on mobile, the map continues to be displayed (it does not default to the list)
- [ ] When a pin is selected on the map in mobile, information about the facility is displayed

## Acceptance Criteria
- [ ] Remaining accessibility gaps and work to be done is documented in #16027

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
Closing this issue with this comment - https://dsva.slack.com/archives/C0FQSS30V/p1609256146333700?thread_ts=1609250405.330000&cid=C0FQSS30V

**Comment by mmiddaugh** [comment]
In a closer look, the plugin is not more than a javascript class that modifies styles that do not apply to our implementation. The desired behaviors of https://github.com/department-of-veterans-affairs/va.gov-team/issues/14872,  are fixable and we can groom them individually

**Comment by mmiddaugh** [comment]
- When the map receives keyboard focus, each pin should be treated as a paragraph, presenting information from the result card (aria-described by) (#515)
- When a pin is selected, the corresponding search result card receives focus and the screenreader presents information from the result card (aria-described by) (#515)
- Speech input users can interact with the map controls by speaking the visible text labels ("zoom in/zoom out") (#6104)
- Zoom in/zoom out buttons are styled as interactive links (#17963)
- The interface can be intuitively navigated by keyboard. (#17963)
- Screen reader users can hear the attribution content separately from the map interactive controls.  (#16971)
- Screen reader users can interact with the relevant content on the page and easily recover from mistakenly accessing less or not relevant content (such as technology attribution links).
- Screen reader users know what the keyboard shortcuts are to interact with the map but the information is not always displayed on the screen. (#17963)
- Mapbox attribution info is always visible (or can be toggled), rather than available only on hover (#16971)
- Mapbox info is styled as interactive links (#16971)
- When the button appears (after the Veteran has interacted with the map), it receives focus and is announced to screenreaders. (#16027)
- Button uses the role=alert (#16027)
- After the search is triggered by the "Search this area button", the focus moves to the subhead. (#16027)
- Following a search triggered by the "Search this area button" on mobile, the map continues to be displayed (it does not default to the list) (#16027)
- When a pin is selected on the map in mobile, information about the facility is displayed (#515)
