### ISSUE TITLE
IRIS Q&A: Spreadsheet

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#14877]
## Issue Description

VA provided a master spreadsheet of all IRIS Q&As. After eliminating all Q&As that were updated prior to 2015 and batching the Q&As into learning center categories, we had a working spreadsheet. We will use this spreadsheet to alert stakeholders to what IRIS Q&As were migrated and convey our reasoning for not migrating other Q&As. 

## Tasks
PW (Laura) is responsible for updating the spreadsheet and keeping it current. Latest version attached here. All requested updates list below as checklist items:

- [ ] Remove #1788 from MVP Q&A migration list, since it's outreach to help improve the MHV website.
- [ ]eBenefits lines 22-27 (DS Logon). Do not migrate. Already accounted for in account and profile section.
- [ ] eBenefits Lines 32-33 can be moved to housing tab. We'll want to cross link those to eBenefits Q&As for release 1.1.
- [ ] #1536. Don't migrate. We don't want to send Veterans to WARMS.

**Comment by bethpottsVADEPO** [comment]
Removed this from the deck, so please also note on the spreadsheet that we tossed it out:

![image](https://user-images.githubusercontent.com/66026798/96039602-c5c82200-0e1d-11eb-81dd-7e6064f19ecd.png)

**Comment by bethpottsVADEPO** [comment]
Removed this from the deck, so please note this on the spreadsheet:

![image](https://user-images.githubusercontent.com/66026798/96039849-2f483080-0e1e-11eb-8b16-d5e7e7690bba.png)

**Comment by bethpottsVADEPO** [comment]
Let's add this one to 1.1 content (I've already edited):

Single Q&A template
H1:
How can I get information about my VA benefits?

INTRO: Find out how to sign in to access your personal information and manage your benefits. Or, explore our benefit pages for general information about VA benefits. 

BUTTON: [Sign in or create an account](https://www.va.gov/?next=%2Fprofile%2F)

TAGS: ??

RELATED INFO:  (please add teaser text found on hub pages in tier 1 content)
Check your claim or appeal status https://www.va.gov/claim-or-appeal-status/ 
View your VA payment history https://www.va.gov/va-payment-history/  
Schedule and view VA appointments online https://www.va.gov/health-care/schedule-view-va-appointments/
Get medical records https://www.va.gov/health-care/get-medical-records/ 


H2: Access your personal information and manage your benefits

When you sign in to VA.gov, you can view your information in your VA.gov profile. You can also securely track and manage your VA benefits and services online. These are some of the tasks you can do:
·      Check your disability claim and appeal status ADD LINK
·      Find out how much money you have left to pay for school or training ADD LINK
·      Refill your prescriptions ADD LINK
·      Communicate with your health care team ADD LINK

If you have questions, call us at 800-827-1000. We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.

H2: Get general information about VA benefits

Explore our benefit pages:

Health care
Disability
Pension
Education and training
Records
Service member benefits
Family member benefits
Burials and memorials
Careers and employment
Housing assistance
Life insurance

Tags/categories: other topics and questions, all Veterans 

Source: IRIS 1726, split FAQ into two. Edited question.

**Comment by bethpottsVADEPO** [comment]
I have to shelve this because fact checking is proving too difficult and we don't have obvious SMEs who could verify this info. Please note this in the spreadsheet. Maybe we can add it to R&S at a later date:

H2: Military Retiree ID Card
Accordion Item 1: Does my Military Retiree ID Card ever expire?
You should update your DEERS record and Military Retiree ID Card when you become eligible for Medicare, normally at age 65. Once you update it, your new identification card will never expire.  
Other topics and questions, All Veterans 

Source: IRIS 3039. Split into two FAQs. Edited question. 

Accordion Item 2:
How do I get a Military Retiree ID Card? 
Make an appointment at your nearest identification office. Remember to bring 2 forms of government-issued identification.  
Locate your nearest identification office
Make your appointment online

Other topics and questions, All Veterans 

Source: IRIS 3039. Split into two FAQs. Edited question.

**Comment by jenniferlee-dsva** [comment]
^ fysa - I think Brian our PM would be able to verify this. (He's a veteran.) And Sandy Tadeo as well - he's a veteran.

**Comment by bethpottsVADEPO** [comment]
Thanks @jenniferlee-dsva will try them!

**Comment by bethpottsVADEPO** [comment]
Save this one for 1.1 @lwalsh617:
![image.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/cf194f48-dc3e-4437-9b92-e11733383fd2)

**Comment by bethpottsVADEPO** [comment]
eBenefits Q&As are too duplicative of DS Logon Q&As to use at this time. Post-launch we will figure out if there's enough helpful info for Veterans about eBenefits to warrant adding an article to R&S.
