### ISSUE TITLE
Remove redundant forms-system definitions

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14887]
## Issue Description
There are two definitions directories in the forms library:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/src/js/definitions/
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/definitions/

This can create confusion and inconsistency between forms using the platform-provided definitions.

---
## Tasks
- [ ] Identify the duplicate definitions
- [ ] Consolidate duplicate definitions
    - So every import of a single definition is from the same module
- [ ] Move all definitions to the same directory
    - Probably the `forms-system/`, but I'm not opinionated
- [ ] Update all imports

## Acceptance Criteria
- [ ] No definitions are duplicated
    - Unless they're subtly different, of course
- [ ] Only one definition directory exists
- [ ] All form applications are unaffected

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
