### ISSUE TITLE
Create Cypress TestRail Reporter Plugin Solution

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#14880]
## Issue Description
Information about the ongoing quality assurance efforts of VFS teams is not available through a centralized view. If we are able to collect information about the scope and execution result of automated tests into TestRail then we can begin to get a more complete picture of QA efforts by each VFS team.

---
## Tasks
- [x] _Create branch of vets-website in order to explore Cypress to TestRail reporter integrations_
- [x] _Install and configure a Cypress TestRail reporter plugin_
- [x] _Create an authentication token for the Cypress TestRail Reporter_
- [x] _Create an example of automated test suite writing execution records to TestRail test cases_

## Acceptance Criteria
- [x] _A pull request containing the installation and configuration changes to vets-website has been created_
---

**Comment by pjhill** [comment]
[Cypress-testrail-reporter](https://github.com/Vivify-Ideas/cypress-testrail-reporter) has had some recent enhancements that supports selecting a subset of available tests for a test run. It may be possible that a default install of cypress-testrail-reporter is sufficient. Previously, I thought some customizations might be necessary.

**Comment by pjhill** [comment]
Working on connecting and existing automated e2e test to a placeholder test case in TestRail. So far, the executions are not being written correctly to the test case as expected.

**Comment by shiragoodman** [comment]
@pjhill  - is this still under review or can we mark as closed?

**Comment by pjhill** [comment]
Initial implementation is done -- closing
