### ISSUE TITLE
Ansible Upgrade [2.9]

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14890]
## Issue Description
Tack-on item for the Python 3 upgrade.

---
## Tasks
- [ ] Test against Ansible v2.9
- [ ] Find and remediate issues
- [ ] Upgrade Ansible across platform

## Acceptance Criteria
- [ ] Platform using Ansible v2.9
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Closing at this time. Please see [ADR-0003](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/adr/0003-continue-leveraging-python-2.md).
