### ISSUE TITLE
Discuss with team leadership about virtual environment moving

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14899]
## Issue Description
A while back, [work was done](https://github.com/department-of-veterans-affairs/devops/pull/6054) to make the "main" virtual environment `relocatable`. This improved build/deploy times a bit as the virtual environment did not have to be recreated on every job. However, with the move to Python 3, there could easily be an argument made to use the built-in functionality of Python 3 for virtual environment creation (`python -m venv nameOfEnv`). This will essentially remove the relocatable option as that is an option in `virtualenv`, but not the built-in Python module for virtual environment creation. Need to decide which is the _most right_ / desired direction on this one. 

---
## Tasks
- [ ] Decide which path is worth the effort. Options are:
 - Keep using `virtualenv` to package one virtual environment to be pulled in / used by all subsequent jobs
 - Use the built-in functionality of Python 3 for virtual environment creation which will remove the ability to use one singular env in all jobs (meaning back to recreation of virtual env on every job)

## Acceptance Criteria
- [ ] Decision made on which path we desire
- [ ] Decision upheld by work to reflect choice made

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Closing at this time. Please see [ADR-0003](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/adr/0003-continue-leveraging-python-2.md).
