### ISSUE TITLE
Incremented Rollout of Python 3

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14893]
## Issue Description
After the completion of #14892, the rollout will arguably be safer to do in an incremented fashion. 
For example:
 - Deploy to dev, wait a day or two in order to catch anything that was not caught during manual testing, remediate.
 - Deploy to staging, wait a day or two to see if any new issues arise
 - Deploy to prod once all other environments have been deployed to and any new issues have been resolved. 

---
## Tasks
- [ ] Deploy to dev, wait, remediate any new issues
- [ ] Deploy to staging, wait, remediate any new issues
- [ ] Deploy to prod only once all other envs are "green"

## Acceptance Criteria
- [ ] Python 3 rolled out and in use by all environments
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Closing at this time. Please see [ADR-0003](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/adr/0003-continue-leveraging-python-2.md).
