### ISSUE TITLE
(DISCOVERY) Localization | Assess Google Translate Quality 

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14891]
## Issue Description
We need to assess the quality of Google Translate to determine its viability as an option.

---
## Tasks
- [ ] Assess quality via back translation
- [ ] Assess quality via BLEU score ranking (Mateo Schmidt in VHA helping with this)

## Acceptance Criteria
- [ ] Quality assessment complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SKasimow** [comment]
Hi @DanielleThierryUSDSVA - is this complete? Can I close it?


cc: @youngfreezyVA
