### ISSUE TITLE
Testing for Python 3 upgrade

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14892]
## Issue Description
Extensive testing will have to be completed in order to catch as many potential issues as possible before rollout. Python is ingrained throughout the entire platform, its pipelines, workflows, etc. This will be a significant portion of the time spent for the upgrade plan as the actual [installation of Python 3 is already taking place](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/common/base-os/tasks/amazon.yml#L129-L133). 

---
## Tasks
- [ ] Manual build, releases, deploys tested leveraging Python 3 instead of the current version (2.7)

## Acceptance Criteria
- [ ] Thorough testing completed, issues resolved, existing workflows ready to start using Python 3 instead of EOL'd version.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Closing at this time. Please see [ADR-0003](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/adr/0003-continue-leveraging-python-2.md).
