### ISSUE TITLE
Restore pharmacy CTA on Facility Locator search result cards

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14907]
## Issue Description
The pharmacy search experience was updated in [#12612](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12612) but the CTA was removed until an accurate and complete webpage becomes available. 

The recommendation for a new "Prescriptions medications and VA community care" page has been proposed to the Office of Community Care.  Once available, we will need to restore our CTA and link to the new page. 

---
## Tasks
- [ ] Restore pharmacy CTA button with label [TBD]
- [ ] Link to [URL TBD]
- [ ] Ensure CTA button receives focus when Veterans navigate by keyboard
- [ ] Ensure CTA button has accessibility handling consistent with urgent care CTA

## Acceptance Criteria

When a Veteran has entered a location and selected Community pharmacies (in VA's network) as a facility type,

- [ ] Search result cards include the [TBD] alert
- [ ] [TBD] alert links to [URL] 

When a Veteran has entered a location and Facility type = Community providers (in VA's network) + Service type = Pharmacy: Community/Retail Pharmacy,

- [ ] Search result cards include the [TBD] alert
- [ ] [TBD] alert links to [URL] 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
