### ISSUE TITLE
Create QA ROE

### ISSUE THREAD

**Issue by peterhill-oddball** [department-of-veterans-affairs/va.gov-team#1490]
## High Level User Story
As a VFS Team, I need documentation for the quality assurance process so I can create and deploy reliable software on the platform.

## Hypothesis/(es)
**If** we create appropriate rules of engagement for the QA process **then** we expect the quality of the software being deployed on the platform to increase.

## Goals
Create a robust set of documents outlining the quality assurance expectations for all teams participating in the platform.

## Objectives
**Intake & Onboarding** and **Support**

## Acceptance Criteria
- [x] QA documentation is created
- [x] Documentation is reviewed by Front end group, Rachael and Andrew G
- [x] Documentation is live on GH

**Comment by peterhill-oddball** [comment]
I've created a branch to which I am committing thoughts regarding QA ROEs -- https://github.com/department-of-veterans-affairs/va.gov-team/tree/peter-qa-practicearea
