### ISSUE TITLE
Add schema for CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#14910]
# Background
Now that we have created all the fields in the CH31 form we need to copy the schema for those fields into `vets-json-schema`.

## Considerations
- Meet with BE as well

## Tasks
- [ ] Build out for fields for CH31 form in `vets-json-schema`
- [ ] Bump version number in package.json in `vets-json-schema`
- [ ] Update commit hash in package.json in `vets-website`
- [ ] change the commit hash in `vets-website`
- [ ] Run `bundle update vets_json_schema` in `vets-api`
- [ ] Submit PR to `vets-api` for review

## Acceptance Criteria
- [ ] The full schema for CH31 has been created in the `vets-json-schema` repo
- [ ] The commit hash in `vets-website` has been updated
- [ ] The `vets-api` repo has been updated accordingly
- [ ] PRs have been submitted for review
