### ISSUE TITLE
Unit Test Non-Static Veteran Information on CH31

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#14920]
# Background
In order to make sure that the non-static Veteran Information page on CH31 behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for the non-static Veteran Information page.

## Tasks
- [ ] Set up test file
- [ ] write unit tests for non-static Veteran Information page
- [ ] submit a PR for review

## Acceptance criteria
- [ ] The non-static Veteran Information page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
