### ISSUE TITLE
Align validation of Facility Locator location field to design system

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14924]
## Issue Description

We need to align the validation and error messages for the Facility Locator City, state or postal code field with the [design system](https://design.va.gov/patterns/form-feedback), similar to the work done in [#5287](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5287)

<details>
<summary> Current behavior </summary>

![image](https://user-images.githubusercontent.com/55411834/96166944-e8207500-0edb-11eb-9623-cfaf32595a75.png)

</details>

---

## Tasks
- [ ] Align error messages with [design system](https://design.va.gov/patterns/form-feedback#error-messages) 

## Acceptance Criteria
- [ ] Error validation messages/stylings appear only after a user has interacted with a particular field.
- [ ] Error messages appear between the label and the input.
- [ ] Error messages use thick border and padding to visually indicate the error message 
- [ ] The field border turns red in the error state.  
- [ ] Screenreaders announce the presence of an error. 
- [ ] The form field receives an aria-describedby attribute that references the id of the error message.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This issue has been addressed
