### ISSUE TITLE
Usability Testing Prep for Medallia

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#14945]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @Shira Goodman and @ AndreaHewitt 
- [x] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/medallia/medallia-product-outline.md)
- Prototype
Intercept Survey: https://staging.va.gov/find-locations/facility/vha_691

![image](https://user-images.githubusercontent.com/48964695/96185544-0ac88300-0f08-11eb-8b9e-627f9149824f.png)
![image](https://user-images.githubusercontent.com/48964695/96185445-e79dd380-0f07-11eb-9184-6f6e1dad7b06.png)
![image](https://user-images.githubusercontent.com/48964695/96185492-f8e6e000-0f07-11eb-91aa-288318fc968d.png)

Feedback Survey: https://staging.va.gov/find-locations
![image](https://user-images.githubusercontent.com/48964695/96181207-a0acdf80-0f01-11eb-93db-5874758faae7.png)
![image](https://user-images.githubusercontent.com/48964695/96181221-a86c8400-0f01-11eb-8ddd-68dbd5fcfcd8.png)
![image](https://user-images.githubusercontent.com/48964695/96181237-af939200-0f01-11eb-8328-50bf0bbb537e.png)

- Link to or attach artifact with copy (if separate from prototypes/mockups)
- Link to research plan ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)) and script ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md))
- Link to regression test plan: N/A
- Link to test cases/test plan in TestRail: N/A

## Meeting attendees from **requesting team**
- Product Manager (required): Joanne Esteban
- DEPO product lead (required): Chante Lantos-Swett
- Anyone else from your team who significantly contributed to the artifacts provided (required): Crystabel Reiter, Bill Fienberg

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira will reach out as needed_

Preferred Scheduling:
1. Friday, 10/16 2-3pm EST
2. Friday, 10/22 2-3pm EST

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by shiragoodman** [comment]
thanks @joanneesteban! scheduling for 10/22 so review team has time to review.

**Comment by joanneesteban** [comment]
@shiragoodman is there any chance we could do a joint staging/usability review? The survey is up on Staging, and we've been told by DEPO that this should go into production as long as there isn't any accessibility issue.

**Comment by shiragoodman** [comment]
@andreahewitt-odd can you weigh in on Joanne's request above? I haven't been involved in a staging review yet, so not sure how to answer.

**Comment by andreahewitt-odd** [comment]
@shiragoodman @joanneesteban yeah I think that's fine as long as the review group is cool with it. Just make sure all accessibility artifacts are accounted for.

**Comment by pjhill** [comment]
As part of coming up with the [test cases for this effort](https://dsvavsp.testrail.io/index.php?/suites/view/79&group_by=cases:section_id&group_order=asc), I've been using Staging. I'll be ready to execute the test cases in earnest after today.

**Comment by ianMcCullough-ob** [comment]
@clantosswett Here is the [draft research plan](https://docs.google.com/document/d/1zBx_wAGYZeoxajHVpV92lTwahDY2pIYTgpuWmmQSSgU/edit?usp=sharing). I added a few questions via comments for your review.

**Comment by clantosswett** [comment]
Can this issue be closed @joanneesteban ?

**Comment by Kimberley2019** [comment]
Closing ticket.  All tasks completed.

**Comment by shiragoodman** [comment]
@1Copenut for a11y review of the 2nd survey

**Comment by jwoodman5** [comment]
All work for this issue is complete. Related issues covered under other iniatives/epics/stories. Closing.
