### ISSUE TITLE
Implement third chunk of account and profile content in drupal

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14948]
## Issue Description

Load the content in the Word doc into templates.

[https://app.zenhub.com/files/133843125/541c8706-9022-46a3-bae3-a44ed95748fd/download](https://app.zenhub.com/files/133843125/541c8706-9022-46a3-bae3-a44ed95748fd/download)

---
## Tasks
- [x] Upload content.

## Acceptance Criteria
- [x] Articles have been created.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
I have entered the content into Drupal. Here are the nodes for review and notes.

### DS Logon accounts: http://preview-prod.vfs.va.gov/preview?nodeId=8483 perhaps the button order should be switched. Did not add summary teaser for related info
#### Common questions about DS Logon accounts. 
- What’s a Premium DS Logon? https://prod.cms.va.gov/node/8475 added content from accordion item #3 (Word doc) per slack comment https://dsva.slack.com/archives/G018JLSB4A2/p1602883610004300
- What’s the difference at sign in between Basic and Premium DS Logon? https://prod.cms.va.gov/node/8476
- I'm a Veteran. How do I get a DS Logon? https://prod.cms.va.gov/node/8478
- What happens after I get in-person proofed for a DS Logon? https://prod.cms.va.gov/node/8480
- Will my DS Logon account or password expire? https://prod.cms.va.gov/node/8479
- Can the spouse or dependent of a Veteran get a DS Logon? https://prod.cms.va.gov/node/8481
- Can the delegate or surrogate for a Veteran get a DS Logon? https://prod.cms.va.gov/node/8482

### My HealtheVet accounts: http://preview-prod.vfs.va.gov/preview?nodeId=8487 Need related info. 
#### Common issues with My HealtheVet accounts (changed h2 wording from "question" to "issues" since the accordion items are not written in the form of a question)
- I can’t register for My HealtheVet because my info doesn't match VA's: https://prod.cms.va.gov/node/8484
- I forgot my My HealtheVet user ID or password: https://prod.cms.va.gov/node/8485
- I’m not sure if I need training to use My HealtheVet: https://prod.cms.va.gov/node/8486

### Commissary and exchange privileges: http://preview-prod.vfs.va.gov/preview?nodeId=8490 did not add summary teasers for related info links
#### Common questions about commissary and exchange privileges (placeholder h2 as it was not included in word doc)

- Am I eligible for commissary and exchange privileges? https://prod.cms.va.gov/node/8488
- How do I apply for commissary and exchange privileges? https://prod.cms.va.gov/node/8489

### How can I find a VA facility?: http://preview-prod.vfs.va.gov/preview?nodeId=8491 
Updated the button link to "Find VA locations" and removed link w/answer field. Need related info.

### Veteran Identification Card (VIC): http://preview-prod.vfs.va.gov/preview?nodeId=8498 no related info
#### The Veteran ID Card (VIC). Also removed "the" from "Learn about the types of Veteran ID cards" button text since it exceeded character limit.
- What’s a VIC? Is it different from an eBenefits ID card? https://prod.cms.va.gov/node/8492 added copy from accordion item 7 here
- Do I need a VIC if I already have a different kind of Veteran ID? https://prod.cms.va.gov/node/8493
- How do I get a VIC? https://prod.cms.va.gov/node/8494
- Are members of the Reserves and National Guard eligible for a VIC? https://prod.cms.va.gov/node/8495
- Will I have to pay a fee to get my VIC? https://prod.cms.va.gov/node/8496
- Will a VIC allow me to access military bases or installations? https://prod.cms.va.gov/node/8497

**Comment by RLHecht** [comment]
The work in this ticket was completed. Nodes have been copied into #14979 to add in related info and button text. Closing ticket.
