### ISSUE TITLE
Health equity fact sheets

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14947]
## Issue Description

We're working with the health equity office to develop COVID-19 fact sheets for vulnerable Veterans:

1. VSO fact sheet
2. Fact sheet for pregnant Veterans
3. Fact sheet for Black, Hispanic, and Native American Veterans
4. Fact sheet for Veterans 65 years old and older
5. Fact sheet for OEF/OIF/OND Veterans.

---
## Tasks
- [x] Complete relevant research
- [x] Write drafts of the 5 fact sheets and share with SMEs
- [x] All SME feedback received
- [x] Revise fact sheets per SME feedback
- [x] Submit for JTF review
- [x] Revise per JTF feedback
- [x] Hand off final fact sheets to Health Equity Office

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
