### ISSUE TITLE
[Facility Locator] Sentry issue: ServiceTypeAhead Cannot read property 'length' of null` 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14959]
# Issue Description
Between 10/6 and 10/16, Sentry logged 41 occurrences for: `TypeErrorchildren(src/applications/facility-locator/components/ServiceTypeAhead) Cannot read property 'length' of null` 

## Tasks
- [ ] Determine the root cause for [error](http://sentry10.vfs.va.gov/share/issue/4b59084bd4a64b858102f264038e03ea/) and which team needs to resolve

## Acceptance Criteria

For errors **within** Facilities team responsibility
- [ ] Error is no longer thrown

For errors **outside** Facilities team responsibility
- [ ] Issue is created and assigned to the appropriate team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
No longer relevant. Closing this issue
