### ISSUE TITLE
[Facility Locator] Sentry issue: TypeError: undefined is not an object (evaluating 'e.center[0]')

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14958]
## Issue Description
Between 10/6 and 10/16, Sentry logged 35 occurrences for: `Type Error on Viewport Changed (src/applications/facility-locator/utils/analytics) error undefined is not an object (evaluating 'e.center[0]')` 

## Tasks
- [ ] Determine the root cause for [error](http://sentry10.vfs.va.gov/share/issue/379675ceb57c4ee5ad0c184a17b671dc/) and which team needs to resolve

## Acceptance Criteria

For errors **within** Facilities team responsibility
- [ ] Error is no longer thrown

For errors **outside** Facilities team responsibility
- [ ] Issue is created and assigned to the appropriate team

**Comment by mmiddaugh** [comment]
Doublechecked - not longer occurring
