### ISSUE TITLE
[Analytics] Profile 2.0: KPI Domo dashboard fixes/updated

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14968]
## Background

I have finally had a chance to take a look at the [Profile 2.0 Domo dashboard](https://va-gov.domo.com/page/492918243) and noticed some things that need confirming/fixing:

**KPIs: Searches for direct deposit from the profile and Searches overall from the profile**

- Can you make sure this data includes all of the profile URLs? The profile URL is no longer just /profile. It’s /profile/[page]. The numbers here look really impressive, almost too impressive, and I am concerned we’re only capturing /profile and not accurately capturing the whole profile.

**KPI: Reduce % of users who visit /account before the profile**

- This KPI is paired with a graph that shows numbers of pages visited before the profile. We are not interested in tracking the number of pages visited before the profile. I wanted a chart of what % of users visited the /account URL before the /profile URL. In theory, this number should now be 0 because we deleted the /account page.

**KPI: Reduce time on profile by 10%**

- Can we see this week by week or month by month? Seeing daily values makes it hard to see if there are any positive trends/patterns.

## Tasks

- [x] Confirm receipt of this request
- [ ] Make the above request updates, if possible
- [ ] If not possible, regroup with Samara on how we should proceed from here

**Comment by jonwehausen** [comment]
Thanks @Samara-Strauss , we appreciate it! Will take a look and get back with you

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - I have updated **KPIs: Searches for direct deposit from the profile and Searches overall from the profile** and **KPI: Reduce time on profile by 10%**. 
For the **KPI: Reduce % of users who visit /account before the profile**, the chart currently shows the total number of pageviews of the `/direct-deposit` page that came from the `/account` page. There have been no instances of this happening since the week of September 27th, that is why there is no data for October.

**Comment by Samara-Strauss** [comment]
> I have updated KPIs: Searches for direct deposit from the profile and Searches overall from the profile and KPI: Reduce time on profile by 10%.

Great, thank you!

> the chart currently shows the total number of pageviews of the /direct-deposit page that came from the /account page. There have been no instances of this happening since the week of September 27th, that is why there is no data for October.

This makes a lot more sense. Thanks for clarifying!

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - Happy to help! I'm closing this issue, but if you need anything else feel free to reopen.
