### ISSUE TITLE
[Facility Locator] Sentry issue: null is not an object

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14960]
# Issue Description
Between 10/6 and 10/16, Sentry logged 37 occurrences for: `TypeErrorcall(src/applications/facility-locator/containers/VAMap)
error null is not an object` 

## Tasks
- [ ] Determine the root cause for [error](http://sentry10.vfs.va.gov/share/issue/71b6c9db2416483dad8774a3f348f1b0/) and which team needs to resolve

## Acceptance Criteria

For errors **within** Facilities team responsibility
- [ ] Error is no longer thrown

For errors **outside** Facilities team responsibility
- [ ] Issue is created and assigned to the appropriate team

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
