### ISSUE TITLE
Typeahead validation implementation

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14963]
## Issue Description
There are two typeahead fields in the Facility Locator search process: City, state or postal code and Service type (for Community providers. These fields need to adopt the typeahead validation design which is used in the 526ez form.

---
## Tasks
- [ ] Update field validation and error messages consistent with the design used in the 526ez form. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
I don't think the City, state or postal code is currently a typeahead field, is it?

I had [started to work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11090) on this several weeks ago but that effort was derailed by other priorities.
