### ISSUE TITLE
[Facility Locator] Sentry issue: error undefined is not an object

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14961]
# Issue Description
Between 10/6 and 10/16, Sentry logged 37 occurrences for: `TypeError?(src/applications/facility-locator/api/LocatorApi)
error undefined is not an object (evaluating 'e.data.map')` 

## Tasks
- [ ] Determine the root cause for [error](http://sentry10.vfs.va.gov/share/issue/06f77c46deb04f668ab9d3ca1ddc97d3/) and which team needs to resolve

## Acceptance Criteria

For errors **within** Facilities team responsibility
- [ ] Error is no longer thrown

For errors **outside** Facilities team responsibility
- [ ] Issue is created and assigned to the appropriate team

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by swirtSJW** [comment]
This should be evaluated to see if it is still a defect.
