### ISSUE TITLE
Review/make suggestions for buttons and related info links in R&S MVP articles

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14979]
## Issue Description
As a user, I want a fluid user experience when I click on a link/button in R&S and land in tier 1 content, and vice versa. I don't want to get lost or wonder how to get back to a page I was on one click ago. I also want to be able to get more information on the given topic if I need it.

---
Nodes to review:
- [x] Signing in to VA.gov preview-prod.vfs.va.gov/preview?nodeId=8222
- [x] Verifying your identity on VA.gov preview-prod.vfs.va.gov/preview?nodeId=8233
- [x] Privacy and security on VA.gov preview-prod.vfs.va.gov/preview?nodeId=8249
- [x] Managing your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8259
- [x] Change your address on file with VA preview-prod.vfs.va.gov/preview?nodeId=8473
- [x] Direct deposit for your VA benefit payments preview-prod.vfs.va.gov/preview?nodeId=8423
- [x] Connecting third-party apps to your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8471
- [ ] Helpful VA phone numbers preview-prod.vfs.va.gov/preview?nodeId=8427. ~(STILL CONFIRMING LANGUAGE FOR TTY LINE, but go ahead and proofread this article--I changed VA311 to VA411!)~
- [ ] How to change your address in your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8417
- [x] How to change direct deposit information for VA education benefits preview-prod.vfs.va.gov/preview?nodeId=8474
- [x] How to change direct deposit information for VA disability or pension preview-prod.vfs.va.gov/preview?nodeId=8434
- [ ] DS Logon FAQs preview-prod.vfs.va.gov/preview?nodeId=8483
- [ ] My HealtheVet FAQs preview-prod.vfs.va.gov/preview?nodeId=8487
- [ ] Commissary and exchange privileges for Veterans preview-prod.vfs.va.gov/preview?nodeId=8490
- [ ] How can I find a VA facility? preview-prod.vfs.va.gov/preview?nodeId=8491
- [ ] Veteran Identification Card (VIC) preview-prod.vfs.va.gov/preview?nodeId=8498
- [ ] How to get a Premium DS Logon account preview-prod.vfs.va.gov/preview?nodeId=8503
- [ ] Get a Premium My HealtheVet account preview-prod.vfs.va.gov/preview?nodeId=8507
- [x] How can I find out my VA claim or appeal status? http://preview-prod.vfs.va.gov/preview?nodeId=8504 (only in Claim status tool)
- [x] What kind of information can I get from VA.gov's claim status tool? http://preview-prod.vfs.va.gov/preview?nodeId=8515 (only in CST)
- [x] Can the tool tell me when I'll receive a decision letter for my claim? http://preview-prod.vfs.va.gov/preview?nodeId=8521 (only in CST)
- [x] What types of claims and appeals can I track online? http://preview-prod.vfs.va.gov/preview?nodeId=8514 (only in CST)
- [x] Can I upload new evidence online? NEW http://preview-prod.vfs.va.gov/preview?nodeId=9276 (only in CST)
- [x] Why does my VA.gov claim info seem different from what's on eBenefits? ~~CAN'T FIND THIS IN THE LIST~~ **http://preview-prod.vfs.va.gov/preview?nodeId=8522**
- [ ] What your claim status means http://preview-prod.vfs.va.gov/preview?nodeId=8548
- [ ] How to check your VA claim, appeal, or decision review status online http://preview-prod.vfs.va.gov/preview?nodeId=8520
- [ ] Request a discharge upgrade or correction http://preview-prod.vfs.va.gov/preview?nodeId=8541
- [ ] What if I don't want a fiduciary anymore? http://preview-prod.vfs.va.gov/preview?nodeId=8540
- [ ] Are service dogs allowed in VA facilities? http://preview-prod.vfs.va.gov/preview?nodeId=8538
- [ ] What if I'm having trouble opening a PDF? http://preview-prod.vfs.va.gov/preview?nodeId=8684
- [ ] Claim status FAQs http://preview-prod.vfs.va.gov/preview?nodeId=9275 

DELETED ARTICLES:
- Managing your documents with the claim status tool http://preview-prod.vfs.va.gov/preview?nodeId=8523 (absorbed this content into other Q&As in the process of consolidating singles into the new Claim status tool multiple FAQ)
- What you can learn from the claim status tool http://preview-prod.vfs.va.gov/preview?nodeId=8528 
- What if I'm having problems opening a PDF on VA.gov? https://prod.cms.va.gov/node/8539
- I'm a Veteran. How do I get a DS Logon? http://preview-prod.vfs.va.gov/preview?nodeId=8478 (we'll maybe bring this back for 1.1, but we need to figure out how to work in language about the other, better ways to be identity proofed since DS Logon will be phased out next year.)

## Tasks
- [ ] Review buttons and related information links in the nodes provided. (@RLHecht to list them here)
- [ ] Make suggestions as needed.

## Acceptance Criteria
- [ ] Suggestions made for navigation.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Could you set up a ticket like this for Laura too? So she can march through the articles already created and add related links? I think it's probably better if it's not a shared ticket as that might get messy with each of them making updates. But whatever you think is best. Let's talk real quick in the morning. Thanks!

**Comment by RLHecht** [comment]
I've added the ones that are in Drupal so far though there will still be more to add, which I will do once they are put in.

**Comment by RLHecht** [comment]
@lwalsh617 Here's the ticket with the nodes available so far.

**Comment by lwalsh617** [comment]
thanks!


–––

Laura Walsh

Content Strategist | Writer

m. 617.549.5496

–––



________________________________

**Comment by lwalsh617** [comment]
@bethpotts @RLHecht -- I just saw Beth's comment above about there needing to be a separate ticket for the Related Information additions I'm making. If I'm not supposed to be checking off pages in this ticket, please advise. Thanks.

**Comment by RLHecht** [comment]
@lwalsh617 You can work in this ticket. We originally set this up for Mikki to look at buttons and you would do related info in another one but we can use the same ticket. Thanks for checking.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO @RLHecht -- All articles in this ticket have been checked/edited for CTA buttons and related info links.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva Here's a list of all the articles we have for MVP. I'm not sure you can see related links yet, but maybe by tomorrow?

**Comment by bethpottsVADEPO** [comment]
@lunascoop In the morning, can you update the H1s listed in this ticket with the most recent H1s that you see in drupal?

**Comment by lunascoop** [comment]
@bethpottsVADEPO I've updated the H1s listed in this ticket

**Comment by bethpottsVADEPO** [comment]
@lunascoop Thanks! Can you go through them once more? I've made some changes. Really appreciate your help updating this.

**Comment by lunascoop** [comment]
@bethpottsVADEPO I've went through the list above and updated the H1s. I also added the node link for: 

- Why does my VA.gov claim info seem different from what's on eBenefits?  http://preview-prod.vfs.va.gov/preview?nodeId=8522
