### ISSUE TITLE
BGS Lookup Location ID by Regional Office for 686

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#14974]
## Background
We need to call the BGS ~~(Regional Office) RO Routing~~ Standard Data Web Service to determine the location id that is associated with the regional office number closest to the Veteran's zip code.

## Considerations
- ~~The RO Routing Service is designed to publish regional office related oracle packages, procedures and decouple Lines of Business from oracle related packages, procedures.~~
- ~~This service doesn’t use tuxedo services.~~
- Do we need to cache this information rather than calling the service every time? 
**Given volume, lets just see.  If we do cache, we could cache this weekly.**

## Tasks
- ~~[ ] Use the method: `getVBARegionalOffices`~~
- [x] Use the method: `findRegionalOffices`
- [x] Update another ticket with the update of the BGS gem, to be written

## Acceptance Criteria
- [x] Write a test for coverage
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000019718/Appendix-A.-Regional-Office-Station-Numbers,-Payee-Codes,-and-Work-Rate-Standards

**Comment by kathleencrawford** [comment]
Upon further investigation, it was discovered that getVBARegionalOffices was not the correct method to be calling.  Instead we should be calling findRegionalOffices.  Ticket has been updated above, just wanted to add a note here to explain all the strikethrough text.

**Comment by kathleencrawford** [comment]
Link to PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5166
