### ISSUE TITLE
Update Payment Method for View Payments

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#14973]
## Background
In `vets-api` when returning the list of payments for the View Payment History feature, it is assumed that payment method will either be "Direct Deposit" or "Paper Check".  After some discussion with the FE, this field should be modified to return a null value if there is no bank account information or check mailing address information.

## Tasks
- [x] Update the logic for determining the Payment Method.

## Acceptance Criteria
- [x] Update test coverage as needed 
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5127
