### ISSUE TITLE
Link Updates for Benefits Apply Wizard Moves 

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#14982]
## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Yes, this request is related to the Education and Disability (as well as HLR and Chapter 31/36) How to Apply Wizards and the move from the How to Apply pages (e.g. https://www.va.gov/education/how-to-apply/) to the Apply or Introduction pages (https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction).

* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Product Outline with all relevant links (to Epics, Flows, etc.)](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665)

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

- [X] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * The complete list of "link to" changes has been created (and is being updated) by @mnorthuis and is [available here.](https://docs.google.com/spreadsheets/d/1HvjCZ86EX4truevyUUbk-WdN-0A_5fcamRZV3GnmLq4/edit#gid=0)
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * N/A
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * N/A

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

*  Expected launch production launch date of the newly-positioned Wizards varies by product line -- however, most are expected to deploy between late October and mid-November.   A tracker with development progress and timelines[ is maintained here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/status_reports/implentation_tracker.md)

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Public Websites
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: Liz Lantz
- FE engineer: Craig Wheeler and Robin Garrison
- Product/team Slack channel: #va-how-to-apply-wizards

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by mnorthuis** [comment]
Closing this old issue - this work is being handled by each team as they deprecate the wizard and move to a sub-task pattern.
