### ISSUE TITLE
[FE] Update phone numbers In the footer. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#14988]
## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d5e01a9b85b431a14)

## Description
Update the UI from user research 

## Tasks

- [ ] Needs help - contact and numbers need to be updated

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
In pull request

**Comment by mdewey** [comment]
Merged. Waiting for deployment to staging

**Comment by mdewey** [comment]
In staging, 

@abuckley3385  and @kristenmcconnell  this is ready for review.

**Comment by kristenmcconnell** [comment]
It matches the wireframes.

**Comment by abuckley3385** [comment]
looks good
