### ISSUE TITLE
Figure out where we are using images from Docker Hub and use authenticated service account to pull them 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14995]
## Issue Description
_Docker Hub is going to start limiting Docker unauthenticated Docker pulls from their registry. In order for our CircleCI processes to work, and not be interrupted, we need to make authenticated pulls of Docker images. 

Please see [HERE](url) for information related to setting up the service account to enable this to happen. 
---
## Tasks
- [ ] _Determine where we pull images using Docker Hub_
- [ ] _Make those docker pulls use the new service account _

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
