### ISSUE TITLE
Discovery - Better organization of Pagerduty account & better alerting scheme

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14994]
## Issue Description
_The Pagerduty account has very little structure in terms of team definitions. We have a very flat configuration at the moment. We would like to add some additional organizational hierarchy, and leverage more of the power of this tool, ie roundrobin for teams, services -> alerts -> teams, etc. The goal is for there to be fewer false positives ie "people get woken up less"_

---
## Tasks
- [ ] _Evaluate whether or not we should move back to using Terraform for Pagerduty configuration (third-party provider for Terraform)_
- [ ] _Document current organizational structure, teams, alerts, contacts, etc_
- [ ] _Propose better organizational structure and layout for teams, alerts, contacts, etc _ 
- [ ] _Plan for the next iteration_ 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Let's create a Pagerduty improvements Epic, and this will be the first ticket on this Epic.

**Comment by jhouse-solvd** [comment]
There is a newer version of this work: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14994

Closing.
