### ISSUE TITLE
Mock appointment data endpoints using `betamocks` and `vets-api-mockdata`

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#14991]
## User Story
**In order** to save time and use a pre-visit questionnaire feature for my upcoming primary care appointment
**As a** Veteran
**I want** the website engineers to incrementally build and test the feature first by using mock appointment data in their development and staging environments 

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
Mock appointments data(JSON) for the `/health_quest/v0/appointments/:id` endpoint using `betamocks` and the `vets-api-mockdata` repository for the development and staging environments.

## Tasks
- [x] Add MAP appointments config to `config/betamocks/services_config.yml`
- [x] Enable mock data for the `hqva_mobile` config in `/config/settings.yml`
- [x] Add `hqva_mobile` module and relevant files to the `vets-api-mockdata` project

## Acceptance Criteria
- [x] vets-api/vets-api-mockdata code is reviewed/accepted and merged back into the master branch
- [x] The `/health_quest/v0/appointments/:id` returns mock appointment data in JSON format in dev and staging environments
- [x] The JSON appointment mock data has all the necessary keys and values as is required by the FE

**Comment by mdewey** [comment]
I have verified it's in master.  Thank you!
