### ISSUE TITLE
Update links and text within Profile that currently go to sign-in FAQ

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14998]
## Issue Description
Resources and support product launch will bring over the sign-in FAQ content and break it into multiple articles. We need to update the links and text within Profile to point to the new nodes/articles.

There are links to the existing sign-in FAQ on these two pages of the profile, at the bottom of each page, in the blue callout boxes:

https://staging.va.gov/profile/account-security
https://staging.va.gov/profile/connected-applications

---
## Tasks

**Timing:**
These changes should be made the same day the redirects happen for sign-in FAQ page, after Resources and support launches. **Please wait for the all clear!**

- [ ] Provide nodes and new text. (Beth)
- [ ] Change the nodes linked to. (Samara's team)
- [ ] Change the text as shown here (Samara's team):

## For Samara's team, here are the specific changes

Please update the links and text as outlined here: 

**For this page: https://staging.va.gov/profile/account-security**

Replace what's in the blue box currently with:

**Have questions about signing in to VA.gov?**
Get answers to frequently asked questions about how to sign in, common issues with verifying your identity, and your privacy and security on VA.gov.

Go to FAQs about these topics: [11/5 updated the links below]
Signing in to VA.gov (va.gov/resources/signing-in-to-vagov/)
Verifying your identity on VA.gov (va.gov/resources/verifying-your-identity-on-vagov/)
Privacy and security on VA.gov (va.gov/resources/privacy-and-security-on-vagov)

**For this page: https://staging.va.gov/profile/connected-applications**

Replace what's in the blue box currently with:

**Have more questions about connected apps?**
[Go to FAQs about connecting third-party apps to your VA.gov profile](va.gov/resources/connected-apps-faqs/)

**Note for @Samara-Strauss:** You may want to look at the repetition of the Q&As here in profile and those you'll link to contained in this article. Although the same repetition exists today, it's a little different now that Connected Apps has its own page. There's no scrolling down the sign-in FAQ to find the connected apps content anymore. So it's a little weird to repeat those Q&As. Calling it out for you in case you want to raise that with TJ. 

## Acceptance Criteria
- [ ] Links in Profile go to the new nodes. 
- [ ] New text replaces old text.
- [ ] Note: Hold on pushing this until the day we're ready to do the redirect. This may be Friday 11/6, but I will be in touch. We have to make sure everything is stable in resources and support first. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Samara-Strauss** [comment]
@bethpottsVADEPO what is the deadline for this work?

**Comment by Samara-Strauss** [comment]
> Note for @Samara-Strauss: You may want to look at the repetition of the Q&As here in profile and those you'll link to contained in this article. Although the same repetition exists today, it's a little different now that Connected Apps has its own page. There's no scrolling down the sign-in FAQ to find the connected apps content anymore. So it's a little weird to repeat those Q&As. Calling it out for you in case you want to raise that with TJ.

Looks like the links in the ticket aren't working, so we need to get that figured out so I can assess the situation and determine how we should move forward.

**Comment by bethpottsVADEPO** [comment]
@Samara-Strauss Can you see the urls now? I updated them above. Sorry for that confusion.

**Comment by Samara-Strauss** [comment]
@bethpottsVADEPO they're all giving me the "Sorry, we can't find that page" page on VA.gov. Not sure why they're not working.

**Comment by bethpottsVADEPO** [comment]
@Samara-Strauss OK, try now!

**Comment by Samara-Strauss** [comment]
YAY! They are all working now, thank you!

**Comment by Samara-Strauss** [comment]
@sanlouise — for the updates to the connected app page, you can also remove the FAQs we currently have there for both the states of the connected apps design (when a user has apps connected and when a user does not have apps connected). The updated FAQ page we'll be linking to in the blue box has all the FAQs we currently have on the connected apps page. 

<img width="1280" alt="Screen Shot 2020-11-05 at 2 36 41 PM" src="https://user-images.githubusercontent.com/34068740/98288260-987e1800-1f74-11eb-9503-cbccb975d056.png">

<img width="1280" alt="Screen Shot 2020-11-05 at 2 40 42 PM" src="https://user-images.githubusercontent.com/34068740/98288567-0c202500-1f75-11eb-89b7-a9d8eebf6340.png">

**Comment by sanlouise** [comment]
Thanks @Samara-Strauss I will make the update in the first screenshot. Per your second screenshot, [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15235) deals with updating that app list and I have a PR ready that can be merged on November 16.

**Comment by Samara-Strauss** [comment]
> Per your second screenshot, this ticket deals with updating that app list and I have a PR ready that can be merged on November 16.

Thank you for catching that! Yes, please move forward with that existing PR and ignore the second screenshot.

**Comment by sanlouise** [comment]
@Samara-Strauss Per the first screenshot, you indicated that I can remove the dropdown for "What other third-party apps can I connect to my profile?" - but that goes against what is asked for in [that other ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15235)

Can you confirm whether to remove the link or not?

**Comment by Samara-Strauss** [comment]
It **should** be OK — that information is in the new learning center, and I don't want us to be responsible for updating that list in two places.

But just to confirm — @ricetj, is it ok if we remove the "What other third-party apps can I connect to my profile?" dropdown from the connected apps page now that that FAQ is in the learning center?

<img width="900" alt="Screen Shot 2020-11-05 at 3 26 47 PM" src="https://user-images.githubusercontent.com/34068740/98292969-9075a680-1f7b-11eb-8cd3-8dbae7b6b86e.png">

**Comment by ricetj** [comment]
> It **should** be OK — that information is in the new learning center, and I don't want us to be responsible for updating that list in two places.
> 
> But just to confirm — @ricetj, is it ok if we remove the "What other third-party apps can I connect to my profile?" dropdown from the connected apps page now that that FAQ is in the learning center?
> 
> <img alt="Screen Shot 2020-11-05 at 3 26 47 PM" width="900" src="https://user-images.githubusercontent.com/34068740/98292969-9075a680-1f7b-11eb-8cd3-8dbae7b6b86e.png">

Hello @Samara-Strauss for sure! Once the Application directory is live it should be just a link to that if users want to see all the different applications they can connect to. I agree I wouldn't want you all to have to keep a static list up-to-date.

**Comment by bethpottsVADEPO** [comment]
@Samara-Strauss @sanlouise **Please hold off on going live with these changes until Monday.** We're still ironing out some issues with search in resources and support, and we'd like to fix a couple things before we start linking to this new area of our site. Thank you for your patience! I'll be in touch on Monday to verify that we're ready (or not) then. We expect to be, but we'll see.

**Comment by Samara-Strauss** [comment]
Absolutely, thanks for letting us know. We'll hold off until Monday — can you let us know when we're good to go live?

**Comment by ricetj** [comment]
To be clear here. The application Directory is different from the FAQ page.

**Comment by bethpottsVADEPO** [comment]
I will let you know. Thanks so much!

**Comment by sanlouise** [comment]
@ricetj @Samara-Strauss 

Just to want to make sure we are all on the same page, please correct me if I am wrong:

1) We KEEP the dropdown "What other third-party apps can I connect to my profile?", and make sure that once the user expands it, it just has the link to the app directory. This is what is required in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15235). I already have a PR up for that ticket, which is ready to merge when I'm told to. 
2) I REMOVE "What should I do if my records are wrong or out of date in a connected app?" and "What should I do if I no longer trust a connected app?"

**Comment by ricetj** [comment]
> @ricetj @Samara-Strauss
> 
> Just to want to make sure we are all on the same page, please correct me if I am wrong:
> 
> 1. We KEEP the dropdown "What other third-party apps can I connect to my profile?", and make sure that once the user expands it, it just has the link to the app directory. This is what is required in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15235). I already have a PR up for that ticket, which is ready to merge when I'm told to.    If you want to remove this dropdown instead, we should talk about updating/cancelling that other ticket.
> 2. I REMOVE "What should I do if my records are wrong or out of date in a connected app?" and "What should I do if I no longer trust a connected app?"

I will let @Samara-Strauss speak to how you all want to make the Profile look, but for what is happening is we are creating a place for users to see all the different applications they can connect to. So you wouldn't need to have a list on the profile (these are changing, we now have 5), instead you could just have a link to the Application Directory when it does live in a week or so. 

I thought that was the idea with this post: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15234#issuecomment-718128418

I am happy to jump on a call to talk through this if anyone would like that.

**Comment by sanlouise** [comment]
> > @ricetj @Samara-Strauss
> > Just to want to make sure we are all on the same page, please correct me if I am wrong:
> > 
> > 1. We KEEP the dropdown "What other third-party apps can I connect to my profile?", and make sure that once the user expands it, it just has the link to the app directory. This is what is required in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15235). I already have a PR up for that ticket, which is ready to merge when I'm told to.    If you want to remove this dropdown instead, we should talk about updating/cancelling that other ticket.
> > 2. I REMOVE "What should I do if my records are wrong or out of date in a connected app?" and "What should I do if I no longer trust a connected app?"
> 
> I will let @Samara-Strauss speak to how you all want to make the Profile look, but for what is happening is we are creating a place for users to see all the different applications they can connect to. So you wouldn't need to have a list on the profile (these are changing, we now have 5), instead you could just have a link to the Application Directory when it is live in a week or so.
> 
> I thought that was the idea with this post: [#15234 (comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15234#issuecomment-718128418)
> 
> I am happy to jump on a call to talk through this if anyone would like that. Also, thank you to everyone working on and around this.

@ricetj Great, we are on the same page! I just want to confirm that Samara did not want me to remove the dropdown (with the link to the application directory) entirely - which would go against the directions in #15234.

**Comment by Samara-Strauss** [comment]
> Just to want to make sure we are all on the same page, please correct me if I am wrong:
> 
> 1. We KEEP the dropdown "What other third-party apps can I connect to my profile?", and make sure that once the user expands it, it just has the link to the app directory. This is what is required in this other ticket. I already have a PR up for that ticket, which is ready to merge when I'm told to. If you want to remove this dropdown instead, we should talk about updating/cancelling that ticket.
> 
> 2. I REMOVE "What should I do if my records are wrong or out of date in a connected app?" and "What should I do if I no longer trust a connected app?"

This sounds good to me. We can keep the dropdown and just link off to the app directory. That way, we surface a path to that info but don't have to also maintain the app list in the profile.

**Comment by sanlouise** [comment]
Thank you for confirming 👍

**Comment by bethpottsVADEPO** [comment]
@sanlouise Wanted to call out that for the below link to connected apps FAQs, we had a bug that we just fixed, and the url has changed. I updated it above in the instructions, but here it is as well (let me know if you have questions about this!):

For this page: https://staging.va.gov/profile/connected-applications

Replace what's in the blue box currently with:

Have more questions about connected apps?
Go to FAQs about connecting third-party apps to your VA.gov profile

**Comment by bethpottsVADEPO** [comment]
@Samara-Strauss Wanted to make you aware of COPE (Create Once Publish Everywhere) functionality coming soon to resources and support that would allow content to be updated in one place and then used in multiple places. So you could add back into Profile any of these helpful Q&As that would really be good for the user to see when they're in this authenticated space (rather than the user having to leave Profile to read about, for instance, other third-party apps that they can connect to their profile). 

I'm letting you know this because Danielle said including those Q&As was a specific content strategy that had been previously discussed and agreed to. So you might want to add them back in once that issue of updating content/details in two places is irrelevant (once COPE launches). Let me know if you want to hear more or need clarification.

**Comment by Samara-Strauss** [comment]
Oh this is great! Will you keep us posted on this? I do think having some of this info in-context would be helpful, so please let us know when COPE functionality is available.

**Comment by bethpottsVADEPO** [comment]
Will do!

**Comment by sanlouise** [comment]
@bethpotts Thank you, I already have a PR up for updating the connected apps URL (which was part of [this other ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15235)) Can you confirm that both this ticket and the connected apps ticket can be merged on the same day in the near future?

**Comment by ricetj** [comment]
> @bethpotts Thank you, I already have a PR up for updating the connected apps URL (which was part of [this other ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15235)) Can you confirm that both this ticket and the connected apps ticket can be merged on the same day in the near future?

@sanlouise The application directory is not live yet and is different from the FAQ page that Beth is talking about. Beth is referring to the link to the sing in FAQ at the bottom of the connected apps section of the profile. We are looking to launch the App Directory next week hopefully and then that will go to replace the list of applications in the profile. 

CC: @Samara-Strauss

**Comment by bethpottsVADEPO** [comment]
@sanlouise 
- According to @ricetj #15235 should go live on his signal.
- Your PR for the work outlined at the top of this ticket, should go live (here's the latest update...) Tuesday rather than today as I'd hoped.

This has been really confusing, all these updates, so I wanted to thank everyone for their patience and thoroughness in clarifying what's needed!

**Comment by bethpottsVADEPO** [comment]
OK, @sanlouise You can move forward today with your PR for the above changes in this ticket. 

@Samara-Strauss for awareness

**Comment by sanlouise** [comment]
Thank you, the PR is now merged 💯

**Comment by Samara-Strauss** [comment]
Awesome! Can I close this out, @sanlouise?

**Comment by sanlouise** [comment]
@Samara-Strauss Yes, we can :) Just verified in staging that all looks good.

**Comment by Samara-Strauss** [comment]
Great! Great work!
