### ISSUE TITLE
Usability Testing Prep - Public Websites [Wizard Migration]

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#15005]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @Shira Goodman and @ AndreaHewitt 
- [x] Shira to schedule meeting with VSP reviewers and **Public Websites** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **Public Websites** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *wizard migration*
- [ ] **Public Websites** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to [product epic](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665)
- [Link to prototype](https://preview.uxpin.com/b1b1e65464a2e1919eac6e6a3cab8bea63d2ada5#/pages/133402738/simulate/sitemap?mode=i). Please see [this Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1602865757168200) about the status of our prototype and timing for this review
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/discovery/research/wizard-research-plan.md) and [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/discovery/research/wizard-migration-convo-guide.md)

**We don't have these things yet afaik**
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from **requesting team**
- Product Manager (required): Brian Lloyd
- DEPO product lead (required): John Hashimoto
- Anyone else from your team who significantly contributed to the artifacts provided (required): Liz Lantz. Please include @chrvalla (cvalla@governmentcio.com) as well, he's helping with this study

## Scheduling
Can we have the 1:30 time slot on 10/22 please?

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by shiragoodman** [comment]
hi @andaleliz  - can you update the "Steps to complete Usability Testing Prep:" section above with your team name where there is **bold text**. Thanks! The timeslot has been reserved.

**Comment by andaleliz** [comment]
@shiragoodman thanks for reserving the time! I made the update.  

How do we know if we need the regression test plan and test cases/test plan? This particular situation is unusual in that my team is making the recommendations for these changes, but other teams (BAM 1 and 2, and Booz Allen Hamilton) will actually be implementing and building them out.

cc @johnhashva and @brianalloyd

**Comment by shiragoodman** [comment]
@pjhill can you answer Liz's question above?

**Comment by pjhill** [comment]
> @shiragoodman thanks for reserving the time! I made the update.
> 
> How do we know if we need the regression test plan and test cases/test plan? This particular situation is unusual in that my team is making the recommendations for these changes, but other teams (BAM 1 and 2, and Booz Allen Hamilton) will actually be implementing and building them out.
> 
> cc @johnhashva and @brianalloyd

Typically, we recommend that you create a regression test plan if you are making changes to an existing product or iterating on a product that you previously created. The product epic for this effort indicates to me that you are replacing an existing product with a new product. Since this is a new effort, there can't be any expectation that test cases for the product that your team is replacing are accessible. So, there is no existing pool of test cases to draw from for the creation of a regression test suite.

Instead, I would encourage the team to think about what functionality will be preserved from the previous product, and what functionality your user research indicates the core of your new product should be. Start thinking about those test scenarios early and as you create the test cases you may consider grouping/labeling them in TestRail as strong candidates for future regression testing.
![image](https://user-images.githubusercontent.com/52456633/96524881-73389c80-1247-11eb-80d0-b6b1be356ac9.png)
Test cases can always be grouped or labeled differently in the future. If you need help working with TestRail please feel free to pose questions @ me in #vfs-platform-support. More information about working with TestRail is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/testrail).

**Comment by johnhashva** [comment]
@andaleliz + @brianalloyd with guidance provided ^ let me now check with the PMs for the BAM teams (Education and Disability) and the CH 31/36 team to determine if they will take the lead in creating test cases for the wizard or we need to do it (or collaborate).   My expectation is CH 31/36 will be responsible for their own as that's a new wizard they created.  I'll post update here.

**Comment by andaleliz** [comment]
@johnhashva that sounds good, thanks.

@shiragoodman do I need to hold off on submitting our research plan to Lauren Alexanderson until this meeting takes place?

**Comment by johnhashva** [comment]
Update @andaleliz -- @tzelei had previously developed test cases for the wizards as outlined here https://github.com/department-of-veterans-affairs/va.gov-team/issues/13124.  Obviously, these test cases do not reflect the changes/refinements as reflected in the prototypes.    @shiragoodman given this, we should be good to go for usability -- yes?

**Comment by shiragoodman** [comment]
@andaleliz I would check with Lauren to see if she has a preference. 

@johnhashva are you asking if you're good to go without the usability test prep?

**Comment by andaleliz** [comment]
>I would check with Lauren to see if she has a preference.

FYSA to all - she prefers this checkpoint be complete before we submit anything. I've adjusted the research timeline accordingly.

**Comment by johnhashva** [comment]
@shiragoodman to clarify, I was asking if the regression test cases and test plan were necessary in order to move forward with usability testing.  Sounds like that is not the case -- so once the "checkpoint" meeting takes place we should be good to go.

**Comment by mnorthuis** [comment]
No IA feedback, looking forward to seeing results!

**Comment by pjhill** [comment]
No QA feedback at this time.

**Comment by peggygannon** [comment]
Hello, @andaleliz the prototype is looking good!! Just a few minor content tweaks, which I dropped into the prototype.

**Comment by allison0034** [comment]
Hello, this is going to be a usability improvement! No outstanding feedback. Here is a list of our questions we discussed during the meeting:

Is the “Apply to 1990 4 A” page supposed to have a CTA button after the wizard? I didn’t see one. (I think there should be one, depending on the answer to this question, we could transform it into a “Must” feedback for including a CTA button)
Chris: We are still working on the prototype so that’s why the CTA button wasn’t there. 

The research plan mentions evaluating whether people notice the “Skip links” - I didn’t see those in the wizard and am curious what they look like. Can you point them out?

Can you give a little more context on the lightweight alert design?
Liz: Primary alert has a lot of issues on mobile. A lot of this information is not really a warning. It’s an outcome, we don’t want to give a false sense of panic. We just want to say, it's a soft next step

In your research, are you planning to ask any questions about the alert design since this is different and more lightweight than what is currently live in wizards on VA.gov?
Liz: Yes, I’ll hope it’ll come organically. Ch 36 had a similar alert. That research shows that people saw that. If someone doesn’t see it. We will prompt them and ask them if they notice anything else.
