### ISSUE TITLE
[UI] Create Drupal Page

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15019]
# Product Documentation
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Feature - Questionnaires List ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## User Story/ies

* Use Case: Veterans need the ability to find the questionnaires feature on va.gov without being logged in and find information about the feature if they didn't know it existed beforehand.

## Tasks
- [x] Create mockups and callouts of Drupal page
   - [Unuthenticated version](https://zpl.io/2jDmm3q)
   - Authenticated version not needed - Once authenticated, a user wouldn’t see this page. It would skip to the Questionnaire List page.
   - [Access to entire wireframe set for anyone with this list](https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780)
- [x] Review with Accessibility and feedback incorporated or documented for team review 
- [x] Engage content for a review (Peggy Gannon)
- [x] Schedule accessibility review (create story)

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (will be implemented by Public websites team, so discussions will occur at a later date).
- [x] published Link and updated product feature outline 
- [x] Accessibility review complete
- [x] Incorporate content feedback into designs

**Comment by kristenmcconnell** [comment]
@abuckley3385 First draft of a wireframe ready for review: https://zpl.io/2jDmm3q

**Comment by kristenmcconnell** [comment]
@peggygannon - Can you review the content on the following wireframes:
- [Authenticated version](https://zpl.io/2jDmm3q)
- [Unauthenticated version](https://zpl.io/anxG0zQ)

This is the main content page (Drupal) for our questionnaire feature. This is the main page that Veterans would navigate to from the va.gov homepage. Our entire wireframe set for the whole feature can be viewed here: https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell I'm adding @DanielleThierryUSDSVA as reviewer to this ticket. She's the content lead for the Public Website team and should be the one looking at the content on the drupal static page. (The PW team writes/edits all content for static pages.)

Danielle and I work closely together, so we'll be syncing on all the content across the static pages and within the questionnaire tool.

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Utilize this link to review, because I don't think you have the same access as Peggy: https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780. You will only need to review the content pages within the "Content page and IA" section of this Zeplin file.

**Comment by kristenmcconnell** [comment]
@peggygannon @DanielleThierryUSDSVA Let me know if you have any questions about this ticket.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @kristenmcconnell. Will do. Could you give me a sense of timing on this for prioritization? Thanks!

**Comment by kristenmcconnell** [comment]
Would having the review completed by the end of the week (Nov. 6) be reasonable on your end?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell. Yes, though it may be the weekend depending on how the rest of the week goes. Also, I mentioned the IA to @mnorthuis yesterday and she's going to look at that piece as well. Thanks!

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Great. We also have ticket #15647, where we asked for the IA request as well.

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell @peggygannon @mnorthuis Comments to date on the Drupal page attached. Since the PW team will be building this page, we can drop in the final privacy content when it's ready. 
[Health questionnaires content 11.10.20.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5521368/Health.questionnaires.content.11.10.20.pdf)

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Thank you. I incorporated the feedback into the Zeplin wireframe deliverable (seen within the Content page section of https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780). I also added some comments into your [PDF](https://app.zenhub.com/files/133843125/f09402e5-a524-4132-93e8-470814fdd030/download).

@mlighdc @abuckley3385 Please review the updated Drupal page for our feature.

@peggygannon @mnorthuis

**Comment by kristenmcconnell** [comment]
@abuckley3385 This page will be implemented by the public websites team, so we need to get this on their roadmap.

**Comment by mlighdc** [comment]
Thanks @kristenmcconnell. Just one minor question:

- Should the first bullet be more about "ask questions to your providers at the appointments" or something like that? Answer questions from your provider makes it sound like the provider will be asking other questions besides the one on the form. Let me know if I am misinterpreting.
![image](https://user-images.githubusercontent.com/35788031/98858509-be9d2f80-242e-11eb-959a-446deca99dd3.png)

**Comment by kristenmcconnell** [comment]
@mlighdc I think what content wrote is correct. Fundamentally, all of our questionnaires include questions that need to be answered. Also, the questionnaires are sent by the VA provider to the Veteran, so the providers are requesting that the Veterans answer the questions.

**Comment by mlighdc** [comment]
I am still wondering if you need the first bullet @kristenmcconnell. It seems bullets #2 and #3 would cover it. I like the last two bullets because they are more veteran focus vs. the bullet #1.

**Comment by kristenmcconnell** [comment]
I liked bullet #1, because it highlighted that these questions are coming from the VA provider, which gives an authority to the questions (the veteran can't just start a questionnaire any old time). That said, we made that point in multiple places on the page and you are correct...that question's wording is all about the patient. When I read the page without bullet #1, I believe that you are correct that we do not really lose anything at this time. Our MVP questionnaire is only a few questions long and their scope is completely covered by bullet #2. We will need to revisit this page as the intake questionnaire expands and we add other questionnaires. I will remove bullet #1 from the wireframe.

**Comment by mlighdc** [comment]
I see what you are saying @kristenmcconnell. Do you think if would be worth it to reword it so it is more about the patient?

**Comment by kristenmcconnell** [comment]
What about...
"- Share details about your health by answering questions sent to you by your VA provider"

@DanielleThierryUSDSVA @peggygannon - Any thoughts on rewording this bullet to address @mlighdc's comments above?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mlighdc @kristenmcconnell. I struggled w/ editing bullet 1 a bit. And I think we're actually okay dropping it. By answering the questions, you're telling your provider about the details.

**Comment by kristenmcconnell** [comment]
Ok. Let's drop bullet 1.

**Comment by kristenmcconnell** [comment]
@abuckley3385 Ready for review.

**Comment by abuckley3385** [comment]
I would change ( or we can change once we know our pilot appts) "All" to select appointments - so we are not saying everyone as I doubt that will happen.
![image.png](https://images.zenhubusercontent.com/5ede4fb2cea2fa1db922bc7f/f7be43f2-6236-4364-a0d3-c4f2033b447a)

Otherwise looks good

**Comment by kristenmcconnell** [comment]
@abuckley3385 That change makes sense to me, since our pilot isn't 100% nailed down yet. 

@DanielleThierryUSDSVA I updated the Zeplin file with Amanda's suggested change.

**Comment by peggygannon** [comment]
hello, @kristenmcconnell here is updated content for the questionnaires landing page to better align with the static page. 
these updates include: 
1. Bringing info about filing out  [X] days further up to intro, to better inform user whether answering questionnaire is helpful, and reframed the intro a bit because of this. 
 
2. per our earlier conversation, moved the "What happens after I answer questions" paragraph above the privacy questions so we can incorporate info about it being added to their medical record.   

3. Under privacy question, this first bullet is still not yet final (•Share your information with only the people who need it as part of providing your health care). Danielle is still in discussion with some SMEs about if this should align it with what's on our current health care tool pages. 

4. Emergency care note. How did this test with users? Wonder if we should consider moving earlier in the flow? It feels buried here and by time users get to this page, they have already have appt. lined up. 

[https://app.zenhub.com/files/133843125/4bcc6c5d-2e24-4713-aec9-4fd0f58cf795/download](https://app.zenhub.com/files/133843125/4bcc6c5d-2e24-4713-aec9-4fd0f58cf795/download)

**Comment by kristenmcconnell** [comment]
Moving Peggy's feedback to #16304, since it related to the introduction page and not the Drupal page.
