### ISSUE TITLE
Reimplement data layer following Mapbox upgrade

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15011]
## Issue Description
Data layer added in [#11597](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11597) will need to be implemented in the new Mapbox version

---
## Tasks
- [ ] Reapply map events data layer 

## Acceptance Criteria
- [ ] Analytics for map interactions are maintained 
- [ ] sign off by Insights team 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
Already implemented in new map
