### ISSUE TITLE
Fix broken link on TSGLI page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15020]
## Issue Description
Per stakeholder Lori Hamilton, their office changed a PDF on the [TSGLI](https://www.va.gov/life-insurance/options-eligibility/tsgli/) page, causing a broken link. We need to update the page with a new link under the H2 "How do I get these benefits?"

---
## Tasks
- [x] Update link with new PDF (Randi)
- [x] Review and publish page (Randi)
- [x] Alert stakeholder of change (Beth/Randi)

## Acceptance Criteria
- [x] Change is live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This change has been made. Creating ticket just to track work. Moving to validate and will close after Tuesday's deployment. FYSA @brianalloyd @bethpottsVADEPO

**Comment by RLHecht** [comment]
These changes have been validated on live site. Closing ticket. FYSA @brianalloyd @bethpottsVADEPO
