### ISSUE TITLE
Update change direct deposit page with new info from stakeholders

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15021]
## Issue Description
The way VBA processes direct deposit enrollments and updates requests changed as of October 13. Stakeholder Monica Rivera provided us with new content that needs to go on the [Change direct deposit](https://www.va.gov/change-direct-deposit/) page. 

Under the H2 "How else can I update my VA payment information?" the new text should read as follows:

To update your direct deposit information or the address on your paper checks, you can:
- Call us at 800-827-1000 (TTY: 711), **or**
- Call us at 981-781-7550 (for international direct deposit updates), **or**
- Go to your nearest VA regional office and change this information in person

**Note:** If you don’t have access to the internet or a phone, you can update your direct deposit information with [Standard Form 1199a](https://www.fiscal.treasury.gov/files/forms/form-1199a.pdf).

---
## Tasks
- [x] Update page with new content (Randi)
- [x] Review and publish page (Randi)
- [ ] Alert stakeholder of change (Beth)

## Acceptance Criteria
- [x] Changes live on the site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This work has been completed. Creating ticket to track the work. I'll close after Tuesday's deployment. FYSA @brianalloyd @bethpottsVADEPO

**Comment by RLHecht** [comment]
This change has been validated on live site. Closing ticket. FYSA @brianalloyd @bethpottsVADEPO
