### ISSUE TITLE
Technical Discovery: Why formation is separate from formation-react

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15047]
## Issue Description
Prior to beginning the work needed to get Storybook setup, technical discovery is needed to answer the following questions: 

- Why is formation separate from formation-react?
-  How is the formation CSS used?
-  Can we integrate formation into formation-react?  

---
## Tasks
- [ ] Discovery / Research 
- [ ] Talk to others with knowledge / history

## Acceptance Criteria
- [ ] Understanding of how to move forward technically
- [ ] Other tasks to set up Storybook can be worked on
---
