### ISSUE TITLE
Update H1s of R&S step-by-step to "How to..."

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15042]
## Issue Description
We need consistency across R&S for the step-by-step articles. All H1s should be "How to..." and the header above the process list should be "Steps to changing..." The nodes that have already been created should be updated.

Articles to work on:

- [x] Steps to changing your VA.gov profile address step-by-step preview-prod.vfs.va.gov/preview?nodeId=8417
- [x] Steps to changing your VA education direct deposit information preview-prod.vfs.va.gov/preview?nodeId=8474
- [x] Steps to changing your VA disability or pension direct deposit info preview-prod.vfs.va.gov/preview?nodeId=8434
- [x] Premium DS Logon step-by-step preview-prod.vfs.va.gov/preview?nodeId=8503
- [x] Steps to checking your claim status appeal http://preview-prod.vfs.va.gov/preview?nodeId=8520
---
## Tasks
- [x] Update all step-by-step articles with the above language. (Randi)

## Acceptance Criteria
- [x] All step-by-step articles have been updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This work has been completed. Created it to track the work. FYSA @brianalloyd @bethpottsVADEPO
