### ISSUE TITLE
[Research][UI] Questions for Clinicians

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15049]
## User Story
- As a clinician, I need to be able to access patient questionnaires, in order to prepare for the patient's upcoming appointment.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
Create a list of questions to ask Clinicians about possible a workflow for interacting with our questionnaire and other questions.

## Tasks
- [X] Create new folder for this specific research: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/november-2020
- [X] Create [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/november-2020/clinician-questions.md)

## Acceptance Criteria
- [x] Review conversation guide with product, Ming, and Lacey

**Comment by kristenmcconnell** [comment]
Created a mural to capture all of the team's feedback on what exactly we want to talk to clinicians about. https://app.mural.co/t/vsa8243/m/vsa8243/1604515913813/c99340a493ee96a95d1a6e563cd57d4c1c4cf83b

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mlighdc @LEHigley Here is the updated clinician interview questions based off of our Mural brainstorming session and the past clinician protocol: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/november-2020/clinician-questions.md

Let me know what you think and if we need to make any changes.

**Comment by abuckley3385** [comment]
questions looks fantastic
