### ISSUE TITLE
Add SiP ID to Sentry call

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#15060]
## Issue Description
https://github.com/department-of-veterans-affairs/vets-website/pull/14581 removed `formData` from Sentry calls to avoid leaking PII to that service. Instead, we need to add the `in_progress_form_id` [received from the SiP load call](https://github.com/department-of-veterans-affairs/vets-api/pull/4925/files#diff-1896db48aa7648bb1d7e8c90a8cc623139acfc46a8fdc69604185919af8b6229R39) to the Sentry call for debugging.

---
## Tasks
- [ ] Determine the casing of the `in_progress_form_id` metadata
    - Should be camelCase, but need to verify
- [ ] Add the `in_progress_form_id` to the Sentry call

## Acceptance Criteria
- [ ] The SiP ID is available in Sentry errors for forms
