### ISSUE TITLE
Design intent Collaboration Facilities [Map Enhancements: Phase 1]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15062]
## Steps to complete Design Intent Collaboration
- [X] Product Manager or Designer: create this issue and fill in team name and feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] Design Intent collaboration meeting completed 
- [ ] [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- [Product Brief - WIP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/map-enhancements/phase-1-limit-search-to-250-miles/product-brief.md)
- Sketches
- Lo-fi mockups
- [Competitive analysis PDF](https://app.zenhub.com/files/133843125/315c0bd6-e7c8-4144-9222-19670e7b25e2/download) used to inform wireframes
- [Recommendations based on analysis with supporting visual examples](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/map-enhancements/Map%20Behavior%20-%20Recommendations.pdf)

## Meeting attendees from **requesting team**
- Designer(s) (required): **Chris Logan, Leyda Hughes**
- Product Manager (optional): **Michelle Middaugh**
- DEPO design lead (required as applicable): **Dave Conlon, Ryan Thurlwell**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
   - **Requesting Thursday, October 29 at 1:30 ET**
- _If no available time slots work for your team, write your availability and requirements here and Crystabel will reach out as needed_

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by allison0034** [comment]
The design intent meeting has been scheduled for October 29 at 1:30 ET. Please add artifacts by Tuesday 1:30 ET.

**Comment by chrisdlogan** [comment]
I have uploaded lo-fi wireframes to address future versions of the map where results don't automatically update without Veterans' expressed intent. 

**Comparative Research**
The proposed functionality is based largely on the practices of Google, Yelp and airbnb, which are part of comparative research done by @lildziner which is found here: https://docs.google.com/spreadsheets/d/1sIqiSYLL6JXqaQJ3iGUnBYYjOxFLTmn0TRWeN0HcDbM/edit?usp=sharing

Also, I have included what could be a temporary fix for allowing Veterans who use screen readers to control the zoom function. This may not be necessary if we are updating the map soon, but I felt it was worth exploring and sharing out to the team.

Lastly, I have included a Search box layout exploration which re-aligns all the UI elements into one row. I'm not sure if this is feasible from a development standpoint but thought I would share. Let me know if anyone would like me to set up time to walk through these - otherwise feel free to review and send me feedback and suggestions.

**Wireframes added for review**
Provide Veterans a way to control how search results are updated in Facilities map for desktop
[Facilities Map Update Issue - Desktop.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5436049/Facilities.Map.Update.Issue.-.Desktop.pdf)
Provide Veterans a way to control how search results are updated in Facilities map for mobile
[Facilities Map Update Issue - Mobile.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5436050/Facilities.Map.Update.Issue.-.Mobile.pdf)
Provide an alternative way to zoom in and out of map by use of a selector for desktop
[Search Distance Selector - Desktop.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5436048/Search.Distance.Selector.-.Desktop.pdf)
Exploration for how to decrease height of search box for desktop
[Realign Search Box UI - Desktop.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5436053/Realign.Search.Box.UI.-.Desktop.pdf)
