### ISSUE TITLE
PW Analytics implementation for Resource and Support (Learning Center)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15066]
## Issue Description
Place holder to track any needed items from the Platform Analytics team. 
 
I want to use them to implement analytics tracking for Learning Center Analytics. 
so we can measure success of our product and make informed decisions. 

---
## Tasks
- [x] Review DL requirements from Platform team - https://github.com/department-of-veterans-affairs/va.gov-team/issues/14408
- [x] Implement analytics tracking
- [x] Give Platform team a heads up (https://github.com/department-of-veterans-affairs/va.gov-team/issues/14408)

## Acceptance Criteria
- Platform Analytics team can generate a GA dashboard for Resource and Support (Learning Center)

**Comment by kelsonic** [comment]
What needs to happen here? Not sure what work needs to get done

**Comment by ncksllvn** [comment]
Good question - did we submit a request to the VSP analytics team, and did that request come back with requirements? I think that's the usual process, but it usually takes a bit of time

**Comment by kelsonic** [comment]
We did for the feedback bread layer component, but not for any other analytics events, I feel like that's maybe what this ticket's purpose is intending?

**Comment by jenniferlee-dsva** [comment]
I believe @brianalloyd  submitted this request as part of the [collab cycle](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10953). 

But yeah, it takes time and it might not be ready in time for beta launch.

Analytics ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14408

**Comment by jenniferlee-dsva** [comment]
Referencing related Analytics team ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196

**Comment by brianalloyd** [comment]
@jenniferlee-dsva validating now, this has been on my radar for a few days but haven't received any feedback.  I'll follow up shortly.

**Comment by brianalloyd** [comment]
Closing based on Analytics team working on [#15196](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196) as it looks like final set up and tracking in underway.
