### ISSUE TITLE
Create Final Content Punchlist for CH31 and CH36 Wizards/ and Forms

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15081]
### Background
The wizards and forms for CH31 and CH 36 were reviewed by participants during usability testing. Clear trends regarding confusing language indicates that changes to text and formatting are needed.

### Considerations
New direction from business stakeholders may necessitate further review and changes to content.

### Tasks
- [x] Consider Peggy's feedback from usability prep review
- [x] Incorporate recommendations from usability testing
- [x] Update prototypes
- [x] Share list of changes to FE for implementation

### Acceptance criteria
- [x] Prototypes updated, if needed
- [x] Punchlist doc created in Github

**Comment by sporeboy** [comment]
General punchlist created in GH: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/text-revisions/CH36-punch-list-1020.md

Specific details will be added as protoype is updated.

**Comment by sporeboy** [comment]
Note: Prototypes are currently "broken" due to changes within various states. Wizard states and expanding sections may behave erratically. Variable for form completion are unlinked. Prototype will be fixed shortly...

**Comment by jason-gcio** [comment]
Holler when these prototypes are finished but there's plenty of time for this 👍
