### ISSUE TITLE
Updates to tier 1 pages and profile to account for content that has moved to R&S

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#15088]
## Issue Description
We're moving some tier 1 content over to resources and support. As a result, the sign-in FAQ will retire and content on 3 other pages will need editing and rewriting. We'll also need a redirect in place for the retiring page. And some content and links in profile need to change. 

---
## Tasks
- [x] **TASK 1.** Changes to this page: https://www.va.gov/change-address/
- Change H1 to Change your address in your VA.gov profile
- Add a link in the VA.gov profile section to the step-by-step R&S article
- Under the sign-in module with the green button, keep only this existing content:

**Will this update my address for all VA benefits and services?**
No, not at this time. Some of our departments keep your contact information in their own separate records.

If you use any of the VA benefits or services listed below, you’ll need to contact the department that handles those benefits directly to change your information.

ADD THIS CONTENT:
**Contact the department directly to update your information for these VA benefits and services:**

Education benefits
Home loan benefits
Veterans’ Mortgage Life Insurance (VMLI)
CHAMPVA
The Foreign Medical Program

[Find the contact information you need](http://preview-prod.vfs.va.gov/preview?nodeId=8473)

- [x] **TASK 2.** Changes to this page: https://www.va.gov/change-direct-deposit
- ~Remove the VBBP Q&A.~
- ~Add text and link to VBBP Q&A in R&S.~ Per conversation with SME (because they already placed urls to this existing page on printed assets to be used when they roll out an official announcement about VBBP on Veterans Day)
- Add text and link to 2 step by step articles in R&S--one for edu, one for disability and pension. Like this:
H2: More information
[How to change direct deposit information for VA disability or pension]<br>[How to change direct deposit information for VA education benefits]
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=711

- [x] **TASK 3.** Changes to this page: https://www.va.gov/?next=%2Fprofile%2F
- Replace the link under "Having trouble signing in?": Get answers to frequently asked questions
With this: Get answers to common questions about [signing in](http://preview-prod.vfs.va.gov/preview?nodeId=8222) and [verifying your identity](https://prod.cms.va.gov/node/8233). Create ticket for Nick. DONE
- Create ticket for Samara to change text and links in the profile. DONE
- Create redirect ticket for Mikki. DONE 10/23

- [x] **TASK 4.**  Notify the following stakeholders about changes to content and share preview node:
- Monica Rivera (VBBP content moving to R&S from direct deposit page) DONE
- TJ Rice (connected apps content moving to R&S from sign-in FAQ) DONE

- [x] TASK 5.  Changes to this page: https://www.va.gov/claim-or-appeal-status/ (here's the preview: http://preview-prod.vfs.va.gov/preview?nodeId=711)
- Add text and links to these new R&S articles: 
Claim status tool FAQs _(also please proof my replacement intro on this page, which matches the teaser text in the related link on Check your VA claim or appeal status: http://preview-prod.vfs.va.gov/preview?nodeId=9275)_
What your claim status means
How to check your VA claim, appeal, or decision review status online
 
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please proofread the edits I made for task 1: http://preview-prod.vfs.va.gov/preview?nodeId=709

Note: I need your help creating a jump link for that text link to the R&S article so that it jumps down to the departmental info. And I'm holding off for now adding a link to the R&S step by step article. So just disregard that in task 1 above in this ticket.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please copyedit the changes I made outlined in tasks 2 and 5 above. Then set to publish. Thanks!

**Comment by RLHecht** [comment]
The pages in task 2 and 5 have now been published.

**Comment by bethpottsVADEPO** [comment]
This work is finished.
