### ISSUE TITLE
Change all imports of formation-react in vets-website to the new NPM package

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15109]
## Issue Description
Change all imports of formation-react in vets-website to the new NPM package for Storybook

---
## Tasks
- [ ] Change all imports of formation-react in vets-website to the new NPM package

## Acceptance Criteria
- [ ] Imports of formation-reaction in vets-website go to new NPM package for Storybook 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by caw310** [comment]
Closing. Duplicate 17254
