### ISSUE TITLE
AE: Sprint 33

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#15105]
# Priorities
1. Decide on MyVA Dashboard approach
2. Continue MyVA Design work
3. Profile 2.0 508/Accessibility Review
4. Finish DD for Edu backend integration
5. Create MyVA Dashboard wrapper
6. Profile 1 cleanup

### PM
- [ ] [PM] Full Accessibility & 508 Office Audit [Profile 2.0] #15247

### Design
- [x] [Design] Connected Apps: Replace app list with App Directory Link #15234 (new)

### Build
- [x] [FE] Connected Apps: Replace app list with App Directory Link #15235 (new)
- [ ] [FE] Create comprehensive e2e tests for address validation #14987
- [x] [FE] Clean up `isVeteran` and `veteranStatus` and `servedInMilitary` in redux store #14610
- [x] [FE] Use new controlInformation.paymentAddressExistIndicator #3992
- [ ] [FE] Rename "vet360" references to "vapSvc" #6268
- [x] [FE] Make feature flag for Dashboard v2 #14913
- [x] [FE] Move/rename reused code from Profile 1 to appropriate folders #14860
- [x] [FE] Connected apps content change #15293

### Design
- [x] [Design] MyVA Dashboard: Revisit Direction/Wireframe explorations (mobile & desktop) #15115

### Dev 
- [x] [FE] Make wrapper for Dashboard #14915

## Direct deposit for Edu
- [x] [BE] Create BGS CH33 DDEFT Service integration #13286
- [x] [Design] Content Review for EDU Direct Deposit #15078
- [x] [Design] Content for Direct Deposit Landing Page #14367
- [ ] [Design] Research Plan for Usability Testing of EDU Direct Deposit #13807 (Stretch goal)

## Unplanned: QA, 508, bugs, or other fixes
- [x] Stop using ESR to determine if a Veteran is enrolled in health care #15304
