### ISSUE TITLE
Upgrade Grafana to 7.2+

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#15126]
## Description
Grafana version 7.2 provides some UX enhancements specific for Loki, which would be nice to have.

## Background/context/resources
This is a minor version upgrade so should be relatively low risk.

## Technical notes
- @pnwstevan provided detailed documentation for an upgrade of 6->7 in [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12322).
- Current release is 7.2.2 [https://github.com/grafana/grafana/releases/tag/v7.2.2](https://github.com/grafana/grafana/releases/tag/v7.2.2)

---
## Tasks
- [ ] Test update locally
- [ ] Deploy to Utility

## Definition of Done
- [ ] Grafana in VSP utility is upgraded to 7.2+
- [ ] Log parsed fields can be toggled [see here](https://grafana.com/docs/grafana/latest/explore/#toggle-parsed-fields)

---

**Comment by omgitsbillryan** [comment]
Testing Grafana Migrations Locally

1. Setup postgres locally using docker
```
docker pull postgres:9.5.24-alpine
docker run --publish 5432:5432 --rm --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres:9.5.24-alpine
```
2. Find your vagrant default gateway (mine was `10.0.2.2` which I think is common)

```
vagrant ssh
...
netstat -rn | grep "^0.0.0.0 " | cut -d " " -f10
```

3. Modify grafana config to point to postgres on the host
```
#################################### Database ####################################
[database]

type = postgres
host = 10.0.2.2:5432
name = postgres
user = postgres
password = mysecretpassword

...

#################################### Session ####################################
[session]

provider = postgres
provider_config = user=postgres password=mysecretpassword host=10.0.2.2 port=5432 dbname=postgres sslmode=disable
```

4. Start grafana in Vagrant
```
PORTS=3000 APP=grafana-vagov vagrant up --provision-with build
```

5. (Optional) Verify connectivity from vagrant to postgres
```
ssh vagrant
sudo yum install -y postgresql95

[root@localhost ~]# pg_isready --host=10.0.2.2 --port=5432 --username=postgres
10.0.2.2:5432 - accepting connections
```

6. Navigate in your browser to `http://localhost:3000` and login to grafana with default credentials of `admin:admin` 🎉  ... I found that using `grafana-cli admin reset-admin-password <new password>` didn't work when using postgres. I never saw an error message, but my new password never worked when trying to log in. Instead, it's possible to manually change the password directly in the DB - hopefully you don't need to 😄 , but this will set the the `admin` password back to `admin`:

```
docker exec -it <postgres container id> bash
bash-5.0# psql -U postgres
postgres=# UPDATE "user"
SET password = '59acf18b94d7eb0694c61e60ce44c110c7a683ac6a8f09580d626f90f4a242000746579358d77dd9e570e83fa24faa88a8a6',
salt = 'F3FAxVm33R' WHERE login = 'admin';
```

At this point you should be able to create dashboards & charts, and any other application data that you'd expect to be stored in the db. Once you've done so, you can [modify the version](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/grafana-vagov/vars/main.yml#L2) as you desire and re-run the build in vagrant.

**Comment by omgitsbillryan** [comment]
[An important tidbit](https://codesposts.com/Wg04jK59) when migrating from pre 7.2 to 7.2+:

> Before Grafana v7.2 alert notification channels did not store sensitive settings/secrets such as API tokens and password encrypted in the database. In Grafana v7.2, creating a new alert notification channel will store sensitive settings encrypted in the database.
...
> For existing alert notification channels, there is no automatic migration of storing sensitive settings encrypted, and they will continue to work as before. Migration must be done manually. Opening a configured alert notification channel in the UI and saving it will store sensitive settings encrypted and at the same time reset the historic unencrypted setting of that alert notification channel in the database.

**Comment by omgitsbillryan** [comment]
Upgrade went off w/o a hitch to `7.2.2`.
![image.png](https://images.zenhubusercontent.com/59c291c1b0222d5de4787932/a3d6a64d-9afc-4a05-803e-3143af82b6e0)

I'm holding off on opening and re-saving the alert channels in the Grafana UI so that if we need to downgrade for some reason, they will continue to work.
