### ISSUE TITLE
Upload 686 Supporting Documents to VBMS

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#15129]
## Background
We need to upload documents (supporting evidence) attached to a 686 submission to VBMS.  Examples of this are marriage certificate, adoption certificate, etc.

## Considerations
- Verify that the attached documents indicator is being set correctly.  This will be used when the form is submitted.

## Tasks
- [x] Check to see whether supporting documents are attached to the claim.
- [x] Retrieve the documents from the in-flight database/storage during the submission workflow.
- [x] Upload supporting evidence to VBMS when the 686 is submitted.

## Acceptance Criteria
- [x] Documents end up where they need to be
- [x] Write a test for coverage, if needed
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5329
