### ISSUE TITLE
Proofread all R&S articles for MVP 1.0 before publishing

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15128]
## Issue Description
We need to ensure all R&S articles are free of typos, links are working. there is consistency in headers and other elements across articles among other things. 

Here is a list of items to look for and verify in each node:
- Bolding of ID.me, My HealtheVet, and DS Logon
- All links are working
- Standardize this language when hours and phone numbers are referred to: We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
- Look for places where we say, “see above” or refer in some other way to content that’s no longer a part of the same article you’re in (since we split up the sign-in FAQ into different articles).
- Spell out abbreviations in individual answers since they can be used in other articles as well
- Check that phone numbers contain aria labels
---
## Tasks
Check off when each node has been proofread:

- [x] Signing in to VA.gov preview-prod.vfs.va.gov/preview?nodeId=8222
- [x] Verifying your identity on VA.gov preview-prod.vfs.va.gov/preview?nodeId=8233
- [x] Privacy and security on VA.gov preview-prod.vfs.va.gov/preview?nodeId=8249
- [x] Managing your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8259
- [x] Change your address on file with VA preview-prod.vfs.va.gov/preview?nodeId=8473
- [x] Direct deposit preview-prod.vfs.va.gov/preview?nodeId=8423
- [x] Connecting third-party apps to your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8471
- [x] Helpful VA phone numbers preview-prod.vfs.va.gov/preview?nodeId=8427
- [x] How to change your address in your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8417
- [x] How to change direct deposit information for VA education benefits preview-prod.vfs.va.gov/preview?nodeId=8474
- [x] How to change direct deposit information for VA disability or pension preview-prod.vfs.va.gov/preview?nodeId=8434
- [x] DS Logon accounts preview-prod.vfs.va.gov/preview?nodeId=8483 CMS NEEDS TO FIX ACCORDION ISSUE
- [x] My HealtheVet FAQs preview-prod.vfs.va.gov/preview?nodeId=8487
- [x] Commissary and exchange privileges preview-prod.vfs.va.gov/preview?nodeId=8490
- [x] How can I find a VA facility? preview-prod.vfs.va.gov/preview?nodeId=8491
- [x] Veteran Identification Card (VIC) preview-prod.vfs.va.gov/preview?nodeId=8498
- [x] How to get a Premium DS Logon account online preview-prod.vfs.va.gov/preview?nodeId=8503
- [x] Get a Premium My HealtheVet account preview-prod.vfs.va.gov/preview?nodeId=8507
- [x] What your claim status means http://preview-prod.vfs.va.gov/preview?nodeId=8548
- [x] How to check your VA claim or appeal status online http://preview-prod.vfs.va.gov/preview?nodeId=8520
- [x] Request a discharge upgrade or correction http://preview-prod.vfs.va.gov/preview?nodeId=8541
- [x] How can I be rated competent and exit the Fiduciary Program?http://preview-prod.vfs.va.gov/preview?nodeId=8540 
- [x] What’s VA's policy regarding service dogs? http://preview-prod.vfs.va.gov/preview?nodeId=8538
- [x] What if I'm having problems opening a PDF on VA.gov in my web browser? https://prod.cms.va.gov/node/8684
- [x] Claim status FAQs http://preview-prod.vfs.va.gov/preview?nodeId=9275 

## Acceptance Criteria
- [x] All nodes have been proofread
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Collecting some tasks for you here:
- I tried to create a jump link for the button on the commissary article, but it doesn't work. Can you try to fix that for me?
- Please create the same jump link for this text in the second accordion: Veteran Health Identification Card (VHIC)--this is in running text, so it'll be an embedded link in that sentence.
- Make sure the H1 makes sense for the template, e.g. it's not in the form of a question if it's in a detail page template. Questions should only be used for single Q&As. 
- Make sure we delete one of these once we decide which one to go with (I'm having trouble with the demo environment and would like to see them there first before deciding): 
preview-prod.vfs.va.gov/preview?nodeId=8684
preview-prod.vfs.va.gov/preview?nodeId=8539

I'll keep adding notes here for you for Monday.

**Comment by RLHecht** [comment]
**FOR TUESDAY** On Verifying ID page node 8233 the first CTA button is giving us an error message. Per Steve Kovaks: you cannot link directly to the "new registration" workflow, since the session must first pass through SSO now. Need to find a new link.

**Comment by RLHecht** [comment]
All of these nodes have been proofread. I've added the CTA buttons to the bottoms of the longer nodes. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
@bethpottsVADEPO All related info teasers now match their H1a

**Comment by RLHecht** [comment]
Closing out this ticket. Will open a new one for publishing content on prod. FYSA @brianalloyd @bethpottsVADEPO
