### ISSUE TITLE
Create Storyboards for VRE Orientation in CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15133]
## Background
Given what we have from VRE around orientation, we need to include that content into the CH31 feature.

## Considerations
- Everything that we were given should be included 
- The intent from the business is for the Veteran to click "Next" all the way through to the form before completing the eligibility wizard
- Link shared in slack (Jason : Jim)

## Tasks
- [x] Create thumbnail story boards of where all the parts to the VRE Content will reside

## Acceptance Criteria
- [x] Thumbnails have been created and shared with the team

**Next steps:**
- [x] The prototype has been updated and shared with the team

**Comment by sporeboy** [comment]
I have my initial storyboards built here: https://xd.adobe.com/view/5ec99f25-03c5-4a2e-864e-62e0425b37e5-0b9a/

Four concepts:
- Modal
- Carousel
- Accordians
- Wizard
