### ISSUE TITLE
Discovery: What would it take to remove the formation-react package from the VFS tools repo?

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15136]
## Issue Description
Discovery needed around identifying what would it take to remove the formation-react package from the VFS tools repo

---
## Tasks
- [ ] Discovery 
- [ ] Remove the formation-react package from VFS tools repo

## Acceptance Criteria
- [ ] Team knows what needs to be done to remove the formation-react package from VFS tools
- [ ] Removal of the formation-react package from VFS tools repo
---

**Comment by bkjohnson** [comment]
This is happening now. Here is what all has gone into it, and what remains to be done:

## So Far

- Moved code into new `component-library` repo using `git subtree`
- Resolved lerna-related dependency and config issues
- Fixed build/test processes so that tests will actually run

## Remaining

- Move the CI storybook publishing into the new repo
- Publish the new package
- Deprecate `formation-react` on npm
- Update `vets-website` to use the new package
- Update the Gatsby docs site to use the new package
- Remove `packages/formation-react` from the tools repo
