### ISSUE TITLE
CH31 - Update Address Schema Import

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#15130]
## Description
Chapter 31 still uses the address schema import from the 686c-674 schema. Recently we created a form agnostic version of the address schema. This new version should replace the current import. 

## Tasks
- Update the chapter 31 schema in vets-json-schema to use the new address model
- Update the chapter 31 application in vets-website so it uses the new address schema / uiSchema

## Acceptance Criteria
- [ ] PR into `vets-json-schema` to update version number, chapter 31 schema
- [ ] PR into `vets-website` to update package.json, chapter 31 schema, unit tests
- [ ] PR into `vets-api` to update Gemfile.lock entry
