### ISSUE TITLE
Initial Integration with VRE API

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15143]
## Background
The VR&E team has provided some endpoints for us to use and we need to ensure we have what we need to integrate with that service.

## Considerations
Per Steve: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/VA-Systems/vre-cms/cms-endpoints.md

## Tasks
- [x] Work with devops about setting up a proxy, learn what is entailed
- [x] Gain access to a token
- [x] Access the JSON payload

## Acceptance Criteria
- [x] Document findings and recommendations for next steps are in [this location](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/engineering) as an .md file.
