### ISSUE TITLE
Add pension questions to 686c

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15141]
# Background
The pension line of business has asked us to add a few questions about income inside a few of the workflows for the 686c. The questions/ workflows are -

- When adding dependent, an optional `yes, no` question: "Did this dependent have income in the last tax year?"
- When adding dependent, at the end of the workflows ad a page with one `yes, no` question: "Did the household have a total income of less than $190,000 in the last tax year?"

The three "add dependent" workflows are:

- Add child
- Add spouse

We will also need to update the copy on the intro page of the form -

NEED TO ASK WHAT THE SPECIFIC CONTENT UPDATES ARE
✔Asked in Slack: https://dsva.slack.com/archives/CLY6Q69RV/p1603311546122400

## Tasks
- [x] Add questions to workflows in `vets-json-schema`
- [x] Submit a PR to `vets-json-schema`
- [x] Import new questions from `vets-json-schema` and add text for questions in `vets-website`
- [ ] Add new text to intro page
- [ ] Submit a PR for `vets-website`

## Acceptance criteria
- [ ] The pension questions have been added to the correct dependent workflows
- [ ] The intro text has been updated to include details of the pension questions
- [ ] PRs have been submitted for `vets-json-schema` and `vets-website` for review

**Comment by micahchiang** [comment]
For reference - https://github.com/department-of-veterans-affairs/va.gov-team/issues/8779

Also, @cohnjesse can you confirm with @sporeboy, @jason-gcio, or @steve-gov about the Add student workflow? That workflow already contains existing questions about a student's income and net worth. I think I recall Steve saying it was just needed on add child and and spouse.

**Comment by cohnjesse** [comment]
@micahchiang I confirmed we do not need these questions added to the Add Student workflow
