### ISSUE TITLE
[Support Slackbot] Set up in EKS Utility cluster

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#15142]
## Description
Currently the VA Support bot uns in Heroku. In discussing with @f1337 there are a number of good reasons to have this running in VSP infrastructure.

## Background/context/resources
[(old support bot repo)](* Source/config here : https://github.com/department-of-veterans-affairs/va.gov-support-slackbot)

## Technical notes
[New support bot repo](https://github.com/department-of-veterans-affairs/platform-support-slackbot
)
Slack now allows direct web sockets connection. Rather than Slack needing to send a message directly, the bot polls / opens a socket to slack which means that it only needs outgoing access. Don't have to open up the firewall to achieve this. 
Alex rewrote the bot to use the sockets. 

---
## Tasks
- [ ] ECR Repo 
- [ ] EKS Manifest 
- [ ] Path in parameter store for storing variables 
- [ ] Need repo automation to build an push the container to ECR and do release
- [ ] Deploy in utility 
- [ ] Determine ownership of this

## Definition of Done
- [ ] Support bot is running in EKS (utility) 
- [ ] Decommission Heroku support bot (Michael Fleet can do this)

**Comment by pnwstevan** [comment]
CC: @f1337 @dginther

**Comment by jhouse-solvd** [comment]
@dginther recently did this with the Pact broker and so would be a good resource for anyone on Ops wanting to take on this task.

**Comment by jhouse-solvd** [comment]
Need to tie up or reference any duplicate tickets, and move to an epic/initiative related to setting up new apps in EKS and or Platform improvements. Removing from the maintenance epic.

**Comment by jhouse-solvd** [comment]
@rmtolmach - I was wondering if we should use the new [application onboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+eks%2C+kubernetes%2C+infrastructure%2C+infrastructure-request&template=kubernetes-onboarding-template.md&title=%5BInsert+app+name+here%5D+-+Application+onboarding+infrastructure+request) to create a new request for this? 

If you decide to do that, we can link to the new issue and close this out.

**Comment by rmtolmach** [comment]
Closing. Jesse and I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/38455 to cover this.
