### ISSUE TITLE
Centralized Logging with Loki - Perform user research to understand how VFS developers will use this solution 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15140]
## Issue Description
We want to use customer research to inform our planned implementation for new and improved logging solution (Loki)

---
## Tasks
- [x] Connect with Service Design team to discuss research opportunities
- [x] Make a plan
- [x] Recruit participants
- [x] Conduct sessions
- [x] Synthesize
- [x] Read out

## Acceptance Criteria
- [x] Operations team will have information and feedback from users to iterate on the user guide and requirements for launching Loki in Production
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Reached out to Service design team in [this slack thread.](https://dsva.slack.com/archives/CPCGRR7F1/p1603736046088800). James Chasia is out this week, but will connect with him upon his return.

**Comment by jhouse-solvd** [comment]
The Service Design team recently helped us to perform user research with a handful of VFS developers. They have provided a research synthesis and we will be scheduling a readout with OCTO-DE in the very near future.

**Comment by jhouse-solvd** [comment]
The readout was performed and the user guide was updated based on findings. 

The user guide has been published on the platform website [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/Centralized-Logging-with-Loki-and-Grafana.619119010.html).

Closing.
