### ISSUE TITLE
[UI] Questionnaire Manager and Print PDF Refinement

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15158]
## User Story
- Veterans need the ability to manage their questionnaire list on va.gov in addition to receiving a notification to complete the form. The Veteran also needs the ability to view and print completed questionnaires.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Feature - Questionnaires List](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/questionnaire-manager.md)

## Description
There were a few questions outstanding at the end of ticket #14312 on the Questionnaire Manager and print PDFs. This story will work to answer those questions.

**Questionnaire Manager Questions:**
1. In the alert box when a Veteran doesn't have any questionnaires to display, can we provide a meaningful phone numbers to include within a second sentence here?
- Wording from Peggy for second sentence... If you think this is an error, [what would be the CTA to give users????]
- Based upon Oct. 21 team meeting, @mlighdc to look into this.

**Print PDF Questions**
1. Look into how PDFs are displayed on va.gov. 
- Do they open in a new tab, then you can download from that tab? _This is the assumed behavior, but confirm._
- Do they automatically download?

2. Look into adding more information to the PDFs, including...
- Clinic name
- Appointment date
- Submitted/not submitted status and submitted date
- Three personal identifiers on every page.

## Tasks
> this is a list of design tasks that are needed for this ticket 
- [x] Answer the above questions
- [x] Finalize detailed mockup and callouts of Questionnaire List and Print PDFs 
   - [Sample PDF of final design](https://app.zenhub.com/files/133843125/a92029ae-049a-48c5-8339-ca5a7f955382/download)
   - Zeplin link of PDF design
      - [Page 1](https://zpl.io/agwryL1)
      - [Page 2](https://zpl.io/a7rWqeY)
      - [Complete wireframe set accessible to everyone](https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780)

## Acceptance Criteria
> when is the ticket done 
- [x] UI review meeting with team for feature capabilities and engineering callouts
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
Discussed the above phone number scenario today with @mlighdc via Slack. It was decided to not include any phone numbers at this time for this particular scenario.

**Comment by kristenmcconnell** [comment]
[Sample PDF of final design](https://app.zenhub.com/files/133843125/a92029ae-049a-48c5-8339-ca5a7f955382/download)
