### ISSUE TITLE
Test / Research Possibility of Switching to CentOS 8 for Underlying AMI Base Layer (Instead of AMZN Linux 1)

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#15166]
## Issue Description
Test for issues / possibility of moving from Amazon Linux 1 base AMI layer to CentOS 8. Due to issues found with Amazon Linux + Python 3 + Ansible, there would essentially no best practice compliant way to get rid of Python 2 entirely while using Amazon Linux and Ansible. This ticket is to track some testing / any findings for the possibility of moving over to CentOS 8 for our AMI base layer.

---
## Tasks
- [ ] Switch to CentOS 8 base AMI layer in another branch and test out some jobs to see if/what issues arise. 

## Acceptance Criteria
- [ ] CentOS 8 properly tested with numerous jobs and findings delivered back to team.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Closing at this time. Please see [ADR-0003](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/adr/0003-continue-leveraging-python-2.md).
