### ISSUE TITLE
Synthesize Vet Center research (related to services, taxonomy and language improvements)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15197]
**Due to the volume of information gathered during this research, synthesis will be broken into parts**

## Issue Description
Synthesize Vet Center research findings from sessions conducted in October 2020. 

**Goal of research**
The goal of this study is to understand a Vet Center client’s experience, impression and relationship with Vet Centers.

**Research questions**
How do Veterans and service members first learn about Vet Centers?
What is the client experience for different demographics?
What services, resources or activities are most valuable to Veterans, service members and their families?
How long do clients typically engage with Vet Centers and does their engagement or opinion of Vet Centers change over time?
What information do Veterans and service members want or expect to see on a website?

**Hypothesis**
Current clients have a favorable view of Vet Centers and the services that they offer and view them as distinct entities from other VA facilities.

---
## Tasks
- [ ] Synthesize findings of research _**as it relates to services, taxonomy and language improvements**_

## Acceptance Criteria
- [ ] Research readout
- [ ] Recommendations for changes to taxonomy and language
- [ ] Recommendations for services within next iteration of design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
[Synthesis spreadsheet](https://adhocteam-my.sharepoint.com/:x:/g/personal/leyda_hughes_adhocteam_onmicrosoft_com/EYZ6B8_w_GJGi93wBq3_x8MBZ4zZgwE9V7earuu0MfDeRg?e=a0vIfE)
