### ISSUE TITLE
Add aria labels to all R&S phone numbers

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15195]
## Issue Description
When the CMS team updated Drupal to the new rich text field, it didn't allow for aria labels around phone numbers. They have now fixed it, but all aria labels will still need to be put in for phone numbers.

Nodes to review:

 - [x] Signing in to VA.gov preview-prod.vfs.va.gov/preview?nodeId=8222
- [x] Verifying your identity on VA.gov preview-prod.vfs.va.gov/preview?nodeId=8233
- [x] Privacy and security on VA.gov preview-prod.vfs.va.gov/preview?nodeId=8249
- [x] Managing your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8259
- [x] Change your address on file with VA preview-prod.vfs.va.gov/preview?nodeId=8473
- [x] Use direct deposit to receive your VA benefit payments preview-prod.vfs.va.gov/preview?nodeId=8423
- [x] Connected apps preview-prod.vfs.va.gov/preview?nodeId=8471
- [x] Toll-free phone numbers for help with your benefits preview-prod.vfs.va.gov/preview?nodeId=8427
- [x] How to change your address in your VA.gov profile preview-prod.vfs.va.gov/preview?nodeId=8417
- [x] How to change direct deposit information for VA education benefits preview-prod.vfs.va.gov/preview?nodeId=8474
- [x] How to change direct deposit information for VA disability or pension preview-prod.vfs.va.gov/preview?nodeId=8434
- [x] DS Logon accounts preview-prod.vfs.va.gov/preview?nodeId=8483
- [x] My HealtheVet accounts preview-prod.vfs.va.gov/preview?nodeId=8487
- [x] Commissary and exchange privileges preview-prod.vfs.va.gov/preview?nodeId=8490
- [x] How can I find a VA facility? preview-prod.vfs.va.gov/preview?nodeId=8491
- [x] Veteran Identification Card (VIC) preview-prod.vfs.va.gov/preview?nodeId=8498
- [x] How to sign up online for a Premium DS Logon account preview-prod.vfs.va.gov/preview?nodeId=8503
- [x] Sign up for a Premium My HealtheVet account preview-prod.vfs.va.gov/preview?nodeId=8507
- [x] How can I find out the status of my VA claim or appeal? http://preview-prod.vfs.va.gov/preview?nodeId=8504
- [x] What types of claims and appeals can I track online? http://preview-prod.vfs.va.gov/preview?nodeId=8514
- [x] What you can learn from the claim tracking tool http://preview-prod.vfs.va.gov/preview?nodeId=8528
- [x] What your claim status means http://preview-prod.vfs.va.gov/preview?nodeId=8548
- [x] Managing your documents with the claim status tool http://preview-prod.vfs.va.gov/preview?nodeId=8523
- [x] How to check your VA claim or appeal status online http://preview-prod.vfs.va.gov/preview?nodeId=8520
- [x] How do I get my discharge upgraded or changed? http://preview-prod.vfs.va.gov/preview?nodeId=8541
- [x] How can I be rated competent and exit the Fiduciary Program? http://preview-prod.vfs.va.gov/preview?nodeId=8540
- [x] What’s VA's policy regarding service dogs? http://preview-prod.vfs.va.gov/preview?nodeId=8538
- [x] What if I'm having problems opening a PDF on VA.gov? https://prod.cms.va.gov/node/8539
---
## Tasks
- [x] Go through each node and add aria labels to any phone numbers and TTY numbers (Randi)

## Acceptance Criteria
- [x] All phone numbers in R&S contain aria labels
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
All phone numbers mentioned are now in aria labels. Closing ticket. FYSA @brianalloyd
