### ISSUE TITLE
Staging Review – Public Websites [Resources and Support]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15209]
## Steps to complete Staging Review: 

- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Attach all artifacts before requesting the meeting
- [X] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] Staging Review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on **Resources and Support**
- [x] **Public Website Team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp)
- Link to [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/release-plan-1-0-beta.md) 
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
- Link to your product [test cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&group_id=214)/[test plan](https://dsvavsp.testrail.io/index.php?/plans/view/685) in TestRail with test execution logs. _Also reference_ [#11581](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11581)
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/142) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/143) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete: [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14774)
- [List of known issues](https://dvagov-my.sharepoint.com/:x:/g/personal/jennifer_lee27_va_gov/EZa-HjZGS-xBuTyi9SI2KzABQlkiP0BvBUQcqu9IdIiZ_Q?e=lArpqP) (with links to tickets when applicable)
  

## Meeting attendees from **requesting team**
- Product Manager (required): **Brian Lloyd**
- DEPO product lead (required): **Jennifer Lee**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Nick Sullivan** **Kelson Adams** **Oksana Cyrwus**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (**10/29/2020 1:30 EST**), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and shira will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by shiragoodman** [comment]
hi @brianalloyd  - we have 10/29 @ 1:30 pm already reserved. Please review the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) to find open timeslots.

**Comment by brianalloyd** [comment]
Thanks @shiragoodman my bad, Sorry.  Can we do 10/29 2:30-3:00(3:30) (or what ever time is needed for the typical review).  Thanks for working the details.

**Comment by 1Copenut** [comment]
@brianalloyd && @jenniferlee-dsva Good afternoon! VSP is preparing work on this staging review. Can you provide a list of URLs that should be reviewed?

**Comment by brianalloyd** [comment]
@1Copenut (Trevor) I'm including the links below for Demo site and page features for R&S.  Looping in @jenniferlee-dsva in the event she has other links or elements for review.  Fairly new to this process so please let me know if their are standard items you would like to review in support of the Staging Review.  Thanks.

Demo Site for Staging/QA: http://learningcenter.web.demo.ci.cms.va.gov/resources/

URL: www.va.gov/resources/account-and-profile/
BC: Home > Resources and support > All articles in: Account and profile
Example H1: Frequently asked questions (FAQs) about signing in to VA.gov

URL: www.va.gov/resources/frequently-asked-questions-faq-about-signing-in-to-va-gov/
BC: Home > Resources and support > Frequently asked questions (FAQs) about signing in to VA.gov
URL: www.va.gov/resources/account-and-profile/frequently-asked-questions-faq-about-signing-in-to-va-gov/
BC: Home > Resources and support > Account and profile > Frequently asked questions (FAQs) about signing in to
VA.gov
Tag landing page
Tag: Claims and appeals status

H1: All articles tagged: Claims and appeals status
URL: www.va.gov/resources/tag/claims-and-appeals-status/
BC: Home > Resources and support > All articles tagged: Claims and appeals status
Search results page
Example search: claim status

H1: Search results for: "claim status"
URL: www.va.gov/resources/search/?query=claim+status
BC: Home > Resources and support > Search results for: "claim status"

**Comment by jenniferlee-dsva** [comment]
@1Copenut @brianalloyd  - I added demo URLs ^, as the live URLs will not be working yet. 

For IA, URL and breadcrumb patterns in the learning center, see Mikki's IA doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-learning-center.md

**Comment by tlei123** [comment]
@pjhill , QA Test Cases/Plan and Report links updated above in main Description.  cc @brianalloyd

**Comment by emilywaggoner** [comment]
Hello @brianalloyd! Would you be able to post screenshots of the pages needing review? Some of our reviewers (including me) don't currently have CAG access to see the demo screens. Thank you!

**Comment by brianalloyd** [comment]
Hi @emilywaggoner let me see what I can put together really quickly in support.  I'll follow up soonest, thanks.

**Comment by peggygannon** [comment]
@brianalloyd I don't have any content feedback to add for this round.

**Comment by brianalloyd** [comment]
@peggygannon checking to validate we answered your questions during staging review?  If not, let me know and I can go into more detail in support.  

@emilywaggoner still working screen shot, but figured I would send a copy of our [mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b) for review in the interim.

**Comment by peggygannon** [comment]
@brianalloyd No, I think we're good, based on the conversation in the meeting. Thanks for following up!

**Comment by allison0034** [comment]
@brianalloyd looking at the Mural board, I see the accordions are all expanded. Is it going to be this way in production or was it done like this in Mural to show the content?

**Comment by allison0034** [comment]
@brianalloyd Emily and I will provide feedback by EOD

**Comment by brianalloyd** [comment]
@allison0034 to answer your above questions, Yes the accordions will expand in production environment.  Let me know if you have any other questions and thanks again for the support.
