### ISSUE TITLE
Add Storybook to formation-react package

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#15210]
## Issue Description
Like it says on the tin, the goal here is to add Storybook to `formation-react` for use in development only. Publishing the result will come later.

---
## Tasks
- [ ] Add Storybook to `formation-react`

## Acceptance Criteria
- [ ] Engineers can use Storybook to aid development of components
- [ ] Publishing `formation-react` doesn't publish any Storybook artifacts
