### ISSUE TITLE
Publish generalized health tool h1s, intros, meta descriptions to support Cerner launch

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#15223]
## Issue Description
To support the 10.24.20 Cerner health tools launch, we need to publish the generalized health tool h1s, intros, and meta descriptions that remove specific mentions of MHV and debrand terms like "secure messaging" to make them lowercase.

Pages include:
https://prod.cms.va.gov/health-care/refill-track-prescriptions 
https://prod.cms.va.gov/health-care/view-test-and-lab-results
https://prod.cms.va.gov/health-care/secure-messaging
https://prod.cms.va.gov/health-care/get-medical-records

---
## Tasks
- [x] Update pages in Drupal (Danielle)
- [x] Review and publish pages in Drupal (Randi)

## Acceptance Criteria
- [x] Content live on site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
All these changes have been reviewed and the pages published.

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing ticket. FYSA @DanielleThierryUSDSVA @brianalloyd
