### ISSUE TITLE
[Analytics] Profile 2.0: Is it possible to add error codes to the address validation dashboard?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15237]
## Background

In the last month, we've seen random but huge spikes in errors for address updates on the [address validation dashboard](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/). I suspect that these are largely due to issues with MPI that I've seen mentioned in Slack, but it would be super helpful if we could see the error codes/types we get back from VA Profile on our GA dashboard in order to confirm this. Is something like this possible? We see error types for direct deposit, though not necessarily error codes, so let me know what GA might have access to.

## Tasks

- [x] Confirm receipt of this ticket.
- [x] Determine whether adding error codes/types to the GA dashboard is possible. Let Samara know either way.
- [ ] If possible, implement that update.

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 for awareness

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss Unfortunately after looking into this, it doesn't look like there are error codes for the address validation updates like there are for direct deposit. Let me know if there is anything else I can assist you with in regards to this request.

**Comment by Samara-Strauss** [comment]
Are you sure? We get sent error codes from our backend partner (VA Profile), so I know we get error codes. How are we getting the error codes for direct deposit? Those are also sent to us from the backend, so I'm wondering how we made that work.

**Comment by bmcgrady-ep** [comment]
Hi @Samara-Strauss - It doesn't look like we currently have error code data in Google Analytics, but this may be something that can be implemented if the error codes are currently being sent from the backend. 

I have a couple of questions regarding the data:
1. Where does the data currently live?
2. What is the backend system (Grafana or Sentry)?

**Comment by Samara-Strauss** [comment]
> What is the backend system (Grafana or Sentry)?

Let me track down an answer to this.

**Comment by Samara-Strauss** [comment]
> Where does the data currently live?

The data comes to us through a VA Profile integration, but I'm not sure where it lives per se. Asking Lihan in Slack.

**Comment by Samara-Strauss** [comment]
@bmcgrady-ep — @lihanli said the following:

> the error codes are here: https://qa.vet360.va.gov:7005/address-validation/swagger/address-v1-msg-keys.html
some of the errors are tracked in sentry, but address not found errors are not

So, most errors are in Sentry, and the error codes can be seen in the swagger docs. If you have further questions about that, @lihanli would be the best person to talk to.

**Comment by Samara-Strauss** [comment]
Giving this a gentle bump. @bmcgrady-ep — are you able to work with the information Lihan mentioned above?

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - Thanks for reaching out. After doing some research, I believe we are going to have to do an analytics implementation to get the address validation error codes and provide a Data Layer spec as part of that process. 

cc @jonwehausen

**Comment by Samara-Strauss** [comment]
Thanks for letting me know. Is there anything my team needs to do to help with this?

**Comment by joanneesteban** [comment]
Thanks, @Samara-Strauss our next step is to provide you all with the datalayer code. @bmcgrady-ep will get back to you!

**Comment by Samara-Strauss** [comment]
OK, thanks for letting me know!

**Comment by bmcgrady-ep** [comment]
## Datalayer Requirements
cc: @Samara-Strauss @jonwehausen @bsmartin-ep 

### **When the veteran clicks 'Add' or 'Edit' and the API call is made to suggest an address and the service is unavailable or an unexpected error occurs**
![image](https://user-images.githubusercontent.com/66263904/98839389-b4653c00-2402-11eb-8aaf-95bce9f76579.png)
```javascript
dataLayer.push({
  'event': 'profile-edit-failure',
  'profile-action': 'address-suggestion-failure',
  'profile-section': 'home-address' //or 'mailing-address'
  'error-key: 'other-error-enroll',
});
```

**Comment by Samara-Strauss** [comment]
@bmcgrady-ep do you need help from a FE dev at this point?

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - We will need a developer to make the changes to the dataLayer.

**Comment by Samara-Strauss** [comment]
@bmcgrady-ep OK, I will create a ticket for the data layer implementation.

**Comment by Samara-Strauss** [comment]
FE implementation in #16088

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

Looks like the`profile-edit-failure` tag in GTM is already passing in `error-key` so you should be OK.  I would just double check the developers clear out  `error-key` dataLayer param after they send in the event so it doesn't stick to any other events.

![image](https://user-images.githubusercontent.com/62304138/99012800-1ade7d00-251d-11eb-9b2f-e76595e0daf0.png)

**Comment by Samara-Strauss** [comment]
@bsmartin-ep @bmcgrady-ep if you have additional guidance for frontend, please put it in the frontend implementation ticket, which is #16088.

**Comment by Samara-Strauss** [comment]
@sanlouise @bsmartin-ep @bmcgrady-ep — I am still not seeing the error codes in the [address validation report](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/) despite Sandra's PR for this work going out yesterday ([comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16088#issuecomment-733009965)). Not sure if this is a code issue or a GA issue, so tagging everyone here. Can you all figure out where the issue might be?

**Comment by sanlouise** [comment]
It appears the deploy went out successfully, so it _should_ not be a code issue. There is a slight possibility that it is not recording the exact string you were looking for, but the `event-key` _should_ populate.

@bsmartin-ep and @bmcgrady-ep In case you can confirm it is not a GA issue as far as you are concerned, I can do a deeper dive to understand what might be wrong.

**Comment by Samara-Strauss** [comment]
Thanks, @sanlouise! @bmcgrady-ep @bsmartin-ep can you please look into this and let me know what you find? Thanks!

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

You expect to see these as a new row in this widget, correct?

![image](https://user-images.githubusercontent.com/62304138/100246783-92da7900-2f07-11eb-93ab-a1d6c580dbff.png)

@bmcgrady-ep -

When I trace the `Home Address - Suggestion Failure` and `Mailing Address - Suggestion Failure` custom metrics, I see them set in [custom JS tags like this](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000378/variables/809) which look for certain profile actions:

![image](https://user-images.githubusercontent.com/62304138/100246975-cfa67000-2f07-11eb-80f8-7b0c04a7983b.png)

When I [look at Sandra's PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15053/files), I see a different profile action event being updated:

```js
event: 'profile-edit-failure',
'profile-action': 'save-failure',
'profile-section': analyticsSectionName,
'error-key': `${metaData?.code}-address-save-failure`,
```
Or am I missing something?

**Comment by Samara-Strauss** [comment]
@bsmartin-ep I am expecting to see the error codes that are causing those errors, like we have in the direct deposit dashboard:

<img width="1024" alt="Screen Shot 2020-11-25 at 10 28 58 AM" src="https://user-images.githubusercontent.com/34068740/100248181-295b6a00-2f09-11eb-8c59-ace7bd786b5e.png">

Having the count of the number of errors/fails is helpful, but we are seeing a much higher rate of errors than usual, and I am trying to to figure out what is going on. I need the error codes that are passed through from the backend for that.

**Comment by sanlouise** [comment]
@bsmartin-ep Not sure if it was clear, but [that same PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15053/files#diff-ab81ffc76d0007b4a6563cbc17ac59250e1d9f0ff280cfe0ed5879c6569eaf44R316) also updates the `event-key` when the profile-action is `address-suggestion-failure`.

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - I believe we will have to update the table to include the new error codes.

@bsmartin-ep @sanlouise - I see new error codes coming in for address validation error. However, it looks like there are a lot of undefined errors coming in. Is there a way to define these errors?
![image](https://user-images.githubusercontent.com/66263904/100249654-08d7e380-2efa-11eb-8841-c9220a8f4f5c.png)

**Comment by Samara-Strauss** [comment]
> I believe we will have to update the table to include the new error codes.

@bmcgrady-ep got it. That would be great. Where are you seeing the table above?

@lihanli, do you have any idea why so many of the address errors are coming in as "undefined"? That doesn't leave us with very helpful information :(

**Comment by sanlouise** [comment]
@bsmartin-ep Thank you, yes - this should be fixed! There was no way for me to test this locally. I will push up a fix ASAP and will post in this thread once it's merged.

**Comment by Samara-Strauss** [comment]
@sanlouise got it. Let me know what you find. Thanks!!

**Comment by bsmartin-ep** [comment]
> @bsmartin-ep Not sure if it was clear, but [that same PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15053/files#diff-ab81ffc76d0007b4a6563cbc17ac59250e1d9f0ff280cfe0ed5879c6569eaf44R316) also updates the `event-key` when the profile-action is `address-suggestion-failure`. 

Ah - you are correct @sanlouise.  My apologies.

**Comment by Samara-Strauss** [comment]
Thanks, @sanlouise! @bmcgrady-ep can you let me know where you were able to see those errors?

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - Sure, [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension57&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22address%22,0%5D%5D&_r.drilldown=analytics.eventLabel:profile-edit-failure) is a link to the report in GA. I also updated the dashboard to show the error key with the new errors.

@sanlouise - Thanks for the update. I'll keep an eye out for the error

**Comment by Samara-Strauss** [comment]
I am now seeing the errors in the address validation report (thank you!), but I am still largely seeing "undefined" errors. @sanlouise any thoughts?

<img width="711" alt="Screen Shot 2020-11-30 at 9 37 18 AM" src="https://user-images.githubusercontent.com/34068740/100623107-b29ae400-32ef-11eb-9914-25de4406b15c.png">

**Comment by bmcgrady-ep** [comment]
@sanlouise - [This](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20201127&_u.date01=20201129&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension57&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22address%22,0%5D%5D&_r.drilldown=analytics.eventLabel:profile-edit-failure/) report may be useful for you. It shows the address validation errors coming into the error key since Friday. Let me know if there is anything I can help with!

**Comment by sanlouise** [comment]
@Samara-Strauss Can you have another look today? I suspect that the fix I pushed out 6 days ago did not go into prod over the weekend due to the holiday code freeze.

**Comment by Samara-Strauss** [comment]
@sanlouise it's still giving me "undefined" for most of the errors. [Here is a link to the report if you have access to GA to view it](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/). If not, here is a screenshot of what I am seeing below:

<img width="709" alt="Screen Shot 2020-12-01 at 11 43 06 AM" src="https://user-images.githubusercontent.com/34068740/100769749-7b4d3580-33ca-11eb-88e4-af94db230010.png">

**Comment by Samara-Strauss** [comment]
This is working. Closing!
