### ISSUE TITLE
Find where we use sign-in links in R&S and determine where it should direct users

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15238]
## Issue Description
We have many instances in the R&S nodes were we direct users to sign in. Currently these all direct to the profile page. There may be instances where we should direct them to a different page after sign in. 

A content team member needs to come through the node to track each place we have the sign-in link. Once we have the list we can determine if we should change the page we are directing to. 

---
## Tasks
- [x] Search R&S nodes for sign-in link and list instances in this ticket (Selina)
- [x] Determine if profile is the right landing page or if it should be something else (Randi)
- [x] Implement changes in nodes (Randi)
- [x] Review changes made (Beth)

## Acceptance Criteria
- [x] Sign-in links go to appropriate pages. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
### Sign in button instances
#### Step-by-step templates
- How to get a Premium DS Logon account online: http://preview-prod.vfs.va.gov/preview?nodeId=8503
- How to change your address in your VA.gov profile: http://preview-prod.vfs.va.gov/preview?nodeId=8417
- How to change direct deposit information for VA disability or pension: http://preview-prod.vfs.va.gov/preview?nodeId=8434

#### Multiple QAs
- My HealtheVet FAQs: http://preview-prod.vfs.va.gov/preview?nodeId=8487
- DS Logon FAQs: http://preview-prod.vfs.va.gov/preview?nodeId=8483
- Connecting third-party apps to your VA.gov profile: http://preview-prod.vfs.va.gov/preview?nodeId=8471
- Verifying your identity on VA.gov: http://preview-prod.vfs.va.gov/preview?nodeId=8233
- Signing in to VA.gov: http://preview-prod.vfs.va.gov/preview?nodeId=8222

#### Learning Center Detail Pages
- What your claim status means: http://preview-prod.vfs.va.gov/preview?nodeId=8548
- Change your address on file with VA: http://preview-prod.vfs.va.gov/preview?nodeId=8473

**Comment by RLHecht** [comment]
Work on this ticket completed. Closing.
