### ISSUE TITLE
Automate Github Projects - Analytics Team Pilot

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#15245]
## Issue Description
VSP Analytics & Insights receives several support requests through Github issues. We have recently switched to using the Github project functionality so that we can more clearly see project swim lanes and address the multiple of issues more efficiently and outside of our other objective-driven work.

How might we automate Github projects in a way that pulls in new issues into the project backlog so that we don't lose customer support tickets in our larger Zenhub board?

---
## Tasks
- [x] Set up [automation test](https://github.com/mchelen-gov/project-automation-test)
- [x] Configure [action](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/assign-to-one-project.yml) in `va.gov-team`
- [x] [Test](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15667) with [Analytics - Customer Support project](https://github.com/department-of-veterans-affairs/va.gov-team/projects/20)
- [x] Create [documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/github-isssue-project-automation.md)
- [ ] Publish & Share w/VSP

## Acceptance Criteria
- [x] New issues tagged with `analytics-insights` or `analytics-request` are assigned to this [project board](https://github.com/department-of-veterans-affairs/va.gov-team/projects/20)
- [x] Document automation of adding issues to a Github project
- [ ] Validate user requirements have been met
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchelen-gov** [comment]
Slack thread: https://dsva.slack.com/archives/CL181NRJQ/p1601471516061200
PoC repo: https://github.com/mchelen-gov/project-automation-test

**Comment by mchelen-gov** [comment]
Created [initial config](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/assign-to-one-project.yml). @joanneesteban can you test?

**Comment by joanneesteban** [comment]
@mchelen-gov It worked!

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/245fffc3-1a4e-455f-8e9d-eda64adb391e)

[#15774](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15774#issuecomment-721814235)
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/5fe04424-977c-4283-8ab0-7323781adcef)

[#15776](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15776)
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/7cfa023a-a814-46ad-8b76-2ceb9f032198)

**Comment by gmaciolek** [comment]
Oh, can we have one of those!
I think our current use case is a lot simpler since we're just grabbing issues with the documentation-support label.
Documentation Support Project Board: https://github.com/department-of-veterans-affairs/va.gov-team/projects/16
label: documentation-support

**Comment by mchelen-gov** [comment]
@gmaciolek  ok should be working now! i wasn't sure what column in the project so i guessed "New". sample issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15877

Documentation created here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/github-isssue-project-automation.md

**Comment by mchelen-gov** [comment]
@joanneesteban @gmaciolek does this all look good, anything else left to do?

**Comment by mchelen-gov** [comment]
related: https://github.com/department-of-veterans-affairs/github-user-requests/issues/5300

**Comment by joanneesteban** [comment]
Thanks for your help here! Project has new work automated. Closing this ticket!
