### ISSUE TITLE
Identify and change multiple FAQs that have 3 or fewer questions to removed accordions

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15259]
## Issue Description
R&S multiple FAQs can be built with the option for accordions. The original templates had this as a requirement. We want to look at those that have three or fewer Q&As to determine if we should take them out of accordions and have them all displayed on the page instead. If these are taken out of accordions we should also note whether the optional TOC should be put on the page.

H2s on these pages are also not requirements so we need to determine if there are any we would want to remove. 

We should compile the list here so we are ready to make changes when the CMS team has implemented these changes to the templates.

---
## Tasks
- [x] Look through all R&S multiple FAQs and identify ones that have 3 or few questions and list them in this ticket. (Selina)
- [x] Review whether they should be removed from accordions (Beth)
- [x] Review if H2s should be removed (Beth)
- [x] Review if we should use TOC (Beth)
- [x] Implement changes (Selina/Randi)

## Acceptance Criteria
- [x] Multiple FAQs with 3 or fewer accordions are taken out of accordions. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
My HealtheVet accounts: http://preview-prod.vfs.va.gov/preview?nodeId=8487
Direct deposit for your VA benefit payments: http://preview-prod.vfs.va.gov/preview?nodeId=8423
Common questions about commissary and exchange privileges: http://preview-prod.vfs.va.gov/preview?nodeId=8490
Managing your VA.gov profile: http://preview-prod.vfs.va.gov/preview?nodeId=8259
What kind of information can I find in the claim status tool?: http://preview-prod.vfs.va.gov/preview?nodeId=8528

**Comment by lunascoop** [comment]
@bethpottsVADEPO should I move forward in removing the H2s for these multiple Q&A's?
cc: @RLHecht

**Comment by bethpottsVADEPO** [comment]
@lunascoop Please go ahead with that for the first 4 links you listed. Hold off on 8528. I think that's a dup and we may need to delete it. I'll check when I'm on the network.

**Comment by lunascoop** [comment]
I removed section headers for the first 4 (except for "Commissary and Privileges which was also done). I am waiting for the fix to deploy re: question titles displaying in multiple QAs.

**Comment by lunascoop** [comment]
@bethpottsVADEPO the fix has been deployed and validated for question titles displaying in multiple QAs. And, I've removed the section headers for the first 4 (except for "Commissary and Privileges which was also done). Should we close this ticket?

**Comment by RLHecht** [comment]
This work has been completed. Closing ticket.
