### ISSUE TITLE
[SPIKE]Save in Progress Dynamic Expiration Date

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#15257]
## User Story
As a veteran, I should be to have an expiration that is relevant to my questionnaire so I know when I can and cannot fill out the questionnaire

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Problem Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/save-in-progress/README.md#L12)

## Description
We need to figure out a strategy to create a dynamic expiration date for a form using the current form system without change too much to affect other teams

## Questions to Answer
- [x] Can the front end pass an expiration date to the SIP endpoint?
- [x] On that SIP endpoint, can the expiration date use the passed in value instead the default value?
- [x] many instances for the same form in SIP

## Tasks

- [x] [FE] Add the date to the PUT
- [x]  [BE] Can we adjust the SIP object to take the date?

## Acceptance Criteria
- [x] All the questions are answered
- [x] We have a plan or tickets to implement the feature.

**Comment by mdewey** [comment]
`many instances for the same form in SIP` 

Technically, We can make the id that the form is associated with dynamic, so we can many instances of the same form for the same user. I need to run this past platform to see if there are any consequences to this.

**Comment by mdewey** [comment]
For the expiration date: 

No, the current system is not set up to allow a dynamic expiration date. It's currently 60 days from which is started.

**Comment by mdewey** [comment]
Link to slack chat: https://dsva.slack.com/archives/CBU0KDSB1/p1606839615301800

**Comment by mdewey** [comment]
Meeting with Dillo to discuss findings and next steps, meeting happening at 12/2 @ 11:30

**Comment by mdewey** [comment]
Met wih Dillo, we are have a few action items: 

@dillo 
- Create branch with extended ex[ires at logic that will look for a number of days and a form id to be passed in and set the expires at appropriately

@mdewey  
- Pass the appointment id and the number of days as formData properties in the SIP call .

**Comment by mdewey** [comment]
Success!  I was to get the front end talking to the back end. 

For the front end, we need to send `daysTillExpires/days_till_expires` field as part of the form. This can be done by adding this property to the first form page as a hidden form field. This will cause the SIP system to pick up the data automatically and send the number of days left to the back end. 

For the back end @dillo  was able to update the `expires_after` to look like: ```def expires_after
    @expires_after ||=  case form_id
                        when '21-526EZ'
                          1.year
                        when /HC-QSTNR/
                          JSON.parse(form_data).fetch('days_till_expires', '60').to_i.days
                        else
                          60.days
                        end
  end```



Actions : 
- [ ] Create back end ticket for real development on a feature
- [ ] Create front end ticket for real development on a feature
- [ ] find out when/how expired data gets deleted

**Comment by mdewey** [comment]
Conversation about delete data: https://dsva.slack.com/archives/CBU0KDSB1/p1607096689079700
