### ISSUE TITLE
Medallia - User Stories for QA

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#15260]
# Intercept Survey

## Issue Description
As a veteran, when I get "intercepted" to provide feedback on the website, I need to be able to close out of the survey if I don't want to give feedback or if I do want to give feedback, I need to be able to see and understand all of the questions and know that my feedback has been submitted.

## Supporting Artifacts
- [Staging site](https://staging.va.gov/find-locations/facility/vha_691)
![image](https://user-images.githubusercontent.com/48964695/97057254-d6347700-1558-11eb-8783-d20bb880a1e0.png)

![image](https://user-images.githubusercontent.com/48964695/97057265-d9c7fe00-1558-11eb-8822-bfa77c209b48.png)

![image](https://user-images.githubusercontent.com/48964695/97057270-dd5b8500-1558-11eb-9c47-bf0b8042d4f7.png)

## Tasks
Veterans should be able to...
- [ ] Close out of the survey at any time
- [ ] Answer the questions on the survey
- [ ] Submit their answers

## Acceptance Criteria
- [ ] Exit buttons should appear & be clickable on all survey pages. 
- [ ] "Provide Feedback" button should appear on the introduction page to lead to the survey
- [ ] Questions should appear on the survey page
- [ ] Answers should appear & be clickable
- [ ] "Submit" button should appear & be clickable on the survey page
---
# Feedback Survey

## Issue Description
As a veteran, I need to be able to see how I can submit feedback and submit feedback on specific VA.gov pages.

## Supporting Artifacts
- [Staging Site](https://staging.va.gov/find-locations)
![image](https://user-images.githubusercontent.com/48964695/97057205-c026b680-1558-11eb-80e5-7d6fbd3a6c93.png)

![image](https://user-images.githubusercontent.com/48964695/97057221-c4eb6a80-1558-11eb-9247-f656e415b911.png)

![image](https://user-images.githubusercontent.com/48964695/97057230-c74dc480-1558-11eb-80c2-c56316f6cc78.png)

## Tasks
Veterans should be able to...
- [ ] Find the Feedback button to open a survey
- [ ] Close out of the survey at any time
- [ ] Answer the questions on the survey
- [ ] Submit their answers

## Acceptance Criteria
- [ ] "Feedback" button should be displayed and click open to a survey
- [ ] Exit buttons should appear & be clickable on all survey pages. 
- [ ] Questions should appear on the survey page
- [ ] Answers should appear & be clickable
- [ ] Text boxes should be appear, be clickable and able to be typed in
- [ ] "Submit" button should appear & be clickable on the survey page
---

**Comment by jwoodman5** [comment]
QA was done.
