### ISSUE TITLE
IA/content strategy audit of Debt management website

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#15265]
## User story
As an IA/content team member working on the migration of content from https://www.va.gov/debtman/ to the modernized VA.gov, I need to have a full understanding of the existing content on https://www.va.gov/debtman/.

---
## Tasks
- [x] Audit all pages on https://www.va.gov/debtman/ from an IA perspective (Mikki)
- [x] Audit all pages on https://www.va.gov/debtman/ from a content strategy perspective (Danielle)
- [x] Discuss audit findings in preparation of final IA/content strategy recommendations (Mikki and Danielle)

## Acceptance Criteria
- [x] Final audit captured in documentation and ready for synthesizing recommendations
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Initial IA/content strategy for discussion: [Debt Management Content_IA + content strategy](https://app.zenhub.com/files/133843125/b8e1a9cc-6556-45a1-8148-88fdfc15a667/download)

+ discussion of where FSR lives since it's used by VHA for health-related debts + other adjacent departments

@mnorthuis I sent you an invite to IA/content strategy discussion on this for Tuesday 10/27, 12:00 noon to 1:00 p.m.

@leahkeeler Tagging you for awareness. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @brianalloyd

**Comment by DanielleThierryUSDSVA** [comment]
**Note:** This work was completed. [Manage debt_content strategy and ia recommendations_12.02.20](https://app.zenhub.com/files/133843125/bc368759-0939-437b-8f5c-02ead5ff9cb1/download)

The result of this work and the document sent to SMEs is here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20590

The related redirect request ticket is here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19908
