### ISSUE TITLE
[Initiative] VAOS Homepage Refresh

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#15290]
# Stakeholder input
## Who is the target user?
Veterans using VA online scheduling as their main reference point for all upcoming and past appointments

## High Level User Need / Problem / Opportunity
As a Veteran who uses VA online scheduling, I want to be able to manage all my appointments from a single place which includes preparing for upcoming appointments, printing specific details about appointments, reviewing past appointments, and rescheduling appointments I need (not just cancel them). 

## Hypothesis or Bet
We believe that by moving the VA online scheduling homepage more towards a dashboard-like experience where Veterans are able to more effectively prepare and manage already booked (or almost booked) appointments, we will improve the usefulness and satisfaction of VA online scheduling. 

## Outcomes / how will we define success
- Improve overall satisfaction (rating) of VA online scheduling
- Improve retention rate of VA online scheduling homepage (dashboard)
- Decrease # of appointments canceled (instead actively rescheduled)

## Supporting data we should consider (feedback, analytics)
- VA Mobile feedback - we have received multiple Veteran points of feedback about confusion of types of appointments on homepage, how they are organized/categorized, and missing 'information' 
- VA Mobile feedback - we have received multiple requests for ability to print individual appointments
- VA Mobile feedback - we have received multiple requests for ability to 'reschedule' 
- Research conducting July 2020 - calls out confusion & need for improvement of homepage/dashboard - [report here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/july-2020-user-research/2020-july-VAOSR-EC-research-report.md)

## Stakeholder AC Checklist:
- [ ] Does this ask make it easier for a Veteran to schedule an appointment regardless of which electronic health record their facility or provider uses? 
- [ ] Does this ask make it easier for a Veteran to access care when and where they need it? (community care, telehealth) 
- [ ] Is this ask directly contributing to scheduling an appointment? 
- [ ] Does this feature solve a current and persistent problem for the user? 
- [ ] Does this feature have downstream impacts on schedulers & providers, where fixing it delivers a better user experience to Veterans, without exposing the guts of the system to them? 
- [ ] What is the urgency and why? 
- [ ] Who wants this feature and why? 

---
# Next iteration of Epic after initial Stakeholder input:

#### Collab Cycle Checkpoints

- [x] Kickoff

- [x] Midpoint Review

- [x] Staging Review #25779

- [x] Privacy & Security Review [288](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/288)

- [ ] Full Accessibility & 508 Office Audit #28307 (9/2-submitted to 508 office)

## (Optional) Supporting Documentation
_Link to Additional Implementation artifacts- requirements based on policy, data, system-related needs_

## Issues to create within this Epic

```
- If discovery needed, create Discovery/Research Epic
- If no discovery needed, break epic into corresponding stories and tasks
```

**Comment by laurenernest** [comment]
rolled out to 100% on 7/20/21
