### ISSUE TITLE
[Research] Search Landing Page Template 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1530]
**Identify Resources:**
1. Research / UX
2. Designer

**Tasks:**
- [ ] work with analytics to identify ideal candidate for SLP Pilot
- [ ] work with Ryan to create design for SLP / after in tandem assigning content writer
- [ ] work with analytics to add all of the tnecessary tracking with launch
- [ ] use search optimized landing page that we can direct to benefit pages

**Comment by aeltarhoni** [comment]
Kara and Jen meeting Friday to unpack into Stories.

**Comment by Karak888** [comment]
@Karak888 to follow up with @jenniferlee-dsva with broken out stories and estimates.

**Comment by johnhashva** [comment]
This is old and will be revived in a separate ticket by new Search team.

**Comment by jenniferlee-dsva** [comment]
Background on this @johnhashva is that SLP was one of the first templates I wanted us to build in the CMS. It was not prioritized in 2019, so it got ice boxed. 

Then it kind of morphed into the CLP (which is not the same, but overlaps) and the Forms Detail Landing Page (which is also not the same but overlaps).  Happy to provide more detail if you wish, but yes, I 'd close this.
