### ISSUE TITLE
Update VSP Terraform Database Modules to disable auto minor version upgrades

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#15317]
## Description
Currently all terraform database modules have `auto_minor_version_upgrade` set to `true` by default.  This is not desirable since upgrades can happen automagically without notice by AWS, leading to broken terraform state and unknown/untracked changes.

The VSP terraform modules for RDS should:

- Disable this by default
- Create a var so it can be enabled per database if desired

## Background/context/resources
See the following Slack [thread](https://dsva.slack.com/archives/CTYQL39FE/p1603746525260900?thread_ts=1603735696.238700&cid=CTYQL39FE) for more details, context and approvals.

## Technical notes
Sample PR for gids [here](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-gids/pull/2)

---
## Tasks
The following modules need to be updated:
- [X] gids [module](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-gids)
- [x] vets-api [module](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vets-api)
- [ ] cms-test [module](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms-test)  
- [ ] cms [module](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms)
- [x] default postgres [module](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-postgres)

## Definition of Done
- [ ] All the above modules have merged PRs

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
will want to get this into upcoming sprint.

**Comment by oragame** [comment]
Question: cms and cms-test currently do not have a postgres DB - is this issue requesting for those 2 to simply add the variable to variables.tf for future potential usage of a postgres DB?
```
variable "db_auto_minor_version_upgrade" {
  type = bool
  description = "postgres auto minor version upgrade"
  default = false
}
```

**Comment by oragame** [comment]
@pnwstevan - Let me know what you think about my previous comment ^
