### ISSUE TITLE
Disable auto minor version upgrade for all VSP RDS databases managed by terraform

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#15319]
## Description
We would like to disable auto upgrade of minor database versions by AWS for RDS databases that currently happen automagically.

## Background/context/resources
See this Slack [thread](https://dsva.slack.com/archives/CTYQL39FE/p1603746525260900?thread_ts=1603735696.238700&cid=CTYQL39FE) for more details/approvals.

## Technical notes
The terraform modules need to be updated first, since they by default set the `auto_minor_version_upgrade` to `true`.  See [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15317).

---
## Tasks
The following needs updating:
- [x] vets-api (dev)
- [x] gids (dev)
- [x] vets-api (staging)
- [x] gids (staging)
- [x] vets-api (prod)
- [x] gids (prod)
- [ ] vets-api (staging)

Once the modules are updated, simply running a terraform apply/plan for each environment should update the value accordingly.

## Definition of Done
- [ ] All above databases have `auto_minor_version_upgrade` se to `false`; this can be confirmed via terraform, or via the RDS console.

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
This should be ready to be picked up by Ops team member. Reference commits

**Comment by oragame** [comment]
Duplicate task listed for vets-api (staging) - I think we are all finished here.
