### ISSUE TITLE
[AWS/RDS] Audit platform database software versions on a monthly basis

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#15320]
## Description
Since auto upgrading of RDS databases will be disabled, there should be regular auditing of versions for security, performance and support/EOL.

## Background/context/resources
See this Slack [thread](https://dsva.slack.com/archives/CTYQL39FE/p1603746525260900?thread_ts=1603735696.238700&cid=CTYQL39FE) for more details/context.

## Technical notes
Not much discussion on how this will be done; likely some script/report.  

We could likely generate a dashboard in Grafana too.

---
## Tasks
- [ ] Create GitHub Action to run monthly query and capture results
- [ ] GitHub Action should create a ticket in Ops backlog that includes results of query 

## Definition of Done
- [ ] Monthly GH ticket created in Operations backlog with information about database versions

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jsev-io** [comment]
resourceId | resourceName | configuration.engine | configuration.engineVersion | configuration.autoMinorVersionUpgrade
-- | -- | -- | -- | --
db-I554V7XVQ3EJHWOSOTZZXOBCYQ | appeals-caseflow-preprod | postgres | 11.8 | true
db-GN6FTMEOXY6TO2CEZ63SRF7LR4 | appeals-caseflow-prod | postgres | 11.6 | true
db-2SRSKWPVZSU7LWOLMOO4TIGZT4 | appeals-caseflow-prod-replica | postgres | 11.6 | true
db-RWHT7ZOTBWYSO656SSEUGJ5DRI | appeals-caseflow-uat | postgres | 11.8 | true
db-MZ7Q2JAKYYUJYMGKQ27BQTDKSU | appeals-efolder-preprod | postgres | 11.8 | true
db-GOBHEWZIV5HPNIXDVPK4X7SJBM | appeals-efolder-prod | postgres | 11.8 | true
db-X7YXTJCWV3MTKDWRGJUXTASWUQ | appeals-efolder-uat | postgres | 11.5 | true
db-CCF65QJE3U3GXKBJRVA7FIMXVQ | appeals-sentry-prod | postgres | 9.5.22 | true
db-3FC6BCSLL4DH4MEWYXBYH3B4GE | appeals-sentry-uat | postgres | 9.5.22 | true
cluster-VGWUG6GYQPS6VPZOE3B2L4MCDU | appealsmetabase | aurora-postgresql | 9.6.6 |  
db-GLMEE2FZMBEEQUD675HMGNMS54 | dsva-appeals-etl-spoke-preprod | postgres | 11.5 | true
db-M42DBES3NYLA4CMRVPMZCFMPD4 | dsva-appeals-etl-spoke-prod | postgres | 11.5 | true
db-AZ5DRHDEBWR5UFUZWVIHQIHA2E | dsva-appeals-etl-spoke-uat | postgres | 11.8 | true
db-2DLIYE2XQCZJCIIQ3OOGNNYFGE | dsva-appeals-metabase-spoke-prod | aurora-postgresql | 9.6.6 | true
db-4RFG6QLWX6TPDBTBO6WNANPRUM | dsva-appeals-spoke-prod-vacols-dr | oracle-ee | 11.2.0.4.v24 | true
db-66LJGEN7PS3FWPEBULIRUHOP3E | dsva-appeals-vacols-uat-sanitized | oracle-ee | 11.2.0.4.v24 | true
db-GX25MBHFZNLCBRVYFLOCNEL7GE | dsva-cms-dev | mariadb | 10.2.12 | true
db-VKJYUYR7HWBC5VCNOHPRX5I5OE | dsva-cms-prod | mariadb | 10.2.12 | true
db-LRSM36CSYAWT62TGYRYQRGHQR4 | dsva-cms-staging | mariadb | 10.2.12 | true
db-5DHY3QLM46IQAIUBGE4KFFWM6E | dsva-cms-test-dev | mariadb | 10.2.12 | true
db-KFYNO6LB6OZHD7NMSZNMPCRUAI | dsva-cms-test-prod | mariadb | 10.2.12 | true
db-KEVCIAPSEFMOEQBEIKY7DFAO7A | dsva-cms-test-staging | mariadb | 10.2.12 | true
db-J7W5VPIKIDWKJ27DRZZB5L6KAM | dsva-gi-bill-data-service-dev | postgres | 11.6 | true
db-6VGKWPB4WMWGFXYN6VPAOQALQE | dsva-gi-bill-data-service-prod | postgres | 11.8 | true
db-2SFQYSYKNIS5WQ7HFIS5XMQOIY | dsva-gi-bill-data-service-staging | postgres | 11.8 | true
db-MJ2Q4RJLNEOGBXVVWZYCVLSOKU | dsva-sentry-utility | postgres | 9.5.22 | true
db-XPI4RKLMQBGWO7ZVYSWXZUV3BE | dsva-vagov-grafana-utility | postgres | 9.5.22 | true
db-6S7KNDVDVVBCZ63F7364IMSVMA | dsva-vagov-utility-pact-broker | postgres | 9.6.18 | true
db-TZDKP2LGT735YNWTY62CD2TEDQ | dsva-vets-api-dev | postgres | 11.8 | true
db-MJY52OYP45VTIY5FP73QZRHRMA | dsva-vets-api-prod | postgres | 11.8 | true
db-V3Z2AJADUTKCJTPM66B2ZDZGQU | dsva-vets-api-sandbox | postgres | 11.8 | true
db-NS3DFURQPAF5A5BPNAHO2S3GRY | dsva-vets-api-staging | postgres | 11.6 | true
db-3MLQUTINTZWUAJMXZPVEULOMWM | dvp-dev-api-gateway-db | postgres | 9.6.18 | true
db-KA2QOGEGO5IP5NYVVNO3QGUZEQ | dvp-prod-api-gateway-db | postgres | 9.6.18 | true
db-2L3R73EIHLRJZ5QZGBG5AEWVBU | dvp-sandbox-api-gateway-db | postgres | 9.6.18 | true
db-QT45PPQBO7YCJJ75GN2EI3XN2I | dvp-staging-api-gateway-db | postgres | 9.6.18 | true
db-BLMOXDKTYNFX4NMOKMCVKDCS74 | vacols-postgres-analytics | postgres | 9.6.18 | true

**Comment by jsev-io** [comment]
Thoughts on a report like this?

**Comment by jhouse-solvd** [comment]
High-level workflow: Run Audit Script on a regular schedule (OS check?)  > Check minor upgrade version available > Create Tickets in GitHub using GitHub actions (or other) > ??? 

Run on a schedule: Monthly 
Message: "There's a new minor version of Postgres available. Please upgrade as soon as possible!" 
Create Ticket w/ info: X,Y,Z

**Comment by rmtolmach** [comment]
This is not a current need for the Platform Infrastructure team. Closing.
