### ISSUE TITLE
Leverage Route53 DNS rather than bind server

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#15326]
## Issue Description
Currently, we leverage a bind server ([config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jumpbox/templates/vetsgov.named.conf.j2) / [installation](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/va-socks/tasks/main.yml#L22-L26)) for routing internal DNS queries. However, we put a substantial amount of effort into obtaining a DNS zone delegation from the VA IT folks for `*.vfs.va.gov` and should likely use that instead. This would ensure we get the most value out of the efforts we made in that direction.

---
## Tasks
- [x] Change how we handle DNS queries to leverage Route53 rather than bind/named
- [x] Test
- [x] Remove old way/associated configurations

## Acceptance Criteria
- [x] Systems using the `*.vfs.va.gov` internal DNS zone
- [ ] Previous services, configs, automation, etc. eradicated

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
During some research it was found that at this time we can't really get rid of Bind altogether. We can however set ourselves up to only use Route53 as a source of truth for anything in the `*.vfs.va.gov` zone, so we did.

**Comment by jbritt1** [comment]
Going to close this one for now since we did all we can do right now on our side to skip using bind and go straight to Route53. There are other services using the bind configs currently that would prevent us from eradicating completely.
