### ISSUE TITLE
Remove PPMS v1 client and "no round trip" flags

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15330]
## Issue Description
Following the successful implementation of the PPMS 10.0 update in Prod, we need to deprecate the flag which was placed to used to restrict our code changes to staging

## Tasks
- [ ] Remove PPMS v1 client feature flag (from endpoint)
- [ ] Remove "no round trip" flag (from endpoint)

## Acceptance criteria
- [ ] Unnecessary code is removed
- [ ] Functionality is maintained
- [ ] V1 API endpoint should only use the V1 client
