### ISSUE TITLE
Test Facility Locator mobile experience post-Mapbox upgrade

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15334]
## Issue Description
Following the Mapbox upgrade from SDK to GL JS, we need to confirm the mobile experience has been maintained as expected. 

---
## Tasks
- [ ] Deploy new map to staging
- [ ] Test Facility Locator mobile experience on actual devices to confirm functionality is maintained

## Acceptance Criteria

- [ ]  Search within existing parameters is successful, including return of no results
- [ ]  The map displays pins for search results
- [ ]  The map displays "I am here" indicator
- [ ]  Uses existing bounding box
- [ ]  Results are returned within acceptable time
- [ ]  Changes are restricted from Prod
- [ ]  FL does not autosearch if not results are found within 80 miles

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
