### ISSUE TITLE
Sunset V0 ccp controller

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15331]
## Issue Description
V0 will be deprecated and we believe the Facilities team is the only consumer of the ccp controller

## Tasks
- [ ] Remove route to v0 ccp controller (from client)
- [ ] Remove PPMS v0 client

## Acceptance criteria
- [ ] Ccp pathway for V0 no longer exists
- [ ] Functionality is maintained

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
