### ISSUE TITLE
Conduct research with Community care schedulers 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15360]
## Issue Description
The Facilities and VAOS teams need better understanding of the process for searching for community care providers to inform the PPMS taxonomy work and to improve the Veteran search experience. We want to understand how and where Community Care Request managers search for type of care/specialties and providers.

## Goals

- [ ] Understand the current data & process that a community care request manager uses to process Veteran's community care requests
- [ ] Understand/gather feedback (where possible) about the VAOS requests for community care coming into Community Care request manages

## Tasks
- [ ] Use the research plan and conversation guide to recruit and conduct internal  interviews

## Acceptance Criteria
- [ ] Interviews have been conducted
