### ISSUE TITLE
Implement Flipper Components for CH31 for eBenefits

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15361]
### Content support for:
- Unauthenticated (static) VA.gov pages
- Apps or tools
- Other writing or editing requests

### Engineering support for:
- Redirects that have first been vetted by the VSP IA team  
- 👉  REACT sign-in widgets or **feature flags (flipper)**
- Other engineering support

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * For Veteran Readiness and Employment (CH31): allows for Veterans to get counseling and other services upon leaving their military service
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/README.md)
   * [Prototype](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526673/simulate/sitemap)
   * [Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/research-design) & [Usability](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing)

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
_Content changes not needed, click Edit to see more_

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [x] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors for all 7 pages given their variability:** 
<details>
  <summary>1. VR&E Reemployment track</summary> 
  
https://www.va.gov/careers-employment/vocational-rehabilitation/programs/reemployment/

<blockquote>
  <details>
    <summary>Current</summary>

- Remove subway header, subway itself, button header and button 

   ![Screen Shot 2020-10-27 at 11 34 54 AM](https://user-images.githubusercontent.com/1899695/97346891-4721aa80-1849-11eb-8363-861bd67b3687.png)

  </details>

  <details>
    <summary>Proposed</summary>  
  
* Replace with flipper widget code  

 ![Screen Shot 2020-10-27 at 11 42 00 AM](https://user-images.githubusercontent.com/1899695/97347021-73d5c200-1849-11eb-945b-e38dc0d5e153.png)

  </details>
</blockquote>

</details>

<details>
  <summary>2. VR&E Rapid Access to Employment track</summary>

https://www.va.gov/careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment/
<blockquote>
<details>
  <summary>Current</summary>
  
- Remove subway header, subway itself, button header and button 

 ![Screen Shot 2020-10-27 at 11 34 54 AM](https://user-images.githubusercontent.com/1899695/97346891-4721aa80-1849-11eb-8363-861bd67b3687.png)

</details>

<details>
  <summary>Proposed</summary>
  
- Replace with flipper widget code

 ![Screen Shot 2020-10-27 at 11 42 00 AM](https://user-images.githubusercontent.com/1899695/97347021-73d5c200-1849-11eb-945b-e38dc0d5e153.png)

</details>
</blockquote>
</details>

<details>
  <summary>3. VR&E Self-Employment track</summary>

https://www.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment/

<blockquote>
<details>
  <summary>Current</summary>
  
- Remove subway header, subway itself, button header and button 

 ![Screen Shot 2020-10-27 at 11 34 54 AM](https://user-images.githubusercontent.com/1899695/97346891-4721aa80-1849-11eb-8363-861bd67b3687.png)

</details>

<details>
  <summary>Proposed</summary>
  
- Replace with flipper widget code

 ![Screen Shot 2020-10-27 at 11 42 00 AM](https://user-images.githubusercontent.com/1899695/97347021-73d5c200-1849-11eb-945b-e38dc0d5e153.png)

</details>
</blockquote>
</details>

<details>
  <summary>4. VR&E Employment Through Long-Term Services track</summary>

https://www.va.gov/careers-employment/vocational-rehabilitation/programs/long-term-services/

<blockquote>
<details>
  <summary>Current</summary>
  
- Remove subway header, subway itself, button header and button 

 ![Screen Shot 2020-10-27 at 11 34 54 AM](https://user-images.githubusercontent.com/1899695/97346891-4721aa80-1849-11eb-8363-861bd67b3687.png)

</details>

<details>
  <summary>Proposed</summary>
  
- Replace with flipper widget code

 ![Screen Shot 2020-10-27 at 11 42 00 AM](https://user-images.githubusercontent.com/1899695/97347021-73d5c200-1849-11eb-945b-e38dc0d5e153.png)

</details>
</blockquote>
</details>

<details>
  <summary>5. VR&E Independent Living track</summary>
[https://www.va.gov/careers-employment/vocational-rehabilitation/programs/independent-living/](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/independent-living/)

<blockquote>
<details>
  <summary>Current</summary>
  
- Remove subway header, subway itself, button header and button 

![number5](https://user-images.githubusercontent.com/53826255/100006164-12493a80-2d98-11eb-987f-f849b6750148.JPG)

</details>

<details>
  <summary>Proposed</summary>
  
- Replace with flipper widget code

 ![Screen Shot 2020-10-27 at 11 42 00 AM](https://user-images.githubusercontent.com/1899695/97347021-73d5c200-1849-11eb-945b-e38dc0d5e153.png)

</details>
</blockquote>
</details>

<details>
  <summary>6. How to apply for Veteran Readiness and Employment</summary>

[https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/)

<blockquote>
<details>
  <summary>Current</summary>
  
- Remove subway and button itself

![number6](https://user-images.githubusercontent.com/53826255/100006422-72d87780-2d98-11eb-98fc-196879ad40a6.JPG)

</details>

<details>
  <summary>Proposed</summary>
  
- Replace with flipper widget code, adding :

 ![Screen Shot 2020-10-27 at 11 42 00 AM](https://user-images.githubusercontent.com/1899695/97347021-73d5c200-1849-11eb-945b-e38dc0d5e153.png)

</details>
</blockquote>
</details>

<details>
  <summary>7. Eligibility for Veteran Readiness and Employment</summary>

[https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/)

<blockquote>
<details>
  <summary>Current</summary>
  
- Remove header and language and button

![number7](https://user-images.githubusercontent.com/53826255/100007105-8801d600-2d99-11eb-9f85-e6adca6a378a.JPG)

</details>

<details>
  <summary>Proposed</summary>
  
- Replace with flipper widget code, adding :

 ![Screen Shot 2020-10-27 at 11 42 00 AM](https://user-images.githubusercontent.com/1899695/97347021-73d5c200-1849-11eb-945b-e38dc0d5e153.png)

</details>
</blockquote>
</details>

   

 
- **Flipper unique id:** 
  - `<div data-widget-type="chapter-31-cta" id="chapter31CTA"></div>`

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [x] **Other**
```diff
! Important: Please Read
```
   * While there are several different pages where this feature is accessed, we have created the flipper component to do a check on the specific url and based on that, add and remove the appropriate variation for each page.  We JUST need the components referenced above to be replaced with: `<div data-widget-type="chapter-31-cta" id="chapter31CTA"></div>`.  That's it!
      

### Desired/target implementation date
What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Sprint 34

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team
- Team name: **eBenefits**
- DEPO product owner: **Steve Kovacs**
- Product manager: **Jason Wolf** 
- Designer: **Jim Adams**
- FE engineer: **Jesse Cohn** 
- Product/team Slack channel: **#vsa-ebenefits** 

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jason-gcio @brianalloyd. Adding quick notes from meeting:

- The link beneath the button should remain on these pages. Jason's team will provide updated screenshots with a box around what to replace w/ react widget. Once we have those, we can assign to content teams for implementation.
- Button label in above screenshots has a typo (“Rediness” should be “Readiness”)
- Button label text is 42 characters. We aim for 35 generally, and the new Resources & Support sets a 40-character limit. I have a ticket open with our design system council to discuss button label length with the design council and will follow up with Peggy on any next steps based on that discussion.

Thanks!

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA moving this into Sprint 34 workflow as discussed during our roundtable discussion.  Thanks team for the quick discussion.

**Comment by DanielleThierryUSDSVA** [comment]
Perfect - thanks, @brianalloyd!

**Comment by jason-gcio** [comment]
@DanielleThierryUSDSVA - here is a link to some screenshots where the first have been edited to show exactly what is being replaced: https://github.com/department-of-veterans-affairs/vets-website/pull/14786
Does that work, or should we do all of them?

**Comment by DanielleThierryUSDSVA** [comment]
This is perfect, @jason-gcio. Thanks so much! @brianalloyd, when we write up up the implementation ticket, we can just note to globally follow the direction re: the link staying per example.

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA is everything ready for implementation on this?  If so, @kelsonic can you take this for action or is this something we could pass off to Fareez in support?

**Comment by kelsonic** [comment]
I don't think there's anything dev related to work on for this, right? I think the content team is just putting their react widget on certain page(s)?

**Comment by brianalloyd** [comment]
Thanks @kelsonic that's my understanding as well, sorry for the confusion.  @DanielleThierryUSDSVA can you source this with content team for implementation and close out?  Just trying to keep this on track in support and little unsure who is best to handle the details.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @brianalloyd. Sure, yes! This can go to @RLHecht and content team for implementation now. Randi, do you want to find 15 minutes on my calendar this week and we can go through this together? 

Note that we haven't gotten to the button character count limit question on the Design System Council yet, so I'll have to circle back on that when we do. For now, let's keep as the team has it.

Also FYSA @bethpotts since this is VBA related

**Comment by RLHecht** [comment]
@jason-gcio I've put the widget on all the above pages but I have a few questions on some:

- Independent-living track: The react widget is not showing the unique subway map for this in preview. I know I saw that the one code will work for all the pages and it will update depending on the URL but it's not showing in preview. Is this an issue?

- Eligibility page: I'm a little confused what will be in the widget and what I should leave on the page. Will the link and the line of text below that button be in the widget or in rich text? And the H2 before it? This preview page also isn't showing a unique widget so it's hard for me to follow.

Your help is much appreciated! Happy to do a screen share if it's easier to talk it through.

**Comment by jason-gcio** [comment]
@RLHecht - Yea, I think we should definitely chat about the first one, and as far as the second one, that is just a button swap.

Let me know when a good time to hop on zoom might be and Jesse and I will be there!

cc: @cohnjesse

**Comment by RLHecht** [comment]
@jason-gcio After reviewing other hub pages, we want to take out the "Ready to apply?" H2 that is above the CTA widget on all these pages. We are also going to update in Drupal the text above the subway map to the following:

H2 How do I get these benefits?
First, you’ll need to apply for VR&E benefits. Then, you’ll work with your Vocational Rehabilitation Counselor (VRC). If you've received your VA disability rating, you can apply online right now.

This makes it clearer why there is a separate link if you haven't received a rating yet. 

Let me know when the widget is updated and then we can publish these pages. 

Thanks again for working through this with me!

**Comment by jason-gcio** [comment]
Sure - let me check in with @cohnjesse on this and we can get back with you

**Comment by RLHecht** [comment]
These pages have all been published. Please let me know if there's anything else I need to do once you've seen it live on the site. FYSA @jason-gcio @cohnjesse

**Comment by RLHecht** [comment]
These changes are live on the site. Closing ticket.
