### ISSUE TITLE
Loki STAGING - Capture System & Application logs

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15372]
## Issue Description
_For every app and service that was configured to log in DEV, make sure that we use that same code to do this in STAGING._

Will want to discuss 
---
## Tasks
- [ ] _Communicate and plan with app teams the migration_
- [ ] _Deploy this configuration to capture logs in staging_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
need to harvest what we can from this ticket and see how it aligns with our current efforts

**Comment by jhouse-solvd** [comment]
See [HERE](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17615) for more relevant information. Closing.
