### ISSUE TITLE
Loki STAGING - Docker logs via Loki Docker Driver

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15373]
## Issue Description
Capture logs with Loki for docker containers in the Staging environment 

---
## Tasks
- [ ] Ensure that configuration done in DEV makes it to STAGING so that docker logs are being captured with Loki

## Acceptance Criteria
- [ ] We will be able to view docker logs in Grafana for Loki Staging as a data source 

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
need to harvest what we can from this ticket and see how it aligns with our current efforts

**Comment by jhouse-solvd** [comment]
@mydesignrocks - Are we capturing docker logs w/ Loki? This is not something that we need to do right away, but wanted to check with you

**Comment by mydesignrocks** [comment]
@jhouse-solvd  - yes, we are capturing docker based logs with loki. Apps like gids are docker based and that can be an example to review from within the grafana dashboard. Since this ticket is specific to staging, we are good to close it out.
query url: http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%20(Staging)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22gi-bill-data-service%5C%22%7D%22%7D%5D

**Comment by jhouse-solvd** [comment]
Good to go. Closing.
