### ISSUE TITLE
Loki STAGING Deployment on EKS

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15371]
## Issue Description
Deploy an instance of Loki into `staging` environment hosted in an EKS cluster.

This should be based on learnings from Loki deployment in `dev`, user research/feedback, and Loki R&D spikes and recent decisions around infrastructure recommit.

Requirements:
* Loki deployed via helm chart
* Loki deployed into Ops-tool EKS cluster in separate namespace
* Loki is deployed in microservices mode
* Loki is using BoltDB shipper + s3 bucket for storage
* Loki is logging to itself
* Ops-Tools EKS cluster is logging to this Loki instance

---
## Tasks
- [x] (Pre-req) Ops-tool EKS cluster deployed in Staging
- [x] Create Loki helm chart for microservices deployment in staging

## Acceptance Criteria
- [x] At least one host can successfully ship logs to Loki staging instance via Promtail
- [x] At least one Docker container can successfully ship logs to Loki staging instance via Docker driver
- [x] EKS Cluster is logging to this Loki deployment 
- [ ] Grafana in `utility` can see this Loki deployment as a Data Source
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pnwstevan** [comment]
@jhouse-solvd Updated this ticket, which is the deployment of Loki into staging via Helm chart; please review and remove the `needs grooming` tag if good to go.

**Comment by jhouse-solvd** [comment]
While there are may be some minor technical differences here, this is definitely done. 

Please check here for up-to-date documentation
