### ISSUE TITLE
Document funnel implementation & visualization process

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#15379]
## Issue Description
We have been improving how we implement funnels within BigQuery. We are currently on version 3 of funnels. How might we document our work with funnels so that we can more easily create funnels & understand what they mean?

---
## Tasks
- [ ] Document how funnels are implemented in GA vs. BigQuery
  - [ ] Determine if we can templatise implementation
  - [ ] Document taxonomy
- [ ] Determine which funnel we recommend gets used

## Acceptance Criteria
- [ ] We can more easily create funnels when requested
- [ ] We have a single source of truth for what "funneling" means for VA.gov
- [ ] VFS teams understand the different options for funnels
- [ ] VFS teams can more easily create and understand what the steps

**Comment by bsmartin-ep** [comment]
Documentation has been merged in:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/bigquery/funnels-in-bigquery-and-domo.md

These are very complex, so probably not a bad idea to re-visit this in a bit to add anything else we learn.

Closing.
