### ISSUE TITLE
Loki STAGING - R&D for microservices

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15370]
## Issue Description
Discovery around needs to run Loki in microservices mode, with the first deployment of that in Staging.

---
## Tasks
- [x] Do some R&D

## Acceptance Criteria
- [x] Staging POC in microservices mode completed and operational, validating assumptions
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pnwstevan** [comment]
Finally got this up and working; here's the tl;dr/findings:
- Significant changes (and bugs) to terraform Fargate module needed, which was completed
- For clustering, gossip/memberlist isn't feasible in Fargate without AWS Service Discovery which is n/a in GovCloud; we already threw out Consul, so that only leaves etcd
- etcd does work, although final deployment config is TBD
- we use path-based routing in AWS ALB to route query requests to querier, and incoming logs to ingester
- It may make sense to keep the ingester+distributor coupled together unless absolutely needed
- Loki 2.0 was released during this sprint; primary relevant here is production ready boltdb, which will replace DynamoDB

**Comment by jhouse-solvd** [comment]
We learned what was needed to deploy Loki in staging and are currently working to deploy into EKS. Closing.
