### ISSUE TITLE
Outreach & Events - New VA.gov Footer Navigation Links

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#15384]
### Content

- [X] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 

We are adding links for the [Outreach and Events pages ](https://www.va.gov/outreach-and-events/) to the VA.gov global footer navigation.   Details:

Per @mnorthuis and @mpeterz:   Recommend splitting this into 2 separate links - the overarching landing page only provides links, not any additional helpful content that (the email sign up is already linked to in the footer) and it doesn't string the two experiences together. Both links would be placed in the footer.

- Add a link for "VA outreach events" that links to https://www.va.gov/outreach-and-events/events/ in the first column of the footer (Veteran programs and services).

- Add al ink to "VA outreach materials" that links to https://www.va.gov/outreach-and-events/outreach-materials/ in the second column of the footer (More VA resources)

We chose to use "VA" over "Veteran" in the labels because 1) the materials experience is more tailored to those helping veterans rather than veterans themselves and 2) the events experience is not a full event calendar, it is only a subset of events and not all of them are specific to just Veterans.

We also altered the order the More VA resources column to better group and label like content. Here is the placement and order for each column, including the new links:

**Veteran programs and services**
Homeless Veterans
Women Veterans
Minority Veterans
PTSD
Mental health
Adaptive sports and special events
_VA outreach events_
National Resource Directory

**More VA resources**
VA forms
VA health care providers
Accredited claims representatives
VA mobile apps
Veterans Service Organizations (VSOs)
State Veterans Affairs offices
Doing business with VA
Careers at VA
_VA outreach materials_
Your VA welcome kit

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - Yes
   * **Link to VSP IA redirect request ticket:** 
     - https://github.com/department-of-veterans-affairs/va.gov-team/issues/14468

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Please deploy live by Veterans Day (optimally, by Thursday Nov. 5)

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Public Websites
- DEPO product owner: @johnhashva 
- Product manager: @brianalloyd 
- Designer: @andaleliz 
- FE engineer: @kelsonic 
- Product/team Slack channel: #vsa-public-websites

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by zacharymorel** [comment]
PR Created.

**Comment by zacharymorel** [comment]
PR Merged!

**Comment by zacharymorel** [comment]
Verified:
![Uploading Screen Shot 2020-11-12 at 1.35.01 PM.png…]()

**Comment by mnorthuis** [comment]
@johnhashva @brianalloyd the changes to the order and labels in the "More VA resources" column were not implemented per the recommendations above, are those being handled in another issue?

**Comment by johnhashva** [comment]
@mnorthuis this was a miss on my part during validation.   @brianalloyd should we-open this ticket and re-assign to Zach (if it's easy)?  I'm guessing that will be more efficient.  LMK.

**Comment by brianalloyd** [comment]
@johnhashva, reopening the ticket and will reassign to @zacharymorel for update as I think he's closest to the implementation needs for this ticket.  We can close out once updates have been applied and validation has been achieved.

**Comment by zacharymorel** [comment]
PR in review.

**Comment by johnhashva** [comment]
@zacharymorel Hi Zach -- will there be a way for @mnorthuis and I to validate this on staging before it's pushed live into production?

**Comment by zacharymorel** [comment]
@johnhashva , great questions. it looks like it was just pushed to staging. 
https://staging.va.gov/

**Comment by zacharymorel** [comment]
Great question @johnhashva , after it is merged, it should be deployed to staging within a few minutes. 

https://staging.va.gov/

**Comment by zacharymorel** [comment]
@kelsonic or @youngfreezyVA can y'all have a look at https://github.com/department-of-veterans-affairs/vets-website/pull/15057 when y'all get the chance?

**Comment by zacharymorel** [comment]
PR merged, it well be ready to validate once the deployment to staging is met.

**Comment by zacharymorel** [comment]
@johnhashva This is ready to be Validated on https://staging.va.gov/

**Comment by johnhashva** [comment]
@zacharymorel looks good, except -- we need to lower-case "outreach" "materials" and "events" as specified by @mnorthuis 

VA outreach materials
VA outreach events

**Comment by zacharymorel** [comment]
@johnhashva or @MarciMcGuireGCIO this user story is ready for validation on https://staging.va.gov/

**Comment by johnhashva** [comment]
@zacharymorel approved!  closing ticket to reflect completion.   TY.
