### ISSUE TITLE
VSA eBenefits Onboarding

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1538]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [x] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist
- [x] Attend general onboarding meeting
- [ ] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md) **_[(see issue #1303)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1303)_**
- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md) **_[(see issue #1652)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1652)_**
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md) **_[(see issue #1653)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1653)_**
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md) **_[(see issue #1654)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1654)_**
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md) **_[(see issue #1656)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1656)_**
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md) **_[(see issue #1657)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1657)_**
- [x] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub **_[(see issue #1660)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1660)_**
- [x] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/DigitalModernizationStrategy.pdf) **_[(see issue #1661)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1661)_**
- [x] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/The-new-VA.gov-briefing-2019-07.pdf) documentation **_[(see issue #1662)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1662)_**
- [x] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [x] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md) **_[(see issue #1665)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1665)_**
  - [x] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [x] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [x] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [x] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [x] Designers: Attend breakout session
- [x] Engineers: Attend breakout session
- [x] Front-end Engineers: Attend deep-dive session
- [x] Back-end Engineers: Attend deep-dive session
- [x] PM, Designers and Content Writer(s): Request content and IA intro **_[(see issue #1557)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1557)_** with @mnorthuis @peggygannon @thatmattjohnson @meganhkelley 
- [x] PM and Front-End Engineers: Request analytics intro with @nedierecel and @joanneesteban 
- [x] PM Request 508 intro with @1Copenut 
- [x] PM and Engineers: Request load testing intro with @peterhill-oddball 

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [x] Assign the issues to individual(s) to complete
- [x] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [x] Attach the issues to this Epic

**Comment by steve-gov** [comment]
Seems like most of these links are 404? There doesn't seem to be an "Administrative" directory in the va.gov-team root.

**Comment by mnorthuis** [comment]
@steve-gov updated the links above, they should all be correct now, but please let me know if you continue to have issues. These all changed with the updates to the va.gov-team repo last week and were corrected in the onboarding epic template but not in the individual epics already created.  Sorry about that!
