### ISSUE TITLE
Front-End Template Work for Outreach & Events Page

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#15394]
## Why you're here 

The VEO team would like for the following capability in the [Events page ](https://www.va.gov/outreach-and-events/events/) : As a Veterans Experience Office employee, I want to set the times for events using my local time or the event’s local time so that I don’t make a mistake converting to EST.

Current date fields in the page don't support time zones.  The CMS team has implemented this functionality as outlined in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2813) -- and now front-end work needs to be done to complete and deploy this new authoring feature.  (Note: The VAMC team is also implementing this [change for local facility sites](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14578).  CMS will support the FE work required for this template change.)
      
### Desired/target implementation date

Best case: Deployed live by Veterans Day (with CMS dependency). Acceptable: Prior to Thanksgiving holiday code freeze.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Public Websites
- DEPO product owner: @johnhashva 
- Product manager: @brianalloyd 
- Designer: @andaleliz 
- FE engineer:  @ncksllvn 
- Product/team Slack channel: #vsa-public-websites

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by johnhashva** [comment]
@jenniferlee-dsva yes, either Sam -- or Brian and I yesterday talked about the new PW/Forms FE engineer who is on-boarding this week -- Zach Morel.   So we are all good on this front.

**Comment by johnhashva** [comment]
@zacharymorel + @brianalloyd while not directly related, this[ newly discovered breadcrumb issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15864) for Outreach & Events might be something to consider in tandem with this work -- once you assess, let me know.

**Comment by johnhashva** [comment]
11/10 Update: Confirmed that Facilities team is solutioning both the local time zone and breadcrumb issues for the Outreach and Events page.
