### ISSUE TITLE
Infrastructure Recommit - Solution Design Doc 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15396]
## Description
We need a place in the open to present and talk through our ideas for infrastructure recommit and re-design. 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Complete a Design doc and ask for feedback_

## Definition of Done
- [ ] _Design doc is created_
- [ ] _Team and leadership provides feedback _
- [ ] _Doc is updated_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Good starting place: https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594199/VSP+Infrastructure+Design+Doc
