### ISSUE TITLE
[Monitoring] Design doc for platform monitoring with Datadog

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15395]
## Description
Create a design doc that describes how Monitoring using Datadog will be implemented. 

## Background/context/resources
[Design doc template](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594189/design-doc-template)

---
## Tasks
- [ ] _Complete a Design doc and ask for feedback_

## Definition of Done
- [ ] _Design doc is created_
- [ ] _Team and leadership provides feedback _
- [ ] _Doc is updated_

**Comment by jhouse-solvd** [comment]
This issue can be closed. See #13748 for more info.
