### ISSUE TITLE
Load testing framework for the VSP

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#154]
## Description

Load testing has historically been a bit of a friction point while launching new features. We expect that teams are load testing their applications, but often come in with very little real world experience of how to do it and are sometimes met with resistance by upstream partners (lower environments are not necessarily auto-scaled or able to handle load, asked to not test in prod, etc). Access to test users can also be difficult as we have to match user identities across systems and not all of our test users may have access to a particular feature we may be launching.

We also do not have a strong story today around testing a particular feature vs testing the platform. Goals for testing a feature would revolve around ensuring a particular backend can withstand some expected load within a given SLO and help find breaking points (goals should be written and thought through much more than this). Platform tests would sort of depend upon being able to push an application or set of applications to ensure that the protections we have in place can keep the API up and properly provide protection from one specific feature affecting others.

## AC

- [ ] Documentation on expectations and goals for load testing by a developer on VSP
- [ ] Documented goals and PoC of broader load testing strategy
- [ ] Ensure developers on VSP have access and can contribute to load testing plans/scripts and documentation

**Comment by kreek** [comment]
@hpjaj eventually this will be part of the steps to build an endpoint (and maybe part of the tutorial)

**Comment by wyattwalter** [comment]
Closing off https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15786 with the final bullet point here in acceptance criteria (access and documentation).

**Comment by jhouse-solvd** [comment]
@mchelen - I found this in the backlog which is relevant to the discussion on #36563

@JoeTice & @pjhill - Has there been any development of a load testing approach or framework for the platform? Curious to know how we might be able to leverage your team as it relates to migrating Vets-API.

**Comment by pjhill** [comment]
Load testing enhancements have generally been deprioritized on our roadmap. That said, we have --
1. Upgraded the platform prescribed tool for load testing, Locust, to a 1.x version with more stable performance and a better set of features.
2. Brought some of the existing load tests up to spec with the new version of Locust
3. Ran the tests again and stored the new results in `devops`

We should be able to pull the tests off the shelf and run them again without much issue 🤞

**Comment by jbritt1** [comment]
With this info from @pjhill, could this one be closed at this time?

**Comment by pjhill** [comment]
Yeah, load testing needs some care and attention, but the prescriptions made in this ticket are perhaps a bit outdated. If we DO want to make some improvements to our support for load testing it's probably worth creating a new initiative for it with up-to-date goals and acceptance criteria.

**Comment by rmtolmach** [comment]
Great! Closing.
