### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Altoona VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15456]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Altoona has 133 Facility Health Services total:**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
- [x] Altoona VA Medical Center
- [x] DuBois VA Clinic
- [x] Huntingdon County VA Clinic
- [x] Indiana County VA Clinic
- [x] Johnstown VA Clinic
- [x] State College VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.

**Comment by ltrombley** [comment]
Task #15456 - Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Altoona VA Health care system facilities is complete and moved to Validate
1. Orphan VAMC: - James E. Van Zandt Veterans' Administration Medical Center
