### ISSUE TITLE
[Communication] Present Kick-off presentation and provide data collection tools to each System in VISN 23 [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15450]
## Issue Description
_As a system PAO and/or Web maintainer, I need to know the details of the product and what my expectations should be from my team and what the VAMC team will provide, so I can best prepare, validate, communicate, and input updates for the new VAMC website.

## Tasks
Coordinate and provide schedule for initial Kickoff meeting to as many System PAOs that can attend and provide the following:
- [x] Detailed presentation on the History, actions to be taken, and tools that can be used to complete the data collection.
- [ ] Estimated timeline for completion, even though this depends on the PAO feedback and engagement.
- [ ] Copy of the presentation and any questions asked during the meeting
- [ ] System/facility Playbook - excel document for each system below:
- [ ] Facility "Plan for your visit" Information sheet (May be attached to above) for each system below
- [x] VA Black Hills health care
- [x] VA Central Iowa health care
- [x] VA Fargo health care
- [x] VA Iowa City health care
- [x] VA Minneapolis health care
- [x] VA Nebraska-Western Iowa health care
- [x] VA Sioux Falls health care
- [x] VA St Cloud health care

## Acceptance Criteria
- [ ]  Kick off meeting is complete and attendees are tracked.
- [ ] POC list is received from VISN for further communications
- [ ] Health service and facility plan for your visit playbooks have been sent to Systems

**Comment by ltrombley** [comment]
Health Services Playbooks and Facility Workbooks are complete and distributed per the POC list.
