### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Butler VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15457]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Bulter VA has a total of 125 Facility health services**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
- [x] Abie Abraham VA Health Care Center (HCC)
- [ ] Sergeant Joseph George Kusick Community Living Center (CLC) 
- [x] Armstrong County VA Clinic
- [x] Clarion County VA Clinic
- [x] Cranberry Township VA Clinic
- [x] Lawrence County VA Clinic
- [x] Michael A. Marzano Department of Veterans Affairs Outpatient Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.

**Comment by ltrombley** [comment]
Task #15457 - Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Butler VA Health care system facilities 
1. Pending response to missing Sergeant Joseph George Kusick Community Living Center (CLC) Health Service in Drupal.
