### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Pittsburgh VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15466]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Pittsburgh has 142 Facility Health Services total:**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
- [x] Pittsburgh VA Medical Center-University Drive 
- [x] H. John Heinz III Department of Veterans Affairs Medical Center (Completed by Dave C.)
- [x] Beaver County VA Clinic 
- [x] Belmont County VA Clinic 
- [x] Fayette County VA Clinic 
- [x] Washington County VA Clinic 
- [x] Westmoreland County VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.
