### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Philadelphia VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15463]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Philadelphia has 109 Facility Health Services total:**
**To include:**
* Is a referral required?
* Are Walk ins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
- [x] Corporal Michael J. Crescenz VA Medical Center
- [x] Burlington County VA Clinic
- [x] Camden VA Clinic
- [x] Gloucester County VA Clinic
- [x] Victor J. Saracini Department of Veterans Affairs Outpatient Clinic
- [x] West Philadelphia VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.

**Comment by lealester** [comment]
moved to in progress - will become apart of Sprint 38 12.29.2020

**Comment by EdwardBoehme05** [comment]
Lea completed pages up to and including:
Podiatry - Victor J. Saracini Department of Veterans Affairs Outpatient Clinic

Ed completed this page and all pages below it:
Polytrauma and traumatic brain injury - Corporal Michael J. Crescenz Department of Veterans Affairs Medical Center
