### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Erie VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15461]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Erie has 92 Facility Health Services total:**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
- [x] Erie VAMC
- [x] Ashtabula County VA Clinic
- [x] Crawford County VA Clinic
- [x] McKean County VA Clinic
- [x] Venango County VA Clinic
- [x] Warren County VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [ ] **Contact PM on how to best confirm data is accurate.

**Comment by ltrombley** [comment]
**Task #15461 - Erie VA Health care system facilities - Pending discussion/decision on the following:**
1. Removal/dissolution of Lancaster County VA Clinic which belongs under Lebanon VAMC
2. Removal/dissolution of Respiratory Therapy (95 Health Service list = Pulmonary Medicine) and Ambulatory surgery center (95 Health Service list = Surgery)
