### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Wilmington VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15465]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Wilmington has 115 Facility Health Services total:**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
- [ ] Wilmington VA Medical Center
- [x] Atlantic County VA Clinic
- [x] Cape May County VA Clinic
- [x] Cumberland County VA Clinic
- [x] Kent County VA Clinic
- [x] Sussex County VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.

**Comment by lealester** [comment]
moved into in progress 12.22.2020

**Comment by lealester** [comment]
moved into validate 12.28.2020
