### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for Wilkes-Barre VA Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15464]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**Wilkes-Barre has 91 Facility Health Services total:**
**To include:**
* Is a referral required?
* Are Walkins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**
- [x] Wilkes-Barre VA Medical Center
- [x] Allentown VA Clinic
- [x] Columbia County VA Clinic
- [x] Northampton County VA Clinic
- [x] Sayre VA Clinic
- [x] Tobyhanna VA Clinic
- [x] Wayne County VA Clinic
- [x] Williamsport VA Clinic

## Acceptance Criteria
- [ ] All facility health services are updated
- [ ] **Contact PM on how to best confirm data is accurate.

**Comment by lealester** [comment]
moving into validate; items highlighted in green were in Drupal but not reflected on worksheet
