### ISSUE TITLE
Publish R&S articles on Prod

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15474]
## Issue Description
Once internal review is complete in the demo environment Resources and Support is ready for launch in prod. We need to set all articles to publish for go-live on 11/4.

Randi will confirm with the CMS team that we will be doing a batch publish of R&S rather than publishing each article individually. 

We also need to make sure we remove any sample nodes we built with test copy. We should have at least two content team members comb through to ensure we found them all. 

---
## Tasks
- [x] Discuss with CMS team how publishing will work (Randi)
- [x] Delete all sample templates from prod (Randi/Selina)
- [x] Publish content on 11/4 (Randi)

## Acceptance Criteria
- [x] All R&S articles are live
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
R&S published 11/4. Closing ticket! FYSA @brianalloyd @bethpottsVADEPO
