### ISSUE TITLE
Enable Review Instances to reach Salesforce CARMA

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#15486]
## Description
@kevinmirc submitted [this PR](https://github.com/department-of-veterans-affairs/devops/pull/7863) to configure review instances to connect to SFDC CARMA.

It appears CARMA has only specific IPs whitelisted so this request it to configure the review instances to use the TIC and fwdproxy for outbound requests.

## Background/context/resources
https://dsva.slack.com/archives/CBU0KDSB1/p1603898242158500

## Technical notes
Error from review instance:
`Salesforce Auth Response Body: -- { "error" => "invalid_grant", "error_description" => "ip restricted" }`

URLs:
```
lookup('credstash', 'carma.staging.url', version='0000000000000000002')
lookup('credstash', 'carma.uat.url', version={latest})
lookup('credstash', 'carma.entsd.url', version={latest})
lookup('credstash', 'carma.uat.url', version={latest})
```

---
## Tasks
- [ ] Investigate / discovery around fix
- [ ] Test change
- [ ] Deploy change
- [ ] Verify connectivity

## Definition of Done
- [ ] Review instances can successfully connect to CARMA (confirmed by @kevinmirc 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed

**Comment by jhouse-solvd** [comment]
@dginther to understand needs and urgency on this request.

**Comment by dginther** [comment]
It appears that this just needed some configuration on the review instances to direct CARMA URLs to the fwdproxy in vagov-staging.

Once Kevin has tested this, we can close this.

**Comment by jhouse-solvd** [comment]
@kevinmirc - Let us know when you've had a chance to test, and whether or not this addressed your immediate need. Thank you!

**Comment by jhouse-solvd** [comment]
@kevinmirc - Have you had a chance to test this? We are leaving this ticket open until we receive your feedback.

**Comment by kevinmirc** [comment]
Hi @jhouse-solvd,

I made two attempts to spin up a review instance today with [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5376) and it was not successful. Jenkins had the following error during the "Review" stage:

```bash
[2020-11-23T19:06:48.502Z] using credential va-vfs-bot
[2020-11-23T19:06:48.515Z] Cloning the remote Git repository
[2020-11-23T19:06:48.515Z] Cloning repository https://github.com/department-of-veterans-affairs/devops.git
[2020-11-23T19:06:51.548Z] ERROR: Failed to clean the workspace
[2020-11-23T19:06:51.548Z] jenkins.util.io.CompositeIOException: Unable to delete '/var/lib/jenkins/workspace/deploys/vets-review-instance-deploy'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[2020-11-23T19:06:51.549Z] 	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:90)
# ...
```

**Comment by jhouse-solvd** [comment]
@kevinmirc - I know there has been a lot of movement around review instances including other issues that may have been blocking you from confirming whether or not this works. 

Can you please comment as to the current status of this specific request, and whether additional work will be needed in the future to enable this for your team? Thank you!

**Comment by kevinmirc** [comment]
Hi @jhouse-solvd,

Thanks for following up. I was able to check the review instance and think @dginther's assumption is spot on.

I believe our staging env is connecting to salesforce's staging env directly (no fwd proxy), but I cannot do this from a review instance (assuming because it's not in the same network).

So to resolve this, I'd need a URL that routes to the fwd proxy and then to CARMA's staging URL. This fwd proxy URL will only be used in the Review Instance and our staging env can stay exactly how it's configured today (leaving the credstash value`carma.staging.url` as it is, and letting our staging talk directly to CARMA's staging).

Please let me know if it's possible to make a fwd proxy URL for the use of connecting to CARMA from the Review Instance.

Thank you!

**Comment by jhouse-solvd** [comment]
@kevinmirc - assigning to @dginther who will follow up with you today/tomorrow. thanks for the feedback!

**Comment by jhouse-solvd** [comment]
@kevinmirc - just following up on this. did you get the input that you needed from demian to enable this functionality? or did you find another suitable workaround. wanting to know if this issue can be closed? thanks in advance for your feedback.

**Comment by kevinmirc** [comment]
@jhouse-solvd I just need a fwd proxy added so RI can reach CARMA Staging and it will resolve this issue. Not sure if that would be a separate ticket or we can close this since we found the root of the issue.

**Comment by ala-yna** [comment]
@jhouse-solvd - just following up on this. Sounds like the last step is for ops to create a forward proxy URL. Would you like me to spin up a separate ticket?

**Comment by jhouse-solvd** [comment]
I followed up with @kevinmirc in a direct message, but adding here for visibility as well. 

I believe that all that is left is to add the correct internal fwdproxy URL to the app's configuration. The fwdproxy already has th e correct mapping that will route traffic to salesforce properly over the Internet. 

the fwdproxy URL was sent to Kevin in a private chat, and he indicated that he would give this a go tomorrow, and that it was safe to close the ticket for now. 

please let us know if we need to re-open the ticket or if anything further is required. cheers!

**Comment by kevinmirc** [comment]
Hi @jhouse-solvd, I tried to connect to salesforce with the provided fwdproxy URL but I was not able to connect, the request just hung. Here are the steps I used to test: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15881#issuecomment-773618304

Maybe I have the wrong URL or I'm missing a step?

**Comment by ala-yna** [comment]
Hey @jhouse-solvd, is this on your radar? ^

**Comment by jhouse-solvd** [comment]
@ala-yna @kevinmirc - let us have a look at the url that Kevin is using are using and help move this forward. sorry for any delay, but we will follow up to find out what's left to resolve.

**Comment by jhouse-solvd** [comment]
sending a direct message to Kevin to get some info about the URL(s)

**Comment by jhouse-solvd** [comment]
Kevin and I have been in touch and I've shared some additional internal connection details / settings for him to try. He will give it a shot early next week and let us know what he finds. We will stay on top of it to helpfully push this forward towards resolution quickly.

**Comment by kevinmirc** [comment]
Hi all, with @jhouse-solvd's help, I was able to connect to CARMA successfully by (1) appending the correct port number on the fwdproxy URL and (2) updating local.settings.yml in the RI we were testing in (the parent class for CARMA::Client::Client was overriding my hardcoded URL, so updating the settings applied the URL changes across all references).

I've opened a [PR](https://github.com/department-of-veterans-affairs/devops/pull/8598) to update the deployment settings. Once merged, I will test on a newly built RI and report back here.

Thanks!

**Comment by kevinmirc** [comment]
@jhouse-solvd, @dginther, Today I was able to successfully connect to CARMA from a RI, using the fwdproxy provided and the [updated settings](https://github.com/department-of-veterans-affairs/devops/pull/8598). Thank you very much for the help!

**Comment by jhouse-solvd** [comment]
@kevinmirc - that's great news. closing. please submit a new issue (or re-open this one if relevant) if anything else is needed
