### ISSUE TITLE
Implement Final Punch List for "View your VA Payments"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15484]
## Goal
The last few items for View Payments need to be addressed and should be found here.

## Considerations
Further feedback from usability prep call:
- [Content](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15440)
- [Information Architecture](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15639)
- [Accessibility](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15638)

## Tasks
- [x] The breadcrumb should say, "Your VA payments"
- [x] The intro text below the H1 need to have line-height increased--it's too tight.
- [x] Change intro text to "Check your payment history for your VA disability compensation, pension, and education benefits."
- [x] Need standard space (padding/margin) below last paragraph
- [x] The line, "If you have questions about payments made by VA, please call the VA Help Desk at 800-827-1000," is its own paragraph
- [x] Right sidebar content needs left/right margin in mobile view
- [x] Link to profile" in sidebar should read, "Go to your profile"
- 🙈 Right align numerical columns, e.g. Amount, Account, Check # etc. **We are now using the standardized component and don't have the ability to move these headers on our own (that logic is within the Design System).**
- [x] Sentence case these labels: "Issue date" and "Cancel date"
- [x] There is no padding between the Payments table and the following paragraph when the is no pagination stepper
- [x] Change content of "Missing check" paragraph, and right side bar content to match mockup

## Acceptance Criteria
- [x] All items in the list above are addressed OR
- [x] Items that cannot be addressed are documented with a brief explanation in the comments
