### ISSUE TITLE
Claims File Upload Discovery

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15489]
## User Story
Determine how the claims file upload feature can be simplified for MVP.

## Tasks
- [ ] Get Grafana access
- [ ] Review upload stats in Grafana
- [ ] Determine if we set stricter bumpers (e.g. page limit, file type limit) for MVP, and if so what

**Comment by bridgethapner** [comment]
Working on Grafana access

**Comment by srmyers17** [comment]
- need COR to grant access to Grafana

**Comment by bridgethapner** [comment]
Working on Grafana access to be able to do this, likely will come thru today

**Comment by bridgethapner** [comment]
I think we should leave the upload flow mostly as-is with the following changes: 
- Communicate 50 MB upload limit in the UI 
- Define error state for if the user tries to upload a file that is larger than 50 MB
- Set a limit that users can't take more than 15 photos for a single file if using the camera app
