### ISSUE TITLE
Finalize and Submit Contact Center Docs and Video for Review (View Payments)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15493]
## Background
Now that the feature is largely done and leverages user data the way it is intended, we need to create a user manual for the support center to have on hand in case there is ever an issue with the feature and someone calls in.

## Tasks
- [x] Take the initial draft and complete it with the final screenshots and address any other functionality in the feature.
- [x] Write a short narrative that describes the service and calls that are in use and where and when they come from.
- [x] Per the [collaboration cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#contact-center-review) request a review per those instructions.

## Acceptance Criteria
- [x] The artifacts have been created (doc and video)
- [x] A request for review has been submitted
