### ISSUE TITLE
Medallia User Research Planning

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#15494]
## Issue Description
Organizing and conducting user research with veterans and other VA.gov users ahead of final medallia implementation. 

---
## Tasks
- [ ] Create User research plan 
- [ ] User research scripting

## Acceptance Criteria
- [ ] First draft or user research plan

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
@

**Comment by clantosswett** [comment]
@ianMcCullough-ob I would take some time reviewing the research repo found here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research There are some special things about doing user research with the government and this should lay out the process of how it works. If you have questions, I would reach out directly to Alex Taylor, who is one of the listed POCs.
