### ISSUE TITLE
Replace 'Appointments' with 'Health care' in the bottom nav

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15490]
# User Story
As the VA mobile app team, we want to update the app's bottom navigation element of **Appointments** to be replaced with **Health care** so that both Appointments and Secure Messaging are accessible from the bottom navigation of the app. 

Screenshot:
![Group 4.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/45fc0e98-1aed-465f-9c3b-b5611da63eb0)

# Tasks
- [ ] Select or design a new icon to represent Health Care
- [ ] Design both an unselected and selected state for the Health Care navigation item 
- [ ] Design review
- [ ] Update Design Library file with new bottom navigation

**Comment by ayushchak** [comment]
Closing since this decision may be revisited based on what we decide re: health landing page placement.
