### ISSUE TITLE
Compile Resources for Privacy and Security Review (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15500]
## Description
One of the final steps in the collaboration cycle is scheduling a privacy and security review with VSP to ensure an application meets platform standards before going to production. 

## Considerations
- [Collab Cycle meeting description](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)
- all artifacts need to be compiled two days prior to the review meeting [per collab cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review).

### Backend
1. Architecture diagram showing involved systems and data flow.
    - [Example here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8179) (Backend)
1. Description of any new publicly exposed endpoints
1. Description of any new interactions with 3rd party services
1. Description of any other security hotspots you're concerned about   
### Product
1. Link to the release plan for your application (To be addressed by Product [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10825))
    - [Release Plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)

## Tasks
- [ ] Compile all above artifacts into the [Privacy and Security GitHub folder under the Dependency Claims feature](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/privacy-and-security)
- [ ] Ask Jason to create a request per [these instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)

## Definition of done
- [ ] All artifacts have been provided and stored somewhere safe
