### ISSUE TITLE
Identify/Prioritize which VSP services Ops will migrate next

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15505]
## Issue Description
_In order to continue our work of migrating services to our new infrastructure (AWS Fargate), we need to review the list of services and prioritize which services are likely candidates to move next. This decision will likely be based on things like priority, importance, ease of transition, level of effort, etc._

[Link to VSP Services Inventory spreadsheet](https://docs.google.com/spreadsheets/d/1yepBUloBtH1gWLDCCXxAeUW2CwUo0_ZoP06uAOJOywE/edit#gid=0)

---
## Tasks
- [x] _Determine (at a very high-level) what is necessary to move each service (or at least a subset of services)_
- [x] _Update VSP Services Inventory spreadsheet with planned migration order_

## Acceptance Criteria
- [x] _Identification of which services Ops will migrate next_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Since I am transitioning to support this week and we put some tiers to the items in our services list, going to call this one complete at this time. If my thought is in error, please feel free to reopen.
