### ISSUE TITLE
[UI] Notifiy Veterans they have a Questionnaire

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#15509]
## User Story
- As a Veteran, I want to be notified in advance of my health care visit that a questionnaire is needed to be completed, so that I don't have to fill it out in the waiting room and can complete when convenient and relevant for me.
 As a Veteran, I want to be notified in a similar or the same appointment reminder that I receive today, so that the questionnaire is in context of the visit I am planning to attend.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- Notifications Feature Outline

## Description
- Create workflow and mockups of the veteran experience with emails and text notifications using VA Notify and VeText

## Tasks
- [x] [Create storyboard of workflow for a veteran receiving an email to questionnaire](https://zpl.io/2GXmyx4)
- [x] [Create a storyboard of workflow for a veteran receiving a text to a questionnaire](https://zpl.io/bJXK7PK)
- [x] Mockup of both [text](https://zpl.io/2ppd4nr) and [email](https://zpl.io/V08Eqvo) the veteran will receive
- Generic Zeplin link that anyone can access...look at the Notification section for all of these diagrams: https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780

## Acceptance Criteria
- [x] Review text and email with content
- [x] Review storyboards with product, Ming, and Lacey

**Comment by kristenmcconnell** [comment]
Draft of the texting experience can be viewed here: https://zpl.io/2ErXn1D or https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780 (navigate to the Notifications section).

**Comment by kristenmcconnell** [comment]
Content's feedback for text messages can be viewed within story #16940. Wireframes have been updated to reflect this wording.

**Comment by kristenmcconnell** [comment]
@abuckley3385 Check out the above links mentioned in the story.
I think that I have everything as up-to-date as possible with everything that we currently know. Let me know if you have any feedback.
