### ISSUE TITLE
VA311 COVID-19 IVR Content Review

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#15516]
## Issue Description
The VA311 number is used to triage general covid-19 calls. There is a section of the IVR (interactive voice recording) that is dedicated to COVID-19 issues. This has not been updated in months and should be reviewed and updated using the VA.gov FAQ content as a guideline.

VA311 Phone Number: 844-698-2311
VA.gov COVID-19 FAQ Page: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

---
## Tasks
- [x] Review current COVID-19 language on VA311 IVR
- [x] Develop new content for IVR
- [x] Receive approval from VEO Contact Center Group
- [ ] Record new content

## Acceptance Criteria
- [ ] Newly recorded IVR message for COVID-19 information
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Here is the text of the covid-19 IVR FAQs.

[COVID 19 FAQs and IVR scripts (003).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5467490/COVID.19.FAQs.and.IVR.scripts.003.docx)

**Comment by starlow00** [comment]
Test

**Comment by starlow00** [comment]
Here's my draft, Chante. Let me know if I should send it differently:

[https://app.zenhub.com/files/133843125/f69f757f-2722-4352-8558-bcf7a69ba8a8/download](https://app.zenhub.com/files/133843125/f69f757f-2722-4352-8558-bcf7a69ba8a8/download)

**Comment by clantosswett** [comment]
@starlow00 I reviewed the the new IVR script. I had a few comments and questions but overall it looks good. The big consistent comment is about URLS. Since this is a recorded voice message, I don't think we can use the long URLs. Maybe we should point people to short URLs (www.cdc.gov or www.va.gov) when we suggest they do something online. Feel free to noodle on that and make those changes. Let me know once you've done that and we will start routing around for reviews with the various groups.

Thanks!

[https://app.zenhub.com/files/133843125/bafa1726-654f-4fa9-b6c3-b17fc07e893e/download](https://app.zenhub.com/files/133843125/bafa1726-654f-4fa9-b6c3-b17fc07e893e/download)

**Comment by starlow00** [comment]
@clantosswett Updated draft attached, _[https://app.zenhub.com/files/133843125/4f8a21d2-efd8-4d07-9a95-3bf330d9d958/download](https://app.zenhub.com/files/133843125/4f8a21d2-efd8-4d07-9a95-3bf330d9d958/download)starlow111320

**Comment by clantosswett** [comment]
Reviewed @starlow00 draft. Submitted to JTF for review and have reached out to the VA Tier 1 contact center to determine who will be responsible for making the updates to the IVR once it has received approval.

**Comment by clantosswett** [comment]
Danielle Thierry came back with a bunch of edits. Also, during a call with the VEO contact center we were given instruction on how to label the new content so it can be added. I will be following up over email to ask for this information so we can complete that task. 

[https://app.zenhub.com/files/133843125/762a46c2-4508-49db-8d42-5ae59252877f/download](https://app.zenhub.com/files/133843125/762a46c2-4508-49db-8d42-5ae59252877f/download)

**Comment by clantosswett** [comment]
We received the file that lists out the current content for the covid-19 recording. I'll work on the matching of the categories/sub-categories so we can then route for final approval!

[Uploading... COVID 19 FAQs and IVR recordings.docx ]

**Comment by clantosswett** [comment]
Tried to do the matching between the two documents and now have this document to share back over with the VEO group for approval. It's a bit messy so we might need to take some time to review it on Friday during our meeting.

**Comment by clantosswett** [comment]
Re-adding the document that I accidentally deleted.

**Comment by starlow00** [comment]
@clantosswett I've uploaded a new draft that incorporates Danielle's edits and the document sent by Ahmed Kochaji. A couple of questions are made in the notes.[https://app.zenhub.com/files/133843125/80567740-42da-4c6e-818b-9cae6e72088a/download](https://app.zenhub.com/files/133843125/80567740-42da-4c6e-818b-9cae6e72088a/download) Questions/needs, let me know!

**Comment by clantosswett** [comment]
We have received approval from VEO and Joint Task Force. They are targeting to record this week.

**Comment by starlow00** [comment]
@clantosswett Just following up on this for recordkeeping. Do we know if this has been recorded and can this ticket be closed? (cc @jwoodman5)

**Comment by Kimberley2019** [comment]
Discussion was had during the weekly sync and VEO stated that this is currently on hold.  Information is changing quickly and how to move forward is up in the air.

**Comment by Kimberley2019** [comment]
@clantosswett have you received any additional information on this particular ticket?  Does the work that @starlow00 is currently doing for COVID-19 relate to this body of work as well?

**Comment by Kimberley2019** [comment]
@clantosswett can you provide an update on this ticket?  Can it be closed out?
