### ISSUE TITLE
[FE] Usability Testing Updates

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#15515]
## Related Documentation
 - Usability Testing Feedback Doc - not linked yet
- See updated mockups - not linked yet

## Description
Update the below tasks based on the user feedback

## Tasks
> this is a list of technical tasks that are needed for this ticket 

- [ ] Intro page- All new content needs updated for unauth. and auth
- [ ] Intro page- Moving button to bottom and Remove the top button
- [ ] Intro page- Button name update
- [ ] Intro page - Needs help - contact and numbers need updated
- [ ] Demo page - home vs. residential label on phone numbers
- [ ] Demo page - bolding removed
- [ ] This Visit - Reason for visit header font updates
- [ ] This Visit - Booking Note text box larger
- [ ] This Visit - Bottom next button label update
- [ ] Review page- Mailing and home labels updated vs. Street 1 & 2 (should be pulling from demo?)
- [ ] Confirm page- Sent box content updated 
- [ ] Confirm page- Add content about who to contact if there are questions about the appointment (VAMC and Clinic phone numbers)
- [ ] Confirm page- Button that links to Questionnaire Manager
- [ ] Confirm page- Button that links to VAOS (va.gov/health-care/schedule-view-va-appointments/appointments/)

## Acceptance Criteria
> when is the ticket done 
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Moved the tasking to the tickets: 

#15387, #14988, #13418 , #15521 , #15522 , and #15523
