### ISSUE TITLE
[FE] Questionnaire Manager - Page Layout

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#15525]
## User Story
As a veteran, 
I should have a landing page 
so that I can see my questionnaires.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f7b3ab94e155b94041d4c4b)

## Description
Create the landing page and page layout. 

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [x] Create the page for questionnaire manager
- [x] Add header, content, and place holder for tabs. 
- [x] Hide behind the same feature flag as the form 
- [x] authenticated only users
- [x] Create e2e tests 

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Approved, and waiting to verify in staging

**Comment by kristenmcconnell** [comment]
@mdewey Here is some of my feedback on the Questionnaire List as a whole based upon my Staging review.
![Artboard.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/3efcffe8-7766-425a-a26b-6ebf187c8d1b)
