### ISSUE TITLE
[FE] Update "This Visit Page from Research

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#15521]
## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d5e01a9b85b431a14)

## Description
Update the UI from user research 

## Tasks
- [x] This Visit - Reason for visit header font updates
- [x] This Visit - Booking Note text box larger
- [x] Missing Period in the message (from #13148 )
- [x] "Finish later flow" (from #13148 )
## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
I will need to spin the finish later flow into another ticket, it is a platform change to make the "start a new questionnaire" button hidden.

**Comment by mdewey** [comment]
from the other ticket: 

```
When I clicked "Finish this questionnaire later," I saw this (which I think is another spot that we originally didn't account for in this story)...
![Screen Shot 2020-10-30 at 4.49.54 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9f2c68ef-c78d-46cb-baa6-85b72558160f)

We should change the first sentence from "Your appointment questionnaire application has been saved." to "Your questionnaire has been saved." The "Start a new application" button should also be removed here.
```

**Comment by mdewey** [comment]
Created Ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/15895

**Comment by mdewey** [comment]
Merged and waiting for deployment to staging

**Comment by kristenmcconnell** [comment]
I was the form looking at something else and I saw that this page seemed to be updated. I reviewed it. It looks good, since I saw that the "start a new questionnaire" button is moving to another ticket.

**Comment by mdewey** [comment]
@abuckley3385 How does this look to you?

**Comment by abuckley3385** [comment]
did I miss the link?

**Comment by mdewey** [comment]
Its the same link as before: https://staging.va.gov/healthcare/questionnaire

**Comment by abuckley3385** [comment]
thanks for the link - i hadn't bookmarked it ( i will now!) l looks great!

**Comment by abuckley3385** [comment]
sorry i reviewed this last week it looks good!
