### ISSUE TITLE
Add SSN and fileNumber to 5655 Form Prefill

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#15526]
## Issue Description
Veterans will need to confirm their identity information, which will include the last four numbers of their SSN along with their VA File Number.

## Tasks
- [ ] Add VA fileNumber & SSN to the Form Prefill
- [ ] Add VA fileNumber & SSN to the vets-json-schema for Form 5655

## Acceptance Criteria
- [ ] fileNumber and SSN are available via the in the progress form endpoint for the 5655 form.
