### ISSUE TITLE
[FE] Populate the Quesitonnaire Manager with Mock data 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#15528]
## User Story
As a veteran, 
I should have a landing page 
so that I can see my questionnaires.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f7b3ab94e155b94041d4c4b)

## Description
Add mock API calls and populating data from a JSON file that is located in the vets-website. We are using mock data because we are still waiting for the FHIR specs and some decisions to be made on where we are storing association. 

## Tasks
- [x] Create the JSON structure needed for the API call
- [x] Call the fake API on page
- [x] show a loading screen until the call is complete
- [x] Show the upcoming questionnaires
- [x] Show the completed.  
- [x] Create tickets and determine how the real API will work. 
- [x] Create e2e tests 

## Acceptance Criteria
- [x] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
for ` Create tickets and determine how the real API will work.` I need to make tickets for : 

- integration with API 
- Once we get real data, what is the logic around determining if the questionnaire response is completed or not. 

Current status: in PR, waiting for the CI build to pass

**Comment by mdewey** [comment]
Closing: 

To centralize feedback for the questionnaire list, use this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16746
