### ISSUE TITLE
[FE] Update Review Page from UI Reseach

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#15522]
## User Story
As a Veteran, 
I should see a cohesive and accessible demographics page
so I can verify my information. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214c66caff64c73f44ba)

## Description
Update demographics page from research and accessibility

## Tasks
- [ ] Review page- Mailing and home labels updated vs. Street 1 & 2 

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
In staging, can you verify @kristenmcconnell and @abuckley3385? 

I am going to set a meeting for us to review all the UI research implementations

**Comment by kristenmcconnell** [comment]
The address changes look great. I'm still seeing the old button. I signed in as User 34 on Chrome.

![Screen Shot 2020-11-16 at 3.51.06 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/74a40bb2-a384-4295-9c21-6428cc3c5056)

**Comment by abuckley3385** [comment]
looks good!

**Comment by mdewey** [comment]
Good Catch @kristenmcconnell  I will that to a new ticket for next sprint.
