### ISSUE TITLE
[FE] Update Confirm Page from Research

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#15523]
## User Story
As a Veteran, 
I should see a cohesive and accessible demographics page
so I can verify my information. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214c66caff64c73f44ba)

## Description
Update demographics page from research and accessibility

## Tasks
- [x] Confirm page- Sent box content updated 
- [ ] Confirm page- Add content about who to contact if there are questions about the appointment (VAMC and Clinic phone numbers)
- [x] Confirm page- Button that links to Questionnaire Manager
- [x] Confirm page- Button that links to VAOS (va.gov/health-care/schedule-view-va-appointments/appointments/)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
@kristenmcconnell, Ran into a small issue. There is no facility phone attached to the appointment. I believe it is doable to get, but it would require some backend work to populate that information. I am okay with moving that to a separate ticket for now. What is the priority of having that phone number?

**Comment by kristenmcconnell** [comment]
Define facility. The VAMC (medical center) phone number or the clinic within the medical center. VAOS does display the VAMC phone number in their UI.

**Comment by mdewey** [comment]
Moved the phone numbers to a new ticket. https://github.com/department-of-veterans-affairs/va.gov-team/issues/16039

**Comment by kristenmcconnell** [comment]
I realized this when working on the PDF, the print button shouldn't say "Print this page," because you are printing the entire questionnaire and not just this page. I updated the wireframe to have the button say "View and print questions." This can be another ticket if need be or maybe the ticket that actually connects the bottom button to the questionnaire list, because it currently goes to the intro page and not the questionnaire list. I know that you were also working on the questionnaire list page this sprint as well.

**Comment by abuckley3385** [comment]
@kristenmcconnell  why are we using 'your' for go to your health care questionnaires and not for the button go to appointment details ?
@mdewey  - the updates look good

**Comment by kristenmcconnell** [comment]
@abuckley3385 Good question. My original idea was that "Go to your health care questionnaires" matches the title of the Questionnaire List page, which is "Your health care questionnaire." However, you are correct that it isn't consistent. Let me think on that.

**Comment by mdewey** [comment]
@kristenmcconnell  I will add that small feedback to a new ticket.

**Comment by kristenmcconnell** [comment]
@mdewey Great. Let me know the number and I'll add the details in that ticket.

**Comment by kristenmcconnell** [comment]
@mdewey - Is it #16278?

**Comment by mdewey** [comment]
@kristenmcconnell  Yes it is

**Comment by mdewey** [comment]
Moved to #16278.
