### ISSUE TITLE
[UX][Research] Full MVP Workflow Usability Test Analysis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15536]
## User Story
- As a product team and Veteran, we want to confirm the full MVP workflow is usable. <br/>
_This research will usability test a mobile and desktop version of the full MVP Veteran workflow to gain feedback._

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A research report detailing findings and design recommendations from the research study.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

## Acceptance Criteria
- [x] Create [research reports/readout documents of findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md)
- [x] Update the [research history](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md) document
- [x] Deal with recordings once analysis is complete
- [x] Create necessary issues/tickets that address findings in coordination with Amanda
- [x] Schedule readout sessions with stakeholders, team, Demos, UX weekly(?)

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mlighdc For review. I also set up a meeting to discuss this research when we return in the New Year.

Research report (PDF): [https://app.zenhub.com/files/133843125/1f96c5e0-8804-4595-8149-518d321a9cd1/download](https://app.zenhub.com/files/133843125/1f96c5e0-8804-4595-8149-518d321a9cd1/download)

You can find all research documentation on GitHub at: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/research/all-mvp-workflows
