### ISSUE TITLE
[UX][Research]Interactive Prototype for Full MVP Workflow usability test

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15532]
## User Story
- As a product team and Veteran, we want to confirm the full MVP workflow is usable.<br/>
_This research will usability test a mobile and desktop version of the full MVP Veteran workflow to gain feedback._

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
All assets (prototypes, designs, spreadsheet for observer notes) needed to run the user research session will be completed by the end of this ticket.

Testing will include the following topics:
- Notifications
- Questionnaire Manager 
- Save in Progress
- Print
- Demo Banner
- Marketing Page
- Updates from last UX testing
- Links to VAOS appts and or Secure Messaging and or Profile for demographics. 

## Tasks
- [x] Create [mobile prototype](https://preview.uxpin.com/d3c9bb8ac5052d077234b5e4b2f7749d0bc5200d#/pages/134593965/simulate/no-panels?mode=cvhidm)
- [x] Create [desktop prototype](https://preview.uxpin.com/db0b9ece7c8e0983a8baf1971db406af9f1d2201#/pages/134600037?mode=cvhidm)
- [x] Add assets to conversation guide in the specific test folder here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/conversation-guide.md

## Acceptance Criteria
- [x] Publish assets to final location (UXPin)
- [x] Review assets with the team (particularly product)

**Comment by kristenmcconnell** [comment]
Accidentally closed.
