### ISSUE TITLE
[UX][Research]Full MVP Workflow Usability Test Sessions

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15535]
## User Story
- As a product team and Veteran, we want to confirm the full MVP workflow is usable. <br/>
_This research will usability test a mobile and desktop version of the full MVP Veteran workflow to gain feedback._

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
We will have met with all Veterans and run the research protocol by the end of this story.

Testing will include the following topics:
- Notifications
- Questionnaire Manager 
- Save in Progress
- Print
- Demo Banner
- Marketing Page
- Updates from last UX testing
- Links to VAOS appts and or Secure Messaging and or Profile for demographics. 

## Tasks
- [x] Make sure all participant sessions are scheduled
- [x] Create notes doc for team to use
- [x] Invite team members to participant sessions

## Acceptance Criteria
- [x] Run the sessions with all the participants
- [x] Gather notes from notetakers
- [x] Download participant videos from Perigean website

**Comment by kristenmcconnell** [comment]
I met with 10 research participants: 8 Veterans, one caregiver, and one service member/medical professional.
