### ISSUE TITLE
[Discovery] Setup an instance of Storybook for developer evaluation 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15538]
## Issue Description
Do some discovery work on setting up an instance of Storybook for developers to use and evaluate. 
---
## Tasks
- [ ] Identify options for setting up an instance of Storybook
- [ ] Make a recommendation of where to host an instance for a pilot with developers

## Acceptance Criteria
- [ ] Hosting platform identified 
---

**Comment by caw310** [comment]
https://github.com/storybookjs/storybook-deployer

**Comment by cvalarida** [comment]
Options include:
- New S3 bucket set up to serve the static files
  - No domain name magic needed; we can just pass around the gross S3 bucket link while we're piloting it
- Chromatic
  - Free for open source
- Heroku
- GitHub pages
  - This is likely the easiest—especially if we don't get fancy with CI for starters and just manually update the `gh-pages` branch when we want it updated
  - I'd recommend this approach after we move the library to the new repo

**Comment by cvalarida** [comment]
I ran an experiment with GH Pages that worked pretty well. The result can be found at https://department-of-veterans-affairs.github.io/component-library/. Since this is a pilot right now, I favored a low barrier to entry approach (which means not setting up any CI for now). To publish Storybook right now, the steps are as follows:

1) Use `git subtree split` on the `formation-react` package to rewrite the git history on the master branch in the `component-library` repo
2) Run `npx storybook-to-ghpages` (from the `@storybook/storybook-deployer` package) to build the static pages and push them up to the `gh-pages` branch of the `component-library` repo

**Note:** You'll have to `npm install -g @storybook/storybook-deployer` to be able to run the deployer without adding it to the repo, which will cause problems when we need to update the git history with commits from the old repo again.
