### ISSUE TITLE
First Pass at Custom View Components for View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15549]
## Description
The View Representative contains a view functionality and a basic implementation of this needs to be added to the app. This initial implementation only needs to largely be static as the actual view action(s) will be added in a subsequent ticket(s). This ticket is mostly for building the initial structure for how the custom functionality will be built on the code side but any logic or data can be omitted at this point.

## Considerations
- [Prototype](https://preview.uxpin.com/00985ac7bf2e8454786086efbf1c89de82d5cb3c#/pages/127904094/simulate/sitemap)
- Some elements from View Dependents may be helpful here

## Tasks
- [ ] Buildout file and folder structure for View Representative
- [ ] Buildout initial component(s) for View Representative with no data and a static render
- [ ] Add content as it stands in the prototype to the basic component structure 

## Acceptance criteria
- [ ] The initial component structure for View Representative has been built
- [ ] Copy has been added per the design files as a first pass
- [ ] A PR for this ticket has been created and is awaiting approval

**Comment by jason-gcio** [comment]
https://preview.uxpin.com/00985ac7bf2e8454786086efbf1c89de82d5cb3c#/pages/127904094/simulate/sitemap
