### ISSUE TITLE
Remove fax info from Higher Level Reviews

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15543]
## Issue Description
Per stakeholder Fred Somers, VBA is winding down their use of fax machines and therefore we should remove any references to faxing from the higher level reviews page in decision reviews. 

Node to work in: prod.cms.va.gov/node/3003/edit

Change H3 to:
**Submit your application by mail or in person**

Remove section "By fax"

![Screen Shot 2020-10-28 at 4.57.53 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/3088d059-2b1b-47f0-8922-be60ad79e0d1)
---
## Tasks
- [x] Remove fax info from page (Selina)
- [x] Review changes and publish page (Randi)
- [ ] Notify stakeholder that change is live (Beth)

## Acceptance Criteria
- [x] Fax info removed from live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht I've made this change and the page is ready for review.

**Comment by RLHecht** [comment]
@lunascoop Thanks! I've reviewed and published this page. I added back the paragraph underneath the fax number line. @bethpotts You can let the stakeholder know this will be published after today's deployment.

**Comment by RLHecht** [comment]
This is validated on the live site. Closing ticket. FYSA @brianalloyd @bethpotts
