### ISSUE TITLE
View Representative Initial Project Scaffolding

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15545]
## Description
In order to get the initial folder and file structure set up for View Representative, we need to scaffold out the project in `vets-website`. This scaffolding will not include any of the custom functionality of the View Representative and all of the content in this scaffolding is heavily subject to change.

## Considerations
- Address the product decision doc in the feature folder
- [Prototype](https://preview.uxpin.com/00985ac7bf2e8454786086efbf1c89de82d5cb3c#/pages/127904094)

## Tasks
- [x] Either run Yeoman generator as non-form app OR manually build out the initial folder structure
- [x] Add a simple component structure to match the basic structure of the prototype as it currently stands
- [x] Add content as it stands in the prototype to the basic component structure

## Acceptance criteria
- [x] The initial folder and file structure for View Representative has been created
- [x] The View Representative page contains the page content as it currently stands in the mockup
- [x] A PR for this ticket has been submitted and is awaiting approval

**Comment by jason-gcio** [comment]
https://preview.uxpin.com/00985ac7bf2e8454786086efbf1c89de82d5cb3c#/pages/127904094/simulate/sitemap

**Comment by jason-gcio** [comment]
https://xd.adobe.com/view/e27b7e71-d920-4bcd-9e81-dc62a9665d5e-b728/
