### ISSUE TITLE
Meet with the Analytics team on View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15557]
`Attempt to do this asynchronously first, save the meeting`

## Goal
In order to track the success metrics for the View Representative we need to get Google Analytics events set up that speak to those metrics. So that the analytics team has a chance to establish those event names and what they are for we need to meet with them either in person or over Slack.

## Tasks
- [x] Connect with the GA/Insights Team (over either Slack or Zoom) to share what function and features this product is involved with, and a recommendation for what events they might be interested in tracking.
- [x] Document what events will be provided by the analytics team

## Acceptance Criteria
- [x] We have connected with the GA/Insights Team 
- [x] We have a document (ticket or otherwise) incoming that has all of the GA events needed for View Rep

**Comment by jason-gcio** [comment]
https://staging.va.gov/view-change-representative/view/ API would be good to capture
https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D

**Comment by jason-gcio** [comment]
Fails - Unable to load with code 500
None found - with code 400
Successful - 200

**Comment by jason-gcio** [comment]
request ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25876
