### ISSUE TITLE
Unit tests for Redux implementation

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15553]
# Background
In order to make sure that Redux on the View Representative behaves as expected we need to write unit tests for it. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for View Representative.

## Tasks
- [x] Set up test file
- [x] write unit tests for Redux on View Representative
- [x] submit a PR for review

## Acceptance Criteria
- [x] Redux on View Representative is unit tested it 80% coverage
- [x] A PR has been submitted for review
