### ISSUE TITLE
Add Google events to View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15558]
## Goal
Now that we have met with the Google Analytics Team on the View Representative and they have shared what the event names are going to be for it, we need to insert them into the code.

## Tasks
- [ ] Insert event names into the code for View Representative
- [ ] Submit PR for review

## Acceptance Criteria
- [ ] Code/event names provided by the GA/Insights Team has been inserted into the View Representative app for tracking
- [ ] A PR has been submitted for review
