### ISSUE TITLE
Swap dummy API call in Redux for correct URL and adjust data structure for View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15556]
# Goal
When we set up the View Representative page we built the Redux code so that it would be able to be connected to the API endpoint set up by back end. We need to connect Redux on View Representative to the endpoint that has been set up.

## Considerations
- [Swagger docs]()

## Tasks
- [ ] Adjust Redux action so that it hits a real URL and returns the data
- [ ] Adjust Redux reducer so that it accesses the correct data
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] Data for View Representative is now being pulled from the back end instead of a static file in the front end
- [ ] A PR has been submitted for review
