### ISSUE TITLE
Unit Tests for Custom View Component for View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15555]
`there will be multiple copies of this ticket as more components get built`

# Background
In order to make sure that the View Representative behaves as expected we need to write unit tests for it's logic. The established standard for VA.gov is 80% test coverage so we need to at least achieve this for View Representative.

## Tasks
- [ ] Set up test file
- [ ] Write unit tests for View Representative page
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The View Representative page is unit tested it 80% coverage
- [ ] A PR has been submitted for review
