### ISSUE TITLE
Refine Current View Representative Components to Better Match Mockup

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15552]
## Background
Since we work in an iterative fashion we initially set up the components for the View Rep when designs were still going through some stage of reviews. Now that the designs are further along we need to sync up the application components with the latest version of the mockup.

- [Mockup](https://xd.adobe.com/view/e27b7e71-d920-4bcd-9e81-dc62a9665d5e-b728/)
- [Changelog](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design) - see notes in mockup

## Tasks
- [x] Review the changelog and call out any questions that need clarification
- [x] Make the latest changes listed in the changelog to the app components for View Rep
- [x] Submit a PR for review

## Acceptance criteria
- [x] The app components on localhost now reflect the latest changes in the changelog for View Rep
- [x] A PR has been submitted for review
