### ISSUE TITLE
Migrate to hosted Sentry

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#1555]
## User Story
As a developer on VSP, I need to have sentry hosted so I can utilize the latest version to reduce maintenance burden on our teams.

## Goal
Migrate our current sentry solution to a hosted one because the “on-premise” solution (the one we use), is treated a bit like a 2nd class citizen by the Sentry development team and is not as well documented. It’s not as well maintained and typically gets features added to it only after that feature has been added to the “hosted” solution

## Current Blocker
We need to get it covered in our ATO
Need a quote for the cost of the hosted solution

## Acceptance Criteria
- [ ] ATO is acquired 
- [ ] Outlining Pros/Cons (or SWAT) completed (#1617)
- [ ] Migration Plan to for data (all or a portion)
- [ ] DevOps changed needed are complete
- [ ] Account is created and live

**Comment by johnpaulashenfelter** [comment]
Closing since we are starting to treat our self-hosted sentry as a first class citizen as part of the v10 upgrade #6769
