### ISSUE TITLE
Initial Redux Code for API Calls for View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15551]
## Goal
We use Redux to manage the state of our apps across VA.gov and since the View Representative will use data from any of various sources we need to build out the redux code to support that. This initial build of the Redux code does not have to use live data if none is available yet, we can hard code mock data for the time being if needed.

## Considerations
- This may be dummy data for now
- Backend integration will probably be through Lighthouse; need some investigating to determine **BGS** vs **EVSS** vs **LH**
  - LH may eventually do the heavy lifting on switching

## Tasks
- [ ] Set up Action(s) file for View Representative
- [ ] Set up Reducer(s) file for View Representative
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] View Representative now uses Redux to mange state
- [ ] A PR has been submitted for review
