### ISSUE TITLE
IAM SSOe Staging Configuration

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#15563]
## Description
The VA Mobile app authenticates users via IAM's SSOe OAuth service. We've completed dev environment testing with IAM and they've promoted us to staging. The next step is to install their SQA SSL key/cert in vets-api server and if necessary the forward proxy. This would have a similar configuration to the dev SSL key/cert.

## Background/context/resources
During a discovery sprint the IAM dev cert (INT) was accidentally installed in staging rather than dev, resulting in much confusion! 😄 The SQA cert should replace that one in staging while leaving the vets-api dev -> IAM INT config in place.

Our contacts on the IAM team are Perry Vessels <Perry.Vessels@va.gov> and Prashant Mukadam <Prashant.Mukadam@va.gov>

### Priority
In terms of priority it's not an emergency but we'd like to get to staging ASAP as vets-api dev uses MPI staging mock data and we can't do integration tests (beyond logging in) with IAM there.

## Technical notes
The vets-api rails app loads an environmental settings file and it should be updated with the new information
```yaml
iam_ssoe:
  client_cert_path: ...
  client_key_path: ...
  client_id: ...
  oauth_url: "https://sqa.fed.eauth.va.gov:444"
``` 

---
## Tasks
- [ ] Provide the IAM team with instructions on how to send over their SQA key/cert
- [ ] Install the SQA key/cert in staging
- [ ] Update the vets-api staging env settings file with the staging information

## Definition of Done
- [ ] Confirm we can curl "https://sqa.fed.eauth.va.gov:444/oauthe/sps/oauth/oauth20/introspect" from a vets-api staging instance.
- [ ] Update [this document](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/SSOe%20OAuth%20Services.md) with testing and configuration information

**Comment by kreek** [comment]
@jhouse-solvd has this work kicked off yet? The first task is to provide the IAM team with instructions on how to send over their SSL key and that might take some time 😄

**Comment by jjulian** [comment]
As mentioned in the description, we'd like to get this process kicked off ASAP since communications with the IAM team can take some time. Who will be assigned this work?

**Comment by jhouse-solvd** [comment]
@kreek  & @jjulian  - Let me talk with the Ops to get an update. The ticket has not yet been assigned. I'll see if we can get started with the first step and find any supporting documentation / process that may exist.

**Comment by jhouse-solvd** [comment]
The operations team is currently working with @kreek for testing this and better understanding what might still be needed. Will update with next steps as soon as possible and / or potential resolution as soon as possible.

**Comment by jhouse-solvd** [comment]
Recent testing from Alastair show this to be working ie "got a valid oauth session response back". 

Before we close this ticket, we want to consolidate relevant steps so that this can be done smoother/faster/more self-service when deploying to prod (possibly before the holidays, per @jjulian)

@tskinn and/or @jbritt1  - Can you add any necessary configuration needed from the Operations team in the comments below? Also, any useful testing that can be done from our team ie "curl -X -foo https://bar.gov" along with expected output? 

@kreek - Can you also add any necessary configuration changes that were necessary - if any - from the application side? Also, any super useful testing commands ie "curl -X -foo https://bar.gov" along with expected output?

**Comment by jbritt1** [comment]
Working on how to summarize all the steps taken so far in a more elegant way, but in the meantime wanted to attach some of the earlier PR's for the initial config(s):

https://github.com/department-of-veterans-affairs/devops/pull/7272
https://github.com/department-of-veterans-affairs/devops/pull/7338
https://github.com/department-of-veterans-affairs/devops/pull/7650

**Comment by jbritt1** [comment]
@tskinn's latest PR attached to this ticket also points out the [external service doc](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/SSOe%20OAuth%20Services.md) that former associate Ben Shyong and @jjulian have done a great job with updating relevant information on. Taylor's PR also adds some good `curl` tests to try once the certs are in place.
