### ISSUE TITLE
EKS Spike - Explore using EKS for hosting/deploying services and applications

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15560]
## Issue Description
_In order to find the best solution and combination of tools for deploying services and applications on VSP, the Operations Team is going to explore using Amazon EKS (Amazon's managed Kubernetes _

---
## Tasks
- [x] _Investigate the best combination of tools, scripts, and configuration of EKS_
- [x] _Experiment with deploying ops-owned services to EKS_
- [x] _Validate our assumptions that this is a good solution for Ops moving forward_

## Acceptance Criteria
- [x] _Ops will be able to make some architectural decisions for the best path forward _
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
This is done.
