### ISSUE TITLE
[Business Optimization] Create System Training Matrix to identify by System - what session and when training will be require that training [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15578]
## User Story or Problem Statement
As a Trainer and PAO, I need to understand what Training is needed and when, so I can better schedule the training and all subsequent activities before it becomes a blocker to those tasks.

## Goal
Align training with dual-state and go live

## Tasks
_Create a cross matrix to identify each system in the pipeline for training and when the estimated training will occur for the following systems:

**VISN-4**
- [ ] Altoona VA Medical Center
- [ ] DuBois VA Clinic
- [ ] Huntingdon County VA Clinic
- [ ] Indiana County VA Clinic
- [ ] Johnstown VA Clinic
- [ ] State College VA Clinic

**VISN-19**
- [ ]  VA Cheyenne health care
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado health care
- [ ]  VA Montana health care
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma City health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care

**VISN-6**
- [ ] VA Asheville health care
- [ ] VA Durham health care
- [ ] VA Fayetteville Coastal health care
- [ ] VA Hampton health care
- [ ] VA Richmond health care
- [ ] VA Salem health care
- [ ] VA Salisbury health care

**VISN-16**
- [ ] VA Alexandria health care
- [ ] VA Central Arkansas health care
- [ ] VA Fayetteville Arkansas health care
- [ ] VA Gulf Coast health care
- [ ] VA Houston health care
- [ ] VA Jackson health care
- [ ] VA Shreveport health care
- [ ] VA Southeast Louisiana health care

**VISN-21**
- [ ] VA Central California health care
- [ ] VA Northern California health care
- [ ] VA Pacific Islands health care
- [ ] VA Palo Alto health care
- [ ] VA San Francisco health care
- [ ] VA Sierra Nevada health care
- [ ] VA Southern Nevada health care

**VISN-23**
- [ ] VA Black Hills health care
- [ ] VA Central Iowa health care
- [ ] VA Fargo health care
- [ ] VA Iowa City health care
- [ ] VA Minneapolis health care
- [ ] VA Nebraska-Western Iowa health care
- [ ] VA Sioux Falls health care
- [ ] VA St Cloud health care

**VISN-2**
- [ ] VA Albany health care
- [ ] VA Finger Lakes health care
- [ ] VA Syracuse health care
- [ ] VA Western New York health care
- [ ] VA Bronx health care
- [ ] VA Hudson Valley health care
- [ ] VA New Jersey health care
- [ ] VA New York Harbor health care
- [ ] VA Northport health care

## Acceptance Criteria
* Cross matrix is created showing systems verses training sessions.
* All systems are represented and training is noted with estimated dates
* Dependencies are listed 
* Blockers to if any of the training is not complete
