### ISSUE TITLE
[Review-Cleanup] Take second pass review at all Wilmington VA System pages to validate MVP and consistency [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15577]
## User Story or Problem Statement
As a Veteran MC Website user, I must have a consistent theme across all of the pages that makes sense, relate to the system and provide direction for my journey, so I can quickly find the solutions and tools to support my health care journey.

## Goal
Does this content/field/data in this page make sense?
Does the content/field/data in this page relate to this facility or system?
Is it in the right place based on facility/system?
How does this help with the focus of the page?

## Resources - Tools - Documentation
[VA Wilmington Review list](https://drive.google.com/drive/folders/1Juw7qXdDtzXHm-yPPwaJNUaYZkCFD9B-)
[Drupal Production](prod.cms.va.gov)

## Tasks
_Complete review of system and facility pages for the following content and flow, asking these questions:
- [ ] Does this content/field/data in this page make sense?
- [ ] Does the content/field/data in this page relate to this facility or system?
- [ ] Is it in the right place based on facility/system?
- [ ] How does this help with the focus of the page?

**Confirm all of the facilities are reviewed**
- [ ] Wilmington VA Medical Center
- [ ] Atlantic County VA Clinic
- [ ] Cape May County VA Clinic
- [ ] Cumberland County VA Clinic
- [ ] Kent County VA Clinic
- [ ] Sussex County VA Clinic
- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All node/pages have been reviewed in Spreadsheet and issues found have been been documented.
* Issues have been escalated for resolution (Using spreadsheet)
* If issue was easily fixed, Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
