### ISSUE TITLE
[BA] Validate Health Services from legacy site by cross checking with Facility Locator [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15570]
## User Story
As a PAO and Web User, I need up to date and concise health services listed that reflect the latest version of services rendered at the Medical System facilities, so I quickly and accurately validate the health services in the VA.CMS system.  

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[VISN 6 Playbooks](

## TASKS: See below list of Stories
- [ ] VA Asheville health care
- [ ] VA Durham health care
- [ ] VA Fayetteville Coastal health care
- [ ] VA Hampton health care
- [ ] VA Richmond health care
- [ ] VA Salem health care
- [ ] VA Salisbury health care

## Acceptance Criteria:
- [ ] Validated Health Services are the most accurate by determining if they match what Facility Locator is presenting.
- [ ] Validated PLAYBOOK of Health Services Content by looking it up on facility locator.
- [ ]
