### ISSUE TITLE
Update pact documentation with changes for broker location 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#15581]
## Issue Description
Update documentation with changes for the new location of the broker. Remove heroku based information and replace with information on for AWS related details 

---
## Tasks
- [ ] Update all urls pointing to heroku
- [ ] Include information on why it was moved? (maybe)
- [ ] Remove heroku based information

**Comment by meganhkelley** [comment]
Hopping onto this ticket with y'all
