### ISSUE TITLE
Update pact helper broker url based on new location in AWS infra

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#15580]
## Issue Description
Update the broker base url in the pact helper based on the new url for the broker inside our AWS infra. This task is blocked until [this revproxy change](https://github.com/department-of-veterans-affairs/devops/pull/7867/files) is merged

---
## Tasks
- [ ] Have Eugene push a pact to the broker with the tag of 'master' (everything below is blocked)
- [ ] Update broker base url to new url
- [ ] Test that the rake task verification can successfully pull down the pacts
- [ ] Verify that basic auth functions properly

**Comment by LindseySaari** [comment]
Pointed the pact_uri to the search pact and it was able to successfully verify the results. No pacts exist with the tag of 'master' currently, so running the rake verification task can't be tested until at least one pact is tagged.
