### ISSUE TITLE
Update the pact broker webhook

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#15582]
## Issue Description
Update the pact broker webhook for contract changed events based on the new broker location inside of our AWS infrastructure. This task is blocked until [this revproxy change](https://github.com/department-of-veterans-affairs/devops/pull/7867/files) is merged

---
## Tasks
- [ ] Update the broker base url to point to the new AWS url 
- [ ] Verify that the webhook can be triggered (use the HAL/API browser)
- [ ] Verify that once triggered, CircleCI can publish results back to the broker 
- [ ] Verify that basic auth functions properly

**Comment by LindseySaari** [comment]
[Pact Broker webhooks can be created using the CLI](https://github.com/pact-foundation/pact_broker-client/#create-webhook) The webhook should just check for contract_content_changed.

pact-broker create-webhook https://circleci.com/api/v2/project/github/department-of-veterans-affairs/vets-api/pipeline -u 54d3ae7211a8ffbe342f681b25203d65fb917eaa: -X POST --header "Content-Type: application/json" -b https://vagov-pact-broker.herokuapp.com/ --broker-username=pact-broker -p GLs#La4oTCyw2ALT --contract-content-changed -d '{ "parameters": { "verify_stable_pacts": true, "consumer_name":  "${pactbroker.consumerName}", "consumer_version_tags":  "${pactbroker.consumerVersionTags}", "consumer_version_number":  "${pactbroker.consumerVersionNumber}" } }'

#### To trigger against a specific branch:
pact-broker create-webhook https://circleci.com/api/v2/project/github/department-of-veterans-affairs/vets-api/pipeline -u <personal_circle_ci_api_token_here>: -X POST --header "Content-Type: application/json" -b <pact_broker_url_goes_here> --broker-username=<pact_broker_username_here> -p <pact_broker_password_here> --contract-content-changed -d '{ "branch": "my-branch", "parameters": { "verify_stable_pacts": true, "consumer_name":  "${pactbroker.consumerName}", "consumer_version_tags":  "${pactbroker.consumerVersionTags}", "consumer_version_number":  "${pactbroker.consumerVersionNumber}" } }'

**Comment by LindseySaari** [comment]
The CLI isn't cooperating very well with the new broker location and certificates. Webhooks need to be created using the curl command via ssm. (I ssm'd into a vets-api instance -- there's an issue with the TIC if you curl locally, so the webhooks need to be created from within the VPC)

`curl -u pact-broker:GLs#PASSWORD_GOES_HERE --header "Content-Type: application/json" \
--request POST \
--data '{ "request": { "method": "POST", "url": "https://circleci.com/api/v2/project/github/department-of-veterans-affairs/vets-api/pipeline", "headers": { "Content-Type": "application/json", "Circle-Token": "CIRCLE_PERSONAL_API_TOKEN_GOES_HERE" }, "body": { "parameters": { "verify_stable_pacts": true, "consumer_name": "${pactbroker.consumerName}", "consumer_version_tags": "${pactbroker.consumerVersionTags}", "consumer_version_number": "${pactbroker.consumerVersionNumber}" } }, "username": "pact-broker", "password": "PASSWORD_GOES_HERE" }, "events": [{ "name": "contract_content_changed" }] }' \
https://dev.va.gov/_vfs/pact-broker/webhooks`


Triggering the webhook is throwing an error with SSL certificates but the above command successfully creates a webhook.

**Comment by LindseySaari** [comment]
When triggering the webhook, an error is currently shown: "certificate verify failed (self signed certificate in certificate chain)\n INFO: Webhook execution failed\n"

Look into a solution [here](https://github.com/pact-foundation/pact_broker/issues/149) as a possible workaround
