### ISSUE TITLE
[Repo migration]: Move/Audit Product Support content to va.gov-team

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1560]
Audit/move product support content on va.gov-vfs-teams and vets.gov-team to va.gov-team

AC: 
- [ ] Create a list of all the content - @accbjt. @mnorthuis might have an excel template - 5
- [ ] Audit that list of content for what needs to move/what can stay and never move - 3
- [ ] Decide where it's moved to -- meeting with Mikki/Matt? - 3
- [ ] Move content - 2

**Comment by mnorthuis** [comment]
Template to use while auditing/documenting files.  For any files in va.gov-vfs-teams that are not planned to be moved/copied into va.gov-teams, we will need to determine their fate, as that repo will be archived/deprecated. 

[Repo Content Audit.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3580207/Repo.Content.Audit.xlsx)

cc: @thatmattjohnson
