### ISSUE TITLE
Contact Center Response Template Review

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#15616]
## Issue Description
_To understand what reoccurring issues we can assist veterans and VA.gov users with._

---
## Tasks
- [ ] _Review the current response template that is used when answering IRIS and SalesForce issues._
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/va.gov-technical-issue-template-responses.docx

## Acceptance Criteria
- [ ] _As a result of this review, responses can be used when responding to issues and even updated as time progresses._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Ticket can be closed.  Ervin Pearson was able to review.
