### ISSUE TITLE
Finalize Checklist template FE - mobile and desktop - learning center 1.1

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15617]
## Finalize Checklist template FE - mobile and desktop - learning center 1.1

This is a follow on from the pre-work we already finished during 1.0: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13497

**AC:**
- [x]  Remove `<hr class="vads-u-margin-top--0">` in template
- [x] Remove the hard coded “Checklist” header in FE   
- [x] Include in FE the checklist section intro text field  (more info/screen shot in ticket #15915)
- [x]  Fix double line - [screenshot here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15617#issuecomment-719010756)
- [x] Remove buttons from printing logic + show checkbox checks on print 

- [x] The FE is accessibility compliant
- [x] The FE works as mobile responsive view
(https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15617#issuecomment-719044334).
- [x] Various checks in ticket  #16240 are done
- [x]  Design implementation is validated by @rtwell 
- [ ] Functionality validated by @jenniferlee-dsva 
- [x] Transformer updated  `Not sure if transformer should be ticketed separately, but including this here, since going forward all the things will need a transformer step at least as a checked item.`

### Additional info:

**Test node with Checklist content: http://preview-staging.vfs.va.gov/preview?nodeId=6924**

**Design:Ryan's mobile view mockup:** 
https://user-images.githubusercontent.com/12564977/99587085-94abb600-29b6-11eb-9d55-69347aaecb39.png

**Comment by jenniferlee-dsva** [comment]
I checked some boxes and then tried printing - it works great! The only funny thing I noticed is there is a double gray line at the bottom. 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/3e36d6db-6b46-466f-9b4d-3fa7263f816b)

**Comment by ncksllvn** [comment]
Awesome! We could also enhance the print layout a little by hiding the buttons for the print view. It's just a standard CSS thing that isn't used often.

**Comment by jenniferlee-dsva** [comment]
^ love that idea Nick. 

One thing I'm noticing is that there's a double gray line at the bottom of the article after the buttons. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/d1cfa34e-1aca-4236-ae48-abefc85feb34)

**Comment by jenniferlee-dsva** [comment]
In addition to the above double gray line, I think there is a [different FE bug wrt not pulling a content field. I put that in another ticket - #15915 for reference.](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15915)

**Comment by jenniferlee-dsva** [comment]
I posted this clarification in Liz's mobile design ticket. Just reposting here for everyone to be on the same page wrt ticket #15915 ^ FE not pulling the right optional checklist section header field and the need to display those as H2s when used: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/13037#issuecomment-728975625

**Comment by jenniferlee-dsva** [comment]
Updated OG ticket and linked to Ryan's final mobile mockup design.

**Comment by kelsonic** [comment]
Tasks:

1. Remove `<hr class="vads-u-margin-top--0">` in template
2. Remove "Checklist" hard-coded header
3. Add checklist section intro text
4. Remove buttons from printing logic + show checkbox checks on print

**Comment by jenniferlee-dsva** [comment]
Updated AC with Kelsons's comments above.

**Comment by brianalloyd** [comment]
Thanks @kelsonic and @jenniferlee-dsva.

**Comment by kelsonic** [comment]
Pull request opened ^ https://github.com/department-of-veterans-affairs/vets-website/pull/15482

This is how the checklist currently looks when printing. Are we sure we want to remove the buttons from it? Are there any other printing modifications we want to make to checklist?

[test registry exam checklist _ Veterans Affairs.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5748480/test.registry.exam.checklist._.Veterans.Affairs.pdf)

This is for http://preview-staging.vfs.va.gov/preview?nodeId=9544

**Comment by brianalloyd** [comment]
Thanks @kelsonic will this deploy during today's release?  Just following up on priority tickets, thanks.

**Comment by kelsonic** [comment]
@brianalloyd there's random e2e tests that keep failing on master so I'm not sure, I hope so!

**Comment by brianalloyd** [comment]
@jenniferlee-dsva and @rtwell all action items are complete on the ticket and are awaiting your review and validation in support of closing out this ticket.

**Comment by jenniferlee-dsva** [comment]
Taking a look...  per og ticket and Kelson's comment above here:

 http://preview-staging.vfs.va.gov/preview?nodeId=6924

http://preview-staging.vfs.va.gov/preview?nodeId=9544

**Comment by jenniferlee-dsva** [comment]
@kelsonic @brianalloyd - The FE web page looks great! No changes there. 

The PDF saved checklist - I have a couple of comments, mainly to do with: 
1/ Links displaying the raw https URL text. (Not sure if this is a 508 requirement.) 
2/ Empty checkboxes not being checkable on the PDF. (I didn't think to include this in the AC, but I think users will be surprised if the checkboxes aren't checkable on both web and PDF.) 
3/ Omit the search bar on the PDF checklist. 

I'm attaching the PDF here with detailed comments:
[https://app.zenhub.com/files/133843125/0b92c6c4-8a05-4fc7-96f9-ba7c8db17408/download](https://app.zenhub.com/files/133843125/0b92c6c4-8a05-4fc7-96f9-ba7c8db17408/download)

**Comment by brianalloyd** [comment]
Thanks @jenniferlee-dsva for the review and updated comments.  @kelsonic I'm going to spin up another ticket with the PDF/Print updates work for action.  If you have bandwidth feel free to jump on that ticket for action.

**Comment by rtwell** [comment]
lookin' great @kelsonic thanks for the hard work

1. question: is there any way we can align type that runs onto more than one line with the fist character? like this:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/0d09e902-d4db-43c2-ad88-243d1780580c)

2. should the checklist section lead with a h2? forgive me if this convo happened already!

3. idk if this looks like this outside of chrome, or if it's part of this ticket, but when i print the screen, all of the tags become full URLs—is this intentional? i can see arguments for either, just curious.

**Comment by kelsonic** [comment]
1. I can probably achieve that! It doesn't come by default with our design system but it would indeed look better.

2. It does actually 🙂 It just has the styling of an h3, should I remove that styling so it looks like an h2?

![image](https://user-images.githubusercontent.com/12773166/104336574-c8d0be00-54b1-11eb-89e8-a9f5f9605ac5.png)

3. Correct, if they didn't then you wouldn't know where those tags link to on paper so this is the default behavior of Chrome 🙂

**Comment by rtwell** [comment]
hmmmm in the comps we were working with, @jenniferlee-dsva and i had a static h2 called "Checklist" at the top and then we allowed a bunch of sections with h3s to help group the content. If we're not doing that, I'd be inclined to let them be plain ol' h2s unless that creates a problem with the On this page component. Or maybe @jenniferlee-dsva or the team made a decision I'm unaware of, and if that's the case, i'm totally ok with this.

**Comment by kelsonic** [comment]
The hardcoded h2 called Checklist at the top was omitted as requested by @jenniferlee-dsva I believe 🙂

**Comment by jenniferlee-dsva** [comment]
Couple things - GH doesn't have threading, lol.

Ryan -'s #2 question above - here is the mock https://user-images.githubusercontent.com/12564977/99587085-94abb600-29b6-11eb-9d55-69347aaecb39.png  -- all H2s (semantically)

RE Kelson's comment about the hardcoded "Checklist" h2 -- correct. We eliminated that hardcoded header.

**Comment by kelsonic** [comment]
PR is up for changing h3 styling to h2 for section headers and making sure the checkbox wrapping looks 💯 https://github.com/department-of-veterans-affairs/vets-website/pull/15618

**Comment by kelsonic** [comment]
PR merged! 🎉

**Comment by brianalloyd** [comment]
Awesome, thanks @kelsonic.

**Comment by brianalloyd** [comment]
@jenniferlee-dsva and @rtwell this is ready for validation, can you both take a look in support of close out.  Thanks.

**Comment by rtwell** [comment]
lgtm! nice work everyone

**Comment by jenniferlee-dsva** [comment]
Commenting only on the web views (since the PDF stuff was broken out into another ticket) - these look good to me as well. The mobile view still seems awfully smooshed up in the margins, but if we are addressing that as a global RS-wide ticket, we can close this ticket as completed. (We should revisit just to check the mobile squooshed margins though when ticket #17470  is ready.) 

![image](https://user-images.githubusercontent.com/43381063/105531789-d6f3bb00-5cb7-11eb-915b-b1539abb79ba.png)
