### ISSUE TITLE
VA.gov header and footer updates from Public Websites Team

### ISSUE THREAD

**Issue by mpeterz** [department-of-veterans-affairs/va.gov-team#15614]
### Content support:
Already worked with Public Websites content team on the text. Visual design mockup coming very soon.  

### Engineering support for:
- Making updates to code

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [ ] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * No.  
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * Mockup of updates to both the VA.gov header and footer: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1603977230451/f2be5be57cb4c9ef848586f1ffa821890e3f1544

---

## About your support needs
*Please select all that apply, and follow related guidance.*       

### Frontend engineering support 

- [ ] **New URL or redirect requests**   
- [ ] **Implementation of REACT sign-in widgets**   
- [ ] **Support for UAT testing or phased roll out of app/tool landing page**

- [ X ] **Other**
   *Updates to VA.gov header and footer. See https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1603977230451/f2be5be57cb4c9ef848586f1ffa821890e3f1544

New "Resources and support" landing page, formerly "Learning Center" URL: /resources
New contact us page URL: /contact-us

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* We'd like to time these updates with the launch of "Resources and Support" (Learning Center) (Nov 4?) and the new "Contact us" page (@DanielleThierryUSDSVA is in the loop). 
"Contact us" page ticket: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12986

---

### About your team

- Designer: *Meg Peters, Ryan Thurlwell*
- Content strategist: *Danielle Thierry*
- FE engineer: *Nick Sullivan or Kelson Adams?*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/97714595-bb518d80-1a97-11eb-91e7-e16c3d1c75ab.png)

**Comment by DanielleThierryUSDSVA** [comment]
Note: We'll be aiming to make these changes in the next week. We wanted to give R&S a little time live before pointing it to it from contact us page.

**Comment by mnorthuis** [comment]
@rtwell Can you provide mobile designs as well?

**Comment by rtwell** [comment]
I do not have bandwidth atm for mocking this up on mobile, nor am I sure if it's needed b/c the changes are all typographic. If it is needed @mpeterz please ping me and we can figure something out. This should not be a blocker as far as I'm concerned, but I could be missing something.

**Comment by mnorthuis** [comment]
Definitely not a blocker, just wasn't sure if you had them.  The groupings in the contact us footer area are a bit different than currently, so wasn't sure if that needed to be laid out.

**Comment by rtwell** [comment]
ah, i see what you're getting at @mnorthuis — we collapse the right-most column into a contact us accordion, and we drop the Crisis line info. i'm not sure how we want to handle these changes @mpeterz. Here's a visualization of what we do now, and what it would do with the changes. if it helps visualize the challenge:

![VA-footer-updates](https://user-images.githubusercontent.com/12564977/100896056-3a1d5a00-348c-11eb-9ec5-61133c1f3132.png)

**Comment by rtwell** [comment]
super side note slash nitpicky observation—do we need all the periods? not my domain, just curious.

**Comment by jenniferlee-dsva** [comment]
@mpeterz @DanielleThierryUSDSVA - just noticing that the first 3 columns use headers in the normal style (un-punctuated), but the final column use headers with periods. I don't care which way, but I do think header styling should be consistent.

**Comment by jenniferlee-dsva** [comment]
One more thing - sorry to only just now notice this: There is currently a column in the footer called "More resources." Is it weird to have a thing called "Resources and support" under "Get answers" instead of under "More resources"?

**Comment by DanielleThierryUSDSVA** [comment]
@jenniferlee-dsva Yeah, I think we can drop periods. Definitely should be consistent in style.

Speaking of consistency, it also looks like columns 1-3 are title case in the mockup. They should be sentence case, per existing footer. 

And the "c" in "crisis" in this one should be lowercase:

![image](https://user-images.githubusercontent.com/62957278/100920572-51b70b80-34a9-11eb-9554-10e37493504c.png)

For your other Q: It is a little weird. Maybe we change **More VA Resources** to something like **More VA links**?

**Comment by bethpottsVADEPO** [comment]
@kelsonic @ncksllvn I don't think you have a ticket yet for implementing these footer changes, do you? We'd like to move forward with this now. Let me know if you'd like to create this ticket or if I should.

**Comment by ncksllvn** [comment]
I think we had one but it was closed long, long ago

**Comment by jenniferlee-dsva** [comment]
@DanielleThierryUSDSVA - replying to your comment/question:

> For your other Q: It is a little weird. Maybe we change More VA Resources to something like More VA links?

Let's not change it because there is probably some history with VA WBC stakeholders as to how the links and the verbiage were selected during the 2018 inaugural va.gov launch.  Doesn't mean we can never change it, but should do it with a more holistic and broadly communicated initiative.

**Comment by jenniferlee-dsva** [comment]
My only other comment is that our style guide calls for "regional office," and specifically says don't use "benefit office."  

This isn't a style that originated with me, but it seems like a tremendous amount of negotiation with VASMEs went into it. I don't want us to start hurdy gurdy changing things up without strong rationales and updating and communicating with VA folks on a term that directly affects them. Since we rely on them to voluntarily follow our style guide, it's not a good look if we don't follow it ourselves, especially somewhere very visible like the global footer.

**Comment by DanielleThierryUSDSVA** [comment]
That's been my understanding around "regional office" vs. "benefit office" as well, @jenniferlee-dsva. I remember we all talked about this in one of our content/ia check-ins, and @mpeterz had a different perspective from recent taxonomy work. Meg, thoughts around this?
