### ISSUE TITLE
Contact Center Matrix Review

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#15612]
## Issue Description
_In order to successfully assist veterans and VA.gov users, becoming familiar with the issues that each contact center handles is a necessity._

---
## Tasks
- [ ] _Review the Excel sheet showing the mapping of issues of each Contact Center._

https://github.com/department-of-veterans-affairs/va.gov-team/files/4985379/VA.gov.Issue.Routing.Matrix.NCC.xlsx

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Ticket can be closed.  Ervin Pearson was able to review.
