### ISSUE TITLE
Review Routing of Issues 

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#15620]
## Issue Description
_In order to appropriately label and route issues accurately you must become familiar with topics, sub topics, and status._

---
## Tasks
- [ ] _Review the mapping of issues spreadsheet that has been created and make suggestions._

[https://app.zenhub.com/files/133843125/e6887770-2179-4f59-b6c5-e1690b918ab8/download](https://app.zenhub.com/files/133843125/e6887770-2179-4f59-b6c5-e1690b918ab8/download)

## Acceptance Criteria
- [ ] _More accurate mapping of issues should occur._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
