### ISSUE TITLE
Set up any Dockerhub pulls to use an authenticated user to make sure we are not rate limited

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#15623]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.

Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.

We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them.
## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Determine where we are pulling containers from DockerHub in CircleCI and Jenkins_
- [ ] _Use the vavfsbot user (password in credstash) to pull containers in CircleCI and in Jenkins_

## Definition of Done
- [ ] _Authentication is being used for all pulls of containrs from DockerHub_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
