### ISSUE TITLE
Can't reach review instances on vets.gov staging 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15634]
## Issue Description
_There are network or configuration issues that are resulting in development teams being unable to reach review instances for testing and verifying deployments. _

---
## Tasks
- [ ] _Debug network and or configuration issues and determine the cause of the issues that people are encountering with review instances_
- [ ] _Implement necessary fixes to restore access to review instances and/or provide alternate solution_

## Acceptance Criteria
- [ ] _Development teams will be able to access review instances (or other acceptable solution)_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tskinn** [comment]
@jbritt1 can correct me if I'm wrong but we couldn't connect to some review instances for two reason:
- review instances didn't have the proper IAM access to allow SSM sessions
- the process of copying github users public ssh keys to review instances was getting throttled or erroring and silently destroying the entire authorized_keys file basically so no one could access them.

We have removed the github user pub key copy role so that no longer exists and we have added the permissions for ssm to function properly.

**Comment by jbritt1** [comment]
What @tskinn has stated is correct / agreeable for backend connections. However, frontend is still broken due to caching issues we think.
