### ISSUE TITLE
Add "Search this area" button

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15631]
## Issue Description
Veterans need a way to trigger a search after zooming or panning the map. 

---
## Tasks
- [ ] Implement "Search this area on map" button consistent with [design specs]( https://drive.google.com/drive/folders/1cnxbzhwxVko9ezveZpoI-KpK2PIkEo8d?usp=sharing)

## Acceptance Criteria
- [ ] Button is not visible until Veteran has interacted with map
- [ ] When the Veteran has moved the map by zooming or panning, the "Search this area on map" button appears 
      - [ ] at the top of the map (desktop)
      - [ ] at the bottom of the map (mobile)
- [ ] "You are here" indicator moves to the center of the map
- [ ] Button is free-floating without magnifying glass icon
- [ ] Clicking the button triggers a new search using the center of the map. 
- [ ] When new search results are returned, they are consistent with the new parameters set by the Veteran's map interactions.
- [ ] Update button is not displayed unless Veteran interacts with the map 
- [ ] Search results subhead updates with new center of the map location (nearest City, State, postal code, place)
- [ ] Search results mileage updates calculated from new center of the map location
- [ ] Location input field in search box updates to reflect the new center (which is presented in the subhead)
- [ ] Tests are updated

---
## How to configure this issue

- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
