### ISSUE TITLE
Update search results 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15662]
## Issue Description
Veterans need to understand the results of the search after zooming or panning the map. This issue is to update the search result headings after a new search has been triggered. 

## Tasks
- [ ] Implement updated subhead consistent with design specs
[Facilities.Map.Update.Issue.-.Desktop.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5475710/Facilities.Map.Update.Issue.-.Desktop.pdf)
[Facilities.Map.Update.Issue.-.Mobile.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5475704/Facilities.Map.Update.Issue.-.Mobile.pdf)

## Acceptance Criteria
- [ ] Search results subhead updates with new center of the map location
- [ ] Search results mileage updates calculated from new center of the map location 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
The acceptance Criteria from this issue has been moved into [#15631](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15631)
