### ISSUE TITLE
Date/Timezone field transformer

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15666]
## Issue Description
Pages with Events, Situation Updates, and banners will be impacted by the addition of a new timezone field so the CMS export will have drifted 

## Example urls from Pittsburgh
[Events](https://www.va.gov/pittsburgh-health-care/events/)
[Situation Update](https://www.va.gov/pittsburgh-health-care/operating-status/)
[Outreach Hub events](https://www.va.gov/outreach-and-events/events/)

## Data for testing 
Found in this [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14578#issuecomment-714552358)

---
## Tasks
- [x] Create transformer

## Acceptance Criteria
- [x] No diffs in date/time format are found after running `yarn cms:compare` and `yarn cms:diff` on the following pages:
- pittsburgh-health-care/events/index.html
- pittsburgh-health-care/operating-status/index.html
- outreach-and-events/events/tele-townhall-live-in-california-with-under-secretary-for-benefits-0/index.html

---
Time displays Tuesday, Nov 17, 10:00 a.m. –Wednesday, Nov 18, 3:00 p.m. ET for [MCEC Education Summit 2020](https://www.va.gov/outreach-and-events/events/mcec-education-summit-2020/) and all other content maintained
<details> 

<summary> Screenshot from Prod </summary>

![image](https://user-images.githubusercontent.com/55411834/97897715-1e3f6080-1cf4-11eb-98c5-46328b23be30.png)

</details>

---
Time displays as 2:00 p.m. – 2:45 p.m. PT for this [Tele-townhall event](https://www.va.gov/outreach-and-events/events/tele-townhall-live-in-california-with-under-secretary-for-benefits-0/) and all other content maintained (note: this is a past event)
<details> 

<summary> Screenshot from Prod </summary>

![image](https://user-images.githubusercontent.com/55411834/97897433-b2f58e80-1cf3-11eb-8bfa-76d132617f77.png)

</details>

---
Time displays Tuesday, Mar 17, 1:09 a.m. ET for [situation update](https://www.va.gov/pittsburgh-health-care/operating-status/) (scroll to bottom for March update) and all other content maintained

<details> 

<summary> Screenshot from Prod </summary>

![image](https://user-images.githubusercontent.com/55411834/97902848-64e48900-1cfb-11eb-8a44-9613347f2be4.png)

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
News Releases removed from the scope of this issue as they use only a date (no time displayed)

**Comment by mpelzsherman** [comment]
Here's an example of the diff we need to eliminate:

`yarn diff outreach-and-events/events/tele-townhall-live-in-california-with-under-secretary-for-benefits-0/index.html`

<img width="1385" alt="Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_AppleUser_and_AppleClockExtra_and_Item-0_and_UAMenu_and_DisplaysExtra_and_AppleTimeMachineExtra_and_AppleBluetoothExtra_and_Item-0_and_AirPor" src="https://user-images.githubusercontent.com/80267/98622796-53414980-22d8-11eb-9803-b1b567c18867.png">

**Comment by mpelzsherman** [comment]
I missed one of the transformers needed for this, and also a template change was required.
