### ISSUE TITLE
Resources and support home page H1 and intro text

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#15660]
## Issue Description
User story: As a Veteran, if I land on the R&S homepage, I want to understand what this new part of the site is for and what kind of help or resources I will find here.

**Note:** @jenniferlee-dsva Danielle and I put our heads together on this, and would be happy to talk it through if you'd like.

---
## Tasks
- [x] Suggested H1 text: **Resources and support**
Would recommend shortening what's there now and getting rid of "your benefits and services" since this part of the site will have broader help content (account, sign in) as well as information for audiences other than Veterans (counselors, fiduciaries, etc.).
- [x] Suggested intro:
Explore our resources and support information. You’ll find FAQs about VA benefits and services, step-by-step instructions for using VA.gov tools, and other helpful articles.

The thinking on the intro: I'd like to use the intro to set expectations for what this part of the site is all about. So I wanted to work in the words "FAQs, step-by-step instructions, and articles." After we populate R&S with more types of content, we can rework this intro if we want to call out things like images or videos. But for now, this is what we have, and it really tells people what type of content to expect here.

## Acceptance Criteria
- [ ] Home page has H1 and intro to ground users who arrive in this part of the site.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
I love it. Ty. 

Could we also include a sentence that links ppl to the coronavirus FAQs? (At some point, we can replace the beta alert with a coronavirus alert, but since the beta alert will be there through 1.1.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you swap this content in for what's currently on the home page for H1 and intro?

**Comment by RLHecht** [comment]
@bethpottsVADEPO I reviewed your changes on the landing page and all looks good.

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO @RLHecht Here's a sentence to add for coronavirus FAQs. Thanks!

If you have questions about how COVID-19 may affect your VA benefits and services, read our [coronavirus FAQs](/coronavirus-veteran-frequently-asked-questions/).

**Comment by bethpottsVADEPO** [comment]
Closing this.
