### ISSUE TITLE
Team Observations + Exploration Notes - Part 1

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#15668]
## Description
Search and Discovery team will conduct their own analysis of the search experience on VA.gov, collecting thoughts and questions about the overall experience. Team will be looking for general observations, overall areas for improvement and potential enhancement ideas that should be considered as we define discovery questions and work to frame search problems that veterans are facing in current experience. 

## Tasks
- [x] John will add some previous analytics information and research that he conducted for the team to review and build on.
- [x] Each member of Search & Discovery team to explore va.gov search experience, capture observations and add findings to [observation document](https://docs.google.com/document/d/16cRM_LuECWCB5MdFr3ZzbsHISAtfHI21fjkLMXlphVE/edit#heading=h.rvveyh613jj2) for consolidation

## Definition of Done
- [x] Time-box to one sprint to collect baseline information that will be informed by user research
- [ ] Complete after each team member has submitted observations to be merged with user research results_
- [x] As a team review and discuss our findings and expectations for a good search experience. This discussion will result in clearly defined set of preferred [VA.gov search experience standards and benchmarks](https://docs.google.com/document/d/1shrOUq_Um5-ri_wAqSXmKTLWoMA3qFuBocDTtlUSo2M/edit).

**Comment by johnhashva** [comment]
**Observational audit of VA.gov Search and Type Ahead feature** - Attaching document here.  Summary:  A light-weight audit of both Search.gov Search Results and Type-Ahead suggestions for VA.gov top search terms and verbs.   The findings: Type-ahead results were not as expected and Search.gov agrees that there **IS** an issue that requires a re-look at the logic.   The general search results are also do not appear optimal -- though more deep dive research is required to quantify this (e.g. click-track data, etc.)

**_Light Audit of VA.gov Search Results + Type Ahead feature (on staging)_**
[Search.gov_Type-ahead_Issues.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5476696/Search.gov_Type-ahead_Issues.docx)

**_Top VA.gov Keywords (Sept 2018-May 2020)_**
[VA.gov Queries Sep 2018 - May 2020.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5476754/VA.gov.Queries.Sep.2018.-.May.2020.xlsx)

**Comment by denisecoveyduc** [comment]
@srsuddath @mgleo - how are you feeling about our observations of va.gov.  I feel there is a good summary on our doc but we should likely discuss the output. I suggest we close this one out and discuss in our next working session. Agree?

**Comment by mgleo** [comment]
Agree

**Comment by srsuddath** [comment]
agree!
