### ISSUE TITLE
[Discovery] Reverse geocoding

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15673]
## Issue Description
We'll need to leverage reverse geocoding through Mapbox to get the location information needed to update the subhead and search result mileage following a new search. This issue to research available options and understand what is possible

Here’s a sample reverse geocode query:
https://api.mapbox.com/geocoding/v5/mapbox.places/-73.989,40.733.json?access_token=pk.eyJ1IjoiYWRob2MiLCJhIjoiY2l2Y3VlNWp5MDBoNjJvbHZ2a3R4bnN2cyJ9.2LoUhwRmz2OiCtRirnc6Pw

Same query limited to “place” type:
https://api.mapbox.com/geocoding/v5/mapbox.places/-73.989,40.733.json?types=place&access_token=pk.eyJ1IjoiYWRob2MiLCJhIjoiY2l2Y3VlNWp5MDBoNjJvbHZ2a3R4bnN2cyJ9.2LoUhwRmz2OiCtRirnc6Pw

If you change the lat/lng slightly, we get back an empty result:
https://api.mapbox.com/geocoding/v5/mapbox.places/-72.989,40.733.json?types=place&access_token=pk.eyJ1IjoiYWRob2MiLCJhIjoiY2l2Y3VlNWp5MDBoNjJvbHZ2a3R4bnN2cyJ9.2LoUhwRmz2OiCtRirnc6Pw

Adding more place types gives some results, but deciding which place type to show in the UI may be difficult to automate.
https://api.mapbox.com/geocoding/v5/mapbox.places/-79.989,40.733.json?%20types=region,%C2%A0postcode,%C2%A0district,%C2%A0place,%C2%A0locality,%C2%A0neighborhood&access_token=pk.eyJ1IjoiYWRob2MiLCJhIjoiY2l2Y3VlNWp5MDBoNjJvbHZ2a3R4bnN2cyJ9.2LoUhwRmz2OiCtRirnc6Pw

---
## Tasks
- [ ] Research reverse geocoding options 
- [ ] Determine performance impact of this addition, if any

## Acceptance Criteria
- [ ] Acceptance criteria for [#15631](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15631) is approved or refined
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
