### ISSUE TITLE
[PM] Platform post-launch review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15683]
## Background

[Outline of post-launch review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#post-launch-check-in)

## Tasks

- [x] Complete post-launch questions in [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)
- [x] Complete [VSA Initiative Impact Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/VA.gov%20Impact%20Review_Profile2.0.pdf)
- [x] Schedule the meeting (Thursday, Nov 12 @ 2:00 ET)
- [ ] Hold meeting

**Comment by Samara-Strauss** [comment]
Meeting is scheduled for 11/12 @ 2:00 ET.

**Comment by shiragoodman** [comment]
Thanks @Samara-Strauss ! I will schedule by EOD.

**Comment by Samara-Strauss** [comment]
Awesome, thanks!

**Comment by Samara-Strauss** [comment]
@shiragoodman since we don't need a meeting for this, can you let me know what next steps are? Wondering what else I might need to do at this point to move this forward.

**Comment by shiragoodman** [comment]
hi @Samara-Strauss  - no next steps. Your responses to the post launch questions look great. I don't have any additional feedback. The post launch is just for us to ensure DEPO project teams are measuring their KPIS and continually iterating. Looks like your team did a thorough retrospective and will take these lessons into your next project. Great work!

**Comment by Samara-Strauss** [comment]
Great! OK, I'll close this then. Thanks!
