### ISSUE TITLE
Usability Testing Prep: Authenticated Experience — Direct Deposit for EDU

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15686]
## Background

[Usability testing prep review overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#usability-testing-prep)

We're about ready to start preparing for Jim to conduct usability testing on his mockups, so that means we need to prep for the usability testing review. This ticket is for tracking all the prep for that review.

## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] Usability Testing Prep review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts

Gather the following materials

- [x] Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md)
- [x] Link to prototype or [mockups](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/) _(prototypes coming soon)_
- [x] Link to or attach artifact with copy
  - [Profile copy](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15518)
  - [Landing page content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14367)
- [x] Link to research materials
  - [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing/dd-edu-research-plan.md)
  - [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing) 
- [x] Link to [test cases/test plan in TestRail](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/qa-testing/Direct%20Deposit_Edu%20test%20cases.xlsx) (learn more) (even if just a draft) for QA practice area review
- [x] Provide these artifacts at least 2 days before the scheduled review meeting
- [x] Schedule the meeting

--

- **Tze said this was not required**: Link to regression test plan (learn more) (if there isn't already a regression test plan for this feature in TestRail) for QA practice area review

----

## Meeting attendees from **eBenefits & Authenticated Experience**
- Product Manager (required): **Jason Wolf & Matt Shea**
- DEPO product lead (required): **Steve Kovacs & Samara Strauss**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Jim Adams**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now: **Thursday, November 19, 2020 at 1:30 pm ET**
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira will reach out as needed_

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by mshea0606** [comment]
@Samara-Strauss Thanks for creating this!

**Comment by Samara-Strauss** [comment]
@jason-gcio @mshea0606 not sure who will handle scheduling this (feel free to coordinate with each other!), but we're probably good to get this on the books for some time next week. The sooner, the better, so that way we can kick off research recruiting ASAP. However, just make sure you also coordinate with Jim so that he feels comfortable with the date. Thanks!

**Comment by jason-gcio** [comment]
Yep, sounds good. I was going to chat with Jim and then move forward.

**Comment by jason-gcio** [comment]
Jim is getting me a link to the convo guide, then I will get it scheduled.

**Comment by pjhill** [comment]
Hey all, it looks like your link to test cases routes to an [empty folder in your product space](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/qa-testing/Direct%20Deposit_Edu%20test%20cases.xlsx).

Have you been able to create draft test scenarios or stubbed out test cases anywhere?

**Comment by Samara-Strauss** [comment]
@pjhill the only reason we used a spreadsheet for this is because the original direct deposit QA for the comp & pen feature happened prior to the team using TestRail. @tzelei said it was OK if I modified the old spreadsheet for the new direct deposit for edu test cases, and he said it was OK to submit the spreadsheet for the review. We know about TestRail and have used it for all our other QAs, and we'll get these test cases into Test Rail by the time QA needs to happen.

**Comment by tlei123** [comment]
@Samara-Strauss @pjhill , now worries...  i already have [TestRail test cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&group_id=402) in-place, just waiting for passwords right now.

And yes, this was a one-off situation with pre-Testrail process/documentation -- my first concern has always been to minimize added workloads on the Product Teams, and that old spreadsheet was definitely the way to go for quick-n-easy updates since the new DD-Edu's so similar to the existing DD-Comp&Pen.  Sorry, @pjhill for the apparent "time-warp!"  :D

FYI, thinking out loud right now, there's opportunities for better use-case development (as a process) which will further reduce PO/PM burden, among which a key item is delineating the difference between use case and test cases.  I'll keep you posted, but for now @Samara-Strauss know that you won't need to descend into exact test-case steps (e.g., negative test-steps for validating error-messages) which I'll flesh out in TestRail as one of my regular test-case process-steps.  Feel free to take a look at this [TutorialsPoint article](https://www.tutorialspoint.com/difference-between-use-case-and-test-case) for differences between use- & test-cases.

cc @mshea0606

**Comment by Samara-Strauss** [comment]
Closing this epic. Please let me know if it should remain open for any reason.
