### ISSUE TITLE
AE: Sprint 34

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15682]
## Priorities

1. Outstanding tickets from sprint 33
2. Update links to learning center in the profile 
3. My VA redesign: Research prep for initial dashboard direction; Start conducting sessions
4. Preferred facility: Technical discovery
5. Direct deposit: Prep for usability testing
6. Profile 2.0: Accessibility testing validation

### Profile

**PM**

- [x] Platform post-launch review #15683

**Design**

- [x] Complete final accessibility review tests #15706
- [ ] Look into error messaging/location #10722 (if time)

**FE**

- [x] Update links and text within Profile that currently go to sign-in FAQ #14998 (Do early in sprint)
- [x] Complete final accessibility review tests #15707
- [ ] Create comprehensive e2e tests for address validation #14987 (will be done by today 11/18)
- [x] Rename "vet360" references to "vapSvc" #6268

### My VA redesign

**Design**

- [x] Research plan #13925
- [x] Conversation guide #13926
- [ ] Conduct research #15684 (carrying over to the next sprint)

**FE**

- [x] Reduce Javascript bundle size #1969
- [ ] Improve My VA Dashboard Cypress tests #15740

### Direct deposit for edu

**PM**

- [x] Prepare for usability testing Platform review #15686

**Design**

For Jim Adams:

- [x] Research Plan for Usability Testing of EDU Direct Deposit #13807
- [x] Conversation Guide for Usability Testing of EDU Direct Deposit #13808

### Preferred medical facility

- [x] Technical discovery #15722

### Dev Ops

- [x] [DevOps] Change instances of "/person-mdm-cuf-person-hub/sba/health" to "/contact-information-hub/sba/health" in INT, QA, PRD environments #14480

### Unplanned: QA, 508, bugs, or other fixes

- [x] Remove `dashboard_show_covid19_alert` feature flag #15737
- [x] VA Profile issue: Determine why we are sending a high volume of calls to VA Profile for a single user #15810
- [x] Add state for if someone is eligible for only one type of direct deposit but not the other #15916
- [x] Add 2FA prompt for when someone is LOA3 but not 2FA and is eligible for direct deposit #15923 (maybe)
- [x] Profile should init a vet360 ID for users who lack it #16012
- [x] Profile 2.0: Change alertbox heading level prop value to 2 to address the heading order issue #15908
