### ISSUE TITLE
[Tech-debt] Review and cleanup-correct Menu - Section titles to assure they are enabled VISN-16 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15696]
## Story
As a Veteran web user, I have to be able to see the sections on the left nave menu, so I can better understand the sections and areas I want to go in my health care journey.

## Resource
[CMS Production](prod.cms.va.gov)

## Task
Review all system's menus to assure that the following Menu Sections (Services and Locations, News and Events, and About VA…) are enabled and have "nolink" in link field:
- [x] VA Alexandria health care
- [x] VA Central Arkansas health care
- [x] VA Fayetteville Arkansas health care
- [x] VA Gulf Coast health care
- [x] VA Houston health care
- [x] VA Jackson health care
- [x] VA Shreveport health care
- [x] VA Southeast Louisiana health care

## Acceptance Criteria
- [x] All system menu sections are enabled. 
- [x] All link fields show "nolink"
