### ISSUE TITLE
Remove check for old content type (Facility Health Services)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15690]
## Issue Description
The implementation of the new facility health services content structure included a check for content in the previous blobby model. Now that all new content uses the hardened structure, we can remove the "if" check. 

---
## Tasks
- [ ] Clean up unneeded "if" check for blobby health services contact info. 

## Acceptance Criteria
- [ ] Code checking for blobby health services contact info is no longer present
- [ ] No content is duplicated (using both old and new structure)
- [ ] Only new content structure is displayed on Prod
- [ ] Remove "Staging only" flag

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
