### ISSUE TITLE
Use fieldDatetimeRangeTimezone in production when present

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15691]
## Issue Description
The implementation of the [new date/timezone field](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14578) included an environment check to prevent the new field from being used in production. Now that all new content uses the new structure, we can remove the environment check. 

---
## Tasks
- [ ] Remove the code that was preventing the use of fieldDatetimeRangeTimezone in production when present.
- [ ] Retain the fallback code that uses fieldDateAndTime when fieldDatetimeRangeTimezone is null.

## Acceptance Criteria
- [ ] Pages that use fieldDatetimeRangeTimezone display the date with the correct time zone. This will need to be confirmed in production.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
