### ISSUE TITLE
[Tech-debt] Review and cleanup-correct Menu - Section titles to assure they are enabled VISN-2 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15694]
## Story
As a Veteran web user, I have to be able to see the sections on the left nave menu, so I can better understand the sections and areas I want to go in my health care journey.

## Resource
[CMS Production](prod.cms.va.gov)

## Task
Review all system's menus to assure that the following Menu Sections (Services and Locations, News and Events, and About VA…) are enabled and have "nolink" in link field:
- [x] VA Albany health care
- [x] VA Finger Lakes health care
- [x] VA Syracuse health care
- [x] VA Western New York health care
- [x] VA Bronx health care
- [x] VA Hudson Valley health care
- [x] VA New Jersey health care
- [x] VA New York Harbor health care
- [x] VA Northport health care

## Acceptance Criteria
- [x] All system menu sections are enabled. 
- [x] All link fields show "nolink"

**Comment by ltrombley** [comment]
Menu - Section titles to assure they are enabled VISN-2 [VAMC]#15694 - Complete
