### ISSUE TITLE
[Design] Profile 2.0: Complete final accessibility review tests

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15706]
## Background

As part of the final accessibility & 508 office review (#15247), we need to re-do some of the accessibility tests we did before launch:

 - [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
 - [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
- [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)

You can find the original results for these tests in #11279.

## Tasks

- [x] Complete the color test
- [x] Complete the content resize check
- [x] Complete the keyboard navigation check
- [ ] Create tickets if issues are found

**Comment by Samara-Strauss** [comment]
Update from @jenstrickland from #15707 

> The team doesn't need to share any results of their tests with me. They should just write issue tickets for anything found, and provide the list in the full audit request, and check all the checkboxes for the tests they complete.

**Comment by callen2563** [comment]
No issues found
