### ISSUE TITLE
[UI] Adding more appointment information in the Questionnaire workflow

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15718]
## User Story
- As a Veteran, I want to be able to access more information about my associated appointment throughout the questionnaire workflow, particularly before starting, once I've completed a questionnaire, and PDF.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A wireframe set depicting the additional appointment information will be delivered with the technical specifications needed for engineering to implement said feature.

Within the last [usability test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md), the following item was found,
Veterans want to view more appointment details when completing health questionnaires.
- 60% of participants suggested displaying more appointment information throughout the questionnaire workflows, specifically on the list of all questionnaires and confirmation page.
  - The most common requests were:
    - Appointment time
    - Provider’s name
    - Clinic name, address with room number, and/or hours

## Tasks
- [x] Revisit how VAOS handles this.
- [x] Brainstorm different design solutions
- [x] Present options to product team
- [ ] Finalize detailed mockup and callouts: https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780 or https://zpl.io/VOOek8j

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
Ideas currently viewable within the "Changes up for Discussion after Second Usability Test" on Zeplin:
https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780
or
https://zpl.io/VOOek8j
