### ISSUE TITLE
[BE] Preferred medical facility: Technical discovery

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15722]
## Background

We need to allow people to indicate their preferred medical facility in the VA.gov profile so that the VAOS tool can consume this information for a better user experience.

What we already know:

- We can get someone's full facility list through MPI. The VAOS team is already consuming this, so it'll probably be pretty easy or us to tap into this information as well.
- We do NOT need to sync someone's preferred facilities to their list of preferred facilities in MHV.
- We will NOT be sending someone's preferences back to MPI.

What we need to figure out:

- How can we store someone's preferred facilities in the profile?
- With our initial setup, is there anything we need to do to make sure that the VAOS tool can consume the info from the profile?

## Tasks

- [ ] Investigate current data available to us from MPI.
- [ ] Come up with a plan for how to save info in the profile (since the profile is not normally a system of record).
- [ ] Determine if there's anything special we need to do to make the info from the profile consumable by the VAOS tool — does it need to be structured in a certain way?
- [ ] Understand and define what needs to happen for the build phase so we can get that work documented.

**Comment by lihanli** [comment]
> How can we store someone's preferred facilities in the profile?

we can store the data in the backend database.

> With our initial setup, is there anything we need to do to make sure that the VAOS tool can consume the info from the profile?

we can create an api that will list a user's preferred facilities which the VAOS team can use.

**Comment by Samara-Strauss** [comment]
@lihanli I can go ahead and create a build ticket. Is this accurate?

- Set up preferred storage on the backend
- Create an API for the VAOS team to pull in preferred facility

Is there anything else you need to do since we can already retrieve people's facilities from MPI?

**Comment by lihanli** [comment]
also i need to create an api that lets users save their preferred facilities. once those 3 things are done then this feature should be complete on the backend.

**Comment by Samara-Strauss** [comment]
Great! @lihanli I will create a ticket for that work and close this out.

**Comment by Samara-Strauss** [comment]
Backend build is documented in #16107. Closing this!
