### ISSUE TITLE
Total combined disability rating

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#15726]
## User Story
As a user, I want to see my disability rating in my profile in the app.

## Tasks:
**Technical Discovery:**
- [ ]  Is there a way for us to get disability permanence & service-connected info?

- [ ] What API do we need to use for the disability rating? (Discuss with Jim Adams)

**UX Discovery**

- [ ] What do users want to see?

**Comment by ayushchak** [comment]
Duplicate ticket with more robust info: https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14759
