### ISSUE TITLE
[DATA-LOAD] Load data for "VISN-6 " - "TOP TASK" Detail Pages in CMS [Data Tech]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15732]
## User Story or Problem Statement
As a Veteran Web user, I want immediate access to my TOP Tasks, so I can quickly access services most important to me on my health care journey. 

## Goal
_Highlight TOP TASK pages with local and national information as required_

## Objectives or Key Results this is meant to further
- _Reduce Click through count by_Highlighting top tasks_

## Tasks
_Complete the following tasks for completion of this story:_
**All information, (i.e. Phone numbers, addresses, and contact information loaded in WYSIWYG/content block as required:
Move all Nationalized Content over from Legacy site to Top Task Page of the Same Name, if not already loaded**
**The following pages must be reviewed and complete for all Systems**
- [x] Make an Appointment
- [x] Register for Care
- [x] Billing-Insurance
- [x] Contact Us 
- [x] Medical records
- [x] Pharmacy
- [x] Policies
- [x]  Cross check is complete for work above.

VISN-6 Systems:

- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care

## Acceptance Criteria
All content and staff profiles must be loaded and visible for the following pages:
* Make an Appointment
* Register for Care
* Billing-Insurance
* Contact Us 
* Medical records
* Pharmacy
* CROSS CHECK is complete and cleaned up in Drupal

**Comment by ltrombley** [comment]
Task #15732 - Complete for VISN-6, all corrections made and updated.
