### ISSUE TITLE
[DATA-LOAD] Load data for "All systems in VISN-16" - "TOP TASK" Detail Pages in CMS [Data Tech]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#15734]
## User Story or Problem Statement
As a Veteran Web user, I want immediate access to my TOP Tasks, so I can quickly access services most important to me on my health care journey. 

## Goal
_Highlight TOP TASK pages with local and national information as required_

## Objectives or Key Results this is meant to further
- _Reduce Click through count by_Highlighting top tasks_

## Tasks
_Complete the following tasks for completion of this story:_
**All information, (i.e. Phone numbers, addresses, and contact information loaded in WYSIWYG/content block as required:**
**Move all Nationalized Content over from Legacy site to Top Task Page of the Same Name, if not already loaded**
*Complete the following pages for all of the systems listed below:
- [x] Make an Appointment
- [x] Register for Care
- [x] Billing-Insurance
- [x] Contact Us 
- [x] Medical records
- [x] Pharmacy
- [x] Policies
- [x]  Cross check is complete for work above.

VISN-16 systems:
- [x] VA Alexandria health care
- [x] VA Central Arkansas health care
- [x] VA Fayetteville Arkansas health care
- [x] VA Gulf Coast health care
- [x] VA Houston health care
- [x] VA Jackson health care
- [x] VA Shreveport health care
- [x] VA Southeast Louisiana health care

## Acceptance Criteria
All content and staff profiles must be loaded and visible for the following pages:
* Make an Appointment
* Register for Care
* Billing-Insurance
* Contact Us 
* Medical records
* Pharmacy
* CROSS CHECK is complete and cleaned up in Drupal

**Comment by EdwardBoehme05** [comment]
Cross checks completed and corrections made.
