### ISSUE TITLE
SSOe Screen Redirect Improvement Research

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#15749]
## Issue Description
- Screen flashing during redirects when logging into va.gov/sign-in for Cerner related uses has been determined to be a less than ideal user experience
- Screen readers may have issues reading content from sites during the redirect sign on process, this is an issue for accessibility
---
## Tasks
- [x] Document each redirect during the login process
- [x] Identify any possible courses of action that can be taken to improve the user experience (reduce the redirects and screen flashing as much as possible)
- [ ] Create issues for each COA to facilitate the closure of this research
## Acceptance Criteria
- [ ] All possible COAs will have an issue created for them to ensure they are independently followed through on
---
## How to configure this issue
- [ ] **Labeled with Team**
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joeniquette** [comment]
[Link to google doc notes](https://docs.google.com/document/d/1U8G8Uzs_aP8IXPXJ7fjdB9ewIctYQz-ei3X6FyLrO24/edit), once the doc is finalized all notes will be transferred to this ticket.

**Comment by joeniquette** [comment]
Notes: https://docs.google.com/document/d/1U8G8Uzs_aP8IXPXJ7fjdB9ewIctYQz-ei3X6FyLrO24/edit#heading=h.6pmzj8pbkrnx

Slides: https://docs.google.com/presentation/d/1Kj-XlZ5tOWM7TqA0AfWZO2cnRHiNTBbxSdY1KEUp-os/edit#slide=id.ga9b1011f84_0_37
