### ISSUE TITLE
Adjust the Max Char Limit (for Address)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15775]
## Background
One of the issues we are seeing that needs to be addressed is that some fields only allow a certain number, and not enough, characters to get passed through.  This can result in an error like this for **address line 1**: `insertBenefitClaim: AddressLine1 is greater than 20 characters`.  

## Goal
We need to truncate the line that says its too long and assign the remainder to the appendix or overflow section with a field label to ensure the complete entry is captured.

## Considerations
- Take the entry and count the number to 20 and truncate the entry (Write a helper method that checks line length and if over 20 chars, append to next line (address_line_2))
- Append the remainder of the address line to the next line `n` since there are are more than one address line (3). 
- Do not break words, like word wrap

## Tasks
- [x] Identify which fields need to be addressed
- [x] Take all lines and combine them
- [x] Keep words together
- [x] Truncate to lines 
- [x] Create a new test 

## Acceptance Criteria
- [x] The address field allows for the max number of characters
- [x] The rest of the data is visible in the payload and pdf
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5579
