### ISSUE TITLE
Change text and link on sign-in page and modal that currently goes to sign-in FAQ

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#15782]
## Issue Description
As part of the launch of Resources and support, the sign-in FAQ will be retired. We link to this FAQ from the sign-in modal and the sign-in page (https://www.va.gov/sign-in/). We need to change the text and link there to point to the new R&S pages for signing in to VA.gov and verifying your identity on VA.gov. The text is below.

**Note:** @ncksllvn We will roll this out either Friday or Monday. 

![Screen Shot 2020-11-04 at 7.41.58 AM.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/e54e5356-6460-4bb3-b32e-56ddc0fb6df5)

---
## Tasks
- [ ] Replace the link under "Having trouble signing in?": Get answers to frequently asked questions
With this: Get answers to common questions about [signing in](/resources/signing-in-to-va-gov/) and [verifying your identity](/resources/verifying-your-identity-on-va-gov/).
- [ ] Make this change in the modal and on the sign-in page.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@ncksllvn **Please hold off on going live with this until Monday** when search issues are all resolved. Thanks!

**Comment by bethpottsVADEPO** [comment]
@ncksllvn Can this change get merged today?

**Comment by bethpottsVADEPO** [comment]
@ncksllvn Can this go out today? @RLHecht for awarenesss

**Comment by ncksllvn** [comment]
I'm asking VSP for a review right now

**Comment by ncksllvn** [comment]
This was merged - and thanks to today's daily deployment failing, we will be probably see this deployed later on in a follow-up deployment lol.

**Comment by bethpottsVADEPO** [comment]
Thanks for the update, and sounds good!

**Comment by bethpottsVADEPO** [comment]
Closing, this work is done.
