### ISSUE TITLE
Establish the Procedure for Refreshing Users Ourselves

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15783]
## Goal
We can ask Christine to remove claims for our test users but it would be ideal if we could do this ourselves.  This might be an involved process and we want to make sure we do it right.

## Tasks
- [x] Establish time to talk to Liz
- [x] Talk to ~~Christine or Linda~~ Liz Rheeler bout the steps to produce these results ourselves

## Acceptance Criteria
- [x] Document the findings and/or procedures in GH

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/documentation/user-reset.md
