### ISSUE TITLE
Update vets-json-schema to Use New Pension Questions for the 686c

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#15788]
# Background
We need to import the schema from `vets-json-schema` and use that inside `vets-website instead of static properties.

## Tasks
- [x] Import the pension questions from `vets-json-schema` into `vets-website`
- [x] Submit PR to `vets-website` for review

## Acceptance criteria
- [x] `vets-website` is now using the pension questions from `vets-json-schema`
- [x] PR has been submitted for review
