### ISSUE TITLE
Create, Extend, and Document Cypress Automation Framework for Use on the Platform

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#15787]
## Problem Statement 
*VSP’s test automation framework implementation and documentation needs improvement, and as a result team participation in test automation is often perfunctory. How might we be able to improve what the framework provides in order to deliver more value to VFS teams and encourage greater adoption and participation?*

## Hypothesis or Bet
*By enhancing the test automation documentation and tooling and providing great examples of automation, the VSP team will encourage and develop a culture of scalable quality on the platform.*

## Goal
*To enhance the offering of our Test Automation Framework in order to provide more value to VFS teams.*

## Objectives
*O4: Get VFS teams to know, use, and love the DEPO Platform products and services.*

## We will know we're done when... ("Definition of Done")
- [ ] All documents have been peer reviewed and are organized into a relevant folder in GitHub
- [ ] A table of contents with a logical hierarchy is front and center in a README
- [ ] Tutorials with step-by-step guides, example code, copy & paste commands, and relevant images are collected into the TOC

## Known Blockers/Dependencies 
No known blockers/dependencies

## Projected Launch Date
12/10???

### Is this service / tool / feature...
Documentation in the form of --
1. Reference Documents
2. Tutorials
3. User Guides

### ... tested?
- [ ] For Documentation - Internal team peer reviews are conducted
  * - [ ] [#15832 - General Documentation for use of Cypress](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15832undefined)
  * - [ ] [#15836 - Document Cypress Best Practices on VSP](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15836undefined)
  * - [ ] [#15835 - Create Helper Functions for Cypress](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15835undefined) *Documentation Reviewed*
- [ ] For Helper Functions - Testing team members with different environments will use the tutorials and guides to implement recommended practices, custom commands, and plugin enhancements in their local environments.
  * - [ ] [#15835 - Create Helper Functions for Cypress](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15835undefined)

### ... documented?
- [ ] Documentation artifacts listed below are present
  * - [ ] [#15832 - General Documentation for use of Cypress](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15832undefined) - **_Provide documentation link here_**
  * - [ ] [#15836 - Document Cypress Best Practices on VSP](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15836undefined) - **_Provide documentation link here_**
  * - [ ] [#15835 - Create Helper Functions for Cypress](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15835undefined)  - **_Provide documentation link here_**

### ... measurable
- [ ] Measurement artifacts listed below are designed and available

### Documentation
1. VSP Best Practices
   1. custom commands
      1. axeCheck
      1. expandAccordions
      1. login
      1. syncFixtures
      1. upload
   1. View ports
   1. Selector best practice (data-cy vs. data-testid)
   1. Collect and organize existing Cypress docs
1. Cypress Best Practices
   1. Resilient tests
   1. Working with text
   1. Penetration testing forms
   1. Collect and organize relevant Cypress videos
   1. Parse and recommend techniques from Cypress Real World App
1. Custom commands
   1. User guides
   1. Tutorials based on example app
1. Plugin installation
   1. User guides
   1. Tutorials based on example app

### Testing
Feedback and issues to be recorded in comment history for PRs of the documentation in va.gov-team.

### Measurement
1. Survey VFS teams regarding the discoverability of information related to Cypress on the platform.
1. Measure number of support requests regarding Cypress.

## TODOs
- [x] Create epics underneath and detail with Launch Checklist & Required Artifacts
