### ISSUE TITLE
Spool submissions report and YTD report are not showing the expected submissions

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15795]
## Issue Description
_Spool submissions report and YTD report are not showing the expected submissions. Could someone verify the app/workers/education_form/create_daily_spool_files.rb job is running on stagin? 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ericboehs** [comment]
- This job was disabled on [staging's sidekiq recurring-jobs](https://staging-api.va.gov/sidekiq/recurring-jobs) page. I enabled it.
- When enqueued, job failed with `Net::SSH::Disconnect: connection closed by remote host`. See Sentry error [1](http://sentry.vfs.va.gov/organizations/vsp/issues/4992/?environment=staging&project=3&query=SSH&statsPeriod=14d) and [2](http://sentry.vfs.va.gov/organizations/vsp/issues/1017/?environment=staging&project=3&query=is%3Aunresolved+spool&statsPeriod=24h).
- Relevant [Nightly batch processing docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/README.md#2-nightly-batch-processing).
- I [asked in #vsa-ebenefits](https://dsva.slack.com/archives/CLY6Q69RV/p1603915073180300).
- I asked Lihan Li about it, he said to email Christopher.Marino2@va.gov (he didn't respond).
- Discussed connectiong to SFTP server with Taylor. He says the "TIMS" server is down.
- TIMS configuration is in [fwdproxy-vagov-staging.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml#L83-L87).
- Need to contact Timothy Allgeier (Timothy.Allgeier@va.gov) via [Slack convo](https://dsva.slack.com/archives/CBU0KDSB1/p1604368735428400) and [GitHub Doc](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/The%20Imaging%20Management%20System.md).

**Comment by jhouse-solvd** [comment]
@ericboehs - Thanks for the additional information. Will follow up with @tskinn to see if he has the resources and access needed to solve this, or if we need to get other team members involved.

**Comment by jbritt1** [comment]
Confirmed this is resolved at this time: https://dsva.slack.com/archives/CBU0KDSB1/p1611753295278200?thread_ts=1611679385.213100&cid=CBU0KDSB1.
