### ISSUE TITLE
Refactor Model for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15801]
## Background
Once the payload comes through properly, we'll have to adjust the Model and update tests to accommodate the new payload

## Considerations
- **Derek:** VSP will likely want us to not fire off api requests from the model. I suspect will have to place VR&E code in /modules. I’ll ask them and refactor accordingly.

## Tasks
- [x] Adjust the payload
- [x] Refactor model methods to accommodate new items in payload

## Acceptance Criteria
- [x] Payload has been adjusted 
- [x] Model methods have been refactored
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
Large Host PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5209/files

New Model PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5320
