### ISSUE TITLE
Adjust CH31 Payload

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15800]
## Background
In order to successfully send the chapter 31 payload to the backend, we need to standardize the payload on the platform wide pattern of wrapping it in an object with the key of `form`.

## Considerations
- Shouldn't need to rename properties
- This won't be named education
- Same pattern as [chapter 36](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vre/28-8832/config/helpers.js#L54)

## Tasks
- [x] Wrap JSON payload and stringify before sending them to BE

## Acceptance Criteria
- [ ] Payload has been wrapped and stringified
- [ ] Confirmed with backend that this allows for sending payload from FE to BE to VR&E API
- [ ] PR has been submitted and merged
