### ISSUE TITLE
Investigate Secure Credentials for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15802]
## Background
The credentials for submission to VRE API need to be obtained from platform and kept in a safe place for safekeeping so that we can successfully authenticate.

## Considerations
- Example: [14991 mock appointment by dillo · Pull Request #5202 · department-of-veterans-affairs/vets-api · GitHub](https://github.com/department-of-veterans-affairs/vets-api/pull/5202/files#diff-e3d36a59a983d33d93409353be8c5f40f456c9883e3dedeb057fe4641ee204f6R1)

## Tasks
- [ ] Keep them in a safe place like credstash (move to another ticket)
- [x] Discuss procedures with #vfs-platform-support
- [x] Find out what needs to be done next

## Acceptance Criteria
- [x] A path forward has been established
- [x] Any relevant notes are captured in this ticket (comments)

**UPDATE - based on new information, these will be in another ticket:**
- [ ] Credentials are secure
- [ ] Testing shows that they work safely

**Comment by digitaldrk** [comment]
UPDATE:
https://dsva.slack.com/archives/CBU0KDSB1/p1605200339015400

**Comment by jason-gcio** [comment]
https://dsva.slack.com/archives/CLY6Q69RV/p1605210607227700
