### ISSUE TITLE
[BE] VA Profile issue: Determine why we are sending a high volume of calls to VA Profile for a single user

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15810]
## Background

Earlier today (11/4/20), Mike Richard posted the following in the VA Profile channel:

> In production we are getting continued requests for the same contact.  The error is Unable to find Contact Information 1403775, so far you've asked us for that ID 3k times in the last 30 minutes.

Lihan looked into this and responded with the following:

> i'm still not sure why this problem is happening, the contact information api could potentially be called in a lot of places but the same user shouldn't be calling it this many times. as far as i know there aren't any automatically retrying requests that would trigger this. i can add some additional logging to try it figure out where it's being called when the error happens. these are all 404 responses from your API right?

So, we don't have answers, but we should still try to figure this out.

## Tasks

- [ ] Get any additional helpful info from VA Profile.
- [ ] If applicable, add additional logging to determine what's going on.
- [ ] Follow up with VA Profile with additional questions, or with findings once we've determined what's wrong.

**Comment by lihanli** [comment]
i created this issue for fixing the problem: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15971

the problem was that when a user does not have any data in va profile yet, we made a separate request for each field we want look up, so when we try to fetch a user's email, addresses, phone numbers, etc we will make 10 requests that will all return not found. 

after my fix is merged, vets-api will remember when a user is not found in va profile and not make any more requests until 1 hour has passed or if the user adds information to their profile page.

**Comment by Samara-Strauss** [comment]
Awesome, thank you for uncovering the problem!

Just want to make sure — there's no downside to not making these request as readily, correct? This won't prevent people from adding or editing info in their profile, right? If there's no risk, then we can move forward with this and I'll close out this ticket in favor of the fix in #15971.

**Comment by lihanli** [comment]
this won't prevent people from editing their profile, once they update their profile the saved "user not found" information will be deleted

**Comment by Samara-Strauss** [comment]
Got it, great! OK, we can close this in favor of #15971.
