### ISSUE TITLE
Remove Facility Locator feature flags

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15813]
## Issue Description
This issue is to clean up code for functionality which no longer needs to be toggled

## Tasks
- [ ] Remove `facility_locator_ppms_forced_unique_id` feature flag	
- [ ] Remove `facility_locator_ppms_legacy_urgent_care_to_pos_locator` feature flag
- [ ] Remove `facility_locator_pull_operating_status_from_lighthouse` feature flag

## Acceptance criteria
- [ ] Unnecessary code is removed
- [ ] Functionality is maintained

**Comment by davidmpickett** [comment]
Duplicate with Flipper audit?

**Comment by davidmpickett** [comment]
Closing as duplicate with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656
