### ISSUE TITLE
Modify feature flag name 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15814]
## Issue Description
This issue is to change the description of a feature flag so it is easier to find and understand. 

For example: 

The description for` facilities_ppms_suppress_pharmacies`  has the following description: 
_Front End Flag to suppress the ability to search for pharmacies_

## Tasks
- [ ] Change the description for the `facilities_ppms_suppress_community_care` feature flag to reflect the toggle impacts the front end. 

## Acceptance criteria
 - [ ] Unnecessary code is removed
 - [ ] Functionality is maintained

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by darkbushido** [comment]
this was already done https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml#L72-L74

**Comment by davidmpickett** [comment]
Per the [Flipper Audit](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656), all flippers now have descriptions
