### ISSUE TITLE
Add tracking events to current CC page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15834]
## Issue Description
Add event tracking to the current community care facility preference page.

---
## Tasks
- [ ] Track continue with "no preference" selection
- [ ] Track selection of 'yes'
- [ ] Track continue with 'yes' selection
- [ ] Track facility locator selection

[/] Track # of CC providers as submission request event _(Waived - moved to #16248)_

**Comment by jonwehausen** [comment]
Hi @laurenernest , thank you for your request, acknowledging receipt!

**Comment by laurenernest** [comment]
Thanks @jonwehausen! Will your team be providing the event names for us to use or would you like our team to pick those?

Here's a screenshot of the page this dev work applies to. (/health-care/schedule-view-va-appointments/appointments_new-appointment/community-care-preference)
![15834_staging va gov_health-care_schedule-view-va-appointments_appointments_new-appointment_community-care-preference](https://user-images.githubusercontent.com/72046525/98423560-d5651000-2043-11eb-8e0e-52fbb1c11d78.png)

**Comment by jonwehausen** [comment]
Hi @laurenernest , 

Thank you for asking. Yes, we will provide the event names --  @bsmartin-ep and/or @bmcgrady-ep would one of you like to take a stab at providing the data layer specification to support new VAOS events...? 

There are 3 outstanding issues: 
- [15794](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15794)
- [15990](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15990)
- [15834 (_this one_)](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15834)

**Comment by bsmartin-ep** [comment]
@laurenernest -

>  Track facility locator selection

It looks like this link already has a unique URL (compared to the footer version):

`/find-locations/?facilityType=cc_provider`

This is being re-written by our PII filters in GA.  If we look at the rewritten URL and filter on a `Previous Page Path`, we get:

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20200901&_u.date01=20201111&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath&explorer-table.advFilter=%5B%5B0,%22analytics.previousPagePath%22,%22EQ%22,%22www.va.gov~2Fhealth-care~2Fschedule-view-va-appointments~2Fappointments~2Fnew-appointment~2Fcommunity-care-preferences~2F%22,0%5D%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Ffacilities~2Findex.html%3FXXX

Work for you @jonwehausen or should we attach an event to this?

**Comment by laurenernest** [comment]
@bsmartin-ep Thanks for the filter for tracking facility locator selection! Glad we can already see that.

**Comment by bsmartin-ep** [comment]
@laurenernest -

Can you elaborate on this one?

> Track # of CC providers as submission request event

**Comment by vbahinwillit** [comment]
@bsmartin-ep - Here are the proposed names for tracking CC preferences:

- vaos-community-care-preferences-has-community-care-provider-selected-true
- vaos-community-care-preferences-has-community-care-provider-selected-false
- vaos-community-care-preferences-has-community-care-provider-true
- vaos-community-care-preferences-has-community-care-provider-false

Where 'selected' is when the user has selected 'yes' or 'no' to the question: "Do you have a preferred VA-approved community care provider for this Primary care appointment?". The second set of names are when the user has clicked the 'Continue' button.

**Comment by bsmartin-ep** [comment]
Hi @vbahinwillit - was just typing this up for you.

For the form control stuff, we are moving towards a global event structure for those:

```js
'event': 'int-radio-button-option-click',
'radio-button-label': 'Do you have a preferred VA-approved...',
'radio-button-option-label': 'Yes' or 'No
```

For the _Continue_ button, how about:

```js
'event': 'vaos-community-care-preferences-continue',
'vaos-has-community-care-provider': 'true' or 'false'
```

...or does this trigger a save-in-progress on the form?

**Comment by laurenernest** [comment]
@bsmartin-ep 
> Track # of CC providers as submission request event

That one is about the submission counts that had a preferred provider included in it (since there are some other steps between this CC preference page and final submission)

**Comment by bsmartin-ep** [comment]
@laurenernest -

So this would be...

- Attached to the `vaos-community-care-submission` event
- A boolean (and not a number)

So something like this?

```js
'event': 'vaos-community-care-submission',
'vaos-has-preferred-provider: 'true',
...(other parameters already on this event)...
```

**Comment by bsmartin-ep** [comment]
For reference @laurenernest , that's the event fired when you click this button:

![image](https://user-images.githubusercontent.com/62304138/99124564-6bfb7900-25d0-11eb-8907-aebfc5e13091.png)

**Comment by laurenernest** [comment]
@bsmartin-ep Correct, that submission event. Right now (and with the next update) there would only be one, but in the future, there could be up to 3. Thoughts on starting with a number now so we don't have to make another change later?

**Comment by bsmartin-ep** [comment]
@laurenernest -

Good idea.  My recommendation on this dataLayer event would be...

```js
'event': 'vaos-community-care-submission',
'vaos-number-of-preferred-provider': 1,
...(other parameters already on this event)...
```

**Comment by laurenernest** [comment]
@bsmartin-ep Thank you!

@vbahinwillit Please see Brian's note [above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15834#issuecomment-727055684). Since that event isn't technically on this preferences page, let me know if you'd like me to break it out from this ticket or if the LOE stays the same.

**Comment by vbahinwillit** [comment]
> Hi @vbahinwillit - was just typing this up for you.
> 
> For the form control stuff, we are moving towards a global event structure for those:
> 
> ```js
> 'event': 'int-radio-button-option-click',
> 'radio-button-label': 'Do you have a preferred VA-approved...',
> 'radio-button-option-label': 'Yes' or 'No
> ```
> 
> For the _Continue_ button, how about:
> 
> ```js
> 'event': 'vaos-community-care-preferences-continue',
> 'vaos-has-community-care-provider': 'true' or 'false'
> ```
> 
> ...or does this trigger a save-in-progress on the form?

@bsmartin-ep Thanks for the suggestions. I will make the changes. I don't think a save in progress event is triggered when clicking continue.

**Comment by vbahinwillit** [comment]
@bsmartin-ep - Is 'in-radio-button-option-click' used for checkboxes too?

**Comment by vbahinwillit** [comment]
@bsmartin-ep - I forgot to ask, but what should the event be for the user selecting the facility locator link?

**Comment by laurenernest** [comment]
@vbahinwillit Per the discussion in scrum, I left a note in this ticket waiving the review page task and created a separate ticket for it.

**Comment by bsmartin-ep** [comment]
@vbahinwillit -

> I forgot to ask, but what should the event be for the user selecting the facility locator link?

I think [we can back our way into those metrics](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15834#issuecomment-726320887) without any additional event tagging.  

> Is 'int-radio-button-option-click' used for checkboxes too?

Ah sorry - didn't know you wanted to track those clicks as well.  Checkboxes would use this event structure:

```js
'event': 'int-checkbox-option-click',
'checkbox-label': 'State',
'checkbox-option-click-label': 'PA'
```

> Is the 'radio-button-label' and 'radio-button-option-label' the actual labels in the form or just whatever text we want it to be?

I believe the intention is that it would be the actual labels (or perhaps a trimmed version).  Do you have a different taxonomy that would be more useful?

**Comment by bsmartin-ep** [comment]
@vbahinwillit -

One other thing, I misspoke on this event:

```js
'event': 'int-radio-button-option-click',
'radio-button-label': 'Do you have a preferred VA-approved...',
'radio-button-option-click-label': 'Yes' or 'No
```

It should be `radio-button-option-click-label` (with `click`).

**Comment by vbahinwillit** [comment]
> @vbahinwillit -
> 
> > I forgot to ask, but what should the event be for the user selecting the facility locator link?
> 
> I think [we can back our way into those metrics](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15834#issuecomment-726320887) without any additional event tagging.
> 
> > Is 'int-radio-button-option-click' used for checkboxes too?
> 
> Ah sorry - didn't know you wanted to track those clicks as well. Checkboxes would use this event structure:
> 
> ```js
> 'event': 'int-checkbox-option-click',
> 'checkbox-label': 'State',
> 'checkbox-option-click-label': 'PA'
> ```
> 
> > Is the 'radio-button-label' and 'radio-button-option-label' the actual labels in the form or just whatever text we want it to be?
> 
> I believe the intention is that it would be the actual labels (or perhaps a trimmed version). Do you have a different taxonomy that would be more useful?

@bsmartin-ep - Thanks for the reply.
> I believe the intention is that it would be the actual labels (or perhaps a trimmed version). Do you have a different taxonomy that would be more useful?

I don't have a taxonomy for this. I'm using a trimmed version of the label due to the label being generated based on the type of care selected.

**Comment by bsmartin-ep** [comment]
> I don't have a taxonomy for this. I'm using a trimmed version of the label due to the label being generated based on the type of care selected

@vbahinwillit - that should work then.  As long as we can differentiate the fields, I'm cool with whatever works for your team.

**Comment by laurenernest** [comment]
@bsmartin-ep Can you confirm you're seeing these events appear on your end?

**Comment by bsmartin-ep** [comment]
@laurenernest -

A few things I see...

1.  The radio button clicks have the `vaos-` prefix.  They should start with `int-`.

![image](https://user-images.githubusercontent.com/62304138/99737535-7ddc9080-2a96-11eb-8cd0-b24d73da5a61.png)

2.  I don't see the `vaos-number-of-preferred-providers` parameter in the `vaos-community-care-submission` event:

![image](https://user-images.githubusercontent.com/62304138/99737450-508fe280-2a96-11eb-99ff-14f35c61c287.png)

3. Should I see any events firing on the dropdown / select clicks?

(cc @vbahinwillit)

**Comment by laurenernest** [comment]
@bsmartin-ep Thanks for reviewing!

1. Good catch. I created another ticket to fix that #16487 (cc @vbahinwillit)
> The radio button clicks have the `vaos-` prefix.  They should start with `int-`.

2. We ended up moving it out of this ticket and into another (#16248) based on where the work was. It should show now.
> I don't see the `vaos-number-of-preferred-providers` parameter in the `vaos-community-care-submission` event:

3. No, I hadn't intended to track that at this time
> Should I see any events firing on the dropdown / select clicks?

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep / @jonwehausen -

This is ready for QA and publishing...

**Non-design system stuff:**
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000391

**Design system stuff:**
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382

Do you feel the need to strip this down to just the radio button used in this ticket?  If not, I would triple check my CTA button changes look good.

Interaction|Data Layer
---|---
![image](https://user-images.githubusercontent.com/62304138/99995231-153c2f00-2d88-11eb-8c93-87540765dc55.png)|`'event': 'vaos-community-care-submission',`<br>`'vaos-number-of-preferred-providers': 1,`<br>`...(other parameters already on this event)...`
![image](https://user-images.githubusercontent.com/62304138/99995541-824fc480-2d88-11eb-8be3-e4cc0bab0d37.png)|`'event': 'int-radio-button-option-click',`<br>`'radio-button-label': 'Do you have a preferred VA-approved...',`<br>`'radio-button-option-click-label': 'Yes' or 'No'`

**Test URL:**
https://staging.va.gov/health-care/schedule-view-va-appointments/

Select a Community Care type like Podiatry

**Comment by bsmartin-ep** [comment]
This has been published.  Closing.
