### ISSUE TITLE
Create Helper Functions for Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#15835]
## Product Outline
N/A

## High Level User Story/ies
As a VFS engineer, I need reusable functions for testing using Cypress so I can more easily and quickly write automated tests for my product.

## Hypothesis or Bet
If we create reusable functions that test commonly used components from the VA design system then VFS team engineers will be able to quickly and easily write automated tests that verify the acceptance criteria for their products.

## OKR
O4: Get VFS teams to know, use, and love the DEPO Platform products and services.
KR4: By Jan 2021, an E2E testing workflow has been adopted by 50% of active VFS teams

## Definition of done
- [x] Cypress environment variables that each contain an array of viewport data by group (e.g. allMobile, allTablet, allDesktop, top5Mobile, top5Tablet, top5Desktop, etc.) will be created with United States, 2020 data or va.gov data from Google Analytics (va.gov data is preferred if it exists)
- [x] New Cypress custom commands and environment variables will be created by extracting common patterns and boilerplate code from existing tests so it's easier to write tests going forward.
- [x] Create additional commands and helper functions per Trevor Pierce.

**Comment by holdenhinkle** [comment]
Created new Cypress custom command, `cy.injectAxeThenAxeCheck()` which gives you two function calls for the price of one--`injectAxe()` following by `axeCheck()`.

- - 

Created the following Cypress environment variables which are each set to an array of viewports (either Cypress preset names or an array of two integers that represent the width and height of a viewport):

- allMobileViewports
- top5MobileViewports
- allDesktopViewports
- top5DesktopViewports

I need the viewports for each of these groups. Posted question about this in vsp-testing-team channel.

**Comment by holdenhinkle** [comment]
Holden Hinkle 4:27 PM
What viewport sizes should I add to these groups? Or where can we get this information?

Peter Hill  1 hour ago
Nice! I think for the viewports we just need to cross reference top 5/10 devices with their screen specs.  Does that make sense?

Peter Hill  1 hour ago
IIRC, iPad has a significant showing, but we can’t be sure which iPad that signifies. So we would need to include all of the iPad screen sizes from the past N years. Maybe 5 years?

**Comment by holdenhinkle** [comment]
Just submitted new PR - https://github.com/department-of-veterans-affairs/vets-website/pull/15107

# I refactored the following:
- `config/cypress.json`
- `src/platform/testing/e2e/cypress/support/commands/viewportPreset.js`

## cypress.json
- Removed `allIPhoneViewports` env var because we don't want people to use it.
- Renamed the viewport env vars. Removed `5` from the name so we can add more than 5 if the need ever arises.
- Added `rank` and `list` properties to each viewport object
- Renamed `name` to `devicesWithViewport`

## src/platform/testing/e2e/cypress/support/commands/viewportPreset.js
- Removed iphone and ipad presets because we don't want people to use them
- Renamed the preset vars. Removed `Top5` from the name so we can add more than 5 if the need ever arises.

**Comment by pjhill** [comment]
MVP for this initiative is complete. Future helpers / extensions will be worked under a new initiative.
