### ISSUE TITLE
Fix anchor link on active-duty service members health care page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15837]
## Issue Description
Currently we have an anchor link on [this page](https://www.va.gov/health-care/eligibility/active-duty/) that goes to the wrong page. In the second accordion "Benefits of enhanced eligibility" the link "Learn more about priority groups" is taking the user to the eligibility page with a #priority-groups but it should go to /priority-groups. 

A content team member needs to update the link on the page so it points to the correct node. 

## Tasks
- [x] Update link in active-duty service members health care page (Randi)
- [x] Review and publish page (Randi)

## Acceptance Criteria
- [x] Anchor link goes to correct health-care/eligibility/priority-groups/ page.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This change has been made. Moving to validate and will close after today's deployment. FYSA @lwalsh617 @DanielleThierryUSDSVA @brianalloyd

**Comment by RLHecht** [comment]
This link is now fixed. Thanks again for calling this out, @lwalsh617 . Closing ticket. FYSA @brianalloyd
