### ISSUE TITLE
General Documentation for use of Cypress on VSP

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#15832]
## Product Outline
N/A

## High Level User Story/ies
As a VFS team engineer, I need robust automated test framework documentation so I can create resilient and valuable tests for my VFS team product.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.
If we enhance the automated testing framework's documentation then engineers will have an easier time participating in test creation with Cypress on VA.gov.

## OKR
_Which Objective / Key Result does this epic push forward?_

50% of active VFS teams are participating in automated testing with Cypress.

### What must be true in order for you to consider this epic complete? 
- [x] General documentation for various areas of Cypress use have been created.
- [x] Existing documentation for use of Cypress on the platform has been enhanced.
- [x] Conduct an internal team peer review.
- [x] Submit a pull request

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
