### ISSUE TITLE
Discover what percent of VFS teams are using 'Form Tester' to test their product's form

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#15833]
## Issue Description
What percent of teams are using the form test documented [here](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/testing/e2e/cypress/support/form-tester), to test their product's forms?

Does the product have a form to test?
Is the team using the form tester?
To what degree is the form covered by testing?
What teams are not using VA Forms Library for their forms?

---
## Tasks
- [x] Determine the best way to scan for use of `form tester` in VFS products
- [x] Perform scan
- [x] Report on results

## Acceptance Criteria
- [x] A report displaying what percent of forms that are hosted on VSP are currently being tested by the `form tester`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
Caveat -- Form tester only works with forms built using the forms library.

Example: COVID Vaccine Prep Tool did not use the VA Forms Library for their form, so the forms tester can't be used.

**Comment by rjohnson2011** [comment]
2/25 Update - Working on gathering information relating to additional info:
- [ ] Number of teams with any kind of form?
- [ ] Number of teams with VA Forms System forms?
- [ ] Number of teams with VA Forms System forms NOT using form tester?
- [ ] Bonus question — can form tester be adapted for none VA Forms System forms?

**Comment by pjhill** [comment]
> 2/25 Update - Working on gathering information relating to additional info:
> 
> * [ ]  Number of teams with any kind of form?
> * [ ]  Number of teams with VA Forms System forms?
> * [ ]  Number of teams with VA Forms System forms NOT using form tester?
> * [ ]  Bonus question — can form tester be adapted for none VA Forms System forms?

Excellent -- where are you going to collect all this info? Also, we should make a note of how you gather all the info so we can reproduce it at a later date in order to measure any potential progress or change in the platform's use of forms.

**Comment by rjohnson2011** [comment]
> > 2/25 Update - Working on gathering information relating to additional info:
> > 
> > * [ ]   Number of teams with any kind of form?
> > * [ ]   Number of teams with VA Forms System forms?
> > * [ ]   Number of teams with VA Forms System forms NOT using form tester?
> > * [ ]   Bonus question — can form tester be adapted for none VA Forms System forms?
> 
> Excellent -- where are you going to collect all this info? Also, we should make a note of how you gather all the info so we can reproduce it at a later date in order to measure any potential progress or change in the platform's use of forms.

For the second and third checkboxes (the VA Forms System) I'm going through instances of `forms-system` and noting the directory, team responsible, and number of instances uses (i.e. used 6 times within `covid-registry`). It is a fairly long, manual process (454 results for `forms-system` alone) but wasn't able to find an alternative on how to filter through the unneeded files or grab team authorship info in an automated way. 

After this, I will look for instances of forms without the VA Forms System using a similar methodology.

**Comment by pjhill** [comment]
This discovery is complete.
