### ISSUE TITLE
Documentation for Direct Deposit component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15845]
## Issue Description
Document the use cases for direct deposit 

---
## Tasks
- [x] Draft description for using direct deposit
- [ ] Post documentation somewhere (TBD) probably in pattern section of design.va.gov

## Acceptance Criteria
- [ ] Sign off on documentation from DST 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
