### ISSUE TITLE
Usability Testing Prep - Facilities [Vet Center pages]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15846]
## Steps to complete Usability Testing Prep: 
- [ ] Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [ ] Attach all artifacts before requesting the meeting
- [ ] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] Usability Testing Prep review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [x] [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/product-brief.md)
- [x] Link to [UXPin prototype](https://preview.uxpin.com/603da0b67ccefbbee74fcd8bb77a8fed12baabb5#/pages/134151554?mode=cvhidm) to be discussed. 
- [x] Usability testing prep [mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1603629469594/94d7825c23f0eff800a5271bf396293535ef5de7?wid=0-1605618343012&outline=open) for discussion.
- [x] Link to [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/discovery)
- [ ] Link to or attach artifact with copy (if separate from prototypes/mockups)
- [ ] Link to research plan 
- [ ] Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- [ ] Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): 
**Leyda Hughes**
**Ryan Thurlwell**
**Meg Peters**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira will reach out as needed_
**Requesting November 17 at 11 AM ET**

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by shiragoodman** [comment]
@mmiddaugh do you have any prototypes or mockups to share for the review tomorrow?

**Comment by lildziner** [comment]
Link to [UXPin prototype](https://preview.uxpin.com/603da0b67ccefbbee74fcd8bb77a8fed12baabb5#/pages/134151554?mode=cvhidm) to be discussed.

**Comment by rtwell** [comment]
Commenting here so I do not forget and because my cats do not allow me to sleep 😹 

### On this page
As a snapshot of the content for this Vet Center, and as a pattern for all Vet Center pages (a module for a template), I'm mulling over the hierarchy of this and wondering if we should hone this information into something more structured and rigid. 

I think what is throwing me off is we're tackling 2 problems at once: 
1. What is this thing we call a Vet Center
2. What is unique about **_this_** Vet Center. 

We don't have this additional layer with something like a VAMC—everyone knows what a hospital/medical center is, but we've got the extra layer of telling Veterans about Vet Centers as a concept. The challenge from a template/CMS approach, is: Do we need to tell users what a Vet Center is on every Vet Center page? Probably not. We could consider solving those 2 problems on 2 different pages. If we leveraged something like the Campaign landing page as a "here's what a Vet Center is, find one near you" main page, and left the individual Vet Center pages on their own, they would be more light weight, and straightforward. More than likely, users have gotten here via organic search, and at this point "what a Vet Center is" is less important (imo) than "this specific Vet Center I would like to learn more about". Additionally, individual Vet Center pages can always reference back to the main Vet Center page to provide access to info about what Vet Centers are and how they are different. 

### Other access points section
This language is a bit confusing to me: Why should I care there are other access points? How can we make this more relevant?

Using the accordion component in this manner places a large amount of cognitive load on the user to parse many concepts at the same time:
1. What is this thing (e.g. it is a place, but also a place inside another place)
2. Where is this place (I have to recognize the address, and cognitively evaluate its relevance to me)
3. This thing is interactive (given all of that, I must decide if I want to know more, and what would I expect to see in this accordion)

### Contact info
We should format our phone numbers/contact information the same across all VA locations. If we hypothesis the main action we'd like a user to be able to take is contacting a Vet Center, then we should use a proper CTA like our buttons. 

### Features
The yellow and blue boxes should be the same type treatment as the VMACs (same header size, etc). I'm not overly concerned about yellow vs blue, I am also thinking about consistency across va.gov.

**Comment by pjhill** [comment]
Hello team, it appears as though there are not any QA artifacts available for review at this time. Typically, I would expect some stubbed out acceptance, functional, and/or integration test cases.  Additionally, if you are iterating on an existing product, it is prudent to evaluate the existing product's content and functionality to create regression test cases. If you have been practicing the Collab Cycle for some time, you should be able to collect a subset of your previous test cases into a relevant regression test sutie.

For more information regarding QA artifacts, how to create them, and when VSP expects to review each artifact please see the [QA Artifacts page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md) under the QA practice area documentation.

**Comment by mpeterz** [comment]
Since we're considering entry points to Vet Center detail pages, let's look at how many people are coming through the main Vet Centers landing page:
https://www.vetcenter.va.gov/

And let's work with (and guide) Vet Centers and Aptive on optimizing the main Vet Centers landing page.
