### ISSUE TITLE
Development for direct deposit component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15843]
## Issue Description
Development for direct deposit component 

---
## Tasks
- [ ] Take artifact from design and implement 
- [ ] Unit tests
- [ ] Stories/description of what the component does 

## Acceptance Criteria
- [ ] Sign off from designer
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
