### ISSUE TITLE
[BUG] - View Payments - Payments do not display properly if only one payment record is found

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#15849]
## Story
As a Veteran or general user of VA.gov, I want to be able to see where all the payments I have received or had returned, so that I can know exactly where I stand with those payments.  During testing it was discovered that payments page does not display properly if only one payment record is found.

## Tasks
- [x] Adjust the code to handle the use case where only one payment record is found.
- [x] Make sure the page displays properly.

## Acceptance Criteria
- [x] The page displays properly when only one payment record is found.
- [x] The page displays properly when multiple payment records are found.
- [x] A PR has been requested for merging.

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5231
