### ISSUE TITLE
Component design for direct deposit

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15842]
## Issue Description
Create a Sketch library pattern for direct deposit

---
## Tasks
- [ ] Create library pattern
- [ ] Hand off to developer 

## Acceptance Criteria
- [ ] Sign off from DST and DC
---
