### ISSUE TITLE
Document build system 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15840]
## Issue Description
 We need to improve the documentation surrounding the build system, including side nav queries 

May be able to add to existing documentation, such as Github on [templating](https://github.com/department-of-veterans-affairs/vets-website#how-templating-works)

---
## Tasks
- [ ] Document build system

## Acceptance Criteria
- [ ] Documentation exists for build system, including side navs 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
