### ISSUE TITLE
Discovery / Audit of existing instances of Direct Deposit 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15841]
## Issue Description
Audit of instances of direct deposit

---
## Tasks
- [ ] Audit and analysis of current direct deposit designs

## Acceptance Criteria
- [ ] Review with team of audit during kick off meeting
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
