### ISSUE TITLE
Audit of current Sketch Library, old vets.gov Sketch Library

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15855]
## Issue Description
Complete an audit of what is in the current Sketch library against the old vets.gov Sketch library and check if design.va.gov documentation has the info on how things should work. 
---
## Tasks
- [ ] Create comparison between the two Sketch libraries 
- [ ] Flag inconsistencies 

## Acceptance Criteria
- [ ] Spreadsheet showing contents of each library 
- [ ] Board with screens showing differences 
---
