### ISSUE TITLE
DataDog - Investigate whether or not an endpoint is provided to access DataDog from within AWS GovCloud

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#15863]
## Issue Description
_In order to integrate correctly manner with DataDog (DD) as a 3rd-party SaaS provider, it needs to be determined whether or not DD provides an endpoint within the Amazon GovCloud_

---
## Tasks
- [ ] _Reach out to DD support and determine whether or not there are additional endpoints to connect to_
- [ ] _If necessary, create a follow up ticket to implement the necessary configuration change that will allow us to send information to DD via GovCloud endpoint_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
This will likely be irrelevant based on work to migrate to using the GovCloud instance of DataDog #23513 

Closing.
