### ISSUE TITLE
Link to Facility Locator from Mental health services page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15871]
## Issue Description
As a Veteran arriving on Facility Locator from another VA.gov page, I would like the appropriate facility type to be pre-populated so that I can search efficiently and don't have to remember what to choose. 

There are two opportunities to link to the Facility Locator for a Vet Center search on the [VA mental health services page](https://www.va.gov/health-care/health-needs-conditions/mental-health/)

1. "Find your nearest Vet Center" link from "Get free mental health care..." box links to Facility Locator but pre-populates with facility type = VA health. 

<details>
<summary> Screenshots </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/aae8d4c5-fa20-4555-9e22-93b1cb78cd3e)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/3fbebeb4-2a9b-4999-9558-61f607dedc95)

</details>

2. "Find a Vet Center near you" link from "What other options do I have" text links to Facility Locator but pre-populates with facility type = VA health. 

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/98302782-47712280-1f7a-11eb-89d5-c086bbf5a379.png)

</details>

## Tasks
- [ ] Edit links to prepopulate Facility type with "Vet Centers"

## Acceptance Criteria
-[ ] Given a  Veteran clicks the "Find your nearest Vet Center" link from the "Get free mental health care..." box on VA mental health services page, the Facility type box on Facility Locator will prepopulate with "Vet Centers".
-[ ] Given a  Veteran clicks the "Find a Vet Center near you" link from the "What other options do I have" text area, the Facility type box on Facility Locator will prepopulate with "Vet Centers".

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
@mmiddaugh URL for Facility Locator to pre-populate with vet center is 

https://www.va.gov/find-locations/?facilityType=vet_center

**Comment by davidmpickett** [comment]
Resolved
