### ISSUE TITLE
Link to Facility Locator from PTSD page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15875]
## Issue Description
As a Veteran arriving on Facility Locator from another VA.gov page, I would like the appropriate facility type to be pre-populated so that I can search efficiently and don't have to remember what to choose. 

[PTSD treatment page](https://www.va.gov/health-care/health-needs-conditions/mental-health/ptsd/) references to Vet Center services in several places but does not link to the Facility Locator for a Vet Center search.  

1. The "What services does VA provide for PTSD?" box mentions referral to a Vet Center without linking to Facility Locator. 
2. The "Find a Vet Center near you link" under "What if I don't have VA health benefits" links to Facility Locator but does not pre-populate with Vet Center as Facility type. 

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/98301665-5eaf1080-1f78-11eb-90b4-35714ffd4521.png)

![image](https://user-images.githubusercontent.com/55411834/98302286-5c998180-1f79-11eb-8dde-362ad40b8b70.png)

</details>

---
## Tasks
- [ ] Make text interactive and link to Facility Locator such that the Facility type is prepopulated with "Vet Centers"

## Acceptance Criteria
- [ ] A Veteran visiting the PTSD treatment page can click a link in the Vet Center referral text and connect to the Facility Locator with the the Facility type prepopulated with "Vet Centers"
- [ ] Given a Veteran clicks the "Find a Vet Center near you" link from the PTSD treatment page, the Facility type box on Facility Locator will prepopulate with "Vet Centers".

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
@mmiddaugh URL for Facility Locator to pre-populate with vet center is

https://www.va.gov/find-locations/?facilityType=vet_center

**Comment by davidmpickett** [comment]
resolved
