### ISSUE TITLE
Link to Facility Locator from MST page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15873]
## Issue Description
As a Veteran arriving on Facility Locator from another VA.gov page, I would like the appropriate facility type to be pre-populated so that I can search efficiently and don't have to remember what to choose. 

"Find a Vet Center near you" link from "How do I access VA services for MST?" box on [Military sexual trauma page](https://www.va.gov/health-care/health-needs-conditions/military-sexual-trauma/) links to Facility Locator but does not pre-populates with facility type = Vet Centers. 

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/98300909-383ca580-1f77-11eb-890f-bcff7ea05e88.png)

![image](https://user-images.githubusercontent.com/55411834/98300961-468ac180-1f77-11eb-9a01-4a8ee514f579.png)

</details>

---
## Tasks
- [ ] Edit link to prepopulate Facility type with "Vet Centers"

## Acceptance Criteria
- [ ] Given a  Veteran clicks the "Find a Vet Center near you" link from "How do I access VA services for MST?" box on Military sexual trauma page, the Facility type box on Facility Locator will prepopulate with "Vet Centers".
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
@mmiddaugh  URL for Facility Locator to pre-populate with vet center is

https://www.va.gov/find-locations/?facilityType=vet_center

**Comment by davidmpickett** [comment]
Resolved
