### ISSUE TITLE
Implement GA Events into CH36 Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15872]
## Goal
Implement the final events from GA Team for the wizard-specific elements.

## Tasks
- [ ] Review the data layer specification
- [ ] Implement event names per the specification below:  

### Specification
Description/Screenshot of Interaction | DataLayer | Test Status 
------------ | ------------- | ------------- 
Clicks on form controls within wizard (radio buttons) | ![image](https://user-images.githubusercontent.com/48527022/96578379-1965c000-12a3-11eb-878e-58500453781f.png) | ❌ **DOES NOT PASS** - Functional firing of this event is correct, however please populate `'form-field-value'` with the full question answer text 
Clicks on links contained within alerts ![image](https://user-images.githubusercontent.com/48527022/96583490-cc85e780-12aa-11eb-872b-b5e8cd66dcc1.png) | `no event fired` | ❌ **DOES NOT PASS** - should fire a `'howToWizard-alert-link-click'` event on click
Clicks on primary button CTA to apply now at end of wizard ![image](https://user-images.githubusercontent.com/48527022/96583885-68175800-12ab-11eb-8eb3-52f98927ace1.png) | `no event fired`  | ❌ **DOES NOT PASS** - should fire `cta-primary-button-click` event
Skip wizard link ![image](https://user-images.githubusercontent.com/48527022/96584739-a7927400-12ac-11eb-96ec-e9437981b100.png) | `no event fired` | ❌ **DOES NOT PASS** - should fire `howToWizard-skip` on click
Visibility of wizard alerts | ![image](https://user-images.githubusercontent.com/48527022/96586005-584d4300-12ae-11eb-91ae-8e18830036aa.png) | ✔️ **PASS** -- Functional firing of this event is correct, however would like to request the `notice` be changed to `alert` though

### Summary of Adjustments to make
- [ ] Populate `form-field-value` with the full form value text as presented to the user within the form control
- [x] Change where the word `notice` is used in spec and replace with `alert` to align with product verbiage -- `howToWizard-**notice**-displayed` and `reason-for-**notice**` should be changed to `howToWizard-alert-displayed` and `reason-for-alert`  
- [x] Events to be newly added: 
   - [x] `'howToWizard-cta-displayed'` 
   - [x] `'howToWizard-skip'`
   - [x] `'howToWizard-alert-link-click'` 
   - [x] `'howToWizard-hidden'`

## Acceptance Criteria
- [x] All adjustments have been made, as appropriate
- [x] A PR has been requested for merging

**Comment by cohnjesse** [comment]
@jason-gcio @jonwehausen We can't actually do the first one of these, `Functional firing of this event is correct, however please populate 'form-field-value' with the full question answer text` because in the wizards we don't get access to the answer text and instead only get access to the value of the answer which is different from the text and can't be changed since it is used by the back end.

**Comment by jonwehausen** [comment]
Hi @cohnjesse , 

Okay thank you very much for this information, appreciate it. We are in the process of QAing your work here.
