### ISSUE TITLE
[FE] Hide the "Start a new Questionnaire" button 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#15895]
## User Story
As a veteran I should not be able to start a new questionnaire, only continue the one I am working on. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d5e01a9b85b431a14)

## Description

When I clicked "Finish this questionnaire later,"

![Screen Shot 2020-10-30 at 4.49.54 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9f2c68ef-c78d-46cb-baa6-85b72558160f)
 The "Start a new application" button should also be removed here.

## Tasks
- [x] Add configuration to hide "start a new  XXX " button
- [x] Create unit tests 
- [ ] Update relevant documentations

## Acceptance Criteria

- [x] The button should be hidable. 
- [x] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [x] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
@kristenmcconnell  and @abuckley3385  This is now in staging.

**Comment by kristenmcconnell** [comment]
Looks good in staging.
