### ISSUE TITLE
Add content per SME request to VET TEC page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15909]
## Issue Description
Per stakeholders Joe Preisser and Tammy Hurley we need to add a statement on the VET TEC page about having exhausted the funding for this fiscal year. We need to change the content they provided to make it more Plain Language before posting on the site. 

VA.gov url: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/
Drupal node: prod.cms.va.gov/node/930/edit

Original text from stakeholders:

“Based on current enrollment data the VET TEC Program remains popular with Veterans and VA has exhausted Fiscal Year 2021 VET TEC funding. VA will continue to accept VET TEC program applications during this time so that Veterans can receive formal eligibility decisions and plan future participation. Students currently enrolled and in receipt of a VET TEC award letter, your training will continue uninterrupted.
 
Funds for new students seeking training through VET TEC will not be available until October 1, 2021 or additional funding is secured. See our webpage for more information about the program, and future funding updates.”

## Tasks
- [x] Rewrite content provided into Plain Language (Beth)
- [x] Add to page and copy edit (Randi)
- [x] Send to SMEs for feedback (Beth/Randi)
- [x] Publish (Randi)

## Acceptance Criteria
- [x] New content live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
PL text emailed to SME for alignment:
We have no more VET TEC funds at this time to offer new participants. But you can still apply and find out if you’re eligible to get money for training when we have funds available again. This will be October 1, 2021, or earlier. If you’re already participating in the VET TEC program, this doesn’t affect you. You can continue with your training.

**Comment by bethpottsVADEPO** [comment]
Update: Here's the final text I've aligned with the SMEs on.
We have no more VET TEC funds at this time to offer new participants. But you can still apply and find out if you’re eligible to get money for training when we have funds available again. This will be October 1, 2021, or earlier if we can secure more funding. If you’re already participating in the VET TEC program, this doesn’t affect you. You can continue with your training.

@RLHecht has it queued up here:
preview-prod.vfs.va.gov/preview?nodeId=930

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close after tomorrow's deploy. FYSA @brianalloyd

**Comment by RLHecht** [comment]
These changes are live on the site. Closing ticket. FYSA @brianalloyd
