### ISSUE TITLE
Crosslink to Vet Center page from VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15904]
## Issue Description
As a Veteran viewing my VA Medical Center's page, I would like to be able to click a link to view the page for the local Vet Center(s) 

Possible locations: 

- Mental health care service accordion 
- Military sexual trauma service accordion 
- PTSD service accordion
- Suicide Prevention accordion
- Women Veteran care accordion
- Addiction/Substance abuse accordion
- "Other resources" box on [Mental health care page](https://www.va.gov/pittsburgh-health-care/mental-health-care/) (linked from health services accordions as "care coordinator"

![image](https://user-images.githubusercontent.com/55411834/98386579-9ae08080-200d-11eb-9354-b27a11c31cbb.png)

---
## Tasks
- [ ] Add interactive links for relevant Vet Center page(s)

## Acceptance Criteria
-[ ] Links to relevant Vet Center pages are present 
- [ ] Given a Veteran clicks the Links to relevant Vet Center(s), a new tab opens for the appropriate page. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
