### ISSUE TITLE
Debt Portal - fallback messaging for unassigned diary codes

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#15911]
## Issue Description
In the case of an unassigned diary code being sent back to us, we'll need to have a fallback status and next step or alert

---
## Tasks
- [x] Draft fallback messaging pattern for diary codes that do not have content
- [ ] Draft and review with content
- [x] Create FE ticket to complete work

## Acceptance Criteria
- [x] FE ticket created and linked in this ticket

**Comment by rebeccawalsh** [comment]
## Background
We're not expecting these unassigned diary codes to come up (and if they do, it's probably a mistake or temporary situation), so we came to the conclusion that using some generic verbiage like the following would suffice. If these unassigned diary codes *do* happen to come up, we'll ask the veteran to wait a week to see if things change, and to call the DMC if it doesn't.

## Proposed content
Status: We're updating your account

_Info alert:_
**We’re updating your account**
Please check back in 1 week for updates. If your account shows the same information then, call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.

## Next steps:
@3obryandogs please take a look and let me know if there are any issues with this direction. This content was written by Peggy for a category of statuses, but seems general enough to use for fallback messaging as well.

We should make sure that we are tracking unassigned diary codes as they come in and make sure that we properly categorize them or give them their own dedicated statuses. @leahkeeler Putting this on your radar to create a ticket to get that work in our backlog.

**Comment by leahkeeler** [comment]
Thanks @rebeccawalsh - DMC was supposed to come up with process to give us new codes @bradl3yC - can we track proactively ?

**Comment by bradl3yC** [comment]
@leahkeeler we could add a tag for an event where we receive a code that we do not have content for, yes!

**Comment by 3obryandogs** [comment]
@rebeccawalsh 
We’re updating your account
Please check back in one week for updates. If your account still shows the same information, call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.
