### ISSUE TITLE
[Design] Direct deposit for edu: Add state for if someone is eligible for only one type of direct deposit but not the other

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15916]
## Background

Most of the [direct deposit for edu designs](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/) are done.

However, I just realized we don't have a state that shows what this page looks like if someone only is eligible for one type of direct deposit but not the other. [These designs](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/c47baced-0945-46f1-a01b-5e7df4662eda) show what it would look like if someone is eligible for BOTH types of direct deposit but has only added info for one. But we still need designs for if someone is only eligible for one type of direct deposit but not the other.

For this state, our options are:

- Don't show the direct deposit block for the benefit type for which someone is not eligible (eg. if someone is only eligible for direct deposit for edu but not direct deposit for comp & pen, we don't show the comp & pen block at all).
- Show both blocks. For the "eligible" block, we'll show the add/edit state depending on what applies. For whatever benefit someone is not eligible for direct deposit payment (aka they just don't receive this kind of payment from the VA), we put messaging in the block that explains that this person does not receive either comp & pen or edu payments (depending on which benefit), and maybe a link to that benefit hub landing page to explore that benefit.

## Tasks

- [x] Decide on approach.
- [x] Review approach with Samara/Tressa/Cassandra
- [x] Mockups
- [ ] Copy review, if applicable

## Acceptance Criteria
- [ ] Provide an updated mockup to Samara
- [ ] Request copy feedback from Peggy

**Comment by sporeboy** [comment]
Here is a link to mocks showing the two options when a user **does** receive one type of VA payments, but not both:
- Simply don't show the "box" if the user doesn't receive that type of payment
- Show a box with link when a user does not receive that type of payment

The link: https://xd.adobe.com/view/5315e9ba-69ee-4082-bb26-29605bc4ae67-0646/

**Comment by Samara-Strauss** [comment]
@tressaellen @callen2563 can I ask you to chime in on the approaches above? We are trying to determine what we show when someone has one type of direct deposit but not the other. Do we just not show the box for the type they don't have? Or do we show both and explain that the person currently does not receive X type of direct deposit payments. 

I, personally, think we *should* show both boxes and explain they don't receive X type of benefit, but Jim feels differently. What do you all think?

**Comment by tressaellen** [comment]
@Samara-Strauss @sporeboy - I think it's a good idea to show _something_ for the benefits they are not currently receiving, but the box feels like the wrong option for that information. Maybe just a simplified link would work?

<img width="1060" alt="Screen Shot 2020-11-09 at 11 50 12 AM" src="https://user-images.githubusercontent.com/58752772/98583771-653bd180-2271-11eb-8c65-9b30434a3bc0.png">

**Comment by sporeboy** [comment]
I can see the merit of *not* showing DD that the user doesn't have: It keeps the screen cleaner and more purposeful. The DD tool is a use-once-and-walk-away sort of feature.

That said, I'm OK with "advertising" there is another payment/benefit out there. And I'm OK with a simple link--but there need to be some context for it. So... more words, a paragraph or something needs to establish that "you," the user, don't get this and do you want to find out more about X benefit. 

This is something we can test in usability. Get a quick read on whether users understand why the link is there, and where they expect it will take them.

**Comment by Samara-Strauss** [comment]
> That said, I'm OK with "advertising" there is another payment/benefit out there. And I'm OK with a simple link--but there need to be some context for it. So... more words, a paragraph or something needs to establish that "you," the user, don't get this and do you want to find out more about X benefit.

I agree with this. I think the link with no other context is confusing, but also I still hypothesize that we should have *something* instead of nothing. I don't think I've been clear about why, so here's my rationale:

- Even after the improved Profile 2.0 redesign, we are still seeing a ton of people searching for direct deposit **from the profile**. About 2/3 of these searches are coming from people who are not seeing the direct deposit section (which makes sense, since we only show it conditionally), but that tells me there are people who are expecting to see this section that are not seeing it. Part of this problem may be solved by us adding direct deposit for edu onto the site, but it's also signaling to me that maybe our approach overall with this tool should not be to hide things conditionally but to instead show blank, "You don't have X" states instead.
- On the rare occasion that there is some sort of mistake and someone should be getting edu/comp & pen payments and we show that they are not, this would signal to someone that there's something they need to get fixed within the VA.

Here's how I would like to move forward: let's test both of Jim's proposals. My guess is that they'll both test just fine, but let's test both and see what kind of feedback we get and if that helps us figure out how we'd like to move forward.

Jim -- the link to the designs is not working for me right now, but I recall that you had the copy that explained that someone did not receive X type of direct deposit indented in the text box. Can you just left align it like so? 

<img width="536" alt="Screen Shot 2020-11-10 at 10 08 09 AM" src="https://user-images.githubusercontent.com/34068740/98692175-d2686900-233c-11eb-9788-da3389d2efeb.png">

Otherwise, that should just need copy review/refinement, and we'll be good to go.

**Comment by sporeboy** [comment]
I understand the rationale. Here is a link to the updated screens (3 and 4): https://xd.adobe.com/view/5315e9ba-69ee-4082-bb26-29605bc4ae67-0646/screen/a942fa36-4ebd-446f-92ee-65149d9e9584

**Comment by Samara-Strauss** [comment]
@sporeboy these look great! We can close this once you get a copy review from Peggy.

**Comment by Samara-Strauss** [comment]
Closing. Copy is captured in #15518, but also copy/pasting below ([via Peggy](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15518#issuecomment-729276025)):

> Hi, @sporeboy additional feedback for use cases where someone has DD for one type of payment, but not the other.
> https://xd.adobe.com/view/5315e9ba-69ee-4082-bb26-29605bc4ae67-0646/screen/5dbf1181-9771-4bfd-b0ca-b9770bfdf4de
> 
> 
> 1. Message for no education DD: 
> 
> Our records show that you're not receiving education benefit payments. If you think this is an error, please call us at [800-827-1000](make this a hyperlink). 
> 
> Where does this education eligibility link take users ?
> 
> I recommend updating link to:
> [Find out if you’re eligible for VA education benefits] (https://www.va.gov/education/eligibility/)
> 
> ------
> 
> 2. Message for no pension and compensation DD
> 
> Our records show that you're not receiving disability compensation or pension payments. If you think this is an error, please call us at [800-827-1000](make this a hyperlink). 
> 
> Where does this link take users? these are two different benefits with different eligibility criteria. 
> [Learn more about compensation and pension eligibility]
>

**Comment by Samara-Strauss** [comment]
Oh, @sporeboy I'm assuming you've updated the mocks with Peggy's copy, but sorry if I closed this out before you got a chance to do that! Feel free to reopen if needed, but my guess is this is still ok to be closed.
