### ISSUE TITLE
Update PDF links on Welcome Kit page with new files uploaded into CMS

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15913]
## Issue Description
Now that Events and Outreach stakeholders can upload PDFs and media files to the CMS, we need to update the Welcome Kit page so that we are using these new files being pulled from the CMS rather than the PDFs being pulled from our assets folder in Github. 

Stakeholder Justin Hoffman uploaded 11 files to the CMS and named them the same as what we named our files in the assets folder. A content team member now needs to update the Welcome Kit page and then we should remove the PDFs from the assets folder. Justin also uploaded a new PDF that will need a new link added onto the Welcome Kit page.

This work needs to be completed and live before Veterans Day.

Files uploaded: 

Health Care Quick Start Guide: Replacement file for "Apply for VA health care (PDF)" link on VA Welcome Kit site.
Mental Health Quick Start Guide: Replacement file for "Get started with mental health services (PDF)" link on VA Welcome Kit site.
 Community Care Quick Start Guide: Replacement file for “Understanding community care (PDF)” link on VA Welcome Kit site.
Urgent Care Quick Start Guide: Replacement file for “Accessing urgent care (PDF)” link on VA Welcome Kit site.
Disability Rating Quick Start Guide: Replacement file for “Apply for a disability rating (PDF)” link on the VA Welcome Kit site.
Education Benefits Quick Start Guide: Replacement file for “ Apply for education benefits (PDF)” link on the VA Welcome Kit site.
Memorial Benefits Quick Start Guide: Replacement file for “Apply for burial in a VA national cemetery and for memorial products (PDF)” link on the VA Welcome Kit site.
 Appeals Modernization (AMA) Quick Start Guide: Replacement file for “Understanding the modernized decision review process (PDF)” link on the VA Welcome Kit site.
Caregiver Quick Start Guide: Replacement file for “Get started with caregiver benefits (PDF)” link on the VA Welcome Kit site.
Survivor Benefits Quick Start Guide: Replacement file for “Apply for survivor benefits (PDF)” link on the VA Welcome Kit site.
65+ Veterans Quick Start Guide: NEW FILE THAT NEEDS A LINK CREATED. The link should say "Get started with services for Veterans ages 65+ (PDF)" and go under the "For Veterans" section of the VA Welcome Kit site.

---
## Tasks
- [x] Update Welcome Kit page by linking to new PDFs in Drupal (Randi)
- [x] Add text for new PDF that was added (Randi)
- [x] Send preview link to stakeholders for approval (Beth)
- [x] Review and publish page (Randi)
- [x] Remove our old PDFs from the assets folder in Github (Nick/Kelson)

## Acceptance Criteria
- [x] Live page is pulling links from within the CMS instead of Github
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These PDFs were uploaded and the page published. Moving to validate. Need to create a redirect ticket for @ncksllvn. Also these PDFs in Github should be removed when you have time. FYSA @brianalloyd

**Comment by RLHecht** [comment]
Redirect ticket #16090 is in progress. @ncksllvn let me know if you want to keep this ticket open to delete the old Github files or do it as part of the redirect ticket.

**Comment by RLHecht** [comment]
@ncksllvn Can you let me know when the old Welcome Kit PDFs are deleted from the assets folder and then I can close this ticket? Thanks much!

**Comment by ncksllvn** [comment]
Thanks for the reminder @RLHecht , here is a PR to do that https://github.com/department-of-veterans-affairs/vagov-content/pull/728

**Comment by ncksllvn** [comment]
I removed all of the PDFs that are now redirecting to `/welcome-kit/` but there are still some PDFs in that repo FYSA, https://github.com/department-of-veterans-affairs/vagov-content/tree/master/assets

**Comment by RLHecht** [comment]
Thanks much @ncksllvn Closing this ticket. FYSA @brianalloyd
