### ISSUE TITLE
Updated OMB expiry date from IRIS

### ISSUE THREAD

**Issue by murrayra** [department-of-veterans-affairs/va.gov-team#15937]
### Content support for:
- Unauthenticated (static) VA.gov pages
- Apps or tools
- Other writing or editing requests

### Engineering support for:
- Redirects that have **first been vetted by the VSP IA team**
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [ ] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests 

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
This request is for the new Contact Us form which is replacing the current IRIS at  https://iris.custhelp.va.gov/ 

Our team is building the replacement for existing [IRIS form](https://iris.custhelp.va.gov/app/ask) An initial version of the new form we are building is on staging [here](https://staging.va.gov/ask-a-question) On the old IRIS form, there is an OMB number and an expiry date illustrated below ![image](https://user-images.githubusercontent.com/2493271/98405360-2243e900-203a-11eb-94d3-52a808205417.png)

* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
Please see the Contact Us product brief at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/iris/IRIS-product-brief.md 

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page - N-A** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

- [X ] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 

Existing IRIS page https://iris.custhelp.va.gov/  
New IRIS page: https://staging.va.gov/ask-a-question/ 

Please see the Contact Us product brief at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/iris/IRIS-product-brief.md 

   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing. N-A
      * < list of new info >
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * < list of new info >

- [ ] **Writing support for new app/tool** N/A 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)   

- [ ] **Editing support for app/tool - N/A**
<br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support - N/A

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
This is a request for an updated OMB number for the IRIS form; the existing form has an expiry date of 11/30/2019.
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Late Q1/early Q2 2021.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: IRIS
- DEPO product owner: Chante Lantos Swett
- Product manager: Ramya Ramesh
- Designer: Rachel M. Murray
- FE engineer: Helen Shin
- Product/team Slack channel: https://app.slack.com/client/T03FECE8V/C016DSVNL07/thread/C8E985R32-1603900048.092200 

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Hi @murrayra. Could you clarify for me what the need is here? Thanks!

**Comment by murrayra** [comment]
Hi @DanielleThierryUSDSVA - because the OMB number has expired we're trying to figure out what to do.  

- Do we need a new OMB Number when the content of the form changes?
- Can we use the same OMB number for our new form that existed on the previous form? 
- Can we renew the OMB number if no new OMB number is required?

Any guidance on what to do or who we should speak would help...thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @murrayra. I'm not sure of the answers, but I'll look into it a bit and get back to you. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @murrayra. I connected with @clantosswett on this as well. I looked into directives and found info around the fact that information collection isn't authorized after the OMB number expires. But I'm not seeing answers to the specific questions above. I think the next step would likely be to find and contact the appropriate forms officer for the IRIS form. Chante, let me know how you'd like to handle next steps in digging into this. Thanks!

**Comment by murrayra** [comment]
@rumyeahs fyi on updates for this

**Comment by clantosswett** [comment]
@DanielleThierryUSDSVA @murrayra let me send an email to Trisha Dang to see if she knows who is the owner of the IRIS form PRA approval. I'll send out that email and see what we learn from there.

**Comment by FranECross** [comment]
@clantosswett @DanielleThierryUSDSVA @murrayra Do you know if this old (2020) epic/request is obsolete and can be closed? Thank in advance!

**Comment by FranECross** [comment]
closing old iceboxed ticket.
