### ISSUE TITLE
Update nginx component list

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#15948]
## Issue Description
[This file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_components.yml) is out of date and could stand to be updated.

---
## Tasks
- [ ] Update list

## Acceptance Criteria
- [ ] Updated list showing current data / items

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
the file mentioned describes itself as being a stop-gap. should likely come up with a better solution. 

The reason this came up is because of an alert that woke up our team but which was not actionable. 

When a lot of these things were created, there weren't the same infra teams in place that could now better respond to alerts like these.
