### ISSUE TITLE
Separate CC language preference

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15945]
## Issue Description
Currently, the community care provider preferred language selection is on the same page as the provider list. Separate language selection into its own page.

---
## Tasks
- [ ] Remove language selection from CC provider list page
- [ ] Create new language preference page

## Acceptance Criteria

- [ ] Update is behind VA Online Scheduling Provider Selection feature flag 
- [ ] Given required provider preferences are entered, When the user clicks/taps Continue, Then show preferred language selection
- [ ] If user doesn't select a language then clicks/taps Continue, show error
- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
- CC provider list page: [Mobile](https://adhoc.invisionapp.com/share/Y5ZLZ4QTAGX#/screens/439406926), [Tablet/Desktop](https://adhoc.invisionapp.com/share/Y5ZLZ4QTAGX#/screens/439406928)
- Preferred language page: [Mobile](https://adhoc.invisionapp.com/share/Y5ZLZ4QTAGX#/screens/439406927), [Tablet/Desktop](https://adhoc.invisionapp.com/share/Y5ZLZ4QTAGX#/screens/439406929)

**Comment by laurenernest** [comment]
@mnorthuis This ticket (part of the [community care provider selection update](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14654)) will be splitting content from one page into two. Did you have any IA input you'd like me to include?

Here's a visual to better show the change. A is the MVP, and B would be an iteration.
[https://app.zenhub.com/files/133843125/60cb4fc8-cb59-4f43-89f2-fba3d5f032b0/download](https://app.zenhub.com/files/133843125/60cb4fc8-cb59-4f43-89f2-fba3d5f032b0/download)

**Comment by mnorthuis** [comment]
Hi @laurenernest!  Thank you for checking in on this!  I generally assist with URLs for the initial form URL (i.e. up to /introduction), but once you are in the form, the teams generally decide that last URL slug based on the intent of the page. We haven't established standards or guidelines for this quite yet, but I would recommend keeping it as short (1-2 words), simple and plain language as possible. Once the content is finalized, you can queue off the title or primary action of the step (i.e. /select-provider).    These pages are not the focus of SEO, so we just want the URL to be readable and understandable for what they are being asked.   

As far as the flow, does the language selection have an impact on the provider selection?  In other words, if they select a language, should their options on the provider selection be limited by that?

Please let me know if there's anything else you'd like to discuss

**Comment by laurenernest** [comment]
@mnorthuis Thanks for the info!
The language doesn't have any impact on the list in the UI. It's information that's passed in the appointment request. That's part of the reason for moving it; to help avoid that confusion.

**Comment by outerpress** [comment]
Mockups showing the separate language page: https://adhoc.invisionapp.com/share/Y5ZLZ4QTAGX

**Comment by narin** [comment]
Verified on staging.  Closing out.
