### ISSUE TITLE
Search on site for links to our tier 1 change address page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15958]
## Issue Description
Now that we have an R&S page with info for changing your address, we have updated information on our Tier 1 Change Address page. We are also removing the departmental contact info from this page. This work is reflected in ticket #15088. 

We need to comb through our site to see if there are any pages linking to the tier 1 Change Address page where we reference the departmental info. If we find any, we need to change the link to point to our R&S node instead.

## Tasks
- [x] Search site for references to Change Address page (Randi)
- [x] If we are linking to the page because of the departmental contact info, update to link to the R&S Change Address page instead. (Randi)
- [x] Publish pages with changes (Randi)

## Acceptance Criteria
- [x] Live pages updated with new links
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
I updated the following pages and set to publish. All the links now say "Change your address in your VA.gov profile" 
- https://www.va.gov/find-forms/ 
- https://www.va.gov/records/get-military-service-records/ 
- https://www.va.gov/va-payment-history/ 
- https://www.va.gov/pension/ 
- https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

FYSA @bethpottsVADEPO 

Moving to validate and will close after the deploy. FYSA @brianalloyd

**Comment by RLHecht** [comment]
These changes are all live on the site. Closing ticket. FYSA @brianalloyd
