### ISSUE TITLE
Resources and Support: Decision reviews chart

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#15957]
### Issue
Fred Somers, our decision reviews SME, has requested that we include a page like https://www.va.gov/resources/what-your-claim-status-means/ for decision review options. It should clearly show:
- Each type of decision review request a Veteran can make
- What happens if the request is granted
- What happens if the request is denied and what options the Veteran has at that point

### Tasks
 
- [ ] PW to develop draft content in Word doc (Laura)

 - [x] PW to copyedit draft (Randi)

 - [ ] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [ ] Copy deck ready for DEPO/SME review and attached to a content review GH ticket. (Laura)

**Comment by lwalsh617** [comment]
@RLHecht - Beth has provided her feedback and I made revisions, so this is ready for you to review (version 4, dated 11-17-20)
[rs-1.1-decisionreviews-copy-v4-11-17-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5553894/rs-1.1-decisionreviews-copy-v4-11-17-20.docx)
 Thanks!
@bethpottsVADEPO - FYI, under **Legacy Appeal**, **Please review your SSOC,** I couldn't change it to active voice. Evidence could have been added by VA or VSO, not just the Veteran.

**Comment by RLHecht** [comment]
@lwalsh617 Here's the word doc with my edits. Minor tweaks and I had one question that I put in the comments. 
[rs-1.1-decisionreviews-copy-v4-11-17-20.-RH-editdocx.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5556463/rs-1.1-decisionreviews-copy-v4-11-17-20.-RH-editdocx.docx)

**Comment by lwalsh617** [comment]
The work on this ticket is complete. I created a new ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/16351) to cover this page being built in Drupal and shared with SMEs.
