### ISSUE TITLE
Content changes to two gulf war illness disability pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15950]
## Issue Description
Stakeholder Paul Schute has requested content changes to two hazardous materials exposures pages:
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-southwest-asia/
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-afghanistan/

Currently the way content is worded it indicates that a Veteran needs a medical link between their presumptive condition and their military service. His office has provided wording that Beth will need to rework into Plain Language before being put on the page. 

Drupal nodes to work on: 
preview-prod.vfs.va.gov/preview?nodeId=884
preview-prod.vfs.va.gov/preview?nodeId=885

---
## Tasks
- [x] Rework SME content into Plain Language (Beth)
- [x] Send to SME for approval (Beth)
- [x] Update pages with approved text (Randi)
- [x] Review and publish pages (Randi)

## Acceptance Criteria
- [x] New content is on live pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Email sent to stakeholders on Friday with this reworking of the page. Waiting for feedback or thumbs up. [https://app.zenhub.com/files/133843125/7d8f6b7f-b1ad-4ff2-b3c2-c06d2b9215a0/download](https://app.zenhub.com/files/133843125/7d8f6b7f-b1ad-4ff2-b3c2-c06d2b9215a0/download)

**Comment by bethpottsVADEPO** [comment]
Edits approved by VBA SME Keith Hancock. Rework the existing "Gulf War Illnesses linked to SW Asia service" page to incorporate these changes:

[https://app.zenhub.com/files/133843125/d9fb748d-20fc-450a-9807-a545cf1e8a5e/download](https://app.zenhub.com/files/133843125/d9fb748d-20fc-450a-9807-a545cf1e8a5e/download)

Next step is to edit similarly for the parallel page: Gulf War Illnesses linked to Afghanistan service.

**Comment by bethpottsVADEPO** [comment]
@lunascoop @RLHecht Edits for the Gulf War page about SW Asia service (linked to above) as well as the one for Afghanistan are both ready to incorporate. Here's the Afghanistan one:

[https://app.zenhub.com/files/133843125/9120feb1-7b22-4f91-8ecd-87e7052ede50/download](https://app.zenhub.com/files/133843125/9120feb1-7b22-4f91-8ecd-87e7052ede50/download)

Please ping me when you're done making changes and copyediting, so I can have a final look! Thanks.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Are you done making these updates? I saw in a slack up that you worked on them, but not sure if you're done. Thanks!

**Comment by lunascoop** [comment]
@bethpottsVADEPO I've made the updates to both pages.

- preview-prod.vfs.va.gov/preview?nodeId=884
- preview-prod.vfs.va.gov/preview?nodeId=885

**Comment by RLHecht** [comment]
@bethpottsVADEPO I did a copyedit on both of these pages and just made minor copy tweaks. Let me know if you want to review again or they are ready to publish.

**Comment by bethpottsVADEPO** [comment]
@RLHecht These 3 question need to be added back in to http://preview-prod.vfs.va.gov/preview?nodeId=884. They weren't in the Word doc Selina used to make edits. The stakeholder hadn't included them since he had no edits to these 3 Q&As. But the intention wasn't to delete them. Can you add them back in?

**What kind of disability benefits can I get?**

Health care
Compensation (payments)

**How do I get these benefits?**

You’ll need to file a claim for disability compensation.
Find out how to file a claim for disability compensation

**What if I need help filing my claim?**

You can get help from a trained professional trusted to help with VA-related claims.
Get help filing your claim

**Comment by RLHecht** [comment]
Questions were added back in to both pages and published. They are now live. Closing ticket.
