### ISSUE TITLE
[OS Check] Discuss with CMS Team a strategy for making sure that their cms-test nodes do not trigger OS Check alerts

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#15954]
## Issue Description
CMS-test and tugboat nodes triggered a couple OS Check jobs in prod and staging envs. This triggered a quick conversation with the CMS infrastructure team. Due to the nature of how the CMS-test and tugboat nodes are deployed / used, it is likely they will continue to trigger the OS Check jobs. Work with the CMS team to determine a strategy for updating the nodes so they do not trigger the alert, (or modify Ansible code to allow longer thresholds for CMS nodes?)

---
## Tasks
- [x] Discuss with @ElijahLynn and @olivereri a strategy for making sure these nodes are updated and not presenting security issues
- [x] Explore the possibility of changing thresholds (in a reasonable manner) so that the CMS team has more time to update these nodes

## Acceptance Criteria
- [x] OS Check jobs no longer failing due to cms-test nodes
- [x] OS Check jobs no longer failing due to tugboat nodes

**Comment by ElijahLynn** [comment]
Agreed on creating and including cms-test nodes in an "excludelist" for this check. We have a story to spin these nodes down when not in use but haven't gotten to it yet. Maybe use a regex check on the "name" tag and look for "test", then others can use this feature with existing tag structure too.

**Comment by jbritt1** [comment]
Edited to include tugboat instances which are another component of cms deployments.

**Comment by dginther** [comment]
Running the OS Check job is an important part of maintaining the security and reliability of our overall system, we want to continue running this on _all_ nodes in our environment, so we need to find a way to honor that, while also allowing for CMS nodes to be somewhat 'different'.

**Comment by jbritt1** [comment]
Pull request made that solely ignores cms-test instances for the ASG check, but leaves those nodes for the overall security checks.
