### ISSUE TITLE
MVI to MPI rename + Caching

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#15955]
## Issue Description
[This change](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14738)  had to be reverted on 11/4 due to redis caching of MVI::Responses::FindProfileResponse
vs MPI::Responses::FindProfileResponse: https://github.com/department-of-veterans-affairs/vets-api/pull/5223

https://dsva.slack.com/archives/CBU0KDSB1/p1604514730074600
https://dsva.slack.com/archives/CQHBJ5U06/p1604507598335500

As a result, we need to re-update the MVI namespace in /lib to match the new name Master Person Index. This is renaming the directory and then updating MVI namespace modules to MPI. After the change is deployed, we need to clear the cache for the mvi_profile_response namespace `Rails.cache.clear(namespace: 'mvi_profile_response')` so that no old MVI::Responses::FindProfileResponse objects are hanging around in the cache

---
## Tasks
- [ ] Revert #5223 (the revert of the revert change)
- [ ] Run specs locally
- [ ] Clear the dev, staging and prod cache for the mvi_profile_response namespace
- [ ] Test by logging in as a user in dev/staging before the change goes out, clear cache and test that user login still works
