### ISSUE TITLE
Review & discuss approach to language toggle with seoURL

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#15967]
## Issue Description
Review and discuss approach to language toggle with seoURL. Learn from the COVID-19 screening tool translation effort and engineering feedback.

---
## Tasks
- [ ] Share current work-in-progress approach
- [ ] Discuss and gather information from COVID-19 screening tool
- [ ] Capture actionable information for next steps

## Acceptance Criteria
- [ ] Review and discussion complete, actionable info to inform next steps captured
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Relevant issues:

- [#15568](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15568)
- [#15728](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15728)

Hi @batemapf. As I mentioned, I wanted to connect you with @youngfreezyVA, our engineer who is working on the localization effort. He's done some work to date, but would like to learn from your efforts on the screener and feedback from platforms engineers on that work. 

Fareez, feel free to add information and/or questions for Patrick here. I'll also look for some time on our calendars this week to connect on this. Thanks to you both!

**Comment by youngfreezyVA** [comment]
> Relevant issues:
> 
> * [#15568](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15568)
> * [#15728](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15728)
> 
> Hi @batemapf. As I mentioned, I wanted to connect you with @youngfreezyVA, our engineer who is working on the localization effort. He's done some work to date, but would like to learn from your efforts on the screener and feedback from platforms engineers on that work.
> 
> Fareez, feel free to add information and/or questions for Patrick here. I'll also look for some time on our calendars this week to connect on this. Thanks to you both!

hi @batemapf nice to "meet" you & I look forward to connecting. 

my biggest question right now with the existing architecture is how graphQL and the drupal CMS would talk to one another... as we are currently fetching all FAQ content through graphql, and the CMS returns an `entityURL` for each entity, I think it would make sense for the CMS to retain control over constructing the seo friendly url for translated content... i think we would just have the cms accept a language parameter from the graphQL call, which would allow the CMS to talk to the google translate API.

look forward to discussing further.

**Comment by youngfreezyVA** [comment]
working Google API translation queries using postman:

https://drive.google.com/file/d/1oB_20nqQBohXZ8y-ZVlP3WJplIZKxJEg/view?usp=sharing

**Comment by DanielleThierryUSDSVA** [comment]
## Notes from 11.13.20 meeting
@batemapf @youngfreezyVA feel free to add/change anything.

For long-term localization, we definitely need machine translation as part of the process in order to make translation sustainable across a large number of pages that are frequently updated. And we need to work with content in the CMS, as that is where our content authors will be creating English content. For the initial coronavirus content effort, integrating Google translate API is complicated by Drupal constraints and possibly with getting approval to use the API. 

We have 3 different goals for localization:
1. Provide accurate, high quality coronavirus content in Spanish as soon as we can (new goal is January 20, 2021 or sooner)
2. Gather analytics and user feedback (we want to have a unique url for this page to help us understand user intent re: how many people toggle from the English page vs. come to the Spanish page via search)
3. Test a sustainable solution for broader, longer-term localization 

To meet these 3 different goals, we may need to take one approach with the coronavirus content to focus on goals 1 and 2, and another with less visible/critical content to focus on 3. 

We want to explore different potential options for the coronavirus content that is currently housed in Drupal, including:

1. Creating a separate Spanish node in Drupal for each of the 2 coronavirus pages we'll be translating (va.gov/coronavirus-veteran-frequently-asked-questions/es and va.gov/coronavirus-research/es), and adding an href link to each page that acts as a toggle to bring the user to the Spanish/English nodes. For the Spanish node, we don't know if we can integrate an API call (with post-editing) or if we'll need to add/update the translated content manually. 

2. Pulling the content for these 2 pages out of Drupal for now, and moving them to https://github.com/department-of-veterans-affairs/vagov-content. This would give us greater freedom in adding a toggle and potentially integrating an API. Again, we may need to start with manual translation.  

In addition, we want to continue conversations with the broader team around longer-term solutions and potential tools and processes.

Next steps:

- Fareez to connect with CMS team re: option 1 and do more technical discovery work on 1 and 2
- Danielle to work with VSP to schedule product kickoff 
- Team to continue exploration and discussions around potential tools, processes, and translation services

**Comment by youngfreezyVA** [comment]
@DanielleThierryUSDSVA re: the Spanish node and for option #1... we could create a liquid filter to make a google translate API call and map the english nodes to Spanish nodes with the google translate API response. that would all happen on the front end though and doesn't seem like an ideal solution, but it would definitely work for the MVP.

my question for @kevwalsh is whether or not we can make a google translate API call from within the drupal CMS, instead of having the front end make that call, and if there's anyway the front end can trigger that API call (whether via a liquid filter or some sort of broadcasted event or callback). we can discuss further on our call, but that's the main question I have at this point :)

**Comment by youngfreezyVA** [comment]
hey @DanielleThierryUSDSVA had a great convo with @kevwalsh  this AM and this was the summary re: Coronavirus FAQ MVP:
- [ ] Spanish node in Drupal CMS (with Google Translate API call) won't be possible before inauguration. Want to do this the right way, and it would add a layer on top of all CMS calls.
- [ ] Spanish node without google translate / static content can be spun up today
- [ ] Fareez proposes adding a feature toggle to try to map English nodes to Spanish on the frontend with google translate API, and if the results aren't translated well (manual intervention) fallback to Spanish node in CMS

Open questions:
- [ ] LOE to integrate Google Translate API in vagov.content repo 

I think we'll need issues/tickets to track the above work :)

**Comment by DanielleThierryUSDSVA** [comment]
Posting here as follow-up to slack: Thank you, @youngfreezyVA. It's great to know that we have these 2 options. Not being able to have a translator post edit is a big concern from a quality/accuracy standpoint (same concern we had with the widget). Would love to look into that more to find out if there's a way to edit w/ the advanced version. Let's sync more tomorrow.
