### ISSUE TITLE
Recommendations for "debt" in url/h1/intro

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#15961]
## Issue Description
We need to consider whether to remove the word "debt" from the url, h1, and/or text of our section on debt management. The concern is that "debt" has negative connotations for many people. 

---
## Tasks
- [x] Keyword research
- [x] Landscape analysis of how other .gov sites talk about benefits and debt
- [x] Prepare recommendations for discussion

## Acceptance Criteria
- [x] Recommendations provided for review and discussion with SMEs
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. Here are recommendations for review/discussion. Feel free to reach out with any questions!
[VA.gov debt management language recommendations 11.9.20](https://app.zenhub.com/files/133843125/1490ab81-afa5-4011-9bae-e78a0cb6a4ad/download)

cc @mnorthuis

**Comment by leahkeeler** [comment]
cc: @3obryandogs Susan, this is relevant for content Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. Have we heard back from the stakeholders on these recommendations? 

cc @mnorthuis

**Comment by 3obryandogs** [comment]
Danielle,
Leah may have more information, but I believe the content is being worked into the form. DMC prefers “request” rather than “application” or “form,” which was good to know. “Debt” is being reworked as “overpayment” or “repayment” depending on the sentence.

Thank you for your help on this project!

Susan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @3obryandogs. Yes, I also recommended "request" in my edits to the FSR content since they're not really applying for anything here but rather asking for help. Please let me know if you have any questions about any of my other edits.

@leahkeeler, could you give @mnorthuis and I an update on where we're at overall on these recommendations? This has implications for SEO, future URL state, etc.  so we'd like to make sure we're aware of and can best help support the conversation as it unfolds. Thanks!

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA I wish I had an answer for you - they are supposed to have a couple of meetings and let me know - I don't think we will have an update until Thursday at the earliest :(

**Comment by DanielleThierryUSDSVA** [comment]
No worries at all, @leahkeeler. Just keep us n the loop as you know more, and let us know how we can support. Thanks!
