### ISSUE TITLE
Add content about STEMtext to Edith Nourse Rogers page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#15968]
## Issue Description
Per stakeholder Tammy Hurley, we need to add content to the [Edith Nourse Rogers STEM Scholarship page](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/) about STEMtext.

Tammy Hurley provided text, but Beth needs to edit for Plain Language and assess for accessibility. 

Original text:

What is STEMtext? 
As a Rogers STEM Scholar, you will receive an initial opt-in text message to your primary phone number asking if you would like to participate in STEMText. If Rogers STEM Scholars opt-in to the program, you will receive text messages each month to verify your attendance. Watch this video to learn more about the STEMText program.

Drupal page to work on: preview-prod.vfs.va.gov/preview?nodeId=6860 

---
## Tasks
- [x] Rework content so it's Plain Language (Beth)
- [x] Send to SME for approval (Beth)
- [x] Add approved content to page (Randi)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] STEMtext info is on live page.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
I conferred with Jennifer Strickland, and learned that this video isn't compliant because there's no transcript. Sent Tammy this email on 11/16:

Hi Tammy,
You’ll need to reach out to the team that created this video and ask them to address an accessibility issue before we can link to it from VA.gov. According to our accessibility specialist, the video needs a transcript to communicate the content for non-sighted users. They can work with the VA 508 office on this. There are two ways to go about providing it to users:
* Include the transcript in the text area of the YouTube page, or
* Next to the video link, provide a “Download a transcript of the STEMText video (format)”

When this is addressed, let me know and we’ll work the Q&A onto the page.

 I have one question for you: how do Veterans currently verify their attendance? There will just be some minor edits to the text to explain that this is another way to verify attendance.

Beth

**Because this work will now pause until this accessibility issue is resolved, I'm going to put this issue in backlog.**

**Comment by bethpottsVADEPO** [comment]
Sent this to PL version Tammy Hurley on 11/30:

**What’s STEMText?**

We use STEMText to communicate with you about your VA STEM benefits through text messages.

If you have a STEM scholarship, we’ll send an opt-in text message to your primary phone number. We’ll ask if you’d like to receive updates about your VA STEM benefits by text message. To participate, respond “yes” within 7 days of receiving this message.

You can also use STEMText to verify your attendance each month. Verifying by text instead of email can help you get your housing payments faster. We’ll send you a text message each month asking if you attended your STEM courses. To verify, just respond “yes.”

[Go to our STEMText video] to learn more.

**Note:** If you need to update your primary phone number, call us at 888-442-4551. We’re here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET. If you have hearing loss, call TTY: 711.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I added the STEMtext info to the page as the last question. The only change I made was adding (YouTube) after the video link. It's saved as draft and ready to publish when we get the green light.

**Comment by bethpottsVADEPO** [comment]
@RLHecht This is the final text to use, placed as the second Q&A under "More questions about the Rogers STEM Scholarship":

**What’s STEMText?**

We use STEMText to communicate with you about your Rogers STEM Scholarship benefits through text messages.

If you receive the Rogers STEM Scholarship, we’ll send an opt-in text message to your primary phone number. We’ll ask if you’d like to receive updates about your VA STEM benefits by text message. To participate, respond “yes” within 7 days of receiving this message.

You can also use STEMText to verify your attendance each month. Verifying by text instead of email can help you get your housing payments faster. We’ll send you a text message each month asking if you attended your STEM courses. To verify, just respond “yes.”

[Go to our STEMText video] to learn more. @RLHecht link to: https://www.youtube.com/watch?v=diBCc8lQcis&feature=youtu.be

Note: If you need to update your primary phone number, call us at 888-442-4551. We’re here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET. If you have hearing loss, call TTY: 711.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I moved the order of the question so it's now second. It's ready for you to look at.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
