### ISSUE TITLE
Explore Google translate API capability with language toggle & SEOurl

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#15970]
## Issue Description
As a team that manages a large volume of frequently updated digital content, we will need a combination of machine translation + translator post-editing to effectively manage localization in the long-term. We'd like to begin to explore Google API's capabilities in combination with a language toggle & SEOurl approach.

Relates to issue [#15728](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15728)

[Info to date on Google translate API](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ef5c1691639d052f6852cf19c53a57be5a5ab15c/products/content/spanish-translation/coronavirus-mvp/google-translate-assessment.md#google-translate-api)

---
## Tasks
- [ ] Explore capabilities
- [ ] Document findings 

## Acceptance Criteria
- [ ] Capture documentation on findings
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @youngfreezyVA. I created this issue based on our chat on Friday. Feel free to add/change things as you see fit. Thanks!

**Comment by youngfreezyVA** [comment]
https://drive.google.com/file/d/1oB_20nqQBohXZ8y-ZVlP3WJplIZKxJEg/view?usp=sharing

**Comment by mchelen-gov** [comment]
@youngfreezyVA Nice! Can you commit those queries someplace like `va.gov-team` repo?

**Comment by youngfreezyVA** [comment]
thank you.. i'd be happy to commit these queries... I had an access key for the api not sure where that should go exactly. where in the repo would you suggest putting the query? thanks :)
