### ISSUE TITLE
Remove autogenerated "Download" from PDF links

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#15972]
## Issue Description
Quick start guide PDFs that are featured on the Welcome Kit page have just been uploaded to the CMS so they don't need to be updated in github anymore. But a PR on October 1 introduced the word "Download" before the name of a PDF. We need to remove that autogenerated word to address repetitive language and icon. 

### Undesired "Download" 
Eg  https://www.va.gov/welcome-kit

![Digital_Service___VA___Slack](https://user-images.githubusercontent.com/643678/98584502-f7ed6800-2293-11eb-9cea-0a66434bce1f.jpg)

### Double "Download" string

Eg  https://www.va.gov/pittsburgh-health-care/university-drive-campus-map/
![VA_Pittsburgh_Health_Care___University_Drive_campus_map](https://user-images.githubusercontent.com/643678/98584934-85c95300-2294-11eb-9d85-f97b63908c35.jpg)

---
## Tasks
- [ ] Keep the icon. Place "download" in an aria label.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Closing this, "download" has been removed.
