### ISSUE TITLE
Replace Expiring SSL Certificate for www.va.gov

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#15979]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The SSL certificate for www.va.gov expires January 18th. 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
see https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md

## Definition of Done
- [ ] cert is replaced at the TIC
- [ ] cert is replaced on the revproxy alb
- [ ] cert is replaced in the revproxy

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
