### ISSUE TITLE
Error Message: Upstream Appointment Error

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15974]
## User Story
As a user, if one type of appointment is successfully fetched but another kind is not, I want to see a message explaining that the app will display some appointments and not others. 

## Technical Context
VA and Community Care appointments are fetched from two different services - and are then merged - so it’s possible one could be down and the other still up.

## Tasks
- [x] Audit VAOS on VA.gov / reach out to VAOS folks to determine if there is an existing error for this
- [x] UI design 
- [ ] Add documentation to the body of this ticket for front-end
- [ ] Loop in VSP content review if needed

## Invision Link
https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439368937/preview?scrollOffset=5741

## UX Documentation
**common component:**
App Background color: #F2F2F7
Border-left: 8px, variable, Warning: warning-message #fac922
Text (Headline): Mobile Body Bold (optional)
Text (Body): Mobile Body
Text color: gray-dark #323a45
Background color: variable
Internal padding: 20px top & bottom; 10px left & right
Margin: standard gutter L/R; marginBetween vertical
Optional ClickForAction button at the bottom

**Content Language:**
Title: We can't load some of your VA appointments
Body: We are only able to load some of your VA appointments right now. To get information about upcoming appointments you don't see here, please call your medical facility.
![Appointments: Upstream error.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/29344361-7785-432e-a39c-6091484a56e5)

**Comment by msmanak** [comment]
Spoke with Peter from the VAOS team. Their current model is that they do not separate CC and VA hospital appointment error states so if one is missing it will be a generalized message stating that not all appointments will be displayed. I asked if this could change in the future as they are revamping their scheduling and it's not in their pipeline. He will send me the screenshot of the error state for the general appointment from development.

**Should I proceed with this information as a general error or do we want to continue investigating if that it should be separate? @bridgethapner**

**Comment by msmanak** [comment]
![Screen Shot 2020-11-18 at 3.20.15 PM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/dbe4d141-f57a-4f73-8119-412160ac2825)![appointments- Upstream.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/624550d3-09e0-4f82-bfc1-76521449c29d)

**Comment by bridgethapner** [comment]
Really like the idea of including a phone number here! But I don't think the help desk # that VAOS features would be able to give a Vet information about appointments if the appointments aren't loading on VA.gov. Maybe we can direct Vets to call their Medical Center (VA or otherwise) as the quickest solution? 

I think we should also clarify the copy here that we can load some upcoming appointments, but not all. Something like:

Title: **We can't load some of your VA appointments**
Body: We are only able to load some of your VA appointments right now. To get information about upcoming appointments you don't see here, please call your medical facility. 

I realize this isn't a perfect solution, but I think it's the clearest escalation point we can offer in this scenario.

**Comment by bridgethapner** [comment]
@msmanak - Just checking in here. Is this story wrapped up?

**Comment by bessgreen** [comment]
@bridgethapner to confirm: will this error state only occur for Upcoming Appointments (i.e. it will not display on Past Appts)?

**Comment by bridgethapner** [comment]
I am pretty sure this is only for Upcoming Appointments because Past Apts come from a different endpoint. @kreek Can you verify?
