### ISSUE TITLE
[FRONT-END] BDD: File Size Limit for STRs Needs to Conditionally Allow for Larger PDFs

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16003]
## Acceptance Criteria
- [ ] Allow PDF uploads up to 150mb _(all other file uploads up to 50mb)_ for all 526 file uploading (Claim Status Tool, BDD, etc.).

## Notes
During UAT, we had a service member with a large PDF (95 MB). Although EVSS is going to do the splitting of the file, our back end has work to do for making sure we allow these file sizes to go through. This story is for our end of the code (separate story for the proxy updates that were part of the previous limitation expansion work).

**Comment by edmangimelli** [comment]
old issue description:
```
## Issue Description
During UAT, we had a service member with a large PDF (95 MB).  Although EVSS is going to do the splitting of the file, our front end needs to accept large STRs.  The front end needs to be able to accept larger files but we don't want to open this up to all of the file uploads.  We are making a executive guess that 150 MB would be large enough (anything larger will likely create more issues on the BE).

---
## Tasks
- [ ] Set max size to 150 MB
- [ ] 526/BDD
- [ ] CST

## Acceptance Criteria
- [ ] Upload a large PDF - EVSS should still reject but for now we just make sure we accept it and our back end tries to submit.
```
Changing it to match the back-end ticket ( #16004 )

**Comment by Mottie** [comment]
This change will require a significant change to the platform code. It currently does not differentiate the type of file being uploaded. If we set the size to 150MB with the current code, it will allow the upload of image and text files up to 150MB instead of only PDFs. We would want to keep non-PDF upload sizes at the current 50MB.

**Comment by meganhkelley** [comment]
Hi @Mottie! A couple questions for you: 

* What is the priority of this for your team? (Must have, nice to have, post-MVP?) 
* When you say "this change will require a significant change to the platform code," do you know where that change would take place? ex. is this part of the forms library and/or design system? Is this a sitewide behavior external to the design system? Is this a FE behavior? If you're not sure the details I can ask my team.

**Comment by Mottie** [comment]
> What is the priority of this for your team?

I'd say it's a fairly high priority since our BDD form asks service members to upload their service treatment records, which in one UAT it was over 90 MB in size. EVSS has already added a method to split large PDFs into 50MB chunks, so everything is ready for us to bump the file upload limit to 150MB.

> where that change would take place?

It would need to happen within the [`uploadFile` action](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src%2Fplatform%2Fforms-system%2Fsrc%2Fjs%2Factions.js#L201). This is where we check the file size, which in this case would depend on the file extension.

It would entail a sitewide behavior change, but it would be limited by the file UI options `maxSize` (global setting) and `fileTypes` (allowed upload types). In our case since it deals strictly with EVSS, we would likely need an additional option, e.g. `maxPdfSize`, which would restrict global behavior.

**Comment by meganhkelley** [comment]
@cvalarida @caw310 passing this to y'all to prioritize. If that's incorrect and it should stay with my team please @ me and add our label back. Thanks!

**Comment by Mottie** [comment]
Done. Uploading 150MB PDFs to 526 & the CST is now available behind a feature flag.
