### ISSUE TITLE
[DISCOVERY] v1 engine

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16013]
## Issue Description
Need to determine the factors and possibility for moving PPMS into a Rails engine 

---

**Tasks**
- [ ] Nail down requirements for a basic engine which can mount to the same routes (no FE changes needed)
- [ ] Determine level of effort
- [ ] Determine who needs to be involved in the conversation for VSP approval and endorsement of code ownership

Acceptance criteria
- [ ] Documentation of the case to be made: why this is needed
- [ ] Meeting is scheduled with VSP to present case and gain approval

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Lance spoke with Michael Fleet and received support for moving PPMS into a Rails engine
