### ISSUE TITLE
[RESEARCH] Vet Center Prototype - non-clients

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16025]
## Issue Description
We need Veteran research to validate the content/structure of MVP pages support Veterans who are learning about Vet Centers or preparing to visit for the first time

## Questions
For desktop and mobile experiences:
- How would non-clients search for a Vet Center?
- Presentation of outstations/community access point
- Does content support the differentiation of Vet Centers?
- Is the information needed to prepare for a visit prioritized in the order displayed?
- What additional information is needed to prepare a Veteran to visit? (what does a new client need to know?)

## Tasks

- [ ] Determine a method for validating the Vet Center prototype with Vet Center clients
- [ ] Create research plan 
- [ ] Create conversation guide 

## Acceptance Criteria
- [ ] Approved research plan and conversation guide to support recruitment of ~10 Veterans
      - Participants should have received counseling/mental health treatment in VA setting (to ensure they are open to a Vet Center experience)
      - Participants should represent a mix of urban/rural, Vietnam/GWOT eras, male/female

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This research to be combined with clients using mobile prototype. Will create new issue.
