### ISSUE TITLE
Accessibility:  Search this area button

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16027]
## Issue Description
In #14872, we re-evaluated the new GL JS implementation against existing accessibility defects and desired behavior. It was determined that the plug-in is not more than a javascript class that modifies styles that do not apply to our implementation. This issue will address some of the individual changes which need to be made. 

This issue will ensure the new "Search this area" button is accessible to those who search using assistive tech. 

---
## Tasks

- [ ] Ensure when the "Search this area" button appears (after the Veteran has interacted with the map), it receives focus 
- [ ] Ensure when the "Search this area" button appears (after the Veteran has interacted with the map), it is announced to screenreaders.
- [ ] Ensure  the "Search this area" button uses the role=alert
- [ ] Ensure the focus moves to the subhead after the search is triggered by the "Search this area button".
- [ ] Ensure the map continues to be displayed  on mobile following a search triggered by the "Search this area button" (it does not default to the list).

## Acceptance Criteria
After the Veteran has interacted with the map, 
- [ ]  "Search this area" button appears and receives focus 
- [ ]  "Search this area" button is announced to screenreaders.

After a search is triggered by the "Search this area button"
- [ ]  the focus moves to the subhead

After a search is triggered by the "Search this area button" on mobile, 
- [ ] the map continues to be displayed (it does not default to the list).

---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Need to validate: 
After a search is triggered by the "Search this area button" on mobile, the map continues to be displayed (it does not default to the list).

All other AC is current functionality after Mapbox version upgrade.

**Comment by mmiddaugh** [comment]
Michael tested in Safari on his iPhone and the map tab remains selected after clicking that.
