### ISSUE TITLE
[FE] Update Phones numbers to be the clinic phone number

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16039]
## User Story
As a veteran, 
I should see the correct phone numbers on the confirmation page 
so that I have someone to call if I have questions. 

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock Up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d0576b5a7ef3eb210)
- [Slack thread](https://dsva.slack.com/archives/C0136TS768M/p1604942655277100)

## Description
On the confirmation and footer, we need to make sure the appropriate data is being populated for both phone numbers. 

The flow: 

If the clinic number exists, use that, 
if that doesn't use the facility locator API to populate the number
If that doesn't return any, don't show anything. 

## Tasks
- [ ] Is that a front end call or a back end call? 
- [ ] .....
- [ ] Create user tests
- [ ] Create e2e tests 
- [ ] Create Pact tests
- [ ] Update relevant documentations

## Acceptance Criteria
> when is the ticket done 
- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by kristenmcconnell** [comment]
I created ticket ##16940 for content to review/create wording for the phone numbers on the "Need Help" section as well as the missing phone number uses case.

**Comment by kristenmcconnell** [comment]
The wireframes have been updated to content's feedback on the confirmation page (for when we are able to get phone numbers and for when we are not).

**Comment by kristenmcconnell** [comment]
The wireframes have also been updated to include the changes to the "Need help?" footer text.

**Comment by mdewey** [comment]
This appointment has clinic number: https://staging.va.gov/health-care/health-questionnaires/questionnaires/answer-questions/introduction?id=195bc02c0518870fc6b1e302cfc326b61

This appointment has not clinic number but has a facility number: https://staging.va.gov/health-care/health-questionnaires/questionnaires/answer-questions/introduction?id=195bc02c0518870fc6b1e302cfc326b59

**Comment by kristenmcconnell** [comment]
The confirmation page looks good for both "This appointment has clinic number" and "This appointment has no clinic number, but has a facility number."

On all the other forms pages, a period is missing after the phone number. That goes for both use cases that you listed.

Can I also see a facility locator example?

**Comment by kristenmcconnell** [comment]
I just reread the description. If there is no facility number, then there is just supposed to be a link to the facility locator tool, so the Veteran can look information up themself.

**Comment by mdewey** [comment]
I will the period in the ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19019

Here is one without a facility locator. This data will be in staging  when #19019 is in staging. 
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-answer-questions-introduction-2021-01-27-09_11_41](https://user-images.githubusercontent.com/1793923/106003042-ce1c3400-607f-11eb-9abd-f0b9a9a5ce4b.png)
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-answer-questions-review-and-submit-2021-01-27-09_11_58](https://user-images.githubusercontent.com/1793923/106003046-cf4d6100-607f-11eb-8b16-9fb0ffa6d414.png)
