### ISSUE TITLE
[Discovery] Inventory metrics and alarms for Sentry health-checks

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#1604]
## Background
Sentry was basically not sending any events on 09/05/2019 because of a queue overflow - this has occurred in the months following without much real action to address the core issue. 

We should ensure we have proper observability and monitoring for our utility tools such as Sentry.

When the Sentry client fails to receive event data for a suspicious period of time, an alarm should trigger a page to the tools or operations team.

While discovering, keep in mind these eventual requirements: 

-  Metrics are implemented based on Sentry health so we can diagnose issues
- Alarm is triggered to the Triage team when Sentry is not responding.
- Sentry documentation (VSP-facing) includes details on what metrics track Sentry instance health
- A simulated stoppage of events sent to Sentry triggers alarm and page
- Changes are documented and communicated

## Tasks 

- [ ] Research and categorize what metrics are available for us 
- [ ] Document planned approach for implementing alarms based on historical performance
- [ ] Create issues for the implementation of these metrics, alarms, and associated documentation

**Comment by johnpaulashenfelter** [comment]
@kfrz I think there's a lot in Zookeeper/Kafka combo that help prevent this

**Comment by kfrz** [comment]
Yeah looks like 10.0.0 will have some significant improvements to this, will definitely be useful to see what we can leverage and setup Prometheus alarms accordingly. We've previously had hours at a time go by with nobody noticing zero errors were getting into Sentry. 

>  Using the sentry queues list command from above, you can observe the size of the queue (events.preprocess_event). If the queue is large, ensure that there are workers running and that they aren't running out of resources (most likely to be CPU or network I/O). In general, the queues are almost always near zero and **a large value even in the hundreds would be abnormal.**

> https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/sentry#event-flow


Easy enough to trigger that gauge-based alarm!

**Comment by alexpappasoddball** [comment]
Closing for now.  If this happens again we should note it, but Ops would be the owner of this type of work moving forward.
