### ISSUE TITLE
<Content review request for direct deposit pattern> from <Design system team>

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#16048]
### Content support for:
- The design system team is working on a design system pattern for direct deposit information. We took the following pieces of content in our mockups from existing form designs on VA.gov. The design system team does not create new designs we take what is existing and make it reusable for the VFS teams to use. We wanted to ask for a content review because the information surrounding the direct deposit forms seems to differ from form to form. We'd like to have content that could be reusable for each team to establish consistency. 

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [ ] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   This request is related to the direct deposit pattern that exists in a number of forms across VA.gov including forms:
- Application for VA Education Benefits (Form 22-1990)
- Update your Education Benefits (Form 22-1995) 
- File for Disability Compensation (Form 21-526EZ)
- Apply for Education Benefits for VA Education benefits (Form 22-5490)
- Apply for Pension Benefits (21P-527EZ)

* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
- [Design system issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/319)
- [Direct deposit audit](https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1589905726551/ebdfbeaf4c51366902b5109f886ec58e443d1512)
- Proposed design system pattern: (Please accept my zeplin invite over email to see mockup links)
  - [DD pattern empty state](https://zpl.io/VxEQL4k)
  - [DD pattern empty state - additional info displayed](https://zpl.io/aNr5P7e)
  - [DD pattern filled state](https://zpl.io/bArDBRq) 
  - [DD pattern update state](https://zpl.io/aBrdBzA)

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     

- [x] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
  - [DD pattern empty state](https://zpl.io/VxEQL4k)
  - [DD pattern empty state - additional info displayed](https://zpl.io/aNr5P7e)
  - [DD pattern filled state](https://zpl.io/bArDBRq) 
  - [DD pattern update state](https://zpl.io/aBrdBzA)

        

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* <Desired/target implementation date>
We want to release this pattern on 11/23. I'm going to send these mockups to the developer on 11/16
**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *Design system team*
- DEPO product owner: *Kevin Hoffman*
- Product manager: *Carol Wong*
- Designer: *Crystabel Reiter*
- FE engineer: *Chris Valarida*
- Product/team Slack channel: *vsp-design-system*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @CrystabelReiter! Per slack, I'll take a look at this early this week and  get back to you Monday or Tuesday.

**Comment by DanielleThierryUSDSVA** [comment]
@CrystabelReiter - following up from our slack conversations. All other updates are in the mockup. 

For this one: 
![image](https://user-images.githubusercontent.com/62957278/100661865-19d18c00-3322-11eb-85e8-01c03e0aabd5.png)

We recently got updated info for folks who don't have a bank account, which we updated on the static change direct deposit page. So I'm thinking we should update that here and pull it out as its own question if possible.

And then I want to just follow up with our main VBA SME because he'd recently noted some concerns with the Direct Express card.

Proposed updates in Word doc: 
[Direct deposit_11.30.20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5618618/Direct.deposit_11.30.20.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @CrystabelReiter. Heard back from VBA SME. As I'd suspected, they confirmed that, at this time, they do not want to promote Direct Express due to some issues with fraud. So they propose that we **only** go with the VBBP copy. I think we can also keep a modified note re: calling the Treasury Dept. if you don't want to use direct deposit.

Content is below. This should replace all instances of the current content that references Direct Deposit. Just let me know if you have any questions. Thanks!

**What if I don’t have a bank account?**

The [Veterans Benefits Banking Program (VBBP)](https://veteransbenefitsbanking.org/) provides a list of Veteran-friendly banks and credit unions. They’ll work with you to set up an account, or help you qualify for an account, so you can use direct deposit. 

To get started, call one of the participating banks or credit unions listed on the VBBP website. Be sure to mention the Veterans Benefits Banking Program.

**Note:** The Department of the Treasury requires us to make electronic payments. If you don’t want to use direct deposit, you’ll need to call the Department of the Treasury at 888-224-2950. Ask to talk with a representative who handles waiver requests. They can answer any questions or concerns you may have.

**Comment by CrystabelReiter** [comment]
Thanks @DanielleThierryUSDSVA We really appreciate your help on this

**Comment by DanielleThierryUSDSVA** [comment]
Sure, of course! Great working with you on this, @CrystabelReiter.
