### ISSUE TITLE
[FE][BUG?] Save in progress not firing on demographics

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16041]
## User Story
As a Veteran, 
the demographics page should be automatically saving my information, 
so that the system can save my information for later

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mockup](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214b2c6b0442cb3bded9)

## Description
On the demographics page, the Save in Progres system is not being trigger. 

## Tasks
- [ ] Trigger the SIP with the veteran information. 

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
![Screen Shot 2020-12-07 at 4 56 11 PM](https://user-images.githubusercontent.com/1793923/101410277-1eabb800-38ad-11eb-98b3-24fd9a9fd689.png)


Verified in staging

**Comment by mdewey** [comment]
@abuckley3385  I have verified this in stagin. I am clear to close this?

**Comment by abuckley3385** [comment]
yep you can close
