### ISSUE TITLE
"Other nearby VA locations" list on VAMC page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16051]
## Issue Description
The locations listed under "Other nearby VA locations" on the system level [Locations page](https://www.va.gov/pittsburgh-health-care/locations/) are not handled consistently. 

<details>
<summary> Facility type is listed for all locations except Vet Centers </summary>

![image](https://user-images.githubusercontent.com/55411834/98846150-ec24b180-240b-11eb-92aa-004a6379044e.png)

</details>

---
## Tasks
- [ ] Determine if Facility type is an important detail to display on the VA locations list. 

## Acceptance Criteria
- [ ] Display for facilities on VA locations list is consistent. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
