### ISSUE TITLE
Extra padding in some health service accordions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16050]
## Issue Description
Some health service accordions for [University Drive](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/) have extra padding between the `Appointments` and `Care we provide at VA Pittsburgh health care` sections. 

<details>
<summary> Psychology example </summary>

![image](https://user-images.githubusercontent.com/55411834/98844700-f2b22980-2409-11eb-8371-6714e7260943.png)

</details>

<details>
<summary> Expected display </summary>

![image](https://user-images.githubusercontent.com/55411834/98844819-1bd2ba00-240a-11eb-8663-a55c4a7b20db.png)

</details>

Also seen in 

- Audiology and speech
- Critical Care
- Gynecology
- HIV Hepatitis
- LGBT Veteran care
- Military sexual trauma

---
## Tasks
- [ ] Make changes to reflect design system and format across accordions

## Acceptance Criteria
- [ ] Padding is consistent across accordions, consistent with design specs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This will be resolved by https://github.com/department-of-veterans-affairs/va.gov-team/issues/17755
