### ISSUE TITLE
Contact Center Data Request 

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#16068]
## Issue Description
_Many times VFS teams (Content & IA, Product Support, Front End Tools, Analytics & Insights, Back End Tools, Service Design, Identity, Design System, Contact Center, Testing Tools) will request Contact Center Data.  How can we better assist these teams in understanding, requesting, and providing them with the information that they need_

---
## Tasks
- [ ] _Understand if there is a common set of data that VFS teams need._
- [ ] _Create a template that VFS teams can complete in order to request data._
- [ ] _Create a contact center data request label._

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Reached out to Chante to inquire about what kinds of direct data requests she could have received previously.

We want to create a template that VFS teams can use to request contact center data; almost like the Contact Center Review template.

If at all possible, we want to include the following in the ticket:

- What contact centers we can request data from.

- Include what each contact center covers (NCC, MHV, VEO, etc.)

- The timeframe that they are requesting data

- How this information will be utilized (This is up for discussion, it doesn't have to be included)

**Comment by Kimberley2019** [comment]
People are usually curious about a particular benefit or service (i.e. calls about filing a claim or applying for a benefit).


A few things to consider as these requests come in:

- Would it be helpful for teams to get qualitative data in addition to numbers in these requests like a call description or even a call transcript? Obviously not for every single call about an issue but maybe a sample for them.

- It would probably be less important that the team requesting the data know which contact center to ask for data but that they make clear what exactly they are looking for.  From there we can use our expertise to understand which group would be best to reach out to.

- It would be supremely beneficial for us to figure out a way to be given access to additional call center CRMs like we have with the VEO group. It's a tough ask but wonder if it's a conversation we could think about having in this new year.

**Comment by Kimberley2019** [comment]
Review of the #vsp-contact-center-support channel is underway by @edpearson20 to review, record, and understand the requests that we receive in order to develop a ZH ticket template that will encompass the needed information.

**Comment by Kimberley2019** [comment]
@edpearson20 bubbling this back up for your review.

**Comment by Kimberley2019** [comment]
Here are items that I was able to find after reviewing the #vsp-contact-center-support channel:

- https://dsva.slack.com/archives/CNCEXNXK4/p1589292724028200

- https://dsva.slack.com/archives/C1Q4294JJ/p1601489686016200

**Comment by jwoodman5** [comment]
Completed in a separate effort [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5&labels=VSP-contact-center&template=qualitative-data-request.yml&title=Qualitative+Data+Request). Closing.
