### ISSUE TITLE
[UX][Research] Clinician Interview Analysis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#16064]
## User Story
- As a product team and Veteran, we want to better understand the clinician workflow to understand how questionnaires could best be utilized.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A research report detailing findings and design recommendations from the research study.

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [ ] Review all participant session notes and videos
- [ ] Do analysis

## Acceptance Criteria
- [ ] Create research reports/readout documents of findings
- [ ] Update the [research history](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md) document (Does this apply?)
- [ ] Deal with recordings once analysis is complete
- [ ] Discuss strategy impact and/or create necessary issues/tickets that address findings in coordination with Amanda
- [ ] Schedule readout sessions with stakeholders, team, Demos, UX weekly(?)

**Comment by abuckley3385** [comment]
@kristenmcconnell  since you've shared all the notes do we want to close this or are we wanting to do a readout with the team?

**Comment by kristenmcconnell** [comment]
All transcripts and key takeaways can be found at: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/november-2020.
