### ISSUE TITLE
[UX][Research] Interview Clinicians

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#16063]
## User Story
- As a product team and Veteran, we want to better understand the clinician workflow to understand how questionnaires could best be utilized.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Research folder with details on this work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/november-2020)

## Description
We will have met with all clinicians and run the research protocol by the end of this story. Ming will be scheduling all of the sessions.

## Tasks
- [x] Run the sessions with all the clinicians

## Acceptance Criteria
- [x] Gather notes from notetakers
- [x] Download participant videos (if we can record)

**Comment by kristenmcconnell** [comment]
Met with researchers who use eScreening on Nov. 19. Met with BHL Demo on Nov. 23.

**Comment by kristenmcconnell** [comment]
Met with Dr. Byrne on Dec. 3.

**Comment by kristenmcconnell** [comment]
On Dec. 8, met with 2 physicians: an emergency room/Whole Health physician and a primary care physician.

**Comment by kristenmcconnell** [comment]
On Dec. 17 met with a Whole Health clinician.

**Comment by kristenmcconnell** [comment]
@abuckley3385 My documentation of these interviews can be found at https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/november-2020. I'm still working on the documentation/report though.
