### ISSUE TITLE
Technical Triage Meetings with VFS Teams

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#16067]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x] _A meeting will need to be held with VFS teams_
- [ ] _Discussion will need to be held regarding what techniques are used to figure out issues._
- [ ] _Request access for any systems (front end or back end) in order to be able to fully assist the user experiencing the issue._
- [ ] _Create a QRG (quick reference guide) to follow appropriate steps_
- [ ] _Create a place to house data and results_
- [ ] _Create a close feedback loop mechanism._

## Acceptance Criteria
- [ ] _A better process for our team and VFS teams._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
First meeting will be held Thursday 11/12/2020 with Ervin Pearson, Chante Lantos-Swett, Luke Majewski, John Hashimoto, Mathew Self, Anna Carey, Robin Garrison, Nick Sprinkle, and Kevin Stachura.

I reached out to Luke and this is the dream team he has indicated that needs to be a part of this process.

We have a new team member on our newly formed Contact Center team. :tada: Ervin Pearson is our Senior Technical Help Desk Analyst and I am reaching out to set up some time for us to meet with this team.  We want to better understand the issues that your team has been faced with, the steps that are taken to try to duplicate the error messages, the systems you use, and the steps you take in order to research and/or resolve the issues that you are aware of.

Our goal for his role is to be the intermediary and to try to research and/or resolve issues before sending them to the appropriate product team.  I am wanting to start with your team since many of the issues are related to the Disability Claim Application, Claim Status, or VA Benefit Letters.

**Comment by edpearson20** [comment]
In our initial meeting with the Luke Majewski (VSA Product Manager) provided general information regarding Form 21-526EZ (described as the parent form for all disability forms). _Reference > About VA Form 21-526EZ Reference > https://www.va.gov/find-forms/about-form-21-526ez/_

Luke M. also described BDD (Benefits Delivery at Discharge) and how it relates to VA Form 21-526EZ submissions. _Reference > https://www.benefits.va.gov/BENEFITS/factsheets/general/BDDFactSheet.pdf_

Several other topics around addressing issues presented by Contact Center Agents were discussed as noted below.

- Are there artifacts that need to be created or bullet points for Webpage form completion features?
- Questions or issues related to service treatment upload page? _Reference > https://www.va.gov/disability/upload-supporting-evidence_
- Is there an understanding of the process and procedure of completing the Form 21-526EZ?
- Why and how is the service treatment record, generated by the DoD after separation, important and why is it necessary for claim submission? _Reference > https://www.va.gov/records/get-military-service-records_
- What is the importance of exam scheduling (claimant has to be available for exam within 45 days) _Reference > https://www.benefits.va.gov/BENEFITS/factsheets/general/BDDFactSheet.pdf_

Kimberley D. and I (Ervin P.) were informed that...

1. ...a priority action requested would be in helping his team understand the needs of the Call Center with regard to documentation and other related "knowledge base" material.

Our immediate tasks would be to...

- [ ]...consult the Contact Center and identify what the needs of the team are with regard to knowledge base material
- [ ]...identify the outstanding issues and determine the commonalities amongst the issues
- [ ] ...prioritize the issues based on quantity of common issues
- [ ]...provided knowledge base material addressing prioritized issues

**Comment by Kimberley2019** [comment]
This ticket is partially blocked due to @edpearson20 not having VA access; however, details and information can be gathered.

The process may pivot to be more streamlined with moving forward.

During my meeting with Ervin, we decided to present the following plan to Jason to see if we can keep momentum with this project.

Initially the plan was to present this during our demo, however, the appropriate parties are not present during that meeting.  Jason did inform us during our stand up today that he would try to figure the best platform for Ervin and I to present this process to the right teams.

**Comment by jwoodman5** [comment]
@jwoodman5 to verify the best platform for this demo/mtg.

**Comment by Kimberley2019** [comment]
Once guide is together Jason will share with Leadership at ToT and then share in appropriate channels for review by members.

**Comment by Kimberley2019** [comment]
Currently this is blocked due to @edpearson20 not having access to the VA side of the house as of yet.  Once he has the proper access, we will be able to re visit this.

Once we are able to, the process will start with a smaller team (fewer issues).

**Comment by Kimberley2019** [comment]
Although @edpearson20 now has VA access, the priority is the current SF issues backlog.  This will be reinstated closer to the end of the month.

**Comment by jwoodman5** [comment]
@Kimberley2019 Seems like this has occurred as part of the recent tier 3 VFS trainings. Can you please review/confirm and close this out unless you think there is work outstanding? Thank you!
