### ISSUE TITLE
VA411 IVR Messaging 

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#16062]
## Issue Description
The VA411 number has an IVR that helps direct users to the correct place for getting answers to issues related to the VA. Currently, the IVR does not have messaging for VA.gov issues. The 

---
## Tasks
- [ ] Identify which VA.gov recurring issues could be addressed in an IVR setting.
- [ ] Write the IVR script based on determination of which issue solutions would work well in the IVR format.
- [ ] Share with Tier 1 Contact Center Group for review and approval. 

## Acceptance Criteria
- [ ] Completed script for VA.gov IVR messaging
- [ ] Discussion with Tier 1 Contact Center group to determine when it could be added to the IVR. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@starlow00 attaching a list of the VA.gov issues with their definitions. Please take a look and let me know if you have any questions. 

[https://app.zenhub.com/files/133843125/940a45bb-13c8-4ec2-a59b-70bb2bd21aa9/download](https://app.zenhub.com/files/133843125/940a45bb-13c8-4ec2-a59b-70bb2bd21aa9/download)

**Comment by clantosswett** [comment]
Also uploading email language for some of the major VA.gov issues. Please take a look and feel free to reach out if you have any questions. 

[https://app.zenhub.com/files/133843125/06af00a3-f546-4cdd-96c0-4504c490307c/download](https://app.zenhub.com/files/133843125/06af00a3-f546-4cdd-96c0-4504c490307c/download)

**Comment by starlow00** [comment]
Sent email language edits to @clantosswett on 11/19/20 for approval;

**Comment by starlow00** [comment]
Sent @clantosswett email language draft for approval 11/19

**Comment by starlow00** [comment]
@Kimberley2019 , sharing the first draft of IVR messaging. As per our meeting, this currently only includes information from the email template I audited; you noted that you'll obtain more of the info needed here, and I'll add it to the document.[https://app.zenhub.com/files/133843125/d047f4c0-21da-4da5-ad97-87ae15ceb1ba/download](https://app.zenhub.com/files/133843125/d047f4c0-21da-4da5-ad97-87ae15ceb1ba/download)

**Comment by Kimberley2019** [comment]
@starlow00 thank you for providing this draft.  Upon first review, it appears that all of the necessary information is contained in the messaging, however, I have very little knowledge of the level of detail that should or should not be included in this messaging.

@clantosswett Wondering if you could provide us with any known IVR messaging guidelines that we should be aware of?

I'm reviewing the MyVA411 IVR messaging that Steven has put together and I know that there a few items that list a longer url and some items contain multiple steps for the caller to follow.  Just trying to understand if there should be a limit on url characters, if we should instruct to call a number instead of providing a url (when applicable), etc.

I wasn't too involved in the COVID IVR messaging, so I probably missed out on some information.

**Comment by clantosswett** [comment]
@starlow00 and @Kimberley2019 I went through and made some edits and comments. I think it would be good to bring this up tomorrow to the VEO group tomorrow. Let's not share it out ahead of time but maybe send out after we tell them we have been working on it.

**Comment by Kimberley2019** [comment]
@clantosswett I'm unable to access the link.  I am getting an error 404.

@starlow00 Can you access the link?

**Comment by starlow00** [comment]
@clantosswett Same here, I get a 404.

**Comment by clantosswett** [comment]
Trying again. Hopefully it works this time!

[VA.gov IVR CLS Edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5642770/VA.gov.IVR.CLS.Edits.docx)

**Comment by starlow00** [comment]
Hi @clantosswett. Does this draft look like it's headed in the right direction? I think it addresses more of the basics up front, but I'm still not sure if you want me to go digging for more to fill in secondary branches that apply to the rest after today's addition.

[https://app.zenhub.com/files/133843125/912c4827-cd93-4df3-8d56-f8ac99c65760/download](https://app.zenhub.com/files/133843125/912c4827-cd93-4df3-8d56-f8ac99c65760/download)

**Comment by Kimberley2019** [comment]
@starlow00 The edits that you made and the suggestions that were provided by Chante look good.  

After going through the template, it doesn't make sense to have all of these options listed out for the IVR due to the length URLs or even the amount of steps that need to be taken in order to start or complete the task.

Having a meeting with the VEO Contact Center to see IF this is possible and to understand which messaging would be most beneficial would be the next steps. I will set up a meeting with them in order to present and discuss next steps.

**Comment by starlow00** [comment]
Awaiting VEO meeting to review direction.

**Comment by starlow00** [comment]
Hi @Kimberley2019. Fresh from our grooming session, following up on this to see if you've heard anything, or whether I should follow up with VEO directly. Not sure if this was directly addressed in our last VEO meeting.

**Comment by Kimberley2019** [comment]
@starlow00 I mentioned this briefly in our first meeting that we had with VEO, but did not go into detail.  I can not recall if they mentioned that they are working on an IVR currently or if that was a future effort.

Let's mention it again in our meeting with them next Wednesday to get more color around what they are trying to accomplish.  I think it would be better if we could get our ideas in there from the start.

**Comment by Kimberley2019** [comment]
Blocked until VEO call center fgiures a way to move forward with their current changes.

**Comment by Kimberley2019** [comment]
Will review with VEO once the IVR messaging decision has been made.

**Comment by jwoodman5** [comment]
Need to review again with VEO to get a decision. Add to VEO mtg agenda for 5/5.
