### ISSUE TITLE
Crosslinking to Facility Locator for Vet Centers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16070]
## Issue Description
There is a lack of awareness about Vet Centers among Veterans that could be improved by leveraging opportunities to cross-link from relevant content. We will begin by optimizing existing links. This issue will document these opportunities. 

## User stories
- As a Veteran learning about services on VA.gov, I would like content referencing Vet Centers to link to the Facility Locator so I can find the location nearest to me. 
- As a Veteran arriving on Facility Locator from another VA.gov page, I would like the appropriate facility type to be pre-populated so that I can search efficiently and don't have to remember what to choose. 

## Issues

- Link to Facility Locator from MST page #15873
- Link to Facility Locator from PTSD page #15875
- Link to Facility Locator from Mental health services page #15871

---
## Tasks
- [ ] Submit request to Public Websites for these changes

## Acceptance Criteria
- [ ] Identified existing links will direct to Facility Locator and pre-populate the Facility type. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
Use the PW intake form (https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=DanielleThierryUSDSVA&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+needs-grooming%2C+Epic&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)  as we get these

**Comment by davidmpickett** [comment]
All but one issue is resolved.
