### ISSUE TITLE
[BE] Ensure the appointment data has Facility and clinic phone number. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16085]
## User Story
As Veteran,
I should be able to see the appropriate phone numbers
So that I can call the right people if I need help. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mockup](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214b2c6b0442cb3bded9)
- [Show Facility](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/facilities/showFacility)
- [Facilities by IDs](https://api.va.gov/v1/facilities/va?ids=vha_516GC,vha_516&per_page=2)

## Description
For the `GET Appointment` endpoint at `/health_quest/v0/appointments/{id}`, the facility number and clinic phone number need to be populated. 

- The clinic number should already be in the appointment
- The Facility number can be populated by the facility API. Reach out to VOAS team to see how where they are getting the facility information from , 
If appt. API has phone numbers show, if not get from Facilities API, if doesn't exist in either - don't show (per mockup @kristenmcconnell )
## Tasks
-authentication API? @stephenBarrs 

## Acceptance Criteria
- [ ] All tests passing. 
- [ ] The correct data is populating
- [ ] PR has been merged into master
- [ ] Front end team has signed off.

**Comment by abuckley3385** [comment]
Facility (backup) vs Map (priority) for where getting this data. @stephenBarrs will research

**Comment by stephenBarrs** [comment]
The MAP Mobile Appointment Service (MAS) populates the facility phone number if present in the data returned from VistA.  It is not always present.  

Facility data can retrieved from the Facilities API which is open and requires no authentication. The current version is V1.

Swagger is here:  https://dev-api.va.gov/v1/apidocs

Example Production url is here:  https://api.va.gov/v1/facilities/va?ids=vha_516GC,vha_516

Example data (truncated to include only one site) returned from above example url:
`
{
	"id": "vha_516GC",
	"type": "facility",
	"attributes": {
		"access": {
			"health": [{
				"service": "Audiology",
				"new": 26.477611,
				"established": 2.621848
			}, {
				"service": "Cardiology",
				"new": 5.0,
				"established": 4.0
			}, {
				"service": "MentalHealthCare",
				"new": 7.8,
				"established": 2.612903
			}, {
				"service": "PrimaryCare",
				"new": 31.627906,
				"established": 4.852668
			}, {
				"service": "SpecialtyCare",
				"new": 23.184782,
				"established": 4.444444
			}],
			"effective_date": "2020-11-23"
		},
		"active_status": "A",
		"address": {
			"mailing": {},
			"physical": {
				"zip": "34684-1908",
				"city": "Palm Harbor",
				"state": "FL",
				"address_1": "35209 US Hwy 19 North",
				"address_2": null,
				"address_3": null
			}
		},
		"classification": "Primary Care CBOC",
		"facility_type": "va_health_facility",
		"feedback": {
			"health": {
				"primary_care_urgent": 0.7599999904632568,
				"primary_care_routine": 0.9100000262260437
			},
			"effective_date": "2020-04-16"
		},
		"hours": {
			"friday": "700AM-430PM",
			"monday": "700AM-430PM",
			"sunday": "Closed",
			"tuesday": "700AM-430PM",
			"saturday": "Closed",
			"thursday": "700AM-430PM",
			"wednesday": "700AM-430PM"
		},
		"id": "vha_516GC",
		"lat": 28.092537,
		"long": -82.738017,
		"mobile": false,
		"name": "Palm Harbor VA Clinic",
		"operating_status": {
			"code": "NORMAL"
		},
		"phone": {
			"fax": "727-734-5914",
			"main": "727-734-5276",
			"pharmacy": "888-820-0230",
			"after_hours": "888-820-0230",
			"patient_advocate": "727-398-9524",
			"mental_health_clinic": "727-398-6661 x 14680",
			"enrollment_coordinator": "727-734-5276"
		},
		"services": {
			"other": [],
			"health": ["Audiology", "Cardiology", "MentalHealthCare", "Nutrition", "PrimaryCare", "SpecialtyCare"],
			"last_updated": "2020-11-23"
		},
		"unique_id": "516GC",
		"visn": "8",
		"website": "https://www.baypines.va.gov/locations/Palm_Harbor_Florida.asp"
	}
}
`

**Comment by stephenBarrs** [comment]
We will need to create pact test for the call to the Facility API endpoint.  @dillo

**Comment by mdewey** [comment]
![Screen Shot 2020-12-16 at 10.22.37 AM.png](https://images.zenhubusercontent.com/5ecebb879a043b865f6cb5b6/aefc85c2-1f8f-4c26-b07f-565ad08989c0)

Works for me! Great work!
