### ISSUE TITLE
Fetch CC providers from facilities api

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16091]
## Issue Description
Build the call to fetch community care providers from the facilities api

---

## Tasks
- [ ] Create fetch call to /v1/facilities/ccp
- [ ] Convert lat/long to bounding box using a chosen radius
- [ ] Map the VAOS type of care to a rollup code documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/notes/CCProvider.md)
- [ ] Create mock data if not created already
- [ ] Transform api data into FHIR Location format

**Comment by laurenernest** [comment]
@jbalboni What did the LOE for this end up being? (in points)

**Comment by jbalboni** [comment]
@laurenernest I think a 3, which I've added to this ticket.
