### ISSUE TITLE
ATO - Information needed for all servers on VA.GOV 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16097]
## Issue Description
_TIME-SENSITIVE REQUEST - Information needed by Monday, November 16, 2020 regarding all of the servers on VA.GOV. Details needed for each instance are listed below:_

Hostname (Required) 
IP Address (Required)	
Operating System (Required)	
Location (Required) 	
Environment (Required) 	
SNMP Community String (Required) 
Application Type (Required) 	
SNOW Priority (Required) 
Server (ADA) TCP Port(s)	
Log File Path and File(s) to Monitor	
Custom KPI's 

---
## Tasks
- [x] _Provide the information requested to @fowusu2 by Monday, November 16, 2020_

## Acceptance Criteria
- [x] _Necessary inventory information for VA.GOV servers will be submitted in ATO packet_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ffafara-tw** [comment]
VANotify (deployed to it's own vaec-notify AWS account) is covered by VA.GOV ATO.
Do you need the same information from us?

We use ECS Fargate and do not use any EC2 instances.

**Comment by jsev-io** [comment]
[https://app.zenhub.com/files/133843125/4d9039b8-182f-479d-9b74-9eb41c78564f/download](https://app.zenhub.com/files/133843125/4d9039b8-182f-479d-9b74-9eb41c78564f/download)

@fowusu2 @jhouse-solvd  
Please see attached, zipped, report. I think this should be sufficient. Please let me know if more is needed.

**Comment by jhouse-solvd** [comment]
@fowusu2 - can you please confirm that this issue can be closed?

**Comment by jsev-io** [comment]
@fowusu2 Closing this ticket but feel free to re-open if it's determined it's still necessary.
