### ISSUE TITLE
[BE] Preferred medical facility: Backend build

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#16107]
## Background

We need to allow people to indicate their preferred medical facility in the VA.gov profile so that the VAOS tool can consume this information for a better user experience.

Based on #15722, build needs to include the following:

- Set up preferred storage on the backend
- Create an API for the VAOS team to pull in preferred facility
- Create an api that lets users save their preferred facilities

There is already an API that allows us to retrieve people's facilities from MPI.

## Tasks

- [ ] Set up preferred storage on the backend
- [ ] Create an API for the VAOS team to pull in preferred facility
- [ ] Create an api that lets users save their preferred facilities
- [ ]  Block endpoints so they are not accessible because frontend will not be able to start build right away

**Comment by lihanli** [comment]
@Samara-Strauss is it necessary to block the endpoints on the backend? i don't think there are any security risks associated with this API, it doesn't call any external services

**Comment by Samara-Strauss** [comment]
@lihanli it's probably OK not to if there is no security risk, but I'll leave that up to you. I'd recommend checking with another BE developer who is more familiar with security concerns than me — I don't feel qualified to advise on this one.

**Comment by Samara-Strauss** [comment]
Update: Waiting on PR review in [5396](https://github.com/department-of-veterans-affairs/vets-api/pull/5396).

**Comment by Samara-Strauss** [comment]
@lihanli hello! Can we get an update on this? Was the PR reviewed/approved in the last couple of weeks? I realize this may not have gotten addressed because of break, so just let me know where things are at with this.

**Comment by lihanli** [comment]
@Samara-Strauss the pr hasn't been approved yet, i will ask for another review in the platform channel when slack is back up

**Comment by Samara-Strauss** [comment]
OK, thanks for the update.

**Comment by mshea0606** [comment]
Hey @lihanli, any update on this issue?

**Comment by lihanli** [comment]
@mshea0606 the pr still needs to be approved, i'll ask again in slack

**Comment by Samara-Strauss** [comment]
I nudged as well. There's no reason this work should be still outstanding after a month, even accounting for the holiday break. Hopefully someone can get to it soon.
