### ISSUE TITLE
Document Findings on OGC Data from LH

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16103]
## Background
To be a VSO, you need to be in a the accreditation DB and the OGC manages that data source.  We need to know how performant that data is; EVSS has a cached copy of that probably.  Andrew Fichter (Program Lead at LH) could share with us their copy, where we could integrate with them.

## Considerations
- [Meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/meeting-notes.md)
- https://www.va.gov/ogc/accreditation.asp
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-POA#abstract

## Tasks
- [x] Understand where the data is and how to get access to it
- [x] Discuss with LH about how we might work with them to get access and use that data
- [x] Set up a meeting with Andrew Fichter to discuss further

## Acceptance Criteria
- [x] A meeting with Andrew Fichter has been scheduled or conducted.
- [x] Document in GH the findings from these discussions

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/lighthouse-api-info/README.md
