### ISSUE TITLE
Add connected apps directory article to R&S

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16110]
## User Story

As a Veteran, I want to know what third-party apps I can connect to my VA profile to help me manage my health and benefits.

## Issue Description
The Lighthouse team has created a mockup and react widget for a connected apps article in R&S. This will use the "about" template (learning center detail page). Please refer to the [mockup in the intake request](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14279) for draft intro and button content and work with the team on any needed edits. And please check in with the team to get the code for the react widget.

---
## Tasks
- [x] Review content and work with team on any needed edits
- [x] Create R&S article and add react widget
- [x] Validate and publish

## Acceptance Criteria
- [ ] App directory article is live in R&S
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @brianalloyd. Could you please work with the team to add this to R&S? Please reach out to @ricetj with any questions. Thanks!

**Comment by RLHecht** [comment]
Thanks, @DanielleThierryUSDSVA I'll take a look at this.

**Comment by RLHecht** [comment]
@ricetj Could you please give me the react code for the widget on this page? I'm going to set up the R&S template. Thanks!

**Comment by ricetj** [comment]
> @ricetj Could you please give me the react code for the widget on this page? I'm going to set up the R&S template. Thanks!

Hello @RLHecht, I am tagging our FE @LeKeve to provide you the code when he is ready. One question I have is, can we have a demo environment before launching in Prod? We would live to do some testing, before going live.  Thank you in advance.

**Comment by LeKeve** [comment]
@RLHecht 

App directory widget code: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/third-party-app-directory

Widget mount id: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/widgetTypes.js#L22

The widget expects to mount to the id `third-party-app-directory`. Please let me know if you have any questions!

**Comment by RLHecht** [comment]
Thanks, @LeKeve @ricetj It looks like the intro text as well as some other R&S template components are incorporated in the widget. I think we would just need the apps directory to be in it and the other parts we could create in Drupal based off the template (certain elements are required to save the page so we would need to input them anyway). Here's a preview link showing what it currently looks like with the intro I added as well as the widget. 
preview-prod.vfs.va.gov/preview?nodeId=9615.

**Comment by LeKeve** [comment]
@RLHecht Great, thank you!

I can remove the intro text and the CTA buttons from the widget code. 

I noticed in the preview that there is a single CTA button to `Learn more about connected apps`. Is a duplicate button at the bottom of the page required as in our mockups?

**Comment by RLHecht** [comment]
Perfect @LeKeve Nope, a duplicate is not required. We have only been putting it on pages that are somewhat lengthy.

**Comment by RLHecht** [comment]
@ricetj We updated the H1 and intro on this page to align more with our voice and tone. I also removed the wording about the apps being created by non-VA developers and the feature not being a requirement. Can you take a look at the changes and let me know if they are OK? preview-prod.vfs.va.gov/preview?nodeId=9615

**Comment by ricetj** [comment]
> @ricetj We updated the H1 and intro on this page to align more with our voice and tone. I also removed the wording about the apps being created by non-VA developers and the feature not being a requirement. Can you take a look at the changes and let me know if they are OK? preview-prod.vfs.va.gov/preview?nodeId=9615

Hello @RLHecht Is it possible to keep the content the same? There has been a lot of back and forward with this content, and I was under the impression that it was ok as is.

Is it possible to just have this text as the H1/intro on the page, right above the CTA:
```
Find apps to use
Below, you'll find a list of third-party websites and applications you can link to your personal VA data, like health or service records. Third-party services are created by developers that aren't VA. It is never required to use them. 
```

We don't need this part:
```
Apps to connect to your VA profile
You can connect these third-party websites and applications to your profile. When you do this, they'll have access to your personal VA data, like your health or service records.
```

**Comment by ricetj** [comment]
At the very least is it possible to keep the H1 header `Find apps to use` ? We choose that to help with SEO since it will be the URL as well. 

We called out non-VA developers, because there was confusion we saw in research that was conducted around this area. We want to make it clear to the users that the apps that are referred to here are non-Va developed apps.

**Comment by RLHecht** [comment]
I had reworked the first sentences to make them active instead of passive voice and we don't generally start intros with "Below." If we put back the info about non-VA apps, does this language work? I was avoiding the word "developers."

You can connect these third-party websites and applications to your profile. When you do this, they'll have access to your personal VA data, like your health or service records. They're called "third-party" because VA doesn't create these services. And you're never required to use them.

**Comment by ricetj** [comment]
> I had reworked the first sentences to make them active instead of passive voice and we don't generally start intros with "Below." If we put back the info about non-VA apps, does this language work? I was avoiding the word "developers."
> 
> You can connect these third-party websites and applications to your profile. When you do this, they'll have access to your personal VA data, like your health or service records. They're called "third-party" because VA doesn't create these services. And you're never required to use them.

Hello @RLHecht that sounds fine to me. Are we able to keep the H1 the same? `Find apps to use`

**Comment by RLHecht** [comment]
Thanks, @ricetj glad that works! For the H1 can you share the SEO data so we can understand the keywords you're going for?

**Comment by ricetj** [comment]
> Thanks, @ricetj glad that works! For the H1 can you share the SEO data so we can understand the keywords you're going for?

Hello Randi, I do not have a SEO report that I can share. We were trying to use a simple H1/ URL that users looking for apps could find. We didn't want a complex or longer URL. 
CC: @careyotto

**Comment by ricetj** [comment]
There really isn't much data we can go off, so when we thought through the url find apps to use showed some good results when we tested that via an organic search. Plus we are going to try to optimize the SEO in other ways on the page. This page will also be linked to from the connected apps FAQ page and the connected apps profile section.

**Comment by careyotto** [comment]
Additionally, if I recall correctly, `Find apps you can use` is also the call to action (CTA) link we settled on with the authenticated experience team (working with Peggy and Danielle) to use in the Profile 2.0 Connected Apps page. This CTA will bring a Veteran to the app directory page in the learning center. We are also using `Find apps you can use` as a CTA on the Connected Apps FAQ page. 

Keeping the language aligned on all of these touch points will create a stronger, holistic, user experience in this connected apps ecosystem. 

BTW, @RLHecht I like what you did with `They're called "third-party" because VA doesn't create these services.` Makes the point nicely, and as @ricetj mentioned, this is a critical point to get across to our users. Thank you for making that change.

**Comment by RLHecht** [comment]
All valid points. Can we go with "Find apps you can use" instead of "Find apps to use"? That will also match the CTA. 

One other change to the page: There's currently a blue box in the widget under the list of apps. Blue boxes are generally used for our eligibility areas. We'd like to take it out of the widget and I can put it a standard H2 with the text underneath it as a regular content block. 

So for the updated widget we would want only that list of apps and you would remove the H1, intro, CTA button and blue box. Once that's all done I can update the page and it can be ready to go. 

Thanks for working through this with us.

**Comment by ricetj** [comment]
> All valid points. Can we go with "Find apps you can use" instead of "Find apps to use"? That will also match the CTA.
> 
> One other change to the page: There's currently a blue box in the widget under the list of apps. Blue boxes are generally used for our eligibility areas. We'd like to take it out of the widget and I can put it a standard H2 with the text underneath it as a regular content block.
> 
> So for the updated widget we would want only that list of apps and you would remove the H1, intro, CTA button and blue box. Once that's all done I can update the page and it can be ready to go.
> 
> Thanks for working through this with us.

Hello @RLHecht that H1 sounds fine to me, but will ask @careyotto her thoughts. 

As for the changes, we will work to remove those. For the blue box we will just remove that, no need for a h2. (@LeKeve).

**Comment by RLHecht** [comment]
Sounds good. I've updated the H1 and the intro so just let me know when everything else is ready. If you need to do testing you'd be able to do it in the R&S demo environment. We would just need to make sure we had copied over the content from prod first.

**Comment by RLHecht** [comment]
@ricetj Yep, that URL is correct.

**Comment by RLHecht** [comment]
@ricetj What date are you wanting this to go live? Whatever date that is, we just need to make sure the page is published in Drupal before 2 p.m. to make the deployment.

**Comment by ricetj** [comment]
> @ricetj What date are you wanting this to go live? Whatever date that is, we just need to make sure the page is published in Drupal before 2 p.m. to make the deployment.

Hello @RLHecht we want to go live on Friday 20th.

**Comment by LeKeve** [comment]
> Sounds good. I've updated the H1 and the intro so just let me know when everything else is ready. If you need to do testing you'd be able to do it in the R&S demo environment. We would just need to make sure we had copied over the content from prod first.

@RLHecht I've updated the widget code on `master`. Could the demo environment be rebuilt? Thank you!

**Comment by RLHecht** [comment]
@LeKeve The widget isn't showing as updated in the Drupal preview link. Is this because it needs to wait for the daily deploy?

**Comment by LeKeve** [comment]
> @LeKeve The widget isn't showing as updated in the Drupal preview link. Is this because it needs to wait for the daily deploy?

@RLHecht That may well be the case. The daily release was deployed a few minutes ago and after refreshing the preview page I'm seeing the updates.

**Comment by RLHecht** [comment]
@LeKeve I see it now too! I noticed that the text that was in the blue box is no longer there. Should I put that in as rich content on our end?

**Comment by ricetj** [comment]
> @LeKeve I see it now too! I noticed that the text that was in the blue box is no longer there. Should I put that in as rich content on our end?

Hello @RLHecht the current CTA replaces the blue box. We do not want it there anymore, so the current look is correct as is.

**Comment by RLHecht** [comment]
Ah, got it. I am rebuilding the demo environment now and will do a content release so that the page should be ready to view there. Not sure how long it will take but I'll let you know when it's done.

**Comment by RLHecht** [comment]
@ricetj Just giving you an update: We are currently having issues with the demo environment but the CMS team is working on it. I'll let you know once you're able to take a look and test what you need to.

**Comment by RLHecht** [comment]
@ricetj Here's the preview link in the demo environment: http://learningcenter.demo.ci.cms.va.gov/resources/find-apps-you-can-use?_format=static_html

**Comment by ricetj** [comment]
> @ricetj Here's the preview link in the demo environment: http://learningcenter.demo.ci.cms.va.gov/resources/find-apps-you-can-use?_format=static_html

@RLHecht thanks, how do I access this link? What is the different between this link and the other preview one?

Also, another question for you. It looks like in order to get better analytics on the app directory some things need to be added the CSM template. Is this something on your radar already?

**Comment by RLHecht** [comment]
The demo environment is for whatever testing you needed to do since it can't be done on prod. It looks the same as the prod preview. Use this link: learningcenter.web.demo.ci.cms.va.gov/resources/find-apps-you-can-use/

**Comment by ricetj** [comment]
@RLHecht we just had our Staging review with VSP and will be ready to go live tomorrow. Do we need to do anything on our end on getting this to prod or is that something on your end?

One thing Peggy brought up during the review was the content of the descriptions in the learn more section of the apps. This is straight from the different applications and is pulled in via an API.

**Comment by RLHecht** [comment]
I will be able to publish this tomorrow so you won't have to do anything. Does @LeKeve still need to test anything on demo or everything is OK to go live tomorrow?

**Comment by RLHecht** [comment]
@ricetj One request: In the intro, can we add "VA.gov" before "profile? So it would read: You can connect these third-party websites and applications to your VA.gov profile.

**Comment by LeKeve** [comment]
> I will be able to publish this tomorrow so you won't have to do anything. Does @LeKeve still need to test anything on demo or everything is OK to go live tomorrow?

@RLHecht No further testing on demo is needed. However, I noticed that the demo environment is not displaying the updates to the UI that are on `master` like prod preview did.

**Comment by ricetj** [comment]
> @ricetj One request: In the intro, can we add "VA.gov" before "profile? So it would read: You can connect these third-party websites and applications to your VA.gov profile.

Hey @RLHecht sure. I think that makes things more clear.

**Comment by RLHecht** [comment]
@LeKeve Great. Yeah, sometimes the demo doesn't pull the latest from Prod as it should. But what you see on Prod is what will publish so we are OK. @ricetj Great. This will get published today in time for the deploy. It should be live by around 4 p.m. ET.

**Comment by LeKeve** [comment]
@RLHecht Perfect, thank you!

An additional question, I have a UI update and analytics that will be in the daily release of `vets-website` today. Will we need to let you know and have the page republished or am I correct in understanding that it will automatically pull from prod?

**Comment by RLHecht** [comment]
@LeKeve I won't need to republish anything. It should automatically pull from prod.

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close after today's deploy. FYSA @brianalloyd @bethpottsVADEPO

**Comment by ricetj** [comment]
> This page has been published. Moving to validate and will close after today's deploy. FYSA @brianalloyd @bethpottsVADEPO

@RLHecht is the content still on track for going live today?

**Comment by RLHecht** [comment]
Yes, it should be though it doesn't look like any pages that were published today are live yet.

**Comment by RLHecht** [comment]
It's live now! https://www.va.gov/resources/find-apps-you-can-use/

**Comment by RLHecht** [comment]
Page on live site. Closing ticket. FYSA @brianalloyd @bethpottsVADEPO
