### ISSUE TITLE
Add a Link in the Gatsby documentation site’s “Visual Design” section to Storybook documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16118]
## Issue Description
Add a Link in the Gatsby documentation site’s “Visual Design” section to Storybook documentation

---
## Tasks
- [ ] Display message to go to Storybook before we replace the link completely 
- [ ] Add a Link in the Gatsby documentation site’s “Visual Design” section to Storybook documentation

## Acceptance Criteria
- [ ] Message is displayed
- [ ] Link on the page goes to Storybook 
---
