### ISSUE TITLE
Create Documentation On Environments 

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#16115]
Per the discussion [here](https://dsva.slack.com/archives/CQHBJ5U06/p1605207983418300).

## Description
In order to provide clarity to developers and other users of the platform we need to create documentation that describe the differences between all the different environments available on the platform.  This will help ensure teams developing on the platform have up to date information to assist them in development and testing their features.  This will also provide non developers with the knowledge of capabilities and limitations of the different environments.  The environments that need to be documented are:

- Production
- Sandbox
- Staging
- Dev
- Review Instances

## Acceptance Criteria

- [ ] Production Environment Detailed description stored in Confluence
- [ ] Staging Environment Detailed description stored in Confluence
- [ ] Sandbox Environment Detailed description stored in Confluence
- [ ] Development Environment Detailed description stored in Confluence
- [ ] Review Instances Environment Detailed description stored in Confluence

## Decisions

The new documents will be created in Confluence in the following top folder:
https://vfs.atlassian.net/wiki/spaces/pilot/pages/603488279/Environments

**Comment by alexpappasoddball** [comment]
@erluti Lets further discuss this moving into Sprint 40.  And what did I miss?  What other questions do we need to ask.  Anyone should be able to look at these descriptions and understand what, and whom for, those are for.  Feel free to update as you see fit.
@gmaciolek Anything I missed?  Have any thoughts where we should store this for the first iteration?
@drorva just for visibility!

**Comment by erluti** [comment]
@alexpappasoddball turn this into an epic and break out each environment into a task.  Hopefully each task will be short, but there are a lot of open questions for this to be considered one task.

**Comment by drorva** [comment]
1. This will start in Confluence but will end up in Github for now.
1. Let's remember to point to the equivalent doc in the FE if it makes sense.

**Comment by drorva** [comment]
closed cause it's done or cause it was converted into an epic?
