### ISSUE TITLE
Create a workflow for designers updating component documentation Storybook

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16117]
## Issue Description
Create a workflow for designers updating component documentation Storybook

---
## Tasks
- [ ] Discovery of how designers would or should update documentation in Storybook 
- [ ] Document describing the process to update component documentation in Storybook  

## Acceptance Criteria
- [ ] Document describing the steps for designers to update documentation in Storybook

**Comment by cvalarida** [comment]
# The problem
The main struggle I see is getting the editing experience for designers. It's easy to add JSDocs to the component which will show up in the `Docs` page, but that requires designers to edit the comments in the actual source file. Also, that's probably not the best place for the "when to use" kinds of documentation.

## Assumptions
Just to be thorough, I'd like to call out any assumptions explicitly.
- Designers won't want to edit JSDocs in source files to add their documentation

# What didn't work
I looked into the [`storybook-readme`](https://github.com/tuchk4/storybook-readme) add-on, which—I think—translates a `README.md` file that lives next to the component into a separate documentation view in Storybook. The problems I had with this approach:
- The add-on only works for Storybook 5 (I think), but we're on v6
- It would add another documentation view _separate_ from the `Docs` tab, which is likely confusing

I then tried to get the [DocsPage](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md) to render the markdown in a separate file, but had no luck.

# What might work
In the end, I think we have two approaches:
1. Create a separate `.stories.mdx` file that behaves as a story itself
    ![image](https://user-images.githubusercontent.com/12970166/99601947-52ce4000-29b5-11eb-8d1f-2861ff60d4b2.png)
1. Create a single `.stories.mdx` that overrides the default DocsPage whenever we have documentation that needs to be edited by designers
    - This shouldn't be _all_ components, but I expect it'll be a lot
    - The experience is likely to be somewhat weird for designers as it interleaves markdown with actual code
      - [Example](https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#mdx)
    - I wasn't able to get a `.mdx` and `.jsx` to work together except like above
      - This means we'd have to write all our stories in `.mdx`, which I don't love
        - We miss out on using our plugins like Controls, a11y, and HTML
        - Writing stories in these files is clunky

# What I recommend
I recommend we stick with the first one, though it does spread documentation out somewhat awkwardly.

# What I didn't try
There are potentially some other options I didn't try including:
- Writing a custom Storybook add-on to interleave the contents of separate markdown files into the DocsPage
- Forking / contributing to `storybook-readme` to get it working with Storybook 6
- Adding a link from each component (when appropriate) to Jekyll-managed documentation
  - Maybe by writing a custom Storybook add-on
  - Maybe by manually linking from our JSDocs
  - Either way, it's probably manually managed, and thus liable to breaking, but better than nothing if we decide to keep designer documentation in Jekyll
