### ISSUE TITLE
[Discovery] Determine next steps for porting SLO monitors to DataDog

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#16112]
## Background
We will work towards migrating the SLO report for external service performance into DataDog. This requires a bit of discovery as to what metrics we might not have, and how to build custom metrics for SLOs in the DataDog interface.

## Tasks
- [ ] Meet w/ ops and determine what metrics are available/not available
- [ ] Explore requirements for building a custom metric in DataDog

## Acceptance Criteria

- [ ] Issues generated for DataDog SLO work
