### ISSUE TITLE
Update documentation in Storybook that doesn't match Gatsby and design.va.gov 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16116]
## Issue Description
Reconcile the differences between existing documentation in Gatsby & Design.va.gov with documentation in Storybook

---
## Tasks
- [ ] Update documentation in Storybook to ensure all components have complete information and is the same as what is on Gatsby & design.va.gov 

## Acceptance Criteria
- [ ] Discrepancies with documentation identified during audit are addressed. 
- [ ] Component documentation in Storybook matches documentation in Gatsby and design.va.gov 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bkjohnson** [comment]
@cvalarida is this closeable?

**Comment by bkjohnson** [comment]
It doesn't look like there is anything documented in the "Visual Design" section of the gatsby site or the "Components" section of design.va.gov that isn't captured in Storybook, so I'm closing this.
