### ISSUE TITLE
Remove the links and message to Storybook and redirect to Storybook documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16120]
## Issue Description
About 1 month after Storybook is live, remove the links and message to Storybook and redirect to Storybook documentation. 
---
## Tasks
- [ ] remove the links and message to Storybook 
- [ ] redirect to Storybook documentation

## Acceptance Criteria
- [ ] message is no longer visible on gatsby and design.va.gov
- [ ] Links for components go to Storybook 
---
