### ISSUE TITLE
Prep for Staging review: Accessibility checks for map enhancements

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16121]
## Issue Description
 There are a number of items we need to complete before we can request the staging review of the map enhancement changes. 

## Tasks 
- [ ] Document existence of axe scans included in end-to-end (e2e) tests 
- [ ] Document the existence of any keyboard end-to-end tests (this will be a future requirement)

Conduct the following accessibility checks

- [ ] Axe scans 
- [ ] Axe-coconut scans
- [ ] Color tests for proper contrast and colorblindness 
- [ ] Content zoomed to 200%, 300%, 400% 
- [ ] Keyboard navigation 
- [ ] Screen reader tests (VoiceOver + Safari or NVDA + Firefox) 
- [ ] WAVE tool spot checks

## Acceptance Criteria
- [ ] Any accessibility defects are documented in issues using the 508 accessibility issue template

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
