### ISSUE TITLE
[SD] Data Analysis + Audit

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16126]
## Issue Description
_Collect, analyze and gathering insights from available data sources to better understand how veterans are searching on VA.gov as well as offsite (Google, Bing, etc. )_

## Known Data Sources to explore:
- Search.gov [#15674](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15674)
- Google Analytics
- Google Search Console  
- Bing Search Console 
- Help Desk Tickets 
- Ask a Question
- SEMRush
- IRIS #16191
- Moz.com

---
## Tasks
- [x] Validate that all team members have access to identified data sources
- [x] Define key data insights from **each** source
- [x] Transfer key metrics to DOMO Dashboard definition #16188
