### ISSUE TITLE
Onboarding - Shadow on-call support rotation to gain familiarity with processes and systems

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16138]
## Issue Description
_As a new member of the VSP operations team, I need to observe other on-call support personnel so that I understand what's involved with a typical on-call rotation. _

---
## Tasks
- [x] _Shadow one or more of our on-call support personnel to gain familiarity with the typical workflow and processes_
- [x] _Take note of any major questions that you may have regarding support rotation_
- [x] _Take note of any tools, channels, or comms that you may need in order to do support rotation in the future_ 

## Acceptance Criteria
- [x] _High-level understanding of our support workflow_
---
## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jhouse-solvd** [comment]
Don has now performed an oncall rotation. Way to go! Closing.
