### ISSUE TITLE
Onboarding - Shadow Grafana upgrade to gain familiarity with processes and systems

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16139]
## Issue Description
As a new member to the team, it would be great to follow along with another team mate while they upgrade an important piece of our infrastructure tooling. 

---
## Tasks
- [x] _Follow along w/ Bill as he upgrades Grafana to gain some insight into that process_

---
## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by oragame** [comment]
Shadowed with Bill, got a good overview of ansible related files for the upgrade.

**Comment by jhouse-solvd** [comment]
Closing.
