### ISSUE TITLE
Discovery - Understand FE Tools needs for monitoring solution (DataDog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16141]
## Issue Description
_Work with FE Tools team to understand what their immediate needs are for infrastructure monitoring._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _Ready to capture specific metrics for FE Tools team_
- [ ] _Ready to create custom dashboard for FE Tools team_
- [ ] _FE Tools team has access to DataDog
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
This can be moved to the backlog for now. We are currently working with BE tools team for application performance monitoring. In speaking with FE tools team, there is no immediate need for this, but it may come up in the future.
