### ISSUE TITLE
Search for and update links to our Sign-in FAQs page from other VA.gov pages and apps

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#16146]
## Issue Description
We have redirected our Sign-in FAQ page to the R&S page "Signing in to VA.gov." We need to do a search on VA.gov and in our apps for any links to the Sign-in FAQs so that we can change them to go directly to the R&S page instead. 

---
## Tasks
- [x] Search VA.gov (Randi)
- [x] Search in applications (Nick/Kelson)
- [x] Update any links found to point to R&S page /resources/signing-in-to-vagov/

## Acceptance Criteria
- [x] All links now point to R&S page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@ncksllvn @kelsonic This is a follow-up ticket for redirecting the old Sign-in FAQs page. Not sure if we have any links to it anywhere else on the site but could one of you run a search to see and then we can change them? Thanks much!

**Comment by bethpottsVADEPO** [comment]
To add a little background... the "old" sign-in FAQ addressed signing in, verifying your identity, privacy and security, and connected apps. There is no longer one article about all those things. There are 4 separate articles. So I would like to find out if there are any links to the old sign-in FAQ not just to swap in the new sign-in article url, but also to swap in the other urls (verifying / privacy / connected apps) if the original intent (say, on the confirmation page of an application) was to send the user to information about verifying their identity--which is now a separate article, not part of the sign-in article. I know this might sound convoluted, so let me know if you want clarification.

**Comment by ncksllvn** [comment]
I did a search across content for the term `/sign-in-faq`. 

| Page path | Term found |
| --- | --- |
| resources/signing-in-to-vagov/index.html | /sign-in-faq |
| resources/va-account-and-profile/2/index.html | /sign-in-faq |
| resources/tag/sign-in/index.html | /sign-in-faq |
| resources/tag/all-veterans/2/index.html | /sign-in-faq |

Kinda funny that `/sign-in-faq` was spotted on R&S. It look like the reason for this is the `Sign in or create account` button has `/sign-in-faq` in the URL.

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/02296d2f-4ccc-4e55-a4ac-9d11be4ffeaf)

Specifically, the link is `https://www.va.gov/?next=/sign-in-faq/`. This means that after logging in, the user is being taken to `/sign-in-faq`. It seems like we would want that to say `https://www.va.gov/?next=/resources/signing-in-to-vagov/` instead?

**Comment by RLHecht** [comment]
This is great, @ncksllvn ! @bethpottsVADEPO , I can go through and list out each one with a suggestion of which R&S page we want to link to instead.

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here are the Q&As where we link to the sign-in faqs and my suggestions for where to go instead:
- https://www.va.gov/resources/verifying-your-identity-on-vagov/
What's the fastest way to verify my identity online? 
How do I verify my identity online without a Premium account? 
What if my credit is frozen and I’m trying to verify my identity?
**Link all of these back to the verifying your ID page (or just to the main VA.gov page)**

- https://www.va.gov/resources/signing-in-to-vagov/
CTA button 
How do I sign in to VA.gov? 
**Link both of these back to the signing in page**

**Comment by bethpottsVADEPO** [comment]
These (https://www.va.gov/?next=%2Fsign-in-faq%2F) aren't really links to the sign-in faq, right? They go to the sign-in page. But @ncksllvn is `sign-in-faq` a part of the url because after the user signs in, they end up on the sign-in-faq page (or what used to be that page and is now redirecting)? I'm thinking we should use this general sign-in link instead?: https://www.va.gov/?next=/profile/

**Comment by bethpottsVADEPO** [comment]
@RLHecht Your suggestions above would be circular, if I'm understanding correctly. For the first bullet, the user is already on the verifying your ID page. For the second, the user is already on the signing in page. So I think we need to use: https://www.va.gov/?next=/profile/

**Comment by ncksllvn** [comment]
Circular _could_ be okay, if you want to get the user signed in and then return. `https://www.va.gov/?next=/profile/` would take them to the profile application - that could be good, if that app is considered a reasonable starting point after signing in?

**Comment by RLHecht** [comment]
Yeah, I was thinking that it would take them back to the page they were reading since there aren't really specific actions to do on the profile page once they click the button. It just allows them to then be signed in to do whatever they need next (verifying ID, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht @ncksllvn I see what you both are saying. Thanks for getting me there. That approach makes sense now. It's not so much circular as it is grounding them, keeping them on the page they started on before signing in. Sounds good--can you implement that? `Sign in or create an account` takes them to sign in, then back to the page they're on (either signing in or verifying your identity).

**Comment by RLHecht** [comment]
@ncksllvn If I were to change these links to the pages they are on, is this how I would write them?

- https://www.va.gov/?next=/verifying-your-identity-on-vagov/
- https://www.va.gov/?next=/signing-in-to-vagov/

**Comment by ncksllvn** [comment]
@RLHecht I think so. You can always test on Staging ->

`https://staging.va.gov/?next=/verifying-your-identity-on-vagov/` -> should take you to the staging homepage w/the login modal open, then once you complete the login flow, it should redirect you to `/verifying-your-identity-on-vagov/`

**Comment by RLHecht** [comment]
These links have been updated. Moving to validate and will close after today's deploy. FYSA @bethpottsVADEPO @brianalloyd

**Comment by RLHecht** [comment]
Validated on live site and confirmed on staging that the links work. Closing ticket.
