### ISSUE TITLE
S3 Support in EKS Terraform Module

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16143]
## Issue Description
Extend the EKS Terraform module to support creation and use of S3 buckets with EKS clusters.

The primary driver of this is Loki, but will be needed by other apps migrating to EKS in the future.

Requirements:
- Creation of NEW s3 bucket and associated EKS Cluster IAM roles/permissions
- Use of an EXISTING s3 bucket and associated EKS Cluster IAM roles/permissions

EKS Module: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks

---
## Tasks
- [x] Update Terraform EKS module
- [x] Test per requirements
- [x] Update documentation

## Acceptance Criteria
- [x] s3 bucket can be created along with EKS cluster creation/update by terraform
- [x] existing s3 bucket can be used along with EKS cluster creation/update by terraform

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Will change this to a requirement for the EKS terraform module, and then close it out.

**Comment by pnwstevan** [comment]
@jhouse-solvd I updated this ticket; please review and remove the `needs grooming` label when good to go.

**Comment by pnwstevan** [comment]
This was completed in release v1.2.0 of the module: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks/releases/tag/v1.2.0

**Comment by pnwstevan** [comment]
Notes/comments:

After testing, this is likely not to usable in the core module itself.  This is because the core module deploys cluster level resources, and S3 buckets will be used by apps/deploys and scoped to namespaces in the cluster.  Thus, S3 buckets and associated IAM roles should be created by/during app deployment, not cluster deployment.

The code is functional and can easily be refactored/reused into a separate module as needed.
