### ISSUE TITLE
Document revproxy to determine what needs to be done to move it to new infrastructure (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16140]
## Issue Description
_Ensure that we've fully documented current architecture / configuration of revproxy to ensure that we can move it to the new infrastructure with minimal impact to the platform._

---
## Tasks
- [x] _Written documentation that clearly explains revproxy's configuration and setup in sufficient detail_
- [x] _Supporting architecture / configuration diagram_

[WIP DOC HERE
](https://vfs.atlassian.net/wiki/spaces/VI/pages/744980492/Reverse+Proxy)

## Acceptance Criteria
- [x] _revproxy configuration and dependencies are well documented_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Awaiting final review.

**Comment by jhouse-solvd** [comment]
@dginther and I looked at this and are very comfortable with the level of documentation that @jbritt1 has provided. We will create a new ticket in the forthcoming Sprint to work on the migration plan for this particular service. Closing.
