### ISSUE TITLE
EKS - Terraform Module

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16158]
## Issue Description
_Terraform module to support creation of EKS clusters in VA.GOV_

Requirements:
- Basic creation of EKS cluster
- Creation of IAM roles and service accounts
- Creation of ODIC authentication provider
- Support for creation of an auth configmap so cluster can be administered post-creation
- Support for user defined options/features

---
## Tasks
- [x] _As this is an epic, separate tickets will be created for each task._

## Acceptance Criteria
- [x] _EKS clusters can be created and deployed meeting the requirements stated in the description_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pnwstevan** [comment]
I think you can close this as we've gotten the CloudPosse EKS module to work.  CC: @jhouse-solvd @dginther

**Comment by jhouse-solvd** [comment]
closing
