### ISSUE TITLE
[Centralized Logging with Loki] Investigate capturing AWS service logs

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16157]
## Issue Description
Ensure AWS service logs (things like RDS, Lambda, ELB) are being captured with Loki
AWS service logs can be sent to Loki in various ways, but most require a Lambda to run on a periodic basis to do so.

---
## Tasks
- [ ] Identify services that need to be logged and document
- [ ] Create stub document in Confluence to contain the list of logged services
- [ ] Create issues for each service that contain the necessary steps to get logs going into Loki for that service
  - [ ] Each ticket should contain a task to document that this service is logged in Loki and how to view logs for the service in Grafana
- [ ] Prioritize the created issues

## Acceptance Criteria
- [ ] Issues are created for each service that should be logged to Loki

**Comment by jhouse-solvd** [comment]
Removing from the Staging initiative, but keeping for our backlog.

**Comment by jbritt1** [comment]
Additional logs not being added to Loki at this time, closing.
