### ISSUE TITLE
Complete checklist items for detangling VFS accessibility and QA from DEPO Platform process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#16150]
## High level division of roles:
DEPO: define standards
DEPO Platform: enforce standards
VFS Teams: meet (and exceed!) standards

## Background
VFS teams are sometimes confused about what the DEPO Platform's standards are: what's required versus desired, and who ultimately gives the "sign off" that the standards are met sufficiently for the team to take their product live. This is largely because we've taken a highly collaborative approach across Platform and VFS accessibility and QA experts to develop process, share workload, and enforce standards. At this point however, the volume of concurrent VFS initiatives is making it such that this organic "blobby" model is creating confusion, swirl, and slow-down. So! We've worked in recent weeks to better define standards, and clarify what the different responsibilities are for Platform experts, and for VFS teams and now it’s time to start aligning to those responsibilities, by detangling VFS accessibility and QA folks from DEPO Platform process, and creating leaner process for the DEPO Platform accessibility and QA folks.

## Accessibility
 - [x] Publish clear standards that the DEPO Platform will enforce
    - [x]  Update existing docs
    - [x]  Publicize (ToTs)
- [ ]  Clearly separate out guidance content from requirements content in the documentation *
    - [x]  Update docs, and share in ToT, so it's clear that VFS teams need to come to the staging review w/their testing and artifacts complete
    - [x]  Update docs, and share in ToT, so there's a clear understanding of tasks that fall on VFS, VFS w/SME, vs VSP
    - [x]  Update docs so it's easy for VFS teams to follow the steps necessary to do their required testing and artifacts
- [ ]  Create automated dashboard of outstanding 508 issues*
- [x]  Cancel Weekly Review Team Standup - 11/16 occurrence cancelled. Still need to cancel permanently. 
- [x]  Archive #practice-area-reviewers Slack channel
- [x]  Create internal Slack channel just for the Product Support team and respective leadership to collaborate
- [x]  Create cross-team channel for the Collaboration Cycle product just for collab cycle reviewers
- [x]  Remove VFS personnel from governance/enforcement activities, but include them in appropriate collaboration cycle meetings by default
    - [x]  Brief all parties that VSP will deliver feedback in review meetings
    - [x]  Brief all parties that VSP may change the severity of an issue based on our review, and that'll be communicated to the VFS team members as a part of the staging review.
- [ ]  Remove DEPO Platform personnel from the shared Support meeting
    - [ ]  Inform all parties that questions about best practices should always go in the #vfs-platform-support channel
- [ ]  Do DEPO Platform workflow evaluation and cut / adjust steps where possible so the workflow is more manageable *
- [x]  Extend staging review SLA to 4 days instead of 2
    - [x]  Update collab cycle md file
    - [x]  Update staging review template
    - [x]  Announce to VFS teams

> *Item cannot be completed within Sprint 39

## QA
- [ ]  Publish clear standards that the DEPO Platform will enforce
- [ ]  Clearly separate out guidance content from requirements content in the documentation *
- [x]  Update docs, and share in ToT, so it's clear that VFS teams need to come to the staging review w/their testing and artifacts complete
- [ ]  Update docs so it's easy for VFS teams to follow the steps necessary to do their testing and artifacts
- [ ]  Remove VFS personnel from governance/enforcement activities and Slack channels
- [ ]  Remove DEPO Platform personnel from VFS-specific meetings (if there are any)
- [ ]  Do DEPO Platform workflow evaluation and cut / adjust steps where possible so the workflow is more manageable *

> *Item cannot be completed within Sprint 39

---
**Source:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/detangling-accessibility-and-qa-responsibilities.md

**Comment by shiragoodman** [comment]
@rroueche - question for you. Since we're retiring/archiving the #practice-areas-review-group channel, we will need to tell the shared resources for QA and a11y how they can contact us re: the Collab Cycle QA testing and a11y testing. See recent posts on that channel for examples of how/why they reach out. What Slack channel do you recommend?
