### ISSUE TITLE
Add new products to content grouping

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16176]
## Issue Description
We have content grouping in Google Analytics with `Benefit Hubs` and `Products.` Newly launched products are not included in this grouping, so anyone who uses this feature will have inaccurate information. We need to add newly launched products to this list in case our customers are using these groupings to analyze their data. VSP is also using trafficked VFS products to help prioritize their work.

---
## Tasks
Add the following products to the Benefit Hubs and Products content grouping
- [x] Product: 22-10203 -- Application for STEM Scholarship; Benefit Hub: Education
- [x] Product: 10-10CG -- Caregiver Application; Benefit Hub: Family Member Benefits
- [x] Product:  1995 -- GI Bill Comparison Tool; Benefit Hub: Education
- [x] Product: Medical Device Reordering Tool: Benefit Hub: Health Care
## Acceptance Criteria
- [ ] Content grouping in Google Analytics is up to date and accurate to use

**Comment by bmcgrady-ep** [comment]
### QA for Content Grouping Updates

**Medical Device Reordering Tool: Benefit Hub: Health Care**
![image](https://user-images.githubusercontent.com/66263904/100122177-5428be00-2e36-11eb-8d9f-0e477a25104d.png)

**22-10203 -- Application for STEM Scholarship**
![image](https://user-images.githubusercontent.com/66263904/100123732-12007c00-2e38-11eb-9833-4ba8b22b1fda.png)

**10-10CG -- Caregiver Application; Benefit Hub**
![image](https://user-images.githubusercontent.com/66263904/100124195-94893b80-2e38-11eb-95a5-9267d6987851.png)

**Comment by bmcgrady-ep** [comment]
Published the GTM workspace for the content grouping.
