### ISSUE TITLE
Terraform EKS Module - Spike

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#16179]
## Description
Initial Terraform module to create EKS clusters in vagov.

This is a spike to scaffold basic EKS cluster creation with BYO everything after cluster is created (auth, iam roles, oidc, s3, tags, etc..)

## Background/context/resources
Module should follow similar patterns as existing modules (ie: https://github.com/search?q=org%3Adepartment-of-veterans-affairs+terraform)

---
## Tasks
- [X] Write module
- [X] Test module
- [X] Initial Docs
- [X] Roadmap / Tickets

## Definition of Done
- [X] Successful creation of EKS Cluster in `dsva-vagov` environment

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
This work was completed with this PR: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks/pull/2

**Comment by pnwstevan** [comment]
Successfully created EKS clusters in `dev` and `staging`; confirmed by @jbritt1.
