### ISSUE TITLE
Social Media User Research

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16189]
## Description
A brief exploration of social groups for veteran pain points and learn more about what veterans are looking for but having trouble finding. 

---
## Tasks
- [x] Define list of social groups to explore: r/veterans on Reddit and http://hadit.com
- [x] Define list of search keywords: “Can’t find”, “Looking for”
- [x] Explore and monitor social channels for related keywords related to search and discovery experiences; looking for veteran pain points
- [x] Collect evidence of "online mood, sentiment and overall feelings {positive, neutral, negative} Veterans have toward searching for information that they need. (Quotes, comments, general impressions, etc.)  
- [x] Analyze the information to identify key needs for veterans and improvements that need to be considered for search enhancement.

## Definition of Done 
- [x] Social listening document created

**Comment by mgleo** [comment]
[Social listening doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/search/research/social-listening.md) created and added to the research folder.

**Comment by mgleo** [comment]
From sprint demo [Social Listening.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5630951/Social.Listening.pdf)
