### ISSUE TITLE
Explore + Establish Medallia Survey Implementation

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16186]
## Description
_There is currently one recommended survey for Veteran-facing Services as Foresee survey is being phased out. Medallia surveys offer consistency across VA.gov services. Implementing a survey in relation to the search experience will help us assess and better understand veteran satisfaction related to the search experience on VA.gov_

## Background/context/resources
The following questions can appear on one screen:
Did you find what you were looking for today? [‘yes’ or ‘no’]
What were you unable to find during your visit today? [text area]
What is your overall satisfaction with this site? [‘Very Dissatisfied’ through ’Very Satisfied”]

Demo is available on the [Find VA Locations staging link](http://staging.va.gov/find-locations) on the far right center of the screen as a button that reads "Feedback".

Joanne has created a ticket for this and says this survey will be prioritized as Medallia goes to Production: [User Survey Request for Public Websites - Medallia Pilot #16625](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16625)

## Technical notes
_Notes around work that is happening, if applicable_

## Tasks
- [x] Investigate Medallia implementation with Joanne Esteban to ensure it meets our expectations and aligns with our needs
- [x] Team to decide if implementation is worth integrating on site
- [x] Define benefits of integrating medallia survey

## Definition of Done
- [x] Team agreement regarding integration of medallia survey (Go/NoGo)

**Comment by mgleo** [comment]
The following questions can appear on one screen:
Did you find what you were looking for today? [‘yes’ or ‘no’]
What were you unable to find during your visit today? [text area]
What is your overall satisfaction with this site? [‘Very Dissatisfied’ through ’Very Satisfied”]

Demo is available on the [Find VA Locations staging link](http://staging.va.gov/find-locations) on the far right center of the screen as a button that reads "Feedback".

**Comment by mgleo** [comment]
Joanne has created a ticket for this and says this survey will be prioritized as Medallia goes to Production: [User Survey Request for Public Websites - Medallia Pilot #16625](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16625)

**Comment by denisecoveyduc** [comment]
@mgleo completed medallia review and is now waiting for implementation covered in  User Survey Request for Public Websites - Medallia Pilot #16625
