### ISSUE TITLE
Terraform EKS Module - MVP

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#16180]
## Description
MVP of terraform module for creating EKS Clusters in `dsva-vagov`.

Basic requirements:
* Creation of EKS cluster in user-defined environment/subnet
* Creation of IAM roles and K8 Service accounts
* Creation of OIDC authentication Provider for cluster
* Basic user-defined inputs/features:
  * Environment/VPC
  * K8 Version
  * Private and/or Public API endpoints
  * Logging to Cloudwatch

---
## Tasks
- [X] Update module per requirements
- [X] Test module
- [X] Initial docs

## Definition of Done
- [x] Successful creation of EKS cluster meeting all requirements

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
This work was completed by this PR: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks/pull/2
