### ISSUE TITLE
EKS - Terraform Module - Initial Usable Version

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#16181]
## Description
Update the VSP Terraform EKS module to be ready for initial use by Ops team.

Requirements:
* Creates cluster with appropriate dsva-vagov tags
* Supports creation of a configmap to be used for auth with user-inputs (Ops team IAM arn's)
* Support for sane/needed outputs to be used by other services
* Cluster supports logging to CW (to start, Loki eventually)
* Subnets used by cluster are tagged appropriately
* Refactor module as needed to organize code

Does NOT need to support creation of worker nodes/groups at this time.
## Background/context/resources
Existing module here: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks/

---
## Tasks
- [X] Update module per requirements
- [X] Test module
- [ ] Update documentation
- [ ] Provide example/sample code

## Definition of Done
- [ ] _Module has been updated with a PR meeting the requirements and can be used to create a permanent Ops-tool EKS cluster_

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
This should be complete; check the repo for all PRs:

https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks/

**Comment by jhouse-solvd** [comment]
@pnwstevan - @dginther and I looked at this together, but noticed that there were a couple of boxes left to check on this ticket so wanted to check with you on current status and what you may need from either of us in this Review stage.

**Comment by jhouse-solvd** [comment]
Okay, we've moved to using the CloudPosse EKS module. This is no longer relevant. Closing
