### ISSUE TITLE
Add content/accordions to Connected Apps FAQs in R&S

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16194]
## Issue Description
Need to add accordion content and links to new app directory per TJ Rice.

---
## Tasks
- [x] DO NOT IMPLEMENT NOW Once the app directory launches, change the CTA green button to "Find apps you can use" and link to the app directory.
- [x] Add H2: "Using connected apps" (First 2 accordions remain as is.)
- [x] DO NOT IMPLEMENT NOW Once the app directory launches in R&S, third accordion changes to:
**Where do I find third-party apps?**
You can find third-party apps for Veterans in [our app directory]. Check back often to connect to new apps.
- [x] Add the word "third-party" to the fourth accordion label: How do I connect a third-party app to my VA.gov profile?
- [x] Fourth accordion: Remove the last line:
For more instructions on how to verify your identity, watch our video on authentication methods for mobile apps and VA.gov (YouTube).
- [x] DO NOT IMPLEMENT NOW Fourth accordion: At the end of the answer, add this text and link to the apps directory:
[Find apps you can use]
- [x] Move the last accordion on the live page to be fifth: "Can I stop sharing..."
- [x] The last accordion in this grouping will be: "I don't have a smart phone. Do I need one?"
- [x] The accordion "What should I do if my records in an app are wrong or out of date?" moves to the third of the 3 new groupings that will each have a new H2.
- [x] Second grouping's H2: Privacy and security with connected apps
**Privacy and security with connected apps**
Accordion 1: **Do I have to connect my account?**	
No. You’re never required to connect your VA data to a third-party app. We offer this feature only for your convenience. In some cases, you can manually enter your information instead.	

Accordion 2: **What information can a connected app access?**
A connected app can only access the information and permissions you see listed when you authorize the connection. This list will vary for each app.	

Accordion 3: **Does an app keep my personal information after I’ve disconnected it?**
It depends on the app’s policy. Once you’ve disconnected an app, they will no longer receive new information about you from the VA. However, you may still need to request that they permanently delete data they’ve already collected. Refer to your app’s privacy policy or contact their customer support if you have specific questions.	

Accordion 4: **What should I do if I no longer trust a connected app?**
Take these 3 steps to protect your information:
1.	[Disconnect from the app] @RLHecht Can this be anchor linked to the accordion above called "Can I stop sharing my VA information with an app?" and expand that accordion? I suspect not, but it was a request from the SMEs.
2.	Contact the app’s support and ask them to permanently delete any stored information they may still have from you.
3.	[Report the app to us] @RLHecht link this to email, same as the link in "Can I stop sharing my VA information with an app?"

- [x] Third grouping's H2: Support with connected apps	
Accordion 1: **I tried to connect to an app and got an error message. What should I do?**
If you’re having trouble connecting to an app, contact the app’s customer support for help.
Accordion 2: **What should I do if my records in an app are wrong or out of date?** [this accordion is already live, so just needs to be placed here]
Accordion 3: **I’m having trouble signing in with DS Logon, My HealtheVet, or ID.me. What should I do?**
If you’re having trouble signing in, you can get answers to [frequently asked questions about signing in]. @RLHecht Link to our R&S article "Signing in to VA.gov"

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht I reviewed these edits you implemented. Looks good, you can set to publish.

**Comment by RLHecht** [comment]
The first round of changes are published. I'll hold off closing until the second set are done once the apps directory is live.

**Comment by RLHecht** [comment]
Second set of changes are now complete. Moving to validate and will close once the updates are live this afternoon. FYSA @brianalloyd

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
