### ISSUE TITLE
Gather SEO data on vaccines

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16193]
## Issue Description
We want to better understand what questions Veterans may have about coronavirus vaccines. As part of this we want to gather relevant SEO data.

---
## Tasks
- [ ] Pull SEO data on vaccine-related keywords
- [ ] Analyze for themes/questions

## Acceptance Criteria
- [ ] List of themes/questions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
