### ISSUE TITLE
upgrade prometheus and components to latest

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#162]
## Description

Prometheus, along with the components it uses like alertmanager, have fallen out of date and need to be upgraded. While these aren't user-facing features, upgrading will give us the ability to store metrics longer-term on the same virtual hardware.

## AC
- [ ] locally, build and test a new BRD app for Prometheus 2.x and related components, so we can run both side by side
- [ ] locally, bring up current stack alongside and test data and config migration
- [ ] locally, test grafana and make sure it works as well (my suspicion is that it doesn't and we'll need to upgrade there too)
- [ ] if needed, same loop for grafana
- [ ] collect integration points, scripts, custom setup and try to test locally
- [ ] collect some data from a dev or stage env and try to get a feeling for migration timing with a test run
- [ ] Given the above, formulate a rollout and cutover plan
- [ ] Execute the plan
- [ ] Tear down the old stuff and archive it.
- [ ] Prometheus and alertmanager updated to latest as of issue work starting

**Comment by nathanhruby** [comment]
Two useful links for dealing with data move to 2.0:
- https://gitlab.com/gitlab-org/prometheus-storage-migrator
- https://www.digitalocean.com/community/tutorials/how-to-upgrade-prometheus-1-x-to-prometheus-2-0-on-ubuntu-16-04#step-1-%E2%80%94-upgrading-prometheus-to-182

**Comment by ricetj** [comment]
@nathanhruby Can you map out the steps you had in mind for taking.

**Comment by nathanhruby** [comment]
This is a big upgrade effort with major version and/or breaking changes in all the components.  We'll need to test this upgrade pretty extensively
- locally, build and test a new BRD app for Prometheus 2.x and related components, so we can run both side by side
- locally, bring up current stack alongside and test data and config migration
- locally, test grafana and make sure it works as well (my suspicion is that it doesn't and we'll need to upgrade there too)
- if needed, same loop for grafana
- collect integration points, scripts, custom setup and try to test locally
- collect some data from a dev or stage env and try to get a feeling for migration timing with a test run
- Given the above, formulate a rollout and cutover plan
- Execute the plan
- Tear down the old stuff and archive it.

**Comment by nathanhruby** [comment]
noting I did some work on adhocteam/script_exporter to get it upgraded as well since that seemed easy enough to do and needed doing (build was busted given current client libs, needed rebuild with newer golang to address security vulnerabilities, needed ci, etc..)

**Comment by rroueche** [comment]
@ricetj is the Prometheus upgrade on hold, or did it get finished? I'm compiling a report of our Q4 2019 milestones and wasn't sure if this was something we completed, or had started investigating but hadn't yet finished.

**Comment by nathanhruby** [comment]
We parked this work due to issues with me getting AWS and socks proxy access, both of which are needed to complete this work.  It is currently still on hold while we do some discovery around our 2020 infrastructure plan.

**Comment by rroueche** [comment]
Great, thanks Nathan!

**Comment by nathanhruby** [comment]
unassigned myself for now, may pick it back up later but I'm cerrtianly not doing anything with this right now.

**Comment by jhouse-solvd** [comment]
The current strategy is to monitor all services in all environments using Datadog: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/17427

If we decide to upgrade/improve/maintain Prometheus, we will create a new issue w/ more up-to-date details. 

Closing.
