### ISSUE TITLE
[Development] HLR: Front-End Filter for Contestable Issues on Data Coming Back from Lighthouse

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16207]
## Issue Description
We decided with the customer to start by filtering by date.  Since the exceptions are more edge cases, we will go ahead and filter out anything older than a year old.  There will be updated content to go along with this but it will be a separate ticket.  Also, we need to ignore deferred decisions.

## Tasks
- [ ] Only show contestable issues with a decision date less than a year old
- [ ] No deferred decisions.

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
