### ISSUE TITLE
Create EDU DD Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16206]
## Goal
Now that the design work is mostly settled for the EDU Direct Deposit feature, we need to test it in usability sessions with Veterans.  We have mockups in place, but a prototype would be better and is required before contacting Perigean.

## Considerations
- [Research and Design Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/add-update-EDU-direct-deposit/research-design) for EDU DD

## Tasks
- [x] In UXPin, create a prototype that closely matches what is in the mockups
- [x] Cross reference the Research Plan and ensure that all functionality that may come up is addressed in the prototype.

## Acceptance Criteria
- [x] A prototype has been created and stored in the **research-design** folder for later access
- [x] The newly created prototype addresses all parts of the research plan

**Next steps:**
- Select dates for usability sessions
- Start scheduling with Perigean

**Comment by sporeboy** [comment]
Initial pass of DD-EDU prototype built: https://preview.uxpin.com/f80ffd0a5433096bc9abd52333b1e60a4ffd745d#/pages/134411565/simulate/sitemap

**Comment by sporeboy** [comment]
Prototype link given to AuthEx team. Seems we're good for the research sessions!
