### ISSUE TITLE
[Content] HLR: Updates to Contestable Issues Screen

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16210]
## Issue Description
Copying my summary from the HLR product guide and also my email to Lauren for context.  Essentially, we need to update the "why can't I see my issue" and "what do I do if I don't see my issue" verbiage.

> During UAT testing, we ran into a major issue where the contestable issues list contained essentially every denied decision. Since HLR has relatively strict timelines (a year after the decision date) and only a handful of exceptions, we realized a major change to the filtering/business logic needs to occur. It was decided that MVP would filter strictly on decision date and that we would add some content updates to explain (further) why an issue may not be showing up. The exceptions are going to require a paper form and possible making a call to a number that can help them etc.

> When a veteran does not find their issues, we wanted to update the wording with some more details about a) exceptions that may be causing this and b) what can they do in case they still want to talk to someone about their HLR.  Is there a bulleted list of exceptions or anything documented you have available to share?  In terms of content around "what to do", is there a more specific hotline or number a veteran can call to find out about appeals and decision reviews, etc?  Do we tell them to go to their VSO for help?  We could use some help forming the narrative around these items so we can get the content written, approved by our content leads, and rolled out in time for UAT next week.

---
## Tasks
- [x] Work with Luke (he is working with Lauren) on wording
- [ ] Get the design/content to FE

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
I've requested a review from the stakeholder of the content.  If I don't get a review we will go with the version they provided and not the version I am working on.

**Comment by luke-gcio** [comment]
Robin mocked it up.  Waiting for Lauren.

![localhost_3001_decision-reviews_higher-level-review_request-higher-level-review-form-20-0996_introduction (1)](https://user-images.githubusercontent.com/53824125/100916548-20cbdc00-3493-11eb-91ee-9d82466aa3c5.png)
![localhost_3001_decision-reviews_higher-level-review_request-higher-level-review-form-20-0996_introduction](https://user-images.githubusercontent.com/53824125/100916559-232e3600-3493-11eb-9b28-a15452cdde11.png)

**Comment by Mottie** [comment]
Reference to "fax" has been removed in the forth bullet point - screenshot has not been updated.

**Comment by luke-gcio** [comment]
Latest info from Lauren which Robin is working towards:

Step 2 of 4:  Previously Decided Issues
Select the issue(s) you would like reviewed:

![image](https://user-images.githubusercontent.com/53824125/101220234-94601b80-3642-11eb-96ac-ecf44311d2b5.png)

**Comment by luke-gcio** [comment]
We decided to go with a minor change to the above:

"Step 2 of 4: Issues Eligible for Review"

**Comment by Mottie** [comment]
I also changed the path from `contested-issues` to `eligible-issues` - e.g. https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/eligible-issues

**Comment by Mottie** [comment]
@mnorthuis I forgot to get your input on the change (in my last comment) I was going to include in the update.

Given we're changing the title from "Contested issues" to referring to "Issues eligible for review", I thought changing the name of the path might also be appropriate. Please let me know if this is acceptable. Thanks!

**Comment by mnorthuis** [comment]
@Mottie thank you for the heads up!  As long as the main path/sub-directory for the form (up to the form number) remains the same, I am ok with whatever the team decides for the individual form chapters.  They do not impact SEO and users can't link directly to chapters (excluding SiP) so I just recommend keeping them short and plain language as with all things. Thank you!

**Comment by peggygannon** [comment]
Hello @luke-gcio and @kevinstachura Below are my content recommendations for this screen. I also noticed that some of my earlier recommendation have not yet been incorporated into the mockup. I'm putting there here again. Can you please let me know when the mockup is updated? I can check it to make sure edits are correct. thx. 

**2nd review 12/11/20**
Form should be Form (with cap F) (we only use “Equal to form a form's intro page) 

Don’t see the issue you’re looking for? {additional component link}

**Your issue may not be eligible for review if:**

- We made the decision over a year ago. You have 1 year from the date on your decision letter to request a Higher-Level Review. **Note:** If you aren’t able to request a timely review due to COVID-19, we may grant you a deadline extension. To request an extension, fill out and submit VA Form 20-0996, with a note attached that you’re requesting an extension due to COVID-19.

- Your issue is for a benefit type other than compensation or pension. To request a Higher-Level Review for another benefit type, you'll need to fill out VA Form 20-0996 and submit it by mail or in person. 

- The issue or decision isn’t our system yet. You'll need to fill VA Form 20-0996 and submit it by mail or in person. 

- You and another surviving dependent of the Veteran are applying for the same benefit. And by law, only 1 of you can receive that benefit. You’ll need to [appeal to the Board of Veterans’ Appeals](https://www.va.gov/decision-reviews/board-appeal/)

- You’re requesting a review of a Board of Veterans’ Appeals decision. Refer to your decision notice for your options. 

- You’re requesting a review of a Higher-Level Review decision. You’ll need to either file a Supplemental Claim or appeal to the Board of Veterans’ Appeals. 

[Download VA Form 20-0996 (PDF)] (https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf)

To learn more about how COVID-19 affect claims or appeals, please visit our [Coronavirus FAQ page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#more-benefit-and-claim-questio).

To learn more about decision review options, please visit our [decision review and appeals](https://www.va.gov/decision-reviews/) information page. You can also call us at 800-827-1000 or work with an accredited representative to [get help with your claim](https://www.va.gov/disability/get-help-filing-claim/).

{end additional component}

-------

QUESTION: is this bullet below a SME addition? It wasn't on an earlier version of this content. 
“The VA hasn’t yet reached a decision on this claim. Please [refer to the Claim Status tool….

If the VA hasn't made a decision yet, then how can a user file for a HLR?

------

{Checkbox} I’d like the same office to do this review
You can request to have the same office conduct your Higher-Level Review. We might not be able to grant your request, however. Either way, a new reviewer will look at your case and consider it separately from your original decision. 

-------

**We’ll try to grant your request**
If we can’t fulfill your request, we’ll let you know at the time we make a decision on your Higher-Level Review.  

------

Informal conference

You or your accredited representative (claims agent, attorney, or Veterans Service Organization) can request an informal conference with the reviewer assigned to your Higher-Level Review. During this conference you or your representative will have the chance to discuss why you think the decision should be changed and identify factual errors. 

If you request an informal conference, the reviewer will call you or your representative. You can request only one informal conference for your Higher-Level Review. 

-------

**We'll call you 2 times**

Each time we call, we'll leave a voice mail and a number for you to return the call. If we aren't able to get in touch with you after 2 attempts, we'll proceed with the Higher-Level Review.

**We'll call your representative 2 times**
Each time we call, we’ll leave a voice mail and a number for them to return the call. If we aren't able to get in touch with them after 2 attempts, we'll proceed with the Higher-Level Review.


-----

**Need help** footer
Please update the Need help footer to the below, with the new VA general number: 

If you have questions or need help filling out this form, please call our MYVA411 main information line at 800-698-2411[hyperlink] and select 0. We’re here 24/7.
If you have hearing loss, call TTY: 711[hyperlink}

**Comment by luke-gcio** [comment]
> QUESTION: is this bullet below a SME addition? It wasn't on an earlier version of this content.
“The VA hasn’t yet reached a decision on this claim. Please [refer to the Claim Status tool…. If the VA hasn't made a decision yet, then how can a user file for a HLR?

Yes, this was a specific addition by the client.  A veteran can certainly come into the application thinking they want a higher level review for a disability they filed, not realizing that an initial decision has not been reached.  This is not uncommon with paper forms that get rejected.

**Comment by Mottie** [comment]
@peggygannon So since the phone number in the footer is different, should we also update the number on the [Veteran's information page](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/386172038), within the [not eligible for review dropdown](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404527932) and on the [confirmation page](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404690149)?

**Comment by peggygannon** [comment]
HI, @Mottie Thank you for checking in about that. I don't think we should update the phone numbers on the other pages. The phone number that appear on those is for VA Benefits Assistance and is the appropriate number for users to call if they have a question related to their benefits or claim. 

The MYVA 411 number is the  general number users should call for general questions or it they are having trouble using online tools. 

I'll be updating content docs with this distinction/guidance.

**Comment by Mottie** [comment]
Hi @peggygannon!

These updates are now available in staging.

**Comment by peggygannon** [comment]
Hi, @Mottie what test user should I use to review the updates?

**Comment by Mottie** [comment]
Hi Peggy! I usually test with user 233 or 239 - see https://dsva.slack.com/archives/C5AGLBNRK/p1601069669025200?thread_ts=1601069567.024300&cid=C5AGLBNRK

**Comment by peggygannon** [comment]
Thanks, @mottie For both of these users, I got a message (see screenshot below) that there were no eligible issues. As such, I wasn't able to review all the screens: 

I've noted a few things on the screens I was able to see: 

Wizard screen
This content is set as a link *Send the completed form to the benefit office**

Where does it take users? 

-------


Form intro page
Cap the I in If here: *if you don’t think this is the right form for you, go back and answer questions again.*


Under VA review
Change “the error” to “an error” 

*A review might take longer if we need to get records or schedule a new exam to correct the error.*

-----

The H1s on form screens should match the one that appears on the form introduction  
Request a Higher-Level Review with VA Form 20-0996

----
Under the *Don't see the issue you're looking for* message: 

We're missing "out" in this sentence: You’ll need to fill *out* VA Form 20-0996 and submit it by mail or in person.


I don’t see a bullet for this reason in the message. Should it be added? It was in an earlier screenshot. 

- The VA hasn’t yet reached a decision on this claim. Please [refer to the Claim Status tool….


-------


![2020-12-21](https://user-images.githubusercontent.com/17554224/102831084-c215c600-439f-11eb-83bf-a78478d7f4f8.png)

**Comment by Mottie** [comment]
Hi @peggygannon!

Sorry I forgot to follow up on your questions.

> _Send the completed form to the benefit office_* ... Where does it take users?

The link takes users to the info page "other benefit types" accordion - https://staging.va.gov/decision-reviews/higher-level-review/#8622

![Screen Shot 2021-01-12 at 8 52 23 AM](https://user-images.githubusercontent.com/136959/104330785-f585d500-54b3-11eb-9582-1a6a933e520d.png)

> Under VA review
> Change “the error” to “an error”

I'll get this fixed on the frontend!

> I don’t see a bullet for this reason in the message. Should it be added? It was in an earlier screenshot.

We're still awaiting more content changes to this section. Please see https://github.com/department-of-veterans-affairs/va.gov-team/issues/18065

**Comment by Mottie** [comment]
Oh, and it's weird, but sometimes in staging, the issues don't load... if you restart the form, it should restore the list of issues. I _hope_ this is only a staging problem that has recently popped up.
