### ISSUE TITLE
[Centralized Logging] Potential Forwarding of Loki Logs to VA Splunk instance

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#16217]
## Issue Description
I _believe_ some talks have started happening about the likelihood of us forwarding logs from Loki to perhaps the VAEC team?

---
## Tasks
- [ ] Work with team / Boris / Joe / etc. to see if this is a hard requirement, timelines, expectations, etc. May need to develop more tasks once some key details are nailed down.

## Acceptance Criteria
- [x] Decide path forward
- [ ] Take decided path

**Comment by jbritt1** [comment]
Sorry for all the tags gentlemen, just trying to make sure this gets in front of the correct people so the conversation can start if needed.

**Comment by joeniquette** [comment]
As a representative of the Identity logging correlation issue, if we were to get logs from cloudwatch for the vets-api (specifically SSO related) into the splunk instance managed by the VA, then it would be helpful for me to potentially identify issues quicker. I do not want to press on this too much, but if we are being asked to complete this work, perhaps the cloudwatch logs specifically for SSO could be the initial step?

**Comment by dginther** [comment]
Work is already underway to allow the VA to scrape our Prometheus, we could extend that to Loki/Cloudwatch if needed.

**Comment by jhouse-solvd** [comment]
We are awaiting a response from the VA's monitoring / Splunk team. Will circle back to this as it progresses.

**Comment by jhouse-solvd** [comment]
Closing this issue. If it's decided that this is a requirement, we can scope an issue accordingly.
