### ISSUE TITLE
[Development] HLR: Updates to Contestable Issues Screen

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16211]
## Issue Description
Copying my summary from the HLR product guide and also my email to Lauren for context. Essentially, we need to update the "why can't I see my issue" and "what do I do if I don't see my issue" verbiage.

**Note: FE will get this from design/content, part of their work in** #16210

> During UAT testing, we ran into a major issue where the contestable issues list contained essentially every denied decision. Since HLR has relatively strict timelines (a year after the decision date) and only a handful of exceptions, we realized a major change to the filtering/business logic needs to occur. It was decided that MVP would filter strictly on decision date and that we would add some content updates to explain (further) why an issue may not be showing up. The exceptions are going to require a paper form and possible making a call to a number that can help them etc.

> When a veteran does not find their issues, we wanted to update the wording with some more details about a) exceptions that may be causing this and b) what can they do in case they still want to talk to someone about their HLR. Is there a bulleted list of exceptions or anything documented you have available to share? In terms of content around "what to do", is there a more specific hotline or number a veteran can call to find out about appeals and decision reviews, etc? Do we tell them to go to their VSO for help? We could use some help forming the narrative around these items so we can get the content written, approved by our content leads, and rolled out in time for UAT next week.

## Tasks
- [ ] Content updates based on #16210 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
This hasn't been started as I am still waiting for the content review to be completed.
