### ISSUE TITLE
Troubleshoot CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16219]
## Goal 
Working on trying to figure out why Central Mail won't take our CH36 form.  The issue is that we cannot fire off our form to CM and we don't know why.  We were getting an unauth error locally.  Platform didn't respond so we merged in our code to try it.  Seemed like authorization was the issue, and Lihan suggested trying another form and that worked.  We want to get an error but there might be risk of PII coming back, or somehow making its way into production.

## PR submitted for reference
https://github.com/department-of-veterans-affairs/vets-api/pull/5246

## Tasks
- [x] Submit form in staging that uses same Central Mail code to confirm issue
- [x] Figure out way to print error in staging if above is successful
    - [x] Push out code that prints error? **Tried but VSP concerned about PII**
    - [x] Spin up Review Instance with error message. **Tried but review instances don't work**
    - [x] SSH into staging, grab credentials? **Just thought of this. Gonna try**
    - [x] Submit code manually via `rails c`. **Might try depending on how other thing goes**

## Acceptance Criteria 
- [x] We have diagnosed the issue

**Comment by digitaldrk** [comment]
PR submitted and merged. Form successfully submitted, UUID obtained
