### ISSUE TITLE
Staging Review [Bilby (Lighthouse End-User Experience Team) - App Directory]

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#16230]
## Steps to complete Staging Review: 

- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Attach all artifacts before requesting the meeting
- [ ] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] Staging Review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline 
    - Link is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14418#issuecomment-703887062
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - Preview link for the draft version of the app directory (need Socks): preview-prod.vfs.va.gov/preview?nodeId=9615 
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References]
      - TestRail cases: https://dsvavsp.testrail.io/index.php?/suites/view/78&group_by=cases:section_id&group_order=asc
      - TestRail plan: https://dsvavsp.testrail.io/index.php?/runs/view/722&group_by=cases:section_id&group_order=asc
      - Defects: https://dsvavsp.testrail.io/index.php?/reports/view/155
      - References: https://dsvavsp.testrail.io/index.php?/reports/view/154

- 508/ Accessibility:
  - https://dsvavsp.testrail.io/index.php?/runs/view/842&group_by=cases:section_id&group_order=asc

## Meeting attendees from **requesting team**
- Product Manager (required): **TJ Rice**
- DEPO product lead (required): **Andrew Fichter**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Rian Fowler, Kevin Lee, Braden Shipley, Bill Wanamaker**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and shira will reach out as needed_

Thursday the 19th at 2pm est

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by 1Copenut** [comment]
@ricetj I can't access the Accessibility test cases that were linked above ( https://dsvavsp.testrail.io/index.php?/runs/view/842&group_by=cases:section_id&group_order=asc ). TestRail says the project doesn't exist or I don't have permission. Please advise if I need a new link or someone should add me to a project.

/cc @shiragoodman

**Comment by ricetj** [comment]
> @ricetj I can't access the Accessibility test cases that were linked above ( https://dsvavsp.testrail.io/index.php?/runs/view/842&group_by=cases:section_id&group_order=asc ). TestRail says the project doesn't exist or I don't have permission. Please advise if I need a new link or someone should add me to a project.
> 
> /cc @shiragoodman

Hello @1Copenut, tagging @LeKeve to troubleshoot this. I'm guessing it's most likely an access thing.

**Comment by LeKeve** [comment]
@1Copenut I just spoke with VSP product support and they gave you permission to view the project. Could you try again?

**Comment by 1Copenut** [comment]
@LeKeve & @ricetj  I have access now. Thank you both.

**Comment by emilywaggoner** [comment]
@ricetj Hey TJ! Would you be able to post some screenshots of the pages needing review from the preview link? Some of us do not have the SOCKS proxy set up to be able to view it.

**Comment by ricetj** [comment]
> @ricetj Hey TJ! Would you be able to post some screenshots of the pages needing review from the preview link? Some of us do not have the SOCKS proxy set up to be able to view it.

Hello @emilywaggoner, here is a screenshot: 
<img width="449" alt="Screen Shot 2020-11-18 at 3 27 23 PM" src="https://user-images.githubusercontent.com/49173478/99584313-c9b60980-29b2-11eb-9f12-be7fa26a0bb2.png">

Also, here are the mockups if you are interested: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14279#issuecomment-722454068

**Comment by ricetj** [comment]
Here is another with the learn more accordion expanded. <img width="343" alt="Screen Shot 2020-11-18 at 3 31 13 PM" src="https://user-images.githubusercontent.com/49173478/99584569-20234800-29b3-11eb-8388-24946a41f91e.png">

**Comment by emilywaggoner** [comment]
Excellent, thanks @ricetj! @allison0034 let's use these 2 screenshots for the staging review.

**Comment by pjhill** [comment]
Hey, it looks like the standard QA artifacts that we ask for as part of staging review are not available. Have you been able to execute your test suite? I poked around in TestRail a bit, and it looks like your [functional / acceptance test cases have not yet been executed](https://dsvavsp.testrail.io/index.php?/runs/view/722&group_by=cases:section_id&group_order=asc).

For more information regarding the timeline by which VSP requests artifacts and how to complete each artifact, please see the following [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md).

**Comment by LeKeve** [comment]
@pjhill 

The test suite has been checked during daily development but I did a check this morning. Those tests have been updated as passing. The test plan and results are linked in the TestRail plan here: https://dsvavsp.testrail.io/index.php?/runs/view/722&group_by=cases:section_id&group_order=asc

As for the Reference Test Coverage Report and Summary (Defects), I don't appear to have access to those example reports. Can I be given access so I can take a look and generate those artifacts?

**Comment by pjhill** [comment]
> @pjhill
> 
> The test suite has been checked during daily development but I did a check this morning. Those tests have been updated as passing. The test plan and results are linked in the TestRail plan here: https://dsvavsp.testrail.io/index.php?/runs/view/722&group_by=cases:section_id&group_order=asc
> 
> As for the Reference Test Coverage Report and Summary (Defects), I don't appear to have access to those example reports. Can I be given access so I can take a look and generate those artifacts?

@LeKeve Sorry about that -- I think a recent update to TestRail changed the default access within our instance to be more restricted which is generally a good thing, but it had the side effect of locking down a bunch of example materials.  I believe I've resolved the issue. Have another go at accessing the relevant reports --
[Defects](https://dsvavsp.testrail.io/index.php?/reports/view/14)
[References](https://dsvavsp.testrail.io/index.php?/reports/view/12)

**Comment by LeKeve** [comment]
> @LeKeve Sorry about that -- I think a recent update to TestRail changed the default access within our instance to be more restricted which is generally a good thing, but it had the side effect of locking down a bunch of example materials. I believe I've resolved the issue. Have another go at accessing the relevant reports --
> [Defects](https://dsvavsp.testrail.io/index.php?/reports/view/14)
> [References](https://dsvavsp.testrail.io/index.php?/reports/view/12)

@pjhill No worries at all! Unfortunately, I'm still not able to view the example reports, however, I believe I've generated the correct reports and made them viewable by all. 

[Defects](https://dsvavsp.testrail.io/index.php?/reports/view/155)
[References](https://dsvavsp.testrail.io/index.php?/reports/view/154)

**Comment by pjhill** [comment]
> > @LeKeve Sorry about that -- I think a recent update to TestRail changed the default access within our instance to be more restricted which is generally a good thing, but it had the side effect of locking down a bunch of example materials. I believe I've resolved the issue. Have another go at accessing the relevant reports --
> > [Defects](https://dsvavsp.testrail.io/index.php?/reports/view/14)
> > [References](https://dsvavsp.testrail.io/index.php?/reports/view/12)
> 
> @pjhill No worries at all! Unfortunately, I'm still not able to view the example reports, however, I believe I've generated the correct reports and made them viewable by all.
> 
> [Defects](https://dsvavsp.testrail.io/index.php?/reports/view/155)
> [References](https://dsvavsp.testrail.io/index.php?/reports/view/154)

Well, that's frustrating!  Thanks for the links to your reports!

**Comment by peggygannon** [comment]
@ricetj Here is the link to my content feedback. thank you!

https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/16428

**Comment by 1Copenut** [comment]
@ricetj I've taken a second look in production and added a few more issue tickets. LMK if you have any questions.
