### ISSUE TITLE
[EPIC] Source of Truth - Creation, documentation and version control for: Root/baseline System, content, nodes, Alerts that are tested to latest revision [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16234]
## VAMC - Product Outline
[VAMC-upgrade Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)

## High Level User Story
As a PAO and VAMC team member,  I need to locate, document, and set improvements to the CMS/Drupal Editorial User Experience, so all future PAO/web editors and editorial users can easily understand how to update and maintain the Web experience for Veterans, their caregivers, and family members. 

## VAMC-Upgrade KPI met with this EPIC
_Document and suggest ways to improve the editorial, help comments, and overall flow and use of the experience in Prod and Staging for future use.

## Definition of Done 
_Creation of a Source Of Truth (SOT) for each of the following key objects with the top object being the parent for all others (for example: System will be parent of all node pages, node page would be parent of node alert or content object)
- [ ] System (SOT)
**Must have the following complete before it is SOT:
- [ ] Full clone
- [ ] Full upload
- [ ] Internal review and documentation
- [ ] PAO input
- [ ] Platform testing to include: IA, Content, QA, and 508 testing.
**Separate child sections**
- [ ] Top Tasks (Call to action)
- [ ] Health Service Programs
- [ ] Health services
