### ISSUE TITLE
Substantive edit of R&S decision review article

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16245]
## Issue Description
DEPO edit of decision review article before copyedit step.

---
## Tasks
- [ ] Edit chart. Provide feedback in comments and track changes. 
- [ ] Provide feedback to @lwalsh617 to incorporate before the next step, copyediting

## Acceptance Criteria
- [ ] Text edited and feedback provided.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 See my edits and comments in the attached Word doc. There are a couple things for you to look into further, then you can pass along to Randi. Thanks![https://app.zenhub.com/files/133843125/0d5c5e28-7c9f-48e1-a390-090f0668c5e4/download](https://app.zenhub.com/files/133843125/0d5c5e28-7c9f-48e1-a390-090f0668c5e4/download)

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lwalsh617 I'm locked out of the file because Randi's in it, so I'll just request here that you swap out

**Comment by bethpottsVADEPO** [comment]
Closing this--my edits have been incorporated.
