### ISSUE TITLE
FE Checklist Layout Changes 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#16240]
## Issue Description
_Need to make some checklist tweaks to heading and layout_

## Front end tasks
- Remove hardcoded "checklist" H2 heading 
- Add intro text for checklist (new field)
- Remove thicker border from the bottom of the page (currently showing two borders right now)
- Prevent wrapping underneath the checkboxes, so that the labels are all aligned to the right (is this possible?)

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by jenniferlee-dsva** [comment]
Referencing related larger Checklist FE ticket - #15649.  

It may make sense to fold this into 15649 or to do it together as a sub-task ticket.

**Comment by brianalloyd** [comment]
Fixes folded into #15617, closing out this ticket in support.
