### ISSUE TITLE
VA411 User Journey Map

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#16253]
## Issue Description
Develop a user journey map to help understand the process VA.gov users go through when finding contact numbers on the website. Determine pain points and problem areas in reference to where call center numbers are located on the site, and how a user determines which number is appropriate for their respective call.

---
## Tasks
- [ ] Develop a user journey map
- [ ] Share user journey map with team & review

## Acceptance Criteria
- [ ] Confirm the map accurately displays the user journey. The accuracy will be determined by the team.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@ianMcCullough-ob Sharing these two documents in case they help with the user journey creation.

First one is a list of VA.gov issues with identified definitions. This is used by the contact center to identify how to categorize an issue.
[https://app.zenhub.com/files/133843125/fa8161fe-60d6-4f32-9826-4bc05c955042/download](https://app.zenhub.com/files/133843125/fa8161fe-60d6-4f32-9826-4bc05c955042/download)

Second one is the scripts used to email veterans with specific issues on VA.gov
[https://app.zenhub.com/files/133843125/f417441a-be75-471b-8109-a9074e442801/download](https://app.zenhub.com/files/133843125/f417441a-be75-471b-8109-a9074e442801/download)

**Comment by ianMcCullough-ob** [comment]
[Helpful VA phone numbers](https://www.va.gov/resources/helpful-va-phone-numbers/)
[Dates, times, phone numbers, and addresses | Design System](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
