### ISSUE TITLE
[FE] Update to new URLs

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16256]
## User Story
As a veteran 
I should have consistent and semantically accurate URLs
So that I know what page I am on. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- TODO ADD DOCS

## Description
Update the URLs to reflect what the Platform suggests

## Tasks
- [ ] ??????
- [ ] Create user tests
- [ ] Create e2e tests 
- [ ] Create Pact tests
- [ ] Update relevant documentations

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by abuckley3385** [comment]
getting info from IA mid week so pointing my change

**Comment by mdewey** [comment]
duplicate of #16954
