### ISSUE TITLE
Contact Center Team Charter Work

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#16277]
## Issue Description
Conduct team sessions to develop a first version of the contact center charter (vision, mission, roadmap). 

---
## Tasks
- [x] Schedule and plan team sessions to discuss and brainstorm contact center work 
- [x] Create first version of contact center charter documentation
- [x] Validate with contact center team

## Acceptance Criteria
- [x] First version of Contact Center Team charter
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Completed first team session to determine the problem statement facing the contact center team. Refer to the mural board for brainstorm session notes: 

https://app.mural.co/t/chanteworkspace9220/m/chanteworkspace9220/1605183640422/c422a7bbc657f74e8abe613e26bef6ac518c31bb

**Comment by clantosswett** [comment]
Completed additional brainstorming work for mission and future work. I will be finalizing a charter document and will share back with the team in the next sprint:

https://docs.google.com/presentation/d/1EaDm84bqOyNdOOKL5k458UrHIfPIsllLc0fsnEZYGCM/edit

https://docs.google.com/spreadsheets/d/16A80UsdStmy9DITf_1Tlm0419cAnW5a5Krgegjxj9qM/edit#gid=0

**Comment by clantosswett** [comment]
Here is the current first draft of the VSP contact center team charter. I will close this issue but still would be open to feedback if others have it. Next step will be to share with the new PM and have him take ownership of any future changes and edits:

https://docs.google.com/presentation/d/1EaDm84bqOyNdOOKL5k458UrHIfPIsllLc0fsnEZYGCM/edit?userstoinvite=starlow@thesocompany.com&ts=5fbc19c6#slide=id.g33cc3b02a5_0_49
