### ISSUE TITLE
Turn `facility_locator_ppms_use_v1_client` back on

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16273]
## Issue Description
Following the work in #16259 and  #16265, we need to  turn `facility_locator_ppms_use_v1_client` back on and monitor 

---
## Tasks
- [ ] Turn `facility_locator_ppms_use_v1_client` back on and monitor 

## Acceptance Criteria
- [ ] Facility Locator uses v1 client

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
