### ISSUE TITLE
Remove Appeals Service Alert from VSP-Ops PageDuty Config

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#16279]
## Issue Description
Ops member and a Front End Engineer were pinged at ~2am Eastern over the weekend for Appeals service being down. This was later discovered to be some planned maintenance, but we likely should not have been woken up for this alert. We should remove it from our alerting system / PagerDuty configurations.

Perhaps [this](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/application.rules#L33-L40) is relevant.

---
## Tasks
- [ ] Remove Appeals service alert 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
