### ISSUE TITLE
[FE] Usability Update Feedback 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16278]
## User Story
As a user I should have a UI that works for me 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214c66caff64c73f44ba)

## Description
- Address the feedback that was given. 

## Tasks
- [x] [The submit button on the review page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15522#issuecomment-728330900)
- [x] [Update `print this questionnaire` button] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/15523#issuecomment-726818005)
- [x] [Sign in text](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14387#issuecomment-728334614)

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [x] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
In Pull Request.

**Comment by mdewey** [comment]
This is in staging @kristenmcconnell  and @abuckley3385. Can you two confirm and close the ticket?

**Comment by kristenmcconnell** [comment]
Looks great.
