### ISSUE TITLE
VSP ATO -  May need an update to PTA

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16289]
## Issue Description
_The VSP ATO may need a PTA update to cover the new GovCIO system and possibly remove the GDIT system.  GDIT has lost their contract and GovCIO will be taking it on_

The PTA cannot be changed now because it has been finalized and submitted as part of the VSP's ATO package. However, I will update the PTA to reflect the change as part of the 2021 Annual review update In January

---
## Tasks
- [ ] _Follow up on PTA update requirements to ensure that things get updated in January_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
This ticket is incomplete and can be closed. We've been tracking issues and tasks around ATO, but this one is irrelevant.
