### ISSUE TITLE
Adjust Copy Around the Income Question for Pension

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16281]
## Background
We want to ensure that we are presenting the income question as it pertains to whether it is greater than a certain amount and not less.

The initial spec was to ask whether household net worth was **greater** than $129,094, but the implementation is asking if it's less than that amount. (https://github.com/department-of-veterans-affairs/vets-website/pull/14717) 

The value expected by VNP/ RBPS,  is:
- "YES, this household income is greater than $129,094" or,
- "NO, this household income is NOT greater than $129,094."

## Tasks
- [ ] Update the copy to reflect this on all applicable pages (coded in one place, but appears on a few pages):
  - _"Did the household have a **net worth** greater than $129,094 in the last tax year?"_

## Acceptance Criteria
- [ ] The copy has been updated to ask the question in the correct orientation.
- [ ] A PR has been requested for merging
