### ISSUE TITLE
[UX] Feedback from content

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#16304]
## User Story
- Veterans need the wording of their questionnaire to be easily understandable.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A wireframes set with the below updates will be delivered with the technical specifications needed for engineering to implement said feature.

### Part 1
**Updated content to intro page.**

Initial feedback from Peggy Gannon sent on Nov. 17, 2020. Further updates can be found within the comments of this story.
hello, @kristenmcconnell here is updated content for the questionnaires landing page to better align with the static page.
these updates include:
1. Bringing info about filing out  [X] days further up to intro, to better inform user whether answering questionnaire is helpful, and reframed the intro a bit because of this.

2. per our earlier conversation, moved the "What happens after I answer questions" paragraph above the privacy questions so we can incorporate info about it being added to their medical record.

3. Under privacy question, this first bullet is still not yet final (•Share your information with only the people who need it as part of providing your health care). Danielle is still in discussion with some SMEs about if this should align it with what's on our current health care tool pages.

4. Emergency care note. How did this test with users? Wonder if we should consider moving earlier in the flow? It feels buried here and by time users get to this page, they have already have appt. lined up.

https://app.zenhub.com/files/133843125/4bcc6c5d-2e24-4713-aec9-4fd0f58cf795/download

### Part 2
**Updated Need Help? Information, approved by Peggy and Danielle:**
Need help?
If you have questions or need help filling out this form, please call our MyVA411 main information line at 800-698-2411 and select 0. We're here 24/7.
If you have hearing loss, call TTY: 711(hyperlink).

### Part 3
**Updated the button text on the confirmation page to (approved by Peggy):**
Go to your health questionnaires
Go to your appointment details

## Tasks
- [x] Finalize detailed mockup and callouts: https://zpl.io/VOOek8j or https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
@peggygannon I reviewed your edits in more detail today.

1. I really like moving the "fill out this brief questionnaire at least [X] days" to the beginning. It was highlighted as one of the most important pieces of information in usability testing. That said, this questionnaire is only "brief" at this time. Once we add in everything, it could get long. I'm ok with leaving "brief" in the text for now, but we will have to remember to come back to this page later.

2. We are now missing the second most important finding from usability testing related to wording. A lot of Veterans were confused about when a doctor would review their answers to the questionnaire. Roughly half assumed that the doctor would review it with 24-72 hours after submission. The clinician will only really review this in time to discuss it during their appointment (potentially immediately before or the morning of the appointment). This is why we wanted to highlight (bold) the text "Your provider will discuss the information on your questionnaire during your appointment." We wanted to help set expectations. If there is a more eloquent way to word this expectation that would be great, but I think that we need to address this with the text.

3. About the CTA button...100% of users didn't read this page and just clicked the button. Therefore, the team talked about only having one button at the bottom. You have shortened the wording a lot, so I don't believe that it would be too horrible to scroll through this even on a mobile device. The product team and Ming are onboard with this.

4. About the 911 box, we did get feedback on that box. Again, most Veterans completely ignored this box. The comments that we did get went like (and I'm paraphrasing)...
"I already know that." or "This is standard stuff that I expect on a government site and I don't really read that part."
I do agree that it does seem a little out of place. People will have an appointment already set up for all of our current questionnaires. I don't know what the privacy/security group would say, but it also help set the expectation that this is not to be used for emergencies and clinicians won't look at your answers immediately.

5. About the order of the information...after usability testing, I proposed the order shown in this image. I would just be changing what you wrote around a little bit.

![After Usability - Introduction - Signed In.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/e9085fdc-0cde-4cf3-b5d6-fd532aa55097)

**Comment by kristenmcconnell** [comment]
@peggygannon I just added the updated Need help? wording to this story as well.

**Comment by peggygannon** [comment]
HI, @kristenmcconnell thank you for your feedback, especially about the findings from usability research. I'll take a look at your updated mockup and drop in feedback later today.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell I've responded above to your notes. It doesn't look like some of the new content is in this updated mockup. I've re-uploaded the document here with some tweaks you mention ^^

[Health care questionnaire landing page.V2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5575369/Health.care.questionnaire.landing.page.V2.docx)

**Comment by kristenmcconnell** [comment]
@peggygannon I incorporated your latest updates into the wireframes and uploaded everything to Zeplin. Attached is a copy of the updated Intro page. The H1 was discussed in ticket #15647.  

Speaking of H1s...
Our your final recommendations at this time, the following H1s.
Drupal page: Health questionnaires
Questionnaire list (the page full of all a Veteran's questionnaires in cards): Your health questionnaires
Our MVP questionnaire (the one shown on the attached intro page wireframe): Primary care questionnaires

Is the privacy text that you sent me for the Intro page also supposed to be used on the Drupal page for this feature?

If the above items are correct, then I think the only currently outstanding content piece (at this time) is the finalization of the first bullet of the privacy text.

![After Usability - Introduction - Signed In.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/acc6e1b0-3b24-4978-afd8-18e51702a62f)

**Comment by kristenmcconnell** [comment]
Reread some things from #15647. I'm fixing the H1s and breadcrumbs.

**Comment by kristenmcconnell** [comment]
@peggygannon I fixed the H1s and breadcrumbs based on #15647. I incorporated your latest updates into the wireframes and uploaded everything to Zeplin. Attached is a copy of the updated Intro page. 

Is the privacy text that you sent me for the Intro page also supposed to be used on the Drupal page for this feature?

If the above items are correct, then I think the only currently outstanding content piece (at this time) is the finalization of the first bullet of the privacy text.

Full wireframe set that you should be able to view (for reference): https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780

![After Usability - Introduction - Signed In.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/c8ecb912-4e4f-4bb7-866c-0d738220038d)

**Comment by kristenmcconnell** [comment]
Meeting with Amanda and Mark held Nov. 23 to review scope of changes and what FE stories need to be written. Call outs added to Zeplin file with list of changes needed as well. Complete list of changes sent out Amanda and Mark via vsa-clipboard Slack channel.
