### ISSUE TITLE
Implement Flipper Component for View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16302]
## Background
With the launch of the payment history feature very quickly approaching, we need to ensure there is plenty of time for implementation and testing of the flipper component on the current [landing page](https://www.va.gov/va-payment-history/).

## Goal
Create the initial components needed for the Flipper functions, button labels, a widget ID that PubWeb might need in order to implement for UAT.

## Considerations
- [Link to IA recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-payment-history.md)
  - Profile is currently point to the tool page in EBN
  - If logged in, what shows?

<details>
<summary>Screenshot of whole landing page with area outlined in red</summary>

![landing-page-feature-toggle.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/acc98fe7-8cbf-4053-b506-723b7be7dc91)

</details>

<details>
<summary>Screenshot of legacy pathway example</summary>

![ebn-login.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/c4976cd9-0ddb-43bc-ab69-564649630f1c)

</details>

<details>
<summary>Screenshot of new pathway example</summary>

![Screen Shot 2020-11-19 at 11.59.23 AM.png](https://images.zenhubusercontent.com/5d643dbea77bcf04870bc424/7d2d86e9-b3e7-4a4a-bbc8-983ba829e036)

</details>

## Tasks
- [x] Add the feature name to `vets-api` (in snake case) by updating [config/features.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml)
- [x] Add the feature toggle name to vets-website by updating [featureFlagNames.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/feature-toggles/featureFlagNames.js)

## Acceptance Criteria
- [x] Feature name has been added to `vets-api` in snake case in [config/features.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml)
- [x] Feature toggle name has been added to `vets-website`  [featureFlagNames.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/feature-toggles/featureFlagNames.js)
- [x] A PR has been requested for merging for each of the items above

**Comment by jason-gcio** [comment]
PubWeb should be able to get this in for us by next sprint (request #16957)
last usability will roll into UAT after security and privacy review
