### ISSUE TITLE
AE: Sprint 35

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#16311]
## Priorities
1. Outstanding tickets from sprint 34
2. Conduct MyVA Research sessions
3. Create MyVA Research Summary
4. DD for Edu prototype, usability platform review, and start recruiting
5. Preferred Medical Facility BE build
6. Preferred Medical facility project kickoff
7. Profile 2.0 enhancements

### Profile
**Design**
- [ ] [Design] Look into error messaging/location #10722 

**FE**
- [x] [FE] Profile 2.0 bug fix: Add 2FA prompt for when someone is LOA3 but not 2FA and is eligible for direct deposit #16218
- [x] [FE] Create comprehensive e2e tests for address validation #14987
- [x] [FE] Research structure of current Profile components #16346
- [x] [FE] Analytics data-layer implementation: Add error codes for address save failures to GA dashboard #16088
- [x] [FE] Add better handling when we cannot get contact info from VA Profile #16306 

### My VA redesign
**Design**
- [ ] [Design] Conduct research #15684
- [ ] [Design] MyVA Dashboard initial explorations: Research summary #15685
- [ ] [Design] MyVA Dashboard initial explorations: Make mobile design updates from research feedback #16327

**FE**
- [x] [FE] Improve My VA Dashboard Cypress tests #15740
- [ ] [FE] Rewrite existing e2e tests for the Dashboard in Cypress #16209 (optional)

### Direct deposit for edu
**PM**
- [x] Schedule/hold usability testing platform review #15686

**Design**
For Jim Adams:
- [x] Create EDU DD Prototype #16206
- [ ] Conduct Usability Sessions for EDU Direct Deposit #13812

### Preferred medical facility
**PM**
- [ ] [PM] Schedule/hold project kickoff - Preferred VA Facility #16328

**BE**
- [ ] Backend build #16107

### Analytics
- [x] Add error codes for address save failures to GA dashboard #16088

### Unplanned: QA, 508, bugs, or other fixes
- [x] Add and update analytics in connected apps and address validation #16565
