### ISSUE TITLE
[VAMC] Pre-Dual-State check list for Erie-health-care system [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16322]
## Issue Description
As a PAO stakeholder I need the new VAMC site implemented into Dual-State, so I can complete all final testing, validation, and training prior to going to GO LIVE

---
## Tasks
- [x] _Provide updated Run book/check list to VSA teams for review
- [x] Implement tasks in run book for Erie health care system_

## Acceptance Criteria
- [x] _Run book has been approved by teams and VHA for implementation of Erie health care.
**Understanding that Run Book is living document and may change before Erie health care has been brought to dual state.
