### ISSUE TITLE
Find VA Forms - Search MVP

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1632]
This page currently lives at https://www.va.gov/vaforms/. Search research indicates that the VA forms page consistently gets high organic search traffic. However, it has almost no or very little conversion value.  Because this page already gets high organic traffic and has high potential to provide better conversion: 

- we want to redesign experience on this page to the new VA.gov look and feel. 
- we want to create new content on this page to drive traffic to top tasks and to the top digital versions of form applications. 
- we want to add analytics tracking to all links and downloads.

**Search research attached as FYSA:** 
[Analytics Veterans Affairs Forms Page Organic Nov2018-May2019.pdf](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3352350/Analytics.Veterans.Affairs.Forms.Page.Organic.Nov2018-May2019.pdf)

[vaforms-org-search-keywords-SEMRush.png](https://user-images.githubusercontent.com/43381063/60547498-e08c8b00-9ced-11e9-8962-4c37d0e8e3cd.png)

### Default state
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/02e0ab3c-baa2-40fc-85f2-a95b4f29c9f3)

### Search state
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/e389e8a0-f249-4bca-9428-6517bcfd3636)

## Def of Done - task list
- [x] Find stakeholder or team
- [x] Draft content 
- [x] Draft design
- [x] Identify requirements around new/proposed and current forms results columns
- [x] Soft launch (Ticket #6317)
- [x] Work with form owners to provide online tool links, if online version exist (Does this require backend work to create a flag and display the online app link with results?)
- [x] Finalize content and design based on SME reviews and requirements
- [x] IA check with Mikki, plus URLs to retire and redirect
- [x] 508 audit
- [x] Add analytics
- [x] Add redirects and retire pages if needed
- [x] Communicate to form owners to remove outdated or duplicate forms; update non-compliant forms

Also tracked in Master DEPO intake board: 
https://github.com/department-of-veterans-affairs/digitalservice/issues/921

**Comment by Karak888** [comment]
We have 2 Epics for Redesign find a form page - one is older but has all of the mockups and comments with it. However it is too long and outdated, and the one I started has all of our newer tickets associated with the Epic.  So, I am going to include the URL for #1482 here https://app.zenhub.com/workspaces/vft-but 59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1482, and will include all of the historical information from #1482 and associate it with this Epic #1632.  Moving forward please use this Epic for tracking issues / stories, etc. Thank you!

**Comment by ncksllvn** [comment]
Hey @mnorthuis, we created a ticket for you to determine the URL for which this new page will live - https://github.com/department-of-veterans-affairs/va.gov-team/issues/3548

**Comment by ncksllvn** [comment]
Hey @artsymartha68, can you link me to the designs for this page (the "Find a VA Form" page)? I've bounced across tickets and I found some designs, but I don't think I've found the right ones.

**Comment by artsymartha68** [comment]
@ncksllvn Are you referring to the search page or the form "landing page"? If it's the latter then https://github.com/department-of-veterans-affairs/va.gov-team/issues/2691 and I worked on this. 

If it's the former, then I think we need to ask @rtwell or @jenniferlee-dsva as to the final design spec. https://github.com/department-of-veterans-affairs/va.gov-team/issues/1482

**Comment by jenniferlee-dsva** [comment]
Hi @ncksllvn - The page/s you are building as part of [this ticket 2340](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2340) are the search page and the search results view of that same page: https://www.va.gov/vaforms/   

You can find @rtwell's design mockups and the copydeck on ticket 2340. (We're still working on finalizing the layout and content elements of the "form detail landing pages" -- the pages Martha and Laura are on -- so we're not ready to build those yet. We'll create another ticket for those.) 

RE Nick's comment to @mnorthuis about IA - I would assume the  URL would stay what it is today va.gov/vaforms/  But I'd love your help on addressing  a weird forms search-action.asp URL; it is actually sucking up organic search traffic, and I think it could be solved by making the default /vaforms URL canonical and permanently redirecting the action.asp page to it...?

**Comment by ncksllvn** [comment]
Ah I see - thank you @artsymartha68 and @jenniferlee-dsva!

**Comment by mnorthuis** [comment]
@jenniferlee-dsva can you provide some of your thoughts around why you would like to keep the same URL versus using a URL that follows our standard approach for all other WBC pages?

**Comment by jenniferlee-dsva** [comment]
I'm open to your thoughts on this. The reason I assumed we might want to keep the current URL is that it currently has a lot of organic search value. I guess we can still maintain value by doing redirects and such but if we're able to do this without redirects...? Not sure.

 https://www.va.gov/vaforms/
https://www.va.gov/vaforms/search_action.asp 
•	Above 2 pages appear to compete for search traffic, but the search_action page does not enable users to search easily (it hides the search function at the bottom of page). It will also omit important new conversion/actionable content that we’re adding to the redesigned forms search page.

**Comment by ncksllvn** [comment]
Hey @rtwell, any chance you can provide the text from the mockups so that I can copy them into Drupal?

**Comment by ncksllvn** [comment]
(Actually, if you could follow-up over at https://github.com/department-of-veterans-affairs/va.gov-team/issues/3604, that would be awesome. That's the ticket for creating this page as a draft in Drupal.)

**Comment by rtwell** [comment]
Find VA forms

Search for a VA form by keyword, form name, or form number. Many form tasks can now be done online like requesting a copy of your medical record or updating your address for your VA prescriptions.

Top tasks for frequently downloaded VA forms

Whether you’re looking for a form to file a disability claim or apply for the GI Bill, many top tasks are now also available as secure online applications. 
To get started online, go to a top task below. We’ll walk you step-by-step through the process. You can even save your work online and come back to it later. 

Keyword, form name, or number
Showing results for “10-10EZ”

File a VA disability claim 
Equal to VA Form 21-526EZ

Apply for the GI Bill and other education benefits 
Equal to VA Forms 22-1990 and 22-1995

Apply for VA health care benefits 
Equal to VA Form 10-10EZ

Update basic information online
Need a copy of your medical record or need to update your address for your VA prescriptions? You can now do many form tasks online. 
To keep things secure, sign in with your DS Logon, My HealtheVet, or ID.me account. If you don’t have an account, we’ll prompt you to create one.

Change your direct deposit information 
Equal to VA Form 24-0296

Change your address 
For disability compensation, claims and appeals, VA health care, and more

Request your medical record 
Equal to VA Form 10-5345

Request your military records, including DD214 
Includes DD214, DD215, release papers, orders and endorsements, and more

**Comment by ncksllvn** [comment]
You rock @rtwell!

**Comment by jenniferlee-dsva** [comment]
The mockups do not have the latest copy @ncksllvn. Per somewhere else (lol), you can find the copydoc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-forms-slp-conversion-paths-110519.docx

**Comment by ncksllvn** [comment]
Thanks @jenniferlee-dsva! I'm not worried about it being anywhere close to final or anything right now. I just need something to help scaffold the content in Drupal.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn @rtwell - Sorry for scope creep, but there are 2 more elements that we need to include in the design and build of the forms search/results page. 

**1/ Email mechanism that lets ppl email the VA forms managers VaFormsManagers@va.gov.**  
@rtwell - I don't know what the design should be for this or if it should just be a text link at the bottom of the page. (On the current live page, they have it just as a line of text with an email link.) What do you think?  

**2/ Foresee satisfaction feedback widget (see screenshot).** 
This would need @JeffBarnesUSDS and for you @ncksllvn to build. (We need analytics on this page, too, but that needs to be a separate ticket for sure when more of the page is built.) 

![image](https://user-images.githubusercontent.com/43381063/69430529-d5b9ad80-0d03-11ea-903f-a7464130f0fe.png)

**Comment by rtwell** [comment]
imo email interaction should be a link at the bottom of the page. Lemme know what the words should be and i'll find a home for it ❤️

**Comment by ncksllvn** [comment]
@rtwell should the blue boxes under the `Top tasks` section be considered for the Design System at all? 

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/a4a6fc49-056c-4f8a-8bf4-000cbf37a89f)

(Ignore the purple color - this is the "visited" state that I just haven't overridden yet.)

**Comment by rtwell** [comment]
they are in the queue! tyvm @ncksllvn

**Comment by ncksllvn** [comment]
Awesome! I built these so that they should be pretty easy to pull out of the rest of the code. Should the whole blue be a link, or just the heading? I was thinking the whole thing with a hover effect on the background. Doesn't need an answer right this second though!

**Comment by rtwell** [comment]
hmmmm good question! i was also entertaining the idea of the entire bkgd as a clickable area. 

a quick nit-picky note: could we equalize the space above/below the rule? i know the underline throws off the visual, but it still looks uneven. 

also, any chance we can make the headers a lil smaller, and Source Sans (like the mock)? i think we have a `h style` that should work

**Comment by ncksllvn** [comment]
> a quick nit-picky note: could we equalize the space above/below the rule? i know the underline throws off the visual, but it still looks uneven.

Do you mean to add some more margin above the underline? I can do that.

> also, any chance we can make the headers a lil smaller, and Source Sans (like the mock)? i think we have a h style that should work

Sorry, the mockup images I found were a little grainy, so I couldn't tell. I'll update that.

Is this better?

![image](https://user-images.githubusercontent.com/1915775/69553655-862aea00-0f6e-11ea-8648-9425023264cf.png)

**Comment by jenniferlee-dsva** [comment]
@rtwell @ncksllvn - I second making the entire card clickable area. 

@rtwell - copy for email feedback (sorry for the delay - holiday + sick). Somewhere at the bottom of the page:
"Questions or feedback about forms? Contact us"  -->mailto:VaFormsManagers@va.gov

**Comment by ncksllvn** [comment]
@rtwell @jenniferlee-dsva  I think we should try consolidating the design of the blue boxes under "Top tasks"  with the ones under [Pittsburgh Health Care](https://www.va.gov/pittsburgh-health-care/health-services/). Then I think we can store those Top Tasks in Drupal.

More info here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/4913

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - sorry, don't understand what you mean by:
>"we should try consolidating the design of the blue boxes under "Top tasks" with the ones under Pittsburgh Health Care. 

Are they not using the same design? RE storing them in Drupal - I would also prefer that. Have asked in #4931 if that Drupal component is available on VA.gov.

**Comment by MickinSahni** [comment]
Grooming notes:
   *  Epic is large — captures 2 separate launches: form detail and search
   *  We could split up and write the separate epic/tickets for launch!
       *  Will be blocked until search functionality is squared away (see #5277)
   *  Mickin to work with Nick to flesh out those 2 separate launches/epics (and whatever tickets we'll need)

**Comment by MickinSahni** [comment]
This epic has primarily included the search aspect of Find VA Forms. 

- Q: how are results sorted by default? do we incorporate click-through or download rate?
  - A: it's currently sorted on form number (https://staging.va.gov/find-va-forms-beta/?q=health) 

- Constituent tickets:
  - Decision ticket 
      - who will update Lighthouse API to treat input as list of terms (rather than compound) (backend)
      - not include keywords in MVP (this is heavier and likely not necessary for launch. see nick's analysis 👆)
  - New ticket for update to Lighthouse API re: "health care" (if we're gonna do it)

**Comment by MickinSahni** [comment]
- What’s left for us to launch the Search MVP?
    - Consider spaces in queries <— next Bet to reach parity between legacy form search results and new Find VA Forms
    - Re-evaluate search results between legacy and staging (2/28) (perhaps a separate ticket for us to test top 5 forms? + other queries)
        - 76 forms getting >= 10k searches per year
        - If not good, consider how we’d get access to `keywords` from the Forms DB <— this would be our subsequent Bet
        - If results are consistent, 
            - Invite members of the form working group to test (feedback by 3/4)
            - Launch!

**Comment by jenniferlee-dsva** [comment]
I'm not sure how to pull Jennifer Strickland's post-launch 508 test ticket into our board's view, so I'll reference it as a new/different post-launch ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8694

I think this 'launch' epic can be closed after [#5589](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5589) is validated, but would like to review with @ncksllvn and team that there aren't any smaller search tickets that need to be completed as part of launch.  Anything that's more 'enhancement' related, we can group into a post-launch iterations ticket/epic.

**Comment by MarciMcGuireGCIO** [comment]
Moved Sitewide items to sitewide epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/16897; moved remaining 508 issue into a post-MVP epic.
