### ISSUE TITLE
Create Cypress Environment Variables for Viewport Groups

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#16330]
## High Level User Story/ies
As a frontend engineer who writes e2e tests in Cypress, I need Cypress environment variables that point to an array of ‘all’, ‘top5’, and/or ‘top10’ viewports used by ga.gov users, grouped by mobile, tablet, and desktop so I can easy iterate through the applicable viewports for each test I write, when appropriate.

## Issue Description
Currently, a list of viewports to run Cypress e2e tests against isn’t readily available to frontend engineers on VSP. Additionally, an easy, standardized method for running Cypress against multiple viewports doesn’t exist.

---
## Tasks
- [x] Obtain list of ALL mobile viewports or device names
- [x] Obtain list of ALL desktop viewports or device names
- [x] Obtain list of top 5 mobile viewports or device names
- [x] Obtain list of top 5 desktop viewports or device names
- [x] Create the following Cypress environment variables in config/cypress.json: allMobileViewports, allDesktopViewports, top5MobileViewports, top5DesktopViewports. Each variable will be an array of viewport names or dimensions. (Cypress supports a number of viewport preset names for the most popular mobile and desktop devices.)
- [x] Using the newly provided environment variables refactor the following spec which currently manually sets the viewport to various mobile dimensions - /Users/holdenhinkle/Documents/Oddball/va_website_docker/vets-website/src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js The Cypress documentation provides an example of how to iterate through an array of viewport names or dimensions here - https://docs.cypress.io/api/commands/viewport.html#Dynamically-test-multiple-viewports

## Acceptance Criteria
- [ ] The config/cypress.json file will be updated to include above-mentioned environment variables.
- [ ] An existing Cypress spec file will successfully be refactored using this new approach
---
## How to configure this issue
- [ ] [Create Helper Functions for Cypress)](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15835undefined)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Submitted PR - https://github.com/department-of-veterans-affairs/vets-website/pull/15006

**Comment by holdenhinkle** [comment]
PR approved, merged and squashed. This ticket can be closed.

**Comment by holdenhinkle** [comment]
Comments from today's demo:

Rachael asked how we're going to enforce the use of these new env vars and presets.

Ideas:
Custom eslint rule (Peter, good idea)
Manually scan code using regex to make sure the viewport isn't being hardcoded in any tests (Holden, not so great idea)

- -

Send announcement in VFS All Teams on Monday about these new features.
Joe is going to make sure that's okay.

**Comment by holdenhinkle** [comment]
Just submitted new PR - https://github.com/department-of-veterans-affairs/vets-website/pull/15107

# I refactored the following:
- `config/cypress.json`
- `src/platform/testing/e2e/cypress/support/commands/viewportPreset.js`

## cypress.json
- Removed `allIPhoneViewports` env var because we don't want people to use it.
- Renamed the viewport env vars. Removed `5` from the name so we can add more than 5 if the need ever arises.
- Added `rank` and `list` properties to each viewport object
- Renamed `name` to `devicesWithViewport`

## src/platform/testing/e2e/cypress/support/commands/viewportPreset.js
- Removed iphone and ipad presets because we don't want people to use them
- Renamed the preset vars. Removed `Top5` from the name so we can add more than 5 if the need ever arises.

**Comment by pjhill** [comment]
Original and Refactor PRs merged
Detailed tasks completed
Created a [follow-up ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16980) to measure the use of these viewport environment variables
