### ISSUE TITLE
FSR - Incorporate content changes

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#16339]
## Issue Description
Before usability, we need to update our design files with the most updated content.

---
## Tasks
- [ ] Incorporate content changes provided by Susan in the UXPin comments
- [ ] Send to Susan to review (incorporations only where necessary / major)

## Acceptance Criteria
- [ ] Content changes incorporated into Sketch files and synced to UXPin
- [ ] All comments checked off in UXPin

**Comment by rebeccawalsh** [comment]
*Most* content comments left on the [UXPin prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701647/comment/comments,sitemap?mode=i) have been incorporated and closed out (green checks)

Due to some blocking decisions about 'debt' terminology, not all content has been incorporated to prevent extra rework. Comments on the content pages and the introduction page haven't all been incorporated, pending a decision.

@3obryandogs There are a couple of comments open throughout the prototype where you and I were discussing things. Go ahead and look through them, add any additional information where, and close out the ones that are no longer issues.

@leahkeeler Let me know what you'd like to do with this ticket. Because I was doing some design cleanup and jiggle-fixing while doing these content updates, I spent a lot of time on this during this sprint. If we want to close this one out and create a second pass content fix ticket, that wouldn't boot out a ticket that's 90% done.

**Comment by 3obryandogs** [comment]
@Rebecca Walsh<mailto:rebecca.walsh@adhocteam.us> I’ve taken care of several comments. There are a few deeper in the document, but most (especially on the first few pages) won’t be resolved until we get the “debt” question answered.

**Comment by rileyorr** [comment]
Think the outstanding work from this ticket has been moved to [#16828](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16828). Gonna move this to validate!
