### ISSUE TITLE
FSR - Create usability conversation guide

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#16335]
## Issue Description
_To kick off usability testing for FSR, we need to write a research plan using [the provided template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)._

---
## Tasks
- [x] _Write a conversation guide for the FSR usability test study._
- [ ] _Send the completed conversation guide to Shawna for feedback._
- [ ] _After the conversation guide is approved by Shawna, send the document to Lauren to kick off the recruiting process._

## Acceptance Criteria
- [ ] _Shawna has approved the conversation guide._
- [ ] _The conversation guide is uploaded to GitHub and linked to this ticket._
- [ ] _The conversation guide is sent to Lauren._

**Comment by rileyorr** [comment]
Finished [the first draft of the conversation guide](https://docs.google.com/document/d/1tLJfovq-xn5G7Owtuj1lfu_rXnJe6OfEuiuz43TtI9Q/edit?usp=sharing). I think either tasks should be readjusted/cut or we should discuss sessions being longer than 60 min - the form is long and may take folks a while to get through.

**Comment by rileyorr** [comment]
[The conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/jan-2021/conversation-guide.md) has been uploaded to GH!
