### ISSUE TITLE
[FSR] Update CH2 with feedback & new list loop design

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#16337]
## Issue Description
_The design team has previously collaborated with VSP's accessibility team to design an accessible list loop component variation that aligns with the existing list loop's functionality. We need to incorporate the modified list loop into CH2's hi-fi designs. Additionally, we received feedback that splitting some of our questions to separate pages may ease cognitive load._

---
## Tasks
- [x] _Update CH2's hi-fi prototype with the modified list loop designs_
- [x] _Split the Veteran's employment history into two pages: one with gating questions and current employment fields, and one for additional jobs the Veteran has had within the past two years_
- [x] _Split the Veteran's other income into 3 pages with one question per page_
- [x] _Update the 'marital status' question to ask if the Veteran is unmarried, married, separated, etc._
- [x] _Split the spouse's employment history into two pages: one with gating questions and current employment fields, and one for additional jobs the Veteran has had within the past two years_
- [x] _Split spouse's other income into 3 pages with one question per page_

## Acceptance Criteria
- [x] _The hi-fi prototype has been updated and exported to UXPin_
- [x] _The updated UXPin prototype has been linked to this ticket as a comment_

**Comment by rileyorr** [comment]
I've finished incorporating all the feedback and updated list loops into what is now [a monstrous chapter](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410885/comment/comments,sitemap?mode=i) (12 pages not including the various states added to each page). I'll probably double-check my work with fresh eyes on Monday, but wanted to pop the update UXPin in here before signing off for the weekend.

**Comment by rileyorr** [comment]
Gave the design another spot check & made [a ticket for content review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16530).
