### ISSUE TITLE
Find VA Form MVP 1.0 508 Issues Discovery

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16331]
## Issue Description
As a Product Manager, I need to clearly understand the underlying nature and teams that will need to be involved in remediating existing 508 Accessibility issues from the Find a VA Form MVP 1.0 so I can coordinate with the correct teams and/or assign the work to my own team.

---
## Tasks
- [ ] Comprehensive matrix of all existing Find a Form MVP 1.0 508 issues
- [ ] A determination as to the origin of the issue -- back end, front end or CMS
- [ ] A clear indication as to which team(s) need to be involved in remediating and testing each issue
- [ ] Issues prioritized in order of importance

## Acceptance Criteria
- [ ] The Decision Tools team will know what work can be handled within the team, what work will need to be coordinated with other teams, and which need to be started on first.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
