### ISSUE TITLE
Cypress helpers hasFocusableCount and hasTabbableCount need input types added to the arrays of checked items

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#16338]
## Issue Description
During a pull request review, I noticed two Cypress helper methods **[hasFocusableCount](https://github.com/department-of-veterans-affairs/vets-website/blob/be526b55b52722c5d4a6ec50141334325a13192d/src/applications/gi/tests/e2e/cypress-helpers.js#L67)** and **[hasTabbableCount](https://github.com/department-of-veterans-affairs/vets-website/blob/be526b55b52722c5d4a6ec50141334325a13192d/src/applications/gi/tests/e2e/cypress-helpers.js#L93)** are missing a few input types in their arrays of checked items. This issue ticket is being opened to add those, and verify no tests break after the change.

---
## Tasks
- [x] Add 5 input types to the method arrays
- [x] Run all e2e tests locally to ensure no breaks
- [x] Modify any tests or or notify teams of breaking changes if previous item does cause breaks
- [x] Relocate this file to a location that is closer to the root of `vets-website` for example `/platform` since it applies to more than one product

## Acceptance Criteria
- [x] All Cypress e2e tests pass  on localhost or are updated to pass
- All Cypress e2e tests continue to pass in CI/CD pipeline

## Code Updates
```diff
! /src/applications/gi/tests/e2e/cypress-helpers.js#L67

export const hasFocusableCount = (selector, count) => {
  const focusableElements = [
    'a[href]',
    'button',
    'details',
    'input[type="text"]',
    'input[type="email"]',
    'input[type="password"]',
    'input[type="search"]',
    'input[type="tel"]',
    'input[type="url"]',
    'input[type="radio"]',
    'input[type="checkbox"]',
+   'input[type="number"],
+   'input[type="file"],
+   'input[type="date"],
+   'input[type="datetime-local"],
+   'input[type="month"],
+   'input[type="time"],
+   'input[type="week"],
    'select',
    'textarea',
    '[tabindex="0"]',
    '[tabindex="-1"]',
  ];
  const msg = `Page does not contain ${count} focusable elements.`;
  elementsWithinCount(focusableElements, selector, count, msg);
};
```

```diff
! /src/applications/gi/tests/e2e/cypress-helpers.js#L93

export const hasTabbableCount = (selector, count) => {
  const tabbableElements = [
    'a[href]',
    'button',
    'details',
    'input[type="text"]',
    'input[type="email"]',
    'input[type="password"]',
    'input[type="search"]',
    'input[type="tel"]',
    'input[type="url"]',
    'input[type="radio"]:checked',
    'input[type="checkbox"]',
+   'input[type="number"],
+   'input[type="file"],
+   'input[type="date"],
+   'input[type="datetime-local"],
+   'input[type="month"],
+   'input[type="time"],
+   'input[type="week"],
    'select',
    'textarea',
    '[tabindex]:not([tabindex="-1"])',
  ];

  const msg = `Page does not contain ${count} tabbable elements.`;
  elementsWithinCount(tabbableElements, selector, count, msg);
};
```

**Comment by pjhill** [comment]
While we are making changes to these helpers, let's consider relocating the file somewhere closer to the root. It's confusing to have these buried deep into the folder structure in a seemingly random product's folder.

One candidate for location suggested by Trevor would be the `/platform` folder. That sounds good to me.

**Comment by holdenhinkle** [comment]
@1Copenut I'm working on this and noticed that these two helper methods aren't being used anywhere. Yet. Just letting you know...

**Comment by holdenhinkle** [comment]
Testing @holdenhinkle Testing...

**Comment by 1Copenut** [comment]
@holdenhinkle Thank you, that's helpful. I noticed I'd missed a swath of focusable elements and figured I"d better get it logged while it was top of mind. IE, before teams started using it :)

**Comment by holdenhinkle** [comment]
Branch 16338_update_hasFocusablecount_and_hasTabbableCount_cypress_helpers

**Comment by holdenhinkle** [comment]
https://dsva.slack.com/archives/C01CHAY3ULR/p1607111188256700

Holden Hinkle  2:46 PM
I refactored the Cypress `hasFocusableCount` and `hasTabbableCount` helper functions by creating a Cypress custom command called `hasCount` - https://github.com/department-of-veterans-affairs/vets-website/blob/16338_update_hasFocusablecount_and_hasTabbableCount_cypress_helpers/src/platform/testing/e2e/cypress/support/commands/hasCount.js

Problem is, I don’t know how to test it because the current  `hasFocusableCount` and `hasTabbableCount` helper functions weren’t being used. I’d have to somehow find a page that has content that can be tested by this new custom command and write the tests. Should I do that? Is there a better way? Suggestions are welcome, if you have the time…

Waiting for response from community before proceeding.

I think I should submit a pull request for this and handle any bugs once the custom command starts being used...

**Comment by holdenhinkle** [comment]
My inclination is to submit a PR for this as-is (all current tests pass) and deal with any bugs that arise (I don’t think there will be any) when people start using the helper.

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/vets-website/pull/15204

Something that may be an issue:

Two files [from another branch](https://github.com/department-of-veterans-affairs/vets-website/pull/15162) that has already been merged ended up in this branch somehow and I haven't been able to remove them:
- config/cypress.json
- src/platform/testing/e2e/cypress/support/commands/viewportPreset.js

**Comment by pjhill** [comment]
Nice, these helpers have been relocated out of a specific product folder and into a more general use folder/file.  Reviewed
