### ISSUE TITLE
Confirm fwdproxy for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16341]
## Background
In order to meet the deadline for the CH31's submission, we need to confirm the configuration of a fwdproxy where our code is sending a payload to the VRE endpoint.

### Resources
- Conversation regarding FWD proxy: https://dsva.slack.com/archives/CLY6Q69RV/p1605210607227700
- link from Jeremy regarding FWD proxy: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml#L5-L16
- Docs about Proxies: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/da5a8e5c70ff4410687839e49dadd5adc28bd590/platform/engineering/TechnicalArchitectureOverview.md#forward-proxies-and-va-network

## Tasks
- [x] Check in with Jeremy Britt on latest progress 
- [x] Check in with Boris Ning as needed
- [x] Engage with other BE's about a checklist for moving forward

## Acceptance Criteria
- [x] Receive token back from auth endpoint
