### ISSUE TITLE
[DESIGN] Prototype for Veteran testing

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16347]
## Issue Description
Make final adjustments to prototype/wireframe for use in Veteran testing for the Vet Center initiative

---
## Tasks
- [ ] Iterate prototype/wire frame with final feedback before Veteran testing

## Acceptance Criteria
- [ ] Prototype/wireframe is available for testing

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@lildziner please link to your prototype

**Comment by lildziner** [comment]
This is a link to the [UXPin prototype](https://preview.uxpin.com/603da0b67ccefbbee74fcd8bb77a8fed12baabb5#/pages/134612636/simulate/no-panels?mode=cvhidmhttp:~2F~2Ff) used in user testing.
