### ISSUE TITLE
[FSR] Update CH3 with feedback & new list loop design

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#16340]
## Issue Description
_The design team has previously collaborated with VSP's accessibility team to design an accessible list loop component variation that aligns with the existing list loop's functionality. We need to incorporate the modified list loop into CH3's hi-fi designs. Additionally, we received feedback that splitting some of our questions to separate pages may ease cognitive load._

---
## Tasks
- [x] _Update CH3's hi-fi prototype with the standard list loop component recommended by the VSP design team as appropriate_
- [x] _Split each section (bank info, real estate, trailers/boats/campers, automobiles, other assets) onto separate pages_
- [x] _(Optional) Evaluate whether a list loop component is appropriately used in each section, and make adjustments as needed_

## Acceptance Criteria
- [ ] _The hi-fi prototype has been updated and exported to UXPin_
- [ ] _The updated UXPin prototype has been linked to this ticket as a comment_

**Comment by rebeccawalsh** [comment]
UXPin links:
- [C3P1: Bank information](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410684/simulate/sitemap?mode=i)
- [C3P2: Real estate](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410685/simulate/sitemap?mode=i)
- [C3P3: Trailers, boats, and campers](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410289/simulate/sitemap?mode=i)
- [C3P4: Vehicles](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410290/simulate/sitemap?mode=i)
- [C3P5: Other assets](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410291/simulate/sitemap?mode=i)
