### ISSUE TITLE
LOE to integrate Google Translate API in vagov.content repo

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16353]
## Issue Description
As we continue to explore the best way to offer translated content, we want to assess the LOE for integrating Google Translate API. **Note:** We also need to discuss and consider issues with content quality and ability to edit as well as questions around ability to use the API. This is an LOE ticket we can do in parallel with those discussions.

---
## Tasks
- [ ] understand how the alternate CMS works
- [ ] try to configure google translate api calls on english content
- [ ] enable edibility of spanish content

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
@youngfreezyVA could you provide an estimate on the work effort for this ticket?  Once selected please remove the 'needs grooming' label and we should be good for action this sprint cycle.  Thanks.

**Comment by youngfreezyVA** [comment]
after discussions with @kelsonic and @ncksllvn closing this out in favor of either a drupal or 3rd party solution (like prismic). edibility workflow of vagovcontent isn't scalable.
cc: @DanielleThierryUSDSVA
