### ISSUE TITLE
Create 2021 Disability rates pages in Drupal

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#16355]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _Clone current page and update content_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht here's the first set for review.
Veterans disability compensation rates
2021: http://preview-prod.vfs.va.gov/preview?nodeId=986
2020: http://preview-prod.vfs.va.gov/preview?nodeId=11075

**Comment by RLHecht** [comment]
@lunascoop These look good. will publish today. FYSA @bethpottsVADEPO

**Comment by lunascoop** [comment]
@RLHecht Here's the other pages
VA special monthly compensation rates
2021: http://preview-prod.vfs.va.gov/preview?nodeId=991
2020: http://preview-prod.vfs.va.gov/preview?nodeId=11080
2019: http://preview-prod.vfs.va.gov/preview?nodeId=4917 Updated second intro sentence to match language/copy on 2020 page

**Comment by RLHecht** [comment]
@lunascoop The special monthly rates look good too. I've published these. Moving this ticket to validate. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
These are live on the site. Closing ticket. FYSA @brianalloyd
