### ISSUE TITLE
Review Instances / Ephemeral Dev Instances - Tracking current issues and determining best path forward 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16350]
## Current Issues: 
- [x] [Unable to reach Review Instances (RIs) due to developer SSH keys not being correctly copied to instances #15634](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/15634)
- [x] ["502 Bad Gateway " error ue to inability to pull drupal cache #16637](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/16637)  
- [x] [Instance deployments failing with Jenkins exception #16734](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16734)

## Product Outline 
The product outline does not yet exist, but will be added once it's been developed - @jhouse-solvd
[Link to product outline template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## Documentation 
WIP: [Troubleshooting document](https://vfs.atlassian.net/wiki/spaces/VI/pages/805634072/Troubleshoot+review+instances+failures) hosted on Confluence
[Review Instances doc from the devops repo](https://github.com/department-of-veterans-affairs/devops/blob/329e14ac1d4c9eaff1d2377a0c36db1977e015ed/docs/Review%20Instances.md) (can potentially move to Confluence)

## High Level User Story/ies
As a developer, I need a way to test my software/configurations before production so I can release software that works.

## Hypothesis or Bet
**If** _we provide a good solution for teams testing their code before it gets to production_ **then** _we expect for it to be easier for them to develop new features / improve existing applications_.

## OKR
_O2: Make it easier and more satisfying to build and operate the DEPO Platform._

### What must be true in order for you to consider this epic complete? 

- [x] Documentation provided to users of review instances so that they understand how they work, and how to use them
- [x] Immediate technical issues resolved 
- [x] Initiatives created to support future work in the coming quarters
- [x] Stories and epics groomed to clarify roadmap for this solution
- [x] Product information shared with teams 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jhouse-solvd** [comment]
It appears that all of the current technical issues may be resolved as of this morning. _(Please see tickets above under "Current Issues" for more detail)_

We will groom remaining stories and continue to develop our roadmap for the near future, with the aim of improving this experience for platform users. 

Also, @drorva started a new [troubleshooting document here](https://vfs.atlassian.net/wiki/spaces/VI/pages/805634072/Troubleshoot+review+instances+failures), and we will synthesize other notes from recent efforts and ensure that teams have access to documentation surrounding how the solution operates now, and in the future.

**Comment by jhouse-solvd** [comment]
[From a member of the VSA Healthcare Experience Team:
](https://dsva.slack.com/archives/CBU0KDSB1/p1607115799145600?thread_ts=1607112235.125900&cid=CBU0KDSB1)

"I have very high expectations and for the record, I want a review environment where the bit of code I wrote can be tested/reviewed by all stake holders EASILY and I want said review environment to be able to talk to and interact with  all of the systems that a similar production/staging instance/container can talk to!"

**Comment by mpelzsherman** [comment]
I thought there was an agreed-upon solution for allowing stakeholder access (using Github authentication).

See https://vfs.atlassian.net/wiki/spaces/VI/pages/976781382/Tool+Logins

**Comment by jhouse-solvd** [comment]
@mpelzsherman - because of where the review instances (RIs) currently live (vpc/env), there is work to be done to figure out how to enable something like GH auth, as well as access to all of the network paths that RIs need to function in the way that is expected. 

Ops has been working with @drorva to discuss the best path forward, and have a spike forthcoming to help us investigate if we can move RIs to another network segment that so that this can be made possible. 

add'l details here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22545

**Comment by ph-One** [comment]
Items completed [across multiple teams].
