### ISSUE TITLE
Update Pension Eligibility Questions Default Values 

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#16364]
## Background
Pension eligibility questions were added to the 686, but some questions were only added for certain workflows.  When the eligibility answers are sent to BGS, they are converted from true/false values to Y/N.  Testing needs to be done to ensure that a default value is not being sent inadvertently for workflows where that question was not added.  

## Considerations
- Questions are set to optional
- If nothing in from FE, BE should not send a response.
- Does it matter if a default value of "N" is sent?  Is an empty string or _nil_ value preferred?
  - We don't want to imply that the Veteran has said anything if not asked, or skipped

## Tasks
- [x] Check every workflow and determine whether the pension is being asked for that workflow.
- [x] If the question is not being asked on the FE, make sure a default value of "N" is **not** being sent (empty string or nil).

## Acceptance Criteria
- [x] Write tests for coverage, if needed
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5392
