### ISSUE TITLE
Set Document Type for 686 Supporting Evidence

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#16362]
## Background
When uploading supporting evidence to VBMS, there is a "document type" field that should be set.  Some examples are marriage certificate, birth certificate, etc. 

## Considerations
- FE: Do we know what type of document the user is uploading?  
  - If not, what would it take to add this?
- If **no** doc type gets submitted, does it fail?
- Check with Mike Walker (in #evss-dev channel in Slack) for a complete list of doc types ✔
**We have the types in hand**
- Design/Eng Spike on how uploads are being handled

## Tasks
- [x] Investigate how other forms are adjusting form types on submission
- [x] Check to see what type of supporting documents are attached to the claim.
- [ ] Investigate what happens when a doc type is not attached (ask Christine or Liz at RBPS)
- [ ] Set the appropriate doc type when uploading supporting evidence to VBMS for the 686.

## Acceptance Criteria
- [x] Findings have been documented in GH under {feature-name}/engineering

### Next steps
- [ ] Documents get uploaded to VBMS with appropriate type
- [ ] Write a test for coverage, if needed
- [ ] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
![Screen Shot 2021-01-20 at 11.35.47 AM.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/0a6f80d7-0040-4fea-93af-4916ffb8a28b)

**Comment by kathleencrawford** [comment]
![Screen Shot 2021-01-20 at 11.38.56 AM.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/fbba435f-51a0-436e-95b9-935ca0d0be93)

**Comment by kathleencrawford** [comment]
![Screen Shot 2021-01-20 at 11.40.05 AM.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/5d337150-2d0b-4f56-9bbe-f6fa059e77e7)

**Comment by kathleencrawford** [comment]
![eben 686 doc screenshot.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/65bc1a2a-5639-41cc-ad0d-0a08db59df87)

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-supporting-evidence.md
