### ISSUE TITLE
VA.gov Search Click Tracking API - Backend Development

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16367]
## Issue Description
Search.gov -- which powers VA.gov site search -- has completed development and soft launched API-based [click-tracking](https://search.gov/manual/clicks.html) to enable "closed loop" analytics.   They have asked VA.gov, along with other agencies, to test the capability.

The click tracking API endpoint lets you send in click events, which allows you to see click data on your Admin Click Analytics page. We also use this click data to strengthen the search results algorithm for your site.

The Click Track API instructions are attached for implementation and validation.

[Search.gov - Click Tracking API Instructions (Beta).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5393167/Search.gov.-.Click.Tracking.API.Instructions.Beta.docx)

## Front end tasks
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests

## Acceptance Criteria
- [x] Success - A response status code of 200 and empty body.

- [x] Missing Required Parameters - A response status code of 400 and an error message describing the missing parameters. ["Query can't be blank"]

- [x] Invalid Or Inactive Search Site Handle - A response status code of 401 and an error message. ["Affiliate is invalid"]

- [x] Invalid API Access Key - A response status code of 401 and an error message. ["Access key is invalid"]

- [x] Unparseable URL - A response status code of 401 and an error message. ["Url is not a valid format"]

* ●	Invalid Module Code - A response status code of 401 and an error message. ["Module code {MODULE} is not a valid module"]​

**Comment by denisecoveyduc** [comment]
Search.gov team conducted validation testing on click tracking - details discussed in #14955 @srsuddath there may be some details mentioned my Nick and others that are helpful to review during implementation.

**Comment by denisecoveyduc** [comment]
@srsuddath will be able to proceed with this once the platform team has completed the efforts in #17009. He is blocked until that has happened. Platform team anticipates this will wrap up in sprint 37 and the search and discovery team's goal would be to implement click tracking before code freeze if possible.

**Comment by srsuddath** [comment]
This is now more of a verification ticket due to the backend work being shifted to the platform team. The acceptance criteria are the same, but I will be validating rather than implementing.

**Comment by srsuddath** [comment]
This endpoint has been created, so this ticket can be closed
