### ISSUE TITLE
[Chapter 31] - Add VRE to Pager Duty for downtime notification

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#16368]
## Description
VR&E needs to be added as an external service to Pager Duty so we can take advantage of maintenance windows in `vets-website`. 

## Considerations
- [List of external services in the devops repo](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L300)
- [List of external services in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/DowntimeNotification/config/externalServices.js)

## Tasks
- [x] Work with Ops to have VR&E added to Pager Duty. [Helpful conversation from when we needed BGS added](https://dsva.slack.com/archives/CBU0KDSB1/p1597259128386900)
- [x] Add VR&E to the vets-website list of external services [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/DowntimeNotification/config/externalServices.js)

## Acceptance Criteria
- [x] VR&E has been added to Pager Duty
- [x] Pull requests have been submitted to the devops and vets-website repos.

**Comment by micahchiang** [comment]
Closing this for now, as we have all the necessary pieces in place to create and display maintenance windows using PagerDuty. A potential future enhancement is to [add automatic alerting on degraded service for VRE](https://dsva.slack.com/archives/CBU0KDSB1/p1621879383346100?thread_ts=1618429325.452000&cid=CBU0KDSB1)
