### ISSUE TITLE
Build Out Orientation Component and Update Wizard for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16365]
## Background
Now that we have a hypothesis for how to place the videos, we need to put them in place on the FE, beneath the wizard. The orientation content should be hidden until the wizard has been completed and a veteran is eligible for chapter 31 benefits. 

## Considerations
- Based on the mockup (https://xd.adobe.com/view/aaf3f28b-b763-4c16-ba02-d1d47e20328e-ffa0/screen/93e3c3c8-b675-4148-a70f-83fb9791ffea) we need to get the content in place
- [link for actual content is with Jason]
- existing PR for proof of concept - https://github.com/department-of-veterans-affairs/vets-website/pull/14761

## Tasks
- [x] take existing proof of concept and drop it beneath wizard 
- [x] include [segmented progress bar](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/segmentedprogressbar/) to represent total number of steps
- [x] modify sessionStorage cookie for chapter 31 wizard so it is always shown
- [x] remove button at the end of the chapter 31 wizard that allows the user to go to the form introduction page
- [x] show orientation component once a user completes the wizard. 

## Acceptance Criteria
- [ ] The Orientation content is shown after completing the wizard
- [ ] Pull request has been submitted to vets-website
