### ISSUE TITLE
Identify KPIs for search (onsite + offsite)

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16360]
## Description
Leverage data from analytics review to define KPIs for enhancing search and discovery features for both onsite -  on VA.gov and also offsite - using Google, Bing and others. 

## Background/Context/Resources
Initial KPI focus areas can be seen in S+D Overview Deck.

## Tasks

- [x] Collect key data metrics that highlight how veterans are using search and looking for information both on VA.gov and on google etc. 
- [ ] Sync with analytics team to identify outliers and possibilities
- [x] Add additional key metrics to what exists today on S+D Overview Deck
- [x] Review and select the right set of metrics that we want to track for our KPIS
- [x] Discuss with team to ensure consensus and alignment

## Definition of Done

- [x] A set of KPIs have been defined and agreed upon by stakeholders

---

## How to configure this issue

- [x] **Labeled with Team** (`vsa-search-discovery`)

- [x] **Validate pipeline placement** (Is the issue placed in the proper pipeline?)

- [x] **Labeled with Practice Area** (`development`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `accessibility`, `content`)

- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

- [x] **Attached to a Milestone** (When will this be completed?)

**Comment by denisecoveyduc** [comment]
KPIs for Onsite search have been established but offsite search KPIS will be prioritized in the later half of 2021. As a result, we are extracting the offsite search KPIs in #17535
