### ISSUE TITLE
[DISCOVERY] Evaluate Campaign Landing page template for use with Vet Center product

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16372]
## Issue Description
We are trying to solve for a fundamental lack of awareness about Vet Centers, the services they offer, and how they are different from the services offered at medical centers. 

The Campaign Landing template may be an opportunity for this centralized information. 

---
## Tasks
- [ ] Evaluate the [Campaign Landing page template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/CLP-Maximal-markup.png) to determine suitability 
     - Can the required components be used for this need? 
- [ ] Connect with John Hashimoto and CMS to understand the current status and options for this template. 

## Acceptance Criteria
- [ ] Review template
- [ ] Document questions for Jon and CMS in this issue
- [ ] Decision regarding path forward
      - If the CLP template **_does not_** make sense for a centralized page about Vet Centers, we will proceed with a prototype which overtly contains content to educate about Vet Centers until we are able to create a different type of page to fulfill this need
       - If the CLP template _**will**_ fulfill this need, we will use light touch on Vet Center pages and link to this central CLP page
     

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
CLP will not work as a replacement for vetcenters.va.gov.
Jen Lee is looking into whether the resource center could be used for this information or if we need to begin to investigate another solution for the future.
