### ISSUE TITLE
Yellow Ribbon Analytics Discovery

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16370]
## Issue Description
Determine user behavior, actions, analytics metrics we want to track in the Yellow Ribbon schools search tool

---
## Tasks
- [ ] What questions do we need answered?
- [ ] What metrics do we need to capture so that we can show improvement?

## Acceptance Criteria
- [ ] We will have a curated list of questions that we want to be able to answer with Google Analytics
- [ ] We will have a curated list of metrics we want to start capturing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
