### ISSUE TITLE
Sentry SSOe Error Cleanup

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#16388]
## Issue Description
This is one of many issues that are a result of research into the `SSOe error:` we see within Sentry [here](http://sentry.vfs.va.gov/organizations/vsp/issues/?project=3&project=4&query=is%3Aunresolved+assigned%3A%23vsp-identity+level%3Aerror+message%3A%22SSOe+error%3A%22&statsPeriod=14d). The changes proposed will reduce the error level for some of the typeerrors being reported from `error` down to `warning` or `info`. Further research will continue and more PRs will be added to this issue for reference. 

This issue in isolation often causes significant research time to determine the validity and ability to take action regarding the errors shown within sentry. The issue is specific to the `SSOe Errors` however several other issues will be documented to complete the cleanup of all Identity related Sentry errors.

---
## Tasks
- [x] Research Sentry `setlevel`
- [x] Determine if additional context can be obtained from TypeError
- [x] Correct the error levels for all `SSOe errors` to ensure appropriate response occurs
- [x] Merge, as appropriate, SSOe errors to ensure they are tracked appropriately within Sentry

## Acceptance Criteria
- [x] Errors will be classified correctly within Sentry
- [x] Errors will have more context to ensure the Identity team is able to properly resolve issues discovered via Sentry
---
## How to configure this issue
- [ ] **Attached to a Milestone**
- [ ] **Attached to an Epic**
- [x] **Labeled with Team**
- [x] **Labeled with Type**

**Comment by AGarcia-Clarity** [comment]
I think this ticket might be able to be closed as it has already been merged in with the above issue on GitHub.
