### ISSUE TITLE
Default search area for secondary searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16380]
## Issue Description
The purpose of allowing a Veteran to initiate a search following zooming or panning is to adjust the search parameters by interacting with the map.

However, we've identified two scenarios which need to be considered - 
1. The Facility Locator has a default bounding search area which applies even after exploring an area with close zoom level before triggering another search. As a result, the map zooms out and searches with the default bounding box. 
We need to determine ideal Veteran experience for this scenario- what should the default zoom area be for secondary searches?
_Decision made during grooming-> The search area should be determined by the map when the secondary search is triggered (need to confirm this will be supported by Lighthouse API)_

2. We've inadvertent made it possible to zoom the view out to large regions (or the entire country) and then trigger a search. This isn't intending functionality and won't return meaningful or performant results.
Should the ability to zoom be limited?-> 
_Decision made during grooming -> max bounding area will be limited to 500 miles in diameter (width of map is 500 miles maximum) - after this, the zoom buttons are no longer available. A Veteran can still pan the map and if so, the "search this area" button becomes available._ 

---
## Tasks
- [ ] Reflect map area for zoom following secondary searches
- [ ] Limit maximum bounding area to 500 miles in diameter
- [ ] Ensure the "search this area" button appears after a Veteran zooms or pans the map

## Acceptance Criteria
- [ ] When a Veteran pans the map (within 500 miles) after initial results are displayed, the "search this area" button appears 
- [ ] When a Veteran zooms the map (within 500 miles) after initial results are displayed, the "search this area" button appears
- [ ] The search area button is only available within a 500 mile bounding area
- [ ] When a Veteran triggers a search using the "search this area" button, the results are displayed on a map that reflects the zoom level/pan area set by the Veteran for the newly triggered search 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
