### ISSUE TITLE
Left Nav on level 4 VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16393]
## What happened?
The Left Navigation menu was not intended to appear on VAMC pages deeper than L3. The spoke label "ABOUT VA PITTSBURGH" is counted as 1 - even though it's not clickable.

However, the Left Nav appears on [example level 4 page] (https://www.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/psychology-internships-and-fellowships/). 

![image](https://user-images.githubusercontent.com/55411834/99600505-c888da80-29ba-11eb-8356-1caf455ea16d.png)

This was based on a belief that the Left Nav could not indent to this level. this page proves it is possible so we need to determine the intent given this new information. 

[Link to Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1605737661089700?thread_ts=1605733478.079900&cid=C0FQSS30V)

## Tasks
Determine intended behavior for Level 4 pages
Identify the pages which need to be changed as a result of this decision

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**
