### ISSUE TITLE
Release map enhancements to Prod

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16392]
## Issue Description
Once the map enhancement changes are complete and validated, we need to release the new experience to Prod. 

---
## Tasks
- [ ] Check on status of CSP error to be sure this will not occur on Prod. 
      - [Link to Slack thread #1 with VSP](https://dsva.slack.com/archives/CBU0KDSB1/p1604435610493100) and {Slack thread #2](https://dsva.slack.com/archives/CBU0KDSB1/p1604508278056900?thread_ts=1604435610.493100&cid=CBU0KDSB1)
- [ ] Deprecate old map
- [ ] Update test cases for new map
- [ ] Remove the environment check
- [ ] Resolve any critical findings from staging check

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
