### ISSUE TITLE
Document fwdproxy to prepare for move to new infrastructure (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16407]
## Issue Description
_Ensure that we've fully documented current architecture / configuration of fwdproxy to ensure that we can move it to the new infrastructure with minimal impact to the platform._

---
## Tasks
- [x] _Written documentation that clearly explains fwdproxy's configuration and setup in sufficient detail_
- [x] _Supporting architecture / configuration diagram_

WIP DOC (not started yet)

## Acceptance Criteria
- [x] _fwdproxy configuration and dependencies are well documented_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
WIP can be seen [here](https://vfs.atlassian.net/wiki/spaces/VI/pages/765427755/Forward+Proxy).

**Comment by jbritt1** [comment]
Added blank copy of BPE worksheet to the DevOps directory ([pull request](https://github.com/department-of-veterans-affairs/devops/pull/8087)).

**Comment by jhouse-solvd** [comment]
It's looking great. We are awaiting feedback from the team, and then will move this to done after any minor updates.

**Comment by jhouse-solvd** [comment]
This is now a living document, and we will iterate as necessary to improve moving forward. Closing this issue.
