### ISSUE TITLE
Update Cypress-TestRail-Reporter config to allows test runs with a limited selection of test cases from the test suite

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#16402]
## Issue Description
Tze is requesting the ability to have Cypress to TestRail reporter create a test run with a subset of the test cases contained in a project's test suite.  This makes sense for a variety of use cases including a dashboard project for the entire platform, automated smoke tests for a product reported to TestRail, creating automated acceptance tests during a sprint, etc.

---
## Tasks
- [x] Figure out how to use the [cypress-testrail-reporter plugin](https://www.npmjs.com/package/cypress-testrail-reporter) to create test runs with a subset of test cases in the test suite
- [x] Update `package.json` cy:testrail-run yarn script to include the additional environment variables needed to configure the reporter to create test runs with a subset of tests
- [x] Update [documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/e2e-testing/cypress-testrail-reporter-config.md)to include how to use cypress-testrail-reporter plugin to execute a subset of test cases from a test suite

## Acceptance Criteria
- [ ] QA/Devs are able to fire off a selection of automated tests in Cypress and the results of just the subset of tests that the user has selected are recorded in a test run in TestRail
---

**Comment by pjhill** [comment]
Current idea on how to fix this:
- Split out config into two different files so that a test run that wants the reporter can use the config with it enabled and a test run that does not want to use the reporter can use the config without the reporter declared.
  - If a test run uses the config with the reporter declared but doesn't set any of the environment variables then it fills the log up with 401 errors due to garbage URLs being generated
- Refactor cy:testrail-run script to reference the split cypress-testrail.json config file
- Remove reporter and options from general cypress.json config file

**Comment by pjhill** [comment]
This was addressed by [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15055) which is now merged.
