### ISSUE TITLE
Add School-Approved Abbreviations to School Data to Improve Search Results

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16405]
## Issue Description
The Yellow Ribbon school search does not yield desirable results for searches containing commonly-used abbreviations (ex: UNC-CH vs. University of North Carolina at Chapel Hill).  

This shortcoming means that, in order to find a specific school, the user must refine their search term so that it contains all or part of the school's "official" full name, scan through a list of schools that happen to contain the text string they initially entered, or potentially abandon their search altogether if they are unwilling or unable to determine the "secret recipe" for locating a specific school through trial and error.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Users will be able to find Yellow Ribbon schools by entering an valid (in the GIDS) abbreviation for a school
- [ ] Predictive text will allow the user to more quickly narrow their search 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
We may be able to leverage GI Bill Comparison Tool predictive text, abbreviation search logic, and weighted results to improve the quality of the Yellow Ribbon search tool.  

The GI Bill Comparison Tool queries the same GIDS data source used in the Yellow Ribbon search - see the search at https://www.va.gov/gi-bill-comparison-tool.  Presumably, the data needed for abbreviation searches should already be present in the dataset, as well as data and/or logic for weighting the results. 

### Predictive Text Behavior:
![image](https://user-images.githubusercontent.com/73354907/99848906-9a390580-2b48-11eb-8e1d-f2a20d2ea856.png)

###  Common Abbreviations Accounted For:
![image](https://user-images.githubusercontent.com/73354907/99849742-1aac3600-2b4a-11eb-8b5b-4a0d28e0ba9d.png)

### Results are Weighted by Best Match:

![image](https://user-images.githubusercontent.com/73354907/99849697-ff412b00-2b49-11eb-83aa-08aa2a4ef923.png)

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO  This is terrific news!  Great job of sleuthing.

**Comment by MarciMcGuireGCIO** [comment]
Grooming note: create issue for estimating size of this
