### ISSUE TITLE
[PM] My VA 2.0: Make a list of all the updates/notifications we'll need on the new dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#16406]
## Background

Regardless of whether we choose approach A or B after user research (#15684) we will need a full list of all the different updates we want to show. This will allow us to do two things:

- Design a standard update pattern (we'll understand exactly what data points we want to include)
- Start working with copy ASAP before visual design is fully complete 

## Tasks

- [ ] Make full list of updates
- [x] [Link list of updates/notifications to this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/my-va-updates-notifications-list.md)
- [ ] Share with team for input and review

**Comment by Samara-Strauss** [comment]
Done, but we aren't going with the "notification" approach anymore, so this is no longer needed.
