### ISSUE TITLE
Yellow Ribbon: Add link to download schools data for upcoming year (Groom in June 2021)

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16404]
## Issue Description
Each year the school data for the Yellow Ribbon Program changes to reflect the schools that are participating in the upcoming school year (Aug 2021 to July 2022)

---
## Tasks
- [ ] Confirm that simply adding a text link to the existing HTML is acceptable (proposed solution below):

![Image 3](https://user-images.githubusercontent.com/73354907/99845354-7c68a200-2b42-11eb-8f1a-4b3512dfabaf.png)
- [ ] Determine where actual downloadable file will reside in cloud/on server
- [ ] Request 508-compliant downloadable data for 2021-2022 school year from Janice Fisher
- [ ] Verify file is 508 compliant
- [ ] Create VSP issue to have file placed on server
- [ ] Add CTA text to page
- [ ] Test

## Acceptance Criteria
- [ ] 508-compliant, downloadable file listing participating Yellow Ribbon schools will be downloadable from a text CTA link on the Yellow Ribbon search page.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Putting in icebox so we don't lose sight of it next year.

**Comment by MarciMcGuireGCIO** [comment]
Added tasks and a screen shot of where the link is meant to appear.

**Comment by MarciMcGuireGCIO** [comment]
Updating title to better distinguish this from the front-end change needed to accommodate the new school data being added to the database for 2021-2022 school year.

**Comment by MarciMcGuireGCIO** [comment]
Note to self - check email to see if we have the CTA copy from Beth Potts.

**Comment by MarciMcGuireGCIO** [comment]
Contacted stakeholders several times between May and late July and could never get clear info on when this data would be ready.  The new school year data is already in the database, so this is no longer needed.
