### ISSUE TITLE
[Content Structure] Move VISN-21 Facilities listed in parent category "VAMC facilities" into Correct VISN-16 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16418]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-16 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**
VA Central California health care
- [x] 570	Fresno VA Medical Center

- [ ] 570GA	Merced VA Clinic
- [ ] 570GB	Tulare VA Clinic
- [ ] 570GC	Oakhurst VA Clinic

VA Northern California health care
- [ ] 612A4	Sacramento VA Medical Center
- [ ] 612B4	Redding VA Clinic
- [ ] 612BY	Oakland VA Clinic
- [ ] 612GD	Fairfield VA Clinic
- [ ] 612GE	Mare Island VA Clinic
- [ ] 612GF	Martinez VA Medical Center
- [ ] 612GG	Chico VA Clinic
- [ ] 612GH	McClellan VA Clinic
- [ ] 612GI	Yuba City VA Clinic
- [ ] 612GJ	Yreka VA Clinic
- [ ] 612QB	Twenty First Street VA Clinic

VA Pacific Islands health care
- [ ] 459	Spark M. Matsunaga VA Medical Center
- [ ] 459GA	Maui VA Clinic
- [ ] 459GB	Hilo VA Clinic
- [ ] 459GC	Kailua-Kona VA Clinic
- [ ] 459GD	Lihue VA Clinic
- [ ] 459GE	Guam VA Clinic
- [ ] 459GF	Faleomavaega Eni Fa'aua'a Hunkin VA Clinic
- [ ] 459GG	Leeward Oahu VA Clinic
- [ ] 459GH	Saipan VA Clinic
- [ ] 459QA	Lanai VA Clinic
- [ ] 459QB	Molokai VA Clinic

VA Palo Alto health care
- [ ] 640	Palo Alto VA Medical Center
- [ ] 640A0	Palo Alto VA Medical Center-Menlo Park
- [ ] 640A4	Palo Alto VA Medical Center-Livermore
- [ ] 640BY	San Jose VA Clinic
- [ ] 640GA	Capitola VA Clinic
- [ ] 640GB	Sonora VA Clinic
- [ ] 640GC	Fremont VA Clinic
- [ ] 640HA	Stockton VA Clinic
- [ ] 640HB	Modesto VA Clinic
- [ ] 640HC	Major General William H. Gourley VA-DoD Outpatient Clinic

VA San Francisco health care
- [ ] 662	San Francisco VA Medical Center
- [ ] 662GA	Santa Rosa VA Clinic
- [ ] 662GC	Eureka VA Clinic
- [ ] 662GD	Ukiah VA Clinic
- [ ] 662GE	San Bruno VA Clinic
- [ ] 662GF	San Francisco VA Clinic
- [ ] 662GG	Clearlake VA Clinic

VA Sierra Nevada health care
- [ ] 654	Ioannis A. Lougaris Veterans' Administration Medical Center
- [ ] 654GB	Carson Valley VA Clinic
- [ ] 654GC	Lahontan Valley VA Clinic
- [ ] 654GD	Diamond View VA Clinic

VA Southern Nevada health care

- [ ] 593	North Las Vegas VA Medical Center
- [ ] 593GC	Pahrump VA Clinic
- [ ] 593GD	Northwest Las Vegas VA Clinic
- [ ] 593GE	Southeast Las Vegas VA Clinic
- [ ] 593GF	Southwest Las Vegas VA Clinic
- [ ] 593GG	Northeast Las Vegas VA Clinic
- [ ] 593GH	Master Chief Petty Officer Jesse Dean VA Clinic

## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN
