### ISSUE TITLE
[Content Structure] Move VISN-16 Facilities listed in parent category "VAMC facilities" into Correct VISN-16 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16417]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-16 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**
VA Alexandria health care
- [x] 502	Alexandria VA Medical Center
- [x] 502GA	Jennings VA Clinic
- [x] 502GB	Lafayette VA Clinic
- [x] 502GE	Lake Charles VA Clinic
- [x] 502GF	Fort Polk VA Clinic
- [x] 502GG	Natchitoches VA Clinic
- [x] 502QB	Lafayette Campus B VA Clinic

VA Central Arkansas health care
- [x] 598	John L. McClellan Memorial Veterans' Hospital
- [x] 598A0	Eugene J. Towbin Healthcare Center
- [x] 598GA	Mountain Home VA Clinic
- [x] 598GB	El Dorado VA Clinic
- [x] 598GC	Hot Springs VA Clinic
- [x] 598GD	Mena VA Clinic
- [x] 598GE	Pine Bluff VA Clinic
- [x] 598GF	Searcy VA Clinic
- [x] 598GG	Conway VA Clinic
- [x] 598GH	Russellville VA Clinic

VA Fayetteville Arkansas health care
- [x] 564	Fayetteville VA Medical Center
- [x] 564BY	Gene Taylor Veterans' Outpatient Clinic
- [x] 564GA	Harrison VA Clinic
- [x] 564GB	Fort Smith VA Clinic
- [x] 564GC	Branson VA Clinic
- [x] 564GD	Ozark VA Clinic
- [x] 564GE	Jay VA Clinic
- [x] 564GF	Joplin VA Clinic

VA Gulf Coast health care
- [x] 520	Biloxi VA Medical Center
- [x] 520BZ	Pensacola VA Clinic
- [x] 520GA	Mobile VA Clinic
- [x] 520GB	Panama City Beach VA Clinic
- [x] 520GC	Eglin Air Force Base VA Clinic

VA Houston health care
- [x] 580	Michael E. DeBakey VA Medical Center
- [x] 580BY	Beaumont VA Clinic
- [x] 580BZ	Charles Wilson VA Outpatient Clinic
- [x] 580GC	Galveston County VA Clinic
- [x] 580GD	Conroe VA Clinic
- [x] 580GE	Katy VA Clinic
- [ ] 580GF	Lake Jackson VA Clinic
- [x] 580GG	Richmond VA Clinic
- [x] 580GH	Tomball VA Clinic
- [x] 580GJ	Texas City VA Clinic

VA Jackson health care
- [x] 586	G.V. (Sonny) Montgomery VA Medical Center
- [x] 586GA	Kosciusko VA Clinic
- [x] 586GB	Meridian VA Clinic
- [x] 586GC	Greenville VA Clinic
- [x] 586GD	Hattiesburg VA Clinic
- [x] 586GE	Natchez VA Clinic
- [x] 586GF	Columbus VA Clinic
- [x] 586GG	McComb VA Clinic

VA Shreveport health care
- [x] 667	Overton Brooks Veterans' Administration Medical Center
- [x] 667GA	Texarkana VA Clinic
- [x] 667GB	Monroe VA Clinic
- [x] 667GC	Longview VA Clinic
- [x] 667QA	Knight Street VA Clinic
 

VA Southeast Louisiana health care
- [x] 629	New Orleans VA Medical Center
- [x] 629BY	Baton Rouge VA Clinic
- [x] 629GA	Houma VA Clinic
- [x] 629GB	Hammond VA Clinic
- [x] 629GC	Slidell VA Clinic
- [x] 629GD	St. John VA Clinic
- [x] 629GE	Franklin VA Clinic
- [x] 629GF	Bogalusa VA Clinic

## Acceptance criteria
- [x] All facilities have been moved from parent to system
- [x] All main locations have been confirmed
- [x] facilities show up correctly under System an VISN
