### ISSUE TITLE
MVP release of keyboard-e2e test

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#16413]
## Issue Description
We are defining the MVP for a keyboard end-to-end test that teams can opt in to for their Cypress forms testing.

---
## Tasks
- [x] Unblock vets-website in developer's working environment -- 2
- [x] Finish work on the tab up / tab down function -- 1
- [x] Extract tab up / tab down to a `goto` function -- 2
- [x] Add the `goto` function to the `formTester` method -- 3
- [x] Add helper methods for dealing with input types: -- 2
  - [x] Text inputs
  - [x] Radio groups
  - [x] Checkboxes
  - [x] Select menus
- [x] Document the use of the `goto` function within the context of `formTester` -- 1

## Acceptance Criteria
- [x] VFS team engineer can consume the documentation for `goto` function and implement it in their team's product

**Comment by pjhill** [comment]
@noahgelman and @ddzz -- Is the MVP of this ready for use on the platform? I know you two have been hashing out some development environment related issues with implementing tests -- have those been addressed? Can we move this to done? Or, are there specific issues that we need to address before moving this to done?

**Comment by noahgelman** [comment]
@pjhill 
The issues are not yet resolved and it is not ready to be moved to done. I hoping to get it there soon. There is an error on mac that is holding up the process and I'm in the process of resolving it.

**Comment by pjhill** [comment]
Throwing this into the Icebox until we have room in our prioritization for a proper testing and release of this product.

**Comment by pjhill** [comment]
Hey, Curt reminded me that we already had [support ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1933607071/Keyboard+Testing)for a bunch of keyboard commands based on the `cypress-real-events` library.

A few questions -- 
How does this previous work play into your current efforts?
Has your KE2E branch been merged?
Are you able to link the PR into this ticket for context and tracking purposes going forward?

**Comment by pjhill** [comment]
@noahgelman Cool, that makes sense. As you're working on collecting your commits into a PR, please keep in mind that we do have this existing set of keyboard helpers. I'm not sure if you started the documentation yet, but if you haven't it would be prudent to include your additional keyboard helpers in the existing [document](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1933607071/Keyboard+Testing).

We want to be sure that the documentation is easy to use for VFS teams, so getting the information from a single source would be best.

Also, do your changes modify any of these existing helpers that we already offer? We would need to update the documentation to reflect that if so.

**Comment by noahgelman** [comment]
@pjhill Thank you, I will add my commands to that doc, and no, I don't modify any existing commands, I've only added new commands so this will have 0 impact on any existing tests

**Comment by noahgelman** [comment]
[Branch with my Keyboard Code and an example test](https://github.com/department-of-veterans-affairs/vets-website/tree/E2E-Keyboard-Test-Port-to-Cypress)

[Updated Documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1933607071/Keyboard+Testing)

People can check out the features, try to write some tests using the new Commands (or add features to their old tests)

**Comment by pjhill** [comment]
- [ ] @noahgelman Work with stakeholders to get their feedback about the KE2E functionality

**Comment by pjhill** [comment]
@noahgelman , What's the status of this release? Have you received any feedback? Anything to resolve?

**Comment by pjhill** [comment]
Draft PR is [here](https://github.com/department-of-veterans-affairs/vets-website/pull/20533).

**Comment by rsmithadhoc** [comment]
- To Dos
    - **Required Fixes**
        - [ ] Infinite loop when attempting to press the down arrow for select options
        - TBD - I might find something after the infinite loop is addressed
    - **Other Improvements**
        - [ ] Docs 
            - Once merged it is no longer "Experimental Features Still in Testing", remove this if we are planning to merge/deploy.
            - Add distinction between this and other keyboard functions documented. When/why should you use this vs `cy.realPress()` or `cy.allyEvaluateSelectMenu()`?
        - [ ] `timeoutDuration` 
            - This will artificially slow down tests. Should it be an environment variable and set to 0 on higher environments? Or should we remove it altogether? Will running the tests as fast as possible have any negative impact on what we are trying to accomplish?
        - [ ] Code comments
            - Remove Cypress example comments: _"This example commands.js shows you how to..."_. 
            - Remove `/// <reference types="cypress" />`, this came from the Cypress TypeScript example which is not being used.
            - Update existing comments to be clearer and use proper multi-line comments.
            - Remove or update empty comments.

**Comment by rsmithadhoc** [comment]
Here is more info on the issue pressing down arrow in a select dropdown.

- Simulating a keypress via JavaScript would not be the same as a user pressing the key.
- `cypress-real-events` uses `Cypress.automation()` to access the remote Chrome session and use Chrome DevTools Protocol (CDP) to create keypresses.
- Because of that, the issue with the down arrow can be an issue in `cypress-real-events`, Cypress, Chrome DevTools Protocol, or Chrome itself
- [CDP recommends against using it directly for browser automation](https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md).
- CDP recommends Playwright. It uses real browser input that is indistinguishable from the real user. This would also allow browser-agnostic tests. With Cypress, using `cypress-real-events` means our tests (specifically those that import `cypress-real-events`) only support Chromium due to its use of CDP. Playwright is beyond the scope of this ticket but something to consider in the future.

What else I'm trying:

- Trying to circumvent `cypress-real-events` and Cypress by accessing the remote Chrome session through CDP directly. If the issue is on the Cypress side, it might work. If it is on the Chrome/CDP side, I don't believe we will be able to go any further with getting a real arrow keypress working in the select element until CDP/Chrome fixes it.

**Comment by rsmithadhoc** [comment]
PR is out for review, I left a comment for reviews to test: https://github.com/department-of-veterans-affairs/vets-website/pull/20533#issuecomment-1099472691

**Comment by pjhill** [comment]
Looking good -- thanks for closing this out!
