### ISSUE TITLE
[Content Structure] Move VISN-23 Facilities listed in parent category "VAMC facilities" into Correct VISN-16 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16421]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-16 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**

VA Black Hills health care
- [ ] 568	Fort Meade VA Medical Center
- [ ] 568A4	Hot Springs VA Medical Center
- [ ] 568GA	Rapid City VA Clinic
- [ ] 568GB	Pierre VA Clinic
- [ ] 568HA	Newcastle VA Clinic
- [ ] 568HB	Gordon VA Clinic
- [ ] 568HF	Pine Ridge VA Clinic
- [ ] 568HH	Scottsbluff VA Clinic
- [ ] 568HJ	Mission VA Clinic
- [ ] 568HP	Winner VA Clinic

VA Central Iowa health care
- [ ] 636A6	Des Moines VA Medical Center
- [ ] 636GC	Mason City VA Clinic
- [ ] 636GD	Marshalltown VA Clinic
- [ ] 636GK	Fort Dodge VA Clinic
- [ ] 636GM	Carroll VA Clinic
- [ ] 636GR	Knoxville VA Clinic

VA Fargo health care
- [ ] 437	Fargo VA Medical Center
- [ ] 437GA	Grafton VA Clinic
- [ ] 437GB	Bismarck VA Clinic
- [ ] 437GC	Fergus Falls VA Clinic
- [ ] 437GD	Minot VA Clinic
- [ ] 437GE	Bemidji VA Clinic
- [ ] 437GF	Williston VA Clinic
- [ ] 437GI	Grand Forks VA Clinic
- [ ] 437GJ	Dickinson VA Clinic
- [ ] 437GK	Jamestown VA Clinic
- [ ] 437GL	Devils Lake VA Clinic

VA Iowa City health care
- [ ] 636  (See Nebraska)
- [ ] 636A8	Iowa City VA Medical Center
- [ ] 636GF	Quad Cities VA Clinic
- [ ] 636GG	Quincy VA Clinic
- [ ] 636GH	Waterloo VA Clinic
- [ ] 636GI	Lane A. Evans VA Community Based Outpatient Clinic
- [ ] 636GJ	Dubuque VA Clinic
- [ ] 636GN	Cedar Rapids VA Clinic
- [ ] 636GS	Ottumwa VA Clinic
- [ ] 636GT	Sterling VA Clinic
- [ ] 636GU	Decorah VA Clinic
- [ ] 636GW	Coralville VA Clinic

VA Minneapolis health care
- [ ] 618	Minneapolis VA Medical Center
- [ ] 618BY	Twin Ports VA Clinic
- [ ] 618GA	St. James VA Clinic
- [ ] 618GB	Hibbing VA Clinic
- [ ] 618GD	Maplewood VA Clinic
- [ ] 618GE	Chippewa Valley VA Clinic
- [ ] 618GG	Rochester VA Clinic
- [ ] 618GH	Hayward VA Clinic
- [ ] 618GI	Northwest Metro VA Clinic
- [ ] 618GJ	Shakopee VA Clinic
- [ ] 618GK	Albert Lea VA Clinic
- [ ] 618GM	Rice Lake VA Clinic
- [ ] 618GN	Lyle C. Pearson Community Based Outpatient Clinic
- [ ] 618QB	Ely VA Clinic

VA Nebraska-Western Iowa health care
- [ ] 636	Omaha VA Medical Center
- [ ] 636A4	Grand Island VA Medical Center
- [ ] 636A5	Lincoln VA Clinic
- [ ] 636GA	Norfolk VA Clinic
- [ ] 636GB	North Platte VA Clinic
- [ ] 636GL	Bellevue VA Clinic
- [ ] 636GP	Shenandoah VA Clinic
- [ ] 636GQ	Holdrege VA Clinic
- [ ] 636GV	O'Neill VA Clinic

VA Sioux Falls health care
- [ ] 438	Royal C. Johnson Veterans' Memorial Hospital
- [ ] 438GA	Spirit Lake VA Clinic
- [ ] 438GC	Sioux City VA Clinic
- [ ] 438GD	Aberdeen VA Clinic
- [ ] 438GE	Wagner VA Clinic
- [ ] 438GF	Watertown VA Clinic

VA St Cloud health care
- [ ] 656	St. Cloud VA Medical Center
- [ ] 656GA	Brainerd VA Clinic
- [ ] 656GB	Montevideo VA Clinic
- [ ] 656GC	Max J. Beilke VA Outpatient Clinic
## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN
