### ISSUE TITLE
[Content Structure] Move VISN-2 Facilities listed in parent category "VAMC facilities" into Correct VISN-16 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16422]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-16 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**
VA Albany health care

- [ ] 528A8	Samuel S. Stratton Department of Veterans Affairs Medical Center
- [ ] 528G2	Westport VA Clinic
- [ ] 528G3	Bainbridge VA Clinic
- [ ] 528G6	Fonda VA Clinic
- [ ] 528G7	Catskill VA Clinic
- [ ] 528GT	Glens Falls VA Clinic
- [ ] 528GV	Plattsburgh VA Clinic
- [ ] 528GW	Schenectady VA Clinic
- [ ] 528GX	Troy VA Clinic
- [ ] 528GY	Clifton Park VA Clinic
- [ ] 528GZ	Kingston VA Clinic
- [ ] 528QK	Saranac Lake VA Clinic

VA Finger Lakes health care
- [ ] 528A5	Canandaigua VA Medical Center
- [ ] 528A6	Bath VA Medical Center
- [ ] 528G4	Elmira VA Clinic
- [ ] 528G8	Wellsville VA Clinic
- [ ] 528GE	Rochester VA Clinic
- [ ] 528QC	Clinton Crossings VA Clinic
- [ ] 528QE	Coudersport VA Clinic
- [ ] 528QF	Wellsboro VA Clinic

VA Syracuse health care

- [ ] 528A7	Syracuse VA Medical Center
- [ ] 528G9	Tompkins County VA Clinic
- [ ] 528GL	Massena VA Clinic
- [ ] 528GM	Donald J. Mitchell VA Outpatient Clinic
- [ ] 528GN	Binghamton VA Clinic
- [ ] 528GO	Watertown VA Clinic
- [ ] 528GP	Oswego VA Clinic
- [ ] 528QN	Watertown 2 VA Clinic

VA Western New York health care
- [ ] 528	Buffalo VA Medical Center
- [ ] 528A4	Batavia VA Medical Center
- [ ] 528GB	Jamestown VA Clinic
- [ ] 528GC	Dunkirk VA Clinic
- [ ] 528GD	Niagara Falls VA Clinic
- [ ] 528GK	Lockport VA Clinic
- [ ] 528GQ	Lackawanna VA Clinic
- [ ] 528GQ01	Springville Community Based Outpatient Clinic
- [ ] 528GR	Olean VA Clinic

VA Bronx health care
- [ ] 526	James J. Peters Department of Veterans Affairs Medical Center
- [ ] 526GA	White Plains VA Clinic
- [ ] 526GB	Yonkers VA Clinic
- [ ] 526GD	Thomas P. Noonan Jr. Department of Veterans Affairs Outpatient Clinic

VA Hudson Valley health care
- [ ] 620	Franklin Delano Roosevelt Hospital
- [ ] 620A4	Castle Point VA Medical Center
- [ ] 620GA	New City VA Clinic
- [ ] 620GB	Carmel VA Clinic
- [ ] 620GD	Goshen VA Clinic
- [ ] 620GE	Port Jervis VA Clinic
- [ ] 620GF	Monticello VA Clinic
- [ ] 620GG	Poughkeepsie VA Clinic
- [ ] 620GH	Eastern Dutchess VA Clinic

VA New Jersey health care
- [ ] 561	East Orange VA Medical Center
- [ ] 561A4	Lyons VA Medical Center
- [ ] 561BZ	James J. Howard Veterans' Outpatient Clinic
- [ ] 561GA	Hamilton VA Clinic
- [ ] 561GB	Elizabeth VA Clinic
- [ ] 561GD	Hackensack VA Clinic
- [ ] 561GE	Jersey City VA Clinic
- [ ] 561GF	Piscataway VA Clinic
- [ ] 561GH	Morristown VA Clinic
- [ ] 561GI	Tinton Falls VA Clinic
- [ ] 561GJ	Paterson VA Clinic
- [ ] 561GK	Sussex VA Clinic

VA New York Harbor health care
- [ ] 630	Manhattan VA Medical Center
- [ ] 630A4	Brooklyn VA Medical Center
- [ ] 630A5	St. Albans VA Medical Center
- [ ] 630GA	Harlem VA Clinic
- [ ] 630GB	Staten Island Community VA Clinic

VA Northport health care
- [ ] 632	Northport VA Medical Center
- [ ] 632GA	East Meadow VA Clinic
- [ ] 632HA	Valley Stream VA Clinic
- [ ] 632HB	Riverhead VA Clinic
- [ ] 632HC	Bay Shore VA Clinic
- [ ] 632HD	Patchogue VA Clinic

## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN
