### ISSUE TITLE
[SD] Click Tracking

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16444]
## Description

Search capabilities on VA.gov are powered by search.gov. To date they have not had click tracking abilities built into their analytics for API clients. As a result, we have not been able to track a users clicks on VA.gov.

Recently Search.gov has completed development and soft launched API-based  [click-tracking](https://search.gov/manual/clicks.html)  to enable "closed loop" analytics. They have asked VA.gov, along with other agencies, to test the capability.

The click tracking API endpoint lets you send in click events, which allows you to see click data on your Admin Click Analytics page. We also use this click data to strengthen the search results algorithm for your site.

The Click Track API instructions are attached for implementation and validation.

[Search.gov - Click Tracking API Instructions (Beta).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5393167/Search.gov.-.Click.Tracking.API.Instructions.Beta.docx)

Establishing click tracking for analytics purposes is a back end API integration and will not impact the front end experience for users. 

## Collaboration Cycle Events Tracking
- [x] **Collaboration Cycle Kickoff :** [#17005](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17005)
- [x] **Analytics Request:**  TBD
- [x] **Privacy & Security Review**:  [#293](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/293)
- [x] **Post Launch - Check in:** TBD

## Tasks

- [x] Back End Development [#16367](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16367)
- [x] Front End Development [#14955](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14955)

**Comment by denisecoveyduc** [comment]
Click tracking has been implemented and is accessible via Search.gov analytics. As a result we are closing this epic and all associated issues.

**Comment by denisecoveyduc** [comment]
Reopening to encompass the inclusion of Click Tracking on the best bets implementation
