### ISSUE TITLE
Remove REAP page from the sitemap and best bets

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16446]
## Issue Description
REAP page is being archived. We need to make sure it is removed from the sitemap and best bets.
/education/other-va-education-benefits/reap/index.html

---
## Tasks

- [x] Remove from Best Bets (@johnhashva) 

- [x] Remove from sitemap (@denisecoveyduc & @srsuddath)

## Acceptance Criteria
- [x] REAP page is no longer findable.
--
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
@denisecoveyduc I will take care of the Best Bets task in this ticket -- and we will need Sam to tackle the Site Map XML removal.   We have a few other Site Map XML housecleaning tasks so may want to bundle these in an upcoming sprint -- e.g. #9494.

**Comment by johnhashva** [comment]
@bethpotts updated the ticket to reflect two discrete tasks -- removal from Best Bets, then removal from Site Map.   The Best Bets has been deleted.  We will get the Site Map in our upcoming sprint.

**Comment by bethpottsVADEPO** [comment]
@johnhashva Thank you, I'll hold off archiving the page until the page is out of the site map.

**Comment by denisecoveyduc** [comment]
@srsuddath Are you able to add an estimate based on the info here?

**Comment by denisecoveyduc** [comment]
@srsuddath I think you mentioned in SU this been completed? Can it be closed now?

**Comment by srsuddath** [comment]
This page no longer appears on the va.gov sitemap
