### ISSUE TITLE
[DISCOVERY] UX for when the Veteran has zoomed out too far

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16449]
## Issue Description
Since community care searches are now limited to 500 miles by PPMS, the "Search this area" button disappears when the Veteran has zoomed out past the limit. 

We need to make some UX adjustments to ensure 

1. Veterans using Voiceover understand that the button is no longer available
2. All Veteran users understand why the button is no longer available and how to adjust the search to be successful

Option: If we use the "Search this area" <div> container for an onscreen error/help message, it will automatically be announced. 

Design input: 

- how do we announce the disappearance of the "Search this area" button for Voiceover users?
- how do we inform all users why the button is no longer available and how to adjust the search 

---
## Tasks
- [ ] Identify how comparative sites handle this scenario
- [ ] Determine placement of the notification for the disappearance of the "Search this area" button
- [ ] Determine appropriate focus flow for notification

## Acceptance Criteria
- [ ] Recommendation for notification style, location, focus and voiceover 
- [ ] Veterans using Voiceover understand that the "Search this area" button is no longer available
- [ ] All Veteran users understand why the button is no longer available and how to adjust the search to be successful
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This will be validated during Mobile search expectation research expectations during Q121

**Comment by mmiddaugh** [comment]
Closing as duplicate for #21256
