### ISSUE TITLE
"Search this area" does not appear after zooming

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16453]
## Issue Description
The "Search this area" does not appear after zooming in or out on the map, only after panning. 

https://www.loom.com/share/64888f77d01f483f96b56803a401f110

Both zooming and panning will trigger the "Search this area" button?

---
## Tasks
- [ ] Determine the desired user experience. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This will be addressed during the work for [#16380]
