### ISSUE TITLE
[Engineer] Rebuild Devshop environments for systems [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16463]
## Issue Description
Sites need to be rebuild for VAMC, so they can continue to test, stage review, and move to dual state prep

---
## Tasks
update the following systems in Devshop
- [x] Erie
- [x] Lebanon
Create the following:
- [x] Asheville
- [x] Durham
- [x] Fayetteville Costal
- [x] Hampton

## Acceptance Criteria
- [x] Sites are created
- [x] Sites are published and content is released
- [x] Sites are accessible or support ticket placed to fix issue and get accessible.
