### ISSUE TITLE
Community Care Provider Selection - Iterations to MVP

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16462]
## Who is the target user?
Eligible community care Veterans who are using VAOS to request community care appointment

## High Level User Story/ies
As a veteran, I would like the VAOS app to automatically find and display eligible Community Care providers closest to my residential address when booking a Community Care appointment. I also want my selected Community Care provider's information to auto populate any required fields into VAOS so I don't have to manually enter or copy-paste this information.

## Hypothesis or Bet
We believe that by providing approved CC providers to Veterans during their CC request process in VAOS we will decrease request dropoff for these appointment types and also improve triage/booking time for Request Managers because information for these appointments is easier to find and easier to triage.

## OKR
Improving the Community Care experience so veterans choose from a list of available providers rather than free text.

## Definition of done
- [x] Non-critical accessibility issues from MVP are resolved
- [x] Critical iterations accessibility issues are resolved
- [x] Veterans can select a preferred Community Care provider
