### ISSUE TITLE
Update Cypress Migration Guide & create new Best Practices doc

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16475]
## High Level User Story/ies
As a frontend developer, I need documentation that is on-topic so I can quickly find the information I need.
 
## Hypothesis or Bet
Moving the general information about Cypress from the Cypress Migration Guide to a new document called Cypress Best Practices will provide focus to the Cypress documentation making it easier for engineers to find the information they’re looking for.

## Issue Description
The Cypress Migration Guide -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-migration-guide.md --  includes documentation for migrating tests to Cypress as well as general information about Cypress. The title of the documentation does not accurately convey its contents.

## Tasks
- [x] Update the Cypress Migration Guide by moving the general, non-migration related Cypress documentation into a new document called Cypress Best Practices that recommends general best practices VSP.
 
## Acceptance Criteria
- [x] The Cypress Migration Guide will be edited down to contain only information about migrating tests to Cypress.
- [x] A new document called Cypress Best Practices will be created.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
