### ISSUE TITLE
Consolidate Cypress documentation & remove documentation that is out of date.

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16476]
## High Level User Story/ies
As a frontend developer who uses Cypress for automated tests, I need Cypress documentation that is up-to-date and in one place so I know where everything is and don’t have to hunt for it, so I can find the accurate information I need quickly and easily.
 
## Hypothesis or Bet
Keeping all Cypress-related documentation in one place will make it easier for engineers to find the information they need. Removing old documentation about testing frameworks no longer being used will reduce confusion.

## Issue Description
The Cypress documentation for VSP is scattered amongst several domains and is out of date. Documentation exists both at this github site -- https://department-of-veterans-affairs.github.io/ -- and va.gov-team repo.

## Tasks
- [x] Determine where the documentation should live and consolidate it. (Perhaps it should live on the va.gov-team repo and be referenced from the department-of-veterans-affairs.github.io website.)
- [x] Update or delete the Writing an end-to-end test documentation -- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test/ -- which currently documents how to write tests using Selenium and Nightwatch.
- [x] Update the End-to-end testing (Frontend) landing page to reference the new documentation.
 
## Acceptance Criteria
- [x] Cypress documentation will be consolidated under one domain.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
