### ISSUE TITLE
Document how to test viewports and which viewports to test

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16474]
## High Level User Story/ies
As a frontend engineer, I need clear and concise documentation about the mobile, tablet and desktop viewports I should test.
 
## Hypothesis or Bet
Creating documentation about the top mobile, tablet and desktop viewports used by va.gov users will help frontend engineers write tests faster and write tests that are applicable to real va.gov users.

## Issue Description
Documentation regarding what mobile and desktop viewports to test against in Cypress e2e does not exist.

## Tasks
- [ ] Add a new section to the Cypress Best Practices on VSP documentation that lists all viewports and the top 5 viewports grouped by mobile and desktop that we want our tests to cover.
 
## Acceptance Criteria
- [ ] The Cypress Best Practices on VSP documentation will be updated.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Documentation for the new Cypress environment variables and custom commands have been added. I'm waiting for the PR for the code updates to be approved and merged to master so I can update the links in this document to the new code then submit a PR for this updated documentation.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/write_documentation_for_new_cypress_viewport_env_vars_and_custom_command/platform/testing/end-to-end/cypress-best-practices-on-vsp.md#iterate-through-top-vagov-viewports

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/va.gov-team/pull/16516

**Comment by holdenhinkle** [comment]
Updated docs to reflect recent changes in code.

Submitted PR - https://github.com/department-of-veterans-affairs/va.gov-team/pull/16653

Update the following sections to reflect recent code changes:

Cypress Custom Commands > Viewport Presets: cy.viewportPreset(preset, orientation, options)
Iterate Through Top VA.gov Viewports
Includes misc. edits.

**Comment by pjhill** [comment]
Great work!
