### ISSUE TITLE
Analyze removing testing data attributes from production to save bandwidth

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16472]
## High Level User Story/ies
As an operations engineer, I need a way to remove the `data-` attributes that are used for Cypress end-to-end and UI tests from the production build so the VA can save bandwidth.
 
## Hypothesis or Bet
If we perform an analysis as to what kind of impact removing test-related data attributes from the production build could have on reducing bandwidth we’ll see that it has an overall positive effect and is worthwhile doing. Installing and configuring `babel-plugin-react-remove-properties` will automate this process for us.

## Issue Description
Currently, all `data-` attributes created for the purpose of e2e end up in production which is not necessary. We can save bandwidth by removing them.

## Tasks
- [ ] Perform an analysis as to what kind of impact removing test-related data attributes from the production build could have on reducing bandwidth
- [ ] Install and configure the `babel-plugin-react-remove-properties` plugin

## Acceptance Criteria
- [ ] If our analysis proves that this strategy is worth implementing, the `babel-plugin-react-remove-properties` plugin will need to be included in the production build and configured to remove the data attributes that are used for e2e testing.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Jhonny Gonzalez was a big help in giving me some direction here. Part of my conversation with him:

Jhonny Gonzalez  11:06 AM
`yarn analyze` should do the trick. You can also specify a bundle.
11:06
I'm not sure how familiar you are with the system

Holden Hinkle  11:06 AM
I’m not very familiar yet.
11:07
cool, I’ll look into `yarn analyze`…

Jhonny Gonzalez  11:07 AM
this is the library
`webpack-contrib/webpack-bundle-analyzer` - https://github.com/webpack-contrib/webpack-bundle-analyzer
Webpack plugin and CLI utility that represents bundle content as convenient interactive zoomable treemap

11:07
It's already installed in `vets-website`

Holden Hinkle  11:08 AM
Okay, awesome. Thanks.
11:11
Was just reading through the documentation. I’ll start here. Thanks Jhonny.

Jhonny Gonzalez  11:12 AM
`yarn analyze` I think generates the `stats.json` file
`build-analyze` runs the analyzer with the vagovprod

Holden Hinkle  11:12 AM
Okay.

Jhonny Gonzalez  11:13 AM
I think it takes a lot of time... like 10 mins
11:13
but you can always add a bundle like:
`NODE_ENV=production npm run build -- --buildtype vagovprod --analyzer --entry=static-pages`
11:13
so, it doesn't take that long

**Comment by holdenhinkle** [comment]
Google doc with notes - https://docs.google.com/spreadsheets/d/15Hu2zHqZLx3Ynh9KTiMTUjVGuy44XFRbc85aY8LeuHA/edit?usp=sharing

Outcome:
Cannot run `build-analyze` because the `json` file that's generated is too big. Jhonny Gonzalez confirmed that he ran into the same problem and said that it's a mac issue. He said it might work on Linux and Windows machines. Noah ran the command and got errors. Peter ran the command on WSL and was able to compile the build but ultimately ran into the same error I did.

Jhonny suggested that I run the reports in chunks be appending the directory name to the `--entry` flag like so:
`NODE_ENV=production npm run build -- --buildtype vagovprod --analyzer --entry=healthcare`

To test this, I installed the `babel-plugin-react-remove-properties` plugin and configured it in the `.babelrc` file by adding the following to the `productions.plugins` property like so:

```javascript
[
          "react-remove-properties",
          {
            "properties": [
              "data-test",
              "data-testid",
              "data-cy"
            ]
          }
        ]
```

**Comment by pjhill** [comment]
- [ ] Peter to discuss the use of `babel-plugin-react-remove-properties` to remove `data-cy` attributes despite the lack of hard numbers on potential build size differences at the next Eng Leads Meeting.

**Comment by pjhill** [comment]
@holdenhinkle -- VSP engineering leadership and FE Tools team are OK with configuring `babel-plugin-react-remove-properties` to remove the `data-cy` and `data-testid` attributes.

**Comment by holdenhinkle** [comment]
Ticket is completed and PR is in draft mode - https://github.com/department-of-veterans-affairs/vets-website/pull/15540

I'll update the PR with the results of running all Cypress tests locally when they finish, then submit it.

I posted a question about this ticket in Slack - https://dsva.slack.com/archives/C01CHAY3ULR/p1609883207443900

> How can we test this so we know that all will be okay in production?

**Comment by holdenhinkle** [comment]
All of the Cypress tests that normally pass passed when I ran `yarn cy:run` after `NODE_ENV=production yarn build --buildtype vagovprod` then `yarn watch` . Which is strange because you’d think the tests that use the `data-` attributes would fail after removing them.

Results:
```
      Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  applications/ask-a-question/tests/c        9ms        1        -        -        1        - │
  │    ypress/ask-a-question.authed.cypres                                                         │
  │    s.spec.js                                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/ask-a-question/tests/c       10ms        2        -        -        2        - │
  │    ypress/ask-a-question.unauthed.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/caregivers/tests/e2e/1      01:02        4        4        -        -        - │
  │    010cg.cypress.spec.js                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/coronavirus-vaccinatio      00:04        1        1        -        -        - │
  │    n/tests/e2e/signup.cypress.spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/debt-letters/tests/e2e       16ms        5        -        -        5        - │
  │    /debt-letters.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/debt-letters/tests/e2e       25ms        7        -        -        7        - │
  │    /diary-codes-content.cypress.spec.j                                                         │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/debt-letters/tests/e2e       11ms        4        -        -        4        - │
  │    /diary-codes-next-step.cypress.spec                                                         │
  │    .js                                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/23      00:16        4        4        -        -        - │
  │    46/tests/mdot.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/68      01:04        3        3        -        -        - │
  │    6c-674/tests/e2e/686C-674-ancilliar                                                         │
  │    y.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/68      01:12        2        2        -        -        - │
  │    6c-674/tests/e2e/686C-674.cypress.s                                                         │
  │    pec.js                                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/99      00:08        2        2        -        -        - │
  │    6/tests/hlr.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/al      15:08        8        8        -        -        - │
  │    l-claims/tests/all-claims.cypress.s                                                         │
  │    pec.js                                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/disability-benefits/vi      00:06        6        6        -        -        - │
  │    ew-payments/tests/e2e/view-payments                                                         │
  │    .cypress.spec.js                                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/0994/test       11ms        1        -        -        1        - │
  │    s/e2e/edu-0994.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/10203/tes      00:29        2        2        -        -        - │
  │    ts/edu-10203.cypress.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1990/test      00:26        1        1        -        -        - │
  │    s/e2e/edu-1990.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1990e/tes      00:20        1        1        -        -        - │
  │    ts/e2e/edu-1990e.cypress.spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1990n/tes      00:16        1        1        -        -        - │
  │    ts/e2e/edu-1990n.cypress.spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/1995/test      00:14        1        1        -        -        - │
  │    s/e2e/edu-1995.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/5490/test      00:27        1        1        -        -        - │
  │    s/e2e/edu-5490.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/edu-benefits/5495/test      00:18        1        1        -        -        - │
  │    s/e2e/edu-5495.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:01        1        1        -        -        - │
  │    /e2e/accessibility.cypress.spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:01        1        1        -        -        - │
  │    /e2e/ccpDisabled.cypress.spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:02        2        2        -        -        - │
  │    /e2e/ccpEnabled.cypress.spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:05        1        1        -        -        - │
  │    /e2e/gaEvents.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:12        1        1        -        -        - │
  │    /e2e/map-zoom.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/facility-locator/tests      00:23        2        1        1        -        - │
  │    /e2e/mobile.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/facility-locator/tests      00:18        9        8        -        1        - │
  │    /e2e/search.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/financial-status-repor       18ms        1        -        -        1        - │
  │    t/tests/e2e/fsr-5655.cypress.spec.j                                                         │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/find-forms/tests/e2e/0      00:03        1        1        -        -        - │
  │    0-required.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/gi/tests/e2e/00-requir      00:05        1        -        1        -        - │
  │    ed.cypress.spec.js                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/02-profil      00:01        1        1        -        -        - │
  │    e-error.cypress.spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/gi/tests/e2e/03-vet-te      00:04        1        -        1        -        - │
  │    c.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/gi/tests/e2e/04-dea.cy      00:05        1        -        1        -        - │
  │    press.spec.js                                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/gi/tests/e2e/05-ojt.cy      00:05        1        -        1        -        - │
  │    press.spec.js                                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/gi/tests/e2e/06-vet-te       15ms        1        -        -        1        - │
  │    c-mobile.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/gi/tests/e2e/07-gibct-      00:05        1        -        1        -        - │
  │    mobile.cypress.spec.js                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/hca/tests/hca.cypress.      02:23        3        3        -        -        - │
  │    spec.js                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:02        2        2        -        -        - │
  │    ire/list/tests/e2e/00.home.cypress.                                                         │
  │    spec.js                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:06        3        3        -        -        - │
  │    ire/list/tests/e2e/01.tabs.switch.c                                                         │
  │    ypress.spec.js                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna       11ms        1        -        -        1        - │
  │    ire/list/tests/e2e/02.bread.crumbs.                                                         │
  │    cypress.spec.js                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:02        2        2        -        -        - │
  │    ire/questionnaire/tests/e2e/00.ques                                                         │
  │    tionnaire.loads.cypress.spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/01.ques                                                         │
  │    tionnaire.demographics.address.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/01.ques                                                         │
  │    tionnaire.demographics.basicInforma                                                         │
  │    tion.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/01.ques                                                         │
  │    tionnaire.demographics.phoneNumbers                                                         │
  │    .cypress.spec.js                                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/03.ques                                                         │
  │    tionnaire.landing.page.accessibilit                                                         │
  │    y.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/04.appo                                                         │
  │    intment.id.is.missing.cypress.spec.                                                         │
  │    js                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/health-care-questionna      00:01        1        1        -        -        - │
  │    ire/questionnaire/tests/e2e/04.appo                                                         │
  │    intment.id.is.present.cypress.spec.                                                         │
  │    js                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/messages/tests/message      00:01        1        1        -        -        - │
  │    s.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:02        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.all-widgets                                                         │
  │    .cypress.spec.js                                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:01        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.find-benefi                                                         │
  │    ts-empty.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:01        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.find-benefi                                                         │
  │    ts-selected.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:07        6        6        -        -        - │
  │    ard/tests/e2e/dashboard.health-care                                                         │
  │    -widgets.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/dashbo      00:01        1        1        -        -        - │
  │    ard/tests/e2e/dashboard.minimal-wid                                                         │
  │    gets.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:06        1        1        -        -        - │
  │    e/tests/e2e/address-validation/bad-                                                         │
  │    unit.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/conf                                                         │
  │    irm-address.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:02        1        1        -        -        - │
  │    e/tests/e2e/address-validation/conf                                                         │
  │    irm-state-diff.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/inte                                                         │
  │    rnational-address.cypress.spec.js                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/low-                                                         │
  │    confidence.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/mili                                                         │
  │    tary-address.cypress.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/miss                                                         │
  │    ing-unit.cypress.spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/one-                                                         │
  │    suggestion.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/two-                                                         │
  │    suggestions.cypress.spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:05        1        1        -        -        - │
  │    e/tests/e2e/address-validation/vali                                                         │
  │    d-address.cypress.spec.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:08        2        2        -        -        - │
  │    e/tests/e2e/profile-a11y.cypress.sp                                                         │
  │    ec.js                                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:04        2        2        -        -        - │
  │    e/tests/e2e/profile.connected-apps.                                                         │
  │    cypress.spec.js                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:14        6        6        -        -        - │
  │    e/tests/e2e/profile.direct-deposit-                                                         │
  │    gating.cypress.spec.js                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:06        1        1        -        -        - │
  │    e/tests/e2e/profile.loa1.cypress.sp                                                         │
  │    ec.js                                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:11        2        2        -        -        - │
  │    e/tests/e2e/profile.mpi-error.cypre                                                         │
  │    ss.spec.js                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:10        2        2        -        -        - │
  │    e/tests/e2e/profile.not-in-mpi-erro                                                         │
  │    r.cypress.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:02        1        1        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-information-fields-check.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:13        2        2        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-information-modals.cypress.sp                                                         │
  │    ec.js                                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:01        1        1        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-information-vap-error.cypress                                                         │
  │    .spec.js                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/personalization/profil      00:10        2        2        -        -        - │
  │    e/tests/e2e/profile.personal-and-co                                                         │
  │    ntact-mailing-address.cypress.spec.                                                         │
  │    js                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  applications/personalization/view-r      00:06        1        -        1        -        - │
  │    epresentative/tests/view-representa                                                         │
  │    tive.cypress.spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/static-pages/health-ca      00:02        3        3        -        -        - │
  │    re-manage-benefits/schedule-view-va                                                         │
  │    -appointments-page/tests/index.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/appoint      00:08        4        4        -        -        - │
  │    ment-list.cypress.spec.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/communi      00:10        1        1        -        -        - │
  │    ty-care.cypress.spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/express      00:04        1        1        -        -        - │
  │    -care.cypress.spec.js                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/va-appo       17ms        3        -        -        3        - │
  │    intment.cypress.spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vaos/tests/e2e/va-requ      00:21        3        3        -        -        - │
  │    est.cypress.spec.js                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-1900/tests/e2e/      101ms        1        -        -        1        - │
  │    authenticated.cypress.spec.js                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-1900/tests/e2e/       73ms        1        -        -        1        - │
  │    unauthenticated.cypress.spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-8832/tests/e2e/      00:13        1        1        -        -        - │
  │    dependent-workflow.cypress.spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  applications/vre/28-8832/tests/e2e/      00:10        1        1        -        -        - │
  │    veteran-workflow-not-logged-in.cypr                                                         │
  │    ess.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  platform/site-wide/side-nav/tests/e      00:01        1        1        -        -        - │
  │    2e/sideNav.cypress.spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  platform/site-wide/user-nav/tests/e      00:12       12       12        -        -        - │
  │    2e/00-required.cypress.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  site/layouts/tests/vamc/smoke.mobil      00:01        1        1        -        -        - │
  │    e.cypress.spec.js                                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  7 of 88 failed (8%)                      30:03      177      141        7       29        - 
```

Cypress runs a build function in between each spec, like:
```
  Running:  site/layouts/tests/vamc/smoke.mobile.cypress.spec.js                          (88 of 88)
✔ Webpack
  Compiled successfully in 28.38ms
```

I'm not sure what effect running `NODE_ENV=production yarn build --buildtype vagovprod` has on running the Cypress tests (meaning, Cypress is obviously not running the tests on the production build because the tests that use `data-` attributes are passing). I've tried searching but couldn't find anything.

**Comment by holdenhinkle** [comment]
I'm running into issues with how to spot-check the production build of the site locally. Lots of pages that I want to review require a logged-in user. And some of the pages that do not require a user that have components that I can check aren't loading, like this one:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/7478a082-761d-48ac-a8c9-4a06d187cfaa)

Peter and I are going to meetup about this later.

In the meantime, I'm moving on to [this ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16994).

**Comment by holdenhinkle** [comment]
After running the commands to build and run the production website locally, it does not appear that the `data-cy` and `data-testid` attributes are being removed.

Example:
http://localhost:3001/resources/ still contains the `data-testid="resources-support-search` attribute on the `form` element:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/2d9fc9d6-580f-442e-98b0-185d54a69470)

Production build commands:
`NODE_ENV=production yarn build --buildtype vagovprod`
`NODE_ENV=production yarn build:webpack --env.buildtype vagovprod`

Researching why...

**Comment by holdenhinkle** [comment]
I posted to #vsp-tools-fe for help - https://dsva.slack.com/archives/CQH357ZTP/p1610143544345400

**Comment by holdenhinkle** [comment]
@billfienberg and I paired for an hour and confirmed that the plugin `babel-plugin-react-remove-properties` does work. We confirmed this by cloning [this repo](https://github.com/kentcdodds/jest-cypress-react-babel-webpack/), then we installed and configured the plugin and ran `BABEL_ENV=production npm run build`; the `data-testid` attributes were removed. We noted that entering the following commands separately, consecutively DID NOT work: `BABEL_ENV=production` then `npm run build`.

It seems that babel or this plugin isn't picking up that we're setting NODE_ENV (OR BABEL_ENV) to "production":

https://babeljs.io/docs/en/options#envname
> Type: `string`
> Default: `process.env.BABEL_ENV || process.env.NODE_ENV || "development"`

We hopped back to the `vets-website` repo and ran `NODE_ENV=production BABEL_ENV=production npm run build -- --buildtype vagovprod` that didn't work.

This didn't work either: `BABEL_ENV=production NODE_ENV=production npm run build -- --buildtype vagovprod`

What we learned:
- The plugin works
- Babel isn't picking up `NODE_ENV=production`

To be continued...

**Comment by holdenhinkle** [comment]
I met with Darius today to go over this ticket.

Darius pointed out that Jenkins is running the Cypress tests against `prod` and there are lots of failures because the `data-cy` and `data-testid` attributes are missing. So we verified that the `babel-plugin-react-remove-properties` plugin is working.

This presents a problem though: unless we can run the tests against `dev` or `staging`, we can't use this plugin.

Also, interestingly, Circle runs the tests against `prod` but they're passing. This means that Jenkins and Circle are compiling the `prod` builds differently, and the `prod` build command Circle is using isn't 'correct'.

We tried getting `prod` built 'correctly' locally using different commands but each build had the `data-cy` and `data-testid` attributes.

To-do:
- Find out what command Jenkins is using which produces the expected build.
- Find out if we can run Cypress tests against `dev` or `staging`.

Darius wondered if we can run our tests against prod and then remove the attributes.

It appears this is the build command Circle is using: `NODE_OPTIONS=--max-old-space-size=4096 webpack --config config/webpack.config.js --env.buildtype vagovprod --env.scaffold`
That's from: https://circleci.com/api/v1.1/project/github/department-of-veterans-affairs/vets-website/171517/output/105/0?file=true&allocation-id=5ff4d3398b8b664f84de67f6-0-build%2F3229A84A

**Comment by pjhill** [comment]
> I met with Darius today to go over this ticket.
> 
> Darius pointed out that Jenkins is running the Cypress tests against `prod` and there are lots of failures because the `data-cy` and `data-testid` attributes are missing. So we verified that the `babel-plugin-react-remove-properties` plugin is working.
> 
> This presents a problem though: unless we can run the tests against `dev` or `staging`, we can't use this plugin.
> 
> Also, interestingly, Circle runs the tests against `prod` but they're passing. This means that Jenkins and Circle are compiling the `prod` builds differently, and the `prod` build command Circle is using isn't 'correct'.
> 
> We tried getting `prod` built 'correctly' locally using different commands but each build had the `data-cy` and `data-testid` attributes.
> 
> To-do:
> 
> * Find out what command Jenkins is using which produces the expected build.
> * Find out if we can run Cypress tests against `dev` or `staging`.
> 
> Darius wondered if we can run our tests against prod and then remove the attributes.
> 
> It appears this is the build command Circle is using: `NODE_OPTIONS=--max-old-space-size=4096 webpack --config config/webpack.config.js --env.buildtype vagovprod --env.scaffold`
> That's from: https://circleci.com/api/v1.1/project/github/department-of-veterans-affairs/vets-website/171517/output/105/0?file=true&allocation-id=5ff4d3398b8b664f84de67f6-0-build%2F3229A84A

Ouch, that makes sense -- of course the tests are running against a prod build as that would provide the greatest value from the tests. This throws quite the wrench into the idea.

Your to-do re: Cypress against `dev` or `staging` is interesting, but it will require some careful analysis of the differences between `prod` and `staging` / `dev`.

**Comment by holdenhinkle** [comment]
Closing this ticket. We are not pursuing this further because we think asking that Cypress tests run against dev or staging instead of prod is too big an ask when compared to the small and currently unquantifiable bandwidth savings removing `data-testid` and `data-cy` attributes from production would provide us.
