### ISSUE TITLE
Yellow Ribbon Search 2021-2022 Academic Year Data Update

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16500]
## Issue Description
The data behind the Yellow Ribbon school search page [https://www.va.gov/education/yellow-ribbon-participating-schools/](https://www.va.gov/education/yellow-ribbon-participating-schools/) is updated annually to include participating schools in the upcoming academic school year.  The text on the search page needs to be updated with the new date range. See below.

![Image 4.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/8ae22e95-270d-4935-9ed8-630f1c90726e)

---
## Tasks
- [x] Contact Janice Fisher at VBAVACO (janice.fisher1@va.gov) to determine when new school data will be uploaded
- [ ] Confirm that August through July is still the correct range
- [ ] Update and stage text change so it can be deployed in conjunction with the new school data 

## Acceptance Criteria
- [ ] The Yellow Ribbon search page will display "...August 2021 through July 2022" where it currently displays "...August 2020 through July 2021".
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Noting that the new data should be available June 30, 2021 per Janice Fisher

**Comment by MarciMcGuireGCIO** [comment]
Contacted Janice Fisher again 6/14 to ask if they are still tracking for end of the month; asked them to let us know when they have a date set.  Got an OOO reply for her on 6/16; she is OOO until 6/21.  I am OOO all that week, as is the PO.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This is live on staging.

**Comment by MarciMcGuireGCIO** [comment]
Very nice!  I think this is good to move on up since it's just updating dates.
