### ISSUE TITLE
Revamp Facility Locator mobile experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16514]
## Issue Description
Problem: Mobile Facility Locator Map is not interactive and missing key information
- Map view is separate from the list view
- Pins do not reveal information about locations
- Using the map in conjunction with pins increases the cognitive load for Veterans
- Map is not screenreader accessible in its current state

- How can display useful information for each map location, independently from the List view?
- How can we design this information to be accessible with screen readers?

[Ideas from Chris Logan during Hackathon, November 2020](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/images/Facility%20Locator%20Mobile%20Chris.pdf)

---
## Tasks
- [ ] Create design spec based on Hackathon which can be used by engineers

## Acceptance Criteria
- [ ] Engineers are able to implement design
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
