### ISSUE TITLE
[DESIGN] "use my current location" in Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16511]
## Issue Description
This idea from @mpelzsherman - Hackathon, November 2020
Veterans need to be able to opt-in for geolocation at the search level, rather than the browser level. It should not be auto-detected. We need to implement a call to action.

<details>
<summary> Example of similar experience: Best Buy </summary> 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/62fd1b8b-c8ca-484b-a37d-edc7dba97f6f)

</details>

---
## Tasks
- [ ] Consider how to represent the geolocation search is occurring to Veteran (where does it appear) 
- [ ] Consider mobile experience 
- [ ] Consider accessibility for screenreaders: how will veteran be notified, how will it be activated and flow for focus state
- [ ] Design experience for "use my current location" hyperlink next above City, state or postal code field, including the following behaviors
       - Veterans can enable use of current location through hyperlink at search level
       - When a Veteran clicks the link, the parameters populate the search field
       - There is an indicator that the location is being identified "searching"

## Acceptance Criteria
- [ ] Build-ready design spec, consistent with design system with detail on font, color, transparency  and accessibility

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrisdlogan** [comment]
[Geolocation Competitive Analysis.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5771936/Geolocation.Competitive.Analysis.xlsx)

**Comment by chrisdlogan** [comment]
[Geolocation - Analysis & Recommendations.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5771937/Geolocation.-.Analysis.Recommendations.pptx)

**Comment by mmiddaugh** [comment]
https://app.zeplin.io/project/600877fdb269d8a4f1f44efd/screen/600879364afaa6a6a2a8a827
