### ISSUE TITLE
Clear input field (FLocator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16513]
## Issue Description
This idea from @lildziner during Hackathon, November 2020
Veterans need a way to efficiently clear the City, state or postal code and Service typeahead fields so that they can the input(s) 

This design was discussed with Josh and his feedback was incorporated. 
**When engineering begins, we should also seek feedback by posting in the va-search channel since they’re wrangling with another/similar tricky search pattern**

## Tasks
- [ ] Add x to clear fields consistent with spec: 
![Specs](https://user-images.githubusercontent.com/4960080/102925614-b5f23d00-4461-11eb-814d-e9e15318aef9.png)
- [ ] Reference [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17272#issuecomment-748089382) for details 
- [ ] Review [Josh's accessibility comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17272#issuecomment-748218659) regarding accessibility
- [ ] Implement the screen reader only class and using aria-hidden on the svg. 
- [ ] Review implementation with team designers and accessibility team

## Acceptance criteria
- [ ] Clear field icon is consistent with design spec with regard to padding, size and expected behavior. 
- [ ] Clear input button appears after first character is inputted
- [ ] While text is being inputted and exceeds the input's width, the text moves left. 
- [ ] Text area is never overlapped by clear input button while field has focus
- [ ] When user exits input (no longer in focus) the inputted text displays left to right. Overflow text (at the end of the text string) is overlapped by clear input button. 
- [ ] Veteran can clear input by clicking on the x. 
- [ ] When clear button is clicked, input is cleared and design matches "Before interaction" state.
- [ ] Veterans using assistive screenreaders are aware of this functionality.
- [ ] Hidden aria label "clean input button" when in focus to make it available to assistive tech 
- [ ] Search is not available until all required fields have been populated. 
- [ ] Consider submitting this as an addition to the Design system.

**Comment by mmiddaugh** [comment]
![image](https://user-images.githubusercontent.com/55411834/102924895-a79b2580-444f-11eb-8aa2-ad01e85b01af.png)

**Comment by lildziner** [comment]
This was a response from a while back when I inquired about whether or not this functionality already exists
![image](https://user-images.githubusercontent.com/4960080/102926462-061dcf00-4463-11eb-8b89-8301a0ec176e.png)

**Comment by lildziner** [comment]
A old thread with some discussion on this  - may or may not be useful. https://dsva.slack.com/archives/C0NGDDXME/p1598280780011700

**Comment by mmiddaugh** [comment]
Hi @1Copenut if you're able to take a peek at this new feature in Staging while Josh is out, we'd love your input on: 

- focus flow (it's an image, rather than a button so we'll need to apply it manually.) 
- how to announce for screen readers

Basically, it has been implemented without either so we can determine the best approach by looking at it in Staging and kicking the tires, so to speak.

**Comment by 1Copenut** [comment]
HI @mmiddaugh. I had a few minutes at the end of the day today to start reviewing this clear input field. I tried it out with a mouse and keyboard, then viewed the HTML.

I wasn't able to use the input with keyboard because it was added to the page source before the input and is an element that couldn't take keyboard focus. I wrote up the following HTML snippet as a possibility. LMK if you'd like to review next week with your team and we can put a meeting on the calendar.

```html
<div class="input-clear">
  <input
    id="street-city-state-zip"
    name="street-city-state-zip"
    title="Your location: Street, City, State or Postal code"
    type="text"
    value="Austin"
    required
  />
  <button aria-label="Clear your city, state or postal code" type="button">
    <i
      aria-hidden="true"
      class="fas fa-times-circle clear-button"
      id="clear-input"
      role="presentation"
    ></i>
  </button>
</div>
```

```css
div.input-clear {
  position: relative;
}

div.input-clear button {
  /* Set your position from right and top to add the button exactly where you want it */
  position: absolute;
  z-index: 1;
}
```

**Comment by mmiddaugh** [comment]
Creating [a new issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2105) with Trevor's feedback
