### ISSUE TITLE
Footer link update on VA.gov homepage from VFS-CMS

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#16520]
### Content support for:
- Unauthenticated (static) VA.gov pages
- Apps or tools
- Other writing or editing requests

### Engineering support for:
- Redirects that have **first been vetted by the VSP IA team**
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [ ] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * < description > 
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

- [ ] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * https://www.va.gov/orm/NOFEAR_Select.asp (the "No FEAR Act Data" link in the footer for VA.gov), Brendan Fitzgerald from EHRIS (Enterprise Human Resources Information Services) is requesting that it be updated to: https://www.va.gov/ormdi/NOFEAR_Select.asp

   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * < list of new info >
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * < list of new info >

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Based on the attached email, it sounds like as soon as possible but I will verify and update in the comments.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: VFS-CMS
- DEPO product owner: Jeff Barnes 
- Product manager: Kevin Walsh
- Designer: Jordana Mello
- FE engineer: N/A
- Product/team Slack channel: CMS; `#cms-team`

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by cmaeng** [comment]
Based on [this slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1606146042473500), tagging in @mnorthuis .

**Comment by cmaeng** [comment]
Converting email conversation to a Word file. 
[Footer link update request email.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5584241/Footer.link.update.request.email.docx)

**Comment by cmaeng** [comment]
Response from Brendan Fitzgerald through email: "yes it needs to be updated ASAP."

**Comment by DanielleThierryUSDSVA** [comment]
Hi @brianalloyd. This looks like a dev-only change to a link URL in the footer. Could you please look into this and coordinate with our engineers to update? Let me know if you have any questions. Thank you!

**Comment by brianalloyd** [comment]
@cmaeng Intake request received and acknowledge the urgency.  Team will jump on this now, thanks. @kelsonic can you take a look at this and advise on estimate, thanks.

**Comment by mnorthuis** [comment]
This change is good to go.   I would recommend notifying the requestor to implement redirects to their old URLs to ensure all traffic is captured and sent to the new URLs.

**Comment by brianalloyd** [comment]
Thanks @mnorthuis for the quick review.  @cmaeng be advised that a PR is already in flight for the update @kelsonic is the quickest trigger in the west and got this knocked out quickly.  Please let us know what questions remain.  Once Validated we'll closeout this ticket in support.

**Comment by kelsonic** [comment]
@mnorthuis that's a great point, I can implement the redirect as well right now. Is that desired?

To be pedantic, that would mean:

**Current URL** => **Destination URL**
`https://www.va.gov/orm/NOFEAR_Select.asp` => `https://www.va.gov/ormdi/NOFEAR_Select.asp`

**Comment by mnorthuis** [comment]
@kelsonic I'd prefer that we are not responsible for redirects that are not part of/unrelated to the modernized site...so let's try to get them to handle it on their side.
