### ISSUE TITLE
Prepare for EDU DD Usability Sessions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16524]
## Goal
Conduct usability sessions for Direct Deposit for EDU to understand how a Veteran is currently interacting with this feature holistically so that we can create a more accurate description of what needs to be further developed or iterated upon.

## Considerations
- Use a research plan and conversation guide (included in previous delivery, linked below)
- Conduct a usability session that answers pain point questions and informs the team what the best thing to build might be
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)
- Estimated to start Monday after Thanksgiving, November 30, 2020
**UPDATE:** Dec 2 to Dec 7

## Tasks
- [x] Incorporate feedback from usability testing prep for research plan
- [x] Kickoff recruiting with Lauren
- [x] Coordinate sessions with user research partner (Perigean), asking them to take notes 

**Next Sprint**
- [ ] Use the [research plan](#), and included [conversation guide](#) to conduct sessions
- [ ] Topline summary

## Acceptance Criteria
- [x] Usability studies have been requested for scheduling

**Comment by sporeboy** [comment]
Usability sessions scheduled from 12/2 to 12/7. Pilot session scheduled 11/30.
