### ISSUE TITLE
[Development] BDD: Update STR Content, Make Very Clear That STR is NOT Required for BDD

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16531]
## Issue Description
We made the executive decision that we will not delay BDD any further in order to fix all of the STR upload issues.  The last real issue is the file size and we have to wait for EVSS to implement it.  In the meantime, we want to change the STR page to encourage veterans to not get stuck on it. 

This is the before:
![Screen Shot 2020-11-20 at 8 46 12 AM](https://user-images.githubusercontent.com/53824125/100010312-4ff49600-2d8d-11eb-90ef-0ff009102080.png)

We would like that first sentence to look like this:
Do you want to upload your service treatment records? <strong> You can still submit a BDD claim without your service treatment record. <strong>

---
## Tasks
- [ ] Implement change above on the STR page.

## Acceptance Criteria
- [ ] Kevin (if he has a chance) reviews this.
- [ ] We can get Peggy to approve (although it is a very minor change)
