### ISSUE TITLE
[FSR] CH2 content review

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#16530]
## Issue Description
_We recently updated the FSR's CH2 designs and would like a quick content spot check._

---
## Tasks
- [x] _Review [CH2 in UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410885/comment/comments,sitemap?mode=i) for content mistakes and improvements_
- [x] _Add comments containing suggested content as needed_ 

Reach out to Becca/Riley with any questions!

## Acceptance Criteria
- [x] _CH2's content has been reviewed_
- [x] _Content changes have been commented in the UXPin prototype_
- [ ] _A comment has been left on this ticket once the review is complete_

**Comment by 3obryandogs** [comment]
I've finished the review. Please note Social Security is always capitalized. I also noted a style for the bottom "help" note. You can choose Monday-Friday, or Monday through Friday, but the time style needs updating.

**Comment by rileyorr** [comment]
Hey, @3obryandogs! This ticket isn't in the current sprint, so no worries getting to it unless your other tickets are complete :) 
I'll create a separate ticket for myself to incorporate your edits. 

Thanks for getting this review done so quickly! I don't see many edits so I just want to double-check: is everything written in plain language and match our content style guide? Are there any areas where our content could be clearer and/or more empathetically-written for our users?
