### ISSUE TITLE
Design Intent Collaboration: BAH - Comparison Tool - The Comparison Feature

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#16546]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in team name and feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #design in Slack; tag @ Allison Christman & @ Emily Waggoner
- [x] Allison and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] Design Intent collaboration meeting completed 
- [ ] [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated
- [ ] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/ct-redesign-discovery_product-outline.md)
- [Mural Sketches](https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1605879130829/3c2aceb3e99f2da8a1a1dcd4537f7cc8fde524fa)
- [Lo-fi mockups](https://bahdigital.invisionapp.com/share/U6IAFMLG9RD)

## Meeting attendees from **Booz Allen**
- Designer(s) (required): Emma Waters, Jen Jones, Amy Knox
- Product Manager (optional): Darrell Neel
- Other BAH team members who like invites: Will McCormack
- DEPO design lead (required as applicable): Ryan Thurwell 
- Other specialists: 
Emily Waggoner, Allison Christman, Trevor Pierce

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Crystabel will reach out as needed_

**Scheduled time: Dec. 1, 11:30am ET** 

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by shiragoodman** [comment]
thanks @amyknox . FYI that timeslot is no longer available.

**Comment by amyknox** [comment]
@shiragoodman - we'll take 11:30 then

**Comment by allison0034** [comment]
Hi @amyknox the meeting has been scheduled for Dec 1 at 11:30. Please be sure to upload all artifacts 2 days prior. Looking forward to seeing this.

Also, I believe you will be creating a new feature (mobile comparison table). If so, can you please submit a [feature request ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?template=feature_request.md) to the design services council so we can reuse this in the future? Let me know if you need any help or brain storming ideas. : )

**Comment by amyknox** [comment]
Thanks @allison0034 - let's see where we are on Tuesday and if we're ready for the feature request.

**Comment by allison0034** [comment]
Here is the [zoom recording](https://zoom.us/rec/share/vJnVe2phA7L8l2TxkVyJ2g5OZysVK78qiiSCRlO-VVIu7jW-YxEX7hKn6FTQ84L4.QgxLPw2nrmuJfbgL) from the meeting.

Passcode: fXRy75*=

**Comment by watersemma** [comment]
Thank you @allison0034 @mnorthuis @1Copenut we will work to incorporate your feedback.

**Comment by amyknox** [comment]
@emilywaggoner @allison0034 - This seems like it should be closed. Can we do that?
