### ISSUE TITLE
Track # of Secondary-only applications

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16548]
## Issue Description
How might we track the number of 10-10CG applications that have only a secondary caregiver?

---
## Tasks
- [ ] Query created

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
Completed in Sprint 35. Created query in CloudWatch to list all submissions within a given time period and identify which form subjects are present in each.

Emailed the results to be forwarded to the Caregiver Program.

Query:
```

```

Formatted Results:
request_id | claim_guid | carma_case_id | vet_icn | pc_is_present | sc1_is_present | sc2_is_present | attachments_dropped
-- | -- | -- | -- | -- | -- | -- | --
{uuid}|{uuid}|{case_id}|{blank}|{1\|0}|{1\|0}|{1\|0}|{1\|0}
