### ISSUE TITLE
Remove environmental checks for facility page templates

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16543]
## Issue Description
Legacy environmental checks that change side nav on news story and event templates make troubleshooting and testing in local environments more difficult. Since the code is no longer needed, it can be removed. 

---
## Tasks
Remove environmental checks from the following facility page templates
- [x] `src/site/layouts/news_story.drupal.liquid`
- [x] `src/site/layouts/event.drupal.liquid`

## Acceptance Criteria
- [x] Confirm relevant pages still render as expected in production
- [x] Confirm no new issues are created on facility pages or other template pages

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@ethanteague @kevwalsh are you aware of any environmental checks which should be preserved for facility pages?

**Comment by ethanteague** [comment]
> @ethanteague @kevwalsh are you aware of any reason the following environmental checks should be preserved for facility pages?
> src/site/layouts/news_story.drupal.liquid
> src/site/layouts/event.drupal.liquid

Nope, there shouldn’t be any in place at this time, @mmiddaugh
