### ISSUE TITLE
Project Kickoff – Authenticated Experience [Preferred VA Facility]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#16557]
## Steps to complete Project Kickoff
- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Attach all relevent artifacts to the ticket
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] Shira will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] Kickoff meeting completed 
- [x] [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- [Preferred Facility Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/preferred-facility)

## Meeting attendees from **requesting team**
- DEPO Product Lead (required): **Samara Strauss**
- Product Manager (required): **Matt Shea**
- Team members: **Sandra Hallie, Erik Hansen, Tressa Furner, Cassandra Allen, Lihan Li**
- QA: **Tze Lei**
- Accessibility: **Jennifer Strickland**

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages? **No**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now

## Selected time slot: Wednesday, 12/2 at 11:30am-12pm ET

**Comment by shiragoodman** [comment]
@mshea0606 we already have 11/30 at 3:30 reserved. Please check the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) for availability - earliest right now is Wednesday 12/2

**Comment by mshea0606** [comment]
@shiragoodman Wed 12/2 at 11:30am works

**Comment by shiragoodman** [comment]
@mshea0606 can you please add this to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809)?
