### ISSUE TITLE
Adjust Flipped Content for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16573]
## Background
There is an item that needs to be removed for clarification of the end state of the flipped feature.

## Tasks
- [x] Remove "Ready to apply" anywhere that needs this for the CH31 feature

## Acceptance Criteria
- [x] The feature toggle has been adjusted accordingly
- [x] A PR has been requested for merging
