### ISSUE TITLE
Create 2021 Pension rates pages in Drupal

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#16570]
## Issue Description
_Update the pension rate amounts for 2021_
[VA protected disability and death pension rates](https://www.va.gov/pension/protected-pension-rates/)
[Survivors pension rates](https://www.va.gov/pension/survivors-pension-rates/)
[Veterans pension rates](https://www.va.gov/pension/veterans-pension-rates/)

Document for reference:
[2020 Pension Rate Tables-Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5592071/2020.Pension.Rate.Tables-Final.docx)

---
## Tasks
- [ ] _Clone 2020 pension rates pages (Selina)_
- [ ] _Update main pension rates pages with 2021 info (Selina)_
- [x] _Review pages and publish (Randi)_

## Acceptance Criteria
- [ ] _Pages are live _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @RLHecht cc: @bethpottsVADEPO here are the pages for review.

**VA pension rates for Veterans:** (see pg. 2 of Pension doc)
- Current rates: http://preview-prod.vfs.va.gov/preview?nodeId=591
- 2020 rates: http://preview-prod.vfs.va.gov/preview?nodeId=11019

**VA Survivors Pension benefit rates:** (see pg. 3 of Pension doc)
- Current rates: http://preview-prod.vfs.va.gov/preview?nodeId=589
- 2020 rates: http://preview-prod.vfs.va.gov/preview?nodeId=11020

**VA protected disability and death pension rates:** (see pg. 4, 6, 7, 8 of Pension doc)
- 2021: http://preview-prod.vfs.va.gov/preview?nodeId=5090
- 2020: http://preview-prod.vfs.va.gov/preview?nodeId=11021

**Comment by RLHecht** [comment]
These rates have all been reviewed and are ready to publish when we get the OK. 
Reminders to myself before publishing:
- Update URLs for 2020 rates pages
- Add new past rates page to left nav

**Comment by RLHecht** [comment]
These pages have been published. Moving to validate. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
These pages are live on the site. I republished the Veterans and Survivors Pension pages today after adding 2021 to the H1 and the meta title. Closing this ticket.
