### ISSUE TITLE
[FE]Dynamic Title based on stop code

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16579]
## User Story
As a veteran, I should the title reflect the appointment type, so that I know what form I am filling out

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f7b3ab94e155b94041d4c4b)

## Description
The title of the form, should be dynamic and reflect the stop code that is in the appointment data. 

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [x] Determine relevant stop codes and UI text
- [x] Add mapping logic in util method to be reused where it's needed. 
- [x] Implement for the Form header
- [x] Implement for the list manager questionnaire card. 
- [x] Create unit tests

## Acceptance Criteria
- [x] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Moving forward with only Primary care. https://dsva.slack.com/archives/C0136TS768M/p1610483148040600
