### ISSUE TITLE
[FE] Pull in real appointment data for the quesitonnaire

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16581]
## User Story
As a veteran, I should see my appointment details, so that I know what appointment this form is for

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Feature Doc](%FILL IN%)

## Description
Pull in real appointment data for the form, and not mock data. 

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [x] Populate redux with the selected Appointment data. 
- [x] verify that the appointment details populate correctly
- [x] load data on form home page
- [x]  load data from session storage if loaded from the middle fo a form
- [x] Create user tests
- [x] Create e2e tests 
- [x] Update relevant documentations

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
This should pull in real data, when real data is supplied on the questionnaire list

**Comment by mdewey** [comment]
![Screen Shot 2021-02-25 at 10 43 57 AM](https://user-images.githubusercontent.com/1793923/109177987-60365b80-7756-11eb-8763-a69ab86414f0.png)

Data is being populated in staging. Verified with the above picture.
