### ISSUE TITLE
Replace Community Care service type prompt (FLocator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16586]
## Issue Description
Currently, the prompt for the Community Care service typeahead is "Like primary care, cardiology". However, based on the current NUCC taxonomy, neither is a valid search term. We need to replace this typeahead prompt with successful search terms. This is a short term solution until we can solve the taxonomy more completely. 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/6934cbf2-ef69-44d1-86b5-33cba478bc89)

Most frequently searched terms (based on specialty code)

- Clinic/Center: Urgent Care
- Clinic/Center: Primary Care
- Chiropractor	
- Optometrist	
- Acupuncturist	
- Physical Therapist	
- Orthopedic Surgery	
- Dermatology	
- Counselor: Mental Health
- Urology	

<details>
<summary> This language is also seen in the error message </summary>

![image](https://user-images.githubusercontent.com/55411834/100805662-4eaa1580-33ec-11eb-8965-5a53c613c28f.png)

</details>

---
## Tasks
- [ ] Replace typeahead prompt with "like Chiropractor or Optometrist"	
- [ ] Replace error text with "like Chiropractor or Optometrist"

## Acceptance Criteria
- [ ] When Community providers (in VA's network) is selected as a facility type, the typeahead Service type box contains "like Chiropractor or Optometrist"

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
I see this change in Staging but not Prod

**Comment by mpelzsherman** [comment]
This has been pushed to production.
![Find_VA_Locations___Veterans_Affairs](https://user-images.githubusercontent.com/80267/103303089-1db10680-49d3-11eb-98c1-978f28d099fa.png)
