### ISSUE TITLE
[FE] Submit Answers to API

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16580]
## User Story
As a veteran, I should be able to submit my answers into PGD, so that my providers can see my answers

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
Send the user's answers to the vets-api and thus into PGD.

## Tasks
- [x] Agree on JSON format 
- [x] Update the submit method for the form to POST data to PGD
- [x] Adde error state message for failed POST
- [x] clear session on successful submit
- [x] Create user tests
- [x] Create e2e tests 

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
link to the gist of current structure: https://gist.github.com/mdewey/04acc00fe1f83fd6f6f9fe24ebf23b61

**Comment by mdewey** [comment]
This can not be completed 100%. That is because we are moving to the lighthouse for the submitting and the current endpoint is pointing to MAP, and that is not working. So the engineering team has decided to focus on the lighthouse and not fix the map PGD. This ticket now represents the JSON structure.

**Comment by mdewey** [comment]
Merged to master, need to verify in staging

**Comment by mdewey** [comment]
In master, deployed to staging. Nothing to really to visually verify or to confirm is working, but the form update is successfully deployed.
