### ISSUE TITLE
[FE][IA] Update the URLs

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16594]
## User Story
As a veteran, 
I should see a consistent URL
so that I understand where I am on va.gov

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [IA Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-questionaires.md)
- [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d5e01a9b85b431a14)

## Description
Update the URLs to match what IA. proposed

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [x] Update URL for questionnaire list
- [x] Update URL for questionnaire
- [x] udpaste URLs for tabbed nav
- [x] rename folder
- [x] Update URL link for questionnaire list to  the form
- [x] Update link on submission page
- [x] Add URLs to server config. 
- [x] Create user tests
- [x] Create e2e tests 

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
blocked until https://github.com/department-of-veterans-affairs/vets-website/pull/15294 gets merged in

**Comment by mdewey** [comment]
All but the OMB fix in the PR, there is a bug with the latest package of formation-react. This will be blocked once all the other changes get merged in and the fix in formation-react is don't fixed.

**Comment by mdewey** [comment]
Merged in master. waiting for deployment to staging.

**Comment by mdewey** [comment]
The URLs are updated in staging: 

https://staging.va.gov/health-care/health-questionnaires/questionnaires/answer-questions/introduction 
and
https://staging.va.gov/health-care/health-questionnaires/questionnaires

@abuckley3385  and @kristenmcconnell -- Does that look good to you?

**Comment by kristenmcconnell** [comment]
I thought the actual questionnaire was going to have that weird ID thing that Mikki talked about and listed in the IA doc (.../answer-questions?id=[id#]), but I like this better. And most of it looks great. If I'm being really picky, I have a few comments. Looking at other forms, the names of the progress bar steps seem to be in the URLS. 

Therefore, the demographics page should actually be .../answer-questions/veteran-information

The reason for visit page should be.../answer-questions/prepare-for-your-appointment

We also seem to be hyphenating between most words. Should the To Do page be hyphenated then? Not .../questionnaires/todo, but .../questionnaires/to-do

I think all of the other URLs look good.

In the grand scheme of UX things, I wouldn't mark these changes as urgent.

**Comment by mdewey** [comment]
I will create a ticket for the updates to the URLs to match the page title. It will go into my backlog to get to at some point.

**Comment by mdewey** [comment]
Creating this ticket :https://github.com/department-of-veterans-affairs/va.gov-team/issues/17501
