### ISSUE TITLE
[FE][IA] Update Content

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16591]
## User Story
As a veteran, 
I should see useful information on the intro page
so that I have a better understanding of the form

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [IA Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-questionaires.md)
- [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d5e01a9b85b431a14)

## Description
Update the content with regards to the feedback

## Tasks
- [x] Intro page:  update content
- [x] Intro Page: New title
- [x] Footer: All new content
- [x] Confirmation page: wording on bottom buttons
- [x] Update the OMB component to be more dynamic
- [x] Create user tests
- [x] Create e2e tests 

## Acceptance Criteria
- [x] Passes Accessibility checks using axe
- [x] PR has been merged into master
- [x] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
![Screen Shot 2020-12-04 at 3 01 40 PM](https://user-images.githubusercontent.com/1793923/101209372-9fff1280-3641-11eb-9a91-896e05f5fa03.png)

BLOCKER:

Context: 
We have decided to keep the Privacy Statement Act, but hide the OMB number and expiration date. Those three items are the same component, (along with Respondent burden) that is owned by the platform team. In order to hide the OMB number and expiration date, we need to make modifications to that component. We have done this in the past, so from a tech perspective that is not an issue. 

Currently, in order to hide the OMB number and expiration date, we would have to copy and content from the Privacy Statment Act and then own that content for our team. We do not want to copy the code, because we do not want to own the content in the Privacy Statement Act. Also, there is content in the Privacy Statement Act that does not apply to us, since we do not have an OMB number or a time burden, that we need to hide.  

Updating this component is not an issue technically, but more of a process issue. I have updated the component before, but to update a component I will need to have some approval to the hiding the expiration date and updating the privacy content to be dynamic. 

We have also found that the text in the Privacy Statement Act modal is not correct for most forms. Currently, it is hardcoded for `education benefits`.  Other teams have solved this but copying and pasting the Privacy Statement Act content and changing it for their team. 

If we are okay with owning the content inside the Privacy Statement Act modal for our own team, then this is not a blocker, but after consulting @kristenmcconnell, we do not want to own that content.

Questions: 
- Does the <strong>Privacy Act Notice:</strong> content of the Privacy Statement Act modal still apply to us or do we need to have our own? 

Blockers:
- For the expiration date removal, unless we want to try to get approval from ??? earlier, we can use the upcoming usability study to confirm the removal of the expiration date, then I can make the changes to the platform and go from there.

Action Items: 
- @kristenmcconnell  is going to take this to the design council that the information is not correct, and @mdewey will take this to the engineering team for a technical fix for the problem. 
- @abuckley3385  For the content, where would we get approval for that content change, and remove the expiration date. 



@kristenmcconnell  Did I miss anything?

**Comment by kristenmcconnell** [comment]
@mdewey We were suggesting removing the expiration date, because it is hardcoded and our forms have dynamic expiration dates. If we can make the expiration dates dynamic, which it sounds like we can, then lets leave the expiration date in the design. I'll update the wireframes.

**Comment by kristenmcconnell** [comment]
Wireframe updated. Expiration date added back in.

**Comment by mdewey** [comment]
Thank you @kristenmcconnell  and @abuckley3385. This no longer has a blocker.

**Comment by mdewey** [comment]
Content changes in PR

**Comment by mdewey** [comment]
Content PR has been merged to master, waiting for deployemtn

**Comment by mdewey** [comment]
@kristenmcconnell  This is now in staging. Let me know if you have any feedback

**Comment by kristenmcconnell** [comment]
1. Well, I found something that is totally my fault. If you read the "What happens after I answer the questions?" answer, we have one sentence twice (but we slightly different wording). That happened when I went to add in the bolding for emphasis. The wireframes have been updated.

2. I see that the OMB component isn't checked off above in this ticket. Is that why I'm still seeing the OMB Control #: in the UI?

3. The confirmation page buttons don't match the wireframe. They are both supposed to have "your" in the wording. This is what I see. 
![Screen Shot 2020-12-09 at 5.29.44 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8f296af6-8b56-4d35-8a3a-a01fc48e3ce5)

**Comment by mdewey** [comment]
I will get to this today! 

And yes, the OMB stuff is still in PR, so that is not done yet.

**Comment by mdewey** [comment]
Merged in master, will notify when its in staging

**Comment by mdewey** [comment]
In staging, and ready to be reviewed

@kristenmcconnell  and @abuckley3385

**Comment by kristenmcconnell** [comment]
Only one comment...
When removing the duplicate sentence (each had slightly different wording) from the "What happens after I answer the questions?", the wrong wording was removed/bolded. The bolded sentence should use this wording...
![Screen Shot 2020-12-15 at 11.55.49 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/877ca474-16bb-4638-b9ab-142b315542bc)

I'd say wait to make this change though. We heard that the VA security and policy people are reviewing the privacy question and answer on this page. We already know that changes are coming. It is just my thought that you could tackle both of those together. Just an idea. Up to you and @abuckley3385. 

I have a story in my backlog to talk to platform about the changes needed to the actual Privacy Act Statement.

**Comment by mdewey** [comment]
I can add the text update to the breadcrumbs PR.

**Comment by mdewey** [comment]
Here: https://github.com/department-of-veterans-affairs/vets-website/pull/15368/files

**Comment by mdewey** [comment]
@kristenmcconnell  The content feedback is in staging. Can you verify?

**Comment by kristenmcconnell** [comment]
It is great. The sentence is now correct.
