### ISSUE TITLE
EKS - Cluster for testing deployments

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#16602]
## Description
Deploy an EKS cluster for testing by the VSP Ops team.

## Background/context/resources
* Should use the terraform module to provision cluster
* Should pre-provision authentication configmap with Ops team members

## Technical notes
EKS Module: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks

---
## Tasks
- [X] Deploy EKS cluster in `dev` to use for testing

## Definition of Done
- [X] Everyone in VSP Ops can access/use test EKS cluster as validated by `kubeconfig`
---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
Test cluster is deployed and accessible here:

https://console.amazonaws-us-gov.com/eks/home?region=us-gov-west-1#/clusters/dsva-vagov-dev-ops-test-cluster

**Comment by jbritt1** [comment]
Long moved past the scope of this ticket. We have stood up multiple clusters now leveraging the referenced modules. Closing.
