### ISSUE TITLE
EKS - deploy "platform-tools" cluster in DEV

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#16604]
## Description
Deploy a `platform-tools` EKS cluster in `dev`.

This will be a permanent cluster and used by both VSP Operations and other teams to host tools/services to support the VSP Platform (ie: Sentry, Grafana, Loki, etc..)

## Background/context/resources
* Should use the terraform module to provision cluster
* Should pre-provision authentication configmap with Ops team members
* Manually deployed node groups are fine for this cluster.
* May need to update tf module to support creating namespaces and SA's in order to make it usable by other teams.

## Technical notes
EKS Module: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks

---
## Tasks
- [x] Deploy a permanent EKS cluster in `dev` for platform-tools
- [x] Create node group and worker nodes in cluster

## Definition of Done
- [x] Everyone in VSP Ops can access/use test EKS cluster as validated by `kubeconfig`

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Reviewed by Demian and I. Looks good. Closing.
