### ISSUE TITLE
Add standard GA event to ErrorableRadioButtons

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16615]
## Background
GA Team wants to have standardized events in wizards. Since we are currently adding events for our wizard work we have offered to add a standardized event that matches the spec the analytics team has provided us for onChange to radio buttons in the wizards. That standardized spec can be found [here in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15757) and looks like this -

```javascript
'event': 'howToWizard-formChange',
'form-field-type': '<form_component_type>',
'form-field-label': <question_text>',
'form-field-value': '<question_answer_or_form_value>',
```

## Tasks
- [x] Update the error radio button file in platform to use a `standardGAEvent` property to fire the standardized event
- [x] Request a PR

## Acceptance Criteria
- [x] Events for radio button change is now a standardized event
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Checking in with Jon to see if it would be a good idea to standardize these a little

**Comment by jonwehausen** [comment]
@cohnjesse Closing this, our team is working thru standardization this quarter. Appreciate your efforts for standardizing the how to wizards
