### ISSUE TITLE
Update Tags component layer with new meta data field

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16623]
## Update Tags component layer with new meta data field for non-beneficiary audiences - global layer update for all article templates in RS

The CMS is adding non-beneficiary audience tags. 

In the FE, all tags show as tags, no differentiation among classes of tags (content vs. beneficiary audience vs. non-beneficiary). However, in the CMS,  non-beneficiary audiences will be a new field, so the FE will need to include this new field in the logic. 

**AC:** 
- [x] Non-beneficiary audience tag field is added to FE. 
- [x]  FE is updated for the Tags component for all article templates globally. 
- [x] All tags in the frontend are displayed in alpha order.
- [x] Transformer is updated (if needed) 
- [ ] Validated with a preview by @jenniferlee-dsva 

_Note: In the CMS, authors will not be able to check both a beneficiary and a non-beneficiary tag for an article. This restriction will be controled in the CMS, but just letting FE know here, in case it impacts FE template work._

**Comment by jenniferlee-dsva** [comment]
@oksana-c  - can you comment here when the non-beneficiary meta data field work is completed in the CMS?

**Comment by brianalloyd** [comment]
@ncksllvn picking up

**Comment by ncksllvn** [comment]
This work has been merged and should be available in the preview server by EOD

**Comment by brianalloyd** [comment]
This looks good on my end, @jenniferlee-dsva and @johnhashva can you validate this meets the intent?  Thanks.

**Comment by johnhashva** [comment]
Leaving this one to @jenniferlee-dsva 's super sharp eyes.

**Comment by jenniferlee-dsva** [comment]
Sure - which should I use -- staging or prod preview to validate @brianalloyd ?

**Comment by brianalloyd** [comment]
@jenniferlee-dsva should be ready on prod preview for validation.  Thanks for the review.

**Comment by jenniferlee-dsva** [comment]
👍 Validated that the alpha sort ordering logic of tags works. 

**In mobile (simulated on Chrome)**
The 'box/border' is expanding as intended - the whole thing gets fatter to accommodate wrapping. However, I think there might be a tad too much padding/space for the right hand side of the border. My eye is not a visual designer's eye, so I'd like to confirm with @rtwell. 

![image](https://user-images.githubusercontent.com/43381063/111640758-e16f9400-87d2-11eb-9d0b-9f399071e044.png)

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/111647723-1aab0280-87d9-11eb-9abd-acd668e06ebb.png)

**Comment by ncksllvn** [comment]
I'll try to update that style.

**Comment by ncksllvn** [comment]
@kelsonic I am drawing a blank on how to write CSS for the style as shown in the screenshot above. Any ideas? Basically, the tag has text so long that it wraps to the next line. The design is calling for the width to sort of collapse inward so that it only expands to the edge of the text. I don't want to say this isn't possible but I am struggling to figure it out.

**Comment by kelsonic** [comment]
This looks surprisingly difficult to achieve with CSS actually. Some css properties that could help:

```css
inline-size: 150px; /* or min-content */
overflow-wrap: break-word;
hyphens: manual; /* probably not useful */
word-break: break-all;
```

One crazy solution we could experiment with is counting the number of characters in a line and once it exceeds a certain amount, break up the word into a separate tag:

```html5
<p class="tag">
  <p class="line">Career counselors and other</p>
  <p class="line">employment specialists</p>
</p>
```

But tbh all of the above solutions really seem either 1) not feasible or 2) not maintainable, so I might recommend us just going with the approach of doing something like:

```css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

where for each tag we can put on an aria-label so that if the user hovers over it or reads it with a screen reader it will say the full text of the tag

**Comment by brianalloyd** [comment]
@ncksllvn @kelsonic can you provide a status update on this ticket, looks like good CSS discussion above and that alpha sort ordering logic of tags works but mobile needed some tweaks.

**Comment by ncksllvn** [comment]
Yeah sorry about the wait. We have a thread on this subject here, https://dsva.slack.com/archives/C52CL1PKQ/p1616178363122500.

Basically, this design doesn't appear to be easily achievable without some side effects on accessibility - wrapping each word in its own HTML tag so that we can derive the border box against the right edge of the words. This would be very verbose for screenreaders.

This UI pattern is sometimes called a "pill box" where each tag is called a "pill." I looked up what other pill boxes do for this case. The Salesforce Design System just truncates text with an ellipsis instead of wrapping to the next line. This is what Kelson is describing in his code example, and what I recommend too.

![image](https://user-images.githubusercontent.com/1915775/112182946-22e9b000-8bd4-11eb-8bfe-eccf3bcb6725.png)

@rtwell @jenniferlee-dsva what are your thoughts on this?

**Comment by rtwell** [comment]
ok let's adjust the design spec—i didn't understand I was introducing something problematic. I think with a couple small visual tweaks, we can get to a solid place. here's the updated spec and a few notes:

1. decrease the line height of the type (not the height of the tag-shape) so if/when type has to run onto two or more lines, it minimized the height. 
2. ensure the spacing between the tags is always equal both vertically and horizontally. i've used 12 px (1.5 spacing units) in sketch but we can adjust as needed
3. adjust horizontal rules above and bellow the tags section to follow the margins of the rest of the page

![image](https://user-images.githubusercontent.com/12564977/112196795-c4c3c980-8be1-11eb-968b-7ab4de2b32bd.png)

**Comment by kelsonic** [comment]
@ncksllvn Would you like me to pick up the remaining work here since you'll be helping CMS? 🙂

**Comment by ncksllvn** [comment]
Sounds good @kelsonic , appreciate it

**Comment by ncksllvn** [comment]
(@kelsonic this was the ticket with the changes to the tag display)

**Comment by ncksllvn** [comment]
@brianalloyd optionally we can capture @rtwell's [feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16623#issuecomment-805121660) into a ticket for this sprint. The work I did here was actually under-the-hood mostly (just feeding the data for "non-beneficiary audiences" into the existing template) and didn't entail updates to the tag presentation. So we could possibly chunk out a separate ticket `[Bug] Tags component whitespace issues` if we want to groom this ticket a bit.

**Comment by brianalloyd** [comment]
Thanks for the follow up @ncksllvn makes sense to break out the styling elements into a separate ticket.  I'll do that now and connect tickets for context.

**Comment by ncksllvn** [comment]
Thank you @brianalloyd !

**Comment by brianalloyd** [comment]
@jenniferlee-dsva going to close out this ticket based on your validation of the tags work @ncksllvn completed.  Created a new ticket to tackle the styling elements as specified by yourself and @rtwell.  Connected both tickets for traceability, Thanks.
