### ISSUE TITLE
Drafting a design doc for a new forms library

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16622]
## Task
Write the design document for building a new forms library.

---
## Design Doc Breakdown
Categories in the design doc template:
- [x] Objective
- [x] Background
  - [x] Problems
- [x] High-level design
  - [x] Modularity
    - [x] Explain: Only import the parts that you need
    - [x] Define the required parts
  - [x] Helpers
- [ ] Specifics (see below)
- [x] Code location
- [x] Documentation
- [ ] Testing plan
- [x] Logging
- [ ] Debugging
- [ ] Caveats
- [x] Security concerns
- [x] Privacy concerns
- [ ] Work estimates
- [ ] Open questions and risks
- [ ] Alternatives
- [ ] Future work

### Specifics
This section is quite meaty, so drilling down deeper, topics in this section include:
- [ ] Modules
  - [x] State management
  - [x] Routing
    - [x] Components
      - [x] Usage
      - [x] Internal architecture
    - [x] Functionality: Array routes
  - [x] Page builder
  - [ ] Save in progress
    - [ ] Data migrations and form versioning
- [ ] Helpers
  - [ ] Validation
  - [ ] Review page builder
  - [ ] Submission validation

**Comment by cvalarida** [comment]
I started writing a design doc in [this branch](https://github.com/department-of-veterans-affairs/va.gov-team/tree/forms-library-design-doc-cv). It's not yet ready for a PR, but I'm pausing work on this for now.
