### ISSUE TITLE
Does Central Mail Have External Monitoring in Place?

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16621]
## Description
It's common practice for applications relying on external systems to be wrapped in `<DowntimeNotification />` to alert users when they may experience incoming down time or service outage. Chapter 36 needs to be wrapped in this component so users are alerted to upcoming service outage.

## Considerations
- Central Mail needs to be added to [this config file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/DowntimeNotification/config/externalServices.js)
- devops repo already has an entry for Central Mail [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L195), but not one under `maintenance` [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L273).
- Might need to create a Pager Duty token for Central Mail to be added to the maintenance list in the link above. 

## Tasks
- [ ] Ask in #devops about whether they can help us with this
- [ ] Add Central Mail to downtime notification config
- [ ] Wrap Chapter 36 in `<DowntimeNotification />`

## Acceptance Criteria
- [ ] A path forward has been established for downtime notifications
