### ISSUE TITLE
Discovery: Create a Web Component pilot of the component library

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16624]
## Issue Description
Do discover on a Web Component pilot of the component library 

---
## Tasks
- [ ] Set up web components in Storybook 
- [ ] Use a web component in static HTML
- [ ] Use a web component in REACT

## Acceptance Criteria
- [ ] Make a recommendation 
- [ ] Define how difficult this would be / LOE 

---

**Comment by bkjohnson** [comment]
The discovery is complete, and we will be writing a design document before any more Web Component development will be done. [This branch](https://github.com/department-of-veterans-affairs/component-library/tree/wc-pilot) has the Web Component code, complete with some Storybook integration.

<details>
  <summary>Web Component in plain HTML</summary>

```diff
diff --git a/src/site/includes/footer.html b/src/site/includes/footer.html
index a75324e8a6..0a1d460109 100644
--- a/src/site/includes/footer.html
+++ b/src/site/includes/footer.html
@@ -1,5 +1,6 @@
 <div id="announcement-root"></div>
 <footer class="footer" role="contentinfo">
+  <my-component first="Brooks" last="Johnson"></my-component>
   <div id="footerNav"></div> <!-- let's try this React thing -->
 </footer>
 ```
 
   ![image](https://user-images.githubusercontent.com/2008881/104493216-9b574380-5589-11eb-97da-7813f07b13ae.png)

</details>


<details>
  
  <summary>Web Component in React code</summary>
  
```diff
diff --git a/src/applications/facility-locator/containers/FacilityLocatorApp.jsx b/src/applications/facility-locator/containers/FacilityLocatorApp.jsx
index d041f27c0f..28c1371215 100644
--- a/src/applications/facility-locator/containers/FacilityLocatorApp.jsx
+++ b/src/applications/facility-locator/containers/FacilityLocatorApp.jsx
@@ -65,6 +65,7 @@ class FacilityLocatorApp extends React.Component {
 
     return (
       <div>
+        <my-component first="Brooks" last="Johnson" />
         <Breadcrumbs selectedFacility={selectedResult}>
           {this.renderBreadcrumbs(location, selectedResult)}
         </Breadcrumbs>
```
  
![image](https://user-images.githubusercontent.com/2008881/104493638-2e907900-558a-11eb-8407-c902d3e8733d.png)

</details>

---

Setting up the Web Component dependnecy (called `wc-pilot`) to be used:

```diff
diff --git a/src/platform/site-wide/index.js b/src/platform/site-wide/index.js
index ba39b0e14a..326ef6b409 100644
--- a/src/platform/site-wide/index.js
+++ b/src/platform/site-wide/index.js
@@ -18,6 +18,10 @@ import addFocusBehaviorToCrisisLineModal from './accessible-VCL-modal';
 
 import '@department-of-veterans-affairs/formation/dist/formation';
 
+import { defineCustomElements } from 'wc-pilot/loader';
+
+defineCustomElements();
+
 /**
  * Start up the site-wide components that live on every page, like
  * the login widget, the header menus, and the feedback widget.
```
