### ISSUE TITLE
Review Instances (RIs) - "502 Bad Gateway" error due to inability to pull drupal cache 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16637]
## Issue Description
_Fetch to get content is failing if it is trying to get content from prod.cms.va.gov, resulting in errors when trying to access RIs_

---
## Tasks
- [ ] _Determine whether or not there is a suitable workaround_
- [ ] _If there is a suitable workaround, determine level of effort and weigh that against the fact that a future initiative will be to improve this solution for (see parent epic for more details on additional stories)_
- [ ] _Depending on the outcome of the tasks above, implement solution that resolves this error and experience for users of RIs_ 

## Acceptance Criteria
- [ ] _Drupal web cache will pull successfully to RIs_
- [ ] _Users will not receive in this error when trying to access RIs_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Some additional notes gathered from Slack: 

From @tskinn in [this slack thread:](https://dsva.slack.com/archives/CBU0KDSB1/p1601316789144500?thread_ts=1601048761.082900&cid=CBU0KDSB1)
---
From what I can tell this is happening:
1. vets-website source is pulled and docker image is built
2. this script is run as the entry point https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/review-entrypoint.sh#L5
3. npm run fetch-drupal-cache actually fails because there is no cached content matching the name generated by this function https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/utilities-drupal.js#L21-L28
4. during this step npm run build -- --buildtype localhost --api='${API_URL}' --host='${WEB_HOST}' --port='${WEB_PORT}' the build doesn't seen any content so it attempts to pull content from drupal as if it was running on a developers machine. (it tries to pull content from prod cms through the socks proxy) This is the prominent error that is distracting from the more subtle error of the previous step. (failed to pull cached content)

---
[This script ](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/review-entrypoint.sh)runs on review instances to pull the drupal-cache: 
`#!/bin/sh
set -e
yarn install --production=false
npm run fetch-drupal-cache
npm run build -- --buildtype localhost --api='${API_URL}' --host='${WEB_HOST}' --port='${WEB_PORT}'
npm run heroku-serve -- build/localhost -p 3001`

**Comment by jhouse-solvd** [comment]
This issue - shared by @mpelzsherman - is potentially related in its nature, though I can't determine if it's related to the actual cause. Will consider in discussions with platform engineering teams to determine its relevance to this issue. 

[Update build script to use S3 cache for CMS DEV/STAGING more reliably OR PROD](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16220)

**Comment by drorva** [comment]
@jhouse-solvd the CMS export team as well as the people involved with the build are very familiar with this process. 
@meganhkelley  can we get someone on the FE team to help trouble shoot and help figure out who owns this.

This is high priority since it's blocking VFS teams.
Related: #16620
cc: @f1337

**Comment by meganhkelley** [comment]
@jhouse-solvd @drorva is this a feature of review instances that was working previously and has now stopped working? Or is this a request for a new feature? 

Also, is this team unable to use feature toggles instead in this case?

**Comment by drorva** [comment]
Yes, this was working.
It looks like #16220 might be the root cause.
We should figure out what changed in the build that this started failing in the last couple of weeks.

**Comment by mpelzsherman** [comment]
FYI, I just had a [build](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/handle_empty_fieldDate/1/pipeline/98) fail (again) due to a CMS system update in progress.

Note that it is trying to pull content from an AWS-hosted instance of Drupal, NOT from prod. Is there any reason not to ALWAYS pull from prod?

```
[2020-11-30T19:14:09.368Z] $ node --max-old-space-size=8192 script/build-content.js --buildtype=vagovstaging --asset-source=local --drupal-address=http://internal-dsva-vagov-staging-cms-1188006.us-gov-west-1.elb.amazonaws.com --pull-drupal

[2020-11-30T19:14:09.368Z] Pulling feature flags from Drupal...

[2020-11-30T19:14:09.368Z] /application/src/site/stages/build/plugins/download-assets.js:14

[2020-11-30T19:14:09.368Z]   throw up;

[2020-11-30T19:14:09.368Z]   ^

...
[2020-11-30T19:14:09.368Z]   <p><strong>System update in progress</strong><br><br>Sit tight! The site will appear when the update is complete. <br>Updates generally take up to 15 minutes.</p>
```

**Comment by theodur** [comment]
Since it seems like the problem may be caused by using the `dev` and `staging` environments for Drupal content, I will update all builds to only use the prod environment for Drupal content. This is the [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15118) I'll be testing on. I Hope to verify whether this makes a change or not by the end of the day.

**Comment by theodur** [comment]
After digging deeper into the "502 Bad Gateway" error, it seems as this may not be caused by the content build, but rather an error in Jenkins.

In the [Jenkins pipeline](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/update-drupal-address/3/pipeline/262) of my PR, the "Triggered Builds" part of the "Review" phase is failing. When I looked into the error of the [review instance deploy](http://jenkins.vfs.va.gov/blue/organizations/jenkins/deploys%2Fvets-review-instance-deploy/detail/vets-review-instance-deploy/34360/pipeline) in Jenkins I am seeing:

```
[2020-12-01T00:07:58.958Z] using credential va-vfs-bot
[2020-12-01T00:07:58.971Z] Cloning the remote Git repository
[2020-12-01T00:07:58.971Z] Cloning repository https://github.com/department-of-veterans-affairs/devops.git
[2020-12-01T00:08:01.939Z] ERROR: Failed to clean the workspace
[2020-12-01T00:08:01.939Z] jenkins.util.io.CompositeIOException: Unable to delete '/var/lib/jenkins/works
```
which seems to be a problem with cloning the `devops` repo.  

The Jenkins step goes on to repeat the following output to the log:
```
[2020-12-01T00:08:08.227Z] 	Suppressed: jenkins.util.io.CompositeIOException: Unable to remove directory /var/lib/jenkins/workspace/deploys/vets-review-instance-deploy/ansible with directory contents: [/var/lib/jenkins/workspace/deploys/vets-review-instance-deploy/ansible/filter_plugins, /var/lib/jenkins/workspace/deploys/vets-review-instance-deploy/ansible/.venv, /var/lib/jenkins/workspace/deploys/vets-review-instance-deploy/ansible/plugins]

[2020-12-01T00:08:08.227Z] 		at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:250)

[2020-12-01T00:08:08.227Z] 		at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:205)

[2020-12-01T00:08:08.227Z] 		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:216)

[2020-12-01T00:08:08.227Z] 		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)

[2020-12-01T00:08:08.227Z] 		at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:87)

[2020-12-01T00:08:08.227Z] 		... 14 more
```
The errors above don't seem to be related to the content as it isn't reaching the step to build the content.

**Comment by jbritt1** [comment]
@theodur, the issue you mentioned above has recently been resolved. We are now back to the original "503 Bad Gateway" issue.

**Comment by jbritt1** [comment]
Linking for awareness / consolidation: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16734

**Comment by theodur** [comment]
The issue seems to have been caused by [dynamic sidenav menus](https://github.com/department-of-veterans-affairs/vets-website/pull/14854). Previously the sidenav menus were static, allowing for them to be pulled in from cache without the need to run a GraphQL query. Once sidenav menus were updated to be dynamic, a query needed to be ran to retrieve the sidenav, which requires access to the CMS, and review instances do not have access to the CMS. This in turn was causing review instances to constantly restart.

The dynamic sidenav [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14854) has been reverted and merged into `master` of the `vets-website` repo [here](https://github.com/department-of-veterans-affairs/vets-website/pull/15141).

We will need to wait for the next successful build in order for cache to be generated properly, as it is generated [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L333). Also all current PRs will have to pull in the changes in `master` to get review instances working after the cache has been generated.

I will verify that review instances work again after the cache has been generated.

**Comment by jbritt1** [comment]
Ongoing Slack thread for tracking: https://dsva.slack.com/archives/CBU0KDSB1/p1605557619162400

**Comment by drorva** [comment]
Based on feedback from several folks on the above thread, it looks like this issue is resolved. 
We'll go ahead and wait 1-2 days to get more confirmations and then close this ticket.

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1606956876455200?thread_ts=1605557619.162400&cid=CBU0KDSB1

**Comment by drorva** [comment]
Confirmed by @mpelzsherman and Paul Short that this works.

**Comment by mchelen-gov** [comment]
> The issue seems to have been caused by [dynamic sidenav menus](https://github.com/department-of-veterans-affairs/vets-website/pull/14854). Previously the sidenav menus were static, allowing for them to be pulled in from cache without the need to run a GraphQL query. Once sidenav menus were updated to be dynamic, a query needed to be ran to retrieve the sidenav, which requires access to the CMS, and review instances do not have access to the CMS. This in turn was causing review instances to constantly restart.
> 
> The dynamic sidenav [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14854) has been reverted and merged into `master` of the `vets-website` repo [here](https://github.com/department-of-veterans-affairs/vets-website/pull/15141).
> 
> We will need to wait for the next successful build in order for cache to be generated properly, as it is generated [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L333). Also all current PRs will have to pull in the changes in `master` to get review instances working after the cache has been generated.
> 
> I will verify that review instances work again after the cache has been generated.

@theodur Good catch on finding the PR that broke `fetch-drupal-cache` script. This should be added to CI tests: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17093

Also for context: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16401
