### ISSUE TITLE
Documentation - Update internal tools document so that teams know to be added to a GitHub group for DevOps repo access

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16631]
## Issue Description
_This is one of those parts of onboarding that could use further clarification. The internal tools document calls out a file ssh/config in the devops repo, but this will 404 if one does not have access to the repo._

Related to this support request: https://github.com/department-of-veterans-affairs/vsp-support/issues/36
---
## Tasks
- [x] _Update internal tools documentation_

## Acceptance Criteria
- [x] _Updated documentation added to repo._
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
