### ISSUE TITLE
Consolidate Analytics product ownership

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16636]
## Issue Description
We need to consolidate our analytics products under a shared account so that:
- VA.gov's data is not owned by a single person, which can be inaccessible when that person is out
- The team can more easily coordinate data tasks by removing the bottleneck of individual ownership of datasets, dashboards, and charts
- VA.gov's usability data is more secure, eliminating single points of failure
- Our products are more visibly owned by the team rather than a single person, which can help with customer trust and design when dashboards are exported
- We increase security so that we don't need to share individual account information with one another when we work on tasks

---
## Tasks
- [x] All Analytics team members have access to the new Analytics Google group & can see incoming emails from the Google group
- [x] Reassign all dashboards, charts, and datasets in Domo to the Google group
- [ ] Assign admin access in GA to the Google group
- [ ] Assign admin access in GTM to the Google group
- [ ] Assign admin access in BigQuery to the Google group

## Acceptance Criteria
- [ ] VSP Analytics & Insights team members can access all of the data, security, and configs within Domo and all of our Google suite products (BigQuery, Google Analytics, GTM, etc.)
- [ ] All of the analytics products' ownership (datasets, dashboards, etc.) have been switched to the Analytics Google Group
- [ ] Stretch: Our analytics products work under the VA.gov domain

**Comment by joanneesteban** [comment]
Next Task:
Check if you received an email from the VSP Analytics & Insights Oddball Gmail.
- [ ] @bsmartin-ep 
- [ ] @bmcgrady-ep 
- [ ] @JasonTheBearded 
- [ ] @jonwehausen

**Comment by joanneesteban** [comment]
### Next Steps

- [ ] Add Jason, Ben, & Brian. 
- [ ] Check team's access
- [ ] Create Domo account for Google Group

**Comment by joanneesteban** [comment]
### Next next steps
Domo ownership
- [ ] Transfer all datasets 
- [ ] Transfer all cards
- [ ] Transfer all pages

**Comment by joanneesteban** [comment]
### Final Steps

- [ ] Add to GA
- [ ] Add to GTM
- [ ] Add to GCP
