### ISSUE TITLE
VAOS Issue Contact Center Article Creation

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#16647]
## Issue Description
We observed during a recent feedback session with a Veteran that he received in accurate information when he called HRC number (877-470-5947).

We did training and updates in March/April with HRC, but it's probably worth re-reviewing now that all scheduling is pointing to VAOS on VA.gov.

Specific feedback:

- when veteran was experiencing what he thought was a problem with the app not displaying his facilities, he called the HRC number

- the veteran was directed to MHV profile to review their 'preferred facility' option 

- MHV profile settings do not translate to VA.gov

- when that didn't work, the Veteran was transferred to another MHV associated but the transfer resulted in the veteran having to leave a voicemail

- he still hadn't received a call back to his issue when we spoke

---
## Tasks
- [x]  Review issue experienced by veteran. 
- [x] Create article/script for how to handle identified issue.
- [ ] Review new content with VAOS team
- [ ] Share with HRC/VEO Tier 1 Contact Center

## Acceptance Criteria
- [ ] we need to sync with @clantosswett on HRC scripts + potentially schedule another HRC training of VAOS
- [ ]  ensure that HRC reps understand the difference between MHV and VAOS - how they differ and where they connect
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
@clantosswett Are you able to provide the training and update materials that were shared/presented to HRC back in April/May for our review?  Also, is there supposed to be 'back end' communication between those two (MHV profile and VA.gov profile) so that changes in either transfer over to the other profile?  If not, is this something that would be beneficial to veterans?  

@starlow00 form our conversation earlier today, below are the steps that I provide to veterans when they are having issues or need to know how to set their facility locator.  

Please feel free to make any modifications as you see fit in order to be cohesive with the other messaging that you have developed.  Although it is a separate issue, we discussed using this information to create possible IVR messaging for this issue too.  I will update the ticket with this information and follow up with Chante on those items that I mentioned.

_Thank you for your service._

_The facility locator tool should automatically present a list of VA locations based off of your address in the system.  You can find instructions on how to update your address on VA.gov at [(https://www.va.gov/change-address/)]. This website also provides information on the other ways to update your address for your different benefits._

Once you have completed that task, please follow the steps below in order to update your VA facility location to that of your choosing.

- Login using MyHealtheVet
- Select appointments
         - Click on VA Facility Locator
-  This will redirect you to VA.gov
         - Select continue to VA.gov if you receive a pop up
-  Find VA locations
         - You can then enter your city, state, postal code
- From the drop down menu to select facility type
         - Choose your facility type
- Click search
         - All options will populate

- Select your preferred location_

**Comment by starlow00** [comment]
@Kimberley2019 Here's a draft that includes Call Center rep-facing instructions, Veteran-facing IVR, and Veteran-facing email language. Questions, let me know!
[16647 VAOS  IVR_starlow_ 120320.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5661987/16647.VAOS.IVR_starlow_.120320.docx)

**Comment by Kimberley2019** [comment]
@starlow00 the edits that you made to my template are great.  Thank you for doing that, I know my message probably wasn't the best.

@clantosswett were you able to find out any information to the questions that I posed?  Also, I have sent this ticket to the VAOS team for review and suggestions.

**Comment by Kimberley2019** [comment]
@starlow00 the article that you created will be useful.  Unfortunately, I misunderstood the issue.  I have asked for more clarification in the other ticket concerning VAOS.

**Comment by jwoodman5** [comment]
This ticket is being addressed in [#16612](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16612) so I am closing it.
