### ISSUE TITLE
Root Cause Analysis of `Flaky` Cypress Tests

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#16645]
## Issue Description
VFS team members are experiencing issues with Cypress tests preventing deploys to staging/prod; however, when the Cypress test is rerun without any other changes the result of the test is different.

---
## Tasks
- [x] Create a list of incidences of flaky Cypress test results
- [x] Analyze each incidence of `flakiness` for its root cause
- [x] Perform meta-analysis of each incident's cause
- [x] Describe a solution that resolves flaky Cypress tests

## Acceptance Criteria
- [x] VSP has an understanding of the root cause of Cypress test flakiness
- [x] VSP has a proposed solution for resolving the cause of the flaky Cypress tests

**Comment by holdenhinkle** [comment]
Google doc with notes about flakey Cypress tests (and Cypress tests that continue to fail) - https://docs.google.com/spreadsheets/d/1NAhszocK2vnxZCLGwc66BnNVcNo__YHM8eXvA4F_ZIQ/edit?usp=sharing

**Comment by holdenhinkle** [comment]
Thread about this the following error - https://github.com/cypress-io/cypress/issues/1305

```
Running:  applications/disability-benefits/996/tests/hlr.cypress.spec.js                (10 of 82)

✔ Webpack  Compiled successfully in 4.82s
(node:30772) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by holdenhinkle** [comment]
## Flakiness when running `/application/gi` Cypress tests locally in headless mode

Regarding the following tests which **ALMOST ALWAYS FAIL** when running:

1. the full Cypress test suite in headless mode using the command `yarn cy:run`
2. only the tests in the `/application/gi` directory using the command `yarn cy:run --spec "src/applications/gi/tests/e2e/*"`:

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  │ ✖  applications/gi/tests/e2e/00-requir      00:05        1        -        1        -        - │
  │    ed.cypress.spec.js                                                                          │
  │ ✖  applications/gi/tests/e2e/03-vet-te      00:03        1        -        1        -        - │
  │    c.cypress.spec.js                                                                           │
  │ ✖  applications/gi/tests/e2e/04-dea.cy      00:04        1        -        1        -        - │
  │    press.spec.js                                                                               │
  │ ✖  applications/gi/tests/e2e/05-ojt.cy      00:05        1        -        1        -        - │
  │    press.spec.js                                                                               │
  │ ✖  applications/gi/tests/e2e/07-gibct-      00:05        1        -        1        -        - │
  │    mobile.cypress.spec.js                                                                      │
```

The errors logged are not assertion errors, but instead are errors with either the `cypress-axe` or `axe-core` modules (it's very difficult to read the compressed/minified compiled javascript. The error given is:

```
TypeError: Cannot read property 'run' of undefined
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/platform/testing/e2e/cypress/support/index.js:25257:442975)
```

The `undefined` object referenced is `axe`:

```
return a.axe.run(t||a.document,u).then(function(e){var t=e.violations;
```

However, the tests in `/application/gi` **ALWAYS PASS** when run:

1. individually using the following commands:
  - `yarn cy:run --spec "src/applications/gi/tests/e2e/00-required.cypress.spec.js"`
  - `yarn cy:run --spec "src/applications/gi/tests/e2e/03-vet-tec.cypress.spec.js"`
  - `yarn cy:run --spec "src/applications/gi/tests/e2e/04-dea.cypress.spec.js"`
  - `yarn cy:run --spec "src/applications/gi/tests/e2e/05-ojt.cypress.spec.js"`
  - `yarn cy:run --spec "src/applications/gi/tests/e2e/07-gibct-mobile.cypress.spec.js"`
2. when run individually in the visual test running using the command `yarn cy:open`
3. when the full test suite is run using chrome instead of electron using the command `yarn cy:run --browser chrome`

Additionally, these tests pass in CI.

### Analysis
When writing Cypress tests, as long as they pass in the visual test runner or when run individually in the headless mode, they will probably pass in CI like the tests in `/application/gi`.

If the tests pass in the visual test runner or when run individually in the headless mode but fail when the entire test suite is run or when more than one test in an application directory is run, the failure should be ignored.

**Comment by holdenhinkle** [comment]
@pjhill 's comments:

- headless vs interactive -- need to explore cypress' documented differences for execution
- does axe-core library version affect the error?

**Comment by holdenhinkle** [comment]
Enable Cypress retries to reduce flakiness - https://docs.cypress.io/guides/guides/test-retries.html

_End-to-end (E2E) tests excel at testing complex systems. However, there are still behaviors that are hard to verify and make tests flaky (i.e., unreliable) and fail sometimes due to unpredictable conditions (eg., temporary outages in external dependencies, random network errors, etc.). Some other common race conditions that could result in unreliable tests include:

- Animations
- API calls
- Test server / database availability
- Resource dependencies availability
- Network issues

With test retries, Cypress is able to retry failed tests to help reduce test flakiness and continuous integration (CI) build failures. By doing so, this will save your team valuable time and resources so you can focus on what matters most to you._

**Comment by holdenhinkle** [comment]
## Failing tests in `src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js`

### Fail #1

Regarding the following test:

```
  it('should render in mobile layouts and tabs actions work', () => {
    cy.visit('/find-locations');
    cy.injectAxe();

    // iPhone X
    cy.viewport(400, 812);
    cy.checkSearch();

    // iPhone 6/7/8 plus
    cy.viewport(414, 736);
    cy.checkSearch();

    // Pixel 2
    cy.viewport(411, 731);
    cy.checkSearch();

    // Galaxy S5/Moto
    cy.viewport(360, 640);
    cy.checkSearch();
  });
```

The second call to `cy.checkSearch();` results in an error:

```
AssertionError: Timed out retrying: expected '[ <span.i-pin-card-map>, 3 more... ]' to be 'visible'

This element `[ <span.i-pin-card-map>, 3 more... ]` is not visible because its content is being clipped by one of its parent elements, which has a CSS property of overflow: `hidden`, `scroll` or `auto`
    at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js:628:29)
```

The error occurs here in `checkSearch()`:

```
  // Pin
  cy.get('.i-pin-card-map')
    .should('be.visible') // error
    .contains('A');
```

Please note: `checkSearch()` immediately calls `cy.axeCheck()`.

#### Solution
`cy.injectAxe()` is a method provided by the `cypress-axe` module. Regarding [`cy.injectAxe()`](https://github.com/component-driven/cypress-axe#cyinjectaxe):

_This will inject the `axe-core` runtime into the page under test. You must run this after a call to `cy.visit()` and before you run the `checkA11y` command._

`cy.checkA11y()` is called by by `cy.axeCheck()` so you must call `cy.visit()` then `cy. injectAxe()` each time before calling `checkSearch()` (which, again, immediately called `cy.axeCheck()`). 

Updated code:

```
  it('should render in mobile layouts and tabs actions work', () => {
    cy.visit('/find-locations');
    cy.injectAxe();

    // After running axeCheck() you need to visit the page then call injectAxe() again.

    // iPhone X
    cy.viewport(400, 812);
    cy.checkSearch();

    // iPhone 6/7/8 plus
    cy.visit('/find-locations');
    cy.injectAxe();
    cy.viewport(414, 736);
    cy.checkSearch();

    // Pixel 2
    cy.visit('/find-locations');
    cy.injectAxe();
    cy.viewport(411, 731);
    cy.checkSearch();

    // Galaxy S5/Moto
    cy.visit('/find-locations');
    cy.injectAxe();
    cy.viewport(360, 640);
    cy.checkSearch();
  });
```

#### Better Solution, using new Cypress `VA Top Mobile Viewports` environment variable:

```
  it('should render in mobile layouts and tabs actions work', () => {
    Cypress.env().vaTopMobileViewports.forEach((viewportData) => {
      const {
        list,
        rank,
        devicesWithViewport,
        percentTraffic,
        percentTrafficPeriod,
        viewportPreset,
      } = viewportData;

      cy.visit('/find-locations');
      cy.injectAxe();
      cy.viewportPreset(viewportPreset);
      cy.log(`Viewport list: ${list}`);
      cy.log(`Viewport rank: ${rank}`);
      cy.log(`Devices with viewport: ${devicesWithViewport}`);
      cy.log(
        `% traffic for the month of ${percentTrafficPeriod}: ${percentTraffic}%`
      );
      cy.checkSearch();
    });
  });
```

### Fail #2

Regarding the following test:

```
  it('should render the appropriate elements at each breakpoint', () => {
    cy.visit('/find-locations');
    cy.injectAxe();

    // desktop - large
    cy.viewport(1008, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(48, 2);
    });
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // desktop - small
    cy.viewport(1007, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(899, 2);
    });
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // tablet
    cy.viewport(768, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(660, 2);
    });
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // mobile
    cy.viewport(481, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(397, 2);
    });
    cy.get('.desktop-map-container').should('not.exist');
    cy.get('.react-tabs').should('exist');
  });
```

The width assertions (`expect($element.width()`) cause the test to fail because the number representing the width that's passed into` closeTo()` is incorrect.

### Solution 1

Remove the width assertions:

```
  it('should render the appropriate elements at each breakpoint', () => {
    cy.visit('/find-locations');
    cy.injectAxe();

    // desktop - large
    cy.viewport(1008, 1000);
    cy.axeCheck();
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // desktop - small
    cy.viewport(1007, 1000);
    cy.axeCheck();
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // tablet
    cy.viewport(768, 1000);
    cy.axeCheck();
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // mobile
    cy.viewport(481, 1000);
    cy.axeCheck();
    cy.get('.desktop-map-container').should('not.exist');
    cy.get('.react-tabs').should('exist');
  });
```

### Solution 2

Update the widths:

```
  it('should render the appropriate elements at each breakpoint', () => {
    cy.visit('/find-locations');
    cy.injectAxe();

    // desktop - large
    cy.viewport(1008, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(48, 2);
    });
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // desktop - small
    cy.viewport(1007, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(907, 2);
    });
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // tablet
    cy.viewport(768, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(675, 2);
    });
    cy.get('.desktop-map-container').should('exist');
    cy.get('.react-tabs').should('not.exist');

    // mobile
    cy.viewport(481, 1000);
    cy.axeCheck();
    cy.get('#facility-search').then($element => {
      expect($element.width()).closeTo(412, 2);
    });
    cy.get('.desktop-map-container').should('not.exist');
    cy.get('.react-tabs').should('exist');
  });
```

**Comment by holdenhinkle** [comment]
## Cypress tests that have failed in CI recently

Appear to have been resolved:
- `src/applications/healthcare/list/tests/e2e/02.bread.crumbs.cypress.spec.js`
- `src/applications/find-forms/tests/e2e/00-required.cypress.spec.js`
- `src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js`

Might have been resolved (this test is flaky locally):
- `src/applications/personalization/profile/tests/e2e/address-validation/bad-unit.cypress.spec.js`

This test gives the following error:

```
1) Personal and contact information
       when entering an address with a bad unit
         should successfully update on Desktop:
     AssertionError: 1 accessibility violation was detected: expected 1 to equal 0
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/platform/testing/e2e/cypress/support/index.js:25257:443712)
```

**Comment by holdenhinkle** [comment]
PR for refactoring Cypress tests that either fail in CI or fail locally - https://github.com/department-of-veterans-affairs/vets-website/compare/16645_refactor_flakey_cypress_tests

Commands to run these locally, one at a time in headless mode:
- ` yarn cy:run --spec "src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js"`
- `yarn cy:run --spec "src/applications/gi/tests/e2e/00-required.cypress.spec.js"`
- `yarn cy:run --spec "src/applications/gi/tests/e2e/03-vet-tec.cypress.spec.js"`
- `yarn cy:run --spec "src/applications/gi/tests/e2e/04-dea.cypress.spec.js"`
- `yarn cy:run --spec "src/applications/gi/tests/e2e/05-ojt.cypress.spec.js"`
- `yarn cy:run --spec "src/applications/gi/tests/e2e/07-gibct-mobile.cypress.spec.js"`

Command to run the `/applications/gi/` Cypress tests as a set:
- `yarn cy:run --spec "src/applications/gi/tests/e2e/*"`

The following tests are still flaky and are still being analyzed:
- `yarn cy:run --spec "src/applications/gi/tests/e2e/04-dea.cypress.spec.js"`
- `yarn cy:run --spec "src/applications/gi/tests/e2e/05-ojt.cypress.spec.js"`

### The reason some of these tests were failing:
The issue was with the `cypress-axe` module. Every time you load a new page by calling `cy.visit()`, `cy.wait(@alias)` (where `@alias` references a route), or `cy.click()` (when you click on something like a search button that loads a new page), you have to load the `axe-core` runtime into the page by calling `cy.inject()`.

We were getting this error because `axe` was not loaded into the page:

```
TypeError: Cannot read property 'run' of undefined
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/platform/testing/e2e/cypress/support/index.js:25257
```

The `undefined` object was `axe`.

**Comment by ddzz** [comment]
This test has been failing in CI and has been disabled: https://github.com/department-of-veterans-affairs/vets-website/pull/15472

**Comment by holdenhinkle** [comment]
## Notes regarding flaky Cypress test - https://github.com/department-of-veterans-affairs/vets-website/pull/15472

### Getting consistent failure from this test in CI #15472

File: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/tests/e2e/search.cypress.spec.js

Failing tests:
- finds community care pharmacies
- renders static map images on detail page

> I thought the issue might be that the test relies on API calls that are _not_mocked by Cypress. That doesn't appear to be the case for this particular test. However, the renders static map images on detail page and finds community care pharmacies tests can fail if un-mocked API calls (to mapbox, I think) fail. You can check this by disabling your computer's internet and running the test. This could result in random failures in CI.

**Comment by holdenhinkle** [comment]
Regarding test `src/applications/gi/tests/e2e/05-ojt.cypress.spec.js` @ddzz found that `cy.click({ waitForAnimations: true })` should be used instead of `cy.click()` when clicking on elements that are animated, like accordions. Otherwise an error can result from a race condition where Cypress tries to click on an element that hasn't yet rendered to the DOM. Thank you Darius!

**Comment by holdenhinkle** [comment]
Test that failed in CircleCI on 12/23/2020

`src/applications/facility-locator/tests/e2e/search.cypress.spec.js`

```
Facility search finds community care pharmacies - finds community care pharmacies
AssertionError: Timed out retrying: expected '<button#search-area-control>' not to be 'visible'
    at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/facility-locator/tests/e2e/search.cypress.spec.js:660:34)
```

**Comment by holdenhinkle** [comment]
# How to Prevent Flaky Cypress Tests

## `cy.click()` vs `cy.click({ waitForAnimations: true })`
`cy.click({ waitForAnimations: true })` should be used instead of `cy.click()` when Cypress clicks on an element that is animated, like an accordion. Otherwise, an error can result from a race condition where Cypress tries to click on an element that hasn't yet rendered to the DOM.

## `cy.injectAxe()` must be called before `cy.axeCheck()` every time a new page is loaded
Every time Cypress loads a new page by calling `cy.visit()`, `cy.wait(@alias)` (where `@alias` references a route), or `cy.click()` (when Cypress clicks on a element like a search button that loads a new page), the axe-core runtime must first be loaded into the page by calling `cy.inject()`.

The cypress-axe documentation explains:
> This will inject the axe-core runtime into the page under test. You must run this after a call to `cy.visit()` and before you run the `checkA11y` command.
> 
> You run this command with cy.injectAxe() either in your test, or in a beforeEach, as long as the visit comes first.

However, as mentioned, it appears that this also applies to other calls that load a new page like  `cy.wait(@alias)` or `cy.click()`.

**Comment by holdenhinkle** [comment]
Documentation for how to avoid/fix flaky Cypress tests - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-flaky-test-management.md

PR to fix flaky Cpyress tests - https://github.com/department-of-veterans-affairs/vets-website/pull/15488

**Comment by holdenhinkle** [comment]
# VSP has a proposed solution for resolving the cause of the flaky Cypress tests
- Enable test retries when we upgrade to Cypress 6.1 - https://docs.cypress.io/guides/guides/test-retries.html
- Follow the suggestions in the new [Cypress Flaky Test Management documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-flaky-test-management.md#call-cyinjectaxe-when-a-new-page-loads)
- Update [the new documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-flaky-test-management.md) as new sources of flakiness are discovered and fixed

**Comment by ddzz** [comment]
This test has been failing on CircleCI recently: `src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js`

**Comment by pjhill** [comment]
@ddzz -- Do you think it's worth investigating the failures in order to see if any of the previous techniques that result in "flakiness" are being used in the test spec? Is there a different cause for the "flakiness" that we need to account for in our documentation?

**Comment by ddzz** [comment]
This Facility Locator test is occasionally causing Cypress to hang indefinitely on Jenkins: https://github.com/department-of-veterans-affairs/vets-website/pull/15556

**Comment by mpelzsherman** [comment]
It seems to me that the CI environment must be responsible for a good portion of the flakiness, since the tests run consistently in our local dev environment. My hunch is that the builds we are using to test against are too unstable and/or too slow to handle the Cypress tests.

My understanding is we are running the Cypress tests against a temporary review environment, then we deploy the "real" review instances if the tests pass.

Have we considered deploying the "real" review instance, then running the Cypress tests against those instead?

**Comment by ddzz** [comment]
`src/applications/personalization/profile/tests/e2e/personal-and-contact-info/modals.cypress.spec.js` was failing occasionally due to a rendering race condition. Fixed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15725).

**Comment by pjhill** [comment]
Ok, I think the scope of this ticket has been completed. Any future efforts around flakiness will be worked under a new ticket.
