### ISSUE TITLE
Create github file listing all VBA stakeholders

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16642]
## Issue Description
We have a lot of stakeholder communications. We need a quick way to find the right business line and person to contact for reviews of new content, redirect notifications, etc. 

---
## Tasks
- [x] Create a new doc organized by business line that shows who the SMEs are. Use this spreadsheet:
[https://app.zenhub.com/files/133843125/022d637e-6118-408a-a87c-00bb645cab6f/download](https://app.zenhub.com/files/133843125/022d637e-6118-408a-a87c-00bb645cab6f/download)
- [x] Create doc here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content

## Acceptance Criteria
- [ ] List is visible in the content processes folder.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
