### ISSUE TITLE
[Bug] PII Removal from Facility Locator Event Tracking 

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#16643]
## Summary
If you go to [Find VA Locations](https://www.va.gov/find-locations), you'll see 3 fields available for you to enter data into. The data from those 3 fields has been collected for the past 2 months and sent to Google Analytics and BigQuery to help the FL team make product strategy decisions.

The problem is that some Veterans may enter a full address into the location field, and we can assume that sometimes that'll be their home address they're entering -- which makes the data from that field potential PII. See thread for more details.

## What happened?
- PII was discovered to be passed into our Facility Locator search event actions. We are passing in both 1) what the user inputs into the "City, state or postal code" search box, and 2) the location identifixcation that the Mapbox API returns, often a city, state and zip code
- October 11, 2020 - November 30 represents the full date range where this data was being collected: 
  > https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=17101&explorer-table.rowCount=2500 

## Acceptance Criteria
- [x] Variables collecting PII have been removed from Facility Locator Event Action to prevent future collection - `fl-search-results` 
- [ ] Add in `(not set)` to GTM params collected
- [ ] BigQuery Facility Locator views have been re-created without these variables included (#15000)
- [ ] Data has been removed from all inclusive Non-Prod and Production views within Google Analytics
- [ ] Data has been removed from BigQuery export schema datasets 
- [x] Post Mortem created

**Comment by jonwehausen** [comment]
### Remaining Steps
- Re-write query in GH issue #15000 to EXCLUDE `searched_query` and `mapbox_place_name`
- Save query results as external table for historical use
- Write a DML `DELETE` statement to remove all `fl-search-results` events up to this point in production and non-production
- Do a data deletion request for all events with `fl-eearch-results` event label

**Comment by joanneesteban** [comment]
Added post-mortem to AC.

**Comment by joanneesteban** [comment]
@JasonTheBearded adding you to this ticket for writing the SQL queries here.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

GTM workspace to get the `(not set)` in these.

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000400

@JasonTheBearded -

We are going to set a default value of `(not set)` for these dataLayer variables to help with splitting.  I think the lack of default value is causing the ` - `'s to run together in a way that makes splitting on ` - ` inconsistent.

Example (dummy data):

`Facility Locator - Search Results - urgent_care - - - true - 20 - 1 - COLONIAL PARK, AK - place - Colonial Park, Alaska, United States - 1.0017101916080497 - 2282`

becomes

`Facility Locator - Search Results - urgent_care - (not set) - (not set) - true - 20 - 1 - COLONIAL PARK, AK - place - Colonial Park, Alaska, United States - 1.0017101916080497 - 2282`

**Comment by joanneesteban** [comment]
[Reaching out to Identity](https://dsva.slack.com/archives/CSFV4QTKN/p1606752353187100) on if PII is actually being passed through. The data we're finding at the moment is facility locations, and need to do a more thorough audit.

**Comment by joeniquette** [comment]
Let's split the conversation. One for GTM and one for non-GTM.

For GTM, we have two items I'd like to get consensus on:  

1. The "PII" of their address being used with GTM; if we state within our privacy policy that we use GTM, it's not really an issue, normally. So item one of GTM, do we state we use GTM in the privacy policy/do we ask for consent to use it with their PII?
2. Is there some other PII exposure concern, such as, is the information not going over https? If it is, and the traffic is only within our systems and GTM, what is the concern outside of item 1 of GTM?

Non-GTM:
1. What are the other systems in question where the PII is passing through that we are concerned about?
2. Do other downstream systems other than GTM depend on this search function and the data within it?

**Comment by rroueche** [comment]
For GTM:

1. Our [privacy policy](https://www.va.gov/privacy-policy/) states the following:
![image](https://user-images.githubusercontent.com/8680732/100638899-8d63a100-3302-11eb-8927-020b91ec6553.png)

**Comment by jonwehausen** [comment]
Thanks @joeniquette and @rroueche -- Just took a solid read-thru of the privacy policy Rachel provided. 

For context, here are the details of what we were collecting that is of potential concern: 
- We collect the raw text input of what the user inputs into the "City, state or postal code" box
![image](https://user-images.githubusercontent.com/48527022/100642347-ad955f00-3306-11eb-99b5-ea5c13353f5c.png)
- We also collect the response that mapbox returns from their API that further classifies how mapbox interprets the query provided 
![image](https://user-images.githubusercontent.com/48527022/100642677-167cd700-3307-11eb-899f-46365752d111.png)

To answer your questions @joeniquette: 
1) I didn't see any explicit verbiage in there around PII and the use of Google Tag Manager. 
2) There are no other concerns of this data being in GTM, it's the downstream to GA we are concerned with. 

We are concerned Google Analytics would classify our collection of the search query from the user and the mapbox API classification as PII. While it's not conclusive a user inputs their personal home address into the search, it can be reasonable to expect a user may do so.

**Comment by joeniquette** [comment]
As I see it then you have two choices.

1. Add the collection of this information and its purpose to the privacy policy. Whats left is the concern around GA classifying this information as PII, if they do, what are the impacts?
2. If you do not have a justification to collect this information, ensure its ignored by GTM and GA to ensure the data is only being collected by our platforms for the specific use it was originally intended for.

**Comment by jonwehausen** [comment]
Thanks for this @joeniquette , 

Before we make a final call on next actionable steps here, could I walk thru the current implementation with you? 

**This verbiage seems most applicable to our current use case here** 

> _"VA.gov does not collect personal information from web users unless the personal information is provided by you. A Limited Privacy Policy will apply in each case where you may provide personal information to VA through our website."_

cc: @rroueche @joanneesteban

**Comment by jonwehausen** [comment]
@joanneesteban -- @joeniquette and I met regarding this implementation & reporting and have determined we should do 1 of the following, would like to get sign-off from @rroueche before proceeding on any further work here: 
1) Work to update the privacy policy for specific language around the use of this data, and/or create a limited privacy policy for the facility locator page, and keep our data structure as-is. 
2) Work to clean-up where this data is surfaced in GA & BigQuery and cleanse our GA collection of this data moving forward.

**Comment by jonwehausen** [comment]
@bsmartin-ep and @JasonTheBearded for your awareness

**Comment by rroueche** [comment]
My initial thoughts:

**Comment by rroueche** [comment]
Update:

**Comment by joanneesteban** [comment]
Adding @JasonTheBearded back in for data scrub.

**Comment by jonwehausen** [comment]
## Update
- We have published the adjustment to prevent the potential collection of addresses this point forward
- We will be QAing the script to update bigquery to remove address information cc: @JasonTheBearded @bsmartin-ep 
- Post-mortem has been started [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/12-1-2020-pii-facility-locator-postmortem.md), will fill in other fields throughout bug completion

**Comment by joeniquette** [comment]
@rroueche Considering the information from Google regarding PII with GA I agree with this approach. It does appear as though we can hash and salt the values (or encrypt) the information before it goes into and through GA, but I don't know that its worth the configuration. The struggle here is collecting enough information to help improve the Veterans experience without violating any policies and protecting the Veterans information. 

A more robust analysis of the options to collect this information is likely worth the effort to ensure we are able to properly identify trouble areas within our Geo Search. 

I would also add that having the ability as a Veteran to enter my exact address to ensure I get the closest facility to my home vs a state lookup is important. So if this means we need to find another way to collect this information for troubleshooting and analytical purposes, we should do it.

**Comment by rroueche** [comment]
Ok, @jonwehausen @joanneesteban and @JasonTheBearded , please proceed in this order then (basically a repeat of what I posted above):

1. remove the GTM code that is passing the address info in GA
2. scrub our current records of address info
3. set up time to work with the Facility Locator team to figure out what data would be both useful to them and safe for us to pass through to Google Analytics so we can re-do the GTM work

**Comment by jonwehausen** [comment]
### Question on Next Steps for GA
_Want to preface this comment by saying we certainly would like to get this data removed from GA, however we want to make the team aware of the impacts with each option we have available_

Currently, our options to remove the data specifically from GA are: 
1) **Do Nothing:** We maintain the Oct 11 - Nov 30 timeframe where this data was surfaced and eliminate any future ingestion moving forward (_have already published the GTM change for this_) 
2) **Complete View Deletion & Re-creation**: We delete & re-create all of the views where we have these events, starting with fresh views. We have this data historically exported in BQ, and would be a medium-to-high grade lift to complete. 
3) **GA Data Deletion Request**: [Data Deletion requests](https://support.google.com/analytics/answer/9450800?hl=en) are limited in that they delete every hit for a specific dimension (_in our case here, we would be interested in deleting the event action where the address is contained_). Using this approach would remove **ALL event actions for the time frame rather than solely facility locator events**. Once again, we have this data historically in BQ; would be a small lift to complete. 

**The major point of emphasis with performing options 2 or 3 is that Google Analytics Dashboards, Custom Reports, Segments _(anywhere the event action dimension is leveraged)_ will no longer work. In addition, apps like performance dashboard where the GA API is leveraged would break for this time frame** 

Per these impacts, please let us know what option you believe we should go with.

**Comment by jonwehausen** [comment]
cc: @rroueche and @joanneesteban for comment above

**Comment by joanneesteban** [comment]
Thanks for sharing this information on the impact, @jonwehausen 

Initially, it seems like we shouldn't be doing Option 1 (keep the addresses currently in GA).

Question for Option 3: does that mean **all** event actions _throughout GA_ would be deleted? As in, every VA.gov page's data would get affected? What would the work be involved between Options 2 & 3?

**Comment by jonwehausen** [comment]
Hi @joanneesteban , 

To answer your question on option 3 directly -- unfortunately yes. All hits of type event across all views would be replaced with a null event action for that time frame. 


## Tasks
Between Options 2 & 3, here's what I see as the task items for both non-prod, prod GA properties, and DOMO where applicable:

### **Option 2 - Complete view deletion & re-creation**
1) Perform a **COPY** of all of the views where these events were contained, here are the production property ones: 
`176188361` -- All Data View
`182764794`
`184317761`
`176154266`
`176878298`
`184624291` -- WBC Modernized
2) QA at least 1 full day of data to verify each of the copied views are consistent with their predecessors for general metrics like users, sessions, pageviews 
3) Turn on BigQuery export for the new All Data view 
4) QA at least 1 full day of BigQuery export completion 
5) _Optional but recommended_: Create share template links for custom reports and all custom segments and recreate in newly created views 
6) Update all DOMO datasets SQL queries to `SELECT ... FROM vsp-analytics-and-insights.NEW_VIEW_ID.ga_sessions_2020*` 
7) Once verified, **move old views with PII to trash can** and use the new views moving forward

### **Option 3 - Data Deletion Request**
1) Perform the steps for a data deletion request for "Event Action" between October 11 - November 30 
2) Verify pending end of grace period and confirmation email receipt event actions have been removed for the time frame

## **Impacts**

### Option 2 - Complete view deletion & re-creation
- Will erase any and all GA dashboards and custom reports in those views listed that teams are using (two of which are most used GA views)
- Will present a problem for DOMO datasets / dashboards where we need to do full historical scans with each execution
 
### Option 3 - Data Deletion Request
  - Will null-out all event actions in Google Analytics across views, whether facility locator specific or not for the time period
  - Will break existing Google Analytics dashboards for this time period where event actions are used (very common) 

cc: @rroueche @JasonTheBearded @bsmartin-ep @bmcgrady-ep for visibility

**Comment by rroueche** [comment]
I think I need a meeting to understand the implications. Could you put one together @jonwehausen and @joanneesteban and @JasonTheBearded ?

**Comment by joanneesteban** [comment]
Set up a meeting for tomorrow, Thursday 10:30-11am EST, @rroueche @jonwehausen @JasonTheBearded 

@jonwehausen could you share what you have for the post-mortem so far?

**Comment by jonwehausen** [comment]
Sure thing, comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16643#issuecomment-736694193) for postmortem link

cc: @joanneesteban @rroueche

**Comment by rroueche** [comment]
Some additional questions pursuant to my meeting w/the rest of DEPO:

- Is community care facility selection captured along with some of the address data?
- If we ask Google to remove the data...
  - Does that mean every VA.gov product would be missing that time period of data that we clear out?
  - Does that mean we wouldn't be able to monitor products while thing are being reconfigured?
  - Would the covid-19 dashboarding work be able to continue uninterrupted?

**Comment by bsmartin-ep** [comment]
@rroueche -

> Is community care facility selection captured along with some of the address data?

Yes - 'Facility type' is one of the fields we collect in the Event action

> Does that mean every VA.gov product would be missing that time period of data that we clear out?

From what we understand, Google removes all data for the "column" you request.  In this case, we believe they would remove the "Event Action" for every event in that time period.  Some products (especially newer implementations) use Event Action to bank data, so those would be greatly affected.  Other products use custom dimensions (and not the event action), so they would be less affected.

A lot of non-product events - like logins, scroll depth, etc - would also be wiped out.

> Does that mean we wouldn't be able to monitor products while thing are being reconfigured?

This is a bit of a gray area.  I think if we give Google a timeframe, we would be able to continue to monitor events outside that timeframe.  They would be using the new GTM implementation and shouldn't have any PII.

The other option (trashing and recreating the views) would probably lead to more downtime. 

> Would the covid-19 dashboarding work be able to continue uninterrupted?

I think the COVID dashboard is 100% pointing to BigQuery, so there would probably be complications but no major gaps in the data.

**Comment by rroueche** [comment]
Thanks @bsmartin-ep ! I added one more question there, sorry :) Appreciate these answers, thank you!

**Comment by bsmartin-ep** [comment]
@rroueche -

> Do we store the data as an address string? Or as lat+long? Both?

Just an address string.  Lat/Lng is used in the geocoding, but we don't save it.

**Comment by JasonTheBearded** [comment]
Non-Prod PII Scrub complete

**Comment by jonwehausen** [comment]
### Slack Thread
https://dsva.slack.com/archives/CKCRMLGAC/p1608300341071900

### Next Steps
- @bsmartin-ep to schedule production Data Deletion Request and in tandem complete #17832 to add annotations in GA
- @JasonTheBearded to perform same steps for production BigQuery scrub, please be sure to backup existing data before executing

**Comment by jonwehausen** [comment]
@bsmartin-ep to run thru post-validation

**Comment by joanneesteban** [comment]
@bsmartin-ep to documentation post-validation (in sensitive repo) & close out.

**Comment by bmcgrady-ep** [comment]
### QA Testing

Data Layer Event | DL Screenshot | GTM Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
fl-search-results | ![image](https://user-images.githubusercontent.com/66263904/108781043-88d80e80-7526-11eb-8570-60029ce87866.png)| ![image](https://user-images.githubusercontent.com/66263904/108780993-72ca4e00-7526-11eb-80b3-780e26550856.png)| ✔️ **PASS**

@bsmartin-ep - QA looks good. Let me know if you need anything else on this.

**Comment by bsmartin-ep** [comment]
Facility Locator search event (`fl-search-results`) has been restored (minus closest-distance field).  DL params now have a default value of _(not set)_.

(cc @JasonTheBearded)
