### ISSUE TITLE
Update health care copay rates for January 1, 2021

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16640]
## Issue Description
We need to update the copay rates at: https://www.va.gov/health-care/copay-rates/. 

---
## Tasks
- [x] Get updated rates from health care SMEs (Danielle)
- [x] Clone 2020 page and leave unpublished as 2020 archived rates (Content team). Note that we haven't had past year pages for copay rates in the past. We'll want to save a draft archive for 2020 rates so that we have it for future conversations around this, but we don't want to publish right now.
- [x] Update rates on main page (Content team)
- [x] Review rates for accuracy (Content team)
- [ ] Send rates to SMEs for final sign off (Danielle)
- [ ] Incorporate any final feedback and publish (Content team)

## Acceptance Criteria
- [x] 2021 copay rates are live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @brianalloyd. Just getting this on the content team's radar for spring 37. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @brianalloyd. Please see rate updates below. Per our health care SME, only inpatient rates are changing for 2021. This work can be completed at any time prior to code freeze on 12/22. Thanks!

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/42d0a5c8-1e5c-4c51-b84b-dab83364f311)

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/ba4520db-28b5-486e-8545-d10651a8f7cc)

**Comment by RLHecht** [comment]
Thanks @DanielleThierryUSDSVA. I'll look into this and have Selina work on it this sprint.

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

2021: http://preview-prod.vfs.va.gov/preview?nodeId=703 (I added the Past rates section and link for the 2020 rates. My want to remove)
2020: http://preview-prod.vfs.va.gov/preview?nodeId=11755

**Comment by RLHecht** [comment]
These pages have been published. Moving to validate and will close after tomorrow's deploy. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
This page is live on site. Closing ticket.
