### ISSUE TITLE
Engineers VSP Onboarding Sub-Task

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1665]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Sub-Tasks to the larger **[VSP Onboarding Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1538)**
- [x] [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md)
  - [x] Micah
  - [x] Kathleen
  - [x] Jesse
- [x] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [x] Micah
  - [x] Kathleen
  - [x] Jesse
- [x] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [x] Micah
  - [x] Kathleen
  - [x] Jesse
- [x] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [x] Micah
  - [x] Kathleen
  - [x] Jesse
- [x] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
  - [x] [Micah](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1503)
  - [x] [Kathleen](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1686)
  - [x] Jesse  

## Acceptance Criteria
 - [x] Each team member above has addressed each item.  
_If other team members want to do this as well, they are welcome to.  We won't track them here._

**Comment by micahchiang** [comment]
@jason-gcio - I was able to complete setup for internal tools yesterday, so feel free to close this out.
