### ISSUE TITLE
Find a VA Form: Map business process for adding/editing/deleting forms, determine forms DB date update triggers

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16654]
## Issue Description
Today, updates to PDF forms in the Forms database don't appear to consistently trigger changes to the date fields in the same database.  This lack of consistency can result in confusion for the user in cases where the **Issue** and/or **Revision** date listed on the search results and forms details pages do not reflect the date displayed on the PDF itself.

#### Date of 11/13/2020 on search page:
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/5008c0b8-cd9f-4560-bdd3-f0640f457638)
---
#### Date of Aug 2020 on actual PDF:
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/eefe46d9-9b64-4908-9437-e3fda4538f21)
---
## Tasks
- [ ] Work with business to map the various ways in which forms are updated/replaced in the Forms DB
- [ ] Determine which series of steps trigger an update to the "Issue" date field 
- [ ] Determine which series of steps trigger an update to the "Revision" date field 
- [ ] Determine which series of steps trigger an update to neither field 
- [ ] Determine and document the types of updates that should be revealed to the end user. For example, a change to the verbiage or addition of a field on the form are material changes that should be relayed to the user, whereas immaterial changes to the PDF file name would not (file name changed from va-2346a.pdf to va_2346a.pdf).
- [ ] Determine and document recommended changes to business processes and/or triggers to ensure Issue and Revision dates are accurate

## Acceptance Criteria
- [ ] Various ways used to update forms in the Forms DB are documented.
- [ ] Each series of steps that trigger an update to the "Issue" and/or "Revision" fields is documented.
- [ ] Each series of steps that do **not** trigger updates to the "Issue" and/or "Revision" fields is documented.
- [ ] Specific types of updates warranting a change to the date field from the user's perspective are documented, as well as those that do not.
- [ ] Recommended changes to business process and/or event triggers to accurately capture the date of material changes in the Forms DB are documented and shared with the appropriate stakeholders.
---
