### ISSUE TITLE
Establish New Escalation Path for OAuth-Proxy Oncall Alerting

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#16656]
## Issue Description
This service is owned by DVP, not sure the Operations team should still be getting oncall alerts for failures dealing with this service. Should we look at adding DVP Infrastructure folks to PagerDuty and establishing new escalation path(s) for alerts around this particular service?

Relates to: #14994

---
## Tasks
- [x] Check with DVP Infra team to make them aware that we plan to disable this
- [x] Disable the alerts in question; or only send them to a specific Slack channel, per Michael Fleet (see comment below)

## Acceptance Criteria
- [x] Ops is no longer alerted for this service

---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by f1337** [comment]
My high level thought is: If there's nothing we can do about an alert, I don't want us receiving it.

So do starters, let's disable the alerts in question. Or only send them to a specific Slack channel.

Then in a separate effort, we can engage with whomever may actually be able to act upon such alerts.

IOW: First aid, first. Then let's talk about surgery.

**Comment by jhouse-solvd** [comment]
@f1337 - Seems like a reasonable approach. :) 

Also, regarding engaging who may able to act on alerts, @dginther mentioned that Beau Grantham (Lighthouse API team) may be a good point of contact for this. Michael, let us know the best way to take this forward? (less urgent, as we will work to disable alerts as a first step)

**Comment by jhouse-solvd** [comment]
Assigning this to @oragame

**Comment by oragame** [comment]
The alerts have been disabled - could be closed or left open until further discussion about the long term plan

**Comment by jhouse-solvd** [comment]
Closing. See parent Epic for ongoing plan to address alerts.
