### ISSUE TITLE
Document vets-api to prepare for move to new infrastructure (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16669]
## Issue Description
_Ensure that we've fully documented current architecture / configuration of vets-api to ensure that we will be ready to create a migration plan for moving it to the new infrastructure with minimal impact to the platform._

---
## Tasks
- [X] Written documentation that clearly explains vets-api's configuration and setup in sufficient detail
- [X] Supporting architecture / configuration diagram (as needed)

## Acceptance Criteria
- [X] vets-api configuration and dependencies are well documented
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mydesignrocks** [comment]
https://vfs.atlassian.net/wiki/spaces/VI/pages/815562765/VETSAPI
(more updates to follow in the near future / coming days)

**Comment by jhouse-solvd** [comment]
[This](https://vfs.atlassian.net/wiki/spaces/VI/pages/815562765/VETSAPI) is looking good. We can always iterate moving forward with additional detail.

**Comment by jhouse-solvd** [comment]
Closing
