### ISSUE TITLE
Add link to direct upload on the Upload evidence page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16687]
## Issue Description
Paul Shute and Cleveland Karren in disability comp would like to add a link to AccessVA's direct upload tool from our Upload evidence page. This is a new tool and they want to make it available to Veterans who need to upload evidence for claims other than an initial disability claim that is pending. So this would be used to upload evidence for new claims or supplemental claims, or Board appeals, etc. 

Here's the link to add (the path to get into the tool):
https://eauth.va.gov/accessva/?cspSelectFor=dmhs

This is the existing page on VA.gov where we want to add the link to the tool: https://www.va.gov/disability/upload-supporting-evidence/

---
## Tasks
- [x] Work language and a link into the existing page in a way that isn't too prominent. 
- [x] We may need to remove the last Q&A on the page if that information gets conveyed in the new text that introduces direct upload. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Cleveland and I had lots of email communication back and forth about how to message this tool since he wants it on the very specific page in disability called "Upload evidence to support your disability claim." One tricky part is that the tool can be used to upload any kind of document to VA--not just for disability benefits, and not just evidence. We came to agreement on text, then I shared on the larger email string with the direct upload team. Erica Dunbar wanted to make the reference more general and not have the examples of "new claims" and "Supplemental Claims," which are disability-specific. So... here's where we landed, and now we're waiting for potentially more feedback from Andrea Lapinski, who is on the team responsible for the direct upload tool.

It will appear on this page and replace the first Q&A there:
https://www.va.gov/disability/upload-supporting-evidence/

**How do I upload evidence online to support my disability claim?**

If you're waiting for a decision on your disability claim, you can upload evidence to support that claim using our [claim status tool](https://www.va.gov/claim-or-appeal-status/). 

**Note:** If you want to upload supporting documents for another claim, you can use the [direct upload tool (https://eauth.va.gov/accessva/?cspSelectFor=dmhs) through AccessVA.


Future work to mention that came out of many conversations with Steve Kovaks, Cleveland, and Erica:
- We need a new page that covers all the ways you can upload docs of any sort to VA. Initial list includes:
Making an inventory of all places where you can upload docs would probably be a good thing. The ones I can think of off the top are
Disability claim (526EZ) - finished on VA.gov
Dependency Claim (686c) - launching on VA.gov in Dec - upload marriage certificate, adoption papers, etc
Supplemental Claim (0996?) - planned but not in development
NOD (10182) - in development
Claim Status Tool - finished on VA.gov

- In the short term, we need to figure out where else to add a link to direct upload--which pages in the other hubs.

**Comment by RLHecht** [comment]
The changes on the Upload Evidence page are now live. @bethpottsVADEPO I'm going to close this ticket.
