### ISSUE TITLE
VR&E SME request to broaden language to include professional not just vocational 

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16682]
## Issue Description
VR&S leadership would like to expand the understanding of the program. It isn't just about vocational job help, but also professional counseling and training. Solving this simply by adding the word "professional" in 3 places where we mention vocational counseling/fields.

Jen Lee and I had a call with Peter Granato and Robyn Trulock about this. We explained that we don't want to remove the word "vocational" altogether and that it would be better to keep that for SEO and add "professional."

Preview: http://preview-prod.vfs.va.gov/preview?nodeId=731

---
## Tasks
- [x] Edit the VR&E Employment Through Long-Term Services track page. Add the word "professional."
- [x] Wait to publish. This page is serving as a mock-up to show the type of change we can make to solve for the problem of Veterans thinking VR&E is only about vocational counseling/training. We'll wait to hear back from Peter Granato in VR&E.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you make this edit across the pages mentioned and see if there are any other places?

Here's the note from the SME on how to proceed:

VR&E wants to go forward with the change but can we make it “Professional or Vocational” instead of “Professional and Vocational?” We believe this makes more sense because each Veteran plan will fall into one of the options.

I also found similar references on these pages:

https://www.va.gov/careers-employment/vocational-rehabilitation/ides/

https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/

https://www.va.gov/careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment/

Thanks! Please let me know if you have any questions or when the changes are made so I can present them to Margarita.

Peter Granato

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made the updates to the following pages. These are all saved in draft form. Let me know when I should publish. 

- http://preview-prod.vfs.va.gov/preview?nodeId=731
- http://preview-prod.vfs.va.gov/preview?nodeId=728
- http://preview-prod.vfs.va.gov/preview?nodeId=726
- http://preview-prod.vfs.va.gov/preview?nodeId=732
- http://preview-prod.vfs.va.gov/preview?nodeId=733 (only in related links)
- http://preview-prod.vfs.va.gov/preview?nodeId=734 (only in related links)
- http://preview-prod.vfs.va.gov/preview?nodeId=730 (only in related links)
- http://preview-prod.vfs.va.gov/preview?nodeId=729 (only in related links)

**Comment by RLHecht** [comment]
These pages have all been published. Moving to validate and will close after today's deployment.

**Comment by RLHecht** [comment]
These changes are live on the site. Closing ticket.
