### ISSUE TITLE
Research generating code coverage reports from Cypress tests

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16680]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Currently, we do not have a clear idea of how much code-coverage Cypress tests are providing. We would like to implement a system that automatically generates Cypress code-coverage reports.

---
## Tasks
- [x] This is going to take some research and exploration
- [x] Review https://docs.cypress.io/guides/tooling/code-coverage.html
- [x] POC configuration of the @cypress/code-coverage plugin

## Acceptance Criteria
- [ ] Unknown at this time
---

**Comment by ddzz** [comment]
Cypress has [a plugin](https://github.com/cypress-io/code-coverage) for generating coverage reports for E2E tests. I was able to generate reports locally, but this required modifying the `vets-website` production build to include testing plugins that are meant only for test environments (this is similar to the [issue with removing test attributes from our production build](urlhttps://github.com/department-of-veterans-affairs/va.gov-team/issues/16472). Since we don't want to include testing plugins in our production build, code coverage reports cannot be generated using our existing configuration.

There are two workarounds to this issue:
- Running Cypress tests against a `test` build.
- Including testing plugins in `production` builds (not recommended).

**Comment by pjhill** [comment]
Let's explore those two workarounds and brainstorm alternatives under this ticket.
- [ ] Schedule timeboxed brainstorming session for alternatives with the team.
- [ ] After the brainstorming session, create a POC of the chosen solution

**Comment by holdenhinkle** [comment]
https://docs.cypress.io/guides/tooling/code-coverage

**Comment by holdenhinkle** [comment]
Instrumenting code
Cypress does not instrument your code - you need to do it yourself. The golden standard for JavaScript code instrumentation is the battle-hardened Istanbul and, luckily, it plays very nicely with the Cypress Test Runner. You can instrument the code as a build step through one of two ways:

Using the nyc module - a command-line interface for the Istanbul library
As part of your code transpilation pipeline using the babel-plugin-istanbul tool.

**Comment by pjhill** [comment]
An MVP of this was completed.
