### ISSUE TITLE
Document unbound to prepare for move to new infrastructure (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16689]
## Issue Description
_Ensure that we've fully documented current architecture / configuration of unbound to ensure that we will be ready to create a migration plan for moving it to the new infrastructure_

---
## Tasks
- [x] _Written documentation that clearly explains unbound's configuration and setup in sufficient detail_
- [x] _Supporting architecture / configuration diagram_

## Acceptance Criteria
- [x] _unbound configuration and dependencies are well documented_
- [x] _receive team feedback and add any minor updates / suggestions_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Document is in "near-complete" status, awaiting team feedback.

**Comment by jbritt1** [comment]
https://vfs.atlassian.net/wiki/spaces/VI/pages/797638657/Unbound

**Comment by jhouse-solvd** [comment]
@jbritt1 - thanks for the stellar documentation. I've reviewed and it looks great, and we can always iterate to clarify as needed moving forward. 

closing.
