### ISSUE TITLE
Draft Research Summary for EDU DD Usability Sessions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16691]
## Background
Based on findings in the usability sessions we need to precipitate out any findings that might lead to any improvements in either the design or the development of the feature. 

## Tasks
- [x] Review all the available notes from the usability session
- [x] Draft the summary findings 

## Acceptance Criteria
- [x] Share the findings in a GH .md file and notify the PM's for both eBenefits and Authenticated Experience for review.
  - [x] ~~If a powerpoint is better suited, feel free to use that~~
  - [x] Summary linked in comments to be shared with AuthXP
  - [x] Synthesis linked in comments AuthXP

**Comment by sporeboy** [comment]
The initial draft for the summary is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing/dd-edu-topline-summary.md

The WIP draft for the analysis is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing/dd-edu-synthesis.md

**Comment by sporeboy** [comment]
Initial draft summary reviewed by AuthExp; no revisions required.
