### ISSUE TITLE
Add SOJ to 686 Submission

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#16696]
## Goal
After determining the closest Regional Office to the Veteran based on their zip code, we need to pass that RO number in the Station of Jurisdiction (SOJ) field when calling the BGS `insertBenefitClaim` service.

## Considerations
This ticket is closely related to this issue (https://github.com/department-of-veterans-affairs/va.gov-team/issues/12425), which may end up being an Epic

## Tasks
- [x] Update the Veteran response to include regional office number
- [x] Update the `insertBenefitClaim` call, passing in SOJ as one of the arguments (populated with RO number)

## Acceptance Criteria
- [x] Tests are updated if needed
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted: https://github.com/department-of-veterans-affairs/vets-api/pull/5421
