### ISSUE TITLE
Implement Design Changes per Usability Session  (if any)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16694]
## Background
Based on feedback received from the usability sessions, we may need to adjust some of the elements in the design for Frontend to build.

## Tasks
- [x] Make, or receive, a list of all design requests
- [x] Prioritize and implement them in the appropriate design file (XD of UXPin)
- [ ] Create tickets for these
- [x] Implement design changes
- [x] Adjust the change log in the research-design folder, as needed

## Acceptance Criteria
- [x] A list of changes have been codified in the changelog
- [x] Design files match the recommendations and findings based on the usability sessions

**Comment by sporeboy** [comment]
Recommendations from research readout: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/discovery/research/wizard-migration-synthesis.md#recommendations

- [Fraud box](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/a1932025-1803-4eda-8b32-e0684fd2453c) suggestion
- [Success text](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/a1932025-1803-4eda-8b32-e0684fd2453c) suggestion

**Comment by sporeboy** [comment]
Copy revisions given to Peggy for review. Design changes implemented across mockups: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/

**Comment by sporeboy** [comment]
Peggy's feedback received and implemented. Latest changes from here: https://dsva.slack.com/archives/DNDN2C66N/p1608753909006800

Mockups are up to date: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/
