### ISSUE TITLE
EKS - Install ArgoCD on "platform-tools" cluster in DEV for deployment of ops-owned services

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16693]
## Issue Description
We want to install ArgoCD on the platform-tools EKS cluster that will be used for hosting ops-owned services and tools that support the VSP.

---
## Tasks
- [x] Install ArgoCD on platform-tools cluster
- [x] Test deployment of applications to this cluster using ArgoCD

## Acceptance Criteria
- [x] ArgoCD will be installed and working for additional services to be deployed
- [x] ArgoCD configurations will be checked in to relevant code repositories
- [ ] Basic documentation for installing ArgoCD to ensure that the process is repeatable
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
@tskinn - Do we have any relevant documentation for installing ArgoCD? If not, I can create a separate ticket so that we can close this one out and work on the documentation in the near future.
