### ISSUE TITLE
Expand test suite for VAMC javascript filters

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16705]
## Issue Description
Expansion of VAMC test coverage is a Q4 2020 priority. This issue will address gaps in areas impacted by Javascript filters. 

[Documentation on running unit tests](https://github.com/department-of-veterans-affairs/vets-website/blob/master/README.md#running-tests)

Most critical issues affecting builds:

- [Slack thread:](https://dsva.slack.com/archives/C01512KN35G/p1618510251363200) On 4/15, Builds failed due to the liquid filter `phoneNumberArrayToObject()`  being called with `[ { entity: null }, { entity: null } ]` (resolved in #24146)

---
## Tasks
- [ ] Identify areas which can be covered by automated and/or unit tests
- [ ] Create appropriate tests

## Acceptance Criteria
- [ ]  The VAMC test suite covers areas impacted by Javascript filters

---

**Comment by mchelen-gov** [comment]
crosslinking to related content release failure:
https://dsva.slack.com/archives/C0MQ281DJ/p1618508968213300
https://dsva.slack.com/archives/C01512KN35G/p1618510251363200

**Comment by mmiddaugh** [comment]
[this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16813) adds a test covering the phone number array issue which was causing builds to fail

**Comment by mmiddaugh** [comment]
Issues related to bad phone number data causing build failures  

- [#24146](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24146)
- [#23330](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23330)
- [PR #16813](https://github.com/department-of-veterans-affairs/vets-website/pull/16813)

**Comment by davidmpickett** [comment]
all issues completed
