### ISSUE TITLE
Expand test suite to cover VAMC navigation breadcrumbs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16710]
## Issue Description
Expansion of VAMc test coverage is a Q4 2020 priority. This issue will address gaps in breadcrumb navigation. 

## Tasks
Add unit/automated tests to cover the following breadcrumb navigation
- Home breadcrumb reflects VAMC system name,  not VA.gov (ie: VA Pittsburgh health care > Health services on [Patient and health services](https://www.va.gov/pittsburgh-health-care/health-services/))
- [ ] Breadcrumbs reflect the title of the page (H1).
- [ ] Breadcrumb at the top navigates back to "see all" Events, News Releases and Stories from an individual Event, News Release or Story [#10030]
- [ ] Non-VAMC pages retain the  Home breadcrumb navigation

## Acceptance Criteria
- [ ] Tests check for the appropriate breadcrumb navigational support. To the extent possible, testing should include checks to be done on mobile devices

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
