### ISSUE TITLE
Frontend App Architecture — Audit VA.gov unit tests and iterate to improve stability

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16716]
## Problem Statement 
Flaky unit tests in `vets-website` continue to fail, blocking builds for the 15+ teams who work in that repository. App isolation (see #1099) will alleviate this problem in that failing tests will only affect the team who own the tests. But app isolation will not solve the root cause. How might we determine why these unit tests are so flaky, and take steps towards resolving the root cause of the issue? 

## Hypothesis or Bet
If we reduce the impact of failing unit tests on VFS teams, then the platform will be more scalable. 
If we reduce the impact of failing unit tests on VFS teams, then we will spend less customer support time on failing builds. 
If we reduce the impact of failing unit tests on VFS teams, then the vets-website deploy will not fail as often (and we will therefore spend less time troubleshooting failed deploys). 

## We will know we're done when... ("Definition of Done")
- [x] Unit tests have been audited
- [ ] ~VFS teams have been interviewed~
- [x] Best practices have been documented and training has been completed
- [x] At least one Platform-based iteration has been implemented (i.e. config or linting)
- [ ] [Stretch] Automated reporting on unit test stability has been implemented
   - [x] [Alternative] Manual reporting on unit test stability has been implemented

## Known Blockers/Dependencies 
- Unit tests are owned by VFS teams — VSP can issue best practices and change the configuration of the build pipeline, buy VFS teams are ultimately responsible for their own tests

## Projected Launch Date
- July 2021

### ... tested?

- [ ] ~Usability test has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.~
    - [ ] ... ~and issues discovered in usability testing have been addressed.~
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._ 
   * Metrics on impact documented [in product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/unit-testing/product-outline.md)
   * [Training](https://www.youtube.com/watch?v=8Y0cuMUoWAw&feature=youtu.be) conducted with VFS teams included Q&A
- [X] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] ~_(if applicable)_ New functionality has thorough, automated tests running in CI/CD~

### ... documented?

- [X] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide): [Updated documentation here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test/)
- [X] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
- [X] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/unit-testing/product-outline.md)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [X] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/unit-testing/README.md) exists for this product/feature tool
    - [X] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [X] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [X] ... and should be linked from the VFS-facing README for your product
    - [X] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [] ~_(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)~
- [X] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [X] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] ~This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).~

### Documentation
* **`PRODUCT_NAME`**: [unit-testing](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/unit-testing)
* **Product Outline**: 
   * Unit testing product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/unit-testing/product-outline.md
   * App deployment platform product outline (the objective of this initiative is to improve the build & deploy process, of which unit testing is one part): https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/app-deployment-platform
* **README**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/unit-testing/README.md
* **User Guide**: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test/

### Testing

* **Usability test**: ~_link to GitHub issue, or provide reason for skipping_~
* **Manual QA**: ~_link to GitHub issue or documented results_~
   * Re: Testing — Each portion of this initiative (linked in tickets) included manual QA. Because this initiative was released incrementally there was no overall manual QA effort or usability testing. As noted above, the [training with VFS teams](https://www.youtube.com/watch?v=8Y0cuMUoWAw&feature=youtu.be) included Q&A to address questions from VFS team members
* **Automated tests**: _link to tests, or "N/A"_ N/A

### Measurement

* **Success metrics**:
   * Success metrics in [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/unit-testing/product-outline.md#measuring-success)
* **Release plan**: ~_link to Release Plan ticket_~ _No release plan for this initiative because it was not a significant change to user functionality. The initiative was made up of discovery and moderate updates and recommendations_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by timwright12** [comment]
In diagnosing a problematic unit test I ran `yarn test:coverage` and noticed in the output there are a lot of 404'ing URLs. Thought these might be contributing to the flakiness

**Comment by meganhkelley** [comment]
Katy: some tests are not cleaning up. There are things we can do at the Mocha level to clean up after each test.

**Comment by meganhkelley** [comment]
Where to start on this initiative? 

- What is an audit? Look through the (non-comprehensive) spreadsheet we have of flaky tests and determine whether there is commonality between flaky tests and talk to the owners. 
   - To supplement the info in the spreadsheet, consider reviewing what tests are skipped in `vets-website`
   - Ask all frontend devs to add failing tests to the spreadsheet
- Determine whether teams are fixing flaky tests once they have been identified — write guidance on what is required of VFS teams once a flaky test is identified 

[Flaky test spreadsheet](https://docs.google.com/spreadsheets/d/1MmseC6sdnCfiwazVYDQIKwW9PgLdREo-_oDkhvsqSD4/edit#gid=0)
