### ISSUE TITLE
Solidify OKRs for Type Ahead 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16730]
## Description

Define tangible metrics that can be used to track success for the Type Ahead POC. 

## Background/Context/Resources

Comments made in epic [8896](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8896) established initial thoughts...

> ### OKR
> - Strategy Goal: Decrease the time users spend waiting for an outcome.
> - Objective: Make VA.gov site search a more effective, reliable way for users to more quickly get the information they seek
> - Success metrics: Custom tagging may be required to capture the following KPIs --
> - Increased use of on-site search
> - High click throughs for type-ahead "suggestions"
> - Increased conversion from search to most popular pages and tasks"

## Technical notes

_Notes around work that is happening (if applicable) _

---

## Tasks

- [x] Discuss potential metrics that can be used to highlight POC success

- [x] Synthesize into key OKRs and KPIs that are agreed upon by product team

- [x] Add OKRs and KPIs to product tracker

- [x] Validate that metrics needed are indeed being tracked and recorded on a monthly basis

## Definition of Done

- [ ] OKRs and KPIs have been defined and are trackable on a monthly basis

---

**Comment by denisecoveyduc** [comment]
OKR and KPIs are being added to the unauthenticated pillar tracker and also copied into OKR + KPI Tracker
