### ISSUE TITLE
Review Instances (RIs) - Instance deployments failing with Jenkins exception 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16734]
## Issue Description
_@mpelzsherman reported that it appears that all RI deployments are failing, and he shared the following code snippet [in this slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1606504762206500?thread_ts=1605557619.162400&cid=CBU0KDSB1): 

```
[2020-11-26T05:20:37.546Z] Cloning repository https://github.com/department-of-veterans-affairs/devops.git
[2020-11-26T05:20:41.268Z] ERROR: Failed to clean the workspace
[2020-11-26T05:20:41.268Z] jenkins.util.io.CompositeIOException: Unable to delete '/var/lib/jenkins/workspace/deploys/vets-review-instance-deploy'. 
```

---
## Tasks
- [x] _Investigate this error in Jenkins and determine the cause of the exception_
- [x] _If there is a fix which can be applied that takes less than 2 hours, please go ahead and implement the fix, otherwise bring it back to the Operations team for further discussion_

## Acceptance Criteria
- [x] _This issue will be fixed, or discussed with the Operations team_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
I used the error in the ticket description to go in a manually force the cleaning of the directory Jenkins was unable to clean gracefully. I am unsure on what cause the hang-up initially, but manually removing the desired directory and replaying the job seems to have fixed the issue being observed at this time. For transparency, the command I used was the following:
`sudo rm -rf /var/lib/jenkins/workspace/deploys/vets-review-instance-deploy`

Not the most kosher of of actions to be taken as it feels a bit heavy-handed, but this is essentially what Jenkins was attempting to do but finding itself unable. Therefore, I felt it okay/safe in this scenario to force the directory removal.
