### ISSUE TITLE
Remove url from sitemap XML

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16738]
## Issue Description
www.va.gov/pittsburgh-health-care/status needs to be removed from the XML sitemap as the same nodes build www.va.gov/pittsburgh-health-care/operating-status/ 

[Slack thread on this topic](https://dsva.slack.com/archives/C0FQSS30V/p1606242372167800)

From Mikki 

> FYI, it looks like /status is currently in the xml sitemap, but /operating-status is not.  With traffic that low, its not necessary to do a redirect, but we do need to get that page out of the sitemap (and put in the correct one if applicable) and ideally archive it.  The redirect is only necessary if we have traffic and are concerned about users getting a 404.

---

## Tasks
- [x] Remove www.va.gov/pittsburgh-health-care/status from the XML sitemap
- [x] Create documentation to educate Facilities team about process of updating XML sitemap so new pages can be automatically added and deprecated pages are removed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@davidconlon FYSA

**Comment by srsuddath** [comment]
I deleted the following depreciated code in order to remove this page from the sitemap

```
// Create the top-level facilities status page for Health Care Regions
  const statusEntityUrl = createEntityUrlObj(drupalPagePath);
  const statusObj = {
    mainFacilities: page.reverseFieldRegionPageNode,
    facilitySidebar: sidebar,
    entityUrl: statusEntityUrl,
    alert: page.alert,
    title: page.title,
  };

  const statusPage = updateEntityUrlObj(
    statusObj,
    drupalPagePath,
    'Operating status',
  );
  const statusPath = statusPage.entityUrl.path;
  statusPage.regionOrOffice = page.title;
  statusPage.entityUrl = generateBreadCrumbs(statusPath);

  files[`${drupalPagePath}/status/index.html`] = createFileObj(
    statusPage,
    'health_care_facility_status.drupal.liquid',
  );

```

**Comment by srsuddath** [comment]
The process for adding and removing pages from the sitemap varies on the implementation, so a unified document is not an option at this time.
