### ISSUE TITLE
SME review of Decision Review status chart 

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16736]
## Issue Description
Because claims and appeals are top topics that come into the contact center, we created a chart that explains each status for Supplemental Claims, Higher-Level Reviews, Board appeals, and legacy appeals. This is now with the SME for review. 

---
## Tasks
- [x] Get SME approval.
- [x] Pass to @RLHecht to proofread any edits that came in from the SME.
- [x] Publish.

## Acceptance Criteria
- [x] New article published in R&S.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpottsVADEPO and @lwalsh617 This page was published. Moving to validate and will close after today's deploy.

**Comment by RLHecht** [comment]
This page is live! https://www.va.gov/resources/what-your-decision-review-or-appeal-status-means/ 

Closing ticket.
