### ISSUE TITLE
[Type Ahead] Back End Dev Efforts

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16744]
## Description

Back End Implementation to support Search.Gov click tracking API

## Background/Context/Resources

The Click Track API instructions are attached for implementation and validation.

[Search.gov - Click Tracking API Instructions (Beta).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5393167/Search.gov.-.Click.Tracking.API.Instructions.Beta.docx)

## Technical notes
This ticket is paired with _____

---

## Tasks

- [ ] Create back end implementation to support Search.gov click tracking endpoint

Copied from partner ticket:
# Issue Description
Search.gov -- which powers VA.gov site search -- has completed development and soft launched API-based [click-tracking](https://search.gov/manual/clicks.html) to enable "closed loop" analytics.   They have asked VA.gov, along with other agencies, to test the capability.

The click tracking API endpoint lets you send in click events, which allows you to see click data on your Admin Click Analytics page. We also use this click data to strengthen the search results algorithm for your site.

## Front end tasks
- Ensure the back end data from API is displayed in local and review instance

## Acceptance Criteria

- [ ] Success - A response status code of 200 and empty body.

- [ ] Missing Required Parameters - A response status code of 400 and an error message describing the missing parameters. ["Query can't be blank"]

- [ ] Invalid Or Inactive Search Site Handle - A response status code of 401 and an error message. ["Affiliate is invalid"]

- [ ] Invalid API Access Key - A response status code of 401 and an error message. ["Access key is invalid"]

- [ ] Unparseable URL - A response status code of 401 and an error message. ["Url is not a valid format"]

* ●	Invalid Module Code - A response status code of 401 and an error message. ["Module code {MODULE} is not a valid module"]​

**Comment by srsuddath** [comment]
This ticket is un-needed!
