### ISSUE TITLE
[FE] Questionnaire List feedback 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#16746]
## User Story
As a veteran,
I should have a landing page
so that I can see my questionnaires.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Mock up](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f7b3ab94e155b94041d4c4b)
- [Original Ticket]
(https://github.com/department-of-veterans-affairs/va.gov-team/issues/15525)

## Description
Address feedback from the Design team

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [x] `To do` Typo
- [x] Answer questions arrow
- [x] breakpoints for mobile design, should match VAOS

## Acceptance Criteria
> when is the ticket done 
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
The changes look to be in staging, @kristenmcconnell  Can you verify that the changes are there?

**Comment by kristenmcconnell** [comment]
@mdewey Check out this [Slack thread about max width for tabs and cards](https://dsva.slack.com/archives/C0NGDDXME/p1607450074385000). Basically, we need to make it narrower. There isn't a true definition. Let's mimic VAOS again and make our cards narrower.

**Comment by kristenmcconnell** [comment]
Everything else looks good in staging except that one responsive (max width) item.

**Comment by mdewey** [comment]
Merged in master, will notify when its in staging

**Comment by mdewey** [comment]
@kristenmcconnell  This is stagin. Can you verify and let me know if you have any feedback?

**Comment by kristenmcconnell** [comment]
Looks good.
