### ISSUE TITLE
Content Request for Scam Awareness from Search & Discovery Team

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#16756]
### Content support for:
- Unauthenticated (static) VA.gov pages
- Other writing or editing requests

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

## Background

**Request for new content/pages to raise awareness on scams targeting veterans.** 

[Social listening research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/research-plan.md) for Search & Discovery highlights the need for information regarding scams targeting veterans.

**Impact of scams on veterans (data via AARP/USPIS)**
- Veterans are **twice as likely** to become victims of scams compared to other Americans
- **78%** of veterans have been targeted by scams specifically crafted to exploit their service history
- Why are veterans so susceptible to these particular scams? For starters, veterans implicitly trust fellow members of the military, making them vulnerable to imposters claiming to be veterans themselves. Sometimes, because of their military experiences, veterans also find it more difficult to recognize and combat the emotional manipulation used by scam artists.

**External sites that list common scams/data**
- [USPIS site on common scams targeting veterans](https://www.uspis.gov/veterans/)

- [ID Watchdog site on common scams targeting veterans](https://www.idwatchdog.com/education/11-military-identity-scams/)

- [FTC data on fraud reports targeting all military (including families and Reservists](https://public.tableau.com/profile/federal.trade.commission#!/vizhome/MilitaryReports/Infographic) 
The most common tactic scammers use is impersonating the government.

- [U.S. Government Accountability Office list of recommendations for VA to protect veterans from financial exploitation](https://www.gao.gov/products/GAO-20-109?mobile_opt_out=1#summary_recommend)

**VA.gov pages that address scams**
- [More Than a Number: Identity Theft Prevention](https://www.va.gov/identitytheft/)
- [VAntage Point blog posts](https://www.blogs.va.gov/VAntage/tag/scams/)

---

### Content
     
- [ ] **New unauthenticated VA.gov page**
   
- Can we create a centrally located page that raises awareness on common scams and what to do to report them?
- How can we update existing pages on VA.gov to raise awareness and prevent veterans from becoming victims of scams?

   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

---

### About your team

- Team name: Search & Discovery
- DEPO product owner:  John Hashimoto
- Product manager: Denise Coveyduc
- Designer: Megan Gayle
- FE engineer: Sam Suddath
- Product/team Slack channel: #va-search

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @mgleo.

Initial thought is that this would be a great article in our new Resources and Support section. @bethpottsVADEPO and I can connect further on that and follow up with more thoughts. 

We do have some info on scams existing pages where relevant. A couple of examples below. We can definitely work to incorporate more (and link back to an article on scams overall). Looking forward to working with you on this, and we'll be in touch soon.

https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b5008b97-1a11-41c3-8f2a-db40b5216c77)

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/a6ddee51-c211-451c-826b-390a9caa7631)

https://www.va.gov/housing-assistance/

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/57d482c4-0e92-41c5-8463-820677eba249)

**Comment by mgleo** [comment]
Thanks for the additional info! Just out of curiosity, do you have a link to the new Resources and Support section?

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA I had the same thought during demo, this would be perfect for the new R&S, glad you both connected.  @mgleo link is [va.gov/resources](url)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @brianalloyd. Moving this over to sitewide content since this is going to be a content-specific effort. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO Flagging this for our Thursday meeting so we can sync on strategy for article(s). @RLHecht Flagging this for your awareness.

**Comment by brianalloyd** [comment]
Thanks @DanielleThierryUSDSVA.

**Comment by jenniferlee-dsva** [comment]
Chiming in -- the RS is really for questions that Veterans are actually calling into VA call centers about or searching for. This sounds more like an informational awareness or educational campaign type of content. (I could be wrong - but first impression.) 

So I wouldn't want to guarantee RS as the right place for this - it will really depend on the specific content, if it actually are questions that Veterans are themselves asking. (VS. we WANT them to ask us this question, but they don't, so we're gonna create a page anyway and hope somehow someone stumbles on it). 

I mention the campaign content model because there is a template being created for engagement/campaign content type. This type of content would allow you @mgleo to create an educational/awareness campaign landing page so that you can drive email blast and social traffic to it -- uh, a campaign. :-P

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @jenniferlee-dsva. Yes, a campaign may be another great way to surface this content. I do think that R&S makes sense, however. We mention scams on other pages and it would be very helpful to be able to link over to more information about it.

On a side note, I attended a session yesterday about issues around this and financial management in general, and would like to explore this much more fully.

**Comment by DanielleThierryUSDSVA** [comment]
Thinking more on campaigns...I'm wondering if the doctors who presented on this last night might be interested in supporting an effort around that. I haven't had the chance to fully process that session and review all that materials, but will do that and build into discussions.

**Comment by mgleo** [comment]
Thanks for bringing up the campaign option, @jenniferlee-dsva. It would be great to have both a dedicated page on scams as well as raising awareness by linking to it via social media/email/text/etc. 
Those who were looking for information on message boards were looking for information _after_ they or their relatives were victims of a scam so raising awareness and stopping it before it happens is at the utmost importance. 

Here's data on how often these keywords were searched for on VA.gov's main search within the last 3 months (11/01/20-02/04/21):
"scam": 80 times
"fraud": 421 times

Also, I want to mention, this week during a Search + Discovery user research session, a veteran mentioned trusting VA.gov and not trusting Google's search results because of the prevalence of untrustworthy sites targeting veterans.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks for the additional info, @mgleo!

I'm also thinking that an approach may be clear benefit-focused tie ins for a more dedicated page (like a tie-in to beneficiary financial counseling services and possibly vet center readjustment counseling, etc.). Will continue digging in and discussing w/ Beth as well and touch base soon with more thoughts.

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
