### ISSUE TITLE
[Initiative] Project Cheetah - VAOS for distribution

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#16755]
---
## All documentation for this effort (brief, research) housed at this link (in sensitive repo)
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/covid-vaccine-distro/scheduling

Backend VAMF work https://issues.mobilehealth.va.gov/browse/VAOSR-1468

MAS change: https://issues.mobilehealth.va.gov/browse/VAOSR-1489

## Design
MVP Dev (for active development) https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9
MVP In Progress (for feedback iterations before dev) https://adhoc.invisionapp.com/d/main#/projects/prototypes/21045980

## Collaboration Cycle
VSP Collaboration Cycle checkpoints:

- [x] Kick-off #19486

- [x] IA request #19821

- [x] Analytics Request #20129

- [x] Midpoint Review #19822

- [x] Contact Center Review #21751

- [x] Staging Review #23735

- [x] Privacy & Security Review [#243](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/243)

- [ ] Full Accessibility & 508 Office Audit #26412 (7/19-submitted to 508 office)
