### ISSUE TITLE
[VAMC] Create new .csv file of System page information for all VISN-1 Systems so Owner/Governance can be created by CMS [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16795]
## Story
As a CMS user and web maintainer, I require System and operating status pages, so I can manage, create, and update the system pages and facility status associated to the governance of the system.

## Goal
The System pages are required to stub out and scaffold all nodes/pages for each system listed below.

## Resources
---
## Tasks
Assure that all VAMC systems pages and operating status pages are created for each of the systems listed below:
- [x] VA Bedford health care
- [x] VA Boston health care
- [x] VA Central Western Massachusetts health care
- [x] VA Connecticut health care
- [x] VA Maine health care
- [x] VA Manchester health care
- [x] VA Providence health care
- [x] VA White River Junction health care
## Acceptance Criteria
- [x] .csv file of System page has been created with all associated field data required in CMS.
- [x] File has been provided to CMS engineer to migrate data.
---
