### ISSUE TITLE
[Content Structure] Move VISN-1 Facilities listed in parent category "VAMC facilities" into Correct VISN-1 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#16796]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-1 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**

VA Bedford health care
- [ ] vha_518	Edith Nourse Rogers Memorial Veterans' Hospital
- [ ] vha_518GA	Lynn VA Clinic
- [ ] vha_518GB	Haverhill VA Clinic
- [ ] vha_518GE	Gloucester VA Clinic
- [ ] vha_523BY	Lowell VA Clinic

VA Boston health care
- [ ] vha_523	Jamaica Plain VA Medical Center
- [ ] vha_523A4	West Roxbury VA Medical Center
- [ ] vha_523A5	Brockton VA Medical Center
- [ ] vha_523BY	Lowell VA Clinic
- [ ] vha_523BZ	Causeway VA Clinic
- [ ] vha_523GA	Framingham VA Clinic
- [ ] vha_523GC	Quincy VA Clinic
- [ ] vha_523GD	Plymouth VA Clinic

VA Central Western Massachusetts health care
- [ ] vha_631	Edward P. Boland Department of Veterans Affairs Medical Center
- [ ] vha_631BY	Springfield VA Clinic
- [ ] vha_631GC	Pittsfield VA Clinic
- [ ] vha_631GD	Greenfield VA Clinic
- [ ] vha_631GE	Worcester VA Clinic
- [ ] vha_631GF	Fitchburg VA Clinic
- [ ] vha_631QA	Plantation Street VA Clinic
- [ ] vha_631QB	Lake Avenue VA Clinic

VA Connecticut health care

- [ ] vha_689	West Haven VA Medical Center
- [ ] vha_689A4	Newington VA Clinic
- [ ] vha_689GA	Waterbury VA Clinic
- [ ] vha_689GB	Stamford VA Clinic
- [ ] vha_689GC	Willimantic VA Clinic
- [ ] vha_689GD	Winsted VA Clinic
- [ ] vha_689GE	Danbury VA Clinic
- [ ] vha_689GF	Orange VA Clinic
- [ ] vha_689HC	John J. McGuirk Department of Veterans Affairs Outpatient Clinic
- [ ] vha_689QA	Errera VA Clinic

## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN
