### ISSUE TITLE
AE: Sprint 36

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#16805]
## Priorities
1. Outstanding tickets from Sprint 35
2. Finish Conducting MyVA Research
3. Determine direction of MyVA 
4. Finalize mobile wireframes
5. Enter test cases into Testrail
5. Begin FE build for DD for Edu
6. Preferred Medical Facility BE build
7. Profile 2.0 hardening/enhancements

### Profile
**Design**
- [x] [Design] Look into error messaging/location #10722 

**FE**
- [x] Remove prop spreading in Contact components #16213
- [x] Remove higher level components (HomePhone, WorkPhone etc) in favor of AddressField, EmailField, PhoneField #16214
- [ ] Create helper functions for custom logic in EditViews and render ContactInformationView directly #16215
- [x] [FE] Make "My home address is the same as my mailing address." un-clickable #12876
- [x] [FE] Direct deposit for comp & pen: Update copy so it matches eventual direct deposit for edu designs #16470 

### My VA redesign
**Samara**
- [x] Work with DEPO team to determine final direction of MyVA (dashboard vs newsfeed) #16806

**Design**
- [x] [Design] Conduct research #15684 
- [x] [Design] MyVA Dashboard initial explorations: Research summary #15685
- [x] **[Design] Finalize MyVA mobile wireframes #16807 (EPIC)**
  - [x] Finalize wireframes of disability rating & claim status blocks #16964
  - [x] Finalize wireframes of health care blocks #16966
  - [x] Finalize wireframes presentation of applying for benefits section #16967

**FE**
- [x] [FE] Rewrite existing e2e tests for the Dashboard in Cypress #16209

### Direct deposit for edu
**PM**
- [x] [PM] Put QA spreadsheet test cases into TestRail #16809
- [x] [PM] Schedule/hold usability testing platform review #15686 (review complete, still completing feedback tickets)

**Design**
For Jim Adams:
- [x] Conduct Usability Sessions for EDU Direct Deposit #13812
- [x] Produce Research Summary #16691
- [ ] Implement Design Changes #16694
- [ ] Accessibility Feedback -Usability Testing Prep – Authenticated Experience [Direct Deposit for EDU] #16332
- [x] Design Feedback - Usability Testing Prep - Authenticated Experience — [Direct Deposit for EDU] #16435
- [ ] IA Feedback - Usability Testing Prep - [Direct deposit for Edu] #16420

**FE**
- [x] [FE] Rename existing direct deposit/payment info code to something more specific to comp and pen when applicable #16684
- [x] [FE] Build redux actions/reducers for getting edu DD info #16685
- [x] [FE] Determine if we can even tell if someone is eligible who has not yet set up DD for edu benefits #16686
- [x] Make educationDirectDeposit feature flag to gate new work #16793

### Preferred medical facility
**BE**
- [ ] Backend build #16107

### Analytics
- [x] [Analytics] Profile 2.0: Is it possible to add error codes to the address validation dashboard? #15237

### Unplanned: QA, 508, bugs, or other fixes
- [ ] TBD
