### ISSUE TITLE
R&S top contact center topic to add for 1.1

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#16817]
## Issue Description
Users contact us because they aren't receiving the confirmation email from ID.me when they are trying to sign into VA.gov. We need to create a R&S article for this.

**Here is the script that is used to answer the confirmation email issue:**
**If you are trying to sign into VA.gov using an ID.me account** and are unable to confirm your email address because it was entered incorrectly, you can update your email address in your ID.me Wallet Account Settings. You will find instructions below to do that.
**If you are trying to sign into VA.gov using your DS Logon or MyHealtheVet account but are not receiving the confirmation email from ID.me**, you will need to contact the ID.me support desk for assistance. You contact them using their help form and selecting the “Update Email Address” option https://help.id.me/hc/en-us/requests/new.
Instructions for Updating Your Email Address in Your ID.me Wallet
 1. First select "Sign In" via ID.me website. Make sure to sign into your ID.me account using the original email address the account was first created with.
2. Select "Settings" in your ID.me Wallet.
3. Select the "Account" box.
4. Under Account Information click "edit" next to the "Email" field.
5. Delete the current email address in the "Update Email" field and replace it with the email address you'd like to change it to.
6. Enter the password for your current ID.me account.
7. Click "Update".
Once you click "Update", you will be sent a confirmation link to confirm that you own the new email address. Click the link in the email and your email address will be updated and next time you sign in to your ID.me account, you'll use the new email address!
**NOTE:** If you receive a message that your new email address is already in use please contact ID.me at https://help.id.me/hc/en-us/requests/new so they can assist you further.

---
## Tasks
- [ ] Write the question.
- [ ] Rewrite the answer according to our VA.gov style, voice, and plain language standards.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht I haven't looked at this in a while. Can you see if any of our R&S articles currently cover this topic?

**Comment by RLHecht** [comment]
I put this in Slack but putting it here too so we don't lose track. We have a question about what happens if you don't get a confirmation email but the answer only points users to call MYVA411. https://www.va.gov/resources/signing-in-to-vagov/#i-didnt-get-a-confirmation-ema

Should we update it with this info above?

**Comment by FranECross** [comment]
@bethpottsVADEPO & @RLHecht Do we still need this old ticket? Thanks in advance!

**Comment by FranECross** [comment]
Closing old ticket.
