### ISSUE TITLE
Remove fax numbers from relevant VBA pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#16815]
## Issue Description
VBA is getting rid of all fax numbers for submitting claims as of January 1, 2021. We need to do an audit of our site for any of these and remove them. 

Randi will work with Nick or Kelson to do a search of our pages where these exist. She will also reach out to Peggy to connect with the dev for applications. 

These can be removed as we find them rather than publishing pages all at once.

## Tasks
- [x] Search site for fax numbers that should be removed 
- [x] Remove fax numbers
- [x] Review and publish pages 

## Acceptance Criteria
- [x] All relevant fax numbers removed from VA.gov pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpottsVADEPO These are two pages i found where we should remove the fax numbers:
- https://www.va.gov/decision-reviews/supplemental-claim/
- https://www.va.gov/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/

These two pages I have questions about: 
- https://www.va.gov/pension/ We reference faxing your pension application (no number listed, but I think should we remove "fax")
- https://www.va.gov/life-insurance/options-eligibility/tsgli/ (There's no specific number but I think we should remove "fax" where it mentions how to file a claim)

**Comment by RLHecht** [comment]
Kelson's search list: 

build/localhost/503.html
~~build/localhost/burials-memorials/eligibility/burial-in-private-cemetery/index.html~~
~~build/localhost/burials-memorials/memorial-items/headstones-markers-medallions/index.html~~
~~build/localhost/burials-memorials/memorial-items/presidential-memorial-certificates/index.html~~
~~build/localhost/burials-memorials/pre-need-eligibility/index.html~~
~~build/localhost/burials-memorials/schedule-a-burial/index.html~~
~~build/localhost/claim-or-appeal-status/index.html~~
~~build/localhost/decision-reviews/board-appeal/index.html~~
~~build/localhost/decision-reviews/board-appeal/veterans-law-judge-hearing/index.html~~
~~build/localhost/decision-reviews/contested-claims/index.html~~
~~build/localhost/decision-reviews/legacy-appeals/priority-review/index.html~~
build/localhost/decision-reviews/supplemental-claim/index.html
build/localhost/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/index.html
~~build/localhost/education/transfer-post-9-11-gi-bill-benefits/index.html~~
~~build/localhost/health-care/family-caregiver-benefits/champva/index.html~~
~~build/localhost/health-care/get-reimbursed-for-travel-pay/index.html~~
~~build/localhost/health-care/how-to-apply/index.html~~
~~build/localhost/life-insurance/file-appeal-for-tsgli/index.html~~
build/localhost/life-insurance/options-eligibility/tsgli/index.html
build/localhost/life-insurance/options-eligibility/vgli/index.html
build/localhost/life-insurance/totally-disabled-or-terminally-ill/index.html
build/localhost/pension/index.html
~~build/localhost/records/get-military-service-records/index.html~~
~~build/localhost/resources/claim-status-tool-faqs/index.html~~
~~build/localhost/resources/other-topics-and-questions/index.html~~
~~build/localhost/resources/tag/all-veterans/index.html~~
~~build/localhost/resources/tag/claims-and-appeals-status/index.html~~

@bethpottsVADEPO The ones I didn't cross out have fax references as well that I think should be removed. The three life insurance pages have a number for submitting a form.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I have a question out to Disability Comp regarding the Camp Lejeune page. 

I don't see a fax number on these pages: /decision-reviews/supplemental-claim/index.html
https://www.va.gov/life-insurance/options-eligibility/tsgli/

The others that aren't checked off above, I'm looking into.

**Comment by bethpottsVADEPO** [comment]
Lori Hamilton, life ins SME, said to keep the fax numbers on these two pages because they are Prudential fax numbers:
/life-insurance/options-eligibility/vgli/index.html
/life-insurance/totally-disabled-or-terminally-ill/index.html

**Comment by bethpottsVADEPO** [comment]
@RLHecht The fax number needs to stay on this page: /disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/index.html

**Comment by RLHecht** [comment]
Update: I removed the fax numbers from the accordion on Supplemental Claims and updated the language on the Pension page. We are keeping the references on the other pages. Moving this ticket to validate.

**Comment by RLHecht** [comment]
These updates are now live on the site. Closing ticket.
