### ISSUE TITLE
Add work study info to STEM scholarship and work study pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#16810]
## Issue Description
Per stakeholder Tammy Hurley, Rogers STEM scholarship recipients can now pursue work study. We need to add text to two places on the stem scholarship and work study pages providing info.

**First page:** https://www.va.gov/education/other-va-education-benefits/stem-scholarship/

**Text provided to be added to the page:** “Effective November 5, 2020 Edith Nourse Rogers STEM Scholarship beneficiaries are eligible for Work Study benefits. Work Study applications and contracts are currently being accepted for STEM Scholarship recipients. Rogers STEM Scholarship beneficiaries interested in Work Study may apply at the VA.gov.“

**Under the More questions section on the page, add the following:** 

Can I use the STEM Scholarship while participating in the Work Study program?
Yes. Individuals receiving the Edith Nourse Rogers STEM scholarship may participate in the Work Study program.

**Second page:** https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/work-study/

**Add to list of programs in blue box:**
The Edith Nourse Rogers Science Technology Engineering Math (STEM) Scholarship

## Tasks
- [x] Rework text provided into Plain language (Beth)
- [x] Add text to pages (Randi)
- [x] Review and publish (Randi)
- [x] Notify stakeholders when changes are live (Randi)

## Acceptance Criteria
- [x] Changes are on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Updated the two nodes:
http://preview-prod.vfs.va.gov/preview?nodeId=6860 (new Q&A is here)
http://preview-prod.vfs.va.gov/preview?nodeId=931 (new link to STEM page added to this work study page)

@RLHecht You can take your copyediting pass! Wait to publish until we hear back from SMEs.

**Comment by RLHecht** [comment]
@bethpottsVADEPO These changes all look good. I'll wait to hear from Tammy to publish.

**Comment by RLHecht** [comment]
These pages were published. Moving to validate.

**Comment by RLHecht** [comment]
These are live on site. Closing ticket.
