### ISSUE TITLE
Empathetic language for FSR form

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16814]
## Issue Description
Request from FSR form team to recommend empathetic language for these 3 specific needs as part of the list of expenses in the form:

- What is preferred term for “disability” as in elder care, child care, disability care?

- What is the preferred term for “special needs” education programs? Just “special education programs?”

- Same question for “special needs health care programs”  (such as programs for autistic children)

---
## Tasks
- [ ] Research 
- [ ] Provide recommendations

## Acceptance Criteria
- [ ] Recommendations provided 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @3obryandogs. I don't have specific guidance for you at the moment on these terms. I will try to look into this as soon as I can. Also inviting @RLHecht @bethpottsVADEPO @peggygannon thoughts/expertise in here.

But we typically use person-first language for VA.gov. Guidance, in general, is to ask the specific person or community what they prefer (for example, some people prefer "disabled person" vs. "person with a disability"), but if you can't do that because it's a more general communication, to default to person first ("person with a disability").

Here are some resources for empathetic language:
https://ncdj.org/style-guide/
https://adata.org/factsheet/ADANN-writing
https://www.apa.org/pi/disability/resources/choosing-words

@RLHecht may have more specifics from AP style.

**Comment by 3obryandogs** [comment]
@danielle.thierry@va.gov<mailto:danielle.thierry@va.gov> – these would part of a loop list for the FSR under “Additional monthly expenses. Definitely want to be sensitive to the Veteran’s needs.
For example, Care services - child care, elder care, “disability care”
Education services – special needs education programs (special school for blind, autistic, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @3obryandogs. Yes, the specific Qs you had are noted at top of ticket.

**Comment by 3obryandogs** [comment]
Thank you for your input, but I want to double-check: 
For example, Care services - child care, elder care, **“disability care” - OK to use?** 
For example, Education services – **special needs education programs - OK to use?**

These are not direct comments to a community, but items included in a list of possible expenses.

**Comment by RLHecht** [comment]
There is no specific entry for "special needs" in AP though in their Q&A section they respond to a question with: 

Our preference is to be specific about the needs when possible (and to use such detail only when clearly pertinent to the story). That said, the general term special needs is widely used and is acceptable.

However, the NCDJ.org style guide recommends "functional needs" Is this too long? "Education programs for the functional needs of people with disabilities"

**Comment by DanielleThierryUSDSVA** [comment]
@3obryandogs Yes, I understand your request and context. I'm offering you general resources to consult and guidance _in addition to and while confirming_ the answers to the specific questions.

**Comment by 3obryandogs** [comment]
Bless you! It’s a Monday on a Wednesday! More chocolate and caffeine are needed on my end!

**Comment by 3obryandogs** [comment]
@DanielleThierryUSDSVA @RLHecht 
Thank you both for your help! Also, I've saved the suggested sites for future reference.

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht I like your suggestion, but that does seem long. @3obryandogs I see you closed the ticket, but I'm not sure the specific questions were answered yet?

**Comment by 3obryandogs** [comment]
@danielle.thierry@va.gov<mailto:danielle.thierry@va.gov> – I feel comfortable using “disability care” and “special needs education program” in the list. They won’t be visible unless someone starts to type the first three letters of the word. Thanks!!

**Comment by peggygannon** [comment]
Hello! just getting a chance to weigh in here! 

@3obryandogs you say this is content will be part of a loop list component. It might be helpful to see a sample design in conjunction with the content options we're deciding on. It sounds like from what you shared above some of this content might nest under a larger subject? (*For example, Care services - child care, elder care, “disability care”*).

**Comment by 3obryandogs** [comment]
I don’t know what the designers will choose for their final product. This is how I presented the items for them to consider:

  *   Care-related services
·         Child care
·         Elder care
·         Disability care
·         Nursing home
·         Rehabilitation home
·         Babysitting

  *   Education-related services
·         School tuition
·         School meals
·         School supplies
·         School uniforms
·         Special education programs
·         Student loans
·         School or college endowment
·         College savings plan
