### ISSUE TITLE
[FSR] Finalize 'Why might I have this debt?' content

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#16827]
## Issue Description
_In order to finalize the Debt Letters MVP release, we need to provide content to users explaining why they may have received a VA debt. There are many ways a Veteran can receive a debt, but we don't need to list every possible reason. Rather, we should provide common reasons why a Veteran may receive a Compensation & Pension or Education debt. We have [a first pass at this content](https://docs.google.com/document/d/17cfVffip0guLS_Y_Nf8bLar6ZI--zc66CoXngWKLSiY/edit?usp=sharing), but need to ensure the content aligns with [VA.gov's content style guide](https://design.va.gov/content-style-guide/) and [plain language best practices](https://www.plainlanguage.gov/)._

---
## Tasks
- [x] _Reach out to the DMC stakeholders for answers on outstanding questions (bolded in the GDoc)_
- [x] _Finalize the content (Don't hesitate to meet with Riley/Becca if you have questions or need assistance!)_
- [x] _Send the finalized content to DMC for feedback as needed_
- [x] _Upload the finalized content in the frontend dev team's preferred format and attach in this ticket (Reach out to Becca/Riley for help uploading to GH if needed)_

## Acceptance Criteria
- [x] _Content has been finalized_
- [x] _Final deliverable has been attached to this ticket_

**Comment by 3obryandogs** [comment]
This was my updated version that incorporated updates from a DMC phone meeting:
Why might I have this debt?
A letter was sent to the address on file with details about VA overpayment for specific benefits. 
Compensation and pension
Some reasons you might owe disability compensation or pension repayment to VA include:
•	Military pay and disability compensation at the same time
•	Change in active duty status
•	Change in eligibility
•	Change in your marital status 
•	Change in your dependents
•	Duplicate payment by VA
•	Unreported income
•	Unreported incarceration
If you want more information about repayment options, please call the DMC at 800-827-0648.
 If you want more information about why you owe this repayment, please call 800-827-1000 for disability compensation or 877-294-6380 for pension.
Education
Some reasons you might owe education repayment to VA include:
•	Academic probation or suspension
•	Change in active duty status
•	Change in your enrollment (drop a class)
o	Note: Change in course enrollment can cause overpayment in tuition, housing, and book and supplies.
•	Change in your eligibility
•	Change in your housing 
•	Duplicate payment by VA
•	Your withdrawal from college, university, or higher education program
Note: For Post-9/11 GI Bill benefits, three separate payments are made by the VA for tuition, housing, and books and supplies. When there is a change in this benefit’s use, VA will collect the three debts separately.
If you want more information about repayment options, please call the DMC at 800-827-0648.
If you want more information about why you owe this repayment, please call the Education office at 888-442-4551.

**Comment by rileyorr** [comment]
@3obryandogs thanks for syncing with me and Becca! I updated this ticket to reflect that the final deliverable should be whatever format works best for the frontend dev team. I also readjusted the content in [the Google Doc](https://docs.google.com/document/d/17cfVffip0guLS_Y_Nf8bLar6ZI--zc66CoXngWKLSiY/edit?usp=sharing) based on what we saw on VA.gov. Feel free to change it to whatever you and Peggy think is best!

**Comment by 3obryandogs** [comment]
@peggygannon - would you take a look at the Google Doc above? (Or I can send it to you in a Word file) Riley, Becca and I are concerned about the bullet points. Are they written in empathic, friendly tone? We are trying to list some of the reasons that a Veteran might receive a debt letter. Thanks!
https://docs.google.com/document/d/17cfVffip0guLS_Y_Nf8bLar6ZI--zc66CoXngWKLSiY/edit?usp=sharing

**Comment by leahkeeler** [comment]
Hi @peggygannon This is the last piece of iteration 2 - do you have ETA of when you will be able to review this so the FE devs can merge - Thanks!

**Comment by peggygannon** [comment]
hello, @3obryandogs and leah, yes taking a look at this today. I've requested access to the google doc.

**Comment by peggygannon** [comment]
hello, @3obryandogs and @leahkeeler Content recommendations for Why might I have this debt: 

[Why have this debt content.pgedits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5660773/Why.have.this.debt.content.pgedits.docx)

**Comment by leahkeeler** [comment]
Thank-you Peggy :) I am going to go ahead and send to DMC after accepting your changes for them to review for accuracy only --as in if something is wrong.

**Comment by 3obryandogs** [comment]
The Google doc has been updated with the approved content from Peggy and DMC.

**Comment by leahkeeler** [comment]
Thanks @3obryandogs - @bradl3yC, this is ready to go (finally) for I2

**Comment by rileyorr** [comment]
Looks like @bradl3yC added this content to the UI based on the mentioned issue. I'm gonna close this :)
