### ISSUE TITLE
Resolve Health service page disconnection

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16832]
## What happened?
The Pittsburgh health services page appears to be disconnected from Drupal on [Staging](https://staging.va.gov/pittsburgh-health-care/health-services/) and [Prod](https://www.va.gov/pittsburgh-health-care/health-services/). 

The root cause was determined in [#16830]

**Errors:**

- Page title should be "Health services", not "Patient and health services"
- Page is missing the intro paragraph
- Page is missing "In the spotlight" section

<details>
<summary> Screenshot from Staging </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/98831bad-28eb-4936-8742-89f815b2c1a2)

</details>

## Expected behavior
<details>
<summary> Expected behavior (seen on Erie devshop) </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b1040af9-b928-4091-843f-10138c48faba)

</details> 

## Tasks
- [x] Resolve issue discovered in [#16783 

## Acceptance Criteria
For Staging, Prod and devshop instances - 
- [x] Page title should be "Health services", not "Patient and health services"
- [x] Page is missing the intro paragraph
- [x] Page is missing "In the spotlight" section

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
