### ISSUE TITLE
VAMC site audit (disconnected pages) 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16833]
## Issue Description
As described in [#16830], the Pittsburgh health services page appeared to be disconnected from Drupal on [Staging](https://staging.va.gov/pittsburgh-health-care/health-services/) and [Prod](https://www.va.gov/pittsburgh-health-care/health-services/). 

---
## Tasks
- [ ] Based on root cause discovery, audit the VAMC site to find any other pages which appear to be disconnected from Drupal. 

## Acceptance Criteria
- [ ] All VAMC pages reflect Drupal as source of truth.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
