### ISSUE TITLE
Synthesize Vet Center research

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16844]
## Issue Description
Synthesize Vet Center research findings

## Goals of research
   
---
## Tasks
- [x] Synthesize findings and prepare associated artifacts

## Acceptance Criteria
Artifacts/documentation available which includes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
Research findings: 
[Detailed .md file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/veteran-usability-tests/research-findings.md)
[Presentation Slides deck ](https://docs.google.com/presentation/d/15J7ZroX9_Nghat3lfMPhd5__BcBQvpwf1AHGThpypaU/edit?usp=sharing)
[Synthesis qualitative spreadsheet](https://adhocteam-my.sharepoint.com/:x:/g/personal/leyda_hughes_adhocteam_onmicrosoft_com/EVg4bPeeecJOvju0ksMeDyABggvuZKbPM-9PGCrXz30zFg?e=8b5qgs)
