### ISSUE TITLE
Synthesize vaccination research

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16843]
## Issue Description
Synthesize vaccination research findings

## Goals of research
Learn the Veteran mental models for immunization within the health service taxonomy, primarily for VAMCs
- Where in the VHA taxonomy do Veterans expect vaccination services to be found? 
- What words do Veterans use when searching for vaccination-related services? 
- Is the mental model different change based on the type of vaccination?
   
---
## Tasks
- [ ] Synthesize findings and prepare associated artifacts

## Acceptance Criteria
Artifacts/documentation available which includes
- [ ] Recommendation for where vaccination services should be included and/or cross-linked
- [ ] Recommendation for key words related to vaccination services

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
