### ISSUE TITLE
Remove CH31 Wizard Question

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16848]
## Background
Per the stakeholders, we need to remove the last question, and related answers, in the wizard that asks:  
  
_"**Are you within 12 years of separation from active duty or first disability rating?**"_  
   
## Tasks
- [x] Remove the above question from the CH31 wizard

## Acceptance Criteria
- [x] The above question has been removed from the wizard
- [x] A PR has been requested for merging
