### ISSUE TITLE
CC provider list - update "show more locations" style

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16850]
## Issue Description
When more than 5 community care locations are available for a use to choose from, +# more locations appears and can be clicked to show more available options.

## Tasks
- [ ] Update style of link

## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag
- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs: https://adhoc.invisionapp.com/share/BFZED2H362S

**Comment by outerpress** [comment]
I updated the link style in the prototype and dropped in a newer prototype link (the one in the ticket was an older version).
