### ISSUE TITLE
Update Cypress viewport env vars and presets with November, 2020 data

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16854]
## Issue Description
As an engineer who writes Cypress tests, I need my tests to be run against up-to-date viewport data derived from GA.

## Tasks
- [x] Update data in the spreadsheet first - https://docs.google.com/spreadsheets/d/176BIlJ_IkSeGJHCYiibJcO3TqLfeTD3JtMO0_ld60aE/edit#gid=297835530
- [x] Update data in `config/cypress.json`
- [x] Update data the `presets` objects in the `viewportPreset()` custom command

## Acceptance Criteria
- [ ] `config/cypress.json` and `viewportPreset.js` will be updated and merged to master

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/vets-website/pull/15162

Google doc with updated month GA viewport data - https://docs.google.com/spreadsheets/d/176BIlJ_IkSeGJHCYiibJcO3TqLfeTD3JtMO0_ld60aE/edit?usp=sharing

Awaiting PR approval.

**Comment by holdenhinkle** [comment]
This ticket is done.

**Comment by pjhill** [comment]
Reviewed
