### ISSUE TITLE
Determine baseline usage for the Documentation Homepage

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16868]
## Issue Description
To move towards this O4KR3,
> By Jan 2021, usage metrics are tracked and targets have been established for 5 VSP platform products or services				
we need to understand the baselines for current usage to set initial targets. 

As VSP Product Managers, we also want to start understanding how our own products are being used and eventually set KPIs and KRs for our own services.

---
## Tasks
- [ ] Determine & document the Median (or Average, if not possible) of the weekly Documentation Homepage overall usage. [Usage tracked here](https://analytics.google.com/analytics/web/?authuser=0#/report-home/a50123418w224573768p212889364). Please document in [column D on the tracker.](https://docs.google.com/spreadsheets/d/1jyIxQAystapzDZ8gRkN4yBtruUsnRKvpjovLatHwgr4/edit#gid=1885541117)
- [ ] Document as a comment here the average top 5 links clicked on a weekly basis. Look at weekly usage to note any outliers.  

## Acceptance Criteria
- [ ] VSP and DEPO knows the usage targets for the Documentation Homepage so that we can understand how often VFS teams are using our products and how we can improve

**Comment by vbellissimo** [comment]
Cancelling/old task.
