### ISSUE TITLE
Product Metrics - Determine baseline usage for Grafana

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16867]
## Issue Description
To move towards this O4KR3,
> By Jan 2021, usage metrics are tracked and targets have been established for 5 VSP platform products or services				
we need to understand the baselines for current usage to set initial targets. 

As VSP Product Managers, we also want to start understanding how our own products are being used and eventually set KPIs and KRs for our own services.

---
## Tasks
- [ ] Determine & document the Median (or Average, if not possible) of weekly Grafana overall usage. [Usage tracked here](https://analytics.google.com/analytics/web/?authuser=0#/report-home/a50123418w232865244p218626196). Please document in [column D on the tracker.](https://docs.google.com/spreadsheets/d/1jyIxQAystapzDZ8gRkN4yBtruUsnRKvpjovLatHwgr4/edit#gid=1885541117)
- [ ] Document as a comment here the average top 5 links clicked on a weekly basis. Look at weekly usage to note any outliers.  

## Acceptance Criteria
- [ ] VSP and DEPO knows the usage targets for Grafana so that we can understand how often VFS teams are using our products and how we can improve

**Comment by jhouse-solvd** [comment]
discussing this with the team as these could be useful metrics to share

**Comment by jhouse-solvd** [comment]
Though we didn't do this previously, this would still be a good idea. 

Moving to the backlog so that we can re-prioritize and consider in the future.

**Comment by ph-One** [comment]
There is no longer a need for this
