### ISSUE TITLE
Determine baseline usage for Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16866]
## Issue Description
To move towards this O4KR3,
> By Jan 2021, usage metrics are tracked and targets have been established for 5 VSP platform products or services				
we need to understand the baselines for current usage to set initial targets. 

As VSP Product Managers, we also want to start understanding how our own products are being used and eventually set KPIs and KRs for our own services.

---
## Tasks
- [ ] Determine & document the Median (or Average, if not possible) of weekly Domo usage. [Usage tracked here](https://va-gov.domo.com/page/899833063). Please document in [column D on the tracker.](https://docs.google.com/spreadsheets/d/1jyIxQAystapzDZ8gRkN4yBtruUsnRKvpjovLatHwgr4/edit#gid=1885541117)
  - [ ] Average weekly usage per KPI dashboard
  - [ ] Average weekly usage for the Covid dashboard
  - [ ] Average monthly usage of Recurring Reports
  - [ ] Average monthly usage of Temporary Reports

## Acceptance Criteria
- [ ] VSP and DEPO knows the usage targets for Domo so that we can understand how often VFS teams are using our products and how we can improve

**Comment by joanneesteban** [comment]
Data collected here: https://va-gov.domo.com/page/514439234

Closing this issue.
