### ISSUE TITLE
Track usage and baselines for Platform products

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16870]
## High Level User Story/ies
As a VSP lead or product manager, I need to understand how often my product is being so I can begin to set success metrics for getting VFS teams to know, use, and love the VSP products and services.

## Hypothesis or Bet
**If** _we track usage and set baselines_ **then** _we expect to set up KPIs and strategies to improve our products and to understand if our products are being used_.

## OKR
O4: Get VFS teams to know, use, and love the DEPO Platform products and services.				
KR3: By Jan 2021, usage metrics are tracked and targets have been established for 5 VSP platform products or services				

### What must be true in order for you to consider this epic complete? 

- [ ] Tracking is completed for 5 platform products
- [ ] Usage baselines are determined for the products tracked
- [ ] Tracking and baselines are documented

Tracking is...[tracked here.](https://docs.google.com/spreadsheets/d/1jyIxQAystapzDZ8gRkN4yBtruUsnRKvpjovLatHwgr4/edit#gid=1885541117)

**Comment by Khyatinp18** [comment]
2/21/2022:
Closing this issue since it's no longer needed.
