### ISSUE TITLE
Send announcement to VFS teams about new Cypress viewport features

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16884]
## Issue Description
VFS teams don't know about the new Cypress viewport env vars and custom presets that reference real VA.gov user data. We need to announce these new features so teams start using them.

---
## Tasks
- [x] Send announcement in VFS All Teams about new Cypress viewport features
- [x] Reach out to Service Design about including it the newsletter

## Acceptance Criteria
- [x] An announcement will be sent to #vfs-all-teams 
- [x] Will reach out to Service Design about including it the newsletter

**Comment by holdenhinkle** [comment]
Discussion link - https://dsva.slack.com/archives/C01CHAY3ULR/p1607013580222700

## Announcement draft:

Test Team Announcement!

If you write Cypress tests, please checkout the new Cypress viewport environment variables and presets that reference real VA.gov user viewport data.

Information can be found in the new Cypress Best Practices on VSP doc:
Iterate Through Top VA.gov Viewports
Viewport Presets

Going forward, it would be great if you can set the viewport in your tests using these new env vars and presets, so viewports dynamically reference the viewports used on VA.gov.

Questions, comments, requests are welcome!

**Comment by holdenhinkle** [comment]
Posted on #vfs-all-teams - https://dsva.slack.com/archives/CE4304QPK/p1607016781462900

**Comment by holdenhinkle** [comment]
Service Design Team contacted - https://dsva.slack.com/archives/CPCGRR7F1/p1607017221187700

**Comment by holdenhinkle** [comment]
This ticket is complete.

**Comment by pjhill** [comment]
Reviewed
