### ISSUE TITLE
Move MegaMenu out of the component library into Vets website

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16889]
## Issue Description
Move MegaMenu out of the component library into Vets website

---
## Tasks
- [ ] Remove MegaMenu out of the component library
- [ ] Move MegaMenu to Vets website

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
