### ISSUE TITLE
Prepare to Build SLO Report in DataDog

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#16900]
## Background 

We intend to migrate the external service SLO report to a Datadog-based 

## Tasks

- [x] Figure out how to sum the `haproxy` metrics for "all requests" and "good requests" in SLO definitions
- [x] Set targets for 7d, 30d, 90d, based on the historical performance data
- [x] Create SLOs in DataDog for development environment, in preparation for prod data
