### ISSUE TITLE
OKRs - Need metrics for VFS build and deploy time

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16908]
## Issue Description
One of the VSP Q4 KRs is "KR3: By Jan 2021, VFS build and deploy time is 25% faster. We need a way to track this and come up with baseline metrics (potentially by polling Jenkins for this information).

---
## Tasks
- [ ] Determine which metrics regarding VFS build and deploy time would be relevant
- [ ] Determine the best way to get those metrics into a format that can be shared with other teams

## Acceptance Criteria
- [ ] We will understand our current average build and deploy time (possibly combined, or potentially split out)
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
For reference, some work was done to improve some aspects of the build time. See [here](https://docs.google.com/presentation/d/1FRY9bM_e290sDD5ayZp2yjEQ5C53MwyHF9BNSteYeRQ/edit#slide=id.g8407007210_0_3) for a relevant presentation on what was done.

**Comment by jhouse-solvd** [comment]
@meganhkelley - Is this something that your team is capturing now?

**Comment by meganhkelley** [comment]
Hmm, to some extent — although not in its final iteration. We want to automate this and get more granular info. I'm manually capturing in this spreadsheet for now: https://docs.google.com/spreadsheets/d/1yaYyJuY-XQ1rBsNuRqn3B78gfIIcjqK5OoeDa-JCKAE/edit#gid=0

**Comment by jhouse-solvd** [comment]
Please see the comment above. If we decide to do something more automated in the future, we will create a new ticket and define the criteria accordingly. 

Closing.
