### ISSUE TITLE
Monitoring - provide application performance monitoring (APM) for BE tools on vets-api in DEV (Datadog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16919]
## Issue Description
_from @kfrz: Starting with vets-api, we want to see how much "magic" datadog provides, and what we can get for just vets-api
specifically, will tracing be useful if we don't have any correlation to proxy requests_

---
## Tasks
- [x] Install Datadog APM on vets-api instances in DEV
- [x] Discuss with BE Tools team to see how our APM solution with Datadog meets their needs

## Acceptance Criteria
- [x] We will better understand how our APM solution with Datadog works for BE Tools team (et al)
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
@mydesignrocks @kfrz - please try to add as many relevant notes as you can that will help others understand the work as you all progress 
@alexpappasoddball @dginther - please follow this ticket for updates or reference

**Comment by kfrz** [comment]
@jhouse-solvd @mydesignrocks I've opened a [PR]() to enable tracing module for `vets-api` including the Rails integration. From the [Datadog documentation](https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#rails): 

> The Rails integration will trace requests, database calls, templates rendering, and cache read/write/delete operations. The integration makes use of the Active Support Instrumentation, listening to the Notification API so that any operation instrumented by the API is traced.

[Here is](https://docs.datadoghq.com/tracing/troubleshooting/agent_apm_metrics/) a list of metrics we can get with APM. Furthermore, with the Rails integration, we'll get tracing for the operations as described above. 

This makes me think we could rewrite our StatsD initializers to use [ActiveSupport::Instrumentation](https://edgeguides.rubyonrails.org/active_support_instrumentation.html#creating-custom-events) but I'll leave that for a future backlog. 

In order to get this productionalized, we'll need to modify the playbook and container configuration to listen for traces. Docker [documentation is here](https://docs.datadoghq.com/agent/docker/apm/?tab=ruby) and looks to be straightforward enough, but this may be moot if we're leaning towards a k8s version. K8s [docs for tracing here](https://docs.datadoghq.com/agent/kubernetes/apm/?tab=helm). 

![image.png](https://images.zenhubusercontent.com/5951581361b4ca3b0a725a57/a4bb0003-095a-4a03-b3cb-7ce5491600e2)

More docs: 

- https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#trace-correlation
- https://docs.datadoghq.com/tracing/guide/


**Based on this info,** I'll need to defer to Sri for the next steps re: agent configuration in the container layer.

**Comment by jhouse-solvd** [comment]
This was done, and in fact, #21465 came out of it which is related to specific fine-tuning and customization metrics needed for the SLO report. 

Considering this closed, and will re-visit APM for BE Tools as a topic after we migrate to GovCloud instance of DataDog in #23513
