### ISSUE TITLE
Vet Centers intro copy content review and feedback

### ISSUE THREAD

**Issue by lildziner** [department-of-veterans-affairs/va.gov-team#16911]
## Issue Description

_Provide content review and feedback for Vet Center's updated description to be used as web page intro copy._

#### Background
Facilities team is designing a new website template to be used for 10 pilot (TBD) Vet Centers. A prototype of this website template will be used in an upcoming usability study with Veterans to test their understanding of the services and logistical information available at a facility.

#### Proposed copy to be reviewed
"Vet Centers offer free, confidential mental health and benefit counseling in a non-medical setting for Veterans, service members and their families needing help transitioning to civilian life."

![Atlanta Vet Center prototype](https://user-images.githubusercontent.com/4960080/101083860-243a9280-357b-11eb-9a58-9366e3477197.png)

---
## Tasks
- [ ] _Review [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/veteran-interviews/research-findings.md) to understand the factors that Veterans value most about a Vet Center_
- [ ] _Consider SEO keywords_
- [ ] _Consider [Plain Language guidelines](https://www.plainlanguage.gov/guidelines/web/)_
- [ ] _Review proposed copy (written by the designer to use in testing)_
- [ ] _Suggest improvements_

## Acceptance Criteria
- [ ] _Recommendations are supplied to designer_
---
## Reference materials
- This content review supports the broader body of work found [in this issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16025)
- [Research Findings - Interviews with Vet Center Veteran clients](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/veteran-interviews/research-findings.md)
- Research Findings with [solution brainstorm Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1603629469594/94d7825c23f0eff800a5271bf396293535ef5de7?wid=0-1603629481483&outline=open)
- [Quantified synthesis of words and concepts](https://docs.google.com/spreadsheets/d/1F1CX6SzijB31ADM1h8fwiKVgU-TRfSXiQcrBh7qQAck/edit?usp=sharing) this view has embedded quotes in each cell that give great color. 
- If you can't access the Google Sheet above, I copied the tallied numbers into a tab in Excel [here](https://adhocteam-my.sharepoint.com/:x:/g/personal/leyda_hughes_adhocteam_onmicrosoft_com/EU1R6aqGYuBJsTF2t7xbj1kBddrCk1f8PSgVyqzCvAdnsA?e=FCAL63) but embedding copy into cells is not supported. This spreadsheet is the master synthesis spreadheet with more than you'd ever want to know about this particular study.
- [Preliminary SEO discovery](https://docs.google.com/spreadsheets/d/1Wh2d6vKhRmNBfPtZCh3GxS7po9xKmIjregef7XfvMOY/edit#gid=1797556819) from Google Trends searching the concepts/services most mentioned by Veteran clients 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lildziner. I'd worked on this with Dave directly. Are we okay to close this for now?
