### ISSUE TITLE
VSA spot check review for Search Discovery [Search Typeahead]

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#16914]
## Instructions

1. Click or press the gear icon next to the "Labels" heading on the right. Search for your team in the labels list. If your team is not listed in the Labels menu, please leave a comment after you have created this issue. The Product Support team will create a new label for your team.
2. Text inside `<-- comment -->` blocks will not appear in your issue ticket. These comments offer guidance on what information you should provide for each section.

### For reference

**VSA Development Review** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review)

## Team Name
Search and Discovery

## Product/Feature Name
Typeahead

## Product description
This feature allows a user to select "suggestions" provided in a drop down menu as they type user input. On a click, these suggestions are auto-populated into your user input for your search.

## Review stage

- [ ] **Design collaboration review** (Review design to discuss accessibility and inclusive design) - This may happen as design evolves.

- [ ] **Development intent review** (Review design to discuss approach to take with development, identify what components and semantic HTML would be appropriate, identify any accessibility issues and how to address) - This would happen as designs are passed to development, before development begins.

- [X] **Spot check review** (Review and follow the steps in the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md) first.) This happens well before launch, so that the 508 office can review and any issues addressed *before* launch.

- [ ] **Other:** Please indicate what you're requesting

## Point of contact
Sam Suddath
@srsuddath 

## Preferred times for dev intent checkpoint, if applicable
Any time

## Staging URL and credentials, if applicable

https://staging.va.gov/

## Test plan, if applicable
Make any QA adjustments as needed, then next week our plan is to push live to production with 5% of users.

**Comment by srsuddath** [comment]
All review work was completed by @joshkimux and any issues uncovered have been resolved!
