### ISSUE TITLE
[DISCOVERY] Translation | Spanish | Corona | Design Implementation Exploration for Links

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16923]
## Issue Description
We need to determine if/how we can implement the previously researched design for the translation link. 

**screenshot of link icon and placement:**
![spanish translation design of link.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b4cf938b-f1fe-4983-ac8f-12f82c7c1169)

**invision mockup of icon and link on a page:**
https://vsateams.invisionapp.com/share/DCRWYHDNVPM#/screens/362213468

---
## Tasks
- [x] Review design elements and determine what we would need to implement the icon (or if we need to go with just the link for now).
- [x] Determine whether we can use the front-end to place this icon/link on the [coronavirus faqs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) and [coronavirus research volunteer list](https://www.va.gov/coronavirus-research/). If not, we may need to talk about different placement (like the COVID-19 screening tool placement as shown in the image below), as I don't think the Drupal template will allow us to add a link above the H1 of the page. We can ask Drupal CMS team about that to be sure.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/fa7637f4-d0c3-4644-99d2-03bb0a5ff9b1)

## Acceptance Criteria
- [x] We understand what we can, and can't do, for implementing this design.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SKasimow** [comment]
Thanks @DanielleThierryUSDSVA .  I'll synch with @youngfreezyVA to investigate.

**Comment by youngfreezyVA** [comment]
it's definitely doable. here are screenshots as well as link to PR:

<img width="731" alt="Screen Shot 2020-12-05 at 9 33 36 AM" src="https://user-images.githubusercontent.com/46791771/101259367-5bc15000-36dd-11eb-9b9c-53cb78ccd48d.png">
<img width="744" alt="Screen Shot 2020-12-05 at 9 33 28 AM" src="https://user-images.githubusercontent.com/46791771/101259370-5d8b1380-36dd-11eb-8dfb-4b77cef2ae2f.png">

https://github.com/department-of-veterans-affairs/vets-website/pull/15209

**Comment by DanielleThierryUSDSVA** [comment]
This is fantastic news, @youngfreezyVA .Thank you so much for the quick turnaround!

@batemapf @artsymartha68 keeping you in the loop here re: design discovery for translation link.

**Comment by batemapf** [comment]
Thanks! This looks great!

**Comment by SKasimow** [comment]
Yes, great news! Thanks @youngfreezyVA

**Comment by jenniferlee-dsva** [comment]
All - could you please include @rtwell to validate design? He was the og designer who worked with me on the localization research, and my eye is not trained, but the spacing in the screenshot looks off.

**Comment by jenniferlee-dsva** [comment]
Also the "n" in espanol is missing the tilda.

**Comment by youngfreezyVA** [comment]
@jenniferlee-dsva the associated PR was prefixed with WIP and was a discovery ticket. it's not intended to be merged in just yet.

**Comment by rtwell** [comment]
hello gang! a couple notes:

1. the spacing on the link for Spanish is too close to the breadcrumb (so much so it kinda looks like part of the breadcrumb). Might we add some space above? I'm thinking something in the neighborhood of 3 spacing units. 
2. the icon should also be blue like the link

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @jenniferlee-dsva and @rtwell. And just to make sure we're all aligned: This ticket was just a discovery ticket for @youngfreezyVA to confirm if we could add this icon/link on the front end for the Drupal page. Definitely not intended as the actual implementation. This will go through a design intent review as part of the collab cycle as well. Thanks!

**Comment by rtwell** [comment]
no problem! thanks, @DanielleThierryUSDSVA

**Comment by jenniferlee-dsva** [comment]
Thx for that clarification @DanielleThierryUSDSVA. (Sorry to jump the gun.) RE design intent review/collab cycle - will be helpful to make them aware that we went through user research and prototype testing with this prior to there even existing a Platform team (and a collab cycle).  Excited to see this move forward.

**Comment by SKasimow** [comment]
Hi @jenniferlee-dsva - could you point me to the docs for user the research that was conducted and prototype testing? Would love to review these. Thanks.

**Comment by SKasimow** [comment]
@youngfreezyVA - can you close this?
