### ISSUE TITLE
Staging Review - Facilities [Map enhancements]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16921]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 4 days before scheduled meeting, you must complete list of artifacts below
- [ ] Staging Review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/map-enhancements/phase-1-limit-search-to-250-miles/product-brief.md)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/map-enhancements/phase-1-limit-search-to-250-miles/release-plan.md)
- Access information for the tool or feature in staging -> **unauthenticated** 
- Link to your product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/7&group_by=cases:section_id&group_order=asc&group_id=35)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/1068) [**Staging review for Map enhancement initiative**](https://dsvavsp.testrail.io/index.php?/runs/view/1018&group_by=cases:section_id&group_id=84&group_order=asc) in TestRail with test execution logs
- Link to your [Coverage for References (Cases)](https://dsvavsp.testrail.io/index.php?/reports/view/169) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/170) reports in TestRail 
- Link to verification that accessibility checks are complete:

  - Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.
  
    Required:
    - [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
    - [x] Conduct axe browser scan, and document or address issues found 
    - [x] Ensure end-to-end tests - including the axe check, pass 
    - [x] Check color pairing for proper contrast 
    - [x] Check for colorblindness issues 
    - [x] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
    - [x] Repeat for 300% 
    - [x] Repeat for 400% 
    - [x] Navigate all pages and core functionality with keyboard only 
    - [x] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox 
    
    Recommended:
    - [ ] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) 
    - [ ] Add keyboard end-to-end tests in CI/CD test runs 
    - [ ] Conduct axe-coconut browser scan, document or address issues found 
    - [ ] Test with [WAVE tool](https://wave.webaim.org/) 

  - Link to your [TestRail VSP accessibility test plan](https://dsvavsp.testrail.io/index.php?/runs/view/1017&group_by=cases:section_id&group_order=asc&group_id=84).

  - Known accessibility issues:
    * [#16971 508-defect-2 [KEYBOARD, FOCUS MANAGEMENT]: Keyboard focus flow](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16971)

  - Note: [Color contrast](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16951): was discovered during AXE testing but is not within the scope for map enhancements 

- List of known issues (with links to tickets when applicable)
  - [Edge case](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16945): Following a successful search, if the Veteran changes the search parameters to a search which correctly returns no locations, the map does not move to display the new location. 
  - Known issue: the zoom buttons are slightly offset (which makes the focus also offset) due to something which is overriding the styling/padding

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): 
  * **Gibran Rodriguez, FE Engineer**
  * **Chris Logan, Designer**
- Other specialists: 
  * **Jennifer Strickland, Accessibility**
  * **Tze Lei, QA**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 4 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite 
   - **Thursday, December 17 at 2:00 ET**
- _If no available time slots work for your team, write your availability and requirements here and shira will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by shiragoodman** [comment]
@mmiddaugh thanks! do you have a preferred date in mind per the [VSP Collaboration Meetings Calendar?](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)

**Comment by mmiddaugh** [comment]
[testrail-report-165.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5654155/testrail-report-165.pdf)
[testrail-report-166.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5654171/testrail-report-166.pdf)

**Comment by tlei123** [comment]
@mmiddaugh @pjhill , QA test-runs completed -- QA-artifact links added/updated above in main description.

2 defects logged: #17261, #17305 -- I'm surmising 17305's a **launch-blocker**.

NOTES:
- I added a new Test Plan for my QA test-runs.  It includes the QA-specific [non-A11y] test-cases that Michelle selected for her own test-run [R1018](https://dsvavsp.testrail.io/index.php?/runs/view/1018), which was mostly completed before I got started.  My Plan was needed in order to "explode" the main Run into cross-browser/-device instances.
- Test Case [C2961 Limit zoon](https://dsvavsp.testrail.io/index.php?/cases/view/2961) was not included in Michelle's R1018, so it's not in mine either.
- To enable 1:1 reference-mapping between TestRail test-cases and product Use Cases, I've created:
  - A [Use Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/use-cases/fl-map-enhacements-use-cases.md) in the GH product folder.  The Use Cases are based on the test-cases Michelle created in TR.
  - A "link" ticket that just deep-links each TR test-case to a specific use-case in the doc above.  These tickets serve no other purpose than to support the 1:1 reference-mapping, and won't appear anywhere else beside the test-cases' Reference fields.

Feel free to ping me on Slack for further discussion.

**Comment by brangi** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17305#issuecomment-743262976

**Comment by jenstrickland** [comment]
@mmiddaugh Hi! Do you know if the accessibility tests were completed, but not marked as such? The TestRail accessibility test plan looks like the foundational tests are not complete. I just tested with axe and axe-coconut and the work passed, if that helps.

![Screen Shot 2020-12-14 at 6 56 59 AM](https://user-images.githubusercontent.com/57469/102078851-9f047880-3dd9-11eb-9ad6-c0d6bf4a1492.png)

**Comment by mmiddaugh** [comment]
Hi @jenstrickland they're done. I did them myself. I thought it was captured in Test Rail but I will figure that out. I created only one issue: [#16971] 508-defect-2 [KEYBOARD, FOCUS MANAGEMENT]: Keyboard focus flow (which Gibran has already addressed). I noted a color contrast issue during AXE testing but couldn't tell if it was legit. Regardless, the area called out is not within the scope for map enhancements. Doesn't sound it presented during your testing so hopefully we're good there.

**Comment by jenstrickland** [comment]
Hi @mmiddaugh — I just updated the ticket above with the [check list ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-test-cases-checklist.md#vsa-accessibility-test-cases-checklist)since TestRail doesn't seem to allow me to change "Untested" status.

**Comment by pjhill** [comment]
> Hi @mmiddaugh — I just updated the ticket above with the [check list ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-test-cases-checklist.md#vsa-accessibility-test-cases-checklist)since TestRail doesn't seem to allow me to change "Untested" status.

Jennifer, you're unable to create pass/fail execution records in TestRail? Which account are you authenticating with?

**Comment by jenstrickland** [comment]
@pjhill I use @tlei123 's login credentials. Those "untested" items at the bottom, I couldn't see a way to change that value.

**Comment by mmiddaugh** [comment]
I think we have a disconnect on the Test Run id. All tests show as run and passed on my view. 
Accessibility test run: https://dsvavsp.testrail.io/index.php?/runs/view/1018&group_by=cases:section_id&group_order=asc&group_id=84
![image](https://user-images.githubusercontent.com/55411834/102237490-f70eae00-3eb1-11eb-81c6-77bf3e2068a7.png)

**Comment by peggygannon** [comment]
@mmiddaugh I have no content feedback for this staging review. thx!

**Comment by jenstrickland** [comment]
Not sure why I see "untested". Is this based on individual login? 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/16921#issuecomment-744393892

**Comment by brangi** [comment]
@pjhill @tlei123 Any update from the FE-tools team on this issue ? - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17305#issuecomment-743306048   cc @mmiddaugh

**Comment by mnorthuis** [comment]
FYI, there is no global IA work needed for this effort, so no feedback at this time.

**Comment by allison0034** [comment]
No design feedback for this review. Thank you!

**Comment by tlei123** [comment]
@jenstrickland , just to make sure there's no confusion about where the Passed A11y test-cases are...

This is the Run (R1018, which @mmiddaugh also linked above in her last [Comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16921#issuecomment-745377573)) that includes the Passed A11y tests: https://dsvavsp.testrail.io/index.php?/runs/view/1018&group_by=cases:section_id&group_order=asc

**Comment by tlei123** [comment]
> @pjhill @tlei123 Any update from the FE-tools team on this issue ? - [#17305 (comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17305#issuecomment-743306048) cc @mmiddaugh

@brangi , Chris Alexander (VSP F/E Tools team) has a PR open that he thinks should fix the IE11 Flipper bug -- see his [Comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17305#issuecomment-746543743) on that ticket.

**Comment by shiragoodman** [comment]
hey @mmiddaugh when did this launch?
