### ISSUE TITLE
Update special benefits and birth defects pages with 2021 rates in Drupal 

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#16933]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x] _Clone current pages and update content_

## Acceptance Criteria
- [x] _Updated rates are live and links to 2020 past rates pages are live_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

Birth defects:
2021 (main page): http://preview-prod.vfs.va.gov/preview?nodeId=993
2020: http://preview-prod.vfs.va.gov/preview?nodeId=11440

Special benefits:
2021 (main page): http://preview-prod.vfs.va.gov/preview?nodeId=990
2020: http://preview-prod.vfs.va.gov/preview?nodeId=11441

**Comment by RLHecht** [comment]
These pages are now all published. Moving to validate.

**Comment by RLHecht** [comment]
These changes are now live. Closing ticket.
