### ISSUE TITLE
Turn off jenkins missing query flag notification to #cms-team

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#16931]
## Description
Looking to turn off jenkins notifications to the `#cms-team` Slack channel when a query flag is found to be missing in the vagovprod build.

## Background/context/resources
The current notifications create unhelpful noise in the channel.

## Technical notes
examples: 
![image](https://user-images.githubusercontent.com/60702623/101175606-5dbedc80-3613-11eb-83f9-a1bc66f756bc.png)

The notification might be in the build script itself but unsure.
---
## Tasks
- [ ] identify the source of the notifications
- [ ] turn them off

## Definition of Done
- [ ] the `#cms-team` slack channel no longer receives notifications from jenkins when missing query flags are found in the vagovprod build

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by cmaeng** [comment]
@meganhkelley not sure if this is in your purview to help triage? any guidance you can give is greatly appreciated.
