### ISSUE TITLE
Find a VA Form: Post-Launch Enhancements MVP 1.0 x Collab Cycle Plan

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16930]
## Product Outline
[Link to Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md)
## Collab Point Tracker & Shared Support Spreadsheet
- [Collab Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887)
- [Shared Support Spreadsheet](https://docs.google.com/spreadsheets/d/1vjBkIF_gyjEhKArvgk3n2wyfIsUIurejpA922UoCicE/edit#gid=390831332)
## Plan
**Note:** Strikethough items not needed [per VSP review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17148).
- [x] **[Define] Kickoff-Intent** - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17148
- [x] **[Define] [Design intent](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#collaboration-format-30-minute-meeting-1)** <--Laurel already met to discuss & learned it's not currently part of Design System
- [x] **[Discover] [Usability Testing Prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#collaboration-format-30-minute-meeting-2)** - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17900 **Note**: this pertains only to the sorting feature as the connection from the search results page to the form details pages was part of the original design and just now being implemented.
- [x] ~~**[Discover] Research Plan Review**~~ <-- Team decided due to low risk this was not needed
- [x] ~~**[Discover] IA Request**~~
- [x] **[Discover] [Analytics Request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#collaboration-format-30-minute-kickoff-meeting-for-google-tag-manager)** - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17273
- [x] **[Build] [Contact Center Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#collaboration-format-asynchronous-2)** - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17927  **<-- 2 WEEKS BEFORE LAUNCH**
- [x] **[Build] [Privacy/Security Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#collaboration-format-60-minute-meeting)** - #https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/200
- [x] **[Build] Pre-Staging Review activities**
  - [ ] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md)
  - [x] Compile [QA test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)
  - [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)  https://github.com/department-of-veterans-affairs/va.gov-team/issues/17813
  - [x] [Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
  - [x] Request [QA test plan](https://dsvavsp.testrail.io/index.php?/suites/view/2&group_by=cases:section_id&group_order=asc) - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17919
- [x] **[Build] [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#collaboration-format-30-minute-meeting-3)** - #(ticket)
  - [ ] Resolve Staging Review findings - #(tickets)
- [x] **Launch - Jan 18, 2021**
- [ ] **[Validate] [Post-launch checkin](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#collaboration-format-asynchronous-4)** - #(ticket)
  - [ ] Complete [accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) in Prod - #(ticket if necessary)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket) [A11y Review steps tool](https://docs.google.com/spreadsheets/d/1xHwdyQAwbsAnD5pTHGaMxpS9XfdbBVcVVTvulgWI7dw/edit#gid=2089055656)

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [x] **Convert to an Epic**  
- [x] **Labeled with Team**

**Comment by MarciMcGuireGCIO** [comment]
Adding this to capture dependencies on other teams

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Today I am going through, researching, and dry running the Feature Toggling since I am done on Iterate Find Forms until GA adds the tags we need.

Looks like I can make sure the link does not show on Production until we are 100% ready with GA implemented on the FE and dashboard along with the Light house api flag down.

**Comment by MarciMcGuireGCIO** [comment]
That is excellent news!
