### ISSUE TITLE
Find a Yellow Ribbon School: State of the Product

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16935]
## Issue Description
Create a single point of reference to access existing documentation about Find a Yellow Ribbon School Product

---
## Tasks
- [ ] Locate all existing product overview info
- [ ] Locate all existing product technical info
- [ ] Locate existing code repos
- [ ] Create State of the Product doc that includes overview info and links to technical and product documentation

## Acceptance Criteria
- [ ] A State of the Product document will existing in the Find a Yellow Ribbon School product folder on GitHub and can be used to access all currently  existing information about the product
---
