### ISSUE TITLE
Comparative Analysis Research (Part 1)

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16936]
## Description
Audit of on-site search features on content-heavy websites.
#16936 is **Part 1** of a compendium of on-site search research and comparisons.
#18036 is **Part 2**

## Background/Context/Resources
Part 1 to focus on:
- Broad on-site search research from nngroup.com
- Research and examples of typeahead

## Tasks

- [x] Identify and summarize research from Nielsen Norman Group (search items from nngroup.com)(Sprint 37)
- [x] Create a more in-depth summary of research and examples of Typeahead (Sprint 37)
- [x] Create a draft of initial review (Sprint 37)

## Definition of Done

- [x] Draft created

**Comment by denisecoveyduc** [comment]
After discussion with @mgleo this portion has been completed
