### ISSUE TITLE
[Content] Phone Number and Text Notification Wording

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#16940]
# Issue Description

1. We plan to show facility and clinic phone numbers on the confirmation page of our form, so Veteran can contact them if they have more questions about their appointments.
- We want to link the user to the facility locator tool, so they can find more information, when 		
  - an appointment has no associated phone number or 		
  - there is an error because the code didn’t correctly handle a missing phone number  	

I spoke to VAOS about how they handle these similar use cases. I attached an image of the wording that VAOS uses (“View facility information”). I also attached an image of our use case with draft wording crafted by me. Any help on finalizing that wording would be great. 
![Screen Shot 2020-12-03 at 9.58.21 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/fcc1f18e-5d1b-4f5a-960c-e73f54a89af0)
![Confirmation - No phone numbers.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/5682ca03-382d-4de8-a0cb-87c9ede34253)

2.  We are contemplating adding the facility and clinic phone number to the “Need help?” Section at the bottom at the page as well. We would need wording  to clarify that Veterans should only contact those numbers for questions about their appointment or medical related things. Those numbers should not be used for technical problems with the questionnaire. Help crafting this additional wording would be great. 
- We would also have to account for when the facility and clinic phone number isn’t available in this section as well.   
Our current "Need help?" section:
![Screen Shot 2020-12-04 at 11.24.50 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/1bfae666-474f-4def-9842-b44a824bc6bb)

3. We are going to send out text notifications to let Veterans know that they have a questionnaire to complete. We have been in discussions with VeText to understand our options. I have a diagram describing our options. VeText requested to make the wording as short as possible.
- We can add a sentence to each default appointment reminder template. I wrote up a possible sentence, but wanted you opinion. Especially, when you review it in context of the complete text message. 

Current draft: 
To better prepare for your appointment, your provider sent this questionnaire for you to complete: https://www.va.gov/health-care/health-questionnaires/questionnaires/.
![Text.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/b9f6818e-3477-481e-980e-175d3021e374)

- We are also toying with the idea of crafting an additional text related to questionnaires. This text would only be sent if a Veteran started a questionnaire and saved their progress, but never finished it. We would send a reminder to complete this half-finished questionnaire a day prior to their appointment.

Current draft:  
You started a health questionnaire in preparation for your VA appointment on NOV 26 at 09:30.
To complete your questionnaire go to:https://www.va.gov/health-care/health-questionnaires/questionnaires/.
For more info call 909-825-7084 options 2 or reply HELP.
Send STOP to end messages.  
![Texting Notification Strategy.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9be30d56-b33b-423a-9bc4-3c41a676383b)

# Tasks
- [ ] Work with Kristen to answer any questions, etc as content is crafted

# Acceptance Criteria
- [ ] Final content sent to Kristen
- [ ] Wireframes updated
- [ ] Phone number content changes added to #16039.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell Please see recommendations below for the health care questionnaire phone and text content: 

a note about this one, this link is different than VAOS, as I wanted to not use "view". I'll actually be asking VAOS to update their link. 

**What if I have questions about my appointment?** 
If you have questions about your upcoming appointment, please call your VA health facility. [Contact your health facility](links to? 


------

2. Need help? update footer content: 

For questions about your appointment or if you have a health-related concern, call your VA health facility. [Contact your health facility](links to?

For questions about how to fill out your health care questionnaire or if you need help with the form, please call our MYVA411 main information line at 800-698-2411[hyperlink] and select 0. We’re here 24/7. 
If you have hearing loss, call TTY: 711[hyperlink}

-----------

3. Text notification updated content:

To help us better prepare for your appointment, please fill out this questionnaire from your provider 
https://www.va.gov/health-care/health-questionnaires/questionnaires/.


-------


4. Text notification for unfinished questionnaire: 

You have an in-progress health questionnaire for your VA appointment on {date}. To finish filling out this questionnaire, go to: https://www.va.gov/health-care/health-questionnaires/questionnaires/.
For more information, call {phone number}

**Comment by kristenmcconnell** [comment]
**Scenario 1 & 2**
So "Contact your VA provider" would sometimes link to the VA facility locator?

If we do have clinic and facility phone numbers, then I assume the text would be: 
**What if I have questions about my appointment?**
If you have questions about your upcoming appointment, please call your VA provider. Contact your VA provider at the [facility name] at XXX-XXX-XXXX or the [clinic name] at XXX-XXX-XXXX.

or could the text be...

If you have questions about your upcoming appointment, please call your VA provider. Contact the [facility name] at XXX-XXX-XXXX or the [clinic name] at XXX-XXX-XXXX.

**Scenario 3**
I do like that wording. My original wording which VeText reviewed was 168 characters. They asked if we could shorten it. Your new wording is 170 characters. Thoughts on this?

**Scenario 4**
Looks good. I think we are ok on character count with this, since questionnaires is the focus of this text message. They just worry about the other scenario, because it is already so long.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell sorry, I didn't check the character count! will drop in a shortened version after our meeting.

**Comment by peggygannon** [comment]
@kristenmcconnell here's additional recommendations, based on your questions. Let me know if you have questions! 


Scenario 1 & 2
So "Contact your VA provider" would sometimes link to the VA facility locator? Yes, that is correct. Sorry i should have broken out the two different use cases: 

Here's recommended content if there is no phone number/facility to show dynamically: 
 
**What if I have questions about my appointment?**
If you have questions about your upcoming appointment, please call your VA provider. [Contact your VA provider](links to facility locator]

If we do have clinic and facility phone numbers, then: 

**What if I have questions about my appointment?**
If you have questions about your upcoming appointment, please call your VA provider. You can contact them at [facility name or clinic name] at XXX-XXX-XXXX[hyperlink phone number]. 


-----

Scenario 3 update: 
To help us prepare for your appointment, please fill out this questionnaire from your provider 
https://www.va.gov/health-care/health-questionnaires/questionnaires/.

**Comment by kristenmcconnell** [comment]
Great. Thanks. This looks good. I'll make the changes.

**Comment by kristenmcconnell** [comment]
Everything has been added. Closing story on my end.
