### ISSUE TITLE
Map displays area searched, even if no results found 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16945]
As a Veteran, I want the map to display the area I entered, even if no results are found.
As a Veteran, when no results are found, I want to be able to zoom out and search again.

E.g.:
1. search for Oral & Maxillofacial Surgery in Poulson, MT
2. Map zooms to Poulson, MT. no results found,
3. Click Zoom Out control a few times and pan West until Cour d'Alene appears. "Search This Area" button appears.
4. Click "Search This Area" button. Results are shown in list view.

Notes: 

1. Veteran may need to zoom out to see the results when using the "Search This Area" button, because we are not using "fitBounds" in that case. We may want to change this.

2. Update the no results found message as follows:

![Locator_No_Facilities_Msg](https://user-images.githubusercontent.com/80267/103243365-a7a39580-4927-11eb-83fc-057460a8af2f.png)

## Tasks
- [x] refactor and modify code as needed to achieve acceptance criteria with high code quality

## Acceptance Criteria
- [x] map displays the area entered, even if no results are found.
- [x] when no results are found, after zooming out or panning the map, the "search this area" button appears
- [x] clicking the "search this area" button sends a radius determined by the new map bounding box
- [x] new messaging is displayed when no results found
- [x] unit tests are added to cover new code
- [x] no new bugs are introduced
- [ ] skipped cypress tests are un-skipped and pass reliably

**Decision:** Flyover animation is not necessary for the secondary search map display

**Comment by mmiddaugh** [comment]
@chrisdlogan @lildziner will you please add a recommendation for the appropriate error message to display if no results are found? (with content input as needed)

**Comment by mpelzsherman** [comment]
@mmiddaugh I removed this item from the AC since it isn't an acceptance criteria.

- [ ] Flyover animation is not necessary for the secondary search map display

We can discuss next week.
