### ISSUE TITLE
Process 10-10CG Attachments in a background job

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#16952]
**Description**:
Create a background job to process the attachment(s) on Form 10-10CG Submissions. This should allow us to reattempt the delivery of attachments when the PDF generation fails or there is a network failure.
- [x] [Prerequisite] Persist Form 10-10CG Submissions https://github.com/department-of-veterans-affairs/va.gov-team/issues/10280
- [x] Create the Background Job (and update the From1010cg::Service) https://github.com/department-of-veterans-affairs/va.gov-team/issues/17204
- [x] Schedule the job at the time of submission https://github.com/department-of-veterans-affairs/va.gov-team/issues/17205

**Business Context**:
Although the original purpose for sending the PDF was for convenience, the Caregiver Program clarified that attachment is an absolutely critical component of processing the application and even refer to it as the historical record (the source of truth of what data was sent at the time of submission).

**Considerations**:
Since we have plans to improve API response times and we expect to send additional attachments, I think it's best to persist  it and let Sideqik do its thing rather than a [hardcoded re-attempt](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15147) (which would likely resolve the [cases of dropped attachments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14429)).

We will still send the submission data to CARMA inside the req/res cycle. Ensure that failure to save the claim / submission or trigger the background process does not display an error to the user, at that point the submission was accepted.

**Prerequisite**
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/10280

**Relates to**:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/14429
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/16888

**Comment by kevinmirc** [comment]
Completed.
