### ISSUE TITLE
ATO - Action items from retro and upcoming tasks

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16956]
## Issue Description
_This epic is for tracking actions items that came out of an ATO retrospective meeting held w/ Nancy Smith, Faith Owusu-Sekyere, and other members of the VSP Operations team. The purpose is to track relevant action items and potential upcoming tasks related to the outcome of that meeting, as well as work that we will need to schedule in the near future._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] _Get Demian access to EMASS system_
- [ ] _Create better plans + tickets for ATO moving forward in advance of the work needing to be done_
- [ ] _Ensure to communicate the priority and importance of ATO to DEPO leadership so that we have reliable and significant resources allocated to this work_
- [ ] _Nancy can get additional training information and/or definitions from NIST and background information that might helps us understand better what ATO office is actually looking for_
- [ ] _Create a better mapping/translation between what's being asked, and what can be provided, based on the actuality of the infrastructure and services running on the platform system vs the NIST standards / definitions_
- [ ] _Explore notifications / updates around changes to the system that can inform updates to ATO documentation or compliance requirements_
- [ ] _Explore better tooling / reporting that informs our response to ATO requirements_
- [ ] _Faith to share presentation for ATO with Operations team_
- [ ] _Annual Contingency Plan Test or Incident Response Test  Exercises. The last one was performed in December 2019 and these table top exercises have to be performed annually. We will discuss more into details during Sprint Planning (needed by end of Jan or Feb)_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story? (TBD)_
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
These were notes from retro in 2020 about potential improvements to the internal processing of ATO-related tasks. 
There have been a number of changes and team re-org since that time, though this may be useful for future reference. 

This issue can be closed.
