### ISSUE TITLE
Redeploy EBS resources to ensure all volumes are encrypted

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#16958]
## Issue Description
Default encryption is already enabled at the account level, so a simple re-deploy of any of those resources should do the trick.

---
## Tasks
- [x] Audit EBS volumes and attach a list of unencrypted volumes to this ticket
- [ ] Re-deploy EBS volumes that are currently un-encrypted
- [ ] Ensure that EBS volumes are re-attached as needed after being re-deployed

## Acceptance Criteria
- [ ] All EBS volumes (that can be encrypted) will be encrypted

**Comment by dginther** [comment]
@jsev-io to run audit of EBS volumes, create a ticket with a list of any that are not encrypted.

**Comment by jsev-io** [comment]
resourceId | resourceType | configuration.volumeType | tags | configuration.availabilityZone | configuration.encrypted
-- | -- | -- | -- | -- | --
vol-03831c2a1c57f2467 | AWS::EC2::Volume | gp2 | 20 items | us-gov-west-1a | false
vol-04b984a4f3040fce4 | AWS::EC2::Volume | gp2 | 15 items | us-gov-west-1a | false
vol-06b7962667abb5333 | AWS::EC2::Volume | gp2 | 20 items | us-gov-west-1a | false
vol-06d58c4a627c8a931 | AWS::EC2::Volume | gp2 | 20 items | us-gov-west-1a | false
vol-07caffc8418f2f7cc | AWS::EC2::Volume | gp2 | 20 items | us-gov-west-1a | false
vol-08694fcf5354a2eff | AWS::EC2::Volume | gp2 | 20 items | us-gov-west-1a | false
vol-09554bb3227864b91 | AWS::EC2::Volume | gp2 | 3 items | us-gov-west-1a | false
vol-0bd649b089158970d | AWS::EC2::Volume | gp2 | 15 items | us-gov-west-1a | false

**Comment by jsev-io** [comment]
Above is an audit of the remaining unencrypted volumes within the account.

**Comment by jhouse-solvd** [comment]
@jbritt1 - When you have time, and with your recent work around tagging EBS volumes, could you take a look at this and investigate whether or not it's still necessary? thanks in advance for your help, sir.

**Comment by jbritt1** [comment]
> @jbritt1 - When you have time, and with your recent work around tagging EBS volumes, could you take a look at this and investigate whether or not it's still necessary? thanks in advance for your help, sir.

These are still the final remaining unencrypted volumes: 
![image](https://user-images.githubusercontent.com/56260532/129356834-dc6f6a29-6d14-4c95-bf97-42bdb1344897.png)

**Comment by jbritt1** [comment]
The one with no name here belongs to an Appeals owned box:
![image](https://user-images.githubusercontent.com/56260532/129357073-5f027f26-8d0e-4cac-94f4-2be009f2e8da.png)

**Comment by jbritt1** [comment]
> @jsev-io to run audit of EBS volumes, create a ticket with a list of any that are not encrypted.

It seems Julian was supposed to have created a spin off ticket for us to tackle these, but was perhaps not done? Just glancing at it, I am unsure on the LOE it will take to encrypt these volumes as the Prometheus ones persist from deployment to deployment. Perhaps as we move away from Prometheus this issue will solve itself. Then we will just be left with two remaining unencrypted EBS volumes. One not owned by VSP-Operations, and one for Sentry.

**Comment by jbritt1** [comment]
Waiting for decommission of remaining VSP-Operations owned items for the last few non-encrypted volumes observed above. Slack thread for tracking: https://dsva.slack.com/archives/CJYRZK2HH/p1628870563279000
