### ISSUE TITLE
[Design] My VA: Finalize wireframes presentation of health care blocks

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#16966]
## Background

Epic #16807

Post-testing design exploration A and design exploration B, we have decided to move forward with a more traditional dashboard approach instead of a newsfeed approach. We're ready now to finalize the wireframes for each section. This ticket covers the health care blocks.

### Which blocks?

We need to show next upcoming appointment, secure messages, prescription refills, and additional links. Whether those are four separate blocks or all under one "health care block" is up to you.

### Next appointment

This needs:

- [x] Title
- [x] The appointment block (I know you all have a working group working on this, but unless things have changed drastically, you can probably copy/paste the upcoming appointment block from the prototype)
- [x] A link to view all appointments
- [x] Blank state (no upcoming appointments)

### Secure messages

This needs:

- [x] Title
- [x] A sentence saying these are unread or recent (last 30 days) messages (we should discuss and define exact logic here)
- [x] Up to 2 - 3 unread or recent messages
  - Sender
  - Title
  - Date or timestamp (we should confirm what we can get)
- [x] A link to view all messages
- [x] Blank state (no new or recent messages in the last 30 days)

### Prescription refills

This needs:

- [x] Title
- [x] A sentence saying these are prescriptions in the process of being refilled (we should discuss and define exact logic here)
- [x] Up to 2 - 3 unread or prescription refills
  - Prescription
  - Dose
  - Status (Submitted or Filled)
  - Date or timestamp (we should confirm what we can get)
- [x] A link to view all prescriptions
- [x] Blank state (no refills in the last 30 days)

### Additional links

This is already mocked up in the prototype and we can just carry that over.

- View lab and test results
- Find a VA facility
- Get your VA medical records

## Tasks

- [x] Mock up appointment block; Share, review, and finalize
- [x] Mock up secure messages block; Share, review, and finalize
- [x] Mock up prescription refills block; Share, review, and finalize
- [x] Mock up additional links block; Share, review, and finalize

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
Here is the first wire for healthcare, I kept every thing in boxes for the most part and will revisit that in the design phase. Let me know your thoughts. Thanks! 😊

![myVA mobile Traditional Dashboard V4](https://user-images.githubusercontent.com/68560244/101673206-baebd100-3a0b-11eb-884c-ab5e97d9d204.png)
![myVA mobile Traditional Dashboard - Blank State - V4](https://user-images.githubusercontent.com/68560244/101673223-bf17ee80-3a0b-11eb-94cf-db5c08c2eb4e.png)

**Comment by Samara-Strauss** [comment]
Thanks for this! Here are my thoughts so far:

**Secure messages**

- Since these are just messages within the last 30 days, I would mention that.
- Is it safe to assume you're planning on showing this as a table? I think that works for this information. One alternative I would consider is showing them in "preview"-like state like you did for claims. Since people are used to seeing patterns like the one below, I think we could play with a design where we show subject/sender/date without the field labels (though we would use aria labels for screen readers). But this not required, and I'll leave that call up to you. Just something to mull over:

<img width="265" alt="Screen Shot 2020-12-09 at 3 00 29 PM" src="https://user-images.githubusercontent.com/34068740/101681078-9f92bd00-3a2f-11eb-8e4d-ef069492db19.png">

**Prescriptions**

- Since we have moved away from the notification style, I would make the info structure more like the precedent we've set in the claim section. I think the structure could be like this:

**Metformin, 500mg**

December 9, 2020: Your prescription was submitted for refill.

- Alternatively, you could consider showing these in a table view if that's what you go with for messages.
- As a refresher, there will be two statuses: the submitted-on date, and the date the prescription was filled.
- Up to how many prescriptions would we show here? Is it safe to assume no more than 3?
- Since the logic for this is that we would show any prescriptions that have been filled in the last 30 days, this might be a good place to clarify that we are showing them some, but potentially not all, data. So "You have refilled 6 prescriptions in the last 30 days. Here are the top 3." Of course, keep in mind that this may not be the case, so whatever copy or structure we use needs to account for someone refilling 1 prescription in the last 30 days or someone refilling more (even if we only show up to 3).

**Blank states**

- For appointments, I think those two CTAs would ultimately go to the same place, so I would just keep the same CTA as the non-blank view.
- Messages: Same thing — these CTAs would go to the same place, so just use the same CTA as the non-blank view.
- Prescriptions: Again, same as the above — these CTAs would go to the same place, so just use the same CTA as the non-blank view.
- For both messages and prescriptions, for both blank and non-blank view, please mention we are showing info for the last 30 days.

Also, if you use link CTAs in the non-blank view, please don't change them to button CTAs in the blank view. This would be annoying to code and I think the inconsistency is weird from a UX perspective.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
I've just made the above updates. I agree we should think about how to show the messages and prescriptions in the design phase (grid vs. blocks) and to consider how each approach would lay out on mobile vs desktop so I'll leave those for later. Any way let me know your thoughts. Thanks :)

![myVA mobile Traditional Dashboard V4](https://user-images.githubusercontent.com/68560244/101696222-a3701080-3a2a-11eb-8e61-f73fd8e460fa.png)
![myVA mobile Traditional Dashboard - Blank State - V4](https://user-images.githubusercontent.com/68560244/101696242-a965f180-3a2a-11eb-9777-1540af350ac6.png)

**Comment by Samara-Strauss** [comment]
> I agree we should think about how to show the messages and prescriptions in the design phase (grid vs. blocks) and to consider how each approach would lay out on mobile vs desktop so I'll leave those for later.

That sounds good to me, but this should definitely be resolved *before* moving on to the visual design. Once we move on to the desktop wireframes, we can figure out if we want to take a table vs. block approach for messages and prescriptions.

**Prescriptions**

- The hierarchy of information here doesn't make sense to me. Can you please change it as follows:
  - Prescription & dose
  - Submitted on
  - Filled on
- Also, FWIW, I've been thinking — IMO, the most important pieces of info are the prescription, dose, and whatever the status is. So "submitted on" is the initial status, but once a prescription has been filled, the submitted on date doesn't really matter anymore. So that's why I think this structure most clearly communicates the most important information:

> **Metformin, 500mg**
>
> December 9, 2020: Your prescription was submitted for refill.

Or 

> **Metformin, 500mg**
>
> December 10, 2020: Your prescription was filled by the pharmacy.

In a table, this could be something like:

|Prescription| Status|
|-----|-----|
|Metformin, 500 mg | Filled on December 10, 2020|
|Warfarin, 1mg| Submitted for refill on December 8, 2020|

**Appointment**

- Just making sure — is all the data we need in this block represented? I know there was some feedback on wanting more information here in user research, but I'm relying on you guys to know what that data is *and* if we actually have access to it (ie. does it exist in the VAOS tool). If we have all the data we can represent, then I'm also trusting that you all are showing whatever information/structure you've talked about with other folks who are also working on displaying appointments. I know that you've been part of discussions on this, but since I haven't, I'm relying on you all to carry over conclusions from those discussions.

**Blank state**

Looks good to me!

----

I think with the updates/comment above, this will probably be finished today. You can move on to the Apply for benefits section after this, and then I'm going to have you start desktop iterations immediately following. I would love to have a solid desktop direction before you both leave for winter break so we can start immediately on the visual design when you get back.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
We met with Petter Russo today from VAOS to confirm what data points we can show for appointments. He said that some appointments can show appointment type "primary care, eye" etc but others cannot. Also he is getting confirmation on the exact data points we can show by end of this week and we will update the mock ups accordingly. We felt like showing "canceled" appointments was crucial for the overview page so I included that in this wire. I also changed the appointment title to: "My appointments" to include the canceled state.
Also, Jennifer with accessibility pointed out that the appointments should be a list instead of individual buttons since they all link to the same page and not individual appointments.

For prescriptions we thought that changing the intro text to: "You have 4 prescription updates in the last 30 days:" solved the problem users were having understanding if their appts were being filled or already filled. 

Any way let me know your thoughts. Thanks! 


![myVA mobile Traditional Dashboard V4](https://user-images.githubusercontent.com/68560244/101831736-3c666080-3aeb-11eb-9b9d-e2d4d83dee49.png)
![myVA mobile Traditional Dashboard - Blank State - V4](https://user-images.githubusercontent.com/68560244/101831744-3ff9e780-3aeb-11eb-95ac-3cf7b4c8111b.png)

**Comment by Samara-Strauss** [comment]
**Appointments**

> We met with Petter Russo today from VAOS to confirm what data points we can show for appointments. He said that some appointments can show appointment type "primary care, eye" etc but others cannot. Also he is getting confirmation on the exact data points we can show by end of this week and we will update the mock ups accordingly. 

Great! That's great news.

> We felt like showing "canceled" appointments was crucial for the overview page so I included that in this wire. I also changed the appointment title to: "My appointments" to include the canceled state.

OK, I know that people found the "canceled" update useful in testing, and I agree that it's important in general to let people know if an appointment is canceled. However, I'm skeptical that changing the whole direction of this block *just* to accommodate the "canceled" use case is the right move. I have a few reasons for that:

1) Ultimately, I think the most timely update is when your next appointment is, so that's a much stronger thing to feature on this page than a list of appointments (which people can easily see in the VAOS tool).
2) We don't know how often appointments get canceled or how problematic canceled appointments are, so it feels weird to me to change the whole design to accommodate the  "canceled appointments" use case. Is canceling something that happens to people all the time? Is it common? Is it something that happens super rarely? 
3) Also, what else do we know about how cancelations are communicated? Are there phone calls? Is the VAOS team planning for email or text notifications? Is the My VA dashboard the place people would go to see this?
4) Finally, again, I agree this is an important thing to communicate to someone, but I could see it fitting readily into a notification center once we eventually have something like that on VA.gov.

So, my conclusion is this: my problem is **not** that there could potentially be a "canceled" status or appointment shown on the dashboard given that people in testing said that they thought that was a helpful notification. My problem is that we changed the whole design of this section to accommodate what may or may not be an outlier case, or what might be handled better as a notification elsewhere (phone/email/text/notification center). Without having more information that canceled appointments are a huge issue or frequent occurrence, I don't feel like the design rationale is strong enough to have changed this from "your next appointment" to a list of appointments. 

That being said, that's what I think, and ultimately, I am going to leave this call up to you. If you think it over and still feel strongly that the list direction is stronger from a UX perspective than the "next appointment" direction, we can pursue that going forward.

**Messages and Prescriptions**

These are both looking much stronger! Nice job!

> For prescriptions we thought that changing the intro text to: "You have 4 prescription updates in the last 30 days:" solved the problem users were having understanding if their appts were being filled or already filled.

Makes sense!

**General**

- A note on mock data: Mock data communicates functionality, so it's confusing when you copy and paste the same details for each appointment/message/prescription. This is an opportunity to communicate things like hierarchy. For example, I assume that appointments are shown chronologically, and prescriptions and messages are shown in reverse chronological order, but I can't know for sure since all the mock data is the same. Using your design to communicate that stuff is super helpful for me as I write documentation and to Erik/Sandra as they are building so that the mockup reflects the documentation. So, my request here is to make the dummy data vary in each block (yes, even names and message subjects, basically anything that's **not** a standardized status), and make dates reflect the order you expect the update blocks to show in.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
I have updated the mock content with long names and chronological dates. The reason we changed the format on the appointment section was to reflect what the VAOS team had mocked up for mobile. I have attached a copy here to take a look at. It will most likely change when they get further on data points but we wanted to keep the user experience consistent if that makes sense. Let me know your thoughts. Thanks! :)
![VAOS-apptcards Copy](https://user-images.githubusercontent.com/68560244/101938938-18f9ef00-3b99-11eb-9267-53112386fb6c.png)
![myVA mobile Traditional Dashboard V4](https://user-images.githubusercontent.com/68560244/101939027-3af37180-3b99-11eb-933b-15ef70771aa1.png)

**Comment by Samara-Strauss** [comment]
> The reason we changed the format on the appointment section was to reflect what the VAOS team had mocked up for mobile. I have attached a copy here to take a look at. It will most likely change when they get further on data points but we wanted to keep the user experience consistent if that makes sense. Let me know your thoughts. Thanks! :)

Totally make sense. Thanks for clarifying! This additional context is helpful, and of course we want to be consistent with how this information is shown across the site.

**Appointments**

- Appointments should be shown in chronological order, not reverse chronological order. That's because the first appointment in the list should be your next appointment, and also, you don't need to show past appointments on here, just upcoming. So please update the dates so these reflect chronological order.
  - **Prescriptions and messages are fine in reverse chronological order**, so don't change those. For those, we want to show most recent update first, so the rules/mental models there are a little different.
- Also, if it fits, can we change the label to "My upcoming appointments"? If that goes to two lines, then we don't need to change it.

Otherwise, this looks great and ready to ship! Once these updates are done, this ticket should be good to close!

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
I just made those last two edits and will move onto desktop next :) 

![myVA mobile Traditional Dashboard V4](https://user-images.githubusercontent.com/68560244/101944310-61b5a600-3ba1-11eb-9fb4-7d7c80740cb9.png)
![myVA mobile Traditional Dashboard - Blank State - V4](https://user-images.githubusercontent.com/68560244/101944323-69754a80-3ba1-11eb-97b5-bee09a684bdc.png)

**Comment by Samara-Strauss** [comment]
Great! Closing!
