### ISSUE TITLE
[Design] My VA: Finalize wireframes presentation of applying for benefits section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#16967]
## Background 

Epic #16807

Post-testing design exploration A and design exploration B, we have decided to move forward with a more traditional dashboard approach instead of a newsfeed approach. We're ready now to finalize the wireframes for each section. This ticket covers the applying for benefits section.

### Applying for benefits

At this point, I think we can move over what we have in the prototype as-is, pending any updates you'd recommend coming out of user. One I would recommend is adding a sentence that explain these applications have been started but need to be completed/submitted before they expire since people seemed confused whether these applications had been submitted already or not.

As a refresher, this is what this should include (but again, this is almost all in the prototype already):

- [x] Section title
- [x] A sentence explaining these applications have been started but need to be completed/submitted before they expire.
- [x] Blocks for open applications
  - Title
  - Form #
  - Expiration date
  - Last opened
  - Link to form
- [x] A "What benefits does the VA offer" FAQ

### First time user experience

I have a very lightweight first-time experience I think we can incorporate into this section, but we can save that for another sprint if we find we're short on time. It would make it so we don't really have a "blank" state for this section, so let's worry about that later.

## Tasks

- [x] Mock up applying for benefits section; Share, review, and finalize

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
This one is pretty much what we had on the last mock with the addition of the intro text and I changed the wording in the link. Let me know your thoughts. thanks!
![myVA mobile Traditional Dashboard V5](https://user-images.githubusercontent.com/68560244/101940422-51023180-3b9b-11eb-8ed8-a3f39c9a0583.png)

**Comment by Samara-Strauss** [comment]
This is fine, I don't have any additional changes. Unless Tressa has some other feedback from what came out of testing, I would say this is good to go!

**Comment by callen2563** [comment]
Ok, great!! I know Tressa had seen this last night so we are good to go then. 👍🏼

**Comment by Samara-Strauss** [comment]
Great! Then we can close this.
