### ISSUE TITLE
[Design] My VA: Finalize wireframes of disability rating & claim status blocks

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#16964]
## Background

Epic #16807

Post-testing [design exploration A](https://vsateams.invisionapp.com/share/EDZFDJ7UWTC#/screens/437719085_myVA_Mobile_A) and [design exploration B](https://vsateams.invisionapp.com/share/HDZFDLY3WEZ#/screens/438177954), we have decided to move forward with a more traditional dashboard approach instead of a newsfeed approach. We're ready now to finalize the wireframes for each section. This ticket covers disability rating and claims an appeals status.

### Disability rating

As a refresher, this is what we need for the disability rating block

- [x] A title 
- [x] The overall disability rating
- [x] A link to view all ratings

### Claim status block

As a refresher, for the claim status block, this is what we need:

- [x] A title
- [x] A sentence that explains that these are the claims that have been updated in the last 30 days (note: this is not in the original data spreadsheet but I think we need a clarifier so people understand what we are showing them)
- [x] Showing up to 2 or 3 of the most recently updated claims. This needs to include:
  - the claim title
  - the status
  - a link to view
  - a date or timestamp (let's check to see how this is shown on VA.gov)
- [x] A link to view all claims
- [x] A secondary link to file a claim
- [x] Optional: The number of all open claims and appeals (note: this can be one number instead of 2)
- [x] A blank state — do we show this block if you don't have claims within the last 30 days?

## Tasks

- [ ] Mock up disability rating block; Share, review, and finalize
- [ ] Mock up a claim status block; Share, review, and finalize

**Comment by tressaellen** [comment]
I'm dropping this link in here from the claims folks so it doesn't get lost in slack. :) https://dsva.slack.com/archives/C5AGLBNRK/p1596741886253000

**Comment by Samara-Strauss** [comment]
@tressaellen thank you for that! That's really interesting — I hadn't seen that convo before. One thing to note is even for the people who have a crazy amount of claims, they likely aren't going to all get updated at the same time, and even if they magically did, we don't need to show them all on the dashboard. In other words, we don't need to accommodate showing 32 claims on the dashboard even if someone had that many and even if they all got updated at once (which wouldn't happen, but for the sake of hypotheticals...).

**Comment by callen2563** [comment]
I mocked up "3 claims in progress in the last 30 days" since the data showed that 6 was the average but they didn't have any data showing how many claims were typically processed in a 30 day period.

**Comment by Samara-Strauss** [comment]
@callen2563 sends good. Remember, the average of 6 claims is not 6 claims that have been updated in the last 30 days. In fact, it was unclear to me whether that was an average of 6 open claims, or 6 claims total (so some might be open and in progress, while others have been fully adjudicated and closed). So, that's all to say I think showing 3 updated claims at most is fine, but we shouldn't be worried that users will be missing out if we don't show them more than that.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
Hi Samara, 
Here are 3 mockups: 1 traditional dashboard with 2 blank state options. I'd love to get your thoughts on the last blank state option for users who have never filed a claim and don't have a disability rating. Does it make sense to show it like this or should we not show the disability rating at all?

![myVA mobile Traditional Dashboard](https://user-images.githubusercontent.com/68560244/101404937-2dce3e00-388c-11eb-9dcd-7ab0167c6223.png)
![myVA mobile Traditional Dashboard - Blank State - No Current Claims](https://user-images.githubusercontent.com/68560244/101404941-30c92e80-388c-11eb-928f-543b042b7ea4.png)
![myVA mobile Traditional Dashboard - Blank State - No Claims](https://user-images.githubusercontent.com/68560244/101404948-3292f200-388c-11eb-8cfe-b1baa973d866.png)

**Comment by Samara-Strauss** [comment]
Hey! This is a really great start :D :D :D 

**Disability rating**

- This is pretty straightforward, and not much to change here. For the "disability rating" after "40% disability rating", can you change that to "service connected?" We'll work out the final copy with Peggy or another content person, but being "service connected" is the term used for whether a disability has been deemed related to service or not. If that ends up not being appropriate (our content folks will know best), then I would say we could just leave out that copy altogether.

**Claim status**

- I know we are only wireframing at this point, but I also think this design feels really close to what we already have, which feels really clunky on desktop. Let me know if you're already thinking ahead to make this more streamlined with the visual design — you might be, and I don't want to assume anything because we're in the wireframe phase. But, I do want to point out that we don't have to exactly copy the blocks that are there now design-wise, and I want us to take a risk and try to move this forward so things aren't so weighty and clunky. That being said, here are some ideas I have about how we could make this more streamlined:
  - Show the "Updated" date as a timestamp or label style or something instead of as part of the claim title (note: we will need to confirm we can pull in the date separate from the title of the claim, but I think we can based on how [the updated on date is shown on the claim status tool](https://staging.va.gov/track-claims/your-claims).
  - I would consider removing the "submitted on" date. We'll want to ask about this in our final round of usability testing, but this feels less important to me for the dashboard preview of the claim (more important for the claim detail once they click in).
  - I would reduce the heading for each claim title to one heading size down (so if this is H3, change to H4). Right now, it appears to be the same size as the "Claim and appeal status" heading. 
  - Change the individual "View claim" CTAs to links; change the main "View all claims" to a button"; Change the secondary "File a claim for compensation" CTA to a link.
- Overall — and this is not scientific at all — my goal would be to have those claims blocks we currently have on My VA be about half the height they are now, if we plan to stack them vertically on *desktop* (so this gets ahead of the mobile 'frame, but can help us think through mobile). If you plan to show them as squares side by side, I still think we can go more streamlined, but then vertical height is less of an issue.

**Blank states**

- For disability rating, we don't need to show this block at all if they have no rating.
- For claim status... I could see us doing a couple of things:
  - Always show this block if you have any claims in progress, even if none have been updated in the last 30 days (so this warrants the blank state you designed above). But if you have 0 claims in progress (either none started or all closed), we can hide this block.
  - Only show this block if a claim has been updated in the last 30 days, but hide otherwise even if you have claims in progress.
- I am leaning towards the first option. If we go with the first option, I would change the CTAs in the blank state to be the same as the state with claim updates (so "View all claims and appeals" and "File a claim for compensation").

Let me know if you have questions! Looking forward to the next round of updates :)

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
I made the updates (design finessing to come later ;).. I removed the "Issue on review" and "Submitted on" as I felt that I felt it was a bit too much info on mobile and they can get those details once they click the claim. Maybe we can show more details on desktop vs mobile. Any way let me know your thoughts. Thanks! :)  

![myVA mobile Traditional Dashboard V2](https://user-images.githubusercontent.com/68560244/101514684-645e9400-3932-11eb-9abb-cc31c4f102a8.png)
![myVA mobile Traditional Dashboard - Blank State - No Current Claims](https://user-images.githubusercontent.com/68560244/101514701-69234800-3932-11eb-9441-c4fa2e7cff6f.png)

**Comment by Samara-Strauss** [comment]
This is looking really good!

**Claim and Appeal status**

- Can we change the block title to "Claim and appeal status updates"? I think that could help clarify that this is meant to show updates. If "updates" fits in the title while keeping it on one line on mobile, I think we should make that change (the content team, of course, will have final say).
- Can you bold "3" in "You have 3 claims or appeals..."? I think this will help call out this number and also indicated that it's dynamic. Content may choose to remove that emphasis, and we can follow whatever guidance they provide.
- For the updated on date, when I said showing it as a timestamp or label, I meant something like this (btw this is a totally random screenshot I got from an article, so none of this is real info :)):

<img width="651" alt="Screen Shot 2020-12-08 at 12 34 42 PM" src="https://user-images.githubusercontent.com/34068740/101520176-18bbe280-3952-11eb-8b46-01a0e04fae6f.png">

- That being said, I wonder if the date would actually take up **less** space if you just kept it as part of the title like it is now/like you had it in your original mock. Could I see a mockup with the date back as part of the title, and one with maybe more of a "timestamp" style like in the screenshot above (note: we obviously don't have exact timestamps; just showing the month/day/year is fine)?
- Otherwise, the claim status block updates look great! Moving the title to an H4 looks great, and I agree with the call to remove "Issues on review" in addition to "Submitted on". This helps reduce the overall heaviness of these blocks while also still delivering important info.
- Can you flip the order of the main CTAs in this block? The "View all claims and appeals" button should appear on top, with the secondary "File a claim for compensation" CTA below it.

**Claim and appeal status blank state**

- This was a little closer in V1 you posted yesterday. Let's make the following updates:
  - Go back to the original copy you had "You have 0 claims or appeals that have been filed in the last 30 days."
  - Main CTA - "View all claims and appeals" button 
  - Secondary CTA -  "File a claim for compensation" CTA below it.

Reminder: the logic for the blank state will be to show this state if they have claims and appeals in progress, but no updates in the last 30 days. We will *not* show this if they have never filed a claim or if all claims are closed.

**Comment by Samara-Strauss** [comment]
One other idea for the claim status date (but we'd need to check there were no issues with this from an accessibility perspective):

Higher-level review for disability compensation

**September 03, 2020**: A senior review is taking a look at your case

View claim >

**Comment by callen2563** [comment]
@Samara-Strauss Here are the updates, I really like how the date looks with the status update but let me know what you think. 
![myVA mobile Traditional Dashboard V3](https://user-images.githubusercontent.com/68560244/101527016-4f89fc80-3942-11eb-8c01-6dbbe4dea9b4.png)
![myVA mobile Traditional Dashboard - Blank State - No Current Claims V2](https://user-images.githubusercontent.com/68560244/101527023-51ec5680-3942-11eb-95a8-d222a11ef244.png)

**Comment by Samara-Strauss** [comment]
This is great! I agree — I like how the date + status look together. That makes a lot of sense to me.

One final thing — the secondary "File a claim for compensation" CTA in the blank state should be a link, not a button, so it matches the state where there are claims.

Otherwise, unless @tressaellen has additional thoughts, I would call this done! Once you make the update to the blank state CTA, we can close this out. 😃

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen 
Awesome! 👏  Here is the updated blank state I replaced that button with the link.. 
![myVA mobile Traditional Dashboard - Blank State - No Current Claims V2](https://user-images.githubusercontent.com/68560244/101528669-721d1500-3944-11eb-8e90-66004de2a10d.png)

**Comment by Samara-Strauss** [comment]
Looks good!
