### ISSUE TITLE
Improve web performance on vets-website & vets-api

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#16961]
## Issue Description
This is a request to improve web performance on VA.gov by making the following improvements to reduce latency:
- Use Brotli as a primary compression algorithm with GZIP as a backup ([14% smaller than GZIP](https://expeditedsecurity.com/blog/nginx-brotli/)).
- Work with External Service Provider teams (like eAuth/IAM) to investigate using compression (ie eAuth is serving up the full uncompressed resources like jQuery and jQuery UI).
- Work with IAM team to minify their `common.js` file & images.
- Resize/compress images and SVGs efficiently.

This document [Latency within the Login-flow (using ID.me).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5645393/VA.gov.-.ID.me.workflow.-.Latency.Document.-.ID.me.Workflow.pdf) was my analysis on latency of resources during the ID.me login flow which consists of redirects between (VA.gov, ID.me, and eAuth).

## Tasks
- [ ] Nginx is configured to use Brotli first with GZIP as a backup
- [ ] IAM team uses Brotli/GZIP compression, minifies any JS, purges any unused CSS
- [x] Appropriate cache policy for fonts and images on vets-website

## Acceptance Criteria
- [x] Nginx is configured to use Brotli first with GZIP as a backup
- [ ] IAM team uses Brotli/GZIP compression, minifies any JS, purges any unused CSS
- [ ] Reduce size of images on vets-website
- [ ] Latency is reduced by systematic improvements

**Comment by cvalarida** [comment]
Any way you can convert that PDF file into something safer to consume? (I'm perhaps paranoid, but opening a PDF from a GH ticket makes me nervous.)

**Comment by AGarcia-Clarity** [comment]
@cvalarida Sure. Which format would you prefer?
