### ISSUE TITLE
Covid Dashboard - Iterate on Covid Dashboard for Vaccines

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16970]
## Problem Statement 

VA digital health decision makers needs to understand how Veterans are looking for vaccine-related information and benefits during the pandemic so that the VA can best support them during a time of crisis.

How might we design a Covid-19 dashboard so that we can provide relevant data that VA digital health decisions makers need to understand how Veterans are looking for vaccine support during the pandemic and condense the dashboard for better readability?

## Hypothesis or Bet
If we can quickly give VA digital health decision makers the information they need, they can quickly given Veterans support during the vaccine release.

## We will know we're done when... ("Definition of Done")
- [x] We have completed charts for a new sub-dashboard in the Covid dashboard for:
  - [x] How Veterans are contacting about the vaccine
  - [x] How Veterans are getting to vaccine tools
  - [x] How Veterans are viewing vaccine content
  - [x] How Veterans are registering for vaccine information

## Known Blockers/Dependencies 
- Contact Center data comes from various sources that are not always sent on a regular cadence (Contact Center team)
- New vaccine-related tools have not yet been launched to production 

## Projected Launch Date
January 2021

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] ~_(if applicable)_ New functionality has thorough, automated tests running in CI/CD~

### ... documented?

- [ ] ~New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)~
- [ ] ~Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)~
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] ~External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool~
    - [ ] ~... and should be located at `platform/PRODUCT_NAME/README.md`~
- [ ] ~External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative~
    - [ ] ~... and should be linked from the VFS-facing README for your product~
    - [ ]~ ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it~
    - [ ] ~_(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)~
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Covid Dashboard
* **Product Outline**: [Product Outline Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/covid-dashboard/covid-dashboard-product-outline.md)
* **README**: [Readme link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/covid-dashboard)
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: [KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/covid-dashboard/covid-dashboard-product-outline.md#measuring-success)
* **Release plan**: [Release plan template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17384)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

---

# Request a KPI Dashboard

Is this a new KPI dashboard request? Or is this an iteration? Please check the correct response.
- [ ] New dashboard
- [x] Iteration of current dashboard

### Description
VFS user story: As a Veteran, I want to know when and how I can get access to the Covid Vaccine.

How might we support the digital health teams with the right analytics to best help Veterans as the vaccine comes out?

#### Vaccine Products & Owners
Main Products
- Covid Chatbot - Danielle
- Vaccine Hub - Danielle
- Trial Registry - Patrick
- Form of Interest - Patrick

Data Owners
- Contact Centers - Chante
- VEText - Shane

Next Products
- VAOS - Lenae
- I Am Here - Shane

### Timelines
- First dashboard MVP: Monday to Tuesday

### Solution Approaches
_Be iterative! It's okay if we don't have a complete dashboard right away, but have parts of the data story ready now and build as we learn more._

DO:
Create a new tab/dashboard (or, in Domo, sub-page) on the Covid Dashboard between "Tool Usage" and "Exploratory Analysis, named, "Vaccine Response" <- may need to rename later
- [ ] Add data that we currently have
    - Vaccine Trial Registry
    - Contact Centers (reach out to Chante)
- [ ] Groom metrics for the rest of the main vaccine products

TRY:
- [ ] Incorporate the Vaccine Research to the other pages on the overall Covid Dashboard.

CONSIDER:
- [ ] Add pathways for VAOS to track the vaccine appts
- [ ] Add VEText for 
- [ ] Add MHV Social Studios to understand sentiment

### Vaccine Page Design
Set it up similarly to the Digital Response summary page (@joanneesteban to attach prototype)

**1. How Veterans are contacting about the vaccine**
- Datasets:
    - Contact Centers
    - Chatbots
    - Any ForeSee information

Do: Nested bar chart - daily

1a. How Veterans are getting to vaccine tools
- Datasets:
    - GA

Try: Line graph page entries - daily

**2. How Veterans are viewing vaccine content**
- Datasets:
    - BQ - COVID Pages - Pageviews, Users, Sessions

Do: Nested bar chart - daily
Do: Percent change - daily

**3. How Veterans are registering for the vaccine**
- Datasets
    - GA

Do: Nested bar chart of successful submissions - daily
Do: Percent change - daily
Try: Registry Funnel - since launch (this may need to be changed given new data)
Try: Page Views vs. Successful Submissions vs. Failed Submissions - daily (this may need to be changed given new data)

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [x] Groom analytics for technical feasibility
    - [x] Document data sources for each metric
    - [x] Document unavailable vs. available metrics
- [x] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [x] Draft dashboard on Domo
- [x] Structure data for ETL
- [x] Pipe available metrics to Domo
- [x] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Bodies of work here - incorporating data from:

1. Vaccine trial registry. @jasonthebearded has begun work in [16348](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16348).
2. Contact Center data. @clantosswett & Contact Center team will provide updates.
3. Chatbot data. We should already be tracking data. @bsmartin-ep do you know if we can start segmenting this for Vaccines? Otherwise, we should reach out to Danielle. 
4. Form of interest. @bsmartin-ep @stephenBarrs opened an [implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16981) to get vaccine prep tool data added.
5. Landing page hub. @joanneesteban to reach out to @DanielleThierryUSDSVA to get started.

**Comment by joanneesteban** [comment]
Continuation of other bodies of work:

6. Clean up the current week/month view. It looks like the numbers fall off during the current week/month and are misleading.
7. Fix data update bugs. Outside of Contact Centers data, it looks like the following datasets aren't updating:
    - `Topic Trends` - `Number of link clicks on homepage banner` - no update since 11/4
    - @lalexanderson-dsva is there additional data on the dashboard that you were looking at that isn't updating?

**Comment by joanneesteban** [comment]
@JasonTheBearded edited the dashboard you created to include a template of what it should eventually look like (including formatting for eventual exports). Please edit it as you need to.

**Comment by joanneesteban** [comment]
## Notes on Closing

We are ready to close this Initiative, but are cutting the Contact Center dependencies. We have a note as a team to open a new ticket if and when Contact Center data becomes available.

### Final To Do
- [ ] Reach out to Lauren & Patrick
- [ ] Update Product Outline w/screenshots & solution approach for Vaccine dashboard
- [ ] Add Vaccine Dashboard to Service Design February Platform Newsletter
