### ISSUE TITLE
Update Cypress docs with information about new hasCount() custom command

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16975]
## Issue Description
Update Cypress documentation to include information about new hasCount() Cypress custom command.

---
## Tasks
- [ ] Add documentation about new hasCount() Cypress custom command
- [ ] If documentation about the old hasFocusableCount() and hasTabbableCount() helper functions exists, remove it.

## Acceptance Criteria
- [ ] Documentation will be updated.

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/va.gov-team/pull/16976

**Comment by holdenhinkle** [comment]
This is merged.

**Comment by pjhill** [comment]
Reviewed
