### ISSUE TITLE
Error States: Phone Number Screens

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#16982]
## User Story
As a user saving a phone or fax number, I want to see the message "Please enter a valid phone number." when what I've written does not meet field requirements. 

## Tasks
- [ ] Design UI for what a phone number screen looks like when an error has occurred
- [ ] Define text of the error
- [ ] Define when the error shows up (e.g. field rules)
