### ISSUE TITLE
Update outdated documentation for mailing address and name 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16992]
## Issue Description
Update outdated documentation for mailing address and name 

---
## Tasks
- [x] Update documentation  for mailing address in the forms library 
- [x] Update documentation  for name in the forms library

## Acceptance Criteria
- [x] Documentation is updated for mailing address and name
---
