### ISSUE TITLE
Project Kickoff [Search & Discovery- Click Tracking]

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17005]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all relevent artifacts to the ticket
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] Shira will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] Kickoff meeting completed 
- [x] [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))  - Click Tracking Epic #16444  ] 
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Denise Coveyduc**
- DEPO Product Lead (required): **John Hashimoto**
- Entire VFS team (recommended): **Megan Gayle -Designer/Researcher and Sam Suddath-FE Engineer**
- Other specialists: **Tze Lei- QA Resource**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** NO

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket)**Thursday December 10, 2020@1:30pm EST**, and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**Comment by shiragoodman** [comment]
hi @denisecoveyduc and the VSA Search & Discovery team! Thank you for answering our questions at Project Kickoff today. After reviewing your responses to our questions, we're recommending the following Collaboration Points:
- Analytics Request
- Privacy & Security Review
- Post-launch Check-in

Additional details for the above collaboration points can be found in our [Collaboration Cycle guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md). The Platform Collaboration Point Tracker has been updated. Please let me know if you have any questions.

**Comment by denisecoveyduc** [comment]
We do not have an Analytics Request ticket for Click Tracking since all click tracking data is all captured via Search.gov not the Analytics Insights team. 
cc: @shiragoodman
