### ISSUE TITLE
Staging Review [Search & Discovery - Type Ahead POC]

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17002]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] Staging Review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
- Link to your product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/150&group_by=cases:section_id&group_order=asc&group_id=640)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/1034) in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/167) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/168) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

## Meeting attendees from **requesting team**
- Product Manager (required): **Denise Coveyduc**
- DEPO product lead (required): **John Hashimoto**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Megan Gayle- Designer/Researcher and Sam Suddath- FE Engineer. **
- Other specialists: **Tse Lei - QA**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 4 business days from now
- Write that preferred time slot here (on this ticket)[**Friday December 11, 2020 @ 2pm EST**], and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and shira will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by tlei123** [comment]
@denisecoveyduc , I just opened VSA-QA Test Plan ticket #17051 for us to start putting Use Cases together.

I'll chat w/ you tmrw (Tue) about this.  Thx much!

**Comment by tlei123** [comment]
@pjhill , all Test Runs now completed -- QA-artifact links added/updated above in main description.

cc @denisecoveyduc @johnhashva

**Comment by peggygannon** [comment]
@denisecoveyduc @johnhashva is there a staging link for us to review/check? can you drop it here into the ticket

**Comment by shiragoodman** [comment]
@denisecoveyduc adding onto Peggy's comment above.. do you also have a Product Outline you can provide?

**Comment by mnorthuis** [comment]
For documentation purposes, no IA feedback.

**Comment by allison0034** [comment]
For documentation purposes, no design feedback.

**Comment by pjhill** [comment]
I have no detailed QA feedback -- thanks!
