### ISSUE TITLE
Search & Discovery - Search.gov fwd proxy endpoint

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#17009]
## Description
We need a backend fwd proxy set up to allow us to hit the Search.gov click tracking API endpoint (Secret key required)

## Background/context/resources
The endpoint is:
https://api.gsa.gov/technology/searchgov/v2/clicks/

the required parameters are:
url: passed in
query: passed in
affiliate: va
position: passed in
module_code:  I14Y.
access_key: (this is a secret, reach out to me for it)
client_ip: passed in
user_agent: passed in

## Technical notes
[Search.gov.-.Click.Tracking.API.Instructions.Beta.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5655070/Search.gov.-.Click.Tracking.API.Instructions.Beta.docx)

---
## Tasks
- [x] Fwd Proxy endpoint has been created

## Definition of Done
- [x] Fwd Proxy endpoint allows front end to hit Search.gov's click tracking api using secret key

---
### Reminders
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@srsuddath - So that we can get this work prioritized for an upcoming Sprint, could you possibly provide some insight into your roadmap / timeline for this feature?

**Comment by srsuddath** [comment]
Sure thing, this is an analytics add-in that search.gov has made available to us ahead of their full release. We are hoping that this, tied with the analytics from type ahead (which starts a phased roll out next week), could provide us some valuable insight into our search metrics.  My PO's hope is to have this feature implemented before the Christmas code freeze, so that we can cash in on our early access. There is a bit of front-end work to be done on this effort, but mostly just hitting this endpoint. 

I apologize if this isn't all the information you are looking for. I am new and this product is a hand-off from before I began, so I am learning as I go!

**Comment by jhouse-solvd** [comment]
@srsuddath - just wanted to let you know that I've spoken with the team and this seems like something pretty straight forward, and we plan to address during this current Sprint. We will reach out to you if we have any other specific questions, and as we make progress on getting this set up for your team. thanks so much!

**Comment by denisecoveyduc** [comment]
Hi @jhouse-solvd  I just wanted to touch base and see if there are any updates on the progress? We would love to implement click tracking before the code freeze if at all possible and I know that @srsuddath is ready to go once your team has completed the back end portion. Thanks in advance for updates.

**Comment by jhouse-solvd** [comment]
@denisecoveyduc - I've spoken with Taylor (@tskinn) from our team, and he has a few questions for Sam (@srsuddath). Taylor will be following up in the comments below to continue the conversation and clarify requirements.

**Comment by tskinn** [comment]
Hey @srsuddath we try to fill out some documentation whenever we add a backend to the forward proxy. [Here](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/external-service-template.md) is a template. If you could copy that and make a PR to the devops repo that would be great.

Don't sweat too much about it but do the best you can. Honestly, the biggest question I have, besides the connection details, is what do we do if the service goes down? Who is affected if it goes down? Who do we contact, both for the service and on our side? (like is there a vfs team that wants to be informed of the services status)


Also on a configuration side note: Do you happen to know if there is a health check endpoint we could hit? It is nice to have an HTTP health check as opposed to plain tcp but not a huge deal.

**Comment by srsuddath** [comment]
@tskinn I will check this out and get it edited / pushed up shortly

**Comment by srsuddath** [comment]
@tskinn I just started the pull request. I am going to reach out to search.gov to see if I can get more answers to some of the questions you posed, as everything I have on the endpoint is captured in the document tagged above

**Comment by tskinn** [comment]
vets-api should be able to reach the gsa api (and therefore the search api) through the forward proxies at these addresses:

```
dev:     https://internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com:4477
staging: https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4477
prod:    https://internal-dsva-vagov-prod-fwdproxy-2075821597.us-gov-west-1.elb.amazonaws.com:4477
```

**Comment by jhouse-solvd** [comment]
@srsuddath & @denisecoveyduc  - please see Taylor's comment above, and let us know if this meets your requirements for this functionality. it appears that Vets-API should be able to reach the GSA API & Search API through our FWDPROXY's :)

**Comment by srsuddath** [comment]
@jhouse-solvd I will look into this and get back with you!

**Comment by srsuddath** [comment]
@jhouse-solvd Looking into this now and digging into the links you sent. If I understand correctly, this means that now I need to go ahead and build out the endpoint on Vets-api? Or is that already built out with the forward proxy urls you posted above?

**Comment by srsuddath** [comment]
Thanks for your hard work! Closing this issue!
