### ISSUE TITLE
Audit blocked by data in health care facility node

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17018]
## Issue Description
The Facilities team needs to perform a final audit of pages before cms-export cutover. The audit is blocked by invalid data in the `health care local facility` node. 

---
## Tasks
- [x] Resolve blocker caused by newly populated data

## Acceptance Criteria
- [x] Audit work can proceed. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
PR: #15231 Fix validation error in health_care_local_facility nodes
