### ISSUE TITLE
Breadcrumb Tweak for "View your VA payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17015]
## Background
Since authenticated uses will go straight to the tool page itself, it was recommended by IA that the breadcrumbs not mention the interstitial landing page and simply show the **Home > View your VA payment history** breadcrumb.

## Considerations
- [IA Recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-payment-history.md)
- Current breadcrumb: **Home > View your VA payment history > Your VA payments**❌
- New breadcrumb:  **Home > View VA payment history**✔

## Tasks
- [x] Remove the middle page from this breadcrumb
- [x] Request a PR for merging

## Acceptance Criteria
- [x] Breadcrumb is up to date
- [x] PR is requested for merging
