### ISSUE TITLE
Create Test User Dashboard Database for Identity Team

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17021]
## Issue Description
Identity/backend needs a new Postrgres DB for the purpose of hosting the test users

---
## Tasks
- [ ] Create new DB in utilities environment
- [ ] Create admin accounts for new DB for John Bramley and Trevor Bosaw and Alex Garcia

## Acceptance Criteria
- [ ] Expect to be able to directly access the new DB over development & staging environments (not available via production)

## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
The TUD backend data schema was changed to [add a `test_user_dashboard_tud_accounts` table](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/test_user_dashboard/db/migrate/20210121161138_add_tud_accounts.rb) to the existing `vets-api` database for the environment in question. As such, there is no need for the creation of a new database at this time.
