### ISSUE TITLE
Test User Dashboard Application MVP

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17026]
## Product Outline
[TBD](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a QA tester, I need an easier way to assume a test user account so I can test changes to va.gov.

## Hypothesis or Bet
**If** we make this change to the test user account processes **then** we expect testing to be simpler to accomplish.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete?
- [ ] Users can view an accurate list of test user accounts available on staging.
- [ ] Users can filter test user accounts based on different categories
- [ ] Users can view details about a specific test user account's credentials
- [ ] Users can perform CRUD operations on new/copied test user accounts
- [ ] Users can "check out" a test user account to log into staging with it

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by bramleyjl** [comment]
Closed as duplicate, overall Test User Dashboard epic @ #13714
