### ISSUE TITLE
Separate Repo (or Gem) For Test User Dashboard Work

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17023]
## Issue Description
The Identity team needs a separate place to host the Test User Dashboard (TUD) codebase; we are unsure if a new repository is the best way to accomplish this. The TUD app is a full-stack app (React/Ruby/Postgres) to connect to the Test Users database as well as making API calls to vets-api on staging and development environments (only, no connection to production wanted).

---
## Tasks
- [x] A new repository is created to host both the React frontend and the RoR backend.

## Acceptance Criteria
- [x] Identity Team developers (John Bramley, Alex Garcia, Trevor Bosaw, and Joe Niquette) have access to the new repository.

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
