### ISSUE TITLE
Update UI design of Input Field Common Component to include an error state

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17031]
_Internal note:_ This story is for the work to document: 
1) The common component for an input field with a label above the input field ([should look like this](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/431636876))
2) The error state for this component 

---

## User Story
- [x] As a user of the VA mobile app, I want to see a field's label **above** the field for clarity and increased visual accessibility
- [x] As a user of the VA mobile app, I want to see when a field has an error 
- [x] As a user of the VA mobile app, I want the voiceover experience of input fields to be consistent across the board

## Tasks
- [x] Document Input field design as a common component ([should look like this](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/431636876))
- [x] Design & document error state of the input field
- [x] Document voice over rules that should be applied to the field in both default and error state

## Context 
In an effort to match the UX and accessibility of VA.gov's Profile 2.0, we want to include field labels above all input fields and provide error messages at the field level. We believe this will increase the usability of the app because it will allow us to let users know exactly where they have made a mistake so they can fix it.

## Design decisions
- Current VA.gov  form field is out of compliance with the use of colors, suggested using primary-Navy blue for focus colors
- added dropdown button for state/country mode

## Accessibility considerations:
Inactive state(empty):
- Formfield: “{label}, empty."
- Formfield/Message: “{label, Hint message}, empty. "
- Dropdown: “{label}, empty."
- Dropdown/Message “{label, Hint message}, empty. "

Focused state(editing):
- Formfield: “{label}. Editing - {Input text}. "
- Formfield/Message:“{label, hint message}. Editing - {Input text}. "
- Dropdown: “{label}. Editing - {Input text}."
- Dropdown/Message “{label, hint message}. Editing - {Input text}. "

Activated state:
- Formfield: “{label}. Filled - {Input text}. ”
- Formfield/Message:“{label, hint message}. Filled - {Input text}. ”
- Dropdown:“{label}. Filled - {Input text}. ”
- Dropdown/Message “{label,hint message}. Filled - {Input text}. ”

Error state:
- Formfield: “{label}. error - {Validation text}.”
- Formfield/Message: “{label, hint message}. error - {Validation text}.”
- Dropdown:“{label}. error - {Validation text}.”
- Dropdown/Message“{label, hint message}. error - {Validation text}.”

for iOS, always add "Double-tap to edit(for iOS)” as It is not coded in.

**Comment by bridgethapner** [comment]
I'm revisiting this to wrap up and get into the prototype, and as I'm combing through the web, the web design library, and work done so far, I'm making a couple of changes to bring the UXs across web and mobile in line a bit more: 

- We should remove the placeholder text to match the [guidance of the VA.gov design system](https://design.va.gov/components/form-controls#accessibility). I checked with Josh on VSA and his guidance was to remove it & there is no placeholder text on the web.
- I'm increasing the size of the error text to standard 17px mobile body bold size, worried it'll be too small otherwise
- I think we can increase the contrast of the default label outline to match VA.gov 

Working on these changes today/early next week

**Comment by bridgethapner** [comment]
Made the couple edits noted above, here is the visual documentation for the updated Input field CC & the A11y documentation from Meli is above in the ticket body. Please note that I upped the contrast of the default empty form field border, so the visual design for the inactive state and active stated are the same, but have different voice over rules per the documentation above.

![mobile app - input UI.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/15d813be-9e2e-44ce-a115-d53c8167cfcc)

Here are a couple of screens in the prototype that have been updated with the new designs: 

- [Edit state of Mailing Address (Empty)](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432053040)
- [Edit state of Mailing Address (Errors)](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/442012480)
- [Edit state of Home Address (Completed)](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/442018171)

**Comment by bridgethapner** [comment]
@bessgreen

**Comment by bessgreen** [comment]
Hi @msmanak, question about the a11y-requirement listed above: 

"for iOS, always add "Double-tap to edit(for iOS)” as It is not coded in."

Is the ask to include this announcement on iOS for each editable field that is not in focus? If so, should a similar announcement also apply to every button/dropdown that could be selected throughout the mobile app (e.g. "Double-tap to navigate to the Claims page")? 

For additional context: the VoiceOver settings screen on iOS also includes guidance to "Double-tap to activate the selected item" (screenshots below), so it seems to be a fundamental part of the VoiceOver UX. That said, if it's important to reiterate "Double-tap to [action]" on the mobile app, we can do that - I just want to make sure we're accounting for all of the scenarios where we should be making this change. 

cc: @bridgethapner @ayushchak 


![Image from iOS (10)](https://user-images.githubusercontent.com/71455141/107304700-7514ae80-6a36-11eb-96f4-4ad815d93e66.png)
![Image from iOS (9)](https://user-images.githubusercontent.com/71455141/107304703-76de7200-6a36-11eb-9d83-98097dc3dead.png)
