### ISSUE TITLE
Error States: Email address

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17042]
## User Story
As a user saving an email address, I want to see the message "Please enter your email address again, using this format: X@X.com." when what I've written does not meet field requirements. 

## Tasks
- [ ] Design UI for what the email screen looks like when an error has occurred
- [ ] Define text of the error
- [ ] Define when the error shows up (e.g. field rules)
