### ISSUE TITLE
Claims: Add description of each of the 5 steps to the Claims Detail Screen

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17052]
## User Story
As a user, I want to see text describing what happens at the step of each claim. 

## Tasks
- [x] Track down language used on VA.gov CST for each of the 5 steps
- [x] Update UI to include language
- [x] Update documentation of Claim Status Tool Step List

**Comment by bridgethapner** [comment]
# Gathering text requirements

**Step 1**
Title: **Claim received**
Description: Thank you. VA received your claim. 

**Step 2**
Title: **Initial review**
Description: Your claim has been assigned to a reviewer who is determining if additional information is needed.

**Step 3**
Title: **Evidence gathering, review, and decision** 
Description: If we need more information, we’ll request it from you, health care providers, governmental agencies, or others. Once we have all the information we need, we’ll review it and send your claim to the rating specialist for a decision.

**Step 4**
Title: **Preparation for notification** 
Description: We are preparing your claim decision packet to be mailed.

**Step 5**
Title: **Complete**
Description: [N/A] _I cannot find one. I think we'd switch over to showing the closed state of the Claims Detail screen here anyway._

**Comment by bridgethapner** [comment]
I added an accordion element that, when opened, displays the description of that claim's step. 

- [Wireframe for the default state of a claim at step 3 with a file request](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432345660) 
- [Wireframe with an expanded row that has an active file request ](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/440039340)
- [Wireframe for an expanded past event row](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/440039998)

**Comment by bridgethapner** [comment]
- As part of this story, I also added a Mobile Alert up alert people of file requests right away. This uses the Mobile Alert CC without the Click for Action CTA or Body text. 
- Re the interaction design of the accordion, users should be able to have multiple steps of the Claim open at the same time (e.g. don't auto-close one step once the user opens a different step).

**Comment by bridgethapner** [comment]
@bessgreen @lexicalninja I think this UX story is wrapped up, please let me know if you have any questions/feedback! Thank you.

![Claim Status-step 3-open.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/8d0fe9f6-05da-49c9-a456-3fedc4393b93)

**Comment by lexicalninja** [comment]
Should be good. I think all the rest is in other tickets that are almost done
