### ISSUE TITLE
Non-Lighthouse engine routes are not covered by nginx route metrics 

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#17054]
## Description
We attempt to record http metrics for specific routes in nginx, so you can break out things like request rate/error rate for a specific application.

All or most of the "classic" API endpoints that are part of the main Rails monolith get mapped to `api.va.gov/v0/foo` are defined in a list `api_generic_components`, and then the metrics are regexed out in this block:
https://github.com/department-of-veterans-affairs/devops/blob/850deb141b28738ca3cb33bdc400a6f9c93108be/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L131

Starting with the lighthouse work, new functionality was broken out into rails engines and mounted under `api.va.gov/services/foo`. Those are enumerated in `kong_components` and broken out into metrics in this block:
https://github.com/department-of-veterans-affairs/devops/blob/850deb141b28738ca3cb33bdc400a6f9c93108be/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L174

However, there is also some new work that has occurred that is being done in engines, and mounted under separate paths not under `api.va.gov/v0/`, but are not part of lighthouse and thus are not mounted under `/services` either. At the moment the list looks like:
- health_quest
- vaos
- covid-research
- mobile
- covid_vaccine

So these routes get no per-component metrics whatsoever. 

## Technical notes

---
## Tasks
- [ ] At minimum, add a similar location block and a list of non-lighthouse engine API paths to capture, with `application=api` and component=`engine` (eg. covid_vaccine, etc) 
- [ ] For something as complex as VAOS, it probably warrants being able to set `application=vaos` but also to break out `component` values individually. But that might be beyond the scope of what is needed here. 

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by patrickvinograd** [comment]
To clarify, those requests would get counted in the total "nginx_http_request_" metrics, but there's no way to break them out by `app` or `component`.

**Comment by jhouse-solvd** [comment]
@patrickvinograd - This has been assigned to @omgitsbillryan and prioritized for the current sprint. Bill may reach out to you with additional questions, but otherwise know that we are working on this during this sprint.

**Comment by omgitsbillryan** [comment]
Threw together [a quick graph](http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=6h&g0.expr=sum(nginx_http_request_duration_seconds_count)%20by%20(component)&g0.tab=0) showing that an empty `component` is far and away the most frequent value... a distant 2nd place is `component not set in nginx_components.yml`

**Comment by omgitsbillryan** [comment]
The following engines namespace 100% through `/v0`:
- `covid_vaccine`
- `health_quest`

which makes me think they can be just added to `api_generic_components` - is that correct?

**Comment by patrickvinograd** [comment]
`config/routes.rb` is a little confusing for engines - the line 
```
mount CovidVaccine::Engine, at: '/covid_vaccine'
```
means that /covid_vaccine is prefixed, and then the per-engine routes get appended, so the route for the covid_vaccine API is `api.va.gov/covid_vaccine/v0/registration`, so it's not caught by this line:

```
location ~ ^/v0/({{ api_generic_components|join('|') }}) {
```
because the carat means "starts with /v0"

**Comment by omgitsbillryan** [comment]
Looks like the metrics are working properly in `prod` - [link](http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=1h&g0.expr=sum(nginx_http_request_duration_seconds_count%7Bcomponent%3D~%22health_quest%7Cvaos%7Ccovid-research%7Cmobile%7Ccovid_vaccine%22%7D)%20by%20(component)&g0.tab=1) 

Ticket looks good to close to me. @patrickvinograd - do you see any additional work to be done?
