### ISSUE TITLE
Assist in Configuring IAM SSOe OAuth backend in Production

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#17069]
## Issue Description
Assist Jonathan Julian in configuring the IAM SSOe OAuth backend in production with necessary client ssl connection.

---
## Tasks
- [x] Assist in obtaining VA signed SSL certificate
- [x] Configure systems to leverage the new backend connection in production

## Acceptance Criteria
- [x] Obtain VA signed SSL cert
- [x] Configure new backend connection in production
- [x] Config tested, all things working as intended 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Tagging @jjulian on this for visibility. CSR and cert request were submitted yesterday (12/07/2020), awaiting reply from VA PKI Team.

**Comment by jbritt1** [comment]
This is currently being blocked by a "change freeze" at the ESECC level.

**Comment by jbritt1** [comment]
Certs are in place, firewall rules updated. @jjulian plans to test this some this week. Will leave this open to await feedback that all things are working as desired.

**Comment by jbritt1** [comment]
There were some final issues that needed to be worked out, but this connection is good and has been tested on both ends by @kreek and partners on the other end. This is ready for final review @jhouse-solvd.
