### ISSUE TITLE
Update / Migrate VA Signed SSL Doc 

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#17068]
## Issue Description
Process for obtaining VA signed SSL certs has changed according to the old landing page we had in our docs. This likely needs to be updated and moved to Confluence under our "How do I..." section.

Current location / content for reference: https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/CreatingVASignedSSLCertificate.md

---
## Tasks
- [ ] Written documentation that clearly explains the process for obtaining a VA signed SSL cert for requiring backends with latest directions.
- [ ] Migrated from old location to new, desired location with perhaps a pointer link in the former.

## Acceptance Criteria
- [ ] Doc migrated to Confluence
- [ ] Updated with latest information and instruction.
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
