### ISSUE TITLE
CMS Export build adds unnecessary meta tag

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17065]
The CMS Export build is adding this header to many pages:

`<meta name="DC.Date" scheme="W3CDTF" content="2020-03-24">`

This isn't needed and creates a lot of false positives when running audits.

It should be removed.

## Acceptance Criteria
- [x] CMS Export does not add unnecessary header to pages

**Comment by meganhkelley** [comment]
@mpelzsherman @mmiddaugh could y'all please help us understand the priority of this issue and how it affects your team? Thanks!

**Comment by mpelzsherman** [comment]
As previously mentioned, the tag creates false positives when running audits.

**Comment by meganhkelley** [comment]
Update — Jhonny will need to verify that his fix for this applies to all transformers, but is troubleshooting a broken build again 

Related — #18791

**Comment by jhonnyoddball** [comment]
The following pages need to be fixed:

- [ ] /education/about-gi-bill-benefits/post-9-11/index.html 
- [ ] /erie-health-care/health-services/index.html 
- [ ] /erie-health-care/leadership/index.html 
- [ ] /erie-health-care/locations/index.html 
- [ ] /erie-health-care/news-releases/erie-vamc-hosts-veteran-town-hall/index.html
- [ ] /erie-health-care/news-releases/index.html 
- [ ] /erie-health-care/stories/index.html 
- [ ] /pittsburgh-health-care/health-services/index.html 
- [ ] /pittsburgh-health-care/leadership/index.html 
- [ ] /pittsburgh-health-care/news-releases/belmont-county-veterans-getting-larger-more-modern-va/index.html
- [ ] /pittsburgh-health-care/news-releases/ (26 more)
- [ ] /pittsburgh-health-care/stories/index.html 
- [ ] /pittsburgh-health-care/stories/ (3 more)

**Comment by jhonnyoddball** [comment]
Fixed on PR [15914](https://github.com/department-of-veterans-affairs/vets-website/pull/15914)
