### ISSUE TITLE
[Analytics] Upload data needed for Patient-advocates Program Pages - VISN-6 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17079]
## Story
As a web user, I need staff and contact information for Patient-advocates, so I can quickly find and reach out for caregiver support.

## Goals
Complete ALL Patient-advocates pages in the entire VISN

## Resources
[Staff Profiles for VISN-6](https://drive.google.com/drive/folders/1VE97L56orKhof5TXBbSaMvbmsrta2uyo)

## Tasks
Complete ALL Patient-advocates pages for each System Across the VISN to include the following sites:
- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care

## Acceptance Criteria
- [x] Each Patient-advocates page has the Staff profile created "Person or location"
- [x] Local and nationalized information has been provided in the page

**Comment by EdwardBoehme05** [comment]
Decreased points from 3 to 1.
