### ISSUE TITLE
[Analytics] Upload data needed for Suicide-prevention Program to the Latest version of Suicide Prevention Page - VISN-6 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17083]
## Story
As a web user, I need staff and contact information for Mental Health-care, so I can quickly find and reach out for caregiver support.

## Goals
Complete ALL Suicide-prevention pages in the entire VISN and assure that latest page is set for this VISN.

## Resources
[Staff Profiles for VISN-6](https://drive.google.com/drive/folders/1VE97L56orKhof5TXBbSaMvbmsrta2uyo)

## Tasks
Complete ALL Suicide-prevention pages for each System Across the VISN to include the following sites:
- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care

## Acceptance Criteria
- [x] Each Suicide-prevention page has the Staff profile created "Person or location"
- [x] Local and nationalized information has been provided in the page

**Comment by ltrombley** [comment]
Task #17083 - Upload data needed for Suicide-prevention Program to the Latest version of Suicide Prevention Page - VISN-6 - Complete and moved to Validate.  **All VISN-6 Suicide Program Pages have been Cloned from Sierra Nevada.**

- VA Asheville health care
- VA Durham health care
- VA Fayetteville Coastal health care
- VA Hampton health care
- VA Richmond health care
- VA Salem health care
- VA Salisbury health care
