### ISSUE TITLE
[Analytics] Upload data needed for Women-veteran-care Program Pages - VISN-6 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17084]
## Story
As a web user, I need staff and contact information for Women-veteran-care, so I can quickly find and reach out for caregiver support.

## Goals
Complete ALL Women-veteran-care pages in the entire VISN

## Resources
[Staff Profiles for VISN-6](https://drive.google.com/drive/folders/1VE97L56orKhof5TXBbSaMvbmsrta2uyo)

## Tasks
Complete ALL Women-veteran-care pages for each System Across the VISN to include the following sites:
- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care

## Acceptance Criteria
- [x] Each Women-veteran-care page has the Staff profile created "Person or location"
- [x] Local and nationalized information has been provided in the page

**Comment by EdwardBoehme05** [comment]
Durham link teasers might have incorrect URLs (with an extra "va-"), e.g.

http://preview-prod.vfs.va.gov/va-Durham-health-care/mental-health-care

**Comment by EdwardBoehme05** [comment]
The Durham link teaser issue (see above comment) has been brought into the vamc-support channel.
