### ISSUE TITLE
Session Timeout Modal does not display in production

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17087]
## Issue Description
There have been several issues that stem from the `SessionTimeoutModal.jsx` file not being viewable in production as it is currently behind environment flags.  Discussions below outline the UX (User Experience) issue and security concerns of not having the modal in production.

- [Robin G discussion in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1607013285486200)
> UX: On production VA.gov site, Robin is auto-logged without warning
- [Erik Hansen discussion in Slack](https://dsva.slack.com/archives/C5HP4GN3F/p1598840245002600)
> Security: Possible security issue of two users using a shared computer and PII might be exposed

---
## Tasks
- [x] Remove/change environment flag to allow in production

## Acceptance Criteria
- [x] Verify changes in Staging & Production

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
