### ISSUE TITLE
[PM] Update .csv files for Facility Health Services as reflected from CMS review

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17095]
## Story 
As a engineer I need corrections to the .csv files in order to finalize testing, so the .csv will migrate successfully in test and can be implemented to Production.

## Tasks
- [ ] Update VISN-6 .csv issues
- [x] Update VISN-16 .csv issues
- [x] Update VISN-21 .csv issues
- [x] Update VISN-23 .csv issues
- [x] Update VISN-2 .csv issues

## Acceptance criteria:
- [ ] All .csv files successfully process through test environment
