### ISSUE TITLE
Create feature flag for Homepage iteration

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17098]
## Background
Set up toggle in anticipation of the next iteration of the homepage and appointment cards.

## Tasks
- [x] Add FE flag "va_online_scheduling_homepage_refresh"
- [x] Add BE flag
- [x] New appointments page shell

- [x] Appointment type dropdown list https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/qeRrE5e#Inspector
