### ISSUE TITLE
EKS - Set up dedicated repo for application manifests that Argo can monitor

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17092]
## Issue Description
_As per Argo best practices, we need a place to keep the kubernetes manifests separate from the application source code._

https://argoproj.github.io/argo-cd/user-guide/best_practices/

---
## Tasks
- [x] _Create repo with name that makes sense given our current naming scheme and the purpose of this repo_
- [x] _Configure repo with appropriate permissions_
- [x] _Create a directory structure in the repo too account for applications and their respective environments (ie <app name> -> <environment name> -> manifest.yml)_

## Acceptance Criteria
- [x] _Repo is created and configured_
- [x] _Admin access to repo for vsp-operations team_

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests

Added CODEOWNERS for vsp-operations. We can add more as we go.

**Comment by jhouse-solvd** [comment]
This now exists here: 

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests

Closing.
