### ISSUE TITLE
Improve the quality of screen shots in R&S articles

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#17091]
## Issue Description

The screen shots are slightly blurry in these articles (listed in order of priority to work on them--the last one here isn't in need as much as the others):
https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/
https://www.va.gov/resources/how-to-change-your-address-in-your-vagov-profile/
https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-education-benefits/
https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-disability-or-pension/

---
## Tasks
- [ ] Take new screen shots and replace what's in drupal now for the above articles.

## Acceptance Criteria
- [ ] Images are clearer.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lwalsh617** [comment]
@brianalloyd @RLHecht -- Do you have any idea how to get clearer screenshots? I made sure the browser window was at 100% and used shift command 4. I'm not aware of anything that can cause them to be blurry aside from not having browser at 100% -- so am not sure how to capture clearer ones. Thanks for any help!

**Comment by laurellawrence** [comment]
@lwalsh617, I downloaded all the screenshots to look at the sizing and resolution. The css applied for this is max-width: 100%, so the images are not being stretched larger and pixelated because of the CMS.  It appears that most of these are being saved too small at a low resolution. For example: 

Horizontal images are all sized inconsistently (width) and are too small 
Step1signin.png (638px x 434px)
eBenefits home page.png (480px x 376px)

Here is a GOOD resolution horizontal image, the width and height are approximately double that of the other images
Direct deposit information - Jonnie.png (1366px 764px)

My recommendation would be:
- For the horizontal images - re-capture all the screenshots and make sure they are approximately 1366px x 764px
- I can help with this consistent resizing if needed (I live and breathe in photoshop)
- For vertical images (login screens), it gets a little trickier since making them 1366px width will cause them to take up more vertical real estate on the page. We could try resizing one of the images to test, for example Step2VerifyID.png (382px x 513px) could be doubled size (764px x 1026px) to see if it improves

Another thing to consider is making sure the image size and resolution does not affect the page load performance. 

Let me know if I can assist in any way (:

**Comment by lwalsh617** [comment]
@laurellawrence -- Thanks so much for looking into this. I will try to capture a couple of screenshots as you described above to make sure I'm getting them right. Will run them by you if you don't mind. Thanks!
