### ISSUE TITLE
Update specialty codes for CC provider selection list

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17103]
## Description
For the community care provider selection list, define the 4 speciality codes in the query for each type of care.

Below is the list, ranked in priority order, as defined by Dr. Beckett and approved by Dr. Greenstone.

Note: these lists are defined in the type of care list in the constants file on the front end.

## Tasks
Primary Care
1. 207QA0505X - Family Medicine - Adult Medicine
2. 363LP2300X - Nurse Practitioner - Primary Care
3. 363LA2200X - Nurse Practitioner - Adult Health
4. 261QP2300X - Clinic/Center - Primary Care

Audiology - Routine hearing exam
1. 231H00000X - Audiologist
2. 237600000X - Audiologist-Hearing Aid Fitter
3. 261QH0700X - Clinic/Center - Hearing and Speech

Audiology - Hearing aid support
1. 231H00000X - Audiologist
2. 237600000X - Audiologist-Hearing Aid Fitter

Nutrition
1. 133V00000X - Dietitian, Registered
2. 133VN1201X - Dietitian, Registered - Nutrition, Obesity and Weight Management
3. 133N00000X - Nutritionist
4. 133NN1002X - Nutritionist - Nutrition, Education

Podiatry
1. 213E00000X - Podiatrist
2. 213EG0000X - Podiatrist - General Practice
3. 213EP1101X - Podiatrist - Primary Podiatric Medicine
4. 213ES0131X - Podiatrist - Foot Surgery

Optometry
1. 152W00000X - Optometrist
2. 152WC0802X - Optometrist - Corneal and Contact Management

## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag
- [ ] If user selects Primary Care type of care , provider list results match at least one of the defined speciality codes
- [ ] If user selects Audiology - Routine hearing exam type of care, provider list results match at least one of the defined speciality codes
- [ ] If user selects Audiology - Hearing aid support type of care, provider list results match at least one of the defined speciality codes
- [ ] If user selects Nutrition type of care, provider list results match at least one of the defined speciality codes
- [ ] If user selects Podiatry type of care, provider list results match at least one of the defined speciality codes
- [ ] If user selects Eye Care - Optometry type of care, provider list results match at least one of the defined speciality codes

**Comment by jbalboni** [comment]
My temporary, for testing use only, first pass at these codes is:

Primary care: '208D00000X', '207R00000X', '261QP2300X'
Nutrition: '133N00000X', '136A00000X', '132700000X'
Podiatry: '211D00000X', '213E00000X', '261QP1100X', '207XX0004X'
Optometry: '152W00000X', '156F00000X'
Audiology (hearing exam): '231H00000X', '261QH0700X'
Audiology (hearing aid support): '332S00000X', '237600000X', '237700000X', '231H00000X'
