### ISSUE TITLE
 Pass `mobile=false` from FL frontend

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17108]
## Issue Description
In #13730. we excluded Mobile Vet Centers from Facility Locator search results 
Since then, Lighthouse added an optional [facility mobile search filter](https://developer.va.gov/explore/facilities/docs/facilities?version=current): `mobile:boolean:query`	

To reflect this change,  the FE should pass `mobile=false` instead of `exclude_mobile`

### Facilities for testing: 

[Facility Locator search VA health in Cheyenne, WY](https://www.va.gov/find-locations/?address=cheyenne%2C%20wy&facilityType=health&location=undefined%2Cundefined&page=1&serviceType&zoomLevel=4&latitude=41.14&longitude=-104.8202&radius=71&bounds%5B%5D=-105.5702&bounds%5B%5D=40.39&bounds%5B%5D=-104.0702&bounds%5B%5D=41.89&context=Cheyenne%2C%20Wyoming%2C%20United%20States)

**Current result list includes**
  - Cheyenne VA Medical Center
  - Cheyenne VA Mobile Clinic
  - Laramie VA Mobile Clinic
  - Fort Collins VA Clinic
  - Loveland VA Clinic

**Expected after this change**
 - Cheyenne VA Medical Center
 - Fort Collins VA Clinic
 - Loveland VA Clinic

---

[Facility Locator search VA health in Mobile, AL](https://www.va.gov/find-locations/?address=mobile&facilityType=health&location=undefined%2Cundefined&page=1&serviceType&zoomLevel=4&latitude=30.6488&longitude=-88.1946&radius=31&bounds%5B%5D=-88.9446&bounds%5B%5D=29.8988&bounds%5B%5D=-87.4446&bounds%5B%5D=31.3988&context=Mobile%2C%20Alabama%2C%20United%20States)

**Current result list includes**
- Mobile VA Clinic

**Expected after this change**
- Mobile VA Clinic

---

[Facility Locator search Vet Centers in Spokane, WA](https://www.va.gov/find-locations/?address=spokane%2C%20wa&facilityType=vet_center&location=undefined%2Cundefined&page=1&serviceType&zoomLevel=4&latitude=47.6589&longitude=-117.4247&radius=38&bounds%5B%5D=-118.1747&bounds%5B%5D=46.9089&bounds%5B%5D=-116.6747&bounds%5B%5D=48.4089&context=Spokane%2C%20Washington%2C%20United%20States)

**Current result list includes**
- Spokane Vet Center
- Spokane Mobile Vet Center

**Expected after this change**
- Spokane Vet Center

---
## Tasks
- [ ] Remove custom code to drop mobile facilities.
- [x] Pass `mobile=false` instead of `exclude_mobile` to backend
- [ ] Update unit tests

## Acceptance Criteria
- [ ] Mobile facilities are excluded from search results

**Comment by darkbushido** [comment]
I need to make sure Rails won't drop mobile=false from the params.

**Comment by gescobardev** [comment]
@darkbushido Hey Lance! You made a comment on this issue a while back. I just want to make sure there will be no issues with Rails?

**Comment by mmiddaugh** [comment]
Validated this in Staging - looks great! Thank you @gescobardev
