### ISSUE TITLE
Map FSR Wizard Flow + Content Draft 1

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#17119]
## Issue Description

The various [wizard options](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages//simulate/no-panels?mode=i) will branch into several different flows, and this needs to be mapped out and content written. 

---
## Tasks
- [x] Map out logical flows (Becca / Riley)
- [x] Create corresponding content draft (Becca / Riley)
- [x] Review content with content writer (Susan)
- [x] Send to DMC for feedback

## Acceptance Criteria
- [x] Content mapped and reviewed by Susan
- [x] Content sent to DMC for feedback

**Comment by rebeccawalsh** [comment]
Current progress can be seen here: https://docs.google.com/document/d/14XZjQJ0M1Z5F16PY5_DZ6NtbI7q5IEGj1uqn9gQRL44/edit?pli=1#

An email has been sent to Jill and our SMEs at the DMC to elicit feedback and get some questions answered so that this can be fully completed and a FE ticket made.

Due to the holidays, it's probable that we will not get the feedback we need in order to close out this ticket for the sprint, so I'm modifying the ticket to reflect a draft.
