### ISSUE TITLE
Staff profile node for Behavioral health call center generating page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17116]
## Issue Description
It was understood that staff profiles should not have links unless there is a bio. However, it has been discovered that even those without apparent links still create a node.
- Example 1: [Kristin Lyons (LGBT Coordinator)](https://www.va.gov/pittsburgh-health-care/lgbt-veteran-care/) -> she's not linked and doesn't have a bio. However, she does have [a page.](https://www.va.gov/pittsburgh-health-care/staff-profiles/kristen-lyons/)
- Example 2: [Behavioral health](https://www.va.gov/pittsburgh-health-care/staff-profiles/behavioral-health-call-center/) In lieu of a person, Pittsburgh created a staff profile for their Behavioral-health-call-center and placed it on their mental health program page. Drupal node: https://prod.cms.va.gov/pittsburgh-health-care/staff-profiles/behavioral-health-call-center

**More info from Kevin Walsh**
Staff profiles are embedded on va.gov pages, regardless of their Published status in Drupal.  CMS export-based builds, which do not let any unpublished content go out, would not embed those profiles. This may have been resolved by bulk publishing Staff Profile content for VA Pittsburgh. Perhaps the idea of keeping some staff profiles unpublished (but still allow them to be embedded) was to avoid this problem where they would show up on standalone pages like https://www.va.gov/pittsburgh-health-care/staff-profiles/kristen-lyons/

Two mutually exclusive solutions jump out at me:

1. CMS team add a boolean field to the Staff Profile content model, something like “Enable profile page”. We have something similar on the Q&A content type form (“Enable standalone Resources and support page for this Q&A.“). FE checks if that boolean is TRUE during the build, and only builds the page if it is true. 
2. FE checks to see if there’s a bio field before adding this page to the FE build.

Both seem like relatively low effort. option 1 involves two different teams, but may be more flexible and might be a better overall experience for editors. (less FE mystery/magic)

We will disregard the editorial experience portion of this for now. Will retain in the icebox to revisit

---
## Tasks
- [ ] Check to see if there’s a bio field before adding this page to the FE build.
- [ ] Work with VSP for approval since this pertains to build time. 

## Acceptance Criteria
- [ ] Pages are not built unless there is a bio field
- [ ] Staff profiles containing bios are maintained
       - For testing: [Ali Sonel, M.D.](https://www.va.gov/pittsburgh-health-care/staff-profiles/ali-sonel/) is linked from [Cardiology page](https://www.va.gov/pittsburgh-health-care/programs/cardiology/). 
- [ ] Standalone staff profile pages are no longer published 
- [ ] [Kristen Lyons](https://www.va.gov/pittsburgh-health-care/staff-profiles/kristen-lyons/) and [Behavioral Health Call Center](https://www.va.gov/pittsburgh-health-care/staff-profiles/behavioral-health-call-center) are no longer available due to an **earlier** publishing cycle 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
FYI, this url had 18 pageviews between Sept 1 - Nov 30, 2020

**Comment by mpelzsherman** [comment]
This page came up in my audit of the facilities pages. It is generated by the cms-export build as well, but there's an issue:

![Behavioral_Health_Call_Center___VA_Pittsburgh_health_care___Veterans_Affairs](https://user-images.githubusercontent.com/80267/102139836-66da5580-3e2c-11eb-93cd-f437458df834.png)

**Comment by mmiddaugh** [comment]
Addressed in #29096
