### ISSUE TITLE
Create Flipper Component for CH36 Unauthenticated Landing Page: Dependent Benefits

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17117]
## Background
Part of the phased rollout requires the ability to granularly control who sees the new application we are building on VA.gov as opposed to eBenefits so that we can control who accesses it.

On the [Dependents Benefits page](https://www.va.gov/careers-employment/dependent-benefits/index.html) for CH36:

<details>
<summary><b>Expand to see flipper state for old path:</b> Go back to eBenefits, keep the subway instructions</summary>

![CurrentCH36-depben3](https://user-images.githubusercontent.com/53826255/101684149-f4d0cd80-3a33-11eb-99c4-0f5f014fddc2.JPG)

</details>
<details>
<summary><b>Expand to see flipper state for new path:</b> Go on to the new VA.gov application, just need the button</summary>

![VA-new](https://user-images.githubusercontent.com/53826255/92036653-944c3900-ed3e-11ea-8249-6656f1e9ab0c.JPG)

</details>

Please note that the `<h3>Follow these steps to apply online now:</h3>` should also be removed as we will handle that in the feature toggle.  When all si said and done, we just want the button and not mention irrelevant steps. 

## Tasks
- [x] Discuss with PW about what we intend to change in the flipper component
- [x] Create a flipper component to be shared with the Public Websites folks for implementation
  - [x] Include the subway map for the old path
  - [x] Allow the button to change from "Go to eBenefits to apply" to "Apply for career counseling"
- [x] Config feature toggle for profile

## Acceptance Criteria
- [x] A flipper component can be shared with the PW team

**Comment by micahchiang** [comment]
If a user is on `/careers-employment/dependent-benefits/index.html`: Remove the fifth step and update the language of the second step to align with the above screenshot.
