### ISSUE TITLE
Prepare for Privacy Review

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17127]
## Issue Descritopn
As part of the collab cycle, we need to meet with VSP for a Privacy and Security review. 
This milestone has been requested in [#190](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/190)
The following items need to be documented and linked to the request before the review: 

- [ ] Points of contact for the system and dependent VA backends 
   - Lighthouse
   - Facilities
   - VSP (DevOps)
   - PPMS

- [ ] Links to dashboards that help identify and debug application issues  (@darkbushido to provide)

- [ ] Links to technical diagrams (to be checked into GitHub alongside your product documentation), including:
    - An **architecture diagram**, showing involved systems and how they connect.
    - For non-trivial flows (i.e. more than a single round-trip call from frontend → `vets-api` → VA Backend), a **sequence diagram** showing the ordered flow of data and operations between systems. (@darkbushido to provide)
    - Call to PPMS, second call for each result (will be changing)

- [ ] Description of any new publicly-exposed endpoints (`vets-api` or otherwise):

**v1/facilities/va** when Facility type = 
- VA health
- VA benefits
- Cemeteries
- Vet Centers
- Urgent care + Service type = VA urgent care

**v1/facilities/ccp** when Facility type = 
- Community care providers (in VA’s network)
- Community care pharmacies
- Urgent care + Service type =  Community urgent care (in VA’s network)
 
**/v1/facilities/va_ccp/urgent_care** when Facility type = 
- Urgent care + Service type =  Community urgent care (in VA’s network)

- [ ] Description of new interactions with dependent VA backends
   - How we search for PPMS/Lighthouse
   - Query examples (@darkbushido to provide)

## Tasks
- [ ] Assemble above artifacts, documentation

## Acceptance Criteria
- [ ] Links to all items are available in [Technical Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/technical%20documentation.md)
- [ ] Items are checked off and linked in Privacy and Security request](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/190)

**Comment by mmiddaugh** [comment]
Following arch diagrams can be used as the basis for our Facilities diagram
![facilities-API-system-components](https://user-images.githubusercontent.com/55411834/101677036-40c24900-3a19-11eb-9d20-c3370366f41f.png)
![facilities-API-data-flow](https://user-images.githubusercontent.com/55411834/101677037-415adf80-3a19-11eb-9b2f-19076a8a01db.png)

**Comment by mmiddaugh** [comment]
Documentation should be posted here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/technical%20documentation.md

**Comment by mmiddaugh** [comment]
Privacy and security review was conducted on 12/18 and all feedback has been addressed.
