### ISSUE TITLE
Scrub FL PII

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17120]
## Problem Statement 
Veterans need to be able to use VA.gov securely - meaning they do not have to worry about their PII or PHI data being collected - so that they can get the benefits they need online without having to go in person in order to feel secure or not go to the VA for benefits at all.

How might we secure the data we have collected and further secure our data collection processes so that Veterans have a safe environment to apply for their VA benefits?

## Hypothesis or Bet
If we eliminate the FL data from all of our analytics tooling and warehousing, then we expect to have cleaner and more compliant data and for Veteran data security to improve.

## We will know we're done when... ("Definition of Done")
- [x] Sensitive Facility Locator events are scrubbed from Google Analytics
- [x] Sensitive Facility Locator events are scrubbed from BigQuery
- [x] Sensitive Facility Locator events are scrubbed from Domo
- [x] GTM, GA, & BigQuery are no longer collecting the identified Events
- [x] VSP Analytics has a backlog of impacted analytics & work
- [x] VFS teams and other VA stakeholders are aware of the impacts

## Known Blockers/Dependencies 
- Dependency on Google
- Dependency on CTO's office

## Projected Launch Date
January 2021

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] ~Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.~
    - [ ] ~... and issues discovered in usability testing have been addressed.~
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] ~_(if applicable)_ New functionality has thorough, automated tests running in CI/CD~

### ... documented?

- [ ] ~New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)~
- [ ] ~Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)~
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] ~Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)~
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ~... and should be located at `platform/PRODUCT_NAME/README.md`~
- [x] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ~... and should be linked from the VFS-facing README for your product~
    - [ ] ~... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it~
    - [ ] ~_(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)~
- [ ] ~_(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)~

### ... measurable

- [ ] ~_(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.~
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] ~This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).~

### Documentation
* **`PRODUCT_NAME`**: Analytics services
* **Product Outline**: N/A
* **README**: N/A - see post-mortem
* **User Guide**: N/A

### Testing

* **Usability test**: N/A
* **Manual QA**: N/A
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: N/A
* **Release plan**: [Template Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17381)

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by joanneesteban** [comment]
## 3 Main Sections

- Clean FL data out of BigQuery
  - Scrub FL data

- Clean FL data out of GA
  - Update GA-pulled cards in Domo
  - Announce to VFS teams
  - Submit the request to Google

OUT OF SCOPE
  - Work with VFS teams to update broken GA dashboards & reports
  - Update API calls to va.gov/performance-dashboard

- Fix at larger scale
  - Audit existing GA for existing PII
  - Update GTM collection
  - Event restrictions
  - Enforce analytics-related privacy reviews

**Comment by joanneesteban** [comment]
GA Scrub effort on our team:

- Fill out form; wait in queue for 7 days
- Backlog the impacted work to prioritize
    - FL updates in GTM
- DEPO to message CJ, Charles, & VFS teams

**Comment by joanneesteban** [comment]
Please comment any additional information about this bug fix on this epic, or if there's additional work involved, please add the tickets to this epic.

@bsmartin-ep @bmcgrady-ep @jonwehausen @JasonTheBearded

**Comment by JasonTheBearded** [comment]
BigQuery Scrub Effort:

- Run UPDATE script across impacted GA session tables (10/11 - 12/8) to set event action to '-' where the event label = 'fl-search-results'

@bsmartin-ep @joanneesteban

**Comment by joanneesteban** [comment]
## Backlog Items

- [ ] Recreate GA dashboards in Domo, OR shift those dashboards to the KPI dashboarding
- [ ] Redirect GA API in VA.gov/performance-dashboard to BQ
- [ ] Create larger flag in GA about the data gap
- [ ] Redirect the FL insights from missing data

**Comment by joanneesteban** [comment]
## Final To Do's before closing this Initiative out

- [ ] Backlog ticket of Domo dashboards that will need to be updated.

(@bsmartin-ep @JasonTheBearded )

**Comment by joanneesteban** [comment]
![image](https://user-images.githubusercontent.com/48964695/105184031-e084f380-5afc-11eb-8cc1-551213cf2b8a.png)

**Comment by joanneesteban** [comment]
See above for data deletion. Closing this epic.
