### ISSUE TITLE
Meet with Lighthouse Team to Explore Existing Endpoints for POA

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#17126]
# Background
Before we get too deep into the POA work we want to explore the existing endpoints that the Lighthouse team has set up so that we can answer two critical questions -

1. How can we interact with the existing endpoints; what parameters can we send to the endpoints to search on, how many parameters can we send at once, do parameters sent need to be in certain combinations, etc?
2. What does the data coming back from the existing endpoints look like; Is the data coming back already formatted as we will need it, will we need to merge multiple objects together or split objects out?

We would like to get answers to these questions documented in GitHub in as much detail as possible so that we can begin the exploration of front end and back end search functionality.

## Considerations 
- A helpful link to the API built by LH can be found here: https://developer.va.gov/explore/benefits/docs/claims?version=current _(scroll down to the bottom for Power of Attorney_
- We need to ask specifically on how to query the OGC database as part of a "search for representative" initiative, endpoints for View, and to submit the form.- Team notes, thus far: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/meeting-notes.md

## Tasks
- [x] Set up a meeting with the Lighthouse team _(PM is Kelly Lein, meet with Andrew Fichter)_
- [x] Meet with the Lighthouse team _(set for Friday at 10:30 am PT / 1:30 pm ET)_
- [x] Document findings

## Acceptance criteria
- [x] A meeting between eBenefits and the Lighthouse team has taken place
- [x] Documentation of the answers to the two questions in the description is in GitHub

**Comment by jason-gcio** [comment]
Another meeting with engineering team to be scheduled in 2021
