### ISSUE TITLE
Update Credstash with New Credentials

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17124]
## Background
Given new information, it appears we need to adjust the credentials with our Ops team in credstash.

## Tasks
- [ ] Update the credentials that the CH31 application uses to submit to.

## Acceptance Criteria
- [ ] Credentials are updated in credstash for the new CH31 endpoints
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
@digitaldrk - this you?
