### ISSUE TITLE
Update `vets-api` with New Endpoints

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17125]
## Background
Given new information, it appears we need to adjust the endpoints used in `vets-api`.

## Tasks
- [x] Update the endpoints that the CH31 application uses to submit to in `vets-api`.

## Acceptance Criteria
- [x] Credentials are updated in `vets-api` for the new CH31 endpoints
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5456
