### ISSUE TITLE
Best bet in search showing a bad link

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17139]
## Issue Description
When searching for "healthevet" on VA.gov one of the top recommendations shows a page with a bad url. The one linking to View Your Lab and Test Results Online sends the user to /health-care/view-test-lab-results/ instead of /health-care/view-test-and-lab-results/ 

Per Mikki, we should do analytics to determine if the bad URL is getting traffic and therefore needs to be redirected.
 ![Screen Shot 2020-12-08 at 2.42.26 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/0efd44d4-c52c-4c70-863e-731feeb22867)

## Tasks
- [x] Update Top Recommendation to point to /health-care/view-test-and-lab-results/
- [x] Do analytics on /health-care/view-test-lab-results/ to determine if redirect needed

## Acceptance Criteria
- [x] Top Recommendation no longer broken

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
@RLHecht best bet is updated and live.

<img width="542" alt="Screen Shot 2020-12-09 at 10 26 32 AM" src="https://user-images.githubusercontent.com/63107147/101649886-5def1b80-3a09-11eb-8c7f-1ad92f1b1514.png">

As for _checking analytics to see if we need a redirect_ -- looks like this page has not been getting any meaningful traffic:

Via Google Analytics/VA.gov:
<img width="1337" alt="Screen Shot 2020-12-09 at 1 07 11 PM" src="https://user-images.githubusercontent.com/63107147/101669312-bd582600-3a1f-11eb-8fac-a2dc2efa11dc.png">

Did a quick Google Search for a key phrase -- and the right page/link is displayed:

<img width="726" alt="Screen Shot 2020-12-09 at 10 27 31 AM" src="https://user-images.githubusercontent.com/63107147/101669406-dd87e500-3a1f-11eb-9693-8806b2b99420.png">


I checked Google Search Console -- and that page is not being indexed.

<img width="1142" alt="Screen Shot 2020-12-09 at 10 31 58 AM" src="https://user-images.githubusercontent.com/63107147/101661585-79acee80-3a16-11eb-93c6-5d03e20feddd.png">

**Comment by RLHecht** [comment]
Excellent. Thanks @johnhashva ! Closing ticket.
