### ISSUE TITLE
Add Sentry attachStacktrace option to enable stack trace for all Javascript Sentry entries

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#17135]
## Issue Description
In Javascript Sentry, certain exceptions don't save a stack trace, making it fairly difficult to trace the error back to the source. I was looking up potential causes for this, and it looks like Sentry with default settings only save a stack trace for Exceptions that we throw an Error class for, not exceptions we throw with simply a string description, or errors that we send to Sentry with `Sentry.captureMessage`. It looks like there's a configuration setting called `attachStacktrace`, disabled by default, that we can add to attach a stack trace to all Sentry logs. Adding this would help us figure out the source for many Sentry logs that we currently don't have many leads for. 

Reference for `attachStacktrace` and other configuration options here: [Sentry config](https://docs.sentry.io/platforms/javascript/configuration/options)
## Tasks
- [ ] In vets-website/src/platform/monitoring/sentry.js, add option to `Sentry.init` -> `attachStackTrace: true,`
- [ ] May want to do the same in vets-website/src/platform/testing/unit/mocha-setup.js ? (Not sure if it matters here, I'm honestly not sure how we use Sentry in test environments)

## Acceptance Criteria
- [ ] In Sentry errors that we create with `Sentry.captureMessage`, we should now see a stack trace
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
