### ISSUE TITLE
Remove Final Time Option for CH31 Callback

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17141]
## Background
The final time option for when a Veteran, dependent, or claimant selects when to be called back needs to be removed.

## Tasks
- [x] Update `vets-json-schema`
- [x] Update `vets-website`
- [x] Update `vets-api`
- [x] Remove the "Other" time option in the UI
- [x] Under Additional Info, the last two questions (years of education, and whether they are moving in the next 30 days) need to be set to be required.
  - [x] Remove the description text that talks about how it is optional:
_"**The information below is optional.** You don't have to answer these questions now, but we may ask for this information again when we process your application."_

<details>

<summary>Image of option to be removed</summary>

![Screen Shot 2020-12-08-at-7 56 57-PM](https://user-images.githubusercontent.com/53826255/101559891-1e381d80-3990-11eb-8ecb-e1fd5728dde3.png)

</details>

## Acceptance Criteria  
- [x] "Other" option is removed 
- [x] Last 2 questions are set to be required
- [x] The description text has been removed
- [x] A PR has been requested for merging
