### ISSUE TITLE
Write Resources & Support article on how to request a debt waiver

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17144]
## Issue Description
As we bring the debt management center content into the modernized VA.gov experience, we need a Resources & Support article on how to request a debt waiver. Since this will be launching before the FSR tool, we'll want this article to reflect the current process for now.

**SEO keywords:**
va waiver
va debt waiver 

**Template to follow to create this page**
- **How to article** template
- **Example:** https://www.va.gov/resources/how-to-get-a-premium-ds-logon-account-online/
- **Requirements for buttons, characters counts, etc:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#content-fields-on-all-learning-center-pages

**References to use to create this page**
- Approved "manage debt" content on waivers (see info on waivers in this pdf: [manage your debt content](https://app.zenhub.com/files/133843125/128a7ddd-7058-4b75-b89d-25de9e1aaefe/download)
- Legacy content from: https://www.va.gov/debtman/Submit_A_Waiver_Request.asp. Content not currently covered in new/approved VA.gov questions: Info on requesting an oral hearing, the fact that waivers can't be granted if there's fraud/misrepresentation/bad faith, details on denied/full or partial waiver notifications, more details on repaying student loan debt, title 38 info.

**Note:** Please make sure it's clear that this is for VA debt related to benefits and not health care.

---
## Tasks
- [ ] Draft article on Resources & Support article on how to request a VA debt waiver (Susan)

**Do not publish article. We'll package all articles for SME review as one and publish all together.**

## Acceptance Criteria
- [ ] Article is in Drupal and ready for Danielle's final review
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@3obryandogs Here's a ticket to work on for debt content. Please reach out with any questions. 

cc @leahkeeler

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA Ideally I would like to launch both at the same time, but not to 100% of traffic, I am not sure that is possible - will discuss with devs. If it is not possible, I would like to launch new content before the FSR, correct.

**Comment by DanielleThierryUSDSVA** [comment]
Okay, great - thanks, @leahkeeler. We could plan to work on 2 versions of content if need be.

**Comment by 3obryandogs** [comment]
@DanielleThierryUSDSVA, is this what you had in mind?
[How to request a debt waiver.docx]
https://github.com/department-of-veterans-affairs/va.gov-team/files/5667190/How.to.request.a.debt.waiver.docx

**Comment by DanielleThierryUSDSVA** [comment]
@3obryandogs - In general, the step-by-step approach part, yes. But not the FAQs beneath them from the legacy content. The how-to template won't support them, and we don't want to just pick up the legacy content. We want to use that content as a reference and weave the key points from it into the step-by-step as relevant/appropriate. So, for example, info on an oral hearing might be woven into a later step as a note or a separate "if you need this" step.

Feel free to take your time with this over the next few days to think through how to weave the important pieces of this content in this format.

**Comment by 3obryandogs** [comment]
@DanielleThierryUSDSVA - Thank you!

**Comment by 3obryandogs** [comment]
@DanielleThierryUSDSVA - I've reworked the step-by-step and eliminated the questions. Your thoughts?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @3obryandogs. I don't see an attachment in the comment above. But as we talked about in the call, go ahead and take some time and work on this a bit, look at other pages for guidance/examples. Thanks!

**Comment by 3obryandogs** [comment]
@DanielleThierryUSDSVA - Hopefully it's there now. Thank you!

[How to request a debt waiver.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5674500/How.to.request.a.debt.waiver.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @3obryandogs. I'll review when I can. Will also post another issue for you to work on as soon as I'm able. Thanks.

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA @brianalloyd  - Is this ticket going into sprint 39? or is this complete in 38 for y'll? Want to make sure we are in sync as this heads towards release.  Thanks both!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. This is not complete at this time. 

@brianalloyd  This is one that we can probably remove from PW since it's a purely content article. 

Thanks!

**Comment by brianalloyd** [comment]
Thanks @DanielleThierryUSDSVA concur, I'll remove our label.  Thanks again.

**Comment by DanielleThierryUSDSVA** [comment]
@leahkeeler As we talked about, since I ended just jumping into this work, I'm going to close out this ticket and create a separate one to track all the content work. Thanks!
