### ISSUE TITLE
"Keep me informed" tool: Content updates based on V1 review

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17150]
## Issue Description
We need to make some content tweaks based on V1 VHA leadership review.

**Notes:**

- Write a contextual note re: why we want to collect SSN and DOB (may be optional).
- One thing we're adding (but isn't merged yet) is another emphasis on the disclaimer at the top of screen 2 (form screen). This will be important to addressing the "not a sign up for the vaccine" concern.
- Write another version of the "not a sign up" disclaimer that's more explicitly "You're not signing up to get a vaccine here" for testing.
- Create 1-2 more versions of the "interest" question for testing.
- For the enrolled/receiving care piece: We have a link back to the content page to "Learn who will receive the vaccine first..." so that may be enough to lead folks to that info if they want it. On the content page, we'll need to add "and receiving care" message to our "Eligibility and cost" statement.

---
## Tasks
- [x] Draft versions of content areas that need to be tweaked
- [x] Finalize w/ team
- [x] Handoff to dev
- [x] Implemented

## Acceptance Criteria
- [x] Updated content is in staging
- [x] We have versions of content pieces we want to test with Veterans
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
# Interest question other version options

**V1**

**Do you plan to get a COVID-19 vaccine when one is available to you?**

- Yes
- No
- I'm not sure yet.
- I prefer not to answer.

**V2**

**Which of these best describes your current thoughts on getting a COVID-19 vaccine?"

- I plan to get the vaccine as soon as I can.
- I don't plan to get the vaccine at this time.
- I'm not sure yet if I want to get the vaccine.
- I prefer not to answer this question.

**Comment by DanielleThierryUSDSVA** [comment]
# Optional field notes

@batemapf let me know what you think of these.

- Not sure that we need to be explicit about "You don't to provide" so we can remove if not needed.
- Not sure if "VA health records" or just "Veteran records" is best.

Date of birth
**Note:** Your date of birth helps us match your information to your VA health records so we can better understand your needs. (You don't have to provide this information.)

Social Security number (SSN)
**Note:** Your SSN helps us match your information to your VA health records so we can better understand your needs. (You don't have to provide this information.)

**Comment by DanielleThierryUSDSVA** [comment]
# Intro page updates

## H1 update

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/92250e23-8264-4a0c-9456-b02431a823ad)

Change the em dash to a colon to read:

**COVID-19 vaccines: Stay informed and help us prepare**

## Body copy and link updates

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/721fdd92-9249-4b6a-80d6-0a7485e6d0e1)

- Paragraph 1, sentence 2: Delete the word "regular" to read: <br> We’ll send you updates on how we’re providing vaccines across the country—and when you can get your vaccine if you want one.

- Note, sentence 3: Change the words "communicate with you" to "keep you informed" to read: <br> We’ll use the information you provide to understand your interest and keep you informed.

- Last paragraph (link): Make the statement a link to the main COVID-19 vaccine mini hub, and delete the period at the end to read:
[Learn who will get a COVID-19 vaccine first based on CDC guidelines](/covid-19-vaccine/]

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn updates to form page below

# Changes to form page

## Update to text

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/2e9b7411-7e78-4264-9811-ad0f3b96fa44)

- Sentence 1: Delete the word "regular" to read: <br> We’ll send you updates on how we’re providing COVID-19 vaccines across the country—and when you can get your vaccine if you want one. You don't need to sign up to get a vaccine.

## Update to DOB and SSN fields

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/7881a1f4-30d0-4988-8f42-180277711e8a)

- Add the following note between "Date of birth" and the fields: <br>**Note:** Your date of birth helps us match your information to your Veteran records so we can better understand your needs.

- Add the following note between "Social Security number (SSN)" and the fields: <br>**Note:** Your SSN helps us match your information to your Veteran records so we can better understand your needs.

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn Updates to confirmation page below. Also, I added one more update to the form page above (update to interest question). Tried to submit form in staging to get a screenshot of confirmation page, but it just sent me back to intro so showing change in copy-only image below.

# Confirmation page updates

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/d09a7c00-43e8-4fd5-bb4a-9a973b6a2d38)

- **Remember** note: Replace with the following text: <br> **Remember:** This form doesn’t sign you up to get a vaccine. And you can change your mind about getting a vaccine at any time. We’ll use the information you provided to understand your interest and keep you informed. If you want to update your information later, you can submit a new form.

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn Here's the already submitted note.

# You already submitted this form note.

Our records show you provided the information below on {timestamp}. If you’d like to update your information, please make any updates below and click **Sign up to stay informed**.

**Comment by stephenBarrs** [comment]
@DanielleThierryUSDSVA  here is PR for content updates.  Please let me know if I need to tweak anything.  Thanks!
https://github.com/department-of-veterans-affairs/vets-website/pull/15306

**Comment by ncksllvn** [comment]
@DanielleThierryUSDSVA the heading currently says `You already submitted this form note.`. Should the word "note" be there?

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn No. Sorry, that's just a header to show what piece of content to update. I don't think we need a header at all for that message, right?

**Comment by ncksllvn** [comment]
Ohhh I misunderstood @DanielleThierryUSDSVA - thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Completed and closing.
