### ISSUE TITLE
IRIS Q&As: Education -- General

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#17151]
### Issue
For the launch of Learning Center MVP 1.1, content that fall into the "general" category under education & training needs to be developed based on the following:

- https://gibill.custhelp.va.gov/
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)
- Credible external sources as needed

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

- [x]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

 - [x] PW to develop draft copy (Laura)

 - [ ] PW to assign tags (Laura)

 - [x] DEPO to complete substantive edit (Beth) 

- [x] ~PW to copyedit draft (Randi)~ We'll wait on the copyedit until after stakeholders send us feedback.

 - [x] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [x] Copy deck ready for 2nd DEPO review and attached to a content review GH ticket.

### Up-to-date copy deck
Please use the deck shown here and replace it when you make edits/comments to ensure that the latest document is always here, at the top of this ticket. 
[rs-1.1-education-general-v0.2-12-09-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5666706/rs-1.1-education-general-v0.2-12-09-20.docx)

**Comment by lwalsh617** [comment]
Hi @bethpottsVADEPO, the copy deck is at the top of this ticket. Let me know when it's ready for Randi to proof and I'll tag her. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I split this doc into two chunks to make sure SMEs had time to review at least some of these Q&A before the freeze. Here's the doc with my edits (I cleaned up the formatting and sent these 4 articles to them): 
[rs-1.1-education-general-v0.1-12-04-20.bp.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5691207/rs-1.1-education-general-v0.1-12-04-20.bp.docx)

Can I get a replacement Certificate of Eligibility?
How VA education payments affect your taxes
How do I get college credits for my military experience?
What if my school closes because of a hurricane or natural disaster? (I'll need to think about this H1 since a hurricane is a natural disaster, but there isn't available character count to say: "hurricane or other natural disaster")

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Going forward with tickets, let's use this approach:
1/ Ticket for your initial work writing the chunk of articles, and creation of the rest of the tickets, listed below.
2/ Ticket for my substantive edit pass, and contacting SMEs for review.
3/ Ticket for incorporating SME feedback.
4/ Ticket for copyediting and publishing.

**Comment by bethpottsVADEPO** [comment]
If you're done with the other tasks listed above, you can close this ticket @lwalsh617

**Comment by lwalsh617** [comment]
Closing this ticket. Opened ticket [17449](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17449) to capture SME feedback/revisions.
