### ISSUE TITLE
Set Up Test User Dashboard Application to be run in EKS

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17157]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The Test User Dashboard has a front-facing application that needs a subdomain.  The previous requirements suggested that it be setup behind the SOCKS proxy.  After further evaluation, the Identity team suggested that the site be built with using some kind of OAuth authentication that has integration into the Github API [researching possible authentication providers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19243).

---
## Tasks
- [x] Set up subdomain (https://**tud**.staging.va.gov)
- [x] Set up EKS to host the built site
- [x] Set up any access to resources to only staging resources (staging-api.va.gov & associated DBs)

## Acceptance Criteria
- [x] I can access the subdomain site (https://tud.staging.va.gov) as a an unauthenticated user
- [x] Ensure site is only built for **staging** and only has access to those associated resources

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@jhouse-solvd Is there anything I need/can do to help get the hosting / SOCKS proxy up for the VSP Test User Dashboard?

**Comment by AGarcia-Clarity** [comment]
@dginther Is there anything I need/can do to help to setup the hosting and SOCKS proxy up for the VSP Test User Dashboard?  I will start setting up the CircleCI `config.yml` and Docker stuff to work in the `vsp-test-user-dashboard` repo.

**Comment by jhouse-solvd** [comment]
@AGarcia-Clarity - so sorry for not responding sooner. wanted to follow up on this and see what's left / needed from the Ops perspective so that we can assist if possible?

**Comment by AGarcia-Clarity** [comment]
@jhouse-solvd - not a problem at all I know the Ops team has been spread pretty thin.  Because of stakeholders input there was a slight change in requirements and the SOCKS proxy is no longer required.  Instead we will be implementing auth for the site.  So what I need is hosting & a subdomain set up for the `vsp-test-user-dashboard` repo.

I will verify the subdomain URL with my team.

**Comment by AGarcia-Clarity** [comment]
@jhouse-solvd Because the site will only be used for the staging environment.  The team has decided on a subdomain of `https://tud.staging.va.gov`.  Thank you.

**Comment by jhouse-solvd** [comment]
@AGarcia-Clarity - okay, great, thanks for the additional info. to clarify, the ask is for the Ops team to set up the tud.staging.va.gov subdomain in the platform's DNS, correct? are there specific hosts that this subdomain should point to for now, or do we just need to add the subdomain and your team will add specific hosts... forgive me if that's unclear. just wanting to make sure I understand what's needed. :)

**Comment by AGarcia-Clarity** [comment]
@jhouse-solvd, Yes please add it to the platforms DNS.
As for the hosts, let me rope in my colleagues. @bramleyjl @jimiray @joeniquette ☝️  Do we want to point to a specific host for now or can we set this up later (possibly after auth)?

**Comment by joeniquette** [comment]
@jhouse-solvd is there a standard OP we should follow for hosting this service? I would assume its a stand alone host (EC2/fargate/whatever) but I wouldn't want to draw outside the lines on this. If there are no other services running within our current AWS stack that are like this, then we can partner on charting our own path.

**Comment by jhouse-solvd** [comment]
@joeniquette - @dginther is gonna follow up w/ y'all on this

**Comment by AGarcia-Clarity** [comment]
@dginther Is there any update on this? Specifically if you know which sprint it will be pulled into?  Thank you!

**Comment by jhouse-solvd** [comment]
@AGarcia-Clarity & @bramleyjl - Christine and I have discussed what's needed here and are setting up a call to discuss so that we get together and chat technical next steps / todos.

**Comment by jhouse-solvd** [comment]
#24307 has more accurate and relevant information which is helping us track towards the completion of this. @bramleyjl - maybe we could close this one in favor of that one? I want to make sure we are communicating and tracking in the most efficient way and don't lose any relevant info or tasks at the same time. let me know what you think? :)

**Comment by AGarcia-Clarity** [comment]
^ @jhouse-solvd Yes, we can close this one in favor of the Kubernetes Onboarding ticket as it tracks the individual tasks.
