### ISSUE TITLE
[FE] Re-org Code Folder

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#17159]
## User Story
As a veteran, 
I want va.gov codebase to be in an organized structure
So that features are easily created

## Description
> this should be a plain English description of what the ticket is
Now that we know the URL structure and where we fit into the va.gov ecosystem, the front end team wants to rework the folder structure to better represent what we are doing. 

## Tasks
- [ ] move the code form `healthcare` to `health-care-questionnaire`
- [ ] Update the code owner file 

## Acceptance Criteria
> when is the ticket done 
- [ ] PR has been merged into master

**Comment by mdewey** [comment]
Folder has been updated: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/health-care-questionnaire
