### ISSUE TITLE
Error messages for COVID-19 vaccine "Keep me informed" tool

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17152]
## Issue Description
We need plain language error messages for the COVID-19 vaccine "Keep me informed" tool.

---
## Tasks
- [ ] Identify error messages needed
- [ ] Write error messages
- [ ] Implement messages

## Acceptance Criteria
- [ ] Error messages are implemented in tool
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hey @ncksllvn @stephenBarrs. Just creating this issue so we have a place for any error messages we might need. If you identify any that don't already have standard messaging, feel free to drop in here and tag me and I'll write the messages. Thanks!

**Comment by ncksllvn** [comment]
Hey @DanielleThierryUSDSVA this is the only error message we show currently. It's just a generic catch-all if the server doesn't indicate success after the user submits the form.

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/33e161d6-9be7-4d5c-a734-d999ef91e228)

Once the captcha work continues though, we may have another error state to look for.
