### ISSUE TITLE
Identity: Detailed view of test user account

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17165]
## Issue Description
As a frontend engineer, I can view more details about a test user accounts credentials, so that I can see if the user's details fits within my scenario.

---
## Tasks
- [ ] Creates ___ to view more detailed information of a user (modal or dropdown*)
- [ ] Detailed information of a test user includes _____ fields

## Acceptance Criteria
- [ ] I can see detailed information about a test user's credentials
- [ ] The ____ feature is in compliance with 508c & WCAG standards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
