### ISSUE TITLE
Test User Account Dashboard - Frontend Work

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17160]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a frontend engineer, I need to accomplish these tasks so that we can complete this VSP-Initiative.

## Hypothesis or Bet
**If** we make this change **then** we expect users to be able to use the Test User Accounts Dashboard.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete?
- [x] I can see a front-end web application
- [x] I can see a table with test account credentials
- [x] I can filter a table for different categories based on my requirements from UX (by Service Provider, by LOA1/3, by Availability, etc)
- [x] I can view more details about a test accounts credentials 
- [x] I can create a new test user (or copy an existing user) with specific credentials (environments, services, service providers, etc) that interfaces with staging
- [x] I can check out/in a test user account
- [x] I can read an information page and/or documentation on how to use test user accounts

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by nsoutouras** [comment]
Closing as TUD is transitioned to Testing Tools Team
