### ISSUE TITLE
Identity: Filter tables fields

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17164]
## Issue Description
As a frontend engineer, I can filter a table's fields based on requirements from UX (Service Provider, LOA1/LOA3, Availability, etc.)

---
## Tasks
- [x] Find out all table fields that need to be filterable (by Name, LOA1/LOA3, ICN, etc.)
- [x] Receive filtered data from the TUD API based on query parameters
- [x] Update filtered table based on data
- [x] Checked out user field filters table is enabled by default (Checked in/ Checked out/ All)

## Acceptance Criteria
- [x] I can filter a table's fields and find the test user I am looking for
- [x] The table is in compliance with 508c & WCAG standards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
TODO:
- [ ] Gather table filtering requirements (from Peter Hill & UX => {
Name
Birthday
Gender
Id Type
Authentication Type
Account Type (kind of like LOA1/3)
 - Basic
 - Advanced
 - Premium
Standard/Custom
Account Availability
}
- [ ] Update filtered table based on data
  - [ ] Create query filters for API consumption via HEAD request for information ({ startRow, endRow, numberOfAccounts })
  - [ ] Handle data from API via a GET request & data transformation possibly
  - [ ] Create default query parameters (ex. `page=1&filter=default`) Then API side can handle filtering out unavailable
