### ISSUE TITLE
Identity: CRUD for test user on the frontend

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17167]
## Issue Description
As a frontend engineer, I can create a new test user (or copy an existing user) with specific credentials (environments, services, service providers, etc) that interfaces with staging.

---
## Tasks
- [ ] Creates a new user by ____ (new view, modal, etc.) and using a POST request to hit the TUD API
- [ ] Clones an existing test user with a new UUID by sending a POST request to the TUD API with an unique field (possibly email)
- [ ] Updates/deletes existing test users by sending a POST request to TUD API (*for custom users only)

## Acceptance Criteria
- [ ] I can create a new user and see it in the front-end
- [ ] I can clone an existing user (with the UUID changed) and see it in the front-end
- [ ] I can update / delete existing custom test users and see it in the front-end
- [ ] CRUD operations are 508c / WCAG compliant
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
Some questions --
* Who has been contacted to discuss support for CRUD operations?
* What is the status of each of those conversations?
  * Have we indicated that we do want to get our request for CRUD onto the roadmap for the dev teams supporting these services?
