### ISSUE TITLE
Add react widget to View Your Payment History page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17169]
## Issue Description
To support the eBenefits team on their View Payments work, we need to add a flipper react widget to the View Your Payment History page. Before implementation we need to review the content. The widget is replacing the alert with CTA button currently on the page.

Page to work on: https://www.va.gov/va-payment-history/

Flipper unique ID: view-payment-history

Ticket #16957 for reference

## Tasks
- [x] Review content in flipper (Randi)
- [x] Add react widget (Selina)
- [x] Review and publish (Randi)
- [x] Alert eBenefits team work is complete

## Acceptance Criteria
- [x] Flipper is live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA here's the wording they have for the widget. I'm thinking we should change to active voice: "You'll need to sign in first with your DS Logon, My Healthevet, or ID.me account. If you don't have any of those accounts, you can create one."![Screen Shot 2020-12-10 at 9.25.49 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/499717a4-91dc-4d08-82a6-c19f8145a2f1)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Can we model content after existing sign-in modals like:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b1ea6a43-cfe2-4eb5-9ec8-fe02474b4d96) 

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b5ac8233-a651-41c3-b66f-181809d61348)

**Comment by RLHecht** [comment]
@jason-gcio See Danielle's comment above. Can we please change the language in the widget to the following:

H3 Please sign in to view your VA payment history
Try signing in with your DS Logon, My HealtheVet, or ID.me account. If you don't have any of those accounts, you can create one now.

Then the button should be:
Sign in or create an account

**Comment by RLHecht** [comment]
The widget has been added to the page. New language is being merged today so after deployment should be live on site. Moving to validate and will close later today. FYSA @jason-gcio @brianalloyd

**Comment by brianalloyd** [comment]
Awesome, @RLHecht and @DanielleThierryUSDSVA for the quick turn on this, thanks.

**Comment by RLHecht** [comment]
widget is live on site. Closing ticket. FYSA @jason-gcio
