### ISSUE TITLE
RD: Front End Display

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1716]
## User Impact
Knowing how the front end displays information will better inform the team how to be the most effective with that data.

### Tasks
- Investigate and see if there is any current code that can be reused.
- Locate or define the standard or best practice.
- Document any error codes and what they do.

### Considerations 
- How does the front end get displayed to the user?

### Definition of Done
- [x] Established whether there is any code that can be reused.
- [x] Able to refer to a standard or best practice (our own or preconceived)
- [x] List of error codes found with definitions.
- [x] Pull any data and display

### Notes
- What did we learn about those exceptions?
- [ ] Any notes for the Call Center should be uploaded to `feature/$feature-name/call-center` in GitHub

**Comment by micahchiang** [comment]
@jason-gcio - I've updated the definition of done for this ticket to include 'pull and display data' originally from #1720. I think this is a more appropriate place for this definition of done to live, as this ticket has more to do with displaying data.

**Comment by sporeboy** [comment]
@micahchiang I'd say the **Related To** column shows "special_issues... name"

**Comment by micahchiang** [comment]
A thought to consider - Can there be more than one special issue? special_issues is an array so it seems possible. If so, what is the best way to display multiple special issues in the Related To table field?

**Comment by micahchiang** [comment]
As outlined here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/front-end-standards/react/

Any new application should consider using a Container Component as a single point of connection to the redux store. All other react components should be handed props down the component chain from this Container component.

**Comment by sporeboy** [comment]
I've review the current frontend code and the MD files for clues as to how the screen are built. I believe Micah has a good handle on this. Of course discover is ongoing. A few things to bolt down:

--MD formatting for React pages (layouts, templates, etc.)
--Responsiveness of components used--particularly the table component
