### ISSUE TITLE
Identity: Check out a test user

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17170]
## Issue Description
As a TUD app user, I can click a **Sign in** button that will take me to the `staging.va.gov/sign-in` page, so that I can get to using a test account faster.

---
## Tasks
- [x] Implement a link that navigates to the `staging.va.gov/sign-in` page

## Acceptance Criteria
- [x] I can check out a user and get automatically get sent to (staging.va.gov) Sign In page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
