### ISSUE TITLE
Identity: Check in a user

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17172]
## Issue Description
As a frontend engineer, I can check in test user account

---
## Tasks
- [x] When I log out of staging.va.gov, a check-in POST request to TUD API which marks the user account as checked-in
- [x] If the userSession or userSessionSSO is inactive, a check-in POST request to TUD API which marks the user account as checked-in
- [x] The Login/Checkout button is enabled and can be checked out again (and possible color change)
- [x] The checked in user account is viewable (again)

## Acceptance Criteria
- [x] I can check in a user and view the user (and the ability to check out again) in the table
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
