### ISSUE TITLE
Medallia Research Read Out

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#17176]
## Issue Description
- Present final Medallia research read out to appropriate DEPO stakeholders

---
## Tasks
- [x] Finish Medallia read out deck
- [x] Schedule meeting with appropriate DEPO stakeholders
- [ ] Deliver presentation with DEPO
- [x] Determine next steps in regards to recommendations and next steps

## Acceptance Criteria
- [x] Read out was presented and handed over to DEPO
- [x] Concrete, actionable next steps are determined

**Comment by ianMcCullough-ob** [comment]
Presentation was handed over to Kevin Hoffman who approved the recommended changes. Will launch with out-of-the-box Medallia button then implement recommendations in the near future.

Research read out dec is attached.[https://app.zenhub.com/files/133843125/b4da54bd-dbc2-4c1e-9947-10c735277fda/download](https://app.zenhub.com/files/133843125/b4da54bd-dbc2-4c1e-9947-10c735277fda/download)
