### ISSUE TITLE
RD: UX Error Analysis

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1717]
## User Impact
How does UX ensure the errors are meaningful?

### Tasks
- Research/analyze best practices
- Document what is being done now & what's not happening now but should

### Definition of Done
- [x] Identified best practices
- [x] List of what needs to change

### Notes
- What did we learn about those exceptions?
- [ ] Any notes for the Call Center should be uploaded to `feature/$feature-name/call-center` in GitHub

**Comment by sporeboy** [comment]
I reviewed errors and alerts on the VA.gov Design System site--and in the VA.gov Sketch doc.

In the presentation layer, screen-level errors and alerts are displayed via React AlertBox components. These are styled with a series of properties that will determine the type of message, and its look. Guidance regarding error text and remedies presented will be provided by the content team. The is boilerplate copy that is used throughout VA.gov.

Automatic log-out occurs after X minutes of inactivity. A modal appears prompting the user to reset the activity timer. If there is no reset, the user is redirected to a signed-out screen that provide the user a secondary sign-in button.

**Comment by sporeboy** [comment]
The Rated Disabilities screen has the potential for several alerts/errors:

     • No data (but no error) for Total Combined Disability, Rated Disabilities Table, and/or Pending Disabilities Table.
     • Error returned for Total Combined Disability, Rated Disabilities Table, and/or Pending Disabilities Table.

Error states mocked-up here: https://xd.adobe.com/view/ebfa6df6-c0aa-4ea9-413e-98793ba7a5a3-9dcb/

Passive log-out will be handled via the site's inactivity timer and modal.
