### ISSUE TITLE
EKS - re-deploy Loki in DEV

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#17177]
## Issue Description
Deploy an instance of Loki into `dev` environment hosted in an EKS cluster.

Requirements:
* Loki deployed via helm chart
* Loki deployed into `platform-tools` EKS cluster in separate namespace
* Loki is deployed in microservices mode
* Loki is using BoltDB shipper + s3 bucket for storage
* Loki is logging to itself via promtail installed on EKS cluster
* `platform-tools` EKS cluster is logging to this Loki instance

---
## Tasks
- [x] (Pre-req) `platform-tools` cluster deployed in DEV
- [x] Create Loki helm chart for microservices deployment in staging

## Acceptance Criteria
- [x] At least one host can successfully ship logs to Loki staging instance via Promtail
- [x] At least one Docker container can successfully ship logs to Loki staging instance via Docker driver
- [x] EKS Cluster is logging to this Loki deployment 
- [x] Grafana in `utility` can see this Loki deployment as a Data Source
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pnwstevan** [comment]
Helm chart is created but not sure where to store it?

**Comment by pnwstevan** [comment]
This was completed and Loki has been deployed in microservices mode on the `platform-tools` EKS cluster in DEV:

```
└─▶ kubectl -n loki get pod
NAME                                       READY   STATUS    RESTARTS   AGE
loki-dev-distributor-6866f8754b-4zl87      1/1     Running   0          17d
loki-dev-gateway-745bcff6b-w66s2           1/1     Running   0          17d
loki-dev-ingester-0                        1/1     Running   0          17d
loki-dev-ingester-1                        1/1     Running   0          17d
loki-dev-querier-0                         1/1     Running   0          17d
loki-dev-query-frontend-75c8f78d84-8w89t   1/1     Running   0          17d
```

**Comment by pnwstevan** [comment]
All hosts in DEV are now logging to this new Loki instance per this PR:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/17788
