### ISSUE TITLE
SPIKE: Validate feasibility of CloudPosse Terraform EKS Module

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#17184]
## Description
We had developed and internal terraform module for building and deploying EKS clusters in dsva-gov:

https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks

It generally works but didn't have support for key things like node groups, workers, etc..

It was discussed the possibility of using the CloudPosse module instead, which contains broader support but may have challenges working with the way our environment is setup.

This spike would validate whether we could use the CloudPosse module instead of the custom written module.

Further progress on Loki is dependent on this in order to avoid redeploys.

## Background/context/resources
https://github.com/cloudposse/terraform-aws-eks-cluster

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Look at CloudPosse EKS module
- [x] Deploy a test EKS cluster using Cloud Posse Module

## Definition of Done
- [x] Decision on whether the Cloud Posse module can be used

---
### Reminders
- [ X Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
Looks like this module works, and the `platform-tools` cluster in DEV has been deployed, along with Loki, Promtail and ArgoCD and seems stable.

There are 2 outstanding issues:
- aws-auth needs to be disabled AFTER provisioning, or non-ops users will be blocked in tf updates as they won't be able to read the config map.
- Tags aren't currently working as Cloud Posse has a whole tagging thing.

**Comment by jhouse-solvd** [comment]
Regarding 2 outstanding issues in Stevan's comment above: 

In speaking with Demian, 

1. aws-auth needs to be disabled AFTER provisioning, or non-ops users will be blocked in tf updates as they won't be able to read the config map. -- this is something that we will want to document as a "need to know" when setting up a cluster. added that to[ this ticket #17486 ](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17486)
2. Tags aren't currently working as Cloud Posse has a whole tagging thing. (TBD). will leave ticket open until we decide where/how to address this
