### ISSUE TITLE
EKS - deploy "platform-tools" cluster in UTILITY VPC 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17182]
## Description
Deploy a `platform-tools` EKS cluster in `utility`.

This will be a permanent cluster and used by both VSP Operations and other teams to host tools/services to support the VSP Platform (ie: Sentry, Grafana, Loki, etc..)

## Background/context/resources
* Should use the terraform module to provision cluster
* Should pre-provision authentication configmap with Ops team members
* Node groups should use Terraform for deployment
* [Create and deploy a Kubernetes/EKS Cluster in VSP](https://vfs.atlassian.net/wiki/spaces/VI/pages/871202823/Create+and+deploy+a+Kubernetes+EKS+Cluster+in+VSP)

## Technical notes
Should be able to copy the module information from the already deployed DEV "platform-tools cluster"

---
## Tasks
- [x] Deploy a permanent EKS cluster in `utility` for platform-tools
- [x] Create node group and worker nodes in cluster

## Definition of Done
- [x] Everyone in VSP Ops can access/use "platform-tools cluster in utility VPC

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by mleclerc00** [comment]
Unable to deploy platform-tools cluster in the utility VPC as it stands currently due to the lack of IP addresses in subnets A (11) and subnet B (13).

Subnet c has 49 available IP addresses so as discussed in prior meetings we will likely need to shift around resources in order to give us the ability to deploy the cluster successfully.

**Comment by jhouse-solvd** [comment]
Adding dependency and moving back to ready column so that we can pick this up next sprint. OR, if we remove the block and can still accomplish this sprint, please move back to current sprint and feel free to proceed.

**Comment by jbritt1** [comment]
We moved away from the "platform-tools" nomenclature, but do have a working EKS cluster in utility. Is this okay to close at this time?
