### ISSUE TITLE
[HOLD UNTIL JAN. 4] Add "apply now" link to left nav for Chapter 36

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17188]
## Issue Description
After the Chapter 36 form is live on January 4, we need to add a link in the left nav for users to apply.
In Careers and employment the link "Apply now" should be a child of Educational and career counseling.

Link to use: www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/

**Note:** Mikki's IA summary/suggestions, for reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt36.md

## Tasks
- [x] Add link to left nav (Randi)

## Acceptance Criteria
- [ ] Apply now option is now showing on live page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This work has been done. moving to validate.
