### ISSUE TITLE
EKS - Need platform-tools cluster in STAGING

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17183]
## Description
Deploy a `platform-tools` EKS cluster in `staging`.

This will be a permanent cluster and used by both VSP Operations and other teams to host tools/services to support the VSP Platform (ie: Sentry, Grafana, Loki, etc..)

## Background/context/resources
* Should use the terraform module to provision cluster
* Should pre-provision authentication configmap with Ops team members
* Node groups should use Terraform for deployment

## Technical notes
Should be able to copy the module information from the already deployed dev "platform-tools cluster"

---
## Tasks
- [x] Deploy a permanent EKS cluster in `staging` for platform-tools
- [x] Create node group and worker nodes in cluster

## Definition of Done
- [x] Everyone in VSP Ops can access/use test EKS cluster as validated by `kubeconfig`

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by mydesignrocks** [comment]
This is now complete
`dsva-vagov-staging-platform-tools-cluster` is now available.
following command to include the new cluster/context: `aws eks --region us-gov-west-1 update-kubeconfig --name dsva-vagov-staging-platform-tools-cluster`
ip addresses are looking OK for staging vpc

**Comment by jhouse-solvd** [comment]
This is complete per Sri's notes. Closing.
