### ISSUE TITLE
Document grafana to determine what's need to move it to EKS 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17180]
## Issue Description
_Ensure that we've fully documented current architecture / configuration of fwdproxy to ensure that we can move it to the new infrastructure with minimal impact to the platform._

---
## Tasks
- [x] _Written documentation that clearly explains fwdproxy's configuration and setup in sufficient detail_
- [x] _Supporting architecture / configuration diagram_

WIP DOC (not started yet)

## Acceptance Criteria
- [x] _fwdproxy configuration and dependencies are well documented_
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
