### ISSUE TITLE
Identify IAM requirements for applications to access SSM Parameter Store

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17186]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
We need to know how to get to the parameters we're creating.

---
## Tasks
- [x] Research SSM access information. 

## Acceptance Criteria
_What will be created or happen as a result of this story?_
- [X] We will know what permissions are needed for applications to access SSM parameters natively.

---
## How to configure this issue
- [X] **Attached to a Milestone** (when will this be completed?)
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
@jsev-io - please see this ticket to harvest any relevant info. detaching from this epic.

**Comment by jsev-io** [comment]
@jhouse-solvd Let's make this a story, not an epic.

**Comment by jsev-io** [comment]
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-hierarchies.html
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-labels.html
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-versions.html
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameter.html
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameters.html
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html

**Comment by jsev-io** [comment]
Provided all relevant SSM Access Information in comment.
Closing ticket.
