### ISSUE TITLE
RD: Internal 508 Breakout

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1718]
## User Impact
508 Compliance is important for ensuring that all users can access the features set forth.

### Tasks
- Investigate more about how Rated Disabilities fares in 508

### Considerations 
- 508 can be quite involved, lets just establish the landscape at this point.

### Definition of Done
- [x] Complete meeting with 508 team **(set for Friday, September 13 at 12 pm ET)**
- [x] Define 508 checklist or reference 
- [x] Include links to 508 review request and Trevor's best practices
- [x] Check with Amen Ra (`@Amen Ra`, in Slack) for useful tools

### Notes
- What did we learn about those exceptions?
_508 Checklist can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/508-checklist-wip.md)_
- [ ] Any notes for the Call Center should be uploaded to `feature/$feature-name/call-center` in GitHub

**Comment by sporeboy** [comment]
508 overview and checklist is updated in team repo. List includes best practices, resources, tools, detailed checklist, and review processes.
