### ISSUE TITLE
Schedule UAT for CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17194]
Conduct user acceptance testing (UAT) for VA Form 28-8832 and wizard (Chapter 36).

### Considerations
UAT will include screening wizard and form submission.

### Tasks
- [x] Create UAT plan
- [x] Create conversation guide/acceptance punchlist
- [x] Submit RP and CG for review
- [x] Deliver RP and CP to Lauren A.
- [x] Schedule and prepare to conduct UAT sessions

### Acceptance criteria
- [x] UAT plan created
- [x] Convo guide/punchlist created
- [x] UAT sessions scheduled

**Comment by sporeboy** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/uat/ch36-uat-research-plan.md

Conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/uat/ch36-uat-convo-guide.md
