### ISSUE TITLE
[UI] Write VSP Tickets for Design Council to Review

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#17199]
## Description
> The VSP team will get three tickets to evaluate for possible additions to the VA Design system.
- Submitting our use case for tabs, so tabs can be added to the design system.
- Requesting additional documentation on cards design (max. width, etc) 
   - [Review Slack thread on this](https://dsva.slack.com/archives/C0NGDDXME/p1607450074385000)
- Privacy Act Statement variation and customization
- Review of statuses across va.gov. There are currently inconsistencies. 
  - I brought up the topic of statuses during the DEPO Design Hours on January 19, 2021. @emilywaggoner stated that she will take this topic to the design council, so I will not write a ticket for this item. I also sent her the associated audit that I completed of statuses, which is listed in the comments of ticket #17805. I also sent images of the health questionnaires use case to be added to the audit.
- Error message visual documentation (check into this more before writing).
- Dynamic title, expiration date, and URL (unique identifier)
- Confirmation page standardization.

## Tasks
- [x] Review current VSP tickets to make sure that none of these items already exist
- [ ] Write one VSP ticket for each item, provide use cases and justification for changes, user research results, etc.

## Acceptance Criteria
- [ ] When all appropriate VSP tickets are submitted

**Comment by kristenmcconnell** [comment]
**Draft of the VSP ticket for tabs...**

 Title: Feature Request - Tabs component  # Feature Request

# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: VAOS has tabs implemented and Health questionnaires plans to implement them as well, but they aren’t part of the design system yet.

## Do you have a suggestion for a new component or utility?


## Additional context
Screenshot of tabs within VAOS
![Screen Shot 2021-01-13 at 6.00.43 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/0eed433c-5721-4efc-807e-933e9f7f0209)

Screenshot of tabs within Health questionnaires
![Screen Shot 2021-01-13 at 6.02.39 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9fc094ef-b231-410f-b76e-5f0788d62224)

**Comment by kristenmcconnell** [comment]
Title: Documentation request: Width suggestions for cards

# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [X] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

This request is for additional documentation on the suggested widths of cards.

## What is the nature of this update?

Please review the attached Slack thread to understand what was missing from documentation that resulted in clarification being needed related to widths of cards. https://dsva.slack.com/archives/C0NGDDXME/p1607450074385000

- [X] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

**Comment by kristenmcconnell** [comment]
Title: Feature Request - Privacy Act Statement variation and customization  # Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Two changes are proposed for the Privacy Act Statement modal, in order to address current use cases.
![Screen Shot 2021-01-19 at 1.37.29 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/78c84708-7410-423d-9af3-61a2814e705b)

## Do you have a suggestion for a new component or utility?
1. The first line of the respondent burden paragraph within the privacy act statement always states the feature is for “education benefits,” even when the feature is something else like the caregiver or health questionnaire forms. This can be seen on almost every form implemented on va.gov. This wording needs to be customizable so it can list the actual name of the feature.
![Respondent Burden.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/b2d0c6b7-df4f-4648-bf65-ddcf68cdfe1a)
2. Health questionnaires will not have a respondent burden or OMB control number. Therefore, the entire respondent burden section of the privacy act statement does not apply. The health questionnaires team discussed keeping our own version of the privacy act statement minus the respondent burden in our code. However, we wouldn’t know when and if any updates occur to the privacy act notice section. Therefore, we wanted to know if the respondent burden paragraph could be made optional at the platform level? 
![Education benefits.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/3e2ff705-1a6b-42bc-9a12-ab29c6a4fd0c)

**Comment by kristenmcconnell** [comment]
Title: Documentation Request: What error messages are automatically implemented as part of the forms library?

# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [X] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Error messages (particularly all error messages that are automatically implemented as part of the forms library).

## What is the nature of this update?

Health questionnaires utilize the forms library. However, they are not an application. Therefore, most of the default error messages that come as part of the forms library had to be changed. Most often the word application had to be replaced with questionnaire.  The UX designer and front-end engineer on the team organically identified most of the error messages, in order to make appropriate changes. However, we weren’t sure if we missed any error states. Therefore, we created a [ticket to do an audit](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17314) through the code to find error message states that we missed. A handful of missed error messages were identified at the end of the ticket. If more documentation existed on which error messages were part of the forms library, then it could help other teams to not have to do an audit as well.

**Comment by kristenmcconnell** [comment]
Title: Feature request: Dynamic title, expiration date, and URL (unique identifier)

# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: It relates to the forms library.

## Do you have a suggestion for a new component or utility?
The health questionnaires feature is not just one single form that a Veteran will fill out once. What questionnaire is displayed to the Veteran relies on a combination of appointment type (stop code), appointment date, and the associated clinic/facility where the appointment will take place. A Veteran can even have multiple instances of the same form to complete depending upon their appointments. 

As a result, we needed the forms library to be much more dynamic to accommodate our use case. We are proposing that the following changes be added to the platform, so other teams can utilize them if needed:   1. Dynamic expiration date: the default form system has a 60 sliding expiration date for a form's data. For our use cases, 60 days is not correct. A questionnaire expires on the day of the appointment. This is about passing the expiration date to the SIP system.
2. Using the URL parameter, give each form a unique id in the format of {form-id}-{appointment-id}. This will be of the SIP feature, so the user can have multiple instances of the form filled in progress at once.
3. The title of the form, should be dynamic and reflect the stop code (primary care, etc) that is in the appointment data.

**Comment by kristenmcconnell** [comment]
Title: Feature request: Confirmation page standardization

# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: The confirmation page that is part of the forms library.

## Do you have a suggestion for a new component or utility?
The confirmation page has evolved over time. Some items that have changes include: 
1. The introduction of the “print this page” feature has changed the importance of the information shown within the blue box. 
2. A lot of recent teams have also implemented a green success alert at the top of the page, but this alert isn’t part of current documentation.
    1. The implementation of the green alert has resulted in changes to the semantic heading structure.  All of these evolutions have caused confirmation pages to diverge more and more. As a result, can a wholistic review of confirmation pages be completed and new recommendations be proposed?


## Additional context
The following Slack channel lists some confirmation page designs:  https://dsva.slack.com/archives/C0NGDDXME/p1579042705077800  Here is an example for the caregiver team: 
![Confirmation-print .png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/6bc79403-3026-49df-8abe-1c434dfec2a0)

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mdewey Each comment in this ticket is a draft of possible VSP ticket that we can submit. Please review all of them and make edits (particularly the dynamic title/URL one...I know I'm missing stuff).

**Comment by kristenmcconnell** [comment]
Tickets that were submitted to platform:

1. Tabs: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/379
2. Width suggestions on cards: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/380
3. Privacy Act Statement variation and customization: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/381
4. Error message documentation: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/382
5. Dynamic title, expiration date, form id, and URL: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/383
6: Confirmation page documentation: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/384

**Comment by abuckley3385** [comment]
@kristenmcconnell  I created a markup page for us to track all enhancements for our product
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/enhancement-list.md

**Comment by caw310** [comment]
> Tickets that were submitted to platform:
> 
> 1. Tabs: [department-of-veterans-affairs/vets-design-system-documentation#379](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/379)
> 2. Width suggestions on cards: [department-of-veterans-affairs/vets-design-system-documentation#380](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/380)
> 3. Privacy Act Statement variation and customization: [department-of-veterans-affairs/vets-design-system-documentation#381](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/381)
> 4. Error message documentation: [department-of-veterans-affairs/vets-design-system-documentation#382](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/382)
> 5. Dynamic title, expiration date, form id, and URL: [department-of-veterans-affairs/vets-design-system-documentation#383](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/383)
> 6. Confirmation page documentation: [department-of-veterans-affairs/vets-design-system-documentation#384](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/384)
> 
> @caw310 - FYI

Thanks! I added the vsp-design-system-team label to the tickets and assigned them to be for the time being.

**Comment by kristenmcconnell** [comment]
@sshein For reference too.
