### ISSUE TITLE
Setup Test User Accounts Database Schema

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17208]
## Issue Description
A database schema needs to be created in order for the database to hold Test User Accounts. This schema will primarily consist of a table to hold basic account information and will largely mirror existing .csv representations of existing test accounts.

Current Test User Accounts DB Schema plan:

1. table `test_user_dashboard_tud_accounts` to be added to existing vets-api DB schema, no standalone database needed
2. `test_user_dashboard_tud_accounts` fields:
- `account_uuid` (uuid used to lookup account in MPI)
- `first_name`, `middle_name`, `last_name`
- `gender`
- `birth_date`
- `ssn` (social security number)
- `phone`
- `email` (used to login with)
- `password` (all existing test accounts are using the same password, this shouldn't be sensitive information)
- `id_type`
- `authentication_type`
- `account_type` (basic/advanced/premium)
- `loa_level` (integer, account LoA)
- `standard` (bool, designation of standard/custom test user)
- `available` (bool, account checked in or out)
- `checkout_time` (datetime, time when account was checked out/null)
---
## Tasks
- [x] Research is completed to determine which fields Test User Accounts will need to have
- [x] A schema is created with the fields determined.

## Acceptance Criteria
- [ ] A database schema exists that can hold Test User Accounts.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
Migration commit: https://github.com/department-of-veterans-affairs/vets-api/pull/5771
