### ISSUE TITLE
[Spike] Lighthouse authentication capability

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#17203]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the vets-api to authenticate against MAP for appointments and against Lighthouse for PGD data

## Description
Provide the ability for the Health Quest module to authenticate against MAP for appointment data and against Lighthouse for storing and retrieving FHIR resources.

## Tasks
- [ ] Refactor authentication and session management code to accommodate the two different authentication mechanisms as well as the API token management systems.

## Acceptance Criteria
- [ ] Health Quest module must be able to authenticate independently against MAP and retrieve appointment data.
- [ ] Health Quest module must be able to authenticate independently against Lighthouse in order to create and retrieve FHIR resources.

**Comment by dillo** [comment]
System to a system-auth document: https://dsva.slack.com/files/U01A62SN05P/F01HCLXLNR2/system-authorization.pdf
