### ISSUE TITLE
Test User Account Dashboard Backend CRUD Functions

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17217]
## Issue Description
The TUD application will include CRUD functionality for custom users and the standard user population script will include CRUD functionality for standard users. Both will require API endpoints on the TUD backend to carry out CRUD commands.
---
## Tasks
- [ ] CRUD API endpoints exist that can parse fields/values and translate them into creating, reading, updating, and deleting Test User Accounts in the TUD DB.
- [ ] A CRUD API request will trigger an API call to update the same test user in the staging/va.gov DB
- [ ] A CRUD API request will trigger API calls to update the same test user in the external services (DSLogon, etc.) where that user has or will have external information
- [ ] CRUD API requests from the frontend app will only be able to affect custom users, attempted CRUD API requests on standard users from the frontend app will result in an exception
- [ ] CRUD API requests from the population script will be able to affect standard users

## Acceptance Criteria
- [ ] Users using the TUD frontend will be able to create, read, update, and delete custom test user accounts
- [ ] Standard test user accounts can be created, updated, and deleted via the DB population script
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
After conducting research and interfacing with external service providers we have determined that programmatic test account CRUD operations is not possible at this time and will not be included in the MVP.
