### ISSUE TITLE
Test User Accounts Dashboard Database Population Script

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17214]
## Issue Description
Currently test user account records are managed through Markdown lists ([example](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Administrative/vagov-users)), we would like to maintain a semi-static list of "standard" test user accounts that will be managed in a similar list. This list can be imported into the TUD database through a script. The script can be run initially to populate the DB with the standard test users or updated through Github version control and re-run to update existing standard users.

---
## Tasks
- [ ] Consolidate different existing Markdown lists of standard users into a single .csv with all "standard" users, to be hosted inside test_user_dashboard module (within vets-api repository)
- [ ] Create rakefile and corresponding TUD module service to write list of standard users into `test_user_account_tud_account` table

## Acceptance Criteria
- [ ] A list of standard users can be written into the TUD database from a .csv file.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5777
