### ISSUE TITLE
Add DB Querying Endpoints to Test User Accounts Dashboard Backend

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17211]
## Issue Description
The TUD frontend will have filters to view test user accounts based on different account fields and properties (LoA, Education benefits, etc.). The TUD backend needs to have API endpoints for the frontend to hit that query the TUD database and return filtered lists of accounts.

---
## Tasks
- [x] create route `GET /test-user-dashboard/tud-accounts` (index view)
- [x] route returns following JSON:
```
{
"data": [
{
"id": "1",
"type": "test_user_dashboard_tud_accounts",
"attributes": {
"account_uuid": 1234567890,
"first_name": "First",
"middle_name": "M",
"last_name": "Last",
"gender": "M",
"birth_date": "1950-01-01T08:00:00.000Z",
"ssn": 1234567,
"phone": "800-800-8000",
"email": "vets.gov.user+0@gmail.com",
"password": "testpass",
"available": null,
"checkout_time": null
"id_type: "idme"
"loa": 3,
"account_type": "premium",
"services": "service data string here",
}
]
}
```
- [x] JSON data is returned in [JSON API format](https://jsonapi.org/examples/)

## Acceptance Criteria
- [x] A TUD frontend request returns a list of all tud_accounts
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5804
