### ISSUE TITLE
FSR - Vehicle make and model data 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#17216]
## Issue Description
_In order to make adding vehicles faster, we want to populate vehicle makes and models so as Veterans type it'll filter down similarly to our other list loops. The idea is that once a vehicle make is selected, we'll show the models corresponding with that make. There's many makes and models, but we should be able to find a JSON file online to use. [This component's design can be viewed here.](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410290/comment/sitemap?mode=i)_

---
## Tasks
- [ ] _Search for a JSON file that includes all vehicle make and model data_
- [ ] _Incorporate the vehicle data in the vehicle list loop component_
- [ ] _Provide vehicle model filtering for the corresponding vehicle makes_

## Acceptance Criteria
- [ ] _A JSON file with vehicle make and model data is discovered_
- [ ] _Vehicle make and model data is incorporated into the list loop component_
- [ ] _Vehicle models filter as makes are selected_

**Comment by LinnJS** [comment]
This is a nice to have feature not high priority but possibly heavy lift.
