### ISSUE TITLE
QA Dashboard: Functional Testing, E2E Testing, Accessibility Testing

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#17228]
## Problem Statement 
VFS Teams, VSP Staff and OCTO-DE leadership don’t have a way to easily understand the state of quality on individual products, or across the platform.

How might we develop a solution that allows stakeholders to see the QA metrics from the product or products that are relevant to them according to their role?

## Hypothesis or Bet
By providing a dashboard that enables stakeholders to view metrics for how products are doing in following QA processes and ensuring quality on their products, stakeholders will have better insight into the state of quality on the platform and will be able to make better decisions to address any gaps on products or the platform.
* NOTE: This will be an extended effort that likely goes into Q1 of 2022, each quarter this effort will focus on incorporating any new test methodologies or tools.

## We will know we're done when... ("Definition of Done")
- [x] We have identified metrics in the existing test methodologies/tools (This should include available metrics, which of those metrics would be helpful for teams and any key metrics that could be included in an overall product scorecard)
   - [x] Functional Testing
   - [x] E2E Testing
   - [x] Accessibility Testing
- [x] *We understand what it takes to obtain those metrics and they are identified as feasible, or the plan has been updated accordingly to reflect any limitations*
- [x] *We have an MVP of the dashboard ready for launch*
- [ ] *We have any necessary documentation completed and available for use*

## Known Blockers/Dependencies 
* Some data that would be required in the Accessibility area of the dashboard is dependent on the Analytics team related to their work with DOMO/BigQuery
* E2E Test Results may be limited depending on what data we can get from Cypress Dashboard

## Projected Launch Date
*Q2 2021*

**Comment by holdenhinkle** [comment]
Document with notes - https://docs.google.com/document/d/1jc4FGRMNFIlNuWlkB4p5MFhKdOQRHE4vutOyot48kHw/edit?usp=sharing

**Comment by holdenhinkle** [comment]
Metrics Spreadsheet - https://docs.google.com/spreadsheets/d/1UWbOr9avjfJJPGaG4OHJY5MNd-zGkMvESce7dWPmIl8/edit#gid=0

**Comment by holdenhinkle** [comment]
PR (draft) for creating Mochawesome Reports for Cypress tests - https://github.com/department-of-veterans-affairs/vets-website/pull/16655

Mochawesome creates detailed `json` files for each test:

**Comment by holdenhinkle** [comment]
# Cypress Test Report
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16655
Run command: `node cypress_runner`

Using the following Mochawesome packages:

- https://github.com/adamgruber/mochawesome
- https://github.com/Antontelesh/mochawesome-merge

We can grab the `json` that Mochawesome generates to create reports like this - https://nottyo.github.io/cypress-e2e-code-coverage/cypress/report/mochawesome-report/mochawesome.html

Mochawesome generates a json file like the following for each spec file:
File: `cypress/report/mochawesome-report/mochawesome_04062021_104000.json`

```js
"{
  ""stats"": {
    ""suites"": 1,
    ""tests"": 4,
    ""passes"": 4,
    ""pending"": 0,
    ""failures"": 0,
    ""start"": ""2021-04-06T14:39:56.174Z"",
    ""end"": ""2021-04-06T14:40:00.989Z"",
    ""duration"": 4815,
    ""testsRegistered"": 4,
    ""passPercent"": 100,
    ""pendingPercent"": 0,
    ""other"": 0,
    ""hasOther"": false,
    ""skipped"": 0,
    ""hasSkipped"": false
  },
  ""results"": [
    {
      ""uuid"": ""703365e3-d8d8-4aad-88f7-564ded444c37"",
      ""title"": """",
      ""fullFile"": ""src/applications/disability-benefits/all-claims/tests/all-claims-wizard.cypress.spec.js"",
      ""file"": ""src/applications/disability-benefits/all-claims/tests/all-claims-wizard.cypress.spec.js"",
      ""beforeHooks"": [],
      ""afterHooks"": [],
      ""tests"": [],
      ""suites"": [
        {
          ""uuid"": ""b9995547-4d0a-4168-b79c-778ba49b2560"",
          ""title"": ""526 wizard"",
          ""fullFile"": """",
          ""file"": """",
          ""beforeHooks"": [],
          ""afterHooks"": [],
          ""tests"": [
            {
              ""title"": ""should show the form wizard"",
              ""fullTitle"": ""526 wizard should show the form wizard"",
              ""timedOut"": null,
              ""duration"": 1408,
              ""state"": ""passed"",
              ""speed"": ""slow"",
              ""pass"": true,
              ""fail"": false,
              ""pending"": false,
              ""context"": null,
              ""code"": ""cy.url().should('include', _constants__WEBPACK_IMPORTED_MODULE_2__[\""DISABILITY_526_V2_ROOT_URL\""]);\ncy.get('h1').should('have.text', 'File for disability compensation');\ncy.axeCheck();"",
              ""err"": {},
              ""uuid"": ""2bccc1b5-3b74-4d7f-b198-4be82778c083"",
              ""parentUUID"": ""b9995547-4d0a-4168-b79c-778ba49b2560"",
              ""isHook"": false,
              ""skipped"": false
            },
            {
              ""title"": ""should show disagreeing with a decision questions & alert"",
              ""fullTitle"": ""526 wizard should show disagreeing with a decision questions & alert"",
              ""timedOut"": null,
              ""duration"": 1122,
              ""state"": ""passed"",
              ""speed"": ""slow"",
              ""pass"": true,
              ""fail"": false,
              ""pending"": false,
              ""context"": null,
              ""code"": ""cy.get('[type=\""radio\""][value=\""appeals\""]').check(checkOpt);\ncy.checkFormChange({\n  label: 'Are you on active duty right now?',\n  value: 'no-appeals'\n});\ncy.get('[type=\""radio\""][value=\""disagree-file-claim\""]').check(checkOpt);\ncy.checkFormChange({\n  label: 'Are you filing a new claim or are you disagreeing with a VA decision on an earlier claim?',\n  value: 'disagreeing'\n});\ncy.checkFormAlert('disagree with VA decision, needs a decision review');\ncy.axeCheck();"",
              ""err"": {},
              ""uuid"": ""40491446-1fd7-492d-90ce-9f577c820d8c"",
              ""parentUUID"": ""b9995547-4d0a-4168-b79c-778ba49b2560"",
              ""isHook"": false,
              ""skipped"": false
            },
            {
              ""title"": ""should show BDD questions & start button"",
              ""fullTitle"": ""526 wizard should show BDD questions & start button"",
              ""timedOut"": null,
              ""duration"": 1292,
              ""state"": ""passed"",
              ""speed"": ""slow"",
              ""pass"": true,
              ""fail"": false,
              ""pending"": false,
              ""context"": null,
              ""code"": ""cy.get('[type=\""radio\""][value=\""bdd\""]').check(checkOpt);\ncy.checkFormChange({\n  label: 'Are you on active duty right now?',\n  value: 'yes-bdd'\n});\ncy.get('.form-datefield-month').should('exist');\ncy.findByLabelText(/month/i).select(mockMonth120);\ncy.findByLabelText(/day/i).select(mockDay120);\ncy.findByLabelText(/year/i).clear().type(mockYear120);\ncy.checkStorage(_constants__WEBPACK_IMPORTED_MODULE_2__[\""FORM_STATUS_BDD\""], 'true');\ncy.checkStorage(_constants__WEBPACK_IMPORTED_MODULE_2__[\""SAVED_SEPARATION_DATE\""], mockDate);\ncy.checkFormChange({\n  type: 'usa-date-of-birth',\n  label: 'What’s the date or anticipated date of your release from active duty?',\n  value: mockDate\n});\ncy.checkCallToAction();\ncy.axeCheck();"",
              ""err"": {},
              ""uuid"": ""808ae2ea-df40-48ff-ab59-efa50c0f414c"",
              ""parentUUID"": ""b9995547-4d0a-4168-b79c-778ba49b2560"",
              ""isHook"": false,
              ""skipped"": false
            },
            {
              ""title"": ""should start all-claims/original claims flow"",
              ""fullTitle"": ""526 wizard should start all-claims/original claims flow"",
              ""timedOut"": null,
              ""duration"": 970,
              ""state"": ""passed"",
              ""speed"": ""slow"",
              ""pass"": true,
              ""fail"": false,
              ""pending"": false,
              ""context"": null,
              ""code"": ""var h1Text = 'File for disability compensation'; // starts with focus on breadcrumb\ncy.focused().should('have.class', 'va-nav-breadcrumbs-list');\ncy.get('h1').should('have.text', h1Text);\ncy.get('[type=\""radio\""][value=\""appeals\""]').check(checkOpt);\ncy.checkFormChange({\n  label: 'Are you on active duty right now?',\n  value: 'no-appeals'\n});\ncy.get('[type=\""radio\""][value=\""file-claim\""]').check(checkOpt);\ncy.checkStorage(_constants__WEBPACK_IMPORTED_MODULE_2__[\""FORM_STATUS_BDD\""], undefined);\ncy.checkStorage(_constants__WEBPACK_IMPORTED_MODULE_2__[\""SAVED_SEPARATION_DATE\""], undefined); // learn more link\ncy.get('a[href*=\""disability/how-to-file-claim/\""]').should('exist');\ncy.checkFormChange({\n  label: 'Are you filing a new claim or are you disagreeing with a VA decision on an earlier claim?',\n  value: 'new-worse'\n});\ncy.axeCheck(); // start form\nvar h1Addition = ' with VA Form 21-526EZ';\ncy.findAllByText(/disability claim online/i, {\n  selector: 'a'\n}).first().click(); // title changes & gets focus\ncy.get('h1').should('have.text', h1Text + h1Addition);\ncy.focused().should('have.text', h1Text + h1Addition);\ncy.checkStorage(_constants__WEBPACK_IMPORTED_MODULE_2__[\""WIZARD_STATUS\""], 'complete');\ncy.axeCheck();"",
              ""err"": {},
              ""uuid"": ""c1d385cb-be8e-40d9-8efb-b2b099c68468"",
              ""parentUUID"": ""b9995547-4d0a-4168-b79c-778ba49b2560"",
              ""isHook"": false,
              ""skipped"": false
            }
          ],
          ""suites"": [],
          ""passes"": [
            ""2bccc1b5-3b74-4d7f-b198-4be82778c083"",
            ""40491446-1fd7-492d-90ce-9f577c820d8c"",
            ""808ae2ea-df40-48ff-ab59-efa50c0f414c"",
            ""c1d385cb-be8e-40d9-8efb-b2b099c68468""
          ],
          ""failures"": [],
          ""pending"": [],
          ""skipped"": [],
          ""duration"": 4792,
          ""root"": false,
          ""rootEmpty"": false,
          ""_timeout"": 2000
        }
      ],
      ""passes"": [],
      ""failures"": [],
      ""pending"": [],
      ""skipped"": [],
      ""duration"": 0,
      ""root"": true,
      ""rootEmpty"": true,
      ""_timeout"": 2000
    }
  ],
  ""meta"": {
    ""mocha"": {
      ""version"": ""7.0.1""
    },
    ""mochawesome"": {
      ""options"": {
        ""quiet"": false,
        ""reportFilename"": ""mochawesome"",
        ""saveHtml"": false,
        ""saveJson"": true,
        ""consoleReporter"": ""spec"",
        ""useInlineDiffs"": false,
        ""code"": true
      },
      ""version"": ""6.2.2""
    },
    ""marge"": {
      ""options"": {
        ""reportDir"": ""cypress/report/mochawesome-report"",
        ""overwrite"": false,
        ""html"": false,
        ""json"": true,
        ""timestamp"": ""mmddyyyy_HHMMss""
      },
      ""version"": ""5.2.0""
    }
  }
}"
```

After all tests are executed, it merges the test results (example coming soon).

**Comment by holdenhinkle** [comment]
# Mocha Coverage Report

Run the command `yarn test:unit --coverage`

Takes ~5 mins to run locally

Creates a report in `coverage/lcov-report/`

Creates a summary file - `coverage/coverage-summary.json`

**Comment by holdenhinkle** [comment]
# Mocha Unit Test Results

Run `mochawesome` to generated a Mochawesome report for unit tests.

A results page is created at `mochawesome-report/mochawesome.html`.
A results `json` file is saved at `mochawesome-report/mochawesome.json`.

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/863e32d9-5435-451b-be48-bb1cdb137013)

**Comment by holdenhinkle** [comment]
## RSpec Code Coverage
To generate a `JSON` file with RSpec code coverage results we need to install the [simplecov-json](https://github.com/vicentllongo/simplecov-json) gem.

PR - https://github.com/department-of-veterans-affairs/vets-api/pull/6495

Generated `JSON` can be found in `coverage/coverage.json`

The format you can expect is:
```json
{
    "timestamp": 1348489587,
    "command_name": "RSpec",
    "files": [
        {
            "filename": "/home/user/rails/environment.rb",
            "covered_percent": 50.0,
            "coverage": [
                null,
                1,
                null,
                null,
                1
            ],
            "covered_strength": 0.50,
            "covered_lines": 2,
            "lines_of_code": 4
        },
        ...
    ],
    "metrics": {
          "covered_percent": 81.70731707317073,
          "covered_strength": 0.8170731707317073,
          "covered_lines": 67,
          "total_lines": 82
    }
}
```

Picture of SimpleCov `HTML` Report
![image](https://user-images.githubusercontent.com/9326247/113904711-5ade1f00-97a0-11eb-862d-78190f71d9b2.png)

**Comment by holdenhinkle** [comment]
## RSpec Test Results

`RSpec` test results can be saved as `JSON`.

Docs:
- https://rubydoc.info/github/rspec/rspec-core/RSpec%2FCore%2FConfiguration:add_formatter
- https://relishapp.com/rspec/rspec-core/v/3-10/docs/formatters/json-formatter

PR (draft) - https://github.com/department-of-veterans-affairs/vets-api/pull/6497

Example `JSON`:
```json
{"version":"3.10.0","messages":["Run options: include {:focus=>true}","\nAll examples were filtered out; ignoring {:focus=>true}"],"seed":22471,"examples":[{"id":"./spec/jobs/cypress_viewport_updater/existing_github_file_spec.rb[3:1:8:1]","description":"returns the correct value when it is updated","full_description":"CypressViewportUpdater::ViewportPresetJsFile behaves like an existing file #updated_content= returns the correct value when it is updated","status":"passed","file_path":"./spec/jobs/cypress_viewport_updater/existing_github_file_spec.rb","line_number":67,"run_time":0.1044383,"pending_message":null}],"summary":{"duration":7.6773135,"example_count":84,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":0},"summary_line":"84 examples, 0 failures"}
```

**Comment by holdenhinkle** [comment]
The following test results don't have a pretty HTML report but are available as `json` or `csv`:
- RSpec Test Results--available as `json`
- Load Tests (Locust)--available as `csv`

**Comment by holdenhinkle** [comment]
Waiting on access to DOMO.
