### ISSUE TITLE
Design staging review + feedback for usability

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#17222]
## Issue Description

For upcoming usability, we're testing in staging, unauthenticated (https://staging.va.gov/financial-status-report/), we need to compile feedback to provide FE to complete before the testing can happen.

---
## Tasks
- [x] Review FE progress in staging and create a functional feedback document, prioritized for usability testing
- [x] Create FE ticket for feedback

## Acceptance Criteria
- [x] Document outlining staging feedback and priorities created
- [x] FE ticket created and linked below

**Comment by rebeccawalsh** [comment]
Usability staging feedback provided here: https://docs.google.com/document/d/1K8I1mYmCgJdHUxt62drlOqqKw1s6Mb80AaigbsN7k0A/edit#heading=h.tkjjkxog3eo6
