### ISSUE TITLE
FE: Implement search experience for COVID-19 vaccines (Facility Locator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17226]
## Issue Description
"COVID-19 vaccines" will be added as a system and facility health service to Drupal and will be a searchable service on Facility Locator. 

## Dependencies
- [ ] "COVID-19 Vaccines" health service is available via Facilities API
- [x] [Design](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17260) 

---
## Tasks
- [ ] Add service type to drop down
- [ ] Add service type to query when `COVID-19 vaccines` is selected as service type
- [ ] Add alert to results
- [ ] Implement design spec
- [ ] Implement data layer to track the number of clicks on the "Covid-19 vaccines at the VA" alert
- [ ] This change needs to be on Flipper

## Acceptance Criteria
- [ ] A Veteran can select `COVID-19 vaccines` as service type when the facility type = `VA health`
- [ ] When a Veteran selects `COVID-19 vaccines` as a service type, the search results contain only facilities with COVID-19 vaccines as a service 
- [ ] When a Veteran selects `COVID-19 vaccines` as a service type, cards are consistent with current experience except 
      - Add the alert "COVID-19 vaccines at the VA"
      - Remove mental health phone number
- [ ] Blue "COVID-19 vaccines at the VA" button links to https://www.va.gov/health-care/covid-19-vaccine/
- [ ] Blue "COVID-19 vaccines at the VA" button appears **above** the phone number'
- [ ] When available, the facility operating status appears **below** the phone number
- [ ] Implementation is consistent with design
- [ ] Alert shows only if `COVID-19 vaccines` has been selected as Service type
- [ ] When Service type = `All VA health services`, the alert does not display

**Out of scope: COVID-19 vaccines display on detail page** 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
