### ISSUE TITLE
Discovery: Research Plan

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1722]
## User Impact
Looking ahead to what is entailed for design is helpful to better achieve our goals.

### Tasks
- Initialize a research plan

### Definition of Done
- [x] Complete research plan for initial eBenefits discovery.
- [x] Start a Conversation Guide
- [x] Determine Team availability

### Notes
- What did we learn about those exceptions?
- [ ] Any notes for the Call Center should be uploaded to `feature/$feature-name/call-center` in GitHub

**Comment by jason-gcio** [comment]
Great work, this is going to be super helpful.
