### ISSUE TITLE
Test User Accounts Dashboard Mark Account Checked Out

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17221]
## Issue Description

---
## Tasks
- [x] When the test user account is logged into on vets-api it will call a TUD API endpoint that will mark the test user account as having been checked out so that it cannot be checked out by another user until it is checked back in

## Acceptance Criteria
- [x] When a test user account has been logged into it will be marked as checked out in the test_user_dashboard_tud_accounts table

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
