### ISSUE TITLE
Test User Accounts Dashboard Checkin Account

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17223]
## Issue Description
When a user checks out a test user account for use on a staging.va.gov, they can check the user back in for use by others by logging out of staging.va.gov or when their session expires.
---
## Tasks
- [x] The vets-api endpoints for logging a user out and session expiration are updated to make an API call to the TUD backend
- [x] A TUD API endpoint is created that updates the TUD DB to mark the user as checked back in

## Acceptance Criteria
- [x] When a user using a test user account on staging.va.gov logs out their test account will be marked as checked in on the TUD frontend
- [x] When a user using a test user account on staging.va.gov has their session expire their test account will be marked as checked in on the TUD frontend

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
