### ISSUE TITLE
Add CODEOWNERS to the Test User Dashboard repo

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17224]
## Issue Description
Adds a CODEOWNERS document to outline that the `vsp-test-user-dashboard` repo that the Identity team will own.  This will allow better visibility for the Identity team with code ownership, issues, and requests

---
## Tasks
- [x] Adds a `CODEOWNERS` document to the `vsp-test-user-dashboard` repo

## Acceptance Criteria
- [x] I can see a `CODEOWNERS` file in the repo
- [x] Creating a new issue with appropriate tags will send notifications (emails) to appropriate user
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
