### ISSUE TITLE
FSR - Error messages

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#17230]
## Issue Description
_The FSR's required input fields need error validation so users can correct errors they may experience in the form._

@troyriser reviewed the error messages and has the following feedback: 

[The error messages ca be found in this Excel spreadsheet](https://app.zenhub.com/files/133843125/a92bac4f-139e-4f0b-befb-0aab47dd3767/download)

**Revision Summary:**

- [ ] "Please enter a numerical value." has been changed in 21 instances throughout to "Please enter only numerical values." where the user enters special characters or letters. The language is now more concise in accordance with Plain Language dictates.

- [ ] Line 101: Re "Do you currently own other assets?" query, "Please enter your assets information." has been changed to "Please enter your other assets information." for internal consistency.

- [ ] Re C5P1 on lines 131-137, questions beginning with "What type of help do you want for your Post-9/11 GI Bill debt for tuition and fees?" and ending with "How much can you afford to resolve this debt?", messages have been revised by replacing the verb 'provide' with 'enter' for internal consistency.

- [ ] Line 133: Re query "How much can you afford to pay monthly on this debt?", the error message has been revised from "Please provide a response." to "Please enter the amount you can pay monthly."

- [ ] Line 135: Re query "How much can you afford to resolve this debt?", the error message has been revised from "Please provide a response." to "Please enter the amount you can afford to resolve this debt."

- [ ] Line 136: Re query "How much can you afford to resolve this debt?", the error message has been revised from "Please provide a numerical value." to "Please enter only numerical values."

Reach out to @rileyorr or @troyriser with any questions!

---
## Tasks
- [ ] _Incorporate the outlined error messages into the corresponding input fields_

## Acceptance Criteria
- [ ] _All error messages have been incorporated into the FSR_

**Comment by rileyorr** [comment]
@bradl3yC & @craigwheeler I removed this ticket's blocker! Susan and I finalized the content for every error message except one that requires the DMC's assistance - I marked that error message in the doc. Also, I'm not 100% certain that a couple of the error messages are possible given the form system's schema, so I tagged Brad on those ones to double-check. 

I broke up the document by page and included a link to the corresponding UXPin. LMK if either of you have questions!

**Comment by LinnJS** [comment]
This ticket looks ready to go just need to break this ticket into a couple of smaller tickets to reduce conflicts.

**Comment by rebeccawalsh** [comment]
@LindaLi123 @LinnJS  this ticket had a [content/design ticket blocking it](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23299), but that tag was removed. 

These error messages were meant to be reviewed by @troyriser for plain language "compliance" prior to engineering with [this ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23299).

IDK where we are on the engineering work for this, but we can either allow it to be completed without content review, then make updates to the content once reviewed (if needed)... or we can pause engineer work and allow Troy some time to review the messaging for any errors.

**Comment by LinnJS** [comment]
@rebeccawalsh 100% got the tickets mixed up, switched it back around thanks for straightening that out!

**Comment by rileyorr** [comment]
@craigwheeler & @LinnJS the error messages have been reviewed by @troyriser! I updated the original ticket with his feedback. Please reach out to me or Troy with any questions. 

Removing the blocked tag as well

**Comment by craigwheeler** [comment]
Noticed the content provided uses the same message for number inputs and currency values. If an incorrect dollar amount is entered like 1.2333333 it's technically a numerical value but will fail validation for an incorrect currency amount which will display "Please enter only numerical values". Other places in VA.gov use "Please enter a valid dollar amount" for currency inputs and will update error messaging to use this instead.

**Comment by rebeccawalsh** [comment]
@craigwheeler Sounds good -- "Please enter a valid dollar amount" for currency errors.
