### ISSUE TITLE
Access Requests - Improve workflow to make sure requests are handled efficiently 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17235]
## Issue Description
Currently, there is a basic workflow for access requests, but it is easy for those tickets to get lost in the shuffle, or for the operations team to be waiting on approval from authorized personnel. We want to ensure that access requests are handled in a timely fashion. We need to review how this workflow can be improved and determine a good path forward.

As an operations support engineer, I want to ensure access that requests are handled in a timely fashion. 

How might we improve the access request workflow so that it access gets approved before Ops is given the ticket?

A high-level overview of existing workflow: 
1. fill out access request using a template (which automatically adds the label and drops ticket in #vsp-operations) 
2. ping @department-of-veterans-affairs/vsp-operations in the ticket (which sends a message to members of that GitHub group) 
3. ticket gets put into the backlog.

As a result, we hope that access requests will be handled in a more timely fashion. 

---
## Tasks
- [x] Review and discuss existing access request workflow
- [x] Come up with suggestions for improvements to the access request workflow
- [x] Implement changes to the workflow that will support more timely resolution of access requests
- [x] Document the new workflow
  - [x] Update Ops' internal onboarding instructions w/ the new info regarding how to reach out to VA product owners etc
  - [x] The 3 docs should cross-reference one another somehow  

## Acceptance Criteria
- [x] There will be a new, documented workflow agreed to for handling access requests

**Comment by jhouse-solvd** [comment]
thinking we should add "Awaiting Feedback" label when we've processed the ticket, but need the user to let us know that all is well.
That will help us filter out the ones that have been processed, and which ones haven't been picked up yet.

**Comment by jhouse-solvd** [comment]
Please see this slack thread which outlines the new communication process which includes Dror reaching out to the COR instead of Ops: 

https://dsva.slack.com/archives/CTYQL39FE/p1623080910492400

**Comment by jhouse-solvd** [comment]
The new workflow will be as follows: 

1. Person needing access fills out the access request template 
2. The template should tag the GitHub group that includes VA product owners (Mike Chelen, Dror Matalon, Mike Pritchard et al) (let's leave the operations label for now?)
3. one of the VA product owners will contact the COR for the person needing access 
4. once approved by the COR, the va product owner will pass the ticket to ops to enable the required access 

Just need to document the above and then this can be completed

**Comment by jhouse-solvd** [comment]
1. For platform crew members who are processing the request, we will probably want to make sure that they are linked to and familiar with this: [Granting AWS or SOCKS](https://vfs.atlassian.net/l/c/31znP5ww)
2. Demian pointed out that the "access-request" label for issues is used by more than one team. Ops would like to subscribe to a label for these requests to receive them in the #vsp-operations slack channel. That means that the label should be updated, along with the template.

**Comment by jhouse-solvd** [comment]
Okay, have been checking the different pieces of documentation involved in this process, and perhaps it's easiest to group by audience: 

_for ops personnel processing access requests:_ 
[Internal onboarding instructions
](https://github.com/department-of-veterans-affairs/devops/blob/f9f0391b0c81af746a2548dccd477c440724ec48/docs/operations/Internal_Onboarding_Instructions.md) 

_for leadership personnel approving access requests / verifying that access is justified:_ 
[Granting AWS access](https://vfs.atlassian.net/wiki/spaces/VI/pages/1543143557/Granting+AWS+access)

_for developers and other personnel requesting access:_ 
Request access to tools 
[internal version for editing:](https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools)
[published, developer-facing version:](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)

**Comment by jhouse-solvd** [comment]
See [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools) for new, documented workflow.



Closing.
