### ISSUE TITLE
Documentation - move Grafana upgrade doc to Confluence 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17236]
## Issue Description
_Grafana was recently upgraded, and it would be great to have an up-to-date document that outlines the steps and requirements, so that w can increase knowledge across the team when we need to do this again in the future._

---
## Tasks
- [ ] _Create document in Confluence for Grafana upgrade steps_

## Acceptance Criteria
- [ ] _Document will be shared with the Operations team_
- [ ] _Document will be easy to find in the future_
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
@omgitsbillryan - @pnwstevan mentioned that there is an existing doc / notes that could be updated with notes from your recent experience in upgrading Grafana. this could also be linked to the document that we will be creating as a result of [this ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17180).

**Comment by jhouse-solvd** [comment]
@omgitsbillryan - this is an oldy, but potentially a goody. Do you know if we have any steps/docs we could just post in confluence re: upgrading Grafana to close this one out? If it's been too long and you don't have anything handy, then we'll just consider this as stale and re-visit when the need arises.

**Comment by jbritt1** [comment]
I think it this would be completely different now than how things were at the time of inception on this ticket. Any old docs would not capture how this is done today as it would likely be geared towards the BRD versions of our pipelines rather than the GHA+Argo+EKS we use now.

**Comment by mchelen-gov** [comment]
Ok renaming this to "Document Grafana upgrade process"
