### ISSUE TITLE
Creates Epics and Tickets for Test User Dashboard MVP

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17239]
## Issue Description
The Test User Dashboard needs Epics and tickets created to better inform the progress of setting up scope of work for the TUD application.

---
## Tasks
- [x] John Bramley & Alexander Garcia will work together to create Epics and tickets as part of the Test User Dashboard VSP Initiative
- [x] Adds technical details to the Test User Dashboard tickets as more information is provided through UX research

## Acceptance Criteria
- [x] Test User Dashboard Epics are created for Identity, Operations, and Testing team
- [x] Test User Dashboard tickets are created for both Front-end and Back-end work
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
