### ISSUE TITLE
Collaboration Cycle - Update guidance/documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#17238]
## Problem Statement 
VFS teams have struggled with the documentation and guidance for the Collaboration Cycle as it is difficult to understand, challenging to locate, and not consistent across practice areas. VFS teams are unclear on how to go through the process, what is expected of them, when to schedule collab cycle reviews, what artifacts to provide and what follow-up is required. The Collaboration Cycle guidance is not well aligned with VSP practice area guidance. The current presentation of the Collaboration Cycle touch points is interpreted as a linear/waterfall process, however that is not how it is intended. Lastly, guidance to VFS teams regarding their roles and responsibilities post-launch are not well defined.

HMW intuitively structure and organize the Collaboration Cycle guidance?
HMW ensure our practice area specific guidance complements the Collaboration Cycle guidance? 
HMW make sure VFS pain points are addressed?

## User Stories
As a Collaboration Cycle team member, I want to provide clear documentation and guidance to VFS teams about the Collaboration Cycle process so that I experience less swirl due to conflicting expectations.

As a VSP Collaboration Cycle team member, I want to ensure VFS teams have a clear understanding of what issues we are identifying so that there is no confusion and/or frustration for VFS teams if/when issues are uncovered at Staging Review.

As a VFS team member, I want to easily understand how to do the tasks related to Collab Cycle so I can proceed in a self-service fashion when possible and not be slowed down waiting for answers or heading down the wrong path.

As a VFS team member, I want to know what issues might be uncovered at Collaboration Cycle touchpoints so that I can ensure they are addressed prior to launch.

As a VFS Product Manager, I want to know what issues could be potential launch blockers so that my product is not delayed due to these issues not being addressed.

As a VSP DEPO lead, I want to ensure there is transparency between VFS and VSP teams regarding platform standards and launch blockers so that I do not have to escalate concerns.

## Hypothesis or Bet
If we provide clear guidance and documentation supporting the Collaboration Cycle, then VFS teams will be better prepared for Collaboration Cycle touchpoints allowing them to easily move through the process.

If we provide clear guidance and documentation supporting the Collaboration Cycle, then VSP Collaboration Cycle team will need to do less hand-holding throughout the process, allowing us to scale and support more teams.

## We will know we're done when... ("Definition of Done")
- [x] Collaboration Cycle guidance has been updated to reflect current DEPO Platform standards
- [X] VFS teams can easily identify what artifacts are necessary for a Collaboration Cycle touch point
- [x] VFS teams can easily ascertain what is expected of them throughout the Collaboration Cycle and _post launch of their product_
- [x] VFS teams can clearly understand when to schedule a Collaboration Cycle touch point in relation to their product build
- [x] VFS teams can clearly understand what post-touch point follow-up is required of them
- [x] 100% of Collaboration Cycle guidance is available in Platform Website.

## Projected Launch Date
Previously: End of Q1 2021
Status as of 3/22/2021: End of Q2 2021
Actual Launch date: August 26, 2021

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: [VA.gov Experience Standards Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/vsp-collaboration-cycle/va.gov-experience-standards-product-outline.md)
* **README**: [_link to VFS-facing README for your product_](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle)
* **User Guide**: [_link to User Guide_](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)
### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: [_link to Release Plan ticket_](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/17275)

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by rroueche** [comment]
@shiragoodman heads up the link to the product outline is broken
