### ISSUE TITLE
Find a VA Form:  Improve Search String Comparison for better fault tolerance

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17244]
## Issue Description
In its current form. the Find a VA Form search appears to do a simple string comparison between the search term entered and the form metadata, yielding poor results when the user does not include dashes, or uses a partial form name
 
|Search term |  Expected	|   Current Result|  
|--|--|--|
| 1010EZ |  Form 10-10EZ is presented as the top match since its name matches the search result if the absence of dash is ignored| No results found |  
|21P1775 |Form 21P-1775 is presented as the top match since its name matches the search result if the absence of dash is ignored|No results found |

##Background Information
Some details about how the current search described here, along with a link to additional info in GitHub:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/19012#issuecomment-774155887

----
## Tasks
- [ ] Determine tasks required to complete this work
- [ ] Create issues for each task and attach to this epic
- [ ] Estimate issues to the best of our ability

## Issues to create
- [x] Discovery issue to break this into tasks and estimate # https://github.com/department-of-veterans-affairs/va.gov-team/issues/19601
- [ ] Collab Cycle

**Comment by MarciMcGuireGCIO** [comment]
Updating title and description to broaden scope to generally improving the search algorithm vs. the previously narrower scope of handling special characters and spaces.

**Comment by MarciMcGuireGCIO** [comment]
Converted to an Epic so we can track related sub-tasks as one body of work.

**Comment by MarciMcGuireGCIO** [comment]
This is being handled as part of this Epic - > Find a VA Form: Add Relevance, Popularity, Related to & PDF Instructions & UI consistency #21639
