### ISSUE TITLE
Remove navigation compass from Facility Locator map

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17248]
## Issue Description
The upgrade to Mapbox included a third button in the zoom control area which may confuse Veterans and raise accessibility concerns. 

---
## Tasks
- [ ] Remove the navigational compass button

## Acceptance Criteria
- [ ] The navigational compass button is not longer visible
- [ ] Keyboard navigation no longer includes the compass button
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
