### ISSUE TITLE
[Development] HLR: Small fixes & code cleanup

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#17240]
## Issue description

Higher-Level Review will likely be released soon. There are still some minor issues (e.g. `<div>` contained in a `<p>`) and some code cleanup that still needs to be done.

## Tasks

- [ ] Final code run through & cleanup
- [ ] Fix semantic markup issues

## Acceptance criteria

- [ ] Code is ready for QA, accessibility and peer review
