### ISSUE TITLE
Test User Account Dashboard - Testing Team Work

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17242]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As Identity team members building the Test User Account Dashboard feature, we need research, specifications, and feedback from the Testing team. 

## Hypothesis or Bet
**If** the Testing team provides research, specifications, and feedback **then** the Identity Team can build the Test User Account Dashboard to better serve their needs.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete?
- [x] The Testing team has participated in UX research to determine the functionality and filter fields for the Test User Account Dashboard
- [x] The Testing team has provided a list of standard users to be included in the standard users population file
- [x] The Testing team will provide help (if necessary & resources available) for integration with other VA service providers

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
