### ISSUE TITLE
Remove formation-react from tools repo

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#17255]
## Issue Description

Remove `formation-react` code from the tools repo and update documentation to use `component-library` instead

---
## Tasks
- [x] Remove mention of 'formation-react' and point to component library as needed 
- [ ] Delete all files under `packages/formation-react` in the tools repo

## Acceptance Criteria
- [ ] `formation-react` is removed

Dependent on announcement of Storybook.
