### ISSUE TITLE
Screenreader announcement and focus for "Search this area" button

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17252]
## Issue Description
As a veteran using a screenreader, I want to be notified when the 'Search this area' button is available so I can use it to refine my search. 
As a veteran using a screenreader, I want to manage focus to the new search results after using the 'Search this area' button so I can hear the new search results, along with the new geographic location.

For the introduction of the "Search this area" button, zooming or panning the map must announce the "Search this area" button for screen reader users (the aria-live attribute is likely to be helpful; it depends on how this is built).
When a user activates the button to search this area, focus must be set on the heading for Results for "VA health", "All VA health services" near "Arlington, Virginia 22202" (with the actual criteria, of course). That way screen reader users will hear the new search results, along with the new geographic location.

---
## Tasks
- [ ] Make "Search this area" button available to screenreaders
- [ ] Move focus to search results header after the "Search this area" button has been used to trigger a new search. 

## Acceptance Criteria
- [ ] zooming or panning the map announces the "Search this area" button for screen reader users
- [ ] When a user activates the button to search this area, focus must be set on the heading for (as example) _Results for "VA health", "All VA health services" near "Arlington, Virginia 22202"_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
