### ISSUE TITLE
Publish component-library & deprecate formation-react

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#17253]
## Issue Description

Prepare `component-library` for publishing by updating the documentation, and deprecate `formation-react`

---
## Tasks
- [x] Move the documentation from the [tools repo README](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/e3e00302ba8bf194ed0c2bf342fb9e38bc753187#updating-formation-and-formation-react) on publishing `formation-react` into the new `component-library` repo.
- [x] Publish initial version of new `component-library` package
- [x] Use [`npm deprecate`](https://docs.npmjs.com/cli/v6/commands/npm-deprecate) to deprecate `formation-react`

## Acceptance Criteria
- [ ] `formation-react` will no longer be updated
- [ ] `component-library` is published
