### ISSUE TITLE
Write tests primarily for checking `color-contrast`

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#17259]
## Issue Description
`color-contrast` accessibility checks should only be done on a select group of pages to cut down on the time it takes the Cypress tests to run.

---
## Tasks
- [ ] Identify a group of pages that cover the VA.gov design template
- [ ] Write tests that check `color-contrast` on identified pages

## Acceptance Criteria
- [ ] 'color-contrast' test coverage will be robust but spread across just a few pages representative of the VA.gov design

**Comment by pjhill** [comment]
For future reference, Dequeue recommends this approach of evaluating a representative sample because the CPU use for evaluating all applications on the Platform would be too intense.
