### ISSUE TITLE
[DISCOVERY] Dynamic query for side nav

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17256]
## Issue Description
A [solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12970) was found to dynamically add FACILITY_MENU_NAMES so the side nav component would be included in new facility builds (rather than using the previous method of hardcoding). A dynamic method is needed to support the increasing volume of new VISNs that are onboarding. The PR had to be rolled back due lack of network access to the Drupal API, causing the builds to fail (or was at least one of the causes).

 
---
## Tasks
- [ ] explore options for dynamically pulling a list of  FACILITY_MENU_NAMES 

## Acceptance Criteria
- [ ] A new solution is outlined and can be groomed and prioritized 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
Closing since https://github.com/department-of-veterans-affairs/va.gov-team/issues/17187 will make it possible to restore the dynamic side nav code without breaking the CI builds.
