### ISSUE TITLE
Copy formation-react to new repo

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#17250]
## Issue Description

Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/15061

Move the component library into its own repo & set up CI for it

---
## Tasks
- [x] Copy code from `packages/formation-react` in `veteran-facing-services-tools` repo into its own repo
- [x] Update `package.json` with the new repo name and any missing dependencies no longer provided by lerna structure
- [ ] Set up CircleCI in this new repo
