### ISSUE TITLE
[DESIGN] COVID-19 search experience on Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17260]
## Issue Description
As a Veteran, I need to search for a facility offering COVID-19 vaccines so that I can be vaccinated and prevent infection. 

**TBD**

1. Main number -> The blue alert button may replace the phone number, pending a decision to be made the week of 12/28. 
2. Does the alert show if Service type = `All VA health services`?

---
## Tasks
- [ ] Design Veteran search experience for COVID-19 vaccines as health service  

## Acceptance Criteria
1. Build ready design spec which includes the following:
- `COVID-19 vaccines` is available in the Service type dropdown when Facility type = `VA health`. The order of services in the list must begin with Primary care and Mental health. 
- Search result cards include blue info button with `COVID-19 vaccines at VA` (similar to urgent care benefit alert) which links Veteran to https://www.va.gov/health-care/covid-19-vaccine/
- Search result cards contain the following
      - Location pin
      - Distance
      - Hyperlinked name
      - Address
      - Hyperlinked "Get directions"
      - Main number
      - Blue alert button "Covid-19 vaccines at the VA"
      - Facility operating status, if available
- Alert shows only if `COVID-19 vaccines` has been selected as Service type (for example, if Veteran selects `Primary Care` as service type, the alert does not appear, even if that facility has COVID-19 vaccines as a service)
- Note:  The mental health number will not display when `COVID-19 vaccines` has been selected as Service type

2. A second spec with 
- all of the above except with the blue button alert replacing the phone number.  

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrisdlogan** [comment]
I have uploaded the specifications for the following:

- Default state of Facility Locator displaying the COVID-19 Vaccine selection in the service type dropdown menu
- Search result cards which contain, location pin, distance, hyperlinked name, address, hyperlinked "Get directions," main number, blue alert button "Covid-19 vaccines at the VA," and facility operating status, if available
- A second version of the results cards which exclude the main phone number.

The specifications are output as HTML. Download the enclosing folder and open index.html to view, and click on design elements to see specs. 

URL: https://drive.google.com/drive/folders/11HM7MgLceAEkoH4Tc4-s_qFeIlSg3dLy?usp=sharing

**Comment by chrisdlogan** [comment]
PNG Version of the 3 screens: [Uploading... Facility Locator - COVID-19 Vaccine Search.png ]

**Comment by chrisdlogan** [comment]
![Facility Locator - COVID-19 Vaccine Search.png](https://images.zenhubusercontent.com/5f7e112df61e4dfc818b06d8/acd2d290-4ed9-4761-8cf5-d0f5753c2aaa)
