### ISSUE TITLE
[Analytics] Upload data needed for ALL Health Program pages and update Suicide for VA Central California health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17270]
## Story
As a web user, I need staff and contact information for all of my health programs, so I can quickly find and reach out appropriate caregiver support.

## Goals
Complete ALL Health Service Program pages in the current System

## Resources
[Staff Profiles for VISN-21](https://drive.google.com/drive/folders/1PyfOuTOkDybK2SQJmvOePks8aCoeD_bw)

## Tasks
Complete ALL health program pages for each System Across the VISN to include the following sites:
- [x] Caregiver Support
- [x] Homeless Veteran Care
- [x]  LGBT-Veteran-Care
- [x]  Mental Health-care
- [x] Minority Veteran Care
- [x] Patient-advocates
- [x] Returning-service-member
- [x] Suicide-prevention (Latest Version)
- [x] Women-veteran-care
- [x] Leadership

## Acceptance Criteria
- [x] Each health program page is completely updated with System information.
- [x] Appropriate Staff profile or location profile has been created "Person or location"
- [x] Local and nationalized information has been provided in the page

**Comment by EdwardBoehme05** [comment]
1. Suicide Prevention page cloned from Sierra Nevada
2. Caregiver Support Coordinator and Mental Health Care POC are TBD.
3. Points reduced from 3 pts. to 1 pt.
