### ISSUE TITLE
Create a mechanism for automatically retrieving CSRF token and sessionID for a given endpoint

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#17274]
## User Story

As a QA engineer creating and executing load tests on the platform, I need the [rake task used to create session cookies](http://jenkins.vfs.va.gov/job/rake_tasks/job/vets-api-load-test-sessions/) to include the corresponding CSRF token. Since the CSRF token is generated for each endpoint, the task should be created with a parameter to point the task at a specific endpoint.

## Expected Behavior

The console output for the rake task includes corresponding X-CSRF Tokens for each session id.

## Solution Brainstorm
* cronjob on interval (monthly?)
   * space out tests in order to allow staging infra to recover from stress/load
* not attached to CI
* scheduled execution
* basic UI to allow on-demand execution of a given load test
* reporting?

## Tasks
- [ ] Discover what % of the tests require authentication (guesstimate = 20/29)
- [ ] Discover environment requirements
- [ ] Design / borrow Puppeteer script to authenticate a user
- [ ] Navigate to the designated endpoint(s)
- [ ] Retrieve CSRF token + sessionID
- [ ] Execute load test for given endpoint using stored creds

## Acceptance Criteria
- [ ] User input for the endpoint is prompted

**Comment by rjohnson2011** [comment]
*Insights from Research 2/2*
- This ticket is large in scope, and really encompasses 3 different aspects:
  1. Move token generator from Jenkins to CircleCI (which may not be necessary if using Puppeteer to pull the proper request headers).
  2. Write a script/scraper to authenticate into staging.vets.gov as a user and pull the request/response headers (Cookie & CSRF tokens).
  3. Invoke the script to pull request headers and asynchronously and await the response in the load tests. 
- Most of the 26 load tests require a unique Cookie & CSRF token that would have to be generated individually involving a sign in authentication and their own endpoint.

Remaining Questions:
- If we write a Puppeteer script to generate the proper request headers, where would this live to be invoked by the load tests? A possible option is a Heroku microservice triggered by an endpoint request and argument passed via the Locust test. It would require adding an async request to each of the load tests.

**Comment by pjhill** [comment]
OBE
