### ISSUE TITLE
Design "Clear input" for FLocator fields

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17272]
## Issue Description
As a Veteran, I need a way to efficiently clear Facility Locator text fields (City, state, or postal code and Service typeahead) so that I  can change the input(s). 

---
## Tasks
- [x] Translate hackathon design to match the design system

## Acceptance Criteria
- [x] Specs are consistent with the design system and include size, color, and transparency.
- [x] Spec details expectations for behavior, such as: 
       - Veteran can clear input by clicking on the x.
       - Veterans using assistive tech can clear the field using keyboard commands.
       - Veterans using assistive screenreaders are aware of this functionality.
       - Use the screen reader only class and use aria-hidden on the svg
       - When a Veteran clicks on the x in the field, the input is deleted and the field remains active for a new entry.
       - Search is not available until all required fields have been populated.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
### Goal:
Incorporate a “Clear input” button on Facility locator’s location input field.

### **Problem to be solved:** 
Today, if a user wants to change an inputted location, then the user must manually highlight all the text in the field. This happens when a user is geolocated. Geolocated addressed are very long so it’s cumbersome to highlight or delete all the text within the field. 

![image.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/ffde7a06-1050-4765-b949-47e9a0162cd4)

### Solution:
A clear input button would allow clearing the input with clicking of an icon.
![image.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/0051b4cc-6141-4a4a-9011-799217b1ce50)

### Research:
[Mural board with reference examples](https://app.mural.co/t/vsa8243/m/vsa8243/1608209536683/390da5c82d07a0365d6b7fe9cad0665d52f05474?wid=0-1608212540964) 
[Comparative analysis spreadsheet](https://docs.google.com/spreadsheets/d/1sIqiSYLL6JXqaQJ3iGUnBYYjOxFLTmn0TRWeN0HcDbM/edit?usp=sharing)

### PROPOSED DESIGN

Before interaction
![Before interaction.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/3bae1af4-eac9-4ab2-bbc4-a1ba45d00128)

Clear input button appears after first character is inputted
![After first character is inputted.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/d9db78c1-c491-4dbb-8cb7-c85fe52fd15b)

While text is being inputted and exceeds the input's width, the text moves left. Text area is never overlapped by clear input button.
![Text exceeds input width.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/d097fc88-e786-49cd-bd67-e4a977e28c16)

When user exits input (no longer in focus) the inputted text displays left to right. Overflow text (at the end of the text string) is overlapped by clear input button. When clear button is clicked, input is cleared and design matches "Before interaction" state.
![After entry when not in focus.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/f9f02eca-3b1b-4a2a-b812-7fa1829b51c2)

### Sepcs
![Specs.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/85a18bd2-9520-4c29-81f7-bf487c6c9db7)

**Comment by lildziner** [comment]
![times-circle-solid.svg](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/67404b12-91d8-4342-981d-eb83df1469bf)

**Comment by lildziner** [comment]
Regarding accessibility, from Josh: 

"If you stick with the “X” icon, **I’d recommend using the screen reader only class and using aria-hidden on the svg.** Using aria-label on the svg itself has been documented to have some failures in some browser/screen reader combinations. [More on this technique in this article by Sara Soueidan](https://www.sarasoueidan.com/blog/accessible-icon-buttons/#technique-1-accessible-visually-hidden-text) 

and 

[reasons why aria-label on the svg can be faulty](https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y#svgs-within-links-and-buttons) in this article by Scott O Hara."
