### ISSUE TITLE
COVID-19 vaccines keep me informed tool: Confirmation email content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17277]
## Issue Description
We need content for the tool's confirmation email.

---
## Tasks
- [ ] Draft content 
- [ ] Revise as needed

## Acceptance Criteria
- [ ] Confirmation content implemented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
**Name:** COVID-19 vaccine updates confirmation

**Subject:** We've received your information

**Content:**

Dear Veteran,

Thank you for signing up to stay informed about COVID-19 vaccines at VA. When we have new information to share about our COVID-19 plans and your vaccine options, we'll send you updates by email or text.

You can also visit our main [COVID-19 vaccines at VA page](https://www.va.gov/health-care/covid-19-vaccine/) for the latest information and answers to common questions.

**Remember:** This form doesn’t sign you up to get a vaccine. And you can change your mind about getting a vaccine at any time. We’ll use the information you provided to understand your interest and keep you informed. If you want to update your information later, you can submit a new form.

**Comment by toddstanich** [comment]
Dropped the content in a mockup below. A few comments:
• As a best practice we aim to display the full URL for any links so Veterans have the ability to view where the link will take them and can also copy and paste if they do not feel comfortable clicking the link. If you can work the full URL in the content, I'd recommend that.
• For the standard closing, we've used "Thank you for your service, VA.gov" when the email will always be going to Veterans. Can we confirm that this is a Veteran only email?
• Absolutely open to adding a phone number to the footer text.

![COVID-Vaccine.jpg](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/c4175445-8c6d-4d49-8f59-c439cf400048)

**Comment by miabecker** [comment]
Dear Veteran,

Thank you for signing up to stay informed about COVID-19 vaccines at VA. We’ve received your information as of 12/10/2020. Your Reference ID is: 19835.

When we have new information to share about our COVID-19 plans and your vaccine options, we’ll send you updates by email or text.

You can also visit our [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) page for the latest information and answers to common questions at https://www.va.gov/health-care/covid-19-vaccine/.

**Remember:** This form doesn’t sign you up to get a vaccine. And you can change your mind about getting a vaccine at any time. We’ll use the information you provided to understand your interest and keep you informed. If you want to update your information later, you can submit a new form.

Thank you for your service,
VA.gov

You’re receiving this email because you submitted a form on VA.gov. Please don’t reply to this email. If you need to contact us, go to https://VA.gov.

**Comment by toddstanich** [comment]
Updated mockup:

![COVID-Vaccine.jpg](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/20db7c10-c989-4db2-9aff-db7fea0f7b37)

**Comment by miabecker** [comment]
Dear Veteran,

Thank you for signing up to stay informed about COVID-19 vaccines at VA. We’ve received your information as of 12/10/2020.

When we have new information to share about our COVID-19 plans and your vaccine options, we’ll send you updates by email or text.

You can also visit our COVID-19 vaccines at VA page for the latest information and answers to common questions at https://www.va.gov/covid-19-vaccine.

Remember: This form doesn’t sign you up to get a vaccine. And you can change your mind about getting a vaccine at any time. We’ll use the information you provided to understand your interest and keep you informed. If you want to update your information later, you can submit a new form.

Thank you for your service,
VA.gov

You’re receiving this email because you submitted a form on VA.gov. Your reference number 19835.
Please don’t reply to this email. If you need to contact us, go to https://VA.gov.

**Comment by toddstanich** [comment]
Updated based on content above.

![COVID-Vaccine.jpg](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/0b9e4997-1b2c-4e68-aa16-9536e117bedd)
