### ISSUE TITLE
[Collaboration Cycle Custom Tracks]: Release Plan

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#17278]
## Guidance

_This Release Plan Template is intended to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

**- Desired date range or test duration:** 12/10/2020 through end of 2020 Q4 (or possibly into 2021 Q1, dependent on how many teams request project kickoffs through Collaboration Cycle)
**- Desired number of users:** 5 VFS teams
**- The group(s) from which you'll recruit test users:** VFS
**- How you'll recruit test users:** through the existing Collaboration Cycle process
**- How you'll give test users access to the product:** N/A. Our test users will be asked questions orally at Project Kickoff.
**- What "Success" criteria will you look at before launch?** Our success criteria is defined by validation of our assumptions. Our assumptions are:
1. These questions could replace Project Kickoff.
2. Teams can answer these off the cuff - they don't need advanced noticed.
3. Teams can answer these questions as early as kickoff.
4. The questions we choose to ask don't encourage waterfall thinking.
5. In answering these questions, teams buy-in to the process.
6. This process results in significant amount of teams having leaner paths through Collaboration Cycle.
7. Also, we'd like to ensure that the custom track identified by the questionnaire is in line with what the Collaboration Cycle reviewers believe is appropriate for the VFS team.

**- How you'll measure your "Success" criteria?**  Yes, our assumptions were met, or No, they were not. Yes, the custom track identified by the questionnaire is in line with what the Collaboration Cycle reviewers believe is appropriate for the VFS team, or no it is not.

### Results:

- Number of users: 4 	

- Results per your "Success" criteria:
1. These questions could replace Project Kickoff. Yes
2. Teams can answer these off the cuff - they don't need advanced noticed. Yes
3. Teams can answer these questions as early as kickoff. Yes
4. The questions we choose to ask don't encourage waterfall thinking. Yes
5. In answering these questions, teams buy-in to the process. Yes
6. This process results in significant amount of teams having leaner paths through Collaboration Cycle. Yes
7. Also, we'd like to ensure that the custom track identified by the questionnaire is in line with what the Collaboration Cycle reviewers believe is appropriate for the VFS team. It was

- Number of bugs identified / fixed: N/A

- Any UX changes necessary based on the logs, user feedback, or VA challenges? N/A

### Planning:

- Desired launch date: 2/17/2021
- Post-launch KPI 1: 50% of initiatives have leaner path through the Collaboration Cycle (AKA not the full path)
- Post-launch KPI 2: 75% favorability of teams via Zoom survey at Staging Review

### What will be included in the release:

- [ ] Team concerns about introducing the terminology "Custom Tracks" - it's not a new product, its just a change to the Collaboration Cycle. Questions? Questionnaire? 
- [x] Project Kickoff and Design Intent will be merged into 1 meeting called Design Intent (formerly called Collaboration Cycle Kickoff, but we thought it would be too confusing for VFS teams).
- [x] Usability Testing Prep will be renamed to Midpoint Review
- [x] Collaboration Cycle Office Hours will be added to our weekly calendar (potentially replace Wednesday timeslot for reviews)
- [x] Midpoint Review and Staging Reviews templates will be updated to request VFS team give VSP reviewers appropriate access to secured applications.
- [x] VFS teams will be given the option to have Design Intent and Midpoint Reviews held asynchronously.
- [x] Incorporate the practice area involvement into the Collaboration Cycle. 
- [ ] Incorporate the Content Outline as a required artifact (if content is identified as a practice area involved in the initiative). (REMOVED because of changes from Sitewide Content team)
- [x] The Custom Tracks questions will be it's own referenceable markdown file available via the Collaboration Cycle README.
- [x] Examples and/or additional details will be provided for each Custom Tracks question in the Custom tracks questions md file.
- [x] VSP will have scripts for the Collaboration Cycle Kickoff, Midpoint Review and Staging Review stating the purpose of the review, VSP commitment and VFS expectations.
   “You are going to need to do your own QA, here’s how.”
   “You are going to need to test new patterns for design, here’s how."
- [x] The sequence in which the Collaboration Cycle Meetings will be reordered so the IA Request is earlier in the process.
- [x] The guidance for the Full Accessibility and 508 Audit will be updated to reflect that all a11y issues found at Staging Review must be addressed prior to a Full Accessibility and 508 Audit ticket can be submitted.
- [ ] References to Storybook (included in script for Collab Cycle kickoff?) (guide teams to go to design.va.gov)
- [x] Add VSP Calendar to README
- [x] Remove individuals names from all Collaboration Cycle User Guide
- [ ] Create another md file under README explaining who we are (similar to Orientation)
   Add Darius alongside Peter for QA.
   Remove mentions of Emily.
   Remove mentions of Kevin.
- [x] Add research synthesis to Resources heading in README page
- [ ] set up Zoom poll
- [ ] For Midpoint Review, include Research Plan & Conversation Guide as required artifacts
- [ ] In Slack and Newsletter announcement, share that VFS teams should no longer reach out directly to Collab Cycle team members for direct support with content, IA, design, QA and/or accessibility.

### Documents in need of updating:
- [Collaboration Cycle README.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle)
- [Collaboration Cycle visual](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf) - low priority
- [Collaboration Cycle descriptive text (AKA the User Guide)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)
- [Project Kickoff Issue Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=project-kickoff.md&title=Project+Kickoff+%5BTeam+Name+-+Feature+Name%5D)
- [Design Intent Collaboration Issue Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+allison0034%2C+emilywaggoner&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=design-intent-collaboration.md&title=Design+intent+Collaboration+%5BTeam+Name+-+Feature+Name%5D) - remove
- [Usability Testing Prep Issue Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=usability-testing-prep.md&title=Usability+Testing+Prep+%5BTeam+Name%2C+Feature+Name%5D)
- [Staging Review Issue Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D)
- [Full Accessibility & 508 Office Audit](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+shiragoodman%2C+noahgelman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)

### Documents in need of creating
- Custom Tracks questionnaire markdown file (accessible via README)  
- Who We Are markdown file (accessible via README) (NO LONGER CREATING - PART OF README)
- Communication message for Slack for VFS teams
- Newsletter article
- VSP Internal Script for Collaboration Cycle Kickoff, Midpoint Review, and Staging Review

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 7 PMs completed 12 Collab Cycle Kickoff tickets. 1 Staging Review.
- Post-launch KPI 1 actual: 58.33% were recommended a leaner path through the Collaboration Cycle. Goal was 50%.
- Post-launch KPI 2 actual: 83.33% state the experience has been favorable or somewhat favorable. Goal was 75%.
- Any issues with VSP handling/processing?: No
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? No
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"? The KPIs are on track with our pre-launch definition of success. We are still looking to gather more data for the favorability KPI.
2. What qualitative feedback have you gathered from users or other stakeholders, if any? We have not solicited users for feedback, however Service Design team did a VFS feedback [survey for Q1 ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1613697702881/8a0216fc79234f04ebab1cfe0b86da56f7b73104)that aligned with the release of our enhancements.
3. Which of the assumptions you listed in your product outline were/were not validated? All of our assumptions have been validated. However, by having the Collab Cycle Kickoff replace the Project Kickoff, we are not able to communicate to VFS as early in the process what other teams, products, services, tools, etc. on VA.gov are related or they could view for reference. This can still be done, just not as early in the VFS process. 
4. How might your product evolve now or in the future based on these results? We will be making some modifications to the Collaboration Cycle kickoff questions to address some findings found through analysis of the PM responses. In the long term, we'd still like to move towards a self-service automated tool for this part of the process. We would like to get to a point where we can trust the responses from PMs in our tickets, and not have to validate the responses against their Product Outline.

**Comment by shiragoodman** [comment]
Hypothesis #1 - These questions could replace Project Kickoff.
#2 - Teams can answer these off the cuff - they don't need advanced noticed.
#3 - teams can answer these questions as early as kickoff.
#4 - the questions we choose to ask don't encourage waterfall thinking
#5 - in answering these questions, teams buy-in to the process
#6 - this process results in significant amount of teams having leaner paths through CC (at least 30%?)

**Comment by shiragoodman** [comment]
@allison0034 please review the Phase I planning section above and let me know if you have any questions or concerns

**Comment by shiragoodman** [comment]
@allison0034 please update the Results section to include the 4 kickoffs where we tested the wizard. Please let me know if you have any questions.

**Comment by shiragoodman** [comment]
@allison0034 can you expand upon the Results section in Phase 1 above - per our discussion with Rachael on 1/21? For example: 

1. These questions could replace Project Kickoff. Yes
While these questions will not replace Project Kickoff, they will be asked during the Project Kickoff to help VSP understand the intent of the VFS initiative, as well as the practice areas involved in the initiative. In the future, it would be ideal for the VFS teams to complete these questions on their own time so kickoff can be asynchronous or no longer necessary. 

feel free to use this for #1. Let me know if you need assistance with the others.
