### ISSUE TITLE
Monitoring - Move licenses for {fwpdroxy,vets-api} APM from DEV to STAGING (Datadog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17290]
## Issue Description
_Due to the fact that we have limited number of licenses for Datadog, we want to re-allocate licenses that are currently used in the dev environment, to hosts running in the staging environment. These licenses will be used to activate application performance monitoring (APM) on selected instances, for the purpose of collecting metrics for the infrastructure services known as "fwdproxy" and "vets-api". 

These metrics will be used to power a dashboard that will be used by the Backend Tools team for the purposes of providing an SLO report around accessibility of external services. _

---
## Tasks
- [x] Re-allocate Datadog licenses currently used on {fwpdroxy,vets-api} hosts in DEV to {fwpdroxy,vets-api} hosts in STAGING
- [x] Ensure that the dashboard for Backend Tools team is still working for the purposes of SLO report.

## Acceptance Criteria
- [x] APM will be working for {fwpdroxy,vets-api} in STAGING
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Looks good. Closing.
