### ISSUE TITLE
IRIS Q&As: Education -- Payments

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#17298]
### Issue
For the launch of Resources and support MVP 1.1, content that fall into the "payments" category under education & training needs to be developed based on the following:

- https://gibill.custhelp.va.gov/
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)
- Credible external sources as needed

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

- [x]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

 - [x] PW to develop draft copy (Laura)

 - [x] PW to assign tags (Laura)

 - [x] DEPO to complete initial review (Beth) 

- [x] PW to copyedit draft (Randi)

 - [ ] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [ ] Copy deck ready for 2nd DEPO review and attached to a content review GH ticket.

### Up-to-date copy deck
Please use the deck shown here and replace it when you make edits/comments to ensure that the latest document is always here, at the top of this ticket. 
[rs-1.1-education-payments-v0.1-12-09-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5674745/rs-1.1-education-payments-v0.1-12-09-20.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Copy deck is ready for your initial review, and is attached to the top of this ticket. (I will flag if for copy editing by Randi once you give me the go-ahead.) Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 For this Q&A, can you do some research and find out how you verify enrollment and how you choose either check or direct deposit? It would be good to include that information in the answer:

**When will I get my first education benefit payment?**

The time it takes for your payment to arrive depends on how you choose to be paid. Find out how many days it’ll take for you to get your payment after you verify enrollment.

**If you choose to get your payments by check,** you should receive your first check by mail about 14 days after you verify your school enrollment. 

**If you choose to get your payments by direct deposit,** you should receive your payment 7-10 business days after you verify your school enrollment.

Please use a new comment to let me know what you found rather than amending the deck, since I already have my edits in a new version of the deck that's in progress.

**Comment by lwalsh617** [comment]
Will do!




–––

Laura Walsh

Content Strategist | Writer

m. 617.549.5496

–––



________________________________

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- I Slacked you this Word doc, but attaching here for tracking purposes. 
[ed benefits payments QA.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5767533/ed.benefits.payments.QA.docx)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 for awareness: Here are my edits. I'll accept these in track changes and send to the SME for review.  I had to remove the restoration of benefits content because I discovered that it was one of the pages flagged for rewriting. We'll tackle that separately.

@lunascoop This multiple FAQ is ready for you to build the page in drupal. 

@RLHecht for awareness. I'll ask you to copyedit what's in drupal after I get feedback from the SMEs.

[https://app.zenhub.com/files/133843125/6b920fe5-1845-49fd-8b26-189534c8dcc0/download](https://app.zenhub.com/files/133843125/6b920fe5-1845-49fd-8b26-189534c8dcc0/download)

**Comment by lunascoop** [comment]
@bethpottsVADEPO The multiple FAQ has been created.

GI Bill payments: http://preview-prod.vfs.va.gov/preview?nodeId=15640

**Comment by bethpottsVADEPO** [comment]
@lunascoop There are some minor edits here for you to incorporate based on SME feedback. Some links we'll need to create once other articles launch... thanks!

[https://app.zenhub.com/files/133843125/4f5b5116-2da7-412e-8a83-a15c7db1fcfa/download](https://app.zenhub.com/files/133843125/4f5b5116-2da7-412e-8a83-a15c7db1fcfa/download)

**Comment by bethpottsVADEPO** [comment]
@lunascoop Please alert @RLHecht when you're done, and she can do her copyedit.

**Comment by lunascoop** [comment]
@RLHecht the copy for this multiple QA has been updated and is ready for review (cc: @bethpottsVADEPO )
GI Bill payments: http://preview-prod.vfs.va.gov/preview?nodeId=15640

**Comment by RLHecht** [comment]
I reviewed this and made a few copy tweaks. Also had a few questions:

Why is my monthly GI Bill payment less than my monthly rate?
- Should we link to the education rates page?
- In the example we use, do you think we need to show the math for how we got to $320 for August 19 to 31?

Is it OK that one of our CTA buttons is the same as a related link? Another suggested related link is the [GI Bill School Feedback Tool](https://www.va.gov/education/submit-school-feedback/introduction)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks for raising these. 
1/ Yes, I will added a link to the education rates page.
2/ I'm ok with the level of mathiness we have there! Mostly because we're short on character count.
3/ Can you look into whether we already have a CTA button that goes to the change-direct-deposit page? I'm asking because you thought we had a duplicate CTA and related link when in fact one is the how-to article and the other is the actual change direct deposit page in tier 1. But if it confused you, it'll confuse others too! So I'm thinking of changing the button label to: Sign in to change VA direct deposit info. But I want to see how we've labeled it elsewhere in R&S. Would you let me know in a comment here?

Also, I'm in touch with Tammy about one other detail. So some of these questions may very slightly alter with whatever she comes back with. I'll let you know.

**Comment by bethpottsVADEPO** [comment]
@RLHecht OK, want to take one more look then set to publish? I added the payment rates link.

**Comment by RLHecht** [comment]
This page is now published! Moving to validate and will close after today's deploy.

**Comment by RLHecht** [comment]
This page is live on the site and added to the R&S landing page. Closing ticket.
