### ISSUE TITLE
Design Intent Collab [Content & Localization -Translations | Spanish Corona Pages]

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17291]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in team name and feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Allison Christman & @ Emily Waggoner
- [x] Allison and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] Design Intent collaboration meeting completed 
- [x] [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)) https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11599
- Sketches
- Lo-fi mockups - [https://app.zenhub.com/files/133843125/ea7608fd-29c4-4b51-9849-2124d2b37247/download](https://app.zenhub.com/files/133843125/ea7608fd-29c4-4b51-9849-2124d2b37247/download)

## Meeting attendees from **requesting team**
- Designer(s) (required): **name(s)** Ryan Thurwell
- Product Manager (optional): Sharon Kasimow
- DEPO design lead (required as applicable): **name** Ryan Thurwell
- Other specialists: **names** (Optional): Danielle Thierry, Fareez Ahmed

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite **Fri 12/18 at 2pm et**
- _If no available time slots work for your team, write your availability and requirements here and Crystabel will reach out as needed_

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by SKasimow** [comment]
Hi @DanielleThierryUSDSVA - I've drafted the ticket for the Design Intent Collab; can you send me (or add) the mock-ups once they are available and I'll work with VSP to get a meeting set up.

Also, lmk if there are any other people I should include for the review.

Thanks, Sharon

cc: @youngfreezyVA

**Comment by allison0034** [comment]
@SKasimow  Hi Sharon! This meeting has been scheduled for 12/17/2020 at 2:00 ET. This is less than 48 hours, however, due to the upcoming holiday and the small size of the change, we decided it would be best to squeeze it in. If a VSP team member is unable to attend, they can provide feedback on this Epic.

**Comment by SKasimow** [comment]
@allison0034 sounds good - thanks Allison!

**Comment by allison0034** [comment]
@SKasimow there is no design feedback. Reference the [typography guidelines](https://design.va.gov/design/typography). Also, check the Sketch file. Try to use font awesome when picking an icon. Good work!

**Comment by SKasimow** [comment]
@allison0034 -excellent - thanks again!


cc: @youngfreezyVA
