### ISSUE TITLE
User attributes is missing an ID.me UUID

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17306]
## Issue Description
Issue from the Sentry Hackathon (December) in which the SAML request comes back with missing UUID.

---
## Tasks
- [ ] Research: Fix missing ID.me UUID error in Sentry & Ruby

## Acceptance Criteria
- [ ] Error is not populated in Sentry
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joeniquette** [comment]
Access Staging DB instructions: https://github.com/department-of-veterans-affairs/va.gov-team/blob/fc41e3164c2467420c21a742047f4b26e74e5b83/platform/engineering/backend/aws-shell-access.md

**Comment by bosawt** [comment]
If we can find a test user with a sec_id and not an idme_id, we can hack `app/models/user_session_form.rb#idme_uuid_from_account` to use the sec_id when idme_id doesn't exist, and see what happens to the rest of the sign in process

**Comment by joeniquette** [comment]
This ticket evolves into researching how to label the uuid missing for id.me if its v1 and outbound. So if the context is dslogon, mhv, or id.me && version v1 of the API, then we need to be alerted and investigate the issue. Otherwise if its inbound v1 or v0, we do not want to see an error as this is expected. [Identity Error Messages](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/login/error-messages) @bramleyjl Please associate this ticket with your issue.
