### ISSUE TITLE
Best Bets URL fix

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#17300]
## Issue Description
We need to fix the url in Best Bets for On-the-job training. The "and" needs to be removed from the last segment of the url. 

This is the correct url: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/

![image.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/bbf67a42-5fa7-4b75-8547-690eff5fec75)

---
## Tasks
- [x] Fix the url.

## Acceptance Criteria
- [x] Best bets link goes to the On-the-job training and apprenticeships page instead of "Sorry--we can't find that page"
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
This is fixed and live.   Feel free to validate and close -- TY.

<img width="609" alt="Screen Shot 2020-12-10 at 1 33 51 PM" src="https://user-images.githubusercontent.com/63107147/101814626-68ceac80-3aec-11eb-8ecf-db02187f0e1a.png">
