### ISSUE TITLE
SSL certificate replacement - www.va.gov by Jan 24, 2021

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17301]
## Issue Description
_Replace security certificates for www.va.gov before they expire in late January._

[According to a Jenkins SSL certificate scan result](https://dsva.slack.com/archives/C37M86Y8G/p1607360173345000): certificates for www.va.gov are set to expire in less than 60 days, on 2021-01-24  in {DEV,STAGING,PROD} environments. 

---
## Tasks
- [ ] _Request and install certs for www.va.gov in {DEV,STAGING,PROD}  environments_
- [ ] _Test by connecting to the endpoints and ensuring that the updated certificates are returned_

## Acceptance Criteria
- [ ] _Services are up and running using new certs_
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
