### ISSUE TITLE
Implement manual "use my location"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17319]
## Issue Description
This idea originated with @mpelzsherman - Hackathon, November 2020
Veterans need to be able to opt-in for geolocation manually. It should not be auto-detected. We need to implement a call to action.

## Accessibility resource
This might be a [helpful reference](https://adrianroselli.com/2021/01/multi-function-button.html) for handling “loading” accessibly within a button

[Michael's PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14963)

Decision: use existing mapbox logic for both mobile and desktop

Note: location of link and icon is different for desktop and mobile
 
## Tasks
- [ ] Remove automatic geolocation
- [ ] Implement manual geolocation based on [design spec](https://app.zeplin.io/project/600877fdb269d8a4f1f44efd/screen/600879364afaa6a6a2a8a827)
- [ ] Ensure button remains present during error messaging (since it can be used to resolve the field error) 
- [ ] Implement data layer to track metrics on use
- [ ] Add an e2e test (if possible)

## Acceptance Criteria
- Veterans can enable use of current location through hyperlink at search level
- When a Veteran clicks the link, the parameters populate the search field
- There is a "searching" indicator that the location is being identified 
- Design signoff: Implementation is consistent with design spec
- Accessibility signoff
- Data layer in place

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@chrisdlogan please attach SVG for the location icon and font awesome reference for animation

**Comment by chrisdlogan** [comment]
@mpelzsherman here is the fontawesome URL: https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons

**Comment by mmiddaugh** [comment]
@joshkimux @tlei123 we'd love your feedback on this one when you are able

**Comment by joshkimux** [comment]
@mmiddaugh @mpelzsherman 

First off, great work! This is going to make selecting a location so much easier ✨ 
There's a couple of issues that will need to be tweaked for accessibility which I've documented below:

### "Use my location" should be written as a button `<button>` instead of a link `<a>`
- Since the user is not navigating to a new page, a button would be semantically more appropriate
- Veterans with voice assistive technology will be able to access this better, as they will more likely ask their tech to "Click on the use my location _button_" instead of "Click on the use my location _link_." 
- Keyboard users will be able to accurately use the `space` bar as well to activate it instead of just the `enter` key.

### Focus must be managed after allowing to use their location
Currently, focus is lost after the user selects "Allow Use." This causes several issues:
- Keyboard users must tab again to reach the "Use my location"
- Screen reader users may become confused as an error is thrown as well when additional instructions to "choose a facility type" are provided but the focus itself is not set to anything. When they `tab`, they reach the "Use my location" instead.

https://user-images.githubusercontent.com/14154792/110351406-ca76b800-8002-11eb-8555-9ebf477c6e80.mov

The team may want to consider several things here when fixing this:
- Focus could be placed on the populated "City, state or postal code" input field so that screen reader users can confirm their location and keyboard users can easily edit it
- Not throwing an error to choose a facility type will prevent screen reader users from becoming confused, and save some frustration for sighted users too

### A group label by using a `<fieldset>` and `<legend>` may provide valuable additional context

Upon a first tab within the initial search form, a screen reader user will hear "Use my location." Providing additional context through a group label e.g. "Find a VA location" may make it more explicit as to what they are using their location for without the need of navigating around the button itself for more context.

I remember a prior conversation that something like this would be a larger effort. This wouldn't make for a high level defect, but it could greatly improve the user experience for screen reader users.

[You can reference this codepen I made for this demonstrating how a group label could work](https://codepen.io/joshkimux/pen/WNGmXxG)

**Comment by mmiddaugh** [comment]
Will keep this issue open to handle focus management. The other feedback items have been moved into separate issues. 

- "Use my location" should be written as a button <button> instead of a link <a> #21247
- [CONSIDER] adding group label by using a <fieldset> and <legend> (FL) #21249

**Comment by joshkimux** [comment]
Thank you @mmiddaugh , that's perfect

**Comment by tlei123** [comment]
> @joshkimux @tlei123 we'd love your feedback on this one when you are able

@mmiddaugh , I hope to get to this late this week or early next.  Got another team's QA test-runs in-progress right now.

**Comment by mpelzsherman** [comment]
A couple of things I'd like to point out here:

1. In production right now, we always try to geolocate the user _automatically, without warning_. One of the main goals of adding this "Use my location" button is to put that behavior under the control of the user. This feature doesn't introduce any **new** issues with regard to focus after enabling geolocation.
2. Every browser handles granting geolocation permissions differently. There is no standard API for handling permissions events. It will take a significant research effort to determine a cross-browser solution for implementing the acceptance criteria.

**Comment by tlei123** [comment]
@mmiddaugh , can someone Add me to the Zeplin project please? [Zeplin User ID: tlei123 (tze@adhocteam.us)]

I tried to access the [design spec](https://app.zeplin.io/project/600877fdb269d8a4f1f44efd/screen/600879364afaa6a6a2a8a827), but Zeplin threw up an error-message saying "You're not invited to this project."

**Comment by tlei123** [comment]
@mpelzsherman , I think making geolocation manually triggered is a GREAT idea too!

Here's some preliminary feedback [not much beyond what @joshkimux has provided] -- it's definitely not broken...

### Geolocation allowed:
- I can confirm the error message @joshkimux mentioned above [for **Facility type**] also gets thrown when using the mouse to click **Use my location**.  I must admit I myself [not just vision-impaired users] got confused by that, since I haven't even gotten to or past that field yet.
- The auto-populated geolocation value collides with the "**Clear-input**" button (X-icon) in the search text-field.  This makes the text hard to read and the button hard to discern.  For a second, I though it was some kind of font-anomaly.

### Geolocation blocked:
- Let's hope **Permission-API** gets more cross-browser support!  The tiny "geolocation-blocked** icon that gets displayed the address-bar is easily missed, and Users might think something's broken in our app.  It'd be great if we could some day add an alert reminding the User that he/she has blocked geolocation -- especially in case he/she has set browser-settings to always block it and simply forgotten about that.  I myself had to double-check what I've set myself.  :D

**Comment by mpelzsherman** [comment]
I sent you an invite to the Zeplin project, @tlei123 . 

We have a ticket to address the premature error messages.

> The auto-populated geolocation value collides with the "Clear-input" button (X-icon) in the search text-field.

I'm not sure what to do about that, given @davidconlon's request that we populate the field with the complete address, including the full country name. I suggest omitting the country name.

> It'd be great if we could some day add an alert reminding the User that he/she has blocked geolocation 

Agreed 100%! I even coded up an alert, but was told to hold off on this pending further research.
Here's one approach we discussed - using a Modal dialog:

https://recordit.co/BmJjt9fWsS

**Comment by mpelzsherman** [comment]
@joshkimux Adding a `<fieldset>` and `<legend>` wouldn't be that hard. It might cause some styling issues that we would need to address, but if it makes it easier for screen readers, that's great.

Side note: It would be interesting to get some metrics on how many users actually use the Facility Locator using a screen reader.

**Comment by joshkimux** [comment]
@mpelzsherman it would be interesting indeed, and lots of people have asked that question before both here and in a number of industries (myself included). However, I've learned that doing so (even with good intentions) can result in an ethical dilemma of purposeful neglect.

From Deque:

> Another fear that blind users have is that web site owners may use usage statistics against people with disabilities. If the web server logs show that only a small percentage of users have screen readers, a web site owner could make a business decision not to support screen readers, based solely on the perceived lack of importance of blind customers. There are two main problems with relying on usage statics to drive that kind of a decision.
> 1. If the web site is inaccessible, blind users are unlikely to use it, thus driving down their usage statistics.
> 2. Usage statistics are sometimes used to determine things like when not to support a certain browser, or a certain version of a browser. That makes sense, because users can upgrade their browsers as technology marches forward. It's different for screen reader users though. Blind users cannot choose to not be blind. A choice to not support screen readers is a choice to exclude an entire segment of the population, even though yes, it is a minority.

**Comment by mpelzsherman** [comment]
Good points indeed @joshkimux . I'm in full support of the VA's efforts to make our site as accessible as possible.

One of the things I love about working for the VA is that our decisions aren't based solely on profit. ❤️  🇺🇸

**Comment by tlei123** [comment]
> I sent you an invite to the Zeplin project, @tlei123 .

I'm in!  Thanks much, @mpelzsherman !  :)

> I'm not sure what to do about that [text-icon collision], given @davidconlon's request that we populate the field with the complete address, including the full country name. I suggest omitting the country name.

Great suggestion!  I'll add some QA-weight to your suggested solution here [assuming country-name inclusion is not a legal requirement]...

Given that the text collides with the button, including the country-name arguably generates less benefit than cost:
- low benefit:
  - it's almost certain that the User already knows what country (s)he's in before clicking **Use my location**, and including country-name helps arguably very few Users
  - the country-name's already obscured; moreover, depending on full-address length, may be completely truncated
- high cost:
  - ALL Users would see this visual anomaly, compromising usability and eroding perceived quality of not just this feature, but VA.gov site in general.
  - the obscured button, no longer easily discernible as interactive, may well end up altogether unused.

**Comment by tlei123** [comment]
@mmiddaugh @mpelzsherman , I also did a quick check on my iPhone 12, and the features working.

Unless you have any objections, I'm gonna hold of 'til this, #21247, #21249 *, & #21253 are Closed before running a full QA cross-device/-browser test-run.

*IF 21249 (fieldset & group-label) does get postponed, then lemme know if I should conduct full test-run before that gets Closed.

**Comment by mmiddaugh** [comment]
@tlei123 I am confident that #21249 (fieldset & group-label) will remain in the backlog for now. #21253 is now closed and #21247 is pending.

**Comment by mmiddaugh** [comment]
@mpelzsherman which part of the focus management feedback from the [comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17319#issuecomment-796923437) is possible/reasonable?
> If the user chooses to enable geolocation - focus needs to go to the browser verification/approval modal (we assume this is automatically handled by the browser but this needs to be tested) -> when the browser focus goes away, the focus should go to the City, state, postal code field, whether or not approval was given in the browser modal. This allows the populated value to be announced/reviewed by the user before moving on to the Facility type selection or so that the user can enter the location (in the event the user declined approval in the browser).

**Comment by mpelzsherman** [comment]
> focus needs to go to the browser verification/approval modal

Not feasible. This is controlled by the browser.

> the focus should go to the City, state, postal code field, whether or not approval was given in the browser modal

We can focus the field after geolocation finishes, regardless of success/failure. But we shouldn't "steal" focus away from a currently-focussed field.

**Comment by mpelzsherman** [comment]
We need a ruling on the UX for messaging the user if geolocation fails due to lack of permission.
Attn @lildziner and @joshkimux

**Comment by tlei123** [comment]
@mmiddaugh @mpelzsherman , QA cross-device/-browser [test-runs all passed](https://dsvavsp.testrail.io/index.php?/plans/view/1554).  :)

**Comment by mmiddaugh** [comment]
The remainder of this work will be captured in #21976 and #21958
