### ISSUE TITLE
Add new related links to R&S Apps directory page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17311]
## Issue Description
A member of the team who worked on the the third-party apps directory has asked for new related links to be added to the R&S page. He provided links as well as summary text. We need to first confirm if we will add summary text to the other related links on the page or keep all related links as just the linked H1. 

Note: We have the FAQs link as the CTA button so wouldn't also have as a related link.

Link text suggestions:
![image (4).png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/e401abe2-1903-4026-9000-0073454d5d71)

Links to add: 
Profile links to https://va.gov/profile/personal-information
FAQ links to: https://va.gov/resources/connected-apps-faqs

Page to work on: https://www.va.gov/resources/find-apps-you-can-use/

## Tasks
- [x] Determine whether to add summary text to page 
- [x] Add links (and summary text if needed) to apps directory page
- [x] Review and publish
- [x] Alert stakeholder change was made

## Acceptance Criteria
- [x] New related links on live page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
>We need to first confirm if we will add summary text to the other related links on the page

Because we can have a mix of RS articles and non-articles in that related info section, please do not use the summary text. I know this is enabled in the CMS, but for the pages we publish, let's set a consistent model across all RS pages. 

Also - the profile link does not seem to work;  I think it's bc it  is a page you need to be signed in to see, abd we are on public (non-authenticated) pages.  I think we could link people to the profile sign in page https://www.va.gov/?next=/profile/ but we should make the text link clear that it's 'sign in to your VA.gov profile` or the like.  

I would actually recommend making this a second CTA button, instead of a buried text link in the Related section, if they're open to it.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I added the profile link as a second CTA button from Jen's recommendation. Can you let me know if the wording is good? "Sign in or create an account" I used what we have on a few other pages when we link to the profile. If this is good I can publish.

**Comment by bethpottsVADEPO** [comment]
How about "Sign in to access your profile"?

**Comment by RLHecht** [comment]
Thanks! Just made this change and published. Most likely won't be live until tomorrow's deploy but I'll check this afternoon.

**Comment by RLHecht** [comment]
These changes are now live on the site. Closing ticket. @brianalloyd I just pulled it into this sprint.
