### ISSUE TITLE
Fix phone number on About VA disability ratings page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#17312]
## Issue Description
The phone number at the bottom of this page has the wrong area code (should be 800, not 877):
https://www.va.gov/disability/about-disability-ratings/

---
## Tasks
- [x] Fix the area code. Add aria label.

## Acceptance Criteria
- [x] Phone number no longer goes to a sex chat.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
New number live on site. Closing ticket.
