### ISSUE TITLE
[FE] UI Error state Audit

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#17314]
## User Story
- As a Veteran, I want to be notified when my questionnaire fails to be viewable, sendable, can't be populated with data, or a user error occurs. I want to know next steps of how I can proceed and complete my questionnaire.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md

## Description
An audit of error states within the questionnaire and suggestions on any edits that need to be made to said error states. 

Use cases to review/think about:
1. No appointment ID being returned
  - When coming directly to questionnaire
  - When opening a questionnaire from questionnaire list
2. Booking note is missing/can't be returned
  - Think through if anything else needs to happen besides the current behavior: we do not show the "What's the reason for your visit?" question.
3. All the alert boxes that are part of the forms library, which deal with...
  - Authentication
  - In-progress
  - Submitting
4. PDF creation errors
5. Form field validation errors (we only really have one required form field).
6. Time out errors
7. Down time errors. 

## Tasks
> this is a list of design tasks that are needed for this ticket 
- [ ] Receive audit of alert boxes related to errors and form field validation error from Mark Dewey.
     - This audit will include wherein the UI the alert boxes are, steps to see them in the UI, text and level of effort to customization 
- [ ] Review design library for normal error states that they have already taken into account and see if any need to be added/reviewed for our project
- [ ] Review error states and wording
- [ ] Create documentation on the proposed changes.
- [ ] Complete a content review by sending Peggy Gannon a message within the vfs-platform-support channel and tagging her within the comments section of this story
- [ ] %Add any additional Tasks%

## Acceptance Criteria
> when is the ticket done 
- [ ] UI review meeting with product/team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Published mockup link exists and it is added/updated within the appropriate front-end engineering story
- [ ] Feedback from content is incorporated into the mockup

**Comment by mdewey** [comment]
Copied from #15125

**Comment by mdewey** [comment]
Set meeting with PM and Design Team for Monday. 

Findings are here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/error-flows/README.md#L13
