### ISSUE TITLE
VAMC Arch Diagram

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17324]
## Issue Description 
We need to document our architecture for the VAMC product

## Tasks 
Document the following 

- [ ] Points of contact for the system and dependent VA backends
- [ ] Links to dashboards that help identify and debug application issues Links to technical diagrams (to be checked into GitHub alongside your product documentation), including:
- [ ] An architecture diagram, showing involved systems and how they connect.
- [ ] For non-trivial flows (i.e. more than a single round-trip call from frontend → vets-api → VA Backend), a sequence diagram showing the ordered flow of data and operations between systems.
- [ ] Description of any new publicly-exposed endpoints (vets-api or otherwise):
- [ ] Description of new interactions with dependent VA backends
- [ ] Consider arch diagram from front end (Mapbox/GA)
