### ISSUE TITLE
Modifies Sentry logging for SSOe related errors.

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17348]
## Issue Description
Discovery during the Sentry Hackathon. There was an issue with Sentry appropriately tagging/ignoring the right exceptions.  This will require updates to the `keepAliveSSO.js` & `platform/monitoring/sentry.js` files to ensure stack traces are attached.

[Github Issue](https://github.com/department-of-veterans-affairs/vets-website/pull/15310)

---
## Tasks
- [x] Modifies `keepAliveSSO.js` file to update to `captureMessage` method to `captureException`
- [x] Modifies `monitoring/sentry.js` to enable `attachStackTrace`

## Acceptance Criteria
- [x] Sentry filters out unneeded log events that are of type `info` (The network connection was lost, etc.)
- [x] Sentry still logs `error` and `warning` severity levels
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
[Pull request - 15310](https://github.com/department-of-veterans-affairs/vets-website/pull/15310) closes this issue.
