### ISSUE TITLE
Infrastructure Recommit - Container Orchestration for hosting/deploying services and applications (Q1 2021) 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17349]
## Problem Statement 
*In order to evolve the infrastructure-as-a-service offering on the VSP, and sunset the legacy infrastructure services that the platform is outgrowing, we are moving to container orchestration using infrastructure-as-code, immutable deployments, and ephemeral containers that can be built on-demand. *

*How might we improve developer experience, and enable more self-service pathways for product development teams, while also improving scalability and future for potential growth?*

## Hypothesis or Bet
*Our hypothesis is that by evolving VSP's infrastructure as a service, we can provide better support for existing development and engineering teams, and reduce friction for onboarding new projects to the platform.*
*Our hypothesis is that infrastructure can become and abstraction that development teams do not need to be build and maintain, allowing them to focus on the business logic that is core to their application or service, making it easier for them to iterate more rapidly, thus driving additional value for Veterans.*

## We will know we're done when... ("Definition of Done")
*Development and engineering teams will be able to build and deploy services by customizing boilerplate configuration files within their own project/repo, and push their applications through to various environments with minimal intervention from the VSP operations team.*

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
* By the end of Q1 2021, we expect that container orchestration and supporting tools will be production-ready for the onboarding of new VFS projects. During this time, we will also migrate a handful of existing services, with a move to sunset our previous Build/Release/Deploy (BRD) infrastructure services during the Q2 2021. *

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by drorva** [comment]
Let's talk when you start working on implementing this.
I want to make sure we're clear around VFS teams on the platform, BE teams using RAR, for instance, vs teams using other architectures, like CMS and PHP.

**Comment by jhouse-solvd** [comment]
Although this is still technically possible, it will need to be scoped relative to the work that's being done around Vets-API and Frontend autonomous deployments for VFS teams. The solution may not be to offer "container orchestration on EKS" directly. It may instead be something akin to a deployment pipeline that can be triggered through a console UI. Moving this to "Future Initiatives" and will follow up with links to other relevant initiatives once those become clear.

**Comment by mchelen-gov** [comment]
@jhouse-solvd What is the status of this Initiative?

**Comment by jhouse-solvd** [comment]
@mchelen-gov - Hey Mike. This initiative never began. The Platform would need to evaluate if there is a need or use case for VFS teams to deploy applications to EKS, outside of the frontend website or Vets-API. Happy to discuss more!

**Comment by mchelen-gov** [comment]
Does this duplicate https://github.com/department-of-veterans-affairs/va.gov-team/issues/46779 ?

**Comment by jhouse-solvd** [comment]
> Does this duplicate #46779 ?

Possibly. #17349 (this issue) was created to consider providing VFS teams the ability to deploy apps using the platform's app hosting and deployment solution. Will that be covered as part of #46779?
