### ISSUE TITLE
Direct Deposit for EDU: Remove "Add" State

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#17345]
## Background

Despite being told by eBenefits that people who receive paper checks *can* go online to add direct deposit info for edu benefits, the BGS team can not find an actual endpoint that allows for this. Since we can't figure out how to do this in the code, and since the eBenefits team can't provide us with screenshots to actually prove that eBenefits allows for this, we have to remove the "add" state from our proposed functionality for direct deposit for edu on VA.gov.

**Note**: There is a chance that someone later will figure out how "add" functionality works (this happened when we were working on functionality for C&P benefits), and if that's the case, we can always add it back in if someone can prove the backend supports this.

## Tasks

- [ ] Update mockups to remove "add" state.
- [ ] Link updated screens here so Samara can update the frontend documentation.

## Acceptance Criteria
- [ ] Mockups have been updated
- [ ] Updated mockups have been shared with Samara

**Comment by sporeboy** [comment]
I've pulled the "Add Account" screens from the flow of the XD mockups. I still have the layouts, they're just "invisible" for now.

https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/

**Comment by Samara-Strauss** [comment]
Thanks for this! Can you still include the screens that show what it looks like if you have direct deposit for comp & pen but NOT edu, and what it looks like if you have direct deposit for edu but NOT comp & pen? We still need those states, just not the "add" state.

**Comment by Samara-Strauss** [comment]
Oh, wait, NVM — saw they are still in there. We're good!
