### ISSUE TITLE
Continuous Delivery (CD) - Implement New Deployment Workflow 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17354]
## Problem Statement 
Deploying applications and services on the VSP infrastructure is a difficult and cumbersome process. Deployment jobs are confusing, pipelines are hard to configure, and there is a heavy reliance on the VSP Operations team to release software. 

How might we implement a resilient deployment pipeline for services and applications running on the platform?

## Hypothesis or Bet
Our hypothesis is that by improving the software deployment workflow, we can make it easier to deploy services and applications on the platform. 

## We will know we're done when... ("Definition of Done")
- [x] VSP operations will be able to build and deploy services by customizing boilerplate configuration files within a project/repo that they have access
- [x] VSP Operations will be able to automatically deploy and update services and applications in various environments with minimal manual steps/configuration

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
End of Q1 2021

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: [Continuous Delivery (CD) using ArgoCD](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593891/Continuous+Delivery+CD+using+ArgoCD)
* **README**: [Platform Tools](https://vfs.atlassian.net/wiki/spaces/OT/pages/1801682995/Platform+Tools) (WIP)
* **User Guide**: [Getting Started - Argo CD](https://argoproj.github.io › argo-cd › getting_started)
* **Access this tool**: [ArgoCD on VSP](https://argocd.vfs.va.gov/) (need SOCKS)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
The first iteration of this has been online for some time. What was left was tying up a few pieces of documentation and linking them to this initiative. 

**Please see child tasks for links to add'l resources** for using Continuous Delivery pipeline tools on the platform. 

**Note**: Not every workflow may be "off-the-shelf", but the tooling and framework are in use and can be extended to accommodate add'l use cases.
