### ISSUE TITLE
Routine System Jobs - Discovery For New Jobs Solution

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17357]
## Problem Statement 
The current solution for running routine system-related jobs is difficult to use, has a steep learning curve, is confusing, and lacks a good story for high availability.

How might we provide a better solution for running jobs for routine system-related activities that support platform operations? 

## Hypothesis or Bet
Our hypothesis is that providing a better solution for running routine system jobs will make it easier for teams to have control over the jobs that they need to run. 
Our hypothesis is that we can provide a new solution for running routine system jobs that will make jobs more reliable and enable high availability for running routine system jobs on the platform. 

## We will know we're done when... ("Definition of Done")
- [x] We will have a decision in place on which tool to use for Routine System Jobs - [ADR005](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d0590431e9b119b9f17bd58cda508a92153e555f/docs/adr/0005-use-github-actions-for-vsp-platform-ci.md)
- [x] [Guidance for GitHub Actions Usage](https://vfs.atlassian.net/wiki/spaces/VI/pages/1147142190/Guidance+for+Github+Actions+usage)
- [x] [Self-hosted runners documentation](https://vfs.atlassian.net/wiki/spaces/VI/pages/1397194827/Self-Hosted+Runners) 

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
Middle of Q1 2021

### ... documented?

- [X] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
There are several potential solutions for this. Our next step is to consult with FE Tools and BE Tools teams to discuss their needs around this solution, and ensure that we pick something that meets several of the most common use cases / scenarios. 

We should also audit jenkins jobs such as cron jobs that are not related to deploy. We should be able to come up with a simple spreadsheet or other form and evaluate based on what we find.

**Comment by jhouse-solvd** [comment]
Jesse to solidify and share artifacts / readout from the results of this initiative. Will work on this during Sprint 51.

**Comment by jhouse-solvd** [comment]
Will be discussing this with Andrea Hewitt on 5/12/21 to get her recommendations for how to close out this initiative properly.

**Comment by jhouse-solvd** [comment]
Met w/ Andrea Hewitt, reviewed checklist and documentation. Closing.
