### ISSUE TITLE
Testing Tools Team VFS Research

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#17352]
## Problem Statement 
The newly created testing team does not yet fully understand its metrics for success, the needs of its customers, nor does it have any defined processes to help us effectively provide for the needs of its customers or the platform.

How might we begin to learn what we need to learn to be able to set the most effective direction for our team and its work?

## Hypothesis or Bet
By creating a plan that focuses on researching metrics and measurements around our work (and relevant OKRs) we will understand where we are starting, and where we need to go. By conducting research with VFS teams and VFS leadership, we can also gain a better understanding of the gaps in our current offerings, and the needs of those VFS teams.

## We will know we're done when... ("Definition of Done")
- [x] We will have a clear/thorough understanding of metrics related to the ‘Adoption Rate’ OKR (O4-KR4)
- [x] We will understand the needs of VFS teams for automated testing support
- [x] We will understand what metrics are available/attainable
- [x] We will have identified the Testing related processes that need to be formalized/documented
## Known Blockers/Dependencies 
*None at this time*

## Projected Launch Date
Q1 2021

### Is this service / tool / feature...
Discovery
### ... documented?
- [ ] Research plan, goals, and approaches are defined and documented
- [ ] Results are analyzed, made available, and decisions on next swing are made/documented in collaboration with DEPO lead
   - [ ] Additional Zenhub initiative/epics tickets are created as needed based on the findings
   - [ ] Additional documentation, product outlines, release plans are created as needed

New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_
### Measurement
* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
