### ISSUE TITLE
[VAMC] Create .csv file referencing VISN,SYSTEM and data in VAMC-SYSTEM page for use in migration [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17371]
## Issue Description
_As a Veteran, I need to have access to COVID-19 Vaccine information on all appropriate VAMCs, so I can best determine where and how to get the support I need as a Veteran.
---
## Tasks
- [x] _Provide .csv file with the following information. 
* VISN
* Plain language Name
* URL
* Page intro
* Meta title
* Meta description
* GovDelivery
* Social media
Include information for the following VISNs:
- [x] VISN-7
- [x] VISN-8
- [x] VISN-9
- [x] VISN-10
- [x] VISN-12
- [x] VISN-15
- [x] VISN-17
- [x] VISN-20
- [x] VISN-22

## Acceptance Criteria
- [x] .csv has been created and separated by ; and ' for organization.
- [x] report any enomolies in the data when delivered
