### ISSUE TITLE
Add chapter 36 flipper widget to dependents page and update Chapter 36 page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17388]
## Issue Description
In support of the Chapter 36 work, we need to do the following:

1. - [x]  Add a react widget to the [dependents](https://www.va.gov/careers-employment/dependent-benefits/) page like we did for the main [Chapter 36](https://www.va.gov/careers-employment/education-and-career-counseling/) page.

**Widget code to add**: chapter-36-cta

This replaces the H2 "How do I apply?" along with the subway map, CTA button and note underneath the button. 

2. - [x] We need to take out the H3 "Follow these steps to apply online for Chapter 36 services" above the subway map on the main Chapter 36 page as this will now be in the widget.

## Tasks
- [x] Remove copy described above and add widget to dependents page 
- [x] Remove H3 from Chapter 36 page 
- [x] Review and publish pages 
- [x] Alert eBenefits team pages have been published

## Acceptance Criteria
- [x] React widget and changes are live on the site

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These changes to these pages have both been published. Moving to validate and will close once live. FYSA @brianalloyd @bethpottsVADEPO @jason-gcio

**Comment by RLHecht** [comment]
This work has been completed. Closing ticket.
