### ISSUE TITLE
Alerting - Iterate to ensure all alerts are actionable

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17385]
## Problem Statement 
Keeping an eye on critical infrastructure services and application performance is difficult without relevant, actionable alerts. Responses to mission-critical technical issues, outages, and failures are more difficult without an effective alerting strategy and supporting tools. 

How might we provide actionable alerts for infrastructure services, which allows support personnel to better respond to mission-critical issues with infrastructure components and services? 
How might we empower support personnel with alerting that allows them effectively and efficiently support the platform? 
How might we avoid unnecessary disruptions to support personnel with alerts that they are unable to act upon? 

## Hypothesis or Bet
We hypothesize that by ensuring that all alerts are relevant and actionable, VSP Operations personnel can provide better support for the platform and better experience while supporting infrastructure and applications.
We hypothesize that with a better response to issues affecting platform health, we can provide a higher quality experience for VFS teams and veterans themselves.
We hypothesize that this iteration may help provide additional justification for a future monitoring iteration towards developing an internal services status page. 

## We will know we're done when... ("Definition of Done")
- [x] We will inventory existing alerts
- [x] We have comfortably reduced the number of in-actionable alerts that currently exist (low-hanging fruit) 
- [X] [Procedure in place to create tickets for alerts that cannot be actioned](https://vfs.atlassian.net/wiki/spaces/VI/pages/1438875838/Respond+to+Alerts+that+are+not+actionable)

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
End of Q1 2021

### ... documented?

- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline, WIP:](https://docs.google.com/document/d/1xft-33oqsQZFyRp5mYQRSCxtFe62bT1__6RzqigqLv4/edit) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/) WIP
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_

### Documentation
* **`PRODUCT_NAME`**: Alerting
* **Product Outline**: [Alerting using Prometheus and PagerDuty](https://vfs.atlassian.net/l/c/hBiZ2t6i)
* **README**: We will be developing alerting guidance after the re-org of PagerDuty.
* **User Guide**: We will be creating this later in the year after the re-org of PagerDuty

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
As a first step, we need to perform an audit of existing alerts and determine if they contain enough information to be actionable as well as determine whether or not they are routing to the correct team(s) that can perform an action. 

Audit should include, at minimum: 
- service / metric
- expected response
- threshold 
- point of contact
- notification channels

Relevant thoughts / background information: 

quote from @dginther: 
"Alerts on third party services over which we have no control only serves to contribute to alert fatigue. We are trying to implement a policy in which alerts that are inactionable, that is, it serves only to notify when a third party is having an issue, but there is nothing that we can do to try to fix or resolve the issue, are no longer used or created" 

quote from @drorva :
"All kind of scripts are going to start to fail and we'll get notification about them. These notifications, won't necessarily be real time oncall notifications. 

Examples:
Google Analytics import into bigquery
SLO report from datadot into bigquery
and there'll be others as we start using bigquery more and more.

Here's the paragraph for the VA:
At VSP we have an on-call team that monitors critical infrastructure that we control that affects veteran facing services on va.gov.
We do not directly monitor the underlying infrastructure, such as bigquery, from our cloud providers: AWS, AZURE, GCP because these have very high uptime, the providers have their own monitoring systems and nothing we would do would shorten their downtime."

**Comment by jhouse-solvd** [comment]
Here's what we will do when there are alerts that we cannot action: (documented procedures) 

if on-call and you receive an alert that is in-actionable, 
or, it's unclear what action you should take
then, create a ticket using the ops issue template, and provide the following: 

screenshot of the alert
time/date of the alert
channel through which alert was received 
why it couldn't be actioned 
what do you think would improve this alert? 

We're creating something in confluence / github with additional detail

**Comment by jhouse-solvd** [comment]
Will be discussing this with Andrea Hewitt on 5/12/21 to get her recommendations for how to close out this initiative properly.

**Comment by jhouse-solvd** [comment]
Additional documentation is attached. This is now complete. Closing.
