### ISSUE TITLE
Centralized Logging - Log all of the things in STAGING (using Loki)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17389]
## Problem Statement 
Current logging solutions on the VSP are overly complex and insufficient for current needs. Because of the complexity and difficulty of accessing logs, development teams rely heavily on the VSP Operations team, rather than being able to self serve. It is challenging to leverage existing log data to understand how applications and infrastructure is running so that they can take steps to improve the application software on their own. 

How might we improve developer experience on the platform with reliable access to highly-accurate log data?
How might we provide powerful tools for searching and analyzing logs through a centralized interface?
How might we streamline developer operations and systems engineering with easy-to-use, web-based tools and data visualization? 

## Hypothesis or Bet
Our hypothesis is that by implementing centralized logging, we can enhance observability for infrastructure services and applications running in the staging environment, empowering developers to better troubleshoot, debug, and analyze how their software is running on the platform.

## We will know we're done when... ("Definition of Done")
- [x] Centralized logging solution to be ready for VFS/Platform development teams to access application/service logs in STAGING _(with the exception of AWS-maintained services like RDS, ALB, etc which we will approach in a coming phase)_

## Known Blockers/Dependencies 
- [X] Working CI Solution (now GitHub Actions)
- [X] Working CD Solution (now ArgoCD)
- [X] EKS cluster in Staging

## Projected Launch Date
May 3, 2021

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/logging) exists for this product/feature tool
    - [x] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [x] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [x] ... and should be linked from the VFS-facing README for your product
    - [x] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it

- [x] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### Documentation
* **`PRODUCT_NAME`**: Centralized Logging
* **Product Outline**: [Centralized Logging - Log Collection, Aggregation, Search, Query, & Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/818d278fb0b9d96b31f2ebef13a14f0fdadf5795/products/platform/centralized-logging/centralized-logging-product-outline.md)
* **README**: [Logging](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/logging#readme) (will be moving to Centralized Logging)
* **User Guide**: [Centralized Logging with Loki - User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/818d278fb0b9d96b31f2ebef13a14f0fdadf5795/platform/logging/centralized-logging-user-guide.md)

### Testing

* **Usability test**: Skipping - using mostly out of the box solution 
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: [Centralized Logging - Log Collection, Aggregation, Search, Query, & Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/818d278fb0b9d96b31f2ebef13a14f0fdadf5795/products/platform/centralized-logging/centralized-logging-product-outline.md)
* **Release plan**: See product outline, above

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
This solution is live in STAGING with all appropriate documentation. We are now working towards deploying and launching the solution in production. Please see [HERE](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17615) for more information

Closing.
