### ISSUE TITLE
Staging Review [C & L | Translations | Spanish | Corona FAQs 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17392]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] Staging Review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- Link to product outline ([template]
(https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11599 

- Link to [release plan]
(https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live) 
https://app.zenhub.com/files/133843125/a2bf0d4d-cbf3-4299-a02a-5e1eee152a09/download

- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
- Link to your product test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/1156) & [cases](https://dsvavsp.testrail.io/index.php?/suites/view/183&group_by=cases:section_id&group_order=asc) in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
https://dsvavsp.testrail.io/index.php?/plans/view/1156
- Link to your Coverage for References [n/a; only accordions were tested for this content-translation] and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/182) reports in TestRail _for QA practice area review_
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17965#issuecomment-759140397
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
https://dsvavsp.testrail.io/index.php?/plans/view/1156 
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/accessibility-checklist.md
- List of known issues (with links to tickets when applicable)

## Meeting attendees from **requesting team**
- Product Manager (required): **name** @SKasimow 
- DEPO product lead (required): **name** @DanielleThierryUSDSVA 
- Anyone else from your team who significantly contributed to the artifacts provided (required): **names** @youngfreezyVA 
- Other specialists: **names** Others??  @tlei123 @mnorthuis @1Copenut @bmcgrady-ep 

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 4 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
Requesting slot for ~~Jan 15th at 2pm et.~~  **Jan 18 @3.30pm et**

- _If no available time slots work for your team, write your availability and requirements here and shira will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - can you review the above template required to request staging collaboration checkpoint and lmk if I missed anything that would be applicable to this effort?

**Comment by tlei123** [comment]
@pjhill , QA test-runs now completed.  QA-artifact links updated above in main description.

NOTE: No Coverage for References report was generated, as no Use Cases were needed for non-product-specific React-widgets.  Only the accordions were tested.

cc @SKasimow @shiragoodman

**Comment by peggygannon** [comment]
@SKasimow Hello, can you include a staging or preview link where we can view these pages?

**Comment by SKasimow** [comment]
@peggygannon Hi - here's the link to the page:  https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/

**Comment by joshkimux** [comment]
@SKasimow I've started up an accessibility review and have attached it to this ticket!

**Comment by peggygannon** [comment]
@SKasimow I have no content feedback for this staging review. thanks!

**Comment by SKasimow** [comment]
@joshkimux Thank you Josh!

**Comment by SKasimow** [comment]
@peggygannon thanks Peggy!

**Comment by mnorthuis** [comment]
@SKasimow This work was originally for 3 pages to be translated into spanish, I just see a link for 1 of those pages.  Should we be reviewing all 3 or are you planning to handle the other 2 pages separately?

**Comment by joshkimux** [comment]
@SKasimow I have the same question as @mnorthuis ! If there are extra pages, I will need more time to review them. Otherwise, this is ready for @1Copenut !

**Comment by SKasimow** [comment]
@mnorthuis @joshkimux Hi - we had a delay in getting the other pages translated so decided to move ahead with just the Corona FAQ page for now. Dates for other pages are still TBD.

Because the node is in Drupal and there isn't a staging environment, we "soft-launched" the page **without** the link/toggle to the English page in order to complete testing & staging review while limiting the number of users who may find the page. Once we complete staging review on 1/19 and don't have any blockers, we will  add the link/toggle in.

Sharon

cc: @DanielleThierryUSDSVA @youngfreezyVA

**Comment by pjhill** [comment]
VSP QA has no detailed quality assurance practice area feedback. You did a great job with the cross-platform testing of the accordions!

**Comment by allison0034** [comment]
There is no design feedback. Thank you!

**Comment by SKasimow** [comment]
Closing as completed.
