### ISSUE TITLE
Create 4 new education articles in drupal

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#17407]
## Issue Description
We're adding 4 new education articles to R&S. We need to create these pages in drupal:
**Can I get a replacement Certificate of Eligibility?** (I'll revisit this H1 before publishing once we hear back from SMEs about how this is referred to: Education COE / GI Bill Certificate of Eligibility / etc. --it will be good to distinguish this from the home loan COE)
**How VA education payments affect your taxes**
**How do I get college credits for my military experiences?**
**What if my school closes because of a hurricane or natural disaster?**

---
## Tasks
- [ ] Create drupal articles for the 4 articles are in this spreadsheet. (Selina)
[https://app.zenhub.com/files/133843125/25d8c352-64ac-4685-a230-f570f12f459c/download](https://app.zenhub.com/files/133843125/25d8c352-64ac-4685-a230-f570f12f459c/download)
- [ ] Create 2 new tickets for the next tasks: Incorporate feedback from stakeholders (Beth) / Copyedit and publish (Randi)

## Acceptance Criteria
- [ ] 4 new edu articles created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@bethpottsVADEPO @RLHecht these pages a ready for review in Drupal. For all of the articles, in the VA benefits section, I replaced health care (or disability) link with Education and training. Here are some other notes and node links.

- Can I get a replacement Certificate of Eligibility?: http://preview-prod.vfs.va.gov/preview?nodeId=14971 (changed CTA button to link to about GI Bill benefits, wanted to link to check GI Bill benefits but requires user authentication first)
- How VA education payments affect your taxes: http://preview-prod.vfs.va.gov/preview?nodeId=14963 (Used the learning center detail page template instead of multiple QA template)
- Get college credits for your military experience (changed title from How do I get college credits for my military experience? in Word doc): http://preview-prod.vfs.va.gov/preview?nodeId=14964 (Used the learning center detail page template instead of single QA template because copy exceeded character limit by 209 characters. Reworked some of the copy to add an intro text (per the template) and reworked title)
- What if my school closes because of a hurricane or natural disaster?: http://preview-prod.vfs.va.gov/preview?nodeId=14968

**Comment by bethpottsVADEPO** [comment]
@lunascoop Thank you for the adjustments you made to use other templates when needed and for the new CTA. I'll take a look at the pages, then we should have feedback from the SMEs in the next couple days. I'm hoping to publish these Thursday or Friday.
