### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Bay Pines MC [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17408]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Bay Pines healthcare system Legacy Site](https://www.baypines.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] C.W. Bill Young Department of Veterans Affairs Medical Center
- [x] Lee County VA Clinic
- [x] Sarasota VA Clinic
- [x] St. Petersburg VA Clinic
- [x] Palm Harbor VA Clinic
- [x] Bradenton VA Clinic
- [x] Port Charlotte VA Clinic
- [x] Naples VA Clinic
- [x] Sebring VA Clinic

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* C.W. Bill Young Department of Veterans Affairs Medical Center
* Lee County VA Clinic
* Sarasota VA Clinic
* St. Petersburg VA Clinic
* Palm Harbor VA Clinic
* Bradenton VA Clinic
* Port Charlotte VA Clinic
* Naples VA Clinic
* Sebring VA Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [x] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [x] _Archived in Github and/or SharePoint for review by Product Lead and PAOs

**Comment by ltrombley** [comment]
Task Complete: Create new Health Services content "LIST & PLAYBOOK" for VA Bay Pines MC [BA]#17408
