### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Miami MC [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17418]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Miami healthcare system Legacy Site](https://www.miami.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Bruce W. Carter VA Medical Center
- [x] William "Bill" Kling VA Outpatient Clinic
- [x] Miami Flagler VA Clinic
- [x] Key West VA Clinic
- [x] Homestead VA Clinic
- [x] Pembroke Pines VA Clinic
- [x] Key Largo VA Clinic
- [x] Hollywood VA Clinic
- [x] Deerfield Beach VA Clinic

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Bruce W. Carter VA Medical Center
* William "Bill" Kling VA Outpatient Clinic
* Miami Flagler VA Clinic
* Key West VA Clinic
* Homestead VA Clinic
* Pembroke Pines VA Clinic
* Key Largo VA Clinic
* Hollywood VA Clinic
* Deerfield Beach VA Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [x] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs

**Comment by ltrombley** [comment]
Task #17418 -  Create new Health Services content "LIST & PLAYBOOK" for VA Miami MC - Complete and moved to Validate
