### ISSUE TITLE
Validate user submitted QuestionnaireResponse data.

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#17413]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** my QuestionnaireResponse data validated upon form submission

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- Due to FHIR only allowing 1M data to be submitted to the database we need to provide errors if the user submits more than can be saved.
- Provide the ability for the Health Quest module to validate the QuestionnaireResponse data submitted by the user before creating the QuestionnaireResponse resource in the PGD.
- Example, we don't want the user to copy and paste a very large text from the frontend and crash our systems.
- Example, we don't want the user to bypass the UI and submit an empty questionnaire response to the backend.
- Example, we don't want the user to submit content that could potentially compromise our systems.

## Tasks
- [ ] Create a validation for checking empty responses.
- [ ] Create a validation for checking the size of the responses.
- [ ] Create a validation for sanitizing the user input.
- [ ] Write tests to cover all validations

## Acceptance Criteria
- [ ] Submitting a completely empty QuestionnaireResponse from the UI must not create an associated QuestionnaireResponse resource in the PGD.
- [ ] Questionnaire answers must not be bigger than 1MB in size. If any answer is bigger, validation should fail and a QuestionnaireResponse resource must not be created in the PGD.
- [ ] If the QuestionnaireResponse validation fails for any reason, an appropriate JSON response must be sent to the FE by the API explaining the reasons for the failure.
- [ ] Frontend sign off required.

**Comment by abuckley3385** [comment]
@kristenmcconnell @mdewey  determine error message to be shown to the veteran.  Currently there are no character limits on the form fields in the UI.
