### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Caribbean HCS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17417]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Carobbeam healthcare system Legacy Site](https://www.caribbean.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] San Juan VA Medical Center
- [x] Eurípides Rubio Department of Veterans Affairs Outpatient Clinic
- [x] Mayaguez VA Clinic
- [x] Saint Croix VA Clinic
- [x] Saint Thomas VA Clinic
- [x] Arecibo VA Clinic
- [x] Guayama VA Clinic
- [x] Comerio VA Clinic
- [x] Utuado VA Clinic
- [x] Vieques VA Clinic

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* San Juan VA Medical Center
* Eurípides Rubio Department of Veterans Affairs Outpatient Clinic
* Mayaguez VA Clinic
* Saint Croix VA Clinic
* Saint Thomas VA Clinic
* Arecibo VA Clinic
* Guayama VA Clinic
* Comerio VA Clinic
* Utuado VA Clinic
* Vieques VA Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs

**Comment by ltrombley** [comment]
Task #17417 - Create new Health Services content "LIST & PLAYBOOK" for VA Caribbean HCS is Complete and moved to Validate.
