### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Orlando HCS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17424]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Orlando healthcare system Legacy Site](https://www.Orlando.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Orlando VA Medical Center
- [x] Viera VA Clinic
- [x] William V. Chappell, Jr. Veterans' Outpatient Clinic
- [x] Kissimmee VA Clinic
- [x] Deltona VA Clinic
- [x] Tavares VA Clinic
- [x] Clermont VA Clinic
- [x] Lake Baldwin VA Clinic
- [x] Crossroads VA Clinic

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Orlando VA Medical Center
* Viera VA Clinic
* William V. Chappell, Jr. Veterans' Outpatient Clinic
* Kissimmee VA Clinic
* Deltona VA Clinic
* Tavares VA Clinic
* Clermont VA Clinic
* Lake Baldwin VA Clinic
* Crossroads VA Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs

**Comment by bcastoe** [comment]
Task is complete for Create new Health Services content "LIST & PLAYBOOK" for VA Orlando HCS [BA]#17424 and moved to validate
