### ISSUE TITLE
View Payments - Change `vagovprod` From False to True

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#17423]
## Description
In order to conduct UAT for the View Payments, it needs to be in production.

## Tasks: Monday Morning (December 21, 2020)
- [x] Update the entry in `registry.json` needs to have the `vagovprod` flag updated from `false` to `true`. 
- [x] Turn on e2e tests, if needed
- [ ] Request on off-cycle deploy (only if needed)
- [ ] Log in to Flipper and update the toggle

## Acceptance Criteria
- [ ] The View Payments application is in prod
