### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA Tampa HCS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17425]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Tampa healthcare system Legacy Site](https://www.tampa.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [ ] South Hillsborough Outpatient Clinic
- [ ] James A. Haley Veterans' Hospital
- [ ] Tampa VA Domiciliary
- [ ] New Port Richey VA Clinic
- [ ] Lakeland VA Clinic
- [ ] Brooksville VA Clinic
- [ ] Zephyrhills VA Clinic
- [ ] Lecanto VA Clinic
- [ ] Hidden River VA Clinic

## Definition of Done 
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* South Hillsborough Outpatient Clinic
* James A. Haley Veterans' Hospital
* Tampa VA Domiciliary
* New Port Richey VA Clinic
* Lakeland VA Clinic
* Brooksville VA Clinic
* Zephyrhills VA Clinic
* Lecanto VA Clinic
* Hidden River VA Clinic
- [ ] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
