### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA North Florida/South Georgia HCS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17422]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[North Florida healthcare system Legacy Site](https://www.northflorida.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Malcom Randall VA Medical Center
- [x] Lake City VA Medical Center
- [x] Jacksonville 1 VA Clinic
- [x] Valdosta VA Clinic
- [x] Ocala VA Clinic
- [x] Saint Augustine VA Clinic
- [x] Sergeant Ernest I. "Boots" Thomas VA Clinic
- [x] The Villages VA Clinic
- [x] St. Marys VA Clinic
- [x] Marianna VA Clinic
- [x] Palatka VA Clinic
- [x] Waycross VA Clinic
- [x] Perry VA Clinic

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Malcom Randall VA Medical Center
* Lake City VA Medical Center
* Jacksonville 1 VA Clinic
* Valdosta VA Clinic
* Ocala VA Clinic
* Saint Augustine VA Clinic
* Sergeant Ernest I. "Boots" Thomas VA Clinic
* The Villages VA Clinic
* St. Marys VA Clinic
* Marianna VA Clinic
* Palatka VA Clinic
* Waycross VA Clinic
* Perry VA Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs

**Comment by bcastoe** [comment]
Completed and moved to validate new Health Services content "LIST & PLAYBOOK" for VA North Florida/South Georgia HCS [BA]#17422
