### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VA West Palm Beach HCS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17428]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Tampa healthcare system Legacy Site](https://www.tampa.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] West Palm Beach VA Medical Center
- [x] Palm Beach Vet Center
- [x] Jupiter Vet Center
- [x] Fort Pierce VA Clinic
- [x] Delray Beach VA Clinic
- [x] Stuart VA Clinic
- [x] Boca Raton VA Clinic
- [x] Vero Beach VA Clinic
- [x] Okeechobee VA Clinic
- [x] Port Saint Lucie VA Clinic

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* West Palm Beach VA Medical Center
* Palm Beach Vet Center
* Jupiter Vet Center
* Fort Pierce VA Clinic
* Delray Beach VA Clinic
* Stuart VA Clinic
* Boca Raton VA Clinic
* Vero Beach VA Clinic
* Okeechobee VA Clinic
* Port Saint Lucie VA Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [x] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs

**Comment by bcastoe** [comment]
Task #17428 Created new Health Services content "LIST & PLAYBOOK" for VA West Palm Beach HCS completed and moved to validate
