### ISSUE TITLE
FSR - List loop type options

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#17435]
## Issue Description
_We've compiled a list of options that will filter as Veterans type to make adding multiple assets and financial information quicker. We need these lists added to their corresponding list loop input fields outlined [in this Word document](https://github.com/department-of-veterans-affairs/va.gov-team/files/5712157/FSR.type.ahead.lists.docx). The Word document also contains links to the corresponding UXPin pages under each category. [Click here for a visual example](https://preview.uxpin.com/fa323c51a84318fe2c5aec9cf6f125fa4062625b#/pages/134459616/simulate/sitemap?mode=i) of what this will look like in the form._

---
## Tasks
- [ ] _Incorporate the outlined list loop options to their corresponding input fields_
- [ ] _Ensure the options filter as users type_
- [ ] _Allow users to still add custom string inputs_

## Acceptance Criteria
- [ ] _The list loop options have been incorporated into the FSR's UI_
- [ ] _The list loops have been tested to make sure filtering works and users can still add custom inputs_

**Comment by rileyorr** [comment]
@bradl3yC & @craigwheeler I know this ticket isn't in the current sprint, but I just wanted to let ya know that Susan and I finalized the list loop type ahead options and I've removed the issue that was blocking this work!
