### ISSUE TITLE
[PM] Create Database query that will automatically update imported data table with an export that will represent A-Z cross reference to new 95 [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17443]
## Story
As a VAMC web maintainer and analyst, I need to have an easier way to cross reference the old A-Z health services into the new 95 health service, so I can simply importing my excel list to a data base and parsing out a file that I can download the updated cross reference for easy use.

## Goal
Create an import-query-export process to easily cross reference all know A-Z lists and highlight those that do not match.

## TASKS
- [x] Create a DB with the latest versions of A-Z list and associate those to the new 95 list
- [x] Create a query that will take the new lists imported in and parse them automatically with 95 list
- [x] Start the structure of a user interface

## Acceptance criteria
- [x] Tables with old and new associated 
- [x] Working query to parse the data
- [x] Process to show teams how to build their own listing
