### ISSUE TITLE
Test User Accounts User Interviews

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#17446]
## Issue Description
Conduct Discovery Research Sessions 

---
## Tasks
- Recruit for research sessions/Schedule research sessions
- Create conversation guide

## Acceptance Criteria
- Conduct user interviews with members from following teams: 

- [x] VFS team QA specialists

- [x] VFS team accessibility testing specialists

- [x] VFS team PMs

- [x] VSP QA specialists

- [x] VSP accessibility specialists

- [x] VSP collaboration cycle reviewers
