### ISSUE TITLE
Time Zone Adjustment for Dependency claim Submissions [UNPLANNED]

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17452]
## Background
During testing, we found an issue with dates not being converted properly due to a time zone offset in BGS.  This was causing submissions times to move outside certain parameters and not giving an accurate reading to the accepting service.

## Tasks
- [x] Update the date format for the appropriate dates in `vets-api` before sending to `BGS`.
- [x] Update any tests that need to check for this
- [x] Submit a PR for review

## Acceptance Criteria
- [x] Dates are now updating correctly to account for the time zone issue in BGS
- [x] Test are updated to account for the change
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5512
