### ISSUE TITLE
Draft a technical diagram for BigQuery ATO

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17458]
## Issue Description
As part of the BigQuery ATO, the approval team needs some technical information about how BigQuery works, where the info comes from and goes to, and how we know it’s secure.

How might we clearly show this information so that we understand the warehouse architecture and get BigQuery through ATO. 

---
## Tasks
- [ ] Create a technical diagram that shows:
  - [ ] All of the data platforms we will be pulling from
  - [ ] The overarching data types from each of those platforms
  - [ ] How the data will be ETL'd into BigQuery
  - [ ] Where the data will be pushed

## Acceptance Criteria
- [ ] VSP & DEPO has a diagram that can show the data sources and sourcing for ATO approval

**Comment by rroueche** [comment]
Below is an example of the kind of diagram we're looking for, we created that one for our overall VA.gov ATO. We don't need to map the BigQuery system architecture itself if we can just find a diagram / description from them (@joanneesteban were you able to find the interactive diagram they gave you, and could you paste that here?) but we do need to map out the architecture of how we get data into and out of it, and what type of data that is.

![image](https://user-images.githubusercontent.com/8680732/102226970-05ab9400-3eb7-11eb-9ac8-c75313de903c.png)

**Comment by joanneesteban** [comment]
Thanks for the example, Rachael! Unfortunately, the diagram wasn't an overall system architecture, but the [Google Analytics schema](https://storage.googleapis.com/e-nor/visualizations/bigquery/ga360-schema.html).

**Comment by JasonTheBearded** [comment]
@joanneesteban @rroueche here is a link to the tech diagram, https://lucid.app/lucidchart/invitations/accept/ed96ccdd-433a-4e84-9cd6-f510bb148f55. There are some blanks around the different product descriptions so I would greatly appreciate your assistance in filling those in. Thanks and let me know if you need anything else!

**Comment by joanneesteban** [comment]
Thanks, @JasonTheBearded ! I'm not able to edit the chart, but I've added comments for the missing descriptions.

**Comment by rroueche** [comment]
@JasonTheBearded could you please:
- Make the updates per Joanne's and my comments
- Link the central BigQuery Systems Architecture cylindar to Google's documentation: https://lucid.app/users/registerOrLogin/free?showLogin=false&pseudoEditorTitle=BigQuery+Tech+Diagram&instructionParameter=i18nKey%23%3D%3Achart-web-controllers-invitations-document%23%40%3APN%23%3D%3Aname%23%40%3APV%23%3D%3ABigQuery+Tech+Diagram&invitationId=ed96ccdd-433a-4e84-9cd6-f510bb148f55&product=chart
- Export to PDF so I can share w/folks to get feedback and see what other data they need filled in

**Comment by JasonTheBearded** [comment]
@joanneesteban @rroueche I've made the requested changes to the tech diagram. I double checked and you both have edit permissions so I'm not sure why it is not letting you make updates. Let me know if there's anything else!

**Comment by rroueche** [comment]
@JasonTheBearded and @joanneesteban getting some great Qs from Faith to assist this diagram and our ATO:

- Which team will be manage the access of BigQuery? i.e. how to access it, how to get an account, how you approve ppl for access. Is that y'all or is it Operations?

**Comment by joanneesteban** [comment]
Thanks, Jason! It looks like my lack of owning a LucidChart license is preventing me from editing the diagram. 

> Which team will be manage the access of BigQuery? i.e. how to access it, how to get an account, how you approve ppl for access. Is that y'all or is it Operations?

This is the VSP Analytics & Insights team - unless, we _shouldn't_ be managing this access and it _should_ be Operations.

**Comment by rroueche** [comment]
Thanks @joanneesteban! Could you add information about your intake approval process for granting access to BigQuery, into the BigQuery documentation you already started? (This can be a separate issue, and is not urgent. We actually may want an epic for BigQuery ATO, bc there will be little questions like this that come up for your team as we attempt to get all the info over for approval)

**Comment by rroueche** [comment]
Thanks Jason! I'm assigning this issue now to @fowusu2 so she can add a few more technical details to the diagram, and then we can close this issue out. Thanks team!

**Comment by joanneesteban** [comment]
Thanks! Added this to a new [BigQuery ATO epic](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17750) so we can track this work.

**Comment by joanneesteban** [comment]
Hi @fowusu2 @rroueche - is it okay to close out this ticket?

**Comment by joanneesteban** [comment]
@fowusu2 @rroueche checking in again here to see if the Analytics team can close this out.

**Comment by fowusu2** [comment]
Yes this ticket can be closed. Thanks
