### ISSUE TITLE
Add more temp specialty codes for CC provider selection

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17472]
## Issue Description
Add more speciality codes to the current community care provider selection setup for greater chance of returning results.

---
## Tasks
- [ ] Add 207Q00000X (Family Medicine) to Primary Care

- [ ] Add 133V00000X (Dietitian, Registered) to Nutrition

## Acceptance Criteria
- [ ] Behind feature flag

- [ ] Multiple results are returned for a test user account
