### ISSUE TITLE
Update bottom navigation icons

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17475]
# User Story
As the VA mobile app design team, we want to update the icons at the bottom of the app to be more similar in style to each other before we release to the app stores. Right now the stroke weights are different from each other and the sizing looks inconsistent. 

**Screenshot:** 

![Navigaton.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/a894f1eb-d215-412e-98c4-a561140722e6)

# Tasks
- [x] Select icons from an icon library OR design from scratch 
- [x] If using an icon library, figure out how to buy a license to the library
- [x] Design or select **selected** and **unselected** states for icons (8 total) 
- [x] Hand-off icons svgs to front-end
~- [ ] Update Design Library file with new bottom navigation~ (don't worry about this - we should update these icons into the design library, but this ticket can be closed without doing that)

**Comment by bridgethapner** [comment]
@drjecker this update is not at all urgent / not at all priority imo, but before I forget, here is the ticket for the redesign of the bottom nav! I think we'll need to design the icons ourselves because we don't have a subscription to Font Awesome that gives us access to all the icons & styles we'd need.

**Comment by ayushchak** [comment]
Update
- Need a $99 one-time font license from FontAwesome
- If we can't bill, can make our own but may not be cost-efficient.

**Comment by bridgethapner** [comment]
@drjecker Here is the link to the Hub icons that are used on the web that we can replicate in our bottom nav: https://design.va.gov/design/icons#hub-icons.

I think for Profile we can use fa-user-circle..I could see fa-id-card making sense too, but fa-user-circle seems clearer at a small size.

**Comment by drjecker** [comment]
@melissa-lefevre Let's start with these icons as they are already being used in the [VA design system](https://design.va.gov/design/icons#hub-icons). We may decide to pick different ones but it's a good place to start.

Home: https://fontawesome.com/icons/home?style=solid
Claims: https://fontawesome.com/icons/file-alt?style=solid
Health: https://fontawesome.com/icons/medkit?style=solid
Profile: https://fontawesome.com/icons/user-circle?style=solid

**Comment by drjecker** [comment]
Reopening this as @msmanak and I have been discussing tweaking the non-active home icon.
