### ISSUE TITLE
Documentation - Write migration plan for Grafana to EKS

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17485]
## Issue Description
Before we move services from Ansible BRD to EKS, we need to have a high-level migration plan to ensure that we the service migrated properly, with all known dependencies addressed. (note, before taking on this ticket, we will decide on a specific service to write the migration plan for)

---
## Tasks
- [x] Write migration plan for X Service

The migration plan will have the following, at minimum: 

1. List of any infrastructure changes that need to be made
2. List of configuration files or methods that need to be changed
3. List of environment variables that need to be updated 
4. Steps to take to safely transition from BRD service to EKS service
5. Understanding of impact (ie will there be downtime? who should we contact? what's the best time to do it?)
6. Any other pertinent information to ensure smooth transition with minimal impact

(in progress)

Research good basis for deploying grafana: jsonnet helpers or helm chart?

Update vsp-infra-grafana https://github.com/department-of-veterans-affairs/vsp-infra-grafana repo to pattern after a repo with update ci/cd like https://github.com/department-of-veterans-affairs/vsp-infra-aws-load-balancer-controller
- add Dockerfile
- build/deploy code (github actions?)

Get dashboard/datasource configuration from current grafana
- not sure how to do this
- we can login as admin and get json https://github.com/grafana/grizzlyobjects (make a shell script to get all? or using some kind of sdk)
- maybe there is a way to get the data from the filesystem?
- there maybe be an easier way need to do research
- just found grizzly which might be able to pull and push dashboards to grafana https://github.com/grafana/grizzly

Migrate grafana credentials to ssm and figure out how to use them in new grafana eks deployment

Create ability to add those configuration files to new grafana deployment
- there are some cool jsonnet libs that facilitate the creation of dashboards and other grafana config
- not 100% what this looks like

Once a new grafana is running that looks and sounds like the old grafana we should be able to switch over to the new without any downtime.

## Acceptance Criteria
- [x] Migration plan exists in Confluence
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
We will want to have our Argo deployment pipelines solidified before writing these migration plans.

**Comment by jhouse-solvd** [comment]
Taylor, Jeremy, and Matt - We will discuss this and decide on a service to write the plan for and then migrate. Please ping me when you're ready to pick this up.

**Comment by jhouse-solvd** [comment]
One thing to work through is how to export/import grafana dashboards

**Comment by tskinn** [comment]
We've decided to reuse the grafana database so there is no need to export/import dashboards and datasources so that is pretty much done.

**Comment by jbritt1** [comment]
More will come out of our discussion today, but some of the major discussion points that need to be nailed down are:

- Is the utility platform tools cluster here to stay? If so, are we comfortable and content with current configurations?
- Namespace nomenclature
- Oauth app in github change or replace endpoint for existing Route53 record (`grafana.vfs.va.gov`)

**Comment by jbritt1** [comment]
High level migration plan doc added to confluence: https://vfs.atlassian.net/wiki/spaces/VI/pages/1177780240/Grafana+Migration

**Comment by jhouse-solvd** [comment]
This looking good. Moving to review/qa

**Comment by jbritt1** [comment]
Is this ticket just in the scope of Grafana? If so, is it okay to close at this time?
