### ISSUE TITLE
Documentation - How to set up an EKS cluster 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17486]
## Description
We need documentation that can be used by ops team members (et al) to get a new EKS cluster set up in AWS. 

## Background/context/resources
Things we need to know: 
1. aws-auth needs to be disabled AFTER provisioning, or non-ops users will be blocked in tf updates as they won't be able to read the config map. -- this is something that we will want to document as a "need to know" when setting up a cluster 
2. etc
3. etc

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Document the high-level steps for setting up an EKS cluster

## Definition of Done
- [x] Living document for setting up an EKS cluster

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by pnwstevan** [comment]
This is being worked on here:

https://vfs.atlassian.net/wiki/spaces/VI/pages/871202823/Create+and+deploy+a+Kubernetes+EKS+Cluster+in+VSP

**Comment by jhouse-solvd** [comment]
Living document here: 
https://vfs.atlassian.net/wiki/spaces/VI/pages/871202823/Create+and+deploy+a+Kubernetes+EKS+Cluster+in+VSP
Closing
