### ISSUE TITLE
Review and publish new Contact us page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17483]
## Issue Description
Beth created a new Contact us page with important VA phone numbers and other info. This needs to be reviewed and published. 

Before publishing Beth is checking with MIkki about IA. 

Drupal node: http://preview-prod.vfs.va.gov/preview?nodeId=8472

## Tasks
- [x] Review page, check phone numbers and links 
- [x] Publish page

## Acceptance Criteria
- [x] New page is live on site

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This page is now live on the site. Closing ticket. FYSA @brianalloyd
