### ISSUE TITLE
EKS - Ingress controller using Traefik for "platform-tools" cluster in DEV

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17487]
## Description
Creating an AWS LB for each service we want to launch could become very difficult for our EKS clusters. We would be better off using an ingress controller that can route to backend pods/services. Traefik is one that looks like it is full featured and not too difficult to set up. Let's get it working in the dev platform-tools EKS cluster and see if we like it!
 
## Background/context/resources
Helm chart is here, please modify if needed.
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/traefik/dev-platform-tools/traefik

ECR building repo is here:
https://github.com/department-of-veterans-affairs/vsp-infra-traefik

There is an ECR repo but it is not yet in Terraform, it was manually created in the AWS console. We should import it into TF.

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] _Get Ingress working with Traefik_
- [x] _Route existing Argo UI through Traefik_

## Definition of Done
- [x] _Traefik Ingress is up, with ALB pointing to it_
- [x] _argocd-dev.vfs.va.gov routes through the Traefik controlled ingress to the EKS backend_

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Moving to review. Pretty sure this is done.

**Comment by jbritt1** [comment]
Long since been decided to only stand up one Argo deployment/endpoint rather than one per cluster. Argo has been stood up and reachable @ argocd.vfs.va.gov (requires SOCKS) for a while now. Closing.
