### ISSUE TITLE
[Analytics/Content] Provide Path of data collection for Health service, Content improvement on Programs Best Examples [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17492]
## Story
As a Veteran, I need to quickly travel through my journey from finding my health service to my health service program, so I can get to a concise and actionable page and resource as soon as possible.

## Goal
Provide Demonstration of how the VAMC team had improved flow to health service and program and how we have improved the contetn strategy of those pages (best examples).

## Task
Provide examples of before and after for finding a health care service that goes to a program and how that has been improved.
- [x] Legacy Site example of the health service looking for (Bad result)
- [x] Link and missing links to the program page
- [x] Example of original (BAD) program page - To show content update examples
- [ ] Examples of pulling data from all sites/facilities
- [ ] New health services example and points to find this from Facility, System, (Facility Locator)
- [ ] Going to Program page from health Service (Options to find page)
- [ ] Best example of improved Program Page (To show side by side)

## Acceptance Criteria
- [ ] Walk step by step examples for Demonstration to see improvement of Health Care Program journey.
