### ISSUE TITLE
Documentation - Create mapping for Customer Segments <-> Permissions <-> Ops Services

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17491]
## Issue Description
Identify ops supported services for various customer segments and have a matrix of what permissions capabilities enabled in those various tools. 
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
A lot of work has been done in this space. While a specific mapping as such might not exist, there is much more available documentation now available in Confluence. 

If a specific mapping is needed again in the future, we will create a new issue with a clearly defined body of work.
