### ISSUE TITLE
Remove Moment.js Deprecation log

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#17493]
## Issue Description
This bug is a third-party JavaScript library (moment.js) that logs a Deprecation warning to the console when trying to parse a the `sessionExpirationSSO` from Local Storage.
---
## Tasks
- [ ] Modify the setters to the `sessionExpirationSSO` & `sessionExpirationSSOe`

## Acceptance Criteria
- [ ] Ensure the date is being properly formatted to and from moment and Local Storage
- [ ] Ensure login, SSO, and SSOe works as initially intended
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Closing as Moment.js deprecation no longer shows in production
