### ISSUE TITLE
Manage debt FAQ content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17490]
## Issue Description
As part of the debt management content rewrite, we will need an FAQs page on top questions about managing VA debt related to VA benefits. Much of this content is written from the MVP, but we'll need to fit it into the Resources & Support FAQ template. We'll also need answers to some additional questions worked in.

---
## Tasks
- [x] Follow the instructions in the comments in this document to write/edit content: [manage debt faqs_12.15.20](https://app.zenhub.com/files/133843125/8718b700-6b98-446a-be1d-effaaface498/download)

## Acceptance Criteria
- [ ] Revised FAQs doc is ready for Danielle's review
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @3obryandogs. Here's the next ticket for the debt management content work. Please let me know if you have any questions.

**Comment by 3obryandogs** [comment]
@DanielleThierryUSDSVA  - the content is attached. Let me know if you have questions. Thanks!
[8718b700-6b98-446a-be1d-effaaface498.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5705961/8718b700-6b98-446a-be1d-effaaface498.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Closing to open new tickets to reflect current work process.
