### ISSUE TITLE
Atlantis and Applies

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#17495]
## Issue Description
Team should decide on whether we want to turn on Atlantis feature to apply based on pull request comments.
Once decided, Atlantis should be configured as decided.

---
## Tasks
- [x] Team reach a decision on if this is something we feel comfortable with at this time or not.
If we are comfortable with moving foward:
- [x] Decide on _who_ will be able to use this feature
- [ ] Implement the change allowing the functionality in Atlantis configs

## Acceptance Criteria
- [x] Decision made
- [ ] Solution updated to allow the desired functionality with chosen restrictions (as far as who can `atlantis apply`)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
The Operations team feels comfortable with allowing atlantis to apply terraform changes from github PR conversations.

The list of teams that will be allowed to `atlantis apply`:
- vsp devops
- dvp devops
- cms devops

**Comment by jbritt1** [comment]
Atlantis is now migrated and operating on EKS. Adding the functionality to apply via Atlantis is likely still avoidable at this time as we are potentially poised for creating our own Terraform automation via GitHub Actions in the near future. 

Thread ref: https://dsva.slack.com/archives/CTYQL39FE/p1617812464200400

**Comment by jbritt1** [comment]
With the holdoff on applies, planning for future implementation of our own automation to replace this service, etc. can this be closed at this time? CC @jhouse-solvd
