### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Asheville health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17503]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-6 Internal Review Folder](https://drive.google.com/drive/folders/1VV3WPyTJRccsay82aL-Roe3VbSUwGEkJ)
[Review template for review](https://drive.google.com/drive/folders/18Oo5eoy4yn0LyTtQ3OLdNgGqN1FUof81)

## Tasks
_Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 637	Charles George Department of Veterans Affairs Medical Center
- [x] 637GA	Franklin VA Clinic
- [x] 637GB	Rutherford County VA Clinic
- [x] 637GC	Hickory VA Clinic

- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [x] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.

**Comment by lealester** [comment]
Cloned - news, events, stories; Operational Status and Franklin Clinic highlighted until to test
