### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Hampton health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17509]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Hampton Workbook](https://drive.google.com/drive/folders/1lzta6IAtN4GYZZvEtknL3kw2S8nVKZup) 

## Tasks
_Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 590	Hampton VA Medical Center
- [x] 590GB	Virginia Beach VA Clinic
- [x] 590GC	Albemarle VA Clinic
- [x] 590GD	Chesapeake VA Clinic

- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
