### ISSUE TITLE
[VAMC] Rebuild and Publish VISN-6 Systems in one Bulk set up and provide URLs for reivew [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17502]
## Resources

[Devshop Demo Site](dev.cms.va.gov)

## Tasks
- [x] Rebuild VISN-6 instance in DEMO within Devshop
- [x] Publish all pages in one bulk publish (Submit and accept action in CMS portion of VISN-6)
- [ ] GO to VISN-6 CMS version and Release Content to complete Publishing
- [ ] Confirm URL is working for VA Asheville health care and all associated sites

## Acceptance Criteria
- [ ] Devshop instance rebuilds successfully
- [ ] Devshop instance publishes successfully
- [ ] URLs can be provided in spreadsheet

**Comment by SgardnerPMP** [comment]
Devshop continues to crash on publication and now release of content for Visn6.  It is uncertain if this is a Devshop issue, or a process failure were it is unable to publish an entire visn in one bulk publish and release.  CMS Support ticket has been created in cms-support channel.
