### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Durham health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17507]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
TBD

## Tasks
_Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 558	Durham VA Medical Center
- [x] 558GA	Greenville VA Clinic
- [x] 558GB	Raleigh VA Clinic
- [x] 558GC	Morehead City VA Clinic
- [x] 558GD	Durham County VA Clinic
- [x] 558GE	Hillandale Road VA Clinic
- [x] 558GF	Wake County VA Clinic
- [x] 558GG	Raleigh III VA Clinic
- [x] 558QA	Brier Creek VA Clinic
- [x] 558GH	Clayton-East Raleigh VA Clinic

- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.

**Comment by EdwardBoehme05** [comment]
Notes included in spreadsheet.

**Comment by EdwardBoehme05** [comment]
The Clayton-East Raleigh VA clinic was on the Durham legacy site, however not under Durham in Drupal. I moved this clinic under Durham in Drupal, and also added it to the story.
