### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Fayetteville Coastal health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17508]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Fayetteville_Coastal workbook](https://drive.google.com/drive/folders/1-ORUm-MtKEtohlBlJXV1Ssc_eWPpR-m1)

## Tasks
_Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [ ] 565	Fayetteville VA Medical Center
- [ ] 565GA	Jacksonville VA Clinic
- [ ] 565GC	Wilmington VA Clinic
- [ ] 565GD	Hamlet VA Clinic
- [ ] 565GE	Robeson County VA Clinic
- [ ] 565GF	Goldsboro VA Clinic
- [ ] 565GG	Lee County VA Clinic
- [ ] 565GH	Brunswick County VA Clinic
- [ ] 565GL	Cumberland County VA Clinic
- [ ] 565QA	Robeson Street VA Clinic
- [ ] 565QD	Raeford Road VA Clinic

- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.

**Comment by lealester** [comment]
broken links in Prod addressed; devshop is down

**Comment by EdwardBoehme05** [comment]
These facilities were in VAST but not on the legacy site nor the story. I found these in Drupal and after verifying facility ID and address, I moved them under Fayetteville Coastal:

Jacksonville 2 VA Clinic
Jacksonville 3 VA Clinic
Jacksonville 4 VA Clinic
Womack VA Clinic
Fayetteville VA Mobile Clinic
Fayetteville 2 VA Mobile Clinic
