### ISSUE TITLE
Create meta-wrapper job to listen for master changes and build/deploy to STAGING 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1750]
Brought over from CMS doc:
- Webhook is already sending all push events to the dev.va.gov/* endpoint
- e.g for () loop this job http://jenkins.vfs.va.gov/job/cms/job/rmw-meta-build-deploy-env/ 
    - use master instead of develop 
    - use STAGING instead of DEV
- Rename job to remove rmw- prefix
- Wait to activate, needs to be a timed/planned merge. ETA Sept 18thish. Discuss with Elijah. 

@tskinn Please clear this guy up as you like.

As CMS moves to a similar branching strategy as vets-website and vets-api we need a job to be triggered on pushes to master that trigger a build and deploys of dev and staging. We need to have the changes ready for when CMS changes their branching strategy.

I think we can create a wrapper job in the 'Testing' folder of Jenkins that is triggered by `va.gov-cms` master branch that does the following:
- [ ] ability to determine which branch triggers dev or staging deploy (there are times when a new feature needs to be tested on a branch other than master. NOTE: this would require change of the wrapper job to be triggered by that testing branch as well)
- [ ] triggers and waits for [cms build](http://jenkins.vfs.va.gov/job/builds/job/cms/)
- [ ] triggers cms deploy of [dev](http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-dev/) and [staging](http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-staging/) and doesn't wait
- [ ] ability to notify slack channel on failure (maybe on success as well?)

**Comment by ricetj** [comment]
@tskinn to update ticket
