### ISSUE TITLE
[FE] Update urls to progress bar. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#17501]
## User Story
> these should be why the veterans cares
As a veteran, 
I should see URLs that match the page titles
So that I know what page I am on. 

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [IA Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-questionaires.md)
- [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f97214d5e01a9b85b431a14)

## Description
Update the URLs of the form internals to have the id and to match the progress bars. As well as update the URLs to have hyphens, not camelcase. 

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [x] Update the form URLs to match the title of the page, ie: demographic should be ` .../answer-questions/veteran-information`
- [x] Update the todo URL to be `to-do`
- [x] ~Update the questionnaire URL to pass the appointment id to each page.~ Can;t be done in the forms library.  
- [x] Create user tests
- [x] Create e2e tests 

## Acceptance Criteria
> when is the ticket done 
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [x] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
merged to master, need to verify in staging.

**Comment by mdewey** [comment]
In staging.

**Comment by kristenmcconnell** [comment]
Looks great. No other comments from me.
