### ISSUE TITLE
Generate and Upload PDF to VBMS when 674 is Submitted 

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#17517]
## Background
We need to update the 686c/674 submission job to generate and upload a PDF to VBMS when a 674 form is submitted.  

## Considerations
- The job will need to determine if a 686 or a 674 is being submitted, and then generate and upload the correct PDF.  

## Tasks
- [x] Check to see whether a 686 or 674 is being submitted.
- [x] Update the current 686 PDF job to account for 674 submissions (or create a new job if needed).
- [x] Generate and upload a PDF to VBMS when the 674 is submitted.

## Acceptance Criteria
- [x] PDF gets generated and uploaded to VBMS
- [x] Write a test for coverage, if needed
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5560
