### ISSUE TITLE
Add commas to staff profiles

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17519]
## Issue Description
In ALL staff profiles on VAMC pages:  if the "suffix" field is populated then a comma is needed after the person's "last name"

## Current display
![image](https://user-images.githubusercontent.com/55411834/102286659-fef04180-3ef5-11eb-89ac-0717779c87c9.png)

---
## Desired display
![image](https://user-images.githubusercontent.com/55411834/102286772-34952a80-3ef6-11eb-8e78-dab8cdf42796.png)

---
## Tasks
- [ ] Add commas between a person's last name and their degree/license. (For example, John Smith M.D. is incorrect. John Smith, M.D. is correct.)

## Acceptance Criteria
- [ ] Commas separate a person's last name and the degree/license in staff profiles
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
@mmiddaugh put a note in to Ed to validate the grammar rule to be sure that this is 100% always the case.

**Comment by jilladams** [comment]
https://www.va.gov/altoona-health-care/staff-profiles/richard-s-magee/
