### ISSUE TITLE
Implement appointments field (content model)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17518]
## Issue Description
The appointment section for facility health services was designed for VHA services. The appointment section needs to become more flexible to accommodate other services taxons. 

<details>
<summary> Currently, the Appointment section contains the following </summary>
**Heading:** Appointments
**Intro text (hardcoded):** Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.

Referral needed? 
- Unknown
- Yes
- No

Walk-ins accepted? 
- Unknown
- Yes
- No

Online scheduling?

- Unknown
- Yes
- No

Phone: 412-360-3818

</details>

### New use cases/considerations
**COVID-19 vaccines**
- Hardcoded intro text does not fit this situation -> no referral needed, Veterans should not call unless they have already been scheduled and need to cancel/reschedule

`If a referral is required, you’ll need to contact your primary care provider first.` should be connected to "Referral needed? -> yes" (unknown?)

Decision:  New field:` field_health_service_appt_leadin plain text field` will be added to the content type. The existing text will be treated as default draft content which content editors can override to accommodate other needs (ie: COVID-19).

---
## Tasks
- [ ] Replace hard coded text with dynamic text in new` field_health_service_appt_leadin plain text field` in VAMC front end.

## Acceptance Criteria
- [ ] Text appearing in the `field_health_service_appt_leadin plain text` field in CMS appears on front end
- [ ] If `field_health_service_appt_leadin plain text` field is null, the Appointments heading will still display, regardless of other content
- [ ] This change will be seen only in Staging until environment flag is removed (after Transformer issue)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Duplicate to https://github.com/department-of-veterans-affairs/va.gov-team/issues/17917
