### ISSUE TITLE
AE: Sprint 37

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17526]
## Priorities
1. Outstanding tickets from Sprint 36
2. Convert MyVA mobile wireframes to desktop
3. Complete Direct Deposit for Edu IA Review
4. Resolve address error logging issue
5. Profile 2.0 hardening/enhancements

### Profile
**FE**
- [ ] Create helper functions for custom logic in EditViews and render ContactInformationView directly #16215
- [x] Make a platform-level function to disable FTUX modals for Cypress tests #16507 
- [x] Show address validation screen if suggested `stateCode` does not match input `stateCode` #17703

*FE analytics issues*
- [x] Stop recording _all_ contact info save failures as `address-save-failure` #17556
- [x] [FE] [BUG] When an address save fails we don't stop poling the endpoint #17209
- [ ] Stop recording address validation errors in Sentry when we no longer need it #17315
- [x] Is there any reason the VA.gov Profile might treat some address updates as _creations_ #17625
- [x] Record more info to Sentry when users encounter a 301 error from VA Profile #17572

Stretch goal (unlikely we will get to this)

- [ ] [FE] Provide specific alert when VA profile updates fail due to MVI errors #17210

### My VA redesign
**Design**
- [ ] [Design] My VA: Convert mobile wireframes to desktop layout #17307 (stretch goal)

### Direct deposit for edu
**Design**
For Jim Adams:
- [x] Implement Design Changes #16694
- [x] Remove "add" state for direct deposit for edu from mockups #17345
- [x] IA Request [Authenticated Experience, Direct Deposit] #17816

**FE**
- [x] [FE] Build redux actions/reducers for getting edu DD info #16685
- [x] Make educationDirectDeposit feature flag to gate new work #16793
- [ ] [FE] Direct deposit for edu build #16479

### Preferred medical facility
**BE**
- [ ] Backend build #16107 (PR up for review, on hold while Lihan is out)

### VA Notification preferences
 **PM**
- [x] [PM] Create Product Outline for VA Notification Preferences #17528

**Comment by Samara-Strauss** [comment]
Is this ready to be closed yet?

**Comment by mshea0606** [comment]
@Samara-Strauss Yes, closing it now.
