### ISSUE TITLE
Conduct vaccination taxonomy research sessions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17522]
## Issue Description
Conduct moderated vaccination research sessions 

## Goals of research
Learn the Veteran mental models for immunization within the health service taxonomy, primarily for VAMCs

Where in the VHA taxonomy do Veterans expect vaccination services to be found?
What words do Veterans use when searching for vaccination-related services?
Is the mental model different change based on the type of vaccination?

## Tasks
 - [ ] Conduct vaccination research sessions
 
Acceptance Criteria
- [ ] Session notes available

 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
