### ISSUE TITLE
Bootstrap new command line app with TTY

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#17527]
## Issue Description
As a team, we've decided to use [TTY toolkit](https://github.com/piotrmurach/tty#28-working-with-subcommands) for the CLI tooklit. TTY has a bootstrapping feature to get started with the new command line application. Bootstrapping the app creates the project file structure and various commands/subcommands can then be created. A branch for the work was created [here](https://github.com/department-of-veterans-affairs/vsp-toolkit/tree/start-afresh-with-tty)

---
## Tasks
- [x] Create new command line application
- [x] Create subcommand to add new module (use vets-api module generator)
- [x] Readme is up to date
- [x] include help descriptions
- [x] git tag master before merging new work

**Comment by LindseySaari** [comment]
Notes from 12/16 sync:

- To make the CLI portable across apps of various types, we looked into creating a binary executable, but the documentation was misleading https://github.com/piotrmurach/tty#212---ext-flag
- Ran into an issue with commands/subcommds when trying to add subcommands to an existing command (this is not possible)
- Next step - publish to ruby gems and install as `gem install vtk`

**Comment by LindseySaari** [comment]
Tagged the current master branch with the tag of [oclif](https://github.com/department-of-veterans-affairs/vsp-toolkit/tags)
