### ISSUE TITLE
Hyphenation in breadcrumb

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17521]
## Issue Description
The issues causing hyphenation in events names was resolved in[#15880](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15880) but the hyphen in the main breadcrumb (Outreach and-events) looks to be text coming from CMS. 

URL: (example) https://www.va.gov/outreach-and-events/events/vets-for-vets-celebration-at-the-star-theatre/
Expected breadcrumb: Home > Outreach and events > Outreach events > Veterans Film Festival
Existing breadcrumb: Outreach **and-events**> Events > Vets for-vets-celebration-at-the-star-theatre

---
## Tasks
- [ ] Address content in CMS 

## Acceptance Criteria
- [ ] Outreach and events breadcrumb in Outreach hub does not contain hyphen

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
FYI @brianalloyd

**Comment by RLHecht** [comment]
@brianalloyd Sitewide Content doesn't work on Outreach and Events pages. I did a quick look at this page in the CMS and I don't see where the breadcrumbs are to fix this hyphen so you may need to ask the CMS team for guidance.

**Comment by brianalloyd** [comment]
Thanks @RLHecht appreciate the review from a Sitewide Content standpoint.  We'll reach out to CMS for additional triage.

**Comment by brianalloyd** [comment]
@kevwalsh can review this ticket, might need some assistance from CMS to diagnose.  CC @kelsonic @johnhashva

**Comment by kevwalsh** [comment]
I think to this “right” will require a non-trivial iteration on the existing Alert block product in Drupal. We have that stubbed in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3380 but it’s not in our Q3 priorities.

There may be a smaller, custom solution where FE homepage query just hardcodes a specific alert entity ID, and the Published status of that block determines whether or not it appears. @kelsonic   does that make sense? Because of the critical nature of this content, we have to think carefully through this type of approach, and what could go wrong in the CMS.

**Comment by Rleahy22** [comment]
`replace` needs to be `replaceAll` here: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/page.js#L174
