### ISSUE TITLE
CC Provider Selection - can't load providers alert

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17524]
## Issue Description
When a technical issue causes list of providers not to load, provide messaging to user.

---
## Tasks
- [ ] Update [current](https://user-images.githubusercontent.com/8315447/101203702-19463780-3639-11eb-9064-683656909878.png) version of the error

- [ ] Ensure instances of error are captured in analytics (similar to our other errors)

## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag

- [ ] If can't load providers due to technical error, display alert

- [ ] "Find your health facility’s phone number" links to Facility Locator and opens in a new tab

- [ ] DESIGN - All desktop, tablet, and mobile design match the specs: **_TBD_**

- [ ] CONTENT - All copy matches content guidance:

> We can’t load provider information
> We’re sorry. Something went wrong on our end. To request this appointment, you can:
> - Call your VA or community care facility. Find your health facility’s phone number, or
> - Continue your request without choosing a provider. We’ll contact you about a provider.

![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/53e0364a-2be2-42d1-ae72-2054e7860430)
