### ISSUE TITLE
Draft guidance on Platform Collaboration Point Tracker

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#17533]
## Problem Statement
The [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=82123904) is intended to be the source of truth for both VSP and VFS teams as to what collaboration points in the Collaboration Cycle are required, as well as what collaboration points have occurred. The spreadsheet includes links to collaboration point github tickets, and recordings of the collaboration cycle meetings.

It has been the responsibility of the VFS team PM to keep the Platform Collaboration Point Tracker up to date, however it has been difficult to monitor and it is not strictly enforced. The tracker is unreliable as a source of truth because:
- VFS PMs remove collaboration points at their will.
- VFS PMs are not reliable in adding their products, zh tickets, and/or launch date to the tracker.

VFS PMs have also reported that they do not refer to the tracker as their source of truth and 9/10 PMs reported that they keep track of the Collaboration Cyce via other means: [Slack poll](https://dsva.slack.com/archives/CE4304QPK/p1607719092020800).

## Solution
VSP would like to make the Platform Collaboration Point Tracker view-only for VFS teams. It will be the responsibility of VSP collaboration point reviewers to keep the tracker up to date and correct. 

## Tasks

- [x] Reach out to VSP collaboration cycle reviewers and get their buy in
- [ ] Assign a collaboration cycle review point to a VSP team member
   - [x] Project Kickoff - Shira Goodman
   - [x] Design Intent - Allison Christman
   - [x] Usability Testing Prep - Shira Goodman
   - [ ] Research Plan Review - Lauren Alexanderson
   - [x] IA Request - Mikki Northuis
   - [x] Analytics Request - Joanne Esteban
   - [x] Contact Center Review - Jason Woodman
   - [x] Staging Review - Shira Goodman
   - [x] Privacy & Security Review - Michael Fleet or Joe Niquette
   - [x] Full Accessibility & 508 Audit - Trevor Pierce or Noah Gelman
   - [ ] Post-launch Check-in - Shira Goodman
- [x] Update Collaboration Cycle github issue templates to include task for VSP reviewer to update tracker
- [x] Change permissions of Platform Collaboration Point Tracker so that it is view-only for VFS teams and editable only by the people mentioned above.
- [ ] Add an Instructions tab to the Platform Collaboration Point Tracker so VSP team members know how to update the tracker

## Acceptance Criteria
- [ ] The Platform Collaboration Point Tracker is a reliable source of truth for the Collaboration Cycle.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
