### ISSUE TITLE
Identify KPIs for Off Site Search

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17535]
## Description
Leverage data from analytics review to define KPIs for enhancing search and discovery features for Off Site Search. i.e. using Google, Bing and others providers.

## Background/Context/Resources
Initial KPI focus areas may be considerd from S+D Overview Deck.  (link to be added)

## Tasks

- [ ] Collect key data metrics that highlight how veterans are using search and looking for information both on VA.gov and on google etc. 
- [ ] Sync with analytics team to identify outliers and possibilities
- [ ] Add additional key metrics to what exists today on S+D Overview Deck
- [ ] Review and select the right set of metrics that we want to track for our KPIS
- [ ] Discuss with team to ensure consensus and alignment

## Definition of Done

- [ ] A set of KPIs have been defined and agreed upon by stakeholders

---
