### ISSUE TITLE
Establish List of top 50 Search Terms

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17532]
## Description

Establish a solid list of top 50 search keywords used on VA.gov Previous search.gov audit highlights two different lists of top keywords and we need to review that list and extract unique search terms to be used to harden canned responses etc.

## Background/Context/Resources

Previous search.gov audit - Link

## Tasks

- [x] Collect Top Search Terms from  search.gov data from 2018 to Current Date
- [x] Review that list and eliminate any duplicate terms etc to establish a list of 50 unique search terms

## Definition of Done

- [x] Have a list of 50 "top search terms" to use as a baseline for investigation and exploration

**Comment by denisecoveyduc** [comment]
Rolling this over into Sprint 38 to align with John and the decision tools as well as formulate strategy to narrow in on top search terms (avoiding duplications and redundancies etc)

**Comment by denisecoveyduc** [comment]
[Top 50 De-Duped Search Terms of 2020 .xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5812376/Top.50.De-Duped.Search.Terms.of.2020.xlsx)
