### ISSUE TITLE
Component Library: Continue building more web components 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#17543]
## Problem Statement 
In order to have a consistent user experience, individual components in applications and content should be identical across the user experience. For example, the user interface of a simple form should not appear or behave differently in different parts of VA.gov. However we currently do not maintain a library of components that is technically agnostic, so teams building in each of the three technical approaches draw from different shared/reusable code bases. If the 3-4 web components we build and pilot are successful, the DST could continue building additional web components.. 

How might we create a technically agnostic approach to our design system and the components and patterns within it that will allow a team to build a new REACT app, new content, or hybrids without recreating components from a specific technical stack or creating more code that is unique to a single component. 

## Hypothesis or Bet
- [ ] VFS teams will be able to build more consistent applications across different technical environments
- [ ]VSP will be able to maintain a single source of truth for multiple technical environments

This work would support

Objective 1: Scale the DEPO Platform to comfortably support 50+ simultaneous VFS builds, leveraging more self-service pathways.
Objective 3: Facilitate VFS and VSP teams meeting or improving DEPO and VA.gov standards for security, consistency, and quality.

## We will know we're done when... ("Definition of Done")
- [ ] More web components are in the component library 
- [ ] Migration scripts are available to teams so they can update to web components
- [ ] Migration from REACT components to Web components

## Known Blockers/Dependencies 
Dependency on the success or results of the web component library pilot in Q1 2021. 

## Projected Launch Date
Q2 or Q3 2021 

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] Conversion of the most used components from REACT to Web Component
- [ ] X Percentage of REACT components have been migrated to web components

- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: va.gov-team/teams/vsp/teams/design-system
* **Product Outline**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/design-system/web-component-pilot.md
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_
