### ISSUE TITLE
Load test Chapter 36 endpoint

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#17549]
## Description
As an engineer, I want to make sure my endpoint is resilient to high loads of traffic, so high numbers of submissions don't result in intermittent failure and degraded performance. 

## Tasks
- [x] Load test chapter 36 endpoint with locust
- [x] Submit pull request

## Acceptance Criteria 
- [x] PR has been submitted on successful load test
