### ISSUE TITLE
Remove Facility Selection v2 flags

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17550]
## Item Description
Facility Selection v2 page is live. Make v2 (flat list) the new standard for non-Cerner sites.

## Tasks

- [x] Remove va_online_scheduling_flat_facility_page flag

- [x] Remove va_online_scheduling_flat_facility_page_sacramento flag

## Acceptance Criteria

- [ ] No changes in experience

- [ ] Cerner sites are still directed to v1 version

**Comment by jenniemc** [comment]
@jbalboni @laurenernest , does this ticket also include removing the feature toggle flags from `features.yml` in  vets-api?

**Comment by jbalboni** [comment]
Yes, but we need to make sure the front end change goes to production before the vets-api change is merged.
