### ISSUE TITLE
[SD] Type Ahead 1.0

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17558]
## Description
Iteration of typeahead POC #8896 targeted for release by end of March 2021

## Background/Context/Resources

- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/typeahead/product-outline.md)
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/typeahead/release%20plan.md)
- [Typeahead POC ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8896)
- [Typeahead POC 2 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21316)
- [Search.gov Suggestions](https://open.gsa.gov/api/searchgov-suggestions/) 

## 1.0 Release Definition
- [x] Release to 100% of Users #19368 
- [x] Enhancement: Ordering suggestions based on character length #19369 
- [x] Styling Improvement: Change suggested characters to be the bolded portion of the suggestion #19370 
- [x] Styling improvement: Align typed search term in the input bar with drop down suggestions (also on #19370)
- [x] Enhancement: Global Blacklisting to improve quality of Typeahead Suggestions #19763

## Collaboration Cycle Events 
- [x] **Collaboration Cycle Kickoff Issue:** [#20512](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20512) 
 - [x] **Staging Review:** *[#20532](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20532) - Scheduled for May 17th 3:30pm EST* 
	 - [x] *Accessibility Feedback*
	    -  [#24778](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24778) (Should) - Headings Nested improperly in search results  - will be addressed in reorganization
	    - [#24779](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24779) (Should)-Screenreader shouldn't be fired upon selecting a suggestion from the list with enter 
	    - [#20721](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20721) (Consider) - Iterating UX Pattern for mobile screen reader use  -- Unable to implement
	    - [#20719](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20719) (Consider) - Mobile Screen Reader Research 
	    - Not working for iOS (Chrome and Safari) - [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20532#issuecomment-842338150) ---> product team could not replicate issue
	 - [x] *IA Feedback*
		 - [None](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20532#issuecomment-841493028) 
	 - [x] *QA Feedback*: 
	   - [#24793](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24793) Clear Suggestions when below threshold --> [#24837]
	   - #20841 (Must) - Update  TestRail search string test case  --> [Completed](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20841#issuecomment-790758610)
	   - #20841  (Should) - Establish Automated Tests  --Complete
	   - #20841  (Consider) - Review Typeahead impact to search input autofocus --Complete
	 - [x] *Design Feedback* 
		 - [#24789](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24789) (Must) - Font Color Change  --> Change implemented on May 17 
	 - [x] *Content Feedback* 
		 - [None](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20532#issuecomment-842385399)
- [x] **Privacy & Security Review**:  [team-sensitive #226](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/226) 
- [x]  **Target Launch Date:** Phased Rollout, 100%  Thursday, May 21, 2021 (see Release Plan for details) 
 - [ ] **Post Launch -  Full Accessibility + 508 Office Audit:** 
    - #27062 
 - [ ] **Post Launch - Check in:** TBD

## Tasks

- [x] Global Blacklisting Typeahead Suggestions #19763
- [x] Ordering suggestions based on character length #19369 
- [x] Styling Improvements to change suggested characters to be the bolded portion of the suggestion #19370 
- [x] Styling improvement to align typed search term in the input bar with drop down suggestions (also on #19370)

## Definition of Done
- [x] Typeahead 1.0 release has been released and is available for users. 
- [ ] All issues have been completed and closed OR documented if deferred to icebox. 
- [ ] All Collab Cycle Touch points have been achieved

---
## Type Ahead Enhancements for future consideration 
- Expand acronym using VA acronym list to improve clarity
- Remove State references from suggestions unless typed directly from user
- Add typeahead to results page refinement search
- Hover over suggestions fill out search input
- Improving Suggestion Quality 
    - a)Enhance Fault Tolerance for spelling mistakes (eg “goverment”)
    - b)Don't allow plural/singular terms in same suggestion set
    - c)Explore ways to improve the algorithm search.gov uses to establish suggestions (decrease weighting of frequently searched for terms, establish a blacklist to remove terms that we don't want to appear)
- Canned Suggestions for top terms #17844

**Comment by denisecoveyduc** [comment]
The transition from [Typeahead POC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8896) to [Typeahead 1.0](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17558) has proven to be more complicated than first envisioned. Search.gov unexpectedly  resolved a bug fix which was preventing suggestions older than 30 days from being purged from the database. This bug reduced the suggestions database from 40,000 terms to 39 terms and essentially made it **appear** that the feature was not working. Before we release typeahead to 100% users we are going to conduct a [second POC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21316) leveraging a [new list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21325) of typeahead suggestions that will be VA specific and hardcoded to the suggestion database. After we analyze the data we will then circle back to launch to 100% of users. We are hopeful this will be sometime in April 2021.
