### ISSUE TITLE
Vaccine communications tool: Message 1

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17553]
## Issue Description
We need a first email for vaccine communications tool. Sending word doc for copy editing via slack.

---
## Tasks
- [x] Copy edit Word doc (Randi)

## Acceptance Criteria
- [x] Vaccine email reviewed and sent to stakeholders
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Will there be another draft of this email or should we close out this ticket?

**Comment by DanielleThierryUSDSVA** [comment]
HI @RLHecht. It's going through leadership reviews now, so we'll have updates for sure. Let's leave open for now. Thank you for checking!
