### ISSUE TITLE
Update Content on FE for CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17557]
## Background
Based on Peggy's list of feedback, we need to ensure that the FE is up to date

## Considerations
- [x] Peggy's ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16690

## Tasks
- [x] Update content changes per Peggy's ticket (seen above)

## Acceptance Criteria
- [x] Content changes have been saved in prototype
