### ISSUE TITLE
Update CH36 Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17555]
## Background
Based on Peggy's list of feedback, we need to ensure that the prototype is up to date

## Considerations
- [ ] Peggy's ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16690

## Tasks
- [ ] Update content changes per Peggy's ticket (seen above)

## Acceptance Criteria
- [x] Content changes have been saved in prototype

**Comment by sporeboy** [comment]
All applicable content changes made to CH 36 prototype here:https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088565
