### ISSUE TITLE
Confirm UUID in Submission to CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17565]
## Background
We want to ensure that the submissions are landing in the Central Mail Portal appropriately, noting a new vendor.

## Tasks
- [x] Submit a test submission for CH36, share UUID
- [x] Discuss with new vendor that the submission is usable and behaving as expected _(meeting set with new vendor at 3:30 pm ET)_
- [x] Confirm that the business has received the application
  - [x] Ask new vendor to advance the status from _received_ to _pending_
- [x] The process is deemed complete by the business (Angel)

## Acceptance Criteria
- [x] Validate steps above are complete

**Comment by jason-gcio** [comment]
Here is a list of statuses that CMP is using to process forms in their systems

Status | Description
-- | --
Pending | This is the initial status and indicates an intention to upload a document through benefits intake. Using the location identified in the response, the user has 15 minutes to upload a payload before the request is marked as expired.
Uploaded | This is the status that is set on the record when the document is uploaded to the S3 bucket on AWS. Once uploaded, a job is kicked off to send the document to central mail for additional processing
Received | Once the document is received by GovCIO, the status is changed to received. From this point forward, central mail processes the file, passing it through the additional statuses 'processing', 'success', 'error' and 'vbms' via a status check job
Processing | This is set on our record when central mail reports the status as either 'In Process' or 'ProcessingSuccess'
Success | This status maps to the 'Success' status returned by central mail.
VBMS | This status maps to the 'VBMSComplete' status returned by central mail.
Error | This status maps to either 'Error' or 'ProcessingError' returned by central mail.

**Comment by jason-gcio** [comment]
Last submission the morning of 12/16 was received and seen as "Pending."  
As of the afternoon the status was assumed as "Processing," 
SSH-ing in to confirm the status as currently set to "Success."

Per the vendor (Jay Ruggerio), from what they can see now: "Packet ID 16931898 is available in DMHS portal," where Packet ID corresponds to the morning submission.

**Comment by jason-gcio** [comment]
SSH confirms: "status\":\"Processing Success\"

**Comment by jason-gcio** [comment]
Waiting to hear from Angel that DMHS is seeing that packet id.
