### ISSUE TITLE
Add Feature Toggle for Updating Dependents on View Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17564]
## Description
As a user, I want to be able manage my dependents without having to fill out a long and laborious form. 

## Considerations

- There's some ambiguity about how to handle the "synchronicity" between the view dependents page and remove someone from award: Do we move them to the `not on award` list? Do we provide messaging to the user saying the request is pending? Basically, how do we manage application status after 686 submission behind the scenes? 
- Build a feature toggle that will allow us to research and investigate this functionality safely without exposing it to production users.
- [proof of concept mocks for dependent removal on view dependents page](https://xd.adobe.com/view/9a75a359-e0e2-4411-b235-60c3dddb4e6e-cf26/screen/b66a902d-cdd1-4ed1-8757-37ffe6306db7)

## Tasks
- [ ] Add a feature toggle to [this file in vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/1bd0c4abc1d20bffb400e910da7a64dbf09ed66b/config/features.yml)
- [ ] Add a feature toggle to the view dependents page

## Definition of done
- [ ] PR into vets-api has been made
- [ ] PR into vets-website has been made
