### ISSUE TITLE
List Loop component updates

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#17569]
## Issue Description
There is a need to update the List Loop to match the functionality outlined in the mocks:
https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134307865/simulate/sitemap?mode=i

---
## Tasks
- [ ] verify money amounts in the table view have $ placeholder
- [ ] add cancel link
- [ ] update the card view to match the mock
- [ ] restrict form submission when missing or incorrect values

Add/edit card actions:
- [ ] For the first entry, there should be a blue ‘save’ button ([example](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410896/simulate/sitemap?mode=i))
- [ ] For subsequent additions, there should be a blue ‘save’ button and a ‘cancel’ link directly to its right ([example](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410289/simulate/sitemap?mode=i))
- [ ] When editing an entry, there should be a blue ‘save’ button, a ‘cancel’ link directly to its right, and a right-aligned ‘remove’ border button ([example](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410685/simulate/sitemap?mode=i))

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
