### ISSUE TITLE
Conduct Testing for Dependency Claims

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17575]
## Background
We need to make sure that the simpler forms are completed based on recent PR changes

## Considerations
- There might be caching issues that we need ot ask about to see if View Dependents needs anything to make sure its updating from the BGS side

## Tasks
- [x] Conduct 2 tests  from staging for Shane to consume:
  - [x] Report divorce
  - [x] Add spouse
- [x] Request feedback from Shane/Linda
- [x] Reserve some bandwidth for further testing 

## Acceptance Criteria
- [x] Tests have been submitted

### Next steps 
- Establish what other code might need to be updated

**Comment by kathleencrawford** [comment]
Testing Results: 
- Report a divorce:
   1. Got error when submitting claim locally - "Claim already established". Need to use a different test user for local testing.
   2. Dependency decision MT (Marriage Terminated) added with effective date 2020-06-01.  Submitted from Staging.
   3. Auto Dependency Processing Reject Reason: No dependents to send to awards.  (The spouse had already been removed from the award for this Vet)
- Claim benefits for a spouse: 
    1. Spouse successfully added.  Submitted from Staging.
- Report the marriage of a child under 18:
   1. Auto Dependency Processing Reject Reason: No dependents to send to awards.  Asked for clarification - according to spreadsheet, should have an eligible child on award.  Response is that 'child_prevly_married_ind' flag needs to be set to 'Y'.  Also, 'family_rlnshp_type_nm' should be set to 'Biological'.
   2.  Exception occurred in RPBS while communicating with external service.  RatingComparisonEJBService.GetDecisionsAtIssue. Please contact Admin;Call to WS RatingComparisonEJBService.decisionsAtIssue failed.
- Report the death of a spouse, child or dependent parent:
   1.  [SPOUSE] Auto Dependency Processing Reject Reason: Rating changes to the Veterans Last Authorized Award have been made.  Please review.  That means either the rating or the award has changed and not been regenerated and authorized.
   2. [PARENT] Auto Dependency Processing Reject Reason: No dependents to send to awards.  Asked for clarification - according to spreadsheet, should have an eligible parent on award.
