### ISSUE TITLE
Hard code all unauthenticated data

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#17576]
## Issue Description
Hard code the following fake veteran info into the unauthenticated experience:
```
Hector Smith
Last 4 of Social Security number: 1234
VA file number: 5678
Date of birth: 01/01/1970
```

---
## Tasks
Mock data should be added to the following:
- [ ] Veteran information
- [ ] Contact information

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
