### ISSUE TITLE
DebtRes FSR Introduction page updates

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#17574]
## Issue Description
Add content to the subway map for the introduction page refer to the mock:
https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701377/simulate/sitemap?mode=i

---
## Tasks
- [ ] Implement desktop unauth view ([link](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701377/simulate/sitemap?mode=i))
- [ ] Implement desktop auth view ([link](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701378/simulate/sitemap?mode=i))

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
