### ISSUE TITLE
Conduct Programming Session with VRE API Team

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17571]
## Background
We are reaching the last mile list of items for the VRE API Team and we need to ensure that all of our changes are being resolved on their end.

## Tasks
- [x] Schedule and conduct a working meeting with Fatjon K.  and anyone else from his team that would be deemed helpful
  - [x] Work with them sand submit locally to see what is coming trough and what further changes need to happen
- [x] Submit a PR that holds the latest changes for the VRE WPI Team to consume our submissions

## Acceptance Criteria 
- [x] A PR has been submitted with the latest code changes

**Comment by digitaldrk** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5554
