### ISSUE TITLE
DebtRes Update installment contracts and other debts

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#17583]
## Issue Description
Updates to the installment contracts and other debts (repayments section) refer to the mock:
https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134307869/simulate/sitemap?mode=i

---
## Tasks
- [ ] add yes/no widgets
- [ ] set required fields
- [ ] styling and formatting to match mock

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
