### ISSUE TITLE
DebtRes FSR Update Spouse information

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#17582]
## Issue Description
Update spouse sections according to mock https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410899/simulate/sitemap?mode=i

---
## Tasks
- [ ] What is your spouse's name’ should have a ? refer to mock ([link](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410902/simulate/sitemap?mode=i))
- [ ] Type of employment should be a standard dropdown with the following options:
```
Part time
Full time
Seasonal
Temporary
```
- [ ] Payroll deduction list loop should be populating a table rather than cards
- [ ] Verify required fields should be marked so
- [ ] Veteran employment details are pre-filling into spouse employment

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
