### ISSUE TITLE
App Hosting and Deployment: Container Orchestration for Ops-managed utilities (specific list of services inside) 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17586]
## Problem Statement 
Due to the design and architecture of the current Ansible BRD System, and due to its mix of older technologies and brittle components, infrastructure and applications are difficult to deploy, maintain, scale, and support. Additionally, the current infrastructure does not allow the Platform operations team to upgrade existing utilities or onboard new utilities to the platform very easily. 

For the future: Additionally, the infrastructure design and implementation do not enable the Platform to onboard new projects to the platform without there being considerable assistance from the Platform Operations team. 

How might we use container orchestration for deploying utilities that are managed by the operations team? 
How might we develop and use the infrastructure solutions that we plan to offer to the developers that are using the platform? 
How might we make it easier for developers to deploy to the platform without needing to manage the underlying infrastructure? 

## Hypothesis or Bet
Our hypothesis is that by implementing container orchestration for all of the utilities that the Platform Operations team manages, we will have the infrastructure and tooling in place that will prepare us to deploy other Platform and VFS projects using the same approach. 

## We will know we're done when... ("Definition of Done")
- [x] These specific utilities that are managed by the Platform Operations team have been migrated to Amazon's Elastic Kubernetes Service (EKS). 
  - [x] Grafana 
  - [x] Loki 
  - [x] Sentry 
  - [x] GIDS
  - [x] Atlantis (Note: we replaced this with a GitHub action) 

## Known Blockers/Dependencies 
- [x] EKS being authorized as FedRamp High

## Projected Launch Date
Beginning of Q3 2021

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by jhouse-solvd** [comment]
This is what we need next: 

- Migrate revproxy to EKS: lift and shift at first ie take the current revproxy (open resty) config and move it into a container and run it in EKS rather than EC2; likely some little gotchas in terms of network routing, but overall can probably happen in a couple of Sprints
  - tasks for observability and alerting 
- Migrate fwdproxy to EKS: lift and shift at first ie take the current fwdproxy (ha proxy) config and move it into a container and run it in EKS rather than EC2; likely some little gotchas in terms of network routing, but overall can probably also happen in a couple of Sprints 
  - tasks for observability and alerting 

--- 
These will be left to do, but will happen in separate initiatives: 
- GIDS running and being consumed in staging, prod
- Vets-API running in EKS 
- Jenkins may not be moved to EKS, as will likely be sunset in the near future 
- Prometheus may not be moved to EKS, as will likely be sunset in the near future

**Comment by jhouse-solvd** [comment]
This initiative can be considered complete once all of the checklist items have been addressed and supporting artifacts and documentation have been linked.

**Comment by jhouse-solvd** [comment]
See previous comment. Moving to review.

**Comment by jhouse-solvd** [comment]
Please see product outline [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

Work is being done this quarter to iterate on the platform's application management solution. See [here](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/38890) for more info. 

This issue can be closed.
