### ISSUE TITLE
IRIS Q&As: Education -- Eligibility

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#17600]
### Issue
For the launch of Resources and support MVP 1.1, content that fall into the "eligibility" category under education & training needs to be developed based on the following:

- https://gibill.custhelp.va.gov/
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)
- Credible external sources as needed

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 

- [x] SC to identify IRIS faqs to migrate (Laura)

- [x] SC to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

- [x] SC to develop draft copy and review against content checklist  (Selina)

- [ ] DEPO to review (Beth)

- [ ] SC to copyedit draft (Randi)

- [ ] DEPO to get SME approval (Beth)

- [ ] SC to build Drupal page(s) (Selina, Randi or Laura)

- [ ] SC to proof Drupal page(s) (Randi)

- [ ] DEPO to approve Drupal page(s) (Beth)

- [ ] SC to publish pages (Randi)

- [ ] DEPO to alert SMEs that pages are live (Beth)

- [ ] SC to update R&S status document (Laura)

### Acceptance Criteria

- [ ] Page live

### Up-to-date content here

Please post most up-to-date content (whether copy deck, Drupal link, or live url) here rather than in comments below.
[RS.Education.Eligibility.QAs (2).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6287087/RS.Education.Eligibility.QAs.2.docx)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 This was just a placeholder ticket, right? I think we can move it to backlog since we won't be assessing IRIS eligibility Q&As as they relate to tier 1 content for a while. Let's touch on this in our sitewide content meeting tomorrow to confirm this approach.

**Comment by lunascoop** [comment]
I had worked on these questions and am posting the draft copy here to pickup whenever.
[RS Education Eligibility QAs.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6065839/RS.Education.Eligibility.QAs.docx)

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
