### ISSUE TITLE
IRIS Q&As: Education -- Debt

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#17605]
## Issue
For the launch of Resources and support MVP 1.1, content that fall into the "debt" category under education & training needs to be developed based on the following:

https://gibill.custhelp.va.gov/
Product guide pages
Credible external sources as needed
Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates currently in Drupal.

Content will meet learning center template requirements.

Content will be tagged per requirements.

## Tasks
- [x] PW to identify IRIS faqs to migrate (Laura)

- [x]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

- [x] PW to develop draft copy (Laura)

- [x] PW to assign tags (Laura)

- [x] DEPO to complete initial review (Beth)

- [x] PW to copyedit draft (Randi)

- [ ] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

## Acceptance Criteria
- [ ] Copy deck ready for 2nd DEPO review and attached to a content review GH ticket.

## Most recent copy deck
Please use the deck attached and replace it when you make edits/comments to ensure that the latest document is always here, at the top of this ticket.
Copy deck version: 07/08/21 Compared against live page https://www.va.gov/resources/va-debt-management/ and noted which questions are covered there. 
[rs-1.1-education-debt-v0.1-12-30-20-LW.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6785386/rs-1.1-education-debt-v0.1-12-30-20-LW.docx)

## Preview links:
http://preview-prod.vfs.va.gov/preview?nodeId=34646
http://preview-prod.vfs.va.gov/preview?nodeId=33833

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- The copy deck attached to the top of this ticket is ready for your first look. Randi has not had a chance to review it yet. LMK if you have questions. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Per your request, I compared Danielle's debt pages to the education debt copy deck. I inserted a comment for each question, indicating whether it's already covered or if we should make it an article. See deck at top of this ticket. Thanks!

**Comment by bethpottsVADEPO** [comment]
Thanks for this! Looks like there are a couple single Q&As that are EDU specific, and a couple places where we may want to add info to Danielle's general page. I'll take it from here!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO and @DanielleThierryUSDSVA  -- On the[ VA debt management article](https://www.va.gov/resources/va-debt-management/) that's live, we have a link to the  IRIS inquiry routing tool. I'm assuming this is retiring in October, too? Should we just remove the link? 

![image](https://user-images.githubusercontent.com/53535663/129424728-809a4361-afa8-49cf-9e56-8f1cc4a64259.png)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - 
Beth, you asked me about the mitigating circumstances article. I had grouped those faqs (gibill.custhelp answer IDs 1[564](https://gibill.custhelp.va.gov/app/answers/detail/a_id/1564/kw/what%20is%20mitigating%20circumstances) , [1565](https://gibill.custhelp.va.gov/app/answers/detail/a_id/1565/kw/what%20is%20mitigating%20circumstances), and [403](https://gibill.custhelp.va.gov/app/answers/detail/a_id/403/kw/what%20is%20mitigating%20circumstances) ) with the "Manage benefits" articles. See [GH 17603](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17603)  Copy deck is attached to that ticket.

I could not find the content from the following answer IDs (which SMEs requested that we migrate) in any of the 3 existing debt articles:

[989](https://gibill.custhelp.va.gov/app/answers/detail/a_id/989/kw/989)

[1422](https://gibill.custhelp.va.gov/app/answers/detail/a_id/1422/kw/1422)

[1423](https://gibill.custhelp.va.gov/app/answers/detail/a_id/1423/kw/1423)

[1437](https://gibill.custhelp.va.gov/app/answers/detail/a_id/1437/kw/1437)

[1569](https://gibill.custhelp.va.gov/app/answers/detail/a_id/1569/kw/1569)

**Comment by bethpottsVADEPO** [comment]
Update: Education Service removed 1422 and 1423 from their benefits.va.gov page. So we won't address those FAQs at this time.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - There are 4 faqs highlighted in the attached copy deck. Two of them, I think we should combine into one single Q&A article. The other two would be their own single Q&As, so a total of 3. Let me know if you agree and I'll create them. Thanks
[rs-1.1-education-debt-v3-08-25-21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7048232/rs-1.1-education-debt-v3-08-25-21.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Here's the Multiple faqs article (number 1 in your comment above. Note that I added an intro, etc:
**Multiple FAQS article**
Article:  http://preview-prod.vfs.va.gov/preview?nodeId=34659
1st faq:   http://preview-prod.vfs.va.gov/preview?nodeId=34646
2nd faq;  http://preview-prod.vfs.va.gov/preview?nodeId=34647

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Thanks! Taking a look, and I have a question. Do we know anymore about what this sentence means? It feels like we're saying that the school will pay, but then also saying that it might not, depending on its refund policy:

"The school will pay any money that it owes depending on its refund policy."

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - I think this is clearer and that including a concise example helps:

**Will my school refund money to VA if I drop a class?**

The school will pay any money that it owes depending on its refund policy. If the school's refund is less than the debt on your VA account, you're responsible for the difference.

For example, let's say you drop a class after two weeks and VA already paid the full $1,800 in tuition. If your school's policy is to refund only 80% of the tuition, because it's already 2 weeks into the semester, the school will refund only $1,440. You will owe VA the remaining $360.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I see, yes, that makes more sense. I think originally the example was too involved, but now that it's simplified, it makes sense to include. Thank you! I will update the drupal node.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 OK, here's my reworked and slimmed down single Q&A as I mentioned on our call today: http://preview-prod.vfs.va.gov/preview?nodeId=34646

Let me know if you see anything missing. And please check the tags and categories since I don't usually add those in and I'm not sure I did it right! 

Also, could you repurpose the nodes we're not moving forward with (34659 and 34647) for the housing content you're working on? Just so we don't have to throw those away.

**Comment by bethpottsVADEPO** [comment]
@RLHecht This is mostly an FYI for you. There has been quite a bit of shuffling of article content and I wanted to update you on what to review from this ticket (2 nodes originally holding EDU content will be repurposed for housing content instead!).

So... these pages are out for SME review and when they return, I'll ask you to copyedit them before we put them live (I'll also put them at the top of the ticket for clarity):

http://preview-prod.vfs.va.gov/preview?nodeId=34646
http://preview-prod.vfs.va.gov/preview?nodeId=33833

**Education Service SMEs reviewing:** 
Tammy / Joseph P. (our usual POCs)
Louise Wright / Myriah Moore (the team working on loading IRIS FAQs into knowva... but not the ones associated with this content we worked up)

**Comment by bethpottsVADEPO** [comment]
@RLHecht This article is ready for copyediting and then publishing:
http://preview-prod.vfs.va.gov/preview?nodeId=33833

I'm not sure yet if we'll move forward with this one at all since the rules have changed and now it's the school that's responsible for the debt. http://preview-prod.vfs.va.gov/preview?nodeId=34646. Let's keep this ticket open until I make a call on that.

**Comment by RLHecht** [comment]
I've published node 33833

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Based on the info we recently received from Myriah, let's officially delete this node: http://preview-prod.vfs.va.gov/preview?nodeId=34646. And you can note in the spreadsheet that this question is outdated. Thanks!

**Comment by lwalsh617** [comment]
@RLHecht - Could you delete node: http://preview-prod.vfs.va.gov/preview?nodeId=34646 per Beth's comment ^? My access privileges don't allow me to delete pages. Thank you!

**Comment by RLHecht** [comment]
I deleted this node. Closing ticket as rest of work is complete.
