### ISSUE TITLE
IRIS Q&As: Education -- manage benefits

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#17603]
### Issue
For the launch of Resources and support MVP 1.1, content that fall into the "manage benefits" category under education & training needs to be developed based on the following:

- https://gibill.custhelp.va.gov/
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)
- Credible external sources as needed

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
**Tasks**

- [x] SC to identify IRIS faqs to migrate (Laura)

- [x] SC to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

- [x] SC to develop draft copy and review against content checklist  (Laura)

- [x] DEPO to review (Beth)

- [ ] SC to copyedit draft (Randi)

- [ ] DEPO to get SME approval (Beth)

- [ ] SC to build Drupal page(s) (Selina, Randi or Laura)

- [ ] SC to proof Drupal page(s) (Randi)

- [ ] DEPO to approve Drupal page(s) (Beth)

- [ ] SC to publish pages (Randi)

- [ ] DEPO to alert SMEs that pages are live (Beth)

- [ ] SC to update R&S status document (Laura)

### Acceptance Criteria

- [ ] Page live

### Up-to-date content here

Please post most up-to-date content (whether copy deck, Drupal link, or live url) here rather than in comments below.
[rs-1.1-education-managebeneifts-v1-04-23-21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6366095/rs-1.1-education-managebeneifts-v1-04-23-21.docx)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please copyedit this latest version (I slacked it to Laura and she'll upload to this file). 

Then pass to @lwalsh617 for building the page out in drupal. Thanks to both of you!

**Comment by lwalsh617** [comment]
@RLHecht and @bethpottsVADEPO -- I thought we were having Randi do reviews in Drupal so it's the first time she's seeing the content? I'm going to put it in Drupal now. Randi, if you'd rather review Word doc, it's attached here. Thanks!
[rs-1.1-education-managebenefits-8-16-21-bp.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7003129/rs-1.1-education-managebenefits-8-16-21-bp.docx)

**Comment by RLHecht** [comment]
I read this over in Drupal and made a few changes. Two questions I had that I didn't fix:
1. Is "mitigating circumstances" plain language enough? Or is it being used for SEO value?
2. We have been taking out "on this page" in the other intros when we say "Keep reading..." Should we remove it here too?

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Per Randi's comment ^ I took out "on this page" in the intro.
@RLHecht -- We can leave "mitigating circumstances." 
Thank you both!

**Comment by bethpottsVADEPO** [comment]
Couple updates to note here:

1/ I did end up changing the H1 to a more plain language title for the page. The term "mitigating circumstances" gets some SEO value by being in the H2s on this multiple FAQ. But then we're leading with PL. I was waffling on that, but I do think it's VA jargon that we can try to tone down. Much of the communication for this content is tracked in the debt ticket. 

2/ Randi: in the latest version of the Word doc, I have a comment about changing an H2 in a multiple FAQ that's live called "GI Bill WAVE FAQs": https://www.va.gov/resources/gi-bill-wave-faqs/. I think this ticket is ready to be closed, so I'm putting my comment here instead of it being buried in the Word doc: Would you please change the first H2 from "Should I use the WAVE website to verify my enrollment" to "How do I verify my enrollment?" Ping me if you have questions! I don't think it's currently selected as a "stand-alone" in drupal, so I don't think this is a big deal, but let me know if you think/know otherwise.

@lwalsh617 If you agree that this ticket can be closed and we can track the mitigating circ article in the other debt ticket, go ahead a close this one.

**Comment by RLHecht** [comment]
I updated the H2 you mentioned in the previous comment and published the page.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Leaving it to you to close this ticket if you think we can.

**Comment by lwalsh617** [comment]
@RLHecht - I am closing this ticket.
