### ISSUE TITLE
IRIS Q&As: Education -- Montgomery GI Bill

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#17604]
**Issue**
For the launch of Resources and support MVP 1.1, content that fall into the "Montgomery GI Bill" category under education & training needs to be developed based on the following:

https://gibill.custhelp.va.gov/
Product guide pages
Credible external sources as needed
Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates currently in Drupal.

Content will meet learning center template requirements.

Content will be tagged per requirements.

**Tasks**

- [x]  SC to identify IRIS faqs to migrate (Laura)

- [x]  SC to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

- [x]  SC to develop draft copy (Laura)

- [ ]  SC to assign tags (Laura)

- [x]  DEPO to review (Beth)

- [ ] SC to copyedit draft (Randi)

- [ ] DEPO to get SME approval (Beth)

- [ ] SC to build page (Selina, Randi or Laura)

- [ ] SC to proof Drupal page (Randi)

- [ ] DEPO to approve Drupal page (Beth)

- [ ] SC to publish page (Randi)

**Acceptance Criteria**

- [ ] Page live

**Up-to-date copy deck and Drupal link**
Please use the deck shown here and replace it when you make edits/comments to ensure that the latest document is always here, at the top of this ticket. **Add Drupal and live links here when available**. 
[rs-1.1-education-mntgmrybill-0.1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6285931/rs-1.1-education-mntgmrybill-0.1.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- See copy deck attached to the top of this ticket. Thank you.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- If you haven't already reviewed the Word doc at the top of this ticket, should I go ahead and build this multiple faq article in Drupal for you to review there instead?

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Here's some feedback for you for reworking this article. Then you can pass it to Randi for a copyedit so it's in final form next time I review. 
**Note:** This isn't work for the current sprint. We'll look to prioritize it in our next sprint planning meeting. 

- Reframe the intro so it doesn't start in a negative way.
- Follow our style for bulleted lists so that we don't mix "and" and "or"--we have examples on live pages where we've needed to break those out into 2 chunks.
- Consolidate the "can I get a refund" info into 1 section.
- Follow our style for "Example" text--refer to live pages and match the style
- Change "how do I apply" H2 wording so it doesn't imply that you need to apply.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- I revised this article and Randi edited so it's ready for you to review. http://preview-prod.vfs.va.gov/preview?nodeId=37333
@RLHecht FYI.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 @RLHecht Thank you! I reviewed and added some edits directly into drupal. 
- I also moved up the $600 Buy-Up Q&A higher on the page. 
- For future articles, let's make the last sentence of the intro more specific--you can take a look and see how I framed it. 
- Note that I unbolded "all" per the style guide. Our style is not to emphasize these broader words/phrases, like "more than" or "all" or "only if."
- Remaining work on this for your team: I thought it was a little too complicated the way the example was laid out. Can you find some examples on the site for how to deal with this kind of example that has a multi-step calculation? I made some edits to that Q&A to show that we should have one instance of "Example." The part that still needs some research and framing there is the calculation. Then Randi, you can write up an entry for the style guide that captures several examples on the site for how to approach examples where we need to show the calculation/math to the user. That way each time we need to have an example like this, we don't have to search around the site for precedent. There are likely some examples in the health care and disability hubs, but maybe others too.

**Comment by lwalsh617** [comment]
Hey @bethpottsVADEPO and @RLHecht, 
The "for example" examples I found were like this one on [the disability ratings page](https://www.va.gov/disability/about-disability-ratings/), which I used as a model for this page. (The only difference being that our Q&A template wouldn't let me format the "Steps" as H3s.) Should we rework this disability page and others like it, too? If so, I'll see if I can find the others I saw. 
![image](https://user-images.githubusercontent.com/53535663/144932489-4a13f8fe-4cb7-4720-bc17-b93e8a089cc7.png)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 This steps approach would only makes sense for this article if we could use H2s/H3s. I edited the example--I think we can go with this latest iteration. 

@RLHecht Would you copyedit the content in this one little section with the example again and let me know if you think the conditional works?

**Comment by RLHecht** [comment]
That part looks good to me @bethpottsVADEPO

**Comment by RLHecht** [comment]
Closing this ticket and completing publishing part in ticket #34121.
