### ISSUE TITLE
saml_callback "Could not perform token exchange" error

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#17606]
## Issue Description
Further breakdown of unhandled exceptions in `saml_callback` has uncovered a SAML error `could_not_perform_token_exchange`, probably related to an issue with ISAM.

Original saml_callback code change to pull more detail from unhandled exceptions: https://github.com/department-of-veterans-affairs/vets-api/pull/5425/files

Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/10234/?environment=production&project=3&project=4&query=is%3Aunresolved+message%3A%22StatusDetail%22&statsPeriod=14d

---
## Tasks
- [ ] Further research to determine exact cause of error
- [ ] Error fix (if fixable from va.gov side)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
