### ISSUE TITLE
Direct Scheduling - Best Times to Call Not Needed

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#17616]
## Description
As product/design, I don't want to request best times to call so that a user isn't required to enter unnecessary fields in the form.

---
## Tasks
- [ ] Contact info page

## Acceptance Criteria
- [ ] If appointment is self-schedule/direct schedule, Then do not show "best times to call" field on contact info page

- [ ] If appointment is self-schedule/direct schedule, Then do not require "best times to call" selection to continue form from contact info page
- [ ] If appointment is self-schedule/direct schedule, Then do not show "best times to call"  on review page
- [ ] If appointment is self-schedule/direct schedule, Then do not show "best times to call"  on confirmation page

- [ ] If appointment is a request (not self-schedule/direct schedule), Then show "best times to call" field

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation/screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/direct-schedule-flow.md) are updated

---

**Original Description**

Not really sure if this is a really an issue or not.  Nevertheless I will log anyway.
Direct Scheduling prompts and requires users to enter best time to call.  
This information can not be viewed by schedulers in VistA or anything so not sure why veterans are required to answer best times to call.

Best times to call is really only needed for Appointment Requests and not Direct Scheduling.  

![BestTimesToCall.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/f60e008a-0413-40f7-97f9-1094785d155b)

**Comment by laurenernest** [comment]
The page is working as designed so technically not a bug, but keeping for potential improvements. The background on what's visible in VistA is helpful!
