### ISSUE TITLE
Remove second CTA button from connected apps

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17624]
## Issue Description
Per Bill Wanamaker's request, we need to remove the second CTA button they had asked us to put on the "Find connected apps you can use" page. Their team is still working on UX on the page and won't have updates until January. 

## Tasks
- [x] Remove newly added CTA button from page

## Acceptance Criteria
- [x] Button no longer on page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This work is complete. Moving to validate. FYSA @brianalloyd this was a quick request their team asked us. Just creating the ticket for tracking purposes.

**Comment by RLHecht** [comment]
This change is now live. Closing ticket.
