### ISSUE TITLE
Publish vtk to ruby gems

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#17629]
## Issue Description
The new toolkit changes exist in [this branch](https://github.com/department-of-veterans-affairs/vsp-toolkit/tree/start-afresh-with-tty). Once the changes are merged into master, this can be published as a gem. 

---
## Tasks
- [x] Update gemspec descriptions and URLs
- [x] Publish to rubygems (including permissions for pushing)
- [x] Confirm that installing as `gem install vtk` works properly

**Comment by LindseySaari** [comment]
An [issue](https://github.com/department-of-veterans-affairs/github-user-requests/issues/5684) was created to change the [vtk repo](https://github.com/department-of-veterans-affairs/vtk) to a public repository. We need to get this approval before publishing to rubygems
