### ISSUE TITLE
Monitoring / Alerting- Synthetic monitoring of search functionality on va.gov

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17631]
## Description
The search functionality on va.gov was broken recently in production and resulted in users being redirected to va.gov when submitting a search. We need a simple monitor in place which will check to see that search is working and alert relevant personnel when search is not working as expected. 

## Background/context/resources
The issues was initially brought to support's attention in [this slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1608164661039900?thread_ts=1608164617.039500&cid=CBU0KDSB1)
Post-mortem for the incident: 
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/search-postmortem-12-16-2020.md

## Technical notes
The solution approach here is to use synthetic monitoring within AWS. 

---
## Tasks
- [x] Create new synthetic monitor for checking search functionality on va.gov
- [x] Test monitor in dev to ensure that it is working
- [x] Create corresponding alert that notifies support personnel that search is not working
- [x] Clean up canary naming convention 
- [x] Clean up TF module

## Definition of Done
- [x] New monitor and alert will be in place
- [x] Relevant stakeholders will be notified that this is in place and working (Jesse happy to take this part; see thread under background section above)

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Please see #18297 to create a Terraform module for this synthetic monitor so that it can be automatically re-created in the future.

**Comment by jhouse-solvd** [comment]
Added a dependency, which is not a true blocker, but rather the output of this ticket will inform next steps for #19843

**Comment by jhouse-solvd** [comment]
@omgitsbillryan - can you update with any relevant notes and move to review/qa when ready? or let us know if there is add'l work to be done. thank you, sir

**Comment by mchelen-gov** [comment]
was there a post mortem for this incident?

**Comment by jhouse-solvd** [comment]
@mchelen - [HERE](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/search-postmortem-12-16-2020.md) (also added to Background section above)

**Comment by jhouse-solvd** [comment]
@omgitsbillryan to clean up canary naming convention TF module (also added as task above)

**Comment by jhouse-solvd** [comment]
This has been completed. 

Closing.
