### ISSUE TITLE
Build Life Insurance pages in Drupal and incorporate stakeholder feedback

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17646]
## Issue Description
Life insurance articles for R&S have been reviewed and approved by Beth. They have been sent to stakeholder for feedback. We need to build these in Drupal and incorporate SME feedback once we get it back. 

Copydeck with Beth's edits: [https://app.zenhub.com/files/133843125/e696303c-cb2c-4930-850d-5400dc51891b/download](https://app.zenhub.com/files/133843125/e696303c-cb2c-4930-850d-5400dc51891b/download)

**Articles to review:**
- **Do you think you're owed more money from a TSGLI claim?** (formerly titled: _Should I refile my TSGLI claim if I think I’m entitled to more money?_) Could also be titled: What to do if you think you're owed more money from a TSGLI claim?  http://preview-prod.vfs.va.gov/preview?nodeId=15172 
- Deciding how much life insurance to get: http://preview-prod.vfs.va.gov/preview?nodeId=15060
- Life insurance if you have pre-existing conditions: http://preview-prod.vfs.va.gov/preview?nodeId=15059
- Life insurance dividend payment options: http://preview-prod.vfs.va.gov/preview?nodeId=15062
- Closed life insurance programs: http://preview-prod.vfs.va.gov/preview?nodeId=15063

## Tasks
- [x] Build articles in Drupal (Selina)
- [x] Copyedit articles in Drupal (Randi)
- [x] Put in stakeholder feedback (Selina)
- [x] Review changes (Randi)

## Acceptance Criteria
- [x] Pages built in Drupal with stakeholder feedback

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht These pages are ready for review

- Should I refile my TSGLI claim if I think I’m entitled to more money?: http://preview-prod.vfs.va.gov/preview?nodeId=15061 (Here's the link to the TSGLI contact info @bethpottsVADEPO: https://www.benefits.va.gov/INSURANCE/forms/SGLV-8600_ed2013-06.pdf)
- Deciding how much life insurance to get: http://preview-prod.vfs.va.gov/preview?nodeId=15060
- Life insurance if you have pre-existing conditions: http://preview-prod.vfs.va.gov/preview?nodeId=15059
- Life insurance dividend payment options: http://preview-prod.vfs.va.gov/preview?nodeId=15062
- Closed life insurance programs: http://preview-prod.vfs.va.gov/preview?nodeId=15063

**Comment by RLHecht** [comment]
@lunascoop @bethpottsVADEPO I did a copyedit on these pages. Here are my comments and questions:

**Should I refile my TSGLI claim if I think I’m entitled to more money?**
- Should we add the TSGLI VA.gov page to either the related links or as a second CTA button?
- I think this is already in the works but putting here to keep track of: We need to list the contact info for the branch of service TSGLI offices

**Deciding how much life insurance to get**
- Should we add the life insurance calculator as second CTA button since we mention it right above in the intro?

**Life insurance if you have pre-existing conditions**
- Just an FYI that AP doesn't put a hyphen in preexisting. I changed throughout.
-  We are linking to a life insurance page that hasn't been published yet (node 5678) when we say "Review a list of participating private insurance companies"

**Life insurance dividend payment options**
- Should we define what dividends means somewhere? Either in the intro or under an H2 before we go into the different options?
- How come we have interest rates for 2007? Are there any newer ones?

**Closed life insurance programs**
- Still a TK for average age of policyholders under Veterans' Reopened Insurance

**Comment by bethpottsVADEPO** [comment]
@RLHecht 
These 3 articles are approved by the SME, but need some related link work done (we'll Zoom about this):

Deciding how much life insurance to get. 
@lunascoop Would you make the categories (1, 2, 3, 4) H3s rather than just plain text and in bold?
http://preview-prod.vfs.va.gov/preview?nodeId=15060

Life insurance if you have pre-existing conditions
http://preview-prod.vfs.va.gov/preview?nodeId=15059

Life insurance dividend payment options
http://preview-prod.vfs.va.gov/preview?nodeId=15062

@lunascoop Can you go ahead and create the chart for this page from the contact info you mention above in this ticket?:
http://preview-prod.vfs.va.gov/preview?nodeId=15061 
**Note:** We're still holding on publishing this one until Ruth Berkheimer gets back to us about corrections she said need to be made to the Air Force and Air National Guard contact info. She also mentioned wording changes. So, holding... but we may as well get the chart created. This would take priority over your other projects, if you could please get to it this week. 

@bethpottsVADEPO My job is to work on this page that the SME confirmed would be good to have on the site:
Closed life insurance programs: http://preview-prod.vfs.va.gov/preview?nodeId=15063

**Comment by bethpottsVADEPO** [comment]
@RLHecht Add related links to these 3 pages, linking to each other:

**Deciding how much life insurance to get**
http://preview-prod.vfs.va.gov/preview?nodeId=15060

**Life insurance if you have pre-existing conditions**
http://preview-prod.vfs.va.gov/preview?nodeId=15059
- Also, please add a related link to the Myths & rumors page: https://www.benefits.va.gov/INSURANCE/sgli_myths_rumors.asp
- And add a related link to the SGLI page, jumping to disability extension (same as the jump link under Option 2).

**Life insurance dividend payment options**
http://preview-prod.vfs.va.gov/preview?nodeId=15062

For the page that Selina is adding the chart to: http://preview-prod.vfs.va.gov/preview?nodeId=15061 
@RLHecht would you replace the related link that's there now with a link to this page instead?: https://www.va.gov/life-insurance/manage-your-policy/

**Comment by RLHecht** [comment]
@bethpottsVADEPO I've added the related links to the three nodes. Also:

**Life insurance if you have pre-existing conditions**
http://preview-prod.vfs.va.gov/preview?nodeId=15059
- I fixed the two broken links in option 3. Now they are pointing to a legacy page as well as a PDF on that legacy page. Before they were pointing to pages we haven't published yet, which is why they weren't working. 

**Deciding how much life insurance to get**
http://preview-prod.vfs.va.gov/preview?nodeId=15060
- This also linked to a page we haven't published yet so I put in the legacy page instead for the link "Find out if you can get free financial planning services"

**Comment by lunascoop** [comment]
@RLHecht @bethpottsVADEPO I've completed work on the recent version of the _Should I refile my TSGLI claim if I think I’m entitled to more money?_ article and is ready for review. I did change the article title. My notes are below and I've included a total list of nodes to review in the ticket description.

Article title
**Do you think you're owed more money from a TSGLI claim?** or **What to do if you think you're owed more money from a TSGLI claim?** (Can't decide on title) http://preview-prod.vfs.va.gov/preview?nodeId=15172
I updated the contact info for all service branches based on the most recent info I could fine. The sources are listed below.

- Air Force, Air Force Reserves and Air National Guard: https://www.myairforcebenefits.us.af.mil/Benefit-Library/Federal-Benefits/Traumatic-Servicemembers-Group-Life-Insurance-(TSGLI)
- Army: https://www.hrc.army.mil/content/TSGLI%20Claim%20Instructions
- Coast Guard: https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Human-Resources-C[…]rsonnel-Services-Division-Field-Support/Field-Support-TSGLI/
- Marines: This source is rather old, but seems to somewhat align with the PDF version. https://www.marines.mil/News/Messages/Messages-Display/Article/890264/traumatic-inju[…]otection-under-the-servicemembers-group-life-insurance-tsgli/
- Navy: https://www.public.navy.mil/bupers-npc/support/casualty/Pages/TSGLI.aspx

**Comment by bethpottsVADEPO** [comment]
@lunascoop Thanks! I'll take a look at 15172. Please see my inline comments responding to @RLHecht 's notes above after her copyedit of all the articles. I have a couple requests for you in there. It's her December 22 note. Randi, I'm thinking about defining "dividend."

**Comment by bethpottsVADEPO** [comment]
@mnorthuis We're getting close to finishing these 3 rewritten legacy pages. Now that we have R&S, we'll be putting them in there instead of within tier 1 content. For 2 of them, we link to the equivalent legacy page currently from the LI hub landing page. What's your guidance as far as action to take there? Do we want to point to R&S from hubs? It's new territory. Here are the pages that will launch on R&S:

**Deciding how much life insurance to get:** http://preview-prod.vfs.va.gov/preview?nodeId=15060

**Life insurance if you have pre-existing conditions:** http://preview-prod.vfs.va.gov/preview?nodeId=15059

**Life insurance dividend payment options:** http://preview-prod.vfs.va.gov/preview?nodeId=15062

**Comment by bethpottsVADEPO** [comment]
@RLHecht I just heard back from Lori Hamilton that we should change that 2007 date to 2021. Would you do that please? Thanks!

**Comment by lunascoop** [comment]
@bethpottsVADEPO I've addressed your inline responses from Randi's comment on Dec 22nd. I've also made the change mentioned in another comment:

> Deciding how much life insurance to get.
@lunascoop Would you make the categories (1, 2, 3, 4) H3s rather than just plain text and in bold?
http://preview-prod.vfs.va.gov/preview?nodeId=15060

**Comment by mnorthuis** [comment]
@bethpotts are all 3 of those pages in the "More resources" spoke?  I believe the how much page and dividend options page are, but not sure about the pre-existing page.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis 
**In the more resources spoke on LI hub, we have:**
[How much life insurance do I need?](https://benefits.va.gov/insurance/lifeins101.asp)
and
[Medical conditions that make you uninsurable](https://www.benefits.va.gov/INSURANCE/uninsurable.asp)

**Those will be replaced by these new R&S pages:**
Deciding how much life insurance to get: http://preview-prod.vfs.va.gov/preview?nodeId=15060
and
Life insurance if you have pre-existing conditions: http://preview-prod.vfs.va.gov/preview?nodeId=15059

**I don't believe we link to an equivalent legacy page currently for this new R&S page:**
Life insurance dividend payment options: http://preview-prod.vfs.va.gov/preview?nodeId=15062

**Comment by bethpottsVADEPO** [comment]
@lunascoop Putting the latest contact info from Ruth in LI in our ticket here. I had forwarded her mail to you. But just capturing it here too. Thanks for adding this to the first accordion on http://preview-prod.vfs.va.gov/preview?nodeId=15172:

From: Berkheimer, Ruth VBAPHILINS <ruth.berkheimer@va.gov>
 Sent: Wednesday, February 3, 2021 4:35 AM
 To: Potts, Beth <Beth.Potts@va.gov>
 Subject: RE: content for our new resources and support section that will need your review

This is the contact information for AF Active and AF Reserve & Guard:
  Air Force
(Active Duty)
 Phone: (800) 433-0048
Email: AFPC.DPFCS.Pol_Trng_CaseMgt@us.af.mil
 Submit Claims via email: AFPC.DPFCS.Pol_Trng_CaseMgt@us.af.mil
Submit Claims via postal mail:
AFPC/DPWC
550 C Street West, Suite 14
Randolph AFB, TX 78150-4716


  Air Force Reserve and Air National Guard
 Phone: (800) 525-0102
Email: casualty. casualty.arpc1@us.af.mil
 Submit Claims via fax:
(720) 847-3887
Submit Claims via email:
casualty.arpc1@us.af.mil
Submit Claims via postal mail: HQ, ARPC/DPTTB
18420 E. Silver Creek Ave
BLDG 390 MS 68 Buckley AFB, CO 80011

**Comment by lunascoop** [comment]
@bethpottsVADEPO I've made those changes. @RLHecht you can review.

**Comment by RLHecht** [comment]
This page has been reviewed. I added the full name of TSGLI in the intro. I didn't add "Claims and appeals status" as one of the tags because I wasn't sure if it is only for decision reviews claims or it's also for life insurance. @bethpotts

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop "the Reserves" is correct plural when it's a general reference. But when it's used with the actual official name, it's singular. See this website: https://afreserve.com/how-to-join?gclid=Cj0KCQiApY6BBhCsARIsAOI_GjYPqXOePO5z8h9srk2mkaEZw0slVc37sv92rcB4hQAs1mND-rqE5ucaAhuaEALw_wcB

Can you change the label on the accordion to this?: Air Force Reserve and Air National Guard

Also, let's lowercase "active duty" in the first accordion and get rid of the parentheses, like this: Air Force, active duty

**Comment by lunascoop** [comment]
I made the changes and the page is ready for review. @bethpottsVADEPO @RLHecht

**Comment by bethpottsVADEPO** [comment]
@lunascoop Thanks!

@RLHecht Can you review what Selina did, and then we're still pausing on that page for now.

Second thing for you to copyedit: H2s on our page called Deciding how much life insurance to get
http://preview-prod.vfs.va.gov/preview?nodeId=15060

If all looks good on that one, go ahead and publish.

**Comment by RLHecht** [comment]
Just reviewed and published the page with the changed H2s.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I can't seem to access the SME feedback now from the email string, so I'll just post here for your awareness. We can't use "we" as we usually do when talking from the point of view of VA since it isn't VA in this situation that reviews TSGLI claims. It's the branch of service, which Ruth has indicated we should refer to as "uniformed service"--so that's another change in that paragraph. Anyway, that's the gist. 

Please run through your pre-pub checklist before pressing publish! Let me know if any questions come up--I think there's a tag to add.

**Comment by RLHecht** [comment]
I reviewed this page and set to publish. I added the payments and debts tag and I also added the article to the R&S landing page. Moving this ticket to validate.

**Comment by RLHecht** [comment]
This last page is now published. Closing ticket.
