### ISSUE TITLE
Prototype Content Build for CLP 

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#17648]
## About your app/tool/functionality

For the new Campaign Landing Page, we need to test the initial CMS tooling and authoring experience by building out two internal-only prototype pages using "old" campaign page content.

This process will help us identify bugs and usability issues that will need to be addressed prior to making the page building tool available to VA stakeholders in Q1 2021.

## Who is involved

- Randi Hecht and John Hashimoto will do the builds.

## Desired completion date

- Optimally by Dec. 23, 2020 -- but can stretch into early January if necessary.

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
    
- [X] **Writing support for new app/tool** 
   * **Additional info.** The CMS team has made the CLP AX available for internal content build.

---

### About your team

- Team name: Public Websites
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: Ryan Thurwell
- FE engineer: TBD
- Product/team Slack channel: #vsa-campaign-landing-page

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by RLHecht** [comment]
I started creating a CLP for Flu shots based on this page: https://www.va.gov/communitycare/flushot.asp

It's still a WIP but the node ID is: prod.cms.va.gov/node/15051

**Comment by johnhashva** [comment]
I completed an initial build of a CLP for VA Solid Start (https://benefits.va.gov/transition/solid-start.asp).

The node ID is: prod.cms.va.gov/node/15068

I'm capturing questions/issues in this [shared doc here](https://docs.google.com/document/d/1s1nKP5pNp68SN6_euUeUX2aI5lfSfFNfynd-gFBRdJo/edit?usp=sharing).

**Comment by RLHecht** [comment]
@johnhashva I think now that we've both built our prototypes we can close this ticket out. Just want to confirm.

**Comment by brianalloyd** [comment]
Concur @RLHecht, @johnhashva we can reopen if needed but closing for now based on content add for both builds.  Thanks.
