### ISSUE TITLE
Screenreader map when zooming (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17656]
## Issue Description
Screen readers should read properly when focusing on the map

## Current experience
Screenreader users hear  

> Map
> A B C D E F Zoom In, Zoom Out, https://www.mapbox.com/, Mapbox logo, link Search this area of map, group 

when the `zoom in` button is activated. 

## Expected behavior

When the Veteran activates the Zoom In button, he/she should hear 

> button, Search this area of map

---
## Tasks
- [ ] Following [Discovery for Accessibility plugin](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14872), improve screenreader flow for map. 

## Acceptance Criteria
- [ ] When the Veteran activates the Zoom In button, he/she should hear "button, Search this area of map"

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This issue has been resolved by #17405
