### ISSUE TITLE
Re-deploy VA.gov Database with proper specifications 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17654]
## Description
After performance degradation and outage on va.gov due to the database not being able to handle the load, a new instance was deployed directly from the console. We need to ensure that the database is re-deployed with the proper specification and which matches our typical patterns and best practices for database infrastructure. 

## Background/context/resources
Additional details can be found in [this slack thread](https://dsva.slack.com/archives/CJRQ85PQB/p1608108171419700) regarding the incident.

## Technical notes
_Notes around work that is happening, if applicable (notes about database specification should be added below)_

---
## Tasks
- [x] Communicate with Demian and Operations team to ensure proper specification for the database
- [ ] Modify Terraform modules appropriately given new desired specifications for va.gov database
- [ ] Modify the read replica to upgraded specifications
- [x] Communicate with Team Lead, Product Manager, et al to announce plan to switch over
- [x] Plan a maintenance window for the intended database failover with Team Lead, Product Manager
- [x] Perform database failover to database with new upgraded specification

## Definition of Done
- [ ] Database will be re-deployed during a planned maintenance window _(The goal is minimal impact to users of the website)_
---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@tskinn - there are a couple of tasks and an item under definition of done that I believe are finished, but wanted to check with you and request that you check them off if all is well. 

beyond that, please confirm whether anything else is needed, and then I will close this out for us. thank you, sir!
