### ISSUE TITLE
Please generate Public/Private Key pairs for Clipboard Questionnaire app integration with Lighthouse PGD

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#17668]
## Issue Description

The Clipboard Questionnaire app will make calls into the Lighthouse PGD environment. Authentication is handled by a `JWT Exchange` service endpoint in Lighthouse, which requires a public/private key exchange. We will need three sets of keys for each environment we will connect to: Sandbox, Staging and Production.

This key exchange is identical to the HealthQuest key exchange for their MAP integration, if we want to see an example of how this has been previously implemented.  

---
**> You must generate RSA-2048 or RSA-4096 keypairs to be used in each environment- sandbox, staging, and production. Once that is completed, you must submit all 3 generated public keys and a desired reverse DNS-style issuer ID (e.g. gov.va.system.v1)**

Please store the private keys in credstash.
---

## Tasks
- [ ] Creation of **shared** keys across Dev, Sandbox, and Staging and delivery of the public key to stephen.barrs@va.gov, beau.grantham@va.gov, and draju@governmentcio.com in **JWK** format
- [ ] Please deliver the **shared** private key to draju@governmentcio.com(@dillo), the backend developer on the Health Quest team who will be developing the services which interact with the Lighthouse PGD
- [ ] Creation of Production keys and delivery of public key via encrypted email to stephen.barrs@va.gov in **JWK** format

- Example JWK format
  - `{
         "kty": "RSA",
         "n": "EXAMPLE...",
         "e": "AQAB",
         "alg": "RS256",
         "use": "sig"
       }`

## Acceptance Criteria
- [ ] All public keys have been generated and delivered securely to the relevant contact 

## How to configure this issue
- [ ] **Labeled with Team** ( `operations`)
- [ ] **Labeled with Practice Area** (`backend`)

**Comment by jhouse-solvd** [comment]
@dillo - Thanks for creating the issue for us. Can you give us an idea as to how soon these keys will be needed to support for the Clipboard Questionnaire app in integrating with Lighthouse PGD?

**Comment by dillo** [comment]
> @dillo - Thanks for creating the issue for us. Can you give us an idea as to how soon these keys will be needed to support for the Clipboard Questionnaire app in integrating with Lighthouse PGD?

@jhouse-solvd I'd like the **shared** keys as soon as possible since this will enable development work to continue without being blocked. The production key generation can be done at a future date that's deemed appropriate by both the Health Care and Lighthouse teams.

**Comment by jhouse-solvd** [comment]
@dillo - I am following up with the Ops team today to get some information for you and help set timeline and expectation for next steps. Thank you for your patience!

**Comment by dillo** [comment]
@jhouse-solvd Thank you very much!

**Comment by jhouse-solvd** [comment]
@dillo - Would you be able to generate the keys and send them to us using keybase / onceler? It is generally better for Ops if application teams create the auth keys / tokens that they need. Ops can then ensure that they are properly installed using credstash. 

If so, I can message you a team member's keybase account name. Thank you, sir!

**Comment by dillo** [comment]
@jhouse-solvd Thank you! I can go ahead and generate the keys and send them to a team member if you can provide me their keybase account! Happy Holidays!

**Comment by stephenBarrs** [comment]
@jhouse-solvd are you able to get the keybase account name to @dillo so we can get the private keys into credstash?  Thanks!

**Comment by jhouse-solvd** [comment]
@stephenBarrs - yes, absolutely. (you beat me to it!) I am following up right now to get the best team member for the job and will be sending over the keybase account to @dillo shortly.

**Comment by jhouse-solvd** [comment]
@stephenBarrs - keybase account was sent to @dillo in a direct message, and this ticket is being assigned to @mydesignrocks (Srikanth Valluru) to get the keys installed.

**Comment by mydesignrocks** [comment]
added the keys to credstash and followed through this PR: https://github.com/department-of-veterans-affairs/devops/pull/8339

**Comment by jhouse-solvd** [comment]
@dillo - can you please confirm whether or not you got everything that was needed here? thanks so much in advance.

**Comment by dillo** [comment]
Hi @jhouse-solvd, yes we got everything we needed setup for the environments in question. I'll be creating a new issue in the nearby future to setup up the private/public keys in the production environment. Thank you for all your help!

**Comment by jhouse-solvd** [comment]
Closing per dillo's comment above
