### ISSUE TITLE
Vet Center Mobile prototype

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17667]
## Issue Description
We need to incorporate initial Veteran feedback into a mobile version of the Vet Center prototype for the next round of Veteran testing. 

This prototype will be used to validate 

- mobile design
- initial feedback on taxonomy display/content/organization for a few priority Vet Center services
- presentation of satellite locations using real world examples

---
## Tasks
- [ ] Iterate prototype using findings from Vet Center research and input on locations/services from Outreach Coordinator

## Acceptance Criteria
- [ ] Prototype is available to support research with Vet Center clients and (non-client) Veterans

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
[Link to mobile prototype](https://preview.uxpin.com/cdd25414c3c03534b7a8ee83b89f964219565580#/pages/135469174?mode=cvhidm)
