### ISSUE TITLE
 Feature Definition: Secure Messaging

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17674]
# User Story
As a team member on VA mobile app, I want to define the scope of the Secure Messaging feature for the VA mobile app. 

### Research support
User research in May-October 2020 supports that many users would find it valuable to access Secure Messaging via the mobile app.

> "[The first thing I would add is] Secure Messaging - it's hard to quantify [why this is valuable] because it can be used on phone today [using MHV] - but if you didn't have to log in every time that would be helpful."  [Link to the research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/prototype-testing/testing-summary.md#health-features-are-highly-useful-appointments-secure-messaging-and-rx-refill-are-the-most-useful-health-features).

### What we know about Secure Messaging today
- This is a feature Veterans interact with through MHV

#### Technical
- What endpoints does this feature use?

#### Viewing messages
- How commonly do users use advanced search features to navigate their inbox? Do we need a search or filtering feature for the inbox to meet user needs for mobile?
- Do messages sent from users **and** messages from providers appear in the inbox list together, organized by date, on MHV today? Or is there a separate sent folder?
- Say there are 2+ new messages from a provider in one thread that a user hasn't read yet. How does MHV flag that to the user? Do flags include the number of new replies in the thread?

#### Selecting a recipient
- Is there a maximum number of providers a user can have in their recipients list?
- What’s the average number of recipients a user can have in this list?
- On MHV today, can users add recipients to this list? If not, how do recipients get added? If yes, how common is it that a user needs to add to their recipient list -- does that seem like a mobile feature for now to us?
- Can a user message multiple recipients at once?

#### Compose message
- Is there a character limit on the subject line? 
- Is there a character limit on the message field?

#### General usability
- What major pain points exist with Secure Messaging today?
- Do most messages have a lot of back and forth? Is there a limit in MHV to how many times a chain can go back and forth?

- Can we get a test account that shows some new messages from providers? Would it be possible to have a test account on the user side and provider side that we can set up to talk to each other to see what messaging UI looks like in different states?
- Is it accessible to Veterans who are LOA3 only or also LOA1?

#### Attachments
- How common is it that files are sent using Secure Messaging -- by the user? By the provider?
- Can multiple files be sent in 1 message?
- What are the accepted file types?
- Is there a size limit on files?

#### Folders
- How common is folder usage? We've kind of made the assumption this doesn't need to be part of the feature on mobile, but would like to understand user behaviors around folders / messaging organization and management.

#### Preferences
- Under 'Preferences', users can edit the list of who they can send messages to under 'My Secure Messaging Contact List'. Users can select 'Yes' or 'No' to display a list of recipients on "To" List of Contacts.
     - How do recipients get added to the system?
     - If a Veteran wants to send a message to a provider who isn't showing up in MHV, what do they do?

#### Errors
- What happens if a message fails to send? Why might this occur and what error message does MHV display?

# Tasks
- [ ] UX/product discovery
- [ ] Technical discovery
- [ ] Define the scope of the feature for mobile app
- [ ] Write user stories for design work
- [ ] Write user stories for engineering work

**Comment by bridgethapner** [comment]
#### Logging the things I'd like to do to wrap my head around how SM works today: 
- Log into an MHV test account & see what the UI looks like
- Review vets.gov Secure Messaging work 
- Review user guide

#### Logging questions I have top of mind & want to investigate further there: 
**General**
- What major pain points exist with Secure Messaging today?
- Is there a character limit on the message field?
- Can a user message multiple recipients at once?
- Can we get a test account that shows some new messages from providers? Would it be possible to have a test account on the user side and provider side that we can set up to talk to each other to see what messaging UI looks like in different states?

**Files & Folders**
- How common is it that files are sent using Secure Messaging, either by the user or the provider? I'm curious if Veterans would consider files to be a central VIP part of messaging.
- How common is folder usage? We've kind of made the assumption this doesn't need to be part of the feature on mobile, but would like to understand user behaviors around folders / messaging organization and management. 

**Recipients**
- Under 'Preferences', users can edit the list of who they can send messages to under 'My Secure Messaging Contact List'. Users can select 'Yes' or 'No' to display a set list of recipients on "To" List of Contacts. 
        - How do recipients get added to the system?
        - If a Veteran wants to send a message to a provider who isn't showing up in MHV, what do they do?

**Comment by bridgethapner** [comment]
This has been covered by the Secure Messaging team's work, am closing
