### ISSUE TITLE
FL Search experience, Phase 2: Usability and Accessibility

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17671]
## User Story or Problem Statement
As a Veteran, I want the ability to enable my location each time I search so that I understand how and when my information is being used. 
As a Veteran, I need to be able to quickly clear a field so that I can change my search parameters. 
As the Facilities team, we want the Facility Locator to be easy to use with assistive technology so the search experience is an equitable experience for all Veterans. 

## Product Outline
[Product Brief - WIP]

## Background
The Facility Locator map has historically not been entirely 508 compliant due to obstacles related to the Mapbox version. After a recent version upgrade, we are revisiting the search experience from a mobile-first and accessibility perspective. 

## Issue Description
The issues within the scope of this epic are

### Accessibility
- [SCREENREADER] Announce zoom in/out context change (FL) #17963
- 508-defect-2 Mapbox in keyboard user flow #16971
- Inconsistent/buggy focus for "Search this area" button #17665
- [DISCOVERY] Adopting the form system for Facility Locator #18355
- [SCREENREADER] Facility Locator error messages #18351 (informed by #18355)

### Usability 

- Urgent care mash-up user experience #18521
- Design "Clear input" for FLocator fields #17272
- Front end: Clear input field (FLocator) #16513
- [DESIGN] "use my current location" in Facility Locator #16511
- Implement search level "use my location" #17319
- [RESEARCH] Mobile search expectations (Veteran population) #5761
  - Conduct research: Mobile search expectations (Veteran population) #18687
  - Synthesis: Mobile search expectations (Veteran population) research #18690
- [RESEARCH] Mobile search expectations (assistive tech) #18685
  - Conduct research: Mobile search expectations (assistive tech) #18688
  - Synthesis: Mobile search expectations (assistive tech) #18691

## OKR
Key Result: Decrease defined list of legacy map-related accessibility and usability issues 

## Solution - overview of approach

1. We will resolve list of accessibility issues (as above) and implement the two new usability features ("find my location" and "clear field")
2. Conduct two mobile experience research sessions (1 - general Veteran population and 2- Veterans using assistive tech) for   foundational accessibility knowledge and to inform changes to search experience

## Issues to create within this Epic
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)
- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
  - [ ] Create research plan and conversation guide - #(ticket)
  - [ ] Conduct research - #(ticket)
  - [ ] Research synthesis/read-out - #(ticket)
- [ ]  ~**[Discover] IA Request** - #(ticket)
- [ ] **[Discover] Analytics Request** - #(ticket)
- [ ] **[Build] Contact Center Review** - #(ticket)
- [ ] ~**[Build] Privacy/Security Review** - #(ticket)
- [ ] **[Build] Pre-Staging Review activities**
  - [ ] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=staging-review-accessibility-checklist.md&title=%3CInitiative%3E+x+Staging+Accessibility+Checklist) - #(ticket)
  - [ ] Compile QA test cases - #(ticket)
  - [ ] Release plan - #(ticket)
  - [ ] Submit QA test plan request - #(ticket)
- [ ] **[Build] Staging Review**- #(ticket)
  - [ ] Resolve Staging Review findings - #(tickets)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
  - [ ] Complete accessibility checklist in Prod - #(ticket if necessary)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)
*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by mmiddaugh** [comment]
Closing this epic as complete
