### ISSUE TITLE
Comparison Tool: Conduct Accessibility Audit

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17675]
As a member of the development team, I need to complete an Accessibility/508 audit regularly to ensure our applications are 508 compliant. 

## Assumptions:
1. Tester has access to most common browsers including: Chrome, Safari, IE 11, Firefox (this could be using an external tool like Browserstack or a Virtual Machine)
2. Tester can access mobile simulation and desktop formats

## Acceptance Criteria:
1. The Comparison Tool has been evaluated and run through from beginning to end using the tools referenced in the tasks for each of the following features: 
   a. Landing page
   b. Search results page
   c. IHL profile page
   d. OJT pofile page
   e. VETTEC Search Results
   f. VETTEC profile
2. Any errors or problems have been captured in a defect.

## Tasks:
- [x] Test with Voice Over
- [ ] Test with JAWS
- [ ] Test with NVDA
- [x] Test with Axe
- [x] Test while zoomed in to 400%

## Supporting Artifacts
1. The Accessibility and 508 compliance process is documented in GitHub: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/ead0fe129bfee6b8e7eaae59d7f4f681a37dec15/Practice%20Areas/Accessibility/Readme.md
2. For support on executing the feature flow using keyboard strokes only, see the WebAIM keyboard accessibility guide for keyboard strokes. - zoom browser to 400% and verify that the layout is still meaningful and the feature is still usable (see WCAG guide for understanding reflow)
3. How to access Safari Voice Over: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Work%20Practices/Accessibility%20and%20508/Mac_VoiceOver_guide.md

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1123&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
No issues found
