### ISSUE TITLE
10203: Cross-Browser Audit

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17686]
As a member of the development team, I need to conduct cross browser testing to ensure that our products work as expected in all browsers. 

## Assumptions:
1. Tester has access to most common browsers including: Chrome, Safari, IE 11, Firefox. This could be using an external tool like Browserstack or a Virtual Machine
2. Tester can access mobile simulation and desktop formats
3. End to End test script exists here: [INSERT LINKS]

## Acceptance Criteria:
1. The 22-10203 has been tested and run through from beginning to end.
  a. Testing will be completed as an authenticated user and as an unauthenticated user. 
2. Any errors or problems have been captured in as defects in GitHub. 

## Tasks
- [x] Test form end to end on Chrome
- [x] Test form end to end on Firefox
- [x] Test form end to end on Safari
- [x] Test form end to end on IE 11
- [x] Test form end to end on Edge
- [x] Test form end to end on Mobile
- [x] Test form using google's responsive features.

## Supporting artifacts
1. Requirements for cross browser testing are located in GitHub: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/testing/cross-browser-manual-testing.md

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/587&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
Testing complete. No issues found
