### ISSUE TITLE
0993: Cross-Browser Audit

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17689]
As a member of the development team, I need to conduct cross browser testing to ensure that our products work as expected in all browsers. 

## Assumptions:
1. Tester has access to most common browsers including: Chrome, Safari, IE 11, Firefox. This could be using an external tool like Browserstack or a Virtual Machine
2. Tester can access mobile simulation and desktop formats
3. End to End test script exists here: [INSERT LINKS]

## Acceptance Criteria:
1. The 22-0993 has been tested and run through from beginning to end.
   a. Testing will be completed as an authenticated user and as an unauthenticated user.
2. Any errors or problems have been captured in as defects in GitHub. 

## Tasks
- [x] Test form end to end on Chrome
- [x] Test form end to end on Firefox
- [x] Test form end to end on Safari
- [x] Test form end to end on IE 11
- [x] Test form end to end on Edge
- [x] Test form end to end on Mobile
- [x] Test form using google's responsive features.

## Supporting artifacts
1. Requirements for cross browser testing are located in GitHub: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/testing/cross-browser-manual-testing.md

**Comment by delli-gatti-michael** [comment]
Form is located at
https://staging.va.gov/education/opt-out-information-sharing/opt-out-form-0993/claimant-information

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1186&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
No issues found.
