### ISSUE TITLE
Remove data layer/event capture for FL location field

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17683]
## Issue Description
Due to the [potential for privacy concerns](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/decisions/google_analytics_data_scrub.md), DEPO removed the Google Tag Manager code which collected location data and scrubbed the data from Google Analytics and BigQuery. We need to remove unwanted code until we are able to replace it with approved event capture. 

---
## Tasks
- [ ] Remove data layer capturing location data 

## Acceptance Criteria
- [ ] Data layer on FL location field will no longer be present. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@mmiddaugh we've started work on this; will be linking our issue here.

**Comment by jonwehausen** [comment]
@bsmartin-ep Can this be closed along with https://github.com/department-of-veterans-affairs/va.gov-team/issues/18930

**Comment by bmcgrady-ep** [comment]
### QA Testing

Data Layer Event | DL Screenshot | GTM Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
fl-search-results | ![image](https://user-images.githubusercontent.com/66263904/108781043-88d80e80-7526-11eb-8570-60029ce87866.png)| ![image](https://user-images.githubusercontent.com/66263904/108780993-72ca4e00-7526-11eb-80b3-780e26550856.png)| ✔️ **PASS**

**Comment by jonwehausen** [comment]
@bmcgrady-ep & @bsmartin-ep Can this be closed now?

**Comment by bmcgrady-ep** [comment]
@jonwehausen - I believe so and I think that @bsmartin-ep published out the workspace.

**Comment by bsmartin-ep** [comment]
Yep.  Closing....
