### ISSUE TITLE
Backend support for "mobile = false"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17694]
## Issue Description
In #13730. we excluded Mobile Vet Centers from Facility Locator search results
Since then, Lighthouse added an optional facility mobile search filter: mobile:boolean:query
To reflect this change, the FE should pass mobile=false instead of exclude_mobile

**Facilities for testing:**
Facility Locator ID = vha_442QD (Laramie VA Mobile Clinic)
Facility Locator ID = vc_0741V (Mobile Vet Center)
Facility Locator ID = vc_0821MVC (Brooklyn Park Mobile Vet Center)
Facility Locator ID =nca_862 (Cemetery)

## Tasks
- Test Rails backend to verify which path is appropriate
- May need to handle this completely from the backend

## Acceptance Criteria
- [ ] Mobile locations are not included in search result set 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
