### ISSUE TITLE
Update Confirmation Page 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17699]
## Background
Currently the confirmation page indicates that applications are "**usually decided upon within a week**" and has some instructions in the event that that might not be the case.  However, because that information is relatively outdated, we should remove any mention of time as an expectation until we can explicitly say that it is the current turnaround time from the business.

There is also some capitalization missing and the letters "**VA**" missing from a call out for the actual form in use.

## Considerations
- In the event that the turnaround time is updated, replaced or put back in, [this is the style](https://design.va.gov/patterns/benefit-applications#after-you-apply) that should be used.
<details>

<summary>Screenshot of edits to the CH36 `/confirmation` page</summary>

![Turn-around-time_changes.jpg](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/eb85905b-cbe6-4a4d-84d3-2938323b23cd)

</details>

## Tasks
- [x] Remove the header and language, per screenshot above
- [x] Edit capitalization, per the screenshot above
- [x] Add "VA" to the parentheses form callout, per the screenshot above

## Acceptance Criteria
- [x] The issues described above are complete
- [x] A PR has been requested for merging
