### ISSUE TITLE
Update Remaining Event Names for CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17693]
## Background
GA Team has some updates to the event names for CH36 we need to add.

## Tasks
- [x] Along with the the `'howToWizard-alert-displayed'` event, update `'reason-for-notice'` to be `'reason-for-alert'` (to align with business verbiage of "alert") 
- [x] Along with the `'howToWizard-alert-link-click'` event, push a generic `'howToWizard-alert-link-click-label'` along with this event with the click text of the link 
- [x] When the "Apply" primary button becomes visible, push a `'howToWizard-cta-displayed'` event
- [x] Push the `'howToWizard-start-over'` event when the "go back and answer the questions again" link is clicked: 
![image](https://user-images.githubusercontent.com/48527022/100138283-ceb80480-2e5b-11eb-9f39-4c8c18e27aa8.png)

## Acceptance Criteria
- [x] The events above are implemented
- [x] A PR has been requested for merging
