### ISSUE TITLE
Create E2E tests for the site-wide search experience 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17697]
## Description

Establishing E2E tests for site-wide search will improve our ability to test the search experience 

## Background/Context/Resources
Will use cypress for a comprehensive set of tests

## Test Cases:

Default
- [x] Search menu appears when search button is clicked
- [x] Passes Axe requirements when search is open and suggestions are displayed
- [x]  The search icon is disabled when no valid user input is present

Typeahead Disabled
- [x] Can press search icon to initiate search using user input
- [x] Can press 'enter' to initiate search using user input

Typeahead Enabled
- [x] Shows suggestions when user input is present
- [x] Tabbing / Focusing the search icon hides search suggestions
- [x] Refocusing the input field refetches search suggestions (input must be present)
- [x] Can press search icon to initiate a search using user input
- [x] Can press enter while focused on input field to initiate a search using user input
- [x] Can click on a suggestion to initiate a search using the suggestion
- [x] Can use arrow keys to navigate search suggestions, and can press enter to search a suggestion

---

## Tasks

- [X] Review information about how E2E tests are conducted at VA.gov
- [X] Implement E2E testing 

## Definition of Done

- [X] All test cases above have been implemented and non-flakey pass

**Comment by srsuddath** [comment]
Tests have been written, validated, and merged into master
