### ISSUE TITLE
Address Accessibility Issues related to 508 Defect  Level 1

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17704]
## Description

As a result of an accessibility review for Type Ahead POC. A 508-defect-1 was identified and tracked in issue #16965. As a result, search and discovery team completed tasks to resolve issues and move forward with the Type Ahead POC implementation. This issue is to track the development efforts required and summarize the tasks involved. 

---

## Tasks

- [x] Rebuilt the typeahead experience using the downshift component. this was a total and complete rebuild of typeahead - hoping to address any accessibility issues

- [x] Updated the typeahead aria-labels, and added in some accessibility features like allowing to search on an enter press, fix excessive tabbing, etc

- [x] Make the following update: which met the following user flow criteria: 

- User can enter input and press enter key to search
- User can enter input and click search button to search
- User can enter input, and click on a suggestion from the dropdown to search
- User can enter input, use the arrow keys to select a suggestion and press enter to search
- Tabbing to the search button closes the suggestions list
- Back-tabbing from the search button to the input field re-fetches suggestions and displays them
- User can press escape key anywhere inside search experience to close the suggestions list
- Default Search cases tested:
- User can enter input and press enter to search
- User can enter input and click search button to search

- [x] Update the analytics logging for the search results page

## Definition of Done

- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/559

- https://github.com/department-of-veterans-affairs/vets-website/pull/15387

- https://github.com/department-of-veterans-affairs/vets-website/pull/15415

**Comment by srsuddath** [comment]
PRs have been merged and staging review is taking place. Planning to move this ticket to validation by COB

**Comment by srsuddath** [comment]
Now that the launch blocking issue has been rectified, this issue can be closed.
