### ISSUE TITLE
Truncate Docker Tag in vets-website CI

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#17719]
## Description
Docker tags can only be 128 characters long. Long branch names cause vets-website CI to fail due to docker refusing to use long tag names.

## Background/context/resources

Example: http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/16963-Write-RTL-tests-to-check-order-of-facilities-when-sorting-by-current-location-and-residential/5/pipeline/

The branch name is `16963-Write-RTL-tests-to-check-order-of-facilities-when-sorting-by-current-location-and-residential`

## Technical notes
_Notes around work that is happening, if applicable_

We need to truncate this value: https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L38

---
## Tasks
- [ ] truncate docker tag so it is less than 128 characters long

## Definition of Done
- [ ] vets-website jenkins ci works with extremely long branch names

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic
