### ISSUE TITLE
Identify VA.gov pages where we could link to direct upload

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#17723]
## Issue Description
We recently added a link to the direct upload tool in the first Q&A on this page: https://www.va.gov/disability/upload-supporting-evidence/
We need to identify other pages that talk about sending documents/evidence/etc. to VA. Here's what's already been discussed as possibilities:
- https://www.va.gov/decision-reviews/supplemental-claim/
- https://www.va.gov/pension/survivors-pension/
- https://www.va.gov/disability/dependency-indemnity-compensation/

---
## Tasks
- [x] Audit VA.gov to identify pages where we might link to direct upload.
- [x] Make a list in this ticket of those pages.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@lunascoop Here's the ticket. Let me know if you have questions. I didn't add it into a sprint yet but we can once you've started working on it.

**Comment by lunascoop** [comment]
I’ve reviewed the pages on VA.gov and identified these pages that can either use a direct upload link or the “send the form” instructions aren’t as clear as on other pages.
- https://www.va.gov/health-care/about-va-health-benefits/cost-of-care/#how-we-assess-and-verify-your-
- https://www.va.gov/health-care/about-va-health-benefits/va-health-care-and-other-insurance/
- https://www.va.gov/health-care/how-to-apply/#more-information-about-applyin (first accordion question. If not, may be helpful to add mailing address of where to send form (see https://www.va.gov/health-care/update-health-information/#how-do-i-use-this-form-to-upda. Actually, all the forms in the three accordions may need "where to send" info)
- https://www.va.gov/disability/how-to-file-claim/additional-forms/
- https://www.va.gov/disability/how-to-file-claim/evidence-needed/standard-claims/
- https://www.va.gov/disability/eligibility/ptsd/#how-do-i-get-these-benefits (Where to send the additional forms in the two bullets?)
- https://www.va.gov/disability/eligibility/special-claims/automobile-allowance-adaptive-equipment/#how-do-I-get-these-benefits (Where to send the additional forms in the two bullets?)
- https://www.va.gov/disability/how-to-file-claim/evidence-needed/ (where to send the additional forms on this page?)
- https://www.va.gov/disability/dependency-indemnity-compensation/#how-do-i-apply-for-compensatio (where to send the additional forms?)
- https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/#how-do-i-get-these-benefits (I know the forms in Step #3 likely shouldn’t link to direct upload tool, but where should these forms be sent?)
- https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/work-study/#how-do-i-get-these-benefits (Where to send this form?)
- https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/#how-do-i-get-these-benefits (where to send form in first accordion?)
- https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/ (where to send form in this section: What if I’m a service member who hasn’t yet received a service-connected disability rating?)
- https://www.va.gov/careers-employment/education-and-career-counseling/#how-do-i-get-these-benefits  (where to mail form)
- https://www.va.gov/education/other-va-education-benefits/veap/ (where to send form in step #2? Also, is there a spacing issue between the steps?)
- https://www.va.gov/pension/aid-attendance-housebound/#how-do-i-get-these-benefits (where to send these forms?)
- https://www.va.gov/housing-assistance/home-loans/how-to-apply/#how-do-i-prepare-before-starti (where to send form in last accordion?)
- https://www.va.gov/life-insurance/options-eligibility/fsgli/#which-forms-would-m (where to send these forms?)
- https://www.va.gov/life-insurance/options-eligibility/vgli/ (where to send multiple forms on this page?)
- https://www.va.gov/life-insurance/options-eligibility/vmli//#how-do-i-get-these-benefits 
- https://www.va.gov/life-insurance/file-appeal-for-tsgli/ (where to send this form?)

#### Bug possibly found
<img width="1018" alt="Screen Shot 2021-01-04 at 6 05 45 AM" src="https://user-images.githubusercontent.com/42546515/103530318-2f702f00-4e55-11eb-9af2-677fed38de29.png">

When clicking the “Premium rates” link on left nav, the page doesn’t seem to go anywhere and just refreshes.

**Comment by RLHecht** [comment]
@mnorthuis It looks like there's a link in the left nav under insurance that is redirecting back to the same page. See the comment from @lunascoop above. This is the link that's in the menu in the CMS: https://www.benefits.va.gov/INSURANCE/vgli_rates_new.asp Should this still be in the left nav?

**Comment by mnorthuis** [comment]
The "Premium rates" option should be removed from the left nav. The rates were added to the displayed page and the legacy page was redirected last January.

**Comment by RLHecht** [comment]
@mnorthuis Just removed it. Thanks! FYSA @lunascoop

**Comment by bethpottsVADEPO** [comment]
Just getting this info in the ticket. Stakeholders want a link to direct deposit added to these 2 pages 1 of which Selina already identified.

Erica Dunbar asked for both of these and Michael Young asked for the second one, DIC. I need to respond to their requests with recommended PL text:
https://www.va.gov/pension/survivors-pension
https://www.va.gov/disability/dependency-indemnity-compensation/

Language Erica suggested:
**Electronically**
	You can upload you claim or supporting evidence by using the direct upload tool through AccessVA.

Order of "ways to apply on DIC page" from Michael:
1. Accredited Rep
2. Direct Upload
3. PMC
4. RO

**Comment by bethpottsVADEPO** [comment]
@lunascoop These 2 are ready for you to implement. Let me know if you have any questions! These are the most important ones to get live soon. I'll consider the others. Thank you for the list you put together. After you implement, let me know and I'll send to the stakeholders for a thumbs up. So please don't publish these edits yet.

**https://www.va.gov/disability/dependency-indemnity-compensation/
(Under "How do I apply for compensation?")**

New bullet: Use the direct upload tool through AccessVA to upload your form online.
[Go to AccessVA to use direct upload](https://eauth.va.gov/accessva/?cspSelectFor=dmhs)

Order of ways to apply will change to:
Accredited Rep
Direct Upload
PMC
Regional office

**https://www.va.gov/pension/survivors-pension
(Under "How do I apply for a VA Survivors Pension?")**

New H3: **Online**
Use the direct upload tool through AccessVA to upload your form online.
[Go to AccessVA to use direct upload](https://eauth.va.gov/accessva/?cspSelectFor=dmhs)

Order of ways to apply will change to:
With the help of a trained professional
Online
By mail
In person

**Comment by lunascoop** [comment]
@bethpottsVADEPO @RLHecht I've added the direct upload link to the two pages and they're ready for review.

- About VA DIC for spouses, dependents, and parents: http://preview-prod.vfs.va.gov/preview?nodeId=855
- VA Survivors Pension: http://preview-prod.vfs.va.gov/preview?nodeId=590

**Comment by RLHecht** [comment]
@bethpottsVADEPO These have both been reviewed and are ready to go. Let us know when we are ready to publish.

**Comment by bethpottsVADEPO** [comment]
Thanks, @RLHecht and @lunascoop! I'm now getting approval from the pension SME. We'll wait to hear back from her.

**Comment by bethpottsVADEPO** [comment]
@RLHecht  You can take a final look before publishing the two pages mentioned above. Angie's approval came through! Go go go! And thank you.

**Comment by RLHecht** [comment]
These have been reviewed and the new change of adding the address for the mail section was also added. I'll keep this ticket open for the other pages that still need to have the links added.

**Comment by bethpottsVADEPO** [comment]
I think we can close this now. @RLHecht in your note above, were you referring to all the pages Selina listed? We're just going to stick with the two we already updated.

**Comment by RLHecht** [comment]
@bethpotts Yep, if these are the only pages we are touching, we can close this ticket.
