### ISSUE TITLE
Make Room in vagov-utility VPC subnets for EKS cluster

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#17736]
## Issue Description
In order to have an EKS cluster in vagov-utility, we will need more available IP addresses in one or more existing subnets (1a and 1b in particular). Currently there is a `1c` subnet that was created long after the VPC, but is still a bit under-utilized. We will have to shuffle some deployments around to balance the IP addresses being used / available. 

Background: 

- Tools like grafana, argo, sentry, et al will run in this cluster
- This will likely result in some downtime for services as deployments are shifted
- Unable to change ALB settings w/out minimum needed IP addresses
- Will likely want to move things like Support Bot into this cluster in the future
- We hypothesize that fewer IPs will be needed in the future when everything is moved to EKS 

Ref: https://dsva.slack.com/archives/CTYQL39FE/p1608315873173700

---
## Tasks
- [ ] Decide if we can consolidate a bit and use DNS / routing rules on the utility-tools ELB rather than having 3 separate ELBs altogether
- [ ] Properly configure ELB(s) to use the newer `1c` subnet
- [ ] Shift deployments around so that we aren't seeing numbers of available IP addresses in the current manner of
- [ ] If needed, upgrade this ticket to an epic, and create add'l tickets for each deployment that we need to shift

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/e41646cd-e6c5-49cd-8102-1e3683739405)

## Acceptance Criteria
- [ ] Proper distribution / usage of available IP addresses within the vagov-utility VPC
- [ ] Provisioned EKS cluster that does not block future deploys to the VPC
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
This was addressed with our solution development using Calico
