### ISSUE TITLE
Scaffold component structure for Search form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#17730]
`Review LH call responses, review mockups ahead of larger iteration`

## Goal
In order to begin building the POA Search according to the mockups we need to first scaffold out any components that will be needed. These scaffolds do not need to include any logic, as that will be added in separate tickets, but it should reflect the basic structure the app architecture will follow. For the POA Search in particular we need to build/ modify the following components -

- [x] A form using the form system
- [x] A custom search component used inside the form

## Considerations
- [Current Search Rep mockups](https://xd.adobe.com/view/b80b0931-826b-413a-9b07-1efff71cae16-ed58/screen/b416b28c-7153-4d67-ae7c-a2150008af3a)

## Tasks
- [x] Build/ modify the components listed above to reflect the architecture of the POA Search app
- [ ] Add a new entry to the code-owners file
- [ ] Remove the Veteran Representative feature in `vets-api` (3 years old and we rebuilt it)
- [x] Submit a PR for review

## Acceptance criteria
- [x] The above components that have been scaffolded
- [x] A PR has been submitted for review
