### ISSUE TITLE
Find a VA Form - Add 'Sort by Form last updated' feature

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17732]
## Add a 'sort by form last updated' function on modern forms search

**User story:** As an external user of VA forms - such as a state Veterans benefit agency or a Veterans claims agent service - I need to access the full list of VA forms by the most recent form updated date. 

Today, by doing a null search, users are able to get the full list of forms. However, users are not able to view the forms in the order of the most recent **Form last updated** date. This is a frequent request by organizations using VA forms (e.g., state veteran agencies).

Acceptance Criteria:
- [ ] Create design for 'Sort by Form last updated' date feature following established pattern if one exists.
- [ ] Content changes needed to implement this feature are written and approved.
- [ ] Add a 'Sort by Form last updated' date feature to FE code.
- [ ] Ensure that the new sort feature is 508 compliant.
- [ ] Internal staging test 
- [ ] All collaboration cycle touch points complete.

**Comment by MarciMcGuireGCIO** [comment]
Converting to epic so we can bundle up the discovery, design, testing work inside.  Also breaking this apart from the [Post-Launch MVP work ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10758)since this involves creating a new component not yet in the design system.
