### ISSUE TITLE
Add basic logic to search form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#17742]
# Goal
Now that the basic structure has been set up for POA Search we need to begin adding the logic that will drive the functionality. This ticket is to add logic to the POA Search form component. The logic should only cover the scope of the following user story 

## User Story
As a Veteran, I want to be able to specify the parameters by which I am searching for a POA so that I can find the best POA for my needs

This functionality will require logic to do the following step:
- [ ] The search component passes the parameters that the user wants to search by up to the parent component to be sent to the API

## Tasks
- [ ] Code the logic to accomplish the above-listed step
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] As a user when I specify the search parameters I want to search by they are ready to be sent to the api
- [ ] A PR has been submitted for review

**Comment by jason-gcio** [comment]
building using schema form
