### ISSUE TITLE
Normalize print style for for print this page 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#17749]
## Issue Description
This issue is a follow up from a DC meeting about Print styling for confirmation page (#197). Decision was made for DST to do an audit and define a print style for print this page. 

---
## Tasks
- [ ] Audit existing print this page style
- [ ] Define behavior of print this page
- [ ] Write up guidelines

## Acceptance Criteria
- [ ] Audit is complete
- [ ] A pattern / norm is defined
- [ ] Guidelines written up.

**Comment by caw310** [comment]
This is the ticket that was discussed in DC meeting for reference.
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/197

**Comment by bkjohnson** [comment]
Adding `forms` label since the confirmation page is part of the forms library.

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated
