### ISSUE TITLE
Create a Github Repo, ECR repo, and RDS database for the Identity Team's Test User Dashboard project.

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#17745]
## Issue Description
The Identity team is setting up a "test user dashboard" and will need a place to put their code, as well as a database to store the data in.
There will be a single database and application accessed via SOCKS proxy at this time.
We will host the application in an EKS cluster in either the staging or utility VPC.
We may need to assist with CircleCI/release management

---
## Tasks
- [x] Create Github Repo: 'vsp-test-user-dashboard' with appropriate permissions for @vsp-identity
- [ ] Create Terraform code for ECR Repo: dsva/test-user-dashboard with appropriate permissions for Identity team in IAM
- [ ] Create Terraform code for RDS Database: test-user-dashboard with appropriate permissions for Identity team in IAM
- [ ] Create a path in Parameter Store for the Identity team to store their application secrets
- [ ] Modify the Identity team's IAM permissions to have access to the Parameter Store path created above

## Acceptance Criteria
- [X] Github Repo
- [ ] ECR Repo
- [ ] RDS Database
- [ ] Parameter Store path
- [ ] IAM permissions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
do we need to leave this one open, or does #24307 have more relevant information for you, Demian?

**Comment by jhouse-solvd** [comment]
Please see [#24307](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25448)

Closing.
