### ISSUE TITLE
Normalize of the behaviors of confirmation page 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#17748]
## Issue Description
This issue is a follow up from a DC meeting about Print styling for confirmation page (#197). Decision was made for DST to normalize the behaviors of confirmation page, and define content guidelines for success page (include errors )

---
## Tasks
- [ ] Audit existing confirmation pages
- [ ] Define behavior of confirmation pages 
- [ ] Define content guidelines
- [ ] Write up guidelines

## Acceptance Criteria
- [ ] Audit is complete
- [ ] A pattern / norm is defined
- [ ] Guidelines written up.

**Comment by caw310** [comment]
This is the ticket that was discussed in DC meeting for reference. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/197
