### ISSUE TITLE
Initial Redux Code for API Calls

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#17744]
# Goal
We use Redux to manage the state of our apps across VA.gov and since the POA Search will use data from any of various sources we need to build out the redux code to support that. This initial build of the Redux code does not have to use live data if none is available yet, we can hard code mock data for the time being if needed.

## Tasks
- [x] Set up Action(s) file for POA Search
- [x] Set up Reducer(s) file for POA Search
- [x] Submit a PR for review

## Acceptance criteria
- [x] The POA Search now uses Redux to manage state (dummy calls)
- [x] A PR has been submitted for review
