### ISSUE TITLE
Add Pagination for Search Results

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#17743]
## Goal
We need to sync this in staging with what we have in design and then paginate results.

## User Story
As a Veteran, I want to see the results of my POA search so that I can determine which POA I want to go with

## Considerations
This functionality will require logic to do the following steps:

- [x] Search data is iterated over and each result is passed to the search result component
- [x] The search result is displayed by the search result component
- [x] Paginate results (10 per page or similar to View Payments)

## Tasks
- [x] Wrap the search results in a pagination component to accomplish the above-listed steps
- [ ] Add remaining local pages to staging (request is in 2 different repos) (stretch: may end up in another ticket)
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] As a user when I view my search results I can determine which POA I want to go with
- [ ] A PR has been submitted for review

**Comment by micahchiang** [comment]
@cohnjesse - do you think the work originally described for this ticket has been completed in your PR for https://github.com/department-of-veterans-affairs/va.gov-team/issues/17730? Feel like we may be able to close this one as a duplicate now.
