### ISSUE TITLE
[DISCOVERY] Evaluate viability of dynamic solution code for VAMC side nav

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17746]
## Issue Description
A solution was found to dynamically add FACILITY_MENU_NAMES so the side nav component would be included in new facility builds (rather than using the previous method of hardcoding). A dynamic method is needed to support the increasing volume of new VISNs that are onboarding. The PR had to be rolled back due lack of network access to the Drupal API, causing the builds to fail. The front end tools team will make it possible to access a frequently updated latest cache so that anyone (devs, review instances, CircleCI, etc.) can always pull from that S3 bucket without the need to pull from Drupal.

Once [this work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17187) is complete, we can restore the code to dynamically add FACILITY_MENU_NAMES

This may become important in the case of new systems/mergers with name changes - results in dependencies/cross-team collaboration

## Related issues
[PR for dynamic sidenav which we had to roll back](https://github.com/department-of-veterans-affairs/vets-website/pull/14854)
[Revert PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15141)

---
## Tasks
Evaluate viability of previous code by
- [ ] Testing the option for restoring code
- [ ] Collab with VSP to revive/test (since previous problems showed during deployment)
- [ ] See how this works with Tugboat

## Acceptance Criteria
- [ ] Tasks and Level of effort is documented

**Comment by mpelzsherman** [comment]
Since the original work was done before the content-build separation, we can't simply re-apply the code changes; these will have to be done manually. Also, there have been many changes since the work was done (e.g. to support parallel GraphQL queries), which complicates the effort. Still researching...

**Comment by mpelzsherman** [comment]
After further investigation, I do not think this project is worth the risk/effort, unless the lack of dynamic side nav content is truly causing a major problem. The code in content-build has diverged too far from where it was when this work was originally done. This change could cause major issues if not done correctly. I suggest we leaving this one on the cutting room floor, sorry!

**Comment by mpelzsherman** [comment]
@mmiddaugh can we close this?
