### ISSUE TITLE
Location and Contact section of Facility Health Services is not to design spec

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17755]
## Issue Description
Location and Contact section of Facility Health Services is not to design spec.
When viewed on [Staging](https://staging.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/), some aspects of the design/UI implementation have deviated from the design spec. 

**Extra padding/spacing between address lines (p tags) and between subsets of info**

<details>
<summary> Padding issues (from staging) </summary>

![image](https://user-images.githubusercontent.com/55411834/102666326-db223b00-4143-11eb-85ac-c5e384db35bc.png)

![image](https://user-images.githubusercontent.com/55411834/102666696-ce521700-4144-11eb-8ae2-f9cf7a7ae23d.png)

![image](https://user-images.githubusercontent.com/55411834/102667031-9dbead00-4145-11eb-96ba-f03246a22bd9.png)

![image](https://user-images.githubusercontent.com/55411834/102667265-33f2d300-4146-11eb-9f69-3a021f7cb2f5.png)

![image](https://user-images.githubusercontent.com/55411834/102667473-b1b6de80-4146-11eb-98b0-7b6be23a15c0.png)

</details>

---

[Design spec](https://app.zeplin.io/project/5f5268f4bbe0d289b757f0cb/screen/5f526c2da9b6cb7eeeeb3127)

---
## Tasks
- [x] Remove extra padding/spacing between address lines
- [x] Shorten the space between phone numbers and "Referral required" to match  the space below "Referral required"
- [x] Spacing above and below the "appointments" button is visually equal 
- [x] Spacing between Sun hours and the info line for "on call" or "holidays" (for example) should be the same as the spacing between Sat and Sun
- [x] Details in the line below Sun should be italicized (such as "On call 24/7" for Cardiology and "Some appointments may be available at other hours" for Mental health)
- [x] Make Appointments H3 (the same heading level as Contact information)
- [x] Ensure no heading levels are skipped between _Location names_ and _Hours_ and _Phone_ 

## Acceptance Criteria
- [x] Address display is consistent with spec
- [ ] Spacing between subsets of things is equal - >  
      - The spacing above "Referral required" matches spacing below "Referral required"
      - Spacing above and below the "appointments" button is visually equal 
      - Spacing between Sun hours and the info line for "on call" or "holidays" is the same as the spacing between Sat and Sun
 - [ ] Text in the detailed information line is italicized (such as "On call 24/7" for Cardiology and "Some appointments may be available at other hours" for Mental health)
- [ ] No heading levels are skipped when the location name is missing, but the appearance of the text headings does not change.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rtwell** [comment]
1. Spacing between the phone number and "Referral required?"
   • the spacing between subsets of things should be equal in order for users to group content by proximity. It looks like there is more space below the phone numbers and "Referral required", and should be shortened to match the space below "Referral required"

2. Spacing of the appointment button
   • same as 1 above, the spacing should be visual equal. 

3. Spacing for the line with details following the hours listing (such as "On call 24/7" for Cardiology and "Some appointments may be available at other hours" for Mental health")
   • correct—this spacing should be identical as the content above it. 

4. Alignment of hours in "Holidays"
   • since this is kind of a catch all field in drupal for different information, let's simply italicize this line, and make sure the spacing is consistent (I believe the same as 3).

**Comment by mmiddaugh** [comment]
Headings and accessibility
Always use semantic headings, logically nested in the proper order. Do not use improper nesting to achieve a different font size. In other words, an h1 should never be followed by an h3; it should only be followed by an h2. Use the font-size utility to change the font size of a semantic heading instead.

**Comment by mmiddaugh** [comment]
[A related issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15701) documents heading level changes which are needed

**Comment by mpelzsherman** [comment]
Dev note: the template with the HTML markup for this section is `src/site/facilities/service_location.drupal.liquid`.

**Comment by mmiddaugh** [comment]
Non-critical findings are noted in #18866. This issue can be closed.
