### ISSUE TITLE
Update URL on mental health services page to avoid broken link

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#17776]
## Issue Description
A SiteImprove report showed that there was a broken link on our [VA mental health services page](https://www.va.gov/health-care/health-needs-conditions/mental-health/). The last link in the last accordion on the page was pointing to http://www.mentalhealthamerica.net/. MHA recently changed their URL to https://www.mhanational.org/ and the redirects weren't put in place yet. 

We need to update the url on our page to avoid a broken link.

## Tasks
- [x] Update MHA url (Randi)
- [x] Review and publish page (Randi)

## Acceptance Criteria
- [x] New URL on page and working

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This ticket was created after the work was done. Created for tracking purposes. Moving to validate and will close after deploy. FYSA @brianalloyd

**Comment by brianalloyd** [comment]
Thanks @RLHecht for putting in the ticket for tracking, much appreciated.

**Comment by RLHecht** [comment]
This broken link is fixed on the site. Closing ticket. FYSA @DanielleThierryUSDSVA
