### ISSUE TITLE
Add FSR PDF download route, controller method, and service method

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#17781]
## Issue Description
Completed financial status report PDFs will be available to download for the veteran's records; we need to expose that in the API.

---
## Tasks
- [x] Add controller method
- [x] Add route
- [x] Add service method
- [x] Add tests

## Acceptance Criteria
- [x] Generated PDFs will be available to download
