### ISSUE TITLE
Add max number of result returned from PPMS 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17782]
## Issue Description
Sentry monitoring indicates someone is hitting our endpoint hard with PPMS requests, using multiple specialty codes and receiving 300+ results. As a result,  we need to cap the number of results we will return from PPMS. 

Note: the front end caps results at 10. Currently, no max set on backend.  

---
## Tasks
- [x] Cap max number of results to 50. 

## Acceptance Criteria
- [x] Queries will be limited to 50 results on backend. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
