### ISSUE TITLE
General Type Ahead Usability Improvements

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17783]
## Description

Type Ahead POC has been launched on VA.gov on December 21, 2020 to 5% of audience and will run for 4 weeks (~Jan 19). During that time general usability improvements will be captured and considered for integrated as part of Type Ahead 1.0

---

## Tasks

- [x] Search and Discovery team will collect potential improvements or changes that should be considered to make type ahead better in Type Ahead 1.0. These improvements may be captured through a variety of sources including testing, user feedback, comments and feedback from others exploring type ahead
- [x] Search and Discovery Team will meet to  review the potential changes listed and discuss on a case by case basis.  @denisecoveyduc to schedule a meeting to discuss and explore comparative analysis, style guide as they relate to Type Ahead
- [x] Review potential changes, decide if they should be implemented and extract into new issues 

## Potential Changes Captured
- [x] As a user, I should be able to click search and automatically start typing without having to click or tab into the typing box. 
- [x] As a user selects one of the type ahead suggestions the query should automatically be run versus requiring them to then initiate query manually.
- [x] Direct matches should appear first in the list of suggestions versus buried in list of suggestions
<img width="273" alt="Screen Shot 2020-12-21 at 11 34 10 PM" src="https://user-images.githubusercontent.com/72393866/102849483-3f175e80-43e5-11eb-9fb0-9c3677e77fdc.png">

- [x] Consideration: How should type ahead handle singular vs plural? "form" vs "forms" currently yields completely different results. After we have some canned suggestions users expect that both queries yield the same results. 

## Definition of Done

- [ ] Search and Discovery team has met and decided which changes above should be implemented.
- [ ] Changes that have been selected for further exploration have been extracted into individual issues for backlog

**Comment by denisecoveyduc** [comment]
@mgleo @srsuddath @johnhashva As discussed, as you identify potential type ahead improvements please add them to the list for discussion and exploration.

**Comment by mgleo** [comment]
We need to know more about how typeahead suggestions are formatted to inform the design moving forward: Will the typed word always appear in front of a typeahead suggestion?

**Comment by denisecoveyduc** [comment]
Deprioritized. Removed from Sprint 39 as we need to review the style guide for type ahead which is being shaped by conversations with search.gov team. Once we have a better understanding of the limits for type ahead then we can decide which of these improvements we would like to explore for typeahead 1.0.  We will continue to update issue with future ideas and then review when ready to tackle new features for typeahead.

**Comment by denisecoveyduc** [comment]
As part of our typeahead POC assessment these potential improvements were captured and discussed in a [mural exercise](https://app.mural.co/invitation/mural/vsa8243/1611953766486?sender=u2d05955ffd6072aabd7a3918&key=30b69020-97f7-4387-9952-a5031bc3246c). Improvements were categorized and identifies for potential integration in typeahead 1.0 and beyond. Each recommendation will be raised with VAPO for prioritization.
