### ISSUE TITLE
[Analytics] My VA: Looking into what ""Dashboard - Navigation - Continue Button" is actually tracking

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#17786]
## Description
**Who is this request for?**

Ben McGrady

**What team/project is this work for?**

This request is for authenticated experience, specifically related to the My VA redesign project.

**What type of analytics support are you looking for?**
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    
Details: [In this report of the top clicks from My VA](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20201220&_.useg=builtin1&_r.drilldown=analytics.pagePath:~2Fmy-va~2Findex.html,analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50/), in row 11, there is something labeled "Dashboard - Navigation - Continue Button -". I am not 100% sure what this is tracking on the dashboard, and I need someone (most likely Ben) to look into this and figure out what this is actually tracking. 

## Timeframe for Analytics Requested
**Please provide the timeframe for the metrics you are requesting.**

ASAP, though there is no serious urgency.

## Analytics to Track Down

See above.

## Other Helpful Questions to think through

I'm hoping to understand what this specific metric is since it seems like a common action taken from this page.

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

[My VA report from Jan 1 - Dec 20, 2020](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20201220&_.useg=builtin1&_r.drilldown=analytics.pagePath:~2Fmy-va~2Findex.html,analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50/)

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - After looking into this, the **"Dashboard - Navigation - Continue Button -"** event is fired when the **"Continue Your Application"** button is clicked.
![image](https://user-images.githubusercontent.com/66263904/103098937-d2a98480-45c9-11eb-977a-8dfe013a62b5.png)

**Comment by bmcgrady-ep** [comment]
I'm closing out this ticket. Feel free to reopen if you have any additional questions.

**Comment by Samara-Strauss** [comment]
Thank you! This is what I thought but wanted to confirm. We'll probably want to rename that tag for My VA 2.0, but no need to worry about that now. We can get that set up when we're working on those analytics in a few months.
