### ISSUE TITLE
Migration of Loki (Dev) ECS/Fargate->EKS

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#17788]
## Description
Loki for dsva-vagov DEV had originally been deployed on ECS/Fargate.

New direction is to use EKS for these types of services, so migrate existing Loki infrastructure in DEV to an EKS-based Loki solution.

## Background/context/resources
Depencencies:
* EKS cluster in dev is available and stable for app deploys
* Loki is installed, tested and stable on EKS cluster
* There is a mechanism to manage/change DNS CNAME entries at the Kubernetes level

## Technical notes
Loki docs: https://vfs.atlassian.net/wiki/spaces/VI/pages/619119010/Loki+-+Centralized+Logging+in+VSP

EKS docs/info: https://vfs.atlassian.net/wiki/spaces/VI/pages/856621057/2020-12-17+Meeting+notes+Standing+up+a+new+EKS+cluster

---
## Tasks
- [x] Change DNS CNAME for `loki-dev.vfs.va.gov` to point to EKS cluster
- [x] Update Ansible code as necessary to ensure all DEV hosts are using new cluster (may require some refactoring)
- [x] Add Loki dev EKS as a new datasource in Grafana
- [x] Delete old Loki DEV Fargate datasource in Grafana

## Definition of Done
- [x] All instances/services currently logging to Loki Dev Fargate/ECS are now logging to Loki Dev EKS
- [x] dsva-vagov DEV logs can be queried in Grafana using EKS Loki Dev as a datasource

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
This work is complete; associated PRs:

- https://github.com/department-of-veterans-affairs/devops/pull/8244
- https://github.com/department-of-veterans-affairs/devops/pull/8238
- https://github.com/department-of-veterans-affairs/devops/pull/8246
- https://github.com/department-of-veterans-affairs/devops/pull/8247
- https://github.com/department-of-veterans-affairs/devops/pull/8266

Grafana using new datasource "Loki (Dev)":

http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Benvironment%3D%5C%22vagov-dev%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by jhouse-solvd** [comment]
closing.
