### ISSUE TITLE
Displaying the Call Center phone number (Vet Center)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17799]
## Issue Description

As a Veteran, I need to know how to contact someone representing my local Vet Center. 

**Current protocol** 

- As of 12/21, the Vet Center call center only does warm handoffs to the crisis line. 
- The Call center gives the local Vet Center contact info to the Veteran and sends an email to the relevant local Vet Center about the Veteran's call (generally within a few hours) 
- If a Veteran calls the Vet Center directly after hours, he/she is patched through to the Call Center. 
- There is a new director for the Call Center so this process is subject to change. 

---
## Tasks
- [ ] Consider the best display for the Call Center considering no warm handoff is given

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Replaced by #28819
