### ISSUE TITLE
Solution for managing DNS in K8/EKS

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#17791]
## Description
Since platform tools will be managed with EKS/K8 clusters, there will be a need to manage DNS records associated with services and apps deployed there.  Currently, DNS is managed by Terraform but Terraform has little/no visibility to changes at the K8 level.

## Background/context/resources
External DNS looks promising, and will focus efforts on that:

https://github.com/kubernetes-sigs/external-dns

---
## Tasks
- [x] Spike / Research possible solutions
- [x] Test  and solicit input/feedback on solution proposal
- [x] Commit example code
- [x] Documentation

## Definition of Done
- [x] There is a documented solution with sample code to update DNS for apps/services deployed on EKS clusters

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
This work is complete and currently working/deployed on the `platform-tools` cluster in DEV:
```

┌─[loki-staging-eks 16 files, 120]──[Mon Dec 21 13:31:37 35 days]──[Stevan-Arychuk-Macbook]──[~/Projects/loki-staging-eks]
└─▶ kubectl describe pod external-dns-59bf88f769-6szhk
Name:         external-dns-59bf88f769-6szhk
Namespace:    default
Priority:     0
Node:         ip-10-247-96-187.us-gov-west-1.compute.internal/10.247.96.187
Start Time:   Wed, 16 Dec 2020 12:13:10 -0800
Labels:       app=external-dns
              pod-template-hash=59bf88f769
Annotations:  iam.amazonaws.com/role: arn:aws-us-gov:iam::008577686731:role/dsva-vagov-eks-manage-route53-role
              kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.247.96.174
IPs:
  IP:           10.247.96.174
Controlled By:  ReplicaSet/external-dns-59bf88f769
Containers:
  external-dns:
    Container ID:  docker://99534fbf10ed99ba8706f9b835a375ffb3e863786cf8065aa2dee69a95bf058a
    Image:         008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/external-dns:0.7.5-vagov-certs
    Image ID:      docker-pullable://008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/external-dns@sha256:9bfd6558ec790bba54c4c8620b778c25cbb45a3513bfdbfea7d8d10c1938c9b8
    Port:          <none>
    Host Port:     <none>
    Args:
      --source=service
      --source=ingress
      --domain-filter=vfs.va.gov
      --provider=aws
      --aws-prefer-cname
      --policy=upsert-only
      --aws-zone-type=private
      --registry=txt
      --txt-prefix=dsva-vagov-
    State:          Running
      Started:      Wed, 16 Dec 2020 12:13:11 -0800
    Ready:          True
    Restart Count:  0
    Environment:
      AWS_REGION:                   us-gov-west-1
      AWS_ROLE_ARN:                 arn:aws-us-gov:iam::008577686731:role/dsva-vagov-eks-manage-route53-role
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from external-dns-token-jqflb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  external-dns-token-jqflb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  external-dns-token-jqflb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Comment by pnwstevan** [comment]
Example manifest for above has been checked into the "vsp-infra-application-manifests" repo here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/k8s/external-dns-vagov.yaml

Will include a section in the EKS docs specifically for this, but once external-dns has been deployed on a cluster with the above manifest, you can create a DNS CNAME by annotating the pod/deployment/service like this:

`external-dns.alpha.kubernetes.io/hostname: loki-dev.vfs.va.gov`

**Comment by jhouse-solvd** [comment]
Want to make sure Stevan's comments are linked into some documentation for posterity's sake and then will close this out.

**Comment by jhouse-solvd** [comment]
See [here](https://vfs.atlassian.net/wiki/spaces/VI/pages/871202823/Create+and+deploy+a+Kubernetes+EKS+Cluster+in+VSP) for great documentation on this and more regarding EKS on VSP

**Comment by jhouse-solvd** [comment]
closing.
