### ISSUE TITLE
[VAMC] Reassociate orphan Facility Health Services to System Health Services that were previously duplacates and that were deleted [PM] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17790]
## Issue Description
All orphan facility health services have to be re-associated, due to Duplicates at the System Health Service level, all Facility health service associated to those duplicates when they were deleted created orphans, so there are no more orphan health services.

---
## Tasks
Resolve all orphan facility health services for the following Systems:
- [x] Altoona
- [x] Erie
- [x] Find and list all orphans 
- [x] Research and find the Parent System health service and re- associate them to that services/System

## Acceptance Criteria
- [x] No orphans remain in each System.
---
