### ISSUE TITLE
Decommission and remove old Loki ECS/Fargate Infrastructure in DEV

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#17793]
## Description
Loki in the DEV environment for dsva-vagov was originally deployed on ECS/Fargate.

New direction is to deploy these services on EKS.  Once Loki has been deployed on EKS and all hosts/services in DEV are logging to the new Loki deployment, clean-up and decommission the old ECS/Fargate infrastructure and all associated AWS resources.

## Background/context/resources
Dependencies:
* `platform-tools` EKS cluster in DEV is deployed and stable (ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16604)
* Loki Deployed on EKS cluster in DEV (ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17177)
* Migration from existing ECS/Fargate cluster is complete (ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17788)

## Technical notes
Resources:
* ECS/Fargate Cluster
* Fargate Task Definition
* Security Groups
* IAM Roles
* S3 Buckets
* DynamoDB

---
## Tasks
- [x] Update and commit terraform code for DEV to reomve existing Loki ECS resources
- [x] Remove all resources via terraform plan/apply
- [x] Clean-up any remaining resources NOT managed by Terraform (sanity check)

## Definition of Done
- [x] All AWS resources associated with old Loki ECS cluster are removed
- [x] Terraform state is in sync in DEV with no tf code for old resources

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
This work has been completed; associated PR:

https://github.com/department-of-veterans-affairs/devops/pull/8250

Confirmed:
* PR merged
* Terraform plan/apply run in DEV and state is in sync.
* Verified via AWS console all associated resources have been removed

**Comment by pnwstevan** [comment]
Terraform plan for record keeping:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy
 <= read (data resources)

Terraform will perform the following actions:

  # data.null_data_source.wait_for_cluster_and_kubernetes_configmap will be read during apply
  # (config refers to values not yet known)
 <= data "null_data_source" "wait_for_cluster_and_kubernetes_configmap"  {
      + has_computed_default = "default"
      + id                   = "static"
      + inputs               = {
          + "cluster_name"             = "dsva-vagov-dev-platform-tools-cluster"
          + "kubernetes_config_map_id" = ""
        }
      + outputs              = {
          + "cluster_name"             = "dsva-vagov-dev-platform-tools-cluster"
          + "kubernetes_config_map_id" = ""
        }
      + random               = "5434850211935010741"
    }

  # aws_alb_listener.this will be destroyed
  - resource "aws_alb_listener" "this" {
      - arn               = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:listener/app/dsva-vagov-dev-tools/46769a30f69f30cb/f4f3fe7768641deb" -> null
      - id                = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:listener/app/dsva-vagov-dev-tools/46769a30f69f30cb/f4f3fe7768641deb" -> null
      - load_balancer_arn = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/dsva-vagov-dev-tools/46769a30f69f30cb" -> null
      - port              = 3100 -> null
      - protocol          = "HTTP" -> null

      - default_action {
          - order            = 1 -> null
          - target_group_arn = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/vagov-dev-loki-tg/4fa4dfe05b161db2" -> null
          - type             = "forward" -> null
        }
    }

  # aws_cloudwatch_log_group.this will be destroyed
  - resource "aws_cloudwatch_log_group" "this" {
      - arn               = "arn:aws-us-gov:logs:us-gov-west-1:008577686731:log-group:/vagov/dev/loki" -> null
      - id                = "/vagov/dev/loki" -> null
      - name              = "/vagov/dev/loki" -> null
      - retention_in_days = 0 -> null
      - tags              = {
          - "Application" = "vagov-loki"
          - "Environment" = "dev"
        } -> null
    }

  # aws_ecs_cluster.this will be destroyed
  - resource "aws_ecs_cluster" "this" {
      - arn                = "arn:aws-us-gov:ecs:us-gov-west-1:008577686731:cluster/vagov-dev-loki-cluster" -> null
      - capacity_providers = [] -> null
      - id                 = "arn:aws-us-gov:ecs:us-gov-west-1:008577686731:cluster/vagov-dev-loki-cluster" -> null
      - name               = "vagov-dev-loki-cluster" -> null
      - tags               = {
          - "Adminstration" = "TBD"
          - "Environment"   = "DEV"
          - "Office"        = "tbd"
          - "ProjectName"   = "VA Vets.gov"
          - "ProjectShort"  = "Vets.gov"
          - "ResTag"        = "shared"
          - "Role"          = "tbd"
          - "VAECID"        = "AWG20180517003"
          - "dsva_version"  = "v2"
          - "environment"   = "dev"
          - "group"         = "dsva"
          - "managed"       = "terraform"
          - "office"        = "osva"
          - "project"       = "vagov"
          - "provider"      = "aws"
          - "region"        = "govcloud"
          - "suboffice"     = "cto"
        } -> null
    }

  # aws_ecs_service.this will be destroyed
  - resource "aws_ecs_service" "this" {
      - cluster                            = "arn:aws-us-gov:ecs:us-gov-west-1:008577686731:cluster/vagov-dev-loki-cluster" -> null
      - deployment_maximum_percent         = 100 -> null
      - deployment_minimum_healthy_percent = 0 -> null
      - desired_count                      = 1 -> null
      - enable_ecs_managed_tags            = false -> null
      - health_check_grace_period_seconds  = 0 -> null
      - iam_role                           = "aws-service-role" -> null
      - id                                 = "arn:aws-us-gov:ecs:us-gov-west-1:008577686731:service/vagov-dev-loki-service" -> null
      - launch_type                        = "FARGATE" -> null
      - name                               = "vagov-dev-loki-service" -> null
      - platform_version                   = "LATEST" -> null
      - propagate_tags                     = "NONE" -> null
      - scheduling_strategy                = "REPLICA" -> null
      - tags                               = {} -> null
      - task_definition                    = "arn:aws-us-gov:ecs:us-gov-west-1:008577686731:task-definition/vagov-dev-loki:6" -> null

      - deployment_controller {
          - type = "ECS" -> null
        }

      - load_balancer {
          - container_name   = "vagov-dev-loki" -> null
          - container_port   = 3100 -> null
          - target_group_arn = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/vagov-dev-loki-tg/4fa4dfe05b161db2" -> null
        }

      - network_configuration {
          - assign_public_ip = false -> null
          - security_groups  = [
              - "sg-0cb8d3759ea990638",
            ] -> null
          - subnets          = [
              - "subnet-2c4e176a",
              - "subnet-8d3dd6e9",
              - "subnet-d6f512a0",
            ] -> null
        }
    }

  # aws_ecs_task_definition.this will be destroyed
  - resource "aws_ecs_task_definition" "this" {
      - arn                      = "arn:aws-us-gov:ecs:us-gov-west-1:008577686731:task-definition/vagov-dev-loki:1" -> null
      - container_definitions    = jsonencode(
            [
              - {
                  - cpu          = 0
                  - environment  = []
                  - essential    = true
                  - image        = "nginx:latest"
                  - mountPoints  = []
                  - name         = "vagov-dev-loki"
                  - portMappings = [
                      - {
                          - containerPort = 3100
                          - hostPort      = 3100
                          - protocol      = "tcp"
                        },
                    ]
                  - volumesFrom  = []
                },
            ]
        ) -> null
      - cpu                      = "256" -> null
      - execution_role_arn       = "arn:aws-us-gov:iam::008577686731:role/vagov-dev-loki-task-execution-role" -> null
      - family                   = "vagov-dev-loki" -> null
      - id                       = "vagov-dev-loki" -> null
      - memory                   = "512" -> null
      - network_mode             = "awsvpc" -> null
      - requires_compatibilities = [
          - "FARGATE",
        ] -> null
      - revision                 = 1 -> null
      - tags                     = {} -> null
      - task_role_arn            = "arn:aws-us-gov:iam::008577686731:role/vagov-dev-loki-task-role" -> null
    }

  # aws_iam_role.task_execution will be destroyed
  - resource "aws_iam_role" "task_execution" {
      - arn                   = "arn:aws-us-gov:iam::008577686731:role/vagov-dev-loki-task-execution-role" -> null
      - assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRole"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "ecs-tasks.amazonaws.com"
                        }
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - create_date           = "2020-09-01T15:16:46Z" -> null
      - force_detach_policies = false -> null
      - id                    = "vagov-dev-loki-task-execution-role" -> null
      - max_session_duration  = 3600 -> null
      - name                  = "vagov-dev-loki-task-execution-role" -> null
      - path                  = "/" -> null
      - tags                  = {} -> null
      - unique_id             = "AROAQD72FDTFVT366PIKZ" -> null
    }

  # aws_iam_role.task_role will be destroyed
  - resource "aws_iam_role" "task_role" {
      - arn                   = "arn:aws-us-gov:iam::008577686731:role/vagov-dev-loki-task-role" -> null
      - assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRole"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "ecs-tasks.amazonaws.com"
                        }
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - create_date           = "2020-09-01T15:16:46Z" -> null
      - force_detach_policies = false -> null
      - id                    = "vagov-dev-loki-task-role" -> null
      - max_session_duration  = 3600 -> null
      - name                  = "vagov-dev-loki-task-role" -> null
      - path                  = "/" -> null
      - tags                  = {} -> null
      - unique_id             = "AROAQD72FDTFYNJIOS2HQ" -> null
    }

  # aws_iam_role_policy.dynamodb will be destroyed
  - resource "aws_iam_role_policy" "dynamodb" {
      - id     = "vagov-dev-loki-task-role:DynamodbAccess" -> null
      - name   = "DynamodbAccess" -> null
      - policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = [
                          - "dynamodb:UpdateTable",
                          - "dynamodb:UpdateItem",
                          - "dynamodb:UntagResource",
                          - "dynamodb:TagResource",
                          - "dynamodb:Query",
                          - "dynamodb:PutItem",
                          - "dynamodb:ListTagsOfResource",
                          - "dynamodb:GetItem",
                          - "dynamodb:DescribeTable",
                          - "dynamodb:DeleteTable",
                          - "dynamodb:DeleteItem",
                          - "dynamodb:CreateTable",
                          - "dynamodb:BatchWriteItem",
                          - "dynamodb:BatchGetItem",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws-us-gov:dynamodb:us-gov-west-1:008577686731:table/dsva-vagov-dev-loki*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = "dynamodb:ListTables"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - role   = "vagov-dev-loki-task-role" -> null
    }

  # aws_iam_role_policy.s3 will be destroyed
  - resource "aws_iam_role_policy" "s3" {
      - id     = "vagov-dev-loki-task-role:S3Access" -> null
      - name   = "S3Access" -> null
      - policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = [
                          - "s3:PutObject",
                          - "s3:ListBucket",
                          - "s3:GetObject",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws-us-gov:s3:::dsva-vagov-dev-loki/*",
                          - "arn:aws-us-gov:s3:::dsva-vagov-dev-loki",
                        ]
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - role   = "vagov-dev-loki-task-role" -> null
    }

  # aws_iam_role_policy.ssm_parameter_access_policy will be destroyed
  - resource "aws_iam_role_policy" "ssm_parameter_access_policy" {
      - id     = "vagov-dev-loki-task-execution-role:vagov-dev-loki-ssm-parameter-access" -> null
      - name   = "vagov-dev-loki-ssm-parameter-access" -> null
      - policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "ssm:DescribeParameters"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = "ssm:GetParameters"
                      - Effect   = "Allow"
                      - Resource = "arn:aws-us-gov:ssm:us-gov-west-1:008577686731:parameter/vagov/dev/loki/*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = "kms:Decrypt"
                      - Effect   = "Allow"
                      - Resource = "arn:aws-us-gov:kms:us-gov-west-1:008577686731:alias/aws/ssm"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - role   = "vagov-dev-loki-task-execution-role" -> null
    }

  # aws_iam_role_policy_attachment.ecs_task_execution will be destroyed
  - resource "aws_iam_role_policy_attachment" "ecs_task_execution" {
      - id         = "vagov-dev-loki-task-execution-role-20200901151647137000000001" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy" -> null
      - role       = "vagov-dev-loki-task-execution-role" -> null
    }

  # aws_lb_target_group.this will be destroyed
  - resource "aws_lb_target_group" "this" {
      - arn                                = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/vagov-dev-loki-tg/4fa4dfe05b161db2" -> null
      - arn_suffix                         = "targetgroup/vagov-dev-loki-tg/4fa4dfe05b161db2" -> null
      - deregistration_delay               = 10 -> null
      - id                                 = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/vagov-dev-loki-tg/4fa4dfe05b161db2" -> null
      - lambda_multi_value_headers_enabled = false -> null
      - load_balancing_algorithm_type      = "round_robin" -> null
      - name                               = "vagov-dev-loki-tg" -> null
      - port                               = 3100 -> null
      - protocol                           = "HTTP" -> null
      - proxy_protocol_v2                  = false -> null
      - slow_start                         = 0 -> null
      - tags                               = {} -> null
      - target_type                        = "ip" -> null
      - vpc_id                             = "vpc-b50046d0" -> null

      - health_check {
          - enabled             = true -> null
          - healthy_threshold   = 3 -> null
          - interval            = 30 -> null
          - matcher             = "200" -> null
          - path                = "/ready" -> null
          - port                = "3100" -> null
          - protocol            = "HTTP" -> null
          - timeout             = 5 -> null
          - unhealthy_threshold = 3 -> null
        }

      - stickiness {
          - cookie_duration = 86400 -> null
          - enabled         = false -> null
          - type            = "lb_cookie" -> null
        }
    }

  # aws_s3_bucket.this will be destroyed
  - resource "aws_s3_bucket" "this" {
      - acl                         = "private" -> null
      - arn                         = "arn:aws-us-gov:s3:::dsva-vagov-dev-loki" -> null
      - bucket                      = "dsva-vagov-dev-loki" -> null
      - bucket_domain_name          = "dsva-vagov-dev-loki.s3.amazonaws.com" -> null
      - bucket_regional_domain_name = "dsva-vagov-dev-loki.s3.us-gov-west-1.amazonaws.com" -> null
      - force_destroy               = false -> null
      - hosted_zone_id              = "Z31GFT0UA1I2HV" -> null
      - id                          = "dsva-vagov-dev-loki" -> null
      - region                      = "us-gov-west-1" -> null
      - request_payer               = "BucketOwner" -> null
      - tags                        = {
          - "Adminstration" = "TBD"
          - "Environment"   = "DEV"
          - "Office"        = "tbd"
          - "ProjectName"   = "VA Vets.gov"
          - "ProjectShort"  = "Vets.gov"
          - "ResTag"        = "shared"
          - "Role"          = "tbd"
          - "VAECID"        = "AWG20180517003"
          - "dsva_version"  = "v2"
          - "environment"   = "dev"
          - "group"         = "dsva"
          - "managed"       = "terraform"
          - "office"        = "osva"
          - "project"       = "vagov"
          - "provider"      = "aws"
          - "region"        = "govcloud"
          - "suboffice"     = "cto"
        } -> null

      - versioning {
          - enabled    = false -> null
          - mfa_delete = false -> null
        }
    }

  # aws_security_group.lb will be destroyed
  - resource "aws_security_group" "lb" {
      - arn                    = "arn:aws-us-gov:ec2:us-gov-west-1:008577686731:security-group/sg-038a5eeeceea30362" -> null
      - description            = "Managed by Terraform" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-038a5eeeceea30362" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "10.247.96.0/23",
                  - "10.247.91.128/26",
                  - "10.247.142.64/26",
                ]
              - description      = ""
              - from_port        = 3100
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 3100
            },
        ] -> null
      - name                   = "vagov-dev-loki-lb-sg" -> null
      - owner_id               = "008577686731" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {} -> null
      - vpc_id                 = "vpc-b50046d0" -> null
    }

  # aws_security_group.task will be destroyed
  - resource "aws_security_group" "task" {
      - arn                    = "arn:aws-us-gov:ec2:us-gov-west-1:008577686731:security-group/sg-0cb8d3759ea990638" -> null
      - description            = "Managed by Terraform" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-0cb8d3759ea990638" -> null
      - ingress                = [
          - {
              - cidr_blocks      = []
              - description      = ""
              - from_port        = 3100
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = [
                  - "sg-b322d9d4",
                ]
              - self             = false
              - to_port          = 3100
            },
        ] -> null
      - name                   = "vagov-dev-loki-task-sg" -> null
      - owner_id               = "008577686731" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {} -> null
      - vpc_id                 = "vpc-b50046d0" -> null
    }

  # module.internal-tools-alb.aws_alb.internal-tools will be updated in-place
  ~ resource "aws_alb" "internal-tools" {
        arn                        = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/dsva-vagov-dev-tools/46769a30f69f30cb"
        arn_suffix                 = "app/dsva-vagov-dev-tools/46769a30f69f30cb"
        dns_name                   = "internal-dsva-vagov-dev-tools-1729619844.us-gov-west-1.elb.amazonaws.com"
        drop_invalid_header_fields = false
        enable_deletion_protection = true
        enable_http2               = true
        id                         = "arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/dsva-vagov-dev-tools/46769a30f69f30cb"
        idle_timeout               = 60
        internal                   = true
        ip_address_type            = "ipv4"
        load_balancer_type         = "application"
        name                       = "dsva-vagov-dev-tools"
      ~ security_groups            = [
          - "sg-038a5eeeceea30362",
            "sg-b322d9d4",
        ]
        subnets                    = [
            "subnet-2c4e176a",
            "subnet-8d3dd6e9",
            "subnet-d6f512a0",
        ]
        tags                       = {
            "Adminstration" = "TBD"
            "Environment"   = "DEV"
            "Office"        = "tbd"
            "ProjectName"   = "VA Vets.gov"
            "ProjectShort"  = "Vets.gov"
            "ResTag"        = "shared"
            "Role"          = "tbd"
            "VAECID"        = "AWG20180517003"
            "dsva_version"  = "v2"
            "environment"   = "dev"
            "group"         = "dsva"
            "managed"       = "terraform"
            "office"        = "osva"
            "project"       = "vagov"
            "provider"      = "aws"
            "region"        = "govcloud"
            "suboffice"     = "cto"
        }
        vpc_id                     = "vpc-b50046d0"
        zone_id                    = "Z33AYJ8TM3BH4J"

        access_logs {
            enabled = false
        }

        subnet_mapping {
            subnet_id = "subnet-2c4e176a"
        }
        subnet_mapping {
            subnet_id = "subnet-8d3dd6e9"
        }
        subnet_mapping {
            subnet_id = "subnet-d6f512a0"
        }

        timeouts {}
    }

Plan: 0 to add, 2 to change, 15 to destroy.```
