### ISSUE TITLE
[UI] Filtering and Sorting Questionnaire List

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#17804]
## User Story
- As a Veteran, I want to be able to quickly get to my completed questionnaire of interest. I need to sort and filter through my historical record of all completed questionnaires.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A wireframes set for filtering and sorting will be delivered at either 
- the fidelity required to user test this functionality or 
- with the technical specifications needed for engineering to implement said feature.

Suggestions on filters from last [usability test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md):
- specialty
- type of questionnaire
- date (particularly year)

## Tasks
- [ ] Do an analysis of other filtering and sorting interfaces across VA.gov
- [ ] Coordinate with platform
- [ ] Finalize detailed mockup and callouts of filtering and sorting
- [ ] Write [accessibility review ticket - follow Dev Intent Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+jenstrickland&labels=508%2FAccessibility%2C+development+review%2C+product+support&template=vsa_request_dev_review.md&title=Request+a+VSA+dev+intent+or+spot+check+review+for+ENTER_PRODUCT_NAME)
- [ ] Incorporate or document accessibility feedback into the wireframes for the team review
- [ ] Complete a content review by sending Peggy Gannon a message within the vfs-platform-support channel and tagging her within the comments section of this story

## Acceptance Criteria
- [ ] UI review meeting with product/team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Published mockup link exists and it is added/updated within the product feature outline
- [ ] Accessibility review is complete and feedback is incorporated into the mockup
- [ ] Feedback from content is incorporated into the mockup
