### ISSUE TITLE
[UI] Appointment Status on Questionnaire List

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#17805]
## User Story
- As a Veteran, I am interested in viewing the different statuses of my questionnaires, such as...
  - in-progress questionnaires for canceled appointments, because it might help with rescheduling and filling out the questionnaire for the rescheduled appointment.
  - no shows
  - in-progress versus new
  - any other statuses (engineering will look into statuses more)

Questionnaire Response status definitions: https://www.hl7.org/fhir/valueset-questionnaire-answers-status.html

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A wireframes set for will be delivered 
- with the fidelity required to usability test, or
- with the technical specifications needed for engineering to implement said feature.

The following status use cases will be explored:
- not submitted, but canceled appointments,
- no shows
- in-progress versus new
- any other statuses (engineering will look into statuses more)

During the last [usability test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md), the following items were found.
- Veterans are not interested in seeing not submitted questionnaires, except when they started the questionnaire, then the appointment was canceled.
  - Only 30% of participants had an interest in viewing not submitted questionnaire information on a list of all their questionnaires.
    - One participant only wanted to see not submitted questionnaires, so they knew their appointment date. The value was with the appointment information and not the questionnaire information.
  - Eight out of 10 participants are interested in viewing in-progress questionnaires for canceled appointments, because they believe it might help with rescheduling and filling out the questionnaire for the rescheduled appointment.
    - Four out of four participants wanted additional text, such as “Your answers will be available for the next X days,” if the not submitted but cancel appointment questionnaires would eventually disappear.
- 70% of participants understood the difference between the buttons (Answer Questions versus Continue Questions) on the Questionnaire list (To do tab).
  - However, most of the 70% had to be explicitly asked about the buttons before they determined the difference.
  - Even the other 30% knew that they had to click on either button to finish the questionnaires.

## Tasks
- [x] Brainstorm different solutions
- [x] Present options to product team
- [x] Finalize detailed mockup and callouts

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
For reference, this is how VAOS is currently planning on displaying status and sorting appointments (they only really have wording in the UI to denote canceled).
![Screen Shot 2021-01-07 at 2.29.34 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8439add6-ba79-49bc-b1b0-91c1d002b554)

This is how the mobile app currently plans to display appointment status. They have a backlog item to add an icon to make canceled more accessible (not relying on just color).
![Screen Shot 2021-01-07 at 2.01.46 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/39b9c9de-d210-41f1-a3e6-5820c00f6c4b)

**Comment by kristenmcconnell** [comment]
Other inspiration (debt letters and claims/appeal tracker)

![Screen Shot 2021-01-08 at 11.21.14 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/13ea2027-4271-4721-9a22-dcf935bf4417)![Screen Shot 2021-01-08 at 11.43.10 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/a05dfbae-5f7b-468f-8f5c-f65189d67eb3)![Screen Shot 2021-01-08 at 11.49.49 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/445e819a-5586-49fa-88fe-cc0284efb163)

**Comment by kristenmcconnell** [comment]
Possible designs that I want to discuss on Monday.![Status Exploration.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/d45513ba-2cf1-4ace-89be-ee13e902f858)

**Comment by kristenmcconnell** [comment]
Met with team on January 11, 2021. Going to complete another iteration.

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mlighdc I completed another iteration on questionnaire status based upon our last discussion (see the attached images). I believe that these designs address the rescheduled appointment and not just canceled scenario that Amanda mentioned. I think that the layout issues have also been addressed. 

I have been contemplating one item that I definitely would like feedback on. Should we remove the time from the "completed by" and "submitted on" information? We discussed this briefly during our last meeting. Removing the time might help a Veteran to not confuse these with actual appointment information.

Let me know what you both think.

![Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/2ee573a1-c501-4117-9704-8e767e3f0323)
![Mobile Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/13052f5d-4c27-48a1-816b-ff51b7f61b69)!![Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/25dfa6ff-84d0-428b-b91a-e7ffa9f9e90a)
![Mobile Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/913379a6-5276-4a57-b89a-c7463f0f57c3)

**Comment by sshein** [comment]
I like the way these are looking - not sure where you're at in terms of final designs of the statuses, but one little note that all caps are hard for folks with visual impairments to read, so we try to avoid it unless it's necessary - "Readability is reduced with all caps because all words have a uniform rectangular shape, meaning readers can't identify words by their shape." https://accessibility.huit.harvard.edu/design-readability

**Comment by kristenmcconnell** [comment]
@sshein Good catch. I was copying VAOS and it became an oversight. I'll mention it to VAOS as well.

**Comment by kristenmcconnell** [comment]
Peter Russo and I talked yesterday about some status feedback he received during his collab cycle. As a result, I created the following wireframe utilizing the label component.![Labels - After 2nd usability - Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/e82970e1-32e7-4982-b149-1f93593fcff5)

Peter and I took the topic of statuses to DEPO Design Hours. I will check the color contrast on the labels as a result. Emily Waggoner plans to take the above audit to the design council.

**Comment by kristenmcconnell** [comment]
Discussion on possible accessibility improvements to the label component, which we now plan to utilize to show status, can be viewed here: https://dsva.slack.com/archives/C0NGDDXME/p1611158823044100

**Comment by kristenmcconnell** [comment]
After syncing with Peter and platform, here are the current designs under content review by Peggy Gannon.

They can also be viewed at: https://zpl.io/VOOek8j or https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780

Changes to the label component include: 14  Bold font, 0.5 character spacing. and 4px spacing underneath. 
Currently it is being tested by Peter Russo on VAOS.

![After 2nd usability - Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/b1ee2aeb-0571-4999-8066-1f743866287e)
![After 2nd usability - Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ff57b936-30d9-42e9-98ba-bd31e7934719)
![After 2nd usability - Mobile Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/6d741d88-24f1-49f5-bdf1-1fc2b065c4ea)
![After 2nd usability - Mobile Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/c1072d52-24be-4ff5-a576-3e6626b685c1)

**Comment by kristenmcconnell** [comment]
Updated based upon design and content feedback. 
![After 2nd usability - Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/4b754561-2e5f-41c0-8d0e-c0ed8d23d2a2)
![After 2nd usability - Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/63eca377-6419-47d3-8ae5-c97038d3b8b8)
![After 2nd usability - Mobile Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8644c3cf-3f22-4ce4-a63d-3147c0ee2376)
![After 2nd usability - Mobile Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/db24400c-ce5a-4f03-af1a-9e06a9059f50)

**Comment by kristenmcconnell** [comment]
Updated after talking with Amanda and Mark. Peggy reviewed the additional sentence on the Canceled appointment, in-progress questionnaire card.

![After 2nd usability - Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/821619f7-4e0c-424a-8109-9a7a25768b2e)
![After 2nd usability - Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8702e1a5-eabb-4c6b-bdcd-ebcbc27e5eef)
![After 2nd usability - Mobile Questionnaire List - Completed.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/4e5c0c30-fe8d-420c-ac8b-09a0a7fa2544)
![After 2nd usability - Mobile Questionnaire List - To Do.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/abb1b900-0778-49e9-aae8-8c50cfa342ba)
