### ISSUE TITLE
[UNPLANNED] 686c Set Child Previously Married Indicator Flag and Relationship Type

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#17810]
## Background
During testing, we discovered that when reporting the marriage of a child under 18, the child previously married indicator must be set to `Y` and the relationship type must be set to `Biological`.

## Considerations
- The child previously married indicator flag needs to be set manually (instead of from the form data payload) for this specific workflow (report the marriage of a child under 18).

## Tasks
- [x] Check to see if the user is reporting the marriage of a child under 18.
- [x] Update the child previously married indicator to `Y`.
- [x] Update the relationship type to `Biological`.

## Acceptance Criteria
- [x] The correct relationship type and child previously married indicator are being sent to BGS.
- [x] Write a test for coverage, if needed
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5564
