### ISSUE TITLE
Activate Holiday Code Freeze on COB December 23, 2021 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17823]
## Description
A member of the Ops team needs to follow the Holiday Code Freeze procedures at close of business (COB) on December 23, 2021 

## Background/context/resources
[Holiday Code Freeze standard operating procedures](https://github.com/department-of-veterans-affairs/devops/blob/8daa049cba3cf57753f750fb0274a9f1d98057d4/docs/StandardOperatingProcedures/HolidayCodeFreeze.md)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Disable automatic releases in Jenkins according to SOP above when freeze begins
- [x] Re-enable automatic releases in Jenkins according to SOP above when freeze completes

## Definition of Done
- [x] The Holiday Code Freeze will be activated 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by mydesignrocks** [comment]
followed these guidelines: https://github.com/department-of-veterans-affairs/devops/blob/8daa049cba3cf57753f750fb0274a9f1d98057d4/docs/StandardOperatingProcedures/HolidayCodeFreeze.md

**Comment by jhouse-solvd** [comment]
closing.
