### ISSUE TITLE
PACT Broker - TIC issues making pact broker inaccessible 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17821]
## Description
Intermittent connectivity issues through the TIC have resulted in PACT broke being inaccessible via their URL / web portal. Demian is in touch with Gateway Ops and they've asked that he also submit a Service Now ticket. 

## Background/context/resources
None

## Technical notes
None

---
## Tasks
- [ ] Create a root cause analysis document
- [ ] Update documentation in va.gov-team repo to describe a process for resolving this issue in the most timely and efficient way possible in the future

## Definition of Done
- [ ] Updated documentation is available in va.gov-team with details on the cause of and solution to this intermittent issue

**Comment by meganhkelley** [comment]
Following

**Comment by dginther** [comment]
There seemed to be an intermittent DNS issue or something else, and it ended up not being the TIC interfering with the requests. I modified the code used to configure the revproxy and it solved the issue. We should be good to go moving forward.
