### ISSUE TITLE
[CONSIDER] Facility images available via Lighthouse

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17828]
## Issue Description
As a Veteran, I want to see the facility's facade so I can more easily find the location when I visit. 
As a Veteran, I want to see the facility's facade presented in the search results so I can differentiate facilities with similar names or addresses. 

To make this possible, we will need the images to be available via Lighthouse API

---
## Tasks
- [ ] Work with Lighthouse to make facility images available to Facility Locator 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
