### ISSUE TITLE
Redirect GA dashboards to Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17836]
## Issue Description
With the GA Event Action data scrub, we anticipate VFS teams to have custom reports and dashboards in Google Analytics that they'll want recreated with the missing data. We believe that we can redirect these dashboards to Domo, and that this can serve as an opportunity for VFS teams to look at their analytics on a more strategic level and point them to requesting KPI dashboards.

---
## Tasks
- [ ] List all of requested GA reports/dashboards for rebuilding in Domo
- [ ] Redirect teams where possible to setting up KPI setting dashboards
- [ ] Set up 

This issue may end up being a placeholder for VFS team driven issues, and can be closed based on new priorities in 2021.

## Acceptance Criteria
- [ ] VFS teams have access to the data they have been looking at in Google Analytics
