### ISSUE TITLE
Flag missing GA data in the Covid Dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17834]
## Issue Description
With the GA Event Action data scrub, data in the historical Covid dashboard will be missing since many of those charts are not pointing to BigQuery instead of Google Analytics. While this is a historical dashboard, we have data to suggest that folks are viewing the dashboard.

How might we ensure that people who are viewing the historical Covid dashboard know the status of the data involved?

---
## Tasks
- [ ] Add a flag to the historical covid dashboard indicating lack of maintenance & missing data
- [ ] Stretch: Redirect charts in the Covid dashboard from GA to BigQuery

## Acceptance Criteria
- [ ] Historical Covid dashboard users
