### ISSUE TITLE
Adjust Applicant Information Post Login 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17831]
## Background
After logging in, the personal info the VA knows about is shared and the Veteran is able to continue on if correct, or call a number to get the info corrected.  If you log in without any info, nothings shows.

## Considerations

<details>

<summary>Expand to see blank info screen</summary>

![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/4b4a7a0b-3761-4e47-ac9f-b62d49c8ec35)

</details>

- If this happens, the next step for the Veteran should be: 
  - Check for LOA level:
    - If LOA1 -> unauth'd 
      - Hook fires on intro page, we could read from profile (`authcontext`) and give them the page list that is for the unauth experience
    - If LOA3 -> Proceed, as per usual  
 - We will be doing this for CH31 when that time comes, hopefully this work will be helpful for that.

## Tasks
- [x] Determine best path forward (See notes above)
- [x] Implement logic on the CH36 form 

## Acceptance Criteria
- [x] The info screen has a contingency for auth'd users who have no profile info
- [x] A PR has been requested for merging, as needed

**Comment by jason-gcio** [comment]
- Check for LOA level:
  - If LOA1 -> unauth'd
  - If LOA3 -> Proceed, as per usual

Hook fires on intro page, we could read from profile (`authcontext`) and give them the page list that is for the unauth experience
