### ISSUE TITLE
Integrating canned suggestions for Type Ahead

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17844]
## Description

Initial Type Ahead POC launched using suggestions generated from search.go algorythm. At the time there was a bug which was preventing suggestions from falling off after 30 days. Search.gov addressed that bugs which removed suggestions and motivated us to pivot back to creating a list of suggestion terms that will be hardcoded onto the suggestion database that search.gov will use in typeahead experience.  

## Tasks

- [x] List of suggestions are being creating in #21325, that list when ready needs to be sent over to search.gov for integration
- [x] Search.gov integrate spreadsheet into type ahead experience. 
- [x] SD team to test integration to ensure terms have been added and experience is working as expected

## Definition of Done

- [x] Typeahead suggestions list has been added allowing suggestions to appear to users

**Comment by denisecoveyduc** [comment]
During our planning call (Feb 10th) we decided that the new Global Blacklisting efforts will take priority over canned suggestions and potential even replace the need for this since adding a term to the suggestions list achieves the same result.

**Comment by denisecoveyduc** [comment]
Based on discussions with search.gov this has been deprioritized  and removed from Typeahead 1.0 release.
