### ISSUE TITLE
Footer - Misrouted VAOS calls to VA Mobile Help Desk

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17852]
## Issue Description

Note from Help Desk
> FYI - This blurb on the VA.gov VAOS interface is confusing the Veterans. They are calling the 877-470-5947 VA Mobile Health Help Desk to make appointments when they get an error with the tool. The second line tells them correctly to call their local VAMC but we are still getting a lot of appointment calls on the mobile line. It may help to use verbiage like “to report a technical issue with using the va appointments tool contact…etc.”

![Screen Shot 2020-12-23 at 8.41.43 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/6c5bb6d0-8fe2-4b59-a11f-e954e2aa7994)

---
## Tasks
- [ ] Update first two sections of footer. Swap the lines.

## Acceptance Criteria
- [ ] CONTENT - Copy matches the following guidance:

> Need help?
If you need help scheduling an appointment, please call your VA or community care health facility.
{link} Find your health facility’s phone number
To report a technical issue with the VA appointments tool, or if you have a question about using the tool, please call 877-470-5947[hyperlink] (TTY: 711[hyperlink]). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.

- [ ] Bottom of footer (VVC section) remains the same

**Comment by peggygannon** [comment]
Hi, @laurenernest 

Question:  did you get any feedback from the Help Desk that we should also update the static landing page to make this language more clear and parallel with the tool? (screenshot below)

--------

Here is my recommendation to make this more clear. I recommend swapping the first and two lines, so the "scheduling" information come first in the footer. 

**Need help?**

If you need help scheduling an appointment, please call your VA or community care health facility.
{link} Find your health facility’s phone number

To report a technical issue with the VA appointments tool, or if you have a question about using the tool, please call 877-470-5947[hyperlink] (TTY: 711[hyperlink]). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.


-------


VA appointment static landing page (https://www.va.gov/health-care/schedule-view-va-appointments/)

![2021-01-04.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/d3eb5273-ad50-45d1-92b1-9a4d406b9e33)

**Comment by laurenernest** [comment]
@peggygannon No, we didn't get feedback about the static page. The reorder makes sense!

@clantosswett As far as you know, should there be any phone number changes in the VAOS footer? Currently, we're directing to 877-470-5947 for technical support.

**Comment by laurenernest** [comment]
Number confirmed in this [thread](https://dsva.slack.com/archives/CMNQT72LX/p1602170914092600). Moving to dev.
