### ISSUE TITLE
Refine Process Flow for Search for a VA Representative

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17857]
### Goal
Design initial user and process flows for representative search.

### Considerations
- Review current search tools and patterns on VA.gov
- Determine search parameters and filtering criteria
- Position search tool in context of View/Search/Appoint process flow

### Tasks
- [x] Include team in discussion
- [x] Revise and refine current usecase and process flow diagrams
- [x] Revise and refine initial search screens
- [x] Check in with Josh on edits

### Acceptance criteria
- [x] Usecase diagram revised and refined
- [x] Process flow diagram revised and refined
- [x] Search screen mockups revised and refined

**Comment by sporeboy** [comment]
Discussed Search Rep with Josh and Beth. Redesigned Search Rep tool with mobile-first strategy. Took wizard-like step-by-step approach.

New mockups: https://xd.adobe.com/view/b80b0931-826b-413a-9b07-1efff71cae16-ed58/

**Comment by sporeboy** [comment]
Went through design intent review. Initial revisions made to mocks here: https://xd.adobe.com/view/b80b0931-826b-413a-9b07-1efff71cae16-ed58/

**Comment by sporeboy** [comment]
User flow options--as well as isolated user flow to search tool--are here: https://xd.adobe.com/view/d38776dd-93cb-44be-a994-2c6f414df1bc-86d4/
