### ISSUE TITLE
Implement design intent feedback for View Representative

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17856]
### Goal
Review and implement feedback from design intent meeting. Areas to review include Design, Content and Accessibility. Update mockups to reflect feedback.

### Considerations
- View tool built to conform to design council recommendations
- May need to reconcile feedback from design intent call with current patterns and new "view tool" layout
- Some discussion needed around placement of tools vs. a logged-in profile flow
- View representative functionality must work with Search and Appoint features

### Tasks
- [x] Establish which feedback is the latest (Shawna vs Design Intent)
- [x] Review and implement design feedback
- [x] Review and implement content feedback
- [x] Review and implement accessibility feedback

### Acceptance criteria
- [x] Mockups (or prototypes) reflect feedback from Design, Content and Accessibility

**Comment by sporeboy** [comment]
WIP changes here: https://xd.adobe.com/view/e27b7e71-d920-4bcd-9e81-dc62a9665d5e-b728/

- Content changes made
- Closed state for TMM accordion
- Blue button implemented

Working on alternate states and new content.
