### ISSUE TITLE
Define Search User Journey

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#17868]
## Description

As a product team tasked with looking at the search experience on va.gov we would like to understand more about the journey  veterans, their family members, caregivers take when looking for information on va.gov.  

---

## Tasks

- [x] Collect any/all Information we can find that may aid in defining a users search experience. Information from VAPO discussions, other research sessions, persona information etc. 
- [x] Collect information from user research sessions to aid in the creation of a user journey 
- [x] Review journey with search and discovery team members in a meeting where we can discuss and identify any gaps in our understanding that may require further clarification or exploration. 

## Definition of Done

- [x] Search and discovery team members collectively have a good understanding on how veterans are exploring va.gov for information and know what implications that has to figure development and improvements.

**Comment by denisecoveyduc** [comment]
Established a user journey that outlines the veteran experience on va.gov in relation to searching for content and information. User Flow was captured in Miro

Associated screenshot. - for live version proceed to Miro link: https://miro.com/app/board/o9J_lY_QTys=/ 

<img width="1656" alt="Search User Journey" src="https://user-images.githubusercontent.com/72393866/106036263-16008280-60a3-11eb-85fb-febc37c63853.png">
