### ISSUE TITLE
Describe LoE for making changes to diary web entries

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17863]
## Background
A large part of the dependency verification is to make a change in the VA's system and we need to understand how to WRITE to that system.  

## Consider
- We should be asking for verification on dependents if they are stale for more than a year
- Upon a WRITE to the diary entry, we need to submit a Form 538 on behalf of the Veteran and save it in the eFolder.
  - Bio info and a check box
- [Investigation notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16106)

## Tasks
- [x] Gain access to system
- [x] Check with Linda and/or Shane about this
- [x] Determine how to WRITE a diary entry when a Veteran confirms that the dependents in their account is updated.

## Acceptance Criteria
- [x] A path forward has been documented 

**Next steps**  
- [ ] A POC can be shared

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/documentation/bgs-diaries-service.md

**Comment by kathleencrawford** [comment]
A POC has not been created for this because the updateDiaries function is not currently working in Linktest.  The BGS team is working on troubleshooting this issue.
