### ISSUE TITLE
Find a Form - Add link to Online Tool from  Form 21-4138 Detail Page

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#17877]
## Issue Description
Add an Online Tool CTA link from the Form 21-4138 page (https://www.va.gov/find-forms/about-form-21-4138/) to the _Upload evidence to support your disability claim_ tool at https://www.va.gov/disability/upload-supporting-evidence/

---
## Tasks
- [ ] Add link to form detail page via CMS

## Acceptance Criteria
- [ ] A working Online Tool link is displayed on the Form Detail page for 21-4138
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO I generated this ticket as a reminder to me to update this Form with an online tool link via the CMS.  No dev required.

**Comment by MarciMcGuireGCIO** [comment]
Hi @johnhashva , just ran across this issue.  Do you know if that new tool has launched?

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO thanks for the reminder.  Just added this link to the Form details page via CMS.  Should go live by tomorrow.  Once I validate in production I will close this ticket.
