### ISSUE TITLE
FSR Wizard Flow + Content Draft 2

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#17879]
## Issue Description
Finalize FSE Wizard flow and content, pending feedback from DMC in an email sent 12/28.

---
## Tasks
- [x] Incorporate changes and improvements from SMEs
- [x] Create GH page 
- [ ] Create FE ticket

## Acceptance Criteria
- [x] Work documented in GH and linked in this ticket
- [ ] FE ticket created and linked in this ticket

**Comment by rebeccawalsh** [comment]
@DanielleThierryUSDSVA 

Here's the current iteration of the wizard mapping / content work. We're still waiting on more feedback from the DMC to determine if the flow is correct and complete and any more context to add to the content before shaping it up.

Tried putting it in Github, but the table doesn't allow for much formatting! [Link to GH]()

You can see the .docx with more comments attached here.[https://app.zenhub.com/files/133843125/dd7bb170-5645-41a2-acdd-c4e30d21d4fe/download](https://app.zenhub.com/files/133843125/dd7bb170-5645-41a2-acdd-c4e30d21d4fe/download)

**Comment by rebeccawalsh** [comment]
Github link: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/design/wizard-design-content.md 

Status: DMC has not undertaken content writing work after initial rough proposals
