### ISSUE TITLE
VR&E - Ensure form numbers are accurate

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#17878]
## Description
There are two VR&E forms currently being worked on, 28-8832 and 28-1900. There is at least one instance of the incorrect form number being displayed on the confirmation page for the 28-1900 (Displays 28-8832 instead of 28-1900). Form numbers should be accurate and consistent for both 28-8832 and 28-1900 wherever they occur. 

## Considerations
- 28-1900 confirmation page - https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vre/28-1900/containers/ConfirmationPage.jsx

## Tasks
- [x] Fix above instance of incorrect form number
- [x] Search for and update any remaining instances of incorrect form numbers for chapter 31 and chapter 36

## Acceptance Criteria
- [x] All instances of form numbers reflect the actual form being filled out
- [x] Pull request has been created that addresses the issue
