### ISSUE TITLE
Update Data Layers for CH31 and CH36

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#17884]
# Background
The analytics team has requested a couple of changes for the events pushed on CH31 and CH36. The changes are - 

- changing the prefix for the forms to be `careers-employment-{form number}--` so that for example the submission event for the CH36 form looks like this `careers-employment-28-8832--submission`

- Adding an event when the flipper toggles are fired that records that event in the following spec

```javascript
recordEvent{(
  'event': 'phased-roll-out-enabled', 
  'product-description': 'Chapter 36'
});
```

## Tasks
- [ ] Make the above changes to the data layers for CH36 and CH31
- [ ] Submit a PR for the changes

## Acceptance criteria
- [ ] The above data layer changes have been made
- [ ] A PR has been submitted for review
