### ISSUE TITLE
[Content Structure] Move VISN-1 (part 2) Facilities listed in parent category "VAMC facilities" into Correct VISN-1 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17883]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-1 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**

VA Maine health care

- [ ] Togus VA Medical Center
- [ ] Caribou VA Clinic
- [ ] Calais VA Clinic
- [ ] Rumford VA Clinic
- [ ] Saco VA Clinic
- [ ] Lewiston VA Clinic
- [ ] Lincoln VA Clinic
- [ ] Bangor VA Clinic
- [ ] Portland VA Clinic
- [ ] Bingham Access Point
- [ ] Fort Kent VA Clinic
- [ ] Houlton VA Clinic

VA Manchester health care

- [ ] Manchester VA Medical Center
- [ ] Portsmouth VA Clinic
- [ ] Somersworth VA Clinic
- [ ] Conway VA Clinic
- [ ] Tilton VA Clinic

VA Providence health care

- [ ] Providence VA Medical Center
- [ ] New Bedford VA Clinic
- [ ] Hyannis VA Clinic
- [ ] Middletown VA Clinic

VA White River Junction health care

- [ ] White River Junction VA Medical Center
- [ ] Bennington VA Clinic
- [ ] Brattleboro VA Clinic
- [ ] Burlington Lakeside VA Clinic
- [ ] Littleton VA Clinic
- [ ] Keene VA Clinic
- [ ] Rutland VA Clinic
- [ ] Newport VA Clinic

## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN

**Comment by SgardnerPMP** [comment]
Completed in CMS migration PR.
