### ISSUE TITLE
[CONTENT] Translate legacy VA Atlanta (part 2) health care web pages to new VAMC-upgrade format [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17889]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Atlanta VA Medical Center legacy Site](https://www.atlanta.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-7 Content Folders](https://drive.google.com/drive/folders/1yihJnU99DrVPv6VxmYKSf3Ky4-Nypv4z)
[VISN-7 Health Service Playbooks](TBD)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
* Completed Content is written in Word Document format (Template can be found in Google Drive) and is saved referencing Medical Facility Name & Web Page Name in folder of the VA [System] Name_
**(See Part 1 for Standard Content Pages)**
*INTROS updated in the following CMS/DRUPAL pages:
**Facility page intros**

VA Atlanta health care
- [x] vha_508GN	Covington VA Clinic
- [x] vha_508GO	Northeast Cobb County VA Clinic
- [x] vha_508GP	South Cobb County VA Clinic
- [x] vha_508QB	East Point VA Clinic
- [x] vha_508QC	Henderson Mill VA Clinic
- [x] vha_508QD	Fulton County VA Clinic
- [x] vha_508QE	Gwinnett County VA Clinic
- [x] vha_508QF	Atlanta VA Clinic
- [x] vha_508QH	South Fulton County VA Clinic
- [x] vha_508QI	North DeKalb County VA Clinic
- [x] vha_508QJ	North Fulton County VA Clinic

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing System Name & Page Name_
- [ ]Pages have been cross checked by peer content writer for each of the following:
* About
* Work With Us
* Jobs & Careers
** Optional Doing Business with us
* Facility Intro pages as designated above

* Page must be saved in Content folder on Google Drive under Page reference name
