### ISSUE TITLE
[Content Structure] Move VISN-8 Facilities listed in parent category "VAMC facilities" into Correct VISN-8 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17882]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-8 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**

VA Bay Pines health care:

- [ ] C.W. Bill Young Department of Veterans 
- [ ] Affairs Medical Center
- [ ] Lee County VA Clinic
- [ ] Sarasota VA Clinic
- [ ] St. Petersburg VA Clinic
- [ ] Palm Harbor VA Clinic
- [ ] Bradenton VA Clinic
- [ ] Port Charlotte VA Clinic
- [ ] Naples VA Clinic
- [ ] Sebring VA Clinic

VA Caribbean health care:

- [ ] San Juan VA Medical Center
- [ ] Eurípides Rubio Department of Veterans 
- [ ] Affairs Outpatient Clinic
- [ ] Mayaguez VA Clinic
- [ ] Saint Croix VA Clinic
- [ ] Saint Thomas VA Clinic
- [ ] Arecibo VA Clinic
- [ ] Guayama VA Clinic
- [ ] Comerio VA Clinic
- [ ] Utuado VA Clinic
- [ ] Vieques VA Clinic

VA Miami health care:

- [ ] Bruce W. Carter VA Medical Center
- [ ] William "Bill" Kling VA Outpatient Clinic
- [ ] Miami Flagler VA Clinic
- [ ] Key West VA Clinic
- [ ] Homestead VA Clinic
- [ ] Pembroke Pines VA Clinic
- [ ] Key Largo VA Clinic
- [ ] Hollywood VA Clinic
- [ ] Deerfield Beach VA Clinic

VA North Florida health care:

- [ ] Malcom Randall VA Medical Center
- [ ] Lake City VA Medical Center
- [ ] Jacksonville 1 VA Clinic
- [ ] Valdosta VA Clinic
- [ ] Ocala VA Clinic
- [ ] Saint Augustine VA Clinic
- [ ] Sergeant Ernest I. "Boots" Thomas VA Clinic
- [ ] The Villages VA Clinic
- [ ] St. Marys VA Clinic
- [ ] Marianna VA Clinic
- [ ] Palatka VA Clinic
- [ ] Waycross VA Clinic
- [ ] Perry VA Clinic

## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN
