### ISSUE TITLE
[CONTENT] Translate legacy VA Central Alabama health care web pages to new VAMC-upgrade format [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17892]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Central Alabama VA Medical Center legacy Site](https://www.centralalabama.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-7 Content Folders](https://drive.google.com/drive/folders/1yihJnU99DrVPv6VxmYKSf3Ky4-Nypv4z)
[VISN-7 Health Service Playbooks](TBD)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
* Completed Content is written in Word Document format (Template can be found in Google Drive) and is saved referencing Medical Facility Name & Web Page Name in folder of the VA [System] Name_
* The following pages will have to be researched and created using the templates created:
- [ ] About
- [ ] Work With Us
- [ ] Jobs & Careers
*INTROS updated in the following CMS/DRUPAL pages:
**Facility page intros**

VA Central Alabama health care
- [ ] vha_619	Central Alabama VA Medical Center-Montgomery
- [ ] vha_619A4	Central Alabama VA Medical Center-Tuskegee
- [ ] vha_619GA	Columbus VA Clinic
- [ ] vha_619GB	Dothan 1 VA Clinic
- [ ] vha_619GD	Wiregrass VA Clinic
- [ ] vha_619GE	Monroe County VA Clinic
- [ ] vha_619GF	Central Alabama Montgomery VA Clinic
- [ ] vha_619QA	Dothan 2 VA Clinic
- [ ] vha_619QB	Fort Benning VA Clinic

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing System Name & Page Name_
- [ ] Pages have been cross checked by peer content writer for each of the following:
* About
* Work With Us
* Jobs & Careers
** Optional Doing Business with us
* Facility Intro pages as designated above

* Page must be saved in Content folder on Google Drive under Page reference name
