### ISSUE TITLE
Add COVID19Vaccine parameter to query (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17908]
## Issue Description
Add support for `Covid19Vaccine` service to vets-api /v1/facilities/va endpoint

NOTE: LightHouse does not yet support searching for facilities with serviceType = `Covid19Vaccine`

See [Slack](https://lighthouseva.slack.com/archives/CJ162GDDJ/p1609256977298600) for details.

---
## Tasks
- [ ] Work with Lighthouse to implement new COVID-19 vaccines field
- [ ] Put this on flipper (VA facilities COVID-19 vaccines locations) <--- Do we need this? (MPS)

## Acceptance Criteria
- [ ] When `services[]=Covid19Vaccine`is passed to a `/v1/facilities/va` request, only facilities that offer COVID-19 vaccines are returned.

**Comment by mmiddaugh** [comment]
Lighthouse work does not yet allow searchability. This effort is blocked pending this change.
