### ISSUE TITLE
Render new Appointment field on front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17917]
## Issue Description
New appointment field (which allows editor to replace default content) needs to be implemented on FE

**Phase 1:** For the first round of implementation, FE team will be required to display the 'default' appointment lead-in intro text:
> Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.

**When to display default text vs custom text**

**Implementation of the new appointment fields can be found on the `health_care_local_health_service` content type.**
Editors in the CMS will be allowed to select 3 different options for the appointment lead-in intro text `field_hservice_appt_intro_select`

1. `default_intro_text` Use default appointments intro text 
   - If default_intro_text, then FE displays: `Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first`
2. c`ustom_intro_text `Customize appointments intro text
   - If custom_intro_text then display field_hservice_appt_leadin on front end
3. `no_intro_text `No appointments intro text
   - If no_intro_text then don't display Appointment lead-in fields.
 
**Phase 2: Default text will be provided by the CMS.**

---
## Tasks
- [ ] Get replacement Appointment field name from CMS
- [ ] Ensure new field is included in GraphQL query (Check with Ethan)
- [ ] Build front end to consume GraphQL output
- [ ] Build transformer to prepare for Tome sync cutover

## Acceptance Criteria
- [ ] Front end displays whatever content is displayed in the new Appointments field in CMS
- [ ] If default_intro_text, FE displays: 
> Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first
- [ ] If custom_intro_text, FE displays display field_hservice_appt_leadin on front end.
- [ ] If no_intro_text then FE does not display Appointment lead-in fields.
- [ ] Transformer exists
- [ ] No content is lost/changed in generated page
- [ ] Cutover is not blocked

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kaise-lafrai** [comment]
Phase 1: For the first round of implementation, FE team will be required to display the 'default' appointment lead-in intro text: 

> Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.

**Details below on when to display default text vs custom text**

---
- Implementation of the the new appointment fields can be found on the `health_care_local_health_service` content type.
  - Editors in the CMS will be allowed to select 3 different options for the appointment lead-in intro text `field_hservice_appt_intro_select`
    - `default_intro_text`|Use default appointments intro text
    - `custom_intro_text`|Customize appointments intro text
    - `no_intro_text`|No appointments intro text

---
- If `default_intro_text`then display this on FE: 
    > Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.
- If `custom_intro_text` then display `field_hservice_appt_leadin` on front end.
- If `no_intro_text` then don't display Appointment lead-in fields.

**_COMING SOON_**: Phase 2: Default text will be provided by the CMS.

CC: @kevwalsh @cmaeng @swirtSJW
