### ISSUE TITLE
Bounding box radius computed as 0

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17913]
## What happened?
Urgent Care searches for 92052 does not return results. The same search using Oceanside, CA (which corresponds to 92052) returns results. 
There are community care locations in PPMS swagger.
The radius is computed as 0 based on the bounding box (may consider a minimum default radius when the bounding box calculation is 0)

## Desired behavior
Urgent care searches using zip code should return results

## Tasks
Determine root cause
Identify fix options

## Acceptance Criteria
- [ ] Search results returned for zip code are be the same as the results returned for the corresponding city and state 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
I’ve confirmed that this issue has been pushed to staging, but we are still getting 0 results on staging when searching for urgent care in 92052. This is due to lack of data in staging. The same API query against prod returns results
