### ISSUE TITLE
GA: Create Custom dimension for Service Provider tracking

### ISSUE THREAD

**Issue by HikeBandit** [department-of-veterans-affairs/va.gov-team#17929]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Sherri De Loof, Mark Stephens, Margery Spears

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._

    Sorry, we do not have access to the DSVA Slack Channel. Email addresses:
    sherri.deloof@va.gov
    mark.r.stephens@comcast.net
    margery@searchenginecatalyst.com
    
- What team/project is this work for?

    _this adds context for the data_

    - Geriatrics and GRECC web teams
    
- What type of analytics support are you looking for?
  - [X] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
   
Our request is for you to set up custom dimensions (as described in https://www.3whitehats.com/knowledge/how-to-get-service-provider-back-in-google-analytics) to find out service providers for direct traffic analysis. Please contact margery@searchenginecatalyst.com for questions. After that, please provide a one-time report, dashboard, or saved report with the service provider information. Thank you.

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)? 

By January 23, 2021.

## Analytics to Track Down
> Examples
> 
> - [ ] Metric 1
> - [ ] Metric 2
> - [ ] Metric 3

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks for your request @HikeBandit, we will be triage and be in touch soon.

**Comment by RachaelMR** [comment]
Hi @HikeBandit! This analytics team's purview is just for the modernized VA.gov experiences, so I have a question or two to understand whether this is something we might be able to help with or not.

First of all, could you let me know what modernized VA.gov experience you're trying to learn more about with this data? I.e. what area of the modernized VA.gov site are you hoping to assess?

Thank you!

Rachael

**Comment by HikeBandit** [comment]
Hi, Rachael. Do you have a reference for the "Modernized" VA experience? My team is not aware of this initiative.
________________________________

**Comment by rroueche** [comment]
Sure thing @HikeBandit ! 

Here's an example of the modernized VA.gov experience: https://www.va.gov/health-care/
And here's an example of a legacy VA.gov experience: https://www.va.gov/health/

I'm not sure if VA has a department that helps with analytics for the legacy experiences or not.

**Comment by HikeBandit** [comment]
Hi, @rroueche Do I correctly understand that you cannot support my request for a custom GA dimension which will help us understand how best to support our veteran readers because the websites are using the legacy templates? Google Analytics is the same for both legacy and modern websites.

Is there any mandate to migrate to the modern template?

**Comment by rroueche** [comment]
Hello @HikeBandit ,

**Comment by HikeBandit** [comment]
Hello @rroueche. Did you mean to comment more?

**Comment by rroueche** [comment]
Hello @HikeBandit, haha yes I did - thank you for the ping.

It's more like this: we have the all-too-common challenge where we have a very small team of people (2 FTE), and a huge amount of things we could be doing for analytics across all of our digital properties. As happens a lot in work / life, we're faced with these options: we could do a shoddy job at _all_ the things, or we could do a great job at a narrow set of things. We're taking the narrow approach now in the hope we can expand the team going forward and provide analytics support for more and more things.

That being said, if there are quick things here and there (efforts that would take just a few hours), we'd like to help and pick them up when we can -- even outside of our scope. Because ultimately we want analytics to be helpful across all of VA, so it's an exciting prospect to be communicating with you. Jon is asking some follow up questions on your other ticket so we can understand the LOE and figure out if that would be a small-size thing we could help with.

Thanks for your understanding,

Rachael
