### ISSUE TITLE
[Content Structure] Move VISN-7 (Part-1)Facilities listed in parent category "VAMC facilities" into Correct VISN-7 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17922]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-7 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**

VA Augusta health care
- [ ] vha_509	Charlie Norwood Department of Veterans Affairs Medical Center
- [ ] vha_509A0	Augusta VA Medical Center-Uptown
- [ ] vha_509GA	Athens VA Clinic
- [ ] vha_509GB	Aiken VA Clinic
- [ ] vha_509QA	Ray Hendrix Department Of Veterans Affairs Clinic

VA Birmingham health care
- [ ] vha_521	Birmingham VA Medical Center
- [ ] vha_521GA	Huntsville VA Clinic
- [ ] vha_521GC	Florence VA Clinic
- [ ] vha_521GD	Rainbow City VA Clinic
- [ ] vha_521GE	Oxford VA Clinic
- [ ] vha_521GF	Jasper VA Clinic
- [ ] vha_521GG	Bessemer VA Clinic
- [ ] vha_521GH	Childersburg VA Clinic
- [ ] vha_521GI	Guntersville VA Clinic
- [ ] vha_521GJ	Birmingham VA Clinic
- [ ] vha_521QA	Callahan VA Clinic

VA Central Alabama health care
- [ ] vha_619	Central Alabama VA Medical Center-Montgomery
- [ ] vha_619A4	Central Alabama VA Medical Center-Tuskegee
- [ ] vha_619GA	Columbus VA Clinic
- [ ] vha_619GB	Dothan 1 VA Clinic
- [ ] vha_619GD	Wiregrass VA Clinic
- [ ] vha_619GE	Monroe County VA Clinic
- [ ] vha_619GF	Central Alabama Montgomery VA Clinic
- [ ] vha_619QA	Dothan 2 VA Clinic
- [ ] vha_619QB	Fort Benning VA Clinic

## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN
