### ISSUE TITLE
Refactor/cleanup facility health service contact info

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17928]
## Issue Description
The content modeling work for facility health services location/contact info resulted in some technical debt that needs refactoring/cleanup. 

Examples

- The appointments area looks for populated appointment/walk-in/referral and phone number fields. The section requires only the phone number to be populated. 
- Given what we know now, the template used for this implementation may not be the best option

 
---
## Tasks
- [ ] Identify extraneous logic that can be removed 
- [ ] Identify the appropriate template 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
