### ISSUE TITLE
[Content Structure] Move VISN-8 (Part-2) Facilities listed in parent category "VAMC facilities" into Correct VISN-8 System [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17921]
## Story
As a VAMC web user in need to have all facilities correctly listed under the system, so I can best associate and find my closest health service provider.

## Tasks
**Move facility from parent "VAMC facilities" location to the correct System location within VISN-1 as listed below**
Open VAMC facilities menu and search for each of the below facilities and assign the following:
**What health care system does the facility belong to?**
**Confirm if site is MAIN Location** Medical centers only
**Owner**

VA Orlando health care:

- [ ] Orlando VA Medical Center
- [ ] Viera VA Clinic
- [ ] William V. Chappell, Jr. Veterans' Outpatient Clinic
- [ ] Kissimmee VA Clinic
- [ ] Deltona VA Clinic
- [ ] Tavares VA Clinic
- [ ] Clermont VA Clinic
- [ ] Lake Baldwin VA Clinic
- [ ] Crossroads VA Clinic

VA Tampa health care:

- [ ] South Hillsborough Outpatient Clinic
- [ ] James A. Haley Veterans' Hospital
- [ ] Tampa VA Domiciliary
- [ ] New Port Richey VA Clinic
- [ ] Lakeland VA Clinic
- [ ] Brooksville VA Clinic
- [ ] Zephyrhills VA Clinic
- [ ] Lecanto VA Clinic
- [ ] Hidden River VA Clinic

VA West Palm Beach health care:

- [ ] West Palm Beach VA Medical Center
- [ ] West Palm Beach VA Medical Center
- [ ] Palm Beach Vet Center
- [ ] Jupiter Vet Center
- [ ] Fort Pierce VA Clinic
- [ ] Delray Beach VA Clinic
- [ ] Stuart VA Clinic
- [ ] Boca Raton VA Clinic
- [ ] Vero Beach VA Clinic
- [ ] Okeechobee VA Clinic
- [ ] Port Saint Lucie VA Clinic

## Acceptance criteria
- [ ] All facilities have been moved from parent to system
- [ ] All main locations have been confirmed
- [ ] facilities show up correctly under System an VISN
