### ISSUE TITLE
Yellow Ribbon [DISCOVERY] Formulate strategy & estimate for improving abbreviation search

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17939]
## Issue Description
This is a discovery task to research options for improving the search results in the Yellow Ribbon search tool so that it returns relevant results for common abbreviations

---
## Tasks
- [x] Determine how the current search works
- [x] Research other search tools currently used on VA.gov (collaborate with Search & Discovery team)
- [x] Identify best option for improving Yellow Ribbon search handling of abbreviations
- [x] Create additional issues for tasks related to implementing the selected solution
- [x] Estimate size of additional tasks

## Acceptance Criteria
- [ ] Current search algorithm is documented
- [ ] Other tools used on VA.gov are documented
- [ ] Best option for improving abbreviation search is identified
- [ ] Additional issues for implementing are created and estimated

**Comment by zacharymorel** [comment]
Taking a minute today and researching this a little while we have some time.

**Comment by zacharymorel** [comment]
Pairing with @kelsonic today for a knowledge transfer.

**Comment by zacharymorel** [comment]
Findings after working with Kelson and the GIDS team:

**Data flow** as goes:
1. FE Request comes in.
2. Vets-API acts as a proxy to the GIDS API (It is a server connecting to other microservices). 
3. GIDS is a microservice which receives request from Vets-API. 
4. GIDS queries it's in house DB which stores various CSV's uploaded by various federal sources. 

**Data**
Relationship between an Institution and a Yellow Ribbon Program.
1 Yellow Ribbon Program Belongs to 1 Institution. 
1 Institution has many Yellow ribbon Programs. [SEE EXAMPLE](https://www.va.gov/education/yellow-ribbon-participating-schools/?name=Academy+College) 

**Abbreviation work:** 
1. We can utilize the same data set that the GI Bill Comparison Tools does. 
2. Work will have to be done in several stages.
    a. Update GIDS API existing Yellow Ribbon search abilities 
    b. Update FE work once GIDS is deployed to production.
    
 **Autocomplete**
 Problem: GIDS can go down with too many requests. It's a very fragile API. 
 Solution:  1. We throttle the front requests like what is done currently on the GI Comparison Tool. 2. We can search ONLY after n number of characters. 
1. Work will have to be done in several stages.
    a. Create a new api endpoint (code to intercept the request from the Vets-API) on the GIDS.
        - (Additionally, Updated Model Layer to query DB for Autocomplete results)
    b. Create a new api endpoint (code to intercept the request from the client) on the Vets-API. 
    c. Once Vets-API is deployed, updated the widget on the FE to account for autocomplete.

**Comment by zacharymorel** [comment]
FYI: GIDS = GI Data Service
I also realize y'all might know a bit of that already. But I figured it'd be nice to repeat or include further details for context sake.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO can you do a once over of the info I documented here before I close the discovery?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel is everything in the Tasks and Acceptance Criteria complete? (you can check off whatever is done).  Thx!

**Comment by zacharymorel** [comment]
Okay, this is ready for close I think @MarciMcGuireGCIO .
