### ISSUE TITLE
Yellow Ribbon: Devise short-term text option to improve search success rate

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17937]
## Issue Description
The Yellow Ribbon search tool currently does not handle searches for common school abbreviations, such as NYU or UCLA.   While the discovery, design and engineering work is being done to improve the search algorithm, we believe that providing some guiding text will help users conduct more successful searches in the meantime.

---
## Tasks
- [x] Determine if the design system allows for placing instructional text near the search tool
- [ ] Draft message that will to advise users to enter the full school name rather than abbreviations
- [x] Enter request for Content team to review
- [x] Mock up placement of message on Yellow Ribbon search page
- [x] Enter request for Accessibility team to review

## Acceptance Criteria
- [x] Research on design system allowance for message is complete
- [x] Message draft is written
- [ ] Message placement is mocked up
- [ ] Request for Content review is created
- [ ] Request for Accessibility review is created

**Comment by laurellawrence** [comment]
Mockup for feedback can be found here: https://xd.adobe.com/view/11c751ae-0a20-44fc-99e5-348eddc3272b-4494/

**Comment by MarciMcGuireGCIO** [comment]
I love it! I commented in XD as well.

**Comment by johnhashva** [comment]
@laurellawrence + @MarciMcGuireGCIO Just a few Q's:

- Correct to assume this is our Design System approach to "tool tips" -- e.g. large "notification" box?
- Can we have a Content person review our tip text -- e.g., Peggy Gannon on Platform (as part of Collab Cycle) or Public Websites content specialist -- Danielle or Beth.   Might be easier/faster to have Peggy review/approve since the Content team is usually swamped.  (Note: They have a content intake ticket template -- and ask for two weeks notice).

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva I can't speak to the Design System approach, but I do think we should have a Content person review the copy.  I will put that request in today.

**Comment by laurellawrence** [comment]
@johnhashva, I can confirm that the info alert box is included in our design system library and the mock is following the design guidelines. https://design.va.gov/components/alertboxes

**Comment by johnhashva** [comment]
Thank you both -- this is going to reduce some series friction -- as measured by search refinement rate -- by a lot.  In fact, @MarciMcGuireGCIO if we could quantify our overall "average refinement rate" for this tool -- whether that is a blended average of all searches/schools -- or top searches/schools (maybe the top 50) -- we could use that as our baseline to measure improvement.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva thank you.  I'll collect baseline metrics and create a report.

**Comment by sshein** [comment]
just chatted with Laurel and it does feel like this takes up quiet a bit of the results page - maybe we can let people know about this [on the landing page](https://www.va.gov/education/yellow-ribbon-participating-schools/) instead of the results page? And maybe we can have shorter instructions closer to the "school name" field?  Peggy might have some thoughts here that could help

**Comment by sshein** [comment]
Also wondering if this is an opportunity to create a better "hint text" component - right now we just put hint text in parens after the label typically. See this slack thread for more details: https://dsva.slack.com/archives/C8E985R32/p1610131947323100 (@laurellawrence)

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO and @laurellawrence based on Shawna's feedback, have we hit a wall?  Or do we have some ideas about how to refashion our approach?

**Comment by MarciMcGuireGCIO** [comment]
> just chatted with Laurel and it feels like this notification takes up quiet a bit of the results page - maybe we can let people know about this [on the landing page](https://www.va.gov/education/yellow-ribbon-participating-schools/) instead of the results page? And maybe we can have shorter instructions closer to the "school name" field? Peggy might have some thoughts here that could help

That make sense, and having it on the landing page initially also sets them up for success at the outset, vs after they've already tried (and possibly failed) once.

**Comment by MarciMcGuireGCIO** [comment]
> @MarciMcGuireGCIO and @laurellawrence based on Shawna's feedback, have we hit a wall? Or do we have some ideas about how to refashion our approach?

@johnhashva, I don't think we've hit a wall.  Moving it to the landing page helps up front, vs. after they've already tried --  like providing password rules vs. displaying them after one failed attempt ("must contain a number, letter, special character...")  

I'm very confident that @laurellawrence will be able to come up with a new design based on the feedback Shawna has given.

**Comment by laurellawrence** [comment]
![Yellow ribbon search results - Desktop@2x](https://user-images.githubusercontent.com/75386943/104337031-aa22f500-54ba-11eb-839c-d8597649791c.png)
After discussion with Shawna on 1/12, we may want to consider the established design pattern [Contextual help link](https://design.va.gov/patterns/supplemental-content) under the school name field. This would appear on both the search landing and results pages. 
As always, there are a few things to consider: 
- There a few drawbacks on just showing the info alert box on the results page. As Marci mentioned above, this info message would appear after the user has already searched once and potentially failed. The info message box takes up alot of real estate on the page, causing scrolling
- Benefit of the alert box is that it is front and center on the results page, a user doesn't have to click anything for those tips for success to appear
- The contextual help link, would be placed under the school name field, on both the landing and search results page. It is right below the school name field but the the drawback is that the tips are collapsed and require a user click to display. 

Mocks of the 2 options can be found here: https://xd.adobe.com/view/11c751ae-0a20-44fc-99e5-348eddc3272b-4494/

**Comment by johnhashva** [comment]
@laurellawrence (with @MarciMcGuireGCIO) -- thanks for this, and agree with you about establishing a design pattern approach (especially given our Find a Form sort experience).  I mentioned to Marci that its a little unclear how the process of "approval" works here -- as an example: does Shawna make the call or Ryan?  My recommendation is you post a Slack message about this one (maybe in #design channel) and ask for Ryan, Shawna and Josh to weigh in.   Does this make sense to you both?

**Comment by MarciMcGuireGCIO** [comment]
@laurellawrence cc @johnhashva --  The mockups look great!  I strongly prefer the Contextual help link approach (where the help text appears immediately below the School Name field) because I think it's more likely for the user to see it.  I also like it being on the search & result; doubles the chance of success!  Please let us know what kind of feedback you get from Ryan, Shawna and Josh.

**Comment by sshein** [comment]
I like this option better for sure. Agree that it's worth a quick slack post in #design just to make sure there isn't already a different pattern that's being used by others that's similar. 

In general, designers on VSA don't need "approval" by anyone for small design choices, but it's nice to conduct due diligence (e.g. posting in the #design channel) if you're designing something that is something of a pattern that others might have thought of.

**Comment by peggygannon** [comment]
@laurellawrence 

I think we can condense the content to 1 line. Here’s what I would recommend based on your design approach. I've also provided another option if we want to move that line of content up next to the label 

{label} School name
{search box}
To improve search results, enter a school's full name. For example, search for New York University not NYU. 

OPTION B (condensing content more)
{label} School name (Enter a school's full name. For example, search for New York University not NYU)
{search box}

**Comment by laurellawrence** [comment]
<img width="945" alt="Screen Shot 2021-01-12 at 3 54 28 PM" src="https://user-images.githubusercontent.com/75386943/104379310-ecfec000-54ee-11eb-8af9-a21dbbae62c4.png">

Based on feedback from other VA designers, Shawna and Peggy here's where we stand: 

- Add shortened contextual text under "School Name" field on both the landing and results pages
- Add a dismissible info alert, with shortened copy below "Displaying 1–1 of 1 results" before search results 

XD mocks have been updated, same link as above https://xd.adobe.com/view/11c751ae-0a20-44fc-99e5-348eddc3272b-4494/

**Comment by MarciMcGuireGCIO** [comment]
Love it!! 👏🏻

**Comment by johnhashva** [comment]
@laurellawrence works for me, too -- @MarciMcGuireGCIO how about we add tracking on that Tips to improve link to see how many click it?  My hunch is some users may miss/ignore it.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva good suggestion. I’ll get it teed up for Analytics to generate a tag.

**Comment by sshein** [comment]
looks good! tracking is a good idea then if no one every clicks on it you can just remove it and keep the dismissable alert :)

**Comment by MarciMcGuireGCIO** [comment]
I'm going to mark this particular task closed and create another ticket for the actual implementation.
