### ISSUE TITLE
[Tech-Debt] Add new design and Suicide prevention alert to existing VISN-19 pages.

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17934]
## Issue description
The display of information on the [suicide prevention detail page](https://www.va.gov/pittsburgh-health-care/suicide-prevention/) is duplicative, poorly formatted and inconsistent with the design system. The crisis hotline number is displayed three separate ways. Erie has added an image for the crisis line. We need to standardize this national content for ease and risk mitigation. 

<details> 
<summary> Page screenshot </summary>

![mental health phone bug.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b102e360-71de-40eb-bf9b-52d28bb058b8)

</details>

Most content is nationalized, with the exception of some facilities which add local content for Behavioral health or community care under ongoing support. 

<details> 
<summary> Example from Erie </summary>

![erie](https://user-images.githubusercontent.com/55411834/94721908-c20fa800-0313-11eb-8c4c-5d3c52c24bf0.png)

</details> 

## Tasks
- Delete content and replace with react widget for "How do I talk to someone right now?"

- [x]  VA Cheyenne health care
- [x]  VA Eastern Colorado health care
- [x]  VA Western Colorado health care
- [x]  VA Montana health care
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma City health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care

## Acceptance Criteria
- Add Alert for How do I speak to someone now- VISN4  
- Pittsburgh/VISN 4 pages will be cloned and will have source Content added.

**Comment by ltrombley** [comment]
[Tech-Debt] #17934 - Add new design and Suicide prevention alert to existing VISN-19 pages is Complete and moved to Validate.
1. All pages Cloned from Sierra Nevada and marked as "Cloned"
