### ISSUE TITLE
[VAMC] Resolve orphan Facility Health Services in each of the list Systems [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#17936]
## Issue Description
All orphan facility health services have to be re-associated, due to Duplicates at the System Health Service level, all Facility health service associated to those duplicates when they were deleted created orphans, so there are no more orphan health services.

---
## Tasks
Resolve all orphan facility health services for the following Systems:
- [x] Butler
- [x] Lebanon
- [x] Wilkes-Barre
The following will be complete for each System
- [x] Find and list all orphans 
- [x] Research and find the Parent System health service and re- associate them to that services/System

## Acceptance Criteria
- [x] No orphans remain in each System.
---
