### ISSUE TITLE
Yellow Ribbon [DISCOVERY] Formulate strategy & estimate for improving search ranking 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17940]
## Issue Description
This is a discovery task to research options for improving the search results in the Yellow Ribbon search tool so that it ranks results in order of greatest relevance

---
## Tasks
- [ ] Determine how the current search works
- [ ] Research other search tools currently used on VA.gov (collaborate with Search & Discovery team)
- [ ] Identify best option for ranking Yellow Ribbon search results in order of relevance
- [ ] Create additional issues for tasks related to implementing the selected solution 
- [ ] Estimate size of additional tasks

## Acceptance Criteria
- [ ] Current search ranking algorithm is documented
- [ ] Other tools used on VA.gov are documented
- [ ] Best option for improving ranking is identified
- [ ] Additional issues for implementing are created and estimated

**Comment by zacharymorel** [comment]
Does _ranks results in order of greatest relevance_ mean sorting the results returned?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Example - the top result for "UNC" would be The University of North Carolina at Chapel Hill --  the school for which that abbreviation is commonly used and widely recognized.  Other schools in the UNC system would appear immediately below that.  

It would also either exclude schools that simply contain the string "unc" (aka %unc% in an SQL query)  or would rank them at or near the bottom.   There seems to be metadata/logic that already works in this manner in the GI Bill search.  I've provided additional info & screen shots of this in the Epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/16405.  Hope that helps!
