### ISSUE TITLE
Telehealth data availability in PPMS

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17946]
## Issue Description
This request was submitted by the OCC

Telehealth availability was added to PPMS over the summer and the data is being submitted by contractors. This information will ensure Veterans in rural areas are aware of the option/capability, especially for urgent care. 

This will become particularly important when CCN rolls out in Alaska in March. 

---
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
TriWest is required to provide telehealth services under Region 5 for neuropsychology and rheumatology (at a minimum)

**Comment by Agile6MSkinner** [comment]
@mmiddaugh What is the status of this effort?

**Comment by jilladams** [comment]
This is light on details, not an active effort, and lingering in an old epic that doesn't need to migrate to Github projects. Closing and we can recreate as needed later on when we properly wrangle telehealth related things.
