### ISSUE TITLE
Move PPMS into Rails engine

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17953]
## OKR
_Which Objective / Key Result does this epic push forward?_

## Tasks

- [ ] [Work with BE team to outline plan/tasks](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17954)
- [ ] Connect FE directly to Lighthouse
- [ ] Determine method of version control
- [ ] Work with Security group

### What must be true in order for you to consider this epic complete? 

- [Generate new engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11608)
- [Copy PPMS Models/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18526)
- [Copy Lighthouse Models/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18528)
- [Copy V1 PPMS Client/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18529)
- [Copy Lighthouse Client/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18531)
- [Copy V1 VA Controller/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18533https://github.com/department-of-veterans-affairs/va.gov-team/issues/18533)
- [Copy V1 CCP Controller/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18534)
- [Copy V1 VA_CCP Controller/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18535)
- [Mount Engine to /v1/facilities](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18537)

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
