### ISSUE TITLE
Determine plan/tasks for Rails engine

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17954]
## Issue Description
Following Lance's Discovery conversation with Michael Fleet, we have support for moving PPMS into a Rails engine

---
## Tasks
- [ ] work with BE tools team to determine the plan/tasks which need to be done to move PPMS into a Rails engine

## Acceptance Criteria
- [ ] Tasks (and responsible team) are documented
- [ ] Issues are created and associated with this epic
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
- [Generate new engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11608)
- [Copy PPMS Models/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18526)
- [Copy Lighthouse Models/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18528)
- [Copy V1 PPMS Client/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18529)
- [Copy Lighthouse Client/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18531)
- [Copy V1 VA Controller/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18533https://github.com/department-of-veterans-affairs/va.gov-team/issues/18533)
- [Copy V1 CCP Controller/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18534)
- [Copy V1 VA_CCP Controller/Tests to Engine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18535)
- [Mount Engine to /v1/facilities](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18537)
