### ISSUE TITLE
Vet Center Research (Mobile prototype)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17959]
### Goal of this study
Within the context of this mobile prototype which uses "real-world data", to get feedback from both Vet Center clients and non-clients on:
- The display/content and organization of a few priority Vet Center services
- The presentation of satellite locations using real world examples

### Research questions
Do the participants: 
- understand that Vet Centers are different from other VA facilities?
- understand the difference between the Vet Center and satellite locations?
- have enough information in order to visit or call?
Do our service descriptions give Veterans the information that they need to make an informed decision about their care?

### Hypothesis
What is your hypothesis for this research?

### Participant criteria

---
## Tasks
- [ ] Create research guide and conversation guide for next round of Veteran research

## Acceptance Criteria
- [ ] Approved research guide and Veteran research submitted to begin recruitment

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
https://preview.uxpin.com/cdd25414c3c03534b7a8ee83b89f964219565580#/pages/135469174?mode=cvhidm

**Comment by mmiddaugh** [comment]
[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/client-usability-tests/research-plan.md)
