### ISSUE TITLE
Conduct Veteran research (Vet Center 1.0 mobile prototype)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17961]
## Issue Description
Conduct Veteran research sessions as scheduled by Perigean
---

## Tasks
- [ ] Conduct Veteran research sessions as scheduled by Perigean

## Acceptance Criteria
- [ ] Notes are available from sessions

vet---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
[Notes from sessions found here.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/discovery/client-usability-tests/session-notes)
