### ISSUE TITLE
Change Check From 'logged in' to LOA3 or Not

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#17970]
## Background
Currently, in the CH36 and CH31 forms, we check if the user is logged in. In some cases, a user could be logged in but not have all data to properly fill out the required information to pass `vets-json-schema` validation. We need to adjust the check so that we ensure the user has LOA3 and thus has necessary data to complete the CH36 form.

## Tasks
- [ ] Adjust the check to see if the user has LOA3 or anything else
  - [ ] If not LOA3, route the user to the unauth page list  
- [ ] Include this solution in the CH31 form 

## Acceptance Criteria
- [ ] Non-LOA3 users are shown the non-auth'd version of the feature

**Comment by digitaldrk** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5590
