### ISSUE TITLE
Bad Address Indicator

### ISSUE THREAD

**Issue by lkoenigsberg** [department-of-veterans-affairs/va.gov-team#1797]
**Background**
Each address stored in Vet360 comes with an optional Bad Address Indicator (BAI). When BAI is true that means that the VA has had mail returned to it from that address, which means not only have the taxpayers paid for a bad government interaction, but also that the Veteran in question did not receive her benefit.

**Expectations**
We should consume the BAI and surface a UI notification to the user that the address in question needs attention.

**Considerations**
- VA.gov has multiple addresses, identifying which address in in question
- When to engage - at login, in account, etc
- Address validation & override must be complete first

**Other Information**
This feature is expected to be available from Vet360, as a boolean, in November.

[GitHub Documentation]( )

We'll use this epic to track the progress for combining the existing Profile and Account pages.

## Project management

- [ ] Create product outline 

## Design
- [ ] Design Discovery 
- [ ] Design Wireframes/Prototypes [#2198](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2198)

##  Design Research / User Testing 
- [ ] Research Plan
- [ ] Socialize research plan with appropriate team members for approval (Lauren Alexanderson)
- [ ] Create Conversation Guide and Schedule Review 
- [ ] User Testing Sessions Scheduled
- [ ] Conduct user testing sessions
- [ ] Deposit user testing session notes into GitHub
- [ ] Create research summary 
- [ ] Create tickets for any changes/ updates that came from user testing

## Build

We'll track high-level build tickets here.

## UAT
- [ ] UAT Plan
- [ ] UAT Conversation Guide
- [ ] Recruiting
- [ ] Conduct UAT
- [ ] Summarize
- [ ] Any changes that resulted from UAT

## Pre-launch Checklist

- [ ] QA
- [ ] 508 accessibility testing

We'll track additional pre-launch tickets here.

[Info on the new launch checklist]( )

- [ ] [Accessibility / 508 review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Accessibility/508-request-prelaunch-review.md)

- [ ] [ATO review](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md)

- [ ] [Content QA](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-content-qa.md) / review(?)

- [ ] [Design QA](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-design-qa.md) / review(?)

- [ ] **Analytics / Product Health Report review**
*   Reviewing analytics that will be used to just the product health / success, and making recommendations as appropriate.

- [ ] **Release plan review**
*   Review release phases and criteria for moving between them. This should include rollout schedule, success/rollback criteria, any pre- and post-launch user testing and monitoring, external documentation and comms.

- [ ] [IA review](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ia-review.md)
*   Should include review of URLs, navigation hierarchy, crosslinks/redirects, SEO

- [ ] **Security review**
*   Review looking for potential technical security issues / vulnerabilities, focusing particularly on frontend-backend interactions, anything involving certificates or cookies, and any new interactions with dependent backends.

- [ ] **Privacy review**
*   Review looking for potential user data issues, including affirming best practices around handling PII.

- [ ] **Production readiness / infrastructure review**
*   Review of technical architecture, looking for potential scaling concerns, dependency analysis, SLO assessment

- [ ] **Documentation for quickly addressing when things go wrong**

- [ ]   **Contacts for on-call support**: who do we contact if the application is failing? What kinds of failure modes are likely?
    - [ ]  ** Documentation and points of contact for any new backend dependencies**
    - [ ]  ** Links to important dashboards for investigating relevant issues**

- [ ] **No high-severity bugs present**

- [ ] **Testing requirements**
    - [ ]   E2e tests, running in CI/CD, passing on all browsers
    - [ ]   Code coverage requirements
    - [ ]   Load testing

- [ ] **Monitoring requirements**
    - [ ]   Contact (mailing list? Slack channel?) for errors to be reported to
    - [ ]   Errors getting sent directly to team

- [ ] **Contact center(s) are prepared for this launch, with updated scripts/documentation as needed**
- [ ] **VA web comms team is aware of this launch and has accurate messaging**
- [ ] **Product Outline w/critical criteria up-to-date**
- [ ] **Tested in prod with VA back-of-house people and systems**
- [ ] **Entrance pages (i.e. supporting static content) in place**
- [ ] **Downtime UX and error messaging documentation complete**
- [ ] **"Learn and Improve" plan written**: KPI measurements, analytics reporting, next phase of features to build

**Comment by Samara-Strauss** [comment]
Closing. If we ever actually do this project, I'll create a new epic.
