### ISSUE TITLE
Adjust Address Line in PDF 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17975]
## Background
In looking into another issue, an opportunity arose to improve how the address line was being rendered when a PDF was being generated for the CH36.

## Tasks
- [x] Align the field names for **address_line_1** between what frontend sends and backend receives 

## Acceptance Criteria
- [x] Characters in **address_line_1** render properly upon PDF generation
- [x] A PR has been requested for merging

**Comment by digitaldrk** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5591
