### ISSUE TITLE
Notification Launch Checklist

### ISSUE THREAD

**Issue by lkoenigsberg** [department-of-veterans-affairs/va.gov-team#1799]
All items here must be completed and signed off on by VSP before your new application can launch, and you should start convos about each item early - so you can work on them incrementally and iterate from day one.

If you're unsure how to tackle various things on this list, just ask in #vfs-platform-support so VSP can help!  These processes are here to help ensure we're launching features that are:

- in line with VA.gov's standards for design, UX, reliability, and availability
- maintainable over time
- have measurable analytics and success metrics to empower future planning and development

All items on this checklist should be completed for launch:

- [ ] Accessibility / 508 review
- [ ] ATO review
- [ ] Content QA / review
- [ ] Design QA / review
- [ ] Analytics / Product Health Report review
- [ ] IA review
- [ ] Security review
- [ ] Privacy review
- [ ] Production readiness / infrastructure review
- [ ] Load testing
- [ ] Contact center is ready for the launch
- [ ] VA web comms team is aware of this launch and has accurate messaging
- [ ] Product Outline w/critical criteria up-to-date
- [ ] Tested in prod with VA back-of-house people and systems
