### ISSUE TITLE
Fix bug in CH31 GA events

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#18002]
# Background
During testing, we found a bug in the CH31 Google Analytics events where every event had the same value for `form-field-label`. Upon investigation, I found that the issue was caused by how I had populated this value. I need to update how the value is populated so that it can be changed for every set of buttons.

## Tasks
- [x] Update how `form-field-label` is populated in CH31 Google Analytics events
- [x] Submit a PR for review

## Acceptance Criteria
- [x] The `form-field-label` now has the correct value for each set of questions
- [x] A PR has been submitted for review
