### ISSUE TITLE
Refactor "pension_burial" Load Test for Locust 1.x

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18017]

**Comment by pjhill** [comment]
# Tasks
- [ ] Test the refactored code by executing the load test
- [ ] Review execution results and ensure that the test run looks normal
- [ ] Record the results of the load test in order to establish a baseline
