### ISSUE TITLE
Format Use Case Sheet for Dependency Claims

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18029]
## Background
We want to ensure that the accounts that we use and the characters and attributes we assign to the different use cases are up to date and accurate because it is difficult to look up each user and get info on them.

## Tasks
- [x] Merge our existing Excel spreadsheet (created in August) with Linda's spreadsheet and our own historical notes into a Google Sheet
- [x] Track SSNs + DOB for future test accounts
- [x] Leave room for tracking some helpful business rules (i.e., some go straight to manual and why)

## Acceptance Criteria
- [x] A shared Google Sheet has been created.
