### ISSUE TITLE
COVID-19 updates 1.4.21

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#18032]
## Issue Description

Need to update FAQs and chatbot to reflect updated info:

- Coronavirus FAQs: prod.cms.va.gov/node/3014
- Chatbot: https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/345 <br>

For the debt and copay questions, you can review against these Word docs. 
[https://app.zenhub.com/files/133843125/9ba81bd5-6599-4b75-b45f-7bab68a4a0f7/download](https://app.zenhub.com/files/133843125/9ba81bd5-6599-4b75-b45f-7bab68a4a0f7/download)
[https://app.zenhub.com/files/133843125/060d382b-eef5-4fe9-b3c0-8188da318303/download](https://app.zenhub.com/files/133843125/060d382b-eef5-4fe9-b3c0-8188da318303/download)

---
## Tasks
- [x] Update faqs and chatbot (Danielle)
- [x] Review faqs updates, publish, and trigger content release (Randi)
- [x] Review chatbot PR and approve (Randi)
- [x] Hand off chatbot to ThoughtWorks team (Danielle)
- [x] Validate chatbot in staging (Danielle)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
Changes to FAQs are published and live on the site.
