### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for VA Oklahoma City Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18035]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Resources
[VISN-19 Playbook](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.

**To include:**
* Is a referral required?
* Are Walk-ins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**

VA Oklahoma City health care
- [x] Ada VA Clinic
- [x] Altus VA Clinic
- [x] Ardmore VA Clinic
- [x] Blackwell VA Clinic
- [x] Enid VA Clinic
- [x] Lawton VA Clinic
- [x] North May VA Clinic
- [x] Oklahoma City VA Medical Center
- [x] South Oklahoma City VA Clinic
- [x] Stillwater VA Clinic
- [x] Wichita Falls VA Clinic
- [x] Tinker VA Clinic
- [x] Clinton VA Clinic
- [x] Fourteenth Street VA Clinic
- [ ] Yukon VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [x] **Contact PM on how to best confirm data is accurate.
