### ISSUE TITLE
[TECH-Debt] Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for VA Salt Lake City Health care system facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18034]
## Story
As a Veteran I need to see all of the facility health services in a detail manner, so I can best verify my required contact information by health service in each facility

## Resources
[VISN-19 Playbook](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
* Move all data in the current blobby/text field down into detail fields.  If information is same as default information then confirm that the "Use Default information" is checked and move to next field.
**To include:**
* Is a referral required?
* Are Walk-ins accepted?
* Is online scheduling available?
* Phone number for appointments
* Service Location
** Address (If different than default)
** Hours (if different than default)
** Contact Info (If provided in detail)

**Complete the above for the following Systems**

VA Salt Lake City Health Care
- [x] Elko VA Clinic
- [x] George E. Wahlen VA Medical Center
- [x] Idaho Falls VA Clinic
- [x] Ogden VA Clinic
- [x] Orem VA Clinic
- [x] Pocatello VA Clinic
- [x] Price VA Clinic
- [x] Roosevelt VA Clinic
- [x] St. George VA Clinic
- [x] Weber County VA Clinic (Appears that Weber County VA Clinic is now part of Ogden VA Clinic)
- [x] Western Salt Lake VA Clinic

## Acceptance Criteria
- [x] All facility health services are updated
- [ ] **Contact PM on how to best confirm data is accurate.

**Comment by ltrombley** [comment]
[TECH-Debt] #18034 -  Manually migrate Facility health services from "Blobby/plain text" to "Detail field" Front end for VA Salt Lake City Health care system facilities is Complete and moved to Validate:

1. Western Salt Lake VA Clinic is now South Jordan VA Clinic
2. Weber County VA Clinic has been incorporated into the Ogden VA Clinic
