### ISSUE TITLE
Find a VA Form: Handle use case where deprecated form has been replaced by another

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18033]
## Issue Description
Deprecated forms are sometimes replaced by other forms, and we need to establish a method for providing a link to the replacement form, rather than simply displaying a message that the form has been deleted.
---
## Tasks
- Determine how this would fit into the current workflow
- Determine what new fields/data would be required to provide this information
- Estimate work required to design, code, test and review

## Acceptance Criteria
- [ ] Determine where handling of replacement forms fits into form management process
- [ ] Determine what data/fields are needed
- [ ] Break work into sprint-sized tasks
- [ ] Estimate tasks
---
