### ISSUE TITLE
Deployable Helm Chart for Loki (microservices / distributed mode)

### ISSUE THREAD

**Issue by pnwstevan** [department-of-veterans-affairs/va.gov-team#18048]
## Description
As Loki will be deployed on K8/EKS, a repeatable way to deploy Loki in microservices mode with configuration specific to VFS is needed.

## Background/context/resources
We've explored a number of K8 deployment models, and Helm is under consideration.

## Technical notes
Helm Chart should probably live here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests

---
## Tasks
- [x] Create Loki Helm Chart
- [x] Deploy Loki on EKS cluster via Helm Chart
- [x] Ensure Loki operates per design intent
- [x] Commit Helm Chart to repo
- [x] Add necessary documentation top chart

## Definition of Done
- [x] Deployable Helm Chart for Loki in microservices/distributed mode

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please connect to an epic

**Comment by pnwstevan** [comment]
Working Helm Chart for Loki in distributed microservices mode + docs here:

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/loki

**Comment by jhouse-solvd** [comment]
Working helm chart + docs from Stevan's previous comment copied to confluence loki docs [here](https://vfs.atlassian.net/wiki/spaces/VI/pages/619119010/Loki+-+Centralized+Logging+in+VSP)

closing.
