### ISSUE TITLE
[PM] Make a list of staging test cases (MyVA)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18042]
## Background
We need to create a list of staging test cases for the MyVA Dashboard

[MyVA staging test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/MyVA%20-%20test%20cases.md)

## Tasks
- [ ] Create list of staging test cases
- [ ] Review with Tze
- [ ] Review with Samara

**Comment by mshea0606** [comment]
Updates are now in. Closing this.
