### ISSUE TITLE
[PM] Submit QA request for Sprint 39 (DD for Edu)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18046]
## Background 
We need to be ready for QA by next sprint (S40). 

## Tasks
- [x] Submit request for QA
- [x] Making sure the feature is done
- [x] Reviewing the feature
- [x] Making sure Jim Adams has reviewed the feature
- [x] Talking with Erik to make sure we are 100% going to be ready for QA

**Comment by Samara-Strauss** [comment]
Moving to sprint 39, as this can't be completed until #17292 and #17294 are finished.

**Comment by mshea0606** [comment]
[DD4edu QA Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16528) submitted on 1/20/21.
