### ISSUE TITLE
[FE] Make updates to DD for Edu as needed prior to going into QA

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18051]
## Background
Once LIhan's backend changes are in Jim will review the DD4EDU feature. We're aiming to QA DD for EDU starting sprint 40.

[[Design] Review Erik's initial DD for Edu build #18050](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18050) 

Jim's feedback is listed below: 

## Tasks
- [x] Change success message for C&P change to, "We’ve updated your bank account information for your compensation and pension benefits. This change should take place immediately."

- [x] Change success message for EDU change to, "We’ve updated your bank account information for your education benefits. Your next payment will be deposited into your new account."

- [x] Remove periods from all field validation error labels; e.g. "Please enter your account number"

- [x] In "Please enter the bank’s 9-digit routing number," change "the" to "your"

- [x] For consistency, change "the" to "your" in "Please select the type that best describes the account"

- [ ] Review with Matt/Samara/Jim

**Comment by erikphansen** [comment]
The first two items are the only ones that will take more than a few minutes to change.

**Comment by erikphansen** [comment]
@sporeboy @mshea0606 @Samara-Strauss this is ready for you to review on staging.

**Comment by mshea0606** [comment]
looks good to me!

**Comment by erikphansen** [comment]
@sporeboy If things looks good to you on staging, can you close this? Thanks!

**Comment by Samara-Strauss** [comment]
FWIW, I do not have any additional feedback on the feature. Looks like it's working to me. Thank you @sporeboy for reviewing the feature more closely!

**Comment by sporeboy** [comment]
Sorry for the slow reply... We're good to close this!
