### ISSUE TITLE
Perform a content inventory audit on the Collaboration Cycle/Practice Area documentation of Github

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#18055]
## Issue Description
In order to move correct, consolidated, restructured guidance/documentation from Github to Confluence, we need to take an inventory of the existing Github documentation. 

## Tasks
- [x] Create a Google Sheet audit template 
- [ ] Assign team members specific practice areas to audit:
   - [x] IA - Mikki
   - [x] Content - Peggy
   - [x] Design - Allison
   - [x] QA - Allison
   - [x] Product - Shira
   - [x] Accessibility - Shira
   - [x] Collaboration Cycle - Shira
- [x] Review audit template with team to address questions, identify gaps.
- [x] Team members complete inventory by Friday 1/15
- [ ] Team members will complete peer review of one another's practice areas by Tuesday 1/19
   - [x] IA - Shira
   - [ ] Content - Allison
   - [x] Design - Peggy
   - [x] Product - Mikki
   - [x] Collaboration Cycle - Mikki
   - [x] Random - Peggy
- [ ] Peter/Darius verifies QA audit and fills in any gaps by Tuesday 1/19
- [ ] Trevor/Noah verifies Accessibility audit and fills in any gaps Tuesday 1/19

## Acceptance Criteria
- [ ] Product Support team has a full inventory of Collaboration Cycle and practice area documentation with relevant metadata and urls
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
@shiragoodman Here is a start to a template for doing the auditing.  I added a few of my own files to use as an example.  Would love to walk through this and make sure we are clear on the goals of not only the inventory activity, but the audit.  That may help identify any other information we may want the team to collect as they are doing their inventory. 

https://docs.google.com/spreadsheets/d/1DHeJ6N7Z2DfwBY6uk1urnKOr_sLBe7RTl5oIN1-yRQU/edit?usp=sharing

**Comment by shiragoodman** [comment]
@mnorthuis this looks great - can you move the google sheet to this location? https://drive.google.com/drive/folders/1VHQ2XelZ4BqcutWADawVhPzh1gGGNPj8

**Comment by mnorthuis** [comment]
Done!

**Comment by shiragoodman** [comment]
@allison0034 @peggygannon @mnorthuis Inventory log can be found here: https://drive.google.com/drive/folders/1VHQ2XelZ4BqcutWADawVhPzh1gGGNPj8

**Comment by shiragoodman** [comment]
hey all - the inventory log should be complete. For the peer review, please validate the following:

- Goal/purpose is appropriate
- all sections are completed (to the best ability)
- no pages are missing (yes, that means going to github and verifying all pages are logged)
- any notes are clear and easily understood
- feel free to complete missing sections, or add your own notes/comments

The peer review is NOT intended to analyze content. It is a necessary step so that when we do analyze/synthesize next sprint, we are confident that we are working with ALL relevant content, and all information captured is correct.

Please let me know if you have any questions.

**Comment by peggygannon** [comment]
@shiragoodman @allison0034 Hello! I'm reviewing Design and don't see links to the  design resources in red box. Are we supposed to include  links to files that are in nested folders? 

![2021-01-19.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/2c5a98a9-9e91-4a4a-a54c-d78f75033d44)

**Comment by shiragoodman** [comment]
@peggygannon @allison0034  - YES. The inventory should include ANY documentation on Github related to the practice area that would be relevant for a team going through the Collaboration Cycle.

**Comment by allison0034** [comment]
@shiragoodman @peggygannon I did not inventory those bc they are related to how to design, not the collab cycle. In other words, we could do away with the collab cycle and all those documents would still exist

**Comment by shiragoodman** [comment]
@allison0034 I think we need to include those folders and their content in our audit. I just reviewed some of the docs and they're seriously outdated. These are the processes we expect VFS teams to follow (AKA how to design) and they are enforced/encouraged/adapted through the collaboration cycle. Does that make sense?

**Comment by shiragoodman** [comment]
hey everyone - just a reminder that peer review will be extended until EOD tomorrow, 1/21. Thanks!

**Comment by peggygannon** [comment]
@shiragoodman confirming I've finished my peer review. My edits/additions to Design tab are in bold in the google doc.
