### ISSUE TITLE
AE: Sprint 38

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18052]
## Priorities
1.  All My VA work
2. Get BE and FE tickets done for direct deposit for edu
3. Outstanding tickets from Sprint 37 not already included in the priorities listed above
4. Start VA Profile notification preferences work
5. VA Profile deprecated ID's issue
6. Profile 2.0 hardening/enhancements

### Profile
**FE**
- [x] [FE] Create helper functions for custom logic in EditViews and render ContactInformationView directly #16215
- [x] [FE] Remove PhoneField, EmailField, AddressField in favor of ContactInformationField #17531
- [x] [FE] Reduce number of props passed to ContactInformationField and ContactInformationEditField #17536
- [x] [FE] Improve E2E testing for existing Direct Deposit for Comp/Pen #17867
- [x] [FE] Update vap-svc README #17279

*FE analytics issues*
- [x] Stop recording address validation errors in Sentry when we no longer need it #17315

**BE**
- [ ] Are we sending deprecated IDs to VA Profile? #17739

### My VA redesign
**Design**
- [x] [Design] My VA: Convert mobile wireframes to desktop layout #17307 
- [x] [Design] Create LOA1 Design (MyVA Dashboard) #18043
- [x] [Design] Mock-up first time user experience (MyVA Dashboard) #18044

### Direct deposit for edu

Main objective:  Finish backend and frontend work

**FE**
- [x] Add Cypress tests for DD4EDU #18057

**BE**
- [x] [BE] Clarify findCh33DdEft attributes #18061
- [x] Modify Ch33BankAccountsController#index method to also return bank name #17294
- [x] Change PUT profile/ch33_bank_account to return bank details after a successful update #17292

### Preferred Medical Facility
- [x] Backend build (Preferred Medical Facility) #16107 (Final review being done by identity team on 1/11 by EOD: [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1610381062297800)

## Unplanned
- [x] Clean up msw-mocks.js #18226
- [x] Form System `select`s often have additional `")}"` cruft after the options #10576
