### ISSUE TITLE
[BE] VA Profile notification preferences: Technical discovery

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18054]
## Background
We  will know more once we meet with Terry regarding technical discovery requirements.
Initial BE requirements discussion with Terry taking place on Wednesday, 1/13/21.

## Tasks
- [ ] Meet with Terry
- [ ] Determine Technical discovery requirements
- [ ] Complete technical discovery
