### ISSUE TITLE
Public Websites: Sprint 38 Priorities 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18063]
## Priorities
1.  Finalizing R&S functionality (post code freeze)
2. Begin working CLP Transformer/graphql lay-down ISO FE build
3. Outstanding tickets from Sprint 37 not already included in the priorities listed above
4. Intake Requests for January and looming December Tickets
5. Content Publishing for R&S / IRIS migration 
6. Transformer followup and close out of tickets

### Resources and Support
Priority R&S Breakdown: WIP  [MVP 1.1 EPIC #15588] [Iterate EPIC #15584]
**FE**
- [x] [FE] Homepage RS Browse by topics FE update (Nick - WIP) #15649
- [x] [FE] Checklist template (PR Open - Kelson) #15617 (Spun up a separate ticket for PDF/Print)
- [ ] [FE] PDF/Print Save Checklist - mobile and desktop - R&S 1.1 #18337
- [ ] [FE] Browse by audience RS homepage FE update (WIP - Nick) #17276 `(BLOCKED)`
- [x] [FE] Add dynamic back to top feature to the other RS article templates #16369

### Campaign Landing Page MVP 1.0
**FE**
- [ ] [FE] Create transformer/output/input for the CLP [Transformers] #17513 
- [ ] [FE] Create CLP Template + graphql query [Transformers] #17514

### Content
- [x] Intro audits #17774
- [x] Improve the quality of screen shots in R&S articles #17091
- [x] [DO NOT PUBLISH UNTIL JANUARY] PCPG update to the coronavirus FAQ page #14001
- [x] Vaccine communications tool: Message 1 #17553
- [x] IRIS Q&As: Education -- General -- Incorporate SME Feedback #17449

**PM**
- [x] [PM] Submit  KPI Dashboard request in support of CLP defined KPIs. 

### Cerner Support

Main objective: Acquire facility list to determine what facilities need to be set accordingly.  

### Intake Request - Techical Debt

**FE**
- [ ] [FE/Content] Analytics Implementation for COVID FAQ Accordion Embedded Links #13727
- [x] [FE] Publish Landing Page and URL redirects for Debt Letters Iteration 2 from BAM2 (1/4/2021) #16950 
- [ ] [FE] [COGNITION]: Footer links are inconsistently styled and missing interactive cues #3179 (Stretch Goal - Discovery)

**Comment by johnhashva** [comment]
@brianalloyd appreciate this preview!

**Comment by brianalloyd** [comment]
@johnhashva something new I'm proposing for 2021 to better align the team to sprint goals and achievements.  Plan to discuss details in planning on Wednesday.

**Comment by johnhashva** [comment]
@brianalloyd this looks spot-on.  I will huddle with Jen Lee to get a better understanding of her 2021 plans for R&S, e.g.  _Other than implementing video (after the CMS migration to a new version of Drupal), what is the go forward strategy?_

**Comment by brianalloyd** [comment]
@johnhashva in terms of forward strategy it would be great to have Jen's prospective.  As you mentioned the video elements for UX that will need to be implemented is a primary one at front of mind.  I'm also recommending we look at a "share" functionality that allows users the ability to share articles.  Since we have a high number of mobile users think it would be of value to have a "Share to Mobile" feature that enables users to send valuable articles to phone or tablet for consumption.  In addition to some added features I believe most the effort will be around adding content and growing the article library which will rest on the content team.

**Comment by johnhashva** [comment]
@brianalloyd love the share idea.  Let me schedule a convo for the three of us -- maybe this week, maybe next -- to talk about your ideas, hers -- and long-term goal for R&S.   In looking at the data in GA, I know Search Refinement is an issue -- meaning (I think), users are searching for content we don't have -- so we need to use that data to determine iteration priorities, as well.

**Comment by johnhashva** [comment]
Adding Jen's note about R&S iteration items:

•	Continue migrating IRIS and other (non-IRIS) tier 2 support content. (Content – Beth is already leading this work.)
•	Finish Video template. (CMS, FE)
•	Expand Reusable COPE FAQs functionality to benefit hub nodes (and later possibly, other suitable content products – like CLPs? – ability to use them, not to add to them per se.) (CMS, FE for functionality; and probably Randi/Content for actually using in the benefit hubs)

**Comment by brianalloyd** [comment]
Sprint is complete. Closing Ticket.
