### ISSUE TITLE
[Content] Text Notification Wording Updates based on Usability Test Findings

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18078]
# Issue Description
During our last [usability test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md), the following item was found.

Questionnaire links within text messages are more easily overlooked by participants who already receive appointment reminder text messages.
- Three out of four participants shown the text message mentioned that they currently receive these text messages. 
  - Two out of the three participants stated they would just confirm or cancel. They didn’t review the rest of the text and had to be prompted to review the questionnaire link.

Therefore, we were hoping to revise the text message, so the questionnaire sentence calls more attention to itself. Also, we need to make sure that the wording is as short as possible, since this text message is already so long. We possibly could move the questionnaire sentence above the phone number. We are able to add a sentence anywhere.

The current text is:
Your VA appointment is on NOV 26 at 09:30.
Reply:
Y1 to CONFIRM
N1 to CANCEL
D1 for DETAILS
For more info call 909-825-7084 options 2 or reply HELP.
To help us prepare for your appointment, please fill out this questionnaire from your provider: https://www.va.gov/health-care/health-questionnaires/questionnaires/.
Got a fever, cold, cough or flu-like symptoms? Stay home and phone VA first: (909) 825-7084 ext. 5085.
Don’t catch the bug. Ask your Provider to receive your flu shot!  Get yours at the VA or anytime at Walgreens Pharmacy.
Find a location of the closest pharmacy here: https://go.usa.gov/xGQk2
Send STOP to end messages.

Possible revision options:
- 1
Your VA appointment is on NOV 26 at 09:30.
Reply:
Y1 to CONFIRM
N1 to CANCEL
D1 for DETAILS
Want to better prepare for your appointment? Fill out this questionnaire from your Provider: https://www.va.gov/health-care/health-questionnaires/questionnaires/.
For more info call 909-825-7084 options 2 or reply HELP.
Got a fever, cold, cough or flu-like symptoms? Stay home and phone VA first: (909) 825-7084 ext. 5085.
Don’t catch the bug. Ask your Provider to receive your flu shot!  Get yours at the VA or anytime at Walgreens Pharmacy.
Find a location of the closest pharmacy here: https://go.usa.gov/xGQk2
Send STOP to end messages.

- 2
Don't forget to fill out this questionnaire from your Provider: https://www.va.gov/health-care/health-questionnaires/questionnaires/.

- 3
Your Provider sent you this questionnaire to fill out: https://www.va.gov/health-care/health-questionnaires/questionnaires/.

- 4
DON’T FORGET - Complete your questionnaire NOW! https://www.va.gov/health-care/health-questionnaires/questionnaires/

- 5
REMINDER - complete your questionnaire before your appointment: https://www.va.gov/health-care/health-questionnaires/questionnaires/

- 6
WE NEED YOUR FEEDBACK- complete your questionnaire before your appointment: https://www.va.gov/health-care/health-questionnaires/questionnaires/

- 7
ITS NOT TOO LATE - complete your questionnaire before your appointment: https://www.va.gov/health-care/health-questionnaires/questionnaires/

- 8
GET READY FOR YOUR APPOINTMENT - complete your questionnaire before your appointment: https://www.va.gov/health-care/health-questionnaires/questionnaires/

# Tasks
- [x] Kristen to brainstorm a few revision ideas
- [x] Work with Kristen if there are any questions

# Acceptance Criteria
- [x] Final content sent to Kristen
- [x] Wireframes updated

**Comment by kristenmcconnell** [comment]
@peggygannon I'm not sure why the text messages currently capitalize Provider. If that isn't correct (which I don't think it is), then I can talk to the team to change that when they add our sentence as well.

**Comment by kristenmcconnell** [comment]
@peggygannon The team is going to help create some ideas for text messages too, so hold on looking at this. I'll message when it is time.

**Comment by kristenmcconnell** [comment]
@peggygannon All of the team members added their suggestions. It is ready for you to review. Thank you.

**Comment by kristenmcconnell** [comment]
Future enhancement to think about: replace "before your appointment" with the actual date.

**Comment by peggygannon** [comment]
@kristenmcconnell can you remind me what is the character count limit for this sentence?

**Comment by kristenmcconnell** [comment]
@peggygannon No limit, but VeText asked to make it as short as possible. Can we keep it around the same character count that we had planned for before, which was 165?

**Comment by peggygannon** [comment]
Hello, @kristenmcconnell here is my recommendation. Please let me know if you have any questions. 

Recommendation: 

OPTION A (identifying this questionnaire as coming from the provider) 
Fill out this questionnaire from your provider to help them prepare for your visit: https://www.va.gov/health-care/health-questionnaires/questionnaires/.


OPTION B: 
Fill out this questionnaire to help your provider prepare for your visit: https://www.va.gov/health-care/health-questionnaires/questionnaires/.


Please note, I used 'visit" above to shorten lines.  If we want to avoid that term, then just swap in appointment for "visit"  


Future state: Fill out this questionnaire by {date} to help your provider prepare for your visit.  


Additional feedback: 

1. I don't recommend using all caps for this messaging. It is hard to read for low-vision users and reads as shouting. 

2. Do we have any say about styling? If so, I recommend styling  time per our styleguide:  9:30 a.m. or p.m. (Not 09:30)

3. There are two different styles for phone numbers in this text. (one showing area code in parens, the other without). Our style is to not use parenthesis to set off the area code:

**Comment by kristenmcconnell** [comment]
@abuckley3385 See @peggygannon's response above.

**Comment by kristenmcconnell** [comment]
@peggygannon Thank you for the suggestions. I'm still concerned about how much attention those sentences can bring. What about something a little more commanding and shorter to match the other structures within the text. Thoughts on...

Prepare for your visit! Fill out this questionnaire from your provider: https://www.va.gov/health-care/health-questionnaires/questionnaires/.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell the update above ^^ works for me.  Thanks for checking back.

**Comment by kristenmcconnell** [comment]
@peggygannon Thank you!

**Comment by kristenmcconnell** [comment]
Wireframes updated.
https://zpl.io/bJXK7PK and https://zpl.io/2ppd4nr or https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780.
