### ISSUE TITLE
[UI] Denoting other questionnaires to complete on Confirmation page

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18080]
## User Story
- As a Veteran, I want to be able to know if I have any more questionnaires to complete once I've completed one questionnaire.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A wireframe of the confirmation page depicting a solution for how many other questionnaires a Veteran still has to complete will be delivered with the technical specifications needed for engineering to implement said feature.

## Tasks
- [x] Brainstorm different design solutions
- [x] Present solutions to product team
- [x] Finalize detailed mockup and callouts of

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
Ideas currently viewable within the "Changes up for Discussion after Second Usability Test" on Zeplin: 
https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780
or
https://zpl.io/VOOek8j

**Comment by kristenmcconnell** [comment]
@abuckley3385 After talking with platform and the MyVA team, I completed another iteration on the confirmation page. There is still much to explore before this would go to engineering to be implemented. I captured all of the items to revisit when it is time in the attached image. Since this turned into just an exploration, I'm proposing a change to the acceptance criteria that it is only review with product and incorporate any changes.

![Confirmation with Other Health Questionnaires.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/6c7f6204-ee2a-4a88-b14e-e05960e14dfb)
