### ISSUE TITLE
22-0994: Update VET TEC meta description

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#18087]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

Head / Metadata / content on the 22-0994 is incorrect.  Says "Vet Tec." Should say "VET TEC"

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/877acba9-8335-40fe-9c34-47d52625aade)

## Specs:
- Device: (e.g. iPhone 8, Macbook) - all
- Browser: (e.g. Firefox, IE 11) - all
- Test User _(if applicable)_: - NA

## Steps to Reproduce
- URL: Share VET TEC application in Slack to see og description displayed. 
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

Jhonny Gonzalez says: 

> The creation of these pages is located in [create-react-pages.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/create-react-pages.js) and it's pulling data from applications/registry.json.
> The "Vet Tec." content is coming from [here](https://github.com/department-of-veterans-affairs/vets-website/blob/5591ec0a21910dbc7f270ad4a280222e95368cec/src/applications/registry.json#L668).
> I think changing there should fix it.

## Acceptance Criteria
- [ ] meta content tags have `VET TEC` instead of `Vet Tec.`

When sharing 22-0994 on slack or other social media, the description "VET TEC" will display instead of "Vet Tec."

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by amyknox** [comment]
Full DEPO Slack thread here: https://dsva.slack.com/archives/CBU0KDSB1/p1609783885432000

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15529

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-01-05 at 11.52.32 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/260bfae7-f272-46ff-8c02-eb254efa9dcc)

**Comment by amyknox** [comment]
Works as expected.  Thanks for the _fast_ turn around!

**Comment by sonntag-adam** [comment]
Closing bug
