### ISSUE TITLE
[UI] Finalize Email Design with VANotify

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18084]
## User Story
- As a Veteran, I want to be able to receive email notifications that I have a health questionnaire to complete.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
Finalize the wording and design of the questionnaire email.

Current strategy and draft wording (minus usability testing feedback)
![Email Notification Strategy.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/070f4f69-745d-4875-984d-03bd095c3e75)

Email feedback from last [usability test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md):
- Veterans welcomed and even expected email and text notifications for health questionnaires.
  - “I like the whole idea of it.”
  - “It seems pretty straight forward.”
  - A few participants brought up the idea of notifications before they reviewed the prototype examples.
- Veterans are interested in receiving multiple notifications.
  - Eight out of ten participants mentioned that they would like to receive an initial and reminder notifications.
  - The most suggested time period for sending the initial and reminder notifications were:
  - Seven days in advance of the appointment, then again one day in advance.
  - Side note: They are particularly interested in a reminder if they didn’t complete the questionnaire.
- Additional findings: Emails:
  - Some participants suggested adding or emphasizing appointment information, such as date and time.
  - “Change the title of it, so it is less like a computer-generated survey, [such as] Dr. So-and-so would like to ask you a few questions before your next appointment.”

## Tasks
- [x] Coordinate with VANotify team
- [x] Finalize detailed mockup and callouts 

## Acceptance Criteria
- [x] Review email with product and VA PO
- [x] Updated email strategy documentation and wireframes with final solution from VANotify discussions
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
Sent a Slack message to Maria Becker and Todd Stanich.

**Comment by kristenmcconnell** [comment]
Met with VANotify today. VANotify information: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify

**Comment by kristenmcconnell** [comment]
Content reviewed by Peggy Gannon. Design viewable at: https://zpl.io/VOOek8j or https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780
