### ISSUE TITLE
[UI] Answer Questions from All MVP Usability Test

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18082]
## User Story
- As a VA PO, I am interested in answering the following questions after reviewing the last [usability research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md):
   - Was there a difference in the interest in printing the questionnaire between mobile and desktop participants?
   - Detail what portions of the After Visit Summary Veterans were interested in, such as lab tests, etc.
     - Remove the term "After Visit Summary" from the research report and replace with above details.
  - What were the IA question results for PTSD and TMI participants? 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
Answers will be provided to the project team as well as added to the final research report.

## Tasks
- [x] Review research videos.
- [x] Analyze findings, in order to answer the above questions.

## Acceptance Criteria
- [x] Incorporate findings into research report.
- [x] Communicate findings with product team.

**Comment by kristenmcconnell** [comment]
@mlighdc @abuckley3385 I was able to review the research and answer the above questions. Here are the findings. I will work on adding this into the research report now.

**Was there a difference in the interest in printing the questionnaire between mobile and desktop participants?**
- Mobile
   - 50% (2 participants) would print, but 50% (2 participants) would not print.
- Computer
  - 66% (4 participants) would print, but 33% (2 participants) would not print.
- The reasons given on why participants would print the questionnaires did not differ at all between mobile and desktop participants. Participants mostly sited printing as a way to remind them of what they wanted to discuss at the appointment. 
- Participants who were not interested in printing mostly stated that they see no need to print. No one sited lack of access to a printer as their reason why.

**What portions of the After Visit Summary are Veterans were interested in?**
- The most often referenced item that participants were interested in viewing in combination with their questionnaire responses was their “medical history;” however, there was no definition as to what the participants exactly meant by “medical history.
- Other specific items of interest mentioned were: 
  - a list of diagnoses/chronic issues, 
  - referrals resulting from the appointment, 
  - comparing what different doctors recommended (participant had received competing opinions in the past), and 
  - connecting their pre-visit questionnaire questions with a lab result. 

**What were the IA question results for PTSD and TMI participants?**
- 50% (2 participants) selected a badge/notification on an authenticated dashboard.
- The other 50% (2 participants) selected navigating to the appointments section.

**Comment by kristenmcconnell** [comment]
@abuckley3385 The research report on [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md) and the [downloadable PDF](https://drive.google.com/file/d/1fJP31TPYLjXwvtUuHe1h4DKG3HAuiczy/view?usp=sharing) have been updated as well. This story can be marked complete after the Epic and Milestone are added.

**Comment by mlighdc** [comment]
@kristenmcconnell thank you for the follow-up. You may already have incorporated my feedback based on your summary above. I can't access google drive so is there another way to access the downloadable PDF? Thanks.

**Comment by kristenmcconnell** [comment]
Adding the final PDF here as well. 
[https://app.zenhub.com/files/133843125/4058e569-49ed-4fc4-a00b-7b584a8aefac/download](https://app.zenhub.com/files/133843125/4058e569-49ed-4fc4-a00b-7b584a8aefac/download)
