### ISSUE TITLE
Document Contact information in form patterns library

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18092]
## Issue Description
Document Contact information in form patterns library

---
## Tasks
- [ ] Audit
- [ ] Create Sketch Templates
- [ ] Write documentation
- [ ] Review/approval of documentation
- [ ] Publish/announce pattern release

## Acceptance Criteria
- [ ] There is documentation for Contact information in form patterns library
---
