### ISSUE TITLE
STEM AD: Automate denial for 10203

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18118]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-decision_product-outline.md)

## High Level User Story
As an Education team member, I need stem applications that can be denied based on applicant information to be automatically denied so that the applicant receives feedback in a timely manner and the workload on the RPO is reduced.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work follows the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Acceptance Criteria
1. A process exists that denies applications after applicant submission.

## VSP Collaboration Cycle.
- [x] ~Project Kickoff~
- [x] ~Design Intent Collaboration~
- [x] ~Usability Testing Prep~
- [x] ~Research Plan Review~
- [x] Information Architecture (IA) Request - #20656
- [x] Analytics Request #21747
- [x] Midpoint review - #20726
- [x] ~Contact Center Review (NA)~
- [x] Staging Review - #21115 
- [x] Privacy and Security Review - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/224
- [x] ~Full Accessibility and 508 Office Audit~
- [x] Post-launch Check-in

## Supporting Artifacts:
1. N/A

**Comment by RileyRPM** [comment]
@mrblanco1

**Comment by RileyRPM** [comment]
Talked to Darrell and he said that "that the automated decision logic is handled during spool file generation for the form."
