### ISSUE TITLE
OS Check jobs will need to ignore eks deployed instances

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#18119]
## Issue Description
OS Check jobs currently failing in at least staging environment due to not being able to reach EKS deployed instances. We will need to put in an ignore of some sort for these instances.

---
## Tasks
- [ ] Team discussion on best path forward
- [ ] Best path forward taken

## Acceptance Criteria
- [ ] OS Check jobs no longer failing due to EKS deployed instances
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
Rather than removing checks against the eks cluster nodes, we have made a decision to refresh the worker nodes on a schedule to avoid them triggering the OS check. Closing this ticket and opening a new ticket for that work.
