### ISSUE TITLE
IRIS Q&As: Education -- WAVE

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#18130]
### Issue
For the launch of Resources and support MVP 1.1, content that fall into the "WAVE" category under education & training needs to be developed based on the following:

- https://gibill.custhelp.va.gov/
- [Product guide pages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/Benefit.Hubs.Product.Guide.docx)
- Credible external sources as needed

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into learning center page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

- [x]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

 - [x] PW to develop draft copy (Laura)

 - [ ] PW to assign tags (Laura)

 - [x] DEPO to complete "first look" (Beth) 

 - [ ] PW to create two GH tickets:
        "Content Review" ticket with 2 tasks: substantive DEPO review (Beth) and PW copyediting (Randi)
        "Page Build" ticket with 3 tasks: Drupal build (Laura or Selina) and final SEO review (Laura)

### Acceptance Criteria
- [ ] Copy deck ready for 2nd DEPO review and attached to a content review GH ticket.
- [ ] Page build GH ticket exists in icebox

### Up-to-date copy deck
Please use the deck shown here and replace it when you make edits/comments to ensure that the latest document is always here, at the top of this ticket. 
[rs-1.1-education-wave-v0.2-012821.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5895250/rs-1.1-education-wave-v0.2-012821.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- The Education WAVE article is ready for you to take a first look. Word doc is attached at the top of this ticket. Let me know if you have any initial feedback you want me to address before you do a substantive review.

**Comment by lwalsh617** [comment]
@bethpotts -- Per our status call last Friday, I made some edits to the copy deck attached to the top of this ticket. I reviewed it against on our new content checklist. I also looked for any related content on our tier 1 pages in case we wanted to move it, but did not find any. This is ready for your first review. Let me know if you have any initial feedback you want me to address before you do a substantive review. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 You can see my edits here.
@lunascoop Please build this page in drupal. Thanks!

[https://app.zenhub.com/files/133843125/98a038b0-c4d5-4a97-b805-9808a67f1247/download](https://app.zenhub.com/files/133843125/98a038b0-c4d5-4a97-b805-9808a67f1247/download)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Next tasks/tickets that you can set up: 
I'm getting a stakeholder review next (ticket 1)
Selina can work on building the page in drupal (ticket 2) 
Selina can incorporate edits into drupal when they come back from the stakeholder (ticket 3)
Randi can copyedit and set to publish after all the above is done (ticket 4)

**Comment by lunascoop** [comment]
The page has been created w/ the exception of the link to the overpayment and debt article:
GI Bill WAVE FAQs: http://preview-prod.vfs.va.gov/preview?nodeId=16484

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 @RLHecht This came back from the SME with NO edits required, so we can move forward with publishing. Going forward, do you all want to decide how to track things with tickets? In other words, how much to break down the work by individual tickets? We can choose to keep all the steps in one ticket as we did with this one. I'd just like to be consistent about our overall approach ticket to ticket. @lwalsh617 and I have talked about the fact that there's no longer a need for a "first look" from me/DEPO. And the process now is that I see the Word doc to make substantive edits before Randi copyedits. With that in mind, going forward, you can adjust the check boxes under Tasks. 

Next for this one: final edit by Randi, then publish. Since this is the 6th edu article, you'll need to add the "Go to all articles" link to the R&S landing page--and of course step through the pre-pub checklist. thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht When Danielle's article about overpayments and debt launches, we'll want to add it to the related links in this WAVE article.

**Comment by RLHecht** [comment]
Page reviewed and published! Moving to validate and will close after the next deploy.

**Comment by RLHecht** [comment]
This page is now live. Closing ticket.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Re-opening this ticket to track a quick link addition.
We wanted to add a link to a debt page. Here's my recommendation. If you're good with it, let me know and I'll make the change in Drupal. Thanks!
![image](https://user-images.githubusercontent.com/53535663/129422364-4ab6c55e-b089-41d6-b58f-7a83a502954a.png)

**Comment by bethpottsVADEPO** [comment]
Hi @lwalsh617--yes, thank you for adding that link!

**Comment by lwalsh617** [comment]
@RLHecht - The text link I added works fine in Drupal in edit mode, but I get a 403 error when I tested it in preview mode. Not sure why. Linkit found the url okay. Let me know if there's something I should do differently. Thanks!
http://preview-prod.vfs.va.gov/preview?nodeId=16483

**Comment by RLHecht** [comment]
@lwalsh617 Links to internal pages using the node ID don't work on the preview server. You have to test them in the latest view mode. This link is all good and I published the page.
