### ISSUE TITLE
[UI] Update examples in Life Event question 

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18131]
## User Story
- As a Veteran of an advance age, I want to see an example within the Life Events question that relates more to my phase of life, such as retirement or caregiving.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
An updated wireframe showing the new example will be delivered with the technical specifications needed for engineering to implement said feature.

Within the last [usability test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/research-findings.md), the following item was found,
- Two older participants commented that our examples of life events were for younger people and that they would like to see examples that apply to them (retirement or caregiving).

## Tasks
- [x] Finalize detailed mockup and callouts of [new wording](https://zpl.io/2jzjwGq)

## Acceptance Criteria
- [x] UI review meeting with product/team and engineering for feature capabilities, layout and callouts
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
Add in retirement and not caregiving.

**Comment by kristenmcconnell** [comment]
@abuckley3385 I reread the current text. It already says "change in your job."

Here is the full current question.
Are there any other concerns or changes in your life that are affecting you or your health? (For example, a marriage, divorce, new baby, change in your job, or other medical conditions)

Some thoughts on possible changes (changes in bold):
- Are there any other concerns or changes in your life that are affecting you or your health? (For example, a marriage, divorce, new baby, change in your job **status**, or other medical conditions)
- Are there any other concerns or changes in your life that are affecting you or your health? (For example, a marriage, divorce, new baby, change in your job, **retirement,** or other medical conditions)

**Comment by kristenmcconnell** [comment]
@abuckley3385 As discussed on Slack, I updated the wireframes by adding the word "retirement" to the question, so the Life Events question now reads:
Are there any other concerns or changes in your life that are affecting you or your health? (For example, a marriage, divorce, new baby, change in your job, retirement, or other medical conditions)

@mdewey Zeplin is up-to-date to reflect the above wording change: https://zpl.io/2jzjwGq.
