### ISSUE TITLE
Front end: add header to identify FL as source 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18136]
## Issue Description
This work will differentiate the source of traffic querying PPMS (Facility Locator vs VAOS)

Back end implementation is in https://github.com/department-of-veterans-affairs/va.gov-team/issues/18144

---
## Tasks
- [ ] Facility Locator front end needs to pass static header to identify FL as source of traffic 
- [ ] Once header is identified, coordinate with VAOS team 

## Acceptance Criteria
- [ ] Regardless of facility type, Front end sends header identifying FL as source of traffic 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Per Lance, a front end header is already in place

**Comment by darkbushido** [comment]
Here is a link to [Grafana](http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v1%2Ffacilities%2Fccp&var-backend_controller=v1%2Ffacilities%2Fva&var-backend_controller=v1%2Ffacilities%2Fva_ccp&var-frontend_app=All) to see the current dashboards
