### ISSUE TITLE
Back end: capture header to identify FL as source

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18144]
## Issue Description
This work will differentiate the source of traffic querying PPMS (Facility Locator vs VAOS)

Front end implementation is in https://github.com/department-of-veterans-affairs/va.gov-team/issues/18136
---
## Tasks
- [ ] Capture a header for PPMS traffic on backend (tag statsd data with header so traffic can be filtered) 
- [ ] Tag radius and # of results
- [ ] Once header is identified, coordinate with VAOS team 

## Acceptance Criteria
- [ ] Traffic originating from Facility Locator can be filtered
- [ ] Radius and number of results info can be captured

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by darkbushido** [comment]
we are already doing something similar to this with [Grafana](http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v1%2Ffacilities%2Fccp&var-backend_controller=v1%2Ffacilities%2Fva&var-backend_controller=v1%2Ffacilities%2Fva_ccp&var-frontend_app=All) I'm meeting with @saneshark later today to go over how this effects the metrics around calls directly to PPMS
