### ISSUE TITLE
Reorganize left panel / remove form controls as a folder 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18145]
## Issue Description
From usability testing of storybook, we found that users didn't identify with items being under form controls. Reorganize left panel / remove form controls as a folder 

---
## Tasks
- [ ] Remove form controls as a folder 
- [ ] Move all items under form controls into the left panel (outdent)

## Acceptance Criteria
- [ ] Form controls folder is removed 
- [ ] Items under form controls are now listed in the left panel
