### ISSUE TITLE
In Storybook, remove the 'usage' section and create Designer Documentation section 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18143]
## Issue Description
Based on usability testing, we discovered that designers had a hard time finding documentation when it was labeled usage. Team has decided to  remove ‘usage’ and create designer documentation section. &  Update how to use Storybook

---
## Tasks
- [ ] Remove usage sections
- [ ] Create designer documentation section 
- [ ] Update how to use storybook page by removing usage section 

## Acceptance Criteria
- [ ] Usage sections are gone
- [ ] Designer documentation section has been created
- [ ] How to use storybook page does not reference usage section
