### ISSUE TITLE
Link TTY: 711 number in footer and right rail of hub landing pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#18151]
## Issue Description
We need to make the TTY: 711 listed in the footer of the VA.gov home page and right rail of the benefit hub landing pages linkable using an aria label. Both the TTY and 711 should be in the link. ![Screen Shot 2021-01-05 at 4.24.16 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/013ee9f7-7bb7-4796-af4a-1788ba485831)

![Screen Shot 2021-01-11 at 9.25.19 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8c270841-1540-4f58-9f96-11c141224228)

## Tasks
- [ ] Fix TTY: 711 in footer so it is linked within an aria label.
- [ ] Fix TTY: 711 in right rail so it is linked within an aria label.
## Acceptance Criteria
- [ ] Link is showing on live site

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@ncksllvn @kelsonic Beth had asked me to fix this but I can't access the footer so I created a ticket for you. Not sure if you can get to it this sprint or not. FYSA @brianalloyd

**Comment by kelsonic** [comment]
Need to make this a link in the following locations:

https://github.com/department-of-veterans-affairs/vets-website/blob/f621103f458d47045646251e35f5c63cea3d0b3b/src/platform/static-data/footer-links.json#L222

https://github.com/department-of-veterans-affairs/vets-website/blob/f621103f458d47045646251e35f5c63cea3d0b3b/src/platform/landing-pages/header-footer-data.json#L223

fysa @sanlouise

**Comment by kelsonic** [comment]
We don't support `aria-label` for links in the footer atm

**Comment by RLHecht** [comment]
@kelsonic But we are still able to link them just not in aria labels? FYSA @bethpottsVADEPO See Kelson's note above.

**Comment by kelsonic** [comment]
@RLHecht Oh no I was just saying that `aria-label`s aren't _currently_ supported in the footer.json, but that it's definitely feasible we just need to add that functionality 🙂

**Comment by sanlouise** [comment]
@RLHecht 

Hi Randi, I was not able to add the href and aria-label to the TTY in the right rail because the link would have to change in the CMS to include a `fieldPhoneNumber` and a `fieldLink`, and ideally a `fieldAriaLabel` from the CMS which does not exist. 

![image](https://user-images.githubusercontent.com/14869324/104616686-d5871a80-5647-11eb-918d-555774c7e5a8.png)

![image](https://user-images.githubusercontent.com/14869324/104617119-4d554500-5648-11eb-9515-eb482058c65d.png)

**Comment by brianalloyd** [comment]
@RLHecht @kelsonic is this something that we need to punt over to the CMS team?

**Comment by brianalloyd** [comment]
@kevwalsh tagging you on this ticket, refer to the notes above concerning CMS.

**Comment by brianalloyd** [comment]
Discussed with CMS, looking to hardcode on Frontend.

**Comment by Rleahy22** [comment]
Moving this back to validate as I think the github outage last week affected the ticket stage

**Comment by brianalloyd** [comment]
@Rleahy22 that's exactly what happened, thanks for working these details.
