### ISSUE TITLE
[Accessibility] [UI] Dev Intent Review

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18152]
# Issue Description
As a Veteran, I need my health questionnaires to be accessible.

# Tasks
- [x] Write [accessibility review ticket - follow Dev Intent Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+jenstrickland&labels=508%2FAccessibility%2C+development+review%2C+product+support&template=vsa_request_dev_review.md&title=Request+a+VSA+dev+intent+or+spot+check+review+for+ENTER_PRODUCT_NAME)
  - Must include content from stories: #17805 , #18131 , #15718 , # 18080
- [x] Incorporate or document accessibility feedback into the wireframes for the team review

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Published mockup link exists and it is added/updated within the product feature outline
- [x] Accessibility review is complete and feedback is incorporated into the mockup

**Comment by kristenmcconnell** [comment]
Meeting with Josh Kim on a call tomorrow instead of the Dev Intent ticket from the past.

**Comment by kristenmcconnell** [comment]
Meet with Josh Kim on January 21, 2021 on a call, instead of writing a ticket.

**Comment by kristenmcconnell** [comment]
Incorporated all accessibility comments into wireframes.
