### ISSUE TITLE
[Content] [UI] Review of changes from All MVP Workflow Research

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18155]
## User Story
- As a Veteran, I want the wording within my health questionnaires to be understandable.

## Tasks
- [x] Complete a content review by sending Peggy Gannon a message within the vfs-platform-support channel and tagging her within the comments section of this story
  - Review must include stories: #17805, #18131, #15718, #15125, #18080, and #18084.
- [x] Update wireframes with content feedback

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Published mockup link exists and it is added/updated within the product feature outline
- [x] Feedback from content is incorporated into the mockup

**Comment by kristenmcconnell** [comment]
@peggygannon As stated in our meeting this afternoon, the best place to look to review all of the items in this tickets is within my Zeplin file: https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780.

Please review the following sections of the Zeplin:
1. Changes up for Discussion after Second Usability Test
2. Error Messages
3. Notifications (email only)

As we also discussed, the confirmation page and that status indicators are a work in-progress. I will keep you up-to-date on this items.

**Comment by kristenmcconnell** [comment]
@peggygannon I can post again! Wahoo. As a I mentioned in Slack, all of my design unknowns have cleared up, so Zeplin is totally ready for your review.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell Here is my feedback and a few questions to the updated screens. Let me know if you have any questions!

**Questions**: 
1. For a Canceled card scenario, it tripped me up a bit to see the "View and print questions" button still clickable. 
Did users get get confused with this blue button still clickable even if appt was canceled?  

2. Can you give me more info on when a user would see the error message: **Some parts of this might not be working**? Do you know if trying again would fix this for the user? Trying to see if I can recommend a more detail/descriptive message..  

**Content recommendations**

**Questionnaire list screen**
Per style, please add hyphen  when To-do appears before questionnaires> To-do questionnaires

For this line of content "Access in-progress questions until"   maybe update to: “Available until” to mirror treatment of this line in the other cards. 

**Demographics screen**
Please remove colon after "You have an upcoming appointment:"

**Reason and concerns screen**
What’s the reason for your visit? 
Routine or followup visit? 

These headers seem to compete with each each. Should the second one have a smaller point size/font? 

**Error messages**
I recommended changing "questions" to "questionnaire" in this message

**We’ve run into a problem viewing and printing your questionnaire**
We’re sorry. Something went wrong on our end. Please try again. 

**Notifications**
no changes, as we had discussed this line of content in earlier ticket. 

can P in provider be lowercase?

**Comment by kristenmcconnell** [comment]
@peggygannon 

To answer your questions:
1. We originally had the “canceled appointment, but in-progress questionnaire” card on the completed tab. During usability testing, Veterans commented on how they would like to access this information, so they could save what they wrote before it disappeared (they will disappear on the old appointment date). Therefore, we thought it would be overlooked on the completed tab, since the action on why people want to access this is time-sensitive. Maybe we need to highlight the “Available until” information more or change what the status says? Thoughts?
2. The scenario that engineering and I talked about was if the services went down while the form was being filled out, so a connection to Lighthouse, where we are saving these questionnaires, or connection to appointment information goes down.

I have a question for you. If we hyphenate To-do when it appears before questionnaires, do I need to hyphenate the To do tab?   All of your other recommendations make sense. I will work them into the designs.

**Comment by kristenmcconnell** [comment]
I talked to engineering more about the error message that you had a question about. Fundamentally, we need something for when the services go down when the Veteran is in the middle of working on the form. Below is what engineering wrote:

If its the Save-in-progress (SiP) system, they would still be able to submit the application (this is handled by platform already)
If the PGD/Lighthouse went down then would not be able to submit the application (this is what we need error messages for). If the SiP System is still up then the data has been saved
If the vet-api went down, this includes both the SiP and PGD, then they will not be able to do anything and the form is dead in the water. This is the worst case scenario. The last scenario is out of scope as I would say.

**Comment by kristenmcconnell** [comment]
@peggygannon I also talked to engineering about the other error messaging that I had you look at related to a failure when generating the PDF. We agreed that it is more of a "please try again later" without the button appearing on the screen situation compared to what I had originally drawn with the button showing and telling the user to immediately try again. 

Below is the refined error message. My question to you is...which of the following title patterns should I use in this case?
1. We've run into a problem viewing and printing your questionnaire
2. Viewing and printing your questionnaire isn't working right now

I still like #1, but wanted to ask you.

![Questionnaire List - Completed - Error Message.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/b82c757e-027e-4c9f-a9e8-797b6f80f243)

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell thank you for the follow up!

1. We don't need to hyphenate To do on the tab. We only need to hyphenate it when it used as an adjective and before a noun. 
2. Yes, agree that  that option 1 is what we should use for the PDF error **We've run into a problem viewing and printing your questionnaire**
3. Thank you for the background on the other error. I will drop in another error message in a little bit. 
4. Yes, agree that the canceled appointment questionnaire shouldn't go under the Completed tab. 
The canceled label applies to the Appointment, not so much the questionnaire.  Another question:  if a user "reschedules" an appointment, do they get a new questionnaire or would they use this questionnaire for the reschedule appt?


I wonder if using an In-Progress label would work (since the questionnaire is technically "in progress"), with some content adjustments like this: 

{label} In-Progress
**Primary care questionnaire**
for your canceled or rescheduled appointment at {name of VA Medical Center}. You can still access this questionnaire for [x] days. 

Access until
{date}

Let me know your thoughts!

**Comment by kristenmcconnell** [comment]
@peggygannon If an appointment is "rescheduled," it is essentially a cancellation, then a completely new appointment in the EHR. Therefore, the Veteran would get an entirely new questionnaire. This is also why Veterans were interested in not losing the work that they already did on the questionnaire.

Good point that the canceled appointment, but in-progress questionnaire should probably have the In-progress status label. I will change that and upload a version here for you to see.

**Comment by kristenmcconnell** [comment]
I'll talk to engineering about the "You can still access this questionnaire for [x] days." sentence to see if we can add it. If not, I think the "canceled appointment, but in-progress questionnaire" card still works.
![Group.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8da62b63-80d9-4183-b36d-06a1501b1591)

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell Here my content recommendation for the error state where user isn't able to submit the application. But the SiP System is still up. 

I've offered 2 options. The second options lets users know they can continue filling out the questionnaire.. Not sure if this is accurate or if they can't proceed when the service goes down? Do you want to run this by the engineers to see which message is most accurate? 

OPTION 1 

**We can’t submit your questionnaire right now**
We’re sorry. Something went wrong and we can't submit your questionnaire. The information you’ve entered so far has been saved. If you’re having trouble, please try again later.

OPTION 2 (tells users they can still continue filling out questionnaire)

**We can’t submit your questionnaire right now**
We’re sorry. Something went wrong and we can't submit your questionnaire. You can continue to fill out your questionnaire and your information will be saved. If you’re having trouble, please try again later.

**Comment by kristenmcconnell** [comment]
Thank you very much. I updated the wireframes. I will present both error state wording options to engineering. I think that answers everything. I'll close out this story.
