### ISSUE TITLE
Set up CI process that builds and pushes the Loki container to ECR

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18156]
## Description
There is already a vsp-infra-loki repo. There is a CI job with GitHub Actions (GHA)I, but we need to further customize. 

## Background/context/resources
This job does push containers, but there is a deploy step in there that is no longer valid. So, we need to fix that, and also pushing the right version of the container to ECR. 

## Technical notes
TBD

---
## Tasks
- [x] Modify GHA workflow to test the container on all commits 
- [x] Modify GHA workflow to push container to ECR on successful merge
- [x] Modify GHA workflow to tag container with semantic release (already doing) 
- [x] Modify GHA workflow to include promtail + nginx along w/ Loki

## Definition of Done
- [x] Loki CI process will be set up using CircleCI 
- [x] The Loki CI pipeline will work with the ArgoCD pipeline

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
We have the CI pipeline in place, and are working on the enhancement to integrate that pipeline with tanka + ArgoCD

**Comment by jhouse-solvd** [comment]
This is good to go.
