### ISSUE TITLE
EKS - Install ArgoCD on "platform-tools" cluster in STAGING for the deployment of ops-owned services

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18153]
## Issue Description
We want to install ArgoCD on the platform-tools EKS cluster that will be used for hosting ops-owned services and tools that support the VSP.

---
## Tasks
- [x] Install ArgoCD on platform-tools cluster in STAGING
- [x] Test deployment of applications to this cluster using ArgoCD

## Acceptance Criteria
- [x] ArgoCD will be installed and working for additional services to be deployed
- [x] ArgoCD configurations will be checked in to relevant code repositories

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tskinn** [comment]
requested an oauth app be created for argo https://github.com/department-of-veterans-affairs/github-user-requests/issues/5726

**Comment by jbritt1** [comment]
Hooked ArgoCD on staging cluster to [manifests repository](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) (this has also been done in dev).

We should likely decide on how to get this change "codified" as it was initially set up via manual interaction with the ArgoCD GUI.

**Comment by jhouse-solvd** [comment]
@tskinn - would you consider this done? any other notes or ongoing work for this?

**Comment by jbritt1** [comment]
We now leverage a single ArgoCD deployment in utility to manage the other clusters. Is this okay to close at this time?
