### ISSUE TITLE
New Deployment Workflow - Write the glue that modifies app manifest when new release is pushed to ECR

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18154]
## Issue Description
Implement working auto-deploy process aka “write the glue” (in the form of script or other automated process) to modify an application's manifest when new a release is pushed to ECR (test this with deploying <insert app name> to STAGING “platform-tools” Cluster) 

Background: 
[Thread here](https://dsva.slack.com/archives/CTYQL39FE/p1609887932449400) with outline of desired workflow: 

- Any resources needed in AWS like ECR Repos, S3 buckets, databases, etc, will be created in Terraform in the appropriate environment
- There is an application manifests Github repository.
- Each service or application (Loki, Grafana, vets-api, etc) has it’s own Github repository, i.e.: vsp-infra-grafana or vsp-infra-loki which has CI to test, build, and push Docker containers to the appropriate ECR repo. CI runs on every commit to test/build/push the container to ECR with a commit hash tag, then on a PR merge, it performs a release, and then pushes a container to ECR (or retags an existing container from that Commit hash).
- On a PR Merge, there is a script that edits the application manifest in the previously mentioned application manifest Github repository, to update the helm chart, Jsonnett, etc.
- ArgoCD detects the change in the manifest and redeploys the application

---
## Tasks
- [x] Double check that all of the existing resources are managed as desired
- [x] Verify application manifests for each app in its own repo
- [x] Create Pipeline (Create tasks in CI config for CircleCI that checks out the application manifest from GitHub, modifies it, commits it, and checks it in)

## Acceptance Criteria
- [X] Sample application like ALB Controller is deployed via CircleCI/Argo and re-deploys automatically when a merge is made to the [aws load balancer controller repo](https://github.com/department-of-veterans-affairs/vsp-infra-aws-load-balancer-controller)
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tskinn** [comment]
@jhouse-solvd why was this closed? Are we not doing this anymore?

**Comment by jhouse-solvd** [comment]
@tskinn @jbritt1 - please forgive the confusion as this was closed intentionally. this is definitely still a priority, and please continue as planned / discussed. thank you!

**Comment by jhouse-solvd** [comment]
This is done.
