### ISSUE TITLE
Phrasing and Commonly Asked Questions Research

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#18169]
## High Level User Story
As a product team focused on Search, we want to know what the most frequent questions (e.g. pain points) are asked of the VA customer care touch points, including:

|**Data Source**         |**Contact Name**         |**Source**| **Type of Information + Notes**|
|-----------------------|------------------------------|------------------------------|------------------------------|
|Call Center             |Megan working with Chante |https://va-gov.domo.com/page/1744754544 |[CallType_Subtype_PROD 10.23-11.30.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5776201/CallType_Subtype_PROD.10.23-11.30.xlsx) |
|Resources & Support             |Denise working with Brian  |https://www.va.gov/resources/ |top searched terms, read articles |
|Health Secure Messaging Data           |TBD|TBD|Information about what they are looking for in regards to their health information. Would this be available given privacy concerns?|
|Top Search Terms from MyHealtheVet        |John NOW has access to MHV dashboard in Search.gov|Search.gov |Top search terms and user research|
|Top Search Terms from eBenefits          |John working with search.gov |TBD |TBD|
|GI Bill Help Portal      - low priority       |Megan working with Chante |https://gibill.custhelp.va.gov/ |Ask a question about your VA bill  |
|IRIS  -low priority            |Chante |https://iris.custhelp.va.gov/app/ask |Ask a question about your VA benefits |

## Tasks

- [ ] To document the top questions asked by veterans and their care-takers in a categorized format (e.g. Health, Education, Careers, etc.)
- [ ] Identify keywords/phrases/concepts from those questions
- [ ] Extract any words that are captured in "Our Top 50 Search terms for va.gov"
- [ ] Conduct search for remainder of words and analyze the results that come back. Do those terms provide relevant search results. 

## Goals
- To determine how effective on-site Search is at navigating users to answers for their top questions. Is there content missing from VA.gov that would enhance their ability to answer their questions? Does the content we have need to be rewritten so that it is more discoverable by veterans. 

## Issues to create within this Epic

```
- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

## How to configure this issue
- [ ] **Labeled with `discovery` and `research` and `team-name`**

**Comment by johnhashva** [comment]
@denisecoveyduc + @mgleo just capturing some info I've received from Chante and a note from our convo with Lauren so we have a placeholder in our overall research plan.

**Comment by mgleo** [comment]
That call type data is very helpful. I wonder if call transcriptions are available? It would be helpful to see the phrasing used in calls.

**Comment by johnhashva** [comment]
@mgleo you're right, that additional context would be far more helpful.   Let's discuss how we go about this during our planning session today.

**Comment by denisecoveyduc** [comment]
Changed the title of this one as it was pretty generic and leading to some confusion.

**Comment by denisecoveyduc** [comment]
@johnhashva @mgleo  and I created a table with the contact names that we think would be appropriate for each source of data. 

Could you please review the revised information and confirm? Specifically we are wondering if you can validate the contact source, the tasks and the overall goal for this issue?

**Comment by johnhashva** [comment]
@denisecoveyduc I will follow up on the MyHealteVet and eBenefits search terms and post updates here.

**Comment by denisecoveyduc** [comment]
Extracting Iris resources from #16191

Requested access to recent Contact Center Monthly Reports similar to these:
[February 2020 Google Sheets](https://drive.google.com/file/d/1ytpv0UOdDrl8itRDiCYX7EOwm8dlStvX/view)
[March 2020 Google Sheets](https://drive.google.com/file/d/162Cn_srmNNQ3d7X62HIOOTdVrm2HSwQN/view)
[July 2020 DOMO](https://va-gov.domo.com/page/1744754544)

**Comment by johnhashva** [comment]
1/26 Update: I am in contact with product leads who will (hopefully) give me permission to include MHV and eBenefits in my Search.gov dashboard so we can analyze usage data as we see fit.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO just received access to MHV as part of my Search.gov dashboard so we can run any queries we want.   Will run a report and post initial findings here.
