### ISSUE TITLE
Homepage - Update schedule CTA section styles

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18161]
## Issue Description
On the VAOS homepage, update the styles for the section above the appointment cards.

---
## Tasks
- [ ] Schedule an appointment section
- [ ] Express Care section

## Acceptance Criteria
- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag
- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
- Mobile - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/Jne5e4z#Inspector
- Mobile states - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/ZOM9MYJ#Inspector
- Desktop/Tablet - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/v89m9lQ#Inspector

## Out of scope
- Vaccine CTA

**Comment by narin** [comment]
@outerpress @laurenernest @peggygannon 

There are some conditionals to be aware of if we are planning on making any copy updates:

# Schedule appointment
Copy is conditional depending on whether we have direct scheduling (DS) or community care (CC) enabled/disabled.

## DS: enabled, CC: enabled
![image](https://user-images.githubusercontent.com/786704/103802266-bf53db80-5003-11eb-8b9e-411f148f08b3.png)

## DS: enabled, CC: disabled
![image](https://user-images.githubusercontent.com/786704/103802304-ca0e7080-5003-11eb-9abf-bcfd3059f27a.png)

## DS disabled, CC enabled
![image](https://user-images.githubusercontent.com/786704/103801791-1311f500-5003-11eb-92fc-cb2bb58e516b.png)

## DS: disabled, CC disabled
![image](https://user-images.githubusercontent.com/786704/103801724-fd9ccb00-5002-11eb-9f69-edca9e8cc9b2.png)


# Express Care
Copy changes depending on whether user has access to a clinic that has an express care window open:

## Express Care window open
![image](https://user-images.githubusercontent.com/786704/103802604-43a65e80-5004-11eb-9036-d7fd42aa0c47.png)

## Express Care window closed
![image](https://user-images.githubusercontent.com/786704/103802636-4d2fc680-5004-11eb-922a-03e30a2e4478.png)

**Comment by outerpress** [comment]
Thanks @narin ! @peggygannon let's address the design/content needs for this in the larger home page iterations ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18070

**Comment by peggygannon** [comment]
@outerpress sounds good. I've added comments to the prototype.
