### ISSUE TITLE
Homepage - Update canceled appointment card styles

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18165]
## Issue Description
On the VAOS homepage, update the styles for canceled appointments.

---

## Tasks
- [ ] Canceled appointments in Canceled
- [ ] Verify Canceled appointments in Requested
- [ ] Verify Canceled appointments in Past

## Acceptance Criteria
- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag

- [ ] When VAOS homepage loads, then default view is Upcoming appointments

- [ ] When Canceled is selected from dropdown, then canceled confirmed appointments display

- [ ] When Canceled is selected from dropdown, then appointments display in reverse chronological order

- [ ] When Canceled is selected from dropdown, then canceled appointments up to 395 days in the future display
- [ ] When Canceled is selected from dropdown, then canceled appointments back to 30 days in the past display

- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
- Mobile - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/L0Ojw3y#Inspector
- Desktop/Tablet - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/PGDJyjP#Inspector
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/6e7be4cf-2eae-4b3d-ba12-e57d1526f0cf)

## Out of Scope

- Appointment detail pages

**Comment by narin** [comment]
@outerpress @laurenernest Should canceled **requests** show on this list as well?  The mockup calls for appointments to be grouped by month.  If we're following the design for the request cards, they do not have dates listed, so I'm not sure which month to organize requests into.

![image](https://user-images.githubusercontent.com/786704/106487500-91797f80-6467-11eb-8393-dacdd25dbead.png)

I *could* put the request under the month it was created, but not sure how clear that'd be to the user.

**Comment by outerpress** [comment]
@narin I'm thinking we keep the canceled list just for canceled appts and express care, and only show canceled requests in the "requested" list. 

We'll have to do some testing after the fact to see if this assumption meets the user's mental model, but basically the idea is that a requested appointment isn't an actual appointment, so it would be confusing to see canceled requests mixed in this list, if I'm looking through it from the perspective of wanting to know my medical history.
