### ISSUE TITLE
Add Error Notification Messaging for Non-LOA3 Access

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18171]
## Story
As a Veteran using VA.gov, I want to be informed when my credentials need extra attention so that I can resolve any proofing issues and move forward with my intended objective.

## Background
It has been determined, in testing, that there is the possibility of Veteran user accounts not being fully proofed and they need some messaging around why they aren't seeing what is expected and what they can do about it.  Profile uses a "verify ID.me" component that supplies messaging as well as instructions on how to proceed.

## Considerations
- [View Payments mockup](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/7ccc0d63-bb20-4679-bcd7-a2f6ed4f69ab/)
- Testing can be done with a vanilla account using a personal email address as it will be LOA1

<details>

<summary>Expand to see error messaging for non-LOA3 users</summary>

![Screen-Shot 2021-01-05-at-11.40.57 AM.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/c01c2cff-1dbb-487c-bc66-016e137e2e78)

</details>

<details>

<summary>Expand to see example of level of access, where we check for `current`</summary>

![Screen-Shot-2021-01-06-at-9.16.41 AM.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/35e38e18-875f-4e9c-a0d9-f8c2be733b74)

</details>

## Tasks
- [x] Include the action the Veterans is trying to take in the `verify` component header (In this case: "Verify your identity to view your payments")
- [x] Check that header values (h1, h2, h3, etc) progress in the correct fashion

## Acceptance Criteria
- [x] If a Veteran is not LOA3, they will be presented with appropriate error messaging
- [x] A PR has been requested for merging
