### ISSUE TITLE
[Design] - Generate mockups for `Sign as a representative` initiative 

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18178]
## Issue Description

- How do we give Veterans the ability to sign as a representative (and attach documentation) without detracting from the ease of the form?
---
## Tasks
- [x] Prototypes created

## Acceptance Criteria
- [ ] Design intent review with Collab Cycle
- [x] Move forward with research
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sshein** [comment]
codesign session conducted today, Jan. 14th. Mural board can be found here: https://app.mural.co/t/vsa8243/m/vsa8243/1610652864386/2d5d0b2c68ca3431c21ed1aa3aba8bc73539db5f

**Comment by ala-yna** [comment]
## Takeaways from 2/3 meeting:
- We will move forward with asking the representative questions within the form (Option 2 and Option 3)  - either at the start of the form or before signature/submit
- Run a comparative study addressing: placement within the form; if the question will dissuade caregivers from starting/completing the from, etc
## Timeline:
- Submit research plan: February 5
- Recruitment starts: February 8
- Testing begins: February 16
- Synthesis following completion of usability study
##  Action items:
- Revise content (make more conversational and softer in tone)  - sync with content (around representative)
- Iterate on signature page (if representative is signing)
- Create research plan

**Comment by jonathanjnelson** [comment]
Questions for Caregiver program team (2/8/21) 

**Legal requirements for signing as a representative** 
- What name do we want the user to enter on the signature page? 
  - Representative's name? 
  - Veteran's name? 
  - Both? (e.g. Jane doe on behalf of John Doe/John Doe, POA Jane Doe) 
- Do we want/need to validate the representative's name on the signature page? (collect the name earlier in the form) 
- Is there specific evidence we want the user to upload? 
  - Limit on supporting documentation uploads?

**Comment by jonathanjnelson** [comment]
Current prototype for Option 1 (end of form): [Option 1](https://vsateams.invisionapp.com/share/W5ZZA7U3DUE#/444247168_Own_Chapter-2-2)

**Comment by ala-yna** [comment]
**Notes from 2/8**
- Prefer both names in signature box (rep on behalf of Veteran)
- Do we need to change the wording of the Statement of Truth heading and/or content?
- Will need to work with Cari & Caregiver policy team
- Prefer asking the question towards the end of the form (not the beginning/to scare people off)
- Don't necessarily need to match the name of the representative 
- 5% of applications that might use this functionality
- CARMA LOE - maybe nothing?

**Comment by jonathanjnelson** [comment]
[For awareness: Prototypes used for Feb 2021 usability study ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19805)
