### ISSUE TITLE
Search analytics tagging fixes

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#18174]
## Description
This ticket is to update the search analytics tagging to fix / streamline tagging

## Tasks
- [x] phased rollout tagging needs to be triggered only once per session
- [x] typeahead enabled flag is not populating correctly on search-results page search bar
- [x] A new variable to add to onsite-search-results-click event push -- 'search-result-type'. This comes as an addition to various types of search results that are now presented on /find-forms. In our case for type ahead and regular search we will just always push 'title' since there's only text links as results there

## Definition of Done
- [x] Above tasks have all been completed

**Comment by srsuddath** [comment]
The fixes for this ticket have been merged in and it can be closed!
