### ISSUE TITLE
Homepage - VVC appointment details

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18187]
## Issue Description
Add VVC appointment details page styling and interaction.

---
## Tasks
- [ ] ~~VVC pending~~ (waived)

- [x] VVC confirmed

- [ ] ~~VVC canceled~~ (waived)

## Acceptance Criteria
- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag

- [ ] When user clicks/taps a VVC appointment card, appointment details open on a new page

- [ ] Appointment detail page has a unique URL

- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs
- Mobile confirmed - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/Kv9bDLV#Inspector
- Mobile expanded - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/wL9poM9#Inspector
- All fields template - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/ELn2Ldx#Inspector

**Comment by LanceGundersen** [comment]
@laurenernest @outerpress I am verifying this is just the confirmed vvc correct?

**Comment by laurenernest** [comment]
It should include pending/request and canceled, but those states look similar to regular VA appointments so I'm not positive if there's actual dev work specific to VVC or if it was automatically covered in other work and it's only validation necessary here.

If you drop screenshots for both of those states, we can help determine if other work covered it.

**Comment by LanceGundersen** [comment]
@laurenernest the cancelled status isn't a thing for vvc appointments. Pending looks like this as of now.
![image.png](https://images.zenhubusercontent.com/5f3eac7874547508dad0702d/137c856b-50ad-4084-8b84-df28ef012d38)![VA_appointments___Veterans_Affairs.png](https://images.zenhubusercontent.com/5f3eac7874547508dad0702d/480c59e9-0cfd-4da8-a43a-9c0149ba6f5c)

**Comment by laurenernest** [comment]
It looks like most of the pieces are there and needs the blue info and the preferred type of appt. (I might've removed too many templates.) I updated the description to waive those 2 states since it wasn't clear in the AC. I'll write up new tickets for anything else that needs to be covered.

**Comment by LanceGundersen** [comment]
Understood
