### ISSUE TITLE
Create concept for "Remove" workflows on View Dependents Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18195]
## Background
The View Dependents page has a "remove" dependent button on each dependent card. Dependent removal workflows are relatively simple; some consideration has been given to abstracting-out the 686 form via a series of simple selections. The idea is that a 686 will be submitted "in the background" and the user will see a "pending" indication on the dependent card.

### Considerations
The dependency check feature will connect selected users with the View Dependents feature. The Dependents screen will need to facilitate (or connect) to add and remove processes so that a user can rectify problems.

## Tasks
- [ ] Create a user flow diagram showing feature connectivity between verification, view, add and remove functionality
- [ ] Create mockups showing various screens and states illustration the functionality above

## Acceptance Criteria
- [ ] Diagram created
- [ ] Mockups created
- [ ] Ideas have been formed and shared with the team for discussion

**Notes for Dependency Verification**
- Drive traffic to VD and ask the question is this correct? 
- If you say yes, we write the the 05388 form to eFolder?
- If no, we go into the 686?

**Comment by jason-gcio** [comment]
This work was covered in another ticket: https://xd.adobe.com/view/9a75a359-e0e2-4411-b235-60c3dddb4e6e-cf26/

**Comment by jason-gcio** [comment]
With user flow: https://xd.adobe.com/view/95773c75-de5a-4e55-8c35-34a91425155d-c024/
