### ISSUE TITLE
Chapter 31 - Adjust form workflow based on LOA level

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#18191]
## Background
Given the complexity required to support dynamically changing form flow, the decision was made to remove the biographical information card and present traditional form fields to all users, regardless of LOA. 

## Considerations
- Remove the bio info card so that data does not get over written
<details>

<summary>Expand to see blank info screen</summary>

![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/4b4a7a0b-3761-4e47-ac9f-b62d49c8ec35)

</details>

## Tasks
- [x] Determine best path forward (See notes above)
- [ ] ~~Implement logic on the CH31 form~~
- [ ] Remove the the bio info card for now until the issues can be resolved at a larger platform level
- [ ] update e2e tests

## Acceptance Criteria
- [ ] The info screen has a contingency for auth'd users who have no profile info (its a straight forward workflow)
- [ ] A PR has been requested for merging, as needed

**Comment by micahchiang** [comment]
Given our decision regarding chapter 36, this ticket can probably be closed.
