### ISSUE TITLE
Audit Contact Center Support Issues

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#18190]
## Issue Description
_Through a long period of time being short on support staff, getting VA access, and acquiring correct permissions, the support backlog grew to over 2,000 issues. This effort is to consolidate our focus to resolving these issues in a short amount of time by pooling most of our team resources to address it_

---
## Tasks
- [ ] _Respond to, resolve, and/or close all historical support issues 3 days (arbitrary) or older to catch us up to current._

## Acceptance Criteria
- [ ] _All support issues 3 days old or older have been responded to and/or closed._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
The plan outlined below was shared with VEO on 3/3/2021 for completing the currently backlog.

Good Morning Team.  Please see the issues plan that I am going to cover with VEO today during our call.
Please remember that we will end 5 minutes early.  I am still having issues with the VA side and cannot access my teams, so I will be calling in.
Please see the breakdown below that I am going to cover with VEO today.  I am not sending this to them, but I will be reviewing with them today.  Please let me know your thoughts.

There are currently 2,285 tickets that are backlogged.  On average it takes me around 5 to 7 minutes to complete a SF ticket from beginning to end.  I am assuming that it will take the team around 8 to 10 minutes in the beginning to complete a ticket.  The plan below shows the backlog being cleared by the end of the month is based on that data.  Although our plan is the end of the month, I would like to think that it will be done sooner than that.  Better to under promise and over deliver.

Also, my definition of 'caught up' is that all tickets that belong to our group are no longer in a 'routed' status, but in a status that indicates that we have reviewed and are 'in progress' or 'closed'.

It is also important to point out that Ian has the fewest amount of hours on the issues.  This is because I thought it would be beneficial for him to create the ZH tickets for the issues that need to be escalated to a team.  When the influx of responses start to pour in, someone is going to have to create ZH tickets for them.

- Kimberley 7.5 tickets an hour based on a 5 hour day and 8 mins per ticket

            - 38 total daily (37.5 actual)

- Ervin 6 tickets an hour based on a 5 hour day and 10 mins per ticket

            - 30 total daily

- Stephen 6 tickets an hour based on a 4 hour day and 10 mins per ticket

            - 24 total daily

- Ian 6 tickets an hour based on a 3 hour day and 10 mins per ticket

           - 18 total daily

- 110 Daily

- 550 Weekly

- 21 Days / 4.15 Weeks

**Comment by Kimberley2019** [comment]
Now that the SalesForce cases are down to well under 1200, the objective now is to gather all data from the reply emails, sort them by the respective group, and send the information to the appropriate teams in order for them to research and resolve the issue.

**Comment by Kimberley2019** [comment]
Since Salesforce cases are majority caught up, the major support catch up effort can be considered done.

The second phase is to identify the best solution for providing the appropriate teams with the cases they need to review and ultimately resolve.

@edpearson20  and I are taking the trainings that are offered through DOMO and will be doing discovery work around its capabilities.

**Comment by edpearson20** [comment]
During our Reporting Chat, it was determined that I (Ervin) should create reports and a dashboard to provide the information Jason is seeking.  The dashboard will be produced by Thursday 11:45AM.  Kimberley and I will have a meeting on Thursday / Friday (Morning) to discuss.  We will present this information to Jason during a meeting scheduled for Friday, May 7th.

**Comment by edpearson20** [comment]
White House Hotline Reporting (Salesforce)

Pearson, Ervin D. (Oddball, Inc.)
6:08 PM
to Jason, Kimberley, Steven, Ian

Hi, Jason / Team!

Below, you’ll find the links to the Salesforce Reports.  There is no need to apply updates to the reports as they will provide the data as the report title suggests.  You can subscribe to these reports as well.

*** Hopefully the links work, but if not, you’ll find them in the Salesforce Public Reports folder entitled as shown below***

How many total support issues did VEO receive?
                Cases Opened Last Week WH VA Hotline

How many of those were escalated to tier 2 (us)?
                Cases Opened Last Week WH VA H TSup/T2

How many of those were escalated to tier 3 (VFS teams)?
     We will need a way of labeling the cases to identify those escalated to Tier 3.
     Suggested Solution... Tier 2 would update the Case Outcome field to "Transfers/Escalations."  This field could then be reporting on.

How many of those escalated to us (tier 2/3) were closed?
                Cases Closed Last Week WH VA Hotline T2
               
How many of those escalated to us (tier 2/3) remain open/in-progress?
                Open / In-Progress Cases WH VA H TSup/T2

Let me know if you have any questions.


Kind regards,

Ervin D. Pearson II
Senior Technical Analyst
VA Contact Center (US Department of Veterans Affairs)

**Comment by jwoodman5** [comment]
Hey @edpearson20 This seems great! I don't see any links, but I'm going to see if I can dig around in SF and get what I need. Thank you!! Have a great weekend!

**Comment by jwoodman5** [comment]
This particular effort is complete. Closing.
