### ISSUE TITLE
[FE][SPIKE] Save In Progress - Different System . 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18209]
## User Story
As a veteran, 
I should be able to store my data in PGD as I fill out the form
to reduce the complexity and places my data is being stored. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
Using the current SiP system adds more complexity. Takes a look at how much effort and what the risks/benefits are moving to a new system. 

## Questions to Answer
- [ ] How can we point the SiP system to another data source/URL. 
- [ ] Where would the customizations happen. 
- [ ] What systems would be affected by this change. 

## Tasks
- [ ] Answer questions

## Acceptance Criteria
- [ ] Engineer team has a recommendation, documented in the team notes.

**Comment by mdewey** [comment]
Dupe of #18236
