### ISSUE TITLE
Create Feature Toggle for Sections of View Rep

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18207]
## Background
For the 1) link in the first box of the sidebar, and 2) the "Change your representative" button, we want to place the behind a feature toggle so that we can iterate on them safely and fold the min in a future version.

## Considerations
- ~~There are two separate entities that need to be covered to be shown as we build them.~~
- Update 1/15/21: Given the new mockups, there is now only one entity to feature toggle, the blue `Find a new representative` button.
- Staging link: https://staging.va.gov/view-change-representative/view/
<details>

<summary>Expand to see example screenshot of functions that are to be toggled</summary>

![feature-toggle.jpg](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/f83a0feb-0de0-42d6-8044-b5cb07773301)

</details>

## Tasks
- [x] Create new feature toggle
- [x] Ensure there is a state where they don't appear and do appear
- [x] Test various states

## Acceptance Criteria
- [x] The feature has a default appearance of not having a button or a link in the side bar
- [x] A PR has been requested for merging

**Comment by micahchiang** [comment]
updated mocks - https://xd.adobe.com/view/e27b7e71-d920-4bcd-9e81-dc62a9665d5e-b728/

**Comment by micahchiang** [comment]
Keeping in validate for now, since there is still one additional PR out on review.
