### ISSUE TITLE
"Search this area" may block location in mobile experience. 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18204]
## Issue Description
This issue was reported by Josh Kim during testing on mobile (in devtools). 

The search button can block out a good chunk of the page which may hide locations. (see video)

https://user-images.githubusercontent.com/14154792/103007174-f2c14100-4500-11eb-954a-ed446490cf68.mov

---
## Tasks
- [ ] Identify appropriate  mobile experience

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
