### ISSUE TITLE
FSR Usability Topline Debriefing

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18216]
## Issue Description
To quickly share our findings (i.e. demo), we should compile our debrief discussions into a list of notable trends.

---
## Tasks
- [x] Hold debrief sessions at the end of each research day
- [x] Create a document or deliverable that highlights major takeaways from session attendees

## Acceptance Criteria
- [x] Topline summary deliverable uploaded to GH and linked in this ticket

**Comment by rebeccawalsh** [comment]
Deliverable available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/fsr-debriefs.png
