### ISSUE TITLE
FSR Usability Synthesis

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18213]
## Issue Description
Complete synthesis activity for FSR Usability study data

---
## Tasks
- [x] Complete synthesis activity for FSR Usability study data
- [x] Upload deliverable to GH

## Acceptance Criteria
- [x] Synthesis deliverable uploaded to GH and linked in this ticket

**Comment by rileyorr** [comment]
The research readout and presentation have been uploaded to [this GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021).
