### ISSUE TITLE
FSR Usability Sessions

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18212]
## Issue Description
Conduct all scheduled usability sessions, for a minimum of 7 and a maximum of 15

---
## Tasks
- [x] Conduct usability sessions
- [x] Scrub and upload session transcripts to GH

## Acceptance Criteria
- [x] Scrubbed session transcripts uploaded to GH and linked in this ticket

**Comment by rileyorr** [comment]
FYI @troyriser I added you as an assignee to this ticket since you're taking notes in all our sessions so your work properly reflected for the sprint.

**Comment by troyriser** [comment]
Received and acknowledged, and thanks.

**Comment by rebeccawalsh** [comment]
Uploads courtesy of @troyriser can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/sessions
