### ISSUE TITLE
Capture and Store Historical ForeSee Data 

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#18222]
## Issue Description
---

_VA is transitioning from using ForeSee to Medallia for survey on VA.gov. We have historical survey data in ForeSee, which we need to collect and store for future use._

---

## Tasks
Once all ForeSee surveys have been disabled (migrated to Medallia)
- [ ] Extract all historical ForeSee survey data
- [ ] Load all extracted ForeSee data into BigQuery

## Acceptance Criteria
- [ ] _All historical ForeSee data is obtained and stored in a BigQuery
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Just making a note:

Will want to have historic data so we can compare MoM and YoY form submissions to gauge the success of the Medallia feedback button redesign.

**Comment by Kimberley2019** [comment]
@jwoodman5 to follow up with Joanne for status update.

**Comment by jwoodman5** [comment]
Adding @joanneesteban and the analytics-insights label for visibility on updates and timing.

**Comment by jwoodman5** [comment]
@clantosswett Is currently collecting this data with her existing ForeSee access and the planned 8/26 deprecation of ForeSee.
