### ISSUE TITLE
Testing Tools Team - User Research Survey

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#18239]
## Issue Description
In order for the Testing Tools Team to understand it's OKR, the current testing landscape across the platform, and the needs of the VFS teams, we will create a survey to share out with teams in order to help gain an understanding of where things stand currently.

---
## Tasks
- [x] Create a draft set of questions for the survey
- [x] Vet those questions with the team
- [x] Enter the questions into Optimal Workshop and review w/ Service Design team
- [x] Launch the survey and conduct follow-ups to help get more responses

## Acceptance Criteria
- [x] We have sufficient responses to be able to begin discussing/planning future work and/or research

**Comment by JoeTice** [comment]
Research completed, results collected, reviewed, and turned into action items:

https://vfs.atlassian.net/wiki/spaces/VI/pages/1116274741/2021+User+Research+Survey+-+Complete+Insights+List
