### ISSUE TITLE
Yellow Ribbon: Incorporate -ALL- Yellow Ribbon search GA code per Analytics specifications

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18234]
## Issue Description
Slack thread for background: https://dsva.slack.com/archives/C01DWJFD45D/p1609886505051000

We learned from the Analytics team on 1/5/2021 that they recently discovered that the search data layer for Yellow Ribbon was washed away unbeknownst to them.   In order to track searches, a new revamped & standardized data layer will need to be added.
---
## Tasks
- [x] Define search data we need to track
- [x] Open new GA issue for Analytics
- [x] Install new GA data layer code per specification provided by Analytics team here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18470#issuecomment-759721402
- [x] Test new GA code in Staging
- [ ] Deploy to Prod

## Acceptance Criteria
- [ ] The decision tools team will once again have the ability to gather event metrics on the Yellow Ribbon product.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by zacharymorel** [comment]
With the search tool tip and alert box added, this should be ready to test.

**Comment by MarciMcGuireGCIO** [comment]
> With the search tool tip and alert box added, this should be ready to test.

Thx.  Do you mean an internal staging review or testing with Analytics?

**Comment by zacharymorel** [comment]
> > With the search tool tip and alert box added, this should be ready to test.
> 
> Thx. Do you mean an internal staging review or testing with Analytics?

Testing with analytics on staging.

**Comment by zacharymorel** [comment]
@jonwehausen https://staging.va.gov/education/yellow-ribbon-participating-schools/ is ready for GA QA.

**Comment by jonwehausen** [comment]
Thanks for the heads up @zacharymorel ! Will get to this QA as soon as we can.

**Comment by jonwehausen** [comment]
@zacharymorel This was my mistake for not including in the original specification -- could we please include `'search-total-results'` and `'search-total-result-pages'` on the `view_search_results` event fire? Thanks so much in advance

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel @jonwehausen catching up... @jonwehausen can we schedule some time with you to do a quick review of the changes Zach added?  Thx!

**Comment by MarciMcGuireGCIO** [comment]
🎉
