### ISSUE TITLE
[FE][SPIKE] SiP Progress, using FHIR

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18236]
## User Story
As a veteran, 
My data should be stored in the fewest amount of places
so that I know where my data is. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
The SiP System integration has some overhead in complexity. We want to look at the possibility of using a PGD instead of the Vets API to store the data. 

## Questions to Answer
- [ ] How can the FE be modified to use a different SiP system 
- [ ] How can the BE be modified to use a different SiP system 
- [ ] What are the current disadvantages of the SiP system 
- [ ] What are the current advantages of the SiP system 

## Tasks
- [ ] Create a FE  prototype where the SiP system talks to another prototype
- [ ] Create a list of Pros and Cons
- [ ] Create a list of viable options

## Acceptance Criteria
- [ ] Findings are documented in the team docs folder
- [ ] Team meeting to exploring findings and choose a path forward

**Comment by julieadair1** [comment]
Per @mdewey  this is something we may still want to explore at some point, however it will not be in the near future so I'm closing this now and we can open again if needed.
