### ISSUE TITLE
[FE][BUG] Reason for visit description can not be emptied

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18238]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Labeled with Team (`vsa-healthcare-exp`)
- [ ] Fill in User Stories
- [ ] Fill in Documentation 
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria 
---

## User Story
As a veteran, I should be able to completely edit my reason for the visit. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
https://images.zenhubusercontent.com/133843125/26f09ef0-a460-429a-986a-df8b47ddbe30/screen_recording_2021_01_07_at_9_34_36_am.mov

## Description
the user should be able to clear the box

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [ ] Write test to recreate the bug
- [ ] Fix the bug
- [ ] Create user tests
- [ ] Create e2e tests 

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Merged, waiting for deployment to staging

**Comment by mdewey** [comment]
In Staging. 

Steps to confirm: 

1. Start a questionnaire
2. Completely empty the prepopulated `Are there any additional details you’d like to share with your provider about this appointment?` question and enter in anything else.
3. See what was entered on the review page.

**Comment by mdewey** [comment]
https://user-images.githubusercontent.com/1793923/105909293-5d303a00-5ff5-11eb-8d35-4a54556d94a9.mov
