### ISSUE TITLE
[UNPLANNED] Adjust the Net Worth on Dependency Claims

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18255]
## Story
As a Veteran, answering questions in the 21-686c/674 application, I want to ensure that the net worth threshold is up to date so I can respond accurately and reflect my situation to the VA as my claim is considered.

## Background
Every year, on December 1, the net worth threshold amount gets updated and that needs to be reflected on VA.gov within the net worth question.

## Considerations

<details>

<summary>Expand for example</summary>

![new-net-worth-value-130.jpg](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/21b49790-3616-4d8f-a0f1-9ce8c246b4da)

</details>

- Aside from a calendar reminder, is there a way to transfer this check to future teams to ensure it is up to date on December 1?

## Tasks
- [ ] Update the value from $129,094 to ~~**$130,733**~~ **$130,773** as content on all questions that reference net worth

## Acceptance Criteria
- [ ] New amount shows on all questions that ask about net worth
- [ ] A PR has been requested for merging

**Comment by micahchiang** [comment]
Update 1/15/21: On call with RBPS a discrepancy was found with networth amount. Originally this ticket called for 130,733. Instead, it should be 130,773.
