### ISSUE TITLE
[FE] Handle negative cases on the questionnaire list

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18260]
Handle no questionnaires in each list, 
handle server is down for the questionnaire list
## User Story
As a veteran, I should see the correct errors on my questionnaire list

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17314)

## Description
Add the error states for the questionnaire list. 

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [ ] Add the "no questionnaires" message
- [ ] Add the "Server is down message"
- [ ] Create user tests
- [ ] Create e2e tests 

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Merged, waiting for deployment to staging

**Comment by mdewey** [comment]
The commit has been deployed to staging, though there currently no way to validate that is in staging. since we do have test accounts with no questionnaires. 

Best to validate is to have a developer manipulate the staging data to show the empty messages. 
![Screen Shot 2021-01-26 at 4 48 41 PM](https://user-images.githubusercontent.com/1793923/105910035-5b1aab00-5ff6-11eb-9d1a-251840312926.png)
![Screen Shot 2021-01-26 at 4 49 20 PM](https://user-images.githubusercontent.com/1793923/105910091-72599880-5ff6-11eb-9a25-13cdd208dca6.png)
