### ISSUE TITLE
Update vets-api DB CPU Alert

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#18261]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Usually when CPU is pegged on a database there are more problems going on. Recently in an outage the DB was a bottleneck and there was a vets-api outage. A prometheus alert triggered about database CPU. That should be a pagerduty alert. 

Along with this effort we probably want to increase the threshold of the alert to closer to 100%.

Example alert is here https://dsva.slack.com/archives/C24RH0W11/p1608077557164800

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] route the alert to pagerduty so oncall gets paged

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Is this still an issue? Has the team done any work in the background that might have addressed this directly or indirectly? What alerts might we have now for DB CPU?

**Comment by oseasmoran73** [comment]
Not creating alerting, but team-3 (Charlie) creating monitoring for vets-api RDS

Ticket found here https://github.com/department-of-veterans-affairs/va.gov-team/issues/47463#event-7544938897

In an ideal world, may make sense to have this as an alert. Not sure if we have a ticket for it @npeterson54 , but throwing it on your radar
