### ISSUE TITLE
Staging Review: Design System Team - Back to Top Component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18289]
## Steps to complete Staging Review: 

- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance criteria in each practice area feedback ticket
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- Back to top component issue: https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/298
- Mockups - https://zpl.io/VYloBlM
- Brooks will share a branch to access Back to Top component for usability testing 

## Meeting attendees from **requesting team**
- Product Manager (required): Carol Wong
- DEPO product lead (required): Kevin Hoffman
- Anyone else from your team who significantly contributed to the artifacts provided (required): Crystabel Reiter and Brooks Johnson
- Other specialists: Chris Valarida (optional)

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Monday at 3:30pm
- Wednesday at 11:30am 
- Thursday at 1:30pm

**Comment by allison0034** [comment]
@caw310 I am unable to login in to view prototypes. Do you have a login or can you make it public? Thank you!

**Comment by caw310** [comment]
@CrystabelReiter , can you give Allison access to mockups?

**Comment by peggygannon** [comment]
@CrystabelReiter I'm also unable to access this mockup. Can you also grant me access?

**Comment by CrystabelReiter** [comment]
@peggygannon Just gave you access to the workspace. Please check your email for access.

**Comment by peggygannon** [comment]
hello, @CrystabelReiter  I don't have any content feedback for this component.

I just have one question: how will screenreaders or assisted tech "read" the arrow on mobile?

**Comment by CrystabelReiter** [comment]
@peggygannon With Trevor's recommendation, it would read, "Back to top, button"

**Comment by bkjohnson** [comment]
Implemented in https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/562
