### ISSUE TITLE
Adjust Environment Mapping

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18288]
## Background
To better accommodate the VRE API team's testing effort, we need to repoint where the staged CH31 feature points in the lower environments.

## Considerations
`dev.va.gov`  >  CMS QA
`staging.va.gov`  >  CMS POSTSPRINT
`www.va.gov`  >  CMS PRODUCTION

- Testing these will need to be completed with SoapUI
- These changes may require a change to values stored in **credstash**

## Tasks
- [ ] Initiate the mapping change request with DevOps Team
- [ ] Follow up with any other tasks set forth by DevOps Team

## Acceptance Criteria
- [ ] The VRE API Team is able to receive submissions in the environment they need
