### ISSUE TITLE
Adjust Date Shown for Non-Explicit Dates 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18287]
## Story
As a Veteran viewing my payment history, sometimes there might be a date shown as **Invalid date** when the date is not available , like if the payment was pending that day, and I want it to be clear that that date's invalidity is not indicative of the payment being invalid so I can better understand that payments status.

## Background
In UAT, we found a payment that was likely to be pending and the date was unavailable and showed in the entry as **Invalid date**.  We take the machine provided date and add a mutation to make it more readable with this MomentJS library code: 

`payCheckDt: moment(payment.payCheckDt).format('MMM D, YYYY'),`

and we might need another check to cover instances where there is simply no date as the default is to display **Invalid date**.  The first, and safest notion is to replace **Invalid date** with **---**, three simple dashes.

## Considerations
- Testing this might be interesting as we might have to mock in the response where a date, and/or its expected format is not explicitly returned

## Tasks
- [ ] Add another check that looks for a non-date response 
- [ ] Replace that non-date response with **---**
- [ ] Add unit test to ensure complete coverage

## Acceptance Criteria
- [ ] A non-date response like pending would show **---** instead of the default **Invalid date**
- [ ] A unit test has been included
- [ ] A PR has been requested for merging
