### ISSUE TITLE
CI Jobs Alerting - explore if GitHub Actions can integrate with Slack given our permissions / security 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18298]
## Description
We want to explore whether or not GitHub Actions can integrate with Slack given our permissions / security 

## Background/context/resources
Slack comment here from Tim Wright looking for this functionality 

## Technical notes
Probably just need to put Slack API tokens/urls in parameter store and pull them using credentials store encrypted secrets

https://github.com/marketplace/actions/slack-notify

---
## Tasks
- [x] Make a determination as to whether or not we can easily integrate GiHub Actions with Slack, and if not
- [x] Perform discovery around enabling a slack app that can do this

## Definition of Done
- [ ] There is a clear way to send Slack messages from GHA without having to register a new slack app for each channel (should strive to use a webhook for this, so that we don't need slack admin privileges) 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
prefer solution that doesn't require admin privileges, but understand that webhooks are being deprecated

**Comment by jhouse-solvd** [comment]
Closing this one out. Creating a new ticket for the setup of the integration.
