### ISSUE TITLE
Usability Testing Prep [VAOS Homepage Refresh]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18301]
## Steps to complete Usability Testing Prep: 
- [x] VFS Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance included in each practice area feedback ticket 
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/homepage-refresh-initiative-2021.md)
- [prototype](https://adhoc.invisionapp.com/share/URZV3YHCQFZ)
- [research plan and script](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/research/jan-2021-appts-list-test)
- [TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/21&group_by=cases:section_id&group_order=asc&group_id=109)

## Meeting attendees from **requesting team**
- Product Manager (required): **Lauren Ernest**
- DEPO product lead (required): **Leanna Miller, Lauren Alexanderson**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Peter Russo, Jeff Balboni**
- Other specialists: 

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Tue, 1/12 11am ET

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by shiragoodman** [comment]
hey @laurenernest  - please see the feedback tickets for the Usability Testing Prep review of the VAOS Homepage Refresh. Please feel free to reach out to us via #vfs-platform-support on Slack if you have any questions about the feedback provided. thanks!
