### ISSUE TITLE
Update facility label for #620 (Franklin Delano Roosevelt)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18300]
## Issue Description
- Site 620 is now called VA Hudson Valley Health Care System rather than Franklin Delano Roosevelt Hospital.
---
## Tasks
- [ ] Change the label mapping for #620

## Acceptance Criteria
- [ ] Label is changed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by hdjustice** [comment]
This ticket is no longer necessary, as we will be connected to Lighthouse/Facilities API to retrieve the most up to date facilities list for selection
