### ISSUE TITLE
Manually add for FACILITY_MENU_NAMES for VISNs 6,16,21, 23 and 2

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18320]
## Issue description
As a contingency plan to the [discovery of a dynamic solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17256), we may need to manually add for FACILITY_MENU_NAMES for VISNs 6,16,21, 23 and 2 so the node and data load processes are not blocked.

## Tasks
- [x] Manually add FACILITY_MENU_NAMES for VISNs 6,16,21, 23 and 2 (list from Stan below in comment)

## Acceptance Criteria
- [x]  36 systems have been added to the array
- [ ] Facility builds for VAMCs in VISNs 6,16,21, 23 and 2 each  include the side nav component when published in DevShop*

* or Tugboat?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
[Left_NAV_Needed_FAB-FIVE.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5789537/Left_NAV_Needed_FAB-FIVE.xlsx)

**Comment by mpelzsherman** [comment]
@indytechcook @SgardnerPMP  Can you help validate this?
