### ISSUE TITLE
Sidekiq Admin UI

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#18328]
## Description

This epic is used to track two issues with the Sidekiq Admin UI.

Issue #1: The Sidekiq web UI has no authentication on it and is open to the public.  There is an issue raised to the CISA that needs to be remedied.

Issue #2: Authentication needs to be added to the Sidekiq Admin UI for all environments

## Definition of Done
- [ ] Initial CISA security issue is resolved 
- [ ] Authentication approach is decided and approved by DEPO and Eng Lead (and any other VSP teams that will be involved)
- [ ] Production Sidekiq UI is accessible through a log in
- [ ] Staging Sidekiq UI is accessible through a log in
- [ ] Sandbox Sidekiq UI is accessible through a log in
- [ ] Development Sidekiq UI is accessible through a log in
- [ ] Review Instance Sidekiq UI is accessible through a log in (?)

## Related Documents
[Initial Documented Issue and Immediate Proposal](https://vfs.atlassian.net/wiki/spaces/VI/pages/926089332/Sidekiq+Access)

**Comment by jeff2d2** [comment]
Closing as #22354 is a replacement
