### ISSUE TITLE
Content finalization of Spanish Coronavirus FAQs page for soft launch

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#18326]
## Issue Description
Review and finalize the Spanish version of the Coronavirus FAQs page.

English version: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

Spanish: https://prod.cms.va.gov/coronavirus-veteran-frequently-asked-questions-esp

---
## Tasks
- [x] Review Spanish page vs. [certified translation PDF](https://app.zenhub.com/files/133843125/eb09c8ae-e6ca-4f96-aa72-32a9dad0ecac/download)
- [x] Add code for anchor links (highlighted in PDF)
- [x] Add code for all phone numbers
- [x] Check all links on page
- [x] Double check Spanish content (today's launch is a "soft launch" so we will also be checking for the next week)
- [x] Add meta description
- [x] When publishing - add breadcrumb/nav menu link
- [ ] Make this a "no index" page for now if possible

## Acceptance Criteria
- [x] Page is live on site and ready for full testing/QA/dev work to add connecting links
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Good morning, @SKasimow! Just keeping you in the loop on this ticket. Thanks!

**Comment by SKasimow** [comment]
Excellent - thanks you!!!!

cc: @youngfreezyVA

**Comment by SKasimow** [comment]
Closing as completed.
