### ISSUE TITLE
[Design] Error to show when we cannot connect to a Direct Deposit endpoint

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18338]
## Background
We need some content to show when there is an error connecting to one of the direct deposit endpoints.

This is a new situation that does not exist with the current CNP-only direct deposit section.

For example, in the below screenshot, we know the user has DD4CNP set up, but we cannot _connect_ to the DD4EDU endpoint so _we should not be telling them they do not receive education benefits. Instead we should be showing an error of some kind letting them know we could not determine if they receive education benefits.

![Screen Shot 2021-01-11 at 10.02.24 AM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/705368d8-f2ce-4d5b-a92e-a967ab38fb73)

The same goes for the this next screenshot. We know they have DD4EDU set up, but we couldn't connect to the endpoint that provides DD4CNP info so we should be showing an error of some kind, not declaring that our records show they do not get CNP benefits.

![Screen Shot 2021-01-11 at 10.02.36 AM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/ad66ae42-c272-4875-97df-d5bc706df0b3)

Note: If we cannot connect to _both_ endpoints, we hide the Direct Deposit page entirely and show the generic "We can't load all the info in your profile" alert, which mirrors the behavior of the current CNP-only Direct Deposit page that is live on prod.

## Tasks
- [ ] determine the content to show when we have a problem connecting to one of the direct deposit endpoints but we are showing the Direct Deposit page because the user is eligible for the _other_ direct deposit feature on the page.
## Acceptance Criteria
- [ ] Mockups showing requested states are in place and shared with Auth Exp Team
- [ ] Start Content Review process with Peggy

**Comment by erikphansen** [comment]
FWIW, this is how we handle a similar situation when we are unable to connect to the VA Profile service so we hide the user's contact info entirely

![image](https://user-images.githubusercontent.com/20728956/104223974-2f45d580-53f9-11eb-960f-468963620ecf.png)

**Comment by peggygannon** [comment]
Hi, @mshea0606 and @erikphansen  a few questions from me: 

--are we needing to replace the content that's in the red box? or the  **We can't load all your information in your profile** alert? 

-- if I'm understanding this, if seems that a message similar to **we can't load your information** would work for this use case?  Am I understanding the use case correctly?

**Comment by erikphansen** [comment]
@peggygannon

1. We are talking about updating the content in the red box

2. Yes, I think something along the lines of "We can't load your education benefits information" would be appropriate.

**Comment by mshea0606** [comment]
cc @sporeboy

**Comment by Samara-Strauss** [comment]
> --are we needing to replace the content that's in the red box? or the We can't load all your information in your profile alert?
> 
> -- if I'm understanding this, if seems that a message similar to we can't load your information would work for this use case? Am I understanding the use case correctly?

> We are talking about updating the content in the red box
> 
> Yes, I think something along the lines of "We can't load your education benefits information" would be appropriate.

@erikphansen, is it safe to assume we would *only* be replacing the information in each box when we are having trouble connecting to the direct deposit endpoint? This is probably obvious, but the existing copy is designed to account for when we *know* someone does not receive either disability or edu payments, so I don't want to nix that. I want to make sure we can detect and reliably serve up messaging in both use cases — if we know someone does not have one type of direct deposit *and* if we aren't sure if they have one type of direct deposit because we are having trouble connecting to the endpoint. If so, then I am OK with the approach outline above.

**Comment by erikphansen** [comment]
@Samara-Strauss yeah that's mostly what I'm thinking. With one small caveat. We _only_ show the Direct Deposit page when we _know_ someone should see it. So in the case you described: we know the user doesn't have one type but we aren't sure about the second type because of a server error, we would _not_ show the Direct Deposit page, but the user would see the "We can't load all the information in your profile" alert at the top of the Profile. This mirrors the current functionality if we cannot connect to the DD4CNP endpoint.

**Comment by Samara-Strauss** [comment]
@erikphansen that makes sense, and this sounds good to me. I wanted to make sure we shouldn't combine the two states into one (ie. "You either don't have X type of direct deposit, or we're having some trouble loading it right now.") It doesn't sound like that is necessary, so we can move forward with things as you've outlined.

**Comment by peggygannon** [comment]
@erikphansen Please let me know if this error works for when we can't connect to an endpoint: 

for EDU: 

**We can’t load some of your profile information**
We're sorry. Something went wrong on our end. We can’t display information about your education benefits. Please refresh this page or try again later. 

for Pension and disability comp:

**We can’t load some of your profile information**
We're sorry. Something went wrong on our end. We can’t display information about your disability compensation and pension benefits. Please refresh this page or try again later.

**Comment by sporeboy** [comment]
I have initial mocks with Peggy's copy in-place:
- [No-load EDU](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/8a43a64c-1644-4213-8afb-296d824d1019/)
- [No-load C&P](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/da4b50a6-875c-4f2b-8449-4044e7bebdc2/)

**Comment by Samara-Strauss** [comment]
Sorry, I should have got back to this sooner. @peggygannon @sporeboy can we update the copy? I think it's kind of confusing for a couple reasons:

- We should be more specific than "We can’t load some of your profile information" since we know what information we're having trouble loading.
- @erikphansen can correct me if I am wrong here, but we won't know for sure whether a person has C&P or edu benefits or not *because* we're having trouble connecting to the endpoint. So, it's not totally accurate to say that we can't display **your** C&P or edu benefit information because we actually don't know for sure that a given user has information to load in the first place. I would suggest taking out the reference to "your benefits" to be more accurate.

I would suggest something like this (definitely needs refinement and approval from @peggygannon): 

**For EDU** 

**We can’t load education benefits information**

We're sorry. Something went wrong on our end. We are having trouble loading information about education benefits. Please refresh this page or try again later. 

**For Pension and disability comp**

**We can’t load disability compensation and pension information**

We're sorry. Something went wrong on our end. We are having trouble loading information about disability compensation and pension benefits. Please refresh this page or try again later.

**Comment by erikphansen** [comment]
I second @Samara-Strauss's comment.

**Comment by peggygannon** [comment]
Hi, @Samara-Strauss @erikphansen the suggested copy updates look good ^^. thanks.. 

cc @sporeboy

**Comment by sporeboy** [comment]
I have the text updated:
- [No-load EDU](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/8a43a64c-1644-4213-8afb-296d824d1019/)
- [No-load C&P](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/da4b50a6-875c-4f2b-8449-4044e7bebdc2/)

**Comment by Samara-Strauss** [comment]
Great, thanks, all!

**Comment by Samara-Strauss** [comment]
I think this is done, so closing. Please feel free to reopen if needed!
