### ISSUE TITLE
Set Phone Number to Required

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18334]
## Background
Within the CH36 application process, the VA will use phone number as a method of communication to the Veteran after submission and sometimes that number does not get filled out. 

## Story
As a Veteran seeing education and career counseling, I must be required to include my phone number so that the VA can contact me quickly and easily as requested.

## Tasks
- [ ] Set the phone number field to required within the CH36 form using the Form System

## Acceptance Criteria
- [ ] The phone field is set to be required in order for the form to submit
- [ ] A PR has been requested for merging
