### ISSUE TITLE
PDF/Print Save Checklist - mobile and desktop - R&S 1.1

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18337]
## Issue Description
_The PDF saved checklist needs a few updates in order to ensure users are able to display, enact and print properly with R&S Checklist article ~types~_

I'm attaching the Checklist PDF here with detailed comments:
https://app.zenhub.com/files/133843125/0b92c6c4-8a05-4fc7-96f9-ba7c8db17408/download

Reference to Original Ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/15617)

## Front end tasks
- Estimate ticket and remove "needs grooming" label
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 

## Acceptance Criteria (AC)
- [x]  Links displaying the raw https URL text.
- [x] Empty checkboxes not being checkable on the PDF. (users should have checkable checkboxes on both web and PDF)
- [x] Omit the search bar on the PDF checklist.

**Comment by brianalloyd** [comment]
@kelsonic please groom ticket and remove 'needs grooming' label in support.  I've placed in sprint for action.

**Comment by jenniferlee-dsva** [comment]
Just made a slight clarification in the desc, so it's clear this is for Checklist article type only.

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/104358519-cda26b80-54cb-11eb-99e8-f863bea3b600.png)

Posting this image here as #1 I'll also add to this ticket as AC if that works CC @rtwell @jenniferlee-dsva @brianalloyd

**Comment by kelsonic** [comment]
Just kidding 🤪 lol PR is already up for above comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15649#issuecomment-758856867

**Comment by brianalloyd** [comment]
Thanks @kelsonic

**Comment by brianalloyd** [comment]
@ncksllvn as mentioned in planning handing this off to you.  @kelsonic please parse with Nick and advise on current progress and actions left.  Thanks.

**Comment by kelsonic** [comment]
I haven't started any work on this 🙂 lmk if you need any help or if you have any questions @ncksllvn! Thanks for picking this up for me!

**Comment by ncksllvn** [comment]
I remember this being handed off to me but I'm a little unsure where it's at. Is the acceptance criteria up-to-date, or should I be looking at the checklist PDF linked in the description?

**Comment by ncksllvn** [comment]
@jenniferlee-dsva a couple notes...

### HREFs showing during print

![image](https://user-images.githubusercontent.com/1915775/104966867-f9cc5980-59af-11eb-9428-b16575dc4f6f.png)

As strange as it sounds, that's an intentional [style rule in our design system](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/81fe8fc578202fc43f5bb60151f172d09d0ecb64/packages/formation/sass/modules/_m-print.scss#L24). It took some hunting for me to find that. The rule is easy to remove or override for just this type of page, but I'm wondering if we actually want this style anywhere or if this page should do what the rest of the site is doing.

### Empty checkboxes not being checkable on the PDF. 
I haven't done a full investigation yet but I don't feel good about this being possible. It seems like it's going to be up to the browser's handling of rendering a page into a PDF to determine whether the checkbox will be checkable after the conversion.

**Comment by ncksllvn** [comment]
Starting a Slack thread on the `hrefs showing during print` w/design system team, https://dsva.slack.com/archives/C7NJWUA8K/p1611093271006000

**Comment by ncksllvn** [comment]
Just opened a PR into the design system to fix the issue with showing the HREF during print view - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/584

**Comment by ncksllvn** [comment]
Two things should go live today -

1. Hide the search bar during print of the checklist
1. Fixes for the visible HREF value during print for _all_ pages
    - Design System team seemed to support the visible HREF so I didn't remove it. Instead I just fixed the bugs.

**Comment by brianalloyd** [comment]
Validated and closing @ncksllvn, understand the HREF value will remain per the Design System team, still looks a little wonky but the bugs are fixed and search bar is hidden during print of checklists.  Thanks for the hard work on this, as always.
