### ISSUE TITLE
Publish 2 new COVID-19 vaccine questions

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#18335]
## Issue Description
Add 2 new FAQs and update h3.

**Is VA participating in COVID-19 research studies?**
Yes. As one of the nation’s leaders in health research, we continue to participate in research studies for new COVID-19 vaccines and treatments. These studies are also called clinical trials.

We need research studies to help find more safe and effective ways to prevent and treat COVID-19. Because COVID-19 is so new, we still have a lot to learn.
If you’d like, you can help in these efforts by signing up for our research volunteer list. If we think you may be eligible to be a participant in one of our research studies, we’ll contact you to tell you more about it. Then you can decide if you want to join.

Anyone who is at least 18 years old can volunteer. You don’t have to be a Veteran or enrolled in VA health care. Your decision to join a study or not won’t affect any of your VA benefits or services in any way.

[Learn more about volunteering for coronavirus research at VA](http://www.va.gov/coronavirus-research)

**Are authorized COVID-19 vaccines at VA different from vaccines received through research studies?**
Yes. Our effort to provide authorized COVID-19 vaccines to Veterans and VA health care personnel is completely separate from our participation in COVID-19 research studies.

Here's what you need to know:

- **An authorized COVID-19 vaccine** is one that the FDA has determined is safe and effective for public use. If you’re eligible to get a COVID-19 vaccine at VA, you’ll get an authorized vaccine.

- **Research studies** test new vaccines to help determine if they’re truly safe and effective. Research studies require special enrollment and consent. We’ll never give you a study vaccine unless you volunteer to join a study.

If you do volunteer for a study, the study team will talk with you about all the details of the study before you join. They’ll explain all of the possible benefits and risks. And you can leave the study at any time. 

[Learn more about volunteering for coronavirus research at VA](http://www.va.gov/coronavirus-research)

---
## Tasks
- [x] Add the 2 questions above (Danielle)
- [x] Revise the relevant h3 from "The vaccine authorization process" to "Vaccine research and FDA authorization" (Danielle)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I've added the updates on the vaccine page. Could you review and publish today? Thanks!

**Comment by RLHecht** [comment]
These changes have been reviewed and published. Moving to validate.

**Comment by RLHecht** [comment]
Work on this ticket has been completed. Closing ticket. FYSA @DanielleThierryUSDSVA
