### ISSUE TITLE
Add Don Seymour to config maps for dev and staging EKS clusters

### ISSUE THREAD

**Issue by oragame** [department-of-veterans-affairs/va.gov-team#18346]
## Description
Add Don Seymour to auth config map for EKS clusters on dev and staging.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes

---
## Tasks
- [x] Add user to config map on platform tools eks staging
- [x] Add user to config map on platform tools eks dev

## Definition of Done
- [ ] Access to Kubernetes objects on EKS clusters

**Comment by jhouse-solvd** [comment]
@oragame - Did you get "Access to Kubernetes objects on EKS clusters"? If so, can you please mark as done above and confirm in a comment below? 

Is anything else needed? If not, I will close the ticket. Thank you, sir!

**Comment by jhouse-solvd** [comment]
@oragame - bumping this... do you have what you need? if so please check off the "definition of done" item and close, please? thank you, sir

**Comment by oragame** [comment]
oops... sorry, slight delay, but i guess it doesn't matter anymore

**Comment by jbritt1** [comment]
Don was added, but has since moved to a different team due to business need. Closing.
