### ISSUE TITLE
Update coronavirus FAQs page 1.11.21

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#18340]
## Issue Description

**Update 2 questions on https://prod.cms.va.gov/node/3014/latest:** 

**If I receive VA disability or pension benefits, will I automatically get my second stimulus check?**

Yes. If you receive VA disability or pension benefits, you’ll automatically get your second stimulus check. This check is also called an economic impact payment. The Internal Revenue Service (IRS) will send your check even if you don’t file tax returns. You don’t need to do anything. 

If you didn’t get your first stimulus check, or if you didn’t get the full amount, you may still be eligible to get a payment in 2021.

To learn more, [go to the IRS.gov website](https://www.irs.gov/coronavirus/economic-impact-payments).

**Note:** Use only IRS.gov to get information about your stimulus check. Be careful of scams. Unless you’ve asked the IRS to contact you, they’ll never ask for personal or financial information by phone, email, or text. They also won’t ask you to open an attachment or visit a website link.

**Do I have to pay my VA copays at this time?**

Yes.

From April 6, 2020, through December 31, 2020, we put our monthly copay patient statements on hold. We did this to help relieve financial stress due to COVID-19.

We’ve now started to send statements again.

**Your January 2021 statement includes the total amount of any of these charges:** 

- **New copay charges** for health care and prescriptions you received from April 6, 2020, through December 31, 2020 

- **Unpaid copay charges** for health care and prescriptions you received before April 2020 

Please pay the total amount by the due date on your statement. This will help you avoid late fees, interest, or collection actions.

[Find out how to pay your VA copay bill](https://www.va.gov/health-care/pay-copay-bill)

**If you can’t pay your bill,** we can help. Call us at 866-400-1238 or 800-698-2411 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET. We’ll work with you to determine your debt relief options.

[Learn more about requesting financial hardship assistance](**https://www.va.gov/health-care/pay-copay-bill/financial-hardship**)

[Watch a video about financial hardship options (YouTube)](https://www.youtube.com/watch?v=3Pa_EUA0Qy0)

---
## Tasks
- [x] Update 2 questions (Danielle)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Content updated on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here's the ticket for the coronavirus faqs page updates to review today. Thank you!

**Comment by RLHecht** [comment]
These have been reviewed and published. Moving ticket to validate.

**Comment by RLHecht** [comment]
I believe work for this is complete. Closing ticket.
