### ISSUE TITLE
Public Websites: Sprint 39 Priorities 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18342]
## Priorities
1.  Build out CLP FE Panel tickets - Panel 1 [#17636] & Panel 2 Epics [#17642] 
2. Finalizing R&S functionality (post code freeze) - Remaining tickets from Sprint 38
3. Outstanding tickets from Sprint 38 not already included in the priorities listed above
4. Intake Requests for January, along with some applicable Tech Debt (508/a11y issues)
5. Transformer followup and close out of #16440 (Pending Platform comparison tool)
6. Follow up with CLP Content Nodes for FE.

### Campaign Landing Page MVP 1.0
**FE Transformer**
- [x] [FE] Create CLP Template + graphql query [Transformers] #17514
- [ ] [FE] Create transformer/output/input for the CLP [Transformers] #17513 
- [x] [Design/PM] Work with a11y to review mural design.  508/a11y Review #18756

**FE Panel 1 [#17636]**
- [x] [FE] CLP Hero Banner Node Title, Header and Blurb H3 #17638
- [x] [FE] CLP Field Images (Hero, Field Image, Field Image Alt) #17640
- [x] [FE] CLP Primary CTA (Label, Link) #17641

**FE Panel 2 Epics [#17642]**
- [x] [FE] CLP Field Title and Blurb H2 “Why this matters" #17644
- [x] [FE] CLP "Why this matters" Field Secondary CTA (Label, Link) #17645

### Resources and Support
Priority R&S Breakdown: WIP  [MVP 1.1 EPIC #15588] [Iterate EPIC #15584]
**FE**
- [x] [FE] PDF/Print Save Checklist - mobile and desktop - R&S 1.1 #18337
- [x] [FE] Browse by audience RS homepage FE update (WIP - Nick) #17276 `(BLOCKED)`
- [x] [FE] Auto-expand accordion items if the URL hash matches the item ID #15798

### Transformers
- [x] [PM] Transformer followup and close out of #16440 
- [x] [PM] Determine ETA on Platform CMS Transformer Comparison Tool

### Cerner Support
Main objective: Acquire facility list to determine what facilities need to be set accordingly.  

### Intake Request - Techical Debt

**FE**
- [x] [FE/Content] Analytics Implementation for COVID FAQ Accordion Embedded Links #13727 (WIP - Nick)

### Kanban Board
_Please select a ticket and include [WIP - [NAME]] next to the ticket that is being worked._  Pick up tickets by priority on the `To Do ` section to begin and move ticket through kanban workflow until `Done`. Please include resolution steps on tickets along with instructions if for some reason you are unable to complete the ticket during this sprint.  

Please tag @brianalloyd on tickets when moved to **Done** section for validation and closeout.  Please reach out if you have any questions or concerns in the interim.  Welcome to **PW team** (for this sprint) we're excited to have the help.  

<details> 

 <summary> TO DO </summary>

</details>

<details> 

 <summary> ON-GOING </summary>

- [ ] [FE] Enhancement: RS mobile views, left margin is too smooshed to the edge and cutting off text #17470 (WIP Sandra)

</details>

<details> 

 <summary> DONE </summary>

- [x] [FE] Link TTY: 711 number in footer and right rail of hub landing pages #18151 (Sandra) @brianalloyd 
- [x] [FE] [COGNITION]: Footer links are inconsistently styled and missing interactive cues #3179 (Sandra) @brianalloyd 
- [x] [FE] Main nav's "Contact Us" button can wrap when logged-in user has a long name #18412 (Sandra) @brianalloyd 
- [x] [FE] [COGNITION]: Multiple ambiguities with linked text in content block #3556 (Sandra) @brianalloyd 
- [x] [FE] Use redesigned "In this section" button for triggering sidebar on mobile devices across benefit pages #13325 (WIP Erik)
- [x] [FE] VA.gov mobile nav bugs #8256 (WIP Erik)

**Comment by brianalloyd** [comment]
@sanlouise and @erikphansen reaching out on status of WIP items as we approach end of sprint.  If you all could update tickets that are not complete and provide breadcrumbs for the next developer that will be working these tickets.  I also wanted to send out a huge "THANK YOU" for you support this sprint and helping our team work through some of these backlog items.  Appreciate it.

**Comment by erikphansen** [comment]
@brianalloyd I've got [this one PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15795) open that should pass Jenkins finally. Once that's merged it'll handle https://github.com/department-of-veterans-affairs/va.gov-team/issues/18916 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/18917

**Comment by brianalloyd** [comment]
Sprint 39 is a wrap, closing out ticket, transitioned open items for tickets to Sprint 40 priorities for reference.
