### ISSUE TITLE
Including LGY debts in the FSR wizard 

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18352]
## Issue Description
In our meeting with FSR SMEs, we removed LGY (Loan Guarantee Service) from the first layer of the wizard due to some complexity that is 'out of scope.' We'd like to revisit adding LGY debts back into the wizard to ensure veterans looking for assistance with LGY debts can get where they need to go.

---
## Tasks
- [ ] Meet and discuss LGY complexities with DMC
- [ ] Revise decision tree and content
- [ ] Send draft to DMC for review

## Acceptance Criteria
- [ ] Draft of decision tree and content uploaded to GH and linked to this ticket
- [ ] Draft sent to DMC for review
- [ ] Ticket created to address feedback attached to this ticket (if applicable)
---

**Comment by HeatherRienks** [comment]
@denisecoveyduc to discuss with Melonie Wheeler about next steps.

**Comment by denisecoveyduc** [comment]
11/2/23 - I have spoken with Melonie and there is a along story about this but the bottom line is that for Veterans who may have questions about these LGY/Home Loan Guarantee we (VODA) would need to route them on the wizard to call VBA. I am confirming the details and will circle back asap.. maybe this is something we can weave into the current VBA wizard updates. FYSA @mgleo @josephrlee

**Comment by denisecoveyduc** [comment]
11/3/23- Melonie is discussing internally with DMC. This is a bit more complicated that just directing Veterans to a phone number because there are 3 different types of LGY Loans and the type determines the information we would need to provide the Veteran. There may be a way to better articulate who the Veteran should contact but they need some time to discuss internally before the provide guidance.

**Comment by denisecoveyduc** [comment]
Closing this ticket for now as it is out of scope at the moment. Capturing on longer term roadmap and we will reopen a proper, detailed ticket when we get to a place where we can tackle this.
