### ISSUE TITLE
[DISCOVERY] Adopting the form system for Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18355]
## Issue description
The Facility Locator currently does not handle errors accessibly or in alignment with the design system. It may be best for us to adopt the form system in order to be compliant and efficient. 

Relevant issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18351

## Tasks
- Investigate the options and components available through the form system (with mobile first lens)
- Determine if/how form system will work with our responsive design/mobile first experience
- Determine if/how form system will work with our secondary behaviors (after the "Search this button" has been used to trigger a new search)
- Evaluate level of effort to adopt form system compared to addressing error messages with current UI

## Acceptance Criteria
Recommendation for path forward to resolve the accessibility error message issue
- [ ] should we handle error messages with current UI or adopt form system
- [ ] timing with regard to mobile first experience
- [ ] timing with regard to service first search

**Comment by mpelzsherman** [comment]
Analysis and recommendations attached

[Facility Locator Search Form -_ react-jsonschema-form_.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5845537/Facility.Locator.Search.Form.-_.react-jsonschema-form_.pdf)

**Comment by mpelzsherman** [comment]
We are leaning toward recommending converting to the forms system.

This will be a complete re-write of the search form. It will require an environment check to allow testing in staging.

No impact to secondary behaviors.

Level of effort to convert to form system: 2-3 weeks.
Level of effort to implement error messages post conversion: 2-3 days
