### ISSUE TITLE
[Debt Letters] Expand the 'Debt letters history' table to 'Debt history'

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18354]
## Issue Description
_We're making improvements to the “Debt letter history” table by transforming it into “Debt history” by including retrospective content for certain diary codes. The goal is to include a more holistic view of the diary code changes for the debt. By expanding the debt letter history section of the debt detail page, we will need to account for a much longer table._

---
## Tasks
- [ ] _Add the content under the 'Debt history content' tab in this spreadsheet (still waiting for finalized content - TBD) for the corresponding diary codes_
- [ ] _Each debt can now potentially have a long history, so we need to [add pagination](https://design.va.gov/components/pagination). Please refer to [this UXPin prototype](https://preview.uxpin.com/8bf81d84b749c20c8c2635709fe57e4547d9c30b#/pages/135518502/simulate/no-panels?mode=i) for more information about the styling._

## Acceptance Criteria
- [ ] _The retrospective content for each diary code has been added to the 'Debt history'_
- [ ] _The updated table matches the UI in the UXPin prototype_
- [ ] _UI updates have been reviewed by a BaM2 designer_

**Comment by denisecoveyduc** [comment]
Feb 9, 22 - Blocked as we are awaiting feedback from the DMC. I followed up with Jill Anderson (DMC) today to collect any feedback on this approach, will update with any comments when we hear back.

**Comment by rileyorr** [comment]
@denisecoveyduc following up on this while in backlog grooming - have you received feedback from Jill on the content?

**Comment by denisecoveyduc** [comment]
Need to create a new ticket to review this table with the new diary codes to make sure they line up correctly

**Comment by HeatherRienks** [comment]
@denisecoveyduc - to follow up with Jill.

**Comment by denisecoveyduc** [comment]
Moving this out of blocked.. this will be integrated in as part of the VBMS Letter work in Epic #52762

**Comment by Tom-Davis** [comment]
@denisecoveyduc will check with the DMC team to verify the number of records and then either close or move to another Epic.

**Comment by josephrlee** [comment]
To determine whether pagination is needed on the debt history table, we need to know the average number of line items a single debt has; in our mockups, we only have about 6 lines, so pagination is currently unnecessary.
 
![Image](https://github.com/user-attachments/assets/274e29d2-a49b-4f3d-bd9a-7e090f19d652)

But pagination would probably be helpful if the average debt transaction were to be 10+ lines. @denisecoveyduc, can you please reach out to DMC to verify the average number of transactions a debt might have?

**Comment by josephrlee** [comment]
@denisecoveyduc, thanks for getting the information; this is helpful! Will go ahead and create a new follow-up ticket for this.

**Comment by HeatherRienks** [comment]
@josephrlee - do you have any info on this one? TY!

**Comment by josephrlee** [comment]
@HeatherRienks marking this as closed now, I have [created the follow-up ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105603) with the information that @denisecoveyduc has provided.
