### ISSUE TITLE
Revisit pagination for Community care results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18372]
## Issue Description
The best user experience is an accurate representation and display of search results, including the total number in the heading and paginated. However, because sort order for PPMS results could not be guaranteed, the team decided to return results without pagination (and for all facility types, to be consistent). Now that we've optimized our query and will be moving to a Rails engine, we can revisit this issue. 

---
## Tasks
- [ ] Determine best approach for PPMS search results 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate to #13138
