### ISSUE TITLE
Bio Info Page Issue with SIP component

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18373]
## Background
An issue was found with the interactions between the biographical info and the save in progress (SIP) component where non-LOA3's were not able to convey certain fields to the form.

## Solution 
At this point we are going by-pass the bio info page on login and simply present the fields as they exist pre-filled.  Once the bio info page as a component is able to handle more granular control over what pages are redirect upon login we can reinstate it and allow users to verify their identity before completing their ID.me account.

## Tasks
- [ ] Comment out the bio confirmation card post-login
- [ ] Present the form as it exists with pre-fill in place

## Acceptance Criteria
- [ ] The bio confirmation page does not overwrite the pre-fill data
- [ ] A PR has been requested for merging
