### ISSUE TITLE
[VAMC] VISN-2 - WEB MODERNIZATION EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18386]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Albany health care
- [ ] VA Bronx health care
- [ ] VA Finger Lakes health care
- [ ] VA Hudson Valley health care
- [ ] VA New Jersey health care
- [ ] VA New York Harbor health care
- [ ] VA Northport health care
- [ ] VA Syracuse health care
- [ ] VA Western New York health care

Facilities include for System:
VA Albany health care

- [ ] 528A8	Samuel S. Stratton Department of Veterans Affairs Medical Center
- [ ] 528G2	Westport VA Clinic
- [ ] 528G3	Bainbridge VA Clinic
- [ ] 528G6	Fonda VA Clinic
- [ ] 528G7	Catskill VA Clinic
- [ ] 528GT	Glens Falls VA Clinic
- [ ] 528GV	Plattsburgh VA Clinic
- [ ] 528GW	Schenectady VA Clinic
- [ ] 528GX	Troy VA Clinic
- [ ] 528GY	Clifton Park VA Clinic
- [ ] 528GZ	Kingston VA Clinic
- [ ] 528QK	Saranac Lake VA Clinic

VA Bronx health care
- [ ] 526	James J. Peters Department of Veterans Affairs Medical Center
- [ ] 526GA	White Plains VA Clinic
- [ ] 526GB	Yonkers VA Clinic
- [ ] 526GD	Thomas P. Noonan Jr. Department of Veterans Affairs Outpatient Clinic

VA Finger Lakes health care
- [ ] 528A5	Canandaigua VA Medical Center
- [ ] 528A6	Bath VA Medical Center
- [ ] 528G4	Elmira VA Clinic
- [ ] 528G8	Wellsville VA Clinic
- [ ] 528GE	Rochester VA Clinic
- [ ] 528QC	Clinton Crossings VA Clinic
- [ ] 528QE	Coudersport VA Clinic
- [ ] 528QF	Wellsboro VA Clinic

VA Hudson Valley health care
- [ ] 620	Franklin Delano Roosevelt Hospital
- [ ] 620A4	Castle Point VA Medical Center
- [ ] 620GA	New City VA Clinic
- [ ] 620GB	Carmel VA Clinic
- [ ] 620GD	Goshen VA Clinic
- [ ] 620GE	Port Jervis VA Clinic
- [ ] 620GF	Monticello VA Clinic
- [ ] 620GG	Poughkeepsie VA Clinic
- [ ] 620GH	Eastern Dutchess VA Clinic

VA New Jersey health care
- [ ] 561	East Orange VA Medical Center
- [ ] 561A4	Lyons VA Medical Center
- [ ] 561BZ	James J. Howard Veterans' Outpatient Clinic
- [ ] 561GA	Hamilton VA Clinic
- [ ] 561GB	Elizabeth VA Clinic
- [ ] 561GD	Hackensack VA Clinic
- [ ] 561GE	Jersey City VA Clinic
- [ ] 561GF	Piscataway VA Clinic
- [ ] 561GH	Morristown VA Clinic
- [ ] 561GI	Tinton Falls VA Clinic
- [ ] 561GJ	Paterson VA Clinic
- [ ] 561GK	Sussex VA Clinic

VA New York Harbor health care
- [ ] 630	Manhattan VA Medical Center
- [ ] 630A4	Brooklyn VA Medical Center
- [ ] 630A5	St. Albans VA Medical Center
- [ ] 630GA	Harlem VA Clinic
- [ ] 630GB	Staten Island Community VA Clinic

VA Northport health care
- [ ] 632	Northport VA Medical Center
- [ ] 632GA	East Meadow VA Clinic
- [ ] 632HA	Valley Stream VA Clinic
- [ ] 632HB	Riverhead VA Clinic
- [ ] 632HC	Bay Shore VA Clinic
- [ ] 632HD	Patchogue VA Clinic

VA Syracuse health care
- [ ] 528G5	Auburn VA Clinic
- [ ] 528A7	Syracuse VA Medical Center
- [ ] 528G9	Tompkins County VA Clinic
- [ ] 528GL	Massena VA Clinic
- [ ] 528GM	Donald J. Mitchell VA Outpatient Clinic
- [ ] 528GN	Binghamton VA Clinic
- [ ] 528GO	Watertown VA Clinic
- [ ] 528GP	Oswego VA Clinic
- [ ] 528QN	Watertown 2 VA Clinic

VA Western New York health care
- [ ] 528	Buffalo VA Medical Center
- [ ] 528A4	Batavia VA Medical Center
- [ ] 528GB	Jamestown VA Clinic
- [ ] 528GC	Dunkirk VA Clinic
- [ ] 528GD	Niagara Falls VA Clinic
- [ ] 528GK	Lockport VA Clinic
- [ ] 528GQ	Lackawanna VA Clinic
- [ ] 528GQ01	Springville Community Based Outpatient Clinic
- [ ] 528GR	Olean VA Clinic

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live
