### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Augusta health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18384]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Augusta healthcare system Legacy Site](https://www.augusta.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-7 Playbook locations](https://drive.google.com/drive/folders/1b6YaJVZLe80SrIj2Z0ThizP6dNDHA851)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_509	Charlie Norwood Department of Veterans Affairs Medical Center
- [x] vha_509A0	Augusta VA Medical Center-Uptown
- [x] vha_509GA	Athens VA Clinic
- [x] vha_509GB	Aiken VA Clinic
- [x] vha_509QA	Ray Hendrix Department Of Veterans Affairs Clinic

## Staff Profiles for the the following Health Service Programs
- [x] Leadership Page
- [x] Caregiver-support
- [x] Homeless-Veteran-Care
- [x] LGBT-Veteran-Care
- [x] Mental-Health_Care
- [x] Minority-Veteran-Care
- [x] Patient-Advocates
- [x] Returning-Service-Member-Care
- [x] Suicide-Prevention
- [x] Women-Veteran-Care
* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Charlie Norwood Department of Veterans Affairs Medical Center
* Augusta VA Medical Center-Uptown
* Athens VA Clinic
* Aiken VA Clinic
* Ray Hendrix Department Of Veterans Affairs Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] All Staff Profiles have been documented for Analytics for creation of Health Service pages.

**Comment by bcastoe** [comment]
Task #18459 - Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Columbia South Carolina health care [BA] - is Complete and moved to Validate.
1. Augusta Playbook created and all Health Services matched up to 95 Health Service list
2. Augusta Caregiver/Coordinator data collected and data loaded to Drupal
