### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Atlanta health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18383]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Atlanta healthcare system Legacy Site](https://www.atlanta.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-7 Playbook locations](https://drive.google.com/drive/folders/1b6YaJVZLe80SrIj2Z0ThizP6dNDHA851)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_508	Atlanta VA Medical Center
- [x] vha_508QF	Atlanta VA Clinic
- [x] vha_508GJ	Blairsville VA Clinic
- [x] vha_508GN	Covington VA Clinic
- [x] vha_508GA	Fort McPherson VA Clinic
- [x] vha_508QD	Fulton County VA Clinic
- [x] vha_508QE	Gwinnett County VA Clinic
- [x] vha_508QC	Henderson Mill VA Clinic
- [x] vha_508GH	Lawrenceville VA Clinic
- [x] vha_508GI	Newnan VA Clinic
- [x] vha_508QI	North DeKalb County VA Clinic
- [x] vha_508QJ	North Fulton County VA Clinic
- [x] vha_508GO	Northeast Cobb County VA Clinic
- [x] vha_508GE	Oakwood VA Clinic
- [x] vha_508GM	Pickens County VA Clinic
- [x] vha_508GL	Rome VA Clinic
- [x] vha_508GP	South Cobb County VA Clinic
- [x] vha_508QH	South Fulton County VA Clinic
- [x] vha_508GG	Stockbridge VA Clinic
- [x] vha_508GK	Trinka Davis Veterans Village
- [x] vha_508GF	(Austell) West Cobb County VA Clinic

## Staff Profiles for the the following Health Service Programs
- [x] Leadership Page
- [x] Caregiver-support
- [x] Homeless-Veteran-Care
- [x] LGBT-Veteran-Care
- [x] Mental-Health_Care
- [x] Minority-Veteran-Care
- [x] Patient-Advocates
- [x] Returning-Service-Member-Care
- [x] Suicide-Prevention
- [x] Women-Veteran-Care
* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done 
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Atlanta VA Medical Center
* Atlanta VA Clinic
* Blairsville VA Clinic
* Covington VA Clinic
* Fort McPherson VA Clinic
* Fulton County VA Clinic
* Gwinnett County VA Clinic
* Henderson Mill VA Clinic
* Lawrenceville VA Clinic
* Newnan VA Clinic
* North DeKalb County VA Clinic
* North Fulton County VA Clinic
* Northeast Cobb County VA Clinic
* Oakwood VA Clinic
* Pickens County VA Clinic
* Rome VA Clinic
* South Cobb County VA Clinic
* South Fulton County VA Clinic
* Stockbridge VA Clinic
* Trinka Davis Veterans Village
* (Austell) West Cobb County VA Clinic
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [x] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [x] All Staff Profiles have been documented for Analytics for creation of Health Service pages.

**Comment by ltrombley** [comment]
Task #18383 - Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Atlanta health care [BA] - is Complete and moved to Validate.
1. Atlanta Playbook created and all Health Services matched up to 95 Health Service list
2. Atlanta Caregiver/Coordinator data collected and data loaded to Drupal
