### ISSUE TITLE
Add sentence to VGLI page with new April 2021 rates info

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#18397]
## Issue Description
Per stakeholder Lori Hamilton, VGLI rates are increasing as of April 1, 2021. Before then, we need to add a sentence to our VGLI page announcing this. In April, we need to add a link to the new rates page as well. 

Page to update:  https://www.va.gov/life-insurance/options-eligibility/vgli/ 

Suggested language from SME:

All Veterans insured under the Veterans’ Group Life Insurance (VGLI) program will see a reduction in their premiums effective April 1, 2021.
[See the new VGLI premium rates effective April 1, 2021 (PDF)](https://www.benefits.va.gov/INSURANCE/docs/VGLI_Rates_04-2021.pdf)

## Tasks
- [x] Add info about new rates to VGLI page before April 2021
- [x] Get SME approval on text
- [x] Add link to new rates table in April 2021

## Acceptance Criteria
- [x] New rates info showing on live page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Here's the preview link with the revised content, in a note, under "How much will I pay for these benefits."

Ready for your copyedit, then you can publish it for tomorrow's build!

**Comment by bethpottsVADEPO** [comment]
http://preview-prod.vfs.va.gov/preview?nodeId=769

**Comment by RLHecht** [comment]
@bethpottsVADEPO This page is published. I just added (PDF) to the end of the link. I'll let the Lori know.

**Comment by RLHecht** [comment]
This work is now complete.
