### ISSUE TITLE
Sentry is not receiving errors from vets-api sandbox environment

### ISSUE THREAD

**Issue by SlakrHakr** [department-of-veterans-affairs/va.gov-team#18403]
## Description
There should be errors present in Sentry from our sandbox environment but there doesn't appear to be anything here:
http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=sandbox&project=3&query=is%3Aunresolved&statsPeriod=14d

## Background/context/resources
I asked why this might be the case in slack here:
https://dsva.slack.com/archives/CBU0KDSB1/p1607376862233900

## Technical notes
It was suggested that we may not have the proper variable set in credstash in that environment:
https://github.com/department-of-veterans-affairs/devops/blob/d47154eb4840438ecde34036f1cd8164ce6ccd0b/ansible/deployment/config/vets-api/sandbox-settings.local.yml.j2#L163

---
## Tasks
- [x] Check credstash for this information
- [x] Resolve if simply missing the above information in credstash
- [x] Investigate alternate theories on why errors in sandbox are not sending to Sentry

## Definition of Done
- [x] Errors from the vets-api sandbox environment should be present in Sentry

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s)

**Comment by SlakrHakr** [comment]
Opened the issue over here: https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/168

**Comment by jhouse-solvd** [comment]
from @jbritt1 "essentially the traffic wasn't being allowed to the sentry10 instance from the sandbox vpc". 

I'm checking w/ @SlakrHakr if all is well with the need for this request. and then will close.
