### ISSUE TITLE
[FE][Spike] Understand Testing updates from platform

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18416]
## Related Documentation
- [Slack about Pact](https://dsva.slack.com/archives/C5HP4GN3F/p1610402901305800)
- [Slack about Cypress](https://dsva.slack.com/archives/C01CHAY3ULR/p1610464253026400)

## Description
The engineering team needs to understand the requirements and updates to the new testing libraries

## Questions to Answer
- [x] As a FE engineer what cypress tests need to be updated
- [x] As a FE engineer what Pact tests need to be created and when 
- [x] As a BE engineer what Pact tests need to be created and when 

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [x] Answer Quetstions

## Acceptance Criteria
- [ ] Engineering team understands.

**Comment by mdewey** [comment]
FE Tasks

- [ ] Update fixtures
- [ ] Change route to intercept
- [ ] Remove __dirname

Estimate: a

**Comment by mdewey** [comment]
Pact tests: 

No immediate action, timeline still up in the air. 

For Front end, 
- Once required, all new API calls will have to use Pact and the feature will not be able to be merged until the Pact is resolved in both the front and back end. 

For the back end
- API endpoints for the Front end will need Pacts
- API calls out to Lighthouse and MAP will need Pacts

Using Pact is not being technically enforced yet, so this can still be a low priority while we are driving towards our MVP.

**Comment by mdewey** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18530
