### ISSUE TITLE
[FE] Update Reason for Visit UI 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18417]
## User Story
As an older veteran, 
I should see the relevant life experiences, 
so that i better understand the question.

## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
 - [Slack conversation](https://dsva.slack.com/archives/C0136TS768M/p1610466229036700)

## Description
Update working for the `reason for visit` question.

## Tasks

- [x] Update wording. 
- [x] Create user tests

## Acceptance Criteria
- [ ] Passes Accessability checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Going to be in with the PR for https://github.com/department-of-veterans-affairs/va.gov-team/issues/18238

**Comment by mdewey** [comment]
Merged, waiting for deployment to staging

**Comment by mdewey** [comment]
@kristenmcconnell  This is in staging. Can you confirm?

**Comment by kristenmcconnell** [comment]
The scope of this story looks good. I see "retirement" was added to the question.
