### ISSUE TITLE
Discovery into BigQuery<>Github

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18414]
## Issue Description
To understand how Github is being used and to understand the velocity and completion of our open VSP tickets, we are looking to connect our data warehouse to Github. This issue is around the technical discovery for that work.

---
## Tasks
- [ ] Determine & document steps for connecting BigQuery to Github
- [ ] Determine any dependencies for BigQuery<>Github
- [ ] Determine any blockers for BigQuery<>Github
- [ ] Determine which datasets to connect, if we need to pick and choose
- [ ] Stretch: Discovery around data connections for [Accessibility Dashboarding
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16423)

## Acceptance Criteria
- [ ] VSP Analytics & Insights understand the general work & potential dependencies or blockers that will be involved in connecting BigQuery to Github

**Comment by joanneesteban** [comment]
https://www.gharchive.org/

**Comment by JasonTheBearded** [comment]
the gharchive dataset captures _event_ data as it happens on github for all public repos. As such, in order to visualize the health of our github projects, we will need to create additional calculations to determine tickets that are currently active based on an open event but no associated close event.

**Comment by joanneesteban** [comment]
@JasonTheBearded documenting the [question about PRs and Github teams](https://dsva.slack.com/archives/CKCRMLGAC/p1612823577090600).

**Comment by JasonTheBearded** [comment]
Testing tools team provided workflow to bring GitHub issues into BigQuery. It's now loading all issues so we're good to close this ticket.
