### ISSUE TITLE
Discovery into BigQuery<>Medallia

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18413]
## Issue Description
To track survey usage for VA.gov metrics and for the DEPO Platform to understand how Medallia is being used, we are looking to connect our data warehouse to Medallia. This issue is around the technical discovery for that work.

[GTM Implementation Issue.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18278)

---
## Tasks
- [ ] Determine & document steps for connecting BigQuery to Medallia
- [ ] Determine any dependencies for BigQuery<>Medallia
- [ ] Determine any blockers for BigQuery<>Medallia

## Acceptance Criteria
- [ ] VSP Analytics & Insights understand the general work & potential dependencies or blockers that will be involved in connecting BigQuery to Medallia

**Comment by JasonTheBearded** [comment]
Discovery complete. 

Daily files will be uploaded to a production level bucket in our Google Cloud instance. Once the file is received a google cloud function will execute to load the file into a BigQuery table inside a Medallia specific BQ dataset. Process will be automated once Medallia export is live and in Production.

We've received an updated test file so all known columns are available, only remaining dependency is the readiness of Medallia export in production and once in production, load system will depend on the import of a new file.

Current known blocker is confirmation of Medallia usage within our BigQuery ATO. Once confirmed, the team should be set to go live.

Closing ticket.
