### ISSUE TITLE
AE: Sprint 39

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18428]
## Priorities
1.  All MyVA work
2. Getting DD4EDU ready for QA next sprint
3. VA Profile Notification preferences BE technical discovery
4. Resolving analytics error discrepancies
5. BE Profile issues (deprecated ID's and MVI201 errors) 

## Profile
**FE**
- [x] Look into analytics error discrepancies #18270 (see follow up BE ticket below #18349)
- [x] Contact Info edit error alert has too much top margin #18548
- [x] [FE] Research frontend integration with Sentry #18501

**BE**
- [ ] Are we sending deprecated IDs to VA Profile? #17739
- [ ] Log when users have a mvi_response.status of OK then return a va profile MVI201 error #18349

## My VA redesign
**PM**
- [x] [PM] Make a list of staging test cases based on wireframes (MyVA) #18042

**Design**
- [x] [Design] MyVA Visual design / Get feedback from design team #18469
- [x] [Design] Health care: Cerner/MHV split use case for My VA dashboard #14025
- [x] [Design] Submit MyVA wireframes for copy review #17530 

## Direct deposit for edu
**Be ready for QA next sprint**

**PM**
- [x] [PM] Submit QA request for Sprint 39 (DD for Edu) #18046

**Design** (Jim Adams)
- [x] [Design] Review Erik's initial DD for Edu build #18050
- [x] [Design] Error to show when we cannot connect to a Direct Deposit endpoint #18338 (note: This should not hold up QA)

**FE**
- [x] Update location link for View Payment History #18472
- [x] [FE] Make updates to DD for Edu as needed prior to going into QA #18051

**BE**
- [x] [BE] Set up direct deposit for edu confirmation email #18262

## VA Profile Notification Preferences
- [x] Technical Discovery #18054
- [ ] Start implementation #18056

PW FE work
