### ISSUE TITLE
Build components to dist/

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#18422]
## Issue Description
Repo: `component-library`

Rather than muddying up our current working directory when we run `yarn build` before publishing, we should build to `dist/` and publish the contents of that. Unfortunately, this creates some technical hurdles. When `vets-website` is running Webpack 5, we'll have access to [package exports](https://webpack.js.org/guides/package-exports/), which will allow us to build to `dist/` and still import without specifying `dist` in the import path.

---
## Tasks
- [ ] Build files to `dist/`
- [ ] In `.npmignore`, ignore all files except those in `dist/`
- [ ] Add `exports` to `package.json` so we don't have to specify `dist` in our import path
    - Like `import Thing from '@department-of-veterans-affairs/component-library/dist/Thing';`

## Acceptance Criteria
- [ ] The build `.js` files aren't added to the project root directory

**Comment by cvalarida** [comment]
Depends on https://github.com/department-of-veterans-affairs/vets-website/pull/15526

**Comment by k80bowman** [comment]
This work is specific to the React components.

**Comment by bkjohnson** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/837
