### ISSUE TITLE
Update Product Development Checklist for new form deployment 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#18432]
## Issue Description
VSA Decision Tools team needs to know when a new form is deployed. This will be added to the [Product Development Checklist.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md) 

Verify with Marci McGuire from Decision Tools when changes have been implemented.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] VFS teams are aware that they need to contact Decision Tools team if they are deploying a new form on VA.gov.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jimuhh** [comment]
@shiragoodman , @rroueche  is there any existing documentation on how VFS teams who aren't familiar with the process should go about alerting VSA Decision Tools on the new form deployment?

**Comment by shiragoodman** [comment]
I do not think there is any existing documentation, however the person to ask is @MarciMcGuireGCIO as she is the PM for the Decision Tools team (hi Marci!).

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman We used to post a monthly announcement on Slack and ask teams to contact us if they needed to have a link added. Then someone would update the form info in the CMS at the appropriate time.

We opened this ticket with the intent of getting that  added to the collab cycle.

I am not sure how the new team will want to handle.  @LindaLi123 is the new PM and may be able to answer.

I hope that helps!

**Comment by shiragoodman** [comment]
Thanks @MarciMcGuireGCIO . We talked to our PO about adding this in the Collab Cycle and we decided it wasn't the right place. However, we are working to expand and improve our [Product Development Checklist. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Product-Development-Checklist.1971650643.html) The goal of this checklist is to inform VFS teams of important steps as they build and launch their product on VA.gov. It will be used in conjunction alongside the Collaboration Cycle.

In the interim, our team is aware that new forms need to be updated on Find a VA Form, so we will be sure to direct teams to you in whatever way makes sense. @LindaLi123 please let us know your thoughts!

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @shiragoodman !

**Comment by jimuhh** [comment]
@shiragoodman I followed up w/ Maria at VA.notify and Linda Li about forms. No word back from either yet but will keep you posted.

**Comment by jimuhh** [comment]
@shiragoodman -- I reached out to Linda Li. She  isn't going to have any info for me before end of sprint. Hopefully she will get me that next week and I can wrap this up then.

**Comment by jimuhh** [comment]
This team is still working out the details of their process, so I'm just going to park this here until they have more specific guidance to share.

**Comment by shiragoodman** [comment]
Interim solution: contact Decision Tools team via their Slack channel #vsa-decision-tools

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman - the Search & Discovery team now manages Find a VA Form and their channel is #vsa-search.

**Comment by shiragoodman** [comment]
thanks @MarciMcGuireGCIO !

**Comment by MarciMcGuireGCIO** [comment]
Sure thing!

**Comment by jimuhh** [comment]
I got the OK from Linda so I've added the text below under "discoverable"

- If your product includes forms, you have alerted the  [#va-search Slack channel.](https://dsva.slack.com/archives/C011K1VSTC3)

**Comment by shiragoodman** [comment]
that sounds good to me. thanks @jimuhh !

**Comment by jimuhh** [comment]
Updated. Closing ticket
