### ISSUE TITLE
Homepage - Express Care appointment details

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18443]
## Issue Description
Add Express Care (EC) appointment details page styling and interaction.

---
## Tasks
- [ ] request submitted

- [ ] request escalated

- [ ] completed/resolved

- [ ] canceled

## Acceptance Criteria
- [x] Changes are behind the va_online_scheduling_homepage_refresh feature flag

- [x] Given user clicks/taps an EC request appointment card, When request is in submitted status, Then appointment details open on a new page AND option to cancel appears
- [x] Given user clicks/taps an EC request appointment card, When request is in escalated status, Then appointment details open on a new page AND option to cancel **does not** appear
- [x] Given user clicks/taps an EC request appointment card, When request is in completed status, Then appointment details open on a new page 
- [x] Given user clicks/taps an EC request appointment card, When request is canceled, Then appointment details open on a new page AND cancelation note appears
- [x] Appointment detail page has a unique URL

- [ ] CONTENT - Existing copy related to statuses is maintained

- [ ] CONTENT - Cancellation copy matches specs, respective to who cancelled the request.

- [ ] DESIGN - All designs match the specs
- Request submitted (in context) - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/1K0v8zb#Inspector
- Request templates:
  - Request submitted - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/jg7vgZD#Inspector
  - Request escalated - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/R1yK158#Inspector
  - Completed/resolved - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/dl0Yl8m#Inspector
  - Canceled - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/zx7Vx15#Inspector
  - Canceled : couldn't reach veteran - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/oYM2Yej#Inspector
