### ISSUE TITLE
Discovery into BigQuery<>Confluence & Documentation Homepage

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18441]
## Issue Description
To understand how our documentation is being used, we are looking to connect our data warehouse to Confluence; and to understand how our documentation _has_ been used, we are looking to connect our data warehouse to the [Documentation Homepage analytics](https://analytics.google.com/analytics/web/?authuser=0#/report-home/a50123418w224573768p212889364). This issue is around the technical discovery for that work.

---
## Tasks
- [ ] Determine & document steps for connecting BigQuery to Confluence
- [ ] Determine any dependencies for BigQuery<>Confluence
- [ ] Determine any blockers for BigQuery<>Confluence
- [ ] Determine which datasets to connect, if we need to pick and choose
- [ ] Determine & document steps for connecting BigQuery to the current Documentation Homepage Google Analytics

## Acceptance Criteria
- [ ] VSP Analytics & Insights understand the general work & potential dependencies or blockers that will be involved in connecting BigQuery to Confluence & the Documentation Homepage's analytics.

**Comment by joanneesteban** [comment]
@JasonTheBearded keeping this in the backlog for now since we didn't prioritize this work for Sprint 43. If you do have time, feel free to pull it in, but otherwise, we can keep it in the backlog.

**Comment by joanneesteban** [comment]
Two parts of this data:

1. Historical: The current Documentation Homepage Google Analytics
  - Our Gatsby pages are currently being tracked in GA.
2. Future: Confluence
  - Liani's team is looking to track Confluence via Google Analytics. We'll need to coordinate with them to see how far they've gotten, if they need support from us, and then connect that information to BigQuery.

**Comment by joanneesteban** [comment]
Confluence work will be tracked [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18746)

**Comment by JasonTheBearded** [comment]
Documentation homepage tracking is up and running. Currently feeding into AooA DOMO Dashboard. Closing ticket
