### ISSUE TITLE
Address 500 Errors for View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18440]
## Background
There is potential for an error where the call for a list of payments will work and then within in that, a payment could not show up and it throws an error.

## Considerations
- `object[:payments]` - the list of payments
- `object[:payments][:payment]` - the actual payment within the list

## Tasks
- [ ] Check for `nil` values in the data object
- [ ] Address them appropriately

## Acceptance Criteria
- [ ] Payment 500 errors are more granularly laid out
- [ ] A PR has been requested for merging
