### ISSUE TITLE
Analytics Implementation or QA Support for Pittsburgh Facility Pilot

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#1846]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA? - Google Analytics

- Who is this request for?

PO: @andrewlewandowski 
Delivery Manager: @jefflbrauer 
Communication Slack Channel: https://dsva.slack.com/messages/CFM5WUYGL
    
- What team/project is this work for?
VA.Gov Modernization - CMS team for the VA Pittsburgh Facility Pilot 
    
- Provide the Domain where Google Analytics needs to be implemented
va.gov/pittsburgh-health-care
No PII

**Milestones**
Beta Launch - Early October. We want to gather analytics for about 6 weeks to determine if any further optimization is required before launch.

Full Site Launch - November/December, pending above

- Typical Website Interactions to Track

**Top pages to track click events and user flows/funnels into content pages:**

- [ ] VA Pittsburgh home page: https://www.va.gov/pittsburgh-health-care/ (edited) 
- [ ] Health services listing page: https://www.va.gov/pittsburgh-health-care/health-services/ 
- [ ] Locations listing page: https://www.va.gov/pittsburgh-health-care/locations/ (edited) 

**Track banner referrals** on pittsburgh.va.gov as well as referrals from va.gov/pittsburgh-health-care to the legacy site from our banner. 

**Facility pages (x7)**:
- [ ] https://www.va.gov/pittsburgh-health-care/locations/hj-heinz/ **NEED FINAL URL @kevwalsh or @jefflbrauer** 
- [ ] https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
- [ ] https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/
- [ ] https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/
- [ ] https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic/
- [ ] https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic/
- [ ] https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic/

**Patient task pages (x6):**
- [ ] https://www.va.gov/pittsburgh-health-care/make-an-appointment/
- [ ] https://www.va.gov/pittsburgh-health-care/register-for-care/
- [ ] https://www.va.gov/pittsburgh-health-care/pharmacy/
- [ ] https://www.va.gov/pittsburgh-health-care/medical-records-office/ **URL CHANGED/UPDATED**
- [ ] https://www.va.gov/pittsburgh-health-care/billing-insurance/
- [ ] https://www.va.gov/pittsburgh-health-care/contact-us/

**This product has a ton of accordions — we’ll want to track those.** 

**We also would like to track scroll depth (all H2s and H3s on each of the URLs above.** 

> Please leave the following blank

## Acceptance Criteria
- [x] Audit site to see what nav tracking already exists
- [x] Track main calls-to-action (AKA user tasks) e.g. "Make an Appointment"
- [x] Review jumplinks and determine approach for tracking these as History Changes that trigger a pageview vs. nav tracking
- [x] Banner on the page that tracks clicks back to legacy pittsburgh.va.gov; also track banner clicks on legacy page to modernized Facility pilot
- [x] Get naming convention from Jeff on `vads-facility-hub-cta-label` for mid-page "Manage Your Healthcare Online" area
- [x] Get priority on other content blocks, including "Stories" (and its CTA button) and "In the spotlight" (and its CTA button)
- [x] Custom dimensions for healthFacilityType (e.g. Campus vs. Clinic) and location
- [x] Scroll Depth tracking [Nedie]
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
**Updates:** CC: @jefflbrauer @nedierecel 

1) As a result of our previous go-ahead work, we already have accordion expands/collapses, side navigation expands/collapses, scroll depth, and outbound link tracking available.  


2) I have documented the various dataLayer pushes we will need from FE devs for tracking the button CTA's, jumplink clicks, and banner clicks (see below DL example) 

An example of the button click dataLayer push

```javascript
dataLayer.push({'event': 'nav-primary-button-click'});
```

The purpose for going with a simplistic, generic dataLayer push as shown above is to enable out-of-box tracking for any time a future Primary Button UX component would be used. This is the same sort of logic we would use for the other trackable components. 

We can tailor the event action to output whatever granularity is necessary. But below is an example of what the primary button (CTA) will look like. 

![image](https://user-images.githubusercontent.com/48527022/65437523-f479f180-ddf1-11e9-8f4b-1b46b6428dd0.png)

3) We also will identify the location and facility type (clinic vs campus) by 'scraping' the HTML and storing in custom dimensions, an example of information outputted would be: 

- Health Facility Type: Campus _// or clinic_
- Health Facility Location: Pittsburgh




-----------------------------------------------------------------------

**Outstanding Questions for you both:** 
1) I'm not seeing where the CTA is for linking from the legacy page to the modernized content, if you all could call that out I'd appreciate it :)
2) I need more information on if there's a need to incorporate vads-facility-hub-cta-label into the tracking paradigm at all.

**Comment by nedierecel** [comment]
@jefflbrauer 

1. *Staging Banner for Legacy-->Modernized Pittsburgh Pilot* - Is there a location on staging where we can see this?
2. `vads-facility-hub-cta-label`: These are the links within the Manage Healthcare section. Should we simply call these "Manage Healthcare links"? 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/42021fe2-s567a-487f-9b9d-a0b8be141399)

**Comment by jefflbrauer** [comment]
@jonwehausen Thank you for your quick and thorough review! For your first question - that banner isn't live just yet on the legacy site, but it will function just like the one on the modernized site, just will go in the opposite direction and be served by the Teamsite CMS. 

@andrewlewandowski you may need to answer #2 

I think we also need a follow up call as I don't see where you have documented the various dataLayer pushes noted above. I will want to bring my FE engineer onto the call as well to ensure requirements are clear.

**Comment by jonwehausen** [comment]
**Proposed DL requirements:** 
_These are components that will require developer intervention, we can discuss tomorrow during our call._

**Primary CTA Buttons:** 

- Example: Make an appointment, Register for care, pharmacy

```javascript
dataLayer.push({'event': 'nav-primary-button-click'});
```

**Jumplinks**

- Example: Top of this [page](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)

```javascript
dataLayer.push({'event': 'nav-jumplink-click'});
```
**Alert Box Link Click**

- Example: Banner at the top to legacy site

```javascript
dataLayer.push({'event': 'nav-alert-link-click'});
```
**Hub CTAs**

- Example: 'Manage your health online' section links

```javascript
dataLayer.push({'event': 'nav-hub-link-click'});
```

**Featured Content Link Click**

- Example: 'In the spotlight box'

```javascript
dataLayer.push({'event': 'nav-featured-content-link-click'});
```
**'See All' - Secondary Buttons**

- Example: See all locations, stories, events buttons

```javascript
dataLayer.push({'event': 'nav-secondary-button-click});
```

**Comment by nedierecel** [comment]
@jonwehausen Notes from our Tuesday call. I'll chat with you via Slack on naming convention. 

- For the Primary CTA buttons, we'll treat these differently since they are common and heavily requested patient tasks.

**Comment by jonwehausen** [comment]
Team: 

Following our call from Tuesday, I've made the following adjustments/updates: 

1. Changed the convention for the primary navigation button clicks to be 
```
dataLayer.push({'event': 'cta-primary-button-click'});
```
2. I setup a stand alone event for CTA button clicks and put in an additional page path check that will output 'Patient Tasks' with the click text for CTAs contained on the relevant pages
3. I made a similar adjustment for the hub CTAs, changing the naming convention to: 

```
dataLayer.push({'event': 'cta-hub-link-click'});
```
4. I setup a stand alone event for Hub CTA button clicks as well, this will output 'Hub CTA - {{Click Text}}' in the event action. 
5. I've updated the comment above containing the dataLayer pushes to reflect these updates, they can be implemented as listed above. 
6. At this time @ethanteague, don't worry about implementing globally, we can stick with the pages relevant here. 

CC: @jefflbrauer @nedierecel

**Comment by jefflbrauer** [comment]
Cool! I like "cta" as the preface. Is Andy cool with that?

:)
Jeff

**Comment by andrewlewandowski** [comment]
@jonwehausen - Thanks for connecting this afternoon! Everything in this ticket looks good. Here is the one item that needs to be added.

**1. Tracking click events of detail page links inside these 10 health service accordions:**

https://www.va.gov/pittsburgh-health-care/pharmacy/
https://www.va.gov/pittsburgh-health-care/mental-health-care/
https://www.va.gov/pittsburgh-health-care/suicide-prevention/
https://www.va.gov/pittsburgh-health-care/caregiver-support/
https://www.va.gov/pittsburgh-health-care/homeless-veteran-care/
https://www.va.gov/pittsburgh-health-care/lgbt-veteran-care/
https://www.va.gov/pittsburgh-health-care/minority-veteran-care/
https://www.va.gov/pittsburgh-health-care/patient-advocates/
https://www.va.gov/pittsburgh-health-care/returning-service-member-care/
https://www.va.gov/pittsburgh-health-care/women-veteran-care/

These links are located at the bottom of the "Care we provide at VA Pittsburgh" content block. This block shows up on the Health Services page, and on the Facility pages (x7 for Pittsburgh).

**Comment by jonwehausen** [comment]
@andrewlewandowski Thanks for your time as well. 

@ethanteague For links that are embedded within an expanded accordion (found [HERE](https://www.va.gov/pittsburgh-health-care/health-services/)), such as the one in the screenshot below, we would like to track these as: 

![image](https://user-images.githubusercontent.com/48527022/65913846-8b205280-e39e-11e9-9c61-9f827a979583.png)

```
dataLayer.push({'event': 'nav-accordion-embedded-link-click});
```

I've added this to the full list above. 

Also @andrewlewandowski I'll make sure the words "Health Tools" are included with the hub link clicks... @ethanteague this doesn't mean everything different for the DL push. 

CC: @nedierecel

**Comment by andrewlewandowski** [comment]
Yes! So for the accordions on the Health Services page (like the screenshot above), we need to track the location links (what the red arrow points to) and also the 10 links for the health program pages (listed above).

**Comment by andrewlewandowski** [comment]
The URL for medical records was updated (noted above), and we need to update the URL for the Heinz campus (also noted above).

**Comment by jonwehausen** [comment]
@ethanteague @ncksllvn 

I noticed there is an issue with the 

```javascript
dataLayer.push({'event': 'nav-jumplink-click'});

```
request...this dataLayer push seems to be happening on page load rather than on jumplink click. 

I've paused the tag I have setup to track jumplink usage not fire to not skew data until corrected in staging/production.

Thanks, 
Jon Wehausen

**Comment by ncksllvn** [comment]
Thanks @jonwehausen! @ethanteague addressed this issue in PR, https://github.com/department-of-veterans-affairs/vets-website/pull/10830

**Comment by jonwehausen** [comment]
As nick called out [here](https://github.com/department-of-veterans-affairs/vets-website/pull/10818), there's a correction that needs to be made to the jumplink dataLayer push to only occur on jumplink click. 

While we wait for the correction to the jumplink dataLayer push, @nedierecel and I have put a hotfix in GTM in place to eliminate the risk for inflated jump link event fires. 

We put in an exception specifically for the custom event of nav-jumplink-click, which means the jumplink interaction will not be tracked until the code adjustment is made.

**Comment by jonwehausen** [comment]
For transparency, here is a list of the changes currently contained within the GTM container from this story and a couple 1-off improvements: 

- Temporary hotfix for nav-jumplink-click PROD event - **TO REMOVE LATER**. 
- Navigation event additions as outlined in https://github.com/department-of-veterans-affairs/va.gov-team/issues/1846
- CTA-specific tracking needs 
- Additional info tracking adjustment to account for additional-info-expander-label when available...[see notes here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1541)
- Turned on debug mode variable to serve as an input to LUT - Debug - Parent Lookup.

**Comment by jefflbrauer** [comment]
@jonwehausen Any other work required by @ethanteague to fulfill the additional requirements will need to be done next week. He's out at this point. 

Can we run through some tests with what we have tomorrow?

**Comment by jonwehausen** [comment]
Hi Team,

I've done some initial QA in staging and it looks like we are in a good spot with most of what was requested. 

### :exclamation: The remaining tracking needs / adjustments include:
- Change jumplink clicks to only fire when clicked [_currently firing on page load_]
- Missing dataLayer push for clicks on 'In the Spotlight' links on landing page [_this is working on health services page_]
![image](https://user-images.githubusercontent.com/48527022/66011672-0ca4dd00-e492-11e9-8cab-03dfd120b686.png)
   - I would like to request a small adjustment to the featured content dataLayer push to include an additional variable, to make the complete dataLayer push be: 
    ```javascript
   dataLayer.push({
    'event':  'nav-featured-content-link-click',
    'featured-content-header': 'In the Spotlight'
   });
    ```
 - For the featured content blocks contained on the Health Services page, we'll want to make the complete dataLayer push be: 
 ```javascript
   dataLayer.push({
    'event':  'nav-featured-content-link-click',
    'featured-content-header': 'Cardiology at VA Pittsburgh' //CHANGE WITH EACH SUBHEADING
   });
```
![image](https://user-images.githubusercontent.com/48527022/66012303-a077a880-e494-11e9-8268-d91053b17d6a.png)



- Missing dataLayer push for clicks on embedded links within accordion expands
- Reminder there currently isn't a banner on the legacy site to confirm tracking persists there
-----------------------
### :white_check_mark: See below for screenshots on QA tracking accurately: 

**Hub Link Click - Notice "Health Tools" in the Event Action**
![cta-hub-link-click](https://user-images.githubusercontent.com/48527022/66011797-7e7d2680-e492-11e9-95ca-764e3def27b8.png)

**Primary Button Click - Notice "Patient Tasks" in the Event Action**
![cta-primary-button-click](https://user-images.githubusercontent.com/48527022/66011814-8b017f00-e492-11e9-81c7-293923a0187f.png)

**Banner click**
![nav-alert-link-click](https://user-images.githubusercontent.com/48527022/66011835-a10f3f80-e492-11e9-81ad-6aecc7728237.png)

**Seconday 'See All' Buttons
![nav-secondary-button-click](https://user-images.githubusercontent.com/48527022/66011909-ee8bac80-e492-11e9-8f89-04ecca3397dd.png)
**

**Custom Dimensions - City & Location**
- 51: Populates with the city
- 52: Populates with the type of location...either Campus or Clinic
![location-and-type-custom-dimensions](https://user-images.githubusercontent.com/48527022/66012009-5cd06f00-e493-11e9-87b4-7ad478df3663.png)

**Comment by nedierecel** [comment]
@jonwehausen Scroll depth has been added to the Scroll Depth tag. The new trigger is built on `Page Path` contains /pittsburgh-health-care and will fire at 50, 75, and 100%. (I avoided 25% since this is typically the viewport on page load) 

For future-proofing as new facilities are rolled out, we can reformat the trigger conditions to be more inclusive of all `location-health-care` URLs.

Please proof that:
- [ ] Use of Jumplinks should trigger the event+scroll depth
- [ ] Scrolling does not trigger any percentages beyond the 50, 75, and 100%

**Comment by jefflbrauer** [comment]
Hi @nedierecel Thank you so much for doing the thorough QA! The remaining adjustments we'll be able to make on Monday. @ethanteague is OOO the remainder of this week unfortunately, but I don't anticipate any of that taking him longer than Monday to complete.  @andrewlewandowski I'll adjust our timeline accordingly to plan for Monday to resolve the issues, Tuesday to test and QA certify, and then Wednesday to go to production with the 3pm build.

**Comment by ethanteague** [comment]
Hey all. I've made the changes requested, here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1846#issuecomment-537301447 in this pr: https://github.com/department-of-veterans-affairs/vets-website/pull/10860/

cc: @jefflbrauer @jonwehausen

**Comment by jonwehausen** [comment]
Hi Ethan, 

Thanks for the update. 

:exclamation: **Here are the gaps I have identified in phase 2 of QA:** 
- The `nav-jumplink-click` event populating on every page in staging
- 'In the Spotlight' clicks on the landing page
- Additional dataLayer variable for `nav-featured-content-link-click`
- Link clicks embedded within accordion 

Let me know if you have any questions on the above. 

:white_check_mark:   **Validated**
- `nav-featured-content-link-click` is being pushed with featured content on health-services page, would like to request additional variable above

**Comment by jefflbrauer** [comment]
@jonwehausen Could you please re-validate the 4 bullets now?

Thank you,
Jeff

**Comment by jonwehausen** [comment]
Hi Team, 

CC: @jefflbrauer @ethanteague @nedierecel @joanneesteban 

:exclamation: **Here are the remaining gaps in latest iteration of QA:**
- The nav-jumplink-click is still firing prematurely, instead of firing only on jumplink click, it's actually pushing multiple times on any page load...Below is a screenshot of our testing 
![image](https://user-images.githubusercontent.com/48527022/66570250-3c5f7f00-eb3b-11e9-9fe0-18f85a24d1ba.png)



-  We also still need the embedded accordion links captured with this dataLayer code: 
```javascript
dataLayer.push({'event': 'nav-accordion-embedded-link-click'});
```
--------------------------
:white_check_mark:   **Validated**
- `nav-featured-content-link-click` is now including the correct 'featured-content-header' additional variable, thanks.

**Comment by ethanteague** [comment]
Latest pr to address the above: https://github.com/department-of-veterans-affairs/vets-website/pull/10879 cc @jefflbrauer

**Comment by jonwehausen** [comment]
Hi Team, 
cc: @ethanteague @ncksllvn @jefflbrauer @andrewlewandowski @nedierecel @joanneesteban 

Thanks so much for working thru the changes! 

The accordion embedded links are working great 👍 

**I did notice however the jumplink `nav-jumplink-click` push is still not firing on click..._good news is it is no longer firing on page load_.** 

I was able to put in a temporary fix that gives tracking to these interactions in case we're not able to get the click push operating prior to launch but we still need this corrected. 

Let me know if you have anymore questions - Thanks!

**Comment by ethanteague** [comment]
Awesome, @jonwehausen ! Can you give me the url(s) and the subordinate links you are testing that aren’t firing? I wanna make sure I’m plugging in my trackers in the correct place. Thanks!

**Comment by nedierecel** [comment]
@ethanteague - @jonwehausen is OOO today, but I believe an example of the jumplinks is on https://staging.va.gov/pittsburgh-health-care/health-services/#mental-health-care

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/d233467f-19fb-414d-ae16-0df210a9872c)

I see Jon's temp fix here on the page.

**For Analytics-Insights Team to address:**
@jonwehausen Once the ^^ is resolved, how should we address the extra PV that is fired on the historyChanges? I believe we discussed an exception on these pages (vs. a virtual PV) but did not add to the AC.

_See screenshot of the extra PV that was triggered when I clicked on a jumplink:_
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/854f3678-d34b-4b95-a6bc-202de9c8c808)

**Comment by ethanteague** [comment]
Okay. I _think_ this pr should resolve: https://github.com/department-of-veterans-affairs/vets-website/pull/10894 cc: @jefflbrauer @nedierecel

**Comment by jonwehausen** [comment]
@ethanteague Thanks for all of your work in correct this, I've validated the jumplinks are now firing on click. 

@nedierecel I am ready for your final QA of this container: [Pittsburgh Health](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/672), the latest changes include: 

- T[ag for header link clicks ](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/672/tags/350) to location pages - built generic for H3 components
- Put in History Change exception for jumplinks on health care pages, used in [Va Basic Page Tracker](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/672/tags/1)
- Made small adjustment to the scroll tracking trigger to use any [*-health-care](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/672/triggers/682) page to future-proof for when other locations pages are launched

**Comment by jonwehausen** [comment]
@nedierecel @ethanteague @andrewlewandowski @jefflbrauer @joanneesteban 

Moving this to Closed, as we have completed QA and published to live container. New data will begin flowing immediately to the production property. 

Feel free to use this **[custom report template](https://analytics.google.com/analytics/web/template?uid=mNZF5wYgS_mukgRIrhd02A)** to monitor events throughout the prototype launch. 

Thanks team,
Jon
