### ISSUE TITLE
[VAMC] Create Devshop Environments for each System in VISN-16 for revew and testing [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18466]
## Story
As a VAMC team member, I need a development environment, so I can test and validate all the URL pages from Production.

## TASKS
Create new test environments, rebuild, publish all nodes, and release content for the following VISN-16 Systems:

- [x] VA Alexandria health care
- [x] VA Central Arkansas health care
- [x] VA Fayetteville Arkansas health care
- [x] VA Gulf Coast health care
- [x] VA Houston health care
- [x] VA Jackson health care
- [x] VA Shreveport health care
- [x] VA Southeast Louisiana health care

## Acceptance Criteria:
- [ ] All pages are released and accessible
- [ ] Left Navigation information (Visible, Actionable, working links) is provided to Facilities team
- [ ] Site availability is provided to Analytics team.
