### ISSUE TITLE
[Dual-State-Prep] Prepare Lebanon Health Care VAMC for Dual State [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18462]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Lebanon Devshop Instance](http://lebanonhealthcare.web.demo.ci.cms.va.gov/lebanon-health-care/)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Validate that each page:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system

**Comment by ltrombley** [comment]
Updated from 3 points to 5 points due to complexity and number of of issues.
