### ISSUE TITLE
[Dual-State] Clean up all broken llinks and code errors prior to Dual State Launch

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18463]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Sites
[Erie health care system legacy site](https://www.erie.va.gov/)
[Lebanon health care legacy site](https://www.lebanon.va.gov/)
[Google Drive locations for VISN-4](https://drive.google.com/drive/folders/1Juw7qXdDtzXHm-yPPwaJNUaYZkCFD9B-)

## TASKS
See below associated tasks:

## Acceptance Criteria
- [ ] All pages in have been tested for broken links tested
- [ ] All additional pages that are NOT duplicates have been added to list and have been checked
- [ ] Updates suggested from Staging have been input into system or reported back why they have not been input
