### ISSUE TITLE
[Design] MyVA Visual design /  Get feedback from design team

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18469]
## Background
Now that we have got wireframes for MyVA, we can start on the visual design.

## Tasks
- [x] Settle on MyVA visual design 
- [x] Begin visual design
- [x] Get feedback from design team
- [x] Review with Matt and Samara 

If time, begin working on the different states

**Comment by tressaellen** [comment]
Hello @Samara-Strauss - here's the next round of visuals for MyVA. We'd love your thoughts. (cc/ @callen)

I added back in a heading for each of the sections, but updated it to be the status update to reduce redundancy. For the card design I started with the original cards in the style guide with a few small changes (white backgrounds vs grey). There are also some new cards, though they are based off of the style guide. The new cards are the cards shown in the first image in messages, appointments and prescriptions - I still tried to keep them similar to existing cards though. 

The difference between the first and second desktop images is the layout.  The first one has a 2 and 3 column layout, the second one just sticks to the 2 column layout and also strictly uses cards from the style guide (aka no updates to the cards in messages, appointments, and prescriptions sections). I personally prefer the first one - I think it's a better use of space and easier to scan and read.

![MyVA Desktop 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/63584314-642b-4b03-ae2a-a659b89468bb)

![MyVA Desktop 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/77aa3655-4f1c-4118-a12d-15263c202383)

![MyVA Mobile.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/7b5b34ba-9680-494a-8a4f-24f1e9ce4817)

**Comment by Samara-Strauss** [comment]
We can talk more about this in our meeting later, but my preliminary feedback and questions are:

- Why are we showing two claims now? What is the UX rationale for this?
- Did you ask Erik/Sandra if making the claims/appointments/prescriptions/messages headings dynamic (ie. will be personalized to each person based on how many  claims/appointments/prescriptions/messages they have) will be annoying to code? I think it's possible because I guess it's just like making any other copy dynamic, but I also know it would be simpler if the headings were standard and not dynamic.
- And on that note, I personally thought the iteration we looked at yesterday with the standard headings (eg. Most recent claim update/Latest appointment/Latest message/etc) was much cleaner and clearer. As I understand it, the feedback around showing the total number of claims/appointments/etc was that that information should be more closely associated with the CTAs to View All, and I think that's valid feedback and clarifies the hierarchy a bit more. I personally would recommend changing the headings per Kevin/Ryan's guidance and more closely associating the total number of claims/appointments/etc with the View All CTAs. However, you do not have to do it in the way they suggested (ie. putting a number in the button itself).
- I know this does't seem important, but it's really confusing to look at the Applying for benefits section and to see three blocks for the health care application — two in the "in progress" section, and one in the "You might be interested in section." While I know how this section is supposed to work, other people looking at your design — including other designers or our FE devs — don't know how this will work, and seeing the same information multiple time looks like a mistake. Please be more careful with dummy data and realize that it's always an opportunity to communicate actual functionality.

**Comment by Samara-Strauss** [comment]
And quite frankly, I'm not the right person to answer the question about columns, so I'll let Kevin and Ryan give more guidance on the proper way to handle columns from a visual design & build perspective.

**Comment by tressaellen** [comment]
@Samara-Strauss @callen2563 @KevinMHoffmanUSDS here's some iterations based on our discussion earlier. I'll keep noodling tomorrow but I wanted to give an update. Versions 1&2 are both using those hairlines from the pittsburgh site. In V2 I swapped the order of the stats&CTA and the update, just to try it. Anyway, as always, I'd love any thoughts.

![My VA 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f9e55c77-74a4-4fe6-ab9f-03bc3801ee0b)

![My VA 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/a98de2fa-118f-4ffa-a493-b346caa54228)

![My VA 3.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/7ed520d6-6339-4bb3-bdfa-c2cb7c25e8f9)

**Comment by Samara-Strauss** [comment]
These have come a long way and are looking really good. 

- For V1: Re: the hairline: I would need to rely on Kevin as to whether this has been employed correctly. I understand how you've used it to break up latest updates and the "You have x [new messages]" message and CTA, but I think (maybe?) that it should go below the CTA to indicate the end of the column. But I genuinely don't know, and that would definitely be a question for Ryan or Kevin or someone else who is familiar with how that element should work.
- For V2: I think there's some merit to putting the stats/CTA above the update, but with the way it's shown in V2, I think that'll feel a bit weird on mobile for two reasons: First, because there's no main heading for each health care section — "You have x [new messages]" sort of serves as the heading, but it also isn't really a heading. Second, with everything stacked on mobile, I think all the line breaks will make it unclear which information is associated with each other.

To solve for some of this, I mocked up an idea that may or may not worth considering at all. I broke the health care section into 2 columns instead of 3, added a notification state (yes, this would be a new element), but otherwise, I don't think anything is new. This would allow us to have the total/CTA up top, but also have a proper heading that anchors each section. FYI, Idk if I broke the design system in a million ways with how I used the hairlines, so if this idea has any merit, we should make sure that I employed things the right way:

![My VA idea](https://user-images.githubusercontent.com/34068740/104743585-db4d3080-5719-11eb-9dfa-75a40f60f1a7.png)

- V3: I still think the card design in V3 for the health care section provides the most clear hierarchy that would work well on both desktop and mobile (not as many confusing line breaks on mobile). BUT, the cards would be a new element, so let's only take this approach if we really can't figure out how to get the existing hairline/column pattern to work.

We can discuss later today if you have time. Great work!

**Comment by Samara-Strauss** [comment]
BTW, for reference — here is the [Pittsburgh VA Medical Center website](https://www.va.gov/pittsburgh-health-care/) that shows how columns are being used (and it looks like icons, too, if that is something we feel we could or should meaningfully employ).

**Comment by tressaellen** [comment]
Hello @KevinMHoffmanUSDS and @rtwell (cc/ @callen2563 and @Samara-Strauss) -

This is where we landed after sifting through all the feedback and working through some options.  We'd love any feedback that you have and we also have a few questions about this design.

- What is the correct way to use the hairline (as shown in the pittsburgh site)? Does all the information need to be encompassed by the line? Or can it be used as more of a delineation of content and columns?
- In this version we used the secondary CTA button for any interaction that takes you to an overview page, and the primary for when it takes you to a specific thing within a page. Let us know if this incorrect or if you have thoughts about this.
- We've used the blue box to callout the 'stats' (i.e. You have 2 new messages).  We are definitely open to ideas about ways to do this/changing the color, but that information is important and should not be missed.

We're happy to meet next week or can receive any feedback via GH if that's better for you. Thank you!

![My VA 1 Desktop.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/d4b489b3-46e8-4c5f-843b-d4eefb722385)

**Comment by Samara-Strauss** [comment]
> We've used the blue box to callout the 'stats' (i.e. You have 2 new messages). We are definitely open to ideas about ways to do this/changing the color, but that information is important and should not be missed.

I just want to clarify this — they added the blue callout BECAUSE it felt like this information would be easily missed without it. The question around this is two-fold — do you agree the callout is warranted to aid with scannability and findability of this information? And, if you do, is a blue the right color for that background? From our call yesterday, it sounds like the blue background is supposed to be employed in a very specific way, and we were hoping one of you could provide guidance on this.

**Comment by KevinMHoffmanUSDS** [comment]
Good morning! Hope everyone had a great weekend. 

This isn't really the intended use of the blue callout, but it's not a stretch to use it this way, either. This team is designing things that don't exist in this system, so I think using the blue this way is subtle enough that it doesn't add too much noise to the page but does the job of both calling attention to itself as something more impt. to the user and relating clearly to the action buttons that follow. 

My only piece of feedback would be that in the third section, the "Apply for education benefits (2)" button is calling too much attention to itself, and it is not as important to the user as completing the two applications above (1). I would suggest an alternative treatment to de-emphasize that button - ghost button without a chevron or a link would both be worth exploring. 

<img width="1164" alt="Screen Shot 2021-01-19 at 10 16 23 AM" src="https://user-images.githubusercontent.com/50150810/105054773-5d05cc80-5a40-11eb-89f9-227697634e36.png">

I realize that in an empty state (e.g. the user would have no incomplete applications) this object would rise in importance, and in that case, the blue button would make sense. To put it another way, based on this design, here the front ends design rules for buttons you could follow:

1. The first action a user can take users a solid blue button. 
2. If the user has secondary actions, use a ghost button without a chevron (or a link, or whatever you decide). 
3. If the user is just linking to an external application, use a ghost button with a chevron. 

In that case, the button would change based on how complex the page gets, which I see as a good thing, as it disambiguates more complex/full versions of this page.

**Comment by rtwell** [comment]
if it helps, NN group just posted a [relevant article around hierarchy in visual design](https://www.nngroup.com/articles/visual-hierarchy-ux-definition/), and i think a couple principles they discuss apply to this work, particularly the squint test. I do not intend this to be prescriptive, but as a reference.

**Comment by Samara-Strauss** [comment]
Talking with @KevinMHoffmanUSDS, he also had questions about:

- What is the reason beyond appearance that we decided to use white cards instead of gray cards (existing pattern) for the claims and applications in progress blocks?
- Also, regardless of color, what is the reason those blocks have rounded corners (also would be different from the existing card pattern)?

**Comment by tressaellen** [comment]
Hello @KevinMHoffmanUSDS @rtwell @Samara-Strauss (cc @callen2563)

Thank you for the feedback!

> What is the reason beyond appearance that we decided to use white cards instead of gray cards (existing pattern) for the claims and applications in progress blocks?

The idea behind the white boxes were to differentiate this page from the content or tool pages, but I'm not sure that changing the color of the boxes achieves that really. 

Also, from a hierarchy standpoint - the cards were competing with the related links box, but we tried a different treatment of the related links box (from the design system) and that seems to have worked. We'd love your thoughts on this treatment or if you have another solution that might work.

> Also, regardless of color, what is the reason those blocks have rounded corners (also would be different from the existing card pattern)?

The rounded corners were an attempt to help correlate the MyVA page to the profile page since they will be using very similar nametag headers.  I'm not sure that is enough to constitute a change to the design system - in these mocks we removed all the rounded corners.

Here are all the updates:

![My VA desktop 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/0e37b28a-ac8a-49c5-9309-b4a2f92990be)


> I realize that in an empty state (e.g. the user would have no incomplete applications) this object would rise in importance, and in that case, the blue button would make sense.

@KevinMHoffmanUSDS mentioned that in the empty state a blue button might work for those links - I tried that out but I think we should still keep it as the ghost button for consistency. There's a use case where a user could still be in that page for the first time, but also have applications in progress, in which case those applications would have the blue button. (shown below). I think it would just be better to 

![My VA FTUX.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/596859ba-2246-4d82-9636-190342e6b858)

![My VA FTUX 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/88367026-eb74-4e35-a02f-3d3e6c65feae)

One more thought (this is not important to this page, but I want to record it while I'm thinking of it) - we need to spend a little time finessing the color of the nametag header. If we use the same color that is used in profile but have it bump up right agains the main header then the colors don't have enough contrast. *But* I do think the headers should match, which means tweaking the header in the profile as well.

**Comment by Samara-Strauss** [comment]
Overall, I think this version works really well. The overall hierarchy is simpler (fewer headings); we leverage the design system almost exclusively, but we're not bound to ONLY gray boxes and a single-column design; and the additions to the design system (is it just the blue label/status?) are well-rationaled from a usability and user need perspective. This is great work.

A couple things:

- @KevinMHoffmanUSDS or @rtwell can give a better perspective on this, but I think there is room for rounded corners on the blue "You have [X upcoming appointments]" label **if** you feel like they have a purpose (eg. the rounded corners will help call out this information and differentiate it from other blocks). But that is totally up to you, and if you don't think it matters, don't add them back. 

> One more thought (this is not important to this page, but I want to record it while I'm thinking of it) - we need to spend a little time finessing the color of the nametag header. If we use the same color that is used in profile but have it bump up right agains the main header then the colors don't have enough contrast. But I do think the headers should match, which means tweaking the header in the profile as well.

Idk if this solves the problem, but I noticed this colored stripe between the global notification and the main navigation. I'm not sure what the rules are on this stripe and why this color is different in different places, but it could potentially be an alternative to changing the nametag color. HOWEVER, if the stripe doesn't work OR if you determine that you want to finesse the nametag color no matter what, please feel free to do so. I'm just pointing this out in case this is helpful, and this is NOT a mandatory solution.

<img width="1280" alt="Screen Shot 2021-01-19 at 5 01 33 PM" src="https://user-images.githubusercontent.com/34068740/105098796-9eb26980-5a78-11eb-87e5-d79389624176.png">

<img width="1280" alt="Screen Shot 2021-01-19 at 5 01 52 PM" src="https://user-images.githubusercontent.com/34068740/105098798-9f4b0000-5a78-11eb-973d-6862a9fe2eb2.png">

**Comment by tressaellen** [comment]
@callen2563 @Samara-Strauss @rtwell @KevinMHoffmanUSDS   Here's where we landed with the nametag.  The blue is the primary blue (0071BB) in the design system. We tried to minimize the number of stripes because there's the possibility that a banner could also be on these pages which would just make the page a block of stripes.

I updated one of the profile screens as well just to see... I think it works.  I also added a link to the MyVA page from the profile page as well, but we can discuss if we think that's valuable or not.  

![My VA Desktop blue.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/26b14e24-93a2-4811-ad05-fd727952a98f)

![Screen Shot 2021-01-21 at 10.13.07 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/31401ea9-cd6c-449f-87dc-26759e7bc2c2)

**Comment by Samara-Strauss** [comment]
The name tag looks good to me, though I'll defer to @KevinMHoffmanUSDS and @rtwell because I'm not a color expert.

Re: the profile: I think the proposed updates — moving where the breadcrumbs are and adding a My VA button — are worth considering, but let's not make any immediate changes to the profile besides the name tag element (should be consistent across pages). Can you add a ticket for us to consider those changes later?

**Comment by tressaellen** [comment]
Yep, I can do that!

**Comment by tressaellen** [comment]
@mshea0606 @Samara-Strauss are we good to close this ticket?

**Comment by mshea0606** [comment]
Closed
