### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Central Arkansas health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18467]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-16 Internal Review Folder](https://drive.google.com/drive/folders/19WE1dLBjZkeIMW8ACPbOZ-BWzaoOTopq)
[Review template for review](https://drive.google.com/drive/folders/18CfKY3QZhR4AoiByBYKqAgKfFewEb9RV)

## Tasks
Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 598	John L. McClellan Memorial Veterans' Hospital
- [x] 598A0	Eugene J. Towbin Healthcare Center
- [x] 598GA	Mountain Home VA Clinic
- [x] 598GB	El Dorado VA Clinic
- [x] 598GC	Hot Springs VA Clinic
- [x] 598GD	Mena VA Clinic
- [x] 598GE	Pine Bluff VA Clinic
- [x] 598GF	Searcy VA Clinic
- [x] 598GG	Conway VA Clinic
- [x] 598GH	Russellville VA Clinic

* Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [x] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.

**Comment by EdwardBoehme05** [comment]
Blocked due to cannot be accessed in Devshop.
