### ISSUE TITLE
S+D Team DOMO dashboard preparation

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#18476]
## Description

As a product team we need a dashboard to display our top metrics and KPIs as they relate to our products and bets. Analytics team will establish dashboard and the request has been made in GH #16778. This issue is for the search and discovery team to collect all the information they need to implement. 

## Background/Context/Resources

_TBD: Applicable information to be added _

## Technical notes

_TBD: Tech Notes to be added (if applicable) _

---

## Tasks

- [x] Create a spreadsheet that outlines the various metrics that are needed on our dashboard

- [x] Identify potential display preferences for each metrics identified including an example of how we may see or read the output

- [x] Meet with the analytics team to review the spreadsheet,  discuss details and answer questions that may come up

- [x] This issue is defining v1 dashboard requirements but any v2 considerations or iterates may need to be captured in a seperate issue. 

## Definition of Done

- [x] Analytics team has what they need to establish our initial DOMO dashboard. They have a clear understanding of what data we want on v1 of the dashboard

**Comment by denisecoveyduc** [comment]
KPIs have been drafted and added to analytics dashboard request. Next steps include meeting with analytics team to address any related questions and get a better understanding of their timeline for implementation.
