### ISSUE TITLE
Search.gov Exploration

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#18475]
## Description

As a product team who is getting closer to defining how we want to refine the search experience for veterans and their family members we need to gain a better understanding of search.gov. How it is implemented and what the capabilities and customization feature of it are. 

## Background/Context/Resources
[Search.gov](https://search.gov/)
[Managing Search Configuration ](https://search.gov/manual/index.html)

---

## Tasks

- [x] Identify different components of search.gov for review and where any existing information can be found. (Listed below in resources section  with relevant links to resources or information)
- [x] Meet with the search.gov team to discuss outstanding questions and requirements (Listed Below)
- [x] Capture any risks or concerns centered around the use of search.gov for the expansion of search on va.gov. This will help base our perspective on exploring other search services and determine if that is something that is actually needed.  

## Components being explored:

- Spell Check 
- Results 
- Collections

## Search.gov Discussion Questions:
**Priority Discussion Items (for meeting)**

1. **Type Ahead**
   - Why does the "exact match" appear at the beginning of the suggestions? Could we alter that?
   - Format for canned suggestions

2. **Click Tracking** 
   -  Best Bets URL: Can we create a unique url for best bets so that we can better track them in the click tracking data? _(JH Note: Moving this one here since it combines three things: Click Tracking, Best Bets and Type Ahead)_

3. **Content Metadata**
   - Can we change the metadata tags that are associated with content?
   - Potential bug: Is Search.gov not reading metadata correctly? Metadata descriptions are not appearing on search results.
   - Is there a limit to the # of metadata fields they can handle?
   - What format would you need data in?

4. **New API Features** _(JH Note: Added this as a fourth topic for the call as these are near-term priorities for us)_

- **_Spell Check API:_** Has this been implemented for va.gov to address spelling errors and pluralization etc.?

- **_Collections:_** Late last year it was estimated to be nearing completion. What is the current status?
Filtering the different categories of information using collections

**Secondary Questions (will be emailed):** 

- **_Validate Analytics Assumption:_** Reviewing analytics when we type in the search term, does that further break down subsequent terms related to that query? (i.e if forms is a top search term and we search for forms we can see the top search terms as they relate to forms)

- **_Search.gov Documentation:_** Where is the source of truth on what search.gov can offer? Search.gov or GSA?

- **_Search Result Page Information:_** How customizable is the search results page? How is the results description information selected? Could we remove the url? Can we manipulate the text: Search description/Truncated breadcrumb/header information? Can we take out header/footer content on search results?

- **_Results Relevancy:_** How is relevance determined? Can we change what ends up as a top result?
- **_Similar Search Terms_**“Users also searched for this”

- **_Other VA.gov Search Engines:_** Ability to pull in results from other search features? (Ex: Find a form, find a facility, MyHealthyvet)

- **_Ignore Stop Words:_** Can it be programmed to ignore prepositions, articles, conjunctions that appear in most documents and are unlikely to be distinctive for any one of them?

## Definition of Done

- [ ] Core components of search.gov have been explored and the Search & Discovery team has a good handle on the overall functionality and capabilities. This includes our ability to use search.gov to refine search going forward for veterans.

**Comment by denisecoveyduc** [comment]
Search & Discovery team conducted a debrief meeting after our session with search.gov and have identified some follow on discussion topics that will occur over email to gain further clarity. Topics are outlined in #19011 which will be discussed our upcoming sprint 40.
