### ISSUE TITLE
Work with Perigean and Lauren to schedule User Research Sessions

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#18481]
## Description

_TBD: Outline what this issue is about _

## Background/Context/Resources

_TBD: Applicable information to be added _

## Technical notes

_TBD: Tech Notes to be added (if applicable) _

---

## Tasks

- [x]  Send S+D Team the research plan link in Slack for final review
 

- [x] Practice Usability Study Conversation with Veteran on Staff (Brian - Jan 14)
- [x]  Submit Research Plan to Lauren (est. Jan 15- subject to change)
- [x]  Recruit for research sessions (Perigean) [will take ~ 1 week (caveat that the req are more important than timing- estimated Jan 22- Jan 27 (subject to change)]
- [x]  Schedule research sessions (Perigean) - [Timeline for scheduling: within 1-2 weeks; A bit unknown (estimate) - Jan 25-Feb 5 subject to change)

## Definition of Done

- [x] Sessions are scheduled
