### ISSUE TITLE
Update Content for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18489]
## Background
The content received by the stakeholders has been reviewed and needs some editing before it can presented as an option to platform for inclusion into the feature. 

## Considerations
- Current [mockup](https://xd.adobe.com/view/aaf3f28b-b763-4c16-ba02-d1d47e20328e-ffa0/)
- Latest mockups: Mockups: https://xd.adobe.com/view/76c8e03c-ff8e-498b-ada5-0e2c08a8d8bd-239b/
- Orientation is extremely long: tighten it up as best we can
- Language, including subway maps, will require revision for clarity, VA styling
- Process steps are redundant with summary information: ask if we can provide just a summary at the end 
- Module is out of context
- Orientation info is relatively inaccessible as reference
- Module is a barrier to completing the form

## Tasks
- [x] Revise content
- [x] Get a review from Content (Beth Potts?)
- [x] Generate a list of recommendations for Sabrina

## Acceptance Criteria
- [x] Mockups are updated and shared with Team
- [x] Beth has been contacted

**Comment by jason-gcio** [comment]
Come back to this and see if there are any other deliverables that we should include ahead of working with CH31 stakeholders

**Comment by sporeboy** [comment]
Recommendations:
1. Orientation is extremely long:
    - Consolidate content into as few ‘slides’ as possible, potentially “doubling-up” sections
2. Language will require revision for clarity: 
    - Revise copy to align with plain-language mandate
    - Align with VA.gov style guide
3. Process steps are redundant with summary information
    - Drop process slides in favor of summary/process map
4. Module is out of context, and orientation info is inaccessible as reference for process:
    - Put the orientation module on VR&E content pages; put links on form intro and confirmation page
5. Module is a barrier to completing the form:
    - Present a bypass link to users; keep visible throughout orientation

**Comment by sporeboy** [comment]
Worked with Beth P. on text changes. Content revisions in place here: https://xd.adobe.com/view/dd487b28-382f-4f45-8116-c9259b88cfb3-881b/

Final review pending.

**Comment by sporeboy** [comment]
Received and implemented additional revisions. Current revs in place. Will share with dev when all revs are reviewed and approved.

**Comment by jason-gcio** [comment]
@sporeboy Hey Jim!
I think we are ok to consider this complete, do you agree?

**Comment by jason-gcio** [comment]
Mockups: https://xd.adobe.com/view/76c8e03c-ff8e-498b-ada5-0e2c08a8d8bd-239b/
