### ISSUE TITLE
Create mockups for Dependency Verification modal

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18482]
## Background
While we have a POC in place for the Dependency Verification, we need to ensure we are using the correct design system elements so we stay true to design intent.

## Considerations
- Explore other modal instances on VA.gov
- Determine user flow per diagram
- Determine which form will be used: 686 or 538
- Formalize verification interactions with View Dependents tool

<details>

<summary>Expand to see screenshots</summary>

![Screen-Shot-2020-12-30-at-10 42 27 AM](https://user-images.githubusercontent.com/53826255/104480783-f6416880-5592-11eb-9d53-a8f671117487.png)

![Screen-Shot-2020-12-30-at-10 42 38 AM](https://user-images.githubusercontent.com/53826255/104480785-f6416880-5592-11eb-818a-b35b8428f115.png)

</details>

## Tasks
- [x] Create mockups of the dependency verification modal window

## Acceptance Criteria
- [x] Share the mockups with FE and get feedback
- [x] Update the research-design folder with a changelog

**Comment by sporeboy** [comment]
Initial modal mockups available here: https://xd.adobe.com/view/9a75a359-e0e2-4411-b235-60c3dddb4e6e-cf26/

This XD doc includes revisions to View Dependents feature to align with the new "tool" layout. Some text revisions may be forthcoming...

**Comment by sporeboy** [comment]
Created Readme page here: https://github.com/department-of-veterans-affairs/va.gov-team/new/master/teams/vsa/teams/ebenefits/features/dependency-verification

**Comment by sporeboy** [comment]
Added "grey card" formlet version to View Dependents layout per review of design system and discussion w/ Shawna. This is the likely way forward.
