### ISSUE TITLE
Strategize Roadmap for KPI procedures

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1849]
## Problem Statement
How might we roadmap supporting and enabling KPI tracking for Now, Next, and Future.

## Goal
Have a roadmap for supporting VFS teams in KPI tracking.

## Objectives or Key Results this is meant to further
Human-centered-ness: incentivize high quality, holistic VFS UX, and product decisions based on user research / data.

## Acceptance Criteria
- [x] Create and document a roadmap for how to support VFS teams in tracking KPIs each quarter.
- [ ] Stretch: Flesh out epics related to the KPI roadmap

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[KPI Roadmap in Insights Strategy Deck](https://docs.google.com/presentation/d/10QFMqTCrEliqYaQr0dP4MZGOeL9broJPmakNc6A5YKk/edit#slide=id.g61980307dd_0_236)
