### ISSUE TITLE
Add disallow line for Erie Healthcare 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18497]
## Issue Description
Each time the VAMC team brings up a new System into Dual-State, a facilities engineer needs to add a disallow line (`Disallow: /erie-health-care/`) under # existing disallow on va.gov to the robots.txt file  and push a PR to engineering to prevent crawlers from accessing the new site in dual state.

Platform needs a PR to add that one line to the robots.txt file found 

Per Steve Wirt, the disallow should go [here: src/site/assets/robots.txt:97]( https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/robots.txt#L97)
`Disallow: /performance-dashboard`
(In the useragent *  section which covers all bots other than usasearch and synapse)

A [separate issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18498) has been created for the addition of an allow statement when the VAMC team is ready to put up a banner from the legacy site. 

[Slack conversation here](https://dsva.slack.com/archives/CPQFCQKEH/p1610487930440000)
---
## Tasks
- [x] add a disallow line (Disallow: /erie-health-care/) under # existing disallow on va.gov to the robots.txt file
- [x] Post message in VSP when PR is ready

## Acceptance Criteria
- [x] Disallow line has been added
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
`Disallow: /erie-health-care/` is showing on https://www.va.gov/robots.txt
