### ISSUE TITLE
Add Allow statement for Erie healthcare

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18498]
## Issue Description
When the VAMC upgrade team is ready to put up the banner from the legacy site, a facilities engineer needs to put in an allow statement that will "Allow FROM: /httpw://www.erie.va.gov"  so a URL can be placed to redirect the legacy website visitors to the new site, currently in Dual-state.

Related issue: [Disallow line](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18497) 

---
## Tasks
- [ ] Add allow statements for Erie

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
This is dependent on VAMC Upgrade plans for roll-out

**Comment by mmiddaugh** [comment]
These are being handled as roll-out dependencies with separate issues.
