### ISSUE TITLE
Update save-in-progress component to allow developers to specify heading levels

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#18502]
# Background
In a [past ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16692) we came across an issue where the heading level in the save-in-progress intro component breaks the heading level progression for accessibility. After some discussion with the accessibility folks, we decided the best solution was to update the save-in-progress intro component to allow the developer to specify what heading level they want the heading in the intro block to be. We will need to do this in a way that does not break the current implementations of this save-in-progress intro component.

## Tasks
- [ ] Obtain guidance from platform (tag Ryan Thurlwell/Chris Valarida/Brooks Johnson in Slack) on what would be needed to implement this as recommended by Josh

**Next steps**
- [ ] Update the `save-in-progress` intro component to allow for an optional property to specify heading level
- [ ] Submit a PR to the platform folder of  `vets-website` for review

## Acceptance criteria
- [x] A path forward has been established.

**Next steps**
- [ ] We are now able to specify what heading level we want the heading in the save-in-progress intro component
- [ ] A PR has been submitted for review

**Comment by cohnjesse** [comment]
@joshkimux After some [discussion with VSP](https://dsva.slack.com/archives/CBU0KDSB1/p1611789311332100) it looks like the work to fix this is outside the scope of what our team is working on. They have a bot open and tracking the issue.

**Comment by joshkimux** [comment]
@cohnjesse Thank you for the update! 🙏
