### ISSUE TITLE
Update BGS Gem for Update Diaries

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#18507]
## Goal
We need to call the BGS Diaries Web Service to update the diary due date when a Veteran verifies the status of their dependents.

## Tasks
- [x] Update BGS gem to allow the `updateDiaries` service to be utilized

## Acceptance Criteria
- [x] BGS gem code is submitted 
- [x] A PR is requested for merging, if unborked at time of request

**Comment by jason-gcio** [comment]
Onur is currently working to resolve this, so it can be moved forward
