### ISSUE TITLE
Content Support Request from VAOS

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18500]
## Background
The Help Desk notified the VAOS team that the VVC support hours are 24/7. We've made the respective change in the VAOS app footer and would like to align similar content.

## Content request
Update existing copy for VA Video Connect support hours on the static landing page for VAOS.

- [ ] Updates to an existing unauthenticated VA.gov page

- **What URL(s) do we need to review or update?**
https://www.va.gov/health-care/schedule-view-va-appointments/ (and lower environment equivalents)

- **Are updates for a small section of copy?** Yes

From:
> We’re here Monday through Saturday, 7:00 a.m. to 11:00 p.m. ET.

To:
> We’re here 24/7.

![Screen Shot 2021-01-13 at 8.13.52 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/caaa70f8-a3c7-4a6c-8d1c-19b61aa830aa)

- **Are updates related to usability testing or analytics?** No

## Desired/target implementation date
1/21/21

## About your team

- Team name: VAOS
- DEPO product owner: Lauren Alexanderson
- Product manager: [Lauren Ernest](https://dsva.slack.com/archives/D01CW02PGSE)
- Designer: Peter Russo
- Product/team Slack channel: vaos-team

---

### Acceptance Criteria

- [ ]  Convert this request into a Zenhub epic
- [ ]  Follow-up with requestor to address any lingering questions/concerns
- [ ]  Create epic/tickets as needed for the Public Websites team to implement

### Definition of Done
- Request ticket is closed and implementation tickets created as needed

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Could you work with Kelson to update this, since the content isn't in Drupal? 

Adding sitewide content labels.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/16183

**Comment by RLHecht** [comment]
Thanks, @kelsonic ! @DanielleThierryUSDSVA This change should be live today or tomorrow.

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy tomorrow since I missed the cut off today 🙂

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA @RLHecht this has been merged, wondering if we can close this ticket?

**Comment by RLHecht** [comment]
Yep, all good to close, @brianalloyd. Thanks!

**Comment by laurenernest** [comment]
@DanielleThierryUSDSVA How do we handle the "last updated" date since it's now no longer accurate?
<img width="810" alt="Screen_Shot_2021-02-26_at_3_33_08_PM" src="https://user-images.githubusercontent.com/72046525/109551876-f5eb2700-7a85-11eb-8f4d-d4db5f066f8f.png">

**Comment by DanielleThierryUSDSVA** [comment]
Great question, @laurenernest! I think for the moment, we just go in an republish the Drupal page any time we make an update in the react file so the dates stay consistent.

But, this speaks to a larger need to shift back to having more of this content in Drupal. When the implementation of this came to the PW team, this approach of all content (except intro) in Drupal was a solution because of urgent timing and lots of complications. But the ideal would be for as little of the content as possible to be in the react widget and instead live within Drupal so the content team can manage it.

That's on our list of things we want to do in 2021. @RLHecht we can add to our next content mtg and set up an epic for the work (which would need to start w/ an audit of the pages to determine which content is dynamic outside of the sign-in modal). Thanks!

**Comment by brianalloyd** [comment]
Closing per Validation, thanks @RLHecht
