### ISSUE TITLE
Design: Explore UX of 10-10EZ of displaying both mailing and home address on review page 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#18509]
## Issue Description

_As a Veteran_

_I might like to see both mailing and home address on the review page._

_So that I can see that both addresses are being sent correctly with my application._

---
## Tasks
- [ ] _Explore how other forms handle two addresses_
- [ ] _Investigate technical limitations_

## Acceptance Criteria
- [ ] _Team uses information to determine next steps _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by hdjustice** [comment]
The home and mailing addressed do appear on the review page, this ticket is no longer needed.
