### ISSUE TITLE
Meet with GA Team re: Failed Events

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18519]
## Background
There is some fuzziness as to what is being tracked as failed event for non-LOA3 access in View Payments that needs to be fine tuned.

## Considerations
- Topics of discussion:
    - Event for when a user hits the LOA1 verification alert
    - Why unique error events (4xx vs 5xx) are indistinguishable in GA. [error-keys in these events aren't viewable?](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/view-payments/actions/index.js#L28)

## Tasks
- [ ] Schedule and conduct a meeting with GA

## Acceptance Criteria
- [ ] Meeting has been attended
- [ ] New event for LOA1 alert has been agreed on
- [x] Resolution on why unique error events aren't viewable

**Comment by jason-gcio** [comment]
This might not need to go over to the Analytics folks just yet; in GA, we found a better way (thank you @cohnjesse) to display error keys:
![image](https://user-images.githubusercontent.com/53826255/104759010-448a6f00-572d-11eb-99ba-1e1ce2a24afd.png)
We also have some improvements to how 500's are handled waiting to be merged in.  This ticket might be closed, depending on those results.
