### ISSUE TITLE
Post-launch review of 'VA Debt Management' tool 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18522]
## Issue Description
_Now that the Debt Management tool launched and we're getting closer to releasing the FSR we should take a look at the 'Manage your VA Debt' tool to uncover areas to improve/iterate on_

---
## Tasks
- [x] _Review the launched Debt Management tool and document proposed improvements_
- [x] _Review DOMO analytics in relation to the Debt Management_

## Acceptance Criteria
- [x] _Documentation has been attached to this ticket and proposed improvements/features have been discussed w/ the team_

**Comment by rileyorr** [comment]
This work coincided with capturing the overall VA debt experience, so the attached documents (which can also be viewed in [this miro board](https://miro.com/app/board/o9J_kxbu2M4=/)) contain planned and potential improvements to the debt portal as well as the FSR.

**Artifact 1: Debt journey**
![VSA - Debt Management MVP (1)](https://user-images.githubusercontent.com/46329147/105881432-812e5400-5fd2-11eb-99c3-c3cff11e08e4.jpg)

**Artifact 2: Experience mapping**
![VSA - Debt Management MVP](https://user-images.githubusercontent.com/46329147/105881433-81c6ea80-5fd2-11eb-8d5d-8a05e1696d60.jpg)


The planned and proposed features have also been documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1rQV_eobcgze0FiZ_ahgdwz6jhb1zz7zROglLPxOY1QU/edit?usp=sharing) and indicate priority, dependencies, and next steps.
