### ISSUE TITLE
[DISCOVERY] Urgent care mash-up user experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18521]
## Issue Description
When a Veteran selects "Urgent care" + "All urgent care" the results list includes 10 community providers and 10 VA facilities. Because of this fixed number, the result set may not include all of the closest locations of any one type. This may cause additional confusion if the "Community providers only" or "VA urgent care" search results are compared to list of results for "All urgent care".

Example: All Urgent Care in New York. Note the VA locations (U and V) should not be included.

![Find_VA_Locations___Veterans_Affairs](https://user-images.githubusercontent.com/80267/107827260-6b4fbb80-6d54-11eb-8446-baabb9a95db0.png)

---
## Tasks
- [x] Document current logic for returning urgent care mashup results
- [x] Determine options for handling urgent care results so that the closest [x number] of VA and Community care locations are returned, regardless of type distribution

## Acceptance Criteria
- [x] Current logic is documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
**Current Implementation**
In the back end mashup controller we make 2 separate calls, 

1. Lighthouse 
2. PPMS

Each of these requests uses the per_page query param to determine max # of results returned.

We can’t do sorting or pagination on the back end efficiently with this implementation.

**Recommendation**

- Make 2 separate queries on the front end (one for VA, one for CC) and merge them together on front end, sorted by distance.
- Queries can be done in parallel
- Show the 20 closest results
- Would let us sunset the mashup controller

**Comment by mmiddaugh** [comment]
Created engineering issue (#19959) for this work
