### ISSUE TITLE
Maintain Session State for Wizard Presentation

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18538]
`Note: this is closely related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/18539 and should probably be done at the same time`

## Background
Much like we did with the CH36, we want to check when the Veteran completes a wizard so that we are not constantly presenting the eiligibility wizard to them.

## Considerations
- A link will be included that allows the Veteran to reinstate the wizard (and content) in case they wish to see if the application is the right one for them.

## Tasks
- [ ] Adjust the session state to keep wizard progression

## Acceptance Criteria
- [ ] The wizard is only shown once per session
- [ ] A PR has been requested for merging
