### ISSUE TITLE
Include a "Go Back" Link for CH31 Wizard

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18539]
`Note: this is closely related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/18538 and should probably be done at the same time`

## Background
Much like we did with the CH36, we want to callow the Veteran to be able to re-visit the wizard and orientation content if they wish, as the session will slip it if it has already been completed.

## Considerations
<details>

<summary>Expand to see example screenshot on CH36</summary>

![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/0c2c273f-bbc7-4cf0-b053-2746968fc7d2)

</details>

## Tasks
- [ ] Include a link that removes the session state and brings the Veteran back to the wizard and content

## Acceptance Criteria
- [ ] The feature has a link on the intro page (at the bottom) that allows the Veteran to be taken back to the top of the uncompleted wizard and orientation content page
- [ ] A PR has been requested for merging
