### ISSUE TITLE
[FSR] Incorporate content specific for waiver requests on the 'financial overview' screen

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18541]
## Issue Description
_If a Veteran requests to waive their debt, they need to provide a written statement providing more information about why they're requesting that resolution path. Content needs to be added to that screen to clarify what information the user needs to provide when requesting a waiver. Additionally, the content in the 'Why do I need to explain this?' additional info component needs to be updated to provide more information about what DMC expects Veterans to include in the text field._

---
## Tasks
- [x] _Review the content under the 'Why do I need to explain this' additional info component and update as needed_
- [x] _Add clarifying content for Veterans requesting to waive their debt_

## Acceptance Criteria
- [x] _The UXPin prototype has been updated with proposed content and linked in this ticket_
- [x] _The proposed content is reviewed by a VSP content writer_
- [x] _A ticket for frontend implementation is created and linked in this ticket_

**Comment by rebeccawalsh** [comment]
Waiting on Danielle's feedback on content, but the new design proposals are here:
- [If a waiver was requested](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/135883557/simulate/sitemap?mode=i) 
- [If no waiver was requested](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/135732390/simulate/sitemap?mode=i)

**Comment by leahkeeler** [comment]
@rebeccawalsh  closing - the content has been reviewed already by Danielle corerct?

**Comment by rebeccawalsh** [comment]
@leahkeeler In this case, yes, I requested the copy from Danielle before she sent over the rest of the document!
