### ISSUE TITLE
Remove LOA Check for CH36 and CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18579]
## Backend
There is a small backend check that needs to be removed to allow for non-LOA3 users to be presented with the correct workflow in the CH36.

## Tasks
- [ ] Remove the LOA3 specific check on login for the CH36 feature
- [ ] Verify that the form is populated correctly

## Acceptance Criteria
- [ ] The CH36 feature does not get hung up on a LOA3 specific check
