### ISSUE TITLE
[FE] Update Test and Mock data

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18585]
## Related Documentation
> these should be links to feature docs
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
In order to help guide development, We need to make test data to verify that all use cases for the front end have been converted. This test data will update the mock data for Questionnaire List to reflect the different states of an appointment and questionnaire response

Appointment status 
- upcoming
- canceled

Questionnaire Response Status
 - not started
- in progress
- completed
- past due

## Tasks
> this is a list of technical tasks that are needed for this ticket 
- [ ] Update data on the questionnaire list
- [ ] All the states for an appointment is a document
- [ ] Create unit tests

## Acceptance Criteria
> when is the ticket done 
- [ ] Engineer team is synced up. 
- [ ] Team has been updated on all the different cases.

**Comment by mdewey** [comment]
Merged, waiting for deployment to staging

**Comment by mdewey** [comment]
Updated data is in staging. https://staging.va.gov/health-care/health-questionnaires/questionnaires/to-do
![screencapture-staging-va-gov-health-care-health-questionnaires-questionnaires-to-do-2021-01-26-16_34_33](https://user-images.githubusercontent.com/1793923/105908582-6371e680-5ff4-11eb-8409-d16334167368.png)
