### ISSUE TITLE
Set up CD process that automates the deployment of Loki using ArgoCD

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18588]
## Description
We need to be able to automate the deployment of Loki using our CD tools. 

## Background/context/resources
We have CI pipeline set up for Loki, and have deployed Loki using a Helm chart, but now want to close the loop with a fully automated deploy of Loki using ArgoCD + Tanka 

## Technical notes
TBD

---
## Tasks
- [x] ArgoCD way of Loki deployment to staging once ArgoCD staging is done (https://github.com/department-of-veterans-affairs/devops/pull/8365/files)

## Definition of Done
- [x] Loki CD automated process using ArgoCD
---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
This is good to go. Closing
