### ISSUE TITLE
[FE][SPIKE] Dynamic Mapping of Questionnaire

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18591]
## User Story
As a veteran, 
I might have more than just Primary Care questionnaires 
So I need a UI that is dynamic

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
Research and prototype creating a mapping of questionnaires based on a questionnaire id to load an entirely different form.
## Questions to Answer
- [ ] How can we dynamically determine a form config based on URL params?

## Tasks
- [ ] Create a prototype
- [ ] Document and share pitfalls and successes

## Acceptance Criteria
- [ ]  Engineering team is aware of the outcome
- [ ] Team understands summary

**Comment by leahkeeler** [comment]
not part of MVP - future iteration

**Comment by acrollet** [comment]
Closing OBE
