### ISSUE TITLE
Remove Basic Auth for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18595]
## Background
VRE teams are conducting some testing and noticed an issue with basic auth prohibiting some browsers from allowing access.  We should remove basic auth.

## Tasks
- [ ] Submit a request for a PR review to ops folks on getting that removed.

## Acceptance Criteria
- [ ] Basic auth is removed from the CH31 feature.
- [ ] A PR has been requested for off cycle deploy

**Comment by jason-gcio** [comment]
PR: https://github.com/department-of-veterans-affairs/devops/pull/8368
