### ISSUE TITLE
Separate ROE from practice area guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#18608]
## Issue Description
The content inventory is complete. With the Collaboration Cycle being the desired point of interaction between VSP Product Support and VFS teams (and not the individual practice area themselves), we need to ensure that our practice area specific documentation does not reference how VFS teams should be interacting with us. The practice area guidance should focus on standards, expectations, guidelines, and resources only. All references to interaction, engagement, communication, Collab Cycle, ticket submission, slack channels, etc. need to be flagged and removed from the practice area documentation/guidance.

---
## Tasks
- [X] Consolidate all tabs within [Content Inventory - Product Support ](https://docs.google.com/spreadsheets/d/1DHeJ6N7Z2DfwBY6uk1urnKOr_sLBe7RTl5oIN1-yRQU/edit#gid=0)spreadsheet into 1 tab and name "Combined Audit"
- [X] Lock individual practice area tabs
- [ ] Using column O, specify the Document Type. Acceptable answers include: README, standard, process, template, checklist, common issue, best practice)
- [X] Identify documents that make reference to the Collaboration Cycle (0-4, 0= no Collab cycle reference, 4=100% Collab Cycle document)
- [ ] For documents marked as OUTDATED, provide more context - goal is to identify documents that do not have a place in the new github organization (essentially we are identifying docs that are candidates for archive/delete, but not actually doing that yet) and their content is no longer relevant for VFS teams.
- [ ] Review documentation that has 1-3 rating (25%-75% mentions of the Collab Cycle)
   Is the documents reference to the Collab Cycle covered in the new Custom Tracks documentation?
   If yes, remove mentions of the Collab Cycle in the practice-area documentation.
   If no, add to list of requirements for Collab Cycle documentation.
- [ ] Review documentation that has 4 rating (100% Collab Cycle document):
   Add to list of requirements for Collab Cycle documentation.
- [ ] Discuss archive process with Content & IA team
- [X] Regroup as a team on 2/9 and discuss next steps 

Using column C, specify which documents should be reviewed for Collaboration Cycle mentions and/or references to other interaction points.

## Acceptance Criteria
- [ ] VSP Product Support team understands the likes, dislikes, commonalities, and gaps within their existing documentation/guidance.
- [ ] VSP Product Support team has enough information to begin drafting a desired framework.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
[Mural Board for Synthesis of Content Inventory](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1611253696417/589622d5cf8ab57443589563164c91023de98c60)

**Comment by peggygannon** [comment]
@allison0034 Can you give me write access to the Mural board? It seems I have view-only access to it.

**Comment by shiragoodman** [comment]
Update 2/24: This work was completed, however the team was challenged with what steps come next. It is likely we will come back to this in order to determine how best to remove Collaboration Cycle references from practice area documentation, and move Collaboration Cycle documentation (for example: how to run foundational accessibility tests at Staging Review) currently associated with the practice area to being documentation that is part of the Collaboration Cycle. 

For now, we are pivoting to focus on identification of launch blocking standards in QA, IA, content and design.
