### ISSUE TITLE
Determine how to convert one of Ops-owned applications to use SSM Parameter store

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18613]
## Description
We need to create a strategy for moving credentials and applications from credstash to SSM efficiently

## Background/context/resources
Step needed for determining path forward

## Technical notes

Script for lifting and shifting credentials is being re-written (written by @dginther, in devops repo)
We have identified the necessary way to change how Ansible performs lookups for credentials 
We have identified the first app that we're looking to convert (fwdproxy)

---
## Tasks
- [x] Determine most efficient way to attack application conversion / eliminating credstash as the app credential store.
- [x] Provide an iterable path for teammates (script created) 

## Definition of Done
- [X] A plan for how we'll convert an app will be defined by tasks in a separate ticket -> [#18614](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/18614)

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
What will likely make this pretty easy, is that the lookup tool that we use in Ansible for credstash, works with SSM Parameter store as well.

**Comment by jbritt1** [comment]
Please see the attached issue above: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18614

**Comment by dginther** [comment]
Done!
