### ISSUE TITLE
Usability Testing Prep: Booz Allen - GI Bill Comparison Tool Redesign

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#18610]
## Steps to complete Usability Testing Prep: 
- [ ] VFS Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [ ] VFS: Attach all artifacts before requesting the meeting
- [ ] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance included in each practice area feedback ticket 
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/ct-redesign-discovery_product-outline.md)
- [Link to prototype](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens)
  **- Desktop Prototype**
  - [**Desktop Task 1** Radius from location](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055355)
  - [**Desktop Task 2** Program Search](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055379)
  - [**Desktop Task 3** Compare Schools](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055387)
  **- Mobile Prototype**
  - [**Mobile Task 1** Radius from location](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055352)
  - [**Mobile Task 2** Program Search](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055383)
  - [**Mobile Task 3** Compare Schools](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055388)
- Link to or attach artifact with copy (if separate from prototypes/mockups): **NA**
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/usability-testing/research-plan.md) and [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/usability-testing/discussion-guide.md) 
- Link to regression test plan: **N/A** This is a completely new build so there's nothing to regression test against.  
- Link to [test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/1248) (...just a draft) 

## Meeting attendees from **requesting team**
- Product Manager (required): Darrell Neel, PO - neel_darrell@bah.com
- DEPO product lead (required): Matt Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): 
  - Jen Jones, UX - jones_jennifer2@bah.com
  - Emma Waters, UX - waters_emma@bah.com
  - Amy Knox, UX - knox_amy@bah.com
  - Michael Delli-Gatti, QA - delli-gatti_michael@bah.com
  - Will McCormack, Delivery Lead (Optional) -  mccormack_will@bah.com
- Other specialists: **names**
  - 
VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira will reach out as needed_

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by amyknox** [comment]
@shiragoodman & @andreahewitt-odd 
Booz team is looking to schedule the CT Usability Testing Prep session Jan 27 at 11:30.  Could you set that time for us now and we'll get the assets together and ready for your review.

**Comment by shiragoodman** [comment]
sounds good @amyknox . I will schedule by EOD.

**Comment by shiragoodman** [comment]
hi @amyknox - do you have the artifacts and/or attendees ready?

**Comment by amyknox** [comment]
Hi @shiragoodman - I added links to the artifacts we've drafted thus far. Since the mtg is next Wednesday, some of the items are still in the works. 

Question for you: When I'm listing who's supposed to be invited, the template says "VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable."  Does that mean I have to list Emily, Allison, Peggy, Ryan, etc. Or should I be listing just people from my own team?

**Comment by peggygannon** [comment]
Hi, @amyknox Is there a content outline artifact? If so, can you link it to this ticket? It will help greatly with my content feedback/recommendations.

**Comment by amyknox** [comment]
Hi @peggygannon - there's not a lot of content in this UI.  Here's where we're keeping it now; https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/design/content-doc.md

**Comment by allison0034** [comment]
@watersemma @amyknox I know you have worked so hard on this and it is looking great. The search and filter option at the top (vs left) is a new pattern, we have something similar on facilities locator but not nearly as complex. In order to approve the new pattern we need to make sure we usability test this on both mobile and desktop. That being said I did not see a mobile view of this. Do you have one?

**Comment by amyknox** [comment]
@allison0034 - [Here's the mobile prototype](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055352).

**Comment by 1Copenut** [comment]
@amyknox Would you be able to link the second and third task starting points above with the first task? Those direct links are especially helpful!

**Comment by amyknox** [comment]
@1Copenut - added direct links to the original story and here for easy access: 

  **- Desktop Prototype**
  - [**Desktop Task 1** Radius from location](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055355)
  - [**Desktop Task 2** Program Search](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055379)
  - [**Desktop Task 3** Compare Schools](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055387)
 
  **- Mobile Prototype**
  - [**Mobile Task 1** Radius from location](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055352)
  - [**Mobile Task 2** Program Search](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055383)
  - [**Mobile Task 3** Compare Schools](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055388)

**Comment by pjhill** [comment]
The draft test plan appears to be empty -- https://dsvavsp.testrail.io/index.php?/plans/view/1248
![image](https://user-images.githubusercontent.com/52456633/106020317-a03feb00-6091-11eb-86cc-32ec44f9e178.png)

**Comment by pjhill** [comment]
Since there were no QA artifacts available to review at this time, no detailed feedback regarding specific QA efforts has been provided.

**Comment by amyknox** [comment]
Thank you @pjhill - we are very early in the design phase and no development is planned for quite awhile.

**Comment by allison0034** [comment]
@amyknox  I spoke with Shira and we are good to move forward with doing more than 1 staging review for you for the GI comp tool. If you can have all artifacts for the first review complete by Monday, then we can do your first review Thursday July 8 at 2. Submit the ticket asap please. @shiragoodman  I have a hold on that spot in the calendar.

**Comment by amyknox** [comment]
@allison0034 - thanks for all your help on this. Glad to know @shiragoodman 's on-board with the updated approach.  

Reviewing the staging review criteria, I'm pretty confident we won't have all the testing assets complete by next Monday (or Tuesday since Monday's a holiday) so you can release the hold on that time for another team.
