### ISSUE TITLE
Design hierarchy for parameters and credentials in SSM

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18611]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Background/context/resources
Managing dozens or hundreds of parameters as a flat list is time consuming and prone to errors. It can also be difficult to identify the correct parameter for a task. This means you might accidentally use the wrong parameter, or you might create multiple parameters that use the same configuration data You can use parameter hierarchies to help you organize and manage parameters. A hierarchy is a parameter name that includes a path that you define by using forward slashes (/)..

(From AWS Documentation)

## Technical notes
_Notes around work that is happening, if applicable_
The parameters that existed as a flat list in credstash have been lifted and shifted migrated to SSM. 
We'll be able to use these as a baseline to plan. 
[SSM Documentation Working with Parameter Hierarchies](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-hierarchies.html)

[SSM Hierarchy Documentation](https://vfs.atlassian.net/wiki/spaces/VI/pages/1021935643/SSM+Hierarchy)

---
## Tasks
- [x] Select and agree on a hierarchal structure for credstash params and credentials.
- [x] Document the hierarchy design and get feedback from team. 
Devise a way for consistent / regular updates to SSM while teams are still using credstash. (creating a new ticket for this) 

## Definition of Done
- [x] SSM Parameter Store hierarchy is detailed, shared, and agreed on by team.
---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
WIP: https://vfs.atlassian.net/wiki/spaces/VI/pages/1021935643/SSM+Hierarchy

**Comment by jsev-io** [comment]
https://vfs.atlassian.net/wiki/spaces/VI/pages/1021935643/SSM+Hierarchy

**Comment by jsev-io** [comment]
Documentation now complete.

**Comment by jhouse-solvd** [comment]
Per discussion w/ @dginther & @jsev-io, we can move this to done. Please see https://vfs.atlassian.net/wiki/spaces/VI/pages/1021935643/SSM+Hierarchy for more info and up-to-date documentation. 

Closing.
