### ISSUE TITLE
Convert fwdproxy (DEV) to use SSM Parameter store (instead of credstash)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18614]
## Description
We want to eliminate dependency of Credstash for fwdproxy so that we can modernize our infrastructure with an improved approach to credentials management (using Amazon's SSM parameter store). 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
In the case of DEV, there are specific variables that contain references to certs/keys/etc in the following environment-specific config: 
ie. ansible/deployment/config/fwdproxy-vagov-dev.yml
```
  - content: "{{ lookup('credstash', forward_proxy_interfaces.es.key, version=forward_proxy_interfaces.es.key_version) }}"
    dest: "{{ forward_proxy_interfaces.es.ssl_certificate_key }}"
    owner: "{{ forward_proxy_interfaces.es.owner | default(deployment_app) }}"
    mode: "0400"
```

There are also instances where variables can be expressed **ACROSS ALL ENVIRONMENTS** in a j2 (jinja) file, which is beyond the scope of this ticket, but good to know for the future:
ie. ansible/deployment/config/fwdproxy/*.pem.j2
```
{{ lookup('credstash', forward_proxy_interfaces.api_vet360.key, version=forward_proxy_interfaces.api_vet360.key_version) }}
{{ lookup('file',  "../deployment/config/fwdproxy/" + forward_proxy_interfaces.api_vet360.cert)  }}
```
---
## Tasks
- [x] Run the credstash->parameter store sync script that is in the devops repo 
- [x] Convert one of the existing credstash lookups (cert/key/etc) to use SSM parameter store (limiting impact to DEV only!) 

## Definition of Done
- [x] One credstash lookup ~for fwdproxy~ in DEV is converted to use SSM parameter store

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
moved back to Ready column until @jsev-io returns 4/5 and can pick this back up

**Comment by jbritt1** [comment]
This has been used in a few places that aren't necessarily in fwdproxy configs, but is definitely already being used after being tested previously. Example: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-server-vagov-dev.yml#L203-L207

**Comment by jbritt1** [comment]
Edited definition of done to drop the fwdproxy since this was coincidentally tried out in a different service config, but all seems to be working as expected with this new process. Think this is a closable one at this time.
