### ISSUE TITLE
Improve output on failed content release from CMS team

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#18620]
## Why you're here 

The VAMC upgrade team is attempting to do content reviews of previously unpublished content.  Fairly often we run in to  build error that gives not feedback as to what page failed.

![image](https://user-images.githubusercontent.com/5752113/104736236-a7b9d880-5710-11eb-8f9b-0fd15cab2449.png)

The root cause is a page in the CMS is missing a parent or reference to a grandparent, so the breadcrumb builder is unable to build the breadcrumb and the url.  The problem is we have no way of knowing which piece of content is failing and we spend hours hunting for the content in the CMS.
It would be of great help to the VAMC Upgrade team and the CMS team if this bit up code could be wrapped in try catch so that it could output a meaningful error report to tell what page has the error.
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/health-care-region.js#L196-L202

These same errors come up occasionally on front den content releases and send engineers from both front end and CMS team scattering to find the break.

This is currently blocking the release both Salisbury VAMC and FayettevilleCostal, but potentially effects all CMS products.

### Content support for:
- Unauthenticated (static) VA.gov pages
- Apps or tools
- Other writing or editing requests

### Engineering support for:
- JS build script

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [ ] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * < description > 
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

- [ ] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * < URL list >
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * < list of new info >
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * < list of new info >

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* <Desired/target implementation date>

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *enter name*
- DEPO product owner: *enter name*
- Product manager: *enter name*
- Designer: *enter name*
- FE engineer: *enter name*
- Product/team Slack channel: *enter*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by brianalloyd** [comment]
@ncksllvn could you look into this issue today?  It's currently blocking VAMC upgrade team work and would like to help unblock.  Here's the [slack](https://dsva.slack.com/archives/C01H29ERVJ7/p1610720044002400) convo for review.

**Comment by ncksllvn** [comment]
I'll try. I need to read it about a dozen more times before I understand what it's asking me to do.

**Comment by swirtSJW** [comment]
@ncksllvn TLDR: Output the page that is failing when trying to determine the url.

**Comment by ncksllvn** [comment]
@swirtSJW I'm following now. Is there an easy way for me to recreate it?

**Comment by ncksllvn** [comment]
And is the expected behavior still to throw an error and fail the build?

**Comment by swirtSJW** [comment]
@ncksllvn It should still fail the build.  If a breadcrumb or location of the page is broken that would be bad.  So I thing failing it is still the right thing.   I just want to know which one is failing.    

Reproducing... If you have the ability to pull the content from http://fayettevillecoastalhealthcare.demo.ci.cms.va.gov/ it would fail as that is the one that has the proofing content published and is failing to build.

**Comment by ncksllvn** [comment]
This work is done, https://dsva.slack.com/archives/CDHBKAL9W/p1611067457017300?thread_ts=1610755128.013300&cid=CDHBKAL9W

**Comment by brianalloyd** [comment]
Closing per validation.  Thanks @ncksllvn for the great work effort.
