### ISSUE TITLE
[REVIEW] [PRIORITY] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Fayetteville Arkansas health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18629]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-16 Internal Review Folder](https://drive.google.com/drive/folders/19WE1dLBjZkeIMW8ACPbOZ-BWzaoOTopq)
[Review template for review](https://drive.google.com/drive/folders/18CfKY3QZhR4AoiByBYKqAgKfFewEb9RV)

## Tasks
- 1) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 564	Fayetteville VA Medical Center
- [x] 564BY	Gene Taylor Veterans' Outpatient Clinic
- [x] 564GA	Harrison VA Clinic
- [x] 564GB	Fort Smith VA Clinic
- [x] 564GC	Branson VA Clinic
- [x] 564GD	Ozark VA Clinic
- [x] 564GE	Jay VA Clinic
- [x] 564GF	Joplin VA Clinic
- [x] 564QB	Sunbridge VA Clinic
- [x] 564QA	Township VA Clinic

- 2) Confirm that All Menu items are below the --[System name] and not under "<" system name ">"
- 3) Review and correct all **Broken Links** on each of the system pages in Prod/Devshop

- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [ ] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by lealester** [comment]
Checklist for Lea: Meta tags, Meta descriptions; Incorporate Peggy changes, add facility pictures; complete prepare for your visit (parking and transportation only two required for both VAMC & Clinics); change TDD to TTY; Clone Events, Stories, and News Release; Review broken links and redirect links in PROD

**Comment by ltrombley** [comment]
Added to additional sites from VAST:
