### ISSUE TITLE
Fix Covid Dashboard Charts

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18634]
## Issue Description
During our Covid Dashboard sync on 1/15/21, we noticed a few charts that need updates. This issue is to track those updates.

---
## Tasks
- [x] [All VA.gov pageviews chart](https://va-gov.domo.com/page/1789426532/kpis/details/1424082415) only updates to Jan 1, 2021
- [x] [Number of link clicks on homepage banner chart](https://va-gov.domo.com/page/1614417801/kpis/details/1248831427) was last run on 12/19/20
- [x] [National Call Center (NCC) - Covid-related calls per week chart](https://va-gov.domo.com/page/1614417801/kpis/details/1057146443) is not appearing

## Acceptance Criteria
- [ ] Fixes to known chart issues have been made, and the Covid Dashboard is up-to-date

**Comment by JasonTheBearded** [comment]
@joanneesteban All fixes complete and implemented!

**Comment by joanneesteban** [comment]
Fantastic! Thanks, @JasonTheBearded . Looks good, closing this out 👍🏼
