### ISSUE TITLE
[RESEARCH] V2 COVID-19 vaccines search experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18659]
## Issue Description
The initial v1 COVID-19 vaccines search experience made searching for facilities offering COVID-19 vaccines possible and linked VAMC search results to the COVID-19 vaccine info page. The goal for v2 search experience is to make relevant service details 
available in the Facility Locator search workflow. 

<details>
<summary> COVID-19 vaccines VAMC accordion content </summary>

![image](https://user-images.githubusercontent.com/55411834/104775610-d6967580-5735-11eb-87ac-7aefc471f1fa.png)
</details>

## Research questions

Considering the information displayed within the COVID-19 vaccines accordion
- When searching for facilities offering COVID-19 vaccines, what service details do Veterans need/expect? 
- What information is best suited to display in the results card?
- What information should be made available via links to VAMC (or other page)? 

---
## Tasks
- Determine the search method best suited to gathering feedback on the research questions 
- Prepare a research plan, conversation guide and appropriate wireframe/visuals to support the sessions

## Acceptance Criteria
- [ ] Research plan and conversation have been reviewed by PM, PO, Shawna and accepted for recruitment kickoff by Lauren Alexanderson. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as public health emergency declared to be over
