### ISSUE TITLE
[DESIGN] COVID-19 vaccines FL search experience V2

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18660]
## Issue Description
The initial v1 COVID-19 vaccines search experience made searching for facilities offering COVID-19 vaccines possible and linked VAMC search results to the COVID-19 vaccine info page. The goal for v2 search experience is to make relevant service details 
available in the Facility Locator search workflow. 

Note: Veteran research will be conducted using this design once in Production to inform future iterations and detail display for other services 

## Current workflow
https://app.mural.co/t/vsa8243/m/vsa8243/1612565378813/60857e25414c7bebeb8e6982cde371e443001a60

---
## Tasks
- Review content displayed on VAMC system and facility pages (in Teamsite and Drupal) and on VA.gov
   - [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/#who-can-get-a-covid-19-vaccine)
   - [COVID-19 vaccines at Washington DC VA Medical Center](https://www.washingtondc.va.gov/services/covid-19-vaccines.asp)
- Identify which data available via Lighthouse should be displayed on the Facility Locator result card (when Facility type = VA health and service type = COVID-19 vaccines) 
  - Appointment intro test
  - Service location address
  - Service hours
  - Service phone #
  - Referrals needed?
  - Walk-in available?
  - Online scheduling available?
- Determine best flow/method to link Veterans to finding more facility service-specific information. 

## Acceptance Criteria
- [ ] Wireframe/design spec ready for front end implementation 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
From lighthouse: 
- `detailed_services`
- `hservice_appt_leadin` -> the intro text for appointments. They can either pick the standard (please call for scheduling, rescheduling, ...) or it can be customized if needed (i.e. VA health care team will call you if eligible or there is a drive in clinic for Covid-19 vaccines)
- `online_scheduling_available`
- `referral_required`
- `walk_ins_accepted`

**Comment by mmiddaugh** [comment]
Pending more info about the data which will be available from Lighthouse

**Comment by lildziner** [comment]
This file contains prototype iterations as follows:

If the phone number goes to a generic number use: "Call us to schedule" call to action, as seen in [iteration V11](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/137873897). This language was proposed by Beth Potts and Danielle T. .

**Comment by lildziner** [comment]
These designs were vetted via the #Design channel. Decisions and input from SMEs:

• Action link (the link with the preceding blue circle icon) is ok to use as shown in the iterations above (per Crystabel and Allison). 
See Design System [guidance](https://design.va.gov/components/action-links) and [code example](https://design.va.gov/storybook/?path=/docs/components-action-link--page). 

• Per Trevor: "COVID-19 info at this location" as with "Get directions" need accessible labels via SR-only text so that each provides contextual labels, e.g. "Get directions to Austin VA clinic". The equivalent here could be: "Get COVID-19 information for Rocky Mountain Regional VA Medical Center"

**Comment by lildziner** [comment]
**Regarding facility status:**

If scheduling appointments ahead of time is mandatory, a status would be less useful and relevant and clutters the results cards.

However, if/when walk-ins become available, just-in-time messaging like facility statuses could be more important to users. In this scenario, would online scheduling still be preferred? If not, [consider V10](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/137867358).

**Comment by lildziner** [comment]
[Iteration V12](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/138022004) factors in the variability of information that facilities may or may not offer to Veterans. 

This iteration includes:

- Facility status - COVID-19 pages are not required to communicate this
   - Facility status placement moves back to below facility name (old placement that tested poorly) because it needs to be associated with the detail page and not the COVID-19 page

- "Call us to schedule:" phone label since a dedicated "COVID-19 phone", _that does not go to a central line first_, is not guaranteed

![Screen Shot 2021-04-06 at 8.33.35 AM.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/c7852c78-7f0d-43b4-9a37-56316c52771d)

**Comment by mmiddaugh** [comment]
@lildziner one requested change: 
One primary goal of this iteration is to drive use of online scheduling/self-service - with that in mind, the online scheduling CTA should come before the phone number. 

Dave suggested if online scheduling is available, then the label for the phone could be "or call us to schedule". If online scheduling is not available, the label remains as you've designed. 


In either case, the link to COVID-19 info should be the last CTA, as shown in your Aurora VA Clinic prototype result. 

1. Online scheduling CTA (if available)
2. Phone CTA
3. Link CTA

**Comment by lildziner** [comment]
I made the change in [iteration V13](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/138059694). I shortened the CTA to "Or call to schedule:" (omitting 'us') so that it wouldn't break onto two lines. 
![Screen Shot 2021-04-07 at 7 42 57 AM](https://user-images.githubusercontent.com/4960080/113861176-e6da5180-9774-11eb-9993-ea3c4f44989e.png)

**Comment by mmiddaugh** [comment]
Nailed it, @lildziner - thank you!!
