### ISSUE TITLE
Remove appointments views flags

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18683]
## Item Description
The view to display past and express care appointments as tabs on the homepage is live.

## Tasks

- [ ] Remove va_online_scheduling_past flag

- [ ] Remove va_online_scheduling_express_care flag

## Acceptance Criteria

- [ ]  No changes in experience

- [ ] Past appointments can be viewed in the homepage list
- [ ] Verify that Express care CTA is toggled by va_online_scheduling_express_care_new flag
