### ISSUE TITLE
Data Discovery for Github

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18680]
## Issue Description
We assume that we will be able to pull our Github data from Google's BigQuery datawarehouse. We need to determine which VSP and VFS product questions we'll be able to answer with the available data so that we can look into how to retrieve the data in a structured way and if we need to do more technical discovery into additional datasets.

We will link product questions to be solved by GH in this issue.

This is a follow up from https://github.com/department-of-veterans-affairs/va.gov-team/issues/18414

---
## Tasks
- [ ] Gather product questions for Github data
- [ ] Determine if we have data available for these questions
- [ ] Determine any blockers or dependencies for additional technical discovery based on these product questions

## Acceptance Criteria
- [ ] VSP understand what we can, can't, and _may_ be able to answer using the available Github data

**Comment by joanneesteban** [comment]
Dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/18813. Closing this ticket.
