### ISSUE TITLE
[FSR] Update content for the post-9/11 GI Bill waiver resolution verification

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18693]
## Issue Description
_If a Veteran submits an FSR for a waiver on a Post-9/11 GI Bill and it's granted, their remaining education benefits are reduced to resolve the debt. This may not be clear to our users, so we want to verify that they understand that their debt won't be completely waived if they choose this resolution._

---
## Tasks
- [ ] _Update the FSR's debt resolution UI to display a certification checkbox if the user has an education debt **and** requests a waiver ([UXPin for design + content](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/135678340/simulate/sitemap?mode=i))_
- [ ] _Ensure that other debt types don't display the checkbox when the user requests a waiver ([UXPin for comp + pen design](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/135678339/simulate/sitemap?mode=i))_

## Acceptance Criteria
- [ ] _FSR's UI has been updated and matches the linked designs_
- [ ] _UI has been reviewed by a BaM2 designer_

**Comment by rebeccawalsh** [comment]
Already completed
