### ISSUE TITLE
FSR - Unauthenticated Personal information design

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18699]
## Issue Description
For the unauthenticated FSR, we will need to make some adjustments to several pages that would normally be pre-filled for authenticated users. 

---
## Tasks
- [x] Alternative designs created for C1P1: Personal Information
- [x] Sync designs to UXPin
- [x] Create frontend ticket 

## Acceptance Criteria
- [x] Designs synced to UXPin and linked in this ticket
- [x] Frontend ticket created and linked in this ticket

**Comment by leahkeeler** [comment]
Hi y'll is this still in progress? it' sin the wrong pipeline

**Comment by rileyorr** [comment]
@leahkeeler this work wasn't originally slated for the sprint that just ended - I pulled it in to work on it this week because we finished our other tickets. I updated the milestone!

**Comment by rileyorr** [comment]
Added [the unauthenticated personal info designs](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136312480/simulate/no-panels?mode=i) to UXPin. I'll make a frontend ticket first thing tomorrow morning and move this ticket over to be validated!

**Comment by rileyorr** [comment]
Created a [frontend ticket encompassing the entire unauthenticated CH1 UI work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19833)
