### ISSUE TITLE
FSR - Unauthenticated Contact information designs

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18702]
## Issue Description
For the unauthenticated FSR, we will need to make some adjustments to several pages that would normally be pre-filled for authenticated users. 

---
## Tasks
- [x] Alternative designs created for C1P3: Contact information
- [x] Sync designs to UXPin
- [x] Create frontend ticket 

## Acceptance Criteria
- [x] Designs synced to UXPin and linked in this ticket
- [x] Frontend ticket created and linked in this ticket

**Comment by rileyorr** [comment]
Added [the unauthenticated contact info designs](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136312483/simulate/no-panels?mode=i) to UXPin. I split the phone + email contact info and the mailing address info into separate pages because it was way too many input fields on one screen. I'll make a frontend ticket first thing tomorrow morning and move this ticket over to be validated!

**Comment by rileyorr** [comment]
Added [the unauthenticated contact info designs](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136312483/simulate/no-panels?mode=i) to UXPin. I split the phone + email contact info and the mailing address info into separate pages because it was way too many input fields on one screen. I'll make a frontend ticket first thing tomorrow morning and move this ticket over to be validated!

**Comment by rileyorr** [comment]
Created a [frontend ticket encompassing the entire unauthenticated CH1 UI work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19833)
