### ISSUE TITLE
FSR - Unauthenticated Your VA benefits designs

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18703]
## Issue Description
For the unauthenticated FSR, we will need to make some adjustments to several pages that would normally be pre-filled for authenticated users. 

---
## Tasks
- [x] Alternative designs created for C2P3: Your VA benefits
- [x] Sync designs to UXPin
- [x] Create frontend ticket 

## Acceptance Criteria
- [x] Designs synced to UXPin and linked in this ticket
- [x] Frontend ticket created and linked in this ticket

**Comment by rileyorr** [comment]
Added two screens:
- [Asking if they get VA benefits ](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136384630/simulate/no-panels?mode=i)
- If yes, [asking the amounts they receive for comp + pen and edu](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136384631/simulate/no-panels?mode=i)
- [Frontend ticket added to the backlog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19862)
