### ISSUE TITLE
TUD FE: Update CircleCI configuration file

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#18719]
## Issue Description
The current CircleCI configuration file has the default setup of `hello-world` only.  The `.circleci/config.yml` file should be improved to reflect the updated requirements of unit tests, ECR/EKS hosting, and Dockerfile pointer.

---
## Tasks
- [x] Update the `.circleci/config.yml` to point towards the Dockerfile for production
- [x] Update any commands and tests that need to be run for the Dockerfile.prod
- [x] Add any environment variables as required

## Acceptance Criteria
- [x] Updated `.circleci/config.yml` successfully runs unit-tests for `vsp-test-user-dashboard`
- [x] Updated `.circleci/config.yml` successfully runs build for `vsp-test-user-dashboard`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Todo
- [x] Unblocked by the Filtering & Pagination bug
- [ ] Pull in latest from main and resolve any errors
- [ ] Get Docker container size to under 400Mb (currently 1.4Gb)
