### ISSUE TITLE
TUD FE: Figure out alternate hosting for UX/UI testing

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#18722]
## Issue Description
As per a [conversation](https://dsva.slack.com/archives/C019S3NSSAD/p1611070769013300) with Demian and I about the VSP Test User Dashboard hosting & SOCKS proxy setup.  The DevOps team is not ready for migrating from the Jenkins build to CircleCI along with the migration from ECR to EKS on AWS yet.

There was a decision to create an alternate hosting with FAKE data to test out functionality of the TUD Front-end.  This UX testing will be tested again once we have our SOCKS proxy hosting setup with REAL data.

---
## Tasks
- [x] Research and discovery the TUD FE app deployment
- [x] Ensure usability on the site / no obvious errors, etc.
- [ ] I have provided the Amanda (UX Designer) and Christine (PM) with the URL

## Acceptance Criteria
- [x] I can visit the TUD FE site
- [x] I do NOT see real data
- [x] I see no references to VA.gov or VSP

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Status
- Going to finish the deployment by noon. Should have a URL by then

**Comment by AGarcia-Clarity** [comment]
**Updated:**
@APorter-Clarity @christine-dillman Test User Dashboard site is here: https://tud-app.netlify.app/.

(This site removes all references to VA.gov & VSP).
