### ISSUE TITLE
TUD FE - Bug - Filtering and pagination bug

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#18723]
## Issue Description
This is a bug when navigating to a **nth** number page and trying to select filter additionally the page shows no uses because the page context is out of bounds (see attached image).  The test accounts found were **8**, the current page is **6**, and the table shows 'No test accounts found'.  This should redirect to the first page

![Screen Shot 2021-01-19 at 12.03.40 PM.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/9c610675-8c22-4e09-9ba7-8e9fac8f3f36)
---
## Tasks
- [ ] Redirect users to the first page when filters are changed

## Acceptance Criteria
- [ ] Redirects users to the first page when filters are changed!
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
