### ISSUE TITLE
Module generator rubocop issues

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#18726]
## Issue Description
After running the module generator, there are rubocop issues seen locally. Issues noted in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5682/files#r560355597)

---
## Tasks
- [ ] Review rubocop issues locally
- [ ] Make necessary generator changes
- [ ] Ensure specs pass
