### ISSUE TITLE
Transition from Type Ahead POC to Type Ahead 1.0

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#18734]
## Description

As a product team we have just completed a POC for the Typeahead experience on VA.gov (5% of all va.gov users). Leveraging the experiences and data from 5% of the VA audience the team must now define next steps and outline plan to migrate to full production and future iterations (Type Ahead 1.0 - 100%)  This issue outlines the steps and information needed to make informed decisions and reach consensus regarding next steps.

**Type Ahead Releases:**
POC - 5% of all users to va.gov received type ahead suggestions
1.0 - 100% of all users to va.gov received type ahead suggestions and some enhancements to improve experience

## Background/Context/Resources

[Type Ahead POC Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8896)
[Type Ahead 1.0 Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17558)

---

## Tasks
**Style Guide / Best Practices Definition**
- [x] Define Style Guide for Type Ahead on VA.gov - aligned with best practices #18552
- [x] Discuss [style guide recommendations ](https://docs.google.com/spreadsheets/d/1wykvDgFAOLIYIA-ySz8Hjtmo74Qih884cjvFndrFgh4/edit#gid=0)with team 

**POC Summary:** 
- [ ] Examine data collected during POC + summarize findings (Denise/ John) #19693
- [x] Confirm 1.0 Release Definition with John

## Definition of Done

- [ ] Extracted a set of next steps from POC for Type Ahead by defining improvements that can be integrated into roadmap
- [ ] Solidified plan to roll typeahead out to remaining VA audience. 

---

**1.0 Release Definition**
- [ ] Q1 Release - Targeting Release by March 1
- [ ] Release to 100% of Users #19368 
- [ ] Enhancements including:
- Canned Suggestions for top terms #17844
- Ordering suggestions based on character length #19369 
- Styling Improvements to change suggested characters to be the bolded portion of the suggestion #19370 
- Styling improvement to align typed search term in the input bar with drop down suggestions (also on #19370)

---

## Type Ahead Enhancements - Stretch goals for Typeahead 1.0 
- Expand acronym using VA acronym list to improve clarity
- Remove State references from suggestions unless typed directly from user
- Add typeahead to results page refinement search
- Hover over suggestions fill out search input
- Improving Suggestion Quality 
    - a)Enhance Fault Tolerance for spelling mistakes (eg “goverment”)
    - b)Don't allow plural/singular terms in same suggestion set
    - c)Explore ways to improve the algorithm search.gov uses to establish suggestions (decrease weighting of frequently searched for terms, establish a blacklist to remove terms that we don't want to appear)

**Comment by denisecoveyduc** [comment]
## Type Ahead Enhancements  and Changes for Consideration

- [ ] Establish canned suggestions for top 50 search terms
- [ ] Expand acronym using VA acronym list to improve clarity
- [ ] Enhance Fault Tolerance for spelling mistakes (eg “goverment”)
- [ ] [search.gov] Explore ways to improve the algorithm search.gov uses to establish suggestions (decrease weighting of frequently searched for terms, establish a blacklist to remove terms that we don't want to appear)

**Comment by denisecoveyduc** [comment]
Data analysis has been deferred (GH#19693) as we wait for the analytics team to complete dashboard in #18785 which is expected to be completed by February 16, 2020. Typeahead1.0 scope has been defined and added to the epic #17558
