### ISSUE TITLE
Document Domo Dashboards impacted by the GA/BQ Scrub

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18748]
## Issue Description
In order to understand which VFS dashboards were impacted by the GA & BQ scrub, we need to audit and document which dashboards no longer have data or have deteriorated data.

---
## Tasks
- [ ] Audit & document the dashboards that were impacted by the GA/BQ scrub
- [ ] Audit & document the charts within the dashboards that were impacted
- [ ] _Stretch_ Determine & document what will need to be done to fix those charts and dashboards

## Acceptance Criteria
- [ ] VSP Analytics & Insights understands what will need to be done to clean up Domo dashboards impacted by the GA/BQ scrub

**Comment by joanneesteban** [comment]
Archived GA dashboards - can probably decommission.

**Comment by JasonTheBearded** [comment]
DOMO Dashboards impacted by Scrub:

- KPIs - Facility Locator

**Comment by bsmartin-ep** [comment]
@joanneesteban / @JasonTheBearded -

Here is a list of all DOMO datasets "affected" by the GA data deletion.  By "affected", I mean they have an `Event Action` column and are direct Google Analytics connector datasets (and not BigQuery).

Outside of the first one - which is the retired, but still visible original COVID dashboard - these are all GA datasets that contain zero cards, are on archived pages, or have not been updated in several months.

I don't see any immediate fixes necessary but would recommend eventually removing these datasets (and the archived dashboards they are attached to).

------

### Still visible.....

#### COVID FAQ Page - Jumplinks
https://va-gov.domo.com/datasources/98e7c1b6-1ec2-4cd2-afc0-18d1a4eac9f2/details/overview
"On This Page Section - Jumplink clicks" card on retired COVID page is still visible


--------------------------

### Broken, but no one will notice...


#### [Custom] Reporting Request - Charles Worthington - Various Events 
https://va-gov.domo.com/datasources/92ee2e9b-bbe9-45a1-b166-f0148d34be2c/details/overview
All archived or not in use.  Updated 7 months ago. 

#### [Partitioned] All VAOS Events
https://va-gov.domo.com/datasources/5f392291-b59c-4ded-ba41-db9e1b321df5/details/overview
All Archived or not in use

#### [Partitioned] BAM2 Medical Device events
https://va-gov.domo.com/datasources/446144d4-eda9-4094-b319-54e7ee4999ef/details/overview
All archived or not in use

#### [Partitioned] Caregivers events (10-10CG)
https://va-gov.domo.com/datasources/783871dd-945e-4091-b1f4-7f00f4c3b72f/details/overview
No cards

#### [Partitioned] COVID Chatbot Outbound Link and Resource Link Clicks 
https://va-gov.domo.com/datasources/0561e5ff-127b-427f-81a1-491e6fc7e76a/details/overview
All archived or not in use

#### [Partitioned] COVID FAQ - No FAQ Question Interactions 
https://va-gov.domo.com/datasources/55ed5c07-74e0-47fe-8e5f-1a9b71364b47/details/overview
No cards

#### [Partitioned] COVID FAQ Page - Jumplinks
https://va-gov.domo.com/datasources/aac7dde1-4f47-4652-8b10-8d097e5d7cb9/details/overview
No cards

#### [Partitioned] COVID FAQ Page Scroll Depth
https://va-gov.domo.com/datasources/2d1754c8-4f11-4624-b02d-935a3ca43d56/details/overview
No cards

#### [Partitioned] COVID Navigation Events (Apr 21 - current)
https://va-gov.domo.com/datasources/72cfbda1-d120-4e48-ae07-f7c92fa1a62a/details/overview
No cards.  1.6M rows!!!!!

#### [Partitioned] COVID Screening Tool Metrics
https://va-gov.domo.com/datasources/6b31f414-d723-45af-8b92-0ebe18527d95/details/overview
No cards

#### [Partitioned] ebenefits.va.gov All Events
https://va-gov.domo.com/datasources/bc2d3b24-c122-4a57-b4fa-4a86ed1fd426/details/overview
All archived or not in use

#### All Navigation Events
https://va-gov.domo.com/datasources/06f9921f-145a-4358-898f-e33cdfdf64a1/details/overview
1 un-paged card.  > 8 months since last run.  

#### Claims View Details Only
https://va-gov.domo.com/datasources/d36dd4e7-04c7-4ed9-84c4-ddbc2d584357/details/overview
All archived or not in use

#### COVID FAQ Page Scroll Depth
https://va-gov.domo.com/datasources/6a20750e-38cf-4273-95bb-2c3324bfc967/details/overview
All archived.

#### Education Modernized - Event Tracking Submissions
https://va-gov.domo.com/datasources/1a2a796c-a298-4d27-9e13-e447ae1306cb/details/overview
No cards

#### Navigation - COVID [With FAQ CD]
https://va-gov.domo.com/datasources/c377bd10-44c7-424a-a227-9684addcf13b/details/overview
All archived or not in use

#### Va.gov - WBC Modernized & All Website Data - All VEO Relevant Events (2018-present)
https://va-gov.domo.com/datasources/7d8594eb-8af2-4db8-95e1-2fcb14cea2b5/details/overview
No cards

#### VEO - Relevant Events by Date
https://va-gov.domo.com/datasources/a91c6b25-974f-43fb-bffe-d4b3aa64122c/details/overview
All archived or not in use

#### Warning Alert Boxes Clicks
https://va-gov.domo.com/datasources/0cbed02e-4702-40aa-9810-3305552c79dd/details/overview
No cards
