### ISSUE TITLE
L Nav update for VAMC Pittsburgh

### ISSUE THREAD

**Issue by andrewlewandowski** [department-of-veterans-affairs/va.gov-team#1874]
## High Level User Story
As a user on a content page on VA.gov, I need better on-page and section navigation and menus so I can get to all content and tools in 1-2 clicks/taps.

We will initially redesign and build our new navigation and menu components and patterns for the va.gov/pittsburgh-health-care product. We will do usability testing on staging.va.gov/pittsburgh-health-care.

## Hypothesis/(es)
**If** we redesign our page navigation and menus **then** we expect user satisfaction scores will increase because users can get to all content and tools in just 1-2 clicks.

## Goals
* Get users to all content and tools in just 1-2 clicks/taps
* Allow users to "preview" all content pages in a section of content
* Only allow for four levels of menu/page publishing:
1. Spoke (no content; use as a label, and do not publish in URL)
2. Parent
3. Child
4. Grandchild
* Optimize for mobile navigation and scrolling
* Consider making headings, subheadings, and sections sticky for better wayfinding

## Objectives
Objective 3: Deliver a usable and accessible experience
KEY RESULT: By April 30, Veterans can access top tasks and most frequently visited Pittsburgh VAMC website content within 4 clicks or less  from the Left Nav. 

## Definition of done
The following milestones have been successfully completed (or determined to be unnecessary for this work)
- [x] Project Kickoff (N/A: this work was already mid-flight when collaboration process rolled out)
- [x] Design Intent Collaboration (N/A: this work was already mid-flight when collaboration process rolled out)
- [x] Usability Testing Prep [#7033]
- [x] Research Plan Review (N/A: this work was already mid-flight when collaboration process rolled out)
- [x] Information Architecture (IA) Request (N/A due to nature of work)
- [x] Analytics Request [#7336]
- [ ] Contact Center Review 
- [ ] Staging Review
- [x] Privacy and Security Review (N/A due to nature of work)
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in

**Comment by ncksllvn** [comment]
@kelsonic 
**Page** - https://staging.va.gov/pittsburgh-health-care/
**Design** - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/page-nav/design/VA-gov-on-page-nav-MASTER.pdf

**Comment by ncksllvn** [comment]
@andrewlewandowski @Karak888 - I wrote a ticket specifically for implementing the first iteration of Pittsburgh sidebar redesign - https://github.com/department-of-veterans-affairs/va.gov-team/issues/2278. @kelsonic is tackling that work.

Side question - should this Epic be connected (maybe as a sub-Epic?) to this ticket, `New VA.gov primary header/footer, navigation, and menus`, https://github.com/department-of-veterans-affairs/va.gov-team/issues/1875?

**Comment by Karak888** [comment]
Thanks @ncksllvn ! I will be organizing and prioritizing this work today and work with Jen on prioritization.  much appreciated!

**Comment by jenniferlee-dsva** [comment]
Thanks @ncksllvn and @Karak888 . Would love to get the interaction on the Pittsburgh nav built this sprint, as we may have a dependency/blocker coming up in the next sprint.

**Comment by Karak888** [comment]
@ncksllvn looks like we can probably get @kelsonic back on this one?  thanks

**Comment by ncksllvn** [comment]
@Karak888 This ticket is an Epic, so @kelsonic and I created an associated ticket at https://github.com/department-of-veterans-affairs/va.gov-team/issues/2278 which @kelsonic has already picked up. That ticket aligns with what @jenniferlee-dsva is describing.

**Comment by jenniferlee-dsva** [comment]
@AkucherGCIO - Not sure if for the upcoming sprint or the next (there are a couple of things incoming we need to consider) - could you work with @rtwell to create ticket/s related to this epic to implement updated nav designs and ux behaviors for VAMC Pittsburgh left nav? (This is not urgent - just want to have tickets ready  to pull into grooming.)

The updates will be based on Kevin Hoffman's research findings: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/left-nav/research-findings.md

1/ Remove Home in the Pittsburgh VAMC breadcrumb.
2/ [Nav design updates to be provided by Ryan]
3/ [Nav interaction/behavior write up to be provided by Ryan]
4/ [Anything else I have missed :-) ]

FE engineering implementation will be Kelson + engineer on VAMC team. @kelsonic has knowledge of this from his work on the usability sessions, so, per convo with @davidconlon , Kelson, and Ryan, Kelson will do a knowledge transfer/pair code with VAMC's engineer to get this completed.

**Comment by jenstrickland** [comment]
Related:

- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/header-footer-and-navigation/page-nav

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/left-nav/research-findings.md

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/3413#issuecomment-590518022

**Comment by AkucherGCIO** [comment]
@rtwell - Ryan, I would like to schedule sometime today, March.2nd or March.3rd for us to discuss the tickets that need to be created for this effort.  I will reach out to you in Slack and find some time for us.

**Comment by mmiddaugh** [comment]
@jenniferlee-dsva @AkucherGCIO 
My understanding from  @davidconlon is that the Facilities team will be handling the front end changes for the Left Nav (not the VAMC team). I have a meeting with Ryan, Kelson, Dave and Gibran to discuss the work that is pending scheduled for this Thursday. Please let me know if I am confused about the responsibility for this work. Thanks!

**Comment by AkucherGCIO** [comment]
@mmiddaugh - As this is effort by Facility Locator team, please meet with @rtwell about the tickets needed for the effort.  If you need me to attend as well, feel free to add me to that meeting as well.

**Comment by rtwell** [comment]
ok so i dropped designs into Zeplin and invited @brangi and @kelsonic — all can view here: https://zpl.io/2jxORgp

the big changes:
1) remove the duplicative pages
2) on click, the parent page (e.g. Locations) **both** goes to the Locations page **and** reveals all of its children and grand children
3) grand children have a vertical rule
4) hover/active/on-click states included
5) for focus state, i assume we will continue to use our focus from the rest of va.gov

Let me know if anyone has any questions

including PNGs here for posterity:

![image](https://user-images.githubusercontent.com/12564977/76093107-71f38180-5f8e-11ea-9d9e-fa2a8b68aafe.png)

![image](https://user-images.githubusercontent.com/12564977/76093123-761f9f00-5f8e-11ea-9718-f1ac35801203.png)

**Comment by jenstrickland** [comment]
@rtwell bullet #2 above - would you tell me more about that link both going to another page and opening the hidden options beneath it?

**Comment by rtwell** [comment]
@jenstrickland sure! it works exactly like our current nav does now, save one—onclick, the user is taken to the parent page, and when that page loads the children (and what's new here) and grandchildren are revealed. If you look at the States png I included, from left to right, that would be the action (user hovers/tabs, user clicks/enters, user goes to Locations page, with the children/grandchildren revealed). does that help?

**Comment by jenstrickland** [comment]
@rtwell — That helps! It sounds like it clearly addresses the objectives quite well.

**Comment by kevwalsh** [comment]
@mmiddaugh @MickinSahni @jenniferlee-dsva 

 I don't know what the timeline is for this epic, but if it's going to be awhile: 

Can the new left nav be rolled back from dev and staging (eg master?) and moved to a review environment? It occasionally messes up our automated tests and manual QA for CMS tasks. For example, the fact that some pages no longer have left sidebars at all (Events, News releases, etc) trips up QA.

**Comment by mmiddaugh** [comment]
@rtwell can you please attach the mobile designs to this issue?

**Comment by rtwell** [comment]
## menu closed on mobile
![image](https://user-images.githubusercontent.com/12564977/77205604-980b3c80-6acb-11ea-88f9-be02476f7aa4.png)

## menu open
![image](https://user-images.githubusercontent.com/12564977/77205661-b2451a80-6acb-11ea-8241-b7dddcfb5c0f.png)

## menu open, in a section
![image](https://user-images.githubusercontent.com/12564977/77205672-b709ce80-6acb-11ea-9823-a667a17b665e.png)
