### ISSUE TITLE
[FSR] Pre-usability staging review

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18757]
## Issue Description
_We need to take a pass through the form's UI in staging to make sure the main functionality works prior to conducting the FSR's usability study._

---
## Tasks
- [x] _Review the entire FSR in staging and document updates that need to happen prior to usability_
- [x] _Create a ticket for frontend dev team to implement the updates_

## Acceptance Criteria
- [x] _Final document of necessary changes has been attached to this ticket_
- [x] _A ticket has been created for devs to incorporate the changes and has been linked to this ticket_

**Comment by rebeccawalsh** [comment]
I've updated the [document here](https://docs.google.com/document/d/1K8I1mYmCgJdHUxt62drlOqqKw1s6Mb80AaigbsN7k0A/edit#) with all of the changes we found as we reviewed staging, and created the following tickets:

Design
----
- [Update list loop error state design](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19030)
- [Update installment contracts and other debts radios to be inputs](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19037)

Frontend
---
- [Update FSR debt card statuses to match portal](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19067)
- [Hardcode contact information for usability](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19066)
- [Fix list loop cards so they do not open when stepping back](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19068)
- [Update employment history questions so that people who haven't been employed are not asked twice](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19069)
- [Add waiver progressive disclosure checkbox](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18693)
- [Update written statement screen with new design and content](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/19046)

**Comment by rileyorr** [comment]
Yay for fixing things! I also added a few tickets for bugs I found in the FSR:

- [List loop cancel buttons aren't working](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18964)
- [Selecting the default list loop card's 'Save' button without inputting values is breaking the form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18974)
- [Some progressive disclosures are throwing errors for subsequent questions if the previous question threw an error](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19071)

**Comment by leahkeeler** [comment]
Do y'll want to close this or keep open for potential regression issues
