### ISSUE TITLE
[Content-Review] Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA Asheville health care [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18758]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Asheville Devshop Instance](http://ashevillehealthcare.web.demo.ci.cms.va.gov/asheville-health-care/health-services/)
[VISN-6 Internal Review Folder](https://drive.google.com/drive/folders/1VV3WPyTJRccsay82aL-Roe3VbSUwGEkJ)
[Review template for review](https://drive.google.com/drive/folders/18Oo5eoy4yn0LyTtQ3OLdNgGqN1FUof81)

## Tasks
_Complete content review of system pages from a reader's point of view and make corrections in Production (prod.cms.va.gov):
**Use Analytics Review document to see changes already implemented**
* Review NOT needed (Double check if there is content on Jobs/Intern/Volunteer)
- [X] Location Listing Page 
- [X] History    
- [x] Internship and Fellowship 
- [x] Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x] System Page 
- [x] Health Services Listing Page (Health service on this page only)
- [x] About us Page 
- [x] Mission-Vision 
- [x] Leadership Listing Page 
- [x] Work with Us Page 
- [x] Jobs and Careers
- [x] Policies Page 
- [x] Contact us 
 
* Facility Pages - review intro, Plan for your visit, if any. (DO Not review health services this is at System level only)
- [x] 637	Charles George Department of Veterans Affairs Medical Center
- [x] 637GA	Franklin VA Clinic
- [x] 637GB	Rutherford County VA Clinic
- [x] 637GC	Hickory VA Clinic
* Observe and report (Correct any spelling errors)
- [x] Performance Page
- [x] Make an Appointment
- [x] Register-for-Care
- [x] Billing
- [x] Contact-us		
- [x] Dav-vans
- [x] Medical-Records
- [x] Operational Status
- [x] Pharmacy
- [x] Caregiver
- [x] Homeless
- [x] LGBT
- [x] Mental
- [x] Minority
- [x] Patient
- [x] Returning Service member
- [x] Suicide prevent
- [x] Women-vet
- [x] Campus Map
- [x] Chaplain Services
- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [x] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.

**Comment by larrywest52** [comment]
Reviewed all pages, revised where possible, and noted changes made and issues we still need to address.
