### ISSUE TITLE
Design of health care landing screen 

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18764]
# User Story
As a user of VA mobile app, I want to be able to navigate to both health care features - Appointments and Secure Messaging - from the bottom navigation.

# Context
Right now, the Appointments navigation item opens the Appointments landing screen. We need to create a screen that users will land on when they select Health care that allows them to navigate to both Appointments and Secure Messaging.

# Tasks
- [ ] Determine content, actions, and copy on landing screen 
- [ ] UI design for landing screen 
- [ ] Update Design Library file with any new components

**Comment by bridgethapner** [comment]
Moving this up because it's part of the prototype @drjecker is working on for Secure Messaging. Jen - if you feel like this ticket is not helpful or accounted for elsewhere, feel free to close!
