### ISSUE TITLE
[Content-Review] Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA Durham health care [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18767]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Durham Devshop Instance](http://durhamhealthcare.web.demo.ci.cms.va.gov/durham-health-care/)
[VISN-6 Internal Review Folder](https://drive.google.com/drive/folders/1VV3WPyTJRccsay82aL-Roe3VbSUwGEkJ)
[Review template for review](https://drive.google.com/drive/folders/18Oo5eoy4yn0LyTtQ3OLdNgGqN1FUof81)

## Tasks
_Complete content review of system pages from a reader's point of view and make corrections in Production (prod.cms.va.gov):
**Use Analytics Review document to see changes already implemented**
* Review NOT needed (Double check if there is content on Jobs/Intern/Volunteer)
- [x] Location Listing Page 
- [x] History    
- [x] Internship and Fellowship 
- [x] Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x] System Page 
- [x] Health Services Listing Page (Health service on this page only)
- [x] About us Page 
- [x] Mission-Vision 
- [x] Leadership Listing Page 
- [x] Work with Us Page 
- [x] Jobs and Careers
- [x] Policies Page 
- [x] Contact us 
 
* Facility Pages - review intro, Plan for your visit, if any. (DO Not review health services this is at System level only)
- [x] 558	Durham VA Medical Center
- [x] 558GA	Greenville VA Clinic
- [x] 558GB	Raleigh VA Clinic
- [x] 558GC	Morehead City VA Clinic
- [x] 558GD	Durham County VA Clinic
- [x] 558GE	Hillandale Road VA Clinic
- [x] 558GF	Wake County VA Clinic
- [x] 558GG	Raleigh III VA Clinic
- [x] 558QA	Brier Creek VA Clinic

* Observe and report (Correct any spelling errors)
- [x] Performance Page
- [x] Make an Appointment
- [x] Register-for-Care
- [x] Billing
- [x] Contact-us		
- [x] Dav-vans
- [x] Medical-Records
- [ ] Operational Status
- [x] Pharmacy
- [x] Caregiver
- [x] Homeless
- [x] LGBT
- [x] Mental
- [x] Minority
- [x] Patient
- [x] Returning Service member
- [x] Suicide prevent
- [x] Women-vet
- [x] Campus Map
- [x] Chaplain Services
- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.
