### ISSUE TITLE
FL error message design (aligned with design system)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18773]
## User Story or Problem Statement
As a Veteran using a screenreader to search on Facility Locator, I need to hear errors announced relative to the field where the error occurs so I know how to resolve the error.

The Facility Locator is not currently using the design system for form field errors. and per Josh, current error messages are not 508 compliant. 

❗️ Must for if the feedback must be applied
## Details
- The error message itself is not specific. Screen reader users won't know what exactly is the problem if the problem is called "this" instead of saying "Fill in a city, state, or postal code."
- Errors are tooltips instead of being persistent within the label of the field itself.

https://user-images.githubusercontent.com/14154792/103782570-9f251c00-5005-11eb-955d-8a1a45420f50.mov

## Design system 
- The form field and its corresponding are wrapped in a container with a class name of usa-input-error. This will provide a thick border and padding to visual indicate an error message to users who might have difficulty perceiving contrast. It also changes the border of the input to red as a secondary indicator.
- An error message is placed between the label and the form field.
- The form field receives an aria-describedby attribute that references the id of the error message. (Error has context, such as "Error, select an item from the Facility type list")
- Prepending Error to error messages alerts screen screen readers clearly that an error exists.
- Error message should be persistent
- Error message should appear in the field itself (not as tool tip)

## Tasks
Create spec for error message aligned with design system to handle the following scenarios 
- If a Veteran clicks "Search" before City, state or zip field is populated 
- If a Veteran clicks "Search" before Facility type has been selected 
- If a Veteran clicks "Search" before Service type field is populated (when Facility type = Community providers (in VA's network))

## Acceptance Criteria
- [ ] Specs for error messages are ready for front end implementation

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate to #18351
