### ISSUE TITLE
Development for email template 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18776]
## Issue Description
Need to create email template based on pattern defined by Crystabel. 

---
## Tasks
- [ ] research on what needs to be built
- [ ] building out email template based on design
- [ ] launch/ on design.va.gov 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by cvalarida** [comment]
Discovered we don't need this after all. :tada:
