### ISSUE TITLE
[FE][SPIKE] Snapshot PDF R&D

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18779]
Because need to store a PFD of answers on submission, where can we store the data? 

## User Stories
As veteran, 
I should be able to download a PDF of my response at the time I submitted my answers
So that I can view my past responses.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
This is the architecture planning of how to we are doing PDFs. The team already has a loose idea, this is syncing and documenting how we plan on fulfilling the requirements. 

## Considerations. 
- Stored in a secure system
- Should recall the information  (demographics, appointment, etc) that was correct at the time of submission. 
- Document retrieval should be timely, and performant. 

## Questions to Answer
- [x] When are we generating the PDF? 
- [x] Where are we storing the data for the PDF?
- [x] How are we letting the users download the PDF? 
- [x] What does FHIR give us for document storage?

## Tasks
- [ ] Engineering team will meet around current ideas and implementations
- [ ] Meet up with the whole team to ensure we fulfill all current use cases
- [ ] document the findings

## Acceptance Criteria
- [ ] Questions Answers
- [ ] The team is happy with the plan.

**Comment by mdewey** [comment]
Document here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/printing-questionnaire/snapshot.md#L47

**Comment by mdewey** [comment]
Blockers: We have a few outstanding questions. Some for Lighthouse and some for Stephen to follow up on.
