### ISSUE TITLE
Ensure blobby content is sent to DevShop and Prod

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18786]
## Issue Description
Only blobby content should be published to both Prod and Devshop so that the changes made by the VAMC upgrade team are visible and broken links can be identified prior to dual-state roll out. 

There is currently "if" logic that sends field data to DevShop. 

---
## Tasks
- [ ] Remove "if" statement

## Acceptance Criteria
- [ ] Blobby content is published to both Prod and Devshop
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
We still need a way to review the structured content on both staging and dev, so how about we change the logic from "if the buildtype is not production, show structured content" to "if the buildtype is staging or dev, show structured content"?

This will only work if the buildtype for DevShop/Tugboat is something other than dev or staging.

@indytechcook - what is the buildtype for DevShop/Tugboat instances?

**Comment by indytechcook** [comment]
Our testing/demo build scripts use `vagovdev`.  This is easy to change if we come up with something better.

Here is the GraphQL based one:

```
        "va:web:build": [
            "drush state-set va_gov.build va.web_build_stats TRUE -y",
            "rm -rf docroot/vendor/va-gov/web/build/vagovdev",
            "cd web && echo \"Downloading assets for vets-website ref $(git rev-parse --verify HEAD)\" ",
            "cd web && NODE_ENV=production yarn build:content --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov --asset-source=$(git rev-parse --verify HEAD)",
            "echo 'Replace s3 address with local in generated files'",
            "find ./docroot/vendor/va-gov/web/build/vagovdev/generated -type f -print0 | xargs -0 sed -i \"s/https:\\/\\/dev-va-gov-assets\\.s3-us-gov-west-1\\.amazonaws\\.com//g\" ",
            "drush state-set va_gov.build va.web_build_stats FALSE -y"
        ],
```

Here is the Transformer one

```
        "va:web:build:export": [
            "drush state-set va_gov.build va.web_build_stats TRUE -y",
            "rm -rf docroot/vendor/va-gov/web/build/vagovdev",
            "cd web && echo \"Building assets for vets-website ref $(git rev-parse --verify HEAD)\" ",
            "cd web && NODE_ENV=production yarn build:content --use-cms-export --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov --asset-source=$(git rev-parse --verify HEAD)",
            "echo 'Replace s3 address with local in generated files'",
            "find ./docroot/vendor/va-gov/web/build/vagovdev/generated -type f -print0 | xargs -0 sed -i \"s/https:\\/\\/dev-va-gov-assets\\.s3-us-gov-west-1\\.amazonaws\\.com//g\" ",
            "drush state-set va_gov.build va.web_build_stats FALSE -y"
        ],
```
