### ISSUE TITLE
[UNPLANNED] Fix 686 Submission PDF Job

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#18789]
## Background
The PDF for the 686/674 job submission is not being generated properly and needs to be fixed.  During testing we discovered that an error is occurring when the PDF job is being called, which is causing the PDF generation to fail.  

## Tasks
- [x] Determine what broke the PDF job
- [x] Update the PDF job with the necessary fix 

## Acceptance Criteria
- [x] A PR has been requested for merging
