### ISSUE TITLE
Feature Definition: Claims File Upload (Refinements for App Stores Launch)

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18795]
# User Story
As a designer, product manager, or engineer on VA mobile app, I want to improve the MVP Claims File Upload feature before the app store release so that is easier to use, more accessible, and best meets the needs of Veterans who have file requests on their VA claims.

# Tasks
- [x] Discovery - can we better understand how this feature gets used on the web today?
- [x] Identify areas for UI/UX and accessibility improvement
- [x] Write design & engineering user stories for further implementation work 

## Links
https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614706523689/cc3dee234151084674ffa8b2005f8cfe297f4665

# Punch list for Claim File Upload updates in priority order 

1.  Error states for upload"more than 50mb" "wrong type of file uploaded" **App Store**
2.  For File upload flow, only offer file upload option with eliminating"take a photo" option  **App Store**
3. “Take photos” button copy to “Take or select photos” **App Store**
4.  adding the option to select multiple photos from one’s camera roll once it’s open **Post-App Store**
5. Option to remove a photo or several photos at same time  **Post-App Store**
6. Change button naming for camera flow "Camera roll" to "Photo gallery"  **App Store**
7. add content language for accessibility upload - "this isn't accessible just yet; you may want to use web or desktop to upload photo"  **App Store**
8. Add accordion for long text within  file uploads **Post-App Store**
9. Include a drop down with ideal file types **Post-App Store**
10. FAQ or how to upload content narrative  **Post-App Store**
11. Update title to match web  **Post-App Store**

**Comment by bridgethapner** [comment]
One idea: When selecting photos from the camera roll, enable the ability to select multiple at a time rather than needing to tap back into "Select photo" each time

A question that came up in a research session today: Why limit photos to 10? P4 found the feature useful, and also commented on finding the help text "please select up to 10 photos" helpful, citing that he'd want to know about a limit before hitting it & thought using a computer made more sense for a big file. However, he expressed an interest in wanting to upload _more_ photos via mobile.

**Comment by lexicalninja** [comment]
One thing I noticed was that the first screen once a user selects Select a File or Take Photos, the next screen just says choose a file for Request 2 or whatever. I think it might help to use an info dropdown with the description here as a bailout for the user in case they need to double check what the parameters are.

Other items that were brought up in the demo included copy that indicated that you can only upload one file per tracked item, as well as adding the ability to remove one picture from the image list when following the take photos path.

**Comment by bessgreen** [comment]
Additional thoughts: 

1. Refining error messaging to be specific about what went wrong, e.g.: 
- "Your **.png** file could not be uploaded because it is not an accepted file type. Acceptable file types include .pdf (unlocked), gif, jpeg, jpg, bmp, txt." 
- "Your **62 MB file** could not be uploaded because it exceeds the 50 MB limit." 

2. Enabling multiple file uploads, rather than limiting to 1

3. Stronger visual updates to the File Request screen after a user has uploaded a file (confirmation icon, icon to indicate a "file", etc.)

4. File usage status bar that shows how close they are to the 50 MB limit

5. After a user has fulfilled all of their requests, clearer messaging to inform them that they will not be able to return to the File Request detail screen. (Not sure if there is an alternate avenue that allows them to revisit this page at any point in the future.... can their file requests + uploads be part of their Claim history that they can revisit in the Claim Details page?)

**Comment by bridgethapner** [comment]
Yesss love these thoughts!!! Love the idea of the specific error messaging. 

A couple more thoughts: 

- The initial File Upload page could have just 1 CTA saying "upload", then the next screen could have CTAs for "Select a file" or "Select photos". Maybe, at this step, we could offer more info about each option to help people choose what's right for them.
- We should change the copy to "Select photos" rather than "Take photos" since there's an option to select from the camera roll. 
- What if we turned off the ability to select from the camera roll on "Select a file"? Do we need if, if we have that option in "Select photos"?

**Comment by tmulrooney-va** [comment]
A few thoughts for the feature:

- Add a clearer notification that the file was uploaded, possibly an animation and a checkbox
- Ability to add additional files when uploading, similar to photos.
- Ability to delete a file once it has been uploaded in case it's the wrong one
- Provide a notification and more information that the file is moving through to the processor flow and cannot be updated
- "Take photo" does not clearly explain that the user can also upload the photo
- Add the ability to delete photos once uploaded
- Explain the confirmation process and next steps

**Comment by bridgethapner** [comment]
**A couple more things that came out of testing:** 

- People wanted to see estimates for file processing _after_ upload via the app - is there any estimated processing time we can offer after upload?
- Consider including FAQs about claims processing

**Comment by bridgethapner** [comment]
@ayushchak @lexicalninja We are blocked on UX design for this ticket for now - we need a staging user with file requests to fully audit the flows for both the 'Select a File' and 'Take Photos' flows & to audit the A11y criteria included in the build.

**Comment by msmanak** [comment]
I will be revisiting this ticket next week but I wanted to follow up with @bessgreen @jmarchi on edge detection decision for the uploads. For accessibility purpose, I am wondering how we would get around VoiceOver if we do not have this feature. Do we know how many engineering hours we'd need to add this? 

My other solution is to have updated content (*provided by VA content team) that reflects that if we cannot add this before the code freeze.
