### ISSUE TITLE
Update 2 links on Life insurance hub landing page to point to new R&S pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#18794]
## Issue Description
Now that we have life insurance articles in R&S we need to update two links on the life insurance hub landing page that currently point to legacy pages. 

The two links that need to change are:
**How much life insurance do I need?
Medical conditions that may make you uninsurable**

New links should point to:
**Deciding how much life insurance to get
Life insurance if you have preexisting conditions**

We need teaser text written to go along with this.

Page to work on: prod.cms.va.gov/life-insurance

## Tasks
- [ ] Update links on LI hub landing page
- [ ] Create teaser text for new links
- [ ] Review and publish

## Acceptance Criteria
- [ ] R&S links now appear on LI hub landing page

**Comment by RLHecht** [comment]
Closing ticket. This work was done as part of #17646
