### ISSUE TITLE
[Tech Debt] - 686c - Check cypress test integrity against migration guide

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#18805]
## Description
The testing team recently rolled out an upgrade to Cypress, bumping the package version from 4.8 to 6.2.1. Though there are no breaking changes, [it was recommended](https://dsva.slack.com/archives/CE4304QPK/p1610486583177300) to go through [this migration guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-upgrade-guide.md) in preparation for Cypress upgrades that **would** introduce breaking changes. 

To ensure the 686c cypress tests do not break the build pipeline in Jenkins, we need to go through the guide and make any necessary updates to deprecated methods. 

## Considerations
- Migration Guide - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-upgrade-guide.md

## Tasks
- [ ] Perform an audit of all 686c-674 cypress tests, update any methods recommended by the migration guide

## Definition of Done
- [ ] Tests run properly
- [ ] Pull request submitted
