### ISSUE TITLE
[Cheetah MVP] Add second appointment page info

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18801]
## Issue Description
Replace second calendar page with new plan for second appointment page.

---

## Tasks
- [ ] Add return for 2nd appointment page after the calendar

- [ ] Remove 2nd calendar page

- [ ] Format dates based on 1st calendar selection

## Acceptance Criteria
- [ ] All changes are behind va_online_scheduling_cheetah feature flag

- [ ] On page load, "Can I choose which vaccine I will get?" additional info is collapsed

- [ ] On click of "Can I choose which vaccine I will get?" additional info, expand with copy

- [ ] CONTENT - Header, body, and additional info copy matches designs, with the following elements as variables:
  - {selected facility} 
  - {selected date}
  - Moderna {selected date + 28 days}
  -  Pfizer {selected date + 21 days}

- [ ] DESIGN - Specs match designs: https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/aggrY5D#Inspector
**Default**
![Plan ahead@2x.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/904f0375-09c6-40b7-9abd-668810e346f3)

**Expanded**
![Plan ahead - Addl info@2x.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/18453b8e-be7a-4198-9772-50601254c605)
