### ISSUE TITLE
[Cheetah MVP] Remove conditional CTA

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18800]
## Issue Description
Update homepage CTA section with applicable flow copy.

## Tasks
- [ ] Remove existing conditional year logic

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] If feature flag is on, user can see CTA
- [ ] CONTENT - Section heading, description, and CTA label match copy in designs
- [ ] DESIGN - Specs match the designs https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/zxxw92M#Inspector
![18800 scope.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/d61d2446-1a45-4651-8150-0c44a105f191)

**Comment by laurenernest** [comment]
@jenniemc @jbalboni I'm not seeing the changes for the AC below reflected in Staging. Can you double check that everything went through?

> CONTENT - Section heading, description, and CTA label match copy in designs

**Expected**
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/ac6e04cd-fb11-4755-9153-0adaf6070567)

**Actual**
![Screen Shot 2021-02-16 at 10.37.39 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/666de408-a378-48fc-96f6-3e7db510b825)

**Comment by jbalboni** [comment]
Looks like that was missed

**Comment by jenniemc** [comment]
@laurenernest @jbalboni Doh! I see what is missed. I'm on this ticket now .
