### ISSUE TITLE
Determine product & design goals for Github data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18813]
## User Story/Description
The VSP Analytics & Insights team has been working to retrieve Github data through BigQuery so that we can aggregate data to tell stories and provide insights on our customer service tickets. We have done [some technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18414) into the data connection and believe we are able to get data through Google's public BigQuery dataset, given that the va.gov-team Github repo is public.

How might we understand if the data that is available can tell us if our customer support is successful and where we can find room for improvement? This ticket will be open to track those product and design questions so that we can determine if we have relevant data to answer those questions.

## Tasks
- [ ] VSP PMs provide input for the product and design questions, particularly for customer support, they would like answered through Github data. Please add questions to comments to this ticket.
- [ ] OCTODE and VSP Leadership provide input to the types of product & design questions they would like answered through Github data. Please add questions to comments to this ticket.
- [ ] VSP Analytics synthesizes the questions into which metrics & datasets could answer those question
- [ ] VSP Analytics determines where there may be gaps in the datasets for the requested questions.

## Questions to support thinking through the VSP Product Questions:
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of VSP and Platform are you hoping to assess?
- How frequently do you need this data?

## Acceptance Criteria
- [ ] VSP understands which product questions need to be answered by the Github data
- [ ] VSP Analytics understands where there may be gaps in the data for those product questions

**Comment by joanneesteban** [comment]
##  Testing Tools Team ([Accessibility](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16423))

### Outcomes to measure
- Adherence to Section 508 (accessibility) compliance. Are we getting better, staying the same, or need more improvement?
- Identify if VSP training, documentation, and support is improving VFS teams' adherence

### KPIs

| KPI                                                                                                                                       | Filters                                                                                |
|-------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|
| Number of open accessibility issues (total count)                                                                                         | Issues by: - Label - Open - Date is Open                                               |
| Number of open accessibility issues by defect severity.  Each issue is assigned one defect severity based on the VSP accessibility rubric | Issues by: - Multiple Labels - Open - Date is Open                                     |
| Track changes in total defects and defects by severity over time                                                                          | Issues by: - Date is Open - Date is Closed - Closed Date - Open Date - Multiple Labels |
| Be able to zoom into issues by type, by team, and by severity                                                                             | Issues by: - Multiple Labels - Date is Open - Date is Closed - Closed Date - Open Date |
| Additional insights into input, as well as the previously listed output                                                                   | ???                                                                                    |

**Comment by joanneesteban** [comment]
## Analytics & Insights Team (Customer Support)

### Outcomes to measure
- To which analytics services can we add documentation and automation to improve the self-service and velocity of our services?
- Which services and which times of the year or quarters take up the most time and effort? Where can we improve efficiency?
- What percentage of VFS teams are getting quality analytics tracking? Which of those services are getting completed, and where are the efficiency gaps in those services?

### KPIs
| KPI                                       | Filters                                                                                                                                       |
|-------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| % of VFSs with quality GTM tracked        | Issues by: Date is Open // Date is Closed // Closed Date - Open Date // Multiple Labels // Project Swim Lane // Project Swim Lane Date Change |
| % of VFSs with quality KPIs set & tracked | Issues by: Date is Open // Date is Closed // Closed Date - Open Date // Multiple Labels // Project Swim Lane // Project Swim Lane Date Change |

**Comment by drorva** [comment]
# Engineering teams

## Outcomes to measure

* Measure the quality of support we're providing to VFS teams
* Measure the level of effort the engineering team is investing in support

KPIs
Identical to the *accessibility* team's KPIs above with the addition of:
* Issues that are neglected: not answered in X (initially 3) number of days, 
* Issues that are dormant: no activity in X (initially 15) number of days
* Average time to close an issue over time
* Issues that are closed using a link to documentation (identified by a label).

**Comment by RachaelMR** [comment]
Product
- The platform

Desired outcomes
- High performing VFS teams
- High performing VFSs

Potential KPIs we could draw from GitHub to help us understand the platform product's impact
- Customer support volume, by platform team, topic area, and time to close, and with VFS launches indicated along the timeline
- VFS production deployment rate (can this be measured through GH, and if so is that the best way? May need discovery)
- Volume of "standards" issues (open, closed, older than x days) by VFS team and topic area, and with VFS launches indicated along the timeline

(@shiragoodman cc'ing you for visibility into the desire around "standards" issue tracking)

---

- Who is your audience? (assuming "audience" means who's going to be looking at this data)
  - Platform crew leadership and teams, OCTO-DE, VA at large 
- Why do you need this data?
  - To understand the impact of the platform product on the VA.gov ecosystem
What are you hoping to find?
  - Opportunities for platform product improvement
  - Visibility into state of VFS standards, to help us drive OCTO-DE and VFS team behavior change
What is your hypothesis that you're hoping the data will support?
  - As we release self-service tools, flexible deploys, and standards clarity, we'll see the quality and efficiency of VFS teams and their work improve 
How frequently do you need this data?
  - Open to recommendations here, maybe weekly? Daily?
