### ISSUE TITLE
Improve Caregiver issue tracker board performance

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#18810]
User story:

**As a:**
Veteran

**I want:**
VA teams to coordinate and track their work.

**So that:**
They can provide services efficiently.

AC:
- [x] Issue board shows all work assigned and planned for Caregiver team
- [x] Board columns reflect status of work
- [x] Zenhub UI performance is improved
- [ ] Board usage and config is documented

**Comment by tchrisdyer** [comment]
I believe this has been completed. Board performance is OK
