### ISSUE TITLE
[Tech Debt] - View Dependents - Write new cypress e2e tests that adhere to migration guide

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#18812]
## Description
The testing team recently rolled out an upgrade to Cypress, bumping the package version from 4.8 to 6.2.1. Though there are no breaking changes, [it was recommended](https://dsva.slack.com/archives/CE4304QPK/p1610486583177300) to go through [this migration guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-upgrade-guide.md) in preparation for Cypress upgrades that **would** introduce breaking changes. 

View Dependents currently has no e2e tests. New cypress tests should be written, and they should adhere to the latest standards set forth in the migration guide.

## Considerations
- Migration Guide - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-upgrade-guide.md

## Tasks
- [x] Write cypress e2e tests for view dependents that adhere to the recommended standards prescribed in the migration guide.

## Definition of Done
- [x] Tests run properly
- [x] Pull request submitted
