### ISSUE TITLE
Front end display when Walk ins value  = "unknown"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18816]
## Issue Description
Within the Audiology accordion for [University Drive](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/), the CMS value for "Walkins accepted" = Unknown. 
- On Staging, "Walkins accepted" = No. 
- On Prod, "Walkins accepted" does not appear at all.

<details>
<summary> Screenshot from Staging </summary>

![image](https://user-images.githubusercontent.com/55411834/105376250-c879a680-5bc6-11eb-82be-dfd62d772f58.png)

</details>

---
A similar situation occurs in the Telehealth accordion, which has "Unknown" for both "walk ins" and "referrals". The front end displays "No"

<details>
<summary> Screenshot from Staging </summary>

![image](https://user-images.githubusercontent.com/55411834/105389029-95d6aa80-5bd4-11eb-98e9-e0ee8fd670f1.png)

</details>

---

### Possible Values and display settings
If the value for "Walk  ins" = "Yes" in CMS, the front end should display "Walk-ins accepted? Yes"
If the value for "Walk  ins" = "No" in CMS, the front end should display "Walk-ins accepted? No"
If the value for "Walk  ins" = "Unknown" in CMS, do not display the line "Walk-ins accepted" 

If the value for "Referrals required" = "Yes" in CMS, the front end should display "Referrals required?" Yes"
If the value for "Referrals required" = "No" in CMS, the front end should display "Referrals required? No"
If the value for "Referrals required" = "Unknown" in CMS, do not display the line "Referrals required" 

---
## Tasks
- [ ] Ensure the front end renders appropriately based on logic displayed above. 

## Acceptance Criteria
- [ ] When the value for "Walk  ins" or "Referrals required"= "Yes" in CMS, the front end displays "Walk-ins accepted? Yes" or "Referrals required? Yes"
- [ ] When the value for "Walk  ins" or "Referrals required"= "No" in CMS, the front end displays "Walk-ins accepted? No" or "Referrals required? No"
- [ ] When the value for "Walk  ins" = "Unknown" in CMS,  the line "Walk-ins accepted" or "Referrals required" line is not displayed at all. 

This can be validated using the Audiology and Telehealth accordions for  [University](Drive](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Looks good!
