### ISSUE TITLE
[Epic] My VA frontend build

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#18819]
## Background

We're tweaking the final My VA designs now, but the final structure and data we're including are largely set. 

These are the latest mockups.

- [Desktop](https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443777220)
- [Mobile](https://vsateams.invisionapp.com/share/XNZWCYAYD45#/screens/443913926_My_VA_Mobile_Icons)

And this is the documentation of the different sections in the new design:

- [Name tag](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md)
- [Claims and appeals section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/claims-and-appeals-status.md)
- [Health care section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md)
- [Apply for benefits section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/apply-for-benefits.md)

## Tasks

- [ ] Review documentation and let Samara/Tressa/Cassandra know if there are questions.
- [ ] Break down FE build into smaller tickets based on the documentation.
- [ ] Link FE build tickets to this epic.
- [ ] Complete FE build.

**Comment by erikphansen** [comment]
FWIW, the link to the "latest full mockup we have" has gotten a little stale at this point :)

**Comment by Samara-Strauss** [comment]
> FWIW, the link to the "latest full mockup we have" has gotten a little stale at this point :)

Updated.

**Comment by Samara-Strauss** [comment]
Done ages ago. Closing!
