### ISSUE TITLE
Bold "or" at the end of. two bullets inside react widget

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#18814]
## Issue Description
The page [Get your VA medical records online] has text within bullets that needs to be bolded. The content is inside a react widget so work needs to be done by a dev. 
Screenshot of where to bold the "or" at the end of the bullets"![Screen Shot 2021-01-21 at 10.43.50 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/3a439d51-d7e8-450f-aed6-7fbbe71bb4fa)
---
## Tasks
- [ ] Fix text in react widget
## Acceptance Criteria
- [ ] Text is bolded on live site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/15724

**Comment by kelsonic** [comment]
PR merged, will be deployed during today's daily

**Comment by RLHecht** [comment]
Thanks for the fast work, @kelsonic !

**Comment by brianalloyd** [comment]
Closing per validation.
