### ISSUE TITLE
Remove colon in Email label on VAMC

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18825]
## Issue Description
On [University Drive in Staging](https://staging.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/), the label for the Minority Veterans Program email has a colon.
- The similar label for phone does not have a colon
-  The colon does not appear in the CMS data 
<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/105387465-cf0e1b00-5bd2-11eb-9507-39e76d823821.png)

![image](https://user-images.githubusercontent.com/55411834/104962901-ab5e9100-5996-11eb-849e-d1a701db4052.png)

</details>
---
## Tasks
- [ ] Ensure colon does not display on front end

## Acceptance Criteria
- [ ] Phone and Email labels are displayed consistently and without the colon
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Looks good!
