### ISSUE TITLE
[CONSIDER] Location information for Services not offered at "home location

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18841]
## Issue Description
It's unnecessary to always specify a city, state, zip for Facility health services because the Veteran already knows what facility they are viewing and the address is provided higher on the page. Inside the health service accordion, additional context is needed for where specifically at that address to find the service - unless that address is not the address of record for that facility.
For example, if a COVID-19 Vaccines clinic is happening at the Brockton Clinic, only the Brockton address needs to be displayed on the page with "Building 9" (or similar) is needed inside the service accordion. However, if the Brockton clinic decides to rent space in the Westgate Mall to vaccinate veterans (such as their parking lot), the facility page will need to provide more info than simply the building/wing/floor. 

### Current functionality
The content editor can check a box in Drupal to indicate “use the facility’s street address” which triggers the template to show the facility’s address when that box is checked.

---
## Tasks
Determine the right front end display for services which are not offered at "the home location", such as 
- [ ] a need for a "directions" link

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
