### ISSUE TITLE
Debt Portal Iteration 3 - Debt Reason from RO's 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#18842]
## High Level User Story/ies
As a  Veteran who has logged in to view my debts in Debt Portal I can see the type of debt I have but not the specific reason I have debt. I would like to see reason from Regional Office (RO) data. 

## Hypothesis or Bet
IF this data is available to the Veteran, they will have a full understanding of why the debt was incurred and will expedite the time to payment or seeking resolution. 

## OKR
Better user experience, Decrease time to resolution. 

## Definition of done
As a Veteran  who is logged into Debt Portal, I a abel to see the specific reason for my debt, along with the debt description and amount. 

- [ ] Is there an Integration point (API, potential integration w/DMC) with ROs data? 

- [ ] Is the data structured in a way that makes sense to Veteran - ie Is it just codes or full explanations?

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
