### ISSUE TITLE
Yellow Ribbon: Incorporate search tips message into YR Search

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18854]
## Issue Description
Add search tips to the Yellow Ribbon search page based on the design that Laurel did - see 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17937

## Design Reference

![image](https://user-images.githubusercontent.com/63107147/106466618-90495200-6469-11eb-8fa3-4d9fab99bdc9.png)

---
## Tasks
- [x] Add the search tips message to the Yellow Ribbon search page
- [x] Add a feature flag to hide on Production
- [x] Include the Google Analytics code supplied by the Analytics team here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/18470
- [ ] QA analytics code with Analytics team on Staging
- [ ] Staging Peer Review
- [ ] Review on Staging with John H and Marci
- [ ] Remove feature flag
- [ ] Deploy to Prod ~Feb 9, 2021

## Acceptance Criteria
- [ ] A new search tips message will be displayed on the Yellow Ribbon search page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Reference design at the bottom of https://github.com/department-of-veterans-affairs/va.gov-team/issues/17937

**Comment by MarciMcGuireGCIO** [comment]
@zacharymore I added more details to the Tasks at the top of this issue.  Pls let me know if it doesn't make sense.

**Comment by zacharymorel** [comment]
One question: is this piece of work suppose to incorporate the Search Analytics as well or is it just the tool tip analytics?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Great question!  Just the tool tip analytics.  I'll create a new issue in the backlog for incorporating the rest of them.

**Comment by zacharymorel** [comment]
That sounds good to me. It's another win before we head deep in to back end work on GBCIT data service.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO I need to bump this story points up to a because I'll need to add a new Feature Flag for Yellow ribbon work.

**Comment by zacharymorel** [comment]
We also can create a quick small User Story for 1 point that says, "Adding Yellow Ribbon Enhancements Feature Flag to vets-api" instead if you'd prefer that for documentation.

**Comment by MarciMcGuireGCIO** [comment]
Hey @zacharymorel  let's just bump this story and I'll add it to the tasks at the top.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO + @zacharymorel adding the design comp screenshot  for visual reference.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel, when you have a few min, can you scan down this Find a Form MVP issue at how the merge and PR info has been connected, and PR-open tags are used:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/7691#issuecomment-612955354?  

If you could start doing something similar, it will keep John and me in the loop, we can easily go back and see the related PRs, and I can escalate if something is ever blocking us.  Thanks!!

**Comment by zacharymorel** [comment]
To make sure that I understand correctly, you'd like me to add the PR-Open flag to the user story when there is one open?

**Comment by MarciMcGuireGCIO** [comment]
Yeah!  That, and reference the issue number in the pull request so they are linked, like this:  

![image](https://user-images.githubusercontent.com/73354907/107082879-d3395b80-67c2-11eb-885e-e15b09eade81.png)

**Comment by zacharymorel** [comment]
Ah yes! I do link them. There's two Pull Requests linked to user story above.

**Comment by MarciMcGuireGCIO** [comment]
Oh, I see it now.  Sorry about that!

**Comment by zacharymorel** [comment]
No worries!

**Comment by MarciMcGuireGCIO** [comment]
I changed my notification for pull requests.  No wonder I wasn't seeing them!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @johnhashva @laurellawrence this should be on staging by 6pm EST today. FYI.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO does this look good to y'all?

**Comment by zacharymorel** [comment]
https://staging.va.gov/education/yellow-ribbon-participating-schools/?name=University+of+south+florida

**Comment by MarciMcGuireGCIO** [comment]
Apart from the caps in "Enter A School's full name..."  It looks awesome!  Unless there was a specific reason for the caps, I think it should read, "Enter a school's full name..."   @johnhashva @laurellawrence - thoughts?

**Comment by zacharymorel** [comment]
Whoops.

**Comment by zacharymorel** [comment]
I can fix that spelling here in a bit.

**Comment by zacharymorel** [comment]
Pull request merged. Typo should be fixed on staging by 3.

**Comment by zacharymorel** [comment]
This is ready for validation and staging review on my end, as far as I know.
