### ISSUE TITLE
FSR - Unauthenticated review page / signature design

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#18867]
## Issue Description
For the unauthenticated FSR, we will need to make some adjustments to several pages that would normally be pre-filled for authenticated users. 

---
## Tasks
- [x] Alternative designs created for C7: Review
- [x] Sync designs to UXPin
- [x] Create frontend ticket 

## Acceptance Criteria
- [x] Designs synced to UXPin and linked in this ticket
- [x] Frontend ticket created and linked in this ticket

**Comment by rileyorr** [comment]
[Alternative review page/signature design has been added to UXPin](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136386555/simulate/no-panels?mode=i)

**Comment by rileyorr** [comment]
I've created [the frontend ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19936)
