### ISSUE TITLE
Add Heath Care Experience team to Pager Duty 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18863]
## Description
The Health Care Experience team is creating a new application, called `Health Care Questionnaire` on va.gov and we want to add our services to Pager Duty. 

Our app depends on the following functionality: 

- Users successfully logging in
- Lighthouse Health APIs
- MAPs/MAS

We are not yet live, but we are working towards getting the infrastructure up and going. 

I have been following [this documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/) to get Pager Duty set up. 

[Slack conversation for more context](https://dsva.slack.com/archives/CBU0KDSB1/p1611255904032200)

---
## Tasks
- [x] A team member needs access to Pager Duty, That can be Mark Dewey (@mdewey)  for now. 
- [ ] A new Pager Duty app needs to be created for the app, Health Care Questionnaire

## Definition of Done
- [x] The point of contact (@mdewey) has access to the Pager Duty
- [ ] A new application for the Health Care Questionnaire has been created.

**Comment by jhouse-solvd** [comment]
@mdewey - The VSP Operations currently has zero (0) remaining free licenses for PagerDuty, so are unable to process this request at this time. 

However, I am tagging @f1337 and @drorva here as they may be able to help us expedite the process of procuring additional licenses.

**Comment by mdewey** [comment]
@jhouse-solvd What is the time frame for getting more licenses. 

Short term I need to create a new app in Pager Duty, the long-term need is our team needs to be able to access Pager Duty. 

I am willing to hop on a quick call to sort this out.

**Comment by mdewey** [comment]
@jhouse-solvd Still waiting for an answer.

**Comment by jhouse-solvd** [comment]
@mdewey - This will need to be addressed directly with @f1337 and @drorva 

Please forgive for the delayed reply.

**Comment by f1337** [comment]
Doh, I fat fingered the button in GitHub mobile. Didn't mean to close. We just got new licenses added to PD. I'll take this on, please give me til Monday EOB to follow up?

**Comment by mdewey** [comment]
Hey @f1337! I am following up! What can I do to help this along?

**Comment by f1337** [comment]
@mdewey I created a PD Team for your called Health Care Experience, and invited you to PD as a Manager of that group.

For VSP, we give every team member Manager level access. Whether you do the same for Health Care Experience is up to you. :)

Do you have add'l folks you want me to invite? I'll need names and emails, or you can invite them yourself if you'd rather do that.

Lastly, I'm not sure what is meant by "Pager Duty app". Is there something else you need from me?

**Comment by mdewey** [comment]
Thanks so much! I will add other team members as needed, We are still in pre-launch so I am not sure who will be added at the end of day. 

By "PagerDuty App" I meant a new service to be added to this [file](https://github.com/department-of-veterans-affairs/devops/blob/a4b5432061ae60a4f77952bbe5f668a1355ee007/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L232). But now that I have access I can rock that myself. 

Thanks so much !

**Comment by jhouse-solvd** [comment]
@mdewey - let us know if you still need assistance from the operations team? If not, let me know if it's safe to remove the "operations" label? thank you in advance and looks like Fleet helped get you on the right path.

**Comment by mdewey** [comment]
@jhouse-solvd 

I have everything set up. I think I am good for now. This can be closed. Thank you so much!

**Comment by jhouse-solvd** [comment]
closing per mdewey's comment above
