### ISSUE TITLE
R&S, Disability benefits -- Content Review 

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#18871]
## Issue Description
First-draft copy of batch 2 Careers and Employment Q&As needs to be reviewed by DEPO before building in Drupal.

Copy deck to review: 

## Tasks
- [ ] DEPO to review the copy deck attached here (Beth)
[rs-1.1-disability-v1-112420 (3).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5895546/rs-1.1-disability-v1-112420.3.docx)
- [ ] Sitewide content to review and copyedit (Randi)
- [ ] Create ticket to input content into Drupal (Laura)

## Acceptance Criteria
- [ ] Copy deck reviewed and ready to be input into Drupal. 
- [ ] Build ticket created in GH with final copy deck attached.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 You can move forward with writing these R&S articles that the SME, Paul Shute, gave the thumbs up on:

- What is Combat-Related Special Compensation and why is it important?
- How do I get a copy of my rating decision?
- What is a Non-compensable disability?
- What is the difference between VA compensation and severance disability?
- Are there other VA benefits related to compensation?
- How does VA determine someone's net worth?
- If I am already receiving monthly payments or a service-connected disability can I get a VA pension too?

**Comment by lwalsh617** [comment]
Thanks for the list of questions, @bethpottsVADEPO 
I capture copy development under [GH ticket 21414](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21414)

**Comment by lwalsh617** [comment]
I am closing this ticket. Ticket 
![image](https://user-images.githubusercontent.com/53535663/114201823-9b66a580-9924-11eb-9ca4-e1b84dc67cb3.png) replaces it.
