### ISSUE TITLE
Content Support for Static HLR Page from Claims and Appeals

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18876]
## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @DanielleThierryUSDSVA and @brianalloyd. If your request includes engineering support, also tag @ncksllvn and @kelsonic.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |

This is an update to the Higher Level Review public websites pages (https://www.va.gov/decision-reviews/higher-level-review/) to point to the HLR application page (https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/).

The initial IA work was done as part of #12957.

As part of that story, there was an information architecture worksheet.  I have pasted it below with some comments:

## Information Architecture Worksheet (Optional)
**SEO Keywords** - Higher Level Review, Decision Review
**Proposed site map/page structure** - None
**Suggested URL(s)** -Noted above
**Suggested entry points** - Somewhere higher up on the https://www.va.gov/decision-reviews/higher-level-review/ page so it is not buried below/  We talked about potentially finding a way to provide a temporary note or something that advertises that HLR is available.
**Crosslinking opportunities** - N/A
**Redirects/canonical tags** - N/A

## About your app/tool/functionality
* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Currently VA.gov does not support any appeals or decision review paths. The existing path is only through the paper form. This does not exist on eBenefits either, so this digitization is the first step in bringing the review process to veterans using VA.gov. It is also the first step before supplemental claims and Notice of Disagreement. We believe that bringing this to VA.gov will greatly reduce the time-to-a-decision for veterans. This will be talked about further below.
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/430329537

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
- [x] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * This is an update to the Higher Level Review public websites pages (https://www.va.gov/decision-reviews/higher-level-review/) to point to the HLR application page (https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/)
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * No copy updates other than wording around the link to the HLR form.
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * No

### Desired/target implementation date
What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Spoke to Brian - understand that you are busy.  Currently, the second result from the VA.gov search is the page we are trying to link **to** so it is not an emergency that there is no link from the main page.  That being said, we have no way of advertising this app outside of Google search and VA.gov search. 

---

### About your team

- Team name: Claims and Appeals
- DEPO product owner: Matt Self
- Product manager: Luke Majewski (soon to be Veronica Henry)
- Designer: Kevin Stachura
- Product/team Slack channel: #vsa-claims-appeals

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA @RLHecht @kelsonic @ncksllvn  is this something sidewide content can action or is FE support needed in support?  Trying to assess when we need to insert this into the board for action.  Thanks

**Comment by RLHecht** [comment]
@brianalloyd This would be a content issue. It looks like it's adding a line with a link to the application page. I can work with @DanielleThierryUSDSVA to figure out when we can implement.

**Comment by brianalloyd** [comment]
Thanks @RLHecht for the follow up, super helpful, please reach out if you need any support from your old team mates.

**Comment by RLHecht** [comment]
This ticket can be closed. Work was completed in ticket #19073
