### ISSUE TITLE
Create a pattern for The header / hero area with the veteran's name and info

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18877]
## Issue Description
Create a pattern for The header / hero area with the veteran's name and info

---
## Tasks
- [ ] Add header/hero pattern to Sketch library
- [ ] Create documentation for header hero pattern
- [ ] Develop header/hero component if needed 

## Acceptance Criteria
- [ ] Sketch library update
- [ ] Pattern is on design.va.gov 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
