### ISSUE TITLE
Test User Accounts_Conversation Guide Usability guide

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#18890]
## Issue Description
Guide for testing the usability of the existing prototype 

---
## Tasks
- [x] Talk to Naomi about prototype from 2019 to understand intended functionality
- [x] Construct initial guide with general questions about functionality

## Acceptance Criteria
- [ ] Share questions with team members
- [x] Recruit participants for testing
