### ISSUE TITLE
[CONSIDER] Force location name (to avoid heading level defects)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18906]
## Issue Description
the absence of a H4 location name caused a skipped heading level, identified as a 508-defect-2: #15701. The defect has been resolved. However, it was proposed by Ryan to force a location name to avoid causing this issue in the future. 

<details>
<summary> Location names, such as Center for Treatment of Addictive Disorders, (seen within Addiction and Substance Abuse Treatment), use H4 headings, making the H5 for **Hours** and Phone headings appropriate. </summary>

![image](https://user-images.githubusercontent.com/55411834/97904272-7890ef00-1cfd-11eb-9ead-3665e64916ee.png)
![image](https://user-images.githubusercontent.com/55411834/97904472-c4dc2f00-1cfd-11eb-85c1-af4626c7f319.png)
![image](https://user-images.githubusercontent.com/55411834/97904135-5008f500-1cfd-11eb-83f8-5993f41e8aa4.png)

</details>

<details>
<summary>Without this H4 location name heading,  **Hours** and Phone headings skip a level. </summary>

![image](https://user-images.githubusercontent.com/55411834/97905387-1b963880-1cff-11eb-9361-a1440b658cfa.png)

</details>

---
## Tasks
- [ ] Determine business rationale for location names as mandatory

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Should be addressed as part of #13140 VA Services Taxonomy improvements / iterations

**Comment by jilladams** [comment]
@laflannery FYSA this exists

**Comment by laflannery** [comment]
@jilladams These headings were worked on in a [different ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12068) to get rid of the skipping heading levels.

- Accordions are now H3s (after the work PWs did which was separate)
- "Contact Information" is now an H4 instead of H3
- All headings under that are H5 (that was unchanged)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106678594/01eb4dfa-683f-478d-979b-cf80f47698b5)

**Comment by jilladams** [comment]
And that satisfies this issue / we're ok to close?

**Comment by laflannery** [comment]
Yep, I wasn't sure if anyone else (i.e. Michelle) needed to review or be aware but I'll close if you're good!
