### ISSUE TITLE
VAMC audit using comparison tool

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18900]
## Issue Description
Using the comparison tool recently made available by VSP, we need to audit VAMC pages to identify any other discrepancies which could block the cms-export cutover

---
## Tasks
- [ ] audit VAMC pages

## Acceptance Criteria
- [ ] Issues are created for any identified discrepancies 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Working through false positives and missing fields in #18922
