### ISSUE TITLE
FL - Convert to forms system

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18908]
## Issue Description
The Facility Locator currently does not handle errors accessibly or in alignment with the design system. Discovery was done to determine the feasibility of adopting the form system in order to be compliant and efficient and the recommendation was made to convert to the forms system. This will be a complete re-write of the search form. No impact on secondary behaviors was identified. 

---
## Tasks
- [ ] Create new components and check for front end rendering #18977
- [ ] Check functionality of new components #18979
- [ ] Add feature flag to allow testing #18978 
- [ ] Design spec for error messages #18773
- [ ] Accessibility check-in for error messages
- [ ] Implement error messages post conversion/Add cypress and unit testing #18351

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Per Chris Valarida, the current forms library is not a good option for the Facility Locator as it is really intended for the digitization of paper forms[Slack thread here](https://dsva.slack.com/archives/G01PBG4D397/p1614030445000100)
Any improvements to the current forms library likely won't be available for early adoption until probably Q3 at the earliest.
