### ISSUE TITLE
[UNPLANNED] Debug Pension Question Responses

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18909]
## Background
One of the results from testing pension questions with BGS/RBPS was that responses to whether a dependent had any income or if the household had an exceeded net worth were not showing displaying as answered.  We need to debug that and confirm our initial assumption that they are being sent and somehow not written on the BGS side.

## Tasks
- [x] Pull logs from a submission that includes these questions to see if they exist and are being sent
- [x] Check results with Linda and/or Shane 

## Acceptance Criteria
- [x] The reason those responses are not displaying to BGS has been determined and a correction ticket has been drafted.

**Comment by kathleencrawford** [comment]
We are sending the `netWorthOverLimitInd` field in the `vnpBnftClaimCreate` call but according to Linda it is getting overwritten.  We need to also sent it in the `vnpBnftClaimUpdate` call so that it doesn't get overwritten during the update.
