### ISSUE TITLE
Add Feature Toggles to Pension Questions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18910]
## Background
In light of RBPS having an issue accepting new scripts to accommodate the new pension questions introduced on to the form, the deployment of RBPS new code base may be delayed to the point where we might launch the 686c/674 before the questions are ready to be used.  We may need to not show those optional questions until they are ready to be used as intended.

## Considerations
- Making changes inside the VA Form System can be a challenge and a feature toggle may not work.  
- Consider simply removing them from the frontend temporarily and re-adding them back in later.
- Can they simply be commented out?

## Tasks
- [ ] Determine the safest way to temporarily hide these questions
- [ ] Temporarily hide these questions until the LoB is ready for them to be introduced

## Acceptance Criteria
- [ ] The questions have been addressed
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Form System cannot tolerate feature toggles
