### ISSUE TITLE
[CONSIDER] Implement "operationalHours" from VAST in VAMC

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18912]
## Issue Description
VAST administrators have included a new `operationalHoursSpecialInstructions` field that is now in Lighthouse.

![operational status](https://user-images.githubusercontent.com/55411834/105556756-e5e26980-5cc7-11eb-85dd-56ac73acca56.jpg)

There are 4 possible options that could be concatenated from VAST:
- Administrative hours are Monday-Friday 8:00 a.m. to 4:30 p.m.
- Expanded or Nontraditional hours are available for some services on a routine and or requested basis. Please call our main phone number for details.
- Vet Center after hours assistance is available by calling 1-877-WAR-VETS (1-877-927-8387).
- Vet Center hours are dependent upon outreach assignments. Please call our main phone number for details.

Field may contain one or more of the options above. 

---
## Tasks
- [ ] Determine options for use of these variables on VAMC product, particularly the administrative hours variable
 
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
Possible duplicate with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7027

**Comment by mmiddaugh** [comment]
Closing per [Dave's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27035#issuecomment-1513661743)
