### ISSUE TITLE
[Erie-Health-Care](https://www.va.gov/erie-health-care/)  Staging Review Accessibility/508 Check

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18928]
## STORY
VAMC web modernization website requires a deep dive 508/accessibility check performed, so the VAMC team will know what to resolve on this product and all future products coming into Dual-state.

## Resources
** The VAMC team does not create new products from design or IA, we are providing new content on an already reviewed and approved template from Pittsburgh-health-care site.  Most of the issues we expect will be related to media, alt, and content.   Please help us escalate any design, IA, or structural issues up to our Facilities team by highlighting those as they occurr.

## Product
[Erie-health-care](https://www.va.gov/erie-health-care/)

## TASK
- Please perform and provide report of the following areas:
  - [ ] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - Conduct axe browser scan, and document or address issues found
  - [ ] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [ ] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast **This is a design item that wil have to be escalated to Facilities)
    - Check for colorblindness issues
  - [ ] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [ ] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [ ] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox

## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [ ] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [ ] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - Conduct axe browser scan, and document or address issues found
  - [ ] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [ ] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
  - [ ] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [ ] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [ ] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- [ ] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Attach to Collab Cycle Epic**
- [ ] **Labeled with Team**
