### ISSUE TITLE
[FE] Update nametag/banner 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18932]
## Background
We are updating the nametag/banner component and adding it to MyVA.

## Tasks
- [ ] Update nametag/banner
- [ ] Include disability rating
- [ ] Review with design/matt/samara
