### ISSUE TITLE
[VAMC] VISN-4 - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18933]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**First VISN with 9 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Erie health care system legacy site](https://www.erie.va.gov/)
[Google Drive locations for VISN-4](https://drive.google.com/drive/folders/1WygUuvMetcaCm43woL6rfTursUVUyGeO)

## TASKS
See below associated tasks which should include, but are not limited to:
- Prepare the following Systems for Web Modernization:
- [ ] Altoona VA Medical Center
- [ ] (Butler)Abie Abraham VA Health Care Center (HCC)
- [ ] Coatesville VA Medical Center
- [x] Erie VAMC
- [ ] Lebanon VA Medical Center
- [x] Pittsburgh VA Medical Center-University Drive 
- [ ] Corporal Michael J. Crescenz VA Medical Center
- [ ] Wilkes-Barre VA Medical Center
- [ ] Wilmington VA Medical Center

- Completed the following initiatives for each System included in order:
- [x] Kickoff Meeting-	Comms
- [x] Playbook & Staff Profiles-	Data
- [x] Content write/build-	Content
- [x] Build .csv files- 	Data
- [x] **Migrate .csv files**-	**CMS**
- [x] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [x] Move Facilities under correct System (Consolidate?)-	Build
- [x] Load Content-	Load
- [x] Build Devshop environments-	Build
- [x] Review/Clean up- 	Review
- [x] (staging Review Requests)-	Issues to begin (1 sprint out)
- [x] **Staging Review**-	**Platform**
- [x] Clean-up from Staging	Review
- [x] List of PAOs for Training sent to CMS training-	Training (update)
- [x] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

Facilities include for System:
Altoona:
- [ ] Altoona VA Medical Center
- [ ] DuBois VA Clinic
- [ ] Huntingdon County VA Clinic
- [ ] Indiana County VA Clinic
- [ ] Johnstown VA Clinic
- [ ] State College VA Clinic

Butler:
- [ ] Abie Abraham VA Health Care Center (HCC)
- [ ] Sergeant Joseph George Kusick Community Living Center (CLC) 
- [ ] Armstrong County VA Clinic
- [ ] Clarion County VA Clinic
- [ ] Cranberry Township VA Clinic
- [ ] Lawrence County VA Clinic
- [ ] Michael A. Marzano Department of Veterans Affairs Outpatient Clinic

Coatesville:
- [ ] Coatesville VA Medical Center
- [ ] Delaware County VA Clinic
- [ ] Spring City VA Clinic

Erie:
- [x] Erie VAMC
- [x] Ashtabula County VA Clinic
- [x] Crawford County VA Clinic
- [x] McKean County VA Clinic
- [x] Venango County VA Clinic
- [x] Warren County VA Clinic

Lebanon:
- [ ] Lebanon VA Medical Center
- [ ] Berks County VA Clinic
- [ ] Cumberland County VA Clinic
- [ ] Landcaster County Va Clinic
- [ ] Schuylkill County VA Clinic
- [ ] York VA Clinic				

Pittsburgh:
- [ ] Pittsburgh VA Medical Center-University Drive 
- [ ] H. John Heinz III Department of Veterans Affairs Medical Center 
- [ ] Beaver County VA Clinic 
- [ ] Belmont County VA Clinic 
- [ ] Fayette County VA Clinic 
- [ ] Washington County VA Clinic 
- [ ] Westmoreland County VA Clinic

PHILADELPHIA:

- [ ] Corporal Michael J. Crescenz VA Medical Center
- [ ] Burlington County VA Clinic
- [ ] Camden VA Clinic
- [ ] Gloucester County VA Clinic
- [ ] Victor J. Saracini Department of Veterans Affairs Outpatient Clinic
- [ ] West Philadelphia VA Clinic

Wilkes-Barre
- [ ] Wilkes-Barre VA Medical Center
- [ ] Allentown VA Clinic
- [ ] Columbia County VA Clinic
- [ ] Northampton County VA Clinic
- [ ] Sayre VA Clinic
- [ ] Tobyhanna VA Clinic
- [ ] Wayne County VA Clinic
- [ ] Williamsport VA Clinic

Wilmington:
- [ ] Wilmington VA Medical Center
- [ ] Atlantic County VA Clinic
- [ ] Cape May County VA Clinic
- [ ] Cumberland County VA Clinic
- [ ] Kent County VA Clinic
- [ ] Sussex County VA Clinic

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 
- [ ]
