### ISSUE TITLE
[FE] Update MyVA wrapper to load all required data upfront

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18938]
## Background
The current MyVA does not load any data upfront. The new MyVA should behave like the profile and load all required data before displaying the UI. Also, the new MyVA requires more data than the current MyVA. 

## Tasks
- [ ] Discuss with design why it takes forever to pull data (how to resolve this?)
- [ ] Confirm with design that this is acceptable (could take additional time to load all of this info)
- [ ] Determine if LOA1 vs LOA3 vs 2FA all call the same endpoints
- [ ] Update MyVA wrapper
- [ ] Review with design/matt/samara

**Comment by erikphansen** [comment]
The scope of this ticket has changed a bit. I've determined that it's not practical to load all data up front like I'd initially hoped. So our approach will change.

1. We will show a spinner in place of the entire My VA Dashboard while we load some basic info, such as name, military history, and disability rating.
2. When that basic info loads we will show the Dashboard/Profile nametag
3. We will then show the Apply for Benefits section and possibly the Claims/Appeals section as well as the Health Care sections. (At that point we will know if we even need to show the Claims/Appeals section as well as the Health Care section)
4. The Claims section will be responsible for loading claims and appeals. While it is doing so it will only show a simple progress spinner with a generic "we are loading your info..." message. That section might show data or it might render nothing at all. See [this Slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1611939415120700?thread_ts=1611937032.118700&cid=C909ZG2BB).
5. The Health care section will be responsible for loading messages, rx data, and appointments (and also knowing if the rx and messages sub-sections will even been shown)

**Comment by erikphansen** [comment]
I'm closing this. The Dashboard now loads the data it can, but it'll be up to other child component to load their own data, as described above.
