### ISSUE TITLE
Public Websites: Sprint 40 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18941]
## Sprint 40 Priorities
1.  Build out remaining CLP FE Styling build (boilerplates are complete)
2. Transformers Update + JSON Comparison tool #18954
3. Finalizing R&S functionality - Remaining tickets from Sprint 39
3. Outstanding tickets from Sprint 39 not already included in the priorities listed above
4. Intake Requests for January, along with some applicable Tech Debt (508/a11y issues)
5. CLP Transformer Build ISO CLP MVP 1.0

### Campaign Landing Page MVP 1.0
**FE Transformer**
- [x] [FE] Create transformer/output/input for the CLP [Transformers] #17513
- [x] [FE] Incorporate applicable 508/a11y recommendations from mural design review. #18756

**FE Panel Build [Panel 1-5 (Nick)]**
- [x] [FE] CLP Hero Banner FE Build [Panel 1] #17636
- [x] [FE] CLP FE Build “Why this matters” [Panel 2] #17642
- [x] [FE] CLP FE Build “What We Can Do” [Panel 3] #17649
- [x] [FE] CLP FE Build “Video” Element [Panel 4] #17657
- [x] [FE] CLP FE Build “Spotlight” Element [Panel 5] #17974

**FE Panel Build [Panel 6-11 (Kelson)]**
- [x] [FE] CLP FE Build “Stories” Element [Panel 6] #17979
- [x] [FE] CLP FE Build “Downloadable Resources” Element [Panel 7] #17983
- [x] [FE] CLP FE Build “Events” Element [Panel 8] #17988
- [x] [FE] CLP FE Build "FAQ Accordion" NO TICKET
- [x] [FE] CLP FE Build “Connect with us” Element [Panel 10] #17999
- [x] [FE] CLP FE Build “VA Benefits” Element [Panel 11] #18004
- [X] [PM] Created QA Ticket - Campaign Landing Page VSA-QA Test Plan #19554

### Transformer + JSON Comp Tool
- [ ] [FE] CMS export JSON diffs for Public Websites Transformers #18954

### Resources and Support
Priority R&S Breakdown: WIP  [MVP 1.1 EPIC #15588] [Iterate EPIC #15584]
**FE**
- [x] [FE] updating the URL hash when an accordion item is expanded (coronavirus FAQs page as a test bed - Collab with Sharon's Team) 
- [ ] [FE] Enhancement: RS mobile views, left margin is too smooshed to the edge and cutting off text #17470 (WIP Sandra, determining status?)

### Cerner Support
Main objective: Acquire facility list to determine what facilities need to be set accordingly.  **_No Immediate Requirements_**

### Intake Request - Techical Debt
**FE**
- [x] [FE/Content] CMS team: VAWEB - update GraphQL query and template #18755
- [ ] Content Support for Static HLR Page from Claims and Appeals #18876 (Sitewide Content Team WIP)
- [x] Mobile side-nav focus not properly managed in Safari #18916 (WIP Erik)
- [x] Mobile side-nav trigger can render on top of page contents #18917 (WIP Erik)

### Discussion Topics/Grooming 
- [ ] Explore and revisit Visual Regression Testing to aid in modifications to CMS templates and style #18869
- [ ] Table Caption Update/Fix #16562 (R&S)
- [ ] Design effort for R&S "Share to Mobile" and "Share article" feature adds? 
- [ ] Enhancement: RS mobile views, left margin is too smooshed to the edge and cutting off text #17470
- [ ] Pager Component for Outreach Event Page #19292
- [ ] CMS, design system, components [SCREENREADER, KEYBOARD]: Aside SHOULD not be contained in another landmark #6379
- [ ] CMS [COGNITION]: Multiple ambiguities with linked text in content block #3556

**Comment by brianalloyd** [comment]
Sprint 40 is a wrap.
