### ISSUE TITLE
[FE] Build the Benefits You Might Be Interested section

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18947]
## Background
Specs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/apply-for-benefits.md

Should be relatively straightfoward.

## Tasks
- [ ] All logic to determine what boxes to show should be loaded by the parent Apply For Benefits component
- [ ] Apply For Benefits should call ESR to see if the user has applied for health care in the past and if they have we should not show the Health Care box
- [ ] Optional: Apply For Benefits should also get the DD4EDU info (if user has 2FA set up) and if we _know_ the user is getting DD4EDU we can hide the education box
- [ ] add simple tests to make sure the correct boxes are shown under certain situations

**Comment by mshea0606** [comment]
Waiting to confirm design
