### ISSUE TITLE
[FE] Build the Healthcare "related links" section 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18943]
## Background
We need to build an updated healthcare "related links" section

## Tasks
- [x] Confirm copy with design
- [x] Determine location of the links and whether they change if they are in Cerner 
- [x] Build healthcare related links
