### ISSUE TITLE
[FE] Create a wrapper component for the Healthcare sections

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18942]
## Background
We need a reusable component to show "latest message", "next appointment", and "prescription update" columns

## Tasks
- [ ] Make sure we include the header, blue info/status box, and the button link and nest the content body
- [ ] Confirm with designers how this will work based on varying screen size
- [ ] The height of each box should be consistent across each row 
- [ ] Review with Design/Matt/Samara
