### ISSUE TITLE
[FE] Make a component for in-progress application

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18945]
## Background
The new component varies slightly from the existing component. 

## Tasks
- [ ] Create component for in-progress application
- [ ] Height needs to match across the row
- [ ] Determine if anything needs to be truncated to keep the height short enough

**Comment by erikphansen** [comment]
I got carried away with this work and went ahead and wired up the component to the user data. ¯\_(ツ)_/¯

**Comment by erikphansen** [comment]
Waiting for this to roll out to staging and then we can validate that it works.

**Comment by erikphansen** [comment]
It's working on staging now:

<img width="1291" alt="Screen Shot 2021-02-10 at 11 12 46 AM" src="https://user-images.githubusercontent.com/20728956/107559560-1dd72100-6b91-11eb-8ee4-604cd78c020e.png">
