### ISSUE TITLE
[EPIC] MyVA copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18956]
## Background
This is a ticket to track copy for MyVA 2.0 

## Tasks
- [ ] Matt creates tickets for each case below
- [ ] Tressa/Cassandra add info to tickets
- [ ] Peggy reviews each ticket

LOA1 user

LOA3 First-time user experience

LOA3 user who has everything

LOA3 user who has things but has no updates
