### ISSUE TITLE
Add collapsing "card" that opens with "Remove This Dependent" button

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#18958]
# Background

In order to allow the user to click into a specific dependent and provide us with the information needed to remove them, we need to add the ability for each dependent card in the list to "expand" with a formlet inside. 

[Mockup](https://xd.adobe.com/view/9a75a359-e0e2-4411-b235-60c3dddb4e6e-cf26/screen/47bc540b-9ae3-448f-b73f-c9dcc259aa99)

## Tasks
- [x] Add Javascript functionality to expand a space inside each dependent card listed
- [x] Submit a PR for review
## Acceptance criteria
- [x] When the "Remove this dependent" button is clicked a space opens up that will contain the formlet
- [x] A PR has been submitted for review
