### ISSUE TITLE
Add logic to Collapsing "Card" Based on Dependent Type

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#18959]
## Background
When a user clicks to "Remove this dependent" an area will open up that needs to include a few form fields to collect the information that we need and don't already have. These "formlets" will need to include slightly different fields based on the type of dependent.

## Considerations
- [Mockup](https://xd.adobe.com/view/9a75a359-e0e2-4411-b235-60c3dddb4e6e-cf26/screen/47bc540b-9ae3-448f-b73f-c9dcc259aa99)

## Tasks
- [x] Add logic to change what fields are rendered based on dependent type
- [x] Submit a PR for review

## Acceptance Criteria
- [x] The cards show the correct formlet based on dependent type
- [x] A PR has been submitted for review
