### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA So. Louisiana health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18957]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-16 Internal Review Folder](https://drive.google.com/drive/folders/19WE1dLBjZkeIMW8ACPbOZ-BWzaoOTopq)
[Review template for review](https://drive.google.com/drive/folders/18CfKY3QZhR4AoiByBYKqAgKfFewEb9RV)

## Tasks
Complete review of system and facility pages, manually assure all Facilities are under correct system and Auto URL is checked, manual review and test URLS, Resolve broken links, test phone #s, and hyperlinks for:
- [x] 629	New Orleans VA Medical Center
- [ ] 629	New Orleans Veterans Medical Center
- [x] 629BY	Baton Rouge VA Clinic
- [x] 629GA	Houma VA Clinic
- [x] 629GB	Hammond VA Clinic
- [x] 629GC	Slidell VA Clinic
- [x] 629GD	St. John VA Clinic
- [x] 629GE	Franklin VA Clinic
- [x] 629GF	Bogalusa VA Clinic
- [x] 629QA	Baton Rouge South VA Clinic

* Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [x] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.

**Comment by ltrombley** [comment]
#18957 - Internal Review, Test, Proof Read, and CORRECT all NODES for "VA So. Louisiana health care" ending with stakeholder review doc is Complete and moved to Validate.
1. Did not find 629 New Orleans Veterans Medical Center
2. Moved 629QA Baton Rouge South VA Clinic to Southeast Louisiana System, Review Pending Rebuild/Publish
