### ISSUE TITLE
[FSR] The 'cancel' button functionality needs to be updated in the list loop component

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18964]
## Issue Description
There are multiple bugs occurring with the 'cancel' buttons in the list loop component. 
**How to recreate the bugs in staging:**
1. Navigate to Step 2: 'Your employment history'
2. Select 'yes' for, "Have you been employed within the past two years?"
3. Select 'yes' for, "Are you currently employed?"
4. Select the 'Add payroll deduction' button
5. **Bug 1:** Selecting the 'cancel' button on the second payroll deduction card doesn't close the card
   - Ideal experience: Selecting the 'cancel' button should remove the card
6. **Bug 2:** Selecting the 'cancel' button on the default payroll deduction card breaks the form
   - Ideal experience: There shouldn't be a 'cancel' button on the default card _unless_ the user has already saved inputted values and is in the 'edit' mode. In this case, the 'cancel' button's action would cancel the action and close the card with the original inputted values.

Please refer to this video to see a visual of the bugs:
https://images.zenhubusercontent.com/133843125/3af14a1b-39e8-41cd-93ff-51cd69a756f4/screen_recording_2021_01_25_at_2_02_00_pm.mov

---
## Tasks
- [ ] _Update the list loops so that selecting the 'cancel' button on subsequently added cards removes the card_
- [ ] _Remove the 'cancel' button on the default card_
- [ ] _Ensure that the 'cancel' button only displays on the default card if the user is editing previously inputted values_

## Acceptance Criteria
- [ ] _Updates have been pushed to staging and sent to a designer for review_
