### ISSUE TITLE
Health Record Discovery

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#18962]
## Product Links
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [HealthRecord Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/health-record.md)
- [Medications Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md)
- [Allergies Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/allergies.md)
- [Immunizations Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/immunizations.md)

## Description
Beginning to plan and explore the Health Record initiative, including medications, immunizations, and allergies features.

## Tasks
- [x] [Think through questions that we have](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/health-record#questions-we-have)
- [X] [Think through knowns](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/health-record/README.md)
  - Documentation also in medications, allergies, and immunizations feature files
- [x] [Think about what internal VA groups we need/want to talk to](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/health-record/interviews.md)
- [X] [Begin thinking about what questions we want to ask Veterans about](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/health-record/README.md)
- [X] [Draw a map of the landscape of medications at the VA](https://www.sketch.com/s/f84952b4-9e8b-457d-b25e-5015c92e3913/a/g00Vbvq). Kind of like a customer journey and all the meds touch points at the VA.
- [x] [Storyboard](https://www.sketch.com/s/f84952b4-9e8b-457d-b25e-5015c92e3913) (very high level) of where this feature could go

## Acceptance Criteria
- [X] Add any documentation/ideas to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/health-record.md

**Comment by kristenmcconnell** [comment]
Started to review past Medication research (particularly on Rx Refill) and look at current MyHealtheVet capabilities. Added anything that could be applicable here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/health-record/README.md

**Comment by abuckley3385** [comment]
@kristenmcconnell - FYI i updated the tasks with the two areas you wanted to start on.

**Comment by kristenmcconnell** [comment]
[Immunization vision storyboards](https://www.sketch.com/s/f84952b4-9e8b-457d-b25e-5015c92e3913) can be seen on Sketch Cloud now.

**Comment by kristenmcconnell** [comment]
[Allergy vision storyboards](https://www.sketch.com/s/f84952b4-9e8b-457d-b25e-5015c92e3913) are in Sketch Cloud as well. The use case scenarios were also added to the [Allergies feature file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/allergies.md) along with links to the associated storyboard.

**Comment by kristenmcconnell** [comment]
[Medication vision storyboards](https://www.sketch.com/s/f84952b4-9e8b-457d-b25e-5015c92e3913) are in Sketch Cloud as well. The use case scenarios were also added to the [Medication feature file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md) along with links to the associated storyboard.

**Comment by kristenmcconnell** [comment]
[Medications landscape map](https://www.sketch.com/s/f84952b4-9e8b-457d-b25e-5015c92e3913/a/g00Vbvq) is in Sketch Cloud and link to from the [Medications feature file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md).

**Comment by kristenmcconnell** [comment]
@abuckley3385 I updated all of the vision boards based upon your comments.
