### ISSUE TITLE
Remove feature toggle for address work on HCA

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18969]
## Tasks
- [x] Remove the feature toggle that controls whether the home address question is available

## Acceptance Criteria
- [x] Ensure that the release of the address work has gone smoothly
- [x] Understand how SIP forms will be impacted
- [x] Ensure that SIP forms will be safely migrated
- [ ] The SaveInProgress bug should be fixed
- [ ] All previous positive QA checks should still be positive 
---
## Steps to reproduce for testing
- Unauthenticated
  - "Yes" mailing is the same
    - **Expected**: Two address as with label “Mailing” then with “Home” sent as `veteranAddress` (mailing) and `veteranHomeAddress` (home). `veteranHomeAddress` in the data is same as mailing.
    - **Actual**: :white_check_mark: As expected. Filled in both "mailing" and "home" (with different addresses) and went back to click, "yes, home is same as mailing" and it sent data as expected.
  - "No" mailing is not the same
    - **Expected**: Two address as with label “Mailing” then with “Home” sent as `veteranAddress` (mailing) and `veteranHomeAddress` (home).
    - **Actual**: 

- Authenticated
  - with Mailing & Home in Profile
      - **User**: 100
      - **Expected**: Address labled "Mailing" populated by mailing address in profile "same as mailing" question defaulted to "no" - Address labled as "Home" populated by home address in profile.
      - **Actual**: :white_check_mark: As expected.
  - with Mailing and Home (same as mailing) in Profile
      - **User**: (unknown - Jonathan may have in notes)
      - **Expected**: EZ askes for 2 addresses. Mailing is populated, "Yes, home is same as mailing" is pre-selected. `veteranAddress` and `veteranMailingAddress` is sent to the api, and they both have the same value (same address).
      - **Actual**: :white_check_mark: As expected.
  - with No addresses in Profile
      - **User**: 113
      - **Expected**: No prefill would happen, both addresses are collected in the EZ.
      - **Actual**: :warning: As expected but contains SiP bug (needed to refresh for second address).
        - :beetle: After starting the application, but before filling in any information, I went to profile to see my attributes, then went back to the form. The EZ only asked for one address (as it did in the previous day's test).
        - :question: When entering SSN for user 113, an input error ("Please enter a valid 9 digit SSN (dashes allowed)") prevented me from continuing through the form.

** bug should be fixed and all green checks should be unaffected from this iteration **

All of these steps were pulled from @kevinmirc previous QA testing document [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/87c173bc05dabb931f8bd26ffe8cb19fb8046680/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/use-cases.md#feature-toggle-set-to-on-both-address-questions-available-1)

**Comment by mchelen-gov** [comment]
Note: checks can be done in Review Instance

**Comment by kevinmirc** [comment]
FYI on testing: We are not able to update users' profiles in the RI environment (due to some kind of bug or unsupported feature in RI env). When updating a profile, changes aren't saved. So in order to do these test scenarios, you have to find users with the profile structure that you need (versus updating a user's profile to be in the structure you need).


https://user-images.githubusercontent.com/7391284/107408175-9d54e980-6ad8-11eb-97e0-7761992b57c9.mov

**Comment by jonathanjnelson** [comment]
## Testing on RI 

## Unauthenticated
  - "Yes" mailing is the same
    - **Expected**: User will navigate to the Veteran Information (email/telephone) - User can edit on the review page 
    - **Actual** :white_check_mark:  As expected
   
- "No" mailing is not the same
    - **Expected**: User will navigate to the "Home address" - User can edit on review page
    - **Actual** :white_check_mark:  As expected
   
## Authenticated
  - with Mailing & Home in Profile
      - **User**: 275
      - **Expected**: Address labeled "Mailing" populated by mailing address in profile "same as mailing" question defaulted to "no" - Address labeled as "Home" populated by home address in a profile.
      - **Actual**: :white_check_mark: As expected.


  - with Mailing and Home (same as mailing) in Profile
      - **User**: 
      - **Expected**: EZ askes for 2 addresses. Mailing is populated, "Yes, home is same as mailing" is pre-selected. `veteranAddress` and `veteranMailingAddress` is sent to the api, and they both have the same value (same address).
      - **Actual**: Unknown - **Need tasting in staging** 

  - with No addresses in Profile
      - **User**: 
      - **Expected**: No prefill would happen, both addresses are collected in the EZ.
      - **Actual**:

**Comment by jonathanjnelson** [comment]
Due to the constraints of the review environment ([being unable to update profiles](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20021)) we are unable to conduct further testing on this ticket until we push to Staging

**Comment by kevinmirc** [comment]
@jonathanjnelson @ala-yna 

Can you please list the scenarios you were unable to test because of the inability to update a user's profile (in a RI).

**Comment by ala-yna** [comment]
The last two - 

1) Mailing and Home addresses are the same in Profile
2) No addresses in Profile

**Comment by jonathanjnelson** [comment]
Completed testing in staging:  

 - with Mailing and Home (same as mailing) in Profile
      - **User**: 275
      - **Expected**: EZ askes for 2 addresses. Mailing is populated, "Yes, home is same as mailing" is pre-selected. `veteranAddress` and `veteranMailingAddress` is sent to the api, and they both have the same value (same address).
      - **Actual**: 

  - with No addresses in Profile
      - **User**: 
      - **Expected**: No prefill would happen, both addresses are collected in the EZ.
      - **Actual**:
