### ISSUE TITLE
Create Github md document for Custom Tracks questions

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#18972]
## Issue Description
This document will serve as a reference guide for VFS teams. It will show them what questions we ask, why we ask those questions, what is the outcome of each answer and how that will impact them throughout their build.

---
## Tasks
- [x] Take questions from the Wizard V3 flow and transcribe them into a markdown file.
- [x] Provide examples for each question asked. 
- [x] Make this document accessible via the Collaboration Cycle README page.
- [x] Ensure the document is in alignment with the [Custom Tracks Release Plan.](https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/17278)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
