### ISSUE TITLE
[FSR] Clicking the 'save' button on the default list loop card breaks the form

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18974]
## Issue Description
Clicking the 'save' button on the default list loop card breaks the form 
**How to recreate the bug in staging:**
1. Navigate to Step 2: 'Your employment history'
2. Select 'yes' for, "Have you been employed within the past two years?"
3. Select 'yes' for, "Are you currently employed?"
**Bug 1:** Selecting the 'save' button on the default payroll deduction card breaks the form
   - Ideal experience: Selecting the 'save' button shouldn't break the form. Ideally I think we'll want to have some kind of messaging like, "Please include a type of payroll deduction and deduction amount" without making it required. This seems like it may have complications with the form system schema, so for now we should just make sure the form isn't breaking. 
**Bug 2:** Repeat steps 1-3, then add another payroll deduction. Selecting the 'save' button on the default card breaks the form as well.
   - Ideal experience: Please see the experience under bug 1

Please refer to this video to see a visual of the bug:
https://images.zenhubusercontent.com/133843125/abfd05c9-4d73-4bc9-9d2e-3511df85a232/screen_recording_2021_01_25_at_4_27_22_pm.mov

---
## Tasks
- [ ] _Resolve the bug that breaks the form when 'save' is selected on the default list loop card_

## Acceptance Criteria
- [ ] _Selecting 'save' on an empty default list loop card matches the outlined ideal experience_
- [ ] _The solution has been pushed to staging and reviewed by a designer_
