### ISSUE TITLE
Update TUD account population rakefile to overwrite existing accounts

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#18975]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The current iteration of the TUD account population rakefile pulls test account user data out of the test_users.csv file and writes it into the vets-api database, but does not have handling removing existing TUD accounts; running the script multiple times

---
## Tasks
- [ ] Ensure running population rakefile properly purges existing "standard" users and recreates them to avoid duplicate test user creation

## Acceptance Criteria
- [ ] The testing team can manage the list of standard users by updating the list and pushing the changes in the vets-api repo, then running the population script again to replace the old standard test users with updated ones.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
This story is no longer necessary due to the decision to abandon using a version-controlled .csv file as the source of truth and instead using the TUD API DB table itself instead. An initial population script will still be run once to seed the DB with the primary users but will not be used after, so there will not be any concerns about it ignoring vs. overwriting conflicting test accounts.
