### ISSUE TITLE
Add schema and uiSchema for remove child workflows in manage dependents

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#18983]
## Background
Now that schemaform has been used to create a basic form, we need to align with mockups to create a form usable by the 686c endpoint. This is for all the `remove child` workflows

## Considerations
- [mockups](https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/f272c2e9-8983-4228-8bab-916eede80e0a?x_product=cc-slack%2F1.5.1)

## Tasks
- [x] Add redux, schema, uiSchema
- [x] Submit a PR for review

## Acceptance criteria
- [x] The data from the form fields in a formlet is picked up and stored in redux, and accessible for form submission.
- [x] A PR has been submitted for review

**Comment by jason-gcio** [comment]
May merge with the other one

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/16130
