### ISSUE TITLE
Implement Facility Locator error messages (post form system converstion)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18980]
## Issue Description
So that the Facility Locator can fall into line with the design system and use accessible error messages, we had to convert to the form system. Now that we have implemented the form system, we need to implement accessible error messages. 

---
## Tasks
- [ ] Implement error messages consistent with design spec
- [ ] Add cypress and unit testing

## Acceptance Criteria
- [ ] Sign off from accessibility and design teams
- [ ] Appropriate tests are in place
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
closing as duplicate to #18351
