### ISSUE TITLE
 [Epic] MyVA copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18989]
## Background
This is a ticket to track copy for MyVA 2.0 

## Tasks
- [ ] Matt creates tickets for each case below
- [ ] Tressa/Cassandra add info to tickets
- [ ] Peggy reviews each ticket

LOA1 user

LOA3 First-time user experience

LOA3 user who has everything

LOA3 user who has things but has no updates

**Comment by Samara-Strauss** [comment]
This appears to be a duplicate of #18991. Closing, but feel free to reopen if there is a meaningful difference I'm unaware of.

**Comment by mshea0606** [comment]
Nope, forgot to delete this one. Thanks!
