### ISSUE TITLE
Add Logic to Pick Up Data in Form Components for `Spouse`

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#18981]
## Background
Now that schemaform has successfully been used to build a basic form with inputs, we need to align with the mockups and build out more robust schemas and uiSchemas for the `remove spouse` workflow. 

## Consideration
- [mockups](https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/f272c2e9-8983-4228-8bab-916eede80e0a?x_product=cc-slack%2F1.5.1)
- Do we need a new endpoint to work with this?
- If the payload is the same can we use the same endpoint as the full 686?

## Tasks
- [x] Add schema, uiSchema, and redux for filling out a form and storing the data
- [x] Submit a PR for review

## Acceptance criteria
- [x] The data from the form fields is stored in redux and accessible for submission to backend.
- [x] A PR has been submitted for review
