### ISSUE TITLE
Editorial experience: heading levels

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18986]
## Issue Description
Josh identified a DEFECT-2 headings level issue occurring inside the "Prepare for your visit" accordions. 

Headings on the page should increase by one in a logical order. The absence of headings within the accordion elements caused a skipped level between the `h2` and `h4` headings on the page. 

The Facilities team is resolving the issue by placing the accordion buttons within a `h3` so that no editing would need to be done to the collapsible content's headings.

We need to address the editorial experience to ensure that editors are able to only add H4 and above so that this defect is not able to recur.  This issue blocks delivery of our defect resolution. 

## Tasks
- [ ] Restrict content editors from adding headings below an H4 inside accordions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevwalsh** [comment]
While it's possible to lock down the heading options, i think this implementation pattern (rich text editors with unique heading rules, depending on the context) might not be the most sustainable or scalable approach. 

The "Prepare for your visit" section with accordions driven by rich text fields was an MVP implementation, and the original goal was to harden these fields down, so that editor-submitted headers could be removed altogether, and the associated risk to accessibility.  

Substantial research was done on the content model for Parking, for example, and it was determined (september 2019) that this accordion could easily be "fieldable". (new information may have arisen to suggest slightly different content design or requirements) 

<img width="720" alt="VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr" src="https://user-images.githubusercontent.com/643678/105786142-7def8580-5f4a-11eb-81d2-69dcc954a44d.png">

similarly, we should have enough data across facilities to harden the content model for Transportation. 

<img width="785" alt="VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr" src="https://user-images.githubusercontent.com/643678/105786246-aecfba80-5f4a-11eb-88ad-9462c98c3119.png">

In the absence of content model hardening (or as an interim solution) perhaps we can look at improved help text on this part of the Facility form, to explain what headers should be used. 

Another option is to remove the possibility of headers altogether, a solution we support in other parts of the CMS.

I've created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4084 where we can consider various approaches to this problem.

**Comment by jilladams** [comment]
@laflannery FYI this also exists. It's an old case, and could potentially be helped by magical headers, when they're ready.

**Comment by laflannery** [comment]
@jilladams I agree that these could potentially be harden more using magical headers
