### ISSUE TITLE
Pass `operationalHoursSpecialInstructions` field to Facility Locator front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18987]
## Issue Description
VAST administrators have included a new `operationalHoursSpecialInstructions` field that is now in Lighthouse. We need to pull in this field to use in the Facility Locator. 

This field has 4 possible values at this time and more than one value can be present. 

![image](https://user-images.githubusercontent.com/55411834/105777461-a3b76300-5f27-11eb-9e6a-13aed9497a10.png)

 Data may need to be scrubbed to make formatting appropriate for displaying (ie: remove pipes)-> will be handled separately

---
## Tasks
-[ ] Pass `operationalHoursSpecialInstructions` field to front end for rendering on detail pages for VHA locations (medical and Vet Centers)

## Acceptance Criteria
- [ ] Front end has access to `operationalHoursSpecialInstructions` field
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
<img width="1357" alt="Screen Shot 2021-02-08 at 10 57 59 AM" src="https://user-images.githubusercontent.com/100468/107254184-aec8c380-69fc-11eb-900b-36f9df873571.png">
