### ISSUE TITLE
MyVA 2.0 copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18991]
## Background
This is a ticket to track the copy review for MyVA 2.0 

[Documentation invision link](https://vsateams.invisionapp.com/share/H8ZWCZGV52S#/screens/443197287)

## Tasks
- [x] [Design] MyVA LOA1 copy #18990
- [x] [Design] MyVA LOA3 First-time user experience copy #18992
- [x] [Design] MyVA LOA3 user who has everything copy #18995
- [x] [Design] MyVA LOA3 user who has everything but has no updates #18996
- [x] [Design] MyVA Cerner copy #19002 (Danielle Thierry also reviewing)
- [x] Evaluate new My VA title #13738
- [x] Copy has been reviewed and finalized

**Comment by Samara-Strauss** [comment]
All tasks are complete.
