### ISSUE TITLE
Find a VA Form - Add 'Sort by Last Updated' feature x Collab Cycle Plan

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19007]
## Product Outline
[Link to Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md)

## Plan
- [x] **[Define] Kickoff-Intent** - [18838](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18838)
- [x] **[Define] Design intent** - #(ticket)
- [x] **[Discover] Usability Testing Prep** - #(ticket)
- [x] **[Discover] Research Plan Review** - Not required per Shira following kickoff meeting
- [x]  **[Discover] IA Request** - Not required per Shira following kickoff meeting
- [x] **[Discover] Analytics Request** - #[18525](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18525)
- [x] **[Build] Contact Center Review** -[19027] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/19027
- [x] **[Build] Privacy/Security Review** [207](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/207) - per [this Slack thread](https://dsva.slack.com/archives/G01HB818B9V/p1611674746000100), Michael Fleet and Joe Niquette advised a full review wasn't necessary since we'd just had a review and are making such a minor change.
- [x] **[Build] Pre-Staging Review activities**
  - [x] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=staging-review-accessibility-checklist.md&title=%3CInitiative%3E+x+Staging+Accessibility+Checklist) - #(ticket)
  - [x] [Compile QA test cases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=product-use-cases.md&title=%3CProduct%2FInitiative%3E+Use+Cases) - #(ticket)
  - [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=product-release-plan.md&title=%3Cproduct%2Finitiative%2Ffeature%3E+x+Release+plan) - #[Link to release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/sort-by-last-updated/release-plan.md)
  - [x] [Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Kimberley+Daniels%2C+Chante+LantosSwett&labels=contact+center%2C+analytics-insights%2C+analytics-request%2C+collaboration+cycle&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTool%5D) - #(ticket)
  - [x] Request QA test plan - #(ticket)
- [ ] **[Build] Staging Review** - #(ticket)
  - [ ] Resolve Staging Review findings - #(tickets)
- [ ] **Launch** - Date (and/or ticket)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
  - [ ] Complete accessibility checklist in Prod - #(ticket if necessary)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Convert to an Epic**  
- [ ] **Labeled with Team**
