### ISSUE TITLE
[UNPLANNED] Fix for 686 Pension Question Not Being Saved

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19003]
## Background
One of the results from testing pension questions with BGS/RBPS was that the response for whether the household had an exceeded net worth was not showing displaying as answered.  After some debugging, it was discovered that we are sending the `netWorthOverLimitInd` field in the `vnpBnftClaimCreate` call but it is getting overwritten.  According to BGS, we need to also send it in the `vnpBnftClaimUpdate` call so that it doesn't get overwritten during the update.

## Tasks
- [x] Update the `vnpBnftClaimUpdate` call with the `netWorthOverLimitInd` field.
- [x] Tests have been updated as needed

## Acceptance Criteria
- [x] A PR has been submitted for merging.

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5769
