### ISSUE TITLE
Coordination to establish analytics dashboards

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19004]
## Description

The search and Discovery team has identified KPIs for the Typeahead POC as well as our KPIs. Analytics requests have been submitted for implementation. This issue is for SD team to coordinate with analytics to ensure they have the information that they need to establish the dashboard. 

## Background/Context/Resources

GH #18785 - Analytics KPI dashboard request for Search & Discovery [Typeahead POC]
GH #16778 - KPI Dashboard Request  [SD KPIs] 

## Tasks

- [x] Meet with analytics team to discuss KPIs identified and discussion questions.
- [x] Prioritize top 5 KPI metrics for our MVP Dashboard 

## Definition of Done

- [x] Analytics team has what they need and are ready to implement Search & Discovery Domo Dashboard

**Comment by denisecoveyduc** [comment]
Analytics team (Jon Wehausen and Jason Caviar) are ready to implement the dashboards for both typeahead POC #18785 and KPI #16778.
