### ISSUE TITLE
Search.gov Follow Up Discussions

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19011]
## Description

As an outcome of #18475 the search and discovery team has follow up questions for the search.gov team (as outlined below). We need to circle back and iron out the remaining questions over email to ensure clear communication and context for the below inquiries. 

## Search.gov Discussion Topics

**_Questions from original Email:_**
- Validate Analytics Assumption: Reviewing analytics when we type in the search term, does that further break down subsequent terms related to that query? (i.e if forms is a top search term and we search for forms we can see the top search terms as they relate to forms)
- Search.gov Documentation: Where is the source of truth on what search.gov can offer? Search.gov or GSA?
- Search Result Page Information: How customizable is the search results page? How is the results description information selected? Could we remove the url? Can we manipulate the text: Search description/Truncated breadcrumb/header information? Can we take out header/footer content on search results?
- Results Relevancy: How is relevance determined? Can we change what ends up as a top result?
- Similar Search Terms: Users also searched for this”
- Other VA.gov Search Engines: Ability to pull in results from other search features? (Ex: Find a form, find a facility, MyHealthyvet)
- Ignore Stop Words: Can it be programmed to ignore prepositions, articles, conjunctions that appear in most documents and are unlikely to be distinctive for any one of them?

**_Questions from SD Team Debrief Discussion (post meeting):_**
- What does the search.gov Roadmap look like right now? When will collections happen? What are the benefits/new features of the elastic search upgrades?
- How can we ensure that we see updates to their roadmap? (example deprioritizing of collections is important for us to know.)
- How do we get access to their newsletter?
- Could we get a sense of other API Clients that use search.gov? 
- How many API Clients versus non API Clients
- Two main knobs to explore - threshold for determining that a search is “trending”, and lifespan for a “trending search” before it falls off the suggestions list.
- Can we filter out spelling errors from type ahead suggestions? 

- Add a few questions about routed queries to better understand implementation

## Tasks

- [x] John to email search.gov (put S+D team on cc for reference)
- [x] Communicate with search.gov team to ensure clear communications and collect answer to our questions. 

## Definition of Done

- [x] All questions have been answered and there are no outstanding points of clarification
