### ISSUE TITLE
[FE] Adding Appt Information and layout updates for Demo /Confirmation Pages 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#19019]
## User Story
As a veteran, 
I want to see the my appt. details on the questionnaire, so that I know what visit and care team is receiving my information.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/600080c76d298d2157a8c5dc)

## Description
Update the Questionnaire Form. The updates on the Demographics and confirmation page. 

## Tasks
- [x] Update the appointment information on demographics page
- [x] Update the Confirmation page - layout and content and adding appt information
- [x] Step Titles should only have first letter Cap.
- [x] Confirmation page buttons secondary vs. primary 
- [x] [Add missing period](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16039#issuecomment-767853961)
- [x] Timezones.
- [x] Create user tests

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by kristenmcconnell** [comment]
@mdewey A period is missing after the facility locator example in the Need help? section as well. It should be...."Contact your VA provider."

**Comment by mdewey** [comment]
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-answer-questions-confirmation-2021-01-29-10_52_24](https://user-images.githubusercontent.com/1793923/106298324-c0061900-6221-11eb-908e-2fd482fa309a.png)
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-answer-questions-veteran-information-2021-01-29-09_47_58](https://user-images.githubusercontent.com/1793923/106298328-c1374600-6221-11eb-92b7-f4adc50a81fa.png)


@kristenmcconnell  For a tighter feedback loop, here are the screen shots of the form updates. Let me know what you think

**Comment by kristenmcconnell** [comment]
![Artboard.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/eb87f469-12f0-426e-9183-bc119ae09e90)
![Artboard 2.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/507ab7cf-4ddc-4f36-82e5-0467d77ce53f)

Overall, the changes look good. Here are just a few things that I caught. Also, I'm not super tied to the day of the week information, if that ends up being a problem.

**Comment by mdewey** [comment]
Thank you @kristenmcconnell! 

For summary 
- [ ] Day of week, on both pages
- [ ] h2 is missing
- [ ] header wording on confirmation page
- [ ] phone wording

**Comment by mdewey** [comment]
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-answer-questions-confirmation-2021-01-29-14_13_40](https://user-images.githubusercontent.com/1793923/106318063-3fedac80-623d-11eb-8b4c-d913217e4d22.png)
![screencapture-localhost-3001-health-care-health-questionnaires-questionnaires-answer-questions-veteran-information-2021-01-29-14_21_04](https://user-images.githubusercontent.com/1793923/106318066-411ed980-623d-11eb-948a-d37e73a50b61.png)


@kristenmcconnell  Updated screenshots. Do you see anything else?

**Comment by kristenmcconnell** [comment]
Looks good. I will still want to check the responsiveness of the pages, but all the correct wording is there, in the right order, and with the correct styling.

**Comment by mdewey** [comment]
@kristenmcconnell  and @abuckley3385 This is in staging.

Can you verify that everything looks good?

**Comment by kristenmcconnell** [comment]
The only thing I wasn't able to see was if the period was added after the phone numbers. I was only able to see the period was added to the "Contact your VA provider." facility locator link text.

Everything else looked good.

**Comment by abuckley3385** [comment]
looks good to me.

**Comment by mdewey** [comment]
Thanks @abuckley3385 

@kristenmcconnell , Here is one with the clinic phone number https://staging.va.gov/health-care/health-questionnaires/questionnaires/answer-questions/introduction?id=195bc02c0518870fc6b1e302cfc326b60

and here is one with the facility number https://staging.va.gov/health-care/health-questionnaires/questionnaires/answer-questions/introduction?id=195bc02c0518870fc6b1e302cfc326b59

**Comment by kristenmcconnell** [comment]
Interestingly...this is what I see when I click those links before I sign in.

![Screen Shot 2021-02-04 at 2 07 32 PM](https://user-images.githubusercontent.com/66287082/106942774-930aa800-66f2-11eb-9a04-ed55f47c586b.png)

This is basically an example of something that could be bookmarked, correct? Weren't we sending them directly to sign in?

**Comment by kristenmcconnell** [comment]
Besides the above comment/question. The screens look good. I saw that the period was added.

**Comment by mdewey** [comment]
Interesting. I have never tried clicking those links without being logged in. I will add a ticket to refine that.
