### ISSUE TITLE
[BE] Implement GET questionnaire manager list endpoint

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#19015]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the questionnaire manager interface to coordinate with all the services which interact with MAP and Lighthouse PGD and return to the UI(front-end) a consumable data structure

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- Create a Questionnaire Manager code module in the back-end that interfaces with all of the health-quest services which in turn interact with the MAP/MAS and the Lighthouse/PGD services.
- This module will ultimately return an aggregated data structure when invoked by the frond-end.

## Tasks
- [x] Create the code files and directory structure for the questionnaire manager within the health-quest service namespace
- [x] Create the test directory structure inside the relevant spec directories
- [x] Return mock appointments hash for the appointments index route in the development environment
- [x] Write code that interacts with and calls functions on the health-quest Patient service code module
- [x] Write code that interacts with and calls functions on the health-quest Appointment service code module
- [x] Write code that interacts with and calls functions on the health-quest Questionnaire service code module
- [x] Write code that interacts with and calls functions on the health-quest QuestionnaireResponse service code module
- [x] Write code that interacts with and calls functions on the health-quest Save in Progress module
- [x] Implement multi-threaded calls to the PGD
- [x] Write code that aggregates data from all the different service calls and then creates a consumable data structure for the front-end

## Acceptance Criteria
- [x] The back-end Questionnaire Manager module must return an aggregated data structure with the appropriate keys and values containing the information required to display the front-end Questionnaire Manager list to a patient
- [x] Front-end dev approval required
