### ISSUE TITLE
[BE] GET Questionnaire by a use context

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#19018]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the backend to retrieve Questionnaire resources by a given Use Context

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- when the veteran selects to view their questionnaire manager - the API submits a request to Map for clinic and facility ID for an appt. to Lighthouse so that we can get the questionnaires for a Veterans appt. 
- hardcoded list of the clinic and facility ID for MVP

## Tasks
- [x] Configure the options-builder module in the health-quest service to gather UseContext data from the calling resource factory module.
- [x] Create the proper query parameter string for the UseContext data using the options-builder module
- [x] Pass the UseContext query parameter to the associated MapQuery module
- [x] Ensure that the lighthouse PGD service is called with the UseContext parameters and that the Questionnaire bundle is returned.

## Acceptance Criteria
- [x] Create an endpoint to retrieve Questionnaires by a Use Context; Facility and Clinic id combination so that #19015 can generate the aggregated from the retrieved questionnaires for the front end to display the Veterans Questionnaire list.
