### ISSUE TITLE
[FE] Implement Error Messages

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#19024]
## User Story
As a veteran, 
I should see relvatent error messages
So I know the status of viewings and submitting my questionnaire.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/600080c76d298d2157a8c5dc)

## Description
Implement the error messages from the Design team.  

## Tasks
- [x] PGD is down message. on Submit page 
- [x] Printing was unsuccessful on questionnaire list
- [x] Printing was unsuccessful on confirmation. 
- [x] Figure out a way to validate the error messages work. 
- [x] Create user tests
- [x] Turn error off. 

## Acceptance Criteria
- [x] Passes Accessibility checks using axe
- [x] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
The error message for the form is in staging. @kristenmcconnell  and @abuckley3385  As you two sign off, I will update the form to no longer be busted.

**Comment by kristenmcconnell** [comment]
@mdewey I was able to review the error messages on the review page and the Questionnaire List. They both looked good. Due to the one error state on the review page, I couldn't check the one on the confirmation page (unless I'm missing something - which could happen).

**Comment by mdewey** [comment]
Awesome! I will enable the form again today :-)

**Comment by kristenmcconnell** [comment]
The error message on the confirmation page looks good. In the process, I noticed something on the confirmation page that I didn't see before. The View and Print button has an arrow on it (which it shouldn't have in this instance). 

<img width="704" alt="Screen Shot 2021-02-09 at 11 44 23 AM" src="https://user-images.githubusercontent.com/66287082/107397422-a213a080-6acc-11eb-9688-f495f0ce90e7.png">

**Comment by mdewey** [comment]
Fixes in PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15989

**Comment by abuckley3385** [comment]
i am not able to see _PGD is down message. on Submit page_ is there one I should look at?

On the confirmation page I see the error in printing. I follow the instructions in the message which says to refresh the page.  Page refresh takes the user to the Ques. Manager Todo tab.  I get why its doing that but just thought I'd check if there was a way on page refresh if we can't stay on confirmation page can they at least be directed to Completed tab?  @kristenmcconnell if you have another idea throw it out.  Also not worth holding up this ticket from completion we can add a new ticket if we decide to change the flow.

**Comment by kristenmcconnell** [comment]
The View and Print button looks good now. Good catch @abuckley3385. I did not refresh when I was reviewing the workflow. Your suggestions make sense from a workflow perspective to me.

**Comment by mdewey** [comment]
I will create a ticket to track this and then close this ticket.
