### ISSUE TITLE
Incorporate completed form download into FSR confirmation screen

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19022]
## Issue Description
We'll be able to offer completed form downloads to veterans upon submission of the form, with a delay of only a couple of seconds. Create a design to incorporate this action into the mockups.

---
## Tasks
- [x] Create designs for download
- [x] Create a ticket for FED 

## Acceptance Criteria
- [x] Designs synced to UXPin and linked below
- [x] FED ticket created and linked below

**Comment by rebeccawalsh** [comment]
[Designs can be found here](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134209101/simulate/sitemap?mode=i)!

[Frontend ticket here](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19397)
