### ISSUE TITLE
Document design changes for list loop error states

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19030]
## Issue Description
When there is an error on the list loop inputs, the card distorts. Document the intended design pattern with the feedback given in the DSVA design channel. 

---
## Tasks
- [x] Document intended design
- [x] Create a ticket for FE to make changes to existing form

## Acceptance Criteria
- [x] Design synced to UXPin and linked in this ticket
- [x] FE ticket created and linked to this ticket

**Comment by rebeccawalsh** [comment]
We tried a few variations for this issue but came back to simply ensuring the error state defaults to the same line rather than bumping the error-ed input down to another row, like in the following screen capture:
https://images.zenhubusercontent.com/133843125/f5f6d5c5-af57-4116-88d9-ceba4c621192/screencap_error.mov

We also decided that these fields should validate on 'save', if possible.

**Comment by rebeccawalsh** [comment]
[UXPin link](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19617)
