### ISSUE TITLE
Update 'Installment contracts and other debts' section to use inputs instead of radio selections

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19037]
## Issue Description
DMC has asked that we reintroduce text inputs for the date of debt and amount overdue questions on the 'installment contracts and other debts' section of the form.

---
## Tasks
- [x] Incorporate new inputs into the design and sync to UXPin
- [x] Create a ticket for FE work

## Acceptance Criteria
- [x] UXPin updated and attached to this ticket
- [x] FE ticket created and attached to this ticket

**Comment by rebeccawalsh** [comment]
[This update can be found in UXPin here](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134307869/simulate/sitemap)!
