### ISSUE TITLE
Review VAOS Dashboard Design

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19044]
## Issue Description
Brian has put together a KPI dashboard on Domo for the VAOS team. There are multiple charts and stories within this dashboard. We would like this dashboard reviewed for its design so that we're delivering easy to use, easy to read Domo dashboards.

[VAOS Dashboard Link](https://va-gov.domo.com/page/1769944412).

There are also sub dashboards on this page that can be reviewed as well.

---
## Tasks
- [ ] Review VAOS dashboard for design (content, colors, chart types, user flow, etc.)
- [ ] Work with @bsmartin-ep on any updates based on design feedback
- [ ] _Stretch:_ Review VAOS sub-dashboards for design

## Acceptance Criteria
- [ ] The VAOS team can easily navigate and read their Domo dashboard

**Comment by joanneesteban** [comment]
@mandy-uxd - I'm moving this to our backlog since editing this design is lower priority than getting folks new data.

**Comment by joanneesteban** [comment]
Closing this ticket. We're no longer supporting custom dashboards.
