### ISSUE TITLE
[FSR] Update written statement to be required when a waiver is selected

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19046]
## Issue Description
If a Veteran asks for a waiver, the DMC requires a written statement to be submitted along with the request, while other debt resolution options don't strictly require (but greatly benefit from) a written statement. We must make this written statement required when waivers are requested and also make the written statement more prominent for all submissions.

---
## Tasks
- [ ] Update the content and design of the written statement pages:
  - [ ] [If a waiver was requested](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/135943815/simulate/sitemap?mode=i)
  - [ ] [If no waiver was requested](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/135732390/simulate/sitemap?mode=i)

## Acceptance Criteria
- [ ] _FSR's UI has been updated and matches the linked designs_
- [ ] _UI has been reviewed by a BaM2 designer_
