### ISSUE TITLE
[BE] Create a comprehensive scope for the Lighthouse auth access token in the health-quest vets-api module

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#19059]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the vets-api requests for access tokens to the Lighthouse to have a comprehensive set of `scopes` in the request body

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- HTTP GET requests for access tokens made to the Lighthouse PGD must have `scopes` set in the request body so that the vets-api will be granted access to resources like Patient, Questionnaire and QuestionnaireResources

## Tasks
- [x] Configure the Token module in the lighthouse directory in the health-quest namespace to include a comprehensive list of scopes provided by the lighthouse team
- [x] additional scope to get appt. ID
- [x] write quest. responses

## Acceptance Criteria
- [x] Patient, Questionnaire and QuestionnaireResponse resources can be accessed from the PGD only when the scope has been set.
- [x] Access tokens without the appropriate scope will not be able to access the FHIR resources from the PGD
