### ISSUE TITLE
Questionnaire Manager production deploy checklist

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#19054]
## vets-website app checklist
- [ ] Enable the feature toggle in the production environment
- [ ] Check VA search result
- [ ] Check new form release criteria

## vets-api app checklist
- [ ] Check hqva_mobile configuration settings in the production Settings and DevOps YAML files and make sure all the values for the keys are production values
- [ ] Check that the production public/private key for Lighthouse has been installed in Credstash- Ops

## Database and datastore checklist
- [ ] Check that the production PostgreSQL DB has all the necessary tables and columns for the HealthQuest Engine.

## Lighthouse checklist
- [ ] Get the final green light from the Lighthouse team that their systems are a go in the production environment.
- [ ] Ensure that Lighthouse has installed the public key that was generated by the vets-api team in their system
- [ ] Confirm that production PGD and HealthAPI has the necessary data(Questionnaire/Appointments/Organization/Location/User resources) for the Loma Linda patients

## Vetext/VA-Notify checklist
- [ ] Ensure that the Vetext team has provided the Lighthouse team with the necessary public/private key pairs for the production environment
- [ ] Ensure production configuration(data and network) has been established prior to going live
- [ ] Ensure that the email and text template has been delivered and hooked up in the production environment

## Loma Linda/Jerry L Pettis integration checklist
- [ ] Ensure that the PVS system is operational and communicating with the Lighthouse's production environment

## Facilities API checklist
- [ ] Ensure that HealthQuest in production has permission to call the Facilities API in production
- [ ] Check if we need any credentials or extra configuration settings for the production release

## Ops checklist
- [ ] Ensure that network connectivity between vets-website, vets-api, Lighthouse, VA-Notify is operational
- [ ] Ensure that on-call pager duty is setup

## Platform checklist
- [ ] On-call team member during production verification/testing
- [ ] ?

## Engineering Risks
- [ ] Data availability and integrity
- [ ] High production traffic during the release and verification process
- [ ] Production systems like ID.me, VA Profiles being unavailable or unresponsive

**Comment by dillo** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/engineering/production-release
