### ISSUE TITLE
Setup the service harness to communicate with the future Lighthouse Appointment Service

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#19053]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** Amanda will update with the Lighthouse's health_api Appointment service to be setup

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- Create the basic code foundation for the new appointment service.
- In the upcoming ticket/story, we will mount relevant code modules on top. This will allow us to fetch appointments from the lighthouse health API and package it up for the frontend(UI) to consume.

## Tasks
- [ ] Create the directory structures where the code will be housed
- [ ] Create the folders for the RSpec tests
- [ ] Create the appointment routes in the configuration file(s)
- [ ] Create the basic controllers for routing the UI calls
- [ ] Ensure that token exchange with the health_api is happening and is being saved in redis

## Acceptance Criteria
- [ ] All tasks have been completed and the complete test suite is passing without any errors
