### ISSUE TITLE
[FSR] Fix employment sections to only ask for add'l employment if employment was indicated

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19069]
## Issue Description
Your employment history / Your spouse’s employment history:
When ‘no’ is selected for ‘Has your spouse been employed within the past two years?’, the next page is still, ‘Has your spouse had additional jobs in the past two years? (*Required)’

We should not be asking for additional jobs within the past 2 years if they indicated that they have not been employed within the past 2 years.

---
## Tasks
- [ ] Hide followup question for additional employment if no employment was indicated in the initial question
- [ ] Confirm behavior with designers (can be via screen recording)

## Acceptance Criteria
- [ ] Behavior fixed
- [ ] Behavior confirmed with designers
