### ISSUE TITLE
Current appointment cards - Add to calendar

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19060]
## Issue Description
The Add to Calendar feature for appointments should allow the user to create a calendar item with pre-populated appointment details.

### Specs
- Device: Macbook Pro, iPhone SE iOS14.2, Pixel 4 V11
- Browser: Safari, Chrome
- Test User _(if applicable)_: Judy Morrison

![IMG_3686 2.PNG](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f461fed9-4103-4337-9463-3986d0516af0)  ![IMG_8C866A3DF0E3-1.jpeg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/51a41178-e6b3-4bf6-b885-6abba937a443)  ![Screen Shot 2021-01-26 at 4.42.36 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/30c98c79-5f0b-416b-be74-0c10b104fa06)

---
## Tasks
- [ ] Desktop behavior

- [ ] Tablet/Mobile behavior

## Acceptance Criteria
- [ ] Given desktop device, When user clicks Add to Calendar, Then new calendar file downloads

- [ ] Given desktop file, When user opens file, Then new calendar item opens

- [ ] Given tablet/mobile device, When user taps Add to Calendar, Then new calendar item popup opens

- [ ] Given any device, When opening new calendar item, Then pre-populate the following fields:
  - Title = {appointment type label}
  - Location = {clinic address}, if applicable
  - Date and Time matching appointment card

## Out of Scope
- Homepage refresh (new feature toggle) appointments

**Comment by outerpress** [comment]
I ran into this on a Pixel 4/Android V11. On staging.va.gov when I clicked "Add to Calendar" and selected my gCal, I got the error "Unable to Launch Event"
