### ISSUE TITLE
Revisit FL front end direct connection to Lighthouse 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19065]
## Issue Description
Following a meeting in June 2020, the expectation was that the Facility Locator front end would connect through vets-api rather than directly to other endpoints. New information/considerations are now available and we need to revisit this decision. 

Reference [original issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9716)

---
## Tasks
- [ ] Identify security considerations (Lighthouse, CORS) for direct connection from front end 
- [ ] POC for direct connection from front end to Lighthouse

## Acceptance Criteria
- [ ] Results from POC
- [ ] We are prepared to revisit this conversation with VSP/Michael Fleet/Lighthouse 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
