### ISSUE TITLE
Disable issue tracker on component-library 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#19062]
## Issue Description
Disable issue tracker on component-library and link to DSC issue template in README

Link to Slack message in case you need more information. 
https://dsva.slack.com/archives/C5HP4GN3F/p1611093336033500?thread_ts=1610472673.307600&cid=C5HP4GN3F
Summary: The migration to the component-library repo doesn't introduce a change in the way we track issues for the component library.
va.gov-team is still the go-to for bug tickets, but if it's a request that should have a decision from the Design System Council (not DS team), then the design system council board is the right place for it.

---
## Tasks
- [ ] Disable issue tracker on component-library
- [ ] Link to DSC issue template in README

## Acceptance Criteria
- [x]  Disabled issue tracker on component-library
- [ ] Link to DSC issue template in README

**Comment by bkjohnson** [comment]
Issue tracker has been disabled.
