### ISSUE TITLE
Adjust icon for COVID-19 vaccines 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19063]
## Issue Description
Our COVID-19 vaccines alert has a disconnect between the icon used and the color. Blue typically is associated with the "info" icon, rather than the "alert" icon (which is currently in use). This should parallel the urgent care alert (which is correct).
 
[Design system reference](https://design.va.gov/components/alertboxes#informational-alert)

<details> 
<summary> Current implementation </summary> 

![image](https://user-images.githubusercontent.com/55411834/105895970-732d0300-5fd3-11eb-9979-8ffc5c5b0bf0.png)

</details>

---
## Tasks
- [ ] Replace alert icon (!) with info icon (i) for COVID-19 vaccines 

## Acceptance Criteria
- [ ] COVID-19 vaccines search results include a blue alert using the "i" info icon 
- [ ] All other functionality is maintained. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
looks good to me, @brangi thank you
