### ISSUE TITLE
[FSR] Ensure list loop cards are closed by default when stepping backwards in the form

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19068]
## Issue Description
Currently, there is some weird behavior surrounding the list loops and stepping backwards in the form. When stepping back, the cards should not be open by default.

1. Fill in the list loop card
2. Save
3. Continue to next page
4. Step back to find the card in an edit/open state

If there are multiple cards previously saved, you will see something like this:
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/337e1d23-f29d-463f-96bf-b1bf86a69b58)

---
## Tasks
- [ ] Ensure list loop cards are closed by default when stepping backwards in the form
- [ ] Confirm behavior with designers (can send a screen recording)

## Acceptance Criteria
- [ ] Behavior fixed
- [ ] Behavior confirmed with designers
