### ISSUE TITLE
[FSR] Hard-code contact information for staging usability

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19066]
## Issue Description
We want to prefill a couple of inputs in the unauthenticated experience for usability:

---
## Tasks
- [ ] Prefill first email input in contact section with ‘hector.smith@email.com’
- [ ] Prefill phone number with ‘555-123-4567'

## Acceptance Criteria
- [ ] Inputs show as prefilled in the unauthenticated experience
