### ISSUE TITLE
Add link on Higher-Level Review page to go to HLR application

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19073]
## Issue Description
Per a request from the Claims and Appeals team, we need to add a link with text on the [Higher-Level Review](https://www.va.gov/decision-reviews/higher-level-review/) page to point to the [HLR application page](https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction). 

See intake request ticket #18876 for more details. 

Page to link to: https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction

## Tasks
- [x] Write text to go with link to the HLR application
- [x] Add content to page
- [x] Review and publish

## Acceptance Criteria
- [x] Link is now on live site

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA My two suggestions for how to add this text are below. They would both be under the H2 for requesting an HLR 

**Option 1:**

H2: How do I request a Higher-Level Review?

To request a Higher-Level Review, fill out the Decision Review Request: Higher-Level Review (VA Form 20-0996). 

[Fill out VA Form 20-0996 online](https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction)
[Download VA Form 20-0996 (PDF)](https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf)

**Option 2:** This would use a CTA button like we do for other online applications

H2: How do I request a Higher-Level Review?

To request a Higher-Level Review, fill out the Decision Review Request: Higher-Level Review (VA Form 20-0996).

You can request a Higher-Level Review online right now.
CTA button: [Request a Higher-Level Review](https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction)

You can also fill out the paper form.
[Download VA Form 20-0996 (PDF)](https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @RLHecht!

I would definitely use a button CTA to emphasis the online form.

And then, we usually provide more info around the other options involving the paper form (by mail, in person, etc.).

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA We have the by mail, in person, etc. under step 4 of the subway map. I still think the CTA button should be above all that but if we are putting the link to the PDF in step four should we also put the online link there too? The subway map was throwing me because the setup is different from what we have on other pages with online applications.

**Comment by Mottie** [comment]
We have a design for this content already - https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/430329537 - I still see a reference to "fax" which I think needs to be removed

**Comment by RLHecht** [comment]
@Mottie I didn't realize this was created already. I thought the ask was putting in the CTA button on the page. So does this text need to be reviewed by Sitewide Content (I see a few things looking at the Invision). Will this be put on the page as a react widget?

**Comment by Mottie** [comment]
I created this injectable widget over a year ago - https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/996/components/createHLRApplicationStatus.jsx - with the intention to have it render this react component - https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/996/wizard/WizardLink.jsx - when the feature flag is set... but now I don't think it'll be necessary since the introduction page displays an alert saying HLR is still a work in progress and I think we're planning to ramp to up 100% rather quickly.

**Comment by Mottie** [comment]
And yes, it probably does need to be review by Sitewide Content since the design I shared is out-of-date

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I put into the Drupal page what was mocked up with a few tweaks. Can you take a look and let me know what you think? I was wondering if we should actually add a step 5 to the process list that would be "Submit your application." Right now it is under the same step as "Apply" but it seems like its own step. I also didn't change the accordions like how it was in the InVision because Drupal doesn't allow for accordions in a process list. Let me know what you think. Preview link: preview-prod.vfs.va.gov/preview?nodeId=3003

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I'm actually thinking @bethpottsVADEPO is better to look at this since she was more involved in the review work and since this is VBA. @bethpottsVADEPO do you want to look at this?

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close after live on site.

**Comment by RLHecht** [comment]
Changes live. Closing ticket. Will open up a new one if/when we make more substantive changes to the page to better align with our other pages.
