### ISSUE TITLE
Update School Type Field

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19072]
## Background
In testing, we learned that the school type needs to be designated as a discrete drop down ~~and not an open text field~~ and added in addition to the "kind of training..."

## Considerations
- Backend has ticket #19092 that should prove helpful

## Tasks
- [x] Update the [text field](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/686c-674/schema.js#L738) to be a **required** drop down, displaying these three options: high school, post secondary, home school.
- [x] Be sure they are named properly based on BE's findings for the actual string values to be passed
  - `HighSch`, `POSTSCNDY`, and `HomeSch`

## Acceptance Criteria
- [x] The frontend should reflect the drop down as shown above
- [x] Tests are updated to include these
- [x] A PR has been opened into `vets-json-schema`
- [x] A PR has been requested for merging into `vets-website`

**Comment by jason-gcio** [comment]
![school-type](https://user-images.githubusercontent.com/53826255/106038166-91fbca00-60a5-11eb-9b8d-3582fdf2f5b2.JPG)
