### ISSUE TITLE
[Design] FL Mobile search experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19076]
## Issue Description
As a Veteran using a mobile device to search on Facility Locator, I want the experience to be consistent with industry standards. 

## Background 

- In a mobile month study, veterans were not interested in using the map view of facility locator #14484
- The Facility Locator search experience has not been approached from a mobile-first perspective
- Planned changes include the implementation of two new usability features ("use my location" and "clear field") and the resolution of accessibility defects
- A separate mobile research session will be conducted with a specific assistive tech focus #18685

## Hypotheses

- The FL search experience could be better for mobile users. It is not aligned with Veteran expectations or other private industry map-based mobile search experiences. 
- Veterans searching on FL using a mobile device want to view useful facility information displayed independently from the list view. 
- Veterans need to be able to clear field inputs
- Veterans want to be able to opt-in to geolocation at search level, rather than via browser. 

- ---

## Tasks
- [x] Adapt [Mobile exploration designs from hackathon](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/images/Facility%20Locator%20Mobile%20Chris.pdf) to create a testable prototype to test hypotheses. 
- [x] Include planned ["clear field"](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16513) and ["use my location"](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17319) designs in prototype

## Acceptance Criteria
- [x] Testable mobile first prototype 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sshein** [comment]
cool to see this is going to be happening :)

**Comment by chrisdlogan** [comment]
Here is the URL to the working prototype: https://preview.uxpin.com/c60117d778b6116d11f6fc707a5ac6d953d91aa0#/pages/136040014?mode=chidfm

Included in prototype:
- Geolocation UI
- Clear text field UI
- Map pins which are active
- Cards can be swiped as an alternate way to navigate from pin to pin
