### ISSUE TITLE
Content review of Custom Tracks release

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#19077]
## Issue Description
VSP Product Support is preparing to release enhancements to the Collaboration Cycle the week of 2/15. We need to ensure that the voice and tone is consistent across all impacted documentation, as well as ensure that the documents adhere to plain language best practices and are free of grammatical errors. 

---
## Tasks
- [ ] Review the following documentation and ensure they meet VSP content standards:
   - [x] [Collaboration Cycle README](https://docs.google.com/document/d/1_1gGJW6Go0Kk-H5jttDbQIZrcbKTst9gSZnXKVdeQSg/edit#)
   - [x] [Collaboration Cycle Kickoff](https://docs.google.com/document/d/1QH77u8Roi_TtD7rhg1_Vel2wJwsTO4Au9pPkXNPxMmk/edit#heading=h.frsa63ovwv15)
   - [x] Collaboration Cycle Touchpoints, including:
      - [x] [Design Intent](https://docs.google.com/document/d/1JzdE-MPRZNAY5iseh3vidP0L_J6QZKO6tOtMMzAIUuM/edit#heading=h.e9bbaemgyxnn)
      - [x] [IA Request](https://docs.google.com/document/d/1LKHEjyORvevrx4aV6mV1Oq709oqyzb7H9nbYrMkqrXk/edit)
      - [x] [Research Plan Review](https://docs.google.com/document/d/1Kl3B2rmq0n7WCKbRdQ5q60na-4fLRin2rNlubfMfAzU/edit)
      - [x] [Analytics Request](https://docs.google.com/document/d/1LXajsoBdNRoqGXUVuP37VfSnTTK1a1UNeazfVl1eJ0s/edit#) (Joanne is still working on updating this. She should be pinging Peggy on Monday 2/15 when it's complete)
      - [x] [Midpoint Review](https://docs.google.com/document/d/133UMGNOwFc1VVYOjmdhPNSOYmPgsEUSlUzLic07ojJE/edit)
      - [x] [Contact Center Review](https://docs.google.com/document/d/1-HlUIZuCgYe-cPd3o1PXf7MOwf6OhohXs96UD1DWsSY/edit#heading=h.962557r9iiv6)
      - [x] [Staging Review](https://docs.google.com/document/d/1LoVXcGvXIjRTwD1HsIWNlliybESu5ZfG9P8yLzkaE3M/edit#)
      - [x] [Privacy & Security Review](https://docs.google.com/document/d/1RzxUxaFQazLsK8vTiL56fs66C1bBmHxfaj3UXfoo5ZQ/edit#)
      - [x] [Full Accessibility & 508 Office Audit](https://docs.google.com/document/d/1SeUrEV629mSSyWQ_5h-vssVBf9Ye4wdtldSEhjS0gu0/edit#)
      - [x] [Post-launch Check-In](https://docs.google.com/document/d/19ygrh9Ga3tx_X4onYpbCBFWxQefO8fvR6ciDqJ10g5k/edit)
   - [ ] [Collaboration Cycle visual](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf) (this has not been updated)
   - [x] [Scripts for Collaboration Cycle meetings](https://docs.google.com/document/d/1SzAwfYnFsxdNtNqXqgiiBV4B6LqFgptWqPJ-UrfWZMc/edit?usp=sharing):
   - Collaboration Cycle Kickoff
   - Midpoint Review
   - Staging Review
   - [x] Issue templates for Collaboration Cycle meetings:
      - [x] [Collaboration Cycle Kickoff ](https://docs.google.com/document/d/13VyRvFXMs5d41sYN8yUG3vqnddzKumJhzj0GcXGp8cE/edit)
      - [x] [Design Intent template](https://docs.google.com/document/d/1KJxHASYfXXIeAVretAe2cyhNVi8Xw5K0gnLZMxDMVgc/edit#)
      - [x] [Midpoint Review template](https://docs.google.com/document/d/17mIEXAOk2GAF8hTIx2Mxfxc06-TYrUKhsX14J2PcUP8/edit#)
      - [x] [Staging Review template ](https://docs.google.com/document/d/1ZshjS3pZNarKhebGnZ2gw536Er1o-_QmdjE-7oOt118/edit#)
   - [ ] Newsletter article - we didn't meet the February deadline so our announcement will be included in the March newsletter. We can follow up on verbiage after this release.
   - [x] [Rollout communication message for Slack](https://docs.google.com/document/d/1sS6y7qSoFxboDU3JbzojUKFYeeOWJXDLIkxThGdl0bA/edit) 
   - [x] [Release Announcement on Github](https://docs.google.com/document/d/1CzDYvNpHIHASgjrfDl5wGXwxhGr_MzixjjwenhTT5Jc/edit)

## Acceptance Criteria
- [ ] VSP Collaboration Cycle guidance and documentation meets VSP content standards.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@mnorthuis @peggygannon this should be ready for you all to review - everything is linked to the internal google docs, so all links will have to be updated once we move over to Github. Please feel free to make changes to the docs (maybe turn track changes on?) and we will discuss on Wednesday where we landed. I'll schedule a meeting to review.

**Comment by mnorthuis** [comment]
I reviewed docs and left a few comments/questions.  Once @peggygannon does her review, I can take another look to help finalize how we want to organize the content.

**Comment by peggygannon** [comment]
hello, @shiragoodman @mnorthuis I've completed my content review of the documents.( I didn't review the Visual doc, as we need to discuss if we're going to update this one.) 
I do think it would be helpful for me to review this documentation again once comments/suggestions have been accepted or resolved. 

I also think it would be helpful once the documents are updated to cross-check the Collaboration Cycle touchpoints documents against the issue templates to ensure content is aligned.

**Comment by shiragoodman** [comment]
hey @peggygannon @mnorthuis and @allison0034 - I have gone through and reviewed all of your comments and suggestions. Grammar/formatting suggestions have been accepted. There are a couple items I'd like to discuss as a group, so we will cover at our 1:30 meeting. At that time, we'll also put together a quick ppt for the demo today. Once everything is in alignment, we can begin updating/adding docs to Github. I'll work on creating a checklist for launch (should be pretty short). Thank you all for your help while I was out!
