### ISSUE TITLE
[FSR] Error handling bug within FSR's progressive disclosure

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19071]
## Issue Description
Some progressive disclosures are throwing errors for subsequent questions if the previous question threw an error

**How to recreate this bug in staging:**
1. Navigate to Step 2: 'Your employment history'
2. Select the 'continue' button to attempt to proceed to the next page. You should now see an error for 'Have you been employed within the past two years?' question 
3. Select 'Yes' for the 'Have you been employed within the past two years?' question
**Bug:** You should now see an error message for the 'Are you currently employed?' question
_Ideal experience:_ Errors shouldn't be displayed by default. The second error should only be displaying if the user attempts to proceed again without selecting a response. 

Note: The same bug is happening in multiple areas of the form, including the 'Your other income' page. The bug doesn't seem to happen if the next question in the progressive disclosure is a list loop. 

Please refer to this video for a visual of the bug: 
https://images.zenhubusercontent.com/133843125/1522d974-df97-48dc-98b5-5cc3dee1a21a/screen_recording_2021_01_26_at_3_32_42_pm.mov

---
## Tasks
- [ ] _Resolve the bug that's automatically throwing errors in the form's progressive disclosure interactions_
- [ ] _Test that none of the progressive disclosures in the form no longer have the identified bug_

## Acceptance Criteria
- [ ] _The error handling within progressive disclosures aligns with the outlined ideal experience_
- [ ] _The solution has been pushed to staging and reviewed by a designer_

**Comment by bradl3yC** [comment]
Per discussion here https://dsva.slack.com/archives/CBU0KDSB1/p1612192427089600 - there is no way to resolve this currently - moving to closed
