### ISSUE TITLE
Confirm Ch 31 Upload PDF to VBMS

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19088]
## Background
When a user submits a Chapter 31 claim/form, a PDF is currently being generated but needs to be uploaded to VBMS.

## Considerations
- Check With Derek in case he wants it in a job

## Tasks
- [ ] Ensure the PDF is being generated correctly from the form data
- [ ] After PDF generation, upload the file to VBMS

## Acceptance Criteria
- [ ] The Chapter 31 PDF gets successfully uploaded to VBMS when the form is submitted
- [ ] Test specs have been created/updated as needed
- [ ] A PR has been requested for merging

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5889/files
