### ISSUE TITLE
Set 674 Document Type When Uploading PDF to VBMS

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19089]
## Background
When submitting a 674, we generate a PDF and send it to VBMS but currently we are using the incorrect document type.  We need to set the document type that corresponds to the 674 form.

Document types can be found [here](https://github.com/department-of-veterans-affairs/caseflow-commons/blob/master/app/models/caseflow/document_types.rb)

## Tasks
- [x] Set the appropriate document type when uploading a 674 to VBMS

## Acceptance Criteria
- [x] The appropriate document type is being set when a user submits the 674
- [x] Test specs have been created/updated as needed
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5798
