### ISSUE TITLE
Add validation logic for form components

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#19085]
## Background
Once the formlet is in place for the View Dependents page we need to add validation logic to the form fields to ensure the user knows what they should and should not put in the fields as well as to make sure the data is of the highest quality.

## Considerations
- Not using the Form System means that we need to build field validation
- Notes from Micah: we might be able to use some of the parts from the Form System where we get the some of the benefits and might include field validation as well

## Tasks
- [ ] Research how form fields are validated in the form system ( what validations are used and how we check against them )
- [ ] Build out validation logic for the fields
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The formlets validate correctly according to VA.gov standards
- [ ] A PR has been submitted for review
