### ISSUE TITLE
Update VSP Orientation epic

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#19080]
## Issue Description
The [New Team VSP Orientation Epic Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=New+Team+VSP+Orientation) does not include items for BE Orientation, FE Orientation or Design Orientation. If new BE engineers, FE engineers, or Designers join a VFS team, the current process for getting them oriented involves Shira messaging the VSP POC on Slack to set up the orientation.
-    Travis Hilton - BE POC
-    Dan Shank - FE POC
-    Allison Christman - Design POC

The manual component of this process will be removed and instead, the New Team VSP Orientation Epic Template will be updated to include line items for BE, FE and Design. 

---
## Tasks
- [x] Update the New Team VSP Orientation Epic Template to include BE, FE and Design
- [x] Backend team approves changes and understands new process
- [x] Frontend team approves changes and understands new process
- [x] Designer (Product Support Team) approves changes and understands new process

## Acceptance Criteria
- [x] Scheduling orientation for new VFS team members is less manual
- [x] Orienting a new VFS team member does not "pigeonhole" a VSP team member in providing a face-to-face meeting on-demand

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@meganhkelley @alexpappasoddball I added you both as reviewers in the PR. Let me know if you have any questions/concerns about the changes. Thanks!
