### ISSUE TITLE
686 Update Manual Proc State Type Code

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19087]
## Background
During 686 testing, BGS asked us to update the proc state type from `MANUAL` to `MANUAL_VAGOV` so they can see that VA.gov is the application that is setting the claim to manual.  Note that this only applies to certain workflows that can not currently get processed by RBPS.  

## Tasks
- [x] Determine the work flows/use cases that are currently setting the status to `MANUAL`
- [x] Update the `MANUAL` status to `MANUAL_VAGOV` for all appropriate work flows

## Acceptance Criteria
- [x] The proc state type code has been updated in all relevant places, or just one for now for testing
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5826

**Comment by kathleencrawford** [comment]
This is the first PR and may require a second, but it will depend on the results of testing.

Currently, we set the status to `MANUAL_VAGOV` when RBPS can not process the claim.  BGS is asking that we always manually set it to `MANUAL_VAGOV` for certain workflows.  I'm hesitant to change the process this late during integration testing and lean more towards if it isn't broken don't fix it.  I'd like to test the referenced workflows in our next integration testing meeting and then if the change in this PR is not sufficient, we will implement the next set of changes.

**Comment by jason-gcio** [comment]
Applicable workflows
- death of a child
- child stopped attending school
- death of a parent
