### ISSUE TITLE
Determine Values for School Type Dropdown

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19092]
## Background
In testing, we learned that the school type needs to be designated as a discrete drop down and not an open text field.

## Tasks
- [x] Determine what the values are for these dropdown fields
- [x] Check EVSS or ask Shane/Linda

## Acceptance Criteria
- [x] The frontend has been informed of the values to be passed based on the dropdown selection in their ticket.

` No PR needed`

**Comment by kathleencrawford** [comment]
`HighSch`
`HomeSch`
`College`
