### ISSUE TITLE
Fix View Dependents When Veteran Only Has One Dependent

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19090]
## Background
During testing it was discovered that View Dependents is currently unable to render properly if the user only has one dependent.  BGS returns an array when multiple dependents are found, but returns an object if there is only one dependent.  The FE is expecting an array all the time, which is why the page is not displaying correctly when there is only one dependent.

## Tasks
- [x] Find a test user with only one dependent.
- [x] Update the return object to be an array of size 1.

## Acceptance Criteria
- [ ] The View Dependents call returns an array regardless of how many dependents are found
- [ ] Test specs have been created/updated as needed
- [ ] A PR has been requested for merging

**Comment by digitaldrk** [comment]
Found a user. It's 21, Chad (lol)

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5875
