### ISSUE TITLE
686 Determine How MPI is Mocked in Dev

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19091]
## Background
To complete testing for the 686, we need to be able to test against the BGS/RBPS/VBMS pre-prod environment.  Currently, our dev environment is mapped to BGS pre-prod, but we need to determine how to mock data for the BGS pre-prod users for testing.

## Considerations
- Long term, there is a bit of an issue here where we are working in staging but BGS has a few others and mapping to those without hacking dev.
- Be really cool if we could switch to different environments with a switch
- Do we need to form a mockdata file for each user?

## Tasks
- [ ] Determine how login/profile data is mocked.
- [x] Ask Charley or Cameron for guidance if needed. 

## Acceptance Criteria
- [x] A path forward has been determined
- [x] That path is documented in GH under the EBN engineering notes

## Next Steps
- [ ] Get pre-prod test MPI data from Don Moses(?)
- [ ] Create corresponding mock data to be used in dev for testing

**Comment by jason-gcio** [comment]
Test user ruat149testsmoke@noemail.com presents with no VA file number

**Comment by kathleencrawford** [comment]
Note: Charley sent an email on 05.24 to the BGS team asking for more information about how BGS environments map to MPI environments.

**Comment by kathleencrawford** [comment]
We received an email response from BGS on May 26th with information regarding how the environments are mapped.  

We need to connect with DevOps to come up with a plan for testing.  Possibly restrict it to a specific time/date range?
