### ISSUE TITLE
686 Document Uploads/Attachments

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19094]
## Background
During 686 testing, there was an error when trying to upload a document as supporting evidence.  We need to investigate to see why file uploads/attachments are not working.  Note that there were intermittent staging issues that day, so the error we saw could have been a side effect of staging issues in general.

## Tasks
- [x] Test the document upload to determine whether it is working consistently in staging
- [x] If not, determine what is causing the document upload to fail

## Acceptance Criteria
- [x] The cause of the document upload problem has been identified

**Next Steps**
- [ ] A solution/fix has been determined
- [ ] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
This feature is broken in staging but I'm not able to reproduce it locally.  I did notice that it is also broken for some other forms as well.  When I try to attach a PDF, I am getting a CORS error in the browser.  However, when I attach a PNG, the file upload works fine.  I've posted a question in platform support about this issue.

**Comment by kathleencrawford** [comment]
Apparently this issue has also been discovered by another team, and is being worked on by devops.  

https://github.com/department-of-veterans-affairs/va.gov-team/issues/14427#issuecomment-704285824

https://github.com/department-of-veterans-affairs/va.gov-team/issues/15687

**Comment by jason-gcio** [comment]
Another possible solution: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/enable-auth.conf.j2#L4-L13
