### ISSUE TITLE
Engage with Content/IA Team

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1909]
## Story
The Content/IA Team is an important component in ensuring that all products, features and pieces of VA.gov come together as a cohesive experience for the end user; the Veteran and their caregivers/dependents.

## Tasks
Engage with the Content/IA Team and introduce them to the new feature with a walkthrough with various highlights to help them better understand the goals of the product, see ticket #1965.

## Definition of Done
- [x] Schedule a meeting with the Content/IA (@meganhkelley)
- [x] Give walkthrough introduction of Rated Disabilities
- [x] Highlight language that are not part of the boilerplate CMS (navigation, sidebar, etc unless you are editing that)
- [x] Discuss the verbiage and share with Content/IA an easy to access document that they can edit as needed
- [x] Ask any questions if need be
- [x] Discuss the intended location and/or path to the feature

**Comment by jason-gcio** [comment]
@sporeboy - Is there anything else missing from this that we should capture ahead of getting feedback back from Content/IA?

**Comment by sporeboy** [comment]
My takeaways from the meeting:

--Content/IA didn't carefully review what we sent :-0 We may have hit them too early...
--Peggy will put us on her calendar to review Disabilities mockup for content in the next two weeks
--Mikki suggested looking at current inbound eBenefits Disabilities links
--IA wants to have redirect plan when we go live
--Rated Disabilities will (most likely) live in the disabilities hub of VA.gov
--Mikki suggested coordinating with team working on Rated Disabilities tool for cross-linking
--Peggy posted content guide links for errors/alerts

**Comment by sporeboy** [comment]
[Content Review Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/content-review-process.md)
[Error Handling Dictionary](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Design%20System/Guidelines/Error%20handling/Dictionary.md)
[Error Message Standardization](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Design%20System/Guidelines/Error%20handling/Content%20Style%20Guide.md)
