### ISSUE TITLE
[VAMC] Create New Devshop environments for all VISN-21 Systems [PM}

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19103]
# User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial devshop environments to begin testing

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-21 Internal Review Folder](https://drive.google.com/drive/folders/1z5U48stIVVaG5PnaKMJs8RlNUgUZ32N6)
[Review template for review](https://drive.google.com/drive/folders/1iRChKVhQ09f-ZTbWvvQkljfBRQ_wogZd)

## Tasks
- Create new devshop environments for the following systems
- 1) Assure that all facilities in Prod are linked correctly to System
- 2) Assure there are no errors in menu itesm
- 3) Build, Publish, and release content, test web pages
- [x] VA Central California health care
- [x] VA Northern California health care
- [x] VA Pacific Islands health care
- [x] VA Palo Alto health care
- [x] VA San Francisco health care
- [x] VA Sierra Nevada health care
- [x] VA Southern Nevada health care

## Acceptance Criteria
- [x] All environments are created and tested
- [x] Any environment that does not come up is immediately placed in CMS support and story is placed in BLOCKED until resolved.
