### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Southern Nevada health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19106]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-21 Internal Review Folder](https://drive.google.com/drive/folders/1z5U48stIVVaG5PnaKMJs8RlNUgUZ32N6)
[Review template for review](https://drive.google.com/drive/folders/1iRChKVhQ09f-ZTbWvvQkljfBRQ_wogZd)

## Tasks
- 1) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 593	North Las Vegas VA Medical Center
- [x] 593GC	Pahrump VA Clinic
- [x] 593GD	Northwest Las Vegas VA Clinic
- [x] 593GE	Southeast Las Vegas VA Clinic
- [x] 593GF	Southwest Las Vegas VA Clinic
- [x] 593GG	Northeast Las Vegas VA Clinic
- [x] 593GH	Master Chief Petty Officer Jesse Dean VA Clinic
- [x] 593QC	West Cheyenne VA Clinic

- 2) Review and correct all **Broken Links** on each of the system pages in Devshop

- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [x] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by ltrombley** [comment]
Task #19106-  Internal Review, Test, Proof Read, and CORRECT all NODES for "VA Southern Nevada health care" ending with stakeholder review doc 
1. Added new clinic: vha_593QC West Cheyenne VA Clinic
