### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Northern California health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19100]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-21 Internal Review Folder](https://drive.google.com/drive/folders/1z5U48stIVVaG5PnaKMJs8RlNUgUZ32N6)
[Review template for review](https://drive.google.com/drive/folders/1iRChKVhQ09f-ZTbWvvQkljfBRQ_wogZd)

## Tasks
- 1) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 612A4	Sacramento VA Medical Center
- [x] 612B4	Redding VA Clinic
- [x] 612BY	Oakland VA Clinic
- [x] 612GD	Fairfield VA Clinic
- [x] 612GE	Mare Island VA Clinic
- [x] 612GF	Martinez VA Medical Center
- [x] 612GG	Chico VA Clinic
- [x] 612GH	McClellan VA Clinic
- [x] 612GI	Yuba City VA Clinic
- [x] 612GJ	Yreka VA Clinic
- [x] 612QB	Twenty First Street VA Clinic
- [x] 612GK	Sierra Foothills VA Clinic
- [x] 612QC	Cypress Avenue VA Clinic
- [x] 612QD	Howe Road VA Clinic

- 2)  Review and correct all **Broken Links** on each of the system pages in Prod/Devshop

- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [ ] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by lealester** [comment]
resume with caregiver support (2/1)

**Comment by lealester** [comment]
added three locations from VAST: Sierra Foothills VA Clinic (612GK), Cypress Avenue VA Clinic (612QC), Howe Road VA Clinic (612QD)
