### ISSUE TITLE
AE Sprint 40

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19116]
## Priorities
1.  MyVA: Get ready for Pre-usability Prep review (copy review, research plan, and convo guide)
2. MyVA: Start frontend build
3. DD4edu: QA/ any QA fixes
4. DD4edu: Analytics planning 
5. DD4edu: Contact center guide
6. Notification preferences: Finish integration; VSP kick-off
7. Profile BE errors issue

## Profile
**BE**
- [ ] Are we sending deprecated IDs to VA Profile? #17739
- [ ] Log when users have a mvi_response.status of OK then return a va profile MVI201 error #18349
- [x] [BE] Rename Vet360Redis to VAProfileRedis #19201

## My VA redesign
**PM**
- [x] [PM] Make a list of staging test cases based on wireframes (MyVA) #18042 (mostly done)
- [x] [PM] Submit request for MyVA 2.0 Usability Testing Prep review #19131 
- Usability Testing Prep [Authenticated Experience - MyVA 2.0] #19389, 2pm ET Feb 12th
 - Design will add the research plan, convo guide, and prototype to the ticket

**Design**
[Epic] MyVA 2.0 copy #18991 
- [ ] [Design] MyVA: Updates from copy review #19165 
- [ ] [Design] MyVA 2.0: Mock up mobile screens to match desktop #19163 
- [ ] [Design] MyVA: Create clickable prototype for research #19164 
- [x] [Design] MyVA 2.0 Research plan for usability of finalized designs #19120
- [ ] [Design] MyVA 2.0 Convo guide for usability testing of finalized designs #19121
- [ ] Add My VA to unauth nav and add sign-in flow to prototype #19356
- [x] [Design] MyVA: Mock up desktop screens #19795

**FE** 
- [x] [FE] Update MyVA wrapper to load all required data upfront #18938
- [x] [FE] Research current claims widgets #18934
- [x] [FE] Create blue "info/status" box component #18935
- [x] [FE] Update nametag/banner #18932
- [x] [FE] Add breadcrumbs and page title to my VA #19058
- [x] [FE] Make a component for in-progress application #18945
- [x] [FE] Build the Healthcare "related links" section #18943
- [x] [FE] Write high-level bdd Cypress tests #19152
- [x] [FE] Investigate EVSS Claims endpoint speed #19171
- [x] [FE] Add breadcrumbs and page title to my VA #19058

## Direct deposit for edu
**QA this sprint**
Staging Review [Authenticated Experience - Direct Deposit for Edu] #19281 (Sprint 41)
- Monday 2/15 at 3:30pm ET

**PM**
- [x] [PM] DD4EDU Create release plan #19123 (save in dde4du Github folder)
- [x] [PM] DD4EDU Analytics Planning/Submit request #19124
- [x] Create contact center guide for DD4edu #19129 

**Design** (Jim Adams)
- [x] Create contact center guide for DD4edu #19129 
-  QA issues if applicable

**FE**
- QA issues if applicable
- [x] [FE] Build Error alert to show when we cannot connect to a Direct Deposit endpoint #18339

## VA Profile Notification Preferences
**PM**
- [x] VSP Kickoff meeting for Notification Preferences #19133

**BE**
- [x] [BE] VA Profile notification preferences: Implementation (part 1) #18056

## Unplanned

- [x] Record errors when we cannot create a VA Profile transaction #19318
- [x] [FE] Hide the profile banner when the user is LOA1 #19348
- [x] [FE] Store the `disabilityDecisionTypeName` in Redux alongside `userPercentOfDisability` #19404
- [x] [FE] Make `personalization/components` dir for shared components #19504
- [X] [FE] Ensure we collect GA data on the View Payment History link #19352
