### ISSUE TITLE
Find a VA Form - Add 'Sort by Last Updated' feature x Staging Accessibility Checklist

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19117]
## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [ ] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [ ] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - Conduct axe browser scan, and document or address issues found
  - [ ] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [x] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
  - [ ] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [ ] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [ ] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- [ ] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [x] **Attach to Collab Cycle Epic**
- [x] **Labeled with Team**

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel please tag Josh Kim when you've done the prelim accessibility testing.

**Comment by zacharymorel** [comment]
@joshkimux preliminary a11y testing as been run on staging.

**Comment by joshkimux** [comment]
@zacharymorel @MarciMcGuireGCIO 

Great stuff! The select box works like a dream! One extra thing to consider:

Would it be possible for us to announce to screen reader users that the search results have been updated based on the sort they selected? This makes up for not having an explicit submit button.

I like gov.uk's approach of using a screen reader only `span` with a `aria-live="assertive"` to serve as a screen reader only alert which provides an equivalent experience to seeing the search results update visually (see screenshots)-- but I think there's probably other ways of handling this too that might be easier for us to implement.

@zacharymorel would love to collaborate with you here on what might be the best path forwards

<img width="1112" alt="Screen Shot 2021-01-27 at 11 12 21 AM" src="https://user-images.githubusercontent.com/14154792/106019821-12fc9680-6091-11eb-8641-60498912a462.png">
<img width="675" alt="Screen Shot 2021-01-27 at 11 15 53 AM" src="https://user-images.githubusercontent.com/14154792/106019824-12fc9680-6091-11eb-902d-d1877cab1db9.png">

**Comment by zacharymorel** [comment]
When the user selects an option, doesn't the screen reader read the option that has been selected? 
Or do we need more context for the user?

**Comment by zacharymorel** [comment]
Another note, I have discovered documentation on how to implement the above scenario, so I can do that probably if it's the best solve to the issue?

**Comment by joshkimux** [comment]
@zacharymorel It reads out the selection, but it's not clear that the sort has been completed. Re-announcing the results with the type of sort appended helps address that-- it's also more future proof should filters be introduced where the amount of results may fluctuate.

And yea, go for it!

**Comment by zacharymorel** [comment]
Perfect, from a11y stand point, would this be a blocker to launch? 
Seems to me I can get it in anyways before launch since we're launching on 2/9.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO can create a user story out of this to implement?

**Comment by MarciMcGuireGCIO** [comment]
Yep!

**Comment by joshkimux** [comment]
@zacharymorel , no this would not qualify as a launchblocker! But it would be a _huge_ enhancement worth celebrating if you can sneak it in before launch! 🤩
