### ISSUE TITLE
Update 'Installment contracts and other debts' section to use inputs instead of radio selections

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19125]
## Issue Description
DMC has asked that we reintroduce text inputs for the date of debt and amount overdue questions on the 'installment contracts and other debts' section of the form.

---
## Tasks
- [ ] Incorporate new inputs into the FE according to [this prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134307869/simulate/sitemap?mode=i)
- [ ] Confirm with screenshot to designers

## Acceptance Criteria
- [ ] UI updated
- [ ] Confirmed with screenshot to designers
