### ISSUE TITLE
[Development] Access Decision Review Page for Higher Level Review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1912]
## User Story
As a claimant, I need to easily access the Decision Review page on VA.gov so I can submit a Higher Level Review for my existing claim.

## Goal
_Easy and direct access to the Decision Review page_

## Tasks
- [ ] Multiple points of entry created
- [ ] Update this ticket with individual points of entry
- [ ] _ *This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Acceptance Criteria
- _As a va.gov user who needs to submit a Higher-level review, I can access that part of the va.gov site without having to search for a point of entry._

**Comment by YanaRoy** [comment]
@Karak888 this ticket may need Global UX eyes on it. FYI

**Comment by Karak888** [comment]
@YanaRoy this seems like it is for the authenticated experience?

**Comment by Samara-Strauss** [comment]
Hello! So I want to clarify how things should work. Authenticated experience doesn't manage flows for other teams/products unless we are linking to those products from the profile or My VA dashboard. Any team that owns a product is responsible for figuring out what the entry points are and working with @mnorthuis as our resident IA expert to get those into the sitemap and with the content team to get any content pages created/updated for the product. But definitely the team who owns the product — in this case, benefits and memorials — should own the vision for this and then work with the necessary folks to get things updated.

Happy to answer questions about that. Let me know if you have them.

**Comment by luke-gcio** [comment]
OBE, solved under different I/A ticket (now we have Drupal as well).
