### ISSUE TITLE
Add Income Question for Spouse Removal

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19137]
`Determine impact on BE first`
`These questions need to be in place for RBPS to complete pension question testing`

## Background
In testing for pension, an error was shown that said **"Dependent has income flag missing for pension award change"** meaning that we asked about net worth but not about if they had income in last 365 days.  To ensure that the messaging is consistent and clear to those that review these, we should include these questions even as the responses are not hard requirements Yes or No.

## Considerations
- These questions will need to be included for pension to test
- We should probably keep the fields in place as long as possible for testing then as production gets turned up, remove those fields from view from the Veterans perspective

## Tasks
- [ ] Include the income pension question for **spouse** removal: **divorce** or **death**
- [ ] Include the income pension question for **dependent death** 
- [ ] Update `vets-json-schema`, `vets-website`, and `vets-api`

## Acceptance Criteria
- [ ] The questions appears on the frontend
- [ ] The response values are conveyed in the payload, even if null
- [ ] A PR has been requested for merging

**Comment by micahchiang** [comment]
Change traingingProgram to schoolType, re-add `trainingProgram` as text field.
