### ISSUE TITLE
VTK Implement usage tracking using DataDog

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#19139]
## Description

Our current tracking approach which utilizes a commit message has been determined to be a robust option.  Based on our discussion with Insights & Analytics, Google Analytics is not advised either.  Our 3 option was to implement tracking through DataDog.

## Definition of Done
- [x] All vtk commands have metrics recorded in DataDog
- [x] A "dashboard" is created in DataDog to show usage metrics (per command)
- [x] ~remove old way of tracking (commit message)~ Done in [5792](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets-api/issues/5792).

**Comment by alexpappasoddball** [comment]
ericboehs & @LindseySaari, The last step of this ticket would be to wright out the decisions we've made and why.  We can do that here in the ticket, or in Confluence in our team section.  Then this ticket can be closed and we can move on to [this](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/19139) ticket!

**Comment by ericboehs** [comment]
Hit a blocker here.

Datadog doesn't allow reporting to their API via the client token. In order to handle that we need to create a middleware application to forward the requests from the CLI clients to our Datadog instance.

Another option is to find a different analytics service which would allow for client metric submisison via an API.

Currently [I'm in discussion](https://dsva.slack.com/archives/CJYRZK2HH/p1611951352139600) with Demian on how to deploy this tiny middleware.

**Comment by ericboehs** [comment]
Middleware is now deployed. Had some uptime issues with it but it looks stable as of this morning.
