### ISSUE TITLE
Remove react widget from main Caregivers page-WAIT TO PUBLISH UNTIL 1/29

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19141]
## Issue Description
The caregivers team is done needing to use a react widget with a toggle on the [Program of Comprehensive Assistance for Family Caregivers](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/) page. We need to add the text back into Drupal that is currently in the widget and remove the widget form the page. 

The entire Q&A "How do I apply for this program?" needs to be added back into Drupal and published on Friday 1/29.
Also, we need to add the hours of operation in the second bullet where we list the Caregiver Support Line and change the phone number in the sentence below that. That text should read:

If you need help with completing the application, call 855-488-8440, option 3. Or you can contact your local Caregiver Support Coordinator.

## Tasks
- [x] Add text back into Drupal with updated hours and new phone number and accompanying text
- [x] Remove react widget from page
- [x] Review and publish

## Acceptance Criteria
- [x] React widget no longer on page and correct text in Drupal on live site

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I took the react widget out and added the text back into Drupal with the added hours and that changed phone number. Before we publish on Friday, could you just check the new version against the live version to make sure I didn't introduce any errors? The preview is: preview-prod.vfs.va.gov/preview?nodeId=10 Thanks! FYSA @ala-yna

**Comment by RLHecht** [comment]
This work is completed. Closing ticket.
