### ISSUE TITLE
Prepare for UAT for VRE (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19142]
## Story
As a designer/researcher for the eBenefits Team, I want to be able to understand how the Veteran is currently interacting with this feature holistically so that I can create a more accurate description of what needs to be developed.

## Goals
- Use a conversation guide (include as delivery)
- Use research plan (include as delivery)
- Conduct a usability session that answers pain point questions and informs the team what the best thing to build might be
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)

## Tasks
- [x] Using the [previous research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/uat/ch36-uat-research-plan.md), and included [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/uat/ch36-uat-convo-guide.md) create a UAT plan for CH31
- [x] Request any reviews on these as needed  
- [ ] Shawna has approved this, then
  - [ ] ~~Lauren Alexanderson has approved this~~ save for scheduling 

**Next Steps**
- [ ] When ready for scheduling, coordinate with user research partner (Perigean), asking them to take notes 

## Acceptance Criteria
- [x] UAT has been prepped in advance for the week of April 5
`(Initial synthesis due 7 days from last session)`

**Comment by sporeboy** [comment]
Initial draft of Research Plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/research-design/uat/ch31-uat-research-plan.md

**Comment by sporeboy** [comment]
Initial draft of Conversation Guide available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/research-design/uat/ch31-uat-convo-guide.md

**Comment by sporeboy** [comment]
Made date revisions to Research Plan.

**Comment by sporeboy** [comment]
Reached-out to Shawna for review in Slack design thread.
