### ISSUE TITLE
Review KPI framework example metrics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19144]
## Issue Description
Review [current KPI Framework metrics](https://vfs.atlassian.net/wiki/spaces/~173922865/pages/614531245/VA.gov+Analytics+-+KPI+Framework) for edits and suggest new metrics so we will have a template of metrics that we will flesh out for: 
- BigQuery & Google Analytics standardization
- Example VA.gov metrics with baselines
- Recommending action items for teams if the data falls below baselines

---
## Tasks
- [ ] Review columns to remove extraneous columns
- [ ] Review current metrics to revise or remove 
- [ ] Add additional metrics
- [ ] Prioritize "highly suggested metrics"

## Acceptance Criteria
- [ ] KPI framework metrics are up to date for the Analytics team to flesh out
