### ISSUE TITLE
Remove pamphlet link from Post-9/11 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19153]
## Issue Description
Per stakeholder Tammy Hurley, we need to remove a link to the Post-9/11 GI BIll pamphlet from the [Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) and the [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) pages. 

## Tasks
- [x] Remove link to pamphlet PDF on two pages
- [x] Review and publish
- [x] Notify stakeholder 

## Acceptance Criteria
- [x] Change is live on site

**Comment by RLHecht** [comment]
This change was made. Will close after today's deployment. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
Changes to both pages now live. Closing ticket.
