### ISSUE TITLE
Revert changes to Redux for View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#19155]
# Background
When we created the unit tests for View Representative the method we used to export the Reducer was causing tests to fail so we changed the way the Reducer is exported. This change did not allow the front end of the application to load so we need to revisit this change and update it to work both with the front end and the unit tests.

## Tasks
- [x] Update Reducer export to include brackets
- [x] Update unit tests to work with newly exported Reducer
- [x] Submit a PR for review

## Acceptance criteria
- [x] The front end of the View Representative page once again works correctly
- [x] The unit tests for View Representative work correctly
- [x] A PR has been submitted for review

**Comment by micahchiang** [comment]
Including this in the PR for #19553 since the change is relatively small.
