### ISSUE TITLE
Determine Analytics Playbook IA for Confluence

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19161]
## Issue Description
Determine the best information architecture for the Analytics Playbook and how the KPI Framework can fit into the Playbook.

---
## Tasks
- [ ] Document IA of Analytics Playbook for Confluence
- [ ] Determine how the Analytics Playbook can best align with other VSP documentation, including the Collaboration Cycle

## Acceptance Criteria
- [ ] VSP Analytics & Insights understands the IA of the Analytics playbook so that we can smoothly transition the Analytics Playbook to Confluence
