### ISSUE TITLE
CH31 Bug fix

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#19180]
During partner testing, it was discovered vets-api is overwriting user information when authenticated. We need to ensure we are appending/merging data such as va file number.

## Tasks
- [x] Test and determine which fields are not working
- [x] Make changes to ensure form is submitting required data again

## Acceptance Criteria
- [x] PR is submitted
