### ISSUE TITLE
[FSR] Chapter 2 content changes

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19187]
## Issue Description
_The VSP content team provided [a document of content changes](https://drive.google.com/file/d/188CvoTOmTkY-uyAZ3JPo8GNW3CmLr_6t/view?usp=sharing) that need to be incorporated into the FSR. This ticket encompasses the content changes that need to be made to chapter 2._

---
## Tasks
- [x] _Incorporate the changes outlined on page 18 to 30 of the provided document_

## Acceptance Criteria
- [x] _UXPin has been updated and linked in this ticket_
- [x] _Work has been checked off in the [FSR Content epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19132)_

**Comment by rileyorr** [comment]
All CH 2 content has been incorporated and [updated in UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410887/simulate/sitemap?mode=i). This was a huge chunk of work so I'm going to review tomorrow to make sure I didn't miss anything before moving the ticket.

**Comment by rileyorr** [comment]
Double-checked the ch2 content & am moving this ticket over
