### ISSUE TITLE
[FSR] Wizard content changes

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19181]
## Issue Description
_The VSP content team provided [a document of content changes](https://drive.google.com/file/d/188CvoTOmTkY-uyAZ3JPo8GNW3CmLr_6t/view?usp=sharing) that need to be incorporated into the FSR. This ticket encompasses the content changes that need to be made to the wizard. Additionally, some of the wizard screens haven't been reviewed by the content team yet, so this ticket will encompass that work as well._

---
## Tasks
- [x] _Send the full wizard flow for content review_
- [x] _Update the wizard section of the FSR's UI in Sketch with the modified content_

## Acceptance Criteria
- [x] _UXPin has been updated and linked in this ticket_
- [x] _Work has been checked off in the [FSR Content epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19132)_

**Comment by rebeccawalsh** [comment]
This content has been updated in our Github document here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/design/wizard-design-content.md

I will compile some mockups for each of these content blocks and attach them soon!

**Comment by rebeccawalsh** [comment]
Here are the mockups for each of the cards: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136854443/specification/no-panels
