### ISSUE TITLE
Install operator for management of Kubernetes secrets 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19188]
## Description
We need a way to effectively manage secrets that integrates with applications at deploy time so that they can authenticate against various platform resources. 

## Background/context/resources

- At this moment, ["kubernetes-external-secrets"](https://github.com/external-secrets/kubernetes-external-secrets) seems like the best choice due to maintainers, maturity, integration w/ AWS SSM Parameter store, and active contributions
- A good overview for "kubernetes-external-secrets" can be found [here](https://medium.com/aeris-things/kubernetes-external-secrets-join-the-disjoints-5dab8910d2c8)

## Technical notes
This is working but needs to be codified. 
May need to discuss the implications of how external secrets are exposed as it relates to SSM 

---
## Tasks
- [x] Need to create a repo for this. 
- [x] Need to create the pipeline

## Definition of Done
- [x] Kubernetes secrets controller is working Ops {DEV,STAGING} EKS clusters

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by tskinn** [comment]
Jeremy and I have temporarily installed the kubernetes-external-secrets controller and run tests to verify that it can generate secrets from SSM Parameter Store parameters.

The controller monitors "external-secret" custom resources which maps param store values to k8s secrets, and the controller creates the k8s secrets accordingly.

I'm not sure if that satisfies this ticket or not. We probably need an official decision on if we are going to use this tool or not before we create a github repo with ci/cd pipeline for it.
