### ISSUE TITLE
[VAMC] VISN-19 "Rocky Mountain Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19195]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 8 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Salt Lake City health care system legacy site](https://www.saltlakecity.va.gov/)
[Google Drive locations for VISN-19](https://drive.google.com/drive/folders/18c9fpui7dMr5LRnkhziw1GPXw9NoXAWT)

## TASKS
See below associated tasks which should include, but are not limited to:
** Prepare the following Systems for Web Modernization:**
- [ ]  VA Cheyenne health care
- [ ]  VA Eastern Colorado health care
- [ ]  VA Western Colorado health care
- [ ]  VA Montana health care
- [ ]  VA Eastern Oklahoma health care
- [ ]  VA Oklahoma City health care
- [ ]  VA Salt Lake City health care
- [ ]  VA Sheridan health care

** Completed the following initiatives for each System included in order:**
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 

** Facilities include for System:**
VA Cheyenne health care:
- [ ]  Laramie Mobile Telehealth Clinic
- [ ]  Cheyenne VA Medical Center
- [ ]  Fort Collins VA Clinic
- [ ]  Loveland VA Clinic
- [ ]  Rawlins VA Clinic
- [ ]  Sidney VA Clinic
- [ ]  Sterling VA Clinic
- [ ]  Torrington VA Mobile Clinic
- [ ]  Wheatland VA Mobile Clinic

VA Eastern Colorado health Care:
- [ ] Alamosa VA Clinic
- [ ] Aurora VA Clinic
- [ ] Burlington VA Clinic
- [ ] Denver VA Clinic
- [ ] Golden VA Clinic
- [ ] Jewell VA Clinic
- [ ] La Junta VA Clinic
- [ ] Lamar VA Clinic
- [ ] PFC Floyd K. Lindstrom Department of Veterans Affairs Clinic
- [ ] PFC James Dunn VA Clinic
- [ ] Rocky Mountain Regional VA Medical Center
- [ ] Salida VA Clinic

VA Western Colorado (Grand Junction) health care:
- [ ] Glenwood Springs VA Clinic
- [ ] Grand Junction VA Medical Center
- [ ] Major William Edward Adams VA Clinic
- [ ] Moab VA Clinic
- [ ] Montrose VA Clinic

VA Montana health care :
- [ ] Anaconda VA Clinic
- [ ] Benjamin Charles Steele VA Clinic
- [ ] Bozeman VA Clinic
- [ ] Cut Bank VA Clinic
- [ ] David J. Thatcher VA Clinic
- [ ] Fort Harrison VA Medical Center
- [ ] Glasgow VA Clinic
- [ ] Glendive VA Clinic
- [ ] Great Falls VA Clinic
- [ ] Hamilton VA Clinic
- [ ] Kalispell VA Clinic
- [ ] Lewistown VA Clinic
- [ ] Merril Lundman VA Outpatient Clinic
- [ ] Miles City VA Medical Center
- [ ] Plentywood VA Clinic

VA Eastern Oklahoma health care:
- [ ] Ernest Childers VA Outpatient Clinic
- [ ] Jack C. Montgomery VA Medical Center
- [ ] Jack C. Montgomery East VA Clinic
- [ ] McAlester VA Clinic
- [ ] McCurtain County VA Clinic
- [ ] Tulsa Eleventh Street VA Clinic
- [ ] Vinita VA Clinic
- [ ] Yale Avenue VA Clinic

VA Oklahoma City health care:
- [ ] Ada VA Clinic
- [ ] Altus VA Clinic
- [ ] Ardmore VA Clinic
- [ ] Blackwell VA Clinic
- [ ] Enid VA Clinic
- [ ] Lawton VA Clinic
- [ ] North May VA Clinic
- [ ] Oklahoma City VA Medical Center
- [ ] South Oklahoma City VA Clinic
- [ ] Stillwater VA Clinic
- [ ] Wichita Falls VA Clinic
- [ ] Tinker VA Clinic
- [ ] Clinton VA Clinic
- [ ] Fourteenth Street VA Clinic

VA Salt Lake City Health Care:
- [ ] Elko VA Clinic
- [ ] George E. Wahlen VA Medical Center
- [ ] Idaho Falls VA Clinic
- [ ] Ogden VA Clinic
- [ ] Orem VA Clinic
- [ ] Pocatello VA Clinic
- [ ] Price VA Clinic
- [ ] Roosevelt VA Clinic
- [ ] St. George VA Clinic
- [ ] Weber County VA Clinic
- [ ] Western Salt Lake VA Clinic

VA Sheridan health care:
- [ ] Afton VA Clinic
- [ ] Casper VA Clinic
- [ ] Cody VA Clinic
- [ ] Evanston VA Clinic
- [ ] Gillette VA Clinic
- [ ] Riverton VA Clinic
- [ ] Rock Springs VA Clinic
- [ ] Sheridan VA Medical Center
- [ ] Worland VA Clinic
