### ISSUE TITLE
[VAMC] VISN-16 "South Central VA Health Care Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19196]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 8 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site / Documents / Resources
[Google Drive locations for VISN-16](https://drive.google.com/drive/folders/1bbTmpYjtFcY-8q9O5RRdOOU3rPIPyiAx)

## TASKS
See below associated tasks which should include, but are not limited to:
** Prepare the following Systems for Web Modernization:**
- [ ] VA Alexandria health care
- [ ] VA Central Arkansas health care
- [ ] VA Fayetteville Arkansas health care
- [ ] VA Gulf Coast health care
- [ ] VA Houston health care
- [ ] VA Jackson health care
- [ ] VA Shreveport health care
- [ ] VA Southeast Louisiana health care

** Completed the following initiatives for each System included in order:**
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 

**Facilities included for each System**
VA Alexandria health care
- [ ] 502	Alexandria VA Medical Center
- [ ] 502GA	Jennings VA Clinic
- [ ] 502GB	Lafayette VA Clinic
- [ ] 502GE	Lake Charles VA Clinic
- [ ] 502GF	Fort Polk VA Clinic
- [ ] 502GG	Natchitoches VA Clinic
- [ ] 502QB	Lafayette Campus B VA Clinic

VA Central Arkansas health care
- [ ] 598	John L. McClellan Memorial Veterans' Hospital
- [ ] 598A0	Eugene J. Towbin Healthcare Center
- [ ] 598GA	Mountain Home VA Clinic
- [ ] 598GB	El Dorado VA Clinic
- [ ] 598GC	Hot Springs VA Clinic
- [ ] 598GD	Mena VA Clinic
- [ ] 598GE	Pine Bluff VA Clinic
- [ ] 598GF	Searcy VA Clinic
- [ ] 598GG	Conway VA Clinic
- [ ] 598GH	Russellville VA Clinic

VA Fayetteville Arkansas health care
- [ ] 564	Fayetteville VA Medical Center
- [ ] 564BY	Gene Taylor Veterans' Outpatient Clinic
- [ ] 564GA	Harrison VA Clinic
- [ ] 564GB	Fort Smith VA Clinic
- [ ] 564GC	Branson VA Clinic
- [ ] 564GD	Ozark VA Clinic
- [ ] 564GE	Jay VA Clinic
- [ ] 564GF	Joplin VA Clinic

VA Gulf Coast health care
- [ ] 520	Biloxi VA Medical Center
- [ ] 520BZ	Pensacola VA Clinic
- [ ] 520GA	Mobile VA Clinic
- [ ] 520GB	Panama City Beach VA Clinic
- [ ] 520GC	Eglin Air Force Base VA Clinic

VA Houston health care
- [ ] 580	Michael E. DeBakey VA Medical Center
- [ ] 580BY	Beaumont VA Clinic
- [ ] 580BZ	Charles Wilson VA Outpatient Clinic
- [ ] 580GC	Galveston County VA Clinic
- [ ] 580GD	Conroe VA Clinic
- [ ] 580GE	Katy VA Clinic
- [ ] 580GF	Lake Jackson VA Clinic
- [ ] 580GG	Richmond VA Clinic
- [ ] 580GH	Tomball VA Clinic
- [ ] 580GJ	Texas City VA Clinic

VA Jackson health care
- [ ] 586	G.V. (Sonny) Montgomery VA Medical Center
- [ ] 586GA	Kosciusko VA Clinic
- [ ] 586GB	Meridian VA Clinic
- [ ] 586GC	Greenville VA Clinic
- [ ] 586GD	Hattiesburg VA Clinic
- [ ] 586GE	Natchez VA Clinic
- [ ] 586GF	Columbus VA Clinic
- [ ] 586GG	McComb VA Clinic

VA Shreveport health care
- [ ] 667	Overton Brooks Veterans' Administration Medical Center
- [ ] 0704V	Shreveport, LA Veterans Service Center
- [ ] 667GA	Texarkana VA Clinic
- [ ] 667GB	Monroe VA Clinic
- [ ] 667GC	Longview VA Clinic
- [ ] 667QA	Knight Street VA Clinic
 
VA Southeast Louisiana health care
- [ ] 629	New Orleans Veterans Medical Center
- [ ] 629BY	Baton Rouge VA Clinic
- [ ] 629GA	Houma VA Clinic
- [ ] 629GB	Hammond VA Clinic
- [ ] 629GC	Slidell VA Clinic
- [ ] 629GD	St. John VA Clinic
- [ ] 629GE	Franklin VA Clinic
- [ ] 629GF	Bogalusa VA Clinic
