### ISSUE TITLE
[VAMC] VISN-10 "VA Healthcare SystemL" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19198]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 11 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Sites / Documentation / Resources
[Google Drive locations for VISN-10](https://drive.google.com/drive/folders/1gshksVD3KVxzo4Ol5ejYz9jTtCD3ldro)

## TASKS
See below associated tasks which should include, but are not limited to:
** Prepare the following Systems for Web Modernization:**
- [ ] VA Ann Arbor health care
- [ ] VA Central Ohio health care
- [ ] VA Chillicothe health care
- [ ] VA Cincinnati health care
- [ ] VA Dayton health care
- [ ] VA Northeast Ohio health care
- [ ] VA Battle Creek health care
- [ ] VA Detroit health care
- [ ] VA Indiana health care
- [ ] VA Northern Indiana health care
- [ ] VA Saginaw health care

** Completed the following initiatives for each System included in order:**
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 

** Facilities include for System:**
VA Ann Arbor health care
- [ ] 506	Ann Arbor VA Medical Center
- [ ] 506GA	Toledo VA Clinic
- [ ] 506GB	Flint VA Clinic
- [ ] 506GC	Jackson VA Clinic
- [ ] 506QA	Packard Road VA Clinic
- [ ] 506QB	Green Road VA Clinic

VA Central Ohio health care
- [ ] 757	Chalmers P. Wylie Veterans Outpatient Clinic
- [ ] 757GA	Zanesville VA Clinic
- [ ] 757GB	Grove City VA Clinic
- [ ] 757GC	Marion VA Clinic
- [ ] 757GD	Daniel L. Kinnard VA Clinic

VA Chillicothe health care
- [ ] 538	Chillicothe VA Medical Center
- [ ] 538GA	Athens VA Clinic
- [ ] 538GB	Portsmouth VA Clinic
- [ ] 538GC	Marietta VA Clinic
- [ ] 538GD	Lancaster VA Clinic
- [ ] 538GE	Cambridge VA Clinic
- [ ] 538GF	Wilmington VA Clinic

VA Cincinnati health care
- [ ] 539	Cincinnati VA Medical Center
- [ ] 539GA	Bellevue VA Clinic
- [ ] 539GB	Clermont County VA Clinic
- [ ] 539GC	Dearborn VA Clinic
- [ ] 539GD	Florence VA Clinic
- [ ] 539GE	Hamilton VA Clinic
- [ ] 539GF	Georgetown VA Clinic
- [ ] 539QD	Norwood VA Clinic

VA Dayton health care
- [ ] 552	Dayton VA Medical Center
- [ ] 552GA	Middletown VA Clinic
- [ ] 552GB	Lima VA Clinic
- [ ] 552GC	Richmond VA Clinic
- [ ] 552GD	Springfield VA Clinic

VA Northeast Ohio health care
- [ ] 541	Louis Stokes Cleveland Department of Veterans Affairs Medical Center
- [ ] 541BY	Canton VA Clinic
- [ ] 541BZ	Youngstown VA Clinic
- [ ] 541GB	Lorain VA Clinic
- [ ] 541GC	Sandusky VA Clinic
- [ ] 541GD	David F. Winder Department of Veterans Affairs Community Based Outpatient Clinic
- [ ] 541GE	McCafferty VA Clinic
- [ ] 541GF	Lake County VA Clinic
- [ ] 541GG	Akron VA Clinic
- [ ] 541GH	East Liverpool VA Clinic
- [ ] 541GI	Warren VA Clinic
- [ ] 541GJ	New Philadelphia VA Clinic
- [ ] 541GK	Ravenna VA Clinic
- [ ] 541GL	Parma VA Clinic

VA Battle Creek health care
- [ ] 515	Battle Creek VA Medical Center
- [ ] 515BY	Wyoming VA Clinic
- [ ] 515GA	Muskegon VA Clinic
- [ ] 515GB	Lansing South VA Clinic
- [ ] 515GC	Benton Harbor VA Clinic

VA Detroit health care
- [ ] 553	John D. Dingell Department of Veterans Affairs Medical Center
- [ ] 553GA	Yale VA Clinic
- [ ] 553GB	Pontiac VA Clinic

VA Indiana health care
- [ ] 583	Richard L. Roudebush Veterans' Administration Medical Center
- [ ] 6463	Crane VA Outreach Clinic
- [ ] 6483	Patient Response Center
- [ ] 6505	Crane VA Clinic
- [ ] 583GA	Terre Haute VA Clinic
- [ ] 583GC	Martinsville VA Clinic
- [ ] 583GD	Indianapolis West VA Clinic
- [ ] 583GE	West Lafayette VA Clinic
- [ ] 583GF	Wakeman VA Clinic
- [ ] 583GG	Shelbyville VA Clinic
- [ ] 583QA	Monroe County VA Clinic
- [ ] 583QB	Indianapolis VA Clinic
- [ ] 583QC	Vigo County VA Clinic
- [ ] 583QD	Indianapolis YMCA VA Clinic

VA Northern Indiana health care
- [ ] 610	Marion VA Medical Center
- [ ] 610A4	Fort Wayne VA Medical Center
- [ ] 610A4	Fort Wayne VA Medical Center
- [ ] 610BY	St. Joseph County VA Clinic
- [ ] 610GB	Muncie VA Clinic
- [ ] 610GC	Goshen VA Clinic
- [ ] 610GD	Peru VA Clinic

VA Saginaw health care
- [ ] 655	Aleda E. Lutz VA Medical Center
- [ ] 655GA	Gaylord VA Clinic
- [ ] 655GB	Colonel Demas T. Craw VA Clinic
- [ ] 655GC	Oscoda VA Clinic
- [ ] 655GD	Lieutenant Colonel Clement C. Van Wagoner VA Clinic
- [ ] 655GE	Clare VA Clinic
- [ ] 655GF	Bad Axe VA Clinic
- [ ] 655GG	Cadillac VA Clinic
- [ ] 655GH	Cheboygan County VA Clinic
- [ ] 655GI	Grayling VA Clinic
- [ ] 655QA	Saginaw VA Clinic
- [ ] 655QB	Grand Traverse VA Clinic
