### ISSUE TITLE
[VAMC] Publish Erie health care into Dual-State [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19192]
## Story
As a VA tester and web maintainer,  VAMC systems need to launch into a Dual-state prior to Go-Live, so complete testing, training, 508 compliance and final updates and content can be loaded in prep for final product release.

## Goal
- run through publishing testing and document obstacles and performance tasks to improve future publishings

## Resources
[Erie Run Book](https://drive.google.com/drive/folders/1GC6PkeS-iIv1XijLCINW5J_1bo7tSO37)

## Tasks
- [x] Confirm that root URL has been added to robots.txt/blacklist (Disallow)
- [x] The Publishing and release of content for va.gov/erie-health-care/
- [x] Confirmation Site is up and accessible
- [x] Left-Navigation bar is valid and working
- [x] Documenting any errors/bugs that need to be resolved
- [x] Determining if there are critical errors and rollback may be require
- [x] schedule and document postmortem/process improvement areas

## Acceptance Criteria
- [x] https://www.va.gov/erie-health-care/ is published
- [x] Left Nav is up and working and or issue initiated to fix any anomolies
- [x] Access to pages is confirmed and/or issue is initiated to fix any anomolies
- [x] Postmortem/lessons learned meeting is scheduled.
