### ISSUE TITLE
[VAMC] VISN-7 "VA Southeast Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19199]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 8 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site / Documents / Resources
[Google Drive locations for VISN-7](https://drive.google.com/drive/folders/1_6Oj8xq8RekLV83VYQ-PUfXlrofsjscl)

## TASKS
See below associated tasks which should include, but are not limited to:
** Prepare the following Systems for Web Modernization:**
- [ ] VA Atlanta health care
- [ ] VA Augusta health care
- [ ] VA Birmingham health care
- [ ] VA Central Alabama health care
- [ ] VA Charleston health care
- [ ] VA Columbia South Carolina health care
- [ ] VA Dublin health care
- [ ] VA Tuscaloosa health care

** Completed the following initiatives for each System included in order:**
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 

**Facilities included for each System**
VA Atlanta health care
- [ ] vha_508		Atlanta VA Medical Center
- [ ] vha_508QF	Atlanta VA Clinic
- [ ] vha_508GJ	Blairsville VA Clinic
- [ ] vha_508GN	Covington VA Clinic
- [ ] vha_508GA	Fort McPherson VA Clinic
- [ ] vha_508QD	Fulton County VA Clinic
- [ ] vha_508QE	Gwinnett County VA Clinic
- [ ] vha_508QC	Henderson Mill VA Clinic
- [ ] vha_508GH	Lawrenceville VA Clinic
- [ ] vha_508GI	Newnan VA Clinic
- [ ] vha_508QI	North DeKalb County VA Clinic
- [ ] vha_508QJ	North Fulton County VA Clinic
- [ ] vha_508GO	Northeast Cobb County VA Clinic
- [ ] vha_508GE	Oakwood VA Clinic
- [ ] vha_508GM	Pickens County VA Clinic
- [ ] vha_508GL	Rome VA Clinic
- [ ] vha_508GP	South Cobb County VA Clinic
- [ ] vha_508QH	South Fulton County VA Clinic
- [ ] vha_508GG	Stockbridge VA Clinic
- [ ] vha_508GK	Trinka Davis Veterans Village
- [ ] vha_508GF	(Austell) West Cobb County VA Clinic

VA Augusta health care
- [ ] vha_509	Charlie Norwood Department of Veterans Affairs Medical Center
- [ ] vha_509A0	Augusta VA Medical Center-Uptown
- [ ] vha_509GA	Athens VA Clinic
- [ ] vha_509GB	Aiken VA Clinic
- [ ] vha_509QA	Ray Hendrix Department Of Veterans Affairs Clinic

VA Birmingham health care
- [ ] vha_521	Birmingham VA Medical Center
- [ ] vha_521GA	Huntsville VA Clinic
- [ ] vha_521GC	Florence VA Clinic
- [ ] vha_521GD	Rainbow City VA Clinic
- [ ] vha_521GE	Oxford VA Clinic
- [ ] vha_521GF	Jasper VA Clinic
- [ ] vha_521GG	Bessemer VA Clinic
- [ ] vha_521GH	Childersburg VA Clinic
- [ ] vha_521GI	Guntersville VA Clinic
- [ ] vha_521GJ	Birmingham VA Clinic
- [ ] vha_521QA	Callahan VA Clinic

VA Central Alabama health care
- [ ] vha_619	Central Alabama VA Medical Center-Montgomery
- [ ] vha_619A4	Central Alabama VA Medical Center-Tuskegee
- [ ] vha_619GA	Columbus VA Clinic
- [ ] vha_619GB	Dothan 1 VA Clinic
- [ ] vha_619GD	Wiregrass VA Clinic
- [ ] vha_619GE	Monroe County VA Clinic
- [ ] vha_619GF	Central Alabama Montgomery VA Clinic
- [ ] vha_619QA	Dothan 2 VA Clinic
- [ ] vha_619QB	Fort Benning VA Clinic

VA Charleston health care
vha_534	Ralph H. Johnson Department of Veterans Affairs Medical Center
vha_534BY	Savannah VA Clinic
vha_534GB	Myrtle Beach VA Clinic
vha_534GC	Beaufort VA Clinic
vha_534GD	Goose Creek VA Clinic
vha_534GE	Hinesville VA Clinic
vha_534GF	Trident 1 VA Clinic
vha_534QA	Market Commons VA Clinic
vha_534QB	Trident 2 VA Clinic
vha_534QC	Charleston VA Clinic

VA Columbia South Carolina health care
vha_544	Wm. Jennings Bryan Dorn Department of Veterans Affairs Medical Center
vha_544BZ	Greenville VA Clinic
vha_544GB	Florence VA Clinic
vha_544GC	Rock Hill VA Clinic
vha_544GD	Anderson VA Clinic
vha_544GE	Orangeburg VA Clinic
vha_544GF	Sumter VA Clinic
vha_544GG	Spartanburg VA Clinic
vha_544HK	Columbia VA Mobile Clinic

VA Dublin health care
vha_557	Carl Vinson Veterans' Administration Medical Center
vha_557GA	Macon VA Clinic
vha_557GB	Albany VA Clinic
vha_557GC	Milledgeville VA Clinic
vha_557GE	Brunswick VA Clinic
vha_557GF	Tifton VA Clinic
vha_557HA	Perry VA Clinic

VA Tuscaloosa health care
vha_679	Tuscaloosa VA Medical Center
vha_679GA	Selma VA Clinic
vha_679HK	Tuscaloosa VA Mobile Clinic
