### ISSUE TITLE
[FSR] Chapter 4 content changes

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19204]
## Issue Description
_The VSP content team provided [a document of content changes](https://drive.google.com/file/d/188CvoTOmTkY-uyAZ3JPo8GNW3CmLr_6t/view?usp=sharing) that need to be incorporated into the FSR. This ticket encompasses the content changes that need to be made to chapter 4._

---
## Tasks
- [x] _Incorporate the chapter 4 changes outlined on pages 36 - 41 of the provided document_

## Acceptance Criteria
- [x] _UXPin has been updated and linked in this ticket_
- [x] _Work has been checked off in the [FSR Content epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19132)_

**Comment by rileyorr** [comment]
Chapter 4 content updates have been incorporated & progressive disclosures have been broken out ([UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134307864/simulate/sitemap?mode=i))

**Comment by leahkeeler** [comment]
@rileyorr - Do we need FE tix for this?

**Comment by rileyorr** [comment]
@leahkeeler I created [an epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19513) and attached a bunch of tickets for the FE work. This epic doesn't include the progressive disclosure rework (which has all been incorporated into the UXPin at this point) so during backlog grooming we can decide if we want to create a separate epic or just add tickets to the epic that already exists
