### ISSUE TITLE
[BE] QuestionnaireResponse creation mechanism must use the lighthouse appointment ID URL format

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#19209]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the questionnaire response resource to be created in the lighthouse PGD with the new appointment id in subject

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- Today Appt. ID is in the Meta tag.
- When creating a QuestionnaireResponse resource in the PGD for a patient, the subject field must be populated with an appointment identifier in a format specified by the lighthouse team.

## Tasks
- [x] Update the QuestionnaireResponse Resource module in the health-quest namespace and refactor/add new code which will set the appointment identifier on the subject field for the QuestionnaireResponse resource object
- [x] Update relevant tests

## Acceptance Criteria
- [x] QuestionnaireResponse created in the lighthouse PGD will have the new appointment id URL format in the subject field.
