### ISSUE TITLE
[FSR] Chapter 7 content changes

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19208]
## Issue Description
_The VSP content team provided [a document of content changes](https://drive.google.com/file/d/188CvoTOmTkY-uyAZ3JPo8GNW3CmLr_6t/view?usp=sharing) that need to be incorporated into the FSR. This ticket encompasses the content changes that need to be made to chapter 7._

---
## Tasks
- [x] _Incorporate the changes outlined on page 49 to 52 of the provided document_
- [x] _Since this is the review page, make sure any changes that were made to previous chapters, such as headers, are reflected on this screen as well_

## Acceptance Criteria
- [x] _UXPin has been updated and linked in this ticket_
- [x] _Work has been checked off in the [FSR Content epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19132)_

**Comment by rebeccawalsh** [comment]
[Page has been updated here.](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134117869/simulate/sitemap)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rebeccawalsh @rileyorr! As we continue to restructure content teams for greater clarity, I'm going to add our "sitewide content" and sitewide content-product support" labels to all content tickets that I'm (or @bethpottsVADEPO) involved in so that we can fully track our capacity and differentiate from VSP platform content support. Thanks!
