### ISSUE TITLE
[VAMC] VISN-6 "VA Mid-Atlantic Health Care Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19200]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 7 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site / Documents / Resources
[Google Drive locations for VISN-6](https://drive.google.com/drive/folders/16fYaBYNTGRXYlCWP96OqYEMrNRUrIjTA)

## TASKS
See below associated tasks which should include, but are not limited to:
** Prepare the following Systems for Web Modernization:**
- [ ] VA Asheville health care
- [ ] VA Durham health care
- [ ] VA Fayetteville Coastal health care
- [ ] VA Hampton health care
- [ ] VA Richmond health care
- [ ] VA Salem health care
- [ ] VA Salisbury health care

** Completed the following initiatives for each System included in order:**
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 

**Facilities included for each System**
VA Asheville health care
- [ ] 637	Charles George Department of Veterans Affairs Medical Center
- [ ] 637GA	Franklin VA Clinic
- [ ] 637GB	Rutherford County VA Clinic
- [ ] 637GC	Hickory VA Clinic

VA Durham health care
- [ ] 0	Blind Rehabilitation Outpatient Clinic
- [ ] 558	Durham VA Medical Center
- [ ] 558GA	Greenville VA Clinic
- [ ] 558GB	Raleigh VA Clinic
- [ ] 558GC	Morehead City VA Clinic
- [ ] 558GD	Durham County VA Clinic
- [ ] 558GE	Hillandale Road VA Clinic
- [ ] 558GF	Wake County VA Clinic
- [ ] 558GG	Raleigh III VA Clinic
- [ ] 558QA	Brier Creek VA Clinic

VA Fayetteville Coastal health care
- [ ] 565	Fayetteville VA Medical Center
- [ ] 565GA	Jacksonville VA Clinic
- [ ] 565GC	Wilmington VA Clinic
- [ ] 565GD	Hamlet VA Clinic
- [ ] 565GE	Robeson County VA Clinic
- [ ] 565GF	Goldsboro VA Clinic
- [ ] 565GG	Lee County VA Clinic
- [ ] 565GH	Brunswick County VA Clinic
- [ ] 565GL	Cumberland County VA Clinic
- [ ] 565QA	Robeson Street VA Clinic
- [ ] 565QD	Raeford Road VA Clinic

VA Hampton health care
- [ ] 590	Hampton VA Medical Center
- [ ] 590GB	Virginia Beach VA Clinic
- [ ] 590GC	Albemarle VA Clinic
- [ ] 590GD	Chesapeake VA Clinic

VA Richmond health care
- [ ] 652	Hunter Holmes McGuire Hospital
- [ ] 652GA	Fredericksburg VA Clinic
- [ ] 652GB	Fredericksburg 2 VA Clinic
- [ ] 652GE	Charlottesville VA Clinic
- [ ] 652GF	Emporia VA Clinic

VA Salem health care
- [ ] 658	Salem VA Medical Center
- [ ] 658GA	Tazewell VA Clinic
- [ ] 658GB	Danville VA Clinic
- [ ] 658GC	Lynchburg VA Clinic
- [ ] 658GD	Staunton VA Clinic
- [ ] 658GE	Wytheville VA Clinic

VA Salisbury health care
- [ ] 659	W.G. (Bill) Hefner Salisbury VA Medical Center
- [ ] 659BY	Kernersville VA Clinic
- [ ] 659BZ	South Charlotte VA Clinic
- [ ] 659GA	North Charlotte VA Clinic
