### ISSUE TITLE
Update language around Monthly Housing Allowance on education pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19230]
## Issue Description
Per stakeholder Tammy Hurley the language around the Monthly Housing Allowance has changed and it needs to be updated in plain language on our pages. 

New info Tammy provided:
![Screen Shot 2021-01-28 at 4.42.26 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/21e21bfd-eec7-47e0-bcf0-2918bd4af1d8)

VA.gov page https://www.va.gov/education/benefit-rates/

## Tasks
- [ ] Rework text provided into plain language (Beth)
- [ ] Send to SME for approval (Beth)
- [ ] Add content to relevant pages
- [ ] Review and publish (Randi)
- [ ] Notify stakeholder (Beth/Randi)

## Acceptance Criteria
- [ ] New content live on site

**Comment by RLHecht** [comment]
@bethpottsVADEPO Do we want to keep this ticket open for when we do eventually have this information on our pages or close knowing this will be incorporated in the new content?

**Comment by bethpottsVADEPO** [comment]
Closing this ticket. There's no work currently, since we link to the page that the edu business line already updated with the new housing info.
