### ISSUE TITLE
Appointment List & Details (Homepage Refresh) MVP

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19237]
## Description
- [x] Update current homepage/appointment list with new designs
  - [x] Upcoming
  - [x] Past
  - [x] Requested
  - [x] Canceled

- [x] Separate appointment details into new page
  - [x] VA
  - [x] CC
  - [ ] ~Express Care~
  - [x] VVC
- [x] Update confirmation pages with new designs
- [x] Add Print functionality to appointment details

## Specs
- In context - https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/p/e63f6ca2-9241-4acf-ada6-46b53f460f6d
- Templates/layouts
  - Mobile - https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/p/440ee22f-5200-43e3-ad53-644dc088f5b7
  - Tablet - https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/p/a1d9fd82-5dd6-4954-bc33-dbb9c0fc6bea
- Homepage CTAs - https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/p/61c22a86-100a-42ee-8227-bf81c722f6cd
- Confirmation pages - https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/p/809784a4-663e-4dfc-b367-72fbc7d0903b

**Comment by laurenernest** [comment]
Homepage Refresh launched 100% on 7/20/21
