### ISSUE TITLE
[BE] Move direct deposit emails from GovDelivery > VANotify

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#19233]
## Background

Email changes implementation ticket: https://app.zenhub.com/workspaces/vanotify-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/notification-api/366

Now that [the VANotify platform](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md) is up and running, we can send the direct deposit confirmation emails through there. This will allow us to leverage their template as well as help to keep all of the VA.gov emails on the same platform.

Additional info from [Filip in Slack](https://dsva.slack.com/archives/C010R6AUPHT/p1611871117026300?thread_ts=1611869663.021900&cid=C010R6AUPHT)

> Since it’s all in vets-api it’s actually much less work. We just need to create templates and then your team would need you replace invocation of granicus mailer with calls to VANotify service (module that already exists in vets-api)

See ticket: [Create templates for direct deposit confirmations](https://app.zenhub.com/workspaces/vanotify-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/notification-api/366)

Here are the email templates we
want to add:

Direct deposit edu benefits email
https://gist.github.com/lihanli/0531314d84be03dec669a891149ac060

Direct deposit comp & pen email
https://gist.github.com/lihanli/d5cf0e3bf021e512a341a9f4335aac7f

Also someone was asking how we tracked our email send failures. Looks
like we get that data from the govdelivery API. The code for it is
here: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/transactional_email_analytics_job.rb

Email subject line: "Confirmation - Your direct deposit information changed on VA.gov".

## Tasks

- [ ] Briefly meet to discuss steps with VANotify team (in the process of being scheduled)
- [ ] [Review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md)
- [ ] Get API key
- [ ] Have a template created for the email
- [ ] Complete transition from GovDelivery > VANotify

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 for awareness

**Comment by lihanli** [comment]
@Samara-Strauss @mshea0606  i noticed that we are using the same google analytics campaign name (`direct-deposit-update`) for both edu and comp&pen direct deposit emails. do we want to add a new campaign name for edu benefits emails?

**Comment by Samara-Strauss** [comment]
> do we want to add a new campaign name for edu benefits emails?

@lihanli yes, I think we should be able to clearly differentiate between any analytics we might get from VANotify as to whether they pertain to comp & pen emails or edu emails.

**Comment by lihanli** [comment]
@Samara-Strauss what label do you want to use for the new campaign? not sure if the campaign has to be created in google analytics first or if we can just start using a new label. also, from looking at the code the "failed to send direct deposit email" events will no longer be tracked if we switch to va notify

**Comment by Samara-Strauss** [comment]
> the "failed to send direct deposit email" events will no longer be tracked if we switch to va notify

That's OK. I don't think we're really using this metric much.

> what label do you want to use for the new campaign?

Where does this label show? And what data is it capturing?

**Comment by lihanli** [comment]
at the bottom of a direct deposit email there is a link for a user to go to their profile page "Go to your VA.gov profile"
the link includes the google analytics campaign name, which is currently `direct-deposit-update`

`https://www.va.gov/profile?utm_source=gov-delivery&utm_medium=email&utm_campaign=direct-deposit-update`

not exactly sure what data it's capturing, maybe the analytics team knows

**Comment by Samara-Strauss** [comment]
So you're looking to rename `direct-deposit-update`?

Could we do the following?:

- `direct-deposit-c&p-update`
- `direct-deposit-edu-update`

**Comment by Samara-Strauss** [comment]
Also, can you or @mshea0606 confirm with analytics what that is tracking?

**Comment by lihanli** [comment]
https://dsva.slack.com/archives/CKCRMLGAC/p1613079722137500

i asked in the analytics channel and they mentioned that they're not sure what the `direct-deposit-update` campaign is for but it should be fine to separate it into 2 campaigns or have a campaign term for comp and pen and another one for education benefits.

**Comment by Samara-Strauss** [comment]
OK, sounds good to me. Thanks!

**Comment by lihanli** [comment]
yes i can confirm it tracks when people click the link in the email. what i was asking was is the `direct-deposit-update` campaign part of a group of statistics that includes other direct deposit actions, if we rename it then going into that group will no longer show the "clicked email profile link" action.

**Comment by Samara-Strauss** [comment]
> what i was asking was is the direct-deposit-update campaign part of a group of statistics that includes other direct deposit actions, if we rename it then going into that group will no longer show the "clicked email profile link" action.

I don't *think* it's part of a group. @mshea0606 can you please work to confirm this?

**Comment by mshea0606** [comment]
I will put some time on the calendar with @bmcgrady-ep and @lihanli today to confirm details and include them here.

**Comment by bmcgrady-ep** [comment]
@lihanli - Here is the [link](https://ga-dev-tools.appspot.com/campaign-url-builder/) that is useful in building campaigns.

**Comment by mshea0606** [comment]
To answer your question @lihanli, No, everything that analytics builds (as far as dashboards and reports goes) is around user interactions (events) on the page itself, not on different URLs.

We will have 2 different email campaigns and two different email templates.

cc @Samara-Strauss

**Comment by mshea0606** [comment]
Here is the proposed mock up from @toddstanich:  
![image](https://user-images.githubusercontent.com/60523453/108240545-f2b47a80-7118-11eb-9055-597201c41341.png)

**Comment by mshea0606** [comment]
@miabecker asked if we care about tracking open rates, delivery statuses etc for each of these communications separately? Once we understand this we can understand what to do about the "benefit" question Todd asked in his prior email.

**Comment by mshea0606** [comment]
@toddstanich @miabecker  The subject line for the email will be: "Confirmation - Your direct deposit information changed on VA.gov"

**Comment by mshea0606** [comment]
@toddstanich @miabecker , links to the email templates are above in the "background" section of this ticket for future reference.

**Comment by Samara-Strauss** [comment]
> asked if we care about tracking open rates, delivery statuses etc for each of these communications separately? Once we understand this we can understand what to do about the "benefit" question Todd asked in his prior email.

Yes, we should track emails separately given that comp & pen will see a lot more traffic than edu based on what we know now.

For any review of the design, please ask our designers. It looks good to me, but remember, I am not the designer on the team.

**Comment by mshea0606** [comment]
@sporeboy can you provide your feedback on the email design mockup above?

**Comment by miabecker** [comment]
@mshea0606 cc: @toddstanich below are the template ids for your respective notifications. Do you know if there is an opt in/opt out required for these notifications and if so how are you all handling it? 

dev:

Education Template template id: a995dfe8-ee82-4f42-9ad4-ae82677683ab
Comp & Pen Template id: 779c9b42-9f53-4459-948e-54e51efc07a0

staging:
Education Template template id: b0d2455b-cbbc-4b9b-9345-b468250d68e7
Comp & Pen Template id: 4f2752b7-179d-4b22-9445-47cceeced575

prod:
Education Template template id: 879bfc33-3cb5-4c66-83b8-390c9dbe2af7
Comp & Pen Template id: 36d8ba76-9a08-4dfa-a044-7fe6ec267520

**Comment by Samara-Strauss** [comment]
cc/ @lihanli ☝️ 

> Do you know if there is an opt in/opt out required for these notifications and if so how are you all handling it?

@miabecker there is not opt-in/opt-out because this email is effectively a receipt that direct deposit info was updated.

**Comment by lihanli** [comment]
@miabecker thanks for adding the templates. i noticed that for the staging comp&pen template (`4f2752b7-179d-4b22-9445-47cceeced575`), the "Go to your VA.gov profile" link doesn't have [the right google analytics URL parameters](https://github.com/department-of-veterans-affairs/notification-api/issues/366#issuecomment-779400871). could we get that link updated for all the comp and pen emails? thanks

**Comment by miabecker** [comment]
@lihanli These should be updated now! Thanks for the feedback.

**Comment by Samara-Strauss** [comment]
This work has been merged, but we need to figure out how to test that the emails are working now that they've been moved to VANotify.

**Comment by miabecker** [comment]
I checked with out dev team to see if there was anything on our side but it doesn't seem like this is something we can help with. Let me know how the testing is going for ya'll.

**Comment by ffafara-tw** [comment]
I see that the toggle `direct_deposit_vanotify` is already enabled in dev and staging environments.
You should be able to send emails to test users on va.gov.
I actually can see 2 delivered emails in staging environment for the comp & pen template.

Do you need any specific help from our side?

**Comment by Samara-Strauss** [comment]
> I actually can see 2 delivered emails in staging environment for the comp & pen template.

@ffafara-tw where/how are you seeing this? The challenge around our staging users is that we don't actually have access to the email accounts associated with them, so I'm not sure how our team is supposed to verify everything is working a-ok. I want to make sure we're good before anything gets pushed to prod.

**Comment by ffafara-tw** [comment]
In our platform statistics for va.gov service I could see 2 notifications with delivered status for the comp & pen template.
The direct deposit confirmation is sent to the email address from user profile? There is no way to override it (like it happens on some form submissions)?
Would it be feasible to temporarily change the email address of a test account, so that you can check the inbox?

**Comment by ffafara-tw** [comment]
Maybe we can do a quick zoom session later today, so that I can show you the statistics that we have?
However I still believe that to get full confidence an email should be sent to an inbox you can check.

**Comment by Samara-Strauss** [comment]
> However I still believe that to get full confidence an email should be sent to an inbox you can check.

Me too. I'm gonna ask again in Slack to see if anyone can help.

**Comment by Samara-Strauss** [comment]
@ffafara-tw I don't know that I'm going to be able to get into an actual inbox, so a couple more questions:

> In our platform statistics for va.gov service I could see 2 notifications with delivered status for the comp & pen template.

- Are your stats for staging?
- Do you see any confirmation emails for the edu template? I updated the direct deposit for edu info for our staging user yesterday, so I want to see if an email went out for that. If so, we can close this ticket and further verify functionality in UAT.

**Comment by lihanli** [comment]
we can verify the emails by changing the va profile email for a user, the email job should send to both the login email and the va profile email

**Comment by Samara-Strauss** [comment]
@lihanli you'r a genius. I'll try that.

**Comment by lihanli** [comment]
i'll look into it, not sure why it's not working

**Comment by Samara-Strauss** [comment]
Thank you! Since we are going to UAT tomorrow, it would be ideal if we could figure this out ASAP.

**Comment by lihanli** [comment]
it looks like background jobs are not running at all in staging and i can't login on dev. the emails should be working in production.

**Comment by Samara-Strauss** [comment]
> we can verify the emails by changing the va profile email for a user, the email job should send to both the login email and the va profile email

Changed the user's contact email address to my own and confirmed everything is working. This should be good to close, but I want to confirm one thing first — @lihanli which feature flag(s) is this work behind? Given that the comp & pen feature is already live, that VANotify email probably can get pushed to production. For the edu email, that should be behind the same feature flag (ideally) as the rest of the feature so that the new email goes out as the feature is rolled to production. Let me know how things are set up and what additional tickets we might need, if any, to make sure these rollouts happen accordingly.

**Comment by lihanli** [comment]
there's one feature flag (`direct_deposit_vanotify`) which enables va notify for both direct deposit emails. if the flag is disabled then they both will use govdelivery.

**Comment by Samara-Strauss** [comment]
OK, so let me know if I am understanding this correctly:

- Flipping the flag will turn on VANotify for both emails.
- Right now, that means the new email for comp & pen will go live in production because that feature is live in production.
- For direct deposit for edu, that means staging emails will get sent from VANotify, and then from production as the feature moves to production.

Correct? If so, then we are probably good to flip that flag, but let me know if my understanding is correct first.

**Comment by lihanli** [comment]
that's right, should i turn on that feature for all users now?

**Comment by Samara-Strauss** [comment]
@lihanli yes, please turn on the feature flag! Then we can close this ticket, and we'll be able to make sure that everything is looking good for the new VANotify email in direct deposit for edu UAT.

**Comment by lihanli** [comment]
i found a bug with the implementation, i will need to fix it before enabling in production https://github.com/department-of-veterans-affairs/va.gov-team/issues/21391

**Comment by Samara-Strauss** [comment]
@lihanli OK, thank you for letting me know. UAT starts today, but if the confirmation email should still trigger via GovDelivery at this point, then we should be OK.

**Comment by lihanli** [comment]
vanotify emails are enabled now in production

**Comment by Samara-Strauss** [comment]
Great! I think we are good to close this ticket, then :D
