### ISSUE TITLE
Create detailed recommendations for viewportPreset() use

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#19244]
## Issue Description
As a VFS team member I need more specific guidance about how to best make use of the viewportPreset(). There is an execution time cost associated with running e2e tests in multiple viewports. Which viewports are prudent and how can a VFS team member make that determination? Is there a maximum number of viewports that we allow?

---
## Tasks
- [ ] Modify the best practices document to include specific advice about how to use viewportPreset().
- [ ] Modify the best practices document to include examples of how to determine exactly which viewports should be tested for your application. Platform wide recommendation based on site traffic from GA?
## Acceptance Criteria
- [ ] More detailed best practice documentation for viewportPreset is available to VFS team members.
---

**Comment by pjhill** [comment]
* Global preset? (Default 1000x666)
* Consider recommending that VFS teams us viewportPreset() for a single most used viewport

**Comment by pjhill** [comment]
[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16169) implemented a default viewport size that reflects the current topmost desktop viewport.
