### ISSUE TITLE
TUD: Research various Authentication services

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19243]
## Issue Description
It was brought up during the demo of the Test User Dashboard web application that using a SOCKS proxy on the front-end might not be sufficient enough for any Authenticated/Authorized usage.  More research is needed of using 3rd-party tools (Okta and Auth0) or hand-rolling our own authentication/authorization service for the TUD app. Weighing the pros/cons of each tool/service and keeping notes on integrating each.

---
## Tasks
- [ ] Create a PowerPoint for pros and cons of each service/tool

## Acceptance Criteria
- [ ] Deliverable: PowerPoint for TUD Authenticated/Authorized Experience
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Google Slides: https://docs.google.com/presentation/d/1cgNe0v-50w0rFG5icY0RvHi9OcpL6iJ_4XP0Ox3NCcA/edit#slide=id.ga9d486ddf7_1_0
