### ISSUE TITLE
Update number of days to complete disability related claims for May

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19255]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number into both Drupal pages (Aliyah)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore This is another ticket we need to pull into this sprint. As soon as I have the numbers from Tanekwa we should post them on the site. Thanks!

**Comment by RLHecht** [comment]
@aliyahblackmore The number for May 2022 needs to change to 141.9. Thanks!

**Comment by RLHecht** [comment]
Thanks @aliyahblackmore! I reviewed and published. I also changed April to May, which I realized I don't have as part of the work to do in these tickets (I only have to change the number), so I'll update for next month's.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket
