### ISSUE TITLE
Update number of days to complete disability related claims for May

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19254]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Sandy Tadeo on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [ ] Email Sandy for most recent number 
- [ ] Input number into both Drupal pages
- [ ] Review and publish

## Acceptance Criteria
- [ ] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore This is a ticket that we have each month and it's just updating a number and a date on 2 pages. I can email the stakeholder for the info Monday and walk you through how we usually do the updates so you can do this going forward.

**Comment by RLHecht** [comment]
April's average number is 152.1. @aliyahblackmore and @megzehn Let me know when you have time today and I can screen share with you and we usually do this. It would be good to get this published today but it's a very easy lift.

**Comment by RLHecht** [comment]
Aliyah, Megan and I did this as a screen share and the pages are now published. Moving to validate and will close once it's on the live site.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
