### ISSUE TITLE
Update number of days to complete disability related claims for March

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19253]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Sandy Tadeo on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Sandy for most recent number 
- [ ] Input number into both Drupal pages
- [ ] Review and publish

## Acceptance Criteria
- [ ] Most current number of days is on live site.

**Comment by RLHecht** [comment]
Update: Reached out to Tanekwa Bournes now that Sandy Tadeo is no longer there. She is still awaiting access to get the number for me but is following up with other team members to see if they can help.

**Comment by bethpottsVADEPO** [comment]
Can this be closed @RLHecht ?
