### ISSUE TITLE
Update number of days to complete disability related claims for November

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19261]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number 
- [x] Input number into both Drupal pages
- [x] Review and publish

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
The number for November is 149.4. @lunascoop could you update this and I'll review and publish?

**Comment by RLHecht** [comment]
I published the page. Will close once live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
