### ISSUE TITLE
Update number of days to complete disability related claims for October

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19260]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number 
- [x] Input number into both Drupal pages
- [x] Review and publish

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@lunascoop Could you please update both pages with the following number for October 2021: 144.4 

Thanks!

**Comment by lunascoop** [comment]
@rlhect these pages are ready for review.

How to file a VA disability claim: http://preview-prod.vfs.va.gov/preview?nodeId=905
The VA claim process after you file your claim: http://preview-prod.vfs.va.gov/preview?nodeId=870

**Comment by RLHecht** [comment]
Thanks. I reviewed and published. Moving to validate and will close once live. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
