### ISSUE TITLE
Number of FL search results inaccurately announced by screenreader 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19264]
## Issue Description
During an accessibility discussion with Josh, it was discovered that the Screenreader is announcing a number of results in the subhead. This is problematic because 1- the number of results is actually not in currently displayed in the subhead and 2 - the number of locations presented by the screenreader was inaccurate based on the results list in the scenario observed. 

---
## Tasks
- [ ] Remove screenreader presentation of  number of results 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This issue is apparently no longer occurring on Prod.
