### ISSUE TITLE
Add note to caregiver page to align text with what's on caregiver.va.gov site

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19262]
## Issue Description
We need to add language to the [Program of Comprehensive Assistance for Family Caregivers page](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/) so that it better aligns with what is on caregiver.va.gov. 

Danielle's suggestion to add the following note: 

**Please don't send medical records along with your application.** We'll follow up after we receive your application. If you need help with completing the application or if you'd like to check the status of your application, call us at 855-488-8440, option 3.

We should also add the hours of operation to above. 

## Tasks
- [x] Add text to caregiver page
- [x] Review and publish

## Acceptance Criteria
- [x] New info is live on site

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

The Program of Comprehensive Assistance for Family Caregivers: http://preview-prod.vfs.va.gov/preview?nodeId=10

**Comment by RLHecht** [comment]
Thanks @lunascoop These changes were reviewed and published. Moving to validate and will close after next deploy.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
