### ISSUE TITLE
[SPIKE] Current location accuracy score on VPN

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19282]
## Description
When on VPN, a user that chooses to sort VA facilities or Community Care providers by current location may not receive accurate results.

Original bug report #18893

**Knowns**
- We can't directly detect if a user is on a VPN
- The Geolocation API we use has an accuracy property

---

## Tasks

- [ ] Provide answers to the following questions
  - What is the range of accuracy values?
  - At what approximate thresholds could be considered high/low accuracy confidence?
  - Are there accuracy differences in desktop, IP-based locations when compared to GPS-based locations?
- [ ] Provide possible technical approaches to detecting when accuracy is poor enough to decrease the value of searching by location
- [ ] Provide technical implementation recommendations, including any risks

## Time Box
1 day

**Comment by laurenernest** [comment]
@jbalboni Please update description with any other information or open questions that would be helpful

**Comment by narin** [comment]
Added discovery findings write-up here: 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/geolocation_discovery.md

**Comment by laurenernest** [comment]
Fantastic write-up! Looking at the 3 additional attributes mentioned, `speed` looks like the only one that would require design changes for the additional state. Once you all have time to debrief on which of the possible approaches we'd implement, let me know so we can prioritize.
