### ISSUE TITLE
Implement "type of care" attribute on VAMC front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19284]
## Issue Description
The original hierarchy for health services at the system level uses a Parent -> Child relationship, ie: Mental health -> Mental health Note: this relationship exists at the **system** health services level - not at the **facility** health services level. 

This hierarchy is being replaced by a `type of care` attribute to allow grouping by `attribute` to provide great flexibility in using these services for Vet Centers and other facility types. **This work is necessary for the Vet Center rollout.** 

**This change occurs on the health system level (facility level services do not use these headings)**

New field: `field_service_type_of_care`
Label: "Type of care"
Type: "List (text)"
Possible values: "Primary care, Mental health care, Specialty care, Social programs and services, Other services"
Cardinality: 1 (single value)

Note: the "Possible values" list may expand over time. 

Accordions have been built for "children" only. We will need to ensure that accordions are built for services using the new `type of care` attribute in the absence of a "parent". 

For now, CMS will support both. When this implementation is complete, "parent" will be removed. 

<details>
<summary> Screenshots from the front end and from CMS </summary>

![image](https://user-images.githubusercontent.com/55411834/106316887-ad441200-622a-11eb-9ff1-0d7c6cf31944.png)

![image](https://user-images.githubusercontent.com/55411834/106320908-bf28b380-6230-11eb-9542-2e40c9cf32e2.png)

![image](https://user-images.githubusercontent.com/55411834/106320814-9e605e00-6230-11eb-8c88-43879fbedfda.png)

![image](https://user-images.githubusercontent.com/55411834/106320849-ab7d4d00-6230-11eb-8793-252b6a929886.png)

![image](https://user-images.githubusercontent.com/55411834/106321010-eaab9e00-6230-11eb-86e3-55c0d2cd2fcc.png)

</details>

---
## Tasks
- [x] Update query/Refactor health services to use the `type of care` attribute for grouping 
- [ ] Ignore all terms without "type of care" (former "parent" categories have not been given attributes)

## Acceptance Criteria
- [x] For a given health service **on the system level** , the value for "Type of care" in CMS = grouping heading displayed on ".../health-services/ page
       Example: If "type of care" attribute for PTSD = "Mental health care", then PTSD will appear on **the system** health services page under "Mental health care" heading. 
- [ ] Regardless of "type of care" value, a given health service will be organized in an alphabetical list on the **facility** health services page. 
- [x] The FE renders the same/no visual changes
- [ ] Data layer for accordions is maintained

**Comment by mmiddaugh** [comment]
Question: how does this impact the GraphQL? 
This field is currently available in CMS but is not consumed in front end. How do we access this data?

**Comment by mmiddaugh** [comment]
This field is already available in TomeSync so we're deferring this work until the cms export cutover (so that GRaph QL can be kept out of the mix). Will still require Transformer effort.

**Comment by mmiddaugh** [comment]
How does this change impact the GraphQL query?

**Comment by gescobardev** [comment]
@mmiddaugh We have discovered that the current grouping logic occurs in `sortServices()` - [here](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/health-care-region.js#L19)

This function is not called by the preview server which makes testing/development very difficult.
FYI going to try moving the logic in this function into a liquid.filter to see if this helps the issue.
