### ISSUE TITLE
[VAMC] Audit Specific pages for latest updates and content changes in Pittsburgh [BS]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19287]
## Story
As a Pittsburgh web maintainer, I need now how my pages and source code conforms with current design and plain language standards, so I will know where to improve, update, and correct accessibility.

## Resources
Design Doc

## Tasks
- Review the following nodes/pages for current content requirements/content strategies:
**Observe and report/document**
- [x] Health Services Page 
  ** Surgery Health Service** Must include
  **Surgery Service page** (Added by VAPHS)
   *  Look for added links or mods. (Non standard changes)
   *  Random audit of Health Services for source code (See below)
- [x] University Drive Facility page. 
   * Prepare for your visit
   * Random Health Service
   * Intro / Other
- [x] Heinz Facility page.
   * Prepare for your visit
   * Random Health Service
   * Intro / Other
- [x] Random Health Service Program Page (LGBT, Homeless, Mental, Suicide, etc)
- [x] Random Call to action (Make an Appointment, Pharmacy, etc
- [x] Policies
- [x] Contact us

**Validate if IA actions highlighted in ISSUE 9334 were resolved**
[IA Issue #9334](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9334)

# Acceptance Criteria
- [x] Pages are listed in report
- [x] Document items that do not meet current design/accessibility/Plain Language VA standards

**Comment by ltrombley** [comment]
Task #19287 - Audit Specific pages for latest updates and content changes in Pittsburgh - Complete and moved to Validate
