### ISSUE TITLE
Transformer for refactoring of "type of care" health services 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19286]
## Issue Description
In Implement "type of care" attribute on VAMC front end #19284, the front end was refactored to implement the new `field_service_type_of_care` attribute for grouping system health services. 

---
## Tasks
- [ ] Create transformer to account for `field_service_type_of_care` attribute refactoring

## Acceptance Criteria
- [ ] No loss of front end content

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
