### ISSUE TITLE
Staging Review [Authenticated Experience - Direct Deposit for Edu]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19281]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance criteria in each practice area feedback ticket
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- [x] [DD4edu product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md)
- [x] [DD4edu release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/product/Release%20Plan.md)
- [x] [DD4edu staging user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md)
- [x] QA test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&group_id=402)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/903) in TestRail with test execution logs
  - [x] [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/183)
  - [x] [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/184)
- [ ] [Link to verification that accessibility checks are complete:Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete]()
## Foundational accessibility tests [required](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md)
- [x] [FE] Axe scans in daily development - [read more about the axe browser plugin](#axe-scans-in-daily-development)
- [x] [FE]  Axe scans included in end-to-end (e2e) tests - [read more about e2e tests with axe checks](#axe-scans-in-end-to-end-tests)
- [x] [Design] Color tests for proper contrast and colorblindness - [read more about contrast and colorblindness](#color-tests)
- [x] [Design] Content zoomed to 200%, 300%, 400% - [read more about zoomed layouts](#content-resize-check)
- [x] [Design] Keyboard navigation - [read more about navigating with the keyboard](#keyboard-navigation-check)

## Meeting attendees from **requesting team**
- DEPO product lead (required): **Samara Strauss**
- Product Manager(s) (required): **Matt Shea, Jason Wolf**
- Design: **Jim Adams**
- Accessibility: **Josh Kim**
- Frontend Engineer: **Erik Hansen**
- Backend Engineer: **Lihan Li**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 4 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and shira will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by shiragoodman** [comment]
hey @mshea0606  - when are you looking to schedule this? Please review our [calendar ](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) and be sure to pick a date/time at least 4 business days out. Thanks!

**Comment by tlei123** [comment]
@pjhill , QA-artifact links are now updated above in main description.

cc @Samara-Strauss @mshea0606 @shiragoodman

**Comment by mshea0606** [comment]
@shiragoodman  Monday 2/15 at 3:30pm ET

**Comment by mshea0606** [comment]
@shiragoodman , I forgot about the federal holiday. Can you please reschedule for Tuesday 2/16 at 11:00am ET? Thanks!

**Comment by peggygannon** [comment]
hi, @mshea0606 I want to confirm that this is the staging link we should use to get to the DD work? thx! 

 https://staging.va.gov/profile

**Comment by mshea0606** [comment]
Hi @peggygannon ,the link is:   https://staging.va.gov/profile/direct-deposit

**Comment by mnorthuis** [comment]
@mshea0606 Can you provide an update on the status of when changes needed to this page will be done: 
https://staging.va.gov/change-direct-deposit/

**Comment by allison0034** [comment]
No design feedback.

**Comment by mnorthuis** [comment]
No IA feedback on the profile portion of this work.  No review was done on the static landing page at https://staging.va.gov/change-direct-deposit/ - the content and entry point currently on that page will need to be updated.

**Comment by Samara-Strauss** [comment]
@mshea0606 or @sporeboy can you please point @mnorthuis to the work that was done on the static content page?

**Comment by mshea0606** [comment]
@mnorthuis [Static Direct Deposit Landing Page](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/72860e86-bed9-4e10-8794-223ebb03794f/). @sporeboy can provide you with any additional information.

**Comment by sporeboy** [comment]
@mnorthuis Hi there! The link to the layout/content for the landing page is here: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/72860e86-bed9-4e10-8794-223ebb03794f

**Comment by mnorthuis** [comment]
Thanks @sporeboy, unfortunately we can't do a staging review on a prototype/mock.  If that work is being done by the PW team, it will be up to that team to bring it through the collab cycle for review.  However, I recommend your team stay informed on that work so you can also validate that key entry point to your functionality.  

cc @shiragoodman

**Comment by Samara-Strauss** [comment]
@mshea0606 @sporeboy did no one communicate this need for an update to the content to the PW team? Do we not have a ticket for this work?

**Comment by mshea0606** [comment]
@Samara-Strauss @sporeboy that work is being tracked on this ticket #17826. @RLHecht has already started making the updates.

**Comment by Samara-Strauss** [comment]
@mnorthuis can you work off of #17826?

**Comment by mnorthuis** [comment]
I will review that content page if/when that team brings it through the collab cycle.  This is not a blocker to your work, I'm just letting you know that I have not confirmed that work is done, and recommending that your teams are coordinating on the launch timing.

**Comment by RLHecht** [comment]
The only changes sitewide content is making is removing the ebenefits widget from the page and updating some of the content to match what's in the mockup. Does that kind of work go through the collab cycle?

**Comment by mnorthuis** [comment]
@RLHecht We will follow up with you and team outside of this ticket.  For the sake of this particular review, there are no IA blockers or feedback.

**Comment by Samara-Strauss** [comment]
@shiragoodman does this still need to be open, or can we close it? I think we've done all of the required items, though we are waiting for @joshkimux to get back to do a final review on some of the launch-blocking accessibility tickets (the work is otherwise done pending Josh's review). I am happy to leave this open if we want those tickets to be closed out first, or we can close this and assume those tickets will get resolved when Josh gets back. Let me know either way!

**Comment by shiragoodman** [comment]
Hi @Samara-Strauss  - you can close the ticket. Thanks for checking! We have updated our Staging Review (and other Collaboration Cycle ticket) templates to specify that it's on VFS to close the ticket. We want to make sure you have access to our feedback for as long as you need so we will never close CC tickets. Hopefully the updated templates make this more clear!

**Comment by Samara-Strauss** [comment]
Awesome, thanks! Closing.
