### ISSUE TITLE
Implement new Policies page using new centralized content type

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19289]
## Issue Description
The content structure for the VAMC Policies page has changed to use the new "Centralized content" type. 

## Details
Page:  VAMC System Policies Page (Every VAMC system has a single Policies page)
Content type:  `vamc_system_policies_page`
Contains the standard VAMC system fields and the following new, locally editable, fields specific to this content type
- `field_vamc_visitiation_policy` ("Visitation Policy") 
  - Rich text field. 
  - Required. 
  - Contains default content 
-  `field_vamc_other_policies` ("Other policies") 
    - Rich text field.

## Relevant resources
- [CMS link to Policies top task page](https://prod.cms.va.gov/centralized-content/15588/vamc-system-policies-page)
- [CMS issue #3275](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3275)
- [Relevant section of CMS demo page](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1111195667/Sprint+24+demo+January+29+2021#Policies-and-Centralized-content)
- Policy demo(begins around 32:43)
  -[Link to CMS demo recording](https://zoom.us/rec/share/F6n7-WDTHmMYnm713euUqDnDThUxpZmCspwb48GRStfGIUPHKA8wAZO7OkhT4Wgj.ARt3ZczE_lzoBhHs) Password: UWEozU$2   

<details> 
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/106324355-390f6b80-6236-11eb-8693-6238bf6fc44c.png)

![image](https://user-images.githubusercontent.com/55411834/106324180-f483d000-6235-11eb-957b-75c9b307447e.png)

</details>

## Tasks
- [ ] Build new page
- [ ] Add expected fields
- [ ] Determine appropriate environment/feature flags to be used (there can only be one page with the same URL)

## Acceptance Criteria
- [ ] When the Policies page renders, the following content areas are displayed, consistent with [Pittsburgh Policies page](https://www.va.gov/pittsburgh-health-care/policies/) in production 
      - National intro text
      - National top of page content
      - Privacy and patient rights
      - Family rights
      - Visitation policy
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as a duplicate to #21041
