### ISSUE TITLE
Transformers for VAMC System Policies page 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19290]
Issue Description
In [Implement new Policies page using new centralized content type](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19289), the Policies page front end was refactored to implement the new centralized content structure. 

## Tasks
- [ ] Create transformer to account for  refactoring of Policies page

## Acceptance Criteria
- No loss of front end content

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
