### ISSUE TITLE
674 Update School Type Field

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19302]
## Background
During 674 testing, it was discovered that school type is a required field that gets validated in BGS.  This field should populate the `fullTimeStudntTypeCd` field and in the payload from the FE it is mapped to the `training_program` field under the `school_information` section.

Also, it was discovered that the `partTimeSchoolSubjctTxt` field needs to be set if the Veteran has selected part-time instead of full-time student.  In the payload from the FE this field maps to the `course_of_study` field under the `program_information` section.

## Tasks
- [x] Populate the `fullTimeStudntTypeCd` with the appropriate value.
- [x] If part-time is selected, populate the `partTimeSchoolSubjctTxt` with the appropriate value.

## Acceptance Criteria
- [x] The `fullTimeStudntTypeCd` and `partTimeSchoolSubjctTxt` fields are being set properly.
- [x] Test specs have been updated as needed.
- [x] A PR has been requested for merging.

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5820
