### ISSUE TITLE
[DISCOVERY] FL Sentry error: Failed to initialize WebGL

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19300]
## Issue Description
Engineer review of Sentry identified the following error: Failed to initialize WebGL
- 508 events in a 2 week period, 1.1K occurrences
- Occurring with modern browsers as well as IE 11
   - 79.51% Chrome, 11.5% IE (for at least one list item in Sentry)
- http://sentry.vfs.va.gov/share/issue/d5dd96cf07324c329816ad6e9c1a3cff/

Test for Facility Locator on Firefox 32: User gets the header and footer: nothing in the middle 

---
## Tasks
- [x] Determine level of Veteran impact based on browser use (Michelle)
- [x] Determine options for rendering parts of the page

## Acceptance Criteria
- [x] Steps to reproduce the issue
- [x] Identification of possible options for error handling and page rendering

**Comment by mmiddaugh** [comment]
@davidconlon 
[BROWSER SUPPORT FOR WebGL 2.0](https://www.lambdatest.com/webGL-2.0)

User impact represents the number of sessions between Oct 28, 2020-Jan 28, 2021
Total sessions = 1,724,765

| Browser | Status | User impact |
| --------- | ------  | ------------- |
| Google Chrome | Chrome version 4 to 42 doesn't support WebGL 2.0. can be enabled by Chrome 43 to 55 version. Chrome 56 to 70 supports WebGL 2.0 property. | 103 |
| Mozilla Firefox | This element is not supported by Mozilla Firefox browser version 2 to 24. This property is not supported by default but can be enabled by Firefox 25 to 50 version. Firefox 51 to 63 supports WebGL 2.0 however there are some bugs with overflow | 77 |
| Internet Explorer | IE browser version 6 to 11 doesn't support WebGL 2.0. IE 10 and 11 partially supports this property | 269,182 |
| Safari | Safari browser version 3.1 to 10 doesn't support WebGL 2.0. Safari 10.1 to 11.1 supports it completely. | 5547 | 
| Microsoft Edge | Microsoft Edge browser version 12 to 18 supports this property partially. Edge 16 and 17 supports css grid-layout. | 12,616 | 
| Opera | Opera version 10.1 to 42 doesn't support WebGL 2.0. Can be enabled by Opera 43 to 53 version. Opera 44 to 53 supports WebGL 2.0 property. | 39 |



NOTE: most of the IE browser use between 6 -11 is version 7 and 11 (139,076 and 130,074 respectively). IE 11 is at least partially supported.

**Comment by mpelzsherman** [comment]
When this error occurs, I suggest we add a message to inform veterans that their browser is too old, with info on how to upgrade.

**Comment by mpelzsherman** [comment]
Link to Firefox 50.0 Mac installer: https://ftp.mozilla.org/pub/firefox/releases/50.0/mac/en-US/Firefox%2050.0.dmg

**Comment by mpelzsherman** [comment]
I was able to reproduce this locally using Firefox 32 on BrowserStack with the local testing support.

By adding a `try/catch` around the map initialization code, I was able to determine that the search functionality still works. I suggest we take this approach and show an error message in place of the map, e.g.

"Sorry, your browser doesn't support our map. Please upgrade to a newer browser."

... or something like that.

Here's how it would look in Firefox 32 (released September 2, 2014):

![Dashboard](https://user-images.githubusercontent.com/80267/110021078-4e295f80-7cf8-11eb-91f9-562c5d6c8972.png)

**Comment by mpelzsherman** [comment]
Error handling code pushed to `fl_map_init_error_handling` branch.

**Comment by mpelzsherman** [comment]
BTW - if you view maps.google.com in Firefox 32, you get a blank screen with no error messages.
