### ISSUE TITLE
Claims & Appeals: Sprint 41 Priorities

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#19309]
## Priorities

1. Outstanding tickets from Sprint 40 not already included in priorities below
2. For 526 General Usability Study planning[#19227](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19227#issue-796370632))
3. Follow up with Paul on email approval. #18220 
4. Preparation for NOD - Sprint 42/43

## 526 - Reduce form 526 submission errors, technical debt, and improvements
- [ ] [BE] Original Claims: Deeper Analysis of MVI Add-Proxy Errors  [#10524](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10524)
- [ ] [BE] (Ed creating ticket)
- [ ]  [BE] (Anna creating ticket). 

- [ ] [Design] 526: Fully Developed Claim screen - UX Enhancements #19477 
- [ ] [Design / Research] 526: Military service history - Reserves screen - UX Enhancements #19479 
- [ ] [Design / Research] 526: New or Existing Disability screen - UX Enhancements #19544 

 

## Notice of Disagreement

- [ ] [Research] NOD Research Review #19745 

## Status

<details open>
	 <summary>PENDING</summary><p>

- [ ]  [FE] Error found in 526 schema during submission #14174 - Waiting for the [accordion alert fix](https://github.com/department-of-veterans-affairs/vets-website/pull/14465) to get merged before we can determine if this is still a usability issue
- [ ]  [FE] Disability-benefits all-claims has axe violations #14013 - Waiting for our [axe-core library upgrade](https://github.com/department-of-veterans-affairs/vets-website/pull/16056) before I can try to fix this problem. The color contrast issue is still a false-positive problem with the current axe-core version. **Will be unblocked on 2/18/2021**
</p></details>

<details open>
	 <summary>ON-GOING</summary><p>

- [ ] [FE] Claims Status: Display or Provide Link to Decision Letter #13405. 
 - [ ] List item
 - [ ] List item
 - [ ] List item
</p></details>

<details open>
	 <summary>DONE</summary>

 - [x] [FE ] Update 526 Suggested endpoint facilities [#14028](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14028) 
 - [ ] List item
 - [ ] List item
</details>
