### ISSUE TITLE
Updating debt questions on COVID FAQs English and Spanish versions

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19310]
## Issue Description
Danielle updated two debt questions on the COVID FAQs page. These need to be copyedited and reviewed in both the English and Spanish versions. The meta description was also updated in the Spanish version.

Once changes are reviewed we need to do a manual content release.

## Tasks
- [x] Review changes on COVID FAQs English version
- [x] Review changes on COVID FAQs Spanish version by comparing to a Word doc
- [x] Review meta description on Spanish version
- [x] Publish pages
- [x] Do manual content release

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by RLHecht** [comment]
These changes were made and work complete. Created ticket to track. Closing ticket. FYSA @DanielleThierryUSDSVA
