### ISSUE TITLE
CC - selected provider distance from current location

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19335]
## Issue Description
Add distance of provider from current location when selecting a preference from list sorted by current location. (Compared to distance from address when preference is selected from list sorted by residence address.)

In #19010, distance was removed to temporarily resolve the bug.

---
## Tasks/Technical Notes
- Provider distance is shown from the sorting origin selected

## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag
- [ ] The distance shown on the selected provider information should match the distance shown when selecting the provider from the list
![VAOS-CC-MVP-04@2x copy.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/4d04d27d-a216-4d15-94d9-0402532207c9)
- [ ] The distance shown is the same after leaving and coming back to the provider selection page (for both sorting origins: current location or residential address)

**Comment by laurenernest** [comment]
@jbalboni Can you add any other notes to the description, technical or otherwise, that might be helpful for this work?
