### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Black Hills health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19336]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-23 Internal Review Folder](https://drive.google.com/drive/folders/1TCMIslLjIEkGTGfH9IIgijxs_zaNiBms)
[Review template for review](https://drive.google.com/drive/folders/1yikdjmdiPXRrJCJj-5m6W_3Nr8bxT22u)

## Tasks
- 1) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 568	Fort Meade VA Medical Center
- [x] 568A4	Hot Springs VA Medical Center
- [x] 568GA	Rapid City VA Clinic
- [x] 568GB	Pierre VA Clinic
- [x] 568HA	Newcastle VA Clinic
- [x] 568HB	Gordon VA Clinic
- [x] 568HF	Pine Ridge VA Clinic
- [x] 568HH	Scottsbluff VA Clinic
- [x] 568HJ	Mission VA Clinic
- [x] 568HP	Winner VA Clinic- 
- [x] 568GB01	Wessington Springs VA Clinic
- [x] 568HK	McLaughlin VA Clinic

- 2) Review and correct all **Broken Links** on each of the system pages in Devshop

- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [ ] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by lealester** [comment]
Added from VAST: 568GB01 Wessington Springs VA Clinic & 568HK McLaughlin VA Clinic

**Comment by lealester** [comment]
Not able to test in tugboat: Hot Springs VA Medical Center, McLaughlin VA Clinic, Wessington VA Clinic, & Campus Map
