### ISSUE TITLE
Salesforce-GIBFT Connection for vets-api in STAGING not working 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19331]
## Description
Salesforce-GIBFT Connection for vets-api in STAGING is not working and VSP Operations DevOps engineers have been brought in to help debug and fix the connection. Users of the front end application are receiving an error when trying to submit data through the GI Bill Feedback Tool (https://staging.va.gov/education/submit-school-feedback/introduction)

## Background/context/resources
- rotating variable consumer key
- consumer key gets updated periodically (monthly?)
- STAGING to UAT environment was previous connection
- STAGING to REG environment is new connection
- [currently open pr/branch in devops with new changes](https://github.com/department-of-veterans-affairs/devops/pull/8449/files)
- [merged pr in vets-api to update environment naming scheme](https://github.com/department-of-veterans-affairs/vets-api/pull/5807)
- [knowledge dump left for us by Johnny Holton](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14921)

## Technical notes
- @jbritt1 has worked w/ @lihanli, @LindseySaari, and @dginther to try and debug the connection
- Jeremy has been in touch with external teams to try and resolve this issue 
- Consumer key is now up to date with exact value provided by Salesforce
- The [cert signing key](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-server-vagov-staging.yml#L182) also had to be changed from the one we use in STAGING, to the one that we use for DEV (ref: https://dsva.slack.com/archives/CJYRZK2HH/p1611956508150000?thread_ts=1611872226.101200&cid=CJYRZK2HH)
- [Invalid header article found on stackexchange ](https://salesforce.stackexchange.com/questions/234316/messageinvalid-header-type-errorcodeinvalid-auth-header-received)
- [ Sentry errors found that may be related](http://sentry.vfs.va.gov/organizations/vsp/issues/5210/?environment=staging&query=is%3Aunresolved&statsPeriod=24h)
- This connection WORKS when using the rails console to trigger the action (forcing a query / POST from rails console) 
- Example of past rails console commands that have worked:
```
Gibft::Service::CONSUMER_KEY = 'REDACTED'
Gibft::Service::SALESFORCE_USERNAME = 'vetsgov-devops-ci-feedback@listserv.gsa.gov.reg'
Gibft::Configuration::SALESFORCE_INSTANCE_URL = 'https://va--reg.my.salesforce.com/'
service = Gibft::Service.new
body = service.send(:request, :post, '', service.oauth_params).body
```

---
## Tasks
- [ ] External team wants to meet again to continue troubleshooting

## Definition of Done
- [ ] Salesforce-GIBFT connection for vets-api will be working in STAGING

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by LindseySaari** [comment]
Backend notes:

Opened a rails console in vets-api-server staging
The below command returns a valid access token/response:
```
service = Gibft::Service.new
service.get_oauth_token
```
When Lori tried submitting on her end, we found this [sentry error](http://sentry.vfs.va.gov/organizations/vsp/issues/5210/?environment=staging&project=3&query=is%3Aunresolved+GiBill&statsPeriod=14d)

All of the newly updated credstash values are checking out in the rails console

This[ job](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/gi_bill_feedback_submission_job.rb#L14) is what calls submit 
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/gibft/service.rb#L23 <--- The line is throwing the Restforce::UnauthorizedError error

Sentry error shows INVALID_AUTH_HEADER: INVALID_HEADER_TYPE

`{
error: invalid_client, 
error_description: invalid client credentials
}`

**Comment by lihanli** [comment]
rails console commands no longer work for connecting, i think they have changed something in their configuration since friday and they need to change it back or give us the updated values

**Comment by jbritt1** [comment]
> rails console commands no longer work for connecting, i think they have changed something in their configuration since friday and they need to change it back or give us the updated values

The consumer_key was updated again @lihanli, I can pass that to you if you'd like.

I also ran the seed job to return everything to defaults in the meantime as well so staging vets-api does not continue to deploy my branch.

**Comment by LindseySaari** [comment]
I was able to reproduce the error in the console by running

`
client = Gibft::Service.new.get_client
`
`
client.post('/services/apexrest/educationcomplaint', '').body`

**Comment by omgitsbillryan** [comment]
Some random observations from someone who knows nothing about gibft & salesforce, excuse my ignorance in advance:

- based on the Sentry error, `get_oauth_token` is returning `nil`. The code marches onward however, and tries to insantiate `Restforce.new` instance using `oauth_token: nil` - which probably explains the `Restforce::UnauthorizedError` exception
- [`exp` is set to `Time.now.utc.to_i` in the JWT token claim](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/salesforce/service.rb#L25) - is this right? I would expect something like Time.now + 5 minutes or something
- the [`with_monitoring` wrapper isn't doing anything on the `get_oauth_token` POST request](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/salesforce/service.rb#L34) since nothing gets raised. As a result, [`api_gibft_get_oauth_token_fail` in prometheus shows 0 errors ](http://prometheus-staging.vetsgov-internal:9090/prometheus/graph?g0.range_input=1w&g0.expr=api_gibft_get_oauth_token_fail&g0.tab=1) despite errors clearly happening
  - I opened a WIP PR to address this problem - [WIP PR Link](https://github.com/department-of-veterans-affairs/vets-api/pull/5816)
- the GIBillFeedbackSubmissionJob [tries to find the user](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/gi_bill_feedback_submission_job.rb#L13) but that user may no longer exist in Redis by the time the job is executed - is it ok if no user is found? (this is a common 'gotcha' for async sidekiq jobs)

**Comment by jbritt1** [comment]
Also, just to rope everyone in here about another small change I am about to make:

As Bill suggesting in https://github.com/department-of-veterans-affairs/devops/pull/8449#discussion_r567952388 to keep the naming schemes in line I have updated the `gibft_sfdc.staging.key` for signing to the same value as `gibft_sfdc.dev.key` in credstash and updated to that new version. This keeps the naming scheme a bit more consistent and less confusing, but wanted to make sure we all stayed on the same page with it.

**Comment by jbritt1** [comment]
Alright #8449 has been merged and deployed and those values should stay the same for future deploys until we make additional changes.

**Comment by LindseySaari** [comment]
When I run the [get_client method](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/gibft/service.rb#L21) in the rails console in staging `client = Gibft::Service.new.get_client`, the Restforce client object that gets returned has a host of :host=>"login.salesforce.com". login is associated with the prod env and this should be test I believe (test.salesforce.com). Just something I noticed that might contribute to the invalid credentials/access token issues

**Comment by jhouse-solvd** [comment]
@LindseySaari - that sounds like a potentially good find. if i recall correctly, it works from the rails console, and in production, no? this might help us narrow down what's happening here...

**Comment by jhouse-solvd** [comment]
@dginther - Passing this to you for follow up.

**Comment by LindseySaari** [comment]
Correct, @jhouse-solvd. It works in the rails console, but not in the staging environment. It appears that prod works properly.

**Comment by jbritt1** [comment]
Newly linked PR shows an email I received this morning about pertaining to this external business partner / connection.

**Comment by jbritt1** [comment]
Seems there are also some successes being observed in staging at this time (redacted ip addresses just in case):

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/9af0d08f-b99a-42a8-b516-f142aac59d27)

**Comment by jbritt1** [comment]
Never mind, another team member tested and is still seeing errors in staging :\

**Comment by jbritt1** [comment]
![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/a09f3e25-5ac3-4da1-be32-92e6d960094b)

**Comment by jbritt1** [comment]
I am unsure on the specifics of any changes made on the other side, but it appears this is now resolved.

**Comment by jbritt1** [comment]
Additional notes:

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/37899697-0cb3-4966-aed1-5eee8cba38a2)

**Comment by jbritt1** [comment]
Success in dev as well:

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/210a5388-0e30-46f1-bed0-46ad2a1257ce)

**Comment by jhouse-solvd** [comment]
@jbritt1 - thanks so much for following up on this. It sounds like things are now working in DEV, STAGING, and that this can be closed
