### ISSUE TITLE
[VAMC] VISN-21 "Sierra Pacific Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19338]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 7 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site / Documents / Resources
[Google Drive locations for VISN-21](https://drive.google.com/drive/folders/186yH0BF26ofcI0FZJmBHc_U4Zz6kpYfr)

## TASKS
See below associated tasks which should include, but are not limited to:
** Prepare the following Systems for Web Modernization:**
- [ ] VA Central California health care
- [ ] VA Northern California health care
- [ ] VA Pacific Islands health care
- [ ] VA Palo Alto health care
- [ ] VA San Francisco health care
- [ ] VA Sierra Nevada health care
- [ ] VA Southern Nevada health care

** Completed the following initiatives for each System included in order:**
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 

**Facilities included for each System**
VA Central California health care
- [ ] 570	Fresno VA Medical Center
- [ ] 570GA	Merced VA Clinic
- [ ] 570GB	Tulare VA Clinic
- [ ] 570GC	Oakhurst VA Clinic

VA Northern California health care

- [ ] 0	McClellan VA Dental Clinic
- [ ] 612A4	Sacramento VA Medical Center
- [ ] 612B4	Redding VA Clinic
- [ ] 612BY	Oakland VA Clinic
- [ ] 612GD	Fairfield VA Clinic
- [ ] 612GE	Mare Island VA Clinic
- [ ] 612GF	Martinez VA Medical Center
- [ ] 612GG	Chico VA Clinic
- [ ] 612GH	McClellan VA Clinic
- [ ] 612GI	Yuba City VA Clinic
- [ ] 612GJ	Yreka VA Clinic
- [ ] 612QB	Twenty First Street VA Clinic

VA Pacific Islands health care
- [ ] 459	Spark M. Matsunaga VA Medical Center
- [ ] 459GA	Maui VA Clinic
- [ ] 459GB	Hilo VA Clinic
- [ ] 459GC	Kailua-Kona VA Clinic
- [ ] 459GD	Lihue VA Clinic
- [ ] 459GE	Guam VA Clinic
- [ ] 459GF	Faleomavaega Eni Fa'aua'a Hunkin VA Clinic
- [ ] 459GG	Leeward Oahu VA Clinic
- [ ] 459GH	Saipan VA Clinic
- [ ] 459QA	Lanai VA Clinic
- [ ] 459QB	Molokai VA Clinic

VA Palo Alto health care
- [ ] 640	Palo Alto VA Medical Center
- [ ] 640A0	Palo Alto VA Medical Center-Menlo Park
- [ ] 640A4	Palo Alto VA Medical Center-Livermore
- [ ] 640BY	San Jose VA Clinic
- [ ] 640GA	Capitola VA Clinic
- [ ] 640GB	Sonora VA Clinic
- [ ] 640GC	Fremont VA Clinic
- [ ] 640HA	Stockton VA Clinic
- [ ] 640HB	Modesto VA Clinic
- [ ] 640HC	Major General William H. Gourley VA-DoD Outpatient Clinic

VA San Francisco health care
- [ ] 662	San Francisco VA Medical Center
- [ ] 662GA	Santa Rosa VA Clinic
- [ ] 662GC	Eureka VA Clinic
- [ ] 662GD	Ukiah VA Clinic
- [ ] 662GE	San Bruno VA Clinic
- [ ] 662GF	San Francisco VA Clinic
- [ ] 662GG	Clearlake VA Clinic

VA Sierra Nevada health care
- [ ] 654	Ioannis A. Lougaris Veterans' Administration Medical Center
- [ ] 654GB	Carson Valley VA Clinic
- [ ] 654GC	Lahontan Valley VA Clinic
- [ ] 654GD	Diamond View VA Clinic

VA Southern Nevada health care
- [ ] 0	Mike O'Callaghan Military Medical Center
- [ ] 593	North Las Vegas VA Medical Center
- [ ] 593GC	Pahrump VA Clinic
- [ ] 593GD	Northwest Las Vegas VA Clinic
- [ ] 593GE	Southeast Las Vegas VA Clinic
- [ ] 593GF	Southwest Las Vegas VA Clinic
- [ ] 593GG	Northeast Las Vegas VA Clinic
- [ ] 593GH	Master Chief Petty Officer Jesse Dean VA Clinic
