### ISSUE TITLE
Create Anchor Tags on the Coronavirus FAQ page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#19337]
## User Story 1

- As a Veteran or VA call center representative, I'd like to provide someone with a link that opens to a particular question/answer within an accordion or outside of the accordion on the "Coronavirus FAQs: What Veterans need to know" page. 

- Link: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ 

### Example - question that's not inside an accordion:
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/c64485c0-e539-4de5-8d63-a56170dbc696)

### Example - question that is inside an accordion:
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/0b5a1182-8d27-41b6-b1ac-735a1d41d7b0)

## Expected Behavior

- When the SENDER user clicks on the anchor link affordance, the anchor link URL will be copied. (So they can share the anchor link to that question text.) 
- When a user RECEIVES the anchor link URL and clicks on it, they will land on the specific Q/A (whether residing within an accordion or outside).
- If the Q/A is inside an accordion, it should be defaulted to the "open" position when they user lands there from an anchor link.

## Acceptance Criteria

- [ ] SENDER: Upon clicking the affordance, the anchor link URL will be copied, and they will receive some UX clue that it has been copied. 
- [ ] Upon clicking the RECEIVED link, the user will get taken to the the relevant Q/A  displayed at top of screen
- [ ] Each Q/A will have a unique ID element within the URL which continues to work even if some of the text for the Q/A's are modified.

## User Story 2

- Each Q/A -- within the accordion or near the H3 question text (for questions that are not inside an accordion) will have a "share" link affordance (placement for this?)

## Acceptance Criteria

- [ ] Each "answer" in a Q/A  section will display a "hyperlink" symbol 🔗  to indicate the specific question can be copied and pasted for sharing
- [ ]  When the shared anchor link is received and clicked on, the link will route to appropriate Q/A.

## Older tickets for reference only: 

- https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15758 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/7523 

## Highlighted Q/A's that will need anchor links in attached:

[https://app.zenhub.com/files/133843125/dbe30234-3589-4b05-9471-75094784f242/download](https://app.zenhub.com/files/133843125/dbe30234-3589-4b05-9471-75094784f242/download)

**Comment by jenniferlee-dsva** [comment]
I found another example of this affordance on the government 508 website: 

![accessible-section-linkit-feature-121720.PNG](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/96f1f1c1-7b95-4c10-b3ce-71de34a8c9f8)
