### ISSUE TITLE
Create checklist for removing feature toggles from pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19330]
## Issue Description
We need to create a checklist for the steps to take when removing a feature toggle that has been put in place. This will avoid removing it prematurely and causing an issue with users accessing the application or page that it is going to. 

Once the checklist is created, it should be stored in the Sitewide Content folder within Drupal: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content

## Tasks
- [x] Create checklist (Randi)
- [x] Review checklist (Danielle)
- [x] Add to folder within Github

## Acceptance Criteria
- [x] Checklist complete and accessible to Sitewide Content team

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I created a checklist for removing the feature toggle like we discussed last week. Can you take a look at this and if it's good, I'll put it into Github and store it in our Sitewide Content folder? Thanks!

[https://app.zenhub.com/files/133843125/4c479687-6a47-4339-9ce4-a782064bf37a/download](https://app.zenhub.com/files/133843125/4c479687-6a47-4339-9ce4-a782064bf37a/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht! This is great. Looking at this more, I think we can make this a process doc that we can share with product teams for greater clarity around this process as well. I reworked the doc a bit to that end. Let me know what you think. Once we're ready, we can add this in GH and then also share out with product teams as well as the public websites team so they're also fully aware/aligned.

Thanks so much for putting this together!

[Dynamic content process_danielle](https://app.zenhub.com/files/133843125/4ea1ddc3-903e-47e7-9052-b2aef69ef995/download) 

cc @bethpottsVADEPO

**Comment by RLHecht** [comment]
This looks good, @DanielleThierryUSDSVA. My only change was adding more info to the step when sitewide content puts the react widget on the page. I added that the new page should match the mockup that the product team provides. 
[Dynamic content process-Randi edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6103453/Dynamic.content.process-Randi.edit.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Awesome! Thank you, @RLHecht!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I added this as an md file in our github sitewide content folder. Let me know if you want to take another look before we share it out.

**Comment by RLHecht** [comment]
work completed. closing ticket.
