### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Iowa City health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19341]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-23 Internal Review Folder](https://drive.google.com/drive/folders/1TCMIslLjIEkGTGfH9IIgijxs_zaNiBms)
[Review template for review](https://drive.google.com/drive/folders/1yikdjmdiPXRrJCJj-5m6W_3Nr8bxT22u)

## Tasks
- 1) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 636A8	Iowa City VA Medical Center
- [x] 636GF	Quad Cities VA Clinic
- [x] 636GG	Quincy VA Clinic
- [x] 636GH	Waterloo VA Clinic
- [x] 636GI	Lane A. Evans VA Community Based Outpatient Clinic
- [x] 636GJ	Dubuque VA Clinic
- [x] 636GN     Cedar Rapids VA Clinic
- [x] 636GS	Ottumwa VA Clinic
- [x] 636GT	Sterling VA Clinic
- [x] 636GU	Decorah VA Clinic
- [x] 636GW	Coralville VA Clinic
- [x] 636QG      Iowa City VA Mobile Clinic
- [x] 636QJ       Iowa City VA Clinic
- [x] 636QC	Linn County VA Clinic
- [x] 636QD      Macomb VA Clinic
- [x] 636QI       Davenport VA Clinic
- 2) Review and correct all **Broken Links** on each of the system pages in Devshop

- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [ ] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by lealester** [comment]
Added From VAST: Grand Island VA Medical Center 636A4, Lincoln VA Clinic 636A5, Des Moines VA Medical Center 636A6, Norfolk VA Clinic 636GA, North Platte VA Clinic 636GB, Mason City VA Clinic 636GC, Marshalltown VA Clinic 636GD, Fort Dodge VA Clinic 636GK, Bellevue VA Clinic 636GL, Carroll VA Clinic 636GM, Shenandoah VA Clinic 636GP, Holdrege VA Clinic 636GQ, Knoxville VA Clinic 636GR, Fort Dodge North VA Clinic 636GX, Omaha VA Clinic 636QA, Des Moines VA Clinic 636QB, Linn County VA Clinic 636QC, Macomb VA Clinic 636QD, Iowa City VA Mobile Clinic 636QG, Des Moines VA Mobile Clinic 636QH, Davenport VA Clinic 636QI, Iowa City VA Clinic 636QJ

**Comment by lealester** [comment]
Unable to test in tugboat: Lane A. Evans VA Community Based Outpatient Clinic, Iowa City VA Mobile Clinic, Iowa City VA Clinic, Linn County VA Clinic, Macomb VA Clinic, Davenport VA Clinic
