### ISSUE TITLE
[UI] Completed Tab Defaults to a filtered date range 

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#19347]
## User Story
- As a Veteran, I want a way to quick start reviewing a portion of my health questionnaires, if my complete history of completed questionnaires will take some time to load.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
> What will the team get at the end of this ticket?
A wireframes set of the completed tab showing how to deal with this loading issue as well as how to change (manually or automatically) the time period being displayed with the technical specifications needed for engineering to implement said feature.

## Tasks
- [x] Review this functionality in VAOS
- [x] Finalize detailed mockup and callouts of [feature name](link to prototype)

## Acceptance Criteria
- [x] UI review meeting with product/team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Published mockup link exists and it is added/updated within the product feature outline

**Comment by kristenmcconnell** [comment]
@abuckley3385 @stephenBarrs Do I need to add the To Do tab to this story as well. We mentioned that the To Do tab would show the next year's worth of questionnaires. Can someone ever schedule more than a year out right now?

**Comment by kristenmcconnell** [comment]
**Information from VAOS.** 

- For the past appts it looks like we go back two years. They are looking into the reasons why these particular date ranges were chosen.
![Screen Shot 2021-02-05 at 10.43.13 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ace5316b-ce32-4c5d-bc09-5364715db50f)
- VAOS displays appts 395 days in the future in the upcoming list. This is likely more of a business decision than a technical limitation - 395 days is the furthest out direct scheduled appts are allowed by default (though some facilities may have tweaked this default)
- If there's nothing in the past three months we show some messaging that says to choose a different date range. They are looking into providing a screenshot to me of this scenario.

**Comment by kristenmcconnell** [comment]
VA payments example (the call takes a long time to load, but they load everything, then paginate)

![Screen Shot 2021-02-10 at 3.03.52 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/50686c1e-e675-4dca-b7b9-c93ef0ddd4ee)
![Screen Shot 2021-02-10 at 3.04.39 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/a401338b-9386-4d06-bbcb-89d898a8628e)

**Comment by kristenmcconnell** [comment]
Possible options to review with designers...

Option 1
![Loading Option 1 A.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/cbe53ea8-c33f-4a03-9931-4a28f9da8e1d)

Option 2
![Loading Option 2.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/dda9b593-efb4-4961-9da3-0a306c56c9a5)Option 1

**Comment by kristenmcconnell** [comment]
@sshein @joshkimux @allison0034 I was wondering if the three of you could provide some feedback on possible design options that I atta

**Comment by sshein** [comment]
Hi Kristen I looked through your mocks and am a little confused about what exact parts you want thoughts on, sorry! I think you're wondering if we should go with pagination or some kind of "load more" button given that it might take awhile to load things.

My immediate thought is that initially, if it takes awhile to load things, we should just have the loading indicator on a white background (no boxes around it) that says "Loading your health care questionnaires (this may take x minutes)" or something... without details as to how many months back things are going because why does the user need to know that? I think @peggygannon gave someone language (maybe Jonathan on Caregiver?) for long wait times at some point. 

Then it seems like we should just go with our normal pagination. 

But let me know if I'm missing some nuances here.

**Comment by kristenmcconnell** [comment]
@sshein You did kind of identify my main question. I think that a "load more" might be needed, since we will be loading these questionnaires through a series of calls. Only the first 12 months of health questionnaires will load at first, then engineering proposed immediately doing a second call on the back end to pull more in.  I didn't see any va.gov solutions that utilized the load more pattern (I may just not know of an example). I wanted to get input on introduction that pattern.

Some more nuances to consider...some people might have a very large amount of questionnaires returned in that first call. If I introduce pagination at that point, then the pagination numbers would change when the other call return, which is weird. If pagination isn't introduced at that point, then it could feel more like infinite scrolling until all calls return. Also, what happens if someone is far down the list when the second call is returned and what they were looking at ends up on the second or third page in the pagination. I might be over thinking this (I probably am), but I just envision some possibly weird interactions. I was thinking that infinite scrolling does well for this lazy loading of list items, but I know that has accessibility concerns and our footer/Need help sections complicate that.

VAOS solved this by completely avoiding the loading of multiple calls and went with the date range filter solution. I could go that route too, but I wasn't sure if that was the pattern that we want to go with.

**Comment by kristenmcconnell** [comment]
Just talked to the team and this story just got a lot easier. To cut engineering scope for MVP, we will only be pulling in just the past 1 year of questionnaires. It will just be one call, so this will result in just a simple loading indicator with traditional va.gov pagination. This way we don't have to deal with filtering yet, either. This gives us a year to enhance this before anyone would have a questionnaire that wouldn't display on the completed questionnaire tab. This ticket will come back around at a later date.

@sshein Thanks for taking a look at this though.

**Comment by kristenmcconnell** [comment]
@mdewey After our discussion today, we need a loading indicator saying "Loading health questionnaires..." and normal va.gov display pagination.

**Comment by joshkimux** [comment]
@kristenmcconnell just a heads up, the pagination is in the design system backlog for an update given its volume of accessibility issues!

**Comment by kristenmcconnell** [comment]
@joshkimux Given those accessibility problems, is it better for us to just have a long list of cards right now or implement the pagination?

**Comment by joshkimux** [comment]
@kristenmcconnell Go ahead and implement! I'm hoping that with an update all those issues will be fixed down the road-- just wanted to give you a heads up since accessibility tickets could be written up on them just for documentation/tracking purposes 😄

**Comment by kristenmcconnell** [comment]
@joshkimux Just checking that it wasn't something big that was found. Great. We will continue on then.
