### ISSUE TITLE
[FE] Profile - Do not try getting full name, personal info, or military info for LOA1 users

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#19349]
## Background
If a user is LOA1 we should not even try to get their name, personal info, or military info for the Profile.

We should also make sure we don't show the generic Profile error if that data is not available.

## Tasks
- [x] stopping making those API calls from the Profile if the user is LOA1 (https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/applications/personalization/profile/components/Profile.jsx#L66-L68)
- [x] adjust the logic for determining if all Profile data has loaded (https://github.com/department-of-veterans-affairs/vets-website/blob/982dee29c4b2023efcf9f179812f286e01196162/src/platform/user/profile/vap-svc/actions/transactions.js#L206)
- [x] confirm that `showNotAllDataAvailableError` does not flip to true for LOA1 users (https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/applications/personalization/profile/components/ProfileWrapper.jsx#L120-L125)
- [x] potentially update the LOA1 Cypress tests to confirm endpoints aren't hit https://github.com/department-of-veterans-affairs/vets-website/blob/5c47006a97d9d73906ddef0f5b58ee3e362b2f98/src/applications/personalization/profile/tests/e2e/profile.loa1.cypress.spec.js

**Comment by erikphansen** [comment]
fix merged with commit `a37afc8de3d995d7525907db631aba8c42cf5a9d `: https://frontend-support-dashboard.vercel.app

**Comment by ajakabcin** [comment]
confirmed on staging
