### ISSUE TITLE
Add Space Force to 10-10EZ

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#19354]
## User Story

As a veteran, I would like to be able to select US Space Force as my service branch when I apply for healthcare using the online 10-10EZ form.

Acceptance criteria:
- [ ] Added it to the dropdown for last branch of service
- [ ] Adding the new reference code to send it in the interface to ES
- [ ] Tested in Staging prior to release

**Comment by mlighdc** [comment]
@ala-yna can you slate this for the sprint close to May 22? Based on Josh's email, the backend system should be able to receive this value after May 22.  Should not be hard to implement. Thanks.

**Comment by tchrisdyer** [comment]
This has been completed and in production. Closing
