### ISSUE TITLE
[VAMC] VISN-23 "VA Midwest Health Care Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19351]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 8 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site / Documents / Resources
[Google Drive locations for VISN-23](https://drive.google.com/drive/folders/1ttwMd4VOpbWYNR6dfKvR1aPtuqKbsLAX)

## TASKS
See below associated tasks which should include, but are not limited to:
** Prepare the following Systems for Web Modernization:**
- [ ] VA Black Hills health care
- [ ] VA Central Iowa health care
- [ ] VA Fargo health care
- [ ] VA Iowa City health care
- [ ] VA Minneapolis health care
- [ ] VA Nebraska-Western Iowa health care
- [ ] VA Sioux Falls health care
- [ ] VA St Cloud health care

** Completed the following initiatives for each System included in order:**
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] Site Published and LIVE
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live 

**Facilities included for each System**

VA Black Hills health care
- [ ] 568	Fort Meade VA Medical Center
- [ ] 568A4	Hot Springs VA Medical Center
- [ ] 568GA	Rapid City VA Clinic
- [ ] 568GB	Pierre VA Clinic
- [ ] 568HA	Newcastle VA Clinic
- [ ] 568HB	Gordon VA Clinic
- [ ] 568HF	Pine Ridge VA Clinic
- [ ] 568HH	Scottsbluff VA Clinic
- [ ] 568HJ	Mission VA Clinic
- [ ] 568HP	Winner VA Clinic

VA Central Iowa health care
- [ ] 636A6	Des Moines VA Medical Center
- [ ] 636GC	Mason City VA Clinic
- [ ] 636GD	Marshalltown VA Clinic
- [ ] 636GK	Fort Dodge VA Clinic
- [ ] 636GM	Carroll VA Clinic
- [ ] 636GR	Knoxville VA Clinic

VA Fargo health care
- [ ] 437	Fargo VA Medical Center
- [ ] 437GA	Grafton VA Clinic
- [ ] 437GB	Bismarck VA Clinic
- [ ] 437GC	Fergus Falls VA Clinic
- [ ] 437GD	Minot VA Clinic
- [ ] 437GE	Bemidji VA Clinic
- [ ] 437GF	Williston VA Clinic
- [ ] 437GI	Grand Forks VA Clinic
- [ ] 437GJ	Dickinson VA Clinic
- [ ] 437GK	Jamestown VA Clinic
- [ ] 437GL	Devils Lake VA Clinic

VA Iowa City health care
- [ ] 636  (See Nebraska)
- [ ] 636A8	Iowa City VA Medical Center
- [ ] 636GF	Quad Cities VA Clinic
- [ ] 636GG	Quincy VA Clinic
- [ ] 636GH	Waterloo VA Clinic
- [ ] 636GI	Lane A. Evans VA Community Based Outpatient Clinic
- [ ] 636GJ	Dubuque VA Clinic
- [ ] 636GN	Cedar Rapids VA Clinic
- [ ] 636GS	Ottumwa VA Clinic
- [ ] 636GT	Sterling VA Clinic
- [ ] 636GU	Decorah VA Clinic
- [ ] 636GW	Coralville VA Clinic

VA Minneapolis health care
- [ ] 618	Minneapolis VA Medical Center
- [ ] 618BY	Twin Ports VA Clinic
- [ ] 618GA	St. James VA Clinic
- [ ] 618GB	Hibbing VA Clinic
- [ ] 618GD	Maplewood VA Clinic
- [ ] 618GE	Chippewa Valley VA Clinic
- [ ] 618GG	Rochester VA Clinic
- [ ] 618GH	Hayward VA Clinic
- [ ] 618GI	Northwest Metro VA Clinic
- [ ] 618GJ	Shakopee VA Clinic
- [ ] 618GK	Albert Lea VA Clinic
- [ ] 618GM	Rice Lake VA Clinic
- [ ] 618GN	Lyle C. Pearson Community Based Outpatient Clinic
- [ ] 618QB	Ely VA Clinic

VA Nebraska-Western Iowa health care
- [ ] 636	Omaha VA Medical Center
- [ ] 636A4	Grand Island VA Medical Center
- [ ] 636A5	Lincoln VA Clinic
- [ ] 636GA	Norfolk VA Clinic
- [ ] 636GB	North Platte VA Clinic
- [ ] 636GL	Bellevue VA Clinic
- [ ] 636GP	Shenandoah VA Clinic
- [ ] 636GQ	Holdrege VA Clinic
- [ ] 636GV	O'Neill VA Clinic

VA Sioux Falls health care
- [ ] 438	Royal C. Johnson Veterans' Memorial Hospital
- [ ] 438GA	Spirit Lake VA Clinic
- [ ] 438GC	Sioux City VA Clinic
- [ ] 438GD	Aberdeen VA Clinic
- [ ] 438GE	Wagner VA Clinic
- [ ] 438GF	Watertown VA Clinic

VA St Cloud health care
- [ ] 656	St. Cloud VA Medical Center
- [ ] 656GA	Brainerd VA Clinic
- [ ] 656GB	Montevideo VA Clinic
- [ ] 656GC	Max J. Beilke VA Outpatient Clinic
