### ISSUE TITLE
Extend TypeAhead to All Users

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19368]
## Description 

During typeahead POC 5% of all VA.gov users were presented with typeahead suggestions. This issue is meant to extend the experience to all VA.gov users.

Update: As a result of the rate limits we have encountered when pinging the Search.gov endpoint we have decided to switch to a phased roll out as per our [release plan.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/typeahead/release%20plan.md
)  As a result roll out consists of #24839 and #19368

## Tasks
- [x] Ensure all dependencies have been cleared
- [x] After dependencies have been resolved change toggle feature flag to allow 100% of users to see/use typeahead
- [x] On Wednesday, May 19, 2021 - Increase to 80%
- [x] On Thursday, May 20, 2021 - Increase to 100%
- [x] Monitor the rates at which we are hitting the search.gov API. If there is ANY concern that we are reaching the overage rates we will decide if rolling back to 80% is needed or if Search.gov needs to further increases our rate limits.

## Definition of Done

- [x] All VA.gov users are presented with typeahead suggestions

**Comment by denisecoveyduc** [comment]
As a result of Search.gov typeahead suggestion database purge we have decided to re-run a POC (#21316) after we have established a list of typeahead suggestions and implemented some data fixes. That means typeahead 1.0 has been pushed back until we are comfortable that the feature is offering value to users. Moving this issue back to backlog until then.

**Comment by denisecoveyduc** [comment]
We have decided to do a phased roll out, as a result #24839 was created and this issue will be bumped to the next Sprint (Sprint 48) for completion.

**Comment by denisecoveyduc** [comment]
Following our [release plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/typeahead/release%20plan.md)typeahead was released via a phased roll out and was live to 100% of all VA.gov users on May 20th, 2020.
