### ISSUE TITLE
Order Suggestions based on character length

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19369]
## Description

To improve the user experience,  type ahead suggestions should appear based on the length of the suggestions characters

## Tasks

- [ ] sort typeahead suggestions by string length before displaying them.

## Definition of Done

- [ ] Direct matches should appear at the top of the suggestions list as a result
- [ ] Suggestions should appear in ascending order of character length

**Comment by srsuddath** [comment]
PR has been closed and waiting on build to prod
