### ISSUE TITLE
Add two numbers to birth defects rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19376]
## Issue Description
Per stakeholder Catherine Dolan, we are missing two numbers on the [birth defects rates page](https://www.va.gov/disability/compensation-rates/birth-defect-rates/). The following rates should be added:

Spina bifida Level III $1,979
Birth defects Level IV $1,979

## Tasks
- [ ] Add numbers to birth defects page
- [ ] Review and publish
- [ ] Alert stakeholder that change will be live

## Acceptance Criteria
- [ ] New numbers are showing on live site

**Comment by RLHecht** [comment]
These numbers are actually in the Drupal node but missing on production. I opened a ticket with the CMS team to report it as a bug.

**Comment by RLHecht** [comment]
This is a FE bug and is now being worked on in ticket #15910. Closing this and will email stakeholders when table is fixed. FYSA @bethpottsVADEPO
