### ISSUE TITLE
COVID-19 vaccine KMI shift + email #4 content check

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#19377]
## User story

As a Veteran or caregiver, I need to understand how to get a COVID-19 vaccine at VA and how VA is using my information when I sign up for the stay informed tool.

## Issue description

We've made content updates to the stay informed tool (landing page, form, confirmation page, confirmation email). We're also sending out segmented emails to people who've already signed up to explain a shift in how VA is using their information.

We need to check the PR and formatted emails against the Word docs to make sure all content updates were made accurately.

### Form 
- **PR for form flow:** https://github.com/department-of-veterans-affairs/vets-website/pull/15881
- Word doc for form flow: [KMI_page_shift to sign up_v6a_02.01.21](https://app.zenhub.com/files/133843125/5b315cb0-a0a0-404a-838f-d36b55873a66/download)

**Note:** Please note any needed changes directly in the PR.

### Emails
- **Note:** I will forward the emails to you now.
- See confirmation email content in Word doc above.
- Word docs for emails (2 variations of email newsletter): 
[KMI_email #4_v5a (plan to get a vaccine)_02.1.21](https://app.zenhub.com/files/133843125/c7221c00-cd1c-468e-bd3d-3134d9d5cbb4/download)
[KMI_email #4_v6c (other plan answers)_02.1.21](https://app.zenhub.com/files/133843125/f9833d65-7e27-4f3a-98f1-75a8b7e96010/download)
---
## Tasks
- [x] Check all content against Word docs

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here are my email comments:

 For the Other Plan email:
- The link to the COVID CDC risk criteria is not showing in the email.
- The dynamic text is coming through as "template 2"
- A period is missing from the last sentence in the first paragraph of the footer "...you can sign up to receive future updates"

For the confirmation email:
- Should we link to the Program of Comprehensive Assistance for Family Caregivers in the "Note to caregivers" section like we do on the other email?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @RLHecht!

- Thank you for noting link - I will pass along to team.
- We just asked for individual emails for that. Forwarding those to you now.
- Thank you for noting footer - I will pass along to team.
- We actually want to **remove** the link to the caregiver program in the other email. I'll note that!

**Comment by RLHecht** [comment]
This work was all completed. Closing ticket.
