### ISSUE TITLE
Read Diaries Service

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#19378]
## Background
We need to make use of the new BGS Diaries service. The service returns all diaries given a `pariticpant_id`.

## Task

- [x] Get Gem PR merged
- [x] Add service that leverages new gem code

## Acceptance Criteria
- [x] A PR has been submitted and requested for mergin'

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5829
