### ISSUE TITLE
Staging Review [VAMC- Eastern-oklahoma-health-care]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19375]
## Steps to complete Staging Review: 
**VAMC-upgrade product iterations do not require all areas of collaboration staging review**
- [x] design (Not applicable, No Design changes since Pittsburgh build)
- [ ] Accessibility - requested to be complete while in dual-state
- [x] Content - Required 
- QA (Not applicable, no changes to product since Pittsburgh build) 
- product - (Not applicable)
- [ ] analytics (Request to duplicate same as Pittsburgh build, while in Dual-state) 
- engineering - (Not applicable)
- information architecture - (Not applicable, No IA changes from Pittsburgh build)

- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team
- [ ] VFS: Completes attached feedback tickets based on acceptance criteria in each practice area feedback ticket
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)
- Link to release:  Not Applicable: [See VAMC Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Dual-State_RunBook_2020.1.21_Final.xlsx)

- Access information: Site can be seen in Tugboat [Here](https://web-ee8rfzidxqrextxhrymyuyl4at6qwfig.demo.cms.va.gov/eastern-oklahoma-health-care/)
- ~~Link to your product test cases/test plan in TestRail~~ - N/A 
- ~~Link to your [Coverage for References] reports in TestRail _for QA~~ - N/A
- Link to verification that accessibility checks are complete:  - 508 Accessibility checks complete in Dual State.
  
## Meeting attendees from **requesting team**
- Product Manager (required): **Stan Gardner**
- OCTO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **names**

## Scheduling

- [x] Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 4 business days from now
- [x] Please feel free to book anytime in Calendar open to discuss with Stan Gardner and David Conlon**

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: ~~design~~, accessibility, content, ~~QA~~, and optional: ~~product, analytics, engineering, information architecture~~

**Comment by SgardnerPMP** [comment]
Had to update Dev environment link.  Now can be found in Tugboat.  Here. https://web-ee8rfzidxqrextxhrymyuyl4at6qwfig.demo.cms.va.gov/eastern-oklahoma-health-care/

**Comment by SgardnerPMP** [comment]
Completed Foundational 508 Testing.  Document located in Repo here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/508_checks

**Comment by peggygannon** [comment]
Hi, @SgardnerPMP   I want to check in on which pages I should include in my content review. For previous VAMC reviews, I looked at the high-level pages where the content changed across VAMCs.  Is this how I should proceed with eastern Oklahoma review?  If so, can you share a list of those pages that I should focus on? Thx!

**Comment by shiragoodman** [comment]
Hey @SgardnerPMP  - just to reiterate what we communicated on Slack, our Staging Review feedback will be completed with 1 week turnaround. We will provide our feedback asynchronously by EOD on Thursday 3/4. Thanks!

**Comment by peggygannon** [comment]
@SgardnerPMP Hello! following up on our slack conversation, do you have a list of pages I should focus on for this review? Thx!

**Comment by 1Copenut** [comment]
@peggygannon I'm seeing pages in Staging at https://staging.va.gov/eastern-oklahoma-health-care/ . Going to run the accessibility audit from there.

**Comment by peggygannon** [comment]
Thanks, @1Copenut !

@SgardnerPMP do you have the list of Eastern OK pages you want me to focus on for content? If not, I'll just review all the pages.

**Comment by mnorthuis** [comment]
Hi, no formal IA review was part of this touchpoint, but just wanted to give you a heads up on a few things I spotted in case you weren't aware...

- Many patient advocate pages aren't linked to from the health services page - the text to "Learn more" is there, but it isn't linked. 
- The breadcrumbs on the [suicide prevention page](https://staging.va.gov/eastern-oklahoma-health-care/suicide-prevention/) and the [operating status page](https://www.va.gov/eastern-oklahoma-health-care/operating-status/) are missing the current page, and the previous page is not clickable.  
- The URLs of a couple of locations appear to have the names truncated.  The Jack C. Montgomery Department of Veterans Affairs Medical Center is missing "center" from the URL.  Looks like the same issue with the Ernest Childers outpatient clinic.  Given these are legal names, I didn't think we could truncate them. 
- The list of locations in the left nav does not match the order on the locations page - left nav is in alpha order, so the main location appears second in the list, this is different than other sites. 
- The About Us page has a different URL than other About Us pages.   This should be consistent.  Pittsburgh has just `/about`
- URLs for all pages nested under "About us" are incorrect, they should all have `/about` in the URL
- URLs for all pages nested under "Work with us" are incorrect, they should all have `/work-with-us` in the URL
