### ISSUE TITLE
Typeahead Styling Improvements

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19370]
## Description

Updating style of typeahead suggests to better align with best practices as appropriate based on search.gov restrictions. 

## Tasks

- [x] Change 'suggested characters' to be the bolded portion of the suggestion
- [x] Align typed search term in input bar with drop down suggestions
- [ ] communicate/request that other type ahead experiences do change the bolded terms as well to align with global search

## Definition of Done

- [x] Style now matches the below guide:

![va-gov-typeahead-benefits](https://user-images.githubusercontent.com/5553542/106320556-0880ff00-6241-11eb-9e5c-56edf3e6828a.png)
