### ISSUE TITLE
Usability Testing Prep [Authenticated Experience - MyVA 2.0]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19389]
## Steps to complete Usability Testing Prep: 
- [x] VFS Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance included in each practice area feedback ticket 
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [x] [MyVA product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign) 
- [x]  [Prototypes/mockups](https://vsateams.invisionapp.com/share/XNZWCYAYD45#/444040702_My_VA_Mobile
)
- [x]  [MyVA research plan] (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-research-plan.md)
- [x] [MyVA conversation guide] (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products[…]/2.0-redesign/product/Research%20V2/MyVA2-conversation-guide.md)

- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_

- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from **Authenticated Experience**
- DEPO product lead (required): **Samara Strauss**
- Product Manager (required): **Matt Shea**
- UX Designer: **Tressa Furner**
- UX Designer: **Cassandra Allen**
- Frontend engineer: **Erik Hansen**
- Frontend engineer: **Sandra Hallie**
- Backend engineer: **Lihan Li**
- Accessibility/design: **Josh Kim**
- Content: **Peggy Gannon**
- IA: **Mikki Northuis**
- QA: **Tze Lei**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)

Time selected: **2:00PM ET on Feb 12th, 2021**

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by mshea0606** [comment]
@shiragoodman I'll add in the research plan, convo guide, and clickable prototype later this sprint once they are complete.

**Comment by shiragoodman** [comment]
hey @mshea0606 - I'm not seeing any artifacts attached to this ticket and we're almost 48 hours out. Can you please provide ASAP so my team is able to review?

**Comment by mshea0606** [comment]
Hey @shiragoodman research plan and conversation guide have been added above. @callen2563 is adding the prototypes today.

**Comment by mshea0606** [comment]
all artifacts are now in

**Comment by peggygannon** [comment]
hi, @callen2563 It look like the mockup linked above has just 1 screen.  Is this correct? I know there are several views for the My VA dashboard.

**Comment by tressaellen** [comment]
Hi all - I just wanted to let you know that we're making some small updates to these artifacts and wanted to outline them here so you aren't surprised. 

**Prototype**

- @peggygannon we will not be testing the FTUX or empty states for this page at this time, so we will only be showing the 'user who has everything page' for now. 
- We will be updating all the links to screenshots of the tool pages instead of real links. Since a user has to be logged in to view any of these tool pages we won't be able to use live links in the prototype.
- We are in the process of adding a homepage to the test as well to test navigation from an unauthenticated start - we are figuring out if this should be the live site and then switching to the prototype OR just starting in the prototype and going from there.

**Conversation Guide**
- Please note - we are planning on asking participants what their top tasks on a dashboard would be, and those will dictate the tasks that we ask them. And then we will fill in whatever tasks/topics we didn't cover.
- We just added a few questions there, but nothing major has changed since yesterday so we should be good to go there.

**Comment by allison0034** [comment]
@tressaellen I will have design feedback by EOD. I was out sick Thursday/Friday.
