### ISSUE TITLE
Gather design/accessibility/content feedback for Dependency Verification concept

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#19388]
## Background
Dependency Verification is a feature currently in design. The feature is intended to drive Veterans to a page where they can confirm and/or change the status of dependents on their award. As initially conceived, this page would be a dedicated "Confirm Dependents" landing page that would lead to a confirm/change function. 

Because there is an existing screen in staging for viewing dependents, that page must be considered within the overall ad/change/remove/view dependents flow.

A proposed first step in implementing a Dependency Verification feature is to route the flow directly to the View Dependents page. From there a user can change (remove) a dependent, or connect to the 21-686c to add dependents.

Accessibility concerns (modal, etc.) and language (confirmation, consequences, etc.) must be considered.

## Goals
- Determine and discuss potential accessibility issues
- Identify content changes needed to address DV flow
- Review design choices and determine best patterns/elements

## Tasks
- [x] Post DV flow/screen concepts in Slack for review
- [x] Discuss accessibility issues with Josh
- [x] Discuss research finding with Kevin H.
- [x] Discuss design issues with Ryan T.
- [x] Determine next steps and way forward (e.g. Collaboration Cycle) 

## Acceptance Criteria
- [x] Feedback documented
- [x] Next steps determined

**Next steps**
- Update states for spouse, parent, and dependent removal
- Request (2nd) Design Intent Review for either/ both Modal and View Dependents iteration

**Comment by sporeboy** [comment]
Dependency Verification user flow and screen design posted in Slack for review: https://dsva.slack.com/archives/CLY6Q69RV/p1612193531061700

**Comment by sporeboy** [comment]
Had quick call with Josh re: accessibility. Notes are placed in XD doc. Takeaways fro meeting:
- Provide context--give reason for 'hijacking' screen
- Revise content for screen readers
- Address cognitive issues with modal buttons; consider framing a choice (radio buttons?)
- Modals are OK provided keyboarding is contained within modal itself (tab-trapping)
- Consider how modal would "announce" (alert, aria-live, auto-focus, etc.) within user flow

**Comment by sporeboy** [comment]
Design considerations include:
- Modal styling--alert modal or plan?
- Jump links on View Dependents screen should be connected to H2 or greater 

Content revisions will also be needed to address confirmation scenarios.

**Comment by sporeboy** [comment]
Had a quick call with Kevin H. re: research findings. Takeaways from meeting:
- Research conducted with Veterans, VSOs and stakeholders
- Paul Shute was a POC
- Modal presented was just to direct users to review dependents, not a list
- Modal was considered at sign-in for content views; modal presented at end of tasks so as to not interrupt
- Many Veterans preferred direct language for potentially traumatic questions (death, divorce), some wanted softer approach (must test)
- Divorce was a high-stress scenario; Veterans motivated to act quickly
- Non-biological stepchildren and less-traditional marriages were problematic edge cases
- Consider not presenting dependents "not on award;" may be confusing
- Not sure if Dependency verification is a high priority--is very important in light of debt issues
