### ISSUE TITLE
Add life insurance R&S articles to left nav and LI hub landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19391]
## Issue Description
Now that we've added life insurance pages to Resources and Support, we need to link to some of these articles from the Life Insurance left nav and hub landing page.

Under the More resources and support spoke on LI hub, change:

How much life insurance do I need? to [Deciding how much life insurance to get](https://www.va.gov/resources/deciding-how-much-life-insurance-to-get/)

Medical conditions that make you uninsurable to [Life insurance if you have pre-existing conditions](https://www.va.gov/resources/life-insurance-if-you-have-preexisting-conditions/)

Here is the new teaser text:
**Deciding how much life insurance to get**
Use our life insurance needs calculator to help decide how much life insurance you need.

**Life insurance if you have preexisting conditions**
You have 4 options to get life insurance as you transition out of service, but they have time limits. Learn about your options if you have preexisting conditions.

These need to be updated in the left nav as well. 

## Tasks
- [x] Change headers and links on hub landing page
- [x] Add R&S links to left nav
- [x] Review and publish

## Acceptance Criteria
- [x] Updated content on live site

**Comment by RLHecht** [comment]
These changes have all been made. Moving to validate and will close when live on the site. @mnorthuis One question we had about setting up the redirects: We currently link to [this landing page](https://www.benefits.va.gov/insurance/lifeins101.asp) to get to the calculator and the questionnaire. Should that page be redirected too? FYSA @bethpottsVADEPO @lunascoop you can open up a ticket to start the redirects for this.

**Comment by RLHecht** [comment]
These changes are live. FYSA @bethpottsVADEPO @mnorthuis Closing ticket. Redirect work will be set up in new ticket. @lunascoop
