### ISSUE TITLE
Capture metrics for current Github Practice area guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#19403]
## Issue Description
In order to measure success of the Collaboration Cycle - Update Guidance/Documentation initiative, we need to understand where we currently are with our documentation on Github. Capturing these initial data points will allow us to identify appropriate KPI for the initiative release.

## Possible metrics to capture

- Number of files (Between all practice areas and Collab Cycle): 169
- Number of files by practice areas
   - Design: 47
   - IA: 16
   - Content: 14
   - QA: 31
   - Accessibility: 29
   - Product: 20
   - VSP: 12
- % of references to Collab Cycle (0-4) 
   - 0: (127 files) 75%
   - 1: (9 files) 5%
   - 2: (4 file) 2%
   - 3: (13 files) 8%
   - 4: (15 files) 10%

---
## Tasks
- [x] Capture initial baseline metrics and log within this ticket

## Acceptance Criteria
- [ ] VSP Product Support has baseline metrics and is able to establish KPIs for measuring success

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034 can you think of anything else valuable we should be capturing? If not, this can be closed.

**Comment by allison0034** [comment]
@shiragoodman nope!
