### ISSUE TITLE
[Design] DD4edu - 508 checks required pre-staging review

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19409]
## Background
There are some 508 checks/scans needed prior to the Staging Review for DD4edu.

[Staging review 508 scans/checks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md)

## Tasks
- [x] Color tests for proper contrast and colorblindness - read more about contrast and colorblindness
- [x]  Content zoomed to 200%, 300%, 400% - read more about zoomed layouts
- [x] Keyboard navigation - read more about navigating with the keyboard

**Comment by sporeboy** [comment]
Cursory 508 checks complete.

Color contrast
- All color combos pass WCAG AA and AAA tests
- Lowest contrast elements are 10.02:1 (text on light blue)
- No instance of color as sole indicator of status (green success message has text)
- Page legible in grayscale, B/W and inverted color

Screen zoom
- Zoom to 200%, 300% and 400% supported
- Screens respond to "mobile" view
- Issue at 400%: 'sticky' navigation (Your profile menu) obscures DD box headers, creating some confusion

Keyboard navigation
- All elements navigable via keyboard, including:
- Nav to page
- Entering DD forms
- Completing forms
- Submitting or canceling 
- All nav links
- All phone links
