### ISSUE TITLE
Update broken link on Mental Health page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19405]
## Issue Description
We currently have a broken link in the alert on our [mental health page](https://www.va.gov/health-care/health-needs-conditions/mental-health/). 

Current link: https://www.whitehouse.gov/presidential-actions/presidential-executive-order-supporting-veterans-transition-uniformed-service-civilian-life/
Suggested new link: https://www.mentalhealth.va.gov/transitioning-service/docs/FINAL_EO_Fact_Sheet_508.pdf

Danielle first needs to review this to determine if this is the correct link to replace it with. Then, Randi can update the page.

## Tasks
- [x] Review new suggested link and determine if it should replace broken one (Danielle)
- [ ] Add new link (Randi)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Broken link no longer showing on live page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I created this ticket so this didn't get lost in Slack.

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Update. Remove link for now. Thank you!

**Comment by RLHecht** [comment]
When making this change I learned there was a second broken link on the page. Going to remove text for now and will check back next week if the site is back up and running to add the text back in. Here it is so we don't lose it:

[The Psychological Health Resource Center](https://pdhealth.mil/)
The center works to improve the lives of Veterans, service members, and their families by advancing excellence in psychological health care, readiness, and prevention.

**Comment by RLHecht** [comment]
This page is now published. Moving to validate and will close after today's deploy.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
