### ISSUE TITLE
Test User Accounts_Usability Testing_week1

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#19419]
## Issue Description
Usability testing February 2- February 14

## Tasks
- [x] Recruit participants
- [x] Schedule tests
- [x] Use guide to receive feedback about functionality of prototype
- [x] Synthesize notes from test to share with team
- [x] Prep for next phase of testing

## Acceptance Criteria
- Conduct testing with participants on the following dates:
- [x] Th 2/4     2:30pm ET
- [x] Th 2/4     4:30pm ET
- [x] Fri 2/5     11:00am ET
- [x] Fri 2/5     2pm ET
- [x] Mon 2/8  2pm ET
- [x] Mon 2/8  3pmET
