### ISSUE TITLE
Use PaymentHistory endpoint to pull in veteran C&P and EDU payments to display in 5655 form

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#19411]
## Issue Description
5655 in progress form currently only shows the composite monetary award amount for the veteran. This is not sufficient data for the current design which requires displaying both Compensation & pension payments along with educational payments, both net and gross amounts.

The net amounts will be easy to show, at the time of the creation of the ticket I am unsure of whether I can easily gather the gross amount from this service - I may have to look elsewhere to retrieve this data.

---
## Tasks
- [ ] Integrate with paymentshistory service to pull in the data mentioned above to the 5655 form.

## Acceptance Criteria
- [ ] C&P, EDU payments information is displayed to the veteran within the 5655 form.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
