### ISSUE TITLE
Test User Accounts_ Usability Test Schedule

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#19417]
## Issue Description
Schedule for usability testing for prototype 

---
## Tasks

- [x] Set tentative meeting schedule of 45-60 minutes
- [x] Recruit participants for testing
- [x] Meet with participants weekly to test functionality of prototype
- [x] One other identity team member to observe and take notes for usability schedule
- [x] Schedule 10-15 mins sync after session to go over notes collect
- [x] Synthesize findings from testing to share with FE

**Comment by APorter-Clarity** [comment]
Tentative schedule:
- Monday: 11am-5pm Est
- Thursday: 1pm-5pm Est
- Friday: 1pm-4pm Est
