### ISSUE TITLE
TUD: Logging & monitoring on the Front-end

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19418]
## Issue Description
The Test User Dashboard front-end web application will need logging and monitoring for security, bugs, errors, etc.

---
## Tasks
- [ ] Investigate and research possible logging & monitoring libraries for the TUD front-end
- [ ] Integrate logging & monitoring libraries for the TUD front-end
- [ ] Add documentation about the types of logging/monitoring events that are done.

## Acceptance Criteria
- [ ] I see a list of both log & monitor events that happen inside the TUD front-end
- [ ] I see documentation for event types

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
