### ISSUE TITLE
[Cheetah MVP] Add Screener pages and paths

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19412]
## Issue Description
Add screener page with yes/no conditions to determine scheduling path.

---

## Tasks

- [ ] Add screener page

- [ ] Add not eligible page

## Acceptance Criteria
- [ ] All changes are behind va_online_scheduling_cheetah feature flag

- [ ] When user selects flow CTA from homepage, Then load screener page

- [ ] Given user selects no, When user clicks Continue, Then continue to regular scheduling flow (going to Facility page next)

- [ ] Given user selects yes, When user clicks Continue, Then load not eligible/contact a facility page

- [ ] Given not eligible page, When user is registered at a facility, Then display facility in flat list AND do not allow facility selection

- [ ] Given not eligible page, When user clicks "Search for more facilities.", Then open Facility Locator page in a new tab

- [ ] DESIGN - Screener page specs match designs https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/Jnnk1mk#Inspector
![Screen Shot 2021-02-03 at 11.33.43 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/c1814901-b04c-47a7-a4e8-bb540e515141)

- [ ] CONTENT - Screener page header and body copy matches designs

- [ ] ANALYTICS - When user clicks Continue, event fires indicating yes/no selection

- [ ] DESIGN - Not eligible page specs match designs https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/R11w5EW#Inspector
![Screen Shot 2021-02-03 at 11.33.33 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/80dbe4cf-d69a-434b-860b-b85ba9cde80c)

- [ ] CONTENT - Not eligible page header and body copy matches designs

**Comment by jbalboni** [comment]
@laurenernest @outerpress Did we want to limit the facilities shown on this page to 2 (or 5 without a residential address) like we do in the facilities not shown dropdown?

**Comment by laurenernest** [comment]
@jbalboni Yep, go with the 2/5 limits.
