### ISSUE TITLE
Usability Testing Prep [Facilities, Facility Locator: Mobile first]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19413]
## Steps to complete Usability Testing Prep: 
- [x] VFS Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance included in each practice area feedback ticket 
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [x] Link to [product outline- WIP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/map-enhancements/usability%20and-accessibility-product-brief.md)
- [x] Link to [prototype](https://preview.uxpin.com/c60117d778b6116d11f6fc707a5ac6d953d91aa0#/pages/136040014?mode=chidfm) (best viewed on mobile)
- [ ] ~Link to or attach artifact with copy (if separate from prototypes/mockups)~
- [x] Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/mobile-experience)
- [x] [Link to regression test plan](https://dsvavsp.testrail.io/index.php?/runs/view/1018&group_by=cases:section_id&group_order=asc&group_id=35) R1018 Staging review for Map enhancement initiative can be used as a solid set of regression tests for this initiative (plus the new test cases listed below)
- [x] Link to [test cases/test plan- WIP](https://dsvavsp.testrail.io/index.php?/suites/view/7&group_by=cases:section_id&group_id=897&group_order=asc) in TestRail 
       - C4241 | Clear input field 
       - C4242 | "Use my location"  
       - C4243 | Search this area accessibility testing

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Leyda Hughes**
- Other specialists: **Laurel Lawrence**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira will reach out as needed_

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by mmiddaugh** [comment]
@shiragoodman we're requesting Thursday, February 11 at 1:30 or 2 PM ET

**Comment by allison0034** [comment]
No design feedback. Looks good!

**Comment by peggygannon** [comment]
Only content feedback is to use sentence case for the View tabs

View list 
View map

**Comment by mnorthuis** [comment]
No IA feedback. Thanks!

**Comment by pjhill** [comment]
We have no detailed feedback regarding QA --
Thanks for stubbing out functional test cases and identifying relevant regression tests to accompany your iteration!

**Comment by shiragoodman** [comment]
hey @mmiddaugh  - just wanted to follow up and let you know that this initiative is being tracked under the New tab of the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886).

**Comment by mmiddaugh** [comment]
Feedback has been added to [Mobile design issue ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20254)
