### ISSUE TITLE
[VAMC] Double check Facility Health Service move to Hardened fields for all VA Pittsburgh Healthcare System facilities [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19425]
## TASK
**Review ALL facility health service by Facility to assure that data/content was transferred correctly to include the following sites:
- [x] Pittsburgh VA Medical Center-University Drive 
- [x] Beaver County VA Clinic 
- [x] Belmont County VA Clinic 
-
- [x] H. John Heinz III Department of Veterans Affairs Medical Center 
- [x] Washington County VA Clinic 
- [x] Westmoreland County VA Clinic
&
- [x] Fayette County VA Clinic 

## Acceptance Criteria
- [x] All Facility Services are checked
- [x] Any small mistakes are corrected.
- [x] If there appears to be any **Show Stopper** item, list what is found with screenshot in vsa-vamc-upgrade channel and explain.

**Comment by ltrombley** [comment]
Task #19425 -Double check Facility Health Service move to Hardened fields for all VA Pittsburgh Healthcare System facilities - is Complete and moved to Validate
