### ISSUE TITLE
10-10CG - Improve Facility Selection

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#19433]
## Product Outline
[Improve Facility Selection on 10-10CG outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)

## High Level User Story/ies
As a Veteran, I need to select the most relevant VA Medical Facility so I can participate in the PCAFC.

## Hypothesis or Bet
**If** _we improve the facility selection page_ **then** _Veterans will be more confident selecting a facility and applications will need to be rerouted less_.

## OKR
- reduce the number of incorrectly routed applications

### What must be true in order for you to consider this epic complete?

- Facility page changes are available in Production. The Veteran can select their preferred facility and it will be matched up with the associated Caregiver facility (if different).

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

<details>

<Summary>Expand to view Task list, similar to Sub-issues below</Summary>

```[tasklist]
### Tasks
- [ ] Designs
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/55327
- [x] Development
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70846
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90381
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70847
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92297
- [ ] QA
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91947
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91948
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91949
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91953
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91950
- [ ] Staging review
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91951
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91952
- [x] Usability/Research sessions
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91231
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/47976
- [ ] Launch Prep
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92022
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92023
- [ ] Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92034
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92036
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92037
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92038
- [ ] Post-Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92042
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/26248
```
</details>

**Comment by kevinmirc** [comment]
At the end of the day, the user is really just choosing what facility to route their application to, so why not just explicitly ask them to chose that. It may lead to less confusion about the purpose of the question and make it easier for people who know about the program or go to an out-of-state facility (which is what we see a lot in research).

> **Please choose a facility to process your application**
> Only some VA medical facilities provide a Caregiver Support Coordinator to process your application and be a point of contact for family-caregiving-related support and benefits.

**Comment by tchrisdyer** [comment]
Information from Dat about using the facility API and getting mapbox coordinates is located in ticket #27375
