### ISSUE TITLE
Staging Review [VAOS - Community Care Provider Selection]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19430]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [x] VFS: Completes attached feedback tickets based on acceptance criteria in each practice area feedback ticket
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1zoQG_4Ndp5SSLnc3UBQxWa7xtfnnUy_2LP9MxwbUWpI/edit#gid=266151061) is updated

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/cc-provider-selection-initiative.md)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/cc-provider-selection-release-plan.md)
- Access information for the tool or feature in staging: [Judy](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md)
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
  - **_We won't have this_**
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
  - **_We won't have this_**
- Link to verification that accessibility checks are complete: #18708 
- List of known issues: [PR#15872](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/15872)

### Steps to get to updates
1. Go to https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Sign in with user cred above
3. Click Schedule an appointment button
4. Select Primary care
5. Select Community care facility
6. Select a date and AM/PM preference

## Meeting attendees from **requesting team**
- Product Manager (required): **Lauren Ernest**
- DEPO product lead (required): **Lauren Alexanderson**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Peter Russo, Jeff Balboni, Kam Karshenas**
- Other specialists: **Peggy Gannon, Trevor Pierce, Joanne Esteban**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- 2/15 3:30-4pm ET

If you have earlier availability, that would be great! Here are some additional options:
- 2/10 3-5pm ET
- 2/11 1130-12, 130-2 ET
- 2/12 1130-12, 130-2, 230-3 ET

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by shiragoodman** [comment]
hey @laurenernest  - we can do 2/11 at 1:30 ET. I'll schedule now

**Comment by allison0034** [comment]
@laurenernest , I am getting an error when trying to open the product outline. Can you please check to make sure it is linked correctly?
This page isn’t workingIf the problem continues, contact the site owner.
HTTP ERROR 406

**Comment by laurenernest** [comment]
@allison0034 Updated :)

**Comment by allison0034** [comment]
@laurenernest thank you! Do you have a link or can you tell how to get to the provider selection?

**Comment by laurenernest** [comment]
@allison0034 Added a "Steps to get to updates" section above to help walk through our flow to get the page with the updates for this initiative

**Comment by allison0034** [comment]
@laurenernest sorry if I am miss understanding, but wasnt the "copy and paste address" supposed to be going away and the user could select their provider while in the map locator? I am not seeing anything different. Or am I confusing what was supposed to change? : )
<img width="863" alt="Screen Shot 2021-02-09 at 10 58 55 AM" src="https://user-images.githubusercontent.com/72398073/107390775-0848f500-6ac6-11eb-863d-af4ca534c891.png">

**Comment by laurenernest** [comment]
@allison0034 your understanding is correct so I'm not sure how you got the old page. To confirm, you're using the Judy account, correct?

Feel free to drop time on my calendar if you want to walk through it together.

**Comment by peggygannon** [comment]
hi, @laurenernest and @allison0034 I don't get the map locator screen either. Here's the screen I see for selecting a provider

![2021-02-09](https://user-images.githubusercontent.com/17554224/107405683-6bce2500-6abc-11eb-8191-e07c49b88e82.png)

**Comment by allison0034** [comment]
@laurenernest sorry, I was using  the wrong person and you clearly have "Judy"

**Comment by laurenernest** [comment]
@peggygannon The location-based view is correct. I'll take a look at address-based list.

**Comment by laurenernest** [comment]
@peggygannon @allison0034 Of course there weren't any nearby locations for that home address :( I've updated Judy's home address and it should now return results when sorting by address.
![Screen Shot 2021-02-09 at 10 16 01 AM](https://user-images.githubusercontent.com/72046525/107408507-ee0c1880-6abf-11eb-9198-c8c553e630f6.jpg)

**Comment by pjhill** [comment]
@laurenernest -- It's my understanding that your QA efforts are planned and executed using tools outside the purview of VSP. Are there any artifacts from those QA efforts that we are able to review? Spreadsheets of test cases and test executions or collections of defects?

**Comment by laurenernest** [comment]
@pjhill Here's where they keep their documentation https://wiki.mobilehealth.va.gov/display/VAOSR/Regression+Test+Scripts

Any FE defects get written up in GH and if it's related to the initiative, I'll add them to the epic. They don't keep separate artifacts specific to initiatives.

For this initiative, they found #18893

**Comment by mnorthuis** [comment]
Hi, there were no changes to global IA elements with this work and therefore there's not IA feedback at this time.  Thank you!

**Comment by laurenernest** [comment]
@shiragoodman The collab point tracker link in the description is broken. Can you add the new link please? :)

**Comment by allison0034** [comment]
@laurenernest here is the new link. https://docs.google.com/spreadsheets/d/1zoQG_4Ndp5SSLnc3UBQxWa7xtfnnUy_2LP9MxwbUWpI/edit#gid=266151061

**Comment by laurenernest** [comment]
All issues have been resolved.
