### ISSUE TITLE
Plain language definitions to capture and terms to add to the style guide for February

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19437]
## Issue Description

This ticket is to keep track of any plain language rules and definitions that we need to correct or update on our pages and/or add to the style guide. We can open up a new ticket to implement the work of adding to the style guide. 

## Tasks
- [ ] Add plain language terms to address in style guide or revise on our pages

## Acceptance Criteria
- [ ] Ticket created for style guide additions and/or updating on our pages

**Comment by RLHecht** [comment]
Eliminating the use of "extend Post-9/11 GI Bill or Fry Scholarship benefits" when talking about the Edith Nourse Rogers STEM Scholarship

**Comment by laurwill** [comment]
More items to make consistent and add to guide:
- condition vs disability
- service-connected disability rating vs disability rating
- when to use "that" and when to skip it

**Comment by megzehn** [comment]
- how to style PACT on first mention within body copy

**Comment by bethpottsVADEPO** [comment]
Add to the word list: which is the preferred term for discharge papers / discharge document / separation document, etc. And we'll probably want to account for the parenthetical we've been using: "your discharge papers (DD214 or other separation documents)"

**Comment by RLHecht** [comment]
Multifactor authentication. We have another ticket for this work but adding it here too: #33051

**Comment by megzehn** [comment]
- Revise entry about en dash ([some context in this thread](https://dsva.slack.com/archives/C8E985R32/p1657561939162259))

**Comment by megzehn** [comment]
- "intent to file" capitalization rules

**Comment by megzehn** [comment]
Update: most of these were added in the latest style guide changes. 

But we still need to confirm the preferred choice for discharge papers / discharge document /  separation document

**Comment by megzehn** [comment]
During the next round of audit updates, we're going to check with Paul on this one:

which is the preferred term for discharge papers / discharge document / separation document, etc. And we'll probably want to account for the parenthetical we've been using: "your discharge papers (DD214 or other separation documents)"

**Comment by megzehn** [comment]
Look into preferred usage for mobile phone (or mobile device) vs smartphone vs cellphone

**Comment by megzehn** [comment]
(To discuss) Add guidance on symbols. When and why to avoid, and what the exceptions are.

**Comment by megzehn** [comment]
- a note about avoiding directional language (above, below, etc.) (First make sure we don't have it already.)

**Comment by megzehn** [comment]
- fractions (half vs 1/2, a third vs 1/3, etc.)

**Comment by megzehn** [comment]
- Add $ to dollar amounts in tables, per this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52594#issuecomment-1731422267

**Comment by megzehn** [comment]
- VA DIC vs DIC

**Comment by aliyahblackmore** [comment]
- [ ] Conditional statements (as a tip, not a rule)

**Comment by megzehn** [comment]
Hi @chelsealevinson, we got the green light to add these 4 entries in the style guide:

- condition vs. disability
- intent to file
- mobile phone
- smartphone

[The approved entries are in this Sharepoint doc](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/ERaKriuBC59MjgXzbkIfUQ4BnvPEWk9ibiykgZ2SMVkgmw). When you have a chance, could you add them to the word list?

**Comment by megzehn** [comment]
- [ ] CTA link text guidance: When to use certain verbs (Learn more, find out, review, go to etc.) and when we don't need to use a verb. What verbs not to use (jump, view, watch, hear, etc.)

**Comment by megzehn** [comment]
**Update:** We're moving away from documenting items in this ticket, and instead adding them to [this Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/content-patterns-and-standards), so we can add more notes and examples. 

This is ongoing work that we're making space for as much as we can!
