### ISSUE TITLE
TUD: Draft an Architectural Diagram

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19444]
## Issue Description
As part of the ongoing Test User Dashboard effort, an Architectural Diagram will help engineers to understand how the TUD app works.
---
## Tasks
- [ ] Create an architectural diagram of all EVENTS that can be done on the TUD app
- [x] Create an architectural diagram of how the TUD front-end & back-end are connected.

## Acceptance Criteria
- [ ] I have a handout of the architectural diagram of the events in the front-end
- [ ] I have a handout of the architectural diagram of the connection between front-end & backend.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
TODO:
- [ ] Get initial feedback, does it need more information? More details? Et cetera?[https://app.zenhub.com/files/133843125/fc41ade9-d5ec-4a21-b738-cff6dd75f770/download](https://app.zenhub.com/files/133843125/fc41ade9-d5ec-4a21-b738-cff6dd75f770/download)
