### ISSUE TITLE
Required Fields for View Dependents Formlet

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19449]
## Background
As the formlet gets...formed, we need to add the necessary fields that would need to be answered for a given dependent removal.  We know about the Veteran and now we will be able to pick up the info for the Veteran and to complete the payload for a submissable application, we need to fill in any blanks.

## Considerations
- This functionality is behind a feature toggle
- Think about any other fields that are going to be required but not shown
- There are two workflows under consideration here:
  - Removal of a spouse, for various reasons,
  - Removal of various types of children for various reasons
  - For the modal: [VA Form 21-0538 ](https://www.va.gov/find-forms/about-form-21-0538/) is the form for Dep Ver.
    - "If this is correct;" we send a 0538 on their behalf and update the entry
    - "If not, please remove them using the 686c/674"

## Tasks
- [x] Generate a list of required fields that need to be included in the formlet for each dependent type
- [x] Share that list with the FE 

## Acceptance Criteria
- [x] The extra required fields needed for successful removal are documented in a mockup (or in GH, if easier) and shared with FE

**Next Steps**
- Create a ticket for those fields to be implemented into the formlet by FE
- Discuss any impact with BE

**Comment by sporeboy** [comment]
Subject to verification by BE for valid submission requirements! @kathleencrawford @digitaldrk 

I'm basing this on our current workflows.

**For all:**
- Veteran's info
   - First name/Last name
   - Address/City/State/ZIP
   - SSN
   - DOB
   - VA file number
- Dependent's info
   - Relationship
   - First name/Last name
   - SSN
   - DOB

**Remove spouse:**
- Why
   - Divorce
   - Annulment
   - Void
   - Death
- When/MM/DD/YYYY
- Where/City/State

**Remove child:** 
- Why?
   - Stepchild left (See below)
   - Married
   - Stopped attending school
   - Death
- When/MM/DD/YYYY
- Where/City/State

**Remove stepchild leaving household:**
- When/MM/DD/YYYY
- How much do you pay for expenses? (I combined two questions here)
- Who does stepchild live with
   - First name/Last name
- Stepchild's new Address/City/State/ZIP

**Remove parent:**
- Why
   - Other (Is this an option?)
   - Death
- When/MM/DD/YYYY
- Where/City/State

**Comment by sporeboy** [comment]
Below is a link to the View Dependents V2 mockups. Please note:
- Mockups conform to Version 2 tool screen layout
- Some content has been revised to support Dependency Verification
- There are formlet variations per removal workflow
- There is a revised Dependency Verification modal
- Confirmation message based on DD-EDU/C&P formlet
- Layout includes only preliminary copy
- Layout does **not** include all states
- **Layout will need to run through full collab process**

https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/

**Comment by sporeboy** [comment]
The (most) minimal version of the functional dependents "card" can link straight to the 21-686c.

This version will require quite a bit of FE logic (and unique field IDs) to present all the states.
