### ISSUE TITLE
TUD: Authentication/Authorization on the Front-end

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19442]
## Issue Description
The Test User Dashboard front-end web application was originally going to locked down by the use of a SOCKS proxy.  After speaking to several stakeholders it was determined that we're moving away from authorization by the SOCKS proxy for new applications and tools.

### Update
> UPDATE 1:

We have decided to do Basic Authorization on the server/directory and will use .htaccess & .htpasswd files to login for now.  The second quarter initiative is to implement Github OAuth.  Two options that we can decide on is using **[Devise](https://github.com/heartcombo/devise)** (RoR implementation of Passport.js) to be implemented on the `test-user-dashboard` module on Rails or using **[OAuth 2 Proxy](https://oauth2-proxy.github.io/oauth2-proxy/)** that is a Proxy service that will sit between the TUD App.

> UPDATE 2:

Because of the way the AWS ECR repository is setup the Test User Dashboard is located behind the SOCKS proxy by default.  The API (`vets-api`) test user dashboard endpoint needed to be locked down from unauthorized usage.  A JWT is generated client-side and sent to the backend for verification.

---
## Tasks
- [x] Generate a JWT and public key client side

## Acceptance Criteria
Current
- [x] I receive data from vets-api

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
