### ISSUE TITLE
TUD: Integrate Vets-API with TUD front-end

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19448]
## Issue Description
The Test User Dashboard previously was using mock data to do the front-end implementation and design while the `test-account-dashboard` module in `vets-api` was being created.  Now that the `test-account-dashboard` module is merged into the `main` branch in `vets-api` we can begin remove the mock data.

---
## Tasks
- [x] Integrate the API with the front-end TUD application
- [x] Update any documentation for getting started with the API integration (seeding the database, API endpoints, etc)
- [x] Fix the birthdate to a common formatting that is easily readable by the user.

## Acceptance Criteria
- [x] I can see documentation on how to get started with the new API integration setup
- [x] I see REAL data from the API
- [x] I see the birthdate is in a readable format
- [x] Verify with TUD Backend Engineers (John & Jim)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
TODO:
- [ ] Verify with John & Jim to get setup.
