### ISSUE TITLE
Enhance Best Bets to include keyword variations for top form searches.  

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19443]
## Description
Through user research and data discovery we have discovered a discrepancy in the way veterans are searching for forms. Adding a dash, altering the location of spacing, using the terms va forms etc will greatly impact the quality of the search results that are being presented back to veterans. As a result, the search and discovery team would like to update the keywords associated with the best bests for forms to ensure that the various search methods all showcase the same results. 

## Tasks

- [x] Review 2020 query list to identify the various search terms related to forms
- [x] Summarize the various search terms for each form to highlight the variations we have seen veterans use
- [x] Identify top 20 forms in alignment with the decisions tools team. 
- [x] Update keywords for best bets to include variations. 

## Definition of Done
- [x] Best Bet keywords have been updated to include various and improve the result set.

**Comment by denisecoveyduc** [comment]
@johnhashva I have reviewed the top queries form 2020 and grouped them by form to get a better picture of the various ways users are searching for a given form (Column F). Using the criteria outlined on the spreadsheet (row2) I then (in Column E) created a list of keywords for us (you ☺️) to add to best bets. @srsuddath  and @mgleo  have reviewed this list as well to double check. I would recommend we start with the top forms in row 5-45). Happy to discuss once you have had a chance to review. [Form Search Variations Spreadsheet](https://docs.google.com/spreadsheets/d/1tRyfY8K_hpFVIWI9C9k7lSOE9_WrE5Ir6DAY5L9VP10/edit#gid=1889918370)

**Comment by johnhashva** [comment]
Excited to see this @denisecoveyduc .   Will take a look as my first task in the AM.  TY.

**Comment by denisecoveyduc** [comment]
Two outstanding questions/tasks 

1} Do we want to include the green highlighted terms from column F (on the [Form Search Variations Spreadsheet](https://docs.google.com/spreadsheets/d/1tRyfY8K_hpFVIWI9C9k7lSOE9_WrE5Ir6DAY5L9VP10/edit#gid=1889918370))  as a keyword for that best bet? I am not convinced either way but question if searching for 4138 should always generate 21-4138 as a best bet. (another example searching for 1995- should that populate the best bet for 22-1995?) If you feel that the handful of terms highlighted in green should be included as keywords, then they should be added as you go through. 

2} Rows 76-88 Highlighted searches from 2020 that don’t obviously connect with an existing best bet. More exploration needed.

**Comment by denisecoveyduc** [comment]
@johnhashva has made good progress on this time consuming task of adding keywords to the best bets. He is over half way through the list and expects to be completed during Sprint 42 (Feb 24-Mar9). Rolling issue over to allow for more time.
