### ISSUE TITLE
Test Lighthouse API for Representatives

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19450]
## Background
As we move to start getting the POA work in place, we have been given access to the Lighthouse API (LH API) to start testing with.  We need to ensure that our connection to that is working as expected and that we can move data as we need to with that system.

## Considerations
- Do we need to consider mock data?
- Pair with FE, as needed
- We are making claim calls but we need to see the vet’s representative.
1. Is that in the claims call?
2. Do we need to make another call based on what we got back from the claim call?
- https://developer.va.gov/explore/benefits/docs/claims?version=current
- FE: needs a certain set of values from `/forms/2122/active` from the claims url (above) 
- Potential users: https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts.md#representative
- Relevant convo with Mark Greenburg: https://dsva.slack.com/archives/CLY6Q69RV/p1615311614044200

## Tasks
- [x] Call the service and confirm connection 
- [x] Call the service and request rep data back from it for a particular Veteran

##  Acceptance Criteria
- [x] A test Veteran can see who is set as their representative
- [x] There is a path forward for  the FE to start implementing data

**Next steps**  
1. If needed, talk to Charley about a user, maybe he knows of one that has data.  
1. Figure out how to make Lighthouse calls. Seems like there's a way to make this call already in `vets-api`  
1. Write up ticket(s) for view rep once LH calls are working

**Comment by digitaldrk** [comment]
Working with Charley. I made the request to `/forms/2122/active` and I'm getting a 500 back. He sees the error in Sentry and is looking into it. I am in a group DM with him and his team.
