### ISSUE TITLE
Pact Transition Work

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#19457]
## Description
Transition Pact ownership from FE tools to Testing Tools Team.

## Tasks
- [x] Assign SMEs on TTT
- [x] TTT SMEs review available [Pact documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/testing/contract-testing) prior to ownership transfer meeting
- [x] Schedule meeting between FE Tools SMEs and TTT SMEs

**Comment by pjhill** [comment]
- [ ] @rjohnson2011 has reviewed the available Pact documentation and is ready to meet with FE Tools
- [ ] @holdenhinkle has reviewed the available Pact documentation and is ready to meet with FE Tools

**Comment by holdenhinkle** [comment]
This ticket is complete.

**Comment by pjhill** [comment]
Confirmed
