### ISSUE TITLE
Adjust File Upload Language

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19452]
## Background
An opportunity to better perfect the language around the file uploader has arisen and should be implemented.

### Currently:
_"You’ll need to provide a copy of your stepchild’s birth certificate, showing the names of both parents if you don’t live in the U.S. or a territory of the U.S._

### Should be changed to:
_To add a stepchild, you’ll need to provide a copy of their birth certificate, showing the names of both parents if:_

- _Your stepchild is not the biological child of your spouse (adopted, for example) or_
- _You don’t live in the U.S. or a territory of the U.S._

## Tasks
- [ ] Adjust the language for all file uploader components in the instructions, including the helper text dropdown.

## Acceptance Criteria
- [ ] The language has been updated where appropriate
- [ ] A PR has been requested for merging

**Comment by sporeboy** [comment]
Note: there are wholesale revisions to the explanatory copy in the [686 punchlist.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0720.md#add-child-section)

Consider changing ALL the explanatory copy since we're in the code. This could address the non-biological stepchild :

To add a stepchild, you’ll need to provide a copy of their birth certificate, showing the names of both parents if
- Your stepchild is *not* the biological child of your spouse (adopted, for example) or
- You don’t live in the U.S. or a territory of the U.S.
