### ISSUE TITLE
Endpoint Access Token for CH31 Prod

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19466]
## Background
Need documentation on CH31 Prod endpoint:

We may want to avoid giving too much info out that doesn't compromise future systems/ efforts.
Establish what is truly needed, see ticket #19606

This is what we're needing for prod: https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L870

## Tasks

- [x] Connect with Devops (Jeremy Britt?)
- [x] Reference work with me (Derek) in regards to this (Conversation took place in keybase)

We will likely need to give him the following:
  base_url:
  credentials (maybe not?):
  auth_endpoint:

It would be good to check with CMS that the endpoint for submission is the same: here is what we are sending to  currently: https://github.com/department-of-veterans-affairs/vets-api/blob/7cc29c662e79636ec1913684a71ec5a480a5dc53/lib/vre/service.rb#L46

## Acceptance Criteria
- [x] Once the endpoint arrives from the stakeholder (post CI) we can insert it on Monday and have it deploy as soon as we can

**Comment by kathleencrawford** [comment]
Devops PR submitted here: https://github.com/department-of-veterans-affairs/devops/pull/8938

Julian from devops added what we needed to credstash.
