### ISSUE TITLE
Security - iterate to improve the management of user credentials 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19478]
## Problem Statement 
Maintaining credentials is difficult, and we lack the ability to grant fine-grained access to specific platform resources, without granting broad administrative access which is outside of the scope of a developers given role. This is caused by permission redundancy between groups and there being no unified strategy to granting permissions. This results in over-privileged users that have more access than needed to perform their role / job function. This also results in an expectation of needing elevated privileges that are outside of the scope of day-to-day work in order to carry on one's tasks. There is also inconsistency in the existing design of various security-related resources. 

How might we add easily manage user credentials in a way that grants only the access which is required for a developers given job function? 
How might we integrate this new credentials management workflow and associated tools into ops-owned applications and services? 
How might we reduce administrative overhead by automating these processes and workflows for granting access to resources? 
 
## Hypothesis or Bet
Our hypothesis is that by implementing a solution for better management of credentials, we can improve platform security, and the administration thereof. 

## We will know we're done when... ("Definition of Done")
We have migrated permissions from credstash to Amazon's parameter store for all platform resources, ensuring that only required access is granted. 
There is a clear, documented process in place for managing credentials in a way that is easy to do and requires minimal manual administration. 
There is plan in place for how applications will use only SSM integration (and can be migrated completely off of cred-stash). 
When we've considerably reduced policy sprawl (ie clear, straight-forward, easy-to-understand policy in place).
When we have a plan for how to automate the securing of non-compliant credentials. 
Maybe: When we have a plan for how to notify users of non-compliant credentials. 

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
By the end of Q1 2021, we expect to have new permissions management system in place.

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**:

- developer onboarding time ~24 hours (match current request SLA)
- no empty groups in IAM
- only operations team members have administrative privileges (unless service account and/or unless justifiable, documented reason for enhanced privileges for a given user) 
- full accounting / audit of existing policies 

* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
For up-to-date iterations of this work, please see recent initiatives from the Platform's Access Management team.
