### ISSUE TITLE
[Cheetah MVP] Add contact info page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19474]
## Issue Description
Update contact info page for cheetah flow.

---

## Tasks
- [ ] Remove best times section

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] Phone number and email address values are pre-populated from profile (existing behavior)

- [ ] Phone number is a required field (existing behavior)

- [ ] Email address is a required field (existing behavior)

- [ ] Given user has valid phone number and email address entered, When click Continue, Then continues to review page

- [ ] DESIGN - Specs match designs: https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/099PmqG#Inspector
