### ISSUE TITLE
Implement solution to route URLs for utilities through to EKS clusters

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19471]
## Description
We need a way to access the interfaces of utilities using URLs and standard web browsers. 

## Background/context/resources
We have looked into using Traefik.io ([see this ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17487)), but need something working for the time being that will allow us to route traffic through load balancers / ingresses to the appropriate Kubernetes service. 

- ALB controller service that runs in Kubernetes 
- Binds a service to a target group 
- If pod is healthy, attaches to a target group
- Right now, Argo has a binding that tells the controller to watch the service, and attaches it to target group 
- argo-cd-dev-* --> points to ALB ("dev-tools in va gov dev vpc")
- Can attach a target group to any ALB controller that we want
- Right now we have an ALB in each env that can serve 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [X] Install Traefik
- [X] Set up a demo w/ Grafana so that when you visit the URL it route through to the correct pod 
- [ ] Automation for setting this all up (dependent on "the glue")   
- [ ] Set up target group 
- [ ] Set up listener rules on ELB 
Note: each app will have to set up it's own ingress so that it gets picked up by Traefik 

## Definition of Done
- [x] Solution in place to route traffic to services via URL

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by tskinn** [comment]
After spinning up the utility cluster that uses calico we successfully ran grafana on it and exposed it to traffic through an ALB/TargetGroup via the AWS Load Balancer Controller. Routing is handled by the ALB listener rules.

**Comment by tskinn** [comment]
It has been decided to run traefik as an ingress controller. All services that need to be exposed to outside the cluster will create ingressRoute resources (CRD from traefik) to get exposed. We expect routing will mostly be done by hostname.

Traefik service will be ran as type NodePort and all EKS worker nodes will be attached to the traefik AWS Target Group.

So traffic from outside the cluster will go something like:
AWS ALB -> TargetGroup -> EKS Worker NodePort -> Traefik -> Exposed Service

Traefik is now running on the dev, staging, and utility cluster. The CD is almost done as well.

**Comment by jhouse-solvd** [comment]
Moving to review/qa

**Comment by jbritt1** [comment]
Is this okay to close at this time?

**Comment by jhouse-solvd** [comment]
@jbritt1 - can we just make sure that the additional tasks above have been marked as completed (if in fact they are still relevant), or updated to be more accurate?

**Comment by jbritt1** [comment]
> @jbritt1 - can we just make sure that the additional tasks above have been marked as completed (if in fact they are still relevant), or updated to be more accurate?

Updated with strikethroughs on no longer relevant action items like target groups for load balancer configurations.
