### ISSUE TITLE
Adding a link to example of component in prod.

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#19475]
## Issue Description
Based on user feedback, it would be helpful to add a link to an example of a component in production in the Design System. 
---
## Tasks
- [ ] Create list of components that are frequently used 
- [ ] Find examples of components on prod
- [ ] Add a link to in SB to the production version of the component 

## Acceptance Criteria
- [ ] Most frequently used components have a link to an example of that component on production. 

---
