### ISSUE TITLE
[Design] 526: Military service history - Reserves screen - UX Enhancements

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#19479]
## User Story or Problem Statement
As a veteran, I need a clearer understanding of what data is being asked of me when prompted to enter my start and end date for 'reserves' service. 

### Why we're asking this question

Recently, our backend devs [collected some data on drop-off points for the 526 form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15689#issuecomment-769944735). Among them was a fair amount of drop-offs on this page. After assessing whether or not this was tech or experience design-related, we determined it was likely to be a design question that requires some research and UI edits.

Currently, Veterans or their reps are asked to enter a start and end date for service in the reserves on the 'military history' screen. However, the end date cannot be in the future for normal 526 claims. This is potentially confusing because some recently retired or non-active military Veterans may still be in the reserves - meaning they don't have a 'service end' date. Rather, they would expect to see an 'obligation end' date. In the current 526 form we split these nuanced differences into two separate screens. We believe this may create a confusing experience for the user. 

We also ask the user if they are currently activated on federal orders, which we surmise can potentially be consolidated as well.

Some specific questions to consider:

- Should this be right after the military service history page?
- Would it be advantageous to consolidate both the military service history page and the reserves obligation page? 
- What is federal orders and how does that differ from an obligation date? If they are different then how might we explain that to the user?
- Is it possible to move the obligation date and the federal orders questions before the user selects a new condition or existing, in the flow?

## Tasks
- [x] Chat with VBA to understand business requirements around being in the reserves
- [x] Make proposed UI design changes
- [ ] Add this proposed change to list of enhancements to test in a general 526 usability initiative

**Comment by kevinstachura** [comment]
Based on conversations with Paul Schute and Nancy Hogan, we should be able to successfully 'nest' the reserves data into the military service history page. Here is a mockup of what that might look like:

https://vsateams.invisionapp.com/share/9Y10APGURJSV#/445677373_BDD_Military_History_-_Reserves_-_Concept

This will be added to the list of 526 enhancements to test with veterans.
