### ISSUE TITLE
Revisit phone number labels for VAMC health services

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19485]
## Issue Description

<details>
<summary> Something has changed in CMS editorial experience for VAMC health services phone numbers. The FE template is using the hardcoded "Phone" as the heading. </summary>

![image](https://user-images.githubusercontent.com/55411834/106810003-9e45d100-6629-11eb-8ca5-d712489f2d15.png)
</details>
 
## Considerations 
[Slack conversation here](https://dsva.slack.com/archives/C0FQSS30V/p1612551546421100?thread_ts=1612481122.408400&cid=C0FQSS30V)
1. Need to make sure labels are headers so Veterans using assistive tech can tab by header to the number they are looking for.  If those phone labels are not an h of some kind, each label and number will be read to them instead of being able to 

> For example:  if the Phone section begins with an h3:
> Phone `h3`
> Phone label `h4`
> 555-555-5555 `p`

2. Determine the default for labels (if labels are required for phone number and other values like emails, etc). Content editors will need guidance around "good vs bad" labels. 
How to handle services with more than one phone?
Pull in service name for the label and/or allow something more general like Main or Phone?
> For example: 
> 3E Critical Care Unit Phone
> 555-555-5555

---
## Tasks
- [ ] Use the required `fieldPhoneLabel` from the CMS for the heading rather than the hard-baked template.
- [ ] Remove hardcoded Phone from template
- [ ] Evaluate reusable phone components 

## Acceptance Criteria
- [x] Display the value in `fieldPhoneLabel` 
- [x] Multiple phone numbers can be present
- [x] If `fieldPhoneLabel` is null, use "Phone" as label
- [x] No heading levels are skipped

**Comment by mpelzsherman** [comment]
Reviewed with @davidconlon and @mmiddaugh - approved!
