### ISSUE TITLE
Search & Discovery Sprint 40  Priorities

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19480]
## Sprint 40 Priorities for Search & Discovery Team
1. Conduct User Research Sessions 
2. Planning for spelling improvements & Type Ahead 1.0 
3. Establish DOMO Dashboard

#### User Discovery
- [x] [Research] Conduct user sessions for VA.gov sitewide search usability study #12332
- [x] [Product] Search.gov follow up discussions #19011

#### Type Ahead 1.0
- [x] [ALL] Transition from Type Ahead POC to Type Ahead 1.0 #18734

#### Spelling Suggestions Improvements
- [x] [Product] Planning Spelling Improvements #19017

#### Align with Analytics Team to establish DOMO Dashboard
- [x] [Product] Coordination to establish analytics dashboards #19004
- [ ] [Analytics] KPI Dashboard Request #16778
- [ ] [Analytics] KPI Dashboard Request  [Typeahead POC] #18785

**Comment by denisecoveyduc** [comment]
Analytics team is working on implementing requests but all other sprint priorities have been completed.
