### ISSUE TITLE
JSON diff tool reports false positives for array data

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19498]
## Acceptance Criteria

The diff tool should not report false positive diffs in array data.

Examples of false positives:

<details>
  <summary>Identical JSON showing up as diff:</summary>

```js
 {
    "diffType": "Array Edit",
    "path": "fieldContentBlock/6",
    "graphQL": {
      "entity": {
        "fieldSectionHeader": "Preparing for your appointment",
        "fieldSectionIntro": {},
        "fieldAccordionDisplay": true,
        "fieldQuestions": [
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldQuestion": "What should I bring to my appointment?",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p>Please bring the following to your appointment:</p>\n\n<ul><li>Your Veteran Health ID Card (VHIC). If this is your first appointment, we can help you get your picture taken for your card.</li>\n\t<li>Cards for any other types of health coverage you may have (like Medicare, Medicaid, Tricare, or private insurance plan).</li>\n\t<li>Your appointment confirmation letter.</li>\n\t<li>List of your current medications including prescriptions, over-the-counter medicines, vitamins, and any herbal supplements.</li>\n</ul>"
                    }
                  }
                }
              ]
            }
          },
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldQuestion": "Can I get a reminder before my appointment?",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p dir=\"ltr\">Yes, we’ll send you a reminder by phone about your appointment date, time, and location. If you have more than one appointment on the same day, you'll get a phone call for each appointment.</p>\n\n<p dir=\"ltr\"><strong>If you want to get reminders by text message</strong></p>\n\n<p>You'll need to sign up to opt in to this service. Visit the  patient registration office at our <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"0b968788-cfb0-41aa-8206-2577105072fa\" href=\"/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive\" title=\"Pittsburgh VA Medical Center-University Drive\">University Drive</a> or <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"e15ebe41-f7cf-4f2c-a407-3728c341220b\" href=\"/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center\" title=\"H. John Heinz III Department of Veterans Affairs Medical Center\">H.J. Heinz</a> locations. This service is free, but standard messaging rates from your mobile service provider may apply.</p>\n\n<p>Once you sign up to receive text message reminders, you’ll no longer receive reminders by phone call.</p>\n\n<p dir=\"ltr\">If you have more than one appointment on the same day, you'll get one text reminder for all appointments. You can't cancel or reschedule appointments using our text message reminder service.</p>\n\n<p> </p>"
                    }
                  }
                }
              ]
            }
          },
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldQuestion": "How do I cancel or reschedule my appointment?",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p dir=\"ltr\">Please call the clinic where your appointment is scheduled, so we can give the appointment time to another Veteran.</p>\n\n<ul dir=\"ltr\"><li><strong>For appointments at University Drive or H.J. Heinz:</strong> 866-482-7488, select 2</li>\n\t<li><strong>For mental health (behavioral health) appointments: </strong>412-360-660</li>\n\t<li><strong>For appointments at any of our outpatient clinic: </strong>Call the clinic where you scheduled the appointment. </li>\n</ul><p dir=\"ltr\">If you miss your appointment without letting the clinic know ahead of time, we'll consider you a \"no show\" and you'll need to reschedule your appointment.</p>\n\n<p dir=\"ltr\">You can also <a href=\"https://www.va.gov/health-care/schedule-view-va-appointments/\">reschedule or cancel some appointments online</a>.</p>"
                    }
                  }
                }
              ]
            }
          },
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldQuestion": "What if I'm going to be late for my appointment?",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p>Please call us as soon as you can. If you arrive more than 20 minutes late without calling ahead of time, we may have to reschedule your appointment. </p>\n\n<ul dir=\"ltr\"><li><strong>For appointments at University Drive or H.J. Heinz:</strong> 866-482-7488, select 2</li>\n\t<li><strong>For mental health (behavioral health) appointments: </strong>412-360-660</li>\n\t<li><strong>For appointments at any of our outpatient clinic: </strong>Call the clinic where you scheduled the appointment. </li>\n</ul>"
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "cmsExport": {
      "entity": {
        "fieldAccordionDisplay": true,
        "fieldQuestions": [
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p>Please bring the following to your appointment:</p>\n\n<ul><li>Your Veteran Health ID Card (VHIC). If this is your first appointment, we can help you get your picture taken for your card.</li>\n\t<li>Cards for any other types of health coverage you may have (like Medicare, Medicaid, Tricare, or private insurance plan).</li>\n\t<li>Your appointment confirmation letter.</li>\n\t<li>List of your current medications including prescriptions, over-the-counter medicines, vitamins, and any herbal supplements.</li>\n</ul>"
                    }
                  }
                }
              ],
              "fieldQuestion": "What should I bring to my appointment?"
            }
          },
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p dir=\"ltr\">Yes, we’ll send you a reminder by phone about your appointment date, time, and location. If you have more than one appointment on the same day, you'll get a phone call for each appointment.</p>\n\n<p dir=\"ltr\"><strong>If you want to get reminders by text message</strong></p>\n\n<p>You'll need to sign up to opt in to this service. Visit the  patient registration office at our <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"0b968788-cfb0-41aa-8206-2577105072fa\" href=\"/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive\" title=\"Pittsburgh VA Medical Center-University Drive\">University Drive</a> or <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"e15ebe41-f7cf-4f2c-a407-3728c341220b\" href=\"/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center\" title=\"H. John Heinz III Department of Veterans Affairs Medical Center\">H.J. Heinz</a> locations. This service is free, but standard messaging rates from your mobile service provider may apply.</p>\n\n<p>Once you sign up to receive text message reminders, you’ll no longer receive reminders by phone call.</p>\n\n<p dir=\"ltr\">If you have more than one appointment on the same day, you'll get one text reminder for all appointments. You can't cancel or reschedule appointments using our text message reminder service.</p>\n\n<p> </p>"
                    }
                  }
                }
              ],
              "fieldQuestion": "Can I get a reminder before my appointment?"
            }
          },
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p dir=\"ltr\">Please call the clinic where your appointment is scheduled, so we can give the appointment time to another Veteran.</p>\n\n<ul dir=\"ltr\"><li><strong>For appointments at University Drive or H.J. Heinz:</strong> 866-482-7488, select 2</li>\n\t<li><strong>For mental health (behavioral health) appointments: </strong>412-360-660</li>\n\t<li><strong>For appointments at any of our outpatient clinic: </strong>Call the clinic where you scheduled the appointment. </li>\n</ul><p dir=\"ltr\">If you miss your appointment without letting the clinic know ahead of time, we'll consider you a \"no show\" and you'll need to reschedule your appointment.</p>\n\n<p dir=\"ltr\">You can also <a href=\"https://www.va.gov/health-care/schedule-view-va-appointments/\">reschedule or cancel some appointments online</a>.</p>"
                    }
                  }
                }
              ],
              "fieldQuestion": "How do I cancel or reschedule my appointment?"
            }
          },
          {
            "entity": {
              "parentFieldName": "field_questions",
              "fieldAnswer": [
                {
                  "entity": {
                    "fieldWysiwyg": {
                      "processed": "<p>Please call us as soon as you can. If you arrive more than 20 minutes late without calling ahead of time, we may have to reschedule your appointment. </p>\n\n<ul dir=\"ltr\"><li><strong>For appointments at University Drive or H.J. Heinz:</strong> 866-482-7488, select 2</li>\n\t<li><strong>For mental health (behavioral health) appointments: </strong>412-360-660</li>\n\t<li><strong>For appointments at any of our outpatient clinic: </strong>Call the clinic where you scheduled the appointment. </li>\n</ul>"
                    }
                  }
                }
              ],
              "fieldQuestion": "What if I'm going to be late for my appointment?"
            }
          }
        ],
        "fieldSectionHeader": "Preparing for your appointment",
        "fieldSectionIntro": {}
      }
    }
  }
```
</details>

<details>
  <summary>Object mismatch due to sorting/filter?. e.g. in event-listing:</summary>

```js
  {
    "diffType": "Array Edit",
    "path": "pastEvents.entities/0",
    "graphQL": {
      "title": "Camp Pendleton Area Military Virtual Career Fair",
      "entityUrl": {
        "path": "/outreach-and-events/events/camp-pendleton-area-military-virtual-career-fair"
      },
      "fieldFeatured": false,
      "fieldDatetimeRangeTimezone": {
        "value": 1619719200,
        "endValue": 1619733600,
        "timezone": "America/Los_Angeles"
      },
      "fieldDescription": {},
      "fieldLocationHumanreadable": {},
      "fieldFacilityLocation": {}
    },
    "cmsExport": {
      "title": "Savanna, Georgia Veteran Employment Job Fair",
      "entityUrl": {
        "path": "/outreach-and-events/events/savanna-georgia-veteran-employment-job-fair"
      },
      "fieldFeatured": false,
      "fieldDatetimeRangeTimezone": {
        "value": 1583938800,
        "endValue": 1583949600,
        "timezone": ""
      },
      "fieldDescription": "Are you a Veteran searching for employment or a career change? The Compensated Work Therapy (CWT) Section is hosting a job fair.",
      "fieldFacilityLocation": {},
      "fieldLocationHumanreadable": "Ralph H. Johnson VA Medical Center"
    }
  }
```
</details>

## Tasks

- [x] use lodash `isEqual` to compar arrays item by item (MPS)
- [x] use the graphql array for the “left hand” side of the array comparison (MPS)
- [ ] ~sort the arrays by entityId, if possible, before comparing. Add entityId's as needed to support. (MPS)~
We tried this but it didn't seem make any difference, and there are too many missing entityIds to make it practical anyway.
- [x] output the array diffs to a separate file, listed by entity name - e.g. `<entity>_array.json` (Theo)
- [x] add more attributes to keysToIgnore (MPS)
- [x] remove keysToIgnore recursively (Theo) - MPS started but this isn't working 100% yet
- [x] Show Array Length diffs - these appear to be missing (Theo)
- [ ] Look at using [json-diff](https://github.com/andreyvit/json-diff) to get colorized diff output (?? nice to have)
Theo investigated, but json-diff didn't work as advertised.

**Comment by brangi** [comment]
Here is an example:
<img width="574" alt="Screen Shot 2021-02-04 at 11 46 14 AM" src="https://user-images.githubusercontent.com/100468/106935272-c04e5a80-66e0-11eb-9fa7-fa3e4a2ad747.png">

**Comment by theodur** [comment]
Looking through the [deep-diff](https://github.com/flitbit/diff) repository, I noticed a [PR](https://github.com/flitbit/diff/pull/101) was merged for adding a "order Independent diff" option. The `orderIndependentDiff` function seems to do this. I tested this on @mpelzsherman's gist above, and it works as expected. I am going to test this in the JSON diff tool.

**Comment by mpelzsherman** [comment]
Resolved by https://github.com/department-of-veterans-affairs/vets-website/pull/15971

**Comment by theodur** [comment]
Update: https://github.com/department-of-veterans-affairs/vets-website/pull/15971 was merged into `master` with improvements to array diffs. We have that array sorting isn't a problem with the tool, especially since we can't sort arrays in it. Array sorting could be an issue with CMS export or transformers. No active work is being done on this ticket at the moment.
