### ISSUE TITLE
[VAMC] Review plain language writing on new Pittsburgh pages and provide feedback [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19493]
## Story
As a Pittsburgh web maintainer, I need now how my pages and source code conforms with current design and plain language standards, so I will know where to improve, update, and correct accessibility.

## Resources
TBD 

## Tasks
- Review the following nodes/pages for current content requirements/content strategies:
**Review the following pages report/document**
- [ ] About us
- [ ] Intensive Rehab Program
- [ ] Interdisciplinary Pain Rehab program
- [ ] Intermediate Low Vision Clinic
- [ ] Any additional page you believe needs a review.

# Acceptance Criteria
- [ ] Pages are copied down into word document where the markups can be seen
- [ ] Document items that do not meet current design/accessibility/Plain Language VA standards
