### ISSUE TITLE
Updated Spanish COVID FAQs page with corrected translation

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19491]
## Issue Description
The VHA translation team reviewed our Spanish COVID FAQs page to ensure the page has the most accurate, high-quality Spanish content as possible. They have some changes, which are reflected in red in the Word doc attached to this ticket. 

The sitewide content team needs to make these changes to the Drupal page. Note that any changes that were made to the page after January 13th won’t be reflected in the Word doc, so we’ll need to check before making changes that the content (other than the edit) is the same. If not, we’ll need to review further.

[https://app.zenhub.com/files/133843125/e3315053-f5ec-454a-9be5-63cea21160d7/download](https://app.zenhub.com/files/133843125/e3315053-f5ec-454a-9be5-63cea21160d7/download)

Drupal page to work on: preview-prod.vfs.va.gov/preview?nodeId=14580

---
## Tasks
- [x] Make changes to Spanish COVID page based on edits in Word doc (Selina)
- [x] Review changes (Randi)
- [x] Publish

## Acceptance Criteria
- [x] Spanish COVID page is updated on live site with edit changes from Word doc
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht I updated to page and it's ready for review.

**Comment by lunascoop** [comment]
Hi @DanielleThierryUSDSVA I made the changes in red. I noticed some other changes on pages 16 and 18 in light brown/oranges. Should they be implemented as well? CC: @RLHecht

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I just noticed one change I'm reviewing they capped Telehealth in once sentence but not in the other. And other places throughout it's still lowercased. Pretty sure this one should be lowercased too but wanted to point it out.![Screen Shot 2021-02-04 at 11.15.50 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/45468b85-0351-42f8-b75a-74db3d4320c8)

**Comment by RLHecht** [comment]
I reviewed these changes and sent an email to the translation team to ask some follow up questions about some of their suggested edits.

**Comment by RLHecht** [comment]
work on this is complete. I made fixes based on on Mateo's email response and set it to publish. Thanks @lunascoop for doing this so quickly! FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
