### ISSUE TITLE
Loki - when EKS is provisioned, we want Loki to have S3 permissions

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19496]
## Description
In order to ensure that the installation of Loki can be easily reproduced in the future, we want to ensure that its components are brought under Terraform control. 

## Background/context/resources
There are still some aspects of this service that have been installed / configured / deployed manually. Let's get those into our IaC modules / workflow. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Bring Loki DEV S3 bucket under Terraform control ?
- [x] Bring Loki STAGING S3 bucket under Terraform control 
- [x] Determine how the "dsva-vagov-loki-eks-staging-s3’" policy the is attached to "dsva-vagov-staging-platform-tools-cluster" role
  - [x] Ensure that this is done in an automated way (Terraform or CloudPosse module) 

## Definition of Done
- [x] When an EKS cluster is provisioned, it has proper permissions to S3

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by oragame** [comment]
The last 2 tasks were approved in my PR today, however, Matt is going to tear down the platform-tools staging cluster and recreate it and include the resources which are part of those tasks. I closed my PR and this ticket should also be complete at this point.

**Comment by jhouse-solvd** [comment]
@oragame - if these are good now, can we check off the tasks mentioned in your above comment and move this to review/qa?

**Comment by jhouse-solvd** [comment]
This is good to go. Closing
