### ISSUE TITLE
Centralized Logging - enable Loki in STAGING for ops-owned services 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19499]
## Description
Before we enable Centralized Logging with Loki in STAGING for all application/service logs, we want to make sure that it is workingfor a selected subset of services that are primarily used and maintained by the operations team. This will allow us to test and confirm Loki setup and configuration launching it to a wider audience. 

## Background/context/resources
Let's start with logs that other teams are not dependent upon so that they don't have difficulty in finding logs before documentation is ready. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Ops-owned services are being ingested by Loki in STAGING
- [ ] Logs in STAGING can be viewed with Grafana

## Definition of Done
- [ ] Logs for all applications/services are available in STAGING (with the exception of AWS-maintained services like RDS, ALB, etc) 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@mydesignrocks - I believe that we've finished the major tasks here and that the ticket can be closed. 

Can you confirm?

**Comment by mydesignrocks** [comment]
yes @jhouse-solvd  - this can be closed.
