### ISSUE TITLE
[SPIKE] Document needed appointment details 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#19506]
## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
As we shift data sources, we need to document what data points are needed for an appointment.

## Tasks
- [ ] Create a small document documenting what data we are using from a MAP appointment structure. 
- [ ] Map data points back to FHIR structure and MAP appointment structure. 

## Acceptance Criteria
- [ ] Engineering team has verified the docs are accurate.

**Comment by mdewey** [comment]
Started the doc here
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/appointment-data/required-data.md

**Comment by mdewey** [comment]
The document is complete.
