### ISSUE TITLE
[FSR] Remove the progressive disclosure components from CH2

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19515]
## Issue Description
_The VA design system is moving towards splitting our form’s pages into smaller chunks to reduce cognitive load, so we need to remove the FSR's progressive disclosure components and create additional pages to spread those input fields across. This ticket encompasses the changes for CH2._

---
## Tasks
- [x] _Remove all the progressive disclosures from the FSR_
- [x] _Evaluate the questions/inputs that were in the original progressive disclosures and create additional pages as necessary_

## Acceptance Criteria
- [x] _The FSR'S CH2 UI has been updated and exported to UXPin_
- [x] _The updated UXPin is linked in this ticket_

**Comment by rileyorr** [comment]
I've broken out the progressive disclosures and reworked the 'Your work history' logic because it now seems redundant to ask the Veteran if they've worked within the past 2 years multiple times. I've updated [the UXPin prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136159503/simulate/sitemap?mode=i), but some of the content now looks a little strange so I'm working with Danielle to incorporate any changes.

**Comment by rileyorr** [comment]
I've incorporated Danielle's content recommendations & updated the prototype. The frontend tickets have also been updated to reflect this work.
