### ISSUE TITLE
Pass Spouse Removal Income Question into Payload

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19510]
## Background
Now that the FE has the income questions in place, we need to ensure the values they represent are passed in to the payload appropriately.

## Considerations
- In the divorce workflow, the property is called `spouseIncome`, and in the death workflow the property is called `dependentIncome`

## Tasks
- [x] Use FE values, add them as needed

## Acceptance Criteria
- [x] The payload has these flags present for **null**, **Yes** or **No** responses
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5885
