### ISSUE TITLE
[UI] Adding Link to VAOS on Questionnaire List

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#19517]
## User Story
- As a Veteran, I want a way to differentiate my Questionnaire List from my appointment list.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A wireframes set for will be delivered showing a link to VAOS on the questionnaire list with the technical specifications needed for engineering to implement said feature.

## Tasks
- [x] Work with Peggy Gannon on wording
- [ ] Finalize detailed mockup and callouts of [feature name](link to prototype)

## Acceptance Criteria
- [ ] UI review meeting with product/team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Published mockup link exists and it is added/updated within the product feature outline
- [ ] Feedback from content is incorporated into the mockup

**Comment by kristenmcconnell** [comment]
@peggygannon There is some concern that users will be confused by our health questionnaire list and think that it is a list of all their appointment (VAOS). However, our page tested well in general, so I don't believe this information needs to be high up on our pages. I was thinking about including a sentence within the Need help? section. Attached is an image, where I took a crack at some text. However, it would be great to get your opinion. Let me know if you have any questions. Thanks.

![VAOS sentence.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/b5cd8d44-2471-4b49-a56a-7a6ca0f7b91a)

**Comment by peggygannon** [comment]
@kristenmcconnell will the link take users into VAOS landing page showing their upcoming appointment cards? do we need to take into account if users are making/have appointments through Cerner/My VA Health? 

here's a recommendation. Let me know what you think! 

Don't see an appointment that you think should be listed here?  You may not have a health questionnaire for that appointment. [Go to the list all your VA appointment]where will link this take users?

**Comment by kristenmcconnell** [comment]
I was thinking that this would link to VAOS. As a whole, how is va.gov handling the Cerner/MyVA Health appointments? If you have some template text that you use for those appointment, then I could include it. I don't think that it is totally necessary right now, but it could future proof a little bit. Our MVP pilot sites for aren't Cerner sites, so the first group of people with any health questionnaires won't be Cerner. Let me know. 

I'll use the text that you sent for now, but I'll leave the ticket open until I hear if there is template Cerner appointment text.

**Comment by kristenmcconnell** [comment]
@peggygannon Any feedback on Cerner appointment wording?

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA @bethpottsVADEPO Based upon this week's VSA UX Weekly meeting, I am tagging you in this story. Please review the story and comments, then let me know if you have any particular feedback on the Cerner/My VA Health thing that Peggy mentioned. Thank you.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell thanks for the ping. The issue is where that link will take users.  I was thinking it would go to health-care/schedule-view-va-appointments/appointments/ , but is that the right location for those users whose facility users Cerner/My VA Health for appts? 

We should get Danielle's and/or Lauren Alexanderson thoughts here, as they are more closely involved with the Cerner integration and VA.gov health tools.

**Comment by kristenmcconnell** [comment]
@peggygannon Thank you. @DanielleThierryUSDSVA and @lalexanderson-dsva - Let me know if there is anything else that I should be aware or if you have different recommendations.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell.

At this time, on the **Schedule appointments** page, we show users who are signed in to VA.gov and are registered at one or more Cerner facilities a modal that directs them to go to either My VA Health or the VA appointments tool, based on the facility they want to schedule appointments at. 

You could perhaps link directly to the full list of appointments in VAOS now and then, in the future, link to the schedule appointments page instead so users could choose the correct portal. If you did that, you'd need to just change the language of the link at that time since it wouldn't be taking the user directly to the list of all appointments. Or, it's possible you could do something like have multiple links depending on where the user is registered and what tool(s) they need. The latter feels overly complex to me for this case, and there may be a better solution than either of these. I think we'd have to think through it more in the context of the full experience of questionnaires for Cerner facilities. 

Do you have an estimate of when you might expand questionnaires to Cerner sites? If it's going to be a while, I think it may be best to just link to VAOS for now and then revisit when the time comes.

I'd also offer a couple of tweaks on the recommended language from above. I'd like to avoid implying that people will "see" their appointments since that doesn't apply to people using screen readers. And need to fix minor typos in link label language.

Not sure if we need to add the word "health"...that's probably obvious in context, but might not hurt to be clear that it's not _all_ VA appointments. Will leave that up to you here.

A few options:

**Can't find an appointment that you think should be on this list?** You may not have a questionnaire for that appointment. [Go to the list of all your  VA health appointments]

**Do you think there's an appointment missing from this list?** You may not have a questionnaire for that appointment.  [Go to the list of all your VA health appointments]

**If you think there's an appointment missing from this list,** you may not have a questionnaire for that appointment. [Go to the list of all your VA health appointments]

Note: If you want to make the link slightly shorter, you could consider: [Go to your full VA health appointments list]

Feel free to use whichever of these you think works best, or let me know if you have questions or other thoughts. Slack is best so the GH notification doesn't get buried in my email. Thanks!

**Comment by kristenmcconnell** [comment]
Slacked with Danielle Thierry about bold font. Yes, we will be bold conditional phrases in the "Need help?" section.

**Comment by kristenmcconnell** [comment]
@mdewey @abuckley3385 After coordinating with Danielle Thierry, the sentence about VAOS within our "Need help?" section has been finalized. Mark, you can create a FE ticket now. 

There are two part to this update. 
1. All the conditional phrases within the "Need help?" section need to be bold text. 
2. The VAOS sentence needs to be added and linked to VAOS appropriately. 

I attached an image of the changes here. The changes are also available in Zeplin: zpl.io/ad6qv0l.

![VAOS sentence.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/13aed935-2996-4861-86e4-eba10fbafa67)
