### ISSUE TITLE
[FSR] Chapter 2 content + UI updates

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19523]
## Issue Description
_The VSP content team provided [a document of content changes](https://drive.google.com/file/d/188CvoTOmTkY-uyAZ3JPo8GNW3CmLr_6t/view?usp=sharing) that need to be incorporated into the FSR. Additionally, the form's UI has been reworked to remove the progressive disclosure component per the VSP design council's recommendation. This ticket encompasses the content and UI changes that need to be made to Chapter 2._

---
## Tasks
[View the updated prototype here.](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136159503/simulate/sitemap?mode=i)

- [ ] Break out the progressive disclosures into separate pages as outlined in the linked prototype
- [ ] _Incorporate the content changes (pages 18-29 in the provided document) into the FSR's staging environment; it may be easier to reference the UXPin for the content updates_
Reach out to the design team with any questions!

## Acceptance Criteria
- [ ] _The Chapter 2 changes have been incorporated into the FSR's staging environment_
- [ ] _Chapter 2's UI matches the linked prototype_
- [ ] _Work has been checked off in the [FSR frontend content epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19513)_
