### ISSUE TITLE
[FSR] PLACEHOLDER - Wizard content changes

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19532]
**This ticket is a placeholder and will be edited once the finalized wizard content is available**

## Issue Description
_The VSP content team provided [a document of content changes](https://drive.google.com/file/d/188CvoTOmTkY-uyAZ3JPo8GNW3CmLr_6t/view?usp=sharing) that need to be incorporated into the FSR. This ticket encompasses the content changes that need to be made to the form's wizard._

---
## Tasks
[View the updated prototype here.](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701647/simulate/sitemap?mode=i)

- [ ] _Incorporate the content changes in the provided document into the FSR's staging environment_
Reach out to the design team with any questions!

## Acceptance Criteria
- [ ] _The form's wizard changes have been incorporated into the FSR's staging environment_
- [ ] _Work has been checked off in the [FSR frontend content epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19513)_

**Comment by leahkeeler** [comment]
There are no changes to content - closing ticket
