### ISSUE TITLE
Add Medallia GTM Script to VA.gov Front-end

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#19539]
## Issue Description
In order to track and report on-site activities related to Medallia user surveys we need to implement Google Tag Manager (GTM) on-site.

---
## Tasks
- [x] Google Tag Manager tracking script is added to VA.gov pages where Medallia surveys are implemented.
- [x] [Privacy and Security review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review) is completed successfully - [Issue](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/218)
- [x] Step is added to Medallia implementation guidelines to ensure the Medallia GTM script is added when new Medallia surveys are added on VA.gov

## Acceptance Criteria
- [ ] Medallia GTM tracking script is added to the following pages (on staging):
  * https://staging.va.gov/find-locations/facility/vha_691
  * https://staging.va.gov/find-locations
_Legacy VA.gov pages_
  * https://www.va.gov/ORMDI/
  * https://www.va.gov/ORMDI/NoFEAR_Select.asp
  * https://www.va.gov/ORMDI/Contact_Us.asp
  * https://www.va.gov/ORMDI/EEOcomplaint.asp
  * https://www.va.gov/ORMDI/HPP.asp
  * https://www.va.gov/ORMDI/Diversity_Inclusion.asp
  * https://www.va.gov/adr/
  * https://www.va.gov/ORMDI/Reasonable_Accommodations1.asp
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
@ianMcCullough-ob Do you have the GTM script? I could not readily find it. Thanks.

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 sure, here's a file with the code in it.

[medalliaGTM.js.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/5932704/medalliaGTM.js.zip)

**Comment by billfienberg** [comment]
## Notes

I suspect that adding GTM script tag to the Legacy VA.gov pages (ORMDI and ADR) will require a TeamSite dev, just like the Medallia script tag.

The good news is that it looks like Google Tag Manager is already available on https://staging.va.gov/find-locations/facility/vha_691 and https://staging.va.gov/find-locations. 

## Screenshots

`/find-locations`: ![image](https://user-images.githubusercontent.com/6130520/107978197-fc57aa00-6f81-11eb-824d-7ea2368c2ef4.png)

`find-locations/facility/vha_691`: ![image](https://user-images.githubusercontent.com/6130520/107978349-3a54ce00-6f82-11eb-9dfe-7d8795728d4a.png)

## Links 

- Google Analytics (GA) script for staging: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/js/google-analytics/vagovstaging.js
- GA script included in GA template: https://github.com/department-of-veterans-affairs/vets-website/blob/6780e56942e1081681c8a0af2ea28d0ad5291f73/src/site/includes/google-analytics.liquid#L18-L26
- GA template included in `header.html`: https://github.com/department-of-veterans-affairs/vets-website/blob/6780e56942e1081681c8a0af2ea28d0ad5291f73/src/site/includes/header.html#L37

**Comment by ianMcCullough-ob** [comment]
Hey @billfienberg does that include the content from that JS file attached in my comment above? Thanks!

**Comment by ianMcCullough-ob** [comment]
|Tag|Screenshot        |Status|
|---|--------|-------|
|survey-invitation-display|<img width="564" alt="survey-invitation-display" src="https://user-images.githubusercontent.com/73119703/110377494-7b407f80-8022-11eb-83af-78ce4c40da75.png">|Pass   |
|survey-invitation-accept|<img width="529" alt="survey-invitation-accept" src="https://user-images.githubusercontent.com/73119703/110377513-7d0a4300-8022-11eb-856b-6ee21bb93edf.png">|Pass   |
|survey-start-form|<img width="559" alt="survey-start-form" src="https://user-images.githubusercontent.com/73119703/110377512-7d0a4300-8022-11eb-8e21-fcbd37c35d26.png">||Pass   |
|survey-invitation-decline|<img width="550" alt="survey-invitation-decline" src="https://user-images.githubusercontent.com/73119703/110377515-7d0a4300-8022-11eb-86c4-b4b783755b6c.png">|Pass   |
survey--submission-successful|<img width="782" alt="survey--submission-successful" src="https://user-images.githubusercontent.com/73119703/110377505-7c71ac80-8022-11eb-9108-fd01a6a45210.png">|Pass   |
|survey-submit-close|<img width="791" alt="survey-submit-close" src="https://user-images.githubusercontent.com/73119703/110377503-7bd91600-8022-11eb-9d0e-f57d8712db7e.png">|Pass   |
|survey-no-submit-close|<img width="540" alt="survey-no-submit-close" src="https://user-images.githubusercontent.com/73119703/110377508-7c71ac80-8022-11eb-9926-839abb8f99ea.png">|Pass   |
|survey--submission|<img width="787" alt="survey--submission" src="https://user-images.githubusercontent.com/73119703/110377506-7c71ac80-8022-11eb-8ca1-856c3e7fd22d.png">|Pass   |
|survey--submission data-layer|<img width="520" alt="survey--submission-dl" src="https://user-images.githubusercontent.com/73119703/110377501-7bd91600-8022-11eb-80f3-2a2504bbe8fe.png">|Pass   |

@jwoodman5 GTM testing has been completed on the ORMDI page, and looks good. Everything is firing properly.

**Comment by ianMcCullough-ob** [comment]
|Tag|Screenshot        |Status|
|---|--------|-------|
|survey-invitation-display|![survey-invitation-display](https://user-images.githubusercontent.com/73119703/110546314-4f91c800-80fc-11eb-93ee-de693b62343b.png)|   |
|survey-invitation-accept|![survey-invitation-accept](https://user-images.githubusercontent.com/73119703/110546296-4acd1400-80fc-11eb-9d60-42a915fb6c72.png)|  |
|survey-start-form|![survey-start-form](https://user-images.githubusercontent.com/73119703/110546327-53bde580-80fc-11eb-80a8-4ab15e1d8d88.png)|   |
|survey-invitation-decline| ![survey-invitation-decline](https://user-images.githubusercontent.com/73119703/110546300-4c96d780-80fc-11eb-8af5-3ce32ce93458.png)|   |
survey--submission-successful|![survey--submission-successful](https://user-images.githubusercontent.com/73119703/110546284-47398d00-80fc-11eb-9e0e-9ccc657f9711.png)|   |
|survey-submit-close|![survey-submit-close](https://user-images.githubusercontent.com/73119703/110546332-56203f80-80fc-11eb-810b-a6f7e5748095.png)|  |
|survey-no-submit-close|![survey-no-submit-close](https://user-images.githubusercontent.com/73119703/110546318-515b8b80-80fc-11eb-9c22-1261414756c3.png)|   |
|survey--submission|![survey--submission](https://user-images.githubusercontent.com/73119703/110546262-4143ac00-80fc-11eb-986e-79b54a376d91.png)|   |
|survey--submission data-layer|![Screen Shot 2021-03-09 at 5 27 28 PM](https://user-images.githubusercontent.com/73119703/110546649-c333d500-80fc-11eb-9faf-d6b6b9d008cb.png)
|   |
