### ISSUE TITLE
[Content] [UI] Review of sign as represeantive workflow for the 10-10CG 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#19548]
## User Story

_As a Veteran, I want the ability to sign as a representative and attach supporting documentation without detracting from the ease of the form._

## Expected Behavior

_ I want the wording within my 10-10CG to be understandable._

## Tasks
- [x] Complete a content review by sending Peggy Gannon a message within the vfs-platform-support channel and tagging her within the comments section of this story
  - Review must include stories: [#18178](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18178)
- [x] Update wireframes with content feedback

## Acceptance Criteria
- [x] Published mockup link exists and it is added/updated within the product feature outline
- [x] Feedback from content is incorporated into the mockup

**Comment by jonathanjnelson** [comment]
Hi @peggygannon 

Wondering if you can review and help finesse the content in this "representative" workflow. 

Please let me know if you have any questions. I would be happy to set up a meeting if easier to discuss. 

[You can see the mockups here](https://vsateams.invisionapp.com/share/W5ZZA7U3DUE#/444247168_Own_Chapter-2-2)

I have also included a couple of screencaps: 

![Screen Shot 2021-02-05 at 12.03.01 PM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/5d9bd41a-d821-450b-b99e-b852a8da0aa4)

![Screen Shot 2021-02-05 at 12.03.27 PM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/7d255abb-ec3e-4c9c-8d85-1591a09359ac)

**Comment by peggygannon** [comment]
@jonathanjnelson Can you give me some context about where this screen will appear in the form flow? What screens will users see immediately before and after this one?

**Comment by jonathanjnelson** [comment]
Thanks @peggygannon 

-- Will users see this screen if they select "Other" for Primary or Secondary Caregiver?
--Or will users always seen this screen?

_**Users will always be presented with this screen.**_ 

--If a user selects "no" is that the end of this flow? (no more action needed on user's part)?

**_If the user selects "no" it is the end of the flow._** 

We are playing around with the location within the flow. 

We are going to test designs with this decision point at the start of the form and at the end before the sign and review screen  

Option 1: https://vsateams.invisionapp.com/share/W5ZZA7U3DUE#/444375620_Intro_


Option 2: https://vsateams.invisionapp.com/share/W5ZZA7U3DUE#/444380802_Intro_2-3

**Comment by peggygannon** [comment]
Hi, @jonathanjnelson Here is my content recommendation for this screen. I also have a few questions/thoughts that came up when I was taking a look at this. Please let me know if you  have any questions. thx! 

**Questions/thoughts**

- I recommend also adding content about representatives to the application's introduction page (maybe under the Prepare step), so this information/documentation requirement is shared with users before they start the application.  

- Would any questions asked in the form need to change if the person filling out the application is a representative? 

- Under the add'l component, I removed the first paragraph as it repeated the content above. I also recommend using bullet points to break up the paragraph about what documents can be submitted. 

- On representative screen, we ask if person is "filling out form as a Veteran's representative" One upload screen, we say "If you're signing as a representative" Which is the most accurate way to present this info? I think we should be consistent in the language. 

------

Content recommendations: 


A legal representative, or someone with power of attorney, can fill out this application on behalf of the Veteran. A representative is someone other than the Veteran who, under law, has the authority to act on behalf of the Veteran, or who can make legal decisions about their responsibility or care. 
 
You’ll need to submit documentation with this form that proves your legal status as a representative. 

{question} Are you filling out this application as a Veteran’s representative?
Yes
No

{add'l component} What documents can I submit to show legal status as a representative? 

Documentation to show your legal status as a representative could include: 
-  A current power of attorney document or legal guardianship order, **or**
- A similar legal document or certification issued by an appropriate attorney, including a federal, state, local, or tribal law that establishes such authority. 

**Note:** Being a Veteran’s closest family member or next of kin doesn’t automatically give you legal status as their representative. You’ll still need to provide documentation to show you can legally act as their representative. 

-------

Upload screen. 
I'm recommending updating this line on the Upload screen to be more PL, replacing "reflecting" with "showing"

If you’re signing as a representative, you can upload supporting documents showing your authority to complete this application on behalf of the Veteran.

**Comment by jonathanjnelson** [comment]
Great @peggygannon! Thank you. 

_I recommend also adding content about representatives to the application's introduction page (maybe under the Prepare step), so this information/documentation requirement is shared with users before they start the application._

Totally agree and I was going to work on this today. Do you have any recommendations or should I take a shot at it and send it your way?

_Would any questions asked in the form need to change if the person filling out the application is a representative?_

Great question. I don't think we would have to change any questions/form labels because we designed the form (as you know) with the assumption that multiple users are completing it. 

With that being said, the "signature box" may need some content updates.

**Comment by jonathanjnelson** [comment]
Hi @peggygannon, 

A couple of things: 

- I took a stab at the content on the intro page (see below). I played around with it as a bullet point and a "note." Seemed to make the most sense as a "note" but not tied to it if you have other recommendations. 
- The upload supporting evidence will not be required for users. Therefore, I was trying to find an alternative for "You’ll **need** to submit..."

![Screen Shot 2021-02-09 at 4 40 44 PM](https://user-images.githubusercontent.com/58444931/107438928-ee73d600-6af6-11eb-99e2-f7a9fa058a25.png)

**Comment by peggygannon** [comment]
Hi, @jonathanjnelson thank you for the clarification that legal status documentation upload is optional.  

followup question: If they don't upload documentation with this application do they need to show proof later or mail it in?

-------

Here's slight tweak to the intro page copy to account for this. Let me know your thoughts. 

**Note:** A legal representative, or someone with power of attorney, can fill out this application on behalf of the Veteran. They’ll need to sign the application. They'll also have a chance to submit documentation to show their status as a legal representative.

**Comment by jonathanjnelson** [comment]
If the user does upload documentation with this application: They will have to submit the evidence later in the process. Typically, a Caregiver Support Coordinator (or a VA employee) will follow up with the applicants to collect proper evidence, etc.   

Thank you for the recommendation on the into page. I think it reads nicely.

**Comment by jonathanjnelson** [comment]
Hi @peggygannon, 

I am curious if you have any guidance for the content and how that might be tweaked if a user signs as a representative (see below). Currently, I left the content from the Veteran's signature box as placeholder text. 

<img width="627" alt="Screen Shot 2021-02-11 at 5 18 21 AM" src="https://user-images.githubusercontent.com/58444931/107631976-7a871a00-6c2b-11eb-9a13-ba2bfd476a87.png">

**Comment by peggygannon** [comment]
Hi, @jonathanjnelson I assume this signing content has already been  approved by stakeholders. If so I just replace "me" with "Veteran". But please let me know if you need a full rewrite of this blurb? 

I certify that I give consent to the individual(s) named in this application to perform personal care services for the Veteran upon being approved as Primary/Secondary Family Caregivers in the Program of Comprehensive Assistance for Family Caregivers.   

A few other recommendations: 

I don't think we need "Enter" for the labels.  I recommend we say:

Representative's full name (note: please fix misspelling of "Representative")
Veteran's full name

**Comment by jonathanjnelson** [comment]
Please see https://preview.uxpin.com/667a6269d62332d37e18a10b41547f6905588c4b#/pages//simulate/no-panels?mode=i
