### ISSUE TITLE
[Design] 526: POW page - UX Enhancements

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#19546]
## User Story or Problem Statement
As a veteran, I need a clearer definition of what a POW is. I also would like better instructions on how I determine whether or not to associate one or more of my conditions with my confinement. 

### Why we're asking this question

Recently, our backend devs [collected some data on drop-off points for the 526 form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15689#issuecomment-769944735). Among them was a fair amount of drop-offs on the fully developed claim page. After assessing whether or not this was tech or experience design-related, we determined it was likely to be a design question that requires some research and UI edits.

Some specific questions to consider:

- How do POWs remember their dates of confinement (i.e. is it easy to remember the actual date they were captured)? 
- Why is it important for VBA to know what conditions came out of their confinement? How does this help the claims process?
- What is the best way to ask veterans for the 'dates of confinement' question?
- How can we clarify the process of asking Veterans to associate their conditions to their time as a POW?
- How might we clarify what a 'single service period' is?

## Tasks
- [x] Chat with VBA to understand business requirements around the POW screen
- [x] Make proposed UI design changes
- [ ] Add this proposed change to list of enhancements to test in a general 526 usability initiative

**Comment by kevinstachura** [comment]
This design concept has been completed and can be viewed here:

https://vsateams.invisionapp.com/share/9Y10APGURJSV#/446610338_BDD_-_POW

We will add it to our list of enhancements to test. Worth mentioning that content is taking a look at it to see if language can be improved, but we have enough to test at this point. Closing.
