### ISSUE TITLE
[Research] 526: New or Existing Disability screen - UX Enhancements

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#19544]
## User Story or Problem Statement
As a researcher, I would like to know why there are drop-offs for this page. I would like to understand why the Veteran or their rep abandons the process at this screen.

<img width="743" alt="Screen Shot 2021-02-19 at 7 54 25 AM" src="https://user-images.githubusercontent.com/54544300/108507033-be130100-7287-11eb-9008-a0732a2aa1a5.png">

### Why we're asking this question

Recently, our backend devs [collected some data on drop-off points for the 526 form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15689#issuecomment-769944735). Among them was a fair amount of drop-offs on certain parts of the flow. After assessing whether or not this was tech or experience design-related, we determined it was likely to be a design question that requires some research and UI edits.

Some specific questions to consider:

- Why are there drop-offs on this page?
- How might we address the problem visually? (i.e. Would there be value in having a 'don't see the condition you're looking for?' dropdown?)

## Tasks
- [ ] Chat with VBA to understand business requirements around this information
- [ ] Make proposed UI design changes
- [ ] Plan a test of these changes with veterans

**Comment by sshein** [comment]
Interested in this, so following :)

**Comment by kevinstachura** [comment]
@sshein this is actually just the checkbox page - I updated the description above with a screenshot so you can see! You may be more interested in ticket #20069 - where we will be taking a look at patterns and improving the language and dropdown for adding new conditions 👍

**Comment by kevinstachura** [comment]
This is a pretty interesting data point...so, I ran some numbers in GA and found some data correlation in the higher output of [SIP data drop-offs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15689#issuecomment-769944735) and bounce rate / exits in the form process. Here's what's interesting:

### High bounce rate in October 2020 for /claim-type

Around the time Anna found a high number of drop-offs from her report (October of last year), I also found a relatively high number of bounces¹ from the same page:

<img width="1172" alt="Screen Shot 2021-02-23 at 4 15 00 PM" src="https://user-images.githubusercontent.com/54544300/108910176-7c6db780-75f3-11eb-9c64-ca039822f052.png">

_Analytics for the claim-type page from October 1st-28th, 2020_

close to 5%, which is significant compared to other assumedly high bounce rate pages in the flow, like evidence-types:

<img width="1179" alt="Screen Shot 2021-02-23 at 5 08 26 PM" src="https://user-images.githubusercontent.com/54544300/108914776-df624d00-75f9-11eb-9b0a-cadcd5cafb03.png">

_Analytics for the evidence-types page from  October 1st-28th, 2020_

So that's an interesting find. But to make it more odd, the bounce rate for this page drops significantly the following month:

<img width="1175" alt="Screen Shot 2021-02-23 at 5 13 15 PM" src="https://user-images.githubusercontent.com/54544300/108915214-8a730680-75fa-11eb-9208-a2f5dc668356.png">

_Analytics for the claim-type page from  November 1st-30th, 2020_

Leading me to conclude it was an isolated incident, as the bounce rate has remained relatively low since then and remains low all-time (2.35%). Remember, a bounce is when someone enters the website on a particular page, takes no action, then immediately leaves. 

### Low exits for /claim-type

Regardless, /claim type has some pretty low exits, consistently:

<img width="1173" alt="Screen Shot 2021-02-23 at 5 21 15 PM" src="https://user-images.githubusercontent.com/54544300/108916205-edb16880-75fb-11eb-9973-9ec181d136c2.png">

_Analytics for the claim-type page from Jan 1st, 2020 - Jan 1st, 2021_

0.38% over the last year. Again, compared to some other pages users are likely to exit (such as the step to upload their private medical records), this is rather low:

<img width="1165" alt="Screen Shot 2021-02-23 at 5 51 38 PM" src="https://user-images.githubusercontent.com/54544300/108918849-07ed4580-7600-11eb-93f9-2ffec84e0c09.png">

_Analytics for the private-medical-records page from Jan 1st, 2020 - Jan 1st, 2021_

The private medical records upload page has about 3.5% of all users exit the process.

### Conclusions

1. **It's likely that there was an anomaly during October last year that had users entering the claim-type page and then immediately leaving.** Whether it was tech related or somehow experience-related, it seems to have corrected course.
2. The exit rate, which tells us whether the user entered via other pages and left via this particular page (ditched the form-filling process), is actually low and therefore not worrisome. 
3. If you read through all of this, please give yourself a pat on the back and make yourself a sandwich too - thinking this much burns serious calories.

I think there's value in running another report in Sentry / grabbing data for SIP and seeing if this anomaly has persisted. Otherwise I think we're okay to focus on other pages

1. In Analytics, a bounce is calculated specifically as a session that triggers only a single request to the Analytics server, such as when a user opens a single page on your site and then exits without triggering any other requests to the Analytics server during that session.
2. in Analytics, an exit is defined as the (number of exits) / (number of pageviews) for the page or set of pages. It indicates how often users exit from that page or set of pages when they view the page(s).
