### ISSUE TITLE
[Tech Debt] - View Payments - Remove feature toggle code

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#19553]
## Description
Now that View Payments has been in production for a while, it makes sense to remove the feature toggle code we have in place. We do this because the feature toggle has served its purpose and the code is no longer needed in the code base.

## Considerations
- The View Payments feature toggle renders code on va.gov/va-payment-history/

<details><summary>Screenshot of rendered widget</summary>

![Screen Shot 2021-02-05 at 11.43.33 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/d2003249-1f98-433b-9bb4-d849d8828e4a)

</details>

## Tasks
- [ ] Remove all feature toggle checks from the [view payments CTA](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/view-payment-history/ViewPaymentHistoryCTA.js)
- [ ] Remove entry from [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml#L315)
- [ ] Run through app, e2e, and unit tests to make sure nothing relies on feature toggles. 

## Definition of done
- [ ] feature toggle removed in `vets-api`
- [ ] feature toggle removed in `vets-website`
- [ ] PRs submitted.
