### ISSUE TITLE
[Tech Debt] - Chapter 36 - Remove feature toggle code 

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#19557]
## Description
Now that CH36 has been in production for a while, it makes sense to remove the feature toggle code we have in place. We do this because the feature toggle has served its purpose and the code is no longer needed in the code base.

## Considerations
- The Chapter 36 feature toggle renders code on va.gov/careers-employment/education-and-career-counseling/

<details><summary>Screenshot of rendered widget</summary>

![Screen Shot 2021-02-05 at 12.21.21 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/2ab56941-974c-42bf-8710-7cee67330836)
</details>

- Chapter 36 feature toggle renders code on https://www.va.gov/careers-employment/dependent-benefits/

<details><summary>Screenshot of rendered widget on dependents benefits page</summary>

![Screen Shot 2021-02-05 at 12.27.33 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/226ff9de-3e12-485f-9357-a57fc7b90543)
</details>

## Tasks
- [x] Remove all feature toggle checks from the [CH36 CTA](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/vre-chapter36/Chapter36CTA.js)
- [x] Remove entry from [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml#L307)
- [x] Remove feature toggle check from [Chapter 36 App Container](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vre/28-8832/containers/App.jsx#L52)
- [x] Run through app, e2e, and unit tests to make sure nothing relies on feature toggles. 

## Definition of done
- [x] feature toggle removed in vets-api
- [x] feature toggle removed in vets-website
- [x] PRs submitted.
