### ISSUE TITLE
[Epic] Complete Original 526 Claim on VA.gov

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1955]
## High Level Epic Goal
As a Veteran, I want to be able to submit a 526 Disability Compensation application on VA.gov even if I have never filed a 526 claim previously, so I can avoid having to be redirected to eBenefits.

## Hypothesis/(es)
**If** _the gating to complete an original 526 form is removed_ **then** _the claimant can avoid having to take additional steps to begin the process to do so_.

## Goals
- Remove gating on VA.gov to allow a claimant enter an original Disability Compensation application
- Any bug fixes, design, or functionality fixes we can make along the way
    - This is a new "goal" for this Epic but it has become obvious we are doing some of this as we go along.
    - One major new example of this is the change for overseas military addresses that has come from the Authenticated Experience team.

## Screenshot
*Current View/Capability*
![Current Ability capture.PNG](https://images.zenhubusercontent.com/5d52c3244773cd34ebdf4867/d88270ff-f4e2-4516-8b12-c75fdcdc5b96)

### Original Ticket: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17775

### MVI Details:
- If Corp ID is not found, but BIRLS ID is found, va.gov needs to be able to create a Corp ID
- MVI needs to expose an endpoint for va.gov to be able to create a Corp ID 

## Launch Checklist

- [ ] **[Accessibility / 508 review]**(https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Accessibility/508-request-prelaunch-review.md)

- [ ] **[ATO review]**(https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md)

- [ ] **[Content QA]**(https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-content-qa.md) / review(?)

- [ ] **[Design QA]**(https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-design-qa.md) / review(?)

- [ ] **Analytics / Product Health Report review**
*   Reviewing analytics that will be used to just the product health / success, and making recommendations as appropriate.

- [ ] **Release plan review**
*   Review release phases and criteria for moving between them. This should include rollout schedule, success/rollback criteria, any pre- and post-launch user testing and monitoring, external documentation and comms.

- [ ] **[IA review]**(https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ia-review.md)
*   Should include review of URLs, navigation hierarchy, crosslinks/redirects, SEO

- [ ] **Security review**
*   Review looking for potential technical security issues / vulnerabilities, focusing particularly on frontend-backend interactions, anything involving certificates or cookies, and any new interactions with dependent backends.

- [ ] **Privacy review**
*   Review looking for potential user data issues, including affirming best practices around handling PII.

- [ ] **Production readiness / infrastructure review**
*   Review of technical architecture, looking for potential scaling concerns, dependency analysis, SLO assessment

- [ ] **Documentation for quickly addressing when things go wrong**
- [ ]   **Contacts for oncall support**: who do we contact if the application is failing? What kinds of failure modes are likely?
    - [ ]  ** Documentation and points of contact for any new backend dependencies**
    - [ ]  ** Links to important dashboards for investigating relevant issues**

- [ ] **No high-severity bugs present**

- [ ] **Testing requirements**
    - [ ]   E2e tests, running in CI/CD, passing on all browsers
    - [ ]   Code coverage requirements
    - [ ]   Load testing

- [ ] **Monitoring requirements**
    - [ ]   Contact (mailing list? Slack channel?) for errors to be reported to
    - [ ]   Errors getting sent directly to team

- [ ] **Contact center(s) are prepared for this launch, with updated scripts/documentation as needed**
- [ ] **VA web comms team is aware of this launch and has accurate messaging**
- [ ] **Product Outline w/critical criteria up-to-date**
- [ ] **Tested in prod with VA back-of-house people and systems**
- [ ] **Entrance pages (i.e. supporting static content) in place**
- [ ] **Downtime UX and error messaging documentation complete**
- [ ] **"Learn and Improve" plan written**: KPI measurements, analytics reporting, next phase of features to build

**Comment by luke-gcio** [comment]
Moved the remainder of the Original Claims stories to our 526 technical debt and we can now groom them again.
