### ISSUE TITLE
Public Websites: Sprint 41 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#19558]
## Sprint 41 Priorities
1.  Finalize CLP FE Styling build (Complete Punchlist and learn from UAT)
2. Transformers Update + JSON Comparison tool #18954 (Trying to reach Functionality Parity is the goal)
3. Assess Iterative R&S functionality - Video and some backlog items are ready for implementation. 
4. Intake Requests for February along with some applicable Tech Debt (508/a11y issues)
5. Discovery for Tech Debt - Internal Audit of Tech Debt opportunities 

### Capacity Planning: PTO/Holiday's
John: 1H
Brian: 1P / 1H
Nick: 0
Kelson: 1H
Laurel: Feb 22-26 (PTO)

### Campaign Landing Page MVP 1.0
- [x] [FE] CLP Refinement Punch List - FE Build #19500
- [x] [PM/PO] Campaign Landing Page VSA-QA Test Plan #19554
- [x]  [FE/PM] General Analytics Request for Campaign Landing Page (Public Websites) #16749
- [x] [PM] Schedule VSP Staging Review 'Post' QA Test/Stakeholder UAT 
- [ ] [PO] Finalize User Guide / On-boarding process flow 
- [x] [Content/PO] Building next proto campaign async during sprint 
- [x] CLP Refinement Punch List - Internal UAT #20087
- [x] CLP Refinement for Event Links and Background #20399

### Transformer + JSON Comp Tool
- [x] [FE] CMS export JSON diffs for Public Websites Transformers #18954
- [x] [FE] Discovery: JSON comparison tool 'Diffs' and assessment on reaching 1:1 Parity for Public Website #19469

### Resources and Support
Priority R&S Breakdown: WIP  [MVP 1.1 EPIC #15588] [Iterate EPIC #15584]
- [ ] [FE] Enhancement: RS mobile views, left margin is too smooshed to the edge and cutting off text #17470 
- [x] [FE] Alert not showing in preview of single Q&A article (RS)#19653
- [ ] [FE] Implement Videos template mobile UX and progressive enhancement #15605
- [ ] [FE] Update Tags component layer with new meta data field #16623
- [ ] [FE] Add whole phrase matching logic to RS search (learning center) #16916

### Cerner Support
- [x] Remove feature toggles + legacy content (Auth/Unauth Cerner Pages) #18821
- [x] Provide facility IDs for all facilities #15309 (@kelsonic look here for Facility ID details)

### Intake Request - Techical Debt
- [x] [FE/Content] CMS team: VAWEB - update GraphQL query and template #18755
- [ ] [Tech debt] Delete deprecated CMS code #19722
- [ ] [Content]  Content Support for Static HLR Page from Claims and Appeals #18876 (Sitewide Content Team WIP)
- [ ] [FE] Pager Component for Outreach Event Page #19292 (Validate)
- [x] CMS [COGNITION]: Multiple ambiguities with linked text in content block #3556

### Discussion Topics/Grooming 
- [ ] Clean up the widget pattern in the "static-pages" code #7751
- [ ] Review [CLP Product Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Collab%20Cyle%20Docs/product-use-cases.md)
- [ ] CMS Video panel is still not rendering on the FE [Diagnose Issue](https://dsva.slack.com/archives/C01DS1XDEQ0/p1612878571006300?thread_ts=1611858742.036500&cid=C01DS1XDEQ0)
- [ ] Explore and revisit Visual Regression Testing to aid in modifications to CMS templates and style #18869 (Add to future sprint).

**Comment by brianalloyd** [comment]
Closing Sprint Tasks
