### ISSUE TITLE
ATO - Table Top Exercises April 2021

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19556]
## Description
Annual Table Top exercises need to be performed in order to maintain ATO. These are exercises that the platform infrastructure engineering team needs to perform in order to step through how to respond to various scenarios that could occur that could affect the platform's performance, stability, or availability. 

## Background/context/resources
These are the three (3) exercises to be performed: 

1. Contingency Plan Test 
2. Disaster Recovery Plan Test
3. Incident Response 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [X] Perform each of the exercises, and produce a report that details how the team would respond to each scenario 

## Definition of Done
- [X] The Annual Table Top exercises report will be submitted to the ATO office. 
---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@fowusu2 submitted the report to the ATO office on Monday, February 22, 2021 and we are compliant with this requirement.
