### ISSUE TITLE
SSL Certificates - Update vets360 fwdproxy certs {dev,staging,prod} BEFORE February 13

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19565]
## Issue Description
Replace security certificates for vetsgov-vet360 before they expire on February 13 in the devevelopment, staging, and production environments.

---
## Resources
Jenkins [alert]( https://dsva.slack.com/archives/C37M86Y8G/p1612198572055800):
URGENT: /ansible/deployment/config/fwdproxy/vetsgov-vet360-dev-cert.pem expires in less than 30 days: 2021-02-13T15:28:21+00:00
URGENT: /ansible/deployment/config/fwdproxy/vetsgov-vet360-prod-cert.pem expires in less than 30 days: 2021-02-13T15:28:21+00:00
URGENT: /ansible/deployment/config/fwdproxy/vetsgov-vet360-staging-cert.pem expires in less than 30 days: 2021-02-13T15:28:21+00:00
Instructions [HERE](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md)

## Tasks
- [ ] Request and install certs for vetsgov-vet360 in {DEV,STAGING,PROD}  environments
- [ ] Test by connecting to the endpoints and ensuring that the updated certificates are returned

## Acceptance Criteria
- [ ] Services are up and running using new cert
- [ ] cert is replaced at the TIC
- [ ] cert is replaced on the fwdproxy alb
- [ ] cert is replaced in the fwdproxy

---

- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic
