### ISSUE TITLE
Alerting - Perform an audit of existing alerts

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19564]
## Description
Perform an audit of existing alerts in Prometheus/PagerDuty (which is currently the only tool that sends texts / calls to individuals' phones) 

Audit should include, at minimum:

- service / metric 
- threshold (warning / critical) 
- point of contact
- notification channels

## Background/context/resources
This is a solid first step in helping to move towards less alert fatigue. 
We also need to provide this information to VA Monitoring team to satisfy their ATO requirements 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Create a spreadsheet / document that captures the alerts audit

## Definition of Done
- [x] We have a current inventory of alerts that has been fully documented 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
re-assigning to @oragame

**Comment by oragame** [comment]
Here is a link to the document - this is just a starting point, more work to be done on point of contact and notification channels. https://docs.google.com/spreadsheets/d/1OT8CJfcqhK208o-Ct-fjf53nGEBrfLMSJfGHXZ1BQDQ/edit#gid=0

**Comment by mchelen-gov** [comment]
these are prometheus alerts, right?

**Comment by oragame** [comment]
@mchelen - yes, these are the prometheus alerts.

**Comment by jhouse-solvd** [comment]
There are a few more rule sets that can be audited, but this is in a good stopping place to share w/ VA monitoring team and get add’l feedback to ensure completeness / legibility of information captured.

**Comment by jhouse-solvd** [comment]
Closing.
