### ISSUE TITLE
[Dual-State-Prep] Prepare Altoona Health Care VAMC for Dual State [VAMC]#

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19574]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Altoona tugboat Instance](http://wilkesbarrehealthcare.web.demo.ci.cms.va.gov/wilkes-barre-health-care/)
[Site Page Checklist](https://drive.google.com/drive/folders/1pxtOTIKPP87uGMcfT-DsmBqIlIgnHXwb)

## TASKS
Validate that each page:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system

**Comment by ltrombley** [comment]
Task #19574 - [Dual-State-Prep] Prepare Altoona Health Care VAMC for Dual State is Complete and moved to Validate.
1. Duplicate locations pages - need to remove page dated 1/19/21
2. Missing Internship and fellowship page
3. Removed the following non-essential broken links:
   a. Floor plans for VA Altoona - page does not exist
   b. Printable transportation guide - does not exist
   c. Edgewater Inn - website link has changed - needs to be confirmed
