### ISSUE TITLE
[FE] - Integration of HealthQuest service to post to Lighthouse PGD 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#19587]
## User Story
As a veteran, 
I want my questionnaire answers to be viewable by my care team
So I know they can be prepared and discuss my status during my appt. 

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Mock ups](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/600080c76d298d2157a8c5dc)

## Description
Implement the integration of the healthquest service to post to PGD
- real data from the front end UI can be sent via the healthquest service to save in PGD

## Tasks
- [x] POST agreed upon JSON structure to the API 
- [ ] Display a success message
- [x] Display error message on error. 

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] PR has been merged into master
- [ ] Designer has signed off on the feature
- [ ] Product owner has signed off feature

**Comment by mdewey** [comment]
Agreeed upon structure: https://gist.github.com/mdewey/f2fad4147c59a0bf04753633122532db

**Comment by mdewey** [comment]
waiting till content is merged to check refactor.

**Comment by mdewey** [comment]
endpoint to check: http://localhost:3000/health_quest/v0/questionnaire_responses?source=1008882029V851792

**Comment by mdewey** [comment]
Works in local ( dev/sandbox), does not work in staging because staging is not set up.
