### ISSUE TITLE
Single Facility, Eligible to Schedule design updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19580]
## Issue Description
Currently, if the selected type of care only has one facility available that supports scheduling and the user is eligible to schedule at that facility, we communicate that in an informational alert.

---
## Tasks
- [ ] Update listing of single facility to the body of page, removing alert style

- [ ] Add "Why isn’t my facility listed?" section and existing logic

- [ ] Update live version

- [ ] Update version behind cheetah feature flag

## Acceptance Criteria
- [ ] Given selected type of care only has one facility available that supports online scheduling, When the user eligible to schedule, Then show facility details AND do not show radio button

- [ ] Given user is registered at a closer facility than the one available, When online scheduling is turned off, Then show "Why isn’t my facility listed?" section

- [ ] Existing logic, design, and copy for the "Why isn’t my facility listed?" section is maintained

- [ ] Given single facility is available, When user clicks Continue, Then user can proceed through the scheduling flow

- [ ] CONTENT - Page header and body/description copy match the specs
  - (Remove required)

- [ ] DESIGN - Designs match the specs: https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/444263109
![19580_scope.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8cf9f70e-b94b-4c5a-a9ee-c2b61f564529)

**Comment by jbalboni** [comment]
@outerpress @laurenernest The page title in the screenshot is different from what's on the page currently. Do you want the page title to be "Your appointment location" for just the single facility scenario or do you want the page to always have that title?

Here's the current title:

![Screen Shot 2021-02-22 at 10.17.51 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/b4f803df-b30d-43ed-996b-35188c3df5d5)

**Comment by outerpress** [comment]
@jbalboni "Your appointment location" should be the header. The choose language would be confusing in there for sure.
