### ISSUE TITLE
HealthRecords - Immunizations

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#19590]
## Product Documentation
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [HealthRecord Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/health-record.md)

## User Story/ies

**(5F) As a Veteran, I want to update my current immunizations so that my care team is aware of what shots I may have received outside the VA medical facilities and update my health record.**

Review and Edit
(2A) As a Veteran, I want to review and update my health information to ensure its accuracy, so my care team can focus on my treatment plan and whats important to me vs. data entry during my visit.

Since Last Time
(2B) As a Veteran, I want to only provide updates to my health information that is affecting me now, changed since last time, or due for screening, so that I save time documenting my information and my care team can focus on the changes to my treatment plan and whats important to me.

Patient-centric plain language
(3A) As a Veteran, I want to have complicated medical terms explained to me in a tone and language that I understand, so that I am able to provide accurate updates to my health information and be prepared to ask questions to my care team for further education.
(5A) As a Veteran, I want to provide my health status and updates to my medical history so that I do not have to feel I have to repeat the information to my nurse and provider in the same and subsequent visits.

---
## Tasks
- [ ] [Complete Immunizations Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/immunizations.md)
- [X] Create new folder for this specific test: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/research/health-record
- [X] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/health-record/research-plan.md)
- [ ] Create conversation guide 
- [ ] Mockups link 

## Acceptance Criteria
- [ ] UI review with entire team for feature capabilities

**Comment by julieadair1** [comment]
@jparker0425 do we need to prioritize any of this work related to health records?
cc: @batemapf
