### ISSUE TITLE
TUD - Hide the password in the table

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19599]
## Issue Description
In the TUD web application, the passwords are currently viewable to authenticated users.  Our security engineer brought up a good point about if there was a breach it'd be more difficult to scrape these items if the passwords her obfuscated.  This feature would effectively hide test account passwords by default and only revealing the passwords when the table row is expanded.

---
## Screenshots
Default
<img width="1035" alt="default" src="https://user-images.githubusercontent.com/67602137/107378028-94085480-6ab9-11eb-8b77-90b04195b210.png">
Expanded
<img width="1243" alt="expanded" src="https://user-images.githubusercontent.com/67602137/107378026-936fbe00-6ab9-11eb-9996-9d57d5a13569.png">

---
## Tasks
- [x] Meet with Amanda (UX) to determine design implications of hiding passwords
- [x] Obfuscate the passwords so they aren't recognizable by default
- [x] When a row is expanded reveal the correct password.

## Acceptance Criteria
- [x] I do not see test user account passwords in the table on the TUD by default
- [x] I can see the test user account password when expanding the row for more information
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
