### ISSUE TITLE
Migrate "View and Apply for Certificate of Eligibility" for LGY LoB to VA.gov

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19595]
# View and Apply for Certificate of Eligibility

Issue brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/

| Screens | Links | Text Sources | Last Rev | |
| :--- | :--- | :--- | :--- | :--- |
| Feature Flow Diagrams | [Adobe XD](https://xd.adobe.com/view/6c65f5c2-36e1-4051-81be-6f8b9415a3cd-3936/) | No text | TBD | --- |
| Concept Mockups | [UXPin](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137576823/comment/sitemap,comments) | Using prototype screens | TBD | --- |
| Prototype | [UXPin](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137576823/simulate/sitemap?mode=f) | Set to full screen | TBD | --- |

**eBenefits URL:** https://www.ebenefits.va.gov/ebenefits/coe

**Staging:** https://staging.va.gov/

**Production:**
Static landing (Drupal): https://www.va.gov/
Online form application: https://www.va.gov/

## Story
As a Veteran I want to establish my eligibility for loan assistance, view my application status a list of my dependents, and apply for a certificate of eligibility to assist with getting a VA home loan, so that I can make sure me and my family is getting the benefits I've earned.

### Mission
Create a user friendly, innovative, self-serve Veteran portal in VA.gov to request benefits available to the Veteran, Servicemember, Dependents and Surviving Spouses, including VA Home Loan Benefits.

## Considerations
- Like most _view_ actions, this has a _form_ action as well: Modify Dependents (issue number TBD)
- No visibility into automatic COE criteria. Basic components:
  - Applicant is a Veteran (?)
  - Applicant biological and contact info
  - Service history
  - No loans on record (?)
- BE dev discovery of current EBN process required.
- When a COE can not be automatically issued (ACE), provide precise messaging that details exactly what data or documentation is required to determine eligibility and issue the COE and nothing more.
- Only permit one active COE record at a time. There should never be multiple active COEs at one time.
- If there is a data mismatch. provide precise error messaging to the requestor immediately advising what data is not matched. 
- They should be permitted to correct or input the missing data needed for an eligibility determination to be rendered.

## Definition of Done
- [ ] I can see my latest COE application status, if any
- [ ] I can see whether I am eligible automatically based on information the VA already knows about me
- [ ] I can apply for COE easily using the online application

## Pilot Tasks
- [x] Discuss and determine the goals for LoB
  - [x] Determine how the service currently establishes eligibility and what those requirements are
  - [x] Determine what services may be needed for eligibility and tracking claim statuses
- [x] Create artifacts towards pain points by the Veteran; user research plans/convo guide
- [x] Develop mockups/prototypes to validate any new hypotheses
- [x] Make the initial integration
- [x] Render the claim status(es) and "automatic eligibility check" status to the front end
- [ ] UX, 508, call center updates

## Further Tasks
- Connect this work to other features, APIs
- Determine what tasks are being accomplished when viewing this list and connect it to a broader UX (Profile?)
- Provide responses to Frequently Asked Questions (FAQs) regarding VA Home Loan Benefits within the Veteran portal.
- Provide a contact list for the Veteran, Servicemember or Surviving Spouse to reference if they did not find an answer to their VA Home Loan benefit question within the FAQs.
- Increase the number of automatically issued COEs (ACE) by improving the accuracy of the required data and documentation associated to the Veteran or Servicemembers record.
- Provide push notifications (text or email) about Eligibility status if there is a cell number or email on record.
- Create a Dashboard of VA Home Loan benefits that can be accessed by the requestor to obtain status (Eligibility status, Funding Fee Exemption Status, Available Entitlement, Entitlement Code, Outstanding VA loans history, etc) related to their VA Home Loan Benefits.
- Loan Calculators that include the specific funding fee and available entitlement for the loan they are seeking.
- Provide clear, concise status of where the COE requests is in process under a Check COE status link.
- Allow requestors to be able to correct data at the time of request or prior to LGC issuance (Name, Address, etc) or for data they should not be permitted to update themselves, provide the ability for them to submit a request to update to the RLC.
- Provide a fast and efficient way to upload supporting documentation required for an eligibility determination to be rendered.

## LoB Considerations
- Once we define the 'request a COE experience', we need to determine the API vision to support the redesigned user experience.
- The API vision must be created with an eye towards the long term COE Redesign initiative.
- API vision plan will need to be coordinated with the SAH team to ensure consistency and compatibility in design
