### ISSUE TITLE
Document deduplication examples

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19593]
## Issue Description
Examples of the deduplication scenario will illustrate the current logic and support communication about the issue with OCC

---

## Tasks
- [ ] Document two Provider Locator search examples that are impacted by deduplication logic
- [ ] Document two Place of service search examples that are impacted by deduplication logic

## Acceptance Criteria
For at least two (each) Provider Locator and Place of service search examples, the documentation includes
- [ ] Query/curl
- [ ] Swagger data 
- [ ] Facility Locator result set 
- [ ] logic in place and impact (missing providers)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
