### ISSUE TITLE
[UI][Research] Health Record Research Assets

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#19602]
## Product Links
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [HealthRecord Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/health-record.md)
- [Medications Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md)
- [Allergies Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/allergies.md)
- [Immunizations Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/immunizations.md)

## Description
All assets for the Mural activity needed to run the health record user research session will be completed by the end of this ticket.

## Tasks
- [X] Create assets for Mural activity (https://app.mural.co/t/vsa8243/m/vsa8243/1612803040285/9ee796589a8531afe6837796feb42a5dfd2e7037) 

## Acceptance Criteria
- [X] The Mural activity is ready to be utilized within research session
- [X] Review assets with the team (particularly product)
