### ISSUE TITLE
Create and implement credentials for VRE CH31 Prod

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#19606]
## Background
With a coming launch for CH31, VRE informed us that they need a list of IPs/Subnet and an SSL cert.

> Sometime in the near future, the CMS REST endpoints will be hardened to only allow traffic from a specific IP / subnet and will only trust SSL certificates from certain servers. As your VA.GOV service sends the application JSON to one of these endpoints, I wanted to go ahead and get the communication started so that we are ready to implement this change – there will be no delays.

## Goal
Get VRE everything they need so they can get us production endpoints/credentials

## Tasks

- [x] Send Jessie from ops a message, get Jason involved
- [x] Create a ticket for Ops, (Note to Derek: look in your discussion with Jeremy Britt about ticket template/format)
- [x] Generate cert (Don't add a PW) (Note to Derek: look in your conversation with BE devs, SF link was provided)
- [x] Give Cert to Devops team via Keybase so they can upload to Credstash (Find out who's on call/taking these creds at the time)

## Acceptance Criteria
- [x] Creds are inputted into credstash

### Notes
Link to VRE config Jeremy setup a while back. Might be needed for reference: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml#L160-L165

**Comment by digitaldrk** [comment]
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/20128
