### ISSUE TITLE
[UI][Research] Health Record Research Analysis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#19605]
## Product Links
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [HealthRecord Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/health-record.md)
- [Medications Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md)
- [Allergies Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/allergies.md)
- [Immunizations Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/immunizations.md)

## Description
A research report detailing findings and design recommendations will be created from the research study.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

## Acceptance Criteria
- [x] Create research reports/readout documents of findings
- [x] Update the [research history](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md) document
- [x] Deal with recordings once analysis is complete
- [x] Create necessary issues/tickets that address findings in coordination with Amanda
- [x] Schedule readout sessions with stakeholders, team, Demos, UX weekly(?)
