### ISSUE TITLE
Remove contexts from CircleCI until we have the ability to limit context access by security groups

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#19614]
## Description
Contexts in CircleCI are currently only able to be created with a default 'All members' group, which gives access to all members of the github Org 'department-of-veterans-affairs'. This can be limited by security groups within the circleci interface, based on github teams within the org, however, configuring those settings requires administrative privileges on the org. 

It appears that the only workaround for the time being is to manage the AWS and github tokens by putting them in the per-project ENV settings. This means that if we change these credentials, we have to change them in _all_ of the projects, but this is safer than keeping them in a context.

## Background/context/resources
https://dsva.slack.com/archives/C01CJV0L9PS/p1612651359029600

## Technical notes
Partial list of repos that I know are using contexts:
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-nlb"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-elastic-search-logs"
    "https://github.com/department-of-veterans-affairs/vsp-infra-aws-load-balancer-controller"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-saml-proxy"
    "https://github.com/department-of-veterans-affairs/vsp-infra-pact-broker"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-internal-alb"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vetsgov"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-iam-user"
    "https://github.com/department-of-veterans-affairs/vsp-infra-traefik"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms-test"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-fwdproxy"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-nested-map"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-content-preview"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-fargate-service"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-s3-bucket"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-revproxy"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-kong-logs-elasticsearch"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks"
    "https://github.com/department-of-veterans-affairs/vsp-infra-grafana"
    "https://github.com/department-of-veterans-affairs/vsp-infra-nginx-sidecar"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-postgres"
    "https://github.com/department-of-veterans-affairs/vsp-infra-fluentd"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vaec-vpc-flowlog-subscription"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vpc-endpoint"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vets-api"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-unbound"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-atlantis"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-api-gateway"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-gids"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-prometheus"
    "https://github.com/department-of-veterans-affairs/vets-api"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-epo-sg"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms-ci"
    "https://github.com/department-of-veterans-affairs/vsp-infra-loki"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-ecs"
    "https://github.com/department-of-veterans-affairs/terraform-aws-vsp-iam-role"
Other repos in the org may also be using contexts, may require investigation.
---
## Tasks
For each project:
- [ ] Determine what contexts a job needs (defined in the workflows section of the config.yml)
- [ ] Determine what permissions are conferred by those contexts
- [ ] Create Environmental Variables in the project that replicate the credentials that would have been in the context

Once all have been done:
- [ ] Delete the global contexts

## Definition of Done
- [ ] AWS credentials and github credentials will no longer be stored in the global CircleCI Organizational contexts.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@dginther - please comment and close if this is no longer relevant? Thank you.
