### ISSUE TITLE
Add operationalHoursSpecialInstructions field for VA health

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19615]
## Issue Description
VAST administrators have included a new `operationalHoursSpecialInstructions` field that is now in Lighthouse.

![operational status](https://user-images.githubusercontent.com/55411834/105556756-e5e26980-5cc7-11eb-85dd-56ac73acca56.jpg)

There are 4 possible options that could be concatenated from VAST:
- Administrative hours are Monday-Friday 8:00 a.m. to 4:30 p.m.
- Expanded or Nontraditional hours are available for some services on a routine and or requested basis. Please call our main phone number for details.
- Vet Center after hours assistance is available by calling 1-877-WAR-VETS (1-877-927-8387).
- Vet Center hours are dependent upon outreach assignments. Please call our main phone number for details.

Field may contain one or more of the options above. If more than one is sent, more than one will be displayed. 
If null, nothing will be displayed. 
Value sent will be displayed beneath hours of operation on detail page. 

 
---
## Tasks
- [ ] Keep hardcoded language for now and put this on a flipper
- [ ] Pull in `operationalHoursSpecialInstructions` field language **for VA health facilities only** 
- [ ] If value in the field contains pipes or other odd formatting, we need to inform Lighthouse to resolve formatting

## Acceptance Criteria
- [ ] When flag switched for production, the language displayed on **VA health detail page** matches language from `operationalHoursSpecialInstructions` field 
- [ ] If more than one option is sent, all display. 
- [ ] If null, nothing displays

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
@mmiddaugh this change can be validated with this review instance - 
http://358b3315109fec54fc0b497ad65f6ea3.review.vetsgov-internal

Example, Dallas:  http://358b3315109fec54fc0b497ad65f6ea3.review.vetsgov-internal/find-locations/facility/vha_549

**Comment by mmiddaugh** [comment]
@davidconlon we have some formatting clean-up to do with Lighthouse 

![image](https://user-images.githubusercontent.com/55411834/107972683-6f0c5980-6f71-11eb-8eec-4bcb749293eb.png)
