### ISSUE TITLE
Fix list loop's input error state presentation

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#19617]
## Issue Description
We tried a few variations for this issue but came back to simply ensuring the error state defaults to the same line rather than bumping the error-ed input down to another row, like in the following screen capture:
https://images.zenhubusercontent.com/133843125/f5f6d5c5-af57-4116-88d9-ceba4c621192/screencap_error.mov

[UXPin link
](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136255713?mode=i)
We also decided that these fields should validate on 'save', if possible.
---
## Tasks
- [ ] Adjust the UI to match the pattern above
- [ ] Confirm with designers (w/ video call or screencapped video)

## Acceptance Criteria
- [ ] UI fix implemented and approved by designer(s)

**Comment by rebeccawalsh** [comment]
This is a inherent design system problem, which will probably be made null by redesign of list loop sections.
