### ISSUE TITLE
[VAMC] Broken Link Check for Lebanon VA Healthcare System prior to Dual State [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19629]
## Story
As a VA tester and web maintainer,  VAMC systems need to launch into a Dual-state prior to Go-Live, so complete testing, training, 508 compliance and final updates and content can be loaded in prep for final product release.

## Goal
- run through publishing testing and document obstacles and performance tasks to improve future publishings

## Resources
[Lebanon Run Book](https://drive.google.com/drive/folders/1GC6PkeS-iIv1XijLCINW5J_1bo7tSO37)

## TASKS
- Confirm and validate all of the following have been complete prior to Dual-State Launch Date: 
**Tie this story into Dual-State-Launch for Lebanon**
- [x] Using Tugboat, validate and correct all Broken Links
- [ ] Confirm and resolve any issues from Internal and external testing
- [ ] Implement any 508 recommendations received from previous testing cycles

## Acceptance criteria
- [ ] All valid broken links are resolved
- [ ] NO known 508 failures remain unresolved or documented for repair by the correct team
