### ISSUE TITLE
Add disallow text file 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19622]
##Issue Description
Each time the VAMC team brings up a new System into Dual-State, a facilities engineer needs to add a disallow line (`Disallow: -health-care/`) under # existing disallow on va.gov to the robots.txt file and push a PR to engineering to prevent crawlers from accessing the new site in dual state.

Platform needs a PR to add that one line to the robots.txt file found

Per Steve Wirt, the disallow should go here: [src/site/assets/robots.txt:97](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/robots.txt#L97)
`Disallow: /performance-dashboard`
(In the useragent * section which covers all bots other than usasearch and synapse)

A separate issue will be created for the addition of an allow statement when the VAMC team is ready to put up a banner from the legacy site.

## Tasks
- [ ] Add a disallow line (Disallow: /-health-care/) for the following facilities under # existing disallow on va.gov to the robots.txt file (this will cover the Q1 2021 rollouts)

> va.gov/altoona-health-care/
> va.gov/butler-health-care/
> va.gov/coatesville-health-care/
> va.gov/lebanon-health-care/
> va.gov/philadelphia-health-care/
> va.gov/wilkes-barre-health-care/
> va.gov/wilmington-health-care/
> va.gov/asheville-health-care/
> va.gov/durham-health-care/
> va.gov/fayetteville-coastal-health-care/
> va.gov/hampton-health-care/
> va.gov/richmond-health-care/
> va.gov/salem-health-care/
> va.gov/salisbury-health-care/
> va.gov/cheyenne-health-care/
> va.gov/eastern-colorado-health-care/
> va.gov/eastern-oklahoma-health-care/
> va.gov/montana-health-care/
> va.gov/oklahoma-city-health-care/
> va.gov/salt-lake-city-health-care/
> va.gov/sheridan-health-care/
> va.gov/western-colorado-health-care/

- [ ] Post message in VSP when PR is ready

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
For future reference, it will save us a little time if you provide these entires in the following format:

`Disallow: /erie-health-care`

**Comment by mpelzsherman** [comment]
Validated in production.
