### ISSUE TITLE
Create a Grafana Board with Log Data

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19623]
## Background
Our features will need better reporting beyond what GA can do at the page level.

## Tasks
- [ ] Using server log and application error messaging, create a Grafana dashboard for the CH36 feature that shows the following:
  - [ ] Number of **total** submissions
  - [ ] Number of **successful** submissions
  - [ ] Number of **failed** submissions and **why**
- [ ] Has the ability to select various time periods

## Acceptance Criteria
- [ ] A Grafana dashboard has been shared with the team
- [ ] If applicable, steps have been shared to create other dashboards for other features
