### ISSUE TITLE
[VAMC] Publish Altoona Healthcare System into Dual-State [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19635]
## Story
As a VA tester and web maintainer,  VAMC systems need to launch into a Dual-state prior to Go-Live, so complete testing, training, 508 compliance and final updates and content can be loaded in prep for final product release.

## Goal
- run through publishing testing and document obstacles and performance tasks to improve future publishing

## Resources
[altoona Run Book](https://drive.google.com/drive/folders/1GC6PkeS-iIv1XijLCINW5J_1bo7tSO37)

## Tasks
Pre-launch confirmations:
- [ ] Confirm Drupal FE environment is stable and building correct as expected in last 24 hours
- [ ] Confirm with FE tools there are no competing builds (Dependent on Jenkins to determine)
- [ ] Confirm with Platform FE there are no outstanding issues and we are OK to publish
- [ ] Confirm that root URL has been added to robots.txt/blacklist (Disallow)

Begin Deploy

- [ ] The Publishing and release of content for va.gov/altoona-health-care/
- [ ] Open Deploy link to Jenkins and confirm which PR is associated to Publication
	- [ ] If there is an issue, validate issue in logs and try correction within 15 minutes.
	- [ ] If resolved start again, If not reschedule deployment and Schedule postmortem on Logs.
**After successful Deployment**
- [ ] Confirmation Site is up and accessible
- [ ] Left-Navigation bar is valid and working
- [ ] Documenting any errors/bugs that need to be resolved
- [ ] Determining if there are critical errors and rollback may be require
- [ ] Schedule and document postmortem/process improvement areas

## Acceptance Criteria
- [ ] https://www.va.gov/erie-health-care/ is published
- [ ] Left Nav is up and working and or issue initiated to fix any anomalies
- [ ] Access to pages is confirmed and/or issue is initiated to fix any anomalies
- [ ] Postmortem/lessons learned meeting is scheduled.
