### ISSUE TITLE
[VAMC] Publish Wilkes-Barre health care into Dual-State [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19632]
## Story
As a VA tester and web maintainer,  VAMC systems need to launch into a Dual-state prior to Go-Live, so complete testing, training, 508 compliance and final updates and content can be loaded in prep for final product release.

## Goal
- run through publishing testing and document obstacles and performance tasks to improve future publishing

## Resources
[Wilkes-Barre Run Book](https://drive.google.com/drive/folders/1GC6PkeS-iIv1XijLCINW5J_1bo7tSO37)

## Tasks
Pre-launch confirmations:
- [x] Confirm Drupal FE environment is stable and building correct as expected in last 24 hours
- [x] Confirm with FE tools there are no competing builds (Dependent on Jenkins to determine)
- [x] Confirm with Platform FE there are no outstanding issues and we are OK to publish
- [x] Confirm that root URL has been added to robots.txt/blacklist (Disallow)

Begin Deploy

- [x] The Publishing and release of content for va.gov/Wilkes-Barre-health-care/
- [x] Open Deploy link to Jenkins and confirm which PR is associated to Publication
	- [ ] If there is an issue, validate issue in logs and try correction within 15 minutes.
	- [ ] If resolved start again, If not reschedule deployment and Schedule postmortem on Logs.
**After successful Deployment**
- [x] Confirmation Site is up and accessible
- [x] Left-Navigation bar is valid and working
- [x] Documenting any errors/bugs that need to be resolved
- [x] Determining if there are critical errors and rollback may be require
- [x] Schedule and document postmortem/process improvement areas

## Acceptance Criteria
- [x] https://www.va.gov/wilkes-barre-health-care/ is published
- [x] Left Nav is up and working and or issue initiated to fix any anomalies
- [x] Access to pages is confirmed and/or issue is initiated to fix any anomalies
- [x] Postmortem/lessons learned meeting is scheduled.
