### ISSUE TITLE
[Content-Review] Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA Fayetteville-Coastal health care [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19637]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Fayetteville-coastal Devshop Instance](http://fayettevillecoastalhealthcare.web.demo.ci.cms.va.gov/fayetteville-coastal-health-care/)
[VISN-6 Internal Review Folder](https://drive.google.com/drive/folders/1VV3WPyTJRccsay82aL-Roe3VbSUwGEkJ)
[Fayetteville_Coastal workbook](https://drive.google.com/drive/folders/1-ORUm-MtKEtohlBlJXV1Ssc_eWPpR-m1)

## Tasks
_Complete content review of system pages from a reader's point of view and make corrections in Production (prod.cms.va.gov):
**Use Analytics Review document to see changes already implemented**

* Review NOT needed (Double check if there is content on Jobs/Intern/Volunteer)
- [ ] Location Listing Page 
- [ ] History    
- [ ] Internship and Fellowship 
- [ ] Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [ ] System Page 
- [ ] Health Services Listing Page (Health service on this page only)
- [ ] About us Page 
- [ ] Mission-Vision 
- [ ] Leadership Listing Page 
- [ ] Work with Us Page 
- [ ] Jobs and Careers
- [ ] Policies Page 
- [ ] Contact us 
 
* Facility Pages - review intro, Plan for your visit, if any. (DO Not review health services this is at System level only)
- [ ] 565	Fayetteville VA Medical Center
- [ ] 565GA	Jacksonville VA Clinic
- [ ] 565GC	Wilmington VA Clinic
- [ ] 565GD	Hamlet VA Clinic
- [ ] 565GE	Robeson County VA Clinic
- [ ] 565GF	Goldsboro VA Clinic
- [ ] 565GG	Lee County VA Clinic
- [ ] 565GH	Brunswick County VA Clinic
- [ ] 565GL	Cumberland County VA Clinic
- [ ] 565QA	Robeson Street VA Clinic

* Observe and report (Correct any spelling errors)
- [ ] Performance Page
- [ ] Make an Appointment
- [ ] Register-for-Care
- [ ] Billing
- [ ] Contact-us		
- [ ] Dav-vans
- [ ] Medical-Records
- [ ] Operational Status
- [ ] Pharmacy
- [ ] Caregiver
- [ ] Homeless
- [ ] LGBT
- [ ] Mental
- [ ] Minority
- [ ] Patient
- [ ] Returning Service member
- [ ] Suicide prevent
- [ ] Women-vet
- [ ] Campus Map
- [ ] Chaplain Services

- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [ ] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.

**Comment by larrywest52** [comment]
Reviewed all pages, fixed what I could, and documented the rest. Posted the internal review document to our team's Google Drive.
