### ISSUE TITLE
Create a Blank Page on the 28-8832 (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19648]
## Background
Now that the CH36 feature is complete in staging, we have gotten feedback that the pdf is difficult to use in that chars are being separated out and copying is inconsistent.  While we are unable to have an impact on the PDF directly given our scope, we can replicate the data being entered onto a blank page so that the LoB can easily work with the PDF in the meantime.

## Considerations
- Include the label 
- Consider if the business will accept just the fields, and not worry about the "official" form

## Tasks
- [x] Add a blank page that allows for data to be replicated with labels

## Acceptance Criteria
- [x] A blank page has been created for the CH36 question responses to be stored upon PDF creation and saving.
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5955
