### ISSUE TITLE
Fetch appointments from the Lighthouse Health API 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#19656]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the backend to create an appointment service that will fetch all my relevant appointments from the Lighthouse's Health API

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- Currently, we're fetching a user/patient's appointments from the Mobile Appointment Service(MAS) in the MAP domain.
- We want to stop fetching appointments from the MAS, and instead, create a new service module on top of the already established appointment harness so that we can start requesting appointments for a user from the Lighthouse's Health API service.

## Tasks
- [x] Ensure that the access token request with the Lighthouse's Health API is successful and is being saved to Redis.
- [ ] Create a factory class for handling all high-level functions and dependencies.
- [ ] Create a class for handling all queries to the Health API's appointment endpoint.
- [ ] Create a presenter/serializer for packaging up the appointments data for the frontend.
- [ ] Add index route for fetching collections
- [ ] Add show route for fetching a single resource
- [ ] Write tests so that coverage is at ninety percent or more

## Acceptance Criteria
- [ ] Appointments are being fetched for a user by a given date range
- [ ] Ability to fetch a single appointment by a given appointment id
- [ ] Appointment has all of the relevant fields and data
- [ ] Signed off by frontend/UI
