### ISSUE TITLE
Return a validation error when a query parameter is missing

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19655]
## Issue Description
When a query parameter is missing the issue needs to be identified at the controller level 
@saneshark and @darkbushido introduced a quick hack / workaround in https://github.com/department-of-veterans-affairs/va.gov-team/issues/19625

## Tasks
- [ ] Return a validation error when a query parameter is missing

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
