### ISSUE TITLE
[FE] Update Appointment Structure from MAP to FHIR

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#19654]
## User Story

As a veteran, I should see my appointment that is coming from Lighthouse in the FHIR structure. 

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [JSON structure](https://gist.github.com/mdewey/13f6e42bbf9beda5dfc55fd26e7e1368)

## Description
With the migration from MAP to Lighthouse, the Appointment data is now in an FHIR compliant structure. 

## Tasks

- [ ] update test data
- [ ] create shared utils methods to get appointment data
   - [ ] appointment status
   - [ ] booking note
   - [ ] appointment type
   - [ ] appointment date
   - [ ] clinic name
   - [ ] clinic phone number
   - [ ] facility name
   - [ ] facility phone number
 - [ ] update questionnaire list 
   - [ ]  todo 
   - [ ] completed
 - [ ] update questionnaire 
   - [ ] intro
   - [ ] demographics
   - [ ] pre visit
   - [ ] confirmation
 

- [ ] Create unit tests
- [ ] Create e2e tests

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
