### ISSUE TITLE
Add or Update Copy for CH31 Orientation

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19652]
## Background
Now that the content for CH31's orientation pieces are agreed upon and complete, it is at the point where they can be brought into staging, so that that feature can engage with its remaining last mile activities ahead of launch.  Launch date moved by business to April 19, 2021.

## Considerations
- Mockup: https://xd.adobe.com/view/76c8e03c-ff8e-498b-ada5-0e2c08a8d8bd-239b/
- Check with Jim for a place to copy language easier

## Tasks
- [ ] Add or update orientation content for CH31

## Acceptance Criteria
- [ ] Latest version of content is in place
- [ ] A PR has been requested for merging

**Next steps**
- PM Walkthrough, stories
- 508 review: ask about transcripts
- GA review
- Staging review
- Privacy and Security Review
- QA Update
