### ISSUE TITLE
Create designs / template for links versus buttons

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#19666]
## Issue Description
Create designs / template for usage of links versus buttons 

Link to original ticket for reference. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/390

---
## Tasks
- [ ] Create designs
- [ ] Review designs 
- [ ] Update Sketch library with designs

## Acceptance Criteria
- [ ] Designs are approved
- [ ] Sketch library updated
---

**Comment by caw310** [comment]
In progress pending testing.
