### ISSUE TITLE
Continuous Integration (CI ) - Discovery for New CI Solution 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19663]
## Problem Statement 
The solution that we currently have in place (Jenkins) lacks a good high availability story, is cumbersome to use, difficult to understand, hard to update, and requires a steep learning curve. Additionally, there are multiple security concerns around our previously _proposed_ new solution for Continuous Integration which is CircleCI). Among those, are: 

- The VA does not support creating a unique namespace for things like publishing Orbs (used for easier administration, etc). 
- We are unable to use 3rd-party Orbs for security reasons. 
- We are unable to use contexts because we cannot create security groups to control access, which means that without contexts, credentials would be shared across all of the users in the VA.gov GitHub Org. 

How might we find a CI solution that integrates well with our current infrastructure and is scalable, flexible, reliable, and secure? 
How might we find a CI solution that provides the desired performance ie the ability to run tests in parallel? 
How might we find a CI solution that enables development teams to have autonomy when running their software through VSP's CI pipelines? 

## Hypothesis or Bet
Our hypothesis is that this initiative will allow for us to come up with the requirements for the new CI solution which better meets the needs of the platform both now, and in the future. 
Our hypothesis is that we can come up with a solution for CI that is in alignment with security and performance requirements. 

## We will know we're done when... ("Definition of Done")
- [x] We will have a decision in place on which tool to use for CI - [ADR005](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d0590431e9b119b9f17bd58cda508a92153e555f/docs/adr/0005-use-github-actions-for-vsp-platform-ci.md)
- [x] [Guidance for GitHub Actions Usage](https://vfs.atlassian.net/wiki/spaces/VI/pages/1147142190/Guidance+for+Github+Actions+usage)
- [x] [Self-hosted runners documentation](https://vfs.atlassian.net/wiki/spaces/VI/pages/1397194827/Self-Hosted+Runners) 

## Projected Launch Date
February 2021

**Comment by jhouse-solvd** [comment]
This discovery initiative is now complete. Please see HERE for ongoing work to facilitate the adoption of GitHub actions for CI on the platform. 

Closing.
