### ISSUE TITLE
[VAMC] Update Operating Status pages and associated to correct System pages [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19661]
## Task
- Find and/or create operating status pages and associate them to the correct System page for the following sites:

- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care

## Acceptance Criteria
* All systems have an operating status and that status is associated to the system page
* All social media links have been uploaded correctly.
