### ISSUE TITLE
TUD: Add sorting order to the accounts table

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19677]
## Issue Description
As a user of the TUD web application, I would like to have the ability to sort the Test User Account table so that I can find the account credentials I need more quickly.

---
## Tasks
- [ ] As a default, sort the list of accounts alphabetically/numerically (example: vets.gov.user+2@gmail.com **comes before** vets.gov.user+158@gmail.com)
- [ ] Sort the table by **Account** column field (Ascending & Descending).

## Acceptance Criteria
- [ ] I can see a list of accounts that are sorted alphabetically
- [ ] I can click on the **Account** column field to sort the data (Ascending or Descending)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
