### ISSUE TITLE
TUD: Move the Issues table to it's own page

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19681]
## Issue Description
As a user, I would like to be able to see an Issues page that contains information when ID.me or the Staging API is down, a table to troubleshoot issues, and a way to submit new issues so that I can quickly identify errors and issues when using a TUD account.

---
## Tasks
- [x] Move the Issue table in Documentation to a separate page
- [x] Add Statuses for ID.me and Staging to see their availability (aka when they're down or up; Joe has a good list [here](https://dsva.slack.com/archives/CSFV4QTKN/p1604681861118000).
- [x] Add more content to the Issues table and hook up the _Create a Ticket_ feature to Github.
- [x] Create templates in Github for specific issues to keep consistency

## Acceptance Criteria
- [x] I can navigate to the `/issues` endpoint and see content, 3rd-party statuses (ID.me & Staging API), and a list of issues in an accordion
- [x] I can click on the _Submit a Ticket_ link and I will be sent to the Github 'Submit an Issue' page with a pre-filled template for (Updating credentials for an existing user, Adding features/user attributes to a specific user, Create a request for a new user)
- [x] I have ensured proper accessibility & 508c testing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Created a Pull Request - ready for review
