### ISSUE TITLE
TUD: Add tab/pills based on the filters data

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19687]
## Issue Description
As a user, I would like to see tabs/pills (frequently called **pilters**) based on the filters selected in the Modal/URL bar by the Test Accounts table and be able to remove these 'pilters' easily, so that I can quickly filter test accounts without having to reopen the modal.

---
## Tasks
- [x] Create a container of 'pilters' that are based on the selected filters in the Modal
- [x] Create a pilter item that when clicked on (X-icon) removes the filter from the list of selected filters

## Acceptance Criteria
- [x] When adding filters from the modal, I can see a grouping of Pilter items
- [x] When clicking the close icon (X) on a Pilter item, it removes itself from the Filtered items
- [x] Ensure proper accessibility and 508c
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by APorter-Clarity** [comment]
![Screen Shot 2021-03-19 at 4.47.39 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/be4c41f4-69f1-49df-9b25-0f627b1ce529)

 I have the pills like this: 10px between text and x function, 16px between pills. 

- (Ideal function-> user closes the pills that do not fit their search and the table reload with the remaining selections. )
