### ISSUE TITLE
TUD: Add search bar to filter test accounts

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19685]
## Issue Description
As a user, I would like to be able to use a search bar that filters the Test User Accounts table so that I can find test account credentials quicker.

---
## Tasks
- [x] Add a search bar on the Test Account Matcher page (`/test-account-matcher`)
- [x] Filter the table based on the Search bar input (currently only filter the **Account** column, however this can expand and change in the future).
- [ ] 
- [x] Add the Search bar input as part of the query parameters. (**Note: this might not be needed as we're doing filtering on the frontend only)

## Acceptance Criteria
- [x] I can use the Search bar to filter the Test Accounts table
- [x] I can search by `first name` `last name` `email address`
- [x] I can clear the Search bar.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
