### ISSUE TITLE
TUD: Update content and documentation for the website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#19692]
## Issue Description
As a user, I would like to see appropriate definitions in the documentation (i.e. Account Type), a chevron for the table row dropdown, a reorganized landing page, a table column moved to LOA1/3 status, and review content to make more sense.

## Why
These requirements came from the usability testing on the Test User Dashboard website for Week 1.  These were varying remarks from different users and what Amanda and I discussed as appropriate design solutions.

---
## Tasks
- [x] Add a list of definitions for TUD properties (example: Account Type of Basic, Advanced, Premium).
- [x] Modify the row button dropdown to add a 'chevron' icon
- [x] On the landing page, reorganize the Test Account Matcher to go above the 'Getting Started' section
- [x] Add the `Age` user property in the dropdown section
- [x] Modify the table column of LOA1/3 field
- [x] Research and save all forms related to veterans (i.e. forms.json)
- [x] Update the content on the homepage so that it makes more sense

## Acceptance Criteria
- [x] All task items above are completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
