### ISSUE TITLE
Redesign KPI framework doc

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19708]
## Issue Description
We have a skeleton of the KPI Framework content, but it's currently sitting in a spreadsheet format. How might we design the framework to be easier to read so that more VFS teams will use it and want to use it to help their KPI setting process? How can we make the process easier?

---
## Tasks
- [ ] Design the [framework](https://vfs.atlassian.net/wiki/spaces/~173922865/pages/614531245/VA.gov+Analytics+-+KPI+Framework) 
- [ ] Prepare the design so that it can be shared with DEPO and VFS teams without Confluence
- [ ] Prepare the design so that it can be easily pulled into Confluence when Confluence is sharable

## Acceptance Criteria
- [ ] The design allows users to easily find the metrics they need, why they need them, and how they can use those metrics.

**Comment by joanneesteban** [comment]
Mandy started a draft [here](https://docs.google.com/document/d/1_dlEG53GfCuhuwozdityGIP8xyJny2mffmePF4Fg2cI/edit?ts=601b4cd9#heading=h.dmjefxrr0nu0)

**Comment by joanneesteban** [comment]
Draft linked above can be used for a redesigned framework. This work was pivoted in favor of the KPI Dashboard standardization initiative. We're planning on doing a documentation audit in Q3 of 2021. Closing this ticket.
