### ISSUE TITLE
Determine baseline metrics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19709]
## Issue Description
As VFS teams have been setting up their KPIs, we have been asking them to set baselines so that they have targets/accountability for the KPIs. They often ask us what those baselines should be, or how to calculate them. How might we make the process for determining KPI baselines easier for VFS teams?

---
## Tasks
- [ ] Determine if we can set baselines for our suggested KPIs
- [ ] Document those baselines,  if possible
- [ ] Determine & document how teams can set their baselines on their own

## Acceptance Criteria
- [ ] We understand and can share what common baselines are, or how VFS teams can calculate them on their own

**Comment by joanneesteban** [comment]
Using VA.gov-wide averages. Closing this ticket.
