### ISSUE TITLE
[VAMC] VISN-5: "West Virginia VISN" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19717]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-5](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Clarksburg health care
- [ ] VA Martinsburg health care
- [ ] VA Maryland health care
- [ ] VA Washington DC health care
- [ ] VA Beckley health care
- [ ] VA Huntington health care

Facilities include for System:
VA Clarksburg health care
- [ ] vha_540	Louis A. Johnson Veterans' Administration Medical Center
- [ ] vha_540GA	Tucker County VA Clinic
- [ ] vha_540GB	Wood County VA Clinic
- [ ] vha_540GC	Braxton County VA Clinic
- [ ] vha_540GD	Monongalia County VA Clinic
- [ ] vha_540HK	**Clarksburg VA Mobile Clinic

VA Martinsburg health care
- [ ] vha_613	Martinsburg VA Medical Center
- [ ] vha_613GA	Cumberland VA Clinic
- [ ] vha_613GB	Hagerstown VA Clinic
- [ ] vha_613GC	Stephens City VA Clinic
- [ ] vha_613GD	Franklin VA Clinic
- [ ] vha_613GE	Petersburg VA Clinic
- [ ] vha_613GF	Harrisonburg VA Clinic
- [ ] vha_613GG	Fort Detrick VA Clinic

VA Maryland health care
- [ ] vha_512	Baltimore VA Medical Center
- [ ] vha_512A5	Perry Point VA Medical Center
- [ ] vha_512GA	Cambridge VA Clinic
- [ ] vha_512GC	Glen Burnie VA Clinic
- [ ] vha_512GD	Loch Raven VA Medical Center
- [ ] vha_512GE	Pocomoke City VA Clinic
- [ ] vha_512GF	Eastern Baltimore County VA Clinic
- [ ] vha_512GG	Fort Meade VA Clinic
- [ ] vha_512QA	Baltimore VA Clinic

VA Washington DC health care
- [ ] vha_688	Washington VA Medical Center
- [ ] vha_688GA	Fort Belvoir VA Clinic
- [ ] vha_688GB	Southeast Washington VA Clinic
- [ ] vha_688GD	Charlotte Hall VA Clinic
- [ ] vha_688GE	Southern Prince George's County VA Clinic
- [ ] vha_688GF	Montgomery County VA Clinic
- [ ] vha_688GG	Lexington Park VA Clinic
- [ ] vha_688QA	Franklin Street VA Clinic

VA Beckley health care
- [ ] vha_517	Beckley VA Medical Center
- [ ] vha_517GB	Greenbrier County VA Clinic
- [ ] vha_517HK	Beckley VA Mobile Clinic
- [ ] vha_517QA	Princeton VA Clinic

VA Huntington health care
- [ ] vha_581	Hershel "Woody" Williams VA Medical Center
- [ ] vha_581GA	Prestonsburg VA Clinic
- [ ] vha_581GB	Charleston VA Clinic
- [ ] vha_581GG	Gallipolis VA Clinic
- [ ] vha_581GH	Lenore VA Clinic
- [ ] vha_581QA	Huntington Ninth Street VA Clinic
- [ ] vha_581QB	**Huntington VA Mobile Clinic

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live
