### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Martinsburg health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19712]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Martinsburg healthcare system Legacy Site](https://www.martinsburg.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-5 Playbook locations](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_613	Martinsburg VA Medical Center
- [x] vha_613GA	Cumberland VA Clinic
- [x] vha_613GB	Hagerstown VA Clinic
- [x] vha_613GC	Stephens City VA Clinic
- [x] vha_613GD	Franklin VA Clinic
- [x] vha_613GE	Petersburg VA Clinic
- [x] vha_613GF	Harrisonburg VA Clinic
- [x] vha_613GG	Fort Detrick VA Clinic

## Staff Profiles for the the following Health Service Programs
- [x] Leadership Page
- [x] Caregiver-support
- [x] Homeless-Veteran-Care
- [x] LGBT-Veteran-Care
- [x] Mental-Health_Care
- [x] Minority-Veteran-Care
- [x] Patient-Advocates
- [x] Returning-Service-Member-Care
- [x] Suicide-Prevention
- [x] Women-Veteran-Care
* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
- [ ] All Staff Profiles have been documented for Analytics for creation of Health Service pages.

**Comment by bcastoe** [comment]
Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Martinsburg health care [BA]#19712

02182021 - Martinsburg Playbook created and all Health Services matched up to 95 Health Service list/staff profile is on hold

**Comment by bcastoe** [comment]
02222021 - Martinsburg Caregiver/Coordinator data collected and data loaded to Drupal; completed and moved to validate
