### ISSUE TITLE
[Design] DD4edu UAT Conversation Guide

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19729]
## Background
We need to create a conversation guide to go with the research plan for UAT.

## Tasks
- [x] Create conversation guide
- [x] Review with Matt/Samara/Jason

## Acceptance Criteria
- [x] Share with Auth Exp + Lauren ALexanderson

**Comment by sporeboy** [comment]
Convo guide stubbed here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/uat/dd-edu-uat-convo-guide.md

Content commented-out for now.

**Comment by Samara-Strauss** [comment]
> "During this call, I'll be helping you navigate a form that can change your direct deposit information. So, can you confirm that you indeed would like to do this, and are comfortable walking through the form on the call?"

You can explain that we'll stop screen-sharing during the portion where they actually enter their bank information, so we won't be able to see their private bank info. Also, we should confirm that they have access to their routing/bank number in order to fill out the form. My guess is people will have to go get it.

> Look at the links to the left; click on "Direct deposit information."

- Please add **UAT item**: User sees Direct deposit information in the profile side nav.

> Review/enter your bank information.

We do need them to enter their bank information. **However**, they can stop the screenshare at this time, and then resume the screenshare after they have submitted the form.

> Please review/enter your bank information once more.

Why are we having them do this a second time?

**Comment by sporeboy** [comment]
Regarding the screenshare issue, I have a paragraph addressing this:
>So today we're going to observe you navigating to the direct deposit feature. There, we'll ask you to review your bank information and re-enter it. If you choose, you can turn off video for this. We're not recording this session, but we need to see your screen as you go to the form. The form **does** ask for personal financial information. Are you comfortable sharing your screen? Would you like to turn off video while you re-enter your bank info? 
- If not: Explain this is necessary for testing. If they are still unwilling (e.g. because of personal info), end the call.
Do you want to just make turning off video mandatory?

I added the UAT item regarding the LH nav link.

We ask them to review again to confirm that nothing weird happened when they "re-entered" their info.

**Comment by Samara-Strauss** [comment]
> Regarding the screenshare issue, I have a paragraph addressing this:

Got it! Sorry I missed it.

> I added the UAT item regarding the LH nav link.

Sounds good!

> We ask them to review again to confirm that nothing weird happened when they "re-entered" their info.

Sounds good!

**Comment by Samara-Strauss** [comment]
Done! Materials have been submitted to Lauren for recruiting.
