### ISSUE TITLE
[Design] Direct deposit for edu: Conduct UAT Research

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19732]
## Background

Following a successful UAT Go/No-go meeting we can start conducting UAT sessions for direct deposit for EDU.

## Tasks
- [x] Update Convo guide on email issue
- [x] Conduct UAT
- [x] Upload results to Github

## Acceptance Criteria
- [x] All notes are codified in GH under the feature folder
- [ ] Create or start any tickets for any issues found in

**Comment by jason-gcio** [comment]
@mshea0606 - Just a heads up, I moved this ticket back to Ready since I am not sure when Perigean will be contacted for scheduling.

**Comment by Samara-Strauss** [comment]
[UAT results posted here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/uat/dd-edu-uat-results.md). Closing!
