### ISSUE TITLE
[FE] Build the Claims and Appeals section

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#19742]
## Background
This section should load its own data using the `getClaimsV2` and `getAppealsV2` actions

## Tasks
- [ ] build an "alert/CTA" component that can display all the potential claims and appeals statuses
- [ ] Add loader for the loading state when loading data from claims and appeals APIs
- [ ] It's possible that after loading all data this component will render _nothing_ because all claims and appeals on record have been closed for over 30 days!
- [ ] tests that confirm it's only shown when it should be

**Comment by ajakabcin** [comment]
Complete
