### ISSUE TITLE
[FE] [SPIKE] Wording of the confirm submission message

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#19746]
## User Story

As a veteran, I should be able to try again to download my successfully answered questionnaire. 

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Related Ticket]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/19024#issuecomment-776751637)

## Description

**from ticket**
On the confirmation page I see the error in printing. I follow the instructions in the message which says to refresh the page. Page refresh takes the user to the Ques. Manager Todo tab. I get why its doing that but just thought I'd check if there was a way on page refresh if we can't stay on confirmation page can they at least be directed to Completed tab? @kristenmcconnell if you have another idea throw it out. Also not worth holding up this ticket from completion we can add a new ticket if we decide to change the flow.

## Tasks

- [x] See if we can refresh the page and still stay on the confirmation page
- [x] If we can not, is there a different try again function?
- [ ] Create user tests
- [ ] Create e2e tests

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by abuckley3385** [comment]
@kristenmcconnell  recommend to go to the completed tab if possible. Needs investigation to determine what our options are by @mdewey

**Comment by mdewey** [comment]
First answer: We are not able to stay on the confirmation page for two reasons

1. The form system doesn't allow a user to start on the confirm page. 
2. We are clearing the session data on the confirmation page. This data is cleared when the user encounters a page and is lost on a refresh.

**Comment by kristenmcconnell** [comment]
Taking them to the completed tab is great. I would change the error message wording on the submission page as a result.

**We've run into a problem viewing and printing your questionnaire**
We're sorry. Something went wrong on our end. Please try again from [your list of completed questionnaires](url).

**Comment by mdewey** [comment]
@kristenmcconnell  and @abuckley3385. How does this look ?

**Comment by kristenmcconnell** [comment]
@mdewey Good to me.
