### ISSUE TITLE
Documentation - EKS 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19744]
## Description
Make sure developers understand how we use Kubernetes in our environment.
- How to onboard a new project
- Application Manifest documentation (How to make a simple application manifest, etc)
- CI documentation (what CI needs to output to manifest)
- ArgoCD documentation (logging in, interacting with applications)
- How to use Kubernetes secrets in your application repo (external-secrets, parameter store)

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Write documentation_
- [ ] Peer review / Edits

## Definition of Done
- [ ] _Developer documentation for EKS is written and available to developers_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Please see more recent initiatives around "App Hosting and Deployment..." where we will be adding documentation, product outlines, and other artifacts as we work through customizing the solution for various audiences. 

Closing.
