### ISSUE TITLE
EKS - Migrate Grafana service into utility cluster 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19747]
## Description
In order to move the Grafana service away from the legacy infrastructure deployment system (BRD), Ops is moving Grafana to EKS, and then decommissioning the previous installation. 

## Background/context/resources
Grafana currently in BRD will move to EKS

## Technical notes

- Grafana will go into the utility cluster
- Grafana will be still available via the existing URL - https://grafana.vfs.va.gov)
- Grafana database will remain the same 

---
## Tasks
- [x] Set up app manifest
- [x] CD Pipeline
- [x] URL routing 

## Definition of Done
- [x] Grafana has been fully migrated to EKS
- [x] Legacy Grafana (BRD) has been de-commissioned 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by tskinn** [comment]
Grafana is now running in the EKS utility cluster with functioning CD pipeline. (grafana repo pushes changes to app manifest repo and argocd deploys grafana)

The new grafana uses the same database as the current grafana and making the switch should be fairly painless. Jeremy is planning on doing a soft open tomorrow to see if we run into any issues. This just involves updating the ALB routing to point grafana.vfs.va.gov to the new setup. It is easily rolled back.

**Comment by jbritt1** [comment]
This is what is currently being served to the masses in our soft rollout (simplified flowchart of migration plan can be found [here](https://vfs.atlassian.net/wiki/spaces/VI/pages/1177780240/Grafana+Migration)).

**Comment by jbritt1** [comment]
Need to discuss on when we are to take down the older infrastructure pieces for BRD-Grafana.

**Comment by jhouse-solvd** [comment]
Now that the new Grafana service is functioning and stable, and prompted by a couple of minor issues that were spotted with having both the legacy and new apps running simultaneously, we are now moving to decommission the legacy instance so that this task can be considered complete.

**Comment by jbritt1** [comment]
Old BRD Grafana taken down fully at this time.

**Comment by jhouse-solvd** [comment]
Thanks, @jbritt1! Great work. Closing.
