### ISSUE TITLE
SPRINT 41 PRIORITIES

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19752]
## Instructions for first few sprints using this priority document:

- This is a living document that everyone is empowered to keep updated.  
- If you complete a task, please come here to check if off.  If you add a new issue or run across something that needs to be discussed in the next grooming session, please include add it to Discussion Topics/Grooming.

## Sprint 41 Priorities

1. 🥳 ~Get **Yellow Ribbon search tips** (includes Google Analytics event tags) into Production - note: On Staging now; good to go as soon as we give thumbs up.~ Will  deploy initially without GA tags reviewed, but will be a quick follow on week of 2/15.
2. 🎉 ~Get **Find a VA Form results sorting feature  (including A-Z, Z-A change and sorting bug fix)** into Production~
3. ~Update End to End test for Yellow Ribbon FE. ~
4.  ~Implement Google Analytics data layer event code for Yellow Ribbon~
5.  ~Break down Find a VA Form search improvements into tasks and estimate~
6. ~Monitor bugs CMS, Lighthouse, VA Forms Mgrs are working on~
7. ~Complete consolidated on-site search and Find a Form search query top searches data sheet (de-duped) so we understand fully what forms are being searched the most.~
8. Complete the [GH read-me](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/top-forms.md) which captures the top searched Forms and indicate if they have an online tool link as well as 

<hr>

#### Zach
- [x] ADP Training

#### Marci
- [x] ADP Training

<hr> 

#### Zach
- [x] Update Sort to include Sorting by A-Z and Z-A. #19507  🥳 
- [x] Correct persistent bug that is causing sort not to work on some browsers: #19429
- [x] Find a VA Form - Remove sort feature toggle, do PR, deploy to Prod #18950
- [x] ❔ Find a VA Form [Discovery] Break out tasks needed to improve search string matching #19601

#### Laurel

- [ ] Find a VA Form [Discovery] Break out tasks needed to improve search string matching #19601

#### John
- [x] Stakeholder meeting Fri 1/12/2020

#### Marci
- [x] Stakeholder meeting Fri 1/12/2020
- [x] Cross-reference/de-duplicate VA.gov searches against form-specific searches
- [ ] Diagram of testing/deployment process
- [x] Find a VA Form [Discovery] Break out tasks needed to improve search string matching #19601
- [x] Monitor bugs Lighthouse & CMS are working on
- [x] Monitor Analytics KPI dashboard request for Decision Tools Team - Find a VA Form #19689
- [x] Monitor CMS/PW reply to #8248, untag us if needed. **Update - I removed our team from this ticket; the original description states that it needs to be remediated by VSP**
- [x] Monitor CMS/PW reply to #8250, untag us if needed.   **Update - I removed our team from this ticket; the original description states that it needs to be remediated by VSP**

<hr>

#### Zach
- [x] Yellow Ribbon: Incorporate search tips message into YR Search #18854  🥳 
- [x] Yellow Ribbon: Incorporate -ALL- Yellow Ribbon search GA code per Analytics specifications #18234
- [x] Deploy search tips to Prod (pre-Analytics review - we won't look at Feb metrics since it's mid-month)  🥳 
- [ ] Analytics Review on Staging
- [ ] Re-deploy search tips to Prod post-Analytics review

#### Laurel
- Nothing

#### John
- [x] Review search tips on Staging prior to go-live.

#### Marci
- [ ] Domo Dashboard/Reports Request for Yellow Ribbon **Create new ticket**  - Moving to next Sprint since event code is not yet in Production.  Need to generate basic reports to use for reference in the request.

### 🛠️ Technical Debt / A11y Issues
**Our goal is to include 1-2 tech debt issues into each sprint.**

#### Zach
- [x] Update End to End test for Yellow Ribbon FE. #19332

<hr>

#### CMS
CMS Backlog:  department-of-veterans-affairs/va.gov-cms#4083 | Original issue #18920 

#### Lighthouse 

- [ ] [Bug] Online tool button missing on some forms detail pages in Staging #18728 note: John has found & commented re: some that are also missing in Production. 
- [ ] [Bug] Find a VA form search is showing duplicate listing of VA Form 10182 #17484
- [ ] [BUG] Find a VA Form: "Related to" information missing on some results #19561

#### VA Forms Managers

- [ ] Find a VA Form [BUG] - Invalid character in VA DB PDF URL is causing "not found" error. #18926

<hr>

**Comment by zacharymorel** [comment]
Wow, what a template this is....

**Comment by MarciMcGuireGCIO** [comment]
I had put a bunch of stuff at the end that was related to the Collab Cycle, but I took it out.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel since this is a new tool we’re using, just pinging you to check off the tasks you completed with the sort launch. I also clarified the remaining items for Yellow Ribbon
