### ISSUE TITLE
Update Header Level

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19755]
## Background
While the headers in the platform component need to be adjusted, we can still update the **blue rated disabilities box** in the CH36 feature.

## Considerations
- Josh's ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16692

## Tasks
- [x] Update the headers

## Acceptance Criteria
- [x] Headers are updated
- [x] A PR has been requested for merging

**Comment by micahchiang** [comment]
Blocked until 16692 is complete.

**Comment by jason-gcio** [comment]
Josh's ticket should be done first to avoid duplicate work
