### ISSUE TITLE
Global Blacklisting Typeahead Suggestions 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#19763]
## Description
A meeting with search.gov on Feb 5 resulted in a set of questions which were emailed over to the search.gov team. Along with their responses a data dump of all typeahead suggestions. This list of suggestions includes terms we would like extract from the suggestion list. This issues is aimed at working through the details to identify those terms and align with search.gov team to remove them. 

## Background/Context/Resources
[Search + Discovery Team questions and Search.gov responses](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/type-ahead/search-gov-meeting-notes.md)
[SAYT Suggestions Export.csv](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/assets-docs/VA.gov%20-%20SAYT%20Suggestions%20Export.csv)

## Tasks
- [x] Define follow up questions for search.gov team
- [x] Define strategy to identify terms from data dump provided by search.gov [SAYT Suggestions Export.csv](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/assets-docs/VA.gov%20-%20SAYT%20Suggestions%20Export.csv)
_Search & Discovery team discussed a potential strategy to tackle the 34,000 terms in the suggestion list. Initial thoughts are to start exploring the top 50 search terms from [Search term audit ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/audit/Search%20%26%20Discovery%202020%20Audit%20Summary.pdf) and review what suggestions appear and modify accordingly._
- [x] Review and discuss search.gov responses. 
- [x] Connect with Search.gov to align on strategy before any refinement is made to suggestions list. (Discussion Questions:How can you make edits, what format do you need, what scale)
- [x] Identify list to be reviewed ( Plan to star by reviewing 2020's Top 50 queries for the year and removing the obviously low quality suggestions)
- [x] Exploration to determine ways to automate process
- [x] Create and share a sample for search.gov discussion(2/19)
- [ ] Search.gov agreement to implement the expected lists
- [ ] Establish plan to review the list of terms and share the changes with search.gov. This will be an ongoing effort over the next several weeks; slowly improving the quality of typeahead suggestions for the top 50 search terms from 2020

## Implementation Plans
|**Action**         |**SD Team Delivery Goal**         |**Search.gov Implementation Goal**|
|-----------------------|------------------------------|------------------------------|
|**"Round 1"**- Sample (quick pass + location check) |Feb 19 |March 5  |
|**"Round 2"** (Full Review of 3800 terms - including city since only states will be removed by search.gov)             |April 16 (end of S43) |April 30 |
|**"Round 3"** (New terms to be added)            | April 20  (end of S45) | May 14|
|**"US States"**- Search.gov removal of State (full name and acronym) references from suggestions           |n/a |Feb 26  |

## Definition of Done

- [ ] All phases of the implementation plan have been completed and all terms have been sent to search.gov to improve the quality of the typeahead suggestions

**Comment by denisecoveyduc** [comment]
This is an extensive piece of work that will require several sprints to wrap up and coordinate with Search.gov for implementation. The search & discovery team will continue to refine the quality of the typeahead suggestions by blacklisting terms and sending to the Search.gov team for implementation until the work is complete. As a result this issue will continue to roll over with incremental changes along the way.

**Comment by denisecoveyduc** [comment]
The typeahead suggestion database was a list of over 40,000 terms which we had planned to review - blacklisting many of the suggestions which did not offer any value to the users. 

Search.gov however resolved a bug fix which was preventing suggestions older than 30 days from being purged from the database. The Search & Discovery team was not aware of this bug and assumed that the search.gov algorithm was working as described. 

After the bug was resolved the database was purged which dropped the suggestion list down from 40,000 to 39 terms. Blacklisting is no longer required but instead we are pivoting our efforts to establish  list of terms that can be added to the suggestion database. We believe VA specific / targeted suggestions will improve the users ability to find relevant VA results.
