### ISSUE TITLE
Remove broken link from sign-in screen and R&S pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19760]
## Issue Description
There is a broken link on the Sign in to VA.gov screen that needs to be removed. 

It's the last link in the text box that says "Submit a request to get help signing in"

This link also needs to be removed from the R&S page [Signing in to VA.gov](https://www.va.gov/resources/signing-in-to-vagov/). It's the second CTA button and is also a link in the third, fourth, and fifth questions. 

## Tasks
- [x] Remove sentence with link from sign in screen (Nick)
- [x] Remove links from R&S page (Randi)
- [x] Review and publish R&S page (Randi)

## Acceptance Criteria
- [x] Broken link no longer showing on live site

**Comment by RLHecht** [comment]
This work has been completed. Closing ticket. @ncksllvn I don't know if you want to spin up another ticket for the other work you had to do for this since it was so extensive.
