### ISSUE TITLE
Dependency Verification - Add Redux Infrastructure

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#19766]
`app directory needs to be created (separate ticket) first`

## Description
As a user, I want to know that my dependents are up to date with VA so I am the right amount of compensation. 

## Tasks
- [ ] Add redux reducers and actions that can handle the api call to `vets-api` for dependents status.

## Acceptance criteria
- [ ] Actions and reducers have been added
- [ ] Dummy api call has been stubbed
- [ ] A PR has been requested for merging
