### ISSUE TITLE
🚢 Migrate "Modify Dependents" (Submit 686c and 674) from eBenefits to VA.gov

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#1976]
# Modify Dependents
eBenefits URL: https://www.ebenefits.va.gov/ebenefits/dependents

**Staging URL:** https://staging.va.gov/view-change-dependents/add-remove-form-686c/

**Production:**
Static landing (Drupal): https://www.va.gov/view-change-dependents ([Ticket via PubWeb](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8012))
View dependents: https://www.va.gov/view-change-dependents/view
Online form application: https://www.va.gov/view-change-dependents/add-remove-form-686c/ 

## Story
As a Veteran I want to add, update, or remove dependents to/from my benefits so that I can make sure that they and I get the benefits we've earned.

## Considerations
- Involves VA forms VA 21-686c and VA 21-674 Part 1
  - Does not involve other parts of 674, the 674b, or any other forms.
- The first form submission workflows we've worked on, requires true research and service design
- [Prior vets.gov sprint teams advanced this work quite a bit](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9306), make sure to connect with people who know about this work!
- [Outline of workflows](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce)  
  - [x] **Task Selection Wizard** 
    - [x] Mockup  
    - [x] Workflow  
    - [x] Unit test
  - [x] **Veteran Information**  
    - [x] Mockup  
    - [x] Workflow  
    - [x] Unit test
  - [x] **Add spouse**  
     - [x] Mockup  
     - [x] Workflow 
     - [x] Unit test   
   - [x] **Veteran marriage history** _(part of Add spouse part 3)_
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test 
   - [x] **Veteran Divorce**
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test 
   - [x] Add Child 
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test 
   - [x] Child in School (674)
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test 
   - [x] **Stepchild Leaves**
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test
  - [x] **Dependent Death**
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test 
  - [x] **Child Married**
     - [x] Mockup
     - [x] Workflow  
     - [x] Unit test
   - [x] **Child leaves School**
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test 
   - [x] **Additional Evidence / Uploads**
     - [x] Mockup
     - [x] Workflow 
     - [x] Unit test 

## Definition of Done
**(Tentative, WIP)**
- [x] The Veteran must be able to submit forms VA 21-686c and VA 21-674 Part 1
- [x] RBPS is able to automatically approve claims that do not need manual intervention

## Pilot Tasks
- [x] Research: What is the current process like? How do Veterans use this feature today? What is the turnaround processing time? What are the baseline metrics? What improvements could be made?
- [x] UX: Current journey map, identify gaps and pain points
- [x] Design: New service design based on research outcomes
- [x] Engineering: Discovery on similar flows in the product line, discovery on existing work, discovery on existing integration points
- [x] Build out pilot product

## Further Tasks

- [x] Investigate the use of other file types for additional evidence and their support in the 686 application
- [ ] Think about setting up a BE response to communicate to the user the upload status as it can take up to 1 minute to fully submit into BGS
  - What happens if: 
    - The Veteran closes the page, (SIP)
    - thinks its broken? etc (Help line)
  - What happens now? (Messaging about receipt)
    - It will show spinner for a second, then looks like it submitted successfully.  If it fails after that, even in part it will reattempt, but there is no messaging about it. (Silent failures send an email to the Veteran with instructions)
