### ISSUE TITLE
Add Schema and uiSchema for Remove Dependent Parent Workflow to Manage Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19770]
## Background
Now that we have used schemaform to create a basic form, we need to add schemas and uiSchemas that support the removal of a dependent parent from award.

## Considerations
- [mockups](https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/f272c2e9-8983-4228-8bab-916eede80e0a?x_product=cc-slack%2F1.5.1) [(parent)](https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/b0af32a2-f1d7-4aa6-9aff-959a8ee1ae2b?x_product=cc-slack%2F1.5.1)

## Tasks
- [x] Add schema and uiSchema for `remove a parent` 
- [x] Submit a PR for review

## Acceptance criteria
- [x] Schemas and uiSchemas have been added for removing a parent
- [x] A PR has been submitted for review
