### ISSUE TITLE
[Derek: Update] Create Service for Diary Entry

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19777]
## Background
We have a PR that was recently merged in the `bgs-ext` gem that allows us to update diaries for a user/veteran. We need to add a service to `vets-api` that leverages that `bgs-ext` gem diary update call

## Considerations
The tricky part is we have to send back _ALL_ of the diaries the person has along with the updated one. If we don't, we will erase all the unsent diaries. 🤯 

## Tasks
- [ ] Talk to FE about what is being sent
- [x] Service gets an interface

## Acceptance Criteria
- [x] A PR has been submitted to `vets-api` if possible
