### ISSUE TITLE
TUD API - return user login information

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#19786]
## Issue Description
The TUD frontend app will include a feature to allow someone to select a test user account and be redirected to staging.va.gov's login page with the proper login credentials pre-filled into the login form. The backend will supply an API endpoint that allows the frontend app to request the appropriate user account login information.
---
## Tasks
- [ ] An API endpoint is created that returns the test user account's UUID and password based on the va.gov login method selected (ID.me, DSLogon, MHV)

## Acceptance Criteria
- [ ] The frontend TUD app can request a test user account's login information and receieve it from the DB
- [ ] If a request is made to check out a user that is marked as checked out an exception will be raised

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
The TUD API will now return each `tud_account`'s login information (email, IDP, password) as part of the general index method, so this story will no longer be necessary; the TUD frontend app will already have the information it needs about an account in order to perform its login functions.
