### ISSUE TITLE
Public Websites: Sprint 42 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#19793]
## Sprint 42 Priorities
1.  Finalize CLP build tweaks/fixes (learn from Stakeholder UAT, finalize QA, Internal Security Testing, Staging Review Prep)
2. Resources and Support Enhancements - Video / Tags / Search
3. Work 'Tech-Debt' items from backlog
4. Intake Requests for February along with some applicable Tech Debt (508/a11y issues)
5. Discovery for feature adds to R&S along with 

### Capacity Planning: PTO/Holiday's
John: 0
Brian: 0
Nick: 0
Kelson: 0
Cassandra: 0

### Campaign Landing Page MVP 1.0
- [x] [PM/PO] Campaign Landing Page VSA-QA Test Plan #19554
- [x] [PM] Update 'Release Plan' artifact ISO Staging review
- [x] [PO] Finalize User Guide / On-boarding process flow
- [x] [PO] Product guide (John)
- [x] [PO/PM] Collab Cycle review with VSP. (Discuss how VSP works with Mikki, Peggy, Shira)
- [ ] [PO/PM] CLP Request Form (John/Brian/Kevin (CMS)
- [ ] [FE] CLP Refinement Punch List - Stakeholder Review #20338 [Place Holder Ticket] 
- [x] [FE] Full Accessibility & 508 Office Audit [Public Websites - Campaign Landing Page] #20436 reviewed by Josh Kim prior to FE Build? [#18756]
- [x] [FE] Back to Top Component [#20407]
- [x] CLP Bug - Preview-page Events section are missing description-paragraphs below event-titles. #20631
- [x] [Campaign Landing Page] Add feature flag for Mission Act page #20632

### Resources and Support
Priority R&S Breakdown: WIP  [MVP 1.1 EPIC #15588] [Iterate Search EPIC #15584] [Iterate New Feature #20332]
- [x] [FE] Enhancement: RS mobile views, left margin is too smooshed to the edge and cutting off text #17470 
- [ ] [FE] Implement Videos template mobile UX and progressive enhancement #15605
- [ ] [FE] Update Tags component layer with new meta data field #16623
- [ ] [FE] Add whole phrase matching logic to RS search (learning center) #16916
- [ ] [FE] Related information FE not matching design (learning center) #15272
- [ ] [FE] Bug: Articles listings and RS search listings are showing weird html tag text #17779
- [ ] [FE] Chrome bug: Yellow line showing on some RS pages #18570

### Sitemap SEO Discovery
- [ ] [FE] VA.gov Site Map XML & Template Structured Data Issues #20170 

### Cerner 
- [x] [FE] Remove feature toggles (Auth/Unauth Cerner Pages) #20442

### Discovery (Research & Design)
- [ ] [DISCOVERY] Send to Mobile R&S Enhancement #20331
- [ ] [CLP Design] CLP background alternating panel color to optimize UX [new ticket]

### Intake Request - Techical Debt
- [ ] [FE/Content] Explore and revisit Visual Regression Testing to aid in modifications to CMS templates and style #18869
- [ ] [Tech debt] Delete deprecated CMS code #19722
- [x] [Content]  Content Support for Static HLR Page from Claims and Appeals #18876 (Sitewide Content Team WIP)
- [ ] [FE] Pager Component for Outreach Event Page #19292 (Validate)
- [x] CMS [COGNITION]: Multiple ambiguities with linked text in content block #3556
- [x] Documenting Templating/GraphQL Approach (Smaller Queries Approach) #20539

### Discussion Topics/Grooming 
- [ ]  Bug: Articles listings and RS search listings are showing weird html tag text #17779 
- [ ] Chrome bug: Yellow line showing on some RS pages #18570
- [ ] Talk to Public Websites about better BDD landing page PLACEHOLDER #18641
- [ ] 508-defect-3 [AXE-CORE]: Aside must not be contained in another landmark #20236
- [ ] [Public Websites Bug] VA.gov T&Cs for MHV login #20608
- [ ] Typo fixes for VCL modal from Sitewide content #20610
