### ISSUE TITLE
Create a Research Plan and Conversation Guide for LGY: COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19798]
## Goal
The initial plan for getting the Certificate of Eligibility for the LGY folks in motion is to talk to Veterans about what pain points and opportunities there are for improvement so that we can ensure we are building the right thing to get Veterans the loan benefits they deserve.

## Considerations 
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)
- There are several workflows that need to be looked at as well as a few hypotheses that need to be validated.

## Task
- [x] Document a research plan to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/discovery-research-plan.md)):
  - Research method (moderated user interviews)
  - Participants & Recruitment
  - Timeframe
  - Team Availability
  - Roles (include emails)
  - Seek review before implementation
- [x] Coordinate with Shawna on some of the questions to ask in the conversation guide
- [x] Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-convo-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
## Acceptance Criteria
- [x] Research Plan and convo guide is ready for review by [Lauren Alexanderson in Recruiting](https://dsva.slack.com/team/U772MC9BQ) ([email](mailto:lauren.alexanderson@va.gov)) and Shawna

**Comment by sporeboy** [comment]
Initial commit of stubbed research plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/discovery-interviews/coe-discovery-research-plan.md

**Comment by sporeboy** [comment]
Research plan and conversation drafts are available for review.

Research Plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/discovery-interviews/coe-discovery-research-plan.md

Convo Guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/discovery-interviews/coe-discovery-convo-guide.md

**Comment by sporeboy** [comment]
Reviewed by Shawna; feedback implemented.
