### ISSUE TITLE
Update 686 for Death of a Child

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19801]
## Background
For 686 Dependency testing, we want to test that RBPS sets the status to `MANUAL` when removing a child due to death.  Currently, we skip creating the relationship if the dependent type is `Child` because RBPS does not have the functionality in place to process child removals automatically.  

## Tasks
- [x] Remove the check for `Child` relationship type and allow the process to continue normally.

## Acceptance Criteria
- [x] The `Child` removal workflow is updated
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5907
