### ISSUE TITLE
Create Discovery Docs for LGY: COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19800]
## Background
As we explore some of the pain points and improvement opportunities for the Certificate of Eligibility feature, we want to ensure we are mapping out all the right things, including: user flows, top-funnels, interaction points.

## Considerations
- Make a note of the stories in the Epic (#19595)

## Tasks
- [x] Create a journey map at a high (thumbnail) level of the e2e path
  - [x] auth vs unauth
  - [x] Immediate eligibility
- [x] Document requirements for auto eligibility

## Acceptance Criteria
- [x] Initial docs have been created and shared with the team and stakeholders for further discussion

**Comment by sporeboy** [comment]
Outlined discovery, formatted readme.md: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/readme.md

**Comment by sporeboy** [comment]
Created current and future flow diagrams: https://xd.adobe.com/view/6c65f5c2-36e1-4051-81be-6f8b9415a3cd-3936/

**Comment by sporeboy** [comment]
Use case diagram added. Next draft of discovery doc available with inline graphics.

**Comment by sporeboy** [comment]
No visibility into automatic COE criteria. Basic components:
- Applicant is a Veteran (?)
- Applicant biological and contact info
- Service history
- No loans on record (?)
