### ISSUE TITLE
Staging Review [Public Website - Campaign Landing Page]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#19816]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [x] VFS: Completes attached feedback tickets based on acceptance criteria in each practice area feedback ticket
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- Link to product outline ([CLP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/state-of-product.md))
- Link to [CLP Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Summary%20of%20Release%20Plan%20Steps%20-%20CLP%20MVP%201.0.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
- Link to your product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=904)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/1450) in TestRail with test execution logs ([CLP Test Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19554)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/195) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/196) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)
- http://preview-prod.vfs.va.gov/preview?nodeId=16139 is the test URL. CAG or SOCKS proxy required.

## Meeting attendees from **Public Websites**
- Product Manager (required): **Brian Lloyd**
- DEPO product lead (required): **John Hashimoto**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Nick Sullivan** **Kelson Adams**
- Other specialists: **Kevin Walsh - CMS Team**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot [**March 3rd @ 2PM ET**] 
- _Understand this a ways out, but wanted to plan forward in support.  Team is available and ready for staging review on March 3rd @ 2PM ET_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by shiragoodman** [comment]
scheduled for March 4, 2021 at 2pm ET

**Comment by 1Copenut** [comment]
@brianalloyd When you have a few minutes, would you mind updating this ticket with Staging URLs you'd like Product Support to review? Thank you!

**Comment by brianalloyd** [comment]
@1Copenut thanks for reaching out, so this is a little different product from what we've worked in the past as it's an internal product designed for VA Stakeholder use.  We have a mock campaign preview here: http://preview-prod.vfs.va.gov/preview?nodeId=16139. Let me know if this works, as a staging URL as not been set yet but it can to be viewed from CMS preview environment.

**Comment by tlei123** [comment]
@pjhill , while I'm waiting on team-update re. Mac Safari, I've updated the test cases, test plan, and Coverage for References links above in the main Description.

I have a [preliminary Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/193) ready for your preview, and I'll finalize that report once we determine whether Mac Safari can access the CMS prod-preview environment.

cc @brianalloyd

**Comment by peggygannon** [comment]
@brianalloyd I want to confirm that the CLP that needs a review is for the Mission Act located  here: http://preview-prod.vfs.va.gov/preview?nodeId=16139.? Your above comment says it's a mock campaign, so I want to confirm what needs reviewing. thx!

**Comment by brianalloyd** [comment]
@peggygannon great question, so we did a mock campaign to help facilitate staging review and both internal and stakeholder UAT.  The intent was to set this up to help facilitate a staging review, to validate all the elements are ready for a launch/release of the toolset.  Once an active campaign comes online that's when we would initiative a micro-collab review as discussed yesterday during our round table.  I hope that helps answer the questions, LMK.

**Comment by peggygannon** [comment]
ok, thanks, @brianalloyd for responding so quickly.

**Comment by tlei123** [comment]
@pjhill , final Summary (Defects) report link now updated above in main Description.

Finally [got Mac Safari to load the page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19554#issuecomment-789345217), and completed that test-run.  :::phew!:::

**Comment by mnorthuis** [comment]
Hi, no IA feedback at this time.  Looking forward to seeing the first real CLP!

**Comment by peggygannon** [comment]
@brianalloyd and @johnhashva  I don't have any content feedback.

**Comment by tlei123** [comment]
@brianalloyd , per @pjhill 's recommendation, please let me know once we have a comprehensive*/full* CLP deployed on Staging.  I'll then schedule another test-run there for more browsers/devices.

*By comprehensive/full, I mean a CLP that uses most/all the features covered in our [Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Collab%20Cyle%20Docs/product-use-cases.md).

Thx much!

**Comment by allison0034** [comment]
I have no design feedback. @rtwell you can link the design feedback ticket to this epic.

**Comment by rtwell** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/20883

**Comment by laflannery** [comment]
@shiragoodman All tasks within the epic are closed, can this task be closed?

**Comment by laflannery** [comment]
Closing based on your previous comment
