### ISSUE TITLE
Draft Email Template for CH36 Confirmations

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19826]
## Background
VANotify has a service that we can use to send emails to Veterans that use this service to receive a confirmation of their submission.  The first step is to draft an email template that gives the Veteran pertinent information, like when they submitted their application and what they should do next.

## Considerations
[VANotify Onboarding Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#technical-onboarding-guide)

## Tasks
- [ ] Draft an email that would be received by Veterans
- [ ] Share this email with the line of business to confirm it lines up with their comms, if any

## Acceptance Criteria
- [ ] An email has been drafted and saved in GH under this feature's email folder (make one if not found)

**Comment by jason-gcio** [comment]
might need a discovery task for finding the correct template
https://design.va.gov/patterns/email_template
