### ISSUE TITLE
Usability Testing Prep [VAOS, VAOS for Distribution]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19822]
## Steps to complete Usability Testing Prep: 
- [x] VFS Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance included in each practice area feedback ticket 
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to product outline
  - [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/vaos-for-distribution-initiative.md)
- Link to or attach prototype or mockups
  - [Prototype](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/443560117_Home)
- Link to or attach artifact with copy (if separate from prototypes/mockups)
- Link to research plan
  - [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/scheduling/research/feb-2021-vaos-vaccine-concept-test/research-plan.md)
  - [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/scheduling/research/feb-2021-vaos-vaccine-concept-test/conversation-guide.md)
  - Note- Research may be informal discussions/demos with VA facility leaders
- Link to regression test plan
  - TBD, not sure if we'll have this documented in TestRail
- Link to test cases/test plan in TestRail
  - TBD, not sure if we'll have this documented in TestRail

## Meeting attendees from **VAOS**
- Product Manager (required): **Lauren Ernest**
- DEPO product lead (required): **Lauren Alexanderson, Ryan Thurlwell**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Peter Russo**
- Other specialists:

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- 2/18, 3pm ET
- 2/22, 3:30pm ET 

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by laurenernest** [comment]
Hoping we can get Design, Content, and Accessibility feedback with what we have available.

IA request captured in #19821

**Comment by shiragoodman** [comment]
scheduled for 2/18 at 2:00 pm ET

**Comment by mnorthuis** [comment]
No IA feedback at this time.  Will be interested in hearing how user testing goes in terms of flow and order of information disclosure.  Thank you!

**Comment by shiragoodman** [comment]
The [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) has been updated (under the "New" tab). Zoom link is available there.
