### ISSUE TITLE
686c Update Manual Status for Unsupported Workflows

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#19823]
## Background
Currently, we are relying on RBPS to return an error and only then do we set the status to `MANUAL_VAGOV`.  BGS has asked us to manually set the status to `MANUAL_VAGOV` for these specific use cases: death of a child and a school age child has stopped attending school.  (Also possibly death of a dependent parent ?  Need to follow up with BGS on that particular workflow.)

## Tasks
- [x] Determine the work flows/use cases that are currently setting the status to `MANUAL`
- [x] Update the `MANUAL` status to `MANUAL_VAGOV` for all appropriate work flows

## Acceptance Criteria
- [x] The proc state type code has been updated in all relevant places
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Other ticket for this is #19087

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5907
