### ISSUE TITLE
[FSR] Unauthenticated CH1

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19833]
## Issue Description
_As we move towards releasing an unauthenticated FSR, we need to adjust some of the UI to gather information that would be populated in an authenticated experience. This work encompasses the UI updates to CH1_

---
## Tasks
- [ ] _Update the unauthenticated FSR's UI to match [the UXPin mockups](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136312480/simulate/sitemap?mode=i)_

## Acceptance Criteria
- [ ] _The unauthenticated CH1 has been updated to match the UXPin mockups_
- [ ] _The UI has been reviewed by a designer_

**Comment by LindaLi123** [comment]
Need to verify how is unauthenticated user data is handled currently. 6-9
