### ISSUE TITLE
Analytics Implementation for Design System Standardization - Custom Event Listener

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#19837]
# Google Analytics Implementation

## Task List
- [ ] Create helper function in `component-library` to dispatch custom event (discuss standards + metadata)
   - i.e component name, component action, 
   - ```{ type: 'AdditionalInfo', action: 'expand', title: 'This is the title.' , clickLabel: '', otherComponentParams:...}```
- [ ] Iteratively update each component to use new helper function
- [ ] Create custom analytics event listener on `vets-website`
- [ ] Update tests to listen for custom events instead of examining dataLayer
- [ ] Create and attach site-wide listener on document body 

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by bsmartin-ep** [comment]
This is live.  Closing.
