### ISSUE TITLE
Build out vaccine content in COVID chatbot

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19832]
## Issue Description
We need to add vaccine content to the COVID-19 chatbot. Danielle is providing new content for certain questions and the rest is being pulled from the vaccine mini hub. Selina will add the text to Github and Randi will review it. Danielle's mural board with the info and relevant Github folders can be found here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1612627412513/5e0acf06f5737a45020ca859119392161d082a46

## Tasks
- [x] Build out vaccine section (Selina)
- [x] Provide content for new questions (Danielle)
- [x] Review content (Randi)
- [x] Send completed file to chatbot team to finish out and publish (Randi/Danielle)

## Acceptance Criteria
- [x] Vaccine content added to live chatbot

**Comment by RLHecht** [comment]
These changes are live on the site. Closing ticket.
