### ISSUE TITLE
Develop a solution for routine synchronization of app credentials from credstash to SSM parameter store

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19849]
## Description
While we are in the process of moving from credstash to parameter store, teams may request changes to credstash for existing secrets. And those would not normally propagate to parameter store. Until that migration is complete, these secrets need to be synced routinely through a manual process. 

## Background/context/resources
Ops is developing a script that will sync credentials/secrets from credstash to parameter store.
We will run this script on a frequent cron job to make sure that things are sync'd. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Create a script to perform the sync of secrets from credstash to parameter store
- [ ] Set up a cron job that runs the above script 

## Definition of Done
- [ ] Secrets will be routinely synchronized from credstash to parameter store. 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jbritt1** [comment]
I think Demian stated wanting to warrant caution around automatically running the script in order to prevent some unintended overwrites. In my opinion, this one may not be needed if we can just only put new things in parameter store going forward and discontinue usage of Credstash over time.

**Comment by jbritt1** [comment]
Edited description to remove additional tasks and definition of done. This effort is no longer moving forward as we want to fully discontinue adding and updating values within credstash and continue our efforts to migrate to using parameter store entirely. Confirmed in this thread: https://dsva.slack.com/archives/CJYRZK2HH/p1628782755218100
