### ISSUE TITLE
Set up standard Forms KPI datasets in BigQuery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19854]
## Issue Description
Determine if and how we can standardize KPI framework metrics within our BigQuery datasets so that we can more quickly deliver KPI dashboards and the data can be more consistent across the VFS products.

---
## Tasks
- [ ] Technical Discovery into each of the highly suggested metrics & what VA.gov-wide standardized datasets would look like
- [ ] [Stretch] Technical discovery into other KPI Framework metrics & what VA.gov-wide standardized datasets would look like

## Metrics to standardize (Complete list TBD following [#19144](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19144))
- [ ] Time to complete (from the start of the user journey to the end. Can we break down time?)
- [ ] Funnel completion/conversion (from the start of the user journey to the end

## Acceptance Criteria
- [ ] VSP Analytics & Insights has standardized datasets set up in BigQuery so use when VFS teams request KPI Framework metrics, and has documented why we can't get some datasets & steps to mitigate that pain point

**Comment by joanneesteban** [comment]
@bsmartin-ep to add the funnel querying sheet/doc.

**Comment by JasonTheBearded** [comment]
Standardized datasets for Forms set up in BigQuery
