### ISSUE TITLE
Determine current VA examples

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19863]
## Issue Description
As we suggest general KPIs for VFS teams to use, we have received questions on how these metrics look for other VFSs. Draft and document examples of current VA.gov metrics that VFS teams can reference.

---
## Tasks
- [ ] Pull example VA.gov metrics & charts for each highly suggested metric in each VFS column
- [ ] [Stretch] Pull example VA.gov metrics and & charts for all metrics in the framework

## Acceptance Criteria
- [ ] VSP Analytics & Insights can share examples of VA.gov KPIs for our highly suggested metrics.

**Comment by joanneesteban** [comment]
Dupe of research audit at the beginning of the KPI Dashboard standardization initiative. Closing this ticket.
