### ISSUE TITLE
[FSR] Unauthenticated CH2 'Your VA Benefits' UI

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#19862]
## Issue Description
_As we move towards releasing an unauthenticated FSR, we need to adjust some of the UI to gather information that would be populated in an authenticated experience. This work encompasses the UI adjustments to CH2's 'Your VA Benefits' pages_

---
## Tasks
- [ ] _Update the unauthenticated FSR's UI to match the UXPin prototype._
   - [Asking the Veteran if they receive VA benefits](https://app.uxpin.com/edit/8796645#?id_page=136384630)
   - If the Veteran receives VA benefits, [asking for the amount they receive for comp + pen and edu](https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/136384631/simulate/no-panels?mode=i)

## Acceptance Criteria
- [ ] _The unauthenticated CH2' 'Your VA benefits' pages have been updated to match the UXPin mockups_
- [ ] _The UI has been reviewed by a designer_

**Comment by denisecoveyduc** [comment]
This is no longer relevant, closing.
