### ISSUE TITLE
KPI framework - release plan

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19869]
## Guidance

_This Release Plan Template is intended to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: February-March 2021 
- Desired number of users: 3
- The group(s) from which you'll recruit test users: VFS PMs and DEPO POs
- How you'll recruit test users: DM users & ask on the VSA Product Channel
- How you'll give test users access to the product: Screen Share
- What "Success" criteria will you look at before launch? VSA leadership & DEPO leadership agree to adopt the framework in analytics asks
- How you'll measure your "Success" criteria? y/n

### Results:

- Number of users: x 	

- Results per your "Success" criteria:

- Number of bugs identified / fixed: x/x

- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no

  - If yes, what: lorem ipsum  

### Planning:

- Desired launch date: April 2021
- Post-launch KPI 1: % of VFS & DEPO users
- Post-launch KPI 2: CSAT
- Post-launch KPI 3: VSP Analytics & Insights dashboard creation velocity

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by joanneesteban** [comment]
## Go to market

### Do
- [ ] Announce in Platform Newsletter
- [ ] Announce in `#vfs-all-teams`
- [ ] Announce in `#platform-team`
- [ ] Announce in Team of Teams
- [ ] Check in with OCTO-DE Crew leads on how we can empower them to support & encourage Crews to use this framework
- [ ] Update KPI dashboard request template
- [ ] Update Analytics Playbook 
- [ ] Update KPI setting workshop
- [ ] Update product outline template in Github

### Try
- [ ] Announce in `#vfs-analytics`
- [ ] Announce in `#vsa-product`
- [ ] Analytics team changes our Zoom backgrounds with KPI Framework announcement banner

**Comment by joanneesteban** [comment]
KPI Framework initiative was pivoted in favor of the KPI Dashboard standardization initiative. Closing this ticket. We can reopen if we focus on the Framework again.
