### ISSUE TITLE
Incorporate the framework into the Analytics Playbook

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19870]
## Issue Description
Setting KPIs is a part of the larger analytics journey (setting, tracking, analyzing, and taking action with data), which is documented for VFS teams and DEPO in the larger [Analytics Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/AnalyticsPlaybook.md). How might we incorporate the KPI Framework into the Analytics Playbook so that teams can seamlessly use all of the Analytics products and services through the Playbook?

---
## Tasks
- [ ] Plan out which parts of the KPI Setting Framework should stay in the Framework and which should be incorporated in the Playbook
- [ ] Determine how the Framework should be integrated in the Playbook's content
- [ ] Update the Playbook content with the KPI Setting Framework

## Acceptance Criteria
- [ ] VFS teams can use the Analytics Playbook and get to the KPI Setting Framework if they need to, and vice versa
