### ISSUE TITLE
Audit Domo datasets for standardization flips

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19873]
## Issue Description
The Analytics team should have [standardized datasets](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19854) for several suggested KPIs. For data consistency and cleanliness, and to be able to update data efficiently, we need to update our Domo datasets to fit our standardization. How might we determine which datasets need to be updated?

---
## Tasks
- [ ] Audit Domo datasets for those that can match our standardized BigQuery datasets
- [ ] Share documentation with the rest of the Analytics team

## Acceptance Criteria
- [ ] All "live" Domo datasets that can be flipped have been recorded for the Analytics team

**Comment by joanneesteban** [comment]
Will most likely sunset any non-standardized datasets. Closing this ticket.
