### ISSUE TITLE
Flip all Domo datasets to standardized datasets

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19874]
## Issue Description
The Analytics team should have [standardized datasets](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19854) for several suggested KPIs. For data consistency and cleanliness, and to be able to update data efficiently, we need to update our Domo datasets to fit our standardization. How might we deliver current Domo dashboarding with the standardized datasets?

---
## Tasks
- [ ] Flip all of the Domo datasets that have been [audited](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19873)
- [ ] QA that datasets are accurate, up-to-date, and don't change the functionality of the charts

## Acceptance Criteria
- [ ] All Domo datasets that fit our standardized BigQuery datasets should point to the standardized BigQuery datasets

**Comment by joanneesteban** [comment]
Tech debt. Moving to next/future backlog.

**Comment by johnny-jesensky-adhoc** [comment]
Our team recently audited some of our Domo datasets for the GA4 Migration -- we do need to go back in and clean-up our Domo instance where possible. Closing this out for now, and will revisit Domo clean-up as part of a larger epic.
