### ISSUE TITLE
Discovery into BigQuery<>Slackbot

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19878]
## Issue Description
To understand our VSP customer support velocity and pain points to improve, we need to understand our workflow. This issue is around the technical discovery for the Slackbot, since that bot tracks our engineering support. 

---
## Tasks
- [ ] Determine & document steps for getting Slackbot data into BigQuery
- [ ] Determine any dependencies for BigQuery<>Slackbot
- [ ] Determine any blockers for BigQuery<>Slackbot

## Acceptance Criteria
- [ ] VSP Analytics & Insights understand the general work & potential dependencies or blockers that will be involved in connecting BigQuery to the Slackbot

**Comment by joanneesteban** [comment]
Slackbot not in use anymore. Closing this ticket.
