### ISSUE TITLE
Discovery into BigQuery<>ForeSee

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19876]
## Issue Description
To track survey usage for VA.gov metrics and for the DEPO Platform to understand historical VA.gov customer satisfaction, we are looking to connect our data warehouse to ForeSee data. This issue is around the technical discovery for that work. Because we are trying to get historical data and ForeSee will be replaced by Medallia, this data does not need to be dynamic or automated.

---
## Tasks
- [ ] Determine & document steps for getting ForeSee data into BigQuery
- [ ] Determine any dependencies for BigQuery<>ForeSee
- [ ] Determine any blockers for BigQuery<>ForeSee

## Acceptance Criteria
- [ ] VSP Analytics & Insights understand the general work & potential dependencies or blockers that will be involved in connecting BigQuery to ForeSee

**Comment by joanneesteban** [comment]
If we're able to retrieve CSVs of all historical data, we can manually add that data into BigQuery.

**Comment by JasonTheBearded** [comment]
Discovery complete and Foresee data loaded into BigQuery. Closing ticket!
