### ISSUE TITLE
Connect BigQuery<>Medallia

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19879]
## Issue Description
Dynamically connect BigQuery to Medallia so that VFS teams can get up-to-date information on Veteran satisfaction.

Discovery Work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18413

---
## Tasks
- [ ] Set up Medallia data in BigQuery to automatically pull new survey and usage data

## Acceptance Criteria
- [ ] We can get up-to-date (daily) Medallia survey question and answer data
- [ ] We can get up-to-date (daily or weekly) Medallia survey usage data

**Comment by joanneesteban** [comment]
@jonwehausen & @JasonTheBearded to meet.

**Comment by JasonTheBearded** [comment]
Meeting held 3/25 with Sarkis and @bsmartin-ep for confirmation of Medallia export setup. Received updated test file and will code out the import function to load files into BigQuery. Awaiting confirmation of some security related items before moving to production. Once ready for production we will provide new google cloud bucket and receive the exports on a daily basis.

**Comment by JasonTheBearded** [comment]
Testing for python package to load Medallia export completed and ready to go. Meeting is scheduled for 4/16 to discuss final ATO items and prep production release.

**Comment by JasonTheBearded** [comment]
Moved to Blocked while waiting on ATO approval for Medallia

**Comment by JasonTheBearded** [comment]
ATO for BigQuery approved and ATO for Medallia is moving forward. Will prep code and meet with Sarkis to confirm finalized columns and start production process.

**Comment by joanneesteban** [comment]
Rachael sent a follow up email to Halfaker on 7/7/21. One workaround _might_ be to drop the data into AWS S3 and then drop it into BQ.

**Comment by JasonTheBearded** [comment]
Google cloud bucket and trigger set up and ready to receive files and load to BigQuery. Waiting on Halfaker to start sending files. @bsmartin-ep can you confirm with Sarkis when the production files start coming in that they need to go to the medallia-exports bucket? Moving this ticket to blocked until files starting coming in.

**Comment by michelle-dooley** [comment]
@obrienjulie assigning this one to you.  Please add others as needed.  This is an older one that I brought back to life.  Let me know if you want to discuss.

**Comment by obrienjulie** [comment]
Meeting on 2/10 with Ian & Jason from Contact Center. Bringing in medallia data into Big Query is still in security review. Closing out this ticket.
