### ISSUE TITLE
Add the Playbook & KPI Setting Framework to Confluence

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19871]
## Issue Description
As of February, 2021, the Analytics Playbook is sitting in Github and does not have an easy-to-use structure. We also cannot track how many of our customers are using it. How might we add the Analytics Playbook to Confluence so that it is accessible, easy to use, and trackable? If the KPI Framework is not in Confluence, how might we add the Framework to Confluence as well?

---
## Tasks
- [ ] Use the [Playbook IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19161) and redesigned [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19708) to add both to Confluence
- [ ] Verify that VFS teams and DEPO can access the playbook and framework

## Acceptance Criteria
- [ ] VFS teams and DEPO can access the Analytics Playbook and KPI Framework in a trackable location that's consistent with other Platform documentation

**Comment by joanneesteban** [comment]
This is a documentation initiative. Moving to the next/future backlog.
