### ISSUE TITLE
Prep Medallia datasets for Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19887]
## Issue Description
Prep our BigQuery data to be connected to Domo.

BQ connect work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19879

---
## Tasks
- [x] Prep Medallia survey datasets in BigQuery to connect to Domo
- [x] Prep Medallia usage datasets in BigQuery to connect to Domo
- [x] Update all charts that point to ForeSee to also point to new BigQuery datasets

## Acceptance Criteria
- [ ] Our Domo dashboards can get accurate Medallia data through BigQuery

**Comment by joanneesteban** [comment]
Additional Medallia work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18278

**Comment by michelle-dooley** [comment]
@obrienjulie assigning this one to you.  Please add others as needed.  This is an older one that I brought back to life.  Let me know if you want to discuss.
