### ISSUE TITLE
Prep ForeSee Datasets for Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19888]
## Issue Description
Prep our BigQuery data to be connected to Domo.

BQ connect work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19880

---
## Tasks
- [ ] Prep ForeSee datasets in BigQuery to connect to Domo
- [ ] Update all live charts that point to ForeSee with BigQuery datasets

## Acceptance Criteria
- [ ] Our Domo dashboards can get accurate ForeSee data through BigQuery

**Comment by joanneesteban** [comment]
@joanneesteban look into Intercept survey CSV dump.

And an API dump.

**Comment by joanneesteban** [comment]
Waiting on ForeSee sunset to complete this ticket.
