### ISSUE TITLE
Prep Confluence/Documentation Homepage datasets for Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19884]
## Issue Description
Prep our BigQuery data to be connected to Domo.

BQ Connect Work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19882

---
## Tasks
- [ ] Prep Documentation Homepage datasets in BigQuery to connect to Domo
- [ ] Prep Confluence datasets in BigQuery to connect to Domo

## Acceptance Criteria
- [ ] Our Domo dashboards can get accurate Platform Documentation data through BigQuery

**Comment by joanneesteban** [comment]
Echoing https://github.com/department-of-veterans-affairs/va.gov-team/issues/19882#issuecomment-857991777
