### ISSUE TITLE
Connect Confluence/Homepage<>BigQuery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19882]
## Issue Description
Connect BigQuery to Confluence & the Documentation Homepage so that VSP teams can get both up-to-date and historical information on how VFS teams use Platform Documentation.

Discovery work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18441

## Tasks
- [ ] Set up Documentation Homepage data in BigQuery
- [ ] Connect Confluence to BigQuery

## Acceptance Criteria
- [ ] We can get all documentation homepage and confluence usability data

**Comment by joanneesteban** [comment]
Can re-open if we're able to get analytics-team tracking in Confluence or with a Content/IA team request. Closing this ticket.
