### ISSUE TITLE
Remove remaining instances of Access to Care form link

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#19893]
## Issue Description
Instead of linking to the Access to Care form (https://www.accesstocare.va.gov/sign-in-help), we'd like to recommend that users call our main 411 info line. We need to replace the messaging and link to the Access to Care form with the following:

If you need more help, call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711).

Note: There may be small tweaks to the above sentence needed depending on the surrounding text. @RLHecht can verify that each instance works as a unified UX.

---
## Tasks
- [x] Identify all pages where this change needs to happen.
- [x] Replace the Access to Care link and sentence it's in with the new sentence above with the phone number.

## Acceptance Criteria
- [x] We no longer link to Access to Care form anymore
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@brianalloyd This is one to add to your board. I think @ncksllvn needs to do the changes but I can review whether the wording is still correct.

**Comment by RLHecht** [comment]
@brianalloyd Just checking in on this ticket and if it's something PW can pick up in an upcoming sprint. Thanks!

**Comment by brianalloyd** [comment]
@RLHecht yes, we'll slot for this sprint for action. I'll follow up once ready for review.

**Comment by brianalloyd** [comment]
@ncksllvn is this something the PW team can support or does this need to go to another team?  @kelsonic thinks this might need to be action for the "Access to Care" team.  LMK.

**Comment by kelsonic** [comment]
Sorry I think I may have misread this ticket. So @bethpotts and @RLHecht, these are all the locations in vets-website where we have the link `accesstocare.va.gov/sign-in-help`:

![image](https://user-images.githubusercontent.com/12773166/116269885-d85fd400-a73b-11eb-9fb1-96624b632921.png)

To clarify, then all of the above instances of `accesstocare.va.gov/sign-in-help` should be switched to `If you need more help, call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711).`?

**Comment by RLHecht** [comment]
@kelsonic Is there a way we can see where those links are? Like what the surrounding text is so we know if that sentence still makes sense to put in or if it should be tweaked in any way?

**Comment by kelsonic** [comment]
The text for each of those links is currently `submit a request to get help signing in`:

https://github.com/department-of-veterans-affairs/vets-website/blob/d26a85874dd4a11617be9fabe46926b19b0f08bf/src/applications/auth/containers/AuthApp.jsx

https://github.com/department-of-veterans-affairs/vets-website/blob/29aa8a7d1d59e68c95214144ac4971128f3f29b1/src/platform/static-data/SubmitSignInForm.jsx

https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/platform/user/profile/vap-svc/components/base/VAPServiceTransactionErrorBanner.jsx

**Comment by RLHecht** [comment]
If the link to Access to Care is in running text, my suggestions are in the chart below. I think some of these are CTA buttons though, but admittedly I'm having a hard time reading the code. @kelsonic can you help me with that? @bethpottsVADEPO can you look at my suggestions in the chart and let me know if the wording is OK?
| Before | After |
| --- | --- |
| If you still can’t sign in, please use our online form to submit a request for help | If you still can't sign in, call our MyVA411 main information line for help at 800-698-2411, select 0 (TTY: 711). |
| We’re having trouble signing you in to VA.gov right now because we found more than one DoD ID number for you. To fix this issue, please submit a request to get help signing in. | We’re having trouble signing you in to VA.gov right now because we found more than one DoD ID number for you. To fix this issue, call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |
| We’re having trouble signing you in right now because your My HealtheVet account number doesn’t match the account number on your VA.gov account. To fix this issue, please submit a request to get help signing in. | We’re having trouble signing you in right now because your My HealtheVet account number doesn’t match the account number on your VA.gov account. To fix this issue, call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |
| If you’ve taken the steps above and still can’t sign in, please use our online form to submit a request for help. | If you've taken the steps above and still can't sign in, please call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |
| To find out if this is about an account with the Department of Defense: You can submit a request to get help signing in | To find out if this is about an account with the Department of Defense: Call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711) |

**Comment by kelsonic** [comment]
Thanks @RLHecht! Updating the content now. Could you confirm this markup looks right?

```html
call our MyVA411 main information line for help at
<a href="tel:18006932411" aria-label="8 0 0. 6 9 3. 2 4 1 1.">
  800-698-2411
</a>
, select 0 (TTY: 711).
```

I wasn't sure if the TTY: 711 also needs to be a link? 🙂

**Comment by kelsonic** [comment]
@RLHecht Absolutely! 🙂

**Comment by bethpottsVADEPO** [comment]
@RLHecht Where did you get the "select 0" part from? I see we don't use that on the COVID vaccines page. Where do we use it that you pulled it from? 

For the last one in the chart in this ticket, let's use a comma instead of a colon:
To find out if this is about an account with the Department of Defense, call our MyVA411 main information line at 800-698-2411, select 0 (TTY: 711)

For each of these, it would be more conversational if we added "and" before "select 0"--what do you think?

**Comment by RLHecht** [comment]
@bethpottsVADEPO For the "select 0" I was using the language you had above in the ticket. We can take it out if you think it isn't needed.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Gah! I don't remember anymore where that content originated. Sorry about that. I just want to try to be consistent across our site with this language. Go ahead and work with @kelsonic to make the updates I call out above in my comment:

- "and select 0"
- comma instead of colon for the last one in the chart

Thank you both!

**Comment by RLHecht** [comment]
@kelsonic let me know when you want me to look at these changes. Per Beth's comment above you can take out "and select 0" from all my edits.

**Comment by kelsonic** [comment]
Oops! Thanks for the ping, I'll get a PR up for this asap

**Comment by kelsonic** [comment]
PR is open: https://github.com/department-of-veterans-affairs/vets-website/pull/17117 tagged you as a reviewer @RLHecht 🙂

**Comment by kelsonic** [comment]
In [this code](https://github.com/department-of-veterans-affairs/vets-website/pull/17117/files#diff-770d5be1446c6026093fb50c478cea3174f259f8da7963fede514e1a824e0e67L251) the links to accesstocare.va.gov/sign-in-help had Google Analytics query params (assuming for tracking purposes). Anything I need to do on my end to preserve the analytics tracking or is it ok to just not worry about them anymore? CC @jonwehausen @RLHecht @bethpotts

**Comment by RLHecht** [comment]
@kelsonic Is there an easy way for us to see these changes for me to validate?

**Comment by brianalloyd** [comment]
Validated and will close the ticket.  Randi and Beth let me know if you have any questions on this ticket.  Thanks.
