### ISSUE TITLE
Minor change to wording on copay rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19896]
## Issue Description
We got a stakeholder request to change some wording on the [VA health care copay rates](https://www.va.gov/health-care/copay-rates/) page. 

See screen shot for change: 

![Screen Shot 2021-02-12 at 11.14.56 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/17c9cb67-d7d8-458a-b258-8f863affbe3f)

This change should also be made on the 2020 past rates pages. 

## Tasks
- [x] Make change to 2021 and 2020 copay rates pages (Randi)
- [x] Review and publish (Randi)
- [x] Notify stakeholder that change has been made (Randi/Danielle)

## Acceptance Criteria
- [x] Content change live on site

**Comment by RLHecht** [comment]
This change has been made for both the current and past rates pages. Moving to validate and will close after today's deploy. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
