### ISSUE TITLE
Build basic/simple list loop component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#19903]
## Issue Description
Develop reusable code for the basic list loop component 

---
## Tasks
- [ ] Follow design pattern
- [ ] Develop reusable code for list loop 

## Acceptance Criteria
- [ ] List loop component in SB
---
