### ISSUE TITLE
Basic List Loop pattern documentation 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#19901]
## Issue Description
Write up documentation describing usage guidelines for the basic list loop pattner

---
## Tasks
- [x] Draft documentation
- [x] Submit for review
- [x] Post final documentation 

## Acceptance Criteria
- [x] Documentation of basic / simple list loop is available on design.va.gov
---
