### ISSUE TITLE
Document the existing List Loop pattern

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#19900]
## Issue Description
document existing List Loop pattern

---
## Tasks
- [ ] document existing list loop pattern
- [ ] Update Sketch library with the existing list loop pattern

## Acceptance Criteria
- [ ] documentation completed
- [ ] Sketch library template is updated with new list loop pattern
