### ISSUE TITLE
Move child of Veteran section on Survivors DIC rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19912]
## Issue Description
Per stakeholder Angie Smith, we need to move the "Child of a Veteran" section into its own H2 section instead of having it full under the "DIC rates if the Veteran died on or after January 1, 1993" section.

We need to go into Drupal and move around several content blocks and change header levels so they are correct with the new placement. 

Other fixes that need to be made are:
-  Removing the table for child status and monthly payment and turning them into bullet points instead. 
- Adjusting the totals for the total monthly payments in the child section (multiply the first two columns to get the correct number)

Once these changes have been approved for the 2021 rates page, we need to make these same changes on our past rates pages.

## Tasks
- [x] Make all above changes to the 2021 survivors DIC rates page (Randi)
- [x] Send to stakeholder for approval (Beth)
- [x] Review and publish page when OKed (Randi)
- [x] Make changes to past rates pages (Randi)
- [x] Review changes on past rates pages (Beth)
- [x] Publish past rates pages (Randi)

## Acceptance Criteria
- [x] All Survivor DIC rates pages are live with changes

**Comment by RLHecht** [comment]
@bethpottsVADEPO I updated the three past rates pages. Can you just look them over to make sure I did the math correctly in the new examples we give?
preview-prod.vfs.va.gov/preview?nodeId=6203
preview-prod.vfs.va.gov/preview?nodeId=6799
preview-prod.vfs.va.gov/preview?nodeId=11018

**Comment by lunascoop** [comment]
@RLHecht I've reviewed the pages and they look good.

**Comment by RLHecht** [comment]
These pages are now published. Moving to validate.

**Comment by bethpottsVADEPO** [comment]
Thanks for your work on this, @lunascoop and @RLHecht ! There's one tweak I think we should make to the H2s now that the children rates are pulled out into their own section again. The first 2 H2s don't indicate that the content in those sections are for spouses (as the third one does for children). Let's change the first 2 H2s to this (it's right at the 70 character limit!):

Surviving spouse rates if the Veteran died on or after January 1, 1993

Surviving spouse rates if the Veteran died before January 1, 1993

**Comment by RLHecht** [comment]
I made these changes on the current and the past rates pages. Will close after I validate they are live on the site.

**Comment by RLHecht** [comment]
Work has been validated. Closing ticket.
