### ISSUE TITLE
Discovery of Changes to 526 PDF Form

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1991]
## User Story or Problem Statement
As a disabled Veteran, I want to be sure that I am submitting all VA required information and that I am provided with the most up to date instructions on the online disability claim form so I can be confident that nothing is missing from my submission.

## Goal
_Identify and research all updates made in the PDF version of the 526 form and how they should  be incorporated in the online version_

## Tasks
- [ ] Yana and Andrea will meet on 12/10 to discuss and write up differences between current and new versions
- [ ] Help EVSS identify their changes

## Acceptance Criteria
- [ ] _Content updates_
- [ ] _Requirements of fields_
- [ ] _Functionality of entry fields_
- [ ] _Instruction fields_

## PDF with Highlighted changes
[VAF21-526EZ (Sept 2019 - Highltd) (1).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3677801/VAF21-526EZ.Sept.2019.-.Highltd.1.pdf)

**Comment by YanaRoy** [comment]
Andrea provided PDF updates to Casey. Paul Shute following up with her on 11/5.
