### ISSUE TITLE
Minor copy change to Spanish COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19911]
## Issue Description
Our translator requested a minor copy change to one of the H2s in the Spanish COVID-19 FAQs page. 

The sixth H2 that reads: Deuda, copagos, apelaciones y otras dudas financieras should be changed to:
Deuda, copagos, apelaciones y otras **deuda financieras**

## Tasks
- [x] Update copy on page (Randi)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Change is on live site

**Comment by RLHecht** [comment]
This change was made. Moving to validate and will close after today's deploy. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
