### ISSUE TITLE
[Front End] Revise 'Request for Higher-Level Review' Launch page

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#1994]
## User Story or Problem Statement
As a Veteran, I need to understand the higher-level review process so I can decide if I should file a higher-level review.

## Goal
Revise the design and content of the higher-level review content page based on UX and content strategy recommendations.

## Current URL
https://www.va.gov/decision-reviews/higher-level-review/

## Revised page
* [Higher-level review mockup](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385333421_00-Request-Higher-Level-Review)
* [Higher-level review mockup with expanded accordions](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385333422_01-Request-Higher-Level-Review-Expanded-Benefit-Office)

## Related tickets
- Design: #1989
- Content: #1993

## Tasks
- [ ] Does not appear in production when it's added to staging
- [ ] Page matches design and content on the mockups
- [ ] Reviewed by UX and Engineering team
- [ ] Deployed

## Acceptance Criteria
- Content revised in Drupal

**Comment by YanaRoy** [comment]
@peggygannon this is the Drupal update that you and @Mottie discussed. Please let us know if you have any questions. Thank you!!

**Comment by peggygannon** [comment]
Hi, @Mottie and @YanaRoy Yes, we need to create a new ticket for the content updates to the Higher-Level Review landing page. I'm happy to create this ticket and assign it to the public websites team and myself.

We'll coordinate with your team on when this page is ready to update in drupal. The mockup is still in content and I/A reviews. Once the content and I/A elements in the mockup are approved, we can make the updates to the drupal file.

**Comment by peggygannon** [comment]
@Mottie @YanaRoy I've created this issue to capture the I/A and content drupal updates to this page: 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3460

**Comment by jenniferlee-dsva** [comment]
Is this ticket now duplicative of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3460 ? Do we still need it or can we close 1994?

**Comment by Karak888** [comment]
moving to close as @lwalsh617 will be working on this and this is a duplicate of #3460
