### ISSUE TITLE
Merge and sort urgent care mash-up results on the FL front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19959]
## Issue Description
When a Veteran selects "Urgent care" + "All urgent care" the results list includes 10 community providers and 10 VA facilities. Because of this fixed number, the result set may not include all of the closest locations of any one type. This may cause additional confusion if the "Community providers only" or "VA urgent care" search results are compared to list of results for "All urgent care".

**Current Implementation**
In the back end mashup controller, we make 2 separate calls,
- Lighthouse
- PPMS
Each of these requests uses the per_page query param to determine max # of results returned, making sorting/pagination complex on the backend

Recommendation from [Engineering discovery issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18521):

- Make 2 separate queries on the front end (one for VA x 20 results, one for CC  x 40 results each) and merge them together on front end, sorted by distance.
- Deduplication will be done on the backend.
- Queries can be done in parallel
- Show the 20 closest results
- Would let us sunset the mashup controller

**Pagination is not within scope**

---
## Tasks
- [ ] Make 2 separate parallel queries on the front end (one for VA x 20 results, one for CC x 40 results) 
- [ ] Merge results together on the front end, sorted by distance.
- [ ] Return the 20 closest results (after both queries are returned)

## Acceptance Criteria
- [ ] Closest 20 locations (of a list of VA and Community urgent care locations) are returned, regardless of type distribution
- [ ] If two locations are at the same distance, it does not matter which is returned first
- [ ] Lst of results corresponds with map
- [ ] Alpha order (pins) is maintained

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
