### ISSUE TITLE
[Discovery] FE VAOS service Staging testing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19974]
## Background
Before determining the scope and LOE to integrate with the new VAOS service, FE team to do discovery and testing in Staging environment. The goal for the first iteration of VAOS Service in Production is to have feature parity with var-resources.

## Tasks

- [ ] Direct scheduling

- [ ] Request scheduling

- [ ] Community Care/HSRM

## Definition of Done

- [ ] Tickets for issues/requests in the service are opened for VAMF

- [ ] Tickets are created for FE work

**Comment by laurenernest** [comment]
closing epic. vaos service tickets are captured in #14091
