### ISSUE TITLE
Update interest rate number on NADL page-HOLD UNTIL 2/17

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19991]
## Issue Description
Per stakeholder Raleigh Contreras, the interest rate for an NADL is changing from 3% to 2.75% on February 17. We need to update that number on our [NADL page](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) and publish on 2/17

## Tasks
- [x] Change interest rate on NADL page (Randi)
- [x] Review and publish (Randi)
- [x] Let stakeholder know it's been published (Beth/Randi)

## Acceptance Criteria
- [ ] New interest rate live on site

**Comment by RLHecht** [comment]
This work has been completed. Moving to validate and will close after today's deploy. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
This is live on the site. Closing ticket.
