### ISSUE TITLE
Changes needed to error message

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20002]
## Issue Description
Per stakeholder Cory Trimm, changes need to be made to an error message.
1. My HealtheVet needs to be 2 words.
2. We need to add the TTY number 800-877-8339 to the error message page.

![Screen Shot 2021-02-16 at 9.44.46 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/0016de5d-8dd9-4787-ab7d-6a3165b8fef9)

## Tasks
- [x] Change My HealtheVet to 2 words
- [x] Add TTY number
- [x] Review and publish
- [x] Notify stakeholder change was made

## Acceptance Criteria
- [x] Error message now has correct info on live site

**Comment by ncksllvn** [comment]
@RLHecht what I am seeing is that this error message already shows the TTY number `800-877-8339`. Is it possible we meant `800-877-3399`? That's what I'm seeing the VA Profile use in a certain error case where they suggest calling My HealtheVet.

```
<p>
            Contact us at <Telephone contact={CONTACTS.MY_HEALTHEVET} />. We’re
            here Monday - Friday, 8:00 a.m - 8:00 p.m. ET. If you have hearing
            loss, call <Telephone contact="800-877-3399" />. Tell the
            representative that you tried to sign in to VA.gov, but got an error
            message that you may have more than one My HealtheVet account or ID.
          </p>
```

**Comment by AGarcia-Clarity** [comment]
@ncksllvn, I too am confirming that the TTY number is correct `800-877-8339` and that VA Profiles TTY number is possibly incorrect.  I have verified the correct TTY number is in both the staging & production environments.

[Staging]
![Screen Shot 2021-02-18 at 12 26 02 PM](https://user-images.githubusercontent.com/67602137/108396102-7be4b380-71e4-11eb-8296-811fb4cc6747.png)

[Production]
![Screen Shot 2021-02-18 at 12 24 17 PM](https://user-images.githubusercontent.com/67602137/108396010-5f487b80-71e4-11eb-9d84-d4bcecc00dd7.png)

**Comment by RLHecht** [comment]
Thank you @AGarcia-Clarity So I think the only change that needs to happen is My HealtheVet needs to be two words instead of one on the error message.

**Comment by AGarcia-Clarity** [comment]
TODO:
- [ ] Reverify & confirm in the staging & production environments that changes are reflected.

**Comment by bethpottsVADEPO** [comment]
You all may have this covered already, but I just wanted to note that My HealtheVet appears incorrectly as one word in several places on that "We can't sign you in" page--in the alert box and also in the text under that box. I see it wrong twice under "Submit a request for online help." And a space needs to be inserted before the link "My HealtheVet online help form." Can someone make those additional corrections as well? Thanks!

**Comment by AGarcia-Clarity** [comment]
@bethpottsVADEPO, I corrected all references of My HealtheVet on the entire "We can't sign you in page".  I took a [screenshot of my local changes](https://github.com/department-of-veterans-affairs/vets-website/pull/16097) as they will appear once the deployment process kicks off for staging & production.  Thank you.

**Comment by RLHecht** [comment]
@AGarcia-Clarity It looks like there's a space missing after the sentence "Call us at 877-327-0022." Could you please fix?

**Comment by bethpottsVADEPO** [comment]
When should I tell the stakeholder that this fix will be deployed? Today or next week? Thanks!
