### ISSUE TITLE
[DISCOVERY] VAMC analytics

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20006]
## Issue Description
Pageviews and navigation interactions for VAMC (Pittsburgh) more than doubled from December to January
- December 2020 ->  19,841 Pittsburgh health care  page views and 38,478 unique side navigation interactions
- January 2021 -> 47,314 page views and 70,637 unique side navigation interactions

As the Facilities team, we need to understand the source of this notable increase. 

---
## Tasks
Identify the forces which impact this product
For example:
- New legislation
- New administration
- Current landscape
- Social media
- Organizational (VA Secretary) announcements
- Related launches
- Non-Veteran visits (stakeholders)
- Seasonality/Veteran population or milestone, What happened in previous years?
- Larger VA traffic (macro changes)
- Veterans assigned to a given health care system

Month over month

## Acceptance Criteria
- [ ] Updated documentation regarding VAMC analytics
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/vamc-analytics.md
