### ISSUE TITLE
Investigate how to improve test environments

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#20031]
# Description
Given that our test environments are currently less than ideal due to the following issues:

1. Insufficient test data
1. Rigid integrations with external data providers
1. Collisions when multiple users want to use a single test user

## How might we improve test data available to VFS teams?
- [ ] Could we create a bigger pool of test data?
- [ ] Could we create a process for requesting new test data from Platform?
- [ ] Could we create a tool allowing self-service creation of test data?

## How might we more thoroughly verify Platform integrations with external services?
- [ ] Could we create a new framework for verifying integrations between the Platform and external services?
- [ ] 

## How might we reduce multiple testers converging on a single 'good' test user / set of test data?

- [ ] Discover methods for enhancing our existing test environment (staging) to be more suitable for testing.
- [ ] Research creating a new test environment specifically for testing
- [ ] Research the creation of test harnesses for test data
