### ISSUE TITLE
[Cheetah MVP] Event tracking

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20035]
## Item Description
With the change in homepage CTAs, ensure existing events are still working and add specific tracking for cheetah flow.

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag
- [ ] Given "Primary or specialty care" is selected, When user clicks Start scheduling, Then event is tracked _(Note- `vaos-schedule-appointment-button-clicked` is the existing event that fired when the Start Scheduling button was clicked)_
- [ ] Given "COVID-19 vaccine" is selected, When user clicks Start scheduling, Then event is tracked specifically for flow
- [ ] Given cheetah flow, When user clicks Submit appointment button on Review page, Then event and data is tracked specifically for flow
- Cheetah Submission attempt with data
- Cheetah Submission succeed
- Cheetah Submission failed

![ee1cc333-4be8-42d2-a332-11280b5787e9.jpeg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/20dcdc26-0356-456f-b415-ff9644dda403)

**Comment by laurenernest** [comment]
We will move forward with vaccine-specific start and submission events. `covid19` can be used in place of `cheetah` in the event data

**Comment by laurenernest** [comment]
What's the difference in scenario when `schedule-covid19-button-clicked` fires vs `covid19-path-started`?

**Comment by jbalboni** [comment]
@laurenernest It looks like for the vaccine flow, effectively nothing. In the new appointment flow the `path-started` event will fire whenever someone starts the flow from either the appt list page or the confirmation page. And the button click events are specific to the button being clicked on one of those pages.

So, since the vaccine flow doesn't have a button to schedule another appointment on the confirmation page, those events should always happen together.

**Comment by laurenernest** [comment]
@jonwehausen Since we're using a covid-specific event name, do we need to request another GTM set up to track the submission data? I'm trying to track submissions by facility similar to what we have for the request submission.

**Comment by jonwehausen** [comment]
Hi @laurenernest , 

Before answering concretely could you point me to the new covid19 event names you're referring to? Also, in order to begin collecting the facilities along with submissions, we'll want to pass the facility id along with each submission. The variable name for the facility id is `health-FacilityID`

cc: @laurensimpson14

**Comment by laurenernest** [comment]
@jonwehausen Looking at `vaos-covid19-submission` which should look similar to our `vaos-request-submission` and `vaos-direct-submission` events. Let me know if you're seeing the data in the submission and I can re-open #20309 and include that info.

**Comment by jonwehausen** [comment]
Hi @laurenernest , 

We apologize for the delay here. I wanted to update you as I ran through another test of the vaccine scheduling flow and **did not** see the facility ID populate. 

We of course will want to include this on submission if we want to be able to filter by facility. 

![image](https://user-images.githubusercontent.com/48527022/115776168-d4216880-a381-11eb-8be2-63f72156f3ee.png)

Thanks and let us know any other questions you may have. 

cc: @laurensimpson14
