### ISSUE TITLE
Rework the component library's build process

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#20057]
## Issue Description
Currently, this build process is a [pretty basic script](https://github.com/department-of-veterans-affairs/component-library/blob/master/scripts/build.js) which simply "babelifies" each component and writes the output to the project root. We should use a bundler to intelligently package the components.

I'm currently recommending Rollup. GitHub's own design system, [Primer](https://github.com/primer/components/), uses it, and it looks like it works well. We'll need to investigate whether we can get proper tree shaking in `vets-website` when we use Rollup to bundle all the components and dependencies together in a single ES module like Primer does.

---
## Tasks
- [ ] Use Rollup (or similar) to bundle the components into a git-ignored `dist/`
- [ ] Ensure we get tree shaking in `vets-website` when using the component library
- [ ] Modify the publish process to publish from `dist/`

## Acceptance Criteria
- [ ] No (or minimal) additional file size increase is seen on application bundles using the component library
- [ ] The component library uses a maintained JavaScript bundler for building the components for distribution

**Comment by bkjohnson** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/837
