### ISSUE TITLE
Investigate date-fns tree shaking

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#20060]
## Issue Description
When we [introduced `date-fns` to the maintenance banner](https://github.com/department-of-veterans-affairs/vets-website/pull/16043), it apparently added the whole library to the application bundles. I investigated this for a while and put my discoveries in a [Slack thread](https://dsva.slack.com/archives/GLDNCMRSP/p1613423077097300), but I didn't ever figure out what the cause was.

---
## Tasks
- [ ] Determine whether the issue is indeed that tree-shaking isn't working on the `date-fns` dependency when building application bundles
- [ ] Figure out the cause
- [ ] Propose or implement a solution
