### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK" for VA West Texas health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20074]
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA West Texas health care [BA]

## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[West Texas healthcare system Legacy Site](https://www.westtexas.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-17 Playbook locations](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_519	George H. O'Brien, Jr., Department of Veterans Affairs Medical Center
- [x] vha_519GA	Wilson and Young Medal of Honor VA Clinic
- [x] vha_519GB	Hobbs VA Clinic
- [x] vha_519GD	Fort Stockton VA Clinic
- [x] vha_519HC	Abilene VA Clinic
- [x] vha_519HF	San Angelo VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
03012021 - Removed Stamford VA Clinic. The VHA-VAST does not have Stamford VA Clinic listed however the legacy site does.  It was recommended to remove as "It appears that either this clinic was incorrectly listed under West Texas or is no longer in operation".
