### ISSUE TITLE
[FE] Investigate reason for 'Address line too long' update errors in Profile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20079]
## Background
We (the VA.gov front end) are seeing some instances of address update failures happening due to the street line 1 being too long. In the past week it looks like one person tried seven times to save their address but kept getting blocked. We limit each street line to 35 characters in the FE. But we run all user-input addresses through address validation first. 

See: [slack convo](https://dsva.slack.com/archives/C7TE0PFTL/p1613427271071600)
See [slack convo 2](https://dsva.slack.com/archives/C7TE0PFTL/p1613488754081700)

Lihan has created an issue to track/log addresses/instances that trigger the "address is too long error" - See ticket #20025 

## Tasks
- [x] Investigate logged issues from BE ticket
- [x] Determine what is causing these errors
- [ ] Work with Matt to create ticket for next steps

**Comment by Samara-Strauss** [comment]
No immediate action required. Adding to next sprint, though do let us know if you tackle this sooner.

**Comment by Samara-Strauss** [comment]
Cross posting for awareness: Lihan has added backend tracking for this issue in #20025

**Comment by lihanli** [comment]
i was able to reproduce the error, the address validation api does give address suggestions that are over 35 characters long

**Comment by erikphansen** [comment]
We are going to need to follow up with VA Profile on this. I'll try to summarize what is happening:

1. A user enters an address with an Address Line 1 length of less than 35 characters
2. We send that address to the validation API to check its validity
3. The validation API returns a _single, confirmed, high-confidence_ address (and that suggested address has an Address Line 1 length greater than 35 characters)
4. We take the suggestion from the validation API and send it to the update endpoint
5. The request to update fails because the Address Line 1 is too long

In summary: As Lihan said, the address validation API can return addresses that are too long and violate VA Profile's rules. Worth noting: even if you _bypassed the validation API_ and sent the address from item 1 directly to the update endpoint, the update would still fail because VA Profile runs that address through validation before saving anyway (they have done this for as long as I've been on this project).

Possible solutions:
1. VA Profile totally drops this 35 character limit
2. VA Profile gives us some way to get around the 35 character limit
3. VA Profile adjusts the validation API to never return address lines that are longer than 35 characters and/or breaks long address lines into multiple lines/fields
4. We (and any other client that saves addresses with VA Profile) updates our logic to shorten addresses from the validation API if they have lines longer than 35 characters or break long address lines into multiple lines/fields
5. ???

**Comment by lihanli** [comment]
how about when we get an address suggestion from the validation API that is too long, we ignore the suggested address but use the validation override key to update to the user's entered address?

**Comment by erikphansen** [comment]
Oh, smart. I'll add that to my list! But VA Profile needs to know about this issue as well.

**Comment by Samara-Strauss** [comment]
@erikphansen thank you for this. We should prob set up a short call with VA Profile to talk about this, as I think it might be too complex to address in Slack (given there are a few potential solutions).

@mshea0606 could you create a ticket for the sprint starting tomorrow that addresses following up with VA Profile about this issue? Please copy over Erik's explanation of the problem and potential solutions. The goal of that ticket is to get a meeting with VA Profile on the calendar, and have a determined path forward. We can create additional tickets from there if there is work required for our team beyond that point.

**Comment by mshea0606** [comment]
i just made this ticket [PM] Follow up with VA Profile Re: "Address line too long" errors #20397

**Comment by Samara-Strauss** [comment]
This ticket should be OK to close.

**Comment by mshea0606** [comment]
@erikphansen  can you drop an estimate in here when you get a chance? Thanks!
