### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK" for VA El Paso health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20072]
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA El Paso health care [BA]

## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[El Paso healthcare system Legacy Site](https://www.elpaso.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-17 Playbook locations](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_756	El Paso VA Clinic
- [x] vha_756GA	Las Cruces VA Clinic
- [x] vha_756GB	El Paso Eastside VA Clinic
- [x] vha_756GC	El Paso Westside VA Clinic
- [x] vha_756GD	El Paso Northeast VA Clinic
- [x] vha_756QA	El Paso South Central VA Clinic
- [x] vha_756QB	El Paso Central VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#20072 - Create new Health Services "LIST, PLAYBOOK" for VA El Paso health care [BA] - is Complete and moved to Validate
