### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK" for VA South Texas health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20070]
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA South Texas health care [BA]

## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[South Texas healthcare system Legacy Site](https://www.Southtexas.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-17 Playbook locations](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_671	Audie L. Murphy Memorial Veterans' Hospital
- [x] vha_671A4	Kerrville VA Medical Center
- [x] vha_671BY	Frank M. Tejeda Department of Veterans Affairs Outpatient Clinic
- [x] vha_671GB	Victoria VA Clinic
- [x] vha_671GF	South Bexar County VA Clinic
- [x] vha_671GH	Beeville VA Clinic
- [x] vha_671GK	San Antonio VA Clinic
- [x] vha_671GK01 San Antonio-Northeast 410 VA Clinic
- [x] vha_671GK02 San Antonio-Southwest Military VA Clinic
- [x] vha_671GK03 San Antonio-Pecan Valley VA Clinic
- [x] vha_671GL	New Braunfels VA Clinic
- [x] vha_671GN	Seguin VA Clinic
- [x] vha_671GO	North Central Federal VA Clinic
- [x] vha_671GP	Balcones Heights VA Clinic
- [x] vha_671GQ	Shavano Park VA Clinic
- [x] vha_671GR	North Bexar VA Clinic
- [x] vha_671QA	South Texas VA Mobile Clinic
- [x] vha_671QB	Data Point VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
Updated facility name from Bexar County VA Clinic to South Bexar County VA Clinic

**Comment by bcastoe** [comment]
Updated facility name from San Antonio-Southeast 410 VA Clinic to San Antonio-Northeast 410 VA Clinic

**Comment by bcastoe** [comment]
Updated facility name from San Antonio--west Military VA Clinic to San Antonio-Southwest Military VA Clinic

**Comment by bcastoe** [comment]
Updated facility name from South Central Federal VA Clinic North Central Federal VA Clinic

**Comment by bcastoe** [comment]
Updated facility name from Texas VA Mobile Clinic to South Texas VA Mobile Clinic
Updated facility name from South Bexar VA Clinic to North Bexar VA Clinic

**Comment by bcastoe** [comment]
#20070 - Create new Health Services "LIST, PLAYBOOK" for VA South Texas health care [BA] - is Complete and moved to Validate
