### ISSUE TITLE
Make changes to Entrepreneurship Training page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20084]
## Issue Description
We need to remove references to the Small Business Liaisons answering questions about training on the  [Entrepreneurship Training](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/entrepreneurship-training/) page. 

To do this we should remove the entire question "How do I get this training?" And move the eligibility section out of the blue box into a main content block. 

Luke Tickner is getting more information about how Veterans can get this training. Once he has that we will add back in the the question "How do I get this training?" and move the eligibility question back into the blue box. 

## Tasks
- [x] Remove question and move eligibility info out of blue box (Randi)
- [x] Review and publish (Randi)
- [x] Let stakeholders know page is published (Beth/Randi)

## Acceptance Criteria
- [x] Live page has old H2 removed

**Comment by RLHecht** [comment]
This work has been finished. Creating ticket for tracking purposes.

**Comment by RLHecht** [comment]
Change is live. Closing ticket. FYSA @bethpottsVADEPO
