### ISSUE TITLE
Remove R&S articles from life insurance left nav

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20081]
## Issue Description
We need to remove the 2 life insurance R&S articles we added to the life insurance left nav. Having them in the left nav is causing the breadcrumbs to be incorrect on those two articles within R&S. We will leave the links to them on the LI hub landing page though. 

![Screen Shot 2021-02-17 at 10.34.42 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/bd135c89-c20c-40bc-bf3e-cdad602ef6b9)

The two articles to remove: 
[Deciding how much life insurance to get](https://www.va.gov/resources/deciding-how-much-life-insurance-to-get/)
[Life insurance if you have preexisting conditions](https://www.va.gov/resources/life-insurance-if-you-have-preexisting-conditions/)

## Tasks
- [x] Remove 2 articles from left nav (Randi)
- [x] Review and publish (Randi)
- [x] Notify Mikki when breadcrumbs are fixed (Randi/Beth)

## Acceptance Criteria
- [x] Articles removed from left nav and breadcrumbs showing correctly on live site

**Comment by RLHecht** [comment]
@mnorthuis @bethpottsVADEPO I removed these two articles from the left nav to fix the breadcrumbs issue we were having. Moving to validate and will close after today's deployment.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
