### ISSUE TITLE
Content updates to Direct Deposit page for Auth Exp/eBenefits team-Hold to publish

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20096]
## Issue Description
We need to update content on [Direct deposit](https://www.va.gov/change-direct-deposit/) to support work for the Authenticated Experience/eBenefits team. The eBenefits widget needs to be removed and there are minor text changes to support the new line of business that was added. The page should match this mockup: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/72860e86-bed9-4e10-8794-223ebb03794f/

More information is in the intake request ticket #17826

## Tasks
- [x] Remove eBenefits widget and make content updates to match mockup shown above (Randi)
- [x] Review and publish changes (Randi)
- [x] Notify product team that changes will be live (Randi)

## Acceptance Criteria
- [x] Live page matches mockup

**Comment by mshea0606** [comment]
Hi @RLHecht, I wanted to give update you on our start date for UAT...3/10.

**Comment by Samara-Strauss** [comment]
@RLHecht I'm stepping in for now now that Matt's rolled off the team. Question for you — how do we typically handle content updates when we are doing UAT and a phased rollout of the feature? Does the content go out with UAT, at the beginning of the phased rollout to production, or at the end of the phased rollout to production when we've launched to 100% of users? Just trying to figure out what I should expect so I can check back in accordingly.

**Comment by Samara-Strauss** [comment]
**Update: Please do not publish this 3/9.** That is around the date we are going to UAT, not when we are going to 100%. We should not push this until the direct deposit for edu feature is available to all users.

**Comment by Samara-Strauss** [comment]
@RLHecht I wanted to check in about this — is this page good to go for when we're ready to launch direct deposit to 100% of users? Or do you need any guidance/help from design or frontend? We want to make sure we're in good shape to go when the time comes.

Speaking of which, our anticipated go-live date for 100% of users is **April 21**. I can confirm as that gets closer.

**Comment by RLHecht** [comment]
@Samara-Strauss I'll still need to rework the page in Drupal, but as long as what it should look like still matches the Mockup that's in this ticket (only one sign-in widget and nothing separate for education benefits), it should be an easy fix. I don't want to make the changes to the page just yet in case it were to accidentally get published without someone realizing it wasn't ready yet (we've had this happen a few times!). I'd rather wait until closer to the launch date to make the changes if that's all right with you..

**Comment by Samara-Strauss** [comment]
> but as long as what it should look like still matches the Mockup that's in this ticket (only one sign-in widget and nothing separate for education benefits), it should be an easy fix

Yep! The mockup looks accurate to me, and the [new content is already live on staging](https://staging.va.gov/change-direct-deposit/), so you can always check that for reference.

How much time do you need to get this updated before our go-live to 100%? I think it's very likely we'll track on time for that and be ready on April 21.

**Comment by RLHecht** [comment]
I can have it set up the day before. It's really a minimal lift of just updating the content and removing one of the widgets.

**Comment by Samara-Strauss** [comment]
Great! Then we'll count on you having things ready on 4/20 for our 4/21 phase up to 100% of users.

**Comment by Samara-Strauss** [comment]
cc/ @ajakabcin we should be all set here

**Comment by RLHecht** [comment]
@Samara-Strauss Just confirming that you are still set to launch at 100% on Wednesday 4/21. Do you want to wait for a set amount of time after deployment to ensure it is working before we publish the how to apply page with the new info? Or we can publish right after the form is live at 100%?

**Comment by Samara-Strauss** [comment]
> Just confirming that you are still set to launch at 100% on Wednesday 4/21.

Yep! We are :D 

> Do you want to wait for a set amount of time after deployment to ensure it is working before we publish the how to apply page with the new info? Or we can publish right after the form is live at 100%?

You can publish right away after launch. I will keep you posted when the feature flag has been flipped.

**Comment by RLHecht** [comment]
@Samara-Strauss Question for you: I noticed that much of the content on the page is now in a react widget. @lunascoop reworked the page so all the text but the apply box info is back in Drupal. When she checks the box in Drupal to make it a CTA widget, the page looks as you want it to on staging. When you flip the feature flag on your end, what is it switching the content to? I just want to make sure we won't have duplicate text and everything will be showing the way you want it to. Happy to jump on a call if this isn't making sense in writing.

**Comment by Samara-Strauss** [comment]
When the feature flag is flipped on our end, the content is updated so that it directs people to the VA.gov profile for both direct deposit for comp & pen and direct deposit for edu. [You can view that here by signing into staging with any staging user](https://staging.va.gov/change-direct-deposit/).

As for duplicate content, I have no idea how the whole react widget thing works. We only did that to accommodate our phased launch, but we won't need it anymore after going to 100%. If you have specific questions about this or if we need to undo the React work, I would check in with @erikphansen about that.

**Comment by RLHecht** [comment]
@erikphansen We took out all the content from the react widget that is not in the gray and green box directing users to sign in and put it as a regular content block within Drupal. If we check the box on the react widget to make it a CTA widget, our preview shows that the page will look as it is intended and matches what's in staging. I think @lunascoop and you walked through this a few weeks ago for the phased launch. Just confirming that whatever your team does with the feature flag doesn't have anything to do with the widget and it wouldn't be showing duplicate content or anything on the page.

**Comment by erikphansen** [comment]
@RLHecht @lunascoop That sounds correct!

Just to recap, right now, everything that's highlighted in blue is from the "direct deposit" React widget that @lunascoop set up for me a few weeks ago:

<img width="720" alt="dd widget" src="https://user-images.githubusercontent.com/20728956/115485782-36575d80-a20a-11eb-9b41-67ac155d0904.png">

After we flip this to 100% (any time after, there is no rush at all as the React widget that's currently there will continue to work fine) you can update things on the Drupal side so that the content in the red boxes is static content set in the CMS and the content in the blue box is a "Direct Deposit CTA widget" (I don't remember exactly how you set that up in the CMS):

<img width="717" alt="Screen Shot 2021-04-20 at 6 52 01 PM" src="https://user-images.githubusercontent.com/20728956/115485853-52f39580-a20a-11eb-9bc1-0932e022724a.png">

Does that line up with what you were thinking?

**Comment by Samara-Strauss** [comment]
Good morning! The feature flag has officially been flipped so 100% of users should see direct deposit for edu on VA.gov! We are ready to go live with the content whenever you are.

**Comment by RLHecht** [comment]
Congrats! We will publish this for the next deploy and confirm everything looks OK with the content moved into Drupal.

**Comment by RLHecht** [comment]
Page is published. Will validate and close after next deploy.

**Comment by RLHecht** [comment]
Changes are live and all looks good. Closing ticket.

**Comment by erikphansen** [comment]
Looks good to me, too! Thank you.
