### ISSUE TITLE
COVID-19 vaccine page: Add links to FDA and CDC vaccine safety info in other languages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20092]
## User story
As a Veteran or caregiver with limited English proficiency, I need access to vaccine safety information in my first language.

---
## Tasks
- [x] Add links (Danielle)
- [x] Review link labels and URLS and publish (Randi)

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I've added these links to the page. Could you review and publish? Thank you!

 ![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/2718afc4-2f2f-4c90-8d91-16acb4526f8f)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA These links and the text all look good to me. I've published the page.

**Comment by DanielleThierryUSDSVA** [comment]
Yay! Thank you, as always, @RLHecht!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
