### ISSUE TITLE
[UI] Error Messages or Character Limits when FHIR Size Limit Reached

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#20105]
## User Story
- As a Veteran, I need to know when I've reach the 1MB FHIR limit and can't submit my questionnaire.

## Related Documentation
 - [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
A wireframes set for error messages or character limits UI on form fields will be delivered with the technical specifications needed for engineering to implement said feature.
- [For Reference](https://gist.github.com/khaykov/a6105154becce4c0530da38e723c2330) 

## Tasks
- [x] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [X] Complete a content review by sending Peggy Gannon a message within the vfs-platform-support channel and tagging her within the comments section of this story (Not doing, since Mark is looking into the preferred method mentioned in the comments)

## Acceptance Criteria
- [X] UI review meeting with product/team for feature capabilities - dealt with through ticket comments
- [X] UI review meeting with engineering for layout and callouts (can be the same meeting as above) - dealt with through ticket comments
- [X] Published mockup link exists and it is added/updated within the product feature outline - dealt with through ticket comments
- [X] Feedback from content is incorporated into the mockup - Not needed

**Comment by kristenmcconnell** [comment]
Met with engineering. Going to look into what other teams do for an error state when a form is submitted and its size is too large. We had a 1MB cap on each form field.

**Comment by kristenmcconnell** [comment]
## Preferred UX experience...
Put a limit on the number of characters that a user can enter into a field. If a user hits the character limit, then the field just stops them from entering anything more. They will never be able to go past the limit.

## Alternative for MVP
 Custom error message upon submission.

### Scenario 1 (if only one field name is too large)
**We can't submit your questionnaire right now.**
Your answer to "[field name]" is too large. Please delete some text, then submit your questionnaire again.

For [Field name], I would like to put in the full question, so the possibilities would be...
1. Are there any additional details you’d like to share with your provider about this appointment?
2. Are there any other concerns or changes in your life that are affecting you or your health?
3. Do you have a question you want to ask your provider?

_My assumption is that we don't want for MVP to be more specific than "some text." Otherwise, we could let them know how many characters they need to delete._

### Scenario 2 (if two field names are too large)
**We can't submit your questionnaire right now.**
Your answers to "[field name]" and "[field name]" are too large. Please delete some text, then submit your questionnaire again.

### Scenario 3 (if all three field names are too large)
**We can't submit your questionnaire right now.**
Your answers to "[field name]," "[field name]," and "[field name]" are too large. Please delete some text, then submit your questionnaire again.

Grammatically, the punctuation would need to disappear from the [field name] in Scenario 3. Therefore, here is an alternate. This could also be used for all three scenarios. The sentence would just be "Your answer is..." if there was only one [field name] affected.
**We can't submit your questionnaire right now.**
Your answers are too large for:
- [field name]
- [field name]
- [field name]

Please delete some text, then submit your questionnaire again.

@mdewey @abuckley3385

**Comment by kristenmcconnell** [comment]
At stand-up on March 5, @mdewey stated that he will look into UX's preferred method.

**Comment by mdewey** [comment]
https://images.zenhubusercontent.com/133843125/0ab7ce73-6b7e-4331-8443-0c673ef692dd/screen_recording_2021_03_05_at_4_09_45_pm.mov


This is some built-in functionality of the forms library.  We can set an upper limit of whatever think (something less than a megabyte of text)

**Comment by kristenmcconnell** [comment]
@mdewey Built-in functionality is good. Let's go with that. It will stop the users from causing an error on submission.
