### ISSUE TITLE
Launch Checklist for Custom Tracks

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#20118]
## Issue Description
Checklist for launching the new custom tracks enhancement to the Collaboration Cycle.
---
## Tasks

- [x] (Allison)The following markdown files have been reviewed for content (tone, voice, plain language), have been added to va.gov-team/platform/working-with-vsp/vsp-collaboration-cycle github location, and are linked appropriately:
   - [x] Getting Started with the Collaboration Cycle (Shira) 
   - [x] Touchpoint - Design Intent
   - [x] Touchpoint - IA Request
   - [x] Touchpoint - Analytics Request 
   - [x] Touchpoint - Midpoint Review
   - [x] Touchpoint - Research Plan Review
   - [x] Touchpoint - Contact Center Review
   - [x] Touchpoint - Staging Review
   - [x] Touchpoint - Full Accessibility & 508 Office Audit
   - [x] Touchpoint - Post-launch Check-in
   - [x] README.md (VSP Collaboration Cycle) (Shira) (still need to add many links)
- [ ] (Shira) The following markdown files have been reviewed for content (tone, voice, plain language), have been added to va.gov-team/.github/ISSUE_TEMPLATE/ github location, and are linked appropriately:
   - [x] Issue template - Collaboration Cycle Kickoff 
   - [x] Issue template - Design Intent (Allison)
   - [x] Issue template - Midpoint Review (formerly Usability Testing Prep) (Allison)
   - [x] Issue template - Staging Review (Allison)
   - [x] Issue template - Full Accessibility & 508 Office Audit
   - [x] Issue template - IA Request (update Platform Collaboration Point Tracker link only)
   - [x] Issue template - Analytics Request (update Platform Collaboration Point Tracker link only)
   - [x] Issue template - Contact Center Review (update Platform Collaboration Point Tracker link only)
   - [x] Issue template - Privacy & Security Review (update Platform Collaboration Point Tracker link only) (located here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/.github/ISSUE_TEMPLATE)
- [x] (Allison) The following markdown file have been reviewed for content (tone, voice, plain language), has been added to va.gov-team/platform/working-with-vsp/vsp-collaboration-cycle/cc-changes github location, and is linked appropriately:
   - [x] February 2021 release
- [x] (Allison) The following markdown file has been moved to va.gov-team/platform/working-with-vsp/vsp-collaboration-cycle/archive github location:
   - [x] vsp-collaboration-cycle-visual.pdf
- [x] (Shira) Channel topic in #vfs-platform-support has been updated to add "Collaboration Cycle: @vsp-product-support-members"
- [x] (Shira) Channel topic in #vfs-platform-support has been updated to remove Content & IA
- [X] (Shira) Collaboration Cycle Office Hours has been added to VSP Collaboration Meetings Calendar at 11:30am-12:00pm ET Wednesday 
- [X] (Shira) The CALENDAR BLOCK on the VSP Collaboration Meetings Calendar for 11:30am-12:00pm ET has been removed.
- [x] (Shira) The Slack announcement has been posted in #vfs-all-teams and #vfs-platform-support
- [x] Research Synthesis - location TBD
- [x] Make modifications to the Platform Collaboration Point Tracker to reflect change in touchpoint names, and to add responses from VFS re CC Kickoff
- [x] Archive vsp-collaboration-cycle.md

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034  I still need to add assignments, and possibly a couple additional items.
