### ISSUE TITLE
Test User Accounts_Mock Up revisions

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#20113]
## Issue Description
Design revisions to mock up of TUD with focus on expanding rows on table and Services section of modal

## Tasks
- [x] Consistent look and feel of content (from modal to table)
- [x] Mock up options to copy/paste password
- [x] Mock up options of hover or toast to show more information in drop down

## Acceptance Criteria

- [x] Content in drop down is clear and consistent with Modal
- [x] Table to be compared with design system to ensure consistency

**Comment by APorter-Clarity** [comment]
![Screen Shot 2021-03-10 at 4.00.46 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/76f32152-2d4a-471b-a5cf-e930f7d6c33e)

**Comment by APorter-Clarity** [comment]
![Screen Shot 2021-03-10 at 4.01.19 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/f93859ec-8b02-46ad-8a24-b6ed9769bb37)

**Comment by APorter-Clarity** [comment]
![Screen Shot 2021-03-10 at 4.08.04 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/78ed827e-d9aa-485f-b5ff-3eef3fde26db)

**Comment by APorter-Clarity** [comment]
[Uploading... Screen Shot 2021-03-10 at 4.11.44 PM.png]

**Comment by APorter-Clarity** [comment]
![Screen Shot 2021-03-10 at 4.11.44 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/097e3cbf-ac08-448f-a7ef-b9e5f199b4b3)
