### ISSUE TITLE
Test User Accounts_Usability Testing Week 2

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#20115]
## Issue Description
Usability testing February 15- March 1

## Tasks

- [x] Schedule tests
- [x] Use guide to receive feedback about functionality of prototype
- [x] Synthesize notes from test to share with team
- [x] Prep for next phase of testing

## Acceptance Criteria
- Conduct testing with participants on the following dates:

- [x] Th 2/25 12:30pm ET
- [x] Th 2/25 2:30pm ET
- [x] Fri 2/26 11:30am ET
- [x] Fri 2/26 3:30pm ET
- [x] Mon 3/1 12:00pm ET **60min
- [x] Mon 3/1 4:00pm ET
