### ISSUE TITLE
Test User Dashboard - Account Addition & Creation Guide

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#20114]
## Issue Description
The TUD MVP will not include CRUD functionality; users wishing to create new test accounts will have to contact various IDPs and VA service providers to have them manually add new accounts. In order to streamline this process and make it as easy as possible for users to request new accounts a guide detailing the process should be created.

---
## Tasks
- [x] An account creation guide is added to the TUD frontend application's repository as a markdown file
- [x] The guide will establish the TUD application as the primary "source of truth" for finding and using test accounts
- [x] The guide will link to the [current PW list](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) for cases where a user is seeking additional test accounts, but will warn that accounts are not fully supported like ones in the TUD application are
- [x] The guide includes a section on requesting the addition of currently-unsupported accounts to the TUD application (via a GitHub issue request to go through Peter Hill/Joe Tice)
- [x] The guide includes a section on requesting the creation of a new test account (via a GitHub issue request to go through Peter Hill/Joe Tice)

## Acceptance Criteria
- [x] Users using the TUD frontend application or browsing its GitHub repository will be able to follow a guide to find additional unsupported accounts
- [x] Users using the TUD frontend application or browsing its GitHub repository will be able to follow a guide to add currently-unsupported accounts to the TUD application
- [x] Users using the TUD frontend application or browsing its GitHub repository will be able to follow a guide to request the creation of new test accounts

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
The new documentation consists of three documents, a user guide for adding new or existing test accounts and two Github issue templates, one for adding existing accounts and one for creating new accounts:


Guide to requesting additional test accounts: https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/blob/main/src/markdown/requesting-additional-test-accounts.md

Add existing user Github issue template: https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/blob/main/.github/ISSUE_TEMPLATE/add-existing-test-user.md

Create new user Github issue template: https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/blob/main/.github/ISSUE_TEMPLATE/create-new-test-user.md
