### ISSUE TITLE
[LINTING]: Write an ESLint rule to warn when e2e tests do not have at least one axeCheck call

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20124]
## Issue Description
End-to-end tests are required to include axe checks per our ATO. We want to ensure all Cypress e2e tests warn (and later error) when users do not include at least one `cy.axeCheck()` call.

---
## Tasks
- [ ] Write an ESLint warning rule
- [ ] Test ESLint rule message with peers
- [ ] Update documentation defined in #20119 to include mention of the ESLint rule

## Acceptance Criteria
- [ ] ESLint rule has been socialized with teams, including a timetable for moving from warn to error
- [ ] Verify the rule notifies correctly

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
This was completed under a separate ticket.
