### ISSUE TITLE
vsa-eben-migrations VRE cert and key

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#20128]
## Issue Description

During an open office session with VSP recently, I asked about certificates/keys and how to get them on the platform. I was advised to do a few things, one of which was to get this ticket submitted.

This is for the [ebenefits migration team](https://dsva.slack.com/archives/CLY6Q69RV). We are building a new integration with a VA group 'CMS/VRE. They have informed us that they want to verify a cert and list of IP's for security reasons. I have created a cert/pem that I need to provide to VSP via keybase so they it can be uploaded to credstash.

---
## Tasks
- [x] Message me (Derek Dyer) on slack or keybase(digitaldrk) so I know who to give the creds to for upload to credstash
- [x] Upload creds to credstash

## Acceptance Criteria
- [ ] Credentials are available in staging for PR to utilize

**Comment by jhouse-solvd** [comment]
Related ticket that @digitaldrk is working on: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/19606

**Comment by jsev-io** [comment]
@digitaldrk I've contacted you on keybase for the credentials. I'll get them in there upon delivery. Thanks!

**Comment by jsev-io** [comment]
Update Keys have been entered into credstash and request is complete!
