### ISSUE TITLE
Staging Review [VAMC - Salt Lake City health care]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20132]
Staging Review [VAMC- Salt-Lake-City-health-care]

## Steps to complete Staging Review: 
**VAMC-upgrade product iterations do not require all areas of collaboration staging review**
- [x] design (Not applicable, No Design changes since Pittsburgh build)
- [ ] Accessibility - requested to be complete while in dual-state
- [ ] Content - Required 
- QA (Not applicable, no changes to product since Pittsburgh build) 
- product - (Not applicable)
- [x] analytics (Requested separately.  Will duplicate same as Pittsburgh build, while in Dual-state) 
- [x] engineering - (Not applicable)
- [x] information architecture - (Not applicable, No IA changes from ORIGINAL build)

- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bold information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team
- [ ] VFS: Completes attached feedback tickets based on acceptance criteria in each practice area feedback ticket
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)
- Link to release:  Not Applicable: [See VAMC Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Dual-State_RunBook_2020.1.21_Final.xlsx)

- Access information: Site can be seen in Tugboat [Here](https://web-rwfjfd1ipjp1vdgr5yod4wtu6h2gnnzq.demo.cms.va.gov/salt-lake-city-health-care/)
* [Foundation 508 check](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/508_checks)
- ~~Link to your product test cases/test plan in TestRail~~ - N/A 
- ~~Link to your [Coverage for References] reports in TestRail _for QA~~ - N/A
- Link to verification that accessibility checks are complete:  - 508 Accessibility checks complete in Dual State.
  
## Meeting attendees from **requesting team**
- Product Manager (required): **Stan Gardner**
- OCTO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **names**

## Scheduling

- [x] Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 4 business days from now
- [x] Please feel free to book anytime in Calendar open to discuss with Stan Gardner and David Conlon**

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: ~~design~~, accessibility, content, ~~QA~~, and optional: ~~product, analytics, engineering, information architecture~~

**Comment by SgardnerPMP** [comment]
Please see foundation 508 check link to find testing for Salt Lake City.

**Comment by shiragoodman** [comment]
Thanks @SgardnerPMP. Like we did with Eastern Oklahoma, my team will now begin our review and will get our feedback to you by next Thursday 3/18. Please reach out if you have any questions or concerns.

**Comment by peggygannon** [comment]
Hi, @SgardnerPMP I want confirm which pages I should look for my this review. In my last VAMC content reviews, I looked at the following sections. Please advise if I should do the same for Salt Lake City VAMC?  thx. 

 About us
 History
 Suicide Prevention
 Pharmacy
 Billing and Insurance
 Mental Health

**Comment by peggygannon** [comment]
hi, @shiragoodman and @SgardnerPMP I don't have access to Tugboat to see these files. Can I be granted access? or am I able to see this content on Prod?

**Comment by SgardnerPMP** [comment]
Hi @peggygannon , what files are you looking for?  if it is just salt-lake city you should be able to access them in prod.cms.va.gov.  If you want to see them in action, please tell me and I can send you the Dual-state link.

**Comment by peggygannon** [comment]
HI, @SgardnerPMP OK, thanks. I was looking for the Salt Lake City content by clicking on the Tugboat link above. But thank you for letting me good to know that I can access them at prod.cms.va.gov.

**Comment by mnorthuis** [comment]
Hi @SgardnerPMP, no formal IA review was part of this touchpoint, but just wanted to give you a heads up on a few things I spotted in case you weren't aware...Many of these are the same from the last VAMC launch. I have bolded questions/concerns where it would be helpful to understand the plan for them as you continue to roll out more sites. 

- Patient advocate pages have the wrong URL, all should have "/health-services/" in the URL path (i.e. www.va.gov/salt-lake-city-health-care/health-services/minority-veteran-care/). **Can these be corrected prior to retiring the legacy site and before too many more VAMC sites are launched so we don't have to deal with redirects?**
- Patient advocate pages aren't linked to from the health services page - the text to "Learn more" is there, but isn't linked.
- Suicide prevention page appears in the left nav accurately and with an accurate breadcrumb, but the URL is not accurate and does not reflect the "/health-services/" directory.   **Also, no other health services have appeared in the left nave before, is this intentional? If so, is it intentional for only this page?**
- Breadcrumb on [Operating status page](https://www.va.gov/salt-lake-city-health-care/operating-status/) is missing the current page, and the previous page is not clickable - **this must be fixed.**  Also could not find a link to this page from any other page - **where is the entry point?**
- URL of the primary VAMC is truncated. **Are we now ok with truncating legal names?** 
- The order of the locations in the left nav does not match the order on the locations page - left nav is in alpha order, so the main does not appear first, this is different than other sites.  **Is this a revised approach for this?**
- The [About Us](https://www.va.gov/salt-lake-city-health-care/about-us/) page has a different URL than other VAMC sites. **If this is the new URL for these sites, please confirm so documentation can be updated appropriately.**  
- URLs for all pages nested under "About us" are incorrect, they should all have /about in the URL.  **Can these be corrected prior to retiring the legacy site and before too many more VAMC sites are launched so we don't have to deal with redirects?**
- URLs for all pages nested under "Work with us" are incorrect, they should all have /work-with-us in the URL.  **Can these be corrected prior to retiring the legacy site and before too many more VAMC sites are launched so we don't have to deal with redirects?**

**Comment by SgardnerPMP** [comment]
Thank you @mnorthuis  and @peggygannon,  Thank you so very much, we implementing these now, as a team we have some questions as the IA was following the original Pittsburgh layout as well as the design layout, so I think it would be great to have a quick sync on these items in question and get your input and direction to move forward.  I will set a meeting up with Dave and key team members and we will roll out the changes.

**Comment by shiragoodman** [comment]
thanks @SgardnerPMP !
