### ISSUE TITLE
Staging Review [VAMC upgrade - Sheridan-health-care]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20133]
Staging Review [VAMC- sheridan-health-care]

## Steps to complete Staging Review: 
**VAMC-upgrade product iterations do not require all areas of collaboration staging review**
- [x] design (Not applicable, No Design changes since Pittsburgh build)
- [ ] Accessibility - requested to be complete while in dual-state
- [ ] Content - Required 
- QA (Not applicable, no changes to product since Pittsburgh build) 
- product - (Not applicable)
- [x] analytics (Requested separately.  Will duplicate same as Pittsburgh build, while in Dual-state) 
- [x] engineering - (Not applicable)
- [x] information architecture - (Not applicable, No IA changes from ORIGINAL build)

- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all artifacts before requesting the meeting
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team
- [ ] VFS: Completes attached feedback tickets based on acceptance criteria in each practice area feedback ticket
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)
- Link to release:  Not Applicable: [See VAMC Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Dual-State_RunBook_2020.1.21_Final.xlsx)

- Access information: Site can be seen in Tugboat [Here](https://web-rebdedmp20fkowud7guilvoglhzuddtd.demo.cms.va.gov/sheridan-health-care/)
- ~~Link to your product test cases/test plan in TestRail~~ - N/A 
- ~~Link to your [Coverage for References] reports in TestRail _for QA~~ - N/A
- Link to verification that accessibility checks are complete:  - 508 Accessibility checks complete in Dual State.
  
## Meeting attendees from **requesting team**
- Product Manager (required): **Stan Gardner**
- OCTO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **names**

## Scheduling

- [x] Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 4 business days from now
- [x] Please feel free to book anytime in Calendar open to discuss with Stan Gardner and David Conlon**

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: ~~design~~, accessibility, content, ~~QA~~, and optional: ~~product, analytics, engineering, information architecture~~
