### ISSUE TITLE
Add Pension Form Number to 686 Confirmation Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20144]
`confirmed with Steve and stakeholders`

## Background
On the final confirmation screen, the 686 and the 674 are noted as being submitted and we now need to ensure that the 21P-527EZ is also included for pension submissions.

## Considerations
<Details>

<Summary>Expand for current example without pension form inclusion</Summary>

![add-527.JPG](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/d9c69974-c035-4e10-b987-5d0ad1c248f5)

</Details>

## Tasks
- [x] Incorporate the 21P-527EZ in the final confirmation text language after the 674 and 686 disclosure:
_"....and/or Application for Veterans Pension (Form 21P-527EZ)"_
- [x] Also on the intro page and at the top

## Acceptance Criteria
- [x] All applicable forms are shown on the confirmation page
- [x] A PR has been requested for merging

**Comment by micahchiang** [comment]
![Screen Shot 2021-03-10 at 3 39 04 PM](https://user-images.githubusercontent.com/15097156/110694572-c55a6a00-81b6-11eb-9f5f-e772a0028f63.png)

@jason-gcio @sporeboy - what should this sub text be updated to? `VA Form 21-686c (and 21-674 and 21P-527EZ)` doesn't exactly roll off the tongue lol.
