### ISSUE TITLE
TUD - Add an expand/close all rows button

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20149]
## Issue Description
As a user, I would like to have a button that can expand/close all rows of test accounts, so that I can easily compare each test account quicker.

---
## Tasks
- [x] Add a button that can expand / close all rows at once

## Acceptance Criteria
- [x] (Rows are closed/normal) I can click on an expand all button to expand each row in the Test Account table
- [x] (Rows are open/expanded) I can click on a collapse all button to collapse each row in the Test Account table
- [x] I have ensured proper accessibility and 508c standards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
