### ISSUE TITLE
TUD - Update services content in Modal

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20145]
## Issue Description
As a user, I would like to view better defined list of services for a Veteran in the Test Account Matcher modal, so that I can more easily select services that will apply to the test account I am looking for.

---
## Tasks
- [x] Sync with UX Designer (Amanda) on how to better defined the services checkboxes in the Modal
- [x] Update the services content and ensure proper functionality (might be dependent on Jim's work for adding the `services` property on the `tud_accounts` endpoint.

## Acceptance Criteria
- [ ] The services content makes sense both in the Modal & Table view.
- [ ] I have ensured proper 508c and accessibility standards.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Update:
Some of this work was completed in a previous ticket.  Reach out to Amanda to see if the Modal will change

**Comment by AGarcia-Clarity** [comment]
Update:
Sent to PM Review for close out.
