### ISSUE TITLE
[Possible Bug] Update Field Validation for Phone Number

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20140]
## Background
In testing, a strange error occurred where BGS is claiming that 12 chars are being passed when 11 is the max.  In case a Veteran enters their phone number with dashes or letters or too many of either it might exceed the limit and, possibly, a vnp table insertion might fail.

We need update the phone number field validation to account for any dashes (or letters) that might get entered by the Veteran, ensuring that only the 11 digits in a phone number are being passed.

## Considerations
- There may be a foreign number option in the same object called `frgnPhoneRfrncTxt` that allows 30 characters?
- `800-827-1000` should be `8008271000` (10 digits)
- `1-800-827-1000` should be `18008271000` (11 digits)

## Tasks
- [ ] ~~Strip away any other characters other than the 11 numbers used in a phone number~~ (Backend originally)
- [ ] Set field validation to only allow numbers, no letters, or other characters like dashes
- [ ] Set the field limit to be 11
- [ ] Be sure to address both the 686 and the 674, or anywhere else a phone numbers is used

## Acceptance Criteria
- [ ] Only a max of 11 numbers are being sent to BGS
- [ ] A PR has been requested for merging
