### ISSUE TITLE
TUD - Create a definitions and terms list on Documentation page

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20148]
## Issue Description
As a user, I would like to have a list of terms and definitions that apply to finding a test account, so that I can make better formed decisions on which terms are (un)important.

---
## Tasks
- [x] Research with UX Designer (Amanda) to create a list of definitions and terms that are not definitive
- [x] Add definitions and terms list to Markdown in the `markdown` folder

## Acceptance Criteria
- [x] I can navigate to the Documentation page and see a link for Terms & Definitions
- [x] On the Terms & Definitions page, I can see a list of terms and their meanings as it applies to the TUD website
- [x] I have ensured proper accessibility and 508c standards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Possibly duplicated by this PR https://github.com/department-of-veterans-affairs/va.gov-team/issues/19681 (refactoring Issues & Documentation page).  Reconfirm with Amanda terms and definitions.
