### ISSUE TITLE
TUD - Update columns for a Test Account

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20163]
## Issue Description
As a user, I would like the ability to additionally see the **Person Type** and an updated **Account** column, so that I can see test accounts that are not ID.me specific.

Person Type: One of = [Veteran, Dependent, etc]
Account: One of = [ID.me email, DS Logon Username, MHV User ID]

---
## Tasks
- [x] Add the Person Type to the expanded detailed view for a test account
- [x] Update the Account column to use account instead of solely on email

## Acceptance Criteria
- [ ] I can see a Person Type as a [Veteran, Dependent, etc.] in the expanded detail view
- [ ] I can see the Account of different types of logins not only ID.me
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Not sure if this is needed anymore and could be blocked until User Roles in `vets-api` are completed.

**Comment by AGarcia-Clarity** [comment]
Update:
Spoke with Amanda for closing out this ticket until required at a later date.
