### ISSUE TITLE
SSOe Login Round Trip Data Collection

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#20167]
## Epic Description
The current login process is currently missing login stats data. One reason for this is some users are closing their browser session, there are some theories that we can find out how many people are abandoning the login process through google analytics, this is not part of this ticket. The request in this ticket is to build a login tracking helper. We need a solution/method that provides the number of missing login responses.

The stats collection mostly occurs in this [class](https://github.com/department-of-veterans-affairs/vets-api/blob/2685fbf1020aaefffe324e2a50fc307f21d56897/app/controllers/v1/sessions_controller.rb). What the helper should do is 

**Login Round Trip Data Collection**
- [ ] track all "new auth" attempts and **record a unique user ID of some sort for each attempt**. The new auth stat exists, the recording of some ID to be used to match against a response doesn't.
- [ ] then record any responses (success, failure, unknown, anything that isn't a success?), what doesn't exist is anything that returns for login and doesn't fit into one our canned errors (please verify this is accurate, I was not able to verify either way). All responses must be tied back for stats purposes to an auth attempt and recorded as such.
- [ ] match the new auth up with the response, record that the process completed, or record that it didn't complete if no response of any type comes back within 30m(or some technical reasonable amount of time). This part will not be easy, and doesn't exist within our stats collection capabilities as of this ticket creation.
- [ ] write to a stats collector that can be used inside statsd indicating number of "no responses", "responses", and "percentage of response" as a result of the new "round trip collection". The key difference between this method and the current stats analysis we perform is that we don't know what users, or anything about a user, that we dont have a response for. We also don't know if a user who doesn't get a response to an auth attempt eventually gets a response on some subsequent attempt, or the next day. We need a way to track a users overall login health. This task starts that work.
- [ ] draft a stat collector model for login attempts. This model should track failed logins, ip addresses used, [device id?], login attempts (may be best to record this in interval form), login responses, more to follow. This needs to be stored in someway, no restriction on ideas of how to do this.

## Tasks
TBD

## Acceptance Criteria
- [ ] Final acceptance for the overall concept includes a graph in grafana which displays the percentage of responses that consolidates the responses and focuses on a per user instead of just total attempts vs. total responses.
- [ ] Acceptance for the first phase is a solution which allows tracking of new auth attempts per user inside of a statsd increment within [this class](https://github.com/department-of-veterans-affairs/vets-api/blob/2685fbf1020aaefffe324e2a50fc307f21d56897/app/controllers/v1/sessions_controller.rb) **AND** tracks responses to a unique user ID. The stats in the first phase should simply focus on overall numbers and not necessarily make available the ids which are having the biggest issues with a lack of a response. Phase two should include the ability to help dig into which users are having issues, and the information about them. 

## How to configure this issue
- [ ] **Labeled with Team**
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

**Comment by joeniquette** [comment]
![Screen Shot 2021-02-18 at 4.42.48 PM.png](https://images.zenhubusercontent.com/5f6a5e454ede530876cfc425/3bc8e64e-cec3-4d38-951a-684e0903dc7e)

**Comment by joeniquette** [comment]
not required
