### ISSUE TITLE
Content updates to Pre-discharge claim page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20160]
## Issue Description
Stakeholder Sandy Tadeo made several content updates to the eligibility section of the [Pre-discharge claim page](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/). We need to review and edit for plain language and VA.gov style before publishing. 

## Tasks
- [x] Review Sandy's changes and make edits (Randi)
- [x] Review changes made (Beth)
- [x] Copy edit and publish (Randi)
- [x] Alert stakeholder page is published (Randi)

## Acceptance Criteria
- [x] Changes are live on site

**Comment by RLHecht** [comment]
This page is published and changes are live on the site. Closing ticket.
