### ISSUE TITLE
Update COVID FAQs and debt management page with links for debt-related questions

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20174]
## Issue Description
In an effort to provide the most up-to-date information on COVID-19, we need to add new links to our [FAQs page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) for debt-related questions. This will go under the question "What if I can't pay my existing VA debt?" These links and new content surrounding it also needs to be added to our [Manage your VA debt page](https://www.va.gov/manage-va-debt/) underneath the widget and before the first H2.

Once these changes are made, we need to get them translated and put on our [Spanish COVID FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/) page.

We will need to do a manual content release do get these pages live before the regular deployment.

## Tasks
- [x] Add new links and content to both pages (Danielle)
- [x] Review and publish (Randi)
- [x] Send new text to translator (Randi)
- [x] Update Spanish page with new content (Randi)
- [x] Publish Spanish page (Randi)
- [x] Do content release (Randi)

## Acceptance Criteria
- [x] Changes are live on site

**Comment by RLHecht** [comment]
These changes are all live. Closing ticket.
