### ISSUE TITLE
Review and edit SME content changes to Headstones, Markers and Medallions page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20171]
## Issue Description
Stakeholder Brett Lee made content changes to the [Headstones, Markers, and Medallions page](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/) in the "Who can be honored with a medallion?" section. We need to review these changes and edit for plain language and VA.gov voice and style before publishing.

![Screen Shot 2021-02-18 at 3.58.41 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8485473f-8a6d-4599-a7bf-d8372834d285)

## Tasks
- [x] Review SME changes and edit (Randi)
- [x] Review edits (Beth)
- [x] Copyedit and publish (Randi)
- [x] Alert stakeholders that page has been published (Beth/Randi)

## Acceptance Criteria
- [x] Content changes on live site

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made changes to the edits that Brett made. Can you take a look and let me know if what I have is OK? I put a screenshot of his changes in the top of the ticket so you can see the difference. preview-prod.vfs.va.gov/preview?nodeId-859

**Comment by bethpottsVADEPO** [comment]
@RLHecht Looks good, thank you!

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close after deployment.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
