### ISSUE TITLE
VA.gov Site Map XML & Template Structured Data Issues 

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#20170]
## Why you're here 

Crawl reports from SEMRush -- and reported by Jen Lee --  have revealed issues that appear to be rooted in our Site Map and Site Templates.  Details:

- report has identified 17 of our modernized pages as missing the mainEntity field value in structured data (schema markup).

[va.gov_structured_data_that_contains_markup_errors_20210218.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6005669/va.gov_structured_data_that_contains_markup_errors_20210218.xlsx)

- report shows modernized pages coming up as non-canonical URLs (possible issue: URLs having a version with the ending slash/ and without -- the one that we put in the XML sitemap should always be the one that we set as canonical). @mnorthuis also recommends taking a look at our trailing slash use and making sure we are consistent with what the canonical/primary URL should be.

[SEMrush-Site_Audit_Incorrect_pages_found_in_sitemap_xml-va_gov-18th_Feb_2021.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6005673/SEMrush-Site_Audit_Incorrect_pages_found_in_sitemap_xml-va_gov-18th_Feb_2021.pdf)

### Frontend engineering support 

- Need a PW FE engineer to analyze the two reports to help determine (a) if these are issues which require immediate resolution and (b) how -- and which team -- should implement the resolution.
      

### Desired/target implementation date

- Need to understand the implications of these reports and determine resolution path by 2/26/21

---

### About your team

- Team name: Public Websites
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: N/A
- FE engineer: Nick Sullivan
- Product/team Slack channel: #vsa-public-websites

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by ncksllvn** [comment]
Is this for sure work for Public Websites and not the Search team?

**Comment by johnhashva** [comment]
@ncksllvn unclear to me -- and so @brianalloyd will surface this a topic of quick discussion/assessment with you at Sprint Planning this week.

**Comment by denisecoveyduc** [comment]
Reference Article: [SEM Rush Article/Audit - How To Perform a Technical SEO Audit in 15 Steps  ](https://www.semrush.com/blog/technical-seo-audit)

**Comment by ncksllvn** [comment]
__Thoughts from meeting on 3/18/21 -__

## Thoughts on the reports
The modernized VA.gov is only a small segment of the overall `www.va.gov` domain. The vast majority of these reports I suspect are from the non-modernized pages and are not actionable for our teams (and are likely not impactful to our area of the domain anyway.) For instance, modernized VA.gov has a "broken link checker" to ensure we aren't writing broken links. This means that modernized VA.gov is likely responsible for only a very _very_ small fraction of those reported broken links. __I think it is worth looking at the reports but the vast majority will not be actionable for our team and definitely does not reflect the SEO of the modernized VA.gov.__ I would possibly skim it for things we can do and write a dedicated GitHub issues for things we determine we are capable and interested in doing.

If there is significant traffic going to a broken page, such as a `.asp` page, we can possibly consult with `mnorthuis` (Mikki, but not pinging) to get a redirect in place there to direct its SEO to a modernized page.

Issues that pertain to the homepage and the [sitemap.xml](https://www.va.gov/sitemap.xml) file are part of the modernized VA.gov. It would be worth taking a look at those.

## Areas to improve 
These things come to mind for me when I think of search improvements.

1. In `SEMrush-Site_Audit_Incorrect_pages_found_in_sitemap_xml-va_gov-18th_Feb_2021.pdf`, I don't really know what it means to report those pages as `non-canonical URL`s. For instance, looking at `https://www.va.gov/health-care/ `, I don't know what could be wrong with that page. Perhaps it is flagged as `non-canonical` because there is some repeating content on that page. This could be worth looking into.  We may come up with some findings that we can relay to the content team - "Did you know that we have the same content  on Page X and Page Y? If we can consolidate this to just one of the two, we will get an SEO boost."
2. Links require trailing slashes on modernized VA.gov pages. For instance `https://www.va.gov/health-care` will redirect you to `https://www.va.gov/health-care/` via a "301 redirect." When many of our pages write their links, they forget to add the slash. Adding the slash would increase SEO for the page that contains the link and the page being linked to. We could also consider adding enforcement that links be written w/the trailing slash.
3. The Schema.org done in this [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/13679) and this [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10772) is in very base-level MVP state. If you haven't already, I would do a technical dive into what schema.org even is. Our implementation manifested without error on many pages but not every page - some pages contain errors, as listed in `va.gov_structured_data_that_contains_markup_errors_20210218.xlsx`. Perhaps it is time we matured the implementation, then start using other elements of schema.org. At the time, we were really only interested in making sure `https://www.va.gov/coronavirus-veteran-frequently-asked-questions/` worked okay.
4. Our [sitemap.xml](https://www.va.gov/sitemap.xml) is still very barebones and never had any deep exploration to improve it AFAIK. For instance, currently the `lastmod` is the same for every page - it is the date of the last deployment. I recall the search.gov team asking that we instead use the date that each page was modified, instead of the time of the deployment, which isn't useful. You could also figure out how localization works with a sitemap. For instance, is there a way we can indicate in the sitemap where a Spanish version of a page lives? It seems like the localization team might start becoming interested in this https://github.com/department-of-veterans-affairs/va.gov-team/issues/21076. This as well, https://developers.google.com/search/docs/advanced/crawling/localized-versions.
5. I am sure there are site-wide SEO improvements that can be performed on VA.gov by improving the semantic HTML of the website. We can probably work with our a11y experts to determine this, and I am sure they would love to see us move forward. Here is a quick article I found when I Google'd `semantic HTML seo`, https://searchengineland.com/seo-advantages-of-machine-readable-html5-semantic-markup-314455.

On Vets.gov, we had an SEO report ran in Sept 2017. We did make some of these changes back then but not every one. Lots of interesting things here. I just copied it from an old old email.

<details><summary>Vets.gov SEO report</summary>

In Summary

After a comprehensive review of https://www.vets.gov/, we conclude that Vets.gov has the opportunity to improve ranking and search visibility by addressing the following areas, listed in order of priority (1 being low - 10 being high) based on SEO impact. Priorities may shift based upon LOE.

 ```

1.      301 Redirects [SEO IMPACT 8] 
RECOMMENDATION: 1) update the left and bottom navigation to use the trailing slash versions of each URL and 2) update redirect logic to 301 redirect rather than 302 redirect.

2.      Page Title Optimizations  [SEO IMPACT 8]
RECOMMENDATION: Prioritize pages to optimize and insert page titles using best practices.

3.      Orphaned Pages [SEO IMPACT 8]
RECOMMENDATION: There are long tail search opportunities to optimize* these profile and facilities landing pages and create and submit an XML sitemap so the search engines crawl, find and index these pages. *More implementation details to be provided. There may also be a backlink outreach opportunity.

a.      GI Bill Tool profile pages

b.      Facility pages

4.      Keyword Usage [SEO IMPACT 8]
RECOMMENDATION: Identify on-page opportunities to add priority keyword phrases to optimized title, Meta description and in-content.

5.      Backlinks [SEO IMPACT 8]
PLEASE NOTE: A comprehensive Linking Strategy will be presented in phase four of this project.

6.      Block Pages from Indexing [SEO IMPACT 7]
RECOMMENDATION: 1) Add the the  <meta name="robots" content="noindex, nofollow" /> in the <head> of all search-jobs? parameter results and paginated list pages, as well as the login and users URLs identified. 2) Remove the /auth/login/callback/ URL from the XML sitemap. 3) Block these assets in the robots.txt file.

7.      Schema Structured Markup [SEO IMPACT 7]
RECOMMENDATION: We encourage the use of Schema markup across the entire site where applicable.

8.      Internal Links [SEO IMPACT 6]
RECOMMENDATION: Determine if Vets.gov is open to adding in-content links. If yes, create a list of prioritized pages and identify opportunities to add internal links within content.

9.      Meta Description Optimizations [SEO IMPACT 6]
RECOMMENDATION: Prioritize pages to create and insert optimized Meta descriptions.

10.   Duplicate Content [SEO IMPACT 6]
RECOMMENDATION: 301 Redirect duplicate URLs to the prefered URL.

11.   XML Sitemap [SEO IMPACT 5]
RECOMMENDATION: 1) Remove all test, maintenance, error and redirecting pages. 2) Re-generate the XML sitemap using https. 3) Submit updated sitemap to Google Search Console.

12.   Page Speed [SEO IMPACT 5]
RECOMMENDATION: Development team should optimize website for speed.

13.   Repetitive Content [SEO IMPACT 5]
RECOMMENDATION: Identify priority pages where content repeats and there is an opportunity to rewrite a version without compromising the user-experience.

14.   Accessibility [SEO IMPACT 4]
RECOMMENDATION: Remove links on the site to the assets identified.

15.   HTML Sitemap [SEO IMPACT 4]
RECOMMENDATION: Publish an html sitemap and add a link to it from the footer. For reference, the va.gov site has a useful html sitemap (see: https://www.va.gov/site_map.htm).

16.   Canonical Tags [SEO IMPACT 4]
RECOMMENDATION: As part of best practices, Vets.gov should implement  <link rel="canonical" href="prefered URL " /> tags on all pages to signal the prefered URL to be indexed in the search engines.

17.   H1 Headings [SEO IMPACT 4]
RECOMMENDATION: Prioritize pages by SEO traffic and potential and add an <h1> to the page template.

18.   Google Search Console [SEO IMPACT 3]
RECOMMENDATION: Update the logic to return a 404 header response for not found status. It is also suggested that these Not Found pages include a page title that identifies them as 404 (ex: 404 - Page Not Found). These pages can then be tracked in Google Analytics via Page Title filter. It is also recommended that we clear out all the errors noted in Google Search Console so that fresh reporting can be monitored.

19.   External Links [SEO IMPACT 3] RECOMMENDATION: Update identified links or remove from the site.
```
</details>

**Comment by brianalloyd** [comment]
Thanks @ncksllvn for the updated details and comments.  Good Stuff.

**Comment by johnhashva** [comment]
@denisecoveyduc and @srsuddath I've going to break this ticket into two -- one focused on the non-canonical URLs "issue" and the other on structured markup since they are two very different potential problems.    For non-canonical URLs report -- I've done some probing and here is what I've come up with: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22242

**Comment by johnhashva** [comment]
@denisecoveyduc I've just broken this one out with a second ticket Structured Markup Entity Field Issue #22442 -- so closing this "catch-all" version.
