### ISSUE TITLE
[UNPLANNED] Pass Through Bio for Standalone 674's with Preexisting Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20179]
## Background
In testing, it was determined that there is a field that RBPS requires to be passed that shows no impact but needs to be set a certain way:
When a 674 is submitted referencing an existing child, it requires the child's status to be set as `Biological` in the payload to be successful.  Currently, it is difficult to retrieve the actual status as it is not stored in CorpDB (yet) but is also not used to make any decision at this point.  Currently, the default value being submitted is `Other` and needs to be changed to `Biological` to avoid an error on manual offramp.

## Tasks
- [x] Update the value to `Biological` from `Other`

## Acceptance Criteria
- [x] The value is set to `Biological` by default
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5972
