### ISSUE TITLE
TUD - Update Availability column for accessibility

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20184]
## Issue Description
As a user, I would like to be able to see if an account is available / currently being used by a means other than it being conveyed by color so that I can easily determine which test accounts will appropriately serve my needs.

---
## Tasks
- [x] Reformat the 'Availability' column to display useful text for the relationship of Available vs Unavailable
- [x] Apply a nicer UI to the 'Availability' column to describe the above
- [x] Ensure good accessibility & 508c standards

## Acceptance Criteria
- [x] I can see text in the Availability column that is useful to me
- [x] UX Designer (Amanda) approves of the UI
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
TODO
- [ ] Design review with @APorter-Clarity (Amanda)
