### ISSUE TITLE
COVID-19 Documentation Audit

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#20187]
## Issue Description
There has been a surplus of COVID-19 documentation created over the last year (nearly). We need to review the documentation and make edits/deletions to ensure we only have currently relevant and non-duplicative content.

---
## Tasks
- Review all existing COVID-19 documentation VA.gov has
- Delete any duplicate documentation
- Archive non-relevant/current documentation
- Update any documentation that is still relevant, but not current
- Ensure documentation aligns with best practices

## Acceptance Criteria
- [ ] COVID-19 related documentation is current, relevant, properly formatted and non-duplicative 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Contacted Chante re. details for this project.

**Comment by starlow00** [comment]
@clantosswett, I have reviewed the documents and made minor edits. There are questions in a small handful of places. Ready for your review at https://drive.google.com/drive/folders/1c3qdyuIgtwcrNKjOUU70Di6R9Dxt0EZT

**Comment by Kimberley2019** [comment]
@clantosswett have you had the opportunity to review the documentation that was sent over to you by @starlow00?  Understanding that it was only two days ago.  Any updates or feedback that you can provide?

**Comment by starlow00** [comment]
Hi @clantosswett Just following up on this. Please let me know if you need anything else.
