### ISSUE TITLE
Delete education direct deposit R&S article and update disability/pension R&S direct deposit article 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20204]
## Issue Description
The Authenticated Experience/eBenefits team is adding education benefits to the direct deposit page (it will no longer be done through eBenefits). Because of this our ["How to change direct deposit for VA education benefits article](https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-education-benefits/) is irrelevant and should be removed. 

We will also need to update the ["How to change direct deposit information for VA disability or pension" article](https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-disability-or-pension/) to add in education benefits information. These updates include doing new screenshots for steps 5 through 7 to reflect education included in the list.

This work needs to be done at the same time the updated [Change your VA direct deposit page](https://www.va.gov/change-direct-deposit/) gets published. ~~Matt Shea will know soon when that is, but most likely not until March 1.~~ Update: Their go-live date is April 21.

We will also need to check if the education direct deposit page is linked to from other R&S pages and remove those links and remove the page from the R&S landing page.

## Tasks
- [x] Delete education direct deposit R&S article 
- [x] Update disability/pension direct deposit article with education info
- [x] Remove education direct deposit R&S article from landing page
- [x] Update article teaser text for disability/pension direct deposit article on R&S landing page
- [x] Check R&S articles and remove links to education direct deposit R&S article
- [x] Remove education direct deposit R&S article from helpful links section of change direct deposit page
- [x] Review changes and publish

## Acceptance Criteria
- [x] All changes are live on the site

**Comment by RLHecht** [comment]
The direct deposit work is now set to go live April 21. @bethpottsVADEPO I think we should probably have these pages updated around the same time since some won't be relevant anymore. We can talk about it at next week's sitewide content meeting.

**Comment by lunascoop** [comment]
@RLHecht here are my changes thus far and other observations. cc: @bethpottsVADEPO 

**For the "How to change direct deposit information for VA disability or pension" article http://preview-prod.vfs.va.gov/preview?nodeId=8434:**

- Article title is too long. Changed to VA benefits
- Updated intro sentence
- Added "compensation" after disability as shown on Change your VA direct deposit information, Direct deposit for your VA benefit payments
- Changed screenshots for steps 5 & 6 (Step 7 screenshot was fine as is
- Updated instructions for step 6
- Added education benefit hub under VA benefits at the bottom of page
- Removed education direct deposit link teaser

**For Change your VA direct deposit information page (http://preview-prod.vfs.va.gov/preview?nodeId=710):**

- Because most of the page content is actually w/in the react widget, I manually added the content in Drupal for when the react widget is updated. It's in draft mode of course.
- Removed education direct deposit link teaser
- Didn't update the disability compensation direct deposit link teaser until the new article title has been decided
- For the R&S landing page (http://preview-prod.vfs.va.gov/preview?nodeId=8296):
- Removed education direct deposit link
- Still need to update the disability compensation direct deposit link teaser w/the new article title
- Another article needs to be added to VA account and profile topic to replace the education direct deposit article

**For Direct deposit for your VA benefit payments article (http://preview-prod.vfs.va.gov/preview?nodeId=8423):**

- Removed education direct deposit link teaser
- Updated VA benefits hub links at bottom of page (disability, pension and education)
- Didn't update the disability compensation direct deposit link teaser until the new article title has been decided

**For How VA education benefit payments affect your taxes article (http://preview-prod.vfs.va.gov/preview?nodeId=15137):**

- Removed education direct deposit link teaser

**For GI Bill and other VA education benefit payments FAQs article (http://preview-prod.vfs.va.gov/preview?nodeId=15640):**

- Updated "Sign in to change VA direct deposit info" CTA to not go to a specific section on the Change your direct deposit page (since the content/section is moving out of the react widget)
- Removed education direct deposit link teaser

**Other observations:**

- May want to audit R&S articles to update the benefit hub listed at the bottom of page. Health care was the default, but it's not always applicable.

**Comment by lunascoop** [comment]
@RLHecht the pages listed in my previous comment are ready for review, though we are still waiting for Erik's feedback re: the react widget and content for the Change your VA direct deposit information page (http://preview-prod.vfs.va.gov/preview?nodeId=710)

**Comment by RLHecht** [comment]
Thank you @lunascoop for all this work! I just published all the pages and archived the education R&S page. Will confirm all is working right after the next deploy.

**Comment by RLHecht** [comment]
All changes are now live. Closing ticket
