### ISSUE TITLE
Translate KPI Framework Metrics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#20208]
## Issue Description
On the VFS side, our customers often ask what the data actually means.
On the Platform side, we often have to put in extra work to determine what the data requirements are.

How might we translate our KPI Framework Metrics so that:
- VFS customers understand what the metrics mean for their product
- VSP understands how to pull the metrics for dashboards and can more easily hand off dashboarding to each other

---
## Tasks
- [ ] Translate KPI Framework Metrics into plain language
- [ ] Translate KPI Framework Metrics into 
## Acceptance Criteria
- [ ] VFS and VSP understand KPI metrics

**Comment by joanneesteban** [comment]
Dupe ticket for the KPI dashboard data dictionary work being done [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25323). Closing this ticket.
