### ISSUE TITLE
Exploration - Other VA Search Tools

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#20217]
## Description

The search and discovery team would like to learn more about the right rail implementation on the results page to understand the intent from a stakeholder perspective. Why were these links chosen and what is the reasoning to have them on the right rail. We would also like to understand more about the user data and have reached out to the analytics team. 

![Right Rail Links.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/bf7a4ac5-9963-48a3-89df-b23eb5743768)
## Background/Context/Resources

Analytics Request - [GH#20168](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20168)

## Tasks

- [x] Connect with Jennifer Lee to understand VA value and approach
- [x] Collect user data from analytics to determine usage of links on right rail ([Analytics Request #20168](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20168))
- [ ] Collect user data from analytics to determine usage of other search tools - listed below
- [ ] Review design implications for the results page redesign

## Definition of Done

- [ ] Search + Discovery team has a clear understanding of the usefulness of the links on the right rail and has identified a clear path forward to integrate into the search results redesign.

**Comment by mgleo** [comment]
List of search tools:

On [main search sidebar](https://www.va.gov/search/?query=health):
[Look up Board of Veterans' Appeals (BVA) decisions](https://www.index.va.gov/search/va/bva.jsp)
[Search VA reference materials (WARMS)](https://www.index.va.gov/search/va/va_adv_search.jsp?SQ=www.benefits.va.gov/warms)
[Find a VA form](https://www.va.gov/find-forms/)
[VA handbooks and other publications](https://www.va.gov/vapubs/)
[Explore and apply for open VA jobs](https://www.vacareers.va.gov/job-search/index.asp)

More search pages that we know about:
[GI Bill® Comparison Tool](https://www.va.gov/gi-bill-comparison-tool)
[Find a Yellow Ribbon school](https://www.va.gov/education/yellow-ribbon-participating-schools/)
[Resources and Support](https://www.va.gov/resources/)
[Grave Locator](https://m.va.gov/gravelocator/index.cfm)
[Find Locations](https://www.va.gov/directory/guide/home.asp)
[Find a Facility](https://www.va.gov/find-locations)

**Comment by denisecoveyduc** [comment]
Hi @johnhashva  Did you happen to get any info from Jen Lee or others around the links on the right rail and how/why they were chosen over others?

**Comment by johnhashva** [comment]
Not yet @denisecoveyduc , so let's do this: 

- Move on from Jen
- Do we have GA tracking to see if there are clicks on those links?  If not, no worries
- Can we suggest what we think the right rail should contain as an alternative and the reason why?
- Then, I will put that in front of Danielle/Beth for approval -- and then we implement (with tracking)

Good?

**Comment by denisecoveyduc** [comment]
We are currently awaiting data from the analytics teams to better understand how the links in the right rail is being used. Shifting this to the backlog until we hear back from them through the analytics requests (#20168) and (#16778)

**Comment by denisecoveyduc** [comment]
@mgleo Resources & Support are in the process of refining this data in a dashboard but for now here is what they are using. https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22Type%20Ahead%20Disabled%20~~%20Resources%20and%20support%22,0%5D%5D&_.gSectionId=site_usage_events/

**Comment by denisecoveyduc** [comment]
@mgleo Marci also offered these links although they are still working through the Yellow Ribbon Information so we need to take that with a grain of salt until they have finalized.

- Yellow Ribbon (although subject to change): https://analytics.google.com/analytics/web/?authuser=1#/report/content-pages/a50123418w177519031p184[…]orer-graphOptions.selected=analytics.nthMonth

- Find a VA Form: https://va-gov.domo.com/page/1785082329/kpis/details/465801162 - the dark blue bar is unique pageviews"

**Comment by denisecoveyduc** [comment]
During the design intent review for "Search UI Consistency" Mikki made a comment that recommended we may want to identify and follow up with stakeholders who requested the links be placed on the right rail for veteran use. 

Referencing #23538
> Some of the links within the right rail of the global search are there because of stakeholder requests (i.e. the BVA lookup). Appropriate conversations/investigation must take place to before these links are considered for removal. That said, I have no issues with exploring different placement/design ideas for these links in support of deprecating the right rail. :-)

 @mgleo will provide a list of search tools that are being considered for relocation and @johnhashva will confirm next steps.

**Comment by denisecoveyduc** [comment]
we are able to close this issue now as we have collected enough information to determine the overall usage of the links on the right rail.
