### ISSUE TITLE
Sunset mashup controller

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20215]
## Issue Description
#19959 changes the sort and merge process for urgent care mash-up searches on the Facility Locator. By changing this process, we are able to sunset the mashup controller

---
## Tasks
- [ ] sunset the mashup controller

## Acceptance Criteria
- [ ] Mashup controller is no longer in use

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing this issue as no longer needed following the merge and sort change
