### ISSUE TITLE
Update TUD Documentation Post-MVP

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#20219]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

With the TUD app's soft release, various documentation needs to be updated to direct internal VA.gov users to use the tool, as well as to prepare for the project's handoff from the Identity to the Testing team.

---
## Tasks
- [x] update all password lists and references in `va.gov-team-sensitive` to reference the TUD app (in addition to hard-coded PW information that will remain in the sensitive repo)
- [x] update all password lists and reference in `va.gov-team` to reference the TUD app instead of hard-coded PW information (no hard-coded PW information should remain in the non-sensitive repo)
- [x] update documentation to include information on managing the TUD app in its "production" (vets-api staging) environment

## Acceptance Criteria
- [x] `va.gov-team-sensitive` will reference users to the TUD app wherever password information is kept
- [x] `va.gov-team` will no longer contain hard-coded password information & reference users to the TUD app
- [x] The TUD app repository's README is updated to include production-related documentation

**Comment by bramleyjl** [comment]
Blocked pending release of TUD MVP; the application needs to be live before we begin to direct users to it.

**Comment by bramleyjl** [comment]
TUD app is live at https://tud.vfs.va.gov, test password-related documentation can now be updated to reference it.

**Comment by bramleyjl** [comment]
`va.gov-team-sensitive` & `va.gov-team` repositories are ready to be switched over to reference the TUD application in all sections related to test user accounts. Future requests from the Testing Team to update either the TUD application's users or the test accounts listed in `va.gov-team-sensitive` can go through the normal ticketing process.
