### ISSUE TITLE
Review Policy content spec

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20214]
## Issue Description
As the Facilities team, we need to understand the tasks required for the implementation of the new Policies content front end implementation so that we can accurately groom and complete the work. 

---
## Tasks
- [ ] Review the [CMS documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/content-model-changes.md) for content changes in general
- [ ] Review relevant issues in [Policies epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3046)
- [ ] Create task list
- [ ] Document questions

## Acceptance Criteria
- [ ] Good understanding of the required tasks
- [ ] List of questions to clarify any missing requirements
- [ ] Task list ready for grooming

**Comment by mpelzsherman** [comment]
List of tasks - high level: 

1. Facilities devs continue to ramp up on how our CMS build system works.
1. Get bundleType from CMS team for Policy pages
1. Create new graphql query and register in the build system
2. Create new liquid template(s)

Connecting the /policies url to the new page should "just work" according to @kevwalsh.

**Comment by mpelzsherman** [comment]
We still don't have a spec to review that shows where each page element will come from in the new content model. I'm considering this ticket blocked until that's available for review.

**Comment by mpelzsherman** [comment]
This [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1614800814809/825fd5a0b0360ff42c2470e128d8f35af42579ee) was made available on March 4. Still waiting for centralized content to be converted to use entity ID instead of UUID. See [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1614896460307600?thread_ts=1614892798.305000&cid=C0FQSS30V) convo.

**Comment by mmiddaugh** [comment]
Content review is complete. Tasks have been added to https://github.com/department-of-veterans-affairs/va.gov-team/issues/21041
