### ISSUE TITLE
Add list component of dependents

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#20226]
# Background
Now that the dependency verification modal has been scaffolded out we need to fill in the component that will list the dependents inside the modal.

## Tasks
- [ ] Build out the dependents list component for dependency verification modal
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The users dependents can be listed in the dependency verification modal
- [ ] A PR has been submitted for review
