### ISSUE TITLE
Sprint 4 Retrospective

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2022]
## High Level User Story
As an Authenticated Experience Team Member I need review and comment on the retrospective board prior to our retrospective meeting so I can provide feedback to the team to apply this feedback towards the next sprint.

[Link to Retro board](https://funretro.io/publicboard/5gBtcenp7aSilrbq7MHxFy06UtF3/04c74306-55fb-4c74-8fcc-62f0f0c2aa58)
## Hypothesis/(es)
If we are providing this feed back we expect our processes and team cohesion to continue to improve. 

## Goals
Outcomes we want to see our better open communication around feedback for the team and how to work better during our sprints. 

## Definition of Done

- [x] [Sprint Retrospective Board](https://funretro.io/publicboard/5gBtcenp7aSilrbq7MHxFy06UtF3/04c74306-55fb-4c74-8fcc-62f0f0c2aa58)
- [x] I have reviewed the sprint retrospective and provided feedback on the board.
- [x] We have conducted our retrospective meeting for Sprint 4
