### ISSUE TITLE
Add Redux to dependency verification modal application

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#20227]
# Goal
We use Redux to manage the state of our apps across VA.gov and since the [App Name] will use data from any of various sources we need to build out the redux code to support that. This initial build of the Redux code does not have to use live data if none is available yet, we can hard code mock data for the time being if needed.

## Tasks
- [ ] Set up Action(s) file for dependency verification modal
- [ ] Set up Reducer(s) file fordependency verification modal
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The dependency verification modal now uses Redux to mange state
- [ ] A PR has been submitted for review
