### ISSUE TITLE
Scaffold Dependency Verification Modal Application

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#20225]
## Background
Now that we have a refined design for the dependency verification modal we need to scaffold out the actual files and folders we will eventually use in production. This scaffolding is not meant to build the final product but rather to set up the files and folders and basic structure as we know it today as we will have subsequent tickets to fill in the rest later.

## Tasks
- [x] Build out the folders and files needed for the dependency verification modal
- [x] Build the basic structure of the dependency verification modal
- [x] Submit a PR for review

## Acceptance Criteria
- [x] The dependency verification modal has been scaffolded
- [x] A PR has been submitted for review

**Comment by jason-gcio** [comment]
Design Intent feedback not required
