### ISSUE TITLE
[Design] Profile: Add FAQ around what departments get updated when a veteran updates their contact info

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20221]
## Background

In the last two days, I've had two different groups (MHV and VAOS) ask me about showing information in the profile around what departments get updated when someone updates their contact info. We used to have a FAQ in profile 1.0 about this, and I don't remember why we took this out of Profile 2.0. But, I do think this information would be helpful since VA Profile connects to some, but not all, departments at the VA. We currently have this information [on the Change Your Address content page](https://www.va.gov/change-address/), but we really should have it in the profile. Design should determine whether we want the copy directly in the profile, or if it makes sense from a content governance perspective to link to the change address page.

## Tasks

- [ ] Add FAQ back into the profile that lists what departments do/don't get updated when people update their contact info. 
- [ ] Determine whether we should show the [Change Your Address](https://www.va.gov/change-address/) content right in the FAQ, or if we should link to the content page. 
- [ ] Get copy approved (you can probably just take what's on the content page)
- [ ] Once design is finalized, work with AJ to create a FE ticket

**Comment by andaleliz** [comment]
Adding some mock-ups to review in discussion with content team tomorrow (4/1). 

side note: the content inside the "how will you use my contact information" FAQ is different than what's on the change your address page but it still feels like there may be bit of redundancy. will get content teams take on this.

![profile - desktop FAQ open](https://user-images.githubusercontent.com/55992116/113128430-c98f0b80-91e7-11eb-9db7-cd51329ba7a3.png)
![profile - desktop FAQ update](https://user-images.githubusercontent.com/55992116/113128436-cb58cf00-91e7-11eb-9c93-0d746796644f.png)
![profile - mobile FAQ update](https://user-images.githubusercontent.com/55992116/113128441-cc89fc00-91e7-11eb-8a50-9e3f2daf0eab.jpg)

**Comment by andaleliz** [comment]
>If we link off to the content page, we probably don't need the FAQ given that it's redundant and also doesn't include info on how to update other benefits not connected to our profile.

I read it as being _slightly_ different since it's about how info is used vs which departments know about it. The FAQ specifically states that that information will be used to "contact you" and the change address doesn't have that language.  But I do agree that it is redundant, and people will hopefully infer that information is used for contacting them since it lives in a place called "contact information".

>Should we move this information up? Idk the answer to that, but I do know that I missed it entirely. But, of course, I'm just one person and not representative of other users.
Does the FAQ contain the same info the folks from MHV and VAOS teams were asking about? If so, that's at least 3 people who missed it! I think moving it up makes sense, but going to hold off on more mock-ups until I talk to the content team so I can make all the updates at once.

**Comment by Samara-Strauss** [comment]
🤦‍♀️ I'm so sorry, Liz. I don't know where my brain is right now.

You're right — this is what they asked about. I was thinking we had some convo with Lauren/Peter that I wasn't remembering. So, yes, to your earlier point, that means a bunch of people are missing the current FAQ or they don't think the information about what departments get updated will be part of that.

> I think moving it up makes sense, but going to hold off on more mock-ups until I talk to the content team so I can make all the updates at once.

Sounds good to me! Let me know how your review with them goes.

**Comment by sshein** [comment]
+1 on moving it up - I feel like I'd want to know what systems get changed *before* I click edit and edit my contact info

**Comment by andaleliz** [comment]
I discussed this with Danielle and Beth yesterday, and they recommended keeping both the FAQ and link for now.  Danielle pointed out that the reference to where people's Rx's are going is particularly important, because they could miss some very important meds if they're not aware of that.   They are working to update the content on the [change your address page](https://www.va.gov/change-address/) so it also includes what we have in our FAQ. Once that update is made, we can remove our FAQ.

We ran out of time during the suite office hours, so I am continuing to discuss hierarchy w/ them async wrt to moving this up the page.

Also, given that prescription use case, we wondered if it might be better to inform people about how their contact info is used when they're actually _editing_ their address.  Since we know if someone has prescriptions, profile can be smart enough to let them know during the edit address process that their prescription address will be updated too.  There may be other use cases like this but I haven't thought through this since it's out of scope for this particular request. Added it to my list of profile improvement ideas :grin:

**Comment by Samara-Strauss** [comment]
> I discussed this with Danielle and Beth yesterday, and they recommended keeping both the FAQ and link for now. Danielle pointed out that the reference to where people's Rx's are going is particularly important, because they could miss some very important meds if they're not aware of that. They are working to update the content on the change your address page so it also includes what we have in our FAQ. Once that update is made, we can remove our FAQ.

Got it. Sounds good to me!

> Also, given that prescription use case, we wondered if it might be better to inform people about how their contact info is used when they're actually editing their address. Since we know if someone has prescriptions, profile can be smart enough to let them know during the edit address process that their prescription address will be updated too. There may be other use cases like this but I haven't thought through this since it's out of scope for this particular request. Added it to my list of profile improvement ideas 😁

Also sounds good as something to explore. Thanks for adding it to the list!

**Comment by ajakabcin** [comment]
Moving to sprint 45 per Liz's comment above.

**Comment by andaleliz** [comment]
Moving this to blocked since I can't do any more on this until I meet w/ Danielle.

**Comment by andaleliz** [comment]
@RLHecht and @DanielleThierryUSDSVA, here's the page we reviewed today and discussed re-wording the FAQ and moving the link to the `change your address` page inside the FAQ.  The previous version [is in the comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20221#issuecomment-813470727), and below is the mock-up we ended on:

![image](https://user-images.githubusercontent.com/55992116/114089649-66a31180-9884-11eb-8622-a799abe73f66.png)


The current copy inside the `How will you use my contact information` FAQ reads as follows:
>We’ll use this information to contact you about certain benefits and services, like disability compensation, pension benefits, and claims and appeals. If you’re enrolled in VA health care, we’ll send your prescriptions to your mailing address. Your health care team may also use this information to contact you.

Thanks in advance for your edits!

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA gave this a sticky note and will have feedback for us tomorrow :)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz! Thanks for another great working session in office hours yesterday. Here's recommended content for this additional information component. I am recommending that we actually now link to the section within the new Resources and Support article that offers info on how to update your contact info for other benefits and services. This is a more helpful place to send folks. If you have questions, you know where to find me :)

**Which benefits and services does VA use this contact information for?**

We use this information to contact you about these VA benefits and services:
- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)

If you’re enrolled in VA health care, we also use this information to send you these:
- Appointment reminders
- Communications from your VA medical center
- Lab and test results
- Prescription medicines (we send prescriptions to your mailing address)

[Find out how to change your contact information for other VA benefits](https://www.va.gov/resources/change-your-address-on-file-with-va/#change-your-address-by-contact)

**Comment by andaleliz** [comment]
Thanks @DanielleThierryUSDSVA! 

I've updated the mock-ups accordingly (did not create an expanded FAQ for mobile given we're using a design system component and the desktop view shows the copy):

![profile - p+c FAQ updates](https://user-images.githubusercontent.com/55992116/115039575-95317580-9e9e-11eb-944d-b942134ec828.png)
![profile - p+c FAQ updates expanded](https://user-images.githubusercontent.com/55992116/115039587-96fb3900-9e9e-11eb-8fa9-cb9b037ce89d.png)
![profile - mobile FAQ update](https://user-images.githubusercontent.com/55992116/115039595-995d9300-9e9e-11eb-87c8-1872329a7441.jpg)


@ajakabcin I think this is ready for FE implementation; probably should be a new ticket to track their work.  We can use Danielle's copy above as the copy source of truth.

**Comment by Samara-Strauss** [comment]
> @ajakabcin I think this is ready for FE implementation; probably should be a new ticket to track their work. We can use Danielle's copy above as the copy source of truth.

Yep! Let's get a ticket created.

This looks great, btw :D

**Comment by ajakabcin** [comment]
I've created #23376 and will review with @andaleliz on Monday to make sure I've captured all the details.

**Comment by Samara-Strauss** [comment]
Awesome, thank you!
