### ISSUE TITLE
Debt collection pause communications

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20232]
## User story

As a Veteran or family member, I need to know the latest updates on VA debt collection and understand what it means for me and what I need to do.

## Issue Description
Work with DMC stakeholders to determine how best to surface Q&As around this and create content that aligns with plain language and VA.gov content standards.

Immediate step is adding links to a Q&A on the DMC site to both the Manage your VA debt and Coronavirus FAQs pages. The next step is to create similar content on VA.gov.

---
## Tasks
- [ ] Ongoing work with stakeholders (Danielle)
- [x] Add temporary links to DMC website Q&A from Manage your VA debt and Coronavirus FAQs page (Danielle/Randi)
- [x] Write R&S article with revised content as provided by DMC (Danielle)
- [x] Copy edit R&S article (Randi)
- [x] Share R&S article with stakeholders (Danielle)

HOLD FOR REVIEWS AND APPROVAL (will add additional tasks when we can move forward)
 
## Acceptance Criteria
- [x] Links to DMC site Q&A are live on VA.gov
- [x] Full content is live on VA.gov
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht I created this ticket to make sure we capture this work. If you have other related tickets to capture your part of this work, feel free to use those to estimate your time on this. I just want to make sure we're capturing the full volume of content work as we track sitewide content's capacity. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@leahkeeler This work isn't specifically tied to the DMC content migration. But since you've been on the emails around this, I wanted to tag you in the ticket for awareness. Thanks!

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA Thank-you for tagging I was going to open a ticket requesting a new alert for the debt portal but it sounds like it is captured in this ticket - correct? Basically, an update to the original alert we had for debt collection suspension but with dates updated - Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
**Noting status update 2/28/21:** The full content page remains with stakeholders. The temporary solution of links over to the debt management content site from the coronavirus FAQs and manage VA debt pages remains in place for now.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This is all updated now with final stakeholder feedback, and will go live as part of the FSR launch. Could you do a final copy edit review on Monday? Thank you!
