### ISSUE TITLE
Lighthouse Appointment/Location/Organization API integration with Questionnaire Manager service

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#20248]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the backend's questionnaire manager service to provide a complete set of data to my browser so that I can use the pre-visit questionnaire service successfully

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- Currently, we're using appointment data from MAP to provide the frontend with an aggregated data set
- Provide an aggregated data set to the UI which removes appointment/facility/clinic information from MAP and includes appointment/location/organization information from the Lighthouse instead.

## Tasks
- [x] Blend Appointment/Location/Organization/Patient/Questionnaire/QuestionnaireResponse into a single data structure
- [ ] Write tests so that coverage is at ninety percent or more

## Acceptance Criteria
- [ ] Final data structure has all the agreed-upon fields.
- [ ] Signed off by frontend/UI
