### ISSUE TITLE
Locations API

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#20246]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the backend to create a location service so that my questionnaire manager in the browser will show clinic information.

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- Currently, this information is already provided to us by the MAP appointments. Lighthouse, since it's FHIR based, has clinic information separately stored in a Locations endpoint.
- create a new service module for fetching locations(clinic information) for a patient's appointments.

## Tasks
- [x] Create a factory class for handling all high-level functions and dependencies.
- [x] Create a class for handling all queries to the Health API's location endpoint.
- [ ] Add index route for fetching collections
- [ ] Add show route for fetching a single resource
- [ ] Write tests so that coverage is at ninety percent or more

## Acceptance Criteria
- [ ] Locations are being fetched for a user by a given set of location ids
- [ ] Ability to fetch a single location by a given location id
- [ ] Signed off by frontend/UI
