### ISSUE TITLE
[FE] Figure out what [X] days before should be 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#20242]
## User Story

As a veteran, I should know how many days I have to fill out my form, so I can fill my form out on time. 

## Related Documentation

> these should be links to feature docs

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description

This text is on the introduction page: 

```
Please try to fill out this questionnaire at least [X] days before your appointment. When you tell us about your symptoms and concerns, we can better prepare to meet your needs.
```

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Update copy

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

Wee need t

**Comment by kristenmcconnell** [comment]
Remove "at least [X] days" from the sentence.

**Comment by mdewey** [comment]
This is staging, @kristenmcconnell  can you take a look?

**Comment by kristenmcconnell** [comment]
Looks good.
