### ISSUE TITLE
Facility Locator Mobile Design

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20254]
## Issue Description
Following [usability test prep ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19413 )and [research ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18690 )using a mobile first prototype, we need to incorporate findings into an engineering-ready design spec

---
## Tasks
- [ ] Incorporate research findings/recommendations
- [ ] Incorporate usability test prep recommendations
      - [Content feedback ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19413#issuecomment-777074168)
      - [Accessibility feedback ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19699)
- [ ] Work with accessibility to identify and resolve any problem areas

## Acceptance Criteria
- [ ] Engineering-ready design spec

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
