### ISSUE TITLE
[FSR] Redesign employment sections to allow for multiple current jobs [usability]

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#20251]
## Issue Description
Currently, both the Veteran and spouse employment screens allow for only a single current job. Adjust the design to allow for multiple current jobs.

---
## Tasks
- [x] Redesign the employment sections to allow for multiple current jobs
- [x] Sync to UXPin - both Unauth and Auth
- [x] Create a frontend ticket for the work

## Acceptance Criteria
- [x] Designs updated and posted in UXPin, then linked in this ticket
- [x] Frontend ticket created and linked in this ticket

**Comment by rebeccawalsh** [comment]
Designs are uploaded to auth uxpin here: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/139219177?mode=i

**Comment by rebeccawalsh** [comment]
FE ticket here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25463
