### ISSUE TITLE
Analysis of spotlight/featured content boxes across VA.gov analysis

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20258]
## Issue Description
Before we determine the appropriate character limits for the spotlight/featured content box component for the Vet Center MVP, we need to understand current usage

- CTA/link label and URL currently has a character limit of 40

---
## Tasks
- [ ] Review places across VA.gov where the spotlight/feautred content boxes are used and document the character limits in place for
      - the header
      - free text 
      
      
## Acceptance Criteria
- [ ] Documentation of the average and maximum characters currently in use for featured content boxes across VA.gov

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
analysis available [here](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/137069227/simulate/sitemap)
