### ISSUE TITLE
[FSR] Empty state for when there are no Veteran benefits

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#20250]
## Issue Description
Currently, a Veteran is served a benefits screen displaying $0 if they have no active benefit payments from the VA (See mockups here: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136159512/specification/sitemap?mode=i). Investigate our options and define the design direction for this.

---
## Tasks
- [x] Determine design direction for Authenticated FSRs with no active benefit payments, document in GH & comment in this ticket
- [x] Create a ticket for frontend

## Acceptance Criteria
- [x] Direction defined in GH and commented in this ticket
- [x] Ticket created for front end and linked

**Comment by rileyorr** [comment]
- [Empty state](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/137058261/specification/sitemap?mode=i)
- [Frontend ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20506)
Weekly content office hours are starting next week, so I will ask for a quick review of the content and make any adjustments before the sprint ends.

**Comment by rileyorr** [comment]
Content has been reviewed and updated
