### ISSUE TITLE
Update “production” gem group minor versions

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#20264]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path for our production gems should be split into three sub-steps, with increasing risk level. This step includes updating the minor versions.

In the case of regression caused by a gem update, gems should be updated in isolation. It would be best to commit each update in isolation to avoid an “all or nothing” rollback situation

To update “Production” gems to latest minor version:
`bundle update --minor --strict`

[Gem update spreadsheet](https://docs.google.com/spreadsheets/d/1XAANeTmGK2-kSDyxk3qjlS3aODSWBIgFhPHAH7by9Ns/edit#gid=1749343339)

Create tickets for:
- [x] aasm
- [x] aws-sdk-s3
- [x] aws-sdk-sns
- [x] date_validator
- [x] dry-struct
- [x] dry-types
- [x] faraday
- [x] fastimage
- [x] flipper
- [x] flipper-active_record
- [x] flipper-active_support_cache_store
- [x] flipper-ui
- [x] google-api-client
- [x] googleauth
- [x] holidays
- [x] json
- [x] mini_magick
- [x] notifications-ruby-client
- [x] octokit
- [x] oj
- [x] ox
- [x] parallel
- [x] pdf-forms
- [x] prawn
- [x] rack-attack
- [x] rails
- [x] rails_semantic_logger
- [x] redis
- [x] redis-namespace
- [x] ruby-saml
- [x] rubyzip
- [x] sidekiq-pro
- [x] typhoeus
- [x] will_paginate
---

## Acceptance Criteria
- [ ] Run automated test suite
- [ ] Test manually
- [ ] Check each updated gem’s CHANGELOG — if available — for potential backward-incompatible changes.
---
