### ISSUE TITLE
Populate Country Code on 686 PDF 

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#20274]
## Background
The country code is no longer being populated in the address fields on the 686 PDF.  This occurs in multiple places (screenshot added in comments as an example).

## Considerations
This was working previously so need to determine why it is no longer working.

## Tasks
- [ ] Determine why the country code is no longer displaying on the PDF
- [ ] Fix the broken PDF code to ensure country is being populated

## Acceptance Criteria
- [ ] The PDF has been updated and all address fields are populated correctly
- [ ] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
![Screen Shot 2021-02-22 at 11.27.15 AM.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/9aba6804-4b5a-438a-a215-b26b9d72328b)

**Comment by kathleencrawford** [comment]
This is working has intended...it is not a bug.  We do populate country code for full addresses, but for "location" fields (such as marriage city) we only ask for city and state.  

![Screen Shot 2021-02-26 at 1.40.26 PM.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/6c32203f-8a33-442f-9e07-734703dfdadd)
