### ISSUE TITLE
Add pop-up logic for when dependency verification modal appears

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#20284]
## Background 
Now that the basic structure of the verification modal is in place we need to build the logic that will fire the modal. This will largely depend on an API call that will be made to the back end and then to the diary service to see if we need to ask the user to verify their dependents. Then based on the answer we get back from the API we need to show the modal.

## Considerations
- Consider Redux
- Consider when a Veteran on the site leaves the page and comes back; where is the data stored about what they chose?

## Tasks
- [x] Set up a mock API call that returns a boolean
- [x] Build logic that shows the modal based on data from the API call
- [x] Submit a PR for review

## Acceptance criteria
- [x] The modal now shows based on a mock API call
- [x] A PR has been submitted
