### ISSUE TITLE
[MCP] VAHRC Call Center Interviews

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#20289]
## Issue Description
We need to hold VAHRC interviews to learn more about what Veterans commonly struggle with.

---
## Tasks
- [x] Hold 5 interviews with VAHRC SMEs
- [x] Add notes and artifacts to Github 

## Acceptance Criteria
- [x] Notes scrubbed and uploaded to Github

**Comment by rileyorr** [comment]
- [Added the sessions I took notes for to the notes folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Medical_Copays/research/feb-2021/notes)
- [Added the VHA copayment process flow's second iteration to GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/feb-2021/copayment-flows.md)
