### ISSUE TITLE
Dashboard: Legacy VA.gov MyVA vs. WBC My VA confusion

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20290]
## Background

@artsymartha68 just alerted me to the fact that there is this [whole initiative on the legacy site called MyVA](https://www.va.gov/myva/).  It's also linked from the legacy footer: https://blogs.va.gov/VAntage/myva/. 

Clearly, this could cause some confusion with users who log into the WBC site and are looking for/at their [My VA dashboard](www.va.gov/my-va), as these two things are completely separate and unrelated. This is especially confusing because it's not only the names that are virtually the same (MyVA vs. My VA) but also the URLs:

- Legacy initiative URL: https://www.va.gov/myva/
- WBC VA.gov user dashboard URL: https://www.va.gov/my-va/

We need to figure out a course of action:

- Do we care enough about this issue to solve it? Do we think this could cause meaningful confusion?
- If so, what is the course of action? Probably the easiest thing would be to change the name of the My VA dashboard on our site. Alternatively, we could see if this initiative is even still alive and active, and if it's not, see about getting these pages/the footer URL retired from the legacy site.

**Note**: We discussed My VA's name recently in #13738, but decided not to change it. However, this was before we knew about the MyVA section on the legacy site.

## Tasks

- [ ] Determine if we want to address this
- [ ] Determine course of action
- [ ] Create necessary tickets for next steps
