### ISSUE TITLE
Remove base facility table for V0

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20299]
## Issue Description
After sunsetting the v0 ccp controller and v0 VA controller, we need to remove the v0 base facility table
---
## Tasks
- [ ] Remove base facility table for V0

## Acceptance Criteria
- [ ] Unnecessary data models are no longer present
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by darkbushido** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1620759544202700

**Comment by jilladams** [comment]
For backend sorting if real or no
