### ISSUE TITLE
Swap dummy api calls for real calls to BE

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#20291]
`needs diary update endpoint complete: could be another ticket`

## Background
Once we have the back end API call in place for the dependency verification we need to swap our dummy API call for that real one.

## Tasks
- [x] Holler at Derek for methods
- [x] Test the list and logic (READ)
- [x] Adjust API call and returned data
- [x] Submit a PR for review

## Acceptance criteria
- [x] The API call made by the dependency verification is now the real API call
- [x] A PR has been submitted for review
