### ISSUE TITLE
Remove v0 lighthouse engine

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20298]
## Issue Description
After sunsetting the v0 ccp controller and v0 VA controller, we need to remove the backend code for the v0 lighthouse engine. 

---
## Tasks
- [ ] Remove v0 lighthouse engine

## Acceptance Criteria
- [ ] Unneeded code for the v0 lighthouse engine is no longer present
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
