### ISSUE TITLE
[DISCOVERY] FE build process from CMS to VA.gov

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20304]
## Issue Description
We need to understand the build process from CMS to VA.gov, including how new pages are added to the system to inform our work with VAMCs and the creation of the new Vet Center pages. 

---
## Tasks
- [x] Review existing documentation related to the build process, if any is available
- [ ] Identify any gaps in understanding/documentation and work with CMS/Public Websites team to fill in the needed info

## Acceptance Criteria
- [x] Strong documentation to support  understanding of the build process from CMS to VA.gov

**Comment by mpelzsherman** [comment]
@ncksllvn has offered to generate some documentation. See [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1614115391071600?thread_ts=1614114250.057900&cid=C0FQSS30V).

**Comment by mmiddaugh** [comment]
We may also want to consider documenting the organization of liquid templates as part of this discovery effort. https://github.com/department-of-veterans-affairs/va.gov-team/issues/11092

**Comment by mpelzsherman** [comment]
I've completed my review of @ncksllvn 's [documentation](https://github.com/department-of-veterans-affairs/vets-website/pull/16210/files).

Sounds like we basically just need to get the entityBundle name from the CMS team for each new page type.

From there we can use GraphQL Explorer to get the list of entities we need, but it would be nice to have an ERD of the content model so we don't have to "explore" to figure this out.

We don't know what we don't know. This will be an ongoing learning process.

I'm willing to call this "done", but might be good to get @brangi's signoff before we close the ticket.
