### ISSUE TITLE
Remove flipper for operationalHoursSpecialInstructions field (VHA)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20328]
## Issue Description
The implementation of operationalHoursSpecialInstructions field for VHA was governed by a flipper, pending data scrubbing to remove the pipes. This issue will remove the flipper once it is no longer needed. 

---
## Tasks
- [ ] Remove flipper

## Acceptance Criteria
- [ ]  operationalHoursSpecialInstructions field can no longer be toggled using flipper

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
Per the [Flipper audit](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656) this flipper should be removed. There is not a current ticket in our repo, so I am migrating this
