### ISSUE TITLE
Refactor User Model Address

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#20327]
## Issue Description
As part of a larger refactoring of the `User` model the logic around accessing a user's address/location information should be cleaned up. The larger User model refactoring/`va_profile` elimination story can be found here: **https://github.com/department-of-veterans-affairs/va.gov-team/issues/18740**

---
## Tasks
- [x] Replacement of all instances where `user.va_profile.address` is called with `user.address`, moving the reference to `va_profile` into the User model's internal logic

## Acceptance Criteria
- [x] No noticeable changes for the end user should occur as a result of this change, but it will make future development simpler and faster.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
