### ISSUE TITLE
EKS - Set up DEV cluster that allows other teams to deploy applications

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#20322]
## Description
Let’s see if we can get a DEV EKS cluster running for application teams to deploy to. Right now, we have a couple of teams that have some testing apps that are not yet running in production, and this environment will be a great place for them to bring up these new apps, and it will help ops in setting up deployment pipelines for applications that are not owned by Ops. 

Right now, we have a few apps/teams that are ready to test out EKS, including Rian Fowler's team on Lighthouse for backstage (developer portal) from, and the Backend Tools team has a small middleware app for reporting VTK CLI usage, and potentially others in the near future. 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Install EKS cluster in DEV
- [X] Install Calico CNI
- [x] Add this new cluster to ArgoCD running in platform tools cluster
- [ ] Set up RBAC on ArgoCD dev to allow teams to only access their applications 
- [x] Configure URL routing to the applications (Traefik) 

## Definition of Done
- [x] Running EKS cluster in DEV that teams can deploy applications to _(this does not necessarily need to be the final dev environment, as this will be an environment that we use to learn through doing)_ 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by tskinn** [comment]
Traefik is running on the dev cluster and argocd is deploying it.

I think in order to setup rbacs and roles for a particular app team we will need to know what the app team is and what app they will be deploying.

**Comment by jhouse-solvd** [comment]
There is a working cluster that could be used to deploy an app to for testing /demo purposes

**Comment by jhouse-solvd** [comment]
Once we get to a place where we will be installing an app, we can circle back to configuring RBAC/roles, in a new ticket. 

Closing.
