### ISSUE TITLE
[Original Claims] Downtime Testing with Consumers

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2033]
## User Story
As the Back-end Engineer on the Benefits and Memorials team, I need to perform downtime testing with consumers so I can ensure they experience the expected results.

## Task
Downtime Testing with Consumers

## Acceptance Criteria
- [ ] Tests have been scheduled
- [ ] Tests have been executed
- [ ] Addition needs have been identified and documented in future ticket (if needed)

**Comment by luke-gcio** [comment]
This is OBE.  Part of new collab cycle among other things.
