### ISSUE TITLE
Homepage-Updates to printable appointment page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20333]
## Description
Additional enhancements to the printable appointment found from work in #12679.

## Tasks

- [ ]  VA
- [ ]  CC
- [ ]  VVC

## Acceptance Criteria
- [ ]  Changes are behind the va_online_scheduling_homepage_refresh feature flag
- [ ]  When user clicks/taps Print link on appointment detail page, open default browser dialog box

- [ ] If appointment has a "Join Appointment" link, Then show link and full URL on the printable page

- [ ] DESIGN - On printable page only, Join Appointment link is:
  - Black text
  - Left aligned

- [ ] On printable page only, do not show the following text/links:
  - Add to calendar
  - Print
  - Reschedule
  - Cancel appointment

- [ ] No changes are made to the actual web page

**Comment by laurenernest** [comment]
@LanceGundersen Can you add an estimate to this one once you look at the ACs? Thanks!
