### ISSUE TITLE
[MCP] Veteran interview conversation guide

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#20341]
## Issue Description
We need to speak to Veterans about their experiences with medical copayment debt in order to better evaluate their needs

---
## Tasks
- [x] Create a conversation guide for initial discovery work with Veterans around MCP
- [x] Upload conversation guide to GH and link to this ticket

## Acceptance Criteria
- [x] Conversation guide linked in this ticket

**Comment by rileyorr** [comment]
The conversation guide has been reviewed by multiple researchers for feedback, [uploaded to GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/conversation-guide.md), and sent out to Lauren for feedback + to kick off the recruitment process. I'll move the ticket over to 'validate' once she approves it.

**Comment by rileyorr** [comment]
Recruitment has been kicked off!!!
