### ISSUE TITLE
[Development] Testing in MVI Staging Environment

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2034]
## User Story or Problem Statement
As a veteran, I need to be able create a profile so I can file a new, first time claim for a disability compensation.

In order to achieve the goal for the veteran, we need to complete a series of tests in the staging environment to test the proxy add endpoint and complete the integration with MVI.  This is dependent on the iDev story wrapping up.

## Tasks
- [x] Find a SSOe that fits the criteria for testing if we haven't already - 2 hours
- [ ] Document and code up the API calls we will be making - 4 hours
- [x] Do the testing!

## Acceptance Criteria
- [x]  Finish testing in staging environment
- [x] Get sign-off from MVI that we are good to go with full access (at some point)

**Comment by SMLuthi** [comment]
This is hinging on the PR being approved and pulled through into the master branch. At that point, we can begin what MVI calls `SQA testing` (aka testing on staging).
