### ISSUE TITLE
[MCP] Veteran interview research plan

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#20343]
## Issue Description
We need to speak to Veterans about their experiences with medical copayment debt in order to better evaluate their needs. Create a research plan to describe our plans so that we can start scheduling people!

---
## Tasks
- [x] Create a research plan for initial discovery work with Veterans around MCP
- [ ] Upload research plan to GH and link to this ticket

## Acceptance Criteria
- [ ] Research plan linked in this ticket

**Comment by rebeccawalsh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/research-plan.md
