### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Albany health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20362]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-2 Internal Review Folder](https://drive.google.com/drive/folders/1QW3CJjCQBVFKh2iIyxJxAdDiH6P-4PY6)
[Review template for review](https://drive.google.com/drive/folders/1QW3CJjCQBVFKh2iIyxJxAdDiH6P-4PY6)
[Albany Legacy Site](www.albany.va.gov)

## Tasks
- 1) Confirm Correct facilities are listed by comparing Story, VAST DB/spreadsheet, and Legacy Site.
- [x] Updated Story below with correct facilities.
- [x] Publish change in VAMC Support Channel
- [x] Update Facility change list (owner: ltrombley)

- 2) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 528A8	Samuel S. Stratton Department of Veterans Affairs Medical Center
- [x] 528G2	Westport VA Clinic
- [ ] 528G3	Bainbridge VA Clinic
- [x] 528G6	Fonda VA Clinic
- [x] 528G7	Catskill VA Clinic
- [ ] 528GT	Glens Falls VA Clinic
- [x] 528GV	Plattsburgh VA Clinic
- [x] 528GW	Schenectady VA Clinic
- [x] 528GX	Troy VA Clinic
- [x] 528GY	Clifton Park VA Clinic
- [x] 528GZ	Kingston VA Clinic
- [x] 528QK	Saranac Lake VA Clinic

- 3) Review and correct all **Broken Links** on each of the system pages in Tugboat

- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [ ] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by lealester** [comment]
Unable to test in tugboat: Bainbridge and Glenn Falls VA clinics
