### ISSUE TITLE
 [REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA New Jersey health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20368]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-2 Internal Review Folder](https://drive.google.com/drive/folders/1QW3CJjCQBVFKh2iIyxJxAdDiH6P-4PY6)
[Review template for review](https://drive.google.com/drive/folders/1QW3CJjCQBVFKh2iIyxJxAdDiH6P-4PY6)
[New Jersey Legacy Site](www.newjersey.va.gov)

## Tasks
- 1) Confirm Correct facilities are listed by comparing Story, VAST DB/spreadsheet, and Legacy Site.
- [ ] Updated Story below with correct facilities.
- [ ] Publish change in VAMC Support Channel
- [x] Update Facility change list (owner: ltrombley)

- 2) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 561	East Orange VA Medical Center
- [x] 561A4	Lyons VA Medical Center
- [x] 561BZ	James J. Howard Veterans' Outpatient Clinic
- [x] 561GA	Hamilton VA Clinic
- [x] 561GB	Elizabeth VA Clinic
- [x] 561GD	Hackensack VA Clinic
- [x] 561GE	Jersey City VA Clinic
- [x] 561GF	Piscataway VA Clinic
- [x] 561GH	Morristown VA Clinic
- [x] 561GI	Tinton Falls VA Clinic
- [x] 561GJ	Paterson VA Clinic
- [x] 561GK	Sussex VA Clinic
- [x] 561BY	Newark VA Clinic
- 3) Review and correct all **Broken Links** on each of the system pages in Tugboat
- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [ ] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by lealester** [comment]
Added from VAST: Newark VA Clinic
