### ISSUE TITLE
[VAMC] Content Management Strategy - How best to administer and support the VAMC websites [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20361]
## VAMC - Product Outline

[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**VISN with 7 Systems to determine LOE, Velocity and MVP**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site / Documents / Resources
[Google Drive locations for VISN-6](https://drive.google.com/drive/folders/16fYaBYNTGRXYlCWP96OqYEMrNRUrIjTA)

## TASKS
See below associated tasks which should include, but are not limited to:
**Determine Content Levels**
- [ ] Hardened page planning
- [ ] Content management strategies
- [ ] Process and procedures
- [ ] Training
- [ ] Artifacts for training
- [ ] Guidelines

## Acceptance Criteria
