### ISSUE TITLE
[VAMC] VISN-17 "VA Heart of Texas Health Care Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20363]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-5](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [x] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Amarillo health care
- [ ] VA Central Texas health care
- [ ] VA North Texas health care
- [ ] VA South Texas health care
- [ ] VA Texas Valley health care
- [ ] VA El Paso health care
- [ ] VA West Texas health care

Facilities include for System:
VA Amarillo health care
- [ ] vha_504	Thomas E. Creek Department of Veterans Affairs Medical Center
- [ ] vha_504BY	Lubbock VA Clinic
- [ ] vha_504BZ	Clovis VA Clinic
- [ ] vha_504GA	Childress VA Clinic
- [ ] vha_504HB	Dalhart VA Clinic

VA Central Texas health care
- [ ] vha_674	Olin E. Teague Veterans' Center
- [ ] vha_674A4	Doris Miller Department of Veterans Affairs Medical Center
- [ ] vha_674BY	Austin VA Clinic
- [ ] vha_674GA	Palestine VA Clinic
- [ ] vha_674GB	Brownwood VA Clinic
- [ ] vha_674GC	Bryan VA Clinic
- [ ] vha_674GD	Cedar Park VA Clinic
- [ ] vha_674GF	Temple VA Clinic
- [ ] vha_674HB	LaGrange VA Clinic

VA North Texas health care
- [ ] vha_549A4	Sam Rayburn Memorial Veterans Center
- [ ] vha_549A5	Garland VA Medical Center
- [ ] vha_549BY	Fort Worth VA Clinic
- [ ] vha_549GD	Denton VA Clinic
- [ ] vha_549GE	Decatur VA Clinic
- [ ] vha_549GF	Granbury VA Clinic
- [ ] vha_549GH	Greenville VA Clinic
- [ ] vha_549GJ	Sherman VA Clinic
- [ ] vha_549GK	Polk Street VA Clinic
- [ ] vha_549GL	Plano VA Clinic
- [ ] vha_549GM	Grand Prairie VA Clinic
- [ ] vha_549HK	*North Texas VA Mobile Clinic
- [ ] vha_549QA	Dallas VA Clinic
- [ ] vha_549QB	East Lancaster VA Clinic
- [ ] vha_549QC	Tyler Broadway VA Clinic

VA South Texas health care
- [ ] vha_671	Audie L. Murphy Memorial Veterans' Hospital
- [ ] vha_671A4	Kerrville VA Medical Center
- [ ] vha_671BY	Frank M. Tejeda Department of Veterans Affairs Outpatient Clinic
- [ ] vha_671GB	Victoria VA Clinic
- [ ] vha_671GF	South Bexar County VA Clinic
- [ ] vha_671GH	Beeville VA Clinic
- [ ] vha_671GK	San Antonio VA Clinic
- [ ] vha_671GK01	San Antonio-Northeast 410 VA Clinic
- [ ] vha_671GK02	San Antonio-Southwest Military VA Clinic
- [ ] vha_671GK03	San Antonio-Pecan Valley VA Clinic
- [ ] vha_671GL	New Braunfels VA Clinic
- [ ] vha_671GN	Seguin VA Clinic
- [ ] vha_671GO	North Central Federal VA Clinic
- [ ] vha_671GP	Balcones Heights VA Clinic
- [ ] vha_671GQ	Shavano Park VA Clinic
- [ ] vha_671GR	North Bexar VA Clinic
- [ ] vha_671QA	South Texas VA Mobile Clinic
- [ ] vha_671QB	Data Point VA Clinic

VA Texas Valley health care
- [ ] vha_740	Harlingen VA Clinic
- [ ] vha_740GA	Harlingen VA Clinic-Treasure Hills
- [ ] vha_740GB	McAllen VA Clinic
- [ ] vha_740GC	Corpus Christi VA Clinic
- [ ] vha_740GD	Laredo VA Clinic
- [ ] vha_740GH	South Enterprize VA Clinic
- [ ] vha_740GI	Old Brownsville VA Clinic
- [ ] vha_740GJ	North Tenth Street VA Clinic
- [ ] vha_740QA	Texas Valley Coastal Bend VA Mobile Clinic

VA El Paso health care
- [ ] vha_756	El Paso VA Clinic
- [ ] vha_756GA	Las Cruces VA Clinic
- [ ] vha_756GB	El Paso Eastside VA Clinic
- [ ] vha_756GC	El Paso Westside VA Clinic
- [ ] vha_756GD	El Paso Northeast VA Clinic
- [ ] vha_756QA	El Paso South Central VA Clinic
- [ ] vha_756QB	El Paso Central VA Clinic

VA West Texas health care
- [ ] vha_519	George H. O'Brien, Jr., Department of Veterans Affairs Medical Center
- [ ] vha_519GA	Wilson and Young Medal of Honor VA Clinic
- [ ] vha_519GB	Hobbs VA Clinic
- [ ] vha_519GD	Fort Stockton VA Clinic
- [ ] vha_519HC	Abilene VA Clinic
- [ ] vha_519HF	San Angelo VA Clinic

## Acceptance Criteria
- [ ] All pages stubbed out and created per IA map
- [ ] All content translated to new Plain language and design
- [ ] All internal and external testing completed and updated
- [ ] Site published to Dual-state and tested
- [ ] All 508 /accessibility testing completed and corrected
- [ ] Site ownership handed to Trained PAO
- [ ] Site launched to Live
