### ISSUE TITLE
[REVIEW] Internal Review, Test, Proof Read, and CORRECT all NODES for  "VA Syracuse health care" ending with stakeholder review doc [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20371]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[VISN-2 Internal Review Folder](https://drive.google.com/drive/folders/1QW3CJjCQBVFKh2iIyxJxAdDiH6P-4PY6)
[Review template for review](https://drive.google.com/drive/folders/1QW3CJjCQBVFKh2iIyxJxAdDiH6P-4PY6)
[Syracuse Legacy Site](www.syracuse.va.gov)

## Tasks
- 1) Confirm Correct facilities are listed by comparing Story, VAST DB/spreadsheet, and Legacy Site.
- [x] Updated Story below with correct facilities.
- [x] Publish change in VAMC Support Channel
- [x] Update Facility change list (owner: ltrombley)

- 2) Complete review of system and facility pages, manual review and test URLS, phone #s, and hyperlinks for:
- [x] 528G5	Auburn VA Clinic
- [x] 528A7	Syracuse VA Medical Center
- [x] 528G9	Tompkins County VA Clinic
- [x] 528GL	Massena VA Clinic
- [x] 528GM	Donald J. Mitchell VA Outpatient Clinic
- [x] 528GN	Binghamton VA Clinic
- [x] 528GO	Watertown VA Clinic
- [x] 528GP	Oswego VA Clinic
- [x] 528QN	Watertown 2 VA Clinic
- [x] 528QI	Erie East VA Clinic
- [x] 528QG	Erie West VA Clinic
- [x] 528QH	South Salina VA Clinic

- 3) Review and correct all **Broken Links** on each of the system pages in Tugboat
- Document all errors, items that need update and testing on each page using spreadsheet listed above_

**When completed spreadsheet is complete, Look for review from Content Team and begin clean-up**
- [x] Update and clean up all pages as provided by review and Content team input.

## Acceptance Criteria
* All URL and node/pages must have been documented in Spreadsheet.
* Broken links, issues in page, duplicates, or anomalies must resolved and/or be documented.
* Issues should list "FIXED" if they were updated in product or high lighted in red if still an outstanding issue.
* Issues that cannot be resolved must be highlighted.  Areas that are not typical need to be posted in Support channel.

**Comment by ltrombley** [comment]
Added 3 Additional Clinics per VAST:
- [ ] 528QI	Erie East VA Clinic
- [ ] 528QG	Erie West VA Clinic
- [ ] 528QH	South Salina VA Clinic

**Comment by ltrombley** [comment]
Task #20371- Internal Review "VA Syracuse health care" is Complete and moved to Validate.
