### ISSUE TITLE
Internal 508 Testing for Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2037]
## Goal
As an frontend engineer, I want an internal 508 test, so I know my application is as accessible as possible, and accounts for various different user scenarios before official 508 review. 

## Task
- Define the 508 testing domains for this feature and reference any existing documentation and create a test infrastructure.
- Keyboard functionality/accessibility
- Onscreen, color contrast, color blind review

## Considerations
- [x] [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/508-checklist-wip.md)

## Acceptance Criteria
- [x] New feature passes aXe tests in Chrome
- [x] Screen reader check
- [x] Review 508 Checklist
- [x] [Schedule a review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md) with 508 Team (Trevor Pierce or Jennifer Strickland) once Rated Disabilities is moved into staging.

**Comment by micahchiang** [comment]
We discussed during backlog grooming today that this is a ticket which should be completed as Rated Disabilities nears a production ready state. Given how much change is coming to the UI of Rated Disabilities (two pages, one logged out view, one logged in view, side bar, etc), should we consider moving this into the backlog for now?

**Comment by micahchiang** [comment]
## Findings:
- Links do not have aria-labels.
- Compensation 101 link needs to indicate it opens in a new tab.
- Your VA disability rating should be an H1 and be independent of total rating state.

**Comment by micahchiang** [comment]
@cohnjesse, @jason-gcio - Should we leave the screen reader check to Trevor / Jennifer? They probably have better resources for it, and they'd be doing a screen reader audit anyway. Otherwise, I think this ticket can be considered done.

**Comment by jason-gcio** [comment]
Let's do at least a check that the screen reader kicks off correctly.
