### ISSUE TITLE
[Design] MyVA: Post Research Planning

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20387]
## Background
Following research, we need to create a plan for the changes. 

## Tasks
 - [ ] Create list of design updates
 - [ ] Determine if we have time for additional research
 - [ ] Determine design handoff deadline
 - [ ] Conduct post research planning
 - [ ] Create plan for changes we will implement
 - [ ] Review with Samara

**Comment by tressaellen** [comment]
Based on the research, these are the changes that I recommend for My VA.

1. Remove grey boxes in messages and prescriptions.
2. Keep totals for messages, but remove totals for appointments, claims and prescriptions. Replace with a 'Manage all X' CTA.   
3. Update CTA verbiage to be more actionable (i.e. Manage all prescriptions) in all sections.
4. Make the 'What benefits does the VA offer' dropdown more visible, or move to the top of section.
5. Eventually add in payment history and a notification hub when time/functionality allows.

**Comment by Samara-Strauss** [comment]
Awesome! And I have created the following tickets for all follow-up design work:

- Post-usability testing updates to the Health care section #21170
- Post-usability testing updates to the Claims section #21172
- Post-usability testing updates to the Apply for VA benefits section #21175

Closing!
