### ISSUE TITLE
AE Sprint 42

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20385]
## Priorities
1. Onboarding Liz
2. MyVA: Research sessions
3. MyVA: Continue FE work
4. DD4edu: Kickoff UAT recruiting
5. DD4edu: Privacy/Security review and finish Contact Center Review
6. Notification Preferences: Finish BE integration
7.  DD4edu: Direct deposit email change (GovDelivery -> VANotify)
8. Resolve Profile error issues

## Profile
**PM**
- [x] Track progress on all open VA Profile-dependent issues (#18549, #20509, #20537, #20397) and follow up with VA Profile
  - **Note**: None of the above issues have been closed, and are still open because of VA Profile dependencies.

**FE**
- [x] Profile: Remove "Your" from "Your Profile" #19890
- [x] Investigate reason for 'Address line too long' update errors in Profile #20079
- [x] Clicking "edit address" from validation view wipes out user-entered address #19978

**BE**

- [ ] Remove references to vet360 from backend code (part 1) #18258
- [x] Remove VA profile defaultable attributes from passed in params #20733

## My VA redesign
**Design**
- [x] [Design] MyVA 2.0: Conduct research #19725
- [x] [Design] MyVA - Research Summary #20386
- [x] [Design] MyVA: Post Research Planning #20387

**FE** 
- [Epic] Load Health Care data and wire it up to the Health Care widget #19743
  - [x] Wire up prescriptions to My VA Health care #21047
  - [ ] Wire up appointments to My VA Health care #21052
  - [ ] Add Cerner AlertBox to My VA Dashboard #21057
- [x] [FE] Show a different view for In-progress Applications that have expired #20177
- [x] [FE] Add RTL tests for "Benefits you might be interested in" #20159
- [ ] [FE] Build the Claims and Appeals section #19742

## Direct deposit for edu
**PM**
- [x] [PM] DD4edu: Conduct Contact Center review #19899
- [x] [PM] DD4edu: UAT Go-No/Go #20389
- [x] [PM] DD4edu Determine Communications needs (GTM strategy) #20390
- [x] [PM] Readiness Review: Authenticated Experience - Direct Deposit for Education Benefits [228](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/228#issuecomment-789163252) 

**FE**
- [x] (Content blocker)  508-defect-2 [COGNITION, SEMANTIC MARKUP]: Buttons MUST have descriptive and accessible labels #19570
- [x] Answer questions in Readiness Review: Authenticated Experience - Direct Deposit for Education Benefits [228](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/228#issuecomment-789163252) 

**Design** (Jim Adams)
- [x] [Design] DD4edu - Kick off UAT recruiting #20388
- [x] [Design] DD4edu: Create UAT Research plan #19728
- [x] [Design] DD4edu: Create UAT Conversation Guide #19729

**BE**
- [x] Move direct deposit emails from GovDelivery > VANotify #19233
- [x] Answer questions in Readiness Review: Authenticated Experience - Direct Deposit for Education Benefits [228](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/228#issuecomment-789163252) 

## VA Profile Notification Preferences

**Design**

- [x] Onboard Liz #20391

**BE**

**On hold until Terry can get Lihan API access**

## Preferred medical facility

- [x] Onboard Liz #20392

## Unplanned

- [x] Create a system and/or data flow diagram for direct deposit for edu #20780
