### ISSUE TITLE
[PM] DD4edu: UAT Go-No/Go

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20389]
## Background
We need to make sure everything is in order prior to starting UAT.

## Tasks
- [x] Create/fill out [UAT go/no go form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/qa-testing/uat-go-no-go.md)
- [x] conduct Go/No-go meeting
- [x] Make changes as needed/ Determine next step

**Comment by Samara-Strauss** [comment]
**Result**: We are a-go for UAT!

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/qa-testing/uat-go-no-go.md
