### ISSUE TITLE
[PM] VA Profile: Notification preferences: Onboard Liz

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20391]
## Background 
Liz Lantz will be joining the AE team on 3/4/21. We need to get her up to speed on the Notification Preferences work.

## Tasks
- [x] Review materials prior to meeting with Samara
  - [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
  - [MVP documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/communications-permissions-mvp-definition.md)
- [x] Meet with Samara to go over materials/the project in detail
- [x] Discuss discovery planning

**Comment by Samara-Strauss** [comment]
Discovery ticket in #20867. Closing!
