### ISSUE TITLE
[PM] Preferred Facility: Onboard Liz

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20392]
## Background 
Liz Lantz will be joining the AE team on 3/4/21. We need to get her up to speed on the Preferred Facility work.

## Tasks
- [x] Review materials prior to meeting with Samara
  - [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/README.md)
- [x] Meet with Samara to go over materials/the project in detail
- [x] Discuss discovery planning

**Comment by Samara-Strauss** [comment]
Added #20866 for discovery. Closing!
