### ISSUE TITLE
[SD] Surfacing VA Search Tools

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#20402]
## Description

As a product team we would like to redesign the search results page to better meet the needs of veterans and other va.gov users. 

## Tasks

- [ ] Design Exploration #21376
- [ ] Integrate Global Search elements update thru UI Consistency Discussions #21977
- [ ] Finalize Design Work #22498
- [ ] Review Designs with Ryan Thurlwell & Meg Peters from DEPO (TBD)
- [ ] Initiate Collab Cycle with Project Kickoff
- [ ] Implement Design Recommendations #21382

## Tracking Collab Cycle Events + Status
- [ ] Project Kickoff  [GH #27753 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27753)
- [ ] Design Intent [GH #27754](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27754) Midpoint Review ("Design Intent")
-  Shira + Denise agreed that the meeting aligned with the structure of a design intent meeting and therefore we will reclassify it and track it as though it was a design intent. 

***Summary of feedback:***

|Platform Team|GH Issue| Feedback Comments  |
|--|--|--|
|In Meeting comments  | n/a |1) Search won’t show up as a landmark if it is a link or a part of a dropdown. 2) The headers in the cards should be H2. 3) On Mobile we can simplify the list to decrease the spacing to make it easier to read. Links should not be buttons.  4) Some users will not see the gray background of the boxes. |
|Accessibility  | #28107 |**Should:** Either make all the additional search headings `h2`s or add a buffer `h2` called "Additional search tools" _and then_ make the additional search tool headings `h3`s **Should:** Update initative brief to include a breakdown of past user research sessions **Should:** Think of assistive technologies (AT) specific KPIs **Consider:** Maintaining a search 'landmark' for screen reader users|
|Design  | [#28194](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28194) |**Must:**  The dark blue buttons should be links not buttons **Should:** The headers in the cards should be H2. **Consider:** Using the gray boxes but remove the links|
|QA  | [#28195](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28195) |1) Develop Draft Test Plan 2) Review QA Articles 3) Create E2E testing for search landing page 4) Modify existing E2E test spec|
|IA  | [#28209](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28209)  |**Breadcrumbs** -   Showing "Search results" in the breadcrumb prior to showing results is not accurate. Options in the ticket to fix. 

- [ ] IA request
- [ ] Research Plan Review
- [ ] Analytics Request
- [ ] Usability Testing Prep
- [ ] Contact center review
- [ ] Staging review
- [ ] Privacy + Security
- [ ] Target Launch Date
- [ ] Full Accessibility + 508 Office Audit
- [ ] Post Launch Check in

## Definition of Done

- [ ] Designs have been created, defined and are ready for development team implementation
