### ISSUE TITLE
Schedule Design Intent: CH31 Orientation Content

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20414]
`async review`

## Background
Now that this feature is more or less fully mocked, we need to bring it before the Design Review group for further discussion and approval.

## Tasks
- [x] Determine if the meeting should be asynchronous or not
  - Sync when designs are very new/ significantly different; else async
- [x] Determine outcomes from the review: _"What are we asking for?"_
- [x] Schedule a review using the [Design Intent ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+allison0034&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D) 

## Acceptance Criteria
- [ ] A meeting has been scheduled, 
**or**
- [x] Async review has been requested

**Comment by jason-gcio** [comment]
request: https://dsva.slack.com/archives/C0NGDDXME/p1615248937040700
