### ISSUE TITLE
Conduct UA for LGY: COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20413]
## Background
LGY/COE is in the Discovery phase. Research session dates/times have been requested for the first week of March. The eBenefits team will conduct discovery interview with Veterans and service members who have experience with VA home loan benefits.

## Goal
The overall goal of these interviews is to achieve a baseline understanding of the VA loan timeline and how COE fits into that process.

## Tasks
- [x] Incorporate stakeholder feedback into the convo guide
- [x] Deliver research plan and convo guide to Lauren A. to initiate research kickoff
- [x] Schedule interview sessions
- [x] Conduct interviews

## Acceptance criteria
- [x] Interviews conducted and research study closed

**Comment by sporeboy** [comment]
Incorporated feedback in convo guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/discovery-interviews/coe-discovery-convo-guide.md

Lauren review/research kick-off requested.

**Comment by sporeboy** [comment]
Sessions complete... Notes being transcribed.

**Comment by jason-gcio** [comment]
@sporeboy - would you like another ticket for the notes/summary part?
