### ISSUE TITLE
Establish Wireframes for Onsite Search KPIs 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#20440]
## Description

KPIs for Onsite Search have been identified in GH#16778. To ensure clear lines of communication the search and discovery team would like to establish wireframes/depictions of how we would like to see data represented. 

## Background/Context/Resources

Analytics Request to establish KPI Dashboard  - GH #16778

## Tasks

- [x] Create wireframes or some form of representation for data
- [x] Review with Search & discovery team members
- [ ] Update Analytics request ticket to communicate intent to the analytics team as they prepare to establish the DOMO Dashboard

## Definition of Done
- [ ] Analytics Request has been updated with agreed upon representations.

**Comment by mgleo** [comment]
![domo-search-kpis.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/5664ba7f-9912-48a6-b520-625cf14ebfaf)
