### ISSUE TITLE
Review adding CMS-focused question to Collaboration Cycle Kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#20444]
## Issue Description
CMS Product Support team wants to be proactive in engaging with teams that may need their services, and wants to encourage teams that already use their services to reach out earlier in their build process. 

Proposed question to add from Clarence Maeng:
```
Is your product going to be part of the VA.gov unauthenticated experience?
- If "yes" then please reach out to @John Hashimoto and @Dave Conlon, who will help to explore if integration with existing content or housing new content in the CMS will be needed.
- If "no" then no action needed.
```
On 3/23, Clarence suggested the following:

```
Replace: "Will your work impact only static content pages?"
With: "Will your work impact content within any of the following products?"

Public Websites related: VA.gov homepage, Benefits hubs, Outreach hub, Resources & Support, Campaign landing page, VA form detail pages
Facility Related: Vet Center, Cemetery, Regional Office, VAMC system

```

---
## Tasks
- [ ] Schedule a meeting with CMS and discuss the following:
   - [ ] Evaluate the question to determine if it is the appropriate question to ask to VFS teams (Do our CC Kickoff questions already suffice? Would we benefit from altering an existing question? etc.)
   - [ ] Provide context into why we are asking this question, and not just the intended action if answered a certain way
   - [ ] Is there a more formal intake process for CMS opposed to reaching out to John and Dave?

## Acceptance Criteria
- [x] VSP Product Support will modify the Collaboration Cycle Kickoff issue template (and the Getting Started guide) to address CMS's need for VFS engagement
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
