### ISSUE TITLE
Identify issues/findings/defects for IA, design and content

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#20443]
## Issue Description
Currently for the Collaboration Cycle, VSP team members provide "Feedback" at Staging Review that follows a Must, Should, Consider framework. When the team launches their product, there is no way to verify/track if all, some, or none of the feedback was addressed by the team. There is no reference for a VFS team to understand (prior to the "Feedback" ticket being created) what type of issues/defects would be classified as a Must, Should and Consider. VFS teams also do not have an understanding of what feedback has to be addressed prior to launch and what feedback can be addressed post-launch.

The only practice area that doesn't currently have this issue is Accessibility. Because of the [Accessibility Defect Severity Rubric ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md), VFS teams understand the type of accessibility issues that are uncovered at Staging, the severity of those issues, and whether these issues must be addressed prior to launch, or can be handled post-launch. 

Edit: QA has been removed from this issue due to bandwidth/scheduling conflicts with Testing Tools Team.

## User Stories

As a VFS team member, I want to know what issues might be uncovered at the Collaboration Cycle Staging Review so that I can ensure they are addressed ahead of time.

As a VFS Product Manager, I want to know what issues could be potential launch blockers so that my product is not delayed due to these issues not being addressed.

As a VSP Collaboration Cycle team member, I want to ensure VFS teams have a clear understanding of what issues we are identifying so that there is no confusion and/or frustration for VFS teams if/when issues are uncovered at Staging Review.

As a DEPO lead, I want to ensure there is transparency between VFS and VSP teams regarding platform standards and launch blockers so that I do not have to escalate concerns.

## Tasks
- [ ] Identify and list the high level issues/findings/defects/concerns that could be uncovered at Staging Review for your individual practice area
- [ ] For each issue identified, specify the impact if the VFS team were to launch without addressing/resolving the issue
- [ ] Receive feedback from our OCTO practice area leads:
Design - Ryan Thurlwell
IA - Meg Peters
Content - Beth Potts and Danielle Thierry

## Acceptance Criteria
- [ ] VFS teams understand what type of issues (QA, IA, content, design) could be uncovered at Staging
- [ ] VFS teams understand the severity of the issues uncovered at Staging
- [ ] VFS teams understand whether the issues uncovered are launch blockers or not
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034 I am linking your Design "defects" doc here: https://docs.google.com/document/d/1dO188vU-BGHONeR_OU7_9ILnzG0bo6_HWT0epzNfyDQ/edit#

**Comment by shiragoodman** [comment]
Hey team - I closed ticket [#20630](https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/20630) since it wasn't necessary to have both this ticket and the other one open. Please be sure to use this ticket moving forward.

**Comment by shiragoodman** [comment]
review what "impact" has been identified across standards to see if there's common themes

**Comment by shiragoodman** [comment]
[Proposed Platform Standards](https://docs.google.com/spreadsheets/d/1IkIX7CgbFneFvlia1r9mYD8QU7uML5HWILkM7qsxizs/edit#gid=0)

**Comment by shiragoodman** [comment]
Sprint 49 objectives:
1. define the high level topic
2. specify if feedback is applicable for Design Intent, Midpoint Review and/or Staging Review
3. Review practice areas and confirm that the issues is applicable to the practice area
4. flag and overlap / duplicates
5. merge/roll up like/similar issues into broader "review criteria"

**Comment by shiragoodman** [comment]
Accessibility specialists (as part of Testing Tools team effort) are working to incorporate WCAG 2.1 guidance into our Accessibility criteria. These efforts will be merged with the IA, design and content standards. Accessibility standards can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/feature/web-accessibility-testing-plan/platform/accessibility/wcag21/web-accessibility-testing-plan.md

cc: @1Copenut @noahgelman @JoeTice
