### ISSUE TITLE
Collaboration Cycle Kickoff Debt Resolution - Medical Copays (MCP) 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#20449]
## Steps to complete Collaboration Cycle Kickoff
- [ ] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [ ] VFS: Answer the questions below.
- [ ] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [ ] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Collab Cycle touchpoints:

- [x]  Design Intent (#24438)
- [x]  Information Architecture (IA) Request (#25663)
- [ ]  Research Plan Review
- [ ]  Analytics Request
- [x]  Midpoint Review (#27333)
- [ ]  Contact Center Review
- [ ]  Staging Review
- [ ]  Privacy and Security Review
- [ ]  Full Accessibility and 508 Office Audit
- [ ]  Post-launch Check-in

## Artifacts (if available)
- Link to draft of [[product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Product_Outline_Medical_Copays.md)]
- Link to [wireframes, mockups, or prototypes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Medical_Copays/research/feb-2021)
- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

**Will your work result in visible changes to the user experience?**
- [ X] Yes
- [ ] No

**Is your work a new product/feature or an iteration to an existing product/feature?**
- [ X] New
- [ ] Iteration

**Will your work impact only static content pages?**
- [X ] Yes
- [ ] No

**Are you making changes to the visual design?**
- [X ] Yes
- [ ] No

**Are you making changes to content?**
- [X ] Yes
- [ ] No

**Are you making a change to the user flow?**
- [X ] Yes
- [ ] No

**Are you making a change to urls, navigation, or entry points?**
- [ ] Yes
- [ X] No

**Are you doing research with VA.gov users?**
- [ X] Yes
- [ ] No

**Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?**
- [X ] Yes
- [ ] No

**If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?**
- [X ] Yes
- [ ] No

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @leahkeeler. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, we are recommending the following Collaboration Cycle touchpoints:

- Design Intent (can be asynch)
- Information Architecture (IA) Request
- Research Plan Review
- Analytics Request
- Midpoint Review (can be asynch)
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch:

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process:

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our [Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) page for next steps.

**Comment by leahkeeler** [comment]
Thank-you @shiragoodman - will you be sending out the meeting invite
