### ISSUE TITLE
Schedule Design Intent: View Dependents Formlet

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20497]
`sync`

## Background
Now that this feature is more or less fully mocked, we need to bring it before the Design Review group for further discussion and approval.

## Tasks
- [x] Determine if the meeting should be asynchronous or not
  - Sync when designs are very new/ significantly different; else async
- [x] Determine outcomes from the review: _"What are we asking for?"_
- [x] Request a review using the [Design Intent ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+allison0034&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D) 

## Acceptance Criteria
- [x] A meeting has been requested and/or scheduled, 
**or**
- [ ] Async review has been requested and/or scheduled

**Comment by jason-gcio** [comment]
Request: https://dsva.slack.com/archives/C0NGDDXME/p1615244440039300
