### ISSUE TITLE
Add clear input feature to Community care service type field 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20498]
## Issue Description
#16513 adds an efficient way to clear the City, state or postal code fields so Veterans can change the input. This issue is to add the same feature to the Service typeahead field which is required when Facility type = Community providers (in VA's network)/ 

<details>
<summary> button spec </summary>

![image](https://user-images.githubusercontent.com/55411834/109198314-4fd4af80-775b-11eb-9452-80d21f5497a4.png)

![image](https://user-images.githubusercontent.com/55411834/109198218-329fe100-775b-11eb-8db6-1a916c03494b.png)

</details>

---
## Tasks
- [ ] Add x to clear fields consistent with spec

## Acceptance Criteria

- [ ]  Clear field icon is consistent with design spec with regard to padding, size and expected behavior.
- [ ]  Clear input button appears after first character is inputted
- [ ]  While text is being inputted and exceeds the input's width, the text moves left.
- [ ]  Text area is never overlapped by clear input button while field has focus
- [ ]  When user exits input (no longer in focus) the inputted text displays left to right. Overflow text (at the end of the text string) is overlapped by clear input button.
- [ ]  Veteran can clear input by clicking on the x.
- [ ]  When clear button is clicked, input is cleared and design matches "Before interaction" state.
- [ ]  Veterans using assistive screenreaders are aware of this functionality.
- [ ]  Hidden aria label "clean input button" when in focus to make it available to assistive tech
- [ ]  Search is not available until all required fields have been populated.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
