### ISSUE TITLE
[FSR] Empty state for when there are no Veteran benefits

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#20506]
## Issue Description
_Currently, a Veteran is served a benefits screen displaying $0 if they have no active benefit payments from the VA. We want to replace that experience with a user-friendly empty state. See mockup here: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/137058261/specification/sitemap?mode=i_

---
## Tasks
- [ ] _Update the current empty state to display the card in the provided UXPin prototype_

## Acceptance Criteria
- [ ] _The FSR's UI has been updated to reflect the new empty state_
- [ ] _The updated UI has been reviewed by a designer_

**Comment by craigwheeler** [comment]
need mock user data for when there are no Veteran benefits
