### ISSUE TITLE
R&S article for online travel pay (article 1: direct deposit)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20519]
## User story
As a Veteran I need to know how to navigate the travel pay reimbursement system.

## Issue Description
Sitewide content needs to create articles within R&S about how to use the travel pay reimbursement system. 

The new AccessVA website travel pay reimbursement system is complex. We had to add the information on the main benefit hub page quickly. We want to create articles in R&S to help Veterans navigate the process, to lighten the amount of content on the main page, and to eliminate the need for the pdf instructions.

This is a ticket for article #1: How to set up direct deposit for VA travel reimbursement

## Info you'll need

Here's the info you'll need:

- Template: How to article
- H1: How to set up direct deposit for VA travel pay reimbursement
- CTA buttons: 1 to [Access VA](https://eauth.va.gov/accessva/) and 1 to [VA Form 10091](https://www.va.gov/find-forms/about-form-10091/)
- Benefit area: Health care
- Include a related link to https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
- We'll also want to add a link from the main VA travel pay reimbursement page to this article. Since this is a first step before you can use the reimbursement system, we should include that link here:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/f3f65bc1-74c1-41d5-b2bc-1d2de9c24ab8)

We can use text like. "You'll need to have direct deposit set up to get your travel reimbursement payments. If you don't have direct deposit set up yet, [link] find out how to set up direct deposit now."

### Content for how to subway map provided by stakeholders (to be edited to align with VA.gov plain language + content standards)

**Step 1: Start direct deposit from VA**
If you do not have direct deposit set up already, you will need to complete and return VA Form 10091. You will need your bank’s name and account and routing numbers to set up direct deposit. The form can be faxed or hand delivered to the local beneficiary travel office.

_Notes from Danielle on Step 1:_

- Incorporate a link to this Q&A (https://www.va.gov/resources/what-if-i-dont-have-a-bank-account-but-i-want-to-use-direct-deposit/). 

**Step 2: Create a DS Logon Level 2 (Premium) Account**
A DS Logon Level 2 (Premium) account is the same as an eBenefits Premium account, but is different from a My HealtheVet account. If you do not have a DS Logon, or you are not sure, you can register, verify or update your DS Logon account from the DoD DS Logon Access Center.

**Step 3: Create a BTSSS Profile**
Log into BTSSS and choose “Proceed to Profile Review.” Enter or save any updates to your personal, contact, or banking information. Once finished, choose “Request Profile Updates” to send a notification to the beneficiary travel office at the nearest VA medical center. You will receive a notice when the updates are complete.

**Step 4: File or Track a Claim**
With your profile created, you are now ready to file or track the status of a submitted claim.

## Tasks
- [x] Build page (Selina)
- [x] Review page (Randi and Danielle or Beth)
- [ ] Send preview of page to stakeholders for accuracy check (Randi)
- [ ] When stakeholder gives thumbs up, publish page (Randi, Selina)

## Acceptance Criteria
- [ ] New article live on site
- [ ] Link to article added to Travel page page

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I filled in more details. Happy to answer any questions or jump on a call to talk through it!

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lunascoop I added the label "high priority" on this to differentiate it from some of the other R&S health care tickets that I'm starting to add. This is the top need in health care because a) the system is complex and we want to help people navigate, b) travel pay is a top search term in R&S, and c) the existing Travel pay page in the health care hub has gotten _way_ too long/dense as we've had to add more and more info.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @lunascoop. Here's the revised ticket for this first travel pay article.

@RLHecht I'll introduce you to the stakeholders via email so you can send them the preview of the article for the accuracy check.

@bethpottsVADEPO Assigned you to this one since I'm preparing to be mostly focused on the sprint soon as our DEPO review.

**Comment by bethpottsVADEPO** [comment]
@RLHecht When you're done with your copyedit pass, let me know and I'll do a higher-level review of this page!

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review

**Comment by RLHecht** [comment]
@bethpotts This is ready for you to look at: preview-prod.vfs.va.gov/preview?nodeId=16665

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop... update on this how-to article: @DanielleThierryUSDSVA and I both dug into this yesterday and edited at a high level and also addressed some of the smaller details because it became apparent that the focus of the article needed some rethinking. I just finished making additional changes, so @RLHecht would you please copyedit again? Alert Danielle when you're done and she will send it to stakeholders. Just wanted to keep you in the loop.

**Summary of the first step in the subway map/edits I made there, fyi**: 
- I looked at the form and saw that more information was required to fill out the form than what was mentioned, so I added SSN, bank name and address, and account type. To see what's required and what's optional, you have to scroll down past the part of the form you fill in. 
- I created a bulleted list so the content is scannable 
- I added the fax number. 
- I used the standard pattern for mentioning form names (at the top of step 1) and then the download link with (PDF). Also used our standard language for talking about submitting the form (at the bottom of step 1)--i.e., we don't use "deliver" but rather "bring it to" if the Veteran will be walking it into an office in person.

Bigger-picture too, each of these steps felt very separate--not connected in a meaningful enough way, so @DanielleThierryUSDSVA changed those so they more accurately reflect the steps a user will take. 

Randi--when you do a final copyedit, can you add any treatment that may be needed (if any) for the fax number I added so it's in line with our site style? I found the number on the form itself. Might be a good idea to add a line to the pre-pub checklist for phone and fax numbers. Basically something like: if we say "call us" or "fax us" we should include the number. I know we're not at the pre-pub stage here, but if that detail hadn't gotten caught here, it would need to have been caught before we published the article. Thanks!

**Comment by RLHecht** [comment]
@bethpottsVADEPO I did another copy check of this. All looked good though I broke out one of the bullets into two. Instead of 
- Routing and account number

I changed it to:

- Bank's routing number
- Bank account number

I also followed the steps in staging on a test user account and it checked out. 

@DanielleThierryUSDSVA This is ready to go to the stakeholders now.

**Comment by bethpottsVADEPO** [comment]
Thanks, @RLHecht ! Appreciate your edits and process check.

**Comment by RLHecht** [comment]
Closing this ticket. I switched the category to Other topics and added it to the landing page (and removed the PDF article). Once we have a health care section, we can move this out of other topics and into there.
