### ISSUE TITLE
Usability study: Facility Locator on Mobile

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#20513]
## Issue Description
_We need to understand how veterans use the Facility Locator on Mobile, what pain points exists, and how they use the new features ((Map view and Use my location and Close info card)
---
## Tasks
- [x] Plan research
- [x] Execute research
- [x] Synthesize findings 
- [x] Write a Findings report (Slide deck and Markdown file for Github)

## Acceptance Criteria
- [x] _Research plan
- [x] Convo guide
- [x] Findings deck
- [x] Markdown of findings in Github
---
## How to configure this issue
- [ ] **Sprint 41**
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
All of this research was completed in Sprint 41

**Comment by chrvalla** [comment]
Research complete
