### ISSUE TITLE
Pre-Launch Internal User Acceptance Testing

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#20511]
## Description
- The purpose of UAT is to ensure the app is working as we expect it to, and to discover any last bugs we need to fix before launching in app stores. UAT will be conducted with production data. 
- Distribution method for internal UAT is on TestFlight for iOS and via APK for Android.

**Acceptance Criteria**
- [x] Checklist below is complete

**Approx Date Needed by**
We did 7 sessions in late April. We want to keep doing 1-2 sessions/week, as we can, until launch. So we'll keep this ticket open until launch. 

## Reference Documentation
- UAT Folder: https://drive.google.com/open?id=1yLF4hPaDAYwBr39hEC6ajmzEZ10rxKCS

## Notes, Status & Tasks

5/3/21:
- First round of internal UAT (with friendlies) is complete
- We can continue to do internal UAT on a continuous basis but with less volume (1-3 interviews/week til launch)
- Designate what bugs constitute app-launch critical vs. not. What determines whether something is app-launch critical?

Immediate next steps (4/20): 
- Testing with the internal group is asap (on the calendar this week)
- Ashley is connecting with internal VA folks Leanna connected us with

# Internal UAT: Round 2

Context: we want to keep talking to new people until we launch as possible/we can get participants.

### Tasks related to prep
- [x] Set up HelloSign for internal participants going forward. **Owner: Bridget**

### Tasks related to recruitment & scheduling
- [x] Send out new call email to more folks at VA. **Owner: Ashley**
- [x] Send out HelloSign prior to sessions **Owner: Ashley**
- [x] Schedule sessions **Owner: Ashley**

### Tasks related to conducting sessions
- [x] Conduct 1-2 sessions/week starting the week of May 3 **Owner: Jen/Bridget/Melissa** We have 8 people signed up as of 5/7 1-3:30 ET Tues/Thurs.
- [x] Continue to log issues in the UAT Issues spreadsheet & Rank by severity matrix included in the [spreadsheet](https://docs.google.com/spreadsheets/d/1swOSRwSo2ULYFuzghiDYlX3qXm8_bD5dorAmxfAiMlI/edit?usp=drive_web&ouid=103668894305424319543). Create new tickets as needed. **Owner: Bridget/Ashley**
- [ ] [Tentative] Follow up 30-minute conversations with folks we've talked with so far. We might do this if we have a problem resolving an issue and need to check something with a former participant. 
- [x] [Tentative] Potentially ask people to come to internal UAT sessions prepared to cross-reference web and app data. We might do this if we want to see/test a specific use case. 

---
# Internal UAT: Round 1

### Tasks related to distribution
- [x] Determine distribution method for Apple **Owners: Bridget, Ashley, w/ guidance from Patrick**
- [x] Determine distribution method for Android **Owners: Bridget, Ashley, w/ guidance from Patrick**
- [x] Determine IF we are moving forward with UAT cross-platform (is the Android strategy usable?) **Owners: Bridget, Ashley, w/ guidance from Patrick S**
- [x] Document access instructions **Owners: Melissa**

### Tasks related to recruitment & scheduling
- [x] Align on timeline  **Owners: everyone**
- [x] Identify internal AH/VA folks who could be our internal testers, reach out to them & schedule sessions  **Owners: Ashley, Leanna**
- [x] Write UAT plan **Owners: Bridget, Ashley, Melissa** 

### Tasks related to conducting sessions
- [x] Conduct all internal pilot sessions  **Owners: Bridget, Melissa, Ashley**
- [x] Identify issues & determine next steps

---

**Comment by bridgethapner** [comment]
@ayushchak :wave: hi! I started a shell here for the UAT plan: https://docs.google.com/document/d/1Xi1Aq2rw7iVruitlEcjzxe13FOGku_2lJzdv-iD1zwA/edit?usp=sharing. This doesn't seem urgent yet and we'll have to keep building as we add stuff, but thought having a shell showing the types of research questions would be helpful. Let's work on this together down the line!

**Comment by bridgethapner** [comment]
Bridget / Ashley / Ayush met today to keep sketching out UAT approach (Google doc link above). 

**Next steps:** 
- Refine recruiting criteria
- Refine test questions
- Prioritize test questions

I can take the lead on these follow-up items & @ashley-matthews I will probably tag you in the GDoc to get your feedback - would love your POV on all the things.

**Comment by bridgethapner** [comment]
Hi there @ashley-matthews -- 

I added a checklist for this ticket, please take a look and feel free to edit as you see fit! 

I'd also love a gut check from you on time frame: 

- I chatted with @lexicalninja and he is aiming to have the app store migration done by the end of next week. When that is done, we can define the distribution UX and start the items under **Tasks related to distribution**. I don't think we can start these things until we have that migration complete, and we need at least a week to complete these instructions and ensure we have a solid distribution method we feel good about completing UAT with. This means we would be aiming to submit our plan to Perigean on **Friday, April 30th**. 
- This aligns well with the development timeline -- timing-wise, it seems like we think we'll be ready to start UAT on **Monday, May 10th** (after the next two sprints). 
- I think we need more than a week to conduct all the UAT sessions, so we could aim to have UAT sessions wrapped up by maybe **Wednesday, May 19th**. I'm thinking we can conduct the friendly UAT sessions from the 10th-12th and start with Perigean recruited folks on the 13th. 

What do you think?

**Comment by bridgethapner** [comment]
@artsymartha68 Hi there! I wanted to check in with you about your connection at BVA. We are trying to decide how much testing we are going to do before the app store release and our recruitment methods, so I wanted to check in with you about this - is working with them mid-May an option?

**One thing to be aware of:** we are still working out distribution methods, which are a question mark til a couple of weeks from now. We don't yet know how accessible the distribution methods pre-app stores release will be.

**Comment by artsymartha68** [comment]
I'll ping my 508 Office contact again. Haven't heard any updates.

**Comment by ambikaroos** [comment]
@leanna-usds can facilitate a casual UAT with internal people at VA who are eager to help test. @bridgethapner to incorporate this into the plan on Monday

**Comment by bridgethapner** [comment]
@drjecker @melissa-lefevre This is a good example of a (much smaller scope than us) UAT discussion guide we can reference as we build the discussion guide for the Perigean recruited sessions:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/uat/dd-edu-uat-convo-guide.md

I like the clarification in this guide: "UAT item: User confirms payment type(s) are correct (EDU, C&P, both)"

I could see us doing that like: "UAT item: User confirms dependency and disability claims within the last [x] years are shown and look correct" 

I'm also thinking we might want to ask folks to come to sessions prepared to answer these questions - people may not know off the top of their head if their claims _are_ all there...it may be helpful to check the list against VA.gov as part of the session? Do we want to get into cross-checking data? Seems like it could be useful, but also time-consuming and complicated...

**Comment by bridgethapner** [comment]
I added a checklist for Round 2 of Internal UAT & added owners for each task. @ashley-matthews please feel free to edit/add as you see fit!

**Comment by bridgethapner** [comment]
Findings from internal UAT have been logged on GitHub! This summary documents all the issues we logged, organized by severity level, and links to issues in ZenHub where we have made them. It also documents the UX/feature suggestions we heard about from participants during the sessions. I think we can consider this issue closed & close it in our 5/20 Launch Check-in.


# [Internal UAT Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/uat/internal-uat-summary.md)
