### ISSUE TITLE
OMB Burden Language UX Recommendation for ORMDI

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#20524]
## Issue Description
_The OMB burden language currently used on the new ORMDI - Medallia 4-question intercept survey seems excessively verbose and not aligned with OMB burden language best practices utilized on other VA.gov properties_

---
## Tasks
- [x] Review VA.gov OMB burden language best practices and implementation of such on VA.gov (referenced below with screenshot and link)
- [x] Review current ORMDI OMB burden language on their new intercept survey (referenced below with screenshot and link)
- [x] Document (in this ticket) recommendations for how ORMDI can reduce their OMB burden language into a better user experience
- [x] Provide recommendations to ORMDI team via email

## Acceptance Criteria
- [ ] Recommendations for OMB burden language on the ORMDI - Medallia 4-questions survey are provided to ORMDI team with the goal of reducing/transforming it into a better visual and actual user experience
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Hey @jwoodman5, my recommendation would be as follows:

Add the paragraph text under the [additional info component](https://design.va.gov/components/additional-info), so it expands when clicked. This would best mimic the response burden experience [elsewhere on the site](https://www.va.gov/health-care/apply/application/introduction), without relying on launching a second modal.

Here's a mockup of what that could look like:
![ormdiResponseBurden.jpg](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/63b46a04-cfa8-453d-a673-bb18a2a24e8d)

**Comment by jwoodman5** [comment]
Thank you for this, @ianMcCullough-ob !!

**Comment by jwoodman5** [comment]
@clantosswett Are we clear to send these recommendations ^ to ORMDI?

**Comment by jwoodman5** [comment]
Emailed recommendation with screenshot to ORMDI group on 4/30. Will open a new ticket if any additional work is necessary. Closing.
