### ISSUE TITLE
Incorporate stakeholder feedback for CH31 orientation mockups

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#20525]
## Background
CH 31 stakeholders have provided feedback on latest copy revisions for the orientation module via PDF.

## Tasks
- [x] Review feedback on CH31 copy
- [x] Triage feedback items: red, yellow, green
- [x] Implement green
- [x] Revise yellow
- [x] Provide guidance on why red are unacceptable
- [x] Remove videos
- [x] Document changes

## Acceptance criteria
- [x] Mockups updated and ready for stakeholder review
- [x] changes documented
