### ISSUE TITLE
Staging Review [Search & Discovery - Typeahead 1.0]

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#20532]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [ ] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to VSP feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [ ] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
**_Requested:_**
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
-  Staging test-user information (if applicable)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Link to your product [test cases](https://dsvavsp.testrail.io/index.php?/suites/view/150&group_by=cases:section_id&group_order=asc&group_id=612)/[test plan](https://dsvavsp.testrail.io/index.php?/plans/view/1457) in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/190) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/191) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

**_Provided:_**

- Collab Cycle Kickoff #20512
- Typeahead POC (5% of all va.gov users) #8896
- Typeahead 1.0 (100% of users with styling enhancements and suggestions quality improvements) #17558
- Release to 100% of Users #19368
Enhancement: Ordering suggestions based on character length #19369
Styling Improvement: Change suggested characters to be the bolded portion of the suggestion #19370
Styling improvement: Align typed search term in the input bar with drop down suggestions (also on #19370)
Enhancement: Global Blacklisting to improve quality of Typeahead Suggestions #19763 This effort will be incremental over the coming weeks since it requires the Search.gov team to implement.
- Link to [Staging](https://staging.va.gov/) where Typeahead can currently be explored
- [Typeahead DOMO Dashboard ](https://va-gov.domo.com/page/439942537?userId=1724393873)
- [Demo Slides
](https://docs.google.com/presentation/d/1re7s91M3Yi-qdXMXyvmMBiTIWbFczn6bZAM_zDN4CgA/edit?usp=sharing)

## Meeting attendees from requesting team
- Product Manager (required): Denise Coveyduc
- DEPO product lead (recommended): John Hashimoto
- Anyone else from your team who significantly contributed to the artifacts provided (required): Megan Gayle (Design/Researcher) & Sam Suddath (FE Engineer)
- Content, IA, accessibility, and QA specialists (if applicable): name(s)Tze Lei - AQ Engineer

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **date/time**

**Thursday March 4th  1:30-2:00pm** 

Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://docs.google.com/document/d/1_1gGJW6Go0Kk-H5jttDbQIZrcbKTst9gSZnXKVdeQSg/edit?usp=sharing) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
scheduled for 3/4 at 1:30 pm ET

**Comment by tlei123** [comment]
@pjhill , QA test-runs now completed -- QA-artifact links updated above in main description.

100% Passed; no defects logged.

cc @denisecoveyduc @shiragoodman

**Comment by denisecoveyduc** [comment]
For anyone who may be testing or reviewing the typeahead experience I wanted to let you know that search.gov has just completed a bug fix on their side that changed the database of the suggestions to remove any terms older than 30 days. 

We were not aware of this fix until yesterday but as a result if you are using a query that has not appeared in the last 30 days no suggestions will come back in the typeahead experience. The experience is not broken and works as intended but only recent or hardcoded queries will populate those suggestions. Note our team is actively working to populate database with additional suggestion using key VA terms and tasks.

Please refer to the list of top terms over the past few days for testing purposes. 

![image](https://user-images.githubusercontent.com/72393866/109991699-8d47b880-7cd8-11eb-9663-3a0f28dcd04e.png)

**Comment by shiragoodman** [comment]
Thanks @denisecoveyduc ! Tagging @1Copenut @noahgelman @pjhill @ddzz for their reference. See Denise's post above.

**Comment by denisecoveyduc** [comment]
Hi @shiragoodman  I have to send a huge apology for the last minute switch but we just met as a team and the recent changes are really changing our plans for this typeahead experience. As I just identified any queries that are older than 30 days are now no longer appearing as a typeahead suggestions. This is actually good news but what it means is we want to beef up the list of VA terms we are adding before we launch to additional users. If you can please just cancel our staging review and then we will ping when we have our timeline ironed out.  Again apologies everyone and thank you!

**Comment by shiragoodman** [comment]
no problem @denisecoveyduc . The Staging Review has been cancelled. We'll move this ticket to our backlog. Please tag me here when you are ready to reschedule.

**Comment by tlei123** [comment]
@denisecoveyduc @pjhill @ddzz , [TR test-case](https://dsvavsp.testrail.io/index.php?/cases/view/3164) & [referenced use-case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/type-ahead/type-ahead-use-cases.md#use-case-b---valid-search-string) updated now for search.gov bug-fix [per [Comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20532#issuecomment-790723175) above].

**Comment by denisecoveyduc** [comment]
Hi @shiragoodman Thanks for the quick touchpoint to iron these details out. As discussed we are launch typeahead 1.0 to 100% of va.gov traffic. As a result we need to schedule the formal staging review and if we can grab the next opening on Monday May 17th @3:30pm that would be great. 
cc: @johnhashva

**Comment by mnorthuis** [comment]
There is no IA feedback for this work.  Thanks!

**Comment by sshein** [comment]
Hi @denisecoveyduc! @joshkimux  and I just became aware of this, since he and Angela were not included in this ticket, a11y feedback on this will most likely be delayed. Especially since there are quite a few other staging reviews happening next week. Ping me with any questions - thanks!

**Comment by denisecoveyduc** [comment]
Hi @sshein, thanks for letting us know. I assumed when I opened this issue everyone was included. How should I include you and Josh going forward?

We had to cancel our original staging review  but in the time @1Copenut opened  #20721 and #20719 which were both 'consider' items. We are planning a phased roll out this week, will Trevor's review allow us to move forward?

**Comment by joshkimux** [comment]
@denisecoveyduc , if possible we'd love to be assigned or tagged on the ticket a week ahead of time 🙇 

As for your second question, we will need to wait for @AngelaFowler82 's review on JAWS and NVDA. I've completed testing on Safari/VoiceOver on desktop and have not found any notable defects. 

I do have a question on mobile though-- typeahead does not seem to work for iOS (on Chrome and Safari). Is this a known issue? 

![image](https://user-images.githubusercontent.com/14154792/118499229-ba5f1100-b6f4-11eb-9444-4cc60daccfa1.png)

**Comment by peggygannon** [comment]
I have no content feedback for this work. thx!

**Comment by denisecoveyduc** [comment]
@joshkimux  I think I understand what has happened and will ensure you are tagged ahead of time going forward. 
Thanks for reaching out to the team about issue seen on mobile; currently exploring further. For tracking purposes here is the [thread link](https://dsva.slack.com/archives/C011K1VSTC3/p1621259627449700?thread_ts=1621256472.444000&cid=C011K1VSTC3).

Thanks to you and @AngelaFowler82 for prioritizing. We will watch out for the JAWS And NVDA feedback.

**Comment by joshkimux** [comment]
@denisecoveyduc We've completed our feedback 🥳 

Angela wrote up a [defect-level-2 on firing off the search from selecting a suggestion from the typeahead list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24779) which was an issue we have brought up before when the typeahead was first made to be accessible.

Angela was also able to catch a [defect-level-2 with headings in the search results](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24778) which we are hoping to forward to the appropriate team as it's not specifically related to typeahead.

**Comment by denisecoveyduc** [comment]
All Staging review feedback has been documented in the Epic for Typeahead and will be integrated going forward. Refer to #17558 for additional details
