### ISSUE TITLE
ATO - Annual Web Application Security Assessment (WASA) Scan

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#20540]
## Description
WASA (Web Application Security Testing) Scans need to be performed annually per the requirements of ATO. The scan is requested through the VA's EAS portal, and contains administrative and technical information about the VSP infrastructure and services that are exposed on the internet, so that a scan be run to determine potential vulnerabilities with the infrastructure and services. 

## Background/context/resources
This year's scan needs to be submitted the week of March 6. 
This year, we are adding additional information to the scan request on behalf of VA Notify so that their services are included in the scan. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Information about VSP's infrastructure services & VA Notify's infrastructure services will be collected and submitted to request the WASA scan through the VA's EAS portal
- [ ] The results of the WASA scan will be received (~30 days later) and we will work to remediate any of the findings 

## Definition of Done
- [ ] The WASA scan comes back clean

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by fowusu2** [comment]
The WASA Scan was completed in May 2021
