### ISSUE TITLE
ATO - Annual Penetration Testing 2021

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#20541]
## Description
Penetration testing need to be performed annually per the requirements of ATO. The scan is requested through the VA's EAS portal, and contains administrative and technical information about the VSP infrastructure and services that are exposed on the internet, so that a scan be run to determine potential vulnerabilities with the infrastructure and services. 

## Background/context/resources
This year's scan needs to be submitted the week of March 6. 
This year, we are adding additional information to the scan request on behalf of VA Notify so that their services are included in the scan. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Information about VSP's infrastructure services & VA Notify's infrastructure services will be collected and submitted to request the Penetration test through the VA's EAS portal
- [ ] The results of the Penetration test will be received (~30 days later) and we will work to remediate any of the findings 

## Definition of Done
- [ ] The Penetration test comes back clean

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@troymosher & @gary-fallon - I believe this was done last year. 

Do you know if the tasks above were done? 
Do you know if the definition of done was met? 
Can this issue be closed?

**Comment by troymosher** [comment]
@jhouse-solvd from what I gather the pentest wasn't conducted, the poam was extended.  This issue can be closed though as it is OBE due to the effort to do the pentest for 3/31/2022.

cc: @gary-fallon

**Comment by jhouse-solvd** [comment]
Closing per Troy's comment above.
