### ISSUE TITLE
CT Redesign: LP - Benefit estimates updates - Solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20557]
## Definition of Done
Document approaches to improve ability to adjust benefits estimate on landing page - in particular on mobile devices	"

## Tasks
- [ ] Explore possible ways to address the challenge on mobile devices and on desktop 
- [ ] Document approaches with greatest potential
- [ ] Discuss pros/cons with UX team

**Comment by amyknox** [comment]
Mural for solutions: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1614213424605/b2d28e86b6944d3e22809581f4fd3eecf51f31e6
