### ISSUE TITLE
View Disability Rating in Staging

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#20558]
## Background
During 686 testing, we kept seeing a generic message on the Rated Disabilities page saying we do not have a disability rating for the user.  However, the majority of the test users should have disability ratings greater than 30%.  We need to investigate to see why the Rated Disabilities page is not displaying properly or if it is behaving as expected.

## Considerations
It is possible that depending on how these accounts were created in another system (VBMS?) they might not populate on this page correctly.

## Tasks
- [x] Test the Rated Disabilities page to determine whether it is working consistently in staging
- [x] If not, determine what is causing the disability rating to fail

## Acceptance Criteria
- [x] The cause of the Rated Disabilities problem has been identified

**Next Steps**
- [ ] A solution/fix has been determined
- [ ] A PR has been requested for merging, if a fix has been put in place

**Comment by kathleencrawford** [comment]
This issue has to do with how test users are created.  The "regular" test users in staging all work properly and the rated disability functionality works as expected.  The "ebn" test users that were created specifically for BGS 686 testing do not work properly for the rated disability feature because the users are not set up to access EVSS.
