### ISSUE TITLE
STEM Automated Denial: HTML Email - Design	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20566]
## Definition of Done
STEM AD HTML email prototype has been drafted	

## Tasks
- [ ] Prototype follows VA HTML email style
- [ ] Prototype incorporate STEM AD email content 
- [ ] Share prototype with relevant team members
- [ ] Respond to any questions

## Supporting Documentation
- Format content of automated decision in VA.gov style: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#email-frame-and-template

- Content document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-email-content.md

- InVision prototype of previous denial email:  https://bahdigital.invisionapp.com/d/main#/console/14222389/296053770/preview

**Comment by amyknox** [comment]
@watersemma - supporting documentation (content doc & invision link) have been added to this ticket. LMK if there's anything missing.

**Comment by watersemma** [comment]
Email has been updated according to copy & design guidance following VA HTML styles. See screen titled 'stem-automated-denial-email 2.0' here: https://bahdigital.invisionapp.com/share/BEIAGFECSGA
