### ISSUE TITLE
CT Redesign: LP - Search results display - Solutions	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20563]
## Definition of Done
Document approaches to more clearly indicate to users when searches have been executed	

## Tasks

- [x] Explore possible ways to address the challenge on mobile devices and on desktop 
- [x] Document approaches with greatest potential
- [x] Discuss pros/cons with UX team
