### ISSUE TITLE
Typo for COVID-19 vaccines on FL detail page 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20567]
## Issue Description
The service listing for COVID-19 vaccines on the Facility Locator service list is incorrect. 
![image](https://user-images.githubusercontent.com/55411834/109365918-6ceaaa80-784f-11eb-9188-abcb6f7b4d98.png)

Screenshot above from https://www.va.gov/find-locations/facility/vha_668

---
## Tasks
- [ ] Adjust service to read COVID-19 vaccines

## Acceptance Criteria
- [ ] When a Veteran views a detail page for a location offering COVID-19 vaccines, it will display `COVID-19 vaccines`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This comes from Lighthouse health services

**Comment by mmiddaugh** [comment]
Looks great - thank you
