### ISSUE TITLE
CT Redesign: Comparison View - Review Past Research

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20562]
## Definition of Done
Priorities for comparison view are captured in a shareable document	"* Review past research to identify what attributes beneficiaries would most like to compare

## Tasks

- [x] Document top-line findings in a shareable format - word doc or mural
- [x] Share findings with UX Team
- [ ] Discuss and prioritize"

**Comment by JenLJ** [comment]
Mural:  https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1614963146124/5158ba217131aa2fa9638e0f0ec914468df9039f
