### ISSUE TITLE
STEM Automated Denial: EDU Final Review	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20573]
## Definition of Done
EDU has reviewed and approved STEM AD Claims integration and HTML email content & presentation	

## Tasks
- [ ] Prototype is shared with Education Service team
- [ ] HTML email is shared with Education Service team 
- [ ] Any questions from EDU are answered / resolved
- [ ] If necessary, new tickets will be created to handle updates

**Comment by amyknox** [comment]
@watersemma - did we demo this for EDU last week? If not we can mark it OBE.
