### ISSUE TITLE
EDU Forms / VET TEC:  Prototype Update	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20574]
## Definition of Done
Prototype for VET TEC Service History page has been updated to include EDU-Approved content	

#Assumptions
- A reusable VET TEC prototype exists in invision

## Tasks
- [x] Prototype is updated
- [x] UX team reviews & approves
- [ ] UXBA reviews & approves
- [ ] Respond to any questions"

**Comment by amyknox** [comment]
@watersemma - The VET TEC application has updates in 2 spots to reflect that service members with <180 days 'til release from active duty are eligible to apply for the program.  Content has been approved by VSP and is ready to be added to the prototype. 

Prototype updates are needed 
1. On the [intro screen in section 1. Prepare](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/vettec-0994/design/0994-content.md#1prepare) 
2. On the [Military service page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/vettec-0994/design/0994-content.md#chapter-title-step-2-of-7-military-service)

You can find the [most recent VET TEC prototype here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/vettec-0994/design/va-form-0994.sketch)

**Comment by watersemma** [comment]
Uploaded updated VET TEC prototype. https://bahdigital.invisionapp.com/d/main#/projects/prototypes/14222516
