### ISSUE TITLE
Define phase 1 content patterns for tool landing pages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20588]
## User story

As a content writer working on the first phase of our tool landing pages refresh, I need to know content patterns to follow for these pages.

## Issue Description

Define content patterns to inform phase 1 tool landing page refresh updates. We'll then update these elements across all tool landing pages, starting with health tool landing pages.

[WIP doc for defining these content patterns](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/tool-landing-pages.md)

---
## Tasks
- [x] Define phase 1 content patterns and document in GitHub. In this doc, we'll also include rationale and shifts in approach in order to document history of content evolution. Bring to IA/content meeting for discussion/awareness. Consider whether we want to define some of these patterns (ie, intros) elsewhere (ie, style guide) or wait until further testing and evolution.

## Acceptance Criteria
- [x] Patterns defined in GitHub

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
For awareness @mpeterz. I'd love to bring this to our content/IA meeting this week on 3/10 for a check-in. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Complete and closing.
