### ISSUE TITLE
IRIS Phase I Research Plan

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#20580]
## Issue Description
_VEO is working on a new "ask a question" portal to replace IRIS. Our VA team has some oversight of this project, though we do not own the development of it. Our current role is to provide expertise in UX and general VA.gov standards. This story will address the Phase 1 Research Plan_

---
## Tasks
- [x] _Draft Initial phase I research plan for IRIS_
- [x] _Work with IRIS team to complete the research plan_
- [x] _Use the research plan to coordinate test user recruitment_

## Acceptance Criteria
- [x] _IRIS phase 1 research plan is complete, used to for starting test user recruitment and planning usability testing_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
This ticket can be closed, but last time I did that I screwed up an epic.
