### ISSUE TITLE
Janssen (J&J)  COVID-19 vaccine content updates (week of 2.28.21)

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20591]
## User story

As a Veteran or caregiver, I need to have the latest information about COVID-19 vaccines at VA and particularly the new Janssen (J&J) vaccine.

## EPIC

- [ ] Update English Veteran-facing COVID-19 content across:
  - [x] [VA.gov vaccine mini hub](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20592)
   - [x] [VA.gov chatbot](**https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20593**)
  - [ ] [Vettext scheduling](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20595)
  - [ ] [Facility slotted content messaging](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21399)
  - [ ] VAOS scheduling mockups

- [x] [Provide Spanish and Tagalog versions of updated VA.gov vaccine mini hub content as quickly as possible after English updates published.](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20596)

- [x] [Send out Keep me informed email on the new vaccine](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20597)

Content audit of all related content products here: https://github.com/department-of-veterans-affairs/digitalservice/blob/master/product-lines/health/covid-19/vaccine/content-planning/janssen-approval.md

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - can we close this? (Doing some major board clean-up :)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. This is primarily a sitewide content epic so I'll just ask @RLHecht to confirm/check off the tasks first. Thanks!

**Comment by RLHecht** [comment]
I believe this is OK to close but I'm not exactly sure what the Vettext or Slotted Facility Content work is and if that's complete. @DanielleThierryUSDSVA those two tickets are still open but I don't know if there was more work to do.
