### ISSUE TITLE
Create debt Resources & Support articles to support migration

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20590]
## User story
As a Veteran or dependent with VA debt, I need to know how to manage my debt effectively.

## Issue Description
Create 3 Resources & Support articles to migrate content from Debt Management Center website:

- VA debt management questions
- Financial status report questions
- VA debt waiver questions

Need to use COPE FAQs here. Some of the single Q&As will be repurposed in more than 1 of these articles, as standalone Q&As, and on the main Manage your VA debt landing page (note: they'll be rewritten there for now until we have COPE capability across all site sections).
 
---
## Tasks
- [x] Audit content
- [x] Write articles
- [x] Package articles and send to DMC SMEs for review

## Acceptance Criteria
- [ ] Articles sent for SME review
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Previews of pages:

- VA debt management FAQs: http://preview-prod.vfs.va.gov/preview?nodeId=15594 
- Submitting a Financial Status Report (VA Form 5655): http://preview-prod.vfs.va.gov/preview?nodeId=15717
- VA debt waiver FAQs: http://preview-prod.vfs.va.gov/preview?nodeId=15606

Review package sent to SMEs on 2.03.21:
[VA debt management for content concurrence_02.03.21](https://app.zenhub.com/files/133843125/de144975-973f-4920-a3e2-a6fd4d89c3c5/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. Just tagging you for awareness on these tickets. Thanks!
