### ISSUE TITLE
Janssen (J&J) vaccine updates: Chatbot

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20593]
## Issue Description

Update chabot to reflect latest available vaccine (Janssen/J&J). This work begins once we have approved content from the vaccine mini-hub.

## Related documents

- [Content audit for Janssen updates](https://github.com/department-of-veterans-affairs/digitalservice/blob/master/product-lines/health/covid-19/vaccine/content-planning/janssen-approval.md)
- Base updates on approved content from vaccine mini-hub

---
## Tasks
- [x] Provide direction on which content needs to be updated (Danielle)
- [x] Start new branch/PR and update content in GH (Selina) 
- [x] Review & approve content (Randi)
- [x] Hand off to dev team (Selina)
- [ ] Review content in staging when notified by dev team (Selina/Randi)

## Acceptance Criteria
- [ ] Content updated in chatbot
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@lunascoop @RLHecht Here's the list of changes we'll need to make to the chatbot. You can use approved content from the mini-hub. If you have any questions, or if you see anything I've missed, let me know! Thank you!!

## Chatbot

- [ ] "Can I choose which authorized COVID-19 vaccine I get?": Will need to update to incorporate Janssen.
- [ ] "How many doses will I need to take?" Will I need a booster dose?": Will need to rework to account for single-dose Janssen vaccine.
- [ ] "Do I need to get both vaccine doses at the same VA facility?": Will need to reframe question (ie, "If I get a vaccine that requires 2 doses, do I need to get both doses at the same VA facility?"). Need to revise answer to specifically mention 2 of 3 of the authorized vaccines (not "both").
- [ ] "Is it safe for me to get a COVID-19 vaccine?": We'll need to incorporate any relevant info from the Janssen FDA fact sheet and add a link to that fact sheet.
- [ ] "Should I get a COVID-19 vaccine even if I've already had COVID-19?": Will need to update to incorporate Janssen info.

**Comment by lunascoop** [comment]
@RLHecht Pull request created for you to review updates to questions#:
72: Can I choose which authorized COVID-19 vaccine I get?
73: How many doses will I need to take? Will I need a booster dose?
74: If the vaccine I get requires 2 doses, do I need to get both vaccine doses at the same VA facility?
75: How do I know if it's safe for me personally to get a COVID-19 vaccine?
77: Should I get a COVID-19 vaccine even if I've already had COVID-19?
54: If I receive VA disability or pension benefits, will I automatically get my second stimulus check?
41: What if I can’t pay my existing VA debt?
43: Do I have to pay my VA copays at this time?
17: How do I refill my prescription?
20: I don't have symptoms, but I feel anxious and overwhelmed. What can I do?

**Comment by RLHecht** [comment]
@lunascoop I just approved the PR after making a few copy tweaks

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lunascoop I think this is launched and can be closed, so I'm closing ticket. Thanks!
