### ISSUE TITLE
Janssen (J&J) COVID-19 vaccine updates: Facility slotted messaging content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20598]
## Issue Description
Update related text messages to reflect latest available vaccine (Janssen/J&J)

## Related documents

- [Content audit for Janssen updates](https://github.com/department-of-veterans-affairs/digitalservice/blob/master/product-lines/health/covid-19/vaccine/content-planning/janssen-approval.md)

---
## Tasks
- [ ] Update content in word doc (highlight updates) (Danielle)
- [ ] Review and finalize content doc (Danielle, Lauren - Patrick, Shane too as part of text message ticket)
- [ ] Send to Dr. Kim's office for review (Lauren)
- [ ] Incorporate Dr. K's changes (Danielle)
- [ ] Send to JTF for review (Lauren)
- [ ] Incorporate JTF's changes (Danielle)
- [ ] Share updated messaging package with Melodee/Kristan for posting on Sharepoint (Danielle)

## Acceptance Criteria
- [ ] KMI text message/slotted content package for facilities updated on Sharepoint

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Duplicate ticket. Closing.
