### ISSUE TITLE
Janssen (J&J) vaccine updates phase 1: Vaccine mini-hub

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20592]
## Issue Description

Update vaccine mini-hub to reflect latest available vaccine (Janssen/J&J)

## Related documents

- [Content audit for Janssen updates](https://github.com/department-of-veterans-affairs/digitalservice/blob/master/product-lines/health/covid-19/vaccine/content-planning/janssen-approval.md)
- [Content document with changes](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EZM_FuP2aVBEglTMYGJKnEQBVsOiVtdRbDzGw_vt3gU2OQ?e=Yxl051) - OLD VERSION
- [Dr. Kim approved version]( https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EUfDqgyIvQ5Mq4pxuBmLLy4BdCLOvrPiy-jqugJ7D5OpUA?e=eYZrNZ
)
- [FINAL JTF-approved version](https://app.zenhub.com/files/133843125/f375f22f-fba1-4350-831b-ad2910f1c236/download)
---
## Tasks
- [x] Update content in word doc (highlight updates) (Danielle)
- [x] Send to Dr. Kim's office for review (Lauren)
- [x] Incorporate Dr. K's changes (Danielle)
- [x] Send to JTF for review (Lauren)
- [x] Incorporate JTF's changes (Danielle) 
- [x] Update content in Drupal (Selina)
- [x] Review and publish content (Randi/Danielle)
- [x] Trigger translation flow (Randi)
- [x] Trigger chatbot updates (Selina)

## Acceptance Criteria
- [x] Content updated in mini-hub
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
LGTM. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@lalexanderson-dsva @batemapf I have some final touches (like links) and one additional question to add here, but feel free to start looking at the mini-hub: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EZM_FuP2aVBEglTMYGJKnEQBVsOiVtdRbDzGw_vt3gU2OQ?e=Yxl051

**Comment by DanielleThierryUSDSVA** [comment]
Complete and @lalexanderson-dsva sending to Dr. Kim.

**Comment by DanielleThierryUSDSVA** [comment]
@lunascoop Here's the doc to use to incorporate the changes. Changes are highlighted.

- [FINAL JTF-approved version](https://app.zenhub.com/files/133843125/f375f22f-fba1-4350-831b-ad2910f1c236/download)

**Comment by lunascoop** [comment]
@RLHecht these updates are ready for review (http://preview-prod.vfs.va.gov/preview?nodeId=11463). A few notes.

- Changed menu weight on Drupal page
- I added "FDA" before links to the fact sheet
- Changed formatting of "Janssen (Johnson & Johnson) COVID-19 " to "Janssen COVID-19 vaccine"
- Only linked the first Janssen fact sheet (per the comment in the doc) and am waiting to link the second when the multiple languages fact sheets are available
- Removed copy mentioned here: https://dsva.slack.com/archives/G01H87UCK7S/p1614715531043800

**Comment by RLHecht** [comment]
This page was published and the new content was sent to the translators on 3/2.
