### ISSUE TITLE
Janssen (J&J) vaccine approval: KMI email #6

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20597]
## Issue Description
Create and send out KMI email #6. Topic: Janssen (J&J) vaccine approval. We're aiming for week of 2.29.21. Team can track status of progress through tasks below.

## Related documents

[WIP content doc](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EVzhvce6nYtCqFeXqrNU9EMBJMsp9-DDsEPM2yFm_WDJhA?e=czUDcw) - OLD VERSION
[Dr. Kim approved version]( https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EYVXJAE6rkFOnNAWAVa5elABBKFR2J0mGTDIw_bS1BbGPg?e=WJSQiZ)

[KMI email #6 Janssen vaccine approved FINAL 03.02.21](https://app.zenhub.com/files/133843125/9c82ae61-ab1d-4ff6-8dcc-986397ac40f9/download)

---
## Tasks
- [x] Create email content (Danielle)
- [x] Review and finalize email content (Danielle, Lauren, Patrick, Chante)
- [x] Begin building out template with draft content (Notifications team)
- [x] Send email content to Dr. Kim's team (Lauren)
- [x] Incorporate Dr. Kim's feedback and highlight any updates for notifications team (Danielle)
- [x] Send email content to JTF (Lauren)
- [x] Incorporate JTF feedback and highlight any updates for notifications team (Danielle)
- [x] Finalize email template and send to team for review (Notifications team)
- [x] Approval email (Danielle, Lauren, Patrick, Shane)

## Acceptance Criteria
- [x] Approved email is ready to send out
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@lalexanderson-dsva @batemapf  Draft content based on Janssen FDA fact sheet and general VA messaging here: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EVzhvce6nYtCqFeXqrNU9EMBJMsp9-DDsEPM2yFm_WDJhA?e=czUDcw

You'll see I have a few notes/questions in comments. And would also love any other thoughts as well. 

I didn't get into the different storage and handling requirements because I didn't think that was what was most important from a Veteran perspective and the email is already long. But if you think we might want to add something around that, let me know. 

Thanks!

**Comment by lalexanderson-dsva** [comment]
THe KMI email looks good ot me. The timing question I will defer to Dr. Kim.

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA just letting you know I saw the ticket and we are intaking to begin drafting the template. Thanks for tagging me cc @toddstanich

**Comment by DanielleThierryUSDSVA** [comment]
Awesome - thanks, @miabecker!

**Comment by clantosswett** [comment]
@DanielleThierryUSDSVA email looks good to me. Thanks!

**Comment by batemapf** [comment]
@DanielleSoCompany added two small comments. Otherwise looks great!

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA Forwarding you the email now for your review FYI

**Comment by DanielleThierryUSDSVA** [comment]
@miabecker Final Word doc (with highlights to mark changes from original) attached. Note that we kept once instance of "(Johnson & Johnson)" as a signal for people who may recognize that name. Thanks!

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA we updated the content based off of what you attached here and I just forwarded you an email from prod. Please reply to that email if you have any feedback. Thanks! @toddstanich
