### ISSUE TITLE
Add copay pause alert to all copay-related pages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20600]
## Issue Description

Add this alert:
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/219af70d-2633-4cd7-952a-49f6e25fc71b)

To these pages:

- 2021 VA health care copay rates: Node 703
- Pay your VA copay bill: Node 704
- Dispute your VA copay charges: Node 705
- Request VA financial hardship assistance: Node 706

---
## Tasks
- [x] Create alert (Danielle)
- [x] Add alert to pages (Danielle)
- [x] Review alert and pages and publish (Randi)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Could you give this alert and these pages a review and publish them today, 3/1? Thank you!

**Comment by RLHecht** [comment]
These pages have been published. @DanielleThierryUSDSVA is emailing to find out if we should change "pharmacy" to "prescriptions" or "medications" but publishing as is for now and will change if necessary.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA is this ticket OK to close or are we still seeing if we can change some of the text?

**Comment by RLHecht** [comment]
Closing this ticket as these alerts have since been updated around specific dates.
