### ISSUE TITLE
Create Ch33 Test User with Power of Attorney Attribute Set to True

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#20604]
In order to test a user with education entitlements and power of attorney associated with another user, the BAH team needs a new test user created in the integrated lower environment that has the power of attorney attribute set to new.

# Tasks
- [x] Reach out to POC with CH33 and request the creation of a new user with the POA attribute set to true
- [x] Record the new test user in the [appropriate test user table](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-edu.md)
- [x] Notify the BAH team that the test user is ready for use in **staging**

**Comment by pjhill** [comment]
As of 2/18 the Ch33 POC are having issues creating a test user with the POA attribute. They are investigating the issue on their side and will reach out when they have an idea about how to create this test data.

**Comment by pjhill** [comment]
Worked with CH33 team to create a new user (+228) which is stored [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-edu.md).

This user should have the Power of Attorney attribute set to _true_ with the code **074** associated.

**Comment by pjhill** [comment]
Clarifying issue with the test user with BAH.

**Comment by pjhill** [comment]
The end point that we are attempting to use in `vets-api` does not appear to support the desired behavior. BAH is working with VSP BE Tools Team to discover a different end point.

**Comment by pjhill** [comment]
The test user we created should work once the BAH team is able to use the correct end point in vets-api. If it doesn't we will re-open this ticket.
