### ISSUE TITLE
COVID-19 vaccine page translation 3.1.21

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20602]
## Issue Description
Build Spanish version of COVID-19 vaccine page.

## Relevant info and documents

[11840_Covid19-Vaccine_Spanish Final](https://app.zenhub.com/files/133843125/2f452b52-94b1-4c24-af1d-64c72a89ca93/download)
[11841_Covid19-Vaccine_Tagalog](https://app.zenhub.com/files/133843125/ef246527-5d0d-4767-9dc8-37017d480e7f/download)

URL for Spanish page will be: www.va.gov/health-care/covid-19-vaccine-esp/

@SKasimow Can you please reach out to @mnorthuis about what the URL for the Tagalog pages should be? Thank you!

---
## Tasks
- [x] Build Spanish vaccine page (Selina)
- [x] Review and publish Spanish page (Randi)
- [x] Build Tagalog vaccine page (Selina)
- [x] Review and publish Tagalog vaccine page (Randi)
- [x] Add link to English version page for Spanish and Tagalog pages
- [x] Add link to Spanish page for English version
- [x] Add link to Tagalog page for English version

## Acceptance Criteria
- [x] Spanish and Tagalog vaccine pages are live on the site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @RLHecht the Spanish translation is ready for review (http://preview-prod.vfs.va.gov/preview?nodeId=16359). A couple of things:

- I haven't added the information callout yet. I noticed that it's not included on the updated version of the English page (in draft mode). I left a question for @DanielleThierryUSDSVA  via Slack if it should be added. https://dsva.slack.com/archives/G01H87UCK7S/p1614617077007000
- The translation doc doesn't include translations for the last link teaser. I used Google translate for now.

**Comment by lunascoop** [comment]
Hi @RLHecht The tagalog page is ready for review (minus I'm having trouble linking to the QA section of the page). Here's a screenshot w/ the link highlighted. I'm having the same issue on the Spanish page.
<img width="929" alt="Screen Shot 2021-03-02 at 11 01 28 AM" src="https://user-images.githubusercontent.com/42546515/109681303-555f3a80-7b4b-11eb-9c06-1844af06ce9d.png">

Tagalog: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by RLHecht** [comment]
Tagalog page is now published

**Comment by RLHecht** [comment]
@lunascoop Here are the two word docs from the VHA translation team with changes that need to be made to both Tagalog and Spanish versions. Once we publish we will send back to them for another review of the live content. [https://app.zenhub.com/files/133843125/4bc99d69-5b20-48e6-b806-f1811a35dd62/download](https://app.zenhub.com/files/133843125/4bc99d69-5b20-48e6-b806-f1811a35dd62/download)[https://app.zenhub.com/files/133843125/7ea48b79-5291-40e4-ab1c-54f9c46de638/download](https://app.zenhub.com/files/133843125/7ea48b79-5291-40e4-ab1c-54f9c46de638/download)

**Comment by lunascoop** [comment]
@RLHecht these updates are ready for review.
Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
@lunascoop We just got back translation updates for both Tagalog and Spanish around the Janssen vaccine changes as well as another update. Can you please input them and then I can review? The one that is just the short paragraph is for the section "Where we'll offer vaccines." Right now we only have the Tagalog but I will get you the Spanish and attach that as well. Thank you!
[https://app.zenhub.com/files/133843125/f3143835-9cb4-4c74-a1b0-11e24ddba9eb/download](https://app.zenhub.com/files/133843125/f3143835-9cb4-4c74-a1b0-11e24ddba9eb/download)
[https://app.zenhub.com/files/133843125/b86b73fc-94a6-45af-bb13-03f4f10ba18e/download](https://app.zenhub.com/files/133843125/b86b73fc-94a6-45af-bb13-03f4f10ba18e/download)
https://app.zenhub.com/files/133843125/db30ce08-c04a-4702-acde-6e6b7c78804e/download](https://app.zenhub.com/files/133843125/db30ce08-c04a-4702-acde-6e6b7c78804e/download)

**Comment by lunascoop** [comment]
@RLHecht the Tagalog version is ready for review. If it helps, I've included an updated draft of the longer translation doc which includes my comments (parts I removed per our call and change I added). I also made the copy text for the Moderna, Pfizer and Janssen fact sheet links consistent.

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

[f3143835-9cb4-4c74-a1b0-11e24ddba9 eb-Selina Comments.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6117938/f3143835-9cb4-4c74-a1b0-11e24ddba9.eb-Selina.Comments.docx)

**Comment by RLHecht** [comment]
@lunascoop These changes all look good. I made a few copy edits (added a period, removed an extra link space). I'll wait to hit publish until we have the Spanish one ready so they can go at the same time.

**Comment by lunascoop** [comment]
@RLHecht The Spanish version is ready for review (minus the "Where we'll offer vaccines" translation which I'm waiting on). I've also included some notes in the doc if it helps.
[11936_Janssen-vaccine-pg-updates_SpanishSelina Notes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6118718/11936_Janssen-vaccine-pg-updates_SpanishSelina.Notes.docx)

Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

Also, added change to:
Will I have side effects after I get a COVID-19 vaccine? 
¿Tendré efectos secundarios después de recibir la vacuna contra COVID-19? Changed "2" to "3" in sentence before bullet points. Added link to Janssen fact sheet

**Comment by RLHecht** [comment]
Both pages are now published with the translated changes around the Janssen vaccine. We are still waiting on one more piece of translation for the Spanish page around the section "Where we'll offer vaccines." Following up with Chad today.

**Comment by RLHecht** [comment]
@lunascoop Here is the final translated content we were waiting for around the section "Where we'll offer vaccines." Could you please put this into the Spanish vaccine page? I can then review and publish.[https://app.zenhub.com/files/133843125/410bf7df-80be-4250-abf7-a1f5b9c88051/download](https://app.zenhub.com/files/133843125/410bf7df-80be-4250-abf7-a1f5b9c88051/download)

**Comment by lunascoop** [comment]
@RLHecht the content for "Where we'll offer vaccines" has been added and the page is ready for review.
Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
@lunascoop This text was reviewed and page published. I'll close this ticket once it's validated after today's deploy.

**Comment by RLHecht** [comment]
Validated on live site and final text for updated Spanish content sent to Mateo for review. Closing ticket. I'll reopen if he comes back with any changes needed.

**Comment by RLHecht** [comment]
Mateo came back with direction to cap Veteranos in 2 instances in that new text. I corrected the page and republished.

**Comment by RLHecht** [comment]
@lunascoop Here are docs of the VHA translation team's final reviews. There is only one change in the Spanish one and a few in Tagalog, so I'm reopening the issue. 
[Spanish translation Janssen updates for review.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6172068/Spanish.translation.Janssen.updates.for.review.docx)
[Tagalog translation Janssen updates for review.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6172069/Tagalog.translation.Janssen.updates.for.review.docx)

**Comment by lunascoop** [comment]
@RLHecht 
This page is ready for review. 
Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
I also updated instances where the Janssen fact sheet (Tagalog) link was appropriate.

**Comment by RLHecht** [comment]
Thanks @lunascoop There were a few more tweaks I made and published the page.

**Comment by RLHecht** [comment]
Work complete on this. Closing ticket.
