### ISSUE TITLE
Create Internal Guide To Manual Test User Account Creation

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#20615]
## Issue Description
The TUD MVP will not include CRUD functionality; users wishing to create new test accounts will have to contact various IDPs and VA service providers to have them manually add new accounts. In order to streamline this process and make it as easy as possible for users to request new accounts a guide detailing the process should be created. In addition to a [guide and documentation for end users of the TUD app](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/20114), an internal guide for testing-team members to help them navigate the process of requesting new test accounts from VA.gov service providers should be created.

---
## Tasks
- [x] An account creation guide is added to the va.gov-team-sensitive repository as a markdown file.
- [x] The guide will provide a summary of the current status of test user account creation capabilities
- [x] The guide will provide specific documentation as to how to request the creation of new test user data from each of the primary VA.gov service providers (MPI, ID.me, EVSS/DSLogon)
- [x] The guide will provide contact information for PoCs at those service providers for the purposes of requesting new test user accounts
- [x] The guide will include instructions for updating vets-api-mocked-data with new test user information
- [ ] Work with Aubrey to familiarize him with test account creation requirements

## Acceptance Criteria
- [ ] Testing-team members using the guide will be able to request the creation of new test user accounts with the third-party service information that they require.
- [ ] testing-team approval (from Peter Hill)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
