### ISSUE TITLE
Typo fixes for VCL modal from Sitewide content

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#20610]
### Engineering support for:
Content fixes that can't be addressed in drupal.
- Insert a space before the TTY number
- In the line about calling by phone, change "press" to "select" for accessibility reasons (because of physical disabilities, not all Veterans can press a button, so they would be selecting instead)

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @RLHecht and @brianalloyd. If your request includes engineering support, also tag @ncksllvn and @kelsonic.
- [x] If noted in the guidance below, please schedule any relevant meetings.

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

![image.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/c4719f00-ef8e-4a4f-a829-e71a9a9a9e19)

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Frontend engineering support 

- [ ] **Other**
There are just these 2 small content fixes needed.
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

ASAP

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Sitewide content 
- DEPO product owner: Beth Potts and Danielle Thierry
- Product manager: n/a
- Designer: n/a
- FE engineer: n/a
- Product/team Slack channel: va-sitewide-content

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/16412

**Comment by kelsonic** [comment]
Bumping estimate from a 3 to a 2

**Comment by brianalloyd** [comment]
This update has been deployed, validated and closing ticket in support.
