### ISSUE TITLE
Implement BE for Pension Questions on 674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20618]
## Background
Now that the FE has installed the pension questions for a student attending and leaving school, the backend needs to add those values into the payload to BGS.

Note: FE also added this for reporting the marriage of a minor child, so BE needs to account for that workflow as well.

## Tasks
- [x] Include the values as part of the payload to BGS

## Acceptance Criteria
- [x] The appropriate values for a student attending school are passed in 
- [x] The appropriate values for a student leaving school are passed in 
- [x] The appropriate values for a minor child getting married are passed in
- [x] Test specs have been updated
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
*Upped the estimate from 2 to 3 because there is an additional workflow that the income question was added to as well (minor child getting married).

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6102
