### ISSUE TITLE
Address Table Component Reflow at 320px Breakpoint

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2061]
## Story
As a member of a development team working within the VA.gov website, I need a way to create tables that reflow to accommodate the 320px grid-breakpoint (mobile).

## Consideration
- Should we consider reflowing table at 481px?

## Tasks
- Review the [VA design system](https://design.va.gov/components/tables) to see if there is any information to address table reflow--particularly at 481px and 320px breakpoints.
- Define parameters of how narrow a table needs to be (is 481px the lower limit for scaling?). If the limit is something like 481px, does that change how we approach the display versus 320px or something?
- Review existing VA.gov screens at mobile resolutions; determine table and/or component behaviors on small screens.

## Definition of Done
- [x] Determine mobile-first approach to screen layouts.
- [x] Develop/style tables that will adequately display tabular info on small screens.
- [ ] Feedback received from Global UX
- [ ] Validate with Emily (or reach out to Kara to see if there is someone else)
