### ISSUE TITLE
[FE] VAOS Text and Link

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#20624]
## User Story

As a veteran, 
I should be able to see my appointments
to understand my appointments

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19517#issuecomment-788056702)

## Description

Add sentence referencing VAOS.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Add senetance to footer of list page. 
- [ ] Update bolding

## Acceptance Criteria

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
This is staging, @kristenmcconnell  can you take a look?

**Comment by kristenmcconnell** [comment]
As I mentioned in stand-up, I realized that the text we settled on works on the Questionnaire List, but not the rest of the pages. Therefore, I would like to change the "should be on this list" to "should be listed." I think that fixes our problem. The full revised text is below:

Can't find an appointment that you think should be listed? You may not have a questionnaire for that appointment. Go to the list of all your VA health appointments.

**Comment by mdewey** [comment]
@kristenmcconnell  This is in staging, can you take a look?

**Comment by kristenmcconnell** [comment]
@mdewey It looks good to me.
