### ISSUE TITLE
[DISCOVERY] PPMS sort order

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20621]
## Issue Description
We need to confirm if drive time impacts the sort order of query results

---
## Tasks
- [ ] Run query for popular community car provider search at various times throughout the day
- [ ] Compare sort order for Swagger query results 

## Acceptance Criteria
- [ ] Documentation on any sort order discrepancies for identical query
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
