### ISSUE TITLE
Create On this page Web component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#20620]
## Issue Description
Build On this page web component. 

---
## Tasks
- [ ] Development of on this page component
- [ ] Testing - basic accessibility testing for staging review prep
- [ ] Put on staging for staging review

## Acceptance Criteria
- [ ] Accessible on staging for testing

---
