### ISSUE TITLE
VA.gov Duplicate User/Veteran ID Causes

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#20636]
## Issue Description
_Numerous Veterans are experiencing and issue where they have duplicate VA.gov IDs without knowing it. When they attempt to login after this issue has been created, they cannot login. The root causes are not entirely known and the route to fix when this happens is not entirely efficient. Our goal with this issue is to document what is know and ideate ways to fix the issue to inform future plans._

---
## Tasks
- [x] Document known causes for duplicate Veteran ID on VA.gov
- [x] Document current resolution process
- [x] Document clearly what the problems are
- [x] Document ideas for solving and discuss with VA lead(s)

## Acceptance Criteria
- [x] The duplicate VA.gov Veteran ID causes, current resolution, and existing problems will be clearly documented to facilitate a conversation regarding solutions.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
@jwoodman5 Below is the email chain between Chante and I discussing this issue.  Please advise if you are unable to view the email.


[https://mail.google.com/mail/u/0/#inbox/WhctKJWQhmSxSkJtfNdGfNCJqHXFgFtfSDQKlXpwQrVWmXksDnSLtzjNWSRftDtHMlvWCFg](url)

**Comment by jwoodman5** [comment]
@Kimberley2019 I am unable to view, but we can chat about this later today in our 1:1. Thanks.

**Comment by jwoodman5** [comment]
When we receive login issues which seem to be related to the user having duplicate IDs, we generally reply to the user (in the issue) with the following message:

"This may be related to your MyHealtheVet information

You can call 877-327-0022 Monday - Friday, 8:00 a.m.- 8:00 p.m. ET. Tell the representative that you tried to sign in to VA.gov, but you’re having trouble because we have more than one ID for you, but you don’t know which kind. Ask if they can look into whether you have more than one MyHealtheVet account or more than one ICN (that’s a fancy abbreviation for an ID that the VA health system uses for you).

 
This may be related to Department of Defense (DoD) information

If the MyHealtheVet folks don’t see any duplicate IDs for you, this might be a problem with the VA having more than one DoD ID for you. You can fill out this form and tell them you think you have multiple IDs associated with your identity.  https://www.accesstocare.va.gov/sign-in-help"

**Comment by jwoodman5** [comment]
Example issues:

- (04291442) Error code E4200-A6A48DAE289A Duplicate accounts Veteran is trying to log and verify info but not allowing to move any further error message code keeps showing up/too many attempts locked out Please reset account to verify email on file/email was reset yesterday allowed to upload Drivers license and then tried go back in but couldn't get passed the verification again/no access to benefits or profile to change info or get benefits letter

- (04259833) Verified PII. Vet is not able to get on VA.gov using her DS log on. It said she has 2 DOD logons. She contacted DEERS and they said she does not have another logon. It must be issue with VA.gov.

**Comment by jwoodman5** [comment]
This is now owned by EVSS who has an established process and who is handling/coordinating all duplicate records issues. Closing.
