### ISSUE TITLE
Minor content update on how to apply for VA health care page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20645]
## Issue Description
Stakeholder Melissa Rebstock reached out with a small content change that needs to be made on the [how to apply for VA health care](https://www.va.gov/health-care/how-to-apply/) page. 

In the first bullet of the eligibility section, we need to change "Your most recent tax return" to "Proof of gross household income." We will also need to add a plain language definition for "gross income." 

This change should be shown to the stakeholder before publishing. 

## Tasks
- [x] Update content with plain language
- [x] Send change to stakeholder
- [x] Review and publish

## Acceptance Criteria
- [x] Content change is live on the site

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I made this change and added a plain language definition. Could you please take a look and tell me if it works? The preview link is preview-prod.vfs.va.gov/preview?nodeId=35

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @RLHecht! I played around with this some more. I think since it's more about the _documents_ you need, we can focus the actual bullet on documents. And then I added an "additional information" component just beneath the featured content for "What is gross household income?" so we can add a more comprehensive definition without  making that on-page text too long.

Let me know what you think!

I also made some other tweaks to the page while I was on it. Let me know what you think of those as well.

Also, before I forget, once we have this all okay'd with our SMEs, we'll want to let Alayna and the 10-10ez team know that they should update "Most recent tax return" on the application intro page as well.

I have other recommendations for that page so if I can get to those in time, we can send together. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ala-yna @mlighdc. We'd received a request to update the bullet for "your most recent tax returns" to "proof of gross household income" in the **How do I prepare before I start my application?** section of the health care how to apply page.

We'd started working to offer a plain language definition of "gross household income" and the associated documents. However, in looking at the screens in the 10-10EZ, I think we should instead plain language it further, add a bullet around expenses, and include a note that you don't _have_ to provide this info but that it's needed if you don't qualify based on other factors.

Can you review the screenshot below and let us know if you think this works? If yes, we can take back to our health care eligibility SMEs. And then we'd also want to ask your team to update the same bullet on the 10-10EZ intro page. Thank you!

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/f1e1db48-33d2-402a-b601-59ea52c4cc27)

**Comment by mlighdc** [comment]
@DanielleThierryUSDSVA funny, we just had a conversation regarding this today. Under info you need, can we also add spouse because they will need SSN information for their spouse. Overall, I think it is fine. FYI - HEC/Healthcare Enrollment would like to make changes to the flow so they can increase the submission rate and reduce the backend work they have to verify income. They are thinking they would like to make income information required in the future but I would not hold anything up for this minor change.

@ala-yna can you take a look and let Danielle know if you see any issues. Also, can you include Danielle on the conversation about the 10-10EZ later this week? Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @mlighdc! We'll add spouse to SSN and share this with the HEC folks for their feedback. And thanks so much for including me in the 10-10EZ conversation. I'm mostly focused on a USDS research discovery sprint this week and next, but will definitely try to be there if I can...if not, will follow up. I'd love to talk about the content on the intro page (which I think we can simplify a lot) and happy to help with any and all content in the application. Thanks!

**Comment by RLHecht** [comment]
work complete. closing ticket.
