### ISSUE TITLE
526 Claims Failure Submission Notification 

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#20650]
## Issue Description
Look into ways to email Veterans if this Sidekiq jobs fail. HCA is an example that I believe already does this. (@f1337 can help you track down more specifics if needed).

**The VA notify team already sends an email when a submission succeeds. It seems like it would be medium effort and high benefit to the veteran if we also email them if/when their submission fails to submit after the final attempt. Related to this[ issue.](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/128)

**
## Tasks
- [ ] Figure out how to email Veteran in the event of failure.

## Acceptance Criteria
- [ ] Documented solution
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
I think we could just reach out in the #va-notify email channel. 

We already have code that makes a call to va notify when a job is complete and successful.    It passes an [email template id](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/form526_confirmation_email_job.rb#L17).  I bet we could use that same code to send a different email template on failure if we worked with VA notify to set up a new email template.

**Comment by vhenry07** [comment]
Stakeholders are making final decision, but looks like this will be a go to implement. New ticket will be created for implementation.
