### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Alaska health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20667]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Alaska healthcare system Legacy Site](https://www.alaska.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-20 Playbook locations](https://drive.google.com/drive/folders/1vR_PXATNS0XXiSifNrYkZCMNB29L7alD)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Confirm all Facilities Match from Story, Legacy Site, and VAST spreadsheet
**Facilities**
- [x] 463GC	Mat-Su VA Clinic
- [x] 463	Anchorage VA Medical Center
- [x] 463GA	Fairbanks VA Clinic
- [x] 463GB	Kenai VA Clinic
- [x] 463GE	Juneau VA Clinic
- [x] 463GD     Homer VA Clinic
- [x] 463QA     Elmendorf-Richardson VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
Added the following facilities to the story which were on VAST spreadsheet and checked; (1) 463GD Homer VA Clinic and (2) 463QA Elmendorf-Richardson VA Clinic

**Comment by bcastoe** [comment]
Task #20667 - Create new Health Services "LIST, PLAYBOOK" for VA Alaska Valley health care [BA] - is Complete and moved to Validate.
