### ISSUE TITLE
TUD: Bug - Name formatted incorrectly

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20666]
## Issue Description
As a user of the TUD app, I would like to see a consistent formatted name pattern in the dropdown detail view so that I can better understand which user I am using.

Has middle name => `John M. Doe`
Has no middle name => `John Doe`
---
## Tasks
- [x] Rewrite the `normalizeName` function to return consistent results

## Acceptance Criteria
- [x] A name displayed in the dropdown detailed view is displays as required.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
