### ISSUE TITLE
[Cheetah MVP] Homepage CTA radio options

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20675]
## Issue Description
As a result of user research, we need to the make the cheetah flow CTA more discoverable.

---
## Tasks
- [ ] Update UI

- [ ] Connect Primary/Specialty Care flow

- [ ] Connect Cheetah flow

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag
- [ ] Changes are behind (homepage refresh) feature flag

- [ ] User can select only one of the appointment flows

- [ ] CONTENT - Section heading matches:
> Schedule a new appointment

- [ ] CONTENT - Option label copy matches:
> - Primary or specialty care
> - COVID-19 vaccine

- [ ] CONTENT - Default CTA label (nothing selected) copy matches:
> Choose an appointment type

- [ ] CONTENT - Actionable CTA label copy matches:
> Start scheduling

- [ ] If an appointment type is not selected, Schedule appointment CTA is not enabled

- [ ] If an appointment type is selected, Schedule appointment CTA is enabled

- [ ] Given user selects Primary and Specialty care, when user clicks Schedule appointment, Then enter standard appointment flow
- [ ] Given user selects COVID-19 vaccine, when user clicks Schedule appointment, Then enter cheetah appointment flow
- [ ] DESIGN - CTA states match the specs https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/446288321_Action_Links
- [ ] DESIGN - Designs match specs https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/446287949_VAOS-Home-Cta-States-V2
_(Note- Copy in specs is FPO)_
![Screen Shot 2021-03-02 at 10.05.54 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/ee1cc333-4be8-42d2-a332-11280b5787e9)

### Out of Scope
- Express Care CTA and flow
- Conditional descriptions

**Comment by LanceGundersen** [comment]
@laurenernest I wanted to verify this is only for project cheetah?

**Comment by laurenernest** [comment]
This won't be for the live version of the app, but we did also include in Homepage Refresh based on grooming discussions.

**Comment by laurenernest** [comment]
I'm not seeing this in Staging with the cheetah toggle on. 
@jbalboni #21545 wouldn't have affected this when using Judy, right?
![Screen Shot 2021-03-16 at 3.23.00 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/82b3d5d1-45b1-4cbb-9752-575adb023ae5)

**Comment by jbalboni** [comment]
@laurenernest I see the radio buttons on staging now, might have been a delay getting deployed.
