### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Portland health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20670]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Portland healthcare system Legacy Site](https://www.portland.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-20 Playbook locations](https://drive.google.com/drive/folders/1vR_PXATNS0XXiSifNrYkZCMNB29L7alD)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Confirm all Facilities Match from Story, Legacy Site, and VAST spreadsheet
**Facilities**
- [x] 648	Portland VA Medical Center
- [x] 648A4	Portland VA Medical Center-Vancouver
- [x] 648GA	Bend VA Clinic
- [x] 648GB	Salem VA Clinic
- [x] 648GD	North Coast VA Clinic
- [x] 648GE	Fairview VA Clinic
- [x] 648GF	Hillsboro VA Clinic
- [x] 648GG	West Linn VA Clinic
- [x] 648GH	Newport VA Clinic
- [x] 648GH01	Lincoln City Clinic
- [x] 648GI	Portland VA Clinic
- [x] 648GJ	Loren R. Kaufman VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#20670 Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Portland health care [BA] - Completed and moved to Validate
