### ISSUE TITLE
Modify Collaboration Cycle documentation to request Content "source of truth"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#20674]
## Issue Description
Often times, VFS teams will submit artifacts and/or documentation for Collaboration Cycle reviews and it is not clear to VSP and/or other content folks (ie Sitewide Content team) where to look for the correct content. Sometimes it is in Sketch or Envision files, other times it is elsewhere.

If we can ask that VFS teams specify which artifacts represent the content source of truth, then we can verify that we are reviewing the correct content for the product. In addition, designating a content source of truth will ensure developers referring to that content when building files in staging. 

If we notify teams that we need to review the correct content in our Collaboration Cycle reviews then we can encourage best practices with VFS teams in keeping their prototypes (or other source of truth for content) current.

---
## Tasks
- [x]  Update Collab Cycle documentation and issues templates to ask VFS team to specify what is their content "source of truth" in artifacts.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
hey @peggygannon  - have you started on this work yet? Please let me know :)

**Comment by peggygannon** [comment]
Hi, @shiragoodman I'll plan to start looking at this this afternoon

**Comment by peggygannon** [comment]
@shiragoodman The following Collaboration Cycle documentation has been updated to request that teams specify their content source of truth: 
- Midpoint Review touchpoint and template
- I/A Request touchpoint and template
- Staging Revie touchpoint and template

I didn't update Design Intent documentation at this time, as we need to discuss how detail content feedback should be at a Design Intent touchpoint.

**Comment by shiragoodman** [comment]
Thanks, @peggygannon. Let me review quickly and we can close this out.

**Comment by shiragoodman** [comment]
@peggygannon the changes look good to me. We'll see how VFS teams respond. I'll follow up with Beth and Danielle and let them know of this change.
