### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Puget Sound health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20673]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Puget Sound system Legacy Site](https://www.pugetsound.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-20 Playbook locations](https://drive.google.com/drive/folders/1vR_PXATNS0XXiSifNrYkZCMNB29L7alD)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Confirm all Facilities Match from Story, Legacy Site, and VAST spreadsheet
**Facilities**
- [x] 663	Seattle VA Medical Center
- [x] 663A4	American Lake VA Medical Center
- [x] 663GA	Bellevue VA Clinic
- [x] 663GF	Federal Way VA Clinic
- [x] 663GG	North Seattle VA Clinic
- [x] 663GB	Silverdale VA Clinic
- [x] 663GC	Mount Vernon VA Clinic
- [x] 663GD	South Sound VA Clinic
- [x] 663GE	North Olympic Peninsula VA Clinic
- [x] 663HK       Puget Sound VA Mobile Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
03052021 - awaiting answers to finish

**Comment by bcastoe** [comment]
03052021 (1) Changed 663GB from Bremerton VA Clinic to Silverdale VA Clinic
                 (2) Changed 663GF from Federal Way CBOC (Valor Healthcare) to Federal Way VA Clinic
                 (3) Changed 663GG from North Seattle CBOC (Valor Healthcare) to North Seattle VA Clinic
                 (4) Added vha_663HK Puget Sound VA Mobile Clinic

Task #20673 - Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Puget Sound health care [BA] - is Complete and moved to Validate.
