### ISSUE TITLE
Edit Rated Disabilities mockup to reflect CTA for Claim Status Tool

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2068]
## Story
As a member of the eBenefits Team, I want a call to action (CTA) link or panel to replace the Pending Disabilities table  of the Rated Disabilities screen, so that veterans can navigate to a comprehensive functional screen to view and manage pending claims.

## Task
- Edit current mockup to include a CTA link or panel
- Incorporate guidance provided by Content/IA and Global UX

## Definition of Done
- [x] Observe Claims Status Tool research session
- [x] Mockup has been updated
- [x] Mockup has been shared with Content/IA, and Global UX (Peggy Gannon)

## Next Steps 
- Work with FE's to implement designs

**Comment by sporeboy** [comment]
Mockups updated to reflect most current thinking. Review by Peggy Gannon pending.
