### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Wallawalla health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20681]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Wallawalla healthcare system Legacy Site](https://www.wallawalla.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-20 Playbook locations](https://drive.google.com/drive/folders/1vR_PXATNS0XXiSifNrYkZCMNB29L7alD)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Confirm all Facilities Match from Story, Legacy Site, and VAST spreadsheet
**Facilities**
- [x] 687	Jonathan M. Wainwright Memorial VA Medical Center
- [x] 687GA	Richland VA Clinic
- [x] 687GB	Lewiston VA Clinic
- [x] 687GC	La Grande VA Clinic
- [x] 687HA	Yakima VA Clinic
- [x] 687QB	Morrow County VA Clinic
- [x] 687QC	Wallowa County VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#20681 - Create new Health Services "LIST, PLAYBOOK, and STAFF PROFILES" for VA Wallawalla health care [BA] - completed and moved to  Validate.
