### ISSUE TITLE
Launch MVP triage process

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#207]
# Epic
As VA.gov/VSP, I need to ensure any problems users are experiencing are discovered and fixed expeditiously, so Veterans are not impeded from finding/applying for/managing their benefits online.

# Hypotheses
Support: robust support for each functional area will foster collaboration and ease of adoption for VFS Teams, and a continued desire to work with VSP.

Automation + Instrumentation: the incorporation of checks and balances into instrumentation and automation will empower VFS teams with the data and alerts they need to make good decisions, without relying on manual/gated bottlenecks.

# Goal
Document our triage process + responsibilities so that we can follow a more official process and accurately convey expectations - based on continuation of status quo process, with some initial MVP iteration for critical areas, and callouts for where high piority improvements are necessary and will be happening in the future.

# AC
- [ ] service blueprint accessible from GH
- [ ] Incl callout for incorporation of Tier 2/3 support
- [ ] Incl callout for automated monitoring and alerting
- [ ] provided to DSVA for review

**Comment by alexpappasoddball** [comment]
Closing this epic out as the two open tasks have been moved to a different epic inside of the Triage teams new ZenHub structure.
