### ISSUE TITLE
VSP Product Manager Checklist

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#2070]
- [ ] Team mission
- [ ] List of Platform features and services your team is responsible for
- [ ] Team charter
- [ ] OKRs for your team
- [ ] KPIs and baselines for each feature and service your team is responsible for
- [ ] Agile roadmap
- [ ] Super Epics for "Now" part of roadmap, in ZenHub fully groomed w/user stories and tasks
