### ISSUE TITLE
TUD: Copy username / password functionality

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20716]
## Issue Description
As a TUD app user, I would like the ability to copy both the **Account** and **Password** fields so that I can paste them when I log into the staging environments for

---
## Tasks
- [x] Create reusable functionality that copies content/values of a specific column field (Account or Password) in a row and copies the value to the clipboard

## Acceptance Criteria
- [x] I can click on a row's **Account** field value and copy it to the clipboard
- [x] I can click on a row's **Password** field value and copy it to the clipboard
- [x] I can see an icon that let's me know whether I can copy values to the clipboard
- [x] I have ensured good accessibility & 508c standards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
