### ISSUE TITLE
TUD: Add help content to the Find Accounts page

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20717]
## Issue Description
As a TUD app user, I would like the ability to see **help content** on the Find Accounts page, so that I can see where to get the information on issues & documentation without having to navigate back to the homepage

---
## Tasks
- [x] Implement UX research provided by Amanda that will _help_ users find what they're looking for faster
- [x] TODO tasks until content makes sense

## Acceptance Criteria
- [x] I can see help content on the Find Accounts page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
