### ISSUE TITLE
Updates to education pages

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#20714]
## Issue Description
In December Congress (both the Senate and the House) passed substantial legislation, the Johnny Isakson and David P. Roe, M.D. Veterans Health Care and Benefits Improvement Act of 2020, (House Resolution 7105 [HR 7105]). Next, the Act goes to the President to sign, at which point we'll need to make updates to our VA.gov pages. 

Brief of HR7105

---
## Tasks
- [ ] Assess the changes needed.
- [ ] Determine which pages we'll need to update.
- [ ] Work with Education Service team (Tammy and Joseph Preisser) on the content updates / get their approval of changes. 
- [ ] Implement the edits in drupal.
- [ ] Copyedit all pages affected.
- [ ] Verify components and other details by running through the pre-pub checklist.
- [ ] Publish

## Acceptance Criteria
- [ ] All relevant pages are updated and published. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
