### ISSUE TITLE
Content Update from eBenefits Migration Team for CH31 VA.gov Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20718]
### Content support for:
- Unauthenticated (static) VA.gov pages
- Apps or tools
- Other writing or editing requests

### Engineering support for:
- Redirects that have **first been vetted by the VSP IA team**
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @RLHecht and @brianalloyd. If your request includes engineering support, also tag @ncksllvn and @kelsonic.
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * < description > 
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @RLHecht and @brianalloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page.  

- [x] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * This should probably say “**Veteran Readiness and Employment Benefits**” then on the next step, “**Apply for CH31 benefits under Veteran Readiness and Employment**” in that subway map.  I am open to suggestion of ocourse but the spirit of where they are going shoulf be specific to CH31 applications and not CH36.

<details>
<summary>Here is an example of where the subway map should refer to:</summary>
<br>

![ch31-apply](https://user-images.githubusercontent.com/53826255/109714039-ed6f1b00-7b6f-11eb-87d6-580754d2d83d.JPG)

</details>

   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * This was raised by stakeholders as a possibility of one reason why Veterans are filling out both and/or incorrectly.

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @RLHecht and @brianalloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs.   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Whenever you can, within a sprint should be fine.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: **eBenefits Migration Team**
- DEPO product owner: **Matt Self**
- Product manager: **Jason Wolf**
- Designer: **Jim Adams**
- FE engineer: **Micah CHiang** and **Jesse Cohn**
- Product/team Slack channel: **vsa-ebn-migration**

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by RLHecht** [comment]
The new text for the subway map should be the following:

1. Sign in to your eBenefits account.
2. Click **Apply**.
3. In the Education and Training section, click **Veteran Readiness and Employment Benefits**.
4. In the Veteran Readiness and Employment Program section, click **Apply for Chapter 31**.

Then under the subway map but not as a step 5 it should read:
If you're eligible, we'll invite you to an orientation session at your nearest VA regional office.

And then the CTA button would follow that. 

@bethpottsVADEPO Can you please just confirm I have this right before Jason does it in the widget? And @jason-gcio can I review it once it's done as well before we put it on the page? Thanks!

**Comment by jason-gcio** [comment]
I am also going to do a lap around some of the other feature toggles for CH31; I know there are a few entrances to that feature.  Once the content is approved, I will assume that for getting into EBN it will be the same

**Comment by jason-gcio** [comment]
Thank you @RLHecht - this looks good to me and I checked that it applies to all the other entry pages - I would like to close this ticket, but please feel free to open if you see something we missed.  Thank you @cohnjesse for your assistance with this as well, I don't know of another feature that has this many toggles!
![image](https://user-images.githubusercontent.com/53826255/112348018-cce13f00-8c9d-11eb-9cf3-dbe387ffd8c7.png)

**Comment by RLHecht** [comment]
Thanks @jason-gcio! Do you have a sense when we would be able to take this content out of the widget? Sitewide content is trying to keep track of these so that we can move content back to Drupal as soon as we can so that changes are way easier to make when needed.

**Comment by jason-gcio** [comment]
This feature is due to be launched on April 19, so I would imagine we would remove the feature toggles some time after that, maybe a month?

**Comment by RLHecht** [comment]
Sounds good. I'll set up a ticket for our team as a reminder to reach out late May about putting the content back into Drupal.
