### ISSUE TITLE
Midpoint Review: Booz Team - STEM Automated Denial

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#20726]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure VSP reviewers have appropriate access to secured applications.
- [x] VSP: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to VSP feedback tickets.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-decision_product-outline.md)
- Link to [prototype - Claims Status Tool](https://bahdigital.invisionapp.com/share/G7IAG7A2XKD)
- Link to [content doc - Claims Status Tool](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content.md) 
- Link to [content doc - automated email](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-email-content.md)
- Link to [content doc - STEM Scholarship Application - Decision notification](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#5-decision)
- Link to research plan (N/A) 
- Link to [test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/1493) (even if just a draft) for QA practice area review

## Meeting attendees from requesting team
- Product Manager (required): Darrell Neel
- DEPO product lead (recommended): Matt Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): Amy Knox, Emma Waters, Jen Jones
- Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No
 
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **Friday, Mar. 5, 2pm**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@amyknox asynch review is scheduled for Friday. Feedback will be delivered by EOD.

**Comment by dneel-bah** [comment]
All associated issues and tickets have been closed/addressed; closing this issue as completed.
