### ISSUE TITLE
Empower VSP teammates to document baseline product artifacts

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#2073]
For every VSP team:

- [x] Team mission
- [ ] List of Platform features and services your team is responsible for
- [ ] Product / Service Outline for each feature and service your team is responsible for
- [x] Team charter
- [ ] OKRs for your team tracked in one canonical place (provided by leadership)
- [ ] KPIs and baselines for each feature and service your team is responsible for tracked in one canonical place (provided by leadership)
- [x] Agile roadmap
- [x] Super Epics for "Now" part of roadmap, in ZenHub fully groomed w/user stories and tasks

## Objective
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

**Comment by rroueche** [comment]
We have 3 very similar issues, how can we consolidate/align?

**Comment by rroueche** [comment]
We made good headway on this overall, and how have the remaining "to dos" broken up into new super epics.
