### ISSUE TITLE
Address update to Foreign Programs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20734]
## Issue Description
Stakeholder Tammy Hurley requested an address change on our [foreign programs](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/) page. 

Under the section "How do I get these benefits?" we need to take out the mailing address and change the text to the following:

You can send your request for information about foreign program approval by email to federal.approvals@va.gov

## Tasks
- [x] Update page with new content
- [x] Review and publish
- [x] Notify stakeholder that change was made

## Acceptance Criteria
- [x] Updated content is live on the site

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made this change to the foreign programs page. Can you take a look and let me know if you think it looks all right? I kept the same spacing as they had before but I made this change into a new bullet. 
Preview link: preview-prod.vfs.va.gov/preview?nodeId=925

**Comment by RLHecht** [comment]
This page is now live with the change. Waiting to close for confirmation from Tammy that it's OK to just use the email address and not not snail mail.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I'm going to close this. If Tammy winds up saying we should add back in the postal address let me know and we can reopen the ticket.
