### ISSUE TITLE
Create Research Plan - 526 Usability

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#20743]
## Issue Description
_Create research plan in support of 526 general usability study_

---
## Tasks
- [x] Develop research plan for 526 Form Usability test created

## Acceptance Criteria
- [x] Completed research plan
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
A research plan for the 526 Usability test is created. 

Plan can be found here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/mar-2021/ResearchPlan.md
