### ISSUE TITLE
Iterations to schedule appointments page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20746]
## Issue Description

We want to iterate on this page to help Veterans get into the tool faster. 

As part of this effort, we want to make these 3 updates to both instances of this page:

- Remove in-body COVID-19 alert
- Move "Please note:" beneath sign-in modal
- Remove H2 above the sign-in modal

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/7494435a-1233-4700-97c9-fc9d5f3ebcbc)

---
## Tasks
- [x] Update react files
- [x] Review and approve PR to deploy

## Acceptance Criteria
- [ ] Updates live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht and @brianalloyd. We're working with the health modernization team to iterate on the health tool pages. This is the first one. Since these pages are in react, we'll need PW help with the updates.

I think this round is very straightforward/quick. But please let me know your thoughts.

Thank you!

**Comment by brianalloyd** [comment]
Thanks @DanielleThierryUSDSVA PW will groom this ticket today and be ready to scrub into supporting.  Looks pretty straight forward but we'll reach out if we need any clarification.  Thanks.

**Comment by kelsonic** [comment]
Hey @DanielleThierryUSDSVA! This seems like a quick one. My only question is for each Cerner page (e.g. scheduling page), we have 2 pages: 1 is unauthenticated and the other is authenticated + Cerner user. Do we want these content changes to also show on the authenticated + Cerner user scheduling page? 🙂

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @brianalloyd and @kelsonic! 

@kelsonic, yes. Sorry, I was thinking of the 3 possibilities (unauthenticated, unauth + no Cerner, and auth + Cerner), but it's only 2 content instances since unauth and unauth + no Cerner see the same content. I just edited above to reflect "both instances" rather than "3 instances". Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @outerpress

**Comment by mpeterz** [comment]
Thanks for updating the H1 and intro text and replacing the top COVID box with the note. :))) **What is the ETA on the rest of the updates?**

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mpeterz @brianalloyd @kelsonic. To keep us all in sync:

- Danielle and Randi updated H1, left nav, intro text, and related links in Drupal - Complete
- Looks like the changes outlined above are scheduled to be completed by Kelson and Brian this sprint (so by 3/23) - Do I have that right?
- Then there are changes to content further down the page that I need to finalize as part of larger tool landing page content patterns. Those will also need PW support. I will create a ticket for that within the next week.
- Finally, Sitewide Content's goal for these health tool landing pages is to work with PW to get much of this content back into Drupal so that we can more easily manage updates. @RLHecht is going to be creating a ticket around that, so we can work with @kelsonic and @brianalloyd to figure out how best to do that. 

Thanks, all!

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA that sounds right! I am picking up this ticket now and will have a PR up for it in a few hours at max 👍

One last thing is that [I have a PR open](https://github.com/department-of-veterans-affairs/vets-website/pull/16383) to change instances of "Schedule and **view** appointments" to "Schedule and **manage** appointments" as can now be seen on the schedule appointments page (https://www.va.gov/health-care/schedule-view-va-appointments/) elsewhere around `vets-website` (VAOS had a few link labels as well as the facilities team).

**Comment by RLHecht** [comment]
@kelsonic Just make sure with that PR for the change in the Schedule and view appointments is "Schedule and **manage health** appointments." The word "health" should be in there.

**Comment by kelsonic** [comment]
Oh thank you for letting me know! I'll make the update now! 🙂

**Comment by kelsonic** [comment]
@RLHecht I updated the PR to use "manage health", could you give it a quick review when you have a second? https://github.com/department-of-veterans-affairs/vets-website/pull/16383/files

I also have a PR up for the scheduling page content tweaks now, if you wouldn't mind giving that a quick review too! Thank you! 🙂 https://github.com/department-of-veterans-affairs/vets-website/pull/16403

**Comment by mpeterz** [comment]
Thanks to everyone! If we don't already, we'll also have a ticket for updating the text in the sign-in box (which is on the pages in this spreadsheet — and might be on other pages). Is that right, @DanielleThierryUSDSVA?  

[sign-in-CTA-inventory_3-1-2021.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6157152/sign-in-CTA-inventory_3-1-2021.xlsx)

**Comment by brianalloyd** [comment]
Hi @DanielleThierryUSDSVA looks like this ticket has been validated, are we clear to close.

**Comment by brianalloyd** [comment]
Closing Ticket in support.
