### ISSUE TITLE
Update TUD population list location

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#20740]
## Issue Description
The TUD population list is being updated to include `idme_uuid` values which are potentially sensitive and therefore should be moved from its current location inside the TUD module in `vets-api` to `va.gov-team-sensitive` where other test user account information is located. This will also allow for the password information to be properly filled out on the list and imported by the script.

---
## Tasks
- [x] Remove the `test_users.csv` file from the `vets-api` repository
- [x] Update the list to include `idme_uuid` information
- [x] Update the list to include account passwords
- [x] Add `test_users.csv` to the `va.gov-team-sensitive/Administrative/vagov-users`
- [x] Update the rake population script to take a file location as an argument to allow the population list to be use while located outside the `vets-api` repository 

## Acceptance Criteria
- [x] The population list will be fully functional; able to populate a list of test users and their login credentials
- [x] The population list can be separately downloaded and used to populate the TUD DB table from outside `vets-api`
