### ISSUE TITLE
[Research] Check In Remote Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#20757]
## Product Links
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)

## Description
Finalized documentation of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.

## Tasks
- [X] Create new folder for this specific test: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/remote-discovery
- [X] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/remote-discovery/research-plan.md)
- [X] Create [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/remote-discovery/conversation-guide.md) 

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product)
- [x] Review research plan and conversation guide with UX manager

**Comment by kristenmcconnell** [comment]
Draft research plan and conversation guide posted and is currently undergoing review.
