### ISSUE TITLE
[Research][UI] Check In Remote Research Assets

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#20760]
## Description
All assets for the usability prototype(s) needed to run the digital check-in remote discovery research study will be completed by the end of this ticket.

## Tasks
- [X] Create [assets for UX Pin prototype](https://preview.uxpin.com/c466c519812f0c48fa2c4e0e25d0a9e703dce5b3#/pages/137806822?mode=cvhidm)

## Acceptance Criteria
- [x] The prototype(s) is ready to be utilized within research session
- [x] Review assets with the team (particularly product)
