### ISSUE TITLE
[Research][UI] Check In Remote Discovery Research Sessions

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#20761]
## Description
Facilitate Remote Usability Research Sessions for Digital Check-in

## Tasks
- [x] Complete all research interviews based on [conversation guide]() and [research plan]()

## Acceptance Criteria
After all of the sessions are complete 
- [x] Consolidate Notes from each team member listening on sessions
- [x] Download video of sessions
