### ISSUE TITLE
FE Implementation of Vet Center 1.0

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20783]
## Issue Description
The MVP design spec has been finalized and CMS has defined the content structure. 

## Dependencies
- [x] Entity bundle type identified (see [Architecture](https://docs.google.com/document/d/1aJfja1dVPl7kzChWvbncZj5XOMOnr48ejxv2dY3B74Y/edit#) doc)
- [x] Mapping from page element to content model is available (See [mural](https://app.mural.co/t/vagov6717/m/vagov6717/1614274642123/3509c33494d6dbc74e362cfe458dc5f2a517ec39).)
- [x] Flag strategy - we'll rely on data not being published to prod until we're ready to roll out. In the meantime people can use Tugboat for dev/testing.

---
## Tasks
- [ ] Create new GrqphQL query for Vet Center content
- [ ] Create new Vet Center 1.0 template which pulls data according to the query and styles it according to the design spec

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
