### ISSUE TITLE
General Analytics Request for Authenticated experience — Existing direct deposit for comp & pen dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20785]
## Background

Now that we are going to have two separate dashboards to track [direct deposit for comp & pen](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/) and direct deposit for edu (#20652), I want to make sure the labeling between each dashboard is clear so we know exactly what data is getting pulled in to each dashboard.

This ticket is to create some labeling updates to the existing [direct deposit for comp & pen dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/). I want to make sure that this dashboard clearly labels all fields with "comp & pen" so there is never confusion around what data we are looking at. These are my suggestions:

<img width="1280" alt="Screen Shot 2021-03-03 at 3 58 43 PM" src="https://user-images.githubusercontent.com/34068740/109872128-004e2200-7c3a-11eb-990c-eae74ef18685.png">

## Tasks

- [x] Acknowledge receipt of this request
- [x] Update the labels on the direct deposit for comp & pen dashboard
- [ ] Samara reviews updates

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss, 

Thank you for your patience on this request. 

To update you -- I have made the requested labeling adjustments within the [direct deposit for comp & pen GA dashboard](https://analytics.google.com/analytics/web/#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/). 

That said, I wanted to make you aware I noticed the filtering within some of the widgets included both standard direct deposit and CNP direct deposit updates, i.e: `Event Action` **_includes_** `Profile - Add Link - Direct Deposit Information|Profile - Add Link - CNP Direct Deposit Information`. If you want this dashboard to only show the CNP-relevant data, we'll want to take a second pass at updating the widget filters. 

Could you confirm for us if your intention is for [this dashboard](https://analytics.google.com/analytics/web/#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/) to only be CNP data and we will make the remaining adjustments? 

Thanks in advance

**Comment by Samara-Strauss** [comment]
THANK YOU, @jonwehausen!! The updates look great.

> That said, I wanted to make you aware I noticed the filtering within some of the widgets included both standard direct deposit and CNP direct deposit updates, i.e: Event Action includes Profile - Add Link - Direct Deposit Information|Profile - Add Link - CNP Direct Deposit Information. If you want this dashboard to only show the CNP-relevant data, we'll want to take a second pass at updating the widget filters.

This dashboard should only be pulling in direct deposit for C&P data, as [this dashboard was put together to track direct deposit for edu data](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/UJwvqguWQMqJaGySJWq1VQ/a50123418w177519031p176188361/). Is this something you would take a look at to make sure we're pulling in the right data, or would I need to get one of my FE developers involved?

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss , 

No problem -- I took another look at each of the dashboards and the tracking on the site to get all the ducks in a row. 

After further review I can confirm we're actively tracking both cnp & edu to-date and each dashboard is filtered to reflect each DD product distinctly. 

I believe what happened was when we initially provisioned the _newly_ renamed C&P dedicated dashboard, we retained the existing logic within the widget for our original/generic/before C&P and edu event structure to give you a chance to look at the historical data if wanted, of course now those events are sunsetted in lieu of the `cnp` and `edu` specific events -- so you're correct in that those widgets on the C&P dashboard will then only show C&P events. 

If you ever want to take a look back at the historical `profile-get-direct-deposit-retrieved` events within the dashobard, you can use the C&P dashboard and set the date range back and those event totals will populate. 

Lastly, I updated the labels on the [edu dashboard](https://analytics.google.com/analytics/web/#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/_u.date00=20210211&_u.date01=20210328) to have similar labeling changes as C&P. 

Let me know any other questions/concerns you have may.

**Comment by Samara-Strauss** [comment]
> Lastly, I updated the labels on the edu dashboard to have similar labeling changes as C&P.

THANK YOU! This saved me another request :D I really appreciate it.

We should be good to close this! Thank you again!

**Comment by jonwehausen** [comment]
Excellent! @Samara-Strauss Thank you for your quick response. 

You have a great rest of your week.
