### ISSUE TITLE
[FE] Update street address field labels in the profile for both Home address and Mailing address

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20788]
## Background

[Slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1614797817147400)

On 3.3.21, Trevor Pierce asked if we could align the labeling of the street address field labels in the profile so that they matched labeling that will be used in the mobile app (and will be overall less confusing). These copy updates have already been approved by the content team and are as follows:

![Screen Shot 2021-03-03 at 4.25.38 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/fd6244d3-25a2-4bfb-ba7b-c55d186478e6)

- Change the labeling for the second Street address field to "Line 2"
- Change the labeling for the third Street address field to "Line 3"
- **Please leave "35 characters maximum" for both**

## Tasks

- [ ] Make the above changes for the Mailing address form
- [ ] Make the above changes for the Home address form
- [ ] Update tests as needed

**Comment by erikphansen** [comment]
This should be on staging soon and can be validated.

**Comment by Samara-Strauss** [comment]
Still not seeing this on staging — not sure if I should give it more time to show up?

**Comment by erikphansen** [comment]
Omg it's still not on staging. I don't know what's up.

**Comment by erikphansen** [comment]
I don't know why, but builds were not going out to staging all day. I see that `master` finally finished a build a few minutes ago. So I'm hoping this change will be on prod within an hour or so.

**Comment by Samara-Strauss** [comment]
Looks good! We can close this once it's pushed to prod.

<img width="578" alt="Screen Shot 2021-03-17 at 9 11 37 AM" src="https://user-images.githubusercontent.com/34068740/111472930-dba97e00-8700-11eb-8d75-2047c4e54548.png">
<img width="583" alt="Screen Shot 2021-03-17 at 9 11 50 AM" src="https://user-images.githubusercontent.com/34068740/111472931-dba97e00-8700-11eb-9ec0-94c0393b6933.png">

**Comment by Samara-Strauss** [comment]
Actually, we can close this out now. Thanks, Erik!
