### ISSUE TITLE
Add list component to Dependency Verification modal

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#20800]
# Background
Now that we have the Dependency Verification Modal in place we need to refine the list of dependents it shows to better match the mockup. 

[Mockup](https://xd.adobe.com/view/9a75a359-e0e2-4411-b235-60c3dddb4e6e-cf26/)

## Tasks
- [ ] Build out the list component to match the mockup
- [ ] Submit a PR for review

## Acceptance Criteria
- [ ] The list of dependents in the verification modal now matches the mockup
- [ ] A PR has been submitted for review
