### ISSUE TITLE
[WCAG2.1]: Update guidance docs with new success criteria and document the impact on practice areas

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20808]
## Issue Description
WCAG2.1 includes 17 new success criteria. We need to meet the Level A and Level AA success criteria. AAA is not required but could be considered if accessibility specialists feel they would not be too cumbersome for teams to implement.

## Tasks
- [x] Review the new success criteria: https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/
- [x] Document the relevant practice area(s) who would need to be trained on new criteria. **Specifically:**
- [x] Add a section underneath Foundational Testing for WCAG2.1 in our [staging review processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) document
- [x] Add any manual testing needed to the [What to expect from a11y specialists during a staging review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#what-to-expect-from-accessibility-specialists-during-staging-review) section

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
All tasks completed.
