### ISSUE TITLE
[WCAG2.1]: Document new and/or updated testing strategies for success criteria

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20809]
## Issue Description
WCAG2.1 will require us to evolve manual testing techniques and possibly invent new ones wholesale. We will need to update our accessibility guidance documents for foundational and advanced testing so teams know how to conduct this testing for themselves.

## Tasks
- [ ] Review the new success criteria: https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/
- [ ] Review all tickets and close them after work is completed
- [ ] Close the epic when all issues are completed

## Related Documentation
* [Staging review foundational testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#foundational-accessibility-tests-required)
* [Staging review advanced testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#advanced-accessibility-tests-recommended)
* There may be others, but these two documents are the most frequently referenced for teams in the collaboration cycle

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by 1Copenut** [comment]
@JoeTice I'm going to close this one since all the child tasks are complete. I'll use Noah's work to build out decks for new success criteria and testing methods.
