### ISSUE TITLE
Create artifacts to implement WCAG2.1 on VA.gov

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20806]
## Problem Statement 
OCTODE leadership is aligned on wanting to move the VSP accessibility standard to [WCAG2.1](https://www.w3.org/TR/WCAG21/). This ticket will capture the work needed to document and socialize the new standard with VFS teams.

This is a fantastic opportunity to improve our accessibility for mobile device usage and cognitive issues. Moving to WCAG2.1 will improve the user experience for a large number of veterans, their loved ones, and caregivers.

## Hypothesis or Bet
* Moving to WCAG2.1 will improve the user experience for mobile device users by putting renewed emphasis on mobile-first design
* This move will also improve the experience for users with cognitive issues such as TBI, ADD or ADHD

## We will know we're done when... ("Definition of Done")
* VFS teams are shipping new products with WCAG2.1 as the verified standard for accessibility

## Known Blockers/Dependencies 
* Accessibility test plan
* Documentation of the new success criteria
* Definition of new testing protocols (automated and manual)

## Projected Launch Date
* End of Q4 2021

## Launch Checklist
* [ ] Create an accessibility checklist
* [ ] Review the WCAG2.1 docs for new success criteria
* [ ] Establish new or updated testing protocols for WCAG2.1 in the VSP collaboration cycle
* [ ] Establish an education protocol for teams to implement the new success criteria in their development cycles

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by noahgelman** [comment]
Adding google doc that lists some upgrade details for WCAG 2.0 to 2.1
https://docs.google.com/document/d/13RNfslwmm1jxLDnlEYuScCBdGYjqjb0BDfKLls_mBwI/edit?usp=sharing

**Comment by shiragoodman** [comment]
@noahgelman  - could you grant Joe and I access to the above link you shared?
