### ISSUE TITLE
[WCAG2.1]: Keep the DRAFT roadmap updated with VA leadership and VSP product support, testing tools teams

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20807]
## Issue Description
Martha has shared a **draft** version of her WCAG2.1 rollout schedule. I'd like to add this roadmap to versioning in an editable format so we can adjust deadlines as needed, and have a single source of truth for our migration effort.

The draft version of the roadmap is attached below.

## Tasks
- [ ] Add the draft roadmap to version control (GitHub) in an easy to edit format. Thinking Markdown as a starting point.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

---
<img width="1000" alt="Screen Shot 2021-03-01 at 4 46 50 PM" src="https://user-images.githubusercontent.com/934879/109881574-24abfd80-7c3e-11eb-8b2b-d52813016423.png">
