### ISSUE TITLE
[WCAG2.1]: Establish training materials and walk-through for teams to implement success criteria

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20810]
## Issue Description
WCAG2.1 will heavily factor into product, design, and research practice areas. We want to ensure we have training materials (written documentation, slide deck, video walkthroughs) for teams to implement WCAG2.1 successfully.

## Tasks
- [ ] Develop a slide deck that can be exported to (accessible!) PDF for teams
- [ ] Schedule 2-3 training sessions where a11y specialists walk through design and testing changes
- [ ] Post videos in easy-to-find locations for teams to reference as needed

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
