### ISSUE TITLE
Add Regional Office Check to CH31

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#20847]
## Background
CH31 stakeholders let the team know that their pilot will be limited to four discrete offices: **Cleveland**, **Columbia**, **Denver** and **San Diego**.  In order to get all the potential applications that might be submitted all across the country filtered for a particular regional office and send them a payload, we need to run a check on the Veterans zip code after the PDF has been sent to the eFolder in VBMS and if it is applicable to the pilot regional office, send it there.

## Considerations
- All application submissions should have their PDF sent to the eFolder in VBMS on the Veterans behalf.
- There are 4 pilot sites, assume it will need to be easy to open these up to all ROs
- Cleveland will most likely be the first site to do this

## Tasks
- [x] Ensure the PDF is being sent to the Veterans eFolder
- [x] Make a call using this: 
`RO Routing`
`RORoutingWebService.Retrieve Regional Offices By Zip Code`
- [x] Determine the RO based on the Veterans zip code,
- [x] Send the application to VRE

## Acceptance Criteria
- [x] The testing submissions are being routed appropriately
- [x] A PR has been requested for merging

**Original note:**
We need to make a call to get the regional office. If it is not on a predefined list, we need to only send the pdf to VBMS.

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6093
