### ISSUE TITLE
TUD: Group by Account Types column; Fix filtering

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#20858]
## Issue Description
As a TUD app user, I would like the ability to group similarly filtered Account Types (ID.me, MHV, or DS Logon), so that I can select account credentials that apply to me.

---
## Tasks
- [x] Create a Dropdown on the Account Types column to select one of the available filtering items (ID.me, MHV, DS Logon)
- [x] Style dropdown according to VA Design system
- [x] Refactor filtering on TUD app
- [x] Ensure proper 508c & accessibility standards

## Acceptance Criteria
- [x] I can select an Account Type from the columns Dropdown box and see the filtered results
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Update:
After doing some preliminary analysis the Grouping by Account Type (ID.me/DS Logon/MHV) work is becoming a bigger issue.  The reason is because the current filtering system is implemented using Lodash's filter method (which filters the returned data from the Vets API) and mixing it with the react-table built-in filtering system.

The scope has drastically changed and refactoring is the best option to reduce code and ensure extendability.
