### ISSUE TITLE
[Epic] Combine Profile & Account (Profile 2.0)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2086]
We'll use this epic to track the progress for combining the existing Profile and Account pages.

## Discovery
- [x] Personalization 2.0 discovery [19078](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19078)
- [x] Create product outline #2168
- [x] Determine analytics approach #2298 

## Design-Intent Review
- [x] Complete Design-Intent review #5061

## Connected Accounts (Carey Otto)
- [x] [Epic] Connected Accounts Updates #6814

## Design
- [x] Samara's initial mockups of the new profile #2453  
- [x] Tressa's initial design explorations #4469
- [x] Settle on final design direction #4759
- [x] Navigation exploration #4843
- [x] Put together all screens for all states #5092
- [x] Contact information #5264
- [x] Military information #5265
- [x] Direct deposit #5266
- [x] Account security #5268
- [x] Connected accounts #5269
- [x] [Design] Connected accounts updates #6731
- [x]  "Personal Contact Info" : Modal to Edit-in-Place: Desktop #6739
- [x] "Direct Deposit" : Modal to Edit-in-Place: Desktop #6740
- [x] "Personal Contact Info" : Modal to Edit-in-Place: Mobile #6741
- [x] "Direct Deposit" : Modal to Edit-in-Place: Mobile #6742
- [x] Update copy for Profile 2.0 ([Content review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/content-review-process.md#how-to-request-content-review)) #5093
- [x] [Design] Create "Not in MPI alert" #9166
- [x] [Design] Update DD Header #9423

### Copy
- [x] Profile 2.0 Screen Copy - Account Security #6246
- [x] Profile 2.0 Screen Copy - Connected Apps #6748
- [x] Profile 2.0 Screen Copy - Military Info #6244
- [x] Profile 2.0 Screen Copy - Direct Deposit #6245
- [x] Profile 2.0 Screen Copy - Personal and contact information #6247

## VSP Pre-Usability Review
- [x] Pre-Usability Testing Design Review #6253
Pre-Usability Review Action Items
- [x] Design Feedback: Usability Testing Prep - Auth Experience #7175
- [x] IA Feedback : Usability Testing Prep [Profile 2.0] - #7140 

## Research Plan 
- [x] Conduct user testing #2092
  - [x] Create research plan & kickoff recruiting #2585
  - [x] Create conversation guide #2586
  - [x] Conduct sessions #2587
  - [x] Create report and tickets #2588

## Information architecture
- [x] Create content inventory of what needs to be included in the combined Profile and Account section. #2090
- [x] Propose new IA. #2091
- [x] Propose updates main navigation. #2093
- [x] Create a list of places we link to account? #2094
- [x] Review content pages/My VA dashboard for any needed updates #5518
  - [x] Review My VA for any links/content that need to be updated #5522
  - [x] Review Change your address content page for any links/content that need to be updated #5524
 - [x] Review Direct deposit content page for any links/content that need to be updated #5525
 - [x] Review Sign in FAQ for any links/content that need to be updated #5527
 - [x] Determine if there's any other pages we might have missed in this list above #5528
 - [x] Profile 2.0: IA plan and review #5534
 - [x] Consolidate any redirects/link updates that need to happen from #5518 into one list. #5536
 - [x] Update My VA account link #8400
 - [x] Update content in Change Address page #8420 
 - [ ] Update link in Change your VA direct deposit information section #8419
 - [x] Propose IA/URL plan for the profile itself #5538
 - [x] Submit IA Review #IA Request [Profile 2.0] #9670

### Build
- [x] Technical discovery #2455
- [x] Refactor Vet360 Profile form components to use SchemaForm #4068
  - [X] Ramp up profile forms to 50%1 | #6781
  - [X] Ramp up profile forms to 100%1 | #6782
  - [x] [FE] Refactor VA Profile: Background research to determine scope #4930
  - [x] Convert profile address form to use SchemaForm #5078
  - [x] Convert profile phone number form to use SchemaForm #5118
  - [x] Convert profile email address form to use SchemaForm #5121
 - [X] [BE] - Change response codes for contact info transactions3 #6774
 - [x] Create feature flag to gate Profile 2.0 work #6269
- [x] Implement extended "Save" state on the modal #6981 
- [x] Create new profile app #7255
- [x] Frontend build epic #5346
  - [x] Create a new side-nav component for Profile 2.0 #7256
  - [x] Profile header #5350
  - [x] Personal and contact information #5353
  - [x] Military information #5354
  - [x] Direct deposit #5355
  - [x] Account security #5356
  - [x] Connected apps #5357
- [x] [FE] - Serve Profile 2 at the normal Profile Route #8685
- [x] Switch to using React based breadcrumbs on the old profile #8692
- [x] [FE] - Change how FE determines in an address is overseas military or not and check/uncheck box #8752
- [x] [FE] Investigate existing functionality for Terms & Conditions on Account page #8753
- [x] [FE} - Change Profile bread crumb hard reload to client side router change #8755
- [x] [FE] Build "Not in MPI" alert on Account Security Page #9165

### Build - Updates that came out of User Testing
- [x] [Design][Discovery] - Profile 2.0 - Benefits #8235
- [x] [Design] Mobile navigation documentation #8234
- [x] [Design] Design Mobile Sub Navigation #8233
- [x] [Design] Create mocks for new mobile view (name tag) #8231
- [x] [Design] - Update email address mocks #8229
- [x] [Design] - LOA1 Profile design #8570

### Build - Implement any content updates/URL redirects/New URLs
- TBD
- TBD

### Build
- Team to ensure everything works prior to beginning QA 

## QA 
- [ ] [QA] Profile 2.0 Test Plan #8059
- [x] Determine what staging users we need/should use for Profile 2.0 QA #8284
- [x] Create updated documentation for Profile error codes #8372

## 508/VSP Staging Review
- [ ] [Submit Staging Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+meganhkelley&labels=product+support%2C+content-ia-team&template=staging-review.md&title=Staging+Review+%5BFeature-Name%5D)

### QA/508:  Implement fixes/updates that came out of QA/508-Staging audit 
QA
- TBD
- TBD
- TBD

508
- TBD
- TBD
- TBD

## Analytics 
- [x] Discovery #2329
- [x] Implementation #2330
- [x] Re-Evaluate Analytics #7470 (Matt)
- [x] Put together analytics plan #8182
- [x] Create VSP Analytics Review ticket [Profile 2.0] #9488
- [x] Profile: Refine OKRs and KPIs #10887

Analytics - FE implementation tickets
- TBD
- TBD
- TBD

## Testing 
 - [x] Conduct unit tests
 - [x] Conduct E2E testing
-  [x] Conduct Error handling test
 - [x] Conduct Manual QA

## Contact Center/ Comms Review (Ensure that VA contact center representatives are prepared to help Veterans troubleshoot VA.gov))
- [x] Create Product Guide #7561
- [x] Create Product Video #7562
- [x] Schedule Call Center Review #7569 

## Privacy and Security Review - VSP
- [x] [Submit Privacy and Security Ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=gunsch&labels=product+support%2C+collaboration-cycle&template=privacy-and-security-review.md&title=Privacy+and+Security+Review+%5BFeature-Name%5D) 
- Ticket for required Artifacts
- TBD (review action item)
- TBD (review action item)

## Pre-launch
[Full pre-launch checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)

##Launch to UAT users

## Phased Launch
 - [x] Launch behind a feature flag. Test with team.
 - [x] Launch to 25% of folks. Observe for 1 week observe any errors/problems.
 - [x] Launch to 50% of users. Observe for 1 week for errors/problems.
 - [x] Launch to 100% of users

## Post-launch
- [ ] [508 Office Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md)
- [ ] [508 Post-launch Audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md)

**Comment by Samara-Strauss** [comment]
Leaving this open for now. We can close out after we've completed the big fixes/enhancements we intended to create and the 508 review.
