### ISSUE TITLE
[Design] Notification preferences: Discovery

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20867]
## Background

Intro'd Liz to this project in #20391. Now we're ready to move on to discovery.

## Tasks

- [x] Liz reviews this list of tasks and adds to it as needed
- [x] Meet with Terry Bazemore (VA Profile) to go over this work
- [x] If needed, meet with Lihan
- [x] Come up with list of discovery questions and determine next steps needed to get answers
- [x] Document discovery findings

## Acceptance criteria

- [ ] Liz is ready to start design (including creating a plan for approaching design, documenting flows; creating mockups, and having the initial design collab with VSP)

**Comment by andaleliz** [comment]
[Documented discovery findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/initial-discovery-notes.md) and ready to move onto some design mock-ups. Feels a little nebulous given the unknowns, but I have enough to go on for concepting.

**Comment by Samara-Strauss** [comment]
Sounds good, and I think this is the best we can do for now. Working with so little definition is new territory for everyone involved. I'm hoping this comes together as seamlessly as VA Profile anticipates, but we'll definitely have to be on top of them throughout development.
