### ISSUE TITLE
Disallow for next VISN roll-outs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20868]
## Issue Description
Each time the VAMC team brings up a new System into Dual-State, a facilities engineer needs to add a disallow line (`Disallow: /(name)-health-care/`) under # existing disallow on va.gov to the robots.txt file  and push a PR to engineering to prevent crawlers from accessing the new site in dual state.

Platform needs a PR to add that one line to the robots.txt file found 

Per Steve Wirt, the disallow should go [here: src/site/assets/robots.txt:97]( https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/robots.txt#L97)
`Disallow: /performance-dashboard`
(In the useragent *  section which covers all bots other than usasearch and synapse)

A separate issue will be created for the addition of an allow statement when the VAMC team is ready to put up a banner from the legacy site. 

[Slack conversation here](https://dsva.slack.com/archives/CPQFCQKEH/p1610487930440000)

---
## Tasks
- [x] add a disallow line (Disallow: /(name)-health-care/) under # existing disallow on va.gov to the robots.txt file for the following

- /bedford-health-care
- /boston-health-care
- /central-western-massachusetts-health-care
- /connecticut-health-care
- /maine-health-care
- /manchester-health-care
- /providence-health-care
- /white-river-junction-health-care
- /albany-health-care
- /finger-lakes-health-care
- /syracuse-health-care
- /western-new-york-health-care
- /bronx-health-care
- /hudson-valley-health-care
- /new-jersey-health-care
- /new-york-harbor-health-care
- /northport-health-care
- /clarksburg-health-care
- /martinsburg-health-care
- /maryland-health-care
- /washington-dc-health-care
- /beckley-health-care
- /atlanta-health-care
- /augusta-health-care
- /birmingham-health-care
- /central-alabama-health-care
- /charleston-health-care
- /columbia-south-carolina-health-care
- /dublin-health-care
- /tuscaloosa-health-care
- /bay-pines-health-care
- /caribbean-health-care
- /miami-health-care
- /north-florida-health-care
- /orlando-health-care
- /tampa-health-care
- /west-palm-beach-health-care
- /huntington-health-care
- /lexington-health-care
- /louisville-health-care
- /memphis-health-care
- /mountain-home-health-care
- /tennessee-valley-health-care
- /ann-arbor-health-care
- /central-ohio-health-care
- /chillicothe-health-care
- /cincinnati-health-care
- /dayton-health-care
- /northeast-ohio-health-care
- /battle-creek-health-care
- /detroit-health-care
- /illiana-health-care
- /indiana-health-care
- /northern-indiana-health-care
- /saginaw-health-care
- /lovell-fhcc-health-care
- /chicago-health-care
- /hines-health-care
- /iron-mountain-health-care
- /madison-health-care
- /milwaukee-health-care
- /tomah-health-care
- /columbia-missouri-health-care
- /kansas-city-health-care
- /leavenworth-health-care
- /marion-health-care
- /poplar-bluff-health-care
- /st-louis-health-care
- /topeka-health-care
- /wichita-health-care
- /alexandria-health-care
- /central-arkansas-health-care
- /fayetteville-arkansas-health-care
- /gulf-coast-health-care
- /houston-health-care
- /jackson-health-care
- /shreveport-health-care
- /southeast-louisiana-health-care
- /amarillo-health-care
- /central-texas-health-care
- /north-texas-health-care
- /south-texas-health-care
- /texas-valley-health-care
- /el-paso-health-care
- /new-mexico-health-care
- /northern-arizona-health-care
- /phoenix-health-care
- /west-texas-health-care
- /alaska-health-care
- /boise-health-care
- /portland-health-care
- /puget-sound-health-care
- /roseburg-health-care
- /southern-oregon-health-care
- /spokane-health-care
- /wallawalla-health-care
- /central-california-health-care
- /northern-california-health-care
- /pacific-islands-health-care
- /palo-alto-health-care
- /san-francisco-health-care
- /sierra-nevada-health-care
- /greater-los-angeles-health-care
- /loma-linda-health-care
- /long-beach-health-care
- /san-diego-health-care
- /southern-arizona-health-care
- /southern-nevada-health-care
- /black-hills-health-care
- /central-iowa-health-care
- /fargo-health-care
- /iowa-city-health-care
- /minneapolis-health-care
- /nebraska-western-iowa-health-care
- /sioux-falls-health-care
- /st-cloud-health-care

- [x] Post message in VSP when PR is ready

## Acceptance Criteria
- [ ] Disallow line has been added

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@SgardnerPMP please add the relevant health care systems (VISN 7,8,10,20) to this issue

**Comment by mpelzsherman** [comment]
For future reference, it would save time if we could get this list in a format that's as similar as possible to the existing file.

Have a look at https://www.va.gov/robots.txt for reference.
