### ISSUE TITLE
[Design] Preferred Facility: Discovery

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20866]
## Background

We intro'd Liz to the preferred facility work in #20392. Now we're ready to move on to discovery.

## Tasks

- [x] Liz reviews this list of tasks and adds to it as needed
- [x] Review the VAOS tool on VA.gov
- [x] Review the VA.gov profile
- [x] Come up with list of discovery questions and determine next steps needed to get answers
- [x] Intro with VAOS team and additional calls as needed
- [x] Review [existing research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/research)
- [x] Document discovery findings

## Acceptance criteria

- [x] Liz is ready to start design (including creating a plan for approaching design, documenting flows; creating mockups, and having the initial design collab with VSP)

**Comment by andaleliz** [comment]
Met w/ Lauren + Peter today - received [VA appt flow document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request_flow.md) from Lauren that I'll review shortly. Sharing here so we can all be on the same page.

**Comment by andaleliz** [comment]
I've gotten answers to all the questions that popped up during this discovery phase and [captured them in our product folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/discovery-and-research/initial-discovery-notes.md). Ready to start on design.

**Comment by Samara-Strauss** [comment]
This is awesome, and excellent documentation! Great job!
