### ISSUE TITLE
Public Websites: Sprint 43 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#20894]
## Sprint 43 Priorities (CLP Launch / R&S Enhance / Tech-debt / Feature Enhancement Discovery)
1.  CLP build tweaks/fixes finalization (UAT/Staging Review Fixes, Internal Security Testing, Prepare for launch)
2. Navigation Headers / Nav
3. Resources and Support Enhancements - Video / Tags / Search
4. Work 'Tech-Debt' items from backlog - Mission to clear out tech-debt and mitigate risk
5. Intake Requests for March along with some applicable Tech Debt (508/a11y issues)
6. Cerner items from Post Mortem 
7. Discovery for feature adds to R&S (Feature adds - Research/Design)

### Capacity Planning: PTO/Holiday's
John: 0
Brian: 1
Nick: 3
Kelson: 0
Cassandra: 0
Cindy: 0

### Campaign Landing Page MVP 1.0
- [ ] [PO/PM] CLP Request Form (John/Brian/Kevin (CMS)
- [ ] [PO/PM/CMS] BLOCKER: Need CLP pages on Staging Env.  (CMS Dependent)
- [x] [PM/PO/CMS] Conduct user training via CMS training team (on-boarding sessions)
- [x] [FE] CLP Refinement Punch List - Stakeholder Review #20338 [Place Holder Ticket] 
- [ ] Practice Area Feedback - Staging Review [Public Website - Campaign Landing Page] #20883 (CMS + PW)
- [x] Quality Assurance Feedback - Staging Review - Public Website - Campaign Landing Page #20846
- [x] 508-defect-2 [SCREENREADER] Download (PDF) links need unique alt tags to differentiate between them #21017
- [x] CLP Update Image Size for Promos [CLP MVP 1.0] #21312
- [x] CLP "Where" Section needs to show URL #21314
- [x] CLP PDF Download button needs to be bottom aligned/Description Centered #21321
- [x] CLP Image window alignment #21322

### Resources and Support
Priority R&S Breakdown: WIP  [MVP 1.1 EPIC #15588] [Iterate Search EPIC #15584] [Iterate New Feature #20332]
- [x] [FE] Implement Videos template mobile UX and progressive enhancement #15605
- [ ] [FE] Update Tags component layer with new meta data field #16623
- [ ] [FE] Add whole phrase matching logic to RS search (learning center) #16916
- [x] [FE] Related information FE not matching design (learning center) #15272
- [x] [FE] Bug: Articles listings and RS search listings are showing weird html tag text #17779
- [ ] [FE] Chrome bug: Yellow line showing on some RS pages #18570
- [x] [FE] FE spacing bug - RS "VA benefits" component #20751
- [ ] [PM] Meet with Chatbot team and discuss readiness and support for R&S chatbot

### Cerner
- [x] [FE] Add unit test to Cerner Facility ID [Vets-website] #21235
- [x] [FE] Step-by-step guide to adding support for a facility to become a Cerner facility #21239

### Sitemap SEO Discovery
- [ ] [FE] VA.gov Site Map XML & Template Structured Data Issues #20170 

### Discovery (Research & Design)
- [x] [DISCOVERY] Send to Mobile R&S Enhancement #20331
- [ ] [DISCOVERY] R&S article ‘recommend/share’ feature #21180
- [x] [CLP Design] CLP background alternating panel color to optimize UX [Ticket]

### Intake Request - Techical Debt
- [ ] [FE] Display issues with button in sitewide nav on screens < 768px #21317
- [ ] [FE] Main navigation update: Add My VA to the unauthenticated navigation #21183
- [ ]  [FE/Content] Iterations to schedule appointments page #20746
- [ ] [FE] Iterations to schedule appointments page #20746
- [x] [FE] Bug: Weird flash and slow loading - VA.gov #21459

### Discussion Topics/Grooming 
- [ ] Talk to Public Websites about better BDD landing page PLACEHOLDER #18641
- [ ] [Public Websites Bug] VA.gov T&Cs for MHV login #20608
- [ ] 508-defect-2 [SCREENREADER] Download (PDF) links need unique alt tags to differentiate between them #21017
- [ ] 508-defect-2 [COGNITION] Videos should have captions and a link to transcript of #21020
- [ ] Add unit test to Cener Facility ID [Vets-website] #21235
- [ ] 1x Test account on a non-production env for Cerner Facilities #21238
- [ ] Step-by-step guide to adding support for a facility to become a Cerner facility #21239
- [ ] [Discovery] 1x Test account on a non-production env for Cerner Facilities #21238 (need to find a source)
- [ ] MVP learning center: videos template for desktop and mobile #11497
- [ ] Bug: Outreach hub events with broken social media links #21517
- [ ] Bug: Pagination link logic and alignment on Outreach hub #21528
- [ ] [Site Scheduled Maintenance] EVSS Maintenance and eBenefits Unavailable (March 17 and March 19) #21529

### Benefit Hubs
- [ ] [Discovery] PM to discover baseline analytics for benefit hubs [General Analytics Request for [Public Websites - Benefit Hubs] #21134] 

### Shift to Sprint 44
- [ ] [FE/Content] Explore and revisit Visual Regression Testing to aid in modifications to CMS templates and style #18869
- [ ] [Tech debt] Delete deprecated CMS code #19722
- [ ] [FE] Pager Component for Outreach Event Page #19292 (Validate)
- [ ] [FE] Typo fixes for VCL modal from Sitewide content #20610
- [ ] [FE] Iterations to schedule appointments page #20746

<details><summary>Collab Cycle Tracking Template</summary>

### 
# Collab Cycle Tasks
After copying this template into your new Sprint Priority issue, keep the Collab Cycle tasks needed for this sprint and delete the rest.
- [VSP Collaboration Cycle Image](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [VSP Collaboration Cycle Requirements/Info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)
- [Change Release Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/decision-tools/DRAFT_Change_Checklist.md)

## Define
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)

## Discover

- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
- [ ]  **[Discover] IA Request** - #(ticket)
### [Submit Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### [Privacy and security review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)
- [ ] Submit ticket for review: Use Privacy and Security Review template in va.gov-team-sensitive repository 
- [ ] Provide artifacts at least 48 hours prior to the review
- [ ] Schedule/hold Privacy and Security Review
- [ ] Complete any tickets that came out of Privacy/Security review (if any)

### [Submit Analytics **QA** request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### Release Plan
- [ ] Create UAT plan
- [UAT Template](www.google.com)*
- [UAT Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/UAT/profile-research-plan-UAT.md)
- [ ] Complete Release Plan 
- [Release Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)

#### QA
- QA Staging review scheduling: Have artifacts in and tag Tze 2 weeks in advance from the Staging Review. This makes it possible for Tze to get to it w/o being rushed. When you schedule the Staging review, also tag Tze in Slack.
- [ ] Create list of staging users
- [ ] Create list of use cases [see [Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)] and submit to Tze so he can create test cases/regression tests
- [ ] Create “Coverage for references report” OR a add a link to the Epic for the product you are releasing  

#### Accessibility
- [ ] Complete the [required accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Complete QA/Accessibility tickets that came out of Staging review prep (if any)

### Conduct Internal QA Session
It is beneficial to conduct an internal QA session prior to actual QA. This consists of the team allocating 1 hour to meet look for bugs and or issues with the product. This is beneficial because the engineers and designers have in-depth knowledge of potential problem areas that QA might not have the time/resources to look into.
- [ ] Internal QA has been conducted

#### List of issues coming out of internal QA session:
- [ ] Issue name #00000
- [ ] All issues that came from internal QA have been completed

### [Request Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Provide all required artifacts in the request
- [ ] Schedule/hold staging review
- [ ] Complete all IA feedback tickets
- [ ] Complete all Accessibility feedback tickets
- [ ] Complete all QA feedback tickets
- [ ] Complete all Content feedback tickets
- [ ] Complete all Design feedback tickets

### [Contact Center review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#contact-center-review)
- [ ] Create Product guide
      - [Product Guide example]()
- [ ] Create Product video
- [ ] Submit request for Contact Center Review
- [ ] Complete Contact Center Review

### Analytics follow up on Staging
- [ ] Analytics are complete
- [ ] Frontend has implemented analytics data layer changes
- [ ] Dashboards have been created and link directly to your OKR/KPI's
- [ ] Review dashboard(s) with Analytics team to ensure understanding of all metrics/calculations
- [ ] Dashboards are finalized/work correctly

### Preparing/Updating all necessary supporting documentation for your product
- [ ] API calls and dependent systems [Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account#api-calls-and-dependent-systems)
- [ ] Update product outline with updated release information and links to analytics dashboards [Product Outline Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)

#### Ex:(re-directs, changes to content, changes that affect other teams) 
- [ ] Create issues in Github for changes that will take place, add dates, and tag relevant people/teams (re-directs, content changes, UI changes, etc)
- [ ] Update dates/parties accordingly as launch approaches and dates are finalized

### UAT
- [ ] Conduct UAT Go/No-Go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/uat-go-nogo.md)
- [ ] UAT has been conducted
- [ ] Issues have been logged/added to the Release Plan. [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)
- [ ] Launch-Critical UAT issues have been resolved

### Phased Launch (depends on phases in your launch)*
- [ ] Conduct Launch Go/No-Go meeting
-  [Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/go-no-go-meeting-template.md)
- Invite your entire team, analytics, platform team members, etc
- [ ] Resolve any issues (if applicable)
- [ ] Continue with phased launch, resolving issues if they arise, monitoring analytics daily

#### Go-live to 100% of traffic
- [ ] Conduct Go-live go/no go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Launch%20go%20no-go.md)
- [ ] Resolve issues (if applicable)
- [ ] Launch to 100% of users

## Monitoring
- [ ] Monitor analytics daily to ensure there are no abnormalities/errors
- [ ] Resolve any issues (if applicable)

## Post Launch
- [ ] Fill in post-launch metrics in the Release Plan
- [ ] Remove old code (if applicable)

### [Full Accessibility and 508 Office Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#full-accessibility-and-508-office-audit)
- [ ] Request [Full 508/Accessibility Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)
- [ ] Complete required scans/tests
- [ ] Make required changes (if any)

### [Post Launch Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#post-launch-check-in)
- [ ] Update Release Plan with "post-launch questions" completed
- [ ] Schedule/Hold check-in
- [ ] Measure results against OKRs
- [ ] Prepare next steps and potential iterations if applicable

# Feedback from other teams

**Platform feedback:**
- The biggest blocker to a successful launch would be not implementing platform feedback earlier in the process. 
- It would be ideal to implement the feedback prior to the staging review. 
- More frequent communication of changes/issues via the slack channel would be beneficial.

**Accessibility feedback:**
- Include accessibility in design syncs, design-intent review, and anytime large changes are made.
- More frequent communication with Accessibility (ex: Biweekly accessibility meetings)
- For individual meeting/mini reviews use this [GH template](Enter link to template)
- Have an "Engineering intent review" and include accessibility (in addition to design intent review).

**PM Feedback:**
- Update Collaboration Tracker
- Add time estimates maybe
- how to roll this out
- put in epic format?

</details>

<details><summary>Kanban Board Template</summary>

### 
# Kanban Board
_Please select a ticket and include [WIP - [NAME]] next to the ticket that is being worked._  Pick up tickets by priority on the `To Do ` section to begin and move ticket through kanban workflow until `Done`. Please include resolution steps on tickets along with instructions if for some reason you are unable to complete the ticket during this sprint.  
Please tag <PM> on tickets when moved to **Done** section for validation and closeout.  Please connect if you have any questions or concerns in the interim.  Welcome to **VFS team** (for this sprint) we're excited to have the help.  

<details> 

<summary> TO DO </summary>

</details>

<details> 

<summary> ON-GOING </summary>

- [ ] [FE] <Discription> #174XX (WIP - Name)

</details>

<details> 

<summary> DONE </summary>

- [x] [FE]<Discription> #174XX (Validate - Name)

**Comment by brianalloyd** [comment]
End of Sprint 43, Closing.
