### ISSUE TITLE
[Epic] Combine Profile and Account: Information Architecture

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2089]
We'll use this epic to track the information architecture phase of the combine profile and account project.

- [ ] Create content inventory of what needs to be included in the combined Profile and Account section. #2090
- [ ] Propose new IA. #2091
- [ ] Conduct closed card sort #2092
- [ ] Propose updates main navigation. #2093
- [ ] Review wayfinding in logged out states and on content pages — what content pages do we need? What additional wayfinding elements do we need to add? #2094

**Comment by Samara-Strauss** [comment]
Closing in favor of tracking in larger project epic #2086
