### ISSUE TITLE
Update Subway Map on CH31 Feature Toggle

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#20890]
## Background
On the feature toggle(s) for the CH31, there needs to be some specificity to what the Veteran should do in order to get to the right feature.  (CH36 stakeholders noticed that they may be getting submissions when they shouldn't be.)

## Considerations
- Here is what the language in the subway should read:

1. Sign in to your eBenefits account.
2. Click **Apply**.
3. In the Education and Training section, click **Veteran Readiness and Employment Benefits**.
4. In the Veteran Readiness and Employment Program section, click **Apply for Chapter 31**.

_Then under the subway map but not as a step 5 it should read:_
If you're eligible, we'll invite you to an orientation session at your nearest VA regional office.

_And then the CTA button would follow that._

## Tasks
- [x] In the feature toggle, the text for routing to the eBenefits site, the content needs to be updated to the above.
- [x] Check if there are any other feature toggles that need to be updated as well
- [x] A PR has been requested for merging, if applicable

## Acceptance Criteria
- [x] Feature toggle(s) are updated
- [x] A PR has been requested for merging
