### ISSUE TITLE
Hyphens in breadcrumb

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20922]
## Issue Description
Breadcrumbs contain hyphens for some VAMC and Vet Center pages
1. Eastern Oklahoma
![image](https://user-images.githubusercontent.com/55411834/110036370-21764780-7cfa-11eb-838f-a5d1bd582bf8.png)
2. Pages without left nav in VAMC product have been addressed separately 

---
## Tasks
- [ ] Work with CMS to determine best method of producing breadcrumb (ie: use H1)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
resolved by #17521
