### ISSUE TITLE
[User testing] Combined Profile and Account

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2092]
Full project epic #2086 

- [x] Create research plan #2585
- [x] Create conversation guide #2586
- [x] Conduct sessions #2587
- [x] Create report and tickets #2588
- [x] Kickoff recruiting for Profile 2.0 Research #6325

**Comment by Samara-Strauss** [comment]
Closing and detaching from epic. The changes to the profile are minimal enough that we don't need to do a card sort.

**Comment by Samara-Strauss** [comment]
Reopening and repurposing to track user testing.

**Comment by Samara-Strauss** [comment]
Somehow, this never got closed out. Closing now!
