### ISSUE TITLE
Map handling in older browsers (WebGL error)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21015]
## Issue Description
We identified 1.3k events in the last 90 days in which Facility Locator failed to initialize WebGL, causing only the header and footer of the search page to render. This represents less than 1% of our pageviews over the same time period.

In the [Discovery issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19300), MPS was able to determine that the search functionality still works and pushed error handling code to fl_map_init_error_handling branch. 

At a minimum, we need to provide an error message when this occurs

---
## Tasks
- [ ] Add error handling when WebGL failed to initialize. 

## Acceptance Criteria
- [ ] Veteran will be presented with an error message rather than an incomplete page render. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Update from Sentry review today - this issue is occurring 10-30 times/day, on average - often with Firefox 52.

**Comment by mmiddaugh** [comment]
Reviewed again during May sentry review -> Impacting mobile users, newer version of Safari
