### ISSUE TITLE
526 Form Removal - Combat Zone

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21013]
## Issue Description

Advisement from Paul Shute that this page is not needed per VBA's claim process. Therefore it can be removed completely from the 526/BDD form - making any page design changes unnecessary.

## Tasks
- [x] Remove combat zone page. (related to this [design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19545#event-4413775804))

## Acceptance Criteria
- [x] Evidence of form removal. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
made BE ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/25173

**Comment by Mottie** [comment]
We are no longer removing the combat question, but instead bypassing it - see https://github.com/department-of-veterans-affairs/va.gov-team/issues/35437
