### ISSUE TITLE
Notice of Disagreement E2E Tests

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21011]
## Issue Description
In preparation for release, create E2E tests for app

---
## Tasks
- [ ] Create tests

## Acceptance Criteria
- [ ] Documented test
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
