### ISSUE TITLE
Update CTA buttons for R&S articles and restructure CTA audit .md file

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#21028]
## Issue Description
We've recently done an audit on CTA button verbiage for Resources and support articles which is captured here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/rs-cta-button-audit.md
Upon review, three CTA buttons need to be changed to ensure consistency (see excel file), and the .md file needs to be restructured so that button labels are easily searchable.
[R&S CTA Button Audit  (1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6092334/R.S.CTA.Button.Audit.1.xlsx)

---
## Tasks
- [x] _Change CTA button labels on 3 R&S pages (Selina)_
- [x] _Review and publish these updates (Randi)_
- [ ] _Restructure .md file (Selina)_

## Acceptance Criteria
- [ ] _Updated pages are published_
- [ ] _.md file is restructured and easily searchable
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review
What your decision review or appeal status means: http://preview-prod.vfs.va.gov/preview?nodeId=9626
Helpful VA phone numbers: http://preview-prod.vfs.va.gov/preview?nodeId=8427
How can I find a VA facility?: http://preview-prod.vfs.va.gov/preview?nodeId=8491

**Comment by RLHecht** [comment]
These pages all look good, @lunascoop. I published them and will validate after deploy.

**Comment by SgardnerPMP** [comment]
Selina to double check folder and close.
