### ISSUE TITLE
[DNS] Explore how to avoid using BIND / managing zones in multiple places 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#21027]
## Description
We manage DNS in 2 BIND servers on the SOCKS & Jumpbox servers, and these get updated by a BASH script that gets executed via Ansible. So, when we add new entires for things like review instances (RIs) for example, the DNS queries get answered by these BIND servers. 

## Background/context/resources
We would rather not have BIND running if it can be avoided, so that we can manage all DNS in Route53. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Research issues involved and determining whether or not this is feasible to use Route53 for these lookups
- [ ] Others TBD

## Definition of Done
- [ ] We're hoping that BIND is no longer used and that all DNS queries are handled by Route53

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Please see #35078 as a more recent, related issue

**Comment by jhouse-solvd** [comment]
This is not a requirement at this time. If we decide to make any changes to DNS infrastructure, it will need to be scoped appropriately, given the platform's new delivery infrastructure using EKS. 

Closing.
