### ISSUE TITLE
[FSR] Submission Data

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#21032]
## Issue Description
Form data should be transformed to match request body used by submission example outlined in the API docs 

Financial Status Report API Documentation
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/benefits-memorials-2/financial-status-report/api.md

---
## Tasks
- [ ] Format form data using submit transformer
- [ ] update submit url and verify successful transmission

## Acceptance Criteria
- [ ] Successful form submission to api
---
