### ISSUE TITLE
Reduce SVG sizes by removing boilerplate

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#21034]
## Issue Description
Web performance is all about reducing file sizes, compression, and removing unneeded things (JS, HTML, CSS, etc.) from passing over the network.  Most of the SVGs in the `vets-website` repository are often exported directly from a design tool (Adobe Illustrator, Figma, Sketch, etc.) without any further thought of refactoring. This issue aims to remove unnecessary properties on SVGs so that we can reduce their sizes.

TL/DR;
- Refactor SVG markup will result in smaller SVG file sizes = faster over the network.

---
## Tasks
- [x] Reduce SVGs in `vets-website` by modifying the SVG files displayed in front-end
- [x] Provide research for before/after for file sizes

## Acceptance Criteria
- [x] I can see the display of SVGs have not changed

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
