### ISSUE TITLE
Create Conversation Guide - NOD

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21049]
## Story
As a design researcher, I want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users I will be communicating with.

---
## Tasks
- [x] Document a conversation guide to include:

-   Intro
-   Warm up Questions
-   Navigation
-   Priorities
-   Features
-   Post Interview
-   Thank you and Closing

## Acceptance Criteria
- [x] Conversation Guide has been reviewed by team.
- [ ] 
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
Complete and documented in Github
