### ISSUE TITLE
[FE] Wire up prescriptions to My VA Health care

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#21047]
## Background
We need to wire up prescriptions to the new My VA Dashboard in the Healthcare section per the new designs.

## Tasks
- [x] Wire up prescriptions endpoint
- [x] Hide/show section based on [specs in documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md)
- [x] Ensure implementation matches [Desktop and Mobile designs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md)

**Comment by Samara-Strauss** [comment]
This has been completed and merged.
