### ISSUE TITLE
Convert generic Policies page to new content model

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21041]
## Issue Description
This issue contains the tasks which are needed to implement the front end for the new hardened. Policies content

### Documentation
[Content model changes in VA.gov CMS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/content-model-changes.md)

### References

- [Mapping from page element to content model is available](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1614800814809/825fd5a0b0360ff42c2470e128d8f35af42579ee)

---
## Tasks
List of tasks - high level:
- [x] Facilities devs continue to ramp up on how our CMS build system works.
- [x] Get bundleType from CMS team for Policy pages: `vamc_system_policies_page`
- [x] Create new graphql query and register in the build system
- [x] Create new liquid template for Policies page and associated centralized content chunks

**Notes:**
- Connecting the /policies url to the new page should "just work" according to @kevwalsh.
- CMS feature flags are attached to the global object under cmsFeatureFlags. These can be accessed from graphql queries or liquid template filters
- The new and old pages may live at different URLs. This will be controlled by the CMS.

## Acceptance Criteria
- [ ] The new Policies page layout should match the spec provided by the CMS team. (See Mural link above)

**Comment by mpelzsherman** [comment]
I am blocked on finishing this ticket. The following items are needed to resume:

1. Centralized content available on prod CMS
2. Clarification on AC for the FEATURE_VAMC_SYSTEM_POLICIES_PAGE flag
