### ISSUE TITLE
Keyboard nav/focus for Clear input field

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21053]
## Issue Description
The Facility Locator clear input field features was implemented in #16513 without keyboard/screenreader focus so it could be reviewed in Staging. 

We need to begin our accessibility work on this feature by allowing it to have keyboard focus so we can seek additional feedback. 

Trevor's feedback follows: 

> I wasn't able to use the input with keyboard because it was added to the page source before the input and is an element that couldn't take keyboard focus. I wrote up the following HTML snippet as a possibility. LMK if you'd like to review next week with your team and we can put a meeting on the calendar.

```html
<div class="input-clear">
  <input
    id="street-city-state-zip"
    name="street-city-state-zip"
    title="Your location: Street, City, State or Postal code"
    type="text"
    value="Austin"
    required
  />
  <button aria-label="Clear your city, state or postal code" type="button">
    <i
      aria-hidden="true"
      class="fas fa-times-circle clear-button"
      id="clear-input"
      role="presentation"
    ></i>
  </button>
</div>
```

```css
div.input-clear {
  position: relative;
}

div.input-clear button {
  /* Set your position from right and top to add the button exactly where you want it */
  position: absolute;
  z-index: 1;
}
```

---
## Tasks
- [ ] Convert icon to button in order to have focus

## Acceptance Criteria
- [ ] Clear input button is accessible with tab 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@joshkimux @1Copenut @AngelaFowler82 this is ready for validation if one of you have a moment

**Comment by joshkimux** [comment]
Just validated on JAWS + Chrome and VO + Safari! Working great 😄 

On a semi-related note, during testing I noticed that the target area is relatively small (18x18). Would it be possible to increase the padding on this to stretch to the upper and bottom right corners of the input field?

**Comment by brangi** [comment]
@joshkimux 
> On a semi-related note, during testing I noticed that the target area is relatively small (18x18). Would it be possible to increase the padding on this to stretch to the upper and bottom right corners of the input field?

everything is possible but how much padding?

**Comment by brangi** [comment]
this is 2px for example:


<img width="1413" alt="Screen Shot 2021-03-19 at 3 30 13 PM" src="https://user-images.githubusercontent.com/100468/111839023-29241780-88c8-11eb-8438-52a1055787f4.png">

**Comment by joshkimux** [comment]
<img width="1121" alt="Screen Shot 2021-03-22 at 9 17 32 AM" src="https://user-images.githubusercontent.com/14154792/111995562-71714e80-8aef-11eb-9e84-8ff3d20bb07c.png">

If we could stretch it out to be 44x44 that would meet future compliance standards for when we switch to WCAG 2.1; it will especially help folks using this on mobile 🥳 

Might be a bit tricky since this is absolutely positioned though.
