### ISSUE TITLE
[FE] Wire up appointments to My VA Health care

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#21052]
## Background
We need to wire up appointments to the new My VA Dashboard in the Healthcare section per the new designs.

## Tasks
- [ ] Wire up appointments endpoint
- [ ] Ensure implementation matches [Desktop and Mobile designs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md)
- [ ] Verify with VAOS that implementation is correct

**Comment by sanlouise** [comment]
Merged and closing as there's not an easy way for this to be validated.
