### ISSUE TITLE
[FE] Wire up messages to My VA Health care

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#21056]
## Background
We need to wire up messages to the new My VA Dashboard in the Healthcare section per the new designs.

## Tasks
- [ ] Wire up messages/folder endpoints
- [ ] Hide/show section based on [specs in documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md)
- [ ] Ensure implementation matches [Desktop and Mobile designs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md)

**Comment by sanlouise** [comment]
Merged and closing as I don't think there's an easy way for this to be validated 😄
