### ISSUE TITLE
Testing: 508 for NOD

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21054]
## Story
As an frontend engineer, I want a 508 test, so I know my application is as accessible as possible, and accounts for various different user scenarios.

---
## Tasks
- [ ] Define the 508 testing domains for this feature and reference any existing documentation and create a test infrastructure.
- [x] Create unit tests for any new component logic.
- [x] Create e2e tests for any new UI functionality.
- [x] Keyboard functionality/accessibility
- [x] Onscreen, color contrast, color blind review

## Acceptance Criteria
- [x] New feature passes aXe tests in chrome.
- [ ] Schedule a review with 508 Team (Trevor Pierce)

**Comment by Mottie** [comment]
Found a 508-defect-1 issue on the review & submit page
- Discussion: https://dsva.slack.com/archives/C8E985R32/p1621369273005200
- Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24897

**Comment by Mottie** [comment]
@vhenry07 I think we can close this. I'll let you close it if you think it's done.

**Comment by vhenry07** [comment]
Closing complete
