### ISSUE TITLE
Authenticated Experience: Sprint 43 (3/10 - 3/23)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21071]
## Priorities

1. Welcome AJ to the team!
2. Direct deposit for edu UAT
3. My VA design updates and continuing build
4. Communications permissions discovery and backend build
5. Preferred facility discovery
6. Additional profile work as time allows

## Onboard AJ

- [x] Onboarding: AJ Jakabcin #20439

## Profile

**BE**

- [x] Use correct case for VA Profile address types #21031

**FE**

- [x] Update street address field labels in the profile for both Home address and Mailing address #20788
- [x] Consolidate duplicate contact info util code #20678 
- [x] Change `Edit Contact Info` form's Update button disabling logic #20494
- [ ] "Are you sure?" deletion alert stays pinned to bottom of window #18547

## My VA redesign

**PM**

- [x] Submit for IA review #14642

**Design**

- [x] Content Feedback - Usability testing prep - My VA #19762
- [x] Post-usability testing updates to My VA #21170
- [x] Regroup on needs for error states #21177
- [x] Disability rating error message #21367
- [x] Messages error message #21368
- [x] Appointments error message #21369
- [x] Prescriptions error message #21403
- [x] Post usability testing content updates #21543
- [x] Determine what errors we need for "Benefits you might be interested in", if any #21445
- [x] Design error for when we can't detect whether someone has health care or not #21579
- [x] Claims error message #21370

**FE**

From last sprint:

- [x] Wire up appointments to My VA Health care #21052
- [x] Add Cerner AlertBox to My VA Dashboard #21057
- [x] [FE] Build the Claims and Appeals section #19742

New tickets:

- [x] Add Loading spinner to My VA Health Care #21060
- [x] Add tests to My VA hiding/showing Health Care sections #21059
- [x] Wire up messages to My VA Health care #21056
- [x] My VA: Revert prescriptions work for My VA 2.0 #21254
- [x] Cannot remove expired application notifications #19703
- [x] Stop showing expired applications on My VA 2.0 #20775
- [x] Look into downtime error handling for My VA #21375
- [x] Look into how to handle 'Applications in progress' errors #21377
- [x] Look into how to handle 'Benefits you might be interested in' errors #21379
- [x] Create CTA Link per new designs #21739

## Direct deposit for edu

**Design**

- [x] Conduct UAT Research #19732

**FE**

- [x] Manage feature toggle for UAT/Attend UAT #21142

**BE**

- [x] Convert dd_type to symbol in direct deposit email jobs #21391
- [x] Add multifactor verification to ch33 direct deposit apis #21231
- [x] Attend UAT #21143

## Preferred medical facility 

**Design**

- [x] Discovery #20866
- [x] Initial mockups for preferred facility #21267

## Communications permissions (notification preferences)

**Design**

- [x] Discovery #20867
- [x] Initial mockups for communications permissions #21265

**BE**

- [ ] VA Profile notification preferences: Implementation (part 2) #19773

**Comment by ajakabcin** [comment]
Closing this sprint epic as the sprint/milestone is complete.
