### ISSUE TITLE
[Epic] R&S articles: VA dental care (Phase 1)

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21096]
## Issue Description

Create R&S articles on VA dental care. Move clearly R&S content from benefit hub as appropriate.

"dental" is 19th top search term in R&S, with 51 searches in the week of Jan 27 - Feb 25

SEMRush data for related terms includes (note: checked to make sure they are driving to results for our VA and not Virginia):

**Keyword > Volume for all results above 100 msv**
dental clinic near me	27100
free dental clinic near me	8100
va dental	4400
va dental insurance	2900
veterans affairs near me	2400
delta dental of va provider login	1900
dental hospital near me	1600
dental insurance for veterans	1600
veterans clinic near me	1300
champva dental	1000
va dental benefits	1000
virginia dental center	1000
vadip	880
delta dental for veterans	720
dental for veterans	720
does the va cover dental	720
va dental care	720
delta dental va login	590
delta dental vadip	590
va dental plans	590
dental care for veterans	390
does champva cover dental	390
free dental for veterans 2020	390
metlife dental for veterans	390
metlife vadip	390
va dental for 100 disabled	390
va dental insurance program	390
dental plans for veterans	320
free dental care for veterans 2019	320
free dental care for veterans 2020	320
va dental clinic near me	320
veterans dental benefits	320
best dental insurance for retired military	260
delta dental of virginia provider phone number	260
dentist lexington va	260
disability dental	260
do dental	260
metlife va dental	260
obamacare office near me	260
va dentist near me	260
delta dental va customer service	210
free dental services for veterans	210
va medical clinic near me	210
clinic dental near me	170
delta dental champva	170
delta dental va phone number	170
dental insurance for veterans no waiting period	170
fort jackson dental clinic	170
free dental care for veterans	170
free dental clinic atlanta	170
free dental for veterans	170
free tooth pulling near me	170
va dental benefits for 100 disabled	170
veterans dental care grants	170
champva dental insurance	140
dentures and dental services near me	140
does tricare cover veneers	140
free dental clinic atlanta ga	140
free dental for veterans near me	140
free dentures near me	140
portland dental school	140
va dental coverage	140
va emergency dental	140
100 disabled veteran dental benefits for family	110
aspen dental veterans	110
delta dental va plans	110
dental coverage for veterans	110
dental dental va	110
dental facilities near me	110
dentist office near me now	110
denture services near me	110
does the va have dental	110
does the va offer dental	110
va dental appointment	110
va dental insurance program vadip	110
va dental program	110
va priority group 1 dental	110
vadip dental	110
veterans affairs dental	110
veterans affairs dental insurance program	110
veterans dental clinic	110
who qualifies for va dental care	110

## Tasks
- [ ] Determine approach for VA dental care for Phase 1 (Beth, Danielle, sync w/ content/IA group)
- [ ] Implement and review changes (Sitewide content team)
- [ ] Alert VHA stakeholders of change (Danielle, Randi)
- [ ] Publish (Sitewide content team)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
