### ISSUE TITLE
Rework Manage your VA debt to become landing page for debt letters, pay debt, and FSR

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21092]
## User story
As a Veteran with VA debt, I need to have a clear understanding of how to check the status of my debt, pay my debt, and request help with my debt as needed. I also need to understand the current status of the pause on VA debts and related debt relief options during the COVID-19 pandemic.

## Issue Description
We have 3 events converging:
- We are launching the new "Request help with VA debt" (Financial Status Report) tool. 
- We are aiming to migrate content related to managing VA debt from the legacy site to the modernized VA.gov website.
- VA has paused debt collection through September 30, 2021.

We need the **Manage your VA debt** page to shift from supporting 1 tool (debt letters) to providing a clear pathway for Veterans who need to do the following:
- Check the status of their VA debt
- Pay their VA debt
- Request help for their VA debt
- Understand how the COVID-19 debt collection pause and debt relief options affect them

We also need to make it clear that this page and related tools are **not** for VA health care copays at this time, and provide pathways over to VA copay information.

## Working mockup of page

http://preview-prod.vfs.va.gov/preview?nodeId=16491 _(No longer relevant - taking down)_

## Current page with revisions

http://preview-prod.vfs.va.gov/preview?nodeId=6521

---
## Tasks
- [x] Build mockup of page (Danielle)
- [x] Final copy edit before stakeholder review (Randi)
- [x] Share page with debt management SMEs (Danielle, Beth, Leah)
- [x] Incorporate SME feedback (Danielle)
- [x] Final copy edit (Randi)
- [x] Send to SMEs for final awareness (Danielle)
- [x] Replace placeholder link with real link after FSR launches (Randi)
- [x] Publish page (Randi)

## Acceptance Criteria
- [x] Draft page ready for the Bam2 team to incorporate into their final staging review ahead of launch 
- [x] Page published
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. 

As we talked about, we're going to need to shift the **Manage your VA debt** landing page to support both the debt letters and FSR tools. Since the debt collection pause is now through at least September, we'll need to also find a way to make that clear on the page for the long-term (and I'm wary of stacking multiple alerts and sign-in modals...those were great for urgent needs at the start of COVID-19, but as we get into an extended time, we're relooking at them across pages).

This isn't really **new** content (and we can incorporate feedback from SME team on the other content pieces here). It's more of a redesign of the page to accommodate next steps.

Could you set up a meeting for us to go over this on Thursday or Friday? You can view my public calendar here: https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html

Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
@leahkeeler A question we'll need to answer here: Will the FSR roll out to all users upon launch? Or will you be doing a phased rollout? If the latter, we'll need to figure out how that impacts content and the need for some content to live within a react app.

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA We will be rolling out FSR to all users since it cannot really be separated from new debtman pages (much of the content on debtman is about how to fill out FSR which is not relevant to the online form) 

DMC is currently getting guidance around what can be communicated to Veterans re: pausing debt collection, I think it makes sense to wait to have the meeting until that is resolved - LMK your thoughts.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I have 1 open question out to health care SMEs, but this is otherwise good for a final copy edit and check of phone numbers and links.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This is all good minus the placeholder for the new FSR button.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Thank you! I've updated the health care info per health care SMEs, if you wouldn't mind just taking a final look at that for errors when you add the new FSR link.

**Comment by RLHecht** [comment]
This page is published. Closing ticket.
