### ISSUE TITLE
Prepare debt management Resources & Support articles for launch

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21093]
## Issue Description
We need to prepare the debt management content for launch.

---
## Tasks
- [x] Receive feedback from stakeholders
Notes:
  - Content for the 3 Resources and Support articles to support content migration was sent to stakeholders on 2.3.21 with a request for feedback by 2.10.21. 3/6/21 update - we are still awaiting content feedback.
  - Additional Resources and Support article to support debt collection pause information was sent to stakeholders on 2.19.21. 3/6/21 update - we are still awaiting content feedback.
  - Launch date dependent on when we receive content and the extent of feedback/need for continued work.
- [x] Evaluate content feedback and send back questions/concerns (Danielle)
- [x] Finalize content (Danielle)
- [x] Final copy edit (Randi)
- [x] Send final content to stakeholders for awareness with go-live date (Danielle, Leah)
- [x] Finalize which single Q&As should be standalone pages (and redirects) (Danielle)
- [x] Publish pages (Randi)
- [x] Take action on redirect request ticket ([#19908](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19908))

## Acceptance Criteria
- [x] Articles are live on site

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Adding articles as they're ready for you:

node 15594 is ready now

**Comment by DanielleThierryUSDSVA** [comment]
node 15606 is now ready

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. node 15715 is ready for final review

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Thank you!! @leahkeeler I've sent the previews to the DMC team, and cleared the copay content with the health care team. We are all set to coordinate these articles with the FSR launch. 

@RLHecht As discussed, we won't launch any single Q&As just yet. I'll look at SEO again and we can decide post-launch which ones we may want to pull out.

**Comment by RLHecht** [comment]
These R&S articles have all been published. @DanielleThierryUSDSVA do we need to do something for the redirects mentioned in the task list?

**Comment by RLHecht** [comment]
This ticket is complete (redirect ticket is still open and being worked on). Closing ticket.
