### ISSUE TITLE
Crosslink to Manage your VA debt page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21099]
## User story

As a Veteran with VA benefit debt, I need quick access to information about how to check the status of my debt, pay my debt, or request help with my debt.

## Issue Description

- Add crosslinks to Manage your VA debt page and Request help with VA debt pages per IA recommendations

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/045918e6-6da2-4463-9471-bcfdccbac0b6)

- Consider also adding as a related link (Manage your VA debt) to:
  - https://www.va.gov/claim-or-appeal-status/
  - https://www.va.gov/va-payment-history/
  - https://www.va.gov/records/download-va-letters/
  - https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/
  - https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/
  - https://www.va.gov/education/change-gi-bill-benefits/
  - https://www.va.gov/change-direct-deposit/

- Consider decision review page as a resource link? https://www.va.gov/decision-reviews/

---
## Tasks
- [x] Decide on "consider" crosslinks
- [x] Add crosslinks
- [x] Review and publish

## Acceptance Criteria
- [x] Crosslinks will be live on site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
A couple of updates to the list of entry points and content links.   The IA is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-fsr.md

There are 2 required link additions/updates 1) add link to the manage debt static page  2) update links on the Your debt page under the "How to get financial help" section.  

The rest of the items listed in the IA are recommended but not required.  There are a couple missing from the list above that we had talked about but hadn't updated.  I added them to the IA.

**Comment by RLHecht** [comment]
Thanks @mnorthuis. When I go to /manage-va-debt/your-debt I get redirected back to manage-va-debt. Is that the right url for the Your debt page?

**Comment by RLHecht** [comment]
@leahkeeler See Mikki's comment above about updating links on the Your debt page. Since that's not in Drupal someone on your team would need to make those changes. Not sure if you were already aware.

**Comment by LinnJS** [comment]
Hey @mnorthuis I am looking at this ticket now. I recall a very similar ticket to this in pre-launch and I thought all the stuff on our side was already done. At least on the required side. I know we are still fine tuning the form and have it on a staggered release. Will make sure there is a ticket in the backlog to revisit recommended cross links once we are fully released.

For #2 it looks like the `your-debts` page is coming from our Debt Letters code and looks like we have a link at the bottom of the page linking to the FSR.

Link reference for #2 https://staging.va.gov/manage-va-debt/your-debt/

![my-debt-fsr-link.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/bb2a8d60-d7df-495a-abea-b7ff1b14d5f7)

As for #1 it looks like that is coming from a page on the static content side but it might be coming from a liquid template or something so you all might not be able to see it in Drupal for that reason but I would have to double check with the Public Websites team. 

Will get back to you on #1.

**Comment by mnorthuis** [comment]
Hi @LinnJS, when I look, it looks like both those content changes have already happened in staging.

**Comment by LinnJS** [comment]
@mnorthuis awesome thanks for the validation, are we good to close this ticket?

**Comment by mnorthuis** [comment]
It's @DanielleThierryUSDSVA 's ticket, will leave it up to her.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @LinnJS @mnorthuis. We'll need to leave this ticket open until the content team adds the other crosslinks on the Drupal pages. Randi is out this week, so will probably be next week. Thanks!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I added related links to each of the pages you suggested above. There were some that didn't already have that section so I added it with the title "More information," which I saw on a few other pages. Is that OK or do we want anything more specific?

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
