### ISSUE TITLE
Create translation process graphic to share with VHA translation team

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21105]
## User story

As a member of the VA.gov content or VHA translation team, I need to understand how my role fits into the overall process of translating COVID-19 content.

## Issue description

Create process graphic to share with VHA translation team.

## Related documentation

Graphic here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1615063493759/5048504443d485e5d3e092b9a7cf5784573628b3

---
## Tasks
- [x] Create graphic (Danielle)
- [x] Finalize graphic (Danielle, Randi, Selina)
- [x] Share graphic with VHA translation team (Danielle, Randi)
- [ ] Add link to graphic to Sitewide Content and Content and Localization team folders for reference (Randi, Sharon)

## Acceptance Criteria
- [x] Graphic shared with translation team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I reviewed this and I think it looks good to me the way you have it broken out.

**Comment by SKasimow** [comment]
@RLHecht Done and closed!
