### ISSUE TITLE
Create template for content briefs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21102]
## User story

As a VA.gov writer, designer, or other expert working on a product, I need to understand the nuances of VA.gov content standards and patterns specific to the product and benefit area.

## Issue description

We are creating a template for a content brief. The content brief is a document that the Sitewide Content team will create for product teams. It is meant to be a living document used by writers, designers, and reviewers to ensure that content is consistent and following VA.gov standards.

### Draft of template

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/content-brief-template.md

---
## Tasks
- [ ] Create template (Beth, Danielle)

## Acceptance Criteria
- [ ] Content brief template is posted in the Sitewide Content github folder
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
This is complete.
