### ISSUE TITLE
NOD - Preliminary VSO Research

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21117]
## Issue Description
Prelim Research on the experience for VSOs to input data / go through the process for a NOD appeal

---
## Tasks
- [x] _What work is necessary for this story to be completed?_
- [x] _Meet with Maria to get all updated research info
- [x] _Gather and synthesize all NOD research. Summarize research still needed.

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- [x] _Summary of research and an overview of the remaining research needs
---
