### ISSUE TITLE
Improve Pact Broker Uptime and Availability

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#21122]
## Issue Description
The Pact Broker experienced significant downtime this past month but continues to suffer from poor availability; pages take forever to load and verification timeouts sometimes occur in CircleCi.

---
## Tasks
- [x] Talk to Demian Ginther in DevOps to learn more about where the Pact Broker is hosted
- [x] Move the Pact Broker to a more suitable host or upgrade the current hosting plan to improve availability
- [x] Discover why the Pact Broker continues to go down and fix it to stop downtime
- [x] Research monitoring solutions

## Acceptance Criteria
- [x] Pact Broker downtime is within acceptable limits
- [ ] Pact Broker response time is within acceptable limits
- [x] Basic monitoring for the service is setup

Unfortunately, as I write this, the Pact Broker is down again :-(
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/17987368-9930-4b3a-afd4-2b472b3bedf3)

**Comment by holdenhinkle** [comment]
I just DMed Demain Ginther:

Holden Hinkle  4:38 PM
Hi Demian, How are you?
We’re working on getting Pact ‘ready’ to release to VFS teams and there’s some talk about improving the availability of the Pact Broker. We’ve noticed that it’s super slow sometimes and still goes down from time to time. Is there a way we can upgrade the hosting or something?

**Comment by holdenhinkle** [comment]
Holden Hinkle  4:38 PM
Hi Demian, How are you?
We’re working on getting Pact ‘ready’ to release to VFS teams and there’s some talk about improving the availability of the Pact Broker. We’ve noticed that it’s super slow sometimes and still goes down from time to time. Is there a way we can upgrade the hosting or something?

Demian Ginther  4:40 PM
The stability issue should be fixed at this point.
4:40
This is the first I have been told that it has performance issues.

Holden Hinkle  4:41 PM
Oh, okay. Yeah, sometimes it’s super slow. And Lindsey and I noticed that requests sometime timeout in Ci.

Demian Ginther  4:42 PM
regarding ‘upgrade the hosting,’ it’s not ‘hosted’. We are running it on ECS/Fargate. We could experiment with giving it more CPU or RAM, but there was essentially no research done about what it wants/needs so I gave it a default value.
4:43
it seems like this is something that should have been experimented with before it was ‘ready to release’ time

Holden Hinkle  4:43 PM
Do you remember when you fixed the stability issue? When I wrote up a ticket about this on the March 8th the Broker was 504ing…

Demian Ginther  4:44 PM
March 10

Holden Hinkle  4:44 PM
Yeah, I guess we’re doing a 2nd release of sorts. Because Pact has been handed off to our team.
4:44
Ok, cool.

Demian Ginther  4:44 PM
is when i made the change that should have fixed that
4:44
however, if it is the TIC interfering with requests, I have no control over that and limited ability to troubleshoot it
4:44
the TIC will sometimes block traffic for no apparent reason
4:45
and I cannot tell when or why that will happen

Holden Hinkle  4:45 PM
Could you give it more resources? How can we experiment with the configuration to make sure it’s good?
4:45
Okay.
4:45
Can we setup monitoring for that?
4:45
The TIC issue?

Demian Ginther  4:45 PM
yes, I would highly recommend setting up monitoring for the pact-broker service.
4:46
I recommended that to the last team as well

Holden Hinkle  4:46 PM
Or general monitoring?
4:46
Oh, great.

Demian Ginther  4:46 PM
it is already monitored from a perspective of infrastructure
4:46
the service is not being monitored from an external viewpoint as far as I know
4:46
Eric Boehs recently set up some monitoring for his vtk-middleware project which is similar
4:47
but as far as detecting whether it is the TIC interfering, or something else, that’s not really possible to determine without investigating at the time it is happening

Holden Hinkle  4:47 PM
Okay.
4:48
when TIC is interfering, does that mean that Ci can’t contact the broker and to verify each pact contract?

Demian Ginther  4:48 PM
I can increase the CPU/memory that the task has, but I would recommend that your team make the recommendation about what it should be, based on expected traffic
4:49
every connection from the internet to the pact broker, via dev.va.gov/_vfs/pact-broker has to traverse the TIC. if it blocks the connection, yes, anything on the internet, including CI, would not be able to contact the pact server

Holden Hinkle  4:49 PM
okay, that’s great to know.
4:50
the plan was to make the pact tests blocking in ci, but given the TIC issue, that’s probably not a good idea, right?

Demian Ginther  4:51 PM
well, i would think that you would want to plan for that but that you would want to test it out for a while and not block CI, and make sure that it’s infrequent (edited) 
4:52
and is not having performance problems

Holden Hinkle  4:52 PM
okay, sounds good. thank you (edited) 
4:53
i’ll get with Eric to find out what monitoring he’s using and we’ll go from there…

Demian Ginther  4:53 PM
cool.

Holden Hinkle  4:54 PM
Thanks again Demian! Have a great rest of your day

Demian Ginther  4:54 PM
the resources settings are here: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-utility/pact-broker.tf

Holden Hinkle  4:54 PM
Okay, thanks for that

Demian Ginther  4:54 PM
right now it has 1024 CPU which comes out to around one CPU and 2048 MB RAM
4:55
but I have no idea what it actually needs

Holden Hinkle  4:56 PM
right. the monitoring will be able to help inform what the resources should be?

Demian Ginther  4:57 PM
doubtful, that will just tell you if the service is up/down and maybe latency

Holden Hinkle  4:57 PM
ah, okay. what’s the best way for us to figure out what it needs?

Demian Ginther  4:58 PM
the documentation doesnt appear to say anything about that. I can see if we can get some metrics about what it’s doing on the backend

Holden Hinkle  4:58 PM
okay, that’d be great.
4:59
super helpful conversation. thanks Demian!
New

Demian Ginther  4:59 PM
no problem

**Comment by holdenhinkle** [comment]
504 issue - https://dsva.slack.com/archives/G011B11C1L7/p1614114833000800

CI:
https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-website/23490/workflows/75b49e57-c47d-4f32-8803-ea4c57a1719d/jobs/203113

```
#!/bin/bash -eo pipefail
yarn pact:publish
yarn run v1.22.5
$ node ./script/publish-pacts.js
Published pact between consumer Search and provider VA.gov API.
***********************************/pacticipants/Search/versions/0c35dc62d9acdcbec2ddf4b1155565e1f7bac70b/tags/covid-chatbot-358
Published pact between consumer My Messages and provider VA.gov API.
***********************************/pacticipants/My%2520Messages/versions/0c35dc62d9acdcbec2ddf4b1155565e1f7bac70b/tags/covid-chatbot-358
Tagged version 0c35dc62d9acdcbec2ddf4b1155565e1f7bac70b of Search as "covid-chatbot-358".
Tagged version 0c35dc62d9acdcbec2ddf4b1155565e1f7bac70b of My Messages as "covid-chatbot-358".
Failed to publish and tag pacts.
Error: Failed to publish pact between consumer VA Profile and provider VA.gov API: 504 Gateway Time-out
    at publishPact (/home/circleci/project/src/platform/testing/contract/client.js:129:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 3)
    at async PactBrokerClient.publishAndTagPacts (/home/circleci/project/src/platform/testing/contract/client.js:208:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by holdenhinkle** [comment]
Holden Hinkle  11:26 AM
Hey Eric, How are you?
I was chatting with Demian Ginther the other day about the Pact Broker. We want to setup external monitoring for it and he mentioned that you setup monitoring for your vtk-middleware project. He suggested that I check in with you to find out what you’re using…

Eric Boehs  11:27 AM
Haha! I'm monitoring the pact broker and vtk-middleware with a personal grafana instance
11:27
I couldn't figure out how to do it within our infrastructure

Holden Hinkle  11:27 AM
Oh cool!
11:28
We’re getting ready to re-release the Pact Broker… It’s keeps going down, and the availability stinks, so we need to make some adjustments to the resources that are allocated for it…
11:29
We can get access to that grafana instance?

Eric Boehs  11:29 AM
Again, it's a personal grafana instnace
11:29
It's litterally running on my imac across the room

Holden Hinkle  11:29 AM
Oh!
11:29
Got it.

Eric Boehs  11:30 AM
I mentioned CloudWatch Canaries and Demian said we're starting to use that but wouldn't give me access to the UI. He said alerts go out via Slack and I could create the canaries via Terraform.
11:31
The uptime has been pretty good (not as good as other endpoints I'm testing though), granted I don't have an exact percentage but here's the last 12 hours:
https://files.slack.com/files-pri/T1ZD0UBMZ-F01RHPTDZ1C/image.png
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/17996ea7-a9b1-4b6d-948a-425f975e06ba)

11:32
Past 2 days
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/316571fb-e3c4-4893-8e62-9a3c39f26b97)https://files.slack.com/files-pri/T1ZD0UBMZ-F01RMF4L6F7/image.png

Holden Hinkle  11:32 AM
Oh, that’s good to know. Demian told me he made some adjustments to it recently…

Eric Boehs  11:32 AM
Yeah. It was when I started monitoring it :smile:

Holden Hinkle  11:33 AM
I think we was getting it from several of us then:+1:

Eric Boehs  11:34 AM
Well, it was when I deployed an app to dev and it was constantly down. So then I started monitoring it and pact. It wasn't pact that was the problem. Some load balancer or dns issue.

Holden Hinkle  11:34 AM
Oh cool. I asked him about it a month ago or so. Some TIC issue…

Eric Boehs  11:35 AM
Yeah. It was fixed in the past ~2 weeks

Holden Hinkle  11:36 AM
Thanks Eric. I’ll circle back to him about monitoring. Thanks for the info about Canaries. I have no experience with this. I’ll check it out.

Eric Boehs  11:36 AM
I don't either which is why I gave up and went with something I was familar with.

Holden Hinkle  11:44 AM
I’ll get with Darius on our team and see if he’s familiar with it. I’ll let you know if we get monitoring up for it.
:+1:
1

**Comment by holdenhinkle** [comment]
PR to bump resources for the Pact Broker from 1 CPU to 4 CPUs and 2GB of RAM to 8GB - https://github.com/department-of-veterans-affairs/devops/pull/8762

Darius and I put together a list of questions for Demian - https://docs.google.com/document/d/1Z-N6WHtkn-Aztudrym1LNx_eLr9SFF4dvqEtwdpUoeg

**Comment by holdenhinkle** [comment]
The Pact Broker's resources were bumped up to 4cpus and 8gb of ram. It's definitely snappier now.

Per Demian's request, I submitted a ticket to have `vsp-testing` team granted access to the console, and also CloudWatch monitoring for ECS, specifically for the Pact Broker. Here's the ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/21922

**Comment by holdenhinkle** [comment]
We're able to monitor resources in AWS:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/a031f844-46ba-47c3-b016-6ada8f5d257e)

Darius created a dashboard in Grafana:
http://grafana.vfs.va.gov/d/t38DSUQGz/pact-broker?orgId=1
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/95cad319-4805-411f-9780-66ddf7355cc0)

**Comment by holdenhinkle** [comment]
This ticket can be closed.

**Comment by pjhill** [comment]
Great work, all!
