### ISSUE TITLE
Determine if Consumer Pact tests must be merged before Provider Pact tests for successful Pact verification and tagging

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#21129]
## Issue Description
Recently there was an issue with verifying the Coronavirus Vaccination Pact. It seems that for the first time (as best as Lindsey Hattamer can recall), the Provider tests were merged before the Consumer tests which might have been the cause for the Pact not being successfully verified.

How we 'solved' the issue:
- Even though `can-i-deploy` failed for the Consumer Pact PR, we got the PR approved and merged it into master.
- We then created a new temporary branch with a commit to trigger the build. That process got the Pact verified.

As Eugene Doan pointed out, this process would not work in the future, once failing Pacts are blocking.

Eugene wrote:
> Oh, that is strange... I wonder if it would've gotten picked up (verified) if you created a new branch and PR. Presumably this failure would block merge eventually, so curious whether that could be the official workaround in that case.

---
## Tasks
- [ ] Research official Pact documentation to see if the Consumer must be merged before the Provider
- [ ] If this is not documented, perform an experiment to determine if the Consumer must be merged before the Provider
- [ ] If we're able to replicate the issue detailed above, test if creating a new branch and PR fixes the issue
- [ ] Update the pact documentation accordingly

## Acceptance Criteria
- [ ] A clear understanding of whether the Consumer tests need to be merged before Provider tests for successful Pact verification
- [ ] Create an official workaround solution for this issue if we're able to replicate it

**Comment by ddzz** [comment]
After testing locally and checking with the FE tools team, I confirmed that provider Pact tests need to be merged first. This PR updates our documentation with this information: https://github.com/department-of-veterans-affairs/va.gov-team/pull/22156
