### ISSUE TITLE
Review Pack Broker Basic Auth System

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#21124]
## Issue Description
When Pact is fully rolled out, VSP engineers responsible for writing Pact tests could each need login credentials to the Pact Broker. The Pact Broker currently uses Basic Auth and there appears to just be one account that's shared amount the current users (this needs to be verified).

---
## Tasks
- [ ] Review the Pact Broker authentication system and how new users can be created and managed
- [ ] Establish a workflow for handling new user requests and creating/managing users
- [ ] Look into creating a new user request form on GitHub

## Acceptance Criteria
- Left blank for now...
