### ISSUE TITLE
Explore the possibility of converting Nightwatch A11y Checks in Jenkins to Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#21128]
# Description
The Nightwatch accessibility test step in the Jenkins pipeline is taking ~32mins to complete. Would we gain any speed by switching to Cypress, or are these tests still needed at all?
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/ccc6458c-f5c0-4295-a0ff-0c2b52c48f06)

# Tasks
- [ ] Are these checks still required? Teams are also injecting axe scans into their e2e tests.
- [ ] Is it possible to switch from running these automated checks in Nightwatch to Cypress? (We have an eye toward phasing out Nightwatch use on the platform and hopefully remove it from the repository in the future.)
- [ ] Will this speed up or slow down the checks? Data please!

**Comment by pjhill** [comment]
Take into consideration the findings from Darius in this Nightwatch deprecation research --

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12209

**Comment by pjhill** [comment]
This effort would be duplicating the work in this [newer ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22443). Also, some characteristics of this ticket have been OBE. Closing
