### ISSUE TITLE
Mental health phone number audit

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21136]
## Issue Description
Missing mental health phone numbers were identified during the 508 review for Eastern Oklahoma VAMC. That issue will be resolved in #21073. 

This issue is to identify any other missing mental health numbers across the facilities and understand the cause for those. 

---
## Tasks
- [ ] Understand factors impacting the display of mental health numbers
- [ ] Identify other areas where these numbers are not displayed

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This was resolved in #21073

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/components/search-results-items/common/LocationPhoneLink.jsx#L13
