### ISSUE TITLE
Mobile design v2

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21137]
## Issue Description
We need to update the mobile search experience with recommendations/findings from the recent Facility Locator mobile research. 

### Two main problems to solve

**Making the map view more intuitive**
- Integration of map/list
- discoverability
- navigation between cards
- closing cards

**Interaction between list and map**
- discoverability/prominence
- navigation between list and map

**Other considerations**
- Prominence of "Use my location" and "clear fields"

## Resources
[Research readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/mobile-experience/FindingsMobileFacilityLocatorStudy%20.pdf)
[Link to tested prototype/design](https://preview.uxpin.com/c60117d778b6116d11f6fc707a5ac6d953d91aa0#/pages/136040014/simulate/no-panels?mode=chidmf)

---
## Tasks
- [ ] Review findings/recommendations from Mobile usability study (Feb 2021)
- [ ] Update design 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate to #20254
