### ISSUE TITLE
[WCAG2.1]: Define and document any testing updates for mobile devices

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21157]
## Issue Description
Define and document changes to our staging review and full audit processes to meet WCAG2.1 requirements for mobile devices.

## Tasks
- [x] Review [SC 1.3.4: Orientation](https://www.w3.org/WAI/WCAG21/Understanding/orientation.html)
- [x] Review [SC 1.4.13: Content on Hover or Focus](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html)
- [x] Review [SC 2.5.1: Pointer Gestures](https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html)
- [x] Review [SC 2.5.2: Pointer Cancellation](https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html)
- [x] Review [SC 2.5.4: Motion Actuation](https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation.html)
- [x] Determine if we need physical devices, a service, or browser emulators to test accurately
- [x] Define new or updated mobile device testing - automated
- [x] Define new or updated mobile device testing - manual
- [x] Define testing guidelines for slow or flaky connections (throttled, 3G, etc.)
- [x] Define testing guidelines for device types, OS
- [ ] Update VSP accessibility documentation with these new requirements

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by noahgelman** [comment]
Google doc: https://docs.google.com/spreadsheets/d/1evTnIcf9mZAP-6VdDqcRZ2MVElnsZuTWqoZqSM4otqg/edit#gid=0
