### ISSUE TITLE
[WCAG2.1]: Present the new decks of success criteria and how to test, so they can be recorded

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21166]
## Issue Description
WCAG2.1 will need to be socialized to teams across Product, Research, Design, Engineering, and possibly Ops practice areas. We should build a couple of slide decks to help teams understand this work.

## Tasks
- [x] Present the short-form deck from #21165 
- [x] Present the long-form deck
- [x] Record both presentations

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
can we close this @1Copenut ?

**Comment by 1Copenut** [comment]
@shiragoodman Yes we can. Moving this one to closed also.
