### ISSUE TITLE
[WCAG2.1]: Define and document any testing updates for keyboard navigation issues

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21164]
## Issue Description
Define and document changes to our staging review and full audit processes to meet WCAG2.1 requirements for cognitive issues.

## Tasks
- [x] Review [SC 2.1.4: Character Key Shortcuts](https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html)
- [x] Define new or updated mobile device testing - automated (keyboard e2e tests) 
- [x] Define new or updated mobile device testing - manual
- [ ] Update VSP accessibility documentation with these new requirements

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
