### ISSUE TITLE
[Design] My VA: Post-usability testing updates

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21170]
## Background

Based on [Tressa's research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-research-findings.md), we have decided to make the following updates to My VA 2.0:

### Health care

**Messages**
- Remove gray box
- Leave "totals" CTA (pending if you think that fits into the final design)

**Prescriptions**
- Remove gray box
- Change CTA to something like "View All Prescriptions" (**Note:** Please run any copy changes through Peggy)

**Appointments**
- Leave gray box
- Remove totals info
- Convert CTA to existing button style

**Overall**
- Update layout of health care section to accommodate removal of gray boxes 

### Claims

- Remove totals information

### Applying for benefits

- Move up "What benefits does the VA offer" FAQ to immediately below the "Apply for VA benefits" heading

## Tasks

- [x] Make all the above design updates to My VA
- [x] Review design with team/Samara 
- [ ] Get feedback from the design team to make sure everything looks a-ok re: design system

**Comment by tressaellen** [comment]
Here are the latest updates on My VA. I've changed it to a 2 column layout and made all the suggested changes.  Just a heads up - theres been some updates on the design system front on the 'actionable link', I'm in the process of discussing with VSP how and when that will effect My Va.

![My VA Desktop Copy 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/84891d2e-1201-45ed-97f9-1ddfb56d967d)

![My VA Mobile.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/0623f8db-ab28-4304-96c0-ab45456fa074)

**Comment by Samara-Strauss** [comment]
This looks pretty much like I would expect given the updates that came out of usability testing. Next step is to review with the team and the larger design team/design system folks if you haven't already!

> Just a heads up - theres been some updates on the design system front on the 'actionable link', I'm in the process of discussing with VSP how and when that will effect My Va.

Noted, and thank you for letting me know. Keep me posted!

**Comment by tressaellen** [comment]
I've chatted with VSP and crystabel - we have the go ahead to use the new 'actionable link' on our new page, so I've updated all buttons that are links to that. :) With that, we are good to go on this design. 

![My VA Desktop Updates.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/626aee4c-dafc-43f9-9c1a-85ccda0eb33c)

![My VA Mobile Updates.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/28604ad0-79bf-4881-8661-41958f010055)

**Comment by tressaellen** [comment]
I had a meeting with Josh and I am in the process of getting feedback from Kevin/Ryan and Josh now for the below design. But I wanted to make sure you're in the loop on what I've gathered and where I've landed.
**What I learned:**

- Action links with the large icon are only meant to signify the start of a large process NOT just linking to another page (i.e. starting a healthcare application)

**Changes I made:**
1.The desktop layout with the latest changes was visually awkward and had no real hierarchy, especially if there is only 1 application in the 'Applications in progress' section. I updated how the health care links are represented using essentially the exact same element from the Pittsburgh site (that has been tested and it tested well), so we should be good there.
2. With a better understanding of when the action link is supposed to be used, that means that the messages element in particular is not getting enough emphasis. So, the rules that I am using for links are as follows.

- Action link for the start of any large process

- Active link (bolded link) for any specific personalized update/total

- Regular link (unbolded link) for all other links to outside pages

I'd love any thoughts!![My VA Desktop Updates Copy 6.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/dc478c17-41cc-4995-bb21-55b06cb1655f)![My VA Mobile Updates  1 Copy.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/3317a10c-ae09-4d0e-8dc4-ac59664eab96)

**Comment by tressaellen** [comment]
Update - just wrapped a conversation with Ryan - something to keep in mind is that this design will likely be single column on a smaller desktop/tablet sizes because of our breaking points. It will still work though. Josh says he can take a look a bit later.

I've started building out all the different screens with this new design, @Samara-Strauss  where's the best place to post those? Do you want them in this ticket? Or maybe an invision link?

**Comment by Samara-Strauss** [comment]
This is great! Did Ryan suggest any changes?

> I've started building out all the different screens with this new design, @Samara-Strauss where's the best place to post those? Do you want them in this ticket? Or maybe an invision link?

This is a better question for @erikphansen and @sanlouise. I would assume that it would be helpful to update the InVision prototype for reference so they have the latest version.

BUT, when you get a chance, can you also send me a sketch file (doesn't need to be the full file of everything) of the latest mock so I can start updating the documentation we have in GitHub? It's now super outdated (as expected!) with the old designs, so I want to modify that and get the new screenshots in ASAP.

**Comment by tressaellen** [comment]
Here are [all of the desktop screens](https://vsateams.invisionapp.com/share/SH10HT8JCKYM), I'll post mobile later.

**Comment by Samara-Strauss** [comment]
Wonderful! Thank you for this!

**Comment by tressaellen** [comment]
Here are all of [the mobile screens.](https://vsateams.invisionapp.com/share/GC10HT8RSMQN)

**Comment by tressaellen** [comment]
@Samara-Strauss sorry, my GH didn't update so I didn't see your comment before I posted anything! He did not suggest any changes. :)

**Comment by Samara-Strauss** [comment]
Awesome, thanks for letting me know!

**Comment by joshkimux** [comment]
@tressaellen This looks good! It might be helpful to annotate the heading hierarchy as well to double check this will make sense to screen reader users.

The one tricky part might be for the `h3` Next Appointment. To sighted users, it's very clear that it's associated only with the date and "schedule and view... >" thanks to the grey box. It won't be explicit to screen reader users, so we may want to consider one of the following:
- Making the grey box a definition list `dl` and the links below it an unordered list `ul` so they are more clearly grouped; we may also want to consider _not_ making the "Next Appointment" a heading, but that may introduce inconsistencies
- Inserting a `sr-only` (screen reader only) heading above the list of links below the grey box titled something along the lines of "Your Tasks" or "Quick Links" (whatever these links are supposed to achieve in the Veteran's language)

**Comment by tressaellen** [comment]
@erikphansen and @sanlouise - tagging you here so you're aware of Josh's comment. ^^

**Comment by tressaellen** [comment]
We ended up updating the 'Benefits you might be interested in' section to this below. I'm also updating all the invision mocks todays, so we should be good to close this ticket!

![My VA FTUX.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/1e4d7630-d74e-4081-b969-d3ea53a623e0)
