### ISSUE TITLE
[WCAG2.1]: Upload training videos and link to them as much as possible

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21173]
## Issue Description
WCAG2.1 will need to be socialized to teams across Product, Research, Design, Engineering, and possibly Ops practice areas. We should build a couple of slide decks to help teams understand this work.

## Tasks
- [ ] Present the short-form deck from #21165 
- [ ] Present the long-form deck
- [ ] Record both presentations

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
