### ISSUE TITLE
[Design] My VA: Design error states

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21177]
## Background

Tressa mentioned that there are error states we still need to design for My VA. **The list of errors is pending a discussion with Erik.** We'll either treat this issue as an epic and create multiple tickets, or if things are simple enough, we can just use this ticket to track all error creation.

## Tasks

- [ ] @tressaellen to meet with Erik on 3/10 to determine error states to create
- [ ] Add list of errors to this ticket
- [ ] Determine if work needs to be broken down into further tickets
- [ ] Design error states (may be broken into smaller tickets)

**Comment by tressaellen** [comment]
Here's what we came up with after a discussion with Erik and Sandra. I've put an asterisk next to anything that needs an actual ticket - some are FE some are design. We also discussed that it would be a good idea to put together documentation for all of the errors similar to what we have for the design, which could be a ticket as well. 

**Overall**
- Error connecting to MPI - same as profile
- Not in MPI - same as profile

**Nametag (name/service)** - 1 endpoint
- same as profile 

**Disability rating** - 1 endpoint
- *Can't reach the endpoint - same error message as the nametag error but for disability rating

**Claims** - 2 endpoints (claims & appeals)
- *If either endpoint fails, then we won't show anything. We will need a message here to say why.
- *if the section is loading for a long time there is a spinner - this can take up to 30 seconds. Maybe we need to think about how to handle this situation better.

**Healthcare - handle each section as an individual section (separate messaging for each section - messages, appts, prescriptions)** 

**Messages** - 1 endpoint
- *Don't show section if there's an error - same message as in profile but for messages

Appointments - 3 endpoints
- *If any of the endpoints fail, do not show the section. (there's the potential that we would be showing the wrong appt) "Check back later" will work, "Refresh" won't work. (could potentially use the same message that's in profile)
- *Erik and Sandra will look into downtime errors

Prescriptions -1 endpoint
- *Don't show section if there's an error - same message as in profile but for prescriptions

Applications in progress - vets.api (likely won't have issues)
- *Erik will look into that more, potentially an error where we can't get their applications in progress

VA Benefits you might be interested in - 
- *Erik and Sandra need to do a little more digging for this one

**Comment by tressaellen** [comment]
Design tickets for this sprint:

- Disability rating error message
- Messages error message
- Appointments error message
- Claims error message
- Claims spinner handling

Design tickets for next sprint:
- Error messaging documentation

FE tickets:
- Look into downtime error handling for My VA
- Look into how to handle 'Applications in progress' errors
- Look into how to handle 'Benefits you might be interested in' errors

**Comment by Samara-Strauss** [comment]
Thank you! I will get those created after sprint planning.

**Comment by Samara-Strauss** [comment]
Created the following tickets:

**Design for this sprint**

- [Design] My VA: Disability rating error message#21367
- [Design] My VA: Messages error message #21368
- [Design] My VA: Appointments error message #21369
- [Design] My VA: Claims error message #21370
- [Design] My VA: Claims spinner handling #21372

**Design for next sprint**

- [Design] My VA: Error message documentation #21373

**FE**

- [FE] My VA: Look into downtime error handling for My VA #21375
- [FE] My VA: Look into how to handle 'Applications in progress' errors #21377
- [FE] My VA: Look into how to handle 'Benefits you might be interested in' errors #21379

**Comment by Samara-Strauss** [comment]
I think we can close this ticket now that more granular tickets have been created.

**Comment by tressaellen** [comment]
I realized I missed the prescriptions error, so I added it in #21402

**Comment by Samara-Strauss** [comment]
Awesome, thank you for letting me know! I will add it to this sprint.
