### ISSUE TITLE
[WCAG2.1]: Add the VA Mobile team's accessibility test plan to VSP documentation

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21174]
## Issue Description
The VA Mobile team wrote an [awesome accessibility testing plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/Accessibility%20Test%20Plan.md) based on WCAG2.1. They have been using it as their baseline for building an accessible app. We would like to add it to VSP accessibility documentation.

## Tasks
- [ ] Port the linked test plan above to VSP accessibility documentation
- [ ] Credit the VA Mobile team correctly
- [ ] PR and merge the plan with at least one VA Mobile team member as a reviewer

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

---
<img width="1000" alt="Screen Shot 2021-03-01 at 4 46 50 PM" src="https://user-images.githubusercontent.com/934879/109881574-24abfd80-7c3e-11eb-8b2b-d52813016423.png">

**Comment by 1Copenut** [comment]
This issue has been completed. We've added the WCAG 2.1 success criteria to the master spreadsheet of Platform standards. Moving to closed.
