### ISSUE TITLE
[WCAG2.1]: Socialize the Accessibility Test Plan as a Collaboration Cycle requirement

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21178]
## Issue Description
The accessibility test plan we are creating for #21174 will need to be socialized with VFS teams so they can familiarize themselves with it as the new baseline standard for future projects. It is meant not to hold teams up, but help them think about accessibility from the first day of a new product or feature.

## Tasks
- [ ] Announce the accessibility testing plan in VSP newsletter
- [ ] Announce the plan on VFS All Teams
- [ ] Announce the plan in Team of Teams

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

---
<img width="1000" alt="Screen Shot 2021-03-01 at 4 46 50 PM" src="https://user-images.githubusercontent.com/934879/109881574-24abfd80-7c3e-11eb-8b2b-d52813016423.png">

**Comment by shiragoodman** [comment]
4/20/2021: This initiative has dependencies to the VA.gov Standards documentation. A decision was made to put this effort on pause while we work on the following:

-  define an implementation approach for the accessibility testing plan
- possibly identify a pilot team/product
- finalize and launch the VA.gov standards for IA, content, design and accessibility on platform website

cc @1Copenut @noahgelman @JoeTice

**Comment by shiragoodman** [comment]
@JoeTice @pjhill itis not a priority for the collaboration cycle (at this time) to require VFS teams complete the Accessibility Test Plan. I am going to remove our team label, however feel free to close the ticket.
