### ISSUE TITLE
Explore alternative methods to placeholder text (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21182]
## Issue Description
When facility type = "community providers", Veterans are required to choose a service type from an extensive list. Placeholder text currently provides examples to guide users. However, Veterans may forget what the examples were upon clicking into the field (see [video](https://user-images.githubusercontent.com/14154792/110373356-67dee580-801d-11eb-9d70-2d21207f557c.mov)). These concerns are officially documented in our design system [here](https://design.va.gov/components/form-controls#accessibility).

This service list is a known problem area due to the clinical, nonintuitive nature of the NUCC taxonomy used by PPMS.  We hope to simplify the list in the future. Until then, we can explore options for improving the form feedback. Ideally, hint text should live above the field and below the label. [There are conversations right now on adding this to the design system.](https://app.mural.co/t/vsa8243/m/vsa8243/1613766593541/3c07de4000524ac050d6296afe88daed177ec5ad?wid=0-1613766656344)

## Tasks

- [ ] Review [this article](https://adamsilver.io/blog/placeholders-are-problematic/) by Adam Silver on placeholder text.
- [ ] Explore alternative methods to placeholder text (FL)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This will be addressed during the efforts in #27449 and #27450
