### ISSUE TITLE
Design intent eBenefits - CH31 Orientation Content

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21189]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Link to this issue once created in #design in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [ ] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [ ] VSP: Create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to VSP feedback tickets.
- [ ] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/README.md)
- Link to [mockups](https://xd.adobe.com/view/76c8e03c-ff8e-498b-ada5-0e2c08a8d8bd-239b/)

## Meeting attendees from requesting team
Designer(s) (required): Jim Adams
Product Manager (required): Jason Wolf
DEPO Product Lead (recommended): Matt Self
DEPO Design lead (recommended): not sure?
Content, IA, accessibility, and QA specialists (if applicable): Josh Kim
Other stakeholders you want to invite (if applicable)

## Scheduling
Would you like this review to be **asynchronous**? Please refer to the Design Intent guidance for the difference between a synchronous meeting and an asynchronous review.

- [x] **Yes:** this is just for folks to see the latest changes to the orientation content that the CH31 stakeholders have made required.  We have gone through a few cycles with them and have settled upon the above mockup - with 2 caveats; 
1. a few items are remaining, I will update this when complete and, 
1. videos seen in the mockup are going to be removed until some point after launch.  

We can certainly upgrade this to synchronous meeting if needed.

- [ ] No

What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
**March 19, 2 pm ET**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
This meeting has been scheduled as asynch for March 19, 2 pm ET

**Comment by jason-gcio** [comment]
@joshkimux - we are going to downgrade this request to spot checks (working with Beth Potts); can we set up a time to chat about this at some point?  Let me know what day is good for you and we can home in on a time.
