### ISSUE TITLE
Main navigation update: Add My VA to the unauthenticated navigation

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21183]
## Background

Per a meeting on 2.1.21, the DEPO/OCTO team determined that we wanted to add My VA to the unauthenticated navigation to see whether this would drive traffic and interaction. Team members who were part of this decision include Chris Johnston, Jen Lee, Meg Peters, Emily Mann, and Lauren Alexanderson.

**Specs:**

- My VA should appear in the unauth nav in the same spot it appears in the auth nav.
- Clicking My VA in the unauth nav should automatically start the sign-in flow. There is **not** going to be an unauthenticated landing page for My VA.
- If someone clicks My VA in the unauth nav and goes through the sign in process, they should land on the logged-in version of My VA once sign in is complete.
- No other sign in redirect behavior will change at this time:
   - If someone logs in from the **homepage**, they will still land on the homepage at this time. We may redirect them to My VA later on pending further discussion, but not right now.
  - If someone logs in from anywhere else on the website, eg. the claims tool, they stay where they are in the flow that they're in.
- We **do not** need to show My Health in the unauth nav.

## Tasks

- [x] Add My VA to the unauth nav in the same spot it appears in the auth nav
- [x] Have My VA in the unauth nav trigger the sign in flow
- [x] Redirect someone who clicks My VA in the unauth nav to the logged-in version of My VA once sign in is complete 
- [x] Once this is on staging, have Samara/unauth team review implementation
- [ ] **Build this behind a feature flag that will go out with the new My VA 2.0 launch**

**Comment by johnhashva** [comment]
For more context:

- Mobile Prototype - https://vsateams.invisionapp.com/share/XNZWCYAYD45#/444774121_Home_Screen

**Comment by brianalloyd** [comment]
@Samara-Strauss do you have a desktop design prototype you could share with our FE team on this?  thanks

**Comment by Samara-Strauss** [comment]
@tressaellen could you please provide both the desktop and mobile mockups we have that show My VA in the unauth nav?

**Comment by tressaellen** [comment]
Sure! ![My VA Unauthenticated Desktop.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/79ef7d38-e401-4cf8-b464-6f2edb42b798)
![My VA Unauthenticated Mobile.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/27db3550-40f4-43ec-a2c0-18904eeb02bf)

**Comment by Samara-Strauss** [comment]
@tressaellen sorry to nitpick — can you please take **out** My Health from the desktop mockup? That will **not** be added to the unauth nav.

**Comment by tressaellen** [comment]
Totally, no problem! 

![My VA Unauthenticated Desktop.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/a562b513-5c90-4060-b807-eb9d7c30ff9b)

**Comment by Samara-Strauss** [comment]
Question for the group: Should My VA be right aligned, or should it appear in the same position it does in the auth nav (which is not totally right aligned given that My Health is the right-most nav item)? I will leave this up to the designers in the group, but calling this out in case having it switch positions between logged out/logged in causes weirdness.

**Comment by johnhashva** [comment]
Good call out @Samara-Strauss.    Let's pull @rtwell into this one given significance.    @brianalloyd do you mind reaching out to Ryan for weigh-in?

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/16487

![image](https://user-images.githubusercontent.com/12773166/112217074-db6d1f00-8be7-11eb-8844-89e931d9ee3c.png)

I kept the `My VA` nav link location the same as when you are authenticated, but happy to move it over to the left side if we feel that's better, just lmk 🙂 For now I'll continue with how I've implemented it in the above PR

**Comment by johnhashva** [comment]
Thanks @kelsonic.    We should get a spot check on this from @rtwell. @brianalloyd want me to reach out to Ryan?

**Comment by rtwell** [comment]
happy to chime in here—could someone point me to the alignment of My VA vs My Health?

**Comment by ncksllvn** [comment]
it's in the screenshot further up the page, https://github.com/department-of-veterans-affairs/va.gov-team/issues/21183#issuecomment-796123975

**Comment by rtwell** [comment]
OH i think i see the question: should My VA stay in the same position, regardless of the presence of My Health? If that's the question then the way Tressa has this designed is the path I would recommend—always right-align.

**Comment by brianalloyd** [comment]
@Samara-Strauss could you review this in staging and validate AC for the FE team.  Thanks.

**Comment by Samara-Strauss** [comment]
Working as expected! 

One final thing: I want to confirm this is behind the same feature flag as the rest of the My VA 2.0 redesign work. This should not go out before the new My VA does, but it should go out at the same time. If you need to coordinate with anyone on that, either Sandra Hallie or Erik Hansen would be the right people to talk to.

**Comment by kelsonic** [comment]
Relevant thread: https://dsva.slack.com/archives/C52CL1PKQ/p1616695338232100 selector `selectShowDashboard2` will be used to derive feature toggle to conditionally add my-va top nav link when unauthed

**Comment by Samara-Strauss** [comment]
@johnhashva separate from the feature flag thing — to answer [this question you asked in Slack](https://dsva.slack.com/archives/G9TV2B50E/p1616694677110000), yes, we should have analytics tracking ready to go on this for when we're ready to launch. Let me know if you'd like me to handle this along with our overall analytics request for My VA 2.0, or if it's easier for you all to handle it as part of this ticket.

**Comment by kelsonic** [comment]
Making sure this wasn't lost on the [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1616696235236600?thread_ts=1616674696.222800&cid=C52CL1PKQ):

![image](https://user-images.githubusercontent.com/12773166/112526551-b0a9d480-8d67-11eb-8486-cdb50c4eabdd.png)

**Comment by johnhashva** [comment]
@Samara-Strauss definitely makes more sense for you to specify the Analytics tracking requirements.   Looks like @jonwehausen is engaged/aware that this will be coming.

**Comment by Samara-Strauss** [comment]
@johnhashva sounds good. We'll reach out to analytics when we're ready.

**Comment by kelsonic** [comment]
PR merged, should go out with daily deploy today: https://github.com/department-of-veterans-affairs/vets-website/pull/16522

**Comment by Samara-Strauss** [comment]
Thank you! I will be OOO around 3:00 ET (deploy time) today, so I will validate this on Monday morning.

**Comment by brianalloyd** [comment]
Thanks @kelsonic for the work on this.  @Samara-Strauss please reach out Monday once you've validated.  Thanks.

**Comment by Samara-Strauss** [comment]
Validated! Thank you for the fast turnaround on this, all. I really appreciate it.

Are we good to close this? When we're ready to launch/put My VA in the unauth nav, do we need to come back to your team, or is this something that will automatically go out with the rest of the functionality that is behind the My VA feature flag?

**Comment by johnhashva** [comment]
@Samara-Strauss if you are months away from My VA 2.0 launch, I say let's close this.   One other question: Are you signed off on the Analytics instrumentation for this -- basic event click -- as noted by @jonwehausen -> https://github.com/department-of-veterans-affairs/va.gov-team/issues/21183#issuecomment-807264813.

**Comment by ncksllvn** [comment]
@Samara-Strauss This was implemented to use the same Flipper feature flag as the My VA 2.0 application - `dashboard_show_dashboard_2`, meaning that if My VA 2.0 is enabled for a certain user, so will the `My VA` link in the navbar. (Thanks @kelsonic for doing the implementation!)

**Comment by ncksllvn** [comment]
^ my point being that no further coordination with Pub Web should be necessary and you should be able to confirm this behavior by toggling the feature flag on Staging

**Comment by Samara-Strauss** [comment]
> One other question: Are you signed off on the Analytics instrumentation for this -- basic event click -- as noted by @jonwehausen -> #21183 (comment).

Yep, this sounds good.

> This was implemented to use the same Flipper feature flag as the My VA 2.0 application - dashboard_show_dashboard_2, meaning that if My VA 2.0 is enabled for a certain user, so will the My VA link in the navbar. (Thanks @kelsonic for doing the implementation!)

Got it! We're *so close* to having My VA ready for staging, so I will confirm this is working as intended once the feature flag is flipped for staging. Thank you!

Otherwise, closing! Doesn't seem like any other work is needed here.

**Comment by ncksllvn** [comment]
Thank you @Samara-Strauss !

**Comment by brianalloyd** [comment]
Thanks @Samara-Strauss please reach out if you need anything else in support.  Greatly appreciated.
