### ISSUE TITLE
[Research][UX] Clinician Health Record Interviews

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#21210]
## Product Links
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [HealthRecord Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/health-record.md)
- [Medications Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md)
- [Allergies Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/allergies.md)
- [Immunizations Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/immunizations.md)

## Description
At the end of this ticket, a plan of what we want to talk to providers about medications, allergies, and immunizations will will finalized. 

## Tasks
- [x] Create new folder for this specific test here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/research/clinician-healthRecord-discovery
- [X] Create [research plan & conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/clinician-healthRecord-discovery/conversation-guide.md)

## Acceptance Criteria
- [x] Plan is finalized
