### ISSUE TITLE
Content updates needed to widget on Spanish vaccine page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21211]
## Issue Description
We received some updates to the content on the react widget on our [Spanish COVID-19 vaccine page](https://www.va.gov/health-care/covid-19-vaccine-esp/). These need to be done by a developer as we can't access the text in Drupal.

Updated text with changes highlighted in yellow: 

![image.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/a59f57d9-f7dd-4ee9-bf2f-b6a1ae1dc1b2)

## Tasks
- [x] Update content in react widget (Fareez)
- [x] Sitewide content to review changes (Selina/Randi)
- [x] Publish react widget

## Acceptance Criteria
- [x] Updated widget is live on site

**Comment by RLHecht** [comment]
@youngfreezyVA Is it possible to get these changes into today's daily deploy? Thanks!

**Comment by youngfreezyVA** [comment]
I will have a pr in shortly. confirming the text:
```Su centro de salud del VA local puede usar esta información para determinar cuándo nos podemos comunicamos una vez que su grupo de riesgo sea elegible. Por favor, tenga nota que estas actualizaciones solo están disponibles en inglés en este momento.',

**Comment by youngfreezyVA** [comment]
@RLHecht main word I need confirmation on is "comunicamos"
it was hard to see from the screenshot whether it was `comunicamos` or `comunicarnos`

**Comment by lunascoop** [comment]
@youngfreezyVA heres the text 

> Inscríbase para una manera fácil de mantenerse informado sobre cómo recibir la vacuna contra COVID-19 en él VA.
> 
> Cuando se inscriba, también le preguntaremos acerca de sus planes de vacunas. Su centro de salud del VA local puede usar esta información para determinar cuándo  nos podemos comunicarnos una vez que su grupo de riesgo sea elegible. Por favor, tenga  nota que estas actualizaciones solo están disponibles en inglés en este momento.
> 
> **Nota:** Intentaremos contactar a todos los Veteranos elegibles en cada grupo de riesgo. No es necesario que se inscriba para recibir la vacuna.

[Button] Regístrese para mantenerse informado (en inglés)

**Comment by youngfreezyVA** [comment]
@lunascoop thank you! PR is in

**Comment by RLHecht** [comment]
@youngfreezyVA One change that didn't get made. In the first sentence we need to change el VA to él VA. Accent on the e in el. Thanks!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
