### ISSUE TITLE
[FSR] Review and update the usability research plan and conversation guide

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#21223]
## Issue Description
_Prior to recruiting for the FSR's usability study, we need to review the research plan and conversation guide to ensure it aligns with the form. Additionally, we received feedback that we shouldn't ask Veterans for their personal financial information during the session; we need to reevaluate the conversation guide to determine a more empathetic way to test the form._

---
## Tasks
- [x] _Review and update the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/conversation-guide.md)_
- [x] _Send the research plan and conversation guide to Shawna for feedback_

## Acceptance Criteria
- [x] _The research plan and conversation guide have been updated in GH and linked in this ticket_
- [x] _Both documents have been sent to Shawna for review_

**Comment by rileyorr** [comment]
Both documents have been updated & approved by both Shawna and Lauren. Our study kicks off on March 19th!
