### ISSUE TITLE
Platform Website - Investigate installing Confluence Data Center (AWS/EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#21228]
## Issue Description
The VSP is interested in migrating to Confluence Data Center, Atlassian's self-managed enterprise edition of its documentation solution. At this time, Ops is looking at what's needed to get it installed into the VSP's AWS account using EKS

## Background / Resources
https://aws.amazon.com/quickstart/architecture/confluence/
https://github.com/Praqma/ask
https://www.praqma.com/products/ask/

---
## Tasks
- [x] Decide on architecture 
- [x] Decide on configuration 
- [x] Decide where to put it
- [x] Integrate with ArgoCD / install on cluster 

## Acceptance Criteria
- [x] Confluence will be installed for the purpose of evaluating and understanding more 

---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
@dginther - when you get a chance, if you can update the checklist, add any relevant PRs and/or notes and possibly move this to review/qa, that would be awesome!

**Comment by lianilychee** [comment]
hi @jhouse-solvd -- FYI, I added the Content team to the `Labeled with Team` line in the last section.

**Comment by lianilychee** [comment]
hey @jhouse-solvd - May the Content Team be added to this ticket somehow?  I initially thought the `content-ia-team` label should be added to the "Labeled with Team" line at the end, but I'm actually not sure how else you're configuring the ticket.

**Comment by dginther** [comment]
I installed Confluence on the EKS cluster as a test. I explored what would be necessary to make it into a multi-node Confluence DC cluster, however, because of the way Confluence is set up on the backend, it is not possible to scale it to multiple clusters in EKS.

The install is here: http://confluence.vfs.va.gov

In order to add a new node to Confluence Data Center, you must follow these instructions:
https://confluence.atlassian.com/doc/adding-and-removing-data-center-nodes-659783919.html which involve shutting down your existing node, manually copying the home directory to the new node, and then adding the _static_ IP address to a list on all the nodes. EKS does not allow for static IP addresses, nor multicast (we are using Calico CNI https://docs.projectcalico.org/reference/faq#can-calico-do-ip-multicast), and so it will really be impossible to add multiple nodes.

Because of this, we are limited to a single node Confluence install in EKS/Kubernetes.

If it becomes necessary for us to scale to a multiple node installation of Confluence DC, we would need to build it as separate EC2 instances. My proposed solution to this would be that each node would have a static IP on an ENI, and the nodes would each be in a single instance ASG so that they would be self-healing in the event that the node died unexpectedly. The shared data drive would be mounted from an EFS volume.

**Comment by jhouse-solvd** [comment]
@drorva - Do you mind leaving a comment or link to a slack thread where the decision has been made to stay w/ Confluence Cloud for now? and/or - should we have an official ADR or something for this? 

cc: @f1337 @dginther

**Comment by drorva** [comment]
Here's is the slack thread confirming the decision to stay with Confluence Cloud https://dsva.slack.com/archives/C01AS05BQ79/p1621270208074800

**Comment by jhouse-solvd** [comment]
Closing.
