### ISSUE TITLE
[FE] [SPIKE] Refactor API Calls for questionnaire list. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#21221]
Currently: the API is the acting like a service bus

problem: this is an anti pattern

solution: move API calls to have more front ends calls. 

----- 
# How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Labeled with Team (`vsa-healthcare-exp`)
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

As a veteran, I should have a lightweight solution that for my questionnaires that works with the lowest amount of data transfer

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description

Currently, we are using the API as a service bus. This is an antipattern for a scalable system. Instead of making one big call, the frontend would make a few smaller, light calls to aggregate the data. 
This ticket is to research the viability and requirements to make this happen

## Questions to Answer

- [x] What endpoints are needed to make this work
- [x] What requirements are needed for the API to make this work
- [x] What is needed to make this doable on the front end? 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Determin APis that are needed to be called
- [x] Create a prototype to replace the QM API calls

## Acceptance Criteria

> when is the ticket done

- [x] Relativant documentation has been created
- [ ] Findings shared with the appropriate team members

**Comment by mdewey** [comment]
Doc is here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/architecture/02.client.side.md

Scheduling meeting with engineer team to discuss findings
