### ISSUE TITLE
Update style guide to spell out March instead of abbreviating

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21233]
## Issue Description
We are going to adhere to AP style when it comes to abbreviating months in running text. That means that only January, February, August, September, October, November, and December should be abbreviated. In our style guide we currently also abbreviate March, so we need to remove this.

## Tasks
- [x] Delete March as a month that gets abbreviated on our pages 
- [x] Review and publish

## Acceptance Criteria
- [x] March removed from style guide abbreviations

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Approved and merged - thank you!

**Comment by RLHecht** [comment]
This work has been validated on live site. Closing ticket.
