### ISSUE TITLE
Conduct Vet Center Taxonomy research

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21237]
## Issue Description
Conduct Vet Center taxonomy research as planned in Vet Center Taxonomy - research plan #12441 

---
## Tasks
- [ ] Conduct research

## Acceptance Criteria
- [ ] Optimal sort survey results
- [ ] Notes as applicable

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This research will be conducted using optimal sort and this issue is no longer needed
