### ISSUE TITLE
TUD: Update account type column to id_type

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#21245]
## Issue Description
As a TUD developer, I would like to ensure the data is reading the correct property (from `Account Type` to `ID Type`), so that the information displayed to the user is more useful.

---
## Tasks
- [x] Update column property from `Account Type` to `ID Type`
- [x] Ensure filters work as intended

## Acceptance Criteria
- [x] I can filter by `Account Type` (one of DS Logon, MHV, or ID.me)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
