### ISSUE TITLE
TUD - Review & Refactor Non-Production Environmental Variable Use

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#21248]
## Issue Description
In order to make sure that the TUD api endpoint and account login/logout jobs are only present in non-production environments a review of the vets-api staging environment is required and if necessary the production environmental variable checks should be refactored.

---
## Tasks
- [x] Investigation of vets-api staging environment to establish what environmental variables it has set
- [x] Refactor of tud-api environmental variable checks to enable the module's features for staging but disable them for production

## Acceptance Criteria
- [x] The tud-api will function properly for staging.va.gov but not on production.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
Staging does not appear to have its `RAILS_ENV` set as production; as such no action or refactoring should be needed.
