### ISSUE TITLE
FL: Firing of error handling before focus 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21253]
## Issue Description
As a Veteran using Facility Locator, I need to know when I've made a mistake entering my search parameters so that I resolve the error. 

When we implemented the new error messages, we changed the timing for field validation. Error handling for all required fields now fires following **any** interaction. This can be disruptive to Veterans using screenreaders since the error may be announced for a field without focus. Users should have a chance to see/hear the options and have an opportunity to make a selection before the error is thrown. This is important for assistive tech users and users with cognitive challenges because we don't want to interrupt their flow unless absolutely necessary.

### Examples of current (wrong) behavior:

1. Visit https://staging.va.gov/find-locations/
2. Zoom in on the map 
3. Observe errors for City, state, postal code and Facility type fields are thrown without receiving focus. 

- Enter a character in the location field, and note the Facility type field error shows right away.

---
## Tasks
- [x] Revisit error handling 

## Acceptance Criteria
- [x] Error handling **should** be fired when a required field loses focus and no input has been entered/selected 
- [x] Error handling should **not** be fired before a field receives focus 
- [x] Error handling should **not** be fired if a field is populated before it loses keyboard focus
- [x] Errors should be related to the field with focus
- [x] If the user searches prior to populating any field, the error should be triggered for the City, state, postal code field
- [x] Search will not execute unless search criteria are valid (required fields are populated). This includes both the Search and Search This Area buttons. If "Search" is clicked with invalid form, an error should be displayed, and the focus should be set to the field with the error. (Note: clicking "search this area" does not require the user to enter a location - the location is determined automatically.)

**Comment by brangi** [comment]
issue - https://recordit.co/dmjJ6ZXVvB

**Comment by mmiddaugh** [comment]
Much more polite!
