### ISSUE TITLE
MVP Release for Liquid Template Unit Testing Framework

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#21258]
# Description 
Given the research and proof of concept outlined in this [ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/19291), VSP will implement an MVP of  a Liquid Template Unit Testing Framework.

# Tasks
- [x] Define a minimal framework that supports the core functions of the liquid template implementation on the platform
- [x] Verify that the framework is capable of testing some representative subset of liquid templates
- [x] Work with stakeholders to verify that the MVP fulfills the core of their requirements

**Comment by holdenhinkle** [comment]
Hey @mpelzsherman and @ncksllvn, we started this new ticket for the mvp.

Links:
Feature branch - https://github.com/department-of-veterans-affairs/vets-website/compare/19291_unit_test_liquid_templates
Research ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/19291

**Comment by holdenhinkle** [comment]
The `src/site/layouts/health_care_region_page.drupal.liquid` template seems to be building correctly with all nested templates (the templates referenced by `include`) and the dynamic content is populating correctly from [`src/site/tests/fixtures/health_care_region_page.json`](https://github.com/department-of-veterans-affairs/vets-website/blob/74c95cf9cd96690ea53c00c8f137f79fc8db48ea/src/site/tests/fixtures/health_care_region_page.json).

To-do:
- From Nick: "Quick glance I think we only need the `rewriteVaDomains`, `rewriteAWSUrls`, and the `modifyDom` steps."
- Confirm the filters are working

**Comment by holdenhinkle** [comment]
I made good progress this afternoon since my last post and I think I'm 98% done (although I could be wrong :-) ).

I imported the following in to `src/site/tests/support/index.js`:
- `import createRedirects from '../../stages/build/plugins/rewrite-va-domains.js';`
- `import rewriteAWSUrls from '../../stages/build/plugins/rewrite-cms-aws-urls.js';`
- `import modifyDom from '../../stages/build/plugins/modify-dom';`

And created a function called `updateHTML()`:

```
const updateHTML = files => {
  const options = {
    buildtype: process.env.BUILDTYPE, // what should i set this to?
    // what should the following values be?
    host: 'defaultHost',
    port: 3001,
    protocol: 'http',
  };

  options.hostUrl = `${options.protocol}://${options.host}${
    options.port && options.port !== 80 ? `:${options.port}` : ''
  }`;

  options.domainReplacements = [
    { from: 'https://www\\.va\\.gov', to: options.hostUrl },
  ];

  const done = () => {
    // to-do: recreate the done function
  };

  createRedirects(options)(files, null, done);
  rewriteAWSUrls(options)(files, null, done);
  modifyDom(options)(files, null, done);
};
```

I need to update some of the `options` values and recreate the `done()` function, which I think is a `metalsmith` function that's passed as a callback to the functions that `createRedirects`, `rewriteAWSUrls`, `modifyDom` return when they're called.

I'm getting the following error when running when tests now:

```
Uncaught Error: file-manifest.json (generated by Webpack) not found!
```

It's coming from `src/site/stages/build/plugins/modify-dom/process-entry-names.js`, `getEntryNamesDictionary()`. I'll look into that tomorrow.

I'm meeting with Nick tomorrow afternoon.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/16337

This is complete.

Nick Sullivan wants to be able to run `axe-checks` on `liquid` templates. I'll create a ticket for that.

**Comment by holdenhinkle** [comment]
This was merged this morning.

**Comment by pjhill** [comment]
Nice work!
