### ISSUE TITLE
Misalignment of error messages (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21263]
## Issue Description
When the user makes a Facility or Service type mistake, the error message causes a visual misalignment of the fields. 
![image](https://user-images.githubusercontent.com/55411834/110543165-329eca00-80e7-11eb-991e-f4086a2c81db.png)

---
## Tasks
- [ ] Identify options for visually aligned error handling (staying consistent with the design system)

## Acceptance Criteria
- [ ] Error messages do not cause Facility Locator search fields to be visually misaligned. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
