### ISSUE TITLE
[Design] Initial mockups for communications permissions

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21265]
## Background

Discovery in #20867.

Now that Liz has a chance to complete discovery, we're ready to create preliminary mockups.

## Tasks

- [x] Add additional info to this ticket if necessary
- [x] Create initial mockups
- [x] Review internally with team and get feedback

Next steps beyond this: Design collaboration with VSP and review with Terry.

**Comment by andaleliz** [comment]
@Samara-Strauss I've updated the mock-ups based on our conversation and [placed them in a Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1616001821140/563f6d0c6a34a52a5708552575b024fdb98e9bfe) for our discussion next Tuesday w/ the VA Profile team.  I think this initial phase can be closed out once I make desktop versions (won't take long), but I'll wait to hear back from you in case there are still any changes you'd like to see. 

IMO, I think both the `read/edit` and `autosave` versions could work.  I see the read/edit option as a bit more "futureproof" in the face of all the unknowns.  However, given our convo yesterday and knowing we'll likely have to re-work this no matter what, I'm good w/ the autosave version too. 


**What I updated:**
- added groups to all variations
- explored a different treatment for the contact info at the top of the page. I like this new version better, and for the sake of simplicity, I think it's best to keep the edit functionality out for now.
- created a non-accordion, auto-save option

I explored the horizontal alignment of checkboxes, and don't recommend this. I added details in the mural board, but it has some a11y problems and goes against our own design system recommendation.  We don't do this anywhere else on the site either.  I also revisited the findings from our mobile month study; we didn't see any major usability problems caused by scrolling. I think the vertical alignment will be fine if we go that route.

**Comment by Samara-Strauss** [comment]
### Overall thoughts & feedback

Overall, both versions are looking a lot cleaner!

> IMO, I think both the read/edit and autosave versions could work. I see the read/edit option as a bit more "futureproof" in the face of all the unknowns. 

I'm not sure which way to go, either, at this point. I think we can get helpful insight from the design intent collab, the VAOS team, and then the design team as a whole. I would recommend bringing these preliminary designs to your Monday design team meeting after we've shared in the design intent collab.

> I explored the horizontal alignment of checkboxes, and don't recommend this. I added details in the mural board, but it has some a11y problems and goes against our own design system recommendation.

Totally fine, and thanks for letting me know!

### Autosave design thoughts and feedback

- We should just link to the contact information section instead of having an FAQ. FAQs are more for additional context or to give info on things that can’t happen on VA.gov (eg. Updating your military info). My guess is we would just tell them in the FAQ to go to the contact information section of the profile, so we can eliminate a click by elevating this link in the first place.
- Should we remove the unsubscribe-to-all option? This feels risky given that it’s kind of separate from the actual forms instead of an integrated check/uncheck all boxes within the forms.

### Read-only/edit design thoughts and feedback

- This should have the same treatment of contact info as the autosave version. I do think the autosave version is an improvement re: contact info given that we don't want to put stuff in the table-style that is editable in one place and then not editable in another. That would cause an inconsistency in our pattern and might cause confusion given that the information is actually changable.

**Comment by andaleliz** [comment]
>We should just link to the contact information section instead of having an FAQ. FAQs are more for additional context or to give info on things that can’t happen on VA.gov (eg. Updating your military info). My guess is we would just tell them in the FAQ to go to the contact information section of the profile, so we can eliminate a click by elevating this link in the first place

That works for me. The only additional info I thought would go in there is a clarification that they can't have a separate email/mobile number for notifications, and we're going to use whatever they have in their main profile.  Let's link it for now and see what kind of questions (if any) arise once we have this in front of veterans.

>Should we remove the unsubscribe-to-all option?

Yes, let's do that for now. We can also have an "unsubscribe from all in this group" option, but that feels like something we can address when we actually have a need to because we have multiple notification options.  If our MVP launches with a small amount as we suspect, this will likely not be a UX hurdle people encounter immediately.

>This should have the same treatment of contact info as the autosave version.

Agree, and glad you agree that it is an improvement.

I've updated the [mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1616001821140/563f6d0c6a34a52a5708552575b024fdb98e9bfe) and will include future edits in the next round.

**Comment by Samara-Strauss** [comment]
This looks great! Great work, Liz!
