### ISSUE TITLE
[Design] Initial mockups for preferred facility

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21267]
## Background

Discovery in #20866.

Now that Liz has a chance to complete discovery, we're ready to create preliminary mockups.

## Tasks

- [x] Add additional info to this ticket if necessary
- [x] Create initial mockups
- [ ] Review internally with team and get feedback

Next steps beyond this: Design collaboration with VSP and review with VAOS team.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss , I put together [a mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1615571726513/f79a3cacb33c92a95cb8f013d085fd6390581b1e) with mock-ups and a possible flow.  I reviewed these with Tressa and Josh for a gut check/a11y check, and would love to get your thoughts on it before I move forward.  

I'm guessing we should have a quick meeting to discuss once you've had a chance to take a look, but happy to receive async feedback if that's better for you.  Thanks!

**Comment by Samara-Strauss** [comment]
Hey! Let's definitely meet to talk about this (nothing wrong, I just think that will be easier). I'll set up some time for us.

**Comment by Samara-Strauss** [comment]
Also want to bring in @ajakabcin to this discussion!

**Comment by andaleliz** [comment]
Sounds good! I agree that will be easier as well.  I'd also like to loop in the devs soon, but I think it'll be a better use of their time once we have something more refined (including desktop screens too).

**Comment by Samara-Strauss** [comment]
Great! I put some time on for Thursday morning, as we didn't have any overlapping time tomorrow.

**Comment by andaleliz** [comment]
@erikphansen, @sanlouise, and @lihanli  I'd love to get your feedback on the screens in[ this prototype](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/137549770/documentation/no-panels?mode=i) to add facilities to profile.   A few notes:

- Samara and I discussed that this section of profile will be available to users with healthcare benefits.

- Most of the prototype has some interaction wired up for the edit + show more buttons.  The last screen covers the "user has healthcare but no registered facilities" use case; you'll have to manually navigate to see that one.

- I added some notes in the documentation tab (should be open when you click that link). Once you've had a chance to review, let me know - maybe we can set aside 15 minutes so I can get your thoughts? Async works as well (either here or via the comment feature in UX Pin) if that is better for you.

Generally, I'm following the same patterns in profile and am not introducing anything outlandish. I believe we have access to all the data I've represented here too (oh how I wish MPI would give us access to date info!! 😭 ).  Once we're all aligned on this, I'll work on desktop screens and then share w/ the VAOS team to get their input. Thanks in advance for your feedback!

**Comment by erikphansen** [comment]
@andaleliz

- the prototype references VAOS a few times. How might I see what VAOS has done on staging?
- I registered so I could comment on the mock itself. But it looks like I might have to pay or get added to a team or something so that my trial doesn't expire?

**Comment by erikphansen** [comment]
@lihanli I know we get the list of facilities as part of the `GET user/` call. Do we have a different API to use for managing which facilities the user has chosen to hide?

**Comment by Samara-Strauss** [comment]
@erikphansen [here are the staging users for VAOS](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md).

**Comment by andaleliz** [comment]
>the prototype references VAOS a few times. How might I see what VAOS has done on staging?

Great question! I've attached a video here, and I'll link to it in the docs as well.  

I'm glad you got UXPin figured out; if it is problematic at all, we can figure out another way.

https://user-images.githubusercontent.com/55992116/111673504-6ff30e00-87f1-11eb-93cf-87dbc4b5a353.mov

**Comment by erikphansen** [comment]
Yes I'd love to chat about this at some point since this is all new to me and have questions about how this should all work, especially since it seems like VAOS will be hooking into the changes a user makes on their Profile.

**Comment by andaleliz** [comment]
Cool - set aside time on the calendar for a discussion tomorrow.  [Here's a link to the product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/README.md), in case you haven't seen it. That may answer some questions for you.

**Comment by Samara-Strauss** [comment]
@andaleliz I mentioned this in Slack as well, but I can't make the meeting tomorrow due to a conflict. I think you're a-ok, though, to have that call without me. Keep me posted on how it goes!

**Comment by andaleliz** [comment]
I synced with Danielle but haven't received her content yet and need to wrap up for today. She said she'd be able to get me some content prior to our meeting with VAOS tomorrow, so I've updated #21841 to include updating content.

Going to close this out since the sprint is over and we did complete [initial mockups](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/137549770/simulate/sitemap?mode=i)

**Comment by Samara-Strauss** [comment]
Sounds great! Great work!
