### ISSUE TITLE
[Cheetah MVP] Calendar & Review content updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21273]
## Issue Description
Update calendar and review pages based on user testing.

---
## Tasks
- [ ] Calendar page content

- [ ] Review page content

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] CONTENT - Copy on the Calendar page matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/VAOS_for_Distribution_Copy-calendar.docx)

- [ ] CONTENT - Copy on the Review page matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/VAOS_for_Distribution_Copy-review.docx)

## Definition of Done

- [ ] All acceptance criteria is met

- [ ] Flow [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) and screenshots are updated

**Comment by jbalboni** [comment]
@laurenernest Is this what you were looking for? It's not a pattern we normally use in our forms, as far as I know:

![Screen Shot 2021-03-15 at 1.49.53 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/b0e58f56-1938-4c91-81bd-c8f02dd71dc0)

**Comment by laurenernest** [comment]
Yep, this is what we're looking for this round of updates. Thanks!
