### ISSUE TITLE
Rebuild Test Cases Based on Current Statuses

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21271]
## Background
Now that we know what dependents are all associated with which test Veterans, we can test the removals of various dependents so those test will be complete.

## Tasks
- [x] Schedule time to get together
- [x] Complete test cases for the removal of various workflows:
  - Removal of a child due to marriage
  - Step-child has left the household
  - School age has left the household for school
  -  etc

## Acceptance Criteria
- [x] Test cases are outlined with expected outcomes

**Next steps**
- Determine what cases are left that need to be wiped
- Ask for EP codes/dependents to be wiped
