### ISSUE TITLE
[VAMC] VISN-17 "VA Northwest Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21283]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-5](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook 
- [ ] Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Have Tugboat environments built and launch sites. -	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Facility based fixes
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership

**Systems included in upgrade**
- [ ] VA Alaska health care
- [ ] VA Boise health care
- [ ] VA Portland health care
- [ ] VA Puget Sound health care
- [ ] VA Roseburg health care
- [ ] VA Southern Oregon health care
- [ ] VA Spokane health care
- [ ] VA Wallawalla health care

* Facilities for this VISN (by System)
VA Alaska health care
- [ ] 463GC	Mat-Su VA Clinic
- [ ] 463	Anchorage VA Medical Center
- [ ] 463GA	Fairbanks VA Clinic
- [ ] 463GB	Kenai VA Clinic
- [ ] 463GE	Juneau VA Clinic

VA Boise health care
- [ ] 531	Boise VA Medical Center
- [ ] 531GE	Twin Falls VA Clinic
- [ ] 531GG	Caldwell VA Clinic
- [ ] 531GH	Burns VA Clinic
- [ ] 531GI	Mountain Home VA Clinic
- [ ] 531GJ	Salmon VA Clinic

VA Portland health care
- [ ] 648	Portland VA Medical Center
- [ ] 648A4	Portland VA Medical Center-Vancouver
- [ ] 648GA	Bend VA Clinic
- [ ] 648GB	Salem VA Clinic
- [ ] 648GD	North Coast VA Clinic
- [ ] 648GE	Fairview VA Clinic
- [ ] 648GF	Hillsboro VA Clinic
- [ ] 648GG	West Linn VA Clinic
- [ ] 648GH	Newport VA Clinic
- [ ] 648GH01	Lincoln City Clinic
- [ ] 648GI	Portland VA Clinic
- [ ] 648GJ	Loren R. Kaufman VA Clinic

VA Puget Sound health care
- [ ] 663	Seattle VA Medical Center
- [ ] 663A4	American Lake VA Medical Center
- [ ] 663GA	Bellevue VA Clinic
- [ ] 663GA01	Federal Way CBOC (Valor Healthcare)
- [ ] 663GA02	North Seattle CBOC (Valor Healthcare)
- [ ] 663GB	Bremerton VA Clinic
- [ ] 663GC	Mount Vernon VA Clinic
- [ ] 663GD	South Sound VA Clinic
- [ ] 663GE	North Olympic Peninsula VA Clinic

VA Roseburg health care
- [ ] 653	Roseburg VA Medical Center
- [ ] 653BY	Eugene VA Clinic
- [ ] 653GA	North Bend VA Clinic
- [ ] 653GB	Brookings VA Clinic
- [ ] 653QA	Downtown Eugene VA Clinic

VA Southern Oregon health care
- [ ] 692	White City VA Medical Center
- [ ] 692GA	Klamath Falls VA Clinic
- [ ] 692GB	Grants Pass VA Clinic

VA Spokane health care
- [ ] 668	Mann-Grandstaff VA Medical Center
- [ ] 668GA	Wenatchee VA Clinic
- [ ] 668GB	Coeur d 'Alene VA Clinic
- [ ] 668QB	Libby VA Clinic
- [ ] 668QD	Sandpoint VA Clinic

VA Wallawalla health care
- [ ] 687	Jonathan M. Wainwright Memorial VA Medical Center
- [ ] 687GA	Richland VA Clinic
- [ ] 687GB	Lewiston VA Clinic
- [ ] 687GC	La Grande VA Clinic
- [ ] 687HA	Yakima VA Clinic
- [ ] 687QB	Morrow County VA Clinic
- [ ] 687QC	Wallowa County VA Clinic
