### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK for VA Memphis health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21282]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Memphis healthcare system Legacy Site](https://www.memphis.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-09 Playbook locations](https://drive.google.com/drive/folders/1U3pzj-0dp_7U1pqjDwEftJvMk2hFRPTR)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_614	Memphis VA Medical Center
- [x] vha_614GA	Tupelo VA Clinic
- [x] vha_614GB	Jonesboro VA Clinic
- [x] vha_614GC	Holly Springs VA Clinic
- [x] vha_614GD	Savannah VA Clinic
- [x] vha_614GE	Covington VA Clinic
- [x] vha_614GF	Nonconnah Boulevard VA Clinic
- [x] vha_614GG	Jackson VA Clinic
- [x] vha_614GI	Dyersburg VA Clinic
- [x] vha_614GN	Helena VA Clinic
- [x] vha_614QA	Union Avenue VA Clinic

* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#21282 - Create new Health Services "LIST, PLAYBOOK for VA Memphis health care [BA] - Completed and moved to Validate
