### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK for VA Mountain Home health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21284]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Mountain Home healthcare system Legacy Site](https://www.mountainhome.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-09 Playbook locations](https://drive.google.com/drive/folders/1U3pzj-0dp_7U1pqjDwEftJvMk2hFRPTR)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_621	James H. Quillen Department of Veterans Affairs Medical Center
- [x] vha_621BY	William C. Tallent Department of Veterans Affairs Outpatient Clinic
- [x] vha_621GA	Rogersville VA Clinic
- [x] vha_621GC	Norton VA Clinic
- [x] vha_621GG	Morristown VA Clinic
- [x] vha_621GI	Dannie A. Carr Veterans Outpatient Clinic
- [x] vha_621GJ	Bristol VA Clinic
- [x] vha_621GK	Campbell County VA Clinic
- [x] vha_621GO	Mountain City VA Clinic
- [x] vha_621QA	Jonesville VA Clinic
- [x] vha_621QB	Marion VA Clinic
- [x] vha_621QC	Vansant VA Clinic
- [x] vha_621QD	Knox County VA Clinic
- [x] vha_621QE	Downtown West VA Clinic
- [x] vha_621QF	Johnson City VA Clinic

* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#21284 Create new Health Services "LIST, PLAYBOOK for VA Mountain Home health care [BA] - Completed and moved to Validate
