### ISSUE TITLE
[VAMC] VISN-09: "VA MidSouth Healthcare Network" - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21286]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-5](https://drive.google.com/drive/folders/1R3aKP4Dm5vmEJljqQ61xYCgUJci-bT34)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Lexington health care
- [ ] VA Louisville health care
- [ ] VA Memphis health care
- [ ] VA Mountain Home health care
- [ ] VA Tennessee Valley health care

Facilities include for System:
VA Lexington health care
- [ ] vha_596	Franklin R. Sousley Campus
- [ ] vha_596A4	Troy Bowling Campus
- [ ] vha_596GA	Somerset VA Clinic
- [ ] vha_596GB	Morehead VA Clinic
- [ ] vha_596GC	Hazard VA Clinic
- [ ] vha_596GD	Berea VA Clinic

VA Louisville health care
- [ ] vha_603	Robley Rex Department of Veterans Affairs Medical Center
- [ ] vha_603GA	Fort Knox VA Clinic
- [ ] vha_603GB	New Albany VA Clinic
- [ ] vha_603GC	Shively VA Clinic
- [ ] vha_603GD	Stonybrook VA Clinic
- [ ] vha_603GE	Newburg VA Clinic
- [ ] vha_603GF	Grayson County VA Clinic
- [ ] vha_603GG	Scott County VA Clinic
- [ ] vha_603GH	Carrollton VA Clinic

VA Memphis health care
- [ ] vha_614	Memphis VA Medical Center
- [ ] vha_614GA	Tupelo VA Clinic
- [ ] vha_614GB	Jonesboro VA Clinic
- [ ] vha_614GC	Holly Springs VA Clinic
- [ ] vha_614GD	Savannah VA Clinic
- [ ] vha_614GE	Covington VA Clinic
- [ ] vha_614GF	Nonconnah Boulevard VA Clinic
- [ ] vha_614GG	Jackson VA Clinic
- [ ] vha_614GI	Dyersburg VA Clinic
- [ ] vha_614GN	Helena VA Clinic
- [ ] vha_614QA	Union Avenue VA Clinic

VA Mountain Home health care
- [ ] vha_621	James H. Quillen Department of Veterans Affairs Medical Center
- [ ] vha_621BY	William C. Tallent Department of Veterans Affairs Outpatient Clinic
- [ ] vha_621GA	Rogersville VA Clinic
- [ ] vha_621GC	Norton VA Clinic
- [ ] vha_621GG	Morristown VA Clinic
- [ ] vha_621GI	Dannie A. Carr Veterans Outpatient Clinic
- [ ] vha_621GJ	Bristol VA Clinic
- [ ] vha_621GK	Campbell County VA Clinic
- [ ] vha_621GO	Mountain City VA Clinic
- [ ] vha_621QA	Jonesville VA Clinic
- [ ] vha_621QB	Marion VA Clinic
- [ ] vha_621QC	Vansant VA Clinic
- [ ] vha_621QD	Knox County VA Clinic
- [ ] vha_621QE	Downtown West VA Clinic
- [ ] vha_621QF	Johnson City VA Clinic

VA Tennessee Valley health care
- [ ] vha_626	Nashville VA Medical Center
- [ ] vha_626A4	Alvin C. York Veterans' Administration Medical Center
- [ ] vha_626GA	Dover VA Clinic
- [ ] vha_626GC	Bowling Green VA Clinic
- [ ] vha_626GE	Clarksville VA Clinic
- [ ] vha_626GF	Chattanooga VA Clinic
- [ ] vha_626GG	Tullahoma VA Clinic
- [ ] vha_626GH	Cookeville VA Clinic
- [ ] vha_626GJ	Hopkinsville VA Clinic
- [ ] vha_626GK	McMinnville VA Clinic
- [ ] vha_626GL	Roane County VA Clinic
- [ ] vha_626GM	Maury County VA Clinic
- [ ] vha_626GN	Athens VA Clinic
- [ ] vha_626GO	International Plaza VA Clinic
- [ ] vha_626GP	Gallatin VA Clinic
- [ ] vha_626QA	Albion Street VA Clinic
- [ ] vha_626QB	Charlotte Avenue VA Clinic
- [ ] vha_626QC	Pointe Centre VA Clinic
- [ ] vha_626QD	Glenis Drive VA Clinic
- [ ] vha_626QE	Glenis Drive 2 VA Clinic
- [ ] vha_626QF	Dalton Drive VA Clinic
