### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST, PLAYBOOK for VA Tennessee Valley health care [BA] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21285]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Tennessee Valley healthcare system Legacy Site](https://www.tennesseevalley.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-09 Playbook locations](https://drive.google.com/drive/folders/1U3pzj-0dp_7U1pqjDwEftJvMk2hFRPTR)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_626	Nashville VA Medical Center
- [x] vha_626A4	Alvin C. York Veterans' Administration Medical Center
- [x] vha_626GA	Dover VA Clinic
- [x] vha_626GC	Bowling Green VA Clinic
- [x] vha_626GE	Clarksville VA Clinic
- [x] vha_626GF	Chattanooga VA Clinic
- [x] vha_626GG	Tullahoma VA Clinic
- [x] vha_626GH	Cookeville VA Clinic
- [x] vha_626GJ	Hopkinsville VA Clinic
- [x] vha_626GK	McMinnville VA Clinic
- [x] vha_626GL	Roane County VA Clinic
- [x] vha_626GM	Maury County VA Clinic
- [x] vha_626GN	Athens VA Clinic
- [x] vha_626GO	International Plaza VA Clinic
- [x] vha_626GP	Gallatin VA Clinic
- [x] vha_626QA	Albion Street VA Clinic
- [x] vha_626QB	Charlotte Avenue VA Clinic
- [x] vha_626QC	Pointe Centre VA Clinic
- [x] vha_626QD	Glenis Drive VA Clinic
- [x] vha_626QE	Glenis Drive 2 VA Clinic
- [x] vha_626QF	Dalton Drive VA Clinic

* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#21285 Create new Health Services "LIST, PLAYBOOK for VA Tennessee Valley health care [BA] - Completed and moved to Validate
