### ISSUE TITLE
[VAMC] Prepare Durham-health-care for Dual-state [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21291]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Durham Tugboat Instance](https://web-ibyxbqdzwszauav2xkjp5wjodkulx3o2.demo.cms.va.gov/Durham-health-care/)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system

**Comment by ltrombley** [comment]
#21291 Prepare Durham-health-care for Dual-state is complete Pending resolution of Tugboat Broken links.
![image.png](https://images.zenhubusercontent.com/5db87b80412896000151c17e/d66a12de-9e4e-4a2b-a5f4-d170e9a690d5)
