### ISSUE TITLE
[VAMC-Scaffolds] Create or Clone all required pages for VA Orlando health care in VISN 8 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21301]
## User Story 
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required VAMC-upgraded va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Menu and Page checklist](https://drive.google.com/drive/folders/1QliZFSkQHEruGgjOGRihG8tohYxswjm1)
[Clonable Website](Salt-lake-city-health-care)

## Tasks
_Creation of the following Drupal types/menus and pages_
* All pages are cloned or created, the System name, Related office or Health Care system, Owner, Meta title, Meta Description, and Menu items are updated.

**1st Step: Go into Manage, Content, and click on Menus**
_Find VA [SYSTEM NAME] (listed alphabetically) that you are cloning in the menu list and select "Edit"
_using the blue button "+add link" add the following "nolink" (See instructions about "nolink" menu link titles:
- [x] SERVICES AND LOCATIONS (Link: "nolink" / uncheck "enabled checkbox")
- [x] NEWS AND EVENTS (Link: "nolink" / uncheck "enabled checkbox")
- [x] ABOUT VA "Short System Name" (e.g.:ALTOONA) (Link: "nolink" / uncheck "enabled checkbox")

**CLONING Clone from Salt Lake City of Sheridan Communicate on VAMC-upgrade channel**

** Clone or create these Listing pages and Add to Menu just below SERVICES AND LOCATIONS 
- [x]  Health Services Listing Page
- [x]  Locations Listing Page
_

* Find the following facilities and make sure they are associated under the correct system and owner
- [x] Validate these sites are matched in VAST DB and Playlist, then move under [System]
** Add facility pages to Menu under "Locations" (Listing page)
- [x] Orlando VA Medical Center
- [x] Viera VA Clinic
- [x] William V. Chappell, Jr. Veterans' Outpatient Clinic
- [x] Kissimmee VA Clinic
- [x] Deltona VA Clinic
- [x] Tavares VA Clinic
- [x] Clermont VA Clinic
- [x] Lake Baldwin VA Clinic
- [x] Crossroads VA Clinic
- [x] Palm Bay VA Clinic
- [x] Port Orange VA Clinic
- [x] Westside Pavilion VA Clinic
- [x] Orlando 1 VA Mobile Clinic

**CLONING Clone from Salt Lake City or Sheridan Communicate on VAMC-upgrade channel**
_
** Top task items listed below require "DISABLED" menu items associated to them**
Place disabled menu items below --[System Name] "DISABLED"
- [x]  Make an appointment
- [x]  Register for care
- [x]  Billing and insurance
- [x]  Dav-vans transportation for veterans
- [x]  Medical records
- [x]  Pharmacy
- [x]  [System Name] - Campus map
- [x]  Chaplain services

** Items below require "DISABLED" menu items associated to them**
Place disabled menu items below "Health Services" (listing page)
- [x]  Caregiver support
- [x]  Homeless Veteran care
- [x]  LGBT Veteran care
- [x]  Suicide prevention
- [x]  Mental health care
- [x]  Minority Veteran care
- [x]  Patient advocates
- [x]  Returning service member care
- [x]  Women Veteran care

**Items below require "ENABLED" menu items associated to them**

*NEW SECTION:*
Clone the below page from previously used (Salt-Lake-City or Sheridan)
_
* The following pages are linked in Menu under ABOUT VA [System Name]
- [x]  About us
- [x]  Work with Us
- [x]  Policies
- [x]  Contact us 

* Add these pages to Menu under About us 
- [x]  Mission-Vision 
- [x]  History 
- [x]  Performance 
- [x]  Leadership (Listing Page)
    
* Add these pages to Menu under Work with Us    
- [x]  Jobs and Careers
- [x]  Internship and Fellowship 
- [x]  Volunteer and Donate 
   
**NEW SECTION** - more listing pages**

* Add these pages to Menu under NEWS AND EVENTS
- [x] Event Listing Page 
- [x] News Releases Listing Page
- [x] Stories Listing Page 

## Acceptance Criteria
- [x]  Validation that all pages created and assigned to the correct SYSTEM. (review in SYSTEM lookup page and take inventory.
- [x]  Validate that all menu pages show up in Menu and are visible in the correct order on the menu
- [x]  Validate that pages are ready to take data load information
- [x]  All system pages listed above have been created

**Comment by EdwardBoehme05** [comment]
Added these facilities to this ticket:
- [ ] Palm Bay VA Clinic
- [ ] Port Orange VA Clinic
- [ ] Westside Pavilion VA Clinic
- [ ] Orlando 1 VA Mobile Clinic

**Comment by EdwardBoehme05** [comment]
These facilities are in the VAST DB but are not included on the Orlando legacy site:
vha_675QB	Port Orange VA Clinic
vha_675QC	Westside Pavilion VA Clinic
vha_675QE	Orlando 1 VA Mobile Clinic
