### ISSUE TITLE
Documentation Site - Launch MVP

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2130]
## User Story

As a team member building or supporting products on VA.gov, I need to be able to access and navigate documentation so that I can find what I need on my own quickly and easily.

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)

- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- Number of documentation support requests per week

## Details and Notes

We created a myriad of documentation that was designed to help our customers (i.e. VFS teams building things on VA.gov) find what they need to work seamlessly and iteratively, and build great products on VA.gov. We have observed that the resources as they exist today aren’t effectively enabling that, which is causing a large support burden for VSP, is frustrating our customers, and is potentially resulting in products on VA.gov that don't meet VSP standards. _How might we improve our documentation resources so that our customers are more successful?_

### Links

**Product Outline:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/product-outline.md

### Goal(s)

- People can find what they need without having to ask
- Documentation is always up to date and canonical (and thus is trusted)
- People can start working quickly on their VA.gov products without huge ramp-up time
- VA.gov products meet VSP standards

### Assumptions and Hypotheses

We believe that **creating a single, searchable, public documentation site that is easy and understandable for VFS and VSP team members to use and maintain** will result in **a single source of truth for building on VA.gov that is robust and well maintained.** We will know we are successful when **we see contributions and traffic to the new documentation site rise, and documentation support requests decrease.**

## Areas for Discovery

See [discovery sprint details](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2227).

## Definition of Done

- [X] Discovery sprint completed to define MVP 
- [x] Consolidated documentation homepage ~with search functionality~ launched
- [x] MVP of feedback loop initiated
- [ ] Next steps captured as future epics and super epics

**Comment by rroueche** [comment]
I thought this was squarely a Content & IA team super epic, is there a reason FE Tools is on it as well?

@brandonrapp @meganhkelley

**Comment by meganhkelley** [comment]
@rroueche I think that's primarily a holdover bc FE Tools was so involved in current Gatsby docs. I'm fine with removing FE tools label if @brandonrapp is as well :thumbsup:

**Comment by brandonrapp** [comment]
We included it in ours as well because more than likely we would be the
development team that would support the implementation of any agreed upon
documentation tool. I am totally fine removing us from the ticket.

**Comment by rroueche** [comment]
@meganhkelley is the fe tools label here accurate? Our understanding is that Bill and Dan would help with this, but not necessarily any FE Tools team members.

**Comment by meganhkelley** [comment]
Sounds good to me! Removing now.

**Comment by vbellissimo** [comment]
Cancelling/old task.
