### ISSUE TITLE
[SD] Typeahead POC 2 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21316]
## Description
Our initial [typeahead POC ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8896)was expected to run for 4-6 weeks (Dec 23, 2020 - January 31, 2021) with a user base of 5% of all va.gov users after which time the plan was to assess the data collected and determine how effective the typeahead feature was at improving the experience for veterans. A variety of factors ([explained in more detail here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8896#issuecomment-795647840)) have blocked our ability to interpret the data from the POC and as a result we have decided to declare this POC inconclusive and reset the dates for this issue - a second POC which we believe will be more representative of the actual typeahead feature and its implications.

## Hypothesis or Bet
**If** _we offer a typeahead experience with relevant suggestions_ **then** _veterans will be able to access content they need in less time_.

## Background/Context/Resources
https://open.gsa.gov/api/searchgov-results/ - Main
https://open.gsa.gov/api/searchgov-clicks/ - Click tracking
https://open.gsa.gov/api/searchgov-suggestions/ - Typeahead

## Tasks

 - [x] Determine strategy to establish typeahead suggestion list
 - [x] Establish list of typeahead suggestions that should be added to suggestion database #21325 
 - [x] Validate list of typeahead suggestions (also on #21325)
 - [x] Address analytics fixes to account for when users are not presented with any typeahead suggestions #20889 
 - [x] Analytics team will reset date on [Typeahead DOMO Dashboard ](https://va-gov.domo.com/page/439942537?userId=1724393873)to represent data accurately for POC 2 _**Already done - March 23, 2021**_
 - [x]  **4/1** S+D team discuss final list & discuss POC 2 timeline + details (on #22497)
 - [x] Search.gov production API - Back End Implementations #21794 
 - [x]  **4/2** Send initial list to Search.gov who will add them to the suggestion database  #17844
 - [x] **4/6** Search.gov to implement 
 - [x] **4/7-4/9** Test integration - SD team to test experience  (also on #17844)
 - [x]  **4/7** Meet with Search.gov - discuss algorithm "logic levers" (Threshold + Deprecate) 
 - [x] **4/9** Denise to send Amani best bet terms
 - [x] **4/9-4/11** John to add best bets for suggestions (#22540)
 - [x] **4/12** John to notify Sam via slack to turn on feature toggle - 35% of users
 - [x] **4/12** Team to a quick sanity check once it is turned on - ensure it is working properly
 - [ ] **4/12** Check [Domo Dashboard](https://va-gov.domo.com/page/439942537?userId=1724393873) - we should see data after 24 hrs
 - [x] **4/12-25** - - - **POC2 will run - uninterrupted #22497** - - - 
 - [x] **4/15** In 11am meeting team will review dashboard data (see/discuss if everything is working as we expect) 
 - [x] **4/26** Denise/John will collect & summarize data from our Domo Dashboard
 - [x] **4/27** Team to review/discuss data & draw conclusions on effectiveness of typeahead feature #22091
 - [ ] **4/26-5/4** Transition to Search.gov production API - Front End Implementations #21793 
 - [x] **5/1** Determine plans for typeahead 1.0 #22930  
 

## Definition of done
- [ ] POC has run and data has been analyzed. 
- [ ] Plans for typeahead 1.0 have been defined

**Comment by denisecoveyduc** [comment]
POC2 Findings Summary - https://github.com/department-of-veterans-affairs/va.gov-team/issues/22091#issuecomment-848249600
