### ISSUE TITLE
Creating R&S single Q&As for information around eligibility for burial in a VA national cemetery

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21315]
## Issue Description
As part of our effort to move Tier 1 support content off of our benefit detail pages and into R&S we need to move specific content from the [eligibility for burial in a VA national cemetery](https://www.va.gov/burials-memorials/eligibility/) into new R&S single Q&As. 

Under the H2: More about VA burial benefits and planning, move these 4 questions as single Q&As into R&S:
- Can I be buried in Arlington National Cemetery?
- What does burial in a VA national cemetery include?
- Can I plan ahead for my burial in a VA national cemetery?
- How can I make sure my family members have all the information and documents they need to plan for the future?

Retain the existing H2 and each question (not answer) on the eligibility page. The question should link to the R&S Q&A.

Move this H3 to sit under the accordions within the H2 section called **Eligibility information for specific groups:**

**What should I do if I received an other than honorable, bad conduct, or dishonorable discharge?**
If you’ve received one of these discharge statuses, you may not be eligible for VA benefits.

There are 2 ways you can try to qualify:

[Find out how to apply for a discharge upgrade](https://www.va.gov/discharge-upgrade-instructions/)
[ Learn about the VA Character of Discharge review process](https://www.va.gov/discharge-upgrade-instructions/#other-options)

## Tasks
- [x] Create R&S single Q&As  (Selina)
- [x] Update burial eligibility page (Selina)
- [x] Review R&S Q&As (Randi/Beth)
- [x] Review updated eligibility page (Randi/Beth)
- [x] Send to stakeholders for review (Beth)
- [x] Complete R&S prepublish checklist (Randi)
- [x] Publish R&S articles and eligibility page
- [x] Add burials section to R&S landing page and publish

## Acceptance Criteria
- [x] R&S single Q&As created and eligibility page updated on live site

**Comment by brianalloyd** [comment]
@RLHecht I was able to figure out the issue and got this ticket connected to the Epic.  Let me know if you need anything else.

**Comment by RLHecht** [comment]
These pages minus the one about "How can I be sure my family has what they need to plan for the future?" have been published and articles added to landing page. The eligibility page has also been published with just the questions as links.

**Comment by bethpottsVADEPO** [comment]
@RLHecht We can close this, right?

**Comment by RLHecht** [comment]
@bethpottsVADEPO I had left it open for that one question that we didn't publish yet. I can close this ticket and create a separate one for if/when we decide to publish it.

**Comment by bethpottsVADEPO** [comment]
Sure, would you mind doing that? Thank you.
