### ISSUE TITLE
Establish list of typeahead suggestions

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21325]
## Description
Establish a list of VA relevant terms to be hardcoded to in search.gov typeahead suggestions database.

## Background/Context/Resources
Search.gov however resolved a bug fix which was preventing suggestions older than 30 days from being purged from the database. The Search & Discovery team was not aware of this bug and assumed that the search.gov algorithm was working as described. After the bug was resolved the database was purged which dropped the suggestion list down from 40,000 to 39 terms. [Blacklisting](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19763) was no longer required but instead we are pivoting our efforts to focus on establishing a list of terms that can be added to the suggestion database. We believe VA specific / targeted suggestions will improve the users ability to find relevant VA results.

## Tasks
- [x] Define Strategy for creating list of terms to be added to typeahead database
- [x] Megan + Denise to generate list - checking in during SU on progress
- [x] Merge columns into one list + De-dupe
- [x] Review list with Content team (incrementally) in Unauth Content/Design meetings
- [x] Validate that results match our expectations and that meaningful terms appear to users
- [x] Secondary check - Audit our top 2020 search terms to ensure we have quality suggestions for the most frequent searches
- [x] S+D team discuss final list + send to search.gov
- [x] Meet with Search.gov - discuss algorithm  "logic levers" (Threshold + Deprecate)  

|       |**Threshold**         |**Deprecate**| 
|-----------------------|------------------------------|------------------------------|
|**Description**            |the threshold for the number of identical queries needed in a day for something to turn into a suggestion |the window of time to deprecate an "old" suggestion.  |
|**Current**            |a query to hit 100 identical queries in a day, |30 days of not meeting that threshold |
|**Search.gov suggested** changes to improve the feel of "recency"        |~30 identical queries / day |within the last 5-7 days |
|**S+D Thoughts**             |40 identical queries/ day |15 days |

- [x] Validate list has been added and  is functioning as we expect

## Identified next steps:
- Consider best bests for resources + support topics

## Definition of Done
- [ ] Search.gov typeahead Suggestion Database has been hardcoded with a list of VA suggestions

**Comment by denisecoveyduc** [comment]
Strategy for creating list of typeahead suggestions has been established and can be found [here ](https://docs.google.com/spreadsheets/d/1GQMbACxz4y6nPuh7erJJx605fqoTVxxuquX_W3Oa5PM/edit#gid=1997340956) 

Screenshot:
<img width="671" alt="Screen Shot 2021-03-10 at 12 29 47 PM" src="https://user-images.githubusercontent.com/72393866/110671354-67208d80-819c-11eb-8cae-1bc8e0a04459.png">

**Comment by denisecoveyduc** [comment]
Resizing since the scope of work is much larger than anticipated

**Comment by denisecoveyduc** [comment]
4/7 - Met with Search.gov to finalize discussions and next steps
