### ISSUE TITLE
GitHub Actions - develop guidance for usage

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#21324]
## Description
We need to provide documented guidance for developers on how to use GitHub Actions

## Background/context/resources
WIP Doc here: https://vfs.atlassian.net/wiki/spaces/VI/pages/1147142190/Guidance+for+Github+Actions+use

---
## Tasks
- [x] Start a living document that provides guidance for GHA usage
- [x] Find a place for this to live where VFS teams can consume it

## Definition of Done
- [x] Development teams are informed of GHA best practice within our organization (ongoing)

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
There is a living document for GHA guidance. 

Closing.
