### ISSUE TITLE
Error state for manually entered invalid facility ID

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21347]
## Issue Description
If a user changes the facility number in the URL of a facility detail page to an invalid ID, everything between the header and footer disappears when the 404 error is returned.

https://user-images.githubusercontent.com/55411834/110682479-33dbff80-8198-11eb-8a04-5a11234edfc0.mov

## Steps to reproduce

1. Visit https://www.va.gov/find-locations
2. Perform a successful search and then click on the name of the first result to get a facility detail page **OR** Open a facility detail page using a bookmarked URL. 
3. Click into URL and change the facility ID to an invalid entry. 
4. Refresh page
5. Observe only the header and footer are rendered. 

---
## Tasks
- [ ] Implement a more specific error state for this scenario

## Acceptance Criteria
- [ ] User understands the cause of the error. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
with modernized pages, this will be irrelevant
