### ISSUE TITLE
Create R&S single Q&As around headstones, markers, and medallions information

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21341]
## Issue Description
In an effort to move tier 1 support content out of our benefit detail pages and into  R&S we need to remove some content from the [headstones, markers, and medallions page](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/) into single Q&As in R&S.

Under the H2: More information about headstones and markers, move these 6 questions as single Q&As into R&S:

Can I choose the type of headstone or marker?  READY TO PUBLISH
What information goes on the headstone or marker and who provides it? READY TO PUBLISH
When will the headstone or marker I requested arrive, and who will set it for me? READY TO PUBLISH
Does VA provide a memorial headstone or marker if remains aren’t available? READY TO PUBLISH
Can 2 Veterans who are married get separate headstones? READY TO PUBLISH
~Can I request a replacement headstone?~ -->Requesting a replacement headstone

Retain the existing H2 and each question (not answer) on the benefit detail page. The question should link to the R&S Q&A. The accordions will go away. What will remain will be text links (the questions).

**Note:** The question "Can I request a replacement headstone?" will need to be set up as an About page because the word count is too long for a single Q&A. Use the question format in tier 1 where you create the text links, then the H1 for the new About article will be: Requesting a replacement headstone.

## Tasks
- [x] Create R&S single Q&As and About article (Selina)
- [x] Update burials page (Selina)
- [x] Review R&S Q&As (Randi/Beth) 
- [x] Review updated burials page (Randi/Beth)
- [x] Send to stakeholders for review (Beth)
- [x] Complete R&S prepublish checklist (Randi)
- [x] Publish R&S articles and burials page (Randi)
- [x] Add Q&As to R&S landing page and publish (Randi)

## Acceptance Criteria
- [ ] R&S articles and updated burials page live on site

**Comment by RLHecht** [comment]
@bethpottsVADEPO These single Q&As and the About page have been created and the tier 1 page updated. I had to rewrite a few of the questions because they were over the character count. I was also having a hard time coming up with the CTAs so let me know what you think. For intro of the About page I basically rewrote the first sentence of the answer. I also thought we could just move that first sentence up into the intro and start the answer with just a one sentence lead-in to the bullet points. 

Here are the preview links:
preview-prod.vfs.va.gov/preview?nodeId=16587
preview-prod.vfs.va.gov/preview?nodeId=16588
preview-prod.vfs.va.gov/preview?nodeId=16589
preview-prod.vfs.va.gov/preview?nodeId=16590
preview-prod.vfs.va.gov/preview?nodeId=16591
preview-prod.vfs.va.gov/preview?nodeId=16592
preview-prod.vfs.va.gov/preview?nodeId=859

**Comment by RLHecht** [comment]
These pages are published as a multiple FAQ and About page. Closing ticket.
