### ISSUE TITLE
[Design] My VA: Appointments error message

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21369]
## Background

Original discussion in #21177.

We need an error message for the appointments if we can't load them. 

-  *If any of the VAOS appointment endpoints fail, do not show the section. (there's the potential that we would be showing the wrong appt) "Check back later" will work, "Refresh" won't work. (could potentially use the same message that's in profile)
- Erik and Sandra will look into downtime errors

## Tasks

- [x] Mock up design for appointments error
- [x] Review with team
- [ ] Work with copy
- [ ] Handoff to FE

**Comment by tressaellen** [comment]
Here's what I have for the errors message for appointments. @peggygannon or @bethpottsVADEPO could you take a look at the content and provide any recommendations?

**We couldn’t retrieve your appointment information**

We’re sorry.  Something went wrong on our end and we couldn’t access your contact information.  Please try again later or click the link below to go to the appointments tool.

[Schedule and view your appointments]

![Screen Shot 2021-03-17 at 12.28.44 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/01badec2-c28e-4811-b6c6-e4e42781e1e7)

**Comment by bethpottsVADEPO** [comment]
@tressaellen Thanks for looping me in! I will have time to look at this either Friday of this week or next Monday. Will that work?

**Comment by Samara-Strauss** [comment]
@tressaellen I have added the error state to [the frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md#next-appointment). I'll leave this ticket open since there are other folks involved, but let me know if you want to move all copy discussions to #21543 or if you'd like to leave the copy discussion for this ticket here. If all copy, including this, is being discussed in #21543, we can close this ticket.

**Comment by tressaellen** [comment]
Content will be tracked in #21872, so I'm closing this ticket.
