### ISSUE TITLE
[Design] My VA: Disability rating error message

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21367]
## Background

Original discussion in #21177.

We need an error message for the disability rating if we can't load it. Something similar to the existing name tag error but for disability rating.

## Tasks

- [ ] Mock up design for disability rating error
- [ ] Review with team
- [ ] Work with copy
- [ ] Handoff to FE

**Comment by Samara-Strauss** [comment]
Wondering if we should just not show this if we can't detect it instead of having a big, clunky error somewhere. But definitely open to ideas. This is just a thought.

**Comment by tressaellen** [comment]
I think that could work!  We could also mimic messages, and just downgrade it to a generic link to 'View disability rating', which could take users to [https://www.va.gov/disability/view-disability-rating/](https://www.va.gov/disability/view-disability-rating/ ) .

**Comment by Samara-Strauss** [comment]
> We could also mimic messages, and just downgrade it to a downgrade it to a generic link to 'View disability rating', which could take users to https://www.va.gov/disability/view-disability-rating/ .

YES! Let's do this!!

**Comment by Samara-Strauss** [comment]
@tressaellen let me know if ☝️ is the final decision, and I will get this into the documentation. We can close this ticket after that :D

**Comment by tressaellen** [comment]
@Samara-Strauss yep, that's the final decision! Thank you!

**Comment by Samara-Strauss** [comment]
Alright! I adjusted the mockup so I could get it [into the documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md), so let me know if it looks OK or needs updating. Otherwise, this should be good to close!

![Name tag with disability rating_error state](https://user-images.githubusercontent.com/34068740/112017071-a6879c00-8b03-11eb-9f8f-bdcd7a1d4ca2.jpg)
