### ISSUE TITLE
Move VTK to EKS

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#21364]
## Description
Set up terraform for ECS/Fargate deployment of VTK CLI middleware

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Set up user in AWS with correct permissions
- [ ] Set up Github Actions to build/push container to ECR
- [ ] Deploy service
- [ ] modify revproxy config to allow ingress/routing
- [ ] troubleshoot with Eric to get it all working

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Please refer to more current initiatives to improve the platform crew developer experience and adoption of Kubernetes for app hosting and deployment. 

Closing.
