### ISSUE TITLE
[Design] My VA: Messages error message

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21368]
## Background

Original discussion in #21177.

We need an error message for the disability rating if we can't load it. Something similar to the existing profile error but for messages.

## Tasks

- [ ] Mock up design for message error
- [ ] Review with team
- [ ] Work with copy
- [ ] Handoff to FE

**Comment by Samara-Strauss** [comment]
Question: Would a better handling of this be to just show a "View All Messages" link or something if we can't detect their unread messages? Definitely review that with FE, but this might be more elegant than an error messsage.

**Comment by tressaellen** [comment]
Oh this is a great idea... let me see if that could work.

**Comment by Samara-Strauss** [comment]
Keep me posted! That would be a better way to degrade gracefully without having to put errors all over everything.

**Comment by Samara-Strauss** [comment]
Sandra says this should work! [Slack comment](https://dsva.slack.com/archives/C909ZG2BB/p1615476418068500?thread_ts=1615476215.068200&cid=C909ZG2BB)

**Comment by Samara-Strauss** [comment]
Confirmed in #21375 that we don't need any other messaging down time messaging if we are going to degrade to an unpersonalized link in the event that we can't detect the number of unread messages.

**Comment by tressaellen** [comment]
Thanks for following up on this @Samara-Strauss ! I'm working with content now on the unpersonalized link and that will be tracked in [#21543](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21543)

![My VA Desktop 2 no messages.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/46fa47c9-a449-4a2f-a644-c333c6d25594)

**Comment by Samara-Strauss** [comment]
Sounds good! Thanks!

**Comment by Samara-Strauss** [comment]
@tressaellen I am going to close this unless you have any objection. This general error handling approach is documented [in the frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md#messages).

**Comment by Samara-Strauss** [comment]
...and I realize copy may not be totally final, but as you said, we can track that in #21543. If there are any UX changes, let me know and we can re-open this.
