### ISSUE TITLE
[FE] My VA: Look into downtime error handling for My VA

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21375]
## Background

Original conversation in #21177.

FE needs to look into how we will handle downtime errors for My VA.

## Tasks
- [x] Add necessary details to this ticket
- [x] Downtime errors research
    - [x] Are there service downtimes that'll prevent us from fetching Claims and/or Appeals?
    - [x] Are there service downtimes that'll prevent us from getting Appointments, Prescriptions, or Secure Messaging info?

**Comment by erikphansen** [comment]
## Claims and Appeals

Claims depends on `externalServices.mhv` and appeals depends on `externalServices.appeals`.

- If a user has access to both services and _one_ of those endpoints is down, we cannot show the section as intended. ie, we can't accurately determine what their latest claim or appeal is and might show them incorrect data. I'd recommend showing a message about the service being down and checking back at date/time the downtime is supposed to be over

- Same goes for if a user can only access claims or appeals. If the required service is down, I'd recommend showing a message about the service being down and checking back at date/time the downtime is supposed to be over

**Comment by erikphansen** [comment]
## Health Care

Both messaging and prescriptions depend on `externalServices.mvi` and `externalServices.mhv` We should show a message about the service being down and checking back at date/time the downtime is supposed to be over

Appointments? I'm not sure yet. @sanlouise do you know if VAOS features are wrapped in a DowntimeNotification component?

**Comment by erikphansen** [comment]
This is 75% done. Just need to determine what service(s) Appointments relies on!

**Comment by Samara-Strauss** [comment]
> Both messaging and prescriptions depend on externalServices.mvi and externalServices.mhv We should show a message about the service being down and checking back at date/time the downtime is supposed to be over

For health care, I thought this issue was more about figuring out what to do when the endpoint that tells us whether someone does or does not have health care is down. I was under the impression that we already agreed there needed to be some sort of error handling if appointments is down (#21369), we can just show a generic "View all messages" link instead of the personalized link for messages (#21368), and we probably don't need anything for prescriptions given that info is no longer going to be personalized in this version of My VA (#21403).

**Comment by erikphansen** [comment]
> For health care, I thought this issue was more about figuring out what to do when the endpoint that tells us whether someone does or does not have health care is down

This is a slightly different issue. Yes, there is a chance that when the Dashboard loads, we won't have the necessary data to even know if they are a VA Patient. (This would happen if the `GET user/` call is unable to get the "vaProfile" data.) In that case we need to show some kind of error in place of the Health Care section (I cannot find the ticket for this particular case...)

For handling known service outages, your points sound right:

- If MVI or MHV are down, it won't affect Prescriptions at all because we are never fetching any personal Prescription data
- If MVI or MHV are down, we can fall back to showing a generic "View all messages" link instead of a personalized link/latest message info.

**Comment by erikphansen** [comment]
## Appointments

This data relies on both `externalServices.vaos` and `externalServices.vaosWarning`. If the first is down, we cannot get appointments. If the second is down, we cannot guarantee the data we are getting is complete and thus cannot be sure that what we show as the next upcoming appointment truly is the next appointment. Therefore, if either of these services are down, I think we should show a message indicating that we cannot get their upcoming appointment data and just show them a link to view all appointments on VAOS.

**Comment by Samara-Strauss** [comment]
Updating the final outcome here based on [this Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1615909362009500):

- Everything @erikphansen posted about Claims is clear, and I added those comments to #21370 for Tressa.

For Health care, this is where we landed:

- No error messaging is needed for messages or prescriptions.
- If we can't determine if someone is a health care recipient or not because `GET user/` isn't working, we should show some sort of error.

I will update Tressa's tickets accordingly to reflect this.
