### ISSUE TITLE
[Design] My VA: Claims spinner handling 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21372]
## Background

Original discussion in #21177. Claims error message is in #21370.

We need to provide Erik and Sandra with guidance on how the claims spinner should work on My VA while the section is loading.

## Tasks

- [x] Mock up design for message error
- [ ] Review with team
- [x] Handoff to FE

**Comment by tressaellen** [comment]
Meeting scheduled with Erik and Sandra on April 1st to go over this. :)

**Comment by tressaellen** [comment]
Hi @bethpottsVADEPO I have something else for My VA for you when you have the time. Currently on My VA, the Claims and Appeals section loads way slower than the rest of the content. We have a spinner at the top, but if it determines that the user doesn't have any claims or appeals to show then we don't show the claims section at all. Which means a user could potentially see a spinner at the top that just disappears.

We'd like to add a line or two under the spinner to give the user more context as to why they're seeing that spinner.  Here's a screenshot of what it looks like currently with no content. 

I'm thinking something along the lines of 'Loading your information...' OR what they currently use in the claim tool is 'Loading your claims and appeals...'

I'm hesitant to use 'Loading your claims and appeals...' because if the endpoint resolves and the user has no claims to show then we do not show the section, which might be confusing to users.

Do you have any guidelines or any other thoughts on what might work?


![Screen Shot 2021-03-31 at 12.58.06 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/e2aa95a5-8d23-4aaa-ba72-b8550ecbfe52)

**Comment by tressaellen** [comment]
Thank you @peggygannon ! I'm curious - why do we tell people to **not** refresh their browser? 

Hmmm @erikphansen and @Samara-Strauss what do you think of this handling? 

> We’re processing your application. This may take up to 2 minutes. Please don’t refresh your browser.

I personally think this seems like a long time for that spinner to be on the page, and then if it doesn't resolve after 2 minutes would we still show an error?

**Comment by Samara-Strauss** [comment]
> Hmmm @erikphansen and @Samara-Strauss what do you think of this handling?

> We’re processing your application. This may take up to 2 minutes. Please don’t refresh your browser.

I don't quite think this works because loading the claim status on My VA isn't the same thing as submitting an application, which is what the copy implies (and I am assuming that's the use case that copy is used for).

Also, two minutes is a hell of a long time. I'd think 60 seconds was long enough to wait before showing an error, but if the standard across the site is 2 minutes, we can go with that.

**Comment by peggygannon** [comment]
@Samara-Strauss @tressaellen yes, the content is specific to applications. I shared it so you are aware of spinner content that exists elsewhere. 

I'm not sure if the 2 minutes is standard across the site or specific to applications. There should be further discussion about that.

**Comment by bethpottsVADEPO** [comment]
@tressaellen Let's go with short and simple:

We're loading your information.

I'll raise spinner language (and whether or not to use the ellipses) to the conversations Danielle and I are having about standardization of labels and content components. We may revisit, but the above messaging will work for now. Thanks!

**Comment by tressaellen** [comment]
That works - thanks so much @bethpottsVADEPO !

**Comment by tressaellen** [comment]
This is done, so I'm closing. The FE on this will be tracked in #22565 .
