### ISSUE TITLE
[Design] My VA: Claims error message

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21370]
## Background

Original discussion in #21177.

We need an error message for the claims section if we can't load it. 

- If either endpoint fails, then we won't show anything. We will need a message here to say why.
- If the section is loading for a long time there is a spinner - this can take up to 30 seconds. Maybe we need to think about how to handle this situation better.

## Tasks

- [ ] Mock up design for claims error
- [ ] Review with team
- [ ] Work with copy
- [ ] Handoff to FE

**Comment by Samara-Strauss** [comment]
Additional information from @erikphansen in #21375:

> ## Claims and Appeals
> 
> Claims depends on `externalServices.mhv` and appeals depends on `externalServices.appeals`.
> 
> - If a user has access to both services and _one_ of those endpoints is down, we cannot show the section as intended. ie, we can't accurately determine what their latest claim or appeal is and might show them incorrect data. I'd recommend showing a message about the service being down and checking back at date/time the downtime is supposed to be over
> 
> - Same goes for if a user can only access claims or appeals. If the required service is down, I'd recommend showing a message about the service being down and checking back at date/time the downtime is supposed to be over

**Comment by tressaellen** [comment]
Hi @erikphansen - for the above comment do we need two separate messages for those scenarios? Or can that be the same error message?

**Comment by tressaellen** [comment]
Here's the content that I came up for what I *think* this ticket is asking for (correct me if I'm wrong @erikphansen )

**For if an endpoint fails:**

**We can't access any claims or appeals information right now**

We’re sorry. Something went wrong on our end. If you have any claims or appeals, you won't be able to access your claims or appeals information right now. Please refresh or try again later.

<img width="1050" alt="Screen Shot 2021-03-23 at 4 20 42 PM" src="https://user-images.githubusercontent.com/58752772/112212828-4dd30480-8bd2-11eb-8613-78fc8d723cc8.png">



**For if there's downtime on claims/appeals (I'm assuming the same alert could work for both scenarios)**

**We can't access any claims or appeals information right now**

We’re sorry. We’re working to fix some problems with the claims or appeals tool right now and cannot display your information on this page. Please check back after [Month, Date] at [00:00 a.m./p.m. ET].

<img width="1064" alt="Screen Shot 2021-03-23 at 4 20 48 PM" src="https://user-images.githubusercontent.com/58752772/112212825-4ca1d780-8bd2-11eb-9c2a-83ce99b0d8fb.png">

**Comment by Samara-Strauss** [comment]
I'll add this to the documentation once we confirm whether we need one or two errors.

**Comment by erikphansen** [comment]
Yes we should have two errors. The first for an unexpected error with either the claims or the appeals API. The second when we _know_ one of those APIs is down and have a known ETA for when it'll be back up.

**Comment by tressaellen** [comment]
Great! In that case @Samara-Strauss I think we're good to close this and add it to  the copy ticket and documentation.

**Comment by Samara-Strauss** [comment]
Sorry to reopen, but I have a question that might affect the copy here:

@erikphansen as I understand it from earlier in the thread, we would show this error if only one endpoint was down, but not necessarily both. In this case, would we not show the claims and appeals section at all? Or might the appeals endpoint be down, but we could still show claims information? I'm trying to understand if the error would ever show alongside claims/appeals data if we could connect to at least one of the endpoints. This would affect both the UX here and the copy.

Sorry if this is clear to everyone else, but figured I'd ask in case it wasnt!

**Comment by erikphansen** [comment]
Since we are showing the most recently updated claim _or_ appeal, we cannot be sure we're actually showing the most recent one if we can only fetch one of those but not the other. The worst case would be us telling them that they have no claims or appeals that we updated in the past 30 days when in fact they may, we just couldn't fetch claims (or appeals) data. It's just safer to show an error if either call fails.

**Comment by Samara-Strauss** [comment]
>  It's just safer to show an error if either call fails.

OK, so we *would* show this error instead of the section altogether? Just making sure.

I guess my one concern about this is it seems like I often get some sort of error/warning when I go to the claim status tool, so I want to make sure we're able to show something most of the time in the claims section on My VA and that we're not being overly cautious. This might just have to be something we feel out once the build is on staging and in testing.

For example, it seems like I almost always see this warning when I go to the claim status tool. Is this indicative that My VA might have problems as well?

<img width="1280" alt="Screen Shot 2021-03-25 at 9 06 57 AM" src="https://user-images.githubusercontent.com/34068740/112477851-c9a38d00-8d49-11eb-92c5-6420c6462d11.png">

**Comment by erikphansen** [comment]
What test user is that? I'm not sure why the claims/appeals tool would show that. It looks like it _did_ get claims, since it's showing claim details right below the error.

I know that the claims endpoint usually takes a long time to resolve, but I didn't see it error out in my testing a few weeks ago.

From a UX/copy perspective it might be pretty tricky to properly handle a situation where one endpoint succeeds and the other fails. We'd have to be clear about the fact that we're only showing them appeals data when we are unable to connect to the claims endpoint and vice versa.

But if one of these endpoint really is prone to failure a lot, I think you're right that just showing them an error isn't great.

**Comment by Samara-Strauss** [comment]
> What test user is that?

This was user 226.

> I know that the claims endpoint usually takes a long time to resolve, but I didn't see it error out in my testing a few weeks ago.

That's good. We can probably verify this more easily once the feature is fully on staging. If we're having an issue with regular errors, then we'll need to adjust our strategy.

> But if one of these endpoint really is prone to failure a lot, I think you're right that just showing them an error isn't great.

I guess it's unclear that whether there are regular issues with one of these endpoints or not, or whether that user (226) tends to have problems. We're probably OK to proceed forward, and we can verify this once the feature is live on staging.

**Comment by tressaellen** [comment]
@Samara-Strauss just to clarify, when you say proceed forward - do you mean the content suggestions that I posted above or something different?

**Comment by Samara-Strauss** [comment]
Sorry for the confusion — I mean with the original suggestion you posted above.

**Comment by Samara-Strauss** [comment]
This has been added to [the frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/claims-and-appeals-status.md#when-to-show-the-claims-and-appeals-section). Closing!
