### ISSUE TITLE
Exploration- Search Input

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21384]
## Description

Search & Discovery team has discussed the search input field on VA.gov and the need to explore the placement, usage and understand more about what options we have as we move forward with various initiatives. 

## Background/Context/Resources
![Screen Shot 2021-03-10 at 4.29.11 PM.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/40cfaf71-db69-45c0-a16e-f461f80f7cd5)

## What questions do we have?
- Can the search input be moved to a different location to make it more prominent?
- Would we want to make search more prominent before we address some of the relevancy issues we have identified?
-
## Tasks

- [ ] PM Exploration - get a sense of how much control we have - can we change the input field?
- [ ] Design Exploration
- [ ] Integrate into research plans to collect user feedback on potential designs
- [ ] Collab Cycle Kickoff and DEPO IA Review

## Definition of Done

- [ ] Search & Discovery Team has a clean understanding of what opportunities we have related to search input.
