### ISSUE TITLE
[FE] My VA 2.0 Enhancements: Consolidate My VA Dashboard date/time helpers

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#21395]
## Background

Consolidate, clean up, and refactor various date/time helpers across the `/dashboard/` app. 

Previous description:

> We are using similar date and time helpers in multiple places for My VA tests. Search for `isWithinPast30Days` or `InMS`. 
> 
> We should standardize and consolidate those in a common helper file. Maybe `src/applications/personalization/profile/tests/helpers.js`

---

## Tasks
- [x] move `isWithinPast30Days` and `...inMS` functions into /utils/helpers.js (maybe we can create a new file specifically for date/time helpers)
- [x] create a replace function for dates that have dashes (see @adamwhitlock1's [comment on a previous PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26079#discussion_r1362889995))
- [ ] write unit tests for each function

## Acceptance Criteria
- [ ] src/applications/personalization/dashboard/utils/helpers.js file has date/time helper functions listed in Tasks

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ FE, BE
- _How can this work be validated?_

## Resources
- related ticket: #66858

**Comment by ajakabcin** [comment]
@dellerbie and @allisonlu maybe a good candidate for discussion in your next engineering sync

**Comment by ajakabcin** [comment]
hey @allisonlu will this be resolved by #66858?

**Comment by allisonlu** [comment]
going to close this ticket since we've consolidated our helpers 🫡

https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/personalization/dashboard/utils/date-formatting
