### ISSUE TITLE
Janssen (J&J) COVID-19 vaccine content updates: Slotted facility content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21399]
## Issue description

Update facility slotted content messaging

## Tasks
- [x] Update content in word doc (highlight updates) (Danielle)
- [ ] Review/add any tweaks (Lauren, Shane review for minor text updates)
- [ ] Send to Dr. Kim's office for review (Lauren)
- [ ] Incorporate Dr. K's changes (Danielle or Randi)
- [ ] Send to JTF for review (Lauren)
- [ ] Incorporate JTF's changes (Danielle or Randi)
- [ ] Ask Kristan and Melodee to post in Sharepoint (Lauren)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lalexanderson-dsva @shanemelliott. Here's the facility slotted content and text messaging doc, updated with the new Janssen info. Updates highlighted. Please let us know any edits. If all looks good, Lauren, we can send up for approvals. It's pretty much all approved content, so should be quick.

[Veteran communications for facilities for review_revised_03.10.21](https://app.zenhub.com/files/133843125/d626012b-625c-42d4-bca6-d5d764b4d83a/download)

Bringing @RLHecht in on this now in case changes are needed while I'm out on the sprint next 2 weeks.

Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lalexanderson-dsva bringing this to the top of email inboxes. though i think we may need to now update this again based on new law...

**Comment by DanielleThierryUSDSVA** [comment]
This is an old ticket and all related, needed work is complete. Closing.
