### ISSUE TITLE
[Design] My VA: Prescriptions error message

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#21403]
## Background

Original discussion in #21177.

We need an error message for if we can't load prescription info.

## Tasks

- [ ] Mock up design for prescription error
- [ ] Review with team
- [ ] Work with copy
- [ ] Handoff to FE

**Comment by Samara-Strauss** [comment]
Question, and I should have realized this yesterday — why do we need an error here if there is no longer personalized prescription info?

**Comment by tressaellen** [comment]
@Samara-Strauss sorry, somehow I missed this notification. I hadn't decided yet if we were separating out the prescriptions section when we made this, but now that it's settled then I think we're good to close this.

**Comment by tressaellen** [comment]
> Also, perhaps you've already discussed this with Sandra/Erik, but given that we are not personalizing prescription info anymore, I think we can show the "View all prescriptions link" at all times and we don't need to show it conditionally based on whether someone has prescriptions or not.

I think this would work just fine - would this mean that we always show the prescriptions link for all users who have healthcare?

**Comment by Samara-Strauss** [comment]
OK, we *are* good to close this — no error messaging is needed, confirmed in #21375. I'll make sure that Sandra knows we no longer need conditional logic around the prescriptions link.
