### ISSUE TITLE
[VAMC]  Research and document the Mobile experience from other medical/clinics around US for discussion [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21406]
## Story
As a Veteran I need a more flexible and useful mobile clinic experience, so I can better understand and plan my health care journey.

## Tasks
**Find and document mobile clinic pages from other platforms**
- [x] Document at least three different mobile pages and how they are formatted

## Acceptance criteria
- [x] At least three different mobile experiences documented
- [x] Set up meeting to discuss findings 
- [ ] Document any input from CLC, Domicilary, or shelters in same system
