### ISSUE TITLE
[Design] My VA: Prescriptions error

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#21402]
## Background

Original discussion in #21177.

We need an error message for the disability rating if we can't load it. Something similar to the existing profile error but for messages.

## Tasks

- [ ] Mock up design for message error
- [ ] Review with team
- [ ] Work with copy
- [ ] Handoff to FE

**Comment by ajakabcin** [comment]
Closing this issue - per slack conversation with Tressa confirmed the issue was not needed
