### ISSUE TITLE
IRIS Q&As: Disability

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#21414]
### Issue
For the launch of Resources and support MVP 1.1, content that fall into the "disability" category needs to be developed based on IRIS questions approved for migration by SME Paul Shute:

- What is Combat-Related Special Compensation and why is it important?
- How do I get a copy of my rating decision?
- What is a Non-compensable disability?
- What is the difference between VA compensation and severance disability?
- Are there other VA benefits related to compensation?
- How does VA determine someone's net worth?
- If I am already receiving monthly payments or a service-connected disability can I get a VA pension too?
- 

Content will take the form of a Word document, but will be organized and labeled so that, when final it, it can be easily flowed into resources and support page templates [currently in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12066#issuecomment-675074504).

Content will meet [learning center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).

Content will be tagged [per requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#purpose-of-tags-in-the-learning-center). 

### Tasks
 
- [x] PW to identify IRIS faqs to migrate (Laura)

- [ ]  PW to identify any content in the Contact Center that should inform editing of IRIS faqs, or be added as additional content (Laura)

 - [ ] PW to develop draft copy (Laura)

 - [ ] PW to assign tags (Laura)

 - [ ] DEPO to complete initial review (Beth) 

- [ ] PW to copyedit draft (Randi)

 - [ ] PW to create content review GH ticket and attach edited draft for DEPO review (Laura)

### Acceptance Criteria
  - [ ] Copy deck ready for 2nd DEPO review and attached to a content review GH ticket.

### Up-to-date copy deck
Please use the deck shown here and replace it when you make edits/comments to ensure that the latest document is always here, at the top of this ticket.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- copy deck is at the top of this ticket. LMK if you have questions. Thanks.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Putting in writing here the feedback I provided today for the Combat-Related Special Compensation Q&A. Thank you for reworking the original along these lines:

- Present the eligibility information so it matches our style of using bullets rather than numbered 1, 2, 3
- Split out the sub-bullets so the chunks of content are easier to digest (I was envisioning the basic eligibility info you had for 1, 2, 3 at the top, then separate sections describing what "officially retired" means and what kind of evidence shows a combat-related disability rating of 10% or higher)
- Change this about article's H2s so they aren't questions (and see if the first line of text under them still works now that the H2s aren't questions)

Thank you!!

**Comment by bethpottsVADEPO** [comment]
Since I've already started editing the Word doc, rather than replacing what's here already, can you just paste the new text in a new comment here and I'll incorporate into what I already have?

**Comment by lwalsh617** [comment]
Will do!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I did some more editing on the CRSC article, and have a couple other things to kick back to you. 

In the How to apply section where we'll link to the PDF, I'd like to add the addresses. Would you grab them from the form itself? I found the form here: https://www.esd.whs.mil/Directives/forms/dd2500_2999/

Again, if you paste the addresses into a comment in this ticket, I will add them to my doc. I couldn't copy and paste them from the file I downloaded for some reason. They're on the first page of the form. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- I've pasted the edited copy in below. I'm also attaching my copy deck with the edited copy highlighted in case you need it for reference. LMK if you need anything else on this one. Thanks!

_<**ELIGIBILITY EDITS** (eliminated numbering and sub-bullets by splitting content into several questions)>_

**Am I eligible for CRSC?**

To qualify for CRSC you must:

- Be officially retired, **and**

- Have a combat-related VA disability rating of 10% or higher, **and**

- Have your DoD retirement payments being reduced by the amount of your VA disability payments

**What does "officially retired" mean?**

Being officially retired means:

- Having 20 or more years of service, **or**

- Being medically retired due to a total disability rating of 30% or higher (Chapter 61), **or**

- Being covered under the Temporary Early Retirement Act (TERA), **or**

- Being on the Temporary Disability Retired List (TDRL)

**What makes a disability "combat related"?**

A combat-related disability means thatyoucan provide evidence that your injury happened while you were:

- In combat (qualifies for a Purple Heart), **or**

- Engaged in hazardous duty (like demolition, flying, or parachuting), **or**

- Participating in war simulation activities (like live fire weapons practice, hand-to-hand combat training, etc.), **or**

- Exposed to an instrumentality of war (like a military vehicle, weapon, or chemical agent used in war)

**Can I get CRSC if I'm not getting disability payments?**

You have to be getting disability payments and having the amount of those payments deducted from your retirement payments in order to get CRSC. If you don't currently receive VA disability benefits, you can file a claim.

Find out how to file a VA disability claim

https://www.va.gov/disability/how-to-file-claim/  


_<**FORM LINK EDIT.** Under WHERE DO I APPLY FOR CRSC? -- FORM LINK DD2860 (this link goes direct to form instead of the long DoD table a user will have to scroll through)>_    

Download DD Form 2860

https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd2860.pdf    


_<**MAILING ADDRESSES EDIT** (added as new faq directly following "Where do I apply for CRSC" faq)>_  

**Where do I send my DD Form 2860 and other documents?**

Send your completed form and supporting documents to your military branch:

**Army**

Department of the Army

Army Human Resources Command

ATTN: AHRC-PDP-V

1600 Spearhead Division Avenue, Dept. 480

Fort Knox, KY 40122

eFAX 1-502-613-9550

**Navy and Marine Corps**

Secretary of the Navy

Council of Review Boards

ATTN: Combat Related Special Compensation Branch

720 Kennon Street SE, Suite 309

Washington Navy Yard, DC 20374-5023

**Air Force**

United States Air Force

Disability Division (CRSC)

HQ AFPC/DPPDC

550 C Street West, Suite 6

Randolph AFB, TX 78150-4708

**Coast Guard**

Commander (PSC-PSD-de)

Personnel Service Center

U.S. Coast Guard Stop 7200

4200 Wilson Boulevard, Suite 1100

Arlington, VA 20598-7200

**NOAA CORPS**

Director, Commissioned Personnel Center

8403 Colesville Road, Suite 500

Silver Spring, MD 20910-6333

**Public Health Service**

United States Public Health Service

Compensation Branch

Program Support Center, ESS

5600 Fishers Lane, Room 4-50

Rockville, MD 20857-0001


[rs-1.1-disability-1.1-041221.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6297757/rs-1.1-disability-1.1-041221.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- In addition to the edits in my comment ^, I have a few more. See highlights below. Thanks!
![Disability v  Pension edits](https://user-images.githubusercontent.com/53535663/115045406-7afa9600-9ea4-11eb-8f0e-80361700a185.png)

**Comment by bethpottsVADEPO** [comment]
@lunascoop Can you build this page out in drupal this week for R&S? 

[https://app.zenhub.com/files/133843125/e0e79e30-b595-4047-8ac1-2f3f07c8f1ea/download](https://app.zenhub.com/files/133843125/e0e79e30-b595-4047-8ac1-2f3f07c8f1ea/download)

**Comment by bethpottsVADEPO** [comment]
@lunascoop 
1/ You can create a separate ticket for that drupal work. It's just one article from the list of IRIS questions above (the first one about CRSC).
2/ For the CTA button and under "How to apply" in the doc, please link to this form url instead of what's in the Word doc: https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd2860.pdf

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Here's the non-compensable disabilities article, ready for building in drupal!

[https://app.zenhub.com/files/133843125/ac6b774a-3fde-459c-93b2-347762a3ba03/download](https://app.zenhub.com/files/133843125/ac6b774a-3fde-459c-93b2-347762a3ba03/download)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Since the drupal creation ticket has been closed, I'm attaching a Word doc here for you with the edits from the branches of service to input into drupal. Let me know if you have any questions as you incorporate! Thanks.[https://app.zenhub.com/files/133843125/0d30ba47-9baa-4394-b7ba-c938efeafb80/download](https://app.zenhub.com/files/133843125/0d30ba47-9baa-4394-b7ba-c938efeafb80/download)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 This is for the CRSC article.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO @RLHecht -- I made the changes to the CRSC article per Beth's Word doc ^. Here's the preview link:
http://preview-prod.vfs.va.gov/preview?nodeId=18658

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Can you build out in drupal the non-compensable disabilities article I attached above? This would take priority over other stuff on your plate.

**Comment by lwalsh617** [comment]
Hey @bethpottsVADEPO  - Unless I'm missing something, I already built this article in Drupal. See my comment just above yours. :)

**Comment by bethpottsVADEPO** [comment]
I thought you had already built the non-compensable article, but when I searched for it in drupal, it didn't come up! And Randi couldn't find it either. Can you put the preview link or node here?

**Comment by lwalsh617** [comment]
Here's the preview: http://preview-prod.vfs.va.gov/preview?nodeId=18658

**Comment by RLHecht** [comment]
@lwalsh617 I think this is different than the one Beth is asking about. This is the one:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/21414#issuecomment-852272872

**Comment by lwalsh617** [comment]
^ Thanks, @RLHecht! 
@bethpottsVADEPO Here's the preview link to the multiple faqs page: 
http://preview-prod.vfs.va.gov/preview?nodeId=26921

**Comment by bethpottsVADEPO** [comment]
Thanks @lwalsh617 -- I sent it off for SME review.

**Comment by bethpottsVADEPO** [comment]
@RLHecht This noncompensable disabilities article is ready for a final copyedit. Paul Shute has approved it. 

http://preview-prod.vfs.va.gov/preview?nodeId=26921

**Comment by bethpottsVADEPO** [comment]
@RLHecht This is the only ticket tracking the noncompensable article. Go ahead and create a new ticket for getting it live as you did for CRSC. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Circling back on the 3 disability articles (based on IRIS faqs Paul Shute requested that we migrate) that still need your go-ahead. I added page views (highlighted in yellow) in the Word doc attached here. If you can bless the articles/templates I'll build them in Drupal before you do a thorough review. (There's a table I'll need to convert to text per our recent Slack thread, etc.)
Thank you!
[rs-1.1-disability-v2-100121.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7268480/rs-1.1-disability-v2-100121.docx)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 
- Because of low PV, let's pause on Disability severance pay. You can mark it down as a possible future article in the chart you're developing in github.
- Because of low PV and the high-level broad overview nature of this article, please pause on VA disability benefits article.  Again, possible future article, but we won't do it immediately. 
- Question about the third one: copy of VA disability rating. I seem to remember you tried to use a test user account to find out if a Veteran can get the decision notice through our [VA benefit letters tool](https://www.va.gov/records/download-va-letters/) or through eBen. But I don't remember the outcome of that--if you were able to definitively figure out if that was possible through either our VA.gov tool or eBenefits. I do think we should write this article and include it in the work in progress now, but I'm not sure if our guidance should be to send a letter to the Veteran's local VA regional office.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Regarding the "copy of VA disability rating letter" article. While you can get a "Benefit Summary and Service Verification Letter" which has some disability rating info, the actual disability rating letter is not mentioned on the list of letters you can download. I attached the benefit summary/service verification letter below.  I'm assuming the attached is different from the official rating letter (thought I can't be positive because I haven't seen one) and that we should not lead users to believe they can get the rating letter through the VA benefit letters tool. 
[Benefit Summary Letter.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/7347543/Benefit.Summary.Letter.pdf)
(I'm still working on getting into eBenefits to try at that route.)
