### ISSUE TITLE
QASP Metric Tracking

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#21437]
# Text of QASP Metric
Number of top ten VA.gov user experiences, based on unique transactions per month, that have a corresponding automated end-to-end browser test that exercises multiple pieces of functionality including both FE and BE.

# Tasks
- [x] Discover what the top ten user experiences on VA.gov are by unique transactions per month
- [x] Determine a threshold for "exercises multiple pieces of functionality"
- [x] Assess the current number of top ten experiences that have corresponding E2E tests

**Comment by rjohnson2011** [comment]
Created a support request with Analytics team to discover the top 10 experiences.

**Comment by rjohnson2011** [comment]
Received metrics information from Analytics team. Currently going through the top experiences on VA.gov and finding if they each contain corresponding E2E tests.

**Comment by rjohnson2011** [comment]
Top Experiences are summarized & evaluated for code coverage on this Confluence doc -> https://vfs.atlassian.net/wiki/spaces/~527721881/pages/1961754635/QASP+Metric+Tracking

**Comment by pjhill** [comment]
Thanks for wrapping this up.
