### ISSUE TITLE
Create and publish Tagalog Covid-19 FAQ page in Drupal

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#21446]
### Issue Description
We need to build out the Tagalog version of COVID-19 FAQs page.

### Relevant info and documents

Drupal page: http://preview-prod.vfs.va.gov/preview?nodeId=16475
Page content: [CoronaVirus FAQ_Web_Final_Tagalog.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6126293/CoronaVirus.FAQ_Web_Final_Tagalog.docx)
Accordion content: [Veteran FAQ Accordion Questions_Content (002) 03.05.21 Final Translation.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6126294/Veteran.FAQ.Accordion.Questions_Content.002.03.05.21.Final.Translation.docx)

### Tasks: 

- [x] Build out page (Selina)
- [x] Review page (Randi)
- [x] Publish page
- [x] Send live page links to translation team for review

### Acceptance criteria:
- [x] Tagalog FAQs page is live on the site

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review

**Comment by RLHecht** [comment]
@lunascoop I've reviewed this page and made some copy tweaks and fixed some links. @DanielleThierryUSDSVA Let us know if you want to take a look over this before we publish. Once it's live I'll send the link to Mateo's team for the final review.

**Comment by RLHecht** [comment]
This page is now live. I sent the link to Mateo for final review on 3.16. Fareez is also working on adding the toggle to the top of the page. Closing ticket.
