### ISSUE TITLE
Content updates to VET TEC page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21444]
## Issue Description
Stakeholder Tammy Hurley sent a request for several content updates to our [VET TEC](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/) page. She asked that these be live by March 17.

All changes are attached in the Word doc. 
[https://app.zenhub.com/files/133843125/f31dc6dc-0822-40fe-8123-f53006c0e4a5/download](https://app.zenhub.com/files/133843125/f31dc6dc-0822-40fe-8123-f53006c0e4a5/download)

Note that the changes to the gray alert box are too lengthy. Beth is rewriting and will post revised copy in this ticket.

## Tasks
- [x] Content updates made to VET TEC page
- [x] Content sent to stakeholders for approval
- [x] Copyedit and publish page
- [x] Notify stakeholders that page is live

## Acceptance Criteria
- [x] Page live with requested content updates

**Comment by bethpottsVADEPO** [comment]
@RLHecht  Here's the text for the gray box. I'd like to model it off this page: https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/ and use the text expander. I'll follow up in another comment with the other edits to incorporate. Thanks!

**Alert header: We’re expanding access to VET TEC and making other improvements** 

As part of the Isakson and Roe Act of 2020, we’re making changes to the VET TEC program. These changes will help more people use the program to get high-tech training from experts.

**Here’s what we’re changing:**

- **We’re expanding access to include service members who are close to separation.** Service members can apply if they’re within 180 days of separating from the military.
- **We’re making it easier for you to find expert instructors.** You can now choose eligible training providers who have been in operation for 2 years or less. Instructors must be experts in their field to be approved for the program.
- **We’re increasing funding.** Our funding increase from $15 million each year to $45 million lets us offer the program to more Veterans.

We’ll update you here to let you know when you can apply.

If you have any questions, you can contact us at 888-442-4551. We’re here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET.

LINK: Learn more about the Isakson and Roe Act of 2020

**Comment by bethpottsVADEPO** [comment]
@RLHecht Here are the rest of the edits:

Under **Am I eligible for this program?**, the first bullet should say:
- Aren't on active duty or are within 180 days of separating from active duty, **and**

Under **What benefits can I get through this program?**, place a note under the second bullet:
**Note:** If you're on active duty, you're not eligible to receive a housing allowance.

**Comment by RLHecht** [comment]
@bethpotts I made these changes and they are ready for Tammy. Unfortunately she won't be able to see the updated alert box on the preview page. Our two choices are to send her the copy separately and let her know that is replacing the alert box or we could set up a demo environment in Tugboat for this page, which is a little more work but she would see the page with the alert as it should be. Let me know what you want to do.

**Comment by bethpottsVADEPO** [comment]
@RLHecht 

Revised header for the alert:
**We're expanding the VET TEC program**

Expander link text:
_Learn more about the changes to this program_

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thank you for the flurry of edits in slack that we had--not all captured in this ticket, but that's fine. They're all in the node now. 

Just putting a note here for tracking purposes that I've sent the link to the demo environment to SME Tammy Hurley. Now we wait to hear back from her/other Education Service SMEs. I did quite a bit of editing, so I'm expecting some further edits from them, but you never know!

Demo environment: 
https://web-a7ap2otqlw1dqanh5n61aw1pf9a0ima8.demo.cms.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/

**Comment by bethpottsVADEPO** [comment]
@RLHecht I heard back from Tammy that this is ready to publish! We can get it live today, then will you follow up with Tammy to let her know? Thanks!

**Comment by RLHecht** [comment]
Page published and Tammy emailed! Moving to validate and will close after deploy.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
