### ISSUE TITLE
Create Initial Prototype for COE

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#21458]
## Background
Expediting design, moving straight to prototype for VA From 29-1880. Form to follow VA.gov conventions. Initial prototype to employ basic form-flow logic/links.

## Considerations
- Keep the scope tight to the first version: auto-eligibility screens, VA form application

## Tasks
- [x] Static screens slideshow fashion
- [x] Interlink screens using basic link/logic connections
- [x] Make UXPin prototype available for review and feedback

## Acceptance Criteria
- [x] Initial COE form prototype saved in the research-design folder, available for review/feedback

**Next steps**
- Request meeting with COE stakeholders for follow up after review

**Comment by sporeboy** [comment]
Prototype starting-point: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312

**Comment by sporeboy** [comment]
Workflows addressed:
- Automatic COE
- Full form process
- Prefilled address
- Known Service history
- Others
