### ISSUE TITLE
Add tab component to DS 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#21469]
## Issue Description
In 3/12 DSC meeting, request from Allison to add tab component to DS was discussed. Decision was made to add tabs component with very limited usage.  Fine putting in DS that we do not recommend w/ exception of following decisions. Recommend using X instead (ie On this page)  
Put in backlog for DST to finalize as a component with a11y work Trevor mentioned. 

Here is the request ticket from Allison. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/403

---
## Tasks
- [ ] Audit existing usage of tabs
- [ ] Draft documentation for usage and guidelines of when tabs can be used 

## Acceptance Criteria
- [ ] Documentation is reviewed
- [ ] Documentation is approved
