### ISSUE TITLE
[Datadog] Percentile-based latency metrics for SLO Report that BE Tools team generates  

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#21465]
## Issue Description
The BE Tools team is looking to provide percentile-based latency, which isn’t something that you get out of the box with DataDog. It doesn’t look too difficult to implement, but we do want to provide the 99, 95, and 50th percentile-based metrics as we do with the current implementation with (Prometheus/Grafana). 

The first step is to determine what is needed in to implement this functionality in Datadog. This may require some investigation by the Platform Operations team. 

## Background / Resources
Prometheus automatically collects data sent to StatsD. There's some more information on how that all works [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/sending-metrics-using-statsd.md) (e.g. Prometheus, StatsD, the StatsD exporter, etc)
[Here's an example](https://dsva.slack.com/archives/CE4304QPK/p1635268843025000) of the current report using Grafana 

## Technical Info
It looks like a quantile function is being used to extrapolate/create percentile-based metrics:
`quantile(0.99, haproxy_server_total_time_average_seconds{proxy=~"$backend"})`

---
## Tasks
- [ ] Research what's needed to implement this feature for BE Tools 
- [ ] Discuss w/ BE Tools team to understand what's needed
- [ ] Install and/or configure dogstatsd on the instances needed for the SLO report 
- [ ] Configure Datadog to consume/present this data 

## Acceptance Criteria
- [ ] 99, 95, and 50th percentile-based metrics will be available for use w/ the SLO report

**Comment by jhouse-solvd** [comment]
Good info here: 

https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/

and possibly here: 

https://docs.datadoghq.com/metrics/distributions/

**Comment by jhouse-solvd** [comment]
@ericboehs - we've taken a look at this as a team and will need to do deeper investigation next sprint to understand how to implement. cannot yet estimate LOE, but will once we have more information.

**Comment by jhouse-solvd** [comment]
We think that we just need to get dogstatsd running and collecting the data on the machine that's running the service that we're trying to collect data from. Let's start by looking into this and finding out if that's true.

**Comment by jhouse-solvd** [comment]
@omgitsbillryan - great to see that this is in progress. let us know the LOE once you've had a chance to dig in? thank you, sir.

**Comment by omgitsbillryan** [comment]
[Here's the dashboard in question](http://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1) I believe.  The specific metric that these panels query off of is `haproxy_server_total_time_average_seconds`. So some questions:

1. What's wrong with the existing SLO dashboard in grafana? Is it just that we want a Datadog flavored one?
2. Are we looking for the same kind of dashboard, specifically, fwdproxy stats on all our backend service integrations?


I do believe the datadog agent is installed and running as a separate process on the fwdproxy EC2 instances, but I still have a lot to learn about the datadog metrics ecosystem.

**Comment by andreahewitt-odd** [comment]
@jeff2d2 I believe those questions from Bill are for you. This is a blocker for BE team to be able to finish https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13677

**Comment by andreahewitt-odd** [comment]
@omgitsbillryan I think you'll also find your answer to the first question in the ticket I linked above ^

**Comment by jeff2d2** [comment]
@jhouse-solvd Just curious where this sits in priority for you guys? No pressure, just gauging.

**Comment by jhouse-solvd** [comment]
@jeff2d2 - tl;dr - no pressure at all. we will probably pick this back up in a month or more at minimum

_also a lil' back story for add'l info:_ 

right now, there is a pending migration from the platform's current DataDog (DD) instance, to an instance hosted by the VA's DOTS team, slated to begin Jun 1. 

This migration is part is of a much longer story that includes the fact that the platform has been waiting for ~6mos to receive licenses that will give it infrastructure monitoring across all instances in all environments. 

we are waiting until the migration happens before doing any additional major work w/ DD.

**Comment by jhouse-solvd** [comment]
There is a newer ticket tracking this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42065

**Comment by jhouse-solvd** [comment]
This issue can be closed. (see #42065)
