### ISSUE TITLE
[DISCOVERY] Mobile VAMC

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21481]
## Issue Description
We need to understand more about Mobile VAMC units before we can make decisions about the best ways to display info about them on the Facility Locator and the VAMC product.

---
## Tasks
- [ ] Discovery with the field to understand how Mobile VAMCs operate, including
       - the various ways they are used 
       - location/schedule 
       - relationship to brick and mortar VAMCs
       
- [ ] Discovery with Veterans, including
      - How do they expect to find information about Mobile VAMCs
      - For what uses do they look for VAMCs
      - What information do they expect to find about the Mobile VAMC

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
closing as duplicate
