### ISSUE TITLE
Update stimulus question based on third stimulus check

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21493]
## User story

As a Veteran who gets disability compensation or pension benefits and may not file taxes, I need to know if I'll automatically get the third stimulus check.

## Issue description

We need to update the main stimulus question to reflect the third stimulus check.

## Content we need to update

- [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#debt-copays-appeals-and-other-): "If I receive VA disability or pension benefits, will I automatically get my second stimulus check?"

## Tasks to completion

- [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/): "If I receive VA disability or pension benefits, will I automatically get my second stimulus check?" question.
- [Coronavirus FAQs in Spanish](https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/): "Si recibo beneficios por incapacidad o pensión del VA, ¿Obtendré automáticamente mi segundo cheque de estímulo?"
- Coronavirus FAQs in Tagalog (to be published on Monday)
- [VA.gov chatbot](https://www.va.gov/coronavirus-chatbot/): Debt, copays, and other financial concerns > "If I receive VA disability or pension benefits, will I automatically get my second stimulus check?"

## Tasks to completion

- [x] Draft content (Danielle)
- [x] Finalize content for sharing (Lauren, Randi, Danielle as needed)
- [x] Send to JTF (Lauren)
- [x] Hand off approved content for implementation (Lauren)
- [x] Send content to translation team and start translation coordination process/tracking (Randi)
- [x] Update content in English FAQs page (Selina, Randi)
- [x] Update content in chatbot (Selina, Randi)
- [x] Update content on Spanish and Tagalog pages (Selina, Randi)

**Comment by DanielleThierryUSDSVA** [comment]
@lalexanderson-dsva @RLHecht Here is draft content for this question: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EU6-MGaYtKxKpUBwWfdCWVEBp8t9U39uiVFrmp6D_Utfqg?e=8b0MgX

We've typically just gone straight to JTF with this content for review.

**Comment by lalexanderson-dsva** [comment]
Submitted to JTF this morning.

**Comment by lalexanderson-dsva** [comment]
This was approved by the JTF. @RLHecht - go ahead and get this content updated in the FAQs.

**Comment by RLHecht** [comment]
Changes input and the page was published. I'll confirm it's live after this afternoon's deploy. @lunascoop you can go ahead and start the work on the chatbot.

**Comment by lunascoop** [comment]
@RLHecht I made the updates to the chatbot (Question #54). I created a pull request for your review. https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/363

**Comment by RLHecht** [comment]
Updates are live on FAQs page. Text was sent to translation team 3/15.

**Comment by RLHecht** [comment]
@lunascoop Here is the Spanish translation copy for this work. [https://app.zenhub.com/files/133843125/75804cf1-5e26-48d9-b6f7-228975d82ffa/download](https://app.zenhub.com/files/133843125/75804cf1-5e26-48d9-b6f7-228975d82ffa/download)

**Comment by lunascoop** [comment]
@RLHecht this is ready for review (minus the sentence that needs translating) http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
This was published and I sent a revised doc to the translators for that last line of copy.

**Comment by RLHecht** [comment]
@lunascoop Here is the translated copy for Tagalog. [https://app.zenhub.com/files/133843125/98278caf-680c-43f8-ad50-b0da3e25d057/download](https://app.zenhub.com/files/133843125/98278caf-680c-43f8-ad50-b0da3e25d057/download)

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. Like the Spanish translation, there's a sentence that still needs translating.

> Go to the IRS.gov website to learn more about economic impact payments

http://preview-prod.vfs.va.gov/preview?nodeId=16475

**Comment by RLHecht** [comment]
@lunascoop These changes look good. I've published the Tagalog page.

**Comment by RLHecht** [comment]
work completed. Closing ticket.
