### ISSUE TITLE
Update VA health care copay content based on new law

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21492]
## User story

As a Veteran, I need to know what's happening with VA health care copays and how it impacts me.

## Issue description

As part of the American Rescue Plan Act of 2021, signed into law on 3/11, VA copays will be waived from April 6, 2020 through September 30, 2021.

We need to work with our partners in VHA, debt management, and JTF, to update content around medical copays across our pages and products.

## Content we need to update

- [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/): "Do I have to pay my VA copays at this time?" question.
- [Coronavirus FAQs in Spanish](https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/): "¿Seguiré teniendo que pagar mis copagos de VA durante la pandemia?"
- Coronavirus FAQs in Tagalog (to be published on Monday)
- [VA.gov chatbot](https://www.va.gov/coronavirus-chatbot/): Debt, copays, and other financial concerns > "Do I have to pay my VA copays at this time?"
- VA.gov alerts on copay pages:
  - [Pay your VA copay bill](https://www.va.gov/health-care/pay-copay-bill/)
  - [Dispute your VA copay charges](https://www.va.gov/health-care/pay-copay-bill/dispute-charges/)
  - [Request VA financial hardship assistance](https://www.va.gov/health-care/pay-copay-bill/financial-hardship/)
  - [2021 VA health care copay rates](https://www.va.gov/health-care/copay-rates/)
  - [Past rates: 2020 VA health care copay rates](https://www.va.gov/health-care/copay-rates/past-rates-2020/)

## Tasks to completion

- [x] Draft content (Danielle)
- [ ] Finalize content for sharing (Lauren, Randi, Danielle as needed)
- [ ] Share content with stakeholders (Lauren)
- [ ] Incorporate changes (Lauren, Randi, Danielle as needed)
- [x] Send to JTF (Lauren)
- [x] Hand off approved content for implementation (Lauren)
- [x] Send content to translation team and start translation coordination process/tracking (Randi)
- [x] Update content in English FAQs page (Selina, Randi)
- [x] Update content in chatbot (Selina, Randi)
- [x] Update content in alerts (Selina, Randi)
- [x] Update content on Spanish and Tagalog pages (Selina, Randi)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lalexanderson-dsva @RLHecht. Here's a link to draft content for this as well as notes on stakeholders to send this to for review before sending to JTF. Thanks!

https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/ETkHtIHlDeVBuM6YA3RGI80BvujJjGb6vjnUrMZ83xKJJg?e=x2NU0o

**Comment by lalexanderson-dsva** [comment]
I saved down a copy of the original file and sent the online shared version to the stakeholders (minus the SME intro) to review by 10am Tues. 

I'll give them til 12ish, work with @RLHecht to compile changes, and get it over to JTF asap after.

**Comment by RLHecht** [comment]
@lunascoop Here is the approved copy for the copay question that is being updated[https://app.zenhub.com/files/133843125/f95f53c9-f8af-4180-a009-07ebf8ab9ff6/download](https://app.zenhub.com/files/133843125/f95f53c9-f8af-4180-a009-07ebf8ab9ff6/download). Can you please input it in the FAQs as well a the chatbot? I sent the copy to the translators today as well.

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is ready for review. I also created a PR for the chatbot updates. There seems to be an CI issue w/the PR that I was going to ask Shefali to help with.

Coronavirus FAQs: What Veterans need to know: http://preview-prod.vfs.va.gov/preview?nodeId=3014

**Comment by RLHecht** [comment]
Thanks @lunascoop I published and did a content release for the FAQs page

**Comment by RLHecht** [comment]
@lunascoop Here are the translations back for this work. 
[https://app.zenhub.com/files/133843125/cf16c545-5061-4f0c-940f-52121c20e2f7/download](https://app.zenhub.com/files/133843125/cf16c545-5061-4f0c-940f-52121c20e2f7/download)

[https://app.zenhub.com/files/133843125/ed6da007-4e34-4721-b942-53e657bdcc8f/download](https://app.zenhub.com/files/133843125/ed6da007-4e34-4721-b942-53e657bdcc8f/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for your review.

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
Thanks @lunascoop ! These are reviewed and published. I'll send the live links to the VHA translation team for their final review.

**Comment by RLHecht** [comment]
Work completed on this. Closing ticket.
