### ISSUE TITLE
[UI] Health Record Documentation

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#21518]
## User Story
- As a product team member, I want to be able to understand the previous work completed on Health Records (Medications, Allergies, and Immunizations).

## Related Documentation
- [Questionnaires Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- [HealthRecord Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/health-record.md)
- [Medications Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md)
- [Allergies Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/allergies.md)
- [Immunizations Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/immunizations.md)

## Description
Documenting all current work and outstanding questions related to Health Records (Medications, Immunizations and Allergies) on GitHub, so whoever picks the topic next can understand all the work already completed.

## Tasks
- [X] Move [data analysis (Lighthouse vs VetsAPI vs MHV) spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/health-record/DataAnalysis-AvailabilityIn-Lighthouse-VetsAPI-MHV.xlsx) to GitHub
- [X] Update [medication product feature document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/medications.md) with known product features and outstanding questions
- [X] Update [allergy product feature document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/allergies.md) with known product features and outstanding questions
- [X] Update [immunization product feature document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/health-record/immunizations.md) with known product features and outstanding questions
- [x] ~~Write out list of data elements that should be added to Lighthouse with justification as to why~~
  - Without knowing Lighthouse's roadmap and without talking to providers/SMEs about their needs/wants, I don't feel comfortable asking Lighthouse to add any data elements at this time.
- [X] Complete a small exploration on a sequential display of one health record section - based upon March 15, 2021 list loop design meeting
  - I used [allergies as the example to wireframe](https://www.sketch.com/s/f84952b4-9e8b-457d-b25e-5015c92e3913/a/ZOWdAla/play)

## Acceptance Criteria
- [ ] Share documentation with product

**Comment by kristenmcconnell** [comment]
@abuckley3385 I think that I have updated all the documentation that I can think of related to health records, except the initiative page. Let me know if you can think of anything missing or want me to make edits.
