### ISSUE TITLE
Exploration of Site Indexing

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21536]
## Description

As a product team we need to collect as much information as possible about how VA.gov site is indexed so we can determine next steps and ways to optimize for future features and enhancements.

## Background/Context/Resources
https://search.gov/blog/searchgov-faqs-indexing.html

## Questions

- [ ] Can we reduce the number of pages of results the user is presented with? 
- [ ] Can we add more content tags to improve indexing?
- [ ] How can we improve relevancy of the results? Do we have to rely on search.gov or are there other ways?
- [ ] How can we ease the user experience across VA sites and mini searches on va.gov?
- [ ] Where is the content (what content sources are out there)? (Drupal, GitHub Repository, CMS, statically generated pages from vet website (javascript), blog posts, rails)
- [ ] Is all "modernized content" in Drupal?
- [ ] How much content is modernized (50%? 10%?) 
- [ ] What tagging is associated with each content source? 
- [ ] Who maintains the metadata for each content source?
- [ ] Is establishing a standard set of metadata an impossible task? 

## Tasks

- [ ] Collect information 
- [ ] Define Site Indexing Goals
- [ ] Review elastic search capabilities to improve search.gov experience
- [ ] **Implement Search Best Practices  ([more info on Nielsen Norman Group](https://www.nngroup.com/articles/internal-website-search/))**
- [ ] **Remove 'stop words'** (Example: remove sentence structure words that reduce result quality ('to', 'get') searching for “how to get prescription” doesn’t produce the results we want however searching for “prescription” will produce best bet)
[Elastic search + stop words](https://qbox.io/blog/how-to-use-elasticsearch-remove-stopwords-from-query/)
- [ ] **Stemming** "Stemming refers to removing endings (like suffixes) from words, and reducing them to their morphological ‘stem.’ ... Although stemming will boost recall, it can also lower precision by returning results that are not relevant, but happen to include the stem of a query word."
[Elastic search stemming](https://www.elastic.co/guide/en/elasticsearch/reference/current/stemming.html)

## Definition of Done

- [ ] TBD

**Comment by denisecoveyduc** [comment]
Initial Exploration Complete. We have captured our findings in the [Onsite Search Product Outlin](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/product-outline.md)e which will continue to be iterated on as more information become available.
