### ISSUE TITLE
Send Build Pipeline Analytics to Prometheus

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-team#21552]
## User Story 

As an Engineer, I need to send the GraphQL multi-query time from the content build process to Prometheus, so that it can be used in a Grafana chart for monitoring (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4700).

## Issue Description

Gather the build pipeline build time metrics in Prometheus. 
The CMS team is currently integrating with Prometheus to record node counts overtime. 
The plan is to create a Grafana chart to track the GrapQL query time alongside node counts to gauge GraphQL performance overtime.

Ideally, each step in the build process is recorded and monitored in a Grafana dashboard, but at the minimum, GraphQL multi-query time should be made available for monitoring to ensure timely response to content build scaling issues.

Related Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4699 and epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4697

---
## Tasks
- [ ] Allow metrics to be sent from the nodeJS build pipeline to Prometheus possible using https://github.com/siimon/prom-client

## Acceptance Criteria

- [ ] GraphQL multi-query performance data is collected from the FE Content Release Build, so that it can be plugged into the CMS Grafana dashboard
- [ ]  GraphQL query is recorded for DEV/STAGING/PROD

---
_GraphQL performance data = total request time from Step 3(?) of the build; e.g. total time of the parallelized GraphQL query from start to completion._

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchelen-gov** [comment]
The AC of this ticket has been resolved in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4699
It's recommended to either create a new ticket or change this AC to:

[Jenkins job](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/activity) metrics are logged in Prometheus/Grafana
- [ ] Total job time for `master` branch
- [ ] `vagovprod` build step time

**Comment by jefflbrauer** [comment]
Per @mchelen-gov closing this because we've done the work for CMS. It may be a good idea for FE team to do this for vets-website full build.
