### ISSUE TITLE
Remove COVID-19 PDF guide from Welcome Kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21568]
## Issue Description
We got a request from Abigail Sanford Pitman to remove the COVID-19 guide PDF from the [Welcome kit](https://www.va.gov/welcome-kit/) page.

---
## Tasks
- [x] Remove PDF from page
- [x] Review and publish
- [x] Notify stakeholder that change was made

## Acceptance Criteria
- [x] COVID PDF no longer on live Welcome Kit page

**Comment by RLHecht** [comment]
I removed the PDF and notified the stakeholder about it. Moving to validate and will close after deploy. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
PDF no longer on live site. Closing ticket.
