### ISSUE TITLE
Cheetah-Update messaging on Contact facility page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21563]
## Issue Description
In addition to providing the facility phone number on the Contact facility page, we would like to update the messaging when no facilities are available for online scheduling and when the user indicates they've already received a dose.

---

## Tasks
- No facilities online
- First dose received

## Acceptance Criteria
- [x] Changes are behind va_online_scheduling_cheetah feature flag

- [x] CONTENT - Copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/VAOS_for_Distribution_Copy-contact_facility.docx)
- No facilities online
- First dose received

- [x] If user clicks "stay informed" link, Then open the keep me informed page (`/health-care/covid-19-vaccine`) in the same window

- [x] ANALYTICS - Track "stay informed" link clicks
- _(Note- Similar implementation in #21274)_

- [x] DESIGN - Designs match the specs
- No facilities online https://www.sketch.com/s/aca1478c-8cfa-433e-8e06-d42b53aaa60d/a/4agKyPZ#Inspector
![Screen Shot 2021-03-16 at 11.12.05 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/1d43cf93-3353-439d-9f8e-66d24c2ea578)

- First dose received https://www.sketch.com/s/aca1478c-8cfa-433e-8e06-d42b53aaa60d/a/DP4WGAW#Inspector
![Screen Shot 2021-03-16 at 11.05.52 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/054afafe-677c-4b4b-8f9b-783d71d63131)

---

## Definition of Done

- [x] All acceptance criteria are met

- [ ] Cheetah flow [screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design/cheetah-flow) and [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) are updated
