### ISSUE TITLE
Medallia CSAT Scoring 

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#21560]
## Issue Description
_Our survey customers are used to having access to a (ForeSee) CSAT score to provide them relative directional information about their user satisfaction. We want to provide something similar with Medallia survey, however, scoring within Medallia is not on the same scale as ForeSee, so we likely need to figure out a way to develop our own score which can be used to relate/compare future satisfaction with past satisfaction_

---
## Tasks
- [ ] Review ForeSee CSAT Scoring model and document notable factors
- [ ] Review Medallia CSAT module, available data and document notable factors
- [ ] Document what Medallia scoring data can apply to a scoring model similar to what ForeSee provided

## Acceptance Criteria
- [ ] A recommended Medallia CSAT scoring option and/or model is documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
ForeSee CSAT scoring:

References:
- ForeSee website - https://www.foresee.com/blog/better-together-nps-csat/
- ForeSee white paper - http://www.foresee.com/assets/foresee-cxa-methodology-white-paper.pdf
- VA ForeSee CSAT Report

Notes:
- Seems to be based primarily on a 0-100 scoring model.
- ForeSee satisfaction (intercept) survey has 24 questions; most are rated 1-10.
- I have not been able to find definitive information on how ForeSee calculates their CSAT score.
- After speaking with other folks involved in the VA side of ForeSee, it seems nobody know how ForeSee calculates their CSAT score.
- It is apparent, we will not be able to replicate their score, which means anything we use or create with Medallia with have a level of variance and lack of direct relatability.

Medallia CSAT scoring:

References:
- To be added

Notes:
- Having a CSAT score with Medallia is very important as the ForeSee equivalent is widely and regularly used in leadership and other meetings.
- Medallia does have their own CSAT score, but it is also proprietary and it is unknown how much it does or does not related to ForeSee's score.
- We can (and are in the process of) pull Medallia rating data into DOMO to create a CSAT score report.
- We are not likely to replicate a ForeSee CSAT score with Medallia.
- We met with Account Experience leadership on 3/25 and proposed exploring running Medallia surveys alongside ForeSee surveys and analyzing the variance between satisfaction scoring to understand three primary factors: 1. Are the satisfaction scores close enough to utilize Medallia as is? 2. Are we able to use Medallia data in a way that produces a satisfaction score similar to ForeSee's? 3. Is there a standard delta we can share with leadership and teams to help them related future Medallia satisfaction score to historical ForeSee satisfaction scores?

**Comment by jwoodman5** [comment]
We are running the Medallia satisfaction survey through the end of May 2021 and will provide recommendation at that time. Dropping this in the backlog for now.

**Comment by jwoodman5** [comment]
The Medallia Satisfaction survey has been running since mid-September. VA leadership decided to use the following scoring model for Satisfaction scoring with the Medallia survey.

Take total number of 4/5 star ratings from "Please rate your experience on VA.gov today." and calculate as a percentage of total responses. The percentage of 4/5 star ratings _is_ the satisfaction score.

Ex.
Total 4/5 star responses = 60
Total 1-3 start responses = 40
Total responses = 100
Percentage of 4/5 star responses -=60%
VA.gov (Medallia) Satisfaction score = 60
