### ISSUE TITLE
[Design] My VA error: Design error for when we can't detect whether someone has health care or not

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21579]
## Background

Background in #21375 and [Slack](https://dsva.slack.com/archives/C909ZG2BB/p1615910203010200?thread_ts=1615909362.009500&cid=C909ZG2BB).

 If we can't determine if someone is a health care recipient or not because `GET user/` isn't working, we should show some sort of error letting them know that we aren't able to access health care information, so some information may be missing from the dashboard.

## Tasks

- [ ] Create error state for when health care endpoint is down and we can't detect if someone receives health care or not
- [ ] Review with team
- [ ] Work with copy
- [ ] Handoff to FE

**Comment by tressaellen** [comment]
@erikphansen or @sanlouise what is the solution for this? Would refresh work? Or is it more of a 'Try again later' situation? Also, I'm assuming we just won't show the health care section in this case, and this error would live at the top of the page. Can you confirm/deny?

@bethpottsVADEPO or @peggygannon could you weigh in on this error message as well?

**We couldn’t retrieve your health care information**

We’re sorry.  Something went wrong on our end and we couldn’t access your health care information. Please refresh or try again later.

![My VA Desktop can't reach health care.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/9dc8ab42-7f37-4c92-9b31-7508c60afa11)

**Comment by erikphansen** [comment]
This mock looks good to me. I can't say for certain if this sort of error is something that'd be resolved very quickly or take longer. So the language in this mock, "refresh or try again" seems totally reasonable.

**Comment by Samara-Strauss** [comment]
Question for maybe @sanlouise or @erikphansen — am I correct that if we can't access the health care endpoint, that means this error would show on everyone's dashboard regardless of whether they actually have health care or not? That's what I am expecting and is totally fine, but I just want to make sure because I think we might want to finesse the copy a little bit to reflect that. Saying "we can't load your health care information" might be confusing for people who don't have any, so I at least want to ask Peggy/Beth if they have thoughts on that.

Otherwise, the UX on this is totally what I would expect, and I can get this into the documentation!

**Comment by erikphansen** [comment]
Correct! This is for the situation where we cannot access the data that would tell us one way or another if someone has VA health care.

**Comment by Samara-Strauss** [comment]
Got it! OK, given that — @bethpottsVADEPO or @peggygannon re: the error message copy suggested above, do you think we should make it more neutral? If the error message is showing, we don't actually know if someone has health care or not, so saying "we can't load your health care information" might be confusing for people who don't have any. However, if this isn't a big deal or we want to prioritize the health care audience, we can leave the messaging as-is. Just wanted to get your thoughts!

**Comment by bethpottsVADEPO** [comment]
@Samara-Strauss @tressaellen I agree that it could be confusing. I will get back to you today with suggestions.

**Comment by tressaellen** [comment]
Content will be tracked in #21872, so I'm closing this ticket.
