### ISSUE TITLE
Dependency Verification - Wire up api call for diaries update submission

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#21574]
## Description
The GET request for diaries was recently completed in #20291. The second part of the dependency verification modal is to wire up the api call for updating the diaries service when a veteran needs to make a change to their dependents. 

## Considerations
- Error states? What is the best way to handle errors when the server returns one instead of a 200 response? 
- This is technically a form submission, do we need to display any sort of privacy agreement?

## Tasks
- [ ] wire up api call to action and reducer
- [ ] handle error states and 200 responses properly

## Acceptance Criteria
- [ ] above tasks are complete
- [ ] PR submitted

**Comment by jason-gcio** [comment]
For first version, we are going to let the 0538 handle the diary update entry.  Learned today that Central Mail has an OCR process that auto picks these up and processes them.

**Comment by jason-gcio** [comment]
@kathleencrawford - can you check the url for the endpoint?

**Comment by kathleencrawford** [comment]
> @kathleencrawford - can you check the url for the endpoint?

`/v0/dependents_verifications`
