### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST & PLAYBOOK" for VA Columbia Missouri health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21617]
# High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Columbia Missouri system Legacy Site](https://www.columbiamo.va.gov)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-15 Playbook locations](https://drive.google.com/drive/folders/1V9ckTMdvmvbvpS7D6yvIco3Phgc4gafN)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_589A4	Harry S. Truman Memorial Veterans' Hospital
- [x] vha_589G8	Jefferson City VA Clinic
- [x] vha_589GE	Kirksville VA Clinic
- [x] vha_589GH	Lake of the Ozarks VA Clinic
- [x] vha_589GX	Mexico VA Clinic
- [x] vha_589GY	St. James VA Clinic
- [x] vha_589JA	Sedalia VA Clinic
- [x] vha_589JD	Marshfield VA Clinic
- [x] vha_589GF	Waynesville VA Clinic (Formerly Fort Leonard Wood VA Clinic)

* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#21617 Create new Health Services "LIST & PLAYBOOK" for VA Columbia Missouri health care [BA] -  Completed and moved to Validate; Playbook created and Health Services matched up to 95 Health Service list.
