### ISSUE TITLE
Design for custom picker

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#21613]
# User Story
As a user, I want to access a custom picker that can be used via voice control on iOS and Android. 

# Background
See #21131 and #20779 for background on why a UI for a custom picker is needed. 

### iOS
- Picker options cannot be accessed with Voice Control

### Android
- Text in the dropdown is smaller than non-dropdown text
- Unable to apply focused state to the dropdown box
- Field error state will not appear until user hits “Save”

# Tasks
- [ ] Review options for how to approach custom picker put together by front-end team here: https://adhoc.slack.com/archives/C01AHEGA7TK/p1615491737082400
- [ ] Select approach to move forward with
- [ ] Create corresponding UI design and A11y requirements

**Comment by msmanak** [comment]
https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1616171830216?sen[…]a40c046eb5ac3dd733614&key=972fbca0-5216-4a0a-87bb-b65df6ad4c7f
I would love if you could leave comments in Mural instead of thread

**Comment by msmanak** [comment]
![Slice-picker.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/d4340259-322f-42cf-83ac-07c041ead773)

**Comment by msmanak** [comment]
## Final design:
![Slice-Picker 2.0.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/3e185476-734b-46bd-b736-b7e5745f0163)


Link:

- Half screen (5> Less): https://adhoc.invisionapp.com/d/main?origin=v7#/console/21180613/447955927/preview?scrollOffset=2935

- Full screen:(5< More) https://adhoc.invisionapp.com/d/main?origin=v7#/console/21180613/448387584/preview?scrollOffset=2935

## Design decision:
Overlay: # Base at 80%
List: use existing list, add checkmark in place of chevrom

**New**: 
list heading:  Topic centered with cancel/done (following top navigation rules)
