### ISSUE TITLE
Translation effort for updated content on top part of vaccine page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21612]
## Issue Description
We made updates to our COVID-19 vaccine page in the section underneath the first H2. Because this part of the page was reworked so much and new copy was added, we need to have this content translated again for both our Tagalog and Spanish pages.

Copy was sent to the translation team on 3.16.

## Tasks
- [x] Update Spanish page with translated copy (Selina)
- [x] Update Tagalog page with translated copy (Selina)
- [x] Review Spanish page and publish (Randi)
- [x] Review Tagalog page and publish (Randi)
- [x] Send link to live site to VHA translation team for final review (Randi)

## Acceptance Criteria
- [x] Spanish and Tagalog pages are live with updated content

**Comment by RLHecht** [comment]
@lunascoop Here is the Spanish copy back from the translators: [https://app.zenhub.com/files/133843125/995e3ad1-f1d8-4488-b5dd-78167e20b363/download](https://app.zenhub.com/files/133843125/995e3ad1-f1d8-4488-b5dd-78167e20b363/download)

**Comment by lunascoop** [comment]
@RLHecht the page is ready for review. http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
I reviewed and published this page. Will send to VHA translation team for final review.

**Comment by RLHecht** [comment]
@lunascoop Here's the translated copy for Tagalog: [https://app.zenhub.com/files/133843125/e614ca17-0f9f-4908-8388-fa04abb12db0/download](https://app.zenhub.com/files/133843125/e614ca17-0f9f-4908-8388-fa04abb12db0/download)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lunascoop This new law passed yesterday, so we had to get updated info live on the English page today. We couldn't have the Tagalog page totally out of sync so I needed to make these updates to that page today. I will open a ticket for the next steps for translating latest updates.

In the meantime, please double check the live site and send to Mateo's team for a check as well.

Thank you!

**Comment by RLHecht** [comment]
This work is completed. Closing ticket.
