### ISSUE TITLE
Null access to care info in VAMC

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21625]
## Issue Description
[Laramie mobile clinic](https://www.va.gov/cheyenne-health-care/locations/laramie-va-mobile-clinic/) has an unpopulated display of unpopulated wait time 

![image](https://user-images.githubusercontent.com/55411834/111388303-a5262180-8674-11eb-94e3-41006047c8c8.png)

---
## Tasks
- [ ] Change logic to ensure null fields are not rendered on the front end. 

## Acceptance Criteria
- [ ] If user satisfaction data is not available, the area does not display. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
