### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST & PLAYBOOK" for VA Wichita health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21624]
## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Wichita system Legacy Site](https://www.witchita.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-15 Playbook locations](https://drive.google.com/drive/folders/1V9ckTMdvmvbvpS7D6yvIco3Phgc4gafN)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [ ] vha_589A7	Robert J. Dole Department of Veterans Affairs Medical and Regional Office Center
- [ ] vha_589G2	Dodge City VA Clinic
- [ ] vha_589G3	Liberal VA Clinic
- [ ] vha_589G4	Hays VA Clinic
- [ ] vha_589G5	Parsons VA Clinic
- [ ] vha_589G7	Hutchinson VA Clinic
- [ ] vha_589GW	Salina VA Clinic
- [ ] vha_589QB	Sedgwick County VA Clinic
- [ ] vha_589QC	South Parklane VA Clinic
- [ ] vha_589QD	Wichita VA Mobile Clinic

* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [ ] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer
