### ISSUE TITLE
TUD: Add help content to Find Accounts page

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#21636]
## Issue Description
As a TUD app user, I would like the ability to view help content on the `Find Accounts` page so I can read how to complete a task without navigating away from the page

---
## Tasks
- [ ] Implement design changes to accommodate help content  on `Find Accounts` page
- [ ] Add help content to `Find Accounts` page

## Acceptance Criteria
- [ ] I see help content on the `Find Accounts` page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
