### ISSUE TITLE
Update guidance in IA Request template and documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#21634]
## Issue Description
Now that the IA Request touchpoint has moved to earlier in the Collaboration Cycle process, it is unlikely that VFS teams will have the requested artifacts available at the time they submit the ticket. This is okay, however the guidance should be updated to reflect that.

---
## Tasks
Update the following documentation to better state what is expected of teams regarding the requested artifacts:
   - [x] [IA Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis%2C+shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=ia-request.md&title=IA+Request+%5BTeam-Name%2C+Feature-Name%5D)
   - [x] [IA Touchpoint](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-ia-request.md)

## Acceptance Criteria
- [ ] VFS teams understand when to submit an IA Request and when to share requested artifacts.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
@shiragoodman I updated the IA request issue template, will you take a look?  I updated timing and made some tweaks to requested artifacts and the IA worksheet info to clean it up.

**Comment by shiragoodman** [comment]
@mnorthuis this looks good to me. Can you make similar changes to the IA Touchpoint documentation?

**Comment by mnorthuis** [comment]
Both the IA request and the touchpoint docs are now updated!
