### ISSUE TITLE
[Pre-release] Deploy content-build to new staging S3 bucket

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#21637]
## Problem Statement
We need to deploy the content from the content build repository to the new, unused dedicated content S3 bucket

---
## Tasks
- [ ] Create a content deployment script in the `devops` repo
    - Similar to the `vets-website` deployment script, but omits application-related build pieces
       - I believe this is where the [current `vets-website` deploy script](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/roles/deploy-vets-website/)
- [ ] Set up Jenkins job to deploy content

## Acceptance Criteria
- [ ] The Jenkins job successfully builds the static content files and deploys them to the appropriate environments

**Comment by timwright12** [comment]
Files and directories used for the dev deploy:

- ansible/deployment/config/content-build-dev.yml (will need staging file)
- ansible/deployment/roles/deploy-content-build (probably don't need to change anything here)

Doing a global search for content-build should also turn up all instances

**Comment by jhonnyoddball** [comment]
This PR [8736](https://github.com/department-of-veterans-affairs/devops/pull/8736) deployed content and app builds to S3 buckets in staging

**Comment by jhonnyoddball** [comment]
Content was verified
