### ISSUE TITLE
TUD: Make Find Accounts homepage and current homepage the FAQ page

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#21633]
## Issue Description
As a TUD app user, I would like to have Find Accounts page as the first page I land on when I navigate to the app. 
I would also like to see the content on the current homepage moved to an FAQ page.

---
## Tasks
- [x] Make Find Accounts make the homepage
- [x] Create an FAQ page and move all `index.js` content to that page
- [x] Update all links to `/find-accounts` and add links to new FAQ page 
## Acceptance Criteria
- [x] I see the Find accounts page as the first page when I navigate to the app
- [x] I see the new FAQ page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
