### ISSUE TITLE
Publish the Newsletter style guide V1

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#21643]
# User story
As a Newsletter content submitter*, I want to have grammar and tone guidelines to follow, so that I can reduce the effort around copyediting with the Content Team.

As a Content Team member, I want to publicize guidelines to Newsletter content submitters*, so that content submissions are as error-free as possible.  This allows for a smoother newsletter production process.

.* A Newsletter content submitter is usually a Platform Team PM, but can sometimes be a Platform Team SME.

# Tasks
- [x] Write an overall doc intro blurb.
- [x] Add March examples.
- [ ] Write short intros for each topic we have examples for

# Acceptance criteria
* Newsletter content submitters are able to access the Newsletter style guide.
* Content Team members are able to begin socializing and enforcing Newsletter Style Guide usage in Sprint 49.

# Reference info
* [Newsletter style guide in Amy's personal Conf space](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1170440248/Platform+Newsletter+style+guide)
* Future style guide additions:
  * Add sub-blurbs to examples section.
  * Fill in the following sections:
    * Remaining examples
    * Word choice
    * Tone and voice
  * QA for ___.
  * (stretch) Collaborate with SD on adding MailChimp formatting.
  * Move Confluence page to public space (currently in personal space).

**Comment by lianilychee** [comment]
Liani and Amy to refine "tasks" list, to populate the shorter list for publishing.

**Comment by lianilychee** [comment]
Pause pending March edition draft!

Short list (we need this info before making the newsletter style guide public):
- Intro blurb <-- Liani to draft, give Amy a skeleton before Thurs
- Add March examples
- Short intro for each topic that we have examples for

**Comment by lianilychee** [comment]
- Will be focus today, aiming for being in a publish-able state by end of next week

**Comment by lianilychee** [comment]
* Will tackle short list and publish by EOD Weds from two updates above

**Comment by lianilychee** [comment]
* EOD goal: Adding March examples and not worrying about refinement for this version

**Comment by lianilychee** [comment]
Today:
- Add remaining examples and experiment w formatting them w info panels
- Will spend Tues and Weds developing all blurbs and intro, and explaining why we did what we did
