### ISSUE TITLE
Test User Accounts_Usability Testing Week 3

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#21647]
## Issue Description
Usability testing March 17- March 31 
---
## Tasks

- [x] Schedule tests
- [x] Use guide to receive feedback about functionality of prototype
- [x] Synthesize notes from test to share with team

## Acceptance Criteria
- Conduct testing with participants on the following dates:

- [x] Th 3/25 12:30pm ET
- [x] Fr 3/26 10:00am ET
- [x] Fri 3/26 1:00pm ET
- [x] Mon 3/29 4:00pm ET 
- [x] Tue 3/30 12:00pm ET
