### ISSUE TITLE
Last Mile Launch Activities for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21656]
## Background
Ensure we have all items addressed for CH31 to be launched on April 19

## Tasks
- [x] Update final copy version (ticket in ready)
- [x] Update per 508 feedback (ticket in ready)
  - first item is platform level, rest could be 2 separate tickets
- [x] Update launch task list
- [x] Walkthrough, e2e FE + BE (3/24)
- [x] QA items in TestRail addressed (3/25)
- [x] Update Release Plan (like [this](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/release-plan.md))
- [x] Staging Review (4/9/2021)
- [x] Privacy and Security Review (async)
- [x] UAT plan
- [x] Schedule Perigean (Use research plan with dates 4/13-16))
**On April 12+**
- [ ] Obtain endpoint and creds
- [ ] Conduct UAT

## Acceptance Criteria
- [x] Items are tracked and ready up until the April 12 items
