### ISSUE TITLE
Rollout of the GitHub Teams initiative MVP to VA.gov

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2166]
Getting teams organized and using GH teams base before connecting access and using them as sources of truth. 

## AC
- [ ] establish process for GH teams
- [ ] Ensure Teams have created and established GH teams. 
- [ ] Make sure process is in place for all teams and they are following it
- [ ] Work with Onboarding to ensure new teams follow the process

**Comment by ricetj** [comment]
@nwalke will break this out into a few tickets.

**Comment by ricetj** [comment]
We need the team to match the logical way we want it to work.

**Comment by ricetj** [comment]
Need more talks about the project's future and the most effective way to implement it.

**Comment by ricetj** [comment]
Need to update the following: 
- [ ] Jumpbox rebuild every day (Monday - Saturday)
- [ ] Updating the doc to remove a user right away

**Comment by jhouse-solvd** [comment]
@ricetj Is this rollout something that still has active / pending / to-be-discovered work? If not, can we close it out?

**Comment by ricetj** [comment]
> @ricetj Is this rollout something that still has active / pending / to-be-discovered work? If not, can we close it out?

you can close this one out, but this topic is something we should chat about in-depth during a call.

**Comment by jbritt1** [comment]
This work still relevant / necessary?

**Comment by jhouse-solvd** [comment]
There is currently some clean-up happening around GitHub teams. When and if a larger initiative is decided, we will re-scope and define new criteria accordingly. 

Closing.
