### ISSUE TITLE
[Cheetah MVP] Recurring COVID clinic report

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21668]
## Issue Description
As DEPO, I would like a daily report of COVID clinic information used for scheduling so that I can communicate with clinics about appropriate set up.

Similar example https://docs.google.com/spreadsheets/d/16FoQCxBXJHo9gIwZsl24IesexrXU84DCKKp0wKQrWEo/edit#gid=0

Key communication points:
- Identify if a facility has set up their second dose clinic (instead of or in addition to their first dose clinic)
- User-facing clinic name includes COVID/clearly identifies what the appointment is for

### Questions
- Can we automate this?

---
## Tasks
- [ ] Create sample report for DEPO review
- Facility ID
- Clinic ID
- User-facing clinic name
- Display to user? true/false

## Acceptance Criteria
- [ ] DEPO-approved report

- [ ] Repeatable artifact/process

**Comment by grossb1** [comment]
I have a re-runnable executable that we can hand off to whomever wants to run this report.
