### ISSUE TITLE
Update the 'What's New' section on design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#21673]
## Issue Description
The What's New section of design.va.gov hasn't been updated since Sept 10, 2020 before the DST was officially a team. We've made a number of updates to the DS so would like to post them so teams are aware of what's new on the DS. 

---
## Tasks
- [x] Draft document with the improvements / updates made to the design system 
- [ ] Post updates on what's new on design.va.gov

## Acceptance Criteria
- [ ] Text approved
- [ ] What's new is updated
---
