### ISSUE TITLE
[FSR] Usability test prep

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#21677]
## Issue Description
_Prior to the FSR's usability study kicking off, we need to prep a notes spreadsheet, schedule debrief sessions, create a Mural board to document takeaways identified after sessions or during debriefs, and conduct the pilot session_

---
## Tasks
- [x] _Notes spreadsheet is created_
- [x] _Pilot session is conducted and any changes are incorporated into the conversation guide_
- [x] _Mural board for debrief sessions is set up_
- [x] _Debrief sessions are scheduled_

## Acceptance Criteria
- [x] _The identified tasks above are completed_
- [x] _The notes spreadsheet is linked to this ticket_

**Comment by rileyorr** [comment]
Everything's been set up and the notes spreadsheet can be accessed [here](https://docs.google.com/spreadsheets/d/1hfu7chDlK6L1njnwc8rYaSlKw8DqZGrpSlDv8Xs592o/edit?usp=sharing).
