### ISSUE TITLE
[Content-Review] Internal Review, Proof read and correct plain language, System HS, and common sence conntent on all pages for VA Palo Alto health care [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21688]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[Health Service Library](https://drive.google.com/drive/folders/1_3ThJKPJ6r1U-zEM-L6iyCWsgXbAypIz)
[VISN-21 Internal Review Folder](https://drive.google.com/drive/folders/1z5U48stIVVaG5PnaKMJs8RlNUgUZ32N6)
[Review template for review](https://drive.google.com/drive/folders/18Oo5eoy4yn0LyTtQ3OLdNgGqN1FUof81)

## Tasks
**NEW ADDED TASKS**
_Palo Alto has a total of 61 System Health Services to replace.
- [x] Update all System Health Services with HTML code from Health Service Library resource.
- [x] Assure that intro line is correct (e.g.: "Care we provide at VA Gulf Coast health care")
**DO NOT UPDATE COVID-19 Health Services**

* Review NOT needed (Double check that updated Best Bet html has been added to pages. Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [x] Location Listing Page 
- [x] History    
- [x] Internship and Fellowship 
- [x] Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x] System Page 
- [x] Health Services Listing Page (Health service on this page only)
- [x] About us Page 
- [x] Mission-Vision 
- [x] Leadership Listing Page 
- [x] Work with Us Page 
- [x] Jobs and Careers
- [x] Policies Page 
- [x] Contact us 
 
* Facility Pages - review intro, Plan for your visit, if any. (DO Not review health services this is at System level only)
- [x] 640	Palo Alto VA Medical Center
- [x] 640A0	Palo Alto VA Medical Center-Menlo Park
- [x] 640A4	Palo Alto VA Medical Center-Livermore
- [x] 640BY	San Jose VA Clinic
- [x] 640GA	Capitola VA Clinic
- [x] 640GB	Sonora VA Clinic
- [x] 640GC	Fremont VA Clinic
- [x] 640HA	Stockton VA Clinic
- [x] 640HB	Modesto VA Clinic
- [x] 640HC	Major General William H. Gourley VA-DoD Outpatient Clinic

* Observe and report (Correct any spelling errors)
- [x] Performance Page
- [x] Make an Appointment
- [x] Register-for-Care
- [x] Billing
- [x] Contact-us		
- [x] Dav-vans
- [x] Medical-Records
- [x] Operational Status
- [x] Pharmacy
- [x] Caregiver
- [x] Homeless
- [x] LGBT
- [x] Mental
- [x] Minority
- [x] Patient
- [x] Returning Service member
- [x] Suicide prevent
- [x] Women-vet
- [x] Campus Map
- [x] Chaplain Services

## Acceptance Criteria
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.

**Comment by larrywest52** [comment]
Done
