### ISSUE TITLE
Audits for KPI Standardization

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21697]
## High Level User Story/ies
As a VFS PM, I need to see the analytics that I care about without having to wait on a Platform team member to support me so that I can track my product's success easily.

As a Platform Analytics team member, I need to understand what data VFS teams have requested in the past and the datasets we have so I can develop datasets and visuals that align with both the KPI framework (Platform quality standards) and customer needs.

## Hypothesis or Bet
**If** _we audit our data and previous reporting requests_ **then** _we expect to understand the most common dashboarding needs and prioritize how we structure our datasets_.

## Tasks/Issue Breakdown
- [x] Consolidate `event labels` from Google Analytics, ForeSee, and Medallia into one place. @jonwehausen @laurensimpson14 #21698 
- [x] Audit & document the Domo queries: what we're using, what should be archived/sunset (which ones have errors, etc.), what should be added, high cost datasets & (stretch: how we can optimize them) - @JasonTheBearded #21700 
- [x] Revisit VA.gov "Products list" - @joanneesteban to follow up with Rachael
    Use the VA.gov Product Directory as the source of truth. OCTODE uses "products" and "features" interchangeably. We can align our KPI dashboards to the products listed here, and roll them up into Benefit Hubs.
- [x] Revisit `Benefit Hub` and `Product` Content Grouping in Google Analytics - @laurensimpson14 #21701
- [x] Audit Domo Dashboards - usage from teams (why they're using/not using, sunset dashboards) - @JasonTheBearded @joanneesteban @mandy-uxd #21702
- [x] Audit Team of Teams slides for how VFS PMs are sharing their data - @joanneesteban #21705
~- [ ] Audit previous dashboard requests - @mandy-uxd #21703~ Will be a part of the larger initiative
~- [ ] Audit previous dashboard user research - @mandy-uxd #21704~ Will be a part of the larger initiative
- [x] Audit Domo Groups - @joanneesteban #21706

## Definition of done
- [x] Issues are completed

## IA Resources
https://app.moqups.com/Rnc4BDEKrA/view/page/abd763ecc
https://docs.google.com/spreadsheets/d/1YucOtYihweNPI1gYtCgdsinKQmH4DMuSgPaSgJMfyYk/edit#gid=948269660

VA.gov Product Directory: https://docs.google.com/spreadsheets/d/1U0InrpgnX0pvrZ-lDbkMuc9Qg7dnPLbcnKXpzpVR8zM/edit#gid=913478450

**Comment by joanneesteban** [comment]
Add audit doc links to [markdown](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/teams/vsp/teams/insights-analytics/kpi-standardization-audits.md)

**Comment by joanneesteban** [comment]
Added in the ticket above:

Use the [VA.gov Product Directory ](https://docs.google.com/spreadsheets/d/1U0InrpgnX0pvrZ-lDbkMuc9Qg7dnPLbcnKXpzpVR8zM/edit#gid=913478450)as the source of truth. OCTODE uses "products" and "features" interchangeably. We can align our KPI dashboards to the products listed here, and roll them up into Benefit Hubs.

**Comment by joanneesteban** [comment]
Audits completed at the beginning of this initiative. Closing this ticket.
