### ISSUE TITLE
Consolidate Event Labels

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21698]
## Issue Description
Consolidate the `event labels` from our available datasets so that we can 

---
## Tasks
- [x] Consolidate Google Analytics WBC `event labels`
- [ ] Consolidate any ForeSee event labels
- [x] Consolidate any Medallia event labels
- [x] Document this consolidation in a readable format in the [Analytics team folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics)

## Acceptance Criteria
- [ ] It's easy for Platform Analytics team members to find and understand our datasets' events

**Comment by jonwehausen** [comment]
### Next Steps
- Start to consolidate `tracking-` documentation from here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/google-analytics
- Create a document for Medallia `survey-` events, document the mappings of custom medallia events to our `survey` taxonomy
   - _Reference original medallia implementation ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18278_ 
- Create a document for Navigation Action Lookup events: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000378?orgId=oXPY3GFFQwaHnjNHpFLyFg

**Comment by jonwehausen** [comment]
cc: @laurensimpson14

**Comment by laurensimpson14** [comment]
@jonwehausen to QA

Here is a link to the document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/b7ba80bb0f7a93eac5cfb2b599007379f5c59859/teams/vsp/teams/insights-analytics/ga-events-data-dictionaries.md

**Comment by joanneesteban** [comment]
@jonwehausen @laurensimpson14 This is looking AWESOME. Do y'all need more time next sprint to finish up, or is this good to go? There's some plain language that we should add here (i.e. "benefit hub" as a column title in lieu of "output"), but that's lower priority for now.

CC: @JasonTheBearded check out Lauren & Jon's work above.

**Comment by JasonTheBearded** [comment]
This is WONDERFUL. Thank you @jonwehausen and @laurensimpson14 for your work on this!

**Comment by jonwehausen** [comment]
@laurensimpson14 

### Here's a list of the items I have to inch to closure for the event label consolidation & content grouping:
- Check out branch with a couple updates here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/ga-event-label-[…]ams/vsp/teams/insights-analytics/ga-events-data-dictionaries.md
  - _Notice the Medallia additions with definitions, would like to get to a similar level of documentation for everything: event name --> plain language of what that event is/does_
- Updating some of the table labels for "Output" to be more plain language i.e "Benefit Hub"
- Remove pieces from each individual document that was carried over so our final document is mostly event label and whatever context is needed. An example of something that can be removed is the component library roll out sprints schedule.
    - _Ideally this document is really just a repository of events_
- Adding plain language definitions to custom dimensions + metrics and updating with most recent names + values
Answer to question on decision review content group, updating within table
- Publishing out GTM changes for nav action lookup
   - _There is currently a conflict because there was a publish of that nav action lookup table before your version_
   - _If you could abandon your changes and re-create them within the "21701 - Content Grouping Updates" workspace I'd greatly appreciate it_

**Comment by jonwehausen** [comment]
### Next Steps
- @laurensimpson14 to begin adding definitions for custom metrics + dimensions
