### ISSUE TITLE
Audit Dashboard research

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21704]
## Issue Description
Audit previous Analytics team dashboarding research so that we can better understand past user research and don't need to do deep dive user research to understand basic user needs.

---
## Tasks
- [ ] Audit previous dashboarding research
- [ ] Document in the Analytics team folder

## Acceptance Criteria
- [ ] Platform Analytics understands the dashboarding feedback our customers provided in the past

**Comment by joanneesteban** [comment]
Audit can be found in [Analytics Platform research deck.](https://docs.google.com/presentation/d/1snS88WVbtgR16Fn4EquiWDre7oG_ia-vdnW9aQJWpYA/edit)
