### ISSUE TITLE
Audit Team of Teams slides

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21705]
## Issue Description
Audit the Team of Teams slides for analytics shares so that we can understand what type of data VFS PMs and POs have shared and how they visualized that data.

---
## Tasks
- [x] Audit Team of Teams slides
  - [x] What type of data was shared
  - [x] How the data was visualized
  - [x] Which mediums were used for visualizations
- [x] Document findings in the [Analytics team folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics)

## Acceptance Criteria
- [x] Platform Analytics understands what type of data was shared and how it was shared in Team of Teams so that we can create data visuals that teams can drop into their Team of Teams slides with little effort.

**Comment by joanneesteban** [comment]
Audit documented in [Visualizations audit](https://docs.google.com/presentation/d/1gapGkzCqnlCURbjz6rtH2A8JsJlzZn-D_6GFobd3cU0/edit)
