### ISSUE TITLE
Audit & Fix Domo Groups

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21706]
## Issue Description
Audit and update the Domo User Groups so that we can more easily and accurately share dashboard permissions with VFS teams.

---
## Tasks
- [ ] All user groups have updated team names
- [ ] All user groups have updated team members
- [ ] All user group permissions are updated
- [ ] Remove any offboarded Domo users

## Acceptance Criteria
- [ ] Platform Analytics can easily share new or updated dashboards with specific user groups

**Comment by joanneesteban** [comment]
[Audit Doc](https://docs.google.com/spreadsheets/d/1dUIy9udnWCPJGNh2bXkeo6C7Lu8VyCHqA-oymmfeyZc/edit#gid=0)

**Comment by joanneesteban** [comment]
Looking deleting users:
- If we delete users, do we lose their previous activity?

Will pause on changing any group permissions/types until we determine the best way forward with any PDP permissions because it looks like we won't be able to change group types after they've been changed.

**Comment by joanneesteban** [comment]
Social user view, with no `Group` access:
![image](https://user-images.githubusercontent.com/48964695/112032413-b8bd0680-8b12-11eb-9d78-5b56d4e91e46.png)

**Comment by joanneesteban** [comment]
Test view of Social User Group with no Alert permissions:
![image](https://user-images.githubusercontent.com/48964695/112033061-6a5c3780-8b13-11eb-9635-3e19b7c856d2.png)

**Comment by joanneesteban** [comment]
New process for removing users located [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/insights-analytics/offboarding-domo.md).

**Comment by joanneesteban** [comment]
New process created. Will need to audit again in the future. Closing this ticket.
