### ISSUE TITLE
Audit Content Groups in Google Analytics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21701]
## Issue Description
Audit and document what needs updates in the `Product` and `Benefit Hub` Content Groups in Google Analytics so that Platform Analytics aligns its Google Analytics and BigQuery datasets to the VA.gov products.

---
## Tasks
- [ ] All of the VA.gov products are added to the Product Content Group
- [ ] All of the VA.gov benefit hubs are added to the Product Content Group
- [ ] Document all standard GA event tracking that need to be added to the Product Content Group
- [ ] Document all standard GA event tracking that need to be added to the Benefit Hub Content Group
- [ ] _Stretch:_ Update all Product Content Group event tracking
- [ ] _Stretch:_ Update all Product Content Group event tracking

## Acceptance Criteria
- [ ] Platform Analytics understands what will need to be updated in the Product and Benefit Hubs

---
## IA Resources
https://app.moqups.com/Rnc4BDEKrA/view/page/abd763ecc
https://docs.google.com/spreadsheets/d/1YucOtYihweNPI1gYtCgdsinKQmH4DMuSgPaSgJMfyYk/edit#gid=948269660

**Comment by joanneesteban** [comment]
@jonwehausen for awareness until Lauren's added to the repo.

**Comment by jonwehausen** [comment]
## Next Steps
- Setup the GTM workspace for content grouping updates 
- Identify and update lookup tables for additional products, updating current null page paths
- Develop documentation for all content groupings

**Comment by joanneesteban** [comment]
@laurensimpson14 to share audit document.

**Comment by laurensimpson14** [comment]
@jonwehausen the doc is complete: https://github.com/department-of-veterans-affairs/va.gov-team/blob/b7ba80bb0f7a93eac5cfb2b599007379f5c59859/teams/vsp/teams/insights-analytics/ga-events-data-dictionaries.md

@jonwehausen to complete GTM QA

**Comment by jonwehausen** [comment]
Thanks @laurensimpson14 !

Please find my QA of the Products Content Groupings here: 

### Products
Page visited for test case | Product name | Page Path(s) RegEx within GTM lookup table | Test Screenshot | Test Status | Notes
| -- | -- | -- | -- | -- | -- |
www.va.gov/pittsburgh-health-care<br>www.va.gov/erie-health-care<br>https://www.va.gov/lebanon-health-care/ | VAMC | `^.*-health-care` | ![image](https://user-images.githubusercontent.com/48527022/112891612-5762dd80-90a6-11eb-9465-e5f867176da8.png) | ✔️ **PASS** | Was accurate for `lebanon-health-care` and `erie-health-care` as well 
www.va.gov/profile/direct-deposit <br> www.va.gov/change-direct-deposit | Direct Deposit | `(^/change-direct-deposit\|^profile/direct-deposit)` | ![image](https://user-images.githubusercontent.com/48527022/112893575-d8bb6f80-90a8-11eb-9f7f-e86091f7194e.png) | ✔️ **PASS** 
www.va.gov/profile | Authenticated Experience - Profile 2.0 | `^/profile.*` <br>**_below the direct deposit specific rule as not to conflict_** | ![image](https://user-images.githubusercontent.com/48527022/112893761-17e9c080-90a9-11eb-91a5-1e8c25f20b6c.png) | ✔️ **PASS** | 
www.va.gov/coronavirus-chatbot | COVID-19 Chatbot | `^/coronavirus-chatbot.*` | ![image](https://user-images.githubusercontent.com/48527022/112894141-7dd64800-90a9-11eb-84b1-8e4b72b31874.png) | ✔️ **PASS** 
www.va.gov/performance-dashboard | Performance Dashboard | `^/performance-dashboard.*` | ![image](https://user-images.githubusercontent.com/48527022/112894228-9e9e9d80-90a9-11eb-95f0-2f5f5d9c2b84.png) | ✔️ **PASS**
www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction | Careers and employment - Personalized Career Planning and Guidance Chapter 36 (28-8832) | `^/careers-employment/.*` | ![image](https://user-images.githubusercontent.com/48527022/112895094-aa3e9400-90aa-11eb-9fbb-45768e063da6.png) | ⚠️ **DOES NOT PASS** | - This RegEx should be updated to be `^careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/.*` specifically for the product 28-8832 <br><br> The Careers & Employment pages will be covered under the benefit hub CG
www.va.gov/privacy-policy | Privacy Policy | `^/privacy-policy.*` | ![image](https://user-images.githubusercontent.com/48527022/112895669-66985a00-90ab-11eb-93f0-da1fd0be8357.png) | ✔️ **PASS**
www.va.gov/disability/about-disability-ratings.* | Disability Ratings Calculator | `^disability/about-disability-ratings.*` | ![image](https://user-images.githubusercontent.com/48527022/112896371-4d43dd80-90ac-11eb-9d6a-d6c8cf509972.png) | ⚠️ **DOES NOT PASS** | This URL is dead unfortunately, will need to update to `^`disability/view-disability-rating.*` 
www.va.gov/resources | Resources & Support | `^resources.*` | ![image](https://user-images.githubusercontent.com/48527022/112896573-9136e280-90ac-11eb-83a9-3007e42cdc2d.png) | ✔️ **PASS** 
www.va.gov/my-va | Personalized Tools - Saved my Benefits Preferences | `^/my-va.*` | ![image](https://user-images.githubusercontent.com/48527022/112897836-1969b780-90ae-11eb-9203-03cd02e5b019.png) | ⚠️ **DOES NOT PASS** | This should be updated to be Personalized Tools - My VA



### Content Grouping Changes
Page Path Regex | Product Name | Add/Modify/Remove | Notes
| -- | -- | -- | -- | 
`^/careers-employment/vocational-rehabilitation/apply/.* | Veteran Readiness and Employment Form CH31 (28-1900) | ➕ **Add**
`^/disability/about-disability-ratings.*` | Disability Ratings | 🌀 **Change** | Adjust to be `^disability/view-disability-rating/.*`
`^/health-care/covid-19-vaccine/stay-informed/.*` | COVID-19 Vaccination | ➕ **Add**
`^covid19screen.* | COVID-19 Screening Tool | ➕ **Add** | this will include all of the [subsequent URLs](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.filter=covid19&explorer-table.plotKeys=%5B%5D/) of the covid19 screening tool 
`^va-payment-history/.*` | Veteran Payment History | ➕ **Add** | This technically doesn't really have a benefit hub as this feature spans education, disability, and education benefits 
`^coronavirus-veteran-frequently-asked-questions.* | COVID-19 FAQs | ➕ **Add** | This should capture all of the foreign language pages 
`^/my-va.*` | Personalized Tools - Saved by Benefits Preferences | 🌀 **Change** | Adjust to be Personalized Tools - My VA
`^/manage-va-debt/your-debt.*` | Debt Management - Manage Your VA Debt | ➕ **Add **
`^manage-va-debt/request-debt-help-5655.*` | Debt Management - Financial Status Report (5655) | ➕ **Add**

**Comment by jonwehausen** [comment]
### QA Content Groupings - Benefit Hubs

@laurensimpson14 

**Other than below changes, benefit hub page paths were verified & confirmed **

### Content Grouping Changes
- [ ] Add a lookup BEFORE existing `^health-care.*` to be `^health-care/get-medical-records.*` --> To include Medical Records within "Records" rather than "Health Care"
- [ ] Remove `^/profile.*` completely -- we've got this granular enough within the Products lookup and profile doesn't really have a benefit hub 
- [ ] Remove `^/va-payment-history` completely -- as this spans across multiple benefit hubs and have more granular at product level 
- [ ] Determine proper benefit hub & product for ^/decision-reviews pages and update
- [ ] Remove duplicate entry for `^records.*`

Verified using [this report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210308&_u.date01=20210328&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22www.va.gov%22,0%5D%5D&_r.drilldown=analytics.pageGroup1:(not%20set)) that there weren't any relevant page paths that were `not set` on www.va.gov -- one's currently under `(not set)` DO NOT have benefit hubs

**Comment by jonwehausen** [comment]
Latest comments on commit: https://github.com/department-of-veterans-affairs/va.gov-team/commit/1ee95d998d08a2ed6565c74374f285b046fffa3d

**Comment by laurensimpson14** [comment]
@jonwehausen I think the proper benefit hub for ^decision-reviews is **Records** since it can help with disability compensation, education, health care, burial benefits, etc. Does this also need to be added to the products index table?

**Comment by jonwehausen** [comment]
@laurensimpson14 

Here's a list of items I have to inch to closure for content groupings: 
- Confirm answer on benefit hub for `/decision-reviews` 
- Update Content Grouping GTM containers accordingly
   - _Update documentation according to the most recently published version_
- Shift these changes to 21701 - Content Grouping Updates

**Comment by laurensimpson14** [comment]
@jonwehausen 

- Working on getting confirmation for '/decision-reviews', but it sounds like there isn't a clear answer since it isn't currently considered a benefit hub or a product
- I've updated the containers and I worked to merge the most recently published version with the changes that we've discussed. Please let me know if all looks correct!
- The changes are now in the correct workspace!

**Comment by jonwehausen** [comment]
@laurensimpson14 Content grouping changes have been published. 

Final touches made before publishing: 
- Removed `/decision-reviews` from lookup table as doesn't have a clear cut benefit hub - these will just be `(not set)`
- Entry was made for soon-to-be-rolling-out product STEM Automated denials, url: /track-claims/your-stem-claims to be `Education` benefit hub CG...all other `/track-claims` will be `Disability`

Thanks again for your work here, container version 386 has been published live to production. Closing this issue.

**Comment by laurensimpson14** [comment]
@mnorthuis here is the ticket

**Comment by jonwehausen** [comment]
## Potential Next Steps
@laurensimpson14 Un-assigning myself -- perhaps we should consider closing this and accommodating Mikki's points in a later iteration.

**Comment by joanneesteban** [comment]
Great job on this audit, Lauren! We'll use Mikki's points for future iterations on this. Closing this ticket.
