### ISSUE TITLE
Audit & Document Domo Queries

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21700]
## Issue Description
Audit and document Domo queries so that Platform Analytics can understand which queries need to be optimized, sunset, or added.

---
## Tasks
- [ ] Audit Domo queries for:
  - [ ] What we're currently using
  - [ ] What should be sunset/archived
  - [ ] Which ones have errors
  - [ ] Which ones we need to update/optimize
  - [ ] _Stretch_ How we can optimize queries
- [ ] Document the audit in the [Analytics team folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics)

## Acceptance Criteria
- [ ] Platform Analytics team members understand which Domo queries need additional updates

**Comment by JasonTheBearded** [comment]
Audit doc started [here](https://docs.google.com/spreadsheets/d/1IrzYZhrFHmPUGhjKwxe8iuqt3RM3fC76mYkoznwegfw/edit#gid=0)

**Comment by JasonTheBearded** [comment]
@joanneesteban I think I have everything. I finished pulling all the fields for each BQ dataset so my work on the audit is done.

**Comment by joanneesteban** [comment]
Great! Thanks, @JasonTheBearded feel free to close when you're ready!

**Comment by JasonTheBearded** [comment]
Thanks @joanneesteban! Audit complete, closing ticket.
