### ISSUE TITLE
Audit Domo Dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21702]
## Issue Description
Audit and document Domo dashboard usage so that we can understand what has worked for VFS teams, what hasn't, and which dashboards we can sunset and use these findings for our prototyping.

---
## Tasks
- [ ] Audit Domo Dashboards
  - [ ] which dashboards haven't been used
  - [ ] for which dashboards haven't been used, why they haven't been used
  - [ ] which charts/designs have received the heaviest usage
- [ ] Document which dashboards should 
- [ ] _Stretches:_
  - [ ] Reach out to dashboard users for why they haven't used dashboards and which parts of the dashboards have been used the most & why
  - [ ] Sunset the dashboards that are no longer relevant
- [ ] Add documentation to the [Analytics Team Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics)

## Acceptance Criteria
- [ ] Platform Analytics understands basic current Domo usage (what is being used, what isn't).

**Comment by joanneesteban** [comment]
Started an [audit doc here](https://docs.google.com/spreadsheets/d/1kztrwpYrF9-UPtYM2zGBpvN7I1zK5YlN8oLmWsIHGWs/edit#gid=0).

**Comment by joanneesteban** [comment]
@JasonTheBearded do you need any additional support from my end for this audit?

**Comment by JasonTheBearded** [comment]
@joanneesteban I think I am good at the moment.

**Comment by JasonTheBearded** [comment]
Dashboard Audit complete! Closing ticket.
