### ISSUE TITLE
Audit Previous Dashboard Requests

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#21703]
## Issue Description
Audit previous VFS dashboard requests so that we understand what VFS teams have asked for in the past and use that knowledge to support our prototyping.

---
## Tasks
- [ ] Audit all previous Domo dashboard requests
- [ ] _Stretch:_ Audit previous Google Analytics reporting requests
- [ ] Document findings in the [Analytics Team folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics)

## Acceptance Criteria
- [ ] Platform Analytics understands the types of metrics VFS teams have asked for in the past so that we can align our dashboard prototyping to both the KPI framework (Platform quality) and VFS customer needs.

**Comment by joanneesteban** [comment]
Closing this ticket.
