### ISSUE TITLE
Pull in online  COVID-19 scheduling data  (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21734]
## Issue Description
As a Veteran searching for locations offering COVID-19 vaccinations, I want to know which locations allow online scheduling through VAOS. 

The following background is from [this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1616076392041300?thread_ts=1616004967.021200&cid=C0FQSS30V)
- The data from MAP mobile-facility-service [swagger](https://veteran.apps.va.gov/facilities/v1/) is available without auth from this endpoint: https://veteran.apps.va.gov/facilities/v1/direct-booking-eligibility-criteria/ or for a specific site: https://veteran.apps.va.gov/facilities/v1/direct-booking-eligibility-criteria/[siteId]
- We should complete an integration agreement with MAP even though the endpoint is open, mostly so we can know if v1 is being deprecated, etc.
- The vets-api endpoint is: https://api.va.gov/vaos/v0/direct_booking_eligibility_criteria?parent_sites=[][siteId].  Calls to this endpoint require authentication (unless there is a way for services in vets-api to make calls to other services without Veteran auth). 
- Here is the mobile-facility-service call in the Staging env that includes the Covid data (requires VA Network): https://veteran.apps-staging.va.gov/facilities/v1/direct-booking-eligibility-criteria

**This query must be behind a flipper because this service to Veterans will be gradual and we don't want to flood the gates until they have rolled out completely**

Adding this info from meeting with Stephen Barrs on 4/20

```
}, {
    "id" : "covid",
    "typeOfCare" : "COVID Vaccine",
    "patientHistoryRequired" : "No",
    "patientHistoryDuration" : 0,
    "stopCodes" : [ {
      "secondary" : "710"
```
- Online scheduling is available for COVID-19 vaccine services if `patientHistoryRequired` is **present** (with either yes or no value)

## Tasks
- [ ] Short term plan: connect directly to VAOS API to do this lookup
- [ ] Add flipper to toggle data 

## Acceptance Criteria
- [ ] Locations that allow online scheduling for COVID-19 vaccines through VAOS can be identified on the FL
- [ ] Functionality is toggled off until rollout is complete

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
