### ISSUE TITLE
TUD: Modify the Sign In link

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#21737]
## Issue Description
As a TUD user, I would like to see a button or link that navigates me to the `https://staging.va.gov` website in a separate tab and the 
---
## Tasks
- [x] Grey out & disable links that have a status of Unavailable
- [x] Remove cursor from the table row
- [x] Change the Availability column name to Status
- [x] Remove the Availability badge and change back to wording with a checkbox & cancel icons

## Acceptance Criteria
- [x] I can click on a link that has a status of available
- [x] I cannot click on a link that has a status of unavailable
- [x] I do not see a cursor for the row

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
