### ISSUE TITLE
[FE] Create CTA Link per new designs

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#21739]
## Background
We need to create a reusable CTA Link component that will be used in the Healthcare and Claims and Appeals section.

## Screenshots
![image.png](https://images.zenhubusercontent.com/5e9d15aab51cccb259a8a6c7/7b90b965-8cfd-43a0-8620-70028ffdc289)

## Tasks
- [ ] Create new CTA Link component
- [ ] Implement the new component in the Health Care section
- [ ] Remove redundant NotificationCTA component

**Comment by sanlouise** [comment]
Closing as there is no idea way to validate this.
