### ISSUE TITLE
TUD: Update the header

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#21736]
## Issue Description
As a TUD user, I would like to have more information available to me in the header across the pages so that I can complete my tasks quicker.

Should look like image below
![Test.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/87d87029-7ef1-4b61-a8ac-c7b8a2612d6c)
---
## Tasks
- [x] Remove 'Contact Us' dropdown
- [x] Create navigation bar for links including 'Getting Started, Find a user account, Documentation, and Issues'

## Acceptance Criteria
- [x] I see the header with easy navigation links
- [x] I can click on a link that will navigate me to the appropriate area.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Duplicate of #21636
Duplicate of #20717
