### ISSUE TITLE
TUD: Update documentation language

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#21735]
## Issue Description
As a TUD user, I would like to have consistent documentation throughout the website so that I can have a better user experience trying to accomplish tasks on the TUD web application

---
## Tasks
- [ ] Ensure documentation reads consistently (aka fix all the create a ticket, submit a ticket, etc)

## Acceptance Criteria
- [ ] The documentation reads consistently and is ready for review by the VSP/VSA content editors
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
