### ISSUE TITLE
[DESIGN] Emergency mash-up (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21741]
## User Story or Problem Statement
As a Veteran, I need to know where I am eligible to receive emergency care so I can have my medical needs addressed quickly without out of pocket costs.

## Background: emergency care
- Some VA Medical Centers have emergency care services
- Veteran can also seek care at local emergency rooms in the community (similar to urgent care)  
- Criteria
   - Location is "in network" (PC3 or Community care depending on geographic location)
   - Veteran is eligible
   - Visit qualifies as requiring emergency attention
   - VA services were not available
   - Without authorization, the Veteran is at risk for out-of-pocket costs and adverse credit impact. A Veteran can submit a request for "consideration" if the care provided out of network. Authorization is not guaranteed and the processing time can take significantly longer.

## Tasks
Design a workflow that includes the following:
- [x] Veterans can select ~Emergency care~ "In-network emergency care"  from the facility type dropdown. 
- [x] When facility type =~Emergency care~ "In-network emergency care" Veterans can search for a list of VA-only locations, Community care-only locations, or a combined list  (service type dropdown)
- [x] Veterans can click within VA facility search result cards to view the detail page
- [x] Veterans can click  "In-network emergency care benefit" within community care search results to view information 
- [ ] The "In-network emergency care benefit" links to the Community Care Emergency Medicine info page at https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency_Care.asp. 
- [x] "In-network emergency care benefit" design is consistent with "In-network urgent care benefit" link
- [x] Some method to provide caveats (at the search level, _not at the result level_) _should this appear for all emergency care searches?_
       - ~this list isn't comprehensive~
       - ~billing will be expedited at VA facilities and locations with a VA partnership~ 
       - if this is a true emergency, please proceed to the nearest emergency room or dial 911
       **_^ will need content input_** 
- [x] Phone numbers will be actionable
- [ ] Community emergency care search result cards should contain "Call to confirm services and hours." but do not need to include the "If you don't have a referral... language. 

~Based on staffing, we may not conduct usability research for this initiative (but will return post-launch to validate the bet)~

**Comment by mmiddaugh** [comment]
I've updated the AC following a design review earlier today. 
Decisions:

- We're going to try "In-network emergency care" as the facility type and test with Veterans to validate that the label conveys the list is not comprehensive. We will also check that the label doesn't cause confusion for other facility type searches. 
- Community care search result cards will keep the "Call to confirm services and hours." caveat due to known data quality issues.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @nicko-amida. I was checking this ticket for the link to the design you shared in office hours earlier this week, but I don't see it here. Would you mind sharing the link? Thanks!

**Comment by nicko-amida** [comment]
Hey @DanielleThierryUSDSVA, here's a link to the current in-progress version: [UXPin](https://preview.uxpin.com/8767aa9028468a26be090fd044d9ff26e40a8f95#/pages/138402705/simulate/no-panels?mode=i)

**Comment by mmiddaugh** [comment]
@DanielleThierryUSDSVA based on a review with Dave this morning, we think we want to condense the information into one line (similar to what Nick's design has in the yellow box) which needs to inform the Veteran to go to their closest ER or call 911 if they're having an emergency

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @nicko-amida @mmiddaugh. 

What do you think about using this line from the community care emergency page here (just changing "believe" to "think")?

 **Note:** If you think your life or health is in danger, call 911 or go to the nearest emergency department right away. 

And then I'm not sure if we need/want this, but we could add:

You don't need to check with us before calling for an ambulance or going to an emergency department.

**Comment by mmiddaugh** [comment]
Awesome @DanielleThierryUSDSVA! Thank you

**Comment by sshein** [comment]
Just passing through, glanced at Nick's designs, I think if we have [multi-line alert boxes with an icon](https://design.va.gov/components/alertboxes), we'd want the icon to stay top aligned (right now looks like it's vertically center aligned in the UXPin) @nicko-amida 
<img width="309" alt="Screen Shot 2021-04-23 at 9 10 37 AM" src="https://user-images.githubusercontent.com/3856611/115899749-fcf23e00-a413-11eb-97b7-e429b368de88.png">

**Comment by mmiddaugh** [comment]
[Link to design in UX pin](https://preview.uxpin.com/8767aa9028468a26be090fd044d9ff26e40a8f95#/pages/138402705/simulate/no-panels?mode=i)
