### ISSUE TITLE
OpenResty 300MB limit increase for file uploads in DEV

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#21742]
## Description
Per our meeting on 3/10. Team Matsumoto would like to increase OpenResty file size limitation from 100MB to 300MB. We are doing a POC test against a new endpoint and would like the limit raised to closer reflect what our consumers need.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 
Discuss Active Storage Proof of Concept 3/10/21
Discussion in Slack found in [this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1614725226004000)

## Technical notes / considerations
If this can be done for a specific path, that may be best. 

This change is only to be applied in DEV at this time. The change has not been approved for other environments, per @drorva 

---
## Tasks
- [x] Increase OpenResty limitation to 300MB in DEV so that multipart form attachments are not limited to 100MB

## Definition of Done
- [ ] The Benefits Intake V2 Endpoint can upload documents up to 300MB in DEV (only!)

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by mviterna** [comment]
@dginther Is there any other information you all need for this ticket?

**Comment by NCHLiberty** [comment]
hi there @dginther and @f1337, wanted to check in and see if you could give us a sense for a good ETA on this change so we can continue on with experimentation [as per this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1614725226004000) and the great follow up conversation we had. we know you have a lot going on, just want to plan our sprints accordingly. Thanks! :)

**Comment by mviterna** [comment]
@drorva @dginther It sounds like we have approval for 300MB limit in dev, per our MS Teams meeting today. Please let us know when this is implemented.

**Comment by drorva** [comment]
@jhouse-solvd this is approved to make the change.

**Comment by jhouse-solvd** [comment]
it looks like this setting might actually be 151M at current, according to [this config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/base-shared.conf.j2#L56), which is global. ops would need to parameterize this so that we can up the setting in dev only. 

will leave this up to the ops engineers to decide and implement, but tagging here for reference

**Comment by jhouse-solvd** [comment]
Gregory Bowman shared this endpoint that they will use for testing: 

https://dev-api.va.gov/services/vba_documents/v2/uploads/submit

This should help us follow the path that the request will take so that we update configurations accordingly.

**Comment by NCHLiberty** [comment]
hi there @jhouse-solvd and @omgitsbillryan. Just for planning purposes, I was wondering if you could give us a likely timeline on parameterizing this setting and updating it to 300MB? 

Once we hit that point, we can participate in the testing through the process to help identify any other bottlenecks that would need adjustments to support the POC (which we should make note of since similar adjustments would be needed in other environments *IF the decision is made to proceed with the solution after the POC evaluation is wrapped up). 

Thanks for all your assistance in this experimentation!

**Comment by omgitsbillryan** [comment]
All requests to `/services/vba_documents/*` have been bumped to `client_max_body_size 300m`. This change has been [deployed to dev](http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-dev/421/).

**Comment by omgitsbillryan** [comment]
When your satisfied with testing in `dev`, applying these changes to the other envs is a simple config update + redeploy of that envs revproxy.

**Comment by NCHLiberty** [comment]
Thank you. We will be experimenting this sprint.

**Comment by drorva** [comment]
@omgitsbillryan this is supposed to be a 30 days experiment, so please make yourself a note to revert this after checking with @NCHLiberty that they're done.

**Comment by jhouse-solvd** [comment]
@omgitsbillryan - and adding to what @drorva mentioned above, I don't believe that we want this change to go past DEV at this time. thanks for the work here!

**Comment by NCHLiberty** [comment]
True. A decision to proceed into other environments would involve review/discussion of risks/benefits among relevant business and technical owners.  It's good info to retain though so thanks! :)

**Comment by jhouse-solvd** [comment]
@NCHLiberty - Did this prove useful in your team's testing? Were we able to achieve the definition of done here, ie: 

"The Benefits Intake V2 Endpoint can upload documents up to 300MB in DEV"? 

If so, would it be okay to close this ticket? We can always open another should we decide to visit this further in other environments. Let us know your thoughts. We're here to make sure we've done what's needed. :)

**Comment by NCHLiberty** [comment]
Hi yes it was successful and yes you can close the ticket but can you please keep the limit in place for now in Dev? We have a separate ticket open for load testing. Thanks!

**Comment by jhouse-solvd** [comment]
Yes, the limit will stay in Dev for now. If for any reason your team has an issue, just let us know. :)

**Comment by omgitsbillryan** [comment]
I see this ticket is now closed but @drorva asked that I [revert this after 30 days](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21742#issuecomment-824984587) pending a followup w/ @NCHLiberty  - thoughts?

**Comment by NCHLiberty** [comment]
Hi. We had to spin up an AWS instance for additional load testing. This is now underway in the current sprint so if possible please keep this in place till the end of the current sprint through 6/2. LMK if any concerns. thanks for your help!
