### ISSUE TITLE
Create and publish R&S article for burials emblems of belief

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21753]
## Issue Description
Now that we are moving Tier 1 support content off of our benefit detail pages into R&S we need to create an article for emblems of belief under Burials and Memorials. We will use the media list template in R&S.

Here is the legacy page with the images we would work off of to download the images: https://www.cem.va.gov/cem/hmm/emblems.asp

## Tasks
- [ ] Create R&S article with media template 
- [ ] Send preview link to SMEs for review
- [ ] Update content with SME feedback
- [ ] Copyedit page
- [ ] Use prepublish checklist
- [ ] Publish page
- [ ] Notify stakeholders page will go live

## Acceptance Criteria
- [ ] New R&S article live on site

**Comment by RLHecht** [comment]
Update: The page mentioned above needs to be assessed with the new R&S criteria to determine if this should still be a new article. If it should, Sitewide Content needs to build the new article and take it through the content creation, edit and publishing process and get stakeholder approval. The template for these emblems is now available in Drupal.
