### ISSUE TITLE
[Epic] Find a VA Form: Content Catch Up & Clean Up

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#21758]
## User Story

As a Veteran, I want the forms-related content in the CMS to be as complete and current as possible so that I can trust the information I see is correct.

## Expected Behavior

When a Veteran searches for a form, the search returns relevant results based on current and complete information in the CMS.

## Acceptance Criteria
- [x] Identify the top searches between VA.gov and Find a VA Form combined
- [x] Determine which forms still need "When to Use" and "Related Forms" data based on results from the Forms API and Search.gov best bets
- [x] Coordinate with Content team on who will manage locating, composing, & vetting When to Use and Related Forms content
- [ ] Most popular forms are populated with "When To Use" and "Related Forms" (if applicable) in the CMS

**Comment by MarciMcGuireGCIO** [comment]
Got a new dataset from Best Bets; will re-assess current state today.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva - here's the latest data mashup of top Find a Form searches, top Search.gov searches, CMS status, "When to Use" descriptions, and Best Bets text.  The total searches figure combines Jul 1 2020- Mar 1 2020 on Find a VA Form and Search.gov. 

First tab highlights info currently lacking.   Keep in mind that some terms are partial or non-VA 
form names, which would account for them not being in the CMS.
[Top_Search_Description_Needs.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6224043/Top_Search_Description_Needs.xlsx)

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva safe to assume we will leave this issue open until all the content updates are in CMS?  Thx!

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO Let's close this one and give ourselves credit for getting this all organized -- and create new ones for each content update batch.    Agree?

**Comment by MarciMcGuireGCIO** [comment]
Agree. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Converted to an Epic; clearing Milestone.

**Comment by MarciMcGuireGCIO** [comment]
Blocked pending content review from VA forms managers.

**Comment by jilladams** [comment]
Contract changed hands, this initiative was not continued, and we are closing old / aging tickets. CLosing. Can reopen as needed in the future.
