### ISSUE TITLE
Jenkins worker node AMI should be prevented from being culled each 30 days

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#21764]
## Description
_Currently, The Jenkins worker node AMI is culled every 30 days, which results in Jenkins not being able to spin up new workers, which results in a queue backlog in Jenkins which prevents jobs from being run._

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_There is a script which cleans up AMIs which are older than 30 days, which is a Lambda function. This script should exclude the Jenkins worker AMI_
https://console.amazonaws-us-gov.com/lambda/home?region=us-gov-west-1#/functions/cleanupAmisAndEbsSnapshots?tab=code

---
## Tasks
- [x] _Document Lambda function's schedule and trigger in Confluence_
- [x] _Modify cleanup script to exclude the Jenkins AMI_

## Definition of Done
- [x] _Jenkins AMI is not deleted after it is 30 days old_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Passing to @oragame to look at during this Sprint.

**Comment by oragame** [comment]
I think this can be fixed pretty easily with an update to [line 29 of cleanupAmisAndEbsSnapshots.py](https://github.com/department-of-veterans-affairs/devops/blob/063958f53e7bafd76b84e83df470f025086c8719/utilities/lambda/cleanup/cleanup_amis_and_ebs_snapshots/cleanupAmisAndEbsSnapshots.py#L29):
`if i['CreationDate'] < str(expiry_date) & i['Name'].find('jenkins-worker') != -1:`

I may need to check on my python syntax, but this should work. Wanted to ask if you think the "Name" or the actual image ID is best for hard coding here? I wasn't sure if the image ID might change for some reason (like if a new AMI was created with intent).

**Comment by jhouse-solvd** [comment]
Ops created a new image for this on May 12, 2021. That means we have 30 days until this happens again.

**Comment by jhouse-solvd** [comment]
@jbritt1 - Can you take a look at this? You don't have to take it on, but we were discussing this during Sprint planning and thought that you might have some information about this or be interested in taking it on.

**Comment by jbritt1** [comment]
Reopened, need to put details in Confluence and ensure the worker AMI doesn't get wiped at the 30 day mark.

**Comment by jbritt1** [comment]
Verified this morning that we are now a few days past the 30 day mark and the Jenkins worker AMI does in fact still exist. ![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/e716af57-554e-4a17-8dea-bd8a762efc44)

**Comment by jbritt1** [comment]
Confluence doc created. Awaiting just a touch of guidance on where it best fits in our Confluence documentation hierarchy and this one will be good to move to review/QA.

**Comment by jbritt1** [comment]
Confluence doc created in new "space". Moving to review/QA.

**Comment by jhouse-solvd** [comment]
Discussed with the team. Looks good. 

Closing.
