### ISSUE TITLE
Combine FL mobile/desktop rendering into one responsive view

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21775]
## Issue Description
Combine the separate functions for rendering mobile and desktop views into one responsive view.
  - Show tabs at mobile width, toggle map when tabs are clicked
  - Hide tabs at desktop width, and always show map
 
---
## Tasks
- [ ] Refactor the separate desktop and mobile rendering code into one responsive view. 

## Acceptance Criteria
- [ ] No changes to behavior.
- [ ] Instead of sepaprate renderMobileView and renderDesktopView functions, we just have one function that renders the component.

**Comment by gescobardev** [comment]
PR ready for review
https://github.com/department-of-veterans-affairs/vets-website/pull/17303
