### ISSUE TITLE
[DISCOVERY] Review Sentry issues

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21771]
## Issue Description
We have issues covering a variety of Sentry errors that date back to the Fall of 2020. We need to investigate them to determine if the issues are still occurring or if they have been resolved by changes released in December.  

---
## Tasks
Review the errors referenced in the following issues to 1- determine if the issue is still occurring, 2- document current frequency (for use in prioritization), and 3- add info to the issue which will be needed to groom/troubleshoot. 

- [ ] Community provider query does not include specialty code #21488 
- [ ] [Facility Locator] Sentry issue: ServiceTypeAhead Cannot read property 'length' of null` #14959 
- [ ] [Facility Locator] Sentry issue: error undefined is not an object #14961 
- [ ] [Facility Locator] Sentry issue: null is not an object #14960
- [ ] Sentry error: unable to get property map undefined/null reference #21588

## Acceptance Criteria
- [ ] Issues that document errors that are no longer occurring have been closed
- [ ] Issues contain details about the frequency of occurrence which can be used for prioritization
- [ ] Issues contain sufficient detail to be groomed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
closing as no longer needed
