### ISSUE TITLE
Create an R&S multiple FAQ around headstones, markers and memorials

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21777]
## Issue Description
We need to combine our single Q&As around the headstones, markers, and memorials content into a multiple FAQ. This means adding an intro and using new CTA buttons and related links. 

These Q&As will be moved into the multiple FAQ template:

Can I choose the type of headstone or marker?
What information goes on the headstone or marker and who provides it?
When will the headstone or marker I requested arrive, and who will set it for me?
Does VA provide a memorial headstone or marker if remains aren’t available?
Can 2 Veterans who are married get separate headstones?

## Tasks
- [x] Create multiple FAQ page (Randi)
- [x] Add intro, CTA buttons and new related links (Beth)
- [x] Review and use prepublish checklist (Randi)
- [x] Publish page
- [x] Update R&S landing page with added articles

## Acceptance Criteria
- [x] Multiple FAQ article live on site and R&S landing page updated

**Comment by RLHecht** [comment]
@bethpottsVADEPO The Drupal node to use for this is preview-prod.vfs.va.gov/preview?nodeId=17053

**Comment by RLHecht** [comment]
Pages are on live site. Closing ticket.
