### ISSUE TITLE
Mobile VHA locations

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21781]
## Issue Description
There are a number of considerations related to displaying "mobile" locations on both the Facility Locator and VAMC sites. 

- Identification in the VAST data 
- Definition of "mobile"
- Return of these locations in FL search results
- Inclusion of mobile locations on left nav and "Locations" on VAMC
- Role in COVID-19 vaccination services

**[This query](https://api.va.gov/v1/facilities/va?bbox[]=-171.791110603&bbox[]=18.91619&bbox[]=-66.96466&bbox[]=71.3577635769&per_page=200&mobile=true) can be used to identify the mobile locations**

---
## Dependency
- [ ] CMS will need to get indicator from VAST [#4743](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4743)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
One of the biggest challenges here and likely dependecy, further design needs, research will be how to approach the locations page and length thereof with health care systems like ATL esp when you build on top of that the mobile clinic locations/experience.

**Comment by mmiddaugh** [comment]
See also 
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-vha-mobile-redesign/initiative-brief.md)
- [VSA UX Transition document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/product-transition-doc/vsa-ux-transition-doc.md) | March 2022 
- [Mobile health clinics feature doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/product-transition-doc/feature-docs/mobile-health-clinics.md) | March 2022
