### ISSUE TITLE
Authenticated Experience: Sprint 44 (3/24 - 4/6)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#21796]
## Priorities

1. Launch Direct Deposit for edu (to 10%)
2. Complete My VA design and continue build
3. Continue design of preferred medical facility and notification preferences
4. Continue BE work of notification preferences
5. If time permits, Profile work

## Profile

**Design**
- [ ] Add FAQ around what departments get updated when a veteran updates their contact info #20221
- [x] Change how international phone numbers are displayed #13246

**FE**
- [x] Focus MUST not be hidden by the sticky profile menu #19779 

From previous sprint:
- [x] "Are you sure?" deletion alert stays pinned to bottom of window #18547 (waiting to go to staging for validation)

**BE**
- [ ] VA Profile: Rename references to vet360 in devops #18259

## My VA redesign

**Design**
- [x] Error message documentation #21373
- [x] Update copy documentation #21825
- [x] My VA content updates #21872 
- [x] Claims spinner handling #21372
- [x] Review and update My VA test cases #22185
- [x] Plan for/coordinate assistive tech testing #22197

**FE**

- [ ] Apply for VA Benefits visual updates #21837
- [ ] Claims and Appeals visual updates #21838
- [x] Update Appointments logic to match new designs #21844
- [x] Name tag error state #21839
- [x] Add error state messaging #21849
- [ ] Add error state appointments #21846
- [x] Implement error state for when we can't connect to the health care endpoint #21870
- [x] Update copy documentation with final copy #21652

## Direct deposit for EDU

**PM**
- [x] Hold go/no-go #21826 

**FE**
- [x] Wrap updated content in a react widget so it will show conditionally throughout phased launch #21725
  - **Needs to be done as early in the sprint as possible before go/no-go**
- [x] An equivalent alternative MUST be provided for the image of the check #19611
  - **Needs to be done as early in the sprint as possible before go/no-go**
- [x] Launch to 10% #21861

## Preferred medical facility

**PM**
- [x] Internal planning around dependencies #22029
- [x] Schedule and hold [design intent collab with VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-design-intent.md) #21858 
  - [x] Design Intent request submitted to VSP #22308

**Design**
- [x] Finish design #21841
- [ ] Review and respond to feedback from Design Intent #22308
   - [x] Accessibility Feedback for Design Intent: Preferred Medical Facilities #22466
   - [ ] Content Feedback - Design intent - Preferred facilities #22519
   - [ ] IA feedback - Design intent - Preferred facilities #22520
   - [x] Design Feedback - Design intent [VSA Authenticated Experience, Preferred Medical Facilities in the VA.gov profile] #22531

## Notification Preferences

**PM**
- [x] Schedule and hold [design intent collab with VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-design-intent.md) #21860
   - [ ] Design Intent request submitted to VSP #22309
- [x] Internal planning around dependencies #22030

**Design**
- [x] Finish design #21855

**BE**
- [x] VA Profile notification preferences: Implementation (part 2) #19773
- [ ] Notification preferences: Implementation (part 3) #19774

**Comment by lihanli** [comment]
i think this issue should also be part of the sprint: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19773

**Comment by ajakabcin** [comment]
Sprint 44 complete - closing
