### ISSUE TITLE
BDD - Change validation on service branch end date

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#21792]
## User Story or Problem Statement
As a service member in the reserves or national guard, I need to be able to input my service end date without the system giving me an error.

Right now, reservists and national guard service members are shown an error when they give their obligation end date (or service end date) in the future:

![Screen Shot 2021-03-19 at 4.09.38 PM.png](https://images.zenhubusercontent.com/5d65638e0845ad5f24bada4a/4948d995-554f-45c2-a18d-33cfa2299fae)

We need to keep this type of validation for all the active duty choices, but remove it for the reservists or national guard folks.

## Tasks
- [ ] Keep the 180-day validation on active military service choices
- [ ] Remove the 180-day validation on reserve or national guard choices

## Acceptance Criteria
- [ ] the 180-day validation works on active military service choices
- [ ] the 180-day validation is removed on reserve or national guard choices

**Comment by Mottie** [comment]
Should we also include "NOAA" and "Public Health Service"?

**Comment by kevinstachura** [comment]
Will ask Barry on this - stay tuned.

**Comment by Mottie** [comment]
NOAA & Public Health Service are equivalent to active duty service periods, so they won't get included in this exception.
