### ISSUE TITLE
[DESIGN] Placeholder for missing optional images in the VAMC product

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21800]
## Issue Description
There are a few places in the VAMC product where images ~are required~ **_can be used._** 
From a design perspective, how should we handle when an image is ~required~ **_expected_** but unavailable? 

<details>
<summary> Example in Locations </summary>

![image](https://user-images.githubusercontent.com/55411834/111839811-05a99e80-88c1-11eb-8959-7a0a9bcc2f33.png)

</details>

<details>
<summary> Stories example </summary>

![image](https://user-images.githubusercontent.com/55411834/111840214-aa2be080-88c1-11eb-86a5-dc1f0ff6643f.png)

</details>

<details>
<summary> System page image </summary>

![image](https://user-images.githubusercontent.com/55411834/112034782-78ef2280-8b04-11eb-9814-9f68132e05fd.png)

</details>

---
## Tasks
- [ ] Determine how VA.gov generally handles placeholder images (is there a precedent?) Should there be one for all scenarios or a plan for Stories vs Facilities, for example?)
- [ ] Determine what placeholder image(s) should be used for the following scenarios:
       - Placeholder image for stories
       - Placeholder for Facilities - brick and mortar
       - Placeholder for Facilities - Mobile
       - System page image (I'm guessing it's unlikely this image would not be available - but just in case)
- [ ] What is the recommendation for markup to assist Veterans using assistive tech?

## Acceptance Criteria
- [ ] Recommendation to standardize placeholder images
