### ISSUE TITLE
Padding to finish "Clear input field" 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21806]
## Issue Description
Based on feedback from Josh, we should increase the padding around the clear input field indicator (see [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21053#issuecomment-803103311)). After this, we can push to Prod. 

---
## Tasks
- [ ] Touch target of 44x44
- [ ] Vertically centered and right aligned within the field at a window size of 320px, 888px, and 960px
- [ ] Remove environment check to make the feature available in Prod. 

## Acceptance Criteria
- [ ] Padding meets design and accessibility requirements
- [ ] Feature is available in Prod 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
Can we allow the padding to fill the whole vertical space within the input, like this? 
![padding](https://user-images.githubusercontent.com/4960080/111988710-35d28680-8ae7-11eb-8947-dce8efd690eb.png)

Also, to me the icon looks slightly off center (vertically) compared to the text - my eye wants the white x within the black icon to rest on the same line as the text instead of the black circle. 
![clear input](https://user-images.githubusercontent.com/4960080/111987784-04a58680-8ae6-11eb-8b59-74cdc310a2ff.png)

Not sure if that's possible? Maybe the icon would need to bump up a pixel to have even pixel spacing?

**Comment by joshkimux** [comment]
<img width="1121" alt="Screen Shot 2021-03-22 at 9 17 32 AM" src="https://user-images.githubusercontent.com/14154792/111995562-71714e80-8aef-11eb-9e84-8ff3d20bb07c.png">

@lildziner , 44x44 would meet future compliance standards for when we switch to WCAG 2.1; it will especially help folks using this on mobile 🥳 

I just checked the code and this is absolutely positioned, so it might be a bit tricky. @mmiddaugh Could we update the AC to the following:

- [ ] Touch target of 44x44
- [ ] Vertically centered

**Comment by mmiddaugh** [comment]
AC updated! Thanks

**Comment by joshkimux** [comment]
@brangi The 44x44 touch target should apply to all responsive sizes. For example, a user on a larger tablet may rely on touch controls. Next time I'll be sure to make it more explicit in the acceptance criteria 🙇
