### ISSUE TITLE
Document confirmation page cards

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21809]
## Description
To support consistency in the redesign of the appointments list, we need to document all the ways appointment submission data is presented to the user on the confirmation page.

Ideally this documentation would include:

- "Types" of appointments (all the ways an appointment or request can show to a user)
- Mock data presented with each type (understand data being sent vs visualized)
- Screenshots of an example state for each

## Tasks

- [ ] Document VA confirmation types
- [ ] Document VVC confirmation types
- [ ] Document CC confirmation types
- [ ] Document EC confirmation types

## Existing Documentation
See the [appointment cards documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md) for example of related task

**Comment by jenniemc** [comment]
documentation for confirmation card can be found on https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/confirmation-cards.md

cc: @jbalboni @laurenernest
