### ISSUE TITLE
SEM Rush Analysis

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21807]
## Description

As a product team we would like to better understand SEM Rush and the reports that they are able to generate. 

## Tasks
- [x] Read [SEM Rush Article - How to Perform a Technical SE Audit in 15 Steps](https://www.semrush.com/blog/technical-seo-audit)
- [x] Review the resource Library offered on SEMRush Website
- [ ] Get Log in information from John (Jen Lee)

## Definition of Done

- [x] Team has a baseline understanding and can read SEM rush reports to determine next steps and importance of issues identified in the reports

**Comment by denisecoveyduc** [comment]
John has access to SEMRush - Sam and I may need it in the future but that is yet to be determined
