### ISSUE TITLE
COVID-19 vaccine page VA vaccine act passed: Translate new updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21817]
##User story

As a Veteran, spouse, or caregiver seeking the latest info on the new VA vaccine act in Spanish or Tagalog, I need updated information.

## Issue Description
Translate updates made 3.20.21 on English page.

---
## Tasks
- [x] Prep translation docs (Danielle)
- [x] Send docs to Chad (Danielle)
- [x] Make updates on Spanish page (Selina)
- [x] Review and publish Spanish page (Randi)
- [x] Make updates on Tagalog page (Selina)
- [x] Review and publish Tagalog page (Randi)
- [x] Send live links to Mateo's team for review (Randi)
- [x] Incorporate any changes from Mateo's team (Randi, Selina)

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lalexanderson-dsva I sent these docs to Chad with a request for timely translation. 

[New law updated eligibility content_for translation to Spanish_03.20.21](https://app.zenhub.com/files/133843125/456c0d0d-371f-449a-8c78-091d3c3e4eed/download)

[New law updated eligibility content_for translation to Tagalog_03.20.21](https://app.zenhub.com/files/133843125/ad40dedd-62bc-4c3f-bbef-328500e48185/download)

**Comment by RLHecht** [comment]
@lunascoop Here is the translated copy back for these new updates.
[https://app.zenhub.com/files/133843125/7e038754-b78e-4a9c-9aff-ef0aac0a1ea2/download](https://app.zenhub.com/files/133843125/7e038754-b78e-4a9c-9aff-ef0aac0a1ea2/download)

[https://app.zenhub.com/files/133843125/46ce25c5-29a9-43c4-a488-86a7ce2d01ab/download](https://app.zenhub.com/files/133843125/46ce25c5-29a9-43c4-a488-86a7ce2d01ab/download)

**Comment by RLHecht** [comment]
@youngfreezyVA We have updated translated content that needs to go into the widget on the Tagalog and Spanish versions of the vaccine page. The only content that needs to be changed is the highlighted parts in the doc. So the header and the first paragraph stays the same. Will this be able to go live by today's daily deploy?

[https://app.zenhub.com/files/133843125/56f5ba3c-1a06-4cc8-a7cd-e33cd70cb97f/download](https://app.zenhub.com/files/133843125/56f5ba3c-1a06-4cc8-a7cd-e33cd70cb97f/download)

[https://app.zenhub.com/files/133843125/18fc5005-16a3-4391-a5b4-e72ca1b49c33/download](https://app.zenhub.com/files/133843125/18fc5005-16a3-4391-a5b4-e72ca1b49c33/download)

**Comment by lunascoop** [comment]
@RLHecht I made the updates per the doc and they're ready for review. 

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359 (missing section 1 (intro) and section 3 (first sentence of first section).  For the latter, I just removed "a los veteranos" and it should be fine.

**Comment by RLHecht** [comment]
thanks @lunascoop I published these pages and did a content release. Once these are live I'll send to the VHA translation team for their final review. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@lunascoop Here are a few changes to the Tagalog page from the VHA translation team after they did their final review.[https://app.zenhub.com/files/133843125/c8a0787b-74cf-4dea-9aef-62316c64a1cf/download](https://app.zenhub.com/files/133843125/c8a0787b-74cf-4dea-9aef-62316c64a1cf/download)

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. Here's another copy of the Tagalog changes from the VHA translation team w/my comments.
[c8a0787b-74cf-4dea-9aef-62316c64a1cf-Selina's comments.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6258455/c8a0787b-74cf-4dea-9aef-62316c64a1cf-Selina.s.comments.docx)

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by RLHecht** [comment]
Reviewed and published the few changes he had. Will close after the next deploy.

**Comment by RLHecht** [comment]
work completed on this ticket.
