### ISSUE TITLE
Update chatbot based on passage of VA vaccine act

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21813]
## Issue description

Update chatbot with approved content around new law.

## Tasks

- [x] Update content and create PR (Danielle)
- [x] Alert chatbot dev team (Danielle)
- [x] Review content and give go-ahead to merge PR (Randi, Selina)
- [ ] Review in staging (Randi, Selina)
- [x] Validate in production (Randi, Selina)

## Related docs and info

PR here: https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/369

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I approved the PR.

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA I've reviewed as well and the changes look good.

**Comment by RLHecht** [comment]
validated on live site. Closing ticket.
