### ISSUE TITLE
[VAMC] Prepare Salisbury-health-care for Dual-state [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21823]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Salisbury Tugboat CMS Instance](## STORY

## TASKS
Validate that each page:
- [ ] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [ ]  Update any last minute changes provided by PAO and approved for input
- [ ]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [ ]  Update pages specified in Content review with updated material (tech-debt)
- [ ]  Validate there are no Additional detail pages or list page duplicates that have not been removed

## Acceptance Criteria
- [ ] All pages in check list have been tested
- [ ] All additional pages that are NOT duplicates have been added to list and have been checked
- [ ] Updates suggested from Staging have been input into system
