### ISSUE TITLE
Search & Discovery: Sprint 45 Priorities

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21836]
## Search & Discovery Team Priorities: Sprint 45 (April 7 - 20, 2021)
_Aligned with [Quarterly Planning](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/search-discovery/quarterly-planning.md)_
1. Launch POC2
2. Finalize Designs for Results Page and Global Search Consistency
3. Implement Click Tracking for Best Bets
4. Dev Exploration for Results Page
5. Exploration of Structured Metadata findings
6. GA Reports for Global Search in lieu of DOMO 

#### *Typeahead POC*
- [x] Add terms that needed best bets #22540
_Completed_
- [ ] Run POC2 - 35% of all users #22497
_POC2 expected to run April 12-25: As a result, this will roll into S46 as expected._ 

#### *Search UI Consistency*
- [ ] Search UI Consistency: Global Search #21977 (Cont'd from S44)
_Completed_

#### *Results Page Redesign*

- [ ] Product outline for "Surfacing our search tools in a better way" based on user research #21382 
_Finalizing ahead of design review_ 
- [ ] DEPO Design Review (Meet w Ryan + Meg +Shawna #22500 
_Will be scheduled once product outline is finalized_
- [ ] Create wireframes #22932 
_Moving to S46, blocked by product outline and design review_
- [ ] Exploration/Audit of Metadata Descriptions #20402
- _Complete_

#### *Sitewide Search Reorganization and Improvements*
- [x] Dev Exploration to optimize/rebuild search #22499
_Completed_

#### *XML Sitemap/Indexing*SEO Performance Review*
 - [ ] Structured Metadata Exploration #22442
 - #22499 took priority, 
- [ ] Google Search Console Exploration (STRETCH) #21795
_Did not attempt in S45_

#### *Click Tracking*
- [ ] Add Click Tracking to Best Bet - Implementation #22131
_BE implementation is complete and awaiting POC2 completion before merge_

#### *Data Analytics*
- [ ] Acquire GA Reports to focus on Global Search #22501
_Moving to S46_

## Sprint Demo
- {Typeahead Suggestions - Denise Coveyduc} 

## Grooming Discussion Topics
{Team to add as sprint progresses; highlighting issues that need to be created or discussed}_
 - List item
