### ISSUE TITLE
Work with VSP DevOps & Triage to map products to backend services

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2184]
## User Story or Problem Statement
As a Product Manager or Product Owner, I need to see if my product or form was down in the last 30 days so that I can understand if trends were due to downtime.

## Goal
Be able to see percentage of downtime for backend systems of different forms (and therefore products) for the last 30 days. Be able to programmatically call the data and and store it so that users can see possible trends.

## Objectives or Key Results this is meant to further
- Launch Grey Sky Product Health Tool

## Acceptance Criteria
- [x] Discovery: Meeting with Triage and Ops PMs to clarify requirements
- [x] Discovery: Engineers on teams meet
- [x] Share VSP Product Success MVP with Keifer and Anna [Nicola]
- [ ] Analytics team to define what backend metrics are needed
- [ ] Accessible end point mapping

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[Triage Issue](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2469)

Triage is working on a more granular dynamic endpoint mapping that Insights may be able to call.

**Comment by joanneesteban** [comment]
### Deliverables from Meeting 12/11:

**Phase 1 Deliverable**
1. Proof of concept on monthly latency (does not include mapped products)
2. How to export that data

Work related to: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2469

**Comment by nedierecel** [comment]
@deweydell I updated the AC to include sharing a screenshot and/or directions for the VSP Product Success tool with Anna and Keifer. We'll work in this sprint to better define the metrics we need.

**Comment by deweydell** [comment]
## Backend Metrics in the Product Success Tool prototype
### Downtime Percent
<img width="1106" alt="Screen Shot 2019-12-16 at 12 29 34 PM" src="https://user-images.githubusercontent.com/11186572/70928831-d4785980-1fff-11ea-91cf-9bceebba31e3.png">

### Backend Systems
#### Prototype view
<img width="832" alt="Screen Shot 2019-12-16 at 12 29 40 PM" src="https://user-images.githubusercontent.com/11186572/70928867-e1954880-1fff-11ea-8c57-0ea31be1be0f.png">

#### Original design
<img width="619" alt="Screen Shot 2019-12-16 at 12 31 10 PM" src="https://user-images.githubusercontent.com/11186572/70928919-f83b9f80-1fff-11ea-8125-a2193818b5a5.png">

Login to the prototype: https://department-of-veterans-affairs.github.io/product-tool/
With GA access you should be able to see data and charts.

**Comment by nedierecel** [comment]
@annaswims @kfrz @wyattwalter As a follow-up to our discussion, please see Nicola's screenshots of the MVP. There are two key sections above:

1. Percent downtime by tool/form (e.g. Percent downtime by Form 22-1990)
2. Percent downtime by tool/form by system where applicable 

Our clarifying questions from our conversations are: 
1. Using Prometheus data, is it possible to align these metrics by tool/form and what level of effort might that entail?
2. Can we map the backend systems by tool/form within Prometheus? 
3. For these metrics, the group had mentioned whether or not we only include backend systems that are under VSP's control or if there are other backend dependencies we want to include. Did I capture this accurately? 

CC: @amycesal

**Comment by joanneesteban** [comment]
Performance dashboard work with BE & Ops has begun (Datadog<>BigQuery). Closing this ticket.
