### ISSUE TITLE
[Design] Preferred Medical Facilities - Finish design 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#21841]
## Background

We are continuing work on the design for the preferred facilities project.

## Tasks
- [x] Update design w/ content recommendations
- [x] Review designs with VAOS team
- [x] Incorporate feedback from VAOS team as needed
- [ ] Incorporate feedback from VSP
- [x] Consider whether or not we should link to VAOS from our profile page
- [x] move "Your medical facilities" above "Account security"

## Acceptance criteria
- [ ] Ready to prototype/ prepare for research

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. Great to talk with you today! Here's some thoughts on content as we chatted about. Feel free, of course, to send questions/additional thoughts/etc. I think using "How can I can a new facility?" with the word "new" could be helpful to nod toward registration. Let me know if you need help with the content within that component as well. Thanks!

[screen 1]
**Your VA health facilities**

You’re registered at all of the facilities listed on this page. We may use this information when you schedule an appointment online. To help us serve you better, update this list to include only the facilities you currently go to for care. You can update the list again at any time.

**Note:** Not all VA facilities offer online scheduling. 

[list of facilities]
[button] Update [button] Cancel

_How can I add a new facility?_

[screen 3]

**Your VA health facilities**

These are the facilities you told us you currently go to for care. We may use this information when you schedule an appointment online. You can update this list at any time.

**Note:** Not all VA facilities offer online scheduling. 

[list of facilities]

[edit link] Add or remove current facilities

_How can I add a new facility?_

**Comment by andaleliz** [comment]
Thanks @DanielleThierryUSDSVA, this is really helpful.  One point to clarify is that in the mock-up screen 1 and 3 are the same screen/URL - the only difference is that one reflects the post-edit state.  

I'm understanding your recommendation as starting with a sort of intro/onboarding content, and then after they edit it once, they'll always see what you're proposing as screen 3.  Is that correct?

If so, we explored that idea but opted to go with the pattern you see in the mock-ups which is consistent with the rest of profile.

Is there a way we can combine the blurbs so it makes sense whether you've ever edited the list or not?

Also, I see you removed the **Note** above the edit button in the post-edit state that lets people know there are other facilities not represented.  I want to confirm you don't think that's necessary. I'm concerned people will be confused, but willing to test w/out any reference to this and see what people say.

Thanks so much for your help :)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @andaleliz! 

- That makes total sense re: screens 1 and 3, thank you for clarifying that. Combined intro is great, yes! Only question I have, which might be a good one for usability testing, is whether it's totally clear that keeping the list current helps us better match the Veteran with an appointment. We can always look at that more/test. 
- Totally understand re: the "edit" link changing back - thanks! 
- I removed the note because I thought the more specific "edit" link helped make it clear that there were more facilities. But if we go back to "edit," I agree people might need that note. So I think it's fine to add back in. Maybe with:
  - **Note:** You're registered at 4 other facilities where you've received care in the past. You can edit this list to add those facilities at any time.
  - For other content, I think you can just open a regular ticket and label it with "sitewide-content-product-support" and "March" and assign it to me and Randi. And we can also chat about it more in next week's office hours.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA glad we're on the same page, and thanks for the extra content note! I'll open that ticket and we can continue to refine from there + during office hours.

**Comment by andaleliz** [comment]
Content ticket created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22036

**Comment by andaleliz** [comment]
@ajakabcin I'm updating the criteria for this ticket to remove the "VSP feedback" dependency - that work is all being tracked in separate tickets.  

I do think it'll be helpful to link `schedule an appointment online` to the [authenticated appointment scheduling page](https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/), and have reached out to all the content/IA folks who have been involved in this review so far to get their blessing.  Approvals for that will be tracked on the relevant content tickets.
