### ISSUE TITLE
Spacing Issues - Media-list-images Page R&S

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#21847]
## Issue Description
_The line spacing between images looks a little squooshed, see images below for spacing fixes for media_list_images in R&S_

[OG Design Mocks](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15618#issuecomment-739889819)

[Slack Convo](https://dsva.slack.com/archives/C52CL1PKQ/p1616094182078600)

<img width="259" alt="Screen Shot 2021-03-22 at 10 37 58 AM" src="https://user-images.githubusercontent.com/70410912/112025609-f44bd680-8afa-11eb-8b01-d922c9e70e53.png">

## Tasks 
- [ ] space between images (and optional text if present) and the next h2. i believe it should be 5 spacing units. 

## Acceptance Criteria
- [ ] Space between images is fixed according to design specs 
- [ ] Validated on preview 

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rtwell** [comment]
@kelsonic can you confirm the % (or number of columns) we've allocated for the images and text on desktop? It's looking really narrow, and i _think_ it might be because we're using the main content column as 100% instead of the full page width. this image might help clarify:

![image](https://user-images.githubusercontent.com/12564977/112029512-b5744b80-8b0f-11eb-8df5-2cb4f5e2566f.png)

**Comment by kelsonic** [comment]
@rtwell The image description currently has a class style on it that reduces its width by 50%, want me to omit that?

current:

![image](https://user-images.githubusercontent.com/12773166/112367434-855bb280-8c9f-11eb-9d4b-f82fb2c5dcd5.png)

without the 50% width:

![image](https://user-images.githubusercontent.com/12773166/112367496-9a384600-8c9f-11eb-8276-5f0a5751c16a.png)

**Comment by kelsonic** [comment]
@rtwell Images' widths are currently reduced to `25%`:

![image](https://user-images.githubusercontent.com/12773166/112367678-d9669700-8c9f-11eb-887f-8c5310a07056.png)

Want me to remove that, too? It would look then like:

![image](https://user-images.githubusercontent.com/12773166/112367736-eb483a00-8c9f-11eb-878a-dcf90035a85e.png)

**Comment by rtwell** [comment]
the `%`s you're referring—is that 25% _of the main column of content_ or 25% of the total width of the page?

**Comment by kelsonic** [comment]
25% of the current column the image is in, not the total viewport width

**Comment by kelsonic** [comment]
![localhost_3001_preview_nodeId=6954](https://user-images.githubusercontent.com/12773166/112376974-c907e980-8caa-11eb-933a-21342875f5d8.png)

**Comment by rtwell** [comment]
got it, thank you. Ok let's try 50% max width for both typography and images

**Comment by kelsonic** [comment]
![localhost_3001_preview_nodeId=6954](https://user-images.githubusercontent.com/12773166/112381880-bd1f2600-8cb0-11eb-9a43-ddd3e66aa4c9.png)

This is 50% for both

**Comment by rtwell** [comment]
Gah this is so tough b/c we don't know what kind of images will utilize this template. tall images will be HUGE, but wider images will be too small (like those screen grab examples). I'm wondering, for non-mobile devices (or maybe a certain breakpoint), we can use a limiting factor. like if an image is 500px or taller, it can only expand to 50% width—does that make sense? is that doable or am i over-engineering this?

**Comment by kelsonic** [comment]
I'm not sure if it's possible, but it would be really cool to limit the size of images (e.g. cropping) within the CMS so that we can better plan how to display them. Would that help you think? If so we can ask Kevin Walsh what he thinks the CMS could do here.

Otherwise, I can write the JavaScript code that checks each image's size and dynamically changes the CSS for each image respectively, but it definitely won't be the cleanest code (e.g. maintainable, easy to build off, etc.) since it will be an inline script in our liquid template. LMK what you'd like me to do 🙂

**Comment by rtwell** [comment]
here's the problem I would like to solve: How might we render images in a way that compliments image sizes, and scales with the CMS? I'm not familiar with best practices in the area, so if you have a recommendation for this, I'm all ears. Happy to toss some time on the cal w/ Walsh to figure out the best approach for this.

**Comment by kelsonic** [comment]
I am not strongly opinionated, just want to provide you with all the options. I think syncing up with @kevwalsh would be helpful to see if we can standardize some of the image sizes for `node-media_list_images` 🙂 My calendar link is in my dsva slack profile 📆

**Comment by rtwell** [comment]
ok last question regarding image behavior: let's say we go max width (like the [mock you posted](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21847#issuecomment-806155393) a few days ago). how are the smaller images not fitting the full width the way the wider images above it?

**Comment by kelsonic** [comment]
So while there is no `max-height` on the images, the images try to match their aspect ratio and it looks like the height and width of the images are set in drupal as `entity.image.height` and `entity.image.width`

**Comment by kelsonic** [comment]
Any update here? 🙂

**Comment by rtwell** [comment]
lets do 2 things
- 50% columns width is gtg
- images can open on their own tab alá [pittsburgh maps](https://www.va.gov/pittsburgh-health-care/university-drive-campus-map/)

**Comment by kelsonic** [comment]
> images can open on their own tab alá pittsburgh maps

Do you mean for each image show the expand icon that is actually just a link to the raw image?

![image](https://user-images.githubusercontent.com/12773166/116948657-3bba9c00-ac3d-11eb-98d8-cc8ad0c0c9c6.png)

**Comment by rtwell** [comment]
yep! I was considering some fancy logic that would leave it off images that were already at 100% resolution, but simple/consistent is probably better. 

we _could_ consider not showing a button, and simply allow the images to be clickable, but /shrug again consistency wins out for me.

**Comment by brianalloyd** [comment]
@kelsonic @rtwell I'm going to create a follow on ticket to address the expand icon for each image.  CC @johnhashva

**Comment by kelsonic** [comment]
PR merged for:

> 50% columns width is gtg

Will go out with daily deploy tomorrow

**Comment by brianalloyd** [comment]
Validated and closing.
