### ISSUE TITLE
[FE] My VA: Update Appointments logic to match new designs

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#21844]
## Background
The [new designs for appointments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md) call for some layout and logic updates.

## Tasks
- [x] No longer render grey div when there are no appointments scheduled in the next 30 days
- [x] Update layout to stack with IconCTALinks when the user has no appointments scheduled
- [x] Improve existing testing coverage around appointment logic
- [x] Update unit tests to reflect new design

**Comment by ajakabcin** [comment]
Issue completed per update from Sandra in standup - closing
