### ISSUE TITLE
[On-call] Ensure procedures and documentation are up-to-date

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#21845]
## Description
On-call operational documentation should be up-to-date with accurate steps and information.

## Background/context/resources
[daytime-oncall-support-role doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a5bf9c37d2e38480507490f59bf69feef2ab8f90/teams/vsp/teams/operations/daytime-oncall-support-role.md)
[plaform oncall folder with various docs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/OnCall)
[Discussion from Michael Fleet regarding weekend slack notifications protocol](https://dsva.slack.com/archives/G01M8VD9USC/p1616416645015100)
[Update to FE tools support policy in response to the slack discussion above (Ops likely does/should have something similar) ](https://github.com/department-of-veterans-affairs/va.gov-team/pull/21820)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Review docs w/ Ops team and update together 
- [ ] Update all relevant on-call support documentation 
- [ ] Submit PRs with relevant changes and attach to this ticket 
- [ ] Review updated docs with Michael Fleet, Dror, et al to ensure alignment on expectations 
- [ ] Set a calendar reminder or other recurring event to revisit and verify accuracy of oncall support docs 

## Definition of Done
- [x] The on-call support role will have clear procedures/protocol/expectations for performing the rotation 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by ph-One** [comment]
Closing. We have met the DoD and continuously make changes to documentation/processes as they are needed -- regular evaluation is taking place.
