### ISSUE TITLE
[Design] Notification preferences - finish design work

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#21855]
## Background

We are continuing work on the design for the notification preferences project.  For reference:
 - [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
  - [MVP documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/communications-permissions-mvp-definition.md)

## Tasks
- [x] Review designs with VA profile team team
- [x] Incorporate feedback from VA profile team as needed

## Acceptance criteria
- [x] All initial rounds of feedback complete and incorporated into design.  Ready for design intent.

**Comment by andaleliz** [comment]
@Samara-Strauss I added some desktop screens to the [mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1616001821140/563f6d0c6a34a52a5708552575b024fdb98e9bfe). Translating to desktop is pushing me toward the read/edit mode.  I know you were also on the fence between the two options, and I'm leaning toward read/edit mode now.  Let me know if this info sways you one way or the other:

- there are some layout issues with autosave if we follow the current multi-column pattern in profile, since the checkbox legend (notification type) needs to be above the form fields. The profile pattern is an a11y violation when it comes to forms.

![image](https://user-images.githubusercontent.com/55992116/112542674-38eda100-8d8b-11eb-9416-b0a2049401b2.png)

We'll have to deviate from the pattern in edit mode with the alternative option, but it's more subtle since the initial view aligns with the rest of profile.
![image](https://user-images.githubusercontent.com/55992116/112542903-7c480f80-8d8b-11eb-95aa-b1913ff59108.png)

- there are complexities w/ autosave regarding confirming with users their changes have been saved, which we don't have to address with the read/edit mode. They are solvable complexities, but at this point, I'm not convinced we need to go there for an MVP.

Looking forward to your thoughts!

**Comment by Samara-Strauss** [comment]
Read only/edit mode is fine with me, though we should be ready to pivot pending testing. If people feel like it's too heavy handed, we should consider bringing back the autosave mode.

**Comment by andaleliz** [comment]
Adding link to UXpin mocks reviewed w/ VA Profile team and devs earlier this week.

Initially VA Profile team said both options would work, but Lihan called out that updating at the group level doesn't align well with how their API is structured (one update at a time).  Regrouping with Terry prior to close of sprint to discuss.

Reviewing screens w/ content team today.

**Comment by Samara-Strauss** [comment]
Adding additional context — Terry did suggest [in Slack](https://dsva.slack.com/archives/C7TE0PFTL/p1617218394047500) that this is a workable problem, but we should definitely determine that in a group convo with Terry/Liz/Lihan/Sandra/Erik.

**Comment by andaleliz** [comment]
@ajakabcin I updated the AC on this to "ready for design intent" since that review will result in a bunch of separate tickets to specifically address their suggestions.  Our Fri meeting with Terry confirmed that we don't need to change anything in the design, so I think we're good to go. Going to close this out and continue design work on this after we have our design intent meeting.
