### ISSUE TITLE
Content strategy, rewriting, and editing for 526 error messages indicating missing information

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#21851]
## Issue Description
There are 17 areas of the 526 application that if not filled in will block submission of the form. When info is missing, an error message appears with a link to the relevant part of the application. The following error message text needs editing and rewriting: header, explanation text, bold setup to the bulleted links, labels for the links, success message once everything's filled in.

---
## Tasks
- [x] Edit/rewrite the text for these error messages. 
- [x] Provide feedback about the user steps to success.

## Acceptance Criteria
- [ ] Plain language, helpful text to guide users to their next steps is in place. 
- [ ] The process and path to success is logical and understandable.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@Mottie I'm attaching here a Word doc with the text I'd like to use for these error messages and link labels. Definitely reach out if you want to talk through anything. I revised the full error message text, not just the link labels. Let me know if that text will work. Based on our slack convo, it sounds like the vast majority of use cases will be missing info rather than "something else isn't right so our system can't accept your application." So I wrote it focusing on missing info. I can rework if that isn't broad enough. 

Questions: 
1/ If the user is presented with more than one link to take them back to the part of the form they need to fill in, how do they get from the first location to the second? Are we providing them with a link to jump to the second place they need to fix. If not, could we do that? 
2/ Is there a way to dynamically tell the user how many places they're missing information (corresponds to how many links we give them to click on)? This is preferable for accessibility reasons, and even for sighted user to be told explicitly how many fixes they need to make. You'll see that highlighted in the Word doc. 

[https://app.zenhub.com/files/133843125/d520a069-d08f-46f8-9887-9d7bbeaa8809/download](https://app.zenhub.com/files/133843125/d520a069-d08f-46f8-9887-9d7bbeaa8809/download)

**Comment by bethpottsVADEPO** [comment]
@Mottie Adding this note here too (from slack):

One of the Contact information bullets asks the user to go back to fill in their postal or zip code. We should remove "or zip" from that line so it says, in parentheses, "enter a postal code for your mailing address" Can you change that on the form screen as well?

**Comment by bethpottsVADEPO** [comment]
@Mottie Do you have everything you need for this now? I'll close this ticket if you do.

**Comment by Mottie** [comment]
Yes, thank you!
