### ISSUE TITLE
Search for and update remaining instances where VR&E info should be changed to new program name

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21864]
## Issue Description
When VR&E changed its program name, we updated all instances in Drupal. However, Robin Garrison found several instances in applications where we still may have the old Vocational Rehabilitation name. We need to review the instances he found and determine whether the name needs to be changed or it's referring to the general term, which we kept in certain places. Below are the instances he mentioned:

Claim status tool:
https://github.com/department-of-veterans-affairs/vets-website/pull/16302#discussion_r592459013

Facility locator:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/config.js#L173

the path to form 1900 is /careers-employment/vocational-rehabilitation/apply which can be fixed by backend redirects

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/view-representative/components/ViewRepresentativeDetails.jsx#L87

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vre/28-1900/config/form.js#L45

https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/common/constants.js#L250

https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/FEEDBACK-TOOL/schema.js#L288

https://github.com/department-of-veterans-affairs/acronyms/blob/master/acronyms.csv#L5341

## Tasks
- [x] Review instances above and determine if any need to be changed (Beth/Randi)
- [ ] Change any instances that need to be changed

## Acceptance Criteria
- [ ] Correct wording around VR&E is set across the site including applications

**Comment by RLHecht** [comment]
@bethpottsVADEPO Looking through the list that Robin had put into Slack, I think most if not all of these need to be updated. There was one I wasn't exactly sure what it was: 

https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/common/constants.js#L250 I think it's referring to the program name so should be changed, but wanted you to take a look as well.

**Comment by RLHecht** [comment]
@Mottie We reviewed all the instances of the vocational rehab/VR&E mentions you noted in our Slack thread and I wanted to follow up. When we were referring specifically to the program name, we should have it changed to Veteran Readiness and Employment. When we are talking about the general benefit, we are leaving it as vocational rehabilitation (lowercased and without "and education"). Of the instances above, they should all be changed to the program title except for the path to form 1900 (we are not changing the URL) and this one: https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/common/constants.js#L250

Are the other changes ones that you can make or should I tag Nick or Kelson?

Thanks again for pointing all these out to us. We thought we had caught them all when the program name changed initially but it seems there were more out there!

FYSA @bethpottsVADEPO

**Comment by Mottie** [comment]
I would be happy to help out when I have time. I'm not sure how much free bandwidth I'll have this upcoming sprint.

**Comment by RLHecht** [comment]
Thanks! That's totally fine if you can't get to it this sprint. Just putting it on your radar.

**Comment by RLHecht** [comment]
@Mottie Just checking in on this and if you opened a ticket I should attach to this one.

**Comment by Mottie** [comment]
I haven't done anything for this ticket yet. Sorry, I forgot and have so many other things to take care of.

**Comment by RLHecht** [comment]
Update: Moving this ticket to blocked. This can't be worked on until the product team has bandwidth for this. It's not something Sitewide Content can do.

**Comment by SgardnerPMP** [comment]
3/30/22 - Product team needs to engage and complete before Content can proceed.  Added Label and assigned to R. Garrison for visibility.
