### ISSUE TITLE
Search for and update remaining instances where VR&E info should be changed to new program name

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21863]
## Issue Description
When VR&E changed its program name, we updated all instances in Drupal. However, Robin Garrison found several instances in applications where we still may have the old Vocational Rehabilitation name. We need to review the instances he found and determine whether the name needs to be changed or it's referring to the general term, which we kept in certain places. Below are the instances he mentioned:

Claim status tool:
https://github.com/department-of-veterans-affairs/vets-website/pull/16302#discussion_r592459013

Facility locator:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/config.js#L173

the path to form 1900 is /careers-employment/vocational-rehabilitation/apply which can be fixed by backend redirects

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/view-representative/components/ViewRepresentativeDetails.jsx#L87

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vre/28-1900/config/form.js#L45

https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/common/constants.js#L250

https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/FEEDBACK-TOOL/schema.js#L288

https://github.com/department-of-veterans-affairs/acronyms/blob/master/acronyms.csv#L5341

## Tasks
- [ ] Review instances above and determine if any need to be changed (Beth/Randi)
- [ ] Change any instances that need to be changed

## Acceptance Criteria
- [ ] Correct wording around VR&E is set across the site including applications
