### ISSUE TITLE
[Content] My VA content updates

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#21872]
## Issue Description

I am combining all content for My VA into one ticket so we can track it all in one place.  This ticket will cover the following design tickets:

- [x] #21543 
- [x] #21369
- [x] #21579
- [x] #21370 (Tressa will provide design for this on March 23, 2021) *Added*

---
## Tasks
- [ ] Content suggestions for all tickets listed
- [ ] Review with Tressa

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
#21543 Can we add "your" to "Continue application"? --> so that it's "Continue your application"
#21369 Why are we using appointment information and contact information interchangeably? Seems like the header of the error message is correct but the text under it needs to change from "contact information" to "appointment information."

**Comment by tressaellen** [comment]
For #21369 - great point the text under it definitely needs to say 'appointment information'. I've updated with that. 

We couldn’t retrieve your appointment information

We’re sorry. Something went wrong on our end and we couldn’t access your appointment information. Please try again later or click the link below to go to the appointments tool.

[Schedule and view your appointments]

![Screen Shot 2021-03-23 at 10.47.16 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/40deb74c-b922-4772-a37b-5986e3ad310a)

**Comment by bethpottsVADEPO** [comment]
Re: #21579 @tressaellen @Samara-Strauss (answering you here Samara, since Tressa consolidated tickets--and the other ticket has closed):

**We can't access any health care information right now**

We’re sorry. Something went wrong on our end. If you get health care through VA, you won't be able to view your health care information right now. Please refresh or try again later.

**Comment by Samara-Strauss** [comment]
That copy sounds good to me! @tressaellen I'll rely on you to make sure this and all updated copy makes it into the [FE copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/my-va-copy.md).

**Comment by tressaellen** [comment]
@bethpottsVADEPO that looks good to me - I'll check that one off. And @Samara-Strauss I'll get that into the FE copy doc. Thanks!

**Comment by bethpottsVADEPO** [comment]
For #21369 - I have a couple other small changes: 
- Can we use "access" instead of "retrieve"? 
- Please add a comma after "our end"
- Please change this sentence: Please try again later or click the link below to go to the appointments tool.
To this: Please try again later or go to the appointments tool: (remove "click the link below to" and replace the period with a colon)

**Comment by tressaellen** [comment]
For #21369 - does this look right to you? And if so, are we good on that one?

**We couldn’t access your appointment information**

We’re sorry.  Something went wrong on our end, and we couldn’t access your appointment information.  Please try again later or go to the appointments tool:

[Schedule and view your appointments]

![Screen Shot 2021-03-23 at 4.33.36 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/dbecbbb0-e2d1-413d-b733-def40f5c0ec1)

**Comment by bethpottsVADEPO** [comment]
@tressaellen Looks great! Are there two spaces between sentences? Should just be one.

**Comment by tressaellen** [comment]
@bethpottsVADEPO - great catch. I'll update. Thank you!

**Comment by tressaellen** [comment]
Hi @bethpottsVADEPO #21370 is all ready for you whenever you have the time. 

Also for #21543 - is that one approved or did you have any further suggestions for that?

**Comment by bethpottsVADEPO** [comment]
@tressaellen Re: #21543 -- If you made this edit, then it should be good now: "Continue your application"
Want to share the latest screen shot here?

Re: #21370 Looks good!

**Comment by tressaellen** [comment]
@bethpottsVADEPO thanks so much for your help! Here's the screenshot for #21543. If there's nothing else then I think we're good to go on this ticket. 

![My VA Desktop Everything.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/cb0e566b-da12-4a5e-8f4d-a5098835ce74)

**Comment by tressaellen** [comment]
@bethpottsVADEPO I have one more piece of content that needs to be approved.

In the first time user experience screen we have some blurbs for the benefits that are highlighted. I made some changes to the education blurb so it aligns a little better with what we have on the homepage.  Let me know if you have any thoughts/changes. 

**Education benefits**

With VA education benefits you or your qualified family members can get help finding and paying for college or a training program.

[Learn about how to apply for education benefits]

![Screen Shot 2021-03-29 at 1.12.42 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/98cb9b48-3694-4766-b160-8a30e133d051)

**Comment by bethpottsVADEPO** [comment]
@tressaellen 21543 looks great, except I think I see another extra space between "all" and "your" in "Manage all your claims and appeals." 

Thanks for sending this latest request along to me! Two things:

1/ Re: the link label for additional text/helper text "What benefits does the VA offer?" 
Please delete the word "the" before VA.
Where's the text that answers that question? Want to post that here for me to look at?

2/ Please use this (is it ok that it's longer and might carry over to the next line?):
With VA education benefits, you or your qualified family members can get help finding a college or training program and paying for tuition or test fees.

**Comment by tressaellen** [comment]
Thank you @bethpotts ! That works just fine, here's the screenshot for the education benefits section. Also, I removed that extra space in "Manage all your claims and appeals" and 'the' from the additional text/helper text.

<img width="1112" alt="Screen Shot 2021-03-30 at 12 40 34 PM" src="https://user-images.githubusercontent.com/58752772/113025041-eec24200-9133-11eb-9ecc-9de2f1ede87d.png">

> Where's the text that answers that question? Want to post that here for me to look at?

**Explore VA.gov to learn about the benefits we offer.**
▪   Health care benefits
▪   Education benefits
▪   Disability benefits
▪   Careers & employment
▪   Pension
▪   Housing assistance
▪   Burials & memorials
▪   Life insurance
▪   Service member benefits
▪   Family member benefits

<img width="410" alt="Screen Shot 2021-03-30 at 12 41 27 PM" src="https://user-images.githubusercontent.com/58752772/113025163-17e2d280-9134-11eb-9f4b-b1067eefa2ad.png">

**Comment by bethpottsVADEPO** [comment]
Thanks @tressaellen --just a few more edits I see. Then I think this is good to go!
1/ For the Education benefits blurb, can you please change "or" to "and" here?: With VA education benefits, you **and** your qualified family members...
2/ For that Education header, I realized you should remove "benefits" to be consistent with the others there. Also, please add "and training" to match the name of the hub: Health care / Disability compensation / Education **and training**
3/ Can you also get the link labels to match: Learn how to apply for VA health care / Learn how to file a VA disability claim / Learn how to apply for VA education benefits
4/ For the bulleted helper text, please remove "benefits" from the first 3, and add "training" to education and "compensation" to disability, like this:
- Health care
- Education and training
- Disability compensation

That's it! Thanks so much.

**Comment by tressaellen** [comment]
@bethpottsVADEPO I've made all the updates. Let me know if you see any last changes - if there's nothing else, then I think we're good to go! Thank you so much for your help! I really appreciate it!

![Screen Shot 2021-03-31 at 11.09.07 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/7f215443-779f-47f4-9de8-7f2bb60e2cc7)

**Comment by bethpottsVADEPO** [comment]
Perfecto! Thanks for implementing all the rounds of edits, @tressaellen!

**Comment by tressaellen** [comment]
Yay! I'll update all the documentation and then close this ticket.

**Comment by bethpottsVADEPO** [comment]
@tressaellen Noticed something that isn't urgent, but that we should make consistent:

#21369 "couldn't" in the header and the body text should be "can't" as we have it with other error messages.

We **couldn’t** access your appointment information

We’re sorry. Something went wrong on our end, and we **couldn’t** access your appointment information. Please try again later or go to the appointments tool:

**Comment by tressaellen** [comment]
I'll update that! Great catch, @bethpotts !

<img width="1072" alt="Screen Shot 2021-03-31 at 12 35 54 PM" src="https://user-images.githubusercontent.com/58752772/113179499-23013580-91fc-11eb-9b87-8845c9208b2f.png">

**Comment by tressaellen** [comment]
I think we got everything that we need here, so I'm closing this. :)
