### ISSUE TITLE
Prevent failed deployments - Create lifecycle policy around available status EBS volumes 

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#21874]
## Issue Description
Running out of total allowed EBS storage (40TiB at the time) caused multiple deploys to fail including vets-api-worker to prod. A support request was submitted and approved to double the allowed space to 80TiB, but we should likely create an automated solution to prevent this going forward. 

Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1616439891346600

---
## Tasks
- [x] Create automation around pruning "available" status EBS volumes
- [x] Look into some form of alerting to inform us when reaching the total capacity 
- [x] Document what's been done 

## Acceptance Criteria
- [x] We don't have several hundred EBS volumes taking up space while not being used. (and it will be documented) 
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchelen-gov** [comment]
looks good, is there a cloudwatch or grafana monitor that can alert for 90% usage?

**Comment by jbritt1** [comment]
> looks good, is there a cloudwatch or grafana monitor that can alert for 90% usage?

Good question, I added ` Look into some form of alerting to inform us when reaching total capacity` as a task so we can look into that as well.

**Comment by mchelen-gov** [comment]
looks like this popped up again recently for caseflow team https://dsva.slack.com/archives/CBU0KDSB1/p1618599091106800?thread_ts=1616439891.346600&cid=CBU0KDSB1

**Comment by jbritt1** [comment]
Did some more looking into this in a "discovery" fashion. Seems we could benefit greatly from using AWS Data Lifecycle Manager ([DLM](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html)). However, it requires a tag for the target in order for the policy to run against necessary resources. We do not currently tag EBS volumes specifically, so this would be a blocker for us in leveraging this particular service.

So we would need to think about a couple different options here. I could see a couple in the form of the following:

 - Automation to trigger daily that would grab all EBS volumes in "available" state with a query based on resources have no tags and add a selected tag (i.e. `dlm_managed: true`). Then let the DLM policy take care of the rest. This would grab current items and all future volumes that go into "available" state with no tags.
  - Clean up the existing items we currently have manually and add some automation to existing pipelines to ensure EBS volumes are tagged going forward and let the DLM policy do the rest. This would also handle existing items as well as future items.
  
Of course open to any and all other ideas, these are just a couple thoughts around this particular body of work.

**Comment by jbritt1** [comment]
We of course also would need a monitor/alert of some sort as @mchelen mentioned to alert us to the limit being approached.

**Comment by jbritt1** [comment]
Got a DataDog monitor stood up that I believe will help us going forward with the alerting of approaching limit portion. Ref: 

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/1e68e438-3b63-4bb6-bfc9-23d5bed9b1b0)


![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/a17e8f7f-56af-45ab-b1d4-4e386e6c8557)

The first image was a test with a higher threshold in order to force an alert. The second is when it recovered after being set to a more realistic threshold. My thought is that we would want to know when we are under 10TiB of storage limit, so that is what it is currently set to alert on if we go below that value. Open to any suggestions for tweaks.

**Comment by jbritt1** [comment]
Manually cleaned 400 volumes this morning which took us from ~64% usage back down to ~53.8%

**Comment by jbritt1** [comment]
Kinda leaning towards a GitHub action solution for this now.

**Comment by jbritt1** [comment]
A [GitHub action](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/ebs-vol-cleaner.yml) was created that handles 15+ day old "available" status / orphaned EBS volumes. It also includes a [Slack notification](https://dsva.slack.com/archives/CJYRZK2HH/p1622232853078700) for awareness, tracking, etc. Moving to review/QA.

**Comment by jbritt1** [comment]
Example Slack notification just in case:

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/0083f059-35e1-4cb3-abd1-d91b795af8e0)

**Comment by jbritt1** [comment]
Need to throw up a small, quick confluence doc on this piece of automation then should be good to close.

**Comment by jbritt1** [comment]
Confluence doc created: https://vfs.atlassian.net/wiki/spaces/OT/pages/1570832385/EBS+Volume+Cleaner+GitHub+Action
