### ISSUE TITLE
Add Feature toggle for KMI updates

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#21876]
# Background
Now that we are making schema changes to the KMI tool we need to hide those behind a feature flag so that users cannot get to this functionality before we are ready to deploy.

## Tasks
- [ ] Add feature toggle code in vets-api
- [ ] Add feature toggle code in vets-website
- [ ] Submit PRs for both sets of feature toggle code for review
