### ISSUE TITLE
Collaboration Cycle - Make Collaboration Cycle more agile

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#21884]
## Problem Statement 
The Collaboration Cycle is a process owned by VA.gov Platform team. It is a series of touchpoints for VFS teams to follow to ensure the products they build for VA.gov meet Platform standards and align to the overall VA.gov.

The Platform Collaboration Cycle was designed to support new products/features built by VFS teams. In early 2021, the process was modified to support iterations to existing VFS products, however the process for iterations is not agile and is very "waterfall." There also also other problems the current process faces, including:

- our current process supports the iteration, not the product. It is not uncommon for the scope of the iteration to change, making it difficult to track and provide support for the team.
- knowing what is in scope for the review is challenging because sometimes VFS teams don't communicate the change/enhancement effectively. The artifacts we receive are similar or identical to the artifacts from a previous review for another body of work.
- product ownership can change, again making it difficult to track/report
- sometimes narrowing the focus to the enhancement alone doesn't allow us to see the product holistically, which could create inconsistencies.
- recommending Full Accessibility & 508 Office audit is challenging. If the team pushes out 2 iterations back to back, we could end up recommending 2 audits for the product. 
- minor reviews can feel unnecessary. Is the amount of time we take to prepare for a review really worth it for an iteration (for example: a 1 line change to a product)?
- tracking feedback from early CC reviews (ie Design Intent) to later CC reviews (ie Staging Review). Per one Platform team member, "I struggle knowing what I recommended at Design Intent when at Staging Review." This is especially challenging when iteration scope has changed or product ownership has changed teams.
- Sometimes small changes bypass Collab Cycle completely
- Urgent work (eg Covid-related) has bypassed Collab Cycle completely.
- we only offer 2 timeslots for staging Review. This could mean that dedicating 1 slot to just an iteration could take away from a team that needs a more thorough review.
- multiple initiatives from the same team may be brought through the Collaboration Cycle at the same time, making it hard to see the connection between the initiatives and view the product holistically. 

HMW provide support to VFS teams in an agile and flexible way while still supporting and enforcing VA.gov standards and practices?

Ideas: 
- remove design and midpoint and have general/generic "cc reviews" prior to staging.
-  first iteration/initial release goes thru CC. After that, audit on recurring cadence (Jim's dr. metaphor)
   - caveats: new design patterns won't fit/work
   - ask the "category" of product: forms, static page, 
   - identify the components of the product at Staging Review, then determine audit cadence
- Copy what Sitewide content is doing wrt intake form at their office hours
- See Proposed flow of making Collab Cycle more Agile in [MURAL board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1630433092173/e295a85b542dbf4ca2f574f0ef1bc1bffc24dd0d?sender=u0574179b1d97118ccc0e3591)
- 

Things that would be valuable:
- Release notes?

## Hypothesis or Bet
TBD

## We will know we're done when... ("Definition of Done")
- [ ] VFS teams don't have to wait long for feedback
- [ ] VFS teams have clear expectations of Collaboration Cycle outcomes
- [ ] Our team members are spending less time per capita on reviews
- [ ] Our team is easily able to provide feedback regardless of product ownership changes or solution design changes
- [ ] Our team is able to get eyes on urgent / emergency work without slowing it down.
- [ ] Our team has better visibility into evolution of the product

## KPIs
- VFS products have fewer formal reviews in a 6 month timeframe
- VFS teams wait < 2 days for feedback
(add to Release Plan)

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: [Make Collaboration Cycle More Agile - Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30372)

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by rroueche** [comment]
This looks awesome! Here's my feedback:Hypothesis or Bet
If we are able to pivot the Collaboration Cycle processes towards a more agile approach then we can still provide VFS products with necessary support, as well as ensure less issues are published in production.

**Comment by shiragoodman** [comment]
thank you @rroueche ! below are my responses.
1. we will leave it blank - thanks!
2. what's currently here is leftover from when this initiative was focused on pivoting towards a "product-focused" model. I should've let you know. Regardless, this is great feedback and I'll be sure to update it.
3. I will add a KPIs section and ping Andrea to see if we can get this added to the template.
4. This is the [VSP Initiative Template ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/vsp-initiative.md) that is linked in our [Product Manager Quarterly Planning Playbook](https://docs.google.com/document/d/1N3HXpdy8qmVbi9O-83WLzePn8d5arPaxdIpUhq3pHcA/edit). I am totally fine adding Business Goals/User Goals to the template.

One last question for you - would you like this initiative to be strictly research/discovery? Or would you like to us split time between research/discovery and implementation of a solution?

**Comment by andreahewitt-odd** [comment]
@shiragoodman @rroueche you should be linking to where your KPIs are tracked under the measurement portion of this outline. 

We can talk about adding business/user goals but I would think a better place for that to live would be the product outline. We can chat about this later, Rachael.

**Comment by rroueche** [comment]
every initiative should have discovery as a part of it, it's up to you what you think will fit in the roadmap for the quarter, but in terms of documentation, the initiative outline should be for the initiative overall, and you will need a separate brief for Discovery that pulls in elements of the overall initiative outline and problem statement, but is specific about the discovery strategy and goals and assumptions you're attempting to validate.
