### ISSUE TITLE
Error States: Dependency Verification Modal Window

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21903]
## Background
We need to be able to have messaging for when data is unable to be rendered or shared with the Veteran that uses the modal window.

## Considerations  
The possible error states that need to be covered are:
- Your info could not be found (blue 400 error)
- Check and reuse the 686c error states as applicable
- 1st Call: If GET request fails, **show nothing** (Data could not be found (red 500 error))
- If POST request fails, show a loading indicator and render a message based on code returned with messaging to the Veteran (might not need this)  

## Tasks
- [ ] Prepare and implement error states as noted above

## Acceptance Criteria
- [ ] Error state message for 500 error is in place
- [ ] Error state message for 400 error is in place
- [ ] Error state message for any other errors are in place
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21574
