### ISSUE TITLE
Error States: View Dependents Formlet

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21902]
## Background
We need to be able to have messaging for when data is unable to be rendered or shared with the Veteran that uses the formlet.

## Considerations  
The possible error states that need to be covered are:
- Data could not be found (500 error) (Handled by page)
- Your info could not be found (400 error) (Handled by page)
- ~~Check and reuse the 686c error states as applicable~~
- Form field validation
- Submission errors

## Tasks
- [x] Prepare and implement error states as noted above

## Acceptance Criteria
- [ ] ~~Error state message for 500 error is in place~~
- [ ] ~~Error state message for 400 error is in place~~
- [x] Message for submission errors
- [x] Inline field validation errors

**Comment by jason-gcio** [comment]
Does error messaging for VD already cover this?  Just wondering if we don't want to duplicate work if we don't need it

**Comment by sporeboy** [comment]
Error states for the View Dependents formlet are mapped here: https://xd.adobe.com/view/109d38ed-c729-4b73-94a7-85f29fa92052-45ce/

We'll need:
- Inline form-field error states
- Submission error

Other error around dependents' data availability (400, 500-series) will be handled using the View Dependents page messaging.

**Comment by jason-gcio** [comment]
Ok cool - do we know if these exist already in the Design System? Or can FE grab these off a shelf or do we need to make them?

**Comment by sporeboy** [comment]
There are design system elements. I have mocks for the text and element placement here:
- [Field validation](https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/ba1c8fe1-a4eb-41a8-b7f2-d76086078b0d)
- [Submission error](https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/70e464a0-a727-4507-b6e8-13263c26516c)

Note: There could be a status indicator on submission errors ID-ing the dependent not submitted... (Maybe)
