### ISSUE TITLE
Sentry - Log formatting and configuration to allow request_uuid queries

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#21911]
## Issue Description
As a user who generates reports from Sentry, it would be nice to have the ability to pull `request_uuid` values in an automated fashion.

Ref to request: https://dsva.slack.com/archives/CBU0KDSB1/p1616428005306400

---
## Tasks
- [ ] Perhaps nginx / Sentry configs in our automation like what is described in this post: https://blog.sentry.io/2019/01/31/using-nginx-sentry-trace-errors-logs#configuring-request_id-in-nginx

## Acceptance Criteria
- [ ] `request_uuid` can be pulled into automated / generated reports if possible
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Tagging @kevinmirc for visibility.

**Comment by jhouse-solvd** [comment]
The user that requested this is no longer on the platform. 

However, as @dginther pointed out: teams already have the ability to modify the information that goes into their logs files. Please reach out to #vsp-operations in DSVA slack if you need guidance on how to do this. 

Closing.
