### ISSUE TITLE
Content Review for Notice of Disagreement Design (NOD)

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#21934]
## Issue Description

We have recently created a design for the digital version of Notice of Disagreement (NOD) also known as a Board Appeal. We are requesting content support for the design. The mockups can be found here:

https://vsateams.invisionapp.com/share/8Y10I6K7DU9R#/447558866_NOD_-_Info_Page

---
## Tasks
- [x]  To rework content as needed to meet va.gov's content standards

## Acceptance Criteria
- [x] Content has been changed to meet the content standards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@kevinstachura As I mentioned, I haven't had a chance to spend much time with this ahead of research, but here are a couple of recommendations for the main informational page (more to come):

On the main informational page... please change the text as follows:
1/ 
## How do I request a Board Appeal?

You can request a Board Appeal online right now.

> Request a Board Appeal 

### Other ways to request a Board Appeal

2/
I see an accordion under "By mail" that says: "Find addresses for other benefit types": Should this be here at all? I think that's only for HLR. Looks like all the address info is taken from HLR, so please switch it to be the address currently on the Board Appeals page.

**Comment by bethpottsVADEPO** [comment]
@kevinstachura Can you incorporate these 2 changes ahead of the stakeholder meeting on Friday?:

1/ Remove the entire section of content under "helpful information"
2/ Insert this below the existing content in the blue box:

**How to opt in to the decision review process if you received a VA decision before February 19, 2019:** If you want to request a Board Appeal under the new decision review process, you’ll need to opt in. To do this, check the opt-in a box on the Board Appeal request form. By checking this box, you’re withdrawing your claim from the legacy appeals process (this is the process for decisions received before February 19, 2019).

**Comment by bethpottsVADEPO** [comment]
@kevinstachura I've added some comments to the InVision file--I got about halfway through the screens. I'm not finished yet! But go ahead and incorporate anything you can ahead of the stakeholder meeting. I'm really curious to talk with them about "issues" vs "conditions" for empathy reasons.

**Comment by bethpottsVADEPO** [comment]
For tracking purposes, I wanted to note here that I took an initial pass at content to address the main content needs. There's still some refining to do to adhere to our content standards, and I'll address the remaining issues at the next stage of content review. 

@kevinstachura I'm going to keep this ticket open for the next round of changes to come from stakeholders.

**Comment by kevinstachura** [comment]
We have done multiple rounds of content changes and the stakeholders have seen a couple passes at content. Closing as complete.
