### ISSUE TITLE
[VAMC] Update all VISN-19 sites with input from Staging review IA, [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#21939]
## Story
As a web user and Veteran, all the VAMC websites should be standardized, so I can find the information clearly and repetitively from site to site.

## Goal
Update all sites in Dual-state or ready to go to dual-state with matching infrastructure

## Task
- [ ] Work with us" are incorrect, they should all have /work-with-us in the URL.
- [ ] "About us" are incorrect, they should all have /about in the URL.
- [ ] Health Programs is not linked from health services to Program pages correctly

## Acceptance criteria
- [ ] All Health service programs have links to correct pages
- [ ] All sites in Dual-state have been reviewed and tested
- [ ] Review run book now includes testing all of these health services
