### ISSUE TITLE
Provide API for nearest vaccine-providing facilities to zipcode

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#21968]
## Issue Description
KMI tool wants to provide users with a list of nearby facilities that are possible vaccine locations, so that users can express a preference about where they get vaccinated. 

Given a zipcode, provide an API that returns the n nearest vaccine-providing VAMCs. The frontend will accept zipcode from the user and use this API to populate a later selection element in the form. 

* This will be separate from the facilities API, but use the facility API internally to determine proximity to the provided zip. 
* This code does similar logic in the original KMI flow (but internally as a service, not as an API): https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/covid_vaccine/app/services/covid_vaccine/v0/facility_lookup_service.rb#L7
* We will configure an allow list of facilities/VAMCs and filter down results to only included allowed facilities. This will let us support the pilot phase where fewer facilities are enabled, then the full roll-out, then fine-tune as facilities need to be added or removed.
* The value of n (number of proximate results) should have a sensible default (in the 3-5) range, but be specifiable as a query parameter (in the 1-10 range) so that if fewer or more results are desired it does not involve a backend code change.
* Return results in a schema that uses the same attribute names as the facilities API (though only returns a limited subset of attributes). That way this can potentially be swapped out for direct use of the facilities API at a later date. 
  * Per Slack discussion - return facility ID, name, city, state, country, distance. 

## Tasks
- [ ] Implement controller within covid_vaccine module that takes zip and n as parameters, returns n nearest vaccine-providing facilities. 
- [ ] Separate PR to establish settings.yml setting for allow list (to ease platform PR approval)
- [ ] Devops PR to get allow list in place for dev/staging/prod (may not need this immediately if the same list is good across the board - but at whatever point we want to make a change, we can update in the devops repo and do a config-only deploy instead of a full build-test-release process).

**Comment by patrickvinograd** [comment]
Right now we are using the definition of "what is a VAMC" that we used earlier - facilities with 3-digit facility IDs plus those in the "consolidated VAMC list". That gives us 144 facilities.

An alternative is to use the `classification` attribute returned by the facility locator and select facilities with classification == `VA Medical Center (VAMC)`. Then there is one facility in that list without an activation_status of `A` so we exclude that. That gives us 170 facilities.

Finally, it's possible that neither of these lists is quite correct and we may need to work off an allowlist or filterlist of facilities stored in settings.yml. 

Will probably at least merge one of the first two approaches pending confirmation from VHA about what the correct list is.

**Comment by patrickvinograd** [comment]
Merged the  initial iteration of this. Will revise as needed to incorporate facility allow/block list.
