### ISSUE TITLE
Update rate for DEA benefits on page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21963]
## Issue Description
The DEA Chapter 35 rates were updated October 2020. Stakeholder Tammy Hurley alerted us that we need to update the number we have on our page to $1,265.

Page to update: https://www.va.gov/education/survivor-dependent-benefits/
Update in the chart toward the bottom of the page. 

## Tasks
- [x] Update rate to $1,265 (Randi)
- [x] Review (Beth)
- [x] Publish page (Randi)
- [x] Alert stakeholder change was made (Beth/Randi)

## Acceptance Criteria
- [x] Correct rate is showing on our page

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please move forward with this update to the chart. Thanks!

**Comment by RLHecht** [comment]
@bethpottsVADEPO Change made here. Can you just take a look and then I'll publish? preview-prod.vfs.va.gov/preview?nodeId=984

**Comment by bethpottsVADEPO** [comment]
@RLHecht Looks good, please publish!

**Comment by RLHecht** [comment]
validated on live site. Closing ticket.
