### ISSUE TITLE
Add date on STEM scholarship page for when PDF has been upated

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#21966]
## Issue Description
Stakeholder Tammy Hurley asked that we add a date for when the PDF of STEM programs was last revised to our [STEM scholarship page](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/). This date should be 3/21.

The link is under the H2 "Which degree programs can I use this scholarship for?"

We don't add dates to links so this will need to be written as a note underneath the link. Beth will provide the copy.

## Tasks
- [x] Supply Plain Language wording for note on revised PDF (Beth)
- [x] Update page (Randi)
- [x] Review (Beth)
- [x] Publish (Randi)
- [x] Alert stakeholder changes were made (Beth/Randi)

## Acceptance Criteria
- [x] Page is updated with date on live site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Let's add this note under the link to the pdf:

**Note:** We updated this full list of eligible programs in March 2021.

**Comment by RLHecht** [comment]
@bethpotts This is ready for you: preview-prod.vfs.va.gov/preview?nodeId=6860

**Comment by bethpottsVADEPO** [comment]
Looks good! Let's hold off and publish this tomorrow after I hear back from Tammy, since this one doesn't seem like an asap kinda thing as does her other request. Let's queue it up and publish it tomorrow.

**Comment by RLHecht** [comment]
published page. will close after deploy.

**Comment by RLHecht** [comment]
Change is live. Closing ticket.
