### ISSUE TITLE
Individual Planning/Grooming Session

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21972]
## Goal 
Commit one hour to preplanning some items before Planning and Grooming

## Tasks
Before Grooming:
- [ ] Stub out any new tickets in the Grooming in column, even if its something that might be closed so we don't lose sight of anything

Before Planning
- [ ] Move tickets from Ready to "Current Sprint" column that you feel will be obvious choices for what we work on next
  - [ ] Enter point estimations
  - [ ] Set Sprint/Milestones as applicable

## Acceptance Criteria
- [ ] New tickets are stubbed out, 
- [ ] Tickets are preloaded into "Current Sprint" column

`no points needed here at this time`
