### ISSUE TITLE
Update Internal Analytics Self-Service Roadmap

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2200]
## User Story or Problem Statement
How might we determine next steps so that we can get closer to VFS team self-sufficiency with analytics?

## Goal
Update internal Analytics & Insights task-roadmap.

## Objectives or Key Results this is meant to further
- Va.gov teams implement their own analytics

## Acceptance Criteria
- [ ] Internal Analytics Self-Service roadmap is up-to-date

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
First draft of high level strategy roadmap [linked here](https://docs.google.com/presentation/d/10QFMqTCrEliqYaQr0dP4MZGOeL9broJPmakNc6A5YKk/edit#slide=id.g61980307dd_0_248)

Github task-based roadmap [linked here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/research/gtm-ga-self-service-process.md)
