### ISSUE TITLE
VRRAP: Create Veteran Rapid Retraining Assistance Program Application 

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22022]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md)

## High Level User Story/ies
As an unemployed veteran without education benefits, I need a way to apply for the Veteran Rapid Retraining Assistance Program so I can receive benefits to pay for training so that I have more employment opportunities.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work is not subject to the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Definition of done
1. An application exists on VA.gov that accepts submissions for the Veteran Rapid Retraining Assistance Program (VRRAP).
2. A process exists that sends submitted data to the Muskogee RPO.
3. All linked stories have been implemented and tested

## VSP Collaboration Cycle.
- [x] Project Kickoff - #22127
- [x] ~Design Intent Collaboration~ - N/A
- [x] ~Usability Testing Prep~ - N/A
- [x] ~Research Plan Review~ - N/A
- [x] Information Architecture (IA) Request - #22142
- [x] Analytics Request - #23723
- [x] Midpoint Review - #22836
- [x] Contact Center Review - #23874
- [x] ~Staging Review~ - N/A
- [x] Privacy and Security Review - [#250](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/250)
- [x] Full Accessibility and 508 Office Audit - #25373
- [x] Post-launch Check-in - [Post Launch Questions Answered](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/vrrap-release-plan.MD#post-launch-questions) and Shared with OCTO

**Comment by dneel-bah** [comment]
Closing epic as functionality has been signed off by EDU and delivered to production.
