### ISSUE TITLE
SPRINT 44 PRIORITIES (Mar 24-Apr 6)

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#22024]
# How to use this document

- This is a living document that everyone is empowered to keep updated.  
- If you complete a task, please come here to check if off.  If you add a new issue or run across something that needs to be discussed in the next grooming session, please include add it to Discussion Topics/Grooming.

## Sprint 44 Priorities (Mar 24 - Apr 6)

1.  Find a VA Form: Discovery to refine search, rank by relevance/popularity
2.  Find a VA Form: [Lighthouse] - Complete fix to remove/prevent duplicate records
3. Find a VA Form: Re-assess which most-searched forms have no descriptions based on latest Best Bets data, create "When to Use" content where it makes sense
4. Yellow Ribbon: Verify events with basic reports, request Domo Dashboard 
5. Update CMS with "When to Use" and Online Tool description data where needed, create/modify Best Bets where needed.
6. Find a VA Form: Design consistency for VA.gov searches
7.  Find a VA Form: [Discovery] Estimate work required to specify language on forms detail page #16632

<hr>

#### Zach (@zacharymorel )
- [x] [BUG] Find a VA Form: "Related to" information missing on some results #19561 - merge FE change to Production 
- [ ] Discovery to refine search, rank by relevance/popularity #19170 
- [x] Find a VA Form: [Discovery] Estimate work required to specify language on forms detail page #16632

#### Cassandra (@callen2563)
- VA.gov Search Consistency - Mock Up Find a Form Results Based on Possible Fields #21513
    - Once Cassandra, Megan & Leyda finish their parts, they will need Josh & Trevor to review, then bring to Design Counsel for review. (maybe next Sprint)

#### John (@johnhashva 
- [ ] Create/modify Best Bets for Search.gov where needed.

#### Marci
- [x] Review Prod CMS for any new forms needing details pages
- [x] Check that acronyms that Zach has been given are in our search terms
- [ ] Update CMS with "When to Use" info, create requests for Content team to review drafts
- [ ] Combine README/State of the Product in GitHub, update links to other docs #22034
- [x] Monitor ID bug Lighthouse is working on
- [X] Monitor Domo dashboard tweaks for Decision Tools Team - Find a VA Form #19689 

<hr>

#### Zach
N/A

#### John
N/A

#### Marci
- [ ] Verify new events, create Domo dashboard/reports request  #22026
- [ ] Combine README/State of the Product in GitHub, update links to other docs #22033

### 🛠️ Technical Debt / A11y Issues
**Our goal is to include 1-2 tech debt issues into each sprint.**

#### Zach
-  [x]  508-defect-3 [COGNITION, SCREENREADER]: Lists SHOULD be announced as lists #18415 (ready for validation)
- [x] 508-defect-3 [FOCUS MANAGEMENT]: Focus outline SHOULD be removed from non-linked heading #8279

<hr>

#### Lighthouse Team
  
- [x] [Bug] Find a VA form search is showing duplicate listing of VA Form 10182 #17484 
    - 2021/03/20 - Mark V will promote new ID field 3/24 (delayed due to Production issues), then will need to remove the duplicate records and populate the ID numbers.  There are no changes on our end.
    - 2021/03/05 - Mark V and Zach are collaborating on a solution
    - 2021/02/26 - Asked for this issue to be lower priority than #19561
    - 2021/02/26 - Met with Lighthouse, Steve Wirt, Zach to discuss.

<hr>

#### 2021-03-26
- Zach has a resolution to the issue with "related to"
- Cassandra coordinating with Ryan on which search should be used; Find a Form has the most modern clean approach, esp on mobile.  Design counsel wants to stay with the round action icon.
- Add Shawna to the tickets/epic for Find a Form

### 🗨️ Discussion Topics/Grooming
- Search changes on FE or in conjunction with LH?
- Can there be a acronym service built on top of what Sam's creating so we could pass in an acronym and get back a form number? 
- Is there another use case for when users "squish" up the form names? (Zach is handling some cases, but not all - "1010ez")
- Double line bug might just be Jen's laptop. We cannot reproduce.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO This is so easy to consume and understand -- makes the task of Planning much easier/efficient.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva I totally agree.  Glad you introduced us to what Brian was doing!
