### ISSUE TITLE
[CONTENT] Translate legacy VA Tennessee Valley health care web pages to new VAMC-upgrade format [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22020]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Tennessee Valley VA Medical Center legacy Site](https://www.tennesseevalley.va.gov/)
[Templates of Required Pages](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VISN-9 Content Folders](https://drive.google.com/drive/folders/15eaoitRZRJGcoGlvGLwjh5ZPzdwjoHEh)
[VISN-9 Health Service Playbooks](https://drive.google.com/drive/folders/18Zhwu5EufxKg4AbY4sCuTpfaR61yV1TD)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
* Completed Content is written in Word Document format (Template can be found in Google Drive) and is saved referencing Medical Facility Name & Web Page Name in folder of the VA Cheyenne Name_
* The following pages will have to be researched and created using the templates created:
- [ ] About
- [ ] Work With Us
- [ ] Jobs & Careers
*INTROS updated in the following CMS/DRUPAL pages:
**Facility page intros**
- [ ] vha_626	Nashville VA Medical Center
- [ ] vha_626A4	Alvin C. York Veterans' Administration Medical Center
- [ ] vha_626GA	Dover VA Clinic
- [ ] vha_626GC	Bowling Green VA Clinic
- [ ] vha_626GE	Clarksville VA Clinic
- [ ] vha_626GF	Chattanooga VA Clinic
- [ ] vha_626GG	Tullahoma VA Clinic
- [ ] vha_626GH	Cookeville VA Clinic
- [ ] vha_626GJ	Hopkinsville VA Clinic
- [ ] vha_626GK	McMinnville VA Clinic
- [ ] vha_626GL	Roane County VA Clinic
- [ ] vha_626GM	Maury County VA Clinic
- [ ] vha_626GN	Athens VA Clinic
- [ ] vha_626GO	International Plaza VA Clinic
- [ ] vha_626GP	Gallatin VA Clinic
- [ ] vha_626QA	Albion Street VA Clinic
- [ ] vha_626QB	Charlotte Avenue VA Clinic
- [ ] vha_626QC	Pointe Centre VA Clinic
- [ ] vha_626QD	Glenis Drive VA Clinic
- [ ] vha_626QE	Glenis Drive 2 VA Clinic
- [ ] vha_626QF	Dalton Drive VA Clinic

*Add "Doing Business with us" to bottom of "Work with us" page, unless 1) There is no information in which case leave area blank, or 2) There is a complete page of information and the Engineer needs to create a new page so the content needs to be added.  

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing System Name & Page Name_
- [ ] Pages have been cross checked by peer content writer for each of the following:
* About
* Work With Us
* Jobs & Careers
** Optional Doing Business with us
* Facility Intro pages as designated above

* Page must be saved in Content folder on Google Drive under Page reference name
