### ISSUE TITLE
[FE] E2E Testing 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#22048]
## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description

Create more testing and methods around testing e2e

## Tasks

> this is a list of technical tasks that need for this ticket
- [x] add any e2e tests
- [x] attempt to fix any skipped tests 
- [ ] create documents to how to test from system to system
- [ ] filter our entered in errored questinnaires
- [ ] test full flow, e2e

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Product team has signed off on the  feature
