### ISSUE TITLE
Compile Resources for Privacy and Security Review (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22041]
## Description
One of the final steps in the collaboration cycle is scheduling a privacy and security review with VSP to ensure an application meets platform standards before going to production. 

## Considerations
- [Collab Cycle meeting description](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-privacy-security-review.md)
- This will be asynchronous
- This may have more complications based on the integrations with the VRE API.

## Required Artifacts for the [Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/251)
- [x] Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31)
- [x] Ensure Product Outline contains Incident Response info, including:
  - [x] Points of contact for your system and dependent VA backends
  - [x] Links to dashboards that help identify and debug application issues
- [x] Links to technical diagrams (checked into GitHub alongside your product documentation), including:
  - [x] An architecture diagram, showing involved systems and how they connect.
  - [x] For non-trivial flows (i.e. more than a single round-trip call from frontend → vets-api → VA Backend), a sequence diagram showing the ordered flow of data and operations between systems.
- [x] Describe any new publicly-exposed endpoints (vets-api or otherwise):
- [x] Describe any new interactions with dependent VA backends
- [ ] Describe any other security hotspots you're concerned about / want extra attention on
- [x] Link to [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- [x] Answer these questions:
### Logging & Data Retention

* Are there any new logging statements or data being stored? This includes data sent to Sentry, Cloudwatch, Google Analytics, PDFs sent to S3, etc...? Consider the front-end, back-end, and infrastructure.
    - [x] Yes
    - [ ] No
* If yes, what kinds of data are being logged or stored? Is there any of the following?
    - PHI: [Personal Health Information](https://www.hhs.gov/hipaa/index.html) is defined by HIPAA. PHI should *never* be logged, *anywhere*. We should avoid even *storing* PHI if possible, but if we must store it, it **must** be strongly encrypted.
        - [ ] Yes
        - [x] No
    - PII: [Personal Identifiable Information](https://www.dol.gov/general/ppii) is defined by the DoL. PII *usually* should not be logged, and if logged the logging **must** be scrubbable. We should avoid storing PII if possible, but if we must, it **must** be encrypted
        - [ ] Yes
        - [x] No
    - PI: [Personal Information](https://www.oag.ca.gov/privacy/ccpa) is defined by the CCPA. PI may be logged, but the logs **must** be scrubbable upon consumer demand (with caveats). We should avoid storing PI if possible, but if we must, the database **must** also be scrubbable upon consumer demand (again with caveats).
        - [ ] Yes
        - [x] No

### User tracking, identity, authentication

* Are there any new cookies?
    - [ ] Yes
    - [x] No
* Are there any new uses of existing cookies?
    - [ ] Yes
    - [ ] No
* Is the feature authenticated?
    - [ ] Yes
    - [ ] No
    - [x] Both

### Front-end

* Does this introduce a new publicly-accessible URL endpoint for the front-end?
    - [x] Yes
    - [ ] No
* Is there any use of `innerHTML`, or otherwise bypassing template rendering system protections like auto-escaping?
    - [ ] Yes
    - [x] No
* Is there any bypass of CSRF protection?
    - [ ] Yes
    - [x] No
* Think like a malicious actor and answer "How could this interface be abused?"

### Back-end

* Are there any new publicly-exposed endpoints (`vets-api` or otherwise), or behavioral changes to existing endpoints?
    - [x] Yes
    - [ ] No
* If YES, please describe the changes:
* If YES, think like a malicious actor and answer "How could this endpoint be abused?":

* Is there any new risky data being sent to `vets-api` (XML, file uploads, etc.)?
    - [ ] Yes
    - [x] No
* If YES, please describe the changes:
* If YES, think like a malicious actor and answer "How could this information be abused?":

* Are there new integrations with other VA endpoints?
    - [x] Yes
    - [ ] No
* If YES, please describe the changes:
* If YES, think like a malicious actor and answer "How could this integration be abused?":

### Infrastructure

* How much new traffic are you expecting to send to `vets-api`? Consider both average (typical weekday traffic) and burst (e.g. an email blast to Veterans).
* What's your rollout plan? Specifically:
    * What % of users are you rolling out to at each phase?
    * What metrics are you looking at before deciding to continue rollout?
* Is there a playbook included in your product outline, for investigating and handling likely failure modes?
    - [ ] Yes
    - [ ] No
* If there new integrations or endpoints:
    - What is the latency/availability profile?
    - Are those expectations configured for monitoring?

### Etc

Describe any other security hot-spots you're concerned about and/or would like extra consideration for:

## Tasks
- [x] Compile all above artifacts into the [Privacy and Security GitHub folder under the CH31 feature](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/)
- [x] Ask Jason to create a request per [these instructions](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=f1337%2C+joeniquette&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D) in va.gov-team-sensitive repository.

## Definition of done
- [x] All artifacts have been provided and stored somewhere safe
- [x] An async request has been submitted

**Comment by digitaldrk** [comment]
[ch31_diagram.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6222499/ch31_diagram.pdf)

**Comment by jason-gcio** [comment]
@micahchiang or @cohnjesse - would one of you be able to answer any of the FE questions?

**Comment by jason-gcio** [comment]
@micahchiang  - Thanks!
For the last question ('**Think like a malicious actor and answer "How could this interface be abused?"**'), is there anything above and beyond the regular things a bad actor could do on VA.gov within this form?  I can't imagine its doing anything different so there might not be anything to note here....

**Comment by digitaldrk** [comment]
# CH31 release plan notes
> Are there any new publicly-exposed endpoints (vets-api or otherwise), or behavioral changes to existing endpoints  

> Please describe the changes:  
`/v0/veteran_readiness_employment _claims`

Takes form JSON from: `/careers-employment/vocational-rehabilitation/apply/introduction`

JSON schema for form: [vets-json-schema/28-1900-schema.json at master · department-of-veterans-affairs/vets-json-schema · GitHub](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/28-1900-schema.json)

This endpoint will accept submissions from auth’d and unauth’d users. Form submission will fail if SSN can’t be found by VBMS when we attempt to upload the 28-1900 PDF to vet’s efolder.

> Think like a malicious actor and answer “How could this endpoint be abused?”:  
Can’t really think of a way for this to he abused. Button disables on submit, we’re using strong parameters, and validating using json schema


> Are there new integrations with other VA endpoints?  

This Form integrates with a 2 services
1. (NOT NEW) VBMS: to upload  28-1900 PDF (this happens on all submissions)
2. (NEW) VRE/CMS: This is a new integration that uses oAuth flow to submit CH31 JSON to an endpoint.

> Describe any other security hotspots you’re concerned about / want extra attention on  

No known concerns


> Are there any new logging statements or data being stored? This includes data sent to Sentry, Cloudwatch, Google Analytics, PDFs sent to S3, etc…? Consider the front-end, back-end, and infrastructure.  

Yes
1. `app/controllers/v0/veteran_readiness_employment_claims_controller.rb`
	* We log errors to sentry if the claim was not saved
	* We log to rails info logs the claim confirmation number and form type

2. `lib/vre/ch31_form.rb`
	* We log to sentry an ‘application_intake’ number. This is captured for a reference so we can verify with integration partner integrity of submission (this is done for success and failure)
