### ISSUE TITLE
Update the What's New section of design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#22059]
## Issue Description
The What's New page on design.va.gov hasn't been updated since Sept 2020 before the DST was formed. We will add an update with all the work that we have done to improve the design system since that time. 

---
## Tasks
- [ ] Draft text with the updates to DST
- [ ] Update the what's new page with text

## Acceptance Criteria
- [ ] What's new page has been updated.

**Comment by caw310** [comment]
duplicate so closing
