### ISSUE TITLE
Improve Build Speed by Reducing the Burden of Testing Tools

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22054]
## Problem Statement 
Currently (3/24/2021) the build pipeline in Jenkins for merges to vets-website master runs approximately 1h21m. This is too long. The build pipeline for vets-website feature branches takes approximately 52m.

- How might we determine areas of the build pipeline that testing tools is responsible for?
- How might we improve execution times for each of the testing tools in the build pipeline?
- How might we reduce the number of tests executed against 

## Hypothesis or Bet
If VFS Teams have tighter feedback loops for the latest pushes in their feature branches and merges to master then they will be more satisfied with the build process.
If VFS Teams are able to receive build feedback in 15-20 minutes then they won't context switch away from their latest push or merge and they can deal with the feedback from the build pipeline more immediately.

## We will know we're done when... ("Definition of Done")
Build steps that the testing tools team owns are not contributing more than 5 minutes of time to the total build time.

## Known Blockers/Dependencies 
Since changes to the build pipeline will be made in GitHub Actions, the primary build mechanism will need to switch to GHA.

## Projected Launch Date
Q2

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by billfienberg** [comment]
>How might we improve execution times for each of the testing tools in the build pipeline?

- I think it would be worth researching how many of our tests are repeating/testing the same operation (for example, how many times are we testing the log in flow)? 
- I wonder if it would make sense to approach e2e testing from a holistic perspective (for example, what are all the behaviors/products/services/etc a specific user/persona would do in a session)? 
   - Hypothetical example: a user might check both prescription and education benefits in the same session, but we might split those two behaviors into two different tests, which could lead us to incur the login process/test multiple times. 
   - Related: [persona based testing](https://dsva.slack.com/archives/C01CHAY3ULR/p1615323650034700)

>How might we reduce the number of tests executed against commits in vets-website?

- We could investigate using dynamic analysis to build graphs showing which tests are run for which files.
   - Related: https://shopify.engineering/spark-joy-by-running-fewer-tests
 - We could investigate using type annotations to build a dependency graph, but that would be a large undertaking. Perhaps it could be a good experiment for a specific folder/app. 
    - Related: [Static analysis](https://blog.logrocket.com/static-analysis-in-javascript-11-tools-to-help-you-catch-errors-before-users-do/)

**Comment by billfienberg** [comment]
https://github.com/maierfelix/Iroh

**Comment by billfienberg** [comment]
💡 Try replacing Webpack with [ESBuild](https://github.com/evanw/esbuild). 

esbuild: 0..37s
webpack 41.91s
webpack5: 54.50s

Source: [esbuild benchmark graphic](https://github.com/evanw/esbuild/blob/master/images/benchmark.svg)

**Comment by billfienberg** [comment]
💡 We might be able to shave some time off of Cypress tests by using an ES Build preprocessor instead of webpack.

https://github.com/bahmutov/cypress-esbuild-preprocessor

>That's pretty strong statement: the ESBuild preprocessor is 17 times faster in bundling the support file and 50 (fifty!) times faster in bundling the spec file. - https://glebbahmutov.com/blog/fast-esbuild/

**Comment by billfienberg** [comment]
💡 Find arbitrary waits and pauses, and replace them with polling. 

Search results for `pause` in `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/search?q=pause
