### ISSUE TITLE
Update Rated Disabilities mockups to new tool-page layout

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#22064]
### Background
The Rated Disabilities screen follows an old right-rail page layout. A new tool-page template has since come into use. The new layout has a single-column format, jump links, and reduced content. These changes are based on usability testing and platform-level directives.

### Tasks
- [x] Redesign Rated Disabilities screen to conform to new tool-page layout
- [ ] Revise content to reduce cognitive overhead and conform to new layout
- [x] Confirm inbound/outbound links are appropriate (pages may have changed)

### Acceptance criteria
- [x] Revised mockups available for review

**Comment by jason-gcio** [comment]
We probably don't need full blown mockups for this depending on how much change there is for the new tool page standard

**Comment by candy-gcio** [comment]
https://sketch.com/s/9a70f4c7-68f8-4998-bfee-2fdbb709cfb2

**Comment by jason-gcio** [comment]
@candy-gcio - is there a public view for this file?

**Comment by candy-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/research-design/tool-design-update-punch-list.md
