### ISSUE TITLE
Schedule Design Intent for COE

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#22069]
## Background
Part of the collab cycle is to check in with the other design folks and get  a sense of their thoughts and guidance as we move towards delivery.

## Tasks
- [x] Work with Jim to schedule a design intent meeting
- [x] (Jim/Jason) Map out next initial collab cycle steps; writing tickets

## Acceptance criteria
- [x] Meeting scheduled
- [x] Next tickets formed

**Comment by sporeboy** [comment]
Made updates to 26-1880 layouts after review of latest Sketch Library file...
