### ISSUE TITLE
Update View Payments mockups to new tool-page layout

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#22065]
### Background
The View Payments screen follows an old right-rail page layout. A new tool-page template has since come into use. The new layout has a single-column format, jump links, and reduced content. These changes are based on usability testing and platform-level directives.

### Tasks
- [ ] Redesign View Payments screen to conform to new tool-page layout
- [ ] Revise content to reduce cognitive overhead and conform to new layout
- [ ] Confirm inbound/outbound links are appropriate (pages may have changed

### Acceptance criteria
- [ ] Revised mockups available for review

**Comment by jason-gcio** [comment]
We probably don't need full blown mockups for this depending on how much change there is for the new tool page standard

**Comment by candy-gcio** [comment]
https://sketch.cloud/s/2cbfbba2-b8c6-490a-8f25-240877a7786b

A few questions (mostly about syncing with new styles in the design system/what's new vs what is an exception):

1. I couldn't find a plain card-like component in the ds (original mocks have a plain gray background). I found interactive cards and decision notifications in forms, but just the bordered informational alerts in the other tools. For now, I've used that blue informational, but let me know if I missed something or if the intent for the forms card includes use in this case.

2. In the payments returned section of the page, the cancel dates are prior to the issue date. Are the columns backwards, or just a copy discrepancy? Or, is the cancel date supposed to be prior (seems very weird, but ::shrug:: could be).

3. Does the logged out view get the "on this page" widget?

4. DS says max 5 cols per table. We have 6. Not sure if this was an exception, or if guidance has changed and we need to update based on that.

5. Green button and icons on buttons - I think I heard last week that the green button is back (instead of an action link). Separately, I saw that the buttons with icons were being removed. So, for now, I have a green "Verify my identity" button. Is that correct? 

Okay, I think that's it... I'm still looking through prod with different user to see what I missed. I turned on public view and embedded the fonts this time, so I hope all that looks right.

**Comment by candy-gcio** [comment]
VP - There are a couple of open questions on the ds components used. Draft change log is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/research-design/tool-design-update-punch-list.md
