### ISSUE TITLE
Homepage Refresh-Express Care in scheduling CTA

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22077]
## Description
On the VAOS homepage, move the Express Care section to the new CTA pattern

---

## Task
- [ ] Verify EC section outside of widget is removed (i.e. CTA not duplicated on page)

- [ ] Verify the below ACs are true when `va_online_scheduling_homepage_refresh` feature flag is true

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/homepage.md) 
- Note- Existing Express Care availability messaging shouldn't change. Let Product know if it's different than the copy doc.

- [ ] If a Veteran is eligible for Express Care, Then show Express Care in CTA widget

- [ ] If a Veteran is **not** eligible for Express Care, Then **do not** show Express Care in CTA widget

- [ ] Given a Veteran is eligible for Express Care, When the scheduling window is **open**, Then Veteran can start flow

- [ ] If user selects Express Care radio option, then "window open" messaging displays

- [ ] Available until time = end time of window (e.g. if EC is available from 7:16am to 11:16pm, then available until 11:16pm)

- [ ] Given a Veteran is eligible for Express Care, When the scheduling window is **closed**, Then Veteran **can't** start flow

- [ ] If user clicks "Express care will be available" additional info, Then "window closed" messaging displays

- [ ] DESIGN - Designs match the specs (copy is FPO) 
- EC in widget https://www.sketch.com/s/aca1478c-8cfa-433e-8e06-d42b53aaa60d/a/PGmEp81#Inspector
- Availability states https://www.sketch.com/s/aca1478c-8cfa-433e-8e06-d42b53aaa60d/a/Gmw8LW5#Inspector
![Screen Shot 2021-03-24 at 9.45.58 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/76caab13-032c-4f45-80be-6032aeeebb92)

## Definition of Done
- [ ] Tasks are complete and acceptance criteria are met

**Comment by laurenernest** [comment]
No longer needed due to sunset of Express Care
