### ISSUE TITLE
Hold to publish until 4/1—Update content on VGLI page to reflect April 1 rate change

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#22072]
## Issue Description
Stakeholder Lori Hamilton asked us to update our [VGLI](https://www.va.gov/life-insurance/options-eligibility/vgli/) page on April 1 with language about the newest rate change. 

There are three places that need updating: 

1. Under the H2 "How much will I pay for these benefits?" text should read:
**Note:** On April 1, 2021, we lowered VGLI premium rates.

2. The text directly above the tables should read: **Choose your age to find monthly premium rates as of April 1, 2021.**

3. Directly below the tables the text should read: See the VGLI premium rates before April 1, 2021 (the link can stay the same) 

## Tasks
- [x] Update text (Selina)
- [x] Review changes and publish (Beth)
- [x] Alert stakeholder that changes are live (Beth)

## Acceptance Criteria
- [ ] Content updated on live site

**Comment by RLHecht** [comment]
@lunascoop These are quick updates we need to make but we can't publish until April 1. I assigned you and Beth since I will be OOO that day. You can make the updates, she can review and then either of you could publish. Thanks!

**Comment by lunascoop** [comment]
@bethpottsVADEPO the page is ready for review. http://preview-prod.vfs.va.gov/preview?nodeId=769

**Comment by bethpottsVADEPO** [comment]
Reviewed your edits @lunascoop and published. Thanks! Moving this to validate.

**Comment by bethpottsVADEPO** [comment]
Closing ticket. Updates are live.
