### ISSUE TITLE
Incorporate design intent feedback into View Dependents Formlet solution mockups

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#22073]
### Background
The View Dependents/Remove Dependents formlet screens were presented in a Design Intent review. Functionality, UX, UI and content were discussed and feedback was provided/documented.

### Tasks
- [x] Revise design of layouts per UI feedback
- [x] Edit text per content feedback
- [x] Revise flow of layouts per UX feedback
- [ ] ~~Mock-up optional UX flows showing a step-wise approach~~
- [x] Mock-up potential error states for formlet

### Acceptance criteria
- [x] Revised "inline formlet" mockups available for review
- [x] new "step-wise formlet" mockups available for review

**Comment by sporeboy** [comment]
- [IA feedback](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21449)
- [Design feedback]()
- [Accessibility feedback]()

**Comment by sporeboy** [comment]
IA feedback:
- Fix breadcrumb text
- Move "add dependents" link to a more prominent position
- Removed "how to" text

Design feedback:
- Removed bolding from card labels
- Set "equal to form..." line to body text (I bolded it)
- Make cancel button a text link

Accessibility feedback:
- Will be addressed in development
- Question: can we have dynamic button labels? E.g. "Remove Joan Smith"

Other: 
- Put in a "learn more" link and reduced text
