### ISSUE TITLE
Architecture for Vet Center pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22071]
## Issue Description
Since we are building these pages from scratch, we have the opportunity to plan the approach from the beginning Architecture-This issue will capture the plan and decisions 

Prototype available [here](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/136042529/simulate/sitemap)

---
## Tasks
- [x] Review [CMS attribute mapping mural](https://app.mural.co/t/vagov6717/m/vagov6717/1614274642123/3509c33494d6dbc74e362cfe458dc5f2a517ec39)
- [x] Evaluate options of existing components from Facility Locator and VAMC
- [x] Evaluate React vs Liquid
- [x] Learn about Type of care attribute

## Acceptance Criteria
- [x] Architecture plan for main page
- [x] Architecture plan for locations page
- [x] Plans document how the page will be built, including the components to be used, pros/cons and how data will be accessed
- [x] List of questions/data we don't know how to acccess
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
[Architecture Doc](https://docs.google.com/document/d/1aJfja1dVPl7kzChWvbncZj5XOMOnr48ejxv2dY3B74Y/edit#)
