### ISSUE TITLE
[Unenrolled POC] Set up scaffolding

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22082]
## Description
Set up frontend scaffolding for unenrolled vaccine scheduling POC

Sample flow (for visual representation only)
![Scheduling workflow - non-vaos.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/16214043-cbb3-42ee-a60f-38d89ccbca37)

Existing VEText solution
https://dsva.slack.com/archives/CMNQT72LX/p1611970391069000

---
## Tasks

- [ ] "Start" page/CTA

- [ ] Confirmation page

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_unenrolled_vaccine` feature flag

- [ ] A user is not required to sign in

## Definition of Done
- [ ] All acceptance criteria are met
