### ISSUE TITLE
Use VA File Number Instead of SSN

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22081]
## Background
When we send data/documents to VBMS we have to send a VA File Number.

We need to ensure we prioritize the VA File number, we think we might be sending SSN and in some rare cases where SSN and VA File number are different.

Something like this (pseudo code):
```
va_file_number: options[:va_file_number] || options[:ssn]
```

## Consider
- CH31 then 686

## Tasks

- [ ] ensure we're good in 686 (KC notified)
- [x] ensure we're good in CH31

## Acceptance Criteria
- [x] CH31 is set for VA file number
