### ISSUE TITLE
Spike solution for Vet Center Main page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22099]
## Issue Description
This issue is to generate the skeleton of the Vet Center main page.

---
## Tasks
- [ ] Generate the Vet Center main pages using GraphQL to access Vet Center data from Drupal. 

## Acceptance Criteria
- [ ] Page resembles prototype
- [ ] Page contains content from CMS,
- [ ] Page uses the build and components outlined in the architecture plan #22071
- [ ] Pages can be viewed in Tugboat and is not available in prod

**Comment by mpelzsherman** [comment]
Code is in `vet_center_spike`
