### ISSUE TITLE
Spike solution for Vet Center locations page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22100]
## Issue Description
This issue is to generate the skeleton of the Vet Center location page using Escanaba Vet Center data. 

---
## Tasks
- [ ] Generate the Vet Center location page using GraphQL to access Escanaba Vet Center data from Drupal. 

## Acceptance Criteria
- [ ] Page resembles prototype
- [ ] Page contains content from CMS,
- [ ] Page uses the build and components outlined in the architecture plan #22071
- [ ] Pages can be viewed in Tugboat and is not available in prod
