### ISSUE TITLE
Finish Vet Center main page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22105]
## Issue Description
This issue is to build upon the skeleton generated in #22099 to complete the Vet Center main page build 

## Tasks
- Complete the Vet Center main page based on CMS data and [UXPIN spec ](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/136042527/simulate/no-panels)

## Acceptance Criteria
 
- [ ] Page contains all required/expected content areas
      - [ ] Breadcrumb navigation using VA.gov home 
      - [ ] Name of Vet Center
      - [ ] Intro text
      - [ ] Operating status 
      - [ ] Jumplinks
      - [ ] Location address and link to directions
      - [ ] Locations phone number
      - [ ] Other locations heading, text and link to Locations page
      - [ ] Hours
      - [ ] Nontraditional hours text
      - [ ] Call center text
      - [ ] Location image
      - [ ] Location map
      - [ ] Prepare for your visit accordions (expecting four: Parking, Transportation services and schedule, What to bring and What to expect)
      - [ ] Spotlight "featured content" (1 national, 2 local expected)
      - [ ] Services accordions - organized by type of attribute (ie: Counseling, Referral, Other)
      - [ ] Service accordions contain expected national and local content
      - [ ] "How we're different" accordions 
      - [ ] "Back to top"
- [ ] Page renders according to UXPIN spec with regard to font, color and size, headings and layout
- [ ] Page is responsive to mobile and other breakpoints
- [ ] Page contains Escanaba test content from CMS,
- [ ] Page uses the build and components outlined in the architecture plan #22071
- [ ] Pages can be viewed in Tugboat and is not available in prod

**Comment by mpelzsherman** [comment]
@brangi and I are working on breaking this into separate stories. See [architecture doc](https://docs.google.com/document/d/1aJfja1dVPl7kzChWvbncZj5XOMOnr48ejxv2dY3B74Y/edit#) for details.
