### ISSUE TITLE
Finish Vet Center location page build

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22106]
## Issue Description
This issue is to build upon the skeleton generated in #22100  to complete the Vet Center location page build 

## Tasks
- Complete the Vet Center location page based on CMS data and [UXPIN spec](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/136042528/simulate/no-panels)

## Acceptance Criteria 
 
- [ ] Page contains all required/expected content areas
      - [ ] Breadcrumb navigation using VA.gov home and main location
      - [ ] Locations heading
      - [ ] Intro text
      - [ ] Main Location 
             - [ ] Operating status
             - [ ] Location address and link to directions
             - [ ] Locations phone number
             - [ ] Image
      - [ ] Satellite locations header and intro text
      - [ ] Each location listed includes operating status, image, "located at header" followed by an address, link to directions and phone number
      - [ ] Other nearby Vet Centers header and location information (if specified in CMS)
      - [ ] " Vet Centers in other areas" header, text and link to the Facility Locator
      - [ ] "Back to top"
- [ ] Page renders according to UXPIN spec with regard to font, color and size, headings and layout
- [ ] Page is responsive to mobile and other breakpoints
- [ ] Page contains Escanaba test content from CMS,
- [ ] Page uses the build and components outlined in the architecture plan #22071
- [ ] Pages can be viewed in Tugboat and is not available in prod

**Comment by brangi** [comment]
@mmiddaugh we are closing this in favor to individual stories - https://github.com/department-of-veterans-affairs/va.gov-team#workspaces/vft-59c95ae5fda7577a9b3184f8/board?labels=vsa-facilities,frontend,vet-center&epics=133843125_20783&repos=133843125
