### ISSUE TITLE
VHA location: Community Living Center

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22113]
## Issue Description
Community Living Centers deliver nursing home level of care, skilled nursing and medical care. It can be a temporary or permanent home. These CLCs are currently displayed as locations under the relevant VAMC. 

Conforming to that content structures awkward as they only display one service accordion: "extended care"
---
## Tasks
- [ ] Determine the right user experience for these facilities

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
