### ISSUE TITLE
Process to access and integrate centralized content

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22112]
## Issue Description
We need to understand how to write complex GraphQL queries to pull the new centralized Policies content

## Tasks
Capture the change to the build system to access and integrate the centralized content.

- [ ] Work with Steve Wirt to understand how to query for the content
- [ ] Work with Kelson Adams to modify the build system to pull it into metalsmith

## Acceptance Criteria
- [ ] Policies work (#21041) is unblocked
---

**Comment by mpelzsherman** [comment]
Blocking this pending update from @swirtSJW

**Comment by mmiddaugh** [comment]
Replaced by CMS issue
