### ISSUE TITLE
[DOCUMENTATION]: Consider adding a section about running Cypress tests with --spec to best practices doc

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#22117]
## Issue Description
A recent issue captured in [Support bot ticket #184](https://github.com/department-of-veterans-affairs/vsp-support/issues/184) surfaced an opportunity to add to our [Cypress best practices on VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-best-practices-on-vsp.md) document. Specifically a section on using the `--spec` command and glob patterns to run a subset of Cypress tests.

## Tasks
- [ ] Update documentation to include information about Cypress `--spec` argument from vets-website README.md

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
