### ISSUE TITLE
"Care we provide" in VAMC template

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22115]
## Issue Description

Semantic headings in VAMC system health service are not structured properly in all displays, causing an accessibility defect. 
“Care we provide at [health care system]” (inside health service accordion) is in a rich text field, giving editors the ability to add heading levels. 

![image](https://user-images.githubusercontent.com/55411834/112385515-52bcb480-8cb5-11eb-88fb-b574f01ff0b5.png)

CMS will write a script to update blobs, removing all heading tags [#4799](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4799) 

Meanwhile, we can put this text into the template and make sure it is  wrapped in the appropriate p tags
---
## Tasks
- [ ] Hardcode the "Care we provide at" in the template
- [ ] Ensure appropriate heading level
- [ ] This must be behind a feature flag and coordinated with CMS

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevwalsh** [comment]
i think this can be closed, since https://github.com/department-of-veterans-affairs/content-build/issues/923 was merged.
