### ISSUE TITLE
[VAMC] VISN 8: VA Sunshine Healthcare Network - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22124]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-8](https://drive.google.com/drive/folders/1YuZ_PJFIEhmOuMhj55oh0lT3aL1uy6Tg)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Bay Pines health care
- [ ] VA Caribbean health care
- [ ] VA Miami health care
- [ ] VA North Florida/South Georgia health care
- [ ] VA Orlando health care
- [ ] VA Tampa health care
- [ ] VA West Palm Beach health care

Facilities include for System:
VA Bay Pines health care:

- [ ] C.W. Bill Young Department of Veterans 
- [ ] Affairs Medical Center
- [ ] Lee County VA Clinic
- [ ] Sarasota VA Clinic
- [ ] St. Petersburg VA Clinic
- [ ] Palm Harbor VA Clinic
- [ ] Bradenton VA Clinic
- [ ] Port Charlotte VA Clinic
- [ ] Naples VA Clinic
- [ ] Sebring VA Clinic

VA Caribbean health care:

- [ ] San Juan VA Medical Center
- [ ] Eurípides Rubio Department of Veterans 
- [ ] Affairs Outpatient Clinic
- [ ] Mayaguez VA Clinic
- [ ] Saint Croix VA Clinic
- [ ] Saint Thomas VA Clinic
- [ ] Arecibo VA Clinic
- [ ] Guayama VA Clinic
- [ ] Comerio VA Clinic
- [ ] Utuado VA Clinic
- [ ] Vieques VA Clinic

VA Miami health care:

- [ ] Bruce W. Carter VA Medical Center
- [ ] William "Bill" Kling VA Outpatient Clinic
- [ ] Miami Flagler VA Clinic
- [ ] Key West VA Clinic
- [ ] Homestead VA Clinic
- [ ] Pembroke Pines VA Clinic
- [ ] Key Largo VA Clinic
- [ ] Hollywood VA Clinic
- [ ] Deerfield Beach VA Clinic

VA North Florida health care:

- [ ] Malcom Randall VA Medical Center
- [ ] Lake City VA Medical Center
- [ ] Jacksonville 1 VA Clinic
- [ ] Valdosta VA Clinic
- [ ] Ocala VA Clinic
- [ ] Saint Augustine VA Clinic
- [ ] Sergeant Ernest I. "Boots" Thomas VA Clinic
- [ ] The Villages VA Clinic
- [ ] St. Marys VA Clinic
- [ ] Marianna VA Clinic
- [ ] Palatka VA Clinic
- [ ] Waycross VA Clinic
- [ ] Perry VA Clinic

VA Orlando health care:

- [ ] Orlando VA Medical Center
- [ ] Viera VA Clinic
- [ ] William V. Chappell, Jr. Veterans' Outpatient Clinic
- [ ] Kissimmee VA Clinic
- [ ] Deltona VA Clinic
- [ ] Tavares VA Clinic
- [ ] Clermont VA Clinic
- [ ] Lake Baldwin VA Clinic
- [ ] Crossroads VA Clinic

VA Tampa health care:

- [ ] South Hillsborough Outpatient Clinic
- [ ] James A. Haley Veterans' Hospital
- [ ] Tampa VA Domiciliary
- [ ] New Port Richey VA Clinic
- [ ] Lakeland VA Clinic
- [ ] Brooksville VA Clinic
- [ ] Zephyrhills VA Clinic
- [ ] Lecanto VA Clinic
- [ ] Hidden River VA Clinic

VA West Palm Beach health care:

- [ ] West Palm Beach VA Medical Center
- [ ] West Palm Beach VA Medical Center
- [ ] Palm Beach Vet Center
- [ ] Jupiter Vet Center
- [ ] Fort Pierce VA Clinic
- [ ] Delray Beach VA Clinic
- [ ] Stuart VA Clinic
- [ ] Boca Raton VA Clinic
- [ ] Vero Beach VA Clinic
- [ ] Okeechobee VA Clinic
- [ ] Port Saint Lucie VA Clinic
