### ISSUE TITLE
Research and Implement Visual Regression Testing in CI/CD

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22129]
## Problem Statement 
VFS Teams do not currently have a means for verifying that changes are not indirectly causing regressions elsewhere in the platform.
VSP personnel do not have any means of continuously scanning for visual regressions on the platform as changes are integrated.

How might we verify that newly integrated changes are not inadvertently causing regressions on the platform?
How might we collect information about visual regressions into a report or dashboard?

## Hypothesis or Bet
Given the ability to observe the impact to regressions on the platform immediately upon integrating their changes, VFS teams can fix regressions with context and precision.
A tighter feedback loop for visual regressions will empower teams to resolve issues more quickly.

## We will know we're done when... ("Definition of Done")
- [x] Visual regression testing tool has been selected.
- [ ] Visual regression testing tool has been procured.
- [ ] Visual regression testing tool has been configured and installed on the platform.
- [ ] Visual regression testing tool use and process has been documented and published for use by VFS teams.

## Known Blockers/Dependencies 
No known blockers

## Projected Launch Date
End of Q2

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by humancompanion-usds** [comment]
Just a note, should we eventually pick this initiative up, since this was originally filed the Design System Team has implemented visual regression testing using Chromatic. In fact, we used it not too long ago to detect a change we picked up from USWDS that impacted a component of ours which was not documented in their release notes. We did do [an evaluation of different solutions](https://vfs.atlassian.net/wiki/spaces/DST/pages/3349217310/Discovery+Visual+Regression+Testing+Automation).

I don't know that our solution scales, and there is cost involved, but I do agree with the premise of this initiative. When the Design System Team picks up the injected header and footer work I have made it a prerequisite that we have some similar visual regression testing for a sampling of sitewide pages so that we can have some sense that any change there is not causing an immediately user visible problem.

**Comment by chrisj-gov** [comment]
@humancompanion-usds Assigning this to you to decide if we should put this in the backlog or close it out.

**Comment by EWashb** [comment]
Is this accurate? https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/visual-regression-testing/?utm_source=chatgpt.com

**Comment by humancompanion-usds** [comment]
@EWashb - I believe that documentation is old. It may be possible to do things that way, but not sure that is still in use.

**Comment by EWashb** [comment]
@CBonade, @va-albers and I would like to get your ideas here. I know this is an old ticket but I wonder what the current scope of this might be for future work to do. Not a priority against other things.

**Comment by EWashb** [comment]
This is a candidate for closure but will make a new card based on FE COP convos.
