### ISSUE TITLE
Collect Acronym Search Data

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#22128]
## Description

As a product manager I want to understand the frequency of which users are searching for acronyms and what acronyms are most popular?

## Tasks

- [x] Review usage data to identify top acronyms, capturing metrics associated with those acronyms
- [x] Determine the frequency at which users are searching for acronyms
- [x] Capture what the top acronyms are  

## Definition of Done

- [x] When we understand which acronyms veterans are searching for and how commonly they use acronyms when searching.

**Comment by denisecoveyduc** [comment]
![image](https://user-images.githubusercontent.com/72393866/113804240-2af53400-972c-11eb-898d-46b1c6e735a7.png)

Updates will be added to [file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/audit/Acronym%20Audit%20Summary.pptx).
