### ISSUE TITLE
Hold until May--Move VR&E subway map out of react widget

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#22125]
## Issue Description
The subway map on the [VR&E how to apply page](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/) is currently in a react widget. The eBenefits team has said the feature will be launching April 19, so they will keep the toggle in place for about a month after that. Sitewide Content needs to touch base with them mid-May to determine when we can remove the widget and put the subway map back into a content block within Drupal.

Once we can remove the widget, a sitewide content team member needs to remove the react widget, add the subway map back into a Drupal component and publish the page.

## Tasks
- [x] Reach out to eBenefits team before May 19 to determine date when widget can be removed
- [x] Remove widget and move subway map back into Drupal
- [x] Confirm with eBenefits team page is OK to publish with widget removed
- [x] Review and publish

## Acceptance Criteria
- [x] VR&E how to apply page is live on site with all content in Drupal

**Comment by RLHecht** [comment]
@jason-gcio Wanted to check in if it looks like we can still remove the react widget for VR&E next week and put the subway map content back into Drupal. FYSA @bethpottsVADEPO

**Comment by jason-gcio** [comment]
We are going to hit 100% today, would it be ok to do this in a week?  I just want to make sure things settle in...

**Comment by RLHecht** [comment]
@jason-gcio That works. I'll reach back out next week to confirm what day we should do it.

**Comment by jason-gcio** [comment]
Here is a link to that other ticket with a few additional edits (in pink)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23928

**Comment by RLHecht** [comment]
@jason-gcio is there any reason the CTA button should stay as a react widget or can we remove it and just put the button into Drupal so the whole page is accessible?

**Comment by jason-gcio** [comment]
I am not sure how I missed this, but I think Beth may have picked this up?  To answer your question though, the CTA button should be just put into the Drupal page.  Holler at me if you want to discuss more!

**Comment by RLHecht** [comment]
Removed react widget from all these pages and put in CTA button. Moving to validate and will close once live on site.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
