### ISSUE TITLE
Add Click Tracking to Best Bets- Backend Endpoint

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#22131]
## Description

Currently click tracking is not implemented on best bets. This issue is to accomplish the required FE and BE lift to connect Best Bets to our existing click tracking endpoint. Our hypothesis is that best bets are incredibly impactful and valuable to the overall user experience and we expect to see high engagement.

## Tasks

- [x] Update Backend Endpoint to allow the Front End to pass in a module code as part of the query parameters
- [x] Related to # #22949 - Update the Front End to pass in a module code that is 'BOOS' when the user clicks on a best bet, and 'I14Y' when the user clicks on a standard search result

    // const moduleCode = bestBet ? 'BOOS' : 'I14Y';

- [x] Denise to reach out to search.gov to find out where/how click tracking will appear for best bets.

## Definition of Done

- [x] Backend Endpoint is ready

**Comment by srsuddath** [comment]
This ticket is complete, however we are not closing it due to the current POC run. Merging in this ticket will interact with the current POC which is a level of risk we are not accepting at this time.

**Comment by srsuddath** [comment]
BE endpoint has been merged
