### ISSUE TITLE
Liquid Template Unit Tester - There appears to be a bug when creating a filename for the saved html file

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#22150]
## Issue Description
There appears to be a bug when creating the `html` filename from the given `liquid` template path. This was reported by Michael Pelz-Sherman:

Michael Pelz-Sherman  2:04 PM
The name of the file is coming out as just `number.html`. It would be great if it used the name of the test or something instead, sorta like how jest does snapshots.

Holden Hinkle  3:11 PM
Looking at your code, the `html` file should be called `phone-number.html` It’s being saved as `number.html`? If so, that’s a bug…

I spoke with Michael. In addition to fixing this bug, we want to add a string that represents a fixture's name after the liquid template name to the `html` filename. This value will be passed in as an argument to `renderHTML()`.

Example:
Given the `liquid` file path: `src/site/layouts/health_care_region_page.drupal.liquid`

And a string representing a fixture: `noLabelLocationName`

The resulting `html` filename will be:
`health_care_region.noLabelLocationName.html`

---
## Tasks
- [x] Fix bug when generating html file name
- [x] Allow dev to optionally pass in a string representing the fixture name

## Acceptance Criteria
- [x] Correct html filename will be created when no optional 'fixture name' string is passed in
- [x] Correct html filename will be created when optional 'fixture name' string is passed in

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/16526

This ticket can be closed.
