### ISSUE TITLE
Collaboration Cycle Kickoff improvements

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#22155]
## Issue Description
The Collaboration Cycle Kickoff ticket went live on Feb 22. Since then, we have identified some areas that may be in need of improvement. The [Collaboration Cycle post-launch review](https://docs.google.com/presentation/d/1m9Scsp_AhjUQ4dRl-n1Rw8APfTVGK8WtEy3VqQO2A7k/edit) includes a full readout of the findings. 

How might we modify the Collaboration Cycle Kickoff to improve the likelihood of PMs answering our questions correctly?
How might we modify the Collaboration Cycle Kickoff so that the flow of questions is more intuitive?

This work has a dependency on [#20444](https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/20444) and the efforts should be worked on together.

---
## Tasks
- [x] reword questions to address points of confusion
- [x] reorder questions so the flow is more intuitive
- [ ] address how to handle work that's previously been through the Collab Cycle
- [x] review the wizard tracks/flow and determine appropriate paths for Track 2 and Track 4 (currently the latter has nothing)
- [ ] review our scripted responses and make changes if necessary, for example:
   - Let teams know that if their solution changes, they should inform us.
   - Let teams know which touchpoints we’re NOT recommending
- [ ] discuss how to address related work moving through the Collab Cycle?
- [x] Merge getting started info into template

## Acceptance Criteria
- [x] Collaboration Cycle Kickoff ticket has been updated to address recent findings
- [x] All related Collaboration Cycle guidance has been updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
What is our process when 2 VFS teams are involved in the completion of the work - 1 team for static content (most likely Sitewide Content team), and the other team for the functional work?

**Comment by 1Copenut** [comment]
@shiragoodman 
Not sure this belongs here, but putting it out there for reaction. I'm interested in starting to socialize the Accessibility Test Plan as part of Collab Cycle kickoffs. I've captured the work and the communication in the two following tickets:
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/21174
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/21178

I'm also interested in the notion of a functional and technical doc, as identified in these two DSVA slack convos:
* https://dsva.slack.com/archives/CJRQ85PQB/p1616861081135100
* https://dsva.slack.com/archives/CBU0KDSB1/p1616860923313700?thread_ts=1616781455.274200&cid=CBU0KDSB1

**Comment by shiragoodman** [comment]
@1Copenut re: the accessibility plan, great. I'm on board. We can talk later on how best to communicate this to teams... not sure if every team completing a kickoff needs to be made aware of the accessibility outline (for example, teams not making visible changes to their product).

Re: the functional and technical doc, let's discuss elsewhere. not sure this is relevant to the CC Kickoff changes... at least not right now.

**Comment by 1Copenut** [comment]
Sounds good @shiragoodman . I'm working on our accessibility testing plan today. Probably won't be done yet, but moving fast. If teams aren't making visible changes or aren't working on new features, you're on point the testing plan may not make sense for them. We can figure out the details when the first draft is posted.

**Comment by shiragoodman** [comment]
changes to template are being captured here: https://docs.google.com/document/d/1FsnuiaPszihDsCHTTosBPmRMJ9ghenu4DyXIEFa2VlA/edit
