### ISSUE TITLE
Modify review instance deploys to integrate content build separation

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#22158]
## Description
As content build and vets-website are separating, we need a way to perform review instance deployments with arbitrary vets-website branches AND arbitrary content-build branches.

It is possible to want a review instance with vets-website 'master' and an arbitrary content-build branch, OR content-build 'master' and arbitrary vets-website branch, OR arbitrary branches for both repos.

To do this we will need a function that is able to determine if a branch name exists in either the vets-website or content build repo that matches the one currently being build in either repo, and if there is one, deploy those branches to the review instance, instead of using 'master' on one or the other.

## Background/context/resources
[Content Build Pipeline - Separate frontend app and content builds#2719
](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2719)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Add a parameter to the ansible/Jenkinsfiles/review_instance_deploy job which allows specification of content build branch
- [x] Apply changes to Jenkins
- [x] Add a function to the Jenkins Common functions which will check for a branch name existing in another repository, returning true or false
- [x] Modify the Jenkinsfiles in both content-build and vets-website to add the extra parameter for content-build branch to use that function to decide what branches to send as parameters for the review-instance deploy.
- [x] Modify https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/review-instance-configure/tasks/main.yml to pull down the content-build repo as well
- [x] Modify the docker-compose.review.yml in vets-website to mount
       - .:/application/vets-website/
       - ../vagov-content:/application/vagov-content
       - ../content-build:/application/content-build
- [x] Modify the https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/review-entrypoint.sh or create an npm script to build the application from the new review instance directory structure. (FE task)

## Definition of Done
- [x] Review instances can be built with arbitrary branches of both content-build and vets-website.

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by theodur** [comment]
PR for modifying review instances to integrate with `content-build` repo: https://github.com/department-of-veterans-affairs/devops/pull/9040

**Comment by theodur** [comment]
## Functionality of Review Instances
- [ ] PRs in the [content-build](https://github.com/department-of-veterans-affairs/content-build) repo that do not have a corresponding PR with the same branch name in the [vets-website](https://github.com/department-of-veterans-affairs/vets-website) should use the `master` branch for `vets-website` in review instances.
- [ ] PRs in the [vets-website](https://github.com/department-of-veterans-affairs/vets-website) repo that do not have a corresponding PR with the same branch name in the [content-build](https://github.com/department-of-veterans-affairs/content-build) should use the `master` branch for `content-build` in review instances.
- [ ] PRs in the [content-build](https://github.com/department-of-veterans-affairs/content-build) repo that do have a corresponding PR with the same branch name in the [vets-website](https://github.com/department-of-veterans-affairs/vets-website) should use that branch for `vets-website` in review instances.
- [ ] PRs in the [vets-website](https://github.com/department-of-veterans-affairs/vets-website) repo that do have a corresponding PR with the same branch name in the [content-build](https://github.com/department-of-veterans-affairs/content-build) should use that branch for `content-build` in review instances.

**Comment by theodur** [comment]
The changes made in https://github.com/department-of-veterans-affairs/devops/pull/9040 are working as expected. All scenarios listed above were tested in the following PRs:
- https://github.com/department-of-veterans-affairs/vets-website/pull/16924 **(branch name: test-RI-changes)**
- https://github.com/department-of-veterans-affairs/content-build/pull/89 **(branch name: test-RI-changes)**
- https://github.com/department-of-veterans-affairs/content-build/pull/86

When 2 PRs with the same branch name exist in `vets-website` and `content-build`, changes in each PR are deployed to the same review instance.

**Comment by theodur** [comment]
Once https://github.com/department-of-veterans-affairs/devops/pull/9040 is merged, the `content-build` and `vets-website` repos will need to be updated to use the new params. I already have PRs for this, the only thing that needs to change in them is the `devops_branch` param from `modify-review-instance` back to `master` in the `Review` Jenkins stage.

**Comment by theodur** [comment]
All of the above PRs have been confirmed to work and merged 🚀
