### ISSUE TITLE
EKS - Autoscaling for clusters/pods

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#22162]
## Description
Working through auto-scaling for EKS clusters 

## Background/context/resources
Now that the eks clusters are starting to take shape and some of the ops owned services are deployed there (grafana/loki/atlantis) we need to start making sure the clusters can gracefully scale at the cluster level (worker nodes) and at the pod level (horizontal pod autoscaling; as needed on a per-service basis moving forward)

## Technical notes
There are a few things that go into this the components being

 - cluster autoscaler (handle scaling of worker nodes)
    https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html 
 - Termination handler (manage creating/terminating pods and nodes gracefully)
    https://github.com/aws/aws-node-termination-handler
 - Metrics sever (required for HPA)
    https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html
 - Per deployment HPA
    https://docs.amazonaws.cn/en_us/eks/latest/userguide/horizontal-pod-autoscaler.html
    https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough
    This is not really a deployment and more so adding the correct definitions per deployment.  We will need to evaluate 
    each deployment and make the determination as to how we want them to scale and defining the constraints as to how 
    they are spread across worker nodes. 
 
---
## Tasks
- [X]  Deploy cluster autoscaler
- [X]  Deploy termination handler
- [X]  Deploy metrics server
- [x] Add cpu/memory requests and limits on containers

## Definition of Done
- [X] Structure in place to implement auto-scaling at the node & pod level in all environments

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@jbritt1 to check on final task

**Comment by jbritt1** [comment]
This was circled back on and ensuring was done that these configurations were set on existing services. However, we later moved in a different direction that leverages horizontal pod autoscaling (HPA) and now that has been set up for existing services where applicable. The scope of this ticket has been completed, but an ongoing task will be that we configure HPA on new services as we stand them up (where applicable).
