### ISSUE TITLE
Update Manual Status for ANY Child Removal

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22167]
## Background
Currently, we are relying on RBPS to return an error and only then do we set the status to `MANUAL_VAGOV`.  BGS has asked us to manually set the status to `MANUAL_VAGOV` for these specific use cases: the removal of ANY child from a Veterans award, in addition to previous manual settings we have already done: death of a child and a school age child has stopped attending school.  

## Tasks
- [x] Update the `MANUAL` status to `MANUAL_VAGOV` for all child removals, even if in combination

## Acceptance Criteria
- [x] The proc state type code has been updated in all relevant places
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/6361
