### ISSUE TITLE
[Design] My VA: Review and update My VA test cases

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22185]
## Background 
In preparation for Staging review we need to review our test cases.

## Tasks

- [x] Review [My VA test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/MyVA%20-%20test%20cases.md)
- [x] Update documentation based on final designs
- [x] Review updates with the team
- [ ] Communicate with @tlei123 to let him know this documentation has been updated and determine whether he or @ajakabcin will update test cases in TestRail.

**Comment by tressaellen** [comment]
@Samara-Strauss @ajakabcin  @erikphansen @sanlouise here is the[ updated test cases document.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/MyVA%20-%20test%20cases.md) Let me know if you have any feedback or changes that you suggest. Thank you!

**Comment by Samara-Strauss** [comment]
### General

- I know we are already linking off to documentation, but it might be worth regrouping with Tze on what he needs in terms of images and screenshots to verify things are correct. Are all the states represented in the docs? They should be. I just want to make sure he has what he needs so we can verify this is all working as intended. 
- Please add test cases around My VA in the unauth nav and how that should work.

### LOA1 user

I linked the heading to the documentation that I just created (sorry that wasn't ready before!).

This looks like all the test cases we need, BUT I do think the Intended Outcome section could use some clarification. For example:

|Test case|Intended outcome|
|----|----|
|LOA1 user has not verified their identity and has an application in progress on VA.gov|User is shown a prompt to verify their identity and also shown their application in progress|

We should clarify that they'll also see "Benefits you might be interested in" so that doesn't come up as a mistake or cause confusion when it's actually intended functionality.

### Test cases for "First-time user experience"

[Per our convo in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1617374356310800), I removed this.

### Disability rating

- I linked this to the nametag documentation.
- Please add test cases to make sure the "View your rating" link works.

### Claims

- Please remove the test case re: number of claims, since that no longer applies.
- Please add test cases to make sure all of the links work. An individual claim should link into the individual claim, and the "Manage all..." link should go to the main Claims and appeals page.

### Health care

Can you clarify the intended outcome for this use case? It probably just needs to be "User sees the health care section." The stuff about the links gets confusing since there is some dynamic functionality there. It actually might be easiest to link to a screenshot to clarify what it should look like.

|Test case|Intended outcome|
|----|----|
|User IS enrolled in healthcare|User sees healthcare section, including the following links: "Get your VA medical records", "Get your lab result", "Refill and track prescriptions", messaging link (could vary based on use case). |

Also:

- Can you remove "Ensure # of appointments is accurate" since that no longer applies?
- Please add test cases to make sure all of the links work.

### Apply for VA benefits

This use case is both if they are not enrolled AND they have never applied, so you might want to clarify. Right now, it's separated into two separate test cases, and that might be confusing.

|Test case|Intended outcome|
|----|----|
User is NOT enrolled in health care|User sees "Learn how to apply for healthcare" link|

This is not correct. Remember that we changed this so the disability link always shows. Please update.

|Test case|Intended outcome|
|----|----|
User HAS filed a claim|User does NOT see "Learn how to file a claim for disability" link|
User HAS NOT filed a claim|User sees "Learn how to file a claim for disability" link|
User HAS NEVER applied for a disability claim|User sees link to "Learn how to file a claim for disability" link then applies, the link disapears, and it becomes a 526 application in-progress|

This also doesn't appear entirely accurate, but please refresh my memory:

- The first use case appears to be correct.
- For the second one, I think we may still show the edu prompt even if they have an application in progress. Can you confirm and update if necessary?
- For the last one, I think the test case is actually "User receives DD4edu payments" not that they don't have an application in progress. Can you please confirm and update if necessary?

|Test case|Intended outcome|
|----|----|
|User receives DD4edu payments|User does NOT see "Apply for education benefits" CTA|
|User has started or submitted an application for education benefits|User will NOT see the "Learn how to apply for Education Benefits" link |
|User DOES NOT have an application for education benefits in-progress|User will see the "Learn how to apply for Education Benefits" link|

**Comment by tressaellen** [comment]
Thank you for the feedback! I'll sift through this and make changes this afternoon/Monday.

**Comment by tlei123** [comment]
@tressaellen , thanks much for getting the doc started!  Looking great so far...

May I suggest either:
- adding a Design Prototype column to the tables for case-specific links to designs? or
- at least a main Design Prototypes link at the top of the doc?

If a template exists for this kind of doc, it'd be great to have above column or main-link added there for future re-use.

I need content/styling references for visual testing.

Thx much in advance!  :)

**Comment by tressaellen** [comment]
@Samara-Strauss and @tlei123  - I've made all the updates and added links to visuals for [this test case document.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/MyVA%20-%20test%20cases.md) Let me know if you have any more changes or need anything else. Thanks!

**Comment by Samara-Strauss** [comment]
Thanks for these updates! A few things:

- The link for the My VA unauth state links to an image of the logged-in dashboard. It needs to show the unauth nav with My VA in it (it can be on the homepage or something).
- **Ensure # of new messages is accurate** — How should Tze do this? I know the answer, but I want to see how you would navigate this if I wasn't here :)
- **User is NOT enrolled in health care and has NEVER applied for healthcare** — This screenshot doesn't show what it looks like if health care is in the "Benefits you might be interested in section," though it's not clear to me if it should be or not based on how the task is worded.
- **User DOES NOT receive DD4edu payments** and **Learn how to apply for education benefits [link]** — You can use user 226 for this, or really any user. 378 is the only staging user that *does* receive direct deposit for edu payments.

Otherwise, this looks great! Thank you for getting this updated :)

**Comment by tressaellen** [comment]
Thanks for combing through this again! I've made all the updates! 

- For ensuring the # of messages is accurate, I just included a note to cross reference MHV and make sure that the number of unread messages matches what is shown on My VA. Is there any other details that I would need to include there?

**Comment by Samara-Strauss** [comment]
> Thanks for combing through this again! I've made all the updates!

Great! We should be good to go, then.

> For ensuring the # of messages is accurate, I just included a note to cross reference MHV and make sure that the number of unread messages matches what is shown on My VA. Is there any other details that I would need to include there?

Yep, this is exactly it. You could actually save Tze the time by logging in to the MHV staging account with [staging user KRISTIE](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md#secure-messages) and seeing how many unread messages she has (don't read the messages so they stay as unread).

**Comment by tressaellen** [comment]
Okay cool! I'm having issues getting into staging on MHV right now, but I'll try again tomorrow and add that in when I can. But I think we can call this done, so I'll close this. :)

**Comment by Samara-Strauss** [comment]
I forgot to mention this, but try signing in through this button. At some point in time, the other routes weren't working (🤦‍♀️ ).

<img width="1280" alt="Screen Shot 2021-04-06 at 4 33 15 PM" src="https://user-images.githubusercontent.com/34068740/113774961-00888400-96f6-11eb-92bf-abd058c55950.png">
