### ISSUE TITLE
Add (PDF) and (YouTube) to end of links where needed

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#22182]
## Issue Description
VA.gov style is to use the descriptions (PDF) and (YouTube) at the end of all links that are either PDFs or Youtube videos. There are a few places on our site where those descriptions are missing.

Pages found needing info added:
- https://www.va.gov/disability/eligibility/
- https://www.va.gov/disability/get-help-filing-claim/

## Tasks
- [x] Add parenthetical to end of needed links (Randi)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Live links have correct info in parentheses at end

**Comment by RLHecht** [comment]
Work completed. FYSA @bethpottsVADEPO
