### ISSUE TITLE
[Design] My VA - Plan for/coordinate assistive tech testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22197]
## Background
As part of the My VA redesign work we need to consider assistive tech testing.

## Tasks

- [x] Schedule meeting with Trevor
- [x] Discuss with Trevor potential for assistive tech testing
- [x] Form a strategy for incorporating this into the project plan if determined we want/need this
- [x] Create tickets as needed for executing the work

**Comment by tressaellen** [comment]
Scheduled for 1/1 with Trevor.

**Comment by tressaellen** [comment]
We chatted with Trevor today and it was very helpful! I've documented what we learned [here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/assistive-tech-research-questions.md)

The most important things to note are:

- We have to do this test after launch since it must be done in prod
- If we want to do a mobile test, we need to follow up with Josh or Trevor so they can figure out how to get it to work on Android phones (right now they've only figured it out for IOS)
- We need to do a dry run before the actual research begins to make sure all tech issues are ironed out. 

@ajakabcin do you want to make tickets for the last 2 bullet points?

**Comment by ajakabcin** [comment]
Create one to for both of those - I think they can be combined, but let me know if you think differently! #22543

**Comment by ajakabcin** [comment]
Closing this as all tasks are complete - follow up ticket created as noted above
