### ISSUE TITLE
Audit VAMC CTAs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22202]
## Issue Description
The Facilities team recently became aware of the button/link design shift which will impact various CTAs throughout the VAMC product. There are a number of CTAs which use buttons but behave as links and should be styled accordingly. 

### Pages/areas which should be reviewed (may not be a comprehensive list)

For the purpose of this issue, a VAMC = pages with this root: https://www.va.gov/pittsburgh-health-care/ 

- https://www.va.gov/pittsburgh-health-care/
- https://www.va.gov/pittsburgh-health-care/health-services/ 
- Prepare for your visit > Chaplain services 
- health service accordions > Schedule online appointment 
- https://www.va.gov/pittsburgh-health-care/register-for-care/

<details>
<summary> Screenshots </summary>

![pittsburgh system home](https://user-images.githubusercontent.com/55411834/112683434-2b8df080-8e37-11eb-849c-84a11b276a83.png)
![image](https://user-images.githubusercontent.com/55411834/112683546-58420800-8e37-11eb-9286-ce17af6db2e4.png)
![image](https://user-images.githubusercontent.com/55411834/112684208-4b71e400-8e38-11eb-9bba-c5a403562916.png)
![image](https://user-images.githubusercontent.com/55411834/112684655-eff42600-8e38-11eb-8ae4-5904d8847e43.png)

</details>
---

Although the Make an appointment page is within the VAMC product, the button/link to sign in is a component owned by another team. A similar issues is present on the [Pharmacy page ](https://www.va.gov/pittsburgh-health-care/pharmacy/)

<details>
<summary> Screenshot </summary>

https://www.va.gov/pittsburgh-health-care/make-an-appointment/
![image](https://user-images.githubusercontent.com/55411834/112684488-bc190080-8e38-11eb-9673-99adf888ccb1.png)

</details>

---
## Tasks
- [x] Audit VAMC pages to identify CTAs which need to be styled as links rather than buttons. 

## Acceptance Criteria
- [x] Document a list of changes which need to be made 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Created the following issues:

- Replace VAMC "Learn more" CTA #22645
- Replace VAMC top task CTA #22646
- Replace "Apply online" CTA on VAMC Register for care page #22647
