### ISSUE TITLE
Remove YouTube urls in CH31 Orientation Section

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22203]
## Background
The stakeholders have indicated that the real You Tube urls will be available later this spring so we should remove these placeholder videos for now and be ready to add them back in at a later time.

## Tasks
- [x] Remove or comment out the urls so they are no visible on the FE
- [x] Make a note of their location so that the real urls can be reinstated

## Acceptance Criteria
- [x] The video is removed from CH31 orientation content
