### ISSUE TITLE
Research & prototype Popunder for /sign-in on vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#22205]
## Issue Description
As a part of the SSOe Screen Redirect Improvement Research a possible solution was proposed: A Popunder tab.

This ticket will conduct research, provide pros & cons, and create a prototype of a Popunder for the vets-website sign in mechanism which currently has multiple redirects.  The popunder, while not reducing the number of redirects would allow a better User Experience.

---
## Tasks
- [x] Research possible Popunder solutions
- [x] Create a pros & cons list of solutions
- [x] Prototype a Popunder solution that works in staging

## Acceptance Criteria
- [x] Research amount of time required for Popunder solution
- [x] Try to create a prototype solution
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
In my research, the Pop-under can be implemented pretty easily using the `window.open()` method and I created a simple prototype.  The next task to tackle was communicating across the newly created tab.  I researched a few different options to communicate across the tabs including
- **Broadcast Channel**,
- **Service Worker**,
- **Local Storage**,
- **window.postMessage method**

The first three all allow cross-tab communication with a caveat, they have to be from the same-origin to prevent any malicious code from being executed.  The `window.postMessage` was the only option that did not have this restriction if the popup is spawned from the page that opened it.  While we do get the benefits of getting a Popunder there are a few concerns that need to be addressed.

1. We would need buy-in from ID.me to use the `postMessage` method to send us a message when the page is fully loaded
2. We would need to additional headers `Cross-Origin-Opener-Policy` (protect our origin from attackers) & `Cross-Origin_Embedder-Pollicy` (protects users from our origin)
3. We would need a security audit to ensure nothing malicious can happen.

I think if we get buy-in from ID.me with the `postMessage` the site can implement the Popunder in a sprint.

**Comment by AGarcia-Clarity** [comment]
## **Update**
ID.me Sync meeting on 4/6 with Kyle Fairbanks, Cory T., Joe N., and I and provided ID.me with an ask for the `postMessage` implementation on the ID.me side.  The conclusion came back that an additional meeting would be set up with Tanel and other ID.me engineers.
