### ISSUE TITLE
Research & prototype Popunder for /sign-in on vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#22204]
## Issue Description
As a part of the SSOe Screen Redirect Improvement Research a possible solution was proposed: A Popunder tab.

This ticket will conduct research, provide pros & cons, and create a prototype of a Popunder for the vets-website sign in mechanism which currently has multiple redirects.  The popunder, while not reducing the number of redirects would allow a better User Experience.

---
## Tasks
- [ ] Research possible Popunder solutions
- [ ] Create a pros & cons list of solutions
- [ ] Prototype a Popunder solution that works in staging

## Acceptance Criteria
- [ ] A popunder is created when I try to sign in with ID.me, DS Logon, or MHV
- [ ] The current page (non-popunder page) will display useful information
- [ ] User is logged in as normal and the popunder tab is closed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
