### ISSUE TITLE
[Super Epic] Outreach & Events Hub - 2021 Enhancements

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#22241]
## High Level User Story/ies
As a VA digital comms lead and user of the VA.gov CMS, I need new capabilities and features as a publisher in the Outreach & Events hub, so I can provide information more effectively to my Veteran and caretaker audience.

## Hypothesis or Bet
If we make improvement and enhancements to improve the authoring experience and to enhance the feature set, the result will be (a) more efficient publishing times, resulting in higher customer satisfaction cores (b) and higher consumption of the content, as measured by page views.

## OKR
These changes will help the VA achieve its veteran communication and engagement goals.

### UX Feature & CMS Authoring Enhancements:

- [ ] Ability to share preview link of Event with stakeholders **on and off** the VA network -- e.g. share an event with a partner organization for review before publishing (Requestors: VEO and VBA)
- [ ] Ability to feature events on the main landing page of [Outreach and Events](https://www.va.gov/outreach-and-events/).  -- e.g. enabling the "Feature this Content" function in the editor. (Requestor: VEO) (Related CMS story: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1318) 
- [ ]  Ability to integrate with events at the [National Resource Directory](https://nrd.org) -- e.g. we can dynamically pull events from NRD into the O&E library?
- [ ] Add disclaimer on all O&E pages -- events featured do not constitute an endorsement from the VA
- [ ] Ability to feature the events in a calendar interface as an option.
- [ ] Ability for user to customize listing of events either by filtering per state or via an interactive US map.
- [ ] Ability for user to filter fact sheets by language (English, Spanish, Tagalog) **Needs moving to a separate epic/issue**.

### CMS Authoring Changes

CMS Epic "Improve Event form" https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1605

- [ ] Ability to have multiple days and times for a single event as opposed to creating multiple versions of the same event (Requestor: VEO)
- [ ] Ability to create recurring events (Requestors: VEO and VBA, also VAMC) CMS epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1956
- [ ] Auto-archiving of past events (Requestors: VEO and VBA) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4214 
- [ ] Ability to shrink down a loaded image so you can fit more of it in the 7:2 aspect ratio (Requestor: VEO)
- [ ] Removal of "Cost" field for Events as all VA events are no-cost. (should this be hidden or true by default?)

## Next steps

- [ ] Prioritize list by product lens (Dave and John)
- [ ] Point the priorities by team.

## Definition of done

- [ ] Work with the CMS team to assess and determine the value and LOE of the requested changes (if needed, validate assumptions with the VA stakeholders) 
- [ ] Ability to add more Social Networks in the Social component -- in particular, Instagram and LinkedIn. (Requestor: VEO)
- [ ] Break each into well-groomed tickets and determine likely timing of delivery
- [ ] Communicate the timeline of delivery to VA stakeholders (e.g. manage expectations)

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by johnhashva** [comment]
Per @kevwalsh: 

- Recurring events is on the backlog but iceboxed. A very common feature request!
- On the FE, a link to the facility is displayed. We need to hide that address form when user selects a facility (part of department-of-veterans-affairs/va.gov-cms#1605 , also on the backlog but iceboxed)
- Our team doesn’t own the Preview server, i don’t think think this is on anyone’s backlog though.
- Old events should be archived eventually, but nothing is automated right now.

department-of-veterans-affairs/va.gov-cms#1605

**Comment by jilladams** [comment]
@cohnjesse hi - I'm new Delivery Manager on the new Public Websites team and trying to sort out the pile of tickets / epics related to Events. There is a separate, nearly identical epic on this topic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42556. (Formerly #28918). Will is disrupt anything from your perspectives to close this epic as a duplicate? Or, are you able to help explain the distinction between these 2?

**Comment by cohnjesse** [comment]
@jilladams Not sure why I am being asked about this ticket but Im happy to help in any way I can. Did you mean to at a different user?

**Comment by jilladams** [comment]
Dupe of #42556 , closing
