### ISSUE TITLE
Define documentation site solution approach

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2227]
## Product Outline
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/product-outline.md

## Problem Statement
We are investing full effort in migrating content to the new, public va.gov-team repo, while simultaneously entertaining a variety of different documentation site ideas that we suspect have better UX (such as GitHub Pages /docs directory and Gatsby). Before we can determine the best path forward for a documentation site, we need a better understanding of the needs of our users, the problems we are trying to solve, and what potential solutions might be. What can we learn about our users, existing pain points, and the solution options available, and what resulting solution might we recommend for the next iteration of the documentation site?

## Hypothesis
If we run a 5-day cross-functional discovery sprint on this problem space, we'll be able to understand the needs of our users, the problem we're trying to solve, and the existing solutions, and therefore we'll be able to recommend an approach for the next iteration of the documentation site.

## Goals
- Identify user needs and user pain points with the current way of doing things
- Better define the scope of what problems we expect a documentation site to solve
- Understand the solution options available to us that could be implemented without significant blockers specific to VA access rules
- Recommend a high level approach and outline next steps for implementing the next iteration of a documentation site
- [Stretch] Create blue sky documentation site mockup to validate our vision

## Definition of Done
- [x] Discovery Brief presented to VSP Clients + Leadership and shared with entirety of VSP
- [x] Product Outline updated 
- [x] Next steps epic(s) and top priority user stories are in ZH, ready to be further groomed and picked up by implementation team(s)

**Comment by meganhkelley** [comment]
Discovery Sprint Core Team: 
Facilitator: Rachael Roueche
Product Manager: Megan Kelley
Information Architect: Mikki Northuis
Frontend Engineer: Bill Fienberg
Frontend Engineer: Dan Shank
Designer: Crystabel Reiter

Pre-sprint resource packet: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/research/discovery-sprint-12-2019/prep-resource-packet.md
