### ISSUE TITLE
Create a Smoke Test to Monitor Platform Login Functionality in Production

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22288]
## Bet
Smoke tests executed on a schedule, monitored in a dashboard, alerted in Slack, targeting core aspects of the platform, and executed in production are an effective way of monitoring for emerging issues in production.

## User Story

As platform support personnel, I need to monitor the functionality of the platform in production in order to be aware of emerging issues. 

## Expected Behavior
* The smoke test scenario simulates logging in to the platform
* The test is executed on a schedule
* The test is executed against production
* Test pass/fail status is reported to a dashboard
* N consecutive failures triggers a notification to Slack / Email / PagerDuty???
* The test scenario has been written in Puppeteer and is staged from the AWS Canary service platform using Operations guidance and documentation from their original **Search Test**

## Acceptance Criteria

- [x] Test scenario script has been created in Puppeteer
- [x] Test is scheduled to execute
- [x] Test results are collected into a dashboard
- [x] Test is hosted in the AWS Canary platform

# From the Duplicate Ticket
## Description 
There is a need for a smoke test that tests standard login on the platform. Leverage the newly created AWS Canary + Terraform implementation from the Ops team to create and schedule for execution a synthetic monitoring test targeting production. A high level sample set of test steps is below --

Navigate to va.gov
Click on Sign-in
Click on the ID.me Sign in with ID.me
Enter production test account credentials
Click Sign in to ID.me
Continue through the 2FA verification
Verify login landing page is free from errors

---
## Tasks
- [x] Sync with Ops to leverage the tooling they have already set up
- [x] Consider using the Canary recording mechanism to record the steps as a starting point
- [x] Review Puppeteer script for fragile selectors
- [x] Create a pull request with the completed test and work with Ops to review any requested changes

## Acceptance Criteria
- [x] A smoke test running on a schedule against production verifies that the ID.me login mechanism of production is functioning as intended

**Comment by rjohnson2011** [comment]
5/3 Update: 
Synced with @omgitsbillryan on 4/30 to go over Puppeteer build script deployment to AWS. The script is running successfully on AWS and triggering alerts if a build error is caught in the console.

For documentation reference, here is the puppeteer gist:
https://gist.github.com/rjohnson2011/483ce2dc7081a3814c0679457e8f68d3 

The PR for AWS conversion:
https://github.com/department-of-veterans-affairs/devops/pull/9050
