### ISSUE TITLE
Create AWS Credentials for Github Actions Self-Hosted Runner 

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#22290]
## Description
Testing Tools Team wants to use a Github Action self-hosted runner on a private, internal team repo. We need a testing-tools-team repo set up with AWS credentials for an AWS IAM team with permissions to access EKS & AWS parameter store.

## Background/context/resources
This ticket helps fulfill https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/20422

## Technical notes
N/A

---
## Tasks
- [x] Create private testing-tools-team repo with admin access for @pjhill & @rjohnson2011 
- [x] Create AWS IAM team for testing-tools-team
- [x] Give proper permissions to access AWS parameter store
- [x] EKS access for team

## Definition of Done
- [ ] testing-tools-team repo with AWS EKS/IAM/parameter store creds

**Comment by rjohnson2011** [comment]
An internal repo for testing-tools is created and available to both Testing Tools and Operations teams as admins.
https://github.com/department-of-veterans-affairs/testing-tools
