### ISSUE TITLE
Design intent [VSA Authenticated Experience, Communication Permissions (Notification Preferences)]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22309]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Link to this issue once created in #design in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] VSP: Create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to VSP feedback tickets.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts
- [Communication Permissions (Notification Preferences) product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
- Link to [mockups](https://preview.uxpin.com/bb87d0fa61a32938a47e7bcdc836db235ab77576#/pages/137640964/simulate/sitemap?mode=i)

## Meeting attendees from requesting team
- Designer(s) (required): @andaleliz  
- Product Manager (required): @ajakabcin 
- DEPO Product Lead (recommended): @Samara-Strauss 
- DEPO Design lead (recommended): @rtwell 
- Content, IA, accessibility, and QA specialists (if applicable): @mnorthuis 
- Other stakeholders you want to invite (if applicable): @joshkimux and @AngelaFowler82 

## Scheduling
Would you like this review to be asynchronous? Please refer to the Design Intent guidance for the difference between a synchronous meeting and an asynchronous review.

- [ ] Yes
- [x] No

What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **Friday, 4/2 2:00 pm ET**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@ajakabcin Friday @ 2 is already booked. Do you have another time preference?

**Comment by ajakabcin** [comment]
How about 11am on Tuesday 4/6?

**Comment by allison0034** [comment]
@ajakabcin this has been scheduled for Tuesday 4/6 at 11am.

**Comment by andaleliz** [comment]
Heads up to reviewers; we're leaning heavily toward the first option (read/edit) for our MVP UX. This autosave option is something we've considered and want to keep in our back pockets in case usability points us in this direction.

**Comment by peggygannon** [comment]
HI, @andaleliz Hello! have you had a chance yet to sync with sitewide content on this feature?

**Comment by andaleliz** [comment]
Closing this out since all feedback tickets have been addressed
