### ISSUE TITLE
Platform Website — Determine content migration order

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#22318]
## Problem Statement 
The Platform Website currently has a mixture of backend development documentation and links pointing to GitHub pages.  We want to populate the Platform Website with information written in Confluence, but we need to determine the order in which info is populated.  That way, we can provide a minimum reading experience to a VFS team member.

_HMW populate the Platform Website in a way that leads to a VFS' member's wholistic reading experience?_  

## Hypothesis or Bet
There are a couple of product lists floating around: [A list based on a Summer 2020 card sort](https://docs.google.com/document/d/1gvypxz20PvluHfkzOOxjALvd11pU59k6U_RR38SifCs/edit?pli=1) and [a list based on 2021 Q1 PMs assessment](https://docs.google.com/spreadsheets/d/1VN73fnx-nQToTMhpLKbQJYIHvxKdmfvFozcBUVvcJks/edit#gid=0).

If we use the product lists to inform the order that info populates the Platform Website, then we can provide VFS teams a minimum viable experience of consuming Platform Website info.

## We will know we're done when... ("Definition of Done")
- [ ] We have an artifact that outlines the order of info needed for the Platform Website.
- [ ] (stretch) The artifact is socialized amongst Platform Teams.

## Known Blockers/Dependencies 
- All Platform Teams - The Content Team will need to know what products teams are planning to release when.

## Projected Launch Date
- Mid May.

## LAUNCH CHECKLIST

<details>

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

</details>

## REQUIRED ARTIFACTS

<details>

### Documentation
* **`PRODUCT_NAME`**: [Platform Website directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website)
* **Product Outline**: [Platform Website product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/platform-website-product-outline.md)
* **README**: n/a
* **User Guide**: n/a

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: [Platform Website product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/platform-website-product-outline.md)
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22319

</details>

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
