### ISSUE TITLE
Process for writing and communicating issue tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#22310]
## Issue Description
Product Support has defined "platform standards" or "platform review criteria" (name still TBD) - in essence, this is the criteria that VFS teams will be evaluated on/assessed against as they bring their work through the Collaboration Cycle. Product support now needs to determine how we will move from the current [Collab Cycle Feedback template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-feedback&template=collab-cycle-feedback.md&title=Practice+Area+Feedback+-+Name+of+Collab+Touchpoint+-+Name+of+Project) to our new process. OCTO would like us to create 1 ticket per issue found, however there are still many decisions to be made. Some questions that we have include:

- how would VFS teams like to receive feedback in the Collaboration Cycle?
   - currently they're child tickets on the CC review. Would specific labels be helpful? assigned to VFS team epic?
   - 5/27: user research might be valuable. we ask them to close tickets and they don't. we still want to include them as child tickets to the Collaboration cycle touchpoint. Shira to discuss this with Rachael.
   - 6/15: Include in Communication Plan - issue tickets are not to be closed until the issue is resolved. These tickets will be used to assess the health of VA.gov so it is critical teams don't close prematurely.
- if we find multiple instances of the same issue, will we create multiple tickets? or 1 ticket?
   - 5/27: 1 ticket for multiple instances of the same issue would be preferred so feedback is not duplicated across tickets, and so all reference information is in 1 location. Concerns about platform awareness of the multiple issues within the ticket.
   - 6/16: 1 ticket per issue.
- how will we handle issues that cross practice areas?
   - 5/27: see 5/27 discussion notes below. 
   - 6/15: Feedback for multiple practice areas will be merged prior to bulk gh upload.
- what labels will we apply so we can track status of these issues?
   - issue #, practice area, defect level # (accessibility), team label, launch-blocker, "collab-cycle-feedback" 
- can we create a standardized template that all Collab Cycle reviewers can use?
   - Currently, the accessibility specialists have [their own process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/writing-508-issue-tickets.md) for creating accessibility issues tickets within staging review. Since this process is already used by a11y specialists across the platform, how can we retain the critical elements of it so as not to disrupt their current practices?
   - 6/15: yes!
- How would feedback at Design Intent differ than Midpoint Review differ than Staging Review?
  - 5/27: Staging is a different thing than Design Intent. Midpoint is challenging. 
  - 6/15: design intent and midpoint will not change. to be discussed later on.
- How can we ensure that our new process doesn't drastically increase the amount of it takes to communicate issues to VFS teams?
   - 6/1: Bulk github upload. 
   - 6/15: see above.
- pre-alignment process before linking feedback to CC review ticket (AKA before VFS sees)
   -6/15: to be included in our Communication Plan. 

5/27 discussion:
-what if we only did Staging Reviews on Thursdays or Tuesdays? That way we can schedule a time to meet internally prior to the team meeting.
   - 6/15: Team would prefer Thursday so that internal pre-Staging sync meeting can occur the week of. Pre-staging meeting will occur Wednesday during out PS standup.
-how is accessibility going to work?
-we know there's going to be gray area - how do we want to handle that?
   - 6/15: Issue 0 will need to be added to our Proposed Va.gov Exp Standards list with the category Other, and the Platform Issue defined.
   - keep process the same. tailor the words and how we would present it.

6/3 question:
How will our proposed changes impact the Full Accessibility & 508 Office Audit?
 - 6/15: Shira to sync with Trevor and Noah on this process.

6/8 question:
How will we deal with questions we have in CC reviews?
- 6/15: Staging - if you have a question, put as a comment in the ticket. Midpoint - if you have a question, document in your practice area feedback OR comment on the ticket.

---
## Tasks
- [ ] Create a new template/framework that is issue focused.
   - [ ] Possible headings/areas of feedback for each practice area:
   - [ ] 508 issue template existing headings
   - [ ] screen that the issue is on (link)
   - [ ] issue
   - [ ] standard
   - [ ] severity (lb or not)
   - [ ] practice area (or as labels instead)
   - [ ] Reviewers (point of Contact)
   - [ ] Recommendation 
   - [ ] References (Design.va.gov, WCAG, Forms Library, Style Guide) 
- [ ] New title for issue tickets
- [ ] Labels:
   - [ ] using the labels that are pre-assigned to the template
   - [ ] existing a11y process
   - [ ] practice areas
   - [ ] Collab Cycle specific touchpoint labels (design intent, midpoint, staging)
  
[MURAL board for new Github Template](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1622562739924/d349ce89128f8c9566777439bb1e61148eb8cb36)

## Acceptance Criteria
- [x] We have a Github issue template, including labels, we will use for creating issues at Staging Review.
- [x] We have defined a process for how issue tickets will be created at Staging Reviews. (@allison0034 )
- [x] We have a Github issue template, including labels, we will use for creating feedback tickets at Design Intent and Midpoint Review. (possibly same template that already exists)
- [x] We have defined a process for how issue tickets will be created at Design Intent and Midpoint Review. (possibly same process that already exists).
- [x] We have determined how the face-to-face meetings of Design Intent, Midpoint, and/or Staging Review will take place. (@allison0034 )
- [x] We have documented our internal process. (@allison0034 )
- [x] We have determined what Collaboration Cycle documentation will need to be updated (to be completed at a later date as part of [ticket #25617)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25617) (@peggygannon )
- [x] We have synced with VSA Accessibility Specialists to share our VA.gov Experience Standards document and our new process for writing tickets
- [x] We have synced with VSA Accessibility Specialists re: communicating tickets at the face-to-face meeting.
   - Meeting scheduled for 7/1 (via ticket #25763) will include this communication
   - [ ] Additional issues tickets may need to be created, contingent upon VSA Accessibility Specialist response.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
when issues are found, should we...

- recommend teams fix themselves per guidance

OR
- provide the recommended fix

OR
- both... depending on the situation

**Comment by shiragoodman** [comment]
in order to show VSP engineering that we would greatly benefit from a form connected to github for creating issue tickets, we need to capture the time it currently takes to create an issue ticket for a specific review vs. the time it takes to create an issue ticket with our new proposed approach.

**Comment by shiragoodman** [comment]
no more "round robin" in review meetings with VFS teams

**Comment by shiragoodman** [comment]
@mnorthuis @peggygannon @allison0034  - as a follow up from yesterday's meeting, please be sure to review the MURAL board linked above. Please add comments, reorder the heading cards, or propose new names/labels. Thanks.

**Comment by shiragoodman** [comment]
let teams know that we won't be validating resolved tickets.

**Comment by shiragoodman** [comment]
@allison0034 any update on our process or how face-to-face staging reviews will take place?

**Comment by allison0034** [comment]
No, but I will work on it today.

**Comment by peggygannon** [comment]
@shiragoodman Below is a list of Collaboration Cycle documents that need to be updated to reflect the new ticket and meeting process for CC staging reviews: 


- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-staging-review.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md 
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md

**Comment by shiragoodman** [comment]
Allison - process for face-to-face feedback at Staging Review

Present issue by issue. Align ahead of time at pre-sync meeting to decide who will be giving the feedback.

Only present high level findings, and only launch-blockers.

problem with going by practice area: might be confusing for VFS teams.

Mikki - do we need to go thru each issue? No, launch blockers first.
