### ISSUE TITLE
Content review - Non-technical discovery on automation opportunities

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2232]
## Problem Statement 

VSP’s content specialist spends a non-trivial amount of time addressing “low-level” content issues, which prevents VSP from being able to scale to support an increasing number of VFS teams and initiatives.  Also, VFS teams rely on the VSP content specialist for all content reviews, reducing their ability to self-serve and thus iterate on their own.

_HMW automate content reviews so that we can serve more VFS teams?_

_HMW automate content reviews so that VFS teams are able to address issues on their own?_

## Hypothesis or Bet

If we develop automated content reviews, then the VSP content reviewer will be freed up from enough manual support to allow VSP to scale more seamlessly.

If we give VFSs the tools to identify and address their own low-level content issues, then they can move through the Collaboration Cycle and get to production more quickly.

## We will know we're done when... ("Definition of Done")

- [x] We have a set of common content validation warnings (preliminary list: [2235](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2235))
- [ ] We understand the user journey(s) for va.gov content writers (see: [15318](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15318))
- [ ] We have identified possibilities for where in the content writers' workflow it makes sense to have these validations (see: [15318](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15318))
- [ ] We have identified tentative metrics to gauge successful integration with content editors’ workflow

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/automated-content-review/product-outline.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: [Internal documentation kept in /products/platform/content/automated-content-review](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/automated-content-review)
* **Product Outline**: [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/automated-content-review/product-outline.md)
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: [Product outline KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/automated-content-review/product-outline.md#key-performance-indicators-kpis)
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by rroueche** [comment]
@meganhkelley and @alexpappasoddball is this definitely still a BE Tools initiative as well? I know we have engineering talent on Content & IA now, so am just curious if this is still cross-team or not.

**Comment by meganhkelley** [comment]
@rroueche I would advocate for keeping this as a shared BE Tools/Content & IA initiative. Keifer is still heavily involved and a lot of this is BE work (which we do not have a resource for on Content & IA). C&IA should own the product roadmap etc but I still anticipate needing collaboration from BE Tools.

**Comment by meganhkelley** [comment]
Decision to pivot MVP from "adjacent" to the CMS user's workflow, as initially planned, to using Vale as a GitHub action: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/automated-content-review/decisions.md

**Comment by KevinMHoffmanUSDS** [comment]
> We understand the user journey(s) for va.gov content writers

@lianilychee Is this a dependency on the service design tea0m? 

Generally speaking, this "definition of done" list seems to center on content, and not IA (or other practices). Is that intentional?

**Comment by lianilychee** [comment]
For posterity - conversation continued in VSP Roadmap (Google Sheets).

**Comment by shiragoodman** [comment]
@peggygannon would you be able to create an issue ticket for this initiative focused on non-technical discovery?

**Comment by peggygannon** [comment]
@shiragoodman Yes, here the non-technical discovery issue. https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15318
