### ISSUE TITLE
QA Dashboard: Discovery - Accessibility Metrics

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#22331]
## Issue Description
As a VFS Team member, I'd like to understand how well the product I'm developing is scoring based on platform QA standards, specifically in the area of: Accessibility Testing.

---
## Tasks
- [x] Survey the industry to determine what other organizations track in these areas
- [x] Look into what metrics are available through our current set of tools
   - [x] Look into what other tools may be able to provide to gain additional insights
- [x] Discuss any additional metrics that we'd like to know and research those metrics to determine if it can be tracked
- [x] Identify which metrics we will track (supporting metrics)
   - [x] Identify any key metrics that will be used to score the product in this area (KPIs)

## Acceptance Criteria
- [x] We will have a final list of KPIs and supporting metrics
- [x] We have identify sources for each of those metrics
- [x] We have tested to ensure those metrics are accessible
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rjohnson2011** [comment]
Report available at https://docs.google.com/document/d/1YIujIxjTrrE5Hpgsem97WZsrl0pcqL2WzDrI3jrzOew/edit?usp=sharing
