### ISSUE TITLE
QA Dashboard: Discovery - Manual Functional Testing Metrics

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#22334]
## Issue Description
As a VFS Team member, I'd like to understand how well the product I'm developing is scoring based on platform QA standards, specifically in the area of: Manual Functional Testing.

---
## Tasks
- [x] Survey the industry to determine what other organizations track in these areas
- [x] Look into what metrics are available through our current set of tools
   - [x] Look into what other tools may be able to provide to gain additional insights
- [ ] Discuss any additional metrics that we'd like to know and research those metrics to determine if it can be tracked
- [ ] Identify which metrics we will track (supporting metrics)
   - [ ] Identify any key metrics that will be used to score the product in this area (KPIs)

## Acceptance Criteria
- [ ] We will have a final list of KPIs and supporting metrics
- [ ] We have identify sources for each of those metrics
- [ ] We have tested to ensure those metrics are accessible
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Document with notes - https://docs.google.com/document/d/1rk0Ilqxo0gkYxx4P_kEqLAoXD0Ua5gJH2o8nc_d1y0w/edit#heading=h.9u6pencv4e30

**Comment by holdenhinkle** [comment]
Waiting on access to DOMO.

**Comment by pjhill** [comment]
Discovery has been completed -- next up is MVP.
