### ISSUE TITLE
[BE Tools] Application Build Pipelines (CI) -  Implement GitHub Actions for vets-api

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#22348]
## Problem Statement 

Currently, the build times for vets-api are around 20 minutes but with the current BRD process, there is not much room for improvement and easy parallelization. Additionally, Jenkins has security issues that are hard to resolve. As a result the full platform is migrating away from Jenkins to Github actions at the Ops team recommendation. 

_We will be working closely with Ops on this initiative -- mostly looking to them for guidance and them using us a a guinea pig_

How might we confirm that Github actions can fully replace what we do in Jenkins for the BRD for vets-api. 

How might we move all our BRD operations from Jenkins to Github actions. 

## Hypothesis or Bet
*If we can move all our BRD process for vets-api to Github actions, we can then streamline the build to bring down our build times.

## We will know we're done when... ("Definition of Done")

- [ ] All the CI actions for the vets-api deploy live in Github actions
  - [x] [Linting and Security Checks are performed by GitHub Actions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22436)
  - [x] [Specs are performed by GitHub Actions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22944)
  - [x] Coverage reports are generated and fail the build via GitHub Actions
  - [x] [Dangerbot is performed in GitHub Actions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24197)
  - [x] [Move tests to self-hosted runner](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23197)
  - [x] [All CI actions are removed from Jenkins & Circle CI (lint/security/specs/reporting)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24536)

## Known Blockers/Dependencies 
Dependent on collaboration with Ops team because they are leading the initiative to move from Jenkins to Github Actions. 

## Projected Launch Date
End of June 2021

### ... tested?

- [x] Usability test (`N/A`) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [x] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [x] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [x] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [x] ... and should be linked from the VFS-facing README for your product
    - [x] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [x] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [x] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: [github-actions](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/github-actions)
* **Product Outline**: https://vfs.atlassian.net/l/c/AmaoZzxq
* **README**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/github-actions/README.md
* **User Guide**: https://depo-platform-documentation.scrollhelp.site/infrastructure/

### Testing

* **Usability test**: N/A (internal tooling change)
* **Manual QA**: N/A
* **Automated tests**: N/A

### Measurement

* **Success metrics**: https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593880/Continuous+Integration+CI+using+GitHub+Actions#Measuring-Success
* **Release plan**: #26438

**Comment by jeff2d2** [comment]
We've decided to pull [Build and run tests from Docker in CI](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24537) out of scope for this epic as it can be accomplished as a follow-up effort.
