### ISSUE TITLE
[Research] In-person Digital Check-in Research Plan and Assets

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#22343]
## Description
Finalized plan for how we will synthesize the in-person research findings. Create assets needed to complete synthesis, probably a Mural board.

## Tasks
- [X] Create new folder for this specific test: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/in-person-discovery
- [X] Add [research plan/conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/in-person-discovery/researchPlan-conversationGuide.md) to GitHub
- [X] Create necessary assets to complete synthesis 
  - [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1617116600269/1f327d221ba7c89b302311089ceee0c49f7ad493)
  - Spreadsheet for raw notes/observations (Added in the comments below.

## Acceptance Criteria
- [x] Review synthesis plan and assets with team (particularly Ming)

**Comment by kristenmcconnell** [comment]
Here is a spreadsheet that researchers can use to capture raw notes and observations if they find this method helpful. They aren't required to utilize this.

[https://app.zenhub.com/files/133843125/0d1db740-2ef3-4787-af94-c586f07c357a/download](https://app.zenhub.com/files/133843125/0d1db740-2ef3-4787-af94-c586f07c357a/download)

**Comment by kristenmcconnell** [comment]
@mlighdc - Review the about spreadsheet and Mural board. 

I was thinking that the spreadsheet could be used by the researchers to gather notes and observations. They don't have to use it though. I can send is out to the group of you that will be researching if you think it is valuable.

As for the Mural board, I was thinking that we could fill out the Mural board as a group during an afternoon working session to synthesis the research finding. I can schedule a time (once everyone knows when they will be completing in-person observations).
