### ISSUE TITLE
Run ForeSee and Medallia Intercept Surveys in Tandem

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#22346]
## Issue Description
_In an effort to develop the most meaningful, understandable, and relatable Medallia CSAT score we plan to analyze similarities and differences of ratings and scoring from users on the same or similar VA.gov pages._

---
## Tasks
- [x] _Explore ways to run ForeSee and Medallia intercept surveys in tandem_
- [x] _Document proposed approach and present to VA Account Experience leadership_
- [x] _Align on next steps and draft stories for implementation approach if feasibility is found and agreed upon - document if this approach will not work_

## Acceptance Criteria
- [x] _Story(ies) for implementation of tandem survey are created and planned for this or next sprint_ -OR-
- [x] _Why approach will not work is documented in this story_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
- It does not seem feasible to run these in a typical  A/B fashion (I think we pretty much knew this).
- A notable concern about running them on similar pages (ex. pages within the same product or category on va.gov) is the fact a Veteran may be hit with both surveys within a short amount of time while trying to complete similar tasks. This is because users are tracked separately in each platform.
- In an effort to avoid that poor experience for Veterans, I recommend we launch the Medadllia satisfaction survey pilot as planned within the Find VA Locations product (ForeSee will be disabled here) and do the following:

1. Compare (Medallia<->ForeSee) month-over-month within Find VA Locations.
2. Compare same month previous year within Find VA Locations.
3. Compare against any other relevant categories.
4. See what that tells us and decide a path forward from there.

I feel this is a prudent path forward, which may still give us the information we are looking for.
