### ISSUE TITLE
Facility Locator Onboarding

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2234]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [ ] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist

- [x] PM: Attend intro meeting with product support PM
- [x] Attend general onboarding meeting
- [x] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [x] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [x] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/DigitalModernizationStrategy.pdf)
- [x] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/The-new-VA.gov-briefing-2019-07.pdf) documentation
- [ ] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [ ] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md)
  - [x] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [x] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [x] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [ ] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [ ] Designers/PM: Attend breakout session
- [ ] Engineers/PM: Attend breakout session
- [ ] Front-end Engineers/PM: Attend deep-dive session
- [ ] Back-end Engineers/PM: Attend deep-dive session
- [ ] PM, Designers and Content Writer(s): Request content and IA intro @meganhkelley @mnorthuis @thatmattjohnson 
- [x] PM and Front-End Engineers: Request analytics intro @nedierecel @joanneesteban 
- [ ] Full team: Request KPI workshop with analytics team @joanneesteban 
- [ ] PM Request 508 intro @1Copenut 
- [x] PM and Engineers: Request load testing, privacy, and security intro @peterhill-oddball 

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [ ] Assign the issues to individual(s) to complete
- [ ] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [ ] Attach the issues to this Epic

**Comment by mmiddaugh** [comment]
**Content and IA intro** 10/17 @ 3 PM EST
**Analytics intro**  10/11 @ 11 AM EST
**KPI workshop** TBD
**Load testing, privacy, and security intro** 10/10 @ 11 AM EST
**508 Intro** 11/11 @ 1 PM EST

**Comment by mmiddaugh** [comment]
Onboarding tasks are complete with the exception of obtaining access to local tools, which has been requested separately in [3088]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/3088)
