### ISSUE TITLE
[BE Tools] Security & Compliance - Developer Tool Authentication (Sidekiq)

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#22354]
## Problem Statement 
Sidekiq doesn’t have any authentication and there isn’t a “platform wide solution” to add authentication for a developer tool. 

We first need to come up with a platform recommended authentication approach for tools that don’t come out of the box with authentication. Then we need to implement that auth solution for Sidekiq.

[More details about problem statement](https://vfs.atlassian.net/wiki/spaces/VI/pages/926089332/Sidekiq+Access)

## Hypothesis or Bet
If we create a recommended authentication solution for developer tools and get acceptance from all of engineering and OCTODE, platform will be more easily maintained because teams won't be implementing different authentication experiences across platform crew.

## We will know we're done when... ("Definition of Done")
- [x] We have researched authentication options
- [x] We have presented those options and our recommendation to the other engineering teams on platform crew, Identity team, Dror, Michael, Mike Chelan, Cory Trimm and Rachael. 
- [x] Everyone has agreed on one solution.
- [x] The authentication solution has been implemented for Sidekiq

## Known Blockers/Dependencies 
None

## Projected Launch Date
July 2021

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [x] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [x] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [x] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [x] ... and should be linked from the VFS-facing README for your product
    - [x] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [x] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [x] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Sidekiq jobs
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/VI/pages/926089332/Sidekiq+Access
* **README**: https://depo-platform-documentation.scrollhelp.site/infrastructure/Sidekiq-jobs.937558053.html
* **User Guide**: https://depo-platform-documentation.scrollhelp.site/infrastructure/Sidekiq-jobs.937558053.html

### Testing

* **Usability test**: N/A, auth on existing tool
* **Manual QA**: N/A
* **Automated tests**: N/A

### Measurement

* **Success metrics**: This initiative is for adding GitHub Authentication to Sidekiq, and is an auth change to an internal (both VSP and VFS) tool. There was no testing and success is determined by successfully enabling it.
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26987

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by mchelen-gov** [comment]
does this replace https://github.com/department-of-veterans-affairs/va.gov-team/issues/18328 ?
