### ISSUE TITLE
KPI Dashboards: Standardize KPI Dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#22360]
## Problem Statement 
Right now, Platform Analytics is taking a long time to deliver KPI dashboards. VFS teams don’t receive requested dashboards fast enough. Platform Analytics is overwhelmed with delivering both dashboarding & initiatives.

How might we scale analytics value for current customer needs?

## Hypothesis or Bet
If we develop our data and dashboarding infrastructure, then we expect to be able to deliver standardized KPI dashboards more quickly, alleviating internal team pain and making KPI dashboards easier to use and read.

## We will know we're done when... ("Definition of Done")
- [ ] Platform Analytics has a front end "template" for standard KPI dashboards, and 
- [ ] Platform Analytics has standardized datasets for 75% of the metrics in the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf). 

This should include the following "VA.gov product types:"
  - [ ] Forms
  - [ ] Search
  - [ ] Content

This should also include the KPI Framework themes:
  - [ ] Findability
  - [ ] Ease of Use
  - [ ] Service Completion
  - [ ] Trust

## Known Blockers/Dependencies 
_Risks_
- Inability to standardize more complex data
- BI Tooling limitations
- Lack of time 
- Increased customer support

## Projected Launch Date
Mid- to end-of June

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: KPI Dashboards
* **[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/kpi-dashboard/kpi-dashboard-product-outline.md)e**
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **[Success metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/kpi-dashboard/kpi-dashboard-product-outline.md#kpis)**
* **[Release plan](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22361)**

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by rroueche** [comment]
@joanneesteban this write up looks awesome - thank you for sharing!

Chris J and I were discussing this effort and we'd like to also include in the goals for this work (along the same lines as what you wrote in the Definition of Done around having the datasets align with the KPI Framework Themes) is: 
thing we'd like to vet the solution design against is OCTO-DE's high level metrics to gauge whether the standardization we do will help roll metrics up into that also in the longer run.

**Comment by joanneesteban** [comment]
## Forms Dashboard Launch Checklist

### Is this service / tool / feature...

### ... tested?

- [ ] [Usability test](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24202) (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] [End-to-end](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24200) [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
~- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD~


### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide) 
  - How to use this dashboard & Data Dictionary to move to Platform Website
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586724953/KPI+Dashboard+Product+Outline+-+WIP) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide]() exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    ~- [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)~
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
    * Data is pulling, instrumentation for automated reporting is being implemented
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22361).

**Comment by joanneesteban** [comment]
## Content Dashboard Launch Checklist

### Is this service / tool / feature...

### ... tested?

- [x] [Usability test](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25871) (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] [End-to-end](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25869) [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
~- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD~


### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide) 
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586724953/KPI+Dashboard+Product+Outline+-+WIP) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/KPI-Dashboards-Readme.1657995529.html) exists for this product/feature tool
    ~- [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`~
- [x] External-facing: a [User Guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    ~- [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it~
    ~- [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)~ _Already located on the Platform Website_
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)
  - [ ] Announced in Team of Teams
  - [x] Prepped for Platform Newsletter - may need to skip

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
    * Data is pulling, instrumentation for automated reporting is being implemented
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22361).

---

### Specific to Content
- [ ] Data Dictionary located in Platform Website
- [ ] Data Dictionary linked to How to
- [ ] Data Dictionary linked to Readme
- [ ] Dashboard shared with `Default` group

**Comment by joanneesteban** [comment]
## Search Dashboard Launch Checklist

### Is this service / tool / feature...

### ... tested?

- [x] [Usability test](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25870) (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] [End-to-end](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25867) [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
~- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD~


### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide) 
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586724953/KPI+Dashboard+Product+Outline+-+WIP) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/KPI-Dashboards-Readme.1657995529.html) exists for this product/feature tool
    ~- [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`~
- [x] External-facing: a [User Guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    ~- [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it~
    ~- [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)~ _Already located on the Platform Website_
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)
  - [ ] Announced in Team of Teams
  - [x] Prepped for Platform Newsletter - may need to skip

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
    * Data is pulling, instrumentation for automated reporting is being implemented
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22361).

---

### Specific to Search
- [ ] Data Dictionary located in Platform Website
- [ ] Data Dictionary linked to How to
- [ ] Data Dictionary linked to Readme
- [ ] Dashboard shared with `Default` group

**Comment by joanneesteban** [comment]
Impact review was held on 9/10/21. Closing this initiative.
