### ISSUE TITLE
Application Build Pipeline (CI) — Iterate on frontend app builds to improve developer experience

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#22364]
## Problem Statement 
The frontend application build pipeline is slow, and is not optimized for a scalable, positive developer experience. FE Tools has separate initiatives to improve particular parts of the process including unit tests (#16716) and CI tooling (#22340), and has long term plans to significantly iterate on frontend app architecture to increase autonomy (#22335). 

How might we improve the current frontend build pipeline process to keep up with VA.gov scaling while we finalize and implement a solution to increase autonomy? 

## Hypothesis or Bet
If we address a few of the major developer pain points regarding the build pipeline, then developers will have more trust in the Platform.
If we address a few of the major developer pain points regarding the build pipeline, then VFS teams will be able to develop more iteratively.

## We will know we're done when... ("Definition of Done")
- [x] Complete memory profile of application build and at least 1 iteration to improve memory use as needed
- [X] Make 3 additional improvements to developer experience
   - [ ] ~Improve staging release behavior~
   - [X] #25379
   - [X] #25512
   - [X] #25793
   - [X] #25461

## Known Blockers/Dependencies 
* Some pipeline work involves coordination with/support from Ops 
* Some pipeline work involves coordination with Testing Tools team

## Projected Launch Date
* Q3 2021

### ... tested?

- [ ] N/A — changes implemented as part of this initiative were not significant enough to warrant formal usability testing ~Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.~
    - [ ] N/A ... ~and issues discovered in usability testing have been addressed.~
- [X] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching

### ... documented?

- [X] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [X] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/VI/pages/919797773/Continuous+Integration+CI+-+Product+Outline)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] ~This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).~

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: [Application Build Pipeline product outline](https://vfs.atlassian.net/wiki/spaces/VI/pages/919797773/Continuous+Integration+CI+-+Product+Outline)
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: 
   * VFS sentiment 
   * Frontend app build times
   * Frontend app build memory usage
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by meganhkelley** [comment]
Could consider revisiting Webpack upgrade as part of this? (Could upgrade loaders, etc, even without upgrading Webpack)
