### ISSUE TITLE
Prep src/site/assets for content separation

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#22362]
## Problem Statement
We need to trace when and how `src/site/assets` works and find out if we can eliminate this path from the content repo

---
## Tasks
- [x] Trace origins and affiliations 
- [ ] Differentiate between Drupal assets and Application assets
- [ ] Remove the path from the content repo

## Acceptance Criteria
- [x] Content build should still work after `src/site/assets` has been removed

**Comment by jhonnyoddball** [comment]
## Files necessary from the `assets` folder to complete the content build

### Step 13 of 29 start: Add app assets

in `src/site/stages/build/options.js` we can see

```
    appAssets: {
      source: '../../assets',
      destination: './',
    },
```

### Step 20 of 29 start: Apply layouts

It's expecting `src/site/assets/js/record-event.js`

#### `src/site/includes/header.html`
Uses:

- src/site/assets/js/record-event.js
- src/site/assets/js/incompatible-browser.js

#### `src/site/includes/footer.html`
Uses:

- src/site/assets/js/static-page-widgets.js

#### `src/site/components/navigation-sidebar-trigger.html`
Uses:

- src/site/assets/img/bars.svg

#### `src/site/includes/google-analytics.liquid`
Uses:

- src/site/assets/js/google-analytics/vagovdev.js
- src/site/assets/js/google-analytics/vagovstaging.js
- src/site/assets/js/google-analytics/vagovprod.js
- src/site/assets/js/google-analytics/medallia-events.js

#### `src/site/includes/survey-tools.html` 
This is not required to finish the content build locally but it is on `vagovprod` and `vagovstaging`
Uses:

- src/site/assets/js/foresee/vagovprod.js
- src/site/assets/js/foresee/vagovstaging.js

**Comment by jhonnyoddball** [comment]
## Webpack on `vets-website`

[This function](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/webpack.config.js#L291-L301) uses `js` files inside `src/site/assets/js`. Optionally generated landing pages in the absence of a content build.

[This function ](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/webpack.config.js#L395-L405) copies all images from `src/site/assets/img` for the header and other content.

**Comment by jhonnyoddball** [comment]
Running ESLint in content repo I have found the following errors

![Screen Shot 2021-04-06 at 10 50 22 AM](https://user-images.githubusercontent.com/55560129/113744537-cc4f9c00-96d2-11eb-9c28-dc984ebe5a26.png)

![Screen Shot 2021-04-06 at 12 20 49 PM](https://user-images.githubusercontent.com/55560129/113744562-d1ace680-96d2-11eb-9508-dc4b57a7dbfa.png)

**Comment by jhonnyoddball** [comment]
After creating [PR](https://github.com/department-of-veterans-affairs/content-build/pull/76) to remove assets. The build is expecting `robots.txt`

![Screen Shot 2021-04-06 at 1 03 35 PM](https://user-images.githubusercontent.com/55560129/113753717-6cf68980-96dc-11eb-9fb8-780e332b8b06.png)

**Comment by jhonnyoddball** [comment]
### Files required to stay on content build:

- src/site/assets/js/google-analytics

**Comment by jhonnyoddball** [comment]
### Files required to stay in `vets-vebsite`

The following files must stay in `vets-vebsite` since they are required or used on some sort of process in the build:

- `src/site/assets/fonts`
- `src/site/assets/img`
- `src/site/assets/js/vendor`
- `src/site/constants`
- `src/site/layouts/tests/vamc/fixtures/health_care_region_page.json`
  - used in Webpack
- `src/site/README.md`

![Screen Shot 2021-04-22 at 1 38 51 PM](https://user-images.githubusercontent.com/55560129/115761333-3cffe500-a370-11eb-8f2b-a08548aefca7.png)

**Comment by jhonnyoddball** [comment]
All preparation work in `content-build` is done.
The work to be done in `vets-website` was added to the launch checklist
