### ISSUE TITLE
KPI Dashboard Standardization: Release Plan

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#22361]
## Guidance

_This Release Plan Template is intended to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: Duration of initiative (starting in April 2021) 
- Desired number of users: 3 VFS teams per iteration
- The group(s) from which you'll recruit test users: VFS, including product owners
- How you'll recruit test users: through the backlogged KPI dashboards
- How you'll give test users access to the product: temporary access via Domo
- What "Success" criteria will you look at before launch? 
  - Increase our velocity. 
    Decrease the average time from dashboard kickoff to production by at least 1 sprint.
  - Consistent customer satisfaction
    Keep customer satisfaction with Platform Analytics at a consistent level.
  - Sustain Platform team health
    Keep workloads at a healthy level so that we can deliver better quality products.
  - Increase KPI dashboard MAU
    Ensure teams are using the KPI dashboards by tracking monthly logins and Team of Teams shares. Goal: at least one monthly log in and Team of Teams share per dashboard.

- How you'll measure your "Success" criteria? 
  - Github, Domo, and internal and external surveys

### Results:

- Number of users: x 	

- Results per your "Success" criteria:

- Number of bugs identified / fixed: x/x

- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no

  - If yes, what: lorem ipsum  

### Planning:

- Desired launch date: June 30
- Post-launch KPI 1:
- Post-launch KPI 2:
- Post-launch KPI 3: 

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by rroueche** [comment]
@joanneesteban Phase I looks great!

**Comment by joanneesteban** [comment]
Remaining milestones & release plans linked [here](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587642603/Release%2Bplan%2B-%2Bstandardized%2Bkpi%2Bdashboards%2Bv1%2B-%2BJune%2BJuly%2B2021).

**Guide to release:**
- [ ] Announce in Platform newsletter
- [ ] Teaser announcements in Slack
  - [ ] How to use this dashboard snippets
  - [ ] User story snippets
For each KPI dashboard
- [ ] Team of Teams announcement
- [ ] Add default group in Domo
- [ ] Share in Slack
