### ISSUE TITLE
Migrate Pact CI Hosting to GitHub Actions

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22374]
## Issue Description
As a platform stakeholder, I need to see the results of the execution of Pact tests as part of the CI pipeline in the new GHA-hosted pipelines for both `vets-website` and `vets-api`.

---
## Tasks
- [ ] Leverage existing CircleCI configuration to re-create a similar configuration in GitHub Actions.
- [ ] Verify configuration in GHA is functioning as intended.
- [ ] Migrate `vets-website` contract execution to GHA.
- [ ] Migrate `vets-api` contract execution to GHA.
  * Work with Ops to create a service account for use with `vets-api`
  * Work with Ops to store Pact secrets in AWS Parameter Store
- [ ] Refactor existing Pact scripts to integrate with GHA.

## Acceptance Criteria
- [ ] GitHub Actions executes the Pact tests in both `vets-website` and `vets-api`
- [ ] GitHub Actions reports the results of the Pact test execution to the Pact Broker
- [ ] GitHub Actions reports the status of the Pact tests to the CI Pipeline as part of the pass/fail for the build

**Comment by ddzz** [comment]
Working branch: https://github.com/department-of-veterans-affairs/vets-website/compare/pact-github-actions

**Comment by ddzz** [comment]
A PR has been opened for migrating `vets-website` to GHA: https://github.com/department-of-veterans-affairs/vets-website/pull/16809

This PR will be merged into Eugene's main branch for migrating `vets-website` to GHA. Currently this PR is a draft because one step in the Pact flow triggers a build in `vets-api`, and Pact steps in `vets-api` have not been migrated to GHA yet. A separate PR will be opened in `vets-api` to address this.

**Comment by jhouse-solvd** [comment]
Added a [ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/23594) for the Ops portion of this work that is a current blocker

**Comment by ddzz** [comment]
PR to migrate `vets-api` Pact builds: https://github.com/department-of-veterans-affairs/vets-api/pull/6691

**Comment by ddzz** [comment]
The `vets-website` PR has been merged into the `pact-github-actions` branch.

**Comment by pjhill** [comment]
Pact is now incorporated into GHA and FE Tools has been notified that this work is completed.
