### ISSUE TITLE
QA Dashboard: MVP - Accessibility Testing Dashboard

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22388]
## Issue Description
Given the information uncovered as part of the research into [relevant metrics](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/22334) on the platform, develop a scheme for collecting and displaying information from the relevant sources (TestRail, Cypress, Nightwatch sitemap test, other sources???).

---
## Tasks
- [x] Manually collect baseline metrics for the MVP.
- [x] Devise a method for automatically collecting metrics going forward.
- [x] Feed data into the dashboard reporting mechanism.
- [x] Create a graphical method for displaying the data from metrics.
- [x] User test the resultant UI.

## Acceptance Criteria
- [x] Metrics are displayed in easy to understand graphics
- [x] Graphics align with the overall design of the dashboard
- [x] Metrics are updated regularly via an automated mechanism

**Comment by pjhill** [comment]
MVP is complete!
