### ISSUE TITLE
QA Dashboard: MVP - Manual Functional Testing Dashboard

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22386]
## Issue Description
Given the information uncovered as part of the research into [relevant metrics](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/22334) on the platform, develop a scheme for collecting and displaying information from TestRail.

---
## Tasks
- [x] Manually collect baseline metrics for the MVP.
- [x] Devise a method for automatically collecting metrics going forward.
- [x] Feed data into the dashboard reporting mechanism.
- [x] Create a graphical method for displaying the data from metrics.

## Acceptance Criteria
- [x] Metrics are displayed in easy to understand graphics
- [x] Graphics align with the overall design of the dashboard
- [x] Metrics are updated regularly via an automated mechanism

**Comment by holdenhinkle** [comment]
This test is complete.

The [Testing Tools Team Dashboard Data repo](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data) has a GitHub action that runs every day at midnight. It grabs all the data from TestRail, deletes the BigQuery tables that mirror that data, creates the tables and inserts all the data. This workflow keeps the data in BigQuery in sync with the data in TestRail, once a day. Here is a sample of the logs that are created when this job runs successfully:

```
Table testrail_users deleted.
Table testrail_users created.
Inserted 38 row(s) into testrail_users.
Table testrail_projects deleted.
Table testrail_projects created.
Inserted 33 row(s) into testrail_projects.
Table testrail_plans deleted.
Table testrail_plans created.
Inserted 83 row(s) into testrail_plans.
Table testrail_runs deleted.
Table testrail_runs created.
Inserted 1000 row(s) into testrail_runs.
Inserted 445 row(s) into testrail_runs.
Table testrail_tests deleted.
Table testrail_tests created.
Inserted 1000 row(s) into testrail_tests.
Inserted 1000 row(s) into testrail_tests.
Inserted 1000 row(s) into testrail_tests.
Inserted 1000 row(s) into testrail_tests.
Inserted 1000 row(s) into testrail_tests.
Inserted 323 row(s) into testrail_tests.
Table testrail_priorities deleted.
Table testrail_statuses deleted.
Table testrail_priorities created.
Table testrail_statuses created.
Inserted 4 row(s) into testrail_priorities.
Inserted 5 row(s) into testrail_statuses.
Error: 'API Rate Limit Exceeded'
Waiting 19 seconds...
Error: 'API Rate Limit Exceeded'
Waiting 19 seconds...
Error: 'API Rate Limit Exceeded'
Waiting 19 seconds...
Error: 'API Rate Limit Exceeded'
Waiting 19 seconds...
Error: 'API Rate Limit Exceeded'
Waiting 19 seconds...
Error: 'API Rate Limit Exceeded'
Waiting 19 seconds...
Error: 'API Rate Limit Exceeded'
Waiting 19 seconds...
Table testrail_configs deleted.
Table testrail_configs created.
Table testrail_sections deleted.
Inserted 31 row(s) into testrail_configs.
Table testrail_suites deleted.
Table testrail_sections created.
Table testrail_milestones deleted.
Table testrail_suites created.
Inserted 186 row(s) into testrail_sections.
Table testrail_milestones created.
Inserted 33 row(s) into testrail_suites.
Inserted 433 row(s) into testrail_milestones.
Table testrail_cases deleted.
Table testrail_cases created.
Inserted 1000 row(s) into testrail_cases.
Inserted 521 row(s) into testrail_cases.
Inserted 1 row(s) into testrail_metrics.
Error: 'API Rate Limit Exceeded'
Waiting 35 seconds...
Table testrail_results deleted.
Table testrail_results created.
Inserted 1000 row(s) into testrail_results.
Inserted 1000 row(s) into testrail_results.
Inserted 1000 row(s) into testrail_results.
Inserted 652 row(s) into testrail_results.
```

Additionally, the following metrics are computed and are inserted into the `testrail_metrics` table:

```
{
  totalUsers: 23,
  totalVfsTeams: 22,
  totalActiveVfsTeams: 10,
  percentActiveVfsTeams: 45.45454545454545,
  totalActiveVfsUsers: 5,
  percentActiveVfsUsers: 21.73913043478261
}
```

Here's a screenshot of the dashboard in its current form:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/47013435-04ac-4191-a7c1-97df73b9c630)

To-do (the following should be completed by the end of today):
- Remove unused cards and data connections from DOMO (cleanup)
- Fix how the 'total teams' metrics are computed
- Update the 'years' table to included data up to the year 2035. Rename the table `week_numbers_by_year` or something like that
- Fix a bug that causing some defects to not be included in the 'Test Cases with Discovered Defects, All Time' query

**Comment by holdenhinkle** [comment]
This ticket is complete.

**Comment by pjhill** [comment]
Done and demoed -- excellent!
