### ISSUE TITLE
QA Dashboard: MVP - E2E Testing Dashboard

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22387]
## Issue Description
Given the information uncovered as part of the research into [relevant metrics](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/22332) on the platform, develop a scheme for collecting and displaying information from the Cypress when it is executed as part of the CI pipeline.

---
## Tasks
- [x] Manually collect baseline metrics for the MVP.
- [x] Devise a method for automatically collecting metrics going forward.
- [x] Feed data into the dashboard reporting mechanism.
- [x] Create a graphical method for displaying the data from metrics.
- [x] User test the resultant UI.

## Acceptance Criteria
- [x] Metrics are displayed in easy to understand graphics
- [x] Graphics align with the overall design of the dashboard
- [ ] Metrics are updated regularly via an automated mechanism

**Comment by pjhill** [comment]
Challenges from the move to GHA and parallelization efforts there:
1. Aggregate E2E results from multiple runners
2. Incorporate the MARGE reports into the GHA checks somehow???
3. Holden's POC for this effort still re-usable???

**Comment by pjhill** [comment]
MVP Complete -- https://va-gov.domo.com/page/1232474697
