### ISSUE TITLE
Cheetah-Update facility phone number to covid scheduling line

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22394]
## Description
Some facilities have specific phone numbers set up for COVID-19 vaccine scheduling instead of routing Veterans through their main facility line.

Facility Locator ticket #23095

---
## Tasks
- [ ] Contact Facility - none online

- [ ] Contact Facility - dose received

- [ ] Confirmation

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag
- [ ] Given vaccine flow, When facility has a vaccine scheduling phone number, Then display as contact number
 - [ ] Given vaccine flow, When facility does **not** have a vaccine scheduling phone number, Then display main facility number
- [ ] Given primary or specialty flow, When facility has a vaccine scheduling phone number, Then display main facility phone number (i.e. don't show vaccine scheduling phone number when not in the vaccine flow)

## Definition of Done
- [ ] All acceptance criteria are met
