### ISSUE TITLE
Form 526 Update - Treatment Date Form Fields

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#22406]
## Issue Description
Form 526 treatment dates are now split into separate fields. 

---
## Tasks
- [x] Schema change - treatment start date no longer required (option to select "do not have date radio button"). Treatment end date will no longer be used.

## Acceptance Criteria
- [x] Treatment end date field no longer required
- [x] Remove treatment end date field.
---

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/7326/files

**Comment by annaswims** [comment]
PR will be merge after review
