### ISSUE TITLE
Publish proposed product list and Platform Website structure (Confl migration plan)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#22418]
# User story
As a Content Team member, I need to map out what Platform Website info goes in which Conf spaces, so that Platform teams have a "map" they can follow.

As a Platform Team member, I need to know in which Conf spaces to put my team's documentation, so that I can populate the Platform Website following the Content Team's guidance.

# Tasks
- [ ] Pre-req: Product list from product workshop https://github.com/department-of-veterans-affairs/va.gov-team/issues/22420 
- [ ] Visualize what content goes where, and why - artifact: diagram.
- [ ] Think through implementation with Conf. technical feasibility.
- [ ] Set up a high-level prototype of Conf. structure + Scroll Viewport configuration.
  - Call out risks of Scroll Viewport Data Center limitations

# Acceptance criteria
* Content Team secures OCTO-DE and Platform Teams' understanding of info goes where.

# Reference info
- Might need the artifact from: Validate list of Platform products (Develop IA) https://github.com/department-of-veterans-affairs/va.gov-team/issues/22420

**Comment by lianilychee** [comment]
Closing - we no longer need this ticket given https://dsva.slack.com/archives/CL181NRJQ/p1617399401063100
