### ISSUE TITLE
Conduct pair-writing sessions (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#22410]
# User story
- As the Newsletter editor, 
- I want to quickly extract submissions' value props and reduce jargon,
- so that I can produce the Newsletter quickly and with minimal back-and-forth with SMEs.

# Tasks
- [ ] Refine questions list.
- [ ] Talk to Service Design about getting a technical backup.

also,

- [x] Get submitters' names.
- [x] Schedule with submitters.
- [ ] Copywrite/edit.

# Acceptance criteria
- We spend less than 1.25-hrs per submission (45-min pair writing, 30-min Slack back-and-forth).

# Reference info
- [Pair writing sessions script](https://docs.google.com/document/d/1YrMxo1MJSdcuRQJ9ZK5TtdoFENT2Vu7BPzIfDUv3-yU/edit)

**Comment by lianilychee** [comment]
On hold till Platform teams submit content.  Deadline for content submission is EOD Weds 4/7.

**Comment by lianilychee** [comment]
Thurs 4/9:
- will sked with submitters!

**Comment by lianilychee** [comment]
Mon 4/12:
- they're scheduled!  tmr (Tu), W, and Th

**Comment by andreahewitt-odd** [comment]
Newletter no longer exists -- closing
