### ISSUE TITLE
Consolidate Platform products list (Develop IA)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#22419]
# User story
As a Content team member, I want to consolidate the various product lists we've encountered*, so that we can present a comprehensive experience to OCTO-DE.

*Product lists included in the last section.

# Tasks
- [x] Secure buy-in from Rachael Roueche
- [ ] Schedle and secure buy-in from Andrea Hewitt
- ~Schedule and secure buy-in from PMs~ no longer needed, as outlined in [this slack msg](https://dsva.slack.com/archives/CL181NRJQ/p1617399401063100)
- [ ] When this ticket is said and done, continue on to https://github.com/department-of-veterans-affairs/va.gov-team/issues/22420

# Acceptance criteria
- We have an artifact (document or visual) that lists the Platform's products.

# Reference info
- Continuation of https://github.com/department-of-veterans-affairs/va.gov-team/issues/21666
- [VSP Products Q1 2021 (PMs assessment, Google xls)](https://docs.google.com/spreadsheets/d/1VN73fnx-nQToTMhpLKbQJYIHvxKdmfvFozcBUVvcJks/edit#gid=0)
- [Product documentation for the DEPO Platform (based on a summer 2020 card sort)](https://docs.google.com/document/d/1gvypxz20PvluHfkzOOxjALvd11pU59k6U_RR38SifCs/edit?pli=1#heading=h.l7hawnmljx6m)

**Comment by lianilychee** [comment]
Closing - we no longer need this ticket given https://dsva.slack.com/archives/CL181NRJQ/p1617399401063100

Platform Teams **DO** still need to discuss/finalize the list of Platform products. But since the product list meeting is not specifically a documentation problem and not a blocker for the Platform Website, Liani will touch base with Andrea and Naomi to facilitate.
