### ISSUE TITLE
Remove Extra Hyphen (CH36/31 GA Events)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22421]
## Goal
Clean up the event names for standard event names per GA Insights Team.

## Considerations
Currently the event names look like this, with an extra hyphen:
![image](https://user-images.githubusercontent.com/48527022/110994088-42681980-8346-11eb-8b0c-b3f6d3380bca.png)

Each full event name should look like this, with only two hyphens: 
- `careers-employment-28-1900--submission`
- `careers-employment-28-1900--submission-failed`
- `careers-employment-28-1900--submission-successful`

_Obviously the form name and number should correspond to the feature, here the CH31-1900 form is used as an example._

## Tasks
- [x] Remove the hyphen from these GA event names for the [CH36](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13167#issuecomment-759417808) and [CH31](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15757#issuecomment-797732568) features

## Acceptance Criteria
- [x] The hyphens have been removed
- [x] A PR Has been requested for merging
- [ ] Jon Wehausen has been notified that this can be validated after the PR has been merged

**Comment by jonwehausen** [comment]
Hi @jason-gcio 

Could you provide an update on this work? Thanks so much

**Comment by jason-gcio** [comment]
Hey @jonwehausen! Apologies, it's still in our backlog.  I did speak to Jesse about this though so I will get it moved to the right for next pick up.  Thanks for being patient with me.

**Comment by jason-gcio** [comment]
@jonwehausen - this has been merged, want to do a quick check and make sure its looking good on your end?

**Comment by jason-gcio** [comment]
cc: @cohnjesse (for awareness)

**Comment by jonwehausen** [comment]
Thanks @jason-gcio ! Will perform validation on this now

**Comment by jonwehausen** [comment]
This is good to close! Thank you @jason-gcio & @cohnjesse
