### ISSUE TITLE
Update list loop component to render add item by default on review page

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#22435]
## Issue Description
For the list loop component on the review page when a user updates the yes/no question from no -> yes it should display the add item by default

---
## Tasks
- [ ] update list loop to show add item by default
- [ ] verify correct item titles

## Acceptance Criteria
- [ ] list loop should show add item by default on the review page
- [ ] item titles should render correctly
---
