### ISSUE TITLE
Update Keep in touch copy for disability rating page

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#22434]
## Issue Description
The below page needs updating at the bottom where it says: Keep in touch. 
https://www.va.gov/disability/about-disability-ratings/after-you-get-a-rating/

![Screen Shot 2021-03-31 at 11.13.38 AM.png](https://images.zenhubusercontent.com/5d5ab731409ffe1c4506543b/8d3fdcc6-51e1-4f3d-8403-17fdceb311d1)

Rewrite that text and point the user to these pages (and see if there are any other opportunities--other info that would be helpful):
https://www.va.gov/resources/change-your-address-on-file-with-va/
https://www.va.gov/resources/how-to-change-your-legal-name-on-file-with-va/

## Tasks
- [ ] Update text (Selina)
- [ ] Review changes (Beth)
- [ ] Copy edit changes and publish (Randi)

## Acceptance Criteria
- [ ] Content updated on live site

**Comment by RLHecht** [comment]
Closing this ticket. This work is being finished in #23161
