### ISSUE TITLE
MCP- BE Integration Set up 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#22440]
As a Veteran logging into expanded Debt Portal I want to see my Medical copay debt displayed 

- [ ] Determine Integration method with BE data (Dynamo db?) Will this be integrated through vets API or another integration point

- [ ] If not Vets API, determine what security implications there are and determine what Ops requires (SSL certs, ports etc) 

- [ ] Determine all per-prod environments and test data sets

**Comment by denisecoveyduc** [comment]
As part of the security review for Medical Copays it was determined that TLS implementation would follow 6-8 weeks after launch.
**Launch of the Medical Copay - VODA Lite went live on production on January 13, 2022**
Epic #36047 captures all associated work
