### ISSUE TITLE
Launch checklist for content build separation 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#22451]
Things we need to do for a content build separation release to prod

# Launch Checklist

## Blockers

- [x] [Review Instances are working](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/22158)
- [x] [Pakagist webhook is set up](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/23093)
- [x] Confirm content-build and vets-website match with diff script
- [x] Add asset movement into webpack

## Pre-launch

**Repo: devops**

- [x] [Create production content deploy](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/22579) (FE Tools)
- [x] Make sure content auto-deploy works (same as above, but on a schedule) - pre launch
- [x] Get reverting PRs ready to merge just in case
- [x] Update [preview server](http://preview-prod.vfs.va.gov/preview?nodeId=15068) deployments ([auto](http://jenkins.vfs.va.gov/job/deploys/job/content-preview-auto-deploy/), [deploy](http://jenkins.vfs.va.gov/job/deploys/job/content-preview-prod/))

**Repo: vets-website**

- [x] Get reverting PRs ready to merge just in case

**Repo: content-build**

- [x] Add Cypress to content-build repo
- [x] Make sure all teams have access to content-build repo

## Launch Day

**Repo: devops**

- [x] Update content-only deployment schedule and comment out old auto-deploy and rerun seed job ([PR to merge](https://github.com/department-of-veterans-affairs/devops/pull/9098))
- [x] Update revproxy for [prod](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/11917) and [staging](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/11916) for launch (Ops) [#23717](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/23717)
- [x] Update slack alerts in content-build ([devops](https://github.com/department-of-veterans-affairs/devops/pull/9062))

**Repo: vets-website**

- [x] Update vets-website references to src/applications/registry.json to point to content-build
- [x] Remove 4 failing tests from vets-website and confirm they exist in content-build
- [x] Update code owners in vets-website so src/site goes to FE Tools [merge PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17026)
- [x] Merge [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16757) to enable `content-build` on review instances

**Repo: content-build**

- [x] Run a last sync on `src/applications/registry.json` file from `vets-website`
- [x] Update slack alerts in content-build ([content-build](https://github.com/department-of-veterans-affairs/content-build/pull/90))

## Immediately Post-launch

**Repo: vets-webiste**

- [x] Confirm review instances are working [#22158](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/22158)

**Repo: content-build**

- [x] [Update code owners for content-build](https://github.com/department-of-veterans-affairs/content-build/pull/87)
- [x] Set content-build repo protections (tests must pass, protect master)
- [x] Confirm review instances are working (Both) [#22158](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/22158)

**General**
 
- [x] Merge updated deployment documentation [PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/614)
 - [x] [Notify teams of change](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/11913)
- [x] Continue vets-website sync post-launch (but in reverse)
- [x] fix file manifest

## 1 Week Post Launch

- [x] Remove vets-website/jenkinsfile.integration & jenkinsfile.content
- [x] Remove `ansible/Jenkinsfiles/deploys/content-only-deploy` (vets-website auto deploy)
- [x] Remove RI script conditionals in vets-website
- [x] [Remove and back up content-related files in vets-website](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/11918) ([Instructions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22362#issuecomment-825056393)) [metalsmith ticket](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/11918)
- [x] Remove black vagovdev/staging banner
- [ ] Close out tickets in the epic

## TBD Post-release

- [ ] [Update production app deploy as part of launch](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/22578)

**Comment by timwright12** [comment]
Documentation for teamsites updates: https://docs.google.com/spreadsheets/d/1NVUm8EV3ojeXKiRuxSplQ8eH2r-vwtsDJ8QcmOFN9P0/edit#gid=0

**Comment by timwright12** [comment]
**Tentative launch information**

**Date**: May 5
**Window**: 4:30pm - 6pm ET 
**Dependancies**: successful deployments

Requesting Ops and FE Tools team members be on hand

**Comment by timwright12** [comment]
Launch day order of operations:

1. [Merge devops PR](https://github.com/department-of-veterans-affairs/devops/pull/9094)
2. [Merge vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17026)
4. [Merge RI PR in vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/16757)
4. Rerun seed job (and cancel 5pm content-only autodeploy)
5. Set up PRs in vets-website and content-build to test review instances
6. deploy: vets-website
7. deploy: content-build
8. deploy: content-only content-build

**Comment by indytechcook** [comment]
@timwright12 Please add an item for the CMS deploy as this will be the start of the manual content build downtime for editors.

**Comment by ElijahLynn** [comment]
> @timwright12 Please add an item for the CMS deploy as this will be the start of the manual content build downtime for editors.

Crosslinking the PR that we just merged for the CMS deploy > https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5199/

**Comment by timwright12** [comment]
PR to remove black banner as post-release item: https://github.com/department-of-veterans-affairs/content-build/pull/140

**Comment by theodur** [comment]
PR for removing `vets-website/jenkinsfile.integration` & `jenkinsfile.content` along with Drupal & content build from Jenkins has been merged: https://github.com/department-of-veterans-affairs/vets-website/pull/17148

**Comment by theodur** [comment]
PR for removing Metalsmith pipeline has been merged: https://github.com/department-of-veterans-affairs/vets-website/pull/17189

**Comment by theodur** [comment]
PR for RI script conditionals has been merged: https://github.com/department-of-veterans-affairs/vets-website/pull/17220

**Comment by timwright12** [comment]
Closing this as we've been launched for a couple weeks now
