### ISSUE TITLE
Authenticated Experience: Sprint 45 (4/7 - 4/20)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22464]
## Priorities

1. Continue with direct deposit for edu launch
2. Finish My VA design (if not done already) and My VA build
3. Continue work on preferred facility and communications preferences
4. Profile tickets

## Profile

**PM**
- [ ] Design and documentation familiarization #22575

**Design**
- [ ] Create confirmation email for when contact information is updated on VA.gov #8383

From Previous Sprint:
- [x] Add FAQ around what departments get updated when a veteran updates their contact info #20221 

**FE**
- [ ] 508-defect-2 [COGNITION]: H1 should match or be included in the page title #19552 
- [ ] Implement change to phone number formatting (US-supported only) #22533

**BE**
From Previous Sprint
- [ ]  VA Profile: Rename references to vet360 in devops #18259

## My VA redesign

**PM**
- [ ] Assist Tressa with contact center guide #22594
- [x] Submit analytics request (VSP collab cycle) #22556
- [x] Design and documentation familiarization #22574
- [x] Thorough review of FE build #22557
- [x] IA Request [My VA redesign] #14642

**Design**
- [ ] Start Contact Center guide #22594
- [x] Thorough review of FE build #22557
- [x] Design error state for when user is not in MVI/MPI #22656
- [x] Add a few more My VA test cases #22928

**FE**
- [x] Implement functionality/prompt for LOA1 users #22644
- [x] Implement "Go to your profile" link #22570
- [x] Error state implementation 
    - [x] Implement error states for claims & appeals #22564
    - [x] Implement handling of long load times for claims & appeals #22565
    - [x] Investigate if there are situations when we won't be able to tell if user has the claims or appeals services #22568

Review of frontend build #22557  resulted in the following minor issues:
- [x] My VA Name tag disability rating can wrap poorly #22899 
- [x] My VA name tag needs x-padding #22898 
- [x] My VA content lacks proper x-margin/padding at 1008px breakpoint #22896 
- [x] Refine My VA name tag line leading? #22895 
- [x] Benefit Of Interest headline wraps poorly #22893 
- [x] My VA shows "undefined" message count when loading secure messages #22964 
- [x] Incorrect message text when unread messages exist #22991 
- [ ] Appointments are not displaying for user when they have one within the next 30 days #23063 
- [ ] "You have no appointments scheduled in the next 30 days" message missing #23064 
- [x] "View your VA medical records" should go straight to MHV #23134 
- [x] Update copy for Health care link under "Benefits you might be interested in" #23135 
- [ ] Clicking "Manage all claims and appeals" link re-routes back to My VA #23015 
- [x] "What benefits does VA offer?" menu in wrong location #22996 
- [x] Incorrect section header for "Apply for VA benefits" #22998 
- [ ] "Learn how to file a claim for disability" links to wrong page #23072 
- [x] "Learn how to apply for education benefits" links to wrong page #23073 
- [x] "What benefits does the VA offer?" links all have weird numerical slug #23132 
- [x] "Health care" block is showing in "Benefits you might be interested in" section after an application has been started #23128 
- [x] For LOA1 user, "Benefits you might be interested in" won't load #23125 
- [x] Cerner alert should be 2/3 width on desktop #23133 
- [x] "View disability rating" link showing to user who doesn't have a disability rating #22957 

From Previous Sprint
- [ ] Add error state for appointments #21846 
- [x] Apply for VA Benefits visual updates #21837
- [x] Claims and Appeals visual updates #21838 

## Direct deposit for EDU

**PM**
- [x] Monitor launch to 25% #22586
- [x] Monitor launch to 50% #22587
- [x] Let content team know anticipated 100% date so that they can publish the updated content page. #20096

**Design**
- [x] Add pngs or jpegs of design files to Github #22665

**FE**
- [x] Launch to 25% of users #22586
- [x] Launch to 50% of users #22587
- [x] Investigate why errors are not showing up in GA dashboard #22629

## Preferred medical facility

**PM**
- [x] Any necessary coordination with VAOS
- [x] Submit for IA review with VSP #22558

**Design**
- [x] Design error and success message states #22591
- [x] Assist with IA review #22558
- [x] Create design documentation for FE #22753
- [x] Content review 
     - [x] Content needed for profile facilities flow from Auth Exp #22036

From Previous Sprint: 
- [x] Design Intent request submitted to VSP #22308 
     - [x] Content Feedback - Design intent - Preferred facilities #22519
     - [x] IA feedback - Design intent - Preferred facilities #22520

## Notification Preferences

**PM**
- [x] Submit IA Review with VSP Collab Cycle #22596

**Design**
- [x] Design error and success message states #22592 
- [x] Assist with IA review #22596
- [x] Create design documentation for FE #22757
- [x] Complete designs incorporating/addressing DI feedback (Reference #22309 and #21860)
     - [x] Design intent [VSA Authenticated Experience, Communication Permissions (Notification Preferences)] #22706
     - [x] IA Feedback - Design Intent - Profile: Notification Preferences #22741
     - [x] Accessibility Feedback for Design Intent: Communication Permissions (Notification Preferences) #22526 
- [x] Content review: 
     - [x] Content review request for notification settings from Authenticated Experience #22529      

From Previous Sprint:
**BE**
- [x] Notification preferences: Implementation (part 3) #19774 
- [ ] Add batch update api to communication permissions #23065

**Comment by ajakabcin** [comment]
Sprint complete
