### ISSUE TITLE
Investigate Doc Attachment Issue

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22476]
## Background
There is an issue with how documents are being attached in the 686 form on staging.  As of now, only PDFs are being submitted successfully. When a jpg or png does get attached, the form pdf doesn't appear in VBMS.

## Considerations
- Check in with the FE to see if there is anything known about this component
- Check with Jim/Jason if they have seen or heard of anything from other forms from their travels, like the 526
- Staging? Platform?
- Check in with platform and ask if anyone is having an issue with file upload
- Check 686 in prod with someone's login (Diane Madsen (sp?))

## Tasks
- [ ] Determine if 
  - [ ] there is an issue with file upload in staging
  - [ ] there are known issues with the file upload component
  - [ ] what, if anything, needs to be adjusted to allow for file uploads to complete successfully
- [ ] Document the findings and/or a solution in GH in the feature folder

## Acceptance Criteria
- [ ] A path forward for file upload has been established, and/or,
- [ ] Implement a solution, if possible

**Comment by jason-gcio** [comment]
This issue was found to not be an issue in prod
