### ISSUE TITLE
Update 674 Form Label

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22488]
## Background
When a VSR pulls up a 674 application, the label indicates that it is a 674b, which is a similar form but might cause confusion.

## Considerations
- [Original ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19089)
- [Original PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5798)

## Tasks
- [x] Update the form label for the 674 to not have a b in it.

## Acceptance Criteria
- [x] The form label has been updated
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6403
