### ISSUE TITLE
Design Forms queries in BigQuery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#22480]
## Issue Description
How might we design the queries for Forms KPIs so that we can calculate funnels and other high priority KPIs to visualize in BI tools?

---
## Tasks
- [ ] Design query for forms data
- [ ] QA event totals from the data architecture
- [ ] QA dimension & metric fields being used

## Acceptance Criteria
- [ ] Platform Analytics have standards to more quickly and consistently calculate most Forms KPIs.
_Stretch:_
- [ ] Forms KPI calculations can be decoupled from the BI Tool

**Comment by joanneesteban** [comment]
@JasonTheBearded - I'm assuming we also need some business logic in here, which means adding feedback. Let's look at the [Gantt sheet](https://app.smartsheet.com/sheets/X43VpCC9gxPC7VC3J28vgRX8vV5XFHwjX5HwjGG1?view=gantt) (I added some rows based off these GH issues, but feel free to change them based on what you need) and see if we need to reach out to VFS teams this sprint as well.

**Comment by JasonTheBearded** [comment]
[WIP query](https://console.cloud.google.com/bigquery?sq=86772881199:75a6fcf00b6548ac8d0f92cafa73edb8) for new Forms view

**Comment by JasonTheBearded** [comment]
Queries designed and implemented in BigQuery. Created separate views for funnels and engagement

**Comment by JasonTheBearded** [comment]
Query design and build complete, closing ticket.
