### ISSUE TITLE
Design prototypes for Forms KPI Dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#22489]
## Issue Description
Design a Forms KPI Dashboard prototype so that we can test a standardized KPI dashboard with VFS teams and understand how this type of data can be visualized in a standard way.

---
## Tasks
- [ ] Design Forms dashboard mockups
- [ ] Receive feedback from Analytics team
- [ ] Iterate on design
- [ ] Deliver prototype to VFS teams for testing & feedback

## Acceptance Criteria
- [ ] Platform Analytics can test a prototype for a Forms KPI Dashboard with VFS teams

**Comment by joanneesteban** [comment]
[Design Audit Deck](https://docs.google.com/presentation/d/1gapGkzCqnlCURbjz6rtH2A8JsJlzZn-D_6GFobd3cU0/edit)

**Comment by joanneesteban** [comment]
![image](https://user-images.githubusercontent.com/48964695/113879153-3c6c2980-9788-11eb-9ec9-e5e9c4d32590.png)

**Comment by joanneesteban** [comment]
[Invision preview V1 ](https://projects.invisionapp.com/share/B710P0FGUQSE#/screens/449201382/comments)after internal team comments

**Comment by joanneesteban** [comment]
Prototypes located in [Invision](https://projects.invisionapp.com/share/B710P0FGUQSE#/screens/449201382/comments). Closing this ticket.
