### ISSUE TITLE
Technical discovery for query standardization

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#22481]
## Issue Description
How might we understand which Google Analytics data needs to be pulled into calculating funnels so that we can start to query high priority KPIs?

---
## Tasks
- [ ] Review Audit to combine all the different field & datasets into standardized queries
- [ ] Group all funnel data
  - [ ] Forms
  - [ ] Search
  - [ ] Content

## Acceptance Criteria
- [ ] Platform Analytics has an outline for which interaction data should go into different VA.gov funnels

**Comment by JasonTheBearded** [comment]
Combing through audits to collect commonly used fields for datasets and designing new structures. Drafting items here, https://lucid.app/lucidchart/invitations/accept/ea2d0a8e-f749-4ec2-9ed0-3d1abe1d027f?viewport_loc=-125%2C-48%2C3072%2C1545%2C0_0

**Comment by joanneesteban** [comment]
@JasonTheBearded :( 
![image](https://user-images.githubusercontent.com/48964695/113610622-6227f000-961b-11eb-8baf-c4b476d72103.png)

**Comment by JasonTheBearded** [comment]
Updated link to lucid chart

**Comment by JasonTheBearded** [comment]
Tech discovery complete, architecture design and development in progress
