### ISSUE TITLE
Produce VNP Fields to Linda

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22486]
## Background
Our BGS partner, Linda, has asked us for a list of all the fields we submit to their VNP tables.

## Tasks
- [ ] Compile all the fields being sent to the VNP tables in the BGS service call
- [ ] Send to Linda C. at BGS

## Acceptance Criteria
- [ ] Linda has been sent the VNP table fields

**Comment by jason-gcio** [comment]
Ask Linda what format she would prefer...XML or spread sheet?

**Comment by steele-lm** [comment]
No longer needed. Closing.
