### ISSUE TITLE
[UNPLANNED] Pass Relationship Status into 674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22494]
## Background
There is a question on the 674 that asks the Veteran if the child that is being sent to school is the child, or under the guardianship, of the Veteran.  Now that the FE has implemented the question into the form, we need to address the response into the payload and PDF form.

## Considerations
The question asks: **"Are you the parent of this child?"**

Then, based on the `yes` or `no` responses, take the following actions:

If `yes`, populate question 16 with `Parent` for the payload and pdf
If `no`, set the application to MANUAL_VAGOV 

## Tasks
- [ ] Implement the relationship field per the considerations above

## Acceptance Criteria
- [ ]  The field is populated appropriately
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
RBPS may not have rules for this but was still set as a requirement to set the relationship and to MANUAL_VAGOV

**Comment by jason-gcio** [comment]
Ensure procID variances are in place before tackling this

**Comment by jason-gcio** [comment]
Consider waiting until the 674+686/proc ID matching issue is settled.

**Comment by sortizsh** [comment]
@evansmith can you take a look?

**Comment by tblackwe** [comment]
Evan and I did some digging on this ticket. It looks like `MANUAL_VAGOV` is always set for 674 forms. This can be part of the effort to improve RBPS  integration. Recommend closing this ticket as we will recreate it with more information once we have requirements.
