### ISSUE TITLE
PDF for Dependency Verification (VA Form 21-0538)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22495]
## Background
The Dependency Verification feature has a part in its process that when a Veteran selects the option that indicates there are no changes to their dependents, a VA Form 21-0538 should be generated with the available Veteran info (Section I) and the status of whether the list of dependents has changed has selected `No` (Section II) and the final page, signature and date submitted.

## Considerations
- There is no field in the VA Form 21-0538 pdf, can that be added?
- [Link to form](https://www.vba.va.gov/pubs/forms/VBA-21-0538-ARE.pdf)
- [Ch36 ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12901) in case it helps
- [CH36 submitted PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4830) in case it helps

## Tasks
- [x] Obtain the blank PDF and sample payload from the FE
- [x] Insert the payload into the the PDF
- [x] Update PDF test specs (?)

## Acceptance Criteria
- [x] A PDF has been created from form data and submitted (stretch: to TBD(?))
