### ISSUE TITLE
Finalize Designs - Search Tool Discovery 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#22498]
## Description

After design brainstorming discussion and design intent review we need to finalize the designs ahead of development efforts. 

## Tasks

- [ ]  integration fo Global Search from UI Consistency elements (#21977)
- [ ] Provide design specs for development

## Definition of Done

- [ ] Designs have been finalized and represent a clear vision of the intent for surfacing VA search tools.
