### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA New Mexico health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22506]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Wichita healthcare system Legacy Site](https://www.wichita.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-22 Playbook locations](https://drive.google.com/drive/folders/1ECC-7U1-PVJ8xlaxjAP4GvJcIq7QCaJt)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Raymond G. Murphy Department of Veterans Affairs Medical Center
- [x] Las Vegas VA Clinic
- [x] Artesia VA Clinic
- [x] Farmington VA Clinic
- [x] Silver City VA Clinic
- [x] Gallup VA Clinic
- [x] Espanola VA Clinic
- [x] Truth or Consequences VA Clinic
- [x] Alamogordo VA Clinic
- [x] Durango VA Clinic
- [x] Santa Fe VA Clinic
- [x] Northwest Metro VA Clinic
- [x] Taos VA Clinic
- [x] Raton VA Clinic

* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#22506 Create new Health Services "LIST and PLAYBOOK" for VA New Mexico health care - Completed and moved to Validate.
