### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA Northern Arizona health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22507]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Wichita healthcare system Legacy Site](https://www.wichita.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-22 Playbook locations](https://drive.google.com/drive/folders/1ECC-7U1-PVJ8xlaxjAP4GvJcIq7QCaJt)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Bob Stump Department of Veterans Affairs Medical Center
- [x] Kingman VA Clinic
- [x] Flagstaff VA Clinic
- [x] Lake Havasu City VA Clinic
- [x] Anthem VA Clinic
- [x] Cottonwood VA Clinic
- [x] Chinle VA Clinic
- [x] Holbrook VA Clinic
- [x] Page VA Clinic
- [x] Tuba City VA Clinic
- [x] Polacca VA Clinic
- [x] Kayenta VA Clinic

* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Definition of Done-Acceptance Criteria
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [ ] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#22507 Create new Health Services "LIST and PLAYBOOK" for VA Northern Arizona health care - Completed and moved to Validate.
