### ISSUE TITLE
DEPO Design Review

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#22500]
## Description

John has indicated that the designs for the results page redesign should be reviewed with DEPO focals before we proceed with a collab cycle kickoff. 

## Tasks

- [x] Update Initiative Brief with R+S Search Term Data to support - [Report Link](https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a50123418w177519031p176188361/_u.date00=20201105&_u.date01=20201215&explorer-table.secSegmentId=analytics.searchStartPage&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.searchStartPage%22,%22PT%22,%22www.va.gov~2Fresources%22,0%5D%5D/)
- [x] Prep: SD Team Bet Brainstorming Workshop to add Hypotheses and Bets **Scheduled for Wed June 3**
- [x] DEPO Design Discussion – Ryan Thurlwell, Shawna Hein, Megan Gayle, John Hashimoto, Denise Coveyduc
- [x] Integrate feedback before proceeding with collab cycle kickoff

## Definition of Done

- [x] All comments and concerns have been interpreted and integrated in the designs as appropriate.

**Comment by denisecoveyduc** [comment]
In order to include any findings from the baseline user research that is being conducted we are going to postpone the design review and move it into S47.

**Comment by denisecoveyduc** [comment]
User research is currently being conducted and it has become apparent that certain findings/insights from that research will have a direct impact on the creation of the product outline, which is needed for this design review.

As a result, we will wait for the research readout (est May 17) to finalize the product outline ahead of design review.

**Comment by denisecoveyduc** [comment]
A productive working session lead us to explore the creation of a search landing page #26011 highlights modified mockups which we will use to facilitate discussions  regarding next steps.
