### ISSUE TITLE
[INVESTIGATE] Connect Doc Type Selection to Payload/PDF (Multiple docs?)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22515]
## Background
The doc type selection needs to be wired up from the frontend to the backend for submission.

## Considerations
"'Add another upload' allows you to add another document but only one type selector is shown"

## Tasks
- [x] Determine if doc type being the same across the board is ok or not
- [x] Take the doc type selection for the applicable file attachment and pass it through so that VBMS can indicate what the file attachment is

## Acceptance Criteria
- [x] VBMS is able to see what the file attachment is even if singular
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Ask Robb Lutz how granular the doc type needs to be
