### ISSUE TITLE
Implement Doc Type Selection

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22512]
## Background
Once the doc type design has been established, it needs to be installed in the right location on the frontend.

## Considerations
This will most likely be a simple dropdown with 4-5 options:

**Document Codes for 686c/674**
Add Spouse Uploader
10 => "Unknown",
14 => "Affidavit",
61 => "Marriage Certificate / License",
119 => "VA 21-4171 Supporting Statement Regarding Marriage",
———
Add Child Uploader
10 => "Unknown",
13 => "Adoption Decree",
25 => "Birth Certificate",
58 => "Medical Treatment Record - Government Facility",
59 => "Medical Treatment Record - Non-Government Facility",
663 => "Medical Opinion",

## Tasks
- [x] Implement the component
- [x] A PR has been requested for merging 
  - [x] `vets-website`
  - [x] `vets-api`
  - [x] `vets-json-schema`

## Acceptance Criteria
- [x] Values are in place on the frontend
- [x] Numeric values are passed to BE
- [x] A PR has been requested for merging

**Comment by micahchiang** [comment]
Is this a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/22573 ?
