### ISSUE TITLE
[FE] Profile - Implement change to phone number formatting (US-supported only)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22533]
## Background
Per discussion in #13246 we've found that we need to make it more clear that we only support US phone numbers. We are removing the info box telling people we only accept US phone numbers and adding helper text and better label to the field itself.

## Tasks
Per @andaleliz 's [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13246#issuecomment-810355050), the proposed changes are as follows (screenshots below for reference and current and desired states):

- [ ] remove existing info box that explains people can only add a US phone number
- [ ] use hint text instead of the alert to clarify we only support U.S. phone numbers
- [ ]  improve specificity of field label and error to better align w/ other forms on VA.gov and reduce ambiguity
- [ ] perform these steps for all number types - home, mobile, work and fax

## Updated Copy

**Home**
**Approved field label text (including hint):** 
Home phone number (U.S. numbers only) 
(*Required)

**Approved error text:**
**Please enter a valid 10-digit U.S. phone number**

**Mobile**
**Approved field label text (including hint):** 
Mobile phone number (U.S. numbers only) 
(*Required)

**Approved error text:**
**Please enter a valid 10-digit U.S. phone number**

**Work**
**Approved field label text (including hint):** 
Work phone number (U.S. numbers only) 
(*Required)

**Approved error text:**
**Please enter a valid 10-digit U.S. phone number**

**Fax**
**Approved field label text (including hint):** 
Fax number (U.S. numbers only) 
(*Required)

**Approved error text:**
**Please enter a valid 10-digit U.S. fax number**

## Screenshots
**Current state of phone number field (edit mode)**
![image](https://user-images.githubusercontent.com/45603961/113338974-d7cc4d00-92f7-11eb-8cef-8d380bc210b1.png)

**Proposed revisions**
![proposed revised state for phone numbers](https://user-images.githubusercontent.com/45603961/113339100-fe8a8380-92f7-11eb-8f37-7bd88108094d.png)

![error state for revised phone numbers](https://user-images.githubusercontent.com/45603961/113339143-0ba77280-92f8-11eb-98d2-21ad8eb35d7c.png)

**Comment by Samara-Strauss** [comment]
Additional specs:

- Remove the existing Info box that explains people can only add a US phone number.

Also @ajakabcin and cc/ @andaleliz — when providing copy updates for frontend, please do not make them rely on screenshots. This tends to lend itself to errors given that they then have to type the copy in by hand. So copy is updated correctly, please provide the text in a ticket (or other documentation if that applies) so that all they have to do is copy and paste it in. [Here's an example of how Tressa did it for one of the My VA tickets](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21846#issuecomment-812159517). You can see she wrote out the copy in addition to the screenshot, so it's clear what needs to be updated and how it should be formatted. If you have any questions about that, let me know!

**Comment by ajakabcin** [comment]
Sorry about that! I added a section for updated copy and I'll double check with @andaleliz to make sure I translated things over properly

**Comment by Samara-Strauss** [comment]
Great, thank you!

**Comment by Samara-Strauss** [comment]
Another thing that is not clear in this ticket — is this for all phone numbers? So home, mobile, work, and fax? I assume that it is, but that's not clear from the specs or the copy, as we don't specify anywhere that this is for all phone numbers, and the copy given is only for the home phone number field.

**Comment by ajakabcin** [comment]
Good catch! I updated the task list to include updating all number types and updated copy for all types. Liz is double checking with content on that copy.

**Comment by andaleliz** [comment]
@ajakabcin Danielle replied [in Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1617371467097400) and we're good to go with copy on all the phone fields

**Comment by Samara-Strauss** [comment]
Great, thanks!

**Comment by erikphansen** [comment]
@sanlouise can you take this one?

**Comment by ajakabcin** [comment]
Confirmed on staging

**Comment by Samara-Strauss** [comment]
YAY! So happy to see this improvement go out :D
