### ISSUE TITLE
[WCAG2.1]: Explore opportunities to improve and document web performance

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#22537]
## Issue Description
WCAG2.1 has given us an opportunity to re-evaluate aspects of mobile-first design that aren't specifically called out in success criteria. One of them is web performance. This epic will hold tickets related to discovery, recommendations, and documentation of best practices for making our site as fast as it can be, for users on devices new and old.

## Tasks
- [ ] Review all tickets and close them after work is completed
- [ ] Close the epic when all issues are completed

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
