### ISSUE TITLE
Supporting Evidence Attachments for 686/674

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#22535]
## Background
Documents that are attached to the 686/674 as supporting evidence are not being uploaded properly to VBMS.  

## Tasks
- [x] Update the PDF submission job to upload supporting evidence documents to VBMS

## Acceptance Criteria
- [x] Files are being uploaded properly and can be viewed in VBMS
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6415
