### ISSUE TITLE
SPIKE - Investigate if review instances can be launched in a subnet that can be accessed from GFE (or w/out SOCKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#22545]
## Description

We want to experiment and see if there is a way to bring up a review instance (RI) in a different environment, so that people can access them via GFE, with a URL like "XXX.vfs.va.gov". 

## Background/context/resources
Currently review instance are the main way for developers to [share code changes with PMs and stakeholders](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a5bf9c37d2e38480507490f59bf69feef2ab8f90/platform/engineering/backend/review-instances.md#reviewing-full-applications). Connecting to review instances, however requires using a SOCKS proxy, which is both complicated for non-technical users and requires intervention by ops to add the public key.

Good comment from Bill Ryan on a previous issue that was looking to do something similar: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12264#issuecomment-678397860
RIs documentation from devops repo: 
https://github.com/department-of-veterans-affairs/devops/blob/329e14ac1d4c9eaff1d2377a0c36db1977e015ed/docs/Review%20Instances.md

## Technical notes
We think in order for this to work, we need to move RIs from dsva-vetsgov-staging -> dsva-vagov-staging/utility (?) (172.x.x.x - > 10.x.x.x). We don't exactly know where is the best place to put them / what they need, but want to look into possible solutions here. 

## Considerations 
- Would developers who do not use GFE still be able to access? (If only via CAG, that might be OK.)"
- How many RIs are running on average? 
- We will need IP address space for RIs in the chosen environment
- We may want to look into cleaning them up more aggressively so as to not consume resources / IPs / etc

---
## Tasks
- [x] Investigate network/security requirements for moving RIs to another subnet that can be accessed via GFE

## Definition of Done
- [x] Understand if RIs can be reconfigured so that they can be accessed w/out SOCKS

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by mpelzsherman** [comment]
Would developers who do not use GFE still be able to access? (If only via CAG, that might be OK.)

**Comment by jhouse-solvd** [comment]
@mpelzsherman - I've added your question to a "Considerations" section above.

**Comment by rroueche** [comment]
@drorva and @jhouse-solvd +1 to Michael's comment above -- was chatting about this plan with others and OCTO-DE and was reminded that SOCKS was _created_ as a way for contractor engineers to be able to have more agility so they don't have to rely on being on the network/VPN/CAG. So keep that in mind as you're doing research here: a solution that will require engineers to be on the network would not necessarily be an improvement from the current state.

**Comment by jhouse-solvd** [comment]
@rroueche & @drorva - understood, and agreed. We will investigate how to add additional ways to access review instances while not removing existing ones.

**Comment by mpelzsherman** [comment]
Hi - just pinging y'all to see if there has been any progress on this?

**Comment by drorva** [comment]
@mpelzsherman, not yet. 
It is quite high priority for us.

**Comment by mpelzsherman** [comment]
Hi @jhouse-solvd ! Looks like the spike was completed? Any news to report?

**Comment by dginther** [comment]
After inspecting the way that the review instances are set up, there are a number of challenges that are extremely difficult to overcome, until we do a significant amount of work on converting vets-api to work in the new infrastructure. It doesn't make a lot of sense to do a lot of work in making the Review instances work differently in the 'BRD' paradigm, as it will all have to be redone shortly, when we move review instances into EKS.

Problems:
- containers are built on-the-fly, using docker-compose. This will not work inside the VAEC/TIC boundary. We will need to be able to build the containers outside the VAEC/TIC boundary, and then run them inside it. This means building a container per PR and then putting it in ECR. This requires a huge amount of retooling of the CI process.
- containers mount the drive of the hosting instance for the vets-api code. This does not work well in Kubernetes.
- containers mount a 'dev_bundle' which appears to be an executable. I don't know what this is for and this will not work in K8s.
- containers use a Procfile to run multiple processes inside the vets-api container, this will need to be split apart into different containers for use in a Kubernetes pod.
- In addition to the vets-api repo, there are now multiple other repositories which need to be added to the build (content-build, vets-website, etc.) This process will require some new automation we have not yet written in lieu of mounting it in docker-compose

Developers will be developing in a different way moving forward and the Platform team is still determining how this will work. We are exploring a number of different toolsets which will allow developers to develop for the new infrastructure and will be collaborating with the BE and FE tools teams and gathering input from VFS developers once we have a solid idea of what will work well with the pieces we already have e.g.: ArgoCD/GHA. The outcome of this discussion will absolutely change how review instances work, and how they are created/deployed, so this particular RI conversation will need to wait until we have this new development process in place.

We have no intention of removing the current access to RIs in favor of CAG/GFE access.

**Comment by dginther** [comment]
I did, however, make a change which should add port 443 and a self-signed certificate to the review instances. You would need to add the following CA to your trusted CAs in order to not get a warning about a self-signed certificate:
```
-----BEGIN CERTIFICATE-----
MIID3jCCAsagAwIBAgIQZm+vwsPM1jV1yUu1Bxt0DDANBgkqhkiG9w0BAQsFADCB
iDELMAkGA1UEBhMCVVMxIDAeBgNVBAoMF1ZldHNnb3YgSW50ZXJuYWwgUmV2aWV3
MRMwEQYDVQQLDApPcGVyYXRpb25zMQswCQYDVQQIDAJEQzEgMB4GA1UEAwwXcmV2
aWV3LnZldHNnb3YtaW50ZXJuYWwxEzARBgNVBAcMCldhc2hpbmd0b24wHhcNMjEw
MjE3MTQzNjQ5WhcNMzEwMjE3MTUzNjQ5WjCBiDELMAkGA1UEBhMCVVMxIDAeBgNV
BAoMF1ZldHNnb3YgSW50ZXJuYWwgUmV2aWV3MRMwEQYDVQQLDApPcGVyYXRpb25z
MQswCQYDVQQIDAJEQzEgMB4GA1UEAwwXcmV2aWV3LnZldHNnb3YtaW50ZXJuYWwx
EzARBgNVBAcMCldhc2hpbmd0b24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC6Az6kdv3TmQc6JAnSWjpM+4xwSFUx2WXxAEBg5MhBRBcJ7AIBiaWl188h
TmbW2PsUM+42uSD3kXzsrZy4jkd51ONA2a0+NiYY8jUar5tpK2N10nTfNImuC3V7
1DNAIdi+PCkGgdYBlKCkFW0kI1fzyDkdF8gEqkkCFJbA5ufAkE5wy49m9jC1Z1o7
DQ15TCj9RG0IV9JaJHQONQK1k7EFTfB0c/x6ra1zgbtSQaTd+pev/0tPkk+WAg5L
nqWAosasaPbj5Y/XFdxox1F03Gv3peY6MbLWcfB2sloASsUjIV/7nBsKPfFkBswG
WDnUD5qlq9Uhs6KZMSrx9HNOvyLdAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8w
HQYDVR0OBBYEFPkeTEAQwYwmTppMc2mTWzCGlhwZMA4GA1UdDwEB/wQEAwIBhjAN
BgkqhkiG9w0BAQsFAAOCAQEAr/bQEfGJGr/u30w/pXh+/XLTkTkMojrd/of3yJaf
w/ZNbIDqluxfQ/wUfKYXcvQqnHUo5tdq2+1A5sX5hHFfF7JhbqQ35Lp5mzuiwUFr
bVG2l+3bfkIMWCTvxWqHYiIz7bIH2OdherAKfZsxnbRSw55NblWGTlscZVvxYoxz
WpdR1JPTt3ueZbiPu8SsHYUMMtTgi2hw4dcCxijhLfGDXs0KqQsc3CTMx90ITvSl
wH+iNaawQDQezvWOmsJX57c+nzRFebNhtY365wnkmn/nnFnZkq7E4rXCr72Hksx/
9w6mgtmK2LiXwneRuWFC+plulHrfmv3Pd+XbpcnnXA4z9w==
-----END CERTIFICATE-----
```

**Comment by jhouse-solvd** [comment]
We will add a few additional notes with links to artifacts to help articulate the roadmap (and for tracking purposes), once those have been solidified over the next few days. 

Thanks all for your patience while we continue to work toward improving this very understandable pain point.

**Comment by mpelzsherman** [comment]
Hi @jhouse-solvd . Any updates for our meeting with @jt20816 and @drorva tomorrow?

**Comment by drorva** [comment]
@mpelzsherman , the result of this spike was that we decided not to move forward with this approach of  providing access from GFE (or w/out SOCKS).
The short version is that the current implementation of review instances is fragile and "translating" it to our new infrastructure would be a major effort and we would still end up with something that is not robust.
Instead, we're looking at a better long terms solution that is compatible with our new EKS architecture.

**Comment by jhouse-solvd** [comment]
Please see Dror's [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22545#issuecomment-877291824) above for resulting decision.. 

Closing.
