### ISSUE TITLE
BDD - Change validation on service branch end date

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#22559]
In addition to https://github.com/department-of-veterans-affairs/va.gov-team/issues/21792 the back end needs to make a change to allow future separation dates for reservists.

related sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/20804/?environment=production&project=3&query=is%3Aunresolved+assigned%3Ame+url%3Ahttps%3A%2F%2Fapi.va.gov%2Fv0%2Fdisability_compensation_form%2Fsubmit_all_claim&sort=priority&statsPeriod=14d

## User Story or Problem Statement
As a service member in the reserves or national guard, I need to be able to input my service end date without the system giving me an error.

Right now, reservists and national guard service members are shown an error when they give their obligation end date (or service end date) in the future:

We need to keep this type of validation for all the active duty choices, but remove it for the reservists or national guard folks.

## Tasks
- [x] Keep the 180-day validation on active military service choices
- [x] Remove the 180-day validation on reserve or national guard choices

## Acceptance Criteria
- [x] the 180-day validation works on active military service choices
- [x] the 180-day validation is removed on reserve or national guard choices

**Comment by annaswims** [comment]
this work is complete.  related work will continue in #22582
