### ISSUE TITLE
TUD - Search filter bug

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#22553]
## Issue Description
There is a slight bug with the Search bar feature in the Test User Dashboard.  With the current implementation, the search query in the Modal will search all rows & columns.  We want a similar functionality that searches all rows for specific column entries.  The bug popped up during a Usability Session (# 3) when a user searched for **52** and was shown each user account that had a Form 526, instead of the specified email account number

---
## Tasks
- [x] Fix the global search functionality in the Table to only allow searching by `email`, `first name`, `last name`, and `number in the email`
- [x] Complete a thorough search "stress test" to ensure no unintended results
- [x] Update `Filter accounts` button to `Search Accounts`
- [x] Add label & blurb about what can be searched through the search bar

## Acceptance Criteria
- [x] I can only search by `email`, `first name`, `last name`, or `email number`
- [x] I can see a Search label & fields that can be searched in the Search bar
- [x] When entering in a search query that is not one of the above, no results should be returned.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
