### ISSUE TITLE
TUD - Modify the Copy/Paste feature

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#22555]
## Issue Description
As a TUD user, I would like to see a Popover on hover of the (copy) icon functionality does and when clicked updates the UI, so that I know when  a `Password/Email` is copied.

(Slack's implementation of Popover)
**On hover**
![Screen Shot 2021-03-30 at 4.14.32 PM.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/cd624a6e-92f6-4837-9670-7d9539b202ac)

**On click/copy**
![Copied.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/c540df48-b27c-476c-a1c2-64175634a5a9)

---
## Tasks
- [x] Display a Popover when hovering over the copy icon that says (Copy email/password)
- [x] Display a Popover when clicking on the copy icon that says (Copied email/password)
- [x] Copied Popover displays a different UI (background color) to inform the user

## Acceptance Criteria
- [x] When hovering on the copy icon I see a Popover saying 'Copy password/email'
- [x] When clicking on the copy icon, I see a Popover saying 'Copy password/email'
- [x] I see a difference in Popovers between the hover & on action (clicked) state
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
