### ISSUE TITLE
[PM] Preferred Medical Facility: Submit IA Review with VSP Collab Cycle

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22558]
## Background
As part of the VSP collaboration cycle we need to request an [IA review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-ia-request.md).

## Tasks

- [x] Review [IA request documentation/process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-ia-request.md)
- [x] Submit [IA request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis%2C+shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=ia-request.md&title=IA+Request+%5BTeam-Name%2C+Feature-Name%5D)
- [ ] Work with Design to perform any follow up actions that come out of the IA review touchpoint.

**Comment by andaleliz** [comment]
@ajakabcin I see we have this slated for sprint 45, but I feel like we need to know more about what VAOS is planning before we can really address this.  I don't think we can know more about the flow than we do now, until they start their work.  What do you think?

**Comment by ajakabcin** [comment]
Submitted #23288
