### ISSUE TITLE
TUD - Create functionality to Clear all filters

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#22552]
## Issue Description
As a TUD user, I would like the ability to clear all applied filters, so that I can quickly remove filters find a user I am looking for.

**Ticket created from TUD usability session 3**
---
## Tasks
- [x] Implement a `Clear filters` to remove all applied filters on click and resets table data back to the original

## Acceptance Criteria
- [x] I can see a `Clear filters` link (next to the pilters) that when clicked removes applied filters
- [x] I can see a `Clear filters` link when no accounts are shown in the blurb below the empty table
- [x] Clicking on `Clear filters` also removes the search query (if any)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
