### ISSUE TITLE
[FE] My VA: Investigate if there are situations when we won't be able to tell if user has the claims or appeals services

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22568]
## Background
There may be instances when we won't be able to tell if a user has access to the claims or appeals services. We need to investigate this and determine how to handle those instances.

## Tasks

- [ ] Investigate when/if this scenario exists
- [ ] Determine how we'll handle it
- [ ] Work with @tressaellen if additional designs are needed and @ajakabcin for additional ticket creation as needed

**Comment by erikphansen** [comment]
I've determined that if there is an upstream error with MVI/MPI, we might not be able to determine if someone has the claims and/or appeals service. So we should show an error in place of the Claims and Appeals if there is an error connecting to MPI.

Taking a step back, I think what this really points to is _the need for a general error state when there is an error connecting to MVI/MPI_. This would be consistent with how we handle MPI errors on the Profile (where we blocks users from accessing most sections of the Profile):

![profile MPI error.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/f2b721c7-ea7d-41b2-b6ee-6d03f80227e6)

Recently [Sandra implement a Health Care error when we cannot connect to MPI](https://github.com/department-of-veterans-affairs/vets-website/pull/16620):

![dashboard MPI error.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/2f6bc650-143c-46df-bf52-296984938f5d)

I think we should revise the above "health care" error and make it a more generic message that blocks users from both health care and claims/appeals info.

So the next task is for @tressaellen to determine the correct error to show when we cannot connect to MPI. This error would be in place of health care and claims/appeals info. The error could be similar to the MPI error we show on the Profile. Keep in mind that when this error happens and we cannot connect to MPI, it also means _we can't tell_ if a user should see the health care or claims/appeals section.

**Comment by erikphansen** [comment]
Oh [we already have a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22656) for the what I just described above ☝️

**Comment by erikphansen** [comment]
I'm going to close this. [Handing MPI errors](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22656) is the path forward here.
