### ISSUE TITLE
[Pre-release] Deploy content-build to new production S3 bucket

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#22579]
## Problem Statement
We need to deploy the content from the content build repository to the new, unused dedicated content S3 bucket

---
## Tasks
- [ ] Create a content deployment script in the `devops` repo
    - Similar to the `vets-website` deployment script, but omits application-related build pieces
       - I believe this is where the [current `vets-website` deploy script](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/roles/deploy-vets-website/)
- [ ] Set up Jenkins job to deploy content

## Acceptance Criteria
- [ ] The Jenkins job successfully builds the static content files and deploys them to the appropriate environments

**Comment by timwright12** [comment]
Submitted PR for deployment: https://github.com/department-of-veterans-affairs/devops/pull/8869

**Next Steps**:
1. Confirm functionality with manual deployment to S3 production.
2. Set up deployment schedule to match vets-website daily deploy
3. Set up content-only deploy to content-build production
3. Set up deployment schedule for content-only in content-build

**Comment by timwright12** [comment]
Opened PR to add more jobs: 
https://github.com/department-of-veterans-affairs/devops/pull/8893

**Comment by timwright12** [comment]
Production deploy is now working, however the auto-deploy job is failing to create a release. We can manually deploy right now, but the schedule is broken. Reached out to Ops for support.

Added the content-only deploy and build (https://github.com/department-of-veterans-affairs/devops/pull/8926), waiting on Ops approval. Content-only requires a release, so I don't anticipate this succeeding until the release issue is fixed.

Will work on the application prod deploy in the meantime

**Comment by timwright12** [comment]
Content-build Jenkins Jobs (pre-launch)

- [x] dev deploy (manual & via commit)
- [x] staging deploy (manual & via commit)
- [x] prod deploy (manual, via release job & auto-deploy)
- [x] prod release (manual, via auto-deploy)
- [x] prod auto-deploy (manual)
- [ ] auto-deploy, full (schedule)
- [ ] auto-deploy, content-only (manual) — needs prerelease job
- [ ] auto-deploy, content-only (schedule)
- [x] content-only build (manual)
- [ ] content-only build (via prerelease job)

If they are checked off, they are fully functioning

**Comment by timwright12** [comment]
Waiting for PR merge and seed job run from ops for the content-only auto deploy schedule, after that is confirmed (next potential run 4/19 8am ET), will close this ticket

**Comment by timwright12** [comment]
All deployments are ready to go, at launch we just need to updated the content-only autodeploy cadence to match the current one.

Closing this out!
