### ISSUE TITLE
 [Pre-release] Deploy apps to new prod S3 bucket

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#22578]
## Problem Statement
We need to deploy the apps from the vets-website repository to the new, unused dedicated content S3 bucket

---
## Tasks
- [ ] Create a content deployment script in the `devops` repo
    - Similar to the `vets-website` deployment script, but omits application-related build pieces
       - I believe this is where the [current `vets-website` deploy script](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/roles/deploy-vets-website/)
- [ ] Set up Jenkins job to deploy content

## Acceptance Criteria
- [ ] The Jenkins job successfully builds the app files and deploys them to the appropriate environments

**Comment by timwright12** [comment]
We're going to take an action item to update the current script rather than creat new scripts for the same purpose because the release creation process seems like it might be a blocker for preemptively doing this work.

**Comment by timwright12** [comment]
**Files to update**

- ansible/deployment/config/vets-website-vagovprod.yml

**Should be fine, but check and confirm with Ops**:

- ansible/Jenkinsfiles/releases/vets-website
- ansible/release/config/vets-website.yml
- ansible/deployment/roles/deploy-speedy-s3-assets/tasks/main.yml
- ansible/deployment/roles/deploy-speedy-s3-assets/files/speedy-s3-deploy.sh

**Comment by timwright12** [comment]
We're holding off on this until TBD post-release because of the teamsites

**Comment by laineymajor** [comment]
closing
