### ISSUE TITLE
Add additional evidence document types to 686c workflows

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#22573]
# Background
During testing it was discovered that we need to send a document type along with the additional evidence upload for the `addChild` and `addSpouse` workflows. The document types are specific to the workflow, for instance a Birth Certificate for the `addChild` workflow. Below are the document types for each workflow

`addChild`
- [x] `Adoption Decree` 
- [x] `Birth Certificate`

`addSpouse`
- [x] `Marriage Certificate / License` 
- [x] `Divorce Decree` 
- [x] `Report of Death`

# Tasks
- [x] Add document type dropdowns in each workflow in `vets-json-schema`
- [x] Bump the version number for `vets-json-schema` in package.json
- [ ] Update the commit hash in `vets-website`
- [ ] Make UI changes in `vets-website`
- [ ] Submit PRs in both `vets-json-schema` and `vets-website` for review

## Acceptance criteria
- [ ] The correct document type drop downs have been added to each workflow in the 686c
- [ ] PRs have been submitted for review
