### ISSUE TITLE
[Design, PM] My VA: Start Contact Center guide

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22594]
## Background
In preparation for launch of My VA redesign, we need to prepare a guide for the contact center so that they are able to help veterans when they call for support. Goal is to have a first draft complete by the end of this sprint.

## Tasks

- [x] Write Contact Center Guide outline
- [x] Check in with Samara to make sure we have everything
- [x] Fill in draft Contact Center Guide details

**Comment by ajakabcin** [comment]
Marking as complete as outline is complete and first draft is underway. Final version on track to be complete next sprint.
