### ISSUE TITLE
[Design] Notification Preferences - Design error and success message states

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22592]
## Background
As part of the Notification Preferences project we need to think through designs and user experience for error messages and 
success messages.

## Tasks

- [x] Create list of error states (may need to review with Sandra/Erik)
- [ ] Design and document error message state mockups and copy
- [x] Design and document success message state mockups and copy

## Acceptance criteria
- [ ] Ready for content review

**Comment by andaleliz** [comment]
@erikphansen and @sanlouise, I chatted with @lihanli and identified 2 error states we might encounter:
- can't save users changes
- can't connect to the end point

Given that the screen also pulls in the user's email and mobile number, I think 2 other scenarios we need to encounter are:
- can't load a users contact info
- can't load a users contact info AND can't connect to the endpoint

Are there any other scenarios you can think of that I'm not considering, or is this comprehensive as far as you know now?

**Comment by erikphansen** [comment]
Not an error state but how do you handle if someone doesn't have a phone number or email address on file?

**Comment by andaleliz** [comment]
@erikphansen and @Samara-Strauss, here's the solution I've landed on for the partial contact info use case (missing email OR phone).  
- We show them the information we do have
- Let them know that they could get notifications in a different format if they update their profile
- Replace the relevant checkbox option with language letting them know they have to update their profile first.
  - I didn't include a link to update the profile in this message because it takes them out of the flow they set out on by clicking `edit` in the first place

Interested to hear your thoughts.  If you are good with this solution, I think we can close out this issue and move forward!

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/c5efc317-01c0-4540-a215-f6cdf957a934)

As part of launch, I think we'll need to update the contact section of profile w/ some reference to the tie back notifications.  E.g. if you delete your email you will no longer be able to receive/manage your email notifications.  

As I type this I'm realizing that's yet _another_ scenario I haven't considered yet.  If someone deletes their email address, I would interpret that as a "I don't want to hear from the VA in this way" and they _should_ be opted out. Do you agree?

**Comment by Samara-Strauss** [comment]
When do people see this screen? Do they see it in place of the normal checklist or at another point in the flow?

Idk how hard this would be, but what I would imagine happening is that people see the normal checklist with the email and/or text check boxes disabled if they do not have an email address or phone number in their profile. Then, we'd have a huge alert at the top prompting them to add this info (kind of like what you have now) if they want to receive notifications via text/email.

> As I type this I'm realizing that's yet another scenario I haven't considered yet. If someone deletes their email address, I would interpret that as a "I don't want to hear from the VA in this way" and they should be opted out. Do you agree?

Yes, I would interpret it this way as well, but I would also show a warning if they delete email or mobile phone info once the notification settings section is live.

We could also consider an alternative — don't allow them to delete email/mobile phone info if they receive notifications. That might be worth thinking through whether that's a good or bad approach.

**Comment by andaleliz** [comment]
>When do people see this screen? Do they see it in place of the normal checklist or at another point in the flow?

This would be in place of the normal checklist, when they click `edit` in a group of notifications.  Technically, it shouldn't be hard to implement the disabled checkbox. That was actually the first solution that came to mind, but disabled elements go against a11y best practices, so I didn't even go so far as to see how it worked in the mock-ups.   @joshkimux am I thinking about that correctly in terms of disabled form elements + a11y?

>huge alert at the top prompting them to add this info (kind of like what you have now) if they want to receive notifications via text/email.

IMO, I think it's best to save the huge alert pattern for things we really need to alert people to (like an endpoint failure), especially considering the poor mobile UX of that pattern.  I'm not convinced that incomplete profile info is a Huge Alert use case for notification settings - but that's a great question to add to our research plan.  I'd love to see how the smaller alert tests.  Also, FYI, there is an ongoing initiative to make our alerts more mobile friendly.

>Yes, I would interpret it this way as well, but I would also show a warning if they delete email or mobile phone info once the notification settings section is live.

Awesome, that lines up with exactly what I would've proposed.  An update to the warning message.

>We could also consider an alternative — don't allow them to delete email/mobile phone info if they receive notifications. That might be worth thinking through whether that's a good or bad approach.

I think it is worth thinking through - have been saving this question for the related Edit/Remove/Cancel button ticket.  I'd like to learn more about the use cases that benefit from the delete functionality.  Among my limited profiles, I couldn't find one app/website that would let me delete my email or phone once I had entered it.   I can explore that in a more dedicated way when I pivot to that ticket.

**Comment by Samara-Strauss** [comment]
> This would be in place of the normal checklist, when they click edit in a group of notifications. Technically, it shouldn't be hard to implement the disabled checkbox. That was actually the first solution that came to mind, but disabled elements go against a11y best practices, so I didn't even go so far as to see how it worked in the mock-ups. @joshkimux am I thinking about that correctly in terms of disabled form elements + a11y?

Got it. I think it might be helpful if we link the message about "If you want to receive texts..." to the contact information section of the profile so that people can click that to go update that information.

Also, we should mock a state for what it looks like if someone doesn't have both an email or mobile phone number.

> I think it is worth thinking through - have been saving this question for the related Edit/Remove/Cancel button ticket. I'd like to learn more about the use cases that benefit from the delete functionality. Among my limited profiles, I couldn't find one app/website that would let me delete my email or phone once I had entered it. I can explore that in a more dedicated way when I pivot to that ticket.

TBH, I don't remember why the "delete" interaction was included in the original iteration of the profile 3ish years ago. I almost wonder whether we need it at all. I guess the only use case I can think of is if something is no longer relevant and you don't plan to replace it with new info, eg. you have a home phone, and then you get rid of it in favor of only having a mobile phone. But even in a case like that, I guess someone could just enter their mobile phone in both home/mobile. Anyway, that's a long way of saying that I don't think the delete interaction is sacred, and we might be able to get rid of it altogether.

**Comment by andaleliz** [comment]
>Got it. I think it might be helpful if we link the message about "If you want to receive texts..." to the contact information section of the profile so that people can click that to go update that information.

I had that in one version of the prototype, but I don't think it's great that people would have to exit the flow they're in the middle of to go to the contact section.  We talked about a future version where people can edit their contact info from notification settings in the top part, which I think would be useful here too.  Not linking it requires people to remember the original link at the top of the page, which is something I want to learn about in testing.

>Also, we should mock a state for what it looks like if someone doesn't have both an email or mobile phone number.

I've got that covered [here](https://preview.uxpin.com/bb87d0fa61a32938a47e7bcdc836db235ab77576#/pages/138278598/simulate/sitemap?mode=i) (content has approved this copy, fyi).

>I don't think the delete interaction is sacred, and we might be able to get rid of it altogether.

Yay! That's so helpful to know.

**Comment by Samara-Strauss** [comment]
> Not linking it requires people to remember the original link at the top of the page, which is something I want to learn about in testing.

Agreed. Let's look at this in testing. We'll be able to figure out which approach users expect (link in context vs. link at the top of the page) at that point in time.

> I've got that covered here (content has approved this copy, fyi).

Awesome! This is great.

**Comment by erikphansen** [comment]
A few thoughts:

- I get that disabled checkboxes are bad for a11y, but man this is a situation where I _really_ want them. I am a "scanner" and look for the juicy checkboxes and buttons before I read anything. So I see your above mock and think "oh notifications by text message aren't even a thing" and maybe leave without reading the text _in two places_ that makes it obvious it is an option, it's just that I don't have a cell phone on file. So, a compromise: show the empty checkbox for "text message" but if they try to click it, display text telling them that they need to update their profile to add a cell phone. This would be in addition to the blue info banner that already exists. Adding this checkbox that they can click but can't actually turn on yet would make it basically impossible for someone to miss the fact that SMS notifications are a thing. And I don't think this is an a11y or UX issue because we are avoiding the issue of having disabled controls without telling the user _why_ they can't be interacted with.

- By far the easiest thing to do from the dev perspective is to not allow someone to delete their phone number or email address if they are currently getting notifications via that channel. For whatever reason I think it's nice to be able to delete contact info even if you don't replace it, so I wouldn't advocate killing the delete functionality altogether. But it could be technically tricky to delete a mobile phone number _and_ make sure we told VA Profile to stop notifying them via text message in a single operation.

- In theory we definitely could allow for adding their email address or phone number on this page, without redirecting them to their contact info section, which would be cool. But also probably not an MVP thing at all.

**Comment by Samara-Strauss** [comment]
Thanks for this feedback, @erikphansen!

@andaleliz let us know how you want to proceed forward with potential design updates given Erik's suggestions.

> By far the easiest thing to do from the dev perspective is to not allow someone to delete their phone number or email address if they are currently getting notifications via that channel. 

I am OK with this.

> In theory we definitely could allow for adding their email address or phone number on this page, without redirecting them to their contact info section, which would be cool. But also probably not an MVP thing at all.

I would think not MVP, but we could consider it if we feel strongly or if user feedback really pushes for this.

**Comment by andaleliz** [comment]
>By far the easiest thing to do from the dev perspective is to not allow someone to delete their phone number or email address if they are currently getting notifications via that channel.

I'm in favor of removing the delete functionality for now. Simplifies work here, and in our open a11y violation regarding buttons we need to address. We can ask people about needing to delete phone/email in our research study, would be interesting to see what they say. I can't really think of a strong reason to have this feature myself.

>In theory we definitely could allow for adding their email address or phone number on this page, without redirecting them to their contact info section, which would be cool. But also probably not an MVP thing at all.

This would be very cool, but you're right - not an MVP thing. Again, interested to see what user feedback tells us about this.

>show the empty checkbox for "text message" but if they try to click it, display text telling them that they need to update their profile to add a cell phone. 

It's an interesting idea! I'm down to explore it if it truly isn't an a11y issue.  We slacked about the  screenshot below - this is how I interpret what you're describing happening when someone clicks. Behavior like how we'd handle an error message, but without causing alarm.  @joshkimux, what's your take on this? Is there an a11y consideration we're missing here? I do think this approach offers more clarity than what I had, and better surfaces the available options when we're missing contact info.

![image](https://user-images.githubusercontent.com/55992116/115304667-35073180-a133-11eb-98ba-c0cfa787a565.png)

**Comment by erikphansen** [comment]
Also, looking at the notification preferences designs with fresh eyes makes me think that maybe we shouldn't even have a non-edit view. I honestly always just want to see the checkboxes. We could just hide the SAVE/UPDATE button if they haven't actually made any changes to their preferences. And once they start changing their preferences we show the SAVE button.

**Comment by erikphansen** [comment]
I just think on principle people should be able to delete personal contact info if they don't want it on file anymore. Like an "I never want the VA to email me again!" kind of thing.

**Comment by andaleliz** [comment]
>Also, looking at the notification preferences designs with fresh eyes makes me think that maybe we shouldn't even have a non-edit view. I honestly always just want to see the checkboxes. We could just hide the SAVE/UPDATE button if they haven't actually made any changes to their preferences. And once they start changing their preferences we show the SAVE button.

I hear you - this is what prompted me to go the auto-save route to begin with (just without a save button).  The existing patterns in profile, plus the possibility of this list being 50 notifications long, led me to feeling like the approach we have in the prototype would be a better starting place for our MVP. But we can see what we learn in usability testing. It wouldn't be hard to adapt the auto-save design to a pattern w/ a save button. At least I don't think so.

>I just think on principle people should be able to delete personal contact info if they don't want it on file anymore. Like an "I never want the VA to email me again!" kind of thing.

I hear you here too.  An unsubscribe or disable/enable function would address that concern without compromising data; that's something else we talked about exploring in future iterations.

P.S Now that many comments have been made between this one and the description of your solution, going to add a [link to that specific comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22592#issuecomment-822772262) for @joshkimux so he can easily find it when he has a chance to jump in.

**Comment by joshkimux** [comment]
@erikphansen Love that idea. The key to good accessibility is feedback, so I'm all behind skirting around a disabled button by giving JIT feedback instead. Maybe even making the "first add your mobile phone to your profile" within the feedback message a link that jumps them to where they need to be would be great.

**Comment by joshkimux** [comment]
Also @erikphansen , super appreciate you coming up with this compromise to take a11y into account! You're the best 🥳

**Comment by andaleliz** [comment]
Thanks @joshkimux 

>Maybe even making the "first add your mobile phone to your profile" within the feedback message a link that jumps them to where they need to be would be great.

I had this in an early version, and your feedback was to remove that so we don't take people out of the flow. Do you think that won't be a problem with this new styling? You acknowledge that people would then be required to remember the alert box up top, but we could test and see how it worked. 

Also @erikphansen I want to pass along something from my DM with Josh:
>Yay Erik! Big kudos to him! I read his comment and was so moved to see him acknowledging that disabled buttons aren’t accessible 

Awesome work, Erik! Thanks for proposing this solution, I really like it.

**Comment by joshkimux** [comment]
@andaleliz it works well now that it's provided just in time 😄

**Comment by andaleliz** [comment]
After talking with Josh, I've landed on a solution based on recommendations from the group - a truly collaborative effort! The flow is [mocked-up here](https://preview.uxpin.com/bb87d0fa61a32938a47e7bcdc836db235ab77576#/pages/138374201/simulate/sitemap?mode=i) (click the edit button), and I'll review it with VSP in their office hours today in hopes of getting their sign off.

**Comment by Samara-Strauss** [comment]
> a truly collaborative effort!

Loving this cross-team collab! 

Question, though — I was confused at first because the disabled checkbox appears clickable at first. I would think this would be confusing to anyone not using a screen reader. Is it an a11y no-no to style this box differently (grayed out or something) if we have the extra helper text?

<img width="289" alt="Screen Shot 2021-04-20 at 3 57 06 PM" src="https://user-images.githubusercontent.com/34068740/115456749-85dd5f80-a1f1-11eb-8621-04c96d3579c1.png">

**Comment by joshkimux** [comment]
@Samara-Strauss , as written in @erikphansen 's comment, his proposed compromise was to not disable the button. When they activate the checkbox, they'll receive feedback telling them to add the mobile number. Basically, since it's not disabled, we're giving folks a chance to get clear just in time feedback.

**Comment by Samara-Strauss** [comment]
But then what happens if they don't add a phone number? We just save the form without them having accomplished the action they assumed they were taking? 

Honestly, upon further review, this feels confusing to me. We should just tell people up front they can't select a certain option (which I know is what Liz originally proposed) unless they add an email address/text box. We shouldn't hide this information behind a click. Showing a checkbox as enabled and then having a user click it and get an error message is bad UX because this is not the assumed outcome of clicking a checkbox — obviously, checking or unchecking the checkbox is the assumed outcome. I would think this would be confusing whether someone uses an assistive device or not.

**Comment by andaleliz** [comment]
I discussed this with the VSP team during office hours today, and they strongly recommend sticking with my original solution ([posted here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22592#issuecomment-821231585)).  Ryan specifically called out that the “notify by text” option presents an option they don’t actually have; I can't argue with that. And, though we are telling people up front in an alert box that they need to add contact info before they even click on anything, I see what Samara is saying too. 

I'd like to move forward with my [first solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22592#issuecomment-821231585) for our testing phase and see what we can learn from that.  

If we need to revisit this, let's start with a new ticket specifically dedicated to solving this partial contact info use case, and track it accordingly. I've far exceeded my estimate on this particular GH issue.  If the team thinks this needs more work before usability testing, I'd love to collaborate in a working session.

**Comment by Samara-Strauss** [comment]
I'm good with this. Thanks for all your hard work, Liz.
