### ISSUE TITLE
[Design] Preferred Medical Facilities - Design error and success message states

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22591]
## Background
As part of the Preferred Medical Facilities project we need to think through designs and user experience for error messages and success messages.

## Tasks

- [ ] Create list of error states (may need to review with Sandra/Erik).  This needs to address what to do when you can't connect to the healthcare endpoint at all. Related to #21870
- [ ] Design and document error message state mockups and copy
- [x] Design and document success message state mockups and copy

### Acceptance criteria
- [ ] Ready for content review

**Comment by andaleliz** [comment]
@erikphansen and @sanlouise I'd love your input on another list of use cases I can think of, and things I'm probably missing.  Please let me know what comes to mind. [Here's the original prototype if that's helpful](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006244/simulate/sitemap?mode=i)

- can't connect to the facilities endpoint ([mock-up](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006249/simulate/sitemap?mode=i))
- can't save a users changes ([mock-up](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006245/simulate/sitemap?mode=i))
- user has healthcare, but no registered facilities ([mock-up](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006248/simulate/sitemap?mode=i), I still need to remove the info icon from that alert)
- can't connect to the healthcare endpoint (no mock-up)

**Comment by andaleliz** [comment]
@erikphansen, @sanlouise, and @lihanli  We've talked about this a bit but want to revisit now that we have an official ticket for the work.  I'd love your input on another list of use cases I can think of, and things I'm probably missing.  Please let me know what comes to mind. [Here's the original prototype if that's helpful](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006244/simulate/sitemap?mode=i)

- can't connect to the facilities endpoint ([mock-up](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006249/simulate/sitemap?mode=i))
- can't save a users changes ([mock-up](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006245/simulate/sitemap?mode=i))
- user has healthcare, but no registered facilities ([mock-up](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006248/simulate/sitemap?mode=i), I still need to remove the info icon from that alert)
- can't connect to the healthcare endpoint (no mock-up)

**Comment by andaleliz** [comment]
Per Slack convo w/ @erikphansen , we don't need to address the health care endpoint failure like I thought.  If we couldn't tell if someone was a VA patient, that would be because of an MPI failure, which we already address in profile through a profile-wide generic message:
![image](https://user-images.githubusercontent.com/55992116/114734832-95046f00-9d12-11eb-9efc-741ce2008084.png)


Here are the mock-ups I've put together. Content has already signed off on all but the messages in an info alert. Will review w/ them tomorrow in content office hours.  From left to right:
- No registered facilities
- Facility endpoint failure
- Save failure
- Successful save
- User unchecked all their facilities and hit save.  VAOS does not require someone to have any current facilities, and I can see this being a legit use case if someone has moved and not yet registered anywhere new.

![image](https://user-images.githubusercontent.com/55992116/114734906-ac435c80-9d12-11eb-9356-ff2921937f48.png)

**Comment by andaleliz** [comment]
Content has provided all copy, and [UX Pin prototype](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006244/simulate/sitemap?mode=i) is updated with all the latest changes! 

[Design specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/design-specs.md) are ready for FE.
