### ISSUE TITLE
Message didn't send error

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#22607]
### User Story
As a user I want to know if my message doesn't send so I can contact my MHV Coordinator or the HRC Helpdesk for support.

### Todos
- [ ] Confirm how it works in current experience and what's happy path
- [ ] Discovery: in the mobile app there a way to save message in state and try again
- [ ] Copy (consider also that we don't have drafts)
- [ ] UI design

### Dev notes
API Error:
`SM903 - Send Message Service Error 
`

**Comment by drjecker** [comment]
### Design
UI is here in Invision: https://adhoc.invisionapp.com/console/share/YM10HVPXJE7V/601892051

### Notes for dev
This alert should display when a message doesn't send due to a network error([reference to unhappy paths mapping](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614017071435/8061f2093dc4679b4b1da3ab3f20423c8f1c8f66))
Headline is Mobile Body Bold
Message body is Mobile Body

### Copy
Headline: **Message failed to send**
Message Body:
Please check your internet connection and try again.
If the app still doesn’t work, call the My HealtheVet Help Desk. We’re here Monday–Friday, 8:00 a.m.–8:00 p.m. ET.
877-327-0022
If you have hearing loss, call TTY:
711

**Comment by drjecker** [comment]
@bessgreen this has a UI/design for it in InVision as notes above, but doesn't have a click through for it. Let me know if you have any questions.
