### ISSUE TITLE
Build controller for View Representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#22611]
# Background
Now that we have researched the lighthouse APIs and know that they will not work for what we need on View Representative as well as how the controller should work to suit our needs we should go ahead and build that controller. The rough idea of what this controller will do is

1. Check the POA code in the user's profile object
2. Make a call to the `vets-api` database and match the POA code with the actual Representative data
3. Return the Representative data to the front end as a JSON payload

## Tasks
- [ ] Build out the controller with basic  a basic `show` method
- [ ] Inside the `show` method pull the POA code from the profile object
- [ ] Build out a private `search` method
- [ ] Inside the `search` method check the database for the representative that matches the POA code
- [ ] Back inside the `show` method return the representatice matched in the `search` method
- [ ] Test
- [ ] Submit PR for review

**Comment by RudyOnRails** [comment]
@jason-gcio @kathleencrawford @cohnjesse this one caught my eye while I was looking at other stuff.

Should we close or adjust to match what we are doing?
