### ISSUE TITLE
[new] 1/2: Populate Platform Website V3 (Develop IA)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#22628]
# User story
As a VFS team member, I need to be able to find information on V3, so that I can continue to reference how to build on VA.gov.

# Tasks
- [x] Move the V2 Designer landing page to V3's "Research and Design" content source. **<-- Amy**
- Break up the V1 Backend development documentation into the appropriate V3 content sources. **<-- Gretchen**
  - [x] Roughly familiarize self with all the content in V2 that has to move to V3
  - [x] Identify "homes" for the V1 pages
  - [x] Move the V1 pages to V3 content sources
  - [x] Add language in GH pages, redirecting to V3
- Modify V2 to become V3
  - [x] Associating the required content sources 
  - [x] Check SVP portal page configuration
  - [x] Apply settings for portal page display from V3 sandbox

# Acceptance criteria
- The V2 Designer landing page info is completely reflected in V3's "Research and Design" content source.
- V1 info is completely reflected in the appropriate V3 content sources.

# Reference info
- for links to the various Platform Website versions, see the pinned post in the `#VSP-content-ia` team channel
- [list of GH pages, to be redirected to V3](https://docs.google.com/spreadsheets/d/1fTS_JAp7RhXbybAgIzmfunPUZ-533yaPD_j48Xyvn7I/edit#gid=1176265944)

**Comment by lianilychee** [comment]
Amy will focus on writing the alert on Tues 4/6.

**Comment by lianilychee** [comment]
Tues 4/6 update:
- Gretchen actually moved the Designer page on Friday 😆 
- Amy and Gretchen will sync today.  Tomorrow we aim to have:
  - Additional content sources added and reparented into new homes
  - Portal page all set up

**Comment by lianilychee** [comment]
Weds 4/7 update:
- Amy and Gretchen will sync today
- Amy start/finish this task: "Add language in GH pages, redirecting to V3"
