### ISSUE TITLE
[new] Deprecate the Home Page MVP (Develop IA)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#22627]
# User story
As a VFS team member who uses the Home Page MVP, I need to know where to access the Home Page's equivalent, so that I can continue to get the information I need to build on VA.gov.

# Tasks
- [x] Determine what "deprecating" the Home Page MVP means.  (Probably in consultation with Rachael Roueche.)
- ~If "deprecating" means removing a file:~
  - ~Identify the location in the GitHub repo~
  - ~Remove the file~
- If "deprecating" involves adding an alert:
  - [x] Write the alert to redirect **<-- Amy**
  - [x] Add the alert to the Home Page MVP **<-- Liani**

# Acceptance criteria
- We are ready to start executing the release plan in Sprint 50 (release plan https://github.com/department-of-veterans-affairs/va.gov-team/issues/17376)

# Reference info
- Home Page MVP
  - [site](https://department-of-veterans-affairs.github.io/va.gov-team/)
  - [GH page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/docs/index.html)
  - [Convo w/ other PMs re: How to add banner to Home Page](https://dsva.slack.com/archives/GMX26FF9D/p1617645674009400)
- [Platform Website V3: In progress "sandbox"](https://va-platform-docs.scrollhelp.site/index.html)
- Rec that we presented to Rachael Roueche on Fri 4/2: [When do we deprecate the Home Page in tandem with building out Platform Website V3?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/2021-04-02-deprecate-homepage-decision.md)

**Comment by lianilychee** [comment]
Mon 4/5 update:
- Amy will focus on writing the alert on Tues 4/6.

**Comment by lianilychee** [comment]
Gretchen's impromptu idea from Friday: 
> We’re moving our docs! Find the official, up-to-date version of this document on the new Platform Website.

**Comment by lianilychee** [comment]
Tues 4/6 updates:
- to come.
- Liani tweaked the HTML file, and Home Page (in a feature branch) now renders like this: 
![Screen Shot 2021-04-06 at 10 01 42 AM](https://user-images.githubusercontent.com/6895034/113735522-ef258480-96c1-11eb-8fc9-12c60d87a72e.png)

**Comment by lianilychee** [comment]
Here's the final -- ready to merge from feature branch to master when https://github.com/department-of-veterans-affairs/va.gov-team/issues/22628 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/22633 are good to go!
![Screen Shot 2021-04-07 at 12 55 02 PM](https://user-images.githubusercontent.com/6895034/113912696-0edfaa00-97a1-11eb-82de-5291507de6f9.png)
