### ISSUE TITLE
Updates to link to NPRC fire page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#22624]
## Issue Description
We have a page about [reconstructing records lost from an NPRC fire page](https://www.va.gov/records/get-military-service-records/reconstruct-records/). Before we created this page, we linked to a legacy page about it from other VA.gov pages. We then created a redirect with those links to go to our modern page. Now we should just link directly to our page without the redirect. We need to do the following: 
- Find all the pages where we link to the reconstruct records page and update to link to it directly
- Rework the note on the [evidence needed page](https://www.va.gov/disability/how-to-file-claim/evidence-needed/) since we don't need to give as much info anymore now that we have a whole page on it

## Tasks
- [x] Identify pages where we have links on the NPRC fire
- [x] Update links so they go directly to our NPRC page rather than a redirect
- [x] Shorten note on evidence needed page
- [x] Review and publish pages

## Acceptance Criteria
- [ ] Pages live with updated link and updated note

**Comment by RLHecht** [comment]
Update: This is work that could be picked up anytime. @bethpottsVADEPO do you think this is worth trying to push through in this last sprint or keep in the backlog?

**Comment by lunascoop** [comment]
@RLHecht these pages were updated.

> Evidence needed for your disability claim: http://preview-prod.vfs.va.gov/preview?nodeId=907 (shortened NPRC note and updated link)
> How to apply for a VA pension as a Veteran: http://preview-prod.vfs.va.gov/preview?nodeId=586 (shortened NPRC note)
> Request your military service records (including DD214): (Changed sighted language) http://preview-prod.vfs.va.gov/preview?nodeId=472
> VA Fully Developed Claims program: (updated sighted language, shortened note, updated NPRC link) http://preview-prod.vfs.va.gov/preview?nodeId=908

**Comment by RLHecht** [comment]
@psanders86 These pages are ready for you to review.

**Comment by bethpottsVADEPO** [comment]
@psanders86 This review can skip straight to me so you can keep focusing on education rates pages.

**Comment by psanders86** [comment]
Thank you!


[cid:dd5306c8-bc7a-4271-8535-96df6b369269]

Patrick Sanders

Content Writer



M:  240-444-6116


About<https://governmentcio.com/about>   |   Services<https://governmentcio.com/services>   |   Careers<https://governmentcio.com/careers>

Confidentiality Note: This email may contain confidential and/or private information. If you receive this email in error, please delete and notify sender.­

________________________________

**Comment by bethpottsVADEPO** [comment]
@RLHecht Would you review my edits to the first 3 nodes, especially the spacing before the text link in each? Then you can publish!

**Comment by RLHecht** [comment]
Thanks. I reviewed all of these nodes and published.
