### ISSUE TITLE
[VAMC]  Tech-debt - update "Other locations" with nearby vet centers or vet services

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22625]
## Story
As a Veteran web user I need to have access to nearby Veteran services, so I can quickly find other services and locations.

The Vet Center product builds the Other Locations list programatically.
On VAMCs the other Locations list is built manually in the CMS on the VAMC System content type form.

We need to verify with VHA DM:
* Should every VAMC System have "Other locations" listed? 
* If so, should that be a programmatic build or an editor task to populate?

## Resources
[Facility Locator](https://www.va.gov/find-locations/)

## Task
Update all VAMC Systems with the following information:
- [ ] System page updates
- [ ] Vet center locations
- [ ] Benefits

## Acceptance Criteria
- [ ] Nearby locations are now visible on VAMC System pages

**Comment by jilladams** [comment]
1. no more dual state VAMCs
2. https://www.va.gov/pittsburgh-health-care/locations/#other-nearby-va-locations exists - not certain without deeper look whether it's built programmatically. But we believe this is not in CMS to select.
3. Vet Center lists are built programmatically, we know. 

To be verified: is https://www.va.gov/pittsburgh-health-care/locations/#other-nearby-va-locations built programmatically? If so, close this ticket. Tagging @maxx1128 for FE look in templates -- not urgent, can be a background task.

**Comment by mmiddaugh** [comment]
This will be addressed in [CONSIDER] Revisit logic governing "Other nearby VA locations" on VAMC pages #13896
