### ISSUE TITLE
[new] 2/2: Populate Platform Website V3 (Develop IA)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#22633]
# User story
As a VFS team member, I need to be able to find information on V3, so that I can continue to reference how to build on VA.gov.

# Tasks
- Determine what is "remaining" on the Home Page MVP, and how that slots into V3 content sources
  - [x] Identify what on the Home Page MVP is -not- covered by V1 and V2
  - [x] Identify which V3 content sources that "remainder" slots into
  - [x] Create links in V3.

# Acceptance criteria
- All information on The Home Page MVP is reflected in V3.

# Reference info
- for links to the various Platform Website versions, see the pinned post in the `#VSP-content-ia` team channel

**Comment by lianilychee** [comment]
Weds 4/7 update:
- Amy and Gretchen will sync on this today!

**Comment by lianilychee** [comment]
Fri 4/9 update:
- Amy and Gretchen will pair if time allows
- goal for today: 
  - have all of the home pg links (minus operational docs) accounted for in the platform website
  - (stretch) have alerts on GH pages, pointing to Platform Website pages

**Comment by gmaciolek** [comment]
[Spreadsheet of what was changed](https://docs.google.com/spreadsheets/d/1fTS_JAp7RhXbybAgIzmfunPUZ-533yaPD_j48Xyvn7I/edit?usp=sharing).

- Deprecate BE tools Docs tab was used to point BE tools GH links to Platform Website
- Homepage MVP Links tab was used to handle the rest of the homepage MVP links
