### ISSUE TITLE
508 Accessibility - Fix heading level for appointment request list

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#22631]
## Description
Heading level skips from level 2 to 4 on appointment request list view.
---
## Tasks
- [ ] None

## Acceptance Criteria
- [ ] Heading levels are not skipped

## Definition of Done
- [ ] All acceptance criteria are met

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
