### ISSUE TITLE
Review and publish burial pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#22632]
## Issue Description
The NCA team updated PDF links and aria labels to the four pages listed below. We need to review and make sure that links and aria labels are correct before publishing. 

- Pre-need eligibility for burial in a VA cemetery: http://preview-prod.vfs.va.gov/preview?nodeId=862
- After you apply for an eligibility determination: http://preview-prod.vfs.va.gov/preview?nodeId=863
- Burial in a private cemetery: http://preview-prod.vfs.va.gov/preview?nodeId=2346
- Veterans headstones, markers, and medallions: http://preview-prod.vfs.va.gov/preview?nodeId=859

## Tasks
- [x] Initial review of pages and make corrections as necessary (Selina)
- [x] Review and publish pages (Randi)

## Acceptance Criteria
- [x] Pages live with updated links

**Comment by RLHecht** [comment]
@lunascoop These pages are all reviewed and published. I added hours to numbers on two pages that we didn't have already for consistency. Moving to validate and will close after the next deploy.

**Comment by RLHecht** [comment]
These pages are live. Closing ticket.
