### ISSUE TITLE
Add language to Style Guide about including days and times in ET for phone numbers

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#22640]
## Issue Description
Our style is to use ET with all hours of operation on our site, even if an office is in a different time zone. It is also our style to always include the hours of operation when we list a phone number. We need to update this language in our style guide, which currently references using other time zones.

## Tasks
- [x] Add language to style guide to always use ET with hours
- [x] Add language to style guide to always include days and times when listing a phone number
- [x] Update current examples to remove other time zone mentions

## Acceptance Criteria
- [x] Style guide is updated with new language around time zones

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made these changes to the style guide but for some reason I can't assign you in the PR to review. Here it is: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/422

**Comment by bethpottsVADEPO** [comment]
Thanks for updates the entries! I put one comment in there to add an article in the first commit. Otherwise, looks great.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
