### ISSUE TITLE
Replace VAMC top task CTA

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22646]
## Issue Description
The Facilities team recently became aware of the button/link design shift which will impact various CTAs throughout the VAMC product. 

## Current behavior: 
![image](https://user-images.githubusercontent.com/55411834/113602543-fb490d80-95ff-11eb-85ca-d80c1d007495.png)

## Expected behavior
This issue will address VAMC "Top task" CTAs which behave as links and should be styled accordingly: 
![image](https://user-images.githubusercontent.com/55411834/113602191-8d044b00-95ff-11eb-8eb7-8517d3191157.png)

This includes: 

1. "Top task" and additional CTAs on Health care system pages and Locations pages

- "Make an appointment"
- "View all health services"
- "Register for care" 
- "See all locations"
- "See all stories"
- "See all events"

2. Health service "Top task" CTAs
- "View all health services"
- "Register for care" 
- "Pharmacy" 
- "Schedule an appointment online" (inside accordions)

---
## Tasks
- [ ] Replace the "Make an appointment" CTA with a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
`<a className="va-action-link--blue" href="#">Call to action</a>` 
- [ ] Replace the "View all health services" CTA with a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
`<a className="va-action-link--blue" href="#">Call to action</a>` 
-  [ ] Replace the "Register for care" CTA with a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
`<a className="va-action-link--blue" href="#">Call to action</a>` 
-  [ ] Replace the "Pharmacy" CTA with a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
`<a className="va-action-link--blue" href="#">Call to action</a>` 
-  [ ] Replace the "Schedule an appointment online" CTA with a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
`<a className="va-action-link--blue" href="#">Call to action</a>` 
- [ ] Replace CTAs linking to "See all locations", "See all stories", and "See all events" with an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, #004795

## Acceptance Criteria
- [ ] The VAMC "Make an appointment" CTA is a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
- [ ] The VAMC "Register for care" CTA is a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
- [ ] The VAMC "Pharmacy" CTA is a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
- [ ] The VAMC "Schedule an appointment online" CTA is a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
- [ ] The VAMC "View all health services" CTA is a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
- [ ] The "See all locations" CTA is an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, #004795.
- [ ] The "See all stories"CTA is an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, #004795
- [ ] The "See all events" CTA is an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, #004795

**Comment by davidmpickett** [comment]
Duplicate with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14928
