### ISSUE TITLE
Replace VAMC "Learn more" buttons

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22645]
## Issue Description
The Facilities team recently became aware of the button/link design shift which will impact various CTAs throughout the VAMC product. 

## Current behavior: 
![image](https://user-images.githubusercontent.com/55411834/113603223-e9b43580-9600-11eb-8fb9-68c6c6fa6f6b.png)
![image](https://user-images.githubusercontent.com/55411834/113603599-5e876f80-9601-11eb-8f37-cc8318047c76.png)

## Expected behavior
This issue will address VAMC "Learn more..." buttons which actually behave as links and should be styled accordingly: 
![image](https://user-images.githubusercontent.com/55411834/113603271-fafd4200-9600-11eb-97f0-737675171198.png)

## Tasks

- [ ] Replace the "Learn how to request chaplain services during your stay at VA Pittsburgh." as seen on the "Chaplain services and chapels" accordion under "Prepare for your visit" with an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, #004795
- [ ] Replace the "Learn more about the history of Veterans Affairs" button as seen on the [History page](https://www.va.gov/pittsburgh-health-care/history/) with an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, #004795
- [ ] Replace the "Find out more about volunteering to participate in research" button as seen inside the "Volunteer for medical research studies" accordion on the [Volunteer or donate page](https://www.va.gov/pittsburgh-health-care/work-with-us/volunteer-or-donate/) with an active link styled according to the [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, #004795

## Acceptance Criteria
- [ ] The "Learn how to request chaplain services during your stay at VA Pittsburgh." as seen on the "Chaplain services and chapels" accordion under "Prepare for your visit" is styled as an active link 
- [ ] The "Learn more about the history of Veterans Affairs" button as seen on the [History page](https://www.va.gov/pittsburgh-health-care/history/) is styled as an active link
- [ ] The "Find out more about volunteering to participate in research" button as seen inside the "Volunteer for medical research studies" accordion on the [Volunteer or donate page](https://www.va.gov/pittsburgh-health-care/work-with-us/volunteer-or-donate/) is styled as an active link
- [ ] The active links listed above are styled according to the [Design system](https://design.va.gov/components/action-links#how-to-use-other-links) and use Source Sans Pro (Bold), underlined, 16px, #004795

**Comment by davidmpickett** [comment]
Updated this ticket to include instances of the same button type on VAMC system pages that were previous listed on https://github.com/department-of-veterans-affairs/va.gov-team/issues/22646
