### ISSUE TITLE
[Content] Update content and style on all Viable System pages [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22650]
## Story
As a Veteran I need to have all pages read accurately and clean, so they are easy to digest and understand in my health care journey.

## Goal
- [ ] Optimize content to meet latest updates in style and plain language

## Task
- [ ] Review and update content pages for latest updates of content style
- [ ] provide pages that have been updated, and or sheet to utilize for planning.

## Acceptance Critieria
- [ ] All pages are updated with new revised content
- [ ] Team is prepped in meeting for future cloning and process

**Comment by psanders86** [comment]
This is added to our shared drive at VAMC_GCIO_Upgrade/Content

https://docs.google.com/document/d/1BJZqNJhEANg8oeBAKJKi64ojDUPnMjdl/edit
