### ISSUE TITLE
[Design] My VA: Error state for when user is not in MVI/MPI

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22656]
## Background
We need to design an error message to account for scenarios when a user is not in MVI/MPI for some reason.

## Tasks
- [ ] Design error state/message
- [ ] Review with FE devs
- [ ] Work with @ajakabcin to create FE implementation ticket(s)

**Comment by erikphansen** [comment]
Earlier today I rediscovered that this is a state we'll need to handle. Perhaps [my mini brain dump](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22568#issuecomment-817992382) is helpful.

**Comment by tressaellen** [comment]
@erikphansen thank you, yes that is helpful! Working on this now!

**Comment by tressaellen** [comment]
I have a question for @erikphansen - [This is what](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22568#issuecomment-817992382) we currently show in profile for MPI, and below is what I have in my sketch file for MPI. Do you know if this is a 'refresh and try again' situation or should we link to 'Find the nearest medical facility'?

![Screen Shot 2021-04-14 at 11.47.24 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/02ef4a3f-e68e-4f04-b743-ea3b0d78eee6) 


This is a rough draft of what I have for the MyVA version of this error. 

![Screen Shot 2021-04-14 at 12.03.07 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/45ec8b66-02a1-438e-8e1c-dc5b5eff35a6)

**Comment by erikphansen** [comment]
This is understandably confusing.

The alert you shared above, "We can't match your information...", is for when the user is _not in MPI_.

The other alert that I had previously shared, "We can't access your veteran records" is for when there is _an error connecting to MPI_.

We probably need both for the My VA Dashboard:
- an error when we cannot connect to MPI
- an error when we can connect to MPI but the user is not in MPI

**Comment by tressaellen** [comment]
OH okay, got it. Does this work @erikphansen ? If so, I'll get copy involved to take a look at these.

- This is the error for when we can connect to MPI but the user is not in MPI

![Screen Shot 2021-04-14 at 12.03.07 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/ba113710-bf89-4c86-b11f-8d16baeac215)

- And this is the error for when we cannot connect to MPI 

![Screen Shot 2021-04-14 at 1.18.20 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/df88ae3c-c7fd-4539-8a54-264769dbb40c)

**Comment by erikphansen** [comment]
Those would work for me.

**Comment by tressaellen** [comment]
@bethpottsVADEPO could you work your magic on this error please? Specifically the heading - the content has already been approved.

**We can't access any health care or claims or appeals information right now**

We’re sorry. Something went wrong when we tried to connect to your veteran records. Please refresh or try again later.

![Screen Shot 2021-04-14 at 1.18.20 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/7e530fe7-659e-4d1e-992f-1c77f743f128)

**Comment by bethpottsVADEPO** [comment]
@tressaellen Thanks for sending this along!
1/ We can't access any health care, claims, or appeals information right now
2/ We don't usually say "Veteran records." For this error message can we use just "records"? If it needs to stay for some reason, please capitalize "Veteran." If we can drop it, would you do the same with the other error message I saw above that also has it?
3/ For the helper text, drop "the" before VA. We're never supposed to refer to VA in that way. 

Please let me know if I missed a different error message come through from earlier this week. I feel like I got tagged on another one but can't find it now.

**Comment by tressaellen** [comment]
Thank you @bethpottsVADEPO ! That's all we needed. 

Final copy for this error:

**We can't access any health care, claims, or appeals information right now**

We’re sorry. Something went wrong when we tried to connect to your veteran records. Please refresh or try again later.

![Screen Shot 2021-04-19 at 2.56.35 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/794f0634-214d-4c89-92ee-57169b873d87)

We'll also need to create a ticket to remove the word 'veteran' from this alert in My VA and in Profile 2.0

![Screen Shot 2021-04-19 at 2.55.05 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/e0edd9e9-bdb1-4171-b576-cff891b1581a)

**Comment by tressaellen** [comment]
@ajakabcin we'll need 2 FE tickets out of this.
 
-  Implement an error when we cannot connect to MPI (copy and design is in the comment above)
- Remove the word 'veteran' from the error when we can connect to MPI but the user is not in MPI in both My VA and Profile

Once we have those then I think we're good to close this ticket!

**Comment by bethpottsVADEPO** [comment]
@tressaellen You had this for final content, but it still includes "veteran" so just wanted to check that you took that out:

Final copy for this error:

We can't access any health care, claims, or appeals information right now

We’re sorry. Something went wrong when we tried to connect to your veteran records. Please refresh or try again later.

**Comment by ajakabcin** [comment]
Hi @bethpotts - yes @tressaellen and I realized that yesterday when I was creating the implementation tickets. She's getting us updated screenshots. Thanks for following up!

**Comment by ajakabcin** [comment]
Final copy will be as follows:

**We can't access any health care, claims, or appeals information right now**

We’re sorry. Something went wrong when we tried to connect to your records. Please refresh or try again later.


and for the existing MVI alert, the final copy will be as follows:

**We can't access your records**

We're sorry. We can't give you access to health and benefits tools until we can match your information with our records and verify your identity.

If you'd like to use these tools on VA.gov, please contact your nearest VA medical center to verify and update your records.

Find your nearest VA medical center (link)

**Comment by tressaellen** [comment]
@ajakabcin I'm now realizing I messed up the title for the existing MVI/MPI alert. This alert exists currently in the profile, so we need to just use that alert and and remove the word 'Veteran' from the title.  The final copy will be as follows:

**We can't match your information with our records**

We're sorry. We can't give you access to health and benefits tools until we can match your information with our records and verify your identity.

If you'd like to use these tools on VA.gov, please contact your nearest VA medical center to verify and update your records.

Find your nearest VA medical center

**Comment by erikphansen** [comment]
This is the not in MPI alert we are showing in the Profile

<img width="688" alt="not in mpi after" src="https://user-images.githubusercontent.com/20728956/115773360-12f4f580-a365-11eb-836a-5ee354e93ba3.png">

The copy is quite a bit different from this My VA error. And it's also a warning alert vs the red error alert for My VA.

So should we using the exact same not in MPI alert on My VA and Profile? Are should they be slightly different?

**Comment by tressaellen** [comment]
Followed up in #23468

**Comment by ajakabcin** [comment]
To close the loop on this, we came away with three follow-up tickets to address our findings:
- My VA: Implement an error when we cannot connect to MPI #23464
- My VA: Implement error for when we can connect to MPI but user does not exist #23696
- Profile: Remove the word “veteran” from copy in existing Profile error #23468
