### ISSUE TITLE
[FSR] Quickfix design for multiple current jobs

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22690]
## Issue Description
For the purposes of release, we need to design a quick fix to account for multiple current jobs.

---
## Tasks
- [x] Create a design and upload it to UXPin
- [x] Create a ticket for FE

## Acceptance Criteria
- [x] Designs uploaded to UXPin and linked in this ticket
- [x] FE ticket created and linked in this ticket ([ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23371))

**Comment by rileyorr** [comment]
I reached out to Craig about a potential quick fix solution to gauge how heavy a lift this would be to implement:
After [the ‘tell us about your current job’ page](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136159504/comment/sitemap?mode=i), we add a page to [ask the veteran if they currently have another job](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138281545/comment/sitemap?mode=i). If yes, we just show them another ‘tell us about your current job’ page and loop until they say no to the question asking if they currently have another job. He's going to look into it and get back to me about the level of effort.

**Comment by rebeccawalsh** [comment]
I created a blank ticket to represent this work for our conversation 5/16 about blocking issues https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23371

**Comment by rileyorr** [comment]
I removed the blocked tag because Craig said he'd be able to do it in the team meeting we just had. @troyriser when you get a chance can you do a content spot check on the question I added on [the page where we're asking the Veteran if they currently have another job](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138281545/comment/sitemap?mode=i) so I can get this work over to Craig? Thank you!

**Comment by troyriser** [comment]
@rileyorr The content checks out on my end. It's succinct, concise, and to the point. You're on a roll.

**Comment by rileyorr** [comment]
Thanks, @troyriser!

I've updated the frontend ticket related to this work; going to move this one over to validate.

**Comment by troyriser** [comment]
@rileyorr Regarding the "Do you currently have another job?" question, it looks copacetic to me: to-the-point and concise and definitely within the plain language standard.
