### ISSUE TITLE
NOD: Build out and test API endpoints

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#22691]
## Issue Description

Before we lose our backend engineer, we'll need to set up NOD's prefill, contestable issue and submit API endpoints and tests.

## Tasks

- Set up & test prefill data
- Set up & test updating contestable issues
- Set up & test submission endpoint with confirmation

## Acceptance criteria

- [ ] Unit tests added for prefill
- [ ] Unit tests added for updating contestable issues
- [ ] Unit tests added for submission & confirmation
