### ISSUE TITLE
Front end route changes for Rails engine

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22701]
## Issue Description
Need to change routes to complete Rails engine work

---

## Tasks
- [x] Add flipper to control routes
- [x] Change route for each API call to new route `https://api.va.gov/facilities_api/v1/ccp` 
- [x] **For ccp routes only**, the service type parameter will go away (i.e. provider, urgent care) and will now be part of route. i.e.:
  - `https://api.va.gov/facilities_api/v1/ccp/urgent_care`
  - `https://api.va.gov/facilities_api/v1/ccp/provider`
  - `https://api.va.gov/facilities_api/v1/ccp/pharmacy`

## Acceptance Criteria
- [x] Calls use new routes
---

**Comment by mmiddaugh** [comment]
Blocked by action work

**Comment by mpelzsherman** [comment]
It's unclear to me why the change to move the type param into the route should be limited to ccp routes only. This makes the code more complicated. I'm blocking this ticket until we have clarity as to why this limitation is required.

**Comment by mmiddaugh** [comment]
Previous implementation makes backend handling difficult due to

- No logging data for parameters passed through API
- Microsoft dependency requirements

**Comment by mpelzsherman** [comment]
Validation is blocked due to issues with the flipper.

**Comment by mpelzsherman** [comment]
`facility_locator_rails_engine` has been enabled for us in Staging

**Comment by mpelzsherman** [comment]
I have verified that the Rails enging queries are working correctly in staging. However, the urgent care queries are running very slowly - averaging around 40 seconds.
