### ISSUE TITLE
526 Enhancements Research Initial Tasks

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#22712]
## Issue Description
526 Enhancements - misc. tasks

---
## Tasks
- [ ]  Create prototype of entire 526/BDD flow
- [ ] BDD gating/ reservists v. active duty validation

## Acceptance Criteria
- [ ] Results documented on GitHub
---

**Comment by vhenry07** [comment]
Closing complete.
