### ISSUE TITLE
GA implementation for form submission

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#22713]
## Issue Description
Since form submission data was recently implemented we need to add GA tags to submission events / changes outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16010#issuecomment-814218488)

---
## Tasks
There's a typo within the datalayer for `reason-for-alert` with an extra e in related

Add the following submission events to FSR:
- [ ] `--submission-successful`
- [ ] `--submission-failed`

## Acceptance Criteria
- [x] `reason-for-alert` typo has been fixed
- [x] `--submission-successful` event has been added and verified
- [x] `--submission-failed` event has been added and verified
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
verified events are being tracked in google analytics
