### ISSUE TITLE
Content release failure notifications provide detailed information about the source of failure

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#22717]
## Issue Description
_As an VFS engineer, I can tell from reading a slack notification, the source of a content release failure, so that I know who is accountable for triage._

---
## Tasks
- [ ] _Update CI/CD notification process to send detailed content release failure details_

## Acceptance Criteria
- [ ] _Slack notifications from content release failures sent to the #VFS-Support include the source of the release failure including a distinction for broken links_
- 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by meganhkelley** [comment]
On hold until migration to GHA is complete
