### ISSUE TITLE
New Smoke Test: Login

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#22718]
## Issue Description
There is a need for a smoke test that tests standard login on the platform. Leverage the newly created AWS Canary + Terraform implementation from the Ops team to create and schedule for execution a synthetic monitoring test targeting production. A high level sample set of test steps is below -- 

1. Navigate to va.gov
1. Click on Sign-in
1. Click on the ID.me Sign in with ID.me
1. Enter production test account credentials 
1. Click Sign in to ID.me
1. Continue through the 2FA verification
1. Verify login landing page is free from errors

---
## Tasks
- [ ] Sync with Ops to leverage the tooling they have already set up
- [ ] Consider using the Canary recording mechanism to record the steps as a starting point
- [ ] Review Puppeteer script for fragile selectors
- [ ] Create a pull request with the completed test and work with Ops to review any requested changes

## Acceptance Criteria
- [ ] A smoke test running on a schedule against production verifies that the ID.me login mechanism of production is functioning as intended

**Comment by pjhill** [comment]
These appear to be related...

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22288

**Comment by pjhill** [comment]
Closing as dupe
