### ISSUE TITLE
Create thresholds for content release failures

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#22720]
## Issue Description
_As a CMS editor, I can expect that my content will be available on va.gov according to the content release schedule I was given so that I have confidence on a reliable system._

---
## Tasks
- [ ] _Update CI/CD process to include thresholds for release failures_

## Acceptance Criteria
- [ ] Top level va.gov page broken links will block the build; any page deeper does not.
- [ ] Use a threshold so that 10 or fewer broken links do not block build, but 11+ do block the build
- [ ] Notifications to #vfs-engineers should be sent when there are broken links, even if they do not break the build

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jefflbrauer** [comment]
CMS Team performed some discovery work on this. Recommendation is included here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19215#issuecomment-776821738

**Comment by meganhkelley** [comment]
@jefflbrauer this work is complete, correct?
