### ISSUE TITLE
Create drupal page for VRRAP, get stakeholders to sign off

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#22727]
## Issue Description
We need to create an informational/static page to communicate this new program to Veterans. Veterans who are unemployed because of COVID-19 and meet the other eligibility criteria can get education or training in a high-demand job. This program will last for 21 months. 

**IA recommendations:** (see here for breadcrumb info): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-vrrap.md

---
## Tasks
- [x] Create page in drupal (Selina) --Content, URL, and breadcrumb info are in the attached Word doc.

[https://app.zenhub.com/files/133843125/3acc6230-b94d-45b1-abb6-f771791cd154/download](https://app.zenhub.com/files/133843125/3acc6230-b94d-45b1-abb6-f771791cd154/download)

- [x] Copyedit (Randi)
- [x] Bring to stakeholders for approval (Beth)
- [x] Collab cycle review
- [x] Run through pre-pub checklist and add breadcrumb (Randi)
**Hold on publishing until form is ready** 
- [x] Publish when form launches (Randi to coordinate with BAH team--Will McCormack and Jen Jones)

## Acceptance Criteria
- [x] Drupal page is created from Word doc and ready to share with stakeholders.
- [x] Static page launches with form (targeted for mid-April)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
Hi @RLHecht I created the page. The info for **Option 1: Apply by mail** still needs be added and I haven't changed the URL and breadcrumb (isn't that the last thing to do?) cc: @bethpottsVADEPO 

- Veteran Rapid Retraining Assistance Program (VRRAP): http://preview-prod.vfs.va.gov/preview?nodeId=17942

**Comment by RLHecht** [comment]
@bethpottsVADEPO This page is ready for you. For now I have in a green button with a fake link that we will need to update once we have the website

**Comment by bethpottsVADEPO** [comment]
Here is the link to the form: www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s

Should know later today if we'll need to switch the green button to an action link. Maybe tomorrow.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I removed the other ways for applying so the page is ready for SMEs now.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks! I sent it off for their review.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I added some tasks to this ticket rather than opening a separate one for stakeholder review and publishing the page. We're now waiting on a collab cycle review that Jen Jones will coordinate and on stakeholder feedback that I sent to Don Ortega in Education Service.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Would you please submit a redirect ticket to point this benefits.va.gov VRRAP page to our new one?: https://benefits.va.gov/gibill/vrrap.asp

**Comment by bethpottsVADEPO** [comment]
@lunascoop Also, please cc me on the redirect ticket, and put a note in for Mikki (like you did for the DD redirects) that she can assign it straight to Kelson or Bryan.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Along with the work for the left nav, we'll add a new header, link, and teaser to this page: https://www.va.gov/education/other-va-education-benefits/

Here's what it'll look like (add it as the last one as you see here) with the other content on that page now:

**Programs for added GI Bill benefits**
Edith Nourse Rogers STEM Scholarship
Veteran Employment Through Technology Education Courses (VET TEC)
Yellow Ribbon Program

**Alternative programs if you're not eligible for the Post-9/11 GI Bill**
The Montgomery GI Bill Active Duty (MGIB-AD)
The Montgomery GI Bill Selected Reserve (MGIB-SR)
The National Call to Service program
The post-Vietnam Era Veterans’ Educational Assistance Program (VEAP)

**Education and training if you're unemployed because of the COVID-19 pandemic**
Veteran Rapid Retraining Assistance Program (VRRAP)
This program offers education or training for high-demand jobs to Veterans who are unemployed because of the COVID-19 pandemic. If you're not eligible for GI Bill or VR&E benefits, you may be eligible for this program.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I added this text to the other education benefits page and will keep as draft until VRRAP goes live on 4/30/.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks so much!

**Comment by RLHecht** [comment]
I published this page without the form link for now. When the form goes to prod this afternoon, I will add back in and do a content release.

**Comment by RLHecht** [comment]
Static page is live with link to form. Closing ticket.
