### ISSUE TITLE
COVID-19 scheduling - Lighthouse connection (Facilities)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22736]
## Issue Description
As a Veteran searching for locations offering COVID-19 vaccinations, I want to know which locations allow online scheduling through VAOS. Our short term plan to provide this information is by connecting directly to VAOS (#21734). 

**This issue is the higher priority work: providing access to this data via a backend connection to Lighthouse**

## Lighthouse background
> Phase 1 added Covid19Vaccine to the list of health services. 
> Phase 2 added detailed service information for the vaccine service. [CMS](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4484) is rolling the service details out slowly; currently the API now includes vaccine appointment phone numbers, health system specific websites for more information on the vaccine, and other details related to obtaining an appointment (sample output in comment to reduce clutter). Further service detail information will include specific details for locations within a facility, service specific hours, email contacts, and more. All of this is already implemented in the API and will be live as soon as CMS updates their interface to include this extra data. 

Note: some of the details below are "null" - this is the reason for the VAOS direct connection in the short term. 

```
"detailed_services": [
                    {
                        "name": "COVID-19 vaccines",
                        "description_facility": null,
                        "appointment_leadin": "Your VA health care team will contact you if you're eligible to get a vaccine during this time. As the supply of vaccine increases, we'll work with our care teams to let Veterans know their options.",
                        "appointment_phones": [
                            {
                                "extension": null,
                                "label": "Main phone",
                                "number": "615-327-4751",
                                "type": "tel"
                            }
                        ],
                        "online_scheduling_available": null,
                        "referral_required": "true",
                        "walk_ins_accepted": "false",
                        "service_locations": null,
                        "path": "https://www.tennesseevalley.va.gov/services/covid-19-vaccines.asp"
                    }
                ]

```
---

---
## Tasks
- [ ] Create backend connection to Lighthouse COVID 19 data
- [ ] Add feature toggle 

## Acceptance Criteria
- [ ] Facility Locator FE has access to COVID-19 appointment data elements 
- [ ] Connection can be toggled 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
