### ISSUE TITLE
Content Release Failure Notifications sent to #vfs-engineers

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#22734]
## Issue Description
_As a CMS team engineer, I am notified in the #vfs-engineers slack channel about broken links so that I know I am responsible for triage._

---
## Tasks
- [ ] _Update slack notifications from jenkins_

## Acceptance Criteria
- [ ] _broken link notifications are delivered to #vfs-engineers slack channel_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jefflbrauer** [comment]
opening in cms team repo
