### ISSUE TITLE
[MCP] Veteran low fidelity usability conversation guide

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22743]
## Issue Description

As part of our research for the Medical Copayment enhancement to Debt Portal, we want to test low fidelity design concepts with veterans. We must create a conversation guide for approval and scheduling.

---
## Tasks
- [x] Create a conversation guide, upload it to GH
- [x] Create usability workspace
- [x] Send conversation guide to Lauryl for review / approval
- [x] Send plan to Lauren for review

## Acceptance Criteria
- [x] Conversation guide completed and linked below
- [x] Workspace linked below
- [x] Convo guide sent to Lauryl for feedback
- [x] Convo guide sent to Lauren for scheduling

**Comment by rileyorr** [comment]
I've uploaded the conversation guide to GH ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/conversation-guide.md)) and am about to send it  along with the research plan to Kristen for review prior to sending it to Lauren.

**Comment by rileyorr** [comment]
Research materials were also sent to Lauryl. We're not doing a codesign for this study, so the usability workspace task isn't necessary

**Comment by rebeccawalsh** [comment]
Feedback has been incorporated and the conversation guide is here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/conversation-guide.md

These have been sent to Lauren now!
