### ISSUE TITLE
[MCP] Veteran usability research readout

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22748]
## Issue Description
Once we complete VHA Veteran usability research, we must create a research readout of our findings.

---
## Tasks
- [x] Create a readout for Veteran usability research
- [x] Upload to GH

## Acceptance Criteria
- [x] Readout created and uploaded to GH

**Comment by rileyorr** [comment]
Synthesis is complete and the readout has been uploaded to GH! ([View the readout here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/readout.md))
