### ISSUE TITLE
[MCP] Veteran discovery research readout

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22744]
## Issue Description
Once we complete initial VHA Veteran discovery research, we must create a research readout of our findings.

---
## Tasks
- [x] Create a readout for Veteran discovery research
- [x] Upload to GH

## Acceptance Criteria
- [x] Readout created and uploaded to GH

**Comment by rebeccawalsh** [comment]
Readout can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/readout.md
