### ISSUE TITLE
[MCP] Veteran low fidelity usability research plan

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22747]
## Issue Description
We need to test our concepts with Veterans in order to better understand how they think of both benefit and copay debt.

---
## Tasks
- [x] Create a research plan for usability with Veterans 
- [x] Upload research plan to GH and link to this ticket

## Acceptance Criteria
- [x] Research plan linked in this ticket

**Comment by rileyorr** [comment]
FYI I started working on this but became blocked due to not having a final design direction post-design intent collab meeting.

**Comment by rebeccawalsh** [comment]
Research plan has been placed [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/research-plan.md), will be updated when prototype links are available.

Note: Dates have been proposed for Jun 9 - Jun 15
