### ISSUE TITLE
[Design] Notification Preferences: Create design documentation for FE

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22757]
## Background
We need to create the design documentation for the notification preferences project so that FE has all the information they need for implementation/FE build.

## Tasks 
Consider this: _if you were a designer onboarding to this product, what documentation would you want?_
- [x] Create design documentation in GH as markdown ([example here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation))
     - [x] Include prototype links
     - [x] Copy documentation
     - [x] Use case documentation
- [ ] Review with FE

**Comment by andaleliz** [comment]
Docs will live here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/notification-preferences.md

**Comment by andaleliz** [comment]
[Design specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/design-specs.md) are ready for FE.

**Comment by andaleliz** [comment]
Done!

**Comment by ajakabcin** [comment]
Documentation can be found in the [frontend folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/frontend)
