### ISSUE TITLE
[Design] Health Facilities: Create design documentation for FE

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22753]
## Background
We need to create the design documentation for the health facility project so that FE has all the information they need for implementation/FE build.

## Tasks 
Consider this: _if you were a designer onboarding to this product, what documentation would you want?_
- [ ] Create design documentation in GH as markdown ([example here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation))
     - [ ] Include invision links
     - [ ] Copy documentation
     - [ ] Use case documentation
- [ ] Review with FE

**Comment by andaleliz** [comment]
Docs will live here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/health-facilities.md

**Comment by andaleliz** [comment]
@Samara-Strauss and @ajakabcin - this is my first time creating FE dev docs for auth experience. Is this something you want to review and provide feedback on?  I have a [draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/design-specs.md) ready - just need to get content sign off on 2 messages, and add screenshots.

I reviewed with the FE team and this format, combined with the more detailed, in-context documentation in UX Pin works for them.

**Comment by ajakabcin** [comment]
I'll review it with you @andaleliz!

**Comment by Samara-Strauss** [comment]
>  Is this something you want to review and provide feedback on?

I don't need to review this, though it looks good at a glance. If you've reviewed with FE and they have the information they need, that's the most important thing!

**Comment by andaleliz** [comment]
[Design specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/design-specs.md) are ready for FE.
