### ISSUE TITLE
[FSR] Add a request number to confirmation page [usability]

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22750]
## Issue Description
In usability we found that Veterans expect a "request number" or "confirmation number" on the confirmation page of the FSR. Add these to the designs.

---
## Tasks
- [ ] Add a confirmation number to the designs and sync to UXPin
- [ ] Create a FE ticket to complete this task

## Acceptance Criteria
- [ ] UXPin updated and linked below
- [ ] FE ticket created and linked below

**Comment by LindaLi123** [comment]
There is a "confirmation number" generated from the system, once we confirm we will decide next step. 6-7

**Comment by rebeccawalsh** [comment]
@LindaLi123 Have we figured out what these confirmation numbers are?

**Comment by LindaLi123** [comment]
@rebeccawalsh I don't think so, i will follow up.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - I just stumbled upon this old ticket :) Maybe something to consider again with the team.
