### ISSUE TITLE
[FSR] Redesign resolution selection screens [usability]

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22756]
## Issue Description
In usability, we found that Veterans struggled with the resolution selection page looping through each of their debts. Do some design rework for this section, keeping in mind potential expansion of the feature to allow for secondary choices.

---
## Tasks
- [x] Create a new design for the resolution selection screen(s)
- [x] Update UXPin
- [x] Create FE ticket to implement

## Acceptance Criteria
- [x] New design in UXPin and linked to this ticket
- [x] FE ticket created and linked to this ticket

**Comment by rileyorr** [comment]
We updated the design to hopefully be a quick fix as we move towards release with the intention of revisiting when we add in 'first choice' and 'second choice' resolution selection in the future. 

- [Default resolution request screen](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138377446/simulate/no-panels?mode=i)
- [Selected resolution](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138377445/simulate/sitemap?mode=i)

@troyriser can you do a quick content spot check when you get a chance? Once it's got your approval, I'll go ahead and make the frontend ticket. Thank you!!

**Comment by troyriser** [comment]
@rileyorr 

In both instances, under 'Resolution options available' in the 2nd bulleted items with the heading 'Extended Monthly Payments', please add the article 'a' so the sentence reads, "...with either monthly offsets or a monthly payment plan."

In both instances, in the bulleted item 'Compromise:', expand the contraction 'you're' to 'you are' and add a comma after "a smaller,' so it reads, "...we can consider a smaller, one-time payment plan."

Thanks.

**Comment by rileyorr** [comment]
Thanks for looking the content over @troyriser! 

I double-checked our content style guide and [it's recommended that we use contractions](https://design.va.gov/content-style-guide/punctuation#contractions). I know there's probably exceptions, but wanted to throw that out there to make sure we wanted to expand it.

**Comment by rileyorr** [comment]
Forgot to link [the frontend ticket related to this work ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23561)

**Comment by sshein** [comment]
just passing through to say, yes, we use contractions in our style guide so should stick with you're
