### ISSUE TITLE
[MCP] Veteran discovery research sessions

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22761]
## Issue Description
Hold sessions with 8 to 10 Veterans for veteran discovery research

---
## Tasks
- [x] 8 to 10 sessions moderated
- [x] Notes scrubbed and uploaded to GH
- [x] Hold daily debrief sessions in Mural

## Acceptance Criteria
- [x] 8 to 10 session notes uploaded to GH
- [x] Debrief board exported and uploaded to GH

**Comment by rileyorr** [comment]
[I've added the notes to the GH research folder. ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/notes)

We didn't do daily debrief sessions for this study so there wasn't a board to export.
