### ISSUE TITLE
[MCP] Veteran usability sessions

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22762]
## Issue Description
Hold sessions with 8 to 10 Veterans for veteran low fidelity usability 

---
## Tasks
- [x] At least 8 sessions moderated
- [x] Notes scrubbed and uploaded to GH
- [x] Hold daily debrief sessions in Mural

## Acceptance Criteria
- [x] At least 8 session notes uploaded to GH
- [x] Debrief board exported and uploaded to GH

**Comment by rileyorr** [comment]
All the sessions I took notes for are up on GH with key takeaways added for each. (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/notes)

**Comment by rileyorr** [comment]
Becca took notes directly in our usability notes spreadsheet ([link](https://docs.google.com/spreadsheets/d/1vPSw3dJpzITntFBg29o9Yf3AwEo4AX77Hn6jiSmQaZg/edit?usp=sharing)) so those notes aren't going to make it up on GH. We also didn't create a board for our debriefs so there isn't anything to export to GH. We're good to close this ticket!
