### ISSUE TITLE
[FSR] Reassess secondary email input [usability]

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#22765]
## Issue Description
There is currently a bug where the secondary email input is not marked required, but has validation. This has been a longstanding issue and needs to be looked at again more closely (i.e. do we really need this thing???)

---
## Tasks
- [x] Appeal to #design to figure out if this secondary input is truly necessary
- [x] Document decision and create a FE ticket with the result

## Acceptance Criteria
- [x] FE ticket created with decision

**Comment by rebeccawalsh** [comment]
Discussed with the #design channel and found the secondary email is not necessary! It has been removed in the prototypes and[ here is the front end ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/24930).
