### ISSUE TITLE
Internal 686 Testing

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22766]
## Background
Reserve 5-10 points for internal 686 testing with reference to the remaining tickets.

## Tasks
- [ ] Establish standing time to meet (4pm daily)
- [x] Gather as a small group and discuss/test final workflows to investigate their viability.
- [x] 674 needs to get through RBPS (+Linda+Shane)

## Acceptance Criteria
- [x] Workflows are ready to be approved as complete or a path forward has generated other tickets
