### ISSUE TITLE
FE Implementation of COVID-19 online scheduling design (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22760]
## Issue Description
As a Veteran searching for locations offering COVID-19 vaccinations, I want to know which locations allow online scheduling through VAOS and how to learn more. 

---
## Tasks
- [ ] Implement COVID-1 iteration according to spec in [UXPin v13](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/138059694/simulate/sitemap)
- [ ] API for online scheduling `(field TBD)`
- [ ] Add data layer for online scheduling action link
- [ ] Add flipper to control environment

## Acceptance Criteria
**Assuming a Veteran has selected VA health + COVID-19 vaccines:** 
- When a Veteran selects COVID-19 vaccines as a service type, the search results contain only facilities with COVID-19 vaccines as a service
- When Service type = All VA health services, COVID service type details are not displayed
- When a Veteran selects COVID-19 vaccines as a service type. the mental health phone number is not displayed

---

When a Veteran selects COVID-19 vaccines as a service type, **if the facility offers online scheduling for COVID-19 vaccines** based on `API field (TBD)`, 
- The search result card is the same as existing but adds the following (see Rocky Mountain Regional search result example in [UXpin](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/138059694/simulate/sitemap)) 

- Online scheduling CTA, styled according to blue action link documented in [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page) (`<a className="va-action-link--blue" href="#">Call to action</a>`) appears below the directions link and above phone number
   - CTA will link to ~https://www.va.gov/health-care/schedule-view-va-appointments/~ _edited on 5/11 to the following_ -> /health-care/schedule-view-va-appointments/appointments/
- COVID-19 scheduling phone number from the API appears below the online scheduling CTA and is labeled as "or call to schedule" 
- Not available in Prod until flipper removed

**Comment by mmiddaugh** [comment]
@mpelzsherman - we've been asked to point to this endpoint: 
 /health-care/schedule-view-va-appointments/appointments/

I will update the description above but want to call your attention to the change.

**Comment by mpelzsherman** [comment]
Per @darkbushido there will be two online scheduling fields:

tmpCovidOnlineScheduling || detailedServices.onlineSchedulingAvailable
