### ISSUE TITLE
[VAMC] Updated VISN listing with updated Primary/MAIN facility(ies) for each System [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22776]
## Task
Review all playbooks and system files to map all main facilities by system
- [x] Review system lists
- [ ] Review Playbooks
- [x] Update full facility listing in VAST tracker to confirm

## Acceptance criteria
- [ ] Mapped list of Main facilities to System has been confirmed and provided to PO.
