### ISSUE TITLE
KMI Email #8: 4 segments

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#22773]
## User story

As a Veteran, spouse, caregiver, or CHAMPVA recipient, I need to understand what I need to do next, depending on my situation.

## Issue Description
We need to send out a KMI email segmented into these 4 segments:

1. The gap: People who signed up between when SLA was announced/passed and the new KMI became available
2. Welcome: People who signed up since the new KMI became available
3. OG KMI: Enrolled, eligible Veterans who haven't yet received a vaccine
4. After vaccination tips: Veterans who've received at least 1 dose of the vaccine 

Targeting week of 4.6.21.

---
## Tasks
- [x] Draft emails (Danielle)
- [x] Team review (Lauren, Patrick, Shane, Chante, Randi)
- [x] Dr. Kim review 
- [x] Incorporate Dr. Kim changes (Danielle)
- [x] JTF review
- [x] Incorporate JTF changes (Danielle)
- [x] New updates to reflect latest info (Danielle)
- [x]  Updates to reflect latest situation (Danielle)
- [x] Share content in templates (Maria and team)
- [x] Review templates (Lauren, Patrick, Danielle, Randi)
- [ ] Update per review notes (Maria and team)
- [x] J&J updates (Danielle)
- [x] Review J&J updates word doc (Randi)
- [ ] Incorporate updates and share content in templates (Maria and team)
- [ ] Review templates (Lauren, Patrick, Danielle, Randi)

## Acceptance Criteria
- [ ] Emails sent 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@lalexanderson-dsva @batemapf @shanemelliott @clantosswett @RLHecht Here's the link to the drafted emails: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/ET2sUhNO9VFJlNX715MTYLABNDqk63V0jp6GaHO_8ZLoYw?e=97Y3xD

Please let me know your thoughts - thanks!

@miabecker tagging you for awareness/preparation - thanks!

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA thanks so much! Creating the issue on our side now : ) cc @toddstanich

**Comment by clantosswett** [comment]
@DanielleThierryUSDSVA I reviewed the emails and they look good. Thanks for pulling these together!

**Comment by lalexanderson-dsva** [comment]
I reviewed the emails and think 2-4 look great. Have some suggestions on 1. LMK if you want to discuss further.

**Comment by RLHecht** [comment]
I reviewed these as well and only made a few minor copy tweaks for typos.

**Comment by DanielleThierryUSDSVA** [comment]
Latest emails [Keep me informed #8 (segmented)_04.14.21 J&J edits 2](https://app.zenhub.com/files/133843125/c021571f-1d99-4b9b-8e02-2f346d4cb2ea/download)

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA Who do you want us to test send too? You, Lauren, Patrick and Randi?

**Comment by DanielleThierryUSDSVA** [comment]
Yes, please @miabecker thank you! Also, I realized that I didn't remove the unsubscribe from the segments we'd discussed. If you didn't already do that on your end, we'll need to take that step. Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
This work is complete. Closing.

**Comment by DanielleThierryUSDSVA** [comment]
This work is complete. Closing.
