### ISSUE TITLE
 Announce appointment list preference change to screen reader

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22770]
## User Story or Problem Statement
Implement VSP recommendation (in #18583) - The `<select>` to adjust users' appointment preference must announce the change to screen readers.
![Screen Shot 2021-04-07 at 10.42.46 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/aa53470d-937b-4a38-9dc8-1d7cec923c88)

## Proposed Solution (if known)
The GOV.UK sort has a proper label as we do here, and then announces "123 results, sorted by OPTION" with OPTION being what users picked from the select menu.

## Task

- [ ] Show by type

- [ ] Date range

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_homepage_refresh feature flag

- [ ] If a user selects an appointment list view preference, Then the change is announced to screen readers

- [ ] Fix is reviewed by VSP Accessibility

## Definition of Done
- [ ] Fix and/or document decisions made.
