### ISSUE TITLE
Add hyphens to phone numbers in appointment details 

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22772]
## Description
Ensure our display of phone numbers on the appointment detail pages align with the Design System.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] DESIGN - On any appointment details page, phone numbers follow the Design System https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by laurenernest** [comment]
All phone numbers were updated in #24172. Closing ticket.

![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f7d55333-b6ad-485d-bbe3-5014e15a0443)
