### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA Indiana health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22785]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[Indiana healthcare system Legacy Site](https://www.Indiana.va.gov)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-10 Playbook locations](https://drive.google.com/drive/folders/1892HeBGmM0G6Glra2UWCbm_AKN9ZVTyX)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] 583	Richard L. Roudebush Veterans' Administration Medical Center
- [x] 6463	Crane VA Outreach Clinic
- [x] 6483	Patient Response Center
- [x] 6505	Crane VA Clinic
- [x] 583GA	Terre Haute VA Clinic
- [x] 583GC	Martinsville VA Clinic
- [x] 583GD	Indianapolis West VA Clinic
- [x] 583GE	West Lafayette VA Clinic
- [x] 583GF	Wakeman VA Clinic
- [x] 583GG	Shelbyville VA Clinic
- [x] 583QA	Monroe County VA Clinic
- [x] 583QB	Indianapolis VA Clinic
- [x] 583QC	Vigo County VA Clinic
- [x] 583QD	Indianapolis YMCA VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#22785 Create new Health Services "LIST and PLAYBOOK" for VA Indiana health care - Completed and moved to Validate.
