### ISSUE TITLE
[Content-Review] Internal Review, Proof read and correct plain language, System HS, and common sence conntent on all pages for VA Nebraska-Western Iowa health care [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22803]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[Health Service Library](https://drive.google.com/drive/folders/1_3ThJKPJ6r1U-zEM-L6iyCWsgXbAypIz)
[VISN-23 Internal Review Folder](https://drive.google.com/drive/folders/1iGnux7qcL0gJWmTklkanq4x1OTpHG22h)
[Review template for review](https://drive.google.com/drive/folders/18Oo5eoy4yn0LyTtQ3OLdNgGqN1FUof81)

## Tasks
**NEW ADDED TASKS**
_Nebraska-Western Iowa has a total of 61 System Health Services to replace.
- [ ] Update all System Health Services with HTML code from Health Service Library resource.
- [ ] Assure that intro line is correct (e.g.: "Care we provide at VA Gulf Coast health care")
**DO NOT UPDATE COVID-19 Health Services**

* Review NOT needed (Double check that updated Best Bet html has been added to pages. Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [ ] Location Listing Page 
- [ ] History    
- [ ] Internship and Fellowship 
- [ ] Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [ ] System Page 
- [ ] Health Services Listing Page (Health service on this page only)
- [ ] About us Page 
- [ ] Mission-Vision 
- [ ] Leadership Listing Page 
- [ ] Work with Us Page 
- [ ] Jobs and Careers
- [ ] Policies Page 
- [ ] Contact us 
 
* Facility Pages - review intro, Plan for your visit, if any. (DO Not review health services this is at System level only)
- [ ] 636	Omaha VA Medical Center
- [ ] 636A4	Grand Island VA Medical Center
- [ ] 636A5	Lincoln VA Clinic
- [ ] 636GA	Norfolk VA Clinic
- [ ] 636GB	North Platte VA Clinic
- [ ] 636GL	Bellevue VA Clinic
- [ ] 636GP	Shenandoah VA Clinic
- [ ] 636GQ	Holdrege VA Clinic
- [ ] 636GV	O'Neill VA Clinic

* Observe and report (Correct any spelling errors)
- [ ] Performance Page
- [ ] Make an Appointment
- [ ] Register-for-Care
- [ ] Billing
- [ ] Contact-us		
- [ ] Dav-vans
- [ ] Medical-Records
- [ ] Operational Status
- [ ] Pharmacy
- [ ] Caregiver
- [ ] Homeless
- [ ] LGBT
- [ ] Mental
- [ ] Minority
- [ ] Patient
- [ ] Returning Service member
- [ ] Suicide prevent
- [ ] Women-vet
- [ ] Campus Map
- [ ] Chaplain Services

## Acceptance Criteria
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.
