### ISSUE TITLE
Chapter 31 - Feature Gate Application Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#22813]
## Description
As launch for chapter 31 approaches, we want to make sure our feature is properly controlled for production release. Though we have feature toggles in place for static landing pages, we need to introduce a gate directly on the application page so users can't simply go to that URL directly and fill out the application. 

## Considerations
- We did a similar thing for Chapter 36 - https://github.com/department-of-veterans-affairs/vets-website/pull/16212/files

## Tasks
- [ ] Add feature toggle messaging on the application page that lets users know the feature is still being rolled out

## Acceptance Criteria
- [ ] messaging in place
- [ ] tests updated if needed
- [ ] PR submitted
