### ISSUE TITLE
Translation effort for vaccine page update on Veteran eligibility

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#22814]
## Issue Description
We updated the vaccine mini hub around the 2 groups of Veterans who are first eligible for the vaccine. We sent text to the translation team on 4/2 and need to update the Tagalog and Spanish pages with the updates.

## Tasks
- [x] Update Spanish and Tagalog pages with translated copy (Selina)
- [x] Review and publish (Randi)
- [x] Send to VHA translation team for final review (Randi)

## Acceptance Criteria
- [x] New translations on live site

**Comment by RLHecht** [comment]
@lunascoop Here are the translations that need to be put into the Spanish and Tagalog pages. Thanks!

[https://app.zenhub.com/files/133843125/2acbbc2a-fbbc-40f2-9bd9-a7e6078f01d8/download](https://app.zenhub.com/files/133843125/2acbbc2a-fbbc-40f2-9bd9-a7e6078f01d8/download)
[https://app.zenhub.com/files/133843125/284fad83-73b0-4557-8e91-f70129e06982/download](https://app.zenhub.com/files/133843125/284fad83-73b0-4557-8e91-f70129e06982/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
Thanks @lunascoop I published these updates. Sending to the VHA team now for their final review.

**Comment by RLHecht** [comment]
Closing this ticket. If we have changes from VHA translation team I'll reopen.
