### ISSUE TITLE
[VAMC] Analyze, find, and document Orphan/type facilities for VISN-23 in categories below [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22811]
## Story Description

As a Veteran I need to better understand the difference in facility types and their services, so I will be able to quickly review and decide the best facility to continue my health care journey.

## Milestone/Goal
Isolate orphan/distinct facility types and how they are used to better understand how a better page can be created to support the Veterans in their health care journeys. 

## Resources
[Health Care System - Facility Type Tracking](https://drive.google.com/drive/folders/11nVYvzYgBtgj1EP7MoLBfTQUBYDd2sVg)

## Tasks
_ Utilizing VAST list, drupal, and legacy websites; review all systems in VISN and document the following type of facilities:
- [x] Mobile
- [x] Domicillary
- [x] Community Living Center (CLC)
- [x] Other (Shelters/Domestic/Rehap/etc)
**Distinguish the following information:
- [x] Independent (Facility ID) or campus building
- [x] Services provided at facility (i.e. one service per a facility may be a waist of service to Veteran.)

**Complete review for the following facilities - Validate against VAST**

- [x] VA Black Hills health care
- [x] VA Central Iowa health care
- [x] VA Fargo health care
- [x] VA Iowa City health care
- [x] VA Minneapolis health care
- [x] VA Nebraska-Western Iowa health care
- [x] VA Sioux Falls health care
- [x] VA St Cloud health care

## Acceptance Criteria
- [x] Clear listing of orphan facilities is provided 
- [x] Service by facility is determined (new 95 health services)
