### ISSUE TITLE
[FSR] Reassess marital status

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#22821]
## Issue Description
_We received feedback during the FSR's usability study that participants didn't know why their marital status/spouse information was necessary. Additionally, there was concern about needing to specify their marital status as 'divorced', 'separated', etc. This specification was added in an attempt to provide more context about the Veteran's financial situation, but the original form only asks if they're 'married' or 'not married'. We need to reevaluate this content._

---
## Tasks
- [x] _Update the marital status options to 'married' and 'not married'_
- [x] _Work with the content team on 'Why do we need to know this' content_

## Acceptance Criteria
- [x] _Updated UXPin prototype has been linked in this ticket_
- [x] _A ticket has been created for the frontend team to implement this work_

**Comment by troyriser** [comment]
For ease of reference, current 'why we need to know this' content consists of the following: 

"We want to make sure we fully understand your financial situation. If you’re married, we also need to understand your spouse’s financial situation. This helps us make the best decision on your request.” 

We could reinforce this point by inserting this or more specifically tailored content in the form itself, in the Household Income, Household Assets, and Household Expenses steps.

**Comment by rileyorr** [comment]
> For ease of reference, current 'why we need to know this' content consists of the following:
>
> "We want to make sure we fully understand your financial situation. If you’re married, we also need to understand your spouse’s financial situation. This helps us make the best decision on your request.”

Ah, yeah that content on the intro page! This ticket, along with a few others, revolves around more specific content within the form itself. We're looking at [the marital status selection page](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136159519/simulate/no-panels?mode=i) and possibly the following pages revolving around the Veteran providing their spouse's information. 

I think that content you shared is definitely a good start! I updated the marital status screens and made a couple versions of different ways we could display that content. People generally click on those 'additional info' components, but it may be beneficial to show that content upfront. Are there any adjustments you'd recommend based on that context? 

**Content upfront**
<img width="677" alt="Screen Shot 2021-04-07 at 3 22 54 PM" src="https://user-images.githubusercontent.com/46329147/113922473-5112e680-97b5-11eb-9595-84acd0d98481.png">

**Content inside the 'additional info' component**
<img width="677" alt="Screen Shot 2021-04-07 at 3 23 04 PM" src="https://user-images.githubusercontent.com/46329147/113922475-51ab7d00-97b5-11eb-9ce1-e39b20866aba.png">

@rebeccawalsh what do you think of those two? In the first option, I'm conflicted on whether or not the 'We want to make sure we fully understand your financial situation.' is necessary. For some reason it reads better to me when inside the 'additional info' component.

**Comment by rebeccawalsh** [comment]
@rileyorr I prefer the additional information component, personally. Mostly because it seems like most people don't *need* further context. I would change the link text to: "Why does my marital status matter?" though.

I wonder if including "household" in the first statement would also help -- "We want to make sure we understand your household's financial situation."?

**Comment by rileyorr** [comment]
@rebeccawalsh yeah I agree with that! @troyriser and/or @peggygannon could I get a quick content spot check before creating a frontend ticket to double check that we're aligned with the content style guide? [The design can be found in our UXPin prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138206407/comment/sitemap?mode=i). Thank you!

**Comment by troyriser** [comment]
@rileyorr Received and acknowledged. Looking now.

**Comment by rileyorr** [comment]
@troyriser thank you for that recommendation! I just want to double check that the recommendation aligns with plain language guidelines. I'll defer to your judgment since I'm not an expert in that area, but I wonder if 'allows' over 'helps' and using 'regarding' will be widely understood by our audience. Let me know what you think!

**Comment by troyriser** [comment]
@rileyorr  I think 'allows' and 'helps' are interchangeable and both would fall into plain language guidelines easily enough. Regarding 'regarding', I'm a sucker for alliteration (regarding...request) since it aids readability. Besides, using the preposition 'on' as in 'on your request' is syntactically suspect since you're missing the verb form as noun gerund; e.g., 'deciding on your request'. 

Sorry, I get a little carried away when I'm in my own wheelhouse. The short version is yes, 'regarding' is safely within plain language guidelines.

**Comment by rileyorr** [comment]
Awesome, thank you for that background info @troyriser! It's helpful for me as someone who advocates for plain language but may not understand all the nuances that get us there :) Appreciate it! 

[I added a ticket to the backlog for frontend implementation.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23170)
