### ISSUE TITLE
Quick List of Topics for Formlet Usability

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22829]
## Background
We want to make a short list of what we want to test for the usability formlet; what workflows should be removed from the first version if any, hot topics or pain points in functionality, etc.

## Considerations
This will help inform the Research Plan and Conversation Guide and make sure we stay tightly scoped.

## Tasks
- [x] Document a list of items for discussion to be inserted into he Research plan
- [ ] [Stretch] Scaffold out the Research plan

## Acceptance Criteria
- [ ] List of research objectives obtained and/or research plan started

**Comment by sporeboy** [comment]
21-686c Workflows for Formlet Consideration:

Remove Scenarios
- Divorce (spouse)
- Death of dependent (spouse, child or parent)
- Child marries (child)
- Child stopped attending school (child)

Remove stepchild was deemed “too long” for a formlet

**Comment by sporeboy** [comment]
Started research plan here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/formlet-usability
