### ISSUE TITLE
Midpoint Review Booz Allen Education Applications - VRRAP

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#22836]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure VSP reviewers have appropriate access to secured applications.
- [x] VSP: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to VSP feedback tickets.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md)
- Link to [prototype](https://bahdigital.invisionapp.com/share/RMIAGJTSDEA)
- Link to [content brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/design/content-doc.md)  
- Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or elsewhere) 
- Link to research plan and conversation guide - N/A, no usability testing for this effort
- Link to regression test plan - N/A, new form.
- Link to [test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/1617) for QA practice area review

## Meeting attendees from requesting team
- Product Manager (required): Darrell Neel / Will McCormack
- DEPO Product lead (recommended): Matt Self
- DEPO Design lead (recommended): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Michael Delli-Gatti, Jen Jones, Amy Knox, Dan Shawkey, Adam Sontag, Emma Waters
- Content, IA, accessibility, and QA specialists (if applicable): included above

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [ X ] Yes
- [ ] No
 
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **First available: 4/12, 3:30 pm OR 4/13, 11am**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by amyknox** [comment]
Assign Shira & Andrea Hewitt when this becomes relevant

**Comment by amyknox** [comment]
FYI - 
1. I'm unable to tag @vsp-product-support-members in slack so just tagged @shiragoodman & @andreahewitt-odd  - LMK if there are others I should be making aware of this. 
2. This review is for VRRAP, please expedite!  Thank you!!

**Comment by mnorthuis** [comment]
There is no IA feedback, but I do have one small question.  Regarding the button on the confirmation page for "Go back to VA.gov"...wondering if it would be more helpful to return them to the static page for the program, so they can review any additional information rather than the home page?

**Comment by amyknox** [comment]
@mnorthuis - thanks for the input. That's an interesting idea. I'd like to check and see where other forms direct applicants so we're using best practices.  If there's not one established, maybe we could add a code snippet that would detect if they traveled through that program page and, if so, return them there.  That could be helpful. We're pushing to get this form out ASAP but will incorporate these ideas into our post-launch idea repository.

**Comment by dneel-bah** [comment]
All attached issues have been addressed and closed.  Closing this issue.
