### ISSUE TITLE
[FSR] 'Your dependents' "Why do we need to know this?" additional info

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#22833]
## Issue Description
_The FSR's usability study highlighted that Veterans don't know why they need to include information about their dependents._

---
## Tasks
- [x] _Work with the content team on 'Why do we need to know this' content_

## Acceptance Criteria
- [x] _Content has been either added to GH or the UXPin prototype and linked in this ticket_
- [x] _A ticket for frontend implementation has been created and linked in this ticket_

**Comment by troyriser** [comment]
@leahkeeler @LindaLi123 @rebeccawalsh @rileyorr 

Need to Know explanatory draft:

"_Why does VA need all this information?_

We want to make sure we fully understand your financial situation. If you’re married, we ask for details about your spouse’s finances. If you have dependents, we ask for number of dependents as well as their ages. Knowing this kind of information helps us to make a more informed decision regarding your request."

Please note Andre has directed that I **not** have direct interaction with the Content Team, at the client's request. The client doesn't want to muddy the waters regarding content origination, so it's incumbent on someone other than myself to present this Need to Know explanatory draft to the client for review.

**Comment by LindaLi123** [comment]
@rebeccawalsh @rileyorr Does Peggy need to review this?

**Comment by rileyorr** [comment]
@troyriser ty for providing that content! I compared it with the content we have in the 'spouse information' section to make sure our voice is consistent throughout the form. I've attached a screenshot for reference.

![Screen Shot 2021-06-14 at 10.44.52 AM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/e89da014-2f5a-49fa-bd9a-eb2caabd5f9c)

Based on the existing content, I had a couple thoughts about the drafted content:

> Why does VA need all this information?

- What about something like, "Why do I need to include my dependents?"
- If we want to stick with the original direction I think it should read, "Why do we need all this information?" in accordance with the ['we, us, you' content style guidelines](https://design.va.gov/content-style-guide/we-us-you). 

> We want to make sure we fully understand your financial situation. If you’re married, we ask for details about your spouse’s finances. If you have dependents, we ask for number of dependents as well as their ages. Knowing this kind of information helps us to make a more informed decision regarding your request.

- Since this page will just be about dependents, can we nix the "If you’re married, we ask for details about your spouse’s finances." since it's unrelated to the question? 

Here's a screenshot of the dependent screen for your reference: 

![Screen Shot 2021-06-14 at 11.00.03 AM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/c52b677e-55b9-4ef4-98c3-e50607fdfd87)

Let me know what you think!

**Comment by troyriser** [comment]
@rileyorr I've incorporated your changes and have no issue with any of them. Good catch on the pronouns, btw. After decades of writing in a more formalized style, it's been hard for me to adapt to the folksier manner dictated by Plain Language and other government style guides. Based on your changes, this is what I've got:

"_Why do I need to include my dependents? _

We want to make sure we fully understand your financial situation. If you have dependents, we ask for number of dependents as well as their ages. This allows us to make a more informed decision regarding your request."

**Comment by rileyorr** [comment]
@troyriser no worries at all! Happy to collaborate!

@LindaLi123 
- I've updated the UXPin to match the provided content ([link](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/139219203/simulate/sitemap?mode=i))
- I've added a ticket for frontend implementation ([link](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26014))

Moving this over to validate!
