### ISSUE TITLE
[FSR] Provide content to ease Veterans' worries about providing real estate, vehicles, and other assets

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#22842]
## Issue Description
_The FSR's usability study confirmed that Veterans are extremely worried about providing information about their assets such as real estate, vehicles, and other assets. We need to add empathetic content to these parts of the form to ease Veterans' concerns that VA will repossess their assets_

---
## Tasks
**Real estate**
- [x] _Verify if real estate assets needed include assets with mortgages/loans or fully owned properties_
- [x] _Provide content explaining why these assets are necessary and reiterate that VA will not ask Veterans to sell their properties to pay off their debt_

**Vehicles**
- [x] _Provide content explaining why these assets are necessary and reiterate that VA will not ask Veterans to sell their vehicles to pay off their debt_

**Other assets**
- [x] _Provide content providing more guidance as to what types of assets qualify to be included_ 
## Acceptance Criteria
- [x] _Content has been either added to GH or the UXPin prototype and linked in this ticket_
- [x] _A ticket for frontend implementation has been created and linked in this ticket_

**Comment by rebeccawalsh** [comment]
I've sent an email to Jill to see about how the real estate "asset" is used.

**Comment by rebeccawalsh** [comment]
@LindaLi123 We're still waiting on Jill and team to answer the question. This is blocked until that can be answered (Jill's latest response: June 1 @ 4:11pm est)

**Comment by LindaLi123** [comment]
@rebeccawalsh Jill responded 6/14 and confirmed your questions

**Comment by LindaLi123** [comment]
@troyriser Hello Troy would you be able to help out with the content portion today so we can close this ticket?

**Comment by troyriser** [comment]
@LindaLi123 @rebeccawalsh I would be glad to help out with the content portion. I'll need to familiarize myself with the particulars.  Just to confirm, this empathetic content will encompass all asset-related information; e.g. real estate, vehicles, and other assets, yes? So we're talking about 2-3 sentences intended to allay their concerns. I'll come up with a draft and fly it by Riley & Becca. Give me about a half-hour. It'll probably be rough but can serve as a starting point.

**Comment by rileyorr** [comment]
@troyriser real estate, vehicles, and other assets are three separate pages within the form, so we'll need content for each page. I probably should have written three tickets - oops! 

Here are the UXPin pages for reference:
- [Real estate](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410685/simulate/sitemap?mode=i)
- [Vehicles](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410290/simulate/sitemap?mode=i)
- [Other assets](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134410291/simulate/sitemap?mode=i) 

This content will be similar to the 'additional information' component content on the ticket we wrapped up yesterday. I'll also draft some content so we can collab!

**Comment by troyriser** [comment]
@rileyorr @rebeccawalsh I asked this in our Slack convo but want to ask again because it's crucial: Does the asset information entered by the veteran in Form 5655 get forwarded to Treasury if the veteran falls behind on their debt and it goes to collection?  If so, we need to be very nuanced on how we approach the content. If not, then we can just allay their concerns outright.

**Comment by troyriser** [comment]
@rebeccawalsh @rileyorr @LindaLi123 

Try these:

_Why do I need to enter my real estate assets?_

We want to make sure we fully understand your financial situation. We ask for details about your real estate assets because it allows us to make a more informed decision regarding your request. 

_Why do I need to enter details about my car and other vehicles I own?_

We ask for vehicle details such as type, make, model, year, and estimated value because this allows us to make a more informed decision regarding your request.

_Why do I need to enter details about items of value other than real estate and vehicles?_

We ask for details about items of value such as jewelry and art because it gives us a picture of your financial situation and allows us to make a more informed decision regarding your request.

**Comment by rileyorr** [comment]
@troyriser this is awesome, thank you! I've had writers block trying to draft this content lol. 

What do you think about this addition based on our research that indicates Veterans are worried VA is going to repossess their homes and vehicles:

**Real estate:**
> We want to make sure we fully understand your financial situation. We ask for details about your real estate assets because it allows us to make a more informed decision regarding your request.
>
> **Note:** We won’t take collection action against real estate you own in order to resolve your debt.  

**Vehicles:**
>We ask for vehicle details such as type, make, model, year, and estimated value because this allows us to make a more informed decision regarding your request.
>
>**Note:** We won’t take collection action against your cars or other vehicles in order to resolve your debt.

I don't think my content suggestions align with plain language, so if you agree with the additions feel free to make any adjustments!

I also think DMC should review this content prior to it being added to the frontend. Once we're satisfied with our draft I'll go ahead and update the UXPin and send an email for them to review.

**Comment by troyriser** [comment]
The debt collection disclaimer Notes look fine to me. Plain Language guidance says to be concise and these are concise. One thing, though: I don't know it's necessary to separate the collection disclaimers with the 'Note:' tag. I recommend incorporating them into the body of the paragraph. That's just a suggestion. It's fine either way.

**Comment by troyriser** [comment]
@rileyorr Sorry, I think I just broadcast this to everyone. Here it is again, Riley, in case you missed it. The debt collection disclaimer Notes look fine to me. Plain Language guidance says to be concise and these are concise. One thing, though: I don't know it's necessary to separate the collection disclaimers with the 'Note:' tag. I recommend incorporating them into the body of the paragraph. That's just a suggestion. It's fine either way.

**Comment by rileyorr** [comment]
@troyriser no worries! I get emails for all responses to GH tickets I'm assigned to :) 

I made some more adjustments to the vehicles content given that we ask if Veterans own cars/vehicles on one page and the details of their vehicles on the next. I've attached screenshots of what the content looks like within the UI. I also updated the question to, "Why do I need to provide this information" because I felt that was concise and made sense within the context of each page. Let me know what you think!

**Real estate**

Page 1 and page 2 have the same content

**NOTE:** on page 1 I added helper text below the question 'Do you own any real estate' to indicate that real estate with mortgage payments should be included. Let me know if I should make adjustments to that sentence. 
![Screen Shot 2021-06-15 at 3.34.37 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/766b2019-8e03-4296-8577-2e8118b65267)

**Cars/Vehicles**

Page 1 - removed the 'make, model, etc.' content because Veterans don't need to provide that info on this screen. Page 2 has the content including make, model, etc.
![Screen Shot 2021-06-15 at 3.34.50 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/09efe0e3-bc2e-49dd-ba82-c114f20ae9a5)

**Additional assets**
Page 1 and page 2 have the same content
![Screen Shot 2021-06-15 at 3.35.05 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/1c211aec-65cf-4cad-8b04-1474d9b5b9b7)

**Comment by troyriser** [comment]
@rileyorr You did a marvelous job. Love collaborating with you and the team on content-related issues. We complement each other nicely, I think.

**Comment by rileyorr** [comment]
Awesome, thanks! Appreciate the collaboration and the openness to each other's suggestions!

@LindaLi123 

The content changes are reflected within the UXPin:
- Real estate:
   - [Page 1](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691645/simulate/sitemap?mode=i)
   - [Page 2](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139699198/simulate/sitemap?mode=i) 
- Vehicles:
   - [Page 1](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691649/simulate/sitemap?mode=i)
   - [Page 2](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691648/simulate/sitemap?mode=i)
- Other assets:
   - [Page 1](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691651/simulate/sitemap?mode=i)
   - [Page 2](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691650/simulate/sitemap?mode=i)

I've also added [a ticket for frontend implementation](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26097). I'm going to send an email to the DMC with screenshots of this modified content as well; I'll CC you on the email. We should be good to close this ticket, so I'm moving it to validate.
