### ISSUE TITLE
[FSR] Help Veterans understand why they should provide as many expenses as apply

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#22847]
## Issue Description
_The FSR's usability study uncovered that many Veterans perceive providing expenses as having a negative impact on their request, when it's in fact the opposite. We need to help Veterans understand why they should provide as many expenses as apply to their financial situation so their information is as accurate as possible._

---
## Tasks
- [x] _Work with the content team to provide content that urges Veterans to provide all their expenses_
- [x] _Provide more examples of common living expenses in the initial question and dropdown as applicable_

## Acceptance Criteria
- [x] _The updated content is either uploaded to GH or updated in the UXPin prototype_
- [x] _A ticket is created for frontend implementation_

**Comment by rileyorr** [comment]
Updates on this work: 

- Becca and I collaborated on how best we could notify Veterans that including their expenses helps their request. Given that the chapter is broken up into multiple pages, our proposal is to add another page at the beginning of the chapter outlining what expenses will be asked and alerting Veterans that providing all these expenses helps the DMC understand their financial situation. See attached screenshot: 

![Screen Shot 2021-06-25 at 1.42.42 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/87bed6a7-7c6a-4bc2-bb6d-26608fba0360)

- We explored multiple ways to write this alert with an emphasis on how fully completing this section _helps_ their request. See attached screenshot: 

![Screen Shot 2021-06-25 at 1.41.41 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/057b0347-e82f-43a5-90cc-792e142bae59)

- We looped Troy in with our ideas and received the following feedback: 

> Try this: "Please include all of your expenses.
> Your expenses are subtracted from your income. This allows us to better understand your financial situation and make a more informed decision regarding your request."

I'm going to add a follow-up comment with an updated version based on Troy's feedback so all work is captured in this ticket.

**Comment by rileyorr** [comment]
@troyriser thank you for the feedback as always! I've created a version of the prototype with your content but also took your concept and iterated on it. Here's my thinking:

The alert became quite large when I added the suggested content to the UI. This is already a content-heavy page, and I think the odds of people reading everything thoroughly are slim to none. Since our goal is to help Veterans understand why including all their expenses helps them, that should be the highlight of the alert's content. Here's a screenshot of the alert within the UI:
![Screen Shot 2021-06-25 at 1.42.42 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/3cceed15-1a30-4a69-a895-f63481a98989)

I played around with incorporating the concepts of your alert into one that's more condensed and highlights how including all expenses can help their request in the alert's bold header: 
![Screen Shot 2021-06-25 at 2.07.23 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/03a29394-f4ea-4361-a83c-c4c0e96c206b)
I think this incorporates your point about the DMC taking a holistic view when reviewing requests while telling the Veteran that providing all their expenses shows DMC why they need financial assistance. 
To @rebeccawalsh's point, not all expenses included will be deducted from their income. Since every situation is unique, DMC manually reviews the expenses and may not consider all of them to be applicable for financial assistance (for example, a $400 monthly charge for salon visits). 

Let me know what you think and additional feedback you have!

**Comment by troyriser** [comment]
@rileyorr The wording of the bolded heading is an elegant solution to the space problem. The only recommendation I would make would be to replace "may be subtracted from your income" with "...are subtracted from your income" since--as I understand it--these calculations are performed automatically as part of the form's functionality. 'May be' is a conditional, denoting something that might or might not happen, depending.

**Comment by troyriser** [comment]
@rileyorr The wording of the bolded heading is an elegant solution to the space problem. The only recommendation I would make would be to replace "may be subtracted from your income" with "...are subtracted from your income" since--as I understand it--these calculations are performed automatically as part of the form's functionality. 'May be' is a conditional, denoting something that might or might not happen, depending.

**Comment by troyriser** [comment]
@rileyorr Sorry, I unintentionally closed this.

**Comment by rileyorr** [comment]
No worries @troyriser! Thanks for the feedback.

UXPin links:
- [Household expenses intro page](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/140008855/simulate/sitemap?mode=i)
- [Updated prompt on the 'add additional expenses' list loop screen](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691662/simulate/sitemap?mode=i)

We'll go ahead and send the expenses intro page over to Jill for review.

Frontend tickets:
- [Add the intro page](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26680) - Blocked until DMC team approves the content
- [Update the list loop page](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26681)

Moving this over to validate!
