### ISSUE TITLE
Build an Alert Box web component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#22844]
## Issue Description
Build an Alert Box web component to pilot since alert boxes are used in a lot of places. 

---
## Tasks
- [ ] Build alert box web component
- [ ] Set up on staging for staging review 

## Acceptance Criteria
- [ ] Alert box web component on staging 
- [ ] Alert box goes through staging review
- [ ] Any a11y issues identified in staging review are addressed
- [ ] Alert box web component on prod and announced

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
