### ISSUE TITLE
SPRINT 45 PRIORITIES

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#22858]
## :fire: Sprint 45 Priorities

1. ~~Work with Lighthouse team on new logic to improve text search matching~~
2. ~~Determine which forms will receive "When to Use" text treatment, and possibly have related form info added #22857~~
3. ~~Give copydeck to Content for them to draft "When to Use" text for forms referenced in 5 to present to SMEs~~
4. ~~Resolve at least one 508 Issue in the backlog~~
5. ~~Enter Medallia requests for Find a VA Form and Find a Yellow Ribbon School -- see guidance at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/readme.md~~
6. ~~Request redirects for Spanish detail pages to Find a Form search page see #22817~~
7. ~~Request for LH to pull the correct language attribute from the CMS~~
8. :question: current status - (Unplanned) PDF bug fix for Discharge Upgrade Wizard - Kelson just approved; deploy failed (flaky unit test).  By 5 PM today or tomorrow.
9. 508 Build passed; should be in tomorrow (Language-related).

#### Zach
- [x] Find a VA Form: Provide current search term transformation logic to Mark and Nichole  and work with Mark on implementing new weighting/ranking logic. #22866
- [x] Diagram/describe Find a Form
- [ ] Review Cassandra's design changes linked in GH issue #21513 and estimate time to implement - **move to later sprint; design changes are not yet approved.**

#### Cassandra
- [X] Design UI consistency #22882
- [x] Improve instruction for entering search term #20257 - Decided this was not needed
 also please see related 508 cognition issues
 https://github.com/department-of-veterans-affairs/va.gov-team/issues/18442
 https://github.com/department-of-veterans-affairs/va.gov-team/issues/3556
 https://github.com/department-of-veterans-affairs/va.gov-team/issues/13819
 https://github.com/department-of-veterans-affairs/va.gov-team/issues/18395

#### John
- [X] Find a VA Form: Create Word copydecks for SME review/input #22857
- [X] Find a Form monthly Stakeholder meeting with VA\
- ❓ - Clarification -- default boilerplate helpful links vs. those in the copydeck - DECISION - Use the ones in the copydeck.  Include in the Word docs for the Content team.

#### Marci
- [x] Find a VA Form: Provide match scoring logic to Lighthouse team #22866
- [X] Find a Form monthly Stakeholder meeting with VA; pull together data
- [X] Request Medallia for Find a VA Form #22820 - confirm what the implementation looks like.
- [X] Request redirects for Spanish detail pages to Find a Form search page see #22817

#### Marci
- [X] Yellow Ribbon: Request Medallia survey -- request - #23208

###  🗨️  Discussion Topics/Grooming 
- [ ] Logic for handling non-ranked form searches:
     - What should be shown when someone searches for a form or term that doesn't appear in the top 100 we've cross-referenced to forms?
     - If, by default, the search sorts results by popularity, what should the behavior be in the case of a term that doesn't have popular forms associated?
- [ ] Decide near-term direction for search matching improvements (are we moving forward with/without LH and CMS team and then circling back when the CMS team has bandwidth, or are we going to take what we learn in our POC and use that to inform a collaborative effort)?
- [ ]  Next steps for implementing the Find a VA Form search UI changes Cassandra mocked up
- [ ] Next steps for other Unauth form design work
- [ ] How to get design changes escalated to a higher level (style guide, design system) for of VSA teams to use

### Notes
- Medallia - thumbs up/thumbs down is a custom approach for Medallia.  4 months before they get to that
