### ISSUE TITLE
[FSR] Break credit cards out from the installment contracts page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#22855]
## Issue Description
_The FSR's usability study revealed that Veterans struggled to input their credit card debt information for multiple reasons:_
- They preferred providing a sum total for all their credit cards rather than list out each individual one
- Many of the input fields didn't seem to apply for credit cards such as 'original contract or debt amount' and 'date debt began' because they pay off their credit cards monthly

---
## Tasks
- [ ] _Reevaluate the installment contracts page design and break out credit cards into a separate page_

## Acceptance Criteria
- [ ] _The UXPin prototype has been updated with the new credit card design_
- [ ] _A ticket has been created for frontend implementation_

**Comment by OptionSelect** [comment]
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/22855
Link to previous CC Bill breakout ticket

**Comment by josephrlee** [comment]
Closing this out as the work was done in #46668. 

cc: @denisecoveyduc @mgleo @charlottecesana @dhill802 @Tom-Davis
