### ISSUE TITLE
Add heading to how to cancel message in appointment details

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22865]
## Description
As VSP, I would like to add a heading to the how to cancel message box to draw attention to the information

---
## Tasks
- [ ] CC confirmed

- [ ] VVC confirmed

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh ` feature flag
- [ ] CONTENT - Heading copy matches (heading is H2)
> Need to make changes?

- [ ] DESIGN - Designs match the specs
- CC https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/a/qeVO2ek#Inspector
![Screen_Shot_2021-04-07_at_10_54_50_AM.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/b8821fd3-490a-482c-8e86-3e6032a4ea92)

- VVC https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/a/7yaKQy8
![Screen_Shot_2021-04-07_at_10_54_41_AM.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/11c2d81d-d79e-4581-9900-edaf42bf923c)

## Definition of Done
- [ ] All acceptance criteria are met
