### ISSUE TITLE
TUD Design Audit

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#22879]
## Issue Description
UX to review current state of Dashboard to note design or content that could be improved for user experience

---
## Tasks
- [x] Review getting started page (home page)
- [x] Review documentation page (wording consistent with rest of dashboard)
- [x] Review issues page
- [x] Review table for design and content consistency
- [x] Review modal for design and content consistency

## Acceptance Criteria
- [x] Review with Front End for possible tickets.
