### ISSUE TITLE
Fail Jenkins build if GitHub status failing

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#22870]
## Issue Description
vets-api is moving to GH Actions. Linting/Security checks have been merged in and run via GH actions.  We'd like to prevent the daily build from going out if one of the checks are failing. Jenkins doesn't currently check the status in GitHub. We need to add a step to the build to check the status via GH's API in order to move CI to GH Actions and still integrate with our current BRD

---
## Tasks
- [x] Investigate if this is needed. The [Jenkins autodeploy](http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-api/) has a "Wait for a valid build status" step (1-2 hour time box)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ericboehs** [comment]
Once we're on GHA, I believe we can remove the rubocop junit formatter gem and associated lines of code.

**Comment by ericboehs** [comment]
Turns out it's not needed as it was already implemented.
