### ISSUE TITLE
[Design] Preferred Medical Facilities: Create static content to support new preferred medical facilities feature

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22886]
## Background
As discussed in the [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22741#issuecomment-815140756) of #22741 we need to create a static content page or a resources and support page to accompany the launch of the project.

## Tasks
- [ ] Determine if we need a static content page and/or resources and support page
- [ ] Design the page
- [ ] Work with @ajakabcin to create implementation tickets

**Comment by andaleliz** [comment]
Moving this to the backlog and out of the ready column - we can't do this until VAOS usability testing is complete, and possibly even after the FE is built.

I suspect what we'll end up doing is a resources and support page, and I think we'd create that along w/ any product guide updates once we're more confident about how everything works.

**Comment by andaleliz** [comment]
I don't think we'll do this work, but added MHV discovery as a blocker in case we learn something that suggests we do need this section of profile. If we do, we'll still need this ticket.

**Comment by andaleliz** [comment]
Closing this out, per Kevin we are putting this work on ice.
