### ISSUE TITLE
Design intent - Decision Tools - Sitewide Search UI Consistency

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#22885]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Link to this issue once created in #design in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [ ] VSP: Create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to VSP feedback tickets.
- [ ] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/search-ui-consistency/product-outline.md)
- Sketches 
[Search tools - UI consistency mobile](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4)
[Search tools - UI consistency desktop](https://vsateams.invisionapp.com/share/SD10IE31CENR)

## Meeting attendees from requesting team
- Designer(s) Cassandra Allen, Megan Gayle
- Product Manager (required): Marci McGuire, Brian Lloyd, Denise Coveyduc, Michelle Middaugh
- DEPO Product Lead (recommended): John Hashimoto
- DEPO Design lead (recommended): Ryan Thurlwell
- Content, IA, accessibility, and QA specialists (if applicable):  Josh Kim, Trevor Pierce
- Other stakeholders you want to invite (if applicable) Crystabel Reiter

## Scheduling
Would you like this review to be asynchronous? Please refer to the Design Intent guidance for the difference between a synchronous meeting and an asynchronous review.

- [ ] Yes
- [X] No

What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **Tuesday, April 20 at 11:30 AM ET**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @MarciMcGuireGCIO  - assuming you're still working on completing the details of this ticket?

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman yes, I am.  I'll Slack you when I have everything together for it.  I just wanted to get it started.  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 @mgleo @lildziner please add links to your Sketch files and any other design artifacts to this ticket by EOD this Thursday in preparation for the design intent review.  Thanks!

**Comment by allison0034** [comment]
@MarciMcGuireGCIO we currently do not have an opening Tuesday April 20 at 2:30. For that date we have 11 or 11:30.

**Comment by MarciMcGuireGCIO** [comment]
I'm sorry; I was looking at the design office hours window and not the Collab Cycle window.  Let me see if I can find another slot that works.  With so many designers and teams involved, it's a challenge.

**Comment by MarciMcGuireGCIO** [comment]
Please schedule us for 11:30 on 4/20.  Trying to shift some things around.  Thank you! 😄

**Comment by allison0034** [comment]
@MarciMcGuireGCIO this has been scheduled for 4/20 at 11:30.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman @allison0034 we just realized this overlaps with ToT, so we're hoping we can get through it in 30 min since several of us have to present.  Thanks!

**Comment by callen2563** [comment]
Here are the mock ups we would like to discuss in the design intent meeting:

[Search tools - UI consistency mobile](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4)
[Search tools - UI consistency desktop](https://vsateams.invisionapp.com/share/SD10IE31CENR)

**Comment by MarciMcGuireGCIO** [comment]
Thank you!  Just FYI, I had failed to include the changes you were making for Resources & Support.  I updated the meeting invite so Brian can see those as well.  Thank you for turning this around so quickly!

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 I included the links to the inVision mockups in the details above.  Please add the questions you'd like to get answered at the meeting once you and Megan have a chance to compile.  Thanks!

**Comment by mgleo** [comment]
Here are the questions that @callen2563 and I have for the Design Intent meeting. 
@CrystabelReiter I hope you are able to make the meeting on Tuesday but if not, feel free to share any feedback on this ticket.

**Inconsistent styles on VA.gov:** 

- Header links on [benefits pages](https://www.va.gov/pension/eligibility/) are not currently underlined. Josh has recommended that links should be underlined. Is there a sitewide plan to add underlined links throughout the site so it will be more consistent?
- Is this the correct style for body copy: size: 16px, color: #323A45 (gray-dark)?
- Are there examples of the green action link currently on VA.gov? The focus/hover styles currently appear outside of the grid.
<img width="436" alt="Screen Shot 2021-04-16 at 3 57 53 PM" src="https://user-images.githubusercontent.com/5553542/115077734-89f53e80-9ecc-11eb-99f8-a8a35346a7c0.png">


**Inconsistent width for content area:** 

- Any insights on the correct content width? On Sketch desktop templates: it is 648px for one column pages and 732px on two column pages with a left nav. On VA.gov, it is 700px.

**Global search right rail:** 

- Most users are currently prevented from seeing the right rail because of how the media queries were set up. Should we adjust the media queries, update the typeface, and keep the right rail for now? Or take it down until another solution is found through 'surfacing other search tools' initiative?

**Resources & Support on mobile**

- R+S mobile presents a lack of consistency in collapsing the search bar into a menu on mobile. Josh has given his comments on the need to update this based on accessibility but we would love to get your thoughts on the proposed design solution.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @mgleo and @callen2563 ! Looking forward to the meeting!

**Comment by CrystabelReiter** [comment]
@mgleo @callen2563 I am not going to be able to make it to the design intent meeting. 
I'll write my answers in this ticket.

Inconsistent styles on VA.gov:

- Header links on benefits pages are not currently underlined. Josh has recommended that links should be underlined. Is there a sitewide plan to add underlined links throughout the site so it will be more consistent?
**Josh's recommendation is correct. We are now striving to be consistent with underlining all links for accessibility reasons. We updated all link text styles in the sketch library to be underlined. There is currently no sitewide plan to underline all links.**
- Is this the correct style for body copy: size: 16px, color: #323A45 (gray-dark)?
**Yes, that is the current default body text style in the sketch library**
- Are there examples of the green action link currently on VA.gov? The focus/hover styles currently appear outside of the grid.
**There is currently no examples of green action links currently on VA.gov. The design system engineers are currently working on fixing the hover styles appearing outside of the grid.**

Inconsistent width for content area:

- Any insights on the correct content width? On Sketch desktop templates: it is 648px for one column pages and 732px on two column pages with a left nav. On VA.gov, it is 700px.
**I would follow what's on VA.gov, I'll update the sketch desktop templates**

**Comment by MarciMcGuireGCIO** [comment]
Noting here that the proposed dynamic title change (adding the words "search results" after "Find a VA Form" when the results are being displayed) is not currently feasible in Find a VA Form because the title comes from CMS and has no awareness of page state (search state vs. result state).
