### ISSUE TITLE
[VAMC] VISN-15: VA Heartland Network - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22918]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-8](https://drive.google.com/drive/folders/1YuZ_PJFIEhmOuMhj55oh0lT3aL1uy6Tg)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Columbia Missouri health care
- [ ] VA Eastern Kansas health care
- [ ] VA Kansas City health care
- [ ] VA Marion health care
- [ ] VA Poplar Bluff health care
- [ ] VA St Louis health care
- [ ] VA Wichita health care

Facilities include for System:
VA Columbia Missouri health care
- [ ] vha_589A4	Harry S. Truman Memorial Veterans' Hospital
- [ ] vha_589G8	Jefferson City VA Clinic
- [ ] vha_589GE	Kirksville VA Clinic
- [ ] vha_589GH	Lake of the Ozarks VA Clinic
- [ ] vha_589GX	Mexico VA Clinic
- [ ] vha_589GY	St. James VA Clinic
- [ ] vha_589JA	Sedalia VA Clinic
- [ ] vha_589JD	Marshfield VA Clinic
- [ ] vha_589GF	Waynesville VA Clinic (Formerly Fort Leonard Wood VA Clinic)

VA Eastern Kansas health care
- [ ] vha_589A5	Colmery-O'Neil Veterans' Administration Medical Center
- [ ] vha_589A6	Dwight D. Eisenhower Department of Veterans Affairs Medical Center
- [ ] vha_589GI	St. Joseph VA Clinic
- [ ] vha_589GJ	Wyandotte County VA Clinic
- [ ] vha_589GM	Chanute VA Clinic
- [ ] vha_589GP	Garnett VA Clinic
- [ ] vha_589GR	Lieutenant General Richard J. Seitz Community-Based Outpatient Clinic
- [ ] vha_589GU	Lawrence VA Clinic
- [ ] vha_589GV	Fort Scott VA Clinic
- [ ] vha_589JE	Platte City VA Clinic

VA Kansas City health care
- [ ] vha_589	Kansas City VA Medical Center
- [ ] vha_589G1	Warrensburg VA Clinic
- [ ] vha_589GB	Belton VA Clinic
- [ ] vha_589GC	Paola VA Clinic
- [ ] vha_589GD	Nevada VA Clinic
- [ ] vha_589GZ	Cameron VA Clinic
- [ ] vha_589JB	Excelsior Springs VA Clinic
- [ ] vha_589JF	Honor VA Clinic
- [ ] vha_589HK	Kansas City VA Mobile Clinic
- [ ] vha_589JC	Shawnee VA Clinic
- [ ] vha_589QA	Overland Park VA Clinic

VA Marion health care
- [ ] vha_657A5	Marion VA Medical Center
- [ ] vha_657GJ	Evansville VA Clinic (Health Care Center)
- [ ] vha_657GK	Mount Vernon VA Clinic
- [ ] vha_657GL	Paducah VA Clinic
- [ ] vha_657GM	Effingham VA Clinic
- [ ] vha_657GO	Madisonville VA Clinic
- [ ] vha_657GP	Owensboro VA Clinic
- [ ] vha_657GQ	Vincennes VA Clinic
- [ ] vha_657GR	Mayfield VA Clinic
- [ ] vha_657GT	Carbondale VA Clinic
- [ ] vha_657GU	Harrisburg VA Clinic
- [ ] vha_657QD	Heartland Street VA Clinic

VA Poplar Bluff health care
- [ ] vha_657A4	John J. Pershing Veterans' Administration Medical Center
- [ ] vha_657GF	West Plains VA Clinic
- [ ] vha_657GG	Paragould VA Clinic
- [ ] vha_657GH	Cape Girardeau VA Clinic
- [ ] vha_657GI	Farmington VA Clinic
- [ ] vha_657GV	Sikeston VA Clinic
- [ ] vha_657GW	Pocahontas VA Clinic

VA St Louis health care
- [ ] vha_657	John Cochran Veterans Hospital
- [ ] vha_657A0	St. Louis VA Medical Center-Jefferson Barracks
- [ ] vha_657GA	St. Clair County VA Clinic
- [ ] vha_657GB	St. Louis County VA Clinic
- [ ] vha_657GD	St. Charles County VA Clinic
- [ ] vha_657GS	Franklin County VA Clinic
- [ ] vha_657GX	Washington Avenue VA Clinic
- [ ] vha_657GY	Manchester Avenue VA Clinic
- [ ] vha_657QA	Olive Street VA Clinic
- [ ] vha_657QB	Washington Boulevard VA Clinic
- [ ] vha_657QE	Scott Air Force Base VA Clinic

VA Wichita health care
- [ ] vha_589A7	Robert J. Dole Department of Veterans Affairs Medical and Regional Office Center
- [ ] vha_589G2	Dodge City VA Clinic
- [ ] vha_589G3	Liberal VA Clinic
- [ ] vha_589G4	Hays VA Clinic
- [ ] vha_589G5	Parsons VA Clinic
- [ ] vha_589G7	Hutchinson VA Clinic
- [ ] vha_589GW	Salina VA Clinic
- [ ] vha_589QB	Sedgwick County VA Clinic
- [ ] vha_589QC	South Parklane VA Clinic
- [ ] vha_589QD	Wichita VA Mobile Clinic
