### ISSUE TITLE
[VAMC] VISN-22: Desert Pacific Healthcare Network - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#22919]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-8](https://drive.google.com/drive/folders/1YuZ_PJFIEhmOuMhj55oh0lT3aL1uy6Tg)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA New Mexico health care
- [ ] VA Northern Arizona health care
- [ ] VA Phoenix health care
- [ ] VA Greater Los Angeles health care
- [ ] VA Loma Linda health care
- [ ] VA Long Beach health care
- [ ] VA San Diego health care
- [ ] VA Southern Arizona health care

Facilities include for System:
VA New Mexico health care
- [ ] Raymond G. Murphy Department of Veterans Affairs Medical Center
- [ ] Las Vegas VA Clinic
- [ ] Artesia VA Clinic
- [ ] Farmington VA Clinic
- [ ] Silver City VA Clinic
- [ ] Gallup VA Clinic
- [ ] Espanola VA Clinic
- [ ] Truth or Consequences VA Clinic
- [ ] Alamogordo VA Clinic
- [ ] Durango VA Clinic
- [ ] Santa Fe VA Clinic
- [ ] Northwest Metro VA Clinic
- [ ] Taos VA Clinic
- [ ] Raton VA Clinic

VA Northern Arizona health care
- [ ] Bob Stump Department of Veterans Affairs Medical Center
- [ ] Kingman VA Clinic
- [ ] Flagstaff VA Clinic
- [ ] Lake Havasu City VA Clinic
- [ ] Anthem VA Clinic
- [ ] Cottonwood VA Clinic
- [ ] Chinle VA Clinic
- [ ] Holbrook VA Clinic
- [ ] Page VA Clinic
- [ ] Tuba City VA Clinic
- [ ] Polacca VA Clinic
- [ ] Kayenta VA Clinic

VA Phoenix health care
- [ ] Carl T. Hayden Veterans' Administration Medical Center
- [ ] Southeast VA Clinic
- [ ] Northwest VA Clinic
- [ ] Show Low VA Clinic
- [ ] Southwest VA Clinic
- [ ] Payson VA Clinic
- [ ] Thunderbird VA Clinic
- [ ] Globe VA Clinic
- [ ] Northeast Phoenix VA Clinic
- [ ] Phoenix Midtown VA Clinic
- [ ] Phoenix VA Clinic
- [ ] Phoenix VA Mobile Clinic

VA Greater Los Angeles health care
- [ ] West Los Angeles VA Medical Center
- [ ] Sepulveda VA Medical Center
- [ ] Santa Barbara VA Clinic
- [ ] Gardena VA Clinic
- [ ] Bakersfield VA Clinic
- [ ] Los Angeles VA Clinic
- [ ] East Los Angeles VA Clinic
- [ ] Antelope Valley VA Clinic
- [ ] San Luis Obispo VA Clinic
- [ ] Santa Maria VA Clinic
- [ ] Oxnard VA Clinic
- [ ] San Gabriel Valley VA Clinic

VA Loma Linda health care
- [ ] Jerry L. Pettis Memorial Veterans' Hospital
- [ ] Loma Linda VA Clinic
- [ ] Victorville VA Clinic
- [ ] Murrieta VA Clinic
- [ ] Palm Desert VA Clinic
- [ ] Corona VA Clinic
- [ ] Rancho Cucamonga VA Clinic
- [ ] Blythe VA Clinic

VA Long Beach health care
- [ ] Tibor Rubin VA Medical Center
- [ ] Anaheim VA Clinic
- [ ] Santa Ana VA Clinic
- [ ] Cabrillo VA Clinic
- [ ] Santa Fe Springs VA Clinic
- [ ] Laguna Hills VA Clinic
- [ ] Gardena VA Clinic
- [ ] West Santa Ana VA Clinic

VA San Diego health care
- [ ] San Diego VA Medical Center
- [ ] San Diego VA Domiciliary
- [ ] Mission Valley VA Clinic
- [ ] Imperial Valley VA Clinic
- [ ] Oceanside VA Clinic
- [ ] Chula Vista VA Clinic
- [ ] Escondido VA Clinic
- [ ] Rio VA Clinic

VA Southern Arizona health care
- [ ] Tucson VA Medical Center
- [ ] Sierra Vista VA Clinic
- [ ] Yuma VA Clinic
- [ ] Casa Grande VA Clinic
- [ ] Safford VA Clinic
- [ ] Green Valley VA Clinic
- [ ] Northwest Tucson VA Clinic
- [ ] Southeast Tucson VA Clinic
- [ ] Cochise County VA Clinic
- [ ] Pinal County VA Clinic
