### ISSUE TITLE
[Design] My VA: Add a few more My VA test cases

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#22928]
## Background

As we're starting to review My VA on staging, I'm realizing there are a few more test cases we should add to our QA to make sure that testing is as thorough as possible. I'm tracking these requests here so we don't lose them in Slack:

- [x] Add a test case for making sure the Cerner alert works as expected.
- [x] For Claims updates, can we please use user 15 instead of user 226? User 15 has an update in the last 30 days, but user 226 does not. Also, if that claim update goes past 30 days, we will need to add a new claim for that user before QA.
- [x] Add a test case to make sure that all the MHV health links go to the correct account.
- [x] Add a test case to make sure that the appointment info on the dashboard matches what is in the VAOS tool. This means the appointment we are showing should indeed be the next upcoming appointment, and the info we are displaying is correct.
- [x] Add a test case to make sure that individual claim info on the dashboard matches what is in the claim status tool. This means we are showing the most recent claim, and that all the info we are displaying is correct.

There may be more, and we can add to this if we think of anything.

## Tasks

- [x] Update [test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/MyVA%20-%20test%20cases.md) as outlined above.

**Comment by Samara-Strauss** [comment]
cc/ @ajakabcin for awareness

**Comment by tressaellen** [comment]
I've added all of these - but I'm going to keep this open in case anything else comes up.

**Comment by Samara-Strauss** [comment]
Sounds good! Thank you!
