### ISSUE TITLE
Update information around spouse eligibility for Fry Scholarship

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#22923]
## Issue Description
Stakeholder Tammy Hurley asked us to update information for the Fry Scholarship around how long spouses can use the benefit. Currently, our site says 15 years but there is no delimiting date. We need to update this information on the following two pages:

https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/ 
Stakeholder suggested edit: 
Learn about the Marine Gunnery Sergeant John David Fry Scholarship (Fry Scholarship), a scholarship for children and dependents of Veterans. If your parent or spouse was an active-duty service member who died in the line of duty or died while a member of the Selected Reserves from a Service connected disability on or after September 11, 2001, you may qualify for this benefit. Find out if you’re eligible for education benefits through this scholarship.

https://www.va.gov/education/survivor-dependent-benefits/ (in the table)

Here is the doc sent from Tammy with stakeholder suggestions for edits: 
[https://app.zenhub.com/files/133843125/a03605dd-b3f7-482d-838d-032f1562bd30/download](https://app.zenhub.com/files/133843125/a03605dd-b3f7-482d-838d-032f1562bd30/download)

## Tasks
- [x] Update content for Fry Scholarship (Randi)
- [x] Review (Beth)
- [x] Send to stakeholders for review (Randi/Beth)
- [x] Update with any changes and publish (Randi)

## Acceptance Criteria
- [x] New content is live on the site

**Comment by RLHecht** [comment]
These pages are published. Moving to validate and will close after the next deploy.
