### ISSUE TITLE
Remove unauth mock data

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#22935]
## Issue Description
mock data was added to the initial state for unauth users and should be removed. We also need to remove the functionality to allow unauth users to start the form without signing in. More details can be found on this [ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/22869)

---
## Tasks
- [ ] remove mocks from initialData found in form.js
- [ ] remove link for "Start your application without signing in"

## Acceptance Criteria
- [ ] unauth users should not so show any fields pre-populated
- [ ] Start your application without signing in link should be disabled
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rebeccawalsh** [comment]
@craigwheeler We'll be needing to remove the whole "Start your application without signing in" in this ticket, correct? The form doesn't currently have true unauthenticated designs incorporated.

**Comment by craigwheeler** [comment]
sure i can update the ticket to include that change as well thanks!
