### ISSUE TITLE
Create wireframes for VA.gov Homepage for Usability Test

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#22932]
## Description

We are planning to conduct a usability study to get user feedback on new design concepts for surfacing site search and other search tools.  This issue is to create a wireframe for the VA.gov Homepage

## Background/Context/Resources
[Research Plan: Search Design Concepts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-plan.md)

## Tasks

- [x] Create Wireframes for VA.gov homepage that has links to the search start page
- Links from search in the header and from the four navigational boxes (as discussed as a team)
- [x] Create a modal design as a potential alternative to the link from search in the header
- [x] Set up time to discuss as needed

## Definition of Done

- [x] Initial wireframes are complete and ready for team review ahead of the usability study

**Comment by sshein** [comment]
I chatted with @mgleo today, want to make sure the product outline is complete and Megan has a design brainstorm with myself and Ryan before working on any kind of wireframes, so we can all move forwards together. Thanks!

**Comment by denisecoveyduc** [comment]
Thanks @sshein! @mgleo and I have had many discussions around the wireframes and design needs. Glad to hear that a brainstorming session will help move things forward.

**Comment by denisecoveyduc** [comment]
Shifting to S46 to ensure the brainstorming session can take place.

**Comment by mgleo** [comment]
User flow/wireframes that were shared during design office hours:
![user-flow-wireframes-search.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/b3648c2a-e3fe-4f12-8ade-29a2079d8e40)
