### ISSUE TITLE
TUD: Modify Filtering & Searching bar for Table

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#22950]
## Issue Description
As a TUD user, I would like the ability to see all available filters and searching on the homepage without having to navigate inside a Modal, so that I can more easily view filtering, sorting, and searching features of the Test User Dashboard application.

(Brought up in the UX Usability session #3).

See attached high-fidelity mockup for implementation provided by Amanda.

---
## Tasks
- [x] Remove the Filter Modal component & functionality
- [x] Reconfigure the functionality of the Filter bar
- [x] Reconfigure the functionality of the Pilter bar
- [x] Reconfigure the EnhancedTable.js component

## Acceptance Criteria
- [x] I can filter services using dropdown
- [x] I can see a number of accounts by service type (Prescriptions (20), etc)
- [x] I can see a filter is selected (light blue background)
- [x] I can see pilters for my selected filters
- [x] I can see a Clear All button
- [x] I can see both the number of filtered accounts and the non-filtered accounts
- [x] I can see a checkbox/toggle for Available filters
- [x] I can see a Search bar on the Find Accounts page (and only query via first name, last name, email, and number)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by APorter-Clarity** [comment]
![TUD Table – filters selected.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/d2ed2bc1-d986-479b-90f9-e66d9b23cd55)

**Comment by APorter-Clarity** [comment]
![TUD Table – categories expanded.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/61f7ad33-0b48-43a2-bc86-7b5748013717)

**Comment by APorter-Clarity** [comment]
![TUD Table – filters selected.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/7822322a-fbc1-4d59-8d8d-3c58ff139776)

**Comment by APorter-Clarity** [comment]
![TUD Table – pilters.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/58f6c194-1394-4a75-a1ba-b70e9bcd2e82)
