### ISSUE TITLE
Announce search this area button state changes with screenreader

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22960]
## Issue Description
#21958 addressed the connection between the appearance of the "Search this area of the map" button and interaction with the map (along with the refactoring). 

## Tasks
- [x] Ensure "search this area" state changes are announced via screenreader. 
- [x] Add information about the button to the zoom control instructions: 
- [x] Add a descriptive aria-label that makes it clear that users can interact with the map

The following HTML snippet was provided by @joshkimux as a sample/reference implementation for tasks 2 and 3:

```html
<p class="sr-only" id="instructions">
  Search areas on the map up to a maximum of 500 miles. Zoom in or out using the zoom in and zoom out buttons. Use a keyboard to navigate up, down, left, and right in the map.
</p>
<map
  aria-label="Find VA locations on an interactive map" 
  aria-describedby="instructions"
></map>
```

## Acceptance Criteria
- [ ] Upon tabbing into the map, simple, global instructions are provided to Veterans using screen readers.
- [x] When text on the button changes, "zoom in to search" is announced to the screenreader. 
- [x] When text on the button changes back to "Search this area of the map", the state change is announced.
- [x] The _Search this area of the map_ button never automatically receives focus.

**Comment by joshkimux** [comment]
@mmiddaugh I've updated the code snippet for updated language! We've decided _not_ to include mobile specific instructions yet as they may not function for screen reader usage on mobile devices. Angela and I will be doing some more research this week.

**Comment by mpelzsherman** [comment]
Blocked until Jenkins build issues have been resolved.
