### ISSUE TITLE
Continuous Integration Tools (CI) - Facilitate the adoption of GitHub Actions and deprecate Jenkins

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#22963]
## Problem Statement 
Now that GitHub Actions (GHA) has been chosen as the primary/preferred tool for CI on the platform, Operations will assist platform and vfs teams in adopting this new tool and moving their CI pipelines to GHA. Also, due to a number of issues and limitations with Jenkins, the platform will be deprecating its use with a view to sunset it altogether later in 2021. 

How might we support other platform teams in moving their CI pipelines to GitHub Actions? 
How might we build a bridge between the two systems so that CI jobs which are reliant on deployment jobs from Jenkins will still work? 

## Hypothesis or Bet
CI with GitHub Actions will make it easier for Platform Crew teams to write and maintain integration pipelines. 
CI with GitHub Actions will reduce complexity for Platform Crew and VFS teams. 

## We will know we're done when... ("Definition of Done")
Platform Crew teams are able to use GitHub actions for platform services and applications. 
Continous Integration pipelines that use GitHub actions are stable and performant. 

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
Mid-2021

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [x] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: Continuous Integration
* **Product Outline**: [Continuous Integration (CI) using GitHub Actions](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593880/Continuous+Integration+CI+using+GitHub+Actions)
* **User Guide**: [Set up GitHub Actions](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595196/Set+up+GitHub+Actions)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by jhouse-solvd** [comment]
This initiative can be considered complete once all of the checklist items have been addressed and supporting artifacts and documentation have been linked.

**Comment by jhouse-solvd** [comment]
This initiative can be considered complete once all of the checklist items have been addressed and supporting artifacts and documentation have been linked.

Moving to review.

**Comment by jhouse-solvd** [comment]
Operational documentation [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595236/Guidance+for+Github+Actions+usage)

**Comment by jhouse-solvd** [comment]
Closing.
