### ISSUE TITLE
Create Conversation Guide for COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22979]
## Goal
We want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users we will be communicating with.

## Considerations
Conversation guides are usually incorporated into Research Plans but because they are large enough, we separate them.  Both are considered deliverables.

## Task
- [x] Coordinate with Shawna on some of the questions to ask in the conversation guide, if needed
- [x] Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-convo-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
## Acceptance Criteria
- [x] Conversation Guide has been saved in the research-design folder in GH
- [x] Conversation Guide has been sent to Shawna for review

**Comment by sporeboy** [comment]
Initial draft of conversation guide is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-convo-guide.md

Not ready for submission. Will need review after design intent check-in.
