### ISSUE TITLE
[Operations] Platform Website: Publish content for common VFS needs

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#22985]
## Problem Statement 
Inaccurate or out-of-date documentation is not very useful for those using the platform. After we inventory and audit documentation, there may be pieces of documentation that we want to re-write and update before moving to confluence. 

How might we provide useful and relevant documentation for VFS developers' common needs? 

## Resources

- [[Ops] Content Audit and Inventory for Platform Website](https://docs.google.com/spreadsheets/d/1ZxwcDDX5NDiOGzMdvhzL2CJ3bMgcPgQccu9NUovCxrk/edit#gid=1460577279)
- [Stats for how docs are being consumed from a vfs-platform-support perspective](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1571323928/Customer+Support+Dashboard+Reports) _<--useful for prioritization_
- [Create a new Platform website documentation page] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page)
- [Platform website publishing workflow](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579803) _<--scroll viewport how-to_

## Hypothesis or Bet
*How will this initiative impact the quality of VFS or VSP teams' work?*
*How will this initiative be easy for VFS or VSP teams? Or how will it be easier than what they did before?*

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
End of Q4, 2021

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by jhouse-solvd** [comment]
Per Mike Chelen: 

Include this in our list of things to publish: 

https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595275/Slack+Notifications+from+Github+Actions

**Comment by jhouse-solvd** [comment]
Instructions for publishing a doc are included in the resources section. Please ask questions if any clarification or guidance is needed. :)

**Comment by jhouse-solvd** [comment]
We will need to pivot on this. The idea is to make documentation part of specific tasks and to look at this as it relates to publishing a service catalog. 

Moving to review. Further information to follow.

**Comment by oseasmoran73** [comment]
Was following url provided in [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22985#issuecomment-936594621) above and this ticket seems outdated through the following:

- Most of the information in the excel sheet still contain confluence & github readme. For some time, we have been moving away to have documentation Github README & some confluence onto our [platform website](https://depo-platform-documentation.scrollhelp.site/)
- With the addition of SRE, if content is outdated, platform website can be updated quicker (whether that is immediately or file ticket based off their workflow

Thoughts @jhouse-solvd ?
