### ISSUE TITLE
[Operations] Platform Website: Identify content relevant to common VFS needs

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#22984]
## Problem Statement 
There are a number of pieces of developer-facing documentation that are either out-of-date, no longer accurate, or perhaps lacking good organization and structure. To support the goals of the Platform Website, the Platform Operations team will be performing an inventory and audit of the documentation that it currently owns and maintains. The goal is to identify and prioritize documentation that is most relevant to common VFS needs so that it can be published on the Platform Website (through Confluence). 

[Audit Guidance](https://vfs.atlassian.net/wiki/spaces/AP/pages/1246527612/Audit+your+content)

How might we understand which pieces of documentation are most relevant to the VFS developer audience? ...so that we can update and publish them to the Platform Website in a [forthcoming initiative](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22985)? 

## Hypothesis or Bet
Identifying the Ops documentation that is most relevant to VFS developers' common needs will allow us to provide valuable content on the Platform website that will empower them to self-serve. 

## We will know we're done when... ("Definition of Done")
- [ ] We've performed an inventory of documentation that Ops owns. 
- [ ] ...and identified the pieces that are relevant to the VFS developer audience 

## Projected Launch Date
End of July, 2021

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by oseasmoran73** [comment]
@jhouse-solvd @ph-One Is this still relevant/needs review? It seems like a large that has not made progress in quiet some time.

My thoughts on this are the following: With the latest addition of SRE triaging via support channel, it is easier for the team to identify if information is no accurate (as feedback is usually given immediately) and then can be updated accordingly by them (whether they spin up a ticket for it or address immediately). Thoughts?

**Comment by jhouse-solvd** [comment]
@oseasmoran73 - I'll take a look. Thanks for the nudge.

**Comment by jhouse-solvd** [comment]
Rather than work on this as an initiative, we're iterating on documentation as needed (based on feedback from VFS teams, the Service Design team, and the Content & IA team). 

This issue can be closed.
