### ISSUE TITLE
Change Sitemap dates from Published to Edited

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#22980]
## Description
@ncksllvn  identified a potential sitemap improvement suggesting we change the published date to the date our editors last edited the page

- Looking on our sitemap right now -> https://www.va.gov/sitemap.xml
- Notice every page has `<lastmod>2021-04-09</lastmod>`
- That's just the date of the last time we published content - it's the same for every entry, and it isn't meaningful at all
- `lastmod `should indicate when the last time our editors actually edited the page was
- It's important for ranking because if we have a page we edit frequently or is hot off the press, a search crawler like Google might rank it might more highly based on that
- But if it's the same in the whole file, then it doesn't carry meaning anymore
- A very reasonable tech task would be to make the `lastmod `date in the sitemap actually reflect when each page was modified

## Tasks

- [x] Update metalsmith sitemap plugin to use each pages last modified date vs the current date/time at each build

## Definition of Done

- [x] last mod accurately reflects when each page was last updated
- [x] Tier 3 (No Socks validation necessary ) Validation of AC not required , once fix has been applied please ensure safe monitoring practice and validation with any applicable cross functional team as applicable.

**Comment by denisecoveyduc** [comment]
Upon investigation @srsuddath discovered that this issue is blocked by #26726. As a result this issue will be held in the backlog until the plug-in has been updated and this is unblocked.

**Comment by srsuddath** [comment]
This issue has been merged!

Unfortunately due to our build process, there were only minor improvements that can be made to the lastmod date
