### ISSUE TITLE
[Consider] Veteran experience and long breadcrumbs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22999]
## Issue Description
When we revisit VAMC breadctrumbs/IA, we need to determine the best user experience for pages which combine long H1s into the breadcrumb. 

Considerations
- [ ] Truncation? (We are unable to truncate facility names due to legislative requirement but other headings may be possible)
- [ ] Wrapping?
- [ ] Leave off the breadcrumb for the current page?

In the meanwhile, we will collect analytics on user navigation and prominent user paths to inform this conversation

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
