### ISSUE TITLE
[FE] My VA error: Review "enrollment eligibility" error Trevor posted about in Slack

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23001]
## Background

In an unrelated thread, Trevor Bosaw posted [in Slack](https://dsva.slack.com/archives/CSFV4QTKN/p1617922636092000?thread_ts=1617891226.082900&cid=CSFV4QTKN) that he was seeing the following error for user 228:

> I see it happening because `http://localhost:3000/v0/health_care_applications/enrollment_status` fails, and looking through the backend, it's the call to the `EnrollmentEligibility` from the backend that fails with `Ox::ParseError: invalid format, DOCTYPE or comment expected at line 1, column 41 [parse.c:180]`, and the following is the `XML` that we are sending, which breaks its parsing for some reason:
> 
> ```
> <?xml version=\"1.0\"?>
> <SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:sch=\"http://jaxws.webservices.esr.med.va.gov/schemas\">
>   <SOAP-ENV:Header>
>     <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" SOAP-ENV:mustUnderstand=\"1\">
>       <wsse:UsernameToken xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\" wsu:Id=\"XWSSGID-1281117217796-43574433\">
>         <wsse:Username>HCASvcUsr</wsse:Username>
>         <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">password</wsse:Password>
>       </wsse:UsernameToken>
>     </wsse:Security>
>   </SOAP-ENV:Header>
>   <SOAP-ENV:Body>
>     <sch:getEESummaryRequest>
>       <sch:key>1008709396V637156</sch:key>
>       <sch:requestName>HCAData</sch:requestName>
>     </sch:getEESummaryRequest>
>   </SOAP-ENV:Body>
> </SOAP-ENV:Envelope>
> ```

Can we look into (1) when this error occurs, (2) what is causing it, and (3) a resolution, if applicable?

## Tasks

- [ ] Review this error and regroup with Trevor if necessary
- [ ] Determine when this error is happening
- [ ] Determine next steps, whether that is a fix or something else
- [ ] If fixable, fix the problem

**Comment by erikphansen** [comment]
I do not see any issues with the My VA Apply For VA Benefits section not resolving (getting stuck on a spinner) for user 228 locally or on staging. The call to get the enrollment status from ESR does fail locally, but that's handled gracefully.

I'm closing this for now.
