### ISSUE TITLE
Add PACT tests for API calls

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23011]
## Issue Description
A breakage in the link for the VAMC "Other Locations" section was identified and addressed in #22107. The cause was determined to be an API call which was still pointed at v0. This slipped through our check for calls using that endpoint during the transition to V1. As a result, we want to add in more monitoring for API calls so we are alerted of these issues and can proactively address them. 

---
## Tasks
- [ ] Add PACT tests for all API calls

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
