### ISSUE TITLE
Create a list of all 'upstream services' vets-api integrates with

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#23012]
## Issue Description
We don't have a complete list of all 'upstream services' `vets-api` integrates with. Such a list is required for implementing integration testing.

---
## Tasks
- [x] Research `va.gov` documentation, code, and other resources for information about the services `vets-api` consumes
- [x] Create a spreadsheet listing all of the services and each `va.gov` application that consumes them
- [x] Order and prioritize the list of external services based on VA ownership and impact to the platform keeping in mind that the filtered list will be contacted for additional information about their SDLC

## Acceptance Criteria
- [x] A collection of documents that mention the services `vets-api` integrates with
- [ ] A spreadsheet listing all of the services and each `va.gov` application that consumes them

**Comment by holdenhinkle** [comment]
# Useful documents and links:
## [Upstream Services](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a5bf9c37d2e38480507490f59bf69feef2ab8f90/platform/triage/upstream-services.md)
A table that links upstream services with their respective contact lists, maintenance notification streams and on-call documentation. Missing data indicates gaps in this pipeline.

## [External Service Integrations](https://github.com/department-of-veterans-affairs/devops/tree/master/docs/External%20Service%20Integrations)
The documents here describe integrations between va.gov services and any services that are not directly managed by the va.gov team. This includes both services within the VA and services managed by external third parties.

## [Outdated Diagram of External Services](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/TechnicalArchitectureOverview.md)
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/71524cc1-0ef1-42a9-b7fa-8bf788831efc)

## [External Service Performance Indicators](http://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1)
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/c2fd406d-d0c3-4fd9-8911-1bd6e35ecec8)

**Comment by holdenhinkle** [comment]
[List of External Services (Google Spreadsheet)](https://docs.google.com/spreadsheets/d/1-ty49As0WEgEf91LUhlD9ASimKrPUOsxmoMphYwx95k/edit?usp=sharing)

**Comment by holdenhinkle** [comment]
The `settings.yml` list lots (all?) of services and the settings needed for them - https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml

**Comment by holdenhinkle** [comment]
Reviewed the above resources and built out that spreadsheet - https://docs.google.com/spreadsheets/d/1-ty49As0WEgEf91LUhlD9ASimKrPUOsxmoMphYwx95k/edit#gid=0

I scheduled an hour with Lindsey H. this Friday at 9am to review the data and to hopefully populate the _"candidate for 
integration testing?"_ column in each sheet.

I started reviewing the `vets-api` code to determine which app is using which external service.

**Comment by holdenhinkle** [comment]
Parking this ticket until I meet with Lindsey on Friday.

**Comment by holdenhinkle** [comment]
My notes about my meeting with Lindsey are here - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/20706#issuecomment-821288003

**Comment by JoeTice** [comment]
Assuming this list is complete, assigning to @pjhill to prioritize

**Comment by pjhill** [comment]
Documentation completed, but we need to do a lot more with this when enhancing the test data and test environment mapping are prioritized in the future.
