### ISSUE TITLE
Adjust Orientation Content Routing

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23017]
## Description
One of the pieces of a11y feedback we received in staging review was that the browser back button didn't work as expected once a user had progressed through the orientation and onto the form introduction page. This is because both components exist in the same parent, so the react route is the same for both. In order to address this, the wizard and orientation should live at a separate route from the introduction page, or some other solution should be considered that manages back button functionality.

## Considerations
- [ ] This experience here should mostly invisible to the user

## Tasks
- [ ] Split the wizard out on to its own page that allows the wizard to be browsed with the back button.

## Acceptance Criteria
- [ ] The back button functions more like how 508 would like to see it.
- [ ] A PR has been requested for merging
