### ISSUE TITLE
Adjust URL for CH31 Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23014]
## Background
In Staging Review, it was noted that the url should have the form number appended to it [per the original IA recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt31.md).

## Tasks
- [ ] Update the url to read: `www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/`

## Acceptance Criteria
- [ ] URL has been updated
- [ ] A PR has been requested for merging
