### ISSUE TITLE
Add Link and Address for PDF on Intro Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23013]
## Background
The stakeholder has requested that a paper option be available to a Veteran that wants it and has also supplied the relevant mailing address as well.

## Considerations
[Mockup](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/138140367/specification/sitemap)

## Tasks
- [x] Insert the following language into the intro page below the button/link to **Sign in to start your application**:

<h#>To apply by mail</h#>
You must sign in to complete this application online. To apply by mail, fill out an Application for Vocational Rehabilitation for Claimants With Service-connected Disabilities (VA Form 28-1900) and send it to the address below:

[Download VA Form 28-1900 (PDF)](https://www.va.gov/find-forms/about-form-28-1900/)

> **Department of Veterans Affairs**
> VR&E Intake Center
> P.O. Box 5210
> Janesville, WI 53547-5210

## Acceptance Criteria
- [x] The link and language is in place on the intro page
- [x] A PR has been requested for merging
