### ISSUE TITLE
Remove Unauth from CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23020]
## Background
At the time of launch, it is problematic to accommodate unauthenticated applications submissions since VBMS may not be able to find the Veterans' eFolder.

The first solution is to roll back the unauthenticated option until applications are being submitted in total via the VRE CMS and can be better managed at that time.

## Tasks
- [x] Remove the unauthenticated link on the dign in page
- [x] Redirect direct access to in app urls back to the sign in page

## Acceptance Criteria
- [x] The CH31 feature is only able to be accessed if logged in
- [x] A PR has been requested for merging
