### ISSUE TITLE
[UNPLANNED] Establish an Email Notification for CH31 Submissions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23024]
## User Story
When an applicant submits a CH31 VA Form 28-1900 online, their pdf'd copy needs to be saved in their eFolder and the RO applicable to them should get an email, notifying the support person that a submission has been made and provide a PID for them to use to look up.  

_As a Veteran Support Representative, I need to **receive an email notification** so that **I know a submission has been made and I can take action on it in my relevant systems**._

## Considerations
- Similar work we did for silent email failures in the 686: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11339
- Sample email:

To: VAVBAWAS/CO/VR&E <VRE.VBACO@va.gov> (in this example)
Subject: VR&E Counseling Request Confirmation
> Submitted Application:
> Veteran's PID: 600072774
> Type of Form Submitted: 28-1900
> Submitted Date: 01/03/2020

- RO number and email: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/engineering/README.md#ro-email-list

## Tasks
- [x] Establish the RO
- [x] Based on the RO select the proper email address
- [x] Create an email with the above fields to be sent 

## Acceptance Criteria
- [x] An email gets sent to the RO for each submission
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6567
