### ISSUE TITLE
Premortem Exercise

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23043]
## Description
In a premortem exercise, team members assume the project they are planning has just failed, and generate plausible reasons for its demise. This exercise is scheduled for 4/16, and will help us identify risks in advance that we can prioritize and mitigate

**Acceptance Criteria**
- [x] Pre-mortem exercise is conducted
- [x] Top risks are identified
- [x] Mitigation for top risks is documented on Github

## Reference Documentation
- Mural 4/16: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1617639923551/fd760966bdef31ff53c6133e62ad80952574b7a0

## Tasks & Next steps
- 5/14: Ayush to add a few notes and then close
- 5/10: We can close this, most open risks are contract based...decided to leave open to remind us to check in about ongoing sessions

- 4/26: We're combining sprint planning with pre-mortem

**4/20**
- We'll hold this session once a sprint
- Leanna and Ayush to go through the stickies in the Mural and ensure whether everything is covered in tickets on this board

**Comment by ayushchak** [comment]
https://docs.google.com/spreadsheets/d/1SZmoVV0ej-BQCXfj7waf-SO91oVWxOiFeJMeWBlEnyI/edit#gid=0

**Comment by leanna-usds** [comment]
@ayushchak I think we can close this?

**Comment by ayushchak** [comment]
Table of pre-mortem risk strategies here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/Launch%20Risk%20Mitigation%20Strategies.md
