### ISSUE TITLE
App Stores - User facing images

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23046]
## Description
App Store & Google Play require various user-facing images such as icon and marketing images

**VA Approver**
- Leanna

**Needed by**
- 5/1
- Should be done before the review build is uploaded

**Acceptance Criteria**
- [X] Quick comparative analysis of other apps: 
- [x] Images are created
- [ ] Alt text is written 
- [x] Images are approved by VA
- [x] Images are uploaded to respective consoles

## Reference Documentation
- App Store & Google Play requirements: https://docs.google.com/document/d/13t36JvEHkqqBOyh1JLxN2mh6jttCRqqtesjZicxSfT0/edit#

## Tasks & Status
**5/27**
- Working to integrate callouts for what is not in the app in a graceful way

**5/14**
- A little more design polish
- Should bring them to meeting with AH content team, for context

**5/10**
- Continuing to wrap up fit and finish to get the images ready
- We can share during demo tomorrow

**5/3**
- @leanna-usds the images in the far top left of [this mural](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1618859740720?sender=uff1791dd79ec763420518644&key=f5317000-b3d6-43bc-8c1f-6c3513ce5dcc) are ready for review
- Does anyone else need to sign up?

**4/20**
- Starting with images: https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1618859740720?sender=uff1791dd79ec763420518644&key=f5317000-b3d6-43bc-8c1f-6c3513ce5dcc

- It would be helpful to have screenshots of apps in each store, identifying descriptive text and images (seeing the app previews in search, vs the product page)

**Comment by tmulrooney-va** [comment]
I know it is trendy right now to have the app store images span across multiple screenshots but we should have stand alone images so we can easily update and rearrange the images when new features come out.

**Comment by ambikaroos** [comment]
@tmulrooney-va agreed and great point. For reference, here's an example of an image spanning multiple screenshots (screenshots 1-2), vs. standalone images (screenshots 3-4):

![image](https://user-images.githubusercontent.com/7320097/114575601-54402380-9c48-11eb-9924-5a01a0e6443c.png)

**Comment by bridgethapner** [comment]
Assigning this one to Melissa, who started some great work already here.

It may be useful to quick audit of some apps to see what they're doing (agreed on not splitting across images!) and get inspiration

**Comment by melissa-lefevre** [comment]
https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1618859740720?sender=uff1791dd79ec763420518644&key=f5317000-b3d6-43bc-8c1f-6c3513ce5dcc

**Comment by melissa-lefevre** [comment]
I have been working on divergent ideation and would love some feedback to help narrow down a direction. Here is the Mural (top left) https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1618859740720?sender=uff1791dd79ec763420518644&key=f5317000-b3d6-43bc-8c1f-6c3513ce5dcc

**Comment by leanna-usds** [comment]
I like the selections on the top left. Very nice job, @melissa-lefevre. We can play with it more post-launch if we want to. 

Is there an equivalent for Google Play?

**Comment by leanna-usds** [comment]
So approve :)

**Comment by bridgethapner** [comment]
Notes from 5/5 sync between @melissa-lefevre @drjecker and myself to wrap up and add polish to these screens: 

## Where we're at
We are polishing and finessing the screens Melissa has made. We will wrap this up in a few days. 

## Decisions made about devices/mockups
- Google Play — use white or black Google Pixel
- iPhone — use white or black iPhone X
- 414px width iPhone - iPhone 11 
- 411px width Android - Google Pixel 

## Decisions made about next steps
- We will quickly rebuild screens using the design library and add dummy text in so we're not showing any staging data

**Comment by leanna-usds** [comment]
@ambikaroos no one else needs to sign off tho I'll probably show them to Charles

**Comment by melissa-lefevre** [comment]
https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1620246912608?sender=uff1791dd79ec763420518644&key=c4e7629c-f786-41f5-9eb1-1811165e26e7

**Comment by leanna-usds** [comment]
@melissa-lefevre nicely done! approved.

**Comment by melissa-lefevre** [comment]
Great! Per the conversation at the sprint demo with setting realistic expectations, we are exploring alternatives that will go a step further with expectation setting for the initial launch. I started throwing some ideas on this [mural](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1618859740720?sender=uff1791dd79ec763420518644&key=f5317000-b3d6-43bc-8c1f-6c3513ce5dcc) in the top left.

**Comment by melissa-lefevre** [comment]
Here is are updated versions of app store images more geared for the initial release rather than promotional images. ![Profile.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/1604acaa-af84-4c3d-a9c4-672a9dd4ab22)![Health care.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/eed8a89d-8099-477f-bd59-d068fd8d03bc)![letters.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/d2522802-9180-4547-8d54-07f0dc678b51)![claims.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/0462f513-e958-4469-b15d-9df94c2c58fa)![inbox.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/9d816570-e893-4aa5-a4a7-82c1b012d56c)![appointment alert copy.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/eb8aa147-4b76-488a-b230-10209c472eda)![first screen copy.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/66b144b0-9273-4552-a785-7812f593543d)

**Comment by ayushchak** [comment]
Thanks, Melissa! This is really helpful to see how we want to manage expectations.

Wondering if this is a little bold or if we need this on all screens (e.g. we know that Rx refill is an expectation based on data, but I don't really think drafts is something that users need flagged). Let's discuss early next week with @leanna-usds

**Comment by bridgethapner** [comment]
Update going into our check-in this morning - @goldenmeanie and I are finalizing the level of alerting we want to include on images. We are meeting later in the day to discuss.

**Comment by bridgethapner** [comment]
In the 6/1 launch command center, we decided as a team to dial back the hedging in images and in the text due to concerns over approvals. The app store text that was submitted to app stores this morning are here: https://docs.google.com/document/d/1OIBK33fOyoWfojkOvwyKJC39szMxQwW9I69aKEnzBWk/edit?usp=sharing

Also - we did not see anywhere in the console to input alt text, we need to look into this further in the future.
