### ISSUE TITLE
Monitoring & Alerting

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23051]
## Description
How will we know about things like:
- Crashes: Crashlytics (can go to a Slack channel). If it happens consistently, it becomes a bug that goes into the system and is addressed as a hotfix or in the next release

- Outages impacting the app, vets-api issues: Can leverage existing VSP on call rotation, monitoring and alerting. How will we be notified if something goes wrong specifically with our part of the API

**Acceptance Criteria**
- [x] Information about monitoring and alerting is documented on GH
- [x] Mobile-relevant alerts are sent to a dedicated slack channel
- [x] Platform team knows escalation path for mobile-relevant alerts in VSP monitoring.

## Tasks & Next step

**5/10**
- [x] Configue slack webhook for `#va-mobile-app-alerts` channel, add to credstash
- [x] Add prometheus alerts for mobile, alerting to above channel
- [x] Configue a mobile team in Sentry, add email notifications  for  mobile routes
- [x] Configue firebase/crashlytics alerting
- [ ] Add PagerDuty service configuration for SSOe OAuth, wire up to availability alerting

**older**
- Determine how VSP will let us know if a backend outage impacting our app occurs
- How will we know if there is an outage in the mobile API?

**Comment by bridgethapner** [comment]
Here's a screenshot of what Medallia does on the web: 

![Screen Shot 2021-04-20 at 1.44.02 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/7d5369ef-5a39-4dbb-9d3b-f15f8ee17f18)

**Comment by leanna-usds** [comment]
Meeting with VSP ops Tuesday to find out whether they want us to be on call or being a part of their rotation. This will determine how we set these alerts up.

**Comment by patrickvinograd** [comment]
After discussion with VSP, and internally during tabletop exercise:
- We don't need to have a PagerDuty-style on-call rotation.
- We can add alerts for the small set of APIs that are unique to mobile. The documentation for these alerts should instruct the operations team how to escalate to the mobile team.
- Likewise for any alerts for shared components/dependencies that we want to be kept in the loop on, we can add documentation asking to be notified.

Separately, we will set up a dedicated slack channel for `#mobile-app-alerts`, and configure Crashlytics and Prometheus to send alerts there (the latter for the mobile-specific APIs and upstream dependencies).

**Comment by patrickvinograd** [comment]
Created `#va-mobile-app-alerts` channel.

**Comment by patrickvinograd** [comment]
Updated Sentry to ensure all backend engineers are in mobile-app-team team, and issues under our url route are assigned to that team.

**Comment by patrickvinograd** [comment]
Firebase alerting connected to #va-mobile-app-alerts

**Comment by patrickvinograd** [comment]
Merged, and see that alerts are present (in non-triggered state) in Prometheus. 

We will need to tune alerts as we go but closing this for now.
