### ISSUE TITLE
Remove redirected burials FAQs page from left nav

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23057]
## Issue Description
One of our stakeholders pointed out that in the burials and memorials hub, when you click on ["Pre-need eligibility determination"](https://www.va.gov/burials-memorials/pre-need-eligibility/) in the left nav, the FAQs that is listed under it in the left nav is redirected back to this same page. This used to link to a legacy page but it doesn't any longer and doesn't need to. Therefore should delete this FAQs from the left nav. There is a burial benefits FAQs under More Resources in the left nav, which should stay.

![Screen Shot 2021-04-12 at 8.22.24 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/711e5913-b9d6-4a2c-abfe-1052a7c42ebd)

## Tasks
- [x] Delete FAQs from burials left nav under Pre-need burial eligibility determination (Selina)
- [x] Notify stakeholder that it has been removed (Randi)

## Acceptance Criteria
- [x] FAQs no longer showing in left nav

**Comment by RLHecht** [comment]
This work is completed. Closing ticket.
