### ISSUE TITLE
Incident Response protocol

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23053]
## Description
If there is an incident or outage with the app, what is our protocol for responding?

**Acceptance Criteria**
Documentation on Github exists that covers:
- [ ] Types of incidents
- [ ] How we will know about them
- [ ] How we will respond to them

## Reference Documentation
- VSP Incident response playbook: https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Incident%20Response%20Playbook.md

- Mobile incident response playbook: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/operations/Mobile%20Incident%20Response%20Playbook.md

## Tasks & Next Steps

- 5/20: Add new ticket per to-dos in comment below?

**5/11**
- After incident response protocol is more fleshed out, hold another tabletop exercise to make sure everyone understands the flows of information

**5/10**
Action items [see Patrick's comment below]

**Comment by leanna-usds** [comment]
- What is the escalation path for IAM?
- Partner with them for revocation of tokens.

**Comment by patrickvinograd** [comment]
Operations homepage: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/operations

Incident response procedure (rides atop VSP): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/operations/Mobile%20Incident%20Response%20Playbook.md

We have several outstanding items identified from the tabletop exercise. I will collect them here, and keep this issue open until those are all resolved or spawned into linked tickets.

**Comment by patrickvinograd** [comment]
Action items:

- [ ] Define a rubric for incident classification - basically "do I wake people up for this, or does it keep til tomorrow?" and "keep product owner informed, or escalate to them for decision/support?"
- [ ] Define initial thresholds for API error rates and latency that will trigger Slack alerts. Initially we should follow VSP defaults, then tune over time.
- [ ] Define a downtime notification service for SSOe OAuth.
- [ ] Assess the need for mobile-specific maintenance window configuration, or an alternate flagging mechanism by which we can disable features, without also affecting VA.gov.
- [ ] Define an initial "business hours on-call" rotation of engineers responsible for checking all our observability tools and triaging/assigning issues.
- [ ] Ensure all engineering team has access to Firebase/Crashlytics.
- [ ] Audit all upstream dependency docs to ensure points of contact and escalation paths are current and correct.
- [ ] Check in with call center team (Chante) about whether they have an escalation path to us
- [ ] True up app store support links with what is available/possible at VA.
- [ ] Ensure that we can trace a specific user's authentication and subsequent API requests via log messages.
- [ ] Verify session revocation story with IAM team - what happens to OAuth API requests when a user is blocked for fraud
-  [ ] Work with VA.gov team to implement app access revocation on  VA.gov profile page - equivalent of "connected applications" but for SSOe OAuth instead of Lighthouse OAuth.
- [ ] Document existing app store release processes
- [ ] Get additional team members necessary access/credentials/keys to perform app store release process

**Comment by patrickvinograd** [comment]
Added Alastair/Jayson/Narin/Teesh to Crashlytics

**Comment by patrickvinograd** [comment]
Rubric for incident classification:
  
From VSP playbook:

> Categorize the Incident
> If at any point during your evaluation you determine that the system has been compromised by a third party, that there is a leak of personally identifiable information, or that the system is under attack, you must contact the Information Security Officer or Privacy Officer to initiate the VA procedures for reporting and assessment. Contact the secondary on-call engineer for assistance, and consult the Security Incident Response Playbook.

> Begin an impact assessment
> If the issue will not violate a Service Level Objective and may be addressed during business hours, create a GitHub issue in devops. You may assign the "Priority" label if this issue deserves priority. If this issue affects a large percentage of traffic, you'll need to address it immediately.
> *Use your best judgement.* An application exception affecting a small subset of users can be tackled with a clearer mind in the morning. If an issue is affecting a large number of users, or the impact is not immediately apparent, contact the secondary on-call engineer for assistance. Don't hesitate to reach out for help.

Notify Leanna:
- Critical issue - security/information breach, affecting a significant number of users, or when we need to engage with another team to resolve.

**Comment by patrickvinograd** [comment]
Incident response playbook is updated with rubric:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/operations/Mobile%20Incident%20Response%20Playbook.md

**Comment by ambikaroos** [comment]
Added #25118 to cover "Ensure that we can trace a specific user's authentication and subsequent API requests via log messages. [spin off ticket]" cc @patrickvinograd

**Comment by ambikaroos** [comment]
Added #25120 to cover "Perform a single-incident game day exercise where we follow incident response process and use actual tools/slack channels/escalation paths. [Patrick]"

**Comment by ambikaroos** [comment]
Everything covered by other tickets, closing.
