### ISSUE TITLE
Change link for Burials and Memorials promo

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23058]
## Issue Description
Currently, the promo for burials and memorials content is linking to NCA's mobile page. We need to update this link so that it points to their desktop site instead. 

New link: https://www.cem.va.gov/

This work needs to be done in the promos section of Drupal. Once it's changed there it will be changed across all pages.
![Screen Shot 2021-04-12 at 8.40.23 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/1b878e68-4609-49de-b9a6-15cf9d11260c)

## Tasks
- [x] Update link in promo to point to desktop page instead of mobile (Selina)
- [x] Alert stakeholders that this was changed (Randi)

## Acceptance Criteria
- [x] Promo is showing new link on live site

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
