### ISSUE TITLE
Translation effort for Vaccine page around greater supply and availability

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23060]
## Issue Description
We made updates to the "Who can now get a COVID-19 vaccine at VA?" section of the vaccine minihub. We need to send these updates to the certified translation team so we can update the Spanish and Tagalog pages.

## Tasks
- [x] Send Word doc with updates to certified translation team (Randi)
- [x] Input updates to Tagalog page (Selina)
- [x] Input updates to Spanish page (Selina)
- [x] Review and publish updates to Tagalog and Spanish pages (Randi)
- [x] Send links of live pages to VHA translation team for final review

## Acceptance Criteria
- [x] Tagalog and Spanish live vaccine pages are updated with this new content

**Comment by RLHecht** [comment]
Word doc with updates sent to translators on 4/12

**Comment by RLHecht** [comment]
@lunascoop Here are the translations for the Tagalog and Spanish pages. [https://app.zenhub.com/files/133843125/30cafd26-4ae1-4c69-924e-9df1c594a59c/download](https://app.zenhub.com/files/133843125/30cafd26-4ae1-4c69-924e-9df1c594a59c/download)

**Comment by RLHecht** [comment]
Tagalog updates: [https://app.zenhub.com/files/133843125/0b0d8285-1f9f-4fe4-9ffc-82143545f2a1/download](https://app.zenhub.com/files/133843125/0b0d8285-1f9f-4fe4-9ffc-82143545f2a1/download)

**Comment by lunascoop** [comment]
@RLHecht these changes are ready for review.

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
Thanks, @lunascoop ! These have been reviewed and published. I'll send the live links to the VHA translation team once for final review.

**Comment by RLHecht** [comment]
These pages are live. Closing ticket and will reopen if translation team has any corrections.
