### ISSUE TITLE
Midpoint Review [VSA Caregivers, Sign as a Representative)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23087]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure VSP reviewers have appropriate access to secured applications.
- [ ] VSP: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to VSP feedback tickets.
- [ ] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [initiative outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/initiatives/sign-as-a-rep/initiative-outline.md)
- Link to or attach [prototype](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666490/simulate/sitemap?mode=i) or [mockups](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21964#issuecomment-814340457)
- ~Link to content brief (if applicable)~
- Link to or specify the artifact that represents this initiative's content source of truth (Both the UXPin and the PDF posted above)
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/Sign-as-Rep-Round2-Usability-April%202021/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/Sign-as-Rep-Round2-Usability-April%202021/conversation-guide.md) 
- ~Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan))~
- Link to test cases/test plan in TestRail \*_coming soon_\*
- *Note* - this feature is currently available in Staging as well

## Meeting attendees from requesting team
- Product Manager (required): Alayna Abel
- DEPO Product lead (recommended): Ming Ligh
- DEPO Design lead (recommended): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Dene Galbadon, Shawna Hein, Kevin Mircovich, Justin Linn
- Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No
 
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **date/time**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @ala-yna  - I've scheduled your asynch review for Thursday, meaning you will received feedback by EOD. no meeting will be held.

**Comment by peggygannon** [comment]
@ala-yna The prototype linked above shows the whole 10-10CG form. Should we be reviewing all of these screens? If not, can you please indicate which screens we should focus our review on? thx!

**Comment by ala-yna** [comment]
@sshein, could you help clarify which screens are specific to our implementation of Sign as a Representative? Otherwise, @peggygannon, the link above should take you to [the first screen](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666490/simulate/sitemap?mode=i) that's specific to this initiative, and the rest can be found by clicking through from there.

**Comment by sshein** [comment]
Hi there - there are 3 pages that are being added or edited in the 10-10CG form
- The[ Representative documentation question page](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666490/simulate/sitemap?mode=i) (note this content was reviewed/created by Danielle already)

**Comment by pjhill** [comment]
QA has no feedback. When QA artifacts are available, and you would like some feedback please feel free to reach out prior to staging.
