### ISSUE TITLE
Add text to COVID FAQs page about calling MyVA411 to get help in other languages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23084]
## Issue Description
Veterans who speak another language and have more questions about COVID-19 can call MyVA411 to ask a call center agent for a translator in the following languages:

Afrikaans, Akan, Albanian, Amharic, Arabic, Armenian, Ashante, Assyrian, Azerbaijani, Azeri, Bajuni, Bambara, Basque, Behdini, Belorussian, Bengali, Berber, Bosnian, Bravanese, Bulgarian, Burmese, Cakchiquel, Cambodian, Cantonese, Catalan, Chaldean, Chamorro, Chao-chow, Chavacano ,Chin, Chuukese, Cree, Croatian, Czech, Dakota, Danish, Dari, Dinka, Diula, Dutch, Estonian, Ewe, Farsi, Fijian, Hindi, Finnish, Flemish, French, French, Canadian, Fukienese, Fula, Fulani, Fuzhou, Ga, Gaddang, Gaelic, Gaelic – Irish, Gaelic – Scottish, Georgian, German, Gorani, Greek, Gujarati, Haitian Creole, Hakka, Hakka – Chinese, Hassaniyya, Hausa, Hebrew, Hindi, Hmong, Hungarian, Ibanag, Ibo, Icelandic, Igbo, locano, Indonesian, Inuktitut, Italian, Jakartanese, Japanese, Javanese, Kanjobal, Karen, Kashmiri, Kikuyu, Kinyarwanda, Kirundi, Korean, Kosovan, Kotokoli, Kpelle, Krio, Kurdish, Kurmanji, Lakota, Laotian, Latvian, Lingala, Lithuanian, Luganda, Luo, Lusoga, Luxembourgeois, Maay, Macedonian, Malagasy, Malay, Malayalam, Malinke, Mandarin, Mandingo, Mandinka, Marathi, Marshallese, Mien, Mina, Mirpuri, Mixteco, Moldavan, Mongolian, Montenegrin, Navajo, Neapolitan, Nepali, Nigerian Pidgin, English, Norwegian, Nuer, Oromo, Pahari, Pampangan, Pashto, Patois, Pidgin English, Polish, Portuguese, Portuguese, Creole, Pothwari, Pulaar, Punjabi, Putian, Quichua, Romanian, Russian, Samoan, Sango, Serbian, Shanghainese, Shona, Sichuan, Sicilian, Sindhi, Sinhalese, Slovak, Slovenian, Somali, Soninke, Sorani, Spanish, Sudanese Arabic, Sundanese, Susu, Swahili, Swedish, Sylhetti, Tagalog, Taiwanese, Tamil, Telugu, Thai, Tibetan, Tigre, Tigrinya, Toishanese, Tongan, Toucouleur, Tshiluba, Turkish, Twi, Ukrainian, Urdu, Uyghur, Uzbek, Vietnamese, Visayan, Wenzhou, Wolof, Yiddish, Yoruba and Yupik.

To alert Veterans of this, we need to add text to the FAQs page (all three languages). On the Tagalog and Spanish pages, this same line should be at the bottom of each question. On the English page, we need to determine if there is a place somewhere toward the top where this could go.

## Tasks
- [x] Write copy to use on FAQs page (Danielle)
- [x] Send to translation team (Randi)
- [x] Add copy to English, Spanish, and Tagalog pages (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Text about MyVA411 on live FAQs pages

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht! I'd love to get a few variations to the translation service so we can use whichever makes the most sense contextually as we need to. 

@clantosswett I've based the text here on Trish's info from VEO's translation presentation. Sounds like agents have access 24/7 to interpreters in 200 different languages who can join the call and work with the agent to provide in-language assistance. Could you just confirm for us before we add this to our pages? Thank you!

### For Spanish page

If you have more questions, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24 hours a day, 7 days a week. Select 0 to connect with a call center agent. Tell the agent you'd like an interpreter who speaks Spanish to join the call.

If you need more information, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24 hours a day, 7 days a week. Select 0 to connect with a call center agent. Tell the agent you'd like an interpreter who speaks Spanish to join the call.

If you need more help, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24 hours a day, 7 days a week. Select 0 to connect with a call center agent. Tell the agent you'd like an interpreter who speaks Spanish to join the call.

### For Tagalog page

If you have more questions, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24 hours a day, 7 days a week. Select 0 to connect with a call center agent. Tell the agent you'd like an interpreter who speaks Tagalog to join the call.

If you need more information, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24 hours a day, 7 days a week. Select 0 to connect with a call center agent. Tell the agent you'd like an interpreter who speaks Tagalog to join the call.

If you need more help, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24 hours a day, 7 days a week. Select 0 to connect with a call center agent. Tell the agent you'd like an interpreter who speaks Tagalog to join the call.

**Comment by clantosswett** [comment]
@DanielleThierryUSDSVA this is correct AFAIK but I sent along to the group to confirm. Will let you know once I hear back. Thanks.

**Comment by RLHecht** [comment]
Text back from the translators:

[https://app.zenhub.com/files/133843125/50bc6659-d21f-4725-91e2-0da2364e430e/download](https://app.zenhub.com/files/133843125/50bc6659-d21f-4725-91e2-0da2364e430e/download)

[https://app.zenhub.com/files/133843125/6a690d3e-149f-4ca8-9d93-c786fee1ca9e/download](https://app.zenhub.com/files/133843125/6a690d3e-149f-4ca8-9d93-c786fee1ca9e/download)

**Comment by RLHecht** [comment]
This work was completed but ticket never closed
