### ISSUE TITLE
Bug: Meta titles on Outreach hub pages are not using standard formatting and style

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#23082]
## What happened?
_Meta titles (i.e., browser titles) in the Outreach hub are not consistently formatted as [per the VA.gov content style guide](https://design.va.gov/content-style-guide/seo#title-tags). Screenshots attached._

## Specs:
- Device: Various ( Macbook, HP)
- Browser: Various (Firefox, Chrome)
- Test User _(if applicable)_: n/a

## Desired behavior
_The meta title style on hub pages should follow:_  `H1 Text In Initial Caps | Veterans Affairs`  _so that when the page comes up in organic (external) searches, users will see the result listing with the correct meta title text and format, consistent with our design system. This will give users confidence that it is a legitimate, authoritative VA page._ 

## Acceptance Criteria
- [ ] _The meta title style on hub pages will use the VA.gov content style guide formatting and style for meta titles:_  `H1 Text In Initial Caps | Veterans Affairs` 

## Screenshots

 **https://www.va.gov/outreach-and-events/events/**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/051ff427-13fc-45b8-b44c-71efe062ee5d)

**Here's how it appears on organic search results (Google on Chrome):**
https://www.google.com/search?q=veterans+affairs+events&pws=0&ei=fot0YKbPA-Ox5NoPp-CIoAM&oq=veterans+affairs+events&gs_lcp=Cgdnd3Mtd2l6EAMyAggAMgYIABAHEB4yBggAEAcQHjoHCAAQRxCwAzoICAAQBxAKEB46CAgAEAgQBxAeUMMhWOFAYPJFaAFwAngAgAFQiAGHCJIBAjE3mAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwimhvGrpfnvAhXjGFkFHScwAjQQ4dUDCA0&uact=5

![image](https://user-images.githubusercontent.com/43381063/114447150-0f60b200-9ba0-11eb-8aab-ae6d74224895.png)

**Note that in the CMS, the meta title is entered correctly for the above page. Only the FE is showing incorrectly styled and wrong meta title text. CMS meta title field: ** 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/3678694c-989b-496c-a5dd-ace7ae405a17)

**Specific event pages are incorrectly formatted.** 

- Example 1:  https://www.va.gov/outreach-and-events/events/bunker-bingo-2/

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/65939844-59ed-475d-8d28-4b238d4980af)

- Example 2: https://www.va.gov/outreach-and-events/events/maintaining-balance-online-yoga-for-caregivers/

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/974ea96e-d228-4db5-bb60-707e91d0b420)

**Here's how it appears on organic (external) search (using Google on Chrome):**

![image](https://user-images.githubusercontent.com/43381063/114447004-e50ef480-9b9f-11eb-8e44-4cd9a2a4f26f.png)

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
Note - the specific event pages do not have a meta title field in the CMS. The FE in such cases should always pull from the H1, making it inital caps, to generate a FE meta title using the design system standard: 

`H1 Text In Initial Caps | Veterans Affairs`

**Comment by brianalloyd** [comment]
@RLHecht can you review this ticket and advise if this is something the `Sitewide content` team would action or a FE element.  PW Team reviewed in grooming and wanted to dial you into the discussion.

**Comment by RLHecht** [comment]
@brianalloyd I don't think this is a Sitewide Content ticket. We don't work in the Outreach and Events hub but when I opened up a few of those pages to see what they look like, I don't see an area where you would manually enter in a meta title so I think it's something that would need to be fixed on the FE.

**Comment by brianalloyd** [comment]
Thanks @RLHecht we'll dig deeper on the FE and work the issue.  Appreciate you taking a look and validating for our team.  Thanks.

**Comment by kelsonic** [comment]
I don't think this data is correct in the CMS (bear with me for a second, I know the content editor likely inputted the info correctly):

![image](https://user-images.githubusercontent.com/12773166/119550185-57edbc80-bd55-11eb-9395-596ab7da76a3.png)

This is the raw data we are getting from the CMS ^ for the page https://staging.va.gov/outreach-and-events/events/.

![image](https://user-images.githubusercontent.com/12773166/119550302-7ce22f80-bd55-11eb-8b5f-b236c686f60f.png)

This is the raw data we are getting from the CMS ^ for the page https://staging.va.gov/outreach-and-events/events/bunker-bingo-2/.

If you look at the data in both of those pages that we're getting back from the CMS, it's not formatted correctly. @kevwalsh or @swirtSJW would either of you know why those pages are receiving the meta description tags' data like this? 🙂

**Comment by swirtSJW** [comment]
@kelsonic  It looks like there are two issues surfaced here.
1) Event content types are missing a token value https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5580
![image](https://user-images.githubusercontent.com/5752113/121562067-1876cf80-c9e7-11eb-867a-1301d80a3485.png)

2) The caps logic is correct for 'title' but not for 'OG:title' and `twitter:title` https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5581
![image](https://user-images.githubusercontent.com/5752113/121563176-2bd66a80-c9e8-11eb-84d0-7bdc424be056.png)



cc: @cmaeng

**Comment by kelsonic** [comment]
Related tickets:
#26679
#23082
#24383

**Comment by brianalloyd** [comment]
Tackled this issue in related issue ticket.  Closing out in support based on validation of workflow.
