### ISSUE TITLE
Add COVID-19 vaccine info - phone and page (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23095]
## Issue Description
Bring local COVID-19 vaccine info from Lighthouse to Facility Locator.

See below for new fields.

![https___staging-api_va_gov_v1_facilities_va_bbox___-79_43_bbox___35_03_bbox___-77_93_bbox___36_53_type_health_services___Covid19Vaccine_page_1_per_page_20_radius_11_latitude_35_78_longitude_-78_68](https://user-images.githubusercontent.com/80267/115576831-dd330c80-a291-11eb-820b-e0491693c171.png)

---

## Tasks
- [ ] Implement COVID-1 iteration according to spec in [UXPin v13](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/138059694/simulate/sitemap)
- [ ] Use Lighthouse data (see image above)  for 
        - scheduling phone number 
        - local URL for COVID-19 vaccine info 
- [ ] Add data layer on COVID-19 vaccine URL (event clicks)

## Acceptance Criteria
**Assuming a Veteran has selected VA health + COVID-19 vaccines:** 
- When a Veteran selects COVID-19 vaccines as a service type, the search results contain only facilities with COVID-19 vaccines as a service. (Maintain existing functionality)
- When Service type = All VA health services, COVID service type details are not displayed
- When a Veteran selects COVID-19 vaccines as a service type. the mental health phone number is not displayed
- "Main number" does not display 

- When a Veteran selects COVID-19 vaccines as a service type, the search result card will contain the following  (see Aurora VA Clinic search result example in [UXpin](https://preview.uxpin.com/da6f3cf6f92a6ce39fa2cc6d510534b5329f86db#/pages/138059694/simulate/sitemap)) 
    - Name of facility (with link to detail page or modernized webpage, based on URL)
    - operating status (when available)
    - address
    - hyperlinked Directions
    - COVID-19 scheduling phone number from the API is labeled as "Call us to schedule" 
    - COVID-19 info at this location` links to specific local URL (from API)

- When a Veteran using a screenreader clicks the `COVID-19 info at this location` the screenreader announces "COVID-19 info at (facility name)"
- Event clicks on the COVID-19 info link can be identified as distinct from other events
