### ISSUE TITLE
Launch Medallia Satisfaction Survey on Production (Pilot)

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#23105]
## Issue Description
_We are ready to move our Medallia satisfaction/intercept survey to production for our pilot. We are going to do this first on www.va.gov/find-locations and all related `Find VA Locations` detail pages._

---
## Tasks
- [x] Disable ForeSee satisfaction survey on www.va.gov/find-locations/ and all related `find-locations` detail pages (by way of Verint/ForeSee) 
- [x] (Staging) Add the Medallia Satisfaction/Intercept survey to www.staging.va.gov/find-locations/ and all related `find-locations` detail pages
- [x] Verify function of survey and analytics
- [x] Reduce Medallia Satisfaction/Intercept survey hit rate from 100% to 5%
- [x] (Production) Add the Medallia Satisfaction/Intercept survey to www.va.gov/find-locations/ and all related `find-locations` detail pages
- [x] Smoke test all functionality
- [x] Post pilot launch on slack

## Acceptance Criteria
- [x] The Medallia Satisfaction/Intercept survey is live on production on www.va.gov/find-locations/ and all related `find-locations` detail pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
Went live on 4/22.
