### ISSUE TITLE
Add LGBT Veterans link to footer

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23120]
## Issue Description
We've been asked to add a link for **LGBT Veterans** to the footer program links, between "Minority Veterans" and "PTSD".

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/ed644fb5-3156-499e-af29-92e2c56e5bce)

For now, this link will go to: https://www.patientcare.va.gov/lgbt/

We'll then work with the LGBT program working group to help support a more comprehensive solution in the future.

---
## Tasks
- [x] Get IA advice from @mpeterz on placement
- [x] Make sure VBA knows about link (and the link from the page to their relevant page) (Danielle/Beth)
- [x] Meet with LGBT program working group re: more comprehensive solution (Danielle)
- [x] Add link (PW team)

## Acceptance Criteria
- [x] Link added to footer
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Note: VA refers to "LGBT" and not "LGBTQ+" in the terminology for these pages. Recommend following that for this for now so there's not a disconnect between the link label and the page. And then we can ask about this in conversations with working group.

**Comment by kelsonic** [comment]
PR merged + ready for validation following the daily deploy today 🙂

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA FE work is complete on this ticket, please validate on your end and let me know if any questions exist.  Thanks.

**Comment by DanielleThierryUSDSVA** [comment]
Looks great! Thanks very much, @brianalloyd and @kelsonic! I'm following up with Mikki on IA check.
