### ISSUE TITLE
Adding links and teaser text in support of VR&E online application-HOLD UNTIL AFTER LAUNCH OF VR&E ONLINE FORM

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23123]
## Issue Description
Now that the VR&E online form has launched, we need to update the top nav and left nav and add other entry points to the online form.  

Mikki's IA recommendations for placement of new links: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt31.md

Link to use throughout to new form: https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/

We will need teaser text on the following pages:
- [Careers and Employment hub landing page](https://www.va.gov/careers-employment/)
- [VR&E landing page](https://www.va.gov/careers-employment/vocational-rehabilitation/)
- [PCPG/Chapter 36 page](https://www.va.gov/careers-employment/education-and-career-counseling/) Content and link should point to VR&E landing page

## Tasks
- [x] Add link to top nav
- [x] Add link and teaser text to Careers hub landing page
- [x] Add link in Careers and Employment left nav
- [x] Add link and teaser text to VR&E landing page 
- [x] Add content and link on PCPG page that goes to VR&E page

## Acceptance Criteria
- [x] New entry points and text are on live pages

**Comment by RLHecht** [comment]
@bethpottsVADEPO here are my suggestions for the teaser text on the pages Mikki ask for.

**Careers hub landing page** 

(I modeled this after the application on the health care page but wasn't sure if we want to say "VR&E benefits" or leave the language the same as the text above it in "How to apply"):

[Apply online (VA Form 28-1900)](https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/introduction)
Start your application for vocational rehab benefits now.

**VR&E landing page:**

[Apply online (VA Form 28-1900)](https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/introduction)
Start your application for VR&E benefits now.

**Chapter 36 page:**
Add an "Other helpful information" box to bottom of page:
[Vocational Rehabilitation and Employment (VR&E)](https://www.va.gov/careers-employment/vocational-rehabilitation/)
If you have a service-connected disability that limits your ability to work or prevents you from working, VR&E can help you explore employment options and address training needs.

**Comment by bethpottsVADEPO** [comment]
These all look great, @RLHecht ! Want to ping me when it's ready for one final QA in preview?

**Comment by RLHecht** [comment]
@bethpottsVADEPO These are now on all the pages in Drupal. Could you take a look. If they are good I'll publish today.

**Comment by bethpottsVADEPO** [comment]
@RLHecht The only thing that wasn't working, and I'm not sure if it's just a drupal thing, is the link in the new box on the Ch. 36 page gave me a 403 error. Can you double check that? Otherwise all looks good.

**Comment by RLHecht** [comment]
@mnorthuis For the Careers top nav we are adding in "Apply for VR&E benefits." Because we are using VR&E there, we want to change the first link to "About Veteran Readiness and Employment (VR&E)." Want to make sure there is no issue with adding those initials there.

![Screen Shot 2021-05-19 at 10.47.57 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/172e7a54-8502-438d-8e03-a4fa684d420a)

**Comment by mnorthuis** [comment]
I don't have any issues with those initials.  Thank you!

**Comment by RLHecht** [comment]
Thanks, Mikki! Link added to top nav. Will close when validated on live site.

**Comment by RLHecht** [comment]
The last piece of this is live. Closing ticket.
