### ISSUE TITLE
Add info to Contact us and Helpful VA phone numbers about MyVA411 offering translator services

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23126]
## User story
MyVA411 offers the use of a translator in close to 200 languages. If a Veteran calls the number and presses 0 to speak to an agent, they can ask for a translator. We should add this information to both the Contact us page and Helpful VA phone numbers.

These are the languages offered:

Afrikaans, Akan, Albanian, Amharic, Arabic, Armenian, Ashante, Assyrian, Azerbaijani, Azeri, Bajuni, Bambara, Basque, Behdini, Belorussian, Bengali, Berber, Bosnian, Bravanese, Bulgarian, Burmese, Cakchiquel, Cambodian, Cantonese, Catalan, Chaldean, Chamorro, Chao-chow, Chavacano ,Chin, Chuukese, Cree, Croatian, Czech, Dakota, Danish, Dari, Dinka, Diula, Dutch, Estonian, Ewe, Farsi, Fijian, Hindi, Finnish, Flemish, French, French, Canadian, Fukienese, Fula, Fulani, Fuzhou, Ga, Gaddang, Gaelic, Gaelic – Irish, Gaelic – Scottish, Georgian, German, Gorani, Greek, Gujarati, Haitian Creole, Hakka, Hakka – Chinese, Hassaniyya, Hausa, Hebrew, Hindi, Hmong, Hungarian, Ibanag, Ibo, Icelandic, Igbo, locano, Indonesian, Inuktitut, Italian, Jakartanese, Japanese, Javanese, Kanjobal, Karen, Kashmiri, Kikuyu, Kinyarwanda, Kirundi, Korean, Kosovan, Kotokoli, Kpelle, Krio, Kurdish, Kurmanji, Lakota, Laotian, Latvian, Lingala, Lithuanian, Luganda, Luo, Lusoga, Luxembourgeois, Maay, Macedonian, Malagasy, Malay, Malayalam, Malinke, Mandarin, Mandingo, Mandinka, Marathi, Marshallese, Mien, Mina, Mirpuri, Mixteco, Moldavan, Mongolian, Montenegrin, Navajo, Neapolitan, Nepali, Nigerian Pidgin, English, Norwegian, Nuer, Oromo, Pahari, Pampangan, Pashto, Patois, Pidgin English, Polish, Portuguese, Portuguese, Creole, Pothwari, Pulaar, Punjabi, Putian, Quichua, Romanian, Russian, Samoan, Sango, Serbian, Shanghainese, Shona, Sichuan, Sicilian, Sindhi, Sinhalese, Slovak, Slovenian, Somali, Soninke, Sorani, Spanish, Sudanese Arabic, Sundanese, Susu, Swahili, Swedish, Sylhetti, Tagalog, Taiwanese, Tamil, Telugu, Thai, Tibetan, Tigre, Tigrinya, Toishanese, Tongan, Toucouleur, Tshiluba, Turkish, Twi, Ukrainian, Urdu, Uyghur, Uzbek, Vietnamese, Visayan, Wenzhou, Wolof, Yiddish, Yoruba and Yupik.

We need to determine where on each page this information should go so it is the most helpful for non-English speakers.

---
## Tasks
- [ ] Write content for Contact us and Helpful VA phone numbers pages
- [ ] Add content to pages
- [ ] Review and publish

## Acceptance Criteria
- [ ] New content is on both live page

**Comment by bethpottsVADEPO** [comment]
@RLHecht Want to make a recommendation for the content to add and where to place it on those two pages? You can reuse content Danielle wrote for COVID. Let's tackle this next week though. There are more urgent stakeholder request to turn to this week. Thanks!

**Comment by RLHecht** [comment]
Update: This can be worked on at anytime. We can take the language to use from the featured content block on the Spanish or Tagalog COVID FAQs page. @bethpottsVADEPO Is this something we should try to squeeze in or just leave in the backlog?

**Comment by lunascoop** [comment]
@psanders86 @RLHecht 

I added content for non-English language speakers to the MyVA 411 line in English. I'm not sure if I should've added the note on the Spanish and Tagalog COVID FAQs page instead. It would need to be tweaked a bit to make sense on these pages. I also added the sentence about VA offering translation services in nearly 200 languages. I'm not sure how relevant that sentence would be if the content was only in Spanish in Tagalog.

Let me know if you want to chat about it.

Helpful VA phone numbers: http://preview-prod.vfs.va.gov/preview?nodeId=8427
Contact us: http://preview-prod.vfs.va.gov/preview?nodeId=8472

**Comment by RLHecht** [comment]
Moving to blocked until @DanielleThierryUSDSVA confirms that VA411 is ready to handle a higher volume of calls once this is on these pages.
