### ISSUE TITLE
Content work for VR&E online form launch

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23122]
## Issue Description
As part of the launch for the VR&E online form, Sitewide Content needs to provide content to the eBenefits team for the CTA button and language around it for applying online, by mail and in person. For the launch, we are only making changes to the following pages:

- How to apply page
- VR&E eligibility page
- 5 VR&E tracks pages 

After launch, sitewide content will do the rest of the updates to the top nav, left nav, and other entry points. Ticket for that work is #23123.

Mikki's IA guidance to follow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt31.md

Intake request form: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23016

## Tasks
- [x] Provide new content for How to apply page that will go in react widget
- [x] Provide new content for VR&E eligibility page that will go in react widget
- [x] Provide new content for the 5 VR&E tracks pages that will go in react widget

## Acceptance Criteria
- [x] eBenefits team has all content for updated react widgets for launch

**Comment by RLHecht** [comment]
@bethpottsVADEPO I'm moving our work to this ticket rather than the intake request form. Here were are my suggested content edits from the other ticket. I wrote it so that it matches what we have on other how to apply pages. I based the directions off of what we have for other benefits. I also shortened the button text to VR&E, but I don't know if that's OK:

H2: How do I apply if I already have a VA disability rating?
You can apply online right now.

CTA button: Apply for VR&E

H2: You can also apply:

H3: By mail
Fill out VA Vocational Rehabilitation - Getting Ahead After You Get Out (VA Form 28-0588)
Download VA Form 28-0588 (PDF)

Mail the completed form to your nearest VA regional office.
Find your nearest VA regional office

If you're eligible, we'll invite you to an orientation session at your nearest VA regional office.

H3 In person
Bring your application to a VA regional office near you.
Find your nearest VA regional office

If you're eligible, we'll invite you to an orientation session at your nearest VA regional office.

**Comment by bethpottsVADEPO** [comment]
@RLHecht This is the right form per Jason's email string with the stakeholders: https://www.vba.va.gov/pubs/forms/VBA-28-1900-ARE.pdf

We'll retain the other link we already have on the static page (for service members who haven't yet received a rating) and add this one in the section above it. I'm doing some thinking about the button label and that may change, but let's go with what you have for now. Here's the content that I've edited:

H2: **How do I apply if I already have a VA disability rating?** 
You can apply online right now.

CTA button: Apply for VR&E benefits

If you're eligible, we'll invite you to an orientation session at your nearest VA regional office.

H2: **You can also apply:**

H3: **By mail** 

Fill out an Application for Vocational Rehabilitation for Claimants with Service-Connected Disabilities (VA Form 28-1900). Download VA Form 28-1900 (PDF)
LINK TO: https://www.vba.va.gov/pubs/forms/VBA-28-1900-ARE.pdf

Send your completed application here: 

ADDRESS BLOCK
Department of Veterans Affairs
VR&E Intake Center
PO Box 5210
Janesville, WI 
53547-5210

H3 **In person** 

Go to a VA regional office and have a VA employee help you.
[Find a VA regional office near you]

H3: **With the help of a trained professional**

You can work with a trained professional called an accredited representative to get help applying for VR&E benefits.
Get help filing your claim

**Comment by RLHecht** [comment]
@bethpotts Thanks! I'll work with Jason to figure out what goes in the widget and what goes in Drupal. One question: Should we also put the line "If you're eligible, we'll invite you to an orientation session at your nearest VA regional office." in the By Mail and In Person sections?

**Comment by RLHecht** [comment]
@bethpottsVADEPO here are my suggestions for the other pages. I think having just the one link to the how to apply page and then the separate note underneath about not having a disability rating is OK but let me know what you think.

**For eligibility page:**

H2: How do I apply if I already have a VA disability rating?

You can apply online right now.

CTA button: Apply for VR&E benefits

[Learn more about how to apply](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/)

**Note:** You can apply even if you’re a service member without a disability rating yet.

**For tracks pages:** 

H2 How do I get these benefits?

First, you’ll need to apply for VR&E benefits. Then, you’ll work with your Vocational Rehabilitation Counselor (VRC). 

If you’ve received your VA disability rating, you can apply online right now.

CTA button: Apply for VR&E benefits

If you're eligible, we'll invite you to an orientation session at your nearest VA regional office.

[Learn more about how to apply](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/)

**Note:** You can apply even if you’re a service member without a disability rating yet.

**Comment by RLHecht** [comment]
@jason-gcio Here is the text needed for the react widget. I followed the same pattern as the widgets on our other how to apply pages with what would go inside it vs. what is on the static page. 

**For the widget:**

H2: How do I apply if I already have a VA disability rating?
You can apply online right now.

Button text: Apply for VR&E benefits

The rest of the text that falls below that would be in Drupal. I added that in now even though the old react widget is there. You can take a look at it from this preview link: preview-prod.vfs.va.gov/preview?nodeId=727

If we are including the H2 in the widget, that means we would need a different widget for the tracks pages and a different widget for the eligibility page because the H2s are not the same as what is on the How to apply page.

**Comment by bethpottsVADEPO** [comment]
@RLHecht 

Looks good. Can you change the note in all places to this?:
**Note:** You can apply if you’re a service member who hasn't yet received a disability rating yet.

Let's keep this under the green button only and not repeat it in the other section.
"If you're eligible, we'll invite you to an orientation session at your nearest VA regional office."

**Comment by RLHecht** [comment]
@bethpottsVADEPO I updated the text in all the VR&E pages according to this ticket. Could you please review before I publish?

Node IDs:
727
726
730
731
732
733
734

**Comment by RLHecht** [comment]
These pages have all been published. Moving to validate and will close after next deploy.
