### ISSUE TITLE
Cheetah-Plan second dose remove J&J

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23129]
## Description
Due to latest CDC & FDA guidelines, we need to remove explicit references to J&J vaccine in the vaccine flow.

---

## Tasks

- [ ] Plan ahead page

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/second-dose.md) 
- [ ] There are no references to J&J or a one-dose vaccine

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by laurenernest** [comment]
@jenniemc For extra clarity on the changes
![second_dose_page__1_.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/56e31153-3939-42c3-8c02-b8e5b30b59ed)
