### ISSUE TITLE
[VAMC] Resolve Tech-Debt of COVID-19 vaccine detail pages for all Systems and link System HS [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#23136]
## STORY
As a Veteran I need to know the latest information and guidance regarding COVID-19 vaccines, so I will know how, when, and where to schedule and get my COVID-19 vaccine.

## GOAL
Provide a Nationalized/local detail page for all sites.

## TASK
- [x] Update the Source of Truth to include COVID-19 detail page
- [x] Clone all sites previously created with the COVID-19 detail page and align this with the System.
- [x] Update link in COVID-19 System health service to the new COVID-19 vaccines page locally.
- [x] VISN-4
- [x] VISN-19
- [x] VISN-6
- [x] VISN-16
- [x] VISN-21
- [x] VISN-23

## ACCEPTANCE CRITERIA
* Update the Source of Truth to include COVID-19 detail page
* All systems have a cloned and updated COVID-19 detail page and align this with the System.
* Link in COVID-19 System health service links to new COVID-19 vaccines page locally.

**Comment by bcastoe** [comment]
Blocked for the following reasons: (1) VISN-21 Northern California lists the Detail page to locations of Chico, Fairfield, Mare Island, Martinez, McCelellan, Oakland, Redding, Sacramento, Sierra Footfills, Yreka, and Yuba City instead of system name (2) VISN-4 Need to follow-up regarding Pittsburgh (3) VISN-6 cloned COVID detail page Durham for Asheville and Fayetteville Coastal but when viewing COVID19 detail page VA.gov URL status is pending (holding off on the rest that need a detail page)

**Comment by bcastoe** [comment]
#23136 - Resolve Tech-Debt of COVID-19 vaccine detail pages for all Systems and link System HS - completed and moved to Validate
