### ISSUE TITLE
Publish content migration order V1 (Determine migration order)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23147]
# User story
As a VSP Team member, I need to know the order that the Platform Website will be populated, so that I know when I'm on the hook and have to make tradeoffs with initiative work.

# Tasks
- [x] Acquire anticipated 2021 product releases
- [x] Acquire preliminary top task findings. 
- [x] Conduct team brainstorm regarding the minimum info needed to provide a comprehensive documentation experience for VFS teams.
- [x] Publish proposed migration order.
- (stretch) Secure OCTO-DE approval on the migration order.  (If we feel ready, we could share the artifact with Rachael Roueche at the mini sprint demo on 4/28.)

# Acceptance criteria
- There is a doc that lists the proposed prioritized content migration order for Platform Website.

# Reference info
- [Big Room planning Lucid Chart roadmap](https://lucid.app/lucidchart/9b3d2f36-2e90-4b2a-9676-8edb96e9dd42/edit?shared=true&page=I9Ok25vTgODC#)
- [Gretchen's initial thoughts](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1286340628/Content+migration+order+DRAFT)
- [2021-04-21 meeting notes about: PMs' validation of outlines + content order](https://docs.google.com/document/d/1oyphCLQHBRx6kfhzrNFoUu9wzOb7ZNuNWj1iVIgcQXo/edit)
- [Liani trying to capture value prop of each product](https://docs.google.com/spreadsheets/d/1J3cQSN4lYF06utBhZYV7MP562pZyXD4FktRroOH1a0A/edit#gid=0)

**Comment by gmaciolek** [comment]
https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1286340628/Content+migration+order+DRAFT

**Comment by lianilychee** [comment]
Fri 4/16 Amy and Liani brainstorming: Acquire anticipated 2021 product releases is important because:
- extracting the time of product release
  - will help us prioritize what IA and content we put in place, when
  - help us determine when we're working with which Platform Teams
  - ^^ both to accommodate rollout of products
- extracting the value prop of each product
  - help people the best when we're aware of when impt products are released
  - supports a holistic view of our support

**Comment by lianilychee** [comment]
Mon 4/19 update:
- at Team sync, Liani to role play script to PMs, to Amy

**Comment by lianilychee** [comment]
Thurs 4/22 update:
- gotta align with everyone on Content Team (hence team sync today)

**Comment by lianilychee** [comment]
Fri 4/23 update: 
- nothing today, but the three of us will be working on this during elongated Team Sync on Monday
  - related cadence: https://dsva.slack.com/archives/CPCGRR7F1/p1619125676063600
