### ISSUE TITLE
Publish guidelines V1 (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23148]
# User story
- As a VSP Team member,
- I need to know 
  - how to populate the Platform Website and
  - how to deprecate GH docs
- so that
  - there is no confusion between GH and Platform Website and
  - I know how to edit the Platform Website.

# Tasks
- [x] Determine accurate, comprehensive, plain language name for "publishing guidelines" (having everything in one space will imply relatedness)
- [x] Reconcile Whimsical and Confluence tree
- [x] Focus: Write outlines for all the pages (regardless of priority) and determine guidance structure
- [ ] Determine what pages we should prioritize, so that Platform Teams can start moving content
- (super stretch) Convert bullets into words - we don't want to write full sentences until we are very confident in our structure and hierarchy
- [x] NEW - Weds - Shop guidance outlines to other PMs, to gauge what is missing
- [x] NEW - Thurs - Shop guidance outlines to OCTO-DE, to gauge what is missing
- [ ] NEW - Fri - Determine 

# Acceptance criteria
- Guidance outlines are ready to be shopped around with OCTO-DE and other PMs, to gauge what is missing.

# Reference info
- Guidance outlines
  - [MURAL outline](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1617819869492/7e8239a6633c039669db26e32b11bb16f9f490b4?wid=0-1618597168382&outline=open)
  - [Confluence outline, based on MURAL](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1242005561/Platform+website+guidelines)
- [Prev discussion w/ FE T from 1/25/21](https://docs.google.com/document/d/1zJTgOjOen3rcVff7WzGgbFT-_EdIfzzmjfcFkrIBic4/edit#heading=h.gm6wccppji0h)
- [2021-04-21 meeting notes about: PMs' validation of outlines + content order](https://docs.google.com/document/d/1oyphCLQHBRx6kfhzrNFoUu9wzOb7ZNuNWj1iVIgcQXo/edit)
- Platform Website
  - [Scroll Viewport site](https://depo-platform-documentation.scrollhelp.site/index.html)
  - [Confluence editor](https://vfs.atlassian.net/wiki/plugins/servlet/ac/com.k15t.scroll.scroll-viewport/k15t-vpc-overview-page?ac.siteKey=8e2b7ad5-c76a-4167-95f1-97ea2f91dfa7)

**Comment by lianilychee** [comment]
Goal to complete before Gretchen's return:
- Reconcile Whimsical and Confluence tree
- _Begin_ to write outlines for all the pages (regardless of priority)

**Comment by lianilychee** [comment]
NEW goal to complete before Gretchen's return:
- Draft all the outlines for her review

**Comment by lianilychee** [comment]
Mon 4/19 update:
- Amy and Liani pairing today, once after SU and once during team sync

**Comment by lianilychee** [comment]
Thurs 4/22 update:
- gotta align with everyone on Content Team (hence team sync today)

**Comment by lianilychee** [comment]
Fri 4/23 update:
- Amy, Gretchen pairing today and Monday to revise guidelines to match DIVIO's structure of : Overview, How-to's, References

**Comment by lianilychee** [comment]
Mon 4/26 update:
- deep dive with Rachael Roueche will help
