### ISSUE TITLE
Publish PUBLISHING guidelines V1 (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23149]
# User story
- As a VSP Team member
- I need to know the intricacies of editing in Conf and publishing in SVP
- so that I do not accidentally publish prematurely.

# Tasks
- [ ] Look at Gretchen's first pass of the guidelines (in `Reference info`)
- [ ] Identify which of the individual guideline pages are considered "Migration"
- [ ] Create bullet-point lists in said pages, of what pages need to cover
- [ ] Transform bullets into plain language sentences (time box?)

# Acceptance criteria
- The first draft of the publishing guidelines are published and ready for iteration.

# Reference info
- Platform Website
  - [Scroll Viewport site](https://depo-platform-documentation.scrollhelp.site/index.html)
  - [Confluence editor](https://vfs.atlassian.net/wiki/plugins/servlet/ac/com.k15t.scroll.scroll-viewport/k15t-vpc-overview-page?ac.siteKey=8e2b7ad5-c76a-4167-95f1-97ea2f91dfa7)

**Comment by lianilychee** [comment]
work is reflected in https://github.com/department-of-veterans-affairs/va.gov-team/issues/23148
