### ISSUE TITLE
Publish the Newsletter style guide V2

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23145]
# User story
As a Newsletter content submitter*, I want to have grammar and tone guidelines to follow, so that I can reduce the effort around copyediting with the Content Team.

As a Content Team member, I want to publicize guidelines to Newsletter content submitters*, so that content submissions are as error-free as possible.  This allows for a smoother newsletter production process.

.* A Newsletter content submitter is usually a Platform Team PM, but can sometimes be a Platform Team SME.

# Tasks
- [x] Write an overall doc intro blurb.
- [x] Add March examples.
- [ ] Write short intros for each topic we have examples for

# Acceptance criteria
* Newsletter content submitters are able to access the Newsletter style guide.
* Content Team members are able to begin socializing and enforcing Newsletter Style Guide usage in Sprint 49.

# Reference info
* [Newsletter style guide in Amy's personal Conf space](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1170440248/Platform+Newsletter+style+guide)
* Future style guide additions:
  * Add sub-blurbs to examples section.
  * Fill in the following sections:
    * Remaining examples
    * Word choice
    * Tone and voice
  * QA for ___.
  * (stretch) Collaborate with SD on adding MailChimp formatting.
  * Move Confluence page to public space (currently in personal space).

**Comment by lianilychee** [comment]
Amy created tickets, so this is duplicative.
