### ISSUE TITLE
Draft April newsletter edition (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23146]
# User story
As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- Conduct pair-writing / SME interviews
  - [x] Talk to Service Design about getting a technical backup.
  - [x] Conduct the sessions
- [x] Draft newsletter edition
- [x] Conduct reviews for technical accuracy and OCTO-DE signoff
- Prepare MailChimp version (Service Design, but we support)
- Publish the newsletter via email (Service Design)
- Announce the newsletter via Slack (Service Design)

# Acceptance criteria
- We have published the newsletter for PMs' and Rachael's review.

# Reference info
- [Pair writing sessions script](https://docs.google.com/document/d/1YrMxo1MJSdcuRQJ9ZK5TtdoFENT2Vu7BPzIfDUv3-yU/edit)
- [April edition draft](https://docs.google.com/document/d/1-CaIgmfz6gfgiUwiQY6JryUyUhZZ6k6YQOzGxdAPwi0/edit?ts=6078ab9a)
- [Newsletter Google Drive folder](https://drive.google.com/drive/folders/1iQ5OZf6NT-k___CJh6D-Yx49yLF5ZMdw?usp=sharing)

**Comment by lianilychee** [comment]
Fri 4/16 update:
- Will be putting together a draft M and T, reviewing with Gretchen on Weds, and soliciting Rachael on Thurs and Fri

**Comment by lianilychee** [comment]
Mon 4/19 update:
- dental surgery yesterday, so conservatively aiming for 2 blurbs drafted today

**Comment by lianilychee** [comment]
Weds 4/21 update:
- one update left!  Just a couple of notes for that to go over
- and then grabbing the link and sharing with Rachael and PM tmr

**Comment by lianilychee** [comment]
Thurs 4/22:
- Amy and Gretchen pairing today, then having draft ready and sendable by EOD!

**Comment by lianilychee** [comment]
Fri 4/23 update:
- just one more [request](https://docs.google.com/document/d/1-CaIgmfz6gfgiUwiQY6JryUyUhZZ6k6YQOzGxdAPwi0/edit?disco=AAAAMN2g2Uw) to Jesse!

**Comment by lianilychee** [comment]
Mon 4/26 update:
- still waiting for Jesse, will FUP with him
