### ISSUE TITLE
Distinguishing the Platform Website and PW sandbox (Configure SVP)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23154]
# User story
As a Content Team member, I want to more clearly distinguish between the Platform Website and its sandbox version, so that I don't populate the wrong thing.  (And send the wrong link to VFS teams!)

# Tasks
- Distinguish the Platform Website and its sandbox
  - [ ] Determine and execute a visual design change to the sandbox.
  - [ ] Change the sandbox URL to indicate its sandbox-ness
- Change the Platform Website URL 
  - [ ] Consult with Rachael re: the new Platform Website URL
  - [ ] Change the URL
- [ ] Run informal usability testing to confirm that the two sites are discernably different.

# Acceptance criteria
- Our informal usability testing confirms that the two sites are discernably different.

# Reference info
- Change Platform Website URL has implications:
  - Probably a longer-term conversation: It would be great to have a custom name set up, but it would make sense only after Data Center
    - We'd have to update analytics with each URL change...
- Platform Website
  - [Scroll Viewport site](https://depo-platform-documentation.scrollhelp.site/index.html)
  - [Confluence editor](https://vfs.atlassian.net/wiki/plugins/servlet/ac/com.k15t.scroll.scroll-viewport/k15t-vpc-overview-page?ac.siteKey=8e2b7ad5-c76a-4167-95f1-97ea2f91dfa7)
- PW sandbox
  - [Scroll Viewport site](https://sandbox-va-platform.scrollhelp.site/)
  - [Confluence editor](https://vfs.atlassian.net/wiki/plugins/servlet/ac/com.k15t.scroll.scroll-viewport/k15t-vpc-overview-page?ac.siteKey=abc74aba-6b59-4bc3-9482-da34cfc8a6a5)

**Comment by gmaciolek** [comment]
Can we change it to va-platform or something like that instead of platform website? Or wait to change it until we can work with someone to get a custom domain that's something like platform.va.gov? 

I think we can refer to it as the platform website without putting "website" in the URL. I mean, if you're on it, you know you're looking at a website 🤷‍♀️  I don't think I've ever been to a website with the word "website" in the URL.

**Comment by lianilychee** [comment]
Gretchen can do the first three subtasks before departing.

**Comment by lianilychee** [comment]
Thurs 4/15 update:
- What's the new sandbox URL?  (IS there a new sandbox URL?)
  - because the sandbox URL in ticket's "reference info" section is throwing a 404...
- LIani spoke with Rachael Roueche about renaming `depo-platform-documentation` - more detail in [this notes section](https://docs.google.com/document/d/1TzjCNbZG1OB4FHSRAoXpBqE3GOiza0cTD-5OzTu2I_w/edit#bookmark=id.cvwnvhv38kol)
