### ISSUE TITLE
Add content about BDD program to 2 benefit detail pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23164]
## Issue Description
Stakeholder Peter Granato asked us to add text about the BDD program on the following two pages:

- VR&E eligibility page
- VR&E how to apply page

**The text he submitted:**

If you have an illness or injury that you believe was caused—or made worse—by your active-duty service, you can file a claim for disability benefits 180 to 90 days before you leave the active duty status. This may help speed up the claim decision process so you can get your benefits sooner. Find out how to file a claim through the Benefits Delivery at Discharge (BDD) program—and what to do if you have less than 90 days left on active duty. Click on below links:

[How do I file a claim for disability compensation before I leave the service?](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/)

[BDD YouTube Video](https://www.youtube.com/watch?v=-m4T4rXNfAs)

**His suggested placement** 
- Eligibility box on VR&E eligibility page
- Under the section "What if I'm a service member who hasn't yet received a service-connected disability rating?"

The above text will need to be reworked for plain language and VA.gov voice and style. 

---
## Tasks
- [x] Write new text (Beth)
- [x] Send to stakeholders for approval (Beth)
- [x] Review and publish (Randi)
- [ ] Notify stakeholder changes are live (Randi/Beth)

## Acceptance Criteria
- [x] New content on live pages

**Comment by bethpottsVADEPO** [comment]
@RLHecht SME will review the eligibility page on Monday and if all looks good, we'll make similar edits to the how to apply page, then publish both.

**Comment by bethpottsVADEPO** [comment]
@RLHecht You can copyedit these two pages now and then publish:

Eligibility: http://preview-prod.vfs.va.gov/preview?nodeId=726

How to apply: https://prod.cms.va.gov/node/727/edit

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
