### ISSUE TITLE
Audit of eBenefits mentions across VA.gov pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23161]
## Issue Description
With eBenefits going away later in the year (timeframe TBD) we need to do an audit of our benefit hubs and Resources and Support to identify everywhere we have a mention of eBenefits or link to it so that these can be updated with new language or deleted. 

Some of these places may be CTA buttons in react widgets that are already in the process of being replaced with direct links to online forms. Others may just be mentions within the text or in the right rail. 

We should first ask for FE help from PW to do a search of all eBenefits mentions and use that list to determine what needs to be worked on. 

As this work continues, we may want to break this ticket out into a separate one for implementing the updates on the page and publishing. For now we can keep it all in this ticket for tracking.

## Tasks
- [ ] Ask Nick or Kelson to run a search of eBenefits mentions
- [ ] Review list and note where we will need to make edits
- [ ] Update pages with changes
- [ ] Review and publish

## Acceptance Criteria
- [ ] eBenefits no longer referenced on VA.gov

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This mention of eBenefits was flagged to us this morning. Could you connect with the authenticated experience team about addressing this one?

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/563e4b03-2862-4afa-9cd4-b0257dbd01d0) 

Here is where the message is located (note only seen by signed in users): https://www.va.gov/track-claims/your-claims

**Comment by Mottie** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21207

**Comment by bethpottsVADEPO** [comment]
@RLHecht We should get started on this work.

Here's one I found... this VA.gov page takes the user to eBenefits, then they route the user back to us: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/

**Comment by kelsonic** [comment]
List of `eBenefit` instances found in HTML files:

```
/careers-employment/index.html
/claim-or-appeal-status/index.html
/decision-reviews/index.html
/decision-reviews/get-help-with-review-request/index.html
/disability/index.html
/disability/about-disability-ratings/after-you-get-a-rating/index.html
/disability/add-remove-dependent/index.html
/disability/after-you-file-claim/index.html
/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/index.html
/disability/get-help-filing-claim/index.html
/durham-health-care/contact-us/index.html
/education/index.html
/education/gi-bill/post-9-11/ch-33-benefit/index.html
/health-care/index.html
/health-care/order-prosthetic-socks/index.html
/health-care/pay-copay-bill/dispute-charges/index.html
/housing-assistance/index.html
/housing-assistance/disability-housing-grants/index.html
/housing-assistance/disability-housing-grants/how-to-apply/index.html
/housing-assistance/home-loans/eligibility/index.html
/housing-assistance/home-loans/how-to-apply/index.html
/life-insurance/options-eligibility/vgli/index.html
/manage-va-debt/index.html
/outreach-and-events/outreach-materials/index.html
/pension/index.html
/privacy-policy/index.html
/records/index.html
/records/download-va-letters/index.html
/resources/are-service-dogs-allowed-in-va-facilities/index.html
/resources/claim-status-tool-faqs/index.html
/resources/ds-logon-faqs/index.html
/resources/gi-bill-and-other-va-education-benefit-payments-faqs/index.html
/resources/gi-bill-wave-faqs/index.html
/resources/helpful-va-phone-numbers/index.html
/resources/how-do-i-get-college-credits-for-my-military-service/index.html
/resources/how-to-change-direct-deposit-information-for-va-benefits/index.html
/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/index.html
/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/index.html
/resources/how-va-education-benefit-payments-affect-your-taxes/index.html
/resources/my-healthevet-faqs/index.html
/resources/reimbursed-va-travel-expenses-and-mileage-rate/index.html
/resources/request-a-discharge-upgrade-or-correction/index.html
/resources/submitting-a-financial-status-report-va-form-5655/index.html
/resources/verifying-your-identity-on-vagov/index.html
/resources/what-if-i-dont-want-a-fiduciary-anymore/index.html
/resources/what-your-decision-review-or-appeal-status-means/index.html
/service-member-benefits/index.html
/sierra-nevada-health-care/make-an-appointment/index.html
/sign-in-faq/index.html
/view-change-dependents/index.html
```

**Comment by lunascoop** [comment]
Hi @kelsonic Are you able to do an audit of eBenefit mentions in PDFs on our site?

**Comment by kelsonic** [comment]
@lunascoop Find all mentions of `eBenefits` within all PDFs? I don't think I'll be able to do that unless I manually go through each one 😬

**Comment by lunascoop** [comment]
Gotcha @kelsonic. Nevermind. Thanks anyway!

**Comment by kelsonic** [comment]
[ebenefit-instances.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/7138183/ebenefit-instances.txt)
@lunascoop

**Comment by lunascoop** [comment]
@RLHecht the eBenefits technical support number has been removed from these benefit hub/root pages and are ready for review.

- VA decision reviews and appeals: http://preview-prod.vfs.va.gov/preview?nodeId=3071
- VA education and training benefits: http://preview-prod.vfs.va.gov/preview?nodeId=71 (Updated sighted language except for View payment history page)
- VA disability compensation: http://preview-prod.vfs.va.gov/preview?nodeId=68 (Changed view to review disability rates under more information)
- Careers and employment: http://preview-prod.vfs.va.gov/preview?nodeId=72 (Updated sighted language instances in more info section)
- VA pension benefits: http://preview-prod.vfs.va.gov/preview?nodeId=73 (Updated sighted language instances in more info section and get VA pension benefits)
- VA benefits for service members: http://preview-prod.vfs.va.gov/preview?nodeId=809

**Comment by RLHecht** [comment]
Thanks @lunascoop these are all reviewed and published. I'll adjust the title of the ticket to reflect that this is no longer an audit but implementing all the changes as well.

**Comment by FranECross** [comment]
@RLHecht Do you know if this item can be closed? Thanks!

**Comment by RLHecht** [comment]
@FranECross CAIA should keep this open for now but I can remove the Public Websites tag so it's no longer on your board. Thanks!
