### ISSUE TITLE
Analytics Implementation or QA Support for Epic 756 Texting for Medical Appointments

### ISSUE THREAD

**Issue by lichellebain** [department-of-veterans-affairs/va.gov-team#2317]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?
QA

- Who is this request for?

    - @elwoodva @talbotmj @brittanyclausen @lichellebain 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for? 
    _this adds context for the data_
    
     - Bylight team, Epic 756 Texting for Medical Appointmetns
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - [www.staging.va.gov]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [mock up:  https://vsateams.invisionapp.com/share/FSTDOO0WUHC#/screens/378179664]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required

    - [Provide users here]

- Test Users to replicate the event

    - [220,226]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [X] QA has been completed on Staging
- [ ] Post-launch QA on Production

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
Thanks @lichellebain - Confirming receipt of this issue

**Comment by nedierecel** [comment]
@lichellebain - Please meet my colleague @jonwehausen who will help with the QA process. 

*Follow-Ups:*
1. To confirm the acceptance criteria for the QA, do we need to validate that analytics is working when a veteran opts-in for SMS reminders?

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/4ab89db0-6128-4aa4-a46e-69e90ea153ca)

2.  It does not appear so in staging, but are there any help or tool tips that are specific to SMS that should be tracked?

3. In my cursory review, opting in _and_ opting out is triggering a successful profile transaction. Do you consider opting out a measure of success with this product?

**Comment by lichellebain** [comment]
@nedierecel  I spoke with the developer, Elwood Gary, @elwoodva, and here are his replies:

1.	There is not a separate opt-in to track for analytics.  It’s just the same as saving a mobile phone.  That does need to work.
2.	No.
3.	Yes, opting out is  measure of success.

Neither of us could access the image-getting Access Denied.

**Comment by nedierecel** [comment]
@lichellebain @elwoodva Thanks for the feedback.

1. This is how the data will appear in GA when a user opts in or opts out:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/f69b1b83-a1e5-43ea-94cf-1a72cf94ae02)

Since the ^^ screenshot shows that the Interaction is the same as saving a mobile phone, this will aggregate both mobile phone saves and SMS optins/optouts and not give a clear picture of user interaction. To better distinguish the actions, can the `profile-section` value for the dataLayer event be modified to:

- `profile-section` value for enabled state=`'profile-section': 'sms-optin'`
- `profile-section` value for disabled state=`'profile-section': 'sms-optout'`

**Comment by elwoodva** [comment]
I am not sure how it works exactly.  I see a table for ANALYTICS_FIELD_MAP that I think I could add the 'sms-optin' to and use that instead of 'mobile-telephone'   Would that work?  (I think the rest stays the same.)

**Comment by elwoodva** [comment]
...however, I'm not 100% positive about getting optin vs. optout but that should be possible.  I'd have to research more.

**Comment by nedierecel** [comment]
Thanks @elwoodva - Ideally, we would like to distinguish, as long as it doesn't impact the `mobile` phone saves. Let me know what you find. Thanks! 

CC: @jonwehausen - I'll draft more acceptance criteria for our QA after I edit Google Tag Manager.

**Comment by nedierecel** [comment]
@elwoodva Following up here if you need Analytics-Insights to do further testing.

**Comment by lichellebain** [comment]
@elwoodva @nedierecel  What is the latest status?  I was out last week, do we need to schedule a meeting, or has everything been resolved?

**Comment by nedierecel** [comment]
Hello @lichellebain - Welcome back! My questions are back with the team around this request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2317#issuecomment-541101106

I logged back into Staging but didn't yet see that the  separated. Can you please advise?

**Comment by elwoodva** [comment]
I have not completed this update yet.  We WERE going to remove the checkbox which would have made this obsolete.  But now we're leaving it and I need to complete this update.

**Comment by nedierecel** [comment]
@elwoodva Confirming I see your PR request and will provide feedback. Thanks!

**Comment by lichellebain** [comment]
I just talked to Elwood, and he has completed the work for analytics.  Can you verify?  I would like to close this issue. @nedierecel  THANKS!

**Comment by nedierecel** [comment]
@elwoodva Thanks for the fix. I'm confirming I am seeing the correct `sms-optin` and `sms-optout`. Screenshots below:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/a64637fa-e33a-4460-86cf-dafaf1f0fd20)

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/4603ac9c-68fa-4a79-b972-985f7bb52328)

There is a `profile-saved` event that is still pulling a profile-section of `mobile-telephone`. I'm going to check in with the Authenticated Experience team on this particular issue.

**Comment by elwoodva** [comment]
Yes, the same profile-saved event for mobile-telephone will still fire when they update their mobile phone when they save it through the edit modal.

**Comment by nedierecel** [comment]
@elwoodva Thanks for the logic with the modal. If they are enabling/disabling from the profile page only (and not modal), is it possible to update the event:

_Current State:_
event: "profile-saved", profile-action: "save-success", profile-section: "mobile-telephone"

_Recommended:_
event: "profile-saved", profile-action: "save-success", profile-section: "sms-optin"
OR
event: "profile-saved", profile-action: "save-success", profile-section: "sms-optout"

**Comment by elwoodva** [comment]
@nedierecel This is the logic that you should be seeing in staging...

Current State for Edit Modal (no changes):
 event: "profile-saved", profile-action: "save-success", profile-section: "mobile-telephone"

Current State for enabling/disabling from the profile page only (and not modal) in STAGING:
 
event: "profile-saved", profile-action: "save-success", profile-section: "sms-optin"
 OR
 event: "profile-saved", profile-action: "save-success", profile-section: "sms-optout"

**Comment by nedierecel** [comment]
@elwoodva You're correct that I reviewed it for the `profile-transaction` event but noticed a reference to `mobile-phone` instead of `sms-optin` or `sms-optout` within the `profile-saved` event (on the profile page and the modal). 

This should not be a blocker for launch but wanted to note it. 

@lichellebain - When this is pushed to production, please let me know, and I will send a link to the report within Google Analytics.

**Comment by nedierecel** [comment]
Thank you @elwoodva for clarifying the modal vs. profile-page/non-modal saving in Staging. 

After I enabled SMS on profile 220 on Staging within the page/non-modal option, I received a correct value for `profile-transaction` but seeing this when the `profile-saved` event occurred:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/e8d5bbda-5e2a-4f79-869a-e9c35c755b1e)

**Comment by elwoodva** [comment]
I'm new to this and still learning.  There are two events involved in this?...  "profile-transaction" and "profile-saved"? I am not sure whether I can change the profile-saved event at this time or not.  I will look into this further.

**Comment by nedierecel** [comment]
@elwoodva That's correct there are two events, and I'm happy to hop on line too if needed. The `profile-transaction` was the original PR. 

If you can't change for MVP, it's not a launch blocker on analytics. We can prioritize that for post-launch.

**Comment by elwoodva** [comment]
@nedierecel I have taken a look at the code.  I don't think I can change anything further for version 1 (which is where we are at now).  We are piggy-backing this transaction when you check the checkbox on the same mobile telephone transaction that the edit modal uses.  So when the transaction goes through it's cycle before it is finally successfully saved, the code on the normal part of the mobile phone profile field watches it until it's done.  But the two don't really talk to each other.  When the transaction is complete, the GA event is captured and it just knows that the mobile telephone was saved because that's all of the information it has at that point.  In v1.5 we might be able to do a better job of capturing the difference but really it might not be until v2.0 that we can clearly indicate the success for the permissions all by themselves.  In the GA logs, when you see the profile-saved for mobile-telephone then a) if the preceding profile-transaction was for mobile-telephone then it was done via the edit modal in the normal way but b) if the preceding profile-transaction was for sms-optin or sms-optout then you'd know it was for the checkbox initiated transaction.  I can look at it a little bit more just to be sure, but I think this is where we are.  If that's Ok for v1 then let us know if @lichellebain can check this off for our launch checklist.

**Comment by nedierecel** [comment]
@elwoodva Thanks for diving in and taking a look at where it stands for v1.

Great point on the order of events. I don't think this is a launch blocker, so let's proceed as-is for v1. Post-launch, I'll regroup with you and @lichellebain on a report summarizing interactions with SMS.

@lichellebain I'm keeping this issue open on our team for visibility post-launch reports, but all the hard work @elwoodva has done is good-to-go for MVP.

**Comment by elwoodva** [comment]
@nedierecel  Thank you!

**Comment by lichellebain** [comment]
Notes from Elwood:  I looked into getting the second Google Analytics event changed but it won’t be possible in version 1.  When we do the Permission Bio we can get both events tagged the way they want it. 

Ready to close on our side...waitinig for @nedierecel to give the ok.

**Comment by nedierecel** [comment]
@lichellebain Thanks - for MVP, this is approved. I am keeping this issue open for myself and will unassign @elwoodva. Please complete an Analytics Implementation ticket when you do the next round of iterations, and we will collaborate on how to update the second GA event. 

Next steps for this launch:
1. I will share a report with you for Production, so you can monitor usage of opt-ins and opt-outs.
2. I'll close this ticket after I have QAed the data within Google Analytics.

**Comment by nedierecel** [comment]
Sent note to Lisa and Clarice via Slack to confirm launch next week

**Comment by nedierecel** [comment]
I am removing the blocked label since this was reported to go live on 1/22. I will monitor the report I built to ensure data is coming in.

**Comment by nedierecel** [comment]
Per ToT notes, push to production is blocked due to an error.

**Comment by nedierecel** [comment]
@elwoodva @lichellebain Please see the link to the Google Analytics dashboard to help the Bylight team monitor usage of the SMS Notifications product:

[Google Analytics Dashboard for Medical Appointment Notifications](https://analytics.google.com/analytics/web/#/dashboard/Zsjhg7AxQhWlGBjr6gsZ-g/a50123418w177519031p187673796/)

Elwood, based on our discussion re: the modal implementation in October, the dashboard tracks activity of opt-ins for the on-page action, not when a veteran opts in using the modal.
