### ISSUE TITLE
Authenticated Experience: Sprint 46 (4/21 - 5/4)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23174]
## Priorities

1. Prep My VA for QA
2. Launch Direct Deposit for Edu to 100%
3. Define MVP details for notification preferences 
4. Preferred Med Facilities planning and design work
5. Review items found in Profile 2.0 a11y & 508 audit

## Profile

**PM**
- [x] Work with Liz to break down #19562 into more manageable tickets
- [x] Review items identified as part of the Full Accessibility & 508 Office Audit [Profile 2.0] #15247

**Design**
- [x] Review items identified as part of the Full Accessibility & 508 Office Audit [Profile 2.0] #15247
- [x] Work on tickets broken out from #19562
     - [x] Improve UX for "please add your [missing contact information]" linked text #22742

**FE**
- [x] (If time permits) Do not try getting full name, personal info, or military info for LOA1 users #19349
- [x] Update FAQ links and copy around what departments get updated when a veteran updates their contact info #23376
- [x] Review items identified as part of the Full Accessibility & 508 Office Audit [Profile 2.0] #15247
- [x] Remove the word "veteran" from copy in existing Profile error #23468
- [x] 508-defect-2 [COGNITION]: H1 should match or be included in the page title #19552
- [x] "we can't load all data" error sometimes shown when it shouldn't be on Profile #24003 

**BE**
- [x] [BE] Vet360Redis::Cache#invalidate should not make requests to va profile #21234  

From Previous Sprint
- [x]  VA Profile: Rename references to vet360 in devops #18259

## My VA redesign

**PM**
- [x] Hold go/no-go for QA #23306 
- [x] Assist with completion of contact center guide #23308 

**Design**
- [x] Coordinate assistive tech mobile testing on Android and iOS #22543
- [x] Finish Contact Center guide #23308
- [x] Attend go/no-go for QA #23306 
- [x] Write UAT Research Plan #24059

**FE**
- [x] Attend go/no-go for QA sync #23306
- [x] Implement an error when we cannot connect to MPI #23464
- [x] Implement error for when we can connect to MPI but user does not exist #23696
- [x] Treat 404 from appeals API as no data state #23417   
- [x] Remove V1 benefits modal from My VA #23924
- [x] "Learn how to file a VA disability claim" link text is incorrect on staging #23776
- [x] "Learn how to apply for education benefits" link text is incorrect on staging #23779

From Previous Sprint
- [x] Add error state for appointments #21846 
- [x] Resolve any remaining pre-QA issues:
     - [x] Appointments are not displaying for user when they have one within the next 30 days #23063
     - [x] "You have no appointments scheduled in the next 30 days" message missing #23064 
     - [x] Clicking "Manage all claims and appeals" link re-routes back to My VA #23015
     - [x] "Learn how to file a claim for disability" links to wrong page #23072

## Direct deposit for EDU

**PM**
- [x] Monitor launch to all users #23215 

**FE**
- [x] Launch to all users #23215 

**BE**
- [x] Remove backend feature flag check for edu benefits direct deposit #23448

## Preferred medical facility
_Note: VAOS should be beginning their design work_

**PM**
- [x] Regroup with VAOS folks on 5/3 after their PI planning
- [x] @Samara-Strauss and @ajakabcin to work on KPI planning with Lauren (VAOS)
- [x] Start test case & test user documentation #23317

**Design**
- [x] Start test case & test user documentation #23317
- [x] Work with Peter (VAOS) on designs (scheduling tool)
- [x] Begin research plan #23320

## Notification Preferences

**PM**
- [x] Samara to work on KPI planning
- [x] VANotify/VEText coordination on MVP notifications #23349

**Design**
- [x] Begin research plan #23321
- [x] Determine naming conventions + organization for notifications and groups #23728

**FE**
- [ ] Technical discovery #22597

**BE**
~- [x] Add batch update api to communication permissions #23065~ 
- [ ] Fix communication preferences null data bug #24115

**Comment by ajakabcin** [comment]
Sprint ended - closing
