### ISSUE TITLE
[FSR] Marital status UI and content improvements

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23170]
## Issue Description
_We received feedback during the FSR's usability study that participants didn't know why their marital status/spouse information was necessary. Additionally, there was concern about needing to specify their marital status as 'divorced', 'separated', etc. This specification was added in an attempt to provide more context about the Veteran's financial situation, but the original form only asks if they're 'married' or 'not married'. We've evaluated the content and need to incorporate the UI and content changes._

---
## Tasks
[UXPin prototype for reference
](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138206407/comment/sitemap?mode=i)
- [ ] _Update the question asking about the Veteran's marital status to 'Are you married' with yes and no radio buttons. 'Yes' will proceed to gather spousal information, whereas 'no' will proceed to the dependent page._
- [ ] _Add an 'additional info' component with the outlined content_

## Acceptance Criteria
- [ ] _The UI has been updated to reflect the provided UXPin prototype_
- [ ] _The content changes have been incorporated_
- [ ] _The changes have been reviewed by a designer on the team_
