### ISSUE TITLE
Appointment request confirmation (Homepage Refresh)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23178]
## Description
Update submission flow to show appointment details instead of separate confirmation page for successful appointment request submissions.

---
## Tasks
- [ ] VA request

- [ ] CC request

- [ ] VVC request

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag

- [ ] Given VA request, When submission is successful, Then show appointment detail page with confirmation message
- [ ] Given CC request, When submission is successful, Then show appointment detail page with confirmation message
- [ ] Given VVC request, When submission is successful, Then show appointment detail page with confirmation message
- [ ] Given new session, When user navigates to VA request appointment detail, Then show appointment detail page AND NOT confirmation message
- [ ] Given new session, When user navigates to CC request appointment detail, Then show appointment detail page AND NOT confirmation message
- [ ] Given new session, When user navigates to VVC request appointment detail, Then show appointment detail page AND NOT confirmation message
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/confirmation-copy.md#homepage-refresh-toggle) 
- [ ] DESIGN - Designs match the specs (copy is FPO)

VA and VVC request specs
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/jgkdPMG)
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/bgAqQzo)
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/Om0PlD8#Inspector)

CC request specs
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/eKgYbza) 
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/ELzYvEY) 
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/JnPpm45) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by LanceGundersen** [comment]
Best Practices https://docs.cypress.io/guides/references/best-practices
- [ ] Selecting Elements => by using highly brittle selectors that are subject to change is an Anti-pattern. Recommend using data-* attributes to provide context to your selectors and isolate them from CSS or JS changes. `data-cy="submit”`
- [ ] Creating "tiny" tests with a single assertion => acting like you're writing unit tests is an anti-pattern. Recommend add multiple assertions and don't worry about it
	- It is common for tests in Cypress to issue 30+ commands. Because nearly every command has a default assertion (and can therefore fail), even by limiting your assertions you're not saving yourself anything because any single command could implicitly fail.
- [ ] Using after or afterEach hooks => using after or afterEach hooks to clean up state is an anti-pattern. Should clean up state before tests run.
- [ ] Unnecessary Waiting => Use route aliases or assertions to guard Cypress from proceeding until an explicit condition is met.

Mocks
- [ ] To make the route mocks more flexible and reusable, we should make each real HTTP call in our application into a separate arrow function mocking that same call. https://blog.bitsrc.io/mocking-http-calls-in-cypress-end-to-end-tests-fa2e6b7caaf7
- [ ] Suggest organizing into a mocks folder structure with the name of the file in relation to the page, call or a combination. Could even be something else altogether.

This file `src/platform/testing/e2e/cypress/support/commands/syncFixtures.js` is pretty neat and if you do a code search for syncFixtures you can see how other teams are using it. Why they named it constants I am not sure but it had me curious if we could do a syncPlugins like that.

The second thought is we could just do the functions like ware currently doing and just rename/restructure it a bit. Ideally it looks like you would just set the function to a task and call that task opposed to calling the function directly.
