### ISSUE TITLE
Add content to HLR page about new Claim Accuracy Request

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23183]
## Issue Description
Stakeholder Adrienne Hooten provided content about the pilot Claim Accuracy Request. This will allow accredited representatives a chance to request an expeditious review and determination of a claim for disability benefits. They have asked that this new content go onto our site no later than April 19, 2021. 

The content provided needs to be rewritten into plain language and VA.gov voice and style. 

**Provided content:** [https://app.zenhub.com/files/133843125/0b2aef6a-ac3b-4646-b730-455aaa2832e3/download](https://app.zenhub.com/files/133843125/0b2aef6a-ac3b-4646-b730-455aaa2832e3/download)

**Background info also provided:** 

In close collaboration with Veteran Service Organization (VSO) partners, the Veterans Benefits Administration (VBA) is launching a pilot program, Claim Accuracy Request (CAR), to allow representatives opportunities to quickly identify significantly flawed decisions with obvious errors, and for VBA to expeditiously review and redecide them. This pilot program was developed to replace the 48-hour review practice by allowing for expedited review of decisions specific to significantly flawed decisions. For the purposes of the pilot program only, participation is limited to VA-accredited VSOs, accredited agents and attorneys.
Office of Administrative Review (OAR) has been working in coordination with Office of General Counsel (OGC) to ensure compliance with NOVA v. Wilkie December 2018. This Court decision rules that substantive guidance or rules cannot be implemented without public notice and comment. For example, any substantive rules should be published for notice in comment, most commonly in the federal register. However, for the implementation of this pilot program, OGC advised that we are able to provide public notice via an external website: VA.gov.

**Page to work on:** https://www.va.gov/decision-reviews/higher-level-review/

## Tasks
- [x] Rewrite provided content into plain language (Beth)
- [x] Send to stakeholders for approval (Beth)
- [x] Review and publish (Randi)
- [ ] Notify stakeholders that change is live (Beth/Randi)

## Acceptance Criteria
- [ ] New content is live on HLR page

**Comment by bethpottsVADEPO** [comment]
I sent the stakeholder this Q&A to add to the HLR page, but it was more than they wanted to communicate at this time:

# What's a Claim Accuracy Request (CAR)? 

This is a new pilot program that may help you get a faster Higher-Level Review decision on your claim. If your claim has a clear factual or legal error, your accredited representative, agent, or attorney can request a faster decision through this program.

## How your representative can request this faster review

Your representative will need to submit a Decision Review Request: Higher-Level Review (VA Form 20-0996) within 30 days of the date on the decision notice. They must print “Claim Accuracy Request or “CAR” on the third page of the application in the top margin. There isn’t a separate CAR form to fill out.

**Note:** If your representative submits the Higher-Level Review form after the 30-day time limit, you can't use this option. Even if your representative asked for the faster review, we'll need to do a standard review.

## When to expect a decision
You can expect a decision in about 30 days.

## Your review options after you get a CAR Higher-Level Review decision

Your options are the same as they are with a standard Higher-Level Review. You can’t submit another Higher-Level Review on this claim, but you can submit a:
- Supplemental Claim, **or**
- Board Appeal
- 
**Note:** If there’s another issue that’s not related to the CAR Higher-Level Review issue, your representative must file a separate decision review form.

------------------------------

So I followed up with the suggestion of putting this note in the blue box on the HLR page:

**Note:** We have a new pilot program called Claim Accuracy Request (CAR) that may help you get a faster Higher-Level Review decision on your claim. If your claim has a clear factual or legal error, your accredited representative, agent, or attorney can request a faster decision through this program.

**Comment by bethpottsVADEPO** [comment]
@RLHecht After a convo with Carolyn Temple in OAR, who had concerns about adding this content to the HLR page, we've decided the best placement is the accredited representative page. Please copyedit http://preview-prod.vfs.va.gov/preview?nodeId=904

What changed:
1/ Moved the note about VSO meaning--both officers and organizations--up into the blue box.
2/ Added a note about CAR to the end of the Q&A "What does an accredited representative or VSO do?"

I will let you know when to publish. Not quite yet. We need to get a final thumbs up from Ray Telez.

**Comment by RLHecht** [comment]
This page was published. Moving to validate and will close after the next deployment.

**Comment by RLHecht** [comment]
Change is live. Closing ticket.
