### ISSUE TITLE
Add link to new HLR form in decision reviews left nav

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23181]
## Issue Description
We need to link to the new HLR form in the decision reviews left nav. It should nest under the Higher-Level Review static page. 

The link label should be: Request a Higher-Level Review
Link: https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction

## Tasks
- [x] Add link to left nav
- [x] Review and publish

## Acceptance Criteria
- [x] Decision reviews left nav is showing new HLR form

**Comment by RLHecht** [comment]
This was added to the left nav. Moving to validate and will close after next deploy. FYSA @mnorthuis @bethpottsVADEPO

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket.
