### ISSUE TITLE
[FSR] Update 'Make a payment' terminus for wizard

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23204]
## Issue Description

**Feedback from IA:**
Linking/information scent: In the wizard alerts after selecting "Make a payment", the link to " Find out how to manage your debt" is a more broad task than what they have indicated they want to do - make a payment. Recommend providing more specific info/link directly to pay.va.gov, or and/or providing a more specific link to deep link them to the corresponding content on the static page for all the ways to make a payment. Not fixing may result in increase in time to complete task and user frustration.

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/c0aac3fd-42bb-4065-a5f3-59992cf9b747)

---
## Tasks
- [x] Rewrite the content in the wizard terminus
- [x] Review with content
- [x] Create a FE ticket to complete the work

## Acceptance Criteria
- [x] New content written and documented in this ticket
- [x] FE ticket created and linked to this ticket

**Comment by rileyorr** [comment]
To align with the VHA's 'Make a payment' termini, I broke out the VBA's 'Make a payment' into an additional question with three termini (online, by phone, by mail). They've been documented as [d1-d3 in this UXPin
](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691609/simulate/sitemap?mode=i)
- [Frontend ticket for this work can be found here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/29876)
