### ISSUE TITLE
Update chatbot with recent changes made to vaccine minihub

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23202]
## Issue Description
We've recently updated the vaccine page with content about eligibility and availability for the vaccines. These updates also need to be made in the chatbot. 

## Tasks
- [ ] Do a comparison of the chatbot and vaccine minihub to determine what content updates are needed to the chatbot (Selina)
- [ ] Update chatbot with new text (Selina)
- [ ] Review changes (Randi)
- [ ] Alert chatbot team when changes are ready

## Acceptance Criteria
- [ ] Updated vaccine content is live in chatbot
