### ISSUE TITLE
[FSR] Content updates per staging review feedback

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23209]
## Issue Description
_Multiple sections of the FSR need content changes per [Peggy's staging review feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22475). This epic contains tickets for both updating the UXPin (given that we're iterating on the design) and frontend._

---
## Frontend tickets
- [x] _[Wizard content updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23218)_
- [x] _[Global form content updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23234)_
- [x] _[Content updates by page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23245)_
- [x] _[Privacy policy statement](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23297)_

## Design tickets
- [x] _[Wizard content updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23219)_
- [x] _[Global form content updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23237)_
- [x] _[Content updates by page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23247)_
- [x] _[Review and update error messages so they align with VA.gov's content style guide](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23299)_
- [x] _[Privacy policy statement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23298)_
---
## Acceptance criteria
- [ ] All tickets have been completed and checked off in this epic
