### ISSUE TITLE
Update chatbot with recent changes made to vaccine minihub

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23203]
## Issue Description
We've recently updated the vaccine page with content about eligibility and availability for the vaccines. These updates also need to be made in the chatbot. 

## Tasks
- [x] Do a comparison of the chatbot and vaccine minihub to determine what content updates are needed to the chatbot (Selina)
- [x] Update chatbot with new text (Selina)
- [x] Review changes (Randi)
- [x] Alert chatbot team when changes are ready

## Acceptance Criteria
- [x] Updated vaccine content is live in chatbot

**Comment by lunascoop** [comment]
Hi @DanielleThierryUSDSVA can you review the changes I made to question #69 (particularly the first sentence and two bullet points)? https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/vaccine-updates-4.14.21/content/chatbot-messages.md 

I wasn't sure that the second bullet point is needed since the question seems solely for a Veteran.

**Comment by RLHecht** [comment]
These work is complete. Closing ticket.
