### ISSUE TITLE
Monitoring - Set up DataDog agent to capture metrics in EKS

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23200]
## Issue Description
As an infrastructure/devops engineer, I need to install DataDog agent so that I can capture metrics from EKS clusters. 

---
## Tasks
- [x] Install node agent 
- [x] Install cluster agent
- [x] Install kubestate metrics service 
- [x] DataDog general configuration
- [x] Basic testing to make sure it's up
- [x] CI Process for installing the above 

## Acceptance Criteria
- [x] DataDog agent will be able to capture metrics from EKS 
---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Think this would be considered complete now with Matt's most recent work to finish the pipeline for the DataDog service.
