### ISSUE TITLE
[FSR] Wizard content changes

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23219]
## Issue Description
_The FSR's wizard needs content updates per Peggy's staging review feedback. Since we're proceeding with a second iteration post-usability recommendations, we need to make sure the changes suggested in production align with the prototype._

---
## Tasks

Ensure the following changes requested in production's wizard align with the prototype: 

- [x] Please fix typo in this sentence: `I this this debt is due to an error.` TO: `I think this debt is due to an error.`

- [x] Update the email under 'Rogers STEM program' from `VETTEC.VBAUF@va.gov` TO `stem.vbabuf@va.gov`

- [x] Update the email under 'VET TEC program' from `VETTEC.VBAUF@va.gov` TO `vettec.vbabuf@va.gov`

- [x] Please delete error/ double Note in this sentence:
`Note: Note: You have 180 days from the date you received your first debt letter to submit your dispute statement. After this time, we can’t consider the request.

- [x] Fix misspelling of `amount` in this sentence: `I think the amout of this debt is wrong.`

- [x] Please update the hours for the alert under 'Separation pay' TO:
`For help with debt related to separation pay/attorney fees, call us at 800-827-1000. We’re here Monday through Friday, 7:00 a.m. to 8:00 p.m. ET. If you have hearing loss, call TTY: 711.`

- [x] Change `Active duty service member` TO `Active-duty service member` under 'Request debt relief (a waiver or compromise offer)
For the alert under 'Report an error or disagreement with a VA decision' > 'I disagree with the VA decision that resulted in this debt': 

- [x] Capitalize 'supplemental claim' and 'higher level review' as shown below
`If you disagree with the VA decision that resulted in this debt, you can submit a Supplemental Claim or request a Higher Level Review or board appeal.`

- [x] Change the link `Learn more about the VA appeals process` TO `Learn more about decision reviews and appeals`

- [x] Change the CTA button `Submit a Financial Status Report` TO `Request help with VA Form 5655`

- [x] Capitalize 'Board' in this sentence: “I want to appeal the decision with the board of Veterans Appeals.” Correct name is Board of Veterans' Appeals

## Acceptance Criteria
- [x] _The content changes have been incorporated and checked off_

**Comment by rebeccawalsh** [comment]
Since most of this feedback is not actually in a prototype, I incorporated this feedback here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/design/wizard-design-content.md

A few items were incorporated into the design file here: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/139494236/simulate/sitemap
