### ISSUE TITLE
Scaffold COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23216]
## Description
In order to get the initial folder and file structure set up for Certificate of Eligibility (CoE), we need to scaffold out the project in `vets-website`. This scaffolding will not include any of the custom functionality of CoE and all of the content in this scaffolding is heavily subject to change.

## Considerations
- Address the product decision doc in the feature folder
- Form application
- 526 also asks for service history, so look into duplicating logic from there
- [Prototype](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137576823)

## Tasks
- [ ] Run yeoman generator for form application
- [ ] Edit generated form schema so it closely matches mockup

## Acceptance criteria
- [ ] The initial folder and file structure for CoE has been created
- [ ] A PR for this ticket has been submitted and is awaiting approval

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16949
