### ISSUE TITLE
Create prototype for mobile VHA location research

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23212]
## Description
Currently, VAMC Location pages include mobile facilities. See [Cheyenne](https://www.va.gov/cheyenne-health-care/locations/) for an excellent example. We'll need a prototype to support Veteran research conducted to understand the best ways to display mobile locations. 

## Background
Listed locations may be truly mobile (with wheels) or be brick/mortar locations with fixed addresses, may not offer full or defined set of services, may not have standard schedules, may not be accessible by all Veterans, or not be used to deliver health care at all. For the purpose of this issue, we're focused on truly mobile (with wheels) locations _with set schedules_ and _with unknown/not routine schedules._

## Goals of research
To learn
- Where (on VAMC pages) they expect to find mobile facility information
- What information they need to know before visiting a mobile facility
- Expectations related to telehealth services (vs in-person care)
- Use cases for visiting mobile facilities 
- How to represent hours/address/parking/transportation information

## Tasks
- [ ] Review [Des_Moines_Mobile_Medical_Unit_brochure.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6313571/Des_Moines_Mobile_Medical_Unit_brochure.pdf) as an example use case
- [ ] Refer to [Laramie VA Mobile Clinic page](https://www.va.gov/cheyenne-health-care/locations/laramie-va-mobile-clinic/) as starting point to create a prototype to support Veteran research about mobile locations 
- [ ] Create a prototype containing the following two mobile unit scenarios to be used in Veteran testing

**The mobile unit is found at scheduled places/dates** (as in the Locations content in the Des Moines brochure) 
- How should the location/schedule/prepare for your visit information be displayed to Veterans? (idea: should the accordions under "Prepare for your visit" represent the locations (Adel—Dallas County Veteran Affairs Office, Algona—Kossuth County VA Office, etc) with details inside?)
- How should "virtual/telehealth" services be displayed? (Scenario: Mobile unit has in-person staff to provide lab/vaccine/benefit eligibility services but Veteran connects with a remote provider via Zoom for primary care discussion)

**The mobile unit is available but set locations, dates (or both) is unknown**
- How should the location/schedule/prepare for your visit information be displayed to Veterans? 
 
## Acceptance criteria
- [ ] Prototype is available to support Veteran research

**Comment by mmiddaugh** [comment]
Closing as duplicate of #24611
