### ISSUE TITLE
[FSR] Wizard content updates

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23218]
## Issue Description
_The FSR's wizard needs content updates per Peggy's staging review feedback._

---
## Tasks

- [x] Please fix typo in this sentence: `I this this debt is due to an error.` TO: `I think this debt is due to an error.`

- [x] Please delete error/ double Note in this sentence:
`Note: Note: You have 180 days from the date you received your first debt letter to submit your dispute statement. After this time, we can’t consider the request.

- [x] Fix misspelling of `amount` in this sentence: `I think the amout of this debt is wrong.`

- [x] Please update the hours for the alert under 'Separation pay' TO:
`For help with debt related to separation pay/attorney fees, call us at 800-827-1000. We’re here Monday through Friday, 7:00 a.m. to 8:00 p.m. ET. If you have hearing loss, call TTY: 711.`

- [x] Change `Active duty service member` TO `Active-duty service member` under 'Request debt relief (a waiver or compromise offer)
For the alert under 'Report an error or disagreement with a VA decision' > 'I disagree with the VA decision that resulted in this debt': 

- [x] Capitalize 'supplemental claim' and 'higher level review' as shown below
`If you disagree with the VA decision that resulted in this debt, you can submit a Supplemental Claim or request a Higher Level Review or board appeal.`

- [ ] ~~Change the link `Learn more about the VA appeals process` TO `Learn more about decision reviews and appeals`~~

- [ ] ~~Change the CTA button `Submit a Financial Status Report` TO `Request help with VA Form 5655`~~

- [x] Capitalize 'Board' in this sentence: “I want to appeal the decision with the board of Veterans Appeals.” Correct name is Board of Veterans' Appeals

- [x] Under **both** the 'Spouse' and 'Dependent' options for 'Request debt relief (a waiver or compromise offer), update the link in `fill out the PDF version of our Financial Status Report (VA Form 5655).` TO `[Financial Status Report (VA Form 5655)](https://www.va.gov/find-forms/about-form-5655/)`

## Acceptance Criteria
- [ ] _The content changes have been incorporated and checked off_

**Comment by LinnJS** [comment]
This need to be validated with design and content... is this content current? @rebeccawalsh @rileyorr

**Comment by LinnJS** [comment]
Removing ACs for lowercasing emails due to them being in another [ticket here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/23199)

**Comment by rebeccawalsh** [comment]
@LinnJS There are no more updates since this was submitted, as far as I'm aware.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/compare/LinnJS-FSR-wizzard-content-bugs?expand=1) where this work is being done.

**Comment by LinnJS** [comment]
Note: crossed out acceptance criteria was already updated.
