### ISSUE TITLE
FSR form submission in production is failing.

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#23213]
## Issue Description
The FSR form submission from the UI in production is failing because the `vets-api` is calling an incorrect URI when making a request to the Debt Management Center API; The URI for the DMC URL is configured incorrectly in the Production Settings file.

---
## Tasks
- [x] _Make the configuration change in the production settings file to include the correct production URI for the Data Management Center provided by Pavan: /api/v1/digital-services/_
- [x] _Change the debts_endpoint to debt-letter/get as per Pavan's recommendation._
- [x] _Verify the above changes in the DevOps branch with Pavan and Craig Wheeler_
- [x] _Create a pull request against the DevOps repo with the above changes and get it merged back into master._
- [x] _Verify that the FWD proxy hostname for the DMC API is valid and active_
- [x] _Verify that the FWD proxy hostname for the DMS API maps back to the DMC  gateway.dmc.va.gov host_
- [x] _Verify that the clients production `client_id` and `client_secret` are still valid in the DMC API_
- [x] _Conduct limited endpoint integration testing against the production DMC API endpoints via Postman and verify that the remote service responds to our calls._

## Acceptance Criteria
- [x] _Completion of all tasks_
---

**Comment by dillo** [comment]
PR created: https://github.com/department-of-veterans-affairs/devops/pull/8956
