### ISSUE TITLE
Update KMI confirmation emails

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23210]
## Issue Description
We need to update the confirmation emails to reflect the latest situation in terms of vaccine supply and coming into a VAMC. These changes pull from already approved content.

---
## Tasks
- [x] Update content (Danielle)
- [x] Review for errors (Randi)
- [ ] Update templates (Maria, Todd, and team)
- [ ] Review templates (Danielle, Randi)

## Acceptance Criteria
- [ ] Confirmation emails are updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Could you review these before Maria and team update? Thank you!

[KMI confirmation email_enrolled_04.13.21 updates](https://app.zenhub.com/files/133843125/64a399c0-c45f-4b3a-b38c-f875f6c4f4d0/download)

[KMI confirmation email_new SLA non-enrolled_04.14.21 changes](https://app.zenhub.com/files/133843125/326ba0e9-ce8c-423b-b578-004f682b24a7/download)

FYSA @lalexanderson-dsva @batemapf @clantosswett @shanemelliott

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA There were no changes to the first email but I had minor tweaks to the second. 
[KMI confirmation email_new SLA non-enrolled_04.14.21 changes 2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6319441/KMI.confirmation.email_new.SLA.non-enrolled_04.14.21.changes.2.docx)

**Comment by DanielleThierryUSDSVA** [comment]
This is an old ticket and all related work is completed. Closing.
