### ISSUE TITLE
COE - Gate Application Behind Authentication

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#23225]
## Description
Because our application relies heavily on user data, we want to gate it behind login. 

## Considerations
- pass the ` hideUnauthedStartLink` prop to `SaveInProgressIntro` ✔
- read URL and redirect to `/introduction` if user is unauthenticated and on a form route

## Tasks
- [x] pass the ` hideUnauthedStartLink` prop to `SaveInProgressIntro`
- [x] read URL and redirect to `/introduction` if user is unauthenticated and on a form route

## Acceptance Criteria
- [x] tasks have been completed
- [x] PR has been submitted

**Comment by jason-gcio** [comment]
(Future @jason-gcio) this is a good one to templatize

**Comment by jason-gcio** [comment]
This was mentioned as a task in (#23958) but left alone there for this ticket
