### ISSUE TITLE
Build the Forms KPI Dashboards in Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#23221]
## Issue Description
Create the Forms KPI Dashboard so that we can test our build SLAs and VFS teams can start using our new Forms KPI Dashboards "MVP."

---
## Tasks
- [ ] Create new datasets for Forms Funnels & Engagement
- [ ] Create any new calculations
- [ ] Create new cards for the dashboard
- [ ] Apply the designs to the dashboard & build out the funnels
- [ ] QA the data 
- [ ] QA the designs/content

## Acceptance Criteria
- [ ] VFS teams can test the Forms KPI Dashboards with real data

**Comment by joanneesteban** [comment]
@JasonTheBearded to tag the team when ready for QA.

**Comment by joanneesteban** [comment]
## MVP Priority List:

(Head's up, I'm attaching the GH issues, but the scope for this is the _standard_ KPIs from the prototype.)

1. [HLR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19844)
2. [Debt Letters](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13404)
3. [Education - 1995](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18316)
4. [Healthcare](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23194) - this one's less urgent, but it's also the most complicated form/funnel + it's one of the top used forms on the website, so it's a good one for us to tackle.
5. [VAOS](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19846)[- Distribution Pilot](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20129) - this one may be more of a "tool," and not necessarily fit into Forms
6. [BDD](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19846)
7. [FSR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22375)
8. [VAOS - Community Care](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18828)
9. [VAOS](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19902) - Overall product dashboard iteration

---
Already in Domo, and will eventually need iterations:

10. [eBenefits](https://va-gov.domo.com/page/1726972169) 
    a. Dependency Claims - 686
    b. Personalized Career Planning & Guidance (Ch36)
11. [Education 10203](https://va-gov.domo.com/page/558555603)
12. [Caregiver](https://va-gov.domo.com/page/1905395623)
13. [Debt Management](https://va-gov.domo.com/page/74130670) - Might be more of a tool than a Form

If you have any issues with anything on this list, feel free to skip it and document the issues in the ticket, @JasonTheBearded ! (Like if I'm marking something on here that's not a Form or doesn't take the same funnel standards)

**Comment by joanneesteban** [comment]
@JasonTheBearded 's [Standard Forms Funnel ETL in Domo](https://va-gov.domo.com/datasources/432a85a7-5581-4e80-8601-dc13c9654436/details/overview?internal=true).

**Comment by joanneesteban** [comment]
@mandy-uxd to share the 2nd design iteration.

**Comment by JasonTheBearded** [comment]
[Standard Forms Engagement in Domo](https://va-gov.domo.com/datasources/f256e93e-e0ff-4d69-bd69-404f98bc335b/details/overview) - View goes back to April 1, 2021 for testing purposes

**Comment by JasonTheBearded** [comment]
[All Cards](https://docs.google.com/spreadsheets/d/1fi2p1XMLNqaejyEqWRjk4PgfvU40pBvBMTYJ5yfG_gE/edit#gid=0) to be built for the Forms KPI Dashboard.

**Comment by joanneesteban** [comment]
## Doing vs. Done
@JasonTheBearded @chloedotbrown - please feel free to edit this comment to add any notes about any dependencies or blockers with any of the ones you're working on.

- [ ] HLR
- [ ] Debt Letters
- [ ] Education - 1995
- [ ] Healthcare - 
- [ ] VAOS- Distribution Pilot 
- [ ] BDD
- [ ] FSR
- [ ] VAOS - Community Care
- [ ] VAOS - Overall product dashboard iteration
- [ ] eBenefits
- [ ] -Dependency Claims - 686
- [ ] Personalized Career Planning & Guidance (Ch36)
- [ ] Education 10203
- [ ] Caregiver
- [ ] Debt Management 

[Google Sheet](https://docs.google.com/spreadsheets/d/1dIh-MVmVYCc2mZ_b_8y-cPVZB5-8RIShuOP_ng9uqAA/edit#gid=0) for user journey/funnel steps.

**Comment by JasonTheBearded** [comment]
Build complete, closing ticket.
