### ISSUE TITLE
COE - Automatic COE Generation Investigation

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#23223]
## Description 
As a user, I expect VA to have all the necessary information needed to provide me with a COE. Because of this, I want a COE to be automatically generated instead of having to walk through a form and fill out information VA already has on file. 

## Considerations
- [Prototype](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137653432/simulate/sitemap)
- Before a user is presented with a form, we should check and see if we have all needed information to generate a COE for them. 
- COE uses [VA Form 26-1880](https://www.vba.va.gov/pubs/forms/VBA-26-1880-ARE.pdf)

## Tasks
- [ ] Determine what pieces of information are needed to generate a COE
- [ ] If all information is present, determine if an API request is needed to generate a COE

## Acceptance Criteria
- [ ] All tasks have been completed
- [ ] Document containing list of required data needed to generate COE added to eben folder
- [ ] Confirmation of whether or not an API request is needed to generate a COE

**Comment by micahchiang** [comment]
- Are the endpoints for automatic certificate generation and 26-1880 different? If they aren't, can we rely on automatic cert generation being sent back to the frontend in the same user session?

**Comment by micahchiang** [comment]
Uploaded LGY architecture docs - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE

**Comment by micahchiang** [comment]
Notes from 4/29/21 LGY meeting - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/engineering-notes.md

Answers the question of whether or not COE auto-generation happens on our side or LGY side. eBen team will be responsible for generating COE based on whatever the call to LGY returns.
