### ISSUE TITLE
COE - Implement Certificate Autogeneration

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#23224]
`this may go away or change to accommodate incoming pdf`

## Description
As a user, I expect to have a COE autogenerated because VA has all of my information on file. 

## Considerations
- Should be completed after https://github.com/department-of-veterans-affairs/va.gov-team/issues/23223
- [Prototype](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137653432/simulate/sitemap)
- If API request is necessary, implement Actions and Reducers in redux

## Tasks
- [ ] If API request is necessary, implement Actions and Reducers in redux
- [ ] ~~Build COE autogeneration feature~~ VRE API folks are building this

## Acceptance Criteria
- [ ] Above tasks have been completed
- [ ] PR submitted

**Comment by micahchiang** [comment]
Bulk of the work here will be merged in with #25545. Remaining work to be done in this ticket is wiring up the actual API call and refactoring existing frontend code to accommodate returned payloads.
