### ISSUE TITLE
COE - Unit test form pages

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#23229]
## Description
As engineers, we want to unit test our form pages to ensure they work as expected and to know whether or not future changes break functionality.

## Tasks
- [x] Write unit tests for each form page

## Acceptance Criteria
- [x] tests are written and passing
- [x] PR submitted into vets-website

**Comment by jason-gcio** [comment]
If there will be changes to the form layout, these will need to be updated.
