### ISSUE TITLE
COE - Migrate form schema to vets-json-schema

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#23226]
## Description
The COE is a form application, thus, the schema for it should live in `vets-json-schema`

## Considerations
- This ticket should be done after https://github.com/department-of-veterans-affairs/va.gov-team/issues/23216

## Tasks
- [x] Add new form schema has been added to `vets-json-schema`
- [x] Remove schema from `vets-website`
- [x] Submit PRs to `vets-json-schem`a, vets-website, and `vets-api`

## Acceptance criteria
- [x] Tasks have been completed

**Comment by jason-gcio** [comment]
might want to wait until we are sure the format isn't going to change
