### ISSUE TITLE
[FSR] Global form content updates

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23237]
## Issue Description
_The FSR's needs some global content updates per Peggy's staging review feedback. Since we're proceeding with a second iteration post-usability recommendations, we need to make sure the changes suggested in production align with the prototype._

---
## Tasks
- [x] Update 'Social security' to 'Social Security' throughout the form
- [x] Change “Compensation & Pension” TO: Disability compensation and pension debt (Debt selection, resolution request, etc)
- [x] Ensure 'Postal code' is used to account for non-US addresses

## Acceptance Criteria
- [ ] _The content changes have been incorporated and checked off_

**Comment by rebeccawalsh** [comment]
Changes reflected in the SFT sketch file and in [UXPin here](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139690652/simulate/no-panels?mode=i)
