### ISSUE TITLE
[FSR] Global form content updates

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23236]
## Issue Description
_The FSR's needs some global content updates per Peggy's staging review feedback. Since we're proceeding with a second iteration post-usability recommendations, we need to make sure the changes suggested in production align with the prototype._

---
## Tasks
- [ ] Update 'Social security' to 'Social Security' throughout the form
- [ ] Change “Compensation & Pension” TO: Disability compensation and pension debt (Debt selection, resolution request, etc)

## Acceptance Criteria
- [ ] _The content changes have been incorporated and checked off_

**Comment by rebeccawalsh** [comment]
This is previously completed.
