### ISSUE TITLE
[FSR] Global form content updates

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23234]
## Issue Description
_The FSR's needs some global content updates per Peggy's staging review feedback._

---
## Tasks
- [x] Update 'Social security' to 'Social Security' throughout the form
- [x] Change “Compensation & Pension” TO: Disability compensation and pension debt (Debt selection, resolution request, etc)
- [x] Ensure 'Postal code' is used to account for non-US addresses

## Acceptance Criteria
- [x] _The content changes have been incorporated and checked off_

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16975) where this work was done forgot to close the ticket.
