### ISSUE TITLE
COE - Write e2e tests for COE form

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#23230]
## Description
As engineers we want to ensure our application UI works as expected, and be notified if any future changes break expected functionality.

## Considerations
- tests need to be skipped until application is included in production build

## Tasks
- [ ] Write Cypress e2e tests for all possible form flows

## Acceptance Criteria
- [ ] tests have been written and are passing
- [ ] PR has been submitted to vets-website

**Comment by jason-gcio** [comment]
https://int.services.lgy.va.gov/eligibility-manager/swagger-ui/index.html?configUrl=/eligibility-manager/v3/api-docs/swagger-config
