### ISSUE TITLE
Direct schedule confirmation (Homepage Refresh)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23246]
## Description
Update direct schedule appointment confirmation page to match appointment details design. 

---
## Tasks
- [ ] VA direct
- [ ] Vaccine direct

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag

- [ ] Given VA direct schedule, When submission is successful, Then show confirmation page
- [ ] Given vaccine direct schedule, When submission is successful, Then show confirmation page
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/confirmation-copy.md#homepage-refresh-toggle) 
- [ ] DESIGN - Designs match the specs (copy is FPO)

VA direct
- Desktop 
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rbMdaRx) 
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/jgkqJZ0) 

Vaccine direct
- Desktop 
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/v8EvkYb) 
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/m18qe4J) 

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by LeKeve** [comment]
This ticket appears to be blocked by [23767](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23767). I don't believe we can redirect to the appointment details page without the id from the confirmed appointment.

**Comment by jbalboni** [comment]
@LeKeve You're correct that we ultimately want to redirect to that page, but since we can't do that, this ticket is to update the current direct schedule confirmation page to match the design of the `appointments/va/:exampleId` page, when the homepage refresh flag is on.

**Comment by LeKeve** [comment]
Got it. Updated the ticket description. 

It looks like appointment cancelation on the confirmation page won't be possible without an id. Will note on PR to reflect that difference from the design specs.
