### ISSUE TITLE
[FSR] Content changes by page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23247]
## Issue Description
_Some of the FSR's individual pages need content updates per Peggy's staging review feedback. Since we're proceeding with a second iteration post-usability recommendations, we need to make sure the changes suggested in production align with the prototype._

---
## Tasks
**Introduction page**
- [x] _CTA button on intro page should be: Start your request now_

**Available debts**
- [x] Remove the second sentence in the intro paragraph: `You will be able to choose a repayment option for each debt you select.` as it repeats the one above it

**Resolution options**
- [x] Move header: "Your financial overview" into the blue box to more closely tie the header to the content in box.
- [x] Change “Compensation & Pension” TO: Disability compensation and pension debt

**Review screen**
- [x] Update submission CTA to: "Submit your request"
- [x] Add the privacy policy checkbox: I have read and accept the privacy policy - need to get the link from Peggy or another form

**Confirmation screen**
- [x] Go Back to VA.gov button should follow sentence-case guidelines. It should be: Go back to VA.gov

## Acceptance Criteria
- [x] _The outlined content changes have been incorporated and checked off in this ticket_

**Comment by rebeccawalsh** [comment]
All changes are reflected in the UXPin here: https://preview.uxpin.com/b4745b18da61eee6b2c74af081afe3aec6cbd685#/pages/?mode=i
