### ISSUE TITLE
[BE] Direct deposit for edu: Look into why the failed retrieval rate is so high

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23248]
## Background

For [direct deposit for edu](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/), the rate at which we are failing to successfully retrieve user's direct deposit for ed info is about 13%. This is really high, way higher than the failed retrieval rate for direct deposit for comp & pen (about 4%).

We need to look into why the failure rate for direct deposit for edu is so high and determine if there is anything we can do about it.

![Screen Shot 2021-04-14 at 4.51.12 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/e83d59d4-7d9f-4c9f-803c-ef4b4ce93596)

## Tasks

- [ ] Look into why the failure rate for direct deposit for edu is so high
- [ ] Determine next steps
- [ ] If there is something we can improve/fix, implement the fix

**Comment by lihanli** [comment]
@erikphansen do you know what causes a failed retrieval event to happen? in the last 14 days i see about 283 errors caused by the bgs downtime and about 95 caused by another issue, but i'm not seeing 1200 errors. there are often errors retrieving the bank name, but in those cases vets-api still returns a 200 but with the bank name set as null.

**Comment by Samara-Strauss** [comment]
Could this be an issue of recording events more than once similar to the tracking issues we had a few months back with contact information?

**Comment by erikphansen** [comment]
@lihanli We record DD4EDU fetch errors a fairly standard way. If we get a non-200 from the `GET profile/ch33_bank_accounts` we will report and error to GA. https://github.com/department-of-veterans-affairs/vets-website/blob/e4b533608d5a279a36da39da0e719a780c9be95c/src/applications/personalization/profile/actions/paymentInformation.js#L181-L184

**Comment by lihanli** [comment]
> @lihanli there was a [huge spike in failed retrievals on Saturday](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last7days&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventAction:Profile%20-%20EDU%20Direct%20Deposit%20Retrieval%20Failed/). It appears to have resolved by Sunday, so hopefully not indicative of a longer term problem. Can you look into what caused this?
> 
> ![Screen Shot 2021-04-19 at 1.20.55 PM.png](https://camo.githubusercontent.com/5f755269542f65a05e1c6272370a61a9c27938df23289651fabcad6e63a3f058/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561346535653333613031366335623033346263303735302f33366633323166632d613636302d346335612d623939342d666665666235303364376537)

starting on 4/17 we received a lot of errors from their server with this message "findCh33DdEft error: String index out of range: -1", the errors stopped happening on Apr 18, 2021 3:43:49 PM UTC, it looks like they fixed the bug in their api that caused these errors

**Comment by Samara-Strauss** [comment]
Got it. I'll note this as a BGS error in the analytics. Thank you!

**Comment by lihanli** [comment]
> @lihanli We record DD4EDU fetch errors a fairly standard way. If we get a non-200 from the `GET profile/ch33_bank_accounts` we will report and error to GA. https://github.com/department-of-veterans-affairs/vets-website/blob/e4b533608d5a279a36da39da0e719a780c9be95c/src/applications/personalization/profile/actions/paymentInformation.js#L181-L184

the discrepency could be caused by authentication errors, those aren't logged in sentry, if the user became logged out due to inactivity, or if they aren't loa3 and have MFA on. it could also be caused by the user not having the backend feature flag turned on for direct deposit, i had already turned it on for everyone but maybe it was accidentally turned off?
i made an issue for removing it from the codebase just in case: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23448

**Comment by ajakabcin** [comment]
Closing this for now as we determined the cause for the initial spike.
