### ISSUE TITLE
DISCOVERY: Placeholder events break FE builds

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23258]
## Issue Description
Current hypothesis: When past events are archived, the FE build breaks. An event page should be able to exist without any events (past or current). 

See [Erie](https://www.va.gov/erie-health-care/events/) 

## Desired behavior:

- [ ] if no future events exist, events page says "no events"
- [ ] if no past events exist, past events page builds saying "no past events"
- [ ] if past events exist and then get archived, events page says "no events"

## Tasks:
- [x] Examine current behavior using tugboat environment for testing
- [x] Run builds locally and document any bugs
- [x] Work with CMS to come up with a solution

**Comment by mpelzsherman** [comment]
My recommendation (already approved by @davidconlon) is to simply remove the Past Events toggle if there are no past events.

Here's how the page would look with 0 events total:

![VA_Erie_Health_Care___Events___Veterans_Affairs](https://user-images.githubusercontent.com/80267/115433844-fd04fa80-a1d5-11eb-87a6-83d7d24b902f.png)

There is a bug in the code that is populating our `pastEvents` array in the template even though there are no past events. Once that has been fixed, we can show upcoming events without the toggle as well.
