### ISSUE TITLE
[Discovery / Design] Preferred facility designs and research

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23257]
## Description
Epic to house discovery and design epics and tasks related to the preferred facility / facility selection work.

---

## Artifacts

- [x] User Research Prototypes: 
    - [Scenario 1](https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669675)
    - [Scenario 2](https://adhoc.invisionapp.com/console/share/B72LX6SPTP/633532185)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/conversation-guide.md)
- [x] [Research synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/research-findings.md)
