### ISSUE TITLE
Include only published event content in FE build

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23256]
## Issue Description
Broken link investigations uncovered a FE defect in which unpublished (either draft, in review, or archived) content shows up on prod va.gov.  This causes accessibility and usability issues, broken links and build problems. 

Examples: 
Events - Placeholder events are being created and then archived. (ie: [Test Outreach](https://www.va.gov/erie-health-care/events/test-outreach/) on Erie health care)
- Node 9483

The CMS team has issues in the backlog to prevent duplicate content from being created in this way in the future, but the unpublished content problem is independent of that.

Content can be deleted to eliminate the immediate problem ([AXE-CORE]: VAMC - Accordions need unique labels #21789)

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/114779802-c8a3c100-9d33-11eb-97cc-c71d307462d9.png)

</details>

---
## Tasks
- [ ] Ensure archived and/or draft events are not added to build
- [ ] Add filter to GraphQL to build published content only. 

## Acceptance Criteria
- [ ] Unpublished (draft) content is not added to the build. 
- [ ] Archived content is not added to the build. 
- [ ] Only published content appears on the Events listing page (and creates a page for the event itself)
- [ ] When I create a draft event, it does not appear on the listing page (or create a page for the event itself)
- [ ] When I archive an event, it does not appear on the listing page (or create a page for the event itself)
- [ ] Archiving or creating events does not cause broken links.

**Comment by mpelzsherman** [comment]
This appears to be a dupe of #21762, or was at least resolved by the same [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16876).

#21789 is a different issue, completely unrelated to Events.
