### ISSUE TITLE
Update KMI confirmation screens

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23278]
## Issue Description
We need to update the KMI confirmation screens based on latest supply situation.

---
## Tasks
- [ ] Update content in Word docs (Danielle)
- [ ] Review for errors (Randi)
- [ ] Update screens (Patrick, Stephen)
- [ ] Review PR (Danielle, Randi)

## Acceptance Criteria
- [ ] Screens updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Morning, @RLHecht! Here's the first of 2 Word docs with some minor changes to the KMI confirmation screens to align with latest supply situation. Could you review for any errors before I pass along? Will post 2nd doc shortly. Thank you!

[SLA flow_confirmation screen_04.14.21 changes](https://app.zenhub.com/files/133843125/57b98cee-2087-4394-ae69-8c6a5b1ad333/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here you go. I just had two changes. 
[SLA flow_confirmation screen_04.14.21 changes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6318537/SLA.flow_confirmation.screen_04.14.21.changes.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @RLHecht! @stephenBarrs  @batemapf Could you update the confirmation screen for the SLA flow as reflected in the doc in Randi's doc above?

Also, could you share here the current confirmation screen here? I want to make sure I'm working from the latest version. Thank you!

**Comment by batemapf** [comment]
I'll pick this one up!
