### ISSUE TITLE
[FSR] Content to update FSR's 'find a form' results page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23292]
## Issue Description
_With the FSR's release coming up, we need to ensure it's findable in multiple places on VA.gov. One area we need to request an update is on [the form's 'find a form' result page](https://www.staging.va.gov/find-forms/about-form-5655/). We should provide content that aligns with [VA form 526-EZ's result page](https://www.staging.va.gov/find-forms/about-form-21-526ez/)._

---
## Tasks
- [x] _Draft the content per Marci's instructions:_

> All we need is a description of what the tool is used for, the URL for the new tool, and when that should be put into place. 

- [x] _Have the content reviewed by Troy to verify it aligns with the style guide_
- [x] _Draft up ticket including finalized content and assign it to Marci_

## Acceptance Criteria
- [x] _Ticket containing finalized content is drafted for Marci and linked in this ticket_

**Comment by rileyorr** [comment]
My proposal for [the FSR's 'find a form' page](https://staging.va.gov/find-forms/about-form-5655/) updates: 

**Title change:** About VA Form 5655

**Related to:** Unsure what guidelines determine what we put here. I looked at multiple results and some listed 1-2 categories while other listed many. Going to reach out to Marci when I make the ticket to see how that team determines what to include in the list.
My thoughts on what we might want to include:
- Debt Management 
- Veteran’s Benefits Administration
- Veteran’s Health Administration
- Disability
- Pension
- Health Care

**When to use this form**
Use VA Form 5655 if you’re a Veteran or service member who needs help with debt related to VA disability compensation, education, or pension benefits. You can use this form to request a payment plan, compromise offer, or waiver. 

**URL:** va.gov/manage-va-debt/request-debt-help-5655/  

**When to put in place:** TBD based on whenever the UAT issues are resolved

There's also a 'helpful links' section at the bottom of the page - we should update to include both the debt management portal and VA copay pages. 

@rebeccawalsh lmk your thoughts and if you'd include other improvements to the page.
@troyriser can you provide a content spot-check on the 'When too uses this form' section? I based it off [the 526-EZ's page](https://staging.va.gov/find-forms/about-form-21-526ez/) and [the 10-10EZ's page](https://www.va.gov/find-forms/about-form-10-10ez/).

**Comment by troyriser** [comment]
Riley,

 

The only change I recommend would be to insert ‘other’ in the following so it reads:

Get your VA records and documents online <https://staging.va.gov/records/> 

Learn how to access your VA records, benefit letters, and other documents online.

 

The reason for the addition of ‘other’ is because VA records and  benefit letters are also documents. 

 

Thanks,

 

Troy.




	Troy Riser  
Business Analyst - VA ES PMO DevOps

| mobile (317) 439-2808
| e. ***@***.***CIO.com ***@***.***CIO.com> 

GovernmentCIO
 <https://www.governmentcio.com/> website |  <https://governmentciomedia.com/> media |  <https://www.governmentcio.com/services> services |  <https://careers-governmentcio.icims.com/> jobs |  ***@***.***,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121> map 

 <https://twitter.com/GovernmentCIO>  <https://www.facebook.com/GovernmentCIOMedia>  <https://www.linkedin.com/company/governmentcio>  <https://www.youtube.com/user/GovernmentCIO/videos>  <https://www.instagram.com/gciotalent> 

Confidentiality Note: This email may contain confidential and/or private information. 
If you received this email in error please delete and notify sender.

**Comment by rileyorr** [comment]
Drafted [the ticket with the finalized content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24098)
