### ISSUE TITLE
[FSR] Review and update error messages so they align with VA.gov's content style guide

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23299]
## Issue Description
_As part of the FSR's content staging review, we learned that the error messages included in the form do not align with our content style guide. We need to review the error messages and adjust them as needed._

---
## Tasks
- [x] _Review [the errors outlined in this document](https://docs.google.com/spreadsheets/d/1fi9aV1YdRQRfvLOFmZUFctvzYpkTRH0RQjQ2SPlq-d4/edit?usp=sharing) to ensure they align with [the content style guide](https://design.va.gov/content-style-guide/error-messages). Make adjustments as needed._

## Acceptance Criteria
- [x] _All errors outlined in the document have been reviewed and updated as needed_
- [x] _The frontend ticket has been updated if necessary_

**Comment by troyriser** [comment]
@LindaLi123 @rileyorr @rebeccawalsh @craigwheeler FSR error messages have been reviewed and revised. Revision summary follows with updated MS Excel spreadsheet attached.

References used:

VA.gov Content Style Guide
US Government Publishing Office Style Manual
OIT Documentation Style Guide
Federal Plain Language Guidelines

Revision Summary:

"Please enter a numerical value." has been changed in 21 instances throughout to "Please enter only numerical values." where the user enters special characters or letters. The language is now more concise in accordance with Plain Language dictates.

Line 101: Re "Do you currently own other assets?" query, "Please enter your assets information." has been changed to "Please enter your other assets information." for internal consistency.

Re C5P1 on lines 131-137, questions beginning with "What type of help do you want for your Post-9/11 GI Bill debt for tuition and fees?" and ending with "How much can you afford to resolve this debt?", messages have been revised by replacing the verb 'provide' with 'enter' for internal consistency.

Line 133: Re query "How much can you afford to pay monthly on this debt?", the error message has been revised from "Please provide a response." to "Please enter the amount you can pay monthly."

Line 135: Re query "How much can you afford to resolve this debt?", the error message has been revised from "Please provide a response." to "Please enter the amount you can afford to resolve this debt."

Line 136: Re query "How much can you afford to resolve this debt?", the error message has been revised from "Please provide a numerical value." to "Please enter only numerical values."

[https://app.zenhub.com/files/133843125/a92bac4f-139e-4f0b-befb-0aab47dd3767/download](https://app.zenhub.com/files/133843125/a92bac4f-139e-4f0b-befb-0aab47dd3767/download)

**Comment by rileyorr** [comment]
@LindaLi123 I updated the frontend ticket; closing this one.
