### ISSUE TITLE
[FSR] Add Privacy Act information to both the form's intro page and review page

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23297]
## Problem statement

VA.gov forms need to provide the Privacy Act in two areas:
- On the introduction page as a modal
- On the review page as a required checkbox 

## Tasks
- [ ] Add a checkbox for accepting the privacy policy on the review page. This is standard across forms and is a blocker to release. The link should point to [the privacy policy page](https://.va.gov/privacy-policy/) and open in a new tab when clicked. 
[Reverence the design in UXPin here](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134117869/specification/sitemap)

### Screenshot(s) 

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/564f21c2-0e8e-42d0-abb7-fff0df67e326)

- [ ] Add a link 'Privacy Act Statement' on the form's introduction screen below the expiration date, above the 'Need help' component. When the link is clicked, it should open a modal containing the Privacy Act Statement and Respondent Burden from the FSR. That content can be copied from [the PDF version of the form](https://www.va.gov/find-forms/about-form-5655/). You can reference an example of the Privacy Act Statement modal on [the 10-10EZ's introduction page](https://www.va.gov/health-care/apply/application/introduction).
[Reference the design in UXPin here](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701378/specification/sitemap?mode=i)

### Screenshot(s)
![privacy act statement.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/9651eac4-4c0c-4738-adbf-f9591bd18590)

### Privacy Act content from FSR
![FSR privacy act statement.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/c129e1ca-ff89-47eb-b25a-f78b87a8da30)

## Acceptance criteria
- [ ] The privacy act checkbox has been added to the form's review submission screen and opens the provided privacy act page in a new tab
- [ ] The privacy act link has been added to the form's introduction page and opens a modal containing the provided content 
- [ ] Reach out to either Becca or Riley once the changes are merged into staging
