### ISSUE TITLE
Alerting - Set up alerts for replica sets in EKS

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23309]
## Description
We need to set PagerDuty to alert on replica set monitors that exist in DataDog. 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Figure out how to make alerts from DataDog for replica set monitor thresholds being exceeded 

## Definition of Done
- [x] Alerts appear in Slack when thresholds are exceeded for replica sets 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jbritt1** [comment]
@mleclerc00 did some awesome work to wrap this one up. An example of what these alerts look like in their current state can be found below:

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/f37aaffb-30fb-464e-9cc2-4ec4ab57e083)
