### ISSUE TITLE
[Design, PM] My VA: Finish Contact Center guide

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23308]
## Background
In preparation for launch of My VA redesign, we need to complete the guide for the contact center so that they are able to help veterans when they call for support. We completed a first draft/iteration last sprint and want to complete it this sprint.

## Tasks
- [x] Complete content
- [x] Get an internal review 
- [x] Review with Samara
- [x] Submit to contact center

**Comment by tressaellen** [comment]
@Samara-Strauss here is the [contact center guide](https://docs.google.com/document/d/1mAZiVsYkbUnqYhCOIY6n36ZfeUeX2inkufpyQZBns4M/edit?usp=sharing).

**Comment by tressaellen** [comment]
Thank you! Yep, we went back and forth about keeping the section overviews, but we can combine them. I'll send you an updated doc once we have that done.

**Comment by Samara-Strauss** [comment]
Sounds good! Thanks!

**Comment by tressaellen** [comment]
Okay, I've combined those sections and added your edits and a few that I caught as well. I still need to update some of the screenshots, but I think we're close. 

[https://app.zenhub.com/files/133843125/e6d8ba9b-5bcd-49f4-b7fe-f5a92c6e286d/download](https://app.zenhub.com/files/133843125/e6d8ba9b-5bcd-49f4-b7fe-f5a92c6e286d/download)

**Comment by Samara-Strauss** [comment]
Great! I'll take a look at it.

**Comment by Samara-Strauss** [comment]
Attached are my most recent round of edits.

[My VA contact center guide_Samara's edits_4.27.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6387241/My.VA.contact.center.guide_Samara.s.edits_4.27.21.docx)

- One of my major edits was to bold links and remove them from single or double quotation marks. This makes references to links a lot easier to scan for. There were also some spots where section titles were in quotes and not bolded, so I fixed those. Please be extra mindful of this formatting. That consistency matters and makes the doc much easier to scan.
- **Question**: do we change the order of the health care links based on whether someone has appointments but none in the next 30 days and whether someone has no appointments scheduled at all? I noticed that the screenshots for these two use cases had the **Schedule and view your appointments** link in two different spots — one had it first and one had it second in the list of links. IMO, I think this link should always appear in the same spot regardless of whether they have no appointments in the next 30 days or no appointments at all.

**Comment by tressaellen** [comment]
Thank you! I'm updating everything still and will post the latest and greatest later today. 

> Question: do we change the order of the health care links based on whether someone has appointments but none in the next 30 days and whether someone has no appointments scheduled at all?

They should be in the same order, and they are not in the same order in the prototype. I'm trying to validate on staging that they're in the same order, but the user we've used for having no appointments in the next 30 days now has appts in the next 30 days... I'll need to work with Erik to make sure that they don't change orders for those two use cases.

**Comment by Samara-Strauss** [comment]
> They should be in the same order, and they are not in the same order in the prototype. I'm trying to validate on staging that they're in the same order, but the user we've used for having no appointments in the next 30 days now has appts in the next 30 days... I'll need to work with Erik to make sure that they don't change orders for those two use cases.

Got it! I figured it might just be a prototype/mockup issue. User 226 doesn't have appointments if you need someone without appointments but that does have health care.

**Comment by tressaellen** [comment]
Okay, I've updated everything with your edits as well as all of the screenshots. Let me know if you have any last edits. 

[https://app.zenhub.com/files/133843125/36c2e767-0a1e-466f-8952-008edab660c4/download](https://app.zenhub.com/files/133843125/36c2e767-0a1e-466f-8952-008edab660c4/download)

I also chatted with Erik about the order of the health care links, and they're the same in both use cases so we should be good there. :)

**Comment by Samara-Strauss** [comment]
These are my final updates. Nothing major, and I don't need to review again unless there are major changes. Great job! The guide looks great :D 

[My VA call center guide_Samara's edits_4.28.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6394530/My.VA.call.center.guide_Samara.s.edits_4.28.21.docx)

**Comment by ajakabcin** [comment]
Submitted contact center guide #24153
