### ISSUE TITLE
Update the Overview page in the Documentation section of design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#23301]
## Issue Description
Update the overview page content 

---
## Tasks
- [x] Review all content in this section 
 - [x] Draft content as needed
 - [ ] Have content changes reviewed by team member 
 - [ ] Update content categorization and structure as needed
 - [ ] Post updates on design.va.gov 

## Acceptance Criteria
- [ ] Overview page of the documentation section on design.va.gov is updated 
---
Note from discussion: 

- What’s new  Should be the homepage of documentation

**Comment by KevinMHoffmanUSDS** [comment]
@rtwell Could you review this page for me? Or anyone on the team who has the bandwidth.  

https://docs.google.com/document/d/1qCeHX4wtul37SOiyyUnsKIryW6GaXNw6V9g-DC9iIDo/edit?usp=sharing

**Comment by rtwell** [comment]
My only feedback is I think it would be good to include something describing how the design system is always evolving, a living document, etc etc
