### ISSUE TITLE
Update the Code and Design files page in the Documentation Section of DS

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#23303]
## Issue Description
Update the Code and Design files page in the Documentation Section of DS

---
## Tasks
 - [ ] Review all content in this section 
 - [ ] Draft content as needed
 - [ ] Have content changes reviewed by team member 
 - [ ] Update content categorization and structure as needed
 - [ ] Post updates on design.va.gov 

## Acceptance Criteria
- [ ] Code and Design Files page of the documentation section on design.va.gov is updated 
---

**Comment by CrystabelReiter** [comment]
- Rename this page "code and design resources"
- Separate out these into 2 sections:
for designers 
- We'll include sketch for teams documentation here
for developers

**Comment by CrystabelReiter** [comment]
Working draft: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_documentation/code-and-design-resources.md
