### ISSUE TITLE
Centralized Logging - Enable Observability & Alerting for Loki 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23307]
## Issue Description
As an devops engineer, I need to monitor the health and performance of Loki receive alerts when thresholds are exceeded. 

---
## Tasks
- [x] Set up monitoring of basic resources like CPU, Memory, Etc
- [x] Set up Loki-specific monitors for things like log ingestion, etc
- [x] Set up alerts in PagerDuty (start by sending to #vsp-kubernetes-alerts-test) 
- [ ] Enable alerts, ensuring that we don't spam on-call personnel or support channels with spurious alerts

## Acceptance Criteria
- [ ] Alerts will be sent to devops-alerts whenever Loki thresholds are exceeded

**Comment by jhouse-solvd** [comment]
@mydesignrocks - is this still something that can be worked on during this Sprint?

**Comment by jhouse-solvd** [comment]
@mydesignrocks - if you can cross-reference any PRs, add notes, and check off tasks to help show status on this one, that would be very helpful. no rush. thank you, sir.

**Comment by mydesignrocks** [comment]
these are the queries I have included for loki within DD:

avg(last_5m):( ( 300 - avg:kubernetes.cpu.usage.total{kube_namespace:loki} by {pod_name,kube_cluster_name} ) / 300 ) * 100 > 90

avg(last_10m):100 - ( ( max:kubernetes.memory.requests{kube_namespace:loki} by {pod_name,kube_cluster_name} - max:kubernetes.memory.usage{kube_namespace:loki} by {pod_name,kube_cluster_name} ) / 
max:kubernetes.memory.requests{kube_namespace:loki} by {pod_name,kube_cluster_name} * 100 ) > 90

sum(last_1m):max:kubernetes.pods.running{kube_namespace:loki} by {kube_deployment,kube_cluster_name} <= 0

**Comment by mydesignrocks** [comment]
![image](https://user-images.githubusercontent.com/69813558/123899342-02e52d80-d935-11eb-914b-60019aa6567e.png)

**Comment by mydesignrocks** [comment]
https://app.datadoghq.com/monitors/manage

**Comment by mydesignrocks** [comment]
As of now, these alerts are muted as we go into adjusting hpa and other resources utilization.

**Comment by jhouse-solvd** [comment]
We've re-scoped the remaining tasks and created a new ticket that better approaches what's left to do: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28803

Closing.
