### ISSUE TITLE
Implementation: Combined Profile and Account

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2330]
## User Story or Problem Statement
As an authenticated product owner, I want to understand the time-to-task completion in the current state where profile and account are separated vs. future state, when they are combined on one page.

## Goal
The outcome is to measure time-to-task completion between

## Objectives or Key Results this is meant to further
- Human-centeredness: Our hypothesis is that the combined profile/account page will be a more efficient way for veterans to manage profile related tasks, including upgrades to 2FA, updates of their home address, mailing address, phone/SMS, and direct deposit information.  

## Acceptance Criteria
- [x] Perform discovery and first draft of implementation of timing between load of page and Form Submission on above events

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

---
## Notes from Auth Exp call with Samara and Justin

Hi Joanne, Jon, and Nedie — 

Thanks for meeting with us yesterday to talk about our potential analytics approach for measuring success with the combine profile and account project. I'm creating this to-do so we can keep track of this conversation and regroup as needed.

These are my big takeaways from yesterdays call:

- We can potentially measure increased visits to the new profile/account as a metric for success, though our goal is to get the *right* people to this section more so than seeing an increase in the amount of unique visits. However, I think we can pretty safely say we don't want to see a reduced number of people to this new combined profile/account section from the amount of traffic we currently see to the separate profile and account pages.
- We would love to be able to measure reduced time to task completion for things like changing your address or updating your direct deposit information, but we don't have a way to measure time to task completion right now.
- We could potentially use an increase in people verifying their identity or adding 2FA as a metric for success since these things should be easier to find in this new section. However, it's worth noting we do prompt people to take these actions elsewhere, so we would have to measure this through increased link clicks from this section.
- We may be able to use exit rate to measure success, but it was not clear to me how we would do this.
- Reduction in profile-related calls to the call center could be a metric for success.

**To-dos**

- I think the only to-do from this meeting was that Nedie and Jon were going to take some time to think through this problem, and we'll regroup when there's more to discuss.

**Comment by nedierecel** [comment]
Reshifting to backlog since it is dependent on the Discovery portion.

**Comment by nedierecel** [comment]
@jonwehausen For our implementation discussion, here are some starting points:

1. Start of Timer - In current state, should we begin incrementing the timer on start of page load for `/profile` and `/account`? (In future state, it would be the combined `/profile`)
2. End of Timer - We track a few key events now, which could potentially be used in your formula:

a) Profile Form Submit - For each section (e.g. home address, mailing addess, phone/SMS, direct deposit), there is a profile form submit that we count as an `Event Category: Transaction`. 

b) API Calls - There is a second event that tracks Profile Saves or Profile Save Failures. This is `Event Category: API Calls`, `Event Action: Profile Saved` (or `Profile Save Failures`).

**Comment by jonwehausen** [comment]
Hi @nedierecel, 

I have put a POC in-place within the staging VA.gov environment. This POC clones the existing profile form submit and save tags we had in place to only send traffic to the staging property. 

From a functionality standpoint here's what I've got: 

- Setup 2 custom metrics: 1 for the event count, 1 for the event timestamp
   - _Did this for each of the two tags, 4 custom metrics total_
- Setup a calculated metric to get to an average time spent to complete an event
   - _Did this as well for each of the tags, 2 calculated metrics total_

Lets give ourselves some time to see if this accomplishes the user timing piece and we can talk about how to improve.

**Comment by nedierecel** [comment]
@jonwehausen Thanks for sharing the proof of concept today. To summarize, we have configured to track the following:

- Timestamp of initial Profile or Account Page Load
- Timestamps of the first profile form submit and profile saved events
- Timestamps and count of subsequent profile form submits and profile saved events

On Staging, we will do a custom report to calculate what the delta is between time of first profile form submit and page load to get time-to-task-completion. We will then connect with the Auth Experience team to get their feedback on approach.

For globalization (particularly on form funnels), we have to understand what form events to add to Google Tag Manager to increment time to completion.

**Comment by joanneesteban** [comment]
Thanks, @nedierecel and @jonwehausen !

So for globalization, does this mean we can (more easily) expand the technical solutions to other forms?

**Comment by nedierecel** [comment]
@joanneesteban There is potential to do so, but I'd like to try it with one form. We'll need to define the "start of the form" which could either mean Step 1 of a form or a form load (for ones where veterans were coming in mid-way)

**Comment by joanneesteban** [comment]
Technical proof of concept completed. Need reporting. Thanks!
