### ISSUE TITLE
Request Design QA for Epic #756 Texting for Medical Appointments

### ISSUE THREAD

**Issue by lichellebain** [department-of-veterans-affairs/va.gov-team#2331]
Functionality adds a new text box field under Mobile Phone Number on profiles page,  This field will allow users to receive text notifications for their medical appointments.
URL:  https://staging.va.gov/
Mock up:  https://vsateams.invisionapp.com/share/FSTDOO0WUHC#/screens/378179664

Note:  The green box containing the save message that appears after editing the check box on the profile page does not have a check box as the mock up shows.  This is due to the fact that the check mark is not in the style guide for alert messages.

There is one existing defect:  The cancel button does not appear to clear the unsaved checked box in the pop-up.

Steps:
1-	On the profile screen, start with an existing mobile number, but the text box unchecked.
2-	Click on Edit to open pop-up.
3-	Click on the text box 
4-	Click on Cancel—which takes you back to the profile page.
5-	Click on Edit to open pop-up.
6-	The text box is still checked.

I would expect that the check box would not be checked since the user pressed cancel and it was never saved.

**Comment by CrystabelReiter** [comment]
@lichellebain Could you please paste a direct link or recommend a login to use so we can see the profile on staging? If not, a screenshot of every state of the experience can suffice. Thank you!

**Comment by lkoenigsberg** [comment]
@lichellebain @CrystabelReiter @andreahewitt-odd what is the status of this please?

**Comment by lichellebain** [comment]
@CrystabelReiter  Sorry, I was out of office last week. The URL is https://staging.va.gov.
The user is vets.gov.user+220@gmail.com  and the password is Zm9ydHkgdHdv.  Lets get a meeting scheduled this week.  My email is lichelle.bain@va.gov.  Elwood Gary is the developer and would need to be present.  His email is kenneth.gary@va.gov.

**Comment by emilywaggoner** [comment]
Hello everyone! Thank you for going through our design review earlier today. Here are the items from our list, along with some comments and recommendations. Please let me know if there are additional questions and ideas!

- [ ] ~New design patterns have been vetted by DSVA and documented~ N/A
- [X] Mobile, tablet, and desktop breakpoints have been accounted for
- [X] Correct use of design patterns in context
- [ ] ~Form chapters in place~ N/A
- [ ] ~Privacy policy is present~ N/A
- [ ] ~Address form follows pattern if applicable~ N/A
- [ ] ~Name form follows pattern if applicable~ N/A
- [X] Correct use of typography
- [X] Padding and spacing has been applied appropriately
- [X] Form components used correctly in context
- [X] Consistent use of iconography
- [X] Colors use are consistent with color palette
- [X] Primary and secondary CTA buttons used correctly in context
- [X] :hover and :focus states have been accounted for and are consistent with design patterns
- [ ] Alert messages have been used appropriately
    - One concern that we have about the success alert is that it goes away too quickly. There isn't currently any guidance in the design system about how long it should be on screen. This is something that we recommend assessing in usability testing which could help us create that guidance.
    - @1Copenut has recommended that the `aria-live="polite"` attribute be added to the success message component to ensure that it is read by screenreaders since it appears on screen dynamically after the page has loaded.
- [X] Error states have been accounted for and used appropriately
    - I think this one is all set pending any copy changes recommended by @peggygannon (the error message copy is shared [here in Slack] (https://dsva.slack.com/archives/CLF4P9UCV/p1571844441025500)) 
- [ ] Loading indicators have been used where appropriate
    - We have the same concern here about the timing of the loading message that appears after the user has selected the checkbox. It feels like it goes away before having a chance to read the whole thing, but we also understand that this was something that was already in place on the profile page. We would also like to recommend that the comprehension of this message be tested with users.

All in all, things are looking great! I'll summarize the recommendations here:
- Add `aria-live="polite"` attribute to the success message component 
- Conduct usability testing of this feature, specifically testing the timing of the success message alert, the loading message, and the comprehension of both. @dorothyjb @lkoenigsberg We are happy to help the team set up usability testing sessions for this!

Thank you all!

**Comment by elwoodva** [comment]
The success message component is built via the foundational <Alertbox /> object.  Are we, as "normal" developers supposed to touch that code and make a change such as adding the aria-live="polite" attribute?  Especially as it would effect so many more components than our notifications mvp.

**Comment by lichellebain** [comment]
@emilywaggoner  Can you give us more information on how you conduct usability tests?  Maybe we could schedule something for Monday?  We should include Arienne Walters as she has just joined the team as a human centered design expert.

**Comment by emilywaggoner** [comment]
@lichellebain Here is a [document that describes the research process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-process.md). We would need to get a research plan put together first, and then about a week to recruit participants for the study. It would be excellent to have @AirWalters involved in that process - I would be happy to help get it all set up.

@elwoodva I will defer to @1Copenut's recommendation of whether your team should integrate that attribute, or whether we should add it globally from the platform side. Thank you!

**Comment by lkoenigsberg** [comment]
Please note that we have already conducted user research for this MVP.  @claricechan can provide details.  If anything, we may consider doing some UAT which does require documenting a research plan, recruiting, creating a conversation guide, conducting research, modifying anything as a result of feedback, summarizing research.

There are other factors to consider when doing UAT. Biggest of which is how/where we'll conduct it.  This is a minor enough change that I offer we do this post launch, in the live environment, and with input/guidance from @Samara-Strauss 

Am also very happy to be challenged on this recommendation!

**Comment by lkoenigsberg** [comment]
Pulled the request to update the success msg component into the Authenticated Experience backlog (https://github.com/department-of-veterans-affairs/va.gov-team/issues/2761) for future consideration.

I've also created the UAT issue at https://github.com/department-of-veterans-affairs/va.gov-team/issues/2762.  We will follow-up post launch on conducting UAT.

Planning on closing this issue unless there are other comments/concerns/question?

**Comment by Samara-Strauss** [comment]
> There are other factors to consider when doing UAT. Biggest of which is how/where we'll conduct it. This is a minor enough change that I offer we do this post launch, in the live environment, and with input/guidance from @Samara-Strauss

Re: UAT — Probably the biggest value we'd get out of UAT is to test that people who've already opted into these alerts are seeing that reflected in their VA.gov account. Otherwise, testing that the box can check and uncheck (and stays saved that way after a refresh) is probably less risky and we should assume that works if it works on staging. But a little extra testing can't hurt.

Are end to end test happening, or was part of the goal of UAT to then verify that the setting had been changed on the backend?

Also, who on your team will be running and coordinating this effort?

**Comment by lichellebain** [comment]
Actually, looks like the team met today and got half of the end to end testing completed, we will meet again tomorrow to finish up.  @lkoenigsberg @emilywaggoner 

Can this ticket be closed?  We have a UAT ticket opened for the usability/UAT testing.
