### ISSUE TITLE
[Design, PM] Preferred Medical Facility - Compile test case & test user documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23317]
## Background
We need to prepare documentation for staging test cases and corresponding test users. Goal to have first iteration this sprint.

## Examples
- [My VA test cases and users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)
- [Direct Deposit for Edu use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/product/dd-e-use-cases.md) original spreadsheet linked in #16528

## Tasks
- [ ] Compile staging test cases
- [ ] Identify corresponding test users
- [ ] Review with Samara

**Comment by andaleliz** [comment]
@ajakabcin I updated the URL for our doc to eliminate spaces in the url; we try to avoid spaces in file names in our repo to keep URLs clean (otherwise spaces get replaced with `%20`).

Here's the new URL:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/QA/facilities-test-cases-users.md

I've taken this as far as I can for now. I'll add additional cases if I can think of any. Thanks in advance for tracking down users!

**Comment by andaleliz** [comment]
@ajakabcin Just checking in - anything else you need from me before we can close this out?

**Comment by ajakabcin** [comment]
@andaleliz apologies for the delay! Nope I think we're good here - I'll add the users and we can refine as needed once we get into development. Thank you!

**Comment by ajakabcin** [comment]
moved this documentation to the secure repo, found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-preferred-medical-facility.md#preferred-medical-facility-testuse-cases--users-your-va-health-facilities)
