### ISSUE TITLE
[FSR] Investigate a new way to use tool action links to be more findable

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23311]
## Issue Description
When the action link component was tested on the caregivers tool, they had some trouble with findability and recognition. Investigate a new way of presenting a tool and its link to be more identifiable.

---
## Tasks
- [x] Ideate new concepts for transitions from
- [x] Run the ideas through #design
- [x] Include new concepts in usability test

## Acceptance Criteria
- [x] Concept created
- [x] Concept vetted
- [x] Concept included in test

**Comment by rebeccawalsh** [comment]
Concepts have been made for this, and run through the vsa design channel. [It's now being reviewed by the #design channel here](https://dsva.slack.com/archives/C0NGDDXME/p1624481281168500). We currently have the white badged version in our test prototype for usability, so this ticket is just pending #design feedback.

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/a6f58050-d4f7-43a6-91fd-6a68f68606f7)

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/924d0141-1df6-4dcf-9d81-d935a07b3e90)

**Comment by rebeccawalsh** [comment]
For our testing, we've decided to go with the blue underline, based on conversations with Shawna and a few other VSA designers. These changes have been reflected in the [prototype here](https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages/140027243/simulate/no-panels?mode=i).
