### ISSUE TITLE
[FE] Direct Deposit for Edu - Record more specific error logging

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23312]
## Background
Right now our GA is tracking when errors are logged, however it's very general which doesn't allow us to know what exactly is causing errors for our users. We need to dig into this more.

## Tasks
- [ ] Investigate existing logged errors
- [ ] Determine how to make them more specific
- [ ] Implement more specific error logging

**Comment by erikphansen** [comment]
I should have asked in sprint planning, but are we seeing enough errors with DD4EDU save errors that we need to do this this sprint?

**Comment by Samara-Strauss** [comment]
Nope, we can deprioritize this. Errors are very low right now. Thanks for asking!

**Comment by erikphansen** [comment]
@ajakabcin I removed this from "current sprint" since I don't think it was every supposed to be in this sprint.

**Comment by Samara-Strauss** [comment]
We probably put this in this sprint a few weeks ago thinking we'd have time for it by now (but we don't, and that's OK!). Totally fine to punt this.

**Comment by ajakabcin** [comment]
that's my mistake! definitely forgot to bump it back out of current sprint. thanks for catching!

**Comment by ajakabcin** [comment]
I think this should actually be in @SKasimow's backlog now. Assigning over to Profile.

**Comment by mdewey** [comment]
@Samara-Strauss 

This has merged in master and will get deployed today. When we get errors in the coming days, let me know and I can check the logs

**Comment by Samara-Strauss** [comment]
Great, thank you! I'll make a note to take a look at this within the next few days to see what information we are getting in.

**Comment by SKasimow** [comment]
@mdewey - can we close this ticket?

**Comment by mdewey** [comment]
Not yet @SKasimow, we did some updates to the logging, but still do not have a clear picture. I need to push another update so we can see what is going on.

**Comment by mdewey** [comment]
Created a new PR to add lopgging, when that gets deployed we can wait a a few days and  see what the errors are saying

**Comment by Samara-Strauss** [comment]
Great, thank you!

**Comment by mdewey** [comment]
Update: New logging is in place, but its showing an empty response from the API (http://sentry.vfs.va.gov/organizations/vsp/issues/116414/?environment=production&project=4&query=is%3Aunresolved+url%3Ahttps%3A%2F%2Fwww.va.gov%2Fprofile%2Fdirect-deposit&statsPeriod=14d) Which is extremely odd. 

I am tweaking the logging even more to get a better look

**Comment by mdewey** [comment]
After I tweeked, Here is what I found, errors are happening in two forms

The first is a `BANK NUMBER NOT VALID`, which seems reasonable and when tested, the site failed as expected. [Sample error](http://sentry.vfs.va.gov/organizations/vsp/issues/119910/events/912ae54169964bdba761a14107d0a6f7/?project=4&project=3&statsPeriod=14d)

The second error is a bit stranger. The API is infact returning an empty error response object. [Sample call](http://sentry.vfs.va.gov/organizations/vsp/issues/119910/events/4e1409551161475199a8df1a7a87b426/?project=4&project=3&statsPeriod=14d). I am not sure why though.  Even though the error is empty, it looks like the site still displays an appropriate error message and doesn't crash. 

Proposed next steps:
- Decide if the messaging around the first error can be more useful. It currently displays the generic `server is down` message. 
- Have the BE team investigate what could be returning an empty error from their end
- Add more logging for the parameters of the `PUT` calls (with respect to PII)  if the error response is empty

**Comment by SKasimow** [comment]
@Samara-Strauss - looks like this needs to go back to the backlog and re-assigned. Is this something I should tee up sooner vs later?

**Comment by Samara-Strauss** [comment]
@SKasimow this isn't especially important right now, as error instances are low.

**Comment by tpharrison** [comment]
@mtcA6 C&P and EDU are separate endpoints.

**Comment by ajakabcin** [comment]
@mtcA6 this ticket has been around for a while and was deprioritized because errors had tapered off, but I think what @tpharrison is saying is that the EVSS > Lighthouse migration they're working on right now is specifically for Direct Deposit for comp and pen, and this ticket is about Direct Deposit for Edu (or DD4EDU for short), ie different features and endpoints.

Sorry to butt in - I still get notifications on these older tickets 🤪

**Comment by mtcA6** [comment]
Since we're going to one form in our [EPIC | Profile | EDU CH33 DD Changes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76202#top)
 work, I am going to close this ticket out and reference/incorporate it into our analytics ticket ( [FE/PM | EDU CH33 Changes | Analytics (I think it's important we track based on EDU, C&P, Both) #76723](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76723) ) we have for the migration effort.
