### ISSUE TITLE
[Design] Preferred Medical Facility - Begin research plan

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23320]
## Background
We need to create our research plan for preferred medical facilities. We'll do this in collaboration with VAOS. 

## Tasks
- [x] Identify questions we want answered through our research
- [x] Coordinate with VAOS
- [x] Document detailed plan/questions

**Comment by andaleliz** [comment]
Created [initial doc w/ questions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/discovery-and-research/research-plan.md) in our folder. Still unsure if we or VAOS will lead this effort, or if it'll truly be 50/50

**Comment by andaleliz** [comment]
Hi @ajakabcin and @Samara-Strauss! I started a [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/discovery-and-research/research-plan.md).  

Based on comments VSA team members have made while reviewing this in early stages, I'm a little concerned that people will be confused by the initial checked state and then having to uncheck to mark as "not current".  As I wrote out the research plan, I realized that we can get this see if this is indeed a problem without having to wait for VAOS through an internal mini-study (similar to what Tressa did for profile mobile nav) - and then iterate on it prior to testing w/ VAOS and Veterans if necessary.  I think the study w/ VAOS will have **a lot** of research questions; my hope is that by doing this mini-study first, we can get some core design questions out of the way and be better focused in the longer sessions.

The research plan reflects this two-pronged approach, and I created a [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/discovery-and-research/conversation-guide.md) for a mini-study. 

In case you're wondering what makes this a "mini-usability" study vs a normal usability study?
- We'll talk to just 5 participants
- We'll do our own recruiting via Slack
- I'll take notes (observers welcome, as always)
- Findings report will be turned around in a day - more aligned with a topline summary than our full-fledged report style

If you're on board with this, I think I could kick off recruiting on Friday via Slack and then talk to folks about this in the first days of our next sprint.  Thoughts?

**Comment by ajakabcin** [comment]
This looks really great @andaleliz and the plan you outlined makes sense to me.

**Comment by Samara-Strauss** [comment]
The research plan looks great to me. A few thoughts:

- I think the mini study is a good idea and I'm on board with that. One thing to keep in mind — the mental model of anyone on the larger VA.gov team may be different than a veteran's mental model (unless they also happen to be a veteran!), so certainly take into account any major usability confusion, but also make sure results are considered from this perspective.
- For the full research study with VAOS, it probably makes the most sense for you and Peter to collaborate on a single research plan that will get sent over to Lauren (and you might have already been planning that). We don't need to mention the mini-study in that document, just our research questions and needs as they pertain to the profile.

**Comment by andaleliz** [comment]
Wonderful, glad you are both on board with this.

>the mental model of anyone on the larger VA.gov team may be different than a veteran's mental model (unless they also happen to be a veteran!), so certainly take into account any major usability confusion, but also make sure results are considered from this perspective.

I'm hoping to find people who are also Veterans, but will definitely take that into account either way.

>For the full research study with VAOS, it probably makes the most sense for you and Peter to collaborate on a single research plan that will get sent over to Lauren (and you might have already been planning that). 

Yep, that's the plan! We'll leave the mini-usability study out of the docs we submit to Lauren and Perigean.

I created #23868 for the mini-usability study tasks next sprint, and will close this out.  The larger study docs will be informed by what we've done here.
