### ISSUE TITLE
Update For Designers page in Documentation section of design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#23327]
## Issue Description
Update For Designers page in Documentation section of design.va.gov

---
## Tasks
 - [x] Review all content in this section 
 - [x] Draft content as needed
 - [x] Have content changes reviewed by team member 
 - [x] Update content categorization and structure as needed
 - [x] Post updates on design.va.gov 

## Acceptance Criteria
- [x] For Designers page of the documentation section on design.va.gov is updated
---
Notes from discussion:

- Update for sketch for teams 
- Can we make a sketch for teams public link?
- Let’s leave the download link for now 
- Move “Sketch for teams” to designers section?

**Comment by CrystabelReiter** [comment]
- Make sketch for teams last on this page
- Rethink having the working with developers section- delete first paragraph

**Comment by CrystabelReiter** [comment]
Working draft: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_documentation/for-desingers-doc-sprint.md
