### ISSUE TITLE
Update the Contributing to Formation page in the documentation section of design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#23324]
## Issue Description
Update the Contributing to Formation page in the documentation section of design.va.gov

---
## Tasks
- [x] Review all content in this section 
 - [x] Draft content as needed
 - [x] Have content changes reviewed by team member 
 - [x] Update content categorization and structure as needed
 - [x] Post updates on design.va.gov 

## Acceptance Criteria
- [x] Contributing  page of the documentation section on design.va.gov is updated 
---

Notes from discussion:

- We want to add some experimental stuff in here. 
- Ryan’s recommendation - basically rip off gov.uk from a structural standpoint on how they organize their community section - steal their subnav
- Need to put in the new flowchart
- Backlog needs to be a subpage

Updating this site 
- What about adding people to the repo?
- Give us your documentation and we will put it in the design system?
- V1. experimental system is up and running. It’ll be up to the design system team to add the first 5 components to the official system, after that we’ll give you templates on how to add to the design system
- Move this under contribution- look at whatever the subnav of is contributing to the design system.

**Comment by CrystabelReiter** [comment]
How to contribute:

- No flowchart 

- 1.2.3 format (look at gov.uk and our working doc with Allison) 

- Rename section "Contributing to the design system"

**Comment by CrystabelReiter** [comment]
Working draft: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_documentation/contributing-to-the-design-system.md
