### ISSUE TITLE
Update Feedback page in Documentation section of design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#23326]
## Issue Description
Update Feedback page in Documentation section of design.va.gov

---
## Tasks
- [ ] Review all content in this section 
 - [ ] Draft content as needed
 - [ ] Have content changes reviewed by team member 
 - [ ] Post updates on design.va.gov 

## Acceptance Criteria
- [ ] Feedback page of the documentation section on design.va.gov is updated 
---

Note from discussion: 
Do we want to keep an open GH? Or do we want to funnel all requests to design system

**Comment by KevinMHoffmanUSDS** [comment]
@rtwell or anyone who has the bandwidth, please review:

https://docs.google.com/document/d/1_shTP-gInup3eiotCLX-vtWubIPaP_Jrnm9hEEFk3PM/edit?usp=sharing

**Comment by rtwell** [comment]
My only comment/question is for the final paragraph, do we want to include checking the backlog before leaving feedback?
