### ISSUE TITLE
Phase 1 Research

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#23338]
## Issue Description
_The Contact Center Team is assisting VEO in usability research and user interviews for their new Ask VA (AVA) tool. In addition to performing the research, a slide deck containing findings and recommendations will be built and delivered by the CC team._

---
## Tasks
- [x] _Conduct the usability tests_
- [x] _Synthesis the information as a team (if necessary)_
- [x] _Build a Research Read Out slide deck_
- [ ] _Deliver Read Out to appropriate VEO members_

## Acceptance Criteria
- [x] _Usability tests have been conducted_
- [x] _Research Read Out has been built_
- [ ] _Research Read Out has been delivered_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Wrapping up synthesis & slide deck today (4/28). Can close ticket by end of week.

**Comment by Kimberley2019** [comment]
Ian email to VEO 5/3/2021.
