### ISSUE TITLE
Document CC Support Data Granularity

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#23340]
## Issue Description
_The Analytics team is looking to provide enhanced reporting for VFS teams, specifically focused around pages/sites with certain types of functionality listed below. We need to understand what data is available to help with planning._

---
## Tasks
- [x] _Research and document granularity levels for IRIS and VEO support issues for supporting analytics_ _dashboards and more granular custom reporting on our side. Specifically, note availability of the following for _analytics team:_
- Forms
- Content Only Sites (typically a lot of links)
- Search (within page - ex. Find VA Locations)_

## Acceptance Criteria
- [x] _Available data fields are attached to or documented within this story_
- [x] _A summary of what may or may not be feasible is added in comments._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
[SF-CRM-Tracking-Fields.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6388307/SF-CRM-Tracking-Fields.xlsx)

Here is a list of fields from our Salesforce instance, which are tracked for support issues generated through VEO/White House Call Center.

While there isn't a specific category for pages with "Forms", "Search", or "Content-Only Sites", we could potentially create mapping for these areas of focus by using the `sub-category` column and known pages/products with these unique functions and segment data by that (`sub-category`).

**Comment by jwoodman5** [comment]
I reached out to the analytics UX designer to discuss.
