### ISSUE TITLE
Review Instances (RIs) - Feature request: Show unpublished content 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23353]
## Description
There is an interest from some developers in the ability to view unpublished content on RIs. 

## Background/context/resources
Slack thread `https://dsva.slack.com/archives/C01512KN35G/p1618257597333100`

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Ops to discuss and prioritize this feature 

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
This is not something that we are looking at right away, but will discuss and prioritize along with leadership in the near future.

**Comment by jhouse-solvd** [comment]
We are not actively adding features to RIs. But will keep this in the backlog as we look at improving app preview functionality.

**Comment by ph-One** [comment]
Please see the Platform Feature Request process, https://depo-platform-documentation.scrollhelp.site/support/submitting-a-feature-request
