### ISSUE TITLE
DataDog (DD) - Investigate need to migrate data/dashboards/settings etc to GovCloud version of DD

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23352]
## Description
Based on an email received by Matt and Sri, there was mention of moving DD to AWS GovCloud, and that this might be another option/requriement/consideration for VSP's use of DD. If that were the case, we would need to migrate data and settings from DD from our current SaaS-hosted solution to the DD instance in GovCloud. We need to investigate and discuss the implications and whether or not this is a requirement for us. The potential impact is the investment of time in customizing DD moving forward. 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Bring this up w/ Demian and discuss
- [ ] Potentially discuss w/ Dror as needed to confirm our stance 

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
DOTS stated that they will assist us in migrating any settings over to the new system. However, existing data will not be retained. Please search for datadog migration tickets for more information. 

Closing.
