### ISSUE TITLE
Update form submission data values

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#23368]
## Issue Description
need to update values in form submission data to use a single object is currently passed as an array

---
## Tasks
need to update the following values:
- [ ] otherIncome
- [ ] otherLivingExpenses 

## Acceptance Criteria
- [ ] submission payload should match API specs found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/benefits-memorials-2/financial-status-report/api.md)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
