### ISSUE TITLE
Staging Review | Anchor Tag Pilot on CoronaFAQ Page | C+L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#23367]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [ ] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to VSP feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [ ] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
-  Link to product outline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags.md

- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
http://86864aa567574a418320047724601e46.review.vetsgov-internal/coronavirus-veteran-frequently-asked-questions/
-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or elsewhere) 
Mock: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20125
CC Brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/Anchor_Tags_Product_Guide_5-7.docx
- Link to release plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags-launch-plan.md
- Link to your product test [case](https://dsvavsp.testrail.io/index.php?/cases/view/4795&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=827)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/1805) in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/220) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/219) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20185
- Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/accessibility-checklist-anchor-tags.md
- Analytics review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19547#issuecomment-827809939
- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): @SKasimow 
- DEPO Product lead (recommended): @jenniferlee-dsva 
- DEPO Design lead (required): Ryan Thurwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): name(s)
- Content, IA, accessibility, and QA specialists (if applicable): @joshkimux @1Copenut @mnorthuis @youngfreezyVA and @bsmartin-ep @tlei123 @AngelaFowler82 

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **date/time**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://docs.google.com/document/d/1_1gGJW6Go0Kk-H5jttDbQIZrcbKTst9gSZnXKVdeQSg/edit?usp=sharing) on Github for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
@shiragoodman Hi Shira - I believe our pilot feature fits criteria for a "non-staged" roll-out but lmk if that isn't the case.

As a reminder the copy link will only be going live on 1 page - CoronaFAQ English.


> Do I need a staged rollout?
> 
> Yes, a staged rollout is required unless you can confidently answer "yes" to all of the following:
> 
> This change does not add substantial new functionality to VA.gov
> This change does not impact user flows through tasks
> This change does not affect traffic to backend services
> 

cc @jenniferlee-dsva @youngfreezyVA

**Comment by shiragoodman** [comment]
@SKasimow would you mind linking the document where you referenced that guidance? Sorry, I don't recognize it offhand.

**Comment by SKasimow** [comment]
@shiragoodman Looks like the Collaboration cycle docs have been/are being updated and I no longer have access. The above excerpt I posted was pulled from the Staging doc overview. If you can grant me access I'll see if it is still listed in collaboration cycle process docs and link you to it.

**Comment by SKasimow** [comment]
@shiragoodman. here you go.... https://docs.google.com/document/d/1QH77u8Roi_TtD7rhg1_Vel2wJwsTO4Au9pPkXNPxMmk/edit?ts=60805393

**Comment by mnorthuis** [comment]
No IA feedback for this.  Thank you!

**Comment by allison0034** [comment]
@SKasimow I am getting an error when I try to access the link...

This site can’t be reached
Check if there is a typo in 86864aa567574a418320047724601e46.review.vetsgov-internal.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by SKasimow** [comment]
@allison0034 Hi - were you using socks for this link?

@youngfreezyVA

**Comment by peggygannon** [comment]
Hello, there is no content feedback for this. thanks!

**Comment by joshkimux** [comment]
@SKasimow @youngfreezyVA I have socks running but the link isn't working for me too 🙇

**Comment by 1Copenut** [comment]
Try this Staging URL. The copy buttons are inside the accordions: https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/

**Comment by pjhill** [comment]
@SKasimow Are there any acceptance test cases, manual functional test cases, a test plan, or other QA related artifacts available for review?

**Comment by shiragoodman** [comment]
todays Staging Review has been cancelled and will be rescheduled soon.

**Comment by SKasimow** [comment]
@pjhill working on this

**Comment by SKasimow** [comment]
Hi @shiragoodman  - can we request re-sched staging review for 5/14 2pm et? Spoke with @tlei123 and we should have QA complete by that date :)

**Comment by shiragoodman** [comment]
rescheduled for 5/14 at 2:00pm ET

**Comment by tlei123** [comment]
@pjhill @ddzz , all QA test-runs now completed, and QA-artifact links updated above in main description.

cc @SKasimow @shiragoodman

**Comment by SKasimow** [comment]
@tlei123 You Rock Tze! Thanks for getting this done sooner than expected 🥇 

cc @jenniferlee-dsva

**Comment by ddzz** [comment]
@SKasimow @tlei123 @shiragoodman: @pjhill and I are no longer seeing the anchor links on staging. The feature was working for Peter earlier today, but only one anchor link is showing up on the entire page now.

**Comment by SKasimow** [comment]
I sometimes find I have to refresh a few times before they show up...did u try that?

cc @youngfreezyVA

**Comment by youngfreezyVA** [comment]
if you’re looking at the FAQ page, the layout was changed, so only seeing one anchor link is correct since the other anchor links are now within the accordions
