### ISSUE TITLE
[FE] Profile: Update FAQ links and copy around what departments get updated when a veteran updates their contact info

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23376]
## Background
As noted in #20221, there's been some confusion over how we show information in the profile around what departments get updated when someone updates their contact info and how the information is used. We've determined that we should elevate the FAQ links higher on the page and in include more information about which benefits and services VA uses the contact information for. We also will change the location of the link for how to change contact information to nest within the second FAQ.

## Tasks
- [ ] Move the "How do I update my personal information?" additional info component to be above the Personal information module and immediately below the page header. Note - leave the copy as is within this link when expanded.
- [ ] Add an additional info  component reading "Which benefits and services does VA use this contact information for?" and move it to be located between Personal information module and contact information
- [ ] The text that appears when the user expands the "Which benefits and services does VA use this contact information for?" link as follows:

We use this information to contact you about these VA benefits and services: 

- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)

If you’re enrolled in VA health care, we also use this information to send you these:

- Appointment reminders
- Communications from your VA medical center
- Lab and test results
- Prescription medicines (we send your medicines to your mailing address)

[Find out how to change your contact information for other VA benefits](https://www.va.gov/resources/change-your-address-on-file-with-va/#change-your-address-by-contact) 

(Source of truth for copy also linked [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20221#issuecomment-821194707))

## Screenshots
Screenshots originally attached [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20221#issuecomment-821218102)

Desktop collapsed FAQ links
![23376 new FAQ links collapsed desktop](https://user-images.githubusercontent.com/45603961/115090309-7ce34a00-9ee2-11eb-8059-bbe6cfb8e6e3.png)

Desktop expanded FAQ link
![23376 new FAQ link expanded desktop](https://user-images.githubusercontent.com/45603961/115090298-794fc300-9ee2-11eb-86af-261b41ecf126.png)

Mobile collapsed FAQ links
![23376 new FAQ links collapsed mobile](https://user-images.githubusercontent.com/45603961/115090277-6ccb6a80-9ee2-11eb-8ba5-2f99aba54c0f.jpeg)

**Comment by erikphansen** [comment]
@ajakabcin this can be validated

**Comment by ajakabcin** [comment]
Confirmed on staging - thanks!
