### ISSUE TITLE
Midpoint Review [Virtual Agent]

### ISSUE THREAD

**Issue by katieho-va** [department-of-veterans-affairs/va.gov-team#23372]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure VSP reviewers have appropriate access to secured applications.
- [x] VSP: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to VSP feedback tickets.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/virtual-agent/product/product_outline.md)
- Link to or attach prototype or mockups: https://invis.io/GD10KM9RSPV7 
- Link to content brief (if applicable): N/A
- Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or elsewhere): https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/virtual-agent - the content source of truth will live within a number of parts of Microsoft infrastructure (PVA and QnA maker) but Github will have the majority of content for [QnA](https://github.com/department-of-veterans-affairs/va-virtual-agent/tree/master/automated-content/qna-content). Please reach out to the team if you have issues navigating the content.
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/virtual-agent/research/moderated-interviews) 
- Link to regression test plan: N/A - no plan required as per VSP collaboration cycle meeting on April 14th
- Link to test cases/test plan in TestRail: N/A - no plan required as per VSP collaboration cycle meeting on April 14th

## Meeting attendees from requesting team
- Product Manager (required): Shahrukh Shamshair (Sham)
- DEPO Product lead (recommended): Luciana Morais
- DEPO Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Rachel Murray (Design), Shane Strassberg (Content), Katie Ho (Project Manager)
- Content, IA, accessibility, and QA specialists (if applicable): VSP team to advise?

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [X] No
 
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
Thu, April 22, 1:30pm – 2:00pm
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
thanks @katieho-va - meeting scheduled for Thursday 4/22 at 1:30 pm ET.

I see in the artifacts section, you commented "no plan required as per VSP collaboration cycle meeting on April 14th" for both the regression test plan and test cases/test plan in TestRail. We won't require you to use TestRail, however it would be very helpful if you could include any QA artifacts your team has created. Thanks!

**Comment by katieho-va** [comment]
Thanks @shiragoodman! Our tech lead and QA are working on a testing strategy so we might have some of that work ready to share on Thursday

**Comment by shiragoodman** [comment]
that's great! thank you for sharing. I wasn't sure what the current status was.

**Comment by pjhill** [comment]
Since no QA artifacts are available at this time, we have no quality assurance feedback at this time. If you want to discuss the testing strategy in the future then please reach out.
