### ISSUE TITLE
[FSR] Add multiple current jobs

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23371]
### User Story
As a Veteran I might have a full time and part time job that are both current,
update FSR so Veteran can add more than one current job,
this way form can accurately report the most current information

#### Solution
After [the ‘tell us about your current job’ page](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136159504/comment/sitemap?mode=i), we add a page to [ask the veteran if they currently have another job](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138281545/comment/sitemap?mode=i). If yes, we just show them another ‘tell us about your current job’ page and loop until they say no to the question asking if they currently have another job.

### Tasks
- [ ] _Update the FSR's UI to reflect the outlined solution above_
- [ ] _Reach out to Becca or Riley to review the UI updates_ 

### Acceptance Criteria
- [ ] Employment history list loop can accept more than one current job

**Comment by craigwheeler** [comment]
need to revisit based on design changes
