### ISSUE TITLE
Language assistance and resources: Rights, problem resolution, and discrimination complaint content (issue 2 of 3 for this work)

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23382]
## User story

As a Veteran, caregiver, or family member, I need to know what my rights are at VA, how to get help to resolve problems, and how to file a discrimination complaint.

## Issue description

We need to create the following:
- Resources and Support articles (in English) about rights and how to resolve problems and file a discrimination complaint

## Tasks to completion 

_Note: This ticket takes this work from post-SME review to launch._

- [ ] Create Resources and Support articles and incorporate SME feedback (Randi, Selina)
- [ ] Final review/edit of articles (Danielle)
- [ ] Publish articles (Randi, Selina)
