### ISSUE TITLE
Language assistance and resources: Rights, problem resolution, and discrimination complaint content (issue 1 of 3 for this work)

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23381]
## User story

As a Veteran, caregiver, or family member, I need to know what my rights are at VA, how to get help to resolve problems, and how to file a discrimination complaint.

As someone with limited English proficiency, I need this information in my first language.

## Issue description

We need to create the following:
- A section of the new Language assistance and resources pages in Spanish and Tagalog with information about rights and how to resolve problems and file a discrimination complaint, translated into Spanish and Tagalog respectively
- Resources and Support articles (in English) about rights and how to resolve problems and file a discrimination complaint

_Note: In the future, we'll want to expand the languages we offer this information in._ 

## Tasks to completion 

_Note: This ticket takes this work through to sending to SMEs to review. Will open a separate ticket to track tasks post-SME review through launch._

- [x] Research and draft content (Danielle)
- [x] Consultation perspective (Eunice) 
- [x] Copy edit (Randi)
- [x] Share with VHA and Office of Resolution Management SMEs (Danielle)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. I'm starting to draft the content that we'll need for our Language assistance and resources pages (and Resources and Support articles), so just opening tickets specific to each part of that content. Feel free to adjust epic, etc. as you need to for tracking. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi Eunice. Here's the draft content. My goal is to share this with SMEs on Monday for feedback and accuracy check. Please let me know if you have anything we should consider as we continue to finalize this. Thanks!
[How to file a discrimination complaint_for Language Assistance and Resources pages_04.23.21](https://app.zenhub.com/files/133843125/570cc958-8c6e-4e0d-9d30-742c5f6fe963/download)

**Comment by eunicegar** [comment]
[https://app.zenhub.com/files/133843125/0b214494-5f92-4417-890a-a7173d48bad0/download]

**Comment by eunicegar** [comment]
[https://app.zenhub.com/files/133843125/fe95e248-6ac4-4334-a9cd-ceeb2be6d029/download](https://app.zenhub.com/files/133843125/fe95e248-6ac4-4334-a9cd-ceeb2be6d029/download)

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi Danioelle - the write up looks good. Only thing I'm wondering is if we should also ask them to include the name of the person that are filing on behalf of in this scenario:


•	Your name, address, and phone number. If you’re filing a complaint for another person, include how you’re related to that person.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA also, can we find out exactly how this agency supports translation services since that seemed to be a question.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Could you give this a final copy edit today before I send over to SMEs? Thank you![How to file a discrimination complaint_04.29.21](https://app.zenhub.com/files/133843125/fa2b709c-d2b2-47cc-a9a5-9191ed96bc25/download)

**Comment by RLHecht** [comment]
Here you go, @DanielleThierryUSDSVA Just a few copy tweaks.
[How to file a discrimination complaint_04.29.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6414960/How.to.file.a.discrimination.complaint_04.29.21.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Oh my. I'm sorry, @RLHecht. In my not-enough-coffee-yet state, I accidentally uploaded an earlier version of this. Can I ask you to copy edit this correct version?

[How to file a discrimination complaint_04.30.21](https://app.zenhub.com/files/133843125/53df66ea-3776-4868-84bc-70ef341374be/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA No problem! Here you go: 
[How to file a discrimination complaint_04.30.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6415257/How.to.file.a.discrimination.complaint_04.30.21.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht. Really appreciate the fast turnaround on both versions :)

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow This ticket is complete so I'm closing. Yay!
