### ISSUE TITLE
R&S 1.2: Disability tier-1-pages audit

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#23380]
### Issue
As part of the effort to migrate tier-2 disability content from tier 1 pages to resources & support, sitewide content will audit all disability pages on VA.gov. 

### Tasks

- [x] SC to audit disability pages on VA.gov, documenting those pages recommended for migration in the list below.

- [x] SC to alert DEPO when list is ready for review

- [ ] DEPO to review/edit list

### Migration List 

About VA disability ratings
https://www.va.gov/disability/about-disability-ratings/

**Beth --**. What about the rates pages, starting with:  https://www.va.gov/disability/compensation-rates/veteran-rates/?

What to expect after you get a disability rating
https://www.va.gov/disability/about-disability-ratings/after-you-get-a-rating/

Disability compensation effective dates
https://www.va.gov/disability/effective-date/

Partial:  VA claim exam (C&P exam)
https://www.va.gov/disability/va-claim-exam/
We could break this content into tier 1 -- targeting those who want to take action and schedule an exam, versus informational R&S content, such as who needs one, what to expect, etc. 

Get help filing your claim or appeal
https://www.va.gov/disability/get-help-filing-claim/

Example of tier 1 page with crucial information that gets weighed down by info relevant to a small subset of Veterans: https://www.va.gov/disability/eligibility/
Can we put h2s in a list of R&S links?:
What should I do if I received an other than honorable, bad conduct, or dishonorable discharge?
What conditions are covered by these benefits?

Example of tier 1 page with content that isn't key to the page and could be tier 2:
https://www.va.gov/health-care/get-medical-records See the h2, **The Veterans Health Information Exchange** (If keeping this content on this page, it needs a smoother transition from the topics above it.)

What about pages that apply to a subset of Veterans:
![image](https://user-images.githubusercontent.com/53535663/115872431-cc100a00-a40f-11eb-95df-f2a70ea41486.png)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I'd like to scale this ticket back to just the audit portion of this work. I don't think we need a table. Just need a list of the titles and urls. And let's keep only the first 3 tasks you have--that's enough for this ticket. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Thank you for looking through disability content and Identifying these pages!

I am also going to track in this issue some content that we can extract from pages that won't move in their entirety. Let's try to find a couple minutes on Friday to talk about next steps, starting with the low-hanging fruit. So... here's one thing I think could move over to R&S as a single Q&A:

**How do I submit an intent to file?**
You can submit your intent to file by phone or by written form.

Note: If you file your claim online, you don't need to separately send an intent to file form. The online application already includes your intent to file.

By phone
Call 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

By submitting a form
Download, fill out, and submit an Intent to File a Claim for Compensation and/or Pension, or Survivors Pension and/or DIC (VA Form 21-0966). 
Download VA Form 21-0966 (PDF)

Turn in your form in any of these ways:

Mail it to this address:
Department of Veterans Affairs
Claims Intake Center
PO Box 4444
Janesville, WI 53547-4444

Turn it in at a VA regional office near you. 
Find a VA regional office near you

Work with a trained professional called an accredited representative to get help applying for VA disability benefits. 
Get help filing a claim

**Comment by bethpottsVADEPO** [comment]
^^ ha! I didn't tell you where this is: Disability How to apply page.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - re: the "submit an intent to file" content,  here's a Word doc that shows changes to the tier 1 page and content for the new R&S page. Let me know if you have feedback and/
[rs-migrate-t1-disability-intent-to-file.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6535120/rs-migrate-t1-disability-intent-to-file.docx)
or if I can go ahead and build this in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Here are my intent to file edits and some strategy notes (in the Word doc). 

If possible, I'd like this article to cover intent to file for disability, Veterans pension, surivors pension, and DIC. It will at least cover disability and Veterans pension. We’ll have to figure out which CTA buttons make sense. In my edits, you'll see that I switched the CTA to be a link to the form, then the Related links at the bottom of the page will be the place where we link off to how to file a disability claim / how to file for a Veterans pension / survivors pension / DIC (assuming we can include the last 2--I'm checking with the pension SME). Want to go ahead and get it into drupal, then we can discuss? And at that point, we may have some more info from the SMEs about how to much to include in related links. 

[rs-t1-disability-intent-to-file-052521.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6572540/rs-t1-disability-intent-to-file-052521.docx)

**Comment by RLHecht** [comment]
Update: If we are going to be reassessing what's moving based on the new criteria I think this ticket can be closed. Just want to confirm.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Agree. Closing.
