### ISSUE TITLE
Adding links in left nav and on pages for new VRRAP page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23424]
## Issue Description
Once the new VRRAP static page and form launch, we need to add links to them from other places on the site. 

**Mikki's IA and Design and Recommendations:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-vrrap.md

**Static VRRAP page:** 
https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance

**VRRAP form:** 
https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s

---
## Tasks
- [x] Add link in education left nav
- [x] Add teaser text and link to [Other VA educations benefits page](https://www.va.gov/education/other-va-education-benefits/)

## Acceptance Criteria
- [x] Added links and text are on live pages

**Comment by RLHecht** [comment]
text and teaser link added to other VA education programs in ticket #22727

**Comment by RLHecht** [comment]
Published the left nav work and the other education benefits page. Moving to validate and will close after the deploy.

**Comment by RLHecht** [comment]
This is live. Closing ticket!
