### ISSUE TITLE
COPE candidates: content from existing tier 1 pages

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#23420]
## Issue Description
Once COPE comes online in the CMS, we have some obvious content already in existence and repeated on multiple pages that we should put into R&S and then reuse on tier 1 pages.

---
## Tasks
- [ ] Identify the candidates for this (Q&As or Notes or teasers).
- [ ] Find all pages where the repeated content appears.

COPE content already identified:
- https://www.va.gov/disability/how-to-file-claim/ (and find others)
**If I start my VA disability application, does VA consider this “intent to file”?**
No. Simply starting your VA disability application doesn’t show your intent to file. You’ll need to submit an intent to file form, which sets the effective date (the day you can start getting your benefits). Then you can focus on gathering supporting documents to turn in with your pension application. If you submit an intent to file before you file your claim, you may be able to get retroactive payments (money you’ll get starting from your effective date).
**Note:** If you file your claim online, you don't need to separately send an intent to file form. The online application already includes your intent to file.

- https://www.va.gov/disability/eligibility/
**What should I do if I received an other than honorable, bad conduct, or dishonorable discharge?**
If you’ve received one of these discharge statuses, you may not be eligible for VA disability benefits.
There are 2 ways you can try to qualify:
Find out how to apply for a discharge upgrade
Learn about the VA Character of Discharge review process

- https://www.va.gov/disability/how-to-file-claim/evidence-needed/
**Note:** In 1973, a fire at the National Personnel Records Center (NPRC) in St. Louis destroyed records held for Veterans who were discharged from the Army and Air Force during certain periods of time. Your records may have been destroyed in the fire if you were discharged from the Army between November 1, 1912, and January 1, 1960, or if you were discharged from the Air Force between September 25, 1947, and January 1, 1964. If you think your records may have been involved in this fire, you can learn more about the fire and how to get help filing a claim.
Learn more about the fire at the NPRC

- https://www.va.gov/health-care/how-to-apply/
You or someone acting as your power of attorney must sign and date the form. And:

If you’re using a power of attorney, you’ll need to submit a copy of the Power of Attorney form along with your application.
If you sign with an “X,” 2 people you know must witness your signature. They’ll also need to sign and print their names on the form.

- [ ] Drupal implementation.

## Acceptance Criteria
- [ ] Content identified exists in only one place and is reused elsewhere. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
This is a dup. Closing.
