### ISSUE TITLE
Add text and link about BTSSS videos on 2 pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23433]
## Issue Description
We need to add links to the BTSSS videos on YouTube to the Travel Program reimbursement page and to the travel pay R&S page.

**The link on the travel pay reimbursement page should go to the main video:**
https://www.youtube.com/watch?v=7lNUiyQT4gM&list=PL3AQ_JVoBEyzJnt68Eq_mPBdyZfkvq0Wu

**The link on the R&S page should be about direct deposit:**
https://www.youtube.com/watch?v=T-joySVMhso&list=PL3AQ_JVoBEyzJnt68Eq_mPBdyZfkvq0Wu&index=4

Content may be need to be updated around it to add these links in. 

**Pages to update:**

- https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
- https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/

## Tasks
- [x] Add content and link to travel pay program page
- [x] Add content and link to R&S page
- [x] Review and publish pages

## Acceptance Criteria
- [x] Links to BTSSS videos are live on the site

**Comment by RLHecht** [comment]
This work is completed. Created ticket for tracking. Closing!
