### ISSUE TITLE
Eligibility text updates to STEM scholarship page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23432]
## Issue Description
Stakeholder Tammy Hurley provided updates that need to be made to the eligibility box on the [Edith Nourse STEM scholarship page](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/).

Their suggested text is attached here:

[https://app.zenhub.com/files/133843125/ca7bc6b9-8765-45ec-b232-017ee71b41df/download](https://app.zenhub.com/files/133843125/ca7bc6b9-8765-45ec-b232-017ee71b41df/download)

---
## Tasks
- [x] Add content updates to eligibility box and review for plain language
- [x] Send to stakeholders for approval
- [x] Review and publish

## Acceptance Criteria
- [x] Content updates are live on site

**Comment by RLHecht** [comment]
@bethpottsVADEPO I added in these updates to the eligibility box. Let me know what you think about changing to bullets for the first paragraph. 

Also, I left in the note about graduate programs not being eligible at this time. It's not in their edits but i can't tell if it was purposely removed. Let me know if I should email them to ask.

preview-prod.vfs.va.gov/preview?nodeId=6860

**Comment by RLHecht** [comment]
Page was OK'ed by stakeholders and published. Moving to validate and will close after next deploy.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
