### ISSUE TITLE
Design intent [Facilities - Emergency mash-up]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23439]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Link to this issue once created in #design in Slack; tag @vsp-product-support-members.
- [x] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] VSP: Create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [x] VFS: Respond appropriately to VSP feedback tickets.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts
- [Product brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/product/emergency-care-mashup)
- Sketches
- Lo-fi mockups
- [Prototype](https://preview.uxpin.com/8767aa9028468a26be090fd044d9ff26e40a8f95#/pages//simulate/no-panels?mode=i)

## Meeting attendees from requesting team
- Designer(s) (required): Nick Osmanski (nick.osmanski@amida.com), Leyda Hughes
- Product Manager (required): Michelle Middaugh
- DEPO Product Lead (recommended): Dave Conlon
- DEPO Design lead (required): Ryan Thurlwell
- Content, IA, accessibility, and QA specialists (if applicable): Josh Kim or Angela Fowler
- Other stakeholders you want to invite (if applicable)

## Scheduling
Would you like this review to be asynchronous? Please refer to the Design Intent guidance for the difference between a synchronous meeting and an asynchronous review.

- [ ] Yes
- [x ] No

What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
**Tuesday, April 27 at 11:30 AM ET**
**Thursday, April 29 at 1:30 PM ET** 

Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
thanks @mmiddaugh ! Would you be able to complete a [Collab Cycle kickoff ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D) for this work? I don't think we've been introduced to this project yet.
