### ISSUE TITLE
Update Vet Center UX PIN for leadership review

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23454]
## Issue Description
We need a method for Vet Center leadership to understand the Vet Center MVP so that it can be used in conversations to get support/buy-in. Because the FE implementation is not yet fully complete, we need to update the UX pin spec for this purpose. 

---
## Tasks
- [x] Update the Vet Center UX pin mobile design spec 

## Acceptance Criteria
- [ ] Vet Center leadership can view an example Vet Center main page and location page containing all MVP components 
- [ ] All accordions open, including Prepare for your visit (appointment), services and "How we're different" areas
- [ ] Service accordions should contain national descriptions and local content. 

(Michelle will attach spreadsheet with data for use in filling in service accordions)

**Comment by lildziner** [comment]
Waiting on:
• confirmation of final categorization of services (those not yet in Drupal)
• decision on addition of a subhead to replace "Care we provide at [Orlando]" and final wording.  e.g. just strip out location and shorten to "Care we provide:"?

Is the following correct:

### Counseling services

- Couples and family counseling
- Grief and bereavement counseling
- LGBT Veteran care
- Intimate partner violence support
- Mental health care
- Minority Veteran care
- PTSD
- Recreational and creative arts therapy
- Returning service member care
- Whole health
- Women Veteran care

### Referral services

- Addiction and substance abuse care
- Homeless Veteran care
- Suicide prevention
- Veteran connections

### Other services

- Community engagement
- Telehealth
- Vocational rehabilitation and employment programs
- Workshops and classes

**Comment by lildziner** [comment]
Here is the [prototype](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/136042529?mode=cvhidm) with working interactions for all accordions, containing the latest content decisions and examples from Escanaba and Springfield.
