### ISSUE TITLE
[FE] Update PDF loading message

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#23459]
## User Story

As a veteran I should be able to download a PDF version of my answers so That I have them for my records

## Related Documentation

> these should be links to feature docs

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- [Orginal Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13146)

## Description

Update the loading indicateors for download PDF

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update loading UI for list page
- [ ] Update loading UI for confirm page
- [ ] Create user tests
- [ ] Create e2e tests

## Acceptance Criteria

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
![Screen Shot 2021-05-04 at 3 32 39 PM](https://user-images.githubusercontent.com/1793923/117059618-fefaad80-aced-11eb-9ee4-41ec50678b79.png)

@kristenmcconnell  If I followed the thread, this is what you had in mind (I think?). Let me know what changes I need to make.

**Comment by kristenmcconnell** [comment]
That is what I had in mind. It looks good to me.

**Comment by mdewey** [comment]
@kristenmcconnell  This is in staging for you to review.

**Comment by kristenmcconnell** [comment]
It looks great in staging. No changes or additional comments from me.
