### ISSUE TITLE
[FE] Update Item text answer

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#23461]
## User Story

As a veteran, I should see the same questions everywhere

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description

Update the items being posted to the questionnaire manager endpoint.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Update the questions text being posted
- [x] Move questions to config file
- [x] Create unit tests

## Acceptance Criteria

> when is the ticket done

- [x] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
