### ISSUE TITLE
Create a Card Layout for Displaying Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2346]
## Story
As an end user, I want to be able see my rated disabilities in a clear, concise way so that the information is represented as clearly as possible.  

## Considerations
An example can be found on the [Claim Status Tool](https://staging.va.gov/?next=%2Ftrack-claims%2Fyour-claims)

## Task
- Create a reusable React component that will display the data to the user

## Definition of Done
- [x] Display a set of cards as populated from data from JSON
- [x] The component is responsive down to 320px breakpoint
- [x] Styling is consistent with other examples on VA.gov
- [x] Passed code review and merged into master.

**Comment by micahchiang** [comment]
Merged into master via https://github.com/department-of-veterans-affairs/vets-website/pull/10908
