### ISSUE TITLE
[FE] Update timezone display

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#23460]
## User Story

As a veteran, I should see timezones in my the timezone of the facility so that I know when my appointment it

## Related Documentation

> these should be links to feature docs

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
Update the front end to work off of the timezone of the facility 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Find out if the lighthouse team can add the time zone data
- [x] Default timezone to PT
- [x] Update To Do List items
- [x] Update Completed list items 
- [x] Update Demographics
- [x] Update Demographs review page
- [x] Update intro page?
- [ ] update unit tests

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
![Screen Shot 2021-05-05 at 9 53 38 AM](https://user-images.githubusercontent.com/1793923/117152199-cc04f800-ad87-11eb-8664-7cfc48e56a96.png)

In staging.
