### ISSUE TITLE
Only published facility services should be included in the build 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23470]
## Issue Description
Unpublished (either draft, in review, or archived) facility services are included in builds. This causes duplicate services, leading to accessibility and usability issues, broken links, and/or build problems. 

Example 1: 
There are two Homeless Veteran care accordions on https://www.va.gov/wilmington-health-care/locations/wilmington-va-medical-center/ Each of these accordions is tied to a discrete facility health service node. 

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/114779802-c8a3c100-9d33-11eb-97cc-c71d307462d9.png)

</details>

<details>
<summary> Note the moderation state: one is published and the other is archived. </summary>

![image](https://user-images.githubusercontent.com/55411834/115305306-56f8b800-a123-11eb-939e-073741b85141.png)

</details>

---

Example 2: 

<details>
<summary> Atlantic County VA has two archived services which appear in the system-level service accordion and on the facility page </summary>

![image](https://user-images.githubusercontent.com/55411834/115308363-d1c3d200-a127-11eb-848b-8baa7586df99.png)

![image](https://user-images.githubusercontent.com/55411834/115308448-f324be00-a127-11eb-8e97-87ed8d31ddae.png)

![image](https://user-images.githubusercontent.com/55411834/115308641-43038500-a128-11eb-88fe-37da18501986.png)

</details>

---

The CMS team has issues in the backlog to prevent duplicate content from being created in this way in the future, but the unpublished content problem is independent of that.
Content can be deleted to eliminate the immediate problem ([AXE-CORE]: VAMC - Accordions need unique labels #21789)

---
## Tasks
- [ ] Ensure archived and/or draft services are not added to build
- [ ] Add filter to GraphQL to build published content only. 

## Acceptance Criteria
- [ ] Unpublished (draft) content is not added to the build. 
- [ ] Archived content is not added to the build. 
- [ ] Only published services appears on the facilities page 
- [ ] Only published services cause a link to the facility from within the system service accordion
- [ ] When I create a draft service, it does not appear on the health service list for the facility
- [ ] When I create a draft service, it does not cause a link to that facility from within the system service accordion
- [ ] When I archive a service, it does not appear on the health service list for the facility
- [ ] When I archive a service, no link remains from within the system service accordion
- [ ] Archiving or creating services does not cause broken links.

**Comment by mpelzsherman** [comment]
this code was deployed to production tonight, so I checked https://www.va.gov/wilmington-health-care/locations/wilmington-va-medical-center/ and there are no AXE violations due to duplicate services. Also, https://www.va.gov/wilmington-health-care/locations/atlantic-county-va-clinic/ no longer includes the archived services (Adaptive Sports and Geriatrics).

**Comment by mmiddaugh** [comment]
@1Copenut this one can be validated when you have a moment

**Comment by 1Copenut** [comment]
@mmiddaugh & @mpelzsherman These issues look to be resolved for both of the linked Wilmington VAMCs. I'll keep an eye on the CI logs, and moving this issue to closed.
