### ISSUE TITLE
Appointment cards updated design and states

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23478]
## Description
Update homepage refresh appointment cards based on VSP Accessibility and Design feedback.

---
## Tasks
- [ ] Default state
- [ ] Hover state
- [ ] Focus stage
- [ ] Active state

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] Given any device, When appointment list displays, Then show default state of appointment cards
- [ ] Given desktop, When user hovers over an appointment card, Then show hover state on respective card
- [ ] Given any device, When appointment card receives focus, Then show focus state on respective card
- [ ] Given any device, When user clicks/taps appointment card, Then show active state on respective card AND open appointment details
- [ ] Given appointment detail initiated from list, When user navigates back to appointment list, Then appointment card no longer shows active state

- [ ] Given confirmed appointment, When appointment is canceled, Then show canceled status label

- [ ] DESIGN - Designs match the specs (copy is FPO) https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/JnPpm4M#Inspector
![Screen Shot 2021-04-19 at 4.08.53 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/4c1936c7-24a9-484b-acd1-8ae81997db16)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
