### ISSUE TITLE
Only include published locations in FE builds

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23481]
## Issue Description
Unpublished (either draft, in review, or archived) locations have been included in builds, potentially causing a number of problems. In this case, a location that is not yet open displayed in the front end despite being archived by the VAMC team (#21791). 

The absence of  the phone number for this archived location causes a high severity "Links must have discernible text" AXE error on two pages:
[System level location page](https://www.va.gov/salt-lake-city-health-care/locations/)
Cache Valley VA Clinic page

---
## Tasks
- [ ] Ensure archived and/or draft services are not added to build
- [ ] Add filter to GraphQL to build published content only. 

## Acceptance Criteria
- [ ] Unpublished (draft) content is not added to the build. 
- [ ] Archived content is not added to the build. 
- [ ] Only published locations are included on system-level location pages 
- [ ] When I create a draft location, it is not displayed on the system-level location pages
- [ ] When I archive a location, it no longer appears on the system-level location pages 
- [ ] Only published locations have pages themselves 
- [ ] When I create a draft location, the location page does not render on the front end. 
- [ ] When I archive a location, the location page no longer renders on the front end. 
- [ ] Archiving or creating locations does not cause broken links.

**Comment by mpelzsherman** [comment]
Cache Valley VA Clinic is PUBLISHED. See https://prod.cms.va.gov/salt-lake-city-health-care/locations/cache-valley-va-clinic. 

So the theory that archived locations are showing up in the build is looking less likely. I’m still investigating, but the example in the ticket isn’t such a case, and the query looks OK to me so far.

**Comment by mpelzsherman** [comment]
I have examined the query used to pull the data for this page. All of the queries appear to be filtering correctly on the published status. There is a field, `fieldOtherVaLocations`, that returns a list of VA facility ID's - we can't filter this data by status. But if we are seeing examples of unpublished locations from that field, we cannot fix this in graphql.

I'm moving this to "Validate" until I can get an example of a page showing an actual archived location.

**Comment by mpelzsherman** [comment]
Once Cache Valley VA Clinic has been archived and the axe checks are run again, we can close this if there are no other errors due to unarchived content showing up in the build.

**Comment by mpelzsherman** [comment]
We will test this in Tugboat - change status to Archived and Draft, and confirm it no longer shows up in either case.

**Comment by mpelzsherman** [comment]
Confirmed by testing locally against Tugboat. Closing.
