### ISSUE TITLE
Updated Email Template

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#23487]
## Issue Description
_To obtain better information from callers regarding their issue(s) with claims/appeals_

---
## Tasks
- [ ] _Take the current template that we use and modify it to include the information that we have been provided from the meeting with BAM team._

## Acceptance Criteria
- [ ] _A new template that will provide better data to the appropriate team._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
This is the current template that we use:

_Thank you for your inquiry. Are you still experiencing this issue? If yes, we will need more information to investigate the problem and find a solution. In as much detail as you can, please respond to this email with answers to the following prompts and questions:_
 
_Please provide step-by-step details of what actions you are taking and what happens when you do.
Please copy and paste the URL or web address you were on when you experienced the issue.
If you saw an error message, please copy and paste the exact text of the error message.
What type of device are you using (i.e., Dell laptop, MacBook, iPhone, etc.)?
Try a different browser (i.e. Internet Explorer, Firefox, Chrome, etc.). Does the issue occur on all browsers?
What account do you use to sign into VA.gov (DS Logon, MyHealtheVet, ID.me)?
Thank you,
VA.gov Technical Support Team_

**Comment by Kimberley2019** [comment]
After meeting with Steven for our one on one, I slacked Anna Carey the message below for more clarification. Awaiting a response.

_Good Afternoon Anna.  I hope that you are having a great day and week so far.
We are updating our template that we discussed the other week during our call; I'm hoping that you could quickly help me with the following:_

- Number at bottom of page (by save button). That number is very helpful to us - it’s like a form id.

- [ ] Is this the application ID that was shown during the meeting?  If not, could you please send me a screen shot of this and/or advise if it is on a particular page?

- EDIPI, or ICN, save in progress ID is best.

- [ ] Can you please provide the actual names of these?  Also, where can the 'save in progress ID' be found?  Is that the same application ID?  If not, can you please provide a screenshot and/or the page it can be found on?

**Comment by Kimberley2019** [comment]
1.  What account do you use to sign into VA.gov (DS Logon, MyHealtheVet, ID.me)?
  _Not only ask what account they used to login but also suggest logging in with a different account_

2. Try a different browser (i.e. Internet Explorer, Firefox, Chrome, etc.). Does the issue occur on all browsers?

3. What type of device are you using (i.e., Dell laptop, MacBook, iPhone, etc.)?

4. If you saw an error message, please copy and paste the exact text of the error message.

5.  Please copy and paste the URL or web address you were on when you experienced the issue.

6. Please provide step-by-step details of what actions you are taking and what happens when you do.
   _Can rephrase to for the veteran to provide steps if issue still occurs after all other steps have been taken._

**Comment by Kimberley2019** [comment]
Will meet with @starlow00 on 5/5/2021 to ensure that verbiage is good.

**Comment by starlow00** [comment]
Draft to review with @Kimberley2019 [https://app.zenhub.com/files/133843125/c57e2be4-3e8f-4185-a455-d271aa4732a9/download](https://app.zenhub.com/files/133843125/c57e2be4-3e8f-4185-a455-d271aa4732a9/download)

**Comment by Kimberley2019** [comment]
The modified version can be found [here](url)[https://app.zenhub.com/files/133843125/b22444c0-556c-4b8b-b1bc-4663295a819c/download](https://app.zenhub.com/files/133843125/b22444c0-556c-4b8b-b1bc-4663295a819c/download)
