### ISSUE TITLE
NOD Phase 2 Design Tasks

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#23494]
## Issue Description
Complete phase 2 design tasks.

####Content brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/content-brief-NOD.md
---
## Tasks
- [x] Address all of Robin's comments from design --> dev (for the duration of the sprint)
- [x] Create a 'board hearing preference' page

## Acceptance Criteria
- [x] The above tasks have been met and implemented into the NOD Invision Prototype
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
