### ISSUE TITLE
Staging Review [Public Website, Campaign Landing Page / Trust (VEO)]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23509]
## Steps to complete Staging Review: 

- [X] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [X] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to VSP feedback tickets.
- [x] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [Campaign Landing Page Production MVP] - VA Trust [#23304](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23304)
- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
-  Staging test-user information (if applicable)
-  Link to content brief (if applicable)
-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or elsewhere) 
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): Brian Lloyd
- DEPO Product lead (recommended): John Hashimoto
- DEPO Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): name(s) Kelson Adams, Kevin Walsh, Jane Xiong, Natalie Dunbar
- Content, IA, accessibility, and QA specialists (if applicable): name(s) Mikki Northuis

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **April 27/11:30** 
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://docs.google.com/document/d/1_1gGJW6Go0Kk-H5jttDbQIZrcbKTst9gSZnXKVdeQSg/edit?usp=sharing) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@brianalloyd the date you requested is today and was almost 2 hours ago. Did you mean to choose a different day?

**Comment by brianalloyd** [comment]
@shiragoodman No, sorry was multi-tasking to speed up the process. Was intended to read April 27/11:30. Does that time work?

**Comment by shiragoodman** [comment]
@brianalloyd we have a review with Facilities at 11:30. Can you do 11 on 4/27?

**Comment by brianalloyd** [comment]
That works @shiragoodman, thanks for the support.

**Comment by allison0034** [comment]
@brianalloyd can you add a link and a screen shot please? Some of us don't have CAG and some do. : )

**Comment by brianalloyd** [comment]
@allison0034 here's a link to the preview: http://preview-prod.vfs.va.gov/preview?nodeId=18299, I'll drop a screen shot shortly.

**Comment by allison0034** [comment]
@brianalloyd I don't see the screen shot. Can you upload one please?

**Comment by brianalloyd** [comment]
@allison0034 the stakeholder is still finalizing the design but should be complete today. Once finalized I'll post screen shot in support. Sorry for the delay.

**Comment by mnorthuis** [comment]
No IA feedback on the staging review of the template or content.

**Comment by joshkimux** [comment]
> @allison0034 here's a link to the preview: http://preview-prod.vfs.va.gov/preview?nodeId=18299, with screen shot:

By any chance is there a staging link too? Angela and I are still in the process of getting our SOCKS set up 🧦

**Comment by brianalloyd** [comment]
@allison0034 @joshkimux updated the above comment with finalized screen shot.  @peggygannon could you also do a content QA on this as well, Beth Potts mentioned content reviews for CLPs might be best handled via this Platform review.  Please reach out if you need anything else in support.  Thanks.

**Comment by pjhill** [comment]
Hey @brianalloyd, I don't see any QA materials for staging review linked in this ticket. Are there QA artifacts available for review at this time?

**Comment by brianalloyd** [comment]
@pjhill I can't think of any outside of a content review, everything else should be pretty streamlined from a CMS prospective.

**Comment by brianalloyd** [comment]
@peggygannon you mentioned a ticket concerning the "6 million surveys" question this AM in staging review, could you link here if possible.

**Comment by peggygannon** [comment]
Hi, @brianalloyd yes, I just linked my feedback ticket, with a few questions about the intro content.  please let me know if you have any questions or need me to clarify anything.

**Comment by johnhashva** [comment]
@peggygannon or @brianalloyd I can't find the content feedback link -- can you post as a comment?

**Comment by peggygannon** [comment]
Hi, @johnhashva here you go: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23778

**Comment by laflannery** [comment]
@shiragoodman All tasks in this epic are closed, does that mean I can close this ticket?

**Comment by shiragoodman** [comment]
@laflannery yes, it can be closed. We typically leave that to the VFS team.

**Comment by laflannery** [comment]
Thanks! Just doing some clean from the older teams
