### ISSUE TITLE
[Post Launch] Create UI Fit/Finish Punchlist for Form 28-1900 (CH31)

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#23502]
### Background
VA Form 28-1900 is out of sync with approved mockups and content. Feedback from Midpoint and Staging reviews have not been implemented. Now that the 28-1900 has deployed, we need a punchlist identifying the differences so they can be addressed.

### Tasks
- [x] Review punchlist for content changes
- [x] Review punchlist for design changes
- [ ] Generate punchlist

### Acceptance criteria
- [ ] Punchlist available in GH as a markdown file

**Comment by sporeboy** [comment]
Initial list available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/research-design/content/ch31-punchlist-080921.md

Will be reviewed--changes likely.
