### ISSUE TITLE
Post Research Tasks: Baseline Wayfinding Research on VA.gov

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23518]
## Description 
Wrap up research study and associated documents/resources

## Tasks
- [x] Share research report with team, stakeholders, research, Shawna for feedback
- [x] Add participant characteristics into MVS checker (for marginalized groups)
- [x] Make short presentation from research report for Sprint Demo 
- [x] Make longer presentation for Design/Research/Content Mon mtg and OCTO DE Sitewide crew
- [x] Present findings to team and stakeholders, discuss recommendations--scheduled for May 20, followup on May 21
- [x] Revise report per report out discussions
- [ ] Close out ticket once once completed
- [x] Post report on Github
- [x] Add link to Research History page
- [ ] Delete recordings -- WAIT until after recommendations discussions w/teams
- [x] Remove PII from notes and post on Github, along with any other synthesis documents

**Comment by cindymerrill** [comment]
Shared report on #public-websites and with Josh and Angela: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/research-report.md. 

Scheduled report out meeting for Friday May 21.

**Comment by cindymerrill** [comment]
Report out meeting now on Thursday May 20 instead.

**Comment by cindymerrill** [comment]
Readout of research findings happened today. Planning to discuss recommendations from research tomorrow (Friday May 21).

**Comment by cindymerrill** [comment]
Discussed some recommendations with the team today, but there were too many to get through them all. Decided to categorize recommendations by relevant team, and then discuss separately with each team. 

I did the categorization as best as I could and shared the spreadsheet with Meg Peters to review/edit. Then will schedule meetings with each team.

**Comment by cindymerrill** [comment]
Completed readout presentation for June 1 Sprint Demo, which is posted here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/research-readout-sprintdemo-June1.pdf

**Comment by cindymerrill** [comment]
Presented at June 1 Sprint Demo. Removed PII from session notes and posted on Github. 

Still need to work on the longer version of the presentation. Won't delete recordings until after recommendations meetings have happened, in case we need to look back at specific navigation paths, so will move this to the Ideation ticket.

**Comment by cindymerrill** [comment]
Drafted longer version of readout presentation. Will share it for feedback tomorrow (Thursday) so can make changes before presenting on Monday and Tuesday.

**Comment by cindymerrill** [comment]
Revised presentation more, and then shared with John and Meg Peters for feedback.

**Comment by cindymerrill** [comment]
Revised long presentation per John's and Meg's feedback. Ready to present on Mon and Tue.

**Comment by cindymerrill** [comment]
Deleted all recordings, and now closing ticket.
