### ISSUE TITLE
Research synthesis and reporting: Baseline Wayfinding Research on VA.gov

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23517]
## Description 
The purpose of this research is to get a baseline understanding of how the current VA.gov website is being used by Veterans and others. With a better understanding of Veterans' pain points and successes while using VA.gov, we can make more informed decisions about priorities for future research and design work in website navigation and tools.

## Tasks 
- [x] Clean up notes spreadsheet 
- [x] Write topline summary and share out with team--target May 6
- [x] Do data analysis/synthesis of data collected from research  
- [x] Write research report

**Comment by cindymerrill** [comment]
Topline summary shared out to #public-websites. Link here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/topline-summary.md

**Comment by cindymerrill** [comment]
Completed draft of research report. Getting it reviewed by 2 people so can make some revisions before sharing on #public-websites.

**Comment by brianalloyd** [comment]
Reviewed, and closing.
