### ISSUE TITLE
Conduct Research: Baseline Wayfinding Research on VA.gov

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23516]
## Description 
Conduct research with Veterans and caregivers

## Tasks 
- [x] Print conversation guide
- [x] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x] Conduct scheduled research sessions
- [x] Debrief research sessions w/team
- [x] Post debrief/updates on slack
- [x] Debrief research sessions into note-taking spreadsheet
- [x] Download recordings
- [x] Download notes from Perigean
- [x] Download final participant list from Perigean
- [x] Change display name of Perigean Zoom account back to what it was
- [x] Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

**Comment by cindymerrill** [comment]
Research sessions with first 2 participants completed

**Comment by cindymerrill** [comment]
Now have 5 completed sessions

**Comment by cindymerrill** [comment]
This week, I completed 7 research sessions. The rest were no-shows, cancellations, reschedules, or severely limited sessions due to technology issues. I’m hopeful that next week’s sessions on Mon-Wed will get me to my goal of 12 sessions completed.

**Comment by cindymerrill** [comment]
Completed the 12th research session today, so closing this ticket.
