### ISSUE TITLE
Remove date-fns from maintenanceBanner.js

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#23525]
## Prerequisite
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23523

## Issue Description
The site-wide [`maintenanceBanner.js`](https://github.com/department-of-veterans-affairs/vets-website/blob/direct-deposit-review-fix-cv/src/platform/site-wide/banners/config/maintenanceBanner.js#L2) uses `date-fns`. Because we can't get the webpack tree-shaking to remove the unused parts of the library, it's adding the whole library (~20kb) to the JS bundle.

Once we [remove `date-fns` from the `component-library`](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23523) and use that version in `vets-website`, we need to remove the `date-fns` dependency from the `maintenanceBanner.js` module.

---
## Tasks
- [ ] Use the latest version of `component-library` when `date-fns` has been removed from it
- [ ] Remove the `date-fns` usage from `maintenanceBanner.js`
  - I'd like to just temporarily re-write the functions we're using so we don't have to use `moment`, but if that's not straightforward, we can fall back to `moment` again

## Acceptance Criteria
- [ ] `date-fns` is no longer included in the `maintenanceBanner.js`
  - Probably this will mean it's removed from the `static-pages` bundle, but I'm not sure if it also shows up in application bundles; need to confirm where `date-fns` is included first

**Comment by bkjohnson** [comment]
Addressed in https://github.com/department-of-veterans-affairs/component-library/pull/243
