### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA  Lovell health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#23548]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[ Lovell healthcare system Legacy Site](https://www.lovell.fhcc.va.gov)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-12 Playbook locations](https://drive.google.com/drive/folders/1gSLnLB0lehQjdNvA-LJFwmBS0oyNNqky)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_556	Captain James A. Lovell Federal Health Care Center
- [x] vha_556GA	Evanston VA Clinic
- [x] vha_556GC	McHenry VA Clinic
- [x] vha_556GD	Kenosha VA Clinic
- [x] TBD  USS Osborne Dental Clinic
- [x] TBD  USS Red Rover
- [x] TBD  USS Tranquillity
- [x] TBD  Zachary and Elizabeth Fisher Medical and Dental Clinic

## Definition of Done-Acceptance Criteria
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [ ] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#23548 Create new Health Services "LIST and PLAYBOOK" for VA Lovell health care - Moved to BLOCKED as awaiting information regarding USS Red Rover, USS Tranquility, and Zachary and Elizabeth Fisher Medical and Dental Clinic
