### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA Iron Mountain health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#23551]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[ Iron Mountain healthcare system Legacy Site](https://www.ironmountain.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-12 Playbook locations](https://drive.google.com/drive/folders/1gSLnLB0lehQjdNvA-LJFwmBS0oyNNqky)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_585	Oscar G. Johnson Department of Veterans Affairs Medical Facility
- [x] vha_585GA	Hancock VA Clinic
- [x] vha_585GB	Rhinelander VA Clinic
- [x] vha_585GC	Menominee VA Clinic
- [x] vha_585GD	Ironwood VA Clinic
- [x] vha_585GF	Manistique VA Clinic
- [x] vha_585GG       Gladstone VA Clinic
- [x] vha_585HA       Marquette VA Clinic
- [x] vha_585HB       Sault Saint Marie VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
Changed vha_537 Jesse Brown Department of Veterans Affairs Medical Center
 vha_537BY Adam Benjamin Jr., Veterans' Administration Outpatient Clinic
 vha_537GA Iron Mountain Heights VA Clinic
 vha_537GD Lakeside VA Clinic
 vha_537HA Auburn Gresham VA Clinic
 vha_537QA Iron Mountain VA Clinic 
to the following
vha_585	Oscar G. Johnson Department of Veterans Affairs Medical Facility
vha_585GA	Hancock VA Clinic
vha_585GB	Rhinelander VA Clinic
vha_585GC	Menominee VA Clinic
vha_585GD	Ironwood VA Clinic
vha_585GF	Manistique VA Clinic
vha_585GG	Gladstone VA Clinic
vha_585HA	Marquette VA Clinic
vha_585HB	Sault Saint Marie VA Clinic

**Comment by bcastoe** [comment]
#23551 Create new Health Services "LIST and PLAYBOOK" for VA Iron Mountain health care - Completed and moved to Validate.
