### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA Milwaukee health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#23553]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[ Milwaukee healthcare system Legacy Site](https://www.milwaukee.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-12 Playbook locations](https://drive.google.com/drive/folders/1gSLnLB0lehQjdNvA-LJFwmBS0oyNNqky)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_695	Clement J. Zablocki Veterans' Administration Medical Center
- [x] vha_695BY	John H. Bradley Department of Veterans Affairs Outpatient Clinic
- [x] vha_695GA	Union Grove VA Clinic
- [x] vha_695GC	Cleveland VA Clinic
- [x] vha_695GD	Milo C. Huempfner Department of Veterans Affairs Outpatient Clinic
- [x] vha_695QA	Milwaukee VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
#23553 Create new Health Services "LIST and PLAYBOOK" for VA Milwaukee health care - Completed and moved to validate
