### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA Tomah health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#23554]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[ Tomah healthcare system Legacy Site](https://www.tomah.va.gov/)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-12 Playbook locations](https://drive.google.com/drive/folders/1gSLnLB0lehQjdNvA-LJFwmBS0oyNNqky)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] vha_676	Tomah VA Medical Center
- [x] vha_676GA	Wausau VA Clinic
- [x] vha_676GC	La Crosse VA Clinic
- [x] vha_676GD	Wisconsin Rapids VA Clinic
- [x] vha_676GE	Clark County VA Clinic
- [x] vha_676QA	Tomah VA Mobile Clinic
## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
Had to change the following: 
vha_695 Clement J. Zablocki Veterans' Administration Medical Center
 vha_695BY John H. Bradley Department of Veterans Affairs Outpatient Clinic
 vha_695GA Union Grove VA Clinic
 vha_695GC Cleveland VA Clinic
 vha_695GD Milo C. Huempfner Department of Veterans Affairs Outpatient Clinic
 vha_695QA Milwaukee VA Clinic
to the following to reflect correctly: 
vha_676	Tomah VA Medical Center
vha_676GA	Wausau VA Clinic
vha_676GC	La Crosse VA Clinic
vha_676GD	Wisconsin Rapids VA Clinic
vha_676GE	Clark County VA Clinic
vha_676QA	Tomah VA Mobile Clinic

**Comment by bcastoe** [comment]
#23554 Create new Health Services "LIST and PLAYBOOK" for VA Tomah health care - Completed and moved to Validate.
