### ISSUE TITLE
Cleanup - Rename references to vet360 in devops

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#23568]
## Description
The VA profile team has requested that we change all references to `vet360` to their new name `va_profile`

---
## Tasks
- [ ] Audit existing references in devops repo
- [ ] Determine if there are any gotchas to consider
- [ ] Change all references to `vet360` in the devops repo to `va_profile` or `vaProfile`

## Definition of Done
- [ ] All references to `vet360` have been renamed to `va_profile` or `vaProfile`

**Comment by jhouse-solvd** [comment]
@lihanli - Would you mind providing some information about the urgency or timeline of this? It would be helpful for our planning purposes. Thank you.

**Comment by jhouse-solvd** [comment]
This is somewhat involved and touches a lot of pieces. Ops will be involved in doing this to limit the impact to running services. 

We may want to do a pretty thorough audit, and see if there are any gotchas that might occur. It's possible that it's fairly easy/straightforward, but best to be sure.

**Comment by jbritt1** [comment]
Due to the velocity at which the upstream makes updates to naming conventions, it is unlikely this ticket will budge for at least the next year. Please see https://dsva.slack.com/archives/CE4304QPK/p1644334170695339 for tracking. Closing at this time, but happy to reopen if/when the upstream wants to make the updates to accepted nomenclature.
