### ISSUE TITLE
[FSR] Implement the resolution selection screens redesign [usability]

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23561]
## Issue Description
_In usability, we found that Veterans struggled with the resolution selection page looping through each of their debts. We've updated the design to hopefully be a quick fix as we move towards release with the intention of revisiting when we add in 'first choice' and 'second choice' resolution selection in the future._

**The design**
- [Default resolution request screen](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138377446/simulate/no-panels?mode=i)
- [Selected resolution](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138377445/simulate/sitemap?mode=i)

Note: The progressive disclosure logic works the same as before. Main differences are: all debts are on one page, consolidated content, adjusted cards

---
## Tasks
- [ ] _Update the UI to reflect the provided prototype_

## Acceptance Criteria
- [ ] _UI has been updated to match the prototype_
- [ ] _The updated section has been reviewed by a designer in staging_
