### ISSUE TITLE
[VAMC] Please add Operating Status to all Systems in VISN-10 and associate the System page to the new Operating Status page [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#23563]
## Story
As a administrator the Operating Status Pages need to be created from scratch and associated to the system page, so emergency status and information updates can be released to the Veterans.

## TASK 
- [x] VA Ann Arbor health care
- [x] VA Central Ohio health care
- [x] VA Chillicothe health care
- [x] VA Cincinnati health care
- [x] VA Dayton health care
- [x] VA Northeast Ohio health care
- [x] VA Battle Creek health care
- [x] VA Detroit health care
- [x] VA Indiana health care
- [x] VA Northern Indiana health care
- [x] VA Saginaw health care

## Acceptance Criteria
- [x] All Operating status pages are created for all systems and they are associated to the System page.

**Comment by ltrombley** [comment]
Task #23563 - Please add Operating Status to all Systems and associate the System page to the new Operating Status page [BA] - is Complete and moved to Validate.
