### ISSUE TITLE
Migrate [email list] from email to GitHub Auth

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#23571]
## Issue Description
We should look at migrating [this list](https://github.com/department-of-veterans-affairs/vets-api/blob/f7f84ddae1c7c316871f024a762b924d9eecb915/config/settings.yml#L663-L740) from email to GitHub Auth.

[Slack context](https://dsva.slack.com/archives/G01M8VD9USC/p1618933453197300?thread_ts=1618593244.173500&cid=G01M8VD9USC)

>We've already talked about using github auth for other things like sidekiq, we should add this to the list. When we do planning for Q3 we can look at adding this

---
## Tasks
- [ ] Investigate what tasks would be required to move the list to GH Auth
  - [ ] Break implementation work (below AC) into separate tix if necessary
- [ ] Email blast to existing users asking for GH usernames to add after launch
- [ ] Document and execute tasks
- [ ] Post-launch email blast to let folks know why they no longer have access and how to request access

## Acceptance Criteria
- [ ] Discovery on what would be required is complete
- [ ] List has been migrated from email to GH Auth
