### ISSUE TITLE
Backend Engineering: Review 'Dependents' Work

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2358]
## Story
As a backend engineer, I want to know how much of the existing 686c code is complete, so I can gain an accurate idea of the level of effort involved, and other issues, to make this application feature complete. 

## Goals
Primarily, to fully understand work that has already been completed and map any functionality that is still outstanding.

## Tasks
- [x] Review the 686c form [Product Outline](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Disability/Declare%20Dependent%20686) with respect to engineering  
  - [x] [API Calls](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability/Declare%20Dependent%20686/api%20calls.md)
- [x] Spin up the feature locally and identify what is functioning "as-is"
- [x] Identify endpoints and data sources used currently and within previous Dependents work notes 
  - From EVSS to BGS
-  [x] Document how much of the current work needs to be connected
   - See list of bugs here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686FrontEndResearch.md

## Acceptance Criteria
- [x] Document in Github [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering) the findings from this review (may include some validation)
  - Documentation added here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-back-end-research.md
  - [x] Identify pathways that need more attention and create an issue for them
  *Issues still need to be created, waiting for more research/discovery with FE team related to json schema validation and other FE issues*

## Next Steps
This will create other tickets

**Comment by kathleencrawford** [comment]
Documentation added here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-back-end-research.md
