### ISSUE TITLE
Begin Design Mock Ups for Search KPI Dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#23584]
## Issue Description
Design mock ups for the Search KPI Dashboards so that we can test what works well, what doesn't, and how we can standardize the dashboards & data for Search KPIs.

---
## Tasks
- [ ] Use the following backlogged KPI dashboards to create "paper" prototypes:
  - [ ] [Facilities](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15131)
  - [ ] [Search & Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16778)
  - [ ] [Type Ahead](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20838)
  - [ ] [Resources & Support](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16233)
- [ ] Share mock ups with the rest of the team for initial feedback

## Acceptance Criteria
- [ ] Platform Analytics has a mock up to test with VFS customers & to test our queries and data architecture against so that we can see what's feasible to standardize & what we'll need to iterate on

**Comment by joanneesteban** [comment]
@mandy-uxd - can you link your designs to this ticket, please?

**Comment by joanneesteban** [comment]
Mock ups were created [here](https://projects.invisionapp.com/share/B710P0FGUQSE#/screens/450753724/comments). Closing this ticket.
