### ISSUE TITLE
Build out health care questionnaire landing page in Drupal

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23589]
## Issue Description
To support the launch of the new health care questionnaire, we need to create a static landing page in Drupal based on the health care team's wireframe. 

Wireframe: https://www.sketch.com/s/fd688be2-76eb-484b-a306-9c1b522f4f09/a/kaQLyag

More info is provided in ticket #22530
## Tasks
- [x] Build page in Drupal (Selina)
- [x] Copy edit and review (Randi/Danielle)
- [x] Let health care team know work is complete (Randi)

## Acceptance Criteria
- [x] New static landing page is built in Drupal

**Comment by lunascoop** [comment]
@RLHecht this page has been created but the information alert box I created (I assume it'll be a react widget when live) is not showing in Drupal preview. I'll ask you about it later to see if I'm doing something wrong, before I open a CMS ticket.

- http://preview-prod.vfs.va.gov/preview?nodeId=18656

**Comment by RLHecht** [comment]
This page looks good to me though just confirm that the alert shows after Kelson's PR is merged. @DanielleThierryUSDSVA wasn't sure what the next steps are. Do you want to review and we can let the team know this is built?

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This page is ready for you. There's an issue with the styling of the CTA button that FE is working on (it should be blue with white text, but is currently showing as blue with blue text).

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht! This looks good. @mlighdc and I have been working on the privacy language. I updated it in the Drupal page.

cc @kristenmcconnell 

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/2088dade-3ca3-4b4e-8496-c6771fc27952)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht - it does say there's a broken link on the page so just want to make sure to fix that.

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell @peggygannon  - 2 additional things for awareness:

1. @ming and I talked about sharing this more general language with the privacy folks and asking if this could also work in the form intro page. If not, we'll review that language with them again and come back with final recommendations.

2. We're in the process of updating the content pattern for tool landing pages. Not changing the actual content really, but just moving components around a bit and using some accordions. When we have that finalized, I'll share with you and also recommend how it can work on this page. Thanks!

**Comment by RLHecht** [comment]
Thanks @DanielleThierryUSDSVA I have a support ticket in to the CMS team for the broken link. It works fine outside of the CMS so it might not be an issue but I want them to confirm.

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA and @mlighdc The wording looks good to me. Yes, the team's front-end engineer is waiting to hear when he can make changes to the intro page, because we are about to head into staging review.

@DanielleThierryUSDSVA Can you send the text to me in a format that I can easily copy (non-image)?

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell Sure, yes! Here you go:

**Will VA protect my personal health information?**

We make every effort to keep your personal information private and secure.

[Read more about privacy and security on VA.gov](http://preview-prod.vfs.va.gov/privacy-policy/)

You're also responsible for protecting your personal health information. If you print or download your information—or share it electronically with others—you’ll need to take steps to protect it.

[Get tips for protecting your personal health information](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/protecting-your-personal-health-information)

**Comment by kristenmcconnell** [comment]
Thank you.

**Comment by RLHecht** [comment]
Closing ticket as the acceptance criteria was met. Please let me know if it should still be open.
