### ISSUE TITLE
DECISION TOOLS SPRINT 46 PRIORITIES

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23587]
## :fire: Sprint 46 Priorities

 - [x] **Find a VA Form**: Follow up with Content team on When to Use copy
 - [x] **Search UI Consistency:** Determine next steps
 - [x] **Discharge Upgrade Wizard:** Update unit testing
 - [ ] **Discharge Upgrade Wizard** Mock up link change - Blocked; need content first.
 - [x] **Find a VA Form:** Unpublish Spanish-language detail pages
 - [x] **Find a VA Form:** Determine which detail pages need Medallia survey~~
- [x]  Create feature flag to hide logic change in Production

#### Zach
- [x] Work out ranking/scoring logic for search terms with Mark
- [x] Create feature flag to hide logic change in Production - [23599](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23599)

#### Mark (Lighthouse)
- [x] Work out ranking/scoring logic for search terms with Zach
- [x] Write code to apply logic to Forms API

#### John & Marci
- [ ] Test ranking/scoring logic on Dev or Staging - Blocked; need deployed to Staging
- [x] Follow up on Content Request #22726
- [x] Determine which detail pages need Medallia surveys & update issue #23207  -  Decision - Top 5 pages - ask for data in 3 weeks.

#### John
- [x] Archive Spanish-language pages #22817

#### Cassandra
- [ ] Mockup for PDF to eApplication Change  - SPRINT 47 - need content first.

#### Zach
- [x] Testing Upgrades #23155
- [x] Organize application #23156

#### Cassandra & Megan
- [x] Review feedback from design intent review
- [X] Collaborate with Marci to create new issues for additional work

### FIND A YELLOW RIBBON SCHOOL
N/A

###  🗨️  Discussion Topics/Grooming 
- [x] Feedback from Design Intent review - Cassandra is reviewing the feedback and making updates based on that.
- [x] Resources & Support mobile nav will be de-scoped from this and made into a separate effort. 
- [x] Crystabel is going to address the hover on the action link falling outside the link.
- [X] Research/testing for search UI changes (Cindy) - there was no feedback related to user testing. Megan's earlier research may have satisfied that.  Is the expectation that we still need to test these changes?  Once the feedback is incorporated, Product team will decide if we will press forward or test.

**Comment by MarciMcGuireGCIO** [comment]
- Zach & Mark will play around in Review instance for a couple of days, then promote search ranking logic to Staging
- Cassandra is reviewing feedback from Design Intent Review

**Comment by MarciMcGuireGCIO** [comment]
4/23/2021
- Zach has been working on Discharge Upgrade Wizard - testing, refactoring
- Chatted with Mark; he's getting stuff spun up locally for Find a VA Form
- Cassandra is going to circle back and add everything to the new ticket.  Posted to the Design, AI and Accessibility tickets with her changes
- Cassandra is not done with the Sketch files for Ryan; hopefully by end of day.  She did share her inVision links.

**Comment by MarciMcGuireGCIO** [comment]
4/26/2021

- I'm trying to generate an SSH keypair so I can request SOCKS access
- Observed Cindy's first research session
- Categorized feedback from design intent review
- Cassandra is going to incorporate design intent feedback
- Zach is working on Discharge Upgrade Wizard

**Comment by MarciMcGuireGCIO** [comment]
4/27/2021

- Mark is continuing to work on search ranking; I will enter SOCKS request so I can test on Review env.
- Cassandra is awaiting feedback after incorporating design intent feedback into her mockups. We will reconvene when Megan returns next week with Ryan, Trevor, Josh, and Mikki to decide on open items
- Zach is working on Discharge Upgrade Wizard testing; will pivot to the new Find a VA Form Level 1 508 issue tomorrow.

**Comment by MarciMcGuireGCIO** [comment]
4/29/2021
- 508 Nightwatch issue - ready for peer review; will ping reviewers
- Discharge Upgrade Wizard - Zach is going to break the merges down some to make it easier for review
- Discharge Upgrade Wizard - Zach has it refactored.
- Discharge Upgrade Wizard - Cassandra is going to start working on design intent.

**Comment by MarciMcGuireGCIO** [comment]
4/30/2021

- Mark will merge the Spanish URL change so that it will go to Prod next Wed.  Consensus is it's risky to do on a Friday afternoon.

**Comment by MarciMcGuireGCIO** [comment]
5/3/2021

- Cassandra checked on R&S - they are going to do a research study to have better data.
- Per Zach, Testing for Discharge Upgrade Wizard is done & merged.  Can be closed
- Zach has started refactoring work on Discharge Upgrade Wizard; has a PR out for the initial refactor; expects Nick or Kelson to look at later today.
- Zach also has a PR to add the feature flag for search improvements on Find a VA Form
- Mark squashed & merged back-end change for search improvements this morning; will be able to test on Staging once Zach's feature flag goes in.
- Mark is still on track for form detail change for Spanish URLs on Wed.
- Mark could probably add a field for the added date this week if we want to move forward with that.
