### ISSUE TITLE
GitHub Actions - Create AWS Service Account credentials for vets-api 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23594]
## Description
Ops to create AWS Service Account credentials and add them to vets-api repo so that credentials can be added to parameter store for use w/ GitHub Actions

## Background/context/resources
[Slack discussion](https://dsva.slack.com/archives/CJYRZK2HH/p1618840076337000)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Create AWS Service account
- [ ] Add service account credentials to vets-api repo
- [ ] Verify that @ddzz is unblocked

## Definition of Done
- [ ] Testing Tools Team can use environment variables for PACT w/ GitHub Actions

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jbritt1** [comment]
I believe @dginther knocked this one out, correct? Demian, please confirm as time allows.
