### ISSUE TITLE
Analytics/User Flow tracking for updating phone/mail address to complete Direct Deposit

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2359]
## Background

Need to have a discussion with the analytics team to amend the analytics so were accounting for the errors currently happening.

## User Story

Authenticated Experience team needs a flow report so we can see if users are making the necessary changes to address or phone  when prompted and then proceeding to complete their DD info.

# Goal
By having this information this will give our team the insight needed to validate if our error messaging is effective for the users to continue completing their direct deposit transaction without any issues. 

#Definition of Done
- [x] Talked with Analytics team about what is needed. 
- [x] Received user flow report from Analytics.
- [x] Analyzed flow report with team members to validate our Bets/hypothesis. 
- [x] Close ticket.

**Comment by nedierecel** [comment]
@Justin-Pickett Confirming that we're seeing this issue. Let's Slack up next week to understand how we can modify the granularity of the tracking. Happy to help where we can!

**Comment by Justin-Pickett** [comment]
@nedierecel thank you! We'll coordinate soon next week on this matter.

**Comment by nedierecel** [comment]
Recap from meeting: 

In current state, we can look at the Behavior Flow report to identify potential blocks with [Direct Deposit-->Address Saves](https://analytics.google.com/analytics/web/?authuser=0#/report/content-engagement-flow/a50123418w177519031p187673796/_.goalOption=3&_.useg=useri7QjhRJgTqiUkfwy6eG7_Q&_r.engageMode=events&_r.screen=~2Faccount~2Fconnected-accounts~2Findex.html&_r.hlNode=3-0-1594310882&_r.steps=8/)

The User Flow report provides a more granular [session-by-session analysis of veterans hitting Direct Deposit Failures](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-legacy-user-id/a50123418w177519031p187673796/_.goalOption=3&_.useg=useri7QjhRJgTqiUkfwy6eG7_Q)

*Next Steps* - 

1. @jonwehausen and I will think through an approach to capture the error code or error text from the info provided with the error state. Since more granularity can be provided via Sentry, we will look at the more generic error code. 

`errors: [       {         title: 'Unprocessable Entity',         detail: 'One or more unprocessable user payment properties',         code: '126',         source: 'EVSS::PPIU::Service',         status: '422',         meta: {           messages: [             {               key: 'cnp.payment.generic.error.message',               severity: 'ERROR',               text:                 'Generic CnP payment update error. Update response: Update Failed: Required field not entered for mailing address update',             },           ],         },       },     ], `

1. @erikphansen - Approximately how many error codes exist? In lieu of pushing the entire `text` value, we could have you pass in the code values via the dataLayer. In Google Tag Manager, we can produce a cleaner lookup table that outputs the `code` # and maps it to a more readable format. Example:

- Code 126: Skipped Required Field - Mailing Address

**Comment by erikphansen** [comment]
@nedierecel I'm not really sure how many error codes we could get back. We've been more concerned with the `key`s that come back and then the `text` values. Right now I'm wondering how we could expand on the events we send you when they can't save direct deposit info. This is the function we call when there is any sort of direct deposit update error:

https://github.com/department-of-veterans-affairs/vets-website/blob/97c611a708a5b59f68a276dee58467657c9e1a49/src/applications/personalization/profile360/actions/paymentInformation.js#L97-L101

Pretty basic and 100% _not_ dynamic. I'm thinking we should do something differently if the error is one that tells them to update their contact info. So if the user is seeing an error like this...

![image](https://user-images.githubusercontent.com/20728956/67131899-60663480-f1bb-11e9-9186-71ab1f251ddf.png)

...we would report something slightly different to GA. I could easily parse the errors we get from the server and if it's an error that requires the user to update their contact info in any way, I'd change the call to the `recordEvent()` function so that you could easily find those events and see what users did after they encountered the error. There's no need to pass you error codes or messages exactly as I get them; I can send you whatever would make the most sense on your end.

**Comment by nedierecel** [comment]
@erikphansen Here are two options if you're more interested in the `key` and `text`: 

Suggested State - Option 1:
`recordEvent({
        event: 'profile-edit-failure',
        'profile-action': 'insert-error-here', // e.g. 'missing-invalid-address'
        'profile-section': 'direct-deposit-information',
      });`

You could then pass a more readable format into the `profile-action` like the suggestion above.

Suggested State - Option 2 - keep the general structure then add the errorKey
`recordEvent({
        event: 'profile-edit-failure',
        'profile-action': 'save-failure',
        'profile-section': 'direct-deposit-information',
        'errorKey': 'key-goes-here'
      });`

**Comment by erikphansen** [comment]
@nedierecel The second option would be the simplest for me to implement on my end. How about these as the possible values for the new `errorKey` prop?:

- `mailing-address-error`
- `home-phone-error`
- `work-phone-error`

**Comment by nedierecel** [comment]
Thanks @erikphansen I think this makes sense to bring those error types in.  

@jonwehausen For your visiblity, I will make a new customDimension called `errorKey`, which other teams can also leverage if they'd like. I'll need to add this to the GTM tag for `Profile Save Failures`

**Comment by erikphansen** [comment]
@nedierecel and to be clear, there will still be times that we don't send a `errorKey` at all. Is that cool? Or do you want me to always send _something_ for the `errorKey` value even if the error reason has nothing to do with bad address or phone?

**Comment by nedierecel** [comment]
@erikphansen It would be a nice-to-have, otherwise the value for the errorKey will just remain as null. In those instances, GA would record the value, but we wouldn't have the context as to why.

**Comment by erikphansen** [comment]
so I'll just pass in `other-error` for anything else if that's cool with you

**Comment by nedierecel** [comment]
@erikphansen For naming conventions, is it easier for your code to use camelCase? If so, I can use `errorKey` and also use camel case for the sections like `primaryTelephone` vs. `primary-telephone` (as outlined in #1740).

**Comment by erikphansen** [comment]
@nedierecel it's not any easier one way or another. But for whatever reason we use hyphens in the front end for both the keys and the values. That's how I set it up in my PR that should get merged and this morning and go out with the daily deploy.

**Comment by nedierecel** [comment]
@erikphansen For naming conventions, is it easier for your code to use camelCase? If so, I can use `errorKey` and also use camel case for the sections like `primaryTelephone` vs. `primary-telephone` (as outlined in #1740).

**Comment by Justin-Pickett** [comment]
@Nedie, after all the changes are made and pushed, how soon can we get a report of seeing the users events?

**Comment by nedierecel** [comment]
@Justin-Pickett We can see error events in real-time, but expect about a 4-hour latency to appear in the dashboard and other GA reports.

**Comment by erikphansen** [comment]
FYI: PR was just merged so it'll go out to prod tomorrow.

**Comment by erikphansen** [comment]
@nedierecel or @jonwehausen can validate that GA is getting the new `error-key`s after this goes to prod tomorrow 3ET.

**Comment by nedierecel** [comment]
@erikphansen @Justin-Pickett For your visibility, I am now seeing the `error-key` data populating since the 3PM deploy:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/255a7456-2d01-47b2-866e-627a1ec6d393)

**Comment by erikphansen** [comment]
Cool. And you can follow a user's path after they see a bad address error?

**Comment by Justin-Pickett** [comment]
@Nedie any update on @erikphansen comment above? Id love to look at getting the report to see if users are able to follow the path correctly to complete their updates.

**Comment by nedierecel** [comment]
@Justin-Pickett Certainly!

**Aggregate view of pathing**
The report I wanted to show you is called the Behavior Flow report, which shows more of the pathing. I'm running into a latency issue, so it looks like there is a delay in processing that particular report. 

**More granular view down to non-PII users**
We can use this report as a starting point:

1. Here is a link to the [User Explorer Report](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-legacy-user-id/a50123418w177519031p187673796/_u.date00=20191023&_u.date01=20191024&_.goalOption=3&_.useg=useri7QjhRJgTqiUkfwy6eG7_Q/)

If you click on the `Client ID` and expand the timestamp, it will show you user interactions (in descending order):
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/81e0dd6a-0b97-426b-b364-d48026591d7e)

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/3db308a9-006f-4303-b356-1fde5a5c1968)

In the few I have reviewed, it looks like there are instances where they a) get the error, b) change the address, and then c) get the error again.

**Comment by erikphansen** [comment]
I was afraid that was happening :( I wonder if data is not correctly flowing from vet360's data to EVSS so EVSS:PPIU is not seeing a valid address even after it's been added in vet360. Will bring it up on tomorrow's call

**Comment by nedierecel** [comment]
@Justin-Pickett @erikphansen Documenting this here from our Slack chat. To see the segment, please take these steps:

Step 1:
>If you click on this link, it will share the saved segment of sessions where the logic is Direct Deposit Failure+Gets error key of mailing-address-error`- https://analytics.google.com/analytics/web/template?uid=zvqMTBkGQuCO_CGmI-o16Q

Step 2: Add this to your view in GA using the screenshot as a guide.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/eebf5023-34a6-448e-a5c4-6098ec7f2e64)

3. From here, you can visit the [User Explorer](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-legacy-user-id/a50123418w177519031p187673796/_u.date00=20191023&_u.date01=20191024&_.goalOption=3&_.useg=useri7QjhRJgTqiUkfwy6eG7_Q/) report, then apply the segment by selecting "All Users" and the new segment. 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/33fb70e4-d797-4aa0-b097-08877f16a9ae)

**Comment by Justin-Pickett** [comment]
@nedierecel @erikphansen 

Is this ticket okay to close out? I believe we have gathered the info we needed but want to confirm that is correct w/ @erikphansen.

**Comment by Justin-Pickett** [comment]
@nedierecel okay great. thanks so much for the update.

**Comment by Justin-Pickett** [comment]
@nedierecel , can you generate a event report similar to the one you provided to us before. 

1. Would like to see the numbers from Oct. 28 - Present day of the successes of users able to update their mailing address and DD info. 

2. Would l like to see a report from Oct. 28 - Present of users that successfully updated their mailing address but did not continue to update their DD information. 

Let me know if you have any questions of my request.

**Comment by nedierecel** [comment]
@Justin-Pickett 

1. I updated the Google Sheet for your review before downloading to Excel for the product team. It shows the recent date range in Col. C. I also included a table below showing the occurrences of the `error-key` of mailing address errors. @erikphansen This shows a decline beginning 11/1/2019 for these types of errors. Can you confirm you're seeing similar in Sentry? 

2. Confirming I see this ask - I will update the ticket with this information.

**Comment by Justin-Pickett** [comment]
@nedie and @erikphansen i will be closing this ticket out. I created a new ticket to continue tracking any new insights we receive at this new ticket for Sprint 8 [ LINK ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3203).
