### ISSUE TITLE
Search UI Consistency: Review feedback & create new issues for additional work

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23604]
## User Story

As a designer, I want to identify additional work items that resulted from the design intent review for Search UI consistency.

## Expected Behavior

Review AI, Accessibility, Design feedback from design intent review, determine what additional work items are needed to incorporate recommended changes.

## Acceptance Criteria

- [x] Review AI feedback
- [x] Review Design feedback
- [x] Review Accessibility feedback
- [ ] Note additional work items needed
- [ ] Work with Marci to create new issues in GH

## Description

As a result of the design intent meeting (#22885) for Search UI Consistency #21055 the following feedback was provided. 

Design Intent Feedback Issues:
- Accessibility Feedback - #23387
- Design Feedback - #23458
- IA Feedback- #23538
- [Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22885#issuecomment-822519028) on Design Intent Issue - #22885 
- Ryan Thurlwell Feedback- TBD

This issue summarizes the comments related to Global Search which will be explored/addressed/incorporated by design. 

## Global Search Comments from IA, Design and Accessibility

- [ ] **IA Feedback MUST:** Breadcrumbs are inaccurate in prototypes. Make sure that the desktop breadcrumb shows the complete path including the current page. The mobile breadcrumb should only show a link to the parent page.
    - Global search results desktop: Home > Search results
    - Global search results mobile: < Home
- [x] **IA Feedback MUST:** The H1 for Resources search results page needs to indicate the user is on a new page. The H1 should remain as "Search results" or something similar to indicate they are on a different page and ensure the desktop breadcrumb is not redundant (i.e. Home > Resources and support > Resources and support).
- [x] **IA Feedback CONSIDER:** An option for consistency between H1s on these search tools is to use a similar structure for the H1s on the results pages. Examples:
    - Global search: "Search results for VA.gov" or "VA.gov search results"
- [x] **Accessibility Feedback MUST**: Fix mobile breadcrumbs so that they are all consistent with one another. Find a Form and Resources and Support should have the same type of breadcrumb as search e.g. "Home > Find a Form"
- [ ] **Accessibility Feedback MUST:** [developers] make the bolded "Search resources and support articles or all of VA.gov" a <legend> within a <fieldset> that includes the radio options on the resources page
- [ ] **Accessibility Feedback CONSIDER:** Removing "Powered by Search.gov" and shifting the pagination to the left so it is more easily discoverable with magnification tools. Veterans with low vision who may use external magnification tools not provided within the browser may only see a certain width of the page at any given time. The pagination may be less discoverable than "Powered by Search.gov" (which may give no value to Veterans) if it is flushed right. [Issue #23647](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23647)
- [x] **IA Feedback CONSIDER:** Somewhat unrelated, but related, to this work...the va.gov/search URL is redirecting to the home page. I don't recall the reason why this is, but this redirect should be removed. It would not be a high traffic page, but user's should be able to access a default display state of search. This change should also impact the breadcrumb by adding in a default state to the path: Home > Search > Search results. [Issue #23648](om/department-of-veterans-affairs/va.gov-team/issues/23648)
- [ ] **IA Feedback MUST:** Some of the links within the right rail of the global search are there because of stakeholder requests (i.e. the BVA lookup). Appropriate conversations/investigation must take place to before these links are considered for removal. That said, I have no issues with exploring different placement/design ideas for these links in support of deprecating the right rail. :-) [Issue #20217](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20217)

- [ ] **Comments regarding Inconsistent styles on VA.gov:** 
- Header links on benefits pages are not currently underlined. Josh has recommended that links should be underlined. Is there a sitewide plan to add underlined links throughout the site so it will be more consistent? 
**Josh's recommendation is correct. We are now striving to be consistent with underlining all links for accessibility reasons. We updated all link text styles in the sketch library to be underlined. There is currently no sitewide plan to underline all links.**

- Is this the correct style for body copy: size: 16px, color: #323A45 (gray-dark)?
**Yes, that is the current default body text style in the sketch library**

- [ ] Comments regarding Inconsistent width for content area:

- Any insights on the correct content width? On Sketch desktop templates: it is 648px for one column pages and 732px on two column pages with a left nav. On VA.gov, it is 700px.
**I would follow what's on VA.gov, I'll update the sketch desktop templates**

**Comment by callen2563** [comment]
@MarciMcGuireGCIO I have reviewed all 3 feedback tickets and have added comments to those tickets where needed. Here are the latest mock ups for FAF and R+S: 

[Mobile mockups ](https://vsateams.invisionapp.com/overview/UI-Search-Consistency---mobile-cknr2uisl2tl001ymf60mfq36/screens?sortBy=1&sortOrder=1&viewLayout=2)

[Desktop mockups](https://vsateams.invisionapp.com/overview/UI-Search-Consistency---desktop-cknr2uisl2tl101ymmt48cx3z/screens?sortBy=1&sortOrder=1&viewLayout=2)

**Comment by mgleo** [comment]
+ Global search has been updated on Invision as well.

**Comment by callen2563** [comment]
@MarciMcGuireGCIO Here are the latest mock ups for FAF and R+S after Monday's meeting incorporating feedback:

[Mobile updates](https://vsateams.invisionapp.com/console/share/8Y10IE2JN2J4)

[Desktop updates](https://vsateams.invisionapp.com/console/share/SD10IE31CENR)

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @callen2563 !

**Comment by mgleo** [comment]
Gray background was added around the global search bar along with the text "Enter a keyword". Also made updates to the breadcrumbs. A note about global search, there are a limited amount of 'stop words' that are excluded from search queries, meaning entering additional sentence structure words will reduce result relevancy. (Ex: "prescriptions" will produce better results than "how to get prescriptions") For this reason, I'm not including "phrases or questions" as seen on R&S. Also, I could go either way but I don't see the gray background and text as adding much value to pages with just one input field as it also pushes the search results further down the page.

**Comment by MarciMcGuireGCIO** [comment]
Noting that the ticket for documenting the design pattern is here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/459
