### ISSUE TITLE
Update current calendar file details

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23606]
## Description
As a user, I would like appointment details in my personal calendar so that I can make appropriate plans to attend.

---
## Tasks
- [ ] VA in person

- [ ] VA phone

- [ ] Community Care

- [ ] VVC ATLAS

- [ ] VVC home

- [ ] VVC VA device

- [ ] VVC VA location

- [ ] Documentation

## Acceptance Criteria

- [ ] If confirmed upcoming appointment, Then show Add to Calendar link

- [ ] If pending (requested) appointment, Then do **not** show Add to Calendar link
- [ ] If canceled appointment, Then do **not** show Add to Calendar link

- [ ] Given desktop, When user clicks Add to Calendar, Then download calendar ICS file

- [ ] Give tablet/mobile, When user taps Add to Calendar, Then open new event in default device calendar

- [ ] Given in-person VA appointment, When user opens ICS file, Then content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#va-in-person)
- [ ] Given VA appointment over the phone, When user opens ICS file, Then content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#va-phone) 
- [ ] Given CC appointment, When user opens ICS file, Then content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#community-care) 
- [ ] Given VVC ATLAS appointment, When user opens ICS file, Then content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#va-video-connect-at-atlas) 
- [ ] Given VVC appointment at home, When user opens ICS file, Then content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#va-video-connect-at-home) 
- [ ] Given VVC appointment on a VA device, When user opens ICS file, Then content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#va-video-connect-on-va-device) 
- [ ] Given VVC appointment at a VA location, When user opens ICS file, Then content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#va-video-connect-at-va-location) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is created with screenshots

**Comment by aarathi-poldass** [comment]
Testing completed on 06/14 with Niko Troia(Veteran) and Shawn Avila(Staff) from Phoenix VAMC. 

Please see the script attached for the scenarios tested: 
[23606_23607_ Acceptance Criteria_Save Appointment To Personal Calendar.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6771401/23606_23607_.Acceptance.Criteria_Save.Appointment.To.Personal.Calendar.xlsx)
