### ISSUE TITLE
Create Combat-Related Special Compensation (CRSC) R&S article in Drupal

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#23625]
## Issue
Per ticket #21414, a Combat-Related Special Compensation article needs to be created in Drupal based on IRIS questions approved for migration by SME Paul Shute.

**Combat-Related Special Compensation (CRSC):** http://preview-prod.vfs.va.gov/preview?nodeId=18658

---
## Tasks
- [x] Create article in Drupal (Selina)
- [x] Copyedit article (Randi)
- [x] Review article and send to stakeholders for final approval (Beth)

## Acceptance Criteria
- [ ] _Page is published and live_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. 

I did make some changes to the article:

- Ordered military branches alphabetically
- For the forms mentioned in the second set of accordions, I linked directly to the forms instead of the web pages they're on.
- Changed the link for the CTA button and "Download DD Form 2860 (PDF)" to https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd2860.pdf per [Beth's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21414#issuecomment-822157802)

**Comment by RLHecht** [comment]
This has been copyedited. One question is for the two forms that we link to (CRSC Form 12e and NCBP 1850-7 it takes you to a separate site that you then have to find the form to click on and download. Do we need to explain that or is there a place where we can link straight to the PDF of the form? @lwalsh617 @bethpotts

**Comment by RLHecht** [comment]
Closing this ticket and creating new one to track publishing in Drupal.
