### ISSUE TITLE
Express Care-remove from appointments list

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23639]
## Description
Express Care scheduling was turned off in VAOS 4/22/21. VA stakeholders and Product Owner would like to remove the EC appointments from the appointments list.

---

## Tasks

- [ ] Live/current appointment list

- [ ] Homepage Refresh appointment list

## Acceptance Criteria

- [ ] Express Care appointments are not viewable in VAOS
