### ISSUE TITLE
Consider: Relocation of "Powered by Search.gov" 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#23647]
## Description

During the design intent review for "UI Search Consistency" a recommendation to examine the location of the "Powered by Search.gov" was made. This will require some exploration to ensure we understand the implications of moving or removing that notification. 

## Background/Context
- Global Search Design Intent Feedback Summary #23650
- Accessibility Feedback - #23387

> CONSIDER: Removing "Powered by Search.gov" and shifting the pagination to the left so it is more easily discoverable with magnification tools. Veterans with low vision who may use external magnification tools not provided within the browser may only see a certain width of the page at any given time. The pagination may be less discoverable than "Powered by Search.gov" (which may give no value to Veterans) if it is flushed right.

## Tasks

- [ ] Review Search.gov trademark requirements
- [ ] Design Exploration to remove/relocate "Powered by Search.gov" 

## Definition of Done

- [ ] A decision has been made regarding   "Powered by Search.gov" notification going forward.

**Comment by mgleo** [comment]
[Search.gov TOS](https://search.gov/tos.html): _"Customers using the Search Results API with Bing results must display the Powered by Bing [PDF] logo on ‘web’ and ‘image’ search results pages for attribution of these results. Customers using any of Search.gov indexes (‘i14y’, ‘docs’, ‘news’, and ‘videonews’) must display “Powered by Search.gov” (using plain text or our logo for Search.gov) for attribution instead of the Bing logo."_

**Comment by denisecoveyduc** [comment]
This will be completed as part of the UI Consistency work in GH#24988
