### ISSUE TITLE
Document Known Issues

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#23656]
## Issue Description
As a follow-on task to our initial meeting with the Contact Center, we need to document all known support issues
---
## Tasks
- [ ] Create document detailing known support issues

## Acceptance Criteria
- [ ] Document complete and posted to GitHub
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
