### ISSUE TITLE
Global Search - Design Intent Feedback Summary

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#23650]
## Description

As a result of the design intent meeting (#22885) for Search UI Consistency #21055 the following feedback was provided. 

Design Intent Feedback Issues:
- Accessibility Feedback - #23387
- Design Feedback - #23458
- IA Feedback- #23538
- [Comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22885#issuecomment-822519028) on Design Intent Issue - #22885 
- Ryan Thurlwell Feedback- TBD

This issue summarizes the comments related to Global Search which will be explored/addressed/incorporated by design. 

## Global Search Comments from IA, Design and Accessibility

- [x] **IA Feedback MUST:** Breadcrumbs are inaccurate in prototypes. Make sure that the desktop breadcrumb shows the complete path including the current page. The mobile breadcrumb should only show a link to the parent page.
    - Global search results desktop: Home > Search results
    - Global search results mobile: < Home
- [x] **IA Feedback MUST:** The H1 for Resources search results page needs to indicate the user is on a new page. The H1 should remain as "Search results" or something similar to indicate they are on a different page and ensure the desktop breadcrumb is not redundant (i.e. Home > Resources and support > Resources and support).
- [x] **IA Feedback CONSIDER:** An option for consistency between H1s on these search tools is to use a similar structure for the H1s on the results pages. Examples:
    - Global search: "Search results for VA.gov" or "VA.gov search results"
- [x] **Accessibility Feedback MUST**: Fix mobile breadcrumbs so that they are all consistent with one another. Find a Form and Resources and Support should have the same type of breadcrumb as search e.g. "Home > Find a Form"
- [x] **Accessibility Feedback MUST:** [developers] make the bolded "Search resources and support articles or all of VA.gov" a <legend> within a <fieldset> that includes the radio options on the resources page
- [x] **Accessibility Feedback CONSIDER:** Removing "Powered by Search.gov" and shifting the pagination to the left so it is more easily discoverable with magnification tools. Veterans with low vision who may use external magnification tools not provided within the browser may only see a certain width of the page at any given time. The pagination may be less discoverable than "Powered by Search.gov" (which may give no value to Veterans) if it is flushed right. [Issue #23647](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23647)
- [x] **IA Feedback CONSIDER:** Somewhat unrelated, but related, to this work...the va.gov/search URL is redirecting to the home page. I don't recall the reason why this is, but this redirect should be removed. It would not be a high traffic page, but user's should be able to access a default display state of search. This change should also impact the breadcrumb by adding in a default state to the path: Home > Search > Search results. [Issue #23648](om/department-of-veterans-affairs/va.gov-team/issues/23648)
- [x] **IA Feedback MUST:** Some of the links within the right rail of the global search are there because of stakeholder requests (i.e. the BVA lookup). Appropriate conversations/investigation must take place to before these links are considered for removal. That said, I have no issues with exploring different placement/design ideas for these links in support of deprecating the right rail. :-) [Issue #20217](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20217)

- [x] **Comments regarding Inconsistent styles on VA.gov:** 
- Header links on benefits pages are not currently underlined. Josh has recommended that links should be underlined. Is there a sitewide plan to add underlined links throughout the site so it will be more consistent? 
**Josh's recommendation is correct. We are now striving to be consistent with underlining all links for accessibility reasons. We updated all link text styles in the sketch library to be underlined. There is currently no sitewide plan to underline all links.**

- Is this the correct style for body copy: size: 16px, color: #323A45 (gray-dark)?
**Yes, that is the current default body text style in the sketch library**

- [x] Comments regarding Inconsistent width for content area:

- Any insights on the correct content width? On Sketch desktop templates: it is 648px for one column pages and 732px on two column pages with a left nav. On VA.gov, it is 700px.
**I would follow what's on VA.gov, I'll update the sketch desktop templates**

**Verbal discussions also lead to the creation of the following efforts:**

- [x] Mock Up Search Bar Iterations (Gray box and prompt text) #24270

**Comment by MarciMcGuireGCIO** [comment]
@denisecoveyduc - Crystabel also left some comments in the original design intent ticket:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/22885#issuecomment-822519028

**Comment by denisecoveyduc** [comment]
@MarciMcGuireGCIO Thank you! I added them above as well so all Global Search Comments are summarized in one place.

**Comment by MarciMcGuireGCIO** [comment]
@denisecoveyduc I am going to steal your consolidated notes since you've compiled them so nicely.

**Comment by denisecoveyduc** [comment]
@mgleo has incorporated the design intent feedback into the final designs.
