### ISSUE TITLE
Update accordion data layer 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23662]
## Issue Description
The analytics team found some issues with capturing DL variables for accordions during testing using this [review instance](http://53ae53620eedaf9217582ef75b4a4ae0.review.vetsgov-internal/erie-health-care/health-services/) to perform testing. Feedback was provided in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18822#issuecomment-823200118) on #18822. 

---
## Tasks
- [ ] Add DL variables for single and double label accordions as documented below 
      - if an accordion has two labels, populate both values 
      - if an accordion has only one label, populate this value and make accordion-child-label `undefined`'
      - populate values with the label of the section where the accordion is present

| Description/Screenshot of Interaction | Data Layer Screenshot | Test Status | Test Notes 
| -- | -- | -- | -- |
Click to EXPAND "Advice nurse" accordion -- _single label accordion_ | ![image](https://user-images.githubusercontent.com/48527022/115386289-32462400-a1a7-11eb-8d6d-37fbbcb302fc.png) | ⚠️ **DOES NOT PASS** | • @mpelzsherman with this accordion only having 1 label, we should only populate the `'accordion-parent-label'` with `'Advice nurse'` and `'accordion-child-label'` should be `undefined`
Click to COLLAPSE "Advice nurse" accordion -- _single label accordion_ | ![image](https://user-images.githubusercontent.com/48527022/115386722-c2846900-a1a7-11eb-92ba-6ddb30218e92.png) | ⚠️ **DOES NOT PASS** | • Same change needed here for `'accordion-parent-label'` and `'accordion-child-label'`
Click to EXPAND "Primary care" <br> "Family and internal medicine" accordion - _double label accordion)_ | ![image](https://user-images.githubusercontent.com/48527022/115387658-f744f000-a1a8-11eb-961c-35847a8cfd21.png) | ⚠️ **DOES NOT PASS** | • @mpelzsherman looks like we did not capture the relevant data layer variables here -- `'accordion-parent-label'`, `'accordion-child-label'`, `'accordion-section-label'`
Click to COLLAPSE "Primary care" <br> "Family and internal medicine" accordion - _double label accordion)_ | ![image](https://user-images.githubusercontent.com/48527022/115388041-6c182a00-a1a9-11eb-8f0f-6b0853620d08.png) | ⚠️ **DOES NOT PASS** |  • Same change needed here for `'accordion-parent-label'`, `'accordion-child-label'`, `'accordion-section-label'`

## Acceptance Criteria
- [ ] Accordions are populated with three values:  `'accordion-parent-label',  `'accordion-child-label' and `'accordion-section-label'`
- [ ] `'accordion-child-label'` is populated with `undefined` when no label is present

**Comment by mpelzsherman** [comment]
#21555 did not specify which pages (or templates) needed this change. Only src/site/layouts/health_care_local_facility.drupal.liquid and src/site/facilities/facility_health_service.drupal.liquid were modified to support the new datalayer attributes (`data-label` and `data-childlabel`). These are used for the VAMC locations pages.

The following templates also have accordions, and will need similar changes to support these new datalayer requirements:

./src/site/navigation/sidebar_nav.drupal.liquid
./src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid
./src/site/layouts/health_care_local_facility.drupal.liquid
./src/site/layouts/campaign_landing_page.drupal.liquid
./src/site/layouts/faq_multiple_q_a.drupal.liquid
./src/site/paragraphs/collapsible_panel.drupal.liquid
./src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
./src/site/facilities/facility_health_service.drupal.liquid
./src/site/facilities/health_service.drupal.liquid

It's very difficult to tell which pages are used by which pages in our system, so I'll just add the new attributes to every template owned by the facilities team. Other teams such as public websites will need to make similar changes to the templates they own.

**Comment by mmiddaugh** [comment]
The intention for this work is to record events on the health service accordions specifically - we need to target those relevant templates @mpelzsherman

**Comment by mmiddaugh** [comment]
Moved this back to Validate for QA visibility

**Comment by mpelzsherman** [comment]
This is currently on staging (e.g. https://staging.va.gov/pittsburgh-health-care/health-services/), but has not been released to production yet. Should go out this afternoon.

**Comment by mpelzsherman** [comment]
Validated on production:

![Health_services___Veterans_Affairs](https://user-images.githubusercontent.com/80267/116175764-ef240d80-a6de-11eb-8e0c-bd9a5558bfee.png)

**Comment by mmiddaugh** [comment]
Copying [this feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18822#issuecomment-828448439) from QA Retest of Accordions  

| Description of Interaction | Data Layer Screenshot | Test Status | Test Notes
| -- | -- | -- | -- |
Click on accordion "Pain management" with no subheading | ![image](https://user-images.githubusercontent.com/48527022/116410024-61414300-a802-11eb-9785-398a7bb56348.png) | ⚠️ **DOES NOT PASS** | @mpelzsherman -- In order to not risk metadata "bleedover" for when an accordion with 2 labels is clicked first, it's imperative we push `undefined` for `accordion-child-label` when a single accordion label is clicked

@jon confirming that `undefined` is a literal value to be pushed for accordions with single labels. 
@mpelzsherman

**Comment by mpelzsherman** [comment]
Moving to Blocked pending a response re: whether we need to send "undefined" as a string or just leave the `accordion-child-label` value empty when there is no child label.

**Comment by mpelzsherman** [comment]
From @jonwehausen via [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1620782681408300?thread_ts=1620398804.320600&cid=C0FQSS30V):

> When there is no accordion-child-label please pass in undefined (not as a string).

**Comment by mpelzsherman** [comment]
Tested in production, and it looks good to me. Can we close please, @mmiddaugh ?

![VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr](https://user-images.githubusercontent.com/80267/118707710-d80da280-b7e8-11eb-8a9e-46193cea7243.png)

![VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr](https://user-images.githubusercontent.com/80267/118707800-f4a9da80-b7e8-11eb-9b5f-05fc61fae04d.png)
