### ISSUE TITLE
[Design] Profile - Improve UX for "remove" [contact information] button

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23665]
## Background
As identified in #19562 and as discussed in the [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22592#issuecomment-822782218) of #22592, we need a better solution for the `remove` button, which currently looks like a link.

![remove-button](https://user-images.githubusercontent.com/14154792/114609901-510b5e80-9c6d-11eb-9c77-b43f6dc03673.png
)

## Tasks

- [x] Mock-up solutions
- [x] review with team
- [x] document solution for FE (including updates to notification settings documentation if needed)

**Comment by andaleliz** [comment]
@Samara-Strauss, I'm not sure we can resolve this button issue without designing new button patterns.  I've explored the options I can think of with the design system buttons (screenshots below), and I don't think either of them set the appropriate hierarchy we need for these buttons.  
- replacing the link style button with the secondary button style
- moving the remove button next to the edit button (this is a pattern I've seen elsewhere, an `edit | delete` combo). I think this could only work if we "upgrade" the edit buttons to the primary button style, which I still don't is a great solution. Those buttons are just so fat. I also tried stacking them which is even worse, IMO.

![image](https://user-images.githubusercontent.com/55992116/117990731-6d052d00-b30b-11eb-967c-8f22a7e9477b.png)
![image](https://user-images.githubusercontent.com/55992116/117990756-72fb0e00-b30b-11eb-8709-b87c99d10c56.png)
![image](https://user-images.githubusercontent.com/55992116/117991116-c2413e80-b30b-11eb-8781-46a7c2607ee8.png)

You previously said you didn't think it was up to our team to design new buttons and that wasn't a good use of our time. Do you still feel that way, seeing these options? If so, are there any other options coming to mind that I haven't thought of? I haven't spent a TON of time on this yet, but wanted to check w/ you before you go on PTO tomorrow and Friday so I can work on this accordingly.

**Comment by Samara-Strauss** [comment]
I agree that neither of these options work. The first and third put too much emphasis on removing information, which we don't want, and also could lead to people erroneously clicking the "Remove" button. The second one doesn't have clear hierarchy. I know you already know all of this, but just documenting my own thoughts so they're clear.

I don't have ideas on alternative solutions at the moment, but I also haven't really thought about this problem. Have you brought this to the design team or design system council? Are there ideas we're missing?

If not, I personally don't think it's our responsibility to design a new button style, but it also feels like we're not really being left with a choice. My question for you is — do you feel that you have the skills to design a new button style? Or is this something you want to go to the design system council about? Not that I work in a design capacity anymore, but if I did, I know I would not have felt comfortable with being asked to design a new button style. Whether we take this on really depends on your comfort level.

**Comment by andaleliz** [comment]
>Have you brought this to the design team or design system council? Are there ideas we're missing?

I have discussed with a couple of other VSA other designers (who did not see more options than what I've proposed), but not the whole team. We have our design weekly today so I'll bring it up there and see what folks have to say.

Regarding the design system council, they have a related [open ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/406), and are aware that a new button style is needed for profile.  They de-prioritized this issue, last I heard.  I remember Kevin Hoffman introducing the design system council and making the analogy that their role is similar to what librarians are to a library, and that they're not authors writing the books on the shelves.  The combination of those two things makes me think they wouldn't be open to providing a solution, but it's a good idea to check that assumption.

>Do you feel that you have the skills to design a new button style?... Whether we take this on really depends on your comfort level.

Admittedly, I'm not the strongest visual designer, but I think my skills could get us to point that is better than the options we have with the design system.  I'm willing to try, if it turns out that we have to go this route.  The risk in not doing this is introducing confusion/cognitive load issues since there is no clear visual hierarchy to those buttons - which is probably an equal a11y violation to the one we're trying to resolve. 

Let me bring this up in our weekly today and I'll share an update here before you go on PTO.

**Comment by Samara-Strauss** [comment]
Ugh, Liz, I feel like we are being left between a rock and a hard place. You should NOT be having to do visual design on buttons if that's not in your wheelhouse, and you're right that there's potential for that to cause additional a11y issues.

Let me know what comes up in the weekly meeting today, but we might need to regroup further on this. I don't feel comfortable that we're just being forced into this solution without the proper tools to actually fix it, and I'm not willing to have you sink a bunch of time into this when there is project work that needs to be moved along. I know we can't ignore the issue, but we also can't drop everything else for it.

**Comment by andaleliz** [comment]
@ajakabcin, @Samara-Strauss and I had a meeting this afternoon and discussed the complexities of providing a solution for this.  We're going to put this in the backlog and not address for now since this is not an easy fix and we have too much project work in progress that needs to keep moving forward. 

The solutions available in the design system introduce different problems of hierarchy and cognition. Options other than simply updating the button style (e.g. moving the placement, replacing w/ a checkbox or radio input) increase the scope quite a lot when you consider the research + design efforts needed to execute.

Samara is going to submit a request to the analytics team to implement event tracking on the remove link  (fwiw Samara, I am able to see the profile events outside of your dashboard link, so we'll be able to see them even if the dashboard isn't set up) to see if people are even using it.  

Taking this out of the current sprint + increasing estimate accordingly.

**Comment by Samara-Strauss** [comment]
So it turns out that we had [stats on deleting contact information](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Profile%20-%20Delete/) all this time! This is this week's report, thought you'll see a similar trend if you scroll back in time — far and away, people are deleting old work phone numbers, which makes a ton of sense. Not only are people not working in offices during the pandemic, but this trend was apparent even before the pandemic. This is also a huge percentage based on [how many people are updating their work phone numbers](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/3Z1vT6SlQqevdav1s72QwA/a50123418w177519031p176188361/_u.date00=20210428&_u.date01=20210505/). About 1/3 of work phone number transactions are deleting this field.

That being said, deletion of other contact information is less common, especially as a percentage of overall updates for any given field. So, I guess that's all to say we can consider removing the "delete" option for some fields if we want to, but I don't think we should remove it for work phone numbers. And if we have this action available for even one field, this accessibility issue will still persist.

Liz/Erik, any thoughts on these stats or paths forward?

**Comment by andaleliz** [comment]
I think we should keep the remove function available for users - off the top of my head I can think of a realistic and valid use case for home address (homelessness), home number (removing landlines), fax machine (obsolete), and work number (described above).  Personally, it's hard for me to wrap my head around someone abandoning (and not simply _changing_) a mobile number or email address, but I can certainly understand that someone could decide they just don't want the VA to have their information anymore. We should give people control of their information.

That being said, I think my previous comment still applies.  
>The solutions available in the design system introduce different problems of hierarchy and cognition. Options other than simply updating the button style (e.g. moving the placement, replacing w/ a checkbox or radio input) increase the scope quite a lot when you consider the research + design efforts needed to execute.

We either need to carve out time for this on our team, or wait for the design system to provide a solution.  Although I'm not a visual designer, I do think I can get us to starting point with a button design that I could then work with a visual designer to refine.  

I also wonder if perhaps @rtwell has lightweight button designs in his pocket that he's already worked on and maybe just need to be tested.  He often times has things in the works that I don't have visibility too. I'll check with him just in case.

**Comment by Samara-Strauss** [comment]
> We either need to carve out time for this on our team, or wait for the design system to provide a solution. Although I'm not a visual designer, I do think I can get us to starting point with a button design that I could then work with a visual designer to refine.

As we've talked about, whether you take on this task is up to you. If you decide you want to take it on, I'd prioritize it for 2 - 3 sprints from now when you'll likely be past the largest portion of your work with preferred facilities and notification preferences.

**Comment by Samara-Strauss** [comment]
> I'm not convinced this is a worthy-trade off: fixing the button issue in exchange for less specificity + an uglier UI. But, documenting the suggestion and throwing it out there in case anyone is, and wants to resolve the a11y issue pronto.

Agreed. This is is not a good solution. Uglier UI + lack of hierarchy = worse experience

> Ryan doesn't have anything in the works, but did made an interesting suggestion I hadn't considered; to update the edit buttons to a dropdown button that triggers a menu w/ edit and remove options. Similar to your personalized menu in global nav once you're logged in. However, since our menu would contain buttons and not links, we would still have to go through the 6 step process of getting adoption into the design system before we could implement it. Not a quick fix.

This is an interesting solution! Definitely something worth exploring, but as you mentioned, not a quick fix. This is something you should have time to pick up towards the end of June if my estimates are accurate, so don't feel you need to poke around on this until then, *unless* you want to de-prioritize the auth experience comparative analysis in favor of this work. Let me know. The choice is up to you.

**Comment by andaleliz** [comment]
Oooph.  So many rocks and hard places!! 😆  Honestly, I think Veterans have more to gain from our team fixing this problem than doing research on authenticated experiences.  I can add a task at the end of the notification preferences research to test the new pattern specifically so we don't have to do a separate study just for this.

Pivoting! I'll adjust my research tickets accordingly.

**Comment by Samara-Strauss** [comment]
Sounds good! For long term planning, let me know how far back you want to push the general research (a sprint, two, more).

@ajakabcin — Liz has decided to move this work into this sprint and push back her research effort. Can you adjust things accordingly?

**Comment by andaleliz** [comment]
I think we should target the research to start in sprint 50.

Also, FWIW it's likely this will take 2 sprints, due to review/approvals/validation, etc.

**Comment by andaleliz** [comment]
@Samara-Strauss, exploring some quick (from a visual design perspective) fixes and interested in your thoughts before I continue investing time on this.  

**Option 1: minimal secondary button style, expose remove functionality**

![image](https://user-images.githubusercontent.com/55992116/119168034-7dfe1e80-ba2e-11eb-834a-6b2b7c7b2db4.png)

What I'm proposing here is essentially the same button we have now, with un-bolded font styling and less padding, so I don't think VSP would give much push back.  We can use the same pattern for hover and active we have as well.   I know you previously said you don't want to encourage people to remove contact information, but I have a few reasons I think this is a better UX than nesting the functionality inside the edit view:
1.  This follows our va.gov design principles of focusing users on one task at a time. Removing is a different task from deleting
2.  People who want to complete this task won't have to guess as to whether or not they can do it by clicking edit
3. I don't think seeing this button is going to inspire someone to do so just by virtue of seeing this button.  People either have a need to do this, or they don't.

If we go this route, I'd propose the remove functionality trigger a modal, instead of the alert we currently have.

**Option 2: Keep current styling of remove link, and make it a real link**
Screenshot shows what people would see after clicking `Remove mobile phone number`:
<img src="https://user-images.githubusercontent.com/14154792/114609901-510b5e80-9c6d-11eb-9c77-b43f6dc03673.png" width="75%"

![image](https://user-images.githubusercontent.com/55992116/119169392-f31e2380-ba2f-11eb-96cd-8278d07f3811.png)

-This would allow us to step in the direction of the va.gov guidance to focus users on one step at a time by moving the remove process out of the edit flow. 
- We'd preserve the current UX of nesting remove within the edit function.  
- It makes it super clear what the consequences of removing contact information would be

I'm not sure what the URL would look like - that'd be something to flesh out with Mikki.

**Option 3: explore dropdown menu idea**
I played around a little bit with that, and I believe this is a pretty heavy visual design lift. Our drop down menu would have buttons inside the menu (not links) with the way profile is currently set up, so we'd have to design accessible but super lightweight buttons (not even a border would work inside the menu, and Josh will not approve a plain text element as a button) in addition to the dropdown pattern itself.  There are also multiple layers of focus management to deal with.  It also feels clunky given that the Mailing Address section would need a different kind of button since the only action is `Edit`, as well as any section where the user doesn't have any information at all.

**Comment by Samara-Strauss** [comment]
First, thank you so much for thinking through this. This problem is a nightmare without a good solution, and you're still trying to make the best of it. I really appreciate that.

There are pros and cons to both options, but if I had to choose, I'd go with Option 1 with the following feedback: The Edit button should have more emphasis than the remove button. Can we keep it bolded? This is the primary action, and right now, the Edit and Remove buttons are not only equal weight, but the Remove button is larger. It's not that I think people are stupid and don't get the difference between Edit and Remove, it's that people don't read, and I am afraid the larger target will get more clicks. Of course, people can cancel if they click the wrong action, but I could see this being annoying. Edit needs to clearly be the primary action.

Re: Option 2, I love that the visual hierarchy initially doesn't change, but it feels SO heavy handed to take people to a whole new page to remove an address/phone number/email address. It also feels like an old-fashioned, clunkier flow. When I think of deleting something like this, I think I should be able to do it smoothly and in-line without being removed from the experience. I get the guidelines of "one action per page", which totally makes sense with forms or more complex flows, but this particular case feels like too broad/strict an application of that rule.

**Comment by andaleliz** [comment]
>First, thank you so much for thinking through this. This problem is a nightmare without a good solution, and you're still trying to make the best of it. I really appreciate that.

My pleasure. It's actually gotten to be fun for me to solve! We're working toward something that will ultimately be a better and more accessible UX 🎉 

>Re: Option 2 ...

I see what you're saying, all good points. Let's toss that idea.

> Edit needs to clearly be the primary action.

Yes! The remove button being physically bigger is not ideal. I played around with a few options and landed on adding an icon - do you think that is enough to clarify that it's the primary action?

![image](https://user-images.githubusercontent.com/55992116/119187253-1c967980-ba47-11eb-8621-f1dbe06c3a57.png)

Bolding the label alone doesn't feel like it places enough emphasis, and using the existing primary/secondary combo feels too heavy.

![image](https://user-images.githubusercontent.com/55992116/119187535-7ac35c80-ba47-11eb-96d4-bbc2950e1956.png)

I also tried bold w/ an icon, but that doesn't seem right either. Something about the pairing of bold and regular text on an otherwise similar button feels awkward.

![image](https://user-images.githubusercontent.com/55992116/119187580-86af1e80-ba47-11eb-9bed-e1c6aec23266.png)

All of these solutions are in line with what we're currently doing on VA.gov; just reducing the padding + softening the font style. Hopefully they'll be easily approved by VSP.

**Comment by Samara-Strauss** [comment]
Liz, I should have thought of this earlier before you did all this exploration. Sorry for my slow brain.

While I like the button style with the icon, and I do agree that the existing primary/secondary button treatment feels heavy, my hypothesis is that the design feedback we'd get if we showed a new button style would be "why didn't you just use the primary and secondary buttons we have?" We got A LOT of feedback like this when we tried to initially introduce some new styles on My VA, so I think if we're designing a new button style, it should be because we absolutely need it. If we decided to keep the "Remove" action in the form itself, that would be a place where we'd *need* a new button style because we'd already be using the primary and secondary buttons styles and would be in need of a third. But, if we have just the two buttons side-by-side in the read-only mode, a new style becomes optional and not necessary.

So, I think the best option is to go with the primary and secondary buttons in the read-only mode even though we all agree it's not very pretty. I believe you've already brought this to the design team, and I think the consensus was that while it's not beautiful, it's not so bad that we can't launch it on the website.

Thoughts?

**Comment by andaleliz** [comment]
No problem @Samara-Strauss! Good to have that background info.

I did bring this to the design team. They preferred the option on the right, which doesn't _exactly_ solve the hierarchy issue.  We can test it though, and see how it performs.
![image](https://user-images.githubusercontent.com/55992116/119192432-27a0d800-ba4e-11eb-8658-bfd7005c6cee.png)

There's an icon variation in our Sketch library, though since it's not documented on design.va.gov, I'm not sure we can use it freely. Currently [learning more in Slack](https://dsva.slack.com/archives/C0NGDDXME/p1621628112021900). I do think it improves the hierarchy:
![image](https://user-images.githubusercontent.com/55992116/119194955-d72b7980-ba51-11eb-993e-b90787d09ca6.png)

**Comment by Samara-Strauss** [comment]
> I did bring this to the design team. They preferred the option on the right, which doesn't exactly solve the hierarchy issue. We can test it though, and see how it performs.

Noted, and very interesting. Were people not concerned with the hierarchy? Was the preference purely visual? Mostly just curious what the rationale was behind the team consensus.

> There's an icon variation in our Sketch library, though since it's not documented on design.va.gov, I'm not sure we can use it freely. Currently learning more in Slack. I do think it improves the hierarchy:

Sounds good to me! Keep us posted!

**Comment by andaleliz** [comment]
>Noted, and very interesting. Were people not concerned with the hierarchy? Was the preference purely visual? Mostly just curious what the rationale was behind the team consensus.

It was visual - people just felt the primary blue buttons were so heavy, it was all they could focus on.

**Comment by andaleliz** [comment]
@Samara-Strauss the icon button in the design system library is actually **not** approved for use w/out a larger approval process -it's an old symbol that needs to be removed.  So, the only design-system approved options we have are these
<img src="https://user-images.githubusercontent.com/55992116/119192432-27a0d800-ba4e-11eb-8658-bfd7005c6cee.png" />

Between these two, I personally prefer the option without the primary button - they just feel so overpowering. But I'd be delighted to test either one and see how they perform.

How about we bring these options, as well as the smaller buttons, to our mid point review w/ the collab cycle and see what feedback we get.  Maybe they'll see how giant the buttons are in this context and understand the need for a lighter weight style, even though they're similar to what we have now.  Or, perhaps those who are stronger visual designers will have a better idea than I can come up with on my own.

**Comment by rtwell** [comment]
I strongly recommend testing with out-of-the-box design system components/patterns and validate with Veteran data that they are not meeting user needs. For example, Liz' option 2 is a relatively straight forward UX might feel clunky, but also might test well.

**Comment by andaleliz** [comment]
@rtwell that makes sense. We can test one of those screenshots above in our notification preferences study, and then IF that doesn't test well, spend more time on design efforts solving this problem.

**Comment by Samara-Strauss** [comment]
> How about we bring these options, as well as the smaller buttons, to our mid point review w/ the collab cycle for notification preferences and see what feedback we get. Part of what we are testing with the notification flow will be to see if people understand how to update their contact information when they're missing email or mobile number, so we will naturally be taking them to personal and contact information anyway. It works out really nicely for testing this too.

> We can test one of those screenshots above in our notification preferences study, and then IF that doesn't test well, spend more time on design efforts solving this problem.

Both of these sounds good to me. If I had to give a preference, I actually prefer the first design with a clear primary and secondary button, *but* I don't feel this so strongly that I'm willing to go to bat for that design, nor do I have a great UX rationale to go with that design beyond it bringing more emphasis to the primary action (edit). If your designer instincts tell you the second option is better, don't let my opinion override that. If we want to test with the second design, then that's fine by me.

Question I should have asked a while ago — why is the copy "remove" instead of "delete"?

**Comment by andaleliz** [comment]
>If your designer instincts tell you the second option is better, don't let my opinion override that. Let's hear what people say in the midpoint review, and otherwise use veteran data to guide our decisions.

That is what my designer instincts tell me, but open to feedback in the review. 

> Question I should have asked a while ago — why is the copy "remove" instead of "delete"

That's a great question! I wondered the same thing but carried it over from the current language inside the edit function. I also noticed when looking at other sites that "remove" is more common than "delete".  Worth a quick post in #va-sitewide-content though to double check that we don't have a pattern for this already.

**Comment by Samara-Strauss** [comment]
> Worth a quick post in #va-sitewide-content though to double check that we don't have a pattern for this already.

Let me know what you hear. I personally think "delete" is clearer, but given that that is also an unproven opinion, I'd be curious if there is more guidance available on this.

**Comment by andaleliz** [comment]
@Samara-Strauss Danielle suggests going with remove over delete:
> If that's more common language on other sites, then that boosts the case for us being consistent with expected experience.
> It's also consistent with the language of "Remove" that we had before when it was a link.

I had also shared with her that IMO "delete" feels more final/permanent, which isn't really the feeling we want to communicate given that they can add it back anytime.  She feels the same way.

**Comment by Samara-Strauss** [comment]
Sounds good to me! Thank you for being so diligent about details like this. I really appreciate it!

**Comment by andaleliz** [comment]
Sure thing! It's the only way I know how to be 😆

**Comment by andaleliz** [comment]
We tested this during the notification settings study, and [findings show that users didn't encounter any issues using the buttons](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/notifications-research-findings.md#all-participants-easily-understood-how-to-remove-contact-information-but-some-wanted-more-information-about-the-impacts-of-doing-so) with this on desktop.  Since the only difference on mobile would be the stacking of buttons, I recommend proceeding with: 
- moving the remove button outside of the edit functionality, and 
- updating the button style to use the secondary button from the design system until a better option is available

We'll need to revisit the content inside the alert modal but that's a separate issue.

I'd like to review/discuss the findings with the team before creating the FE documentation and closing this out. Moving to the next sprint.

**Comment by andaleliz** [comment]
@erikphansen, @tmitchellgcio, and @lihanli, I put [specs together](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md) for this change.

Trying to think through any errors or weird things that might happen when someone tries to remove their contact information. The only thing I can think of is when they click the confirmation in the warning, that call could fail and we can't successfully save the change of removing their contact information.

Is that a legit use case? If so, can you tell me how we handle that now? Screenshots would be helpful. I don't know how to trigger this on staging to see for myself.

Are there any other uses cases I'm missing?

Thanks!

**Comment by andaleliz** [comment]
Also @erikphansen and @tmitchellgcio I'm interested in your thoughts on all the [conditionals I put in the warning modal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md#warning-modal-1). This is still out for review/approval from our content team, FYI.

Currently only two of the bullets have conditionals because I'm fairly confident we can detect those things, and the copy for those bullets is on the long side. 

I'd love to add it for all of the bullets, so the modal will only tell the Veteran about things that are actually relevant to them.

What level of effort would be required to add that kind of logic?

Thanks!

**Comment by lihanli** [comment]
all those conditionals should be possible based on the backend data that is available

**Comment by erikphansen** [comment]
@andaleliz the conditionals for the delete confirmation modal are fine. I'd only push back on this one:

> [If contact email or mobile number, and user has opted into notifications] You will no longer get [email or text] notifications you signed up for.

We _could_ load all their notification preferences on the contact info section, but I wouldn't want to do that just because we want to conditionally show one line of text when they are deleting a piece of info. I was planning on only loading their notification prefs when they went to the notification preferences page.

**Comment by erikphansen** [comment]
@andaleliz yes we need to deal with the fact that:
1. The call to delete contact info will take at least a second or two. Maybe longer.
2. That call can fail. And it can fail quickly or it can fail many, many seconds after they start the delete.

Right now the Profile handles all of these cases.

Deletes and updates happen in the edit view. 
1. If the delete fails quickly, we show an error alert in the edit view and they can try again. You can probably replicate this by disconnecting from the internet before you start a delete.
2. If the delete is still pending after five seconds (I think) we exit edit mode and go back to read mode, but in place of the contact info they are deleting, we show a message like "we are saving your change...". If it eventually fails, we remove that "saving..." message, and show the contact info they were deleting along with a message saying we couldn't save their change. I don't have the actual messages handy and can't easily create those scenarios.

I would imagine doing something similar with this modal. Show the modal for up to five seconds while the delete is happening. If the delete has not succeeded or failed after five seconds, close the modal and show our standard "we are saving your change..." message in place of the info they are deleting.

**Comment by erikphansen** [comment]
@andaleliz question about x-padding in your specs. What should the minimum padding be for these two red lines? This will be more important for the spacing between the contact info itself and the edit/delete buttons to the right.
<img width="799" alt="Screen Shot 2021-07-07 at 4 16 55 PM" src="https://user-images.githubusercontent.com/20728956/124841680-a42a4000-df42-11eb-8f73-e0e93422ac49.png">

**Comment by andaleliz** [comment]
Thanks @lihanli and @erikphansen! In response to your questions/comments:

>We could load all their notification preferences on the contact info section, but I wouldn't want to do that just because we want to conditionally show one line of text when they are deleting a piece of info. I was planning on only loading their notification prefs when they went to the notification preferences page.

That makes sense to me, and I'm find w/ removing the conditional based on whether or not they're signed in. 

>What should the minimum padding be for these two red lines?

I updated the specs to specify a min x-padding of 48px; if you plug that in and it ends up absolutely not working with content, let's try 32px. 

>If the delete fails quickly, we show an error alert in the edit view and they can try again. You can probably replicate this by disconnecting from the internet before you start a delete.

Yep, that tricked worked and allowed me to see it! Thank you. Updated the specs for this use case; for now I think we can put the error message in background-only error alert above the buttons. That feels like the same kind of pattern/placement we have in other parts of profile when someone tries to perform an action that fails.  It's a different type of alert (yes, I know we need to align these all across the board), but it just feels WEIRD to use the alert w/ the sidebar inside of the warning modal since it already has a sidebar and so much padding.  If I learn this is handled another way inside modals on VA.gov, I'll update the specs to reflect the pattern that's already in place.

>I would imagine doing something similar with this modal. Show the modal for up to five seconds while the delete is happening. If the delete has not succeeded or failed after five seconds, close the modal and show our standard "we are saving your change..." message in place of the info they are deleting.

This sounds good to me; when we get to the point of it being built out, can you please show me how it looks? I'll update the specs to include this guidance too.

I heard back from Danielle on the modal content, and the specs are updated to reflect that.

@ajakabcin closing this out! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by andaleliz** [comment]
Reopening

If we update the profile layout to accommodate the remove button, it causes section headings/labels (not exactly sure what the right work is for these data points) to wrap on multiple lines throughout all sections of profile. Examples below.

<img width="876" alt="Screen Shot 2021-07-09 at 1 58 51 PM" src="https://user-images.githubusercontent.com/55992116/125308077-9982f880-e2fe-11eb-8af2-26c5df0b6fcf.png">
<img width="594" alt="Screen Shot 2021-07-09 at 1 59 23 PM" src="https://user-images.githubusercontent.com/55992116/125308074-9982f880-e2fe-11eb-8abb-cf961a0d1011.png">
<img width="585" alt="Screen Shot 2021-07-09 at 1 59 43 PM" src="https://user-images.githubusercontent.com/55992116/125308059-97209e80-e2fe-11eb-8e44-af952021f8ce.png">
<img width="595" alt="Screen Shot 2021-07-09 at 1 59 54 PM" src="https://user-images.githubusercontent.com/55992116/125308062-97b93500-e2fe-11eb-8e0b-8e4c202341e2.png">
<img width="593" alt="Screen Shot 2021-07-09 at 1 59 36 PM" src="https://user-images.githubusercontent.com/55992116/125308069-98ea6200-e2fe-11eb-8104-fcb80abf1cf2.png">

In order to accommodate those buttons and preserve readability in other parts of profile, I think we need to use the layout we use on screens 767px and smaller (see screenshot below).  The width of the containers will actually be narrower on desktop than it is at the 767px breakpoint, so we won't have any more whitespace on the right than we do at this breakpoint.

This layout would also improve accessibility for users who are zoomed in (straw test).
![image](https://user-images.githubusercontent.com/55992116/125308525-f8e10880-e2fe-11eb-86b5-ae3afd694096.png)

**Comment by andaleliz** [comment]
discussed today with @KevinMHoffmanUSDS and confirmed we can move forward with updating the profile layout to stack as shown above.  We'll consider using the primary button style for Edit

**Comment by andaleliz** [comment]
Updated mocks and specs to reflect what we talked about today.

I feel like this ticket is my digital version of Lowe's. I'm going to close it, but probably going to have to come back in 3 hours 😆
