### ISSUE TITLE
[Design] Profile - Determine how to handle profile's "remove contact info" feature when user is subscribed to notifications

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23666]
## Background
As discussed in the [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22592#issuecomment-822772262) of #22592, we need to consider how our "remove [contact info]" functionality impacts our notification settings section.  Erik identified that from a technical perspective, it is easiest not to allow people to delete their contact information.  We need more info about that, and if we agree that's the best approach, then we need to consider and document the UX for people who are opted into notifications but want to remove contact info.  

## Tasks
- [x] Confirm with Erik: why is it easiest not to allow it, vs adding text in the confirmation modal to let people know it will also unsubscribe them?
- [x] Mock-up solution/flow 
- [ ] Review with team
- [ ] document for FE

**Comment by andaleliz** [comment]
Thought: replacing the `remove [contact info]` with an FAQ "why can't I remove my [contact info] might be the best route.

**Comment by andaleliz** [comment]
Discussed with @Samara-Strauss and @erikphansen post-stand up on 5/7.  We decided we'll keep the `remove [contact info]` functionality for Veterans who are opted into notifications so they can continue to have ownership over their own information.  We'll add specificity to the remove confirmation modal to let users know they may stop receiving notifications if they delete that number.

Going to add this option to my existing [notifications content review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23907) for Danielle's input. Once I hear back from her, I'll mock this up.
![image](https://user-images.githubusercontent.com/55992116/117499871-d4a52c00-af49-11eb-8d49-e144cb8cd642.png)

Outstanding and related questions we hope to get answered in our next sync with VA Profile:
- confirm if a person deletes their mobile number or email address, and then adds another one later, from the communications API perspective, they will be opted into all the same things they were previously. 
- If a person deletes their mobile number or email address, and then adds another one later, will they still receive communications at that number or do they have to explicitly opt-in via another channel to get them to work? E.g. the experience of replying to a text to confirm when you opt in, typing STOP to opt out, etc.

**Comment by Samara-Strauss** [comment]
Question: do we show this alert whether or not someone has notifications they've opted into? I would assume yes for ease of programming. 

Either way, don't forget to add this into the frontend documentation for this work since we don't want the messaging to change before the notification preferences work goes out, but we most certainly want the copy updated once the project launches.

**Comment by andaleliz** [comment]
>Question: do we show this alert whether or not someone has notifications they've opted into? I would assume yes for ease of programming.

Yes, I think we should.

 >Either way, don't forget to add this into the frontend documentation for this work since we don't want the messaging to change before the notification preferences work goes out, but we most certainly want the copy updated once the project launches.
 
Noted - thanks for the reminder!

**Comment by erikphansen** [comment]
> >Question: do we show this alert whether or not someone has notifications they've opted into? I would assume yes for ease of programming.
> 
> Yes, I think we should.

Y'all are the best 😁

**Comment by andaleliz** [comment]
It is different in that other cases in profile; this alert replaces the
“remove [contact info]” button as well as the update/cancel buttons when a
user indicates they want to delete contact info. I think the UX was
designed differently so users see this immediately without having to scroll
back up above the fields. Here’s a video of how it works:
https://dsva.slack.com/archives/C0NGDDXME/p1620410805332600?thread_ts=1620401763.329900&channel=C0NGDDXME&message_ts=1620410805.332600
-- 
Liz Lantz
Senior UX Designer, Ad Hoc
843-898-4463
http://adhoc.team
