### ISSUE TITLE
Maintenance + usability updates to coronavirus FAQs page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23687]
## Issue Description
We need to do a maintenance review and update of this page. We also want to make changes to make the page easier to digest.

---
## Tasks
- [x] Finalize link updates (Danielle) - carried over from Randi and Selina's link ticket
- [x] Organizational changes (Danielle)
- [x] Content audit (Danielle) - in progress
- [x] Confirm content updates (Danielle, Lauren, Randi)
- [x] Finalize initial updates (Danielle, Randi)
- [x] Publish initial updates (Danielle, Randi)
- [x] Kick off associated translation ticket (Randi) 

## Acceptance Criteria
- [x] New changes published
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
**Tracking changes here:**
- Link changes (per previous ticket on accessibility)
- Rearranged links and made accordions to make more digestible
- Removed "what is va doing" question (outdated and too expansive for one question now) and instead added a related link to the public health page.
- Removed "Get the flu vaccine" bullet from the symptoms question (outdated). Instead, added a bullet about learning more about getting the COVID-19 vaccine (very generic content) with a link to the mini-hub.
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/192895e3-3b67-4201-a936-54f8275797c7)
- Combined the questions on physical distancing and "how will VA protect me from exposure." Since we're so far into the pandemic now, the general education question about physical distancing feels outdated.

**Questions for discussion:**

**- Do we want to change "How can I stay informed about COVID-19 vaccines at VA?"** to "Can I get a COVID-19 vaccine at VA?" and update the question to reflect latest info (can use approved content from vaccine mini-hub)?
**- Do we want to take the flu shot question down now?** Flu season is close to over, and was super mild to almost nonexistent this year so feels like we should remove.
**- For question about facilities being open for in-person care:** Are facilities still adjusting services based on COVID-19 cases, or are they generally open now with safety measures in place? Want to just check to make sure we have the most up-to-date info.
- For question about visiting patients at VA facilities: I think this is still the same. But any word on new/changing visitor policies?
**- Community care:** Just checking to make sure we're still extending VA authorizations for community care referrals for many types of care.

**Comment by RLHecht** [comment]
Recording here pages where we need to update anchor links now that all questions are in accordions:

https://www.va.gov/disability/get-help-filing-claim/ (in alert)
https://www.va.gov/health-care/pay-copay-bill/ (in alert)
https://www.va.gov/disability/va-claim-exam/ (in alert)
https://www.va.gov/life-insurance/options-eligibility/vgli/ (in alert)
https://www.va.gov/health-care/pay-copay-bill/financial-hardship/ (in alert)

**Comment by DanielleThierryUSDSVA** [comment]
**Updates on questions for discussion based on 4.26.21. meeting with Lauren and Chante:**

- Do we want to change "How can I stay informed about COVID-19 vaccines at VA?" to "Can I get a COVID-19 vaccine at VA?" and update the question to reflect latest info (can use approved content from vaccine mini-hub)?
  - Yes. @RLHecht Can you make this change? Let me know if you have questions.

- Do we want to take the flu shot question down now? Flu season is close to over, and was super mild to almost nonexistent this year so feels like we should remove.
  - Yes. @RLHecht Can you remove this question?

- For question about facilities being open for in-person care: Are facilities still adjusting services based on COVID-19 cases, or are they generally open now with safety measures in place? Want to just check to make sure we have the most up-to-date info.
  - Yes. All good for now. No action needed.

- For question about visiting patients at VA facilities: I think this is still the same. But any word on new/changing visitor policies?
  - All good for now. No action needed.

- Community care: Just want to check to make sure we're still extending VA authorizations for community care referrals for many types of care.
  - Danielle to follow up with community care on this this week.

**Comment by RLHecht** [comment]
The updated page is published and the alert links all work. Closing ticket. The translation effort around this is being done in ticket #23761
