### ISSUE TITLE
Language assistance and resources: Patient advocate content (issue 1 of 3 for this work)

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23685]
## User story

As a Veteran, caregiver, or family member, I need to know how to connect with a patient advocate to get language assistance and help to resolve problems at a VA health facility.

As someone with limited English proficiency, I need this information in my first language.

## Issue description

We need to create the following:
- Sections of the new Language assistance and resources pages in Spanish and Tagalog with information about how to get language assistance and how to resolve problems at a VA health facility, translated into Spanish and Tagalog respectively
- Resources and Support articles (in English) about how to get language assistance and how to resolve problems at a VA health facility

_Note: In the future, we'll want to expand the languages we offer this information in._ 

## Tasks to completion 

_Note: This ticket takes this work through to sending to SMEs to review. Will open a separate ticket to track tasks post-SME review through launch._

- [x] Research and draft content (Danielle)
- [x] Consultation perspective (Eunice) 
- [x] Copy edit (Randi)
- [x] Share with VHA (Danielle)

**Comment by DanielleThierryUSDSVA** [comment]
Hi Eunice. Here's the draft content. My goal is to share this with SMEs on Monday for feedback and accuracy check. Please let me know if you have anything we should consider as we continue to finalize this. Thanks!

[Patient advocate information_for Language Assistance and Resources pages_04.23.21](https://app.zenhub.com/files/133843125/72248aed-9729-4384-98d4-fda8d8d09969/download)

**Comment by eunicegar** [comment]
@DanielleThierryUSDSVA Added my thoughts in! Looks great! Also, would you try and ad my GH name again? Apparently, I had not been added the VA CTO repo so maybe that was the hiccup here.

**Comment by DanielleThierryUSDSVA** [comment]
@eunicegar Yay! I can tag you now. Thanks very much for taking a look at this!

**Comment by eunicegar** [comment]
Hooray! Go team!!

Sent from my iPhone

On Apr 23, 2021, at 1:50 PM, Danielle Thierry ***@***.***> wrote:

﻿

@eunicegar<https://github.com/eunicegar> Yay! I can tag you now. Thanks very much for taking a look at this!

**Comment by eunicegar** [comment]
[https://app.zenhub.com/files/133843125/adb60b41-c061-42e8-ae8d-518266451db6/download](https://app.zenhub.com/files/133843125/adb60b41-c061-42e8-ae8d-518266451db6/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Would you be able to copy edit this doc before I send over to the VHA folks for review?

[VA.gov_patient advocate information for review_04.28.21](https://app.zenhub.com/files/133843125/baea39aa-1fac-4263-88bc-fd0e1e2ba663/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This looks good. I added one word that was missing.
[VA.gov_patient advocate information for review_04.28.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6394331/VA.gov_patient.advocate.information.for.review_04.28.21.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much, @RLHecht!

**Comment by DanielleThierryUSDSVA** [comment]
Version sent to SMEs 04.28.21

[VA.gov_patient advocate information for review_04.28.21](https://app.zenhub.com/files/133843125/cf6e9682-7372-43b2-a25c-83587faba074/download)
