### ISSUE TITLE
Add a Q&A to R&S headstones and markers FAQs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23707]
## Issue Description
Stakeholders from the NCA team asked us to add a Q&A to the current [headstones and markers FAQs](https://www.va.gov/resources/government-headstones-and-markers-faqs/) in Resources and Support about inscribing info of a Veteran's spouse or dependent child on the Veterans' headstone in a private cemetery.

We first need to assess whether this belongs in an R&S Q&A or on the Tier 1 page. Is there other content pertaining to this that needs to be pulled from the Tier 1 page and put with this if it becomes a Q&A?

**Text provided from SME:**

H2: Will VA inscribe the name and dates of birth and death of a Veteran’s spouse or dependent child on the Veteran’s headstone or marker for a private cemetery?

Yes, if requested by the applicant and:

- The Veteran died on or after October 1, 2019; and
- The spouse, surviving spouse, or dependent child is eligible for burial in a VA national cemetery (but is not buried there).
- Documentation showing marital or dependent status is required.
- VA will replace a Veteran’s headstone or marker, upon request, to add an authorized spousal or dependent inscription if the Veteran died on or after October 1, 2019.
- VA is not authorized to furnish a headstone or marker solely for the Veteran’s spouse, surviving spouse, or dependent child for a private cemetery.

This text will need to be rewritten into our voice and style (not all of the above should be in bullets) and the H2 shortened.

## Tasks
- [x] Assess the best place for this content to go (Beth)
- [x] Build Q&A in Drupal (or add to Tier 1 page) and rework text (Selina)
- [x] Copyedit (Randi)
- [x] Review (Beth)
- [x] Send to stakeholders for approval (Beth/Randi)
- [x] Use Pre-publishing Checklist if R&S page (Randi)
- [x] Publish page

## Acceptance Criteria
- [x] New content live on site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you insert this information on https://www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/?:

**Will VA pay for the inscription of a family member’s information on a Veteran’s headstone in a private cemetery?**

Yes. If the family meets the eligibility requirements, we’ll pay to have a family member’s name, along with their dates of birth and death, inscribed on a Veteran’s headstone or marker in a private cemetery. 

**Both of these must be true:**

- The Veteran died on or after October 1, 2019, **and**
- The spouse or dependent child is eligible for burial in a VA national cemetery (but isn’t buried there)

**To apply for an inscription:**
Add the inscription information in block 18 of the Claim for Standard Government Headstone or Marker. When you submit the form, please include documents that show the spouse or dependent relationship (like a marriage license or birth certificate).

**Note:** If needed, VA will replace a Veteran’s headstone or marker in order to add a family member inscription. We'll pay for the replacement. Use the same form to request a replacement headstone or marker. 

-----------------------------
Here's the order under "Memorial items" header:

- Is a Veteran buried in a private cemetery eligible...?
- Is a family member buried in a private cemetery eligible...?
- Will VA pay for the inscription..."?
- If I'm planning in advance...?

**Comment by bethpottsVADEPO** [comment]
@RLHecht I'll send the preview to the stakeholders once you've done the drupal work. We'll see if they agree with the placement on this page rather than the R&S FAQ about headstones.

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close after next deployment.

**Comment by RLHecht** [comment]
content live. closing ticket.
