### ISSUE TITLE
[Campaign Landing Page Production MVP] - Vaccine Confidence

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#23704]
## Description 

Goal: Offer a place for Veterans and their family members who aren’t confident in COVID-19 vaccines to find information from Veterans, VA health care providers, and other trusted sources. This information will be designed to help the Veteran or family member talk with their health care provider and make informed decisions about COVID-19 vaccines.

What we want to do on this page:

- Acknowledge that it’s understandable to have questions about new vaccines
- Provide clear, accurate, and empathic answers to concerns about COVID-19 vaccine safety and effectiveness
- Provide links to:
  - Veteran stories about getting a COVID-19 vaccine (video and/or written) so Veterans and their families can learn from others
  - More information from VA health care providers and other trusted sources so Veterans and their families can continue to get the latest facts
  - Resources to help Veterans and their families keep the conversation about getting a vaccine going with their health care provider
  - Connect Veterans and their families with VA to find out when they can get a vaccine (while stressing that there’s no commitment to get one when signing up)

## Key Info

**Who is Requesting**

- Requestor name: Danielle Thierry
- VA organization: VHA
- Email address: danielle.thierry@va.gov

**About the Campaign**

- Name or focus of Campaign: VA COVID Vaccine Confidence
- Target audience(s) [up to 3]:
   - Veterans
   - Service members
   - Family members
- Goals of the Campaign:  

- Campaign start and end dates: 
   - May 2021 - December 2021
- Campaign page target launch date: 
  - May 20 2021
- Preferred and Vanity URLs
   - Root URL (based on H1): https://va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine
   - Redirect URL: http://www.va.gov/covid-vaccine-questions
- What will you to drive awareness of this Campaign and this page? 
   - TBD
- What metrics will you want to know to measure success of the Campaign landing page? 
   - TBD
   
**About Your Campaign Page Build**

- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
  - Very -- the VA.gov Sitewide Content team will build the CLP on behalf of VHA
- Who will build the campaign landing page in the VA.gov CMS?
  - Possible: @DanielleThierryUSDSVA 
- Who will review and give approval to publish the page? 
  - @DanielleThierryUSDSVA 
- Who will update/maintain the landing page during the campaign?
  - VA.gov Sitewide Content team
- At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved?  If preserved, why?
  - TBD

## What Needs to Be Done

- [X] CMS: Set up the CLP clone page in CMS for the build template - https://prod.cms.va.gov/node/19578/edit
- [x] Content: Create preview version of CLP for staging review: http://preview-prod.vfs.va.gov/preview?nodeId=19578
- [x] Product: Get the Analytics dashboard set-up and obtain UTM URLs from stakeholder(s)
- [x] Product & IA: Validate that the requested URL is workable/optimal

**Comment by johnhashva** [comment]
Adding the draft of the content build template/copy deck as provided by @DanielleThierryUSDSVA 

[Campaign landing page_Vaccine confidence campaign_v2 (04.22.21).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6391993/Campaign.landing.page_Vaccine.confidence.campaign_v2.04.22.21.docx)

**Comment by johnhashva** [comment]
@DanielleThierryUSDSVA and @brianalloyd -- Here are the three UTMs I've generated for this Campaign.  Danielle, let me know if adjustments (or additional UTMs say for CPC/Paid Social) are needed:

VA.gov links
https://www.va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine/?utm_medium=va-network&utm_source=va&utm_campaign=va-covid-vaccince-confidence

GovDelivery Email links
https://www.va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine/?utm_medium=email&utm_source=govdelivery&utm_campaign=va-covid-vaccince-confidence

Facebook links
https://www.va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine/?utm_medium=social&utm_source=facebook&utm_campaign=va-covid-vaccince-confidence

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @johnhashva! These look great.

**Comment by brianalloyd** [comment]
Launched, closing this ticket in support.
