### ISSUE TITLE
EKS - Migrate Sentry service in to utility cluster

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23711]
## Description
In order to move the Sentry service away from the legacy infrastructure deployment system (BRD), Ops is moving Sentry to EKS, and then decommissioning the previous installation. 

## Background/context/resources
Sentry currently in BRD will move to EKS

## Technical notes

- Sentry will go into the utility cluster
- Sentry will be still available via the existing URL - https://sentry.vfs.va.gov)
- There are some considerations around moving sentry data off of the current persistent volumes and into something else (TDB)

---
## Tasks
- [ ] Set up app manifest
- [ ] CD Pipeline
- [ ] Determine solution for persistent data 
- [ ] URL routing 

## Definition of Done
- [ ] Sentry has been fully migrated to EKS
- [ ] Legacy Sentry (BRD) has been de-commissioned 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Sentry has been migrated and is live on EKS. 

Closing.
