### ISSUE TITLE
Verify Delete Draft

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#23715]
## Issue Description
We need to verify and test that the delete draft functionality is working as expected for the SM Mobile API.  Deleting drafts remove them from the database completely instead of moving them to the Deleted folder.

---

## Tasks
- [ ]  Review MHV delete draft functionality in [MHV API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/secure-messaging/existing%20state/MHV_Secure_Messaging_API_Veteran_2.5.pdf)
- [ ]  Test the current behavior of the endpoint on `vets-api`
- [ ]  Test MHV API create draft endpoint directly through a [review instance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/db997e8d7154088155fa60f66265ef26570c8814/platform/engineering/backend/review-instances.md)
- [ ]  Compare response/schema with response we are giving through `vets-api`
- [ ]  Update OpenAPI docs
- [ ]  Update Postman collection if necessary

## Acceptance Criteria
- [ ]  Create delete functionality is working as expected OR if there are bugs/issues found, a new ticket has been created to track this work
- [ ]  Add or update specs if necessary
- [ ]  OpenAPI docs are up to date
  - [ ] Required and optional parameters are updated
  - [ ] Example request and response bodies are updated
  - [ ]  Possible error states have been documented
- [ ]  Postman is up to date
- [ ] Error states have been documented

**Comment by narin** [comment]
Implemented with #25935.  Tested on Staging. Closing out.
