### ISSUE TITLE
Verify Existing Delete Functionality

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#23710]
## Issue Description
We need to verify and test that the delete message functionality is working as expected for the SM Mobile API.

In Secure Messaging, deleting a non-draft message does not actually remove the message to the database, but instead moves a message from its current folder to the Deleted folder.  

**Note:** Deleting drafts will be covered in a different ticket: [#23715](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23715)

---

## Tasks
- [x]  Review MHV delete message functionality in [MHV API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/secure-messaging/existing%20state/MHV_Secure_Messaging_API_Veteran_2.5.pdf)
- [x]  Test the current behavior of the endpoint on `vets-api`
- [x]  Test MHV API delete endpoint directly through a [review instance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/db997e8d7154088155fa60f66265ef26570c8814/platform/engineering/backend/review-instances.md)
- [x]  Compare response/schema with response we are giving through `vets-api`
- [x]  Update OpenAPI docs
- [x]  Update Postman collection if necessary

## Acceptance Criteria
- [ ]  Delete functionality is working as expected OR if there are bugs/issues found, a new ticket has been created to track this work
- [ ]  Add or update specs if necessary
- [ ]  OpenAPI docs are up to date
  - [ ] Required and optional parameters are updated
  - [ ] Example request and response bodies are updated
  - [ ]  Possible error states have been documented
- [ ]  Postman collections are up to date
- [ ] Error states have been documented

**Comment by Teesh** [comment]
The DELETE endpoint worked as expected on all types of messages:
Inbox messages were sent to the Deleted folder
Folder messages were sent to the Deleted folder
Attempting to delete a sent message threw an error

A couple notes:
There were no drafts to test on but they have to be handled in a special way, i.e. deleted from the DB completely, not moved to Deleted folder. This will need to be tested once Drafts are implemented
Deleted items moved from folders don't store information regarding which folder they were deleted from, in case an undelete option is added
