### ISSUE TITLE
[Design] Notification Preferences: Determine naming conventions + organization for notifications and groups

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23728]
## Background
As part of the Notification Preferences work we need to define name for the communication items as well as the names of the groups that we'll categorize those communication items into.  We'll need to collaborate with our partners on VANotify and VEText.

## Tasks
- [x] Define communication items
- [x] Define group names and groupings for communication items to fit into
- [x] Send to Danielle for content review

## MVP notification worksheet
[Communication-Permissions-Configuration-Data-Worksheet_4.20.21-edits.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6367737/Communication-Permissions-Configuration-Data-Worksheet_4.20.21-edits.xlsx)

**Comment by Samara-Strauss** [comment]
@andaleliz I know you are out a few days this week, but I wanted to check in on what reasonable expectations are related to this ticket for the purposes of planning next sprint (always gotta be one sprint ahead!). Does this sound reasonable?

This sprint:

- You make an initial proposal on names for items (notifications) and names/categories for groups.
- You bring that to Danielle for review.

Next sprint:

- IA review. If this sounds good, we should flag this for Mikki now so we can hopefully get a review earlier than later in the sprint.

We can tweak this however we need. Just let me know what you think is realistic. Thank you!

**Comment by andaleliz** [comment]
@Samara-Strauss That sounds very reasonable - planning on spending time on this today so I can get it to Danielle for her review. I'll be out during office hours on 4/29, but hoping I can send it to her in advance and still get feedback by EOD Friday.  I [checked with her on Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1619529245180600) to see if that is possible. Either way, I'll work on this today.

**Comment by andaleliz** [comment]
@Samara-Strauss @ajakabcin Danielle replied:

>I can definitely aim for EOD Friday, but if there's not a definite need for it to be completed in this sprint, I would very much appreciate the added time. Want to aim for me having feedback to talk through together in next week's office hours?

From your perspective, is it ok for this to wait until 5/6 (next week's content office hours) to finalize? I think we could still flag for Mikki after I work through my suggestions today and get her feedback on IA early in our next sprint, which leaves us with:

**Current sprint**
- Complete initial proposal on category/item naming
- Send to Danielle for review
- Send to Mikki for review

**Next sprint**
- Complete IA review
- Complete content review
- Revise category/item names accordingly

**Comment by Samara-Strauss** [comment]
Awesome, thank you for this update, @andaleliz! All of this sounds good to me. Keep me posted on what Danielle says and if that changes anything.

**Comment by Samara-Strauss** [comment]
> From your perspective, is it ok for this to wait until 5/6 (next week's content office hours) to finalize? I think we could still flag for Mikki after I work through my suggestions today and get her feedback on IA early in our next sprint...

Ah, looks like we basically posted at the same time — yes, this is still good to me. Let's still definitely flag for review by Mikki early in the next sprint so we can keep this work moving.

**Comment by andaleliz** [comment]
@Samara-Strauss and @ajakabcin, I've got my initial list ready. I'm backtracking on my suggestion to require 2+ notifications to make a group. If we go that route, that means we'll be moving things from `other` into a group. That will require people re-learn how things are organized, possibly each time they log in depending on the frequency of our updates and their log, and that's not great.

I would like to:
- organize by benefit type where possible
- display groups alphabetically, unless research shows us people need something different
- remove transactional notifications (e.g. debt notification in the spreadsheet)

I'd love to run these by someone before I ask Danielle for her time reviewing. Do these make sense to you based on what we know so far? There are a lot of moving parts here so want to make sure I'm interpreting thing accurately.  I've removed the 2 notifications Paras and I discussed in Slack today.

![image](https://user-images.githubusercontent.com/55992116/116304811-f7c52400-a770-11eb-88c0-921712ec639d.png)

I'll attach the spreadsheet once we're all on the same page. I have a thing about multiple versions of the same file getting outdated on GH.

**Comment by Samara-Strauss** [comment]
These are looking great! I have a few thoughts/suggestions on group names:

- **Applications**: What do you think about "Apply for VA benefits"? This copy is already used on the My VA dashboard, and I also wonder if some people would be confused by the term "application" since that could also mean a computer application or tool (or maybe it's totally clear and I am overthinking this). Anyway, just a suggestion! Obviously, Danielle has final say on all copy.
- **Disability compensation and pension**: Given that these two benefit types may not always be paired in the future, I think this category should be something like "Payments" or "Financial information". The latter could also account for debt notifications, which are actively being worked on by the debt management team even though debt collection is currently paused. Anyway, this would allow us to have "Disability benefits"  and/or "Pension benefits" sections in the future should those be needed. Thoughts?
- Generally, I think we need to be open to the fact that these groups might change and overall IA might change in the future. I totally agree that we don't want this to change every time there is an update because that could be confusing, but given that we don't know now what notifications we'll need to accommodate in the future, it's inevitable there will be some level of change.

**Comment by andaleliz** [comment]
@Samara-Strauss Great point about **Applications**! I'll change it to Apply for VA benefits. I think this name works well to accommodate any other notifications that come up for this group. 

>Disability compensation and pension: Given that these two benefit types may not always be paired in the future, I think this category should be something like "Payments" or "Financial information". The latter could also account for debt notifications, which are actively being worked on by the debt management team even though debt collection is currently paused. Anyway, this would allow us to have "Disability benefits" and/or "Pension benefits" sections in the future should those be needed. Thoughts?

Also very good points! I like the latter since it will account for more. Even though you are totally right - we need to be open to the fact that the groups might change.  I agree it's inevitable, just want to try to set us up for minimizing that given what we know today.

Latest file attached; I'll get these over to Danielle this morning.

[communications-permissions-configuration-data-worksheet-042821-edits.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6390409/communications-permissions-configuration-data-worksheet-042821-edits.xlsx)

**Comment by Samara-Strauss** [comment]
Looks great to me! Looking forward to feedback from Mikki and Danielle!

**Comment by ajakabcin** [comment]
All of this looks awesome thanks @andaleliz and great work!
