### ISSUE TITLE
Staging Review VAOS - VAOS for Distribution

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23735]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to VSP feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/vaos-for-distribution-initiative.md)
- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository. https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
-  Staging test-user information (if applicable) [Judy](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md)
-  Link to content brief (if applicable)
-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or elsewhere) https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/vaos-for-distribution-release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- ~Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan))~ _for QA practice area review_
  - VAMF SQA testing ticket  [VAOSR-1683](https://issues.mobilehealth.va.gov/browse/VAOSR-1683)
- ~Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail~ _for QA practice area review_ 
  - #21487
- Link to verification that accessibility checks are complete:
  - #21342
- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): Lauren Ernest
- DEPO Product lead (recommended): Lauren Alexanderson
- DEPO Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Peter Russo (@outerpress), Jeff Balboni (@jbalboni) 
- Content, IA, accessibility, and QA specialists (if applicable): Danielle Thierry (@DanielleThierryUSDSVA)

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **5/4 1130**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://docs.google.com/document/d/1_1gGJW6Go0Kk-H5jttDbQIZrcbKTst9gSZnXKVdeQSg/edit?usp=sharing) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
thanks @laurenernest ! scheduled for 5/4 at 11:30 am ET

**Comment by pjhill** [comment]
@laurenernest, it looks like the links to the QA artifacts are the default links. Do you have any QA artifacts available for review? Did you use TestRail to create a test plan?

**Comment by laurenernest** [comment]
@pjhill Our borrowed QA support doesn't use TestRail. All I have is that E2E ticket.

**Comment by pjhill** [comment]
> @pjhill Our borrowed QA support doesn't use TestRail. All I have is that E2E ticket.

Thanks Lauren, is there any kind of output that we can review to ensure that a QA test plan for the product adhered to Platform's standards for QA testing?

**Comment by laurenernest** [comment]
I've asked for additional QA artifacts and will post here if they have any

**Comment by laurenernest** [comment]
@pjhill Not sure if you can see this ticket, but I've attached the spreadsheet as well. [VAOSR-1683](https://issues.mobilehealth.va.gov/browse/VAOSR-1683)

[Covid2.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6417855/Covid2.xlsx)

**Comment by pjhill** [comment]
> @pjhill Not sure if you can see this ticket, but I've attached the spreadsheet as well. [VAOSR-1683](https://issues.mobilehealth.va.gov/browse/VAOSR-1683)
> 
> [Covid2.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6417855/Covid2.xlsx)

I am unable to view the JIRA link, but I'm looking through the spreadsheet. Thanks!

**Comment by mnorthuis** [comment]
Hi @laurenernest,  I had provide a recommended change to the breadcrumb and language used in the URLs in the IA ticket here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19821.  It looks like none of those recommendations have been implemented.  Can you provide some background on that decision?

**Comment by laurenernest** [comment]
We had just started a pilot and this flow in its current state is temporary so we'll carry those recommendations over to the sustainment solution if it doesn't end up being baked into our primary flow.

**Comment by laurenernest** [comment]
@mnorthuis Added a ticket for us to at least update the breadcrumb while we determine the sustainment experience since it doesn't have other impacts if we make a change 👍 #24206

**Comment by mnorthuis** [comment]
@laurenernest Perfect!  Thank you for the info!
