### ISSUE TITLE
J&J updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23739]
## Update on the Janssen (Johnson & Johnson) COVID-19 vaccine

We're starting to offer the Janssen COVID-19 vaccine again at VA health facilities. We'll offer this vaccine to Veterans, spouses, caregivers, and CHAMPVA recipients who are at least 18 years old.

###  How we made this decision

We continue to follow guidance from the CDC and U.S. Food and Drug Administration (FDA). When a very small number of people who received the vaccine experienced rare but serious blood clots, CDC and FDA experts recommended a pause in providing this vaccine. They did this to give them time to study the issue. They then carefully reviewed these cases and all available data. Based on this review, they're confident that this vaccine is safe for use and works well to prevent COVID-19. 

**The available data show:**
- The vaccine's benefits outweigh its risks
- The chance of blood clots after getting this vaccine is very low

###  What this means for you

If we offer you the Janssen vaccine, we'll give you information about the potential risks and benefits. This includes the rare risk of blood clots. We'll also tell you about your other vaccine options.

The primary goal of COVID-19 vaccines is to protect those we serve from COVID-19. And your safety—and the safety of all who receive a COVID-19 vaccine from VA—remains our priority.

###  What you can do next

To learn about your facility’s current plan, go to the facility’s website. Once you're on the site, go to Health care services, then COVID-19 in the menu.
[Find your nearest VA health facility that offers COVID-19 vaccines](https://www.va.gov/find-locations/?facilityType=health&serviceType=Covid19Vaccine)

If you have questions about this vaccine, contact your primary health care provider.
[Send a secure message to your VA provider to ask about COVID-19 vaccines](https://www.va.gov/health-care/secure-messaging/)

**Tasks:**
- [x] Add update to page (Randi)
- [x] Review and publish (Danielle/Randi)
- [x] Send copy to translation team (Randi)
- [x] Update Spanish page with translated content (Selina)
- [x] Update Tagalog page with translated content (Selina)
- [x] Review and publish Spanish page (Randi)
- [x] Review and publish Tagalog page (Randi)
- [x] Send links to live pages to VHA translation team (Randi)
- [ ] Update pages with any changes and publish (Selina/Randi)

Acceptance criteria:
- [x] All three pages have updated Janssen content on page

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht heads up this is coming up probably today. We updated content this weekend on English page around J&J. But we should just move right to getting this content translated because by the time we get the weekend version back, we'll have already posted this updated version. I will let you know as soon as this content is approved so we can get it to translators!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Could you post the above approved content in the blue featured box on the vaccine page and send this off to the translators? Thank you!

**Comment by RLHecht** [comment]
This page was published and content sent to translation team.

**Comment by RLHecht** [comment]
@lunascoop Here is the translated copy for both the Tagalog and Spanish page for the updated alert on the Janssen vaccine.

[https://app.zenhub.com/files/133843125/9ef4b8e6-aa0d-4829-839d-e6000f771df9/download](https://app.zenhub.com/files/133843125/9ef4b8e6-aa0d-4829-839d-e6000f771df9/download)

[https://app.zenhub.com/files/133843125/37512948-c3c8-44ef-983a-f6a7dfb6983a/download](https://app.zenhub.com/files/133843125/37512948-c3c8-44ef-983a-f6a7dfb6983a/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. I noticed in Matteo's update to the Tagalog page yesterday, he changed (sa English) to (sa ingles). I'm not sure if it's correct or intentional. If it is, then it needs to be changed throughout this page and the Tagalog faq page.

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
