### ISSUE TITLE
Review and publish CRSC article in R&S

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23755]
## Issue Description
Once we get approval from stakeholders on the Combat-Related Special Compensation article we created for R&S we need to copy edit, review and publish.

## Tasks
- [ ] Input any changes from stakeholders (Selina)
- [ ] Review page (Beth)
- [ ] Copy edit and follow pre-publishing checklist (Randi)
- [ ] Publish article (Randi)
- [ ] Alert stakeholders that page is live (Beth/Randi)

## Acceptance Criteria
- [ ] New R&S article live on site

**Comment by RLHecht** [comment]
@bethpottsVADEPO I copyedited this article and made a few copy tweaks.

A few notes and questions:
- In the **Evidence and documents you'll need to provide section**: We don't spell out NCOERs or OERs. Should we?
- In the **How to apply** section is it correct that under Navy and Marine Corps the only address lists Secretary of the Navy? Also, I reversed Navy and Marine Corps to keep it alphabetized with the other branches.
- I added "mailing" before address since we also say email address in the same sentence.
- I unbolded the lead-ins to the addresses and email addresses in the second set of accordions because we didn't have them bolded in the first set.

**Comment by bethpottsVADEPO** [comment]
- It's ok to not spell out here
- yes, just an address for Navy is right
- thank you!
- sounds good

One more thing you can help me with: I made 2 links full sentences rather than embedding them within only a portion of a sentence. One of them isn't working in preview now. Can you check and see if you can figure out why? It's under "How to request the documents you need": Learn about how to request your military service records

**Comment by RLHecht** [comment]
Thanks, Beth. The reason that one link isn't working is because preview links don't work for Drupal pages. You have to check them on the view or latest revision page to make sure that it's working. The one you mention above is all good.

**Comment by RLHecht** [comment]
This page is published. Moving to validate and will close after the deployment.
