### ISSUE TITLE
Review submission data for analytics

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23760]
## Description
Document all fields and values/value types being passed as part of the submission event.

Goal- With this info, I'd like to review all the fields and make any necessary updates to the events and request GTM updates from Analytics at one time.

---
## Tasks

- [x] vaos-direct-submission-successful

- [x] vaos-request-submission-successful

- [x] vaos-community-care-submission-successful

- [x] vaos-covid19-submission-successful

- [x] vaos-cancel-appointment-submission-successful

- [ ] vaos-community-care-submission
- [ ] vaos-community-care-submission-succeeded
- [ ] vaos-community-care-submission-failed
- [ ] vaos-direct-submission
- [ ] vaos-direct-submission-succeeded
- [ ] vaos-direct-submission-failed
- [ ] vaos-request-submission
- [ ] vaos-request-submission-succeeded
- [ ] vaos-request-submission-failed
- [ ] vaos-covid19-submission
- [ ] vaos-covid19-submission-failed
- [ ] vaos-cancel-appointment-submission
- [ ] vaos-cancel-appointment-succeeded
- [ ] vaos-cancel-appointment-failed
- [ ] vaos-cancel-appointment-submission-failed

## Acceptance Criteria
- [ ] All event data is documented for each of the submission types

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by jbalboni** [comment]
vaos-direct-submission-successful:

flow: "direct"
health-ReasonForAppointment: "routine-follow-up"
health-TypeOfCare: "Primary care"
vaos-number-of-preferred-providers: 0

vaos-request-submission-successful

flow: "va-request"
health-ReasonForAppointment: "routine-follow-up"
health-TypeOfCare: "Primary care"
vaos-number-of-preferred-providers: 0

vaos-community-care-submission-successful

flow: "cc-request"
health-ReasonForAppointment: undefined
health-TypeOfCare: "Podiatry"
vaos-number-of-preferred-providers: 0 (I think this is a bug)

vaos-covid19-submission-successful

facility-id: "983"
flow: "direct"
health-TypeOfCare: "COVID-19 Vaccine"

vaos-cancel-appointment-submission-successful

appointmentType: "confirmed"
facilityType: "va"

**Comment by laurenernest** [comment]
@jbalboni Updated the description with the additional scope. In our analytics event list, it looks like there's more than one event name for the same thing so it would be good to understand if we're actually tracking the same thing in 2 ways or if it's a documentation verbiage issue.

**Comment by jbalboni** [comment]
I don't see these in the code:

vaos-direct-submission-succeeded
vaos-community-care-submission-succeeded
vaos-request-submission-succeeded
vaos-cancel-appointment-succeeded
vaos-cancel-appointment-failed

Generally, we have a submission event, which means a submission was attempted, then either a successful or failed event for the same action.

vaos-community-care-submission:

flow: "cc-request"
health-ReasonForAppointment: undefined
health-TypeOfCare: "Podiatry"
vaos-community-care-preferred-language: "english"
vaos-number-of-preferred-providers: 0

vaos-community-care-submission-failed:

flow: "cc-request"
health-ReasonForAppointment: undefined
health-TypeOfCare: "Podiatry"
vaos-number-of-preferred-providers: 0

vaos-direct-submission:

flow: "direct"
health-ReasonForAppointment: "routine-follow-up"
health-TypeOfCare: "Primary care"
vaos-number-of-preferred-providers: 0

vaos-direct-submission-failed:

flow: "direct"
health-ReasonForAppointment: "routine-follow-up"
health-TypeOfCare: "Primary care"
vaos-number-of-preferred-providers: 0

vaos-request-submission:

flow: "va-request"
health-ReasonForAppointment: "routine-follow-up"
health-TypeOfCare: "Primary care"
vaos-community-care-preferred-language: undefined
vaos-number-of-preferred-providers: 0

vaos-request-submission-failed:

flow: "va-request"
health-ReasonForAppointment: "routine-follow-up"
health-TypeOfCare: "Primary care"
vaos-number-of-preferred-providers: 0

vaos-covid19-submission:

flow: "direct"
health-TypeOfCare: "COVID-19 Vaccine"

vaos-covid19-submission-failed:

flow: "direct"
health-TypeOfCare: "COVID-19 Vaccine"

vaos-cancel-appointment-submission:

appointmentType: "confirmed"
facilityType: "va"

vaos-cancel-appointment-submission-failed:

appointmentType: "confirmed"
facilityType: "va"

**Comment by laurenernest** [comment]
Thank you! I'll update our documentation.
