### ISSUE TITLE
R&S: Links Strategy

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#23765]
### Issue
As more articles are added to resources & support, we have opportunities to link between more articles. It's also an opportune time to revisit links on all articles, as our thinking has evolved about how to leverage the CTA buttons, text links, and related information links.

CTA buttons (Mandatory at top of page. Optional for same button(s) to also appear at bottom of page.)
- Primary action the user would take after reading all the information in the article
- 40 characters and spaces max
- Lead with an action, like download, sign in, learn etc.

Text links (Give users and action to take that's related to the faq or section of text they just read.)
- Okay to repeat the CTA button in a text link where appropriate.  

Related information (At least 1 link is mandatory at bottom of page)
- Do not repeat CTA button links in related information
- It's okay to repeat links as text links and under related information, as long as they're not CTA buttons
- Links should be closely related to the article topic(s)

### Tasks

- [ ] SC to create a spreadsheet of all live R&S articles

- [ ]  SC to review links on each page, indicating proposed changes in spreadsheet

- [ ]  DEPO to review spreadsheet and approve proposed changes

- [ ] SC to create GH tickets for link changes to live pages

### Work in Progress
Document updated July 9
[rs-links-audit-07-09-21.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6791713/rs-links-audit-07-09-21.xlsx)
, 2021

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 What I'd like to do rather than reviewing the whole spreadsheet is have a couple working sessions during our team meeting where we look at groups of recommended changes according to categories you think make sense. Like here are all the articles that a CTA going to sign in. Do all these make sense. And here are all the articles that if we had the choice we wouldn't have a CTA at all because there isn't an obvious/logical one. What to do? So the spreadsheet can be for your use only, however it's helpful to track it all! When you're ready to bring the first group of changes to our sitewide content meeting, just let us know, and we'll spend 15-20 minutes on it, depending on what else we need to talk about that week. We'll go from there... cc @DanielleThierryUSDSVA for awareness

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Are we done looking at all the CTAs that you assessed as needing to be revisited/changed? If so, we could close this ticket. Would any of the info in the spreadsheet be helpful to have in github? Or does Selina's doc there cover all this--or does that need updating now that you've done this work and updated CTAs?

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - There are still 5 open questions in the spreadsheet at the top of this ticket. Can you take a look and help me resolve? Then I can create individual tickets for those changes, and close this ticket. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I saw 4--what did I miss?

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - One on the **account and profile** tab, two on **burials and memorials** tab, one on the **education and training** tab, and one on the **other** tab. Thanks!

**Comment by bethpottsVADEPO** [comment]
**Burials and memorials**
1/ Question:
Confirming if this article answers the question correctly. Our tier 1 page (https://www.va.gov/burials-memorials/pre-need-eligibility/), under step 2 doesn't mention the need to work with a funeral director. It says, "This application doesn’t apply to Arlington National Cemetery or the United States Soldiers and Airmen’s Home National Cemetery. If you’d like to be buried in either of these Department of the Army cemeteries, please call 877-907-8585..." 

Answer: Let's reword and add a sentence like this (with a colon following the last sentence that sets up the CTA button): You can contact Arlington National Cemetery at 877-907-8585 for their eligibility information. Or go to the Arlington National Cemetery website to get details about eligibility:

2/ I will be talking with the NCA SME on Friday, so I will ask her about your family members question.

**Education**
I agree with you about adding headers and rearranging the order of the questions. Thanks for doing that!:
**How education payments work** 
Followed by questions 3-5
**Advance payments** 
Add a new question -- What's an advance payment?, followed by questions 1 and 2. 
@lwalsh617 Let's frame it in the singular, since it isn't an ongoing thing you sign up for. My understanding is that it's more of a one-off. Can you double check?
Let's leave the example where it is.

**New intro:**
Get answers to questions you may have about your GI Bill payments.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 You can go ahead with the above changes I noted, and here are some more edits/updates from your questions in the spreadsheet that you can make now:

- Do you have to be a "family member" to request a replacement, or should we say something like: 
 "If you feel that a Veteran's government-issued headstone needs to be replaced, we may be able to help. Keep reading this page to find out about asking for a new headstone." **Update:** This is outstanding--the SME is checking who can request. But you're right that it's more than the family member. We'll turn back to this when we have the answer. 

- Plain language versus official language question:  
Current copy:  The headstone or marker must meet one of the requirements listed below to be eligible for replacement. One of the following must be true. The headstone or marker:.. 
Is this fine as is--because it's both plain language and official sounding, or should it be more like: 
We can replace a headstone or marker under certain conditions. One of the following must be true. The headstone or marker:... 
**Answer:** This is fine to leave as is.

Questions about page content:
• Do we need to better define the bullet, "Doesn't meet certain contract specifications"?
**Answer:** Yes! Thank you. Please change it to: Doesn’t meet certain guidelines, like size or weight
• Should we format the info about replacements for historic and 50+ headstones with bullets as well -- or even make part of the same bulleted list? **Answer:** Leave as is, thanks.
• Does this line of copy under the "historic" section also apply to the bulleted copy?: Then we'll replace the marker “in kind,” which means the marker will have the same type, style, and inscriptions used when the Veteran was buried. **Answer:** No, this can stay as is since it just applies to historic headstones.

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
