### ISSUE TITLE
Update Spanish and Tagalog pages to match updated FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23761]
## Issue Description
We have reworked the coronavirus FAQs page, removing some questions, moving all questions into accordions, and updating links for accessibility. We need to have the Spanish and Tagalog pages match this. 

Updates to the English page are being tracked in #23687
These updates are being sent to the translation team 4/26. 

## Tasks
- [x] Rework Spanish page to match English FAQs (Selina)
- [x] Rework Tagalog page to match English FAQs (Selina)
- [x] Review Spanish page (Randi)
- [x] Review Tagalog page (Randi)
- [x] Publish Spanish page (Randi)
- [x] Publish Tagalog page (Randi)
- [x] Send live links to VHA translation team (Randi)

## Acceptance Criteria
- [x] Spanish and Tagalog pages are live with matching content to English FAQs

**Comment by RLHecht** [comment]
@lunascoop This content still needs to be sent to the translation team but if you wanted to get started reworking the pages so that they are all in accordions you can.

**Comment by RLHecht** [comment]
@lunascoop here are the 2 word docs. Let me know if you run into any issues.

[https://app.zenhub.com/files/133843125/932848c7-0c77-4c67-94c0-ed461da5ca63/download](https://app.zenhub.com/files/133843125/932848c7-0c77-4c67-94c0-ed461da5ca63/download)

[https://app.zenhub.com/files/133843125/77c8e249-d3a6-41b8-9f07-54afa437cc7d/download](https://app.zenhub.com/files/133843125/77c8e249-d3a6-41b8-9f07-54afa437cc7d/download)

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA @RLHecht These updates, along w/ the ones for ticket #24095 are ready for review.

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano : http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580
- Coronavirus FAQs: What Veterans need to know: http://preview-prod.vfs.va.gov/preview?nodeId=3014

**Notes**

- Bc of the page re-organization a month or so ago, the in-page links on all pages (English, Tagalog and Spanish) needed to be updated
- The **Do I need to wear a mask in a VA health facility or Vet Center?** question needs to be updated and translated for the Tagalog and Spanish pages (formerly Do I have to wear a mask when I go to a VA hospital or other location?)
- Answer for **What if I can't pay my existing VA debt?** needs to be translated in Tagalog
- Some text for the **How will VA protect me from exposure to COVID-19 when I'm in a VA facility?** question wasn't translated. So I translated them via Google translate. ("We're taking these steps to ensure physical distancing:" and "We're also taking these added safety precautions:")
- For the **What should I do while I’m waiting for the results?** question in Tagalog, #1 is missing the link text translation (**Subscribe to the Annie text messaging service**). I've Google translated for now.
- On the Tagalog and Spanish missing link teaser: VA's public health response: Learn more about our efforts to respond to the COVID-19 pandemic.
- Missing link to coronavirus chatbot on Spanish page

**Comment by RLHecht** [comment]
@lunascoop Here's the translated content for the debt question. 

[12324_Debt-question-update_Tagalog.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6577741/12324_Debt-question-update_Tagalog.docx)

**Comment by lunascoop** [comment]
@RLHecht I added updated the content for the debt question.

**Comment by RLHecht** [comment]
I created a word doc of the few pieces of content @lunascoop listed above that we still need translations for and sent off on 6/2.

**Comment by RLHecht** [comment]
Spanish and Tagalog pages are now published. Will send live links to translation team later today for review.

**Comment by RLHecht** [comment]
@lunascoop We just got back the translated copy for the few pieces of content you mentioned in the notes section. Could you please put these in and then I can review and publish? Thanks!

[https://app.zenhub.com/files/133843125/1b54d76d-651b-403b-9bcc-b806021422da/download](https://app.zenhub.com/files/133843125/1b54d76d-651b-403b-9bcc-b806021422da/download)

[https://app.zenhub.com/files/133843125/dd8cbfdf-29e4-4159-8e7f-e46ae8a59469/download](https://app.zenhub.com/files/133843125/dd8cbfdf-29e4-4159-8e7f-e46ae8a59469/download)

**Comment by lunascoop** [comment]
@RLHecht made the updates minus the chatbot.

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano : http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
@lunascoop We got reviewed content back from the VHA translation team. There are two updates to the Spanish page and several to the Tagalog. Could you please input them and let me know if there are any issues or we need to go back to them with any questions.

Thanks!

[https://app.zenhub.com/files/133843125/df1eb9c3-f75d-4231-a11b-e3d5c65ba33f/download](https://app.zenhub.com/files/133843125/df1eb9c3-f75d-4231-a11b-e3d5c65ba33f/download)

[https://app.zenhub.com/files/133843125/cab434fd-383c-40d0-9ca7-feccd673da64/download](https://app.zenhub.com/files/133843125/cab434fd-383c-40d0-9ca7-feccd673da64/download)

**Comment by lunascoop** [comment]
@RLHecht I've reviewed the Spanish doc and included my comments and highlights. 
[cab434fd-383c-40d0-9ca7-feccd673da64 - SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6687687/cab434fd-383c-40d0-9ca7-feccd673da64.-.SC.docx)

**Comment by RLHecht** [comment]
Thanks @lunascoop These changes have been made and the page published.

**Comment by RLHecht** [comment]
The Tagalog page is now published with changes as well. Will close after next deploy.

**Comment by RLHecht** [comment]
Final review changes are live. Closing ticket.
