### ISSUE TITLE
Update FAQs link on debt to go to new R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23777]
## Issue Description
Once our R&S article on debt relief options during COVID is published, we need to update a link on the COVID FAQs page to point to this. 

Danielle will provide text and which link we are updating. 

Note: This article is not published yet so keeping ticket in backlog for now.

## Tasks
- [x] Update content and link on FAQs page to point to new R&S article
- [x] Review and publish
- [ ] If new content, send to translation team

## Acceptance Criteria
- [x] Link going to new R&S debt article

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This work should be able to get done on Monday with the FSR launch. Could you just let us know the new text and which debt questions we're putting it in?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This can definitely get updated tomorrow so no rush needed. 

We just need to update this link:
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/1111a48e-48bc-4004-91dc-920bf42ced1e)

To go to this article now:
https://www.va.gov/resources/va-covid-19-debt-relief-options-for-veterans-and-dependents/

**Comment by RLHecht** [comment]
This has been updated and published. moving to validate and will close after next deploy.

**Comment by RLHecht** [comment]
This change is live. Closing ticket.
