### ISSUE TITLE
Update info on applying for VGLI on covid FAQs page-HOLD UNTIL JUNE

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23773]
## Issue Description
The period to apply for VGLI had been extended due to COVID. We currently give info on our FAQs page about applying through June 11, 2021. We need to check back on this date as it gets closer and rework the content.

We currently have info about it under the question "Can I have more time to apply for Veterans' Group Life Insurance (VGLI) after separation?"

## Tasks
- [x] Check if the June 11 date is changing (Danielle)
- [x] Update content based on new information (Danielle)
- [x] Review and publish (Randi)
- [ ] Send updated content to translation team (Randi)
- [x] Update Spanish page with new info (Selina)
- [x] Update Tagalog page with new info (Selina)
- [x] Review and publish Spanish page (Randi)
- [x] Review and publish Tagalog page (Randi)
- [ ] Send link to live page to VHA translation team

## Acceptance Criteria
- [x] Updated content about applying for VGLI is live on site

**Comment by RLHecht** [comment]
Just changed the date in the Spanish and Tagalog pages. The English was changed earlier but these were never updated. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
