### ISSUE TITLE
Publish guidelines re: how to contribute to the Platform Website (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23799]
# User story
As a VSP Team member, I need to know how to create and deprecate a page on the Platform Website, so that I can contribute to it (the Platform Website).

# Tasks
- [x] Amy - Schedule with Product Support and Analytics, for the end of the sprint.
- [x] Gretchen then Amy - Reconcile V1 and V2 outlines
- [x] Gretchen - Identify relevant section of outline to turn into prose.
- Turn into prose:
  - [x] Gretchen - [`Create a new page`](https://vfs.atlassian.net/l/c/15jvGxiX)
  - [x] Amy - [`Deprecate a page`](https://vfs.atlassian.net/l/c/gWiFvomV) <- placeholder name
  - [x] [`Organization`](https://vfs.atlassian.net/l/c/nGDy07uF)
  - [ ] Pair or trio - [`Publishing workflow visual`](https://vfs.atlassian.net/l/c/1nW1KvuJ)
- [ ] Pair or trio - Validate with Product Support and Analytics - rekindle collaboration around Collab Cycle and Playbook documentation in order to gauge guidelines' coherence.
- [x] Liani - Will Platform PMs be a part of SVP publishing workflow?

# Acceptance criteria
- These guidances exist:
  - Guidelines - How to create a page
  - Guidelines - How to deprecate a page
  - Visual - Publishing workflow
- Guidance can be iterated upon with Product Support's and Analytics' feedback.  This is in prep for Sprint 53 training sessions with PMs.

# Reference info
- [to-do's before we share the guidelines](https://docs.google.com/document/d/16cUk5sV7uuNIX_5D_9o0YmL_wqYGxxGoHUl8MvUOFt8/edit#)
- [V1 outline](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1242005561/Platform+website+guidelines)
- [V2 outline](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1331789975/Platform+Website+guidelines+outline)
- [Prev discussion w/ FE T from 1/25/21](https://docs.google.com/document/d/1zJTgOjOen3rcVff7WzGgbFT-_EdIfzzmjfcFkrIBic4/edit#heading=h.gm6wccppji0h)
- Platform Website
  - [Scroll Viewport site](https://depo-platform-documentation.scrollhelp.site/index.html)
  - [Confluence editor](https://vfs.atlassian.net/wiki/plugins/servlet/ac/com.k15t.scroll.scroll-viewport/k15t-vpc-overview-page?ac.siteKey=8e2b7ad5-c76a-4167-95f1-97ea2f91dfa7)

**Comment by lianilychee** [comment]
Thurs 4/29 update:
- Upon return, Amy will be taking point on the guide to deprecate on GH.  Then will pass to Gretchen.

**Comment by lianilychee** [comment]
Fri 4/30 update:
- Gretchen
  - am mostly done with the `reconcile outlines` piece
  - will update ticket with links to documents that we are working on
- Amy
  - get a good start on drafting the `deprecation how-to` - at minimum will get a skeleton
  - will wait till Monday to kick off scheduling conversations

**Comment by gmaciolek** [comment]
Docs to be written this sprint:
- [Create a new page](https://vfs.atlassian.net/l/c/zewHXvUn)
- [Archive, delete, or deprecate a page](https://vfs.atlassian.net/l/c/dUtodNSS)
- [Organization](https://vfs.atlassian.net/l/c/nGDy07uF)
- [Publishing workflow](https://vfs.atlassian.net/l/c/1nW1KvuJ)

**Comment by lianilychee** [comment]
5/3 Mon update:
- Amy
  - scheduling
  - plugging in Google Docs content into [Archive, delete, or deprecate a page](https://vfs.atlassian.net/l/c/dUtodNSS)
    - tomorrow will have draft ready for review
- Gretchen
  - will work on "Create visual of publishing workflow." task; 
    - tomorrow will have an outline of what q's the doc should answer

**Comment by lianilychee** [comment]
5/4 Tues update:
- Amy
  - scheduled with Joanne, PS still open bc of conflicts
  - will review the `Archive, delete, or deprecate page` at end of SU
- Gretchen
  - focused on audit guidelines instead, but feel optimistic bc we have momentum

**Comment by lianilychee** [comment]
5/6 Thurs update:
Amy Goldman to Everyone (10:45 AM)
For each platform website space:
1. go through “space settings - content tools” and disable the blueprint template
    1. https://dsva.slack.com/archives/CL181NRJQ/p1620237881214400?thread_ts=1620169181.210400&cid=CL181NRJQ 
2. In developing and building, go to “space settings - content tools” 
    1. Go into our templates
    2. Copy all of the content from here, add new user created templates for both, and add these templates to any spaces that don’t have them
Amy Goldman to Everyone (10:46 AM)
- Add something about this Audit Your Content doc: It’s the Platform and VFS teams to reflect the two audiences. Remove references to contract names. Swap out VSP for Platform. 5 or 4 things we’d like you to review your docs for before publishing them. Something about numbers and bullets, make sure they’re sequential steps
    - Writing best practices 
    - Edit non goals
    -  Could be a separate step in this doc, like “clean up/editorial polish/before publishing check for these 5 things”
    - See templates for that little writing guide for ideas
    - Link on the part in style guide, word list etc.
    - Stuff we commonly correct for in newsletter
    - Confluence always makes VA.gov linked. Don’t do that/not always necessary to do that. Consider taking advantage of confluence formatting to format these info panels. Use info panels to separate parenthetical notes and tips.

**Comment by lianilychee** [comment]
Mon 5/11:
- Amy: also updating all the blueprints!
