### ISSUE TITLE
KMI email #9: J&J update

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#23823]
## User story

As a Veteran, spouse, caregiver, or CHAMPVA recipient, I need to understand the latest update on the J&J vaccine and what it means for me.

## Issue Description
Send out KMI email with latest J&J update. Same email to all segments.

---
## Tasks
- [x] Draft content (Danielle)
- [x] Review content (Danielle, Lauren, Patrick, Chante, Shane, Randi)
- [x] JTF review 
- [x] Flow copy into template (Maria and team)
- [x] Review copy in template (Danielle, Lauren, Patrick, Chante, Shane, Randi)
- [x] Send email (Maria and team)

## Acceptance Criteria
- [x] Email sent
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
[KMI email 9_janseen update_draft for awareness_04.26.21](https://app.zenhub.com/files/133843125/ac40e14a-ffee-401f-83da-5e3ea39d8cf1/download)

**Comment by lalexanderson-dsva** [comment]
Honestly I think it's ok because we have the "if you haven't received your covid-19 vaccine yet." 

If they have, they don't have to worry about it, but they're getting the info anyway.

**Comment by lalexanderson-dsva** [comment]
Also - this looks great to me, @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
This looks good to me except changing "show" to "shows" in the sentence "The available data shows"

**Comment by DanielleThierryUSDSVA** [comment]
Latest version: [KMI email #9_final_04.28.21](https://app.zenhub.com/files/133843125/2409ab86-704a-4593-880c-43f526faba12/download)

**Comment by RLHecht** [comment]
work completed. Closing ticket.
