### ISSUE TITLE
TUD Hosting: Setup semantic versioning using GH Actions

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#23839]
## Issue Description
Automate "Release" and "Tag" `vsp-test-user-dashboard` repository to use semantic versioning.

*Ops team is migrating to GitHub Actions and it is preferred over other automation guides
---
## Tasks
- [x] Add GH Action for Semantic Versioning

## Acceptance Criteria
- [x] Ensures Semantic Versioning is working on `vsp-test-user-dashboard` repo
- [x] Verified by DevOps team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
