### ISSUE TITLE
TUD Hosting: Automation to push repo after tagged release

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#23840]
## Issue Description
Write a GH Action that pushes the built container to the ECR repo after "Release" is tagged & container is tagged with the semantic version

*Note: Do **not** tag as latest

---
## Tasks
- [x] Write a GH Action that pushes built container to the ECR repo on tagged "Release"

## Acceptance Criteria
- [x] Ensures pushed container actually is in ECR Repo
- [x] Ensures pushed container has a "Release" tag
- [x] Ensures pushed container has a semantic version number that is not labeled `latest`
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
