### ISSUE TITLE
TUD Hosting: Create Kubernetes Application Manifest

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#23844]
## Issue Description
Create Kubernetes Application Manifest that will be consumed by ArgoCD to kick off deployment cluster.  Reach out to Ops if any questions should arise.

---
## Tasks
- [x] Create Kubernetes Application Manifest YAML file
- [x] Create a PR on `vsp-infra-application-manifests` to add our Application Manifest to be consumed by ArgoCD
- [x] Verify configuration, namespace, and cluster are correct within ArgoCD

## Acceptance Criteria
- [x] Kubernetes Application manifest (YAML) is created
- [x] Application manifest is on the `vsp-infra-application-manifests` repo
- [x] Confirms ArgoCD is deploying the appropriate cluster (verify config, namespace, and cluster are correct).
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
