### ISSUE TITLE
TUD Hosting: Create GH Action to update app manifest

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#23846]
## Issue Description
Create a GitHub Action that updates the Kubernetes Application Manifest on the `vsp-infra-application-manifest` repo when the built ECR container for `vsp-test-user-dashboard` is pushed with a new version.

---
## Tasks
- [x] Create a GH Action that updates the app manifest when new ECR container version is pushed.

## Acceptance Criteria
- [x] The GH Action is ran when the pushed ECR container has a new version

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
