### ISSUE TITLE
Sunset Express Care

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23842]
## Summary
Eric and Steve with VAOS VAMF are coordinating the sunset of Express Care with Stakeholders.

As VAOS FE, we need to:

- [x] Turn off FE toggle - _Turned off 4/22/21_
- [x] Remove Express Care tab from homepage list
- [x] Remove Express Care code (flow, logic, etc)
