### ISSUE TITLE
CLP/Trust Staging Review Punch List 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23856]
## Issue Description
_Punch list items derived from recent staging review for CLP Trust Campaign_

Reference: Staging Review ticket #23509 

## Tasks for Launch / Post Launch 
- [x] PDF that is linked on the CLP should go through a 508 office validation review when possible.
- [ ] Accessibility Feedback: #23784 (Related to Image alt text intent)
- [x] Questions surfaced concerning 6 million survey number from QA (Peggy: Couldn't locate related ticket she mentioned)
- [x] Redirect Request #23783 (PR Submitted but need to confirm timing as a trigger from PO/PM will be required in order to implement)
- [x] a11y requested to validate link breaks in spotlight section in relation to percentages.  Recommend to put this as a list or at least do punctuation breaks when needed.

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
Adding Highlights Notes from link up with Stakeholder: 
- He was in agreement with all the feedback and will do the polish work today/tomorrow. (BTW: He says 508 office is reviewing/signing off on his PDFs)
- He would like to launch Friday -- but is willing to wait until Monday if we need to avoid Friday as a deployment day.  My take: Isn't this a content deployment and therefore we would be okay to go on Friday?  (That said, I'm not for playing it risky on this one).
- He is giving Publish/Deploy rights to me so we have one more opportunity to review everything before WE push it live.

**Comment by brianalloyd** [comment]
Items have been completed, campaign is now live.  Closing.
