### ISSUE TITLE
Set up self-hosted runner for Testing Tools team

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23862]
## Description
In order to support the Testing Tools team's efforts around[ Integration Testing to support upcoming MPI Change](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20422), they need access to a self-hosted runner that can execute GitHub actions from inside of the platform's infrastructure.  

## Background/context/resources
Self-hosted runners allow GitHub actions to execute jobs from within VA's network 
Integration Testing to support upcoming MPI change [#20422](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20422)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Set up self-hosted runner for Testing Tools team

## Definition of Done
- [x] Testing tools team can access a self-hosted runner for executing GitHub actions

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by dginther** [comment]
Self-hosted runner set up and running in the https://github.com/department-of-veterans-affairs/testing-tools repo.
![Screen Shot 2021-05-05 at 3 19 08 PM](https://user-images.githubusercontent.com/4662758/117210801-6596ce80-adb5-11eb-85ca-20f0041cfc21.png)

**Comment by dginther** [comment]
If the self-hosted runner requires more permissions, or software installed, please open a ticket with the details.

**Comment by jhouse-solvd** [comment]
Pending feedback from the Testing Tools team.

**Comment by rjohnson2011** [comment]
Thanks, in the process of verifying this has all the necessary permissions.

**Comment by rjohnson2011** [comment]
@dginther @jhouse-solvd 
A Github Action has been set up and connected to the self-hosted runner which runs a curl command to the MPI service. https://github.com/department-of-veterans-affairs/testing-tools/blob/master/.github/workflows/mpiService.yml

When the MPI service is requested using a curl command, no data comes through with the response.
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/d9184929-7a5b-4ba9-979f-f6faa635548e)
This same curl request and response works when tested on localhost behind the SOCKS proxy. Also, a non-restricted curl request (pinging google.com for instance) returns successfully, so it seems to be specific to MPI.

I've noticed some Github Actions in other repos run bash commands on a specified EC2 instance, such as this: https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/actions/run-commands-on-ec2/action.yml

Is the self hosted runner supposed to include permissions to allow these requests without connecting to an EC2 instance? If connecting to a EC2 instance is required, an instance id or target parameter seems necessary to run, such as creating instance ID `/utility/mpiService/instance`.

**Comment by joeniquette** [comment]
I wanted to ask a few questions from a security perspective about having these self hosted runners from this public repo. I'm a little concerned about having the ability to essentially make calls to MPI from github. Trevor found this article as well that I just wanted to ensure we were taking actions to mitigate the concerns here:

https://docs.github.com/en/actions/hosting-your-own-runners/managing-access-to-self-hosted-runners-using-groups there's a warning there: We recommend that you only use self-hosted runners with private repositories. This is because forks of your repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.

**Comment by rjohnson2011** [comment]
@joeniquette The Testing Tools repo is not a public repo but an internal one, meaning it is only available to members inside the DoVA organization. I understand your concerns about hosting sensitive information. Let me know if internal permissions are not sufficient and private is preferable. 

![image](https://user-images.githubusercontent.com/72466113/118505295-4b84b680-b6fa-11eb-903d-55c101be67e5.png)

**Comment by joeniquette** [comment]
This being an internal repo is better, and even though I would not prefer that all internal org personnel be able to make MPI calls, we have not communicated this enough to enforce this. You are in alignment with standard operating procedure until decisions are made around restricting these types of resources to specific teams/people.

CC: @f1337  for visibility

**Comment by jhouse-solvd** [comment]
> @dginther @jhouse-solvd
> A Github Action has been set up and connected to the self-hosted runner which runs a curl command to the MPI service. https://github.com/department-of-veterans-affairs/testing-tools/blob/master/.github/workflows/mpiService.yml
> 
> When the MPI service is requested using a curl command, no data comes through with the response.
> ![image.png](https://camo.githubusercontent.com/bef01d9e310f33754579623cca10bb219250c23efbe3bdbae37efe63b332e208/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566623430353938643036613036363731653834326136332f64393138343932392d376135622d346261392d393739662d663666616136333535343865)
> This same curl request and response works when tested on localhost behind the SOCKS proxy. Also, a non-restricted curl request (pinging google.com for instance) returns successfully, so it seems to be specific to MPI.
> 
> I've noticed some Github Actions in other repos run bash commands on a specified EC2 instance, such as this: https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/actions/run-commands-on-ec2/action.yml
> 
> Is the self hosted runner supposed to include permissions to allow these requests without connecting to an EC2 instance? If connecting to a EC2 instance is required, an instance id or target parameter seems necessary to run, such as creating instance ID `/utility/mpiService/instance`.

@dginther - not sure if this was already addressed in another thread, but wanted to make sure you saw Ryan's questions about permissions in relation to the data not coming back in a curl request.

**Comment by rjohnson2011** [comment]
@dginther and I chatted about the above over Slack in vsp-operations in this thread: https://dsva.slack.com/archives/CJYRZK2HH/p1620921375137700?thread_ts=1620837323.104800&cid=CJYRZK2HH

Tried a few options to access via the reverse proxy, which also were unsuccessful. Awaiting further guidance.

**Comment by joeniquette** [comment]
@bosawt I believe we experienced similar issues in the past, is the same? If yes, would the confluence article you wrote regarding calling MPI from a lower environment help with this?

**Comment by bosawt** [comment]
Sure, I'll post it to see if it helps, basically if you can use the cert keys from the MPI Service in vets-api, you should be able to hit the forward proxy:
https://vfs.atlassian.net/wiki/spaces/VI/pages/1077411931/MPI+Service+Testing

**Comment by jhouse-solvd** [comment]
@tskinn - it seems that the self-hosted runner/docker container is having a timeout when doing this: 

curl -k -L https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4434/psim_webservice/stage1a/IdMWebService?WSDL

I suppose the bigger question is: should the utility environment be able to reach staging... or should the runners run in the staging environment? etc... some topics to discuss

**Comment by jhouse-solvd** [comment]
to summarize, this is what's needed now: 
- we need to determine/document the endpoint that is being accessed
- determine whether we can use the revproxy to access this endpoint 
- if yes, just may need to update the endpoint
- if no, will need to add a security group rule to allow the runners to get access to the ELB that the endpoint is on

**Comment by dginther** [comment]
This is fixed.
https://github.com/department-of-veterans-affairs/testing-tools/runs/2688247656?check_suite_focus=true
