### ISSUE TITLE
Validate typeahead data / Update analytics

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#23870]
## Description

While reviewing the data from typeahead POC2 (April 12 -25) we have discovered some questions that need further exploration. 

Implement the new analytics tagging to verify typeahead click through rate

## Tasks

- [x] Add query parameter to track whether typeahead was used or not
- [x] use parameter to fill typeahead-used: in on click event

## Definition of Done

- [x] new analytics tagging allows for a GA only click through rate

**Comment by srsuddath** [comment]
PR has been merged
