### ISSUE TITLE
Add 5th Podiatry specialty code

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23895]
## Description
As a Community Care Stakeholder, I would like podiatrists associated to 5 specialty codes to show in provider list results so that Veterans can choose from a variety of approved providers.

**Background**
When Community Care Provider Selection was implemented, we could only query PPMS for 4 specialty codes per type of care. We are dependent on a change request managed by the Facilities team in order to query for 5 specialty codes per type of care.

The latest update was done in #17103

---

## Tasks

Podiatry
1-4 should already exist. 5 is new.
1. 213E00000X - Podiatrist
2. 213EG0000X - Podiatrist - General Practice
3. 213EP1101X - Podiatrist - Primary Podiatric Medicine
4. 213ES0131X - Podiatrist - Foot Surgery
5. 213ES0103X - Podiatrist - Foot & Ankle Surgery

## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag
- [ ] If user selects Podiatry type of care, provider list results match at least one of the defined speciality codes

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by laurenernest** [comment]
The FL change was released in [vets-api/v0.0.900](https://github.com/department-of-veterans-affairs/vets-api/tree/vets-api/v0.0.900). Moving our work to dev

**Comment by LanceGundersen** [comment]
@laurenernest should I be removed from here or is this the public view?

**Comment by laurenernest** [comment]
@LanceGundersen it's public view so you probably have to unsubscribe manually.

**Comment by laurenernest** [comment]
@LeKeve i'm not seeing the Foot & Ankle Surgery provider that i would've expected in the list
![23895 validation missing provider.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/1cdcbd72-9fa6-471c-9b5a-bebdb6e5f729)

**Comment by LeKeve** [comment]
@laurenernest 

What user were you using to test on staging? I'd like to take a look at the data in the console.

**Comment by laurenernest** [comment]
Jacob Reid

**Comment by LeKeve** [comment]
@laurenernest 

It looks like the correct podiatry code is being requested to the backend but it's not sending back data for the 5th code. When I remove a code and request only 4 codes (including the new code for Foot & Ankle Surgery) I see that provider in the response. 

I'll reach out to the backend team to see if they can take a look and will follow up on this ticket.

**Comment by LeKeve** [comment]
@laurenernest 

After looking in vets-api it looks like the facilities endpoint is hardcoded to only look at the first 4 specialty codes. 

[This method](https://github.com/department-of-veterans-affairs/vets-api/blob/fcb8cb4e960d14b0dbe3f6a165c9ec4c2fc6455a/lib/facilities/ppms/v1/client.rb#L161) in vets-api needs to be updated by the facilities team in order for us to query the 5th podiatry code.

**Comment by laurenernest** [comment]
The Facilities work should already be done. I created a separate ticket (#27465) to track this since this ticket has our part of the work complete. Thanks!
