### ISSUE TITLE
Cancel Button Issue on Epic #756 Texting for Medical Appointments

### ISSUE THREAD

**Issue by lichellebain** [department-of-veterans-affairs/va.gov-team#2390]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

The cancel button does not appear to clear the unsaved checked box in the pop-up. (The data does not save, so this defect is minor.)
1-	On the profile screen, start with an existing mobile number, but the text box unchecked.
2-	Click on Edit to open pop-up.
3-	Click on the text box 
4-	Click on Cancel—which takes you back to the profile page.
5-	Click on Edit to open pop-up.
6-	The text box is still checked.

I would expect that the check box would not be checked since the user pressed cancel and it was never saved.  
I am using user 220.

## Specs:
- Device: (e.g. iPhone 8, Macbook) ALL
- Browser: (e.g. Firefox, IE 11) ALL 
- Test User _(if applicable)_: ALL I used 220,226

## Steps to Reproduce
- URL: staging.va.gov
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_
Cancel button should remove the check box data upon entering the pop-up a second time.
## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by lichellebain** [comment]
@elwoodva I retested this on 10/30/19 and still have the issue.
