### ISSUE TITLE
Fix broken links on vaccine pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23909]
## Issue Description
A link to the CDC about phased implementation is no longer working. We had this link twice on the vaccine mini-hub in all three languages. We need to replace the link with this new one: https://www.cdc.gov/coronavirus/2019-ncov/vaccines/recommendations.html

## Tasks
- [x] Replace broken links on English vaccine page
- [x] Replace broken links on Tagalog vaccine page
- [x] Replace broken links on Spanish vaccine page
- [x] Publish pages

## Acceptance Criteria
- [x] No broken links appearing on live pages

**Comment by RLHecht** [comment]
These pages have been published. Moving to validate and will close after next deploy.

**Comment by RLHecht** [comment]
These pages are live. Closing ticket.
