### ISSUE TITLE
Configure Test Tools in GitHub Actions Hosted CI Pipeline for vets-website

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#23918]
## Product Outline
[Link](https://vfs.atlassian.net/wiki/spaces/VI/pages/919797773/Continuous+Integration+CI+-+Product+Outline)

**From FE Tools' plan:**
Release GHA in 2 separate phases.

1. Release GHA and simultaneously deprecate CircleCI. GHA will be an exact copy of what was in Circle, and therefore will be duplicative of what's in Jenkins. Failures in GHA will not block builds.
2. Jenkins will be set up to coordinate with GHA, and simultaneously, duplicative services will be removed from Jenkins. Failures in GHA will block builds.

## High Level User Story/ies
As a VFS team member, I need a test workflow for the GitHub Actions hosted `vets-website` pipeline so I can evaluate the integration of my changes in a timely manner.

## Hypothesis or Bet
**If** we migrate the pipeline to GHA **then** we expect the pipeline to be in better compliance with industry best practices with regards to security and efficiency of our CI solution.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 
- [x] The GitHub Actions build replicates all essential elements from CircleCI and Jenkins
- [x] The GitHub Actions build completes in a similar time to the Jenkins build
- [x] Build artifacts that were previously available in either CircleCI or Jenkins are available and discoverable in the GitHub Actions build

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
