### ISSUE TITLE
Tweak Feature Toggle Content

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23928]
## Background
Given some recent feedback from content folks, we should update our feature toggle content slightly for the CH31 feature.

## Tasks
- [ ] Update the feature toggle for CH31 on the [eligibility](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/) page as well as all the [track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/) pages

## Considerations
- Per the feedback ticket found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23122
- Here are two examples of what needs to be changed

![toggle-tweak-eligibility.jpg](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/8dd5f0c4-8d5b-47b1-87cd-c86b9422fd70)
![toggle-tweak-tracks.jpg](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/21402891-c53c-441b-902e-f064eac5766c)

## Acceptance Criteria
- [ ] The feature toggle for the eligibility page is updated
- [ ] The feature toggle for the track pages are updated
