### ISSUE TITLE
[UI] Check-in User Journey Map and Stakeholder Map

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#23933]
## Description
We need to create a map of the pre-check in, check-in, and post appointment experiences that are part of the check-in MVP, in order to understand the Veteran's journey. We also need to understand what other groups will need to be a part of check-in and what parts they will be involved in. These maps will continue to evolve throughout the project; they will just show our current understanding.

## Tasks
- [x] Create user journey map
- [x] Stakeholder/other groups map

## Acceptance Criteria
- [x] Initial draft of the journey map reviewed by product and Ming
- [x] Initial draft of the stakeholder/other groups map reviewed by product and Ming

**Comment by kristenmcconnell** [comment]
[Stakeholder and product groups involved in check-in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/stakeholders.md)

**Comment by kristenmcconnell** [comment]
The user journey that connects to wireframes for check-in can be found here: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/m18LjOk/play

**Comment by kristenmcconnell** [comment]
Completed user journey showing the check-in workflow and wireframes: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/m18LjOk/play
