### ISSUE TITLE
EKS - Set up cluster for production 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23938]
## Description
Set up production EKS cluster 

## Background/context/resources
Big items that every cluster needs 

- Cluster
- Calico
- Traefik
- DataDog
- Auto scaler - this does not come with the EKS TF
- Termination handler
- Metrics server
- External secrets  

The utility cluster is the most fully-fledged example that we have, so should be a good reference for which services are needed. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Cluster
- [x] Calico
- [x] Traefik
- [x] DataDog
- [x] Auto scaler - this does not come with the EKS TF
- [x] Termination handler
- [x] Metrics server
- [x] External Secrets

## Definition of Done
- [x] The cluster is running in prod and all necessary core services are active

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
AC updated, and requesting definition of done from @dginther

**Comment by jhouse-solvd** [comment]
The cluster is up and running. We are in the phase of adding observability and alerting before moving production loads to the cluster. This task is done. 

Closing.
