### ISSUE TITLE
VFS Reporting - Draft Solution Proposal

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#23932]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x] _Host outcomes exercise with team ideate possible solutions to provide meaningful data to VFS teams to help them know where they can improve Veterans' experiences on their sites/product._

**Salesforce data fields listed in attachment below**

## Acceptance Criteria
- [x] _VFS reporting solution proposal is documented_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
[SF-CRM-Tracking-Fields.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6394382/SF-CRM-Tracking-Fields.xlsx)

**Comment by jwoodman5** [comment]
I hosted two separate "outcomes" exercise sessions with the contact center team focused on this problem and summarized those results along with our solution proposal [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center).
