### ISSUE TITLE
HCE- MVP - Checkin Technical Discovery 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#23945]
What BE systems will this tool integrate with ? 

- [ ] Where will Veteran appointment information be retrieved from 

- [ ] How will Veteran authenticate? Is 'short' authentication such as last 4 of SS# and DOB possible bypassing full va.gov login 

- [ ] What BE systems will be written to once Veteran checks in?

- [ ] Are integrations already in place on vets API or have to be created?

- [ ] How will e2e QA happen?

Def of Done: 

- Define how to integrate

- Flow diagram of data input/output

- Tech team compositions and commitment w/estimated timeline

- Understanding of power environments 

-
