### ISSUE TITLE
Draft Plan for VEO Training

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#23946]
[not-tier-2-lesson-plan.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6455236/not-tier-2-lesson-plan.docx)
## Issue Description
_As part of our effort to improve contact center resources, we will be creating training (and related documentation) to provide oral and written training to VEO trainers_

---
## Tasks
- [x] _Outline primary necessary training to be covered in initial VEO training_
- [x] _Document initial, virtual training plan_
- [x] _Document short-term and mid-term training plan_

## Acceptance Criteria
- [x ] _Draft training plan is created_
- [x ] _Draft training plan is reviewed with contact center team_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
@Kimberley2019 , @clantosswett, Sam Abraham (VEO), Caroline Hain (VEO), and @jwoodman5 plan to discuss ideas for this project this week.

**Comment by starlow00** [comment]
Pre-closure notes: Approved by VEO. After we sit in on New Hire training, plan may be adjusted based on what we learn from those sessions involving the new Tier 1 reps.
