### ISSUE TITLE
EKS - Set up HPA for Loki 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23940]
## Description
Set up horizontal pod auto-scaling for Loki

## Background/context/resources
When a deployment reaches a particular performance threshold, HPA will either scale the deployment up or down by adding additional pods. 

## Technical notes
For more info, read here: 
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

---
## Tasks
- [x] Set up an HPA resource (thresholds for memory/CPU, etc)
- [x] Set up a request in the deployment resource (has a memory/CPU tag which describes resources needed) 
- [x] Chart or other configuration that lives in the app manifest 

## Definition of Done
- [x] HPA is working for Loki (able to scale, scaling active statuses will be attached to the HPA resource)

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@tskinn - any updates here?

**Comment by tskinn** [comment]
All done

**Comment by jhouse-solvd** [comment]
Sweet. Closing.
