### ISSUE TITLE
Authenticated Experience: Sprint 47 (5/5 - 5/18)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23944]
## Priorities

1. QA of My VA
2. ...
3. ...
4. ...

## Profile

**PM**
- [ ] TK

**Design**
- [ ] Work on tickets broken out from #19562
     - [ ] Improve UX for “remove” [contact information] button #23665
     - [ ] Determine how to handle profile’s “remove contact info” feature when user is subscribed to notifications #23666

**FE**
- [ ] Work on tickets broken out from #19562
     - [ ] Correct “edit” buttons so they are styled as buttons #23660
     - [ ] Align cancel button styling throughout profile so that all buttons look like buttons #23661

From previous sprint
- [ ] Do not try getting full name, personal info, or military info for LOA1 users #19349
- [ ] Update FAQ links and copy around what departments get updated when a veteran updates their contact info #23376

**BE**
- [ ] TK  

## My VA redesign

**PM**
- [ ] Get My VA through QA 

**Design**
- [ ] TK

**FE**
- [ ] 

## Direct deposit for EDU

**PM**
- [ ] Prep for Impact Review in May 

**FE**
- [ ] TK

**BE**
- [ ] TK

## Preferred medical facility

**PM**
- [ ] Complete test case & test user documentation NEED A TICKET

**Design**
- [ ] Complete test case & test user documentation NEED A TICKET (same as above)

## Notification Preferences

**PM**
- [ ] Samara to work on KPI planning
- [ ] VANotify/VEText coordination on MVP notifications #23349

**Design**
- [ ] TK

**FE**
- [ ] Technical discovery #22597

**BE**
- [ ] TK
