### ISSUE TITLE
Technical Discovery for Search KPIs query standardization

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#23950]
## Issue Description
How might we understand which Google Analytics data needs to be pulled into calculating funnels so that we can start to query high priority KPIs?

---
## Tasks
- [ ] Review Audit to Search standardized queries
- [ ] Update any Search standardized queries where necessary

## Acceptance Criteria
- [ ] Platform Analytics has an outline for which interaction data should go into different VA.gov funnels

**Comment by joanneesteban** [comment]
Continuation of https://github.com/department-of-veterans-affairs/va.gov-team/issues/22481

**Comment by JasonTheBearded** [comment]
[Link ](https://docs.google.com/document/d/1yDyygvUFBC7UTOZ4llSGALVL-23nw9vY3hlfpy-1bCg/)to tech discovery doc

**Comment by JasonTheBearded** [comment]
Technical discovery complete, depending on additional data pieces to come out of user feedback will circle back if need be.
