### ISSUE TITLE
COE - Feature Toggle Static and App Pages

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#23958]
## Description
We want control over how our application gets rolled out to users. We can do this by adding Flipper feature toggles to any static landing pages containing links to our application, and by adding a feature toggle to the introduction page of the application itself. 

## Considerations
- Add a new COE feature toggle [to this yml file in vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/3aee836bbecc801dc65d41638a0287cd0777c62a/config/features.yml#L11)
- Add the name of the vets-api feature toggle [to this file in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/86025a0fb43eb7ea4b338702ada8a01dc19971ce/src/platform/utilities/feature-toggles/featureFlagNames.js#L0-L1)
- If the feature toggle is a generic CTA, use the [platform provided](https://github.com/department-of-veterans-affairs/vets-website/blob/95761a99247b78f6f423d1334bee655db226e8d7/src/platform/site-wide/cta-widget/helpers.js#L1) CTA Widget by adding to the linked file.

## Tasks
- [x] Add new feature toggles as outlined under considerations
- [x] submit pull requests into vets-website and vets-api

## Acceptance Criteria
- [x] tasks are completed
