### ISSUE TITLE
Security (IAM) - Replace AmazonEC2RoleforSSM across all instance profiles

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23969]
## Description
Replace `arn:aws-us-gov:iam::aws:policy/service-role/AmazonEC2RoleforSSM with arn:aws-us-gov::aws:iam:policy/AmazonSSMManagedInstanceCore` across all instance profiles, as AmazonEC2RoleforSSM is being deprecated as per the description:

> This policy will soon be deprecated. Please use AmazonSSMManagedInstanceCore policy to enable AWS Systems Manager service core functionality on EC2 instances. For more information see https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-profile.html

## Background/context/resources
We use the AmazonEC2RoleforSSM policy in 69 roles

---
## Tasks
- [x] Modify the Terraform to replace the existing role with the new one
- [x] Apply the Terraform 

## Definition of Done
- [x] We no longer use the AmazonEC2RoleforSSM in our instance profiles

**Comment by jbritt1** [comment]
This is not closed and needs a bit more work to complete: https://dsva.slack.com/archives/CTYQL39FE/p1629480523452100

**Comment by jbritt1** [comment]
Reached out to appeals devops team about the appeals items in the shared AWS account: https://dsva.slack.com/archives/CAM9FJ85P/p1629487196154300

**Comment by jbritt1** [comment]
Reached out to lighthouse infrastructure team about dvp related items: https://dsva.slack.com/archives/C013VCQKSE7/p1629488881011300

**Comment by jbritt1** [comment]
This is now complete for VSP owned items. Remaining items have been communicated to the owning teams and linked above.
