### ISSUE TITLE
Migrate Remaining ForeSee Feedback Surveys to Medallia

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#23962]
## Issue Description
_As part of our transition to Medallia surveys, we need to migrate all ForeSee surveys to Medallia. We are starting with Feedback surveys and plan to complete our migration effort._

---
## Tasks
- [x] _Use URL list (attached here) exported from ForeSee to determine team owners of pages where ForeSee Feedback surveys are live_
- [x] _Inform teams of planned migration and gain alignment_
- [x] _Disable ForeSee Feedback surveys on staging and production and verify on page_
- [x] _Provide Sarkis (Medallia team) list of URLs to add the Medallia Feedback survey too_
- [x] _Validate Medallia Feedback survey additions on page once implementation is confirmed by Sarkis (Medallia)_

## Acceptance Criteria
- [x] _ForeSee Feedback surveys are removed from all URLs listed in attachment_
- [x] _Medallia Feedback surveys are added to all URLs listed in attachment_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
[Potential Public Websites ForeSee Surveys_JHedits.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6394379/Potential.Public.Websites.ForeSee.Surveys_JHedits.xlsx)

**Comment by jwoodman5** [comment]
Final migrations were confirmed on 5/7/21 per this attached list, which is segmented by implementation group (green 1st - week of 4/27 and yellow 2nd - week of 5/04). 
[ForeSee Surveys to Migrate to Medallia.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6455229/ForeSee.Surveys.to.Migrate.to.Medallia.xlsx)
