### ISSUE TITLE
Default title for VAMC Common links

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23974]
## Issue Description
The blue Common links box has a Title field which is not required. Defects were observed on Sheridan VAMC, initially due to content missing entirely but rendering with empty link tags on the front end. Subsequently, an editor entered link teaser content but left the title field empty. 

The immediate need was resolved by entering a title but we have an opportunity to build in a defense mechanism on the front end by determining a default title. 

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/116467603-1a1c7780-a82d-11eb-9805-8cccd5cb9040.png)

![image](https://user-images.githubusercontent.com/55411834/116467793-52bc5100-a82d-11eb-8e37-7f85ca3218b3.png)

</details>

 

<details>
<summary> Screenshots </summary>
![image](https://user-images.githubusercontent.com/55411834/110806348-36ddfb00-823f-11eb-84bc-8ca8e68b6c8a.png)

![image](https://user-images.githubusercontent.com/55411834/116295140-0225f480-a756-11eb-83b1-adc14604ebaf.png)
 

 ![image](https://user-images.githubusercontent.com/55411834/110806043-e8c8f780-823e-11eb-92cb-9bbea086bdda.png)

![image](https://user-images.githubusercontent.com/55411834/110806069-ef576f00-823e-11eb-9761-1fec28509e8c.png)
</details>

## Tasks
- [ ] Determine default title to be used when the field has not been populated
- [ ] Add default logic to FE

## Acceptance Criteria
- [ ] When the title field for Common links has not been populated, the default (TBD) title is used. 
- [ ] When the title field for Common links is populated, the value displays on the FE.
