### ISSUE TITLE
Adjust Years of Education Question (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23998]
## Background
In UAT, a participant mentioned that it was difficult to think about the total number of years of education to be entered into the VR&E form.  It would be better to to present an easy to read dropdown that spoke more to levels of education that map to numbers and pass those instead of asking for literal numbers.

### User Story
_As a Veteran, I need to provide my years of education in an easy way so that the VA can move forward with my submission._

**Further use case:** A Veteran might have graduated high school, had a few various attempts at college with some partial/complete semesters/years, but then joined the military, discharged and went back to school and completed a degree.  It's important to have the level of education and the number is hard to calculate.

## Considerations
- End result to be passed should be a 2 digit numerical value for VR&E acceptance  
- Kindergarten seems to not be a consideration
- Proposed levels to share on FE with values that should be passed in:  
  - Some high school => `10`   
  - High school / GED => `12`   
  - Some college => `14`   
  - Associate degree => `15`   
  - Bachelor's degree => `17`   
  - Master's degree or higher  => `19`   

<details>  
  <summary>Current screenshot</summary>  

![years-of-education.JPG](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/c2fa5350-1a4b-40b7-bc6e-7b06bd47005f)    

</details>

### Proposed (updated with Beth's suggestions):
**Additional Information**
What's your level of education? (*Required)
[Dropdown]
- Some high school
- High school / GED
- Some college
- Associate degree
- Bachelor's degree
- Master's degree or higher

## Tasks
- [ ] Adjust question to be a required drop down 
- [ ] Pass two digit numeric value on selection
- [ ] Update form schema
- [ ] Update unit tests
- [ ] Update e2e tests

## Acceptance Criteria
- [ ] Question is adjusted
- [ ] Form schema is updated
- [ ] Unit tests are updated
- [ ] e2e test are updated
- [ ] Values are passed in successfully based on listing above
- [ ] A PR has been requested for merging

**Comment by bethpottsVADEPO** [comment]
@jason-gcio Per our site style: 

- Uppercase only the first words on each line
- Change "What is" to "What's" for plain language/conversational tone
- Add "degree" to "master's" and change "or beyond" to "or higher"
- Remove "or similar" after "bachelor's degree" (unless there's something I don't know, which is entirely possible, I don't think there is anther kind of 4-year degree that's equivalent to a bachelor's degree)

Additional Information
What's your level of education? (*Required)
[Dropdown]

Some high school
High school / GED
Some college
Associate degree
Bachelor's degree
Master's degree or higher
