### ISSUE TITLE
Add Veterans Service Officer to style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23996]
## Issue Description
We need to add the term Veterans Service Officer (VSO) to the style guide so that it's clear we cap it.

## Tasks
- [x] Add to style guide (Randi)
- [x] Review PR (Beth/Danielle)
- [x] Merge PR (Randi/Beth/Danielle)

## Acceptance Criteria
- [x] Veterans Service Officer (VSO) is in live style guide

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I added you as a reviewer to the PR for this: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/439

**Comment by RLHecht** [comment]
Live in style guide. Closing ticket.
