### ISSUE TITLE
Remove Cleveland as Pilot RO (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24004]
## Background
Now that the Cleveland RO pilot is pushed back to May 10, we need to remove it from the [RO model](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/veteran_readiness_employment_claim.rb#L9) until then.

## Tasks
- [ ] Remove Cleveland from being submitted to

## Acceptance Criteria
- [ ] CMS is not taking any submissions 
- [ ] A PR has been submitted for merging

**Comment by jason-gcio** [comment]
Consider removing this as it will need to be reversed almost immediately
