### ISSUE TITLE
Data Points Needed for Banner In-Take Request Build

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#24018]
## Issue Description
_Jump starting a ticket to review data points needed for the new "Banner In-Take Request form for creation.  Would like to review both what items are needed for the form (What do we need to know) but also the associated timing (when do we need the request, how long to work implementation and review/stage/preview/prod workflows).  Please include any details associated with "Adhoc/Emergency requests that might be needed for last minute requests"_

## Tasks
- List recommended (Required) data points needed for a Banner Implementation
- List recommended for associated timeline from request review to release on prod.  
- Review the data with PW team (Ensure accuracy and consensus on details)
- Build In-Take request form 
- Review and advise with VA stakeholders and VSA(VFS teams) for use 

## Acceptance Criteria
- [x] Turn-key Banners in-take request that can be leverage forward in an effort to streamline banner requests and banner rubric forward.

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
Banner intake request template:

# Description

[Write a brief description with the context of the request. Feel free to add any additional info here if you need to.]

## What do you need?

Choose one of the following and make sure you fill out at least the required details for it.

- [ ] Homepage banner
  *(required)*
  - `startsAt`: [What is the exact time we should show it? (Remember to include the timezone) e.g. '2020-06-09T14:00:00.014Z' or 'Immediately']
  - `expiresAt`: [What is the exact time we should stop showing it? e.g. 24 hours AFTER it starts showing]
  - `title`: [What will the title of the homepage banner be?]
  - `content`: [What will the content of the homepage banner be? Feel free to use HTML if desired.]
  
- [ ] Maintenance Banner
  *(required)*
  - `startsAt`: [What is the exact time we should show it? (Remember to include the timezone) e.g. '2020-06-09T14:00:00.014Z']
  - `expiresAt`: [What is the exact time we should stop showing it? e.g. 24 hours AFTER it starts showing]
  - `title`: [What is the title? _Default_: 'Site maintenance']
  - `content`: [What is the content? _Default_: "We’re working on VA.gov right now. If you have trouble signing in or using tools, check back after we're finished. Thank you for your patience."]

  (optional)
  - `warning startsAt`: [Do you want to show a warning before the downtime happens? If so, how much time before we show the maintenance banner should we show the warning? e.g. 12 hours BEFORE it starts showing]
  - `warning title`: [What should the warning title be? _Default_: 'Upcoming site maintenance']
  - `warning content`: [What should the warning content be? _Default_: 'We’ll be doing some work on VA.gov. The maintenance will last x hours. During that time, you won’t be able to sign in or use tools.']

- [ ] Promo Banner
  *(required)*
  - `startsAt`: [What is the exact time we should show it? (Remember to include the timezone) e.g. '2020-06-09T14:00:00.014Z' or 'Immediately']
  - `expiresAt`: [What is the exact time we should stop showing it? e.g. 24 hours AFTER it starts showing]
  - `link url`: [The URL where a user is navigated to if they click the promo banner.]
  - `content`: [The text on the promo banner announcement.]

## Stakeholders

Who specifically should we communicate with when building + deploying the banner?

**Comment by kelsonic** [comment]
Template created [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/banner-intake-request.md), ready for validation + closing 🙂

**Comment by brianalloyd** [comment]
Validated, recommendation was to add visual screenshots.  Added for promo + homepage, now just need to add visual screenshot for maintenance banner and should be complete.

**Comment by brianalloyd** [comment]
Completed, Closing.
