### ISSUE TITLE
 Security - Update design & documentation for SSM Parameter store hierarchy (groups/permissions) 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#24025]
## Description
We need to more clearly identify the best hierarchy for assigning permissions to groups based on organization and/or capabilities. The idea is to have a very clear structure that grants permissions to individuals based on the membership of their team. 

## Background/context/resources
https://vfs.atlassian.net/wiki/spaces/VI/pages/1021935643/SSM+Hierarchy

## Technical notes
Interesting concepts to explore with paths, tags, etc 

---
## Tasks
- [x] Create groups that reflect the team structure / org chart of VSP/VFS 
- [x] Create policies in AWS that define various levels of access to AWS resources - for example, read access to a particular path in parameter store (which would give someone the ability to look up the value of a secret)
- [x] Update the documentation to more accurately reflect the current reality 

## Definition of Done
- [ ] There will be a better design for groups and associated permissions boundaries 

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by dginther** [comment]
This is complete.
Groups are defined here: https://github.com/department-of-veterans-affairs/devops/terraform/environments/global/iam_gha_resources.tf
Permissions are defined in the same file.
