### ISSUE TITLE
Homepage Refresh-recommended foundational accessibility checklist

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24021]
## Scope
- homepage appointment lists
- each appointment type detail page
- includes alert modals

## Tasks
Complete required accessibility checklist items for staging review and check off items as they are completed:
- [x] Screen reader tests (VoiceOver + Safari or NVDA + Firefox) - [read more about getting started with screen readers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests).
- [x] Axe-coconut scans in daily development - [read more about the axe-coconut experimental plugin](https://www.deque.com/blog/test-leading-edge-accessibility-axe-coconut-axe-core-3-0/)
- [x] WAVE tool spot checks - [read more about the WebAIM WAVE tool](https://wave.webaim.org/)

## Definition of Done
- [x] Issues found are documented in separate tickets and linked to this ticket
_(Note- instructions for creating tickets can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/scrum-team/how-to-create-vaos-tickets.md#accessibility-issues-questions-or-recommendations))_

**Comment by LeKeve** [comment]
- Screen reader tests completed with VoiceOver/Safari. 
- Created a ticket for including axe best practice scans in all of our e2e tests
- Wave tool check completed on all pages with screenshot below. No major issues on all pages (The 1 error is from a modal outside of VAOS). There was a minor issue with redundant `Detail` links which I did not create a ticket for since each appointment is separated into its own block. Trevor may note this and have further guidance on copy changes.

![Screen Shot 2021-05-21 at 6.19.42 AM.png](https://images.zenhubusercontent.com/5fb2c17a7bedf7598b0e96f2/a6f37ca4-1447-4ef7-ba8a-2d26ca69a7e6)
