### ISSUE TITLE
Homepage Refresh-required foundational accessibility checklist

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24020]
## Scope
- homepage appointment lists
- each appointment type detail page
- includes alert modals

## Tasks
Complete required accessibility checklist items for staging review and check off items as they are completed:
- [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
- [x] Axe scans in daily development - [read more about the axe browser plugin](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
- [x] Axe scans included in end-to-end (e2e) tests - [read more about e2e tests with axe checks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
- [x] Color tests for proper contrast and colorblindness - [read more about contrast and colorblindness](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)
- [x] Content zoomed to 200%, 300%, 400% - [read more about zoomed layouts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
- [x] Keyboard navigation - [read more about navigating with the keyboard](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)

## Definition of Done
- [ ] Issues found are documented in separate tickets and linked to this ticket
_(Note- instructions for creating tickets can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/scrum-team/how-to-create-vaos-tickets.md#accessibility-issues-questions-or-recommendations))_

**Comment by jenniemc** [comment]
Found and will document issues encountered during the Axe scan test, color test, keyboard navigation, and mobile size screen test. The remaining zoom test and Cypress (e2d) Axe test still needs to be performed. cc @LeKeve, @jbalboni

**Comment by LeKeve** [comment]
Completed zoom tests and verified references to axe checks in all end to end tests. Closing ticket.
