### ISSUE TITLE
Publish updated burial at sea page for stakeholder

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24045]
## Issue Description
Stakeholder Rob Benson updated a broken link and added aria labels to a phone number on the burial at sea page. We need to review his changes and publish the page.

Page worked on: https://www.va.gov/burials-memorials/eligibility/burial-at-sea/

## Tasks
- [x] Review changes made (Randi)
- [x] Publish page (Randi)

## Acceptance Criteria
- [x] Live page has updated link and aria labels

**Comment by RLHecht** [comment]
Ticket created for tracking purposes. Work done and closing ticket.
