### ISSUE TITLE
[ANALYTICS] Create new Health Services "LIST and PLAYBOOK" for VA Maine health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24050]
## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## Goal
_Data collection and mining required for System Health Services and Facility Health Services and staff profiles for caregivers

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[ Maine healthcare system Legacy Site](https://www.maine.va.gov)
[Playbook template](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[VISN-1 Playbook locations](https://drive.google.com/drive/folders/1EySmpu7JIQqshPRA-B5MMXxhK8pecf73)

## TASKS: Scrape, list, and convert all of the health services for the following sites on individual tabs in Playbook for System:
- [x] Togus VA Medical Center
- [x] Caribou VA Clinic
- [x] Calais VA Clinic
- [x] Rumford VA Clinic
- [x] Saco VA Clinic
- [x] Lewiston VA Clinic
- [x] Lincoln VA Clinic
- [x] Bangor VA Clinic
- [x] Portland VA Clinic
- [x] Bingham VA Mobile Clinic
- [x] Fort Kent VA Clinic
- [x] Houlton VA Clinic

## Definition of Done-Acceptance Criteria
- [x] Validated list of all SYSTEM and FACILITY Health Services_
- [x] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for ALL the Above sites:
- [x] Include cross-reference A-Z Index tab for PAO to review and use
- [ ] Assure that playbook can be transformed into .csv file for upload into CMS system by Backend Engineer

**Comment by bcastoe** [comment]
Changed Bingham Access Point to Bingham VA Mobile Clinic
