### ISSUE TITLE
Set up GitHub Actions Slack notifications

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#24055]
## Description
We need to be able to post to arbitrary slack channels from Github Actions.  
Github has no plans currently to add this functionality to the github integration they already offer: https://github.com/integrations/slack/issues/940 so we are on our own to make this work.

I think the best way forward here is to build a new Slack App with incoming webhooks functionality to receive the messages.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] _Create Slack App_
- [x] _Configure permissions for slack app to allow posting to arbitrary channels_
- [x] _Put slack webhook tokens into Parameter Store in appropriate locations_
- [x] _Write documentation which describes how to send a slack message from a github action_

## Definition of Done
- [x] _Documentation is written for how to utilize the Slack App_
- [x] _Webhook tokens are created and distributed to Parameter Store_
- [x] _Teams are able to send a slack notification from within a GHA workflow_

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@dginther to ask slack admins whether or not the app can be re-configured to speak to multiple channels, which might be the easiest path forward with the least amount of effort

**Comment by meganhkelley** [comment]
Adding our team's label just so that we can keep an eye on this progress!

**Comment by dginther** [comment]
I have built a github action to perform the slack message sending. https://github.com/dginther/github-actions/slack-socket

I added an application to our DSVA slack configured to use Websockets instead of a public URL.

I put the app token and the bot token in Parameter Store
- /devops/github_actions_slack_bot_user_token
- /devops/github_actions_slack_socket_token

I will need to give permissions to the other team's service accounts to read that parameter.
I will write documentation.

**Comment by jhouse-solvd** [comment]
@dginther - would you find it useful for me to create a new ticket for the documentation so that we can consider this one done?

**Comment by timwright12** [comment]
This is done, right?

**Comment by jhouse-solvd** [comment]
@timwright12 - technically speaking, yes. I think all that we need is a link to "Documentation is written for how to utilize the Slack App", which would help support the definition of done. :)

**Comment by jbritt1** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595275/Slack+Notifications+from+Github+Actions

**Comment by dginther** [comment]
Closing, complete.
