### ISSUE TITLE
MPI User Fields Validator

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#24065]
## Issue Description
Parent Story: #23220
In order to prevent errors caused by improperly formatted user attribute data in MPI we should validate that user data in vets-api before it is sent. As the Identity team is already in the process of creating a new Ruby gem to handle vets-api's interactions with MPI the most logical place to include this user attribute validation logic is within the built-in Rails validation functionality for that gem.

The most important fields to be validated are the `first_name`, `middle_name`, and `last_name` fields, specifically for the following characters: `|\/<>(){}[]`. Basic SSN validation should also be added, and we are remaining in contact with Danny Reed should the need to add validations for additional fields arise.

---
## Tasks
- [x] Determine which fields need validation & what appropriate validation rules
- [x] Add Rails validations to newly created MPI gem classes to cover a user's `first_name`, `last_name`, and `middle_name` attribute, limiting them to 25 (35 for `last_name`) characters and preventing the inclusion of `|\/<>(){}[]` characters
- [x] Add Rails validations for `ssn`, requiring exactly 9 numeric characters
- [x] Add Rails validations for `gender`, requiring `M` or `F`
- [x] Unit tests added/expanded to cover validations

## Acceptance Criteria
- [x] A user will not be able to submit name field data to MPI that is too long or contains improper characters
- [x] A user will not be able to submit ssn field data to MPI that is less than or greater than 9 characters or contains non-numeric characters

**Comment by bramleyjl** [comment]
Further development is blocked pending a definite list of validation specifications from the MPI team.

**Comment by bramleyjl** [comment]
Initial validation information, based off of Section 5.4 (page 15) of the [MPI Service Document](https://dsva.slack.com/files/U01EU9G6ABD/F021562NP3R/va_mpi_service_description.pdf):

The following are attributes contained within the `user_identity` object that is used to build the SOAP request to MPI:

Validation Information found:
-    @birth_date= "Date" (assume this means YYYY-MM-DD format?)
-    @first_name= String 25
-    @gender= M/F/TM/TF/O(other)/I(chooses not to answer) (matches to Self Identified Gender field in MPI?)
-    @last_name= String 35
-    @loa= "Value" 1 - 4 (our format: `{:current => X, :highest => X}`)
-    @middle_name= String 25
-    @ssn= "Numeric" 9 (we send string)
-    @zip= String 6-11 (we send 5, not a problem?)

Validation information not found:
-    @authn_context ("http://idmanagement.gov/ns/assurance/loa/3/vets")
-    @birls_id
-    @common_name ("Preferred Name"?)
-    @dslogon_edipi
-    @email
-    @errors
-    @icn
-    @idme_uuid
-    @mhv_account_type
-    @mhv_correlation_id
-    @mhv_icn
-    @multifactor
-    @participant_id
-    @persisted
-    @sec_id
-    @sign_in
-    @uuid
-    @validation_context

**Comment by bramleyjl** [comment]
Updated specs following conversation with Danny Reed @ MPI

-    @birth_date= YYYY-MM-DD
-    @first_name= String 25
-    @gender= M/F
-    @last_name= String 35
-    @middle_name= String 25
-    @ssn= String 9 (numbers only)

Additionally for the name fields the special characters `|\/<>(){}[]` should not be accepted. Hyphens `-` and apostrophes `'` should be allowed.

**Comment by bramleyjl** [comment]
This work is being included in the ongoing [MPI Gem](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/24454) rework and is planned to be completed in Sprint 53.

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/ruby-mpi/pull/8
