### ISSUE TITLE
[FE] My VA: Compile technical documentation for privacy and security review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24060]
## Background
We have several artifacts to gather and questions to answer in order to submit our privacy and security review request for My VA. The plan is for @ajakabcin to be able to submit and complete this request in sprint 48.

See [*What artifacts do I provide?*](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-privacy-security-review.md#what-artifacts-do-i-provide) section for reference in the [Privacy and Security review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-privacy-security-review.md) documentation.

## Tasks
- [x] Create technical diagrams in GH for the following:
     - [x] An architecture diagram, showing involved systems and how they connect
     - [x] For non-trivial flows (i.e. more than a single round-trip call from frontend → `vets-api` → VA Backend), a sequence diagram showing the ordered flow of data and operations between systems
- [x] Assist AJ in answering the questions in the [privacy and security/readiness review ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/271)

**Comment by erikphansen** [comment]
I'm not sure what is needed for this ticket so I am holding off on an estimate.

**Comment by lihanli** [comment]
![diagram](https://user-images.githubusercontent.com/830084/118527092-c8f9f800-b6f5-11eb-8332-3462912841ca.png)
here is the architectural diagram. i don't think there are any non-trivial flows that require sequence diagrams.

**Comment by ajakabcin** [comment]
Thanks again @erikphansen and @lihanli for your help on this - closing!
