### ISSUE TITLE
Set up Platform projects in BigQuery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#24077]
## Issue Description
As more Platform teams build dashboards in Domo, they'll be piping data through BigQuery. To keep better track of datasets and to keep the data more clean, Analytics will be looking into creating additional projects in BigQuery.

---
## Tasks
- [ ] Determine if we need new projects in BigQuery
- [ ] If we decide there should be new projects, determine how many and for which teams 
- [ ] Add billing
- [ ] Set up project spaces
- [ ] Share with appropriate Platform team members
- [ ] Document process for future 

## Acceptance Criteria
- [ ] Understand how Platform teams can use BigQuery to pipe data
- [ ] Provide Platform teams access to pipe data
- [ ] Analytics understands how to support other Platform teams with BigQuery datasets

**Comment by joanneesteban** [comment]
Discussion on 1 service account for everybody:
- Create 1 service account for every team
- Spin up a key for each team's service account when new folks request access

That way, we:
- Have tracking on who uses the accounts
- Can expire individual keys

**Comment by bsmartin-ep** [comment]
I created a test GCP project (no organization) for the platform teams.

**Project name**
va-platform-teams-1

This was accomplished by using my @va.gov email to create the project, since it is attached to a Google account, but not a Google Workspace or Cloud Identity organization. 

From what I understand, we are still blocked on billing.  Current requests are being given separate datasets on our existing GCP project.

**Comment by bsmartin-ep** [comment]
This is not possible unless the VA created an Organization for the GCP projects.  As they do not want to start using Google Workspace or IAM, this will not be possible.  

Closing.
