### ISSUE TITLE
[BUG] Zone One / quadrant tracking on home page missing heading and click text

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#24078]
The "Zone One" links on the home page...

![image](https://user-images.githubusercontent.com/62304138/116757603-62c66300-a9dc-11eb-87ba-f5bbd23319f0.png)

...[only record the click URL](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=zone%20one/).

`Navigation - Zone One - ->/claim-or-appeal-status`

Because we have several links that share URLs (and Click Text even), we need to add Click Text and Heading to differentiate.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:  www.va.gov
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by bsmartin-ep** [comment]
This is ready for QA at your leisure @laurensimpson14.

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000511

Changes:

- Added `click-text` and `heading` datalayer variables.  I think it's a good idea to start making these more generic.
- Attached new datalayer variables to `nav-zone-one` event in lookup table
- Deleted extra, unused `nav-path` datalayer variable

Let me know if you have any questions.

**Comment by bsmartin-ep** [comment]
I forgot to mention @laurensimpson14 , you'll need to use the build in the PR with your SOCKS proxy.  

https://github.com/department-of-veterans-affairs/vets-website/pull/17033

It's expired now, so let me regenerate it for you.

**Comment by bsmartin-ep** [comment]
Published and collecting data....

![image](https://user-images.githubusercontent.com/62304138/118822574-47859f80-b886-11eb-9a10-7e4929cf26c2.png)

Closing.
