### ISSUE TITLE
Add new sentence to J&J alert 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24074]
## Issue Description
We need to update the second sentence in the Janssen blue box on the vaccine page to the following:

We’ll provide this vaccine—along with the Pfizer-BioNTech and Moderna COVID-19 vaccines—to Veterans, spouses, caregivers, and CHAMPVA recipients who are at least 18 years old.

This content will need to be translated as well so it can be put onto the Tagalog and Spanish vaccine pages.

## Tasks
- [x] Add sentence to English page
- [x] Review and publish
- [x] Send text to translators
- [x] Add translated text to Tagalog and Spanish pages
- [x] Review and publish Tagalog and Spanish pages
- [x] Send live links to VHA translation team

## Acceptance Criteria
- [x] New sentence is live on English, Spanish, and Tagalog pages

**Comment by lunascoop** [comment]
@RLHecht This page is ready for review

COVID-19 vaccines at VA: http://preview-prod.vfs.va.gov/preview?nodeId=11463

**Comment by RLHecht** [comment]
Thanks, @lunascoop ! I published the page and sent the text to the translators.

**Comment by RLHecht** [comment]
@lunascoop Here are the translations back. Thanks!

[https://app.zenhub.com/files/133843125/d1c686a4-a8ed-4b9e-b77f-7f457836ca87/download](https://app.zenhub.com/files/133843125/d1c686a4-a8ed-4b9e-b77f-7f457836ca87/download)

[https://app.zenhub.com/files/133843125/e563d4e5-1d62-4d87-a90d-44dfd0f0ff3e/download](https://app.zenhub.com/files/133843125/e563d4e5-1d62-4d87-a90d-44dfd0f0ff3e/download)

**Comment by lunascoop** [comment]
@RLHecht These pages have been updated and are ready for your review.

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by RLHecht** [comment]
These pages are live. Closing ticket. Will reopen if Mateo comes back with any changes.
