### ISSUE TITLE
Update Collab Cycle docs to remove "VSP" and replace with "Platform"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#24073]
## Issue Description
OCTO-DE would like us to no longer use our contract name in documentation and instead say "Platform."

\*Please note that the github folders "working-with-vsp" and "vsp-collaboration-cycle" will not be renamed at this time because then all links would break.
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/a338284a-c610-4bc8-ab8a-e8c41f2be10e)
---
## Tasks
- [x] [VSP Collaboration Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York) is renamed to Platform Collaboration Cycle Calendar.
- [x] "VSP" is replaced with "Platform" in the following github pages:
   - [x] READ.me
   - [x] Getting Started
   - [x] Design Intent
   - [x] IA Request
   - [x] Analytics Request
   - [x] Research Plan Review (no mention of VSP)
   - [x] Midpoint Review
   - [x] Contact Center Review (no mention of VSP)
   - [x] Staging Review
   - [x] Privacy & Security Review
   - [x] Full Accessibility & 508 Audit
   - [x] Post-Launch Check-In (no mention of VSP)
   - [x] CC Kickoff Issue template
   - [x] Design Intent issue template
   - [x] IA Request issue template
   - [x] Analytics Request issue template
   - [x] Midpoint Review  issue template
   - [x] Contact Center Review issue template
   - [x] Staging Review issue template
   - [x] Privacy & Security Review issue template (this template has moved to va.gov-team-sensitive respository)
   - [x] Full Accessibility & 508 Audit issue template

## Acceptance Criteria
- [ ] Collaboration Cycle documentation no longer makes any reference to "VSP"
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
hey @peggygannon  - this is not urgent. Also, most of this request is contingent upon me to get the calendar renamed. I'll let you know once that's complete.

**Comment by shiragoodman** [comment]
hi @peggygannon  - the VSP calendar has been renamed to "Platform Collaboration Cycle Calendar" as seen [here.](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)

**Comment by peggygannon** [comment]
peggygannon-patch-2

**Comment by shiragoodman** [comment]
hey @peggygannon - thanks for reminding me of this! I reviewed all PRs and everything looks good. There are a couple comments, but nothing critical. Please review and merge when ready.
