### ISSUE TITLE
Add content to COVID FAQs around VRRAP

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24095]
## Issue Description
Now that the VRRAP landing page and form are live, we need to add a blurb on the COVID FAQs page pointing users to the new page. 

We can take the content from the landing page but need to figure out where on the FAQs page it should be placed.

VRRAP page: https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/

---
## Tasks
- [x] Determine language and where on FAQs page content should go
- [x] Update FAQs page
- [x] Review and publish
- [x] Send text to translation team 
- [x] Update Spanish and Tagalog pages
- [x] Review and publish Spanish and Tagalog pages
- [x] Send live links to VHA translation team to review
- [x] Update chatbot

## Acceptance Criteria
- [x] New content and link to VRRAP page is on live FAQs page

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here's my suggested content. Let me know what you think and Selina can add it in. I wasn't sure if we wanted to link to both our page and the form but I put them both in there. And let me know if you think we need to add more than just the intro text I used.

To be placed in an accordion in the current benefits and payments section:

**What happens if I've lost my job due to COVID-19?**

You may be eligible for the Veteran Rapid Retraining Assistance Program (VRRAP). VRRAP offers education and training for high-demand jobs to Veterans who are unemployed because of the COVID-19 pandemic. 

[Find out if you're eligible for VRRAP](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/)

[Apply for VRRAP education benefits](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Placement is great! And I think you have just the right amount of content here before linking off. 

I think, especially since this is a new program, we'll want people to read eligibility info first. So let's just include the first link and make it:

Find out if you're eligible and how to apply for VRRAP

And then, let's make the question something a little more specific, such as:

If I lost my job due to COVID-19, can I get job training help from VA?

@bethpottsVADEPO Any thoughts on this since you created the VRRAP page?

**Comment by bethpottsVADEPO** [comment]
I'd also include "education" in that question:

If I lost my job due to COVID-19, can I get education or job training from VA?

**Comment by DanielleThierryUSDSVA** [comment]
Great! @RLHecht Want to update and publish? And then, of course, translations + chabot.

**Comment by lunascoop** [comment]
@RLHecht I've updated the FAQs page

- Coronavirus FAQs: What Veterans need to know: http://preview-prod.vfs.va.gov/preview?nodeId=3014

**Comment by RLHecht** [comment]
Thanks, @lunascoop! I published the page and sent the text to the translation team.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop! We received this VRRAP content back from the translation team Could you please incorporate into the Spanish and Tagalog pages?

[12525_VRRAP COVID FAQs question 5621 Spanish LL Final](https://app.zenhub.com/files/133843125/ba6a4613-ee3d-4039-9f23-c9707909e98e/download)

[12524_VRRAP COVID FAQs question 5621 Tagalog Final](https://app.zenhub.com/files/133843125/e375d095-4da2-49eb-8a2f-9b62f2da1840/download)

Also, could you confirm if you've updated the chatbot per Randi's note above? Checking in while Randi is out. Thanks!

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA will do. I did update the chatbot per ticket [#24456 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24456#issuecomment-838345954)and the changes are live.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome - thank you for confirming, @lunascoop!

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA @RLHecht These updates, along w/ the ones for ticket [#23761](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23761#) are ready for review. See my detailed notes in the related ticket.

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano : http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
work completed. Closing ticket.
