### ISSUE TITLE
[Tech-Debt] Return to VISN-17 and replace original Policies Page with New page [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24104]
## Story
As a VHA Digital Media manager, I need the ability to update all site policies page with national content, so I need a Nationalized/hardened policies page loaded at each site.

## Goal
Swap out current policies page with new hardened page to provide VHA DM the ability to update national content.

## TASK
_Update the following sites with the new policies page in the following order:
1) Open up current policies page and rename it Policies - Old
2) Remove Menu link, and save page as "Archived"
3) Clone Policies page from VA Hudson Valley, Scaffold the page to match the site you are cloning [i.e. VISN-17 System]
4) Add menu link under "About VA [System name]
**For the following systems** 
(Communicate within team to complete systems)
- [x] VA Amarillo health care
- [x] VA Central Texas health care
- [x] VA North Texas health care
- [x] VA South Texas health care
- [x] VA Texas Valley health care
- [x] VA El Paso health care
- [x] VA West Texas health care

## Acceptance Criteria
- [x] All systems policies pages have been updated to new hardened page.
- [x] All old policies pages have been renamed and archived.

**Comment by lealester** [comment]
Lea completed: Texas Valley, North Texas, El Paso, & Amarillo VA Healthcare Systems

**Comment by EdwardBoehme05** [comment]
Ed completed for Central Texas, South Texas, and West Texas.
