### ISSUE TITLE
[Tech-Debt] Create new Progams, Research, and Doing Business with detail pages in draft for future use [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24106]
## Story
As a System PAO, I need a location to nest all of my specialty programs and research pages in my system website.

## Goal
Provide a place for future pages to be built and reside in the Systems. 

## Tasks
_Create Three (3) new pages and archive them so they can be released at a later time.
1) Clone Programs page from Source of Truth, and update and scaffold to match current system.
2) Add Programs page to Menu under "About VA [System] Name and disable the menu items - Save as draft.
3) Clone Research page from Source of Truth, and update and scaffold to match current system.
4) Add Research page to Menu under "About VA [System] Name and disable the menu items - Save as draft.
5) Clone Doing business with us from Source of Truth, and update scaffold to match current system.
6) Add Doing business with us page under "Work with us", disable the menu items - Save as draft. 
7) Assure all  pages are saved as "Draft" (Archive will only be used on systems not in Dual State)
_
**Complete for the following VISNs and systems**
**VISN-4**
- [x] Altoona 
- [x] (Butler)Abie Abraham VA Health Care Center (HCC)
- [x] Coatesville 
- [x] Erie 
- [x] Lebanon 
- [x] Pittsburgh 
- [x] Philadelphia 
- [x] Wilkes-Barre 
- [x] Wilmington 
_
**VISN-19**
- [x]  VA Cheyenne health care
- [x]  VA Eastern Colorado health care
- [x]  VA Western Colorado health care
- [x]  VA Montana health care
- [x]  VA Eastern Oklahoma health care
- [x]  VA Oklahoma City health care
- [x]  VA Salt Lake City health care
- [x]  VA Sheridan health care
_
**VISN-6**
- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care
_
**VISN-16**
- [x] VA Alexandria health care
- [x] VA Central Arkansas health care
- [x] VA Fayetteville Arkansas health care
- [x] VA Gulf Coast health care
- [x] VA Houston health care
- [x] VA Jackson health care
- [x] VA Shreveport health care
- [x] VA Southeast Louisiana health care
_
**VISN-21**
- [x] VA Central California health care
- [x] VA Northern California health care
- [x] VA Pacific Islands health care
- [x] VA Palo Alto health care
- [x] VA San Francisco health care
- [x] VA Sierra Nevada health care
- [x] VA Southern Nevada health care
_
**VISN-23
- [x] VA Black Hills health care
- [x] VA Central Iowa health care
- [x] VA Fargo health care
- [x] VA Iowa City health care
- [x] VA Minneapolis health care
- [x] VA Nebraska-Western Iowa health care
- [x] VA Sioux Falls health care
- [x] VA St Cloud health care

## Acceptance Criteria
- [x] Research, Programs, and Doing business with us pages have been cloned, scaffold, menus created as disabled, and saved as "Draft"

**Comment by bcastoe** [comment]
Changed Acceptance Criteria from - [ ] Research, Programs, and Doing business with us pages have been cloned, scaffold, menus created as disabled, and saved as "Archived" to - [ ] Research, Programs, and Doing business with us pages have been cloned, scaffold, menus created as disabled, and saved as "Draft"

**Comment by bcastoe** [comment]
(1) Changed acceptance criteria to reflect draft vs archived to stay with steps listed in tasks
(2) VISN 23
  - Black Hills: No HR# listed for HR - Doing business with us with "Please call Human Resources at Coming Soon"
  - Central Iowa: No HR # listed for HR -  Doing business with us with "Please call Human Resources at Coming Soon"
  - Minneapolis: did not clone Programs page or Research page as already had
  -  St Cloud: did not clone Programs page or Research page as already had
(3) VISN 21
  - Northern California: has two campus names and HR #'s listed - only listed the #'s not the campus names on Doing business with us page
  - Pacific Island: No HR # listed for HR -  Doing business with us with "Please call Human Resources at Coming Soon"
(4) VISN 16
  -  Alexandria: No HR# listed for HR - Doing business with us with "Please call Human Resources at Coming Soon"
  - Central Arkansas: did not clone Program page as already had
  - Shreveport: No HR# listed for HR - Doing business with us with "Please call Human Resources at Coming Soon"
(5) VISN 6
  -  Fayetteville Coastal: No HR# listed for HR - Doing business with us with "Please call Human Resources at Coming Soon"
(6) VISN 19
  - Salt Lake City: did not clone Programs page as already had
(7) VISN 4
  - Philadelphia: did not clone Research page as already had
  - Pittsburgh: did not clone Programs & Research as already had - also did not clone Doing business with us
  - Wilmington: No HR# listed for HR - Doing business with us with "Please call Human Resources at Coming Soon"

#24106 [Tech-Debt] Create new Progams, Research, and Doing Business with detail pages in draft for future use [BA] - Completed and moved to validate
