### ISSUE TITLE
Search Reorganization - User Flow Improvements

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#24117]
## Tasks: 

- [x] Reach out to Search.gov to see if there is a health endpoint for the results API 
  -  If yes, possibly disable search / show "search is down" message when a user attempts to search
  -  If no, explore implementing a health check on the search service in the background to enable some of the above ^^

    > **As per May 11 Search.gov response:** "We don't have a health check endpoint from the status page, but one creative solution another partner from VA (Boris Ying, if you work with them) had is to use Github's RSS feed for commits to be alerted whenever we update our Status page (link to the feed is here: https://github.com/GSA/search-gov-website/commits/master/_posts/2021-01-11-status.md.atom). We'll make sure our commits are more descriptive moving forward too. "

- [x] Remove redirect to home page when an empty query is provided 
  -  Redirect to resources and support?
  -  Redirect to a search landing page?

    > **Search Landing page is being define as part of Epic #24333. Removing redirect will be accomplished when the landing page is implemented- #24992**

- [x] Use improved error logging to provide detailed messages when a search fails: -- 
  -  no results returned
  -  invalid query
  -  search is down
  -  etc

    > **Tracking implementation on Error Logging #24968**

## Timeline
These tasks should be completed in parallel with the search results page redesign

**Comment by srsuddath** [comment]
These tasks have either been closed (not going to be completed) or have been planned in other tickets!
