### ISSUE TITLE
Pre-Launch External UAT

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#24111]
## Description
We want to test the app with users externally that use Secure Messaging, Appointments, Claims, and meet other specific criteria (like having all credential types represented). 

**Acceptance criteria**
- The checklist below is complete

**Approx date needed by:** 
- Needed at least 2 weeks prior to launch (we want a bug fixing sprint after finishing external UAT right?) 

## Reference documentation: 
- Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/uat/research-plan.md
- Discussion guide:https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/uat/discussion-guide.md
- Logistics guide: https://docs.google.com/document/d/1_ihQUGgQ1nSwTJASq1V8LboyDYxy45phCnhRgcvx6Mo/edit?usp=sharing

## Notes, status, and tasks: 
**5/27**
- We've had a bunch of no shows, but 3 great sessions

**5/24**
- UAT is beginning
- Sign up sheet to participate in sessions: https://docs.google.com/spreadsheets/d/1hjlL0G4bSneTNrW1xezMDEVGUs2n-NANadJ_bPotHWk/edit#gid=1284562836

**5/14**
- Plan for this to begin week of 5/24
- Patrick to work with Leanna and Travis on who is doing what in Play stores to get permissions set up

**5/4/21: **
- Bridget and Jen to take a pass at RP and DG, aiming to have in a pace to submit to Perigean by Mon of next week
- Meli owning Google Play distribution instructions 

---

# Checklist

### Tasks related to distribution
- [x] Write final instructions for setting up TestFlight (can people click a link in the email or is it only the code?)
- [x] Come up with a plan for who is adding users into TestFlight and Google Play (when is this happening? who owns it?) - **Ashley to batch add folks on a weekly basis, Bridget and Jen also will have permissions**
- [x] Make sure Ashley/Bridget/Jen have the correct permissions to add folks to Google Play & Test Flight
- [x] Make sure the right build is added to the Perigean facing group
- [x] Determine if Google Play is usable for testing **Owner: Meli** 
- [x] Document set up instructions for Google Play **Owner: Meli** 
- [x] Determine if we are doing testing with BVA 
- [x] Determine if we are recruiting blind or low vision users through Perigean (this may hinge on the accessibility of the distribution methods we can use, we haven't tested Google Play yet) 
- [x] Test set up via Google Play in some internal sessions prior to using this distribution method for external UAT

### Tasks related to recruitment & scheduling
- [x] Align on the timeline - when will we be ready to do external UAT? **Ashley to gut check w/ Bess & BE team**
- [x] Write UAT Research Plan in Perigean format 
- [x] Finalize recruitment criteria 
- [x] Write UAT Discussion Guide
- [x] Submit research plan & discussion guide to Perigean 
- [ ] Refine Google Sheets note-taking template to match final discussion guide 

### Tasks related to conducting sessions
- [ ] Conduct 6-10 external sessions 
- [x] Identify issues, rank by decided upon severity matrix, determine next steps

**Comment by bridgethapner** [comment]
Update: We want to wait for bugs ranked as critical and high to be solved before going forward with conducting external sessions. @ashley-matthews did I hear that right in SU?

**Comment by bridgethapner** [comment]
Notes from 5/7 sync with @bridgethapner @ashley-matthews @drjecker: 

- Ashley is going to gut check timing with the dev crew: are we feeling ok to submit to start testing on May 24th?
- I will set up a knowledge transfer time with @lexicalninja to ensure I, Ashley, & Jen can add folks to Google Play and Test Flight so we can manage UAT participants and add them at the correct permissions level so that Patrick doesn't have to do this for UAT. Ideally, we want to distribute this so multiple people are able to do this.

The plan is to follow up on these 2 items early next week and submit by Weds of next week, still aiming to start sessions 5/24 at the earliest.

**Comment by bridgethapner** [comment]
@drjecker and @melissa-lefevre wrote up a summary of external UAT here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/uat/external-uat-summary.md, so all documentation of issues logged in this UAT is on GitHub. I'm going to close this ticket.
