### ISSUE TITLE
NOD: implement analytics

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#24112]
## Description

Once the analytics review is completed, suggestions need to be implemented for NOD

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23163

## Tasks

- [ ] Add analytics events to form pages as specified
- [ ] Add analytics to submission & error states
- [ ] Update unit tests

## Acceptance criteria

- [ ] Analytics implemented & tested

**Comment by Mottie** [comment]
No change needed... setting estimate to 0.
