### ISSUE TITLE
Change delete upload link to a button

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#24133]
## Description

The file upload "Delete file" button should appear as a secondary button.

Related:
- Design: https://design.va.gov/patterns/form-templates#review-state-1
- Design for review & submit page: https://design.va.gov/patterns/form-templates#usability-guidance-12
- Review ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23960#issuecomment-831255854

## Tasks

- [x] Globally change the delete button style
- [x] Hide delete button on the review & submit page when the page is being reviewed (not edited)
- [ ] Ensure the implementation matches the recommendations

## Acceptance criteria

- [x] Delete button has secondary button style
- [x] Delete button hidden in review until editing a page
- [x] Unit tests updated
