### ISSUE TITLE
Design intent [Healthcare Experience - Check-in]

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#24149]
## Steps to complete Design Intent Collaboration
- [X] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Link to this issue once created in #design in Slack; tag @vsp-product-support-members.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [x] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No
### Has your team met with Sitewide Content for content support?
- [ ] Yes*
- [X] No - Kristen briefly met with Danielle to give a very high-level overview of the product.

\*If yes, please be sure to include your Content brief (if available) and any other relevant artifacts

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Whiteboard sketch or other lo-fi prototypes or wireframes](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/m18LjOk/play)
- User flow
- Content brief (if available) - [Discovery research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/remote-discovery/Research%20Findings.pdf)
- Any other artifacts you have so far - Here is a little more information on the scope of the pre-check in portion that isn’t part of the user flow/wireframes yet: 
    * Confirm appointment
    * Verify & update contact information
    * Verify & update next of kin information
    * Indicate any insurance information changes
    * Complete forms or paperwork needed for appointments (e.g. Release of Information)

## Meeting attendees from requesting team
- Designer(s) (required): Kristen McConnell
- Product Manager (required): Leah Keeler
- OCTO-DE Product Lead (recommended): Ming Ligh
- OCTO-DE Design Lead (required): Ryan Thurlwell
- VFS content, IA, accessibility, and QA specialists (if applicable): name(s)
- Other stakeholders you want to invite (if applicable): Mark Dewey and Dillo Raju (engineering)

### What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
May 6: 2-2:30
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @kristenmcconnell is this new work? I don't think we've been introduced to it yet. Could you please complete a [Collaboration Cycle Kickoff](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D)? This will help us understand the scope of work and provide recommended Collaboration Cycle touchpoints. Thank you!

**Comment by leahkeeler** [comment]
Hi @shiragoodman  Kick-off submitted last night - @kristenmcconnell is faster then I am by a few hours :)

**Comment by shiragoodman** [comment]
hahah I was wondering if the Kickoff you submitted was for this.. thank you!

@kristenmcconnell are you ready to schedule? @allison0034 shared that you asked to reserve the date and would tag us on Slack when ready. If we don't hear from you by 2:00 today we'll need to push out since we ask for 2 full days notice. Please let us know! :)

**Comment by kristenmcconnell** [comment]
Slack post sent. I forgot that part last night.

**Comment by allison0034** [comment]
@kristenmcconnell @leahkeeler this has been schedule for May 6th at 2. I did make it 45 minutes as we have been tight on time in recent meetings.
