### ISSUE TITLE
Resources and Support: Travel pay article #3: How to submit a claim online

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#24156]
We want to create a step-by-step how-to article for how to file a travel pay claim online.

- For info, use the step-by-step from this page: https://www.va.gov/health-care/get-reimbursed-for-travel-pay/. However, I believe we can skip step 1 and start with what is now step 2 (like on this page: https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/).

- Consider any related info that we should add to the intro. For example, the line about submitting a claim within 30 days.

- Consider pulling in screenshots from the user guide. Let's try this and get a feel for whether it might work.

- Watch these 2 new BTSSS videos and consider if there's information/steps we may need to add:
  - How to submit a travel reimbursement claim for a VA facility appointment: https://www.youtube.com/watch?v=axBYPuhZcoo&list=PL3AQ_JVoBEyzJnt68Eq_mPBdyZfkvq0Wu&index=5
  - How to submit a travel reimbursement claim for a non-VA facility appointment: https://www.youtube.com/watch?v=ai_LYF3al-s

- Include links to these videos on page.

- Include links to other travel pay articles as related links.

### Tasks:

- [x] Create article in Drupal (Selina)
- [x] Copyedit/Review (Randi)
- [ ] Danielle review
- [ ] Send to stakeholders (Danielle)
- [ ] Pre-publish checklist and publish (Randi)
- [ ] Add article to R&S landing page
- [ ] Check if this should be added as a related link on other R&S pages
 
### Acceptance criteria:
- [ ] New R&S page live on site

**Comment by lunascoop** [comment]
@RLHecht This page is ready for review
How to file a travel pay claim online: http://preview-prod.vfs.va.gov/preview?nodeId=19367

Some notes
- Added 30-day info to page intro
- Linked to accessVA portal in CTA, like for https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/
- Added content to steps 1 and 4. For step #1, I added **ID.me** and **My HealtheVet** sign in options and the **Note** content. For step #4, I added the **Note** content and links to 2 Youtube videos since they're relevant at this step in the overall process.
- Screenshots were taken from the PDF (except for the 1st one which I took directly from the website) and not the clearest. They do need a border, which I re-edited bc the borders in the PDF varied in color (blue or black), line thickness, and drop shadow.
- Was able to avoid the "Al Pacino" screenshot in step #4, though a fake address is still displayed. Can decide if you want to blur the address.
- Screenshot for step #6 not included in PDF. I tried searching online and taking a screenshot of the step from the Youtube video, but it didn't look good.

cc: @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA This page is ready for you to review.

**Comment by RLHecht** [comment]
Update: This can stay in backlog until there is time to review and move forward with it. We will also need to reassess the page using the new criteria for R&S/benefit hub pages.

**Comment by DanielleThierryUSDSVA** [comment]
This is complete and the page is live at https://www.va.gov/resources/how-to-file-a-va-travel-reimbursement-claim-online/. Closing.
