### ISSUE TITLE
FE implementation for expandable alert: Vet Centers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24151]
## Issue Description
The VAMC product has an Operating Status page which provides details on facility access. The Facility Locator provides the details on the Facility Detail page.

The Vet Center product does not have an equivalent experience to connect to the operating status displayed on the Locations page. Leyda adapted a component from Suicide Prevention pages which will go through the Design intent milestone on 5/4. 

This design pattern will be iterated on to incorporate accessibility/usability considerations

---
## Tasks
- [ ] Implement the expandable alert for Vet Center operating status based on Leyda's [prototype](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138920563/simulate/sitemap?mode=i) and [specs](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145/simulate/sitemap?mode=i)
- [ ] Use filter to make phone number actionable on the front end
- [ ] Add data layer
- [ ] Ensure the implementation is accessible 

Description/Screenshot of Interaction | Data Layer Specification | Dev Notes | 
| -- | -- | -- | 
Operating status |  `'event'': 'int-accordion-expand', //OR 'int-accordion-collapse'`<br>`'operating-status-heading: //dynamically populate according to the top level heading of the alert box'`

## Acceptance Criteria
- [ ] Front end implementation is consistent with the design spec
- [ ] Operating status is displayed for the facility on the main page (assuming there is an operating status available in Drupal)
- [ ] Operating status is displayed for facilities displayed on the Locations page  (assuming there is an operating status available in Drupal)
- [ ] Veteran can view status details by expanding the alert  (assuming there is an operating status available in Drupal)
- [ ] Phone number is actionable on the front end
- [ ] Data layer is in place to track clicks to open/close the accordion
- [ ] Alert is announced by screenreader and 
- [ ] Veterans know they can expand the alert to see details about the operating status

---

**Comment by mmiddaugh** [comment]
temporarily blocking this issue pending final feedback from Ryan/Josh on Leyda's design

**Comment by lildziner** [comment]
@mmiddaugh @brangi today we use slightly different operating statuses on detail pages vs facility locator. (correct?) Should we think about this alert as a component that could be used in either place? That detail isn't something I included in my specs.

<details>
<summary> expandable alert use cases </summary>

![expandable-alert-use-case](https://user-images.githubusercontent.com/4960080/119864902-1beb6080-bee9-11eb-82cd-25d27c65a8be.png)


</details>

**Comment by mmiddaugh** [comment]
@lildziner We have an issue to implement the expandable alert on FL (#24824)
