### ISSUE TITLE
NOD Phase 3 Content Tasks

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#24157]
## Issue Description
Complete phase 3 content --> design tasks.

####Content brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/content-brief-NOD.md
---
## Tasks
- [x] Change the copy of the Opt-in note from Legacy Appeals Process to plain language (e.g. new and old appeal process)
- [x] Simplify and clarify the copy about the opt-in process, and make it consistent with the copy about the opt-in process on the Board Appeals Info page.
- [x] Make the copy on the Board review option page consistent with the Board Appeals Info page. Simplify language if possible. Add the time estimates to both pages.

## Acceptance Criteria
- [x] The above tasks have been met and implemented into the NOD Invision Prototype
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Changes can be viewed here:

https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562
