### ISSUE TITLE
Update language on survivor and dependent education benefits page around Fry Scholarship

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24161]
## Issue Description
Stakeholder Tammy Hurley has asked us to add more info to the [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) page about the Fry Scholarship. 

The following text should be added:
"or was a member of the Selected Reserves who died from a service-connected disability on or after September 11, 2001"

Their suggested edit:

The Marine Gunnery Sergeant John David Fry Scholarship (Fry Scholarship) is for children and spouses of service members who died on or after September 11, 2001, or who died from a service-connected disability on or after September 11, 2001

We have similar language on the [Fry scholarship](https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/) page and can look at that as well. 

## Tasks
- [x] Add content to education page (Randi)
- [x] Review (Beth)
- [x] Send to stakeholders (Randi/Beth)
- [x] Review and publish (Randi))

## Acceptance Criteria
- [x] New content live on site

**Comment by RLHecht** [comment]
@bethpottsVADEPO Should we add what I bolded below to their suggested edit? This is similar to what we have on the Fry Scholarship page.

The Marine Gunnery Sergeant John David Fry Scholarship (Fry Scholarship) is for children and spouses of service members who died on or after September 11, 2001, or **of members of the Selected Reserve** who died from a service-connected disability on or after September 11, 2001.

I can't decide if this reads awkward, but I'm not sure if Selected Reserve needs to be put in there (they didn't have it in their edit).

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks for reaching out to stakeholders about this to double check before adding in that additional content. Nice that Tammy responded so quickly.

I'm thinking of something along the lines of the below to shorten some very long sentences and chunk the content more effectively with this new addition. Can you put this in drupal and we'll see how it looks?:

There are 2 main GI Bill programs offering educational assistance to survivors and dependents of Veterans:

**The Marine Gunnery Sergeant John David Fry Scholarship (Fry Scholarship)** is for children and spouses of: 

- Service members who died on or after September 11, 2001, **or** 
- Members of the Selected Reserve who died in the line of duty after September 11, 2001

Get more information about the Fry Scholarship

**The Survivors’ and Dependents’ Educational Assistance (DEA) program** offers education and training to qualified dependents of Veterans who: 

- Are permanently and totally disabled because of a service-related condition, **or** 
- Died while on active duty or as a result of a service-related condition

Get more information about the DEA program

**Comment by RLHecht** [comment]
Tammy came back with more changes and asked for an update on the Fry scholarship page as well. New edits:

For survivor and dependent education benefits page:

**The Marine Gunnery Sergeant John David Fry Scholarship (Fry Scholarship)** is for children and spouses of:

- Service members who died on or after September 11, 2001, **or**
- Members of the Selected Reserve who died in the line of duty after September 11, 2001

For Fry scholarship page:

You may be eligible for Fry Scholarship benefits if you’re the child or surviving spouse of:

- An active-duty service member who died in the line of duty on or after September 11, 2001, **or**
- A member of the Selected Reserve who died in the line of duty on or after September 11, 2001

**Comment by RLHecht** [comment]
Tammy approved the new changes. Both pages have been published. Will close ticket once live.

**Comment by RLHecht** [comment]
changes live on site.
