### ISSUE TITLE
NOD: Add area of disagreement to selected issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#24169]
## Description

Include selected issues follow up questions regarding the area of disagreement for each issue in the Notice of Disagreement form. The "Other" selection includes a input that is limited to 90 characters (per the schema)

Related:
- Design: https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292864
- API: https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current (`disagreementReason` in post)

## Tasks

- [ ] Include area of disagreement choice in added issues
- [ ] Include value in submission
- [ ] Update tests

## Acceptance criteria

- [ ] Area of disagreement added to NOD
