### ISSUE TITLE
[BE] Communications permissions and Contact information: Review Service Description Document and Interface Control Document (ICD) for VA Profile and send feedback

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#24168]
## Background

On 5.3.21, Terry sent over the Service Description Document and Interface Control Document (ICD) for the notifications preferences and contact information work. We need to review these and get him feedback as soon as we can. Lihan, since these docs are highly technical, I think you'd be the best person on our team to review them and let Terry know if you have questions, see anything inaccurate, or have any other feedback.

Also, Terry would like to know if we have estimates on the volume of calls we are making for contact information, so we should include that as well. Via email, he said:

> For volumes, in this case it would be, “how often would your middle tier (VETSGOV) expect to call VA Profile, in a given period, by endpoint (e.g. Contact Info:Telephone, Communication:CommunicationPermission)”.

## Tasks

- [x] Review Service Description Document and Interface Control Document (ICD) that are attached
- [x] Let Terry know via email thread if you have any feedback or if you have no feedback and everything looks good
- [x] If possible, give Terry estimate on how much we call each endpoint mentioned in the documents

[VA.gov-VAProfile-ICD-CommunicationPermissions_v0.9.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6421961/VA.gov-VAProfile-ICD-CommunicationPermissions_v0.9.pdf)
[VAProfile_Communication Permissions_ServiceDescription_v1.1a.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6421962/VAProfile_Communication.Permissions_ServiceDescription_v1.1a.pdf)
