### ISSUE TITLE
Update expandable alert spec

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24195]
## Issue Description
Following the Design Intent meeting on 5/4, we need to update the spec for the expandable alert (planned for use on Vet Center pages). As part of this effort, we need to create documentation to add the component to the experimental design system. 

---
## Tasks
- [x] Incorporate feedback into updated design spec for engineering, including
       - [ ] Provide alternative text to the Alert icon (use sr-only text or an aria-label) so screen readers have an equivalent understanding of the purpose/nature of the message
       - [ ] Ensure there are no skipped headings and that the heading order is logical. 
- [ ] Request feedback from Josh on proper semantic markup 
- [ ] Create documentation to submit the component to the experimental design system

## Acceptance Criteria
- [x] Spec is ready for FE development (and includes semantic markup guidance) 
- [ ] Documentation is available to accompany experimental design system request and includes
       - [ ] When component should be used
       - [ ] How to use it

**Comment by lildziner** [comment]
@rtwell @allison0034 @joshkimux @shiragoodman  I wanted to post [updates and another design iteration](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145/simulate/sitemap?mode=i) to the Facilities expandable alert for Vet Center operating status. The version below is what we would include for Vet Centers' MVP pilot sites, soon to launch. It does not include rich text so it would not be the ideal long term solution, but rather the first iteration of one. We would consider this experimental, as we'd be tracking it along with all other elements of content on VC sites.

**Updates to design**
- Incorporating rich text has been deprioritized to a future iteration, so plain text only to launch for MVP 
- making phone numbers interactive and tappable will be accomplished by FE dev work
- Alert header text has been bolded 
![image](https://user-images.githubusercontent.com/4960080/118003577-b3ac5480-b316-11eb-9cf9-240bf16df635.png)

**Desktop Version** ([link to all prototypes](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145/simulate/sitemap?mode=i))
- I'm posting a [desktop version of the expandable alert](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138807982/simulate/sitemap?mode=i) that would replace the [current facility statuses](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/136042527/simulate/sitemap?mode=i). 
![image](https://user-images.githubusercontent.com/4960080/118006255-1b639f00-b319-11eb-9097-72cb0ebde64a.png)
![image](https://user-images.githubusercontent.com/4960080/118003299-721ba980-b316-11eb-8655-648403bc99c1.png)

**Comment by allison0034** [comment]
@lildziner thank you for the update!

**Comment by lildziner** [comment]
Posting a [revision to the placement of the status](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138858587). has been updated to be consistent with VAMC location operating statuses ([example](https://www.va.gov/san-francisco-health-care/locations/san-francisco-va-medical-center/)) instead of current Vet Center pages.

![image](https://user-images.githubusercontent.com/4960080/118286581-9905e700-b4a0-11eb-9edd-63eeb896d38f.png)

**Comment by lildziner** [comment]
Alert specs: ([view in UXPin](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145))

![image](https://user-images.githubusercontent.com/4960080/118558956-4bee7300-b735-11eb-8028-7491715f6555.png)

**Comment by lildziner** [comment]
@joshkimux regarding proper semantic markup of this expandable alert, what are must haves for front end?

**Comment by joshkimux** [comment]
@lildziner Should be a `heading` (e.g. `<h2>`) not a `header` (e.g. `<header>`) in this instance, everything else is perfect!
