### ISSUE TITLE
Chapter 31 - Update orientation url and application routing based on wizard completion

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#24196]
## Description
We want to use more plain language for our URLS. A recent piece of feedback we received from content and IA was to change the chapter 31 orientation URL from `/orientation` to `/start`. 

Additionally, an update needs to be made to the application routing based on wizard completion status:
- if an unauthenticated user leaves the form intro page, remove wizard flag from browser storage to ensure re-visiting the app directs to the wizard.

## Tasks
- [x] Update all instances of chapter 31 `/orientation` to `/start`
- [ ] Add session storage wizard flag removal to cover case in description above
- [x] Update any e2e tests

## Acceptance Criteria
-  [ ] PR created and tasks complete

**Comment by micahchiang** [comment]
[PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/17170) that updates the routing from `orientation` to `start`.

Tabling the other issue in this ticket surrounding form abandonment and maintaining wizard state across logging in, as it's taking longer than initially thought. Will return once other tickets are complete.

**Comment by micahchiang** [comment]
Created https://github.com/department-of-veterans-affairs/va.gov-team/issues/24847 to capture the work of application routing more specifically. Closing this ticket out for now.
