### ISSUE TITLE
QA Forms KPI Dashboard - Data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#24200]
## Issue Description
As we start to roll out our dashboards, we need to make sure that our data is accurate and trustworthy

---
## Tasks
- [ ] Verify that data formats are correct
- [ ] Confirm the data is what is expected (does the info collected measure what it's supposed to measure?)
- [ ] Identify & document invalid values

## Acceptance Criteria
- [ ] The production Forms KPI Dashboard in Domo has accurate and trustworthy data

**Comment by bsmartin-ep** [comment]
Some initial questions @JasonTheBearded...

In `vsp-analytics-and-insights.vsp_sites.find_benefit_hub`, I see this duplicate...

`WHEN REGEXP_CONTAINS(page,'^www.va.gov/disability.*') THEN 'Disability'`

..and I think this one is missing:

`^health-care/get-medical-records.*`

(see [list](
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000520))

----------------

In `vsp-analytics-and-insights:vsp_sites.vw_forms_funnels`, I see....

`totals.bounces as bounce,`

Not sure if I saw you actually using this, but standard disclaimer is often a [weird metric](https://support.google.com/analytics/answer/1009409?hl=en)...

> A bounce is a single-page session on your site. In Analytics, a bounce is calculated specifically as a session that triggers only a single request to the Analytics server, such as when a user opens a single page on your site and then exits without triggering any other requests to the Analytics server during that session.

--------------

Out of curiosity, what's the reasoning behind using `DISTINCT` with date this in some of your queries?

`SELECT DISTINCT PARSE_DATE("%Y%m%d", ga.date) AS date,`

**Comment by JasonTheBearded** [comment]
Thanks @bsmartin-ep I fixed the `find_benefit_hub` function.

We don't use bounce on the funnel dataset but do use it for some of the landing page metrics. We're referencing it to see if a user visited the site and then left without any interaction or moving on to the form.

The `DISTINCT `applies to the whole select statement not just the date column, it's to help reduce the number of duplicate records returned in the query.

**Comment by bsmartin-ep** [comment]
@chloedotbrown / @JasonTheBearded  -

The only "data" issue I found is the Date filter on this card...

https://va-gov.domo.com/analyzer?pageId=447193050&cardid=1954273908

![image](https://user-images.githubusercontent.com/62304138/121033486-3d1a3f80-c77a-11eb-9b58-780d8d1ee218.png)

...for whatever reason, this blank data filter is cutting off data in certain forms before a certain point.

-------------------

Other than that,  should we label cards like "Forms by status" and "Forms submitted" to specify they would correspond with the "Unique Events" metric in GA?

![image](https://user-images.githubusercontent.com/62304138/121033926-98e4c880-c77a-11eb-8913-9c848b9bfc0e.png)

![image](https://user-images.githubusercontent.com/62304138/121034132-c762a380-c77a-11eb-9508-894f507d3ad5.png)

**Comment by JasonTheBearded** [comment]
Thanks @bsmartin-ep! @chloedotbrown can we add a note in the empty corner on the highlights section and in the note box under Forms Completion? We'll definitely get that question Brian mentioned when users start trying to compare numbers between the dash and GA.

**Comment by chloedotbrown** [comment]
Notes added in both places! I'll also add to the hover text for both "Forms started" and "Forms submitted" cards.

**Comment by bsmartin-ep** [comment]
Data itself looks good and matches GA.  Other than the labeling mentioned above, this looks good to me!
