### ISSUE TITLE
Add Regional Office Name to CH31 Daily Submissions Report

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#24209]
## Background
Add regional office name to the daily submissions report for Chapter 31.  Currently it is only displaying office number, but we should include name for easier readability.

## Tasks
- [ ] Save the name of the regional office to the submitted claim/form.
- [ ] Get the regional office name for the form data and add it to the report.  

## Acceptance Criteria
- [ ] Regional office number and name are both being displayed on the report.
