### ISSUE TITLE
Submit Dependency Verification Form to Central Mail

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#24211]
## Goal
After the 21-0538 PDF is generated, it needs to be submitted to Central Mail for processing.

## Tasks
- [x] Save the 21-0538 form submission as a claim.
- [x] Generate the PDF with the saved form data and Veteran info.
- [x] Send the PDF to Central Mail.

## Acceptance Criteria
- [x] The 21-0538 PDF is being submitted to Central Mail.

**Comment by jason-gcio** [comment]
Move to next sprint
