### ISSUE TITLE
Modify CH31 Daily Report to display info In email rather than CSV

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#24214]
## Background
Currently the daily submissions report for Chapter 31 includes a link to a CSV file.  Edit the email to contain all the report information rather than generating a CSV file.  

## Tasks
- [x] Create an HTML ERB file with a table to display the report.
- [x] Generate the report data and display it in the email table. 

## Acceptance Criteria
- [x] The email has been modified to show all the data in the report.
