### ISSUE TITLE
[VAMC]  Update VAMC - System list for Facilities team to confirm Left Nav Systems [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24222]
## Story
Front end engineers need to have an updated and accurate list of all VAMC systems, so they can confirm and create the Left-Nav sections required.

## TASK
- [ ] Provide all systems current and upcoming that will be published so Left Nav can be loaded into front end code.
- [ ] Provide any changes due to systems merging (VISN 15)

## Acceptance Criteria
- [ ] Updated and full list of systems have been provided to Facilities team
- [ ] All System updates included
- [ ] Provide time for Facilities team to respond with questions
