### ISSUE TITLE
[Content-Load-Review] Load content and Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA Bay Pines health care.

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24223]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[VISN-8 Content folders](https://drive.google.com/drive/folders/1SxoMr5SVKG7TAGC-BduB_SyJogrlZkzI)

## Tasks
* Load prepared content for the folowing pages:
- [ ] About
- [ ] Work With Us
- [ ] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: 
- [ ] vha_516	C.W. Bill Young Department of Veterans Affairs Medical Center
- [ ] vha_516BZ	Lee County VA Clinic
- [ ] vha_516GA	Sarasota VA Clinic
- [ ] vha_516GB	St. Petersburg VA Clinic
- [ ] vha_516GC	Palm Harbor VA Clinic
- [ ] vha_516GD	Bradenton VA Clinic
- [ ] vha_516GE	Port Charlotte VA Clinic
- [ ] vha_516GF	Naples VA Clinic
- [ ] vha_516GH	Sebring VA Clinic

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [ ]  Location Listing Page 
- [ ]  History    
- [ ]  Internship and Fellowship 
- [ ]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [ ]  System Page 
- [ ]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [ ]  Mission-Vision 
- [ ]  Leadership Listing Page 
- [ ]  Policies Page (Should be new hardened format)
- [ ]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [ ]  Performance Page
- [ ]  Make an Appointment
- [ ]  Register-for-Care
- [ ]  Billing
- [ ]  Contact-us		
- [ ]  Dav-vans
- [ ]  Medical-Records
- [ ]  Operational Status
- [ ]  Pharmacy
- [ ]  Caregiver
- [ ]  Homeless
- [ ]  LGBT
- [ ]  Mental
- [ ]  Minority
- [ ]  Patient
- [ ]  Returning Service member
- [ ]  Suicide prevent
- [ ]  Women-vet
- [ ]  Campus Map
- [ ]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.

**Comment by larrywest52** [comment]
DONE
