### ISSUE TITLE
[Content-Load-Review] Load content and Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA Tampa health care.

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24228]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[VISN-8 Content folders](https://drive.google.com/drive/folders/1SxoMr5SVKG7TAGC-BduB_SyJogrlZkzI)

## Tasks
* Load prepared content for the folowing pages:
- [x] About
- [x] Work With Us
- [x] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: 
- [x] vha_673	James A. Haley Veterans' Hospital
- [x] vha_673BV	Tampa VA Domiciliary
- [x] vha_673BZ	New Port Richey VA Clinic
- [x] vha_673GB	Lakeland VA Clinic
- [x] vha_673GC	Brooksville VA Clinic
- [x] vha_673GF	Zephyrhills VA Clinic
- [x] vha_673GG	South Hillsborough VA Clinic
- [x] vha_673GH	Lecanto VA Clinic
- [x] vha_673QA	Forty Sixth Street North VA Clinic
- [x] vha_673QB	Forty Sixth Street South VA Clinic
- [x] vha_673QC	West Lakeland VA Clinic
- [x] vha_673QD	Deer Park VA Clinic
- [x] vha_673QE	Highway Nineteen VA Clinic
- [x] vha_673QF	Winners Circle VA Clinic
- [x] vha_673QG	Little Road VA Clinic
- [x] vha_673QH	Bruce B. Downs Boulevard VA Clinic
- [x] vha_673QI	Medical View Lane VA Clinic
- [x] vha_673QJ	Hidden River VA Clinic
- [x] vha_673QK	Tampa 1 VA Mobile Clinic
- [x] vha_673QL	Tampa 2 VA Mobile Clinic

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [x]  Location Listing Page 
- [x]  History    
- [x]  Internship and Fellowship 
- [x]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x]  System Page 
- [x]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [x]  Mission-Vision 
- [x]  Leadership Listing Page 
- [x]  Policies Page (Should be new hardened format)
- [x]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [x]  Performance Page
- [x]  Make an Appointment
- [x]  Register-for-Care
- [x]  Billing
- [ ]  Contact-us		
- [x]  Dav-vans
- [x]  Medical-Records
- [x]  Operational Status
- [x]  Pharmacy
- [x]  Caregiver
- [x]  Homeless
- [x]  LGBT
- [x]  Mental
- [x]  Minority
- [x]  Patient
- [x]  Returning Service member
- [x]  Suicide prevent
- [x]  Women-vet
- [x]  Campus Map
- [x]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.
