### ISSUE TITLE
[Content-Load-Review] Load content and Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA North Florida health care.

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24226]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[VISN-8 Content folders](https://drive.google.com/drive/folders/1SxoMr5SVKG7TAGC-BduB_SyJogrlZkzI)

## Tasks
* Load prepared content for the folowing pages:
- [x] About
- [x] Work With Us
- [x] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: 
- [x] vha_573	Malcom Randall Department of Veterans Affairs Medical Center
- [x] vha_573A4	Lake City VA Medical Center
- [x] vha_573A5	Jacksonville Navy VA Medical Center
- [x] vha_573BU	Gainesville VA Domiciliary
- [x] vha_573BY	Jacksonville 1 VA Clinic
- [x] vha_573GA	Valdosta VA Clinic
- [x] vha_573GD	Ocala VA Clinic
- [x] vha_573GE	Saint Augustine VA Clinic
- [x] vha_573GF	Sergeant Ernest I. "Boots" Thomas VA Clinic
- [x] vha_573GI	The Villages VA Clinic
- [x] vha_573GJ	St. Marys VA Clinic
- [x] vha_573GK	Marianna VA Clinic
- [x] vha_573GL	Palatka VA Clinic
- [x] vha_573GM	Waycross VA Clinic
- [x] vha_573GN	Perry VA Clinic
- [x] vha_573GO	Middleburg VA Clinic
- [x] vha_573QA	Gainesville Sixteenth Street VA Clinic
- [x] vha_573QB	Gainesville Ninety Eighth Street VA Clinic
- [x] vha_573QC	Gainesville Sixty Fourth Street 1 VA Clinic
- [x] vha_573QD	Gainesville Sixty Fourth Street 2 VA Clinic
- [x] vha_573QE	Gainesville Sixty Fourth Street 3 VA Clinic
- [x] vha_573QF	Gainesville Twenty Third Avenue VA Clinic
- [x] vha_573QG	Jacksonville Southpoint VA Clinic
- [x] vha_573QH	Ocala West VA Clinic
- [x] vha_573QJ	Jacksonville 2 VA Clinic
- [x] vha_573QK	Lake City VA Clinic

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [x]  Location Listing Page 
- [x]  History    
- [x]  Internship and Fellowship 
- [x]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x]  System Page 
- [x]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [x]  Mission-Vision 
- [x]  Leadership Listing Page 
- [x]  Policies Page (Should be new hardened format)
- [x]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [x]  Performance Page
- [x]  Make an Appointment
- [x]  Register-for-Care
- [x]  Billing
- [ ]  Contact-us		
- [x]  Dav-vans
- [x]  Medical-Records
- [x]  Operational Status
- [x]  Pharmacy
- [x]  Caregiver
- [x]  Homeless
- [x]  LGBT
- [x]  Mental
- [x]  Minority
- [x]  Patient
- [x]  Returning Service member
- [x]  Suicide prevent
- [x]  Women-vet
- [x]  Campus Map
- [x]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.
