### ISSUE TITLE
[Tech-Debt] Swap out current Policies page with New Hardened Policies Page for VISN-23 and save as draft [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24235]
## User Story
As a VHA Digital Media web manager, the national policies need to be hardened and available to national administrators only, so national content should be changed from one source to all systems 

## Goal
Remove tech-debt for all new hardened policies pages.

## Resources - Tools - Documentation
TBD

## Tasks
Archive current Policies page, replace with Cloned page and add to Menu for the following Systems:
- [x] VA Black Hills health care
- [x] VA Central Iowa health care
- [x] VA Fargo health care
- [x] VA Iowa City health care
- [x] VA Minneapolis health care
- [x] VA Nebraska-Western Iowa health care
- [x] VA Sioux Falls health care
- [x] VA St Cloud health care

Complete the follow these steps for each System:
> 1. Open Policies Page in Edit Mode
> 	a. Change Name to "Policies - Old"
> 	b. Remove Menu by un-checking Menu box
>	c. Save as "Archive" 
> 2. Open Fargo or Iowa City System and Find Policies Page
>	a. Select Clone from Tabs and Select Clone 
>	b. Go to Edit and Remove "- Cloned"
>	c. Change Governance to match new [System Name] (Owner and Related system)
>	d. Select Menu, Enable check box
>	e. Type in "Policies" in Name
>	f. Select from Drop down, "About VA [System Name]" From System you are cloning to.
>	g. Copy Visiting hours and/or Security information from original Policies page.
>		g1. Security information will go into "Other Policies" Section.
> 3. Save new Policies page as current status of system, (i.e. Published or Draft)

## Acceptance Criteria
- [ ] All original Policies pages have been archived and removed from Menu
- [ ] All New Policies pages are "Published" and Link is in Menu at bottom of Menu items.

**Comment by bcastoe** [comment]
#24235 Create New Hardened Policies Page for VISN-23 - Completed and moved to Validate; the following systems have VAMC System Policies Page as Published: St Cloud, Nebraska-Western, and Iowa City.
