### ISSUE TITLE
[MCP] Concept ideation

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#24249]
## Issue Description
We need to create new concepts for debt portal with medical copayments included to bring to Design Intent.

---
## Tasks
- [ ] Designers hold ideation session
- [x] Designers present research findings and ideation concepts to team
- [x] Designers refine based on team workshop
- [x] Design intent meeting

## Acceptance Criteria
- [ ]

**Comment by rebeccawalsh** [comment]
Riley and I had ideation sessions and produced several concepts found in [the Miro board](https://miro.com/app/board/o9J_lFg6K9s=/). We had design intent and are still pending feedback from IA as to the strategy / approach we should take.

We're still trying to figure out if we will be creating a "Financial hub" and moving financial tools into it, creating a combined money owed tool (debts + copays), a combined money tool (debts + copays + payments), or creating a separate tool.
