### ISSUE TITLE
Create New Param in AWS Parameter Store and Make it Available to New GitHub Action Repo 

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#24247]
## Issue Description
The Testing Tools Team has a created a [new repo](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-testrail-data) for a scheduled GitHub Action. The action will grab data from the VA TestRail account and post it to a table in the VA's BigQuery account. We need to store a TestRail token in the param store and be able to access it in this new repo.

We have the TestRail token and are waiting for Analytics to provide us with service credentials for BigQuery.

Two things:
- Can you please tell me what name/path you would like us to use when creating the new param in the Parameter Store?
- Can you please make this param available in [this new repo](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-testrail-data) and provide us with an example of how to access it in a GitHub Action `js` file? I don't know how this part works.

I'll submit another ticket for the BigQuery params when we receive them.

Please let me know if you have any questions. 

Thanks :-)

---
## Tasks
- [x] Advise what name/path should be used to create the new param
- [x] Make param available in [this repo](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-testrail-data)
- [x] Provide an example/documentation on how to access values from the AWS Parameter Store in a GitHub Action `js` file

## Acceptance Criteria
- [x] The Testing Tools Team knows what name/path to use to create the new param
- [x] The param can be access in the new repo
- [x] An example/documentation has been provided that explains how to access values from the AWS Parameter Store in the GitHub Action file

**Comment by dginther** [comment]
This is done, the testing team should have access to write variables to /dsva-vagov/testing-team/*
the service account used has the ability to read these variables. The service account variables are placed in the repo secrets, as well as in /dsva-vagov/testing-team/svc-gha-testingteam-user/

**Comment by jbritt1** [comment]
> This is done, the testing team should have access to write variables to /dsva-vagov/testing-team/*
> the service account used has the ability to read these variables. The service account variables are placed in the repo secrets, as well as in /dsva-vagov/testing-team/svc-gha-testingteam-user/

You da man D!

**Comment by holdenhinkle** [comment]
Thank you!
