### ISSUE TITLE
NOD: Split up issues page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#24253]
## Description

The current Notice of Disagreement eligible issues page shows both the eligible issues provided by the API and allows entering new issues. An opt-in checkbox is also included with explanation text. Too much content on this page increases cognitive load and should be split up.

Also, each issue will need to include an area of disagreement select/input (see #24169) which only adds to the cognitive load.

Additionally, we may be able to determine is an issue is in the legacy process (CST includes a "legacy" type). If this is possible, we may get by with conditionally showing the opt-in checkbox to users.

Related:
- Design (pending)
- Discussion: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23960#issuecomment-830274550

## Tasks

- [ ] Move add issue functionality to a separate page
- [ ] Modify eligible issues component to separate out add issues & combined validation
- [ ] Update unit tests
- [ ] Update e2e tests
- [ ] Follow up on conditionally showing the opt-in

## Acceptance criteria

- [ ] Eligible & added issues exist on separate pages
