### ISSUE TITLE
UI Updates to Dependency Verification Modal

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24269]
## Backend
Based on feedback, we have some changes to make to the Dependency Verification Modal window.

~~Per https://github.com/department-of-veterans-affairs/va.gov-team/issues/22070, results and error states would live on the View Dependents page itself.~~

## Considerations
- https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/

## Tasks
- [ ] ~~Update the modal window actions based on latest designs (see ticket above)~~
- [x] Remove the bold labels on gray cards (i.e., Relationships)
- [x] Left align the primary button on the modal
- [x] First modal window: "This is correct" and "Make changes" need accessible labels. "Verify this is correct" and "Change dependents" _Non-sighted users won't understand what is correct, or what they're making changes to without these._

## Acceptance Criteria
- [x] The Dependency Verification Modal is updated per above
