### ISSUE TITLE
TUD Hosting - Create an ECR Repository for TUD

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#24265]
## Issue Description
This will create the ECR Repo for the Test User Dashboard.

---
## Tasks
- [x] Add the `vsp-test-user-dashboard` to the `globals/ecr.tf` file

## Acceptance Criteria
- [ ] Approved by DevOps
- [ ] TUD ECR Repo is created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
