### ISSUE TITLE
Create FE feature flag for variant testing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24277]
## Description
As Product, I would like a feature toggle to serve as a place for managing future variant tests.

---
## Tasks
- [ ] Create frontend flag

## Definition of Done
- [ ] All tasks are complete
- [ ] Name of flag is noted in this ticket

**Comment by jenniemc** [comment]
Feature flag is `va_online_scheduling_variant_testing`
