### ISSUE TITLE
Prepare for Usability for COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24276]
### Background
COE is essentially ready for usability testing. We need a final checklist to ensure all elements are inplace and ready to go. 

### Tasks
- [x] Review research plan and insert dates
- [x] Review convo guide to address latest revisions of prototype
- [x] Submit RP & CG to Lauren
- [x] Get scheduled

### 
- [x] COE usability testing is scheduled
