### ISSUE TITLE
Create BE feature flag for variant testing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24278]
## Description
As Product, I would like a feature toggle to serve as a place for managing future variant tests.

---
## Tasks
- [ ] Create backend flag

## Definition of Done
- [ ] All tasks are complete
- [ ] Name of flag is noted in this ticket

**Comment by cferris32** [comment]
Feature flag name will be `va_online_scheduling_variant_testing`
