### ISSUE TITLE
Mock Up Search Bar Iterations (Gray box and prompt text)

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24270]
## Description

As a part of the design intent discussions, search input fields were discussed.

## Background/Context

Related Issues:
Design Intent Meeting - [#22885](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22885
)
Search & Discovery - Global Search Summary [#23650](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23650)

## Tasks

- [x] Mock up Gray box around search input field
- [x] Update prompt text at the top of search input field

## Definition of Done

- [x] Mock ups are ready for review
