### ISSUE TITLE
Implement design revisions to COE per LOB and Platform feedback

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24271]
### Background

The Certificate of Eligibility is available via VA form 26-1880. The eBenefits team has built an initial prototype using elements from the VA.gov form system. The 26-1880 will conform to form systems conventions. A number of revisions have been requested from both the Line of Business (LOB) and the VA.gov platform team. 

### Tasks
Implement edits/revisions to conform to VA.gov form system conventions /limitations. To include:
- [x] ~~Combine biographical and contact info screens~~ Screens will remain discrete 'chapters'
- [x] Add link to allow auto COE recipient to reapply.
- [x] Implement pre-filled text boxes to allow user to 'correct' known biographical info
- [x] ~~Add 'Cell phone' text box; change 'Phone' to 'Home phone'~~ Creates PRA issue
- [x] ~~Add 'Text message' to contact preferences~~Creates PRA issue
- [x] Remove 'one-time' restoration from loan intent screen
- [x] Add **needed documentation list** to documentation upload screen for user reference
- [x] Reword 'Please go to your profile page' link
- [x] Remove Purple Heart question
- [x] Remove document upload bypass
- [ ] Make Step 3 of 4: Your VA loan history a description list
- [ ] ~~Split up Step 1 of 4: Your VA loan history into multiple steps~~ May not be practical in list/loop; will investigate
- [x] Replace green button with green action link
- [x] Make sure your form content aligns with the Need help (currently indented)
- [x] Add file size to PDF
- [x] Use the ‘After you apply’ style on the confirmation page
- [x] Use the download icon / link combo for PDF download

### Acceptance criteria
- [x] UXPin prototype updated and available for LOB and dev review

**Comment by sporeboy** [comment]
Implemented everything except the strike-throughs and the description list. The Know loan info screen has dummy info; will address this when we know what will be returned.
