### ISSUE TITLE
DECISION TOOLS SPRINT 47 PRIORITIES

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24272]
## :fire: Sprint 47 Priorities

 - [x] **Find a VA Form**: Test search updates on Staging - in progress; some bugs with the FE being worked on
 - [x] **Search UI Consistency:** Request to add pattern to design system  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/459 - `blocked - need template`
 - [x] **Discharge Upgrade Wizard** Mock up link change - `Blocked; need content first.` **
 - [x] Forms overview with Kayce White on 5/10
- [x] Find a VA Form monthly Stakeholder meeting 10 AM Friday, May 14

#### Waiting on Content
- [x] Need Content to advise on verbiage to use on select for sorting by relevance #23912
- [x] Content for catchup & clean up 🔴  - create 3 new issues track progress on each doc?
- [x] FSR content - need more info from Riley Orr on how to proceed - https://github.com/department-of-veterans-affairs/va.gov-team/issues/24098

#### Zach
- [x] Deploy FE to Staging for testing - coordinate with Mark - using #23599
- [x] Internal testing - test search matching/ranking in Forms API on Staging #22866
- [x] Add new sort by relevance option to existing sort #24012 - got content feedback 5/12. Ticket updated.
- [x] Prep for Staging review
- [ ] Add link to detail pages in the "Related To" #24282 - this is going to require design and full Collab Cycle. -  **Mockup in Sprint 48**

#### Mark (Lighthouse)
- [x] Deploy Forms API search matching/ranking update to Staging for testing - coordinate with Zach
- [ ] Possible search logic tweaks following testing on Staging
- [ ] Promote to Prod following Midpoint, Staging, Contact Center reviews (may be Sprint 48)

#### John & Marci
- [ ] Internal testing - test search matching/ranking in Forms API on Staging #22866

#### Marci 
- [x]  Schedule midpoint review #24396
- [ ] Schedule staging review #23992
- [x] Update Contact Center documentation #23995 (Blocked - need screen shot with updated drop-down)
- [x] Schedule Contact Center review #23993
- [x] Schedule Privacy & Security Review #24286

#### Waiting on Content
- [ ] Requested content on 4/29 for Discharge Upgrade Wizard #24034 (🔴 blocked pending meeting with Alexander Reber re keeping PDF option alongside the form.

#### Zach
- [x] Change DD149 PDF link on [DD214 request page](https://www.va.gov/discharge-upgrade-instructions/request-dd214) #23988

#### Cassandra
- [ ] Mockup for PDF to eApplication Change - need content first. #23591 **_< - Move to Sprint 48_**

### SEARCH UI CONSISTENCY
[X] Enter request to have new pattern added to the design system for search and assign to Carol Wong and Crystabel.
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/459

### FIND A YELLOW RIBBON SCHOOL
N/A

###  🗨️  Discussion Topics/Grooming 
- Spanish language forms appearing above English - should be ranked by popularity

**Comment by MarciMcGuireGCIO** [comment]
2021-05-06 
- Discharge Upgrade Wizard - re-factoring PR merged; hopefully in Prod tomorrow
- Find a VA Form - delayed by security issue; feature flag; should be on Staging in an hour or so
- 10-10CG - Drupal does have some auditing on some of the nodes - maybe they create a report - Mark will take that as an action item.  Marci will write up some quick guidance on PDFs.
- Marci will post the search terms for testing on Staging

**Comment by MarciMcGuireGCIO** [comment]
2021-05-07
- Cassandra has been helping Cindy with a presentation
- Zach deployed feature flag for us to test Mark's change on Staging
- Zach pinged Josh to look at the change to add the link to the detail page
- Zach will pick up something else from the sprint backlog to work on while we wait to test
- Mark - troubleshooting the Staging promotion with DevOps folks
- Mark will work on deploying the new "created date" field on Tue
- Nichole is going to add a request for Mark to create a report to let us know if the VA changes a PDF file name.

**Comment by MarciMcGuireGCIO** [comment]
2021-05-10

- Mark tracked down proxy issue.  Vets website makes a connection, it talks to Vets API, but staging points to the Lighthouse sandbox environment, which doesn't have the same domain so there's a trust issue.  Facilities and some other teams still use Sandbox, so we'll do a smoke test on Dev so we can at least get the ball rolling, then we can do the switchover to Staging.
- Zach pinged Ryan and Josh about getting a gut-check on the underline - do we need Collab Cycle? #24282
- Discharge Upgrade wizard - get someone else
- Find a Form Staging review is scheduled for next Tue at 11:00 AM
- Kayce was unaware of the issues with the PDF.

**Comment by MarciMcGuireGCIO** [comment]
2021-05-13 
- Zach is about to merge his changes to get the search updates on Staging
- No updates from Mark. We can probably begin work on the pdf link report next sprint, but need to find out from Nichole
- I will add some sample search terms to the internal staging review & Slack to the DT channel

**Comment by MarciMcGuireGCIO** [comment]
2021-05-14

- Zach closed several tickets today - three related to the Find a VA Form search improvements and one related to refactoring Discharge Upgrade Wizarc (#24616, #23157, #23599, #24012)
- Zach Updated the link on the Discharge Upgrade Wizard (PR open; may be merged late Mon)
- Zach reviewed PRs for other engineers
- Mark changed the sorting so that English appears before Spanish
- Mark should have further bug fix changes on Staging this afternoon

**Comment by MarciMcGuireGCIO** [comment]
2021-05-17

- Did a PR for the PDF link on Discharge Upgrade
- Updating tests to include new work for search
- Mark put in a PR for the bug fixes; had a code review & had to do regex refactors; will try to push up this afternoon.  
- Marci working on presentation for Friday's Impact Review
