### ISSUE TITLE
526 Enhancement - Reserve Info Military History Page

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#24289]
## Issue Description
After doing testing for 526 enhancements, it was clear that this page could be consolidated to provide a better user experience for veterans filing disability claims. This ticket captures the design changes we intend to make based upon testing.

---
## Tasks
- [x] Create mockups of the new military service history page that includes reserve information

## Acceptance Criteria
- [x] Have spoken with BE and FE teams to understand tech requirements
- [x] mockups have been created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Spoke with Robin and Anna on Friday, May 14. Essentially we determined that we would need to specify which fields we would need EVSS to look for when determining eligibility for BDD and consider that within the design. We determined that adding a separation date field within the form and having Robin pull that date from the gating portion of the form would be the simplest way to have us determine if someone falls within the BDD constraints or not. Further, this would be something we could just ask EVSS to look at. The resulting work is changing the design of the separation location page on the form.

**Comment by kevinstachura** [comment]
A prelim design concept has been created and can be viewed here:

https://sketch.cloud/s/5209e90f-ab35-4c98-b535-2b9c80faf442

However, it's worth noting that this will require further work. We will need to communicate a plan to EVSS on how we might move forward, both short term and long term. Because we have not yet spoken on exactly what the short term solution looks like, this design should be paused until we know more. We can pick it back up when we've decided on a path and have communicated a tech strategy with EVSS.
