### ISSUE TITLE
[Variant Test] Sorting Facilities - dropdown

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24280]
## Description
Set up a variant facility selection page to test sorting dropdown and simplified content.

The Design System has documentation for this element:
https://design.va.gov/components/form-controls#select-box
https://design.va.gov/storybook/?path=/docs/components-select--default

---
## Tasks
- [ ] Non-vaccine flow facility page (va-facility-2)

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_variant_testing` feature flag

- [ ] If any user on facility selection page, Then show sort dropdown with 3 options: home address, current location, alphabetically

- [ ] If user has address on file, Then default sort by distance from address

- [ ] If user does not have address on file, Then default sort alphabetically

- [ ] If sorting by address or current location, Then list facilities starting with the nearest from reference point

- [ ] If sorting alphabetically, sort A to Z

- [ ] If user selects sort by address AND doesn't have an address on file, Then display message
- [ ] If user selects sort by location AND it's blocked by browser, Then display message

- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/variant-tests.md#sorting-facilities) 
- [ ] DESIGN - Designs match the specs (copy is FPO) 

## Design assets

**Specs**
All spec copy is FPO. Use copy in the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/variant-tests.md#sorting-facilities)
  - [Mobile spec](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba/a/JnW8pkr#Inspector)
  - [Tablet spec](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba/a/wL1w5eE#Inspector)
  - [Desktop spec](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba/a/qew9bdz#Inspector)
  - [Sorting selector states (IP)](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba/a/rbl4jRd)

**Workflow**
 - [Workflow overview (IP)](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba/a/3Obqv7j)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Screenshots for each state are captured in this ticket

**Comment by jbalboni** [comment]
@LeKeve I think this would be good for you to work on when we get to it, to dig into the facilities page more.

**Comment by laurenernest** [comment]
Wrote up 3 bug tickets from Staging validation:
#27274
#27275
#27276
