### ISSUE TITLE
[FE] Changes from Team Staging Review

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#24287]
## User Story

As a designer, I would like to the user experience to match the designed experience before we release.

## Related Documentation

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description
The following items were found during the team staging review that should be updated:
- Yellow colored focus border - do we need it for accessibility purposes or can we remove the color, but leave the focus? what are other teams doing?
- According to wireframes change to 780 px, but can you cross-check with a feature or two in production
- Remove “st” from July 31 on the Veteran information and confirmation page.
- Add a period at the end of the Need help? section after TTY: 711.
- On the review page, “question” in the list loop section should be capitalized.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update loading UI for list page
- [ ] Update loading UI for confirm page
- [ ] Create user tests
- [ ] Create e2e tests

## Acceptance Criteria

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by kristenmcconnell** [comment]
@tlei123 We just completed a team review of staging and identified the items in this ticket to update.

**Comment by mdewey** [comment]
![Screen Shot 2021-05-07 at 3 30 57 PM](https://user-images.githubusercontent.com/1793923/117499433-3b761580-af49-11eb-8a77-07e2656e8792.png)


@kristenmcconnell  I checked out another form (10-10EZ) They are also at the 640 form witdh. That being said, I totally could change all the breakpoints. 

Let me know what you think.

**Comment by kristenmcconnell** [comment]
If there is precedent, then don't touch it. Leave it as is and we will see what comes up in Staging Review.

**Comment by kristenmcconnell** [comment]
What did you find out about the yellow? I still see it. Besides that, all of the other updates look great. 
![Screen Shot 2021-05-11 at 10.39.47 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/db98cdd3-6030-483f-b608-eb3146f0f065)

**Comment by mdewey** [comment]
In general, the others didn't have the yellow around non-clickable items (headers, and paragraphs) but clickable items (links, buttons, etc) do have it. This behaves similarly to the menu. 

I removed the yellow from headings and figured I would wait till accessibility reviews and gives guidance to how they want it.

**Comment by kristenmcconnell** [comment]
That makes sense to me. I did notice the focus color was removed from headings, so this story looks good to me.
