### ISSUE TITLE
Investigate Top Queries with Low Click Thrus

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24299]
## Description

As a product team we would like to review the Top Queries with Low Click Thrus. There appears to be some type of glitch as many have a 0% click thru despite the fact they have been optimized with best bets. "Health Topics" in particular is confusing as it does not appear as a search term in google analytics or search.gov analytics. 

##Background Information
Slack Thread - https://dsva.slack.com/archives/C011K1VSTC3/p1619794318283700

## Tasks

- [x] Collect data needed
- [x] Reach out to search.gov to clarify/investigate
- [ ] Expect search.gov to respond - next steps will be identified in new issue

## Acceptance Criteria

- [x] Request sent to search.gov. Search.gov response may generate future actions and next steps

**Comment by denisecoveyduc** [comment]
**May 26 -** The following was sent to search.gov via email for clarification... 

---
We noticed a few puzzling things when we look at the list of ‘Low Click Thru’ terms each month. Many have a 0% click thru despite the fact they have been optimized with best bets. A few examples include “health topics” “ebenefits” “travel pay” all which have associated results in best bets.
 
We dug a little deeper using “health topics” as an example and we discovered the following:
·      “Health topics” is not a top query in google analytics
·      It has a 0% click thru rate but is also a top query.
·      We do have two best bets for that query which are a direct match.
·      Health topics is one of the modules.
 
Something fishy is certainly going on hoping you can help pinpoint what that may be. We are wondering if it is a data issue or maybe we are misinterpreting the information. Any thoughts that may help us understand what is happening?

**Comment by denisecoveyduc** [comment]
June 1- Awaiting response from search.gov.
