### ISSUE TITLE
Conduct Audit of available Click Tracking Data 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24294]
## Description

Click Tracking was enabled on XXXXX. Given that we now have a good amount of data available we want to take a closer look at what the data is telling us. 

## Background/Context

_TBD: Applicable information to be added _

## Tasks

- [x] Collect click tracking data
- [x] Review data for trends and takeaways
- [x] Highlight in upcoming ToTs as appropriate - shared on May 11th.

## Definition of Done

- [x] Provide findings in GH

**Comment by denisecoveyduc** [comment]
Findings uploaded to GH
