### ISSUE TITLE
Authenticated Experience: Sprint 48 (5/19 - 6/1)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24301]
## Priorities

1. Moving My VA towards launch (resolve QA issues, any needed collab cycle reviews)
2. All other project work
3. Profile work

## My VA redesign

**PM**
- [x] Hold staging review #24705
- [x] Hold privacy and security review [#271](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/271)
- [x] Meet with comms around My VA launch #25045

_If time permits_
- [ ] ~Hold UAT go/no-go meeting #24701 _(aiming for week of 5/24)_~

**Design**
- [ ] ~Plan discovery for how can we better elevate action items #24967~
- [ ] ~Explore designs/sketches for how we can elevate action items #24970~

**FE**
- [x]  Investigate appointment Cypress tests #24960
- [x] My VA v2 should not show a cancelled appointment #25279 
- [ ] QA fixes ***(must be resolved for UAT go/no-go)***
    - [ ] Health Care messages mismatch #24645
    - [x] Health care appointments mismatch #24646
    - [x] IE11 styling anomalies #24647 
- [ ] Resolve "must" and "should" issues in the following tickets ***(must be resolved for UAT go/no-go)*:**
    - [ ]  **"Should" IA feedback:** Correct inconsistent link labels #25071 
    - [ ] **"Must" Content feedback:** Lowercase the S in service connected in top banner #24858 
    - [ ] **"Should" Content feedback:** Link language doesn’t align and are inconsistent with the page's H1 they link to #24858 
- [ ] Fix issues found during prep for staging and privacy and security reviews:
    - [x] Update Cerner alert header #24905 
    - [ ] Change keyboard focus to start in the banner/disability rating #24714

## Notification Preferences
**PM**
- [x] Compile test case & test user documentation #24549
- [x] Prep for/submit [midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-midpoint-review.md) -- submitted #25313
- [ ] ~Create FE implementation tickets #25046~

**Design**
- [x] Compile test case & test user documentation #24549
- [x] Refine deliverables for notification settings research #24166
- [x] Update FE documentation post-content & IA review #24696 

**FE**
- [ ] ~Start build:~
     - [ ] ~Redux actions and reducers #24863~
     - [ ] ~High-level tests for FE #24864~ 
- [ ] ~Create FE implementation tickets #25046~

**BE**
- [x] Change update communication preferences API #24284

## Preferred medical facility

**PM**
- [x] Prep for/submit [midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-midpoint-review.md) -- submitted #25318 
- [ ] ~Create FE implementation tickets #25043~

**Design**
- [x] Learn more about facilities use cases uncovered during internal usability study #24442
- [x] Work with Peter to recruit for and run research / Preferred facility designs and research #23257
- [x] Prototype - Preferred facility in VAOS #23259
- [x] Update FE documentation post-content & IA review #24697

**FE**
- [ ] ~Technical discovery #24559~
- [ ] ~Create FE implementation tickets #25043~

## Profile

**Design**
- [ ] ~Improve UX for "remove" [contact information] button #23665~

**FE**
- [ ] ~508-defect-1 ❗ Launchblocker [SCREEN READER, COGNITION] Unable to update address, phone number and email address. Silent error messages. #23252~

_If time permits_
- [ ] Accessibility audit tickets:
    - [ ] ~508-defect-2 [HEADINGS, AXE-CORE]: Profile, heading levels should only increase by one #23756~
    - [ ] ~508-defect-2 [AXE-CORE]: Autocomplete attribute must be used correctly for home address/mailing address checkbox #23173~

## Backend Work
- [x] Lihan assisting the identity team

## General Research
- [x] Auth Exp best practices research phase 1 #24973
