### ISSUE TITLE
Remove Case Sensitivity from Email Validation

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24311]
## Background
In testing, the Veteran attempted to confirm their email address which was in all caps and they entered in all lowercase and it would not validate.  Case sensitivity should really be agnostic.

## Considerations
This was seen on the 686, but may be found on other features:
- [ ] 686
- [ ] Ch31 
- [ ] Ch36
- [ ] COE
- [ ] Appoint rep (not yet developed)

## Tasks
- Adjust the case sensitivity to allow for different cases for each of these features:
  - [ ] 686
  - [ ] Ch31 
  - [ ] Ch36 
  - [ ] COE 
- [ ] Submit PR to `vets-website`

## Acceptance Criteria
- [ ] Email validation does not care about case sensitivity for each feature
- [ ] A PR has been requested for merging
