### ISSUE TITLE
Vet Center type of care default

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24313]
## Issue Description
The `type of care` attribute has been defined for services that are intended to be used by Vet Centers. The VHA taxonomy has an extensive list of taxons which are not currently available to Vet Center editors but might be considered for inclusion in the future. ~However, Vet Centers will not be blocked from using other services available in the VHA taxonomy (ie: cardiology).  It is possible a service without a defined `type of care` attribute could be selected by a Vet Center.~ Selection of a non-Vet Center taxon should not be possible but we will add a layer of defense to the FE. 

---
## Tasks
- [ ] ~Add logic to make "Other services" be the default attribute when `type of care` is "null"~ _edited following conversation with CMS team today ->_ Add logic to prevent the display of Vet Center services with `type of care` = "null"

## Acceptance Criteria
- [ ] ~If `type of care` is "null", the service should appear in the "Other services" category on the Vet Center service listing.~ _edited following conversation with CMS team today ->_ If `type of care` is "null", the service will not be included in the Vet Center service listing. 
- [ ] If `type of care` is populated, the value will be used to determine the category on the Vet Center service listing.

**Comment by mpelzsherman** [comment]
Please confirm: Currently we support the following taxons:

“counseling” => displayed under **Counseling services**
“referral” => displayed under **Referral services**

Any service with `typeOfCare` not matching the above, including "other", will be displayed under **Other services**.

If `typeOfCare` is null, it will NOT be displayed.
