### ISSUE TITLE
Nonpublished "Nearby locations" should be retrieved from Lighthouse (Vet Centers)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24312]
## Issue Description
Although we have used the process for a few situations, unpublished content generally should not be rendered on the front end.  Because Vet Center pages are early in the rollout, it is likely that the facilities included in the "nearby locations" section of an MVP page are still **unpublished**. 

We need to change the logic and retrieve data from Lighthouse as the source of truth for the facility until a site is published. 

---
## Tasks
- [ ] Add check to see if the node referenced in `field_nearby_vet_centers` is published. 
      - If **no**, get `field_facility_id` to retrieve the data from Lighthouse (similar to VAMC pages)
      - if **yes**, use current process

## Acceptance Criteria
- [ ] Lighthouse is the source of truth for unpublished facilities referenced in Vet Center "Nearby locations" lists 
- [ ] List displayed does not contain duplicates
- [ ] Location is included whether or not it is a published location
