### ISSUE TITLE
[VAMC] VISN-12: VA Great Lakes Health Care System - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24322]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-8](https://drive.google.com/drive/folders/1YuZ_PJFIEhmOuMhj55oh0lT3aL1uy6Tg)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Illiana health care
- [ ] Lovell FHCC health care
- [ ] VA Chicago health care
- [ ] VA Hines health care
- [ ] VA Iron Mountain health care
- [ ] VA Madison health care
- [ ] VA Milwaukee health care
- [ ] VA Tomah health care

Facilities include for System:
VA Illiana health care
- [ ] vha_550	Danville VA Medical Center
- [ ] vha_550BY	Bob Michel Department of Veterans Affairs Outpatient Clinic
- [ ] vha_550GA	Decatur VA Clinic
- [ ] vha_550GD	Springfield VA Clinic
- [ ] vha_550GF	Mattoon VA Clinic
- [ ] vha_550GG	Bloomington VA Clinic

Lovell FHCC health care
- [ ] vha_556	Captain James A. Lovell Federal Health Care Center
- [ ] vha_556GA	Evanston VA Clinic
- [ ] vha_556GC	McHenry VA Clinic
- [ ] vha_556GD	Kenosha VA Clinic
- [ ] TBD  USS Osborne Dental Clinic
- [ ] TBD  USS Red Rover
- [ ] TBD  USS Tranquillity
- [ ] TBD  Zachary and Elizabeth Fisher Medical and Dental Clinic

VA Chicago health care
- [ ] vha_537	Jesse Brown Department of Veterans Affairs Medical Center
- [ ] vha_537BY	Adam Benjamin Jr., Veterans' Administration Outpatient Clinic
- [ ] vha_537GA	Chicago Heights VA Clinic
- [ ] vha_537GD	Lakeside VA Clinic
- [ ] vha_537HA	Auburn Gresham VA Clinic
- [ ] vha_537QA	Chicago VA Clinic

VA Hines health care
- [ ] vha_578	Edward Hines Junior Hospital
- [ ] vha_578GA	Joliet VA Clinic
- [ ] vha_578GC	Kankakee County VA Clinic
- [ ] vha_578GD	Aurora VA Clinic
- [ ] vha_578GE	Hoffman Estates VA Clinic
- [ ] vha_578GF	LaSalle VA Clinic
- [ ] vha_578GG	Oak Lawn VA Clinic

VA Iron Mountain health care
- [ ] vha_585	Oscar G. Johnson Department of Veterans Affairs Medical Facility
- [ ] vha_585GA	Hancock VA Clinic
- [ ] vha_585GB	Rhinelander VA Clinic
- [ ] vha_585GC	Menominee VA Clinic
- [ ] vha_585GD	Ironwood VA Clinic
- [ ] vha_585GF	Manistique VA Clinic
- [ ] vha_585GG	Gladstone VA Clinic
- [ ] vha_585HA	Marquette VA Clinic
- [ ] vha_585HB	Sault Saint Marie VA Clinic

VA Madison health care
- [ ] vha_607	William S. Middleton Memorial Veterans' Hospital
- [ ] vha_607GC	Janesville VA Clinic
- [ ] vha_607GD	Baraboo VA Clinic
- [ ] vha_607GE	Beaver Dam VA Clinic
- [ ] vha_607GF	Freeport VA Clinic
- [ ] vha_607GG	Madison West VA Clinic
- [ ] vha_607HA	Rockford VA Clinic

VA Milwaukee health care
- [ ] vha_695	Clement J. Zablocki Veterans' Administration Medical Center
- [ ] vha_695BY	John H. Bradley Department of Veterans Affairs Outpatient Clinic
- [ ] vha_695GA	Union Grove VA Clinic
- [ ] vha_695GC	Cleveland VA Clinic
- [ ] vha_695GD	Milo C. Huempfner Department of Veterans Affairs Outpatient Clinic
- [ ] vha_695QA	Milwaukee VA Clinic

VA Tomah health care
- [ ] vha_676	Tomah VA Medical Center
- [ ] vha_676GA	Wausau VA Clinic
- [ ] vha_676GC	La Crosse VA Clinic
- [ ] vha_676GD	Wisconsin Rapids VA Clinic
- [ ] vha_676GE	Clark County VA Clinic
- [ ] vha_676QA	Tomah VA Mobile Clinic
