### ISSUE TITLE
[VAMC] VISN-1: VA New England Healthcare System - Web Modernization EPIC - [C2G]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24323]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-8](https://drive.google.com/drive/folders/1YuZ_PJFIEhmOuMhj55oh0lT3aL1uy6Tg)

## TASKS
See below associated tasks which should include, but are not limited to:
Tasks in this System included in order:
- [ ] Kickoff Meeting-	Comms
- [ ] Playbook & Staff Profiles-	Data
- [ ] Content write/build-	Content
- [ ] Build .csv files- 	Data
- [ ] **Migrate .csv files**-	**CMS**
- [ ] Stub out pages / Clone scaffolds (Clone, Map, fill out)-	Build
- [ ] Move Facilities under correct System (Consolidate?)-	Build
- [ ] Load Content-	Load
- [ ] Build Devshop environments-	Build
- [ ] Review/Clean up- 	Review
- [ ] (staging Review Requests)-	Issues to begin (1 sprint out)
- [ ] **Staging Review**-	**Platform**
- [ ] Clean-up from Staging	Review
- [ ] List of PAOs for Training sent to CMS training-	Training (update)
- [ ] Dual-state prep-	Dual-State
- [ ] Launch into Dual State-	Launch
- [ ] **508 compliance testing**-	Dual-State
- [ ] **Facilities 508**-	Michelle
- [ ] VAMC 508 compliance update (Content)-	Review
- [ ] Hand off Ownership-	Hand off ownership
- [ ] Support role PAO validation/build	Support issues/Copy edit
- [ ] Go-Live-	**Facilities**

**Systems of this Epic**
- [ ] VA Bedford health care
- [ ] VA Boston health care
- [ ] VA Central Western Massachusetts health care
- [ ] VA Connecticut health care
- [ ] VA Maine health care
- [ ] VA Manchester health care
- [ ] VA Providence health care
- [ ] VA White River Junction health care

Facilities include for System:
VA Bedford health care

- [ ] 518	Edith Nourse Rogers Memorial Veterans' Hospital
- [ ] 518GA	Lynn VA Clinic
- [ ] 518GB	Haverhill VA Clinic
- [ ] 518GE	Gloucester VA Clinic
- [ ] 523BY	Lowell VA Clinic

VA Boston health care

- [ ] 523	Jamaica Plain VA Medical Center
- [ ] 523A4	West Roxbury VA Medical Center
- [ ] 523A5	Brockton VA Medical Center
- [ ] 523BY	Lowell VA Clinic
- [ ] 523BZ	Causeway VA Clinic
- [ ] 523GA	Framingham VA Clinic
- [ ] 523GC	Quincy VA Clinic
- [ ] 523GD	Plymouth VA Clinic

VA Central Western Massachusetts health care

- [ ] Edward P. Boland Department of Veterans Affairs Medical Center
- [ ] Springfield VA Clinic
- [ ] Pittsfield VA Clinic
- [ ] Greenfield VA Clinic
- [ ] Worcester VA Clinic
- [ ] Fitchburg VA Clinic

VA Connecticut health care

- [ ] West Haven VA Medical Center
- [ ] Newington VA Clinic
- [ ] Waterbury VA Clinic
- [ ] Stamford VA Clinic
- [ ] Willimantic VA Clinic
- [ ] Winsted VA Clinic
- [ ] Danbury VA Clinic
- [ ] John J. McGuirk Department of Veterans Affairs Outpatient Clinic

VA Maine health care

- [ ] Togus VA Medical Center
- [ ] Caribou VA Clinic
- [ ] Calais VA Clinic
- [ ] Rumford VA Clinic
- [ ] Saco VA Clinic
- [ ] Lewiston VA Clinic
- [ ] Lincoln VA Clinic
- [ ] Bangor VA Clinic
- [ ] Portland VA Clinic
- [ ] Bingham Access Point
- [ ] Fort Kent VA Clinic
- [ ] Houlton VA Clinic

VA Manchester health care

- [ ] Manchester VA Medical Center
- [ ] Portsmouth VA Clinic
- [ ] Somersworth VA Clinic
- [ ] Conway VA Clinic
- [ ] Tilton VA Clinic

VA Providence health care

- [ ] Providence VA Medical Center
- [ ] New Bedford VA Clinic
- [ ] Hyannis VA Clinic
- [ ] Middletown VA Clinic

VA White River Junction health care

- [ ] White River Junction VA Medical Center
- [ ] Bennington VA Clinic
- [ ] Brattleboro VA Clinic
- [ ] Burlington Lakeside VA Clinic
- [ ] Littleton VA Clinic
- [ ] Keene VA Clinic
- [ ] Rutland VA Clinic
- [ ] Newport VA Clinic
