### ISSUE TITLE
Staging Review | Language Assistance and Resources | C&L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#24348]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [ ] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to VSP feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to product outline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/product-outline-working-drafts/markdown-version.md

- Link to Content Brief: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21306

- Link to the tool or feature in staging: 
https://staging.va.gov (footer)
https://staging.va.gov/asistencia-y-recursos-en-espanol/
https://staging.va.gov/tagalog-wika-mapagkukunan-at-tulong/

- Production URLs:
https://va.gov/asistencia-y-recursos-en-espanol (Spanish page)
https://va.gov/tagalog-wika-mapagkukunan-at-tulong (Tagalog page)
https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/ (Other languages)

-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link):

Footer Mocks:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23305

General Footer Updates: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23541

- Link to release plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/release-plan-language-assistance-pages.md 

- Link to your product test [case](https://dsvavsp.testrail.io/index.php?/suites/view/183&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1101)/test [plan ](https://dsvavsp.testrail.io/index.php?/plans/view/1868)in TestRail with test execution logs 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/use-cases-language-assistance-pages.md (draft)

- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/239) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/240) reports in TestRail _for QA practice area review_

- Link to verification that accessibility checks are complete:

  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR

  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): Sharon Kasimow
- DEPO Product lead (recommended): Danielle Thierry
- DEPO Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): name(s)Fareez Ahmed
- Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **date/time**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

**Requesting ~May 27~ June 3 at 2pm et**

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
@shiragoodman Hi Shira! I'm not quite ready to submit this ticket but since we plan to launch June 1st, wanted to officially get on the calendar for May 27 at 2pm et. Thanks!

**Comment by SKasimow** [comment]
@shiragoodman that sounds good! I still need to pull together some docs and get final URLs etc and just wanted to get it on the books while I work on the other stuff. Thx :)

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - can you take a look at the release plan I drafted when you have a chance? Thx

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. Yes, sure! Let's go over in our 1:1 tomorrow too just to make sure we're all set. Thanks!

**Comment by SKasimow** [comment]
@joshkimux Hi Josh...here's the link to a draft of the accessibility test cases. Once we have the translated URLs I will go back in and populate. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/language-assistance-pages-accessibility-testing.md

Sharon

cc @DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
@shiragoodman Hi Shira - once this ticket is ready I'll notify y'all in Slack.

**Comment by SKasimow** [comment]
Hi @tlei123 - I've drafted the use cases for this effort and listed in the ticket. I'm waiting for the translated URLs but thought I'd pass along the use cases now in the event you have some bandwidth to start planning for the test cases :)

cc @DanielleThierryUSDSVA

**Comment by shiragoodman** [comment]
thanks @SKasimow . We request 4 days notice meaning all artifacts should be ready by EOD today, or Monday morning.

**Comment by tlei123** [comment]
Hi, @SKasimow !  When will al the "TBDs" be completed for the [Use-Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/use-cases-language-assistance-pages.md)?

I can start putting test-cases together [w/ similar TBDs], but test-runs can't start 'till the above's provided.

Please let me know.  Thanks much!

cc @shiragoodman

**Comment by SKasimow** [comment]
@tlei123 Hi Tze - we hope to have early next week from the translation service vendor but don't have a hard date. I'll add in and flag you as soon as we get them. Bc of this, we've requested our staging review be moved out a week....

cc @shiragoodman @DanielleThierryUSDSVA

**Comment by tlei123** [comment]
@pjhill @ddzz , all QA test-runs now completed, and QA-artifact links updated above in main Description.

cc @SKasimow @shiragoodman

**Comment by mnorthuis** [comment]
No IA feedback, looks great!

**Comment by SKasimow** [comment]
Closing as complete.
