### ISSUE TITLE
Fix broken PDF link on caregiver page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24343]
## Issue Description
The link to the PDF for Form 10-10CG on the [Program of Comprehensive Assistance for Caregivers](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/) is broken and needs to be replaced.

New link: https://www.va.gov/vaforms/medical/pdf/VA%20Form%2010-10CG.pdf

## Tasks
- [x] Update link on page
- [x] Review and publish

## Acceptance Criteria
- [x] PDF link working on live page

**Comment by RLHecht** [comment]
This has been updated and I triggered a content release. FYSA @johnhashva

**Comment by RLHecht** [comment]
link is live on the site. Closing ticket.
