### ISSUE TITLE
[Campaign Landing Page Production MVP] - Pride & Discharge Upgrade

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#24350]
### Goal:
To provide LGBT Veterans with “bad papers” under DADT and other discriminatory policies with information on how to apply for a discharge upgrade. 

### What we want to do on this page:
To provide information, resources and a link to the online How to Apply for a Discharge Upgrade wizard.

## Key Info
** CMS Node **
https://prod.cms.va.gov/node/19951

**Who is Requesting**

- Requestor name: Kayla Williams, OPIA
- VA organization: OPIA
- Email address: kayla.williams9@va.gov / john.santos@va.gov 

**About the Campaign**

- Name or focus of Campaign
   - TBD, maybe a variation on We Serve All Who Served, or VA Takes Pride in Serving Veterans, or something more specific like Discharge Upgrades for LGBT Veterans. 
- Target audience(s) [up to 3]:
   - LGBT Veterans, their families/caregivers/supports, VSOs 
- Goals of the Campaign:  
  - To provide LGBT Veterans with “bad papers” under DADT and other discriminatory policies with information on how to [apply for a discharge upgrade. ](https://www.va.gov/discharge-upgrade-instructions/
- Campaign start and end dates: 
   - Pride Month - June 1-30, 2021
- Campaign page target launch date: 
  - June 1, 2021
- Preferred URL: 
   - www.va.gov/lgbt-discharge-upgrade
- What will you to drive awareness of this Campaign and this page? 
   - Social media, email, blog (planning to collaborate with DoD)
- What metrics will you want to know to measure success of the Campaign landing page? 
   - Click through from call to action would be great.

**About Your Campaign Page Build**

- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
  - Very -- the VA.gov Sitewide Content team will build the CLP on behalf of OPIA
- Who will build the campaign landing page in the VA.gov CMS?
  - Possible: @RLHecht 
- Who will review and give approval to publish the page? 
  - Kayla Williams
- Who will update/maintain the landing page during the campaign?
  - VA.gov Sitewide Content team
- At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved?  If preserved, why?
  - Preserved so the valuable information remains accessible

## What Needs to Be Done

- [X] CMS: Set up the CLP clone page in CMS for the build template - 
- [ ] Product: Get the Analytics dashboard set-up and obtain UTM URLs from stakeholder(s)
- [ ] Product & IA: Validate that the requested vanity URL is workable/optimal

**Comment by johnhashva** [comment]
@DanielleThierryUSDSVA (with @brianalloyd FYSA) -- the[ Discharge Upgrade Wizard at VA.gov ](https://www.va.gov/discharge-upgrade-instructions/) does contain a number of now out-of-date references and links that we are working to correct this week.  That said, Kayla is recommending we link instead to the various service sites for this process from the CLP.  Let's discuss when you can,     Here are the URLs for those service sites:

Department of Army:
Army BCMR:  https://arba.army.pentagon.mil/abcmr-overview.html
Army Discharge Review Board:  https://arba.army.pentagon.mil/adrb-overview.html

Department of Navy (Navy/Marine Corps)
Board for Correction of Naval Records: https://www.secnav.navy.mil/mra/bcnr/Pages/default.aspx
Naval Discharge Review Board:  https://www.secnav.navy.mil/mra/CORB/Pages/NDRB/default.aspx

Department of Air Force
Review Boards Agency:  https://afrba-portal.cce.af.mil/

U.S. Coast Guard
BCMR:  https://www.uscg.mil/Resources/Legal/BCMR/
Discharge Review Board:  https://www.uscg.mil/Resources/legal/DRB/#:~:text=The%20Coast%20Guard%20Discharge%20Review%20Board%20under%20Title,to%20review%20discharges%20or%20dismissals%20from%20the%20Service.

**Comment by johnhashva** [comment]
@brianalloyd formalizing here decision to:

1. Delay set up of a vanity URL redirect and the campaign UTMs until after June 1 launch as fast follow
2. Delay set up of analytics dashboard until after June 1 launch as fast follow

**Comment by brianalloyd** [comment]
Campaign launched, closing out ticket.

**Comment by brianalloyd** [comment]
Campaign launched, closing out ticket.
