### ISSUE TITLE
Content updates from stakeholders to Military Sexual Trauma page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24389]
## Issue Description
The VHA team had edits to the [military sexual trauma page](https://www.va.gov/health-care/health-needs-conditions/military-sexual-trauma/), which needed to be edited for plain language and VA.gov voice and style. 

VHA team member Robin Baker made the edits in Drupal, so we need to review and make edits there and send them a preview link with our updates.

## Tasks
- [x] Edit stakeholder changes (Danielle)
- [x] Copy edit (Randi)
- [x] Send to stakeholders for review (Randi)
- [x] Incorporate stakeholder feedback (Randi)
- [x] Send to stakeholders for final review (Randi)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Content changes on live site

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close after next deploy.
