### ISSUE TITLE
NOD: Add dynamic opt-in to new appeal process page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#24394]
## Description

In the updated Notice of Disagreement design, an opt-in page is only shown if any of the preloaded issues is determined to be within the legacy process, or any manually added issues have a decision date before the legacy cut-off date.

Note: We still need to determine the best method for determining if an issue is in the legacy appeals process.

Related:
- Design: https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292872

## Tasks

- [ ] Determined best method for classifying an issue as a legacy appeal
- [ ] Add opt-in page with a list of related legacy issues

## Acceptance criteria

- [ ] Legacy appeals page is appropriately shown to Veterans
