### ISSUE TITLE
[VAMC] Resolve 508/a11y duplicate health service (System and facilit) issues found in scans [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24390]
## Related 508 Issue
[#21789](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21789)

## Task

- [ ] Find and remove all duplicate System and Facility Health services
[Erie](https://www.va.gov/erie-health-care/locations/erie-va-medical-center/)
[Lebanon](https://www.va.gov/lebanon-health-care/health-services/)
[Lebanon](https://www.va.gov/lebanon-health-care/locations/schuylkill-county-va-clinic/)
[Lebanon](https://www.va.gov/lebanon-health-care/locations/york-va-clinic/)
[Montana](https://www.va.gov/montana-health-care/locations/hamilton-va-clinic/)
- [ ] Confirm with 508 issue

## Acceptance Criteria
- [ ] All duplicates are resolved and 508 issues is updated. 
- [ ] 508 issue is closed

**Comment by SgardnerPMP** [comment]
![Lebanon-Duplicate_HS.jpg](https://images.zenhubusercontent.com/5dae20cd6a7fc5000106eec0/f6bbe98b-87c5-46f0-b168-050d666cc241)

Example of duplicates created and resolved
