### ISSUE TITLE
Medallia IA Enhancements

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#24407]
## Issue Description
_As part of the staging review for Medallia surveys, and IA review was conduction. There were no *must* do changes, but are logging the *should* do recommendations here for future enhancements._

---
## Tasks
- [ ] _TBD as part of future Medallia enhancements_

## Acceptance Criteria
- [ ] _TBD based on recommendations below_

SHOULD
Intercept survey:

The second question is a follow up to the response of question 1, however, all of the responses to question 2 are positive experiences. If a user indicated that their experience was bad in the first question, none of the answers in 2 are appropriate. Question 2 should be clarified/revised.
In question 4, clarify what "interaction" you are referring to - was it generally "this visit to va.gov" or is this triggered from a specific interaction that can be named?
Feedback survey:

the rating numbers should have more spacing for tapping
CONSIDER
Intercept survey:

There is a small question mark icon in the lower left corner of the opening modal, but you cannot currently interact with it. It is small, but the modal has very little content, so it is noticeable. Is it intended to link somewhere or show something? Add a label or intended interaction for test.
Feedback survey:

Consider adding a heading to the modal
Consider reversing the order of the first 2 questions - the user can then indicate what their task was, then indicate if they were able to complete it.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Medallia 2.0 launched Q2 2024
