### ISSUE TITLE
govdelivery-tms prod gem major upgrade

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#24421]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the govdelivery-tms gem (production group) to it's latest major version 

---
## Tasks
- [ ] Open a PR with [govdelivery-tms-ruby](https://github.com/Granicus/govdelivery-tms-ruby) to relax their gemspec (<7.0.0 ?).
- [ ] CI make target passing locally 
- [ ] Reviewed gem change log updates

**Comment by LindseySaari** [comment]
The latest major version has a runtime dependency on `'activesupport', '>=5.2.4.3', '<6.0.0'` vets-api is currently on activesupport (6.0.3.7)
