### ISSUE TITLE
Design intent Debt Resolution Team - Medical Copayments

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#24438]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [ ] VFS: Link to this issue once created in #design in Slack; tag @vsp-product-support-members.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [ ] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [x] No - completely new functionality 
### Has your team met with Sitewide Content for content support?
- [ ] Yes*
- [x] No - completely new functionality

\*If yes, please be sure to include your Content brief (if available) and any other relevant artifacts

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Product_Outline_Medical_Copays.md)
- [Whiteboard sketch or other lo-fi prototypes or wireframes](https://miro.com/app/board/o9J_lFg6K9s=/) - PM Becca Walsh for password

## Meeting attendees from requesting team
- Designer(s) (required): Rebecca Walsh, Riley Orr
- Product Manager (required): Leah Keeler
- OCTO-DE Product Lead (recommended): Matthew Self
- OCTO-DE Design Lead (required): Ryan Thurlwell
- VFS content, IA, accessibility, and QA specialists (if applicable): 
- Other stakeholders you want to invite (if applicable): 

### What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
**Date/time:** First available slot (May 18th?) 
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@rebeccawalsh this has been scheduled for May 18th at 11:30 am EST

**Comment by allison0034** [comment]
@rebeccawalsh the whiteboard is prompting me for a password.

**Comment by denisecoveyduc** [comment]
According the the collab cycle tracker this design intent occurred on May 18, and therefore this can be closed
