### ISSUE TITLE
[Design] - Update facilities prototype to prepare for research study with VAOS team

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#24440]
**Background**
Now that we've completed our internal usability study, we need to update the prototype to reflect the recommendations that came out of the research.

**Tasks**
- [x] Update content/design to improve clarity around the impacts of editing. Make it more clear that editing does not delete or un-register any facilities
- [x] Add text above the facility list to clarify sort order
- [x] Review proposed changes with content
- [x] Make sure Peter gets updated files

**Comment by andaleliz** [comment]
Sent updated files to Peter today
