### ISSUE TITLE
[Discovery] - Learn more about facilities use cases uncovered during internal usability study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#24442]
**Background**
We ran an internal study that revealed some new use cases we hadn't yet considered:
- A user has registered at a new facility, but does not see this facility in their list
- A user has received health care at a VA, and therefore is registered at a facility, but is not currently enrolled in VA health care

We'd like to learn more about these use cases to see how we need to account for them in our tool.  Specific questions:
- How long does it take for new facility registration to reflect in MPI?
  - Is the timeline different if they register by phone or in person? 
  - Does it vary by facility?
- What is the VAOS UX for a person who has received health care at a VA, and therefore is registered at a facility, but is not currently enrolled in VA health care?
  - Do we still want to show this section to users who have health care but can't use VAOS?
- Should we still display this section to a person based on whether or not they're enrolled in health care, or do we need to update that logic?

**Tasks**

- [x] Document answers to questions above
- [x] Provide recommendations based on answers
- [x] Share with team

**Comment by andaleliz** [comment]
Reached out to Lauren and Peter to learn more about the VAOS UX for the person fitting the second use case above; Lauren will get back to me.

**Comment by andaleliz** [comment]
> How long does it take for new facility registration to reflect in MPI? Is the timeline different if they register by phone or in person? Does it vary by facility?

[From Danny Read in Slack](https://dsva.slack.com/archives/GM5JJ5388/p1620758554022000): there is NO delay in the updating of the VA MPI with the new VistA site, it is a real-time interaction between the VA MPI and VistA Registration process.  If something happens with communication there could be a delay because that identity is put into a queue and there is a background job that runs on an interval (10 min currently) but it could be longer if comms are down between that site and VA MPI but in most cases it should be immediate.

> What is the VAOS UX for a person who has received health care at a VA, and therefore is registered at a facility, but is not currently enrolled in VA health care? Do we still want to show this section to users who have health care but can't use VAOS?

A user can still get into the scheduling flow; appointment schedulers would handle any issues w/ them having an appointment.    Our team is using the same logic as VAOS to determine health care, so we don't have to worry about different experiences in each of our products.

> Should we still display this section to a person based on whether or not they're enrolled in health care, or do we need to update that logic?

We don't need to make any updates; I recommend moving forward with our plans as-is.
