### ISSUE TITLE
Publish V2 guidelines re: contributing to the Platform Website (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#24452]
# User story
As a VSP Team member, I need to know how to create and deprecate a page on the Platform Website, so that I can contribute to it (the Platform Website).

# Tasks
- [ ] Ensure the to-do's in Amy's list (below) are addressed
- ~Validate guidelines with Analytics~
- [ ] Share guidelines with Product Support 
- [ ] Revise guidelines based on feedback

# Acceptance criteria
To come.

# Reference info
- [to-do's before we share the guidelines](https://docs.google.com/document/d/16cUk5sV7uuNIX_5D_9o0YmL_wqYGxxGoHUl8MvUOFt8/edit#)
- [Prev discussion w/ FE T from 1/25/21](https://docs.google.com/document/d/1zJTgOjOen3rcVff7WzGgbFT-_EdIfzzmjfcFkrIBic4/edit#heading=h.gm6wccppji0h)
- Platform Website
  - [Scroll Viewport site](https://depo-platform-documentation.scrollhelp.site/index.html)
  - [Confluence editor](https://vfs.atlassian.net/wiki/plugins/servlet/ac/com.k15t.scroll.scroll-viewport/k15t-vpc-overview-page?ac.siteKey=8e2b7ad5-c76a-4167-95f1-97ea2f91dfa7)

**Comment by gmaciolek** [comment]
Based on very preliminary feedback, I don't think having people start out in the Platform website spaces is the right approach. I'd like to:
- Revise the docs to account for options re: where you can Prepare and Compose/Edit your docs.  I think people will naturally want to work on their docs in their personal or team space and then move them when they're ready.
- Talk to Andrea and/or Naomi about making our custom templates [global templates](https://support.atlassian.com/confluence-cloud/docs/create-a-global-template)

**Comment by lianilychee** [comment]
Tues 5/18:
- add expectation setting checklist (do, try, consider these things before publishing)

**Comment by lianilychee** [comment]
Weds 5/19:
- G
  - Yesterday made new version based on support with SD (aka start in personal space) https://vfs.atlassian.net/l/c/UdnKGMQL
  - Want to add something about adding media
- A
  - investigate if Amy can move something from Liani's personal space to a PW space (if G doesn't stumble upon)

**Comment by lianilychee** [comment]
5/20 Thurs:
- Gretchen
  - I did all the rejiggering moving spaces AND the new info follows the new support instructions 
  - I found a few links that weren't looking quite right (now that they're in the "how we work space")
  - GOAL FOR TODAY
    - update the media bullet
    - `Create a page` script
- Amy
  - goal for today
    - pulling useful content from SVP video we might want to incorporate
    - putting the script together for the `Overview` section
 
- in backwards planning:
  - ~8+ hrs of production for each video:  Finishing up the script, figuring out what visuals to show and when, recording

**Comment by lianilychee** [comment]
closing, since we are firmly preparing for training sessions now
