### ISSUE TITLE
Update FL architecture diagram

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24457]
## Issue Description
We need to update our arch diagram to add the online scheduling

---
## Tasks
- [ ] Add updated diagrams to [Technical documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/issue-response.md)

## Acceptance Criteria
- [ ] Technical documentation includes up to date architectural diagram 
- [ ] Existing documentation continues to exist to reflect the history/timeline
---

**Comment by mmiddaugh** [comment]
closing as duplicate to #27704
