### ISSUE TITLE
Changes to vaccine minihub 5/10/21

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24456]
## Issue Description
We made changes and updates to the vaccine mini hub around who can get vaccines at VA and the safety of the vaccines. 

## Tasks
- [x] Update vaccine mini-hub with approved changes (Danielle)
- [x] Review and publish (Randi)
- [x] Send text to translators (Randi)
- [x] Update chatbot (Selina)
- [x] Input translated copy to Spanish page (Selina)
- [x] Input translated copy to Tagalog page (Selina)
- [x] Review and publish Spanish and Tagalog pages (Randi)
- [x] Send live links to VHA translation team (Randi)

## Acceptance Criteria
- [x] Vaccine minihub has new content in all three languages
- [x] Chatbot is up-to-date

**Comment by lunascoop** [comment]
@RLHecht the chatbot has been updated. You and @DanielleThierryUSDSVA may want to review. **PR 383** _not 382_

Updated questions 

- 72, 73, 75 updated note on Janssen vaccine and link to "Vaccine safety" section on mini-hub page
- Added VRAPP question (q. 78)
- 69, 71 who can get a vaccine at the VA (added blue box content here)

**Comment by RLHecht** [comment]
@lunascoop I reviewed the PR and just updated the link that we changed on the vaccine page last night.

**Comment by DanielleThierryUSDSVA** [comment]
Hi again @lunascoop. We also received this content back from the translation team. 

[12524_VRRAP COVID FAQs question 5621 Tagalog Final](https://app.zenhub.com/files/133843125/b27992a1-c34d-4d3d-8653-b10ef25bada1/download)

[12613_Vaccine-page-updates_Tagalog Final](https://app.zenhub.com/files/133843125/faa3dd52-a456-4e53-b4bc-0f842f39cb25/download)

Here's the original doc that Randi sent so you can see where the updates are. Thanks!

[Vaccine-page-updates-51021](https://app.zenhub.com/files/133843125/6edd26e5-cbfb-4ac5-8f04-eac03b48fdb7/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Do you think you can update these pages tomorrow (5/26)?

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA 
I mixed up my tickets and was working on another ticket. Nevertheless, the pages are ready for review. The accordion for Can eligible adolescents ages 12 to 17 get a COVID-19 vaccine at VA? still needs to be translated.

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA Updates are live.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @lunascoop!

@RLHecht  For awareness: I copied you on the email to Chad sending the eligible adolescents content for translation. That batch also has the new mask question content in it. Sent on 5/24.

**Comment by RLHecht** [comment]
@lunascoop Here are the translations back for this work. 

[12753_VA.govcontent_Tagalog.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6584616/12753_VA.govcontent_Tagalog.docx)

[12752_VA.gov-content_Spanish Final .docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6584617/12752_VA.gov-content_Spanish.Final.docx)

**Comment by lunascoop** [comment]
@RLHecht the pages are ready for review.

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
@lunascoop the vaccine updates are reviewed and published. I'm going to close this ticket since we have the FAQs info in ticket #23761
