### ISSUE TITLE
Publish V2 guidelines re: how to conduct a content audit (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#24453]
# User story
As a Platform team member, I need to know how to conduct a content audit, so that I know which content my team is responsible for + what my team needs to transform.

# Tasks
- [ ] Validate with Product Support
- [ ] Share with Testing Tools Team
- [ ] Revise guidelines based on feedback

# Acceptance criteria
- We are ready to show-and-tell these guidelines to Platform team PMs in Sprint 53.

# Reference info
- [Audit your content [DRAFT]](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1246527612/Audit+your+content+DRAFT)

**Comment by lianilychee** [comment]
5/17 Mon:
- Amy to share with Joe in the public channel (vs DM)

**Comment by lianilychee** [comment]
5/18 Tues:
- Liani / Shira sync near end of day
- Testing Tools sync on Thursday
- Thoughts: 
  - Perhaps we can add editorial checklist guidelines here

**Comment by lianilychee** [comment]
No questions really from Testing Tools
