### ISSUE TITLE
Login.gov Research Plan

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#24532]
## Issue Description
As a designer I need to create a research plan to share with my team. 

---
## Tasks
- [x] Goals for research plan
- [x] List of research methodologies 
- [x] Find participants
- [x] Outline timeframe
- [x] Set team roles  

## Acceptance Criteria
- [x] Revise per meeting with Emily
- [x] Review with PM
- [x] Submit to Lauren for review and approval

**Comment by APorter-Clarity** [comment]
https://docs.google.com/document/d/1YwwcuXS5x55YHTcLh-hazUn5Lw-hYVxANG-9KmczoFY/edit

**Comment by APorter-Clarity** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login.gov/Login.gov-research-plan.md
