### ISSUE TITLE
Adjust RO for CH31 Pilot (May 24)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24539]
##  Background
The CH31 application (CMS) is phasing in their RO and need them added slowly to the wokr flow. 

## Considerations
- CMS will be rolled out to the first pilot station, **Cleveland**, on **Wednesday, May 12**.
- Below are the pilot kick off dates for the additional pilot stations, for awareness:
  - **San Diego** on **May 24**
  - **Denver** on **June 7**
  - **Columbia** on **June 21**

## Tasks
- [x] Update this [file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/veteran_readiness_employment_claim.rb#L9) with the appropriate RO
- [x] Request review and merge as needed

## Acceptance Criteria
- [x] RO has had their location added to receive CMS submissions
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
@jason-gcio can we please get confirmation that san diego is RO #377?  it is not obvious by the email address so I did a lookup, but just want to confirm.  Thanks!

**Comment by kathleencrawford** [comment]
@jason-gcio i should probably move this out of validate...should i put it in `blocked` or move back to `ready` for now?

**Comment by jason-gcio** [comment]
Yea, `blocked` works for now, I got it.
Thanks!
