### ISSUE TITLE
Login.gov Conversation Guide

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#24533]
## Issue Description
As a designer I need to create a conversation guide to prepare for user interviews and submit with research plan.

---
## Tasks
- [x] Gather information about the types of questions that are important to understand user pain points
- [x] Get information on questions that are valuable to the stakeholders and team
- [x] Write conversation guide for user interviews

## Acceptance Criteria
- [ ] Review with PM
- [ ] Submit to Lauren for review and approval
---

**Comment by APorter-Clarity** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login.gov/Login.gov-conversation-guide.md
