### ISSUE TITLE
Create Transaction IDs

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2454]
## User Story or Problem Statement
As a Veteran, I need to successfully complete transactions from start to finish without running into issues so I can submit the needed information.

## Goal
_Identify each transaction to allow for better resolution of errors that currently occur_

## Tasks
- [x] _Create Transaction IDs_
- [x] _Log Transaction IDs on va.gov_
- [x] _Identify what is needed from EVSS to pass along the the Transaction IDs_
- [x] _Create Issue(s) for additional work needed_

## Acceptance Criteria
Scenario: A user submits information but the system returns either a FE or BE error that is not traceable.
GIVEN that a user wants to submit information to VA 
WHEN an error occurs
THEN the system identifies the error
*and* records a Transaction ID

**Comment by YanaRoy** [comment]
@YanaRoy update AC

**Comment by YanaRoy** [comment]
May go beyond letters; have the errors show up on Sentry

**Comment by YanaRoy** [comment]
moving to benefits sprint 9 to allow for resolution of errors

**Comment by camerontesterman** [comment]
Tests that were originally broken, some of which were removed, have all been fixed and re-added, and are available to review in this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/3592
