### ISSUE TITLE
[Design, PM] Notification Prefs - Compile test case & test user documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24549]
## Background
We need to prepare documentation for staging test cases and corresponding test users. 

## Examples
- [My VA test cases and users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)
- [Direct Deposit for Edu use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/product/dd-e-use-cases.md) original spreadsheet linked in #16528

## Tasks
- [x] Compile staging test cases
- [ ] Identify corresponding test users
- [ ] Review with Samara

**Comment by andaleliz** [comment]
@ajakabcin I've added all the test cases I can at this time. Doc is ready for you to hunt down some users :)

**Comment by Samara-Strauss** [comment]
Can you move the test cases doc to the private repo? You can either document them in [the profile users document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile.md) or start a new one if you think the profile doc is getting too long. Sorry, forgot to specify this originally. It's just easier if all staging user documentation is in one place.

**Comment by Samara-Strauss** [comment]
☝️ and same goes for preferred facility test users

**Comment by ajakabcin** [comment]
Notification preferences test case documentation moved [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md)

**Comment by Samara-Strauss** [comment]
Thank you!

**Comment by ajakabcin** [comment]
great work on this @andaleliz thank you for getting us started! Going to close this until dev is underway and then we can get staging user info in there.
