### ISSUE TITLE
Create Visual Regression Testing Proposal

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#24553]
## Issue Description
Create a proposed solution to providing Visual Regression Testing as an additional service on the platform. Based on the research and spike created in other tickets under this Visual Regression Testing epic, generate a proposal document that includes details regarding product selection, cost, and implementation details.

---
## Tasks
- [ ] Select a commercial product for use on the platform
- [ ] Compare the features, cost, and implementation difficulty of the selected product to other products
- [ ] Include details of implementing the proposed solution on the platform including --
  * Hosting?
  * Who has access?
  * How is the solution incorporated into the build? vets-website? content-build? GitHub Actions?
  * Workflow/process for reviewing and resolving visual regression testing results?
- [ ] Provide an estimate as to the effort to implement the proposed solution

## Acceptance Criteria
- [x] A well-polished proposal document is available for review by platform leadership
- [x] The proposal includes information from all the task items
---

**Comment by pjhill** [comment]
Working on proposal here: https://vfs.atlassian.net/wiki/spaces/VI/pages/1488453727/Visual+Regression+Testing+Proposal

**Comment by pjhill** [comment]
Joe completed a final draft presentation in Google Slides [here](https://docs.google.com/presentation/d/1KYvgozLDzHwhZRUi4xAtjoIXS9y7JVb2dee-T_zZiDc/edit?usp=sharing).

**Comment by JoeTice** [comment]
Reopened to reflect Dror's requested changes in the proposal

**Comment by JoeTice** [comment]
Status Update: Proposal is on hold, pending a Percy Proof of Concept in GHA, and getting answers to questions about whether Percy metrics are accessible and usable in BigQuery
