### ISSUE TITLE
[FE] Preferred Facilities: Technical discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24559]
## Background

Frontend devs need to do some technical discovery in preparation for implementation of preferred medical facilities.

## Tasks

- [x] Review [Liz's frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/frontend/design-specs.md)
- [ ] Talk to Liz as needed about the design and how she sees the frontend working
- [ ] Talk to Lihan as needed about the backend integration

**Comment by tmitchellgcio** [comment]
Use [this link](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md) to get users for testing. I've had good luck using `judy.morrison@id.me` as the test user. She has two facilities in her user profile.

[Postman Collection Download](https://github.com/department-of-veterans-affairs/va.gov-team/files/6650617/VA.preferred.facilities.apis.postman_collection.json.zip)
