### ISSUE TITLE
Adjust GA Events for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24557]
## Background
We want to be able to track when a Veteran skips over the orientation content in Google Analytics.

## Considerations
The first one (`howToWizard-skip`) skips the wizard (all the radio buttons, etc), and the second one only skips the orientation because that link only shows up once they’ve completed all the wizard questions and it needs an event label (proposing `ch31-orientation-skip`).

## Tasks
- [x] Update the action link at the bottom of the wizard that takes a Veteran right into the form using `ch31-orientation-skip` as event names
- [ ] Discuss with GA Insights about whether this event name is ok to use, or if they prefer another

## Acceptance Criteria
- [x] Event name is there to track orientation skips
- [x] A PR has been requested for merging

**Comment by bsmartin-ep** [comment]
Sorry @jason-gcio, this seems to have fallen through the cracks.

Thoughts on something like `howToWizard-skip-orientation` so it can be reused for other wizards?

**Comment by jason-gcio** [comment]
Yea that might work although this orientation was a one-off and we should not see another component like this on VA.gov.

**Comment by bsmartin-ep** [comment]
@jason-gcio -

Sorry for the delay in getting back to you.  `howToWizard-skip-orientation` would definitely be easier to tag on our end.

I'm out next week but @laurensimpson14 can help QA this.

Lauren - I updated the lookup table in this GTM workspace:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000534

**Comment by jason-gcio** [comment]
@cohnjesse - just a heads up, does this help?
