### ISSUE TITLE
Authenticated Experience: Sprint 49 (6/2 - 6/15)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24561]
## Priorities

1. Position My VA for UAT by sprint 50
2. All other project work (preferred facility + notification preferences)
4. Profile work as time permits

## Time off

- AJ OOO 6/2 - 6/4
- Tressa OOO 6/10 - 6/17
- Erik OOO 6/10

## Onboarding
- [x] Taylor Mitchell #25000

## My VA redesign

**PM**
- [x] Hold UAT go/no-go meeting #24701 

**Design**
- [x] Attend UAT go/no-go #24701
- [ ] Kick off recruiting for UAT #24062
- [x] Plan discovery for how can we better elevate action items #24967
- [ ] Explore designs/sketches for how we can elevate action items #24970

**FE**

*Sprint 48 carry-over*

In Progress

- [x] Update "Next Appointment" widget header #24906

In "Validate"

- [x] Change keyboard focus to start in the banner/disability rating #24714
- [x] Health Care messages mismatch #24645 
- [x] "Must" Content feedback: Lowercase the S in service connected in top banner #24858
- [x] "Should" Content feedback: Link language doesn’t align and are inconsistent with the page's H1 they link to #24858
- [x] "Should" IA feedback: Correct inconsistent link labels #25071

*Sprint 49*

- [x] Update "Next Appointment" widget header #24906 
- [x] Stop calling GET v0/messaging/health/folders/0/messages if we don't need to #25170
- [x] Fix handling of 403s from secure messages API #25129
- [ ] Configure feature flags in staging and prod for My VA UAT #25817

## Notification Preferences
**PM**
- [x] Midpoint review (6/4, 2:00 PM)- #25313 
- [x] Create FE implementation tickets #25046

**Design**
- [x] Midpoint review (6/4, 2:00 PM)- #25313
- [x] Submit research plan + kick off recruiting #25366
_If time permits:_
- [ ] (Start) Conduct research/usability testing #25367

**FE**
- [x] Midpoint review (6/4, 2:00 PM)- #25313
- [ ] Start build:
     - [x] Redux actions and reducers #24863
     - [ ] High-level tests for FE #24864 
- [x] Create FE functionality implementation tickets #25046 

## Preferred medical facility

**PM**
- [x] Midpoint review (6/10 1:30 PM) - #25318 
- [x] Create FE implementation tickets #25043

**Design**
- [x] VAOS/profile facilities research sessions #25509
- [ ] VAOS/profile facilities research synthesis #25510
- [x] Midpoint review (6/10 1:30 PM) - #25318
- [ ] Update designs and FE documentation #25368

**FE**
- [x] Technical discovery #24559 
- [x] Create FE implementation tickets #25043

## Profile

**FE**
- [ ] 508-defect-1 ❗ Launchblocker [SCREEN READER, COGNITION] Unable to update address, phone number and email address. Silent error messages. #23252
- [x] Profile and My VA have inconsistent x-padding #24279

_If time permits_
- [ ] 508-defect-2 [HEADINGS, AXE-CORE]: Profile, heading levels should only increase by one #23756
- [ ] 508-defect-2 [AXE-CORE]: Autocomplete attribute must be used correctly for home address/mailing address checkbox #23173 

## Backend Work
 Lihan assisting the identity team
