### ISSUE TITLE
Alphabetize Vet Center services

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24579]
## Issue Description
Vet Center services need to be displayed alphabetically, within the type of care category. Currently, they seem to be displaying based on the order they were added. 

**Current behavior**
The  Counseling list ends with
...
Whole health
Women Veteran care
Couples and family counseling
Grief and bereavement counseling

**Expected behavior**
Couples and family counseling and Grief and bereavement counseling should appear in the Counseling list in alpha order (above Intimate partner violence support)

There is a "weight" attribute within CMS that should be ignored. Alpha order should be enforced on the front end. 

---
## Tasks
- [ ] Enforce the alpha display of services within the type of care category

## Acceptance Criteria
- [ ] the list of services under counseling should be in alpha order
- [ ] the list of services under referral should be in alpha order
- [ ] the list of services under other should be in alpha order
