### ISSUE TITLE
TUD: Bump dependencies from Dependabot security alerts

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#24586]
## Issue Description
Update Test User Dashboard dependencies & peer dependencies as stated by Dependabot's security review.

---
## Tasks
- [ ] Bump dependencies and peer dependencies
- [ ] Run `yarn audit`

## Acceptance Criteria
- [ ] Dependencies and/or peer dependencies are bumped
- [ ] TUD repository is in compliance
- [ ] Application functions as normal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
