### ISSUE TITLE
Update form name and link to Form 20-0998

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24596]
## Issue Description
Stakeholder Carolyn Temple informed us that there have been OAR revisions to Form 20-0998. It is updated on the find forms page but we need to update the name and the link on any other benefit detail pages where it's mentioned. 

The new form PDF: https://www.vba.va.gov/pubs/forms/VBA-20-0998-ARE.pdf
New form title: Your Right to Seek Review of Our Decision

## Tasks
- [ ] Search VA.gov for mentions of Form 20-0998
- [ ] Update link and title name
- [ ] Review and publish
- [ ] Alert stakeholder that changes were made

## Acceptance Criteria
- [ ] Form 20-0998 is using new PDF link and title

**Comment by RLHecht** [comment]
@kelsonic would you be able to do a search for us to see if this form shows up anywhere that I haven't already found? Besides find-forms, the only page I see it on VA.gov is https://www.va.gov/burials-memorials/pre-need-eligibility/after-you-apply/. I want to confirm that's correct and none slipped through. Thanks!

**Comment by kelsonic** [comment]
Hey @RLHecht! 🙂 I've responded here: https://dsva.slack.com/archives/C52CL1PKQ/p1620840808255100?thread_ts=1620839812.254700&cid=C52CL1PKQ

**Comment by RLHecht** [comment]
@johnhashva @MarciMcGuireGCIO I updated this form name on the form landing page but I don't know how it gets updated in the search results: https://www.va.gov/find-forms/?q=20-0998

Would you be able to fix this so that the form name is the new "Your Right to Seek Review of Our Decision"?

Thanks!

**Comment by johnhashva** [comment]
@RLHecht Interesting.  @MarciMcGuireGCIO the name has been modified by Randi in the CMS -- so I think this is a LH thing that we need to look into.

**Comment by MarciMcGuireGCIO** [comment]
@RLHecht - Looking at this now to see what's going on.

**Comment by MarciMcGuireGCIO** [comment]
@RLHecht cc @johnhashva - the search landing page data comes straight out of the CMS system while detail page data has to first get merged into the Lighthouse Forms API, which happens nightly.  Since the title was updated in the CMS this morning, it will update on the detail page overnight tonight.  Hope that helps!

**Comment by RLHecht** [comment]
@MarciMcGuireGCIO Thanks for looking into this so quickly.  I'll check back on Monday to validate that it's updated.

**Comment by MarciMcGuireGCIO** [comment]
@RLHecht happy to help!  That's perfect - let us know if you encounter any issues.  Occasionally a hard browser refresh (Shift + F5) is required to see recent changes.

**Comment by MarciMcGuireGCIO** [comment]
@RLHecht I just confirmed that the change happened overnight.

**Comment by RLHecht** [comment]
Work completed. Closing ticket.
