### ISSUE TITLE
Create Research Plan and Conversation Guide for Dependency Verification

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#24609]
### Background
The Dependency Verification flow required usability testing to ensure the user understands the purpose and function of the DV modal--as well as the follow-on add-remove functionality on the View Dependents page.

### Tasks
- [x] Create research plan
- [x] Create convo guide
- [x] Shawna review initiated

### Acceptance criteria
- [x] Research plan created
- [x] Conversation guide created

**Comment by candy-gcio** [comment]
Conversation Guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/research-design/usability-testing-1/dependent-verifiy-usability-1-convo-guide.md
