### ISSUE TITLE
[DESIGN] Spec for VAMC locations page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24605]
## Issue Description
We need to update the Locations page to separate mobile clinics from physical locations. The current page combines all types of locations under "Health clinic locations" heading. Example: [Cheyenne health care](https://www.va.gov/cheyenne-health-care/locations/)

---
## Tasks
- [x] Update VAMC spec with following headings
      - Main location
      - Health clinic locations
      - Mobile clinics

## Acceptance Criteria

Design spec is ready for engineering and includes the following

- [x] The VAMC system location page retains headings for "Main locations" and "Health clinic locations".
- [x] Displayed details are the same for locations listed under "Main locations" and "Health clinic locations"
- [x] VA Clinic locations listed under "Health clinic locations" are sorted alphabetically
- [ ] CLCs and Domiliciliaries (when relevant) are alphabetical below listed VA clinics
- [x] The VAMC system location page has a separate "Mobile clinics" heading.
- [x] Displayed details do not include address or link for directions for locations listed under "Mobile clinics" heading (but are otherwise the same)
- [x] Heading levels are specified 
- [x] Heading levels do not skip
