### ISSUE TITLE
EKS - Set up HPA for Grafana 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#24602]
## Description
Set up horizontal pod auto-scaling 

## Background/context/resources
When a deployment reaches a particular performance threshold, HPA will either scale the deployment up or down by adding additional pods. 

## Technical notes
For more info, read here: 
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

---
## Tasks
- [X] Set up an HPA resource (thresholds for memory/CPU, etc)
- [X] Set up a request in the deployment resource (has a memory/CPU tag which describes resources needed) 
- [X] Chart or other configuration that lives in the app manifest 

## Definition of Done
- [x] HPA is working for Grafana (able to scale, scaling active statuses will be attached to the HPA resource)

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by dginther** [comment]
HPA is up and running!
