### ISSUE TITLE
Address UI/UX feedback from LGY discussions

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#24603]
### Background
Received email from Kelli after an LGY/API call:

1. On Automatic COE screen, LGY will pass back from the Eligibility Determination API if the Veteran is eligible for a Restoration of Entitlement. If Vet is eligible, a question will need to be displayed as follows: “You are eligible for a restoration of entitlement, would you like to accept? Y/N”. This would need to be passed back from VA.gov to LGY.
2. On Automatic COE screen under where it states “What if I need to make changes”, replace the ‘Apply to make changes to your Certificate of Eligibility’ link with these questions instead (default answers to No). Based on the questions they answer Yes to, take them only to that screen(s) to make the changes rather than the whole application.
   - Do you wish to change First  or Middle Name? (if answered yes, would take them to the Applicant Info screen)
   - Do you wish to change Last Name? (if answered yes, would take them to the Applicant Info screen)
   - Do you wish to change Contact Information? (if answered yes, would take them to the Contact Info screen)
   - Do you wish to change Branch of Service? (if answered yes, would take them to the Service History screen)
   - Have you recently completed a tour and need to update the Service end date to remove the active duty condition from the Certificate of Eligibility? (if answered yes, would take them to the Service History screen)
3. On Service History screen under Branch of Service drop down:
   - Remove Reserves, Space Corp, Merchant Seaman from the available options
   - Change Marine Corps to Marines
4. On Loan Details screen, add VA Loan Number (not required)

### Tasks
- [x] Review feedback
- [x] Implement feedback within mockups if possible
- [x] Address revisions that could not be implemented

### Acceptance criteria
- [ ] Revised mockup available for review

**Comment by sporeboy** [comment]
Items 3 and 4 addressed. Need to discuss the a la carte form 'selector' feature (number 2). Need more info about number 1.

**Comment by sporeboy** [comment]
Set up a "screener flow" here: https://xd.adobe.com/view/565e79c8-7fa7-46af-806d-d3a8e3ba783c-030d/

In light of the new design direction from platform and content regarding the layout and functionality of the form system intro screen, a "screener" tool may not be tenable.

The trade-off of user convenience vs. technical hurdles may not be enough to justify this sort of pattern.

**Comment by sporeboy** [comment]
Form elements on the COE intro screen is a no-go due to PRA concerns.
