### ISSUE TITLE
LH API <> eBenefits: Representative

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24606]
## Background
The Lighthouse Team has done some work ahead of this feature's migration that will help move the structured data from OGC and onto VA.gov per a Veteran's needs.  This ticket serves as a vehicle to collaborate with Lighthouse and the eBenefits Team in getting the info out of OGC the most efficient way possible.

## User Story
As a Veteran I want to be able to view my currently assigned representative (either an individual or a VSO) including the name of the VSO as well as the phone number and email of the VSO.

## Tasks
- [x] Contact new LH PM
- [x] Read through documentation
- [x] Smoke test what LH has provided

## Acceptance Criteria
- [x] Establish the correct authentication method
- [x] Reach out to "Team Pivot" for further assistance (Derek Brown, per Jeff Wallace)

**Next steps**
- [ ] An endpoint has been provided that returns the name, phone number (if available), and email (if available) for a Veteran's current representative (either an individual or a VSO)
- [ ] The returned data for a Veteran's current representative (either an individual or a VSO) is added into the profile object

**Comment by markgreenburg** [comment]
- What should happen if a POA is unaccredited? Only accredited representatives are listed in the OGC data set we have. Unaccredited representation is claim-based (i.e., an unaccredited individual represents a specific claim rather than a specific Veteran)
- We have type data (attorney, claim agent, or VSO). Attorneys and claims agents generally have accredited individuals; VSOs generally have org-level accreditation rather than a specific name.

**Comment by markgreenburg** [comment]
- We would provide a service that could be used by a Veteran (or an accredited representative) to retrieve current POA information. However, we wouldn't be able to push that data into the profile object.

**Comment by jason-gcio** [comment]
> * What should happen if a POA is unaccredited? Only accredited representatives are listed in the OGC data set we have. Unaccredited representation is claim-based (i.e., an unaccredited individual represents a specific claim rather than a specific Veteran)  
**We only need to return what is listed on the Veterans profile which, presumably, can only come from the OGC list.  I assume that if who they have as their representative is not accredited, we would still show it.  This is at the individual level, not at the claim level.**
> * We have type data (attorney, claim agent, or VSO). Attorneys and claims agents generally have accredited individuals; VSOs generally have org-level accreditation rather than a specific name.  
**Data type might be an interesting attribute to account for for context/clarity...the main intent of the View task is to simply return who is attached for the purposes of making a change or contacting the representative with the associated info.**
> * We would provide a service that could be used by a Veteran (or an accredited representative) to retrieve current POA information. However, we wouldn't be able to push that data into the profile object.  
**I think that's fine, we want to update their profile with new rep info by submitting the 21-22a and getting that approved.  Here we just want to display.**

**Comment by jason-gcio** [comment]
@cohnjesse ☝️ that look right to you?

**Comment by jason-gcio** [comment]
Working with Jeff Wallace on authentication piece, still in setup phase
