### ISSUE TITLE
Revise Certificate of Eligibility mockups to function as usability prototype

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#24613]
### Background
The COE UXPin mockups need to be 'connected' to support usability testing of VA Form 26-1880. There are several potential user flows:
- Automatic COE
- Partial info available
- Full form walkthrough

### Tasks
- [ ] Rig mockups to function as a walkthrough prototype
- [ ] Address auto and form workflows
- [ ] Confirm logic and branch-points function correctly

### Acceptance criteria
- [ ] Functioning prototype ready for review/usability testing
