### ISSUE TITLE
Displaying access to care section when "null" (VAMC pages)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24626]
## Issue Description
The access to care section is displayed without data on VAMC pages. 

## Steps to reproduce

1. Visit the detail page for [Wheatland Mobile Clinic](https://www.va.gov/cheyenne-health-care/locations/wheatland-va-mobile-clinic/)
2. Scroll down to the "Veteran satisfaction with appointment wait times at this location" header (below the service list)
3. Observe intro text and headers for "Urgent care appointments" and "Primary care appointments" display without the data from access to care.

## Screenshots
![image](https://user-images.githubusercontent.com/55411834/118035558-954f5480-b328-11eb-8133-b6dec8cf1667.png)

---
Example from page with data: 
![image](https://user-images.githubusercontent.com/55411834/118036040-5077ed80-b329-11eb-8c32-98281052fa44.png)

## Expected behavior
- [ ] If access to care data is available, it should display
- [ ] If access to care data = "null", the entire section should not be displayed

---
## Tasks
- [ ] Suppress section if access to care data is not available

**Comment by mmiddaugh** [comment]
Resolved by fix for #26588
