### ISSUE TITLE
Adding link to vulnerability disclosure policy

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24621]
## Issue Description
We need to add a link to VA's vulnerability disclosure policy somewhere on our pages. The ask was to put it on our [privacy policies](https://www.va.gov/privacy-policy/) page but we will also put it on our R&S page on [privacy and security](https://www.va.gov/resources/privacy-and-security-on-vagov/).

Beth needs to follow up with the privacy office to determine if putting a link on the privacy policies page is OK, so we will start with just the link on the R&S page.

## Tasks
- [x] Review and publish link on R&S page (Randi)
- [x] Follow up with privacy office about link on privacy policies page (Beth)

## Acceptance Criteria
- [x] Links to vulnerability disclosure policy on appropriate live pages

**Comment by RLHecht** [comment]
@bethpottsVADEPO I published the R&S page.

**Comment by RLHecht** [comment]
This link was added to the privacy policies page. Moving to validate and will close after next deploy.

**Comment by RLHecht** [comment]
Live on the page. Closing ticket.
