### ISSUE TITLE
[UNPLANNED] Adjust 674 to be Explicitly Off-Ramped (686)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24624]
## Background
There are some peculiarities and nuance around how the 674 is being submitted and RBPS is making it muddy.  We want to set this to `MANUAL_VAGOV` for now.

## Tasks
- [x] Set the appropriate submission as `MANUAL_VAGOV` so the 674 presents as off-ramped.
- [x] Set the appropriate submission as `MANUAL_VAGOV` so any **non-ceremonial** marriage types presents as off-ramped.
  - common-law
  - tribal
  - proxy
  - other

## Acceptance Criteria
- [x] The 674 off-ramps for manual review
- [x] A PR has been requested for merging
