### ISSUE TITLE
Remove va_profile methods from User class

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#24622]
## Issue Description
As part of the larger refactor of the User & Identity at vets-api we are limiting direct access to a user's MPI profile from other parts of the system. With #18742 we have marked the `va_profile` methods within the User class as ready for deprecation and are periodically communicating this planned change via Slack; at the end of May 2021 we plan to remove these methods.

---
## Tasks
- [x] Remove `va_profile` method
- [x] Remove `va_profile_error` method
- [x] Remove `va_profile_status` method

## Acceptance Criteria
- [ ] The `va_profile` User methods will no longer be available for use
