### ISSUE TITLE
Communicating Check-in Ecosystem

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#24635]
## Product Links
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
Communicating check-in ecosystem plan. Refine MVP versus longer-term roadmap.  

## Tasks
- [x] Meet with VAOS, VeText, MyVA, mobile teams
- [x] Work with Ming on stakeholder communications and refinement of roadmap.
- [x] Update [Sketch document](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e) with user journeys, scope, and wireframes.
- [x] Hold meetings with engineering to craft backlog/determine spikes

## Acceptance Criteria
- [x] Meets are held
- [x] Sketch is up-to-date

**Comment by kristenmcconnell** [comment]
All intro meetings with other teams have occurred. Stakeholder meetings have occurred each Monday. Sketch has been continually refined. Two whiteboarding sessions occurred with engineering.
