### ISSUE TITLE
Clean up Vet Center implementation tech debt for Q and A content

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#24636]
The Vet Center content model uses a new centralized content data type, which can include many different kinds of data, including Q and A paragraphs.

In the process of implementing the Vet Center Q & A accordions, we chose to build a new component for handling this data, for 2 reasons:

1: the data is in a different format than our current component expects
2: we wanted to use the new `va-accordion` component, which is recommended for all new work by the design team.

This approach has the downside of "forking" the existing `q_a.collapsible_panel.drupal.liquid` component. We now have a `q_a.accordion_panel.drupal.liquid` component that is only used on vet centers. Ideally there should be only one q_a component. Also, the implementation is not flexible and does not dynamically support other kinds of CMS content that may be used in the future for the FAQ section (though that seems unlikely to change any time soon).

# Tasks

- [ ] Replace this [section](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/layouts/vet_center.drupal.liquid#L134-L148) of the vet_center.drupal.liquid with the following:

```
          {% include "src/site/includes/dynamic-content.drupal.liquid" with
            entity = fieldCcVetCenterFaqs.fetched
            contentType = fieldCcVetCenterFaqs.fetchedBundle
          %}
```
- [ ] Extend the `liquid.filters.processDynamicContent` function to transform the q_a contentType into the format expected by the `q_a.collapsible_panel.drupal.liquid` component
- [ ] Convert the q_a.collapsible_panel component to use the `va-accordion`

# Acceptance Criteria

- [ ] The Vet Center Q & A paragraphs still render and function correctly
- [ ] The code has been modified per the above tasks. Only one accordion component exists, and the template supports arbitrary dynamic content.
