### ISSUE TITLE
R&S Updates: Get a Premium My HealtheVet account

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#24666]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the live page. 

- Replace current CTA button with **Sign up for an account on My HealtheVet** 
-Add a 2nd CTA button: **Upgrade your account on My HealtheVet**

### Tasks

- [ ] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Please review and approve or edit the recommendations above so I can make the changes in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 We'd talked about this phrasing--"on" rather than "at":

Sign up for an account on My HealtheVet

Upgrade your account on My HealtheVet

**Comment by lwalsh617** [comment]
@RLHecht - I made the changes at the top of this ticket in Drupal and fixed a broken link. The page is ready for you to review and publish. Thank you!
http://preview-prod.vfs.va.gov/preview?nodeId=8507

**Comment by RLHecht** [comment]
Looks good @lwalsh617 ! I published. Moving to validate and will close ticket once changes are live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
