### ISSUE TITLE
Adjust Default RO Email Location

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24668]
## Background
For locations that do not have any Regional Offices we send to a generic email but it has been made known to us that that email address should actually be sent to Pittsburgh, and not the VBA front office.

## Tasks
- [x] Update the `'000' => 'VRE.VBACO@va.gov'` line with '000' => `'VRE.VBAPIT@va.gov'` in this [file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/veteran_readiness_employment_claim.rb#L9)

## Acceptance Criteria
- [x] Default emails are now sent to Pitt
- [x] A PR has been requested for merging
