### ISSUE TITLE
R&S Updates:  DS Logon FAQs

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#24665]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the live page. 

CTA button #1: Change label to:  
**Read more FAQs on the DS Logon website** 

Text links #2 and #3: Rework copy and links to make it clear user is leaving VA.gov:

To get a spouse or dependent added to DEERS, the Veteran will need to visit a personnel office (ID card office). They'll need to bring 2 original forms of ID to prove their identity.

Download the list of accepted forms of ID (PDF) 
https://www.cac.mil/Portals/53/Documents/List_of_Acceptable_Documents.pdf

Find a personnel office near you by visiting the ID card office website
https://idco.dmdc.osd.mil/idco/locator

 
H2: Will my DS Logon account or password expire?
After the answer, add link beneath speaks to creating a new password:

Create a new password on the DS Logon website
https://myaccess.dmdc.osd.mil/identitymanagement/consent?continueToUrl=%2Fidentitymanagement%2Fresetpassword.do

### Tasks

- [ ] SC to make change (Laura)

- [x] DEPO to approve change (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -  Please review and approve or edit the changes above so I can make them in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 
CTA: Read more FAQs on the DS Logon website

To get a spouse or dependent added to DEERS, the Veteran will need to visit a personnel office (ID card office). They'll need to bring 2 original forms of ID to prove their identity.

Download the list of accepted forms of ID (PDF) 
https://www.cac.mil/Portals/53/Documents/List_of_Acceptable_Documents.pdf
Find a personnel office near you by visiting the ID card office website
https://idco.dmdc.osd.mil/idco/locator

For the next one, a slight tweak:
Create a new password on the DS Logon website

**Comment by lwalsh617** [comment]
@RLHecht - I made the changes at the top of this ticket. The following Drupal pages are ready for you to review and publish. Thank you!
Multiple faq page: http://preview-prod.vfs.va.gov/preview?nodeId=8483
Single q&a:  http://preview-prod.vfs.va.gov/preview?nodeId=8481
Single q&a: http://preview-prod.vfs.va.gov/preview?nodeId=8479

**Comment by RLHecht** [comment]
Thanks @lwalsh617 These changes are all published. Moving to validate and will close after they are live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
