### ISSUE TITLE
R&S Updates: Change your address on file with VA

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#24663]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the live page. 

- Change CTA button copy to read: **Sign in to manage your VA.gov profile**

### Tasks

- [x] SC to make change in Drupal (Laura)

- [x] DEPO to approve change (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Once you approve this change, I'll make it in Drupal. Under **Tasks** above, do the steps look okay, or do you want to see the page again after Randi reviews it but before she publishes it? Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- I saw your note in Slack that you are good with the tasks I mentioned in my comment above. Can I go ahead and make the edit described at the top of this ticket and then have Randi review and publish?

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 This looks good, you can move forward with the button label change!

**Comment by lwalsh617** [comment]
@RLHecht - This page is ready for your review. Just the one change to the CTA button label at the top of this ticket.
Thank you!
 http://preview-prod.vfs.va.gov/preview?nodeId=8473

**Comment by RLHecht** [comment]
Changes look good. I've reviewed and published. Moving to validate and will close once live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
