### ISSUE TITLE
Technical Discovery for Content KPIs query standardization

### ISSUE THREAD

**Issue by JasonTheBearded** [department-of-veterans-affairs/va.gov-team#24673]
## Issue Description
How might we understand which Google Analytics data needs to be pulled into calculating metrics for Content KPIs?

---
## Tasks
- [ ] Review Audit to Content standardized queries
- [ ] Update any Content standardized queries where necessary

## Acceptance Criteria
- [ ] Platform Analytics has an outline for which interaction data should go into different KPIs

**Comment by JasonTheBearded** [comment]
[Link](https://docs.google.com/document/d/1--0ie8tWCXoiuXUl8n5wQYSNirTOe0H1Ti0Z3Ht-IaQ/edit) to technical discovery doc

**Comment by JasonTheBearded** [comment]
Tech discovery complete. Ready for design and dev.
