### ISSUE TITLE
[Design] Notification Prefs: Update FE documentation post-content & IA review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24696]
## Background
Following completion of content and IA review of notification preferences (#23286), there are some updates needed to the FE documentation.

Also be sure to:
- [ ] add a note in the frontend documentation about filtering the "Your health care" group based on whether someone is enrolled in health care or not (realizing this will not be perfect as we came across with Chuck in the preferred facility mini usability test)
- [ ] add a note reflecting we need to update documentation and mockups to show removal of mobile alert checkbox in contact information section

## Tasks
- [ ] Update [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/frontend) per final [IA recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/auth-profile-notifications.md#ia-design-and-recommendations)
- [ ] Update content documentation per content feedback

**Comment by andaleliz** [comment]
I've updated these docs with all the information I have so far.  The last bullet provides guidance for updating the "remove contact information alert" which may change depending on how we solve #23665. I've updated the tasks in that ticket to ensure we update these docs if needed.

@Samara-Strauss, @ajakabcin and @erikphansen, one thing I want to point out that changed in these docs is the [guidance for handling partial contact information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/README.md#partial-contact-info-missing-email-or-phone).  When we originally mocked this up, we didn't have any groups with only one notification.  I realized that if we have a single notification group, and a person is missing contact information for that channel, it's very poor UX to make them click an `edit` button only to see something that tells them they have to update their profile.  

The guidance I'm recommending is that we replace the on/off status message with text surfacing what they would have seen when clicking the edit button. I reviewed the copy + scenarios with a couple of designers, and Danielle and the [prototype for our usability study](https://preview.uxpin.com/5ecec4de6ec34eddc9f095677a881be3646124ce#/pages/139049744/simulate/sitemap?mode=i) reflects this recommendation.  I also created a [static mock-up](https://preview.uxpin.com/bb87d0fa61a32938a47e7bcdc836db235ab77576#/pages/139109897?mode=i) w/ some guidance to provide extra clarity.  

I'm going to close this (I expect another round of updates to these docs to come after usability testing), but am open to feedback/thoughts if what I described above doesn't seem like the best way forward.

**Comment by Samara-Strauss** [comment]
> The guidance I'm recommending is that we replace the on/off status message with text surfacing what they would have seen when clicking the edit button. I reviewed the copy + scenarios with a couple of designers, and Danielle and the prototype for our usability study reflects this recommendation. I also created a static mock-up w/ some guidance to provide extra clarity.

These look great, and I think the UX is super clear and will test well! Thank you for being so thorough!
