### ISSUE TITLE
Design intent [Facilities - VHA Mobile detail page]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24691]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Link to this issue once created in #design in Slack; tag @vsp-product-support-members.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [ ] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

### Has your product been reviewed by the OCTO-DE Design Lead? 
- [x] Yes (_This work is an iteration on the existing VAMC pages which have been reviewed and exist in Prod.)_
- [ ] No
### Has your team met with Sitewide Content for content support? 
- [x] Yes*
- [ ] No

\*If yes, please be sure to include your Content brief (if available) and any other relevant artifacts

## Artifacts
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-vha-mobile-redesign/initiative-brief.md)
- [Link to wireframes, mockups, or prototypes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-vha-mobile-redesign/initiative-brief.md#evidence-of-the-problem)
- User flow
- Any other artifacts you have so far

## Meeting attendees from requesting team
- Designer(s) (required): name(s) Leyda Hughes, Nick Osmanski
- Product Manager (required): Michelle Middaugh
- OCTO-DE Product Lead (recommended): Dave Conlon
- OCTO-DE Design Lead (required): Ryan Thurlwell
- VFS content, IA, accessibility, and QA specialists (if applicable): Shawna Hein, Josh Kim, Angela Fowler, Tze Lei
- Other stakeholders you want to invite (if applicable): name(s)

### What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
**Date/time:** Tuesday, May 25 at 11 or 11:30 AM ET
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@mmiddaugh this has been scheduled for Tuesday, May 25 at 11 AM ET

**Comment by mnorthuis** [comment]
No IA feedback at this time.  Looking forward to seeing what you learn in research!
