### ISSUE TITLE
Fix internal Heroku VA auth crashes

### ISSUE THREAD

**Issue by Teesh** [department-of-veterans-affairs/va.gov-team#24695]
## Issue Description
_The app is currently deployed on Heroku for authenticating and providing a token for developers for local app testing. The app crashes on attempting a token refresh. Testing is required to isolate the issues causing the crash and fix it._

---
## Tasks
- [ ] _Reproduce issue_
- [ ] _Find and document reason for crashes_
- [ ] _Fix code causing crash_
- [ ] _Perform regression testing on all app features_
- [ ] _(Optional) Update to modern [ES6 syntax](https://www.w3schools.com/js/js_es6.asp)_
- [ ] _(Optional) Add function headers and comments as needed_

## Acceptance Criteria
- [ ] _The app should not crash when attempting to refresh:_
    - [ ] _while the token is still valid (<1 hour)_
    - [ ] _once the token is expired (>1 hour)_
- [ ] _(Optional) The code is updated and commented_
- [ ] _All previous features should still work_
- [ ] _The app should still be deployable to Heroku_

**Comment by Teesh** [comment]
Running some tests and code changes produced the following results:
1. The session is timing out at 1 hour and any attempt to use refresh after that hour is causing the .refresh(0) to either fail and not error out or not fail because token is still valid, but on .redirect() the session itself is expired so dereferencing it causes a server crash. Added checks for existence of session and then redirecting to auth on false would solve this. Using the object?.prop notation (optional chaining) can help with that
2. The .redirect('/') everywhere is causing issues with the Express Sessions I believe, creating new session IDs and saving info in different sessions depending on order of operations. Ideally the view generation would be separated from the Express API and this wouldn't be an issue, but my current solution was to just call .render() in place of .redirect() to keep the session the same. Still testing this on more paths
3. The logout doesn't revoke the token on the auth server. Adding the the revoke URL and calling session.revoke() did not solve this, but my OIDC knowledge is limited

**Comment by Teesh** [comment]
Related WIP branch: [attempt-crash-fixes](https://github.com/adhocteam/va-mobile-sampleweb/tree/attempt-crash-fixes)
