### ISSUE TITLE
[Spike] Moving vaccine MVP to sustainment

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24707]
## Description

Timebox: 2 days

For a pilot and MVP, vaccine scheduling was created with a separate start CTA and scheduling flow. We need to do discovery to determine the steps and considerations for treating the vaccine and/or immunizations as any other type of care in VAOS.

![COVID-19 Sustainment.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/7aebec82-327e-48d9-9ca7-9335e6458e53)

---
## Tasks
- [ ] Document answer to questions:
- What are the steps to include COVID-19 vaccine as another option on the Type of Care page?
 - What are the considerations if we assume vaccines must remain direct scheduling only and all other types of care are requests only?
 - What are the considerations if direct scheduling is turned on for other types of care?
- What are our options for handling the rest of the pages in the flow? (keep separate, integrate into generic new appointment flow)
- How might we apply a "new" label to an option on the Type of Care page?
  - Can we set a duration on the label display so it will be removed from the UI automatically?
- [ ] Document any additional considerations/limitations for this work

- [ ] Document recommendation for technical approach

## Definition of Done
- [ ] Tasks are completed

**Comment by jbalboni** [comment]
# Integrated vaccine flow

## What are the steps to include COVID-19 vaccine as another option on the Type of Care page?

We have two main options. One is to fully integrate the vaccine flow into the new-appointment flow code. This would mean urls for the vaccine flow changing, events changing to be inline with the new appointment flow, and probably some slightly different logic to fit better into the new appointment flow.

If we do that, the steps are something like:

1. Add covid type of type of care enum and to type of care page
2. Add new flow type value to flow type enum?
3. Update new appointment flow with branching to go to the new vaccine flow pages
4. Update eligibility messaging to be appropriate for vaccines
5. Integrate vaccine logic and messaging into existing facility, clinic, and calendar pages, review, and confirmation pages
6. Determine how the flow should work for users who don't have facilities supporting online vaccine scheduling (i.e. should it be like the covid flow now or the way the new appointment flow is)
7. Update the CTA on the list page to point just to the new appointment flow again

Another option is to leave the vaccine flow separate, but add a covid type to the type of care page, and send users to the current vaccine flow if they choose that type. In that case, very little would change, except the new logic on the type of care page.

I think this second option is probably a good one to start with, but I'm not sure I'd want to leave it long term.


## What are the considerations if we assume vaccines must remain direct scheduling only and all other types of care are requests only?

We can add this logic in the eligibility check. We probably also want to tweak the logic for what eligibility messages we show, so that don't fall back to messages about why you can't make a request.

## What are the considerations if direct scheduling is turned on for other types of care?

Shouldn't impact this

## What are our options for handling the rest of the pages in the flow? (keep separate, integrate into generic new appointment flow)

Many of the pages for the covid flow are brand new, so we would just move those over.

Some pages are trickier, primarily the clinic choice, facility choice, and calendar pages. I think you could integrate some vaccine specific messaging into the current appointment flow pages, though that could be hard for the clinic page. So we might want to make a copy of that one.

## How might we apply a "new" label to an option on the Type of Care page? Can we set a duration on the label display so it will be removed from the UI automatically?

We could add a new label that disappeared after a certain date. Given that we can make tweaks to the UI with a less than 24hr turnaround, I don't think it saves much work, but it's not hard to do.

**Comment by jbalboni** [comment]
@laurenernest Do you have any further questions based on the above?

**Comment by jbalboni** [comment]
@laurenernest I think option 1 would be about the same amount of effort regardless of if we started with option 2. Either way, though, for option 1, I think we'd have to put most of the work behind a feature flag and then switch over once we moved all the vaccine logic over.

**Comment by laurenernest** [comment]
Let's start with option 2. Created these tickets:
#25375
#25380
#25382
#25383

Closing this ticket.
