### ISSUE TITLE
Staging Review [Authenticated Experience - My VA Dashboard 2.0]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24705]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to VSP feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
All artifacts listed [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/staging-review/artifact-prep.md)
- [Project Outline: My VA Dashboard 2.0 Redesign](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md)
- Feature in staging: [staging/va.gov/my-va](https://staging.va.gov/my-va/)
-  Staging test-user information: [My VA test cases and users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)
-  Link to content brief (if applicable): NA
-  My VA InVision documentation: [desktop](https://vsateams.invisionapp.com/console/share/SH10HT8JCKYM) and [mobile](https://vsateams.invisionapp.com/console/share/GC10HT8RSMQN)
- [My VA Dashboard 2.0 Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Release-Plan.md)
- [Test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/1799)
- [Test cases in TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1069)
- [Coverage for References Cases Report](https://dsvavsp.testrail.io/index.php?/reports/view/224) 
- [Summary Defects Report](https://dsvavsp.testrail.io/index.php?/reports/view/225)
- Link to verification that accessibility checks are complete: [My VA - Accessibility Staging Review Prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/staging-review/accessibility-test-prep.md) _(minor issues found and noted to be address in sprint 48 - see below)_
- List of known issues (found in QA and verification of accessibility checks)
    - Health Care messages mismatch #24645
    - Health care appointments mismatch #24646
    - IE11 styling anomalies #24647
    - Update Cerner alert header #24905 
    - Update "Next Appointment" widget header #24906 
    - Change keyboard focus to start in the banner/disability rating #24714

## Meeting attendees from requesting team
- Product Manager (required): @ajakabcin 
- DEPO Product lead (recommended): @Samara-Strauss 
- DEPO Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): @tressaellen  and @erikphansen 
- Content, IA, accessibility, and QA specialists (if applicable): @DanielleThierryUSDSVA,  @mnorthuis,  @joshkimux and @AngelaFowler82; @tlei123 

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **5/20 at 2pm**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by mnorthuis** [comment]
Hi @ajakabcin, the timeslot you requested on 5/20 is not available.  Would either of these times work for your team?
Friday, May 21 at 2pm ET
Monday, May 24 at 3:30 ET

**Comment by ajakabcin** [comment]
sure - let's grab Friday at 2pm. Thanks!

**Comment by mnorthuis** [comment]
Review has been scheduled for Friday, May 21 at 2pm ET.  Thanks!

**Comment by joshkimux** [comment]
@ajakabcin Would it be possible for us to [convert the test case and users doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md) into a more [accessible format for Angela's review?](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) The default passwords list is difficult to get through with a screen reader. Using a more list like format for tasks and user names/passwords would increase the likelihood of us completing accessibility feedback in time 🙇

**Comment by ajakabcin** [comment]
Connected with @joshkimux on slack about this - @tressaellen and I will review the accessible version to make sure there's nothing missing and will add the missing pw's.

**Comment by Samara-Strauss** [comment]
**PLEASE DO NOT POST ANY USER NAMES AND PASSWORDS ON THE PUBLIC REPO**. Please only post this in the private repo. Just wanted to catch this before anyone saved anything. If you put passwords in the public repo, we will have to get them all changed, and it's a huge PIA.

**Comment by ajakabcin** [comment]
Reiterating here for security reasons the accessible version of test case and user documentation is in the private repo

**Comment by Samara-Strauss** [comment]
I [renamed the file](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-passwords.md) so that it wasn't as confusing given that we already have staging documentation in this repo. I don't want people to get confused about which document is which (eg. is "dashboard" the same or different than "My VA").

Also, my gut is we should have *one* document, so if we can make one that is accessible and also has all the necessary info in it, great. I'll leave that up to you all to figure out. If you do end up consolidating everything into one document, please delete the extra document. Making sure the documentation is clean and there aren't multiple copies of everything will keep this info usable for everyone.

**Comment by AngelaFowler82** [comment]
Hey guys,

Am I supposed to not be able to view appointments for user15?



Huge thanks.

**Comment by Samara-Strauss** [comment]
@AngelaFowler82 appointments should not appear on the dashboard for user 15, but you should be able to see the link to schedule and view appointments. I see that, right now, that user is getting an error message for appointments on staging. I'm not sure why that is.

**Comment by AngelaFowler82** [comment]
I’m also getting an error when trying to sign into user377.

**Comment by Samara-Strauss** [comment]
What is the error?

**Comment by AngelaFowler82** [comment]
You have experienced an error

An error occurred while trying to link your IDME credential to the proper VA identity record.
If you need further assistance, please contact the HRC Helpdesk at 800-983-0937 7am-7pm Central Time.
Please be prepared to provide the following information to the Help Desk operator in your e-mail or phone call:

**Comment by Samara-Strauss** [comment]
Not sure what is going on, but I'll ask the platform team in Slack for help.

**Comment by AngelaFowler82** [comment]
Hello Samara, 

Sorry to bug you again, but for user ***@***.*** ***@***.***> , the 6 digit code is not populating. 

Angela

**Comment by Samara-Strauss** [comment]
@AngelaFowler82 which user? I see a bunch of asterisks. It's OK to put a user number or email in this ticket just as long as you don't include the password.

**Comment by AngelaFowler82** [comment]
***@***.*** ***@***.***>

**Comment by Samara-Strauss** [comment]
I'm not seeing an email address come through. All I see are asterisks, @ signs, and periods.

**Comment by AngelaFowler82** [comment]
Interesting. I’m literally copying and pasting the email address. Anyway, it’s the cerner user. The very first email address in the private repo.

**Comment by Samara-Strauss** [comment]
Got it! I was able to sign in with that user, so I'm not sure what's happening. Have you tried again and it still isn't working?

**Comment by AngelaFowler82** [comment]
It works now. Not sure what changed, but I’m glad it did.

**Comment by Samara-Strauss** [comment]
@AngelaFowler82 just wanted to follow up to let you know I still do not have resolution on user 377. I'm sorry for the inconvenience. I haven't forgotten about this, but no one seems to know how to help.

**Comment by AngelaFowler82** [comment]
No problem, I appreciate you looking into it. I wonder how necessary it is at this point since Dashboard has so few accessibility issues?

**Comment by Samara-Strauss** [comment]
User 377 is the only one with unread messages, so it's a very particular use case. I can't say whether it's necessary for accessibility testing, but it is for other testing we do, so I have to get the user fixed regardless. Up to you whether you consider it necessary for accessibility purposes or not!

**Comment by Samara-Strauss** [comment]
The issue with user 377 has been resolved, @AngelaFowler82, in case you still wanted to test that use case!

**Comment by AngelaFowler82** [comment]
Awesome! I’ll take a look.

**Comment by ajakabcin** [comment]
AE team has a path forward on all issues discussed at staging review. The following will be addressed prior to UAT:

- Investigate appointment Cypress tests #24960
- My VA v2 should not show a cancelled appointment #25279 
- Health Care messages mismatch #24645 
- Health care appointments mismatch #24646 
- IE11 styling anomalies #24647 
- "Should" IA feedback: Correct inconsistent link labels #25071 
- "Must" Content feedback: Lowercase the S in service connected in top banner #24858 
- "Should" Content feedback: Link language doesn’t align and are inconsistent with the page's H1 they link to #24858 
- Update Cerner alert header #24905 
- Update "Next Appointment" widget header #24906
- Change keyboard focus to start in the banner/disability rating #24714

The issue reported around the "find va benefits" feature will be addressed just before we launch My VA 2.0 (~sprint 50) #25149 

All other reported issues were not launch blockers but will be addressed accordingly post-launch as time permits.

**Comment by Samara-Strauss** [comment]
Thanks for this follow-up, @ajakabcin! I always forget — do we need to leave this open until all the issues are resolved, or can we close this in favor of tracking work in the tickets documented above, @shiragoodman?

**Comment by shiragoodman** [comment]
@Samara-Strauss you can close the ticket whenever you are ready. Platform will never close the ticket for you, so if you have a way to track work, then feel free to close this ticket.

**Comment by Samara-Strauss** [comment]
Great, thanks! @ajakabcin are we good to close? I don't want to close this prematurely if you'd prefer to keep it open.

**Comment by ajakabcin** [comment]
We can close! I have action items noted :)

**Comment by ajakabcin** [comment]
A phases launch of the product began on 6/30/21:

- Launched to 25% of users on 6/30/21
- Launched to 50% of users on 7/7/21
- Launch to 100% of users 7/14/21

cc @shiragoodman
