### ISSUE TITLE
Design Intent Review of "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2470]
## Goal
Present "View Dependents" screen layout to Design community.

## Task
- [x] Schedule time with **Shawna, Jennifer Strickland, **and** Emily W.** for review and feedback of  latest mockup for the "View Dependents." 
- [x] Gather and incorporate feedback to ensure consistent application of design system components. Troubleshoot potential design/development related issues. 
- [x] Communicate concerns regarding design/research constraints or roadblocks.

## Acceptance Criteria
- [x] Scheduled for 1/3/2020: conduct review session with **Shawna, Jennifer Strickland, **and** Emily W.**
- [x] Incorporate feedback and re-present layout as needed.

**Comment by sporeboy** [comment]
Review conducted 1/3. Ten participants in attendance. No direct feedback as of EOD 1/3.
