### ISSUE TITLE
Discovery: Get input from teams regarding Systems Integration Testing needs

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#24703]
## Issue Description
As we plan a solution for System Integration Testing on the platform, we need feedback from external services/teams. Acceptable response rate should be defined based on findings of [#24568](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/24568)

---
## Tasks
- [ ] Send out survey to the groups (OCTO-DE Lead and T3 PM)
- [ ] Follow-up w/ teams until required response rate and/or timeframe is reached (OCTO-DE Lead and T3 PM)
- [ ] Compile findings
- [ ] Summarize, discuss next steps based on findings
- [ ] Report findings to wider audience as needed

## Acceptance Criteria
- [ ] Findings are reported to teams
- [ ] Any findings and subsequent direction from stakeholders is incorporated into findings
