### ISSUE TITLE
Bugfix - 686c - Remove formSaved entry from user profile on successful submission

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#24715]
`discuss as team to ensure this doesn't have a negative impact on a future Veteran experience`

## Description
During integration testing we discovered a bug that breaks the 686 after clicking `continue application`. The reason for this is that the 686 entry in `user.profile.savedForms` isn't cleared once a user successfully submits a 686 and hits the confirmation page. Because of this, the 686 intro page will render a `save-in-progress` box with the option to continue but no associated `returnUrl` from `save in progress data`. 

## Considerations
This is in place to give the Veteran a chance at not having a ton to fill in if the  submission was NOT successful...it takes some time to determine that.

## Steps to reproduce
1. Log into https://staging.va.gov/view-change-dependents/add-remove-form-686c/introduction
2. Fill out a 686c with any workflow and submit
3. Go back to the introduction page, note the blue box with option to continue the application
4. Click `continue`
5. Form breaks.

## Potential fix
- clear the 686c-674 entry from `user.profile.savedForms` on the backend after a successful 686 submission.
or
- return them to the review and submit page 

## Tasks
- [x] Schedule a team meeting, and discuss
- [ ] clear the 686c entry on the backend once successfully submitted (STRETCH)

## Acceptance Criteria
- [x] A team meeting has been scheduled
- [x] The Veteran is given a clear path upon coming back from the submission page so the form (STRETCH)
- [ ] A PR has been requested for merging, if needed

**Comment by jason-gcio** [comment]
BE/FE (Micah) to look into "in progress forms" component for failed situations (CH31, CH36)
- clearing saved forms for CH31 + 36

**Comment by jason-gcio** [comment]
BE needs to test in the event of a submission failure and ensure that a valid return url is being returned (686)
