### ISSUE TITLE
[Documentation] Review existing cluster set up process and update to ensure accuracy

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#24728]
## Description
There are some aspects of EKS cluster setup that could likely be further improved with clean-up, automation, or other workflow customization. 

## Background/context/resources
Some of the manual steps that we're aware of are replacing the AWS CNI w/ Calico CNI, as well as how we're managing which users can access the cluster (security). 

[Existing doc in Confluence](https://vfs.atlassian.net/l/c/gt91qgA0)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Review existing doc
- [ ] Clean up  

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
There is existing documentation that lives in Confluence and that we are updating on an ongoing basis. 

Closing.
