### ISSUE TITLE
Create Conversation Guide (View Dependents)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2472]
### Story  
As a design researcher, I want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users I will be communicating with.

### Task
- Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery-conversation-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
- [ ] Connect with Parigean
- [ ] Schedule user interviews
  - Determine the right number of users to connect with
  
### Acceptance Criteria
- [ ] Conversation Guide has been reviewed by Shawna
