### ISSUE TITLE
[UNPLANNED] Add Address to Silent Fail Email

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24738]
## Background
In order to test when a submission occurs and a bad SSN is used for the dependent (currently submits the PDF but does not create a claim; effectively ghosting the Veteran's application if we don't send an email letting them know).

## Tasks
- [x] Add jason.wolf@va.gov and kathleen.crawford@va.gov to be cc'd to the silent failure email to check.

## Acceptance Criteria
- [x] Jason and Kathleen can see silent failures as we test
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
Next test to do for this would be to add a child that is already too old, with the wrong SSN"
Then run it again, that same day, with the correct SSN.
Check for emails in case the pdf gets sent off and no EP code gets generated.
