### ISSUE TITLE
Vet Center operating status icon: ARIA is hidden

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24748]
## Issue Description
This issue was found during testing in preparation for staging review. 

**Defect**
The icon and chevron used with the operating status are not presented to screen reader users. 

![image](https://user-images.githubusercontent.com/55411834/118335065-08450080-b4cc-11eb-8c2f-ed9cef7d56d7.png)

**Code**

`<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>`
`<i class="fa fa-chevron-right vads-u-padding-left--0p5" aria-hidden="true"></i>

---
## Tasks
- [ ] If the icon is intended to be presented, announce icon. 
- [ ] Announce expandability of operating status 

## Acceptance Criteria
- [ ] Veterans using screen readers understand an alert is present on the page and how to open it for more information. 
---

**Comment by mmiddaugh** [comment]
Closing this one as we will incorporate accessibility into the expandable alert implementation
