### ISSUE TITLE
Create VEO Contact Center Virtual Training

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#24757]
## Issue Description
_As part of our effort to improve contact center resources, we will be creating training (and related documentation) to provide oral and written training to VEO trainers_

---
## Tasks
- [ ] _Create the virtual training for VEO contact center per the plan outlined in [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23946) ticket._

## Acceptance Criteria
- [ ] _VEO contact center virtual training materials are created_
- [ ] _Training session is scheduled_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Met with Chante, Kimberley, Caroline and Sam re. training; have plans to sit in on next New Hire session in June. Sam will forward class information once it is finalized.

**Comment by starlow00** [comment]
Followed up with Sam and Caroline re. itinerary for New Hire training.

**Comment by starlow00** [comment]
Relevant New Hire training will begin on 6/7. Caroline will send a more specific itinerary with times.

**Comment by starlow00** [comment]
@Kimberley2019 and @clantosswett , here's a draft of a training module for "Not Tier 2" involving the ID verification services. I tried to make it something that would fit in amongst other training materials like those used for the New Hire training. Videos and quiz questions can be added, but I figure we'll discuss that in our meeting.

[Not Tier 2 Presentation Example.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6696824/Not.Tier.2.Presentation.Example.pptx)

**Comment by clantosswett** [comment]
Hi @starlow00 this presentation is great. I made some comments on the attached version of it that I think will help round out the material. Let me know if you have any questions about it. Thanks!

[Not.Tier.2.Presentation.Example_cls.edits.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6729333/Not.Tier.2.Presentation.Example_cls.edits.pptx)

**Comment by starlow00** [comment]
Incorporated edits from Chante, sent to VEO for review prior to sync meeting.

**Comment by starlow00** [comment]
Sam A. mentioned in VEO sync meeting that he is sharing the first training module with the training team. Attached is the file
[Not-Tier.2-Presentation-Example.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6786357/Not-Tier.2-Presentation-Example.pptx)
