### ISSUE TITLE
[Content-Load-Review] Load content and Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA Dublin health care.

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24767]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[VISN-7 Content folders](https://drive.google.com/drive/folders/1yihJnU99DrVPv6VxmYKSf3Ky4-Nypv4z)

## Tasks
* Load prepared content for the following pages:
- [x] About
- [x] Work With Us
- [x] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: 
- [x] vha_557	Carl Vinson Veterans' Administration Medical Center
- [x] vha_557GA	Macon VA Clinic
- [x] vha_557GB	Albany VA Clinic
- [x] vha_557GC	Milledgeville VA Clinic
- [x] vha_557GE	Brunswick VA Clinic
- [x] vha_557GF	Tifton VA Clinic
- [x] vha_557HA	Perry VA Clinic

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [x]  Location Listing Page 
- [x]  History    
- [x]  Internship and Fellowship 
- [x]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x]  System Page 
- [x]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [x]  Mission-Vision 
- [x]  Leadership Listing Page 
- [x]  Policies Page (Should be new hardened format)
- [x]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [x]  Performance Page
- [x]  Make an Appointment
- [x]  Register-for-Care
- [x]  Billing
- [ ]  Contact-us		
- [x]  Dav-vans
- [x]  Medical-Records
- [x]  Operational Status
- [x]  Pharmacy
- [x]  Caregiver
- [x]  Homeless
- [x]  LGBT
- [x]  Mental
- [x]  Minority
- [x]  Patient
- [x]  Returning Service member
- [x]  Suicide prevent
- [x]  Women-vet
- [x]  Campus Map
- [x]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.
