### ISSUE TITLE
[Content-Load-Review] Load content and Internal Review, Proof read and correct plain language and common sence conntent on all pages for VA Charleston health care.

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24765]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[VISN-7 Content folders](https://drive.google.com/drive/folders/1yihJnU99DrVPv6VxmYKSf3Ky4-Nypv4z)

## Tasks
* Load prepared content for the following pages:
- [x] About
- [x] Work With Us
- [x] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: 
- [x] vha_534	Ralph H. Johnson Department of Veterans Affairs Medical Center
- [x] vha_534BY	Savannah VA Clinic
- [x] vha_534GB	Myrtle Beach VA Clinic
- [x] vha_534GC	Beaufort VA Clinic
- [x] vha_534GD	Goose Creek VA Clinic
- [x] vha_534GE	Hinesville VA Clinic
- [x] vha_534GF	Trident 1 VA Clinic
- [x] vha_534QA	Market Commons VA Clinic
- [x] vha_534QB	Trident 2 VA Clinic
- [x] vha_534QC	Charleston VA Clinic

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [x]  Location Listing Page 
- [x]  History    
- [x]  Internship and Fellowship 
- [x]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x]  System Page 
- [x]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [x]  Mission-Vision 
- [x]  Leadership Listing Page 
- [x]  Policies Page (Should be new hardened format)
- [x]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [x]  Performance Page
- [x]  Make an Appointment
- [x]  Register-for-Care
- [x]  Billing
- [x]  Contact-us		
- [x]  Dav-vans
- [x]  Medical-Records
- [x]  Operational Status
- [x]  Pharmacy
- [x]  Caregiver
- [x]  Homeless
- [x]  LGBT
- [x]  Mental
- [x]  Minority
- [x]  Patient
- [x]  Returning Service member
- [x]  Suicide prevent
- [x]  Women-vet
- [x]  Campus Map
- [x]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.

**Comment by larrywest52** [comment]
Reviewed content on all pages and posted the review doc to our team share.
