### ISSUE TITLE
[VAMC-Content] Document intent and purpose of each page and area in the page for VAMC [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24769]
## Story
As a content management maintainer and Veteran, the VAMC webpages must have a clear purpose and intent, so I can clearly communicate needs and directions to and for the Veteran

## Goal
Document the intent and purpose of not only the page itself, but how the page is developed to be used.  Both Nationally, regionally, and locally.

## Tasks
**Review the following pages and:
- [x] Document and explain using Power Point and notes the overall purpose of the VAMC page
- [x] Utilize/reference content design document for format (Summary, intent,  Highlight "Like this,  Not Like this"
- [x] Reach out to Analytics to provide examples of how areas have been misused.
- [x] Document and explain (provide examples if possible) break down how each area of the page is meant to be used (intent and purpose)
_
**Pages to be included**
Core Pages
- [x] VAMC System Page
- [x] VAMC Operating Status
- [x] Facility page (Plan for your visit)
- [x] Performance

Listing Pages
- [x] Health Services 
- [x] Leadership
- [x] Locations
- [x] Events
- [x] News releases
- [x] Stories

Main Content
- [x] About us
- [x] History
- [x] Work with Us
- [x] Jobs and Careers
- [x] Internship and Fellowship
- [x] Volunteer and Donate
- [x] Doing Business with us
- [x] Chaplain
- [x] Mission and Vision
- [x] Policies
- [x] Programs
- [x] Research 
- [x] [Medical Center] Campus Map

Health Service Program pages
- [x] Caregiver Support
- [x] Homeless Veteran Care
- [x] LGBT-Veteran-Care
- [x] Mental Health-care
- [x] Minority Veteran Care
- [x] Patient-advocates
- [x] Returning-service-member
- [x] Suicide-prevention
- [x] Women-veteran-care
- [x] COVID-19 vaccine

Top Task pages
- [x] Make an Appointment
- [x] Register for Care
- [x] Billing-Insurance
- [x] Contact Us 
- [x] DAV-VAN (Transportation) 
- [x] Medical records
- [x] Pharmacy

## Acceptance criteria
- [ ] All pages have been documented.
- [ ] Output should be
