### ISSUE TITLE
VFS Support Reporting POC in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#24760]
## Issue Description
_In an effort to reduce the number of issues Veterans experience while trying to complete tasks on VA.gov, we are working to provide meaningful reporting to VFS teams about reported issues related to their products._

---
## Tasks
- [x] _Get support data set in DOMO_
- [x] _Build at least one view which segments support cases by category and sub-category_
- [x] _Determine if we can segment data clearly by team/product/etc for viewer relevance_

## Acceptance Criteria
- [x] _We have created at least one dashboard with contact center support data to the sub-category level_
- [x] _We have made a determination on if we can clearly segment contact center support data by team/product_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Working [DOMO dashboard for SF Issues](https://va-gov.domo.com/page/130739792)
