### ISSUE TITLE
Add filter to VAMC Meta title tags

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24796]
## Issue Description
The [design system](https://design.va.gov/content-style-guide/seo#title-tags) includes initial caps for title tags but the VAMC product has an exception and prefers sentence case. CMS dictates the meta title tags without editor input as sentence case. We need to apply a filter to meta title tag data to add capitalization to display the initial caps. 

This change will impact all templates (which is not be a bad thing). 
The field to be referenced will not change. 

Need to take care with intentional capitalizations (ie: Raleigh III Clinic)

Meta descriptions are not in scope for this issue. 

CMS work includes: removal of fields, remapping of meta_tags -> their work is not a pre-req/dependency
(output will be sentence case)

---
## Tasks
- [ ] Add filter to convert meta title tags to enforce initial capitalization case
- [ ] Work with Public Websites to confirm template impact

## Acceptance Criteria
- [ ] Meta title tags use initial case
- [ ] Capitalization which is sent from CMS (ie: acroynms) is retained 
- [ ] "And" is capitalized per the design guide (i.e. Prescription Refills And Tracking)

**Comment by mmiddaugh** [comment]
This work was recently completed by PW
