### ISSUE TITLE
Support Typeahead Rollout Changes

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24801]
## Description

As a product team we encountered unexpected changes during our roll out of type ahead 1.0 which required coordination with search.gov and development effort  to address. 

## Tasks

- [x] Fix typeahead rate limit issue by coordinating with Search.gov to identify route cause of 429 errors
- [x] Add error logging into sentry to highlight 429s
- [x] Monitor Sentry logs
- [x] Adjust debounce and query rates to meet experience needs

## Definition of Done

- [x] Rate limits are no longer an issue and are not blocking launch of typeahead

**Comment by srsuddath** [comment]
closing this as we have supported this rollout throughout the sprint
