### ISSUE TITLE
NOD: Add issue summary page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#24810]
## Description

Add selected issues summary page.

Design: https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292874

## Tasks

- [ ] Add issue summary page
- [ ] Minor cleanup of other sections

## Acceptance criteria

- [ ] Veterans can review their chosen selection before proceeding
