### ISSUE TITLE
NOD: Update upload file types

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#24818]
## Description

Lighthouse only supports PDF file types for Notice of Disagreement evidence upload. Update the list of file types.

Ref: https://dsva.slack.com/archives/CSKKUL36K/p1620856679016100?thread_ts=1620853259.015800&cid=CSKKUL36K

## Tasks

- [ ] Change file type list to only include PDF
- [ ] Update unit tests

## Acceptance criteria

- [ ] Only PDF shown to Veteran
