### ISSUE TITLE
[Discovery] Unpublished content on Stories, News Releases and Detail pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24811]
## Issue Description
We've addressed other defects caused by the appearance of unpublished content (events, services, staff profiles). To attempt to proactively address any further occurrences, we need to check the pages where draft/archived content is most likely to be present. 

Displaying unpublished content may cause the page to be available on the site map or in Google results - or in the release of embargoed content. 

### Known issue: 
- ~~Stories in review, i.e.:  /pittsburgh-health-care/stories/vaphs-foreman-fights-covid-19-in-new-jersey/~~ - _update: the page in review is_ /pittsburgh-health-care/stories/vaphs-foreman-fights-covid-19-in-new-jersey-0 _which is not published._ 
- Never published, status = in review
<details> 
</summary> Screenshot from CMS </summary>

![image](https://user-images.githubusercontent.com/55411834/118685484-5e61be80-b7c0-11eb-85d9-dc670172e40b.png)
</details> 

---
## Tasks
- [x] Investigate options for filtering unpublished story content
- [x] Check the following areas for `isPublished = true` filters (none of the following are rendered on prod at this time - let's confirm the filter is in place). See comments for updated examples.
- detail pages 
  - [x] archived page, i.e: /new-york-harbor-health-care/internships-and-fellowships 
  - [x] draft detail page, i.e: (TBD)
- news releases 
  - [x] draft news release, ie: /texas-valley-health-care/news-releases/vha-observes-75-years-1-billion-hours-of-volunteerism 
  - [x] archived news release, ie: central-arkansas-health-care/news-releases/virtual-town-hall-discusses-vaccine-hesitancy-for-bipoc-veterans
- stories 
   - [x] archived story, ie: /wilmington-health-care/stories/veteran-presents-flags-to-va-health-care-workers-0 
   - [x] draft story, ie:  /kansas-city-health-care/stories/kansas-city-sets-the-platinum-standard) 
   - [x] in review story, /pittsburgh-health-care/stories/vaphs-foreman-fights-covid-19-in-new-jersey/ 

## Acceptance criteria
- [x] Unpublished content does not display on Prod
- [x] Previously published versions of content, which may be in editing mode, are still displayed.

**Comment by mpelzsherman** [comment]
The sample story provided, /pittsburgh-health-care/stories/vaphs-foreman-fights-covid-19-in-new-jersey/, has been published in production.

The best way to test this is to use tugboat.

It's very time consuming to troubleshoot this because we can't use the preview server.

**Comment by mpelzsherman** [comment]
Here's a link that shows all of the News Stories that are in Draft mode:

https://prod.cms.va.gov/admin/content?title=&type=press_release&moderation_state=editorial-draft&owner=All

So far I haven't found any examples of these showing up in production.

**Comment by mpelzsherman** [comment]
Draft detail page: 

https://prod.cms.va.gov/bronx-health-care/doing-business-with-us

... does not appear on https://www.va.gov/bronx-health-care/

**Comment by mpelzsherman** [comment]
Archived detail page: https://prod.cms.va.gov/bronx-health-care/research

... does not appear on https://www.va.gov/bronx-health-care/

**Comment by mpelzsherman** [comment]
Archived news release: https://prod.cms.va.gov/central-arkansas-health-care/news-releases/virtual-town-hall-discusses-vaccine-hesitancy-for-bipoc-veterans

... does not appear on https://www.va.gov/central-arkansas-health-care/news-releases/

**Comment by mpelzsherman** [comment]
Draft news release https://prod.cms.va.gov/wilmington-health-care/news-releases/wilmington-vamc-2019-annual-report
... does not appear on https://www.va.gov/wilmington-health-care/news-releases/

**Comment by mpelzsherman** [comment]
Archived story: https://prod.cms.va.gov/wilmington-health-care/stories/veteran-presents-flags-to-va-health-care-workers-0

... does not appear on https://www.va.gov/wilmington-health-care/stories

**Comment by mpelzsherman** [comment]
Draft story: https://prod.cms.va.gov/eastern-colorado-health-care/stories/home-based-care-expands-for-vulnerable-veterans-in-southern-colorado
... does not appear on https://www.va.gov/eastern-colorado-health-care/stories/

**Comment by mpelzsherman** [comment]
In review story: https://prod.cms.va.gov/pittsburgh-health-care/stories/vaphs-foreman-fights-covid-19-in-new-jersey-0

... does not appear on https://www.va.gov/pittsburgh-health-care/stories

**Comment by mpelzsherman** [comment]
I've completed the manual verificiation process. We should think about automating something like this.
