### ISSUE TITLE
Conduct interviews for foundational CLC knowledge 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24819]
## Issue Description
VA Community Living Centers are VA health facilities which are included as locations under the relevant VAMC. They don't fit the facility pattern established by the VAMC facility detail pages as they include minimal services, such as "extended care" (or none at all). The information that Veterans need for these types of facilities may be different than that which is expected for medical clinics. 

### Community Living Centers
Community Living Centers deliver nursing home level of care, skilled nursing and/or medical care. They can be a temporary or permanent home. They can also provide rehab care/services.  

There are 2 free-standing CLCs with dual state status at this time. However, they may be different in other systems and not easily recognizable as CLCs. 

Community Living Center example: [Miles City VA Community Living Center](https://www.va.gov/montana-health-care/locations/miles-city-va-community-living-center/)

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/115441894-a1833e80-a1ce-11eb-812f-0fe02cd7b8b3.png)

</details>

### Problem to be solved
Before we can reimagine detail pages or validate potential designs with Veterans, we need to better understand these facilities. 

### Questions
  - how is the facility best described?
  - is the facility free-standing?  
  - or services within other facilities on a floor or wing of existing facilities) 
  - what services are provided?
  - what is the referral process? do Veterans self-refer?
  - what information does a Veteran need for these types of facilities?
  - Who is the likely audience? Is it a Veteran, caregiver, or other advocates?
  - What info is meaningful for the "prepare for your visit" section? Is there specific eligibility criteria?

## Tasks
- [ ] Talk Stan/Lisa to identify other CLC models (existing within other facilities, for example)
- [ ] Identify the PAO/Point of contact for the locations
- [ ] Prepare basic conversation guide for conversations with SMEs
- [ ] Interview SME to gain foundational understanding about these facilities, including the intended audience for detail pages

## Acceptance Criteria
- [ ] Document information from SME conversations

**Comment by mmiddaugh** [comment]
Notes from Meeting with Lisa on 7/7 

Community Living Centers
- Extended care and rehabilitation is an official national health service (which is overlap with extended care facilities)
- Most CLCs are aligned with only one VAMC system but may appear listed only under the main facility although large systems may have more than one 
 - CLCs tend to be more standardized and usually considered a health service by the VAMC
 - some are on DoD campus
 - some are managed by 3rd party
 - Can be freestanding (on VAMC campus) but most often within floor/wing of another facility
