### ISSUE TITLE
[WCAG2.1]: Add the VA Mobile team's accessibility test plan to VSP documentation

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#24823]
## Issue Description
WCAG2.1 will require us to capture a new accessibility testing plan in GitHub documentation and as a TestRail guide for VFS teams.

## Tasks
- [x] Finish the VSP accessibility test plan
- [x] Add the test plan cases to TestRail accessibility sample test cases

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
