### ISSUE TITLE
[WCAG2.1]: Create reusable accessibility testing objects in TestRail

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#24825]
## Issue Description
VFS teams need examples, references, and re-usable objects within TestRail to facilitate the independent creation of robust accessibility test plans. As we are building out re-usable objects, keep in mind that we want to measure the impact of this work. So, let's create objects with names and project membership that is easily identifiable as accessibility focused.

As a bit of reference material, the VA Mobile team wrote an [awesome accessibility testing plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/Accessibility%20Test%20Plan.md) based on WCAG2.1. They have been using it as their baseline for building an accessible app. We would like to add it to VSP accessibility documentation.

## Tasks
- [x] Port the [in PR test plan](https://github.com/department-of-veterans-affairs/va.gov-team/pull/23086) to TestRail
- [x] Update test cases in [VSP Accessibility Template](https://dsvavsp.testrail.io/index.php?/projects/overview/13)
- [x] Review the TestRail updates with QA, A11y specialists
- [x] Create a test plan template for use in TestRail that can be used to verify a core page on the Platform
- [x] Create test case templates for use in TestRail that can serve as a re-usable example of a test case that verifies key elements of WCAG2.1 for a core page on the Platform
~~- [ ] Create shared step templates for use in TestRail that can be used to verify implementations of common components from the VADS are accessible~~
  ~~- [ ] For example: Use shared step objects in TestRail to create a 'formula' for testing a11y of the Accordion component within a given product~~

## Acceptance Criteria
- [x] All template objects created for this effort map to a specific WCAG 2.1 requirement. It may be appropriate to use the previously compiled table of WCAG 2.1 requirements and how they apply to Platform.
- [x] All template objects are clearly named for the accessibility requirements and common element that they are verifying.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by JoeTice** [comment]
@noahgelman - please add comments and updates to this ticket and move it to the appropriate column in the workflow

**Comment by noahgelman** [comment]
Im meeting with Trevor today to go over it and will update the ticket
afterwards

**Comment by pjhill** [comment]
After going over what Noah has created, it seems like shared steps are not actually the preferred way of implementing these template materials. In order to enable easy understanding of the use of these template materials, it may be best to leave them as test cases which can be imported into a team's project in TestRail. We can use a custom field to tag these a11y template materials and track them as they are used across projects.

**Comment by pjhill** [comment]
@noahgelman These template materials look great! I noticed a few test cases appear to be in progress or empty. Namely,

1. https://dsvavsp.testrail.io/index.php?/cases/view/5164
2. https://dsvavsp.testrail.io/index.php?/cases/view/5165
3. https://dsvavsp.testrail.io/index.php?/cases/view/5171
4. https://dsvavsp.testrail.io/index.php?/cases/view/5172
5. https://dsvavsp.testrail.io/index.php?/cases/view/5173
