### ISSUE TITLE
Implement expandable alert for operating status on Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24824]
## Issue Description
The operating status expandable alert was implemented for Vet Center pages in #24151 but could also be used on Facility Locator pages. 

## Tasks
- [ ] Replace existing operating status display with the new [expandable alert design](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138511926?mode=cvhid) on Facility Locator detail pages 
- [ ] Use filter to make phone number actionable on the front end
- [ ] Add data layer
- [ ] Ensure the implementation is accessible 

Description/Screenshot of Interaction | Data Layer Specification | Dev Notes | 
| -- | -- | -- | 
Operating status |  `'event'': 'int-accordion-expand', //OR 'int-accordion-collapse'`<br>`'operating-status-heading: //dynamically populate according to the top level heading of the alert box'` 

## Acceptance Criteria
- [ ] Front end implementation is consistent with the design spec
- [ ] Operating status is displayed for the facility on the main page (assuming there is an operating status available in Drupal)
- [ ] Operating status is displayed for facilities displayed on the Locations page  (assuming there is an operating status available in Drupal)
- [ ] Veteran can view status details by expanding the alert  (assuming there is an operating status available in Drupal)
- [ ] Phone number is actionable on the front end
- [ ] Data layer is in place to track clicks to open/close the accordion 
- [ ] Click events on FL pages can be differentiated from events on Vet Center pages
- [ ] Alert is announced by screenreader 
- [ ] Veterans know they can expand the alert to see details about the operating status

**Comment by mmiddaugh** [comment]
This is being addressed in #35479

**Comment by mmiddaugh** [comment]
This was determined not to be needed or viable
