### ISSUE TITLE
Launch Typeahead 1.0:   Phased Roll

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24839]
## Description

As a product team we have decided to switch to a phased roll out to improve our ability to monitor the rate limits from search.gov.  As a result we will increase the availability as per our [release plan. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/typeahead/release%20plan.md)

## Tasks

- [x] On Monday, May 17, 2021 - Increase to 50%
- [x] On Tuesday, May 18, 2021 - Increase to 65%

## Definition of Done

- [x] 65% of VA.gov traffic has access to typeahead. Remainder of rollout will take place in Sprint 48 - #19638

**Comment by denisecoveyduc** [comment]
65% of all VA.gov users now have access to typeahead. #19368 will continue phased roll out.
