### ISSUE TITLE
[VAMC] Contact and determine true status and purpose of VA Manilla clinic and health services [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24838]
## Story
As a remote clinic that is located within a US embassy, a data mining of services and information is required, so VHA digital media can determine the best Veteran experience to provide health services in this location.

## Goal
_Provide best detail of information to VHA from site and POC so they can determine best course of action in creation of a facility page, or system

## TASKS
- [ ] Data mine legacy site for System and Health services and create health service playbook
- [ ] Contact PAO or other to confirm access, content, and status of facility providing services
- [ ] Report back to VHA with data so they can make determination of how best to categorize and build (e.g. facility under Pacific Islands, or Stand alone System)

## Acceptance Criteria
- [ ] Playbook information is Gathered and can be used to import into System and facility health services.
- [ ] Contact information is obtained for validation and ownership
- [ ] Data provided to VHA to make best determination.

**Comment by SgardnerPMP** [comment]
Pushed to Sprint 49 due to scheduling with Manilla and VISN-21.  Working to get all parties in one meeting.  Dependency on VISN-21 leadership to get schedule.
