### ISSUE TITLE
Update pg_stat_statements documentation

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#24842]
## Issue Description
pg_stat_statements used from within PgHero (for the PgHero jobs) in the test suite fails for the native flow if developers don't have the correct postgres config. Developers that are running the native flow for vets-api will run into the issue `PgHero::NotEnabled: Query stats not enabled` and will have to enable some [postgres config settings](https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md#installation). It's confirmed that pg_stat_statements are enabled in all of our envs ([dev](https://github.com/department-of-veterans-affairs/devops/blob/badb0d95782c9ae91084247995287f478f08c2df/terraform/environments/dsva-vagov-dev/main.tf), [staging](https://github.com/department-of-veterans-affairs/devops/blob/badb0d95782c9ae91084247995287f478f08c2df/terraform/environments/dsva-vagov-staging/main.tf) [prod](https://github.com/department-of-veterans-affairs/devops/blob/4e0904f8fd98a8cd5a3e4fcf7c10046cfb473d46/terraform/environments/dsva-vagov-prod/main.tf)) via terraform, so unless needing to specifically work with pg_stat_statements, it doesn't need to be enabled.

---
## Tasks
- [ ] stub test for PgHero that uses pg_stat_statements
- [ ] update docs

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
