### ISSUE TITLE
Chapter 31 - Manage wizard refresh when user abandons vs logs in

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#24847]
## Description 
Spun out of #24196, this ticket looks more closely at handling wizard render state when an unauthenticated user abandons the chapter 31 form from the introduction page. The issue is complex because differentiating between true abandonment (leaving the introduction page) and login redirect is challenging: they both constitute a browser window refresh. Currently, wizard completion is handled using a flag in session storage. This presents an issue in that until session is ended, the chapter 31 wizard will remain hidden. 

## Considerations
- URL has a `postLogin` query param after a user logs in. Could potentially use that.
- Could potentially use the `beforeunload` event listener to clear wizard flag on nav away

## tasks
- [ ] When an unauthenticated user leaves the intro page the chp31 wizard session flag should be removed
- [ ] When an unauthenticated user leaves the intro page **to log in** and returns to the intro page, they should not see the wizard again.

## Acceptance Criteria
- [ ] Above tasks are met and a PR has been submitted

**Comment by micahchiang** [comment]
Moving this to the icebox for now, as platform needs to regroup and discuss a way forward in general for handling wizard completion. [More here](https://dsva.slack.com/archives/C8E985R32/p1621527833014000?thread_ts=1620076670.078200&cid=C8E985R32)

**Comment by jason-gcio** [comment]
@brianalloyd - quick question for you....do you know who manages wizard type things, over all?

**Comment by steele-lm** [comment]
Wizard will be depreciated. Closing this ticket.
