### ISSUE TITLE
Update content on connected apps FAQs article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24852]
## Issue Description
We currently have the wrong information on our [connected apps FAQs page](https://www.va.gov/resources/connected-apps-faqs/) for how long it takes new health records to appear. We need to change 3 days to 36 hours.

In the answer to the question "What should I do if my records in an app are wrong or out-of-date?" change the content to:

It can take up to 36 hours for new health records to appear.

## Tasks
- [x] Update text (Selina)
- [x] Review and publish (Randi)
- [x] Notify Lighthouse team change was made (Randi)

## Acceptance Criteria
- [x] Text on live site shows 36 hours

**Comment by lunascoop** [comment]
@RLHecht the single QA node has been updated and is ready for review.

- What should I do if my records in an app are wrong or out-of-date? http://preview-prod.vfs.va.gov/preview?nodeId=8426

**Comment by RLHecht** [comment]
Thanks, Selina. Reviewed and published. I also notified Sophia on the Lighthouse team.

**Comment by RLHecht** [comment]
change is live. closing ticket.
