### ISSUE TITLE
PTSD Mockups

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#24859]
## Issue Description
Mockups of pages that we propose removing from form 526

---
## Tasks
- [x] Create mockups of PTSD related pages that will be removed

## Acceptance Criteria
- [x] Completed mockups posted to GitHub
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
Closing complete
