### ISSUE TITLE
Make User.mpi Private

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#24862]
## Issue Description
Followup issue to [6835](https://github.com/department-of-veterans-affairs/vets-api/issues/6835), after removing all external calls of `User.mpi` the method should be made private.

---
## Tasks
- [ ] User model's `mpi` method is made private
- [ ] All affected tests are updated

## Acceptance Criteria
- [ ] The `mpi` method will be unavailable outside of the User class
