### ISSUE TITLE
Jenkins Master Deployment - 5/18 PM 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#24887]
## Description
Re-deploy of Jenkins master after business hours on Tuesday, May 18, 2021. 

## Background/context/resources
[Slack conversation](https://dsva.slack.com/archives/CTYQL39FE/p1621354248031300) in #vsp-operations-internal 
Necessary to get [THIS PR](https://github.com/department-of-veterans-affairs/devops/pull/9177/files) live

## Technical notes
[Jenkins re-deployment workflow documentation 
](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Jenkins%20deployment%20workflow.md)
---
## Tasks
- [ ] Communicate in #vfs-platform-support before the re-deployment
- [ ] re-deploy jenkins according to instructions
- [ ] test to ensure that the system is back up and that plugins, jobs, etc are working 
- [ ] Communicate in #vfs-platform-support once re-deployment is complete 

## Definition of Done
- [ ] Jenkins will be re-deployed and the commits from devops PR 9177 will be live

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@omgitsbillryan - please share the updated steps to re-deploying Jenkins in this ticket if you can, please sir. 

@tskinn - tagging you for awareness and possibly helping our Sri if any issues arise
