### ISSUE TITLE
[EPIC] ORDMI Online Harassment Reporting Page & Tool MVP

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#24883]
## Product Outline
Here is the initial [Product Outline.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/read-me.md)

## High Level User Story/ies
As a Veteran or VA employee, I need a way to report an incident of workplace harassment or assault which takes place at a VA facility so I can be assured that there is investigation and remediation.

## Hypothesis or Bet
**If** we make an online reporting tool (e.g. Webform) that is available on the VA.gov Website **then** we will deliver on the need -- and the legislative mandate (Title 5, Section 5303 which requires the VA Secretary to create a comprehensive policy to end harassment and sexual assault, including gender-based harassment, at all VA facilities) -- to investigate and intervene with effective action when allegations are substantiated. 

## OKR

- **Objective (DRAFT/WIP):** 
Become a primary means of incident reporting, improving speed to outcome.
- **Key results :**
   - <>% in number of reported incidents year over year
   - <>% of all submissions are accepted (information provided is actionable)
   - <>% of all submissions are resolved 

## What is scope for MVP

The Public Websites team will work in partnership with two Presidential Innovation Fellows detailed at the Office of Resolution Management, Diversity and Inclusion to deliver the following, optimally by September of 2021:

**Research/Testing:**
- Do upfront landscape research to determine best practices approaches for placement and positioning (e.g. site linking, labeling) of the landing page and online reporting tool. (Note: ORDMI/PIVs will augment this with their own research/analysis/expertise.)
- Conduct Veteran and VA employee user research to inform the (a) site linking strategy, (b) information landing page content/design and (c) the Web form.

**Engineering:**
- A FE engineer to collaborate on the front-end build of the information landing page and the Web form on the VA platform (using VA Design System).

**Design:** 
- A UX designer to possibly create clickable prototypes (the site link(s), the landing page, the Webform) for user testing
- A UX designer to ensure the design of the product deliverables are in keeping with VA.gov's well-established design principles and design system/storybook.

**Content**
- Support to identify and create the content needed for the Landing Page
- Support to ensure the Form instructions adheres to VA.gov's  content and plain language guidelines.

**IA**
- Recommendations/guidance for VA.gov site linking, URLs and SEO optimization

**Product**
- Bridge and drive technical and agile project collaboration between the two teams 
- Guide collaboration cycle process

## Definition of done

- [ ] MVP of Landing page shipped
- [ ] MVP of Web form shipped, with integration to reporting/processing/handling touch-points
- [ ] VA.gov site links established

### What must be true in order for you to consider this epic complete? 

MVP of the product experience as defined is delivered to the satisfaction of users and VA business stakeholders.

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by johnhashva** [comment]
6/27 Update: Adding here the initiative kick-off questionnaire from VA.gov team provided to the ORDMI-PIF leads.
[VA.gov Digital Experience-ORDMI Initiative.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6721559/VA.gov.Digital.Experience-ORDMI.Initiative.docx)

**Comment by FranECross** [comment]
All tickets are closed on this old epic; closing.
