### ISSUE TITLE
Staging Review [Virtual Agent - Chatbot]

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-team#24884]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to VSP feedback tickets.
- [x] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/virtual-agent/product/product_outline.md)

- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository. 

  https://staging.va.gov/virtual-agent/ is the current version of the Virtual Agent.

-  Staging test-user information (if applicable): 
  
   N/A

-  Link to content brief (if applicable): 
 
   https://docs.google.com/spreadsheets/d/1J6hsR4m4XS6R-yxp1pmXUoVSv9F8qKX9vZn3xLda508/edit#gid=664478734 
   *** Note: Content changes frequently, but this is a helpful reference.

-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link) 

   https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/virtual-agent 
   The content source of truth will live within a number of parts of Microsoft infrastructure (PVA and QnA maker) but Github will have the majority of content for QnA. Please reach out to the team if you have issues navigating the content.

- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)

   The team is doing a controlled study with Perigean for our Virtual Agent POV starting at the beginning of June. We have been working with Lauren Alexanderson and Kevin Hoffman to sort out the specifics. For the next few weeks prior to the study, we are continuing to solidify content in the virtual agent (bot) around claims, addressing any remaining tech tasks and bugs and incorporating VSP feedback.

- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_

   N/A - no plan required as per VSP collaboration cycle meeting on April 14th

- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_

   N/A

- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

   https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/169

- List of known issues (with links to tickets when applicable)

   None.

## Meeting attendees from requesting team
- Product Manager (required): Ian Santarinala 
- OCTO-DE Product lead (recommended): Luciana Morais
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Anita DeWitt, Jacob Gacek, Katie Ho, Rachel Murray, Shefali Nayak, Paul Phillips, Shane Straussberg 
- Content, IA, accessibility, and QA specialists (if applicable): Shane Strassberg 

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **date/time**

Monday, May 24, 3:30pm – 4:00pm
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hi @ianpsant - Staging Review has been scheduled for Monday 5/24 at 3:30pm ET

**Comment by mnorthuis** [comment]
@ianpsant @murrayra   At midpoint this chatbot lived on the Contact Us page, not at its own URL, so an IA request was not required.  Is the plan now to go to production with its own URL?  If so, this may need an IA request and a discussion to understand the approach. so the URL and placement of this page in the va.gov IA can be vetted properly.

**Comment by peggygannon** [comment]
@ianpsant @murrayra Hello, I don't see any content artifact uploaded for the chatbot introduction/landing page. 

Has your team worked with the sitewide content team on this page?

**Comment by pjhill** [comment]
Hey @ianpsant, are there any QA artifacts available for review? We understand that you might not be using the tooling or processes prescribed / provided by the Platform, but do you have other QA artifacts such as a test plan, test cases, test results, automated test results, or load testing results that we might have a look at?

**Comment by allison0034** [comment]
No design feedback. : )

**Comment by murrayra** [comment]
@peggygannon  Yes we worked with the sitewide content team and also got feedback and approval from Dr. Foreman about the crisis content and the security team on the description of how data is used.

**Comment by ianpsant** [comment]
The study has gone live today, Tuesday June 1st, with selected study participants accessing the staging environment with the requested /virtual-agent-study URL.

**Comment by katieho-va** [comment]
We are working with Trevor to submit accessibility tickets with Microsoft, but other than that, we have completed the other Staging Review feedback or added cards to our backlog to address post-study. @shiragoodman can you update the tracker? I think this ticket is good to close from our end once you confirm

**Comment by shiragoodman** [comment]
@katieho-va. Tracker is up to date. You are good to close whenever. Katie, would you mind sharing the link the the Privacy and Security review ticket you created? I will add that to the tracker.

**Comment by katieho-va** [comment]
@shiragoodman Maybe you mean one of these? 

1. [Privacy/Security Readiness Review Ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/258)
2. [Privacy/Security Feedback](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/261)
3. [Team Orchid API toggle](https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/172) as a result of the feedback above

**Comment by shiragoodman** [comment]
thanks @katieho-va ! It's the first one that I was looking for.
