### ISSUE TITLE
Research Solution and Ideation Reviews 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#24898]
## Description 
Creating a generic ticket for addressing the solution/ideation meeting and review process post VA.gov wayfinding research project.  We can fill in the tasks below once we've identified which areas we'll explore and schedule ideation sessions for in support. 

## Tasks
- [x] Research read outs (June 7th, 8th) 
- [x] Recommendations discussions with applicable teams / Product team
- [x] Ideation with Public Websites team and other Unauth Teams. (opportunity mapping)
- [ ] Delete recordings after done looking up navigation/search path details

**Comment by cindymerrill** [comment]
Scheduled meetings with Search, Decision Tools teams for next week (6/8). Planning to meet with Public Websites tomorrow (Friday 6/4).

**Comment by cindymerrill** [comment]
Had recommendations discussion with Public Websites team today.

**Comment by cindymerrill** [comment]
Had recommendation discussions with Decision Tools, and with Search and Discovery today. Also presented research readout to OCTO DE, so now ready to share my preliminary recommendations with them; @johnhashva will schedule the meeting with Ryan and Meg.

**Comment by cindymerrill** [comment]
Had recommendation meeting with OCTO-DE Sitewide Crew today, which went well and might result in more research collaboration going forward. 

Today I pinged Matt Self and Sabrina Mohamed again because they're the last team I plan to share recommendations with, and I didn't hear anything back when I reached out last Friday (June 11).

**Comment by cindymerrill** [comment]
Scheduled meeting for later this week with Matt and Sabrina to share my research findings and recommendations re Benefits and Memorials.

**Comment by cindymerrill** [comment]
Talked with Matt and Sabrina about my research findings and recommendations re Benefits and Memorials, so now done delivering all of my recommendations to teams.

**Comment by cindymerrill** [comment]
I will wait 30 days to delete research recordings to see if I need to look anything else up from the videos.

**Comment by brianalloyd** [comment]
Thanks @cindymerrill going to close out this ticket in support.
