### ISSUE TITLE
Remove Stop Words 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24892]
## Description

Remove 'stop words' (Example: remove sentence structure words that reduce result quality ('to', 'get') searching for “how to get prescription” doesn’t produce the results we want however searching for “prescription” will produce best bet)
[Elastic search + stop words](https://qbox.io/blog/how-to-use-elasticsearch-remove-stopwords-from-query/)

## Tasks
- [x] Send list (#24994) of stop words to search.gov 
- [ ] Validate they have been filtered out as intended

## Definition of Done
- [ ] Stop words have been removed from query on production

**Comment by denisecoveyduc** [comment]
June 4- List sent to search.gov to filter out stop words

- We believe Elasticsearch is by default already filtering out: **a, an, and, are, as, at, be, but, by, for, if, in, into, is, it, no, not, of, on, or, such, that, the, their, then, there, these, they, this, to, was, will, with**

- In addition to the Elasticsearch's default stopwords, we would like to also add: **about, am, any, become, became, can, could, did, do, does, doing, get, getting, had, has, have, how, how's, I, I'm, it's, its, just, my, myself, so, than, that's, them, too, we, who, what, what's, when, where, which, who, who's, whose, why, would, yet, you**

**Comment by denisecoveyduc** [comment]
Dawn from Search.gov was out of the office until June 14th and we have a meeting with them on June 17th. Will determine if these stop words can be filtered out to aid in result relevance.

**Comment by denisecoveyduc** [comment]
We met with Search.gov on June 17th at which time Dawn and Amani stated that they would like to validate that the removal of the stop words  we presented would not cause any disruption to service of other users as this would be a global change for all of their clients. They will keep us informed if these stop words are able to be removed or not. The decision and remaining work items are for the Search.gov team.
