### ISSUE TITLE
MVP high level VSP Now/Next/Future roadmap + OKRs

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#249]
# User Story
As the VSP team I need to set an intentional, outcomes-driven path forward for VSP so that all teams that make up the VSP program can align their work to these goals and progress autonomously.

# Goal
Have a roadmap built using OKRs that we can check in on quarterly, and that teams can use to create their own roadmaps and sprint plans.

# AC
- [x] OKRs exist, and are used as the base of the roadmap
- [x] Roadmap exists
- [x] Initial feedback from DSVA
- [x] Test extension for one VSP sprint team's roadmap
- [x] Built using tools that facilitate easy updates

**Comment by rroueche** [comment]
Done in google slides so we can easily update when needed: https://docs.google.com/presentation/d/1zqnCLdX6K1PgHdFjGiaiU6fesOj26eNFAWUKltB9kz4/edit#slide=id.g5bcedc037d_2_111

Once KRs are agreed upon, and Next/Future themese are agreed upon, and roadmaps are added in for each team, we'll also store a copy in GH for public reference.
