### ISSUE TITLE
[VAMC] Resolve Tech-Debt of the COVID-19 vaccine detail pages for Systems listed and update SHS link [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24916]
## STORY
As a Veteran I need to know the latest information and guidance regarding COVID-19 vaccines, so I will know how, when, and where to schedule and get my COVID-19 vaccine.

## GOAL
Provide a Nationalized/local detail page for all sites.

## TASK
1) Determine which Source of Truth to utilize for Cloning the COVID-19 detail page
2) Clone COVID-19 to system missing the detail page, update page to reflect new System governance.  (on Edit screen document URL Node/#### to make line 3 task easier)
3) Go to COVID-19 VAMC System Health Service and update update link (Use node/### from Line two, or look up using COVID-19 vaccine) to point to new COVID-19 vaccine detail page.  

**Complete for the following VISNs and Systems:
_
_
**VISN-8**
- [x] VA Bay Pines health care
- [x] VA Caribbean health care
- [x] VA Miami health care
- [x] VA North Florida/South Georgia health care
- [x] VA Orlando health care
- [x] VA Tampa health care
- [x] VA West Palm Beach health care

**VISN-7**
- [x] VA Atlanta health care
- [x] VA Augusta health care
- [x] VA Birmingham health care
- [x] VA Central Alabama health care
- [x] VA Charleston health care
- [x] VA Columbia South Carolina health care
- [x] VA Dublin health care
- [x] VA Tuscaloosa health care
_

## ACCEPTANCE CRITERIA
* All listed systems have an updated COVID-19 detail page and align this with the System.
* Link in COVID-19 System health service links to new COVID-19 vaccines page locally.

**Comment by bcastoe** [comment]
#24916 Resolve Tech-Debt of the COVID-19 vaccine detail pages for Systems listed and update SHS link [VAMC] - Completed and moved to Validate
