### ISSUE TITLE
[VAMC] Resolve Tech-Debt of the COVID-19 vaccine detail pages for Systems listed and update SHS link [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24915]
## STORY
As a Veteran I need to know the latest information and guidance regarding COVID-19 vaccines, so I will know how, when, and where to schedule and get my COVID-19 vaccine.

## GOAL
Provide a Nationalized/local detail page for all sites.

## TASK
1) Determine which Source of Truth to utilize for Cloning the COVID-19 detail page
2) Clone COVID-19 to system missing the detail page, update page to reflect new System governance.  (on Edit screen document URL Node/#### to make line 3 task easier)
3) Go to COVID-19 VAMC System Health Service and update update link (Use node/### from Line two, or look up using COVID-19 vaccine) to point to new COVID-19 vaccine detail page.  

**Complete for the following VISNs and Systems:
_
**VISN-6**
- [ ] VA Asheville health care
- [ ] VA Durham health care
- [ ] VA Fayetteville Coastal health care
- [ ] VA Hampton health care
- [ ] VA Richmond health care
- [ ] VA Salem health care
- [ ] VA Salisbury health care
_
**VISN-7**
- [ ] VA Atlanta health care
- [ ] VA Augusta health care
- [ ] VA Birmingham health care
- [ ] VA Central Alabama health care
- [ ] VA Charleston health care
- [ ] VA Columbia South Carolina health care
- [ ] VA Dublin health care
- [ ] VA Tuscaloosa health care
_
**VISN-8**
- [ ] VA Bay Pines health care
- [ ] VA Caribbean health care
- [ ] VA Miami health care
- [ ] VA North Florida/South Georgia health care
- [ ] VA Orlando health care
- [ ] VA Tampa health care
- [ ] VA West Palm Beach health care
_
**VISN-16**
- [ ] VA Alexandria health care
- [ ] VA Central Arkansas health care
- [ ] VA Fayetteville Arkansas health care
- [ ] VA Gulf Coast health care
- [ ] VA Houston health care
- [ ] VA Jackson health care
- [ ] VA Shreveport health care
- [ ] VA Southeast Louisiana health care

## ACCEPTANCE CRITERIA
* All listed systems have an updated COVID-19 detail page and align this with the System.
* Link in COVID-19 System health service links to new COVID-19 vaccines page locally.
