### ISSUE TITLE
Replace link on survivors and dependents benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24924]
## Issue Description
Stakeholder Charlotte Kemper let us know that a link we have on our [VA education benefits for survivors and dependents page](https://www.va.gov/education/survivor-dependent-benefits/) to apply for Chapter 35 is pointing to the wrong page. 

Under the H2 How do I get these benefits? the link **Apply for VA education benefits (Chapter 35 benefits)** should go to this page: https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/ Currently it is pointing to the How to apply for the GI Bill page and causing confusion with users who are applying for the wrong benefit.

## Tasks
- [ ] Change link on page (Selina)
- [ ] Review and publish (Randi)
- [ ] Notify stakeholders of change (Randi)

## Acceptance Criteria
- [ ] Link on live page points to Chapter 35 apply page

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

- VA education benefits for survivors and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=984

**Comment by RLHecht** [comment]
Thanks! Published and notified the stakeholder of the change.
