### ISSUE TITLE
[EPIC] Discharge Upgrade Wizard - Change PDF link for Air Force respondents

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24925]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As an Air Force veteran, I need access to the eApplication that has replaced DD149 so I can have the option of submitting my discharge upgrade information online.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect Air Force veterans currently directed to complete form 149 to have the option to fill out the information via the e-application link

## OKR
Allows Veterans to more quickly access their benefits

### What must be true in order for you to consider this epic complete? 
- [x] Determination of whether PDF link will still be provided
- [x] Content for updated page
- [x] Design for updated page
- [x] Design intent review
- [x] Code solution
- [x] Internal testing (QA, a11y)
- [x] Peer review
- [ ] Internal review
- [ ] Staging review
- [ ] Deploy to Production

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
