### ISSUE TITLE
[EPIC] Discharge Upgrade Wizard - DD149 PDF link change for Air Force respondents

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24926]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a _____, I need _____ so I can _____.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
- [ ] Determine if PDF link will still be provided
-[ ] Discovery to determine level of effort, how to separate Air Force-specific page from others
-[ ] Content to reflect change
- [ ] Design for updated page
- [ ] Design intent review
- [ ] Write code
- [ ] Internal QA and Accessibility testing
- [ ] Peer Review
- [ ] Internal Testing
- [ ] Staging Review
- [ ] Deploy to Production

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by MarciMcGuireGCIO** [comment]
Duplicate created in error
