### ISSUE TITLE
[MCP] Finalize low fidelity prototype(s) for testing

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#24934]
## Issue Description
After design intent and our upcoming meeting with IA to discuss strategy and IA direction, we will need to create low fidelity testing materials for usability.

---
## Tasks
- [x] Have meeting with Mikki / Meg / Ryan
- [x] Create wireframes for testing

## Acceptance Criteria
- [x] Wireframes created and made available in GH

**Comment by rileyorr** [comment]
[Uploaded the prototypes to UXPin](https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages/139236640/simulate/sitemap?mode=i)

I still need to add the interactions and make some adjustments prior to demo on Tuesday. I'll also add another scenario in the wizard flow.

**Comment by rileyorr** [comment]
Keeping this ticket open because we're going to add interactive states to the wizard prior to the study kicking off

**Comment by rebeccawalsh** [comment]
Wizard functionality and other links have been added to the prototype.
