### ISSUE TITLE
Need additional bulk redirects of legacy forms tool

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#24949]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_ As a user, when I look for "va forms" in organic search, I want to get one authoritative source from the VA. Today, I see 2 different VA forms tools from the VA -- one for the modernized forms tool https://www.va.gov/find-forms/ , and another one for a legacy forms tool https://www.va.gov/%5Cvaforms/search_action.asp?FormNo=28-1900&tkey=&Action=Search . 

**Note:** Per [this closed ticket, we bulk redirected](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5549) the legacy forms tool pages (that fell outside of the 1-to-1 high value redrects). But it appears there are several legacy form /sub-paths that we missed bulk redirecting, like the above. 

(Source spreadsheet here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/form-detail-landing-pages/redirects/form-detail-landing-pages-cutoff-for-redirects-092820.xlsx)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_  Investigate what legacy form page URL paths did not get bulk redirected; and work with @mnorthuis in Platform and @brianalloyd in PW to implement additional bulk redirects of legacy form tool pages. 
- [ ] Redirect `va.gov/%5Cvaforms... `URL paths, and any other additional legacy URL paths that we missed, per investigation. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

 ---

### Screenshot - anonymized search result:
![image](https://user-images.githubusercontent.com/43381063/118848079-6abb4980-b89c-11eb-86a2-8b8f09592e10.png)

**Comment by jenniferlee-dsva** [comment]
Note - It creates duplicative shadow form URLs. Example:

**form va 0896a**
https://www.va.gov/%5Cvaforms/va/pdf/VA0896a.pdf
vs.
https://www.va.gov/vaforms/va/pdf/VA0896a.pdf

**form 10-10ez**
https://www.va.gov/%5Cvaforms/medical/pdf/10-10EZ-fillable.pdf
vs.
https://www.va.gov/vaforms/medical/pdf/10-10EZ-fillable.pdf

Etc.

**Comment by MarciMcGuireGCIO** [comment]
@jenniferlee-dsva some unplanned time-sensitive updates for Discharge Upgrade Wizard came up last week, so I personally have not had an opportunity to dive into this yet.

**Comment by MarciMcGuireGCIO** [comment]
Note - pagination on this page redirects to modernized tool.  To see each page, use these links:

https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=2&orderby=number
https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=3&orderby=number
https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=4&orderby=number
https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=5&orderby=number
https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=6&orderby=number
https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=7&orderby=number
https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=9&orderby=number
https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=10&orderby=number

**Comment by jenniferlee-dsva** [comment]
@MarciMcGuireGCIO - I suspect those paginated pages are still using `/vaforms` path, which are captured by our MVP launch redirects. That's all I can think of.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva is correct, if you hover over the pagination links and look at the status bar at the bottom of your browser, you'll see that it is going to the original /vaforms URL, which is is then grabbed by our redirect.   So the change was made at the page level, and the backslash "\" was inserted, which is then encoded to "%5c" by the browser - either way, our redirect isn't picking up that variation of the URL.

**Comment by jenniferlee-dsva** [comment]
Thx @mnorthuis for the added info. 

@johnhashva @MarciMcGuireGCIO - let us know what you learn after your reach out to Kevin regarding the weird URL. If it was unintentional and was meant to be archived via moving it, he should be able to work with web ops or with TeamSite people to fix it. 

If you don't get a response, let me know. I may be able to reach out to the web governance group to help. I guess either way, we probably need redirects.

**Comment by johnhashva** [comment]
Got it @jenniferlee-dsva -- tackling this here in our next Sprint -- and I'll start by reaching out to Kevin.

**Comment by zacharymorel** [comment]
Self note, if we need to match the specific URL of https://www.va.gov/%5Cvaforms/ , the following _should be_ sufficient
`^/\\vaforms/`.

I checked the va.gov/sitemap and I did not find any URLS using /vaforms/.
Anything for your digging @MarciMcGuireGCIO ?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel thank you for taking a look!  John is going to contact Kevin to find out if there's anything on their end that inadvertendly caused the `/`  /  `%5C` to appear in the URL, and then we'll look at doing a wildcard redirect.  

Do you happen to have any means to search the codebase (something like Fisheye) to determine if there are any other URLs that might contain that string?

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO 
I just checked, there's nothing on the site map nor within the repos that build va.gov.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel, @mnorthuis @kelsonic cc @johnhashva --- Hmmm.  all the VA PDF form links have `/vaforms/` in their URLs.   Example: 

- `https://www.va.gov/vaforms/medical/pdf/10-10EZ-fillable.pdf`

If the wildcard redirect specifies that it has to have the `\` (aka `%5C`) in the URL then theoretically it shouldn't affect the **correct** PDF links, should it?

**Comment by zacharymorel** [comment]
Nice catch @MarciMcGuireGCIO , I believe we need to narrow the redirect to `^\/\\vaforms\/`. Then we won't have any issues with the existing PDF links.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel.  Are you sure we don't need to use  `(ノಠ益ಠ)ノ彡┻━┻^\/\\vaforms\/ ¯\_(ツ)_/¯`   🤣

**Comment by johnhashva** [comment]
If we end up implementing this wildcard -- we can do a limited test first, right?

**Comment by zacharymorel** [comment]
> Thanks, @zacharymorel. Are you sure we don't need to use `(ノಠ益ಠ)ノ彡┻━┻^\/\\vaforms\/ ¯\_(ツ)_/¯` 🤣

Haha table flip, right on point there.

**Comment by johnhashva** [comment]
6/7 Update: I sent an email to Kevin Reid recommending (once again) the retirement of the legacy Search VA Forms pages/tool -- with this issue as another example of the consequences of leaving the legacy tool in place.   If I don't hear back from Kevin by Wednesday 6/9, let's redirect va.gov/%5Cvaforms... URL paths, and any other additional legacy URL paths that we missed

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @johnhashva.  I'll mark it on my calendar.

**Comment by mnorthuis** [comment]
FYI, you may need to redirect both the encoded URL (va.gov/%5Cvaforms) and the unencoded URL (va.gov/\vaforms)...

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @mnorthuis!

**Comment by MarciMcGuireGCIO** [comment]
I just entered a redirect request for this with a change date of Jul 15 so that we can advise the stakeholders at our Jul 11 monthly meeting.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/26299

**Comment by MarciMcGuireGCIO** [comment]
Tracking this in #26299
