### ISSUE TITLE
Create functional prototype for View Dependents formlet

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#24955]
### Background
The remove dependents formlet on the View Dependents page need to be validated against usability concerns.

### Tasks
- [ ] Implement mid-point review feedback
- [ ] Implement form /review functionality
- [ ] Incorporate content/design guidance

### Acceptance Criteria
- [ ] Mockups have been converted to functional prototype
- [ ] Content edits included in prototype
- [ ] Design feedback reflected in screen layouts

**Comment by jason-gcio** [comment]
staging is pretty far along and this is not needed
