### ISSUE TITLE
Finalize COE Prototype for usability testing/content revisions

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#24953]
### Background
Semi-functional COE mockups need to be connected to support usability testing. Latest design and contetnt feedback/guidance should be incorporated.

### Tasks
- [ ] Finalize branching logic
- [x] Implement form /review functionality
- [x] Incorporate new intro content/design
- [x] Revise doc upload screen

### Acceptance Criteria
- [ ] Mockups have been converted to functional prototype
- [x] Content edits included in prototype
- [x] design revisions/guidance reflected in screen layouts

**Comment by sporeboy** [comment]
Working on rewrite/redesign of COE intro screen here (WIP): https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137576823

**Comment by sporeboy** [comment]
Content updated. First draft available for review: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137576823

**Comment by sporeboy** [comment]
Latest content revs in place ahead of midpoint review. Step-wise flow should work for review.

**Comment by sporeboy** [comment]
Mid-point review feedback implemented. Prototype functionality pending.

**Comment by sporeboy** [comment]
Added quick edits to confirmation page per Kelli.

**Comment by sporeboy** [comment]
Intro accordions fixed--will work together now.
