### ISSUE TITLE
Error Logging Improvements

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24968]
## Description
Currently when search fails, no complex logging is performed and a user only receives a "try again later" message. 
We would like to expand upon the current error logging to provide users (and developers) a more detailed explanation of what went wrong.

Establish improved error logging to provide detailed messages when a search fails. 

## Tasks

- [x] Establish Error logging for:
 -  no results returned / bad query
 -  search is down / can't be completed

- [x] Document available logs in [on-site-search/technical/error-logging](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/technical/error-logging.md)

## Definition of Done

- [X] Alert box message is shown when search can't be completed
- [X] No Results message is shown when a search returns empty results

**Comment by srsuddath** [comment]
This ticket is awaiting validation in staging review before it can be closed

**Comment by srsuddath** [comment]
feature is live on the review instance
