### ISSUE TITLE
[Discovery] - Auth Exp best practices research phase 1

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#24973]
**Background**
Through the course of working on the Auth Experience team, we’ve identified an opportunity to expand and track our knowledge on best practices in personalized and authenticated experiences. We frequently solicit screenshots and log into our own accounts to compare and see what’s out there, but typically don’t have time for formal documentation.

The goal of this activity is to answer specific research questions through a comparative analysis and create a knowledge base of best practices to share with the authenticated experience team.

**Plan**
We'll break this out over 3 sprints and work on as time allows. Project work takes priority over this.

**Tasks**

- [x] Create research plan
- [x] Share w/ team & incorporate additional questions
- [x] Begin comparative analysis

**Comment by andaleliz** [comment]
As it turns out, the VAOS research sessions won't start until next week, so I have some time to work on this. @tressaellen and I have put together our research questions and captured them in [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/auth-exp-comparative-analysis-reseach-plan.md).

Team (@Samara-Strauss, @ajakabcin, @erikphansen and @lihanli), can you please take a look before EOD Friday, and let me know if you have any research questions to add to this list? Our intention is that the findings will be a team resource so I'd love to include feedback from everyone.

Project work takes priority over this - I'll keep an eye on the timeline section of this doc and tweak as needed.

**Comment by andaleliz** [comment]
No comments from team; tasks in description have been completed.
