### ISSUE TITLE
[Design] My VA: Explore designs/sketches for how we can elevate action items

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24970]
## Background
As part of long-term research and continued improvements to My VA post-launch we need to do some discovery/research prep around how to better elevate action items in the dashboard and create sketches for that work.

## Tasks
- [x] Map out what action items might need to be included
- [x] Begin sketches/exploration of how we can elevate action items
- [x] Review concepts with Samara and AJ

**Comment by tressaellen** [comment]
@Samara-Strauss (cc/ @ajakabcin ) Here is the [spreadsheet outlining potential action items for My VA](https://docs.google.com/spreadsheets/d/1sEkNQvcPNhQ9R-CC-SRdrQiF4DNeix6HDC-WvWRWByo/edit#gid=724842135), as well as what will be included in MVP (depending on timing and other teams). It's a google spreadsheet, which I know is sometimes an issue, so let me know if you can't see it and I can export it to something else.

I'll be posting some rough sketches/ideas by EOD tomorrow - but I just wanted to get your thoughts on if I'm missing any action items that we should include.

**Comment by Samara-Strauss** [comment]
@tressaellen I can't view the spreadsheet because I don't have access. Can you please give access to samara.strauss@va.gov?

**Comment by tressaellen** [comment]
Just shared!

**Comment by Samara-Strauss** [comment]
I think this initial list looks great. We aren't as concerned right *now* with exact notifications that would be included in the MVP, so we can make specific technical decisions later, but I'm glad you did this. It will come in handy when we start defining the MVP more fully. Plus, it might help you make some design decisions in this exploration phase, such as:

- If we elevate new messages in some way, what happens to "You have 2 new messages" that currently lives in the health care section?
- If we elevate appointment info — upcoming or canceled — in some way, how does that affect the appointment info that currently lives in the health care section?
- How would prompts to complete an application affect the design in the Apply for Benefits section?

Looking forward to seeing what you come up with! And sorry to miss most of the design iteration phase — please rely on the team, including Kevin, for feedback and insight if I'm not here when you get back.

**Comment by tressaellen** [comment]
Thank you for looking over this! 

> Plus, it might help you make some design decisions in this exploration phase...

Yes, exactly - I just don't want to get too far down the road and realize we didn't consider these things. 

> And sorry to miss most of the design iteration phase — please rely on the team, including Kevin, for feedback and insight if I'm not here when you get back.

I'm so sad you won't be around - you will definitely be missed. But also YAY, I'm so very excited for you!

**Comment by tressaellen** [comment]
Just for documentations sake.

I also asked other designers on VSA to drop in any potential action items they might be working on, so we can keep track of future work as well - that will be in [this spreadsheet.](https://docs.google.com/spreadsheets/d/1724fvSyOtkoSvCSFOYiWBWZbG8kM-w3yElorKGDS0FQ/edit#gid=871749236)

**Comment by tressaellen** [comment]
Hi @Samara-Strauss - apparently when I said EOD I mean **EOD**. :)

I've put together some rough wireframe-y ideas for action items in this [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1623308977321/dfc68dee89d6073c960339da9d9ebd977caebca1), this round was mostly exploring layout concepts and thinking through high-level UX flows. 

_*Note-these are wireframe-y on purpose, obviously the final product doesn't have to look anything like these._ 

Based on what we learned from the [comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/action-items-comparative%20analysis.md), I landed on 3 main concepts:

1. Action Items with a dedicated section within My VA
2. Action Items as a stand alone page, connected to My VA
3. Action Items in a dropdown

I had some additional questions as I worked through things, and those are at the top of the board. Feel free to add any thoughts/pros/cons/anything to the Mural board. And as always - we can frankenstein concepts as needed.

Since there's a high chance you'll be out by the time I get back (congrats!!), I wanted to outline what I'm thinking for a few of the next steps here. I know you already have this all planned out, I just want to make sure we're on the same page and I also think this will help me with ticket creation down the road. 

1. Get feedback on concepts- refine, refine, refine.
2. Reach out to accessibility early to help us understand what is possible accessibility-wise when it comes to action items/notifications.
3. Land on refined concepts to test with (When I say 'refined' I do not mean a finished design - I mean concepts somewhere between low-mid fidelity).
4. Do research on concepts to establish direction (I'm not sure what this looks like yet, I'll reach out to a few people to help with this)
5. Synthesize
6. Start work on high fidelity designs. 
7. Test again (if time permits)
8. Make updates, do QA/UAT/all pre-launch activities.
8. Launch! 

Anyway, thanks for all of your help, I can't wait to see where this goes, and I'll see you when you get back. :)

**Comment by Samara-Strauss** [comment]
Thank you so much for this! I've left a bunch of comments in the Mural board. I didn't enter my name, so I'm your resident visiting sea lion 😆 If I'm not here by the time you get back, don't feel that you have to explicitly answer the questions I left. Most of it is food for thought and things to consider as you start to refine the design more.

---

In terms of process, what we're doing right now is *just* a discovery phase, so this is actually how I see this phase of things going forward:

1. Get feedback on concepts- refine, refine, refine.
2. Reach out to accessibility early to help us understand what is possible accessibility-wise when it comes to action items/notifications.
3. Land on refined concepts to test with (When I say 'refined' I do not mean a finished design - I mean concepts somewhere between low-mid fidelity). 
  - **Addendum**: I think we should test with something that's a realistic fidelity. IMO, you probably don't need to go totally grayscale given that this is within the context of My VA, which is already designed. Without making the design pixel perfect and realizing work will be refined later, can you drop the alert interactions/flows into the existing My VA designs and use that for testing? This is ultimately up to you – I won't even be here when you do the testing! — but it's just a thought.
4. Do research on concepts to establish direction 
5. Synthesize and make recommendations on how to move forward

From here, you should work with Kevin and AJ to determine what an MVP might look like and when that might start given other work that's happening. From there, you can figure out what additional design work would look like. It might only be a couple sprints to refine designs and create frontend documentation, or maybe an additional sprint beyond that if you need to do more research. You'll need to make which alerts you're including, any interactions you have around alert indicators, or when something is consider read are fully defined. But at that point, it might be good to go to move on to frontend build and various parts of the VSP cycle.

So sorry to be missing the beginning phases of this — I'm really excited to see where this work goes and know it's absolutely essential to the auth experience. Really exciting to see it starting out so strong!

**Comment by tressaellen** [comment]
Refining and further feedback will happen in #24970
