### ISSUE TITLE
** SPRINT 48 PRIORITIES**

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24976]
<hr>

## :fire: Sprint 48 Priorities

- [ ] 1. ~~Find a VA Form Search tested & scheduled for Staging review & possibly go-live~~  **We are expanding the scope of work to include popularity, UI consistency changes and related to links **
- [x] 2. Discharge Upgrade Wizard content changes in preparation for 6/1 Content Landing Page launch **(go-live by Thu 5/27)**
- [ ] 3. Design for adding links to Related To forms on Form Detail pages
- [x] 4. Start Collab cycle for adding PDF download instructions - will have a research component.  Cindy is doing research for another project (ORDMI).  This may be next.
- [x] 5. Design for PDF message on Find a VA Form

**Note: Memorial Day is 5/31**

#### Zach

- [x] Discharge Upgrade Wizard - Upgrade Military Branch Addresses ~~and Add Army portal link~~ #25119
- [x] Discharge Upgrade Wizard - Fix the VA Form 10-5345 link #25124
- [x] Discharge Upgrade Wizard - Change the DD 149 PDF link in App #25121
- [ ] ~~Staging Review Decision Tools - Find a VA Form Search Term Transformation Iteration 2~~ #24436 (Cancelled; scope has changed. Will reschedule)
- [ ] [STRETCH] Find a VA Form: Implement new UI/UX Standards on Staging #22452

#### Cassandra
- [ ] Find a VA Form: Mock up adding links to Related Forms on Detail Pages #24889
- [x] Find a VA Form (and Discharge Upgrade Wizard): Design for adding download instructions for PDF links #24981

#### John
- [x] Find a VA Form: Internal testing - test search matching/ranking in Forms API on Staging #22866

#### Marci
- [x] Find a VA Form: Internal testing - test search matching/ranking in Forms API on Staging #22866
- [ ] Update screen shots on TestRail for Find a Form testing
- [x] Re-schedule staging review **[IN PROGESS] Staging Review Decision Tools - Find a VA Form Search Term Transformation Iteration 2 #24436**
- [x] Discharge Upgrade WIzard: Research into conditional content display #24999
- [ ] Map out decision tree for Discharge Upgrade Wizard - started Mural board: https://app.mural.co/t/vsa8243/m/vsa8243/1621532440874/8a3ee02c63bf5216b24fb01025e1e109b43d5407
- [ ] Determine target refinement rate for Find a VA Form
- [ ] Research delta in spellchecking methodologies used on different search tools

###  🗨️  Discussion Topics/Grooming 
- [ ] Topic
- [ ] Topic
- [ ] Topic

**Comment by MarciMcGuireGCIO** [comment]
**2021-05-21** 
- Testing Find a VA Form search on Staging.  Staging review has been rescheduled for Tue June 1 due to limited capacity for Staging reviews next week.
- Cassandra has done a mockup of a possible solution for the PDF, but there is a curveball with PDFs that are hosted outside VA.gov domain - can require right-click to download.
- Zach - reviewing the new Discharge Upgrade Wizard epic opened today, estimating the work.
- Zach will send me the two mailing addresses so I can ask Margarete to confirm which one(s) he needs to update.
- Marci met with Shira re: timeline vs. Collab Cycle.  Staging Review (walkthrough) scheduled for next Friday (VSP's first availability).  
- John should probably talk with Rachael Rouche to find out if this qualifies as an emergency and can bypass Collab Cycle for now, and qualify for off-schedule deploy on Friday.

**Comment by zacharymorel** [comment]
Should we change the priorities with the new stories that pertain to the Discharge Wizard upgrade.

**Comment by MarciMcGuireGCIO** [comment]
Yes. Thank you! I am eating lunch but I'll do that as soon as I finish.

**Comment by MarciMcGuireGCIO** [comment]
2021-05-24

- CLP content may be changed to point to the portals (question about about the ones not ready/throwing privacy error?)
- PDF link - Josh Kim suggested suggested a simple link
- Cassandra will mockup "Right click and save, then open in Adobe Acrobat Reader"
- John having a go/no go with Kayla as soon as we are comfortable we're ready to go

**Comment by MarciMcGuireGCIO** [comment]
2021-05-25

- Update wizard request for PDF link change to portal still stands.
- Find a VA Form PDF link - Cassandra posted the mockup on the ticket - ready for Marci to schedule a design intent review.

**Comment by zacharymorel** [comment]
Link for new discovery on XFA detection script.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25343

**Comment by MarciMcGuireGCIO** [comment]
2021-05-27
- Cassandra - took a look at the PDF download links.  
- The R&S article about PDFs can be tweaked to provide more info on downloading
- In the mockup, Cassandra put a help tip (Having trouble opening a PDF?)  Downside is the help link would appear under every single PDF.
- Cassandra also has done several mockups for next week's Design Intent, and will also discuss in her 1-1 with Cindy.
- John suggested we check out UK.gov, other similar entities to see if they have solved this issue.
- John's preference a little bit of instruction in context with the PDF download, and a link to more info.  
- Cindy also likes the idea of having some instructions next to the link,
- There are also two technical possibilities we could incorporate in conjunction- download attribute and a server-side http header option.
- There is a discovery issue for next sprint to do deeper dive into the download attribute and http header.
- Zach worked on XFA script today; pulled a report for the PDFs so we can see which have XFA (374 of 403)
- Discharge Upgrade Wizard
- There is currently a survey for [chatbot ideas](https://ows.io/qs/jija2sp6) - please take it if you have ideas!

**Comment by MarciMcGuireGCIO** [comment]
2021-05-28

- Zach reverse-engineered the PDF XFA script to see if there's anything else that can be extracted from the PDFs.
- John and Marci met to talk about Q3 & Q4
