### ISSUE TITLE
Authenticated Experience: Sprint 50 (6/16 - 6/29)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24978]
## Priorities

1. Conduct My VA UAT & address any issues
2. Address any issues for My VA to prepare for launch
3. Continue Notification Prefs build
3. Start Preferred Facilities build
4. General Profile work 
5. Accessibility audit issues as time permits

## My VA redesign
**PM**
_stretch goal_
- [ ] Hold launch go/no-go #26224

**Design**
- [x] Kick off recruiting for UAT #24062 _(from sprint 49)_
- [x] Run UAT sessions #24063
- [x] Attend launch go/no-go #26224
- [x] Explore designs/sketches for how we can elevate action items #24970 _(from sprint 49)_

**FE**
- [x] Configure feature flags in staging and prod for My VA UAT #25817 _(from sprint 49)_
- [x] Ensure we are sending appropriate events to the dataLayer for analytics tracking #25984
- [x] Kill "Find VA Benefits" feature on My VA 1.0 prior to My VA 2.0 launch #25149
- [x] Attend launch go/no-go #26224
- [x] Enhance My VA tracking to allow distinction between My VA 1.0 and My VA 2.0 #26649
- [x] UAT findings:
     - [x] 'View lab results' and 'View medical records' behave differently - one opens in another tab, another opens in the same tab #26528  
    

## Notification Preferences

**Design**
- [x] Conduct research/usability testing #25367  (_started in sprint 49_)
- [x] Usability testing/research synthesis #25932

**FE**
- [ ] Continue build:
    - [ ] Make CommunicationGroup model class #26193
    - [x] Make CommunicationChannel model class #26196
    - [ ] High-level tests for FE #24864 _(from sprint 49)_
    - [ ] Add named anchors to the Personal and Contact Info section #25769 

## Preferred medical facility

**Design**
- [ ] VAOS/profile facilities research synthesis #25510 _(from sprint 49)_
- [x] Update designs and FE documentation #25368 _(from sprint 49)_

**FE**
- [ ] Start build:
     - [ ] ~Redux actions and Reducers #26101~ 
     - [ ] ~React Design #26102~ 

**BE**
- [ ] ~Change preferred facilities api to create and destroy multiple facilities in one request #26270~

## Profile

**FE**
- [x] Correct "edit" buttons so they are styled as buttons #23660 
- [x] Align cancel button styling throughout profile so that all buttons look like buttons #23661
- [x] Implement updated design for when we don't have certain contact info for a user #23917
- [ ] 508-defect-1 ❗ Launchblocker [SCREEN READER, COGNITION] Unable to update address, phone number and email address. Silent error messages. #23252 _(from sprint 49)_

_If time permits:_
- [ ] Accessibility Audit tickets:
     - [ ] 508-defect-2 [HEADINGS, AXE-CORE]: Profile, heading levels should only increase by one #23756
     - [ ] 508-defect-2 [AXE-CORE]: Autocomplete attribute must be used correctly for home address/mailing address checkbox #23173

**Design**
- [ ] Improve UX for "remove" [contact information] button #23665
- [x] Create confirmation email for when contact information is updated on VA.gov #8383

## Backend work
- [ ] Backend work for setting up the contact info change email #25865 
- [x] Lihan assisting the identity team
