### ISSUE TITLE
Not all locations are included on the VAMC Locations page 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24987]
## Issue Description
The [locations page for Minneapolis health care](https://www.va.gov/minneapolis-health-care/locations/) does not include all of the facilities in the list, although they appear in the side nav.

 <details>
<summary> See screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/118895244-06f84700-b8c3-11eb-9855-503f8d9047de.png)

</details>

We think the page is impacted by an intentionally enforced page length limit on events and story listing pages. **Resolving this issue for the relocation page should not remove the truncation for other pages.** 

---
## Tasks
- [ ] Ensure that pages are not artificially truncated and that all relevant locations can be displayed

## Acceptance Criteria
- [ ] All expected locations are displayed on the Locations page
- [ ] The number of locations agrees left nav and locations listed on the page
- [ ] Event and story listing pages are not changed
