### ISSUE TITLE
Implement UI Consistency Elements on Global Search - Part 2

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24988]
## Description

Search UI Consistency elements have been defined as part of this joint effort - Detail in Epic #21055. These UI elements need to be updated on all global search pages to align with the design system addition. 

## Background/Context

[Desktop](https://vsateams.invisionapp.com/console/share/SD10IE31CENR)
[Mobile](https://vsateams.invisionapp.com/console/share/8Y10IE2JN2J4)
[Spreadsheet](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit?usp=sharing)

[Epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21055)

## Tasks

- [x] Finalize changes to address the following global design needs:

1. Link Header
2. Header Link a:visited
3. Header Link a:hover
4. Header Link a:focus & a:active
5. Search input, search button
6. Search input, search button a:hover
7. Search input, search button a:focus & a:active
8. Pagination
9. Page Header
10. Results Description – Style & truncation of the descriptions
11. URL
12. "Showing 1-10 results..."
13. Our top recommendations for you

 

## Definition of Done

- [x] This is a two part initiative, this (part 2) is the finalized development required for UI Consistency Elements.

**Comment by denisecoveyduc** [comment]
Hi @srsuddath I just met with John and we noticed that the gray box isn't even around the input field. I defer to @mgleo but wonder if adding another line of gray under the input field would be best. Here is a visual for reference.  
![image](https://user-images.githubusercontent.com/72393866/121918444-0907c700-cd04-11eb-9e1d-ded489b8510f.png)

**Comment by mgleo** [comment]
I wouldn't add another grey line, it is only missing some padding underneath the input field. I'll add more details soon.

**Comment by srsuddath** [comment]
I'll check it out. I distinctly remember that working haha

**Comment by srsuddath** [comment]
looks like its a padding issue, once megan has her list for me I'll make some edits

**Comment by mgleo** [comment]
@srsuddath 
- Breadcrumb: change from 'Home > Search Results for benefits' to 'Home > Search results'
- Update 'VA.gov search results' header to 40px
- Extend padding for grey background to 24px below input field. Link for reference: [multiples of 8 in the style guide](https://design.va.gov/design/spacing-units).
- Space between grey background and "Showing..." should be 40px
- Remove h5 from header links
- Grey background on hover should line up with text, it is currently extending the whole width
- Grey background on hover only showing for visited links on right nav
- Reduce margin between header link, URL, and description slightly (decrease by 4px above and under URL)
- Descriptions should be truncated to 186 characters(including spaces)

**Comment by johnhashva** [comment]
My only feedback:

- [ ] Maybe already covered, but the Bold treatment in the headline looks too heavy.  Is it supposed to be bold?
<img width="610" alt="Screen Shot 2021-06-15 at 11 10 15 AM" src="https://user-images.githubusercontent.com/63107147/122078178-649c8800-cdca-11eb-8d97-cfd49183db52.png">

**Comment by srsuddath** [comment]
According to the style guide it is supposed to be!

![Screen Shot 2021-06-15 at 11 23 26 AM](https://user-images.githubusercontent.com/47081947/122080267-2a33ea80-cdcc-11eb-83b5-32526c7cddbd.png)
![Screen Shot 2021-06-15 at 11 24 04 AM](https://user-images.githubusercontent.com/47081947/122080322-328c2580-cdcc-11eb-84d3-50f27410b89f.png)

**Comment by mgleo** [comment]
Yes, it is following the header link style from the [benefits pages](https://www.va.gov/disability/eligibility/) (scroll to the bottom, under Veteran Readiness and Employment (VR&E)). The addition of the underline was recommended by accessibility.

**Comment by srsuddath** [comment]
This ticket is awaiting validation in staging review before it can be closed

**Comment by srsuddath** [comment]
feature is live on the review instance and ready for staging review
