### ISSUE TITLE
Update disallow list on robots.txt file

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24985]
## Issue Description
Each time the VAMC team brings up a new System into Dual-State, a facilities engineer needs to add a disallow line (`Disallow: /(name)-health-care/`) under # existing disallow on va.gov to the robots.txt file  and push a PR to engineering to prevent crawlers from accessing the new site in dual state.

Platform needs a PR to add that one line to the robots.txt file found 

Per Steve Wirt, the disallow should go [here: src/site/assets/robots.txt:97]( https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/robots.txt#L97)
`Disallow: /performance-dashboard`
(In the useragent *  section which covers all bots other than usasearch and synapse)

A separate issue will be created for the addition of an allow statement when the VAMC team is ready to put up a banner from the legacy site. 

[Slack conversation here](https://dsva.slack.com/archives/CPQFCQKEH/p1610487930440000)

**Note: we previously updated the file for the entire roll-out but one additional line needs to be added due to a merger** 

---
## Tasks
- [x] add a disallow line (Disallow: /(name)-health-care/) under # existing disallow on va.gov to the robots.txt file for the following
      - Disallow: /eastern-kansas-health-care/

- [x] Remove the following from the file due to mergers
      - Disallow: /leavenworth-health-care
      - Disallow: /topeka-health-care

- [x] Post message in VSP when PR is ready

## Acceptance Criteria
- [x] Disallow line has been added
