### ISSUE TITLE
[VAMC] Resolve CMS Menu structural issues and missing menu items so CMS can run Scripting [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24991]
## Story
As a Veteran I need clear URL bread crumbs and paths to all pages, hidden and enabled, so I can save the location and return.

## GOAL
resolve all CMS reporting issues related to menus and menu structure so they can run script that will harden the menus and URLs using the menues

## Resources:
Contact Kevin Walsh
Utilize Reports for both
[Structured Node issue report](https://airtable.com/shrLvLedjy6aBnl3X)

## Tasks:
Utilizing reports from CMS, go to each Menu and:
- [x] Confirm menus are structured correctly 
- [x] Update any missing Pages that should be in menu

## Acceptance Criteria
- [x] All structural and missing menu items are clear from CMS airtable report.

**Comment by ltrombley** [comment]
Task #24991 - Resolve CMS Menu structural issues and missing menu items so CMS can run Scripting [BA] - is Complete and moved to Validate.
