### ISSUE TITLE
[EPIC] Spanish-Language content pages for Spanish VA forms

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25008]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a person who speaks Spanish, I need form detail pages written in my language so I can understand more about the forms I am searching for.

## Hypothesis or Bet
**If** we create form detail pages fully in Spanish **then** we expect that users searching for Spanish forms will use them.

## OKR
_Which Objective / Key Result does this epic push forward?_

### Details pages that have body copy and headings in Spanish are created for PDF forms in Spanish
- [ ] Consult with localization team
- [ ] Request redirect removals for Spanish pages to coincide with go-live
- [ ] Create templates in Spanish
- [ ] Unit, a11y tests
- [ ] Peer review
- [ ] Internal staging test
- [ ] Staging review
- [ ] Go live
*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
