### ISSUE TITLE
508-defect-2 [SCREENREADERS]: Text related to heading renders above heading

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#25026]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**VFS Point of Contact:** _First name only: Angela

<h2>User Story or Problem Statement:</h2>
When a screen reader user navigates a web page, they will often navigate to a heading and then read the text below it. Text related to the heading which is above it will often be missed.

<h2>Details</h2>
Above the level two heading "main location," there is a statement that we provide counseling, support, and other services at the main location. This statement will be missed by screen reader users who arrow below the "main location" heading for information about the main location.

![image](https://user-images.githubusercontent.com/55411834/122117425-1300f700-cde4-11eb-8048-62c5770b0bc5.png)

## Tasks
- [ ] Remove intro text which appears between H1 **Locations** and H2 **Main Location**

> We provide all of our counseling, outreach, and support services at our main location 

## Acceptance Criteria
- [ ] No text displays between H1 **Locations** and H2 **Main Location**
- [ ] Ensure appropriate spacing between headings

**Comment by mmiddaugh** [comment]
@AngelaFowler82 and @joshkimux 

The following description pertains to the Vet Center Locations page. 

The purpose of the page is to help Veterans understand the locations where they can receive Vet Center services, including the main location, satellite, and mobile locations affiliated with the Vet Center. It also lists nearby locations affiliated with other Vet Centers but which might be geographically closer. 

Locations page is heading level 1. 
Main location and Satellite Locations are both heading level 2. 

Intro text which says "We provide all of our counseling, outreach, and support services at our main location." is located above the Main Location H2. As you noted, the text could be missed by navigating straight to the Main Location heading. 

Rather than moving that text beneath the Main location heading, we propose removing it entirely because we believe Veterans will infer that meaning from the "Main location" heading itself. 

Text following the Satellite location heading informs Veterans that these locations provide select services. It will be retained to create an accurate expectation about what is available at other non-Main locations. 

Are there other factors we should consider or will this resolve the contextual defect?

**Comment by joshkimux** [comment]
@mmiddaugh This sounds good to me! 🥳

**Comment by nicko-amida** [comment]
@mmiddaugh @joshkimux As far as spacing goes, for H1 headers with no text/buttons underneath, I would default to the "Location" H1 with a bottom-margin of 20px, and the "Main Location" H2 with a top-margin of 45px. This are pretty much default [design system guidelines](https://design.va.gov/design/typography), but the the H1 bottom and H2 top margins appear to overlap each other - as for why, that may be a general question for engineering.
