### ISSUE TITLE
LGY - Investigate Alternate Pre-Fill Sources

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25041]
## Background
LGY prefers to use their records as the source of truth for veterans because if they have existing information for someone, it makes processing COE requests much simpler. 

Currently vets-api has existing infrastructure setup for one source of prefill - mvi. We need to do some research into how feasible it is to pull data from another entity and prefill our forms with it. 

## Considerations
- There is some concern with the level of detail the LGY data source might have but we need to know if pre-fill is static to the existing user profile object as a source of truth for pre-fill.

## Tasks
- [x] Investigate how pre-fill can work if given a different data source
- [x] Document any findings in the eben folder

## Acceptance Criteria
- [x] PR into eben folder has been made with any applicable findings.

**Comment by micahchiang** [comment]
Updated the engineering notes for LGY - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/engineering-notes.md
