### ISSUE TITLE
Develop and Prioritize potential research opportunities (Unauth Portfolio)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25040]
## Description
_This ticket will account for the work in putting together a research spreadsheet of potential research opportunities, which is populated with potential future research opportunities. This document will be used to better understand what research needs there are, how to prioritize them, and what to work on when._

Links to Existing Docs:
[Google Research Project Spreadsheet](https://docs.google.com/spreadsheets/d/1LPSVtEs-lTeYWkcdu9XcFfEHP5mBiM1mjHWvHqKiaHE/edit?usp=sharing)
[Github Version](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/Research%20Opportunities%20on%20VA.gov.xlsx)

Previous Github Docs:
[PM Recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-we-work/research-opportunties.md)
[List from post wayfinding research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-we-work/potential-research-for-unauth.md)

## Tasks
- [ ]  Develop and maintain research spreadsheet (opportunities) 
- [ ] Continue to share and prioritize research needs with unauth crew
- [ ] Gather feedback from unauth PM/POs in support of potential future research opportunities

**Comment by cindymerrill** [comment]
Touched base with Marci about find a form research needs, reviewed open ticket, scheduled time to talk with her and Cassandra about it tomorrow.

Had a really good meeting with Sharon and Danielle about Content & Localization research requests. I heard about what they’re looking for and shared my thoughts. They know I’m not available to conduct research for them right now, but I gave them advice and offered to consult a bit with them to help.

**Comment by cindymerrill** [comment]
Talked with John and Meg about how to approach recommendations meeting with OCTO-DE on Wed 6/16. Have prep work to do before that.

**Comment by cindymerrill** [comment]
Talked with Angela Fowler, who asked if I could do more research on the VA.gov home page with Veterans who use assistive technologies, including less experienced/non-expert screen reader users, users with low vision who may be zooming into text. She would like some data in order to supplement the usability audit that Trevor and Angela plan to do. I’m booked with 3 studies until September, so that would be the earliest possible time to work on this.

**Comment by brianalloyd** [comment]
Closing ticket based on work completed.  Plan to move details to a longer term repo such as google sheets or GH sheet or a combo of both.

**Comment by cindymerrill** [comment]
Repo currently maintained in google sheets: https://drive.google.com/file/d/1V09xgMc7lL233AY7JeEIo-0VYEB81yKc/view?usp=sharing
