### ISSUE TITLE
Build out Language Assistance and Resources pages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#25060]
## User story

As a Veteran, caregiver, or family member, I need to know how to get language assistance, resolves problems, and file a discrimination complaint. As someone with limited English proficiency, I need this information in my first language. I also need access to available information in my first language.

## Issue Description
Build out Drupal pages: 1 in Spanish, 1 in Tagalog.

---
## Tasks
- [x] Build shells of pages using English content
- [ ] Update URLs to translated URLs
- [ ] Add links to available in-language materials
- [x] Add translated content (when available)

## Acceptance Criteria
- [x] Pages are built out in Drupal

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. We need to start building out the Spanish and Tagalog pages in Drupal. Could you please build out the shells of these pages, based on the attached Word doc? You'll see that there's a comment with more info on where to pull links. We'll flow the translated content into the pages and update the URLs to the translated URLs once we get the translations back.

@SKasimow Could you please give Selina the info/links to the Spanish-language applications to include?

Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Please hold off on this for the moment. Sharon and I are checking on something around this.

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA Ok. I'll stop working on this. I'll just include the node link for the work I've done thus far.

- VA [Spanish]-language assistance and resources: http://preview-prod.vfs.va.gov/preview?nodeId=20078

**Comment by DanielleThierryUSDSVA** [comment]
This is looking great so far - thank you, @lunascoop!

I think we're good to continue with building these out. Just one note: On the Spanish page, we only want to link to resources that are available in Spanish. So we don't need to include the links to the English fact sheets. Same with Tagalog...for Tagalog, I there are very few fact sheets available at this time. So we may want to just go with: Covid-19 and then Benefits sections. Let me know once you look through the fact sheets and see what's available. Thanks!

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA the shell pages have been created. I noticed on the benefit fact sheet page that there's a PDF listed as Tagalog but is likely Spanish. Here's the link.
**Traumatic Injury Protection Under Servicemembers' Group Life Insurance:** https://benefits.va.gov/BENEFITS/Tagalog/Factsheets/insurance/TSGLI_tag.pdf
It's under the Insurance section: https://benefits.va.gov/BENEFITS/factsheets.asp#BM8

- VA [Tagalog]-language assistance and resources: http://preview-prod.vfs.va.gov/preview?nodeId=20092
- VA [Spanish]-language assistance and resources: http://preview-prod.vfs.va.gov/preview?nodeId=20078

**Comment by SKasimow** [comment]
Hi @lunascoop! Here are the links to the Spanish language application forms:


TITLE | LANGUAGE | URL | Lnaguage on Form
-- | -- | -- | --
About VA Form 10-10EZ (esp) | Spanish | https://www.va.gov/vaforms/medical/pdf/10-10EZ_Spanish.pdf | spanish
About VA Form 21P-0510(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0510(Spanish)-ARE.pdf | spanish
About VA Form 21P-0518-1(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0518-1(Spanish)-ARE.pdf | spanish with english translation
About VA Form 21P-0519S-1(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0519S-1(Spanish)-ARE.pdf | spanish with english translation
About VA Form 21P-0517-1(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0517-1(Spanish)-ARE.pdf | spanish with english translation
About VA Form 10-0137 (espanol) | Spanish | https://www.va.gov/vaforms/medical/pdf/VA Form 10-0137espanol(1).pdf | spanish with english translation
About VA Form 21P-0512s-1(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0512s-1(Spanish)-ARE.pdf | spanish with english translation
About VA Form 21P-0519C-1(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0519C-1(Spanish)-ARE.pdf | spanish with english translation
About VA Form 21P-0513-1(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0513-1(Spanish)-ARE.pdf | spanish with english translation
About VA Form 21P-0516-1 (Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0516-1(Spanish)-ARE.pdf | spanish with english translation
About VA Form 21P-0514-1(Spanish) | Spanish | http://www.vba.va.gov/pubs/forms/VBA-21P-0514-1(Spanish)-Are.pdf | spanish with english translation

cc @DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
@lunascoop @DanielleThierryUSDSVA assume we should drop (Spanish), (esp) and (espanol) from "Title".

Would also be helpful to add in purpose of form such as "SOLICITUD DE VERIFICÁCION DE ELEGIBILIDAD
PENSION" (which is from text in PDF https://www.vba.va.gov/pubs/forms/VBA-21P-0512s-1(Spanish)-ARE.pdf).

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @lunascoop!

**Comment by RLHecht** [comment]
@lunascoop Here is the translated content back for both pages. Could you please add them in? Thanks!

[12709_VA.gov_language assistance_Spanish .docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6591427/12709_VA.gov_language.assistance_Spanish.docx)

[12710_VA.gov_language assistance_Tagalog Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6591428/12710_VA.gov_language.assistance_Tagalog.Final.docx)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. And here are my notes:

- VA [Tagalog]-language assistance and resources: http://preview-prod.vfs.va.gov/preview?nodeId=20092
- VA [Spanish]-language assistance and resources: http://preview-prod.vfs.va.gov/preview?nodeId=20078

**Possible translation issues (via Google translate):**

- Tulong sa wikang Tagalog at dulugan ng VA (Tagalog language help and VA resources): not, "VA Tagalog language resources and help"
- Mga benepisyo para sa mga Beterano at mga miyembro ng sandatahang lakas (Benefits for Veterans and members of the armed forces): Should it be service members
- Missing translations for [accordion 3] Veterans with service-connected disabilities (both Spanish and Tagalog)

Spanish Forms (which I added to their respective accordions):

- Need to decide formatting. Some forms have esp, or espanol. I've removed them for now.
- Will they all have descriptions?
- For VA Form 10-0137, I sort of rewrote the description I found since it was bulleted via Google translate. Description can be found here: https://www.va.gov/find-forms/about-form-10-0137a/

**Comment by RLHecht** [comment]
I've reviewed these and sent the missing text to the translation team.

**Comment by RLHecht** [comment]
@lunascoop here's the translations back with the missing text included. Can you please add to the pages?

[https://app.zenhub.com/files/133843125/367127d8-abd2-4191-981d-f932bf428921/download](https://app.zenhub.com/files/133843125/367127d8-abd2-4191-981d-f932bf428921/download)

[https://app.zenhub.com/files/133843125/3ecd78c2-9437-4793-9ebf-3e4b5100f633/download](https://app.zenhub.com/files/133843125/3ecd78c2-9437-4793-9ebf-3e4b5100f633/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. cc: @DanielleThierryUSDSVA 

- VA [Tagalog]-language assistance and resources: http://preview-prod.vfs.va.gov/preview?nodeId=20092 (only the service member accordion title was updated)
- VA [Spanish]-language assistance and resources: http://preview-prod.vfs.va.gov/preview?nodeId=20078 (Page intro and the service member accordion title was updated)

**Comment by RLHecht** [comment]
Thanks, Selina! @DanielleThierryUSDSVA These 2 pages are ready for you. I noticed that a few of the accordions are not there anymore and we wanted to confirm that's intentional.

**Comment by RLHecht** [comment]
@lunascoop We just got these back from the VHA translation team after we sent it to them with some changes to the pages. Could you please input these and let me know if you have any questions I need to take back to them? Thanks!

[https://app.zenhub.com/files/133843125/7c77dcc7-1b22-4dec-8984-635ae14188af/download](https://app.zenhub.com/files/133843125/7c77dcc7-1b22-4dec-8984-635ae14188af/download)

[https://app.zenhub.com/files/133843125/2b1105c8-b997-4846-88d1-8ce1aba2f1df/download](https://app.zenhub.com/files/133843125/2b1105c8-b997-4846-88d1-8ce1aba2f1df/download)

**Comment by RLHecht** [comment]
These pages have both been published with the revised translations.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I just want to confirm that this ticket can be closed. I believe the work is complete from sitewide content.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA hi - cleaning up our board; can this be closed?

**Comment by DanielleThierryUSDSVA** [comment]
Yes, closing.
