### ISSUE TITLE
Write Questionnaire Job Aid for Clinic Staff

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25079]
# Description
Staff members within the Loma Linda pilot site need guidance on how to answer questions from Veterans about the new questionnaires

# Tasks
- [x] Find current write up about how to log into va.gov
- [x] Write draft document

# Acceptance Criteria
- [x] Review with team (and content?)
- [x] Send to Loma Linda

**Comment by kristenmcconnell** [comment]
Add escalation plan to this job aid.

**Comment by kristenmcconnell** [comment]
Draft job aid.

[https://app.zenhub.com/files/133843125/dc7c8797-a233-409e-b2df-bc8f3657b6cc/download](https://app.zenhub.com/files/133843125/dc7c8797-a233-409e-b2df-bc8f3657b6cc/download)

**Comment by kristenmcconnell** [comment]
[Sent to product team to review via Slack.](https://dsva.slack.com/archives/C0136TS768M/p1622060070076100)

@DanielleThierryUSDSVA If you have time to review this too.

**Comment by kristenmcconnell** [comment]
[Discussed escalation plan with Corey Parker and updated the Job Aid draft.](https://app.zenhub.com/files/133843125/4ba621df-bad6-42d1-be14-b55ba4e3407d/download)

**Comment by kristenmcconnell** [comment]
Incorporated more edits from Patrick and Troy Riser (writer). Waiting on final approval to send to Dr. Byrne's office. Closing ticket though, since the work is done.[https://app.zenhub.com/files/133843125/a43fccc1-a527-460a-9256-2d0ad9631e49/download](https://app.zenhub.com/files/133843125/a43fccc1-a527-460a-9256-2d0ad9631e49/download)

**Comment by kristenmcconnell** [comment]
Sending to Loma Linda now.
