### ISSUE TITLE
Plan migration of documentation to new locations

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#25085]
## Issue Description
As a Testing Tools Team member, I want all of our documentation to be located in the spaces recently made available in Confluence and the Platform Website, so that our team and other teams can easily find what they are looking for.

---
## Tasks
- [x] Read the guidelines and documentation for both the [Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+Website+Guidelines) (intended for VFS teams) and for [Operational Documents on Confluence](https://vfs.atlassian.net/wiki/spaces/AP/pages/1287782439/Platform+Crew+operational+documentation) (Intended for Platform/OCTO-DE teams)
- [x] Conduct an audit of current documentation for Testing Tools, defining what documentation should end up in which place, and then prioritize those areas to ensure that the most important documentation is updated first
- [x] Document that migration plan into a Zenhub Ticket/Confluence page
- [x] Get Leadership/OCTO-DE input and guidance for that plan and its ticket

## Acceptance Criteria
- [x] Migration plan is documented in a Zenhub Ticket
- [x] That plan is approved by appropriate OCTO-DE leadership

**Comment by JoeTice** [comment]
Tasks that have come up are available here in [25086](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/25086)
