### ISSUE TITLE
Migrate Testing Tools Team documentation based on plan

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#25086]
## Issue Description
As a Testing Tools Team member, I want all of our documentation to be located in the spaces recently made available in Confluence and the Platform Website, so that our team and other teams can easily find what they are looking for.

This ticket will be populated by tasks and acceptance criteria based on the completion of ticket [25085](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/25085)
---
## Tasks
**Operational Documentation** - [Guidelines here](https://vfs.atlassian.net/wiki/spaces/AP/pages/1287782439/Platform+Crew+operational+documentation)
- [x] Migrate team documentation to the [Testing Tools Team Space](https://vfs.atlassian.net/wiki/spaces/TTT/overview)
- [ ] Migrate product documentation for Testing Tools products to [Products/Services spaces](https://vfs.atlassian.net/wiki/spaces/PPS/overview)
- [ ] Migrate platform documentation for Testing Tools practices to [Platform Space](https://vfs.atlassian.net/wiki/spaces/AP/overview).

**Platform Website Documentation** - [Guidelines here](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+Website+Guidelines)
- [ ] Migrate VFS-facing documentation to the appropriate area on  [Platform Website](https://depo-platform-documentation.scrollhelp.site/index.html)
  - [x] Manual Functional Testing/TestRail
  - [x] A11y Testing/Axe Scans
  - [x] Manual A11y Test Rail Templates
  - [x] Unit Testing/Liquid Templates
  - [x] E2E Testing/Cypress
  - [x] Contract Testing/Pact
  - [x] Load Testing/Locust
  - [x] Collaboration Cycle: A11y Documentation
  - [x] Collaboration Cycle: QA Practice Area Documentation

## Acceptance Criteria
- [x] Documentation is reviewed by Testing Tools Team Staff
- [ ] Documentation is reviewed by our OCTO-DE Lead (optional)

**Comment by shiragoodman** [comment]
FYI @JoeTice @pjhill we created ticket #30216 to take on the QA and Accessibility documentation relevant to the Collab Cycle. Please review the ticket and let me know if we're missing any pages. Thanks!

**Comment by pjhill** [comment]
I've completed migration of all QA documentation.
