### ISSUE TITLE
[Research] Conversation Guide for Staff at the Pilot Site

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25099]
# Description
Staff members at Loma Linda will be helping to collect feedback from Veterans on the health questionnaire pilot. They staff need to know what questions we want to ask.

# Tasks
- [x] Draft the questions

# Acceptance Criteria
- [x] Review with team
- [x] Make sure that the guide is sent to Loma Linda

**Comment by kristenmcconnell** [comment]
[Draft guide to be utilized by the office staff](https://docs.google.com/presentation/d/1XAqnUKsL5C-Btg_QTFwLUWJeRbn4xNB-Lhzttm-9P4c/edit?usp=sharing) and a [spreadsheet where they can enter the Veteran's feedback](https://docs.google.com/spreadsheets/d/1H0pGsvwg6NqFI4D0WA47fUFu5BPtpqsIC2j4k9igNIc/edit?usp=sharing).

**Comment by kristenmcconnell** [comment]
Drafts: 

- [Overall planning document](https://app.zenhub.com/files/133843125/16d48415-1aa6-47a5-ab9a-08b72f32ecb9/download)

- [Document to print and collect the feedback](https://app.zenhub.com/files/133843125/fca2402f-9350-43a2-8ee6-073b88a88435/download)

- [Spreadsheet to collect feedback](https://app.zenhub.com/files/133843125/5d0f028b-ff35-4efd-89c2-e613bb42ba0e/download)

**Comment by kristenmcconnell** [comment]
Send to product team to review.

**Comment by kristenmcconnell** [comment]
[Updated planning document with feedback from Patrick Bateman incorporated.](https://app.zenhub.com/files/133843125/77fc0044-ea15-4de6-9b04-2ad76b54b599/download)

**Comment by kristenmcconnell** [comment]
Email sent to Dr. Byrnes and Sharon on May 27 requesting that a meeting be scheduled with the staff members that are actually gathering the feedback. This way, I can review the details of the plan and answer any questions that they have.

The .pdf research plan was sent in the email as well for the office to review ahead of that meeting.
