### ISSUE TITLE
Language Switcher | Language + Resource Pages

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25094]
## Issue Description

We need to be able to communicate to screen readers when a language within a given page or section switches from English to Spanish or Tagalog, for example.

## Tasks

- [ ] Create abstract language code setting logic from the language switcher component into react hooks for re use by other react components that include or reference translated content   
- [ ] investigate using React Router in the Footer component to implement client side redirects / preserve redux state on link click. may need to use local storage instead

## Acceptance Criteria

- [ ] Screen readers will correctly switch between English and other languages that may be included in a given page or section.

**Comment by SKasimow** [comment]
@youngfreezyVA Hi Fareez - when you have a moment, can you please review this ticket to make sure I've captured the work and criteria etc correctly and also point it for this sprint?

Thanks!

Sharon

cc @DanielleThierryUSDSVA

**Comment by youngfreezyVA** [comment]
thanks @SKasimow ... initially I thought I could use redux, but then I realized that state will not be preserved when clicking on a link, so I implemented client side re directs with `React Router`, using this example:

https://reactrouter.com/web/example/custom-link

**Comment by SKasimow** [comment]
@youngfreezyVA That sounds good Fareez. Are there any links/examples you are aware of where you won't have control over the structure of the link on the front end? Or is that more of a situation we may encounter in a future effort/different pages than the ones for this project?

**Comment by youngfreezyVA** [comment]
yes, there are cases where the new translated content will include links, so i included a function to modify onclicks with existing links to integrate with the redux store

**Comment by SKasimow** [comment]
Great point
