### ISSUE TITLE
Implement EKS rolling update

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#25092]
## Description
This is a effort to integrate https://github.com/hellofresh/eks-rolling-update into our workflow as a GHA that can be triggered manually or run on a schedule.

It will allow us to update the EKS worker nodes within our clusters with little to no interruptions in service if they one reach a certain age or two the launch template is updated.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Create service account for EKS with proper permissions to run said script
- [x] Create GHA that can be run manually or on a schedule
- [x] Message slack on success/failure

## Definition of Done
- [x] EKS clusters have a regular rolling update, scheduled and operating

**Comment by jhouse-solvd** [comment]
I think all that's lacking here is a definition of done that we can check off. then can likely be closed.
