### ISSUE TITLE
[FE] Adjust Spacing within Cards

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25117]
# Description 
- Since we moved to more platform-level component after staging review, some of the spacing needed within are cards/alerts need to be adjusted. There is currently extra spacing.

# Tasks
- [x] Adjust the <p> that starts with "Note" on the review page to a margin-top: .5em. This matches the same alert on the introduction page.

Review page screenshot:
![Screen Shot 2021-05-24 at 10.35.51 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9a73a410-1502-4345-a785-5bd562163471)

Introduction page screenshot:
![Screen Shot 2021-05-24 at 10.36.30 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/e5004b10-fb6c-4833-ae62-2263071adc6f)

- [x] Adjust the H3 (example: Primary care questionnaire) within the To Do cards to 1em

To Do screenshot (before adjustment):
![Screen Shot 2021-05-24 at 10.36.09 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/b22735c7-ca5c-411e-893d-ee7e4f78ce53)

- [x] Adjust the H3 within the Completed cards to .5em 

Completed screenshot (before adjustment):
![Screen Shot 2021-05-24 at 10.51.38 ### AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/4226e68f-727b-44e9-94f9-53f2ae8c356d)

# Acceptance Criteria
- Remove Spacing

**Comment by mdewey** [comment]
Just to let you know all of these are fixable.

**Comment by kristenmcconnell** [comment]
Wonderful!

**Comment by mdewey** [comment]
@kristenmcconnell  This is in staging. Can you review?

**Comment by kristenmcconnell** [comment]
Looks fantastic.
