### ISSUE TITLE
Authenticated Experience: Sprint 51 (6/30- 7/13)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25126]
## Priorities

1. Begin phased launch of My VA (50% by end of sprint)
2. Continue Notification Prefs build
3. My VA "Actions Items" research: plan research + documentation
4. Profile "cleanup"

PTO
- Erik 7/2
- All team members 7/5 (Independence day observed)

## My VA redesign

**PM**
- [x] Monitor analytics post-launch to 25% #26226
- [x] Monitor analytics post-launch to 50% #26230 
- [x] Submit redirect request for old Find VA Benefits section (see #25149 for reference) - _redirect deemed unnecessary per comments in [26747](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26747)_

**Design**
- [x] Determine method for testing action items work + plan research #25980
- [x] Create mockups for elevating action items #26569
- [x] Figure out what is possible from an accessibility standpoint #26641
- [x] Regroup on notifications + action items #26949

**FE**
- [x] Launch to 25% #26226
- [x] Launch to 50% #26230
- [x] Stop using client-side routing for My VA #26752

**BE**
- [ ] Kill user/preferences API #26705

## Notification Preferences
**PM**
- [x] Regroup on notifications + action items #26949

**Design**
- [ ] Follow-up items from research:
     - [ ] Revisit design for status messages and notification channels #25985 
     - [x] Share notification settings findings and recommendations with VA Profile / VA Notify team #26913 
     - [x] Consult with IA on the order of notification groups #26921
- [x] Regroup on notifications + action items #26949

**FE**
_from sprint 50_
- [x] Make CommunicationGroup model class #26193 
- [ ] High-level tests for FE #24864 

- [ ] Continue build: 
     - [ ] Build the FE functionality for VIEWING notification preferences #25784 
     - [x] Create feature flag for notification preferences feature #26837
     

## Preferred Facilities

**Design**
_from sprint 50_
- [x] VAOS/profile facilities research synthesis #25510

## Profile

**Design**
- [x] Confirm proper styling of edit buttons and edit forms on mobile #26529
- [x] Improve UX for "remove" [contact information] button #23665 (_from sprint 50_)

**FE**
- [x] Long email addresses break Profile layout #27072 
- [x] Contact info tables incorrect (missing rounded corners + x-padding table headers and rows) #27071
- [ ] Profile, DD: Update screen reader to so user hears "updating your preferences" instead of "dimmed" #24954
- [ ] Update DD4CNP "please add your bank info" state #26710
- [x] Update focus upon "edit" so first field is announced immediately #24952
- [ ] Accessibility Audit:
     - [x] 508-defect-2 [AXE-CORE]: Autocomplete attribute must be used correctly for home address/mailing address checkbox #23173 (_from sprint 50_)
     - [ ] 508-defect-3 [SCREENREADER]: International support information should programmatically describe the number field #23162
     - [x] 508-defect-3 [COGNITION]: Links should be styled as links, connected apps #23171
     - [ ] 508-defect-3 [COGNITION]: Link text should make sense when taken out of context in the disconnect alert on connected apps #23436
     - [x] 508-defect-3 [SCREENREADER]: Decorative gear icons should not be announced to screen reader users #23437
     - [ ] Defect-level-4 [SCREENREADER]: Update markup in DD bank info Additional Info #22522 

**BE**

- [x] Work needed to support contact info update email #25865 (_from sprint 50_)
- [x] Fix contact info change email bug #26924

## Backend work
- [x] Lihan assisting the identity team
