### ISSUE TITLE
Authenticated Experience: Sprint 52 (7/14 - 7/27)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25127]
## Priorities

1. Launch My VA 2.0 to 100%!
2. Continue Notification Prefs build
3. My VA "Actions Items" research: mockup refinement and prototype development
4. Profile "cleanup"

PTO
- AJ 7/16 - 7/21
- Liz 7/19 - 7/23
- Tressa 7/20 - 7/21

## My VA redesign

**PM**
- [x] Monitor analytics post-launch to all users #26231 
- [x] Coordinate with comms team on My VA blog post #25305
- [x] Prep for and conduct demo of My VA for chairman of board of appeals #27184

**Design** 
- [x] Prep for and conduct demo of My VA for chairman of board of appeals #27184

**FE**
- [x] Launch to all users #26231 
- [ ] Send appropriate events to GA for enhanced tracking on Claims & appeals #27167
- [x] Reset GA error-key after sending one to GA #27845
- [ ] Clean up My VA 1.0 code post 2.0 launch to 100% #27326
- [ ] Remove feature flag code for My VA 2.0 #27379

**BE**
_from sprint 51_
- [x] Kill user/preferences API #26705

## Action Items Discovery

**Design/Research**
- [x] Review action items mocks and refine #27270
- [ ] Create UX-pin for testing #27271
- [x] Overview of Action Items discovery + BE discussion #27268

**FE & BE**
- [x] Overview of Action Items discovery + BE discussion #27268

## Notification Preferences
**PM**
- [ ] Finish test case documentation #26223

**Design**
- [x] (_from sprint 51_) Revisit design for status messages and notification channels #25985
- [x] Notification settings: create mobile version of update designs #27490

**FE**
Continue build: 
- [ ] (_from sprint 51_) Build the FE functionality for VIEWING notification preferences #25784
- [x] Handling sorting of communication groups on the frontend #27118
- [ ] (_If time permits_) Build_ the FE functionality for EDITING notification preferences #26836 

## Preferred medical facility

**PM**
- [x] Learn more about My VA Treating Facilities (facility preferences) in MHV #27100

**Design**
- [x] Learn more about My VA Treating Facilities (facility preferences) in MHV #27100

## Profile
**Design**
- [x] Revisit how we present information about login vs contact email address #26950

**FE**
- [x] Implement table styling for screens >768px #27377
- [ ] Implement improved "remove" [contact information] button functionality/UX #27169
- [x] Implement proper width styling of all buttons and forms for mobile #26531
- [x] (_From sprint 51_) 508-defect-3 [COGNITION]: Link text should make sense when taken out of context in the disconnect alert on connected apps #23436
- [ ] (_From sprint 51_) Defect-level-4 [SCREENREADER]: Update markup in DD bank info Additional Info #22522
- [x] (_From sprint 51_) Update DD4CNP "please add your bank info" state #26710

## Research
- [ ] Auth Exp best practices research phase 2 #24974 

## Backend
- [x] Lihan assisting identity team
- [x] Don't retry on VANotify 400 errors #26980
- [x] Fix sidekiq expires_in jobs #27059
- [ ] Add statsd logging to ch33 direct deposit api calls #25667
