### ISSUE TITLE
** SPRINT 49 PRIORITIES**

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25135]
<hr>

## :fire: Sprint 48 Priorities

- [ ] 1. Find a VA Form Search improvements go-live
- [ ] 2. Discovery for Discharge Upgrade Wizard - send link to Zach to existing
- [ ] 3.  Find a VA Form: Implement new UI/UX Standards on Staging #22452 (start if enough capacity)

#### Zach
- [ ] Staging Review Decision Tools - Find a VA Form Search Term Transformation Iteration 2 #24436
- [x] Discharge Upgrade Wizard: Update DD149 PDF link on DD214 Request Page #23988
- [ ] [Discovery] Discharge Upgrade Wizard - Link change ONLY for Air Force Veterans directed to DD149 #24928
- [ ] [STRETCH] Find a VA Form: Implement new UI/UX Standards on Staging #22452

#### Cassandra
- [ ] Consult with Zach as needed for **Find a VA Form: Implement new UI/UX Standards on Staging #22452**

#### John
- [ ] Find a VA Form: Internal testing - test search matching/ranking in Forms API on Staging #22866

#### Marci
- [ ] Find a VA Form: Internal testing - test search matching/ranking in Forms API on Staging #22866
- [ ] Update screen shots on TestRail for Find a Form testing
- [ ] Re-schedule staging review **[IN PROGESS] Staging Review Decision Tools - Find a VA Form Search Term Transformation Iteration 2 #24436**
- [ ] Discharge Upgrade WIzard: Research into conditional content display #24999
- [ ] Map out decision tree for Discharge Upgrade Wizard - started Mural board: https://app.mural.co/t/vsa8243/m/vsa8243/1621532440874/8a3ee02c63bf5216b24fb01025e1e109b43d5407
- [ ] Determine target refinement rate for Find a VA Form
- [ ] Research delta in spellchecking methodologies used on different search tools

###  🗨️  Discussion Topics/Grooming 
- [ ] Topic
- [ ] Topic
- [ ] Topic

**Comment by MarciMcGuireGCIO** [comment]
2021-06-10

- Ryan talked to Shawna about spec'ing out everything for the engineers.  Engineers can use InVision inspect mode to see the spacing, etc.
- Design intent for UI consistency, relevance/popularity, PDF download and Related To
- Zach worked with Kelson on an issue, started on Find Form detail page UI changes
- Design UI consistency work - need to find the tickets where the final Sketch links were added.

**Comment by MarciMcGuireGCIO** [comment]
2021-06-11

- Zach got UI updates back on Staging
- Working on Detail page update - can put behind 
- Marci looped in Shawna and Ryan per their request to look at before VSP Staging review
- Marci requested Midpoint review
- Zach may be taking PTO next Friday

**Comment by MarciMcGuireGCIO** [comment]
2021-06-14

- Zach added the gray lines between the search results & submitted a PR, so it's not on Staging yet.  
- Cassandra will update the mockup headers & intro so it matches Staging
- Cassandra will let Content team know that she doesn't need rush content for the download link since that is not going live Jul 6
- Cassandra will iterate on her PDF download instructions design and re-present to design team before requesting content.
- We have de-scoped the PDF download info from the July 6 release and are meeting with Cindy on Wed to talk about testing with users (will have to be on Staging if we test with a screen reader)
- Marci is updating test cases for Tze; just need to include Sketch links with updated headers & intro text
