### ISSUE TITLE
[FE] My VA: Kill "Find VA Benefits" feature on My VA 1.0 prior to My VA 2.0 launch

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#25149]
## Background

Additional discussion in #25071.

Because the Find VA Benefits feature is not moving over to My VA 2.0, there would have been issues if someone went to the Find VA Benefits selection page and tried to save new settings if they already had My VA 2.0 turned on. We agreed the easiest approach was to kill this feature on My VA 1.0 just prior to My VA 2.0 launch in order to avoid any wonkiness.

## Tasks

- [x] Just prior to My VA 2.0's phased launch, kill the Find VA Benefits feature on My VA 1.0
- [x] Verify it's gone in staging
- [ ] Let AJ or Samara know this is complete so we can complete a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request) for the old Find VA Benefits selection page.

**Comment by erikphansen** [comment]
@ajakabcin I'm going to get started on this. I might not merge it immediately, but I want it to be ready to merge so I don't need to worry about it when we are closer to releasing My VA 2.0

**Comment by erikphansen** [comment]
We should also [kill the APIs that supported this feature](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26705)

**Comment by erikphansen** [comment]
@ajakabcin Find VA Benefits is no longer on staging. It'll be removed from prod today. We should get the redirect set up ASAP.

**Comment by ajakabcin** [comment]
Created #26747
