### ISSUE TITLE
526 Form Removal - Combat Zone - BE

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#25173]
## Issue Description

Advisement from Paul Shute that this page is not needed per VBA's claim process. Therefore it can be removed completely from the 526/BDD form - making any page design changes unnecessary.

## Tasks
- [x] Remove combat zone page. (related to this [design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19545#event-4413775804))
- [x] FE ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/21013
- [x] update return url if http://localhost:3001/disability/file-disability-claim-form-21-526ez/review-veteran-details/combat-status
- [ ] 

## Acceptance Criteria
- [x] Evidence of form removal. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
url="/review-veteran-details/combat-status"
  forms = InProgressForm.where( form_id: '21-526EZ').return_url(url)
  forms.each do |f| 
    md = f.read_attribute('metadata')
    md['returnUrl'] = '/review-veteran-details/military-service-history'
    f.write_attribute('metadata', md)
    f.skip_exipry_update = true
    f.save!
  end
