### ISSUE TITLE
Increase content build self-hosted runner memory to 32gb

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#25179]
## Description
FE Tools is testing the content build (`yarn build` in the `content-build` repo) on Jenkins with a lot of additional data. This simulates what we'll experience later this year. We'd like to run the same build on the GHA self-hosted runner. Our experimental Jenkins builds show that peak memory use is about 25gb of the 32gb available on the Jenkins nodes. We'd like to increase the available memory for the content-build runner to match Jenkins (32gb).

## Background/context/resources
- Benchmarks, methodology, and memory use graphs (Jenkins content build) are in this ticket: [Discovery: test content build with 48k nodes on Jenkins](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/24022)

## Technical notes
- If there are configuration differences between Jenkins nodes and the GHA self-hosted runner, they may cause issues with the content build. This is especially true with large amounts of content. We'd like to surface these issues on GHA soon so we can fix them before we encounter them in production.

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] Available memory on the self-hosted GHA runner for content-build is 32gb

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by dginther** [comment]
new runners with 32GB RAM are launching in the content-build repo.
