### ISSUE TITLE
Determine Alias/Root URL for CLP Pride & Discharge Upgrades

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25180]
## Issue Description
_Determine Alias/Root URL for CLP/Pride & Discharge Upgrades.  Next step would be submitting a Redirect request for Vanity URL_

Determination: The root URL will be: https://www.va.gov/initiatives/lgbt-veterans (as set by John S. Hero H1) and the preferred vanity URL redirect would be https://www.va.gov/lgbt

## Tasks
- [x] Determine Alia/Root URL for CLP/Pride & Discharge Upgrades
- [x] Once URL is validated - Submit a Redirect Request for Vanity URL
- [x] Link to Redirect Request URL

**Comment by brianalloyd** [comment]
@mnorthuis wanted to loop you in soonest as we're working a Pride & Discharge Upgrade CLP and wanted to run a redirect element past you for review and validation.  

He says the root URL will be: https://www.va.gov/initiatives/lgbt-veterans (as set by his Hero H1) and his preferred vanity URL redirect would be https://www.va.gov/lgbt  

Any issues with the suggested vanity URL or Redirect element?  CC @johnhashva @kelsonic

**Comment by johnhashva** [comment]
Update from 5/28 Slack thread:

@mnorthuis -- In regards to the vanity URL, this looks like a campaign related to Pride Month, so an annual type thing?  Might be helpful to establish patterns for these...i.e. /pride-month or /pridemonth?  Could be reused each year.
@johnhashva You're right -- this is specific to Pride Month. Not meant to be The Landing Page for LGBT Veterans.  So, how about I go back and recommend /pride-month as the preferred approach.  Is there a preference in format -- e.g. pride-month vs. pridemonth?
@mnorthuis our URL standards do require the hyphen, but with these campaign pages, I understand the desire for them to be more "marketable".  When I google "Pride month" you do see a lot of pages that use "pride-month", so I'm inclined to stick with our standards if possible.
@johnhashva Let me go back to the Pride lead with this -- pride-month --  recommend.

**Comment by johnhashva** [comment]
Update from @mpeterz I am also an IA and stickler for standards. Thanks, @Mikki and @John Hashimoto! I'm 100% on board that this URL should be about Pride Month. When we create an overall audience page for LGBT (above pride month and patient care services), *then* we will need the general URL va.gov/LGBT to be available for that page.

**Comment by johnhashva** [comment]
Word back from John Santos, the Pride CLP lead -- www.va.gov/pride-month is 100% acceptable.

**Comment by johnhashva** [comment]
The vanity URL: http://va.gov/pride-month --> The root URL: https://www.va.gov/initiatives/lgbt-veterans

**Comment by mpeterz** [comment]
Having the root URL https://www.va.gov/initiatives/lgbt-veterans (under /initiatives) is also too general and will limit the URLs we can use for future CLPs related to LGBT. Since we're the ones creating the CLP URL, let's use something like va.gov/initiatives/pride-month. It would also be good to align the 2 URLs -- it will help with managing the CLP in the future when Pride Month happens again. @johnhashva @mnorthuis

**Comment by johnhashva** [comment]
Got it @mpeterz.   Danielle and I just chatted about this and we're going to propose they change the H1 to Recognizing LGBT Veterans During Pride Month (e.g. https://www.va.gov/initiatives/recognizing-lgbt-veterans-during-pride-month).

**Comment by johnhashva** [comment]
@brianalloyd and @kelsonic Final word: the URL for the Pride/CLP will be www.va.gov/initiatives/recognizing-lgbtq-veterans-during-pride-month ( LGBTQ+ will be in the H1 but stripped out by CMS). So for vanity URL:

http://va.gov/pride-month --> The root URL: https://www.va.gov/initiatives/recognizing-lgbtq-veterans-during-pride-month/

**Comment by brianalloyd** [comment]
Action complete, closing out now.
