### ISSUE TITLE
[FE][SPIKE] Determine FE Requirements for Day of Check in

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#25214]
## User Story

As a veteran, I should be able to check in on the day of my appoitnment via my mobile phone

## Related Documentation

- [WIP prototype](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/kaVYLYP/play)

## Description

Start defining requirements and architecture of the front end of the check-in process

## Questions

- How to make this page non-discoverable via searches

## Tasks

> these are the targeted questions that need to be answered in this spike

- [ ] Document risks/considerations/questions about the following flow:
  - landing page with a token in url
  - validate token
  - show stuff with check in button
  - check in button does POST
  - check in button takes to confirm page
  
- [ ] Create a prototype

## Acceptance Criteria

> when is the ticket done

- [ ] Relevant documentation has been created
- [ ] Findings shared with the appropriate team members

**Comment by mdewey** [comment]
maybe relevant notes: # notes

## Live notes

- user "texts XXXXX to check in"
- receive text message with a unique url to a va.gov site
- LoROTA lite,
- No first page
- Hiding the outer stuff (login button, header, footer, etc)
- feature flip

-

## Questions

- which team is building LoROTA?

## summary

- landing page with a token in url
- validate token
- show stuff with check in button
- check in button does POST
- check in button takes to confirm page

**Comment by mdewey** [comment]
PR with groundwork https://github.com/department-of-veterans-affairs/vets-website/pull/17423
