### ISSUE TITLE
Plan migration of BE Tools documentation

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#25227]
## Issue Description
As a BE Tools Team member, I want all of our documentation to be located in the spaces recently made available in Confluence and the Platform Website, so that our team and other teams can easily find what they are looking for.

Reference the new [Frontend developer docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) page for ideas on things we should be putting up on the new site. We should end up with a front page and linked docs similar to theirs.

---
## Tasks
- [x] Conduct an audit of current documentation for BE Tools, defining what documentation should end up in which place
- [x] Document that migration plan into #25226
- [x] Read the guidelines and documentation for the [Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+Website+Guidelines) (intended for VFS teams)

## Acceptance Criteria
- [x] Migration plan is documented in a Zenhub Ticket

**Comment by jeff2d2** [comment]
For this effort, I would create a spreadsheet that shows:
1. Current document title
1. Current doc link
1. Suggested path for where the new doc should live
and a draft of a front page (similar to the [Frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html))

**Comment by jeff2d2** [comment]
Note that some of the frontend docs already launched include links to how to set up vets-api, which are currently all in GitHub. We'll need to go back and update these links later once our docs are launched.

For example: https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html#Settingupyourlocalfrontendenvironment-Step4:Backendandinternaltoolssetup

**Comment by jeff2d2** [comment]
[Working ssheet](https://docs.google.com/spreadsheets/d/1FkkxASkBkGS4gI6mnlo5ZQL00f5lk9Tj81dkmPkuook/edit#gid=0)
