### ISSUE TITLE
Remove MPI getter functions from User model

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#25230]
## Issue Description
This story is an update to #5413; `User.va_profile` is being deprecated and conditional checking of User Identity/SSOe-derived profile information have already been enabled. There remain a number of methods to explicitly obtain user information from MPI directly instead of conditionally delegating the request to user_identity. Upon the successful switch to 100% SSOe logins most of these corner-case direct MPI/MPI profile calls should no longer be necessary and can be removed.

---
## Tasks
- [ ] Determine which explicit MPI getter methods in the User model are safe to remove and which need to remain
- [ ] Remove unneeded MPI getter methods and replace the places where they were invoked with the appropriate user_identity/MPI getter method.
- [ ] Update unit tests to remove tests for MPI getter methods and improve MPI vs. user_identity testing scenarios

## Acceptance Criteria
- [ ] Most or all of the existing User model methods that query MPIData will be removed
- [ ] Developers looking to access a user's attribute outside of the User class will have a clear and consistent set of methods to use
