### ISSUE TITLE
TUD: Refactor TUD Dockerfile to be in compliance with Devops Kubernetes

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#25243]
## Issue Description
The `docker-compose` and docker-compose YAML files are not supported in the Kubernetes infrastructure (test-user-dashboard.  Demian from DevOps pointed out that the current Dockerfile setup was not working within EKS (Kubernetes) https://dsva.slack.com/archives/CSFV4QTKN/p1621898390035900.

This is due to dependency incompatibilities OS with the `sharp` module which `gatsby-plugin-image` and `gatsby-plugin-manifest` both depend on.

---
## Tasks
- [x] Refactor Dockerfile to be used in EKS ecosystem
- [x] Fixes the `on:push:main` Github Action workflow
- [ ] Resolve `sharp` dependency incompatibility errors
- [ ] Remove/resolve Sass deprecation warnings for `usdws` dependency

## Acceptance Criteria
- [ ] Repo works in both local & production environments
- [ ] All tasks above are complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
