### ISSUE TITLE
Draft June newsletter edition (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#25248]
# User story

As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- [x] Update the Google Form (Amy)
  - remove previous submissions
  - update form langauge for next round of submissions
  - create new link for sharing survey
- [x] Solicit content from PMs (James and Liani)
- [ ] Confirm that CTA destinations have POs' approval (Liani)
- [ ] Conduct Pair writing and SME interview sessions (Amy)

Tasks for next sprint:
- Draft newsletter edition
- Conduct reviews for technical accuracy and OCTO-DE signoff
- Prepare MailChimp version (Service Design, but we support)
- Publish the newsletter via email (Service Design)
- Announce the newsletter via Slack (Service Design)

# Acceptance criteria
- To come.

# Reference info
- n/a

**Comment by lianilychee** [comment]
james  Weds 5/26 4:44 PM - PMs' channel:
Hi all, please submit announcements for the June newsletter using this form by Thursday 6/3: https://forms.gle/29sFKr4HhWuJWmAz6

**Comment by lianilychee** [comment]
Tues 6/8:
- Liani to noodle more on how to solicit approval about CTA destinations
- Amy to schedule with Jeff and Megan
