### ISSUE TITLE
Add request for static content page to Staging Review template and touchpoint documents

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25245]
## Issue Description
Platform team would like to review the full user flow at Staging Review. Teams building tools and applications typically have entry points to these applications on Static content pages. This work is completed by Sitewide Content team. We need to update our Staging Review template to request the VFS team to include a link to the Sitewide Content team ticket for creating and/or updating the relevant static content page.

---
## Tasks
- [x] Modify the Staging Review template to ask for the static content page ticket with Sitewide Content.
- [x] Modify the Staging Touchpoint document to ask for the static content page ticket with Sitewide Content.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
Hi, @shiragoodman Updated has been validated in Staging Review template and touchpoint doc.
