### ISSUE TITLE
Conduct training sessions (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#25252]
# User story

As a Content team member, I need to deliver guidance to Platform teams, so that they can contribute to the Platform Website with minimal assistance from us.

As a Platform team member, I need to know how to create and deprecate a page on the Platform Website, so that I can contribute to it (the Platform Website).

# Tasks

- [x] Prepare for rehearsals with Naomi and Dror.
- [x] Conduct rehearsal with Naomi and Dror.
- [x] Conduct training session with PMs (don't forget to record).
- [ ] Upload recording ~with closed captions to YouTube.~ destination TBD

# Acceptance criteria
- Guidance has been socialized amongst Platform team members, who either attended the live session or have the option to listen to the recording.

# Reference info
- [Contributing to the Platform website guidance](https://docs.google.com/presentation/d/1u5ur2ArnaVAG1SZwggWSAQHVfamr1szeMuMobyiaIts/edit#slide=id.gd9205116fb_0_998)
- Guidelines
  - [Overview](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+Website+Guidelines)
  - [Create a page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+page)
  - [Organization](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization)
  - [Publishing workflow](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579803/Publishing%2Bworkflow)

**Comment by lianilychee** [comment]
5/27 Thurs:
- let's focus this afternoon on parts we haven't done yet (overview, deprecate, wrap-up).  then if we have time we can do a full run thru tmr before we meet with Naomi and Dror

**Comment by lianilychee** [comment]
blocked -- pending Rachael/Nancy to tell us where we can upload the training video (Rachael is asking Nancy about the possibility of having a Platform YT acct)

related: https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/platform/product-management/demo-video-creation-process.md
