### ISSUE TITLE
[CONSIDER] Search on VAMC page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25256]
## Issue Description
Clarence reported an enhancement request from VAMC open hours on 5/25 -> The search functionality in the header of every page is expected to be localized to the facility/VAMC that they're on rather than VA wide search. 

![image](https://user-images.githubusercontent.com/55411834/119558467-aa7fa680-bd5e-11eb-9f73-d3987d6ecdc2.png)

---
## Tasks
- [ ] Consider "Search" experience in context of VAMC pages

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
Conversation with Lovell editors resurfaced this enhancement request. In addition to the existing need/expectation for search to be limited to a VAMC, Lovell finds it more urgent because of their TRICARE audience.
