### ISSUE TITLE
Update Product Guide Best Practices

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#25263]
## Issue Description
_As we have added more products and strengthened our relationship with contact centers, we have learned of some needed improvements to product guide. This story will put those new requirements in one place by updating our existing best practices doc and merchandising that to VFS teams._

---
## Tasks
- [x] _Update [this](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) product guide best practices doc with the new requirements listed below_
- [x] _Publish and share updated product guide with all necessary teams, including product support and all VFS teams_

## Acceptance Criteria
- [x] _Product Guide Best Practices doc is updated with the following new requirements:_
* Clickable table of contents
* Table of figures and appropriate references when figures are used
* Title page required
* Consistent use of headers/sub-headers
- [x] _General format and document standards have been applied_
- [x] _New best practices have been published_
- [x] _All necessary teams have been notified of new best practices_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Document updated, shared with @jwoodman5 for review.

**Comment by jwoodman5** [comment]
I shared with Product Support Team lead, Shira Goodman, for feedback on appropriate communication path to publish this out to VFS PMs.

**Comment by jwoodman5** [comment]
Doc looks good and has been shared on #vfs-all-teams on slack as well as in the collaboration cycle change log. I will also share during Team of Teams on 6/8/21.

**Comment by jwoodman5** [comment]
Link to output in details. Closing.
