### ISSUE TITLE
Adjust Note for Off-Ramped Applications

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25273]
## Background
In testing it was found that a note needs to be added to VBMS for various workflows that RBPS is not able to address.  These need to be addressed so that VSR's can better understand how an application needs to be processed as quickly as possible.

## Considerations
- For the service that will need to be called, do we need an ESCP (or SR?) for that?  BGS gem update ticket?
- Each workflow and the corresponding message:  

 **a. 674 (adding, existing, and removal-stopped attending)**
    - _"This application needs manual review because a 674 was submitted to add a new child not previously documented by VA"_
    - _"This application needs manual review because a 674 was submitted to add a child that is already on award."_
    - _"This application needs manual review because a 674 was submitted for removal of a child."_

 **b. Marriages other than ceremonial (tribal, proxy, common law, other)**
    - _"This application needs manual review because a 686 was submitted to add a spouse due to civic/non-ceremonial marriage"_

 **c. Death of a dependent (child or parent)**
    - _"This application needs manual review because a 686 was submitted for removal of a child/dependent parent due to death._"

  **d. Step-child has left the household**
    - _"This application needs manual review because a 686 was submitted for removal of a step-child that has left household."_

  **e. Marriage of a child under 18**
    - _"This application needs manual review because a 686 was submitted for removal of a married minor child."_

``` diff
+ ✔ UPDATED with John Brandt's approved language on 6/16 at 3:30 pm ET
```
## Tasks
- [x] Call a service to allow for the inclusion of a rejection reason
- [x] Include a rejection reason to the "Note" section in VBMS
- [ ] Test (Stretch)

## Acceptance Criteria
- [x] The rejection reason is included in the Notes section of the application as viewed in VBMS
- [ ] A PR has been requested for merging, if needed

**Comment by kathleencrawford** [comment]
Note: I think the wording for removing a school-age child who stopped attending school is incorrect.  According to this wording, we should say that a 674 was submitted, but a 686 is submitted when reporting that a child has stopped attending school.

**Comment by kathleencrawford** [comment]
Also, please note that Linda suggested we mention "VA.gov" somewhere in the notes, so I've added "Claim rejected by VA.gov: " to the beginning of each of the messages.

For example: `Claim rejected by VA.gov: This application needs manual review because a 686 was submitted for removal of a married minor child.`

**Comment by kathleencrawford** [comment]
One more modification, for the 674.  We currently have these listed:
"This application needs manual review because a 674 was submitted to add a new child not previously documented by VA"
"This application needs manual review because a 674 was submitted to add a child that is already on award."

However, at this time, we are setting all 674 submissions to MANUAL_VAGOV until we fix the proc id issue.  We won't know whether we are adding an already existing child or a child previously on award, so I suggest combining these two messages for now.

**Comment by kathleencrawford** [comment]
Draft PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/7301

Please note that there have been some modifications to specific notes, see comments above.

Once we have access to the createNote service, we will need to comment out some parts of this PR and make sure the tests work before submitting.

**Comment by jason-gcio** [comment]
Submitting ITRP soon

**Comment by jason-gcio** [comment]
https://vajira.max.gov/servicedesk/customer/portal/12/CMDMRP-988

**Comment by jason-gcio** [comment]
This service should be available now
