### ISSUE TITLE
Update Existing Product Guides with Clickable Table of Contents

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#25276]
## Issue Description
_During a meeting with VEO they expressed how valuable a clickable table of contents in all product guides would be for their agents, saving them time from scrolling through each page to get to the section they need to provide proper help to Veterans. This efforts aims to add a clickable table of contents to all existing product guides still in use._

---
## Tasks
- [x ] _Access existing product guides in sharepoint (VEO)_
- [x ] _Add links to appropriate sections for all items in the table of contents_
- [x] _If a table of contents does not exist, create one. Work with product guide creator if necessary_

## Acceptance Criteria
- [x] _All existing product guides have a clickable table of contents_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
All full product guides available in VEO CC's Sharepoint folder (Training Files>KM Docs>VA.GOV) are complete with clickable TOC.
