### ISSUE TITLE
NOD: Miscellaneous fixes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25285]
## Description

The Notice of Disagreement form has a few minor issues that need to be fixed

- Fix validation of issues
- Show all selected issues on the confirmation page
- Content updates

## Tasks

- [ ] Fix validation problem
- [ ] Show all selected issues on confirmation page
- [ ] Content updates

## Definition of done

- [ ] Tasks completed
- [ ] Unit tests passing
