### ISSUE TITLE
TUD - API Route Authentication

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#25292]
## Issue Description
The TUD frontend application is hidden behind SOCKs proxy and is implementing basic authentication to limit access to test user account information. The test user account information is stored and accessed through the TUD module inside of `vets-api`, and the endpoint to query for test users is not currently protected. Authentication should be added to the API route (as well as any future TUD API routes) so that only requests coming from the TUD frontend application are accepted. 

---
## Tasks
- [ ] API route authentication is added to the TUD vets-api endpoint, requiring a JWT containing a public key
- [ ] the TUD frontend request to vets-api is modified to pass along a JWT with a public key
- [ ] relevant keys are added to the TUD frontend environment
- [ ] relevant keys are added to the vets-api environment

## Acceptance Criteria
- [ ] The TUD app will be able to request test user information from vets-api
- [ ] A direct query of vets-api will result in a 403 error
- [ ] API authentication works for local builds of both TUD and vets-api
---

**Comment by bramleyjl** [comment]
Specifications for TUD API authentication have been worked out in Sprint 53, the authentication work is planned for Sprint 54.

**Comment by nsoutouras** [comment]
Transitioned to TTT
