### ISSUE TITLE
[BE] Google Analytics Dashboard

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25297]
# Description
Create a GA Dashboard to display metrics for the Clipboard application 

Initial implementation is here: https://analytics.google.com/analytics/web/?authuser=0#/dashboard/00wXuGrzTU2R79u5T9gP_w/a50123418w177519031p184624291/

# Tasks
- [x] Capture page views over time and geographic location
- [x] Capture submission success and failure
- [x] Capture PDF generation success and failure 
- [x] Capture save in progress data
- [ ] Capture authentication drop off data

# Acceptance Criteria
- [ ] Page views over time and geographic location are tracked
- [ ] Form submission outcome is tracked
- [ ] PDF generation is tracked
- [ ] Save in progress activity is tracked
- [ ] Authentication drop off is tracked

**Comment by stephenBarrs** [comment]
Authentication drop off requires work by the analytics team tracked [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25278) and in [this thread](https://dsva.slack.com/archives/C1Q4294JJ/p1621975042031000)
