### ISSUE TITLE
Draft team SLAs for adding analytics to new DS components

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25298]
## Issue Description
As new Design System components get added, we want to add analytics tracking to those components. Make our own team guidelines so that we understand how to add analytics to new design system components as those come out.

---
## Tasks
- [ ] Draft team workflow in Confluence
- [ ] Tag @laurensimpson14  for QA
- [ ] Component Library: add to the component library or inform the DS team that they will need to update the library

## Acceptance Criteria
- [ ] Platform Analytics understands how to add analytics to new DS components as an ongoing service.

**Comment by joanneesteban** [comment]
@bsmartin-ep documented team [SLAs here](https://vfs.atlassian.net/wiki/spaces/AT/pages/1572700285/WIP+-+Design+System+Components+SLA) in Confluence. And the team's[ project workflow is here](https://vfs.atlassian.net/wiki/spaces/AT/pages/1576042497/WIP+-+Design+System+Components+-+Team+Workflow). Closing this ticket.
