### ISSUE TITLE
[FE] Production Checklist To Dos

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25296]
# Production To Do Tasks

## Related docs
- [Full List ](https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/health-care/questionnaire/engineering/production-release/Readiness.md)

## vets-website app checklist

- [x] Enable the feature toggle in the production environment 
- [x] Check VA.gov internal search result
- [x] Check new form release criteria 
- [x] Make sure route is not organically discoverable (no-index / robots.txt etc..)

## Ops checklist

- [ ] Determine who needs to be notified by PagerDuty and configure as such

**Comment by mdewey** [comment]
Search team conversation : https://dsva.slack.com/archives/C011K1VSTC3/p1618597437192100

**Comment by mdewey** [comment]
robots.txt conversation : https://dsva.slack.com/archives/CBU0KDSB1/p1622058638113700

**Comment by mdewey** [comment]
robots PR: https://github.com/department-of-veterans-affairs/content-build/compare/health-care-questionnaire-disallow-robots?expand=1

**Comment by mdewey** [comment]
Toggle Conversation : https://dsva.slack.com/archives/C0136TS768M/p1622057483066300

**Comment by mdewey** [comment]
Page duty questions: https://dsva.slack.com/archives/CBU0KDSB1/p1622128506175100

**Comment by mdewey** [comment]
Trying to get Dillo added to Pager duty, but there are not enough licenses. Added Stephen to our team

**Comment by mdewey** [comment]
Blocked till:

- We enable in prod
- figure out pager duty for Dillo

**Comment by jparker0425** [comment]
@mdewey Are the 2 blockers on this issue still relevant? I reviewed the Slack thread and looks like the last thing stated was there had to be a ticket created for seats for Pager Duty?

**Comment by mdewey** [comment]
The app is enabled, so that is no longer a blocker and I am fine with either making a new ticket to get Dillo into PagerDuty or having this one sit in the blockers. I personally think a new ticket just to track that would be better, but I will leave that decision to you.

**Comment by jparker0425** [comment]
@mdewey closing this one and making a separate ticket for the backlog to get @dillo added to PageDuty.
