### ISSUE TITLE
[BE] Production Checklist To Dos

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25295]
## vets-api app checklist
- [x] Check hqva_mobile configuration settings in the production Settings and DevOps YAML files and make sure all the values for the keys are production values
- [x] Check that the production public/private key for Lighthouse has been installed in Credstash- Ops
- [x] Check that monitoring and error reporting are in place in production

## Database and datastore checklist
- [x] Check that the production PostgreSQL DB has all the necessary tables and columns for the HealthQuest Engine.

## Lighthouse checklist
- [x] Ensure that Lighthouse has installed the public key that was generated by the vets-api team in their system 
- [x] Create production questionnaire in PGD

## Facilities API checklist
- [x] Ensure that HealthQuest in production has permission to call the Facilities API in production 
- [x] Check if we need any credentials or extra configuration settings for the production release

## Ops checklist
- [x] Set up project in Sentry (if not done already)
