### ISSUE TITLE
[PM] My VA: Coordinate with comms team on My VA blog post

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25305]
## Background
After meeting with Leslie from the comms team at the end of May we determined that a blog post would be super helpful for My VA 2.0 exposure post-launch. We're looking at a mid-July timeline for the post and any other comms-related posts or announcements, but we'll use this ticket to track any prep needed for that.

## Tasks
- [x] Send Leslie background and other requested info about My VA 2.0
     - [x] Backstory - why did we do this work?
     - [x] What are the new features and/or functionality available to veterans
     - [x] User feedback and anecdotes from research and testing
     - [x] Analytics 
- [x] Check in with Leslie third week of June (~June 14th)

**Comment by Samara-Strauss** [comment]
Here are some notes we can send over to Leslie:

## Backstory

- The original My VA dashboard launched in 2018.
- We made some initial updates to it, but otherwise, it largely has gone untouched for the last three years.
- In that time, we were getting an increasing amount of internal requests to add information to the dashboard, and it was also clear through usability testing with Veterans that the page wasn't meeting their needs. This largely came down to some of the design decisions that were made as part of the MVP, which left us with a clunky format that was hard to scale.
- Given Veterans' expectations that they see a personalized view of their information when they log in to VA.gov, and given the design constraints of the old My VA dashboard that made it hard to scan and scale, we decided it was time to overhaul this page.
- Our main goal for the the My VA dashboard redesign was to create a scannable, scalable space where Veterans could easily see the status of their VA benefits and manage their benefits accordingly. 

## What are the new features and/or functionality available to veterans

### Features and functionality moving over from version 1.0

- Claim status
- Health care enrollment status
- Applications in progress

### New features

We show the following information which was not available in version 1.0 of the My VA dashboard:

- Disability rating
- A Veteran's next health care appointment
- Your unread messages from your doctor

## User feedback

These are from some [usability testing we did back in March 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-research-findings.md):

> "I like it. I have a similar one for work because I work in finance so it can pinpoint what needs actions, pending or in progress, so it is a one stop shop."

> "I think it covers any questions or guide the veteran where to go if they have any questions. I don’t think they could leave this without finding an answer."

> "Oh, my disability rating is just right up top - I love that!"

> "Make you aware of the next appointment so you don’t miss it. That’s the most important thing is the next one so you do not forget and it is a reminder. It is good they put it there."

## Analytics

These are TBD since we don't have any post-launch analytics yet.

**Comment by Samara-Strauss** [comment]
Emailed over to Leslie today. We can leave this open for now since (1) we should wait to hear back to see if she has what she needs and (2) because we won't be able to send over analytics until after launch.
