### ISSUE TITLE
Phase 2: Integrate Nightwatch E2E and Cypress E2E Execution into the Same GHA Workflow

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25311]
# Description
Since the Nightwatch E2E test execution workflow and Cypress E2E test execution workflow were developed independently they are not currently configured to operate in parallel. We need to incorporate the configuration created in the [Migrate Nightwatch E2E tests to GitHub Actions PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17284) nightwatch.yml into the `E2E Tests` workflow developed for Cypress.

## Tasks
- [x] Integrate the workflow described in [nightwatch.yml](https://github.com/department-of-veterans-affairs/vets-website/pull/17284/files#diff-e5b386da8f8e0cc001a32c68ba5bf5325506837881b1f478b3b82b8c4d83bc2d) into the general E2E Tests workflow described in [cypress.yml](https://github.com/department-of-veterans-affairs/vets-website/blob/circleci-to-gha/.github/workflows/cypress.yml).

## Acceptance Criteria
- [x] Nightwatch E2E and Cypress E2E test suites execute in parallel
- [ ] If either the Nightwatch E2E test suite or the Cypress E2E test suite fail then the workflow reports a failure and correctly indicates which suite the failure occurred in.

**Comment by pjhill** [comment]
The two test suites are integrated into a single flow.
