### ISSUE TITLE
Midpoint Review [Authenticated Experience, Notification Preferences]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25313]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- [Communications Permissions (Notification Preferences) Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
- [Prototype](https://preview.uxpin.com/5ecec4de6ec34eddc9f095677a881be3646124ce#/pages/139049744/simulate/sitemap?mode=i) and [static mock-up](https://preview.uxpin.com/bb87d0fa61a32938a47e7bcdc836db235ab77576#/pages/139109897?mode=i)
- [Research Plan for Authenticated Experience, Notification Settings, June 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/notifications-research-plan.md) and [Conversation Guide for Profile, Notification Settings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/notifications-conversation-guide.md)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- [Test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md) (draft)

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [X] No
 
What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **Tuesday June 8, 11:00 am**
 

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): @ajakabcin 
- OCTO-DE Product lead (recommended): @Samara-Strauss 
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): @andaleliz , @erikphansen 
- VFS Content, IA, accessibility, and QA specialists (if applicable): @DanielleThierryUSDSVA, @mnorthuis , @joshkimux , @AngelaFowler82 , @tlei123 

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
thanks @ajakabcin ! Review scheduled for 6/8 at 11am ET

**Comment by shiragoodman** [comment]
rescheduled to 6/4 at 2:00pm ET

**Comment by peggygannon** [comment]
@andaleliz @ajakabcin Hello! Is there a content brief from the sitewide content team for this work?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @peggygannon. I can answer content brief question. There isn't a content brief for this. But I worked with Liz on some of the content/content strategy. If you think it would helpful, I'd be happy to jump on a call. Thanks!

**Comment by peggygannon** [comment]
Hi, @DanielleSoCompany thanks for the update. No need to have a call. I just wanted to check if there was a brief before I take a look at the prototype.

**Comment by shiragoodman** [comment]
@joshkimux @AngelaFowler82 @noahgelman - Is there an accessibility feedback that can be linked to this ticket? Please let me know.

**Comment by AngelaFowler82** [comment]
Nothing on my end which hasn’t already been discussed. Let me know when you’re ready for screen reader testing.

**Comment by ajakabcin** [comment]
Closing this as all feedback has been addressed in sub-issues. Thank you!
