### ISSUE TITLE
Midpoint Review [Authenticated Experience, Preferred Facilities]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25318]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- [Preferred medical facilities in the VA.gov profile: Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/preferred-facility#preferred-medical-facilities-in-the-vagov-profile-product-outline)
- Prototype link: [Scenario 1, Task 2](https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669680) 
    - Note: this is a joint initiative with VAOS. The scope of the Authenticated Experience team's work is specifically focused on preferred facilities within profile. For additional context on the broader initiative, see full prototype links which can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23259#issuecomment-844472243)
- [Facilities personalization research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/research-plan.md) and [Conversation Guide - Facilities personalization](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/conversation-guide.md)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- [Preferred Medical Facility Test/Use Cases & Users ("Your VA health facilities")](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-preferred-medical-facility.md#preferred-medical-facility-testuse-cases--users-your-va-health-facilities) (Draft)

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [X] No
 
What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **~Thursday, June 10, 1:30 PM~  Friday, June 4, 2 PM**

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): @ajakabcin 
- OCTO-DE Product lead (recommended): @Samara-Strauss 
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): @andaleliz, @erikphansen , @outerpress , @laurenernest 
- VFS Content, IA, accessibility, and QA specialists (if applicable): @DanielleThierryUSDSVA, @mnorthuis , @joshkimux , @AngelaFowler82 , @tlei123 

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by ajakabcin** [comment]
Closing this out - thank you platform team for all your feedback! We'll move #25642 and #25514 over to our backlog to address down the line. Thanks again!
