### ISSUE TITLE
Redesign Search & Content Dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25324]
## Issue Description
Analytics worked with the Service Design team to receive feedback on the initial Search & Content KPI Dashboard mock ups. We'll need to take the prioritized recommendations to redesign these mockups to start building the dashboards in Domo.

---
## Tasks
- [ ] Redesign Search KPI Dashboards
- [ ] Redesign Content KPI dashboards
- [ ] Team reviews Search KPI Dashboards
- [ ] Team reviews Content KPI Dashboards

## Acceptance Criteria
- [ ] The Dashboard mockups are designed with user feedback so that they are most usable and useful for PMs and POs

**Comment by joanneesteban** [comment]
@chloedotbrown recorded the edits & @naomimarcussen helped us make the edits in Sketch on 06-08-2021 . Documentation can be found [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/1572765842/Search%2Band%2BContent%2BKPI%2BDashboard%2BComps). Thanks everyone! Closing this ticket.
