### ISSUE TITLE
Create VFS-facing documentation for standardized KPI Dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25323]
## Issue Description
As we release the new standardized KPI dashboards, VFS teams will need scalable guidance on new processes and how to use the dashboards.

---
## Tasks
- [x] Chloe: Create a `How to use this dashboard` document for the Forms KPI Dashboards
- [x] QA `How to use this dashboard`
- [x] Joanne: Update the KPI Dashboard request template
- [x] QA the KPI dashboard request template
- [x] Joanne: Copy the Funnels Google Sheets template to Excel
- [x] Joanne: Update the KPI Dashboard read.me
- [ ] _Stretch_: create mini how-tos for marketing the dashboard releases
- [ ] _Stretch_: update the Analytics Playbook with the new Framework & Dashboard work & migrate to Confluence

## Acceptance Criteria
- [ ] VFS teams will be able to clearly understand the new KPI Dashboard request process and how to use the dashboards with minimal in person guidance from the Analytics team.

**Comment by chloedotbrown** [comment]
@laurensimpson14 - I've put together a [first draft](https://vfs.atlassian.net/l/c/nUf7243k) of this in Confluence! Would love your thoughts/edits on whether this makes sense, is covering the right topics, and feels like the correct level of detail for our users. Some of the questions I've flagged in comments may be for Jason once he's back, but lmk if you have thoughts there too. I'll do another pass later in the week to polish up and add screen recording GIFs.

Also cc'ing @joanneesteban – but do we want to create a separate how-to for each standardized dashboard that includes KPI explainer tables? Or one how-to that serves all three dashboards, but that links to separate data dictionaries for each at the end? This draft has everything in one doc for now, but I could honestly see good arguments for either.

**Comment by joanneesteban** [comment]
@chloedotbrown As in expanding on what you already have in the How-To vs. adding to the [KPI Framework](https://vfs.atlassian.net/wiki/spaces/~173922865/pages/614531245/VA.gov+Analytics+-+KPI+Framework)? Hm, Mandy had also created [a design](https://docs.google.com/document/d/1_dlEG53GfCuhuwozdityGIP8xyJny2mffmePF4Fg2cI/edit) to readjust the framework to be easier to read than a giant table in Confluence. 

Let's start out by keeping what you have, and we can informally shop the user flow around.

**Comment by joanneesteban** [comment]
@chloedotbrown The [Content & IA team can chat with us](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25477) later this week or next about where might be best to put it!

**Comment by laurensimpson14** [comment]
@chloedotbrown I've gone through your draft - you were thorough! Way to go on that document! I've added in my comments, feel free to take them or leave them, but it at least gives you some perspective from someone who has limited Domo experience.

**Comment by chloedotbrown** [comment]
Thanks to you both! @laurensimpson14 appreciated your thoughtful comments and made most of the changes you suggested. @joanneesteban responded to this in Confluence too, but I agree – the data dictionary is better placed either on its own or one of our other docs to keep this one as sleek/multi-functional as possible. 

I'll add screenshots/GIFs to this before the end of the sprint.

**Comment by joanneesteban** [comment]
Revised KPI Dashboard request template below & funnels Excel template attached.
[Standard KPI Dashboard Funnels Template.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6594552/Standard.KPI.Dashboard.Funnels.Template.xlsx)

@laurensimpson14 @chloedotbrown Whenever you get a chance, please feel free to leave feedback on this ticket's comments! Many of the GH doc links will need to be updated, so they're either broken or non-existent lol. I'm going to deprecate the How to Request a KPI Dashboard Document in favor of creating new customer support guidelines after our workshops next week.

---
# Request a Standard KPI Dashboard

## What this form is for

Use this template to request a Standard KPI dashboard ([example](example-URL)) on Domo for your product.

Re: Custom KPI dashboards: (ADD ACCORDION IN THE .MD)

- Every VFS team should be using the Standard KPI dashboards. If your product *does not* have a Standard KPI Dashboard, please fill this out this template for a Standard KPI dashboard first.
- If your team *does* have a Standard KPI dashboard, and you're looking for additional data, please fill out [this template](potential custom-kpi-dashboard template URL). Please note that *Custom* requests add more complexity, and will take longer for the Platform Analytics & Insights to complete.

Additional Info (ADD ACCORDION IN THE .MD)

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 

- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md).

### Expected delivery timelines

Your Standard KPI dashboard request will be added to the Platform Analytics & Insights team's customer support queue, and we expect tickets at the top of the queue to be pulled in every Platform Sprint Planning & Refinement (every Wednesday). We appreciate your patience.

- Once your ticket has been pulled into the Platform sprint, we expect to deliver your completed dashboard within the next 4 business days.

## Instructions for the VFS team

- [ ] **Please fill out [this template](template-tbd) ([attached Excel sheet](link to Slack w/attachment) if you do not have Google access) & link it below to help define your product/feature's funnels.** The Analytics team will *not* be able to pull this ticket into the queue until this is provided & linked.
- [ ] Link your Product Outline below
- [ ] Add your team label to follow progress

## VFS-provided information

[Funnel Information](Add your product/feature's funnel information here) - Add your product/feature's funnel information here

[Team KPIs](add your team's KPIs here) - Add your team's product outline here

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Build (See [internal process document](https://vfs.atlassian.net/wiki/spaces/AT/pages/1464598569/New+KPI+Dashboard+Request+Process) & [how to](https://vfs.atlassian.net/wiki/spaces/AT/pages/1538294010/WIP%2B-%2BHow%2Bto%2Bcreate%2Bstandardized%2Bdashboards%2Bin%2BDomo))

- [ ] Create templated dashboard
- [ ] Add the `VSP Analytics & Insights` Group as the dashboard owner
- [ ] Structure funnel data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Document any blocked/unavailable metrics
- [ ] Update the dashboard header, including Google Analytics links
- [ ] If any, add [implementation issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) for additional necessary implementation

2. Q&A

- [ ] Please see & complete the [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

3. Share

- [ ] Add VFS group & default group to the dashboard

  *For new VFS customers only:* 

- [ ] Schedule onboarding meeting

- [ ] Host the meeting to explain how the dashboard works

## Definition of Done

- [ ] Accepted Criteria has been completed
  - [ ] KPI Dashboard full QA checklist completed
- [ ] Dashboard has been shared back with the VFS team

**Comment by joanneesteban** [comment]
@jennaouellet to support data dictionary QA.

**Comment by joanneesteban** [comment]
## How To Additions

**1. No data in filter**
- [ ] Add a section to the How to use this dashboard guide on the charts not showing up if there's no data in a given time range. Slack conversation located [here](https://adhoc.slack.com/archives/C01EUNU6W1Z/p1625675788033800).

**Comment by chloedotbrown** [comment]
Added new "no data filter" call-out in the info box in [Using Filters](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html#HowtouseVA.govKPIdashboards-Usingfilters) section. Pushed updates, closing out ticket.
