### ISSUE TITLE
[UNPLANNED] Pause VR&E CMS Application Submissions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25334]
## Background
The VR&E pilot is being paused and needs to stop data from being sent to the CMS for an unknown period of time.

## Considerations
- Every other process and function in place should remain.
- The line of business requested this to be completed ASAP.

## Tasks
- [x] Probably in this file but there should be no RO's that receive structured data from us until they ask us to turn it back on.

## Acceptance Criteria
- [x] No RO's are receiving data unless requested
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/veteran_readiness_employment_claim.rb#L9
