### ISSUE TITLE
Reinsert Videos into CH31 Orientation

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25333]
## Background
The VR&E line of business has redone their videos and are ready to have them placed back into the Orientation content slides.

## Considerations
Reemployment Track - https://www.youtube.com/watch?v=SkRD2CDHB_E
Rapid Access - https://www.youtube.com/watch?v=VkmTgQftRlk
Self-Employment - https://www.youtube.com/watch?v=IYqVu3Q1Wow
Employment Through Long-Term Services Track - https://www.youtube.com/watch?v=32oPJaWpUhI
Independent Living Track - https://www.youtube.com/watch?v=_Yd0aW_NZvA

## Tasks
- [ ] Insert the latest YouTube videos

## Acceptance Criteria
- [ ] Latest videos are reinserted
- [ ] A PR has been requested for merging
