### ISSUE TITLE
VFS Support Reporting MVP in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#25342]
## Issue Description
_In order to provide support reporting to VFS and other teams so they can understand issues being initiated about their products, we want to create a dashboard within DOMO for ease of access to support data and future automation.._

---
## Tasks
- [x] _Manually import VEO contact center/Salesforce data for at least 4 weeks into DOMO_
- [x] _Use the imported data to create basic visualizations within a single DOMO dashboard_
- [x] _Where/how possible, create "cards"/individual charts to reflect categorical support volume with the ability to drill into specific issue categories_

## Acceptance Criteria
- [x] _A dashboard utilizing VEO contact center support data is created_
- [x] _The dashboard displays a count of all tier 1 and 2 support issues initiated through the VEO contact center_
- [x] _The dashboard provides the ability to segment by category so teams can view the data for their products (category) specifically._
- [x] MVP dashboard is released to at least 3 VFS product managers for piloting_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Data Viz Tips for DOMO](https://vfs.atlassian.net/wiki/spaces/AT/pages/1408762356/Data+Viz+Design+Tips+for+Domo)

**Comment by ianMcCullough-ob** [comment]
@starlow00 or @edpearson20 [here's what I have so far on the DOMO dashboard](https://va-gov.domo.com/page/130739792).

Anywhere you see text can be changed. If there are other spots you think definitions or clarification can be added, let me know.

**Comment by ianMcCullough-ob** [comment]
[Here is a GitHub documen](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/reporting-resources/salesforce-domo-resources.md)t with links to resources and steps on how to update a dataset

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 can we close this ticket?

**Comment by jwoodman5** [comment]
Didn't see this one. Yes, closing.
