### ISSUE TITLE
[Research] Notification Preferences: Submit research plan + kick off recruiting

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25366]
## Background
We have some prep work that needs to be done in order to conduct usability testing for the notification preferences feature. 

## Tasks
- [x] Submit research plan to Lauren Alexanderson for review and feedback
- [ ] Incorporate any feedback from Lauren into research plan
- [ ] Monitor recruiting progress
- [ ] Recruit notetakers

**Comment by andaleliz** [comment]
[Pinged Lauren on Slack today.](https://dsva.slack.com/archives/C909ZG2BB/p1623077047197000)
