### ISSUE TITLE
Move vaccine CTA to type of care

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25375]
## Description
As Product, I would like to move the start of the vaccine scheduling flow to the type of care page so that it's treated like any other care type.

---
## Tasks
- [ ] Homepage

- [ ] Type of Care page

- [ ] Plan Ahead page (first page of vaccine flow)

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag

- [ ] On the homepage, a user is not required to select a care type to start scheduling

- [ ] DESIGN - Homepage designs match the specs (copy is FPO) 

- [ ] If user clicks Start Scheduling button, then display Type of Care page

- [ ] Option to select vaccine displays on Type of Care page

- [ ] Option copy is:

> COVID-19 vaccine

- [ ] If user selects Vaccine - COVID-19 from type of care page, then start vaccine scheduling flow

- [ ] On Plan Ahead page, if user clicks Back, Then display Type of Care page

- [ ] Changes appear when the `va_online_homepage_refresh` feature flag is ON
- [ ] Changes appear when the `va_online_homepage_refresh` feature flag is OFF

## Design specs

- [Workflow](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/jgPbqgm)
- [Home page overview](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/jgPbp2G)
    - [Mobile](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/QbxkMYe)
    - Tablet
    - Desktop
- [TOC overview](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/ELjlYLd)
    - Note that the "NEW" label is not a part of this ticket
- COVID-19 start page
    - [Mobile](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/ELjlJmo)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Cheetah flow [documentation and screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) are updated

- [ ] Type of care page screenshot is updated in the [other flows](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design)
