### ISSUE TITLE
Update vaccine dead end with walk-in info

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25388]
## Description
All VAMCs now allow walk-ins for the COVID-19 vaccine. We should update messaging to dead ends in the vaccine scheduling flow to direct users to walk-in instead of calling the VA.

![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f9d4b98a-e96d-4713-b24c-8dfcdb4e60f7)

---
## Tasks
- [ ] Contact a Facility page

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag

- [ ] "Search for more facilities" link does not appear

- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/contact-facility.md) 

- [ ] "Find VA facilities..." is a link

- [ ] If user clicks "Find VA facilities..." link, Then open `/find-locations/?facilityType=health&serviceType=Covid19Vaccine` in the same window

- [ ] DESIGN - Designs match the specs (copy is FPO) 
- [Mobile](https://www.sketch.com/s/2d26a3f6-095d-4c26-869f-a41b6caca1f5/a/52YrxmL#Inspector)

- [ ] DESIGN - Blue box uses the [featured content component](https://design.va.gov/components/featured-content) from the design system

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation and screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design/cheetah-flow) are updated
