### ISSUE TITLE
Update vaccine flow URLs

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25380]
## Description
Per VSP IA feedback, update vaccine flow URLs for sustainment.

---
## Tasks
Page | URL | Notes | Old URL
-- | -- | -- | --
New   covid appt | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment | Content uses the word "appointment", not "booking".  | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking
New   covid appt - contact facility | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-facility | More accurate description of step - user will contact a single facility, not multiple | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/contact-facilities
New   covid appt - dose history | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/confirm-doses-received | current URL (/received-dose) is a statement rather than a request for action or input | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/received-dose
New   covid appt - Choose facility | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-facility | clear description of step in process | health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/facility
New   covid appt - Choose clinic | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-clinic | clear description of step in process | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/clinic
New   covid appt - Select date | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/select-date |  | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/select-date-1
New   covid appt - Second dose  info | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/second-dose-info | More accurate description of step - step is providing info, not planning the next dose | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/plan-second-dose
New   covid appt - Contact info | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-info | |/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/contact-info
New   covid appt - Review | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/review | | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/review
New   covid appt - Confirmation | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/confirmation | | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/confirmation

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag

- [ ] All vaccine flow page URLs match IA guidance

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by laurenernest** [comment]
@laurenernest Check any inbound traffic in GA

**Comment by laurenernest** [comment]
There's some odd prior pages before entering a vaccine page path that I have to dive into more. For now, we will [maintain a redirect](https://github.com/department-of-veterans-affairs/vets-website/pull/17521#discussion_r647647335) but send to the type of care page to align with the other flows.
