### ISSUE TITLE
Determine COE interaction with Claim Status Tool

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25386]
### Background
When a user completes form 26-1880 for a COE, the submission goes into a pending state. We need to determine what info is displayed to the user in the Claim Status Tool on VA.gov. Additionally, we need to determine the data sources for the info displayed.

### Tasks
- [x] Reach out to designers and developers 
- [ ] Determine the functionality of the CST (e.g. Upload)
- [ ] Define what info can be displayed to the user
- [ ] Map out data sources for displayed info

### Acceptance criteria
- [x] Document findings
- [ ] Stretch: mock up CST screens with COE data

**Comment by sporeboy** [comment]
Discussed CST and Letters features with dev and design. Neither feature is in active development. EVSS and Caseflow were mentioned as sources for the Claim Status Tool data. Discussion here: https://dsva.slack.com/archives/CLY6Q69RV/p1623419381068000
