### ISSUE TITLE
Edit Toggl Domo Page

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25396]
## Issue Description
As we standardize our GTM work and take on additional tech debt, the Platform Analytics team needs to know if these efforts reduce the time it takes for us to do customer support for VFS teams. Particularly if this work reduces the time it takes to implement & QA GTM.

We also need to make sure that the time it takes to track this metric does not heavily increase the workload for our team.

---
## Tasks
- [x] Reduce Toggl labels to only a few tags: 
1. GTM (this includes requirements gathering, implementation, meetings, and QA)
2. Reporting (this includes creating/editing reports in Domo & Google Analytics)
3. Misc (everything else)
- [ ] Edit the Toggl dashboard in Domo
  - [ ] A month over month nested bar chart with the avg. time it takes to complete the above tasks/labels

## Acceptance Criteria
- [ ] We can automatically track the average time it takes to complete GTM support work, and see if that time increases, stays the same, or reduces based off the initiatives and tech debt we do.

**Comment by joanneesteban** [comment]
@laurensimpson14 @bsmartin-ep do y'all know what's going on with the [Toggl](https://va-gov.domo.com/page/653316187) data connector?

**Comment by bsmartin-ep** [comment]
@joanneesteban - Looks like the API key expired when they removed Jon's account.  I added one from my account and backfilled.  Looking good now.

**Comment by joanneesteban** [comment]
Great! Thank you! The bar chart there is also what we'll need for GTM standardization KR tracking, so that's great. Closing this issue.
