### ISSUE TITLE
[Research] Staff-facing Research Observer/Notetaker

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25419]
# Description
Assist as observer/notetaker for staff-facing remote check-in research sessions.

# Tasks
- [x] Meet with Julia Snyder to prep
- [x] Attend session(s) and take notes

# Acceptance Criteria
- [x] Send final notes to Julia

**Comment by kristenmcconnell** [comment]
Attended sessions on:
June 8, 4 - 5 p.m. 
June 10, 11 - Noon

And debriefing sessions after each meeting

**Comment by kristenmcconnell** [comment]
Attended June 11 session (2- 3 p.m. ET)

**Comment by kristenmcconnell** [comment]
Just sent to Julia.
