### ISSUE TITLE
10-10EZ - Add Self-Identifying Gender Identity (SIGI) question

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25410]
# Date ES can accept the new question: November 2022

[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)
[SIGI Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Self%20Identifying%20Gender%20Identity%20(SIGI))

## High Level User Story/ies
As a veteran, I want to select my gender on the 10-10EZ form in order to reflect my self-identifying gender identity.

Note: This does NOT need to be added for Spouse. Only for the Veteran.

## Hypothesis or Bet
**If** we make this change, **then** more veterans will disclose their gender identity.

## OKR
Objective: More eligible Veterans apply for health care online
Key result: Number of applications increase
Key result: Proportion of applications submitted online vs. in person increases

### What must be true in order for you to consider this epic complete? 

- [x] Form updated to include gender identity
- [x] Backend updated to store and send gender identity
- [x] Test cases created
- [x] Monitoring plan created 
- [ ] Analytics created
- [x] Tested and verified in staging
- [ ] Accessibility verified
- [ ] Collaboration Cycle milestones met

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

# Checklist for Self-Identifying Gender Identity (SIGI)

## List your team, project contributors, and reviewers
<details>

### Product Team
- OCTO-DE Product Lead: Patrick Bateman
- Product Manager: Heather Justice, Mark Fallows
- FE Engineer: 
- BE Engineer: Lihan Li
- Designer: Jessica Stump
- Slack channel: `#1010-health-apps`
- GitHub tag: `sigi`

</details>

## List of project artifacts for requests

<details>

- [Project epic #25410](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/25410)
- [10-10EZ Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Health%20Care%20Application%20-%20Product%20Outline.md)
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Self%20Identifying%20Gender%20Identity%20(SIGI))
- [User flows](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/4A2A19CA-6283-4FDF-852E-0F5B3392959A/canvas)
- Product URL(s)
     - [va.gov/health-care/apply/application/introduction](https://staging.va.gov/health-care/apply/application/introduction)
- [Use cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-Self-identifying-Gender-Identity.md)
- Finalized design prototype or mockup
     - [Gender sketch file](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ag9MnWd)
- Regression test plans
TestRail 
     - [Test cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=6050)
     - [Test plans](https://dsvavsp.testrail.io/index.php?/plans/view/3565)
     - [Coverage for References (Cases) Report](https://dsvavsp.testrail.io/index.php?/reports/view/378)
     - [Summary (Defects) Report](https://dsvavsp.testrail.io/index.php?/reports/view/379)
     - [Accessibility Testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Self%20Identifying%20Gender%20Identity%20(SIGI)/QA/SIGI%20-%20Accessibility%20QA.md)
          - [ ] [Accessbility QA ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- Technical diagrams (architecture diagram, sequence diagram)
     - [Technical Diagrams folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/engineering)
- [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Self%20Identifying%20Gender%20Identity%20(SIGI)/Release%20Plan.md)
- Product guide for contact center

</details>
     
## List of process steps

<details>

**NOTE** - As of 4/2022, a new team took on this feature.  The feature was on hold and is already in the Staging environment behind a feature toggle.  The feature was taken off hold in August 2022 with a planned November release.  The team picked up where the previous team left off.  

- [x] Finalize design with feedback
     - [x] Present to team, stakeholders and any other interested parties
- [x] Create Use Cases
     - [x] Identify test users
- [x] Create Release Plan
     - [ ] Include E2E test results & signoff
- [x] Complete development
     - [x] Engineers work with Designers on any questions/clarifications
     - [x] Present to team for validation
     - [x] Present to Stakeholders for validation
- [x] Submit QA ticket and schedule with Tze (based on Dev ETA)
- [ ] Engage downstream system team for End-to-End QA coordination
     - [ ] Create E2E use cases and document results
     - [ ] Obtain signoff from downstream system team
- [x] Complete team level QA and Accessibility QA
     - [x] QA
     - [ ] Accessibility QA
- [ ] Request Staging Review 
     - [ ] Review findings with the team
     - [ ] Create tickets for work to be completed before launch
- [ ] Update Error matrix documentation with any new error states
- [ ] Update any FE and/or BE Engineering documentation
- [ ] Update Contact Center guide
- [ ] Submit Contact Center guide review ticket
- [ ] Update Release Plan
     - [ ] Include E2E test results & signoff
- [ ] Review this checklist for any missing artifacts
- [ ] Review the [Product Development Checklist](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/product-development-checklist)
- [ ] Conduct Launch Go/No Go with the team
     - [ ] Review this checklist
     - [ ] Review Release Plan
- [ ] Launch in a phased manner, according to Release Plan
- [ ] Continuous check-ins with downstream system
- [ ] Schedule or close all remaining tickets
     - Some tickets may be backlogged for future work, as they were not required to launch

</details>

**Comment by tchrisdyer** [comment]
Updated to clarify: This does NOT need to be added for Spouse. Only for the veteran.

**Comment by hdjustice** [comment]
Closing all SIGI tickets - There has been no further movement or discussion on this topic
