### ISSUE TITLE
Improve error messaging upon file upload error

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25416]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)

## High Level User Story/ies
As a veteran/caregiver, I want to be told what I need to do whenever I encounter an error while uploading a document while completing the 10-10CG in order to correct the problem or try again.

## Hypothesis or Bet
**If** we improve the error messaging upon file upload errors, veterans/caregivers will be more likely to complete their submission with a POA attachment.

## OKR
Objective 1: Make it easier to Veterans to apply to the PCAFC
Key result 1: Increase the number of successful online applications to the PCAFC (Target: 500)
Key result 2 Decrease the number of requests for application assistance from the Contact Center (Target: 50 )
Key result 3: Increase the % of PCAFC application submissions that are online rather than offline (Target: 10%)

### What must be true in order for you to consider this epic complete? 

- [ ] UX Error Messaging Defined
- [ ] Frontend UX updated to display appropriate error message upon file upload error.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by tchrisdyer** [comment]
This has been promoted to production, including fixes for accessibility and a compromise on the loading bar accessibility.
