### ISSUE TITLE
Investigate why Domo dashboard views dropped in April

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25424]
## Issue Description
Domo dashboard views dropped by 65% from March 2021 (183 views) to April 2021 (63 views). Given that this is a flagship Platform Analytics feature, we would like to investigate why this might be occurring.

![image](https://user-images.githubusercontent.com/48964695/120338194-ff24a380-c2c1-11eb-84d8-1666338774a3.png)

---
## Tasks
- [ ] Determine the accuracy of this data
- [ ] Determine possible causes of the drop
- [ ] Recommend next steps

## Acceptance Criteria
- [ ] Platform Analytics understands why the Domo dashboard views might have dropped and can recommend a path forward to bring the views back up.

**Comment by joanneesteban** [comment]
## Investigation

There was a 30% decrease in unique users from March to April, and the top users viewed the dashboards fewer times. Given that the Platform Analytics & Insights team stopped creating new & editing/maintaining existing custom dashboards, we assume that the usability of the existing custom dashboards on Domo was not as viable.

| March | April |
| --- | --- | 
| 29 unique users in March | 20 unique users in April |
| ![image](https://user-images.githubusercontent.com/48964695/124296600-24f2d180-db28-11eb-8ffb-8d07670a293d.png) | ![image](https://user-images.githubusercontent.com/48964695/124296359-dfce9f80-db27-11eb-99c7-b7377b300f28.png) |
