### ISSUE TITLE
[Research] Check-in MVP Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25422]
## User Story
- As a Veteran, I want to be able to check-in to my VA medical appointment via my mobile phone.

## Related Documentation
 - [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
Finalized documentation of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.

## Tasks
- [X] Create new folder for this specific test: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/mvp-usability
- [X] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/research-plan.md)
- [X] Create [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/conversation-guide.md) 

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product)
- [x] Review research plan and conversation guide with UX manager

**Comment by kristenmcconnell** [comment]
updated the Veteran-facing usability research plan and conversation guide to reflect the dates that we talked about this morning and our plan to utilize Twilio/staging.

https://dsva.slack.com/archives/C022AC2STBM/p1623091014364800

**Comment by kristenmcconnell** [comment]
Updated the research plan and conversation guide with feedback from Julia, Patrick, and Corey.

**Comment by kristenmcconnell** [comment]
Sending to Lauren Alexanderson for final review and to start Perigean recruitment.
