### ISSUE TITLE
[Research] Staff-facing Check-in In-person Observations and Research

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25420]
# Description
Go to VAs oj July 8 & 9, 2021 in and around Pittsburgh to interview and observe staff members who are part of the check-in process.

# Tasks
- [x] Meet with Julia Snyder for final prep once the sessions are scheduled
- [x] Go to VAs
- [x] Interview and observe staff (Document all findings)

# Acceptance Criteria
- [x] Finalize documentation and send to Julia (location TBD)

**Comment by kristenmcconnell** [comment]
- Had sync with Julia and Danielle to prep for what questions to ask and lessons learned from Dallas. 
- Set up call with Pittsburgh for July 6 at 11 AM ET

**Comment by kristenmcconnell** [comment]
Schedule – Thursday July 8th (UNIVERSITY DRIVE)

TIME      DEPT                      POC
9a           HAS                        Jeston Robinson
10a         Imaging                 Shayna Nowark
11a         Surgery                Renita Moore/Marva Brower-2nd floor Check-in
12:30     Medicine             Michael Hoover-9E130
1:30        PC                         Dana Saunders-Check-in Window Primary Care
2:30       BH                          James Newell-#1, bldg 29, 1st floor 

Schedule -- FRIDAY July 9th (HEINZ)

9a           Dental                   Kim Speranza
10a         PC                           Nicole Fechke
11a         Rehab                   Liz Tonarelli/Ann-PT/OT check in
1pm       Pharmacy             Richard Pratt-UD Lobby next to Pharmacy Windows
1:30p     Lab                          Monica Philips-Lab/blood draw collection area

**Comment by kristenmcconnell** [comment]
My final notes are posted to GitHub at: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/site-visits/visit-notes/Pittsburgh-KM.md

**Comment by kristenmcconnell** [comment]
Uploaded photos to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/site-visits/visit-photos
