### ISSUE TITLE
R&S 1.2: Migrate disability "intent to file" from t1

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#25439]
### Issue
As part of the [t1 disability audit](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23380), we decided to move "intent to file" content to R&S.

### Preview
http://preview-prod.vfs.va.gov/preview?nodeId=20490

### Tasks

- [ ] SC to create Word doc detailing changes to t1 pages and new content for R&S pages (Laura)

- [x] DEPO to edit Word doc (Beth)

- [ ] SC to build draft page in Drupal (Laura)

- [ ] DEPO to review draft Drupal page (Beth)

- [ ] SC to copyedit Drupal page (Randi)

- [ ] DEPO to review and share Drupal page with SMEs and approve for publishing

- [ ] SC to publish R&S page

- [ ] SC to make edits to t1 page (Laura)

- [ ] SC to copy edit t1 page and publish (Randi)

- [ ] DEPO to review live edits to t1 page (Beth)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Dropping an update in here for you on this. I want to make sure if we're going to put up an intent to file article that we address all the benefits that this is relevant to. So I got in touch with the pension SME a couple days ago. I asked if it's accurate that the pension online application doesn't follow the same effective date rules as disability, with the effective date being set when you click the button to start fulling out the application. She's pretty sure that's right and is verifying. 

It also makes sense to mention the other benefits that may be relevant for this article--survivors pension and DIC. That means running this article past both disability and pension SMEs. So once I have all the info, I'll update the article in drupal or ask for your help doing that. Then we'll send it out for a dual SME review.

**Comment by lwalsh617** [comment]
Adding a reminder here that once this article goes live, we should add links to it from disability, pension, and DIC pages.

**Comment by bethpottsVADEPO** [comment]
@RLHecht We'll need to coordinate the timing of disability wizard changes to the how to  file a claim page with the following new Q&As we'll add to how to file (disability, Veterans Pension, Survivors Pension, and DIC pages will all have tailored Q&As) when we publish the new R&S article about intent to file:

**How to file a VA disability claim** (2 tasks)
https://www.va.gov/disability/how-to-file-claim/ 
1/ Add this Q&A right above "What happens after I file..." 
2/ Remove current language about intent to file

**H2:  Should I submit an intent to file form?** 

If you plan to file for disability compensation using a paper form, you may want to submit an intent to file form first. This can give you the time you need to gather your evidence while avoiding a later potential start date (also called an effective date). When you notify us of your intent to file, you may be able to get retroactive payments (compensation that starts at a point in the past). 

**Note:** You don’t need to notify us of your intent to file if you file for disability compensation online. This is because your effective date gets set automatically when you start filling out your disability compensation form online—before you submit it. 

Find out how to submit an intent to file form
[LINK TO R&S article]

-----------------

**How to apply for a VA pension as a Veteran** (2 tasks)
https://www.va.gov/pension/how-to-apply/ 
1/ Add this Q&A right above "How long does it take VA to make a decision?" 
2/ Remove current language about intent to file

**H2:  Should I submit an intent to file form?** 

You may want to submit an intent to file form before you apply for pension benefits. This can give you the time you need to gather your evidence while avoiding a later potential start date (also called an effective date). When you notify us of your intent to file, you may be able to get retroactive payments (payments that start at a point in the past). 

**Note:** If you plan to apply online for pension benefits, you'll still need to notify us separately of your intent to file. 

Find out how to submit an intent to file form
[LINK TO R&S article]

----------------------

**About VA DIC for spouses, dependents, and parents** (1 task)
https://www.va.gov/disability/dependency-indemnity-compensation/ 
Add this Q&A at the bottom of the page, right above the gray related links box:

**H2:  Should I submit an intent to file form?** 

You may want to submit an intent to file form before you apply for DIC benefits. This can give you the time you need to gather your evidence while avoiding a later potential start date (also called an effective date). When you notify us of your intent to file, you may be able to get retroactive payments (payments that start at a point in the past). 

Find out how to submit an intent to file form
[LINK TO R&S article]

------------------------

**VA Survivors Pension** (1 task)
https://www.va.gov/pension/survivors-pension/ 
Add this Q&A right above "How long does it take VA to make a decision?":

**H2:  Should I submit an intent to file form?** 

You may want to submit an intent to file form before you apply for VA Survivors Pension benefits. This can give you the time you need to gather your evidence while avoiding a later potential start date (also called an effective date). When you notify us of your intent to file, you may be able to get retroactive payments (payments that start at a point in the past). 

Find out how to submit an intent to file form
[LINK TO R&S article]

**Comment by RLHecht** [comment]
Removing the Q&A from the Survivors Pension page for now so we can publish a change needed for ticket #29906. Will put back in once stakeholders give us OK to publish.

**Comment by bethpottsVADEPO** [comment]
Intent to file article is ready to publish--and all the tier 1 page updates that will cross link to it. @RLHecht would you do a final copyedit, run through the prepub checklist, and then publish? We'll wait to hear back from Kelly in Pension about whether we should cross link from all 3 of these pages (for now, let's hold off on adding it to the DIC page): 
http://preview-prod.vfs.va.gov/preview?nodeId=590
 http://preview-prod.vfs.va.gov/preview?nodeId=586
 http://preview-prod.vfs.va.gov/preview?nodeId=855

**Comment by RLHecht** [comment]
The Intent to file article is published as well as Survivors and VA Pension pages with the crosslinks.

**Comment by RLHecht** [comment]
I published the DIC page as well, so this ticket is now complete. Moving to validate and will close after next deploy.
