### ISSUE TITLE
KMI email #10: Adolescents

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#25449]
## User story

As a Veteran, caregiver, or family member, I want the latest updates on COVID-19 vaccines at VA.

## Issue description

Send KMI email #10 with update on adolescent eligibility for vaccines.

## Tasks to completion

- [x] Create content (Danielle)
- [x] Copy edit (Randi)
- [x] Send to JTF for awareness (Lauren)
- [x] Flow content into template and send for review (Maria and team)
- [x] Review template against content and sign off (Lauren, Danielle, Randi)
- [ ] Send email (Maria and team)

**Comment by DanielleThierryUSDSVA** [comment]
Draft content: [KMI email 10_adolescents_06.01.21](https://app.zenhub.com/files/133843125/9c24308a-31da-4316-b1d5-e693097afa62/download)

@RLHecht Could you review this for a copy edit please?

@batemapf @clantosswett @shanemelliott This is pretty straightforward and based on approved content. But any thoughts welcome!

@miabecker - @lalexanderson-dsva is sharing this with JTF for awareness, and then we'll be ready to send this week.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here you go. Just a few small tweaks. The link for unsubscribing isn't working for me but I think that shouldn't be an issue.
[KMI email 10_adolescents_06.01.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6578312/KMI.email.10_adolescents_06.01.21.docx)

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA created our ticket on VANotify board to track: https://app.zenhub.com/workspaces/vanotify-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/vanotify-team/57 will keep an eye for content updates! Who is this going to in terms of segmentation?

**Comment by lalexanderson-dsva** [comment]
THis has been sent to JTF.

**Comment by DanielleThierryUSDSVA** [comment]
@miabecker Just confirming here that this can go to all segments. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @miabecker @philherbert. Looks like email is still in JTF review. We'll let you know as soon as we have approval to send. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Closing old ticket
