### ISSUE TITLE
[Research] Compare click numbers of links in the “Top 4” 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25445]
## Description 
Analytics ticket to compare click numbers of links in the “top 4” boxes (which are used frequently vs. infrequently) in preparation for research recommendation meetings (as programmed).

## Tasks
- [x] Review/Compare click numbers of links in "Top 4" quadrant 
- [x] Add to shared content from research 
- [ ] Prepare for research recommendation meeting

**Comment by cindymerrill** [comment]
Started looking at analytics data for the "top 4" boxes, and posted a quick question to #vfs-analytics. Started a visualization of link click frequency.

**Comment by cindymerrill** [comment]
Got an answer from Brian Martin. Pulled down data from May 19 and later, which is when they added click tracking per individual "top 4" box. Here's the resulting visualization: https://docs.google.com/presentation/d/1u-FGy-Bepf_03jC6iy0x0ONi7bYiJA4_MT81Ohfz-wE/edit#slide=id.gde880b730a_0_0

**Comment by cindymerrill** [comment]
Just posted my visualization of analytics data on links in the “top 4” boxes [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/Top4-boxes-analytics-visualization.pdf)
