### ISSUE TITLE
[FE] Update application to say questionnaire 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#25458]
## Related Documentation

> these should be links to feature docs

- [MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Description

Update this to be configurable to say questionnaire![Screen Shot 2021-06-01 at 3.36.09 PM.png](https://images.zenhubusercontent.com/5ecebb879a043b865f6cb5b6/9b7b00fd-6c10-428c-95e8-352f93da1563)

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] update forms system to allow that to be configurable. 
- [ ] Create user tests
- [ ] Update relevant documentations

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
