### ISSUE TITLE
[FSR] Redesign employment sections to allow for multiple current jobs [usability]

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#25460]
## Issue Description
Currently, both the Veteran and spouse employment screens allow for only a single current job. Adjust the design to allow for multiple current jobs.

---
## Tasks
- [x] Redesign the employment sections to allow for multiple current jobs
- [x] Sync to UXPin - both Unauth and Auth
- [ ] Create a frontend ticket for the work

## Acceptance Criteria
- [x] Designs updated and posted in UXPin, then linked in this ticket
- [ ] Frontend ticket created and linked in this ticket

**Comment by LinnJS** [comment]
duplicate

**Comment by LinnJS** [comment]
duplicate
