### ISSUE TITLE
[FSR] Implement redesigned employment sections

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#25463]
## Issue Description
We redesigned the employment sections of the form to allow for multiple current jobs by having a single list loop for employment and subsequent income pages for each current job. We need to replace the current pattern for both the Veteran and their spouse with the redesign.

[See designs in UXPin here.](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/139219177?mode=i)

---
## Tasks
- [ ] Update employment sections for both the Veteran and their spouse
- [ ] Review with designers

## Acceptance Criteria
- [ ] Employment sections implemented
- [ ] Reviewed by designers

**Comment by craigwheeler** [comment]
Current ticket is a complete refactor of the way data is captured on FE for current employment, income and payroll deductions for both the veteran and spouse sections including changes to the current review page along with data transformers. This change is a huge lift and is currently still in progress.

**Comment by craigwheeler** [comment]
Work has been completed but this change includes breaking changes for users that have save in progress data from previous sessions so will need to verify whether SIP data can be cleared to direct users to start a new form
