### ISSUE TITLE
NOD: Prevent adding > 1 year old decision date

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25466]
## Description

While demoing the Notice of Disagreement form with the Board, they asked to ensure that any manually added issues with a decision date > 1 year in the past not be allowed.

## Tasks

- [ ] Prevent decision date > 1 year in the past
- [ ] Show appropriate error message
- [ ] Add unit tests

## Definition of done

- [ ] Add date restriction to added issues
