### ISSUE TITLE
S+D Sprint 50 Priorities

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25474]
## Search & Discovery Team Sprint 50 Priorities (WIP)

To summarize and track team efforts aligned to Sprint 50 (June 16 - June 29, 2021)
_Aligned with [Quarterly Planning](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/search-discovery/quarterly-planning.md)_

## Sprint Goals/ Priorities
1. Respond to Staging Review Feedback for UI Consistency for Global Search
2. Resolve Typeahead Suggestion Report Issue
3. Plan Research Session for Design Concepts
4. Google Search Console Exploration

#### *Typeahead 1.0* [#17558](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17558)
- [ ] Determine why queries with Typeahead Suggestions are appearing on reports #26100
- [ ] Typeahead Suggestion Monthly Report #25483
- [ ] Establish Automated testing for Typeahead #25364

#### *Global Search UI Consistency* [#25484](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25484)
- [ ] Respond to Staging Review Feedback + Launch #26104

#### *Surfacing Search Tools* [#20402](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20402)
- [ ] Next steps?

#### *Search Landing Page* [#24333](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24333)
- [ ] Search Landing Page (404) Mockups #26558

#### *SEO + Offsite Enhancements* [#16128](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16128)
 - [ ] Change Sitemap dates from Published to Edited #22980
 - [ ] Google Search Console Exploration #21795

#### Search Result Relevancy [#25485](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25485)
 - [ ] Remove Stop Words #24892
 - [ ] Investigate search tool content indexing #25554

#### Click Tracking
- Follow up on Privacy & Security Collab Cycle Request

## Sprint Demo: 
- *Topic*:  We did not present at demo this week as we were responding and resolving Staging review feedback and planning for usability study

## New Backlog Tasks identified this sprint
- describe Pie in the sky - ideal search experience #26288
- exploring feasibility of a best bet API (would need to discuss with search.gov) #26796
- Media query for right rail (add to sprint 50) #26287
