### ISSUE TITLE
S+D Sprint 49 Priorities

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25473]
## Search & Discovery Team Sprint 49 Priorities

To summarize and track team efforts aligned to Sprint 49 (June 2 - June 15, 2021)
_Aligned with [Quarterly Planning](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/search-discovery/quarterly-planning.md)_

## Sprint Goals/ Priorities
1. UI Search Consistency Changes for Global Search Pages
2. Provide Stop Words to search.gov for removal
3. Design Exploration for Search Landing Page
4. Surfacing Search Tools - DEPO Review

#### *Typeahead 1.0* [#17558](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17558)
- [ ] Typeahead Suggestion Monthly Report #25483 (Blocked by #26100)

#### *Global Search UI Consistency* [#25484](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25484)
- [x] Implement UI Consistency Elements on Global Search - Part 2 #24988 
#### *Search Reorganization + Improvements* [#22977](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22977)
- [x] Error Logging Improvements #24968
- [x] Search Reorganization - Modernization / Tech Debt #24118

#### *Surfacing Search Tools* [#20402](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20402)
- [x] DEPO Design Review #22500

#### *Search Landing Page* [#24333](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24333)
- [x] Design Exploration - Search Landing Page #24300
- [x] PO Review of Initiative Brief Search Landing Page #25547

#### *Best Bets* [#24331](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24331)
- [x] Best Bet Audit + Initial Strategy Definition #24328
- [x] Collect VAMC + Vet Cetner Info for Best Bets #25532

#### Spelling Enhancements #19190

- [x] Search "We think you meant" Frontend implementation #19225

#### Results Relevancy
 - [x] Investigate Search Result Relevancy Score #25553
 - [x] Remove Stop Words #24892

## Unplanned Additions
- [x]  Describe "Search Start Page" with modified screenshots#26011
- [x] Best Bet Request for COVID-19 CLP #25969

## Sprint Demo: 
- *Topic*:  Global Search UI Changes,  Spelling Enhancement and Reorganization Improvements  
- *Presenter*: Sam Suddath
