### ISSUE TITLE
FE implementation for Locations list: Add mobile clinic heading

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25479]
## Issue Description
Mobile clinics are currently included in a list of clinic locations on the VAMC locations page. Because these locations are so different, we need to differentiate them visually. Example: [Cheyenne health care](https://www.va.gov/cheyenne-health-care/locations/)

An update to the detail page is a separate effort. We need to update the Locations page to separate mobile clinics from physical locations. 

---
## Tasks
- [x] Identify mobile clinics (migrated data from Facility API, mobile = true)
- [x] Implement new FE design according to UX Pin specs](https://preview.uxpin.com/fd54ec2443e9812dfc2a26fe5ec10e7cde590ecc#/pages//simulate/no-panels?mode=i) 
    

## Acceptance Criteria
- [x] The following headings are available on the VAMC Locations page 
      - Main location
      - Health clinic locations
      - Mobile clinics
      - Other nearby locations
- [x] Locations under Health clinics heading organized alphabetically
- [x] Facilities with mobile = true are found only under the Mobile clinic heading and are organized alphabetically
- [x] Mobile facilities include a linked name, phone number and photo (when available). 
- [x] Displayed details for facilities under all other headings remain unchanged.  
- [x] If a phone number is not available, the phone label is hidden but the location is still displayed. 
- [x] 45 px padding appears above the heading

**Comment by mmiddaugh** [comment]
Viewed this in for [Cheyenne in Prod](https://www.va.gov/cheyenne-health-care/locations/) 
I do not see a mobile clinic heading with relevant locations. 
Mobile clinics appear in the side nav but do not appear on the page. 
![screencapture-va-gov-cheyenne-health-care-locations-2021-06-17-16_55_53](https://user-images.githubusercontent.com/55411834/122482097-28655500-cf8d-11eb-9115-ef2dc36ebe24.png)

**Comment by mmiddaugh** [comment]
Mobile heading appears and the correct locations are listed.  

Locations are not alpha order - I would expect Rawlins to appear before Sidney in Health clinic location list: 
![image](https://user-images.githubusercontent.com/55411834/122796288-71622580-d27b-11eb-87ad-1607ddc57200.png)
@mpelzsherman

**Comment by mpelzsherman** [comment]
Closing, see https://dsva.slack.com/archives/C0FQSS30V/p1624471517363500?thread_ts=1624471475.363300&cid=C0FQSS30V
