### ISSUE TITLE
Typeahead Suggestion Monthly Report

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25483]
##  Description
Generate a report showing all queries between (May 13-May 31) that had zero typeahead suggestions generated. 

## Tasks

- [x] Sam to generate report
- [x] Denise to manual review queries 

## Acceptance Criteria
- [x] report available for suggestion seeding strategy
- [x] Terms have been reviewed to determine which are missing typeahead suggestions

**Comment by srsuddath** [comment]
report is downloadable here, just click export in the top right corner

https://analytics.google.com/analytics/web/#/opusreport/05GaeRupTCKThVmvlbhQAQ/a50123418w177519031p176188361/_u.dateOption=&_u.date00=20210513&_u.date01=20210531&_u.date10=&_u.date11=&_r.dsa=1&241-table-dataTable.sortColumnName=analytics.uniqueEventsTrue&241-table-dataTable.sortDescending=true&241-table.plotKeys=%5B%5D/

**Comment by denisecoveyduc** [comment]
@srsuddath As discussed this report appears to show query terms that do indeed have suggestions associated with them. You planned to reach out to Brian to explore the typeahead enabled flag - let me know if we are able to extract query terms  that have no typeahead suggestions. I am interested to understand what our top queries are that don't have suggestions.

**Comment by denisecoveyduc** [comment]
This issue is blocked by #26100. Queries with typeahead suggestions are appearing on reports and as a result we are unable to generate reports to show queries that are not presenting users with suggestions. Seeing these terms will help us determine our seeding strategy going forward. As a result we will roll this over into S50 or until we are able to generate these reports.

**Comment by denisecoveyduc** [comment]
@srsuddath created the following report showing the top 250 search terms that did not generate any typeahead suggestions

[No Suggestion Report_ May 13 - June 23 2021.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6709704/No.Suggestion.Report_.May.13.-.June.23.2021.xlsx)

As per comment in [GH #26100](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26100#issuecomment-867554865) ,  we recognize that terms that have suggestions may appear on this list.  

> We believe that this issue is not a problem with our analytics tagging or typeahead functionality, but rather a problem with the delay in fetching typeahead suggestions.
> 
> Our hypothesis is that certain users with slow internet connections, or users who follow the "type a suggestion and then press enter" search pattern will initiate a search faster than suggestions can populate, reading to "false positives": searches appearing to have no suggestions.

Next Steps: @denisecoveyduc  will manually review this list to identify which terms do not have suggestions. There is a potential we may need to increase total number of terms but want to monitor the total unique events if we do so.
