### ISSUE TITLE
[SD] UI Consistency for Global Search

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25484]
## Description
As a direct result of the UI Search Consistency Initiative the search team will implement the design pattern on all global search pages. 

## Background/Context
- UI Consistency Initiative #21055 

## Collaboration Cycle Events Tracking
- [x] **Collaboration Cycle Kickoff :** [#25596](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25596)
 - [x] **Design Intent:**  
 - [x] **IA request:** Not Required
 - [x] **Research Plan Review:** Not Required
 - [x] **Analytics Request:**  Not Required
 - [x] **Usability Testing Prep:** Not Required
 - [x] **Contact center review:**  [#26080](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26080)
 - [x] **Staging Review:** *[Request Issue: #26080  - Scheduled Date: June 22, 2021* 
	 - [ ] *Accessibility Feedback (Josh Kim, Angela Fowler, Trevor Pierce, Noah Gelman)* - all linked to Epic #26323 
       - #26335 (508-defect-1) ❗️- Headers **[@mgleo  to discuss with Josh]**
       - #26352 (508-defect-4) sr-only text **[@srsuddath has resolved]**
       - #26353 (508-defect-2) Semantic Markup **[Share with Decision Tools]**
       - #26360 (508-defect-2) Screenreader: Search fields landmark role **[Separated the Global Search Component into #26506 which @srsuddath has resolved. This issue will be shared with the Public Websites team to address the Resources & Support feedback]**
       - #26413 (508-defect-2) Resources & Support Search Button Should not be disabled **[shared with public websites team]**
       - #26416 (508-defect-1)❗️ Focus Management [contains four parts each have been separated for implementation
           -  #26530
           - #26532
           - #26533
           - #26534
       - Potential Bug - www.fsc.va.gov/fsc/payroll is announced as  VA.gov Veterans Affairs" on screenreader **[we are unable to change titles of pages. This is a legacy page example that can't be changed]**
       - Pagination clips off page on smaller screen sizes  **[Sam will check if there are any updates from the component library to see if we are able to fix this. If there isn't an update that fixes it Sam will move 'powered by search.gov on top of  pagination]**
       - right rail doesn't responsively wrap   **[will be resolved with #26287 - Leverage Media Queries]**
        - "Back to top" on the Find a VA Form Search result page. **[Will share with Decision Tools Team]**
	 - [ ] *Information Architecture (IA) Feedback (Mikki Northuis)*
		 - #26421 User Flow when no search value is entered 
	 - [ ] *QA Feedback (Tze Lei, Peter Hill, Dariusz Dzien)*: 
	   - No Feedback
	 - [ ] *Design Feedback (Allison Christman)* 
		 - #26308 (Must) Spacing on Find a Form Page **[Share with Decision Tools]**
		 - #26308 (Should) Remove horizontal rule **[Share with PW Team]**
	 - [ ] *Content Feedback (Peggy Gannon)* 
		 - [#26368](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26368)
           - Consistent Labeling (Should) (Send to Decision Tools)
           - VA Form Page (Should) (Send to Decision Tools)
           - Plain Language in Labels (Consider) (Send to Decision Tools)
	 - [ ] *Product Feedback* (Shira Goodman) 
		 - No Feedback
	- [ ] *Platform's OCTO-DE co-leads* 
		 - No Feedback - Ryan said we may circle back as this is implemented across all experiences. 
	- [ ] *Analytics (Joanne Esteban)*(if needed)
		 - No Feedback
- [ ] Staging Feedback has been resolved #26104
- [ ] **Privacy & Security Review**:  TBD
- [ ]  **Target Launch Date:** TBD  (See Release Plan for additional details) 
 - [ ] **Post Launch -  Full Accessibility + 508 Office Audit:** TBD
 - [ ] **Post Launch - Check in:** TBD
