### ISSUE TITLE
Move Cerner offboarding to Facility v2

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25482]
## Description
Currently, if a user is registered at a Cerner facility they are directed to the Facility Selection v1 page (`/va-facility`). All users should choose a facility from the Facility Selection v2 page.

---
## Tasks
- [ ] Cerner offboarding to Facility Selection v2

![Overview - Cerner sites on V2 facilities page.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/6a887604-ca3b-44a6-80e6-b2075fb0c413)

## Acceptance Criteria

- [ ] If user is registered at a Cerner site, Then display `/va-facility-2` page for Facility selection

- [ ] If user selects a Cerner facility, Then display Cerner facility (dead end) page

- [ ] _(existing behavior)_ If user selects a non-Cerner facility, Then display Clinic Selection page 

- [ ] If user clicks My VA Health link, Then open Cerner portal in the same window

- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/facility-selection.md) 

- [ ] CONTENT - Cerner facility page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cerner-offboard.md)

- [ ] DESIGN - Designs match the specs (copy is FPO)
- Cerner facility links
- New "How to schedule" page

## Design Assets
**Specs**
All spec copy is FPO. Use copy in the copy doc.

- [Mobile spec](https://www.sketch.com/s/b61269d5-4ea9-439f-b86a-5bf9562d84ba/a/25YVQj5#Inspector)
- Tablet spec (TBD)
- Desktop spec (TBD)

**Workflow**

- [Workflow overview](https://www.sketch.com/s/b61269d5-4ea9-439f-b86a-5bf9562d84ba/a/rblP2LG)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
