### ISSUE TITLE
[VAMC] Create csv file for System Health Services used to migrate into CMS Systems [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#25495]
## Story
As a data editor and customer, unique system health services need to be pulled from the system playbook and migrated through an automated process, so the process is scalable and accurate.

## Goal
Create a repeatable process that will allow for scalable input into the CMS system via data migration

## Resources
[Previous csv files](https://drive.google.com/drive/folders/1jpxDn49L4NonSd6bxya4HZX6kC56fCna)

## TASKS
**Transform playbook into a csv file following these steps**
- [ ] provide one single csv file with required columns for upload into CMS.
>	1. Pull system data into excel file and remove duplicates
>	a. File format must have the following headers:
>		i. ID; Health Services; Full Upload; Health System;, Owner
>	2. Combine all unique system files into one file for the VISN
>	a. Remove all "N/A" lines
>	b. Upload file to access.db for comparison  
>	c. Document number of lines remaining
>	d. Run query to combine Health service library with SHS
>	3. Export file
>	4. Combine columns
>	5. save as csv file
>	a. open in notepad or Notepad +
>	b. Open back up in excel
>	c. Delete columns that are not required
>	d. add brackets to all columns but ID
>	e. Save as csv with version
>	6. Open in editor
>	a. Change all brackets to ' 	

## Acceptance Criteria
- [ ] .csv file created with required column headers to be uploaded into CMS
- [ ] provide support and corrections to CMS engineer until PR is uploaded correctly with no errors.

**Comment by bcastoe** [comment]
#25495 - Create csv file for System Health Services used to migrate into CMS Systems - 06092021 Pulled data from playbooks to create unique system and faciality information for VISN-17.  Listed as BLOCKED as pending/awaiting new list.
