### ISSUE TITLE
[Tech-Debt] Update LGBTQ+ and Suicide pages with new updates from SOT VISN-6 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#25493]
## User Story
As a VHA Digital Media web manager, the national changes need to be implemented prior to Dual state or full production launches, so the systems are updated adequetly prior to the redirect.

## Goal
Remove tech-debt prior to full production

## Resources - Tools - Documentation
TBD

## Tasks
UPdate LGBT with LGBTQ and Suicide pages with new content and organize page correctly.
- [x] Update Suicide pages with correct format order and new content
- [x] Change out LGBT with newly authorized LGBTQ+ in locations provided by Content.
_
**Complete for the following locations**
- [x] VA Asheville health care
- [x] VA Durham health care
- [x] VA Fayetteville Coastal health care
- [x] VA Hampton health care
- [x] VA Richmond health care
- [x] VA Salem health care
- [x] VA Salisbury health care

## Acceptance Criteria
- [x] Suicide pages are updated and if caregiver is not listed on page it is reported in Support channel.
- [x] LGBTQ+ pages are updated and if caregiver is not listed on page it is reported in Support channel.

**Comment by bcastoe** [comment]
#25493 - Update LGBTQ+ and Suicide pages with new updates from SOT VISN-6 
    07/28/21  Put in blocked due to the following question:  Regarding updating Suicide - do all pages (Detail, System, 
                     Facility), need to be listed?  Asking as Asheville, Durham, Hampton, and Salisbury only have the detail 
                      page.

**Comment by bcastoe** [comment]
07/30/21   (1) Moved back to IN PROGRESS as informed to add the System and Facility page to the ones that are                   missing (2) Completed and moved to Validate
