### ISSUE TITLE
Update pages with info on new presumptive conditions

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#25505]
## Issue Description
VA has added 6 new presumptive conditions (3 for Agent Orange and 3 for burn pit toxic exposure). To support this we need to add information to our pages:

- Update the bullets in the top 2 accordions on the disability Agent Orange page
- Add an info alert to replace the Blue Water Navy alert on the Agent Orange page
- ~Add an info alert to disability pages relevant to particulate matter exposure (added this task 6/2/21)~
- ~Make similar updates to the health care Vietnam page~ 

We also will need to decide if we'll also announce the new process of considering presumptive conditions that will eventually mean new presumptive conditions added to the toxic exposure related to burn pits. 

For context:
Facebook: https://www.facebook.com/VeteransAffairs/photos/a.10150363885273178/10158575266238178
Twitter: https://twitter.com/SecVetAffairs/status/1397976441661296643?s=20
Blog: https://blogs.va.gov/VAntage/89496/breaking-news-va-plans-expansion-benefits-disability-claims-conditions-related-certain-toxic-exposures/

## Tasks
- [x] Update bullets (Beth)
- [x] Add info alert (Beth)
- [ ] Make updates to health care Vietnam page (Beth)
- [x] Send to SMEs (Beth)
- [x] Review and publish (Randi)
- [ ] Decide on announcing new process (Beth)

## Acceptance Criteria
- [x] New info is live on pages

**Comment by bethpottsVADEPO** [comment]
@RLHecht here are the preview links. Melissa Rebstock is reaching out to SMEs with screenshots to get an accuracy check. Then we have to socialize to the larger comms group.
http://preview-prod.vfs.va.gov/preview?nodeId=874
http://preview-prod.vfs.va.gov/preview?nodeId=885

I added the social media links above in the ticket case anyone needs context.

Next: We wait to hear if this approach is sufficient to meet leadership expectations. If it is, the alert on 885 will need to be added in drupal to 4 more pages. Here's the breakdown:

The alert on this page: http://preview-prod.vfs.va.gov/preview?nodeId=885
... will be placed on all of these pages: (edited) 
10:02
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/specific-environmental-hazards/
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-southwest-asia/
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-afghanistan/
https://www.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/

The Agent Orange alert will only go on the one page:
http://preview-prod.vfs.va.gov/preview?nodeId=874
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/

**Comment by RLHecht** [comment]
Agent Orange page with new alert and bullets published 6/15

**Comment by bethpottsVADEPO** [comment]
@RLHecht Would you pull the particulate matter info from above into a new ticket, then close this one? Thanks!

**Comment by RLHecht** [comment]
Particulate matter info was moved to ticket #26675 to continue working on. Closing this ticket as work is complete.
