### ISSUE TITLE
[Research] - VAOS/profile facilities research sessions

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#25509]
**Background**
We're running a research study with the VAOS team to evaluate the new facilities section of profile and how it fits into the VAOS flow.

**Tasks, in collaboration with Peter**

- [ ] Facilitate 50% of research sessions
- [ ] Take notes in 50% of research sessions
- [ ] Participate in daily debriefs
- [ ] Help w/ logistics as needed

**Comment by andaleliz** [comment]
Sessions completed 6/9
