### ISSUE TITLE
Discovery: [FSR] Total Benefits the Veteran is entitled to (gross amount) are not returned to FE

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#25508]
## Issue Description

FE needs to display the VA Benefits TOTAL a Veteran is entitled to and is currently not being returned by the BGS endpoint. SIP endpoint `/v0/in_progress_forms/5655` returns the PAYMENT HISTORY `bgs/payment_service/payment_history` but the TOTAL AMOUNT the Veteran is entitled to (gross amount) are not returned to FE

https://github.com/department-of-veterans-affairs/vets-api/blob/bfa443cecc932475b9d976cc30e34822e4b5657e/config/form_profile_mappings/5655.yml#L12

![7b5d13b0-64f6-423f-94a9-25cb0b40e5d7.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/51b4cbed-e180-43b0-bc54-78086ef71f04)
---
## Tasks
- [ ] provide a way for FE to retrieve the total benefits the Veteran is entitled to (gross amount)

## Acceptance Criteria
- [ ] Obtain data dictionary or data-contract from DMC that outlines enums for payment types.

REVISED Acceptance Criteria (as of 2/28/24):
- [x] Identify the source of data and contacts on Lighthouse Team to retrieve data if and when needed.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
@craigwheeler, For context, as of today, the FSR benefit fields are prefilled by:
- Obtaining a list of historical payments from BGS
- Filtering the list by `payment_type` of "Compensation & Pension - Recurring" or "Post-9/11 GI Bill"
- Selecting the payment with the most recent `payment_date` (excluding items with nil payment_date).

It may be possible that (1) there are more `payment_types` we are not considering, or (2) last payment isn't the most accurate way to calculate "current benefits".

Can you provide information on what is missing, or expected to be provided, in the prefill? (We can also do a zoom call when this ticket is "In Progress" if that's easier).

**Comment by kevinmirc** [comment]
Also worth noting that if the user cannot be found in BGS, the benefits data is empty (in the prefill).

**Comment by denisecoveyduc** [comment]
@ScottyRJames Reviewing my notes from one of our meetings and we indicated some BE technical discovery is needed for this so adding a note to remind us when we get to this.

**Comment by Tom-Davis** [comment]
@joehall-tw @amponce is this display still a valid item? If it is no longer a valid request we can close it with that note.

**Comment by Tom-Davis** [comment]
If this is no longer an issue we should also close https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/24403

**Comment by josephrlee** [comment]
@Tom-Davis, actually, I don't know if this should be closed or not anymore. I think this is a different issue than I thought it was. Looks like it's more of a BE thing.

**Comment by HeatherRienks** [comment]
We need to investigate this- maybe add to S111?

cc @Tom-Davis

**Comment by HeatherRienks** [comment]
@kjsuarez - can you please take a look at this? Let's plan to discuss. If this is still an issue, we can refine and prioritize.

cc @Tom-Davis

**Comment by HeatherRienks** [comment]
Per Refinement, @asmithgovcio and @kjsuarez to look into this ticket.

**Comment by asmithgovcio** [comment]
@HeatherRienks @denisecoveyduc I've looked into this ticket and it will take some work on the backend for both vets-api and the BGS service which is a bit of a black box on the backend, the methods that are being called for this are not contained within our code base so we're unable to change them. That being said there seems to be a disconnect between whats being requested and what that service does, from what i can tell it returns information on payments already made, it doesn't provide information about totals one is eligible to receive. 

This looks like it will be a somewhat significant lift to implement, the current payment service simply doesnt support this functionality. Its a payment *history* service.

**Comment by asmithgovcio** [comment]
This will require changes to this repository https://github.com/department-of-veterans-affairs/lighthouse-benefits-gateway-services, specifically [this file](https://github.com/department-of-veterans-affairs/lighthouse-benefits-gateway-services/blob/master/bgs-client/src/main/java/gov/va/api/lighthouse/bgs/BgsClient.java) and other files. I will reach out to someone on the lighthouse benefits team to see if we can get the ball rolling on this.

**Comment by HeatherRienks** [comment]
Per Standup today, @Tom-Davis will be modifying the AC to only encompass the discovery portion; no implementation will be needed. Moving this ticket to closed.

@asmithgovcio - Would you please let Jessica Sexton know that no effort is needed at this time so she can share with the other Lighthouse PM's?

cc: @denisecoveyduc

**Comment by asmithgovcio** [comment]
@HeatherRienks yes Ive notified Jessica, the slack threads are in our payment history channel.

https://dsva.slack.com/archives/C06DR7N1V98/p1707491488500889

https://dsva.slack.com/archives/C06DR7N1V98/p1708982979463679

https://dsva.slack.com/archives/C06DR7N1V98/p1708983167893229

**Comment by Tom-Davis** [comment]
Closing as discovery work is complete.
