### ISSUE TITLE
Adjust RO for CH31 Pilot (*Date*)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25518]
##  Background
The CH31 application (CMS) is phasing in their RO and need them added slowly to the wokr flow. 

## Considerations
- CMS will be rolled out to the first pilot station, **Cleveland**, on **~~Wednesday, May 12~~**.
- Below are the pilot kick off dates for the additional pilot stations, for awareness:
  - ~~San Diego on May 24~~
  - ~~Denver on June 7~~
  - ~~Columbia on June 21~~

## Tasks
- [ ] Update this [file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/veteran_readiness_employment_claim.rb#L9) with the appropriate RO
- [ ] Request review and merge as needed

## Acceptance Criteria
- [ ] RO has had their location added to receive CMS submissions
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
VR&E CMS is officially done, they are looking for a new team to build this
