### ISSUE TITLE
[Research] Preferred Facilities: VAOS/profile facilities research synthesis

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#25510]
**Background**

Now that the study is complete, we need to conduct synthesis on the data we collected

**Tasks, in collaboration with Peter**

- [x] Create topline summary
- [x] Share w/ team + incorporate feedback
- [x] Conduct final synthesis

**Comment by andaleliz** [comment]
@Samara-Strauss, @laurenernest, @ajakabcin, @erikphansen - Peter and I started the process of collaborating on a topline summary for our research study, despite having 1 last session to complete. We feel we have common enough trends to identify some high-level perceived findings, and will certainly update this to include data from the last session as needed.

We'd love to get your input on this! Specifically:
- Do these align with what you observed?
- Is there anything that stood out to you from the sessions that is not captured here?
- Are there any specific findings you want to make sure we really dig into as we complete the final data analysis?

I think of this as more of a working doc than a final deliverable, so I don't think it's necessary to provide feedback on grammar, punctuation, etc (though I did try to clean that up).  Also, anywhere we say "some", "many", "most" etc, will be updated with specific numbers after we do the final analysis.

[Here's a link to the doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/topline-summary.md). If you can provide feedback by EOD tomorrow, that'd be great! If that's not possible, but you definitely plan on reviewing/providing feedback, let me know so I don't interpret silence as acceptance :)

**Comment by Samara-Strauss** [comment]
This looks great! Very thorough. Nice work!! Looking forward to seeing the recommendations that come out of this research.

**Comment by laurenernest** [comment]
@andaleliz @outerpress Looking good!

**Dig in more**
[Most participants saw value in being able to save facilities to limit their options in scheduling, sending secure messages, and for travel purposes.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/topline-summary.md#most-participants-saw-value-in-being-able-to-save-facilities-to-limit-their-options-in-scheduling-sending-secure-messages-and-for-travel-purposes) 
- I would like to get a better understanding of other products or channels they expected the preference to influence (appointment-related or not). I'm trying to keep in mind any adverse effects to building for our specific situation.

**Comments**
[Participants clearly understood they couldn't schedule online at every facility, but they didn't understand why.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/topline-summary.md#participants-clearly-understood-they-couldnt-schedule-online-at-every-facility-but-they-didnt-understand-why-some-participants-wanted-to-see-this-information-earlier-in-the-scheduling-process)
- This bullet seems to conflict with the finding of not understanding why

> Most participants understood the facility didn't offer online scheduling.

**Comment by laurenernest** [comment]
Much clearer. Thanks!

**Comment by andaleliz** [comment]
**Update**
- [Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/topline-summary.md) created, synthesis in progress.
- Peter and I have divvied up the sessions and are working on associating verbatim notes to tasks/research questions to identify trends via an [affinity map in Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1623094588406/918ef3279e0fb661409656bdafe06aee2ee098e9)
- I've completed my sessions, anticipate Peter will complete his by mid-week.

**Comment by ajakabcin** [comment]
Rolling to sprint 51

**Comment by andaleliz** [comment]
[Final report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/research-findings.md) complete!

**Comment by andaleliz** [comment]
[Final report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/research-findings.md) complete!
