### ISSUE TITLE
Create new PTSD page designs

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#25522]
## Issue Description
Work on initial design draft of new PTSD pages.

---
## Tasks
- [x] Create Combat flow in Sketch

## Acceptance Criteria
- [x] Combat flow has been created as Sketch files and properly documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
The Combat flow has been recreated in Sketch files and can be found here:

https://sketch.cloud/s/7b8d47d8-50f5-4119-9a70-f7281e56fd58
