### ISSUE TITLE
Collect VAMC & Vet Center Info for Best Bets

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25532]
##  Description
Collect information need to establish Best bets for all 

## Tasks
- [ ] Collect Headline, Text, Keywords and URL for all VAMC & Vet Center Locations
- [ ] Update #25534 with required information for implementation

## Acceptance Criteria
- [ ] Info is available for implementation

**Comment by denisecoveyduc** [comment]
@johnhashva  to talk to Dave Conlon to discuss the strategy. Do we do it now manually or adopt an API strategy.

**Comment by denisecoveyduc** [comment]
This was to collect the necessary information but sounds like the implementation isnt quite the same as we first anticipated. Will handle all steps in #25534.
