### ISSUE TITLE
Store Cypress Test Artifacts for Individual Download

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25551]
# Description
In order to provide a better experience for VFS teams that are using the GitHub Actions to troubleshoot their E2E test failures, we need to provide access to individual test execution video playback and screen shots for each failing test spec.

## Tasks
- [ ] Gather input from FE Tools with regards to a potential solution for storing screen shots and videos from individual test specs in an S3 bucket and linking them to the GHA report on E2E test results for individual download.
- [ ] Consider incorporating Mochawesome Report Generator into the GHA workflow that executes E2E tests. Use this report generation with detailed pass/fail status and relevant artifacts as a way of readily surfacing the information that VFS teams need for troubleshooting tests.
  * The Mochawesome Report Generator has been incorporated into the **cypress** [workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/cypress.yml) in GHA

## Acceptance Criteria
- [ ] FE Tools approves of the method employed to collect artifacts
- [ ] Individual videos for failing tests can be downloaded from GitHub Actions
- [ ] Individual screen shots for failing tests can be downloaded from GitHub Actions.

**Comment by CBonade** [comment]
The update for this is currently in for review.  The updates have been made to send the reports and corresponding failed test videos to the `testing-reports` repository and then link the page back to the current workflow.  There has been some flakiness with the test suite running successfully that has had checks randomly failing while running the initial tests, so attempting to look into those to see why they're being unreliable. 

There's a few suggestions for further research and/or minor improvements after chatting with Eugene about it that we may be able to move to a future ticket:

- Auto deleting files in the testing-reports repo that are older than X days (anywhere between 7 and 30?)
- Moving the link to the existing summary report, and moving the summary report to the cypress workflow instead of the CI workflow.
- Modifying the summary report to use the complete pass/fail data as Mochawesome does, as opposed to only the most recent parallel run that has finished to display the proper number of tests.
- Get rid of the third party reporting action entirely and generate our own summary.

**Comment by pjhill** [comment]
So, on failed runs like [this one](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/994312945), it looks like we're having trouble storing the artifacts from the failed Cypress runners which is throwing a wrench into the report publishing.

**Comment by CBonade** [comment]
I've been looking into a solution for this. My programming brain says there should be an easy way to check if an artifact exists before it's attempted to be downloaded, however I have yet to find a way to do this and team members I've asked additionally are unsure.  In theory, if it failed because of a failed test an artifact would exist and it would not be an issue, however these failures were due to the SIGILL error, which if we went forward and produced a report, would result in an incomplete and/or blank report.  Unfortunately, right now it doesn't seem to distinguish a difference for WHY it failed, other than it just "failed", and the artifact download is conditional based on failure.  I'll keep digging into this, however functionally, I do believe it's producing the correct results in the correct scenarios, it's just way messy in how it communicates that.

**Comment by pjhill** [comment]
Disclaimer, I have not implemented anything in GitHub:
So, there's no way to create more granular error handling? We really only need two branches --
1. The error was the result of a test spec failing, the artifacts are valid, store the artifacts
2. The error was the result of something outside of a spec, the artifacts may not be valid, throw away the run's results

If we can't do this in GHA then perhaps we park this feature / acceptance criteria for a future effort. I know GHA is under active development, and it may be worth revisiting the feature in 6 months to see if there are mechanisms available for more granular error handling.

**Comment by CBonade** [comment]
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context

So here's the current issue

The type of error has to be made available to the workflow.  In the above linked documentation, you can get the status of both a specific step and a whole job.  However, the only possible values for those are `success`, `failure`, `cancelled` or `skipped`.  Whether it's a failed spec, or a `SIGILL` error, we are going to get a `failure` for that step.  This is reiterated on the Cypress official github action docs, however, we are not currently using that. The only other option is if there's a possible way to return a value or custom output back to the workflow from the tests, which I'm happy to look into. 

I would really have thought the upload/download artifact actions would support conditional behavior, but it unfortunately does not appear that it does.

**Comment by CBonade** [comment]
There's been nothing discovered here about a better way to handle failures, however, as we've monitored this longer....and having resolved the regular "SIGILL" and "SIGTRAP" errors that were occurring, I personally feel that having all cases of Cypress failing has been beneficial to us in shutting down some critical issues and I'm not sure we should remove this, unless the plan is to separate it into two separate notification types eventually. If not, we can probably close this out.

**Comment by pjhill** [comment]
@CBonade -- The current prescribed method for teams to retrieve screen shots and videos is to view the Mochawesome report and download them from there, right?

Do we have any documentation describing the process? Is that included in Eugene's GHA guidance?

**Comment by CBonade** [comment]
I have not personally seen any documentation on Confluence that documents the process of how these reports are created nor what a user could expect to see on them.  The only documentation related to it I've found is by Holden here: https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data on how the report is generated in our data repo. I am unfortunately unable to locate Eugene's documentation on Confluence that we were linked that one time to review before the GHA demo.

Aside from that, the Mochawesome report does not house screenshots as far as I've seen, just videos of failed tests only.  I'm happy to take a stab at adding some documentation for the reports to wherever we'd like that to live, if it doesn't exist.

**Comment by CBonade** [comment]
Was notified at EOD today that the s3 bucket has been created, so this will be moving forward in the coming days.

**Comment by pjhill** [comment]
Let's close this ticket and work the documentation of the interpretation of E2E test results and the retrieval of relevant articles under a different ticket.
