### ISSUE TITLE
Investigate Search Result Relevancy Score

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25553]
##  Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Background/Context
_What background information is available to support this work?__

## Tasks
- [x] read search.gov documentation to determine what is impacting relevancy score for a result. 
   - https://search.gov/manual/ranking-factors.html
   - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/technical/about_search_gov_engine.md
- [x] reach out to search.gov

## Acceptance Criteria
- [x] Meeting with Search.gov on Thursday June 17th to identify ways to improve relevancy score

**Comment by denisecoveyduc** [comment]
Meeting with Search.gov on June 17th to identify what next steps and action items are available to us to impact the relevance of results.
