### ISSUE TITLE
Investigate search tool content indexing

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25554]
##  Description
Content from Resources and Support is not appearing in search results as expected. 

The content team raised a search index issue (which we've long known about): The Resources and Support content is simply not surfacing in Search -- even when you search the H1 or an article.  Take Can I be buried in Arlington National Cemetery? as an example.	When we meet with Amani this is going to be one of the most pointed Use Cases we will surface.  Is this an "us" thing -- we just need to tweak our indexing model -- or a "them" thing? (Course, we always have the option to make a Best Bet for every R&S article -- something I am open to doing if absolutely our only path -- but boy, this does not scale)

## Tasks
- [x] Confirm how content is being indexed from search tools via meeting with search.gov - Feb 17th 

## Acceptance Criteria
- [x] We have a clear understanding of how search tool content is being indexed
- [x] Tier 3 (No Socks validation necessary)

**Comment by srsuddath** [comment]
we have reached back out to search.gov to confirm our desired path forward for indexing the R&S content. moving this ticket to validation
