### ISSUE TITLE
Update the width of SideNav to be 1/3 instead of 1/4

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2556]
## Problem Statement
The Pittsburgh VAMC left side nav width needs to be updated to 1/3 instead of 1/4 so that lengthy titles and names can be accommodated. 

## Goal
Consistency with design system
Usability

## Objectives or Key Results this is meant to further
OBJECTIVE 3: Deliver a usable and accessible experience

---
## Tasks
- [ ] Update the width of SideNav to be 1/3 instead of 1/4 

## Acceptance Criteria
- [ ] Width of SideNav is 1/3 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
**WARNING**: This PR will affect the current SideNav and not just the new SideNav. This will likely want to be merged once the new SideNav is going to production.

**Comment by ncksllvn** [comment]
Unless we're pressed on this, I'm not planning to merge this work for this until @kelsonic is back. It carries site-wide impact that I'm not super comfortable with without more context to be absolutely sure.

**Comment by Karak888** [comment]
@kelsonic definitely don't think we want to apply to production until we are given the go-ahead - I am going to put this in the "Current Sprint" column and add awaiting feedback label.

**Comment by kelsonic** [comment]
Agreed 👍

**Comment by MickinSahni** [comment]
Blocked until designs are updated based on research

**Comment by mmiddaugh** [comment]
Hold on this one until design review complete

**Comment by mmiddaugh** [comment]
> WARNING: This PR will affect the current SideNav and not just the new SideNav. This will likely want to be merged once the new SideNav is going to production.

@kelsonic Does your warning from November only apply if this Left Nav had been rolled out globally or is it still relevant if the Left Nav is implemented for VAMC only?

**Comment by kelsonic** [comment]
This was a long time ago -- but it was relevant if the Left Nav was implemented for VAMC only since the template file is used by all other side navs if I remember correctly! 🙂

**Comment by mmiddaugh** [comment]
@kelsonic @rtwell , I am a little confused and hope you two can clarify this for me. 
My assumptions are: 
Left Nav is for VAMc only
Changes made to Left Nav should not affect the rest of the site

Am I missing anything? Are these assumptions true?

**Comment by kelsonic** [comment]
@mmiddaugh both of those assumptions are true! 🙂We do still have other left navs around the site, but they have a different design.

**Comment by mmiddaugh** [comment]
Per conversation with @rtwell , we will come back to wdith after the other style updated have been addressed in Left Nav design updates[#7212](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7212)

**Comment by mmiddaugh** [comment]
Additional notes from discussion today:
Changing the column width will require significant page by page QA to ensure display of main page content is maintained after changing side nav width. 
Particular areas of risk: 

- Top task buttons
- Thumbnails (should be rendering as %size)
- Maps (should be rendering as %size)
