### ISSUE TITLE
NOD: various fixes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25575]
## Description

The Notice of Disagreement form has a few minor issues that need to be fixed

- Fix styling on review & submit page - see https://dsva.slack.com/archives/G016CG5FT6Z/p1622664042027700?thread_ts=1622663006.023500&cid=G016CG5FT6Z
- Update validation error message if user didn't click save - see https://dsva.slack.com/archives/C5AGLBNRK/p1622661769130600
- Dynamically update "go back and add it" link - see https://dsva.slack.com/archives/C5AGLBNRK/p1622662026132100?thread_ts=1622661977.132000&cid=C5AGLBNRK

## Tasks

- [ ] Add lines between issue pages on review & submit
- [ ] Fix validation message
- [ ] Dynamically update go back link

## Definition of done

- [ ] Tasks completed
- [ ] Unit tests passing
