### ISSUE TITLE
NOD: Fix combined issue validation

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25573]
## Description

The Notice of Disagreement form loads contestable issues from an API, but also allows Veterans to enter issues. We need to fix this validation to properly show an error on the review & submit page. This may require multiple fixes, including changes to the form system validation to completely resolve this issue. Changes may need to be made within this PR - https://github.com/department-of-veterans-affairs/vets-website/pull/16431 - if not merged in

Duplicate the problem by:
- Going to the review & submit page
- Unchecking all eligible and added issues.
- Submit the form - you should see the add issues error
- Use the "Finish this request later"
- Reload the "form-saved" page to reset the form
- Return to the review & submit page
- Submit
- Note: All accordions are collapsed with only a general error message stating that there is some invalid information

Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/21252
- https://github.com/department-of-veterans-affairs/vets-website/pull/16431
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/25061

## Tasks

- [ ] Update schema dynamically to properly register form errors before submission
- [ ] Add changes to existing or new PR to error message processing

## Definition of done

- [ ] Accordion headers show a warning icon to help direct Veteran to form issues

**Comment by Mottie** [comment]
- Update schema dynamically to properly register form errors before submission - https://github.com/department-of-veterans-affairs/vets-website/pull/17529
- Additional fix to ensure additional options page is visible when no issues are selected - https://github.com/department-of-veterans-affairs/vets-website/pull/17617

What still needs work is code within the platform form system to properly highlight the accordion header when there's an error. 

<details><summary>Nothing selected error; no accordion highlight</summary>


![Screen Shot 2021-06-16 at 11 00 00 AM](https://user-images.githubusercontent.com/136959/122254357-a98bf180-ce92-11eb-8360-5b513e0cedd1.png)</details>

**Comment by Mottie** [comment]
Update: Added some logic to better handle the interaction between the eligible vs added issues, but error messages are still not properly handled.

Once [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16431) is merged in, we can include the NOD form and show error links inside the submit error alert.

**Comment by Mottie** [comment]
This isn't something that can be fixed without an update to the form system.  We'll go ahead and close this ticket and address it once the aforementioned PR has been merged.
