### ISSUE TITLE
Update Collab Cycle templates for new Slack Workflow

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25581]
## Issue Description
Platform Service Design team has launched the new Slack Workflow. This will change how VFS teams contact Platform Product Support in Slack when they are in need of a Collaboration Cycle Review (and have already created the Github ticket).

## Tasks

- Update the "Steps" section of the following Collab Cycle templates. 
- Remove the line: "VFS: Link to this issue once created in #vfs-platform-support in Slack; tag @vsp-product-support-members." 
- Replace with: "VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.

## Collab Cycle Tickets needing updated:

- [x] [Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+allison0034&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D) - current guidance asks VFS to post in #design channel. This will be no more.
- [x] [Collab Cycle Kickoff](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D)
- [x] [IA Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis%2C+shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review%2C+ia&template=ia-request.md&title=IA+Request+%5BTeam-Name%2C+Feature-Name%5D) - this template should also be updated to have similar Steps as the other templates. DoD is currently at the bottom of the template.
- [x] [Midpoint Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D)
- [x] [Privacy & Security Review](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=f1337%2C+joeniquette&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D) - This should follow the same steps. When VFS team uses the Slack Support tool, Shira (or whoever) will reassign to Joe Niquette and Michael Fleet.
- [x] [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D)
- [x] [Full Accessibility & 508 Office Audit](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+shiragoodman%2C+noahgelman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
peggygannon-patch-2 for sensitive repo PR (privacy and security template)
peggygannon-patch-1 for other

**Comment by peggygannon** [comment]
Hi, @shiragoodman  PRs have been merged. Once changes are reflected in the CC docs/templates, I will close issue.

**Comment by peggygannon** [comment]
This is completed and the updates have been validated on Github.
