### ISSUE TITLE
[VAMC-Tech-Debt] Review and investigate correct location of orphan facilities and associated Facility Health Services

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#25591]
## Story
As a Veteran and web maintainer, multiple facilities need a home in the correct system, and need correctly associated facility health services.

## Goal
Move all orphaned facilities to the correct system or document it for removal. Associate possible health services for review of PAOs. 

## TASK
Review all orphaned facilities in parent CMS systems and associate them to the correct system:
- [x] Investigate and document correct  facility health services
- [x] Associate Facility to correct System save as Draft 
- [x] Inform PAO that facility is in Draft and can be published once health services are validated and 
- [x] Determine if any facility health services are incorrectly associated and move them to the correct facility

## Acceptance Criteria
- [x] All facilities are associated to correct system and initially saved in draft.
- [x] PAO has been informed and facility health services have been provided so they can confirm if they need to be added.
- [x] Answer PAO questions and support
