### ISSUE TITLE
Modify Collaboration Cycle Kickoff Questions

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25597]
## Issue Description
The Collaboration Cycle Kickoff issue template was updated 4/16/2021 to address challenges PMs had in answering the questions correctly from the first release 2/22/2021. The changes have been successful, with the exception of question #5: 

```
5. Will your work include content changes for: (Select all that apply)
   Tools and applications*
   Static pages
   This work doesn’t involve content changes.
*For tools and applications, take into account if any content on static page entry points will need updates.
 Content changes could include: updates to buttons, links, labels, headings, reordering content, or adding error messages.
```
PMs have consistently chosen option 3 ("This work doesn't involve content changes.") which is problematic for 2 reasons:

1. They are not acknowledging whether their product impacts tools and application and/or static pages. This piece of information is essential to putting the product on the right track per our [flow.](https://drive.google.com/file/d/1zEKhfyYknv5sAp-Ba3vWdn1WTEA8AyIJ/view)
2. They are selecting that their product does not involve content changes when it most likely does. This shows that PMs do not have a clear understanding of what content consists of. 

**Examples:**
[Search & Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25596)
[Public Websites ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25567)
[Facilities ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24690)

HMW modify the template to ensure PMs specify whether their product impacts tools and application and/or static pages?

HMW modify the template so PMs acknowledge that their product will most likely include content changes?

Ensure internal processes, scripts and flow are updated appropriately per the changes. Follow up with Clarence (CMS) to ensure he is informed of changes.

**Solution**
Update question number 5 to:
Will your work involve changes to
- Tools and applications
- Static pages
- Both
*For tools and applications, take into account if any static page entry points will need updates.

Add another question: 

Will your work include 
- New content
- Changes to existing content

--------

## 2nd Issue Description
VSP needs to have a way to report out on QASP metrics. Product Support is responsible for the metric, "Percent of VA.gov products with an identified VHA/VBA/NCA/VACO business owner." In order to do this, we will add the following question to our Collab Cycle Kickoff:
```
10. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

```

## Tasks
- [x] Update Collaboration Cycle Kickoff template with new questions 
- [x] Update Getting Started with Collaboration Cycle document with new questions

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
Changes are live and validated in the Collaboration Cycle kickoff template and documentation.

**Comment by shiragoodman** [comment]
thanks @peggygannon !
