### ISSUE TITLE
Front end should not expect images on VA Medical Center system main page, Locations page and Stories page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25599]
## Issue Description
Images are not required on stories, but the template assumes there is an image and builds the img tag without having an image src, alt and title with no data.  This results in faulty html which breaks the build. 

We can get around this for now by asking the editor to add an image, but it would be good to resolve this template logic to not include an image unless it has a src and an alt.

Two broken links were reported in the build on 6/2/2021:

- houston-health-care/stories :
`<img class="news-img" src alt title width height>`

- houston-health-care/stories/new-va-clinic-open-in-ft-bend-county 
`<img class="story-detail-img vads-u-margin-bottom--2p5" src alt title width="100%">`

[Slack link](https://dsva.slack.com/archives/C0MQ281DJ/p1622655359132400)

## Tasks
**Applies to VA Medical Center system main page, Locations page and Stories page** 
- [ ] Add logic to code to prevent rendering of image tag if there is no image path
- [ ] Create a reusable liquid template for images that handles the AC

## Acceptance Criteria
- [ ] Front end does not build an img tag without having an image `src` and `alt` ~~and title~~ on **VA Medical Center system main, Locations and Stories pages**. The `alt` attribute **can** be an empty string if the image is purely decorative or adds no context to the page. The rendered output for a decorative image with empty alt tag should look like this example:
```html
<img src="picture.png" alt="">
```

**Comment by mchelen-gov** [comment]
a11y scan failure: https://dsva.slack.com/archives/C01RAS1KAQK/p1623773915041900

**Comment by swirtSJW** [comment]
This same issue is happening on VAMCS locations pages. 
![image](https://user-images.githubusercontent.com/5752113/122092740-45a4f280-cdd8-11eb-801a-4fc84c7a5c0d.png)

DIscussed this on the content-release engineering call.   This is triggering both broken link issues  AND 508 issues 

https://dsva.slack.com/archives/C0MQ281DJ/p1623773435233000

**Comment by swirtSJW** [comment]
Here is the 508 issue
![image](https://user-images.githubusercontent.com/5752113/122094925-b9e09580-cdda-11eb-83ed-34db23aae244.png)

**Comment by mpelzsherman** [comment]
To clarify the AC for the system home page: the Main image is required, but the Location and Story page thumbnails are optional:

![VA_Pittsburgh_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/80267/122430589-bc212c00-cf61-11eb-93b6-e893a830f682.png)
