### ISSUE TITLE
[AWS / IAM] Update Service Account User for Operations Team

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#25590]
## Issue Description
We want to be sure that naming conventions are clear for service accounts that the Infrastructure Team uses. There is an account called "dsva-ecr-service-account" which does more than manage ECR, which means the name isn't quite clear. 

---
## Tasks
- [x] Rename dsva-ecr-service-account to something more general
- [x] All areas of usage have been identified and updated

## Acceptance Criteria
- [x] ECR service account has been renamed to make it easier to understand what it's used for

**Comment by jhouse-solvd** [comment]
@jbritt1 - I see you linked a PR above. Is there any add'l work left to do here? Could you help me check off any tasks and update the AC if there remains work to do? Thank you!

**Comment by jbritt1** [comment]
> @jbritt1 - I see you linked a PR above. Is there any add'l work left to do here? Could you help me check off any tasks and update the AC if there remains work to do? Thank you!

That link is just a comment of me trying to remember which one it was lol. I _think_ this is still needed.

**Comment by jhouse-solvd** [comment]
We should be sure to understand the impact of this change. It might cause other things to "break".

**Comment by ph-One** [comment]
A quick `grep` across _most_ of our repos found these results:

```
devops/terraform/environments/global/iam_gha_resources.tf:resource "aws_iam_user" "dsva-ecr-service-account" {
devops/terraform/environments/global/iam_gha_resources.tf:  name = "dsva-ecr-service-account"
devops/terraform/environments/global/iam_gha_resources.tf:  user       = aws_iam_user.dsva-ecr-service-account.name
devops/utilities/deactivate-expired-accesskeys.py:exception_users = ["<root_account>","appeals-circleci","appeals-travis","dsva-appeals-datadog-aws-integration","dsva-appeals-sentry-prod", "dsva-ecr-service-account","dsva-vetsgov-cloudwatch-exporter","jenkins",
```

**Comment by jbritt1** [comment]
It appears we can do this much easier than previously thought. Turns out there is a way to change an IAM username without having to delete / recreate, the option just doesn't exist in the console. By using the CLI to change a username, it appears we can keep all the policy attachments and access keypair of the service account as well: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_manage.html#id_users_renaming. Should I grab this today as a log-hanging fruit @ph-One?
