### ISSUE TITLE
Provide clarity on Design Intent output

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25602]
## Issue Description
The Design Intent touchpoint was updated on 5/3/2021. Platform reviewers will provide feedback to VFS teams no later than the following business day after the Design Intent meeting. However, the Design Intent touchpoint documentation does not specify who VFS teams can expect to receive feedback from. Feedback will only be provided by IA, Design and Accessibility. Content and QA feedback will not be given as it is too early in the development process to be applicable.

---
## Tasks
- [x] Update the [Design Intent touchpoint](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-design-intent.md) to specify what practice areas will provide feedback.
- [x] Update the [Design Intent issue template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+allison0034&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D)to state the same.
- [x] Since we're no longer providing content feedback at Design Intent, remove this question from the template: *Has your team met with the Sitewide Content team for content support?*
- [x]  Add the Sitewide Content question to the Midpoint Review template.
- [x] Update Design Intent script to remove reference about provide content feedback/concerns

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
Updates are live and validated in the Design Intent template and touchpoint documentation.
