### ISSUE TITLE
[Debt Letters] update debt letters mock data

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#25600]
## Issue Description

if `isVAProfileServiceConfigured` is false and `VBMSError` is false we should be rending mock data

---
## Tasks
- [ ] debt letters should display the correct mock data on localhost when isVAProfileServiceConfigured false

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
