### ISSUE TITLE
Change hardcoded Leadership menu link

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25606]
## Issue Description
New URLs, menu items and redirects went live 6.2.21 for Pittsburgh but CMS was unable to move `/leadership` to `/about-us/leadership/` because of the special handling of the Leadership menu item and URL in the person_profile liquid template.

Links will break on person profile page

### Possible solutions (per Kevin Walsh)
- Change that hardcoded menu link to /about-us/leadership/ , with a feature flag OR 
- some rearchitecting to make it more dynamic based on the actual leadership page for the system (maybe based on the staff profile’s URL?) OR 
- a change to the way these menus work, so that the active trail can be shown instead of just the Leadership link, which Mikki has talked about in other contexts.

Once the FE has made a change, CMS will need to change to the automated alias given for new Leadership pages that get added 

[CMS epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5500)
---
## Tasks
- [ ] Determine best approach for changing hardcoded Leadership menu link 

## Acceptance Criteria
- [ ] CMS team can update existing Leadership pages URLs to start using /about-us/leadership/
- [ ] Individual staff profile pages will retain -health-care/staff-profiles/ url

## Dev notes
- will prefer to get data from CMS and use dynamic approach rather than hard coding

**Comment by mmiddaugh** [comment]
Blocking this, pending CMS dependenices
