### ISSUE TITLE
Move existing Collaboration Cycle documentation to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25617]
## Issue Description
Collaboration Cycle documentation currently exists on github, however Platform teams have been asked to begin migrating documentation that is ready over to the new Platform Website (Confluence). 

Guidance to be moved:

 - [x] The Collaboration Cycle process (intro paragraphs on README should be moved to the [main page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/))
- [x] Resources
- [x]  Contact us
- [x] Change history
- [x]  Getting started with the Collaboration Cycle 
- [x] Touchpoint parent page
- [x] All touchpoint pages

All existing Collab Cycle docs should be moved to their own page, accessible from the left nav. Similar grouping should apply. 

Left Nav:
![image](https://user-images.githubusercontent.com/71330581/126390247-13728631-79a6-494a-858d-ac54baa933e5.png)

---
## Tasks
- [x] Pages that are live in Platform Website must be deprecated in GitHub.
- [x] Github Issue templates will need to be updated to ensure all links point to the appropriate page within Platform Website. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
@shiragoodman can you clarify if  we should be moving over the individual practice area guidance docs that we currently linked to (under Practice Areas supported by the Collaboration Cycle) in [this CC doc]( https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle)?

**Comment by shiragoodman** [comment]
@peggygannon no, we won't be moving those. thanks for checking!

**Comment by shiragoodman** [comment]
@peggygannon @allison0034 something else we need to do (and forgive me for just remembering this now) is that we need to deprecate the pages in github that have been moved over to Platform Website. I believe instructions for this were in the training C&IA team did. We can discuss later today at the CC Initiative meeting.

**Comment by peggygannon** [comment]
reopening ticket as we still need to update links in our Github templates.
