### ISSUE TITLE
Revisit alert for Vet Center call center

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25625]
## Issue Description

Design feedback during Vet Center staging review:
- Confusion is introduced by the text and visual display of several different phone numbers  
- If you keep the yellow alert, please put it in the alert box style. Background only alerts are for immediate feedback - although the alert box style is not mobile friendly. 

<details>
<summary> Screenshot from Vet Center staging review design feedback #24791 </summary>

![image](https://user-images.githubusercontent.com/55411834/120709367-0098cc00-c47a-11eb-838e-950e9fc15804.png)\

</details>

As noted in the comments,  

- The language in the facility operating status alert comes from content entered into CMS. The current wording has been vetted by their leadership and will need review before it can be changed.
- Likewise, the "non-traditional hours" statement will soon be populated by data from Lighthouse and not within our immediate control to change.
- The recommended alert style is closely associated with the suicide prevention alert
- The preference is for Veterans to call the Vet Center (rather than calling the Call Center) during business hours so we'll want to evaluate the level of prominence (visually and text) for this message, making sure it doesn't compete with the Vet Center phone number

---
## Tasks
- [x] Work on "nontraditional hours" language with content team
- [x] Confirm that there is a warm handoff  to Veterans Crisis Liner when they call after hours line (Chantae will know who we can validate with)
- [x] Based on Call center, consider options for the Vet Center call center alert box and language 

## Acceptance Criteria

Link to updated alert in [UXPin here](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/140708775/documentation/sitemap?mode=i) [Nick O]

- [x] Spec for engineering for 
       - the "non-traditional hours" statement (to be hard coded in front end) 
       - Call Center alert box
- [x] The Vet Center call center alert box helps Veterans know how to talk to someone after hours. 
- [ ] Veterans understand they can call and speak to someone at the local Vet Center during normal business hours

**Comment by mmiddaugh** [comment]
Per Jessica on 6/15:
Yes the preference is to call the vet center number and after hours all calls are to be automatically forwarded to the call center. We confirmed that with our operations team. The call center does more than warm hand offs to the crisis line though if someone is actively suicidal they will. The crisis line will also refer to our Call Center for those who may benefit from our services. 

 

Thanks for these questions. Yes the preference is to call the vet center number and after hours all calls are to be automatically forwarded to the call center. We confirmed that with our operations team. The call center does more than warm hand offs to the crisis line though if someone is actively suicidal they will. The crisis line will also refer to our Call Center for those who may benefit from our services.

**Comment by mmiddaugh** [comment]
The WAR VETS label for the phone will be removed from the content based on feedback from Jessica. they have been moving away from this label because it could imply that they only serve combat Veterans.

**Comment by nicko-amida** [comment]
@mmiddaugh Here's an [update in UXPin](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/140708775/simulate/sitemap?mode=i) based on some content team input.

![image](https://user-images.githubusercontent.com/81988788/127914354-90338bf4-f917-40bb-9e28-7ba91bcde4af.png)

**Comment by mmiddaugh** [comment]
@nicko-amida we'll still need the phone number in this alert

**Comment by nicko-amida** [comment]
@mmiddaugh Updated the [UXPin](https://app.uxpin.com/edit/8789806#?id_page=140708775) to include the Vet Center call center number:
![image](https://user-images.githubusercontent.com/81988788/129041990-d130d21f-1837-475a-b3e1-ca9d38d396a2.png)

**Comment by nicko-amida** [comment]
@mmiddaugh @davidconlon Got a few [more options](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/140708775/simulate/sitemap?mode=i) that I'm going to run by Content - am including the number, and trying to eliminate passive voice.

**Comment by nicko-amida** [comment]
@mmiddaugh After a second round of content team input:
![image](https://user-images.githubusercontent.com/81988788/129572582-d9368554-1599-469e-9e08-cdb9169b7334.png)
I'm fine closing this issue if this looks good.
