### ISSUE TITLE
Mapping Environments to Allow MPI Test Userdata

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25698]
## Background
We need to map **dev.va.gov** to be able to use MPI data (to test with test users) since we have a line of business who is anxious to test the 686 feature in PREPROD (because of RBPS).

## Considerations
I do not think this needs to be done forever and ever and might only need to be changed in order to complete testing (1-2 weeks)...I am sure other teams might be impacted if that were the case.  

**Charley Stran's original email on our behalf:**
_"Hey BGS Team,
We have been working through some integrations and are having some issues matching up data from BGS, MPI, and VBMS. We have listing of which BGS env’s match to which VBMS envs, but we are missing on how BGS maps to MPI. I am not sure if this is the right list of folks to help us map these environments, but hopefully we can get directed to the right folks if not..."_

**BGS's Response:**
[BGS] -> [MPI]
DEVL -> DEV
WEBTEST -> DEV(IDEV)
LINKTEST -> SQA
PRE-PROD -> PRE-PROD
PROD -> PROD

**Per Charley Stran:**
_"This is the info needed to map the envs. I think we should be set aside from whatever DevOps work is needed to get these matched up. The one thing to note is the VBMS only requires mutual SSL verification in preProd and Prod. So if we do not point an environment to whatever maps to VBMS PreProd, then production will be the only env that we are testing and verifying the VBMS Certs."_

## Reproduced by
- User **38** from MVI staging users (Pauline Foster) has dependents and a VA file number in staging and can access the 686 but in dev.va.gov her dependents can not be found and the VA file number check blocks access.

## Tasks
- [ ] Find a user and obtain their PREPROD info (Linda/Don Moses might be able to help)
- [ ] ...
- [ ] Adjust mappings so that STAGING/LINKTEST test users can be used in PREPROD

## Acceptance Criteria
- [ ] Determine a plan for next steps

### Future AC
- [ ] A user that works in staging can also work in dev.va.gov with the same information

**Comment by jhouse-solvd** [comment]
@jason-gcio - Can you explain a bit more what it means to map environments in this case? What is the desired outcome of this ticket?

**Comment by jason-gcio** [comment]
One of the lines of business we work with wants to test the 686 in PRE-PROD but any users we create(d) in staging MPI don't work (the VA file numbers don't match up) and we can't test.  We understand that dev.va.gov maps to PRE-PROD and we need to get the connection in place to allow for our test users to be accessible.

**Comment by jhouse-solvd** [comment]
Discussing this with Ops and other platform teams to understand the best path forward here. 

@joeniquette - Can you take a look at Jason's last comment, and let me know if you have some understanding/guidance on the best way to accomplish this?

**Comment by jason-gcio** [comment]
@jhouse-solvd / @joeniquette - let me know if my last comment makes sense, I can hopefully help clarify, but @kathleencrawford is also back in case I am off.

**Comment by joeniquette** [comment]
Are you simply asking for the mapping of the vets-api environments to BGS and MPI? As in what are they called so we can ensure when an account is created in one environment it can be found? If yes, @bosawt has the most experience in the calls to BGS from the Identity team but I'm not sure we've mapped all of this out. If not I'm willing to help.

Trevor please add anything additional you know about. @jason-gcio please let me know if I am understanding you questions correctly.

**Comment by bosawt** [comment]
I'm a little unclear if the question is a request for `vets-api` to change settings, or for MPI to update their test stack. From the perspective of `vets-api` here are a couple things that could be affecting MPI calls:
- In `settings.yml`, we define the URL that our interaction with the MPI service uses. I'm not sure what that points to on dev.va.gov, but it's possible that's pointing to a different test environment than expected
- Do we know if dev.va.gov uses mocked data or not? For example, here is the mocked data for the Pauline Foster test user referred to above: https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/mvi/profile/796330625.yml . It's possible we're using that mocked data instead of querying MPI directly

**Comment by jason-gcio** [comment]
We can reach out to OIT to help as well ... @kathleencrawford let's chat and see what else we can describe?

**Comment by jhouse-solvd** [comment]
From the ops perspective, we are not actively working on this, but if/when there are clear tasks for us to perform, we'll gladly work those into an upcoming sprint.

**Comment by jason-gcio** [comment]
@bosawt - we were hoping to find out if dev is mocked or not, but based on the `settings.yml` file, it appears that it probably is. 🤷 Perhaps we just need to create a similar file to the one you shared above and ensure that the correct participant ID is in place along with the other test users we have in mind.  

There are a lot of ID's in this file that we do not fully understand though.

We are going to create one and see if it works.  If it does, we will go from there.

If this doesn't work, we will circle back and see if we can find another solution.

CC: @joeniquette, @jhouse-solvd, @kathleencrawford

**Comment by bosawt** [comment]
> @bosawt - we were hoping to find out if dev is mocked or not, but based on the `settings.yml` file, it appears that it probably is. 🤷 Perhaps we just need to create a similar file to the one you shared above and ensure that the correct participant ID is in place along with the other test users we have in mind.
> 
> There are a lot of ID's in this file that we do not fully understand though.
> 
> We are going to create one and see if it works. If it does, we will go from there.
> 
> If this doesn't work, we will circle back and see if we can find another solution.
> 
> CC: @joeniquette, @jhouse-solvd, @kathleencrawford

Let me know if you need any help interpreting any IDs in an MPI response. This file describes a bunch of REGEX that we use to parse for each type of ID, so might give you a hint of certain ones: https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/identity/parsers/gc_ids_constants.rb

**Comment by bosawt** [comment]
By the way, @jason-gcio, I just logged in on `dev.va.gov` and confirmed from this Grafana dashboard that we hit the MPI Development stack: http://grafana.vfs.va.gov/d/UYI5c1oGk/mpi?orgId=1&var-env=Prometheus%20(Development)&from=now-5m&to=now 
So it does look like we make real calls to MPI on dev.va.gov stack.

**Comment by jason-gcio** [comment]
> By the way, @jason-gcio, I just logged in on `dev.va.gov` and confirmed from this Grafana dashboard that we hit the MPI Development stack: http://grafana.vfs.va.gov/d/UYI5c1oGk/mpi?orgId=1&var-env=Prometheus%20(Development)&from=now-5m&to=now
> So it does look like we make real calls to MPI on dev.va.gov stack.

Ok great - I noticed that users behave differently in staging vs dev...in dev, I can't get them past the VA file number check.  For example, if I try to log Pauline in (User 38) to dev.va.gov, our feature does not see her VA file number, but it works in staging.

**Comment by jason-gcio** [comment]
If you want, we could jump on a screenshare and I can show exactly what we are seeing...just let me know

**Comment by kathleencrawford** [comment]
Update 07/06/2021 - sent an email request to BGS to confirm a test user's PID in PreProd.  Also asked Trevor for help with submitting a request to the IM team to update a user's PID in DEV.

**Comment by kathleencrawford** [comment]
Update 07/13/2021 - Trevor has assisted us in changing the PID for one of our test users.  It could take up to 24 hours to take effect due to caching.

**Comment by jason-gcio** [comment]
Waiting for IAM to adjust values in iDev
