### ISSUE TITLE
[Design][UI] Check-in Poster

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25695]
## User Story
- As a Veteran, I need to know that I can check-in on my phone. I need to see a poster in the waiting areas letting me know how to start the digital check-in process.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
Create check-in poster. This version of the poster will be utilized within the MVP usability test.

[COVID posters](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/visual-collateral/README.md) for reference.

## Tasks
- [x] Create poster in Illustrator.

## Acceptance Criteria
- [x] Review poster with the team (particularly product)
- [x] ~Add poster to the UXPin prototype for the MVP usability test.~ No longer utilizing UXPin, so just be ready to share the PDF during MVP usability testing.

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Attached is a draft poster that I created (based upon Martha's COVID poster), so I could start to put the prototype for the usability test together. I'm not sure if it is too close to the COVID poster. Where are the COVID poster hung? Do you know? From the content, it looks like they are hung outside? If that is the case, then it might be ok. The posters won't exist in the same place. I thought it might help as you were finalizing wording. I'll send a draft out to the check-in-experience channel once I get your content suggestions.

[https://app.zenhub.com/files/133843125/7e85022c-a4a2-47b2-8217-391b1c2f3f4c/download](https://app.zenhub.com/files/133843125/7e85022c-a4a2-47b2-8217-391b1c2f3f4c/download)
