### ISSUE TITLE
[Research] MVP Check-in Usability Study Assets

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25693]
## User Story
- As designer, I need to create a prototype to utilize for our usability test.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/conversation-guide.md)

## Description
All assets (prototypes, designs, spreadsheet for observer notes) needed to run the user research session will be completed by the end of this ticket.

## Tasks
- [x] Create UXPin prototype

## Acceptance Criteria
- [x] Publish assets to final location (UXPin, Mural, etc.)
- [x] Review assets with the team (particularly product)

**Comment by kristenmcconnell** [comment]
Changing to an experience utilizing...

1. screensharing the poster
2. using Twilio for the texting experience
3. using staging for the rest

**Comment by kristenmcconnell** [comment]
Worked with Julia Snyder to get the Twilio portion of the test set-up.

**Comment by kristenmcconnell** [comment]
Reviewed what @mdewey created in staging. Creating the following ticket as a result: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25938
