### ISSUE TITLE
Create new COE message state for pending form; Investigate data sources for users' service history

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#25718]
### Background
Per COE status call on 6/4, there is a business case for pending form submissions. We'll need to notify the user on the 26-1880 intro screen if their submission is still in review. 

We need to determine where a user's service history pre-populates from. We should identify the ultimate source of truth for this data, if possible. 

### Tasks
- [x] Make text change to loan options selection
- [x] Research data sources for service history
- [x] Document and share finding of data sources
- [x] Create new form state for pending submissions

### Acceptance criteria
- [x] List of data sources for service history info documented and shared
- [x] Prototype updated

**Comment by sporeboy** [comment]
Used 10-10EZ pattern for pending state submissions: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139445110

**Comment by sporeboy** [comment]
Implemented pending state on standalone COE screen: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139575305

**Comment by sporeboy** [comment]
I am not sure of data sources for biographical, contact or service info. I found some possibilities: 
- VET360_BSM
- VADIR (Seems to include contact info)
- DEERS (Disabilities)

We'll likely need developers to continue the search.
