### ISSUE TITLE
[FE] Create clickable Protoype on Staging 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#25732]
## User Story

As a user, I should be able to preview the check-in experience on staging.va.gov

## Related Documentation

- [UI to build](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/kaVYLYP/play)

## Description

For UTA testing, we want to use staging. Build the pages and flow for the above UX.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Add pages and routes
- [ ] Add content 
- [x] Add buttons to simulate flow
- [x] enable in staging
- [x] Pass token through the process
- [x] Create e2e tests
- [x] add unit tests

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
