### ISSUE TITLE
Collaboration Cycle Kickoff [Caregivers, Improve File Upload Error Messaging]

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25747]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [ ] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [ ] VFS: Attach any available artifacts.
- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)
- Link to wireframes, mockups, or prototypes
- Any other artifacts you have so far
[(Form system - upload document error message #25320](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25320)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [ ] New
- [X] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [ ] Yes
- [X] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [ ] Yes
- [X] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work include content changes for: (Select all that apply)
- [x] Tools and applications*
- [ ] Static pages
- [ ] This work doesn’t involve content changes.

*For tools and applications, take into account if any content on static page entry points will need updates.

Content changes could include: updates to buttons, links, labels, headings, reordering content, or adding error messages.

### 6. Are you making a change to the user flow?
- [ ] Yes
- [X] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 7. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [X] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 8. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [x] Yes
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 9. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [X] No

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by tchrisdyer** [comment]
**Background:**
As part of the **Sign as a Representative** enhancement for the online Caregivers Application (VSA Form 10-10CG), we allow users to upload legal documents proving they can act as the representative, such as Power of Attorney (POA). We are currently investigating an intermittent failure that occurs when uploading files as part of the caregiver application. These failures occur intermittently about 10 to 20% of the time. We recently reduced the file size limit in our frontend and backend from 25 MB to 10 MB, but it did not resolve the issue. This is an ongoing issue.

Therefore, in the short-term, we are recommending some messaging changes to the message the appears when the file upload fails. This component is a platform level comment.

**Comment by shiragoodman** [comment]
Hi @tchrisdyer. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: (delete Post Launch if there are no touchpoints in this area)

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process: (select all that apply)

- Design
- Content
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

PS: Thank you for the additional background information! This was very helpful. In a perfect world, Product Outlines include this information, but not always for iterations.

**Comment by shiragoodman** [comment]
Also, regarding an Analytics Request. I'm surprised theres no tracking built in to the Caregivers form. I would double check.

**Comment by tchrisdyer** [comment]
@shiragoodman Sorry for the confusion. The HCA does have Analytics tracking in both Google Analytics and Domo. We just are not adding any additional tracking for this new question beyond what is already there. I've updated the answer to Question #8 to "Yes". Let me know if that changes any of the next steps.

**Comment by shiragoodman** [comment]
@tchrisdyer i had assumed this was the case, so I already responded appropriately. Your recommended touchpoints remain the same. Thanks!
