### ISSUE TITLE
[DESIGN] FL doesn't require Community Care selection from dropdown

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25754]
## What happened?
After selecting facility type = "Community providers (in VA's network)", user can type free text into service type and execute search. 
Screen reader users are not made aware of typeahead field

[Loom recording](https://www.loom.com/share/4b6ec3f59fce4185a88c546c20e7ad34)

## Steps to Reproduce
1. Enter postal code or city, state
2. Select "Community providers (in VA's network)" for facility type
3. Enter free text (such as symptom or "can't walk") as service type 
4. Click "Search"
5. Observe search executes with no results found. 

## Desired behavior
When facility type = "Community providers (in VA's network)", user should be required to select a service type from drop down box

## Tasks
**Scope: Although the usability and functionality of the service type box is quirky and unfriendly, this issue is targeted at the lowest hanging fruit improvements which can be made to immediately benefit users. A complete redesign of this field will be needed in the future.** 
- [ ] Recommend changes to help users understand a dropdown box will be revealed once they begin typing
- [ ] Determine appropriate error message to be displayed if user executes search free text in service type box (rather than selecting from the dropdown)
- [ ] Define aria text to support screen reader understanding of service type field functionality 
- [ ] Seek accessibility input on these recommendations

**Comment by nicko-amida** [comment]
Recommendations are in the [UXPin documentation](https://preview.uxpin.com/602167f0ca1beccf4bdf706e04b3a5bd34c78e94#/pages/139907964/documentation/no-panels?mode=i), and includes screen reader/aria messaging and error messaging notes.
