### ISSUE TITLE
[DESIGN] Update accessibility for "Get Directions" link on Facility Locator 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25759]
## User story
As a screen reader user, I need to hear a way to get directions to a place that I need to visit physically. When I leave the page, I need to know where I am going because I do not have the visual cues. 

## Issue description
During screen reader usability sessions, "Get directions" was not audible or decipherable for (3) JAWS screen reader users. "Get directions" does not provide key information on _where_ directions will be procured from and that it opens a new tab. The latter can be particularly frustrating if unanticipated by assistive tech users.

From ##20432: The omission of a space within the alt-text causes the link description to be somewhat garbled potentially confusing screen reader users. The alt text renders "Directionsto facility."

## Details

<details>
<summary> Accessibility guidance </summary> 

- Limit the use of links or buttons that open new windows or tabs within Web content, since they can be disorienting for people, especially those who have difficulty perceiving visual content
- Name of the location is more screen reader specific for folks who navigate using the links list.  If every link says “Directions on Google maps“, it won’t be very useful. 
</details>

**Reference:** [Facility Locator short-term recommendations #7](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/screenreader-usability-study/research-findings.md#on-facility-locator---short-term)

---

## Tasks
- [x] Work with accessibility team to identify ways to improve the "Get Directions" announcement 

(Link to UXPin mockup: [Directions on Google Maps mockup](https://preview.uxpin.com/86d62dbd30d510360fcc3d021544cc24e3422880#/pages/142520031/documentation/no-panels?mode=i) - Nick)

---

## Acceptance Criteria

- [x] "Get directions" is labeled as "Directions on Google Maps" 
- [ ] Clicking on "Directions on Google Maps" does not open a new tab 
- [ ] Screen reader announcement of "Directions on Google Maps" is clear and specific, (i.e. includes Facility name)

### Mockup
Link to UXPin mockup: [Directions on Google Maps mockup](https://preview.uxpin.com/86d62dbd30d510360fcc3d021544cc24e3422880#/pages/142520031/documentation/no-panels?mode=i) - Nick

**Comment by mmiddaugh** [comment]
Thanks, Nick! I will create [a new issue for FE implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30778) and close this one.
