### ISSUE TITLE
(WIP) Past clinic check error message

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25756]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Continuation of #22859

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] CONTENT - Content matches the [copy doc](#) 
- [ ] DESIGN - Designs match the specs (copy is FPO) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laurenernest** [comment]
will cover all scenarios in #22859. closing as dupe
