### ISSUE TITLE
Create communication plan for VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25768]
## Issue Description
We are almost ready to launch our VA.gov Experience Standards and our new process for communicating issues to VFS teams. Now we need to come up with a plan for how we will notify these changes to VFS teams.

**Edit 7/19:** This ticket originally included launch of VA.gov Standards AND new Staging Review process (AKA "new process for communicating issues to VFS teams"). However, the release of the new Staging Review process will be postponed until the pilot is complete and the team has been able to make [post-pilot changes.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25762)

Instead, this ticket will include communication plan for the following changes:

1. Collaboration Cycle documentation has been moved to Platform Website
2. Launch of VA.gov Experience Standards
   - [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
3. WCAG 2.1 Changes
   - Updated [Accessibility Staging Review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc
   - Deck 1: New success criteria
   - Deck 2: impacts to foundational accessibility testing
   - recording of Decision Tools training
4. Accessibility Test Cases in TestRail
   - [How To: Adding Accessibility Test Cases in TestRail](https://depo-platform-documentation.scrollhelp.site/test-release/How-To:-Adding-Accessibility-Test-Cases-in-TestRail.1601307071.html)
   - Artifacts supporting example project (Decision Tools)

## Tasks:
- [x] Guidance reflective of the above has been written for the following:
   - [x] Slack announcement
      - abbreviated version of Change Log post to be shared on #vfs-all-teams, #vfs-platform-support and other channels as needed
   - [x] Change Log post
      - Change Log will be moved from GitHub to Platform Website via ticket #25617. 
   - [x] Team of Teams slide (@shiragoodman)
   - [x] Platform Newsletter article (submitted 8/3/2021)

## Acceptance Criteria:
- [x] VFS teams have been notified of Collab Cycle guidance being moved to Platform Website
- [x] VFS teams have been made aware of the VA.gov Experience Standards
- [x] VFS teams have been introduced to WCAG 2.1 and how Collab Cycle, Staging Review and accessibility will be impacted
- [x] VFS teams have been introduced to the new accessibility test cases in Test Rail and how to use/run them
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
collaborate with Rachael on messaging

**Comment by shiragoodman** [comment]
@peggygannon @allison0034 please be sure to keep me posted on progress/status of ticket #25617 as it is a blocker for this ticket. Thanks!

**Comment by shiragoodman** [comment]
Draft Change Log post can be found here: https://vfs.atlassian.net/wiki/spaces/~500379196/pages/1765114056/Change+Log+Post+draft.

**Comment by peggygannon** [comment]
@shiragoodman I've sent you the link to the updated change log post via Confluence.
