### ISSUE TITLE
Staging Review VAOS - Homepage Refresh

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25779]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] Platform: Schedule meeting with Platform reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] Platform: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to Platform feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/homepage-refresh/homepage-refresh-initiative-2021.md)
- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
  - https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
-  Staging test-user information (if applicable)
   - [Judy](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md)
-  ~Link to content brief (if applicable)~
-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link)
   - [GH appointment details copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/homepage-refresh/homepage-refresh-release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
  - #24686
- Link to your ~[Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and~ [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
  - #24686
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail Platform accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
  - #24020
  - #24021
- List of known issues (with links to tickets when applicable)
  - #24894

## Meeting attendees from requesting team
- Product Manager (required): Lauren Ernest
- OCTO-DE Product lead (recommended): Lauren Alexanderson
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Jeff Balboni, Peter Russo
- VFS Content, IA, accessibility, and QA specialists (if applicable): Peggy, Trevor, Noah

## Scheduling
What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **date/time**
- 6/17 1:30pm 
- 6/22 11:00am
- 6/24 1:30pm 

Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @laurenernest  - Staging Review is scheduled for 6/22 at 11am ET

**Comment by peggygannon** [comment]
Hello! @laurenernest @outerpress 

I'm starting my VAOS homepage refresh staging review,  and I don't see any of the content  recommendations I've provided earlier on staging. 

I don't want to re-submit content recommendations that you've decided to not implement.  So can you let me know in the these tickets below if there are recommendations I've made earlier that you're not incorporating? Thank you. 
 
[VAOS refresh post feedback](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/23018)
[VAOS direct schedule](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/25326)

**Comment by laurenernest** [comment]
We'll be implementing just about all of the recommendations. Open question for one of them in post feedback. Most hasn't gone through dev yet, but i'm going to check on the items I thought we'd already changed. 

The empty states is one of the outstanding items though.

**Comment by pjhill** [comment]
Thanks so much for uploading the test scripts used for QA testing -- [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24686). The test scripts look pretty thorough, and thanks for providing some execution records as well!

I see that at least one defect was opened with regards to a "confusing modal". Is there any kind of output that we are able to review regarding a summary of the defects discovered by these scripts and their resolutions?

**Comment by laurenernest** [comment]
@pjhill Apologies. I've added the list of defects here https://github.com/department-of-veterans-affairs/va.gov-team/issues/24686#issuecomment-866068450

**Comment by laurenernest** [comment]
Launched to 100% on 7/20/21
