### ISSUE TITLE
Add VA.gov Experience Standards to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25771]
## Issue Description
We have begun QA/usability testing of the VA.gov Experience Standards .The VA.gov Experience Standards are ready to be added to the Collaboration Cycle section of Platform Website.

---
## Tasks
- [ ] Platform Product Support team watch[ C&IA team training](https://dsva.slack.com/archives/CJRQ85PQB/p1623690980289100) on Platform Website
   - [ ] Mikki
   - [x] Allison
   - [x] Peggy
   - [X] Shira
- [ ] Read[ Platform Website Guidelines ](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines)
   - [ ] Mikki
   - [x] Allison
   - [x] Peggy
   - [ ] Shira
-  [x] Create page for VA.gov Experience Standards on Platform Website - https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/
 - [x] Upload the standards in a table format (@allison0034 )
 - Category Number, Category Standard Number,	 Standard, Issue, WCAG Reference, PA labels, Severity

## Acceptance Criteria
- [ ] VA.gov Experience Standards are located and accessible in the Collaboration Cycle section of the VA.gov Platform Website
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
@shiragoodman  Platform Website page for VA.gov Experience Standards is located here: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html

**Comment by shiragoodman** [comment]
@1Copenut  - Allison has put the VA.gov Experience Standards on the Platform Website via the link Peggy shared above. She inserted the standards via iframe, and we'd like to ensure that this format is accessible before moving forward. Would you please share if you have any concerns and/or comments? We do have other options, but this allows us to only update and/or manage the standards in 1 location. Our other options would require to us manage the standards in 2 locations.

Please let me know. Thanks!
