### ISSUE TITLE
[EPIC] Campaign Landing Page 1.0 Features

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#25772]
## Product Outline
Here is the [Product Outline.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/state-of-product.md)

## High Level User Story/ies
As a VA stakeholder who creates Campaign Landing Pages, I would like additional page builder functionality to (a) make the task of creating a page easier or (b) to create more effective campaign pages.

## Hypothesis or Bet
**If** we create a more robust authoring and front-end user experience**then** the Campaign Landing Page will be used more effectively as a communications tool by VA stakeholders.

## OKR

- **Objective (DRAFT/WIP):** 
Noticeably increase both VA editor (user and Veteran (consumer) satisfaction for the Campaign Landing Page.
- **Key results :**
   - Increased satisfaction score (via Feedback survey) for users of the Campaign Landing Page
   - Increased Medallia satisfaction score for Campaign Landing Page

## What is scope for MVP

The Public Websites team will work in tandem with the CMS product team to build the following editor and front-end user experience features.

**Research/Testing:**

**Engineering:**
- A FE engineer to collaborate on the front-end build of the information landing page and the Web form on the VA platform (using VA Design System).

**Design:** 
- A UX designer to possibly create clickable prototypes (the site link(s), the landing page, the Webform) for user testing
- A UX designer to ensure the design of the product deliverables are in keeping with VA.gov's well-established design principles and design system/storybook.

**Content**
- Support to identify and create the content needed for the Landing Page
- Support to ensure the Form instructions adheres to VA.gov's  content and plain language guidelines.

**IA**
- Recommendations/guidance for VA.gov site linking, URLs and SEO optimization

**Product**
- Bridge and drive technical and agile project collaboration between the two teams 
- Guide collaboration cycle process

## Definition of done

- [ ] MVP of Landing page shipped
- [ ] MVP of Web form shipped, with integration to reporting/processing/handling touch-points
- [ ] VA.gov site links established

### What must be true in order for you to consider this epic complete? 

MVP of the product experience as defined is delivered to the satisfaction of users and VA business stakeholders.

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
