### ISSUE TITLE
Enable new Rails engine in Prod

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25785]
## Issue Description
The Rails engine is currently held in Staging by a feature flag and can be moved to Prod

## Tasks
- [x] Turn flag on in Prod
- [x] Validate rails endpoints

## Acceptance Criteria
- [x] ccp and urgent care searches use new Rails engine paths
