### ISSUE TITLE
NOD: Fix additional issue validations

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25799]
## Description

When a Notice of Disagreement form includes save-in-progress data with an invalid additional issues decision date is saved then restarted, the additional issue card appears collapsed but does not allow you to continue. The decision date is invalid and the card should be placed into edit mode to make this visible.

Also, a completely empty additional issue entry allows the Veteran to proceed. It also displays a nameless area of disagreement page and entry on the review and submit page.

## Tasks

- [ ] Place additional issue cards with an invalid date into edit mode
- [ ] Prevent continuing with an empty additional issue card

## Definition of done

- [ ] Tasks are complete
- [ ] All tests are passing
