### ISSUE TITLE
[CONSIDER] National Spotlight content library

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25810]
## Issue Description
As Vet Center Central Office staff, I would like to make new content (from press releases/blogs/etc) available to Vet Center Field staff to use as local Spotlight content. 

Use case: local staff would like to use new national content in an available local Spotlight box

---
## Tasks
- [ ] Determine options for making additional national content available for local use 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing this as it has been added to [Enhancements/optional features for Vet Centers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37529)
