### ISSUE TITLE
[FE] My VA: Configure feature flags in staging and prod for My VA UAT

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25817]
## Background
We need to be able to configure feature flags in prod and staging for My VA UAT. Note that we anticipate UAT to be scheduled for the week of 6/21, hopefully beginning that Tuesday (6/22). We'll want to make sure this is all set and ready to go before then.

[Here are the instructions for how to turn My VA 2.0 on for a single specific user in production](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign/flipper-feature-flags)

## Tasks
- [x] [Make sure you already have an LOA3/ID-verified account on VA.gov.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign/flipper-feature-flags/README.md#if-you-do-not-already-have-an-loa3-idme-account-to-sign-into-vagov)
- [x] [Get added to the list of users who can modify our Flipper feature flags](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign/flipper-feature-flags/README.md#if-your-loa3-account-email-address-is-not-on-the-list-of-admin_user_emails)
- [x] Turn My VA 2.0 on for Taylor in production

**Comment by erikphansen** [comment]
@ajakabcin I added some additional info/docs for this and also added it to this sprint since @tmitchellgcio should get this done well ahead of UAT which we plan to start in about two weeks.

**Comment by tmitchellgcio** [comment]
I guess this is on hold for now. I need to wait until my PR is deployed in the Backend. I'm not sure when this happens
