### ISSUE TITLE
Connect to BGS Service to Check for Pension

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25814]
## Background
The Pension line of business would like to have applications routed specifically for them and to do that, a claim label needs to be adjusted to reflect that routing in NWQ who will then route to the appropriate Pension review person.

## Considerations 
Don Moses - has some test case data we can use
David Overton - has access to VBMS
Linda can provide more details, reference BIP (check her email)
What is the exact Claim Label? `PMC` ?

## Tasks
- [x] Understand what Linda has shared
- [x] Determine next steps (BIP?)

## Acceptance Criteria
- [x] Next steps have been determined and documented in the relevant engineering notes folder, or comment section here on this ticket

**Comment by kathleencrawford** [comment]
Discussed this during the BE Developer meeting on 06/23.  None of the VSA teams that were present are currently working with BIP.  

I also spoke to Charley on 06/23 and he does not know of any teams working in vets-api who are integrating with BIP.  He did mention that their name has changed from BIP to BID.

Kevin and I have a meeting with BGS on 06/24 to discuss further.

**Comment by kathleencrawford** [comment]
Kevin and I met with Linda and Shane from BGS on 06/24.

Shane sent some example code in Postman.  I am able to test the awards service on my GFE.  

I followed up with Charley from Lighthouse about next steps to getting that new BIP service integrated in vets-api.  We will need to add some configuration to the devops repo.  I will be writing a new ticket to track that item.
