### ISSUE TITLE
Best Bet Request for Common Spellings Error + Mis-types 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25815]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [x] NEW: Create a new best bet
    - [ ] CHANGE: Alter an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @denisecoveyduc  and @johnhashva

# Section 1: New Request

### Description
*Please provide a brief description of the initiative and supporting information for the creation of a best bet.*  
>Example: "The VA is working closely with the Centers for Disease Control and Prevention (CDC) and other federal partners to provide COVID-19 vaccines to Veterans and VA health care personnel. The Find a Facility tool has just added COVID vaccine as a search category and we want to create a Best Bet to ensure veterans seeking looking information are aware of this new tool feature."*

        >   identifies the 25-50 top commonly mis-spelled words (e.g. representive) — I’m thinking I can add those mis-types as keywords for most obvious Best Bets.  

##  Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Background/Context
_What background information is available to support this work?__

## Tasks
- [ ]Review queries for spellings and mistypes
- [ ] Generate list of terms to add as keyword to best  bets
- [ ] Add to best bet strategy which terms we are capturing 

## Acceptance Criteria
- [ ] Terms have been added to best bets as keywords
- [ ] ***Tier 3 (No Socks validation necessary )*** Validation of AC not required , once fix has been applied please ensure safe monitoring practice and validation with any applicable cross functional team as applicable. 

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
        > date/time
 
 ### Please provide the following information:

 - [ ] Specify the **Headline** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

> Example: Get information about the COVID 19 vaccine from your local VA facility_

        > enter headline
 - [ ] Specify the **Text** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

> Example: Get the latest updates about COVID-19 vaccines at your nearest VA facility._

        > enter text

 - [ ] Specify the  **Keywords** that would generate the Best Bet*(@DanielleThierryUSDSVA or @bethpotts)

> Examples: covid vaccine, covid vaccine availability, vaccine availability, etc._

        > enter text

 - [ ] Specify the **URL** for the Best Bet (@davidconlon )

> Examples: https://www.va.gov/find-locations?facilityType=health&serviceType=Covid19Vaccine_

        > enter url
       

# Section 2: Change Request

### Description
Please provide a brief description of the initiative and supporting information for the creation of a best bet.  
> ****Example:*** "The VA is working closely with the Centers for Disease Control and Prevention (CDC) and other federal partners to provide COVID-19 vaccines to Veterans and VA health care personnel. The Find a Facility tool has just added [COVID vaccine as a search category](https://www.va.gov/find-locations?facilityType=health&serviceType=Covid19Vaccine)and we want to create a Best Bet to ensure veterans seeking looking information are aware of this new tool feature."**

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
        > date/time
 
 ### Please provide the following information:
 - [ ] Identify the Best Bet requiring changes

        > associated best bet
- [ ] Specify the change(s) that are required.  

        > details about required change
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: These requests are handled by the Search & Discovery  Team. Reach out via Slack #va-search with any questions.*** 

#### Acceptance Criteria
- [ ] Add this request into a Zenhub Epic
- [ ] Follow-up with requester to address any lingering questions/concerns
- [ ] For new Best Bet: Setup, test and validate the Best Bet in Production via the Search.gov dashboard (@johnhashva)
- [ ] For Best Bet Changes: Alter Best Bet via the Search.gov dashboard, test and validate (@johnhashva)

#### Definition of Done

 - [ ] Request has been implementation and live on production
