### ISSUE TITLE
526: Remove obsolete feature flags

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25828]
## Description

Form 526 has a few features that have been enabled for some time and the ability to disable the feature is no longer required. This includes:

- `form526_original_claims` - original claims feature flag
- `form526_benefits_delivery_at_discharge` - BDD feature flag

## Tasks

- [ ] Remove feature flags in `src/platform/utilities/feature-toggles/featureFlagNames.js`  (vets-website)
- [ ] Remove feature flags associate code in form 526 (vets-website)
- [ ] Remove feature flags in `config/features.yml` (vets-api)
- [ ] Inform backend engineer of the changes so the services flag can be removed

## Definition of done

- [ ] Tasks completed
- [ ] Tests passing
