### ISSUE TITLE
HLR: Remove obsolete feature flag

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25829]
## Description

Form 20-0996 (Higher-Level Review) has a feature flag that has been enabled for some time and the ability to disable the feature is no longer required.

`form996_higher_level_review` - Higher-Level Review feature flag

## Tasks

- [ ] Remove feature flag in `src/platform/utilities/feature-toggles/featureFlagNames.js`  (vets-website)
- [ ] Remove feature flag associate code in the HLR form (vets-website)
- [ ] Remove feature flag in `config/features.yml` (vets-api)
- [ ] Inform backend engineer of the changes so the services flag can be removed

## Definition of done

- [ ] Tasks completed
- [ ] Tests passing
