### ISSUE TITLE
Draft June newsletter edition (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#25838]
# User story

As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- [x] Determine how to get Rachael Roueche's approval on CTA destination
- [x] Conduct Pair writing and SME interview sessions (Amy)
- [ ] Draft newsletter edition (Amy)

Tasks for next sprint:

- Conduct reviews for technical accuracy and OCTO-DE signoff
- Prepare MailChimp version (Service Design, but we support)
- Publish the newsletter via email (Service Design)
- Announce the newsletter via Slack (Service Design)
- Update the Google Form (Amy)
  - remove previous submissions
  - update form langauge for next round of submissions
  - create new link for sharing survey
- Solicit content from PMs (James and Liani)

# Acceptance criteria
- To come.

# Reference info
- [June newsletter draft](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1583087658/June+2021+draft)

**Comment by lianilychee** [comment]
6/10 Thurs:
- pause pending scheduled pair writing sessions!

**Comment by lianilychee** [comment]
6/15 Tues:
- have pair writing sessions with BE and FE today
- gonna have to share what we worked on with Dror bc Dror is the final approver
- goal for tmr SU: will have started parsing thru info to incorporate into blurbs

**Comment by lianilychee** [comment]
6/16 Weds:
- Amy needs now to tighten up the Collab Cycle reminder + CfA blurb <-- will share/ask further asynchronously
- hoping to share for approval by Monday
-

**Comment by lianilychee** [comment]
6/17 Thurs:
- have added Shira's blurb!  pulling info from the [5/11 ToT slide](https://dsva.slack.com/archives/G01JN8X1S7M/p1620749213081700?thread_ts=1620670650.081200&cid=G01JN8X1S7M)
- by end of today:
  - will have drafts we can review together tomorrow
