### ISSUE TITLE
Documentation of *api.va.gov certificate delivery step to VBMS

### ISSUE THREAD

**Issue by golavarr-va** [department-of-veterans-affairs/va.gov-team#25852]
## Description
VSP currently manages the renewal of *api.va.gov certificates (dev-api.va.gov, staging-api.va.gov, sandbox-api.va.gov, api.va.gov). Every year we have a special usecase involving the VBMS folks require a copy of these certificates to be delivered to them, since they need to import these certs locally in their system. We've been trying to figure out an approach to notifying them of these upcoming notifications, and have landed on the following. 

Overall, this is the proposed process:

1. Certificate renewal.
2. Notify VBMS of upcoming certificate updates, and deliver new certificates. 
3. Installation of certificates in VSP RevProxies.
4. Installation of certificates in TIC Gateways.

VBMS previously requested that these folks be notified before the certs are installed in the revproxies and tic gateways:

- Mark A. McConville mark.mcconville@va.gov
- Mrozinski, Jared F. (BAH) Jared.Mrozinski@va.gov
- VACO VBMS Prod Ops Leads VACOVBMSProdOpsLeads@va.gov
- John, Manu (Mary) M. Manu.John@va.gov
- Clyde Miller Clyde.Miller@va.gov

## Background/context/resources
https://dsva.slack.com/archives/C013VCQKSE7/p1623185213016100

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Add this extra step in the documentation for certificate renewals involving *api.va.gov certificates.
- [x] VBMS receives a notification and the updated certificates prior to the certs being installed in the RevProxies and TIC Gateways. 

## Definition of Done
- [x] Documentation is updated for *api.va.gov certificate renewals. 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by jbritt1** [comment]
Moved [the original SOP](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md) to Confluence [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1644625921/Obtain+or+Renew+Publicly+Signed+SSL+Certificates) with a warning at the very top pointing to an additional Confluence document specific to [updating `*api.va.gov` certificates](https://vfs.atlassian.net/wiki/spaces/OT/pages/1644724240/Renew+a+api.va.gov+SSL+Certificate) as requested.
