### ISSUE TITLE
[Research] MVP Check-in Usability Study Analysis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25851]
## User Story
- As a product team, we want to know the findings from the usability test. 

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/conversation-guide.md)

## Description
Analyzing the videos and notes from the research study on the pre-MVP of Check-in to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

## Acceptance Criteria
- [x] [Post synthesis documents to GitHUB](https://app.mural.co/t/vsa8243/m/vsa8243/1625079366895/f1363142396561f67e55f596ab3be49ccc343e0b?sender=uc940f53ad96ac0203d6d3631)
- [x] Write top-line summary

**Comment by kristenmcconnell** [comment]
All notes are posted to GitHub: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/mvp-usability/sessions-notes

**Comment by kristenmcconnell** [comment]
Synthesis document complete: https://app.mural.co/t/vsa8243/m/vsa8243/1625079366895/f1363142396561f67e55f596ab3be49ccc343e0b?sender=uc940f53ad96ac0203d6d3631

Due to what we found in synthesis, I will skip the top-line summary and quickly work on the final report.
