### ISSUE TITLE
Build Search KPI Dashboard in Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25866]
## Issue Description
Create the Search KPI Dashboard so that we can test our build SLAs and VFS teams can start using our new Search KPI Dashboards "MVP."

---
## Tasks
- [x] Create any new calculations
- [x] Create new cards for the dashboard
- [x] Apply the designs to the dashboard & build out the funnels where necessary
- [ ] QA the data 
- [ ] QA the designs/content

## Acceptance Criteria
- [ ] VFS teams can test the Search KPI Dashboards with real data

**Comment by chloedotbrown** [comment]
### Changes from [design round 2](https://vfs.atlassian.net/wiki/spaces/AT/pages/1572765842/Search%2Band%2BContent%2BKPI%2BDashboard%2BComps)

#### Dates
- All non-multi-value gauge cards have dynamic date range listed in Summary Number field, if they do not have a date axis.
- All multi-value gauge cards:
  - Have the time unit of comparison shown below title. 
  - “Last week” text updated to “last period” for comparison percent and hover text, since users may customize dashboard to graph by week or month.
  - Hover text for main value also specifies that number shown is for most recent period selected.

#### Dashboard filters
- Removed “date” from current filter bar so that we can more clearly direct users to “Choose Date” window, where they can also adjust the time units for comparison.

#### Highlights
- Original “Search Funnel” showed both user (“all VA visitors”) and event level data (“searches/clicks”) on same axis. Given the big difference in scale (“all visitors” would dwarf other bars), have limited to event-level only.
- Removed “Percent of all VA users” from section, as ratio is so small it is unlikely to be meaningful. This KPI still lives in final section (though it counts by sessions, not users). Currently filling this slot with “Refinement Rate” gauge as replacement — **does another metric make more sense?**

#### Search completion
- “Results Clicked” table shows total clicks instead of click-thru rate. This was not possible to calculate, since search result title is only captured when the user clicks (rather than when result is shown).

#### Search timing
- “Avg. time on search results” duplicative of “Avg. time to complete” in practice. Leaving off, as it would have been calculated nearly the same way and meant the same thing.
- “Avg. scroll depth on results” card dropped - scroll depth not captured on results pages.

#### Search exits
- “Exit rate” by users and search and exit totals are in above cards are by session. Have tried to clarify difference in titles, side-by-side text and hover text — but could also switch the exit rate to sessions. 

### Additional data notes
- The numbers for the "Time to click by most searched terms" seem very high — will flag for QA.
- Flagging that Yellow Ribbon may be a special case and need its own sub-page, similar to how we've talked about the Facility Locator. Users don't necessarily click results (list of schools and info shown), so Search completion and Search exits sections look weird.
- Using "search_scope" as our product field to configure dashboard. 
- Search doesn't have landing page to link to or product descriptions available in the data, so those are left out of intro text.

### Next steps
Build out 2nd tier of drill path cards, continue QA of [dashboard](https://va-gov.domo.com/page/1964748112) and [data dictionary](https://vfs.atlassian.net/wiki/spaces/AT/pages/1582727211/WIP%2B-%2BData%2Bdictionary%2BStandardized%2BSearch%2BKPIs).

**Comment by chloedotbrown** [comment]
QA of data blocked until next week, when Brian can help investigate reason for difference between BigQuery and Google Analytics total and unique events. Updated VA stakeholders on team's private channel yesterday (6/16).

**Comment by chloedotbrown** [comment]
QA of data unblocked 6/22 – discrepancy in numbers was caused by sampling in GA report. Brian, Lauren, and Joanne presented on issue during Sprint 54 Demo.

![image](https://user-images.githubusercontent.com/45518242/123166351-2a666280-d42a-11eb-89fb-77080bcb5abf.png)

**Comment by chloedotbrown** [comment]
Drill-path cards have now all been created!

Small note that the final column in the flex table for "Exit rate by most common search terms" shows the most recent exit rate, rather than the percent change between two most recent values as other flex tables do. Domo had trouble creating a percent change of percent-based metric and kept multiplying comparison x100, and unfortunately, this chart type has fewer options to customize number type for different columns. Replacement column is labeled and not colored with the comparison indicator (which I've kept), so hopefully it won't be confusing to readers.

**Comment by joanneesteban** [comment]
Search KPI Dashboard launched 7/21/21. Thank you to the entire team for this work!
