### ISSUE TITLE
QA Search KPI Dashboards in Domo - Data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25867]
## Issue Description
As we start to roll out our dashboards, we need to make sure that our data is accurate and trustworthy

---
## Tasks
- [x] Verify that data formats are correct
- [x] Confirm the data is what is expected (does the info collected measure what it's supposed to measure?)
- [x] Identify & document invalid values

## Acceptance Criteria
- [ ] The production Search KPI Dashboard in Domo has accurate and trustworthy data

**Comment by laurensimpson14** [comment]
## Highlights
| Card | Filter | Domo Screenshot | GA Report| Status |
| :------- | :-------: | :-------:| :-------:| :-------:|
|Successful searches | None| ![image](https://user-images.githubusercontent.com/80417436/123284342-2db92700-d4da-11eb-8421-23741aba2dea.png) | ![image](https://user-images.githubusercontent.com/80417436/123469530-2c165e80-d5c1-11eb-8228-722bc369df6b.png)|🟢 Tracking Correctly|
|Successful searches | Find Forms |![image](https://user-images.githubusercontent.com/80417436/123470004-cb3b5600-d5c1-11eb-80fb-28bdf350346b.png) |![image](https://user-images.githubusercontent.com/80417436/123469982-c4acde80-d5c1-11eb-8d1a-8cf3bd7dbb64.png) |🟢 Tracking Correctly|
|Successful searches | Resources and Support |![image](https://user-images.githubusercontent.com/80417436/123470193-12c1e200-d5c2-11eb-80ce-9067a24d0ae8.png) |![image](https://user-images.githubusercontent.com/80417436/123470271-2cfbc000-d5c2-11eb-8bd0-0e52f86c3475.png) | 🟡 The dashboard is showing 7,762 successful searches, however the GA report when filtered for event actions that begin with `Search Result Chosen ~ Type Ahead Disabled ~ Resources and support` it shows only 3,319. Is the `Resources and Support` dashboard filter set to include more than just the actions that begin with `Search Result Chosen ~ Type Ahead Disabled ~ Resources and support`? |
|Successful searches | Yellow Ribbon | ![image](https://user-images.githubusercontent.com/80417436/123470611-a7c4db00-d5c2-11eb-9e69-7362a00b2560.png) | ![image](https://user-images.githubusercontent.com/80417436/123470869-fa9e9280-d5c2-11eb-9085-8d8eb89a9e85.png)|🟡 The dashboard is showing 4,996 successful searches, however the GA report when filtered for event actions that begin with `Search Result Chosen ~ Type Ahead Disabled ~ Yellow Ribbon` it shows only 4,904. Is the `Resources and Support` dashboard filter set to include more than just the actions that begin with `Search Result Chosen ~ Type Ahead Disabled ~ Yellow Ribbon`?|
|Search funnel | None| ![image](https://user-images.githubusercontent.com/80417436/123471302-93351280-d5c3-11eb-9fee-73b3436120d9.png)|![image](https://user-images.githubusercontent.com/80417436/123471270-87e1e700-d5c3-11eb-904e-e9cebc97be87.png) |🟢 Tracking Correctly|
|Search funnel | Find Forms | ![image](https://user-images.githubusercontent.com/80417436/123471527-ea3ae780-d5c3-11eb-9e20-056fac52b890.png) |![image](https://user-images.githubusercontent.com/80417436/123471506-e14a1600-d5c3-11eb-8446-44a0cf444f69.png) | 🟡 The dashboard is showing a higher number (446,260 vs ga report number of 345,548). I think the `Find forms` filter may be set to `anything that contains "find forms"` rather than `anything that begins with "Search Results Returned ~ Type Ahead Disabled ~ Find forms"`|
|Search funnel | Resources and Support |  | |🟢 Tracking Correctly|
|Search funnel | Yellow Ribbon |  | |🟢 Tracking Correctly|

@chloedotbrown and @JasonTheBearded I'm noticing a trend with the Search dashboard's filters. It looks like the `Find forms` filter, `Resources and support` filter, and `Yellow Ribbon` filter may be set to show anything in the event action that _contains_ `find forms`, `resources and support`, or `yellow ribbon`. However, we likely want to instead have it set to anything that _begins with_ `Search Results Returned ~ Type Ahead Disabled ~ Find forms`, `Search Results Returned ~ Type Ahead Disabled ~ Resources and support`, or `Search Results Returned ~ Type Ahead Disabled ~ Yellow ribbon`. What are your thoughts?

**Comment by JasonTheBearded** [comment]
@laurensimpson14 The search scope field in the view is pulling the value from the event action. I'll double check the query to make sure it's not duplicating results.

**Comment by JasonTheBearded** [comment]
@laurensimpson14 For the user click rate, the calculation was originally based on the count of users rather than the count of events as the search funnel is using. After speaking with @chloedotbrown we agreed that it made sense to change the user click rate to be based on the event count. That change is in the dash now so the numbers should be closer to matching. Thanks for the catch!

**Comment by jennaouellet** [comment]
**Search Completion**

@laurensimpson14  for **Results Clicked** and several others I was not able to reproduce numbers even close to what DOMO has with an unsampled report. I am likely looking in the wrong spots so I'll schedule some time with you for some quick GA guidance on the search event. 


**Search Clicks By Device:** Accurate and matches across GA and DOMO

![image](https://user-images.githubusercontent.com/85642160/124210051-c3dfe500-dab8-11eb-9f19-fd9eb7b08fc9.png)

![image](https://user-images.githubusercontent.com/85642160/124210072-cfcba700-dab8-11eb-8310-18a08518a199.png)


**Search Click Rate:** Accurate - 749,888 users clicked out of 1,109,906 searches viewed (67%)

![image](https://user-images.githubusercontent.com/85642160/124210095-d823e200-dab8-11eb-9a83-af484622f5c7.png)

![image](https://user-images.githubusercontent.com/85642160/124210101-dce89600-dab8-11eb-978e-ce8d5f9d5c6d.png)



**Search Exits**
My numbers here aren’t close here either. Hoping I’m just missing something simple in my GA setup:

![image](https://user-images.githubusercontent.com/85642160/124210119-e540d100-dab8-11eb-9ebe-7181e67b0ace.png)

**Comment by bsmartin-ep** [comment]
@JasonTheBearded / @chloedotbrown -

re: Jenna's question about Search Exits

You are defining a `search exit` as "user searched, but did not click any results" vs the [GA definition](https://support.google.com/analytics/answer/1032321?hl=en#:~:text=Search%20Exits%20%3D%20The%20number%20of%20searches%20made%20immediately%20before%20leaving%20the%20site.) of:

> Search Exits = The number of searches made immediately before leaving the site.
> Percentage of Search Exits = Search Exits / Total Unique Searches

?

**Comment by JasonTheBearded** [comment]
That is correct @bsmartin-ep. @chloedotbrown do you think we should change our definition to match closer to GA's?

**Comment by chloedotbrown** [comment]
@JasonTheBearded Yeah - would this be possible to flag this version exit searches in BQ? I think in general, it's best for us to mirror GA unless we've got a good reason not to, but the defs above make sense to me.

**Comment by JasonTheBearded** [comment]
I believe we should be able to, @bsmartin-ep we'd be able to use the hits.isExit field for this purpose right?

**Comment by bsmartin-ep** [comment]
Yes indeed @JasonTheBearded.  

FWIW I think your metric is more useful than "this search query made someone rage quit the website".

**Comment by chloedotbrown** [comment]
In case, we could keep the metric calculation as is, but rename it so there's less potential confusion with the GA term. "Search abandonment rate", etc.? What are your thoughts @bsmartin-ep @JasonTheBearded?

**Comment by bsmartin-ep** [comment]
Maybe I'm being mean to the metric @chloedotbrown.  Is it interpreted as "they found what they needed and ended the session"?

But I like "Search Abandonment".

**Comment by chloedotbrown** [comment]
@bsmartin-ep Eh current calc is still related to rage-quits, I think. We want search exits and exit rate to go down, and the table with the heat map flagging top searches and their exit rates is supposed to flag terms that aren't giving users good results (since they're not clicking as often). 

Maybe we can all do quick chat about it in standup today?

**Comment by bsmartin-ep** [comment]
@laurensimpson14 / @JasonTheBearded -

I wasn't able to get the period-over-period card to work (generic Domo errors), but can you QA this single value card?

https://va-gov.domo.com/analyzer?pageId=1964748112&cardid=137369139&userId=2108773409

Lauren, there's a GA segment for "Sessions with view_search_results" you can use to compare.

**Comment by bsmartin-ep** [comment]
@laurensimpson14 -

### no results found

Where are you seeing 1.4 million search events for this time period?  

I get [16,285](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210608&_u.date01=20210615&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22BW%22,%22No%20Search%20Results%20Returned%22,0%5D%5D/) / [140,063](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210608&_u.date01=20210615&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:view_search_results) = ~11.6%

**Comment by bsmartin-ep** [comment]
### Search sources

> Both the Domo dash and the GA report are showing www.va.gov/find-forms as the top source, however they are showing very different numbers (281,208 and 573,576 respectively)

I think the issue is Page vs Previous page  We can't mix events and previous page path in GA, so I verified this with BQ.

**Comment by bsmartin-ep** [comment]
### Total search users by week

> Dash shows 32,228 - However I'm seeing 143k in the un-sampled report for unique searches from June 8 - June 15. Should the unique search number be the same as the user count?

This actually lines up pretty well if you include `onsite-search-results-click` event label in your filtering.

**Comment by JasonTheBearded** [comment]
It should also just be the unique user count, not unique search count. Because a single user could have multiple successful searches

**Comment by bsmartin-ep** [comment]
### Successful searches | Yellow Ribbon
### Successful searches | Resources and Support

Unsampled report with event actions filters looks good...

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210707&_u.date01=20210707&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22~~%20yellow%20ribbon%22,0%5D,%5B0,%22analytics.eventAction%22,%22PT%22,%22all%20va.gov%22,1%5D%5D&_r.drilldown=analytics.eventLabel:onsite-search-results-click

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210707&_u.date01=20210707&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22~~%20resources%22,0%5D,%5B0,%22analytics.eventAction%22,%22PT%22,%22all%20va.gov%22,1%5D%5D&_r.drilldown=analytics.eventLabel:onsite-search-results-click

**Comment by bsmartin-ep** [comment]
### Avg. seconds to click results

Stripped down SQL query looks good...

```sql
SELECT
    AVG(Time_between_results_and_click_sec)
FROM
    (
        SELECT
            -- Time_between_results_and_click_sec measure: looks at hit time for search result return and hit time of search results chosen based on position of records
            CASE
                WHEN TRIM(search_results_arr [SAFE_OFFSET(0)]) = 'Search Results Returned'
                AND event_label = 'view_search_results'
                AND LEAD(TRIM(search_results_arr [SAFE_OFFSET(0)]), 1) OVER (
                    PARTITION BY date,
                    sessionid
                    ORDER BY
                        hitNumber
                ) = 'Search Result Chosen' THEN (
                    LEAD(hitTime, 1) OVER (
                        PARTITION BY date,
                        sessionid
                        ORDER BY
                            hitNumber
                    ) - hitTime
                ) / 1000
                ELSE NULL
            END AS Time_between_results_and_click_sec,
        FROM
            (
                SELECT
                    date,
                    CONCAT(ga.fullVisitorId, visitStartTime) AS sessionId,
                    hits.hitNumber,
                    hits.time AS hitTime,
                    hits.eventInfo.eventLabel AS event_label,
                    SPLIT(hits.eventInfo.eventAction, '~') AS search_results_arr,
                FROM
                    `vsp-analytics-and-insights.176188361.ga_sessions_*` AS ga
                    LEFT JOIN UNNEST(hits) AS hits
                    LEFT JOIN UNNEST(hits.customDimensions) AS hcd
                    LEFT JOIN UNNEST(hits.customMetrics) AS hcm
                WHERE
                    _TABLE_SUFFIX --= FORMAT_DATE('%Y%m%d',DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
                    BETWEEN '20210701'
                    AND '20210707'
                    AND hits.eventInfo.eventLabel IN (
                        'view_search_results',
                        'onsite-search-results-click'
                    )
                GROUP BY
                    date,
                    fullVisitorId,
                    visitStartTime,
                    hitNumber,
                    hitTime,
                    hits.eventInfo.eventLabel,
                    hits.eventInfo.eventAction
            ) a
    )
```

**Comment by joanneesteban** [comment]
Thanks for your work here, @bsmartin-ep @laurensimpson14 @jennaouellet !
