### ISSUE TITLE
[Research] Run Pre-MVP Check-in Usability Sessions

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25861]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/conversation-guide.md)

## Description
Facilitate User Research Sessions for Pre-MVP Check-in Usability Study

## Tasks
- [x] Complete all research interviews based on [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/conversation-guide.md) and [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/research-plan.md)

## Acceptance Criteria
After all of the sessions are complete 
- [x] Consolidate Notes from each team member listening on sessions
- [x] Download video of sessions

**Comment by kristenmcconnell** [comment]
Ran successful pilot session on June 21.
