### ISSUE TITLE
QA Content KPI Dashboards in Domo - Data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25869]
## Issue Description
As we start to roll out our dashboards, we need to make sure that our data is accurate and trustworthy

---
## Tasks
- [ ] Verify that data formats are correct
- [ ] Confirm the data is what is expected (does the info collected measure what it's supposed to measure?)
- [ ] Identify & document invalid values

## Acceptance Criteria
- [ ] The production Content KPI Dashboard in Domo has accurate and trustworthy data

**Comment by laurensimpson14** [comment]
@joanneesteban @chloedotbrown @JasonTheBearded I've looked through the content dashboard and, unfortunately, everything is going to have to wait until @bsmartin-ep gets back since I don't know why the event totals, users, pageviews, etc. are not lining up w/GA. 😞  However, I did leave two notes (next to the yellow circles) that we don't need Brian for. 

I'll update the below notes once Brian get's back. 

## All COVID FAQ Users who have their browser language set to Spanish as Percent of Total Users
🟡  In the language filter I see that `es`, `es-419`, `es-co`, `es-es`, `es-mx`, `es-pe`, `es-pr`, `es-us`, `es-uy`, & `es-xl` are selected. However, `es-ar`, `es-bo`, `es-cr`, `es-ec`, `es-gt`, `es-hn`, & `es-sv` are not. Should these be included in the filter as well? Perhaps it would make sense to have the Spanish filter be whenever Language "contains" "es", that way if a new/different es is added then our filter list will dynamically update?
🔴   The chart on Domo is showing 1.38% for the week of June 6th, however when I look at GA I see 5,384 unique pageviews (users) for all languages on the `www.va.gov/coronavirus-veteran-frequently-asked-questions/` page and [15 unique pageviews](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210606&_u.date01=20210612&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22www.va.gov~2Fcoronavirus-veteran-frequently-asked-questions~2F%22,0%5D%5D&_.useg=userokwCJCebRq-fKWToyWfcNQ/) for Spanish. This would end up being .28% for the week of June 6th, not 1.38% - so the two numbers aren't lining up. 

## Comparison of users who translate English FAQ page via link and users who go directly to the Spanish FAQ page
 - Percent of Users who translate English page via link
   🟡 Is there a reason why this card shows through March rather than continuing into June like the other cards? 
   🔴 Paused until Brian returns due to hit/session/event discrepancy 
 - Percent of Users who visit Spanish COVID FAQ Page
   🔴 Paused until Brian returns due to hit/session/event discrepancy 

## Users who Translated English page to Spanish, then went back to English page
   🔴 Paused until Brian returns due to hit/session/event discrepancy 

## User Engagement on Spanish FAQ Page
 - Total Number of Link Clicks
   🔴 Paused until Brian returns due to hit/session/event discrepancy 
 - Scroll Depth Breakdown
   🔴 Paused until Brian returns due to hit/session/event discrepancy 
 - Interaction with the 'Read this page in Spanish/English' Link
   🔴 Paused until Brian returns due to hit/session/event discrepancy

**Comment by laurensimpson14** [comment]
## Content QA
| Initials of Who QA'd | Card Name | Filter (if Applicable) | Domo Screenshot | GA Report Screenshot | Status |
| :------- | :-------: | :-------:| :-------:| :-------:|  :-------:|
| | | | | | |

**Comment by chloedotbrown** [comment]
For @bsmartin-ep re: engagement clicks with missing or incomplete link_labels, as mentioned in Grooming today:

- [Links with highest engagement](https://va-gov.domo.com/page/426422632/kpis/details/1727922670): no value in `link_label` for link with 3rd highest clicks in unfiltered dashboard view _(not consistent across views, more notes below)_.
- [Buttons with highest engagement](https://va-gov.domo.com/page/426422632/kpis/details/2011780730): no value in `link_label` for button with 6th highest clicks.
- [Anchor links with highest engagement](https://va-gov.domo.com/page/426422632/kpis/details/456186080): no value in `link_label` for anchor link with 8th highest clicks.
- [Accordions with highest engagement](https://va-gov.domo.com/page/426422632/kpis/details/1902719488): "(not set)" in part of `link_label` for accordions with 1st, 8th, and 9th highest opens.
- [Time to click for buttons and links](https://va-gov.domo.com/page/426422632/kpis/details/183362264): no value in `link_label` for button/link with 7th highest clicks.

I'm also getting some VERY weird inconsistencies across dashboard, card, and Analyzer views for the [links](https://va-gov.domo.com/page/426422632/kpis/details/1727922670) card mentioned above. The top two links and their totals seem the same across these views, but all other links, their rankings, and totals for the others change across views, even though no filters are applied (save `engagement_type`= "Links"). 

Can anyone else reproduce this error? It doesn't seem to be affecting the other engagement cards, but I've never seen anything like this in Domo before. Screenshots below. 
<img width="200" alt="Link clicks dashboard" src="https://user-images.githubusercontent.com/45518242/125679988-ce5f167a-6688-4c08-9aac-5c1b576fcf9c.png"> <img width="200" alt="Link clicks card" src="https://user-images.githubusercontent.com/45518242/125679994-575d2753-8510-4412-94e3-ad38a37481bf.png"> <img width="200" alt="Link clicks analyzer" src="https://user-images.githubusercontent.com/45518242/125680006-005b4752-6f89-4e46-9924-de24b7824c84.png">

**Comment by jennaouellet** [comment]
@chloedotbrown I also was able to reproduce that error without any filters applied

**Comment by JasonTheBearded** [comment]
@chloedotbrown could it be because the card is linked?

**Comment by chloedotbrown** [comment]
@JasonTheBearded the interaction looks like it's set to the standard "open card details in new tab." Or did you mean linked another way?

**Comment by JasonTheBearded** [comment]
@chloedotbrown when you open to the card details page, at the bottom there is a link to the button engagement card. I'm not sure if linking cards affects the data being presented but it seems like the only thing that could be causing the issue.

**Comment by chloedotbrown** [comment]
@JasonTheBearded ah I see! Sadly no, that just shows any relationship for how cards were created - it appears when you "save as" from another card. But it is a good reminder for me to go through and clean those up this afternoon.

I'll create a new version of this card from scratch and drop it in dashboard to see if the same error appears. Wouldn't solve the mystery, but could potentially fix the problem.🤞

**Comment by chloedotbrown** [comment]
::update:: 

Recreated a new version of the "Links with highest engagement" card from scratch, but it has the same bug with missing totals across dashboard and card details. I've shared a [comparison table card](https://va-gov.domo.com/kpis/details/577724695) I created to see if I could figure out any patterns in what was missing. Nothing jumped out for me, but hoping it maybe helps with QA of this card/issue?

**Comment by JasonTheBearded** [comment]
@chloedotbrown if it's happening on a fresh card as well this may be an actual DOMO issue that we should raise with Ben and the DOMO team.

**Comment by chloedotbrown** [comment]
Good point - emailed Domo Doug about it, fingers crossed this is something he's seen before.

I'd be surprised though if this is something we're able to get Domo to solve before launch tomorrow. In the meantime, what do we think about redoing this card as a table with a heat map on the clicks column, rather than as a bar chart? While it wouldn't look as good and would be a break in design from the other sections, it _would_ be more accurate/stable across views (plus, the links would be easier to read). And I'd much rather release a version of the dashboard with one different chart type than a chart with data that's missing.

@joanneesteban what do you think?

**Comment by bsmartin-ep** [comment]
@JasonTheBearded / @chloedotbrown -

FYI I adjusted the `Avg. scroll depth` beast mode.  I think the 2 character LEFT was chopping off one the zeroes from `100%`.  Updated to this monstrosity....

```SQL
AVG(REPLACE(LEFT(`event_label`, 3), '%', ''))
```

**Comment by joanneesteban** [comment]
Note: No 1:1 GA to BQ QA for links. More info here: 

![image](https://user-images.githubusercontent.com/48964695/126522087-481a4207-cb54-41ba-9772-37270cecbe3a.png)


Otherwise, QA is completed. Thanks, @bsmartin-ep @laurensimpson14 @jennaouellet !
