### ISSUE TITLE
Build the Content KPI Dashboards in Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25868]
## Issue Description
Create the Content KPI Dashboard so that we can test our build SLAs and VFS teams can start using our new Content KPI Dashboards "MVP."

---
## Tasks
- [x] Create any new calculations
- [x] Create new cards for the dashboard
- [x] Apply the designs to the dashboard & build out the funnels where necessary
- [ ] QA the data 
- [ ] QA the designs/content

## Acceptance Criteria
- [ ] VFS teams can test the Content KPI Dashboards with real data

**Comment by chloedotbrown** [comment]
For all 4 tables for different types of engagement in the Task Completion sections, we'll be showing unique clicks instead of engagement rate, which will need another ETL to calculate. Could revise to include this in future iterations once launched.

Also, size of dataset means that some cards performing count distinct calculations do not load when the dashboard is not filtered for a certain product (ie benefit hub). This shouldn't affect the user's ability to see their data, since all teams will need to filter for their product - but if the issue persists, we can add to documentation so it's not confusing when people land on the dashboard page.

**Comment by chloedotbrown** [comment]
## Changes from [design round 2](https://vfs.atlassian.net/wiki/spaces/AT/pages/1572765842/Search%2Band%2BContent%2BKPI%2BDashboard%2BComps)

#### Engagement rate tables (links, buttons, anchor links, accordions)
- Changed card type to horizontal bar with expanded y-axis, limiting to top 10 items plus a combined "other" category.
- Cards show highest unique click events, rather than engagement rates. This is because of the difficulty of reshaping the data to calculate event-level rate (filled gauges aren't an issue because the count by sessions in aggregate). 

#### Time to complete for buttons and links
- Revised card type to table sorted by unique clicks with time to click heatmapped. When sorted by time to click, long outlier times with only one click dominated the view, which did not seem helpful.

#### Finding the page
- Removed "Avg. pre-page time" cards. Data only generated for page hits (not events), making the metric not meaningful/potentially confusing for the user.
- Removed "Top search terms on VA.gov." Data only existed for pages with no benefit hub association, with the exception of < 5 rows for a few other hub categories. Therefore, this card would be completely blank for the vast majority of VFS teams.

_(Other edits copied from the Search Dashboard ticket.)_

- **Dates**: Making the dates of data shown and/or compared more obvious as the card-level.
  - All non-multi-value gauge cards have dynamic date range listed in Summary Number field, if they do not have a date axis.
  - All multi-value gauge cards:
    - Have the time unit of comparison shown below title. 
    - “Last week” text updated to “last period” for comparison percent and hover text, since users may customize dashboard to graph by week or month.
    - Hover text for main value also specifies that number shown is for most recent period selected.
- **Dashboard filters**: Removed “date” from current filter bar so that we can more clearly direct users to “Choose Date” window, where they can also adjust the time units for comparison.

## Next steps
Build out 2nd tier of drill path cards and create data dictionary.

**Comment by chloedotbrown** [comment]
Update: drill paths built out for all cards (except line chart at top left, which doesn't need one). Data dictionary also finished and ready to be proofed. I've added a few small notes on this in my OOO doc, but it should be ready for QAing once data is uploaded from PM forms.

**Comment by joanneesteban** [comment]
Content KPI Dashboard went live 7/21/21.  Thanks for the work on this launch!
