### ISSUE TITLE
Change date for VGLI on COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#25879]
## Issue Description
Lori Hamilton informed us that the end date to have more time to apply for VGLI has been extended from June 11, 2021 to December 11, 2021. We need to update this date on our FAQs page in the question "Can I have more time to apply for Veterans' Group Life Insurance (VGLI) after separation?"

## Tasks
- [x] Change date on FAQs page
- [x] Review and publish
- [x] Alert stakeholder that change has been made

## Acceptance Criteria
- [x] New date of December 11, 2021, is live on the site

**Comment by RLHecht** [comment]
Change made. WIll close after validating on live site.

**Comment by RLHecht** [comment]
Work validated on live page. Closing ticket.
