### ISSUE TITLE
QA Search KPI Dashboards in Domo - Content/Design

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25870]
## Issue Description
As we start to roll out our dashboards, we need to make sure that our dashboards are usable.

---
## Tasks
QA for the following
- [ ] Design
- [ ] Content
_Other_
- [ ] All links should be clickable and correct
- [ ] Filters should work properly
- [ ] Document feedback

## Acceptance Criteria
- [ ] The production Search KPI Dashboard in Domo is usable and follows the design as close as possible

**Comment by joanneesteban** [comment]
@JasonTheBearded @chloedotbrown 

## Usability Checklist 07-08-2021
Completed using the participant tester:

| Test                                 | Expected Behavior                                            | Actual Behavior                                              | Pass/Fail |
| ------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | --------- |
| Default page                         | Page does not automatically filter, and description reflects lack of filter | Page does not automatically filter, and description reflects lack of filter | Pass ✅    |
| Filter on Search Scope               | Every chart gets filtered for every Search Scope             | "Search refinement distribution" in Search timing section does not filter for any search scope | Fail ❌    |
| Filter on Device Category            | Every chart gets filtered on device category                 | Every chart for every search scope gets filtered on device category | Pass ✅    |
| Filter on Browser                    | Every chart gets filtered on browser                         | Every chart for every search scope gets filtered on browser  | Pass ✅    |
| Date Filters                         | Every chart gets filtered on date                            | Every chart for every search scope gets filtered on date     | Pass ✅    |
| How to use this dashboard - header   | Links to Platform Website, "How to use this dashboard" page  | Links to Platform Website, "How to use this dashboard" page  | Pass ✅    |
| How to use this dashboard - footer   | Links to Platform Website, "How to use this dashboard" page  | Links to Confluence Search data dictionary. Will need to relink when the document goes live on the Platform Website. | Fail ❌    |
| Chart Title                          | Corresponding filtered form appears as the page title        | We should change the search scope to the product names that are listed on the [RACI backlog](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit#gid=1660978947). | Fail ❌    |
| Search Scope description             | Corresponding filtered form description appears with every filtered Search Scope | No description appears for any of the filters. We should reach out to the teams to grab these descriptions. | Fail ❌    |
| Data sources                         | Correct data sources appear                                  | Should we be listing Medallia & ForeSee if there's no data flowing in?<br /><br />"Foresee" should be "ForeSee" | Fail ❌    |
| Section titles                       | Every section title & question is spelled correctly          | In the Search Completion section, "How often did people choose each result when it was presented" is missing a "?" at the end. All of the other questions end with a question mark. | Fail ❌    |
| Chart titles                         | Every chart title is spelled correctly                       | Every chart title is spelled correctly                       | Pass ✅    |
| Annotations                          | Every annotation "makes sense" and is spelled correctly      | - In the User surveys section, "(Add all VA comparison)" looks like it's incomplete. Can this be changed to "Waiting on Medallia for All VA comparison"? | Fail ❌    |
| Labels                               | All data labels appear where expected.                       | - Can we add hover text over the table headers in "Exit rates by most common search terms" under the Search exits section? Session exit rates isn't viewable unless the table is clicked on. | Fail ❌    |
| Hover text                           | All hover text "makes sense" and is spelled correctly        | All hover text "makes sense" and is spelled correctly        | Pass ✅    |
| VA.gov Analytics Playbook link       | Links to Github Analytics Playbook                           | Links to Analytics Playbook in Github                        | Pass ✅    |
| Google Analytics link                | Links to Google Analytics 360                                | Links to Google Analytics home page on the `WBC - VA.gov Modernized Content` View. | Pass ✅    |
| VA.gov Data Dictionary link - header | Links to Platform Website, "Forms Data Dictionary" page      | Links to Platform Website, "Forms Data Dictionary" page      | Pass ✅    |
| VA.gov Data Dictionary link - footer | Links to Platform Website, "Forms Data Dictionary" page      | Links to Confluence Search data dictionary. Will need to relink when the document goes live on the Platform Website. | Fail ❌    |
| Domo Help Center link                | Links to Domo Help Center                                    | Links to Domo Help Center                                    | Pass ✅    |
| Export to PPT                        | Entire dashboard exports to PowerPoint without chart cutoffs on the slides or missing labels | - Search completion section gets cut off<br />- Search exits section gets cut off<br />- User surveys section gets cut off<br />- Finding the search page gets cut off | Fail ❌    |
| Export to PDF                        | Entire dashboard exports to PDF without chart cutoffs on the slides or missing labels | - Search completion section gets cut off<br />- Search exits section gets cut off<br />- User surveys section gets cut off<br />- Finding the search page gets cut off | Fail ❌    |

**Comment by chloedotbrown** [comment]
🤔 Questions (@joanneesteban @JasonTheBearded) 
- **Chart Title** – The product names in the RACI tab seem _pretty_ similar to the ones under search_scope, though some aren't in the data yet: Offsite Search, GI Bill Comparison Tool, Facility Locator (though Jason's already flagged this as needing edge case dashboard). Is this issue about matching product name phrasing or completeness of data?
- **Data sources** – Removed Medallia for time being and corrected "ForeSee" capitalization. However, this brings up other question: should we keep User Satisfaction section if there's no data there? Or is that something we're expecting in time for release (at least historical ForeSee data)?

✅ Corrected or couldn't reproduce error
- **Section titles** – Question mark included in Search Completion subheader. 
- **Annotations** – Notes to all-VA comparisons updated.
- **Filter on search scope** – "Search refinement distribution" card in Search Timing section does filter for search_scope. 
- **How to use this dashboard - footer** – Goes to How-To doc on Platform site.

📥 Needs data/URL 
- **Search Scope description** – Need this info from product teams, then will need to be added to Domo datasource. 
- **VA.gov Data Dictionary link - footer** – Can't be updated until published on site right before (same with link at top).

🤷‍♀️ No solution 
- **Export to PPT** – Confirmed with Domo rep, no way to customize breaks/export formatting. Only thing we can do is nudge folks away from this option in our documentation and trainings.
- **Export to PDF** – _(same as above)_

**Comment by joanneesteban** [comment]
Thanks, @chloedotbrown !

🤔 Questions
- **Chart Title** - (I should've titled this "Dashboard Title" instead) This is more an issue about matching product name.
- **Data sources** -  Let's keep the section to remind folks they should still be looking at satisfaction as a KPI. I don't believe we have any ForeSee data specific to these products, but we should check in with Jason Woodman about who has what surveys on Medallia or we can look at the URLs once we get Medallia hooked up to BigQuery.

📥 Needs data/URL
- **Search Scope description** - I'll reach out to teams about this, but if they don't provide anything, we can go ahead and mark this as done.

🤷🏻‍♀️ No solution
- **Exports** - Is there an alternate way of exporting these? If not, in nudging folks away from using "Export," we can encourage them to export individual charts instead of the entire dashboard or take screenshots.

**Comment by chloedotbrown** [comment]
Awesome, thanks for the quick response! For the last few outstanding things: 

- **Exports** – Unfortunately, this is one of the things Domo is not strong in and doesn't provide a lot of flexibility for workarounds. The Domo official rec for improving PDF exports is to keep dashboards under 11 inches tall and Dojo users have recommended DIYing card exports into your own PPT template. Our How-To documentation currently recommends screenshots for the dashboard and other export types for cards. Want to take a look at [our export section](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html#HowtouseVA.govKPIdashboards-Shares&exports) and let me know if it feels like we need to spell instructions out more clearly? I hate to make it longer, but I DO want it to be useful.
- **Dashboard Title** – This may be a @JasonTheBearded question. Where is `search_scope` currently pulling from and would there be any way to match this field to product names in the RACI tab? As a backup, we could also hard code this in a Beast Mode to standardize, but it wouldn't be the most elegant solution, especially as more products get added.

**Comment by joanneesteban** [comment]
- **Exports** - Ah, sorry, I should've reviewed that document first! Let's keep the documentation as is.

**Comment by joanneesteban** [comment]
@JasonTheBearded @chloedotbrown 

Almost good to go here, just waiting on the Platform Website documentation.

## Usability Checklist 07-19-2021

Completed using the Participant tester:

| Test                                 | Expected Behavior                                            | Actual Behavior                                              | Pass/Fail                                                    |
| ------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| Default page                         | Page does not automatically filter, and description reflects lack of filter | Page does not automatically filter, and description reflects lack of filter | Pass ✅                                                       |
| Filter on Search Scope               | Every chart gets filtered for every Search Scope             | Every chart gets filtered for every Search Scope             | Pass ✅                                                       |
| Filter on Device Category            | Every chart gets filtered on device category                 | Every chart for every search scope gets filtered on device category | Pass ✅                                                       |
| Filter on Browser                    | Every chart gets filtered on browser                         | Every chart for every search scope gets filtered on browser  | Pass ✅                                                       |
| Date Filters                         | Every chart gets filtered on date                            | Every chart for every search scope gets filtered on date     | Pass ✅                                                       |
| How to use this dashboard - header   | Links to Platform Website, "How to use this dashboard" page  | Links to Platform Website, "How to use this dashboard" page  | Pass ✅                                                       |
| How to use this dashboard - footer   | Links to Platform Website, "How to use this dashboard" page  | Links to Platform Website, "How to use this dashboard" page  | Pass ✅                                                       |
| Chart Title                          | Corresponding filtered product appears as the page title     | Corresponding filtered product appears as the page title     | Pass ✅                                                       |
| Search Scope description             | Corresponding filtered form description appears with every filtered Search Scope | No description appears for any of the filters. We can add descriptions if VFS teams reach out. | Pass ✅                                                       |
| Data sources                         | Correct data sources appear                                  | Correct data sources appear                                  | Pass ✅                                                       |
| Section titles                       | Every section title & question is spelled correctly          | Every section title & question is spelled correctly          | Pass ✅                                                       |
| Chart titles                         | Every chart title is spelled correctly                       | Every chart title is spelled correctly                       | Pass ✅                                                       |
| Annotations                          | Every annotation "makes sense" and is spelled correctly      | Every annotation "makes sense" and is spelled correctly      | Pass ✅                                                       |
| Labels                               | All data labels appear where expected.                       | All data labels appear where expected.                       | Pass ✅                                                       |
| Hover text                           | All hover text "makes sense" and is spelled correctly        | All hover text "makes sense" and is spelled correctly        | Pass ✅                                                       |
| VA.gov Analytics Playbook link       | Links to Github Analytics Playbook                           | Links to Analytics Playbook in Github                        | Pass ✅                                                       |
| Google Analytics link                | Links to Google Analytics 360                                | Links to Google Analytics home page on the `WBC - VA.gov Modernized Content` View. | Pass ✅                                                       |
| VA.gov Data Dictionary link - header | Links to Platform Website, "Forms Data Dictionary" page      | Links to Confluence Search data dictionary. Will need to relink when the document goes live on the Platform Website. | Fail ❌                                                       |
| VA.gov Data Dictionary link - footer | Links to Platform Website, "Forms Data Dictionary" page      | Links to Confluence Search data dictionary. Will need to relink when the document goes live on the Platform Website. | Fail ❌                                                       |
| Domo Help Center link                | Links to Domo Help Center                                    | Links to Domo Help Center                                    | Pass ✅                                                       |
| Export to PPT                        | Entire dashboard exports to PowerPoint without chart cutoffs on the slides or missing labels | - Search completion section gets cut off<br />- Search exits section gets cut off<br />- User surveys section gets cut off<br />- Finding the search page gets cut off | Pass ✅<br />Domo issue. Redirecting VFS teams to export using screenshots |
| Export to PDF                        | Entire dashboard exports to PDF without chart cutoffs on the slides or missing labels | - Search completion section gets cut off<br />- Search exits section gets cut off<br />- User surveys section gets cut off<br />- Finding the search page gets cut off | Pass ✅<br />Domo issue. Redirecting VFS teams to export using screenshots |
| Color accessibility                  | Any charts with differing colors has distinguishable  values using a color blindness tester. | Any charts with differing colors has distinguishable  values using a color blindness tester. | Pass ✅                                                       |

**Comment by joanneesteban** [comment]
## Usability Checklist 07-20-2021

Thanks for all the edits, @chloedotbrown @JasonTheBearded !

Completed using the Participant tester:

| Test                                 | Expected Behavior                                            | Actual Behavior                                              | Pass/Fail                                                    |
| ------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| VA.gov Data Dictionary link - header | Links to Platform Website, "Forms Data Dictionary" page      | Links to Platform Website, "Forms Data Dictionary" page | Pass ✅                                                          |
| VA.gov Data Dictionary link - footer | Links to Platform Website, "Forms Data Dictionary" page      | Links to Platform Website, "Forms Data Dictionary" page | Pass ✅                                                          |
