### ISSUE TITLE
[UI] Mobile-optimized Header/Footer

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25878]
Based upon use case for check-in, explore a simplified/mobile-optimized header/footer.

Conversation about this in this Slack thread: https://dsva.slack.com/archives/C022AC2STBM/p1623163022407700

## Tasks
- [ ] Write experimental design ticket
- [ ] Talk to group in Slack and Check-in team thread more about what this would even involve

## Acceptance Criteria
- [ ] Turn in experimental design ticket argument

**Comment by kristenmcconnell** [comment]
Mobile optimized header is launching to 50% of users on 12/14/2021. Expected launch to 100% on 12/21.

https://dsva.slack.com/archives/C02GXKL8WM6/p1639505894365200?thread_ts=1639504660.361100&cid=C02GXKL8WM6

**Comment by humancompanion-usds** [comment]
Mobile header has been deployed and is up-to-date in Sketch. We don't yet have this in design.va.gov but we have another issue for that.
