### ISSUE TITLE
Tier 2 Case Process Flow

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#25882]
## Issue Description
_ The current challenge is there is no up to date documentation on the tier 2 case process flow.  Specific instructions should be documented for efficient workflow for current and new team members._

---
## Tasks
- [ ] _Knowledge of the process from beginning to end is necessary for this story to be completed._
- [ ] _Include all relevant information including bottle necks, stop gaps, etc._
- [ ] _Include possible solutions that have been discovered_

## Acceptance Criteria
- [ ] _Documentation will be created as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
[https://app.zenhub.com/files/133843125/ba696e51-c653-4f84-a52c-c36f2b1979a7/download](https://app.zenhub.com/files/133843125/ba696e51-c653-4f84-a52c-c36f2b1979a7/download)

**Comment by Kimberley2019** [comment]
Updated:

[https://app.zenhub.com/files/133843125/1f185533-eddd-4354-a46a-0ab62fb91833/download](https://app.zenhub.com/files/133843125/1f185533-eddd-4354-a46a-0ab62fb91833/download)

**Comment by Kimberley2019** [comment]
Updated
https://docs.google.com/document/d/1z7uCgYcPKDWsRn0Q6ZCWqbR4GkrGiEFS/edit
