### ISSUE TITLE
BDD: Move question & fix separation location logic

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25888]
## Description

Service members who are in the reserves and have been activated on Federal orders need to be asked for their separation location when filing a BDD form. We need to update the separation location logic and move the question to _after_ the activated on federal orders question

## Tasks

- [ ] Update separation location logic to include activated reservists.
- [ ] Move separation location question

## Definition of done

- [ ] Tasks completed
- [ ] Review changes with team
- [ ] Tests all pass
