### ISSUE TITLE
<Create a new Digital Notifications Terms & Conditions page on VA.gov> from <VANotify & VEText>

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/va.gov-team#25887]
## Why you're here 

**Hi! We are looking for your help to create a new Digital Notifications Terms & Conditions page on VA.gov so we can display the relevant terms and conditions specific to notifications. We received guidance from VACO that this should be a separate new page vs. editing an existing one. We are also open to feedback or your ideas.**

### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Does not apply.**

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [x] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Not applicable.
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < 
[Digital Notifications Ecosystem TCs Additions Draft_6_9_21_For Intake.docx.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6626805/Digital.Notifications.Ecosystem.TCs.Additions.Draft_6_9_21_For.Intake.docx.pdf)
 >

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [X] **Other**
   * We are looking to create a new page on VA.gov to be a home for Digital Notifications Terms & Conditions. VACO advised us we need a new page vs. an existing one given the type of content and use cases we are covering. Let us know what the next steps are.
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Ideally 8/2/2021 but we are flexible.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *VANotify & VEText*
- DEPO product owner: *Bev Nelson & Shane Elliot*
- Product manager: *Maria Becker*
- Designer: *Todd Stanich*
- FE engineer: *Filip Fafara*
- Product/team Slack channel: *#va-notify-public*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by bevnobev** [comment]
@DanielleThierryUSDSVA @johnhashva Checking to make sure you have what you need and to get a status.  cc: @miabecker 
Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bevnobev. Thanks for reaching out. Looks like this was submitted as a PW intake form so it didn't get to our sitewide content team's PM, @RLHecht, who manages our grooming. I'm adding our team's label and assigning to Randi.

 We'll need to loop in @mpeterz  @mnorthuis to talk about placement in IA. Also looping in @bethpottsVADEPO @RLHecht. 

cc @brianalloyd @johnhashva

**Comment by bevnobev** [comment]
Thanks @DanielleThierryUSDSVA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bevnobev @miabecker. Following up with a few notes from our content/IA sync:

- Have you all started a collaboration cycle request for this? If not, I would recommend starting that (cc @peggygannon @shiragoodman for awareness). 
- @johnhashva and I would like to have a follow-up call with you both to learn more about the request and the thinking from VACO that it be a separate page as well as to talk through content and process. John's going to look at our calendars and set that up. Thanks!

**Comment by johnhashva** [comment]
@bevnobev + @DanielleThierryUSDSVA -- just set the meeting for Weds 6/30 at 4pm.

**Comment by shiragoodman** [comment]
hi @bevnobev and @miabecker (and thank you @DanielleThierryUSDSVA for tagging me) - if this is a page that is going to be veteran-facing, it is highly recommended that you bring this work through the Collaboration Cycle. We can help you ensure it meets VA.gov standards for design, content, IA, accessibility and QA. If you have any questions, please feel free to reach out on #vfs-platform-support on Slack and request help from Collaboration Cycle. Thanks!

**Comment by miabecker** [comment]
Hi @shiragoodman here is a ticket to kick off a collaboration request for this requeset: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26807 cc: @bevnobev

**Comment by shiragoodman** [comment]
thanks you @miabecker !!

**Comment by mnorthuis** [comment]
IA request for this work is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26923

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bevnobev @miabecker, you'll find our content strategy/IA recommendations in the [IA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26923) referenced above. 

**To note:** There's some broader work on T&Cs going on, so we may want/need to move the location of this page at some point in the future. But we can do a redirect at that time if needed.

Looking at the content, it will need a plain language edit as well. I've added this to my to-do list and hope to get an initial edit completed next week. cc @RLHecht 

FYSA @peggygannon  @shiragoodman

**Comment by bevnobev** [comment]
Hi @DanielleThierryUSDSVA .  Checking in to get a status on the plain language edits to the Terms and Conditions.  Thanks! cc: @miabecker

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bevnobev! We're reviewing and will post by Friday. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Good morning, @RLHecht! @bethpottsVADEPO and I have added edits and comments to this. Could you give it a final copy edit review and then post final here for @bevnobev and @miabecker?

Beverly and Maria: We made a lot of changes to make this more plain language. We also left questions and comments for you and your legal team partners. I'm heading out on vacation, but Beth and Randi are here and can answer any questions you may have about our edits/comments.

And then Randi, can you work with the team on the next steps? Those are:

1. Collaborative review/editing/finalization with the VA Notify team and legal partners
2. Building out the Drupal page (check with Mikki to solidify IA/URL)
3. Hand off to VA Notify for collab cycle reviews.

Thanks!
Danielle

[Digital Notifications Terms And Conditions_dt_bp](https://app.zenhub.com/files/133843125/619729d0-4e18-40b9-88c0-49ed31c23c7c/download)

**Comment by RLHecht** [comment]
@bevnobev @miabecker Here's the content with my final copy edits incorporated as well. Let me know if you have any questions.
[619729d0-4e18-40b9-88c0-49ed31c23c7c.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6983697/619729d0-4e18-40b9-88c0-49ed31c23c7c.docx)

**Comment by miabecker** [comment]
@RLHecht Thank you so much Randi will review in the next few days. Really appreciate the help.

**Comment by miabecker** [comment]
Integrated pretty much all of the changes, just have a few comments and questions. Maybe we should have a quick sync to discuss @DanielleThierryUSDSVA @bethpotts @RLHecht 

[Digital notifications terms and conditions 8.17.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7001273/Digital.notifications.terms.and.conditions.8.17.docx)

**Comment by bethpottsVADEPO** [comment]
@miabecker Could we set up a time early next week? @DanielleThierryUSDSVA is out this week.

**Comment by miabecker** [comment]
Totally! I couldn't see your calendars in slack/outlook what times work best for ya'll? @bethpotts

**Comment by miabecker** [comment]
Attached most up to date draft to be added to drupal: 
[Digital notifications terms and conditions 8.24.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7040003/Digital.notifications.terms.and.conditions.8.24.21.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you for the great meeting today, @miabecker and @bevnobev!

Next steps for this:

- Content team will create Drupal page and send you a preview link and standard "Please review for accuracy only" language to share with privacy SME. @lunascoop Could you please build out this page in Drupal based on the document Maria shared above? URL should be: www.va.gov/privacy-policy/digital-notifications-terms-and-conditions. Thank you!
- VA Notify team will check in about the My HealtheVet specifics and VA.gov profile links and let us know any tweaks we should make re: that.
- VA Notify team will share any feedback from the SME with content team and we'll incorporate/respond as needed.
- Then this will be ready for a final platform staging review. FYSA @peggygannon @shiragoodman 
- As soon as we're good with reviews, we can publish.

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA I built a draft version of this page http://preview-prod.vfs.va.gov/preview?nodeId=34307

**Comment by DanielleThierryUSDSVA** [comment]
Thank you again to @lunascoop for building this page and for the great recommendation on accordions and a subhead for the top section.

Adding a status note: @miabecker and I spoke via slack about next steps, and I provided some additional notes re: sending for an accuracy check. Maria will send to legal expert and let us know any feedback on accuracy.

In the meantime, @RLHecht, could you give this a final copy edit for errors & omissions? One thing I noticed is that we need to shift to sentence casing and us "and" instead of "&" in the accordion section. We can make those changes along with any other copy edits.

Thanks, all!
cc @bevnobev

**Comment by miabecker** [comment]
Yes, thank you @lunascoop really appreciate all of your work. Bev and I sent to Nico yesterday. Thank you @DanielleThierryUSDSVA for suggesting a copy edit and @RLHecht for undertaking it. Will keep you updated when we hear back from VACO. Is there where we should do a midpoint review?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @miabecker. I'd defer to @shiragoodman on platform review timing. 

Shira, wondering if this needs a midpoint review or can just go to staging since it's a content-only page? If it does need midpoint review, then I think it's okay to go ahead with that while waiting for VACO feedback and final copy edit. If staging-only, I'd suggest waiting until it's final. Thoughts?

**Comment by DanielleThierryUSDSVA** [comment]
Also, just to clarify: @RLHecht's final copy edit on this will truly be a proof (other than fixing the casing/"and" in the accordions because I'd originally deleted that content so she didn't see it in her initial pass). She already did a copy edit on the Word doc. So this is just a final double check that we didn't introduce any types or errors as we finalized/put in Drupal. Thanks!

**Comment by shiragoodman** [comment]
hi @miabecker (and thank you @DanielleThierryUSDSVA) - this can most likely skip a Midpoint Review since it is content-only (that path has always been somewhat blurry), and you can go straight to Staging. The Privacy and Security Review is mandatory, however, so be sure to check out our [page on Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) and let me know if you have any questions/concerns.

**Comment by DanielleThierryUSDSVA** [comment]
thanks, @shiragoodman!

**Comment by bevnobev** [comment]
Adding a link to the[privacy and security review page]( https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html  ), so I don't have to hunt for it later cc: @miabecker

**Comment by miabecker** [comment]
@bevnobev @toddstanich and I took an initial whack at the privacy and security review ticket here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/320 I think the main thing we need to sort through is the release plan - for which there is an example template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much, @RLHecht!

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA @RLHecht Thank you so much for the review. We need to remove the below bullet from the content given what we have learned about MyHealtheVet and how it works: "Through your My HealtheVet profile (for health care communications)" And @DanielleThierryUSDSVA can you help me understand our next steps? FYI we completed the Privacy & Security Review.

**Comment by miabecker** [comment]
@shiragoodman We have received Security and Privacy Approval. I know you said we don't need a midpoint review and could go into staging next. What do we do in order to move forward? Thank you! cc:@bevnobev @toddstanich

**Comment by DanielleThierryUSDSVA** [comment]
Hi @miabecker. We can remove that bulleted line, no problem. Are we still waiting for feedback from the legal reviewer? If no, then we'll just remove that one line and this will be ready for staging review. 

Then as soon as it's good to go live, just let @RLHecht know. We'll publish and it will go live in the next content release (usually within an hour or so during normal business hours). Thanks!

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA we just got the legal "ok" which is great. I think we can remove that one line and do a staging review.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @miabecker! That's great now. I removed that line/tweaked that section. Good to go to staging then. Thanks!

**Comment by shiragoodman** [comment]
hi @miabecker  - apologies for the delayed response but I was OOO Thursday-Monday. In order to move forward with a Staging REview, please follow the instructions on our [Staging Review touchpoint page on Platform Website. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) If you have any questions, please feel free to contact us on #vfs-platform-support on Slack.

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA @shiragoodman so sorry for not knowing the process but how do I get a link to the page in staging? We have our review set up but don't have a link for staging.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @miabecker! No worries at all. Drupal pages don't go to staging, so you can use the preview page: http://preview-prod.vfs.va.gov/preview?nodeId=34307

**Comment by miabecker** [comment]
We have successfully completed our staging review and are ready for production @DanielleThierryUSDSVA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. We got final concurrence from privacy today, so we're set to publish this page + the update to add a link to the main privacy page at https://www.va.gov/privacy-policy/.

Could you add a TOC to the terms & conditions page (if I didn't already) and then publish both pages? Thanks!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Both these pages are published. I'll close out the ticket once I validate it's live.

**Comment by RLHecht** [comment]
This page is now live https://www.va.gov/privacy-policy/digital-notifications-terms-and-conditions/ Closing ticket.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!
