### ISSUE TITLE
New url logic for Vet Centers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25894]
## Issue Description
When a Veteran selects a facility from the Facility Locator search results, that location's facility detail page is displayed. As the new Vet Center pages are rolled out, the existing Facility Detail pages for the specific locations will be archived and Veterans should be taken to the new page, similar to the flow for VAMC pages 

Redirects have been separately requested through PW to assist visitors who may arrive to the page via outside links.  (#25885)

Note: Outstations and Mobile Vet Centers have their own Facility Detail pages but will be part of their respective main Vet Center's Location page.

This needs to be a sustainable method, similar to the logic used to direct to new VAMC pages. Since Vet Centers do not have presence on VA.gov, the url field for the locations should currently be `null`. We are working with Lighthouse to have the urls added to the API. Once this happens, we should be able to replace the detail page url with the value sent by Lighthouse. 

**For any facility type,** 
- if Facilities API URL is populated with  "www.va.gov/", then use that URL as the hyperlink and direct Veterans to the new Drupal page
- if  Facilities API URL is `null` or contains a URL with anything beside "www.va.gov/", then use the facility ID and have a facility detail page

---
## Tasks
- [ ] Add logic to construct URL according to criteria, regardless of Facility Type (or remove the limitation in place for VAMC)

## Acceptance Criteria
- [ ] Maintain existing flow from Facility Locator to Detail page or Drupal (opens in the same tab)
- [ ] On the search results for the following Vet Centers, instead of the hyperlink going to a Facility Detail Page, the link should go to the Drupal page 
- [ ] Existing flow for Pittsburgh is maintained

For testing purposes: 

Vet Center | Current URL  |  Drupal URL
---  | ---  |  ---
*For reference* | *enter current URL* | *enter new URL*
Springfield, MA | www.va.gov/find-locations/facility/vc_0103V | va.gov/springfield-ma-vet-center
Great Falls | www.va.gov/find-locations/facility/vc_0538V | va.gov/great-falls-ma-vet-center
Orlando, FL | www.va.gov/find-locations/facility/vc_0314V | va.gov/orlando-vet-center
Escanaba, MI | www.va.gov/find-locations/facility/vc_0434V | va.gov/escanaba-vet-center
Escanaba, MI Mobile| www.va.gov/find-locations/facility/vc_0826mvc | va.gov/escanaba-vet-center
Reno, NV | www.va.gov/find-locations/facility/vc_0506V | va.gov/reno-vet-center
Reno, NV MVC | www.va.gov/find-locations/facility/vc_0867MVC | va.gov/reno-vet-center
Colorado Springs | www.va.gov/find-locations/facility/vc_0525V | va.gov/colorado-springs-vet-center
Rochester, NY | www.va.gov/find-locations/facility/vc_0124V | va.gov/rochester-vet-center
Rochester, NY Mobile |  www.va.gov/find-locations/facility/vc_0873MVC | va.gov/rochester-vet-center
Nashville, TN | www.va.gov/find-locations/facility/vc_0724V | va.gov/nashville-vet-center
Clarksville Outstation | www.va.gov/find-locations/facility/vc_7241OS | va.gov/nashville-vet-center
Cincinnati, OH | www.va.gov/find-locations/facility/vc_0204V | va.gov/cincinnati-vet-center
Concord, CA | www.va.gov/find-locations/facility/vc_0602V | va.gov/concord-vet-center

**Comment by mpelzsherman** [comment]
AFAICT there is nothing we need to do; once the VC `website` attribute is populated in Lighthouse, the links should “just work”.
