### ISSUE TITLE
Explore metatags for CMS content

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25892]
##  Description
Content from CMS is using [metatags.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/includes/metatags.drupal.liquid) to index content. As a product team we want to review the tags currently captured to explore various ways we could better present content to users

## Background/Context
|**Content Source**         |**Metadata**         |**Additional Details**| 
|-----------------------|------------------------------|------------------------------|
|Drupal (CMS)    "Modernized Content"         |[metatags.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/includes/metatags.drupal.liquid) |Initiated in 2019,Majority of all va.gov content, Slack Channel: #csm-support  |

## Tasks
- [ ] Review liquid template
- [ ] Discuss how metatags can be better utilized to allow users to filter results
- [ ] Determine if additional information should be captured to improve the search experience

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
