### ISSUE TITLE
Create Wireframes for Search Landing/Start Page for Usability Testing

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25908]
##  Description
We are planning to conduct a usability study to get user feedback on new design concepts for surfacing site search and other search tools. This issue is to create wireframes which can be used for the search landing/start page during that test. 

## Background/Context
[Research Plan: Search Design Concepts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-plan.md)

## Tasks
- [ ] Megan to establish wireframes which will include:
- Search input field
- Links to search tools
- [ ] If needed to meet to discuss the details will Megan will set up some time

## Acceptance Criteria
- [ ] Initial wireframe intended for use during the usability study is ready for team review ahead

**Comment by sshein** [comment]
I'm interested in this so just following along in the ticket :)
