### ISSUE TITLE
Create "MyCOE" page mockup as a standalone feature

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#25902]
### Background
To address IA concerns: users need a dedicated page to go to for their Certificate of Eligibility once it has been granted. We'll need to create a standalone feature to house the COE link.

### Tasks
- [x] Revise COE user flows/use cases
- [x] Create storyboards showing use flows
- [x] Create initial mockup of standalone "MyCOE" page

### Acceptance Criteria
- [x] User flow diagram crated
- [x] Use cases documented
- [x] Mockup created

**Comment by sporeboy** [comment]
The initial mockup is here: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139511607

Other states are available--just arrow-key forward and back.

**Comment by sporeboy** [comment]
Revised flow diagrams and use cases are here: https://xd.adobe.com/view/6c65f5c2-36e1-4051-81be-6f8b9415a3cd-3936/
