### ISSUE TITLE
Updates to decision reviews and Higher-Level Reviews pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#25917]
## Issue Description
Stakeholder Carolyn Temple provided content changes to the decision reviews and Higher-Level Reviews pages. We need to review these changes and update the content using plain language and VA.gov style. 

Doc to use for decision reviews page:
[https://app.zenhub.com/files/133843125/a5113c62-b276-443e-9afe-7dc0d067f8dd/download](https://app.zenhub.com/files/133843125/a5113c62-b276-443e-9afe-7dc0d067f8dd/download)

Doc to use for Higher-Level Reviews page:
[https://app.zenhub.com/files/133843125/ac61f37e-e1c5-4828-ab7b-0dec03edfd01/download](https://app.zenhub.com/files/133843125/ac61f37e-e1c5-4828-ab7b-0dec03edfd01/download) 

## Tasks
- [x] Rework content into plain language and make edits (Randi)
- [x] Review changes (Beth)
- [x] Send to stakeholders for review (Randi/Beth)
- [x] Review and publish pages (Randi)

## Acceptance Criteria
- [x] New content is live on VA.gov

**Comment by bethpottsVADEPO** [comment]
Thanks, @RLHecht! 
Decision Reviews page: In your note to the stakeholder about not removing "or appeal" from the H2, you could say that we'd want to look at removing the word "appeals" consistently on that page, so we'll put together a recommendation for that next week. And we will get the other edits live on Monday after she's had a chance to see the preview of our changes that take into account our PL standards.

H-L Review page: 
For that second bullet, I'd suggest saying, "If you want to speak with a reviewer on the phone, you'll need to choose that option when you apply for a Higher-Level Review."

For the changes where you removed the subway map: I totally agree with that call, and we'll see how they react to the change. Please explain in your note to them that you added messaging above the 3 sections explaining that we're giving them help with "certain sections." It could be a little confusing here to have the subway map since this isn't a step by step of _all_ the sections. So we wanted to clarify that we're providing selective/targeted help here just with sections 3, 4, and 5. And you can mention also what you talked about on the phone with me--that having subway map numbers that don't correspond to sections of the form could also cause confusion.

For Section IV: The contact preference isn't only who the Veteran wants called, but also the time frame in which they want to be called. So replace the second paragraph with: "To schedule an informal conference, you'll need to select 1 contact preference. Choose either a morning or afternoon time frame. And choose whether you want us to call you or your representative. If you'd like us to call your representative, please fill in their name and phone number."

Under What happens next?, I like how you broke up that long sentence and the other PLing you did! Just change this one sentence please: "You'll get a second survey about 1 week after you receive your decision notification letter."

All other edits I didn't comment on look spot on.

**Comment by RLHecht** [comment]
Preview links sent to stakeholders for review 6/14

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's a draft version of the R&S page of the decision reviews option table. I reworked some of their language to make it more plain language and I added in links to the forms as well as the online form for Higher-Level Review. Let me know what you think!

preview-prod.vfs.va.gov/preview?nodeId=23290

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks for creating the chart! Here are some edits for you to incorporate:

- In general we don't need to retain the labels on the left side of their chart. We should do whatever works best in ours. We probably need some kind of bold set up to each cell. Let's try this... 
- First row: **Type of review:**
- Second row: Select this option if... (this bold text will be part of the first sentence, so: **Select this option if** you're adding or identifying new and relevant evidence... (see if you can figure out what to do with the wording for the Board Appeal column).
- Third row: **Average number of days to complete a Supplemental Claim:**, etc. (Note: It makes sense to use the same language as we do for disability claims and would be good to call this out to the decision review team when we share this chart with them. Maybe share a screen shot of the box on the disability how to apply page.)
- Fourth row: **Submit this form:**
- Fifth row: **Your options after you submit a Supplemental Claim:**

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you swap out the Mark your calendar text for this?: 

**Learn about our 3 decision review options**
You’ll need to choose a decision review option. Your choice will depend on factors like if you have new evidence and if you want a hearing with a Veterans Law Judge. Find out which decision review option is right for you [this links to the new chart we created]

Then take a screen shot of the decision review landing page preview and send it to Carolyn along with a link to the preview of the new chart.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made updates to the chart based on OAR's edits. I did change all the "earlier"s to "prior" but let me know if you think we should push back on that. preview-prod.vfs.va.gov/preview?nodeId=23290

**Comment by bethpottsVADEPO** [comment]
OAR response on 7/8:

We are unable to approve the change to the word “earlier.”

Our concern here continues to be the connotation of those words. The word “prior” gives the connotation we’re referring to a more recent decision, which considering the filing time limitations would be more accurate. The word “earlier” gives the connotation that VA could be referring to any of the decisions (in some cases many decisions) that came before the Veteran applied for the decision review.

Even the dictionary provides different definitions for these words.
           Prior: existing or coming before in time, order, or importance
           Earlier: happening or done before the usual or expected time 
happening, belonging to, or done near the beginning of a particular time or period
 
We are unable to approve the change to “average number of days to complete a Supplemental Claim.”
In response to your question, yes, it does matter to our Veteran population that VA has specific goals and standards that we are driving towards and striving to meet. The goals we’ve set have already taken into consideration time factors such as “average number of days to complete,” “average days processing,” etc. Additionally, we are required (as part of VA’s core characteristics outlined in Title 38, Chapter 1, §0.602 ) to be transparent with Veterans, therefore, they are entitled to know what our goal is, and measure if we are meeting those goals based on their own experience with the process.

Additionally, by definition, “average number of days to complete” indicates a fluctuation. That will give the Veteran a feeling of instability, which is certainly not an empathetic nor Veteran-centric approach, especially when we cannot provide any context for the fluctuation around it within that page. However, the term “goal” is firm, fixed, and provides the Veteran with the assurance that VA is working to provide them with the benefits they deserve in a timely manner. The term goal is also concise, which is in accordance with plain language guidelines.

Finally, the “goal to complete” is different from the “average days to complete”. If we are to change to the average days to complete, we would need to remove the 125 day goal and instead provide the actual statistic of the average days to complete, which would need to be updated on the website each day.

We are unable to approve the removal of the word “goal” on the Higher-Level Review pages for the reasons stated above. We are unable to approve any changes to the Supplemental Claims pages, as those requests must go to Compensation Service. I have cc’d Paul Shute on this email for that purpose.

**Comment by RLHecht** [comment]
I published the new decision reviews article, the updated Higher-Level Reviews page, the R&S landing page with the new article added and the decision reviews hub landing page with the new alert pointing to the new page. Will send C.Temp! the live links after the deploy.

**Comment by RLHecht** [comment]
Changes are live and links sent. Closing ticket.
