### ISSUE TITLE
NOD: Show hint text for area of disagreement input

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25930]
## Description

Currently the "Something else" free text input has a character limit of 34 characters, but there is no hint text or indication of this limitation.

We're limited to a total of 90 characters by the schema. And if a user selects every checkbox, it only allows 34 characters for the input:

- 'The service connection' -> `service connection` submitted
- 'The effective date of award' -> `effective date` submitted
- 'The evaluation of my condition' -> `disability evaluation` submitted
- 'Something else' -> all text entered by Veteran

No space is added around the commas. So with all selections made, this is what the string would look like with a max of 90 characters:

```
"service connection,effective date,disability evaluation,1234567890123456789012345678901234"
```

In addition to the hint text, we should dynamically adjust the 34 character limit based on the Veteran's selections.

## Tasks

- [ ] Add "Something else" input hint text
- [ ] Dynamically adjust the "Something else" text limit

## Definition of done

- [ ] All tasks completed
- [ ] Tests all passing
