### ISSUE TITLE
[VAMC] Create csv file for VISN-10  Facility Health Services used to migrate into CMS Systems [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#25947]
## Story
As a data editor and customer, unique system health services need to be pulled from the system playbook and migrated through an automated process, so the process is scalable and accurate.

## Goal
Create a repeatable process that will allow for scalable input into the CMS system via data migration

## Resources
[Previous csv files](https://drive.google.com/drive/folders/1jpxDn49L4NonSd6bxya4HZX6kC56fCna)

## TASKS
**Transform playbook into a csv file following these steps**
- [ ] provide one single csv file with required columns for upload into CMS.
>	1. Pull system data into excel file and remove duplicates
>	a. File format must have the following headers:
>		i. ID; Health Services; Full Upload; Health System;, Owner
>             ii. ID; Facility ID; VAMC System Health Service; Facility Description of Service; Owner 
>	2. Combine all unique system files into one file for the VISN
>	a. Remove all "N/A" lines
>	b. Upload file to access.db for comparison  
>	c. Document number of lines remaining
>	d. Run query to combine Health service library with SHS
>	3. Export file
>	4. Combine columns
>	5. save as csv file
>	a. open in notepad or Notepad +
>	b. Open back up in excel
>	c. -	Delete the unused columns.  
>	Save again as csv
>	Open in Excel
>	Highlight Column A
>	Conditional formatting>highlight cell rules>Duplicate values
>	Look for duplicates and correct.
>	Save again as csv
>	Add brackets “$”
>	Do not bracket ID
>	Do not bracket title
>	Open Developer, View Code
>	Select Worksheet
>	Copy Bracket code under Private sub
>	Select range
>	Save new csv with “$”
>	Open new version in notepad
>	Select and ‘  (e.g. Veterans’) 
>	Change to ‘’  Single quote, single quote (Not “)
>	Do not want to have single quote before next move
>	Or triple.
>	Search (Ctrl H) replace $ with ‘ 
>	Look for Double quote
>	“’  change to ‘ (double quote,single quote)
>	‘” change to ‘ (Single quote, double quote)
>	“” change “ (Double-double quote)
>	Check for “”” (Triple Double quote)
Save final .csv file
Open in excel to confirm there are no breaks (Do Not Save from excel)

## Acceptance Criteria
- [ ] .csv file created with required column headers to be uploaded into CMS
- [ ] provide support and corrections to CMS engineer until PR is uploaded correctly with no errors.

**Comment by bcastoe** [comment]
#25947 - Create csv file for VISN-10 Facility Health Services used to migrate into CMS Systems - completed and moved to Validate3
