### ISSUE TITLE
Remove old authentication spec

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#25949]
## Issue Description
We upgraded rubocop-rspec recently, which pointed out that [this file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/request/authentication/standard_authentication_spec.rb) needed to have _spec.rb at the end of the filename. After adding that, we got a test failure and we think this was never actually running. After connecting with the original developer, they confirmed that the test can be removed. The test was trying to use vcr in reverse to play back requests from the FE essentially (namely “integration_recorder”). There may also be some code in initializers worth removing too.

---
## Tasks
- [ ] Remove the unused test
- [ ] Review for other code that could be removed

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
