### ISSUE TITLE
Midpoint Review: Decision Tools - Find a VA Form - Add Relevance, Popularity, Related Forms link

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25954]
## Steps to complete Midpoint Review 
- [X] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md)
- Link to or attach prototype or mockups
- Link to content brief (if applicable)
- Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link)   
   - https://www.va.gov/find-forms/?q=10-10ez
   - https://staging.va.gov/find-forms/about-form-10-10ez/
- Link to research plan - N/A
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more]
    - [Test Rail Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/136&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)
    - [Uses Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md)
   
## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [X] No
 
What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **June 17 at 1:30 PM ET**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): Marci McGuire
- OCTO-DE Product lead (recommended): John Hashimoto
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): names
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s)
Zachary Morel
Cassandra Allen
Josh Kim
Trevor Pierce
Angela Fowler
Tze chiu-Lei

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Midpoint Review scheduled for Thursday 6/17 at 1:30pm ET

**Comment by MarciMcGuireGCIO** [comment]
Update - we have de-scoped the PDF instructions from this release so we can do further exploration and possibly user testing.

**Comment by rtwell** [comment]
just tossing this here for transparency/awareness—while the Find a form search results are looking great, in terms of consistency across tools, i find it difficult to evaluate this work without seeing the other tools rendered with the same formatting. would you plz ping me when R&S and Site search have been updated? thank you!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @rtwell.  Makes perfect sense. I will ping Denise and Brian so they can circle back with you as they work through their own implementations.

**Comment by callen2563** [comment]
@zacharymorel Just copying my previous comments here from earlier today so they are on this new ticket:

1) I just took at look at staging where you adjusted the spacing for the divider lines. I think that looks much closer to the comp so I'm good. Thank you for doing that! :)

2) One more little thing I am seeing on staging is that there seems to be a link title that isn't formatted correctly see screen shot:
<img width="779" alt="Screen Shot 2021-06-16 at 1 11 27 PM" src="https://user-images.githubusercontent.com/68560244/122264474-93d3f780-cea5-11eb-8611-b3a68f69ad4b.png">

**Comment by callen2563** [comment]
@MarciMcGuireGCIO @rtwell I just chatted with @brianalloyd on our last call about R+S and he confirmed that R+S any changes to this page have been put on hold. Here are the latest R+S designs just for tracking for when we do get to a place where we can start building these updates out. 

![Resources   Support - mobile](https://user-images.githubusercontent.com/68560244/122265018-3ee4b100-cea6-11eb-9fe4-d98ec66213ce.png)
![Resources   Support - desktop](https://user-images.githubusercontent.com/68560244/122265021-3f7d4780-cea6-11eb-99aa-149df6fe578a.jpg)

**Comment by zacharymorel** [comment]
> @zacharymorel Just copying my previous comments here from earlier today so they are on this new ticket:
> 
>     1. I just took at look at staging where you adjusted the spacing for the divider lines. I think that looks much closer to the comp so I'm good. Thank you for doing that! :)
> 
>     2. One more little thing I am seeing on staging is that there seems to be a link title that isn't formatted correctly see screen shot:
> 
> 
> <img alt="Screen Shot 2021-06-16 at 1 11 27 PM" width="779" src="https://user-images.githubusercontent.com/68560244/122264474-93d3f780-cea5-11eb-8611-b3a68f69ad4b.png">

The Form Title's that are not links are just text because there is no Detail page associated with that result. 
I will update the Title to use the Form title Font.

**Comment by callen2563** [comment]
@zacharymorel Ok, got it. Yes, the font needs to change to Bitter. Thanks :)

**Comment by mnorthuis** [comment]
My IA feedback is in alignment with Peggy's content feedback in regards to link labels, so I did not open another ticket.

**Comment by zacharymorel** [comment]
@callen2563 Font changes should be on staging soon.

**Comment by zacharymorel** [comment]
@callen2563 @MarciMcGuireGCIO font updated!

![Screen Shot 2021-06-17 at 3 05 51 PM](https://user-images.githubusercontent.com/26075258/122458313-ad487280-cf7d-11eb-818a-cc0353bcc4a2.png)

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel !

**Comment by callen2563** [comment]
Thank you Zac!
