### ISSUE TITLE
[Content][Design][UI] Check-in Error Message Wording

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25975]
## Description
We need to notify Veterans when things don't go according the plan during check-in. Design needs to work with content to craft messaging for each of the following scenarios:

List of scenarios already in VeText (text message), but have never been reviewed by content. They must also be updated to reflect the new check-in use cases, but might remain generic to cover other uses.
**Unrecognized number:**
We apologize, but we do not have this cell phone number in our records.  
If you are trying to check in to a VA appointment, please use a cell phone that is on file with VA.  
Please call the VA facility if you need assistance.

**No appointments today:**
We apologize, but our automated system was unable to verify an appointment for you today.  Please call the VA facility to check in.

**"I am here" accepts the following keywords for checking in to appointments:**
HERE
ARRIVED
I'M HERE
I AM HERE
CHECKING IN

This [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1624301678227500?thread_ts=1623162568.403900&cid=C022AC2STBM) shows the suggested keywords for the Check-in product. To be discussed at meeting on June 22.

**In the event that an inbound text is not recognized by any of the VEText message processors, the following message will be sent (this must be adjusted for check-in/if a Veteran doesn't text here):**
This is an automated system and is not monitored. 
If you are asking a question please call %FACILITY_PHONE%, otherwise reply with the confirm or cancel responses in the reminder message.
If this message was sent to the wrong number, please text STOP.

**We also have the use case of Veterans will be sent to see a staff member if they have more than one appointment that day.**
- This new check-in specific error message will display as a text message too.
- Maybe add this to the poster too?

## Tasks
- [x] Confirm that all of these error states apply.
- [ ] Work with content on wording
- [ ] Document final wording

## Acceptance Criteria
- [ ] Work with VeText and Healthcare Experience teams to let them know about final wording, so they can create tickets

**Comment by kristenmcconnell** [comment]
@jparker0425 I just wrote this ticket. I might be a good candidate for next sprint as well. Just FYI, since I'll miss the next planning.

**Comment by kristenmcconnell** [comment]
Danielle and Kristen met on June 22 to discuss all the error messages needed.

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Forgot to update you on the outcome of the June 22 meeting. To eliminate confusion with the "I am here" product, Veterans will text "check in."

Here are all the version that the system is currently set up to accept:
CHECK IN”, “CHECK-IN”, “CHECKIN” and “CHECKING IN”

They aren't case sensitive either.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell. Let me know if you have questions or thoughts on these, or if any of them need tweaking depending on functionality. 
- For the unrecognized text message error, I think we should include the crisis line just in case. And please let me know if that one needs "We don't monitor..." language added back in. I think it's implied by the "automated system" but happy to work that back in if needed.
- For the unrecognized phone number error, I think we should consider including the crisis line.

Thanks!

### Unrecognized phone number
[text message 1]We don’t have this phone number in our records. Try again using a mobile phone that’s in our records. If you need more help, ask a staff member or call us. 
[text message 2] Find our phone number: [facility locator url]. If you’re in crisis, text 838255 for 24/7 confidential help.

### No appointments today
We're sorry. We couldn't find an appointment scheduled for you today. Ask a staff member or call us for help. Find our phone number: [facility locator url]

### Multiple appointments today
Our records show that you have more than one appointment with us today. Check in with a staff member. We can help you check in for each appointment.

### Unrecognized text
[text 1 of 2] We're sorry. Our automated system doesn’t understand your text. To confirm an appointment, reply CONFIRM. To cancel, reply CANCEL. To check in, reply CHECK IN.
[text 2 of 2] Questions? Ask a staff member or call %FACILITY_PHONE%. If you’re in crisis, text 838255 for 24/7 confidential help. To stop getting texts from VA, reply STOP.

**Comment by kristenmcconnell** [comment]
@Kennon-git @snyderje Looping both of you in, so you can provide feedback on the above messages.

Kennon and Julia - How are you determining %FACILITY_PHONE% in the unrecognized text scenario? Could we auto-populate the facility phone number in other scenarios instead of linking them to the facility locator tool?

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA My only comment is about the "We" in the multiple appointment text...

I was wondering if the Veteran could possibly get confused that that "We" is the text messaging system and not the staff member as you intended. Therefore, should "we" be changed to "they" or should we create a more complex sentence (such as below).

Our records show that you have more than one appointment with us today. Check in with a staff member, who can help you check in for each appointment.

**Comment by DanielleThierryUSDSVA** [comment]
Great question, @kristenmcconnell! I'm thinking we can revise and also not repeat "check in" twice while we're at it. How about:

Our records show that you have more than one appointment with us today. Ask a staff member to help you check in for each appointment.

And if we can add facility number in the unrecognized text message, that would be great!

**Comment by kristenmcconnell** [comment]
Thanks, Danielle!

**Comment by kristenmcconnell** [comment]
Further work will continue in #26880, which is assigned to @snyderje.
