### ISSUE TITLE
[Design] Notification settings - revisit design for status messages and notification channels

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25985]
## Background
Following usability testing of the notification preferences feature, we need to explore ways to improve clarity and comprehension for notification status messages, and the channels through which Veterans can receive notifications. We’ll work with our content team to ensure alignment on VA voice and tone.

## Tasks
- [x] Iterate on designs for status messages
- [x] Update designs to reflect new IA
- [x] Explore ways to help people understand which channels are available/which are not
- [x] Create mock-ups
- [x] Share with team
- [x] Review w/ a11y team
- [x] Review w/ content team
- [x] Update FE documentation 
- [x] Flag any updates for FE devs so they're aware

**Comment by andaleliz** [comment]
Worked through some concepts and am thinking going back to our auto-save idea is the way to go:
- It makes it clear to users which channels are available without them having to guess in read mode, and click edit to find out.
- It also makes it clear which notifications are turned on and off.
- From a technical perspective, it's not any more difficult (Erik actually said there are some technical benefits to going this route)

[Samara was on board with this idea from the beginning](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21855#issuecomment-808214205) and already had this concept reviewed during design intent, so we won't have to repeat that.

 Still need to work through error handling and mock-up how this might look for our partial contact info use case (we didn't explore that the first time), but wanted to capture these thoughts.

**Comment by andaleliz** [comment]
Mock-up showing partial contact information, with a missing mobile number.  It's likely this is what ~50% of users will see, since we have so many profiles without a mobile number on file, and the majority of our MVP notifications are text only:

![image](https://user-images.githubusercontent.com/55992116/125207008-13ac7200-e258-11eb-84bf-bfc138143bb2.png)

**Comment by andaleliz** [comment]
I reviewed my auto save concepts with our a11y specialists and have refined the recommendations.  I've prototyped them out, but content still needs to be reviewed for all of them.  

- Proceed with the modal UX (checkbox triggers confirmation modal), and add a "don't show this again" option in the modal.
  - **Why a modal?** It introduces a little friction to confirm people understand what they're doing.  Save buttons do this too, but without an "edit per group" model, they get buried at the bottom of the page.
  - "Don't show this again" will be useful for users who are updating multiple settings at once and are confident about their actions.  I think this should be session based (not forever based) to account for the fact that this isn't something people will be doing regularly, and to help users with cognitive considerations who may not recall their last session.
  
- On success: show users a `saved` toast message in line with the checkbox label once the modal closes. ([prototype](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140288788/simulate/sitemap?mode=i))
  -  added a green background (like our background only alert) to the toast to make it stand out more from the checkbox label
  - Hide after 5 seconds
  - A banner or alert feels like overkill in conjunction with the state of the checkbox

- On immediate fail: show an error message inside the modal, and let people try again ([prototype](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140313108/simulate/sitemap?mode=i))

- On a delayed fail: show a dismissible error message under the legend for the associated checkbox ([prototype](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140314200/simulate/sitemap?mode=i))
  - **Question**: Should we do this after a certain number of failed "try again" attempts?

What else have I missed?

**Comment by tmitchellgcio** [comment]
I like the "Don't show this again" and I agree it should be session based. The only thing we probably need to figure out is a pending state for when the API is waiting for a response. Something like this I would expect to be quick, but it makes sense to have some kind of loading circle. I'm kinda thinking where the saved is have a small loading circle until it's saved and then show the saved message.

**Comment by andaleliz** [comment]
@tmitchellgcio thanks for the feedback - that's a good call. I updated the first interaction on the [success example](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140288788/simulate/sitemap?mode=i) to reflect what I _think_ you're talking about. Is that what you were thinking?

**Comment by tmitchellgcio** [comment]
Absolutely! That is exactly what I was thinking

**Comment by andaleliz** [comment]
Cool - I updated my original comment. I'll persist it through the prototype screens (it's just in one place for now) once I hear back from others.

**Comment by lihanli** [comment]
that design should work fine with the backend api

**Comment by andaleliz** [comment]
Reviewed via Zoom with @erikphansen. Based on his feedback, I decided to keep the modal "don't show this again" option in our pockets as something we might do post-MVP. Giving people a way to do this without the modal increases the technical list by at least double, and also removes the friction added by the modal that ensures people understand what they're doing.

He also let me know we don't need to account for any errors other than the one represented in the modal in [this mock-up](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140313108/simulate/sitemap?mode=i).

I also discussed the design with some fellow VSA designers, and reviewed [this Slack thread](https://dsva.slack.com/archives/C0NGDDXME/p1624979738191700).  I'd like to persist the `update saved` badge instead of making it fade away. It's more accessible, plain and simple. Plus, I don't think it's distracting since it's subtle, and this behavior greatly reduces the risk that someone will miss it. 

I've [mocked up](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140348538/simulate/sitemap?mode=i) everything we've talked about so far.  The first checkbox is also wired up to show the opt-out functionality.

I reviewed the content with Danielle today (all reflected in the mock-ups) and she is going to do one last look over for any fine tuning via #27422 - content is pretty close to done though.

Going to put this in front of colleagues who are also Veterans tomorrow for a gut check - just want to make sure my hunch that the persistent labels and modal UX are not horribly cumbersome for anyone.

**Comment by andaleliz** [comment]
Reviewed my concepts with Ryan and need to pivot yet again.  [Created an abbreviated mock](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140373535/simulate/sitemap?mode=i) (doesn't include all notifications) to demonstrate the success alert functionality that uses the existing design system components we have.

**Comment by andaleliz** [comment]
@erikphansen and @tmitchellgcio I updated the[ FE specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/README.md) to capture all the changes; hopefully this is enough to go on while I'm out.  

I still need to make mobile versions of all these changes (will address in #27490), but mobile behavior should be straightforward. No funny business.

LMK if you have questions.

**Comment by erikphansen** [comment]
I'm sure this will keep me busy for the next week. Hopefully I'll make some progress before you return.
