### ISSUE TITLE
Midpoint Review: Booz Allen / Education Benefits - VA Form 22-5490, 22-0994, 22-1990E

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#25997]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [x] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to feedback tickets.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [Product Outline for Education Benefit Application Updates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/product-outline-IR-legislation.md)
- Link to or attach prototype or mockups
   - [5490](https://bahdigital.invisionapp.com/share/SZIAGWJTXCU) 
   - [0994](https://bahdigital.invisionapp.com/share/EKIAGNW2V86#/screens/296058971_0994-8-4-Review-Certify-Ad-Privacy-Policy)
   - [0994](https://bahdigital.invisionapp.com/share/EKIAGNW2V86#/screens/296058971_0994-8-4-Review-Certify-Ad-Privacy-Policy)
   - For 1990E see the following story for mock ups: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/24718
- Link to or specify the artifact that represents [this initiative's content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/5490/content/5490-content.md) (for example, mockup, prototype, Github, Word outline, or staging or preview link) 
- Link to research plan (N/A)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) 
   - 5490 Cross Browser: https://dsvavsp.testrail.io/index.php?/tests/view/80338&group_by=cases:section_id&group_order=asc&group_id=51
   - 5490 Accessibility: https://dsvavsp.testrail.io/index.php?/cases/view/4359
   - 1990E Cross Browser: https://dsvavsp.testrail.io/index.php?/runs/view/1553&group_by=cases:section_id&group_order=asc
   - 1990E Accessibility: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17712
   - 0994 Cross Browser: https://dsvavsp.testrail.io/index.php?/cases/view/4175
   - 0994 Accessibility: https://dsvavsp.testrail.io/index.php?/tests/view/50563&group_by=cases:section_id&group_order=asc&group_id=51
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) for QA practice area review
   - 5490: https://dsvavsp.testrail.io/index.php?/runs/view/1926&group_by=cases:section_id&group_order=asc
   - 1990E: https://dsvavsp.testrail.io/index.php?/runs/view/1925&group_by=cases:section_id&group_order=asc
   - 0994: https://dsvavsp.testrail.io/index.php?/runs/view/1773&group_by=cases:section_id&group_order=asc

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No
What is your preferred time slot per the Platform Collaboration Meetings Calendar? 07/06/21 @ 11:00AM

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @amyknox  - still working on this?

**Comment by shiragoodman** [comment]
hey @desireeturner  - even tho this is asynch, we still need you to choose a date/time because this is how we manage our workload. Thanks!

**Comment by shiragoodman** [comment]
Please choose one of the timeslots marked REVIEW BLOCK in the [Collab Cycle Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)

**Comment by desireeturner** [comment]
@shiragoodman Updated! 07/07/21 @ 11:30AM

**Comment by shiragoodman** [comment]
@desireeturner 7/7 at 11:30 is our office hours time :)

Could you pick another?

**Comment by desireeturner** [comment]
Oh jeeze sorry. How about 7/6 at 11AM? Does that give you all enough time?

**Comment by shiragoodman** [comment]
thanks @desireeturner ! You will receive feedback by EOD on Tuesday 7/6. Thanks!

**Comment by 1Copenut** [comment]
@amyknox Are there additional URLs for the 1990e and 0994 forms? The linked prototypes ( https://bahdigital.invisionapp.com/share/SZIAGWJTXCU ) appear to only be the first form, 5490.

**Comment by desireeturner** [comment]
@1Copenut Updated the issue with links to 0994 and 1990E. Sorry about that!

**Comment by 1Copenut** [comment]
@desireeturner There are two links to the same 0994 mobile InVision. Should one of them be a desktop, or can we review the changes on just the mobile version?

**Comment by peggygannon** [comment]
@desireeturner @amyknox  For this review, do all of the screens for each form need to be reviewed? Or have only certain screens been updated? Thanks for clarifying the scope for this.

**Comment by desireeturner** [comment]
@peggygannon I think it is probably easiest to review the changes called out in the implementation stories referenced in this section of the product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/product-outline-IR-legislation.md#solution-approach-legislative-updates--additional-form-updates

**Comment by mnorthuis** [comment]
There is no IA feedback for this review.  Thanks!

**Comment by dneel-bah** [comment]
All associated issues have been addressed and closed out.  Closing this issue.
