### ISSUE TITLE
Expandable alert - experimental design system

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26006]
## Issue Description
Now that we've implemented the expandable alert for Vet Centers, we need to complete necessary documentation/code for submitting the component to the experimental design system 

---
## Tasks
- [ ] Design: define metrics for success
- [ ] Engineering: availability (Fac folder/shared folder?)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
[PR for the new page lives here.](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/499#issuecomment-888236410)

**Comment by lildziner** [comment]
Created [page for the expandable alert on the Experimental Design Section ](https://design.va.gov/experimental-design/expandable-alert)of the Design System webpage.
