### ISSUE TITLE
[FSR] Add an 'additional info' component for 'Your dependents' screens (C2P12)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#26014]
## Issue Description
_The FSR's usability study highlighted that Veterans don't know why they need to include information about their dependents. The content and design team collaborated on content for an 'additional info' component to provide more information about why we're asking for dependent info._

The content: 

> Why do I need to include my dependents?
>
>We want to make sure we fully understand your financial situation.
> If you have dependents, we ask for number of dependents as well as their ages. This allows us to make a more informed decision regarding your request.

---
## Tasks
- [ ] Add an 'additional info' component and the corresponding the following pages:
   -  'Do you have any dependents?' page ([UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/139219203/simulate/sitemap?mode=i))
   - 'Enter each dependent's age' page ([UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/139219204/simulate/sitemap?mode=i))

## Acceptance Criteria
- [ ] _The FSR's UI has been updated to match the provided UXPin designs + content_
- [ ] _The UI changes have been reviewed by a designer_

**Comment by josephrlee** [comment]
Marking this as closed since it was accomplished with #63175

cc @HeatherRienks @Tom-Davis @denisecoveyduc @mgleo
