### ISSUE TITLE
NOD: Add pages to allow Veteran to update contact info

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#26013]
## Description

The Notice of Disagreement form requires the Veteran's email, phone and mailing address. If any of these are missing, the user can update this information within the form. Previously, we sent the Veteran to the profile page in a new tab.

Design: pending

## Tasks

- [ ] Add prefilled form elements to contact page 
- [ ] Update mock data
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] Tests are passing
