### ISSUE TITLE
[FSR] Wizard - Debt Dispute Content Improvements

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#26025]
As a Veteran looking to resolve debt, I want to understand under what kind of circumstances I can and should dispute my debt while i am on the selection wizard. 

## Tasks
- [ ] _Reach out to SME team for to confirm what kinds of debt qualifies for dispute and what kind of information veteran need to supply to successfully dispute their debt_
- [ ] _Audit the dispute pathway in the wizard to incorporate examples of debts that could qualify for disputes_
- [ ] _Audit the dispute section of the FSR's content page to incorporate examples of debts that could quality for disputes_ 
- [ ] _Draft content for the appropriate locations_ 

## Acceptance criteria
- [ ] _Content has been drafted_
- [ ] _Content has been sent to DMC SME's (Jill?) for review and approval_
- [ ] _Drafted content has been attached to this ticket_ 

**Note:** If the content hasn't been approved by DMC, we will need a follow-up ticket linked in this one capturing the following:
- [ ] _If the content is approved before end of the sprint, content has been reviewed by Danielle/Beth during office hours_
- [ ] _Create follow-on tickets for frontend and public websites to implement the approved content_

**Comment by rileyorr** [comment]
FYI updated the description to more accurately capture the work that goes into this and assigned myself and Becca to support Troy with this ticket
