### ISSUE TITLE
Platform Website — Train Platform teams to successfully contribute to Platform website

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26033]
## Problem Statement 

In 2021 Q2, we ran and socialized a training session for Platform teams to learn how to contribute to the Platform Website.  However, we still expect teams to have questions.

_HMW ensure that Platform teams understand the guidance well enough to start contributing to the Platform website?_

## Hypothesis or Bet

If we proactively host support sessions for Platform teams, then we will:
- reduce Platform teams' confusion and uncertainty as they balance Platform website work with initiative work, and
- build Platform teams' trust and confidence in the Content team.

If we reduce Platform teams' confusion in contributing to the Platform website, then they will be more likely to contribute to the Platform website.  This in turn will both increase customer (VFS) satisfaction with the Platform.

_(We also hypothesize that this will become an ongoing service_ in Q4 _after we establish the process of providing support.)_

## We will know we're done when... ("Definition of Done")
- [x] Engineering teams have conducted their audits.
- [ ] Engineering teams have Q4 plans based on their Q3 audits.
- [ ] Experience teams have migrated their content from GitHub to the Platform website.
- [ ] Experience and Engineering teams feel confident that they will be able to contribute to the Platform website in future quarters, with minimal assistance from the Content team.

## Known Blockers/Dependencies 
* All Platform Teams - Platform Teams will need to dedicate time to understanding the guidance we deliver.

## Projected Launch Date
August 2021

## LAUNCH CHECKLIST

<details>

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).
</details>

## REQUIRED ARTIFACTS

<details>

### Documentation
* **`PRODUCT_NAME`**: Platform Website [repo directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website)
* **Product Outline**: Platform Website [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/platform-website-product-outline.md)
* **README & User guide**: [Platform website guidelines](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines)

### Testing

n/a - Platform teams will be testing their content on a team-by-team basis 

### Measurement

* **Success metrics**: 
  * Platform teams' sentiment with the support we've given in Q3
  * Platform teams' confidence in contributing to Platform website in Q4 with minimal handholding from us
  * Content team's sentiment regarding the volume of support we're giving
  * Eng teams' success in auditing their content (y/n)
  * Exp teams' success in migrating their content (y/n)
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26034

</details>

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by vbellissimo** [comment]
Cancelling/old task.
