### ISSUE TITLE
Platform Website — Discovery: Transform high-value documents

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26035]
## Problem Statement 

In 2021 Q1, the Content team scrappily compiled the Platform website from the old Home Page MVP.  But, we aren't sure if:
(a) any of the current "Getting started" information is helpful to VFS teams, and
(b) the Platform could be giving VFS teams any _other_ additional helpful information.

_HMW make general info to build on the VA.gov Platform more transparent and accessible?_

_HMW leverage prior work to fill customer experience gaps?_

References: 
- [Platform website's "Getting started" section](https://depo-platform-documentation.scrollhelp.site/getting-started/)
- [Platform website's "Support" section](https://depo-platform-documentation.scrollhelp.site/support/)
- [Old Home Page MVP](https://department-of-veterans-affairs.github.io/va.gov-team/)

## Hypothesis or Bet

If we strategize how the Platform can fill in high-value info on the Platform website](https://depo-platform-documentation.scrollhelp.site/getting-started/), then we will provide a documentation experience that will reduce questions to the #VFS-platform-support channel.

If we leverage competitive analysis and previous VFS user journey research, then we can identify VFS documentation experience gaps.

## We will know we're done when... ("Definition of Done")
- [x] We've published a (living) list of high-value documents that currently do not exist on the Platform website.
- [ ] We've identified the subset of high-value documents that we'll focus on in Q4
- [ ] We've determined what "focusing on" means: Writing, co-writing, supporting?
- [ ] We've established processes for working with these high-value docs' owners

## Known Blockers/Dependencies 
* **Platform leadership:** We'll be identifying owners of certain Platform-wide documentation, which involves conversing with Platform leadership to tease apart responsibility and accountability.  
* **Platform teams (not sure which ones yet):** Same vein - in identifying owners, it's possible that several Platform teams (either PMs or TLs) will be SMEs for certain Platform-wide docs.
* **Service Design:** We'll revisit the VFS user journeys (and potentially the top task research) to see if we can identify Platform-wide documentation.

## Projected Launch Date
End of Q3.

## LAUNCH CHECKLIST

<details>

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).
</details>

## REQUIRED ARTIFACTS

<details>

### Documentation
* **`PRODUCT_NAME`**: Platform Website [repo directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website)
* **Product Outline**: Platform Website [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/platform-website-product-outline.md)
* **README**: n/a - Platform Website is currently not VFS-facing
* **User Guide**: n/a - Platform Website is currently not VFS-facing

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: 
  * Because this initiative is for discovery and solution approach proposal, success = completion of the initiative, as described in the definition of done above
  * Success metrics for implementation - ie, actually transforming the high-value docs - are TBD  
  * One measure: Complexity of each process, perhaps as measured by the number of folks Content has to work through
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26036

</details>

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by vbellissimo** [comment]
Cancelling/old task.
