### ISSUE TITLE
Notice of Disagreement - Power of Attorney update

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26039]
## Issue Description
Remove POA text field

---
## Tasks
- Remove the text field. 

 

## Acceptance Criteria
- [ ] Free entry text field removed.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
