### ISSUE TITLE
Platform Website — Empower Platform teams to monitor page health

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26037]
## Problem Statement 

To sustain customer satisfaction, all Platform teams are expected to contribute and maintain information on the Platform website.  But, teams currently do not have a standard, cross-Platform way of identifying the obsolete documentation they have to update.

_HMW empower Platform teams to maintain the content they contribute to the Platform website?_

References: 
- [Google Analytics dashboard](https://analytics.google.com/analytics/web/#/report/content-overview/a50123418w224573768p240292331/)
- [WIP health tracker](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1337458762/Test+page+report+macro)
- This initiative accompanies https://github.com/department-of-veterans-affairs/va.gov-team/issues/26033 , our 2021 Q3 support ticket
- [The va.gov-team repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master)

## Hypothesis or Bet

If we build/socialize a dashboard that displays a page's health*, then teams will be able to quickly identify the pages that most urgently need maintenance.

*Factors that comprise page health yet TBD.  We are identifying those factors as part of this initiative. 

## We will know we're done when... ("Definition of Done")
- [ ] We have identified factors that define "page health."
- [ ] The page health dashboard automatically includes new pages.
- [ ] The dash has been socialized to OCTO-DE and Platform teams.
- [ ] The dash lives in the appropriate operational docs space.

## Known Blockers/Dependencies 
* (Lack of) knowledge around Atlassian's Confluence Cloud - we may have to interact with Scroll Viewport's customer service.

## Projected Launch Date
TO COME.

## LAUNCH CHECKLIST

<details>

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).
</details>

## REQUIRED ARTIFACTS

<details>

### Documentation
* **`PRODUCT_NAME`**: Platform Website [repo directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website)
* **Product Outline**: Platform Website [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/platform-website-product-outline.md)
* **README**: To come.
* **User Guide**: To come.

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: 
  * Number of questions we receive from Platform teams and OCTO-DE about the tracker
  * Number of factors that comprise "page health"
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26038

</details>

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by vbellissimo** [comment]
Cancelling/old task.
