### ISSUE TITLE
Staging Review [Contact Center Team - Medallia User Surveys]

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#26047]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] Platform: Schedule meeting with Platform reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] Platform: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to Platform feedback tickets.
- [x] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/product-outlines/medallia-product-outline.md)
- Prototype
Intercept Survey: https://staging.va.gov/find-locations/facility/vha_691

![image](https://user-images.githubusercontent.com/48964695/96185544-0ac88300-0f08-11eb-8b9e-627f9149824f.png)
![image](https://user-images.githubusercontent.com/48964695/96185445-e79dd380-0f07-11eb-9184-6f6e1dad7b06.png)
![image](https://user-images.githubusercontent.com/48964695/96185492-f8e6e000-0f07-11eb-91aa-288318fc968d.png)

Feedback Survey: https://staging.va.gov/find-locations
![image](https://user-images.githubusercontent.com/48964695/96181207-a0acdf80-0f01-11eb-93db-5874758faae7.png)
![image](https://user-images.githubusercontent.com/48964695/96181221-a86c8400-0f01-11eb-8ddd-68dbd5fcfcd8.png)
![image](https://user-images.githubusercontent.com/48964695/96181237-af939200-0f01-11eb-8328-50bf0bbb537e.png)
-  Staging test-user information (if applicable)
-  Link to [content brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/product-outlines/medallia-product-outline.md)
-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link) 
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17925) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Link to your product test cases/test plan in TestRail with test execution logs - NA
- Link to your [Coverage for References]- N/A
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail Platform accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): @jwoodman5 
- OCTO-DE Product lead (recommended): @clantosswett 
- OCTO-DE Design lead (required): 
- Anyone else from your team who significantly contributed to the artifacts provided (required): @ianMcCullough-ob 
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Scheduling
What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **6/24/21 - 1:30pm**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by jwoodman5** [comment]
@shiragoodman Our preferred time slot for this would be 6/24 @ 130pm, if possible. Thanks!

**Comment by allison0034** [comment]
@jwoodman5 the product outline is getting a 404 error

**Comment by jwoodman5** [comment]
Hi @allison0034 - Should be good now.

**Comment by shiragoodman** [comment]
@jwoodman5  - the Zoom recording has been added to the [Platform Collaboration Point Tracker. ](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886)

**Comment by pjhill** [comment]
No QA artifacts are available for review, so Platform has no QA-related feedback.
