### ISSUE TITLE
R&S Updates: Verifying your identity on VA.gov

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26044]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/verifying-your-identity-on-vagov/).

- Under related information, add **Privacy and security on VA.gov**. 

- Instead of just Go to Experian.com, add the action we want them to take there: **Go to Experian.com to get your credit report**

- For consistency, add the .com to the link below that one:
**Go to Experian.com to file a dispute**

### Tasks

- [ ] DEPO to approve changes as described above, or edit (Beth)

- [ ]  SC to make changes in Drupal (Laura)

- [ ]  SC to QA and publish (Randi)

### Acceptance Criteria

- [ ]  Updated page is live

**Comment by bethpottsVADEPO** [comment]
These changes look good--thank you! @lwalsh617

**Comment by lwalsh617** [comment]
@RLHecht - On the multiple faqs page, I keep getting a "403 Forbidden" message on this link under related information: **Privacy and security on VA.gov**. It's an R&S page where Linkit is pulling up the URL automatically. 
Aside from that, these pages are ready for you to review and publish. Thank you!
**Multi faq page:**  http://preview-prod.vfs.va.gov/preview?nodeId=8233
**Single faq page**: http://preview-prod.vfs.va.gov/preview?nodeId=8230

**Comment by RLHecht** [comment]
These changes are all good and have been published. Moving to validate and will close after live on the site.
