### ISSUE TITLE
Adding link to HIPAA privacy info from health care hub

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26052]
## Issue Description
We need to add a link to HIPAA privacy info from our health care hub. We need to determine the best place to link from and what the teaser text will be.

Link to add: 

## Tasks
- [ ] Add link to health care page
- [ ] Review and publish page
- [ ] Notify stakeholders

## Acceptance Criteria
- [ ] HIPAA link is on health care hub page

**Comment by RLHecht** [comment]
This can stay in backlog for when we are ready to work on it. We need to add what the HIPAA link will be (it's currently missing from the top of the ticket). @DanielleThierryUSDSVA Do you know what it would be?
