### ISSUE TITLE
R&S Updates: Deciding how much life insurance to get

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26055]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/deciding-how-much-life-insurance-to-get/):  

Replace "below" in intro: 
**Keep reading this page to find out what information you'll need to have ready when using the calculator.**

Add "free financial planning services" under related information. (We have it as a text link, but that's easy to miss and it seems like a benefit that bears repeating.) 
Links to: https://benefits.va.gov/insurance/bfcs.asp

### Tasks

- [ ] DEPO to approve changes as described above, or edit (Beth)

- [ ] SC to make changes in Drupal (Laura)

- [ ] SC to QA and publish (Randi)

### Acceptance Criteria

- [ ] Updated page is live

**Comment by lwalsh617** [comment]
@bethpotts -- Let me know if I should go ahead and make the changes at the top of this ticket. Thanks!

**Comment by lwalsh617** [comment]
Closing this ticket. Live article in resources and support:
Deciding how much life insurance to get

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 reopening this ticket since the changes haven't been made yet.

1/ Change the last sentence to: 
Keep reading on this page to find out what information you'll need to use the calculator.

2/ Yes, link to free financial planning page from related links. You can list it as the first of the 3 related info links.

**Comment by lwalsh617** [comment]
@RLHecht - I made the changes per Beth's comment ^. Ready for you to review and publish. Thanks!
