### ISSUE TITLE
526 - PTSD VADIR alternatives

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26065]
## Issue Description
Determine what screens in PTSD flow will be necessary if a user does not have medals.

---
## Tasks
- [x] Document required screens.

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- [x] Mural board with all screens that will exist and be potentially removed when we have data from Vadir abut medals. 
- [x] https://app.mural.co/t/vsa8243/m/vsa8243/1621527646392/bb806d29d33f781bdbeb542beef8046d11bfe659?sender=cvalla7693
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
https://app.mural.co/t/vsa8243/m/vsa8243/1621527646392/bb806d29d33f781bdbeb542beef8046d11bfe659?sender=cvalla7693

**Comment by chrvalla** [comment]
This is completed. All screens that can be removed when we front-load Vadir data on medals have been identified and described in the Mural link below. These have been confirmed by Paul Shute. 

https://app.mural.co/t/vsa8243/m/vsa8243/1621527646392/bb806d29d33f781bdbeb542beef8046d11bfe659?sender=cvalla7693
