### ISSUE TITLE
Notice of Disagreement - Email

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26064]
## Issue Description
We need to create a custom design solution for the email, phone number and address on file for an applicant. Per the BVA, we can't collect this contact information on the form because it may differ from what gets pulled from the veteran's profile data. This creates confusion within their business process. So until that process can be fixed, we have to use what's in their profile only.

At this time, there's no way to change the profile data from a form on va.gov. That functionality is coming in the future. We will need to design a workaround for the time being.

When a user wants to update their contact information via the profile, we have technical limitations. The form needs to be restarted and refreshed in order for the profile data to get appended to the form flow data. Instructing the user in how to ensure their data is added to the form (via a multi-step process) is confusing. Therefore this limitation provides a multitude of usability challenges.

We will have to create a design that smooths over these requirements to make it more usable.

---
## Tasks
- [ ] Create a new flow for the NOD contact page, whereby only profile data is shown and can only be updated in profile

## Acceptance Criteria
- [ ] A new flow for the NOD contact page has been created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
A few options have been explored and the new flow has been created. It can be found here:

https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/MyWwKO7
