### ISSUE TITLE
PTSD Vadir data research - Followup

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26066]
## Issue Description
Respond to email from VADIR contact, determine how to accesss data.

---
## Tasks
- [ ] Continue email discussion.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
Robin will do a small discovery into retrieving data directly.
If this is negative, we will wait with this project until VA profile have the data from Vadir.

**Comment by vhenry07** [comment]
Closing this ticket and will open a new one for further discovery.
