### ISSUE TITLE
Staging Review Search & Discovery-Search UI Consistency Pattern for Global Search Pages

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26080]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [x] Platform: Schedule meeting with Platform reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] Platform: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to Platform feedback tickets.
- [x] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- [Review Environment for Search UI Consistency Changes](http://9539582b1f3adeff216a5e21e806d315.review.vetsgov-internal/)
-  [Product outline- Search UI Consistency](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/search-ui-consistency/product-outline.md)
- [Invision Link - Showing Global Search Pages](https://vsateams.invisionapp.com/console/share/SD10IE31CENR/614352925)
- [Spreadsheet - Outlining Design Elements](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit#gid=0)

- These UI Changes plan to be released on Staging + Production on June 29, 2021 
- There is no test plan or automated testing since this is for UI Changes only.

## Meeting attendees from requesting team
- Product Manager (required): Denise Coveyduc
- OCTO-DE Product lead (recommended): John Hashimoto
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Megan Gayle, Sam Suddath
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Scheduling
Preferred time slot - Tuesday, June 22 @11am est

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@denisecoveyduc you requested a timeslot that is in the past... Can you please update?

**Comment by denisecoveyduc** [comment]
@shiragoodman Doh! oops..sorry about that error. I meant the 22nd. I have updated the comment above as well.

**Comment by shiragoodman** [comment]
@denisecoveyduc scheduled for 6/22 at 11 am ET

**Comment by tlei123** [comment]
No QA needed; internal design-reviews should suffice for these styling-only changes.

**Comment by ahatfield1** [comment]
@denisecoveyduc I am getting an error when I try to access Review Environment for Search UI Consistency Changes

This site can’t be reachedCheck if there is a typo in 9539582b1f3adeff216a5e21e806d315.review.vetsgov-internal.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by denisecoveyduc** [comment]
@ahatfield1 Thanks for bring this to our attention. @srsuddath is looking into it and we will update this ticket once the issue has been resolved. Review instances are a bit finicky.

**Comment by joshkimux** [comment]
@denisecoveyduc , I also have been getting the same error when trying to access the review environment

**Comment by srsuddath** [comment]
Review instance should be live again (it had timed out over the weekend)
http://9539582b1f3adeff216a5e21e806d315.review.vetsgov-internal/
@joshkimux, @ahatfield1

**Comment by srsuddath** [comment]
Do you have your socks proxy enabled? I just verified it is working.

**Comment by allison0034** [comment]
@srsuddath I do not have socks access

**Comment by peggygannon** [comment]
@srsuddath Most of us on the Platform Product Support team don't have SOCKS access. 

Are you able to share a staging or CMS preview link?

**Comment by srsuddath** [comment]
This content isn't able to be hidden by a feature flag (it is mostly styling on the search results page) so reviewing it in staging is impossible, as for a CMS preview link I am not sure, but I don't think so.

@denisecoveyduc any idea here what the best way forward is?

**Comment by denisecoveyduc** [comment]
Thanks @srsuddath  I defer to @shiragoodman How would you like to handle these UI changes? As mentioned as discussed in our last touchpoint these changes can't be hidden by a feature flag.

**Comment by denisecoveyduc** [comment]
@sshein @rtwell  - we have the review instance issue sorted out if you'd like to see the UI Consistency Changes on the global pages. http://9539582b1f3adeff216a5e21e806d315.review.vetsgov-internal/

**Comment by mnorthuis** [comment]
FYI, there is no IA feedback on these changes.  

I did have a question though - for the change to the search button to always have it active, what is the result if a user clicks the search button but has not entered any search value?  I believe this scenario could apply to Find a VA Form and Resources and Support search.

**Comment by pjhill** [comment]
No test artifacts are available for this effort. Platform QA has no feedback.

**Comment by mgleo** [comment]
@mnorthuis This is currently in development but if the user doesn't enter a search term, they will get a message that reads "We didn't find any results. Enter a keyword in the search box to try again."

**Comment by mnorthuis** [comment]
Thanks @mgleo, I'm going to add an IA feedback issue for this one, just to make sure that user flow is handled.

**Comment by denisecoveyduc** [comment]
Thanks @mnorthuis!   We will be on the look out and link it with the issues that are being resolved now. Appreciate this!

**Comment by denisecoveyduc** [comment]
All issues have been resolved. Closing this staging review issue.
