### ISSUE TITLE
[Documentation] Create Documentation for Kubernetes Development - Local Development

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#26094]
## Description
Developers will need to transition from a docker-compose style of local development to use tools that are more compatible/friendly to Kubernetes, as it is somewhat difficult to translate local development environments using Docker Compose to a K8s application manifest (depending on features used, especially local mounts)
- Do some research into local development for K8s, and document some recommendations
- Keep in mind that the final output should be ArgoCD/Github Actions friendly

## Background/context/resources
Some things I have looked at, but by no means exhaustive or recommended!:

- https://www.telepresence.io/discussion/overview
- https://docs.tilt.dev/
- https://garden.io
- KIND
- minikube
- k3s

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _Research some local development techniques for K8s_
- [ ] _Perhaps involve the BE tools team?!_
- [ ] _Document some local development processes/tools that we recommend_

## Definition of Done
- [ ] _Documentation is stored in Confluence_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Please see here: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28663
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28664
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28665
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28668
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28669

Closing.
