### ISSUE TITLE
[Documentation] Kubernetes Development: Application Manifests

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#26093]
## Description
Create Documentation for Developers
In order to assist developers in onboarding/modifying applications in the new infrastructure, we need to document the following things:
- Creating Application Manifests for Kubernetes
- Jsonnet usage (if any is necessary) for ArgoCD

Documentation should be in the VFS Confluence, in the Operations Team space: https://vfs.atlassian.net/wiki/spaces/OT/overview?homepageId=1391854287

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Create documentation for how to write application manifests
- [ ] Separately, if needed, document what Jsonnet knowledge might be necessary, and link appropriately

## Definition of Done
- [ ] Documentation is written and properly placed in Confluence

**Comment by jhouse-solvd** [comment]
@dginther - this is what you and I quickly drafted before as a start: 

https://vfs.atlassian.net/l/c/KcX4mACk

**Comment by oseasmoran73** [comment]
@jhouse-solvd With our onboarding application and [confluence](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594088/Create+and+deploy+a+Kubernetes+EKS+Cluster+on+the+Platform) I am wondering if we can close this ticket

As we get more feedback, I think we can def iterate & spin up new tickets (like how we have been doing). Thoughts?

Relevant ticket https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/36389

**Comment by jhouse-solvd** [comment]
@oseasmoran73 - I'm good w/ that. We will also likely be scoping developer-facing documentation as part of this initiative: 

Application Hosting and Deployment: Solidify application onboarding process for Platform Crew teams (EKS) #38890

Closing.
