### ISSUE TITLE
[FSR] Provide content to ease Veterans' worries about providing real estate, vehicles, and other assets

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#26097]
## Issue Description
_The FSR's usability study confirmed that Veterans are extremely worried about providing information about their assets such as real estate, vehicles, and other assets. We need to add empathetic content to these parts of the form to ease Veterans' concerns that VA will repossess their assets_

---
## Tasks
Updates to the following pages:

**Real estate**
[Page 1 UXPin prototype](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691645/simulate/sitemap?mode=i)
- [ ] Add hint text under the question 'Do you own any real estate?': `This includes real estate with a mortgage.`
- [ ] Add an 'additional info' component with the content:

> Why do I need to provide this information?
>
>We want to make sure we fully understand your financial situation. We ask for details about your real estate assets because it allows us to make a more informed decision regarding your request.
>
>We won’t take collection action against real estate you own in order to resolve your debt.

[Page 2 UXPin prototype](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139699198/simulate/sitemap?mode=i)
- [ ] Add an 'additional info' component with the same content as above 
- [ ] Update the prompt from `Enter each of your real estate assets below.` **to** `Enter each of your real estate assets below. Please include assets with a mortgage.`

**Cars and other vehicles**
[Page 1 UXPin prototype](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691649/simulate/sitemap?mode=i)
- [ ] Add an 'additional info' component with the following content:

> Why do I need to provide this information?
>
>We ask for vehicle details because this allows us to make a more informed decision regarding your request.
>
>We won’t take collection action against your cars or other vehicles in order to resolve your debt.

[Page 2 UXPin prototype](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691648/simulate/sitemap?mode=i)
- [ ] Add an 'additional info' component _above_ the existing 'additional info' component with the following content:

>Why do I need to provide this information?
>
>We ask for vehicle details such as type, make, model, year, and estimated value because this allows us to make a more informed decision regarding your request.
>
>We won’t take collection action against your cars or other vehicles in order to resolve your debt.

**Other assets**
[Page 1 UXPin prototype](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691651/simulate/sitemap?mode=i)
- [ ] Add an 'additional info' component with the following content: 

>Why do I need to provide this information?
>
>We ask for details about items of value such as jewelry and art because it gives us a picture of your financial situation and allows us to make a more informed decision regarding your request.

[Page 2 UXPin prototype](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691650/simulate/sitemap?mode=i)
- [ ] Add an 'additional info' component _above_ the existing additional info component with the same content as above 

## Acceptance Criteria
- [ ] _The real estate pages have been updated with the new components and content_
- [ ] _The real estate pages match the provided UI_
- [ ] _The cars/vehicles pages have been updated with the new components and content_
- [ ] _The cars/vehicles pages match the provided UI_
- [ ] _The other assets pages have been updated with the new components and content_
- [ ] _The other assets pages match the provided UI_
- [ ] _The UI changes have been reviewed by a designer_

**Comment by josephrlee** [comment]
Closing this ticket as the work was done by #22842.

cc: @Tom-Davis @dhill802 @mgleo @denisecoveyduc @charlottecesana
