### ISSUE TITLE
[Variant Test] Sorting Facilities-tracking events

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26106]
## Description
Add tracking to facility selection variant test so performance can be measured.

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_variant_testing` feature flag
- [ ] ANALYTICS - Track occurrences of this variant (_Note- Product will use this event in combination with the Users and Pageviews metrics in GA_)
- [ ] ANALYTICS - Track default sort type
- [ ] ANALYTICS - Track sort by location selections (ok if multiple events per user or session)
- [ ] ANALYTICS - Track sort alphabetically selections  (ok if multiple events per user or session)
- [ ] ANALYTICS - Track sort by address selections  (ok if multiple events per user or session)
- [ ] ANALYTICS - Track "final" sort type when user clicks Continue

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] All event names and related data are documented in this ticket

**Comment by jbalboni** [comment]
This is what I have for events:

Variant shown (fired once per form use):
vaos-variant-shown

Default sort (fired once per form use):
vaos-variant-default-distanceFromResidentialAddress
vaos-variant-default-distanceFromCurrentLocation
vaos-variant-default-alphabetical

Sort method changed (fired once per change):
vaos-variant-method-distanceFromResidentialAddress
vaos-variant-method-distanceFromCurrentLocation
vaos-variant-method-alphabetical

Final sort method (fired once per continue button click):
vaos-variant-final-distanceFromResidentialAddress
vaos-variant-final-distanceFromCurrentLocation
vaos-variant-final-alphabetical

**Comment by laurenernest** [comment]
added to test document and GA dashboard. closing ticket.
