### ISSUE TITLE
Document Vet Center content intent

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26103]
## Issue Description
While the Vet Center product is still slim, we need to begin documenting decisions, intent and CMS guardrails. The Content deck created to support local staff can provide a starting point

The following documents will be helpful for reference:

- [Vet Center governance mural](https://app.mural.co/t/vsa8243/m/vsa8243/1610485243350/283ad6aab54a8808973aeff9c7c0e586086573b0)
- [Vet Center Content Deck updated.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6658724/Vet.Center.Content.Deck.updated.docx)
- [Vet Center Operating status April 2021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6658725/Vet.Center.Operating.status.April.2021.docx)
- [Vet Center content deck service list April 21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6658726/Vet.Center.content.deck.service.list.April.21.docx)
- [VA Design system content style guide](https://design.va.gov/content-style-guide/)

### Audience for this documentation
The document should have a nontechnical tone
- Vet Center Outreach specialists and directors (who write the content for their local Vet Center)
- Vet Center leadership
- Facilities team members 

### Vet Center pages and sections
Main page
- Intro paragraph
- Location and contact information
  - Operating status
  - Photos
- Prepare for your visit
  - Appointments
  - Parking
  - Transportation services and schedule
  - What to bring
- In the Spotlight
  - National Spotlight
  - Local Spotlight 1
  - Local Spotlight 2
- Services
  - National
  - Local

Locations page
- Satellite Locations
  - Outstations
  - Mobile Vet Centers
  - Community Access Points
- Other nearby Vet Centers

---
## Tasks
Enhance Vet Center content deck, ensuring that the following are documented where appropriate:
- [ ] Screenshots from the page in production
- [ ] Screenshots from Drupal
- [ ] Purpose of page/section
- [ ] Who can edit each section
- [ ] Which fields are required in Drupal
- [ ] Which fields are required by business process
- [ ] Is there default content - and if so, is it editable?
- [ ] Character limits
- [ ] Best practices/ top tips
- [ ] Do/don't do examples 
- [ ] Accessibility considerations
- [ ] Links to VA.gov content style guide where appropriate

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by mmiddaugh** [comment]
Draft sent to Dave for review
