### ISSUE TITLE
[FE] Preferred Facilities: Redux actions and Reducers

### ISSUE THREAD

**Issue by tmitchellgcio** [department-of-veterans-affairs/va.gov-team#26101]
## Background

We need to ensure proper loading and saving of data

## Tasks

- [ ] Create actions and reducers to get preferred facilities
- [ ] Create actions and reducers to add preferred facilities
- [ ] Create actions and reducers to remove preferred facilities
- [ ] Test!!!

**Comment by tmitchellgcio** [comment]
Closing issue because after discussing this is not a feature they need
