### ISSUE TITLE
Create topline summary for COE usability testing

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#26127]
### Background
We need to generate a high-level summary of initial findings for COE usability testing.

### Tasks
- [x] Create topline summary
- [ ] Discuss finding with team
- [x] Make summary available to team

### Acceptance criteria
- [x] Topline summary available for review

**Comment by sporeboy** [comment]
Initial draft of COE usability topline summary is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-topline-summary.md
