### ISSUE TITLE
CRM Updates to VEO Salesforce Instance

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#26128]
## Issue Description
_In an effort to improve efficiency for our support handling process in Salesforce, we are working with VEO to update our (shared) instance. This story is primarily a placeholder to log information provided to and received from VEO through other channels._

---
## Tasks
- [ ] _Tasks and plan of action are being maintained in [this](https://docs.google.com/document/d/19LiTyYHMr33L1Qxyxqr7BqIVXpkLWfOxiwJ_Ac9w1_Y/edit?ts=60c10f3c) separate document. This plan (current as of 6/15/21) is pasted at the bottom of this description.

## Acceptance Criteria
- [ ] _Initial list provided to VEO_
- [ ] _Additional information about likelihood, blockers, dependencies is documented_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Living Plan (current as of 6/15/21)**
Inline editing for mass updates (List View Edit)
Implementing automated email templates for cases escalated to Tier 2 queue
Can these email templates be sent out from the VA.gov Technical Support email address?
Updating case fields: Process and timeline for these types of requests
Case outcome field - ability to track cases that were incorrectly escalated to tier 2
Case category and Case type
Consistent updating based on issues and products that are being launched (i.e. Mobile App)
Reporting 
Automated Reporting
Scheduled reports
Bigquery/domo connection
Contact Channels 
Ability to email directly from Salesforce
Adding templates as part of KM
Tier 2 Case Management
Connection with github?
Provide teams access to salesforce?
Bulk editing of cases (i.e. closing of cases)

Notes:  For the case outcome option:

A majority of cases that are routed to tier 2 can/should be resolved by a tier 1 agent by utilizing the KM articles as well as templates that have been provided.  Currently there are no means for the Technical Support team to indicate cases that should not have been routed to us.  

Misrouting examples:
The agent provided the needed information, but routed to tier 2 anyhow.
There is no email contact information in the ticket: Caller details (email or preferred email) or in the case notes section. 
The case is not a tier 2 technical issue case.

To assist in tracking and reporting, we are requesting that an ‘Escalated to Tier 3’ option be added to the Case Outcome drop down field.  This would allow the Technical Support team to track and report on these cases; currently the process is manual and not efficient or effective.

Adding the Escalate to tier 3 option will allow our team to focus on the cases that are in our wheelhouse that can be reviewed by the appropriate team and ultimately resolved. 

Going about the change this way will hopefully lessen the opportunities for agent misrouting, since they will still only be utilizing their regular options; however, training will still be necessary.  Reporting will be generated and run regularly by our team in order to stay current with our actual case load. 

Cases that remain in the Escalated to Tier 2 bucket will ultimately be resolved by a VEO agent if/when the caller reaches out to VEO again.

Having this option would also allow a training opportunity for VEO by creating reporting and tracking individuals that consistently route non tier 2 cases to tier 2 for resolution.

**Comment by edpearson20** [comment]
Thanks, Jason!

~ Erv/in
