### ISSUE TITLE
[Analytics] Review Production Q&A documents to find common issues and categorize for use in a Knowledge base [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26149]
## Issue Description
As a editor I need a knowledge base or FAQ, so I can review issues and/or find answers to my problems there first before contacting the help desk.

## Goal
Find common issues and then categorize them so common answers can be determined and provided.
---
## Tasks

- [x] Pull data from Production Q&A meetings and categorize and relate to common solution area (e.g., Product, front end, training)
- [x] Provide data in an artifact that can be provided to Product owner and CMS

## Acceptance Criteria
- [x]  Production Q&A are used as basis of data mining
- [x] Artifact is created that outlines categories and examples of issues, provides support type, and what the solution provided was for that issue.
