### ISSUE TITLE
[Content-Load-Review] Load content and Internal Review, Proofread and correct plain language and common sense content on all pages for VA Wallawalla health care - VISN-20.

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26148]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[VISN-20 Content folders](https://drive.google.com/drive/folders/15sj7KZlKWTJQwY_mzb_Tnb7YVXUAUr9f)

## Tasks
* Load prepared content for the following pages:
- [x] About
- [x] Work With Us
- [x] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: 
- [x] 687	Jonathan M. Wainwright Memorial VA Medical Center
- [x] 687GA	Richland VA Clinic
- [x] 687GB	Lewiston VA Clinic
- [x] 687GC	La Grande VA Clinic
- [x] 687HA	Yakima VA Clinic
- [x] 687QB	Morrow County VA Clinic
- [ ] 687QC	Wallowa County VA Clinic

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [x]  Location Listing Page 
- [x]  History    
- [x]  Internship and Fellowship 
- [x]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [ ]  System Page 
- [x]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [x]  Mission-Vision 
- [x]  Leadership Listing Page 
- [x]  Policies Page (Should be new hardened format)
- [x]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [x]  Performance Page
- [x]  Make an Appointment
- [x]  Register-for-Care
- [x]  Billing
- [ ]  Contact-us		
- [x]  Dav-vans
- [x]  Medical-Records
- [ ]  Operational Status
- [x]  Pharmacy
- [x]  Caregiver
- [x]  Homeless
- [x]  LGBT
- [x]  Mental
- [x]  Minority
- [x]  Patient
- [x]  Returning Service member
- [x]  Suicide prevent
- [x]  Women-vet
- [x]  Campus Map
- [x]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.

**Comment by psanders86** [comment]
There are three pending issues.

1. The system page has "VA Wallawalla in display type (H1) and I can't change it.
2. The operating status page contains a reference to VA Wallawalla in display type that I cannot edit.
3. The 23 facility health services have a page title of VA Wallawalla that I cannot edit. I successfully edited the subheads "Care we provide a VA Walla Walla Health Care" in the VAMC system description of service, but I don't know if we need to change these facility health service titles.

**Comment by psanders86** [comment]
Per @SgardnerPMP, these are being transferred to another issue due to permissions.
