### ISSUE TITLE
**DECISION TOOLS SPRINT 50 PRIORITIES**

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26155]
<hr>

## 📅 Team Project Calendar
[Link to calendar](https://calendar.google.com/calendar/u/0?cid=Y19nOXJmdXMxNHZudHV1bHF0bjFoOXA0Y2Znb0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) - **Shared - you can add/edit as needed**

## 🏖️ Sprint 50 Vacation/PTO Schedules
- John PTO Week of June 21
- Marci PTO Week of June 21
- Juneteeth holiday June 18 (unplanned)
- Zach Jury Duty 6/29

## :fire: Sprint 50 Priorities
**EPIC FOR FIND A VA FORM CHANGES : #21639**
- [x] (Team) - Midpoint review for Find a VA Form Changes (Search improvements, UI consistency, Related Forms links)  6/17 at 1:30
- [x] (Cassandra) **Find a VA Form** - Flesh out PDF instructions #26050 
- [x] (Cassandra) **Discharge Upgrade Wizard** - Design intent to change PDF link to Portal link #23591 (will require coordinating with Content on the [related content request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25655). 
- [ ] (Cassandra - Stretch) **Search UI Consistency** - Document design pattern #24597

- [ ] (Zach) **Yellow Ribbon** - 508 Issues 
   - [x] #25599 Front end should not expect images
   - [x] #12060 Screenreader SHOULD announce the accurate number of items
   - [x] #12108 Search form SHOULD use semantic markup
   - [x] #12547 The same terms SHOULD be used for non-sighted and sighted users
   - [ ] #11969 Relevant content provided on desktop MUST also be available on mobile 
- [x] (Zach) **Design System** - switch out alerts to use web components
   - [x] #26216
   - [x]  #26217
- [x] #26664

###  🗨️  Discussion Topics/Grooming 
- [x] Any update from John Santos or Margarete re: Discharge Upgrade Wizard?
- [ ] Topic
- [ ] Topic

**Comment by MarciMcGuireGCIO** [comment]
2021-06-17

- Midpoint review was this afternoon
- Zach
   - Midpoint review
   - 1-1 with VSP
   - Working on alert components
   - Merged font fix on Find a VA Form
- Cassandra
    - Mocked up the PDF download link
    - Ready for me to loop in Ryan, Shawna, Josh

**Comment by MarciMcGuireGCIO** [comment]
**2021-06-28** 

- Discharge Upgrade Wizard Air Force link change - Cassandra has a small adjustment from Beth to make, then we can schedule design intent review
- Find a VA Form PDF Download - no second design intent is needed per Shira and Shawna.  Marci will look at the R&S PDF copy ticket to see what else is left before Zach builds out for Cindy to test with users later this month.
- Working on two 508 issues (On 12108 - Zach hit a wall - Platform is migrating new components to a new technology that is not playing nice with React - there is no checkbox component for him to use yet, so he will create one).  
- Zach is also also working on 12547, which is another 
-
