### ISSUE TITLE
Determine number of tables on rates pages that will be migrated to R&S templates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26175]
## Issue Description
Sitewide Content will be migrating all the rates pages we currently have to R&S by the end of the year. Because there are so many tables on these rates pages, which will be very time-consuming to set up manually, the CMS team will move them for us as content blocks. We need to provide them with a list of the number of tables that will be moved in order for them to do so.

## Tasks
- [x] Create list of number of tables to be moved (Randi)
- [x] Check number is accurate (Selina/Laura)
- [x] Send list to CMS team (Randi)

## Acceptance Criteria
- [x] Full list of tables given to CMS team

**Comment by RLHecht** [comment]
@lunascoop @lwalsh617 I created a doc of the number of tables on each of our rates pages. Kevin asked for a list so that he could see how many they would need to migrate for us. Could one of you please check my math and make sure I'm not missing any rates pages? Thanks!

[https://app.zenhub.com/files/133843125/619bfd44-ff7d-4dbb-9f24-94e02e8a6baa/download](https://app.zenhub.com/files/133843125/619bfd44-ff7d-4dbb-9f24-94e02e8a6baa/download)

**Comment by lunascoop** [comment]
@RLHecht I've reviewed and added the burial allowance rates. The rest of the math is correct.
[619bfd44-ff7d-4dbb-9f24-94e02e8a6baa.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6664700/619bfd44-ff7d-4dbb-9f24-94e02e8a6baa.docx)

**Comment by RLHecht** [comment]
Work completed on this ticket. Closing.
