### ISSUE TITLE
Iterate on View Payments: Remove Sidebar etc

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26179]
## Background
Given feedback and data around View Payments, we would like to adjust the feature in prod.

[Newest Mockups](https://www.sketch.com/s/2cbfbba2-b8c6-490a-8f25-240877a7786b/a/3Ol0lyo)

## Considerations
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22065

## Tasks
- [x] Sync the feature in production with what is in the latest mockups/changelog

## Acceptance Criteria
- [x] The feature has been synced with latest mockups
- [x] A PR has been requested for merging
