### ISSUE TITLE
Document Profile Payload Contents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26176]
## Background
One of the functions of the COE is that they require information about the Veteran including things like military and other prior experiences that are codified in various lower environments.  We need to fully understand the fields that are being requested, how those map to the different environments and what we have access to.

## Consideration
Design's previous work on this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25718

## Tasks
- [ ] Obtain a sample payload for an authenticated Veteran 
- [ ] Share with Jim and Jason; map or note the originating data source (user profile)
- [ ] Or link to the repo that shows what is coming back

## Acceptance Criteria
- [ ] All requirements have been defined 
- [ ] All attributes have been mapped to the originating data sources

**Comment by jason-gcio** [comment]
is this BE or FE technically?

**Comment by micahchiang** [comment]
Would these calls be sufficient for this ticket? 
- https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/user/getUser
- https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/profile/getServiceHistory

**Comment by jason-gcio** [comment]
hold for now, may not be needed for immediate testing

**Comment by jason-gcio** [comment]
consider closing
