### ISSUE TITLE
Q4 Dashboards-Testing Tools: Improved QA Dashboards, Improved Collab Cycle Dashboard

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#26184]
## Problem Statement 
VFS Teams, VSP Staff and OCTO-DE leadership don’t have a way to easily understand the state of quality on individual products, or across the platform.

How might we develop a solution that allows stakeholders to see QA-related metrics from the product(s) that are relevant to them according to their role?

## Hypothesis or Bet
By providing a dashboard that enables stakeholders to view metrics for how products are doing in following QA processes and ensuring quality on their products, stakeholders will have better insight into the state of quality on the platform and will be able to make better decisions to address any gaps on products or the platform.

NOTE: This will be an extended effort that is likely ongoing into the future, and will contain specific goals for each quarter and what should be accomplished, iterating on the current offerings.

## We will know we're done when... ("Definition of Done")
- [x] We have identified metrics in the existing test methodologies/tools
   - [x] Improved QA Dashboard(s)
   - [x] Improved Collaboration Cycle Dashboard
   - [x] Synthetic Monitoring Dashboard (DEPRIORITIZED)
- [ ] <s> (Stretch) We have identified metrics in the upcoming test methodologies/tools as they are stood-up
   - [ ] ``Contract Testing``
   - [ ] ``Test User Dashboard``
   - [ ] ``Visual Regression Testing`` </s> 
- [x] We understand what it takes to obtain those metrics and they are identified as feasible, or the plan has been updated accordingly to reflect any limitations
- [ ] We have an MVP of the dashboard ready for launch
- [ ] We have any necessary documentation completed and available for use

## Projected Launch Date
Q4 2021

### ... tested?
- [ ] Internal tests have been conducted and defects have been logged/resolved as needed.
   - [ ] Verify integrity of data vs actuals
   - [ ] Verify that visuals are as effective as possible in conveying data
### ... documented?
- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located on the Platform website
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it

### ... measurable
- [ ] Each area has specific KPIs and supporting data identified and tracked in BigQuery

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing
* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement
* **Success metrics**: 
  - [ ] Dashboard MVPs are published to DOMO
  - [ ] Dashboard MVPs are in use by stakeholders
* **Release plan**: Not available

**Comment by pjhill** [comment]
OBE
