### ISSUE TITLE
Implement feedback from COE status review

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#26188]
### Background
Each week there is a standing COE status call.

### Tasks
- [x] Attend COE status call
- [x] Document feedback and next steps
- [x] Implement feedback

### Acceptance criteria
- [x] Current prototype and diagrams reflect latest COE feedback

**Comment by sporeboy** [comment]
Design feedback will be implemented after research readout. In general terms:
- Clarify auto COE screen process
- Increase emphasis on documents list
- Move sign-in widget to below subway map
- Address CTA action-link labels
