### ISSUE TITLE
Iterate on Rated Disabilities: Remove Sidebar

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26181]
## Background
Given feedback and data around Rated Disabilities, we would like to adjust the feature in prod.

[Latest mockups](https://www.sketch.com/s/9a70f4c7-68f8-4998-bfee-2fdbb709cfb2/a/eKb9d70)

## Considerations
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22064

## Tasks
- [x] Sync the feature in production with what is in the latest mockups/changelog

## Acceptance Criteria
- [x] The feature has been synced with latest mockups
- [x] A PR has been requested for merging

**Comment by cohnjesse** [comment]
Did not have enough time to work on this because login broke on local machines and I had to spend this time setting up mocking.
