### ISSUE TITLE
Add a Changelog to Mockups

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26182]
## Background
In addition to the meaningful, crisp and hi-fi mockups produced by the Design Team, it would be very helpful for frontend to have a checklist of changes included so that they can be sure not to have missed anything.

## Considerations
- View Payments new mockup: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22065
- Rated Disabilities new mockup: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22064

## Tasks
- [ ] Add a changelog in the comments of each ticket above to capture latest changes made.
- [ ] Add a copy of those changes in the `/research-design/` folder for this feature

## Acceptance Criteria
- [ ] A changelog has been shared in the corresponding tickets.
- [ ] A copy of those changes are saved in the `/research-design/` folder for this feature

**Comment by candy-gcio** [comment]
tool-design-update-punch-list.md

**Comment by jason-gcio** [comment]
RD: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/research-design/tool-design-update-punch-list.md

**Comment by candy-gcio** [comment]
VP - There are a couple of open questions on the ds components used. Draft change log is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/research-design/tool-design-update-punch-list.md
