### ISSUE TITLE
Meet with LH: Rep API

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26197]
## Background
One of the questions that arose is the idea that some representatives might only be able to receive electronic submissions and we need to determine how that is working currently.

## Considerations
http://pint.ebenefits.va.gov/domain1/mock-csp/index.jsp (used in VA network)

## Tasks
- [x] Discuss internally how this is supposed to work in the current EBN environment
- [x] Discuss with LH if they have any different info

## Acceptance Criteria
- [x] An outcome has been determined about whether an electronic requirement is needed
- [ ] A PR has been requested for merging, if needed
