### ISSUE TITLE
Conduct COE usability testing

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#26191]
### Background
COE usability testing has been scheduled. We need to conduct the sessions themselves, as well as daily debriefings. Each session's finding will be captured in draft notes and a usability matrix.

Resources:
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-convo-guide.md)

### Tasks
- [x] Attend and conduct usability sessions
- [x] Capture session findings in usability matrix
- [x] Conduct daily debriefs to discuss initial findings

### Acceptance criteria
- [x] Usability session completed
- [x] Usability matrix updated
- [x] Session notes added to Github

**Comment by jason-gcio** [comment]
@sporeboy - link to RP+CG?

**Comment by sporeboy** [comment]
Sessions began Monday, June 14; Five are scheduled this sprint.

**Comment by jason-gcio** [comment]
Matrix + notes are linked in `/research-design/` folder?
