### ISSUE TITLE
Operations team roadmap

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#262]
## High Level User Story
As a VSP stakeholder, I need to understand the operations team's priorities for planning purposes.

## Goals
Roadmap created with high-level operations tasks, including VFS team support, infrastructure improvements, tech debt paydown, and a prioritization between them.

## Objectives
* Enable agile VFS Team delivery of performant applications

## Definition of Done
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Epic`**
