### ISSUE TITLE
Create forward proxies for each Medical Copay API environment

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#26209]
## Issue Description
We need to be able to connect to the VBS API which is on another network. In order to connect to their network we need to set up SSL and a reverse proxy.

We need to communicate with the liberty team to get their creds, routes, and other details so we can add this information to our DevOps config.

---
## Tasks
- [ ] Get credentials, routes, etc. from liberty team
- [ ] Add config with creds to DevOps repo

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LinnJS** [comment]
We will tackle this when VBS team communicates production env configuration details.

**Comment by LinnJS** [comment]
Moved to blocked since VBS has still not gotten us creds for these endpoints.

**Comment by denisecoveyduc** [comment]
This issue will roll over into Sprint 61 as a result of the caregiver team assistance.

**Comment by denisecoveyduc** [comment]
Awaiting on external stakeholders for final credentials will put in ready until received

**Comment by ScottyRJames** [comment]
Liberty has restricted traffic to the VA Network so we are set to add the forward proxy and setup TLS

SSL certs will not be needed as this is pure `tls-dns` and not `client-tls-dns`/mTLS

**Comment by ScottyRJames** [comment]
Forward proxies have been created for dev, sandbox, and staging. Reserved same port for production when the domain is up. 

Settings have been updated for dev and confirmed working. Awaiting API key to update  configuration in staging
