### ISSUE TITLE
Map design prototypes to data provided by Medical Copay (VBS) API

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#26208]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Review the prototypes for the upcoming Medical Copay UI on va.gov. Ensure that we can map the displayed data to properties on the data dictionary provided by the Medical Copay (LibertyIT) Team.

- Swagger docs/schema: https://yf7yvyucfj.execute-api.us-gov-west-1.amazonaws.com/Prod/swagger/index.html

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Create a list of attributes in the UI that do not map one-to-one to the data dictionary.
- [ ] How will we break up statement data from list to single item?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
Did not get to this ticket this sprint since I was working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/24402

**Comment by kevinmirc** [comment]
Design Reference: https://preview.uxpin.com/18073b171729031ac0af64822d31a7427b012d66#/pages/139873793/simulate/sitemap?mode=i

| UI Page and Component | UI Data Field | Data Source | Data Field |
|:-------|:--------------|:--------------|:-----------|
| Overview Page > Collections Warning Banner | Amount sent to collections | | |
| Overview Page > Collections Warning Banner | Number of days past due | | |
| Overview Page > Collections Warning Banner | "Is in collections" flag | | |
| Overview Page > Copay List Item | Outstanding balance | | |
| Overview Page > Copay List Item | Name of facility balance is due | | |
| Overview Page > Copay List Item | Date payment is due  | | |
| Overview Page > Copay List Item | Is payment due on or before provided date  | | |
| Detail Page > Page Title | Name of facility balance is due | | |
| Detail Page > Copay Summary | Date this information was last updated | | |
| Detail Page > Copay Summary | Balance due | | |
| Detail Page > Copay Summary | Payment Due Date | | |
| Detail Page > Copay Summary | Date you must request financial assistance by | | |
| Detail Page > Copay Summary | Link to make payment | | |
| Detail Page > Copay History Table > List Item | Type of Item (Late Fee, Inpatient care copay, Payment, Service) | | |
| Detail Page > Copay History Table > List Item | Amount of Item | | |
| Detail Page > Copay History Table > List Item | Date of occurrence | | |
| Detail Page > Copay History Table > List Item | Billing Number (reference number?) | | |
| Detail Page > Statement Download > List Item | Date | | |
| Detail Page > Statement Download > List Item | URL to download | | |

**Comment by kevinmirc** [comment]
@LindaLi123 @leahkeeler @rebeccawalsh @rileyorr @LinnJS @craigwheeler 

Risks with the data mapping to be aware of and seek confrimation:
- How will we know when a specific statement / bill was sent to collections. And how do we know the amout sent to collections and when it was sent.
- If we use the statement due date for "Number of days past due", there is a strong likelyhood that users will see statements past due when infact they made a payment. We need to consider that lag time of data reaching our systems (and caching). We should consider a different data source / property that explicitly makes the bill "past due".
- I'm assuming the VBS statement's `pS_STATEMENT_DATE ` is the date that payment is due by (end-of-day). The statement response from VBS also has a `pS_PROCESS_DATE` which may indicate when this statement was paid in full. Both of these assumtions need confirmation from an SME or the VBS team.
- Is the "Date you must request financial assistance by" equel to the date that the patment is due for the bill / statement?
- For the "type of (line) item" on a statement, we do receive a description in `details[i].pD_TRANS_DESC`, but I do not know what the possible values are for this and not entirely sure it will map to the design's labels one-to-one.
