### ISSUE TITLE
Create ruby client library for Medical Copay API

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#26207]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Create a library that will consume the Medical Copay API. The lib should have request and response models along with a service to make the API call.

---
## Tasks
- [ ] Add settings to settings.yml
- [ ] Create the Lib directory
- [ ] Create request and response models
- [ ] Add validation to requests (and responses?).
- [ ] Add the base Faraday service
- [ ] Add a method to call the endpoint for statements

## Acceptance Criteria
- [ ] A new library exists in lib that the main application can use to call the API.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
Did not get to this ticket this sprint since I was working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/24402

**Comment by kevinmirc** [comment]
Completed with the two PRs above.
