### ISSUE TITLE
Design API for fetching user's medical copay information

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#26211]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Desing the vets-website to vets-api data contract for fetching the medical copay (statement) data for the current user.

---
## Tasks
- [x] What are the endpoint(s)
- [x] How will we handle pagination
- [x] What data is returned
- [x] How is sorting and filtering handled

## Acceptance Criteria
- [ ] Create API documentation and data contract.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LinnJS** [comment]
Closing this out since we have the API working end to end.
