### ISSUE TITLE
[MCP] First iteration of wireflows

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#26225]
## Issue Description
_We've wrapped up Veteran research and ideation sessions surrounding different directions to take the medical copay experience. We've been advised to create a standalone tool, so we need to create wireflows and present them to stakeholders and SMEs for feedback._

---
## Tasks
- [x] _Create first iteration wireflows for the standalone medical copay tool_
- [x] _Present wireflow(s) to stakeholders and SMEs for feedback_

## Acceptance Criteria
- [x] _Wireflows and stakeholder/SME feedback have been uploaded to GH and linked in this ticket_

**Comment by rileyorr** [comment]
We presented the first iteration wireflow for stakeholder and SME feedback on 6/11 

The wireflow and feedback can be found in [the wireflow change log on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/design/wireflows-change-log.md).
