### ISSUE TITLE
[PM] My VA: Hold launch go/no-go

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26224]
## Background

We are getting ready to launch My VA 2.0 on VA.gov. Before we can begin our phased launch to 25% of users, we need to hold a go/no-go to make sure the team is ready.

**Go/no-go meeting is tentatively scheduled for 6/28/21**

For reference:

- [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Release-Plan.md)
- [Go/No-go worksheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/my-VA-launch-go-no-go.md)

## Tasks

- [x] Hold go/no-go
- [x] Fill out [go/no-go document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/my-VA-launch-go-no-go.md)
- [x] Follow-up on any issues that come up in the meeting, if necessary

## Acceptance criteria

- [x] We have a clear decision on whether we are ready to launch to 25% of users or not on **6/30/21**
