### ISSUE TITLE
DO JUNE 23: Remove disallow statement from Robot.txt file, to allow crawlers and access to VAMC URL

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26242]
## Story
Each time the VAMC team brings up a new System into Dual-State, a facilities engineer adds a disallow line (Disallow: /(name)-health-care/) under # existing disallow on va.gov to the robots.txt file and pushes a PR to engineering to prevent crawlers from accessing the new site in dual state. Platform needs a PR to add that one line to the robots.txt file. 

As a VAMC site moves from dual state to live, we need crawlers and external browsers to see the new VAMC URL.

src/site/assets/robots.txt:97
Disallow: /performance-dashboard
(In the useragent * section which covers all bots other than usasearch and synapse)As a VAMC site moves from dual state to live, we need crawlers and external browsers to see the new VAMC URL.

## Goal
Remove disallow statements from the following sites on June 23rd to allow time for browsers and crawlers to pick up new URL information and prepare for cut over.

## TASK
Please remove disallow statements for the following VAMC systems in Robot.txt file.
src/site/assets/robots.txt:97
`Disallow: /performance-dashboard`
- [ ]  wilmington-health-care
- [ ] altoona-health-care
- [ ] wilkes-barre-health-care
- [ ] ~~butler-health-care~~ (removed due to pending name change)

## Acceptance criteria
- [ ]  All systems have been removed from disallow listing.
