### ISSUE TITLE
Remove disallow statement from Robot.txt file, to allow crawlers and access to VAMC URL

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26241]
## Story
As a web maintainer and editor, I need crawlers and external browsers to see the new VAMC URL.

## Goal
Remove disallow statements from the following sits on June 23rd to allow time for browsers and crawlers to pick up new URL information and prepare for cut over.

## TASK
Please remove disallow statements for the following VAMC systems in Robot.txt file.
- [ ]  wilmington-health-care
- [ ] altoona-health-care
- [ ] wilkes-barre-health-care
- [ ] butler-health-care

## Acceptance criteria
- [ ]  All systems have been removed from disallow listing.

**Comment by mmiddaugh** [comment]
Closing as duplicate to #26242
