### ISSUE TITLE
526: Move disability wizard

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#26264]
## Description

Per the recent [IA review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/wizard-disability.md), the disability wizard is to be moved from the introduction page to a new separate `/start` page.

> 1. Please review the user flows and URL for the actual wizard move - these are different than what is implemented currently in staging. These flows are based off the work that was done last fall, and a recent accessibility change to move the wizard onto its own page (/start) rather than as a display state on the /introduction page. Please post any questions to this ticket so we can finalize that aspect of the work.
> 1. You will need to coordinate content updates on the static pages and changes to entry points, which will be done by the sitewide content team. Please open an intake ticket with them for this work. You can reference this IA issue, please indicate that it is still in progress for now. Once they have a chance to review the work, then I will connect with them to finalize.

<details><summary>Wizard flow diagram</summary>

![](https://camo.githubusercontent.com/ec3fe677964beaadebf409e56342962d039b2d38cc0fab41e632c8a66c813303/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3539636136613733623032323264356465343739326631642f35633030376433332d656161632d346662612d613038382d323261303965643963343665)</details>

Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/wizard-disability.md
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/24263#issuecomment-860786338

## Tasks

- [ ] Move disability wizard
- [ ] Ensure flow matches IA diagram
- [ ] Update unit tests
- [ ] Update Cypress e2e tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
- [ ] Maintain feature flag
