### ISSUE TITLE
[MCP] Plan and coordinate meetings with SMEs 

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#26262]
### Description
We know of a few knowledge gaps that we need to investigate further:
- [ ] **Code mapping:** what are the backend statuses that medical bills can be in? (Pause for FSR, suspensions, etc.)
- [x] Treasury referrals
  - [x] Will we know if something is sent to TOP vs CS?
  - [ ] What happens in the backend when bills are sent to Treasury? 
- [ ] Medical copay line items / charge types / descriptions
- [ ] Clarification on data points (to be provided by Kevin)

### Tasks
- [x] Create convo guides for SMEs
- [x] Schedule SMEs:
  - [x] David Adcock
  - [ ] (SME for data points?)

**Comment by rileyorr** [comment]
[I've added the notes from David Adcock's interview to GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/sme-interviews-jun-2021/06252021Adcock.md)

We've reached out to the SMEs David identified during the interview; moving this ticket over to validate!
