### ISSUE TITLE
Leverage Media Queries for the Right Rail

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26287]
##  Description
Problem: The right rail is hidden at the bottom of the page for desktop users with a browser width below 1200px. 
Solution: Update the media query for the right rail to stay to the right of the search results until the browser is at 767 or below.

Example: Left navigation feature on [benefits pages](https://www.va.gov/health-care/about-va-health-benefits/) features the following media query:
```
@media screen and (min-width: 768px)
.usa-grid .usa-width-one-fourth {
    margin-right: 2.35765%;
    width: 23.23176%;
}
```

## Tasks
- [x] Update media query for right rail on search results page

## Acceptance Criteria
- [x] Right rail is shown on the right of the screen on all browser widths 768 and up
- [x] Right rail is shown at the bottom of the screen on all browser widths 767 and below
