### ISSUE TITLE
Define 'pie in the sky' search

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26288]
##  Description
As a product team we need a description of what our 'ideal' search experience looks like. What characteristics does it have, what capabilities does it offer to the user etc. 

## Tasks
- [ ] Team workshop to brainstorm on ideal search experience 
- [ ] Define a short write up to describe  ideal search experience
- [ ] Add description to [research folder ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search/research)for onsite search 

## Acceptance Criteria
- [ ] Description has been added to GH and can be leveraged during future discussions

**Comment by denisecoveyduc** [comment]
Given the flux in research and team staffing we have decided to move this discussion to the backlog until we have additional clarity on next steps for search.
