### ISSUE TITLE
Analytics Services - Update content & training

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#26297]
## Problem Statement 
We have a growing amount of VFS teams who need support, and Platform Analytics & Insights spends time answering both basic and complex questions.

How might we improve VFS teams' abilities to find analytics answers on their own so that we are less of an impediment to using data and VFS teams are able to self-serve descriptive data use?

## Hypothesis or Bet
If we add, update, and improve our documentation and training, then we expect:
- Platform Analytics & Insights to spend less time answering questions that have documented answers
- VFS teams to be able to understand how to read available descriptive analytics on their own

## We will know we're done when... ("Definition of Done")
- [See Platform Objective 1 OKRs](https://docs.google.com/spreadsheets/d/1qVAJKXVYys_YlRifglZGVbYQc09mKsLAsI1RTqPbHa8/edit#gid=715168434) for outcomes
- [ ] VFS-facing Analytics documents on Confluence are up to date
- [ ] Any ideated trainings have been tested

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*
- Any design or research support - we will cover internally on the team or look for support from Service Design & the Platform Design Lead.

## Projected Launch Date
We expect to begin this initiative Sprint 57 or Sprint 58 (end of July or early August). Projected Launch date is tentatively end of October 2021.

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by joanneesteban** [comment]
We expect to work in sprints to test smaller bets for documentation & training iterations to allow use to test our ideas more quickly and lean into more successful bets faster. Some of these can be found in previous Initiatives on old "Future" parts of our roadmap, which include:

- [ ] [Update our KPI Framework](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17338)
- [ ] [Adjusting our documentation for usability](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/7585)
- [ ] [Iterating on Analytics reporting processes](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3074)
- [ ] [Expand our Analytics Workshops](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13703)
- [ ] [Expanding our KPI Trainings](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3086)

---

The Platform Analytics & Insights team has also ideated on [solutions for easier insights and access](https://docs.google.com/spreadsheets/d/1a7x1QPZBqWnXgJ5OmNDfzMoBRNA_pz_aqoXrEshUAVo/edit#gid=871256424), which include:
- Iterating on our Data Dictionaries
- Lunch & Learns
- An Analytics Slackbot

**Comment by joanneesteban** [comment]
### Example Sprint
An example sprint or two sprints for this initiative:

1. Prioritized User Story/Sprint Goal: As a VFS product manager, I need to understand how I can work with Platform Analytics & Insights implement analytics tracking on my VA.gov application.

2. Team determines a bet for addressing the user story and the tasks that will be involved in delivering this bet. 
- Bet Sprint 1: If we determine the best VFS PM journey for GTM implementation & which documents need updates, then we can 
- Bet Sprint 2: If we update & add Google Tag Manager documentation to Confluence, then VFS PMs can request tracking with less time spent on business requirement gathering.

Tasks - Sprint 1
- [ ] Determine ideal VFS PM journey for GTM implementation
  - [ ] Determine what documentation touchpoints they need
- [ ] Update customer support process & guidelines & add to Confluence
- [ ] Audit GTM/GA documentation
  - [ ] Determine which documents need to be updated, migrated
  - [ ] Determine what edits are necessary, if any
- [ ] Add Github tracking to Domo to track how long it takes us to do GTM implementation

Tasks - Sprint 2
- [ ] Update any necessary GTM/GA documentation
   - [ ] Update Data Dictionaries
- [ ] Update Confluence documents
- [ ] Update any GTM operational documentation where necessary

**Comment by johnny-jesensky-adhoc** [comment]
Closing this epic, will look to review remaining open tasks as part of our icebox/backlog review.
