### ISSUE TITLE
Staging Review - Decision Tools - Feature Name - Find a VA Form - Add Relevance, Popularity, Related Forms link

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26298]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support. 
- [x] Platform: Schedule meeting with Platform reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] Platform: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to Platform feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md)
- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository
   - Search results:  https://www.va.gov/find-forms/?q=10-10ez
   - Form detail page: https://staging.va.gov/find-forms/about-form-10-10ez/
-  Staging test-user information (if applicable):  N/A
-  Link to content brief (if applicable):  N/A
-  Link to or attach your project's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link) 
   - Search results:  https://www.va.gov/find-forms/?q=10-10ez
   - Form detail page: https://staging.va.gov/find-forms/about-form-10-10ez/
   
-  Link to the Github ticket that shows the work for creating and/or updating any relevant static content pages and entry points for this project:  N/A

- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/improve-search/release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)

- Link to your product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/136&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1308)/test [plan ](https://dsvavsp.testrail.io/index.php?/plans/view/1923) in TestRail with test execution logs.
  - Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/250) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/252) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail Platform accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/136&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1307).

- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): Marci McGuire
- OCTO-DE Product lead (recommended): John Hashimoto
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): name(s)
   - Zachary Morel
   - Cassandra Allen
   - Mark Viterna (Lighthouse - team Matsumoto)
   - Nichole Harris (Lighthouse - team Matsumoto)
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s)
   - Trevor Pierce
   - Josh Kim
   - Angela Fowler
   - Tze-chiu Lei
   - Mikki Northius
   - Peggy Gannon

## Scheduling
What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **Friday, July 2 at 2:00 PM**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
This has been scheduled for Friday, July 2 at 2:00 PM ET

**Comment by shiragoodman** [comment]
hey @MarciMcGuireGCIO  - just wanted to let you know that we will be piloting a new process for writing and communicating issue tickets and your Staging Review gets to be a part of it :) The feedback tickets you receive for this Staging Review will be structured a bit differently than they have been in the past, and the meeting on Friday will also be somewhat different than you're used to. We will be sending out a survey post-meeting to get your feedback. If you have any questions, please let me know. Thanks!

cc @allison0034 @mnorthuis @peggygannon @noahgelman @1Copenut @joshkimux @AngelaFowler82

**Comment by tlei123** [comment]
@pjhill @ddzz , all QA test-runs completed, and QA-artifact links updated above in main description.  100% Passed; no defects logged.

cc @MarciMcGuireGCIO @shiragoodman

**Comment by MarciMcGuireGCIO** [comment]
Thank you @tlei123 !  I was out of town; sorry for the late response.

**Comment by 1Copenut** [comment]
Platform accessibility concurs with the VFS specialist's feedback. 👍

**Comment by pjhill** [comment]
Platform QA team has no feedback for the team -- thanks for your work in TestRail!

**Comment by MarciMcGuireGCIO** [comment]
Notes from Staging review:

This is the first review following the new Staging review process.  There will also be a survey.

**Comment by shiragoodman** [comment]
thank you so much for capturing those notes @MarciMcGuireGCIO ! this is fantastic feedback, and we will definitely use this as a learning experience in preparation for our launch of the new process. 

I will post the survey link here next week after you've had time to review the tickets in more detail. Thanks again for helping us with our pilot!

**Comment by shiragoodman** [comment]
hi @MarciMcGuireGCIO , @johnhashva , @zacharymorel and @callen2563,

As stated on the call, we are asking you to please complete a survey for the pilot of our new standards and Staging Review process. The survey link can be found here: https://adhoc.optimalworkshop.com/questions/xv854bro

We will be reviewing all feedback received from VFS teams, and will be making enhancements to our process prior to launch.

Thank you again!

@MarciMcGuireGCIO could you please forward the survey link to anyone I may have missed?

**Comment by zacharymorel** [comment]
@shiragoodman can you add this issue to the Epic here. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26353

**Comment by MarciMcGuireGCIO** [comment]
This change went live on 7/7/2021.

**Comment by MarciMcGuireGCIO** [comment]
@pjhill @noahgelman for visibility
