### ISSUE TITLE
Remove SSN and VA File Number from CH31 (FE)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26290]
```diff
- Do not merge before BE's ticket
```
## Background
The CH31 stakeholders have brought up the fact that sometimes Veterans enter in the wrong VA file number/SSN and so we should strive to only pass through what is included in the proofed profile object.

## Tasks
- [ ] Hide or remove the SSN and VA file number fields
- Update the following repos:
  - [x] `vets-website`
  - [x] `vets-json-schema`
  - [x] `vets-api`

## Acceptance Criteria
- [ ] Fields are removed
- [ ] PRs for the repos listed above are requested
