### ISSUE TITLE
NOD: Filter out contestable issues with missing titles

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#26294]
## Description

During Notice of Disagreement UATs, we encountered issues that were missing a title. After discussing this with LightHouse, they felt confident that issues without titles could be filtered out and not displayed to the Veteran.

Related: https://dsva.slack.com/archives/CSKKUL36K/p1623956682119300?thread_ts=1623863323.111700&cid=CSKKUL36K

## Tasks

- [ ] Filter out eligible contestable issues that are missing a title
- [ ] Update unit tests

## Definition of done

-  [ ] All tasks completed
-  [ ] All tests passing
