### ISSUE TITLE
Product Success Tool - Launch VA.gov Education Proof of Concept

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#263]
## High Level User Story
As a Product Owner, I need to easily understand how the tools I own are performing so I can make data informed product decisions.

## Hypothesis
**If** we create an analytics dashboard for product teams, **then**  we expect product teams to start to use data regularly as a part of their workflows.

## Assumptions
- VA development teams are willing to use data on a consistent basis to drive decision making
- We will be able to validate the data we collect on the VFS platform for accuracy
- Historical and offline data is available for our team to aggregate and leverage
- We will be able to identify and connect with stakeholders for other sources of VA data
- We will be able to get buy-in from other VA offices to report accurate data on a consistent cadence
- Product “decision makers” include product owners and product managers, who lead overarching product decisions

## Goals
Create analytics dashboards with updated available user-facing product metrics that product owners can use to improve their tools for veterans. 

## Details & Notes
**Problem Statement**: Holistic veteran facing services data is difficult to access and interpret because the VA’s data is scattered across multiple analytics systems, is not captured at all, or is too complex to be read accurately or consistently. This limited holistic data makes it difficult to measure VA.gov digital services, limiting Product Teams’ ability to make data informed decisions about how to prioritize work, design the appropriate experiences, and measure their success.

### Links
[User & Discover Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/research/product-health-prototype)

## Product Outline
[Product Outline](https://docs.google.com/document/d/1GuuhRXT8-NjEHdFHysNg1VA1o89Qr0_Mkrg46Q8kBeI/edit#)
[Product Brief](https://docs.google.com/presentation/d/1sI32UbQRqpKqOhBT8lkUuOHgfD4UUkV2cd5Pzw1fP9w/edit#slide=id.g5ce1b6f7f4_0_19)

### Areas for Discovery
VSP Analytics & Insights proposed the acquisition of the Business Intelligence Tool, Domo, and the data warehouse, BigQuery. We are looking to build out a Proof of Concept with these new tools for Education.

### VSP Objectives
`O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.`

### VSP Key Results
- Customers track KPIs for 100% of their products.
- Increase in VA.gov user satisfaction

## KPIs
- VFS user engagement
- Decisions made with historical data 

**How we will track the KPIs** User engagement will depend on the front end tooling we choose, Decisions will be on #1336 

## Definition of Done
- [ ] All valuable and available metrics with the Education applications are added to a front end solution (custom or BI Tool)
- [ ] The front end solution is connected to the data sources and everything is as automated as possible
- [ ] The Education proof of concept is shared with stakeholders and verified as either valuable or not valuable
