### ISSUE TITLE
Content and IA strategy for moving entire pages from tier 1 to tier 2 (R&S)

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#26300]
## Issue Description

This is part of our sitewide content big rock to optimize the benefit hubs. We'll be moving content in tier 1 that's related but peripheral to benefits/how to apply/eligibility into R&S. I'd like to collaborate with sitewide IA on the strategy around this work.

Initially, the work includes:
- rates pages (both current and past) 
https://www.va.gov/disability/compensation-rates/
https://www.va.gov/disability/survivor-dic-rates/
https://www.va.gov/disability/parent-dic-rates/

- evidence content from disability and pension static pages
https://www.va.gov/disability/how-to-file-claim/evidence-needed/
https://www.va.gov/pension/how-to-apply/fully-developed-claim/

There are tier 1 pages related to those listed above where we may move chunks of content as well--so part of this work takes into consideration existing pages that will stay in tier 1 but some content from those pages will move to tier 2.

---
## Tasks
- [ ] Determine crosslinking and navigation strategy between tiers 1 and 2.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@mpeterz Would like to set up time to talk through this!

**Comment by mpeterz** [comment]
@bethpotts - Let's include @mnorthuis. Hopefully she can attend.

**Comment by bethpottsVADEPO** [comment]
@mpeterz @mnorthuis @DanielleThierryUSDSVA Meg and I just talked about getting this conversation started in one of the weekly IA check-ins. Danielle and I will look for an invite when you can fit us on your agenda!

**Comment by mnorthuis** [comment]
Is this still relevant? Or should we close it out?

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis Let's close this. This is no longer relevant since it doesn't align with the content placement criteria.
