### ISSUE TITLE
MCP - Medical Copay details and action

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#26309]
https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140669280/simulate/no-panels?mode=i

## High Level User Story/ies
As a veteran who owes medical copay bills with the VA, I want to see the total balance of my debt, bill break down by facility and services,  so I know exactly where these debt come from and why i have them i can decide what to do next.

## Hypothesis or Bet
**If** _We allow veterans to review their medical copay details_  **then** _we expect less veterans to be confused of where their copay debt come from and have less questions_.

## OKR
_Veterans can see all their copay details listed by services and facilities, more debt action can be taken due to veterans has less confusion about their copay debt and spend less time trying to investigate_

## Definition of done
- [ ] Veterans can log into their account, view total copay balance and bill break down by facilities and services they had and can decide next steps

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
