### ISSUE TITLE
Research Visual Testing Tools for Inclusion in Production Monitoring

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26313]
# Description
Look into the list of visual testing tools previously assembled for the CI/CD visual regression testing implementation.

Given the fact that production monitoring scripts will need to run on a tight schedule (as often as every minute or up to every 5 minutes), there may be visual testing tools and workflow options more suited to the more frequent execution of the scripts.

## Differences in requirements from Visual Regression Testing in CI/CD
- [x] Frequency of execution is likely an order of magnitude greater
- [x] Workflow will be different (not going to be a CI/CD check) -- changes to visual aspects of monitored areas of the Platform should be communicated in advance in order to prevent triggering an alert in our production monitoring infrastructure.  We will need a way of swapping the reference visual in advance of a change releasing to production.
- [x] Integration with PagerDuty is key
- [x] Integration with AWS Canary infrastructure is important

## Task list
- [x] Reference the existing set of visual testing tools gathered during the [research](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/23888) into visual regression testing tools for our CI/CD pipeline.
- [x] Select the best fitting tool given the requirements
- [x] Estimate pricing for the tool given 1 minute, 2 minute, and 5 minute execution cadence

**Comment by holdenhinkle** [comment]
# PagerDuty
Incidents can be triggered via:
- [Web UI](https://support.pagerduty.com/docs/incidents#manually-trigger-an-incident)
- [API](https://support.pagerduty.com/docs/incidents#send-an-event-through-the-api)
- [Email](https://support.pagerduty.com/docs/incidents#send-an-event-to-an-email-integration)

PageDuty Events API - https://developer.pagerduty.com/docs/get-started/getting-started/#events-api

## [Events API v1](https://developer.pagerduty.com/docs/events-api-v1/overview/)
The PagerDuty Events API is used to add PagerDuty's advanced incident management functionality to any system that can make an HTTP API call. You can now add phone, SMS, email, and mobile push notifications to your monitoring tools, ticketing systems, and custom software.

## [Events API v2](https://developer.pagerduty.com/docs/events-api-v2/overview/)
The Events API v2 is a highly reliable, highly available asynchronous API that ingests machine events from monitoring tools and other systems like code repositories, observability platforms, automated workflow tools, and configuration management systems. Events sent to this API are ultimately routed to a PagerDuty service and processed.

# Percy
## PagerDuty Integration
Percy supports [webhooks](https://docs.percy.io/docs/webhooks).

List of events that trigger webhook notifications:
|Event                    |Description                                                                                                                                                                                    |
|-------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|`ping`                   |A webhook configuration has been created or updated for the current project.                                                                                                                   |
|`build_created`          |A new Percy build was created.                                                                                                                                                                 |
|`build_finished`         |A Percy build finished executing.                                                                                                                                                              |
|`build_approved`         |A Percy build was approved, either manually by a team member, or automatically due to an auto-approve branch rule or because no visual changes were detected.                                  |
|`build_changes_requested`|The state of a Percy build changed from “Unreviewed” to “Changes requested” because a team member requested changes on a snapshot within it.                                                   |
|`build_unreviewed`       |The state of a Percy build changed from “Changes requested” to “Unreviewed” when someone approved the snapshots with requested changes and there are unreviewed snapshots in the build.|

[Viewing recent webhook deliveries](https://docs.percy.io/docs/webhooks#viewing-recent-webhook-deliveries)

## [Slack Integration]( https://docs.percy.io/docs/slack-integration)

Supported notifications:
- Unreviewed and Changes requested: Get notified when builds finish processing with build statuses "Unreviewed" or "Changes requested". These notifications will also auto-update if status of the corresponding build changes.
- No changes: Get notified when builds finish with no visual changes.
- Auto-approved: Get notified when builds are auto-approved from your auto-approved branches.
- Approved: Get additional notifications—in addition to the Unreviewed notification update—when builds are approved.

**Comment by holdenhinkle** [comment]
Question in #vsp-operations - https://dsva.slack.com/archives/CJYRZK2HH/p1624912895334000

Holden Hinkle  4:41 PM
Hello everyone! I’m looking into implementing a visual testing tool for monitoring prod that would integrate with PagerDuty (create new incidents in PagerDuty).

Percy, a visual regression tool, can send notifications via webhooks if a build fails. We would need a service with an endpoint for that webhook where we could process the payload and create a new incident in PagerDuty through PagerDuty’s api.

Does such a service like this already exist for creating new incidents in PagerDuty?

**Comment by holdenhinkle** [comment]
How to create an incident in PagerDuty when a Percy build fails, by writing a Node.js AWS CloudWatch Canary script:
- Use AWS CloudWatch
- Create a Node.js Canary Script
- Script uses Percy's @percy/client
- Take snapshots, upload them to Percy, finalize snapshots
- Wait for the build to finish
- Process the build results
- If the build fails, throw an error
- Use PagerDuty's Amazon CloudWatch Integration to report an incident

**Comment by holdenhinkle** [comment]
# [Applitools](https://applitools.com/)
Has a [JS SDK](https://applitools.com/docs/api/eyes-sdk/index-gen/classindex-images-javascript.html) that we can use in a CloudWatch Node.js Canary.

**Comment by holdenhinkle** [comment]
# [CrossBrowserTesting](https://crossbrowsertesting.com/)
Product: [Automated Visual Testing](https://crossbrowsertesting.com/visual-testing)

They have an API that we can use in a CloudWatch Node.js Canary script:
- [API Documentation Version 3.0 - Screenshots](https://crossbrowsertesting.com/apidocs/v3/screenshots.html#!/default/get_screenshots_browsers)
- [API Documentation Version 3.0 - Screenshot Comparisons](https://crossbrowsertesting.com/apidocs/v3/screenshot-comparisons.html#!/default/get_screenshots_target_screenshot_test_id_target_version_id_target_result_id_comparison_base_result_id)

**Comment by holdenhinkle** [comment]
Google Spreadsheet comparison - https://docs.google.com/spreadsheets/d/1B-jBOmhtUOvVwVEs5RlbM9ny94d3G9BSUda3AvBGzA8/edit#gid=758931068

**Comment by holdenhinkle** [comment]
# Percy Cost
2 screenshots, every 5 minutes = ~17,510 screenshots a month

Percy cost: $99 a month, billed annually

![image](https://user-images.githubusercontent.com/9326247/123833259-2b890b00-d8d4-11eb-993e-a3ac3ed4b45b.png)

**Comment by pjhill** [comment]
Thanks -- we can reference the ticket comments and spreadsheet for the summaries.
