### ISSUE TITLE
VAMC health services should appear alphabetically

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26342]
## Issue Description
VAMC health services should be displayed alphabetically within categories. 

The sort order was handled by CMS until the change was made to use the type of care attribute. Sort order now needs to be handled by the FE. 

<details>
<summary> Screenshot from Prod </summary>

![image](https://user-images.githubusercontent.com/55411834/122800566-51813080-d280-11eb-8f5b-94916864cb10.png)

</details>

---
## Tasks
- [ ] Ensure the alpha order is displayed alphabetically within the type of care categories. 

## Acceptance Criteria
- [ ] When the health service page is viewed at the system level, service accordions should be alphabetized within the type of care attribute (i.e. alpha within Primary care or Mental health, for example)
- [ ] When the health service page is viewed at the facility level, accordions should be alphabetized within a single list (no categories are displayed at the facility level)
