### ISSUE TITLE
[FE] Disable feature flip 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#26346]
## Description

With the problem that was discovered with the Feature Flip and page loading, we have a hunch that the same problem is happening for the clipboard feature. 

To try to have a better pilot we are going to disable the reliance on the feature flip. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Remove reiances on Feature flip
- [x] update unit tests
- [x] add/update e2e tests
- [x] update docs to turn feature off

## Acceptance Criteria

- [x] Page still loads if the feature flip is broken/isn't loaded
- [ ] Deployed to production.
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
Updated docs https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/playbook/toggle-app.md
