### ISSUE TITLE
Midpoint Review [Caregivers, File Upload Error Workflow]

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26354]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [ ] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [ ] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [ ] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

#### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please be sure to include any relevant content artifacts.

## Artifacts

**Quick Summary:** The purpose of this enhancement to the online Caregivers form (10-10CG) is to improve the existing platform-level error messaging that appears when a file upload error occurs. The proposed changes provide more specific direction to the user based on the error. There are several scenarios listed in the [comments below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26354#issuecomment-865271591) along with the proposed changes.

- [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)
- [Mockups linked in comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26354#issuecomment-865271591)
- Link to content brief (if applicable)
- [Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/10-10CG-application-copy.md)
- Link to research plan ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md))  and conversation guide ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)) : N/A
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_ : N/A
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) for QA practice area review : N/A

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No
 
What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? **June 24, 2pm**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): Chris Dyer
- OCTO-DE Product lead (recommended):
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Dené Gabldón (UX), Dat Tran (Frontend)
- VFS Content, IA, accessibility, and QA specialists (if applicable): Peggy Gannon

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by Dene-human** [comment]
This is the second stage of Ticket #25320 and #17589 in which we just updated the copy of the error messages. Our goal now is to create an improved workflow UX that eliminates the need for the user to delete their file before trying an upload attempt again.


## Proposed NEW

### 1. Internet connection error
**Copy:** 

We're sorry. We had a connection problem. Please try again.

[Try again]  [Cancel]

**Desired action:** Try again with same file OR Upload a new file

![Connection problem.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/f9ba6955-5017-4f0d-8c2c-602fba797397)

### 2. File too large error
**Copy:**

We couldn't upload your file because it's too big. Please make sure the file is 10MB or less and try again.

[Upload a new file]

**Desired action:** Upload new file that is less than max size - _Please note that the file size is dynamic_
![too large.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/51a06f87-9f0b-4572-ae32-6f870fce1c01)

### 3. File too small error
**Copy:** 

We couldn't upload your file because it's too small. Please make sure the file is 1B or more and try again.

[Upload a new file]

**Desired action:** Upload new file that is more than min size - _Please note that the file size is dynamic_
![too small.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/8a94a7fc-5163-4c8b-a8cc-65a5400be09e)

### 4. Wrong file type error
**Copy:** 

We couldn't upload your file because we can't accept this type of file. Please make sure the file is a .pdf, .jpeg, jpg, or .png file and try again.

[Upload a new file]

**Desired action:** Upload new file in that fits the file type required-  _Please note that the file type is dynamic_

![file type.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/905b628f-8dd5-4421-b5b4-0898e4fba807)


### 5. Additional considerations

Forms with multiple file upload option should remove "Add another button" on error
![add another.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/4ded0997-9692-4df2-b29a-01a04fe23ef0)


## Current (old) for reference
![mult_error](https://user-images.githubusercontent.com/83595736/121927919-9dc2f280-cd0d-11eb-9f40-a7a21e37a33f.png)
![network_error](https://user-images.githubusercontent.com/83595736/121927953-a61b2d80-cd0d-11eb-94ae-074489836417.png)

**Comment by shiragoodman** [comment]
@tchrisdyer  - Asynchronous review scheduled for Thursday. You will receive feedback by EOD.

**Comment by peggygannon** [comment]
No content feedback for this work. Thanks!

**Comment by allison0034** [comment]
@tchrisdyer no design feedback, nice work!

**Comment by joshkimux** [comment]
@tchrisdyer no accessibility feedback from my end!

**Comment by noahgelman** [comment]
@tchrisdyer
I have a question. I don't think this is necessarily an accessibility issue.

There seems to be a lack of constancy of what the buttons are throughout each error.

For Internet Connection Error, the button says "Try again", which doesn't tell the user they can upload a new file, even though they're allowed to. It also has a "Cancel" option while none of the following errors do.

The following errors have "Upload a new file" but no "Try again" or "Cancel"

On Wrong File Type, there is a "Delete File" button, but no "Try again" or "Upload a new file" button. I'm not sure why they have to delete the file in this case but not the other cases.

It doesn't come off to me (and this might because I haven't used this functionality personally and am just going off the images) like the functionality of the buttons and labeling is consistent.

I'm not sure why in some cases I "Try again" or "Upload a new file" in others, or why I even have to "Delete" the file at all.

**Comment by Dene-human** [comment]
Hi @noahgelman 

Apologies for the confusion. The "Delete" button is from the old workflow that we are replacing with this one, I just put it there for reference.


There's two different error flows:

### Upload a new file
**Use case:** File too large, File too small, File type not allowed
Please note: We have added the Cancel button since preparing the brief for midpoint
![image](https://user-images.githubusercontent.com/83595736/123308475-b8595080-d4f1-11eb-9cf6-4419bb644c82.png)

### Try again
**Use case:** Network error
The reason for the difference is that with a network error the user can actually try again without choosing a new file.
![Connection problem.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/f9ba6955-5017-4f0d-8c2c-602fba797397)

**Comment by mnorthuis** [comment]
No IA feedback for this work, thanks!

**Comment by SKasimow** [comment]
@Dene-human can this one be closed?
