### ISSUE TITLE
[Spike] DS reason for appt prefix check

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26359]
## Description
In the direct scheduling flow, the character limit in the reason for appointment field is 150 less  characters for the 4 predefined booking notes. We would like to explore simplifying the booking note prefixes to allow for more characters in the user input.

### Requirements

- The reason for appointment value displayed in the appointment list/detail pages are only based on user input
  - There are no internal/provider notes displayed
- The radio options on the form remain unchanged (doesn't use the short prefix)
![Screen Shot 2021-06-21 at 12.04.48 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/9ddbc869-9d96-4cf1-88f7-ab1dfbb9b8e9)

---
## Tasks
- [ ] Determine if the following prefixes can be used:
- Routine
- New
- Medication
- Other

## Definition of Done
- [ ] Tasks are complete
- [ ] Research and recommendations are documented in this ticket
