### ISSUE TITLE
Type of care - update intro copy

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26375]
## Description
Per Content feedback, update the intro copy to avoid repeating the H1.
![type_of_care_26375.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/211b17e1-e98f-4593-9ceb-f6355a6e0f54)

---
## Tasks
- [ ] Type of care page

## Acceptance Criteria
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/type-of-care.md) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
- [Request flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request_flow.md)
- [Direct flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/direct-schedule-flow.md)
- [CC flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/community_care_flow.md)
- [Vaccine flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md)

**Comment by LeKeve** [comment]
Ready for validate. Documentation screenshots updated and added type of care page to vaccine flow doc.

**Comment by laurenernest** [comment]
Looks good! Closing ticket.
