### ISSUE TITLE
Review Instances - SSL capabilities/certificates for the review slug URL  

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#26372]
## Description
The platform's review instances (RIs) are not currently deployed with an SSL certificate automatically. This makes it difficult to test various features, including browser-based geolocation, without going through various manual steps to issue and provision a working cert on the instance that would enable SSL for the review slug URL. 

We have a certificate authority (CA) that we have in AWS, which would allow us to issue certificates using that CA to the current review instances. Then, developers could trust that CA in their browser, thereby enabling them to connect to the review slug URL securely. Theoretically, this will allow developers to test the features which require SSL. 

Note: When we move RIs into EKS, they will have a *vfs.va.gov domain name, and there will be additional work to enable SSL for those RIs. (Will link to ticket for that future effort) 

## Technical notes
Will link to how Review Instances work including current limitations 

---
## Tasks
- [ ] Create the automation to issue/attach a cert to the review instance endpoint 
- [ ] Document how this works (which include how developers need to trust the CA in their browser) 

## Definition of Done
- [ ] The review instances support SSL (using the same slug URL they have now), so that developers can test features that require a secure connection.

**Comment by jhouse-solvd** [comment]
@drorva - would you take a look at this? We might have a decent interim solution that would provide SSL capabilities on RIs and address that need for developers. The effort is pretty low, and we think we could fit it into sprint 55 pretty easily, but wanted to check with you to get your thoughts. . 

Please see [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20078) for where this originated

**Comment by mpelzsherman** [comment]
Any updates?

**Comment by jhouse-solvd** [comment]
@mpelzsherman - I think we just need to publish documentation for this. 

If you take a look at https://app.zenhub.com/workspace/o/department-of-veterans-affairs/devops/issues/9466, you can see what has been done so far. the last task is to update documentation. 

Will follow up and see what we can do in the near future. Thanks for your patience.

**Comment by dginther** [comment]
verified that this works with @mpelzsherman
