### ISSUE TITLE
Application Hosting and Deployment: Autonomous deployment for Platform Crew developers (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#26376]
## Problem Statement 
It's difficult for Platform Crew teams to deploy applications to the platform's new delivery infrastructure. There is no clear process to follow for requesting the setup of a new application. And, there is limited documentation to support self-service. 

How might we make it easier for Platform crew developers to deploy applications on the platform without needing to manage the underlying infrastructure? 

## Hypothesis or Bet
Our hypothesis is that we can craft an experience that increases autonomy for developers when deploying to the new infrastructure. 
Our hypothesis is that by collaborating w/ FE/BE tools teams, we can provide consultation for app isolation and backend autonomous deployment efforts in alignment with the future vision for the platform. 

## We will know we're done when... ("Definition of Done")
- [x] Platform crew developers can deploy their application to EKS using processes defined by the Infrastructure Team
- [ ] Documentation is available for the following: 
  - [ ] Managing application manifests 
  - [ ] Building a container for k8s
  - [ ] Pushing a container to ECR 
  - [ ] Viewing deployments in ArgoCD
  - [ ] Troubleshooting deployments

## Known Blockers/Dependencies 

- Formalization of Tiger team w/ stakeholder acceptance
- FE Tools app isolation discovery work
- BE Tools backend autonomous deployment work

## Projected Launch Date
Beginning of Q3 2021

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Application Hosting and Deployment using Container Orchestration (EKS)
* **Product Outline**: [LINK](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by mchelen-gov** [comment]
i believe we have confirmed vets-website has no EKS involvement, since frontend can be built in GHA and deployed directly to S3 buckets
CMS Core would be good to work with for migration of Drupal to EKS though

**Comment by jhouse-solvd** [comment]
This initiative can be considered complete once all of the checklist items have been addressed and supporting artifacts and documentation have been linked.

Moving to review.

**Comment by jhouse-solvd** [comment]
_A lot was learned through Q3 and Q4 2021..._ 

We worked closely with the Console Services team to deploy Vets-API to the platform's new delivery infrastructure (EKS). While that work is ongoing, we believe it key to separate the work of migrating Vets-API from the work being done to improve the application onboarding process for platform applications more broadly. 

**Please see the following initiative for work related to the migration of Vets-API:** 
[Application Hosting and Deployment: Make Vets-API operational on the platform's new delivery infrastructure (EKS) in DEV
](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/35039)

In Q1 2022, [we updated the application onboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36389) to make it easier for platform crew teams to bring new applications online. 

**Several platform teams - Console UI, Integration Experience, and Console Services - have been successful in onboarding new applications to EKS. Moving forward, we aim to solidify the onboarding process, incorporating feedback from platform crew teams**. 

We propose a new initiative for Q2 2022 that picks up where this initiative left off. While #26736- this initiative, as scoped - may not be considered fully complete, _any remaining items (documentation, testing, etc) will be rolled into the following initiative_, pending approval of leaderships and stakeholders during Q2 quarterly planning: 

[Application Hosting and Deployment: Solidify application onboarding process for Platform Crew teams (EKS)](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/38890)

Closing this issue. Please reach out with any questions or concerns.
