### ISSUE TITLE
Monitoring - Enable Datadog agent to run on all instances and clusters, across all environments

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#26378]
## Description
Now that we have the licenses that we need, we want to be sure that the agent is installed and running on all EC2 instances and all EKS clusters that are managed by the platform crew, across all environments. 

---
## Tasks
- [x] Submit PRs to enable Datadog agent on 
  - [x] all EC2 instances 
  - [x] docker containers for vets-api, et al
- [x] Merge PRs
  - [x] all EC2 instances 
  - [x] docker containers for vets-api, et al
- [x] Make sure the above are deployed
  - [x] EC2 instances
  - [x] docker containers for vets-api, et al 

## Definition of Done
- [x] All metrics are being collected and visible in the UI

**Comment by jhouse-solvd** [comment]
@mydesignrocks - if you can cross-reference any PRs, add notes, and check off tasks to help show status on this one as well, that would be very helpful. no rush. thank you, sir.

**Comment by mydesignrocks** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/9438
and 
https://github.com/department-of-veterans-affairs/devops/pull/9439
More to come... and I will tag this issue.

**Comment by mydesignrocks** [comment]
all BRD side of datadog monitoring and EKS cluster side are complete, @jhouse-solvd 
I will keep this open for a couple of days to bake in and close it.

**Comment by mydesignrocks** [comment]
@jhouse-solvd  - should we keep this open until we wrap up the documentation aka "one sheet"?

**Comment by jhouse-solvd** [comment]
@mydesignrocks - Great point. 

Here is the documentation to ["Get Acquainted with Datadog"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1775435805/Get+Acquainted+with+Datadog)

This task is done. Closing.
