### ISSUE TITLE
Developer Experience: Research tools available to support platform crews deploying to Kubernetes 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#26385]
## Description
Operations needs to provide tools and procedures for developers that will be deploying applications to EKS. Before we can make those recommendations or build the toolsets, we will need to research and try a variety of tools and document their pros and cons. The goal is to be able to consult with platform crew teams to support their proposed solutions around app isolation and improving the developer experience. 

## Background/context/resources
We want to move towards the developer experience being consistent locally, and through the various hosted environments. Ideally, developers won't have to use kubectl directly because of its steep learning curve. There are a number of tools that make this experience easier for developers. 

We will also want to consider how a chosen tool could integrate or support the VTK developer tool. We think that VTK could act as a wrapper to kubectl and or other scripts and command-line utilities. 

Here are some of the tools that Demian has found previously: 
- Garden.io 
- Devspace.sh
- Tilt.dev
- Telepresence.io
- Skaffold.dev

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Find tools that work well with GitOps pipelines (and ArgoCD) 
- [x] Play with tools and test them out to understand the feasibility of each one
- [x] Make a list of pros and cons for each tool 

## Definition of Done
- [x] The feasibility and pros and cons of each tool have been documented in Confluence

**Comment by jbritt1** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/1717075969/Tools+for+Development+on+Kubernetes

**Comment by jbritt1** [comment]
Closable yeah?

**Comment by jhouse-solvd** [comment]
Checking out the doc now...

**Comment by jhouse-solvd** [comment]
Great starting place for our discussions. Super great work on this research and evaluation. 

Closing.
