### ISSUE TITLE
Clinic selection - update heading and body copy

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26384]
## Description
Per Content feedback, update the heading and description copy to include the name of the VAMC rather than have it listed below the intro line.
![clinic_selection_26384.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/0c5dcc28-9d84-4e84-9796-cc43b88baf64)

---
## Tasks
- [ ] Clinic selection - multiple locations
- VA flows
- ~Vaccine flow~ _(removed)_

## Acceptance Criteria
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/clinic-selection.md#multiple-clinics) 

### Out of Scope

- Clinic selection version with a single location

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
- [Request flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request_flow.md)
- [Direct flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/direct-schedule-flow.md)
- ~[Vaccine flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md)~ _(removed)_

**Comment by laurenernest** [comment]
@LeKeve good catch. waiving vaccine flow due its variance from the original copy. I also caught that the copy doc had 24 so I updated it to reflect the conditional number of months for the last seen statement.

**Comment by LeKeve** [comment]
Documentation updated. Ready for validate

**Comment by laurenernest** [comment]
Looks good. closing ticket.
![26384 validation](https://user-images.githubusercontent.com/72046525/125653440-6096a745-3e21-4a05-8fbf-37b74e366d88.png)

@LeKeve would this clinic selection page never show in the request flow?

**Comment by LeKeve** [comment]
@laurenernest That's correct, clinic selection isn't shown in request flow.
