### ISSUE TITLE
Monitoring - Parity between Prometheus alerts and Datadog alerts 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#26380]
## Description
We need to identify alerts in Prometheus that aren't out of the box and translate those Datadog. Or we treat this as a greenfield alerting situation and we configure sensible alerts for all of the new services and infrastructure. 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Inventory / Audit
- [ ] Determine what to translate 
- [ ] Determine how to translate 
- [ ] Prioritize
- [ ] Implement 

## Definition of Done
- [ ] We have equal or greater visibility and alerting of our infrastructure in Datadog when compared to Prometheus

**Comment by jhouse-solvd** [comment]
We are treating this as a greenfield alerting situation and will configure sensible alerts for all infrastructure services and components. We will be creating individual tickets for each component to customize the metrics that are specific to that service.

Closing.
