### ISSUE TITLE
Complete a Usability Study for Rated Disabilities & View Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2639]
## Story
As a member of the eBenefits Team Design Team, I need a usability study regarding the tools page implementation so that I can validate that the new components on the  tools page are an effective choice for conveying disability ratings.

## Tasks
- Create the research plan
- Create the conversation guide
- Establish [mockups](https://xd.adobe.com/view/2b040c88-19d3-47dc-4eba-d18d0636ae4e-5d35/) for users to view `* - separate ticket`
- Schedule the study with recruiters (Perigean)

## Considerations
- Components to study for Rated Disabilities:
  - Right rail (do you see any information on {x, y, z}
  - Cards (does the TCDR seem prominent?  are individual ratings in cards effective?)
  - top-border (is it clear where the list starts?)
  - Navigation within the tools page (are breadcrumbs going to be enough?)
- Components to study for View Dependents:
  - View page

## Acceptance Criteria
- [ ] The usability study has been completed
- [ ] New components have been validated
- [ ] Analysis findings have been documented

**Comment by sporeboy** [comment]
Links to several components...

- [Baselining](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/research-findings.md)
- [Mockups/Prototypes](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/)
- [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119)
- Conversation Guide
- Readout

**Comment by sporeboy** [comment]
Conversation guide initial draft is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-convo-guide.md
