### ISSUE TITLE
Build health care rates pages with R&S template

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26411]
## Issue Description
As part of moving tier 2 content from tier 1 pages into R&S, we need to rework rates pages using R&S templates.

We need to create the 2021 page and build three years of past rates pages

## Tasks
- [ ] Build past copay rates pages in Drupal (Selina)
- [ ] Build new copay rates page (Selina)
- [ ] Check numbers and review (Randi)

## Acceptance Criteria
- [ ] Past and current copay rates pages built out in Drupal

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
