### ISSUE TITLE
Build out pension rates pages in R&S template

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26417]
## Issue Description
As part of moving tier 2 content from tier 1 pages into R&S, we need to rework rates pages using R&S templates.

We need to create the 2021 page and build three years of past rates pages

## Tasks
- [ ] Build past Veterans pension rates pages in Drupal (Selina)
- [ ] Build new Veterans pension rates page (Selina)
- [ ] Build past Survivors pension rates pages (Selina)
- [ ] Build new Survivors pension rates pages (Selina)
- [ ] Build past protected pension rates pages (Selina)
- [ ] Build new protected pension rates pages (Selina)
- [ ] Check numbers and review Veterans pension (Randi)
- [ ] Check numbers and review Survivors pension (Randi)
- [ ] Check numbers and review protected pension (Randi)

## Acceptance Criteria
- [ ] Past and current copay rates pages built out in Drupal

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
