### ISSUE TITLE
MCP - Set up SQS/SNS 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#26429]
## Technical Task

We want to set up SQS/SNS resources to allow the Medical Co-Pay service to publish events to Vets-API. This way we can put email notifications in a queue and process them in a performant manner.

SQS - Simple Queue Service
SNS - Simple Notification Service

---
## Tasks
- [ ] Create the resource(s) in AWS
- [ ] Connect Vets-API
- [ ] Connect VA Medical Co-Pay service

## Acceptance Criteria
- [ ] VA Medical Co-Pay service can publish an event
- [ ] Vets-API can receive the event

**Comment by LinnJS** [comment]
[AWS docs](https://docs.aws.amazon.com/sns/latest/dg/subscribe-sqs-queue-to-sns-topic.html) for SNS/SQS

**Comment by rileyorr** [comment]
As discussed during backlog grooming - this isn't applicable anymore
