### ISSUE TITLE
Update accessibility documentation to reflect recent leadership decisions

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#26426]
## Issue Description
Accessibility specialists have been overwhelmed with work assignments and are not able to complete everything on their plate. Because of this, VSP leadership and OCTO leads have agreed to make the following changes:
 - Accessibility specialists will no longer both support the same Collab Cycle Reviews.
 - Accessibility specialists will be temporarily removed from Design Intent’s - both VSA teams and non-VSA teams.

Platform has decided to assign accessibility specialists dedicated VFS teams to support for Collab Cycle reviews. See[ Accessibility Assignments tab](https://docs.google.com/spreadsheets/d/1GY07PAdfmRsXYPdoRvKpOARYyUtXcD2nw8Bl6deIs-s/edit#gid=490791592) of this spreadsheet.

This ticket will
 - update our operational documentation 
 - update VFS-facing documentation so they are aware of the changes.

---
## Tasks
- [x] Add summary of changes to Collab Cycle Change Log, and include list of Noah and Trevor's assigned teams.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
@shiragoodman I updated the internal process document as well as the 2 design intent files

**Comment by shiragoodman** [comment]
@allison0034 FYI please update change log. Thank you!

**Comment by shiragoodman** [comment]
@allison0034 I'm opening this back up.

Josh contacted me and commented how VSA accessibility specialists are still able to attend Design Intents, and their teams are still able to receive accessibility feedback.

Can we update the Design Intent issue template and Design Intent touchpoint guidance to add the word "Platform" to the below sentence?
`
For the Design Intent, you’ll receive feedback from design and IA only. You won’t receive feedback from accessibility, content, or QA, as it’s too early in the development process.`

Can we also add an additional line stating something like, "If your team has a dedicated Accessibility Specialist, please be sure to include them in the attendees list so that they may attend the meeting and provide feedback. As mentioned above, Platform will not be including an Accessibility specialist in the Design Intent."

Thanks, Allison! Let me know if you have any questions.

**Comment by allison0034** [comment]
@shiragoodman yes, I will update it!

**Comment by allison0034** [comment]
@shiragoodman 
"As mentioned above, Platform will not be including an Accessibility specialist in the Design Intent."

We are including Angela and Josh so I should remove this sentence correct?

**Comment by allison0034** [comment]
@shiragoodman I am thinking we may not need this whole paragraph. We do not say it for any other practice area so why say it for accessibility? 

Can we also add an additional line stating something like, "If your team has a dedicated Accessibility Specialist, please be sure to include them in the attendees list so that they may attend the meeting and provide feedback. As mentioned above, Platform will not be including an Accessibility specialist in the Design Intent."

We currently have this...
VFS brings:
  - Designer(s) (required)
  - Product Manager (required)
  - OCTO-DE Design Lead (required)
  - OCTO-DE Product Lead (recommended)
  - Accessibility, Content, IA, and QA specialists (if applicable)
  - Other stakeholders you want to invite (if applicable)

**Comment by shiragoodman** [comment]
@allison0034 key word there is _Platform._ VFS teams are able to include their own accessibility specialists... AKA Josh and Angela. Does that answer your question?

**Comment by shiragoodman** [comment]
yes, that sounds good to me. Let me know when it's ready and i can review :)
