### ISSUE TITLE
Build disability rates pages with R&S template

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26420]
## Issue Description
As part of moving tier 2 content from tier 1 pages into R&S, we need to rework rates pages using R&S templates.

We need to create the 2021 page and build three years of past rates pages

## Tasks
- [ ] Build past birth defect rates pages in Drupal (Selina)
- [ ] Build new birth defect rates page (Selina)
- [ ] Build past special benefit allowance rates pages in Drupal (Selina)
- [ ] Build new special benefit allowance rates page in Drupal (Selina)
- [ ] Build past special monthly compensation rates pages in Drupal (Selina)
- [ ] Build new special monthly compensation rates page in Drupal (Selina)
- [ ] Build past Veterans disability rates pages in Drupal (Selina)
- [ ] Build new Veterans disability rates page in Drupal (Selina)
- [ ] Check numbers and review (Randi)

## Acceptance Criteria
- [ ] Past and current copay rates pages built out in Drupal

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
