### ISSUE TITLE
[FE][SPIKE] Formik Research. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#26439]
## Description

There is a strong chance we will pioneering the new forms system based on Formik. We need to get smart on how we can use formik and what the new Form system will be able to do. 

## Questions to Answer

- [x] Can we create a form based on an FHIR questionnaire
- [x] Can we create a large dynamic form 
- [x] Can we create a todo list with many small forms
- [x] Understand the differences between Formik and Formulate
## Tasks

- [x] Create a prototype
- [x] Update relevant documentations

## Acceptance Criteria

- [x] Relativant documentation has been created
- [ ] Findings shared with the appropriate team members

**Comment by mdewey** [comment]
Created base requirements for new forms system: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/formulate/requirements.md

**Comment by mdewey** [comment]
Spike notes: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/formulate/spike.md#L16
