### ISSUE TITLE
Platform Website - Audit, Inventory, & Publish updated Google Analytics & dashboarding documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#26445]
## Problem Statement 
Platform Analytics & Insights’s existing documentation and training is not empowering VFS teams to easily trust and use their data to build better products on VA.gov on their own.

We have a growing amount of VFS teams who need support, and Platform Analytics & Insights spends time answering both basic and complex questions.

How might we improve VFS teams' abilities to find analytics reporting and dashboarding answers on their own so that we are less of an impediment to using data and VFS teams are able to self-serve descriptive data use?

## Hypothesis or Bet
If we add, update, and improve our documentation and training, then we expect:
- Platform Analytics & Insights to spend less time answering questions that have documented answers
- VFS teams to be able to understand how to read available descriptive analytics on their own

## We will know we're done when... ("Definition of Done")
- [See Platform Objective 1 OKRs](https://docs.google.com/spreadsheets/d/1qVAJKXVYys_YlRifglZGVbYQc09mKsLAsI1RTqPbHa8/edit#gid=715168434) for outcomes
- [ ] Necessary documentation & training is updated & added to the Platform Website
- [ ] Obsolete and ineffective Github documentation is deprecated
- [ ] Corresponding operational documentation is updated in Confluence

## User Stories

- As a VFS PM, I need to know how to see & read my product’s user interaction data
- As a VFS team, I need to understand my product’s user interaction data definitions
- As a Platform Analytics team member, I need to know how to support VFS teams with their Google Analytics and dashboarding needs.

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*
- Any design or research support - we will cover internally on the team or look for support from Service Design & the Platform Design Lead.
- Content/Confluence questions - we will collaborate with the Content & IA team where necessary

## Projected Launch Date
We expect to begin this initiative Sprint 63 or 64. Projected Launch date is tentatively 2-3 sprints after the initiative begins.

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: [Platform Analytics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/analytics/analytics-product-outline.md)
* **Product Outline**: [Platform Analytics Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/analytics/analytics-product-outline.md)
* **README**: See User Guide
* **User Guide**: Customer Support Guide
### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: TBD - Analytics KPIs dashboard in Domo
* **Release plan**: [Release Plan ticket
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26337)

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
