### ISSUE TITLE
Draft July newsletter edition (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26449]
# User story

As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- [ ] Solicit content from PMs (James and Liani)
- [ ] Schedule and conduct pair writing sessions (Amy)
- [ ] Draft newsletter edition (Amy)

Tasks for future sprints:

- Conduct reviews for technical accuracy and OCTO-DE signoff
- Prepare MailChimp version (Service Design, but we support)
- Publish the newsletter via email (Service Design)
- Announce the newsletter via Slack (Service Design)
- Update the Google Form (Amy)
  - remove previous submissions
  - update form langauge for next round of submissions
  - create new link for sharing survey

# Acceptance criteria
- To come.

# Reference info
- n/a

**Comment by lianilychee** [comment]
6/25 fri:
- we'll give ppl till fri 7/2 to submit content, then on the Monday after Amy will schedule for ideally later that week, or the 1st half of the week after _that_

**Comment by lianilychee** [comment]
we're doing a joint july/aug summer edition, per https://dsva.slack.com/archives/G01JN8X1S7M/p1625596206101500
