### ISSUE TITLE
[Spike] Surfacing primary care recommendations

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26442]
## Description
How might we surface a user's current primary care facility or provider to reduce steps in the scheduling flow?

## Tasks
- [ ] Determine if we can surface a user's current primary care facility

- [ ] Determine if we can surface a user's current primary care provider or PACT

- [ ] Answer the following questions:
- On which pages can we surface this information?
  - What is the technical recommendation based on performance, LOE, etc?

## Technical Notes
- Look at CDW endpoints

## Time Box
8 hours

## Definition of Done

- [ ] Tasks are complete

- [ ] Research and recommendations are documented in this ticket

**Comment by jbalboni** [comment]
These endpoints don't seem to be work in staging, so research is a bit limited.

There are two endpoints, one that returns clinics and one that returns providers. I think the clinics one is more likely to be useful to us, because we do clinic based scheduling rather than provider.

The example and schema indicate that we'd be able to see the full facility id as well as clinic ids. It seems pretty clear that we'd be able to get a primary care facility based on that, and maybe some clinics to filter down to.

Some questions I have:

1. Would we see clinics across multiple facilities? I believe you're only supposed to have one PACT active at a time, but not sure if that's reflected here
2. How fast is it? This query was slow before, but I think it should be similar to finding clinics for primary care DS, so maybe it's not so bad now
3. What types of clinics do we get back? It looks like more than primary care from the example I have.

Appointment history alternative:

Another approach we could take is to try to find the right facility from appointment history (or future appointments). We'd want to be careful about how much appointment data we were requesting, but we could infer the facility from past or future visits. We could also use request data to do this. This would mainly be a question of what logic to use to filter down to one or two facilities (depending on the design)

Another thing that would be useful to know is if we can tell what types of appointments/requests are repeated. Are people making regular optometry appointments, or just once in a while, for example?

**Comment by jbalboni** [comment]
I was able to get the two calls working in staging. Some partial answers to my questions:

1. At least in staging, judy morrison has two PACTs, both at the same facility. This is probably more reflective on the staging CDW instance than actual practice
2. In staging, it's about 400ms. That at least suggests it could be reasonable in production
3. We have to make the request by stop code, so we're only getting primary care clinics. We do get providers who are non-primary care providers, but are part of the PACT.

Some additional questions:

How would we narrow down a PACT to a location? It looks like we can get PACT primary care clinics, which have an sta6aid, so we can narrow that down to a specific location. But would get just one per team? Or more?

Are there PACTs that are associated non-primary care stop codes? I suspect no, based on what we've been told about PACTs, but I don't really know.

**Comment by laurenernest** [comment]
Thanks! I'll check with stakeholders about the additional questions.

Additional work will be captured in new tickets.
