### ISSUE TITLE
[Tech-Debt] Confirm and resolve System and facility health services for the below health services that did not match in migration [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26458]
## Story
As a Veteran I need to have accurate System and facility health services, so I can confirm the correct location facility to complete my health care journey.

## Task
- Review the following Facility health services that did not have a matching System health service in the associated Systeam and determine if a System health service needs to be added.  Then add this facility health services in support of the facilyt listed.
- [ ] vha_553 - Specialty care;John D. Dingell Department of Veterans Affairs Medical Center;Specialty care at VA Detroit health care;;VA Detroit health care
- [ ] vha_740GB - Nutrition, food, and dietary care;McAllen VA Clinic;Nutrition, food, and dietary care at VA Texas Valley health care;;VA Texas Valley health care
- [ ] vha_757 - Neurology;Chalmers P. Wylie Veterans Outpatient Clinic;Neurology at VA Central Ohio health care;;VA Central Ohio health care

## Acceptance Criteria
- [ ] System and facility health services have been either confirmed not to exist and documented in Playbook
- [ ] If System and facility belong to system, they have been added to System and a facility health service is then in place and updated.
