### ISSUE TITLE
Contact info - update heading and body copy

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26454]
## Description
Per Content feedback, update the copy on the contact information page:
- heading
- description
- time format (requests)
![contact_info_copy_26454.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/0eb3e5e1-1053-47c0-bbe5-90cac769ba45)

---
## Tasks
- [ ] Contact Information page
- Request flows
- Direct flow
- Vaccine flow

## Acceptance Criteria
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/contact-information.md) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
- [Request flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request_flow.md)
- [Direct flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/direct-schedule-flow.md)
- [CC flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/community_care_flow.md)
- [Vaccine flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md)

**Comment by laurenernest** [comment]
copy changes look good! closing ticket.

@LeKeve can you update the flow screenshots? thanks!

**Comment by LeKeve** [comment]
@laurenernest Contact info screenshots updated for all flows!
