### ISSUE TITLE
Draft June newsletter edition (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26450]
# User story

As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- [ ] Revise the June issue based on technical reviews (Amy)
- [ ] Secure final approval for June issue (Amy)
- [ ] Draft newsletter edition (Amy)
- Prepare MailChimp version (Service Design, but we support)
- Publish the newsletter via email (Service Design)
- Announce the newsletter via Slack (Service Design)

Tasks for future sprints:

- Conduct reviews for technical accuracy and OCTO-DE signoff
- Update the Google Form (Amy)
  - remove previous submissions
  - update form langauge for next round of submissions
  - create new link for sharing survey
- Solicit content from PMs (James and Liani)

# Acceptance criteria
- To come.

# Reference info
- n/a

**Comment by lianilychee** [comment]
6/25 fri:
- Amy: 
  - all set!  in fact too set :D 
  - we'll remind service design that we're sending on the monday/tuesday of the month
