### ISSUE TITLE
Publish SLAs/SLOs re: Contributing to Platform website support (Establish process)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26452]
# User story

As a Platform team member, I need to know the level of support I can expect from the Content Team, so that I can balance my documentation work with initative work.

# Tasks

- [x] (Gretchen) Find comparative SLOs.
- [x] Find Platform/VFS support SLOs.
- [x] Draft Content/Platform support SLOs.
- [x] Publish Content/Platform support SLOs.
- [x] Socialize Content/Platform support SLOs.

Acceptance criteria
- SLOs have been socialized to Platform teams.

# Reference info
- [draft SLOs](https://vfs.atlassian.net/wiki/spaces/~248103751/pages/1640333324/SLOs+about+Content+Platform+support)
- [Platform/VFS support overview](https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html)
- https://hub.rayoscms.com/support-overview/
- [scratch notes](https://vfs.atlassian.net/l/c/a1rPAL28)

**Comment by lianilychee** [comment]
6/25 fri: 
- Gretchen will continue digging into comparative works today, and will have something to share at team sync on Monday

**Comment by lianilychee** [comment]
6/28 mon:
- Gretchen: It's still going!  Gotta wrangle a few thoughts and then will share tomorrow SU

**Comment by lianilychee** [comment]
7/1 thurs:
- liani to take a pass at reconciling the notes at the bottom w/ the notes at the top, then pass to gretchen

**Comment by lianilychee** [comment]
7/2 fri - tentative socialization plan for the sla's/slo's:
- two mediums: 
  - Platform demo Weds 7/7
  - #VSP-confluence channel

Sprint 56 - Socializing the new template ticket and SLA's/SLO's:
- three mediums: Platform demo, #VSP-confluence channel, PMs' channel + sync
  - Platform demo Weds 7/21
  - #VSP-confluence Tues 7/20
  - Product mgrs
    - channel Tues 7/20

**Comment by lianilychee** [comment]
draft message to #VSP-confluence channel

---

(some emojis here)

hello all -- thank you for all your questions about the Platform website, Confluence, and Scroll Viewport so far!

The Content Team has put together **preliminary SLAs/SLOs** governing how and how quickly we respond to you.

Important points:

- Do not DM or tag us in channel messages.
- We’ll acknowledge most questions within 1 business day of posting, and strive to resolve them within 3.

You can read the full document on our [Platform website support overview](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1640333324/Platform+website+support+overview).

Questions?  Let us know in 🧵
