### ISSUE TITLE
Platform Communications Playbook - Guidelines and Principles

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#26455]
## Problem Statement 
A pain point we've heard a lot is a lack of transparency about Platform priorities and product decisions leads to VFS teams being blindsided by Platform changes resulting in them running into avoidable issues.

How might we provide greater visibility and awareness into decisions and plans the Platform has so that VFS teams are not blindsided by product changes?

## Hypothesis or Bet
By creating a playbook for how Platform teams should define and execute product communications, we will improve customer satisfaction by increasing their understanding of Platform product priorities and plans.

## We will know we're done when... ("Definition of Done")
Platform teams are following the guidelines for:
- how customers learn of a product change
- how we remind them of a product change
- how we enable customers to learn more about a product change
- how  we enable customers to provide feedback on a product change
- how we respond to customer feedback on a product change

## Known Blockers/Dependencies 
None

## Projected Launch Date
Q4

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Platform Communications Playbook
* **Product Outline**: [https://vfs.atlassian.net/l/c/n7Y0oVxU](https://vfs.atlassian.net/l/c/n7Y0oVxU)
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: [https://vfs.atlassian.net/l/c/n7Y0oVxU](https://vfs.atlassian.net/l/c/n7Y0oVxU)
* **Release plan**: [https://github.com/department-of-veterans-affairs/va.gov-team/issues/32750](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32750)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jchasia-adhoc** [comment]
**Feedback from prioritization workshop on 6/29/21**

Create epics for each product communications 'play':

**Comment by jchasia-adhoc** [comment]
MVP: https://vfs.atlassian.net/l/c/CvMiSxW1

**Comment by Khyatinp18** [comment]
2/16/2022:
Platform communication playbook is live now. No additional work needed. Closing this now.
