### ISSUE TITLE
Submit Contact Center Documentation

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26469]
## Background
Before a feature is released to production, we should give the Contact Center some documentation about the new feature they might reference in case a Veteran comes with a question.

## Tasks
- [ ] Draft a walkthrough of the feature, highlighting functionality and error states
- [ ] Record, edit, render and share a video walkthrough of the feature
- [ ] Submit using this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-contact-center-review.md)

## Acceptance Criteria
- [ ] A request has been sent to the Contact Center for review
