### ISSUE TITLE
Request Midpoint Review (Dep Ver Modal)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26466]
## Background
Part of the collaboration cycle is to do a Midpoint review before usability and this requires artifacts to be completed, see below.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/README.md)
- Link to or attach [prototype or mockups](https://xd.adobe.com/view/659d31d9-4d54-4400-ad7b-25bbe62ef212-30ce/screen/8d9f1404-ebe1-40f8-8242-a5a90bea180d)
- Link to content brief (if applicable)
- Link to or attach your project's content [source of truth](https://xd.adobe.com/view/659d31d9-4d54-4400-ad7b-25bbe62ef212-30ce/screen/8d9f1404-ebe1-40f8-8242-a5a90bea180d) 
- Link to research [plan  and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/dependency-verification/research-design/usability-testing-1)
- Link to [regression test plan](https://dsvavsp.testrail.io/index.php?/cases/view/5554)  _for QA practice area review_
- Link to [test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/cases/view/5554) (even if just a draft) for QA practice area review

## Tasks
- [x] Compile the above listed artifacts
- [x] Complete a midpoint review request [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-midpoint-review.md)

## Acceptance Criteria
- [x] Request submitted for asynchronous review

**Comment by jason-gcio** [comment]
Requested July 30 at 2 pm ET (async)
