### ISSUE TITLE
Conduct Internal 508 Review (Dep Ver Modal)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26476]
## Background
Before going into production, we need to ensure we have conduct all the internal 508 points of interest.  Coordinating with Josh would be best. or at least share results with him.

## What artifacts do I provide?

VFS provides:
- Access information for the tool or feature in production do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository
- Verify foundational accessibility tests are complete. Choose one of these 2 options:
  - **(preferred)** Use the [TestRail VSP accessibility testing checklist](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
  <br/>**OR**
  - Certify the checklist of required accessibility items in the audit request issue
  - **Required accessibility checklist**
    - [x] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - [x] [Axe scans included in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - [x] [Color tests for proper contrast and colorblindness](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)
    - [x] [Content zoomed to 200%, 300%, 400%](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - [x] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - [ ] [Screen reader tests (VoiceOver + Safari or NVDA + Firefox)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
  - **Recommended accessibility checklist**
    - [x] [Keyboard end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#future-accessibility-tests)
    - [x] [Axe-coconut scans in daily development](https://www.deque.com/blog/test-leading-edge-accessibility-axe-coconut-axe-core-3-0/)
    - [x] [WAVE tool spot checks](https://wave.webaim.org/)

## Tasks
- [x] Conduct internal 508 review per the guidelines above, in Considerations
- [x] Show results from list above in the [508](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/dependency-verification/508) folder for the feature

## Acceptance Criteria
- [x] Internal 508 review has been completed and a discussion has been started

**Comment by micahchiang** [comment]
Internal audit findings are documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/508/README.md). Summary of major changes / necessary follow up items: 
1. Modal doesn't have an h1 so aXe throws a header warning. aXe doesn't seem to scan the rest of the DOM when the modal is active(?)
2. 400% zoom and <1200px viewport width causes text overflow on the buttons.
3. VoiceOver (and presumably other screen readers) read the buttons without issue but none of the modal content is read. We may want to consider adding aria tags to make these things readable.

**Comment by joshkimux** [comment]
@micahchiang Thank you for this! You're the best 🥳
