### ISSUE TITLE
[Design] Harassment Reporting Tool - Introduction Page mockup 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#26477]
## Description 
_The Office of Resolution Management, Diversity and Inclusion (ORDMI) is the office in-charge VA Wide for processing complaints from Veterans and Employees for alleged Civil Rights Violations as well as for Harassment, Reasonable Accommodations, and other inappropriate behaviors while on a VA Site._

_In response to Section 5303 of the Deborah Sampson Act which is part of the Megabus Bill that was passed in January, and new congressional demands for action, a team of Presidential Innovation Fellows (PIFs) is scoping the feasibility of creating a secure, online reporting tool on VA.gov that would enable Veterans and VA employees to report alleged incidents about violations from Veterans and VA employees which occur while on a VA Site._

## Scope of Work
In support of the HRT initiative we'll need to build a "Harassment Reporting 5303" Introduction page as the home page for Veterans and Beneficiaries that are looking to access the Harassment reporting tool (HRT).  The content from this pace will be provided by the PIF/ORDMI team and we'll need to get that information vetted by our local content team for inclusion on the landing page.  
A similar page with content exists: VA OIG Web Page and Link to Report Wrongdoing - https://www.va.gov/oig/hotline/default.asp.  
Business Requirements are listed: [spectrum of workplace behaviors (version 2).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6703489/spectrum.of.workplace.behaviors.version.2.xlsx)
 

## Tasks 
- [x] Mock up introduction page accordingly to VA.gov design system specs
- [x] Design both Desktop and Mobile 
- [x] Incorporate content provided by ORDMI Stakeholders (PIFs will provide)
- [ ] Ensure design is ally compliant and complies with VA.gov design system specifications 
- [ ] URL and Placement will be determined by PO/PM of PW Team

## Acceptable Criteria 
- [ ] Designs are completed in accordance with task identified above 
- [ ] Designs are approved via VSP Design Intent Review / Design System 
- [ ] Designs can be used by FE team to build our landing page

**Comment by callen2563** [comment]
@brianalloyd Just posting the Unauthenticated and Authenticated Intro pages I have mocked up so far but these will need copy. 

![HT-Content page - Unauthenticated - Mobile](https://user-images.githubusercontent.com/68560244/125825255-d5223dbd-c622-420a-9ec1-20b63a52bce0.png)
![HT-Content page - Unauthenticated - Desktop](https://user-images.githubusercontent.com/68560244/125825263-3b80d8ac-1a18-4c99-8eda-984776a8384a.png)
![HT-Content page - Authenticated - Mobile](https://user-images.githubusercontent.com/68560244/125825272-14288921-a5b8-409b-9c93-c4d6f487d893.png)
![HT-Content page - Authenticated - Desktop](https://user-images.githubusercontent.com/68560244/125825281-139f2306-6ad3-44d2-bcd5-1ec6c5c598ac.png)
![Harassment tool - Introduction - Unauthenticated - Mobile](https://user-images.githubusercontent.com/68560244/125830528-fa3ecffb-af11-4b9b-a918-5dde19ce5e5b.png)
![Harassment tool - Introduction - Unauthenticated -  Desktop](https://user-images.githubusercontent.com/68560244/125825296-4c1ac19e-38c4-4927-88c6-055052f5c45d.png)
![Harassment tool - Introduction - Authenticated - Mobile](https://user-images.githubusercontent.com/68560244/125830159-2330a7eb-822a-4518-b34b-d271c7dc76a9.png)
![Harassment tool - Introduction - Authenticated - Desktop](https://user-images.githubusercontent.com/68560244/125825312-6438c6af-9b9b-4c9a-b3b5-7e2cb5afb019.png)

**Comment by callen2563** [comment]
Here is the updated HRT content mock up with new template. I posted this on the content ticket as this page has rough copy placeholders. 
![HT-Content page - Unauthenticated - Desktop](https://user-images.githubusercontent.com/68560244/127703806-80a0718f-6448-4add-b112-418236f8fcf0.png)

**Comment by callen2563** [comment]
Both mobile and desktop first drafts have been mocked up but will be continuing edits during collaboration with content.

[HRT mobile and desktop designs](https://sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

**Comment by brianalloyd** [comment]
Design elements are completed for the initial draft, follow up in second draft ticket. Validated and closing in support.
