### ISSUE TITLE
Send the "will upload documentation" property with the form data on 10-10CG submission

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26482]
## Epic User Story

**As a** VA Employee, **I want to** know whether the caregiver is planning to send PoA documents with their submission in order to ____

The online 10-10cg form asks the applicant if they want to upload documentation that shows their legal representation of the Veteran.

We need to pass the user's selection to the API so it can be sent to CARMA along with the rest of the form data.

![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/0a22a72e-1562-4f32-bc94-0306009f6771)

There are currently 3 possible responses:
* Yes. I want to upload my documents now
* Yes. But I'll provide my documents later
* No. I don't have this document.

These values are currently only used for workflow logic in the front end. We want to change that so that the selected value can be passed to CARMA.

## Expected Behavior

The users selection is passed to CARMA with the submission data

## Acceptance Criteria

- [ ] Schema is updated
- [ ] Frontend is updated to use the updated schema and pass the selection to the backend
- [ ] Backend is updated to use the updated schema and send to CARMA with submission

**Comment by SKasimow** [comment]
N/A. 

Closing this since option to "upload later" has been removed
