### ISSUE TITLE
Conduct Usability for Dependency Verification

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26481]
### Background
The 21-686c/674 is ready for usability testing. Sessions will be scheduled over the course of the coming weeks.

Resources:
- [Usability research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/research-design/usability-testing-1/dependent-verifiy-usability-1-research-plan.md)
- [Usability conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/research-design/usability-testing-1/dependent-verifiy-usability-1-convo-guide.md)

### Tasks
- [x] Pilot
- [x] Kick-off usability study
- [x] Get usability sessions scheduled
- [ ] Conduct usability sessions
- [ ] Capture findings in usability table (Stretch: separate ticket)
- [ ] Topline summary (Stretch: separate ticket)

### Acceptance 
- [x] Begin usability sessions

**Comment by candy-gcio** [comment]
Sent to Lauren for recruiting on Thurs, 8/12

**Comment by candy-gcio** [comment]
Four of eight scheduled tests were completed by end of sprint 54. The four more are scheduled to be completed by Friday, August 27.
