### ISSUE TITLE
Walkthrough Final Fit and Finish for Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26490]
## Background
Now that we have a cadence of maintenance for our portfolio, we need to do some discovery to see what changes need to be implemented to update our features.

## Considerations
~~"21-527EZ pension benefits form"  <- not stand alone, embedded into 686~~
"Rated Disabilities" <- view task, no form
"View Dependents" <- view task, no form
"686C-674"
~~"View your representative" <- view task, no form~~
~~"21-22 Appoint Veteran Service Officer as Representative" <- VA Form 21-22 is for VSOs, VA Form 21-22a is for individual representatives~~
"28-1900 Veteran Readiness"
"Apply for Personalized Career Planning and Guidance with VA Form 28-8832"
"View Payments" <- view task, no form
~~"Apply for Certificate of Eligibility" <- VA Form 26-1880~~

## Tasks
- [x] Establish the Design standards we need to operate in
- [x] Document changes for the feature

## Acceptance Criteria
- [x] A changelog of recommended changes has been listed in GH

**Comment by candy-gcio** [comment]
@sporeboy , Do you have mockups/prototypes that are updated past what is in development for these?
 - 686C-674 
 - 28-1900 Veteran Readiness
 - Apply for Personalized Career Planning and Guidance with VA Form 28-8832


I think I have the latest versions of the others. I'll add the links here, just in case...
- [Rated Disabilities](https://www.sketch.com/s/9a70f4c7-68f8-4998-bfee-2fdbb709cfb2)
 - [View Payments](https://www.sketch.com/s/2cbfbba2-b8c6-490a-8f25-240877a7786b)
 - [View Dependents](https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/b0af32a2-f1d7-4aa6-9aff-959a8ee1ae2b)

**Comment by sporeboy** [comment]
I think we managed to stay up to date on 686. For the others, I'm going to drop the links below. I'll need to check against what's in staging to be sure:

- [CH 31 28-1900](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/130773489)
- [CH36 28-8832](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/139282245)

**Comment by candy-gcio** [comment]
- [View Payments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/research-design/tool-design-update-punch-list.md)
- [Rated Disabilities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/research-design/tool-design-update-punch-list.md)
 - [View Dependents and 686c](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/tool-update-design.md)
 - [Ch 31/28-1900](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/research-design/ch31-update-list.md)
 - [Ch 36/28-8832](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/Ch36-update-list.md)
