### ISSUE TITLE
Create ITRP for Creating a Note

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26499]
## Background
We need to make an ITRP request for a BGS service so that we can hook up our claim label notes to their respective workflows.

## Context
After registering with MAX.gov and finding the correct ticket request service (I think), this is the result: https://vajira.max.gov/servicedesk/customer/portal/12/CMDMRP-988

## Tasks
- [x] Register for MAX.gov
- [x] Locate the correct ticket request page
- [x] Complete the instructions and request

## Acceptance Criteria
- [x] A request has been submitted
