### ISSUE TITLE
Consider New 1900 PDF

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26498]
## Backlog
We found that the 1900 form had a missing char box for the VA file number, we need to address this.

## Considerations
We should only print the VA file number if it differs from the SSN with some adjusted logic

## Tasks
- [x] Change the VAFileNumber limit from 8 to 9
- [ ] Add logic so that the form only includes the VAFileNumber if different from the SSN.

## Acceptance Criteria
- [ ] The VA file number is only added if different from SSN and then populated on the amendment page.

**Comment by RudyOnRails** [comment]
Am I correct when I say that the VA file number should only show on form 1900 when different from SSN, and when it does show, add an extra char box?
