### ISSUE TITLE
Analytics on our Analytics - Domo Engagement

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#26507]
## Issue Description
How might we track how VFS teams are using our dashboards in Domo?

---
## Tasks
- [x] Lauren & Chloe to determine how people are being grouped in Domo
- [x] Configure Domo groups to match the VFS roster, OR using Join to update the groups
- [x] Create charts in Domo

## Acceptance Criteria
Automatically track the following:
- [x] 1. Increase avg. weekly % of VFS teams using Domo
- [x] 2. Standardized dashboard usage vs. custom dashboard usage
- [x] 3. Link clicks to documentation, broken down
- [x] 4. Recurring users
- [x] 5. % of clicks into card details (depth of use)

**Comment by chloedotbrown** [comment]
Created an ETL that generates a [new datasource](https://va-gov.domo.com/datasources/6ca10d20-48d8-4b33-b2ca-c60174d0c901/details/overview) based on Domo's Activity Log, People, and Group reports, as well as the VFS Team Roster and an object table with everything on the Forms dashboard labeled. I'm holding off adding Content and Search, in case we end up adding/swapping any cards and we need object IDs to be stable. But this will allow us to slice up view data by VFS teams vs. other uses and Standardized dashboards vs. other Domo content. 

Small note that in current data structure, it's especially important to count unique users, since POs will have rows for each of their products. If this ends up causing issues in the actual build, I'll update dataflow accordingly.

In the meantime, [working spreadsheet](https://docs.google.com/spreadsheets/d/19cS2nrii95YcMmGcsPQj0RSeSu3Xg6t2ri6KLfJkahw/edit#gid=0) with more notes on KPIs and datasources has been shared with all Analytics team members.

**Comment by chloedotbrown** [comment]
Adding @JasonTheBearded to this ticket for situational awareness about the ETL portion of this work. 

I brought this issue up in our data chat this morning, but documenting it here for better traceability! A downside with the current dataflow is that Domo does not make it easy to append ETLs (instead of replacing full datasources each time they run). This may become an issue for us as people cycle on/off VFS teams, as that person's entire viewing history will be categorized with by their current status, not the one they held at the time. For example, if a person on a VFS team views the dashboard 20x in July _(sidenote: don't I wish!)_, but in August they're moved off to another contract, then when we look back at our July 2021 data, it will appear as though those 20 views came from non-VFS viewers. 

I'm not sure how big of an issue this will be for us – in part, because we just don't know how people will or won't use these dashboards. But it does look like one workaround for this _might_ be to set up the ETL as a [Recursive Data Flow](https://domohelp.domo.com/hc/en-us/articles/360057087393-Creating-a-Recursive-Snapshot-DataFlow-in-Magic-ETL-v2-Beta-). I haven't had time to dig into this today and will probably focus on the mockups instead tomorrow, but will pick back up and investigate whether this would be any help for us once I'm back early next week, unless anyone's able to take a peak beforehand!

**Comment by joanneesteban** [comment]
Hi! Question for y'all: we'll have data issues around folks leaving VFS or changing teams?

**Comment by joanneesteban** [comment]
Head's up, @chloedotbrown - everyone on the [VSP Roster](https://docs.google.com/presentation/d/1ktf_Gx8UJGW9sJiIgyNCWuCe16zMkjjlnZ1mXEEZQFQ/edit#slide=id.g5b254597e5_6_40) should be filtered out from our AooA. The most important folks to filter out are members of our own team, including `VA.gov Platform Analytics & Insights` & `Participant Tester`.

**Comment by chloedotbrown** [comment]
Great! I'm already pulling out activity from our team, but I'll add the `Participant Tester` as well. As for the rest of the Platform crew, using Domo groups with a VSP in the name seems like the easiest approach, so long as they're accurate. 

@laurensimpson14 this may be a question for you! Are these groups pretty actively maintained?

![VSP Domo Groups](https://user-images.githubusercontent.com/45518242/125655159-a98c04a8-771b-439a-a8a5-843128396ad2.png)

**Comment by chloedotbrown** [comment]
Documenting issue - GCIO email addresses have been changed in Domo but **not** on the VFS roster. This means that the join is failing and GCIO VFS members were mis-categorized as `Other user` in yesterday's append - and will be in all data moving forward until issue is corrected.

Here's my plan to address the incorrect VFS data from 7/19 and prevent more mis-categorized data from coming in:

1. Look up new GCIO emails in Domo to update VFS roster (59 affected).
2. Disconnect loop appending new data and re-run historical base set. So long as no Domo power users have changed VFS teams in the past week, this really shouldn't negatively impact our data quality.
3. Add recursive step back in, double check tomorrow to make sure update completed correctly.

![AooA dataflow GCIO emails](https://user-images.githubusercontent.com/45518242/126368435-a4495436-b4ae-4fce-8671-6673c93890e2.png)

**Comment by chloedotbrown** [comment]
Dashboard card creation and layout complete. View [here](https://va-gov.domo.com/page/514439234).

**Comment by chloedotbrown** [comment]
Closing ticket.
