### ISSUE TITLE
Analytics on our Analytics - Discovery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#26503]
## Issue Description
How might we track usage of our Domo dashboards?

---
## Tasks
- [x] Test to see if we can link external images
If yes, 
- [x] Build URLs
- [ ] Determine meta data to pass in
- [ ] Determine how

## Acceptance Criteria
- [ ] We understand if and how we can link external images to Domo

**Comment by bsmartin-ep** [comment]
Unfortunately this is a bit of a dead end.  I was able to link to an external gif and believe I would be able to [generate a GA gif](https://developers.google.com/analytics/resources/concepts/gaConceptsTrackingOverview#howAnalyticsGetsData).  

However I am unable to find a way to generate a consistent user ID or extract other information necessary to track interactions.  The filters are also inaccessible.
