### ISSUE TITLE
Analytics on our Analytics - Velocity

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#26504]
## Issue Description
Track how long it takes us to create a KPI dashboard: from when a VFS team requests their product to be added to a standardized KPI dashboard to when we close out the request.

---
## Tasks
- [ ] Determine if we will be able to automatically track this data, and which method.
- [ ] If we use the public BigQuery dataset, determine the cheapest way to pull the data
- [ ] Build the connector, dataset, & chart in Domo

## Acceptance Criteria
- [ ] Be able to automatically track this KR, `Decrease KPI dashboard delivery to VFS teams from 4 sprints to <=4 business days.`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@JasonTheBearded another option might be using the Github actions that the Testing Tools team did for the Accessibility Dashboard? It looks like the issues also pull `created at` and `closed at`.

**Comment by JasonTheBearded** [comment]
Focus on github issues with the labels: `kpi-dashboards`, `gtm`, `analytics-requests`, and `analytics-insights`

**Comment by JasonTheBearded** [comment]
@joanneesteban what would the preferred lookback period be for github issues?

**Comment by joanneesteban** [comment]
@JasonTheBearded Is it possible to start from Jan 2020?

**Comment by JasonTheBearded** [comment]
There is no Epic column in the Github API. Testing tools team will be adding Milestone to job

**Comment by JasonTheBearded** [comment]
Velocity query built and set up as DOMO data source.

**Comment by JasonTheBearded** [comment]
Card created and added to dashboard. Closing ticket
