### ISSUE TITLE
Analytics on our Analytics - Documentation Use

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#26512]
## Issue Description
How might we see if folks are using our dashboarding documentation?

---
## Tasks
- [ ] Discovery into where to pull the data from & where to put the data into
- [ ] Pull the data into Domo
- [ ] Create dataset & chart in Domo

## Acceptance Criteria
- [ ] Automatically track: Visits and visitors to dashboarding documentation on the Platform site`

From this GA property: https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w224573768p240292331/explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=100/

**Comment by joanneesteban** [comment]
@JasonTheBearded @bsmartin-ep these are the current Documentation URLs we want to look at:

Priorities for this initiative
**1. [How to use this dashboard](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html)
2. [Forms KPIs data dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Data-dictionary:-VA.gov-Forms-KPIs.1549009005.html)**
We'll want to track these too, but it's less urgent:
3. [KPI dashboard readme](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/KPI-Dashboards-Readme.1657995529.html)
4. [Customer support guidelines](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html)
5. [Analytics & insights home page](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-and-insights.1256063000.html)
6. [Announcement](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-support-announcement---June-2021.1586823316.html)

We'll also be adding the Search & Content KPI data dictionaries, which aren't on the public website yet. 

If we can, priority metrics:
1. Page views
--
2. Link clicks
3. Scroll depth
4. Page referrals (where did folks come from before they found the page)
5. % of analytics page views vs. the whole platform website

Please work with Chloe on connecting the data to Domo for a visualization.

**Comment by JasonTheBearded** [comment]
@joanneesteban @bsmartin-ep looking through the GA data we are tracking in BigQuery on the documentation site, I'm only seeing Scroll Depth as a tracked event. Do we have tracking set up for link clicks?

**Comment by bsmartin-ep** [comment]
@JasonTheBearded -

Not on depo-platform-documentation.scrollhelp.site.  Just pageviews.  Are there some interactions you need to have tracked? 

The old .github.io site has global link tracking (under category _Interactions_).

**Comment by JasonTheBearded** [comment]
@bsmartin-ep Yeah, for our AooA we need to have link clicks and scroll depth tracked for the analytics pages

**Comment by joanneesteban** [comment]
For our AooA, link clicks is prioritized over scroll depth. Scroll depth is a nice to have. If tracking scroll depth isn't dynamic, let's deprioritize that.

**Comment by bsmartin-ep** [comment]
@joanneesteban / @JasonTheBearded -

GTM integration for Confluence is pretty basic - just specify a GTM id and... that's it.

This might be the rare case where scraping interactions in GTM is our best bet.  Thoughts on a generic global link click event, Jason?

```js
{
     event: 'link_click',
     link_text: "Infrastructure",
     link_url: "https://depo-platform-documentation.scrollhelp.site/infrastructure/",
     link_classes: "cell tile tile--spaces tile--spacious medium-4 tile--text-center"
}
```

![image](https://user-images.githubusercontent.com/62304138/124677375-4e945b80-de8e-11eb-9a7c-1a189abb2e67.png)

**Comment by joanneesteban** [comment]
Global link clicks should work! Having the different classes is also some good metadata for us.

**Comment by bsmartin-ep** [comment]
@joanneesteban / @JasonTheBearded -

OK cool.

- Global link tracking has been added to `depo-platform-documentation.scrollhelp.site`
- `depo-platform-documentation.scrollhelp.site` has been added to scroll tracking

### New custom dimensions on documentation GA property:

Name | Index | Scope
-- | -- | --
Click Text | 1 | Hit
Click URL | 2 | Hit
Click Classes | 3 | Hit
Click ID | 4 | Hit

</div><br /></b>

**Comment by JasonTheBearded** [comment]
Thanks @bsmartin-ep!

I'll also note that I created an initial version of the query and created a DOMO dataset for this. I'll update an needed once the new event tracking starts showing up in BQ.

**Comment by bsmartin-ep** [comment]
Apologies @JasonTheBearded -

Just noticed these are logging with an event label of `gtm.linkClick` due to the scraping triggers.  I updated to `link_click`.

**Comment by joanneesteban** [comment]
Question for Platform Website tracking. This **does not** need to be added to the dashboard:

- Is there a way to see the search terms & frequency of search terms?

**Comment by JasonTheBearded** [comment]
@joanneesteban We could potentially extract the search term from the URL since the search results page is tracked. But I think it would only be available for all Platform website tracking.

What do you think @bsmartin-ep?

**Comment by JasonTheBearded** [comment]
All cards created for documentation usage

**Comment by joanneesteban** [comment]
@JasonTheBearded @bsmartin-ep Can get search queries for the whole Platform Website? If not, we're good to close this ticket.

**Comment by JasonTheBearded** [comment]
@bsmartin-ep I don't think there's any tracking for search events on the platform website right?

**Comment by bsmartin-ep** [comment]
There is now @JasonTheBearded!  I just added the querystring parameter `q` to the View settings (Both the All view and the Scrollhelp view), so we should start to see (rudimentary) site search metrics shortly.

**Comment by joanneesteban** [comment]
@bsmartin-ep updates:

@joanneesteban to make separate tickets for these:
- Site search events are flowing into BigQuery & GA. May need to update the data source, but the data is there for data visualization.
- We can probably mock something up to set a user-scoped custom dimension or cookie to figure out how to remove ourselves from tracking. This would need discovery.
- Domo is not getting tracked on the navigation

Closing this ticket!
