### ISSUE TITLE
Discovery: Sidekiq job timeout 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#26521]
## Issue Description
We may want to consider timing out jobs after a preset time (e.g. 1 hour) with the option to increase this per job class. We've seen that some jobs are hanging with one example of jobs running for 20+ hours

## Tasks
- [x] Investigate job timeouts and if we can reliably time out jobs
- [x] Read [Add Timeouts to Everything](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#add-timeouts-to-everything) from Sidekiq's Wiki.
- [x] Spin up one or more implementation tickets if necessary

**Comment by cbtkc** [comment]
Looking into accessing loki logs today so I can see which jobs are long running and why, and devise a plan to deal with those long running jobs.

**Comment by cbtkc** [comment]
Created a [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/8057) to add a timeout for queries running on postgres.

**Comment by LindseySaari** [comment]
There is a current incident where Central Mail seems to be down. Thread [here](https://dsva.slack.com/archives/CBU0KDSB1/p1635788894099800). VBADocuments::UploadProcessor keeps failing with a `Common::Exceptions::BadGateway: Bad Gateway` error. We should loop back to this issue.
