### ISSUE TITLE
Focus is going to top recommendations for you. 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26534]
##  Description

defect-3 When searching from the search results page itself, focus goes to "Our top recommendations for you"
"Showing 1-10..." is announced using aria-live which is inconsistent with other search experiences that announce the number of results by sending focus to "Showing 1-10..."

## Background/Context
GH [#26416](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26416)

## Tasks

- [x] update screen reader focus to show 1-10

## Acceptance Criteria
- [x] Tier 3 (No Socks validation necessary)
- [ ] Respond to GH [#26416](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26416) to make Josh aware and to validate.
