### ISSUE TITLE
[VAMC] Resolve changes to Playbooks in VISNs and prepare them for csv file preparation [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26548]
## Story
As an editor/web maintainer and data migrator, I need to have health services match CMS systems so I can better understand the cross over and how best to load the data quickly into CMS.

## Goal
update system health service and facility taxonomy to match changes in taxonomy and prepare files to be loaded using .csv file format

## Tasks
Update Health service playbooks and create .csv file prep document for both System and Facility health services
- [x] Playbook updated with new Taxonomy
- [x] System and Facility Health Service for each system in VISN created.
- [x] Consolidated System and Facility tabs created

## Acceptance criteria
- [x] Excel document is created and shared in team repository 
- [x] Playbook in team repository is updated and ready for distribution to field/stakeholders.

**Comment by bcastoe** [comment]
#26548 Resolve changes to Playbooks in VISNs and prepare them for csv file preparation [BA] - completed and moved to Validate.
    1) All Playbooks for VISN 15, 9, 1 have been updated with new Taxonomy
    2) Created individual excel spreadsheet of VISN 15, VISN 9, and VISN 1 regarding all System and Facility Health Service for each VISN
         -  removed all N/A's entries
         -  removed all COVID entries
    3)  Created consolidated excel spreadsheet of VISN 15, 9, 1 for System and Facility
