### ISSUE TITLE
FSR - Unauthenticated Experience

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#26542]
## High Level User Story/ies

As a veteran who has debt, i want the ability to submit an FSR for myself without logging into my account on debt portal. 

## Hypothesis or Bet
**If** _we allow veterans to submit FSRs without logging in_ **then** _we expect more FSR submissions_.

## OKR
_If veterans can submit FSRs regardless if they can log into their account, form submission workflow is simplified and form filling time will be reduced._

## Definition of done
- [ ] Veterans can successfully create and submit a new FSR for themselves regardless if they log into their account or not. 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by HeatherRienks** [comment]
Per conversation with @denisecoveyduc and @Tom-Davis, Denise will follow up on this issue.

**Comment by denisecoveyduc** [comment]
Closing this one out. There are no plans to provide Veterans with the ability to submit an FSR or VA Form 5655 without logging into their va.gov account at this time. Should the become something we explore in the future we will better define the initiative are open a new Epic. 
FYSA: @HeatherRienks @Tom-Davis
