### ISSUE TITLE
Update Dependency Verification PDF

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#26540]
## Background
The Dependency Verification (21-0538) PDF needs to be updated because currently the wrong radio button is selected.  Also, the Veteran SSN needs to be populated at the top of the second page.

![Screen Shot 2021-06-23 at 2.53.00 PM.png](https://images.zenhubusercontent.com/5d4b154f046a317fe3b7760e/319eacb0-a52e-4147-9154-01103f01e223)

## Tasks
- [x] Change the value of the status question radio button on the PDF
- [x] Populate the SSN at the top of the second page of the PDF
- [x] Update specs

## Acceptance Criteria
- [x] A PR has been submitted for merging
