### ISSUE TITLE
Create a Slack Integration that Alerts When E2E Tests Fail in Master

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26559]
# Description
Notify #vsp-testing-tools-team when the Cypress tests fail on a `vets-website` merge to master event.

## Tasks
- [x] Integrate GHA workflow with Slack
- [x] Send failure messages to Slack a newly created notification channel
- [x] Test the messages and refine

**Comment by CBonade** [comment]
This has been merged to master and should start reporting failed tests effective immediately.  The channel that was set up is called `#gha-test-status` and is currently a public channel that anyone in the organization can join.  The message includes a link to the failed run for ease of use.

**Comment by pjhill** [comment]
It's alive! Any modifications to the current behavior if there are any can be worked in a post-MVP ticket.
