### ISSUE TITLE
Design intent [DGIB - My Education Benefits]

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#26556]
## Steps to complete Design Intent Collaboration
- [X] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [X] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No

## Artifacts
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Product%20Outline.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/MVP%20Site%20Map%20:%20Flow.png
- We have gone past wireframes at this point, but we are still iterating on content and UI elements (leveraging the existing design system patterns). Designs: https://share.goabstract.com/9c202648-de36-45fb-abfc-ab8ec03df2eb
- Any other artifacts you have so far

## Meeting attendees from requesting team
- Designer(s) (required): Russell Lyons, Leelah Holmes, Jacob Buller, Mark Meardon, Audra Ayotte, Miya Furukawa, Isabel Herrick, Alexander Ferzola
- Product Manager (required): Shamik Desai
- OCTO-DE Design Lead (required): Ryan Thurlwell
- OCTO-DE Product Lead (recommended): name
- VFS content, IA, accessibility, and QA specialists (if applicable): name(s)
- Other stakeholders you want to invite (if applicable): Cesar Santiago, Tammy Hurley

### What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
**Date/time:**
7/1 2-2:30
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility, and IA only. You won't receive feedback from content and QA, as it's too early in the development process.

Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@rlyons89 I am having a hard time finding contact on Jacob Buller and Mark Meardon. Can you please let me know their email so I can invite them to the meeting?

**Comment by allison0034** [comment]
This has been scheduled for 7/1 2-2:30pm ET

**Comment by rlyons89** [comment]
jacob.l.buller@accenturefederal.com, mark.meardon@accenturefederal.com

**Comment by rroueche** [comment]
Thank you @rlyons89 for sharing your work with us yesterday! We appreciate your clear reference to and usage of the design system components in your mocks - the look of your work is very much in line with VA.gov which is great to see!

Here's reiteration / summary of some of the feedback we discussed in the Design Intent (cc'ing @mattpointzxer0 so we can have conversations with the Education POs if needed) - this feedback is more around user flow / feature requirements than visual design:

1. There's an existing pattern across all VA.gov forms for unauthenticated vs authenticated user interaction with the form. The pattern enables users to start unauthenticated, then sign in to "Save in Progress" and "Pre-fill" their data if they'd like. The Save in Progress feature also enables the in-progress form to show up on the user's Dashboard. You'll need to ensure your iteration to the 1990 plays into those existing features -- which may mean adjusting the unauthenticated experience to contain the same fields as the authenticated so when a user converts to authenticated part-way through, it can continue seamlessly. Or some other solution design that achieves the same end!

2. It's great that you want to leverage some dashboarding and document download features as a part of the overall end-to-end service design of this flow. There are existing features on VA.gov for those experiences, so instead of creating new ones, please iterate on the existing features to add your functionality in -- the features are Dashboard / Profile (your point of contact for coordinating this is @KevinMHoffmanUSDS ), and Download VA Letters (your point of contact for coordinating this is @mattpointzxer0 ).

I think that's it! Thank you again for your work on this, we're excited to see the 1990 evolve, especially with auto-establishment becoming a potential reality!

**Comment by KevinMHoffmanUSDS** [comment]
Hello, @rlyons89! Hope this finds you well. 

I'm happy to meet with you to discuss modules/ideas for MyVA or VA.gov profile. Let's get thirty minutes on the calendar soon - my availability is in my Slack profile. Please include @ajakabcin as required, as well as @andaleliz, @tressaellen, @erikphansen, @tskinn, and @lihanli as optional on that meeting.

**Comment by fuguesociety** [comment]
Hello, am looking to collaborate here but am fairly new to Linux. I am interested in Carl Sagan, and am willing to devote time resources.
