### ISSUE TITLE
Review COVID-19 pages for outdated, inaccurate content

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26552]
## Issue Description
Now that our COVID-19 pages have been live for so long and rules have changed so much over the pandemic, we need to do a review of the content to ensure that there is nothing outdated or unnecessary and inaccurate. This needs to be done to the vaccine mini hub, the FAQs page and the chatbot.

## Tasks
- [x] Review vaccine mini hub (Randi/Selina)
- [x] Review COVID FAQs (Randi/Selina)
- [ ] Review chatbot (Randi/Selina)
- [ ] Review content that needs changing (Danielle)
- [ ] Make updates to any pages (Selina/Randi)
- [ ] Review and publish [Randi/Danielle]

## Acceptance Criteria
- [ ] Our COVID-19 pages are up-to-date with no unnecessary or inaccurate information.

**Comment by RLHecht** [comment]
Noes on COVID FAQs page FYSA @DanielleThierryUSDSVA :

- We say test results take 3 to 4 days. Still true? https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#if-i-got-a-covid-19-test-at-va-36871
- In the accordion [Is my health facility open for in-person care?](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#is-my-va-health-facility-open-36877) we say "As the number of COVID cases rise..."  Seems like we should change this wording.
- In the accordion [How can I schedule a VA health appointment](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#how-can-i-schedule-a-va-health-36883) we say "if you or VA canceled an appointment due to COVID-19..." which I don't think would be the case anymore. My suggestion is just deleting that sentence.
- In the accordion [What should I do if I have a community care appointment...?](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#what-should-i-do-if-i-have-a-c-36884) we say "If your provider cancels your appointment" which is probably not an issue anymore. Remove this section?
- Should we remove the accordion [What if VA canceled my appointment or procedure?](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#what-if-va-canceled-my-appoint-36885)

**Comment by RLHecht** [comment]
Notes on vaccine mini-hub. FYSA @DanielleThierryUSDSVA :

- In the accordion "Is there a cure or any FDA-approved treatments..." we say the FDA recently approved remdesivir. Should we delete the word "recently"?
- In the accordion "Can I change my mind after scheduling a time to get a vaccine" we say there is currently a limited supply of vaccines. Is that still true for VA facilities?

**Comment by RLHecht** [comment]
This is an old ticket. We have newer tickets to address these. Closing.
