### ISSUE TITLE
[DESIGN] My VA: Create mockups for elevating action items

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#26569]
## Background
As part of long-term research and continued improvements to My VA post-launch we need to do some plan research and create mockups to learn how we can better elevate action items in the dashboard.

## Tasks
- [x] Create more polished mockups
- [x] Review with team/Kevin/Ryan
- [ ] Clean up mockups to be used for testing

**Comment by tressaellen** [comment]
@KevinMHoffmanUSDS @rtwell @sshein just FYI-I'm linking everything here related to action items work so it's easy to find. 

- [Mural board with all iterations/feedback](https://app.mural.co/t/vsa8243/m/vsa8243/1623308977321/dfc68dee89d6073c960339da9d9ebd977caebca1)
- [Comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/action-items-comparative%20analysis.md)
- [Overall/MVP action items spreadsheet](https://docs.google.com/spreadsheets/d/1sEkNQvcPNhQ9R-CC-SRdrQiF4DNeix6HDC-WvWRWByo/edit#gid=724842135) - based off feedback from Kevin I will be adding VA notifications from VA notify. I'll include them in this spreadsheet. 
- [Potential future action items ](https://docs.google.com/spreadsheets/d/1724fvSyOtkoSvCSFOYiWBWZbG8kM-w3yElorKGDS0FQ/edit#gid=871749236)
- [My informal plan/questions/thoughts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/action-items-plan-and-questions-tressa.md)

**Comment by tressaellen** [comment]
@KevinMHoffmanUSDS @ajakabcin 

Here's a more cleaned up version for the My VA action items work. For the actual alerts, I tried to follow the cards in the design system - I don't think we're quite there yet. But I'd love to review what I have so far and refine from there. :) 

**Also - do either of you know where I could find some real content that VA Notify uses for emails/texts?** It seems like we should be aligned there.

If you could leave any thoughts/comments in this Mural board, it'll be easier see the screens and keep all the feedback together. 

![My VA Alerts 1 - Desktop.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/ed6e29dc-ef53-45dd-b2cb-240e70dc758c)
![My VA Alerts 1 - Mobile.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/d7a9cd2c-3706-4113-bede-da496c4eaa78)

![View All Alerts 1 - Desktop.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/a3b3f5bc-3735-4ed2-b2b6-9f30add310e8)![View All Alerts 1 - Mobile.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b4224af4-03d1-4c79-82ea-796a1d7693db)

**Comment by ajakabcin** [comment]
@tressaellen I do not but we can ask them. I'll follow up in slack. 

Looks great otherwise

**Comment by ajakabcin** [comment]
Hey @tressaellen! I checked with @miabecker from VA Notify and she said it would be best to reach out to her directly (slack is fine) to help point us in the right direction. I can start up that thread in a bit!

**Comment by tressaellen** [comment]
All mockups so far can be seen in [this Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1623308977321/dfc68dee89d6073c960339da9d9ebd977caebca1). I will be reviewing these mocks tomorrow with a larger group and all feedback will be tracked in #27270
