### ISSUE TITLE
[Content] Revise the Knowledge Base - review "How to" Guide, changes for System health and facility health service KB articles [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26564]
## Story
As a web maintainer/CMS editor, I need to have a knowledge base of "How to" instructions, so I can find answers to my question of how to manage, maintain, and update my system website pages.

## Goal
- Improve the editorial experience for the web maintainer to find their own answers and "How to" instructions.

## Task
Review rewrite of KB articles for System health service and facility health service "How To":
- [x] Provide copy editing, cross check and recommendations to word documents for each of the "How To" articles.  Track changes in word document.
- [x] How to add new VAMC system health services
- [x] How to add new VAMC Facility health services
- [x] How to edit existing VAMC facility health services
- [x] How to remove an existing VAMC facility health services

## Acceptance Criteria
- [ ] Artifact ( word document) showing recommended changes and highlighted changes.
- [ ] Any additional editorial recommendations for questions or directions to the editorial experience.
