### ISSUE TITLE
Remove IP Address from Click Tracking

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26561]
##  Description
As a result of the privacy and security review we have determined that we will remove the IP address from click tracking. Search.gov does not require them to be collected 

## Background/Context
Privacy & Security Request [#293](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/293)

## Acceptance Criteria
- [x] Remove IP address from tracking
- [x] Tier 3 (No Socks validation necessary)
- [x] Comment on #293 to inform Privacy & Security team that this has been removed and is no longer bing collected from users.

**Comment by srsuddath** [comment]
PR has been merged, this issue is good to close!
https://github.com/department-of-veterans-affairs/vets-api/pull/7419
