### ISSUE TITLE
R&S Updates: What if I'm having trouble opening a PDF?

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26573]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the live page. 

REVISE THE H1:

**How to download and open a PDF document**

REVISE THE INTRO:

If you're having trouble downloading and opening a form or other PDF document, follow the steps on this page. You'll need to have the latest version of Adobe Acrobat Reader installed. You can download it now for free.

REVISE THE CTA BUTTON:

Label: Download Acrobat Reader for free

Link: https://get.adobe.com/reader/

REVISE STEP 5 OF THE SUBWAY MAP SO THAT THE LINK IS ON ITS OWN LINE:
If you're still having trouble, you may have an older version of Adobe Acrobat Reader. You'll need to install the latest version. It's free.

Download the latest version of Adobe Acrobat Reader
Link: https://get.adobe.com/reader/

### Tasks

- [x] SC to make change in Drupal (Laura)

- [x] DEPO to approve change (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [ ]  Updated page is live

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 I updated the above CTA to include "for" before "free"

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 In looking at the original IRIS FAQs on this topic, I think we should use "form" rather than "document" in the H1. I'd also like to make it clear in the intro that the use case Veterans have trouble with is opening PDFs in their browser. So we're saying, try downloading the PDF instead. I like that you incorporated the language "having trouble" from the existing H1, since the H1 is changing and won't have that. Would you make these edits? Then we can iterate some more if we need to!:

**How to download and open a PDF form**
If you're having trouble opening a PDF form in your browser, try downloading it instead to your computer or other device. Then open the PDF in Adobe Acrobat Reader and fill out the form. You'll need to have the latest version of Adobe Acrobat Reader installed. 

Change button to this: Download Adobe Acrobat Reader for free

1. Download the PDF form to your computer or other device
2. [no changes to this existing step]
3. Choose Open from the File menu.
4. [no changes to this existing step]
5. If you're still having trouble, you may have an older version of Adobe Acrobat Reader. 
LINK: Download the latest version of Acrobat Reader for free

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Would you put in a redirect request to Mikki since the H1 and URL will change? There's a template for this type of request when you open the ticket.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- I didn't flag Randi on this yet, as it sounded like you want to take another look. Here's the preview link:  http://preview-prod.vfs.va.gov/preview?nodeId=8684

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO and @lwalsh617 -- Sorry to jump in on this ticket so late in the game, but I was on PTO last week. One important thing to be aware of is that some PDFs will open in the browser, and appear perfectly normal, but unbeknownst to the user, the digital signature field is missing because modern browsers don't support Adobe's Dynamic XFA technology.  The safest bet is for users to always download the PDF and fill it in using Adobe Acrobat Reader.  That is the guidance we were given by one of the VA's Adobe Reps.

**Comment by lwalsh617** [comment]
@MarciMcGuireGCIO - Thank you for your feedback.
@bethpottsVADEPO - Let me know what you want to do about Marci's comment above. Separate note: I opened the redirect ticket you requested. It's ticket [26704](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26704).

**Comment by bethpottsVADEPO** [comment]
This is very helpful, @MarciMcGuireGCIO. Thank you for the additional info on this. I made some further revisions to the article.

**Comment by cindymerrill** [comment]
@bethpotts @MarciMcGuireGCIO Not sure the intro should say "If you're having trouble downloading and opening a form or other PDF document" because the link on the Find a Form page is to _advice on how to do it correctly_, not to address a problem that happened.

**Comment by bethpottsVADEPO** [comment]
@cindymerrill We're still revising/iterating--I'll be sure to share the final version that we plan to publish. This article is addressing both problems actually. It wasn't initially created just for the current use case.

**Comment by cindymerrill** [comment]
Yeah, makes sense. I thought of that after I posted.

**Comment by bethpottsVADEPO** [comment]
@cindymerrill @MarciMcGuireGCIO for awareness, the article has been updated--changes are live.

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO thank you!

**Comment by cindymerrill** [comment]
Here's my initial thought on additional instructions to add to step #15442 @bethpottsVADEPO @MarciMcGuireGCIO 
 
_If you try the Download form link on the Find a Form page and see the form in your browser, look for the Download button in your browser window, which is usually in the top right corner_ .

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill that's a good initial message.  Another one could be:

_If you try the Download form link on the Find a Form page and see a "Please Wait" error message, look for the Download button in your browser window, which is usually in the top right corner.  Download the form to your device and then open it with Adobe Reader before filling it out._

@bethpottsVADEPO @cindymerrill -  I tested the NVDA screen reader for Windows with form 20-0968.  After downloading the PDF (which is a "Please Wait" error in this case), it reads out the URL of the PDF then says "embedded object not available".  If the user is inclined to tab through the toolbar, it will say that there is a download button.    Unfortunately, that "embedded object not available" message is probably going to make them think that nothing downloaded.

**Comment by MarciMcGuireGCIO** [comment]
@joshkimux - I know you're super busy, but if you get a couple minutes, could I trouble you to visit https://www.va.gov/find-forms/?q=20-0968 with a screen reader on Mac and let us know how it responds when you attempt to download the PDF?

If would also be super if you could do the same with https://www.va.gov/find-forms/?q=20-0995

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO I don't think we need the verbage about the "Please Wait" error message because the download button is a what to use in the browser window regardless of whether the form opens correctly in the browser. Or maybe it's good to mention it as a side note, but I want people to use the Download button even if there isn't an error in form display.

**Comment by MarciMcGuireGCIO** [comment]
I'm fine not having a separate bullet, but I do think we have to address the "Please Wait" problem so people understand they can still download even when that appears.

**Comment by joshkimux** [comment]
https://user-images.githubusercontent.com/14154792/126545079-a814352f-e8cc-459f-8b19-58307938df78.mov

@MarciMcGuireGCIO No announcement is made when it opens in a new window, but focus somehow remains on the original page. I'm not sure if I'm experiencing a unique bug here. @AngelaFowler82 could you verify?

I would recommend against providing feedback in a new window solution because no heads up is provided to the user that it will open in a new window.

**Comment by MarciMcGuireGCIO** [comment]
Thanks @joshkimux .   The challenge we're up against is that the instructions for downloading PDFs varies depending on OS, browser, type of PDF, where the form is hosted, so it's more than will comfortably fit in context of the PDF link.

**Comment by AngelaFowler82** [comment]
For me, I don’t get an announcement but focus moves to the form as it renders in Chrome.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @AngelaFowler82 !

**Comment by MarciMcGuireGCIO** [comment]
@joshkimux -- the download icon appears in different locations depending on the browser. Is it acceptable to say "top of browser" or "bottom of browser" in the instructions?

cc @bethpottsVADEPO @cindymerrill

**Comment by joshkimux** [comment]
@MarciMcGuireGCIO , it depends? Top/down or below/above can be understood in terms of the reading order, so if the visual location is equivalent to the location of it in the DOM, then this shouldn't violate WCAG guidelines. For example, if the download icon is at the top of the browser visually, it should also be near the top of the DOM. 

> In some languages, it is commonly understood that "above" refers to the content previous to that point in the content and "below" refers to the content after that point. In such languages, if the content being referenced is in the appropriate place in the reading order and the references are unambiguous, statements such as "choose one of the links below" or "all of the above" would conform to this Success Criterion.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @joshkimux !

**Comment by bethpottsVADEPO** [comment]
This work is complete, so I'm closing ticket.
