### ISSUE TITLE
Limit Staging Review to 1 day per week

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#26585]
## Issue Description
The Staging Review touchpoint of the Platform Collaboration Cycle is the most time consuming, especially for the accessibility specialists. Currently VFS teams can schedule their Staging Review at any available timeslot during the week. The 6 timeslots are:

- Monday at 3:30 pm ET
- Tuesday at 11:00am ET
- Tuesday at 11:30am ET
- Thursday at 1:30pm ET
- Thursday at 2:00pm ET
- Friday at 2:00pm ET

It can be extremely time consuming and overwhelming for the Collaboration Cycle Reviewers if Staging Reviews are scheduled in more than 2 of the 6 timeslots for the week. On occasion, reviewers have been unable to complete their review on time for the meeting.

To allow for the reviewers to better manage the amount of work on their plate, the team has decided to limit Staging Reviews to only be scheduled on Thursday during the 1:30om and 2:00pm timeslots. 

---
## Tasks
- [x] Beginning the week of 7/5*, modify the Platform Collaboration Cycle Calendar to change the Thursday blocks from "[CALENDAR BLOCK]" to "[STAGING BLOCK]".
- [x] Beginning the week of 7/5*, modify the Platform Collaboration Cycle Calendar to change the Monday, Tuesday and Friday blocks from "[CALENDAR BLOCK]" to "[REVIEW BLOCK]"
- [x] In the Design Intent and Midpoint Review issue templates, add a bullet to the scheduling section to specify that Design Intents or Midpoint Reviews can only be scheduled on Monday, Tuesday and/or Friday.
- [x] In the Design Intent and Midpoint Review issue templates, change all instances of "[CALENDAR BLOCK]" to "[REVIEW BLOCK]".
- [x] In the Staging Review issue template, add a bullet to the scheduling section to specify that Staging Reviews can only be scheduled on Thursday.
- [x] In the Staging Review issue template, change all instances of "[CALENDAR BLOCK]" to "[STAGING BLOCK]".
- [x] Add entry to [Change Log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/change-documentation/README.md) specifying the scheduling change.
- [x] Shira to announce change at ToT
   - If launched the week of 7/5, Shira will announce in 6/29 ToT 
   - If launched the week of 7/12, Shira will announce in 7/6 ToT

*Subject to change to 7/12

## Acceptance Criteria
- [ ] VFS teams are aware of when Staging Reviews can be scheduled.
- [ ] Platform reviewers are able to better manage their weekly commitments. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
Hi, @shira, I don't have permissions to edit the Collaboration Cycle meeting calendar, but here is the PR for the other steps: 

https://github.com/department-of-veterans-affairs/va.gov-team/pull/26685

**Comment by shiragoodman** [comment]
@peggygannon the calendar is updated. I will wait to approve the PRs after I announce in ToT tomorrow. Thanks!
