### ISSUE TITLE
Missing appointment wait times on Jersey City page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26588]
## Issue Description
Veteran satisfaction with appointment wait times at [Jersey City VA Clinic](https://www.va.gov/new-jersey-health-care/locations/jersey-city-va-clinic/) are missing - observed on Prod. 

East Orange (in the same VAMC system) displays their wait time as expected

Area appears below service list

<details>
<summary> Screenshot from Prod </summary>

![image](https://user-images.githubusercontent.com/55411834/123318639-a75a1080-d4ec-11eb-9698-aa95d02256d9.png)

</details>

---
~Based on Facility Locator detail page for the location, there should be data available~ - this is wait time in days - not satisfaction scores

<details>
<summary> ~Screenshot from Facility Locator~</summary>

![image](https://user-images.githubusercontent.com/55411834/123319062-2a7b6680-d4ed-11eb-9d96-a956edfc089f.png)

</details>

## Expected behavior
If appointment wait time is available, it should be displayed. 

<details>
<summary> Screenshot from Pittsburgh for example </summary>

![image](https://user-images.githubusercontent.com/55411834/123318890-f2742380-d4ec-11eb-8f4f-34ae7205cd57.png)

</details>

## Dev notes
- This is a React widget
- May be expecting different attributes - Specialty feedback data is completely missing while Primary Care data is 0

---
## Tasks
- [ ] Ensure appointment wait time displays if available
- [ ] Prevent the display of the header and other content if data is not available

## Acceptance Criteria
- [ ] If appointment wait time is available for Jersey City, it should be displayed. 
- [ ] If appointment wait time is **not** available for Jersey City, the entire section should **not** be rendered. 
- [ ] Test coverage is present
- [ ] Should display whatever data is present, even if all is not available

**Comment by mmiddaugh** [comment]
Looks great - thank you!
