### ISSUE TITLE
[Ongoing Service] Contact Center Data Tracking

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#266]
## High Level User Story
As a Product Owner, I need access to Call Center data so I can understand where my users are having trouble with my product and prioritize iteration based on that knowledge.

## Hypothesis/(es)
**If** we have accessible Call Center data for product teams, such as in analytics dashboards **then** we expect the user data to be added to product workflows and decisions.

## Goals
We want to create lasting relationships with call centers and receive consistent and accurate data from each call center to indicate where users are having trouble with the products and where call center representatives are having trouble helping veterans close their issues.

## Objectives
`Intake & Onboarding`, `Automation + Instrumentation`, `Support`

## Definition of Done
- [ ] **Labeled with `analytics-insights`**
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**
