### ISSUE TITLE
Desired date - update heading and body copy

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26605]
## Description
Per Content feedback, update copy to reduce confusion between this page and the calendar page.
![desired date 26605.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/fd2baab2-66a4-4759-b8d1-102b53841cdd)

---
## Tasks
- [ ] Desired date page

## Acceptance Criteria
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/desired-date.md) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
- [Direct flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/direct-schedule-flow.md)

**Comment by laurenernest** [comment]
Update looks good.
![26605 validation.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/278726f8-395d-4c7b-afd1-736e26efb1c9)

@vbahinwillit please update the documentation linked in the description.
