### ISSUE TITLE
[FE] My VA: Investigate if we can rely on vaProfile.mhvAccountState to help determine if someone is getting VA health care

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26603]
## Background
Through building and testing of My VA 2.0 we found instances where we were receiving "false positives" in the health care section, i.e. the healthcare section appears for Veterans who are not actually enrolled in that benefit. See #26365 for context. We believe there's a way to cross check against MHV, but we need to do some research to validate that.

## Tasks
- [x] Investigate if it's possible to rely on vaProfile.mhvAccountState to help determine if someone is getting VA health care
- [x] Share findings with the team
- [x] If this is possible, document a strategy in the comments of the ticket
- [x] Work with PM/APM to create ticket(s) to implement

## Resources
<img width="625" alt="Screen Shot 2021-06-22 at 9 04 22 AM" src="https://user-images.githubusercontent.com/45603961/123335111-ff573e00-d511-11eb-949a-a430e3d1db7c.png">

## Validation
**- Who can validate this ticket? (FE, BE, Design, PM)?** Any team member
**- How can this work be validated?** Review documented strategy and confirm tickets are created

**Comment by tmitchellgcio** [comment]
This could be a plausible check for healthcare. I do not have it and my user profile shows "NONE". The staging users with healthcare show "OK" and the ones without it also seem to show "NONE" This likely is a good indicator. I wouldn't expect this to be a heavy task as we should have access to the user profile on the page already so no API calls, just a check and some tests. I'd expect a 2 point ticket that checks the mhvAccountState for "OK" or "NONE" and shows healthcare accordingly.

**Comment by tmitchellgcio** [comment]
Might need to verify that those are the only two states that can happen

**Comment by ericasauv09** [comment]
health-care-all-teams channel may be able to help
