### ISSUE TITLE
DS calendar - update heading and body copy

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26606]
## Description
Per Content feedback, update copy to reduce confusion between this page and the prior desired date selection page.
![ds calendar 26606.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8de3a0b7-893f-4e85-b547-4d14ca78cf5e)

---
## Tasks
- [ ] Calendar page (direct schedule)

## Acceptance Criteria
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar.md#direct) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
- [Direct flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/direct-schedule-flow.md)

**Comment by laurenernest** [comment]
Copy changes confirmed.

@vbahinwillit please update the screenshots in the documentation linked above.

**Comment by laurenernest** [comment]
Closing ticket since code complete and verified. @vbahinwillit leave a comment when the doc/screenshot has been updated.
