### ISSUE TITLE
Establish Playbook for Search & Discovery

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26617]
##  Description
As a result of the Privacy and Security Review for clicktracking we determined that a playbook for the search and discovery team should be established. 

## Background/Context
_What background information is available to support this work?__

## Tasks
- [x] Collect Information needed for playbook. From a dev ops perspective what would be required to fix an issue on a Sunday?  
   - Route to the code/source code module
   - Search.gov login info
   - etc.
- [x] Add playbook information to the product outline for Onsite Search

## Acceptance Criteria
- [ ] Above tasks have been resolved and playbook is ready for use

**Comment by srsuddath** [comment]
The search playbook now exists here!
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/search-playbook.md
