### ISSUE TITLE
Remove Nightwatch Specs from vets-website

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26618]
# Description
Once the Cypress version of the specs have proven effective for 10 business days we need to remove the redundant Nightwatch version of the specs from the repo.

## Tasks
- [x] `src/applications/burials/tests/00-all-fields.e2e.spec.js` removed
- [x] `00.0993-opt-out.e2e.spec.js` removed
- [x] `src/applications/letters/tests/01-authed.e2e.spec.js` removed
- [x] `00-all-fields.e2e.spec.js` removed
- [x] `00-load-error.e2e.spec.js` removed
- [x] `01-buttons.e2e.spec.js` removed
- [x] `src/applications/caregivers/tests/00.caregivers.e2e.spec.js` removed
- [x] `src/applications/login/tests/00.login-page.e2e.spec.js` removed
- [x] `src/applications/pensions/tests/00-all-fields.e2e.spec.js` removed
- [x] `00.coronavirus-screener.e2e.spec.js` removed
- [x] `01.custom-questions.e2e.disabled.spec.js` removed
- [x] `00.claims-list-breadcrumb.e2e.spec.js` removed
- [x] `00.claims-list-empty.e2e.spec.js` removed
- [x] `00.claims-list.e2e.spec.js` removed
- [x] `01.claim-status-decision.e2e.spec.js` removed
- [x] `01.claim-status-est-current.e2e.spec.js` removed
- [x] `01.claim-status-est-past.e2e.spec.js` removed
- [x] `01.claim-status-est.e2e.spec.js` removed
- [x] `01.claim-status.e2e.spec.js` removed
- [x] `02.claim-files.e2e.spec.js` removed
- [x] `03.claim-details.e2e.spec.js` removed
- [x] `04.claim-ask-va.e2e.spec.js` removed
- [x] `05.claim-additional-evidence.e2e.spec.js` removed
- [x] `05.claim-document-request.e2e.spec.js` removed
- [x] `06-claim-estimation-breadcrumb.e2e.spec.js` removed
- [x] `06.claim-estimation.e2e.spec.js` removed

**Comment by CBonade** [comment]
Update as of today that these have passed all their checks and have some reviews, but are still awaiting a number of reviews for approval to merge.

**Comment by CBonade** [comment]
Originally opened 6 days ago this is still awating 4 approvals to go into master. I've commented on Github notifying the 4 groups that it's awaiting a review.

**Comment by CBonade** [comment]
Got all necessary approvals and this has merged into master.  Ready to close!

**Comment by pjhill** [comment]
Well... there goes that half anyway! Thanks for closing this out.
