### ISSUE TITLE
Add new retroactive benefits question to DEA page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26625]
## Issue Description
Stakeholder Tammy Hurley sent text for a new question and answer about retroactive benefits to be added to the [Survivors' and Dependents' Education Assistance](https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/) page. The new content is provided in the word doc below. We would need to rework it for plain language and VA.gov's voice and tone. 

[https://app.zenhub.com/files/133843125/ba29ba99-d9c4-47e2-abb5-4dbd0de54d32/download](https://app.zenhub.com/files/133843125/ba29ba99-d9c4-47e2-abb5-4dbd0de54d32/download)

## Tasks
- [x] Rework provided content and put on Drupal page
- [x] Send to stakeholder for review
- [ ] Input changes
- [ ] Review and publish

## Acceptance Criteria
- [ ] New content live on DEA page

**Comment by bethpottsVADEPO** [comment]
@RLHecht I rewrote the Q&A so it's less repetitive and aligned with our plain language standards. Please add this to drupal, copyedit, and then send the preview link to Tammy et al. You can place it as the last Q&A on the page. Thanks!:

**Can I get back payments for training I’ve already completed?**

Yes. You can get back payments for training that started on or after your eligibility date. These payments are sometimes called retroactive DEA benefits. Your eligibility date is the same as the effective date of the Veteran’s disability compensation rating decision. So if the Veteran’s effective date is in the past, you can get payments back to that date. We’ll pay you for up to 1 year of back payments. 

**Note:** You may qualify for more than 1 year of back payments if the Veteran’s effective date is more than 1 year before their decision date. But to get the full amount of your payments, you must submit your application within 1 year of the Veteran’s rating decision.

**Comment by SgardnerPMP** [comment]
Randi to Follow up with Tammy/stakeholder

**Comment by SgardnerPMP** [comment]
Tammy will have to be contacted on regular cadence to engage.

**Comment by RLHecht** [comment]
I don't think this back pay question ever got approval. @bethpottsVADEPO is this something we should ask Tammy about again?

**Comment by bethpottsVADEPO** [comment]
I can address this with SMEs Cinda and Jodie, who I meet with weekly for the accuracy audit. We're looking at DEA and Fry pages right now anyway. Closing this ticket!
