### ISSUE TITLE
NOD: Homelessness page content update.

### ISSUE THREAD

**Issue by ashagross** [department-of-veterans-affairs/va.gov-team#26631]
## Issue Description
Homeless page question needs to be re-worded.

---
## Tasks
- [ ] Update homeless page to reflect content changes.

## Acceptance Criteria
- [ ] Question will be changed to "Are you experiencing homelessness?"
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
