### ISSUE TITLE
Remove More helpful resources section from Fully Developed Claims page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26633]
## Issue Description
We need to remove the More helpful resources section from the [fully developed claims](https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/) page because it points to eBenefits pages. 

---
## Tasks
- [x] Remove More helpful resources section
- [x] Review and publish

## Acceptance Criteria
- [x] More helpful resources will no longer show on live page

**Comment by RLHecht** [comment]
Work completed. Moving to validate and will close once live on site.

**Comment by RLHecht** [comment]
Work completed. Closing ticket. FYSA @bethpottsVADEPO
