### ISSUE TITLE
Include Github ticket link in Slack removal request bot message

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#26640]
## Description
There is a [Github action](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/slackRemovalRequest.yml) that sends an automated message to #vsp-slack-user-management triggered by [Offboarding](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3AOffboarding) Github tickets.

When these messages are received in the Slack channel, it would be helpful to have a link to the Github issue that triggered the message for traceability purposes.

---
## Tasks
- [x] Add link to Github issue in Slack message of slackRemovalRequest GHA 

## Definition of Done
- [x] Offboarding Slack messages sent to #vsp-slack-user-management include a link to the Github offboarding ticket

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by mydesignrocks** [comment]
can this be closed? @mchelen-gov

**Comment by jhouse-solvd** [comment]
This looks to be done. Please re-open or create a new ticket if anything else is needed. 

Closing.

**Comment by mchelen-gov** [comment]
Oh yeah this is great, thank you!
