### ISSUE TITLE
[UI] Update check-in based upon usability testing and midpoint review

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#26645]
Based upon the feedback from the midpoint review and the outcome of the usability tests, update the check-in wireframes and poster..

## Tasks
- [x] Work with team to determine what changes we will actually be making
- [x] Update Sketch wireframes
- [x] Update and finalize posters
  - including Vector QR code and more poster sizes

## Acceptance Criteria
- [x] Review with team

**Comment by kristenmcconnell** [comment]
Make sure to include the error states for the following scenarios:
- Unauthorized token
- Check-in fails

Create a version like "See a staff member."

**Comment by kristenmcconnell** [comment]
Met with Corey and Mark to review midpoint review items.

**Comment by kristenmcconnell** [comment]
## Here is the list of things to change from usability and midpoint review: 

**Definitely update**
- Change instruction text for what to do next on the confirmation page. 
- Add back buttons when someone clicks yes or no to the contact/insurance question
  - Work with Danielle on wording
  - “Back to update information” or “Did you mean to hit yes?” Or “Need to update your information?”
   - Ask VeText if we can have a back button in the Yes scenario - Corey taking as an action item.
- Look into more instructions under “please check in with a staff member.” If you are still lost, call this number.” Content explaining why they can’t check in online, because they need to update eerier info. 

**Nice to have**
- Look into hint text example for insurance, contact, or other information. 
- Move “Need help?” Footer to content area? I will play around with that this week. 
- Add a secondary header letting people know that they are on check-in after clicking URL in text message (from IA Feedback in mid point review)

**Comment by kristenmcconnell** [comment]
@jparker0425 Complete list of the design changes that need to be completed based upon the midpoint review and usability testing.

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA The items in the above comment are what we will be discussing today.

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Without shortening the URL, the URL will be around 88 characters and look something like this:

https://va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287

See [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1625667001457200) with details.

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell - Going to start adding content feedback below.

## For text

I think either of these options could work, with the "welcome" being a little warmer.

Check in for your VA appointment at https://va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287

Welcome to VA. Check in now at https://va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287

## Screen 1

_Note: Thinking through this one a bit. Question though - were people looking for examples specifically of what we mean by "other information"? And that's basically next of kin or medical history info, correct?_

## Screen 2

[link] Back to last screen

[h1] Check in with a staff member.

[text] They can help you update your information before your appointment.

[need help component]

Not sure who to check in with?
Call us at [phone number]

## Screen 4

_Question here: Will the place they're going always be called a "clinic"? I want to make sure we're not confusing them. Or, could we potentially show dynamic content here such as "Go to the [clinic name] waiting room."?

[h1] Thank you for checking in

[text] Go to the clinic waiting room. A staff member will tell you when we’re ready for you.

[need help component]
Not sure where the waiting room is?
Ask a staff member or call us at [number]

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA 

**Text**
I like those text options. I'll run them by the VeText team.

**Screen 1**
- I think some examples of contact information, such address and phone would be good. Describing what other information means would be good too. Next of kin is what we meant originally with "other information." However, from my observations today at the Pittsburgh VAMC, they also ask about emergency contacts. I'll have to talk to the team about if we should include emergency contact in our description or not.

**Screen 2**
I like it.

**Screen 4**
We are pulling in the actual clinic name on the Appointment information page, so we should be able to display the actual name on this confirmation page as well. @mdewey Do you see any reason why we should be able to? 

It is also very important to mention that the next step involving a human coming to get them. People thought they would receive a text next, so we want to set the correct expectation.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @kristenmcconnell. Yes, absolutely for screen 4. Just wanted to confirm "clinic" piece first.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell. Full content here:

## For text

### 2 options:

1. Check in for your VA appointment at https://va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287

2. Welcome to VA. Check in now at https://va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287

## Screen 1

### 2 options
_Note: I wanted to explore both placements for the example text, as we discussed. Option 2 reinforces the messaging around checking in with a staff member in addition to providing examples. Just let me know if you want to talk through this screen more._

1. 

[h1] Check in at VA

[h2] Do you need to update any information?

[text] This includes information like your phone number, address, insurance plan, or next-of-kin.

[radio buttons]
Yes
No

[button] Continue

[+ existing help component]

2. 

[h1] Check in at VA

[text] If you need to update information like your phone number, address, insurance plan, or next-of-kin, we'll ask you to check in with a staff member.

[h2] Need to update your contact, insurance, or other information?

[radio buttons]
Yes
No

[button]
Continue

[+ existing help component]

## Screen 2

[link] Back to last screen

[h1] Check in with a staff member.

[text] They can help you update your information before your appointment.

[+ existing help component]

## Screen 4

[h1] Thank you for checking in _[or can use "You're checked in"]_

[text] You can now go to the [clinic name] waiting room. We'll come get you when it's time for your appointment to start. 

[+ existing help component]

**Comment by DanielleThierryUSDSVA** [comment]
## Error message

### We couldn't check you in

We're sorry. Something went wrong on our end. Check in with a staff member or call us at [clinic/facility phone number].

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA @jparker0425 

Here are the two options for Screen 2.
Option 1
![Contact.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/e43970ad-689b-4253-b0b8-d882eea3760f)

Option 2
![Contact Option 2.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ce038aef-2daa-490a-8ca4-106d73c258a1)

Danielle - I like your logic for Option 2 and how it reiterates that they will have to check-in with a staff member. I would pick the version. Corey and Danielle - Thoughts?

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA @jparker0425 

I played around with the confirmation page too. I like the new content. Thoughts on it in just an alert and not H1/text?

![Confirmation.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/59248242-c7a7-4309-b4d3-672ea4750417)![Confirmation Option 2.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/386cbef8-42d3-4fcf-99eb-62a85a4d1d0f)

**Comment by jparker0425** [comment]
@kristenmcconnell For the "update info" screen, based on our conversation I think moving forward with option 1 will be cleaner and more concise. 

For the confirmation page, option 2 with the alert indicator for consistency.

**Comment by kristenmcconnell** [comment]
@mdewey @jparker0425 
Here are the [final wireframes](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/QbxZp4L/play). 

Here is the error state that should be utilized for both the unauthorized token and check-in fails scenarios: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/MynDRab.

@Kennon-git @snyderje 
Based upon our usability test, we made a small update to the text message, so it will need to be updated in VeText. See [wireframe](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/QbxZp4L).

**Comment by jparker0425** [comment]
Looks fantastic @kristenmcconnell !

**Comment by kristenmcconnell** [comment]
Updated posters for review.

8.5X11
[https://app.zenhub.com/files/133843125/41c772fc-73e0-40a9-9a0a-5b569d7dd934/download](https://app.zenhub.com/files/133843125/41c772fc-73e0-40a9-9a0a-5b569d7dd934/download)

11X17
[https://app.zenhub.com/files/133843125/1d6a453b-7656-4764-bc8b-a7e90276d5df/download](https://app.zenhub.com/files/133843125/1d6a453b-7656-4764-bc8b-a7e90276d5df/download)

24x36
[https://app.zenhub.com/files/133843125/d19efa4f-822f-4635-afab-51f8e6dfe841/download](https://app.zenhub.com/files/133843125/d19efa4f-822f-4635-afab-51f8e6dfe841/download)

**Comment by kristenmcconnell** [comment]
Closing ticket. Will incorporate any poster feedback into another ticket.
