### ISSUE TITLE
NOD: Board review timeline update

### ISSUE THREAD

**Issue by ashagross** [department-of-veterans-affairs/va.gov-team#26650]
## Issue Description
Board review options timeline has changed, need to update to reflect the content changes. 
  

---
## Tasks
- [ ] _Update board review page to reflect new timeline updates.  _

## Acceptance Criteria
- [ ] _Request a direct review to from 1 year to 1.5years, Submit more evidence from 1 year to 1.5 years, Request a hearing from 1 year to 2 years.?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
