### ISSUE TITLE
A11y Dash: Refactor to ingest raw data into BQ

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#26662]
## Issue Description

Refactor to ingest data into BigQuery without transforming / making calculations with JavaScript.

---
## Tasks
- [x] Refactor dashboard to display data based on SQL queries
- [x] Refactor ingestion system to remove interpretation of data in flight
- [ ] Filter / do not store unnecessary data such as URLs for avatar pictures, etc.

## Acceptance Criteria
- [ ] Calculations for displaying in DOMO are made with SQL
- [ ] Ingestion mechanism is not interpreting data before storing it in BigQuery

**Comment by rjohnson2011** [comment]
Refactored Github Services to remove Metrics Service entirely and generate all these using SQL/BQ.
Added requested params to Issues Service, including updated_at and issue_number.
Now sending all Github Issues from va.gov-team into BQ rather than parsing these through JS based on '508/Accessibility' label.
Working on final SQL/BQ queries to generate Domo charts.

**Comment by rjohnson2011** [comment]
Added refactored SQL queries for 
Total Issues & PRs for Accessibility vs All Issues & PRs
Open vs Closed Issues
Refactored Defects SQL query so defects show in ascending order

Finalizing labels in Domo to wrap up early tomorrow.

**Comment by rjohnson2011** [comment]
All Domo charts are revised & populated from issues with SQL: https://va-gov.domo.com/page/486021553
Preview:
![image](https://user-images.githubusercontent.com/72466113/124306931-0f37d900-db35-11eb-9f27-919058dbe6a1.png)

![image](https://user-images.githubusercontent.com/72466113/124306893-047d4400-db35-11eb-949c-bb586e75a471.png)

**Comment by rjohnson2011** [comment]
All Domo charts updated and populated using SQL, all JS has been refactored out of services.
https://va-gov.domo.com/page/486021553
