### ISSUE TITLE
Clean Circle CI logic out of Cypress Tests

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#26660]
## Issue Description
There are some Cypress tests that have logic that was built around CircleCI, these tests need to be cleaned up to remove this.

---

## Tasks
- [x] Determine which tests need to be cleaned up
- [x] Clean up and check the tests

## Acceptance Criteria
- [x] All tests are cleaned up and running as expected

**Comment by CBonade** [comment]
This was merged into master this morning. All tests were already running, successfully, in CI.  They just needed the conditional `skip` removed that was determined by Circle CI being present.

**Comment by CBonade** [comment]
Update that one approval has been given, but many outstanding approvals are still required to merge this.

**Comment by CBonade** [comment]
Reminder was sent to outstanding reviews yesterday and one more was received, but still awaiting two more reviews.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17741 PR for this is still awaiting two reviews. The appropriate teams have been tagged in the PR comments.

**Comment by pjhill** [comment]
Thanks for chasing down approvals. This is merged and completed.
