### ISSUE TITLE
526: Fix wizard link

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#26669]
## Description

In the process of moving the 526 disability wizard to its new `/start` page. The production version of the wizard is still rendered on the info page (`https://www.va.gov/disability/how-to-file-claim/`) which still has the feature flag disabled. The "File a disability claim online" link is not including a destination URL

Related:
- https://dsva.slack.com/archives/C5AGLBNRK/p1624890980250500
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/26195

## Tasks

- [ ] Fix production wizard link
- [ ] Double check feature flag

## Definition of done

- [ ] Production wizard works with feature flag enabled & disabled
