### ISSUE TITLE
Vet Center Spotlight CTA

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26676]
## Issue Description
- The "In the Spotlight" area allows Vet Center content field staff to highlight a story or service and include a call to action. 
- If the editor opens the "Add call to action" area and adds a space, the field for the CTA will render and produce an empty tag. 
-Calls to action are not required. 

Calls to action contain:
- Button Label
- Button link

We observed this for the fist time on Springfield's page but I have recreated it on Abilene's. 

<details>
<summary> Preview screenshots for featured content area </summary>

![image](https://user-images.githubusercontent.com/55411834/123660393-daecb180-d7f0-11eb-9914-717fcc37d613.png)

</details>

<details>
<summary> Drupal screenshots for featured content area </summary>

![image](https://user-images.githubusercontent.com/55411834/123661232-a3323980-d7f1-11eb-8986-d396a322b4c0.png)

</details>

---
## Tasks
- [x] View this content on prod.cms.va.gov/node/3886
- [x] Add defensive code 

## Acceptance Criteria
- [x] If no content is present, the call to action area should not render. 
- [ ] Test coverage is present
