### ISSUE TITLE
Add new particulate matter alert to several disability pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26675]
## Issue Description
Now that VA has added 3 new presumptive conditions for burn pit toxic exposure, we need to add an alert on several disability pages. 

Once we get the OK, the alert on this page: http://preview-prod.vfs.va.gov/preview?nodeId=885 will be placed on ~all of these pages~ the following page: 
- https://www.va.gov/disability/eligibility/hazardous-materials-exposure/specific-environmental-hazards/
- ~https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-southwest-asia/~
- ~https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-afghanistan/~
- ~https://www.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/~

This is being brought over from ticket #25505, which is now just for the Agent Orange work.

## Tasks
- [x] Add alert to disability pages listed above
- [x] Review and publish
- [x] Alert stakeholders that changes are live

## Acceptance Criteria
- [x] Particulate matter alert is live on pages

**Comment by bethpottsVADEPO** [comment]
This is live!
