### ISSUE TITLE
National Vet Center content is missing

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26674]
## Issue Description
Two areas of National Content are not rendering on the Vet Center front end pages, although they are available in Drupal. This is a newly identified defect (previously, they were displayed)

Only some areas of national content are missing - national text content is still displayed

This has been observed in Preview. 
Dave rebuilt Tugboat and validated the issue is still present. 

Springfield nodeID = 3599
National "In the Spotlight" nodeID = 16142

## Areas affected:
National "In the Spotlight" 
FAQs (bottom of the Main page)

## Screenshots

<details>
<summary> Drupal screenshots for featured content area </summary>

![image](https://user-images.githubusercontent.com/55411834/123659147-9b719580-d7ef-11eb-82eb-62ead481c89c.png)
</details>

<details>
<summary> Preview screenshots for featured content area </summary>

![image](https://user-images.githubusercontent.com/55411834/123659268-ba702780-d7ef-11eb-93aa-c84226fbf5e3.png)

</details>

---

<details>
<summary> Drupal screenshots for FAQ area </summary>

![image](https://user-images.githubusercontent.com/55411834/123659063-898ff280-d7ef-11eb-98d3-debe27f4ffa5.png)

</details>

<details>
<summary> Preview screenshots for FAQ area </summary>

![image](https://user-images.githubusercontent.com/55411834/123659361-d673c900-d7ef-11eb-984e-973307c2e82b.png)

</details>

---
## Tasks
- [ ] Resolve bug impacting the display of the National "In the Spotlight"  and FAQ content

## Acceptance Criteria
- [ ] National "In the Spotlight" content ("Borne the Battle" podcast) is displayed as first of blue "In the Spotlight" boxes
- [ ] FAQ accordions (and content within) are displayed between end of services list and footer

**Comment by mmiddaugh** [comment]
We assume these issues are related and will separate this issue if needed

**Comment by mmiddaugh** [comment]
Viewed tugboat instance for Escanaba - national content is displayed as expected - thank you!
