### ISSUE TITLE
TUD - Fix bad nginx configuration

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#26672]
## Issue Description
The nginx configuration that was first uploaded to the Kubernetes cluster is not working as intended. This updates the nginx configuration to include best practices like adding security headers, compression, etc.

---
## Tasks
- [x] Update the nginx.conf
- [x] Verify pod is running as expected.

## Acceptance Criteria
- [x] Kubernetes pod runs as expected
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
