### ISSUE TITLE
[FSR] Add a page to the start of CH4 (household expenses) to help Veterans understand why they should provide all their expenses

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#26680]
## Issue Description
_The FSR's usability study uncovered that many Veterans perceive providing expenses as having a negative impact on their request, when it's in fact the opposite. In order to help Veterans understand that they should provide all their expenses, we should add a page at the beginning of CH4 outlining the expenses they should expect to provide as well as why they should provide them._

[UXPin prototype for reference](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/140008855/simulate/sitemap?mode=i)

---
## Tasks
- [ ] _Add a page at the beginning of CH4 that matches the provided prototype_

## Acceptance Criteria
- [ ] _A page has been added to the start of CH4 that matches the provided prototype_
- [ ] _The UI has been reviewed by a designer_

**Comment by rileyorr** [comment]
FYI I added the blocked label because this content should be approved by the DMC team prior to development.

**Comment by josephrlee** [comment]
Marking this as closed, content work was done previously in #15766 not sure when the implementation happened, but it's live in the FSR, here is the [Figma mockup for reference](https://www.figma.com/design/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---(including-Streamlined-Waiver)?node-id=244-72136&t=e7X8xxLJVLGtzFpk-11). 

cc: @Tom-Davis @dhill802 @mgleo @denisecoveyduc @charlottecesana
