### ISSUE TITLE
Implement Visual Testing Tools for Inclusion in Production Monitoring

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26686]
## Issue Description
- As a Platform stakeholder, I need visual testing of production incorporated into the synthetic monitoring solution so I can monitor the Platform for issues presenting in the UI.
---
## Tasks
- [ ] Implement solution based on research from [#26313](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/26313)

## Acceptance Criteria
- [ ] Solution is implemented, tested, and works as expected
- [ ] Notifications are tested to ensure that failures report properly
- [ ] Create documentation describing standard operating procedure for triaging and resolving visual testing errors in synthetic monitoring of production

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
Overcome by events
