### ISSUE TITLE
[MCP] Switch out mobile alerts based on feedback

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#26683]
## Issue Description
After feedback from Shawna and Kristen, we will switch out our mobile alert for MCP for the ones found in [this prototype](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145/simulate/sitemap?mode=i). We will test the new component styling with our upcoming MCP usability study.

---
## Tasks
- [x] Switch out existing mobile alert with the ones found [here](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145/simulate/sitemap?mode=i).
- [x] Update convo guide to ensure we're asking about the alert to test it.

## Acceptance Criteria
- [x] Designs created and prototyped in UXPin and linked
- [x] Convo guide updated and linked

**Comment by rebeccawalsh** [comment]
New design can be seen in the prototype here: https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages/139878809/simulate/no-panels?mode=i

**Comment by rebeccawalsh** [comment]
Determined that the [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/conversation-guide.md) is fine as-is!
