### ISSUE TITLE
Include specified "Nearby Mobile Vet Centers" in Satellite Locations list

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26689]
## Issue Description

- Vet Center field staff can specify "Nearby Mobile Vet Centers", similar to how they specify "Nearby Vet Centers and Outstations". However, the  specified Nearby Mobile Vet Centers do not currently display on Vet Center location pages. 
- This issue impacts all Vet Centers and was observed in preview for Nashville Vet Center, nodeID= 17946
- We need to address the sort order for these locations (Sort order for the Locations list is documented in #26691)

## Background
- Vet Centers are not required to specify a Nearby Mobile Vet Center 
- Vet Centers may choose to specify one or more. 
- Mobile Vet Center addresses should not be displayed, based on transient nature and to be consistent with VAMC location pages 

## Screenshots
<details>
<summary> Screenshot from Nashville Locations page </summary>

![image](https://user-images.githubusercontent.com/55411834/123687625-5f016200-d80e-11eb-8d32-361a97af81a0.png)

</details>

<details>
<summary> Screenshot from Nashville Drupal </summary>

![image](https://user-images.githubusercontent.com/55411834/123687930-b4d60a00-d80e-11eb-95f3-e4cc7be519d0.png)

</details>

---
## Tasks
- [x] Ensure Mobile Vet Centers specified in "Nearby Mobile Vet Centers" are included in list appearing under the "Satellite locations" heading
- [x] Remove Mobile Vet Center address from list details

## Acceptance Criteria
If specified in Drupal: 
- [x] "Nearby" Mobile Vet Centers display at the end of the "Satellite locations" list 
- [x] Mobile Vet Center listings do not contain address (only name, phone number and image, if available)
- [x] In the event there is more than one Mobile vet center in the "Satellite locations" list - they will be alpha order
- [x] Functionality governing the placement of **Affiliated** Mobile Vet Centers within the "Satellite Locations" section is maintained

**Comment by mmiddaugh** [comment]
@mpelzsherman I corrected an error in the task description above - to confirm, any Mobile Vet Centers 
- either "Nearby Mobile Vet Centers" (`field_nearby_mobile_vet_center`) _or_ 
- automatically associated with the location (`vet_center_mobile_vet_center`) 
should appear under the "Satellite locations" heading

**Comment by mmiddaugh** [comment]
Looks good - thank you!
