### ISSUE TITLE
Vet Center Satellite Locations sort order

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26691]
## Issue Description
Affiliated Outstations, Mobile Vet Centers and Community Access points are displayed in a list of "Satellite Locations" on the Vet Center Locations page. Currently, the list appears to based on the order in which they were affiliated. 

This issue impacts all Vet Centers and was observed in preview for Nashville Vet Center, nodeID= 17946

## Background
<details>
**None of the following are required** but a Vet Center **might** have:

- one Outstation _(unlikely to have more than one)_
- one Mobile Vet Center _(unlikely to have more than one)_
- **one or more** Community Access points

Outstations and Mobile Vet Centers 
- exist within VAST 
- have facility IDs
- are automatically affiliated with the appropriate Vet Center in Drupal

Community access points 
- are not in VAST 
- do not have facility IDs
- are added by field staff in Drupal
- follow a naming convention which begins with the Vet Center name (ie: "Nashville Vet Center - Bowling Green") 
- are more likely to come/go than Outstations or Mobile Vet Centers. 
</details>

## Screenshots
<details>
<summary> Screenshot from Nashville Locations page </summary>

![image](https://user-images.githubusercontent.com/55411834/123690232-60805980-d811-11eb-9e9e-1797b7cce6fd.png)

</details>

## Examples
<details>
[Colorado Springs Location page](https://www.va.gov/colorado-springs-vet-center/locations/) has 3 CAPs, listed as 
Colorado Springs Vet Center - Monument
Colorado Springs Vet Center - Fort Carson
Colorado Springs Vet Center - Divide

**Expected behavior:** 
Colorado Springs Vet Center - Divide
Colorado Springs Vet Center - Fort Carson
Colorado Springs Vet Center - Monument
---
[Escanaba Location page](https://www.va.gov/escanaba-vet-center/locations/) has 3 CAPs, listed as
Escanaba Vet Center- Marquette
Escanaba Vet Center - Sault Ste Marie
Escanaba Vet Center - Houghton

**Expected behavior:** 
Escanaba Vet Center - Houghton
Escanaba Vet Center- Marquette
Escanaba Vet Center - Sault Ste Marie
</details>

---
## Tasks
- [ ] Confirm current sort order logic for "Satellite Locations"
## Acceptance Criteria
- [ ] All affiliated outstations, community access points, and Mobile Vet Centers are listed within the "Satellite Locations" list. 
- [ ] within the "Satellite Locations" list = outstations and community access points are grouped together and sorted by alpha order followed by Mobile Vet Centers, grouped in alpha order

**Comment by mpelzsherman** [comment]
Blocked due to information needed about the mobile vet centers content model. See [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1628088503100000) for details.

**Comment by mpelzsherman** [comment]
I confirmed the sort order looks correct on the following pages:

https://www.va.gov/escanaba-vet-center/locations/
https://www.va.gov/nashville-vet-center/locations/
https://www.va.gov/colorado-springs-vet-center/locations/

Can we close, @mmiddaugh ?

**Comment by mmiddaugh** [comment]
looks good to me! Thank you
