### ISSUE TITLE
[VAMC] Resolve changes to Playbooks in VISNs (22, 5, 12) and prepare them for csv file preparation [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26692]
## Story
As an editor/web maintainer and data migrator, I need to have health services match CMS systems so I can better understand the cross over and how best to load the data quickly into CMS.

## Goal
update system health service and facility taxonomy to match changes in taxonomy and prepare files to be loaded using .csv file format

## Tasks
Update Health service playbooks and create .csv file prep document for both System and Facility health services
- [x] Playbook updated with new Taxonomy
- [x] System and Facility Health Service for each system in VISN created.
- [x] Consolidated System and Facility tabs created

## Acceptance criteria
- [x] Excel document is created and shared in team repository 
- [x] Playbook in team repository is updated and ready for distribution to field/stakeholders.
