### ISSUE TITLE
[MCP] Usability study prep

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#26695]
## Issue Description
_Prior to the usability study kicking off on July 1, we need to prep for note-taking and debriefing._

---
## Tasks
- [x] _Set up note-taking/synthesis spreadsheet_
- [x] _Schedule meetings for daily debrief sessions and set up Mural board as needed_

## Acceptance Criteria
- [x] _Note-taking/synthesis spreadsheet is linked in this ticket_
- [x] _Daily debrief sessions are scheduled and Mural board is linked_

**Comment by rileyorr** [comment]
@LindaLi123 FYI I'm pulling this ticket in to work on today since we finished all our design tickets for Sprint 50. I don't see a Sprint 51 milestone, but I'll update this ticket whenever that milestone becomes available.

**Comment by LindaLi123** [comment]
@rileyorr Thank you Riley!  Just created Sprint 51 milestone.

**Comment by rileyorr** [comment]
- Created the topline summary & note-taking spreadsheet ([link](https://docs.google.com/spreadsheets/d/1vPSw3dJpzITntFBg29o9Yf3AwEo4AX77Hn6jiSmQaZg/edit?usp=sharing))
- Added a couple debrief sessions based on Perigean's scheduled sessions; will add more debrief sessions as the invites roll in!

**Comment by rileyorr** [comment]
All the debrief sessions have been scheduled! Both Becca and I have appointments right after Tuesday's session at 2:30 so we won't be able to facilitate a debrief that day.
