### ISSUE TITLE
Set KPIs across VSA & VSP teams

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#267]
## High Level User Story
As a Product Owner, I need to set KPIs so I can establish the right metrics to capture and watch in order to produce a better website experience for veterans.

## Hypothesis/(es)
**If** we aggregate product KPIs across product teams and establish a consistent format **then**  we expect product teams to evaluate how well products are performing in different areas and iterate based on that data.

## Goals
Determine, set, and track KPIs across product teams. Insights should support product teams in establishing KPIs, including hosting workshops that help define and track KPIs, tracking metrics for those KPIs, and determining successful goals. 

## Objectives
`Automation + Instrumentation`, `Support`, `Capacity-building`

## Definition of Done
- [ ] **Labeled with `analytics-insights`**
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**

## Resources
[Example KPI workshop](https://docs.google.com/presentation/d/1mNev7olSi2vM6vjDnp2PJlKSS4BXvEHke12bYM8-qQY/edit#slide=id.p)

## Acceptance Criteria
- [ ] By Light
    - [ ] Workshop scheduled
    - [ ] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [x] VSA Global UX
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
- [x] VSA Authenticated Experience
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
- [x] VSA Benefits & Memorials
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
- [ ] VSP Operations
    - [ ] Workshop scheduled
    - [ ] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [ ] VSP Tools & Improvements
    - [ ] Workshop scheduled
    - [ ] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [ ] VSP Triage
    - [ ] Workshop scheduled
    - [ ] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [x] VSP Product Support
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
- [ ] VSP Analytics & Insights
    - [ ] Workshop scheduled
    - [ ] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [x] VSP Content & IA
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
- [ ] VAOS
    - [ ] Workshop scheduled
    - [ ] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [ ] Get Care
    - [ ] Workshop scheduled
    - [ ] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [x] VSA Caregiver
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
- [x] VSA Facility Locator
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
- [ ] VSA Benefits & Memorials 2
    - [ ] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [ ] Workshop completed
    - [ ] Post-Workshop excel sent out
- [x] VSA eBenefits
    - [x] Workshop scheduled
    - [x] Pre-Workshop Sent out
    - [x] Workshop completed
    - [x] Post-Workshop excel sent out
