### ISSUE TITLE
Analytics Implementation or QA Support for [Authenticated Experience - My VA Claims and appeals error tracking]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26703]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA? 
     - Google Analytics implementation

When users land on the My VA dashboard, we often need to make calls to the GET /evss_claims_async API. This API is very slow and we need to call it every five seconds. If it does not have data after thirty seconds, we stop calling the API and treat it like an error.

We'd like to track the following events:

1. a call to the claims API succeeds
2. a call to the claims API fails
3. a call to the claims API has timed out (when we stopped calling it because it was taking too long)

Additionally, when a claims API call has succeeded we'd like to report how long it took to succeed. This would be done with a very rough level of precision, to the nearest five seconds.

What events would we need to send to GA to record the above events?

- Who is this request for?

    - DEPO Product Lead: @Samara-Strauss (interim, @KevinMHoffmanUSDS )
    - Product Manager: @ajakabcin 
    - Designer: @tressaellen 
    - Frontend engineer: @erikphansen 
    - Backend engineer: @lihanli
    
_Provide any relevant contact information and link this issue on the DSVA Slack Channel: `#VFS-Platform-Support` and tag `@platform-analytics`._
    
- What team/project is this work for?
    Authenticated Experience, [My VA redesign product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md)
    
    
- Provide the Domain where Google Analytics needs to be implemented
    va.gov/my-va

- _Identify if PII is passed in URL or title tag_
No
    
- Please provide any upcoming deadlines or important milestones
    Targeting phased launch to begin this week (6/28), however this enhancement to our existing GA tracking is not required for launch, though we would like it in place as soon as possible
    

- Please provide website interactions to Track
We need to track how frequently My VA fails to retrieve Claims and Appeals data

Additional documentation around OKRs and KPIs here: [Product outline: My VA > Measuring Success](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/README.md#measuring-success)

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
      - [My VA test cases and users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)
    
- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [My VA test cases and users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)

> Please leave the following blank

## Acceptance Criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by joanneesteban** [comment]
Hi @ajakabcin ! @bsmartin-ep will be getting back to you on this ticket!

**Comment by ajakabcin** [comment]
Hi @bsmartin-ep - any updates on this?

**Comment by ajakabcin** [comment]
Also, @bsmartin-ep, I added some additional info to the body of the request, posting here for reference as well:

When users land on the My VA dashboard, we often need to make calls to the `GET /evss_claims_async` API. This API is very slow and we need to call it every five seconds. If it does not have data after thirty seconds, we stop calling the API and treat it like an error.

We'd like to track the following events:

1. a call to the claims API succeeds
2. a call to the claims API fails
3. a call to the claims API has timed out (when we stopped calling it because it was taking too long)

Additionally, when a claims API call has succeeded we'd like to report how long it took to succeed. This would be done with a very rough level of precision, to the nearest five seconds.

What events would we need to send to GA to record the above events?

**Comment by bsmartin-ep** [comment]
Apologies for the delay @ajakabcin - we had to tame our tagging for these API calls.  We would like to to use our new global `api_call` event.

> a call to the claims API succeeds

```js
{
     event: 'api_call',
     api_name: 'View Claims and Appeals',
     api_status: 'successful'
}
```

> a call to the claims API fails

```js
{
     event: 'api_call',
     api_name: 'View Claims and Appeals',
     api_status: 'failed',
    'error-key': '500 Your error message'
}
```

> a call to the claims API has timed out (when we stopped calling it because it was taking too long)

```js
{
     event: 'api_call',
     api_name: 'View Claims and Appeals',
     api_status: 'failed',
    'error-key': '500 timeout message'
}
```

You may also want to fire an event when the request begins to get a completion rate....

```js
{
     event: 'api_call',
     api_name: 'View Claims and Appeals',
     api_status: 'started'
}
```

**Comment by ajakabcin** [comment]
Thanks @bsmartin-ep - I'll create a separate ticket for @erikphansen to implement these and circle back for assistance with QA/testing.

@erikphansen any questions/concerns on this?

**Comment by erikphansen** [comment]
@bsmartin-ep Thanks for this!

A few notes/questions:
- claims and appeals are actually two different APIs. So the `api_name` would be something like `'GET claims'` or `'GET appeals'`. Is that fine?
- I don't think we'll fire events when we make a call, at least when getting claims, because this call could be made every five seconds for 30 seconds. Yeah it's a weird endpoint.
- Also, we want to record how long it took when the `GET claims` succeeded. We'll have that data in the FE and it'll be rough numbers, like 5s, 10s, 15s, etc. Is that something we can track?

**Comment by ajakabcin** [comment]
Created #27167 for implementation on our end.

Just need some clarification from @bsmartin-ep regarding Erik's questions [above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26703#issuecomment-876643142)

**Comment by bsmartin-ep** [comment]
@erikphansen -

> claims and appeals are actually two different APIs. So the api_name would be something like 'GET claims' or 'GET appeals'. Is that fine?

Sure - whatever descriptive name makes sense for you.  It will be appended to the end of the Event Action.

> I don't think we'll fire events when we make a call, at least when getting claims, because this call could be made every five seconds for 30 seconds. Yeah it's a weird endpoint.

Would we see API return events every 5 seconds?  Or those would be less frequent?

> Also, we want to record how long it took when the GET claims succeeded. We'll have that data in the FE and it'll be rough numbers, like 5s, 10s, 15s, etc. Is that something we can track?

Sure - I can add this as a custom dimension or metric.

What's a good name for this parameter?  `api_return_time`?  `api_time`?

**Comment by erikphansen** [comment]
Thanks for your response, @bsmartin-ep . I'm super excited about actually being able to get some insight into how this Claims API is performing!

Responses below:

> > I don't think we'll fire events when we make a call, at least when getting claims, because this call could be made every five seconds for 30 seconds. Yeah it's a weird endpoint.
> 
> Would we see API return events every 5 seconds?  Or those would be less frequent?

We'll only send events when we actually get the claims data or there is an error getting claims data. So if the FE calls the API five times, we'd only send one event to GA:
1. pending - no GA event recorded
2. pending - no GA event recorded
3. pending - no GA event recorded
4. pending - no GA event recorded
5. claims data received! - send `successful` event to GA

> What's a good name for this parameter?  `api_return_time`?  `api_time`?

Maybe `api_latency` or even `api_latency_ms`? So if it takes 20s (a total of 4 API calls) to successfully get claims data, we'd send a single event like:

```
{
     event: 'api_call',
     api_name: 'GET claims',
     api_status: 'successful',
     api_latency_ms: 20000 // Can this be a number or would it have to be a string?
}
```

**Comment by erikphansen** [comment]
@bsmartin-ep I think that the only thing we need an OK from you on is how to handle the _optional_ parameter that'll track how long it took to get data from an API. Will a key of `api_latency_ms` work? And can we pass in numbers or does GA only support strings?

I'm starting to code all of this today but it'll be easy for me to adjust this stuff if you veto this design.

**Comment by erikphansen** [comment]
@bsmartin-ep I've actually got a couple more questions about these events we are sending.

1. I'm not seeing any other places in the `vets-website` repo where we are sending events with `api_name` keys. Is this the first time the new `api_name` event is being used?
2. The use of underscores in key names seems a bit odd since we normally use `-` in the key names. I just want to make sure you really want underscores in these new event objects.

Thanks!

**Comment by bsmartin-ep** [comment]
Apologies for the delay @erikphansen.

`api_latency_ms` with an integer value sounds good to me.  I'll get a Custom Metric added to GA for this.

> Oh! And would it also be possible to pass in this new api_latency_ms key when a call fails?

Definitely - I'm going to include this Custom Metric for every API event, so feel free to pass it in for all of them.

 > I'm not seeing any other places in the vets-website repo where we are sending events with api_name keys. Is this the first time the new api_name event is being used?

Correct.  We currently have a separate GTM tag for every API call (due to the product prefix in the event name).  Thinking ahead though - especially for the move to GA4 - we'd like to have a global API event with event parameters being the differentiator.  

> The use of underscores in key names seems a bit odd since we normally use - in the key names. I just want to make sure you really want underscores in these new event objects.

I've actually gone back and forth on this.  Google [seems to like underscores](https://support.google.com/analytics/answer/9216061?hl=en) and it doesn't require us to quote the key names in code.

But also always down for following the standard.  Thinking I cut over to `-`?

**Comment by erikphansen** [comment]
Underscores are fine if that's what Google considers idiomatic. [It does require us to disable an ESLint rule](https://github.com/department-of-veterans-affairs/vets-website/pull/17878/files#diff-fe0dff57b4f73ab23e943a28112a893eeda349ad1c5c6fe08b79242ad7cdb0dfR309) in our FE code because it is _not_ idiomatic JS :) And also introduces potential confusion since most of the keys use a hyphen and probably always will?

**Comment by erikphansen** [comment]
I don't really have a vote in this, but I'd push towards sticking with using hyphens in the key names, unless there was a plan to convert all the existing hyphenated keys to use snake_case.

**Comment by erikphansen** [comment]
Hey @bsmartin-ep. I just need a final confirmation on using `snake_case` or `kebab-case` event key names and then I can get [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17878) merged in. Thanks!

**Comment by bsmartin-ep** [comment]
@erikphansen - Let's go with `kebab-case`.

**Comment by erikphansen** [comment]
Sounds good. Thanks!

**Comment by laurensimpson14** [comment]
GTM changes look good 👍 (see QA screenshots below). I just published the changes live, so you should see data flowing in later today. 
|QA Screenshots| QA Status|
| - | - |
|![image](https://user-images.githubusercontent.com/80417436/126686110-cd3ec6e2-ef1b-4dca-86ef-fb820b87ef3e.png) 
![image](https://user-images.githubusercontent.com/80417436/126686132-47b83351-557f-40ff-962b-96e4822fd9ca.png)| 🟢 Tracking Correctly|

**Comment by ajakabcin** [comment]
Hey @bsmartin-ep and @laurensimpson14 thanks again for your help on this yesterday. I'm actually still not seeing data flowing through on those widgets unfortunately. Anything else we need to do here?

cc @erikphansen

**Comment by bsmartin-ep** [comment]
@ajakabcin -

I messed up the first regex.  That widget is looking good now.

Not seeing any error keys with the failures.  Looking at that now...

**Comment by bsmartin-ep** [comment]
Should every API failure have an `error-key` attached @erikphansen?

**Comment by erikphansen** [comment]
@bsmartin-ep yes, I'm sending a string for the `error-key` :-/

The dashboard widget is also not showing the `api-latency-ms` data I'm sending when the API calls are successful. Is that something that can be added?

**Comment by bsmartin-ep** [comment]
@erikphansen -

Latency has been fixed and added to the dashboard.  We should see data shortly...

https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/_u.date00=20210725&_u.date01=20210725/

I also found the issue with `error-key` but I'm a little concerned with the error key bleeding over to new events.  I think our best best bet is to add this after the `recordEvent`.

```js
recordEvent({
     'error-key': undefined,
});
```
https://github.com/department-of-veterans-affairs/vets-website/blob/3ac2bd50517b58766d56bdc4dbfd4766e42a79a8/src/applications/claims-status/actions/index.jsx#L212

**Comment by bsmartin-ep** [comment]
@erikphansen -  I'm seeing data not, but the majority of error keys are "unknown".  Is that expected behavior?  OK to close this?

![image](https://user-images.githubusercontent.com/62304138/127233358-58832399-b1b5-4690-9647-b7662fcd5bd0.png)

**Comment by erikphansen** [comment]
I'd have to look into why we are sending `unknown`, but that's almost certainly a problem on my end not yours.

But, I was really hoping to see the API latency as a table. We are only sending latency as multiples of 5000, so we should be able to have a nice table showing how often the latency was 5000ms then 10000ms then 15000ms, etc.

**Comment by bsmartin-ep** [comment]
@erikphansen -

Ah - unfortunately the GA interface won't let us break down Custom Metrics into a hit-level distribution table.  Just the total or a calculated average like we have now.

Some options...

1. You can move this table our of the GA web interface and into something like Datastudio or Domo.  Either of those we can connect to BigQuery and look at these metrics at the hit level.
2. I can move this to a custom dimension (vs a metric).  For this one, we would **not** be able to get an average in the GA interface (but we could in BigQuery).

**Comment by joanneesteban** [comment]
@erikphansen we'd like to move to the first option that @bsmartin-ep shared above. Let us know if you have any questions!

**Comment by bsmartin-ep** [comment]
@erikphansen - GA is a bit dumb with sorting dimensions, but I added your data your dashboard:

https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/_u.date00=20210908&_u.date01=20210908

![Screenshot from 2021-09-08 10-45-33](https://user-images.githubusercontent.com/62304138/132531742-fb350357-7b0c-4e5e-b3d7-86453fa6e299.png)

OK to close this out?

**Comment by erikphansen** [comment]
Looks good enough to me!
