### ISSUE TITLE
Add deprecation warnings on unused v0

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26707]
## Tasks
- [ ] Add deprecation warnings on unused v1 controllers 
- [ ] Coordinate with lighthouse on client (not in our engine)

## Acceptance Criteria
- [ ] V0 pathways have deprecation warnings
- [ ] warnings are dated so code can be sunset

**Comment by mmiddaugh** [comment]
Lance is working with VSP to determine a better process for communicating deprecations
