### ISSUE TITLE
Design intent Decision Tools - Discharge Upgrade Wizard change PDF form link to Air Force portal link

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26700]
## Steps to complete Design Intent Collaboration
- [X] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [X] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/readme.md)
- Whiteboard sketch or other lo-fi prototypes or wireframes     **N/A - iteration to an existing product**
- User flow  **N/A - we are changing only one page in the existing flow.**
- Any other artifacts you have so far: Collaboration on the design and content can be seen in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23591

Prototype: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23591#issuecomment-869962809

## Meeting attendees from requesting team
- Designer(s) (required): Cassandra Allen
- Product Manager (required):  Marci McGuire
- OCTO-DE Design Lead (required): Ryan Thurlwell
- OCTO-DE Product Lead (recommended): John Hashimoto
- VFS content, IA, accessibility, and QA specialists (if applicable): name(s) 
   - Mikki Northius
   - Beth Potts
   - Peggy Gannon
   - Tze-chiu Lei
   - Trevor Pierce
   - Josh Kim
   - Angela Fowler
- Other stakeholders you want to invite (if applicable): N/A

### What is your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
**Wed July 7 at 11:30 AM**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility, and IA only. You won't receive feedback from content and QA, as it's too early in the development process.

Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@MarciMcGuireGCIO Wednesdays are actually our collab cycle office hours. You will want to look at the times that have [Review block]. Would Tuesday July 6 at 11 or 11:30 work?

**Comment by MarciMcGuireGCIO** [comment]
Oh, sorry about that.  Jul 6 at 11:30 will work.  Thank you!

**Comment by allison0034** [comment]
This has been scheduled for July 6 at 11:30

**Comment by MarciMcGuireGCIO** [comment]
Thank you! 😸

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO i don't see a Collab Cycle Kickoff ticket for this work. Did you submit one? If so, can you please send me the link? Thanks.

**Comment by MarciMcGuireGCIO** [comment]
I am looking.  I have a list of the touchpoints, but I can't find it either.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman -- AHA! Found it!  https://github.com/department-of-veterans-affairs/va.gov-team/issues/23279.

**Comment by shiragoodman** [comment]
thanks @MarciMcGuireGCIO !

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman you're welcome!  Was starting to think I was imagining things! 😆
