### ISSUE TITLE
Create Integration for New BIP/BID Service to Determine if Veteran Currently Receives Pension

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#26716]
## Description
BGS created a new service to determine whether or not the Veteran is currently receiving pension benefits when a 686/674 is submitted.  VA.gov needs to integrate with BIP/BID in order to access this new service.  Currently, we can only access the service when on the VA network.  We need to configure the settings so that `vets-api` can access this new service from BGS.

## Tasks
- [x] Meet with Charley
- [x] Get URL(s) from Shane
- [x] Update devops repo with new configuration settings
- [x] Update `vets-api` with new config
- [x] Test connectivity between `vets-api` and new pension service

## Considerations
- Does the BID service exist in prod yet?

## Acceptance Criteria
- [x] Network integration with the BID service (for determining if a Veteran is eligible for pension) is in place
- [x] A PR has been submitted for merging

## Next steps
- Establish ticket for writing it out for `vets-api` (new ticket added #26831)

**Comment by kathleencrawford** [comment]
Update 07/06/2021: Connection established through DEV!  Currently just in terminal session, not tested via vets-api yet (code needs to be added).

**Comment by jason-gcio** [comment]
#26831 is next
