### ISSUE TITLE
Sitemap Plug-in Updates

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26726]
##  Description
Update sitemap generation tool to more accurately display updated at date

## Background/Context
- Change Sitemap dates from Published to Edited #22980

## Tasks
- [x] investigate current sitemap generation tool to see if published date can be changed to updated date
- [x] if current tool can not be updated, fork existing repo and update to enable date change.

## Acceptance Criteria
- [ ] Validate  forking / remaking the tool is what we need to do.
- [x] New tool is able to generate the sitemap and as a result we are now able to update the dates

**Comment by srsuddath** [comment]
This issue has been merged!

Unfortunately due to our build process, there were only minor improvements that can be made to the lastmod date
