### ISSUE TITLE
Research and Implement Visual Regression Testing Dashboard MVP

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26732]
## Product Outline
TBD

## High Level User Story/ies
As a dashboard implementer, I need a well defined set of acceptance criteria for the visual regression testing dashboard MVP, so I can create the dashboard that would be most valuable for all stakeholders.

As a dashboard implementer, I need to create an MVP of the dashboard.

## Hypothesis or Bet
**If** we create a dashboard to visualize important Product Support data  **then** the Platform will attain new insights into the efficiency, efficacy, and pain points of the Collaboration Cycle.

## OKR
TBD

## Definition of done
- [ ] Research the data visualization needs of Product Support
- [ ] Implement a dashboard MVP
- [ ] Usability test the MVP with stakeholders
- [ ] Release refined MVP
