### ISSUE TITLE
Redesign Search/Appoint Rep screens to reflect latest design/functional feedback

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#26753]
### Background
The search and appoint representative tools will require redesign to address recent design feedback, form system implementation, and functional/submission form changes (printable PDF).

### Tasks
- [ ] Separate search and appoint features
- [ ] Use form system components for screen designs
- [ ] Consider printable PDF functionality vs. electronic submission of 21-22/a
- [ ] List inbound screens and landing pages/include tool-card 
- [ ] Update mockups

### Acceptance criteria
- [ ] Revised mockups available for search function
- [ ] Revised mockups for 21-22/a form
