### ISSUE TITLE
Update burial benefit answer on burial allowance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26751]
## Issue Description
Stakeholders requested a change to a Q&A on the [how to apply for a Veterans burial allowance](https://www.va.gov/burials-memorials/veterans-burial-allowance/) page due to a Congressional response that was issued. 

Suggested edits:
[https://app.zenhub.com/files/133843125/6c8a7fe4-7237-4563-a7bd-7e5961e655ad/download](https://app.zenhub.com/files/133843125/6c8a7fe4-7237-4563-a7bd-7e5961e655ad/download)

We need to rework the text for plain language and to maintain our voice and style. 

## Tasks
- [x] Update text on page
- [x] Send to stakeholder for approval
- [x] Review and publish

## Acceptance Criteria
- [x] New content is live on site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Would you copyedit this plain language version of what they provided? And let me know if you think I retained their intended meaning. Then you can go ahead and send them the preview link:

**What kind of burial benefits can I get?**

If you’re eligible, you may receive these benefits:

- VA burial allowance for burial and funeral costs
- VA plot or interment allowance for the cost of the plot (gravesite) or interment
- VA transportation reimbursement for the cost of transporting the Veteran’s remains to the final resting place

**Note:** You can receive these benefits only if you’ve paid for any of these costs.

**Comment by RLHecht** [comment]
All looks good to me. I put it into Drupal and sent the preview link to Angie.

**Comment by RLHecht** [comment]
Angie approved the changes and the page is published. Moving to validate and will close after it's live on the site.

**Comment by RLHecht** [comment]
Live on site. Closing ticket.
