### ISSUE TITLE
Preprod Testing

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26769]
## Background
Per https://github.com/department-of-veterans-affairs/va.gov-team/issues/25698

## Considerations
- [ ] pick a user 
- [ ] get the info we need from preprod (participant ID, check SSN) 
- [ ] ask IM to update that user (can Trevor help with this?)
- [ ] test

## Tasks
- [x] PLACEHOLDER for PREPROD testing with BGS/Pension folks

## Acceptance Criteria
- [x] Reserve for the flood of meetings that we will potentially have with PREPROD testing 

**Other steps to consider if needed**
- [ ] The mockdata file works and the rest can be created in order to test in preprod
