### ISSUE TITLE
Evaluate Applitools in Greater Detail

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26763]
# Description
Let's dig into more details with Applitools. We will modify an existing Cypress spec to use Applitools for Visual Testing.

## Task
- [x] Contact Applitools regarding use and price (~17,000 screen shots per month)
- [x] Create a trial account in Applitools
- [x] Add Applitools dependency to vets-website and modify 1 or 2 Cypress specs to use the Applitools API to screenshot
- [x] Evaluate the review process in Applitools Cloud app

**Comment by holdenhinkle** [comment]
I got Applitools working with Cypress tests locally.

PR - https://github.com/department-of-veterans-affairs/vets-website/pull/17736

I reached out to them to find out what pricing is for ~18k images a month and they wanted to setup a meeting:

> Pricing for Applitools is based off of consumption. I would be happy to set you up for a quick call with my colleague who can give you pricing and answer any questions you may have. What timezone works best for you?

Peter and I are meeting with them tomorrow (Thursday, the 1st) at 10:30am.

**Comment by holdenhinkle** [comment]
Links:
- https://www.npmjs.com/package/@applitools/eyes-cypress
- https://applitools.com/tutorials/cypress.html
- https://github.com/applitools/tutorial-cypress

**Comment by pjhill** [comment]
Evaluation is complete.
