### ISSUE TITLE
[VAMC] Go - Live Pre-analysis for System going into Full producction [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26775]
## Story
As an editor I need to know of any additional final clean up items and barriers, so I can clean them up prior to Go Live

## Goal
Determine and record any issues that may still be outstanding and recommended for change by the PAO.  

## Task
- [ ] Walk system through Go-Live/Full Production Run book and document any discrepancies.
- [ ] Report discrepancies to VHA DM and PAO for resolution
- [ ] Report and document any launch blockers

## Acceptance criteria
- [ ] Recommendation sent to VHA digital media
- [ ] Areas of discrepancy are reported to PAO for resolution
- [ ] Launch blockers are reported to correct area for resolution and if unable to resolve the site is pulled from Full Production Schedule.
