### ISSUE TITLE
[Analytics] Review CMS support desk analytics and compare to  Production Q&A documents  [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26779]
## Issue Description
As a editor I need a knowledge base or FAQ, so I can review issues and/or find answers to my problems there first before contacting the help desk.

## Goal
Find common issues and then categorize them so common answers can be determined and provided.
---
## Tasks
- [x] Pull data from CMS Support desk and categorize and relate to common solution area (e.g., training, editorial issue, etc)
- [ ] Compare and consolidate data with data taken from Production Q&A
- [ ] Provide New data in an artifact that can be provided to Product owner and CMS

## Acceptance Criteria
- [ ] Both CMS support desk and Production Q&A are used as basis of data mining
- [x] Artifact is created that outlines categories and examples of issues, provides support type, and what the solution provided was for that issue.
