### ISSUE TITLE
[VAMC] Go - Live Pre-analysis for System going into Full producction [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26787]
## Story
As an editor I need to know of any additional final clean up items and barriers, so I can clean them up prior to Go Live

## Goal
Determine and record any issues that may still be outstanding and recommended for change by the PAO.  

## Task
- [x] Walk system through Go-Live/Full Production Run book and document any discrepancies.
- [x] Report discrepancies to VHA DM and PAO for resolution
- [x] Report and document any launch blockers

## Acceptance criteria
- [x] Recommendation sent to VHA digital media
- [x] Areas of discrepancy are reported to PAO for resolution
- [x] Launch blockers are reported to correct area for resolution and if unable to resolve the site is pulled from Full Production Schedule.
