### ISSUE TITLE
Prepare Pact for Launch in GHA

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26799]
# Description
Pact has been sitting relatively unused for some time. Now that we are on the verge of launching the GHA pipeline for both vets-website and vets-api, we need to ensure that the documentation and release plan are up-to-date.

## Tasks
- [x] Verify that Pact documentation correctly refers to the CI/CD pipeline hosted in GHA
- [x] Ensure that Pact documentation informs VFS teams how to access the state of their contracts in GHA / Pact Broker behind basic user auth
- [x] Ensure documentation informs teams of how to contribute and maintain contracts with Pact
- [x] Update the [documentation](https://vfs.atlassian.net/wiki/spaces/RELDEP/pages/687931536/Contract+testing) for Pact to refer to resources on the Platform Website instead of GitHub

**Comment by CBonade** [comment]
Copied over the `Using Pact for Contract Testing` page.  Started verifying contents and tracking down exactly how it relates to our current workflow.  Learned how to use Confluence!

**Comment by CBonade** [comment]
Have verified all documentation listed above is present and accurate to the current procedure.  The page exists in Confluence here: https://vfs.atlassian.net/wiki/spaces/TTT/pages/1793949843/Using+Pact+for+contract+testing+on+VA.gov

This is the first link that needs to be changed on the existing platform website documentation (it currently links to github).  The second link is an anchor link to this same page.  Link 3 is the documentation for pact which has not changed. Link 4, is to the pact broker, which needs to be updated to https://dev.va.gov/_vfs/pact-broker/.  

Once this page is reviewed and approved for accuracy, I can move it over to the platform website space and update the links on the main documentation page accordingly.

**Comment by CBonade** [comment]
These documentation updates are complete and published. They're currently sitting in live preview, pending approval of other updates to go live.

**Comment by CBonade** [comment]
These docs updates are now live on the platform website. https://depo-platform-documentation.scrollhelp.site/test-release/Using-Pact-for-contract-testing.689832148.html

**Comment by pjhill** [comment]
Looking good -- thanks for taking care of this!
