### ISSUE TITLE
[VAMC] Create csv file for VISN-15 Facility Health Services used to migrate into CMS Systems [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26790]
## Story
As a data editor and customer, unique system health services need to be pulled from the system playbook and migrated through an automated process, so the process is scalable and accurate.

## Goal
Create a repeatable process that will allow for scalable input into the CMS system via data migration

## Resources
[Previous csv files](https://drive.google.com/drive/folders/1jpxDn49L4NonSd6bxya4HZX6kC56fCna)
[CSV file creation instructions](https://drive.google.com/drive/folders/1iSzTuY3wDsGP4ZpQfh55C3CGVee_VnpC)

## TASKS
- [x] Follow Facility Health Service Directions to create a Facility csv file.

## Acceptance Criteria
- [x] .csv file created with required column headers to be uploaded into CMS
- [x] provide support and corrections to CMS engineer until PR is uploaded correctly with no errors.

**Comment by bcastoe** [comment]
#26790 - Create csv file for VISN-15 Facility Health Services used to migrate into CMS Systems [VAMC
