### ISSUE TITLE
Discovery research for Download VA benefit letters feature on VA.gov

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26811]
## Background
Usability testing of the new Certificate of Eligibility feature/design included wayfinding. Most participants expected to find their COE for VA-back home loans in the "Download VA benefit letters" feature. The benefits letters feature is not in active development.

The feature currently has a series of accordions that contain download link for various VA-issued documents. There is a link to the COE feature on eBenefits below these accordions.

There needs to be a "download your COE" accordion and link in-line with the other download-accordions.

[Download VA benefit letters feature on VA.gov](https://www.va.gov/records/download-va-letters/)

## Considerations
- There might be a place for just a link to COE vs dropping them in there

## Tasks
- [x] Review COE research readout recommendations (is the accordion where its expected to live?)
- [x] Document flow and functionality of current benefits letters feature (Diagram and/or Github)
- [x] Outline content/landing pages affected by change to benefits letters feature
  - E.g., make a note of conflicting sign-in instructions on the letters page for when EBN sunsets, anything sending Veterans to EBN
- [ ] Quick wireframe to address recommendations (may not be needed)

## Acceptance criteria
- [x] Current feature documented in Github
- [x] Feature flow diagram ready for review
- [x] Outline of affected content pages created
- [ ] Quick wireframe/notes on a screencap available, if applicable

**Comment by jason-gcio** [comment]
Check with Matt S on this as well

**Comment by jason-gcio** [comment]
Check in with Mikki if IA work has been completed on this feature yet

**Comment by sporeboy** [comment]
Download Benefits Letters documented in [this tool comparison here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-my-documents/research-design/mydocs-feature-comparison.md)

**Comment by sporeboy** [comment]
Github writeup for the [Download benefit letters tool here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/download-benefit-letters-discovery.md)

**Comment by sporeboy** [comment]
Added screen cap to Github doc. All AC met, ready to close.
