### ISSUE TITLE
**DECISION TOOLS SPRINT 51 PRIORITIES (6/30-7-13)**

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26823]
<hr>

## 📅 Team Project Calendar
[Link to calendar](https://calendar.google.com/calendar/u/0?cid=Y19nOXJmdXMxNHZudHV1bHF0bjFoOXA0Y2Znb0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) - **Shared - you can add/edit as needed**

## 🏖️ Sprint 51 Vacation/PTO/Holidays
- July 4 holiday (observed) - 7/5/2021
- Cassandra PTO - 7/7/2021
- Cindy PTO - 7/6 - 7/14/2021

### FIND A VA FORM Find a VA Form: Add Relevance, Popularity, Related Forms & UI consistency #21639
- [x] (Team) - Staging Review for Find a VA Form Search improvements, UI consistency, Related Forms links -  Friday 7/2 at 2:00 PM ET #26298
- [x] Mark - Promote changes needed for 7/7 go-live  #26826
- [x] Zach - Remediate any launch blockers identified in Staging review (TBD)
- [x] Zach - Promote to Prod with Feature Flags Tue 7/6 #26826
- [x] Zach - Remove feature flags Wed 7/7 #26826

### Find a Form Bug Fix 
- [x] Mark - fix for 10101 &  8824i issue

### FIND A VA FORM PDF DOWNLOAD INSTRUCTIONS, EPIC #26816 
- [x] (Cindy) - Draft research plan & convo guide: #25924 
- [ ] (Zach) - Implement "download PDF" instructions on search results & detail pages #25571 Note: Promote to staging by EOD 7/14 for Cindy to review - see [this Slack thread](https://dsva.slack.com/archives/C01DWJFD45D/p1624992684399100) for more info.   Should link to https://www.va.gov/resources/what-if-im-having-trouble-opening-a-pdf

### DISCHARGE UPGRADE WIZARD CHANGE PDF LINK FOR AIR FORCE RESPONDENTS, EPIC #24925
- [x] (Cassandra) **Discharge Upgrade Wizard** - Design intent review for changing PDF link to Air Force Portal link #26700 

### SEARCH UI CONSISTENCY, EPIC #21055

- [ ] (Cassandra)  - Stretch Goal **Search UI Consistency** - Document design pattern #24597

### DISCOVERY
- [ ] (Zach) - Download data from Yellow Ribbon API into Excel so we can see all fields/data available to us #26829

### TECH DEBT
- [x] (Zach) - #26761

###  🗨️  Discussion Topics/Grooming 
- [ ] Schedule time to discuss e-signature POC
- [ ] Schedule time to discuss Discharge Upgrade Wizard user experience with Beth
- [ ] Topic

**Comment by MarciMcGuireGCIO** [comment]
- Cassandra
   - Focused on Harassment Tool
- Zach
     - Tech debt for Discharge Upgrade Wizard

**Comment by MarciMcGuireGCIO** [comment]
Cassandra
- Mocking up use cases for Harassments tool

We pulled Angela into the discussion
- we'll add the ES attribute and ask them to re-check it. 

- Go to Online Tool would need to be translated into English, and Zach needs to know which translation of the word "for" to use.

- Zach will put the attribute on it and see what additional feedback we get.

- We will try to get with Josh first thing Tue AM 7/6 to see if he has further feedback/context on Zach's change.

**Comment by MarciMcGuireGCIO** [comment]
2021-07-06

- Find a Form changes went in this morning!
- Cassandra is working on Harassment tool

**Comment by MarciMcGuireGCIO** [comment]
2021-07-08

- Mark deploying fix for forms starting with VA to Staging.  Has full control over what time that goes in.
- For testing on Staging - send a handful of search terms
- Cassandra working on harassment tool; preparing for workshop tomorrow.
- Zach 
   - Merged work to fix ability to sort by closest match
   - Working on PDF alert box - messaged Cassandra on that
   - Can't override some of the web component library
- Find an hour with John next week to discuss eSignature POC
