### ISSUE TITLE
Document Type Selection for Each Upload

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26827]
## Background
As a veteran applying for a Certificate of Eligibility, I only want to upload the necessary documents pertinent to my case. I don't want to upload documents that my application may not be able to use.

## Considerations
- Based on the status of an applicant (veteran, service member, etc), LGY may require different types of documents related to their service history, loan history, or other factors tied to their service background. 
<img width="898" alt="Screen Shot 2021-08-30 at 1 33 52 PM" src="https://user-images.githubusercontent.com/15097156/131387698-b45661c0-a6a8-484d-baab-723d42f46704.png">
- [Mockup](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137611933/simulate/sitemap)

## Tasks
- [x] Read from existing form data for values that match criteria from different cases in above table
- [x] Conditionally render `ui:description` based on above values

## Acceptance Criteria
- [x] Conditional list has been implemented
- [x] A PR has been requested for merging
