### ISSUE TITLE
Remove SSN and VA File Number from CH31 (BE)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26822]
## Background
Instead of using the SSN from the form data, we should get it from the profile user object, so that we can limit errors or mistyped entries.

## Considerations
- Check on tests

## Tasks
- [x] Obtain the value from the user object, 
- [x] replace existing code to allow profile data to be passed through

## Acceptance Criteria
- [x] User profile is supplying values instead of form data
