### ISSUE TITLE
Create the Product Support Dashboard MVP

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26828]
# Description
Using the metrics and data sources defined in the [research effort](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/26825), create a Product Support focused dashboard that displays the identified metrics.

## Tasks
- [x] Create a DOMO card for each identified metric
- [x] Collect feedback about the dashboard from Product Support
- [x] Incorporate minor feedback from Product Support team
- [x] Create post-MVP tickets for major feedback from Product Support team

**Comment by JoeTice** [comment]
Here are some details for the first version of this dashboard

Dashboard Title: Collaboration Cycle Dashboard

Would like to have a pulldown menu, that allows you to filter the cards below by team:
- Default selection on the pulldown - [Platform Wide]
- If possible, lets ensure that the team list is created based on a source that will be automatically updated as new teams roll on

Card: "Collaboration Cycle Issues"
- Closed issues
- Open Non-Launch Blocking
- Open Launch Blocking

**Comment by rjohnson2011** [comment]
Created Collaboration Cycle Dashboard on Domo - https://va-gov.domo.com/page/1340527018
Added chart containing filter by team name for closed issues.
In the process of adding additional graphs from the ticket - non-launch & launch blocking.

**Comment by rjohnson2011** [comment]
Working on query to pull all labels of 'blocked' or not 'blocked' for each team name. Made good progress, should be moving on to populating Domo graphs tomorrow.

**Comment by rjohnson2011** [comment]
Dashboards are complete and visible at https://va-gov.domo.com/page/1340527018.
Notified Product Support via Slack for any suggestions/comments and awaiting feedback.

**Comment by JoeTice** [comment]
Feedback based on input from the Product Support team

- Change how the VFS Team List is being populated: Pull team list from the product support spreadsheet *NOTE* - Please be very careful not to modify anything in this spreadsheet, as a lot of things are tracked from this document
- Filter Out the Following Teams, so their tickets are not reflected in the charts – Contact Center, Design System, VA Mobile App, VA Notify (They say this is not currently on the list – so I don’t know that there’s any action to take on that last one at the moment)
-- Refine Open/Closed Issues – By Team
-- Stacked bar chart – Can we list ‘Closed’ first, and then ‘Open’?
- Is there a version of a stacked bar chart that also displays ‘Total’?
•	Refine/Change Open/Closed Launch Blocking/Non-Launch-Blocking Tickets – By Team
o	Use 2x Donut Charts
	Open vs Closed Launch-Blocking
	Open vs Closed Non-Launch-Blocking
o	Nice-To-Have
	Would like to have the ability to click on one of those pie chart categories, and get a list of tickets that match that criteria… I believe the Analytics team may have done something like that before, so if you ping them in their channel, they may be able to point you in the right direction
•	*NEW* Issues by Practice Area – THIS REQUEST IS PENDING INPUT FROM RACHAEL
o	Chart Type: Stacked Bar Chart
	Closed Issues - first
	Open Issues – second
o	Bar sets are based on practice areas

**Comment by rjohnson2011** [comment]
Needed to make some additional query modifications after rereading the requests to generate charts for Open vs Closed Launch-Blocking and Open vs Closed Non-Launch-Blocking. 
Generated the requested pie charts for the above. Reviewing and making final modifications to close out soon.

**Comment by rjohnson2011** [comment]
Submitted the revised changes requested by Product Support https://va-gov.domo.com/page/1340527018. Closing this for now, will reopen if any more changes are desired.
