### ISSUE TITLE
Work with Product Support Team to Identify Metrics

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26825]
# Description
As stakeholders in the creation of the Product Support dashboard, we need to understand the metrics that Product Support is interested in displaying in their dashboard MVP. We need to identify 5 or 6 metrics that Product Support wants to display, as well as the data streams required to gather the metrics.

## Tasks
- [ ] Meet with Product Support team to gather information about metrics and visualizations
- [ ] Take notes and attach to this ticket or a Google Doc that's linked here
- [ ] Identify the source of relevant data for the identified metrics
- [ ] Identify existing ingestion mechanisms that can be used to gather the data into BigQuery

**Comment by JoeTice** [comment]
Discussions have begun on this work, and Shira has provided some information for us to begin planning regarding GitHub labels - we will review and make additional tickets accordingly to begin tracking the labels and associated metrics.
