### ISSUE TITLE
Implementing the Pension Check

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26831]
## Background
Once the access has been established (after talking to Charley) we should start to build the actual code for Pension checks for each authenticated Veteran attempting to enter the 686c/674 application

## Story
The Pension line of business needs to be able to sort rejected applications based on whether they are for Pension applicants

## Considerations
- Make the call, we also need to update the claim label based on the value we get back (`PMC`?)

## Tasks
- [x] Update the 686 submission:
    - [x] If the status is `MANUAL_VAGOV` check if the Veteran is currently receiving pension benefits
    - [x] Update the claim type code to the appropriate claim type when creating the claim
- [x] Update the 674 submission:
    - [x] Check if the Veteran is currently receiving pension benefits
    - [x] Update the claim type code to the appropriate claim type when creating the claim

## Acceptance Criteria
- [x] The claim type label is using the correct rejection claim type when being set to `MANUAL_VAGOV`
- [x] A PR has been submitted for merging

**Comment by jason-gcio** [comment]
Making adjustment to this in another PR
