### ISSUE TITLE
Debt Portal - Add content for 75B debt

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#26838]
## Issue Description
_Veterans are mistakenly receiving notifications about owing 75b debts (represented as 'Chapter 33 Tuition, Fees, Yellow Ribbon – School Liable' in the DMC's deduction code spreadsheet). While the DMC troubleshoots why Veterans are receiving these notifications, we need to provide content in the portal letting Veterans know that they need too check with their school and that they cannot view the debt in our portal._

The content: 

>If you got an email about Chapter 33 tuition debt with code 75b
>
>This is a debt assigned to your school. You won't find it listed here. Before you make a payment on this debt, check with your school. They may have already paid. 

The alert:

![Screen Shot 2021-07-20 at 1.05.30 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/57c80c31-1610-4a42-aa78-118603e955b7)

[View the UXPin for reference on the alert's placement.
](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/140437273/simulate/sitemap?mode=i)

---
## Tasks
- [x] _Add the alert in alignment with the provided prototype_

## Acceptance Criteria
- [x] _The content has been updated in alignment with the provided prototype_
- [x] _UI has been reviewed by a designer_

**Comment by LindaLi123** [comment]
Need to confirm location with stakeholder

**Comment by LindaLi123** [comment]
This should be included in "additional debt"

**Comment by rileyorr** [comment]
Here's more context based on this morning's standup:

- Veterans are currently receiving notifications about owing an education debt under the 75b deduction code, but that deduction code is for _debt owed by educational institutions_
- Deduction code 75b's description based on the master codes Excel spreadsheet: 

> Chapter 33 - Tuition, Fees, Yellow Ribbon - School liable 

Questions I have:
- @LindaLi123 the outlined content states that these are letters Veterans are receiving; is this the only format they're receiving that notification (ie are they also receiving texts/emails?)? In standup, it sounded like they were receiving these notifications in either text or email format which is why DMC needs to discover where the issue is originating from. 
- Veterans don't understand deduction codes, so we write out the debt type's full name in the portal. Is there wiggle room to do the same with this alert so there's more context other than '75b deduction code'?

**Comment by LindaLi123** [comment]
@rileyorr I think we can just go with the text Jill provided for this one since it is expected to only be a temporary alert.

**Comment by rileyorr** [comment]
@LindaLi123 content on VA.gov needs to be reviewed by a content writer prior to going on the site to ensure we're following plain language guidelines; has this content been reviewed by a VSA content writer yet? I can help push the content along for review if you'd like!

**Comment by LindaLi123** [comment]
@rileyorr I don't think content writer has reviewed this, would you please push it for review? Thank you so much

**Comment by rileyorr** [comment]
@LindaLi123 I added Jill's proposed content to our Debt Letters UXPin and created a content review request ticket ([link](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27233))

**Comment by rileyorr** [comment]
@craigwheeler & @LinnJS I updated this ticket's description with the alert's content + where it should sit in the UI! It's ready to be added ASAP 

cc @LindaLi123 & @leahkeeler

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17952) where this work is being done.

**Comment by LinnJS** [comment]
@LindaLi123 bumped this ticket to a 5 since its going to need a complete accessibility 508 review before going to prod and will likely take an additional day.
