### ISSUE TITLE
Research Relevant Metrics for Visual Testing

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26840]
# Tasks
- [ ] Reference common industry metrics for visual testing.
- [ ] Scan Visual Testing offerings for common metrics
- [ ] Brainstorm ideas for metrics with stakeholders
- [ ] Synthesize information from all sources into a set of 5-6 metrics that we deem high value
- [ ] Define the 5-6 metrics in detail in this ticket
