### ISSUE TITLE
Iterate on Cards for Contract Testing Dashboard in DOMO

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26847]
# Tasks
- [ ] Socialize the Contract Testing Dashboard MVP
- [ ] Collect feedback from stakeholders
- [ ] Generate stories from collected feedback
- [ ] Prioritize tickets with stakeholders
- [ ] Work stories in prioritized order

**Comment by pjhill** [comment]
OBE
