### ISSUE TITLE
Create MVP Cards for Visual Testing in DOMO

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26841]
# Tasks
- [ ] Create cards from the raw data ingested into BigQuery that visualize the 5-6 defined metrics
- [ ] Solicit feedback from stakeholders
- [ ] Iterate on cards until the visualization stabilizes
- [ ] Finalize MVP and share the dashboard with stakeholders
