### ISSUE TITLE
Iterate on Cards in DOMO

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26842]
# Tasks
- [ ] Socialize the Visual Testing Dashboard MVP
- [ ] Collect feedback from stakeholders
- [ ] Generate stories from collected feedback
- [ ] Prioritize tickets with stakeholders
- [ ] Work stories in prioritized order
