### ISSUE TITLE
Beta Program 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2685]
We'll use this epic to track the progress for Beta Program

## What is it?

Enrolling in this beta program gives enrolled users access to the new combined account & profile for a period of time so that we might solicit feedback and insure the feature is no only working but satisfying the user.

## Why are we doing this?

Provide a limited set of users early access to new tool in order to understand:
- Are there bugs? (As a user with XYZ data, this feature should work and it doesn't.)
- Ease of use (As a user, I found it pretty intuitive or not to interact with this tool.)
- Usefulness/Relevance (As a user, these new tools help me.)

## How long will it run?

Beta can run for 2-4 weeks, depending on how long it takes to confirm that enough users have tried it. We will be using our feedback forum plus Google Analytics to monitor this. At 2 weeks, the team will make a call to continue beta for another 2 weeks or end it. 

## Who can use it?

A user must meet the following criteria in order to enroll in the beta program:
- Is a Veteran
- Has previously signed into VA.gov with an LOA3 account, either via ID.me's IDP process, or a DS Logon or MyHealtheVet premium account
- Has a record in MVI

## How will users find out about the beta program?

We will notify users about the beta program via an on-site notificaton.  Once the beta program is live, users who sign into VA.gov and meet the criteria above will see the above mentioned notification to participate.

## How will users enroll in the beta program?

The notifications above will link to a unique enrollment page URL that will allow users to opt-in to the beta program. Navigating directly to any of the beta tool URLs will also redirect qualified users to this page.

When enrolling from this page:
- If a user is not signed in, they will be prompted to do so in order to enroll, once enrolled they are directed to the beta profile page
- If a user signs in and meets the enrollment criteria, they will be enrolled and directed to the beta profile page
- If a user signs in and does not meet the enrollment criteria, they will not be able to opt-in and should receive some gentle off-boarding back to the hompepage (or where they came from if not the homepage)

## What will users experience when enrolled in the beta program?

- A user who enrolls will be redirected to the beta profile and see the new beta application.  In this case, the beta profile page
- Throughout the program, users will have an opportunity, through an on-site prompt, to provide feedback on their beta experience. Users may provide feedback as many times as they want. 
- When the team determines it has received sufficient feedback and addressed necessary changes, the beta MVP tools will be rolled out to production for public access. 

## How will users opt-out of the beta program?

- Once a user opts in, they will have an option to return to the original (non-beta) version of the feature and should receive gentle off-boarding that includes an option to stay in the beta program.

## How are we evaluating the beta program? 

- Throughout their beta experience, users will have an opportunity to provide feedback through a feedback-collection mechanism. This feedback will be reviewed throughout the process to give designers/engineers an opportunity to course-correct if users are encountering recurring issues. 
- Users will be given an opportunity to provide an email address in the feedback mechanism, in case they want to talk to one of the team members about their beta experience. Depending on how many people opt to provide an email, we can set up individual calls, or we can do a webinar. 

## How else will be monitor performance?

- Throughout the beta process, the team will monitor and analyze Google Analytics traffic, funnels, and events. 

## What happens when the beta program is over?

- All enrolled and non-enrolled users will be directed to the now live application.

## Discovery

- [ ] Beta Program 

## Project management

- [ ] Create product outline 
- [ ] Determine analytics approach 

## Information architecture

- [ ] Create content inventory of what needs to be included in the Beta Program
- [ ] Propose IA. 

## Design

(List is still a WIP)

- [ ] Create mockups of the new beta program
- [ ] Conduct usability testing 
 - [ ] Create research plan & kickoff recruiting 
 - [ ] Create conversation guide 
 - [ ] Conduct sessions 
 - [ ] Create report and tickets 

## Build

(List is still a WIP)

- [ ] Technical discovery 

## Pre-launch

(List is still a WIP)

- [ ] QA
- [ ] 508 accessibility testing

We'll track additional pre-launch tickets here.

**Comment by lkoenigsberg** [comment]
@Justin-Pickett , since this program is on hold for now might this be moved to icebox?

**Comment by Justin-Pickett** [comment]
@lkoenigsberg that makes sense. We'll revisit this when it is ready to be back in rotation.

**Comment by Samara-Strauss** [comment]
I'm going to close this. I think this is officially out of the purview of this team. Any further beta functionality from what we already have (feature gating) would likely be handled by the platform team.
