### ISSUE TITLE
Retest Leadership url change and feature flag

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26877]
## Issue Description
As part of [the runbook](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5500) for the Leadership url change, we need to retest the fix and the feature flag. 

Related to 

- [Change hardcoded Leadership menu link va.gov-team#25606](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25606) 
- Fix - [Change hardcoded Leadership menu link, check cms feature flag content-build#276](https://github.com/department-of-veterans-affairs/content-build/pull/276)

---
## Tasks (TBD)
- [ ] rebuild tugboat instance
- [ ] test front end changes

## Acceptance Criteria
- [ ] changes made to url:  `/pittsburgh-health-care/leadership` to` /pittsburgh-health-care/about-us/leadership` are reflected in tugboat environment
- [ ] CMS can update Leadership List URL alias pattern.

**Comment by brangi** [comment]
all do this as soon as I can  but anyone can do this as well.
