### ISSUE TITLE
Update urgent care mashup UI to be consistent with emergency care mashup

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26886]
## Issue Description
Elements of the  emergency care mash-up are slightly different than the urgent care mash-up implementation based on a review of analytics and Veteran feedback. We need to update the urgent care mash-up for consistency and usability. 

## Background 

**1. Analytics for click through on the urgent care benefit alert indicate use dropped off shortly after implementation** 

<details>
<summary> June 2020- June 2021 clickthrough </summary>

![image](https://user-images.githubusercontent.com/55411834/124168518-7f295f00-da62-11eb-90c3-e8183f27fe43.png)

</details>

**2. Recommendations from Nick's emergency care research**

- Most participants did not recognize the link as access to additional information, so using more explicit language may make it more recognizable as a call to action (Ex: "View emergency benefit information")
- Change "In-network emergency care" under Facility type, to "Emergency care"
- The "In-network emergency care" label introduced confusion. When juxtaposed with the other ‘Facility type’ dropdown options, which do not have the “in-network” label, some participants felt it was out of place, and suggested changing it to be similar to other options.

## Current urgent care experience
Service type dropdown options
- All urgent care
- VA urgent care
- Community urgent care providers (in VA's network)

Benefit label =`In-network urgent care benefit`

## New emergency care experience

Service type dropdown options
- All in-network emergency care 
- VA emergency care
- In-network community emergency care 

Benefit label =`In-network emergency care benefit`

---
## Tasks
- [ ] Update urgent care service type dropdowns
- [ ] Update urgent care benefit alert label 

## Acceptance Criteria
- [ ] When facility type = `Urgent care`, the service type dropdown options are  
       - `All in-network urgent care `
       - `VA urgent care `
       -` In-network community urgent care `
- [ ] When facility type = `Urgent care`, and search results are in-network community care locations, the urgent care benefit alert label is `Learn about your in-network urgent care benefits`
- [ ] analytics for click through are maintained
- [ ] all other functionality is maintained

**Comment by mmiddaugh** [comment]
Decision: We will not change Community providers (in VA's network) or Community pharmacies (in VA's network) for now. (Likely we will move toward a Pharmacy mash-up by the end of 2021)

**Comment by mpelzsherman** [comment]
Blocked because we can't test in review environment due to an issue with the vets-api.

See https://dsva.slack.com/archives/CBU0KDSB1/p1629469808215100
