### ISSUE TITLE
TUD -  Fix TUD backend mounting

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#26888]
## Issue Description
The current setup for the TUD backend on vets-api uses an environment variable conditional to mount the `test_user_dashboard/tud_accounts` endpoints (in `config/routes.rb`).  This should probably be moved to the `settings.yaml` for the staging environment only as the current setup only allows the route in production.

---
## Tasks
- [x] Change the `Rails.env.production` for the `test_user_dashboard` endpoint
- [x] Verify `test_user_dashboard/` endpoint is mounted in staging

## Acceptance Criteria
- [x] `test_user_dashboard` endpoint is mounted in staging
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
Change to add proper setting to staging environment: https://github.com/department-of-veterans-affairs/devops/pull/9555

**Comment by AGarcia-Clarity** [comment]
Closed by #26888
