### ISSUE TITLE
Create Synthetic Monitors Based on Research with Stakeholders

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26883]
# Description
Using the list of monitors gathered during [research](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/26881) create a suite of synthetic monitors. Instructions for creating synthetics within the infrastructure created by Ops is available [here](https://github.com/department-of-veterans-affairs/devops/blob/master/scripts/aws-canary-scripts/readme.md).

## Tasks
- [x] Create one ticket for each monitor and attach to this epic
- [x] Prioritize monitors with stakeholders
- [x] Work tickets in priority order

**Comment by rjohnson2011** [comment]
Looking into Canary with recent AWS permissions and how to test while triggering alerts silently. Reaching out to #platform-team to get all desired requirements for next iteration of synthetic testing.

**Comment by rjohnson2011** [comment]
Wrapping up [Refactor Staging & Production Canary Checks](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/27095)))

**Comment by pjhill** [comment]
All stories have been completed.
