### ISSUE TITLE
TUD Notes field - Backend

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#26884]
## Issue Description
In order to better communicate the statuses, properties, things of note, etc., about individual test user accounts, a text `notes` field should be added.
---
## Tasks
- [x] Update the `tud_account` class in `vets-api` to include a `notes` field
- [x] Update the `vets-api` DB schema to include a `notes` column in the `test_user_dashboard_tud_accounts` table
- [x] Update the `test_users.csv` and `spec_users.csv` population lists to include a `notes` column
- [x] Add a backend route to handle PUT requests to update test user `notes` information

## Acceptance Criteria
- [ ] The `notes` field is included with other test user account information that is returned to the frontend TUD app
- [ ] A test account's `notes` field can be updated via the new vets-api route
