### ISSUE TITLE
Create a Self-Serve Process and Toolkit for VFS Teams to Create Synthetic Monitors

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26882]
# Description
Given that we have created tooling and processes for creating new synthetic monitors on the Platform, let's go the extra mile to package up the process for self-serve use by VFS teams.

## Tasks
- [x] Create documentation for VFS team use
- [ ] Test the documentation with VFS teams
- [ ] Create a communication plan to collect feedback and provide support

**Comment by holdenhinkle** [comment]
I flushed out the outlined for the document in the Google doc and reviewed it with Peter.

It's 4:42 and I have about 2/3 of the document completed in Confluence. Here's the link - https://vfs.atlassian.net/wiki/spaces/TTT/pages/edit-v2/1768161300?draftShareId=48f56fe7-ebd5-4825-bc0d-a2ba8b437eef

I should be able to finish this tomorrow (even though it's going to be a heavy meeting day).

**Comment by holdenhinkle** [comment]
This document is complete - https://vfs.atlassian.net/wiki/spaces/TTT/pages/edit-v2/1768161300?draftShareId=48f56fe7-ebd5-4825-bc0d-a2ba8b437eef

I'm going to share it with Bill Ryan in Devops now, for feedback/collaboration/etc....

**Comment by holdenhinkle** [comment]
Bill reviewed the document and it's good to go.

Slack thread - https://dsva.slack.com/archives/CJYRZK2HH/p1626886944075000

> Holden Hinkle  1 minute ago
> let me know when you make those few changes you mentioned, and i’ll update the doc right away.
> - give permissions to that directory in that s3 bucket
> - rename that IAM role
> - enable alarm configuration when adding module to canaries.tf

But, as it stands now, the doc is finished and usable.

**Comment by holdenhinkle** [comment]
I proofread this.

But it could use another once-over by someone else. Not only for grammar, spelling, etc., but for feedback.

**Comment by holdenhinkle** [comment]
Ryan reviewed the doc - https://dsva.slack.com/archives/C01CHAY3ULR/p1626900883353700

His feedback was positive.

**Comment by pjhill** [comment]
Documentation is in place, but we will not be broadcasting the availability of this process and document for now.
