### ISSUE TITLE
TUD Notes Field - Frontend

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#26885]
## Issue Description
In order to better communicate the statuses, properties, things of note, etc., about individual test user accounts, a text `notes` field should be added. This field 

---
## Tasks
- [x] Update the account detail display to show the `notes` text
- [x] Add functionality for users to edit `notes` information
- [x] Add PUT call to `vets-api` to update a test account's `notes` information

## Acceptance Criteria
- [x] Users of the TUD app will be able to view & edit `notes` information for a test user account
