### ISSUE TITLE
Check-in Error Message Wording

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#26880]
## Description
We need to notify Veterans when things don't go according to plan during check-in. 

Danielle Thierry and Kristen McConnell took an initial pass on the following error states. Final wording they created is below.

**Unrecognized phone number**
[text message 1]We don’t have this phone number in our records. Try again using a mobile phone that’s in our records. If you need more help, ask a staff member or call us.

[text message 2] Find our phone number: [facility locator url]. If you’re in crisis, text 838255 for 24/7 confidential help.

**No appointments today**
We're sorry. We couldn't find an appointment scheduled for you today. Ask a staff member or call us for help. Find our phone number: [facility locator url]

**Multiple appointments today**
Our records show that you have more than one appointment with us today. Ask a staff member to help you check in for each appointment.

**Unrecognized text**
[text 1 of 2] We're sorry. Our automated system doesn’t understand your text. To confirm an appointment, reply CONFIRM. To cancel, reply CANCEL. To check in, reply CHECK IN.

[text 2 of 2] Questions? Ask a staff member or call %FACILITY_PHONE%. If you’re in crisis, text 838255 for 24/7 confidential help. To stop getting texts from VA, reply STOP.

## Tasks/Outstanding Questions 
- [ ] How is the %FACILITY_PHONE% determined in the Unrecognized Text scenario?
- [ ] Does it make sense to replace the facility locator link with %FACILITY_PHONE% in the No appointments today scenario? or should we only direct them to a staff member? or leave as is?
- [ ] What is the short code used for check-in also used for? Depending upon the answer, the Unrecognized text wording may need to be changed?
- [ ] Should the hints of CONFIRM, CHECK IN be removed from the Unrecognized text scenario. We don't want people to check-in before they actually can.

## Acceptance Criteria
TBD

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA and @Kennon-git For reference.
