### ISSUE TITLE
Vets-API to CHIP Authn/Authz

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#26899]
Tasks to be completed:

- [x] Setup the signed claims token for CHIP

- [x] Setup the Session handler for CHIP

- [x] Setup the Token object for data exchange between CHIP and vets-api

- [x] Setup the Redis handler for adding and retrieving tokens objects

- [x] Setup the request object to submit the claims token to the CHIP API authorization endpoint

- [x] Setup the claims token configuration

- [x] Wire up the CHIP API authentication code to the main Check-in module
