### ISSUE TITLE
Login.gov prototype mockup

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#26894]
## Issue Description
Create an interactive mockup on the Login.gov process for usability testing with Veterans.

---
## Tasks
- [x] Create a Figma prototype (interactive) for Login.gov usability testing
- [x] Create content based on feedback from content editors (VSA).

## Acceptance Criteria
- [x] Amanda signs off on the designed prototype
- [x] Verify functionality of what is requested
- [x] Sign off from Christine, Joe, Identity leadership
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Need sign off from Christine, Joe, and Identity leadership for overall design, last minute updates, content, etc.

**Comment by AGarcia-Clarity** [comment]
Update: 
- Updated prototype based on OCTOD leadership provided feedback.
- Updated prototype based on Identity team feedback.
- Awaiting feedback from Peggy G. (content team)

**Comment by AGarcia-Clarity** [comment]
Update:
- Peggy G. signed off on content.

**Comment by AGarcia-Clarity** [comment]
Update:
- Creating mobile view
