### ISSUE TITLE
Create a Revised QA Process for the Collaboration Cycle

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26922]
## Issue Description
VFS Teams do not have significant QA resources available to devote to QA processes and artifact generation for review in the Collaboration Cycle. Platform should create a revised QA process that requires less effort from VFS teams.

---
## Tasks
- [ ] Research and brainstorm a revised lightweight process with Testing Tools Team and Product Support
- [ ] Propose a draft document for the lightweight process
- [ ] Revise the draft document based on feedback
- [ ] Publish the final draft of the document to the Platform Website
## Acceptance Criteria
- [ ] The revised QA process requires less time and effort from the VFS teams
- [ ] The revised QA process is documented on the Platform Website
---

**Comment by shiragoodman** [comment]
@pjhill this was linked in the Value Matrix. Is this applicable for Testing Tools Team? or the Quality Assurance Standards team?

**Comment by pjhill** [comment]
> @pjhill this was linked in the Value Matrix. Is this applicable for Testing Tools Team? or the Quality Assurance Standards team?

Yeah, we will be addressing this on the QA Standards team, but we will have different tickets / initiatives under which we will pursue the work. It's probably safe to close this from a CC context.

**Comment by shiragoodman** [comment]
thanks Peter. I will be closing this ticket.
