### ISSUE TITLE
[Design] Remove gating for Original Claims

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2692]
## User Story or Problem Statement
As a first time disability claimant, after logging in, I need to be notified of how I can proceed with completing my Disability Compensation Claim if I do not have the required VA identification so that I can start the form.

## Goal
_A Veteran who is not able to have a CORP ID created because they are missing a BIRLS ID needs to be notified (before ITF) of how they can proceed with completing their 526_

## Tasks
- [x] _Error handling of CORP ID, but no BIRLS ID 
- [x] _Identify where the error should be displayed (ITF - Intent to File or SIP - Save in Progress)
- [x] _Identify what displays to user who is logged in and gets to gating but is missing BIRLS ID
- [ ] _(Technical) Add mock user

## Acceptance Criteria
- [x] Design of messaging identified and completed.

**Comment by kevinstachura** [comment]
@Mottie have uploaded designs to an Invision project: https://vsateams.invisionapp.com/share/JNUPVDECGFK

Added a couple notes on the screens - let me know if you want to talk those items through!

**Comment by kevinstachura** [comment]
@ndsprinkle take a look at the designs above (in the Invision link) for tech feasibility please and thank you sir.
