### ISSUE TITLE
Update National Guard eligibility info on home loan page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26933]
## Issue Description
Stakeholder Raleigh Contreras sent us a request for updated language on the [Eligibility requirements for VA home loan programs](https://www.va.gov/housing-assistance/home-loans/eligibility/) for the National Guard. 

In the table below, this is the proposed text to be added to the beginning of the "Any time period" section:

For members of the Reserve and National Guard: at least 90 days of non-training active duty service under USC Title 10 orders, **OR**
For members of the National Guard: at least 90 days of active service including at least 30 consecutive days under Title 32, Sections 316, 502, 503, 504 or 505, **OR**

![Screen Shot 2021-07-02 at 12.44.12 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/15c1b483-42d3-4b50-aaa5-867799d35824)

We need to review and if necessary rework for plain language. 

## Tasks
- [x] Update table with new content (Randi)
- [x] Review (Beth)
- [x] Send to stakeholders for review (Randi/Beth)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [ ] New content live on site

**Comment by bethpottsVADEPO** [comment]
@RLHecht I've been back channeling with Raleigh via chat, and he's trying to figure out how to message this without all the jargon. He was pushing for us to just put up the content with the jargon about titles/sections. But I said I'd rather wait until we have a more plain language approach--and that we'd send him a preview link with this approach of splitting out NG and Reserve info.

Let's try it this way:
3 accordions there instead of 2...

Just repeat the info that needs to appear in both NG and Reserve accordions. So, the labels for the 3 accordions will be:
- Service requirements for Veterans and service members on active duty
- Service requirements for National Guard members
- Service requirements for Reserve members

Let me take a look before we send to Raleigh. Thanks!

**Comment by RLHecht** [comment]
@bethpottsVADEPO I just added the third accordion and redid the bullets so that only National Guard requirements where in that accordion and Reserve requirements were in the other accordion. Take a look and let me know what you think.

**Comment by bethpottsVADEPO** [comment]
Looks good to me. Thank you for sending the preview link to Raleigh. We'll see if he thinks this works.

**Comment by bethpottsVADEPO** [comment]
I sent to Raleigh. We're just waiting to hear back about whether this solution works.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Looks like this is still outstanding? Want to ping Raleigh again?

**Comment by bethpottsVADEPO** [comment]
Update: We're blocked on this one because the SME isn't responding to our requests to approve the edits. We've reached out to him most recently on these dates:
1/12/2022
12/21/2001
10/19/2001

I'll escalate if we can't wrap this up this month.

**Comment by RLHecht** [comment]
I let the stakeholder know these are live. Closing ticket.
