### ISSUE TITLE
[Discovery] Notification settings: Develop an approach to orienting users

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#26946]
Our research shows profile may not be the first place Veterans look to manage notification settings. We need to determine how to best introduce this new feature on VA.gov to Veterans so they manage their settings.  What is the first time user experience? How do Veterans find this the first time?

Some ideas from Kevin Hoffman:

- Once launched, an interrupt alert or modal (gasp!) that says "You can now manage notifications from the VA..." and a CTA to "Set up my notifications preferences"
- Additional framing to the page that onboards them to basic changes, alerts them to limitations. That could be in page or a separate experience -- TBD. 

An onboarding approach may also be effective in helping Veterans understand the channels through which notifications are available.

**Tasks**
- [x] Learn how we have done this for other new features on VA.gov
- [x] Learn about approaches to this from other websites

**Acceptance criteria**
- [ ] Ready to start mock-ups

**Comment by andaleliz** [comment]
- I put together a [mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1627573596392/ff316d078711581807573a35cf49ba63bbb12037?sender=lizlantz1528) with some screenshots of various approaches other sites use, including tool tips, product walk-throughs, modals, and email campaigns.  
- I have not come across any common approaches on VA.gov to new feature or product orientation and onboarding.  Here's what I learned about what teams have done in the past wrt to a communication plan, or a marketing plan:
  - Modal on the tool page to tell users what has changed ([VAOS](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/27694) example)
  - VA blog posts (My VA launch did this)
  - On the UNsigned in experience, we have deployed a ‘new site’ modal upon landing when we launched the new VA.gov
  - Used this modal pattern when a new modernized VAMC site officially and fully goes live
  - For VAMCs and other new products like Find a VA forms, the internal comms has been to work with the relevant stakeholders and/or VACO web comms teams to issue a formal ‘hey it’s launched’ message to SMEs and stakeholder partners.
   - Sometimes that’s as simple as an email. Other times — like with VAMCs — it’s been much more ‘official’ (email plus a product fact sheet with change management instructions, e.g., from now on, use this URL instead of the old URL…).
  - We have never used this pattern on the unauth experience for authenticated functionalities being added. ([slack thread](https://dsva.slack.com/archives/CE4304QPK/p1628086316018600))
  - There is no official guidance from the product practice about launch strategy or communication.
  
 After all this knowledge gathering, my recommendation is to:
 - confirm that we NEED to do something to orient people.  I _think_ we do (because how else will they know), but since it doesn't seem that we've done this for most of the products and features we've launched, why do we need to do it for this? Is it perhaps better to wait until we roll out action items and announce them at the same time, or **through** an action item?
 - If we confirm that we do need to do something now,  I think we should leverage components we already have in the design system: the modal or an alert box. I'm interested in A/B testing to see which is more successful at driving traffic.
 - I propose we put the component on top pages people visit after they authenticate. My VA and Profile feel obvious, but it would be helpful to use analytics to see if there are any other places where it would make sense.  Is the homepage too bold (I think so)? Does it make sense to include an alert or modal on relevant content or tool pages, e.g. the VAOS confirmation page (Now you can get a text reminder about your appt...).  Should MHV include something about this in their notification settings section, since they have email equivalents to some of our alerts?
 
 @ajakabcin it'd be great to get your help with the first and third bullet points. How can we confirm whether or not we need to do this? And are there analytics to guide is if we do need to do this?

**Comment by andaleliz** [comment]
@ajakabcin let me know your thoughts on my questions above - I think those activities could be tracked in a separate ticket for you if you're up for helping out.  Otherwise I can continue the work in this ticket, but we'd likely need to carry it over to the next sprint (and increase the estimate).  Thanks!

**Comment by ajakabcin** [comment]
A lot of great info in here - thank you @andaleliz . I think we can close this ticket for now and pick back up with an approach in another sprint or two. We have #28127 and #27113 slotted for sprint 55 to follow up.

**Comment by tmitchellgcio** [comment]
Have we ever thought about looking at a "joy ride" tutorial for the new VA? Would this perhaps be an option? https://react-joyride.com/

**Comment by andaleliz** [comment]
@tmitchellgcio I think it definitely could be for something more robust than notification settings! I saw a lot of examples of things like that in my comparative analysis. In fact, I did think about just one tooltip to highlight the new navigation menu option in profile...but then what happens on mobile and the menu is collapsed? I'm sure we could solve for that but didn't give it much thought since I think the thing we really need to solve for is _getting_ people to notification settings from other parts of the site when they log in.  We'll certainly keep that joyride idea in our pockets for future releases.
