### ISSUE TITLE
Update Collaboration Cycle guidance to reflect change in Staging Review process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#26953]
## Issue Description
As we move our guidance and documentation over to Platform Website, Staging Review documentation will need to be updated to reflect the new process, as well as to address the VA.gov Experience Standards. 

## Updated Staging Review guidance should address:
- [x] Issue tickets are not to be closed until the issue is resolved. These tickets will be used to assess the health of VA.gov so it is critical teams don't close prematurely.
- [x] if a VFS team challenges our launch-blocking label, OCTO practice area leads and/or OCTO platform product owners should have the final say.
- [x] Collaboration cycle reviewers will assess VFS teams against the VA.gov Experience Standards. 

---
## Tasks

- [ ] Update CC guidance to reflect our process changes:
   - [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-staging-review.md
   - [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md
   - [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
@shiragoodman I do not think we need to provide any changes to [the staging template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md). We currently just refer them to the read me file. Unless you want to include the Platform process for bulk upload in the steps.

**Comment by shiragoodman** [comment]
I don't think we want to put the bulk upload steps in the template since this is VFS facing and thats an internal/operational step.

However, something I noticed recently is that we don't link the Staging Review guidance in the template... Can we do that? Not sure if you want to do that now bc the link will change once moved to Platform Website, but just thought it wwas a good idea.

**Comment by shiragoodman** [comment]
Staging Review Touchpoint doc is ready to go in Document Drafts space. Can be pushed to Platform Website at any time.
