### ISSUE TITLE
Add new PDF link to Welcome Kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#26966]
## Issue Description
Stakeholder Justin Hoffman has requested a new PDF be linked to on the Welcome Kit page. It's the Whole Health quick start guide, which is uploaded to the CMS. This should be the last PDF under the For Veterans section.

## Tasks
- [x] Add PDF link to Welcome Kit page (Randi)
- [x] Review (Beth)
- [x] Publish (Randi)
- [x] Alert stakeholder that change is live (Randi)

## Acceptance Criteria
- [x] New PDF is linked to on live site

**Comment by RLHecht** [comment]
@bethpottsVADEPO I added the new quick start guide to the welcome kit. Could you take a look and let me know if my wording is OK? Then I'll publish and let Justin know it's live. The preview link is: preview-prod.vfs.va.gov/preview?nodeId=716

**Comment by RLHecht** [comment]
Published this update and let Justin know. Will close once validated on live site.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
