### ISSUE TITLE
Collaboration Cycle Kickoff [Caregivers, Facilities Search on 10-10CG)

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26976]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] VFS: Attach any available artifacts.
- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Collab Cycle touchpoints:

- [X] Design Intent (#27066)
- [X] Midpoint Review (#27255)
- [ ] Contact Center Review
- [ ] Staging Review
- [ ] Privacy and Security Review
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)
- Link to wireframes, mockups, or prototypes
- Any other artifacts you have so far

### Enhancement Overview
The purpose of this enhancement is to improve the user experience of selecting a VA facility on VA Form 10-10CG (Caregivers) and solve problems related to maintain hardcoded facilities lists.

**Current Experience**
Currently, to select a facility, the user must select the state from a hardcoded dropdown list of states. Then they must select a facility name from another hardcoded dropdown list filtered by the state.

**Problems with current experience**
1. Facilities names change often, which requires us to update code with the new name.
2. Those living near a state border may need to go to a facility in a different state

**Proposed Solution**
The proposed solution is to integrate with the Facilities API. This will allows us to do City, State, and Zipcode searches rather than using the hard coded state and facilities dropdown lists. It will also allow us to always pull the current Facility Name rather than having to maintain our own list.

**Outline of the Changes:**
1. Replace current state dropdown list with a textbox allowing a City, State, or Zip search similar to the Facilities Search UI.
2. Replace our hardcoded state and facility list with a call to the Facilities API
3. Replace the current facility dropdown list with a dynamic list of facilities (UX TBD)

_Note: This facility search functionality on the 10-10CG could then be reused for a similar set of facility questions on the 10-10EZ (Health care application) form in a future enhancement._

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [ ] New
- [x] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [x] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [ ] Yes
- [x] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work involve changes to: (select all that apply)

- [x] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 6. Will your work include:  

- [ ] New content
- [x] Changes to existing content

### 7. Are you making a change to the user flow?
- [ ] Yes
- [x] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 8. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 9. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [x] Yes
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 10. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

### 11. Who is the VA business owner for this body of work?

- [x] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@tchrisdyer  - thanks for submitting this. I read your overview (thank you so much for providing) and recalled when we discussed this a few weeks back. Would you be able to take a second look at question # 1? I would assume that the Veteran would experience "no visible changes" based on your overview, however you selected Yes to visible changes.

**Comment by tchrisdyer** [comment]
@shiragoodman Originally the plan was for no visible change as we would have used the original dropdown boxes, but as we learned more about the Facilities API we re-evaluated and decided to make a more substantial change allowing the user to search in an area. We may also show more information about the facility such as location and distance. So the complexity has risen quite a bit since we originally spoke about it.

**Comment by shiragoodman** [comment]
@tchrisdyer thank you for sharing! This is helpful. Based on your responses and the additional info you shared, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Design Intent
- Midpoint Review
- Contact Center Review (you may just need to update the Product Outline for the 10-10CG, but check with the Contact Center team)
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). Please review the guidance on our Collaboration Cycle README page for next steps.
