### ISSUE TITLE
Staging Review [Healthcare Experience - Check-in MVP]

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#26972]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support. 
- [x] Platform: Schedule meeting with Platform reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] Platform: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to Platform feedback tickets.
- [x] VFS: Update this ticket with the product’s launch date after it has gone live.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- [Check-in Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Link to the tool or feature in [Staging](https://staging.va.gov/health-care/appointment-check-in/?id=xxxxxxxxxx)
    - When the user texts check in the system looks for a valid appt in vista and if it finds one it posts data to lorota and returns the URL with the correct UUID appended.  That URL can be used 30 minutes prior to the appointment until 20 minutes after the appointment.
-  Staging test-user information (if applicable)
-  Link to content brief (if applicable)
-  Link to or attach your project's content source of truth:
    - [Prototype](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/QbxZp4L/play)
    - [Staging] - **TBD**
- Link to the Github ticket that shows the work for creating and/or updating any relevant static content pages and entry points for this project
- [Check-in Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/Check-in%20Release%20Plan.md) 
- Link to your product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/35&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1348)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/1987) in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/263) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/265) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail Platform accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): Corey Parker
- OCTO-DE Product lead (recommended): Patrick Bateman
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Kristen McConnell, Dillo Raju, Mark Dewey, Stephen Barrs
- VFS Content, IA, accessibility, and QA specialists (if applicable): Angela Fowler

### Staging Reviews can only be scheduled on Thursday.

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York).<br>

**Date/time**
 07/29/2021 
2:00pm - 2:30pm EST

Please note:
- All times are shown in ET. 
- Available time slots are indicated with [STAGING BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [STAGING BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by jparker0425** [comment]
Creating ticket to get on calendar, will be adding artifacts shortly.

**Comment by shiragoodman** [comment]
thanks @jparker0425. Review has been scheduled for 7/22 at 2:00 pm. Please have artifacts added to ticket by 7/15 at the latest. If artifacts are not provided by then, we will have to postpone.

**Comment by shiragoodman** [comment]
review moved to 7/29

**Comment by shiragoodman** [comment]
hey @jparker0425  - just a reminder to please have all artifacts linked in this ticket by EOD Friday 7/23. Collab cycle reviewers will begin their reviews next week, and if all artifacts aren't ready, we won't have adequate time to complete our reviews before the Thursday 7/29 meeting. If you have any concerns about being able to make this timeline, or any questions in general, please let me know. Thanks!

**Comment by jparker0425** [comment]
@shiragoodman thank you for the follow up! We are trying to wrap up a few of the items (links to staging, QA, security.) I will update by end of week on where we stand.

**Comment by shiragoodman** [comment]
@jparker0425 i see a lot of the links and artifacts above are still TBD... Do you have updates? My team is scheduled to begin their reviews today and we can't do that if we don't have the necessary artifacts.

**Comment by jparker0425** [comment]
@shiragoodman I actually wanted to discuss this with you today. We had a meeting this morning and for testing, we will need to know how many users specifically will be testing because of how the product functions. We will need to create URLs for each user testing this for the review and there is also a 30 minute window the testing must be completed in once the URL is generated because those links will expire.  

I wanted to talk with you about how best to coordinate this with each team member doing the testing. There really has not been too many changes aside from what was recommended from the Midpoint Review which was minimal.

**Comment by shiragoodman** [comment]
@jparker0425 my team includes the following people:

1. @allison0034 
2. @peggygannon 
3. @mnorthuis 
4. @pjhill 
5. @ddzz 
6. @joshkimux 
7. @AngelaFowler82 
8. @noahgelman 

I am tagging them here because you may need to coordinate with each of them individually to get this tested. Maybe you could create timeslots for testing and assign each of them to it?

Team - what do you think?

**Comment by joshkimux** [comment]
That could work; Angela, myself, and Noah can potentially be assigned to the same time and we could audit it together?

**Comment by AngelaFowler82** [comment]
Works for me.

**Comment by jparker0425** [comment]
@joshkimux that could work, we would need phone number and dateTime for one of you to set up the test appointment, and then you would all need to meet together to share and go through the review. 

Otherwise, we need the phone number and dateTime that works best with each team member. 

This being said, for those who are familiar with this product already, what is the absolute latest you would be able to test as we hammer out a few items on our end? Right now the soonest we could provide those links would be tomorrow or Wednesday.

**Comment by AngelaFowler82** [comment]
Upon reflection, it would be best to conduct separate tests, as I assume we can only check in once? We will need to test multiple browser and screen reader combinations. 

To whom should we send our numbers and dates/times?

**Comment by jparker0425** [comment]
@AngelaFowler82 agreed. 

If everyone could send that information to me, I will get this end coordinated.

**Comment by peggygannon** [comment]
@jparker0425  Here are some times ranges that would work for me: 
Tuesday 12-2 and 4-5 pm ET
Wednesday 12:30-3:30 pm ET

**Comment by mnorthuis** [comment]
Open times for me:
Tues 3-6 ET
Wed 12-3ET

**Comment by joshkimux** [comment]
Open times for me:
Wed: 9-11am ET

**Comment by allison0034** [comment]
Open times for me:
Tuesday 12-2 ET
Wednesday 1:30-3:30 ET

**Comment by jparker0425** [comment]
Thank you all, I am going sent the date times across. We will need to add your mobile phone number as well for testing. Would you all be able to send that as well?

**Comment by shiragoodman** [comment]
thanks @jparker0425  - I'd like to interject and ask that my team DM you on Slack their mobile number... that way it's more secure and they're not posting their number for the world to see. Thanks!

**Comment by jparker0425** [comment]
Thanks @shiragoodman, agreed. Should have called that out for Slack.

**Comment by allison0034** [comment]
@rtwell can you provide Corey Parker with your phone number in Slack and a 30 min timeframe to check staging

**Comment by AngelaFowler82** [comment]
Just FYI, I do not have my appointment yet. Please note that we have to have our feedback on the ticket by tomorrow morning.

**Comment by allison0034** [comment]
@jparker0425 Mikki and myself do not have appointments yet either.

**Comment by jparker0425** [comment]
I have send Slack details at this time to @joshkimux , @peggygannon , @mnorthuis , @allison0034 , and @AngelaFowler82.
We are working on rescheduling the test for @AngelaFowler82 currently to a better time. 

I still do not have numbers for @pjhill , @noahgelman , or @ddzz and will be reaching out directly in Slack shortly.

**Comment by noahgelman** [comment]
@jparker0425 @shiragoodman 

I tried to access the app at the schedule time and I was unable to access the app so I have not tested it. I will discuss with Corey in the morning and try again before the Meeting

**Comment by tlei123** [comment]
@jparker0425 @pjhill @ddzz , QA test-runs now completed, and QA-artifact links added/updated above in main description.

83% Passed.  2 defects logged: #28100, #28101.

cc @shiragoodman @mdewey @dillo

**Comment by jparker0425** [comment]
Thank you @tlei123! We will review the two items you have entered and address them. 

@shiragoodman as for testing, all users were able to go through the product last week, however @AngelaFowler82 wanted to run through one more time today so I will be setting up another test for Angela today.

**Comment by tlei123** [comment]
@pjhill @ddzz , FYI, I also had time this week to add **[Automated E2E test-cases](https://dsvavsp.testrail.io/index.php?/suites/view/35&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1372)** to TR.  [Test runs](https://dsvavsp.testrail.io/index.php?/runs/overview/24) last night (Tuesday, August 3, 2021)were all Passed*.

*The one run showing 5% passed was just a "boo-boo" -- I didn't set `TR_INCLUDE_ALL` correctly before my `cy:testrail-run` script-call.

@mdewey , feel free to give Peter/Darius any feedback you may have on their **[cypress-testrail-reporter doc](https://depo-platform-documentation.scrollhelp.site/test-release/Cypress-to-TestRail-Reporter-Plugin-Configuration.1738047581.html)**, when you get deputized with a future Cypress-TestRail E2E-integration task.  I wish I had time to help with this for every Staging Review, but it all depends on how many Reviews I'm supporting in any given Sprint.

cc @jparker0425

**Comment by mdewey** [comment]
That's awesome @tlei123! I have a few questions, 

- How often are the automated test cases run in TR? 
- How do I get a TR account?
- Can you elaborate more on the ` Cypress-TestRail E2E-integration task` that will happen at a future time?

**Comment by tlei123** [comment]
@mdewey , 

* The "trigger" is manually [via local Terminal, against local vets-website, and should be run at least for each Staging Review.
* Only team PMs can have a TR acct, not other team members.  All PMs are instructed to share the TR creads with any team-members that need access.
* Beyond VSP-QA's doc [link above in my previous comment], I'll be adding some add'l. help/info in my own VSA-QA docs-area soon.  Stay tuned!

**Comment by tlei123** [comment]
@pjhill @ddzz , FYI, no need to include defect #28100 in your feedback -- Closed as false-positive.  [Use-case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/qa/test-cases.md#test-case-i-edge-case---user-refreshes-the-app-before-finishing-the-check-in-process) & [test-case](https://dsvavsp.testrail.io/index.php?/cases/view/5528) updated.

**Comment by tlei123** [comment]
@pjhill , re. Cypress-TestRail integration, would you like me to just provide feedback here?

**Comment by pjhill** [comment]
> @pjhill , re. Cypress-TestRail integration, would you like me to just provide feedback here?

@tlei123 -- please add your feedback to this ticket.
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28390

**Comment by shiragoodman** [comment]
hi @jparker0425 , @mdewey , @kristenmcconnell, @stephenBarrs and @batemapf , 

As stated on the call, we are asking you to please complete a survey for the pilot of our new standards and Staging Review process. The survey link can be found here: https://adhoc.optimalworkshop.com/questions/xv854bro

We will be reviewing all feedback received from VFS teams, and will be making enhancements to our process prior to launch.

Thank you again!

@jparker0425 could you please forward the survey link to anyone I may have missed?
