### ISSUE TITLE
[FE] Profile: Investigate missing section to update/edit contact information

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26983]
## Background
As reported in [slack](https://dsva.slack.com/archives/C909ZG2BB/p1625163473019200), there is an issue specifically with test user 15 where the section to update contact information is missing entirely:
<img width="1118" alt="Screen Shot 2021-07-01 at 2 00 53 PM" src="https://user-images.githubusercontent.com/45603961/124638258-bd56c200-de58-11eb-81d8-f5c20fc01ce1.png">

## Tasks

- [ ] Track in GA to see how often these types of events are happening in prod

If it's happening in prod, then...
- [ ] Investigate scenarios when users/test users do not have vet360 service
- [ ] Dig into analytics to see if/how we're monitoring this type of event

**Comment by tmitchellgcio** [comment]
Hunting this down I am seeing User 15 does not have `vet360` in their services. We look specifically for that service in order to show the contact information. I'm still a newb so I'm not sure if that is the intention or not, but the code looks pretty specific. I'm not sure if this is a bug or not. It looks like this user just was not setup with `vet360` as a service

![user services.PNG](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/505c4117-df0f-4082-8fee-c015c387af82)

**Comment by tmitchellgcio** [comment]
@erikphansen you may know more than me if it's working as intended and the user was just setup without this. Thoughts?

**Comment by erikphansen** [comment]
Thanks for looking into this Taylor. You're right. I don't know why this user is lacking the `vet360` service, and there might not be a good reason, but this is functioning as intended so I think we can just close this.
