### ISSUE TITLE
R&S Updates: How to check your VA claim, appeal, or decision review status online

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26999]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/):  

- Change CTA button label to **Check your claim or appeal status**

### Tasks

- [ ] DEPO to approve changes as described above (Beth)

- [ ] SC to make changes (Laura)

- [ ] DEPO to approve changes (Beth)

- [ ]  SC to QA and publish (Randi)

### Acceptance Criteria

- [ ]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Let me know if I should go ahead and make the changes described above in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Let's wait on this one to see if we end up changing the button label on the other one as well. I had discussed this one with the SME previously and we agreed that it worked to keep it simple since we can't mention all 3 statuses.
