### ISSUE TITLE
Delete old Platform website support overview page

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27006]
# User story

As a Platform team member, I need to know how to request support from the Content team, so that I can complete the task-that-I-am-doing as quickly as possible.

# Tasks

- [x] Delete old support overview page (Amy)
- [x] Think through holistically how to represent general content support and Platform website support
- [x] Put content from old support overview page somewhere in our Operational Docs team space

# Acceptance criteria
- To come.

# Reference info
- [old GitHub support overview page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/documentation/request-documentation-support.md)
- [Operational docs Platform website support overview page](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1640333324/Platform+website+support+overview)

**Comment by amygoldman** [comment]
Private page in our Op Docs space with the info that was on old the GitHub overview page: https://vfs.atlassian.net/wiki/spaces/CIT/pages/1717796868/Requesting+documentation+support+from+the+Content+and+IA+team+for+other+VSP+teams

**Comment by amygoldman** [comment]
Added the "2 paths for support" info to the current support overview in Confluence: https://vfs.atlassian.net/wiki/spaces/CIT/pages/1640333324/Platform+website+support+overview#Options-for-requesting-support

**Comment by lianilychee** [comment]
7/9 Fri:
- will outline the 2ndary page of general content support (to review at SU on Monday)

**Comment by lianilychee** [comment]
7/12 Mon:
- will outline today; will show at SU tomorrow

**Comment by lianilychee** [comment]
7/13 Tues:
- will edit the new page based on in-SU review `blob-thumbs-up`
