### ISSUE TITLE
Implement `page properties` macros to individual existing pages and tracker

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27008]
# User story

- As a Content team member
- I want to know the metadata for existing Platform website pages
- so that I agitate the teams whose pages are are ROT'd.

# Tasks

- [x] Determine what we _can_ track with the macro
- [x] Decide what page properties to track
- [x] Test macros and reports with a few pages
- [x] Identify and add `page property to all pages
- [x] Add the `page property report` to the health tracker

# Acceptance criteria

- (y/n) The "test page report" displays data from existing pages

# Reference info

- [Test page report (health tracker)](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1337458762/Test+page+report+macro)

**Comment by lianilychee** [comment]
Weds 7/7:
- Gretchen will do initial investigation into what info the page property gives, and how to structure the report

**Comment by lianilychee** [comment]
Thurs 7/8:
- today will work on: tracker reporting out on a few test pages, and we can look over at the team sync gretchen is going to schedule for early next week

**Comment by lianilychee** [comment]
Fri 7/9:
- plot twist!
- I'm gonna build out one of the options today
- send out session for early next week

**Comment by lianilychee** [comment]
mon 7/12 update:
- today:
  - will take out cruft and move to team space
