### ISSUE TITLE
Iterate on and publish the support taskflow

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27007]
# User story

- As a Content team member,
- I need a clearer version of the support taskflow
- so that I can assist other teams smoothly.

# Tasks
- [x] Determine _what_ we want to clarify/refine in the taskflow
- [ ] Determine where this taskflow should live (in MURAL, or operational docs?)
- [ ] Share with Rachael Roueche

# Acceptance criteria
- There are artifacts for all the indicated areas (indicated on the MURAL) 

# Reference info
- [Support taskflow in MURAL](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1617819869492/7e8239a6633c039669db26e32b11bb16f9f490b4?wid=0-1624906143496&outline=open)
- Thoughts:
  - Request types and how to triage: Is this a PW question, a Confluence q, or a both q?
    - Want to be able to say "nope, no can do right now."
