### ISSUE TITLE
Prepare for office hours

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27004]
# User story

As a Platform Eng team member, I want to understand Content's audit guidance, so that I can prioritize what/how to transform my team's documentation.

# Tasks

- [x] Identify times for office hours (Amy) 
- [x] Make calendar series (Tues, Thurs 11-11.30) (Amy will ask what they did)
- [x] Draft message to socialize office hours (Amy)
- [ ] Send out messages on a repeated cadence

# Acceptance criteria
- To come.

# Reference info
- [draft of slack announcement and cal event text](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1714585825/Content+IA+team+office+hours)

**Comment by amygoldman** [comment]
Drafts of Slack announcement and calendar event text: https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1714585825/Content+IA+team+office+hours
