### ISSUE TITLE
R&S updates:  What your claim status means

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#27010]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/what-your-claim-status-means/):  

- Intro:
Change last sentence of intro to read: **Keep reading this page to learn about the terms we use for each stage of the process.**

### Tasks

- [ ] DEPO to approve changes as described above (Beth)

- [ ] SC to make changes (Laura)

- [ ] DEPO to approve changes (Beth)

- [ ]  SC to QA and publish (Randi)

### Acceptance Criteria

- [ ]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Let me know if I should go ahead and make the change described above in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Keep reading ~this page~ to learn about the terms we use for each stage of the process.

Just would like to take out "this page"--thank you!

**Comment by lwalsh617** [comment]
@RLHecht - I made the change to the intro per Beth's comment ^ and the top of the ticket. It's ready for you to edit and publish. Thank you!   http://preview-prod.vfs.va.gov/preview?nodeId=8548

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lwalsh617 Can we move forward with this?

**Comment by RLHecht** [comment]
Yep, I'll look at it now. This must have dropped off my radar!

**Comment by RLHecht** [comment]
Reviewed and published. Moving to validate and will close after the next deploy.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
