### ISSUE TITLE
Turn on 'operationalHoursSpecialInstructions' for VHA

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27035]
## Issue Description
 
#19615 added operationalHoursSpecialInstructions field language (for VA health facilities only) behind a flag due to formatting issues which needed to be resolved by Lighthouse (contained  pipes)

This issue serves as a placeholder reminder to turn on this field once the formatting issue has been resolved

PRs:
- Handle operationalHoursSpecialInstructions field for VA health department-of-veterans-affairs/vets-website#16004
- Add new flag for operationalHoursSpecialInstructions on FL department-of-veterans-affairs/vets-api#5903

## Tasks
- [ ] Switch flag on in production 

## Acceptance Criteria
- [ ] When flag switched for production, the language displayed on VA health detail page matches language from operationalHoursSpecialInstructions field
- [ ]  If more than one option is sent, all display.
 - [ ] If null, nothing displays

**Comment by mmiddaugh** [comment]
closing [per Dave's comment from 2023](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27035#issuecomment-1513661743)
