### ISSUE TITLE
Updating PDF links on life insurance pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27043]
## Issue Description
Stakeholder Lori Hamilton reached out with a new link to their updated life insurance PDF that we need to put on three of our benefit detail pages. 

New link to use: https://www.benefits.va.gov/INSURANCE/forms/ParticList.htm

Pages to update:
https://www.va.gov/life-insurance/options-eligibility/sgli/  under Applying for VGLI when you separate or retire, linked text “Learn how to convert your SGLI coverage to an individual policy”

https://www.va.gov/life-insurance/options-eligibility/fsgli/ Under How do I convert a spousal FSGLI policy to an individual insurance policy?, linked text “View the companies you can choose from”

https://www.va.gov/life-insurance/options-eligibility/vgli/ under Can I convert my VGLI policy into a commercial policy?, linked text “View our list of companies that take part in this program”

## Tasks
- [x] Update links on three pages
- [x] Review and publish
- [ ] Notify stakeholders that changes are live

## Acceptance Criteria
- [x] New PDF links are live on site

**Comment by RLHecht** [comment]
I have an email out to Lori Hamilton to determine if we should use the link above or link directly to the new PDF. Will update and implement when I hear back.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Per our conversation, go ahead and update the link labels and let Lori know when it's published!

**Comment by RLHecht** [comment]
@lunascoop can you make these changes for me since I still can't access Drupal? For the SGLI page the link text should read:

Get the list of participating companies and learn how to convert to an individual policy

For FSGLI: Get a list of the participating companies

For VGLI: Get a list of the participating companies

Thanks! Once you're done, we can screen share for me to review and then you can publish.

**Comment by lunascoop** [comment]
@RLHecht these pages have been set to publish.

**Comment by RLHecht** [comment]
validated on live site. Closing ticket.
