### ISSUE TITLE
[FE] Implement Feedback from UAT

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#27041]
## Description
Update site to match new mockups, https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/QbxZp4L/play

## Tasks
-  [x] Update to new content
-  [x] Address a few out standing [accessibility issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26325)
-  [x] update unit tests
-  [x] update e2e tests

## Acceptances
- [x] Merged in staging
- [ ] Signed off by UI/UX 
- [ ] Signed off by appropriate team members

**Comment by mdewey** [comment]
@kristenmcconnell  This is staging, can you review and give any feedback 

https://staging.va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287

**Comment by kristenmcconnell** [comment]
@mdewey 

Two small items:
- On the appointment page, it says "4:36 EDT." Can we add the a.m. and p.m. too?
- On the confirmation page, we had one small change to the text. You can see the [conversation in this Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1626272128011000?thread_ts=1626225575.002000&cid=C022AC2STBM). The text should read:

Please wait in the [clinic name] waiting room. We'll come get you when it's time for your appointment to start.

[Wireframe with that change.](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/7yEoo3E/play)
