### ISSUE TITLE
[Research] Check-in MVP After Launch Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27053]
## User Story
- As a product development team, we are interested in understanding what Veterans think about the MVP after it is launched at the pilot site.
_Decide if this should involve a trip to the pilot site or not._

## Related Documentation
 - [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
Finalized documentation of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.

## Tasks
- [X] Create new folder for this specific test: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/mvp-UAT
- [x] Create [research plan and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/research-plan.md)

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product)
- [x] Review research plan and conversation guide with UX manager

**Comment by kristenmcconnell** [comment]
Met with Corey.

High-level plan is: 
### How to test MVP launch
- Go to pilot site
  - Would want to go on high volume days and time
  - NPS
  - General thoughts?
  - What did you like? Not like?
- Work with pilot and have them get feedback (similar to Questionnaire plan: https://docs.google.com/presentation/d/1XAqnUKsL5C-Btg_QTFwLUWJeRbn4xNB-Lhzttm-9P4c/edit?usp=sharing)
  - Benefit of veteran and staff feedback.
- Find VA, GCIO, and Ad Hoc employees to do production testing.
  - SUS

**Comment by kristenmcconnell** [comment]
@jparker0425 [Draft research plan/conversation guide written up and ready for review.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/research-plan.md)

**Comment by jparker0425** [comment]
@kristenmcconnell Research plan looks great, captured everything we spoke about the other day. I just made typo corrections. 

I have added a link to the plan to the [Release Plan ](urhttps://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/Check-in%20Release%20Plan.mdl) I have put together.

**Comment by kristenmcconnell** [comment]
Posted [GitHUB link in Slack](https://dsva.slack.com/archives/C022AC2STBM/p1626793254134800) for feedback from the whole team.

**Comment by kristenmcconnell** [comment]
Here is an [interactive PDF](https://app.zenhub.com/files/133843125/b3296be6-944f-4c87-9a1f-022e9c00dc99/download) that can be sent to staff members. They can print out copies or fill out on their computer after talking to Veterans. This would be utilized in Method 3 outlined here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/research-plan.md

**Comment by kristenmcconnell** [comment]
Incorporated feedback from Patrick, Julia, Corey and Danielle in to the [research plan/conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/research-plan.md).
