### ISSUE TITLE
[Research] Foundational Pre-check-in Veteran Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27055]
## User Story
- As a Veteran, I want to complete as many check-in tasks and as much paperwork as possible prior to the day of my appointment.

- As a product development team, we are interested in knowing where the best place to notifyVeterans of these new pre-check-in tasks are. Therefore, we are interested in understanding the landscape of appointment notifications more.

## Related Documentation
 - [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
Finalized documentation of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.

## Tasks
- [x] Touch base with VAOS on their appointment notifications work. Do I pick up that work? Adapt it for our purposes? Basically, make sure that we aren't duplicating efforts.
- [x] Create new folder for this specific test on GitHUB: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/pre-check-in-discovery
- [X] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-discovery/research-plan.md)
- [X] Create [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-discovery/conversation-guide.md) 

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product)
- [x] Review research plan and conversation guide with UX manager

**Comment by kristenmcconnell** [comment]
Set up meeting with VAOS on July 20 @ 11 AM to review their service blueprint work on appointment notifications.

**Comment by kristenmcconnell** [comment]
Action items from VAOS meeting:
- Kristen:
  - Send pre-check-in research questions to Peter.
  - Send list of check-in contacts to Peter.
- Peter
  - Summary or links to Veteran appointment notifications research findings (methods and reasons why Veterans like it)
  - Set up meeting with Julia Snyder, Danielle Johnson, and myself to review staff-facing check-in research findings.

**Comment by kristenmcconnell** [comment]
Research from VAOS on [Veteran channels for scheduling and managing appointments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/appt-notifications-service-map/secondary-research/appt-scheduling-channels.md)

**Comment by kristenmcconnell** [comment]
@jparker0425 Here is a draft of the pre-check-in discovery [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-discovery/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-discovery/conversation-guide.md) for review.

**Comment by kristenmcconnell** [comment]
With the expansion of the card sort and old Optimal Sort test result, I proposed the question if this foundational research was needed anymore. [See Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1627329178322600?thread_ts=1627308587.288500&cid=C022AC2STBM)

Should we move onto usability testing?

**Comment by kristenmcconnell** [comment]
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1627329178322600?thread_ts=1627308587.288500&cid=C022AC2STBM) with the discussion to move onto usability testing for Veterans and discovery research for staff. Will continue this work in other stories.
