### ISSUE TITLE
Revisit Facility Locator "no results" error message

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27057]
## Issue Description
When a search on Facility Locator returns no results, a lengthy error message is displayed. This issue is to revisit the message for a possible rewrite using concise plain language. 

## Related work
In Screen reader announcement for "No search results" message #25629, we restored the search results header and removed the first line of the existing error message.

## Current text
**For better results:**
- **Zoom out** to view a larger area of the map, **or**
- **Move the map** to a different area
Then click the **“Search this area of map”** button.
If we still haven't found any facilities near you, **please enter a different**:
- **Search term** (street, city, state, or postal code), **or**
- **Service type** (like “chiropractor or optometrist”), and select the option that best meets your needs

<details> 
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/124833240-20b92080-df3b-11eb-9613-bce08a7d2b7a.png)

</details>

## Tasks
- [ ] Work with content and design to craft a concise error message

## Acceptance Criteria
- [ ] All Veterans are informed when a search returns no results.
- [ ] Screen reader announces no results have been returned
- [ ] Veterans know how to resolve the error
