### ISSUE TITLE
Design intent [Caregivers, Facilities Search on 10-10CG)

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27066]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [x] No

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)
- [Enhancement Overview](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27066#issuecomment-876434248)
- Whiteboard sketch or other lo-fi prototypes or wireframes:
        - Current design in prod: [Vet Medical Center (old)](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/wL7wYej) - these questions will be split into two pages. The VA heath center is the one this intent is focused on as the other question will not change (other than text).
        - Main design foundation: [Vet Medical Center (V1)](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/v/xjyvMJ/a/7yE5rq7/r/3PD03z) and [Vet Medical Center V1 (show more)](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ELx4l3Y)
        - Graveyard/ other variation sandbox: [Vet Medical Center (V2)](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ag8bW9r) and [Vet Medical Center (V3)](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/L0MPqvD)
        - 10-10CG [Sketch](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8)
        - PDF [files](https://github.com/department-of-veterans-affairs/va.gov-team/files/6793449/10-10CGVA.medical.center.pdf)
Other considerations: Though this will first be implemented in the 10-10CG. We need to make it flexible enough for implementation in the 10-10EZ which will have many more location value returns.

## Meeting attendees from requesting team
- Designer(s) (required): Dené Gabaldón
- Product Manager (required): Chris Dyer
- OCTO-DE Design Lead (required): Ryan Thurlwell
- OCTO-DE Product Lead (recommended): Ming Ligh
- VFS content, IA, and QA specialists (if applicable): name(s)
- Other stakeholders you want to invite (if applicable): Dat Tran, Daniel Nalbach

### Design Intents can only be scheduled on Monday, Tuesday, or Friday. 

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York). <br>

**7/16 @ 2pm**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
For the Design Intent, you'll receive feedback from design and IA only. You won't receive feedback from accessibility, content, or QA, as it's too early in the development process.

Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by tchrisdyer** [comment]
### Enhancement Overview
The purpose of this enhancement is to improve the user experience of selecting a VA facility on VA Form 10-10CG (Caregivers) and solve problems related to maintain hardcoded facilities lists.

**Current Experience**
Currently, to select a facility, the user must select the state from a hardcoded dropdown list of states. Then they must select a facility name from another hardcoded dropdown list filtered by the state.

**Problems with current experience**
1. Facilities names change often, which requires us to update code with the new name.
2. Those living near a state border may need to go to a facility in a different state

**Proposed Solution**
The proposed solution is to integrate with the Facilities API. This will allows us to do City, State, and Zipcode searches rather than using the hard coded state and facilities dropdown lists. It will also allow us to always pull the current Facility Name rather than having to maintain our own list.

**Outline of the Changes:**
1. Replace current state dropdown list with a textbox allowing a City, State, or Zip search similar to the Facilities Search UI.
2. Replace our hardcoded state and facility list with a call to the Facilities API
3. Replace the current facility dropdown list with a dynamic list of facilities (UX TBD)

_Note: This facility search functionality on the 10-10CG could then be reused for a similar set of facility questions on the 10-10EZ (Health care application) form in a future enhancement._

**Comment by allison0034** [comment]
@tchrisdyer this has been scheduled for 7/16 at 2pm ET. Can you answer the question "Has your product been reviewed by the OCTO-DE Design Lead?" in the ticket?

**Comment by allison0034** [comment]
This has been changed to Tuesday July 13 at 11am ET

**Comment by mnorthuis** [comment]
No IA feedback.  Thank you!

**Comment by hdjustice** [comment]
Closing this ticket - we will be starting this feature over from the beginning and will submit for a new collab cycle
