### ISSUE TITLE
Create Slack guide for Platform Product Support

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#27076]
## Issue Description
Platform Product Support team members have shared that the large number of Slack channels is overwhelming. Team members do not know where to post concerns that they have, and have trouble keeping track of conversations. 

We plan to create a Slack Guide for internal (or operational) use by the Platform Product Support team. The Slack Guidance will be published on Confluence:
https://vfs.atlassian.net/wiki/spaces/PPST/pages

Slack Guidance will include what type of posts/discussions should happen on the following channels:

- vsp-product-support-work (Oddball)
- vsp-product-support-team (DSVA)
- vsp-collaboration-cycle (DSVA)
- vfs-all-teams (DSVA)
- vfs-platform-support (DSVA)
- other channels as necessary

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] There is a page on Confluence that teams can refer to to determine what type of conversations happen in which Slack channels. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
@shiragoodman Here is current page on Confluence. https://vfs.atlassian.net/wiki/spaces/PPST/overview?homepageId=1392346189#Slack

**Comment by shiragoodman** [comment]
thanks @peggygannon . This ticket can be closed.
