### ISSUE TITLE
[FE] Profile: Contact info tables incorrect (missing rounded corners + x-padding table headers and rows)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27071]
## Background
As reported by Erik in [slack](https://dsva.slack.com/archives/C909ZG2BB/p1625693643076600), the contact info tables in profile are missing rounded corners and the x-padding for table headers and table rows are inconsistent. 

<img width="689" alt="Screen Shot 2021-07-07 at 2 28 55 PM" src="https://user-images.githubusercontent.com/45603961/124934401-a89e3980-dfd2-11eb-9459-ff6a63c2ae98.png">

Missing rounded corners due to [this](https://github.com/department-of-veterans-affairs/vets-website/blob/4b679fddefe2bc1d34e2f14eb9ef171c46d6bffe/src/applications/personalization/profile/sass/profile-info-table.scss#L3-L7)

## Tasks
- [ ] Restore rounded corners on contact info tables in profile
- [ ] Get guidance from @tressaellen and/or @andaleliz re x-padding
- [ ] Implement fix for x-padding

**Comment by erikphansen** [comment]
@ajakabcin I'll knock this out this sprint since I know the fix.

**Comment by erikphansen** [comment]
This can be validated on staging once https://frontend-support-dashboard.vercel.app shows hash `90a6b76e77360c13881a164ba955e830869ca6ff` as being on staging

**Comment by ajakabcin** [comment]
confirmed on staging
