### ISSUE TITLE
508|NOD -  Review & submit page labels & headers

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27096]
## Description

On the review & submit page, the edit button for an added issue "Edit {issue}" and the area of disagreement page edit button "Edit {issue}" have the same aria-label. These need to be made unique so a screen reader user can differentiate what is being edited.

Additionally the area of disagreement checkboxes included heading level 3

## Tasks

- [ ] Add unique `aria-label` text to edit buttons
- [ ] Fix area of disagreement header levels

## Definition of done

- [ ] All tasks complete
- [ ] All test passing

**Comment by Mottie** [comment]
@joshkimux The fixes have been merged into staging.

**Comment by joshkimux** [comment]
@Mottie aria-labels are now unique 👍 
However, the checkboxes are still headings 😢 

<img width="1489" alt="Screen Shot 2021-07-12 at 9 46 36 AM" src="https://user-images.githubusercontent.com/14154792/125298782-78b6a500-e2f6-11eb-8a24-a593e964f1f4.png">

**Comment by Mottie** [comment]
Oh, I made those headers based on Angela's feedback.

**Comment by Mottie** [comment]
Fixes to the header and removal of checkbox headers is now in staging. Thanks for clarifying!

**Comment by Mottie** [comment]
@joshkimux Do you want me to leave this ticket open until you validate?

**Comment by joshkimux** [comment]
<img width="1077" alt="Screen Shot 2021-07-16 at 11 52 36 AM" src="https://user-images.githubusercontent.com/14154792/125975181-c13f9a3c-b941-4a3f-9454-a694838ad173.png">
Checkbox issue is resolved, but more problems seem to be emerging on the review page specifically around editing 😢

**Comment by Mottie** [comment]
Fixed the headers in staging/production! Thanks Josh!
