### ISSUE TITLE
[Discovery] - Review analytics and previous research for side nav component and VAMC/profile mobile menus

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#27102]
**Background**
We noticed Veterans had a hard time intuitively using the profile mobile menu in our health facilities research study.  We want to better understand any usability problems Veterans may be experiencing with this, and compare with an alternative to our mobile menu, the [side nav component](https://design.va.gov/components/sidenav).

**Goals**
We're hoping analytics can help us understand: 
- If Veterans are indeed having a hard time noticing/using the profile mobile menu as we saw in our facilites research
- If the side nav component performs any better (because if so, it could be a low LOE alternative to our custom menu if we need to replace it)

Previous research can help us understand how Veterans interacted with these components in other scenarios.

**Tasks**
- [ ] [Review the navigation mural board](https://app.mural.co/t/vsa8243/m/mikkiva6685/1625598338949/5367c23bb4909f4624dea1666cbe968f123c70ef?sender=megpeters0505) shared by IA team prior to starting work
- [ ] Use analytics to evaluate the following (desktop vs mobile) for profile, VAMC, and a high traffic hub page that uses the side nav component:
   - compare the percent of users that navigate from the main landing page to other pages that are only linked via the side navigation. Hypothesis: A lower rate on mobile suggests people aren't seeing the menu.
   - review search terms to see if people are using terms included in the side navigation on mobile more than they are on desktop.  Hypothesis: if people are searching for something in side nav significantly more frequently on mobile than desktop, that suggests they're not seeing the links to go there.
   - Update this with points from Meg's comment below
- [ ] Review any previous research that has been done regarding the side nav component. No research has previously been done on the mobile version of the VAMC or profile mobile menu.
- [ ] Document findings and share with team
- [ ] Use findings to determine next steps to improving the UX of the profile mobile menu.

**Comment by mpeterz** [comment]
@andaleliz - The above looks good! I added suggestions below. 

**What do you mean by "main landing page" in the context of benefit hubs?** 
The hub pages themselves don't have "In this section" menus. The "In this section" menus start showing at the next level down. For example:
* Disability hub page does not have "In this section menu": https://www.va.gov/disability/
* "How to file a claim" page has "In this section menu": https://www.va.gov/disability/how-to-file-claim/

The VAMC main landing pages do have the "In this section menu."

**Analytics-wise, I'd love to know:** 
* Besides comparing desktop and mobile, are there differences in behavior for the analytics above ^ and below for users of screen readers? Hypothesis: There are accessibility issues that make it hard for screen reader users to use the menus. (We saw this when Angela walked us through navigation on mobile.)
* Compare the percent of people who navigate using the mobile menus, then use VA.gov site search or Google. Hypothesis: If the mobile menus are too hard to use, people try searching. And differences between mobile, tablet, desktop, and screen readers (in exit rates to site search or Google) could show that either the Profile, hub, or VAMC menu is more usable.
* For the Profile and VAMC sites, how many people close the menus? (On the pages within benefit hubs, they must close the menus if they want to see the content.)
* On the pages within benefit hubs, how many people open and close the accordions within the nav menus? 

The last 2 bullets could inform future design decisions as Profile gets built out.

This isn't the problem you're trying to solve, but...
I'd love to know which nav links in the Profile menu are used most and least.

**Comment by andaleliz** [comment]
@mpeterz thanks for the input! By **main page** I just mean an entry point that has the side navigation on it.  Profile is really the only one that has a "main page". To evaluate the side nav on hub pages, I'd probably choose 2-3 of the most trafficked pages with side nav to look at.

Those are interesting analytics to consider as well - I'll add them to the list when I start this work.  Unfortunately, analytics doesn't tell us whether or not people are using screen readers or assistive technology, so we're not able to get quantitative data on that (big bummer, I know).

**Comment by andaleliz** [comment]
We've conducted several studies on mobile and have not seen a significant pattern of people struggling to use the profile menu. Going to close this for now - we can revisit if needed later.
