### ISSUE TITLE
[Discovery] - Learn more about My VA Treating Facilities (facility preferences) in MHV

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#27100]
**Background**
Based on what we learned in our health facility research study, it isn't valuable to Veterans to have the ability to manually set preferred facilities in their profile.  Before we fully pivot away from this effort, we want to learn more about how this works and performs in MHV.  Perhaps there is still a business case to bring this functionality over to VA.gov

**Tasks**
- [x] Meet with MHV team to learn how facility preferences are used by their team, and what usage of this feature is like (analytics would be ideal). (scheduled for 7/15)
- [ ] Share findings w/ team
- [ ] Determine as a team if there are any reasons we should move forward with adding Your VA Health Facilities to profile.

**Comment by andaleliz** [comment]
@ajakabcin here are my notes from the meeting. My main takeaway was that there isn't a compelling reason shared in that meeting to put this on VA.gov, but we really need to talk to Carnetta before we pull the plug on this.

**Facilities in MHV profile:** 
-  are shown based on what is in MPI
- has to be a treatment facility
- are where records are located (not necessarily where people have actually been)

**Are there any analytics available?**
- The facility preferences option isn't tracked with any kind of formal analytics.  
- The MHV team ran some DB queries during the meeting that show ~20% of MHV accounts (both active and inactive) have one or more facilities marked as current

**Do people use the preferred facilities feature?
Its not required

**Why do they use it?**
- Original objective was to use it as a filter in blue button
- MHV would apply the filter to reduce clutter when people are requesting records
- Not used in any appt logic or for any other features within MHV
- UI does not make it clear to users that it is associated with Blue Button

**When someone sets a preferred facility, what does that do within MHV?**
Nothing, it's for Blue Button

**Misc other notes**
- The Number in parentheses is the Vista Site ID
- MHV team is currently working with VA Profile to read and pull in that data on MHV, and next steps will allow people to update VA Profile from MHV profile

**Comment by andaleliz** [comment]
Per Kevin, we're going to let this work go. We don't have bandwidth on the team to continue hunting this down, and we can defrost this feature, and continue work later if needed.
