### ISSUE TITLE
Update clothing allowance rate on VA clothing allowance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27135]
## Issue Description
We currently have an outdated rate for clothing allowance on our [VA clothing allowance](https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/) page. This number should be changed from $830.56 to $841.36 based on the [2021 VA special benefit allowances rates page](https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/).

## Tasks
- [x] Update number on clothing allowance page (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] New rate is live on the site

**Comment by lunascoop** [comment]
@RLHecht this page has been set to publish.

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket.
