### ISSUE TITLE
NOD: Allow contact info updates within the page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27137]
## Description

The Notice of Disagreement form requires the Veteran's email, phone and mailing address. If any of these are missing, the user should be able to update this information within a modal that directly interacts with their profile data. Previously, we sent the Veteran to the profile page in a new tab.

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26013

## Tasks

- [ ] Add editable profile components 
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] Tests are passing
