### ISSUE TITLE
[FE] Support QA effort

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#27161]
This is a placeholder for any effort that needs to go into supporting the QA team 

## Tasks
- [ ] Automate the use cases that do not have cypress tests (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/qa/test-cases.md)
- [ ] Support the QA in their needs
- [ ] Create A way to create a UUID for testing integration with downstream services
- [ ] Understand TestRail
