### ISSUE TITLE
Authenticated Experience: Sprint 54 (8/11 - 8/24)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27160]
## Priorities

1. Resolve outstanding My VA accessibility issues
2. Notification Preferences design refinement (experimental design work)
3. Notification preferences build (radio buttons)
4. Action Items discovery research (recruit for and conduct research)

## My VA redesign 
**PM**
- [x] Submit for accessibility review #28025 

**FE**
- [x] **Resolve all accessibility findings from staging review (_must complete in order to submit accessibility office review request_)**
     - [x] 508-defect-2 [SCREENREADER]: Alert icon in applications in progress cards must have alt text #25072
     - [x] 508-defect-2 [COGNITION, SEMANTIC MARKUP]: Alert for cerner user should be designed and written semantically #25049
     - [x] Simplify Cerner alert #28575
     - [x] 508-defect-2 [MAGNIFICATION]: "Go to your profile" may be missed by magnification tool users #25052
     - [x] 508-defect-3 [COGNITION]: Applications in progress card's form number should describe the heading and be simplified to be less redundant #25069
     - [x] Update bolding and chevron styling on text links in My VA 2.0 dashboard #28302
     - [x] 508-defect-2 [COGNITION, SEMANTIC MARKUP]: Verify identity prompt should be designed and written semantically #25050

## Notification Preferences
**PM**
- [ ] Finish test case documentation #26223
- [ ] Submit Analytics Request (VSP collab cycle) #27171 
- [ ] Submit staging review request

**Design**
- [x] Experimental Design Submission/Review #28433
- [x] Build prototype for internal testing with revised designs #28361
- [x] Share revised designs with partners #28369
- [ ] Internal usability study for latest notification prefs iteration #28917
- [x] Update FE documentation per new designs #28370 
- [x] Document concepts for A/B testing #28927 

**FE**
- [ ] Continue build/revisions with radio buttons
     - [x] (_from Sprint 53_) Adjust existing RadioButton component #28114 
     - [x] (_from Sprint 53_) Allow local overrides of the profileNotificationSettings feature flag #28063
     - [ ] Replace checkbox component with adjusted radiobutton component #28502
     - [x] Add loading state to radio buttons #28619
     - [ ] Update UI to match new designs #28503
     - [x] Add "null" indicator to Notification Settings checkboxes #28489
     - [x]  'Add email address' link is wrong #27915 

## Action Items Discovery
**Design/Research**
- [x] Internal review of research plan #28507
- [x] Kick off recruiting for research on elevating action items #26600
- [x] Prep materials for action items research #28926
- [ ] Conduct research on elevating action items #26601 

## Backend 
- [ ] Identity team support
- [ ] Fix VA profile ADDRVAL111 DualAddressError #28396
- [ ] Fix VA profile ADDR301 errors #28398

## Direct Deposit
**Design**
- [ ] Create design/content for alert around reactivated DD in limited capacity #28794

**FE**
- [x] Temporarily disable direct deposit functionality on FE #28729
- [ ] Reactivate Direct Deposit in limited capacity #28904

**BE** 
- [x] Temporarily disable direct deposit functionality on the backend #28728
- [ ] Reactivate Direct Deposit in limited capacity #28903

## Profile
**FE**
- [ ] Implement improved "remove" [contact information] button functionality/UX #27169
