### ISSUE TITLE
[FE] Address what happens when the page gets refreshed. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#27164]
## Problem
When the user refreshes a page after clicking the link, the app response in a manner that is not logically

## Solution
The app should still allow a user to check-in if the page is refreshed

## tasks
- [ ] store UUID in session storage
- [ ] Store clinic data in session storage?
- [ ] Have checks around when data isn't there
- [ ] Error page and footer should render correctly, with and without data.

**Comment by mdewey** [comment]
idea: storing stuff in session

**Comment by mdewey** [comment]
ISSUE: When page is refreshed in staging it gets a 404

**Comment by mdewey** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/9624
