### ISSUE TITLE
[FE] Profile: Implement improved "remove" [contact information] button functionality/UX

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27169]
## Background
As outlined in #23665, we needed a better experience for the `remove` button which was previously styled as a link. This required quite a bit of [discovery and usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23665#issuecomment-870718452). The team reached the conclusion to:

- move the `remove` button outside of the edit functionality so that it's visible from the read mode of personal and contact information page
- update the button style to use the secondary button styling from the design system until a better option is available
- update warning modal 

full details for "remove" functionality [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md)

## Tasks
- [x] Move the `remove` button outside of the edit functionality so that it's visible from the read mode of the personal and contact information page
- [x] Update the button style to use the secondary button styling from the design system until a better option is available
- [x] Update warning modal specs and copy as outlined [here for specs and copy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md)

## Acceptance Criteria
- [x] On the personal and contact information page, the `remove` button is visible from read mode
- [x] The `remove` button is styled as a secondary button
- [ ] The warning modal matches specifications and copy documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md)

**Comment by andaleliz** [comment]
Docs have been updated w/ changes we discussed on 7/12 to update the whole layout of profile.

**Comment by erikphansen** [comment]
I think we should have a different ticket to tackle revising the >768px layout of the Profile. That can be done before we change how REMOVE works. And it would affect _all_ `ProfileInfoTable`s. The table row _titles_ will always sit above the table row _values_ regardless of screen size.

**Comment by ajakabcin** [comment]
OK @erikphansen I'll follow up with you on breaking this out.

**Comment by andaleliz** [comment]
FYI: when this is done, we will need to update screenshots and info in the [call center resources](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Call%20Center) too, @ajakabcin.

**Comment by ajakabcin** [comment]
@tmitchellgcio also moving this to next sprint to focus on radio buttons

**Comment by ajakabcin** [comment]
We were able to get a big jump on this in sprint 54, will complete in sprint 55.

**Comment by ajakabcin** [comment]
Hey @tmitchellgcio this looks great except for one minor thing. In the warning modal, the first sentence after the **Are you sure?** header should read "This will **remove** your [contact information] across these VA benefits and services:" but on staging we have "This will **delete** your [contact information] across these VA benefits and services:"

Can we change delete to remove to match the content team approved copy? Thanks so much!

![Screen Shot 2021-09-07 at 1 40 21 PM](https://user-images.githubusercontent.com/45603961/132388482-5df0f1e2-f310-48b0-a83f-1d86abf1950d.png)

**Comment by ajakabcin** [comment]
Confirmed on staging - closing

**Comment by andaleliz** [comment]
@tmitchellgcio and @ajakabcin as part of the alert audit I'm doing, I checked out this functionality and I noticed that there's a delay on the modal closing after confirming removal. The modal shows the loading button, and then the `yes, remove my information` button re-appears and the modal stays open for 2 seconds before it closes.

Here's a video of what I'm talking about.

https://user-images.githubusercontent.com/55992116/133357589-b0a4679b-390c-4d41-9255-ad5e69e71457.mov

It seems like the modal should close as soon as the API call is done (which I would expect to coincide with the end of the loading state on the button).  Did either of you notice this before? I was able to replicate a couple of times with user 36.

**Comment by tmitchellgcio** [comment]
Oh weird. I don't think I noticed that. I will get it fixed. Thank you for noticing this

**Comment by ajakabcin** [comment]
Thanks for flagging this @andaleliz! In the future let's make a new ticket for this instead of reopening it since it was from the previous sprint. Thanks!

cc @tmitchellgcio

**Comment by tmitchellgcio** [comment]
I can close it and open a new ticket if needed. Sorry about that

**Comment by ajakabcin** [comment]
No worries! just for next time :)

**Comment by ajakabcin** [comment]
Ok changed my mind on this one - creating a separate bug ticket to address the issue Liz found > #29992 

Closing this out. @tmitchellgcio please track the issue in the bug ticket linked above. Thanks!
