### ISSUE TITLE
[Design, PM] My VA: Prep for and conduct demo of My VA for chairman of board of appeals

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27184]
## Background
We've been asked to prep a demo of the claims and appeals section of the new My VA dashboard for the Chairman of the Board of Appeals. We'll need to create a small powerpoint, pull together some stats and notes from research to present.

## Tasks
- [x] Create powerpoint using the template Leslie sent us
- [ ] Review with Kevin as needed
- [ ] Tressa, Erik, Lihan and AJ touch base internally on demo 
- [ ] Execute demo

**Comment by tressaellen** [comment]
The demo went really well! Some things to consider after talking to the Chairman:

- Change the expiration date for removing the claims/appeals section from 30 to 120 days. (based on appeals)
- Include VHA priority in the disability rating ( need to do more research about this)
