### ISSUE TITLE
NOD: Fix area of disagreement headers

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27191]
## Description

The Notice of Disagreement form's area of disagreement pages cycle through each selected issue and display a list of reasons for disagreeing. The original a11y ticket wanted a header in place of the legend that is associated with the checkbox group, which I interpreted as adding a header to each checkbox label. This needs to be fixed.

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27096#issuecomment-878295668

## Tasks

- [ ] Wrap `<legend>` text in a `h3`
- [ ] Remove `<label>` headers

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
