### ISSUE TITLE
Implement OOTB automation features in Sentry

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#272]
## User Story
As a triage team member, I need to reduce the amount of manual interaction with Sentry so that I can be more efficient in triaging issues in Sentry.

## Goal
- Reduce the overall amount of manual work that is done in Sentry

## Acceptance Criteria
- [ ] When there is a spike in events, the triage team is automatically notified
- [ ] Sentry consumes individual commit data
- [ ] When events come into Sentry, they are automatically linked to a GH issue (existing or create new one)

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
In terms of Slack integration:

We may be able to hack around the "only one webhook" situation by creating different slack groups and tagging them in messages to the #vetsgov-sentry-alerts channel

**Comment by kfrz** [comment]
Features to scrutinize/implement:

[Ownership rules](http://sentry.vetsgov-internal/settings/vets-gov/platform-api-production/ownership/) for automatically assigning issues to teams based on path.

[Release tracking](http://sentry.vetsgov-internal/settings/vets-gov/platform-api-production/release-tracking/) for tracking events in relation to a given release, requires GitHub integration. [API Docs](https://docs.sentry.io/api/releases/) for reference.

[Issue tracking](http://sentry.vetsgov-internal/settings/vets-gov/platform-api-production/issue-tracking/) for connecting Sentry events to GitHub issues, allowing for status tracking and auto-resolving as of release features. Provides clarity into who is working on what. Requires GitHub integration.

[Alerts](http://sentry.vetsgov-internal/settings/vets-gov/platform-api-production/alerts/) for the integration of alerts via email or Slack/PagerDuty for individuals or teams as mentioned in original issue body.

**Comment by kfrz** [comment]
@mina after some review/thought, this may be better suited as three bodies of work:

- [ ] GitHub integration
  - [ ] Integrate issue tracking
  - [ ] Integrate release tracking
- [ ] Ownership rules (based on path/tagging)
- [ ] Alerting ( revisit and coalesce on what we want to alert ) 

IMO each of these realistically could be its own epic,, especially the GitHub integration
