### ISSUE TITLE
[Tech Debt] - React Applications - Migrate AlertBox components to va-alert

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#27203]
## Description
Recently, the vsp design system team created a new `va-alert` component and deprecated the existing `AlertBox` component. To keep our react applications up to date with current platform conventions, we need to migrate all existing instances of `<AlertBox />` to `<va-alert>`. 

## Considerations
- React applications include rated disabilities, view dependents, view payment history, and view representative.
- [Example of va-alert in coe download component](https://github.com/department-of-veterans-affairs/vets-website/blob/fbf18f18a343385786618e2525f56b42e6b92a9c/src/applications/lgy/coe/components/CertificateDownload.jsx#L8-L16)

## Tasks
- [x] update to `va-alert` in all react applications mentioned above
- [x] update any unit tests and/or e2e tests that check for statuses embedded in `AlertBox`

## Acceptance Criteria
- [x] Alerts are updated
- [x] Test are updated
- [x] A PR has been requested for merging
