### ISSUE TITLE
Operating status alert should use the informational icon

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27206]
## Issue Description
The `Limited services and hours` operating status uses a warning icon rather than the informational icon. 

Facility operating status alerts are used on the following pages:

- VAMC situational update pages
- Vet Center Main and Location pages 
- Facility Locator search result cards
- Facility Locator detail page

# Current behavior

![image](https://user-images.githubusercontent.com/55411834/125359523-9e0fd700-e327-11eb-9d7c-0bdf57ef617d.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/55411834/125359570-b2ec6a80-e327-11eb-85b8-352ab4b27422.png)

## Examples for testing
**Caveat - statuses below were effective 7/27 and may have changed since then**...

### Vet Centers

[Facility Locator search](https://www.va.gov/find-locations/?page=1&address=houston&facilityType=vet_center&serviceType&latitude=29.7589&longitude=-95.3677&radius=53&bounds%5B%5D=-96.1177&bounds%5B%5D=29.0089&bounds%5B%5D=-94.6177&bounds%5B%5D=30.5089&context=Houston%2C%20Texas%2C%20United%20States)
Location = Houston
Facility type = Vet Centers

**Limited services and hours**
- Houston Southwest Vet Center [FL detail page](https://www.va.gov/find-locations/facility/vc_0710V)

**Closed**
- Houston West Vet Center [FL detail page](https://www.va.gov/find-locations/facility/vc_0711V)

### VAMC
**Limited services and hours**
- [VAMC Operating status page](https://www.va.gov/albany-health-care/operating-status/)
- [FL search](https://www.va.gov/find-locations/?address=albany&bounds%5B%5D%5B%5D=-96.1177&bounds%5B%5D%5B%5D=29.0089&bounds%5B%5D%5B%5D=-94.6177&bounds%5B%5D%5B%5D=30.5089&context=Albany%2C%20New%20York%2C%20United%20States&facilityType=health&latitude=42.6512&longitude=-73.755&page=1&radius=14&serviceType&bounds%5B%5D=-74.505&bounds%5B%5D=41.9012&bounds%5B%5D=-73.005&bounds%5B%5D=43.4012])
- Samuel S. Stratton Department of Veterans Affairs Medical Center [detail page](https://www.va.gov/find-locations/facility/vha_528A8)
- Troy VA Clinic [detail page](https://www.va.gov/find-locations/facility/vha_528GX)
- Schenectady VA Clinic [detail page](https://www.va.gov/find-locations/facility/vha_528GW)

---
## Tasks
- [ ] Refer to the [VA design system for icons](https://design.va.gov/design/icons#feedback)
- [ ] Ensure the implementation on all Facility Locator, VAMC and Vet Center pages display the informational icon for `Limited services and hours` operating status alerts

## Acceptance Criteria
When a facility's operating status = `Limited services and hours` 
- [ ] Veterans viewing the facility operating status within Facility Locator search result cards will see the informational icon. 
- [ ] Veterans viewing the facility operating status on a Facility Locator detail page will see the informational icon. 
- [ ] Veterans viewing the facility operating status on a VAMC situational update page will see the informational icon. 
- [ ] Veterans viewing the facility operating status on a Vet Center main page will see the informational icon. 
- [ ] Veterans viewing the facility operating status on a Vet Center Locations page will see the informational icon. 
---

## Dev notes
2 places - vets website and the template

**Comment by mpelzsherman** [comment]
Tested and confirmed in staging.

**Comment by mpelzsherman** [comment]
Validated:

https://www.va.gov/albany-health-care/operating-status/

https://www.va.gov/find-locations/?page=1&address=Albany%2C%20NY%20&facilityType=health&serviceType&latitude=42.6512&longitude=-73.755&radius=14&bounds%5B%5D=-74.505&bounds%5B%5D=41.9012&bounds%5B%5D=-73.005&bounds%5B%5D=43.4012&context=Albany%2C%20New%20York%2C%20United%20States

https://www.va.gov/find-locations/facility/vha_528A8
