### ISSUE TITLE
[FSR] Create a temporary maintenance alert 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27201]
## Issue Description
_The DMC is working through backend issues concerning the signature field, so we need to alert Veterans that the FSR will be down for maintenance until 8/1_

---
## Tasks
- [x] _Confirm a solution for the maintenance alert_
Potential options: 
- An alert on its own page that Veterans are redirected to if they click the CTA; need to confirm the feasibility of this solution
- An alert at the top of the page (form results page? form intro page? locations need to be confirmed); this won't prevent submissions
- Other solution(s)?
- [x] _Add the alert to a UXPin prototype_ 
- [x] _Send the alert's content to a VSA content writer for feedback/approval_ 

## Acceptance Criteria
- [x] _The alert's content has been reviewed by a VSA content writer or a ticket for review has been linked in this ticket_
- [x] _The UXPin with the alert has been linked in this ticket_
- [x] _A ticket for frontend implementation has been linked to this ticket_

**Comment by troyriser** [comment]
@rebeccawalsh @rileyorr We used a graphic approach to the Debt Management site redirect (attached for ease of reference). 
Do we/can we do that here? Use of an eye-catching 'Hey, we're sorry' graphic connotes professionalism and modernity (at least in my view). Or do we just want to create a text-only maintenance alert? 

![2_REVISED_DMC_REDIRECT_NOTICE_WITH_VA_LOGO_2](https://user-images.githubusercontent.com/60044631/125467931-03a51a19-b6e6-4ca7-a26d-f5de24061c64.png)

**Comment by rebeccawalsh** [comment]
Just documenting our conversation (re: graphics) here for reference!

For VA.gov proper, messaging shouldn't be contained in imagery, since it is not accessible for screen readers and can cause problems with responsive mobile viewports. We would not be able to control the sizing of the text in those cases, and could potentially be serving up font sizes that are inaccessible. We should focus on clear, concise, and hierarchical content instead.

**Comment by rileyorr** [comment]
@LindaLi123 I'm working through what alert treatment makes the most sense and I was wondering if you could clarify something for me: 
Is the goal to prevent Veterans from submitting FSR's at all, or is the DMC manually checking submissions while fixing the backend issue(s)?

**Comment by rileyorr** [comment]
Update: Learned that we want to prevent _all_ FSR submissions until the fix is implemented 

I propose adding the alert to both the top of the wizard page as well as replace the wizard's existing result for if the 'Veteran debt relief request' pathway. That way folks won't have to go through the entire wizard to see that they can't submit a form, but also prevents them from proceeding if they miss the first alert.
Additionally, if a Veteran navigates to the FSR's intro page then they'll be redirected into the wizard; this should catch any scenario of someone trying to submit an online FSR. Let me know if I'm missing anything with that logic though! 

[The UXPin prototype can be viewed here](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/140406776/simulate/sitemap?mode=i). 

Here's a screenshot of the proposed maintenance alert that provides them the ability to download the PDF version of the form. @troyriser do you have any feedback on this content? 

![Screen Shot 2021-07-19 at 3.10.34 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/73e967b0-8c92-4c03-ab19-d193daa719a8)

**Comment by troyriser** [comment]
@rileyorr On the first bolded line reading, The online request form...", I recommend revising it slightly to read, "The online financial help request form...' for the sake of internal consistency and clarity--internal consistency because the following, non-bolded line refers to it as "...the online financial help request form...". I also recommend inserting the word 'please' in the last line; i.e., "...please fill out the PDF version...". Doing so softens the imperative nature of the direction. Besides, I like 'please' in a directive, especially when it's aimed at me.

**Comment by rileyorr** [comment]
@troyriser thanks for the feedback! I actually had a "The online financial help request form..." version so we're on the same wavelength! I've incorporated the edits and updated the UXPin. 

@LindaLi123 I added a ticket for frontend implementation ([View the ticket here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27576))!
