### ISSUE TITLE
[Tech Debt] - Form Applications - Migrate from AlertBox to va-alert

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#27204]
## Description
Recently, the vsp design system team created a new `va-alert` component and deprecated the existing `AlertBox` component. To keep our form applications up to date with current platform conventions, we need to migrate all existing instances of `<AlertBox />` to `<va-alert>`. 

## Considerations
- Form applications include **Chapter 31**, **Chapter 36**, **686c/674**, and **COE**.
- [Example of va-alert in coe download component](https://github.com/department-of-veterans-affairs/vets-website/blob/fbf18f18a343385786618e2525f56b42e6b92a9c/src/applications/lgy/coe/components/CertificateDownload.jsx#L8-L16)

## Tasks
- [ ] update to `va-alert` in all form applications mentioned above
- [ ] update any unit tests and/or e2e tests that check for statuses embedded in `AlertBox`#27357 

## Acceptance Criteria
- [ ] Alerts are updated
- [ ] Test are updated
- [ ] A PR has been requested for merging
