### ISSUE TITLE
Midpoint Review [DGIB, My Education Benefits]

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#27215]
## Steps to complete Midpoint Review 
- [X] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [X] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

#### Has your team met with the Sitewide Content team for content support? 
- [ ] Yes*
- [X] No

\*If yes, please be sure to include any relevant content artifacts.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Product%20Outline.md)
- Link to or attach prototype or mockups: https://share.goabstract.com/9c202648-de36-45fb-abfc-ab8ec03df2eb
- Link to content brief (if applicable)
- Link to or attach your project's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link): https://share.goabstract.com/9c202648-de36-45fb-abfc-ab8ec03df2eb 
- Link to research plan (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/HCD%20UT%20-%20Research%20Plan%20(REVISED).docx)  and conversation guide (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/HCD%20UT-%20Conversation%20Guide.docx)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) for QA practice area review

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [X] No
 
### Midpoint Reviews can only be scheduled on Monday, Tuesday, or Friday.

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)<br>

**Date/time**

Tue, July 20, 11:00am – 11:30am
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): Shamik Desai
- OCTO-DE Product lead (recommended): name
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Russell Lyons, Leelah Holmes, Jacob Buller, Mark Meardon, Audra Ayotte, Miya Furukawa, Isabel Herrick, Alexander Ferzola, Cesar Santiago
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
meeting moved to 7/27 at 11:00am per discussions with @rlyons89

**Comment by allison0034** [comment]
@rlyons89 the prototype on product outline are missing. Can you please add them asap so we have time to complete the review?

**Comment by rlyons89** [comment]
@allison0034 yes, just added the most recent versions

**Comment by pjhill** [comment]
@rlyons89 -- Do you have any QA artifacts available for review such as --
* QA Test Plan in TestRail with relevant test cases
* Relevant E2E test spec targeted for update or a plan to create a new one
* User stories / acceptance criteria available for test planning
* Any existing test cases created for past efforts on the product that can be re-used for regression testing

**Comment by mnorthuis** [comment]
@rlyons89 There are 3 products/projects included in your mocks: 
- Changes to the 22-1990 form
- Changes to My VA
- Changes to Download VA benefit letters

Which of these efforts are part of this midpoint review?  Is the expectation that we are reviewing all 3 efforts?

**Comment by rlyons89** [comment]
@mnorthuis yes, we have components of our MVP release targeted for those 3 products. 

@pjhill we definitely have user stories with detailed acceptance that we can share; will add ASAP. I will check if any testing plans have been   started

**Comment by rlyons89** [comment]
@pjhill attaching document with user stories for our PI-2 phase of work which runs through end of August. This doesn't yet include user stories for some of the pages and features that will be worked on by our dev team during our PI-3 phase of work which begins end of August.
[MyEducationBenefitsPI2UserStories.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6885643/MyEducationBenefitsPI2UserStories.docx)

**Comment by allison0034** [comment]
@rlyons89 do you have any user flows to go with this prototype?

**Comment by rlyons89** [comment]
@allison0034 yes, adding the link here: https://accenturefederal.invisionapp.com/freehand/document/KVt7Z0odx. There are 2 flow options at this point, which you will see in the link. We are currently doing a dev level of effort assessment to see which option makes the most sense as the path forward. Main flow difference would be at which points we determine the user is applying for the post-9/11 GI Bill and at which point we know they have military service history data available for us to pre-populate the form with.

**Comment by shiragoodman** [comment]
hey @rlyons89 since there were many questions from our team, I think it might make sense for you to use the first part of the Midpoint Review meeting to walk through your current user flow and share where you're still making decisions about your product. My team typically has our feedback to you by EOD the day of the meeting, but since we had difficulties understanding your scope, we may need more time to complete the feedback. We can discuss today.

**Comment by rlyons89** [comment]
@shiragoodman sounds good

**Comment by peggygannon** [comment]
Hi, @rlyons89 per today's midpoint meeting, I recommend you reach out to the sitewide content team for content support for this work. Let me know if you have any questions. thx! 

Here is the link to the template request that help: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md

**Comment by alexander-ferzola** [comment]
Thank you for all your feedback. Before closing this ticket, we would like to recap feedback and update the group with our approach going forward. Please see the design implementation plan below that considers VA.gov recommendations along with our EDU business needs. 
 
**Note:** The following are recommendations for **designs only.** They do not include specific feedback points about user research or developer implementation/staging. Those points of feedback have been documented and can be addressed in the future.  

Tagging the E
[MGIB Updates Midpoint Review Feedback Response.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8542742/MGIB.Updates.Midpoint.Review.Feedback.Response.pdf)
ducation Product Owners for awareness @ericks24 & @TamGIBill
