### ISSUE TITLE
Write Contact Center Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27216]
As a call center agent, I need to know more about the check-in product, so I can answer questions about it when Veterans call.

## Tasks
- [x] Work with Corey to find out about the contact center process
- [x] Write the contact center guide

## Acceptance Criteria
- [ ] Review guide with the team

**Comment by jparker0425** [comment]
@kristenmcconnell I have the below link round the Contact Center process (you may have this already):
 

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md

We will need to work with the Contact Center team given our timeline as well, since we do not technically have all aspects in staging yet. Maybe can go through this with the prototypes for now?

**Comment by kristenmcconnell** [comment]
Draft product guide minus screenshots
[https://app.zenhub.com/files/133843125/4ab7e5b7-3507-47b8-9ea4-f1f9e3629cae/download](https://app.zenhub.com/files/133843125/4ab7e5b7-3507-47b8-9ea4-f1f9e3629cae/download)

**Comment by kristenmcconnell** [comment]
Updated draft based on Corey's feedback. Sent out to the check-in Slack channel for further review.
[https://app.zenhub.com/files/133843125/ac136728-5485-4bef-98dc-fc1c36ed89d1/download](https://app.zenhub.com/files/133843125/ac136728-5485-4bef-98dc-fc1c36ed89d1/download)

**Comment by kristenmcconnell** [comment]
@jparker0425 will add in the screenshots, so I'm closing out this story for now.
