### ISSUE TITLE
New updates to COVID vaccine mini-hub

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27219]
## Issue Description
We have new updates approved by the JTF that need to be input to the COVID-19 minihub. We will also need these to be translated and put into the chatbot. 

[https://app.zenhub.com/files/133843125/46a09983-8990-4a34-b748-25ad7f267e78/download](https://app.zenhub.com/files/133843125/46a09983-8990-4a34-b748-25ad7f267e78/download)

## Tasks
- [x] Update vaccine page (Selina)
- [x] Update chatbot (Selina)
- [x] Review and publish vaccine page (Randi)
- [x] Send to translation team (Randi)
- [x] Input translated copy (Selina)
- [x] Review and publish Spanish page (Randi)
- [x] Review and publish Tagalog page (Randi)
- [x] Send translated pages for final review (Randi)

## Acceptance Criteria
- [x] New content is on live site in three languages
- [x] Chatbot is updated

**Comment by lunascoop** [comment]
@RLHecht I've updated the Covid mini-hub page and it's ready for review. I've also updated the chatbot, but am having issues with the PR. It may have something to do with Chatbot jobs being moved from Jenkins to github actions, but I posted in the Slack channel for someone to review. https://dsva.slack.com/archives/C011BG82ZL6/p1626199542045000

COVID-19 vaccines at VA: http://preview-prod.vfs.va.gov/preview?nodeId=11463

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published the vaccine page. Just let me know when the chatbot is ready for me.

**Comment by RLHecht** [comment]
@lunascoop Here are the translations back for both Spanish and Tagalog pages. 

[https://app.zenhub.com/files/133843125/09fe0b47-62da-44d1-b1bf-8a743e59157d/download](https://app.zenhub.com/files/133843125/09fe0b47-62da-44d1-b1bf-8a743e59157d/download)

[https://app.zenhub.com/files/133843125/0ea00aa6-ce36-48ec-a649-5f5dd7b121b6/download](https://app.zenhub.com/files/133843125/0ea00aa6-ce36-48ec-a649-5f5dd7b121b6/download)

**Comment by lunascoop** [comment]
@RLHecht these translated pages are ready for review. I also needed to fix an issue on the English page. My notes are below.

**COVID-19 vaccines at VA: http://preview-prod.vfs.va.gov/preview?nodeId=11463**
- Deleted sentence in Q. What should I know if I get a COVID-19 vaccine outside of VA? I should've deleted it in my update yesterday. It was after this sentence: Both of these vaccines have gone through the same safety reviews and both require 2 doses to be effective.
- For the same Q&A mentioned above, made this entire sentence a text link for accessibility/508: You can send a picture of your vaccination record card to your VA provider through secure messaging. (also removed period)

**Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413**
- For the Q&A What should I know if I get a COVID-19 vaccine outside of VA?, I made this entire sentence a text link for accessibility/508 and removed the period at the end of the sentence
- Question title Will the vaccines work to protect against new forms (variants) of the coronavirus? wasn't translated in the doc. Used Google translate for now.

**Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359**
- For the Q&A What should I know if I get a COVID-19 vaccine outside of VA?, I made this entire sentence a text link for accessibility/508 and removed the period at the end of the sentence
- Question title Will the vaccines work to protect against new forms (variants) of the coronavirus? wasn't translated in the doc. Used Google translate for now.

**Comment by RLHecht** [comment]
I've reviewed and published these pages. I sent the english and translated copy to Mateo for a final review and I sent Chad the question that was never translated.

**Comment by RLHecht** [comment]
@lunascoop here are the translated versions of the question that was missing. 

[https://app.zenhub.com/files/133843125/704aa082-2914-40b5-bf54-a33dca4ee516/download](https://app.zenhub.com/files/133843125/704aa082-2914-40b5-bf54-a33dca4ee516/download)

[https://app.zenhub.com/files/133843125/39be8d00-6348-4d79-95f0-5f25ce91f1a4/download](https://app.zenhub.com/files/133843125/39be8d00-6348-4d79-95f0-5f25ce91f1a4/download)

**Comment by lunascoop** [comment]
@RLHecht the question title has been updated for both pages, though it seems the Spanish translation was already correct (via Google translate).

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
I just published these changes. Will close the ticket after I validate on the live site.

**Comment by RLHecht** [comment]
@lunascoop Mateo came back with reviews of the Spanish and Tagalog versions of this work. Can you input any changes or let me know if there are any that I should go back to him with for further explanation? Then I can review and publish.
[English-Tagalog content to review 71521 COVID VACCINE August 20 2021[40].docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7139415/English-Tagalog.content.to.review.71521.COVID.VACCINE.August.20.2021.40.docx)

[Spanish-English vaccine content reviewed 8.20.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7139417/Spanish-English.vaccine.content.reviewed.8.20.21.docx)

**Comment by lunascoop** [comment]
@rlhect these changes were implemented during the last updates to the pages.

**Comment by RLHecht** [comment]
Thanks @lunascoop Going to close this ticket.
