### ISSUE TITLE
Review QA Test Case Document

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27213]
To prepare for staging review, test cases must be written for the check-in product.

## Tasks
- [x] Review [test case document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/qa/test-cases.md) that Mark started
- [x] Make updates to functional write ups

## Acceptance Criteria
- [x] Message team to know that review is complete.

**Comment by kristenmcconnell** [comment]
Broke apart one test case to turn it into two: Test Case F and G. Added the error state wireframes and fixed some small typos.

I had a question that I asked Mark Dewey about. He is posting it in the check-in Slack channel. My question was:

When a user has already successfully checked in, but tries again...we can't tell the difference as to why to the token expired, can we? It would be nice to have an additional error state saying something like "You already checked-in for this appointment."

However, I believe the test case document is up-to-date at this point. It is ready for a final review @mdewey @jparker0425

**Comment by kristenmcconnell** [comment]
Adding slack thread for record purposes about the error case mentioned above: 

https://dsva.slack.com/archives/C022AC2STBM/p1626362005032700
https://dsva.slack.com/archives/C022AC2STBM/p1626362006032900
