### ISSUE TITLE
Vet Center - Facility placeholder images 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27222]
## User story 
As  a Veteran preparing to visit a Vet Center location for the first time, I want to see an image of the facility so that I can find it more easily and anticipate the environment. 

## Problems to be solved
Vet Centers can specify other nearby locations which may not yet have been rolled-out and may not have facility images uploaded in Drupal. 
Mobile Vet Centers are going through a rebranding upgrade and may not have images available. 
Community access points are essentially rented space within a community building (church, YMCA, health district, etcmay not be recognizable as a Vet Center or VA owned/operated property. 
The Location page, in particular, is image heavy and looks awkward without images. 

<details>
<summary> Example on Main page </summary>

![image](https://user-images.githubusercontent.com/55411834/125477413-4037a02c-ec89-4deb-a96d-2c8eeb2c9f14.png)

</details>

<details>
<summary> Nearby Vet Centers - Locations page </summary>

![image](https://user-images.githubusercontent.com/55411834/125477595-b718d9af-fc38-499c-bc24-1fdc4966427a.png)

</details>

<details>
<summary>Mobile Vet Centers - Locations page </summary>

![image](https://user-images.githubusercontent.com/55411834/125477805-de330783-0178-4624-be25-508375728da7.png)

</details>

## Scope
**This recommendation is limited to Vet Center pages only**
- For reference, VAMC location pages do not display photos for "nearby" facilities of other types (i.e.: Vet Centers, Cemeteries and Regional Benefit offices). This was an intentional decision to make the "otherness" of these facilities clear to Veterans 

<details>
<summary> Screenshot from Pittsburgh </summary>

![screencapture-va-gov-pittsburgh-health-care-locations-2021-07-21-11_00_45](https://user-images.githubusercontent.com/55411834/126529479-c00e7f91-f1b2-4053-9a8b-fae4b00dcb71.png)

</details>

---
## Tasks
1. Determine the need for placeholders for the following facility types (in two scenarios - 1) for facilities associated with the page being viewed 2) for "nearby" locations (which are not affiliated with the page being viewed)
- [ ] Vet Centers (brick and mortar locations)
- [ ] Community access points (space within a community location)
- [ ] Mobile Vet Centers (on wheels)
2. If placeholder images are recommended, determine what placeholder image(s) should be used for the following scenarios
       - [ ] Vet Centers (brick and mortar locations)
       - [ ] Community access points (space within a community location)
       - [ ] Mobile Vet Centers (on wheels)
3. Determine the recommendation for markup to assist Veterans using assistive tech (or is it hidden?)
4. Where, if any, should the current facility placeholder image be used (or do we need a different one for Vet Centers/ Mobile VCs)

## Acceptance Criteria
- [ ] Design spec for Vet Center Location page, including possible placeholder images, ready for engineering

**Comment by mmiddaugh** [comment]
This is no longer needed as photos are now required from a business process
