### ISSUE TITLE
Data Dog transition

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27235]
## Issue Description
Now that StatD in in DataDog, we need to update our analytics/reporting, especially related to alerting.

---
## Tasks
- [ ] Learn the modeling used in Data Dog
- [ ] Set up reporting/analytics/dashboards 
- [ ] Work with DevOps on metrics and alerts as needed

## Acceptance Criteria
- [ ] Plan for Monitoring is understood and updated

**Comment by mmiddaugh** [comment]
Will return once StatsD is available

**Comment by mmiddaugh** [comment]
progress on this is blocked pending additional functionality

**Comment by mmiddaugh** [comment]
Returning to backlog

**Comment by mmiddaugh** [comment]
no longer needed
