### ISSUE TITLE
QA CH31 KPI Dashboard in Domo - Data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27239]
## Issue Description
As we roll out new products on our KPI dashboards, we need to make sure that our data is accurate and trustworthy.

This ticket is for CH31.
---
## Other Details
@JasonTheBearded is looking into how we can test without pushing directly to Domo production first.
- Now: Filter views to hide new products until they've been QA'd
- Future: Set up a separate, private to Platform, QA dashboard with a month’s worth of data

---
## Tasks
- [ ] Verify that data formats are correct
- [ ] Confirm the data is what is expected (does the info collected measure what it's supposed to measure?)
- [ ] Identify & document invalid values

## Acceptance Criteria
- [ ] The production CH31 KPI Dashboard in Domo has accurate and trustworthy data

**Comment by joanneesteban** [comment]
@bsmartin-ep @jennaouellet - do you have an update on this QA?

**Comment by joanneesteban** [comment]
@bsmartin-ep @jennaouellet - bringing this back up^

**Comment by jennaouellet** [comment]
| Card  | GA | DOMO | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Successful Submissions  | ![image](https://user-images.githubusercontent.com/85642160/126733351-bb1fc90b-84a0-4e6b-b3af-734bca0d3116.png)  | ![image](https://user-images.githubusercontent.com/85642160/126733398-6b2b6d28-94dc-4da7-9439-a8a0e495aad4.png)  | The event count of successful submissions in GA is off by a very small amount. GA reports 15,051 unique form submissions and Domo reports 15,031. |
| Forms by status |   |   |   |
| Unique Users  |   |   |   |
| Avg. Minutes to Complete |   |   |   |
| Forms started |   |   |   |
| Forms submitted | ![image](https://user-images.githubusercontent.com/85642160/126733560-7db884e5-fb50-4aee-b7e8-feb4b6267511.png) | ![image](https://user-images.githubusercontent.com/85642160/126733492-feaa85cf-a1bb-4d49-bdce-3c195a60bf77.png) | GA and DOMO only differ by 1 number. |
| Form completion rate |   |   |   |
| Completion rate by step |   |   |   |
| Completion funnel |   |   |   |
| Completion by device | ![image](https://user-images.githubusercontent.com/85642160/126733783-6aa79378-4f1c-48c2-96ee-aed083350cdb.png)  |  ![image](https://user-images.githubusercontent.com/85642160/126733759-7b2dd8a9-f020-4eec-b539-a4b0283300c2.png) | Matches between DOMO and GA.  |
| Form exits  |   |   |   |
| Avg. sessions to complete  |   |   |   |
| Sessions to complete form  |   |   |   |
| Top pages viewed before accessing the form  |   |   |   |
| Devices used to access the form  | ![image](https://user-images.githubusercontent.com/85642160/126733852-e52c0331-80a8-4299-9457-e1b4c34c694d.png) | ![image](https://user-images.githubusercontent.com/85642160/126733824-6cc58ee3-bcad-4b7d-8d25-468b9a74025b.png)   | Numbers are very close between GA and DOMO  |
| Landing Page - Unique Visitors  |  ![image](https://user-images.githubusercontent.com/85642160/126733904-abf49e69-4836-4b11-ade9-444fc2c5aedc.png) | ![image](https://user-images.githubusercontent.com/85642160/126733895-1f02c19a-9e82-4c0b-a502-0589ee5c10f2.png)  | I couldn’t get this one to come close despite playing around with the week date range in GA  |
| Landing Page - avg. visits per user  |   |   |   |
| Landing Page - avg. seconds on page |   |   |   |
| Landing Page - avg. scroll depth |   |   |   |
| Landing Page - left without visiting form  |   |   |   |
| Landing Page - Top Sources |   |   |   |
| Landing Page - Top Campaigns |   |   |   |

**Comment by JasonTheBearded** [comment]
@jennaouellet For the landing page metrics, your screenshots show pageview counts but do they also include user counts? The unique visitors and top sources are looking at users and not pageview counts.

**Comment by joanneesteban** [comment]
@jennaouellet can you update your QA to include if each test passed or failed? I'm having a hard time seeing if this is complete or not.

**Comment by bsmartin-ep** [comment]
All cards are QA'd.  We included custom reports and segments when used to make future QA easier.

Maybe a quick task to collect all these QA assets into one location?
