### ISSUE TITLE
CMS  - Launch Content-Only Build Process

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2724]
## High Level User Story
Refine the content build process to better meet the needs of both content-editors and developers.

## Hypothesis/(es)
- Delivering a CMS with long build\deploy times to content editors that have used Teamsite in the past (<1min build\deploy) will be met with disappointment.
-  Current CMS code utilizes a very large query to pull CMS data (graphql) and this query will become so large that problems will occur as we scale up users and content on the CMS.
- The graphql query is a large and complex query which makes it very difficult for developers to troubleshoot issues when they arise.

## Goals

- Make the content-build process so fast that content-editors don't even notice it is happening.
- Make the CMS code simple so developers can quickly troubleshoot issues.
- Enable the CMS to add content owners and content without requiring constant development work.

## Measuring Success
- [ ] Content editors can publish content <1min
- [ ] Separate queries used to gather content in the CMS so developers can more easily identify problems
- [ ] Maintain a sub <1min publishing time during scalibility performance testing

## Charter Objectives Impacted
- Optimize the website and content build processes for the needs of contributors. An editor or developer should be able to preview a content or code change in a reasonable amount of time and should not be impacted by other contributors changes.
- Make content and website builds more incremental by focusing just on changes and reducing time spent on building code or content that is still fresh.

## VSP OKR
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.
- KR1: Increase in customer NPS (Customer: Content Editors)
- KR3: Reduction in volume of "non-human-needed" support requests month over month (Public Website Team or CMS Team)

## Related Work
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/704

**Comment by ElijahLynn** [comment]
I think it is Teamsite right (vs Teamcity)?

**Comment by brandonrapp** [comment]
An epic has been created in JIRA to account for the work that we will need from CMS engineers - https://va-gov.atlassian.net/browse/VAGOV-6193

**Comment by ElijahLynn** [comment]
> An epic has been created in JIRA to account for the work that we will need from CMS engineers - https://va-gov.atlassian.net/browse/VAGOV-6193

We are migrating to ZenHub now from Jira (was too closed, not transparent enough). Just an FYI.
