### ISSUE TITLE
Refresh-Appointment list empty states

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27244]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/homepage.md#empty-states) 
- [ ] DESIGN - Designs match the specs (copy is FPO) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by laurenernest** [comment]
Dupe of #25304
