### ISSUE TITLE
Midpoint Review [Caregivers, HCA-Self-Identifying Gender Identity]

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27257]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [ ] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [ ] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

#### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please be sure to include any relevant content artifacts.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)
- Link to or attach prototype or mockups: 
     - [Sketch files](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/76459AA6-CA78-4B4E-A61B-B4AE0E2BD0F9) - Birth sex, Birth sex -open, gender, gender-open
     - [PDF file](https://github.com/department-of-veterans-affairs/va.gov-team/files/6833596/10-10EZ.SIGI.update_7.16.pdf)
- Link to or attach your project's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link): **Designs have the most up-to-date content**

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No
 
### Midpoint Reviews can only be scheduled on Monday, Tuesday, or Friday.

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)<br>

**July 19 @ 3:30pm**
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): Chris Dyer
- OCTO-DE Product lead (recommended): Ming Ligh
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Dene Gabaldon, Dat Tran, Daniel Nalbach
- VFS Content, IA, accessibility, and QA specialists (if applicable): Shawna Hein, Josh Kim, Angela Fowler

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
thanks, @tchrisdyer . Review is scheduled for 7/19. You'll receive feedback asynchronously via this ticket by EOD.

**Comment by joshkimux** [comment]
One thing per page works great here for accessibility! Great work!!

Some consider items:
- Could we provide more short one-liner help texts to explains why certain questions are being asked? Since the page is much less busy thanks to one thing per page, I feel there's an opportunity to make these questions more transparent without all the noise. For example, instead of just "Marital status, required," having a short one liner help text below it explaining briefly why it is required. I hope this can help build trust and transparency.
- If one thing per page persists throughout this entire form, I wonder if we could experiment with two things:
    - sending focus to the first question on the page instead of the stepper "Step 1 of 6..."
    - setting the question as the heading + legend that receives focus and demoting the stepper to a `p` tag similar to gov.uk

**Comment by peggygannon** [comment]
Hello, @tchrisdyer I have no content feedback for this update. thanks!

**Comment by Dene-human** [comment]
@joshkimux Thanks so much for your feedback. In regards to the one-liners. I have been working on this with Danielle. I  updated the body of this ticket with out most recent designs/content. We will work on the Marital status and race pages next.
[Attaching PDF here](https://github.com/department-of-veterans-affairs/va.gov-team/files/6833612/10-10EZ.SIGI.update_7.16.pdf)

**Comment by joshkimux** [comment]
@Dene-human , that's awesome to hear! If the expandable help accordions are nested within the same fieldset as the radio options and legend, they should announce properly in context to screen reader users. We can test more when it's in staging 👍

**Comment by Dene-human** [comment]
@joshkimux Sounds good. Thank you!

@dat-gcio tagging you here for visibility on these recommendations for when you start the dev.

**Comment by mnorthuis** [comment]
No IA feedback for this work.  Thanks!
