### ISSUE TITLE
HLR: Switch AlertBox to va-alert

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27250]
## Description

Switch the `AlertBox` component to use the `va-alert` web component in the Higher-Level Review form

## Tasks

- [ ] Replace `AlertBox` with `va-alert`
- [ ] Update unit tests
- [ ] Update e2e tests (if applicable)

## Definition of done

- [ ] Tasks completed
- [ ] All tests passing
