### ISSUE TITLE
Pre-need: Switch pure HTML alerts to use va-alert

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27254]
## Description

Switch the pure HTML alert to use the `va-alert` web component in the pre-need form

## Tasks

- [ ] Replace HTML alert (`usa-alert`) with `va-alert`
- [ ] Update unit tests
- [ ] Update e2e tests (if applicable)

## Definition of done

- [ ] Tasks completed
- [ ] All tests passing
