### ISSUE TITLE
Add teaser and link to life insurance hub page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27269]
## Issue Description
Stakeholder Lori Hamilton requested an additional link and teaser text to be put on the [life insurance hub page](https://www.va.gov/life-insurance/).

This should be under the Manage your policy and benefits section.
Link to add: https://www.benefits.va.gov/INSURANCE/docs/Instant_Loan_Approval.pdf
Suggested text: Find out how to receive an instant decision on your insurance loan applications. Learn More>

This text should be reviewed for plain language and VA.gov's voice and style.

## Tasks
- [x] Rework and add text and link to page (Randi)
- [x] Review (Beth)
- [x] Publish (Randi)
- [x] Send live link to stakeholders (Randi)

## Acceptance Criteria
- [x] New link and teaser text is on live site

**Comment by RLHecht** [comment]
@bethpottsVADEPO 

Lori said this should go under the Manage your policy and benefits section. If so, my suggested copy is:

**Get an instant loan decision**
Learn about instant loan approval for your insurance loan applications.

If we think it makes more sense to go under More information and resources, my suggestion is: 

*Instant loan approval**
Find out how to get an instant decision on your insurance loan applications.

Let me know what you think.

**Comment by bethpottsVADEPO** [comment]
@RLHecht We don't link to PDFs from our hub--so we need to figure out another solution. I'm talking wtih Mikki about the promo spot, but I'm not sure that's the way to go. Would you look around in the life insurance section and see if there's any page where you link it might be appropriate to link to this PDF?

**Comment by RLHecht** [comment]
@bethpottsVADEPO Could we put it as a related link on the eligibility page?

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you create a single Q&A in R&S and we'll see if this does it? Let me know when it's created--I'll take a look then you can send the preview link to Lori:

**Can I get a loan through my VA life insurance policy?**

Yes. You can borrow against the value of your policy. And you may be able to get a loan approved instantly online through the Online Policy Access website. If we don’t approve your instant loan request, you can still apply for a loan with an Application for Cash Surrender (VA Form 29-1546). [Get VA Form 29-1546](https://www.va.gov/find-forms/about-form-29-1546/)

CTA Button: Learn more about Instant Loan Approval [LINK TO PDF]

Related links:
https://www.va.gov/life-insurance/manage-your-policy/

**Comment by bethpottsVADEPO** [comment]
@RLHecht I updated the above with a second CTA!

**Comment by RLHecht** [comment]
@bethpottsVADEPO The Q&A is built in drupal for when we're ready got send it to the stakeholders.
preview-prod.vfs.va.gov/preview?nodeId=27589

And Platform is reviewing the PDF.

**Comment by RLHecht** [comment]
Platform approved the PDF 7.23 and the preview link was sent to Lori Hamilton on 7.29.

**Comment by RLHecht** [comment]
The article has been published and added to the R&S landing page. Moving to validate and will close after the next deployment.

**Comment by RLHecht** [comment]
work completed. Closing ticket.
