### ISSUE TITLE
[Research, BE] My VA: Overview of Action Items discovery + BE discussion 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27268]
## Background
At this point in the discovery around Action Items we need to have some initial technical discussions with our partners on VA Notify to get a better idea of what is truly possible from BE perspective. This will help inform our research and ultimately assist in defining the scope of the MVP.
 
## Tasks
- [ ] Schedule meeting with VA Notify
- [ ] Provide VA Notify with an overview of current state of Action Items discovery
- [ ] Discuss BE implications with VA Notify 
- [ ] Revise research plan and prototype (as needed) based on BE discussion with VA Notify
