### ISSUE TITLE
[DESIGN] Review action items mocks and refine

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#27270]
## Background

As part of long-term research and continued improvements to My VA post-launch we need to create a cleaned-up design to use in testing for action items so we can learn how we can better elevate action items in the dashboard.

## Tasks
- [x] Review action items with appropriate parties
- [x] Document all feedback and make changes
- [x] Settle on a direction for testing with AJ/Kevin + team

**Comment by tressaellen** [comment]
Designs will be in this [Mural Board.](https://app.mural.co/t/vsa8243/m/vsa8243/1626214472084/d772e75a35186877eabba1863fed8fa2a51a8195?sender=tressafurner7646)

**Comment by tressaellen** [comment]
All mocks are posted in the [Mural board. ](https://app.mural.co/t/vsa8243/m/vsa8243/1626214472084/d772e75a35186877eabba1863fed8fa2a51a8195?sender=tressafurner7646)

Based on feedback from various parties - for testing we've decided to include 3-5 alerts on the My VA page, also we will be testing a prototype that shows a differentiation between viewed/not viewed. If this is technically possible is still pending the technical discovery. 

I still need to figure out some details around some specifics we can show (eg do we show location for appeal hearings), but this ticket is done.

**Comment by tressaellen** [comment]
All mocks are posted in the [Mural board. ](https://app.mural.co/t/vsa8243/m/vsa8243/1626214472084/d772e75a35186877eabba1863fed8fa2a51a8195?sender=tressafurner7646)

Based on feedback from various parties - for testing we've decided to include 3-5 alerts on the My VA page, also we will be testing a prototype that shows a differentiation between viewed/not viewed. If this is technically possible is still pending the technical discovery. 

I still need to figure out some details around some specifics we can show (eg do we show location for appeal hearings), but this ticket is done.
