### ISSUE TITLE
Adjust Claim Label for 686/674 Manual Submissions

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#27272]
## Background
When submitting a Dependents Application (VA Form 21-686c or VA Form 21-674), there are certain use cases that are not able to be processed automatically so we set those statuses to `MANUAL_VAGOV` for manual processing. We have been asked by our partners to add a check to determine whether or not the Veteran is currently receiving pension benefits, and change the claim type code depending on the response. 

## Tasks
- [x] When a 686/674 is submitted, determine if the status is being set to Manual
- [x] If it is, call the new Awards API service
- [x] Adjust the claim label accordingly, based on whether or not the Veteran is currently receiving pension benefits

## Acceptance Criteria
- [x] The claim is using the appropriate label
- [x] A PR has been requested for merging
