### ISSUE TITLE
Search Canary Enhancements

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#27277]
# Tasks
- [x] Discover why the Canary monitoring the search bar did not trigger alerts
- [x] Research the apparently fragile selector being used in the Canary
- [x] Refactor the Canary to use a less fragile selector

New work after re-opening ticket:
Reopening this ticket per a new ask from stakeholders --
- [x] Discuss with analytics existing filters for activity on the platform with search being the focus of the conversation
  * DOMO dashboards not showing activity from existing Canary -- why?
- [x] Research methods for avoiding the Puppeteer script's activities in GA
  * Blocking GA
  * Setting Do Not Track in Header in Puppeteer script

**Comment by rjohnson2011** [comment]
Per the original ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17631
the main requirement is verifying search brings results and not a redirect to va.gov.

**Comment by pjhill** [comment]
Do we know if this [PR ](https://github.com/department-of-veterans-affairs/vets-website/pull/17586)was the cause of the Canary failing?

**Comment by rjohnson2011** [comment]
@pjhill Yes, not only was the PR merged the day the failures began, the HTML structure of the search results page was modified in `searchApp.jsx`.
This interfered with the Canary search alert XPath selector ```      
await page.waitForSelector("#react-root > div > div:nth-child(3) > div.usa-width-three-fourths.medium-8.small-12.columns > div > div:nth-child(4) > ul > li > a > h5", { timeout: 30000 });
``` which no longer existed and failed. 
A refactor is being put into place that removes the full path in locating desired components on pages.

**Comment by rjohnson2011** [comment]
Awaiting PR approval https://github.com/department-of-veterans-affairs/devops/pull/9579

**Comment by pjhill** [comment]
The PR has been merged. This work is completed.

**Comment by rjohnson2011** [comment]
Opened a support ticket with Analytics team. Confirmed with @bsmartin-ep that Canary requests are not included in metrics due to GA anti-spam bot filters. For this reason, the 2nd part of the ticket (do not track headers) are not necessary.
