### ISSUE TITLE
Separate the Webpack-only build into a new command

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2728]
## Task
As part of the decoupling effort, we need a way to build only Webpack assets.

## Acceptance Criteria
- [x] A command can be run which builds only the Webpack assets
- [x] A command can be run which runs the webpack dev server to watch the webpack assets
- [x] This doesn't disrupt the current build process
- [ ] A command can be run which grabs the latest content and files, and puts them in the appropriate `build/` directory without overriding the `generated/` directory

**Comment by cvalarida** [comment]
I moved the remaining AC to anew ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2806
