### ISSUE TITLE
[Tech-Debt] Swap out LGBT with LGBTQ+ in both System Detail pages and playbooks that need to be dispersed. [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27286]
## User Story
As a VHA Digital Media web manager, the LGBT pages need to be updated to LGBTQ+, so national pages match required changes submitted and approved by VA.

## Goal
Remove tech-debt for all upcoming dual-state systems.

## Resources - Tools - Documentation
See Public Websites - Content review

## Tasks
- [x] Find and replace all LGBT with LGBTQ+ for systems not yet in Dual-State
- [x] Update all playbooks that have not been released to PAOs with updated System and Facility health service language.

## Acceptance criteria
- [x] LGBTQ has been updated on systems ready or in queue for Dual-State
- [x] LGBTQ+ has been updated in all upcoming playbooks.

**Comment by bcastoe** [comment]
#27286 - Swap out LGBT with LGBTQ+ in both System Detail pages and playbooks that need to be dispersed. - completed and moved to validate; VISN 10 and 20 have been completed.
