### ISSUE TITLE
Add widgets to /manage-va-debt

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#27305]
## Issue Description
The content separation work completed by platform moved the static page for /manage-va-debt on localhost:3001 -> localhost:3002 and as a result does not load any content

![listing directory manage-va-debt 2021-07-02 15-50-24.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/03f5480b-5eeb-411d-8cfe-707beab3992f)
---
## Tasks
- [ ] Add widgets for FSR and Debt Letters to localhost:3001 

## Acceptance Criteria
- [ ] When navigating to /manage-va-debt on localhost:3001 the page should load button widgets for FSR and Debt Letters
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
