### ISSUE TITLE
**DECISION TOOLS SPRINT 52 PRIORITIES (Jul 14-27)**

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27308]
<hr>

## 🏖️ Sprint 52 Vacation/PTO/Holidays
- Cindy PTO - 7/14/2021

### Find a Form Bug Fix 
- [x] Mark - fix for issues he's found in Forms API
- [x] Marci - test Mark's changes extensively on Staging 7/15

### FIND A VA FORM PDF DOWNLOAD INSTRUCTIONS, EPIC #26816
- [x] (Zach) - Find a VA Form - PDF Instructions - Implement single alert option on Staging for user research #27424
- [x] (Zach) - Find a VA Form - PDF Instructions - Implement multiple alert option on Staging for user research #27426
- [x] (Cindy) - Update research plan & convo guide to account for testing approach change: #25924 
- [x] (Cindy) - Prep Tasks for Research: Find a VA Form PDF Download Information #27475

### DISCHARGE UPGRADE WIZARD CHANGE PDF LINK FOR AIR FORCE RESPONDENTS, EPIC #24925
- [x] (Zach) Discharge Upgrade Wizard - Change PDF link for Air Force respondents to a link to AFRBA portal #23071

### SEARCH UI CONSISTENCY, EPIC #21055
- [ ] (Cassandra)  - Stretch Goal **Search UI Consistency** - Document design pattern #24597

### DISCOVERY
- [ ] (Cassandra & Zach) [Discovery] Determine Discharge Upgrade Wizard impact to user flow #27143
- [x] (Marci) - Review data from Yellow Ribbon API #26829
- [ ] (Zach) - [DISCOVERY] Yellow Ribbon API data/GI Bill Data join with Rails #26829

### TECH DEBT
- [x] (Marci) - Content request for "Go to online tool" verbiage (blocker for accessibility issue from Staging review)  #27427
- [x] #27467
-  [ ] ~(Zach) [Content organization] Your page doesn't follow heading hierarchy. Headings aren't properly nested, and headings and/or labels aren't relevant to the page. #26904~ MOVED TO SPRINT 53
-  [ ] ~(Zach) 508-defect-2 [SEMANTIC MARKUP]: Search results should be semantically written consistently #26353~ MOVED TO SPRINT 53
-  [ ] ~(Zach) STRETCH [Color, typography and visual elements] Your content or feature uses color as the only method to provide information. #26905~ MOVED TO SPRINT 53

###  🗨️  Discussion Topics/Grooming 
- [ ] Well-groomed issues for Yellow Ribbon discussion
- [ ] Topic
- [ ] Topic

**Comment by MarciMcGuireGCIO** [comment]
**2021/07/16**
- Zach finished research on Yellow Ribbon data
- Working on PDF alerts; hope to have it ready for review on Monday
- Cassandra is heads-down on harassment tool; lots of flowchart updates

**Comment by MarciMcGuireGCIO** [comment]
2021/07/19

- Zach - trying to get both versions of PDF instructions merged.  Some flaky end to end tests. Hopefully merged by 5:00 or 5:30
- Cassandra - Harassment tools; needs to sync up with Zach about the Discharge Wizard

**Comment by MarciMcGuireGCIO** [comment]
**2021/07/23**
- Air Force portal link for Discharge Upgrade Wizard is on Staging for internal review
- Marci contacted Shira to see if we can hold off extensive testing until the larger change goes in
- Cassandra will be taking notes for the research study - CA hours.  **Create a 2-point issue**
- Breakpoint in the design grid doesn't match up, but that's a known issue.  It wraps wherever the design system defined
- Zach added some test coverage to the Discharge Upgrade Wizard
- There are no test cases in TestRail as far as we know
