### ISSUE TITLE
Incorporate COE Recommendations

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#27319]
## Background
Now that the COE feature has had some feedback and analyzed, we need to incorporate that feedback into the feature so that we can be sure we have improved the feature as much as possible based on real Veteran and stakeholder input.

## Tasks
- [x] Using feedback, create a changelog of changes for FE to make 
- [x] Update any applicable mockups or prototypes

## Acceptance Criteria
- [x] A changelog has been added to the `/research-design/` folder for this feature
- [x] Mockups/prototypes are updated

**Comment by sporeboy** [comment]
Revised flow diagram here: https://xd.adobe.com/view/03f5874d-242c-4e74-9616-641276b2b238-56a6/

**Comment by sporeboy** [comment]
Here is the flow diagram with use cases indicated: https://xd.adobe.com/view/03f5874d-242c-4e74-9616-641276b2b238-56a6/

Here is the starting point (landing/content page) for the UXPin prototype: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312

Overview of the big things:
- Revised content on landing/content screen leading to intro
- Unauthenticated state for into (no subway map)
- All states for /Eligibility screen built: auto, available, pending, denied
- Document lists elevated on doc upload screens

**Comment by sporeboy** [comment]
Extensive changelog available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/coe-changelog-072121.md
