### ISSUE TITLE
Authenticated Experience: Sprint 55 (8/25 - 9/7)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27314]
## Priorities

1. Complete Notification Preferences build
2. Test Notification Preferences: with VA Profile and VA Notify; and internally
3. Action Items research synthesis

PTO
- all team members 9/6 (Labor Day)
- Lihan 8/30 - 9/10
- Tressa 9/6 - 9/10
- Taylor 9/3

## Notification Preferences
**PM**
- [ ] Finish test case documentation #26223
- [ ] Submit test plan ticket for Notification Preferences QA prep #28042
- [x] Testing with VA Profile #28469
- [ ] Internal testing #29256

**Design**
- [x] Design solution for redirecting users back to their task after making profile edits #28636
- [x] #29276
- [x] Testing with VA Profile #28469
- [ ] Internal testing #29256
- [x] Mock-up an approach to orienting users #27113
- [ ] Create resources and support page to support new notification preferences feature #22887
- [x] Update mocks and FE documentation #29646

**FE**
- [ ] Complete build
    - [ ] Update UI to match new designs #28503 
    - [ ] Notification settings display bug after removing email address and mobile phone #27864
    - [ ] Implement conditional display rules for Prescription shipment and tracking notification item #28982
    - [x] Styling of "disabled" radio buttons is wrong #28987
    - [x] Notification radio buttons do not work well on mobile #28988
    - [x] Saving message can have FOUC #29002
    - [ ] Implement recommendations for radio button spacing #29473
- [ ] Explore technical solution for redirecting users back to their task after making profile edits #28584
- [x] Testing with VA Profile #28469

**BE**
- [x] Testing with VA Profile #28469

## Action Items Discovery

**Design/Research**
- [x] Research synthesis #26602
- [x] Topline summary #29224
- [x] Research Summary #29226

## Profile

**FE**
- [ ] 508-defect-2 [AXE CORE]: Heading should not be focusable while within the mobile profile menu button #23254
- [ ] Implement improved "remove" [contact information] button functionality/UX #27169 

## Backend
- [ ] Caregiver team support
- [ ] Fix VA profile ADDRVAL111 DualAddressError #28396
- [ ] Fix PII sanitizer variable mutation #29383
