### ISSUE TITLE
Interview VSOs

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#27322]
## Story
VSOs perform a critical part of the Veteran journey for more benefits and we need to talk to them so that we can be sure to capture any other functionality in our features.

## Tasks
- [x] Reach out to Bill Meadows
- [x] Connect with Josh + Leyda + Dene'
- [x] Schedule a meeting with a reasonable number of VSOs (3 -5)
- [ ] Conduct interviews with VSOs

## Acceptance Criteria
- [x] Calls are scheduled
- [ ] Interviews conducted (STRETCH)
- [ ] Notes have been documented in GH for team review (STRETCH)

**Comment by candy-gcio** [comment]
4 interviews are scheduled for this week (Aug 11-13)
