### ISSUE TITLE
Add entry on typographical quotation marks to style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27328]
## Issue Description
We need to add an entry to the style guide under the Punctuation section about using the curved typographical apostrophes in text rather than the straight up and down ones. 

---
## Tasks
- [x] Add entry to style guide (Randi)
- [x] Review update (Danielle/Beth)
- [x] Merge into master

## Acceptance Criteria
- [x] New content is live in the style guide

**Comment by RLHecht** [comment]
@bethpottsVADEPO or @DanielleThierryUSDSVA I added an entry for both apostrophes and quotation marks to the punctuation page. I'm not sure if we need to say anything more than to use the curly ones instead of straight up and down so I left it simple. If you think I need to give direction about cutting and pasting into the CMS or anything more specific let me know. Here's the PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/496

**Comment by RLHecht** [comment]
This PR was reviewed and merged. Moving to validate and will close once changes are live.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
