### ISSUE TITLE
Conduct Walkthrough of COE Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#27321]
## Background
We need to perform an end to end walkthrough of what we have in staging to ensure we are as far along as possible before sharing with LoB.

## Tasks
- [x] ~Schedule some time (Friday morning?) with Team~
- [x] Conduct Walkthrough of COE Feature
- [x] Note any changes

## Acceptance Criteria
- [x] Walkthrough has been completed
- [x] Changes have been noted for completion

**Comment by sporeboy** [comment]
Walked-through staging instance of COE. Changelog notes differences between staging and COE prototype. Changelog is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/coe-changelog-072121.md
