### ISSUE TITLE
[FSR] Fix breadcrumbs

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#27338]
## Issue Description
After the content separation work it was noticed that the breadcrumb path for  "Manage VA Debt" is wrong and redirects to http://localhost:3001/manage-va-debt/request-debt-help-form-5655/manage-va-debt

![Screen Shot 2021-07-14 at 1.03.37 PM.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/65edbc4d-cf93-4644-bd08-377f22df7d23)
---
## Tasks
- [ ] Manage VA Debt breadcrumb should redirect to the Manage VA Debt page http://localhost:3001/manage-va-debt
- [ ] Breadcrumbs should match the [mock](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701377/simulate/sitemap?mode=i) 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
verified issue only exists for local development closing
