### ISSUE TITLE
Midpoint Review [Deb Resolution, Medical Copays]

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#27333]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

#### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please be sure to include any relevant content artifacts.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26646

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Product_Outline_Medical_Copays.md)
- Link to or attach prototype or mockups: [Mockup](https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages//simulate/sitemap?mode=i)
- Link to content brief (if applicable) **N/A**
- Link to or attach your project's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link) https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Medical_Copays
- Link to research plan ([Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/research-plan.md))  and conversation guide ([Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/conversation-guide.md))
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_ **N/A**
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) for QA practice area review **N/A**

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No
 
### Midpoint Reviews can only be scheduled on Monday, Tuesday, or Friday.

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)<br>

**Date/time**
 **Monday 7/19th 3:30 to 4:00 pm**
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): name
- OCTO-DE Product lead (recommended): name
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): names
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@LindaLi123 the Monday 9/19 timeslot is not available. We do have availability on Tuesday 7/20 at 11:30am... does that work for you?

**Comment by shiragoodman** [comment]
@LindaLi123 the Monday 7/19 slot is already booked, but since this is asynch we can get you feedback by EOD Tuesday 7/20. Thanks.

**Comment by rtwell** [comment]
hey gang! thanks for all the hard work on these complex forms! I do have questions about these mockups, and it would be far more efficient for me to ask the team directly. When can we meet?

**Comment by LindaLi123** [comment]
@rtwell Hello Ryan,  we can try to coordinate to meet in the next few days,  do you only want to meet with me or you would like to include our researchers as well?

**Comment by shiragoodman** [comment]
@rtwell @LindaLi123 were you ever able to connect? I was reviewing old tickets and came across these (what look to be unresolved) comments.

**Comment by LindaLi123** [comment]
Hello @shiragoodman  I was in one of the meetings with Ryan and our researchers a few weeks ago.  I think we got everything sorted out.  @rtwell Is there anything still pending?

**Comment by rtwell** [comment]
I haven't seen any of the updates we discussed, but we did make some decisions on a path forward.

**Comment by LindaLi123** [comment]
Hello @shiragoodman I think all we have pending now is the QA and everything else is done.
