### ISSUE TITLE
Mapbox Release

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2734]
@rianfowler commented on [Tue Feb 12 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16901)

The facilities locator is 2 versions behind. Documentation on the current version is difficult / impossible to find. 

---

@rtluu commented on [Thu Feb 14 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16901#issuecomment-463792308)

@WinishaSmith, want to put this on your radar as something to think about for your group

---

@WinishaSmith commented on [Fri Feb 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16901#issuecomment-464097645)

Thanks @rtluu. @rianfowler Are you able to provide additional details? I can review this with the team during grooming today but just curious as to where we should be looking to see our current version.

---

@rianfowler commented on [Fri Feb 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16901#issuecomment-464106433)

@WinishaSmith 
ours: [map box 1.0](https://github.com/department-of-veterans-affairs/vets-website/blob/4f18208a2c1e5959e0a23695f4beb080a94ebbcf/package.json#L215) 
current: [map box 3.1.1](https://github.com/mapbox/mapbox.js/)

The main issue is documentation- I was not able to find docs on the version we're using because. It looks like it's over 2 years old. 

---

@WinishaSmith commented on [Fri Feb 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16901#issuecomment-464157571)

Thanks, we'll queue this up for our next sprint.

---

@ncksllvn commented on [Wed Mar 13 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16901#issuecomment-472467760)

Just an FYI that we're going to shelve this until @aubreyarcangel and I can find some time to work on this together.

---

@WinishaSmith commented on [Wed Mar 20 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16901#issuecomment-474929001)

Putting this on pause for now.

**Comment by mmiddaugh** [comment]
**Prioritization:**
We know we are locked into Mapbox for the foreseeable future so need to upgrade and hope it resolves some existing bugs.

**Grooming considerations:** 
API has changed
Will need to determine upgrade did not break current functionality

**Comment by mmiddaugh** [comment]
**Mapbox Contract**
- November 6, 2019: Per email from Nancy Smith (Oddball), We have been switched to the annual license version of Mapbox and have paid for an entire year, effective October 1, approved by DSVA.

**Comment by mmiddaugh** [comment]
Updating this issue to reflect this is for the upgrade effort alone. Discovery will be done in [3174](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3174).

Will need tot groom this upgrade/implementation once Discovery is complete.

**Comment by mmiddaugh** [comment]
@brangi 

We need to treat this work as a full release and follow the process on our way to moving it into Production. 

### Usability
- [ ] Create a [test plan](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Profile/Direct%20Deposit/Discovery%20&%20Research/Research/Usability%20testing/Research%20Plan.md)
  - [ ] Is the entry point established?
  - [ ] Is there a better entry point?
- [ ] 508 Compliance
  - [ ] Review [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/508-checklist-wip.md)
  - [ ] [Request 508 Audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md)
  - [ ] Ensure the feature is tracked within the [508 Product Sheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-product-review-list.md)  

## Development
_Do we need to merge the FE and BE tasks?_  
### General Engineering Tasks  
- [ ] Documentation for quickly addressing when things go wrong  
- [ ] Establish contacts for oncall support: who do we contact if the application is failing?  What kinds of failure modes are likely?  
### Backend Tasks  
- [ ] Investigation of applicable services  
  - [ ] Which API service does this feature use?
  - [ ] Collaborate with Frontend on Error Handling
  - [ ] Investigate  the common area for error types
  - [ ] Define or reference a known resource
- [ ] For PRs: first review internally with BE or another engineer before the BE Team
  - [ ] Once internally reviewed, share with the BE Review Team at the VSP (team name?)
  - [ ] Ensure that [feature flags](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-flags/) are set appropriately to be [toggled](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/feature-toggles.md) 
- [ ] Documentation and points of contact for any new backend dependencies
- [ ] Links to important dashboards for investigating relevant issues
### Frontend Tasks
- [ ] Investigation
  - [ ] What will be involved in using the API service to pull and display data?
  - [ ] List and define what the main components will be for the feature to function properly
  - [ ] Collaborate with Backend on Error Handling
  - [ ] Investigate  the common area for error types
  - [ ] Define or reference a known resource
- [ ] For PRs: first review internally with FE or another engineer before the FE Team
  - [ ] Once internally reviewed, share with the FE Review Team at the VSP (team name?)
  - [ ] Ensure that [feature flags](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-flags/) are set appropriately to be [toggled](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/feature-toggles.md) 
  - [ ] Entrance pages (i.e. supporting static content) in place
### Security/ATO
- [ ] Establish who among VSP we should talk to about Security Reviews
  - [ ] What is the review process?
- [ ] Review the [ATO Procedures](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md)
- [ ] Request a [preliminary ATO review](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md#request-a-preliminary-ato-review)
- [ ] Request a [pre-launch ATO review](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md#request-a-pre-launch-ato-review)
### QA
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance) from platform 

### Testing
- [ ] Create a test plan from an overall engineering perspective  
  - [ ] Build, test, audits (508, content, security, load, CI/CD, passing on all browsers, etc) in a feedback loop  
  - [ ] Code coverage requirements
- [ ] Develop testing infrastructure, refer to established documentation  
- [ ] Define threshold or definition of high-severity bugs
- [ ] Document any high-severity bugs for future reference  
- [ ] Establish contacts for errors to be reported to
  - [ ] Errors get sent directly to the team
- [ ] Establish steps to take to move feature into [staging](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md) or within 
- [ ] Tested in prod with back-of-house people and systems

## Analytics
- [ ] Confirm that the new feature/product is stable and visible in staging.va.gov  
- [ ] Engage with the Analytics Team about what is to be launched  
- [ ] Review [KPI/metrics spreadsheet](https://docs.google.com/spreadsheets/d/1e9bqzjBnibiCWXWNMcK-fJOw7cjXVdx5M6gmC4phlfg/edit#gid=1554481611)
## Support
- [ ] Does the Call Center have documentation?
- [ ] Have they asked for anything else?
- [ ] What else should we say about 

## Pre-release
- [ ] Call Center is prepared for launch with updated scripts/documentation as needed
- [ ] VA web comms team is aware of this launch and has accurate messaging
- [ ] Product Outline is updated
- [ ] Downtime UX and error messaging documentation complete
- [ ] "Learn and Improve" plan written: KPI measurements, analytics reporting, next phase of features to build

## Release Plan
- [ ] Refer to in-depth [Release Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)

## Consider Deliverables and Artifacts
- [ ] Ensure that these are noted and stored for easy access
  - [ ] Include contact information in case further discussion is required

## Launch
- [ ] Go/No-go from each team member
- [ ] Define what is being tracked
- [ ] Define other last minute items
- [ ] Review the [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)

## Post-Mortem
- [ ] List and define any issues that impeded the process
- [ ] Create post-launch coordination plan including calls with stakeholders and call center 
- [ ] Coordinate with Call Center to monitor calls 
- [ ] Ensure monitoring and resolve issues in 24 hours
- [ ] Collect and report metrics from Google Analytics
- [ ] Schedule regression testing
