### ISSUE TITLE
[Debt Portal] Ideate and design payments functionality for debt portal (v1)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#27343]
## Issue Description
**User story**
As a Veteran, I want to be able to see my payment history and payment agreement information so I can know where I stand with my debt.

We'd like to create a preliminary design so that we can create some guidelines for engineering discovery for the feature. It's likely that we will create something that won't be possible, so this is v1 and will serve as a starting point.

---
## Tasks
- [x] Ideate designs for payment history and payment agreements 
- [x] Create designs and upload them to UXPin

## Acceptance Criteria
- [x] Designs created and linked to this ticket

**Comment by rebeccawalsh** [comment]
Helloooo! 

Riley and I have been discussing these payment features amongst other larger usability changes and consolidation between Debt Portal and Copayments Tools. We will be revisiting some of our ideas and whatnot on Monday, but here's an update. What we've come up with are:

## Repayment agreements
We propose to reconfigure 'Status' and 'Next step' into a single call-out card, where additional information about repayment agreements can be kept (examples of cards below). These different call out cards would be shown conditionally based on the diary code of the debt. Additional information about the repayment agreement itself will need to be pulled into these cards, and additional technical discovery will be required.

**Next steps:**
- Do an audit of all diary codes to ensure current categorization makes sense and pull in any necessary 'out of scope' codes
- Create designs for each category of diary code, along with their summary card and history table content.
- Work with engineering to assess feasibility of designs 

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/b607429a-3e5f-420a-b533-5afa65c8394b)

## Payment history
For payment history, we propose to augment the 'Debt history' table to include payments and payment status. This will involve some technical discovery, SME involvement, and content rewrites.
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/48b9afd7-5125-4747-917e-74df613bad7d)

**Comment by rebeccawalsh** [comment]
Designs have been uploaded to UXPin here: 
- [Portal summary page](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57#/pages/140629615/simulate/sitemap?mode=i)
- [Portal detail page](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57#/pages/140629718/simulate/sitemap?mode=i)
- [Example 'next step' states](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57#/pages/140629717/simulate/sitemap?mode=i)

We will need to meet as a team to discuss these designs and determine next steps.

**Comment by jason-gcio** [comment]
Let us know if we can help at all with the Payment History feature...its definitely one of the more popular tools we put out!

**Comment by rebeccawalsh** [comment]
@jason-gcio Hey Jason! We're working on combining the "Payment History" tool under a financial static hub page, but won't be touching the functionality as far as I know. If we do, we'll reach out!

In this ticket, the 'payment history' is referring to payments that the veteran has made toward their debt, and this information will be housed on the detail page of a debt or bill.
