### ISSUE TITLE
Investigate LH Integration Endpoints

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#27355]
## Story/Background
Now that Lighthouse has finished the work on the endpoint we will use for View Representative, we should investigate and test the endpoint so that we can set up a `vets-api` endpoint that uses the Lighthouse endpoint.

## Considerations
The URL for the Lighthouse endpoint documentation is https://developer.va.gov/explore/benefits/docs/claims?version=current

## Tasks
- [x] Determine what authentication method we should use of the Lighthouse endpoint
- [x] Check in with Mark Greenburg and see about a an auth/key
- [x] Test the Lighthouse endpoint
- [ ] Document how the Lighthouse endpoint should be used by `vets-api`

## Acceptance Criteria
- [ ] We have documented how the Lighthouse endpoint will be used by `vets-api`
- [x] Access has been granted
- [x] API is working
- [ ] A PR has been requested for merging, if needed

**Comment by RudyOnRails** [comment]
Here's the api docu for POA: https://developer.va.gov/explore/benefits/docs/claims?version=current
