### ISSUE TITLE
Create Ten 0538 PDFs for Centralized Mail

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#27371]
## Story
The Centralized Mail folks would like 10 different PDF 0538 so they can run them through the Centralized Mail automated system to update their diary entries, indicating they have verified their dependents as of that date.

## Considerations
- The only (form fields) needed are:
  - (1) Veteran's Name - `Required for establishment`
  - (2/3) SSN or File Number - `Required for establishment`
  - (5)  Address- we do address update, but not a required field for establishment
  - (6) Telephone Number- we do a phone number update, but it’s not a required field for establishment
  - (7) Email Address. we do email update, but not a required field for establishment
  - (8) Has the Status of your Dependent(S) changed? **NO** - `Required for processing`
  - (14a)   Signature - `Required for establishment`

- We should number and name each pdf file something helpful in case we need to reference them: 
  - 1-LastName.pdf
  - 2-LastName.pdf
  -   ...
  - 10-LastName.pdf
  
- For each pdf, in just plain text, we should include that Veterans diary entry (date) before it is sent in for processing so we can test easily and see the entry is updated.

## Tasks
- [x] Create ten 0538 pdfs with the required fields completed (Others are optional for this feature, at this time)
- [x] Accompany pdfs with a text list that maps the pdfs to their current diary entry date

## Acceptance Criteria
- [x] PDFs/diary entries are shared with Jason

**Comment by jason-gcio** [comment]
I thought this first one looked good (1-brooks.pdf)
