### ISSUE TITLE
Backend discovery: GeoBISL 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2738]
## Problem Statement
How might we streamline the data sources/api?

## Background

**Caveat: The following is the background as understood in Fall 2019.**
- Facility locator queries the ArcGIS.com REST endpoints to populate facility locator map views and display facility detail pages. The map data is pulled once per day from ArcGIS and stored locally in vets-api's Postgres database. 
   - Vets-api is not subject to request latency due to slowness due to the ArcGIS external service for the facility locator service. It performs this sync using a set of Sidekiq jobs defined in app/workers/facilities and scheduled in config/sidekiq_scheduler.yml, both in the vets-api repository.
- ArcGIS is a hosted map data endpoint provided by ESRI. 
- GeoBISL team is the account holder for ESRI and is responsible for data and configuration management of the VA data hosted at ArcGIS.com.
-  If ArcGIS.com as a whole is up but the VA REST endpoints are not responding properly it is likely to be a GeoBISL configuration issue.

- See also: https://github.com/department-of-veterans-affairs/va.gov-team/blob/3567fdb5b22f221967f879345b52bbb719297e98/products/facilities/facility-locator/data/how-the-api-file-is-made.md

## Goal
Streamline api and data sources

## Objectives or Key Results this is meant to further
- Objective 1: Enhance the search process
---
## Tasks
- [ ] Determine the GeoBISL data flow and what data the Facility Locator consumes from GeoBISL
- [ ] Understand how that dataflow integrates with the Lighthouse API
- [ ] Propose alterative solutions

**Comment by davidconlon** [comment]
This is likely more of a Facilities API thing than something specific to FL. 
Thoughts @mmiddaugh

**Comment by mmiddaugh** [comment]
No longer relevant with most recent changes to Lighthouse API
