### ISSUE TITLE
Design intent [Public Website Team - Harassment Reporting Tool (HRT)]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27381]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [x] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No (Unsure)

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/product-outline.md)
- [Mural Link - Flow ](https://app.mural.co/t/vsa8243/m/vsa8243/1626971557496/936e375b82d0af58a76ef2b36da3ecf4585bb118?sender=u7ad68f2a3a694c00d8a38130)

## Meeting attendees from requesting team
- Designer(s) (required): Cassandra Allen
- Product Manager (required): Brian Lloyd 
- OCTO-DE Design Lead (required): Ryan Thurlwell
- OCTO-DE Product Lead (recommended): John Hashimoto
- VFS content, IA, and QA specialists (if applicable): name(s)
- Other stakeholders you want to invite (if applicable): Soni Meckem (Presidential Innovation Fellow)

### Design Intents can only be scheduled on Monday, Tuesday, or Friday. 

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York). <br>

**07.23.2021/2-2:30PM:**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
For the Design Intent, you'll receive feedback from design and IA only. You won't receive feedback from accessibility, content, or QA, as it's too early in the development process.

Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @brianalloyd  - the Friday 7/23 timeslot is already booked. We have openings on Monday 7/26 and Tuesday 7/27. Please let me know what works for you!

**Comment by brianalloyd** [comment]
Hi @shiragoodman let's go with 7/26, thank you.

**Comment by shiragoodman** [comment]
@allison0034 will you please schedule for 7/26 at 3:30pm? thanks!

**Comment by allison0034** [comment]
This has been scheduled for 7/26 at 3:30pm

**Comment by brianalloyd** [comment]
Thanks @allison0034 appreciate it.

**Comment by mnorthuis** [comment]
@brianalloyd I do not have any IA feedback at this point, but likely some questions. :-)  Can you please submit the IA request and we can use that to track those questions and work?  If you have a sitewide content ticket created, it would be helpful to link those together as well.   Thank you!!

**Comment by brianalloyd** [comment]
@mnorthuis I submitted an [IA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27911) in support, fairly light in details at the moment as we've been consumed with landing page, form flow and mocks at the moment but do plan to hold a roundtable discussion with all parties to review initial thinking in regards to page/link placement, URL strategy and beyond.

**Comment by brianalloyd** [comment]
All actions are complete on this ticket, plan to follow up with IA actions in that ticket.
