### ISSUE TITLE
CMS Sandbox | Translation Management

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#27380]
## Objective 

Explore the addition of preliminary translation management data to back-end CMS content in order to define requirements for further functionality of front-end implementation.

## Story

As a product manager within the C&L team, I would like to find a programmatic solution to support  in-language content and eliminate the very manual, labor intensive approach we've used to date.

Currently, the C+L team has created separate Drupal nodes for non-English content pages. This is supported via hooks into the react app to identify the language on the front-end. This process requires a lot of manual support and is not a scaleable approach. 

By identifying and testing several approaches in the CMS sandbox, we aim to find an approach that improves on the current solution and allows us to more easily add additional content as well as additional languages in the near-term.

The approach we select should also makes it easy for us to migrate to i18n in the future. 

Potential work-arounds may include:
-  using meta data tags
- naming conventions
- pathways (changing the alias of the page and letting that be the connector for the short-term) 
- UU IDs

# Acceptance Criteria (will be included in associated stories as appropriate)

- [ ] Query and return the correct page by using a relational module
- [ ] Demonstrate the ability to integrate with a 3rd party API and GraphQL by pulling a content page from Drupal as a file (Json?) that can be sent over the API for translation
- [ ] Store the newly translated content in Github and pass this new translated content back to Drupal.
- [ ] Confirm the approach works for both teamsite as well as modernized site (valid A/C???)
- [ ] Confirm accessibility is supported
