### ISSUE TITLE
[vamc] Remove "disallow" entries from Robots.txt file on July 22nd, for the following systems

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27400]
## Story
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
- [x] Remove the following system names from robot.txt file on July 22nd, 2021
**Redirect is scheduled on Wednesday July 28st**

- [x] syracuse health care
- [x] butler health care
- [x] salt lake city health care
- [x] new jersey health care
- [x] oklahoma city health care

## Acceptance Criteria
- [x] All System names are removed from robot.txt file on July 22nd, 2021
