### ISSUE TITLE
Find a VA Form - PDF Instructions - Implement single alert option on Staging for user research

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27424]
## Issue Description
Implement PDF download info alert that is displayed once at the top of the page.

---
## Tasks
- [ ] Build out an alert at the top of the Search results page using the following text and URL.  

  - We recommend that you download PDF forms and open them in Adobe Acrobat Reader 
  - Get instructions for opening PDF forms in Acrobat Reader](https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form/)  
  - It will be based on this mockup:
https://user-images.githubusercontent.com/68560244/125663491-d94300de-4fa9-49c9-aa6a-b641b74dc236.png 
- Further details can be found in the latter comments of this issue: #26050 

## Acceptance Criteria
- [ ] Create alert at top of Search page locally
- [ ] Share screen shot with team prior to deploying to Staging
- [ ] After review, deploy to Staging 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I will add details to this first thing in the AM

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel this issue is fleshed out now.  Updating the multi-alert ticket now.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO So is it cool if I do all the work on the multi-alert ticket?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel it might be good to keep them separate just so you can post the links and keep any commentary/request changes isolated to a specific version.

**Comment by zacharymorel** [comment]
Oh I see, I miss understood the ticket! Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @zacharymorel !

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO @rtwell -- do we have any standard for whether an on-site link opens in the same window or a new one? Thank you! Cc @cindymerrill @zacharymorel @johnhashva

**Comment by rtwell** [comment]
I believe links that direct users to other pages on VA.gov open in the same window.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @rtwell !
