### ISSUE TITLE
Find a VA Form - PDF Instructions - Implement multiple alert option on Staging for user research 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27426]
## Issue Description
Implement PDF instructions alert option that is displayed with every PDF link on the Find a VA Form search results.

---
## Tasks
- [ ] Build out an alert near each PDF link in the Find a Form Search results using the below content and mock-up:

  - We recommend that you download PDF forms and open them in Adobe Acrobat Reader 
  - Get instructions for opening PDF forms in Acrobat Reader](https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form/)  
  - It will be based on this mockup:
https://user-images.githubusercontent.com/73354907/125468686-6328dd80-937a-4229-a637-bed8d4861a2c.png
- This is an experimental design.  You may want to work with @mpelzsherman on how he implemented on the Facility Locator tool.
- Further details can be found in the [latter comments of this issue: #26050](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050#issuecomment-878599072) 
- Josh Kim provides some info on how to make this mult-alert approach unobtrusive [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050#issuecomment-879306824).

## Acceptance Criteria
- [ ] Create alert near each PDF link on the Search page
- [ ] Share screen shot with team prior to deploying to Staging
- [ ] After review, deploy to Staging for Cindy to review & pilot test
- [ ] Hide behind a feature flag until Cindy is ready to test with users

---

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel this too I shall flesh out in the AM

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I believe this one is ready to go also.

**Comment by zacharymorel** [comment]
Thank you, has the sprint been updated to reflect it? 
I gave it a 5 since I have to add a new Feature Flag.

**Comment by MarciMcGuireGCIO** [comment]
The sprint 52 report wasn't ready on Wed because of all the Outlook migration madness, but I'll pull a couple things out of this sprint on here.

**Comment by zacharymorel** [comment]
@cindymerrill @MarciMcGuireGCIO 

![Screen Shot 2021-07-20 at 10 09 46 AM](https://user-images.githubusercontent.com/26075258/126339172-846853a7-c929-405f-be62-76af89da4d4f.png)

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel ! Looks great!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel @callen2563 - updating this per our meeting regarding a third option.  @callen2563 if you can please post a link to the 3rd mockup here and to the hint text in the Design System, that would be great.  Thanks!
