### ISSUE TITLE
Sandbox - Use Entity Reference for tying translated pages 

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#27429]
## Issue Description

We need a rudimentary way to relate existing page nodes to each other in regards to their language and translation.

---
## Tasks
- [ ] On CMS add entity reference module and document/test for usability [entity reference module](https://www.drupal.org/project/entityreference)
- [ ] How does each module work, and what are their benefits?
- [ ] How is this module different than the base relations module and what are the tradeoffs?
- [ ] What additional work would need to be done to use these for translation management (liquid templates, react widget, additional CMS ui / fields)## Acceptance Criteria:

## Acceptance Criteria

Demonstrate the ability to link the 3 Covid pages (English, Spanish and Tagalog) by using the relation module

- [ ] Query and return the correct page by using just the entity reference module
- [ ]  Query the current page's language

**Comment by adamwhitlock1** [comment]
The Entity Reference is a somewhat viable option, and a sandbox was created to demonstrate querying the translated pages and languages.

See ticket [#27428](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27428) for further details into how the two fields could work together to provide translation data.

Work is now done and ticket is ready to be closed.
