### ISSUE TITLE
Pre-need: Form updates

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27425]
## Description

The pre-need form has several issues that need to be addressed including content updates & cleanup and a11y fixes

## Tasks
- [x] Update OMB expiration date
- [x] Update `manifest.json` app name - it's showing an incorrect form number
- [x] Determine what modal content should be shown in production (see https://dsva.slack.com/archives/C5AGLBNRK/p1626367361329700) - moved to ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/27577
- [x] Fix header order - a11y issue
- [x] Clean up "respondent burden" block at the bottom of the [intro page](https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction) - see https://github.com/department-of-veterans-affairs/va.gov-team/issues/27430

## Definition of done

-  [ ] All tasks addressed/complete
-  [ ] All tests passing

**Comment by Mottie** [comment]
Opened a ticket related to the respondent burden content - https://github.com/department-of-veterans-affairs/va.gov-team/issues/27430

**Comment by Mottie** [comment]
Closing. Portions that require more works or feedback have been split out.
