### ISSUE TITLE
Debts are being fetched twice on the Manage VA Debts page

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#27437]
## Issue Description
When navigating to `/manage-va-debt/your-debt/` it was noticed the debts endpoint is being called twice.

---
## Tasks
- [ ]  remove additional debts endpoint call

## Acceptance Criteria
- [ ] calls to the debts endpoint should only fire once on page load
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
