### ISSUE TITLE
[Bugfix] - eben forms - add Puerto Rico to list of states

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#27444]
## Description
There exists in `vets-json-schema` at least two different lists for USA states: `states50AndDC` and `usaStates`. Our forms currently use `states50AndDC` but should use `usaStates` instead because it includes Puerto Rico, the Virgin Islands, and several other places. 

## Considerations
- Import [this list](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/f12ddceab9bdde983dd33b1ab13a31313aec6d65/src/common/address.js#L387) into the 686c-674, 28-1900, and 28-8832 schemas

## Tasks
- [x] update the above schemas in vets-json-schema and pr 
- [x] in vets-website make sure proper imports are used [here](https://github.com/department-of-veterans-affairs/vets-website/blob/48f52dcacc9e4ba2708e219a43e414c78beab17c/src/applications/disability-benefits/686c-674/config/address-schema.js#L30) and [here](https://github.com/department-of-veterans-affairs/vets-website/blob/c899c574bbf6d1a699168ec24326995d900e07f8/src/applications/vre/definitions/profileAddress.js#L10).
- [x] verify Puerto Rico (and Virgin Islands) is present in the dropdowns for all three forms.
- [x] pr vets-website
- [x] pr vets-api

## Acceptance Criteria
- [ ] all tasks are complete
