### ISSUE TITLE
Online scheduling API

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27454]
## Issue Description
As a Veteran searching for locations offering COVID-19 vaccinations, I want to know which locations allow online scheduling through VAOS.

During Q2 21, the Facilities team planned to provide this information by connecting directly to and by providing access to this data via a backend connection to Lighthouse (#22736). However, the service details were slow to roll out and dependent on an update to the interface with Drupal.

To create a short term solution, we created a direct connection to VAOS (#21734) which was parked before implementation in a pivot to present walk-in availability. This connection communicates the availability of online scheduling for COVID-19 vaccine services if `patientHistoryRequired` is present (with either yes or no value).

[Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/online-scheduling)
[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1626283025545/dcd1bf9e576ebb16cb169127c9ba7aab0b77355b?sender=michellemiddaugh9063)

![image](https://user-images.githubusercontent.com/55411834/125867723-8c942bb2-1b0a-4247-8dfa-b037be3d9e54.png)

[VAOS FAQs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/636873fa2cba702b9a514b88766d450bc8bde1ee/products/health-care/appointments/va-online-scheduling/product/decisions-faq.md)

## Related issues
#21734
#22746

## MVP scope
VAOS services (VA only)
- Amputation care (VA appointments)
- Audiology and speech (VA appointments and Community Care appointments for hearing aid support and audiology only)
- Eye care- Optometry and Ophthalmology (VA appointments and Community Care appointments for Optometry only)
- Mental health (VA appointments)
- MOVE! weight management program (VA appointments)
- Nutrition and food (VA and Community Care appointments)
- Pharmacy (VA Appointments)
- ~Podiatry (Community Care Appointments)~
- Primary care (VA and Community Care Appointments)
- Sleep medicine
- Social work

## Out of scope
Assimilation into lighthouse

---
## Tasks
- [ ] Find the source of data
- [ ] Find out where everything got complicated
- [ ] Determine a place to store translation data
- [ ] Make standalone so it can go into Drupal
- [ ] Drupal api

## Acceptance Criteria
- [ ] We can answer this question: _"is service X available for online scheduling at facility y?"_

**Comment by mmiddaugh** [comment]
Per VAOS team, everything except COVID related appts have moved to the request mode (enter your info, indicate preferred dates and a human will schedule the appt). 

Some facilities have very long request queues so we shouldn't advertsie that option as it could be quite frustrating for Veterans. 

Mental health and primary care are moving to online scheduling mid August.

**Comment by jilladams** [comment]
@mmiddaugh it seems like the heart of "find a way to move this into Drupal" is still valid. Agree?
