### ISSUE TITLE
Add phone labels for Facility Locator search results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27451]
## User story
As a screen reader user, I need phone numbers to be labelled so I understand their context relative to other numerical information. 

## Issue description
During screen reader usability sessions, one participant interpreted a phone number as GPS coordinates because it was read directly following "Get directions''.

**Reference:** [Facility Locator short-term recommendations #7](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/screenreader-usability-study/research-findings.md#on-facility-locator---short-term)

---

## Tasks
- [ ] ~Work with accessibility specialists to assess and address the current problems with ‘phone’ links~ (done - tasks added based on comments)

Choose approach adding context to phone numbers within the list of search results. Options from accessibility team:   
- CHOSEN BY TEAM: use `aria-describedby` to tie the phone number to its descriptive label. For example, instead of tabbing to a number and hearing "5 7 1 2 3 1..." they would hear "5 7 1 2 3 1... Main number for (location name)."
```
<div>
  <strong id="unique-id-1">Main number: </strong> 
  <a aria-describedby="unique-id-1" class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
</div>
<div>
  <strong id="unique-id-2">Mental health number: </strong>
  <a aria-describedby="unique-id-2" class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
</div>
```
- _**or**_ use a description list so folks know that this is one of a set and that more contextual information can be found nearby. If they tab to an item within a description list, they should hear "5 7 1 2 3 1... 2 of 4" which may prompt them to move backwards to hear the title.
```
<dl> <!-- sets up description list -->
  <dt id="unique-id">Main number: </dt> <!-- title -->
  <dd> <!-- description -->
      <a class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
  </dd>
  <dt id="unique-id">Mental health number: </dt>
  <dd>
      <a class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
  </dd>
</dl>
```

---

## Acceptance Criteria
**This is for the Facility Locator only**
- [ ] Veterans using assistive technology are able to interpret when numerical information represents phone numbers. 
- [ ] Veterans using assistive technology get the purpose and target within the link
- [ ] Validation by Josh and/or Angela

**Comment by mmiddaugh** [comment]
@joshkimux can you provide information on the markup for handling phone numbers, please?

**Comment by joshkimux** [comment]
@mmiddaugh this problem I think was due to folks tabbing through the list without reading through items line by line. That means folks may miss relevant descriptions "main number" or "mental health". 

A possible way to solve this would be to use `aria-describedby` to tie the phone number to its descriptive label. For example, instead of tabbing to a number and hearing "5 7 1 2 3 1..." they would hear "5 7 1 2 3 1... Main number."

E.g.:
```html
<div>
  <strong id="unique-id-1">Main number: </strong> 
  <a aria-describedby="unique-id-1" class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
</div>
<div>
  <strong id="unique-id-2">Mental health number: </strong>
  <a aria-describedby="unique-id-2" class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
</div>
```

Alternatively, this could be written as a description list so folks know that this is one of a set and that more contextual information can be found nearby. If they tab to an item within a description list, they should hear "5 7 1 2 3 1... 2 of 4" which may prompt them to move backwards to hear the title.

E.g.:
```html
<dl> <!-- sets up description list -->
  <dt id="unique-id">Main number: </dt> <!-- title -->
  <dd> <!-- description -->
      <a class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
  </dd>
  <dt id="unique-id">Mental health number: </dt>
  <dd>
      <a class="no-wrap vads-u-margin-left--0p25" href="tel:+15712312408" aria-label="5 7 1. 2 3 1. 2 4 0 8.">571-231-2408</a>
  </dd>
</dl>
```

@AngelaFowler82 would love your thoughts on which of these approaches you'd prefer.

**Comment by lildziner** [comment]
I had a couple questions: 

- Should/would phone numbers show up within a links list? 
- and, if so, would users expect to hear "Main number for Lynn VA Clinic 5 7 1..."  to differentiate numbers from different locations like we do for 'Get directions' links, where we add the name to the screen reader test, e.g. 'Get directions to Lynn VA Clinic'.

**Comment by joshkimux** [comment]
@lildziner , yes they should and would show up within a links list (see demo)

https://user-images.githubusercontent.com/14154792/127203455-0b7328b2-ffda-4089-a333-3a115b96171c.mov

And yes, that's a great point! Good catch Leyda. It could be appended to the end of the `aria-label` like "5 7 1... Main number for Lynn VA Clinic" so folks get the purpose and target within the link 😄

**Comment by mpelzsherman** [comment]
This ticket will require changing our [Telephone](https://github.com/department-of-veterans-affairs/component-library/tree/master/src/components/Telephone) component.

**Comment by mpelzsherman** [comment]
I don't have permission to publish a new release of the component-library. Need assistance from the design system team (@bkjohnson @cvalarida).

**Comment by mmiddaugh** [comment]
@joshkimux @AngelaFowler82 we'd love your validation of this when you are able

**Comment by AngelaFowler82** [comment]
As I arrow down, there is a label indicating the purpose of the phone number which renders above the number itself, so a user arrowing down from Get Directions" will encounter "main number" followed by the phone number. As I tab through the page however, I do not hear the labels.

**Comment by mpelzsherman** [comment]
I don't hear any difference between tabbing vs. using the arrow keys. Is this a JAWS vs. VoiceOver issue?

https://user-images.githubusercontent.com/80267/132402820-d2dcb3ec-d276-4940-a2b9-8578dfcf8a49.mov

**Comment by joshkimux** [comment]
Tabbing _should_ announce the labels using `aria-describedby`; I've tested and confirmed this on VO/Safari and NVDA/Chrome.
I did a little bit of searching, and it looks like older versions of JAWs won't read out `aria-describedby` on links. This _shouldn't_ be the case for more recent versions of JAWs, so I'll do a little bit more research!

**Comment by joshkimux** [comment]
@mpelzsherman I just tested on JAWS / Chrome using JAWS 2021 and it worked! I talked to Angela about it, and we're planning on logging a bug as we're not sure why it's not working on Angela's device. Closing this out! 🙏

**Comment by mpelzsherman** [comment]
Awesome! Thanks, Josh!
