### ISSUE TITLE
Find a VA Form - VA.gov content pages/apps links should point to form detail pages vs. PDF

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27458]
## Issue Description
Pages across VA.gov that currently link directly to VA form PDFs need to be updated so that they point to the form's detail page (where one exists) so that the link will continue to work if a VA Form Manager changes the PDF file name.

---
## Tasks
- [ ] Identify pages on VA.gov that contain links directly to VA form PDF files
- [ ] Document links by Hub
- [ ] Determine if those PDF files have detail pages on Find a VA Form
- [ ] If a detail page exists, update the PDF link to point to the form's detail page

## Acceptance Criteria
- [ ] Each page that currently links directly to a VA PDF form instead points to the appropriate detail page for that form
- [ ] Artifact is created (Word/Excel) listing all links found by Hub and action taken
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@bethpotts @RLHecht - please review and let me and/or John know your thoughts and what additional info you need from us.  Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht @SgardnerPMP @lunascoop 

@DanielleThierryUSDSVA @mnorthuis and I chatted about this and we'd like to go with this:

From:
Download VA Form 21-526EZ (PDF)

To:
Get VA Form 21-526EZ to download

@lunascoop Thanks for calling out the R&S Intent to file article on our call this week--that's kind of a 1-off, and the main action link CTA could be:
**Get an intent to file form to download**
(It wouldn't make sense to use the form number here since we don't call out the form number before the user would see and click on the action link.)

But for the text link down farther on the page, go with our new style:
Get VA Form 21-0966 to download

**Comment by lunascoop** [comment]
@RLHecht these are the hub pages that have been updated with links to the find form pages (for the most part). I did come across some pages that required other edits (headers, bulleted lists, sighted language, broken links, etc.). I've noted them below.

**Disability**

- http://preview-prod.vfs.va.gov/preview?nodeId=883
- http://preview-prod.vfs.va.gov/preview?nodeId=891
- http://preview-prod.vfs.va.gov/preview?nodeId=893
- http://preview-prod.vfs.va.gov/preview?nodeId=894
- http://preview-prod.vfs.va.gov/preview?nodeId=895
- http://preview-prod.vfs.va.gov/preview?nodeId=900
- http://preview-prod.vfs.va.gov/preview?nodeId=905
- http://preview-prod.vfs.va.gov/preview?nodeId=910 (bulleted formatting, last accordion)
- http://preview-prod.vfs.va.gov/preview?nodeId=907 (forms links and bulleted formatting in multiple accordions)
- http://preview-prod.vfs.va.gov/preview?nodeId=906
- http://preview-prod.vfs.va.gov/preview?nodeId=855
- http://preview-prod.vfs.va.gov/preview?nodeId=710
- http://preview-prod.vfs.va.gov/preview?nodeId=904

**Health Care**

- http://preview-prod.vfs.va.gov/preview?nodeId=29 (sighted language, sub-bullets (8th accordion, modeled language after DEA page), bulleted lists and other bulleted lists)
- http://preview-prod.vfs.va.gov/preview?nodeId=4 (sighted language and links
- http://preview-prod.vfs.va.gov/preview?nodeId=708 (bulleted list)
- http://preview-prod.vfs.va.gov/preview?nodeId=35 (including Spanish expanded callout)
- http://preview-prod.vfs.va.gov/preview?nodeId=30 (hearing language and form link)
- http://preview-prod.vfs.va.gov/preview?nodeId=9 (form links and sub-bullets
- http://preview-prod.vfs.va.gov/preview?nodeId=36
- http://preview-prod.vfs.va.gov/preview?nodeId=5681
- Get your VA medical records online (needs updating but it's a react widget)
- http://preview-prod.vfs.va.gov/preview?nodeId=39
- http://preview-prod.vfs.va.gov/preview?nodeId=706
- http://preview-prod.vfs.va.gov/preview?nodeId=2431
- http://preview-prod.vfs.va.gov/preview?nodeId=703
- http://preview-prod.vfs.va.gov/preview?nodeId=42031
- http://preview-prod.vfs.va.gov/preview?nodeId=11755

**Comment by RLHecht** [comment]
I've published all the pages listed above except where I put a note that there are other changes in draft that can't go live yet. I think it's OK to close this ticket and know that these changes will go once the other chances to those pages are approved. Moving to validate.
