### ISSUE TITLE
Post Research Tasks: Find a VA Form PDF Download Info

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27478]
## Description 
Wrap up research study and associated documents/resources

## Tasks
- [x] Share research report with team, stakeholders, research, Shawna for feedback
- [x] Add participant characteristics into MVS checker (for marginalized groups)
- [x] Make short presentation from research report for Sprint Demo 
- [x] Make longer presentation for Design/Research/Content Mon mtg
- [x] Present findings to team and stakeholders, discuss recommendations--Sept 1
- [x] Revise report per report out discussions
- [x] Close out ticket once once completed
- [x] Post report on Github
- [x] Add link to Research History page
- [x] Delete recordings -- WAIT until after recommendations discussions w/teams
- [x] Remove PII from notes and post on Github, along with any other synthesis documents

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO  What are your thoughts about the timing of research report out meeting(s)? I should be able to share the report in github with you late tomorrow (Wed), and I'll start working on a longer presentation (building on today's short sprint demo presentation) as we discussed previously. I'm on PTO all next week, so I'd like to finish the presentation by this Friday if possible. I could present on Thursday (you're out on Friday, right?) likely without the full presentation, or wait until I get back from PTO on Aug 23. Am I presenting to the Decision Tools team and/or other people, too? Let me know how I can be most helpful with my research results... :)

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill I think it will be best to wait until you are back from PTO before we present this.  We are still in a holding pattern with regard to a new Product Owner, and given the nature of the findings, I think it's important for someone to be in that role and have an opinion on next steps.

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO This makes sense. I'll work on the presentation this week and share it with you for feedback when it's complete. So this ticket should stay open...

**Comment by MarciMcGuireGCIO** [comment]
Ok; sounds good.

**Comment by cindymerrill** [comment]
Research report shared on github with #decision-tools: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/research-findings.md

**Comment by cindymerrill** [comment]
Report added to [VFR Research History page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md)

**Comment by cindymerrill** [comment]
Finished drafting longer readout presentation and shared with @MarciMcGuireGCIO for feedback: https://docs.google.com/presentation/d/1jidZucBRvAu8XEeo-6D9lzgVlbOLirgwmRGpbegbF_M/edit?usp=sharing

**Comment by cindymerrill** [comment]
Notes posted on github.

**Comment by cindymerrill** [comment]
Scheduled meeting with @MarciMcGuireGCIO for Wed Aug 25 to discuss research recommendations and readout(s).

**Comment by MarciMcGuireGCIO** [comment]
I believe we are ready. I will delete the recordings on my end also. Thank you.

**Comment by cindymerrill** [comment]
OK, I've deleted recordings from my laptop and Keybase. Once you've deleted the recordings on your computer, we'll be done :)

**Comment by MarciMcGuireGCIO** [comment]
I'm all done!

**Comment by cindymerrill** [comment]
OK, thanks, @MarciMcGuireGCIO ! Closing ticket now.

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill I am doing the sprint report for sprint 55 and just realized that this task did not have an estimate on it.  How many points was this?  Thanks!

**Comment by cindymerrill** [comment]
Estimate added: 6 @MarciMcGuireGCIO
