### ISSUE TITLE
Research synthesis and reporting: Find a VA Form PDF Download Info

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27479]
## Description 
The purpose of this research is to determine two things:

1. Which of two PDF instruction options is most user-friendly and intuitive
2. Understand challenges PDF forms with e-signature may be introducing for our Veterans.

## Tasks 
- [x] Clean up notes spreadsheet 
- [x] Write topline summary and share out with team
- [x] Do data analysis/synthesis of data collected from research  
- [x] Write research report

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill let me know when you would anticipate having your research synthesis and reporting completed and I'll move those two items to the appropriate sprint.  Thanks!

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO This work is currently planned for the week of August 2

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cindymerrill !

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO Here’s my topline summary of last week’s user research on Find a Form PDF Downloading: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/topline-summary.md
Might be helpful when talking with Adobe. 

Let me know if you have any feedback on these preliminary findings. Next I’m going to do detailed data synthesis work to document more detailed  issues in a research report.

**Comment by MarciMcGuireGCIO** [comment]
Noting here that I am adding two points to this ticket for myself to cover the time spent reviewing recordings and compiling a table with the technical aspects of the study.

**Comment by cindymerrill** [comment]
Looks like it's only 2 points now for the ticket, so where did the greater number of points for me go? Replaced by your 2 points? @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill there wasn't an estimate on it before.  I just searched the history and it appears it was never estimated.

**Comment by cindymerrill** [comment]
I would have put 5 for an estimate. Sorry I didn't see that it wasn't estimated. Should we add our numbers together? @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment]
No worries!  I'll change to 7 to capture both our times.

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO Report writing is going slower than I thought, so I'm probably not going to finish this week. I anticipate taking at least part of next week to do it, and maybe the whole week if I also put together a presentation as you requested. Not sure how far I'll get by Sprint Demo time; maybe I could pause on analysis and put together a few slides about the research including the main findings I have so far. Looks like you're on PTO next Friday (Aug 13), and I'm out the following week (Aug 16-20), so I'm hoping to finish all data analysis and reporting before I leave.

**Comment by MarciMcGuireGCIO** [comment]
Ok, that sounds like a plan. Thank you for the update!

**Comment by cindymerrill** [comment]
Drafted report but needs revising before sharing link here. Drafted presentation for Sprint Demo and shared with @MarciMcGuireGCIO for feedback.

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill I reviewed the presentation and it looks great! I added one comment on slide 7.

**Comment by cindymerrill** [comment]
Finished report. After a researcher reviews it and I make revisions, I will share link with team. Closing this ticket and will shift to follow-on ticket: Post Research Tasks: Find a VA Form PDF Download Info #27478.
