### ISSUE TITLE
Data Fetch Canary

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#27477]
## Description
Seeking to confirm the successful fetch of data from a logged in user to VA platform by querying profile information.

Will begin as test user to staging.va.gov and extend to va.gov production environment as credentials/permissions are generated.

## Tasks
- [x] Log into VA gov as a user
- [ ] Click on 'Profile' section
- [ ] Confirm successful fetch/retrieval of profile information

## Definition of Done
Test on AWS Canary and monitor the process on CloudWatch confirming successful passage of script.

**Comment by rjohnson2011** [comment]
Currently building out a log in flow for a staging test user.

**Comment by rjohnson2011** [comment]
Built out code to successfully perform task locally on Puppeteer. In the process on converting to Canaries and testing on AWS.

**Comment by rjohnson2011** [comment]
All set to go, just waiting for permissions for secret environmental credentials to host on AWS.

**Comment by rjohnson2011** [comment]
Received feedback from Ops to attempt to populate the secret environment variables via the AWS CLI tool. I am configuring that and attempting to get that to work.

**Comment by rjohnson2011** [comment]
Back and forth with Ops to troubleshoot permissions errors on performing AWS CLI commands. Was given the `issue_mfa` shell script to authorize MFA permissions to overcome AWS CLI errors. Installing the many dependencies required and working on getting that set up.

**Comment by rjohnson2011** [comment]
dataFetch Canary is successfully running on AWS. In the process of building out a PR to put in tomorrow and wrap up ticket.

**Comment by rjohnson2011** [comment]
PR approved & merged into DevOps - https://github.com/department-of-veterans-affairs/devops/pull/9686
Canary is running and passing on AWS CloudWatch.
