### ISSUE TITLE
Fix typo in Prosthetic Socks best bet

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27484]
## Issue Description
When searching "prosthetic socks" on VA.gov, the best bet that comes up has a typo in the meta description. The word "stocks" should be "socks." It's correct in the meta description within Drupal though the meta title does not match, so it must be pulling from somewhere else. 

![Screen Shot 2021-07-16 at 2.38.04 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c06d55b0-68b1-4906-b54a-1bc3b3488051)

![Screen Shot 2021-07-16 at 2.38.20 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/eb861d6c-cadb-4e21-961d-a3ce0c9934de)

---
## Tasks
- [ ] Change "stocks" to "socks" in meta description
- [ ] Change H1 to match page?

## Acceptance Criteria
- [x] Correct word is on live page.

**Comment by johnhashva** [comment]
@RLHecht This is fixed and live.  Please close this ticket after you validate. TY.
<img width="687" alt="socks bb" src="https://user-images.githubusercontent.com/63107147/126008533-4c9b54b2-233d-4db9-8651-25654a4e17c5.png">

**Comment by RLHecht** [comment]
Looks good. Thanks @johnhashva !
