### ISSUE TITLE
ATO - Whitelist the penetration testing IP addresses provided by External Assessment Services

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#27482]
## Description
_We have requested a penetration test from the EAS, and they are asking us to whitelist some IP addresses to all of our staging assets._

## Technical notes
_@dginther can provide the IP addresses via Keybase._

---
## Tasks
- [x] _Create an AWS Security group in the staging VPC_
- [x] _Add that SG to all assets in the staging VPC_
- [x] _Add the whitelisted IP addresses, all ports, all protocols, inbound access_

## Definition of Done
- [ ] _EAS team is able to perform their penetration test._

**Comment by dginther** [comment]
I have added the IPs to the whitelist, waiting for ~1 week to let the change be deployed across the infrastructure.

**Comment by jhouse-solvd** [comment]
@troymosher - This was a previous request from last year. 

1. Do we know if this was completed? 
2. Is it the same team requesting access this year in #[36268](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36268)?
3. Can this issue be closed?

**Comment by troymosher** [comment]
@jhouse-solvd Yep, same team requesting access this year in #36268.  This issue can be close.
