### ISSUE TITLE
Image of Vet Center needs context

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27497]
## Issue Description
During validation of #25011, it was determined that  that the image of the vet center is in other locations, which gives the illusion that it's related to other locations instead of the main location itself.

This was observed during validation using https://www.va.gov/nashville-vet-center/ and https://www.va.gov/colorado-springs-vet-center/ in the Production environment. 

### Clarifying questions for Josh and Angela
- Was this observed on the main page or the Locations page? Was it observed on both Nashville and Colorado Springs?
 > The issue appears on the main pages of both Nashville and Colorado Springs. On the locations pages, the images are render under their locations' phone numbers, making it clear which image belongs to which location. ~Please note that under Nashville Locations, the Clarksville Outstation appears to be listed twice.~_(this issue was resolved by an enhancement in Drupal which made the automatically affiliated locations more visible to editors)_
- What about the structure of the page causes the context to be lost?
> On the main pages, a screen reader user will come upon the address, phone number and "get directions" link to the main location, followed by its hours. A level 3 heading then announces other locations, and we are presented with text which states we have other location, the link to the locations page, then a statement about nontraditional hours which I assume applies to the other locations. Immediately below the statement about nontraditional hours we are presented with the image of the main location.

---
## Dev notes
- this is related to the column structure of this area
- rather than a two column div, we can organize the divs as top/bottom - cutting the top off before the "Other locations" heading

![image](https://user-images.githubusercontent.com/55411834/128776104-8cd81261-995d-4e26-ad44-2efc1e4ffdb6.png)

## Tasks
- [ ] Ensure the image for the main location is presented in context with the main location's address and contact information 
- [ ] Separate everything related to the "Main Location" from "Other Locations" 

## Acceptance Criteria
- [ ] Veterans have context for Vet Center images and are able to understand if the image represents the main location or other location. 
- [ ] Angela and/or Josh should validate this fix

**Comment by AngelaFowler82** [comment]
The issue appears on the main pages of both Nashville and Colorado Springs. On the locations pages, the images are render under their locations' phone numbers, making it clear which image belongs to which location. Please note that under Nashville Locations, the Clarksville Outstation appears to be listed twice. 
On the main pages, a screen reader user will come upon the address, phone number and "get directions" link to the main location, followed by its hours. A level 3 heading then announces other locations, and we are presented with text which states we have other location, the link to the locations page, then a statement about nontraditional hours which I assume applies to the other locations. Immediately below the statement about nontraditional hours we are presented with the image of the main location.

**Comment by mmiddaugh** [comment]
Thank you for the additional information @AngelaFowler82 - we'll get this groomed and resolved in the next sprint

Just so you know, the duplicate listing for Clarksville Outstation was a content error. the CMS team recently changed the editorial experience to decrease the risk for this occurring in the future.

**Comment by joshkimux** [comment]
Gave this a check and it looks like the image has been bumped up in the DOM to be above the `h3` other locations. Fantastic a11y work @gescobardev 🥳 

<img width="1792" alt="Screen Shot 2021-08-24 at 9 45 48 AM" src="https://user-images.githubusercontent.com/14154792/130628185-47438424-3237-41b7-b29e-25182d3a9195.png">

https://user-images.githubusercontent.com/14154792/130628192-5ad2a5e0-936d-4a45-a484-91e97335221f.mov
