### ISSUE TITLE
**DISCOVERY** | CMS Sandbox | API Integration 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#27496]
## Description

Weblate is a libre web-based TMS and one of several vendors we are considering for inclusion in our Translation Recommendation report.

We'd like to integrate Weblate's Public API with our CMS sandbox to garner some experience and learnings.
Before doing so, we need to understand details around the technical implementation and set-up as well as what we will be able to test.

## Tasks

- [x] Review tech specs to understand requirements to integrate with Weblate's API
- [x] Identify impacts and/or impediments to setting up a POC
- [x] Based on review of tech docs/specs, make recommendation(s) on what should be included in a proof of concept.

## Acceptance Criteria

- [x] List test scenarios that we can incorporate into our POC
- [x] Demonstrate integration with Weblate's API

**Comment by adamwhitlock1** [comment]
My initial discover notes are here:

[https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/weblate.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/weblate.md)

We should be able to build further tickets from the POC section to explore integrations further.
