### ISSUE TITLE
GHA Self-hosted runners - SSM access for FE Tools devs 

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#27495]
## Description
Engineers from FE Tools need to be able to SSM into the runner instances to be able to troubleshoot and resolve issues that come up in GitHub Actions.

We can start by allowing only the engineers who have been or will be working directly with implementing GitHub Actions in the FE Tools-owned repos.

## Background/context/resources
- Running as root in containers created folders that couldn't be removed by the runner's default user and needed manual intervention ([Thread](https://dsva.slack.com/archives/C01V94K0QNS/p1625863672251800?thread_ts=1625664572.231600&cid=C01V94K0QNS))

---
## Tasks
- [ ] Add permissions to the 'vsp-frontend-tools', to allow SSM Start Session permissions to
  - [ ] github actions self-hosted on-demand runners
  - [ ] github actions self-hosted runners (ASG ones)

## Definition of Done
- [ ] SSM privileges are granted to the listed people via the 'vsp-frontend-tools' group in AWS IAM

**Comment by jbritt1** [comment]
Going to add the `needs-grooming` label to ensure this gets groomed and prioritized in our next grooming session.

**Comment by jhouse-solvd** [comment]
@dginther - Can you take a look at this and let us know a) if it's possible/recommended, and b) level of effort? thank you!

**Comment by dginther** [comment]
> @dginther - Can you take a look at this and let us know a) if it's possible/recommended, and b) level of effort? thank you!

Sure! Let's do this, it should be a low LOE, the group is already created, and this would just be a policy change to the policy that is attached.
