### ISSUE TITLE
Vet Center and VAMC phone numbers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27501]
## Issue Description
Phone numbers with parentheses around the area code are not being handled correctly within Vet Center service accordions. 

<details>
    The following all appear on the preview for Cincinnati Vet Center: preview-prod-vfs.gov/preview?nodeId=3641
   
 ![image](https://user-images.githubusercontent.com/55411834/126013442-cbbcedd5-8f6e-4d3c-b65a-09bd9f8655b5.png)
  
 ![image](https://user-images.githubusercontent.com/55411834/126013536-8627e18e-7246-4270-bb9c-4029020bbe6a.png)

</details>

---
## Tasks
- [ ] Update the  phoneLinks filter function to ensure phone numbers with parentheses around the area code are wrapped.
- [ ] Update src/site/facilities/health_service.drupal.liquid to use the phoneLinks function
- [ ] Update unit tests
- [ ] Notify public websites team

## Acceptance Criteria
- [ ] Phone numbers with parentheses around the area code are converted to clickable links

**Comment by mpelzsherman** [comment]
To validate VAMC's, see https://www.va.gov/eastern-oklahoma-health-care/health-services/, Specialty Care -> Whole Health.

**Comment by mpelzsherman** [comment]
Confirmed on staging: https://staging.va.gov/eastern-oklahoma-health-care/health-services/

I don't see it on prod yet though. Will check again Monday.

**Comment by mpelzsherman** [comment]
`content-build` was re-deployed at 3:15 ET. Wrapping is working in prod now. Closing.

**Comment by mmiddaugh** [comment]
Looks great! Thank you
