### ISSUE TITLE
Migrate Collaboration Cycle Scheduling docs to Confluence

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#27517]
## Issue Description
The I[nternal Process for Collaboration Cycle](https://docs.google.com/document/d/1WrH70oKtAusYQG6pDt3CWwKaDkeOCuEsQ4nqv0n-uiQ/edit#heading=h.sdr5w8mmkd9j) is a Google doc that lives in the VSP Google Drive folder. The contents of this document need to be moved to Confluence so that Platform team members are able to pick up and complete this process if needed.

Location on Confluence: https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748828191/CC+-+How+to+Schedule+and+Respond+to+Collab+Cycle+requests

[Merge new Staging Review guidance as well. ](https://docs.google.com/document/d/1EYyrDVrexR55eoDZGkHQ3RB1iPudeH8mffJOsRU2L60/edit#heading=h.sdr5w8mmkd9j)

---
## Tasks
- [x] Midpoint Review (Peggy)
- [x] Staging Review (Allison)

## Acceptance Criteria
- [x] All instructions/directions for scheduling/managing of Collaboration Cycle touchpoints are available in Confluence.
- [x] Google doc is archived (or deleted).
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
@shiragoodman @allison0034 
The [Midpoint Review scheduling doc] (https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/CC-+Midpoint+Review)is now on confluence:
