### ISSUE TITLE
Alerting - PagerDuty setup for new Canary that monitors DSLogon

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#27520]
## Description
Regarding:
- this ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/24353
- and this canary - https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#synthetics:canary/detail/dslogon_status
- and this conversation with Dror - https://dsva.slack.com/archives/C01CHAY3ULR/p1626367340315400

An incident in PagerDuty needs to be created when this Canary fails and the #oncall DS@VA channel needs to be notified.

---
## Tasks
- [ ] Alarm created for Canary (if applicable)
- [ ] PagerDuty incident created when Canary fails

## Definition of Done
- [ ] Alarm has been configured for Canary (if applicable)
- [ ] When Canary fails an incident is created in PagerDuty and the #oncall DS@VA channel is notified

**Comment by pjhill** [comment]
Thanks for the details on how to attempt this ourselves. We will have a go at wiring this up given the information you provided -- thanks!

**Comment by rjohnson2011** [comment]
Created. The alarm will trigger when failing 2/3 times within any 15 minute period.
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/e14c6f14-88f4-4da0-84d6-1674d57a6bd4)
