### ISSUE TITLE
[Design] Mural Form Flow - Harassment Reporting Tool (HRT) 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27551]
## Description
_ORDMI PIFs have never actually produced any design mockups for the harassment tool. They took conversations with business owners, synthesized requirements from these, then directly put them into code using the https://VA.gov CMS, strictly to save time. They will share screenshots the prototype and the business requirements assembled. We'll need to take these screenshots and requirements and produce envision mockups that are compliant to VSA/VA.gov design systems. The designs will be used for both design intent review and initial FE build of the prototype_

## Tasks
- [x] Create a mural that addresses form flow 
- [x] Mural should be shared with PIF/Stakeholder team for review 

## Acceptable Criteria
- [x] Mural will be used to direct Form mockups in support of VSP Collab Design Intent/Review

**Comment by callen2563** [comment]
Updated HRT Mural board link: https://app.mural.co/t/vsa8243/m/vsa8243/1626971557496/936e375b82d0af58a76ef2b36da3ecf4585bb118?sender=u7ad68f2a3a694c00d8a38130

**Comment by brianalloyd** [comment]
@callen2563 looks like you're pretty close to being complete on the flow.  Let me know and we'll close out this ticket in support.

**Comment by brianalloyd** [comment]
Flow looks good, used during Design Intent Review and everything worked great.  Closing this out in support.

**Comment by brianalloyd** [comment]
@callen2563 form flow looks good, used in support of Design Intent Review and am going to close out this ticket in support.
