### ISSUE TITLE
VFS IA support model

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#27566]
## Develop a model and process for IA support for Veteran-facing teams

To give all Veteran-facing (VFS) teams the IA support they need, we're creating an intake process and service model for working with them. This will improve the information architecture of VFS products and make them more findable.

### This work will include:

- Revising the existing IA request process to detach it from the VSP Collaboration Cycle and move it to the VFS side
- Identifying how sitewide content and IA resources can better connect their work
- Determining how VSA/OCTO supports the VSP Collaboration Cycle
- Figuring out how to best support teams not on the VSA contract
- Defining a new process for all VFS teams to request support/collaboration
- Determining what info should go in the IA request (with the existing IA request as a starting point)
- Removing/updating references as appropriate from the VSP Collaboration Cycle and corresponding documentation
- Defining responsibilities across IA resources (OCTO, VSA, VSP)
- Communicating the new process to all VFS teams

### Headlines

**Business stakeholder -** Sitewide crew chief (?)

**DEPO owner -** Meg Peters

**Is request tracked to an event or Congressional deadline? -**  No.

### Details
**Who is the primary user?**  Designers on VFS teams.

**What are the user goals for the project/page/product?**
- VFS teams know where to go for IA help.
- here's a simple, clear process for requesting IA help.
- VFS teams know what to expect when they submit a request for IA help.

**What is the business goal?**
- There's a simple, clear process for requesting IA help.
- The IA request process has timely and efficient touch points with requests for content help and possibly the VSP Collaboration Cycle.
- VFS teams understand that the new IA request process is no longer part of the VSP Collaboration Cycle.
- Communication to VFS team about the new process is clear, well understood, and flows through the proper communication channels.

**How does this map to our North Star?**
- Increase availability of self-service tools
- VFS teams will be able to self-submit IA requests online. We'll have them provide the background and details we need to start working with them.
- Decrease time to outcomes
- We will streamline the form and request process so that IA requests are handled efficiently and the work is done well.
- Maximize satisfaction, reliability, availability, & security
- VFS teams will be able to ask for IA help easily, and they will get timely support.

**How will we measure success?**

- VFS teams are using the process with little confusion.
- IA requests contain the information we need to start working with VFS teams.
- VFS teams are not going to the VSP Collaboration Cycle team for help.

**How well do we understand the problem?**

Fairly well. To understand it better, we need to:

- Identify how sitewide content and IA resources can better connect their work
- Determine how VSA/OCTO supports the VSP Collaboration Cycle
- Figure out how to best support teams not on the VSA contract

**What is DEPO's role in this work?**

- DEPO will oversee the VFS IA who is doing this work, advise, and provide any connections or resources necessary.

**What are the known risks?**

- The IA who's working on developing a model and process for IA support for Veteran-facing teams is also fulfilling IA requests. As of late July 2021, there were more than a dozen IA requests in progress and 8 new products that need IA support next up.

**Comment by mnorthuis** [comment]
Update on primary task list.  All tasks complete for this work at this time, closing issue. 

- [x] Revising the existing IA request process to detach it from the VSP Collaboration Cycle and move it to the VFS side - combined IA request with Sitewide content intake
- [x] Identifying how sitewide content and IA resources can better connect their work - continuing to refine processes, will be handled via new sprint ceremonies
- [x] Determining how VSA/OCTO supports the VSP Collaboration Cycle - Weekly meeting with VSP IA, VSA IA invited to all collab cycle meetings
- [x] Figuring out how to best support teams not on the VSA contract - this will continue to happen via contact through collaboration cycle and follow up request to work with SC&I
- [x] Defining a new process for all VFS teams to request support/collaboration - done via collab cycle and new combined intake form 
- [x] Determining what info should go in the IA request (with the existing IA request as a starting point) - new intake created
- [x] Removing/updating references as appropriate from the VSP Collaboration Cycle and corresponding documentation - done by VSP team
- [x] Defining responsibilities across IA resources (OCTO, VSA, VSP) - document created for VSP PM and IA defining VSA vs VSP IA roles
- [x] Communicating the new process to all VFS teams - primarily handled via collab cycle process
