### ISSUE TITLE
NOD: Update contact modal content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27563]
## Description

Alert messages within the contact info modal don't show enough details (**U.S. only** and **no leading-ones**; see screenshot). So we need to improve the content message and style - there shouldn't be a close button on the alert.

<img width="589" alt="Screen Shot 2021-07-16 at 2 08 29 PM" src="https://user-images.githubusercontent.com/136959/126207486-43b51aee-7ef0-4a1c-b95c-5f7d3e003d86.png">

## Tasks

- [ ] Improve error message content shown to the Veteran
- [ ] Remove alert close button
- [ ] Check a11y

## Definition of done

- [ ] Tasks complete
- [ ] Update and/or add unit tests
