### ISSUE TITLE
[FSR] Add a temporary maintenance alert on the wizard 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27576]
## Issue Description
_The DMC is working through backend issues concerning the signature field, so we need to alert Veterans that the FSR will be down for maintenance_

The maintenance alert's text:
> The online financial help request form (VA Form 5655) is down for maintenance
>
>We’re making some updates to the online financial help request form (VA Form 5655). We’re sorry it’s not working right now.
>To request help with VA education, disability compensation, or pension benefit debt, please fill out the PDF version of our [Financial Status Report (VA Form 5655)](https://www.va.gov/find-forms/about-form-5655/?_ga=2.210395415.346734835.1626710411-1193325830.1624890584).

[Please refer to the UXPin for the design](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/140406776/simulate/sitemap?mode=i)

---
## Tasks
- [ ] Add the maintenance alert to the top of the wizard's page in accordance with the provided UXPin
- [ ] Replace the result for `VA disability compensation, education, or pension benefit debt > Request debt relief (a waiver or compromise offer) > Veteran` with the alert
- [ ] Replace the result for `VA disability compensation, education, or pension benefit debt > Request debt relief (a waiver or compromise offer) > Active duty service member` with the alert
- [ ] Replace the result for `VA disability compensation, education, or pension benefit debt > Request debt relief (a waiver or compromise offer) > Member of the National Guard or Reserve` with the alert

## Acceptance Criteria
- [ ] _The alert has been added to the top of the wizard page_
- [ ] _The alert has replaced the 'Veteran' debt relief request result_
- [ ] _The alert has replaced the 'Active duty service member' debt relief request result_
- [ ] _The alert has replaced the 'Member of the National Guard or Reserve' debt relief request result_
- [ ] _The final UI has been reviewed by a designer on the team_

**Comment by LindaLi123** [comment]
@craigwheeler @LinnJS Hello Craig and Justin, would you please advise if this can be done quickly?  Would like this to be live ASAP.

**Comment by craigwheeler** [comment]
pulling into the current sprint looking into it now

**Comment by craigwheeler** [comment]
PR [#17942](https://github.com/department-of-veterans-affairs/vets-website/pull/17942) has been opened to show maintenance alert when `show_financial_status_report` feature flag is disabled

**Comment by craigwheeler** [comment]
PR [#17979](https://github.com/department-of-veterans-affairs/vets-website/pull/17979) opened to add DMC external services and downtime notifications to FSR
