### ISSUE TITLE
Pre-need: Update modal privacy statement modal content 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27577]
## Description

There is different content being shown in the privacy statement modal when comparing staging and production. Once the content has been reviewed & provided, the content will be set to show in both development & production.

Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/27425
- https://dsva.slack.com/archives/C5AGLBNRK/p1626367361329700

### Production:
-  Go to https://va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction
- Click the "Privacy Act Statement" link under the OMB info
    <details><summary>Production modal content</summary>

    
    ![Screen Shot 2021-07-15 at 11 35 43 AM](https://user-images.githubusercontent.com/136959/126223835-e47706f7-da72-4e5e-bc11-851741f74113.png)</details>

### Staging
- Go to https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction
- Click the "Privacy Act Statement" link under the OMB info
    <details><summary>Development modal content</summary>

    
    ![Screen Shot 2021-07-15 at 11 35 57 AM](https://user-images.githubusercontent.com/136959/126223843-767a2269-60ae-4e29-98b2-7787ea7269bf.png)</details>

## Tasks

- [ ] Update privacy statement modal content
- [ ] Remove environment check for conditional rendering

## Definition of done

- [ ] Decision on content is made
- [ ] All tasks complete

**Comment by vhenry07** [comment]
This is a sitewide issue, so while our team doesn't own it, we'll keep in the backlog for implementation when new content is ready.

**Comment by MichelleDieudonne** [comment]
Memorials Self-Service Jira Work Item Link: https://jira.devops.va.gov/browse/MBMS-38245

**Comment by MichelleDieudonne** [comment]
This item was fixed upstream by https://jira.devops.va.gov/browse/MBMS-38574
