### ISSUE TITLE
Add More Error Handling for BID Pension Service

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#27571]
## Background
A new integration with the BID Awards service was added to the 686/674 submission.  Better error handling needs to be added if for some reason the BID service returns an error.

## Tasks
- [ ] Add exception handling to the BID Awards service

## Acceptance Criteria
- [ ] An error is displayed in Sentry
- [ ] Test specs have been created/updated as needed
- [ ] A PR has been requested for merging

**Comment by steele-lm** [comment]
@tfink419 Found this old ticket related to error logging. I added it to the backend code review epic.

**Comment by steele-lm** [comment]
@micahaspyr Just for awareness, I found this old ticket, which I believe relates to the previous pension award service api integration with the 686/674.

**Comment by micahaspyr** [comment]
Yeah, I think this is a problem we're seeing in terms of the phone number length issue.  We're not parsing the responses enough to log errors effectively.

**Comment by steele-lm** [comment]
Fix implemented.
