### ISSUE TITLE
BDD: Remove PTSD questions from the flow

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27584]
## Description

When an active service member fills out a Benefits Delivery at Discharge form, they do not need to fill out PTSD questions as they will be asked these same questions in their exit physical. We need to maintain these questions for other 526 filers.

## Tasks

- [ ] Remove PTSD (Form 781 & 781a) questions from the BDD flow
- [ ] Update mock data
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
