### ISSUE TITLE
EKS rolling update - Newly spun up worker nodes failing to attach to cluster 

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#27611]
## Description
At times, when the eks rolling update is run the newly provisioned worker nodes will fail to attach to the cluster.  They are created in the ASG properly, however something is going wrong with the bootstrap script.  This causes the EKS rolling update script to hang waiting for the proper number of worker nodes and fail on any subsequent runs since the ASG thinks it is at the proper capacity.

https://github.com/department-of-veterans-affairs/devops/runs/3105888423?check_suite_focus=true

![image](https://user-images.githubusercontent.com/76792875/126361720-6931bbc6-5424-41a4-a08b-cd14fd0c8356.png)

My manual intervention to fix this has been to find the instances that didnt get properly attached from the ASG, ssm into them, and run the following commnd.

`sudo /etc/eks/bootstrap.sh dsva-vagov-<env>-cluster --use-max-pods false`

Once they have all been attached to the cluster rerunning the eks rolling update on the given environment will allow it to succeed.

I find this happens more often than not when there are a large number of nodes that need to be replaced.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Investigate why worker nodes dont attach to cluster properly

## Definition of Done
- [x] Worker nodes attach to cluster

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by mleclerc00** [comment]
Moving bootstrap (which initializes the worker node connection to the cluster) to the end of the userdata script seems to have cleared this problem up.  It seems like there was a race condition happening where things weren't fully initialized on the instance itself which would cause it to fail.

Haven't seen this happen since making the change.
