### ISSUE TITLE
Design intent | 10-10EZ Short Form |Auto-qualifiers

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27617]
## Steps to complete Design Intent Collaboration
- [x] VFS Product Manager or Designer: Create this issue and fill in your team and feature name in the title. 
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Platform reviewers and VFS team attendees (listed below).
- [ ] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below.
- [x] Platform: After meeting is held, create feedback tickets and link to the Design Intent ticket (if no feedback, please comment stating that).
- [ ] VFS: Respond appropriately to Platform feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [x] No

## Artifacts
- [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)
- [User flows](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/A71F1C96-FF98-42A2-9ADD-6D4B7A1DDB20)
- More logic/specs details #26850 

**Design files**
- [Pre-qualification screen for authenticated user](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/1Kz2Pak) that has a confirmed disability rating of ≥50%
- [Popup for user that self-reports ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4avmPrd) a disability rating of ≥50%.

Variations for form screen once disability rating of ≥50% has been determined
- [Banner version](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/qe0boak)
- [Alert accordion version](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/paoQKOk) (similar to alert accordion that is about to be in the experimental design system from Leyda, Becca, Riley.

### Project Overview

In order to improve the submissions and user experience for Veterans applying for health care using the online 10-10EZ application, we are looking to implement the ability to recognize automatic qualifiers and use those to skip portions of the online form. The primary example of this is using the user's combined service-related disability rating to skip sections of the form containing information that is no longer relevant, such as the household and financial information.

The proposed flow would be something like this:

The Veteran begins the 10-10EZ online form
If they have logged in, when we retrieve their account information we will also retrieve their combined service rated disability.
The Veteran will fill out any remaining or blank personal information (address, phone #, etc.)
If the combined service related disability meets the qualifications, we will inform the Veteran they may skip other sections and then take them to a later point in the form (likely Insurance information or Review).
Designs and flows are still being finalized but from a general perspective the work includes:
1. Retrieving new profile information (combined disability rating)
2. Dynamically altering the flow to skip chapters and sections
3. For any information we skip, we may need to send certain default values to the backend system
4. There may be new a new screen or messaging to discuss the fact that the veteran can skip sections.

## Meeting attendees from requesting team
- Designer(s) (required): Dene Gabaldon
- Product Manager (required): Chris Dyer
- OCTO-DE Design Lead (required): Ryan Thurlwell
- OCTO-DE Product Lead (recommended): Ming Ligh
- VFS content, IA, and QA specialists (if applicable): Angela Fowler, Josh Kim, Shawna Hein
- Other stakeholders you want to invite (if applicable): Dat Tran, Daniel Nalbach

### Design Intents can only be scheduled on Monday, Tuesday, or Friday. 

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York). <br>

**Date/time:  7/27 @ 11:30**
 
Please note:
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
For the Design Intent, you'll receive feedback from design and IA only. You won't receive feedback from accessibility, content, or QA, as it's too early in the development process.

Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
This has been scheduled for 7/27 @ 11:30
