### ISSUE TITLE
EKS worker nodes - ami pruned

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#27613]
## Description
Since our ami images are pruned monthly, we ran into the scenario where the EKS clusters could no longer find the ami it needed to deploy new worker nodes.  This resulted in downtime.

To fix this we need to get the packer build up and running which will create the image and update the launch template for all of our clusters.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] GHA to build new ami and update launch templates for ASG

## Definition of Done
- [x] GHA does what its supposed to defined in tasks

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by mleclerc00** [comment]
This is now complete.  The packer build (https://github.com/department-of-veterans-affairs/devops/actions/workflows/packer-build-eks.yml) is set to run on a schedule or can be triggered manually in order to build out a new EKS worker node ami.  This will ensure that worker nodes both stay up to date and have a valid ami that wont be pruned due to the 30 day cleaning schedule.
