### ISSUE TITLE
Translation Recommendation | Vendor Feature Matrix

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#27633]
## User Story

As a product manager/owner I would like to compare capabilities from a variety of TMS* providers to understand their offerings and determine which one(s) best meet our translation needs.

Note: *A translation management system (TMS) is a centralized platform used to manage, automate, and implement multilingual projects.

## Tasks

- [x] Gather recommendations from other governmental agencies on TMS providers
- [x] Identify 2 private and 1 open source provider that integrate with Drupal and/or Github

## Acceptance Criteria

- [ ] Research and compose a feature matrix with 3 vendors for further evaluation
