### ISSUE TITLE
[FSR] Add the Veteran's benefits to the financial overview's total income 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27636]
## Issue Description
_The Debt Management Center (DMC) considers Veterans' compensation and pension benefits to be part of their income. The online FSR doesn't add Veterans' benefits amount to the total income on the resolution request page. However, it adds their spouse's benefits amount if applicable. We should explore if it's feasible to add logic that adds Veterans' benefit amounts to their total income so they have a clearer picture of their financial situation when selecting a resolution._

**Compensation & Pension benefits screen for reference**

![fsr-disability-compensation-benefits.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/6ad27d26-9653-4b85-b3a1-7266d6ea3603)

**Financial overview for reference**

![fsr-financial-overview.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/7040bd55-f6dd-478a-b612-3b5b801f35e1)

---
## Tasks
- [ ] _Discover if it's possible to add the disability compensation & pension benefits to the total monthly income displayed on the resolution selection screen_
- [ ] _If it's possible, implement the logic or create a follow-on ticket based on the loe_ 
- [ ] _If it's not possible, document why so we can reference it in the future_ 

## Acceptance Criteria
- [ ] _It's been determined whether or not adding the disability compensation & pension benefits to the total monthly income is possible_
- [ ] _If possible, either a ticket has been linked to this ticket for follow-on work or the logic has been implemented_
