### ISSUE TITLE
[Epic] Add 5103 notice info to VA.gov for pension, DIC, and accrued benefits

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#27635]
## Issue Description
We need to add evidence, standard claim, and FDC information to our site that's missing for pension, DIC, and accrued benefits. The pension business line assigned the task of outlining the 5103 notice info that's needed to a P&F (pension & fiduciary) team to work on and they sent us 2 Word docs with all the content they want to add. 

The original request came from  Charlie Dundon and Jesse Rector. Charlie is a program analyst reporting up to Jesse. 

Shireen Lackey is managing the project at a higher level. She's with OAR.

Shannon Hunsicker is the P&F analyst leading the website update (not sure what this means, but it came from Jesse)

We need to assess the best way to add this content to VA.gov...
- Should it be in tier 1 or 2?
- Can we consolidate into one evidence page / one standard claims page / one FDC page? Or do we need to have separate pages for each (i.e., 5 standard claims pages for each of these: disability, Veterans Pension, Survivors Pension, DIC, and accrued benefits)?

---
## Tasks
- [x] Try assembling a consolidated Evidence page to see if it works (after seeing the consolidated page, we won't move forward with this approach--there will be too great a burden on Veterans to find the info they are looking for)
- [x] Create 4 separate Evidence pages for Veterans Pension, Survivors Pension, DIC, and accrued benefits
- [x] Create 4 separate FDC pages for Veterans Pension, Survivors Pension, DIC, and accrued benefits (not sure if we need one for accrued benefits??)
- [x] Create a consolidated Standard Claims page in R&S
- [x] Create a consolidated FDC page in R&S (now we know we probably won't go in this direction)
- [ ] Reconfigure tier 1 page: About VA DIC for spouses, dependents, and parents (pull evidence info out of accordions--it has been moved to a new page about evidence for DIC)
- [ ] Redirect "Fully developed claim for a VA pension" to ?? (all the content from this page has now been split up into Evidence needed for your Veterans Pension claim, FDC for Veterans Pension, and Standard claims)
- [ ] 

## Preview links

SINGLE CONSOLIDATED
Consolidated standard claims: http://preview-prod.vfs.va.gov/preview?nodeId=27713
H1: **Standard claims for pension, DIC, and accrued benefits**   /  H1 in disability hub: **Standard disability claims**

Consolidated FDC: http://preview-prod.vfs.va.gov/preview?nodeId=27739
**Note:** Mikki, Danielle, and I decided this is too much info to sort through. We'll be creating targeted FDC pages for each benefit.

Consolidated Evidence: http://preview-prod.vfs.va.gov/preview?nodeId=27420
**Note:** Mikki, Danielle, and I decided this is too much info to put on one consolidated page. We'll be creating targeted evidence pages for each benefit. 

SEPARATE EVIDENCE
**Evidence needed for your Veterans Pension claim**: http://preview-prod.vfs.va.gov/preview?nodeId=27770 
**Note:** This content already exists in a Veteran Pension FDC page in tier 1. Outstanding question about whether the evidence content moves off the tier 1 Veterans Pension FDC page.

**Evidence needed for your Survivors Pension claim:** http://preview-prod.vfs.va.gov/preview?nodeId=27801 
**Evidence needed for your DIC claim:** http://preview-prod.vfs.va.gov/preview?nodeId=27803
**Evidence needed for your accrued benefits claim:** http://preview-prod.vfs.va.gov/preview?nodeId=32887

SEPARATE FDC
**Fully Developed Claim for Veterans Pension**: http://preview-prod.vfs.va.gov/preview?nodeId=28032
**Note:** There's already an existing Veterans Pension FDC page in tier 1. For now, we won't move forward with this separate FDC page in R&S. We'll instead update the existing tier 1 page.

**Fully Developed Claim for Survivors Pension:** http://preview-prod.vfs.va.gov/preview?nodeId=32879
**Fully Developed Claim for DIC:** http://preview-prod.vfs.va.gov/preview?nodeId=32878
**Fully Developed Claim for accrued benefits:** http://preview-prod.vfs.va.gov/preview?nodeId=32888

**Added:** Fully Developed Claim (FDC) program FAQs: http://preview-prod.vfs.va.gov/preview?nodeId=32889

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@lunascoop For tasks 3 and 4, creating consolidated pages for Standards Claims and FDC, I'm attaching 2 Word docs here for you. I'm going to turn this ticket into an Epic, so go ahead and create 2 separate tickets for tasks 3 and 4. Thanks![https://app.zenhub.com/files/133843125/19119b57-af06-4b01-91c6-10bad47d457c/download](https://app.zenhub.com/files/133843125/19119b57-af06-4b01-91c6-10bad47d457c/download)[https://app.zenhub.com/files/133843125/d89a8f82-d353-4ed4-a2ea-e3d490dfc81a/download](https://app.zenhub.com/files/133843125/d89a8f82-d353-4ed4-a2ea-e3d490dfc81a/download)

**Comment by bethpottsVADEPO** [comment]
@lunascoop I'm not sure what the best CTA button will be for each of these pages. 

For now, for Standard Claims, you can do this:
File a standard disability claim
https://www.va.gov/disability/file-disability-claim-form-21-526ez/start
File a standard Veterans Pension claim
https://www.va.gov/pension/application/527EZ/introduction

For FDC, do this:
File an FDC for disability 
https://www.va.gov/disability/file-disability-claim-form-21-526ez/start
File an FDC for Veterans Pension
https://www.va.gov/pension/application/527EZ/introduction

Thanks!

**Comment by bethpottsVADEPO** [comment]
@lunascoop Another ticket for you to create and another new page for you to build out in R&S:

[https://app.zenhub.com/files/133843125/95871255-6e00-417c-be8d-87972b5dc995/download](https://app.zenhub.com/files/133843125/95871255-6e00-417c-be8d-87972b5dc995/download)

**Comment by bethpottsVADEPO** [comment]
Hi @lunascoop! 
1/ Can you drop all the preview links at the top of this ticket? For all the experimental pages you've been creating in drupal?
2/ Can you create separate pages for FDC and evidence for each: Veterans Pension, Survivors Pension, and DIC

**Comment by lunascoop** [comment]
Hi @bethpottsVADEPO I've updated the ticket description with the experimental pages created thus far. I'll work on the separate pages for the FDC.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Are there any FDC pages yet or do you have an ETA? I'm asking so I can plan for my meeting with stakeholders. Thanks!

**Comment by lunascoop** [comment]
Hi @bethpottsVADEPO I updated the ticket description with the FDC pages. I also created a Fully Developed Claim (FDC) program FAQs page that pulls out the **Questions you may have about the FDC program** section in the consolidated FDC page. I thought to create a FAQ page, instead of duplicating the content for the separate FDC pages. I included a CTA link to the page for now on the separate FDC pages. Here are my other notes:

- Pieced together content for accrued benefits fully developed claim based on the evidence needed page. 
- Need relevant info for the accordions in section **What should the evidence show to support my claim?** of the separate evidence needed pages (for survivors pension, accrued, DIC pages). That info isn't in the doc, or any tier 1 page. There's content on the Veteran's Pension version, but I don't think it's applicable.

**Comment by bethpottsVADEPO** [comment]
Hi @lunascoop Can you drop the preview links into this section at the top of the ticket:

SEPARATE FDC
Veterans Pension FDC:
Survivors Pension FDC:
DIC FDC:
Accrued benefits FDC:

**Comment by lunascoop** [comment]
@bethpottsVADEPO Sorry I must not have saved my updated comment at the top of the ticket last Friday. I've re-added the preview links.

**Comment by bethpottsVADEPO** [comment]
Next: @bethpottsVADEPO to meet with Pension stakeholders to review this approach:

**Leave tier 1 content as is and make any necessary updates/additions to existing pages.**
- Veterans pension: add new 5103 content to existing tier 1 page instead of creating new evidence and FDC pages: Fully developed claim for a VA pension
- DIC: add new 5103 content to existing tier 1 page instead of creating new evidence and FDC pages: About VA DIC for spouses, dependents, and parents

**Create a new tier 1 page for accrued benefits.**
This page will live in family member benefits section: /family-member-benefits/accrued-benefits
We'll link to it in the first section, just after "Compensation for surviving spouse and dependents (DIC)"

It will also be linked to from the Other VA benefits and services section of content on both of these pages:
- https://www.va.gov/disability/
- https://www.va.gov/pension/

**Create new R&S articles for:**
Evidence needed for your Survivors Pension claim: http://preview-prod.vfs.va.gov/preview?nodeId=27801
Evidence needed for your accrued benefits claim: http://preview-prod.vfs.va.gov/preview?nodeId=32887
Fully Developed Claim for Survivors Pension: http://preview-prod.vfs.va.gov/preview?nodeId=32879
Fully Developed Claim for accrued benefits: http://preview-prod.vfs.va.gov/preview?nodeId=32888

**Comment by lunascoop** [comment]
@bethpottsVADEPO there's no new accrued benefits tier 1 page. I deleted all the nodes in the description with the exception of the two accrued benefits claim pages.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Thank you!!

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
