### ISSUE TITLE
Dependency verification midpoint review UI punchlist

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#27634]
### Background
The dependency verification modal needs to move through the Collaboration Cycle midpoint review. A few things need to be addressed per feedback from the design intent review.

### Considerations
- Even though reviewers should concentrate on just the modal flow, there was feedback on the underlying page per design intent
- We showed tool-page version 2 layouts in design intent; we are going with V1 for the midpoint review based on waht's in staging
- Some things in staging will have to be fixed before midpoint; it's primarily fit-and-finish UI work
- Staging user tested: Kenneth Andrews (number 3)

### Tasks
- [x] Modal: Move primary "Change dependents button" to the left
- [x] Remove bolding from "Relationship"
- [x] Change breadcrumb to match H1 ("Your VA dependents")
- [x] Use correct style for lead-in/subhead copy ("Below is a list of dependents...")
- [x] Reduce whitespace between green button and H2
- [x] Change font for dependents names in cards to Bitter
- [x] Confirm mask/no masking on SSN in cards
- [x] Remove bolding from relationship, SSN and DOB in the cards
- [x] Change styling of "No dependents..." message at bottom to gray box (mockup)
- [x] Change heading of first section in the right sidebar to "When should I notify VA about dependents on my benefits?"
- [x] Add space in first section, first paragraph: "...status. Changes..."
- [x] Add link to bottom of first section in right sidebar: "Find out more about dependents and your benefits" (https://www.va.gov/disability/add-remove-dependent/)
- [x] Change text link from "Get help filing a claim" to "Get help filing your claim or appeal"
- [x] Increase padding/margin between last item and the footer

### Acceptance criteria
- [x] Items in punchlist above addressed

**Comment by micahchiang** [comment]
PR for breadcrumb update here - https://github.com/department-of-veterans-affairs/content-build/pull/388
