### ISSUE TITLE
Adjust PDF Generation for VA Form 21-686c

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#27639]
## Background
The dependency claims submission was having a tough time generating a pdf after some recent changes.

## Considerations
An error is being thrown extracting the middle initial from the full name.

## Tasks
- [x] Adjust the pdf generation code to fix the middle initial error
- [x] Verify that middle initials are being printed on the PDF properly

## Acceptance Criteria
- [x] Middle initials are displaying properly on the 686 PDF
- [x] A PR has been requested for merging
