### ISSUE TITLE
Resocialize entire publishing workflow

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27643]
# User story

As a Platform website author, I need to know the complete publishing workflow so that customers can access the info I've written.

# Tasks

- [ ] Write how-to guide about navigating others' changes in changelog
- [ ] Write message #platform-team / #vsp-confluence (and incl. guide)
- [ ] Send message to #platform-team / #vsp-confluence

# Acceptance criteria

- Message links in to how-to guide
- Message is sent to #platform-team / #vsp-confluence

# Reference info

- [Making Platform website changes live](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1763442706/Making+Platform+website+changes+live)
- Message will include distinguishing Conf + SVP site

**Comment by lianilychee** [comment]
Weds 7/21:
- Amy will have another revision of guide by tmr SU
  - We can probs link the "Create a page" guide in the message
- Gretchen will share the draft with Amy and Liani so they can join the swirling

**Comment by lianilychee** [comment]
Gretchen's draft
---
Looking across recently published docs, we’re seeing some variations in formatting and organization. Being consistent in how we format and structure similar types of content will make our docs easer to read and understand.  
Review these sections of our style guide to help you as you write:
Lists
Notes, cautions, and warnings
Page titles and headings
Templates
We have templates for How-to documents and Overview documents that we encourage you to try out. They templates include pre-formatted starter text, prompts to help you think through your page structure, and standard sections. 
Table of contents
ScrollViewport generates a table of contents in the right column for each page based on a page’s headings and subheadings. Be mindful of how you organize your content and double-check that the table of contents in the right column gives a clear, at-a-glance overview of the topics covered in your doc.
We’re excited to see so many of you publishing content and looking forward to the Platform website growing into a useful resource for VFS teams!

**Comment by amygoldman** [comment]
For the sake of maintaining formatting and especially links, [here's my draft in Confluence](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1771864104/Draft+of+Slack+message+for+style+guide+publishing+reminders)

**Comment by lianilychee** [comment]
thurs 7/22:
- Amy - will add screenshots to changelog part of guide in ~1hr, will send to Liani and Gretchen for review
- entire team to look at draft after SU

**Comment by lianilychee** [comment]
Tues 7/27:
- post message Number 1
- Split up messages Number 2, into 2 and 3 (3, which is about the templates, would likely go out next week)
- add supporting visuals to 3 (templates)

**Comment by lianilychee** [comment]
Weds 7/28:
- Today: 
  - wanna finish the style guide so G can review tmr
  - Share templates message
- Tmr: Share style guide message

**Comment by lianilychee** [comment]
Thurs 7/29:
- style guide just about ready for G's review - just need titles and page headings section
- can still share message w/o G's review
