### ISSUE TITLE
[FSR] Update the wizard to the proper PDF download pattern

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27641]
## Issue Description
_There are multiple terminals in the FSR's wizard that direct folks to submit the FSR's paper version. However, those links all redirect to the FSR's 'Find a form' page. It's counterintuitive to not just provide the PDF download in the result. There's multiple patterns for PDF downloads on VA.gov, so we need to discover which is the proposed direction and update the wizard UI as needed_

---
## Tasks
- [ ] _Discover what PDF download pattern is recommended_
- [ ] _Update the appropriate wizard results as needed_

## Acceptance Criteria
- [ ] _The wizard has been updated with the recommended PDF download styling and linked in this ticket_
- [ ] _A ticket for frontend implementation has been linked to this ticket_

**Comment by denisecoveyduc** [comment]
Veterans are currently directed to the  Find a Form page for the 5655 which has the ability to easily download a pdf copy should they wish to do so. This ticket is no longer required as a result.
