### ISSUE TITLE
[FSR] Real estate estimated value bug

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27640]
## Issue Description
_I added real estate with a value of $200,000 to the form. I was eventually signed out due to being afk, and when I signed back in I noticed the estimated value now displays as `$NAN$`. Editing the value doesn't update it._ 

### Screenshot of the bug

![fsr-real-estate-bug.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/b654e48b-a143-4c46-bdc8-95c5a60734e1)

---
## Tasks
- [ ] _Troubleshoot why the real estate's estimated value is showing up as `$NAN$`_
- [ ] _Implement a fix for the bug_ 
Please reach out to Riley for more information about this bug!

## Acceptance Criteria
- [ ] _The correct real estate's estimated value displays_

**Comment by josephrlee** [comment]
Closing this ticket as it's no longer relevant since this is from the deprecated list loop pattern. 

cc: @mgleo , @denisecoveyduc , @Tom-Davis , @dhill802 , @charlottecesana
