### ISSUE TITLE
Iterate on and publish a refined Platform website GA dashboard

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27646]
# User story

As a Content team member, I want a way of monitoring the Platform website's health so I can identify how it can be improved.

# Tasks

- [ ] See what all information we are receiving in the dashboard.
- [x] Identify the metrics we want from (a)  Analytics' Content KPIs and (b) our team's expertise in content analytics
- [ ] Determine how to display the info - Domo?  Google Data Studio? (not Google Analytics Dashboard)
- [stretch] Manipulate the info to render on our dashboard of choice

# Acceptance criteria

- Shared with Rachael Roueche

# Reference info

- creating a dashboard
  - [GA dashboard](https://analytics.google.com/analytics/web/#/report/content-event-overview/a50123418w224573768p240292331/)
  - [SD's Platform customer support Data Studio dashboard](https://datastudio.google.com/u/0/reporting/c4259d38-3515-486f-8fad-82ea06dadc4f/page/F3VEC)
  - [Platform website Data Studio dashboard](https://datastudio.google.com/u/0/reporting/7a104c68-1c6d-4a75-90a3-b1041639bc6d/page/Es9VC)
- identifying the KPIs
  - [Liani's questions to the Analytics' team about their KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27792)
  - [Analytics' Content KPIs](https://vfs.atlassian.net/wiki/spaces/AT/pages/1651867793/WIP+-+Data+dictionary+VA.gov+Content+KPIs)
  - [Liani's MURAL scribbles](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1617819869492/7e8239a6633c039669db26e32b11bb16f9f490b4?wid=0-1626370107492&outline=open)
- Analytics' requests
  - [Domo access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27924)
  - [Content KPI dashboard request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27914)

**Comment by lianilychee** [comment]
Weds 7/21:
- by tmr SU, have read thru Analytics' Content KPIs + started to ask James about the dashboarding tool they used for Support bot

**Comment by lianilychee** [comment]
thurs 7/22:
- today:
  - determine if I should check with James or Rebekah Hickey?
  - think critically about Joanne's KPIs; what should stay or go?
    - read Gretchen's link

**Comment by lianilychee** [comment]
fri 7/23:
- gretchen rec's talking to ian mccullough, who made a domo dashboard on his own!
- will be talking with james and rebekah today about google data studio
- adding more KPIs, using Joanne's suggestions as a starter

**Comment by lianilychee** [comment]
Tues 7/27:
- reconcile my questions/notes in each KPI with what Analytics has actually recommended
- Find each KPI within the Google Analytics dashboard
- submit analytics dashboard request for canned content dashboard

**Comment by lianilychee** [comment]
Weds 7/28:
- Today:
  - ask Rebekah what her level of familiarity is w/ Google Tag Mgr; if it is high, then sked something with Rebekah
  - Find one KPI within the Google Analytics dashboard
