### ISSUE TITLE
Assess Facility Locator page hierarchy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27659]
## Issue Description
Based on screen reader usability findings, we need to assess and refine page hierarchies for Facility Locator and its detail pages 

- Establish a page hierarchy (page outline with intended H1s, H2s, H3s, regions etc)
- Eg. ~COVID content~ and links should move into an alert region that can be announced as such
- Are map, results listing, search areas properly named?

Related: Group Facility Locator COVID content and links under a heading #27447

Page map tool? 

---
## Tasks
- [ ] Work with accessibility team to determine opportunities to improve page navigation
- [ ] Identify design patterns which can be used

## Acceptance Criteria
- [ ] Tasks to improve the screen reader user experience are identified and can be groomed by engineers

**Comment by laflannery** [comment]
Done with current audit and will be done again with new iteration of facility locator
