### ISSUE TITLE
[UNPLANNED] Adjust 686 Upload to VBMS

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#27651]
## Background
The dependency claims submission was having a tough time uploading a PDF to VBMS after some recent changes.

## Considerations
From Sentry: "Invalid format for Veteran Identifier."

## Tasks
- [x] Update the VA File Number class from `Nori::StringWithAttributes` to `String`

## Acceptance Criteria
- [x] The 686 PDF is being uploaded to VBMS
- [x] A PR has been requested for merging
