### ISSUE TITLE
Create React bindings for web component library

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#27691]
## Issue Description

Our Web Components can be used as-is within React, but we will not be able to add event listeners to them using the `on*` prop syntax. We would have to revert back to the `domNode.addEventListener()` style, which is not desirable.

In order to be able to use the `on*` event handler syntax with our web components, we will need to create [React bindings as a Stencil output](https://stenciljs.com/docs/react#bindings). This may mean that we will turn `component-library` into a monorepo, since the docs say:

> If you're going to compile your Stencil components into multiple framework libraries, it's recommended to create a monorepo project that contains the Stencil library alongside each framework library for easier maintainability.

---
## Tasks
- [ ] Find out if a monorepo is necessary, or if simply adding a build output target will suffice
- [ ] Output React bindings as part of the web components build
- [ ] Ensure that the `on*` handler syntax works with the React bindings
