### ISSUE TITLE
Complete transition to PPMS secure endpoint

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27705]
## Issue Description
The new secure endpoint for PPMS will be available in Production by the end of July. 
We need to complete and test our transition to this endpoint. 

---
## Tasks
- [ ] Import new keys for Production
- [ ] Configure in Staging/Prod
- [ ] keep behind flipper until tested
- [ ] Test

Documentation will be done in #27704 

## Acceptance Criteria
- [ ] Veterans search experience for searching community providers in VA's network remains unchanged
