### ISSUE TITLE
(Stretch) Audit GA/GTM Specialist onboarding documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27717]
## Issue Description
We have a general Analytics [onboarding doc](https://docs.google.com/document/d/1qOVmksOT-MCTM8e1icZPYsNM9fQS36i0oTA3UHgE4Ss/edit) and [team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-insights-team-charter.md), but we don't have one that's specific to Google Analytics/Google Tag Manager

---
## Tasks
- [x] In Confluence, document topics that new GA/GTM implementation & reporting specialists need to be successful on the Analytics team.
- [x] Audit current Github documentation for docs related to the documented topics

## Acceptance Criteria
- [x] Platform Analytics understands the topics that a GA/GTM specialist needs in order to successfully onboard to the Platform Analytics & Insights team

**Comment by laurensimpson14** [comment]
See ticket 28936. Closing.
