### ISSUE TITLE
Audit Analytics orientation documents

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27711]
## Issue Description
Audit orientation documents.

---
## Tasks
- [x] @joanneesteban share current orientation deck
- [x] @joanneesteban share data platform ownership doc
- [x] @joanneesteban update content requirements for orientation deck
- [x] @chloedotbrown audit Github for any relevant VFS orientation documents

## Acceptance Criteria
- [ ] Platform Analytics knows what's currently available for Analytics orientation vs. what's still needed

**Comment by chloedotbrown** [comment]
In addition to the [Analytics Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/analytics-playbook.md) (which I assume is already on the list?) these Github docs could also be relevant to VFS new member orientation:
- [GA 360 Platform](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/ga360-platform-access-levels.md): Maybe doesn't need to be transferred over wholesale from Confluence site, but high-level summary of GA and GTM would be useful for FAQ.
- [Guide to the GA Tagging Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/rules-of-engagement-analytics-implementation-qa.md): This is straight-forward and brief, may be helpful to include on it's own or as part of orientation slides.
- [GA Cheat Sheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/google-analytics-cheat-sheet.md): Not a must-read for everyone right away, but knowing this resource exists/where to find it would be good for folks who do want to dive into GA.
- [Analytics Opt-out](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/opting-out-google-analytics.md)

**Comment by chloedotbrown** [comment]
Closing, since orientation materials are complete and in use.
