### ISSUE TITLE
Publish iterated Analytics Orientation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27710]
## Product Outline
[Link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587478606/Platform+Analytics+-+WIP)

[Sprint Planning Workshop link](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1598479416734/2f7bfbc19bf0629c0c9b5fcc559444aec95e2256?wid=0-1626882907525&outline=open) 

## High Level User Story/ies
As a Platform Analytics & Insights team members, I need to understand what and how I can support VFS teams so that I can answer their analytics questions when they onboard.

As a VFS PM / PO / Researcher, I need to learn how to work with and communicate with the Analytics team (the analytics process) so that I know how to get analytics & get my analytics questions answered quickly.

As a VFS FE, I need to learn what analytics I’ll be implementing vs. what the Platform Analytics team will be implementing so that I can understand what my analytics responsibilities are.

As a VFS FE, I need to learn what analytics I’ll be implementing vs. what the Platform Analytics team will be implementing so that I can understand what my analytics responsibilities are.

## Hypothesis or Bet
If we iterate on our Analytics orientation and introductory documentation, then VFS teams will understand how to work with and communicate with Platform Analytics when they go through Platform orientation.

## OKR
OBJECTIVE 1: Info for all common VFS needs are findable in Platform Website							
KR: 50% of VFS's analytics questions on Slack & Github are redirected to the Platform Website.
KR: Decrease Platform Analytics time spent on support questions by 50%.
KR: Increase engagement with Analytics documentation.

### What must be true in order for you to consider this epic complete? 
- [x] Update, QA, and migrate orientation documentation in Confluence
- [x] Update, QA, and migrate Platform Analytics general FAQ in Confluence
- [x] Update and QA analytics tools access request templates

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by joanneesteban** [comment]
Orientation documentation up to date. The Getting Started doc may need some IA edits, but this will be in a future sprint. Closing this epic.
