### ISSUE TITLE
Audit Analytics orientation documents

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27712]
## Issue Description
Audit orientation documents.

---
## Tasks
- [ ] @joanneesteban share current orientation deck
- [ ] @joanneesteban update content requirements for orientation deck
- [ ] @chloedotbrown audit Github for any relevant VFS orientation documents

## Acceptance Criteria
- [ ] Platform Analytics knows what's currently available for Analytics orientation vs. what's still needed

**Comment by joanneesteban** [comment]
Zenhub error caused dupe. Closing this ticket.
