### ISSUE TITLE
Draft & update data engineering documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27716]
## Issue Description
As Jason offboards, the Platform Analytics & Insights team needs to understand the workflow & processes that our data engineer does to support the Analytics product and VFS teams.

---
## Tasks
- [ ] Review the Analytics user journey & note steps that the data engineer is involved in
- [ ] Write & update documentation based on the steps from the review
- [ ] _Stretch:_ Provide notes or documentation to Joanne about Analytics Team Lead (TL) responsibilities
- [ ] QA for understanding - @chloedotbrown @bsmartin-ep before Jason leaves

## Acceptance Criteria
- [ ] New & current Platform Analytics team members understand the work done by the team's data engineer to support the Analytics product & VFS teams.

**Comment by joanneesteban** [comment]
@JasonTheBearded it might also be helpful to go through your column on the RACI for documentation. https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit#gid=0

**Comment by joanneesteban** [comment]
## 07-26-2021 - Documents

@JasonTheBearded 
Documentation priorities from our sync:

Bolding the first 3 priorities. These are the need to have.

**1. Setting up current data sources in BQ**

**- [ ] Medallia**
**- [ ] ForeSee**
**- [ ] Google Analytics for VA.gov**
**- [ ] Google Analytics for documentation (dif property)**
**- [ ] Github**

**2. Domo Dashboard creation**

**- [ ] Technical discovery for requests (i.e. technical feasibility, grooming)**
**- [ ] Writing SQL queries**
**- [ ] Creating BQ views**
**- [ ] ETL dataset within Domo**
**- [ ] Documenting queries**
**- [ ] QA calculations & definitions in the Data Dictionary**
**- [ ] Maintaining the dashboards: is the data still updating?**

**3. Account management**

**- [ ] Edit vs. View, etc.**
**- [ ] API access**
**- [ ] Process for working with other VSP teams (we're not currently providing BQ access to VFS teams)**

4. Dashboarding bug reports

- [ ] Triaging bug requests
- [ ] Data bug - query updates

5. Cloud storage

- [ ] Capacity limitations & best practices

6. BigQuery ownership - "see BigQuery documentation"

- [ ] Stand up new BQ tables, views, schemas
- [ ] Automate pipelines to collect data from new sources
- [ ] Account Management & Security

7. Coordinating with Google Tag Manager/Google Analytics implementation

- [ ] Documentation about data structures, if anything

8. Team Lead responsibilities

- [ ] *ask Fleet about the general TL responsibilities document. 
- [ ] See if there’s anything to add

---
These are less of a priority than the preceding tasks.

9. Setting up future data sources in BQ

- [ ] DataDog
- [ ] Speedcurve
- [ ] VANotify
  - [ ] PowerBI

10. Setting up direct to Domo data

- [ ] Contact center forms
- [ ] Google Sheets
- [ ] Activity Log

**Comment by JasonTheBearded** [comment]
Data Engineering documentation draft, https://vfs.atlassian.net/wiki/spaces/AT/pages/1777762305/WIP+-+Data+Engineering+processes+responsibilities

**Comment by JasonTheBearded** [comment]
Documentation complete. Closing ticket
