### ISSUE TITLE
Update analytics tools access request forms

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27715]
## Issue Description
Update the Github request template for folks to request access to Google Analytics, Domo, and BigQuery

---
## Tasks
- [x] @laurensimpson14  Determine what the Analytics support folks need to provide secure, accurate, and trackable tools access
- [ ] @JasonTheBearded Determine a standardized process to add groups & people to Domo
- [x] @laurensimpson14 Update the Github request template
- [x] @laurensimpson14 Add an easier way for teams to add email addresses
- [x] @joanneesteban @jennaouellet QA the updated template

## Acceptance Criteria
- [x] Platform Analytics can easily, securely, and accurately add new onboarded VFS and VSP team members to analytics tools

**Comment by joanneesteban** [comment]
@laurensimpson14 Checking in on this. Do updates to the Domo & Google Analytics access request form need to be make?

**Comment by laurensimpson14** [comment]
I created a pull request that is ready to be QA'd @joanneesteban and @jennaouellet: https://github.com/department-of-veterans-affairs/va.gov-team/pull/28254

I'm hoping that the 3 steps are easy to follow. 

In step #3 - do we use the info if folks list what team they are on? Is this step necessary?

**Comment by joanneesteban** [comment]
Thanks for working on making this request lean, @laurensimpson14 ! Closing this ticket.
