### ISSUE TITLE
Update Analytics orientation deck

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27714]
## Issue Description
Iterate and update the [Analytics orientation deck](https://docs.google.com/presentation/d/1TKYK88pHqNAJ0HrGtXIjnDYPQT-ccBQcOTy64kd0cd4/edit#slide=id.g5f29ec5fc2_4_71) for VFS teams.

---
## Tasks
- [x] @joanneesteban to update orientation deck
- [ ] @laurensimpson14 & @jennaouellet to review the deck for content & understanding

## Acceptance Criteria
- [x] New VFS teams and team members can get basic Analytics questions answered when they orient through the Collaboration Cycle.

**Comment by joanneesteban** [comment]
## 7-26-2021

@laurensimpson14 a few updates.

- Added a WIP flag on the deck title just in case a VFS team member looks at the orientation deck
- I'm adding WIP & DONE flags on each slide title. You can use this to check content. I'd like to make some design changes afterwards.
- Rearranged the agenda, but would love a gut check on it.

Context for the deck length, too. The deck should be presented in 20 min or less, so the more "to the point" we can make this, the better.

**Comment by joanneesteban** [comment]
## 7-29-2021

@laurensimpson14 All the content is ready for final review! The only slide with non-updated content is the Additional Resources slide, and that won't be ready until the Confluence "Getting Started" doc is published to the Platform Website.

I also made a couple of visualization updates, but, again I'd like all of the slides to get a visual update. I have time set aside to finish this when I get back next week, but please feel free to edit where you see fit!

@chloedotbrown I also added a couple questions around the data journey visuals.

**Comment by chloedotbrown** [comment]
@joanneesteban Responded to the call outs where I saw them. Let me know if there's anything else I've missed? In the meantime, big thanks to both you and @laurensimpson14 – these are looking really good!

**Comment by joanneesteban** [comment]
## 8-02-2021

All the slides are up to date except for the additional resources slide (slide 20)! Thanks for the collab! Feel free to make additional edits, and to update the Additional Resources slide as well.
