### ISSUE TITLE
Draft iterated general Analytics readme/FAQ

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27718]
## Issue Description
What information do new VFS team members need to know about the Analytics team and the 

---
## Previous general FAQ/Readmes

- [Outdated GH readme](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics#readme)
- [Outdated “Data Journey”](https://docs.google.com/presentation/d/1OGdCLFYGA4cb5nDUTJOme_7UBdAM49bX5zpYZ-zg6rw/edit#slide=id.g6d866f9dc2_0_165)
- [Analytics Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/analytics-playbook.md)
    - This will be more detailed than a general FAQ/Readme
    - The FAQ/Readme drafted this sprint can be added to the Playbook depending on relevancy

---
## Tasks
- [x] Everyone should do a brief review of the entire [VFS analytics experience map](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1623339995796/0beb77efcb6353dc3af5dbcf8212eea8ae0f6de4?wid=0-1626107821966&outline=open) - tasks are in the blue headers. Service blueprint is on the right hand side.
- [ ] Use [this Confluence](https://vfs.atlassian.net/wiki/spaces/AT/pages/1771864128/WIP+-+Platform+Analytics+Insights+FAQ+Readme) page as a working draft to add Q&A on the following tasks:
  - [x] @chloedotbrown @joanneesteban "Table of Contents" audit - what are the general headers folks need to know?
  - [x] @joanneesteban team make up
  - [x] @chloedotbrown @joanneesteban What general data is available (beyond GA)
  - [x] @laurensimpson14 Slack support - is there anything beyond the [customer support guidelines](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html) that they need to know?
  - [x] @bsmartin-ep @jennaouellet GTM implementation & QA process - is there anything beyond the [customer support guidelines](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html) that they need to know?
  - [ ] @bsmartin-ep @laurensimpson14 GTM implementation & standardized tags - which tags come out of the box, which interactions need to be custom created - there are docs, particularly the [build & measuring one](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md), in the Google Analytics folder, but the Information Architecture & plain language needs updating. I recommend starting with a green field here.
  - [x] @JasonTheBearded @chloedotbrown What are the dashboards/reports that folks need to get started with data exploration?
  - [ ] @JasonTheBearded how to work with us to get additional data (beyond what we're already doing with VSP teams. An example of additional data would be PowerBI data or text message data from VA Notify)
- [x] QA internally
- [ ] Reach out to Service Design to help QA

## Acceptance Criteria
- [ ] VFS teams & team members get frequently asked questions answered when they first join VFSs.

**Comment by joanneesteban** [comment]
Reminder: This ticket is for very high level FAQ. What would a _new_ VFS team member need to know about analytics to **get started** on their job? 
- This would be a supplement to the [Orientation presentation](https://docs.google.com/presentation/d/1TKYK88pHqNAJ0HrGtXIjnDYPQT-ccBQcOTy64kd0cd4/edit#slide=id.g5f29ec5fc2_4_71)
- Detailed analytics knowledge will be done in future sprints, and will probably be a part of the Analytics Playbook.

**Comment by joanneesteban** [comment]
The current topic headers on this FAQ are good to go. Everything else should be for a larger Analytics FAQ to keep this documentation lean. If you've started on some of the additional topics,  you can throw them in here: https://vfs.atlassian.net/wiki/spaces/AT/pages/1783333118/WIP+-+Analytics+FAQ

**Comment by joanneesteban** [comment]
Thanks for the work here, everyone! 

We'll be iterating on the "Getting Started" doc as we flesh out our other documentation. Guidance from Content & IA is that 
1. our Getting Started doc will end up being the landing page for our team
2. there's probably too much content in here, and that feeling like we need to add "expands" to our documentation means that things need to either be broken up or whittled down. 

Follow up for this ticket:
1. We'll keep the Getting Started doc as is for now
2. We'll continue adding to the FAQ page & publish towards the end of our documentation initiatives.
3. As we continue fleshing out our documentation, we should whittle down the Getting Started doc. We'll remove content and instead add links to the correct content source.

Closing this ticket.
