### ISSUE TITLE
Update Analytics team SLAs and custom support processes

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#27713]
## Issue Description
Update team charter, SLAs, and clarify internal support processes.

---
## Tasks
- [ ] Identify areas to update SLAs, team charter, & support processes.
- [ ] Update operational documents
- [ ] Workshop/share with team for any updates
- [ ] Publish to Confluence

## Acceptance Criteria
- [ ] Platform Analytics team members agree on and understand expectations for customer service

**Comment by johnny-jesensky-adhoc** [comment]
Still a need -- though will look to discuss specifics on what we should prioritize updating, given the team has completely turned over since this was created. Closing for now.
