### ISSUE TITLE
Provide Input ISO Audit of eBenefits mentions across VA.gov pages

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27737]
## Description
_Public Websites team was ask for FE help to do a search of all eBenefits mentions and use that list to determine what needs to be worked on.  We'll need to provide a breakout of all mentions across VA.gov pages in support of ticket #23161. 

## Tasks 
- [ ] Provide a running list of ebenefits mentions
- [ ] Ensure list is validated by sitewide content team 
- [ ] close out ticket once completed

**Comment by brianalloyd** [comment]
Work completed on initial in-take ticket.  Closing in support.
