### ISSUE TITLE
Add Product question to Collaboration Cycle Kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#27730]
## Issue Description
The Collaboration Cycle Kickoff issue template asks VFS teams:
`2. Is your work a new product/feature or an iteration to an existing product/feature?`
If it is an iteration, the template does not ask what product the iteration is supporting. This information can be assumed, however it is not always easy to tell.

It is important for the Collaboration Cycle team to know which product the iteration is supporting in order to pivot the Collaboration Cycle towards product-focused support, opposed to team/iteration focused support. If we are able to identify the product the iteration is supporting (and hence the Collaboration Cycle is supporting) we will be able to add the VFS product label to issue tickets created at Staging Review. This will allow us to track the health of VA.gov at the product level.

---
## Tasks
- [x] Edit the Collaboration Cycle Kickoff template to ask VFS teams what product the iteration is in support of.
- [x] Edit the Collaboration Cycle Kickoff template to ask if the VFS team has a github label for the product
- [x] Edit the Getting Started page on Platform Website to reflect the same

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@peggygannon just noticed this was supposed to be a ticket you worked on during the tech debt sprint but i never added you as an assignee! Could you please work on it when you have time in the next sprint?

**Comment by shiragoodman** [comment]
@peggygannon yes, I like this idea. go for it!

**Comment by peggygannon** [comment]
@shiragoodman @allison0034  PR for the updates to the CC kickoff template: 

https://github.com/department-of-veterans-affairs/va.gov-team/pull/30348

**Comment by peggygannon** [comment]
PR has been merged. Closing ticket.
