### ISSUE TITLE
Midpoint Review ("Design Intent") [Search & Discovery, Surfacing Search Tools]

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27754]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [ ] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [ ] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [ ] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to feedback tickets.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

#### Has your team met with the Sitewide Content team for content support? 
- [ ] Yes*
- [ ] No

\*If yes, please be sure to include any relevant content artifacts.

## Artifacts
- [Initiative Brief for Surfacing Search Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/surfacing%20other%20search%20tools/initiative-%20brief.md)
- [Initiative Brief for Search Landing Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/search-landing/initiative-brief.md)
- Link to or attach prototype or mockups
- Link to content brief (if applicable)
- Link to or attach your project's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link) 
- Link to research plan ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md))  and conversation guide ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md))
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) for QA practice area review

## Scheduling
Would you like this review to be asynchronous? Please refer to the [Midpoint Review guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-midpoint-review.md) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No
 
### Midpoint Reviews can only be scheduled on Monday, Tuesday, or Friday.

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)<br>

**August 2, 2021 @ 3:30pm
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): Denise Coveyduc
- OCTO-DE Product lead (recommended): John Hashimoto
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Sam Suddath, Megan Gayle
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s) Shawna Hein, Josh Kim, Cindy Merrill

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md)or the [Midpoint Review Touchpoint](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-midpoint-review.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@denisecoveyduc can you please complete the list of attendees above? Thanks!

**Comment by shiragoodman** [comment]
going to move forward with scheduling, however please be sure to answer my question above. thank you.

**Comment by denisecoveyduc** [comment]
@shiragoodman I added the list of participants. Thanks so much for catching that mistake.

**Comment by shiragoodman** [comment]
all attendees have been sent invites.

**Comment by allison0034** [comment]
@denisecoveyduc I am not seeing any prototypes. Do you have screens or something for us to review?

**Comment by peggygannon** [comment]
@denisecoveyduc is there a prototype to review for this work? If so, can you add a link here to the ticket?

**Comment by denisecoveyduc** [comment]
Hi @peggygannon There is no prototype, just designs that @mgleo will share.

**Comment by denisecoveyduc** [comment]
Hi @shiragoodman + team,  Apologies for not providing the designs earlier we assumed we would walk thru during the call and feedback would follow. @mgleo could you please post the designs that you shared during the call. 

We are preparing for usability study to test **one** of the two approaches for a search landing page. 
1- Boxes with a short description
2- Boxes with links offering veterans a sense of what they can accomplish using the tool

The goal is to highlight these search tools to veterans in the event that search doesn't offer the users what they need. 
We would like to identify one approach to move forward with for usability testing. 
Your feedback is greatly appreciated. 

FYSA: @allison0034 @peggygannon @rtwell @joshkimux

**Comment by mgleo** [comment]
![homepage-search-](https://user-images.githubusercontent.com/5553542/127920388-c6470fb3-103c-46b3-a3af-d4c48a0192d3.png)

![search-landing-boxes](https://user-images.githubusercontent.com/5553542/127920213-2af6016c-a723-4869-b2c3-ceb577508fc2.png)
![search-landing-btns](https://user-images.githubusercontent.com/5553542/127920266-dc4d6ab0-e81a-448d-a7f6-29f1decc9a87.png)
![search-results-boxes](https://user-images.githubusercontent.com/5553542/127920572-ef8cd161-8084-42af-a7aa-8e6ce7e642c4.png)
![search-results-btns](https://user-images.githubusercontent.com/5553542/127920591-cfe2ebb0-62ab-4750-ae5c-33dcfe8367a1.png)
