### ISSUE TITLE
Implement solution for tracking VA Business Owner from CC Kickoff ticket

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#27757]
## Issue Description
In June 2021, Product Support updated the CC Kickoff issue template per [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25597) (see 2nd Issue Description). Now that VFS teams are identifying who their VA business owner is in the CC Kickoff issue template, Product Support needs to find a way to track and report out this information.

Solution: the "Business Owner" will be tracked in the [VA.gov Product Directory.](https://depo-platform-documentation.scrollhelp.site/getting-started/VA.gov-product-directory.1898676225.html) We will need to add a step to the internal instructions for Collaboration Cycle Kickoff to ensure that the Business Owners listed for the product/iteration from the VFS team from the Collaboration Cycle Kickoff ticket is correctly reflected in the VA.gov Product Directory.

We are receiving information from the Collab Cycle Kickoff ticket  from VFS teams. That information then needs to be shared in the VA.gov Product Directory.

We also need to ensure that the data/information (focus on Business Owner) from the CC Kickoff tickets submitted from June 16 , 2021 onward is copied over to the VA.gov Product Directory. (contact @shiragoodman to figure out all the tickets)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] We have reviewed all CC Kickoff tickets from June 16 onward and added the VA Business Owner to the VA.gov Product Directory for the appropriate products 
- [ ] We have clear processes for keeping the VA.gov Product Directory up to date with the VA Business Owner
- [ ] We have reported QASP metrics to VSP leadership

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@oapolina1 @allison0034 I have moved this to the backlog and de-prioritized this work. Let me know if you have any questions.

**Comment by shiragoodman** [comment]
OCTO PO is being tracked in the Collab Cycle Reviews gh board: https://github.com/orgs/department-of-veterans-affairs/projects/998/views/15
