### ISSUE TITLE
Collaboration Cycle Kickoff [Search & Discovery - Surfacing Search Tools]

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27753]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] VFS: Attach any available artifacts.
- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- [Initiative Brief for Surfacing Search Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/surfacing%20other%20search%20tools/initiative-%20brief.md)
- [Initiative Brief for Search Landing Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/search-landing/initiative-brief.md)
- [User flow and Wireframes](https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/on-site-search/search-landing/user-flow-wireframes-search.jpg)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [x] New
- [ ] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [x] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [x] Yes
- [ ] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [x] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 6. Will your work include:  

- [ ] New content
- [ ] Changes to existing content

### 7. Are you making a change to the user flow?
- [x] Yes
- [ ] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 8. Are you making a change to urls, navigation, or entry points?
- [x] Yes
- [ ] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 9. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [x] Yes
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 10. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [x] Yes
- [ ] No

### 11. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [x] VEO (Veterans Experience Office)

### Contact(s): 
- DEPO Lead: John Hashimoto
- PM: Denise Coveyduc
- Engineering: Sam Suddath
- Design/Research: Megan Gayle & Cindy Merrill

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @denisecoveyduc. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project (pick 1 below) is a new tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Information Architecture (IA) Request
- Research Plan Review
- Analytics Request
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

No Design Intent  is recommended because wireframes were previously discussed at 7/13 CC Office Hours. Team will move forward with scheduling Midpoint Review.

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). Please review the guidance on our Collaboration Cycle README page for next steps.

@denisecoveyduc would you be able to answer question #11 above? Thanks!
