### ISSUE TITLE
Define SEO Strategy for Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2776]
@rroueche commented on [Tue Dec 12 2017](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6704)

# Problem Statement
Right now when you search for `VA office near me` the search results don't seem very carefully crafted and there's an opportunity to have results from Vets.gov better match up to the query terms and provide a good experience for the searchers. 

Add ‘Google as the front door for Facility Locator and facility product pages’ as a use case to solve for and create an action plan.

<details>
<summary> Example </summary>![image](https://user-images.githubusercontent.com/8680732/33894691-d02f45f4-df1b-11e7-9de8-95799f286574.png)

</details>

# Goals
- Define strategy for how to achieve best in class SEO for folks looking for VA facilities near them

## Tasks
- [ ] Pre-work, deciding the type of facility, etc 
- [ ] Assess keyword searches for top facility types on VA.gov and incorporate those terms into the product.
    - E.g. Multiple users mentioned searching for burial and cemetery information and urgent care. Top terms could be surfaced in the page description.
    - Related issue: #27702 
- [ ]  Start experimenting with structured content for location addresses and hours to see how changes could positively affect search engine search results. 
    - Start with one small change to track and learn from
      - consider incorporating experiment into Vet Center pages where we have more research, control and editor involvement
- [ ]  Investigate how structured health data (or other subtypes) reconciles with current health taxonomy
    - Start with one small change to track and learn from
      - If a VA has ER care with 24/7 availability could be a data point be updated to conform to [google structured data]

**Comment by mmiddaugh** [comment]
Product decision: The Facilities themselves need to be optimized, not the Facility Locator. 

Documented in the [Solution Narrative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/solution-narrative/solution-narrative.md)
