### ISSUE TITLE
[UI] Check-in Enhancement Wireframes

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27765]
# Description
- As a Veteran, I wanted to be able to check-in if I have more than one appointment in a day. 
- I also want to feel that check-in is secure. 
- Lastly, I would like to know if I already checked in, but accidentally start the process over again.

## Tasks
- [x] Work with the team to figure out the requirements to the above items in the description. For instance, what exact data are we adding to the auth/identification workflow for security purposes? Is it DOB, last 4 of SSN, last name?
- [x] Update Sketch workflow to include the above scenarios mentioned in the description.
- [x] Review with content

## Acceptance Criteria
- [x] Review with team and UX manager

**Comment by kristenmcconnell** [comment]
[Initial draft wireframes](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/p/E43B7C08-1833-47F8-BC65-44918261F037) that I will review with Corey tomorrow.

**Comment by kristenmcconnell** [comment]
Met with Corey this morning to go over requirements/questions to prep for the whole team meeting later this week. 

I updated the "happy path" wireframes as a result: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/DP9D30k/play.

I also created a [user flow diagram](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=uc940f53ad96ac0203d6d3631) to help describe some of our options/items still to be determined as well as error states.

I'm going to sync with Julia on the error states tomorrow, because VeText is syncing on them today. I'm interested to hear what comes out of their meeting.

@jparker0425 
- Review the user flow diagram is you have time. I plan to use that for the discussion later this week. I will update it after my error message discussion with Julia. 
- I also thought more about the radio button versus card display on the "Your appointments" page. We moved away from radio buttons on the contact information page, since this is a mobile first workflow. The bigger buttons give more clickable area. Therefore, I think we should follow suite here as well.
- I am also debating what appointment statuses we need to display on the "Your appointments" page. 

All statuses possible: 
1. Appt time <30 minutes in future and <10 minutes in past
2. Appt time >30 minutes in future
3. Appt time >10 minutes in past
4. Appt already checked in

- My current thinking is to only show the check-in statuses that the user will be able to still take action on at some point that day, so status 1 and 2. Do you have any thoughts on the "Need help?" text covering status 3 & 4?

**Comment by kristenmcconnell** [comment]
After talking with Julia, I'm exploring ways to show all statuses on the "your appointments" page. More error states related to multiple appointments were also added to the user flow.

**Comment by jparker0425** [comment]
@kristenmcconnell Thanks for the quick turnaround on these, drafts look great. I had thought about the radio button, the main reason I had suggested those originally is so we could limit the ability to check into only one. The big button format stays consistent with what we have now and I like that, just will need to make sure if there are two appointments that overlap in check-in time, only one can be chosen.

**Comment by kristenmcconnell** [comment]
The [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=uc940f53ad96ac0203d6d3631) has been updated with feedback from Kennon. We added reminder SMSs that will be pushed to the Veterans after they attempt to check in at least once for the day. This will cover multiple use cases, such as the Veteran attempted to log in too early. We will then push an SMS message to them when their appointment(s) is finally eligible to check-in. 

The [interactive Sketch prototype](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/DP9D30k/play) is complete.

At this point, the wireframes need to be reviewed with content. There are also outstanding questions that need to be discussed with engineering.

**Comment by kristenmcconnell** [comment]
Content feedback received and incorporated into Sketch, Mural, and UX Pin prototype.

**Comment by kristenmcconnell** [comment]
Went to VPS Office Hours. All of their feedback has been entered into the Mural document. Will quickly incorporate some of their findings into the designs. Some of the feedback requires some investigation, so it may not be incorporated until later.

**Comment by kristenmcconnell** [comment]
Met with Julia to review VSP Office Hours feedback. Updated wireframes. Still to be dealt with feedback shown as stickie notes in the Mural. I will create another ticket for that.
