### ISSUE TITLE
[UI] Check-in Posters Available on GitHUB

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27766]
# Description
As a member of the check-in team, I want easy access to the latest Check-in posters (so I can send them to sites, etc.).

# Tasks
- [x] Create GitHUB page for poster files.
- [x] Add PDFs to the page.
- [x] Create a .zip file for others with all the source files, then upload it to GitHUB.

## Acceptance Criteria
- [x] Message the team to let them know the GitHUB page is finished.

**Comment by kristenmcconnell** [comment]
Location on GitHUB: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md

**Comment by kristenmcconnell** [comment]
Let the team know on [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1627661267003300).
