### ISSUE TITLE
[Research] Martinsburg and Charleston Discovery Research

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27764]
# Description
Talk with Charleston and Martinsburg staff members who are part of the check-in to understand their current processes and help plan for pilot.

# Tasks
- [x] Meet with Charleston 
- [x] Meet with Martinsburg staff (Document all findings)

# Acceptance Criteria
- [x] Finalize notes and post to Slack/GitHub

**Comment by kristenmcconnell** [comment]
[Rough notes on GitHUB](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/group-interviews/session-notes/martinsburg.md)
