### ISSUE TITLE
Remove v0 references from vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#27772]
## Issue Description
As SSOe has been set to 100% we want to deprecate and remove all `v0` session callbacks.

---
## Tasks
- [x] Remove all `v0` references in the vets-website repo
- [x] Remove any helpers not related to `v1` sessions

## Acceptance Criteria
- [x] Ensure only `v1` sessions are being called by default
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
