### ISSUE TITLE
Update TUD Accounts with test accounts in va.gov-team-sensitive

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#27775]
## Issue Description
The va.gov-team-sensitive repo has many guides to finding specific test user accounts for individual va.gov features; these guides list appropriate test accounts by their unique email. Most of the accounts listed are not currently present in the Test User Dashboard; these accounts should be reviewed to make sure that they are still relevant/useful and either add them to the TUD database or remove them from the va.gov-team-sensitive repo. In addition there are several accounts that are referenced throughout individual guides that are not present in the [master list of test users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv), the master list should be updated with these accounts.

---
## Tasks
- [x] Compile a list of test accounts that appear in test account guides in `va.gov-team-sensitive` but are not present in the TUD app.
- [x] Determine the current status of the listed accounts
- [ ] Update the TUD database with approved accounts
- [ ] Remove stale/no longer useful accounts from the test account guides
- [x] Update the master list of test users to contain all currently active test accounts

## Acceptance Criteria
- [ ] Every known "vets.gov.user+XXX@gmail.com" account that is specifically referenced in a guide in `va.gov-team-sensitive` repo is present in the TUD application
- [x] Every known "vets.gov.user+XXX@gmail.com" account listed in the `va.gov-team-sensitive` repo is present in the master list of accounts

**Comment by bramleyjl** [comment]
First Draft of test accounts found on va.gov-team-sensitive:
(Entries preceded by `**` are already present in the TUD dashboard)
```
Missing from mvi-staging-users.csv (master list of staging credentials)
----------------------------------
vets.gov.user+277@gmail.com
vets.gov.user+278@gmail.com
vets.gov.user+279@gmail.com
vets.gov.user+377@gmail.com
vets.gov.user+378@gmail.com

vets.gov.user+501@gmail.com
vets.gov.user+502@gmail.com
vets.gov.user+503@gmail.com
vets.gov.user+504@gmail.com
vets.gov.user+505@gmail.com
vets.gov.user+506@gmail.com
vets.gov.user+507@gmail.com
vets.gov.user+508@gmail.com
vets.gov.user+509@gmail.com
vets.gov.user+510@gmail.com
vets.gov.user+511@gmail.com
vets.gov.user+512@gmail.com
vets.gov.user+513@gmail.com
vets.gov.user+514@gmail.com
vets.gov.user+515@gmail.com
vets.gov.user+516@gmail.com
vets.gov.user+517@gmail.com

- Dependency Claims (info from 686-test-users.md) - should this be added?
	vets.gov.user+EBN1@gmail.com
	vets.gov.user+EBN2@gmail.com
	vets.gov.user+EBN3@gmail.com
	vets.gov.user+EBN4@gmail.com
	vets.gov.user+EBN5@gmail.com

Accounts referenced in individual va.gov-team-sensitive pages
----------------------------------
- vets.gov.user@gmail.com (generic 'Zm9ydHkgdHdv' password doesn't work)
	Recovery phone number (714) 595-3281 (Alastair Dawson)
	Recovery email vsp-team.group@adhocteam.us
	
- "Special Traits"
	Fiduciary: vets.gov.user+26@gmail.com
	Deceased: vets.gov.user33@gmail.com
	Incompetent: vets.gov.user+61@gmail.com
	Fiduciary: vets.gov.user+65@gmail.com
	
- 2FA
	vets.gov.user+242@gmail
	
- Disability Claims
	- Working - Staging accounts with Birls id, participant id, and edipi
	vets.gov.user+38@gmail.com
	vets.gov.user+54@gmail.com
	vets.gov.user+90@gmail.com
	
	- LOA3 veteran with many claims:
	vets.gov.user+100@gmail.com
	vets.gov.user+101@gmail.com
	vets.gov.user+102@gmail.com
	vets.gov.user+201@gmail.com 
	vets.gov.user+205@gmail.com
	vets.gov.user+202@gmail.com
	vets.gov.user+229@gmail.com
	
	- Throw ID Error
	vets.gov.user+1@gmail.com
	vets.gov.user+32@gmail.com
	vets.gov.user+42@gmail.com
	** vets.gov.user+228@gmail.com
	
- Direct Deposit
	vets.gov.user+378@gmail.com
	** vets.gov.user+226@gmail.com
	vets.gov.user+204@gmail.com
	vets.gov.user+175@gmail.com
	
- Health Care Status
	- Users with a health care status
	vets.gov.user+360@gmail.com – Enrolled
	vets.gov.user+361@gmail.com – Deceased
	vets.gov.user+362@gmail.com – Canceled or declined health care
	vets.gov.user+363@gmail.com – Enrolled
	vets.gov.user+364@gmail.com – Canceled or declined health care
	vets.gov.user+365@gmail.com – Update: We need more information
	vets.gov.user+366@gmail.com – Canceled or declined health care
	vets.gov.user+367@gmail.com – Update: We're reviewing your application
	vets.gov.user+368@gmail.com – Update: We're reviewing your application (Unrelated: Also sees health chat prompt)
	vets.gov.user+369@gmail.com – Decision: We determined that you don’t qualify for VA health care
	vets.gov.user+370@gmail.com – Update: We need more information
	vets.gov.user+371@gmail.com – Enrolled
	vets.gov.user+372@gmail.com – Enrolled
	vets.gov.user+373@gmail.com – Update: We need more information
	vets.gov.user+374@gmail.com – Deceased
	vets.gov.user+375@gmail.com – User no longer works
	
	- Users not enrolled in health care (so you can see the health care application)
	vets.gov.user+271@gmail.com
	vets.gov.user+272@gmail.com
	vets.gov.user+273@gmail.com
	vets.gov.user+274@gmail.com
	vets.gov.user+275@gmail.com
	vets.gov.user+276@gmail.com
	vets.gov.user+280@gmail.com
	vets.gov.user+281@gmail.com
	vets.gov.user+282@gmail.com
	vets.gov.user+283@gmail.com
	vets.gov.user+284@gmail.com
	vets.gov.user+285@gmail.com
	vets.gov.user+286@gmail.com
	vets.gov.user+287@gmail.com
	vets.gov.user+287@gmail.com
	
- Education Benefits
	** vets.gov.user+220@gmail.com
	** vets.gov.user+226@gmail.com
	** vets.gov.user+228@gmail.com
	
- GI Benefits
	** vets.gov.user+0@gmail.com
	** vets.gov.user+3@gmail.com
	vets.gov.user+27@gmail.com
	** vets.gov.user+228@gmail.com
	vets.gov.user+229@gmail.com
	vets.gov.user+264@gmail.com
	vets.gov.user+501@gmail.com
	vets.gov.user+502@gmail.com
	vets.gov.user+504@gmail.com
	vets.gov.user+505@gmail.com
	vets.gov.user+506@gmail.com
	vets.gov.user+507@gmail.com
	vets.gov.user+508@gmail.com
	
- Benefit Letters
	** vets.gov.user+1@gmail.com
	vets.gov.user+14@gmail.com
	vets.gov.user+32@gmail.com
	** vets.gov.user+228@gmail.com
	vets.gov.user+264@gmail.com
	vets.gov.user+272@gmail.com
	vets.gov.user+273@gmail.com
	vets.gov.user+274@gmail.com
	vets.gov.user+275@gmail.com
	vets.gov.user+276@gmail.com
	vets.gov.user+277@gmail.com
	vets.gov.user+278@gmail.com
	vets.gov.user+279@gmail.com

- Appeals
	vets.gov.user+11@gmail.com
	vets.gov.user+38@gmail.com
	vets.gov.user+42@gmail.com
	vets.gov.user+54@gmail.com
	vets.gov.user+73@gmail.com
	vets.gov.user+90@gmail.com
	** vets.gov.user+226@gmail.com
	** vets.gov.user+228@gmail.com
	vets.gov.user+264@gmail.com
	vets.gov.user+265@gmail.com
	vets.gov.user+503@gmail.com
	vets.gov.user+504@gmail.com
	vets.gov.user+505@gmail.com
	vets.gov.user+506@gmail.com
	vets.gov.user+507@gmail.com
	vets.gov.user+508@gmail.com
	vets.gov.user+509@gmail.com
	vets.gov.user+510@gmail.com
	vets.gov.user+511@gmail.com
	vets.gov.user+512@gmail.com
	vets.gov.user+513@gmail.com
	vets.gov.user+514@gmail.com
	vets.gov.user+515@gmail.com
	vets.gov.user+516@gmail.com
	vets.gov.user+517@gmail.com

	- no appeals found:
		["vets.gov.user+0@gmail.com", "vets.gov.user+110@gmail.com", "vets.gov.user+121@gmail.com", "vets.gov.user+127@gmail.com", "vets.gov.user+129@gmail.com", "vets.gov.user+13@gmail.com", "vets.gov.user+15@gmail.com", "vets.gov.user+16@gmail.com", "vets.gov.user+17@gmail.com", "vets.gov.user+189@gmail.com", "vets.gov.user+200@gmail.com", "vets.gov.user+220@gmail.com", "vets.gov.user+224@gmail.com", "vets.gov.user+227@gmail.com", "vets.gov.user+22@gmail.com", "vets.gov.user+233@gmail.com", "vets.gov.user+241@gmail.com", "vets.gov.user+24@gmail.com", "vets.gov.user+250@gmail.com", "vets.gov.user+25@gmail.com", "vets.gov.user+271@gmail.com", "vets.gov.user+273@gmail.com", "vets.gov.user+276@gmail.com", "vets.gov.user+32@gmail.com", "vets.gov.user+41@gmail.com", "vets.gov.user+45@gmail.com", "vets.gov.user+46@gmail.com", "vets.gov.user+47@gmail.com", "vets.gov.user+4@gmail.com", "vets.gov.user+50@gmail.com", "vets.gov.user+61@gmail.com", "vets.gov.user+64@gmail.com", "vets.gov.user+66@gmail.com", "vets.gov.user+75@gmail.com", "vets.gov.user+79@gmail.com", "vets.gov.user+82@gmail.com", "vets.gov.user+90@gmail.com", "vets.gov.user+94@gmail.com", "vets.gov.user+96@gmail.com", "vets.gov.user+99@gmail.com"]

	- not found in appeals:
		["vets.gov.user+0@gmail.com", "vets.gov.user+110@gmail.com", "vets.gov.user+114@gmail.com", "vets.gov.user+117@gmail.com", "vets.gov.user+121@gmail.com", "vets.gov.user+127@gmail.com", "vets.gov.user+129@gmail.com", "vets.gov.user+13@gmail.com", "vets.gov.user+15@gmail.com", "vets.gov.user+16@gmail.com", "vets.gov.user+17@gmail.com", "vets.gov.user+189@gmail.com", "vets.gov.user+200@gmail.com", "vets.gov.user+220@gmail.com", "vets.gov.user+224@gmail.com", "vets.gov.user+227@gmail.com", "vets.gov.user+22@gmail.com", "vets.gov.user+233@gmail.com", "vets.gov.user+241@gmail.com", "vets.gov.user+24@gmail.com", "vets.gov.user+250@gmail.com", "vets.gov.user+25@gmail.com", "vets.gov.user+271@gmail.com", "vets.gov.user+273@gmail.com", "vets.gov.user+275@gmail.com", "vets.gov.user+276@gmail.com", "vets.gov.user+281@gmail.com", "vets.gov.user+282@gmail.com", "vets.gov.user+283@gmail.com", "vets.gov.user+284@gmail.com", "vets.gov.user+294@gmail.com", "vets.gov.user+296@gmail.com", "vets.gov.user+32@gmail.com", "vets.gov.user+374@gmail.com", "vets.gov.user+41@gmail.com", "vets.gov.user+45@gmail.com", "vets.gov.user+46@gmail.com", "vets.gov.user+47@gmail.com", "vets.gov.user+4@gmail.com", "vets.gov.user+50@gmail.com", "vets.gov.user+61@gmail.com", "vets.gov.user+64@gmail.com", "vets.gov.user+66@gmail.com", "vets.gov.user+75@gmail.com", "vets.gov.user+79@gmail.com", "vets.gov.user+82@gmail.com", "vets.gov.user+90@gmail.com", "vets.gov.user+94@gmail.com", "vets.gov.user+96@gmail.com", "vets.gov.user+99@gmail.com"]

- My VA
	vets.gov.user+41@gmail.com
	vets.gov.user+377@gmail.com
	
- Change Address
	vets.gov.user+32@gmail.com
	** vets.gov.user+228@gmail.com
	vets.gov.user+264@gmail.com
	
- Prescriptions
	vets.gov.user+28@gmail.com
	vets.gov.user+32@gmail.com
	vets.gov.user+41@gmail.com
	vets.gov.user+50@gmail.com
	vets.gov.user+85@gmail.com
	vets.gov.user+89@gmail.com
	** vets.gov.user+220@gmail.com
	vets.gov.user+225@gmail.com
	** vets.gov.user+226@gmail.com
	** vets.gov.user+228@gmail.com
	vets.gov.user+229@gmail.com
	vets.gov.user+264@gmail.com
	
- Secure Messaging
	** vets.gov.user+1@gmail.com
	** vets.gov.user+8@gmail.com
	vets.gov.user+41@gmail.com
	vets.gov.user+50@gmail.com
	vets.gov.user+89@gmail.com
	vets.gov.user+225@gmail.com
	** vets.gov.user+226@gmail.com
	** vets.gov.user+228@gmail.com
	vets.gov.user+229@gmail.com
	vets.gov.user+264@gmail.com	

- Specific VHA Facilities
	vets.gov.user+37@gmail.com
```

**Comment by bramleyjl** [comment]
I was able to track down the passwords, or rather the default `Zm9ydXXXX` password for some of the accounts not present in mvi-staging-users.csv and updated it accordingly, but there are still roughly a dozen "vets.gov.user+XXX@gmail.com" accounts unaccounted for as well as some eBenefits ones that I'm still trying to find creds for.

**Comment by pjhill** [comment]
It looks like this block --

> vets.gov.user+509@gmail.com
vets.gov.user+510@gmail.com
vets.gov.user+511@gmail.com
vets.gov.user+512@gmail.com
vets.gov.user+513@gmail.com
vets.gov.user+514@gmail.com
vets.gov.user+515@gmail.com
vets.gov.user+516@gmail.com
vets.gov.user+517@gmail.com

might actually be a reference to @id.me accounts with similar numbers instead.  Those account details and relevant passwords are available [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-appeals.md).

**Comment by AGarcia-Clarity** [comment]
Health Care status will be added.

**Comment by bramleyjl** [comment]
@pjhill I think you're right about those @id.me accounts, I'll get them added to the master list as well

**Comment by bramleyjl** [comment]
@pjhill & @JoeTice, I spoke with @jason-gcio about moving the credential information into the main list for the following eBenefits test accounts:
```
	vets.gov.user+EBN1@gmail.com
	vets.gov.user+EBN2@gmail.com
	vets.gov.user+EBN3@gmail.com
	vets.gov.user+EBN4@gmail.com
	vets.gov.user+EBN5@gmail.com
```
These accounts are specifically set up for the eBenefits team to use and as such have some unique attributes; his concern is that adding their credentials to the main list might lead to others using them and altering how they work. How do you feel about keeping them separate for the time being, or at least adding a notice that they should be reserved for the eBenefits team?

**Comment by bramleyjl** [comment]
The `va.gov-team-sensitive` `mvi_staging_users.csv` (main list of all test user credentials) has been updated (pending the official TUD release) to include all known ID.me-proofed accounts. Adding additional accounts to the TUD application or removing their recommendation for specific services is at the discretion of the Testing team and any requests for additions/removals can be documented in further tickets.
