### ISSUE TITLE
Alert Manager mobile_claim latency alert threshold low

### ISSUE THREAD

**Issue by Teesh** [department-of-veterans-affairs/va.gov-team#27776]
## Description
Tune latency threshold of mobile_claim as it is generally higher than other endpoints and ends ip firing off the AlertManager when not necessary

## Background/context/resources
Alert and Grafana chart pics for context:
![Screen Shot 2021-07-22 at 5.54.08 PM.png](https://images.zenhubusercontent.com/608716c8425a91126d5ff063/1bb2cb0b-5a43-44c8-959a-7a284e4cbc30)![Screen Shot 2021-07-22 at 5.55.21 PM.png](https://images.zenhubusercontent.com/608716c8425a91126d5ff063/fd0ce4e1-2f5e-4b37-9ac8-ae31a056d9f0)

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Tune threshold for mobile_claim latency in Prometheus/AlertManager

## Definition of Done
- [ ] AlertManager does not fire unless outside expected latency range

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic
