### ISSUE TITLE
[UI] Notifying Veterans of Time Period to Check-in

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#27784]
# Description
For the MVP, Veterans will have a timeframe around the appointment time where they are actually able to check-in. We need to notify Veterans of this timeframe. More information can be found in t[his Slack Thread](https://dsva.slack.com/archives/C022AC2STBM/p1626987675250000).

## Tasks
- [x] Clarify the technical requirements. How are we setting up the time period?
- [x] Think through where Veterans need to be notified, SMS (and poster?)
- [x] Write a draft error message (and updated poster?)
- [x] Review the error state with Danielle

## Acceptance Criteria
- [x] Send final error wording to Check-in and VeText teams

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Thoughts on this error message wording (will be an SMS) if the Veteran checks in earlier than allowed...

**If we can display the time...**
You can check-in 30 minutes before your 9:00 a.m. appointment. Try again later.

**If we can't display the time...**
We see you have an appointment today. You can check-in 30 minutes before your appointment. Try again later.

_I also messaged you in Slack._

**Comment by kristenmcconnell** [comment]
Should it be "You can check-in no more than [X] minutes..."

**Comment by kristenmcconnell** [comment]
Final wording determined in [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1627066338278400?thread_ts=1626987675.250000&cid=C022AC2STBM),

We see you have an appointment today. You can check in up to [X] minutes before your appointment. Try again later.

cc @Kennon-git and @snyderje for visibility

Also determined in the above Slack thread, we are not going to complete any poster updates at this time.
