### ISSUE TITLE
Fix broken link to form on Request your military service records page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27794]
## Issue Description
We have a broken link to form SF 180 on the [Request your military service records](https://www.va.gov/records/get-military-service-records/) page, which needs to be fixed. 

## Tasks
- [x] Update link on broken page
- [x] Review and publish

## Acceptance Criteria
- [x] Link on live site working

**Comment by RLHecht** [comment]
Work completed. Closing ticket.
