### ISSUE TITLE
Product Success Tool - Iterate to include Phased Rollout Metrics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2779]
## Problem Statement 
VFS teams need an easy way to understand if they are hitting or not hitting metric goals that are vital to release so that they can either continue rolling out to more users or go back and fix something. 

HMW automate metrics that VFS teams need to safely launch so that they can easily see if each phase of their rollout is successful or if they need to pause their launch and go back to fix something?

## Hypothesis or Bet
If we automate phased rollout metrics in Domo then we expect VFS teams to have an easier way of tracking their rollout criteria.

## We will know we're done when... ("Definition of Done")
- [x] We understand if these dashboards should be separate from or in addition to Product KPI dashboards
If they are separate...
- [x] We understand which data sources we'll most likely need to connect for these types of dashboards, and what it will take to 
- [ ] We have an internal design template for what "phased rollout" dashboards might look like
- [ ] We have an MVP for a phased rollout dashboard if it's separate from Product KPI dashboards
- [ ] We have a clear process for requesting a phased rollout dashboard
- [ ] We have a clear internal process for creating phased rollouts dashboards

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: KPI Dashboards
* **[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/kpi-dashboard/kpi-dashboard-product-outline.md)**
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **[Success metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/kpi-dashboard/kpi-dashboard-product-outline.md#kpis)**
* **Release plan**: N/A - pivoting to iterating on KPI Dashboarding & Performance Dashboarding

**Comment by joanneesteban** [comment]
Results from discussions & [user feedback](https://app.optimalworkshop.com/a/adhoc/questions/results/db7588ec-a3e7-4cb5-a500-c4608a2ffbd7#/t/results/analysisTools/questions). 

VFS teams should be using the same KPI and website performance data that we're providing for KPI dashboard and that we're working on retrieving for website performance dashboards. 
- Having separate dashboards just for rollouts can be a confusing user experience. 
- Most of the technical work for rollout dashboarding will roll up into the Performance Dashboards and KPI dashboards
- Dashboards during rollouts may have more point in time charting (i.e. number or pie chart in addition to line graphs), and may need an hour-by-hour or daily view as opposed to the more traditional weekly view that the KPI dashboards have.
- There are opportunities to improve rollout analytics through performance dashboarding and improving KPI dashboard resources.

**Comment by joanneesteban** [comment]
**Initiative to pivot on iterating on KPI dashboarding and Performance Dashboarding.** 
- These products should have the data that we expect VFS teams to use during rollouts. 
- These products may be iterated to be updated daily or hourly _during_ rollouts.
- Additional visuals may be added to these products to clearly tell rollout stories.
