### ISSUE TITLE
[PM, Design] Notification Preferences: Update call center doc and submit for review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27805]
## Background
We need to update the call center documentation for notification preferences and submit it for review.

## Tasks
- [x] Update [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Call%20Center/VA.Profile.-.Product.Guide.v3_030121.pdf)
- [x] Review it internally
- [x] Submit for review with call center

**Comment by andaleliz** [comment]
@ajakabcin can you pleas add a link to the documentation that needs to be updated?  That'll help me provide an accurate estimate. Thanks!

**Comment by ajakabcin** [comment]
@andaleliz updated!

**Comment by andaleliz** [comment]
I also just realized this is assigned to both of us; how are we splitting up this work?  Do you just need me to provide screenshots?

We'll need to update this for the changes to remove functionality too. Not sure what the LOE is to submit this to the CC and get this reviewed, but we might want to do it all at one time if it's hard to get their attention.

**Comment by ajakabcin** [comment]
Yes definitely agree to do it all at once. 

I think a good way to tackle this together could be to create a list of what sections/features need to be updated or added, divide and conquer on making those changes and then review each others' updates. What do you think?

**Comment by andaleliz** [comment]
That sounds like an awesome plan. I'm working on getting access to the OG google doc; I think that'll make collaboration a lot easier. If we can get access, we can use comments to identify what needs to be changed and added.

**Comment by andaleliz** [comment]
[Here's a link to the google doc](https://docs.google.com/document/d/1XNHpYOP73so_bnnEjplx_zG_ybGarGenG2V0E6-N-CA/edit#heading=h.4pw5uak8tqf7). I'm not sure If more updates were made after it was transferred to `.docx` and `.pdf`.

**Comment by andaleliz** [comment]
@ajakabcin FYI I went through all the sections of the google doc and left comments about parts that need to be updated. I'm fairly certain it corresponds with everything I've updated since joining the team that makes sense to include in this doc (e.g. I don't think the FAQ update I made needs to be in this guide).

**Comment by ajakabcin** [comment]
Review complete and submitted to VEO

**Comment by ajakabcin** [comment]
Final version attache
[VA.Profile.-.Product.Guide.v4_102021_srt (1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7455306/VA.Profile.-.Product.Guide.v4_102021_srt.1.docx)
d
