### ISSUE TITLE
Meta tag description for Vet Center Location page from Facilities Team

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27812]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[x] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[ ] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?

Currently, if you search for one of the recently released Vet Center pages, you get the following results
![image](https://user-images.githubusercontent.com/55411834/126844149-ddc334f8-69fb-422c-bfc4-23d72b5fd9f6.png)

We will be using the established pattern for meta tags and descriptions using H1 | (facility name) | Veterans Affairs and intro text for the description. However, we removed the intro text from the Vet Center Locations page as it was redundant and the original placement caused navigation confusion for screen reader users. We'd like input on the best description for this page. 

You can view Colorado Springs Vet Center for a sample [Locations page](https://www.va.gov/colorado-springs-vet-center/locations/). 

We're thinking about something like....

> The Colorado Springs Vet Center offers all of its counseling, outreach and support services at the main location. Other satellite locations may be located near you.

We've considered adding the number of satellite locations (if technically reasonable)
 

## When does this content work need to be done?

- We will be correcting the other meta tags and description during our sprint which begins July 28. 
- 6 of 10 MVP locations have gone live. 
- District 5 has 70+ sites and is now training and creating content with a due date of August 20th for conten

t completion. 

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [x] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Michelle Middaugh
-	Designer: Leyda Hughes and Nick Osmanski
-	FE engineer: Michael Pelz-Sherman and Gaida Escobar
-	Product/team Slack channel: vsa-facilities

## Links to related tickets

Vet Center Meta tags #27648

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
@mnorthuis @shiragoodman @peggygannon for awareness

**Comment by RLHecht** [comment]
@mmiddaugh would you be able to come to office hours next week to work through the  new text with @bethpottsVADEPO and @DanielleThierryUSDSVA?

**Comment by mmiddaugh** [comment]
Get contact information for and directions to our main Colorado Springs Vet Center and other satellite locations. We offer all services at our main location and some services at satellite locations.

**Comment by RLHecht** [comment]
@mmiddaugh  Do you need anything else from us or can we close this?

**Comment by RLHecht** [comment]
Closing this out. @mmiddaugh please reopen if there's more work you need us to do. Thanks!
