### ISSUE TITLE
Lo-fi wireframes/designs for CLC VAMC page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27810]
## Issue Description
Following interviews with SMEs for Community Living Center facilities, we need to revisit the VAMC facility page experience and determine the best way to display accurate and relevant information

---

## Tasks
- [ ] Based on synthesis findings, determine the most relevant and meaningful information to present to Veterans, including the following
       - how is the facility best described?
       - how is the location best described?
       - what services are provided?
       - what does the Veteran need to know to consider or prepare for a visit? 
       - What might caregivers or families need to know about visiting?
       - What do Veterans need to know about the referral process or eligibility criteria? 
- [ ] Create lo-fi wireframes/designs to deliver this information, in line with VAMC facility page style/components 

## Acceptance Criteria
- [ ]  lo-fi design(s)/wireframe(s) representing Community Living Center facility information 

Link to [initial lofi suggestions](https://app.mural.co/t/vaadhoc1321/m/vaadhoc1321/1626443115766/c7cd6759fcfac13269e363dee26fe7d188537eab?wid=0-1628699886813) in Mural - Nick O

**Comment by nicko-amida** [comment]
Link to initial [lofi suggestions](https://app.mural.co/t/vaadhoc1321/m/vaadhoc1321/1626443115766/c7cd6759fcfac13269e363dee26fe7d188537eab?wid=0-1628699886813) in Mural

**Comment by nicko-amida** [comment]
Updated with initial lofi clc page suggestions.
