### ISSUE TITLE
[DISCOVERY] Online scheduling for mental health and primary care

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27813]
## Issue description
As a Veteran, I want to know when a facility has services available for online scheduling so that I can schedule an appointment at my convenience without having to call the VA. 

## Background
Meeting with VAOS team, we learned that the "is online scheduling" (yes/no) toggle is not connected to the system of record for the information and therefore can be misleading. We also learning that the availability of online scheduling is not the same for every facility, every service or every Veteran. 

VA Primary Care and VA Mental health will soon be required to have online scheduling "clinics" (scheduling grids) -> midAugust. This makes them the easiest POC options.

**Community care primary care and community care mental health services are out of scope.** 

Current understanding: 
- primary care will require an active PACT at the facility
- mental health will likely be more open
- both will likely require the Veteran to be registered for care at the facility

---
From Jeff Balboni during meeting on 7/26:

- Endpoint: /vaos/v2/scheduling/configurations
- [Direct VAMF url](https://veteran.apps.va.gov/facilities/v2/scheduling/configurations?facilityIds=552) (rather than VAOS pass through)
- Some [example data](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/services/mocks/v2/scheduling_configurations.json)
   - Basically, you provide a facility id and you get back a list of services with the settings for each. There’s a direct block and a request block, each of which have an enabled field, which is the main thing to look at.
   - There are also patientHistoryRequired and patientHistoryDuration and submittedRequestLimit that tell you what conditions are set up for that facility and service.

## Tasks
Determine who owns the data and what is needed to get the data to answer the following
- [ ] which facilities allow online scheduling for primary care
- [ ] what are the rules for online scheduling of primary care
- [ ] which facilities allow online scheduling for mental health
- [ ] what are the rules for online scheduling of mental health

## Acceptance Criteria
- [ ] Informed for discussion with Dave
