### ISSUE TITLE
Consolidate Facility Locators

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2782]
## This ticket will serve as the Epic for the various issues documenting facility locators which will be considered for consolidation into the modernized Facility Locator over time. 

Linking relevant items and closing individual issues: 

- [ ] decide how to add PTSD information to vets.gov FL #2735 
- [ ] add caregiver/help near home as a service to our FL #2765
- [ ] Add surgery as a service to the FL  #2766 
- [ ] Complementary Integrative Health Service #2773 
- [ ] Discovery on adding VSOs #2777 
- [ ] Decide how to add SUD info to Vets.gov FL #2867 
- [ ] Add surgery as a service to the FL #2869 
- [ ] how can we add this information to FL [parkinsons] #2872 
- [ ] add chiropractic service to FL #2873
- [ ] amputation system of care locations added to our FL #2875 
- [ ] add transportation as a service to FL #2876
- [ ] Outpatient Medical Surgery Care service#2879 
- [ ] decide how to add PTSD information to Facility Locator #2881 
- [ ] FL: Explore adding same day service #2974 
- [ ] Facility Locator: State Veterans Cemetery Information #3658 
- [ ] war related illness and injury center locator add to our FL #2730

**Comment by mmiddaugh** [comment]
Per [10995](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10995)
 'VA Home Loan Help' locations are apparently pulled into Facility Locator as regional offices
