### ISSUE TITLE
[VAMC] Prepare Central Ohio-health-care for Dual-state VISN-10 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27825]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Tugboat](https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed
**Facilities incldud:**
- [x] 757	Chalmers P. Wylie Veterans Outpatient Clinic
- [x] 757GA	Zanesville VA Clinic
- [x] 757GB	Grove City VA Clinic
- [x] 757GC	Marion VA Clinic
- [x] 757GD	Daniel L. Kinnard VA Clinic

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system

**Comment by ltrombley** [comment]
Task #27825 - Prepare Central Ohio-health-care for Dual-state VISN-10 [VAMC] - is Complete and moved to Validate.
