### ISSUE TITLE
[FE] Update Questionnaire JSON location to include missing states

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#27829]
## Description
Update the json schema for locations to include Puerto Rico and Virgin Islands. 

## Related Docs'
- [ Slack Message](https://dsva.slack.com/archives/C5HP4GN3F/p1626381203367600)

## Tasks
- [ ] Update JSON to include the changes
- [ ] move to have this only in one place

## Acceptance criteria 

- [ ] Changes merged into master
