### ISSUE TITLE
[VAMC] Prepare Indiana-health-care for Dual-state VISN-10 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27834]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Tugboat](https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed
**Tugboat Actions**
- [x] Rebuild and refresh Tugboat instance of System
- [x]  Publish all nodes for specific system
- [x]  Release content (Report any issues in release)
- [x]  View logs and resolve any broken links
**Facilities include:**
- [x] 583	Richard L. Roudebush Veterans' Administration Medical Center
- [x] 6463	Crane VA Outreach Clinic
- [x] 6483	Patient Response Center
- [x] 6505	Crane VA Clinic
- [x] 583GA	Terre Haute VA Clinic
- [x] 583GC	Martinsville VA Clinic
- [x] 583GD	Indianapolis West VA Clinic
- [x] 583GE	West Lafayette VA Clinic
- [x] 583GF	Wakeman VA Clinic
- [x] 583GG	Shelbyville VA Clinic
- [x] 583QA	Monroe County VA Clinic
- [x] 583QB	Indianapolis VA Clinic
- [x] 583QC	Vigo County VA Clinic
- [x] 583QD	Indianapolis YMCA VA Clinic

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system

**Comment by ltrombley** [comment]
Task #27834 - Prepare Indiana-health-care for Dual-state VISN-10 [VAMC] - is Complete Pending resolution of URL alias issue - moved to BLOCKED
