### ISSUE TITLE
CHIP - Set up SAM template

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27837]
A SAM (Serverless Application Model) template is infrastructure as code. it provisions aws resources, deploys λ code and their dependencies. 

Carl has been working on a SAM template for LoROTA - that’s done, for CHIP we need to review & modify to fit CHIP’s needs. 

**Task is done when:** 

- [x] The SAM template is set up to create CHIP resources in AWS 
- [x] Code is deployed in Dev
- [x] Code is deployed in Staging
- [x] Code is deployed in Prod
- [x] VPCs linked to each of the above

**Comment by kjduensing** [comment]
I used the environment names:

NONPROD <=> DEV
PREPROD <=> STAGING
PROD <=> PROD
