### ISSUE TITLE
LoROTA - Set up Github actions pipeline

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27849]
We need to set this up in order to automate tasks within the development lifecycle. 

**Tasks**
- [x] Request service account for lorota 
- [x] Set roles and policies
- [x] Get AWS access keys
- [x] Set up trigger
- [x] Implement actions on github

**Task is done when**
We can trigger the SAM template form github

We can ignore tests for now - LoROTA has integration but no unit tests currently.

**Comment by kjduensing** [comment]
VAEC support folks got back. Asked for justification and more info: https://dsva.slack.com/archives/C022AC2STBM/p1628087493067300?thread_ts=1627586827.417400&cid=C022AC2STBM

**Comment by calquisola** [comment]
github workflow has been setup and tested earlier and failed. 

CMS-service-account-1 needs additional S3 Policies

**Comment by calquisola** [comment]
S3 policy issues were resolved. However, we need our CMS service account to have admin access, it can't create an application stack right now.

**Comment by kjduensing** [comment]
Progress made on the service account front - CHIP is now getting the same error we were seeing, but for cloudformation:CreateChangeSet . I updated the ticket with that info. Also, the support person only added the getTemplateSummary permission for a single stack, so I updated the ticket with all our stacks.

**Comment by kjduensing** [comment]
Here's the ticket: https://wfm.vaec.va.gov/servicedesk/customer/portal/2/VAEC-16826

**Comment by calquisola** [comment]
had a successful deployment today, but i had to exclude the cleanup lambda. Had no isssues, deploying metrics and dashboard.  I followed up on the AWS ticket.

**Comment by calquisola** [comment]
i got the CI/CD running. Event bridge permissions were added today.
