### ISSUE TITLE
CHIP - Set up Github actions pipeline

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27848]
We need to set this up in order to automate tasks within the development lifecycle. 

**Tasks**
- [x] Request service account for chip
- [x] Set roles and policies
- [x] Get AWS access keys
- [ ] Set up trigger
- [ ] Implement actions on github

**Task is done when**
We can trigger the SAM template form github

We can ignore tests for now - Chip has unit tests but not integration tests currently.

**Comment by kjduensing** [comment]
Meeting with Filip who offered to help walk us through what we need to put in the ticket.

**Comment by kjduensing** [comment]
Need System Owner and System ISSO to make ticket. The problem is the checkin experience doesn't have an ATO yet.

3 options:
1. Get an ATO (being worked on)
2. Use VEText ATO
3. Use vets-api & va.gov ATO

**Comment by kjduensing** [comment]
Ticket requested: https://wfm.vaec.va.gov/servicedesk/customer/portal/2/VAEC-16826

Patrick approved - waiting to see if we put the right information.

**Comment by kjduensing** [comment]
Ticket requested: https://wfm.vaec.va.gov/servicedesk/customer/portal/2/VAEC-16826

Patrick approved - waiting to see if we put the right information.

**Comment by kjduensing** [comment]
Ticket submitted for LoROTA since Carl is farther along in GH Actions pipeline. Waiting to see if information is correct before submitting ticket for CHIP.

**Comment by kjduensing** [comment]
Access Key is created!

Patrick is the owner of the key, so I've asked him to test it out when he gets a minute.

To clarify - I only provided the justification for the access key, not the additional ATO info. They created the key before I could respond with that info (or lack thereof)

**Comment by kjduensing** [comment]
Patrick was able to create an access key for us. We've set this in the LoROTA repo's secrets manager (Github secrets). 

CHIP and LoROTA will share an access key for now, but we may want to revisit that in the future.

**Comment by kjduensing** [comment]
This is blocked waiting for support

**Comment by kjduensing** [comment]
getting this error:

`
Error: Failed to create/update the stack: chipPreprod, An error occurred (AccessDenied) when calling the GetTemplateSummary operation: User: arn:aws-us-gov:iam::***:user/CMS-service-account-1 is not authorized to perform: cloudformation:GetTemplateSummary on resource: arn:aws-us-gov:cloudformation:us-gov-west-1:***:stack/chipPreprod/821de6d0-f390-11eb-a271-02139adad328
`

**Comment by kjduensing** [comment]
Progress made on the service account front - CHIP is now getting the same error we were seeing, but for cloudformation:CreateChangeSet . I updated the ticket with that info. Also, the support person only added the getTemplateSummary permission for a single stack, so I updated the ticket with all our stacks.

**Comment by kjduensing** [comment]
More progress made - got past all the cloudwatch permissions hangups. Now dealing with creating specific resources (lambda). Asked for lambda permissions.

**Comment by aschulhof** [comment]
Closing as duplicate to https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/51
