### ISSUE TITLE
CHIP - Implement deploying to tiered environments

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27851]
This should work closely with how we're implementing LoROTA to tiered environments. 

Along with implementing - need to answer the following questions: 

- [ ] We need to determine our deploy strategy - Do we deploy to Dev / Demo / Prod or single branch?
- [ ] What are best practices?
- [ ]  update github actions pipeline to reflect decisions above

**Task is done when:**
CHIP API is available in dev / staging / prod

**Comment by aschulhof** [comment]
Outdated
