### ISSUE TITLE
Home Page Banner Updates (Short Term Actions)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27852]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page-banner/product-outline.md)

## High Level User Story/ies
OPIA can publish on VA.gov homepage-only via an update to a yaml file with an HTML snippet on GitHub. This file is then PR'ed by a front end engineer on Public Websites, merged by platform after review and then deployed with hourly content builds. If the file needs to be pushed into production more immediately or during off-hours (evenings, weekends), the process requires Platform approval for an out-of-band deployment and a full content build (a process that can take up to one hour)

## Hypothesis or Bet
If we create a more robust, systematic approach to enabling HP banner alerts then we will reduce the litany of high profile risks (availability, timeliness, content errors) which exist now.

## Definition of done
For Short Term Solution (Goal: Put in place by Sept. 1)

- [ ] Set meeting with Platform for collaboration on improving communication, response, redundancy and speed to publish issues/gaps.
- [ ] Create tickets for solutioning

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by FranECross** [comment]
Closing old, obsolete ticket.
