### ISSUE TITLE
LoROTA - Implement deploying to tiered environments

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27850]
This should work closely with how we're implementing CHIP to tiered environments. 

Along with implementing - need to answer the following questions: 

- [ ] We need to determine our deploy strategy - Do we deploy to Dev / Demo / Prod or single branch?
- [ ] What are best practices?
- [ ]  update github actions pipeline to reflect decisions above

**Task is done when:**
LoROTA API is available in dev / staging / prod

**Comment by calquisola** [comment]
Once we got the GA pipline working. We can set it up to be deployed to different environments.
