### ISSUE TITLE
Review and publish noncompensable disabilities R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27853]
## Issue Description
The R&S article on noncompensable disabilities has been reviewed and approved by stakeholders and is now ready to be published. We need to do a final copyedit before publishing the page.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=26921

## Tasks
- [x] Copyedit article (Randi)
- [x] Complete pre-publishing checklist (Randi)
- [x] Publish article (Randi)
- [x] Add article to R&S landing page (Randi)

## Acceptance Criteria
- [x] New article published on live site

**Comment by RLHecht** [comment]
This article is published. Moving to validate and will close after the next deployment.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
