### ISSUE TITLE
[QA] vaos service integration FE Staging testing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27865]
## Summary
Request for frontend testing for the vaos service integration work in Staging to identify any bugs prior to launch.

### VA.gov Feature Toggle
`va_online_scheduling_facilities_service_v2`
- Toggle enabled in Staging for all test users
Affected areas:
- Showing appropriate facility contact information on appointment list and detail pages
- Getting and displaying the list of parent sites available for community care
- Checking that at least one parent site is enabled for CC in VATS data
- Displaying correct list of facilities, based on their VATS settings, on the facility page in the new appointment flow
- Any other facility contact information displayed in new appointment flow

`va_online_scheduling_vaos_service_requests`
- Toggle enabled in Staging for the Jacqueline Morgan test user

`va_online_scheduling_vaos_service_va_appointments`
- Toggle enabled in Staging for the Jacqueline Morgan test user

`va_online_scheduling_vaos_service_cc_appointments`
- Toggle enabled in Staging for the Jacqueline Morgan test user

### Designs & Copy
Service work only. No design or copy assets to reference.

## Tasks
- Run Mobile and Desktop tests
- Attach spreadsheet(s) of test cases
- Document bugs in GitHub using the [VAOS Bug Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=laurenernest&labels=bug%2C+vaos&template=vaos-bug.md&title=) and attach to this epic
- Document questions that arise in this ticket

### Ready for testing
- [ ] Facilities endpoint
- [ ] Create Community Care request
- [ ] View Community Care request
- [ ] Cancel Community Care request
- [ ] View VA request
- [ ] View booked VA appointment
- [ ] Cancel VA request

### Not ready for testing/Unknown
- [ ] View booked Community Care appointment
- [ ] Create VA request
- [ ] Create VA self schedule appointment
- [ ] Cancel VA appointment

**Comment by JRRoof** [comment]
VAOS Service v2 deployed in production on December 14, 2022.
