### ISSUE TITLE
Automate "Nearby Vet Centers"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27870]
## Issue Description

As A Veteran, I want to know what other Vet Center facilities might be closer to me so that I can visit the one which is the most convenient. 

## Background: 

Vet Centers cover a catchment area. If you are a Veteran living at an edge of a catchment area, the closest location might actually be a satellite location of another Vet Center. 

For example: If I am a Veteran living southwest of Cincinnati, my closest Vet Center could be in Kentucky (especially if they have a satellite location on that side of their area. 

Currently, field staff at Vet Centers designate which locations should be displayed as "Nearby Vet Centers" but many are listing only the ones they are familiar with or none at all.
 
<details>
<summary > screenshot of current page </summary>

![image](https://user-images.githubusercontent.com/55411834/132061396-fe1a2cff-8950-4de2-88b4-2b5c9a4aa8f5.png)

</details>

---
If a Vet Center has not entered any nearby locations, the section header will not display. This functionality should be maintained. 

<details>
<summary> Screenshot of San Luis Obispo, which has no nearby locations entered. </summary>

![image](https://user-images.githubusercontent.com/55411834/132379219-eac1be26-d781-4c49-a9ac-043126b9b393.png)

</details>

 ---

How might we automate this list?
(One idea: select Vet Centers/outstations within 80 miles? radius from the facilities API and remove the ones that are already posted in the local/satellite. And then show the first five sorted by distance.) 

## Dev Notes
- Consider a future state which might set the default of 80 allowing a radius to be changed by the local editor

---
## Tasks
- [x] Ping API for Vet Centers and outstations within 80 miles
- [x] Exclude locations already listed as Satellite or associated locations
- [x] Return the closest locations, up to 5
- [x] Order by distance
- [ ] Add tests
- [x] Add a feature flag to support testing in staging

## Acceptance Criteria
- [x] Up to 5 nearby Vet Center locations will be displayed, in ascending order
- [x] If the VC’s specified in Drupal aren’t included in the Lighthouse search, we will not display them
- [x] In the case where there are no locations at that radius, do not show the header
- [ ] Do not generate empty `<img>` tags for vet centers fetched from Lighthouse.

**Comment by mpelzsherman** [comment]
Note: the current behavior uses Drupal data which may contain both published and unpublished Vet Centers.

The published centers appear first, followed by unpublished. This behavior occurs in both preview mode and on the published site in production (e.g. on https://www.va.gov/escanaba-vet-center/locations/, the Green Bay Vet Center is still in Draft state, but appears under Nearby Vet Centers).

With this new, automated approach, only vet centers that are in Lighthouse will appear, even in preview mode. So there may be some discrepancies introduced with this change. Just wanted to provide a heads up!

**Comment by mpelzsherman** [comment]
@mmiddaugh There is no image data in Lighthouse, so the nearby vet centers will not have images.

**Comment by mpelzsherman** [comment]
I'm seeing some discrepancies between the operating status data in Lighthouse vs. CMS. For example, Green Bay Vet Center has operatingStatus "NORMAL", but "Limited Hours" in Drupal.

**Comment by swirtSJW** [comment]
I am not seeing the disconnect.   CMS and facility locator show the same status.
![image](https://user-images.githubusercontent.com/5752113/133468300-5ee4c932-55c6-41ee-b8f0-dadbead5b4ca.png)

**Comment by mpelzsherman** [comment]
Correct, sorry. I guess the discrepancy only exists on dev.

**Comment by mmiddaugh** [comment]
@mpelzsherman [Nashville Vet Center's Location page ](https://www.va.gov/nashville-vet-center/locations/) lists its own outstation as a "Nearby" Vet Center

**Comment by mpelzsherman** [comment]
That's a prod link, and we haven't turned on the feature in prod yet.

The Clarksville outstation is listed under both Satellite and Nearby in prod:

https://prod.cms.va.gov/nashville-vet-center/locations

![Locations___Nashville_Vet_Center___Veterans_Affairs](https://user-images.githubusercontent.com/80267/134196745-437d2d5f-0f80-4abf-843b-728cb37c1c0a.png)

**Comment by mmiddaugh** [comment]
Thank you - my bad. I'll continue to validate in Staging.
