### ISSUE TITLE
[Tech-Debt] Update LGBTQ+ and Suicide pages with new updates from SOT VISN-16 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27899]
## User Story
As a VHA Digital Media web manager, the national changes need to be implemented prior to Dual state or full production launches, so the systems are updated adequetly prior to the redirect.

## Goal
Remove tech-debt prior to full production

## Resources - Tools - Documentation
TBD

## Tasks
UPdate LGBT with LGBTQ and Suicide pages with new content and organize page correctly.
- [x] Update Suicide pages with correct format order and new content
- [x] Change out LGBT with newly authorized LGBTQ+ in locations provided by Content.
_
**Complete for the following locations**
- [x] VA Alexandria health care
- [x] VA Central Arkansas health care
- [x] VA Fayetteville Arkansas health care
- [x] VA Gulf Coast health care
- [x] VA Houston health care
- [x] VA Jackson health care
- [x] VA Shreveport health care
- [x] VA Southeast Louisiana health care

## Acceptance Criteria
- [x] Suicide pages are updated and if caregiver is not listed on page it is reported in Support channel.
- [x] LGBTQ+ pages are updated and if caregiver is not listed on page it is reported in Support channel.

**Comment by bcastoe** [comment]
#27899 - [Tech-Debt] Update LGBTQ+ and Suicide pages with new updates from SOT VISN-16 [BA] - Completed and moved to Validate.  (1) Suicide Detail pages updated as System and Facilities already created (2) LGBTQ+ Detail, System and Facility pages updated (3) looked for Staff Profile dups and there were none.
