### ISSUE TITLE
Consolidate API tags in GTM

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#27897]
We have several API call tags in GTM that should be consolidated into the `EV - API Calls` tags.  These can be found by searching for "API" in the name or "retrieved" in the trigger event.

- VAOS - Number of Items Retrieved Event
- Claims API Called
- Chatbot API Events
- Profile Connected Apps - API Calls
- Profile Saved - API Calls

## Tasks

- [x] Find all API tags
- [x] Add their triggers to the `EV - API Calls` tag
- [x] Add the event actions to the `RegEx - API Calls - Event Action Lookup` variable
- [x] Test!

**Comment by laurensimpson14** [comment]
I created a new GTM container for this: [27897 - Consolidate API Tags](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000551)

## QA:
|API Call| Screenshot | Status|
| -- | -- | -- |
|`Profile Direct Deposit Retrieves or Failures - API Calls` ▶️ `EV - API Calls` | ![image](https://user-images.githubusercontent.com/80417436/128367006-6a12f653-2978-4e63-a047-2ed10ceb62f3.png)| 🟢 Tracking Correctly|
| `Profile Saved - API Calls` ▶️ `EV - API Calls` | | |
| `Chatbot API Events` ▶️ `EV - API Calls` | | |
| `Claims API Called` ▶️ `EV - API Calls` | | |
| `Profile Connected Apps - API Calls` ▶️ `EV - API Calls` | | |
| `VAOS - Number of Items Retrieved Event` ▶️ `EV - API Calls` | | |
| `View Payment History - API Calls` ▶️ `EV - API Calls` | | |

**Comment by bsmartin-ep** [comment]
LGTM @laurensimpson14 - will publish Monday 8/23.

**Comment by bsmartin-ep** [comment]
Tested and published.
