### ISSUE TITLE
HLR Page Refresh Design Review

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27907]
## Issue Description
_Review HLR page to see which items require design_

---
## Tasks
- [x] Document page refresh items that need page design & then prioritize. Write new tickets

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
needs design = ✅
doesn't need design (probably) = ❌
needs more deliberation = 🤨

- Add ‘I am Homeless’ flag ✅
- Remove Service Number field ❌
- Changed Claimant fields (shouldn’t need to do anything here since we dont’ support non-Veteran Claimants) 🤨
- Remove Same Office selection ❌
- Update Informal Conference fields ❌
- Change Rep Name format ✅
- Explicitly take in Rep phone# and email ✅
- Change time window selection ❌
- Add SOC/SSOC Date field per Issue (only if opting in to AMA) - this will likely be tied to the new Legacy Issues endpoint we are going to build. ✅
- Start sending in Veteran Contact Info (same as NOD) ✅
- Support write-in Issues (same as NOD) ✅

@Mottie let me know if you think this needs a-changin' at all. Thanks!

**Comment by Mottie** [comment]
Some notes I had:

- Homelesss question is required (according to the Lighthouse schema)
- Address doesn't support addressed outside the U.S. and it isn't required?! see https://dsva.slack.com/archives/CSKKUL36K/p1627671609001600
- Conference times
  - The new times are "800-1200 ET" and "1200-1630 ET", and also aren't required?!
  - Since we're down to 2 options, maybe we can switch this back to checkboxes?
- The representative phone number accepts an extension. This might be a nice addition.

**Comment by Mottie** [comment]
On Friday, Lighthouse said that the SOC/SSOC opt-in was required, but didn't have to be checked to allow submission. So it might be better to use a yes/no radio selection here instead of a checkbox.
