### ISSUE TITLE
[MCP] Add medical copay wizard resolution pathways

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27918]
## Issue Description
_Prior to launching the medical copay enhancement tool, we need to add terminals to [the existing wizard](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction) to guide Veterans towards payment options and financial help information._

### Updated wizard flow

[Access the wizard mapping document here for the content for each terminal]
(https://governmentcio.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/VHA%20Debt%20Letters%20Improvement/MCP%20Wizard%20Mapping.docx?d=w7a11b7a85cc3410f84134bdb15f0cf40&csf=1&web=1&e=DYYjYn)

{Updated link:https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B8B3A764A-D917-4EAA-BEF7-3C25C44D8654%7D&file=MCP%20Wizard%20Mapping.docx&action=default&mobileredirect=true}

**Note:** A1-A10 are the new terminals being added

![vha wizard flow.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/e46716e5-a764-4d3e-9d15-1a1cde880757)

---
## Tasks
- [ ] Define paths for wizard 
- [ ] Draft content for each path using existing documentation  (Riley's doc, Danielle's Doc, and Benefit Path)
- [ ] Review with sitewide content

## Acceptance Criteria
- [ ] Pathways have been defined and reviewed by sitewide content

**Comment by denisecoveyduc** [comment]
Blocked: Need SMEs to help with terminology.

**Comment by denisecoveyduc** [comment]
We have added a temporary path to include medical copays and updated the description. We plan to meet with Sitewide content on Oct 26th to iron out the various pathways and changes needed for the wizard going forward.

**Comment by denisecoveyduc** [comment]
[https://app.zenhub.com/files/133843125/a571c8a5-7961-46c2-93c6-a932f35c0106/download](https://app.zenhub.com/files/133843125/a571c8a5-7961-46c2-93c6-a932f35c0106/download)

**Comment by denisecoveyduc** [comment]
Unless @mgleo or @josephrlee see any reason to keep this ticket I think we can close this ticket out. The intent of this ticket is to add copays into the wizard experience and that will be done once we reengage discussions with CAIA.
