### ISSUE TITLE
[MCP - Usability recommendation] Rework the charges and payments table on the copay balance details page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27927]
## Issue Description
_Usability uncovered that Veterans found the charges and payments table to be overwhelming and cluttered._

### Findings

- Simplify table data to be more scannable. Potential solutions:
   - Condense descriptions
   - Reduce labels
   - Minimize data columns on mobile / make transaction details interactive
- List the balance amount and due date closer to the table / support the 'running tally' mental model 
- Non-usability recommendation: Incorporate preliminary sort + filter functionality to test more goal-centric tasks with Veterans. 

---
## Tasks
- [x] _Ideate ways to simplify the table according to the outlined usability findings_
- [x] _Validate the new design with frontend engineers + design leadership as needed_

## Acceptance Criteria
- [ ] _UXPin with the proposed design has been linked to this ticket_
- [ ] _A ticket for frontend implementation has been linked to this ticket_

**Comment by rebeccawalsh** [comment]
**Update on work:**
We nailed down the design of the table itself and have simplified it by removing the 'billing number' and conforming to the base styles of the table component. We'll work with this simplified design for the sake of engineering complexity until further testing can be done to determine if Veterans require more columns in the table or still find the mobile view to be 'jumbled.'

Now we're focusing on the content of the 'description' column. We're trying to find a SME so we emailed Pamela Gunderson, who sent us the [original document](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B14624512-596C-43FB-A6ED-3EC1DF09268B%7D&file=vha-spreadsheets.xlsx&action=default&mobileredirect=true) with highlighted AR categories for line items on a copay statement. By connecting with an SME, we want to:
- Ensure that we understand each of the categories
- Find which categories have additional information (e.g. 'Drug / Qty / Phys' for prescription)

If we're able to nail this information down for all of the highlighted categories, we can create 'designs' for each of the charge types.

**Comment by rebeccawalsh** [comment]
We met with Pamela Gunderson and she provided a lot of context for all of the different AR codes she sent over [(rough notes were taken in the document)](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B14624512-596C-43FB-A6ED-3EC1DF09268B%7D&file=vha-spreadsheets.xlsx&action=default&mobileredirect=true). She wasn't sure about a few of them and wants the CPAC group to review what she gave us, so we're working on putting together [mocks for the different line item types](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140826035/simulate/no-panels) to facilitate that conversation (WIP). 

@LindaLi123 Our next step is to schedule a conversation/workshop with the CPAC individuals who would have systems understanding of these veteran patient statement line items and how all of them are represented on the statements. We are **not** ready to send the mockups above to them, but we should be ready to show them Monday afternoon or later. Can you work with Justin to identify which folks would be right for this workshop?

**Comment by LindaLi123** [comment]
@rebeccawalsh Hello Becca, would you please confirm if we were able to cover this on Monday or if you still need another meeting?

**Comment by rebeccawalsh** [comment]
@LindaLi123 This information was not the focus of the meetings yesterday. We talked about Wizard and broader data fields. We requested sample data from each of the AR codes, which Mike McDougall said was going to be a lot of work for him to curate. Mike was not able to answer specific questions about line items during the meeting.

I think the intended audience for this conversation is meant to be Sergio Falcon, David Adcock, and someone named Mark who we couldn't get a last name for.
