### ISSUE TITLE
[MCP - Usability recommendation] Investigate the problem of transaction dates vs. the expectation of visit dates

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27929]
## Issue Description
_Usability uncovered that Veterans expect the date listed in the charges + payments table to relate to visit dates rather than transaction dates._

We're currently displaying transaction dates in the table because it can take an extended period of time after a visit for the charge to be sent as a statement to the Veteran. We need to discover if it makes sense to list charges by visit date, and if not how to make the table more understandable for Veterans.

---
## Tasks
- [x] _Deduce the validity of displaying visit dates rather than transaction dates_
- [ ] _If we proceed with displaying visit dates, confirm with Liberty team that we have access to that data_

## Acceptance Criteria
- [ ] _Documentation is written about whether or not we should proceed with displaying transaction dates vs visit dates_

**Comment by rebeccawalsh** [comment]
To solve this problem, we:
- Changed 'date' to 'charge date', **and**
- Proposed to include visit dates appended to the end of line items (e.g. 'Inpatient copay for July 3, 2021')

Example:
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/70b882b0-750a-4f6d-b3c6-94080feec115)

We did these rather than change the date column to visit date due to logical chronological sorting. For example, a Veteran can have nursing home charges from May, but not be actually billed for them until much later. If we sorted based on visit date, those charges could appear buried under more recent charges.

**Comment by rileyorr** [comment]
Reached out to the Liberty team to confirm that we have access to both transaction dates and appointment dates. Moving this over to blocked while we wait for a response!

**Comment by rileyorr** [comment]
I remembered that the Liberty team is also consuming the same data we are and aren't SMEs on the data fields, so I reviewed [the mock API data](https://yf7yvyucfj.execute-api.us-gov-west-1.amazonaws.com/Prod/swagger/index.html) we have access to and noticed these date fields:

`"pS_STATEMENT_DATE": "string",`
 `"pS_STATEMENT_DATE_Output": "string",`
`"pS_PROCESS_DATE": "string",`
`"pS_PROCESS_DATE_Output": "string",` 

Under `details` there's more date fields: 
`"pD_DATE_POSTED": "string",`
`"pD_DATE_POSTED_Output": "string"`

@LindaLi123 & @leahkeeler do we have a SME identified who can help us make sense of the data fields we're receiving? If not, maybe this is something Justin Carver can help us with!

**Comment by LindaLi123** [comment]
@rileyorr did you already reach out to liberty team for these exact data fields and confirmed they have no answer?  If that is the case let's reach out to Justin.

**Comment by rileyorr** [comment]
Hi @LindaLi123! Our conversation with Michael and Ray proved unfruitful for identifying the difference between the date fields. Additionally, it seems as though appointment dates are being returned as part of the 

Becca and I were facilitating these discussions due to not having a backend engineer available last week, but now that we have backend resources on our team again it would be great if we could get backend support on this front. Dillo is more equipped to understand the data and facilitate these discussions. 

[I've added a ticket related to this work to the backlog.](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/28500)

**Comment by rileyorr** [comment]
@LindaLi123 Michael and Ray told us that Sergio Falcon, David Miskolczi, and Mark (it's unclear what his last name is) may be able to help answer data questions. We can certainly appeal to the larger group tomorrow to see if those are the appropriate people and if anyone else thinks they could assist us.
