### ISSUE TITLE
Determine if Manage VA debt should be linked to from Decision Reviews hub landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27928]
## Issue Description
We have added related links on several pages to the Manage VA Debt page in ticket #21099. We need to discuss with SMEs whether we should add it to the more information and resources section of the Decision Reviews hub landing page. If so, we can use the same language that is used in the other related links teasers.

## Tasks
- [x] Reach out to SMEs to ask if manage VA debt should go on decision reviews page
- [x] Add teaser text and link to page if needed
- [ ] Review and publish page if needed

## Acceptance Criteria
- [ ]

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Is this something we should try to do in our last 2 sprints or keep in the backlog?

**Comment by DanielleThierryUSDSVA** [comment]
I think we could do either, @RLHecht. Either way, it's going to link to the same url for the Manage your VA debt page, right? I don't have a strong opinion on this, but seems like we could just add now and close the ticket.

**Comment by RLHecht** [comment]
That makes sense, @DanielleThierryUSDSVA I added this as the last link in the helpful resources section. Can you take a look and I'll publish if all is good? I used the same language that we have on the change direct deposit page. preview-prod.vfs.va.gov/preview?nodeId=3071

**Comment by bethpottsVADEPO** [comment]
@DanielleThierryUSDSVA FYI this Manage debt link/teaser is going to publish today on the decision reviews landing page along with another addition I'm making in this last "More information" section.

**Comment by bethpottsVADEPO** [comment]
Closing this ticket. The new link and teaser are appearing on the DR landing page.
