### ISSUE TITLE
[MCP - Usability recommendation] Include clarifying content that prescription bills are included in the tool

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27939]
## Issue Description
_Usability uncovered that some Veterans weren't aware that prescription bills were included in the tool._

---
## Tasks
- [x] _Update the tool's content page to reflect that prescription bills can be viewed in the tool_
- [x] _Work with the sitewide content team on this work as needed_

## Acceptance Criteria
- [x] _The content page has been updated and the UXPin has been linked in this ticket_

**Comment by rebeccawalsh** [comment]
During our testing, we found that some participants weren't sure if both procedure/visit charges and prescription charges fell under the umbrella of 'copays' - they weren't sure if they'd find prescriptions in our tool. 

**We did two things to mediate this:**

- Improved the sign in alert on the content page to ensure prescription charges were specifically mentioned, and
- Changed the subtitle on the copayment summary page:
    - From: Check your VA health care copay balances. Find out how to make payments or request financial help."
    - To: "Check your VA health care and prescription charges from each of your facilities. Find out how to make payments or request financial help."

These changes have been sent for review by content [in this ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27780) and we are pending approval before closing!

**Comment by rileyorr** [comment]
@LindaLi123 due to the amount of content we've changed this sprint, I requested a full content review of the entire prototype. I think we're good to close this out. I'll just open another ticket when Danielle's review is complete so we can incorporate her updates!
