### ISSUE TITLE
[MCP - Usability recommendation] Provide clarity around amount due and resolution options

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27935]
## Issue Description
_Usability uncovered that Veterans were unsure what amount was due by their balance's due date. Additionally, it wasn't clear what resolution pathways were available if they couldn't pay the full amount_

---
## Tasks
- [x] _Provide clarifying content that the full balance is due by the due date_
- [x] _Emphasize the resolution pathways available in context of the balance due_

## Acceptance Criteria
- [x] _The UXPin has been updated and linked to this ticket_
- [ ] _A ticket for frontend implementation has been linked to this ticket_

**Comment by rebeccawalsh** [comment]
This work is partially done... so far, we've:

- Changed language and structure of the 'Next Steps' to be more clear what amount is due: ![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/6708f514-3db3-45f3-af1c-68aea8d94b03)
- Reordered the detail pages to emphasize resolution options earlier on the page.

We'll return to this work on Monday to improve the resolution options section of the page to be more clear about what sort of help they can get.

**Comment by rileyorr** [comment]
We've been playing around with a couple concepts for emphasizing the different resolution options, which can be viewed in [this UXPin prototype](https://preview.uxpin.com/58722552e65e2da8b5a9ce2bd6c2eb2bbe5e5ecd#/pages//simulate/no-panels?mode=i). Our next step is to get both design + content feedback on which option we should proceed with. We're in the process of reaching out to both teams.

**Comment by rileyorr** [comment]
We've presented the accordion designs to both the design leadership team and the sitewide content team; looks like we are good to proceed with the design! 

Danielle will likely give feedback on the titles of the accordions and the body content, but we should be good to close this out.
