### ISSUE TITLE
[MCP - Usability recommendation] Provide more information in the referred charges alert

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27938]
## Issue Description
_Usability uncovered that Veterans wanted to know what charges were referred for collection. Additionally, we want to provide a non-phone contact method if applicable as well as information Veterans will need to provide when contacting Treasury._

---
## Tasks
- [x] _Discover if we have access to the charges that are referred to Treasury and if it can be added to the payload if not_
- [x] _Discovery if there's a non-phone contact method and incorporate that content into the alert_
- [x] _Add information about what Veterans should have on-hand when contacting about their referred charges_

## Acceptance Criteria
- [x] _The alert has been updated in UXPin and linked in this ticket_
- [ ] _If accessing the referred charges involved backend work, add a ticket and link it to this ticket_

**Comment by rebeccawalsh** [comment]
# Demand Letter

**Our records indicate that you owe the U.S. Government $XX.XX.**
The [agency], referred your unpaid debt to the U.S. Department of the Treasury, Bureau of the Fiscal Service, for immediate collection. You must immediately pay your debt to stop collection action and prevent the addition of more interest, penalties, and administrative costs.

## Data points
- Referring agency (?)
- Debt amount
- Treasury case number
- Agency debt number

## Payment Options
- **Pay online:** "Pay online: Visit www.pay.gov/paygov/paymydebt and follow the instructions online."
- **Pay by phone:** "Pay By Phone: Call (888)826-3127 and provide our agent your debit card information. You may also discuss payment with representatives at this number if you are unable to satisfy the debt immediately."
- **Pay By Mail:** "Pay By Mail: Mail your payment and completed payment coupon to the address below. If you pay by check, include the Treasury Case Number [#] in the memo section of your check"

## Nonpayment
**What if I do not pay my debt?**
"As allowed by federal law, we may withhold some or all monies from your tax refunds and other federal and state payments. We may garnish your wages, refer your unpaid debt to a collection agency and report your debt to the credit bureaus, which could hurt your credit score. You will find further information online at www.fiscal.treasury.gov/debt"

## Payment Coupon
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/dcbd3a8b-9953-4633-9cdb-e539a822e881)

# TOP warning and offset letter

This is the letter that a Veteran receives after nonpayment that informs them that their federal or state payments are being reduced to pay their debt. **Unsure if this letter is relevant since all debts are sent through cross servicing rather than TOP.**

# Treasury Letter PDFs
- [Demand Letter](https://app.zenhub.com/files/133843125/76b646d8-66c4-4e5f-82c8-97c28123d1ea/download)
- [TOP warning and offset letter](https://app.zenhub.com/files/133843125/ec753612-f8c2-43ca-95e8-a8803da7bee9/download)

# Questions:
- Does the 'demand letter' precede the 'TOP warning and offset letter'? 
  - After how long?
  - Are these letters still relevant since all debts are sent through cross servicing rather than TOP?

**Comment by rebeccawalsh** [comment]
The Liberty team has been emailed on Aug 5 to determine if the VISTA information for referred debts can be passed to us and what that data looks like. We're awaiting a response from them, but creating optimistic design concepts in the meantime.

**Comment by rebeccawalsh** [comment]
The Liberty team responded to direct us to the data dictionary and sample api data, but we weren't able to interpret it well. It doesn't appear that the Treasury referral data is going to be sent over to us, so we may cut this feature from the MVP. We will discuss this with BE when they return on Monday, and we could potentially talk to the Liberty team Tuesday at the technical meeting (Confirm, @leahkeeler or @LindaLi123?) 

For the sake of this ticket, we will create our designs as planned to help facilitate getting our hands on the data and planning future work.

**Comment by LindaLi123** [comment]
Hey @rebeccawalsh I reached out to Justin Carver to find some SMEs to interpret data for us,  lets see when we can get them, mean while i think we can definitely ask the Liberty team on our Tuesday's technical meeting.

**Comment by rebeccawalsh** [comment]
## What we learned: 
- Treasury referral data is **NOT** being passed to us currently with the API that the Liberty team provided. This data is not currently available on statements, so we will need to grab it from another data source that includes broader Vista data. Mike McDougall says that this is something that they have interacted with in the past.
- Phone is the only **contact** method we could find, but there are non-phone **payment** methods:
    - Pay online: "Pay online: Visit www.pay.gov/paygov/paymydebt and follow the instructions online."
    - Pay by phone: "Pay By Phone: Call (888)826-3127 and provide our agent your debit card information. You may also discuss payment with representatives at this number if you are unable to satisfy the debt immediately."
    - Pay By Mail: "Pay By Mail: Mail your payment and completed payment coupon to the address below. If you pay by check, include the Treasury Case Number [#] in the memo section of your check"
- It's unclear what Veterans should have on hand when contacting Treasury about their referred charges, however, we have learned that the Treasury folks do not discuss debt details, "People in the Treasury Offset Program (TOP) cannot discuss your debt with you, refund your money, or discuss payment arrangements with you. Only the agency to which you owe the money can do that." It appears that calls to TOP will result in payment or direction back to the referring agency (VA).

## Next Steps
- Remove referrals from the initial release / MVP scope, as there is no data to inform it. (This has been completed in the [UXPin here](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140669280/specification/sitemap?mode=i))
- Speak with Mike McDougall / Liberty team about connecting to other Vista data in order to support this feature. (@LindaLi123 @leahkeeler)
- Create a ticket for further referral discovery with VA and Treasury SMEs in order to inform a broader design.
