### ISSUE TITLE
va-text-input: placeholder property

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27936]
## Description

The `<va-text-input>` includes a `placeholder` prop to set the [input's `placeholder` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefplaceholder).

To ensure designers & developers follow best practices, the `placeholder` property for this web component should be removed.

Related:
- https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research
- https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/

## Tasks

- [x] Meet with design system council for discussion & feedback
- [ ] Remove `placeholder` property or close this ticket based on recommendations

## Definition of done

- [ ] Decision made on use of placeholders
- [ ] Tasks completed

**Comment by k80bowman** [comment]
Discussed with the DSC on 1.28.22. Decision was to move forward with removing the placeholder property from the `va-text-input` component.

@bkjohnson also noted that we should also make sure that if any team is using this component with that property, they should be notified.

**Comment by bkjohnson** [comment]
Here are the only two places where `<va-text-input>` is being used in `vets-website` at the moment:

https://github.com/department-of-veterans-affairs/vets-website/blob/7ed95c8e593886f5514b5d744dd7b21bdf7ec215/src/applications/check-in/components/pages/validate/ValidateDisplay.jsx#L20-L41

They aren't using the `placeholder` prop, so we shouldn't have anything blocking the change.
