### ISSUE TITLE
Medallia Bottom of Main Feedback Button

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#27934]
## Issue Description
To assist in the resolution of outstanding 508 launch blocking issues, the Medallia Feedback button needs transitioned to the bottom of the main section of pages.

---
## Tasks
- [x] Design an iteration of the current Medallia feedback button to fit at the bottom of the main content
- [x] Collaborate with appropriate FE members to implement design
- [x] Work with Sarkis to embed code necessary to launch Medallia feedback modal window

## Acceptance Criteria
- [x] Button has been designed
- [x] Button has been approved by the appropriate team members
- [x] Button has been built
- [x] Button launches feedback modal window
- [x] All launch-blocking 508 issues are addressed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Mural with desktop & mobile designs](https://design.va.gov/documentation/contributing-to-the-design-system)

Will eventually need to [suggest a component](https://design.va.gov/documentation/contributing-to-the-design-system)

Have designs out to Ryan T at the moment, waiting to hear back.

Already had discussions with folks during design office hours & collab cycle office hours which lead to tweaks to get to this proposed design.

**Comment by aubreyarcangel** [comment]
After connecting with Sarkis, Medallia tech lead, it was confirmed the Medallia setup would change from Always-On Button, to Embed in Page survey.

Inventory of non react page layouts that use the back to top button
```
src/site/layouts/checklist.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/media_list_images.drupal.liquid
src/site/layouts/media_list_videos.drupal.liquid
src/site/layouts/page.drupal.liquid
src/site/layouts/q_a.drupal.liquid
src/site/layouts/step_by_step.drupal.liquid
src/site/layouts/support_resources_article_listing.drupal.liquid
src/site/layouts/support_resources_detail_page.drupal.liquid
src/site/layouts/vet_center_locations_list.drupal.liquid
src/site/layouts/vet_center.drupal.liquid  inventory of non react pages that use last updated component
 src/site/layouts/checklist.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/media_list_images.drupal.liquid
src/site/layouts/media_list_videos.drupal.liquid
src/site/layouts/q_a.drupal.liquid
src/site/layouts/step_by_step.drupal.liquid
src/site/layouts/support_resources_detail_page.drupal.liquid
src/site/layouts/vamc_system_billing_insurance.drupal.liquid
src/site/layouts/vamc_system_medical_records_offi.drupal.liquid
src/site/layouts/vamc_system_policies_page.drupal.liquid
src/site/layouts/vamc_system_register_for_care.drupal.liquid
```

Inventory of non react page layouts that need to be updated with new last updated component:

```
src/site/facilities/health_care_region_detail_content.drupal.liquid
src/site/layouts/basic_landing_page.drupal.liquid
src/site/layouts/event.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/landing_page.drupal.liquid
src/site/layouts/page.drupal.liquid
src/site/layouts/person_profile.drupal.liquid
src/site/layouts/va_form.drupal.liquid
```

Because the new design changes the Medallia implementation, it also moves the logic of managing where the Medallia feedback button shows on specific urls from within Medallia, to the website teams.   On Drupal pages, we can add a new Drupal entity for each page to show the button conditionally
```feedbackButton: true```

**Comment by aubreyarcangel** [comment]
Throwing this info here for reference:

Medallia Intercept survey shows up on va.gov/ORMDI(Teamsite pages) production URLs only. 

There are two different surveys

Staging 
Survey #20 which shows up on `/search` only
Survey # 11 which shows on all other urls

Production
Survey #21 which shows up on `/search` only
Survey # 17 which shows on all other urls

**Comment by jwoodman5** [comment]
Successfully launched!
