### ISSUE TITLE
va-text-input: include more properties

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27945]
## Description

The input rendered by this component could include more properties to give more control over the rendered input. The following list of properties should be discussed for inclusion:

- [`disabled`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-disabled) - some inputs may need to be dynamically disabled?
- [`inputmode`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-inputmode) - control which virtual keyboard is displayed on mobile devices

## Tasks

- [ ] Discuss addition of each of the above properties
- [ ] Implement properties as accepted

## Definition of done

-  [ ] All tasks complete

**Comment by caw310** [comment]
DS workshop: Group 1 - Medium priority

**Comment by bkjohnson** [comment]
`inputmode` was added in this PR: https://github.com/department-of-veterans-affairs/component-library/pull/188
`disabled` has been discussed in another more recent issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/896
