### ISSUE TITLE
1-800 Vet Center phone numbers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27944]
## Issue Description
Phone numbers beginning 1-800 are not being handled correctly within Vet Center service accordions. In this example, two 1-800 numbers are unwrapped - one has (SAFE) behind it. 

<details>
    The following appears on the preview for Cincinnati Vet Center: preview-prod-vfs.gov/preview?nodeId=3641

 ![image](https://user-images.githubusercontent.com/55411834/127221577-34ea87ed-d9e6-47f0-9064-54ed1f86d3d6.png)

</details>

---
## Tasks
- [ ] Update the phoneLinks filter function to ensure phone numbers beginning with 1-800 (whether or not they are followed by a word in parentheses) are wrapped.
- [ ] Update unit tests
- [ ] Notify public websites team

## Acceptance Criteria
- [ ] Phone numbers beginning with 1-800 (whether or not they are followed by a word in parentheses) are converted to clickable links

**Comment by mmiddaugh** [comment]
This issue was addressed during the work for #27501

**Comment by mpelzsherman** [comment]
> This issue was addressed during the work for #27501

I don't think that's true. Phone numbers with words are NOT converted to links by our filter function.
