### ISSUE TITLE
[FE] Create Pact tests 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#27947]
## Description

Create Pact test for check-in endpoints

## Tasks

- [ ] Create Pact tests
- [ ] Update relevant documentations

## Acceptance Criteria

- [ ] BE also has tests created
- [ ] Deployed to staging.
