### ISSUE TITLE
[Tech-Debt] Update LGBTQ+ and Suicide pages with new updates from SOT VISN-21 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27954]
## User Story
As a VHA Digital Media web manager, the national changes need to be implemented prior to Dual state or full production launches, so the systems are updated adequetly prior to the redirect.

## Goal
Remove tech-debt prior to full production

## Resources - Tools - Documentation
TBD

## Tasks
UPdate LGBT with LGBTQ and Suicide pages with new content and organize page correctly.
- [x] Update Suicide pages with correct format order and new content
- [x] Change out LGBT with newly authorized LGBTQ+ in locations provided by Content.
_
**Complete for the following locations**
- [x] VA Central California health care
- [x] VA Northern California health care
- [x] VA Pacific Islands health care
- [x] VA Palo Alto health care
- [x] VA San Francisco health care
- [x] VA Sierra Nevada health care
- [x] VA Southern Nevada health care

## Acceptance Criteria
- [x] Suicide pages are updated and if caregiver is not listed on page it is reported in Support channel.
- [x] LGBTQ+ pages are updated and if caregiver is not listed on page it is reported in Support channel.

**Comment by bcastoe** [comment]
#27954 - Update LGBTQ+ and Suicide pages with new updates from SOT VISN-21 [BA] - Completed and moved to Validate; (1) Suicide pages checked and in correct format order (2) LGBTQ+ Detail, System and Facility page updated  (3) Caregiver listed for both Suicide and LGBTQ+
