### ISSUE TITLE
[Content-Load-Review] Load content and Internal Review, Proofread & correct plain language for VA Connecticut health care VISN-1 [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27961]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[CMS Production environment](https://prod.cms.va.gov/)
[VISN-1 Content folders](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FAnalytics%2FVISN%2D01)

## Tasks
* Load prepared content for the following pages:
- [x] About
- [x] Work With Us
- [ ] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: 
- [ ] West Haven VA Medical Center
- [ ] Newington VA Clinic
- [ ] Waterbury VA Clinic
- [ ] Stamford VA Clinic
- [ ] Willimantic VA Clinic
- [ ] Winsted VA Clinic
- [ ] Danbury VA Clinic
- [ ] John J. McGuirk Department of Veterans Affairs Outpatient Clinic

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [x]  Location Listing Page 
- [x]  History    
- [x]  Internship and Fellowship 
- [x]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [x]  System Page 
- [x]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [x]  Mission-Vision 
- [x]  Leadership Listing Page 
- [x]  Policies Page (Should be new hardened format)
- [ ]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [x]  Performance Page
- [ ]  Make an Appointment
- [ ]  Register-for-Care
- [ ]  Billing
- [ ]  Contact-us		
- [ ]  Dav-vans
- [ ]  Medical-Records
- [ ]  Operational Status
- [ ]  Pharmacy
- [ ]  Caregiver
- [ ]  Homeless
- [ ]  LGBTQ+
- [ ]  Mental
- [ ]  Minority
- [ ]  Patient
- [ ]  Returning Service member
- [ ]  Suicide prevent
- [ ]  Women-vet
- [ ]  Campus Map
- [ ]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.
