### ISSUE TITLE
[UX] Profile - Clarify user name vs sign-in email address info in profile

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#27979]
## Background
In #26950, we discovered that we are likely incorrectly guiding users to "view or update their sign-in email address" when they've logged in with MHV or DS Logon.  

Based on what we know so far, neither of those services has a sign-in email address associated with them.  If that's the case, it doesn't make sense to prompt users who have signed in with those services to "view or edit" their sign-in email address, like we are currently doing in the account security and personal + contact information pages (see screenshots).

![image](https://user-images.githubusercontent.com/55992116/127337844-a16d84e8-4766-486f-b021-4015342ed723.png)

## Tasks
- [x] Confirm whether or not MHV or DS Logon users have a sign-in email address.  Getting conflicting info in Slack between [this thread](https://dsva.slack.com/archives/C6WGBD0SW/p1627307772109700), and [this one](https://dsva.slack.com/archives/CSFV4QTKN/p1627396339300400).

If MHV or DS Logon users **do** have a sign in email address:

- [ ] Update the URL where we are sending them. There is not a place for them to update this on DS Logon, or MHV.

If MHV or DS Logon users **do not** have a sign in email address:

- [x] Determine approach to present user name info instead of sign-in information.  This includes considering whether or not we need to update profile IA or menu labeling to make it more clear to people where user name information would be found.
- [x] Review approach with AE team
- [ ] Create any mock-ups
- [ ] Review any needed w/ IA and content resources
- [ ] Hand off to FE

**Comment by ajakabcin** [comment]
@andaleliz do we still need this ticket since you completed #26950 and we have the FE ticket for implementation (#28425)?

**Comment by andaleliz** [comment]
Yep, this is a separate problem.

**Comment by andaleliz** [comment]
@Samara-Strauss and @SKasimow I have confirmed with the identity team that there isn't a sign in email address for MHV or DS Logon users.  Here is what I propose:

1. In contact information, we only show the sign in email info if a user has signed in with login.gov or ID.me. We already have logic in place to update the URL accordingly, so I think we'd just have to apply that to conditionally show/hide that section. Ideally, not a huge lift.

2. In account security, we currently show this:
![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/2f047a35-91ed-4da5-89b5-7cdbe3367c3c)

I think an improvement could be as simple as updating the content to say information "email address".  So instead of what you see in the screenshot above, it would read:

**Sign-in Information**
To view or update your sign in information, go to the website where you mange your account information. Any updates you make there will automatically update on VA.gov.

[Update sign in information on MHV]

If you agree, I can run that by content.

I have also considered making "email address" specific to the language used on DS Logon (User name) and MHV (User ID), but that complicates things because:
- I'm not sure you can even change those things on either site
- MHV is going away soon, and idk if it's worth creating custom code to support that for a few months
- If anything else changes, we'd have to update the conditional logic again.

I think "information" is more future proof and still helpful enough that people can figure out where to go if they need to update something related to signing in.

**Comment by Samara-Strauss** [comment]
I agree with the recommendations to remove the "sign in email address" box for DS Logon and MHV users, and to change the wording to "sign in information" in Account settings.

**Comment by andaleliz** [comment]
Hi team! I met with Danielle today and we're good to move forward with proposed updates.

@SKasimow this is ready for FE to:
1. conditionally hide the "sign in email" section on the contact information page ([mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/PG822vj))
2. Replace the word "email address" with "information" in the Sign-in email section of the Account Security page. ([mock up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/v/89kmvO/a/3OYm1ew/r/qjKyb3))

**Comment by SKasimow** [comment]
draft ticket opened #47070
