### ISSUE TITLE
[CONTENT-Write-Load-Review]and then Load content, and Review, Proofread & correct plain language for VA Madison health care VISN-12 [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27971]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Madison VA Medical Center legacy Site](https://www.madison.va.gov/)
[Templates required for pages](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FContent%2FContent%5FProcess%5FApproval)
[VISN-12 Content Folders](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FContent%2FContent%5FProcess%5FApproval%2FVISN%2D12%5FGreat%5FLakes%5FHCS)
[VISN-12 Health Service Playbooks](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FAnalytics%2FVISN%2D12%2FVISN%2D12%20Playbooks)

## Tasks (Part 1)
* Completed Content is written in Word Document format (Template can be found in Google Drive) and is saved referencing Medical Facility Name & Web Page Name in folder of the VA Cheyenne Name_
* The following pages will have to be researched and created using the templates created:
- [ ] About
- [ ] Work With Us
- [ ] Jobs & Careers
*INTROS updated in the following CMS/DRUPAL pages:
**Facility page intros**
- [ ] vha_607	William S. Middleton Memorial Veterans' Hospital
- [ ] vha_607GC	Janesville VA Clinic
- [ ] vha_607GD	Baraboo VA Clinic
- [ ] vha_607GE	Beaver Dam VA Clinic
- [ ] vha_607GF	Freeport VA Clinic
- [ ] vha_607GG	Madison West VA Clinic
- [ ] vha_607HA	Rockford VA Clinic

*Add "Doing Business with us" to bottom of "Work with us" page, unless 1) There is no information in which case leave area blank, or 2) There is a complete page of information and the Engineer needs to create a new page so the content needs to be added.  
## TASK (Part 2) Crosscheck
* Completed Content is written in Word Document format and is saved referencing System Name & Page Name_
- [ ] Pages have been cross checked by peer content writer for each of the following:
## TASK (Part 3) Load and review system pages

* Load prepared content for the following pages:
- [ ] About
- [ ] Work With Us
- [ ] Jobs & Careers
_
* Load Intros and review remaining page content (Plan for your visit), and confirm there is a photo or placeholder photo for the following Facilities: (See above)
_

* Review NOT needed - Quick check only
Hyperlinks should now be disabled.  (Due to broken links)
Complete Plain language review IIF PAO has already started writing these pages may we consider letting them go with content. )
- [ ]  Location Listing Page 
- [ ]  History    
- [ ]  Internship and Fellowship 
- [ ]  Volunteer and Donate 
    
* Read through and review and correct (Report any grey areas/issues)
- [ ]  System Page 
- [ ]  Health Services Listing Page (Intro Only, Health services to be loaded later)
- [ ]  Mission-Vision 
- [ ]  Leadership Listing Page 
- [ ]  Policies Page (Should be new hardened format)
- [ ]  Contact us 
 
* Observe and report (Correct any spelling errors)
- [ ]  Performance Page
- [ ]  Make an Appointment
- [ ]  Register-for-Care
- [ ]  Billing
- [ ]  Contact-us		
- [ ]  Dav-vans
- [ ]  Medical-Records
- [ ]  Operational Status
- [ ]  Pharmacy
- [ ]  Caregiver
- [ ]  Homeless
- [ ]  LGBTQ+
- [ ]  Mental
- [ ]  Minority
- [ ]  Patient
- [ ]  Returning Service member
- [ ]  Suicide prevent
- [ ]  Women-vet
- [ ]  Campus Map
- [ ]  Chaplain Services

## Acceptance Criteria
* Page content has been loaded for "About us, Work with us, Jobs and Careers, Optional "Doing Business with us"
* Intros for Facility pages
* All pages have been read through for consistency and Plain Language
* Broken or repetitive content have been updated or deleted.
* Content that does not fit, or should be moved has been documented and listed in Support channel.  Obvious moves can be completed without approval.  Questions can be discussed in team.

**Comment by larrywest52** [comment]
DONE
