### ISSUE TITLE
[CONTENT] Translate legacy VA Milwaukee health care web pages to new VAMC-upgrade format [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27972]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in VAMC system web pages, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing primary Content Pages_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Milwaukee VA Medical Center legacy Site](https://www.Milwaukee.va.gov/)
[Templates required for pages](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FContent%2FContent%5FProcess%5FApproval)
[VISN-12 Content Folders](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FContent%2FContent%5FProcess%5FApproval%2FVISN%2D12%5FGreat%5FLakes%5FHCS)
[VISN-12 Health Service Playbooks](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FAnalytics%2FVISN%2D12%2FVISN%2D12%20Playbooks)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
* Completed Content is written in Word Document format (Template can be found in Google Drive) and is saved referencing Medical Facility Name & Web Page Name in folder of the VA Cheyenne Name_
* The following pages will have to be researched and created using the templates created:
- [ ] About
- [ ] Work With Us
- [ ] Jobs & Careers
*INTROS updated in the following CMS/DRUPAL pages:
**Facility page intros**
- [ ] vha_695	Clement J. Zablocki Veterans' Administration Medical Center
- [ ] vha_695BY	John H. Bradley Department of Veterans Affairs Outpatient Clinic
- [ ] vha_695GA	Union Grove VA Clinic
- [ ] vha_695GC	Cleveland VA Clinic
- [ ] vha_695GD	Milo C. Huempfner Department of Veterans Affairs Outpatient Clinic
- [ ] vha_695QA	Milwaukee VA Clinic

*Add "Doing Business with us" to bottom of "Work with us" page, unless 1) There is no information in which case leave area blank, or 2) There is a complete page of information and the Engineer needs to create a new page so the content needs to be added.  

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing System Name & Page Name_
- [ ] Pages have been cross checked by peer content writer for each of the following:
* About
* Work With Us
* Jobs & Careers
** Optional Doing Business with us
* Facility Intro pages as designated above

* Page must be saved in Content folder on Google Drive under Page reference name
