### ISSUE TITLE
Resolve Click Tracking Error

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28000]
##  Description
An unexpected error has occurred causing sentry errors and click tracking data is not being captured properly. 

## Acceptance Criteria
- [x] Determine cause of click tracking error
- [x] Work with the platform team as needed to determine a resolution
- [x] Resolve issue - click tracking is functioning as expected.

**Comment by srsuddath** [comment]
This PR has been merged and the fix is working as intended

**Comment by denisecoveyduc** [comment]
reopened to add an estimate change from 3 to 5
