### ISSUE TITLE
E2E Test Formlet

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28006]
`codify a successful submission from a payload perspective - ✔ DONE`

## Background
In order to make sure that the 686 formlet form functions as it should we need to write end to end tests the full user journey.

## Tasks
- [ ] Set up test file
- [ ] Write e2e test for the 686 formlet
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The main user path for the 686 formlet has been e2e tested
- [ ] A PR has been submitted for review
