### ISSUE TITLE
Sync COE with Latest Designs

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28009]
`complete after status page work is complete`
## Background
Based on the latest updates from the Design side of the house, we need to update the COE application with what they have.

## Considerations
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/coe-changelog-072121.md
- https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312/simulate/sitemap?mode=f

## Tasks
- [ ] Review the changelog and address items
- [ ] Note items that are not able to be updated

## Acceptance Criteria
- [ ] The COE application is staging is as updated as possible per the design files
- [ ] A PR has been requested for merging
