### ISSUE TITLE
Package Up Formlet Data

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28003]
## Background
As data comes out of the formlet, it needs to be packaged up and sent to the existing 686 endpoint.

## Considerations
- [x] Micah has written an adapter service some time ago (https://github.com/department-of-veterans-affairs/vets-website/blob/b2003091a2341315294d96b4dadecf0f30717522/src/applications/personalization/view-dependents/manage-dependents/utils/index.js#L61)

## Tasks
- [x] Confirm and document the submission process and outcomes
- [x] Review the endpoint in use

## Acceptance Criteria
- [x] Team has been notified of outcomes in testing
- [x] A PR has been requested for merging, if needed

**Comment by micahchiang** [comment]
Tested all remove scenarios. Screenshot attached of http response. Once a PR for #28001 has been submitted and merged, this ticket can be closed out. 
<img width="727" alt="Screen Shot 2021-07-30 at 2 21 15 PM" src="https://user-images.githubusercontent.com/15097156/127702696-ea46cf99-8402-476a-8be7-de1fb8279f15.png">
