### ISSUE TITLE
[MCP] Consolidate new designs into spec for FE

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#28015]
## Issue Description
With usability adjustments completed, we need to compile all new designs into a spec for FE to begin building. 

---
## Tasks
- [x] Consolidate all MCP designs into a single UXPin project
- [x] Document Josh's Accessibility guidance into the Documentation tab of UXPin
- [x] Present designs to team
- [ ] ~Create FE ticket(s)~ (work already in progress)

## Acceptance Criteria
- [x] All designs spec'd and documented in UXPin and linked to this ticket
- [ ] ~FE tickets created and linked to this ticket~ (work already in progress)

**Comment by rileyorr** [comment]
This ticket evolved from consolidating the MCP designs into a single project into needing to create new designs due to the questions surrounding the statements we'll be receiving. [Becca opened a ticket to capture that work here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/29048). 

We'll be blocked on this work until:
- The backend VODA meeting on 8/23 
- The crosslinking meeting on 8/24

**Comment by rebeccawalsh** [comment]
Design tickets can all be found in the [UXPin here](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140669280/simulate/sitemap?mode=i).

We presented this work in standup on Sep 1, and questions that arose:
- Are we going to be able to pull the statements at all?
- Are we going to be able to pull in table data?
- What are the line items?

We chose not to make engineering tickets as some of the work is in progress. Engineers have been alerted to the designs and are responsible for creating their tickets as needed.
