### ISSUE TITLE
Add training providers info to VRRAP page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28017]
## Issue Description
Stakeholder Tammy Hurley asked us to add a section to the [VRRAP](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/) page with school information similar to what we have on the VET TEC page. This is the VET TEC page:

![Screen Shot 2021-07-28 at 1.13.09 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/603e76fd-a519-47f5-a44b-1e4fe0563117)

On VRRAP it would be called VRRAP training providers and link to this page: https://benefits.va.gov/gibill/vrrap_educational_institutions.asp

## Tasks
- [x] Add training providers section to VRRAP page
- [x] Send to stakeholder for review
- [x] Review and publish page

## Acceptance Criteria
- [x] New training providers section is live on VRRAP page

**Comment by bethpottsVADEPO** [comment]
@RLHecht Let's pull the Q&A about which schools participate in VRRAP out of the "More info" section of the page, and do this instead above that section (ping me to take a look in preview before you share with Tammy. Thanks!):

H2: Participating schools

**For Veterans:** Check our list of participating schools. We'll update this list as schools sign up. Check the list of schools participating in VRRAP (PDF) https://benefits.va.gov/gibill/docs/VRRAP_ApprovedEducationalInstitutions.pdf

**For schools:** Download the participation agreement and learn about the registration process.
Get the information and forms you’ll need to participate in VRRAP
https://benefits.va.gov/gibill/vrrap_educational_institutions.asp

**Comment by RLHecht** [comment]
@bethpottsVADEPO This is ready for you to look at.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Looks good! Go ahead and send it to Tammy for approval. It is pretty different language from what they sent us, so just do your usual mention of the fact that we reworked the text to adhere to our VA.gov style, voice, and plain language standards. Thanks!

**Comment by RLHecht** [comment]
I've published this page. Moving to validate and will close after validated on live site.

**Comment by RLHecht** [comment]
Live on site. Closing ticket.
