### ISSUE TITLE
Find a VA Form: Mock Up updated verbiage to replace "Go To Online Tool"

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#28016]
## Issue Description
Create mockups for updated language on Action and Text links, as describe here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27427#issuecomment-888468708

---
## Tasks
- [x] Mock up new text/action link for Find a VA Form search page
- [x] Mock up new text/action link for Find a VA Form detail page
- [ ] Present at design intent review

## Acceptance Criteria
- [ ] A mockup showing the new language to replace "Go to Online Tool"
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 - when you have a minute, can you please estimate this?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Adding mockups to this ticket
https://user-images.githubusercontent.com/68560244/128070521-84005b3a-4c05-4092-b68f-bb9092295f33.png

https://user-images.githubusercontent.com/68560244/128070153-7c5348b0-b3b3-48c4-a05b-aa8578b4b444.png
