### ISSUE TITLE
Unit Test COE schema

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28014]
## Background
When we set up the form fields for the COE application we added a schema into `vets-json-schema`. All schemas in `vets-json-schema` need to be unit tested to ensure they accept the correct data as well as reject incorrect data. We need to add unit tests for our schema.

## Tasks
- [x] Set up test file
- [x] Write unit tests for the COE application schema in `vets-json-schema`
- [ ] Submit a PR in `vets-json-schema` for review

## Acceptance criteria
- [ ] The schema for COE in `vets-json-schema` has been unit tested to 80% coverage, or
- [x] The form has been unit tested independently
- [ ] A PR has been submitted to `vets-json-schema` for review, if needed
