### ISSUE TITLE
Finalize Search Rep Protoype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28019]
### Background
The current **Search for accredited representative** UXPin prototype has step-through functionality. Fields and results require advanced prototype functionality to facilitate usability testing.

### Considerations
The **Search rep** feature has been redesigned to make use of VA.gov form elements. Existing XD mockups have been transferred to UXPin.
[Initial Search Rep  prototype](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12419)

### Tasks
- [x] Incorporate variables
- [ ] Some text needs to be updated (anything that references online form submission)
- [x] Alt design removing some form elements
- [x] Review search page layout (heading levels, card boxes)

### Acceptance criteria
- [x] Search prototype is fully functional and ready for usability testing

**Comment by jason-gcio** [comment]
Ensure this can be checked off
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26753

**Comment by candy-gcio** [comment]
Screens if we stop at viewing search results:
- https://preview.uxpin.com/61c3ebf323d3662f44e38a8cbb28a7d326533703#/pages/140758443/simulate/sitemap

Screens if we select a rep and generate a pdf:
- https://preview.uxpin.com/61c3ebf323d3662f44e38a8cbb28a7d326533703#/pages/140787783/simulate/sitemap
