### ISSUE TITLE
Fix 'Failed to fetch' TypeError

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28029]
## Issue Description
FE Tools requested help in triaging the top Sentry errors [Original thread](https://dsva.slack.com/archives/CSFV4QTKN/p1627483731312400). In the top Sentry errors, the `Failed to fetch` TypeError displays in Sentry.

---
## Tasks
- [ ] Modify `keepAliveSSO.js` to ensure no false-positives are logged to Sentry

## Acceptance Criteria
- [ ] Ensure no `Failed to fetch` or `Failed fetch` to the keepalive endpoint are created.
- [ ] Ensure no other Sentry logs are affected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
