### ISSUE TITLE
[Discovery] Trauma Design Best Practices for HRT initiative 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28034]
## Description 
_The Office of Resolution Management, Diversity and Inclusion (ORDMI) is the office in-charge VA Wide for processing complaints from Veterans and Employees for alleged Civil Rights Violations as well as for Harassment, Reasonable Accommodations, and other inappropriate behaviors while on a VA Site._

_In response to Section 5303 of the Deborah Sampson Act which is part of the Megabus Bill that was passed in January, and new congressional demands for action, a team of Presidential Innovation Fellows (PIFs) is scoping the feasibility of creating a secure, online reporting tool on VA.gov that would enable Veterans and VA employees to report alleged incidents about violations from Veterans and VA employees which occur while on a VA Site._

## Scope of Work
_In support of the HRT initiative we'll need to build a "Harassment Reporting 5303" Introduction page as the home page for Veterans and Beneficiaries that are looking to access the Harassment reporting tool (HRT).  Looking to gain insight into Trauma design elements as discussed during our most recent VSP Collab review - Design Intent._ 

## Tasks 
- [x]  Collaborate with Martha/Josh to gain insight on trauma design best practices 
- [x] Annotate on ticket lessons learned and recommended updates to HRT ISO discussion
- [x] Present findings at weekly HRT Sync to Stakeholders 
- [x] Determine path forward and ensure updates are applied to both Design and Prototype elements

**Comment by brianalloyd** [comment]
Completed review sessions with expert groups and completed discussion points for Stakeholder incorporation.  Closing ticket in support.
