### ISSUE TITLE
Configure BID Awards PreProd URL

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#28039]
##  Background
We need to configure the BID Awards service in PreProd for 686 testing to continue/resume.

## Tasks
- [x] Generate new auth token for PreProd
- [x] Update devops repo with PreProd URL and auth token

## Acceptance Criteria
- [x] The BID Awards service is configured for testing in PreProd
- [x] A PR has been requested for merging
