### ISSUE TITLE
[Design] Harassment Reporting Tool - Introduction Page Prototype Build

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28032]
## Description 
_The Office of Resolution Management, Diversity and Inclusion (ORDMI) is the office in-charge VA Wide for processing complaints from Veterans and Employees for alleged Civil Rights Violations as well as for Harassment, Reasonable Accommodations, and other inappropriate behaviors while on a VA Site.

In response to Section 5303 of the Deborah Sampson Act which is part of the Megabus Bill that was passed in January, and new congressional demands for action, a team of Presidential Innovation Fellows (PIFs) is scoping the feasibility of creating a secure, online reporting tool on VA.gov that would enable Veterans and VA employees to report alleged incidents about violations from Veterans and VA employees which occur while on a VA Site._

## Scope of Work
_In support of the HRT initiative we'll need to build a "Harassment Reporting 5303" Introduction page as the home page for Veterans and Beneficiaries that are looking to access the Harassment reporting tool (HRT).  The content from this pace will be provided by the PIF/ORDMI team and we'll need to get that information vetted by our local content team for inclusion on the landing page._  

[Link to Design Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26477)
 
## Tasks 
- [ ] Build prototype introduction page accordingly to VA.gov design system specs
- [ ] Build prototype for both Desktop and Mobile (Or which ever will be used in support of research study)
- [ ] Collaborate with Research to ensure prototype works as intended ISO research efforts 
- [ ] Ensure prototype is ally compliant and complies with VA.gov design system specifications 

## Acceptable Criteria 
- [ ] Prototypes are completed in accordance with task identified above 
- [ ] Prototypes work as intended ISO research efforts 
- [ ] Prototypes are updated according to feedback based on review

**Comment by FranECross** [comment]
This will be closed when I again have access to va.gov-team
