### ISSUE TITLE
Send DMC staging test users for Pre-Prod set up

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#28038]
## Tasks
- [ ] _Send DMC a list of staging test users so they can set up their Pre-Prod environment for us to do end to end testing_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
