### ISSUE TITLE
Confirm EVSS Call is showing two different values between EBN and VA.gov

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28031]
## Background
- A discrepancy was found between what is seen for a Veterans TCDR in EBN and what is shown on VA.gov
- We call the EVSS service for both and its presumed they should be the same

## Considerations 
Eventually we will need to update this to BGS from EVSS

## Tasks
- [x] Find a user that has a TCDR
- [x] Login to both EBN and VA.gov with the same test user to detect any discrepancies
- [x] Reach out to Mike Walker / Harlow in #evss-prod and explain the situation to them and ask if they can see that as well

## Acceptance Criteria
- [x] An explanation has been determined, or a path forward 

## Screenshots
- upon request

**Comment by kathleencrawford** [comment]
Logged in as users 17, 38, 216, 217 - they all had rated disabilities and numbers matched in both VA.gov and eBenefits.

**Comment by kathleencrawford** [comment]
Apparently this issue resolved itself after a day or two - possible lag in system updates?  

Email sent to Michael Walker and Michael Harlow to follow up.

Last email correspondence from Harlow to Mike on 08/05/2021 for further investigation.
