### ISSUE TITLE
Update to content on service member benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28033]
## Issue Description
Stakeholder Kevin Hillegas asked for updated language on the [VA benefits for service members](https://www.va.gov/service-member-benefits/) page. The content is in the pre-discharge disability claim section.

We need to change the current text of "Open to active-duty service members, Guard members, and Reservists."

Stakeholder suggestion: “Open to Service members on active-duty, to include those In the National Guard and Reserve serving on active duty orders.”

This needs to be updated to plain language before being put on the page. Beth has emailed Kevin with suggested text and we are waiting to hear back.

## Tasks
- [x] Revise suggested content to make plain language (Beth)
- [x] Update page, review and publish (Randi)
- [x] Alert stakeholder that change is live (Beth/Randi)

## Acceptance Criteria
- [x] New content is live on the site

**Comment by RLHecht** [comment]
I've updated the page and published. Moving to validate and will close after the next deployment. Will also let the stakeholders know the change is live.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
