### ISSUE TITLE
Investigate: Limit EXTERNAL_UID or EXTERNAL_KEY for BGS Service

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#28044]
## Background
Error in Sentry: `The length of the EXTERNAL_UID or EXTERNAL_KEY exceeds the maximum 39 characters allowed`

## Tasks
- [x] Research the issue and its impact of an implementation, and if able:
  - [x] Test what happens when trying to use a uid and/or key > 39 chars
  - [x] Limit the uid and key to 39 characters if an error is thrown and the user is not able to continue

## Acceptance Criteria
- [x] A path forward has been determined, and if possible:
  - [x] A user with uid or key > 39 chars is able to access BGS services
  - [x] Test specs have been created/updated as needed
  - [x] A PR has been requested for merging
