### ISSUE TITLE
[UNPLANNED] Add Feature Flipper for 686 Pension Check

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#28052]
## Background
Adding a new flipper feature to determine whether or not the 686/674 (Dependents Application) should check if it is a pension claim when we are setting the claim to be manually reviewed. Currently this feature should only be enabled in staging and not in production.

## Tasks
- [x] Add a feature toggle to only allow the Pension Check to occur in staging.
- [ ] TBD

## Acceptance Criteria
- [x] The feature toggle is in place and ready for use
- [x] A PR has been requested for merging
