### ISSUE TITLE
Fix typo on how to file a disability claim page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28062]
## Issue Description
On the [How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/) page, we use the word pension instead of disability in the intent to file question. This needs to be changed.

## Tasks
- [x] Change pension to disability (Randi)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Live page has updated text

**Comment by RLHecht** [comment]
work completed. Closing ticket. FYSA @bethpottsVADEPO
