### ISSUE TITLE
Remove "disallow" entries from Robots.txt file on August 5th 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28076]
## Story
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
Remove the following system names from robot.txt file on August 5, 2021
**Redirect is scheduled on Wednesday August 11** 
- [x] central arkansas health care (was added to August 4 go live after #28075 completed)
- [x] southern nevada health care
- [x] sioux falls health care
- [x] san francisco health care
- [ ] central california health care
- [x] fargo health care
- [x] nebraska western iowa health care
- [x] albany health care
- [x] finger lakes health care
- [x] northport health care

## Acceptance Criteria
-  [ ] System names are removed from robot.txt file on August 5th
