### ISSUE TITLE
Remove "disallow" entries from Robots.txt file on July 29th

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28075]
## Story
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
- [ ] Remove the following system names from robot.txt file on July 29nd, 2021
**Redirect is scheduled on Wednesday August 4**

- [x] western new york health care
- [x] salem health care
- [x] asheville lake city health care
- [x] salisbury health care
- [x] alexandria city health care
- [x] shreveport health care
- [x] southeast louisiana health care
- [x] gulf coast health care
- [x] sierra nevada health care

## Acceptance Criteria
- [ ] All System names are removed from robot.txt file on July 29th, 2021
