### ISSUE TITLE
Notice of Disagreement: Board Review Options - Suggested Language from The Board 

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#28070]
## Issue Description
The Board of Veteran Appeals has just sent over suggested language for the review options page. It reads thusly:

Direct Review:  A Veterans Law Judge will review your appeal based on evidence already submitted. Because the Board already has all your evidence, choosing this option will often result in a Veterans Law Judge being able to issue a decision most quickly.  Based on current estimates, the Board’s decision timeline for a direct review appeal is approximately 1 year.
 
Evidence Submission:  I have additional evidence in support of my appeal that I will submit to the Board with my VA Form 10182 or within the 90 days of the Board's receipt of my VA Form 10182. Choose this option if you want to submit additional evidence not already in your file and don’t want to wait for a hearing to share that information with a Veterans Law Judge.  Based on current estimates, the Board’s decision timeline to complete an evidence submission appeal is more than 1.5 years.
 
Hearing: I want a Board hearing and the opportunity to submit additional evidence in support of my appeal that I will provide within 90 days after my hearing. Please keep in mind this option has the longest wait times before a decision.  Based on current estimates, a final decision will take more than two years with this option because there are so many pending hearing requests.

---
## Tasks
- [ ] Work with Beth to ensure it follows plain language guidelines
- [ ] Make necessary adjustments to the NOD design

## Acceptance Criteria
- [ ] Necessary adjustments to the NOD design have been made
- [ ] Changes have been communicated to FE team
---

**Comment by kevinstachura** [comment]
All changes have been made - discussions were held in this ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/28262

The changes are here for the design:

https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/v/MxOqo9/a/WKZQq4k/r/AD5jJ4
