### ISSUE TITLE
Documentation - Move "Internal Onboarding Instructions" to Confluence

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28083]
## Description
There is a single piece of documentation in the department-of-veterans-affairs/devops/docs/operations folder. That doc explains how to process access requests for onboarding developers and other personnel. Let's move that to confluence, and get rid of that old folder. If we can update the doc w/ more relevant images and accurate info along the way, that would be awesome. 

## Background/context/resources
[Internal Onboarding Instructions doc](https://github.com/department-of-veterans-affairs/devops/blob/f9f0391b0c81af746a2548dccd477c440724ec48/docs/operations/Internal_Onboarding_Instructions.md)
[Improve workflow for processing access requests ticket
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17235)

---
## Tasks
- [x] Move to new doc in Confluence OT space 
  - [x] Organize under "How Do I"... section 
- [x] Deprecate devops version of doc w/ link to new confluence version 
- [x] Optional - update imagery 
- [x] Optional - update "When to grant access" section w/ info from #17235 
- [ ] Optional - Deprecate existing doc, using language like the following: 

We're moving our docs!
Find the [latest version of this page](https://vfs.atlassian.net/l/c/QoUGPQR1) in the Operations Team workspace in Confluence.
Still can't find what you're looking for? Reach out to #vsp-operations on Slack.

Example [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md)

## Definition of Done
- [x] Internal Onboarding Instructions lives in OT Confluence space and old doc has been deprecated

**Comment by jbritt1** [comment]
Removed the links we spoke on. Turns out they were solely serving as a table of contents linking to the various headers within the same document. The links kinda went funky upon the transition and arguably aren't super valuable since they just link to items further down in the same document so I opted for removing them vs spending time fiddling with the links.

**Comment by jbritt1** [comment]
WIP doc: https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools

**Comment by jbritt1** [comment]
Ready for review/qa

**Comment by jhouse-solvd** [comment]
@jbritt1 - will review soon. gonna see if there are older things that I can close out first, and will circle back to this asap.

**Comment by jhouse-solvd** [comment]
I'm re-assigning to me. there are a couple of loose ends that I need to tie-up.

**Comment by jhouse-solvd** [comment]
@jbritt1 - I read through the doc and made one or two tiny edits. It looks awesome! I added another final task to deprecate the  "Internal Onboarding Instructions doc" and link to your newly created doc (unless you can think of any objections or reasons we shouldn't do that yet...). 

After that, I think this one will be good to close out.

**Comment by jbritt1** [comment]
> @jbritt1 - I read through the doc and made one or two tiny edits. It looks awesome! I added another final task to deprecate the "Internal Onboarding Instructions doc" and link to your newly created doc (unless you can think of any objections or reasons we shouldn't do that yet...).
> 
> After that, I think this one will be good to close out.

I had removed the old one entirely in: https://github.com/department-of-veterans-affairs/devops/pull/9684. Could add that filename back with a link pointing to the confluence doc if desired though?

**Comment by jhouse-solvd** [comment]
> I had removed the old one entirely in: [department-of-veterans-affairs/devops#9684](https://github.com/department-of-veterans-affairs/devops/pull/9684). Could add that filename back with a link pointing to the confluence doc if desired though?

I don't want to make extra work for you or others when moving Ops' operational docs so we might just leave it as is. But, let's ask the team and Demain what they think. And I might double-check w/ some platform folks to see if they have any recommended norms that they expect us to follow. Re-assigning to me.

**Comment by jhouse-solvd** [comment]
We're good on this one. 

Closing.
