### ISSUE TITLE
Create user flow diagrams for IA and content review

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#28084]
### Background
As Certificate of Eligibility screens evolve, inbound and outbound linking of the 26-1880 and the MyCOE tool must be determined. The overall VA.gov user flow will provide a high-level context for informing the user about the end-to-end COE process.

### Tasks
- [x] Formalize a high-level thumbnail flow within the COE process
- [x] Create high-level user flow diagram showing COE tools within VA.gov
- [x] Coordinate with IA and sitewide content on use cases and flows
- [ ] Incorporate IA feedback
- [x] Determine initial list of inbound pages/link for the 26-1880 and the MyCOE tool 

### Acceptance criteria
- [x] Diagrams delivered to Mikki and Beth
- [x] Create list of inbound VA.gov URLs

**Comment by sporeboy** [comment]
XD diagrams available at this link: https://xd.adobe.com/view/03f5874d-242c-4e74-9616-641276b2b238-56a6/

**Comment by sporeboy** [comment]
Here are the inbound URLs for the COE screens:

How to apply for a VA home loan Certificate of Eligibility
https://www.va.gov/housing-assistance/home-loans/how-to-apply/

Eligibility requirements for VA home loan programs
https://www.va.gov/housing-assistance/home-loans/eligibility/

Buying a home with a VA-backed loan
https://www.va.gov/housing-assistance/home-loans/home-buying-process/

Download VA benefit letters
https://www.va.gov/records/download-va-letters/

About VA Form 26-1880
https://www.va.gov/find-forms/about-form-26-1880/

---------

The Claim Status Tool current says it can check COE status. Haven't confirmed this.

Check your VA claim or appeal status
https://www.va.gov/claim-or-appeal-status/ 

---------

After you apply page (Section or page?)
URL pending

MyCOE page (View, download, status tool)
URL pending
