### ISSUE TITLE
Add table showing practice area involvement against CC touchpoints to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28082]
## Issue Description
Testing Tools team created this very helpful table that shows which practice areas are involved in which Collaboration Cycle touchpoints. This would be a very helpful visual to add to Platform Website.
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/af77184e-8625-4cd4-9f6c-62607f960015)

---
## Tasks
- [ ] Determine where on Platform Website/Collaboration Cycle this table should be located.
- [ ] Update table to be reflective of the current practice areas and current Collab Cycle touchpoints
- [ ] Opposed to "X", create a legend similar to a raci matrix:
   - P = participates but does not provide a feedback ticket
   - F = participates and a feedback ticket is provided
   - O = attendance is optional. If you'd like the Platform specialist to attend, please specify on the ticket.
   - 8/27: ^not sure if we want to do this for our initial MVP

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
[Practice area table](https://vfs.atlassian.net/wiki/spaces/CC/pages/1872232521/Practice+Area+Involvement+Table+for+Touchpoints)

**Comment by peggygannon** [comment]
Hi, @allison0034 table looks good. I have a recommendation below for a new H1: 

Touchpoint practice area involvement

**Comment by shiragoodman** [comment]
hey @allison0034 - Can we move the table to [this page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) and delete the page it's on now? It's hard to find since it's alongside the touchpoints (one of these things is not like the other). Also, can we get more specific with the intro paragraph? Right now it says, "This table shows which practice areas are involved in collaboration cycle touchpoints." Can we modify it to say, "This table shows which Platform practice area reviewers are involved in the various Collaboration Cycle touchpoints" or something like that. I just don't want people to assume Beth and Danielle would be included in Content, or Mikki would be included for IA. This is for Collab Cycle reviewers (aka Platform team) only.

**Comment by allison0034** [comment]
@shiragoodman done. I also changed the table title to include Platform. I am just waiting to push the changes

**Comment by shiragoodman** [comment]
thanks @allison0034 ! I forgot to mention 1 last thing - my bad... Can you change the names of the touchpoints in the table to match the touchpoint names as written on Platform Website? Thanks!
![image](https://user-images.githubusercontent.com/71330581/133482291-4fa493ea-5866-4ff8-b98b-fcb4eb727fa2.png)

**Comment by allison0034** [comment]
Done... it is publishing... taking forever

**Comment by shiragoodman** [comment]
ugh I'm sorry.. I feel like my comments are never-ending. Can we edit, 

"When you’re ready to schedule your recommended Collaboration Cycle touchpoints, review the guidelines outlined in each of the touchpoint documents to prepare. Then go to the Platform Collaboration Meetings Calendar under Resources to find a time for the review." 

to

"When you’re ready to schedule your recommended Collaboration Cycle touchpoints, review the guidance outlined in each of the touchpoint documents to prepare."

honestly I think this whole sentence should be reworked but I'm tired and that seems sufficient for now.

**Comment by allison0034** [comment]
Updating the site now.

**Comment by shiragoodman** [comment]
[Updates FAQ's page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/FAQ's.1864073263.html)
