### ISSUE TITLE
Refresh VBA database

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28090]
## Issue Description
We can improve the accuracy and completeness of VBA facility data by incorporating the data received during the recent data call

This issue is scoped to only updating the VBA. Normalizing the data and/or creating a more usable front end for this data are out of scope. A goal for 4Q21 will be to create a content type for this data so that it is housed in Drupal. 

## Dependencies
- Dave to get answers to following questions
  - Can columns be added? (i.e: Region field, shared location with VHA plus url or identifier, shared location with other entity with Official name of entity and url)
  - What other sources does the existing DB consume (related to change management)
- Missing data should not prevent this work from beginning
- Column names to be maintained.  

---
## Tasks
- [ ] Generate a backup of existing database
- [ ] Add columns
- [ ] Validate ability to update with new csv
- [ ] Dump old database/clear table
- [ ] Fix view
- [ ] Write a script using facility name + facility id as primary key to insert or update Sandy's database with the data from the recent data call
- [ ] Create an example which will be used to validate with Dave in separate issue

## Acceptance criteria
- [ ] Output has the same data for an existing facility plus the new columns 
- [ ] New entries plus new columns are created for new facilities

**Comment by davidconlon** [comment]
[https://app.zenhub.com/files/133843125/5d307ec7-49e3-402f-88c1-a6fc6d03f84e/download](https://app.zenhub.com/files/133843125/5d307ec7-49e3-402f-88c1-a6fc6d03f84e/download)
