### ISSUE TITLE
Discovery - High-level user story mapping w/ BE Tools developer

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28099]
## Issue Description
In order to better understand the capabilities and access needed for BE autonomous deployment, we're going to conduct a brainstorming/ideation session with BE+Ops engineer(s). 

We'll use an interactive format to capture as many potential needs as possible. We'll then use the information to start developing user capability/story maps. 

---
## Tasks
- [x] Meet w/ BE+Ops developer for 1 hour. 
- [x] Brainstorm and capture ideas

## Acceptance Criteria
- [x] We'll document the access and capabilities needed for BE autonomous deployment

**Comment by jhouse-solvd** [comment]
Please see [this mural board] (https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1628015418343/49a1b8efab1c140d58b501c003f57b4d6816bce3?sender=u571992d9c638e14bd70a1743) for WIP documentation. 

And please see parent epic for artifacts to be created that summarize what we've captured. 

Closing.
