### ISSUE TITLE
Add Rejection Reason for Manually Processed 686/674 Submissions

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#28093]
## Background
A note needs to be added to VBMS for various workflows that RBPS is not able to address.  These need to be addressed so that VSR's can better understand how an application needs to be processed as quickly as possible.

## Tasks
- [x] Check if we are setting the claim to `MANUAL_VAGOV`
- [x] Call the BGS `createNote` service to allow for the inclusion of a rejection reason
- [x] Include a rejection reason to the "Note" section in VBMS

## Acceptance Criteria
- [x] The rejection reason is included in the Notes section of the application as viewed in VBMS
- [x] A PR has been requested for merging, if needed
