### ISSUE TITLE
Freeze first 2 rows of VA standards iframe

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#28092]
## Issue Description
The VA standards are published in an iFrame. We would like to freeze the first 2 rows.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
The first 2 rows of the VA standards are sticky.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
There currently is no way to embed code nor have the first 2 rows freeze in scroll viewport/confluence so we are leaving the iFrame as is for now. We may just make this a table in the future. See [Slack thread](https://dsva.slack.com/archives/C01AS05BQ79/p1627596033228000)
