### ISSUE TITLE
Migrate 3 Medallia Documents from Github to Confluence

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#28103]
## Issue Description
_As part of the program-wide documentation (migration to confluence) initiative, we want to make progress each sprint by migrating 3 or more documents_

---
## Tasks
- [x] _Migrate (copy/paste/edit) 3 Medallia documents from Github to Confluence_
- [x] _Link (from Confluence) each migrated document in this story_
- [x] _Note in respective Github documents they have been duplicated in confluence_

## Acceptance Criteria
- [x] _At least 3 Medallia documents currently residing in Github have been duplicated in Confluence_
- [x] _Each of these respective documents have been updated in Github to note they were duplicated in Confluence_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
The following (4) documents were migrated to Confluence:

[How to Request a Medallia Survey](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1793556578/How+to+request+a+Medallia+survey)
[Contact Center Data and Reporting Product Outline](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1791983788/Contact+Center+Data+and+Reporting)
[Contact Center Tier II/III Support Product Outline](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1791983788/Contact+Center+Data+and+Reporting)
[Medallia Product Outline](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product+Outline)
