### ISSUE TITLE
Medallia Reporting Dashboard POC in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#28104]
## Issue Description
_In order to provide reporting to teams utilizing Medallia for user surveys, we want to create a dashboard within DOMO for ease of access and future automation. This issue represent the proof of concept for this reporting._

---
## Tasks
- [x] _Manually import Medallia data for at least 4 weeks into DOMO_
- [x] _Use the imported data to create basic visualizations within a single DOMO dashboard_
- [x] _Where/how possible, create "cards"/individual charts to reflect already utilized metrics such as (not all are required for POC, but are goals for MVP):
* Experience satisfaction %
* Trust %
* Net trust increase/decrease %
* Total responses by top directory
* Task completion by top directory
* Satisfaction by top directory

## Acceptance Criteria
- [x] _A dashboard utilizing Medallia data is created_
- [x] _The dashboard displays at least a portion of the available Medallia data in a meaningful way_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Here is the [Medallia DOMO POC](https://va-gov.domo.com/page/825663825)

I have not created a "how to use this dashboard" page yet.

cc @jwoodman5
