### ISSUE TITLE
Tier 2 Process Flow Chart

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#28102]
## Issue Description
_In order to better understand the numerous steps in the tier 2 escalation process, we want a flow chart we can use to visually identify areas to improve_

---
## Tasks
- [x] _Use the tier 2 process outline to create a tier 2 process flow chart_

## Acceptance Criteria
- [x] _Tier 2 flow chart is reviewed by team and completed after feedback_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
@starlow00 Can you please attached the flow chart here? Thank you!

**Comment by starlow00** [comment]
[Tier 2 Case Process Flow_072921 update.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6908988/Tier.2.Case.Process.Flow_072921.update.pdf)

**Comment by jwoodman5** [comment]
Output linked above. Closing.
