### ISSUE TITLE
Retire IA Request Process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28117]
## Issue Description
Mikki has moved to VSA and will be taking the IA Request process with her. Platform Product Support needs to remove reference to the IA Request from Collaboration Cycle documentation and direct VFS teams to the new IA process so that VFS teams understand how to receive support from IA.

---
## Tasks
- [ ] Identify which Product Platform Support guidance and/or templates reference "IA Request"

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@mnorthuis please review above tasks and let me know if you have any questions/concerns. Also, please share the new IA template when it's ready.

**Comment by mnorthuis** [comment]
@shiragoodman Tasks look good. 

New Sitewide content and IA intake: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E

**Comment by peggygannon** [comment]
thanks, @shiragoodman I'll be taking a look at this today.

**Comment by peggygannon** [comment]
Hi, Shira, In addition to the I/A touchpoint update you listed above,  here are other reference I found to IA Request in CC documents:

1. In [Getting Started](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html)
Are you making a change to the user flow? 
We ask questions 6 and 7 to determine if IA should be involved in your Collaboration Cycle reviews and if a Contact Center Review and/or a separate IA Request is necessary.

- We currently don't link to the IA Request in this document. Should we link to new request doc? 

2. [IA request template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/ia-request.md)

- Archive this? 

3. Other references to IA

[Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html), [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html), and [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1782153274.html) touchpoint docs, we have this line: 

*Platform brings (when applicable):*
Information Architect

- Do we want to remove this line, as IA specialist is also listed under what VFS brings?

**Comment by shiragoodman** [comment]
> In Getting Started
> Are you making a change to the user flow?
> We ask questions 6 and 7 to determine if IA should be involved in your Collaboration Cycle reviews and if a Contact Center Review and/or a separate IA Request is necessary.
> We currently don't link to the IA Request in this document. Should we link to new request doc?

I think we can just remove "and/or a separate IA request is necessary." I would like to leave the questions and I don't think we need to link to the new request doc in this guidance.

> IA request template
> Archive this?

Not right away. I think this is where I'd like to delete the entire content of the template and replace it with verbiage I had outlined in my above comment. After a couple months, then we can archive the template.

> Other references to IA
> Design Intent, Midpoint Review, and Staging Review touchpoint docs, we have this line:
> 
> Platform brings (when applicable):
> Information Architect
> 
> Do we want to remove this line, as IA specialist is also listed under what VFS brings?

This is tough because we don't currently have a back fill for Mikki. We will bring an Information Architect (when we have one), but we don't currently. I think for now we can delete it, and when we get our replacement, we'll add it back in.

**Comment by peggygannon** [comment]
Hi, @shiragoodman All tasks are complete. I can close this issue.

**Comment by shiragoodman** [comment]
thanks, @peggygannon . I created a [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28513)for removing the IA Request touchpoint page from Platform Website (to be completed at a later date).
