### ISSUE TITLE
HLR Form Refresh - Frontend Changes

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28113]
## Issue Description
There is a new version of the HLR form that will require updates to the digital version.

Lighthouse documentation: https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current

---
## Tasks

Implement frontend changes to HLR form
- [x] Add v2 feature flag & migration code
- [x] Add ‘I am Homeless’ flag (required)
- [x] ~Remove Service Number field~ We don't ask for the service number in the online form
- [x] ~Changed Claimant fields (we don’t support non-Veteran Claimants)~ We've never asked who the claimant is in the online form
- [x] Remove Same Office selection
- Update Informal Conference fields
    - [x] Change Rep Name format
    - [x] Explicitly take in Rep phone# and email
    - [x] Change time window selection
- [x] Add SOC/SSOC Date field per Issue (only if opting in to AMA) - this will
likely be tied to the new Legacy Issues endpoint Lighthouse will build.
- [x] Start sending in Veteran Contact Info
- [x] Support write-in Issues - similar to NOD
- [x] Hook up FE to API

## Acceptance Criteria
- Updated form

**Comment by annaswims** [comment]
it might be easier to just diff the schemas in https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/config/schemas/v1/200996.json and https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/config/schemas/v2/200996.json

**Comment by vhenry07** [comment]
All items complete
