### ISSUE TITLE
HLR - Form Refresh Backend

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28112]
## Issue Description
There is a new version of the HLR form. Update v1 backend to address changes.

Lighthouse documentation: https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current
---
## Tasks
- [x] add new schemas in https://github.com/department-of-veterans-affairs/vets-json-schema/tree/master/src/schemas Just copy the lighthouse schemas from https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/appeals_api/config/schemas/v2 
[vets-json-schema PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/627)
- [x] follow the directions in https://github.com/department-of-veterans-affairs/vets-json-schema#updating-version to run schema tests and update the vets-json-schema version
Done: [vets-json-schema PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/627)
- [x] in vets-api copy app/controllers/v0/higher_level_reviews_controller.rb to app/controllers/v1/higher_level_reviews_controller.rb
- [x] Allow for v2 in  lib/decision_review, maybe just make a new service?
- [x] Update swagger docs (app/swagger/swagger/requests/appeals/appeals.rb and spec/request/swagger_spec.rb) (Apivore, swagger_blocks does not support draft 07 schemas)

test users: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md
## Acceptance Criteria
- [x] Updated version 2 of HLR form
- [ ] 
---

**Comment by michelpmcdonald** [comment]
Done with this, any issues that pop up should have a new ticket
