### ISSUE TITLE
Update hours for Korea BOD office on File a pre-discharge claim while overseas page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28119]
## Issue Description
A stakeholder requested a change of hours for the Korea BOD office on the [File a pre-discharge claim while overseas](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/) page.

It should now be: Monday through Friday, 8:00 a.m. to 12 p.m. and 1:00 p.m. to 4:00 p.m.

## Tasks
- [x] Update hours on page (Randi)
- [x] Review and publish page (Randi)
- [x] Alert stakeholder change was made (Randi)

## Acceptance Criteria
- [x] Change is live on the site

**Comment by RLHecht** [comment]
changes made. Created ticket for tracking purposes. Will close after validated on live site.

**Comment by RLHecht** [comment]
changes are live. Closing ticket.
