### ISSUE TITLE
Staging Review Claims & Appeals - HLR Wizard

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28128]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support. 
- [x] Platform: Schedule meeting with Platform reviewers and requesting team attendees (as listed below)
- [x] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [x] Platform: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to Platform feedback tickets.
- [x] VFS: Update this ticket with the product’s launch date after it has gone live. 11/02/21
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665)
- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository. [HLR Wizard in staging](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start).
-  Staging test-user information (if applicable)
-  Link to content brief (if applicable)
-  Link to or attach your project's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link) 
-  Link to the Github ticket that shows the work for creating and/or updating any relevant static content pages and entry points for this project. [Ticket](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665), [ticket 2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16517)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail Platform accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): Ronnie Henry
- OCTO-DE Product lead (recommended): Matt Self
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Robin Garrison, Asha Gross, Kevin Stachura, Anna Carey, Michel McDonald, Christian Valla
- VFS Content, IA, accessibility, and QA specialists (if applicable): Josh Kim, Angela Fowler

### Staging Reviews can only be scheduled on Thursday.

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York).<br>

**Date/time**
 August 12, 1:30

Please note:
- All times are shown in ET. 
- Available time slots are indicated with [STAGING BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [STAGING BLOCK]. 
- Please select a time slot at least 4 business days from request date.

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Review has been scheduled for 1:30pm on 8/12. Thanks!

**Comment by pjhill** [comment]
@vhenry07 -- Apologies, I'm just reviewing this now because I've been out for a few days. Are there any QA artifacts available for review? The items linked in the ticket appear to be the default links in the template.

**Comment by vhenry07** [comment]
No QA artifact for this one @pjhill

**Comment by pjhill** [comment]
> No QA artifact for this one @pjhill

Thanks for the quick reply. Just to verify there are no functional changes to the product that would warrant an independent verification? Are there any tweaks to your end-to-end test cases required?

**Comment by vhenry07** [comment]
> > No QA artifact for this one @pjhill
> 
> Thanks for the quick reply. Just to verify there are no functional changes to the product that would warrant an independent verification? Are there any tweaks to your end-to-end test cases required?

No functional changes. We are simply moving the wizard, as-is, from one page to another.

**Comment by shiragoodman** [comment]
hi @vhenry07, @Mottie , @mattpointzxer0 , @ashagross , and @kevinstachura 
As stated on the call, we are asking you to please complete a survey for the pilot of our new standards and Staging Review process. The survey link can be found here: https://adhoc.optimalworkshop.com/questions/xv854bro

We will be reviewing all feedback received from VFS teams, and will be making enhancements to our process prior to launch.

Thank you again!

@vhenry07  could you please forward the survey link to anyone I may have missed? thanks!

**Comment by shiragoodman** [comment]
Meeting recording: https://zoom.us/rec/share/qMD7BAGMAfTHQMtaV3seNQGFJbgU-iWahPzdiWfnmmrjYPV3VF2wJMejJ4cLJ14P.hDmwLUNx57UsPX6z
