### ISSUE TITLE
[Research/Design] Notification settings: Explore A/B testing options for orienting users post MVP

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28127]
## Background
As part of the effort to encourage Veterans to actively set their notification settings, we want to explore how best to orient Veterans to this new feature. We want to explore A/B testing to determine what design solution (a modal va in-page alert) would get Veterans to engage more with the notification preferences feature. This is likely something we would execute on post-MVP launch.

See #26946 and #27113 for additional reference.

## Tasks
- [ ] Work with PO and PM to discuss a strategy for A/B testing
- [ ] Discuss technical approach for A/B testing
- [ ] Consider analytics implications and what we'll need in place to track the experiment appropriately
- [ ] Set success metrics for for A/B testing

**Comment by andaleliz** [comment]
3 questions are coming up for me that could be answered through an A/B test. It would be helpful to know if any other team members have questions about the design or our strategy that we could test. I don't think we should do A/B testing just for the sake of A/B testing.

1. Do we need to highlight each input, or is the alert at the top of the page sufficient to get Veterans to engage with setting notification preferences? 
    **A:** Page with alert at top of page and inputs without messaging
    **B:** Page with alert at top of page and inputs with messaging

2. Is our background-color only alert or the new pattern we're exploring more effective at getting people to set notification preferences? 
    **A:** Page with background-color only alert
    **B:** Page with new input style messaging (border on left side, background color on message)
 
3. Is a modal or in-page alert more effective at driving traffic to the notification page? We could test the same CTA and button style in both, and our A/B test would be:
    **A:** Use modal component
    **B:** Use in page alert

**Comment by ajakabcin** [comment]
Awesome info here @andaleliz  thank you! I think we can pause on this for now - I'll move it to next sprint or the one after next depending on load. Thanks!

**Comment by andaleliz** [comment]
Per @ajakabcin we won't be pursuing A/B testing with this product, for now.

**Comment by ajakabcin** [comment]
Hey @andaleliz  let's actually keep this open, just in the backlog and revisit post-MVP.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO FYI this has been sitting in the backlog for quite some time. I just realized it didn't have the profile label on it, so I added it. 

I'm not sure if the team still wants to pursue or explore this, based on the current KPIs for notification settings. If OCTO is happy with engagement on the feature, I don't know that it's worth doing a specific "orientation" effort to increase engagement.

**Comment by andaleliz** [comment]
This is something the team talked about doing before @Samara-Strauss came back from maternity leave, not sure it's on her radar either.

**Comment by Samara-Strauss** [comment]
Thanks for letting me know about this, @andaleliz! This is low priority now for a couple reasons:

- Other, higher priority work.
- We don't have a way to A/B test on VA.gov yet, though I believe there is a pilot in the works.

Let me know if you have questions or want to talk about this.

**Comment by andaleliz** [comment]
@Samara-Strauss since we are no longer tracking the MVP KPIs for this feature, I don't think this is something we need to do.  The inspiration for this ticket was to move the needle on those KPIs. I'll close but please feel free to reopen if this is still something you want to explore.
