### ISSUE TITLE
[Design] Notification Prefs: Design solution for engaging veterans to add missing contact information, and then move out of null preference state once all info is in profile

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28126]
## Background
Due to the recent discovery that we will not have data around default settings that result in "nulls" in the database, we need to rework some elements of our design to encourage Veterans to actively set a preference on certain communication channels. As a reminder, there are four possible states regarding the true, false and null statuses in the database:

1. I have asked for something and I get it (true in database)
2. I have asked not to get something and I do not get it (false in database)
3. I have not asked for something and I get it (null in database)
4. I have not asked for something and I do not get it (null in database)

We need our design solution to solve for the new business goal of eliminating as many "nulls" as possible, i.e. getting Veterans to actively chose to receive or not to receive notifications, therefore moving them to true or false states in the data.

## Tasks
- [x] Design solution for encouraging Veterans to set their preferences to true or false (yes or no)
- [x] Review designs with content
- [x] Review designs with team and Kevin

**Comment by andaleliz** [comment]
Spent some time this week working through the design and reviewing w/ a11y and content.  I sent the following message to @KevinMHoffmanUSDS and @ajakabcin; copying some feedback over here for documentation and transparency. Convo took place in a Slack DM so can't link to it.

After reviewing the [last iteration](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140679665/comment/sitemap?mode=i) with a11y and content, I made the following changes:

- Using the [experimental expandable alert component](https://design.va.gov/experimental-design/expandable-alert) instead of the full-width dismissible alert. Primarily because it's more mobile friendly, and IMO, makes a better connection to the notification items since it's physically closer. It also has stronger correlation for those who can see color.  I'm proposing we have it open by default, and users can collapse it (instead of dismiss) if it's in their way.

- I added a list of the notification items in the alert to provide users with a summary, and to make it easier for screenreader users to navigate. I realize this might not scale well as the list grows.  We could have it collapsed by default, but likely we'll need to revaluate the approach (which is OK with me).
  - question from Kevin: 
     > On the one hand, I like that this is tying the thing to the thing we want people to do. On the other hand, it kind of gets them jumping in based on interest, and they still may skip some. Would this only display not set notifications?
   - response from Liz: Yes, only not set notifications.

- I added an icon to the status message in the notification, so we are not strictly relying on color to communicate meaning. 
  - question from Kevin: I'm not nuts about this one. Why not use bold? Or even more importantly, do you really feel like there is sufficient evidence based on desired outcomes that the icons will help make this possible? Something you could explore in testing, e.g. 50% of users go one way or the other way
  - response from Liz:  The icon isn't so much to address a font styling problem, as much as it is to ensure we're not relying only on color to highlight the message. I explored other font treatments. When I tried bold, I felt like it crashed with the fieldset legend, and when the legends aren't bold, I feel they aren't as easy to scan. Especially when we have instances of radio buttons being replaced by missing contact info messaging. (screenshots below)

![image (6)](https://user-images.githubusercontent.com/55992116/128255288-d83134ae-1b70-4a4f-8b15-21292230aa22.png)
![image (7)](https://user-images.githubusercontent.com/55992116/128255298-d04be4ca-9f19-44c0-8fff-7a4567e23339.png)


With the [new design](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140756135/simulate/no-panels?mode=i) I'm proposing, users who are missing an email or mobile number from their profile ( ~40-50%), will see this version when the first land on the page.

Users who have complete contact information in their profile will see this version (less content in alert, and all radio buttons are available).

[Here's a mock-u](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140721595/simulate/sitemap?mode=i)p of the interactivity

**Comment by andaleliz** [comment]
Sharing a couple of thoughts that bubbled up for me last night:

- We discussed as a team that we feel okay about not usability testing this prior to launch; rather we're planning to follow the approach we took with My VA (internal study + slow release to production).
- We could do an A/B test when we launch - one version without the `select an option` messaging, and one with, to see if we get more engagement with both the alert and that treatment on the radio buttons. I think the alert is more important than the radio buttons because it provides that list of links and the summary at the top of the page.  In another study, that component was the first thing people interacted with on the page, so which suggests there is a low risk of it being missed on our page.

**Comment by KevinMHoffmanUSDS** [comment]
@andaleliz Question - has content reviewed this page, either via the collab cycle or other? If so, what kind of feedback did they provide?

**Comment by andaleliz** [comment]
@KevinMHoffmanUSDS yes, content reviewed the page in a 1:1 yesterday, and the mockups reflect all the feedback I received. Changes were minimal but included:
- updating "Please make a selection" to "Select an option." (including punctuation)
- linking the entire sentence "Manage your health care email notifications on MyHeatheVet" instead of just the last word
- Updating the alert text to read "We’ve added notification settings to your VA profile.  Update your settings for these  [count] notifications" instead of "We've recently added notification settings to your profile. Please tell us how you'd like to hear from VA."

**Comment by andaleliz** [comment]
Kevin, AJ, and I met on Friday to discuss these designs. A big change is that we will focus on completing profile first (gathering contact info) then converting nulls to true/false values.  Kevin had design feedback to consider, and I spent the afternoon Friday exploring options.  His feedback, and my response follow:

> Alert feedback - does it need to be expand/collapsible? Also, we should minimize the amount of content in the alert. We want a billboard, short and succinct. "hey, this needs to be done. here's a way to do it"

Agreed. updated alert style to use our standard alert as this works OK on mobile when there is less text. 

> Consider a "one step at a time" approach for completing nulls, but on the same page. Suggest trying a button in the alert that would send the user to the first notification item once clicked. Then upon making a selection in the first item, we can present a way for the user to go to the next item.

- This is an interesting idea. We have to use links instead of buttons on the page since we're linking within the page, using an `<a>` element.  
- After exploring, I landed on a solution where there is a link inside the success message, prompting the user to go to the next item.  [Mock-up here](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140836942/simulate/sitemap?mode=i).
- @AngelaFowler82 and I discussed replacing the list of notifications in the previous version with the approach described above. She agreed it is still an accessible approach, as long as we send focus to the link in the success message.
- I don't think it is a good idea to try this approach and having developers build this without running a usability test. It's a new pattern we haven't tried before in terms of guiding people through a series of inputs.  Is this really "MVP"? I'm inclined to go with the "get started" CTA, and test/implement the links in the success messages if we see a drop off after the first selection.
 - One thought I haven't solved for: how do we handle the links in the success message when people make selections out of order?

> Using bold text in the alert instead of an icon. 

I feel strongly that we need to use the icon to help low vision and colorblind users discern the difference between the different states if there are multiple on the same page. I understand that's not going to be common, but it could happen. Icons help us rely less on color to communicate meaning. I'll bold the text too, as that's consistent with our error messages.

>  Consider consolidating notifications people can't opt into instead of listing them out and repeating the "add contact info to get this notification messaging"

- We'll go back to the previous approach we had where we didn't give users a way to do anything put add contact info for a notification they don't have.  
- I explored options where we only show users notifications they can choose, and then list options in an alert or call-out box ([one option here](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140836983/simulate/sitemap)).  
- Since our usability test listed out notifications and included an "add contact info" for each one, and tested well, I want to stick with that. We can explore variations in our next usability test.

### Latest Mockups
The following is what I propose based on the feedback I got, and the fact that we are not planning further usability testing before MVP. All content will be reviewed afternoon of 8/9

#### If the user is missing email AND mobile phone number
- They can't view notification information
- Use large warning alert to send them to personal and contact information section
- [Mock-up](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140836903/simulate/sitemap?mode=i)

#### If the user is missing email OR mobile phone number
- Use large warning alert related to missing content, send them to personal and contact information section
- They can view notification options for the contact info we have on file and make selection
- They won't see a "get started" CTA
- [mock-up](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140836904/simulate/sitemap?mode=i)

#### If we have complete contact info for a user
- Use the large warning alert to tell them to set preferences, with a "Get started" CTA that sends them to the first notification item where they don't have a preference set, focus will go to the first radio button
- We won't include further links on the page to guide users past the first radio option. They'll need to scroll down on their own for MVP.
- [mock-up](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140836902/simulate/sitemap?mode=i)

@ajakabcin, @KevinMHoffmanUSDS and I have a meeting set for Monday afternoon to discuss the design changes.  Based on the discussion we had on 8/6, I'm confident the MVP design we have is set up to meet the VA goals of getting people to complete relevant notification contact information, and then update at least one setting from `null` to `true/false`

**Comment by andaleliz** [comment]
Reviewed with Kevin + content yesterday, links above reflect approved designs.
