### ISSUE TITLE
[UNPLANNED] Increase Error Messaging or Visibility for CH31 Submissions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28136]
PDFs are not being generated and/or sent to VBMS for some random Veterans that apply.

Consider who to escalate this to

## Tasks
- [x] Add Sentry logging around Ch31 Submission

## Acceptance Criteria
- [x] An event is logged in Sentry
- [x] Test specs have been created/updated as needed
- [x] A PR has been requested for merging
