### ISSUE TITLE
Migrate Contact Center Documents from Github to Confluence

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#28135]
## Issue Description
_As part of the program-wide documentation (migration to confluence) initiative, we want to make progress each sprint by migrating 3 or more documents per sprint_

---
## Tasks
- [ ] _Migrate (copy/paste/edit) 3 general contact center documents from Github to Confluence_
- [ ] _Link (from Confluence) each migrated document in this story_
- [ ] _Note in respective Github documents they have been duplicated in confluence_

## Acceptance Criteria
- [ ] _At least 3 general contact center documents currently residing in Github have been duplicated in Confluence_
- [ ] _Each of these respective documents have been updated in Github to note they were duplicated in Confluence_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
