### ISSUE TITLE
[FE] Address Feedback from Design

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#28141]
## Description

Address the feedback from the design team. Feedback was found at https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/28140

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Update formating of clinic name to be normal casing
- [x] Fix the back button
- [x] Create unit tests
- [x] Create e2e tests

## Acceptance Criteria

- [x] Passes Accessibility checks using axe
- [x] Deployed to staging.
- [ ] Designer has signed off on the feature
