### ISSUE TITLE
Gather initial set of Platform Orientation content

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28179]
## Issue Description
The information shared at Platform Orientation is vast. However, it may not be the full scope of information VFS teams need, and sometimes information may be duplicated across parties (ex: design orientation overlaps with general orientation). The goal of this ticket is to ​define all of the content that should be included in Platform Orientation. 

---
## Tasks
- [ ] Collect content from existing sources (parentheses indicates owner):
   - [General Orientation slide deck ](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit?usp=sharing)
   - [Design Orientation slide deck] (https://docs.google.com/presentation/d/1gSeffl2STubvPDH9EoB-wUE2Al73wAwsG9QPQQU6eqw/edit#slide=id.p1) 
   - [BE Tools Orientation slide deck](https://docs.google.com/presentation/d/1SvXyF3Y2khQQlKpqJFI8g62HfOdx93ckPA0xiwYyjwc/edit?usp=sharing)
   - FE Tools Orientation 
      - [Onboarding for VFS teams] (https://docs.google.com/document/d/1JUp0Nm6NEJfZOt822U7lV2xJdGyLgqF2OIbkX79gFZA/edit) 
      - [FE Tools, Technical Onboarding] (https://docs.google.com/document/d/19C8T0C0pPRgkv_O3RyELVC-qXX8JdXC_XDrXMNtGczk/edit) 
      - [FE Tools, Organizational Onboarding] (https://docs.google.com/document/d/1JUp0Nm6NEJfZOt822U7lV2xJdGyLgqF2OIbkX79gFZA/edit) 
   - [Accessibility orientation slide deck] (https://docs.google.com/presentation/d/1rJLur5iIB0H47JVoTTUKd39U6TbvP12KbxICXgXNu0w/edit#slide=id.p4)
   - [QA orientation slide deck] (https://docs.google.com/presentation/d/1D6QFNd5NsPhbc7JHD7zvFkJ_y1irvJ6yP9WSQkiyLnY/edit)
   - [Analytics Orientation slide deck](https://docs.google.com/presentation/d/1TKYK88pHqNAJ0HrGtXIjnDYPQT-ccBQcOTy64kd0cd4/edit#slide=id.g5f29ec5fc2_4_71) 
   - [Analytics Getting Started page](https://vfs.atlassian.net/wiki/spaces/AT/pages/1771864128/WIP+-+Getting+started+with+Platform+Analytics+Insights)
   - CMS Orientation 
       - [Non-Technical Repo] (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms)
       - [Technical Repo] (https://github.com/department-of-veterans-affairs/va.gov-cms)
   - [New Team VSP Orientation Epic Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=New+Team+VSP+Orientation)
   - [Platform Orientation Research](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1717403694/Platform+Orientation+Research) (@rebekahickey )
   - [Platform Orientation Improvements 2021 Q3](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1626224014681/c8d9fc08366d488190a7fcfba099a2f885dc5b93?sender=u0574179b1d97118ccc0e3591) (@rebekahickey)
   - Slack Workflow Support data analysis  (@jchasia-adhoc )
      - [Requests from new VFS team members in June/July](https://docs.google.com/spreadsheets/d/1rfOXfOwP4rLXF49eKRb9kOWBpHn0fe1b0sh-FoTOov8/edit?usp=sharing) ( @rebekahickey )
   - [VSA team orientation] (https://app.zenhub.com/files/133843125/9934acd7-a4b0-474b-aba4-109c493908ad/download) 
- [ ] add all subjects/topics to MURAL board
- [ ] group like items

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rebekahickey** [comment]
Current orientation materials inventory documented here: https://vfs.atlassian.net/wiki/spaces/SDT/pages/1810399451/Orientation+Materials+Inventory

**Comment by shiragoodman** [comment]
MURAL board: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1628708910813/0841fce2df8cb1ded278a967b22f3a57cd15dbdf?sender=u79256ba52f9221838a435866
