### ISSUE TITLE
Transform 'How to meet DEPO Platform quality standards' doc for Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28177]
## Issue Description
The '[How to meet DEPO Platform quality standards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/how-to-meet-depo-platform-standards.md#how-to-meet-depo-platform-quality-standards)' doc on github is currently used by OCTO-DE leadership in communicating VA.gov requirements to external VA stakeholders. This document allows OCTO-DE leadership to easily sates, "this is what's required in order for something to be ok'd to be on VA.gov."

The document is somewhat outdated and will need to be brought up to today's standards/level of enforcement. 

OCTO-DE would like to have an updated version of this document moved to Platform Website so that they can continue to support VA.gov requirements with external stakeholders.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] OCTO-DE leadership has approved of the updated documentation and location on Platform Website.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@andreahewitt-odd per my comment above, I think this doc should belong on Confluence, not Platform Website. I also think it should be in the About the Platform space... What do you think? Please let @peggygannon and I know ASAP.

**Comment by andreahewitt-odd** [comment]
@shiragoodman Who are external VA stakeholders? I don't know exactly where this should live without more discussion but it sounds like something that should be owned by @rroueche if it's a document she's using to communicate about platform. Not by product support.

**Comment by rroueche** [comment]
Thanks for the convo via this thread! That makes sense - I'll take this on as a thing for OCTO-DE to own for stakeholder communications.

**Comment by shiragoodman** [comment]
thanks Rachael. @peggygannon I am moving this to Icebox and will remove it from our Sprint Report. Let's look at the backlog during our initiative meeting today and find other work you can take on this sprint.
