### ISSUE TITLE
Ingest Relevant Product Support Data from GitHub to BigQuery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#28176]
## Background/Context:
The Collaboration Cycle is a platform process that guides VFS teams through the process of creating a product on platform. While navigating that process, teams go through what is called a 'Staging Review', that results in a series of tickets being created for teams related to their products...

## Target Audience(s):
* Primary Audience: OCTO-DE Leadership, Product POs, VSP Leadership
* Secondary Audience: VFS Team PMs/Staff

## Purpose:
The main intent of the product support dashboard is to provide a view of staging review tickets on a team by team basis

## Anticipated Data Points:  (Source: GitHub Tickets) [REFERENCE DATA HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25770#issuecomment-889241020)
- [x] CC label (Y/N) - This should filter out the tickets we care about or not, every ticket we care about should have this label
- [x] Issues by team (based on VFS Team label)
- [x] Issues Open/Closed
- [x] Launch-Blocking/Non-Launch (It will either have the launch blocking label, or have no label at all)
- [x] Practice Area - May contain one or more of these labels:
  - IA
  - Content
  - Design
  - 508/Accessibility
  - QA
- [x] Collaboration Cycle Touchpoint - Currently Staging review is the only active touchpoint for ticket creation, but they may expand in the future, so may be worthwhile to begin tracking it now
  - design-intent
  - midpoint
  - staging (all tickets should come under this currently)
- [x] Accessibility Issue Severity - Only applies to Accessibility Issues
  - 0
  - 1
  - 2
  - 3
  - 4
- [x] Time to Resolve a Ticket (The emphasis on this is time to resolve launch-blocking tickets - we may want to experiment with different ways to illustrate this)
- [x] VA.gov experience standard categorization  (Each Collab Cycle ticket will refer to this categorization, [documentation can be found here](https://docs.google.com/document/d/1AKqa3kCfo_lq-UsiylRHc5_G-BhdfmxmDrPgWXZ35AY/edit))
Naming Convention format: CCissueXX.YY
  - XX = Issue category number (Column C of spreadsheet)
  - YY = Issue type number (Column F of spreadsheet)

## Tasks
- [ ] Use existing GitHub -> BigQuery ingestion mechanisms to extract and load the relevant data for the Product Support Dashboard into BigQuery

**Comment by rjohnson2011** [comment]
In the process of extending additional queries for the above information into BigQuery.

**Comment by rjohnson2011** [comment]
Have queries available to retrieve the parameters above. Used `date_diff` to calculate days an issue remains open. 
One final question remaining, are these looking to count or filter by the above labels for the eventual Domo ticket?

**Comment by rjohnson2011** [comment]
All of these properties are available to query via BigQuery and modify according into Domo.
