### ISSUE TITLE
Gather VFS feedback for role definement

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28185]
## Issue Description
We are aware that not all orientation content will need to be consumed by all VFS team roles (for example: BE developers do not need to be familiar with the Content Style Guide). We need to ensure that the right folks are being directed to the right content.

In order to ensure we're directing the new VFS team member based on role to content applicable to them (and in order to ensure we aren't missing any valuable content), we'd like to reach out to the existing VFS team roles (PMs, Designers, FE and BE) to get their feedback.

---
## Tasks
- [ ] *idea: possibly create a poll with a complete list of previously identified orientation content topics. Ask VFS team members to identify their role and check which topics are relevant to their role. Then ask if any topics relevant to their role are missing. 
- [ ] add (or evaluate adding) any missing topics to MURAL board
- [ ] using the poll results, assign role labels to each content topic

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
Orientation is already broken out by role, and it is challenging to look at an inventory and decide what's missing. In the MVP, we can make assumptions about which content is relevant to which VFS-team role. We can get VFS team feedback on the MVP and iterate from there if needed.

Because this ticket is not necessary for the MVP, it will be closed.
