### ISSUE TITLE
526 - Certain text breaking/splitting to next line.

### ISSUE THREAD

**Issue by ashagross** [department-of-veterans-affairs/va.gov-team#28181]
## Issue Description
Instances where word-break or another property is causing the text to break and go to the next line.

---
## Tasks
- [ ] Check to make sure word-break or other property is not allowing words to be broken or split when reaching the end of a line.
## Acceptance Criteria
- [ ] Words not broken or split when reaching the end of a line or paragraph. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
