### ISSUE TITLE
Add upload/download functionality to "MyCOE" screens/states

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#28184]
### Background
Letter download and document upload feature need to be added to the MyCOE page MVP. These features will be available only in particular states of the MYCOE page:
- Referred
- Pending with correspondence
- Others as determined

### Considerations
We intend to use the VA.gov standard uploader; some investigation is needed.

### Tasks
- [x] Research current instances of VA.gov uploaders
- [x] Determine which states require upload/download
- [x] Revise prototype/mockups/content

### Acceptance criteria
- [x] Prototype reflects upload/download features in revised layouts

**Comment by sporeboy** [comment]
Created digram to outline content of MyCOE screen states; includes mapped use cases:
https://xd.adobe.com/view/03f5874d-242c-4e74-9616-641276b2b238-56a6/

**Comment by sporeboy** [comment]
Initial layout for upload/download functionality: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140741546

This is just a shot across the bow. Subject to change...

**Comment by sporeboy** [comment]
MyCOE states/conditions and uses cases mapped.
Initial content in place on:
- Check COE status page
- Your COE denied state
- Your COE no-COE state

Handoffs made to Mikki and Beth.
