### ISSUE TITLE
Always show save-in-progress ID

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28190]
## Description

When initially starting a form, altering form data shows an in-progress save message, but it doesn't include the save-in-progress ID. Once you use "Finish this application later" and return to the form, the ID will show up consistently.

![Screen Shot 2021-08-02 at 10 21 28 AM](https://user-images.githubusercontent.com/136959/127894648-caaf7169-3a3f-47fd-8b67-59581c739d10.png)

## Tasks

- [ ] Always show the save-in-progress ID
- [ ] Show the full date since space isn't limited ([ref](https://design.va.gov/content-style-guide/dates-and-numbers#dates-and-years))

## Definition of done

- [ ] All tasks complete
- [ ] All test pass
