### ISSUE TITLE
Alerting - PagerDuty redesign 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28205]
## Problem Statement 
Currently, our alerting scheme is confusing and disorganized. We want to build a parallel setup alongside the current configuration by following best practice guides from PagerDuty. Then, we will deprecate the legacy configuration. 

To get a bit more granular, the scope of this initiative is for the Operations team to redesign the alerts flow for services that the Operations team is directly responsible for. Hopefully, this also serves as an example scheme for other teams to use. 

Really, the goal here is to improve the signal-to-noise ratio for our own alerts, so that we can reduce alert fatigue. 
- alerts go to the team that is responsible for the service 
- only for things that are mission-critical
- containing information that allow them to understand the alert easily 
- containing information that allow them to respond easily 

How might we organize PagerDuty according to best practices? 
How might we create discrete services that clearly describe what the alert is for? 
How might we create discrete services that route to the team that is responsible for the service? 
How might we ensure that only critical alerts are routed to SMS and phone? 
How might we integrate Datadog, Slack, and PagerDuty in a way that serves the Operations team best? 

## Hypothesis or Bet
If we set up PagerDuty according to best practices, we will have a much easier to manage alerting scheme. 
If we have a better alerting scheme, alerts will be more clear and actionable for on-call personnel. 

## We will know we're done when... ("Definition of Done")
We will know that we're done when we have the following in place: 
- Alerting routing flow is documented
- Alert routing flow is implemented 
- Services with discrete names and environments have been created for services that the Operations team is directly responsible for 
- Services that the Operations team is responsible for have a corresponding escalation policy to route the alert notification appropriately 
- Alerting guidance for other teams is documented 

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
September, 2021 

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by mchelen-gov** [comment]
@jhouse-solvd thanks this is helpful! one question about:
> Services that the Operations team is responsible for have a corresponding escalation policy to route the alert notification appropriately
what type of policy is this, PagerDuty or other?

**Comment by jhouse-solvd** [comment]
Documentation: 
- Product outline [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1548386403/Alerting+using+Prometheus+and+PagerDuty)
- Design doc [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting)

**Comment by jhouse-solvd** [comment]
This issue can be closed.
