### ISSUE TITLE
Alerting: Translate Prometheus rulesets into Datadog monitors

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28206]
## Description 
"As a developer using the platform, I want all of the metrics that are currently available in Prometheus to be available in Datadog."

As we work toward parity between Prometheus and Datadog, we need to review the existing Prometheus rulesets so that those can be translated into Datadog monitors. 

## Resources 
- [Alerting inventory](https://docs.google.com/spreadsheets/d/1bjHhCwehCzK6vejK_c_sAmzQdrFuxj0uRBjJ_gk0kEw/edit#gid=186351648)
- [PagerDuty services spreadsheet](https://docs.google.com/spreadsheets/d/1CnKN7Y11aJFshrDg7oprCbf8Vbrm6Tk1kJuV9OIWYpM/edit#gid=0)
- [Prometheus rules IaC](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules)

## Tasks 
- [ ] Audit which metrics are currently being collected by reviewing rulesets
- [ ] Determine if those metrics are being collected via Datadog, and if not...
- [ ] Configure Datadog to make sure that we are collecting those metrics 
- [ ] Translate into plain language what the alert is trying to do so that we can create a new monitor in Datadog w/ Terraform

## Definition of done
All of the metrics that are currently being collected in Prometheus are available in Datadog.

**Comment by jhouse-solvd** [comment]
This is no longer the approach. Please see [#47043](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47043)
