### ISSUE TITLE
Refine guidance around Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28201]
## Issue Description
Search and Discovery had a Midpoint Review on 8/2 where they presented 2 different designs that they had planned to test with veterans. The team had originally brought one of the designs to CC Office Hours, and because they were on the precipice of testing with Veterans, the Midpoint Review seemed like the appropriate next step.

However, at the meeting, it became clear that the team was not going to be testing a functional product with veterans. The purpose of their testing was to test the design and see how veterans' would respond.

Platform Product Support synched after the meeting and came to 2 conclusions:

1. A finalized design should be a prerequisite for Midpoint Review. 
2. Midpoint Review guidance should be updated so that all references to "usability testing" are replaced with "functional usability testing."

In short, Collaboration Cycle would like to review a functional product at Midpoint Review. 

---
## Tasks
- [ ] Update Midpoint Review documentation to reflect above.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
Rachael - "not sure if I like the term functional testing."

Ensure we review the wording with Rachael before we publish.

**Comment by peggygannon** [comment]
Hi, @shiragoodman @allison0034 Please see below for suggested update to Midpoint Review guidance to make it more clear that teams should have a functional product at the Midpoint Review. 

cc @rroueche 

Current guidance: 
**When should I request this touchpoint?** 
When you have determined your initial solution approach and have prototypes or mockups ready for usability testing

Updated guidance:
**When should I request this touchpoint?**
When you have finalized your design and have a prototype or mockup ready for usability testing, where users will complete tasks to ensure your product is functional.

**Comment by shiragoodman** [comment]
this is a great improvement Peggy. I approve.
