### ISSUE TITLE
[Alerting] Create new services in PagerDuty for services that Operations is responsible for 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28207]
## Description 
After we identify discrete services and their ownership, priority, and communications channel, we will want to set those up in PagerDuty according to best practice. 

## Resources
[PagerDuty Service Configuration guide](https://community.pagerduty.com/forum/t/service-configuration-guide/1660) (best practice)
[PagerDuty <-> Datadog Integration](https://pagerduty.com/docs/guides/datadog-integration-guide/)

## Tasks 
- [x] Create discrete services for the major components or utilities that Ops is responsible for maintaining  
- [x] Create escalation policy in PagerDuty for the Ops Team - _ie  "Platform Operations Team"_

## Acceptance Criteria
- [x] Services exist in PagerDuty for the Operations team that follow the new format

**Comment by jhouse-solvd** [comment]
Screenshot of progress with new service layout below: 

![Screen Shot 2021-08-05 at 2 02 44 PM](https://user-images.githubusercontent.com/46828900/128436291-49ad5ca8-dcf1-4746-a949-53a34bcfde6e.png)

**Comment by jhouse-solvd** [comment]
This is good to go. 

Closing.
