### ISSUE TITLE
[Tech-Debt] Update LGBTQ+ and Suicide pages with new updates from SOT VISN-9 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28210]
## User Story
As a VHA Digital Media web manager, the national changes need to be implemented prior to Dual state or full production launches, so the systems are updated adequetly prior to the redirect.

## Goal
Remove tech-debt prior to full production

## Resources - Tools - Documentation
TBD

## Tasks
UPdate LGBT with LGBTQ and Suicide pages with new content and organize page correctly.
- [x] Update Suicide pages with correct format order and new content
- [x] Change out LGBT with newly authorized LGBTQ+ in locations provided by Content.
_
**Complete for the following locations**
- [x] VA Lexington health care
- [x] VA Louisville health care
- [x] VA Memphis health care
- [x] VA Mountain Home health care
- [x] VA Tennessee Valley health care

## Acceptance Criteria
- [x] Suicide pages are updated and if caregiver is not listed on page it is reported in Support channel.
- [x] LGBTQ+ pages are updated and if caregiver is not listed on page it is reported in Support channel.

**Comment by bcastoe** [comment]
#28210 - [Tech-Debt] Update LGBTQ+ and Suicide pages with new updates from SOT VISN-9 [BA] - Completed and moved to Validate; (1) Suicide pages checked and in correct format order (2) LGBTQ+ Detail page updated as System and Facility already updated (3) Caregiver listed for both Suicide and LGBTQ+
