### ISSUE TITLE
[VAMC] Prepare New Mexico-health-care for Dual-state VISN-22 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28211]
## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed
**Tugboat Actions**
- [x] Rebuild and refresh Tugboat instance of System
- [x]  Publish all nodes for specific system
- [x]  Release content (Report any issues in release)
- [x]  View logs and resolve any broken links
**Facilities incldud:**
- [x] Raymond G. Murphy Department of Veterans Affairs Medical Center
- [x] Las Vegas VA Clinic
- [x] Artesia VA Clinic
- [x] Farmington VA Clinic
- [x] Silver City VA Clinic
- [x] Gallup VA Clinic
- [x] Espanola VA Clinic
- [x] Truth or Consequences VA Clinic
- [x] Alamogordo VA Clinic
- [x] Durango VA Clinic
- [x] Santa Fe VA Clinic
- [x] Northwest Metro VA Clinic
- [x] Taos VA Clinic
- [x] Raton VA Clinic

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system

**Comment by lealester** [comment]
awaiting release into tugboat (8/4/2021 @ 2:55pm ET)

**Comment by lealester** [comment]
5 broken links posted in support channel for review
