### ISSUE TITLE
Update URLs for Copay Balances and Copay Details

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28226]
## Issue Description
The app for MCP was created using placeholder URLs before they were finalized by IA and need to be updated. Slack to standup MCP using placeholders ... https://dsva.slack.com/archives/CPE4AJ6Q0/p1624291728195400

- `copays -> /health-care/pay-copay-bill/your-current-balances`

- `copay-details -> /health-care/pay-copay-bill/your-current-balances/balance-details`

URLs can be found here: [IA Design and Recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-copays.md)

---
## Tasks
- [ ] update URLs for copay balances and copay details

## Acceptance Criteria
- [ ] users should be able to navigate to the updated urls
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
