### ISSUE TITLE
Update phone number on DS Logon R&S page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28224]
## Issue Description
We have an out-of-date phone number on the [DS Logon FAQs page](https://www.va.gov/resources/ds-logon-faqs/) in R&S. The new number should be **800-538-9552**.
We also need to confirm if it should still be called the DMDC support center.

## Tasks
- [x] Update phone number and confirm name of center
- [x] Review and publish
- [x] Alert stakeholders change has been made

## Acceptance Criteria
- [x] New number is on live site

**Comment by RLHecht** [comment]
@bethpottsVADEPO I updated the number on the Q&A and changed the wording to Support Office instead of Support Center, which is what they say when you call the number. Moving to validate and will close after the next deployment.

**Comment by RLHecht** [comment]
work completed. Closing ticket.
