### ISSUE TITLE
[FE] Add Feature Toggles for Last 4 and Mulitple Appointments

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#28229]
## Related Documentation

-[Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=64218e8a-e7c8-478a-bd53-e2b90c01f395)

## Description

The next two features are an extra validation step and support for multiple appointments. These should be hidden behind feature toggles 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Add a toggle for extra validation 
- [x] Add Toggle for multiple appointment support
- [x] Add toggles to withFeatureFlip to be available in the app
- [x] Organize e2e tests to be a version 1 vs version 2 (have better names)
- [x] Create unit tests
- [x] Create e2e tests with new mock data

## Acceptance Criteria

- [x] Features are enabled in the development
- [x] Features are available but disabled in staging
- [x] Deployed to staging.

**Comment by mdewey** [comment]
![Screen Shot 2021-08-05 at 11 11 01 AM](https://user-images.githubusercontent.com/1793923/128374421-4214fd28-2db0-4622-bee2-22d748ce2bae.png)

Feature flips are in staging and set to false.
