### ISSUE TITLE
Updates to COVID FAQs on mask wearing

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28230]
## Issue Description
We have new, updated content on mask wearing that needs to be added to the COVID FAQs page as well as the Spanish and Tagalog pages and the chatbot.
Content to add: 

[https://app.zenhub.com/files/133843125/4f62c5fd-c7ce-4d2e-ae59-46086e63c114/download](https://app.zenhub.com/files/133843125/4f62c5fd-c7ce-4d2e-ae59-46086e63c114/download)

## Tasks
- [x] Update FAQs page (Selina)
- [x] Review and publish (Randi)
- [x] Update chatbot (Selina)
- [x] Send text to translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send to translation team for final review (Randi)

## Acceptance Criteria
- [x] New content is on FAQs pages and chatbot

**Comment by lunascoop** [comment]
@RLHecht the drupal page is ready for review. 

Coronavirus FAQs: What Veterans need to know : http://preview-prod.vfs.va.gov/preview?nodeId=3014

**Comment by RLHecht** [comment]
I published the page and sent to translators.

**Comment by RLHecht** [comment]
@lunascoop here are the translations back for both Tagalog and Spanish pages.

[https://app.zenhub.com/files/133843125/f68e1ac0-2950-4aa2-87fe-d1e3c83e02de/download](https://app.zenhub.com/files/133843125/f68e1ac0-2950-4aa2-87fe-d1e3c83e02de/download)

[https://app.zenhub.com/files/133843125/2848b6d2-2339-43c6-b4d0-bff04ebfd177/download](https://app.zenhub.com/files/133843125/2848b6d2-2339-43c6-b4d0-bff04ebfd177/download)

**Comment by lunascoop** [comment]
@RLHecht these pages have been updated and ready for review.

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
Sent pages to Mateo to review. Going to close the ticket and will reopen if he has changes.

**Comment by RLHecht** [comment]
@lunascoop Could you make this correction to the Tagalog page and let me know when it's ready for review? Thank you! 

From Mateo:
For the Tagalog—comments from the reviewer are it was well translated but looks like the following was missed for translation: We follow CDC guidelines for cloth masks when translated is Aming sinusunod ang mga patnubay ng CDC patungkol sa panakip sa ilong at bibig. The reviewer is saying that it is in the English document but left out of the Tagalog translated content.

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is for review.

Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475

**Comment by RLHecht** [comment]
Thanks @lunascoop This has been reviewed and published.
