### ISSUE TITLE
Filter and transform fields [part 1]

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2824]
## Task
The following content models need their fields filtered and transformed:
```
     21  alert
     20  collapsible_panel
      6  documentation_page
     17  event
      1  event_listing
```
This list comes from https://github.com/department-of-veterans-affairs/vets-website/pull/10967

## Goal
The content models after transformation match the result from the GraphQL query.

## Acceptance Criteria
- [ ] The content model shapes after transformation match that of their GraphQL counterpart in `pages.json`
- [ ] JSON schema is created for each content model
- [ ] Unit tests are created to validate the transformation function for each content model
