### ISSUE TITLE
Va.gov sign in/ Login.gov User interviews 

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#28251]
## Issue Description
Conduct discovery research sessions for current state of sign in for VA.gov. Receive participant feedback on Mockup for addition of Login.gov 

---
## Tasks
- [x] Work with Perigean to recruit for research sessions/Schedule research sessions
- [ ] Gather notes from observers

## Acceptance Criteria
Conduct user interviews with Participants following the schedule below:
- [x] Participant 1 Aug 2nd, 11am-12pm EST
- [ ] Participant 2 Aug 2nd, 12:15pm-1:15pm EST [No Show]
- [x] Participant 3 Aug 2nd, 5pm-6pm EST
- [x] Participant 4 Aug 3rd, 12:15pm-1:15pm EST
- [ ] Participant 5 Aug 3rd, 1:30pm-2:30pm EST [Rescheduled per Participant] **Aug 5th, 11am-12pm EST**
- [x] Participant 6 Aug 3rd, 5pm-6pm EST
- [x] Participant 7 Aug 4th, 11am-12pm EST [Rescheduled per Participant] **Aug 5th, 5pm-6pm EST**
- [ ] Participant 8 Aug 4th, 12:15pm-1:15pm EST  [No Show]
- [x] Participant 9 Aug 4th, 1:30pm-2:30pm EST [Rescheduled per Participant] **Aug 5th, 11am-12pm EST**
- [x] Participant 10 Aug 4th, 5pm-6pm EST
---
