### ISSUE TITLE
Filter and transform fields [part 2]

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2825]
## Task
The following content models need their fields filtered and transformed:
```
      7  health_care_local_facility
     94  health_care_local_health_service
     51  health_care_region_detail_page
      1  health_care_region_page
```
This list comes from https://github.com/department-of-veterans-affairs/vets-website/pull/10967

## Goal
The content models after transformation match the result from the GraphQL query.

## Acceptance Criteria
- [ ] The content model shapes after transformation match that of their GraphQL counterpart in `pages.json`
- [ ] JSON schema is created for each content model
- [ ] Unit tests are created to validate the transformation function for each content model
