### ISSUE TITLE
Implement Alert Component for the Details Page

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28272]
## Issue Description

Implement the "Pay your balance" alert on the details page according to the [mocks](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140669277/simulate/sitemap?mode=i)

![MCP Desktop - UXPin Preview 2021-08-04 12-03-14.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/050c4de1-bdc3-4119-81a6-d4e9d20181b9)
---
## Tasks
- [ ] Implement `va-alert` component to render the pay your balance alert

## Acceptance Criteria
- [ ] Pay you balance alert should render on the details page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
