### ISSUE TITLE
Implement Financial Help Section

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28271]
## Issue Description
Implement the "How do I get financial help for my copays" section according to the [mocks](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140669277/simulate/sitemap?mode=i)

![MCP Desktop - UXPin Preview 2021-08-04 11-57-02.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/9dab96c5-fadb-417f-81c7-19927347fd98)
---
## Tasks
- [ ] Create a new component for the "How do I get financial help for my copays" section

## Acceptance Criteria
- [ ] "How do I get financial help for my copays" section should display on the balance details page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
