### ISSUE TITLE
Create Copay Balance Card Component

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28273]
## Issue Description
Create a copay balance card component as shown in the [mocks](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140669280/simulate/sitemap?mode=i)

![MCP Desktop - UXPin Preview 2021-08-04 12-41-01.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/0d3311bc-0837-4fd9-8731-84e72e9d87a5)

---
## Tasks
- [ ] Create a copay balance card component

## Acceptance Criteria
- [ ] Copay balance card component should render according to mocks
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
