### ISSUE TITLE
Platform Website - Perform inventory using example spreadsheet provided by Content & IA team

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28278]
## Description
As part of our initiative to publish content that is most important to address common VFS needs, we need to perform an inventory of Ops' existing documentation. 

The Content & IA team has provided audit guidance and a sample spreadsheet that we can begin working through. Additionally, we worked together as a team to discuss some of the documentation that we think we'll be most relevant. 

## Background/context/resources
- [Audit Guidance](https://vfs.atlassian.net/wiki/spaces/AP/pages/1246527612/Audit+your+content)
- [Sample inventory spreadsheet](https://docs.google.com/spreadsheets/d/1JMoOv08vAKI16__vnkTJNrAS0c0aO3BrwSFkf8U8q6I/edit?usp=sharing)
- Notes in the comments below [copied from a recent meeting with the Ops team](https://vfs.atlassian.net/wiki/spaces/OT/pages/1742110727/2021-07-14+Ops+All+Hands)
- [Commonly asked questions from support bot ](https://datastudio.google.com/u/0/reporting/c4259d38-3515-486f-8fad-82ea06dadc4f/page/F3VEC)

---
## Tasks
- [X] Start new inventory spreadsheet
- [X] Identify the documents that we think will be most relevant
- [X] Inventory those documents with location, status, etc
- [x] Follow up with Service Design team to get additional information regarding support bot topics ('Environments', 'Pipelines', 'Null') - @jhouse-solvd 

## Definition of Done
- [x] Documented inventory of content that we expect to publish on the platform website in a coming initiative 

DOCUMENT WIP HERE: https://docs.google.com/spreadsheets/d/1ZxwcDDX5NDiOGzMdvhzL2CJ3bMgcPgQccu9NUovCxrk/edit?usp=sharing

**Comment by jhouse-solvd** [comment]
Audit Guidance  
- Identify documentation and resources currently available for VFS teams.
- Figure out what topics are most valuable based on available analytics and user research.
- Understand what content needs to be updated before migrating.
- Determine what content can be archived, without migrating.
- Decide where to put each piece of content on the Platform website.

**Where are all of our docs?** 

GitHub repos: 
- devops 
- terraform readme 
- va.gov-team
- va.gov-team-sensitive 
- GItHub wikis 
- Confluence (various pieces already in confluence)

**What are the most important docs?** 
- SOCKS 
- onboarding 
- offboarding 
- Centralized Logging w/ Loki
- Infrastructure monitoring w/ Datadog 
- Onboarding an app to EKS
- Parameter Store  
- Canaries / Synthetic Monitoring 

Approach: 
Could we automate the capture of all of our docs? 
This is what we could use to look at the inventory...
Doc title, URL, authors, commits

**Comment by jbritt1** [comment]
Jenkins deployment workflow: https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Jenkins%20deployment%20workflow.md

**Comment by jhouse-solvd** [comment]
This is done. 

Closing.
