### ISSUE TITLE
Write EDU debt content based on IRIS FAQs linked to from EDU program page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#28289]
## Issue Description
The EDU business line needs to replace the IRIS links on this page with new links to VA.gov debt content: https://www.benefits.va.gov/gibill/resources/education_resources/debt_info.asp

This is the text of the EDU content and links to IRIS FAQs:

**Education and Training**

Information About GI Bill Overpayments and Debts
The following FAQs are provided to assist you in answering your debt related questions. If you need further assistance the Debt Management Center is the authoritative source for debt collection information. You can reach them at 800 827-0648 (612-713-6415 for international callers) or by e-mail at dmc.ops@va.gov.

**Student - Debt FAQs**
What causes debts with VA Education Programs? (IRIS 1437, updated 2018)
Why do I have a debt with the VA over tuition & fees paid to my school? (IRIS 1421, updated 2019)
~Who do I contact about the debt on my account? (IRIS 1422, updated 2018)
What if the debt was created in error and was reported to a debt/collection agency? (IRIS 1423, updated 2018)~
What steps does the VA take to collect a debt under any GI Bill education program? (IRIS 1424, updated 2018)
How can I transfer debts between programs? (IRIS 989, updated 2018)
What are mitigating circumstances? (IRIS 403, updated 2018) **Note: This is the only one LW hadn't written about/not covered by Danielle's debt content either.**

**School Processing - Debt FAQs**
How can my school identify the student for whom the payment is for? (IRIS 1426, updated 2018)
My school is unable to retrieve the addenda record information from our Financial Institution, what should we do? (IRIS 1427, updated 2018)
How can my school enroll in ACH Direct Deposit, or change its ACH Direct Deposit Information? (IRIS 1428, updated 2018)
My school enrolled in direct deposit for Chapter 33 payments, why are we still receiving Paper Checks? (IRIS 1433, updated 2018)
When is my school responsible for refunding VA? (IRIS 1429, updated 2018)
**Post-9/11 School Responsibilities (404 error)**
How may my school avoid liability? (IRIS 1431, updated 2018)
Why is the Tuition and Fees or Yellow Ribbon payment less then the amount we certified for the student? (IRIS 1432, updated 2018)
How can my school refund VA? (IRIS 1430, updated 2018)
What happens if a work-study student received "advance pay" and terminates prior to working 50 hours? (IRIS 1533, updated 2018)

---
## Tasks
- [ ] Assess what's already accounted for on VA.gov. 
- [ ] What articles has Laura already created/written about?
- [ ] What still needs creating?
- [ ] What IRIS content is in fact outdated or irrelevant that's linked to from the benefits.va.gov page?
- [ ] Create articles for anything that's missing from existing VA.gov tier 1 debt content and R&S articles. 

## Acceptance Criteria
- [ ] All content currently linked to from the benefits.va.gov page has been recreated or determined to be outdated and not rewritten.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 In your Word doc you assessed which of your Q&As Danielle has covered in her content. 

1/ Of the ones she didn't have covered, which IRIS FAQs do your Q&As map to? These are the ones I'd love to see the 1:1 mapping for:

What happens when there's an overpayment?
What if I have a question about my debt?
What if the debt was an error and VA reported it to credit reporting and collection agencies?
Will my school refund money to VA if I drop a class?
What happens if my school closes?

2/ Above in this ticket, where I list the IRIS FAQs that the benefits.va.gov page links out to, can you indicate the 1:1 mapping to one of Danielle's debt articles for the ones that do map to one of hers? Here are all the debt pages she created:
https://www.va.gov/manage-va-debt/
https://www.va.gov/resources/va-debt-management/
https://www.va.gov/resources/waivers-for-va-benefit-debt/
https://www.va.gov/resources/submitting-a-financial-status-report-va-form-5655/

The ultimate goal of all this is to be able to list for the EDU business line all the IRIS FAQs and how we've accounted for them with new content either in tier 1 or in R&S.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - I put a note in the debt education ticket [17605 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17605)regarding your comment above.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Just forwarded the latest email string to you from the SME about the article covering mitigating circumstances and how to work in the part about a failing grade. Tag me here outlining how you think we should move forward after you've dug into it. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Can you provide the Word doc with tracked changes you attached to your email to Myriah? I can't access the attachment in the email thread (perhaps because the email was forwarded). Thank you!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO --

Here's my research on the failing grade issue.

I found an [SCO training presentation on Section 1019](https://www.benefits.va.gov/GIBILL/docs/presentations/IsaksonRoeSection1019.pdf)

Page 17 clearly states that mitigating circumstances are associated with non-punitive grades.

![image](https://user-images.githubusercontent.com/53535663/141815030-593cb664-5b06-4ed9-87f9-e2459bbfa462.png)

_____

I believe the question Myriah is raising is whether a failing grade is always a punitive grade, or whether it is synonymous with any of the examples of non-punitive grades included in her email (X, NP, NC or U). I searched for these codes to try to learn more, but can only find GIBHP, [answer ID 405](https://gibill.custhelp.va.gov/app/answers/detail/a_id/405/~/how-do-i-report-non-punitive-grades-at-the-end-of-the-term%3F) which Myriah apparently pasted into her email to you. Unfortunately, the full answer does not refer specifically to failing grades.

My assumption is that  X, NP, NC or U are **not** the same as "failing" and that a failing grade *is* punitive and therefore does _not_ result in overpayment. This is based on the following credible sources including GIBHP and the GIB Facebook page:

- GIPHP 1434: **What if I receive a failing grade?**If you fail a class you receive what is called a "punitive grade" for that class. A punitive grade is a grade that doesn't count as earned credit, but is used in determining a student's progress toward graduation requirements. This means that the grade you receive counts in your overall degree progress, albeit negatively. Since this grade counts towards your graduation progress you are not required to repay any GI Bill money you received for that class. You may take the class again in an attempt to receive credit towards graduation or raise your grade for it and you may receive GI Bill payment for the retaking of the class.

- <https://www.military.com/education/gi-bill/failing-a-class.html>

- <https://www.operationmilitarykids.org/what-happens-if-i-fail-a-class-with-the-gi-bill/>

- Response to comment on GI Bill Facebook page:  https://m.facebook.com/nt/screen/?params=%7B%22note_id%22%3A356027859150236%7D&path=%2Fnotes%2Fnote%2F&_rdr


**If it is correct  that a failing grade is punitive and therefore does not lead to overpayment,** we should:

- Make two adjustments to the mitigating circumstances article:

          - Remove reference to failing grade in the intro

          - Make the changes per Section 1019. (Schools are now liable for overpayments of tuition and fees. Students still liable for housing and books.)   

- Include the "failing grade" single Q&A in [ticket 30420](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30420#issuecomment-965559249) https://github.com/department-of-veterans-affairs/va.gov-team/issues/30420#issuecomment-965559249

**If a failing grade can be non-punitive and therefore can lead to overpayment**, we should:

- Stet the failing language in intro to the mitigating circumstances article, but make changes based on schools now being liable for overpayments

- Replace the article being developed in  [ticket 30420](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30420#issuecomment-965559249) with one that helps to combat the misinformation on widespread sources including those above, that a failing grade won't lead to debt.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO --
Here is the updated Word doc. I made the changes in Drupal as well, but the CMS doesn't let you see the updated single QAs on the multiple FAQs page, so thought it would be easier to review in Word form. Let me know if you have feedback. Thanks!
[How your reason for withdrawing-lw-11152021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7542120/How.your.reason.for.withdrawing-lw-11152021.docx)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - I made changes (based on the assumption that a failing grade is punitive and therefore doesn't lead to overpayment/debt) in Drupal and to the Word doc. Because CMS won't pull single QAs into the Multiple FAQs article on a published page, it may be easier for you and SME to review Word doc:
[How your reason for withdrawing-lw-11152021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7547774/How.your.reason.for.withdrawing-lw-11152021.docx)
But here are the preview nodes if you want to review in Drupal:
http://preview-prod.vfs.va.gov/preview?nodeId=33833
http://preview-prod.vfs.va.gov/preview?nodeId=33830
http://preview-prod.vfs.va.gov/preview?nodeId=33831

**Comment by bethpottsVADEPO** [comment]
Thanks for the Word doc. I updated it with my edits--would you please incorporate into drupal? Then you can communicate with Myriah about the outstanding accuracy questions. I'll introduce you by email.[https://app.zenhub.com/files/133843125/79bfa8f0-db30-45f9-a78a-d046a37e16b6/download](https://app.zenhub.com/files/133843125/79bfa8f0-db30-45f9-a78a-d046a37e16b6/download)

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Per our chat in Slack just now, I copied the current page then used your doc above to edit it while tracking changes. Attaching here and will send to Myriah shortly
[mitigating-circumstances-11162021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7550062/mitigating-circumstances-11162021.docx)
.

**Comment by lwalsh617** [comment]
For tracking, I have attached the Word doc emailed to us by Myriah (SME).
[mitigating-circumstances-11162021_sme.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7558293/mitigating-circumstances-11162021_sme.docx)

**Comment by lwalsh617** [comment]
@RLHecht -- I've made the edits per the SME word doc ^ . The following nodes are ready for you to review and publish. Thanks!
How your reason for withdrawing from a class affects your VA debt: http://preview-prod.vfs.va.gov/preview?nodeId=33833
What are mitigating circumstances: http://preview-prod.vfs.va.gov/preview?nodeId=33830
How do I report mitigating circumstances: http://preview-prod.vfs.va.gov/preview?nodeId=33831

**Comment by RLHecht** [comment]
Thanks @lwalsh617 I published these pages. I'll move this ticket to validate and close once they are live.
