### ISSUE TITLE
[Debt Portal] Rewrite status content for new card designs

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#28280]
## Issue Description
We put in some effort to consolidate the designs of the cards in Debt Portal with that of MCP, so now we need to do some content and design tweaks for each of the statuses so that they suit the new design. 

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/6f5d15c4-24eb-42cf-8cf1-42a410b7959f)

---
## Tasks
- [x] Rewrite content for both summary cards and status cards
- [x] Upload all concepts to UXPin
- [x] Send concepts to Jill and Co. for review

## Acceptance Criteria
- [x] All content written and uploaded to UXPin and linked in the ticket
- [x] Review kicked off

**Comment by rebeccawalsh** [comment]
We've drafted the content for both the grey summary cards and the detail page blue cards.  The goal with this work was to streamline the most important content on the debt detail pages and consolidate the designs with the medical copay tool. By making the tools similar, we create a more consistent experience and we might be able to combine the tools easier.

@LindaLi123 @leahkeeler 

**Our next steps are:**
- Meet with Jill and the VBA SMEs (Stacey Kulevich, Julie Lawrence, Nicole Haselberger, Dawn Eggers, Melonie Wheeler) to introduce the new designs and content to them, ask a few clarifying questions to complete the content draft.
- Revise our content with answers from those outstanding questions
- Send the complete content to that same group for a complete review for accuracy
- Create a ticket for the content team to review and revise content
- Create a backend ticket to pull in payment / payment plan data
- Create a frontend ticket to build up the FE

**Comment by rebeccawalsh** [comment]
FYI -- It's worth noting that quite a few of these cards now include the payment plan amounts and due dates. These are new to the tool, but something we've been expecting to add in for some time.
