### ISSUE TITLE
Update & migrate Google Analytics data dictionary

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28299]
## Issue Description
Update & migrate the Google Analytics data dictionary to the Platform Website.

---
## Tasks
- [ ] Migrate to Confluence
- [ ] Gap analysis on the documentation for missing tags
- [ ] Update the documentation for plain language & updated tags
- [ ] QA the documentation (add @chloedotbrown when docs are ready for QA)

## Acceptance Criteria
- [ ] When VFS teams go into Google Analytics, they can understand how to read the different labels and events for their products.

**Comment by joanneesteban** [comment]
[Confluence doc link](https://vfs.atlassian.net/wiki/spaces/AT/pages/1810464912/WIP+-+Google+Analytics+Data+Dictionary). @laurensimpson14 dropped it in from Github.

**Comment by joanneesteban** [comment]
Clarifying the acceptance criteria, @laurensimpson14 @bsmartin-ep

User story: As a VFS team member, I need to know what VA.gov website user interactions match with Google Analytics labels so that I can use Google Analytics to understand my product's basic interactions without having to reach out to Platform for individual help.

Scope VFS-facing data dictionary documentation down standardized interactions. No custom dimensions. We can keep what's currently on Confluence for internal use, but we should keep up standardized interactions (components library, forms, etc.) up-to-date and maintained & keeping it down to that should be "easier." So it looks like y'all already have most of it down in the data dictionary and it will need to be whittled down for public consumption!

Let me know if you have any further questions about this.

**Comment by laurensimpson14** [comment]
Brian updated the [data dictionary](https://vfs.atlassian.net/wiki/spaces/AT/pages/1810464912/WIP+-+Google+Analytics+Data+Dictionary) to be shorter. CDs, CMs, UTMs, and content groups are now in a [separate doc](https://vfs.atlassian.net/wiki/spaces/AT/pages/1831731201/WIP+-+temp+-+content+groups+CDs+CMs+UTM). @chloedotbrown would you mind taking a look at the data dictionary?

**Comment by chloedotbrown** [comment]
@laurensimpson14 Finished QA of the data dictionary. It looks fantastic, really great work! I made a few small changes and comments, but other than that, good to go!

**Comment by joanneesteban** [comment]
Second that! It looks great, and I'm excited for this to be published. Just make sure to break it out into subpages so it can be easier to search, and y'all are good to publish on [our page in the Platform Website](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-and-insights.1256063000.html).
