### ISSUE TITLE
Update operational docs for data triaging

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28298]
## Issue Description
Update internal documentation on triaging for high level data.

---
## Tasks
- [ ] Draft operational documentation on for all "6 data platforms":
  - [ ] Which team owns what
  - [ ] Team contact & Slack channel/support channel
  - [ ] What the data is
  - [ ] Where the data lives
  - [ ] How to triage VFS teams to each team
- [ ] @laurensimpson14 to QA documentation

## Acceptance Criteria
- [ ] Platform Analytics & Insights team understands how to triage high level data questions from VFS teams.

**Comment by joanneesteban** [comment]
Triaging doc & links updated here: https://vfs.atlassian.net/wiki/spaces/AT/pages/1820786742/Triaging+data+requests
