### ISSUE TITLE
Stretch: Update operational docs for GTM event taxonomy

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28301]
## Issue Description
Update operational documentation for implementing GTM events labels.

---
## Tasks
- [ ] Update documentation for event taxonomy
- [ ] QA documentation
- [ ] Add chatbot events

## Acceptance Criteria
- [ ] Platform Analytics & Insights team members understand how to name new and updated events in GTM when implementing GTM.
