### ISSUE TITLE
Set up Debt Portal email notification on DOMO

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#28308]
## Issue Description
_Bring Debt Portal email notification data to DOMO dashboard for a holistic view_

---
## Tasks
- [ ] _how the tracking in these emails is instrumented_
- [ ] _Work with notification team and analytics team_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindaLi123** [comment]
Hello @joanneesteban @bevnobev any update on this request? What should we do to track existing email notification data on DOMO?

**Comment by joanneesteban** [comment]
Hi @LindaLi123 - apologies for the confusion. My team is doing some technical discovery on this data over on #28356 .

**Comment by bevnobev** [comment]
Hi @joanneesteban, assuming the data they want is here (source: vanotify/email) - https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210201&_u.date01=20210804&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.sourceMedium&_r.drilldown=analytics.pagePath:www.va.gov~2Fmanage-va-debt~2F/

does that make it easier to move to DOMO?  just curious

**Comment by bevnobev** [comment]
@joanneesteban Sorry for the confusion.  After more thought, they probably want other metrics like, number sent, failed, etc. that do not show in the link above.

**Comment by LindaLi123** [comment]
@bevnobev @joanneesteban Yea we are looking for metrics like veteran clicks to the debt portal after receiving notification email

**Comment by LindaLi123** [comment]
Hello @joanneesteban any update so far?

**Comment by bevnobev** [comment]
Hi @LindaLi123  VANotify has some work to do in order to get our data into Big Query.  In the mean time, You can find out how much of the traffic to portal came from email by looking here: https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210201&_u.date01=20210804&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.sourceMedium&_r.drilldown=analytics.pagePath:www.va.gov~2Fmanage-va-debt~2F  
cc: @miabecker

**Comment by denisecoveyduc** [comment]
@bevnobev I am just following up on some of the analytic tickets for the Debt Resolution team and saw this one, wonder if there are any updates?

If I read this correctly VANotify is working to add data to Big Query at which time it can this data could then be added onto DOMO. Is that correct?

**Comment by bevnobev** [comment]
@denisecoveyduc Yes, you are correct.  VANotify is working to get data into DOMO through Big Query.  The work is still in progress, but in the mean time you can see click thru rates [here]( https://analytics.google.com/analytics/web/#/report/content-landing-pages/a50123418w177519031p176188361/_u.date00=20211008&_u.date01=20211115&_r.drilldown=analytics.landingPagePath:www.va.gov~2Fmanage-va-debt~2F&explorer-segmentExplorer.segmentId=analytics.source&explorer-table.advFilter=%5B%5B0,%22analytics.source%22,%22PT%22,%22vanotify%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.deviceCategory/)
