### ISSUE TITLE
[FE] My VA: Update bolding and chevron styling on text links in My VA 2.0 dashboard

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28302]
## Background
[Design feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25096) from staging review indicated we had some inconsistencies in the styling of our text links on My VA 2.0. We need to make some minor changes to be consistent with action link style rules:

- If text is bolded, include chevron
- If text is not bolded, do not include a chevron

## Task
- [ ] Remove the chevron from all text links on My VA 2.0 dashboard as indicated in the images below
- [ ] Add bold formatting to the % service disabled text in the banner as indicated in the images below
- [ ] Remove double chevron next to disability rating. Change to single chevron. 

![My VA Desktop updated chevrons](https://user-images.githubusercontent.com/45603961/128255570-7b91b7d0-8100-4ec1-b172-4a0ce6bb227b.jpg)

<img width="588" alt="Screen Shot 2021-08-04 at 2 55 27 PM" src="https://user-images.githubusercontent.com/45603961/128255017-a50b53f7-599c-46e2-842b-7d4086bca40f.png">

**Comment by tressaellen** [comment]
@erikphansen @tmitchellgcio - the double chevron **does** need to be changed to a single chevron.

**Comment by erikphansen** [comment]
@ajakabcin this can be validated on staging

**Comment by ajakabcin** [comment]
Checking with Tressa and Erik on unread messages link but otherwise all styling is updated and good to go. Thanks @erikphansen !
