### ISSUE TITLE
Audit "high level analytics documentation."

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28303]
## Issue Description
Audit Github & Google Drive documentation for "high level analytics documentation."

Data Platforms Overview: https://docs.google.com/spreadsheets/d/1ucM62P8HQrpn7uO6s45k3jNKECwcwT5tw1kOLpCx3ZA/edit#gid=2497302

High level information:
- Who owns it
- Where are the Slack channels/support channels
- What is the data platform
- What is the data
- How is the data helpful for VFS teams/generally how the data is used (which part of the KPI framework is this)

---
## Tasks
- [x] Create a larger Analytics audit doc
- [x] @jennaouellet Audit Github for Contact Center information
- [x] @chloedotbrown Audit Github for ForeSee & Medallia information
- [x] @laurensimpson14 Audit Github docs for access docs
- [x] @bsmartin-ep Audit Github docs for website performance docs

## Acceptance Criteria
- [ ] Platform Analytics team members understand "high level analytics documentation" needs to be moved to Confluence & what needs to be updated.

**Comment by joanneesteban** [comment]
[Content & IA's Audit guidance](https://vfs.atlassian.net/wiki/spaces/AP/pages/1246527612/Audit+your+content)

**Comment by joanneesteban** [comment]
High level audits completed. Closing this ticket.
