### ISSUE TITLE
Update Analytics Getting Started document

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28304]
## Issue Description
Clarify in the Analytics Getting Started doc how VFS teams can see if a VFS product is included in Google Analytics tracking and Domo reporting.

---
## Tasks
- [x] Discovery into connecting the RACi to Domo to track & table of contents VFS product additions
- [ ] Update the Getting Started doc.
- [ ] QA the Getting Started.

## Acceptance Criteria
- [ ] Platform Anaytics can point to the documentation to show VFS teams if their product is in Domo or tracked in GA.

**Comment by joanneesteban** [comment]
A continuation of #27718

**Comment by chloedotbrown** [comment]
@joanneesteban I created a draft TOC page [here](https://va-gov.domo.com/page/1550814739) for coverage by team and product across all 3 standardized dashboards. Let me know if there are any edits you'd like to see!

Data is being pulled from the [backlog sheet](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit?usp=sharing) in the RACI, so we can also make any data updates there. For example, should we switch which Form 526 product is checked, per their recent shift to Original Disability Claims vs. BDD?

**Comment by chloedotbrown** [comment]
@joanneesteban New card for edge cases/product types marked "other" has been [added](https://va-gov.domo.com/page/1550814739)! Let me know if you have any other changes.

**Comment by joanneesteban** [comment]
@chloedotbrown fantastic! This is great, thanks for adding it. No other changes needed on my end!

**Comment by chloedotbrown** [comment]
Great! I'll add to the Getting Started doc and close out ticket.

**Comment by chloedotbrown** [comment]
Page shared with default group (no email), added to Getting Started doc, and tested link. Closing ticket!
