### ISSUE TITLE
HLR v2 - Update Json Schema

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28315]
## Issue Description
Update vets-json-schema repo to support json draft-07 schemas.
Lighthouse's HLR v.2 json schema now uses if-then-else that was added in the draft-07.  
The repos current version of Ajv JSON schema validator is old and does not support draft-07 schemas.
Attempt to upgrade to a newer version of Ajv

---
## Tasks
- [ ] Complete tasks to update schema

## Acceptance Criteria
- [ ] Updated schema
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
I attempted to upgrade Ajv JSON schema validator to the latest version.
The upgrade caused multiple issues.  
Unfortunately, I didn't have time to solve them all so I discontinued the effort.  Upgrading, for me, was a nice to have but not required.
