### ISSUE TITLE
[FSR - PI3/23] FSR Enhancements V1

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#28318]
## High Level User Story/ies
As a Veteran submitting a waiver (FSR VA Form 5655) I am able to easily progress through the form and navigate the list loop features without any trouble.

## Scope of release
**_Main Enhancements_**
- **LIST LOOP UPDATES:** Improvements were made to list loops as the previous usability study showcased how Veterans had difficulty utilizing the list loop when it was presented as a dropdown. The updates also address accessibility issues that the dropdown version of the list loop had. List loops appear when entering employment and other income for themselves and their spouse, dependents, household assets, household expenses.
    - **Checkboxes to value input** (List Loop Removal)
	    - FE Dev: Utility Bills  [#48507](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48507) -**Done!**
		- FE Dev: Housing Expenses  [#48440](https://app.zenhub.com/workspaces/vsa---debt- 607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48440) **Done!**
		- FE Dev: Monetary Assets  [#48432](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48432)  - **Done!**
    - **Update Employment Info:** [Employment: after | before](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/enhanced_fsr/images/job-listloops-update.png?raw=true)
             -FE Dev: #52818 - **Done!**
    - **Update Dependent Info:** 
	    - Designs [Dependents: after | before](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/enhanced_fsr/images/dependents-update.png?raw=true).    
	    - FE Dev: [#46686](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46686) - **Done!**
   -  **Other Living Expenses:** Ability to add one or more additional living expenses not listed in the checklist. Includes ability for Veteran to describe what those additional living expenses are for and see a summary of what they have added so far. Veterans are also given more control and are able to edit/remove any of the living expenses they have added.  

- FE Dev: #48510 - **Ready (as of 4/11/23)**

 -**Other Assets (ADDED)**: Adding the ability to add one or more additional asset not listed in the checklist. Includes ability for Veteran to describe what the asset and see a summary of what they have added so far. Veterans are also given more control and are able to edit/remove any of the assets they have added.  

- FE Dev: #48438 **- Done!**

   - **Mini Summary Pages ADDED)**: Veterans will be given more control to review/edit/remove their entries in four key sections of the form making the overall experience more flexible and adaptive to the Veteran's needs. previously reserved for the end of the FSR form.
	   *Sections Include:*
	  1. Work History 
	   2. Installment contracts and other debts 
	   3. Other living expenses 
	   4. Household Assets 
	   5. Vehicle Information (TBD): 
          -FE Dev: #52569 - **Done!**
          -Design: #52773 - **Done!**, 52196 - **Done!** and 48388 - **Done!**

- **Editable Benefit Information (ADDED)**: The portal presents VA Benefit information to the Veteran. They will now be able to edit that information if they feel that it is incorrect. 
          -FE Dev: #48742 - **Done!**

</br> **_Smaller Enhancements_**
- **Content Updates:** On both static and application pages to better align with debt/copay content guide
	- FE Dev for Generic Content Updates  [#48446](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48446) - **Done!**
	- FE Dev for "Content Page" - No debts alert  [#48747](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48747) - **Done!**
	- FE Dev for Resolution Options explainer  [#48749](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48749) - **Done!**
	- FE Dev for Benefits Information  [#48742](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48742)  (Current content changes only) **-Done!**
- **Debt/Copay Selection:** Switching from card format to a more minimalist and easy to understand format when presenting debt/copay bills to users.  [Select debt/copay: after | before](https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/combined_fsr/research/enhanced_fsr/images/debt-cards-update.png)
	- FE Dev for Debt Selection [#48736](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48736) - **Done!**
- **Update Personal Info:** Allow Veterans to update phone number and address in addition to mailing address. [Contact info: after | before](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/enhanced_fsr/images/contact-info-update.png?raw=true)
- **Resolution Option Clarity:** Ensure resolution options are easier for Veterans to understand. [Resolution options: after | before](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/enhanced_fsr/images/resolution-updates.png?raw=true)

</br> **_Identified for future release: Not in scope for the FSR Enhancement release_**
- **Review Page Rework (ADDED)**: Updating review page to align with current design system and improve user experience.

### Collab Cycle Touchpoints
- [x] Kickoff #47462 (Collab Cycle Ticket)
- [x]  Design Intent #47599 (Completed Sept 27, 2022)
- [x]  Sitewide Content & Information Architecture (IA) Intake Request 
                                   #56447 (Team to discuss w/Randi Hecht on 4/13/23) -will this suffice? Heather to ask Governance
- [x]  Research Plan Review [#53532](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53532) [#269](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/269) Completed April 2023
- [x]  Analytics Request - #59520
- [x]  Midpoint Review #52101 (Completed January 17, 2023)
- [x]  Contact Center Review #59665 (Submit tix 2 weeks prior to launch) Heather to ask Governance if this applies - (Yes)
- [x] Staging Review (Reminder: Staging Reviews require a 4 day lead time)_Completed on 6/9/23 at 8:45am PT
- [x] Privacy and Security, & Infastructure Review #60086 (Request when in staging & before rollout- Scott to assist)
- [x] Screen Reader Testing (optional) #57662

### Post Release
- [x] 508 audit [REQ13202070](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyourit.va.gov%2Fva%3Fid%3Dsc_request%26is_new_order%3Dtrue%26table%3Dsc_request%26sys_id%3D72ab1a8e1b60f194bb492138624bcbf8&data=05%7C01%7CThomas.Davis%40govcio.com%7C7b73b47ddc4c4fe7181d08db99e8403e%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C638272995026890319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VVW%2FJw3i%2B8rf6UeYyB0wycDTdDyqnUu9UvdMC63GCfI%3D&reserved=0)

**Comment by Tom-Davis** [comment]
Closing as all tickets are complete.
