### ISSUE TITLE
GA Language Reports | VA.gov Trends | Part 1

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#28339]
We need to garner insights and trends on VA.gov on non-English users to be used as part of upcoming Translation Recommendation report.

# Phase 1 includes:

- **Top 10 languages**
- [x] By browser setting
- [x] Pageviews
- [x] Users

- **Top pages visited by non-English browsers**
- [x] Top hubs by English vs spanish
- [x] Top 100 most viewed pages (English)

**Comment by SKasimow** [comment]
We need to garner insights and trends on VA.gov on non-English users to be used as part of upcoming Translation Recommendation report.

Phase 1 includes:


- **Top 10 languages**
- [x] By browser setting
- [x] Pageviews
- [x] Users


- **Top pages visited by non-English browsers**
- [x] Top hubs by English vs spanish
- [x] Top 100 most viewed pages (English)
