### ISSUE TITLE
[Research] Check-in Phase 2 Usability Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#28334]
## User Story
- As a Veteran, I wanted to be able to check-in if I have more than one appointment in a day.
- I also want to feel that check-in is secure.
- Lastly, I would like to know if I already checked in, but accidentally start the process over again.

- As a product development team, I want to know the proposed solution is usable by Veterans and meeting the above needs.

## Related Documentation
 - [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
Finalized documentation of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.

## Tasks
- [X] Create new folder for this specific test: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/phase2-usability
- [X] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/research-plan.md)
- [x] Create [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/conversation-guide.md)

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product)
- [x] Review research plan and conversation guide with UX manager

**Comment by kristenmcconnell** [comment]
Created a UX Pin prototype and linked it to the conversation guide.

**Comment by kristenmcconnell** [comment]
Sent UX Pin link to Julia, so she can connect it in Twilio. Also, sent the research plan and conversation guide to Corey, Julia, and Danielle for review.

**Comment by kristenmcconnell** [comment]
Review from design is complete. Only very small changes were suggested; they are already incorporated into the research plan and conversation guide. 

@jparker0425 I'm going to close this out, but any feedback can still be incorporated before the test starts.
