### ISSUE TITLE
Replace v0 sign-ins with v1

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28347]
## Issue Description
Users are still being logged in via the `v0` authentication route.  We need to refactor all Identity-owned files to remove any instance of `v0` and force `v1` authentication throughout the vets-website experience.

---
## Tasks
- [x] Force v1 authentication regardless of sign-in version preference

## Acceptance Criteria
- [x] All v0 instances will be replaced with v1 with regex in function calls
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Looking at Grafana it looks like `v0` sign in are still occurring however they are a lot less than before (from hundreds to single digits).  All references on the frontend are removed so I will reach out to Joe to pull some Cloudwatch logs.

** v0 logins for August 9, 2021**
![Screen Shot 2021-08-09 at 11.59.58 AM.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/dda364a7-18e0-43de-8c6e-5a816353226e)

**v0 previous logins from last Thurs & Friday (August 5-6, 2021)**
![Screen Shot 2021-08-09 at 12.03.37 PM.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/4f846707-81d9-4525-bb22-89cc5bffa13e)
