### ISSUE TITLE
HLR: Add inline editing of contact info

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28355]
## Description

Implement inline editing of contact info, similar to the Notice of Disagreement form, to the Higher-Level Review form. Previously, we only submitted the zip code and Lighthouse would complete the form with "Use the address on file". This was determined to be inadequate, so we are now submitting the entire address.

## Tasks

- [ ] Add profile address, phone & email components for v2 api submissions
- [ ] Update unit tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
