### ISSUE TITLE
Filter and transform content from CMS export

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2835]
# Problem Statement
The data from the CMS export is raw and needs to be filtered and transformed before it can be used in the templates.

# For each ticket in this epic
There are a bunch of content models.
```
  'node-page',
  'taxonomy_term-administration',
  'paragraph-q_a_section',
  'paragraph-q_a',
  'paragraph-wysiwyg',
  'paragraph-process',
  'paragraph-list_of_link_teasers',
  'paragraph-link_teaser',
  'node-outreach_asset',
  'media-video',
  'file',
  'node-health_care_region_detail_page',
  'paragraph-react_widget',
  'paragraph-collapsible_panel',
  'paragraph-collapsible_panel_item',
  'node-person_profile',
  'paragraph-staff_profile',
  'media-image',
  'media-document',
  'node-health_care_local_health_service',
  'paragraph-downloadable_file',
  'user',
  'node-regional_health_care_service_des',
  'taxonomy_term-health_care_service_taxonomy',
  'node-news_story',
  'node-event',
  'node-support_service',
  'node-health_care_local_facility',
  'paragraph-health_care_local_facility_servi',
  'node-full_width_banner_alert',
  'node-vamc_operating_status_and_alerts',
  'node-press_release',
  'paragraph-number_callout',
  'paragraph-table',
  'node-landing_page',
  'block_content-promo',
  'block_content-alert',
  'paragraph-expandable_text',
  'node-health_care_region_page',
  'node-event_listing',
  'paragraph-media',
  'paragraph-alert',
  'node-documentation_page',
  'paragraph-spanish_translation_summary',
  'node-publication_listing',
  'node-office'
```
This list comes from logging out all unique content model names while building out the entity trees of all `node`s in our current tome-sync output (which reflects the all CMS content on VA.gov when it was exported).
For each of these, we need to do the following.

## Task
- [ ] Create a pre-transformation JSON schema at `process-cms-exports/schemas/raw/${content-model-type}.json`
- [ ] Find the test CMS export data and the corresponding bit in the GraphQL response
- [ ] Copy this chunk of the response to `process-cms-exports/tests/transformed-entities/${content-model-type}.json`
- [ ] Create a post-transformation JSON schema at `process-cms-exports/schemas/transformed/${content-model-type}.json`
- [ ] Create a transformation function to map the raw CMS export data to the GraphQL response counterpart

## Goal
The content models after transformation match the result from the GraphQL query.

## Acceptance Criteria
- [ ] The content model shapes after transformation match that of their GraphQL counterpart in `pages.json`
- [ ] Pre- and post-transformation JSON schemas are used to validate the data 
- [ ] The transformation function is unit tested using known-good data

**Comment by cvalarida** [comment]
# Table of Contents

1.  [How to migrate a CMS content model](#org8249465)
    1.  [Steps](#org4c0cd01)
    2.  [Testing](#orgb211a23)


<a id="org8249465"></a>

# How to migrate a CMS content model

The current build uses GraphQL to fetch and transform CMS
content. This documentation outlines the steps required to duplicate
the transformation done in the CMS using the new tome-sync export
data.

For the following, the current working directory is assumed to be
`vets-website/src/site/stages/build/process-cms-exports/filters.js`.

The content type we'll be using as an example here is `node-page`.


<a id="org4c0cd01"></a>

## Steps

-   [ ] Check `./tests/entities/index.js` for a reference to the
    content model type in the test data
    -   If one doesn't exist, do the following:
        -   [ ] Find an entity in the CMS export directory
            -   The tarball for this can be found in Slack
            -   Use the latest one with the corresponding `pages.json` file
                -   This way `pages.json` will accurately represent what's also
                    in the CMS export
            -   [ ] Copy this file to `./tests/entities/`, preserving the
                original filename
            -   [ ] Add the filename to `./tests/entities/index.js` with the
                appropriate content model type name
                
                    {
                      ...
                      'node-page': 'node.123abc.json',
                    }
    -   If one *does* exist, use it as the example
-   [ ] Search `pages.json` for the corresponding entity
    -   Typically searching for the path or some content that seems
        unique is enough to find the right one
    -   There are often similar entities, however, so don't just use
        the first result; make sure it's the right one
    -   [ ] Copy this entity to `./tests/transformed-entities/`
        -   E.g. `./tests/transformed-entities/page-node.json`
-   [ ] Create the raw data schema
-   [ ] Create a new filter array in `./filters.js`
    -   This may change later to be its own file
    -   The array contains the names of fields in the raw data which we
        want to keep
    -   Use the entry from `pages.json` to determine which fields to
        keep
-   [ ] Create the transformed data schema
-   [ ] Create the transformer
    -   Using your observations while creating the filters and schemas,
        it should be obvious what the general structure should look
        like, but be careful of differences within strings
        -   For example, the WYSYWIG component often has subtle changes
            between the raw data and the GraphQL response in `pages.json`


<a id="orgb211a23"></a>

## Testing

Ensure your transformations work as expected by running the following:

-   `yarn build:content:test`
    -   This runs the raw data build process on all `node` entities
-   `yarn test:unit src/site/stages/build/process-cms-exports/tests/transformer-helpers.unit.spec.js`
    -   This runs all the transformers available on the respective
        entities in `./tests/entities/` and compares them against the
        expected JSON output which we copied into
        `./tests/transformed-entities/` in a previous step
