### ISSUE TITLE
Discovery (and possible implementation) to upgrade Downshift

### ISSUE THREAD

**Issue by gescobardev** [department-of-veterans-affairs/va.gov-team#28359]
## Issue Description
_Part I - Discovery to upgrade Downshift_

Determine if [Downshift](https://github.com/downshift-js/downshift) version should be upgraded. It was found that we are currently using an old version - `1.22.5` and the latest Downshift version available is `6.1.5`. Downshift may be optimized and there could be benefits to upgrading the version.

This issue is separated from the original issue - https://github.com/department-of-veterans-affairs/va.gov-team/issues/26852

Possible considerations

1. **Upgrade Downshift globally**. This would affect other teams since Downshift is being used in multiple areas of the project. Testing would need to be done by those teams and ours to make sure the version upgrade did not break anything.
2. **Upgrade Downshift for Facility Locator ONLY**. Would need to look into how to utilize the latest version of Downshift and import that particular version in the FL files where Downshift is being utilized. Would need to test the FL to make sure version upgrade did not break FL. If FL is broken, as a result of upgrade, would need to consider fixing what is broken before getting started with the issue linked above.
3. **Proceed with the original issue without upgrading Downshift.**

*There may be other options to consider that are not noted above.

---
## Tasks
- [x] Meet with Sam from Search and Discovery about Downshift to get input from his relevant/recent work that we could possibly leverage
- [x] Make a decision on how to proceed in regards to upgrading Downshift or not.
- [x] Implement the upgrade if that is what is decided.

## Acceptance Criteria
- [x] Decision and/or implementation has been made in regards to Downshift.
