### ISSUE TITLE
Update PDF links to form 10-0381 on 2 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28353]
## Issue Description
The CMS team discovered broken links on 2 pages because the link to the find forms landing page for 10-0381 shows the form is either retired or no longer valid: https://www.va.gov/find-forms/?q=10-0381

To avoid the broken links, we need to update the pages with this PDF link instead:

https://www.va.gov/ORMDI/docs/Civil_Rights_Discrimination_Complaint_VHA100381.pdf

The 3 pages to update:
https://www.va.gov/resources/your-civil-rights-and-how-to-file-a-discrimination-complaint/
https://www.va.gov/tagalog-wika-mapagkukunan-at-tulong/
https://www.va.gov/asistencia-y-recursos-en-espanol/

Danielle is reaching out to SMEs to determine if the form is being taken down. If so, we will need to update the pages again.

## Tasks
- [x] Update both pages with new link (Randi)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Both pages have working links on live site

**Comment by RLHecht** [comment]
This work is already completed. Created ticket for tracking purposes.

**Comment by RLHecht** [comment]
@lunascoop There's still more discussions on this so in case we hear back tomorrow, here's the ticket for updating the links since I'll be out.

**Comment by RLHecht** [comment]
Update: We removed mentions of the form on all 3 pages because the form is being discontinued.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
