### ISSUE TITLE
[DISCOVERY] Find a VA Form - Form 10-0003k - inconsistent PDF link behavior on search results/detail page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#28351]
## Issue Description
During a recent user research session, we observed a user on Windows 10 using Chrome.  When user clicked PDF link for form 10-0003k from Find a VA Form search results, the file opened in a new tab in Chrome with "Please wait… If this message is not automatically replaced by the proper contents of the document, your PDF viewer may not be able to display this type of document."

When user clicked PDF link from the 10-0003k form **detail** page, the file downloaded locally.

The link on both pages utilizes the download attribute, meaning that the form should download in both cases.

I (Marci) re-watched the recording at half speed to make sure that we hadn't perhaps missed the user opting to open the file in the browser on the search results page.  I performed the same steps in Chrome on my Windows 10 PC and was able to reproduce this with this form only (10-0003k).  Other forms tested did not exhibit this behavior.

---
## Tasks
- [ ] Determine what might be causing the inconsistent behavior
- [ ] Determine if there is a way to resolve programmatically
- [ ] Work with Marci to create a ticket for the work & estimate

## Acceptance Criteria
- [ ] Research will reveal the possible nature of the issue
- [ ] Research will determine if it is possible for the behavior to be changed via the front-end code
- [ ] If the issue can be resolved in code, a new issue will be created and estimated.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by zacharymorel** [comment]
So @MarciMcGuireGCIO I am trying to reproduce this. I am using the VM provided by GCIO. I have not been able to reproduce it. 

Can you reproduce it today?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I cant reproduce it either now.  Maybe there was a glitch in the Matrix.  I'll close this and we can re-open if the need arises.
