### ISSUE TITLE
Technical discovery for VA.gov-wide Numbers

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28364]
## Issue Description
One of the Analytics's team's backlog items is to create a VA.gov-wide KPI dashboard. The advantages for creating this would include:
- providing a wide view of success for the entirety of VA.gov for VFS products to compare their products to
- automating OCTODE defined "Numbers" for VA CTO reporting & external facing audiences
- providing a wide view of VA.gov success that Platform Analytics & Insights can check our KPIs against

This issue is for technical discovery.

---
## Tasks
- [x] Define which metrics best apply to the OCTODE/VA "Numbers"
- [x] Technical discovery for if we can get the metrics
- [x] Document which metrics we can't get
- [x] Document how we would get the metrics that are unavailable
- [x] Technical discovery for where & how to pull in the metrics

## Acceptance Criteria
- [x] Platform Analytics & OCTODE understands which metrics line up with the VA Numbers, which metrics we can't get, and how to get the metrics that we can.

## Other resources
- [VA.gov Numbers & Notes Google Doc](https://docs.google.com/document/d/1KUVh6erRiybSAESDvOn2ICqRIO3oVWf_pKjd-UzE2Qc/edit#) - bolded are the OCTODE Numbers; [Github doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/strategy)
- [Monthly report iteration](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24741#issuecomment-893552469)
- [KPI Framework](https://vfs.atlassian.net/wiki/spaces/AT/pages/614531245/VA.gov+Analytics+-+KPI+Framework)

**Comment by joanneesteban** [comment]
https://www.va.gov/performance-dashboard/

**Comment by joanneesteban** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/performance-dashboard

**Comment by chloedotbrown** [comment]
**Work-in-progress:** [spreadsheet](https://docs.google.com/spreadsheets/d/1lJ52GHKDrsCp-N7tK5iFe5noWGqg3BX3yDALzkyv7RU/edit?usp=sharing) brainstorming possible metrics and data needs. Will continue to build out there for this sprint.

**Comment by chloedotbrown** [comment]
Technical discovery of [potential KPIs](https://docs.google.com/spreadsheets/d/1lJ52GHKDrsCp-N7tK5iFe5noWGqg3BX3yDALzkyv7RU/edit?usp=sharing) for OCTODE/VA Numbers is complete! 

Quick overview - the spreadsheet is currently sorted by which VA goal each metric is associated with (column A) and then the completeness of the data (column E). I've added information about related data sources already in Domo, what additional info would be needed, and estimated what kind of lift it would be to get it. We likely won't want to (or be able) to lock all of these down, so  I've added a checkboxes to mark which KPIs we'd want to prioritize. 

@joanneesteban have a look and let me know if there are any edits needed for this to meet the AC. Thanks!

**Comment by joanneesteban** [comment]
Ah, this is amazing! Thank you for the thoroughness and completing the technical discovery, @chloedotbrown! 

For moving forward, 
@thepipster Chloe added a column to the technical discovery to check off pursuing a data point. I've added checkmarks based off of the information that was researched, but please feel free to edit as necessary.  

- Sprint 59: new tickets for drafting a mock up (use whichever tool you're comfortable with!) + collect any necessary data
- Sprint 60: cont. any necessary data collection + begin build

**Comment by chloedotbrown** [comment]
@joanneesteban I've added the next round of notes to the "Data Needs" tab of the [discovery spreadsheet](https://docs.google.com/presentation/d/1DaE_NdhC2Z6v0LHKcLQ2LShNH9ZF0kuW52AKIIfHJvE/edit?usp=sharing). This takes only the KPIs that had been checked in the previous tab and expands on:

- what steps would need to be taken to complete that data
- who owns that action
- whether that action _not_ being taken would be a blocker for the KPI's inclusion
- any additional notes about KPI for it to be included in dashboard MVP

In general, I haven't included any metric that may have a blocker on the mockup (#28941), though I don't think any of these would be difficult to work into the design if we end up getting them. For the Analytics team, our next steps should be:

- [ ] Reach out to OCTODE for places where they own the data we'd need, likely for manual updates.
- [ ] Reach out to OCTODE for ideas to incentivize more PMs with Form products to fill out dashboard requests.
- [ ] Connect with Platform Service Design team for best way to connect to their survey data.
- [ ] Connect with Platform Call Center team about possibility of filtering their data for user satisfaction KPI.
- [ ] _(optional)_ Explore options for exporting more robust ForeSee data while we wait on Medallia.
- [ ] QA older Domo data sources.

**Comment by chloedotbrown** [comment]
Closing this ticket, as work will continue (and be updated) on ticket #30700.
