### ISSUE TITLE
Create page on Platform Website with instructions for 508 Office document review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28368]
## Issue Description
The VA 508 office provides a service for document review. Commonly, VFS teams will ask Platform for an accessibility review of a document. We would like to be able to direct VFS teams to this page so that they can take advantage of the service that the VA 508 Office provides.

---
## Tasks
- [x] Determine where on Platform Website this should live (Testing/Accessibility?)
- [x] Add instructions below from Trevor

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@1Copenut I already lost the instructions you shared. Can you please paste them here?

**Comment by 1Copenut** [comment]
Sure thing @shiragoodman 

1. On the VA Network, click on the YourIT! shortcut. Should open a browser and land on the home page.
1. In the search box, enter "508 audit request" and click on the top result. Top result should be "508 Accessibility Audit Request"
1. You'll get an input form to enter relevant data. At the bottom select "Documents" from the Product Type dropdown
1. Enter your 508 office contact. If you do not have a regular contact, ask the Product Support Team for a reference.
1. Upload the document from your machine. (May have to download it from the web first)
1. You should receive a confirmation email with your ticket number linked
1. Lead time is around 1-2 weeks generally, depending on the team's work load

**Comment by allison0034** [comment]
This is live. https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-508-office-document-review.1857913061.html
