### ISSUE TITLE
Bug - Domo isn't surfacing all Platform Website sources of traffic

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28375]
## Issue Description
To understand our documentation findability, we need to see if our customers are finding their documents through our Domo links and other referral links (i.e. Slack, Google, etc.). We know there should be referrals from Domo and direct links based on internal team interactions, but this information is not appearing on the [Top sources of traffic chart](https://va-gov.domo.com/page/514439234/kpis/details/1176923094).

We shouldn't add the new Analytics URLs on the Platform Website to the current dashboard, but we will also eventually want a larger referral visual for all of the Analytics URLs.

---
## Tasks
- [x] Research & document why the Domo and other referral links aren't being pulled into the Google Analytics & Domo datasets
- [ ] Add the data back into the datasets & update the Domo chart.

## Acceptance Criteria
- [ ] Platform Analytics & Insights can see our documentation referrals, including referrals external to the Platform Website such as Domo.

**Comment by joanneesteban** [comment]
This is a follow up from #26512

**Comment by bsmartin-ep** [comment]
@joanneesteban -

Looks like "Top Sources" is just previous page path.  We _do_ have the external referrer in a column called source.

https://va-gov.domo.com/page/514439234/kpis/details/698826492

Add this to the dashboard?

**Comment by joanneesteban** [comment]
This is awesome! Yes, please, let's add this to the dashboard. Thanks, @bsmartin-ep !

CC: @chloedotbrown

**Comment by chloedotbrown** [comment]
Hi! I've reconfigured [this card](https://va-gov.domo.com/page/514439234/kpis/details/1176923094) to show `source` rather than previous page. The last visual showed internal referrals, but they seemed to have all been just from _other_ Analytics pages on platform, which wasn't that useful. 

Let me know if anything needs to get tweaked or added back in - otherwise, I'll close this ticket EOD today!

**Comment by chloedotbrown** [comment]
Closing out!
