### ISSUE TITLE
Visualize Platform Website site search

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28372]
## Issue Description
Site search events are flowing into BigQuery & GA. We want to visualize this data to see if folks are searching for Analytics related documentation, and, if they are, what they are searching for and if they're able to find what they need.

---
## Tasks
- [x] Determine if we need to update the data source.
- [x] Connect the data to Domo
- [x] Update the Platform Analytics dashboard with this data.

## Acceptance Criteria
- [ ] Platform Analytics & Insights can understand what analytics-related documentation VFS teams are searching for so that we can optimize SEO.

**Comment by joanneesteban** [comment]
Keeping this in the backlog for now. @chloedotbrown I think this would go into our larger Analytics KPI dashboard instead of our dashboarding KPI dashboard.

**Comment by joanneesteban** [comment]
Follow up from #26512

**Comment by bsmartin-ep** [comment]
Turns out it was only a few min to add this to the dataset...

https://va-gov.domo.com/page/514439234

I'll defer to your judgement @chloedotbrown on how to ~~fix~~ visualize this...

![image](https://user-images.githubusercontent.com/62304138/128892893-cc531779-e48e-4281-83ca-c822dddbdc28.png)

**Comment by chloedotbrown** [comment]
Thanks, Brian!

@joanneesteban I've added this to the [Standardized KPI Dashboard](https://va-gov.domo.com/page/514439234) for now, since I do think it helps add context for some of the metrics. Would you like a copy/other version of this on the general [Analytics KPI](https://va-gov.domo.com/page/2132475398) dash as well? Let me know and I can add before closing ticket!

<img width="500" alt="Screen Shot 2021-08-10 at 5 02 40 PM" src="https://user-images.githubusercontent.com/45518242/128950802-302b23b8-b35b-4809-942a-530d6933e496.png">

**Comment by joanneesteban** [comment]
Fantastic! Thank you @bsmartin-ep & @chloedotbrown ! 

Yes, I think this should also live on the general Analytics KPI dash, but we can do that when we iterate on the general Analytics KPI dash. So feel free to close this ticket out!

**Comment by chloedotbrown** [comment]
Great! Looking forward to when that iteration project. But closing this ticket for now!
