### ISSUE TITLE
Technical discovery for Platform Website "opt out"

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28376]
## Issue Description
Right now, the Platform Website tracks Platform crew team members & other Platform Website contributors as users. Mimicking the ["Analytics Opt-out" for VA.gov](https://www.va.gov/analytics-opt-out.html), we would like to separate website contributors' interactions from intended users' interactions. This way, we do not count contributors use as part of our success rates, or influence our analysis of user interactions based on our own use.

---
## Tasks
- [ ] Determine & document how we might be able remove VSP and/or Platform Analytics team members from Platform Website tracking
- [ ] Recommend the best solution
- [ ] Appropriate team members "opt out" of tracking

## Acceptance Criteria
- [ ] We can separate Platform team members' use of the Platform Website from its intended users.

**Comment by joanneesteban** [comment]
This is a continuation for #26512

**Comment by joanneesteban** [comment]
Platform Website: https://depo-platform-documentation.scrollhelp.site/

**Comment by bsmartin-ep** [comment]
@joanneesteban -

GTM workspace for these changes:
https://tagmanager.google.com/#/container/accounts/144676348/containers/30787921/workspaces/10

I added a URL query variable called `internal-user-opt-out` to be true|false on depo-platform-documentation.scrollhelp.site.  So anything like `https://depo-platform-documentation.scrollhelp.site/?internal-user-opt-out=true`. 

If we want to match the www opt out, we would attach this to a user-scoped CD.  Point-forward, these users' data will be filtered out of GA (except for the unfiltered view).  We can filter this out in GA or BQ retroactively by looking for `Internal User != true`, but we would need to add it to our BQ queries (and any GA report we build).

 A value of `false` will (point- forward) start recording again.

**Comment by joanneesteban** [comment]
Thanks for making the workspace and those changes, @bsmartin-ep ! Let's move forward to attaching it to a user-scoped CD. We'll want to filter out retroactively as well so that we have baseline numbers.
