### ISSUE TITLE
Logout flows should redirect users back to previous page

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28394]
## Issue Description
When a user's session times out or a user signs out from VA.gov they are redirected to the homepage instead of the page they were previously on.  Some research is needed to find out who owns (Vets API or IAM) the redirect and if a redirect query parameter can be sent.

---
## Tasks
- [x] Research who owns the redirect to the homepage
- [x] Talk with Joe about the security concerns with dumping users at previously authenticated locations.
- [ ] Modify the SessionTimeoutModal.jsx file
- [ ] Modify the logout functionality to pass a query parameter of previous URL
- [ ] Write unit tests to ensure logout functionality works as intended

## Acceptance Criteria
- [ ] Signing out without passing a query parameter redirects a user to the homepage
- [ ] Signing out with a query parameter (current URL) redirects a user to the same URL before signing out
- [ ] Logout unit tests work as expected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Research:
So following the entire logout flow it goes:

1. (FE) `logout` method is called either by signing out
2. (FE) `logout` method calls the `redirect` method with the `sessionTypeUrl` which generates a URL for the vets-api to consume. Endpoint for logout will be `v1/sessions/slo/new`
3. (BE) `sessions_controller/v1` handles the type (`slo`) and resets the session, generates the url from ssoe_slo_url (defined in settings which is eauth environment)
4. (eAuth) completes removing session & cookies that then redirects to the VA.gov homepage
5. (FE) user lands on VA.gov homepage

Idea #1
So there might be a way to copy what the login method does and saves the current URL temporarily to the session/cookie storage.  After a sent to the homepage after signing out we can redirect them to the original page they were on (I'd rather not do this because it will flash which could be jarring for some users)

Idea #2
We send the current URL as a query parameter when logging out, passes that url to the eauth to redirect to whichever page the user was on before signing out/session expired. (Requires modifications in both the vets-api and eauth team).

**Comment by AGarcia-Clarity** [comment]
Won't fix. The redirect URL needs to be static due to the authentication system we have in place.  Currently both eAuth and SiS cannot have varied URLs when redirecting.
