### ISSUE TITLE
Alerting - Create a template for the message that gets sent by Datadog

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28405]
## Description 
Create a template for the message that gets sent by Datadog. This should also give us a good idea of what alerts will look like and help us to build rulesets in PagerDuty

## Resources 

[Getting Started with Monitors](https://docs.datadoghq.com/getting_started/monitors/)
[Notifications](https://docs.datadoghq.com/monitors/notifications/?tab=is_alert#conditional-variables) 
Existing message example [HERE](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/k8s.yaml ) 

## Tasks

- [ ] Create conditionals in the Datadog message that determine whether to send to a Slack channel or to PagerDuty
  - the messages that get sent to Slack can be pretty freeform w/ alert message (default are pretty decent)
  - the messages that get sent to PagerDuty should be formatted so that they can be easily regex’d for PagerDuty rulesets
- [ ] Create a #-pagerduty-integrations-temp for validation of PD conditionals, we should 
- [ ] Send alerts to above channel for now until we feel comfortable sending them to PD

## Definition of Done
Working message template for sending alerts from Datadog for various services.

**Comment by rwilliams-oddball** [comment]
Title
{{service.name}} < Descriptive text about service> 


{{#is_recovery}}
Device {{device.name}} has dropped below 90% usage.
{{/is_recovery}} @slack-{{team.name}}-alerts
{{#is_warning}}
Device {{device.name}} {{last_triggered_at}} has less than 10% free space.
{{/is_warning}} @slack-{{team.name}}-alerts
{{#is_alert}}
Device {{device.name}} {{last_triggered_at}} is expected to run out of space in 48 hours.
{{/is_alert}} @pagerduty-{{serviceName}}



Other Possibilities 
@{{region.name}}-datatdog-alerts@example.com
@webhook-{{availability.zone}}
@sns-{{service.name}}

**Comment by rwilliams-oddball** [comment]
Title
{{service.name}} < Descriptive text about service> 


{{#is_warning}}
  <WARNING_MESSAGE_TEXT> <@-NOTIFICATION>
{{/is_warning}}

{{#is_alert}}
  <ALERT_MESSAGE_TEXT> <@-NOTIFICATION>
{{/is_alert}}

{{#is_match "<TAG_VARIABLE>.name" "<COMPARISON_STRING>"}}
  This displays if <COMPARISON_STRING> is included in <TAG_VARIABLE>.
{{/is_match}}

{{#is_exact_match "<TAG_VARIABLE>.name" "<COMPARISON_STRING>"}}
  This displays if <COMPARISON_STRING> is exactly <TAG_VARIABLE>.
{{/is_exact_match}}

{{#is_recovery}}
  <RECOVERY_MESSAGE_TEXT> <@-NOTIFICATION>
{{/is_recovery}}

**Comment by dginther** [comment]
These look great! Exactly what I was thinking. We may have to work on the is_exact_match for production depending on what we're looking at, but I think this is a great start.
