### ISSUE TITLE
Ensure authenticated users are persisted across teamsites

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28407]
## Issue Description
When an authenticated user navigates to an **external team-site*** from VA.gov, the authenticated state is not persisted.  When that same user navigates back to VA.gov they are automatically signed out and redirected from the homepage.  We want to ensure the authenticated state will persist across VA.gov so that users will not face frustration being auto-logged out and having to reauthenticate each time.

I think this issue can be resolved by updating the CORS policy to include the external teamsites and asking teamsites to call the `v0/user` endpoint to ensure the authenticated state.

**External team-site** - a collection of subdomain VA.gov websites with only the header & footer from vets-website injected (example: https://www.veteranshealthlibrary.va.gov/)

---
## Tasks
- [ ] Research and document external team-sites.
- [ ] Update CORS policy to include team-sites (and their subsidiaries if necessary)
- [ ] Research and modify the site-wide header to persist authenticated state

## Acceptance Criteria
- [ ] Authenticated state is persisted across team-sites
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Update
According to the [Slack thread in the vsa-public-websites](https://dsva.slack.com/archives/C52CL1PKQ/p1628087502058700) channel the injected header will be up-to-date once each teamsite refreshes/redeploys their site.  Resolving the CORS issue on these pages should allow a call to the `feature_toggles` and `v0/user` endpoints.

**Comment by AGarcia-Clarity** [comment]
VSA Public Teams need to fix CORS issues. Closing.
