### ISSUE TITLE
Authenticated users should navigate to specific tools without 2 clicks

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28402]
#### **Background**
On a static page (example claim status), a user is asked to click on a button to sign in to get access to an authenticated tool. After completing the authentication flow they are redirected to the static page (claim status) and are required again to click on a button to be navigated to the authenticated tool.

There are certain scenarios in which an authenticated user will see a flash of the static page (ex claim status) before being redirected to the authenticated tool.

#### **Asks**
1. We want to prevent users from having to click twice to get to an authenticated tool after logging in (a customRedirectURL should be added to allow users to navigate directly to the authenticated tool after signing in **Identity team**)
2. We want to reduce the flash of static pages for authenticated users redirecting to authenticated tools (I think a the RequiredLoginView will need a modification or possibly modifying redirects of individual apps across VA.gov)

---
## Tasks
- [ ] Modify the current login method to add a customRedirectURL property
- [ ] Research the RequiredLoginView & individual apps to see if overriding the redirect is possible
- [ ] Work with applications teams for redirects

## Acceptance Criteria
- [ ] Users no longer have to click twice to get to an authenticated tool
- [ ] Authenticated users do not see flashes of static pages before redirecting to authenticated tools
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
