### ISSUE TITLE
HLR: Change time window selection

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28415]
## Description

In the updated Higher-Level Review form, the available time slots for an informal conference have changed to:

- 8:00 a.m. to 12:00 p.m. ET, and
- 12:00 p.m. to 4:30 p.m. ET

Since there is a change from 4 to 2 time choices, we will need to await the final design which may maintain the two `<select>` elements, or change the choices to a checkbox group.

## Tasks

- [ ] Change the informal conference times
- [ ] Update the form elements as directed

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
