### ISSUE TITLE
Create a public roster of VFS and Platform teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28411]
## Issue Description
The [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) is a spreadsheet maintained by Platform Product Support. It is challenging to keep up to date because the onboarding/offboarding process is unreliable. It is also not publicly accessible, so unless a VFS team knows it exists, they cannot access it without asking (with lots of cross team work occurring recently, this concern has increasing importance). Lastly, the VFS Team Roster only includes VFS teams and does not include Platform teams. VFS teams have asked if there is a public-facing Platform roster and there is not.

The output of this ticket may impact the plan for implementation of a new Platform Orientation via ticket #13709.

---
## Tasks
- [ ] Reaching out to C&IA team to determine where on Platform Website and/or Confluence this should live
- [ ] Get Platform roster from Nancy
- [ ] determine design of roster and/or org charts (MVP: keep it as simple as possible)

## Acceptance Criteria
- [ ] VFS Roster information and Platform team information is available and accessible from Platform Website OR Confluence.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
[VFS roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
[VSP org chart](https://docs.google.com/presentation/d/1ktf_Gx8UJGW9sJiIgyNCWuCe16zMkjjlnZ1mXEEZQFQ/edit#slide=id.g9a46fe9299_0_0)

Check team of teams slides that show crews

**Comment by shiragoodman** [comment]
Atlas has been created. This ticket no longer falls under Governance responsibility.
