### ISSUE TITLE
HLR: Add SOC/SSOC opt-in

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28416]
## Description

In the updated Higher-Level Review form, an opt-in to the new decision path is to be added. This opt-in is required, but does not need to be selected in order to proceed with submission (according to Lighthouse).

For now this page will _always_ show. In the future this page will only show when one or more issues include an SOC date indicating that it is a legacy issue.

## Tasks

- [ ] Add opt-in checkbox or yes/no radio based on pending design
- [ ] Put this page behind the version 2 feature flag

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
