### ISSUE TITLE
HLR: Update representative info page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28414]
## Description

In the updated Higher-Level Review form, the representative name is split into a first & last name field as well as inclusion of an optional email address.

## Tasks

- [ ] Split representative "name" input into "First name" and "Last name" fields
- [ ] Add representative email input field
- [ ] Only show/submit the above behind a version 2 feature flag

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
