### ISSUE TITLE
[Tech-Debt] Update LGBTQ+ and Suicide pages with new updates from SOT VISN-23 [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28426]
## User Story
As a VHA Digital Media web manager, the national changes need to be implemented prior to Dual state or full production launches, so the systems are updated adequetly prior to the redirect.

## Goal
Remove tech-debt prior to full production

## Resources - Tools - Documentation
TBD

## Tasks
UPdate LGBT with LGBTQ+ and Suicide pages with new content and organize page correctly.
- [x] Update Suicide pages with correct format order and new content
- [x] Change out LGBT with newly authorized LGBTQ+ in locations provided by Content.
_
**Complete for the following locations**
- [x] VA Black Hills health care
- [x] VA Central Iowa health care
- [x] VA Fargo health care
- [x] VA Iowa City health care
- [x] VA Minneapolis health care
- [x] VA Nebraska-Western Iowa health care
- [x] VA Sioux Falls health care
- [x] VA St Cloud health care

## Acceptance Criteria
- [x] Suicide pages are updated and if caregiver is not listed on page it is reported in Support channel.
- [x] LGBTQ+ pages are updated and if caregiver is not listed on page it is reported in Support channel.

**Comment by bcastoe** [comment]
#28426 Update LGBTQ+ and Suicide pages with new updates from SOT VISN-23 [BA] - Completed and moved to Validate; (1) Suicide pages checked and in correct format order (2) LGBTQ+ Detail, System and Facility pages updated (3) Caregiver listed for both Suicide and LGBTQ+ - only reported no suicide staff profile listed for Black Hills
