### ISSUE TITLE
[Analytics] Remove Duplicate Staff Profiles across multiple VISNs

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28428]
## Story
As a CMS editor, I need all duplicate staff profiles to be removed so there is no confusion on who is assigned to what location and that there are not multiple nodes with the same information.

## Goal 
Remove all duplicate accounts including those working across VISNs.

## TASK
Review all staff profiles within VISN and throughout the VAMC facilities and:
- [ ] Remove duplicate staff profiles
- [ ] Assure staff profiles are assigned to the correct system

## Acceptance Criteria
- [ ] All duplicate staff profiles have been removed.

**Comment by bcastoe** [comment]
Brenda has researched all VISNs for duplicate staff profiles and has listed them in a spreadsheet.  Some research has been conducted for said duplicate staff profiles.

**Comment by bcastoe** [comment]
I have provided all of my findings for this story.  Since I  will be on PTO for the rest of this sprint I have removed my name from the two listed for assignees.
