### ISSUE TITLE
[Analytics] Sanity check on content wording for Suicide and LGBTQ+ pages [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28427]
## User Story
As a VHA Digital Media web manager, the national changes need to be implemented prior to Dual state or full production launches, so the systems are updated adequately prior to the redirect.

## Goal
Remove tech-debt prior to full production

## Resources - Tools - Documentation
TBD

## TASKS
- [x] Confirm that all content wording matches new Suicide content 
- [x] Confirm that LGBTQ+ content matches new content provided by Content team.

## Acceptance criteria
- [ ] All systems in VISNs have been double checked for content.

**Comment by bcastoe** [comment]
#28427 - Sanity check on content wording for Suicide and LGBTQ+ pages - completed and moved to validate
