### ISSUE TITLE
Remove repetitive text in smaller font underneath intro on opt out of information sharing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28435]
## Issue Description
On the [opt out of sharing education benefits information](https://www.va.gov/education/opt-out-information-sharing/) page, we have smaller text underneath the intro that is just repeating the same information. This should be removed. 

![Screen Shot 2021-08-09 at 12.22.02 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/9de309e9-da07-416a-9a18-4275e3376456)

## Tasks
- [x] Remove smaller text under intro
- [x] Review and publish

## Acceptance Criteria
- [x] Smaller repetitive text no longer showing on live page

**Comment by RLHecht** [comment]
Change is live on site. Closing ticket. FYSA @bethpottsVADEPO
