### ISSUE TITLE
[Design] Notification Preferences: Experimental Design Submission/Review 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28433]
## Background
Compile documentation for notification preferences design with radio buttons to present to the design system council on 8/13.

## Tasks
- [x] Compile documentation & submit ticket
- [x] Present to design council
- [x] Publish documentation on design.va.gov

**Comment by andaleliz** [comment]
published 8/17
