### ISSUE TITLE
Va.gov sign in/ Login.gov Synthesis

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#28445]
## Issue Description
Create a “topline summary” that captures key themes discussed coming out of the user sessions and debriefs.

---
## Tasks
- [x] Review notes from Perigean and observers
- [x] Categorize themes 
- [x] Begin toppling summary
- [x] Review with PM and revise as needed

## Acceptance Criteria
- [x] Use supporting quotes from participants
- [x] Affinity mapping

**Comment by APorter-Clarity** [comment]
[https://app.zenhub.com/files/133843125/d3dc54d8-5419-4d57-8777-0fd9de224f29/download](https://app.zenhub.com/files/133843125/d3dc54d8-5419-4d57-8777-0fd9de224f29/download)

**Comment by APorter-Clarity** [comment]
[Affinity Mapping on Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1629744417400/ea413f9ddf89a10be41c90440d95e3ce423b10db?sender=ue8da07808969ffbb6a970518)
