### ISSUE TITLE
Identify what new 5103 content needs to be added to existing tier 1 Veterans Pension FDC page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#28446]
## Issue Description
We need to account for, on VA.gov, all the Veterans Pension evidence and FDC 5103 info sent to us from Pension SMEs. Short-term, we'll be adding additional content to our existing page in tier 1: 
https://www.va.gov/pension/how-to-apply/fully-developed-claim/

Initially we thought we might create separate R&S pages for Evidence and FDC--as we're doing for Survivors Pension and Accrued benefits pages. To expedite getting required 5103 content online, we won't move forward with those pages. But we can use the content on them for the sake of completing this ticket!

The task here is to compare the existing tier 1 page mentioned above to what's on these 3 mocked up pages and identify what's missing from the existing tier 1 page:
http://preview-prod.vfs.va.gov/preview?nodeId=27770
http://preview-prod.vfs.va.gov/preview?nodeId=28032
http://preview-prod.vfs.va.gov/preview?nodeId=32889

Things are worded and organized differently, so it's an exercise in identifying the substantively matching content, not exact word-for-word matching. 

---
## Tasks
- [x] What content from the 3 draft pages listed above needs to be added to the tier 1 page?
- [x] Either upload a Word doc to this ticket that lists what's missing or put the content right in a new comment.

## Acceptance Criteria
- [ ] All the updated or new 5103 content sent to us by SMEs is accounted for in our tier 1 page.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the Word doc with what's missing from the tier 1 page that is on the different R&S pages. Let me know if you want me to walk through it with you.

[https://app.zenhub.com/files/133843125/0e53c5fe-462b-43f1-931d-27789a8075a2/download](https://app.zenhub.com/files/133843125/0e53c5fe-462b-43f1-931d-27789a8075a2/download)

**Comment by RLHecht** [comment]
Moving to Icebox until the Pension team gets back to us with next steps.

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
