### ISSUE TITLE
Public Websites: Sprint 54 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28443]
## Sprint 54 Priorities (HRT Mobile Design / Research Elements / Home Page Banner Initiative (Short Term) / Tech-debt & In-take Requests / CLP - VEO Action Center)
1.  Harassment Reporting Tool (HRT) Flow/Design (Intro Page/Form) and Wireframes/Design Mockups, Finalize Research Needs (Research/Design/FE), Sync FE build efforts and Next Steps (VSP Design Intent). 
2. Home Page Banner - POC proposed, work with CMS and determine FE requirements for implementation 
3. Campaign Landing Page - VEO Veteran Action Center CLP (Support Launch Strategy)
4. Discovery - Research projects for HRT, DT and Search
5. Focus on Priority InTake and 'Tech-Debt' items from backlog - Mission to clear out tech-debt and mitigate risk
6. Plan future initiatives:  [New Mobile Header](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md)   

### Capacity Planning: PTO/Holiday's
Brian: 1
Kelson: 2
Ryan: .5
Cassandra: 0
Cindy: 5

### Harassment Reporting Tool (HRT) initiative 
- [ ] [EPIC] ORDMI Online Harassment Reporting Page & Tool MVP #24883
- [x] Harassment Reporting Tool [Mobile Screens Mockup] #28434 (Priority Path) 
- [x] [Design] Harassment Reporting Tool [Form Mockup] #26765
- [x] [Design] Harassment Reporting Tool [Introduction Page mockup] #26477
- [ ] [Discovery] Harassment Reporting Tool - Content Copy Review #27438
- [ ] IA Request [Public Websites, Harassment Reporting Tool (HRT)] #27911
- [x] [Discovery] Trauma Design Best Practices for HRT initiative #28034
#### HRT Collaboration Cycle Checkpoints: 
- [x] [PM] Collaboration Cycle Kickoff [Public Website, ORDMI Harassment Reporting Tool] #25567
- [x] Design intent [Public Website Team - Harassment Reporting Tool (HRT)] #27381
**--> Next Step** - Content Copy + Harden Mobile/DT designs.  Research Plan Prep / Mid Point Review (check on Low Risk One time Auth.. LoROTA capability)

### Home Page Banner Alert - Drupal/CMS Migration 
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page-banner/product-outline.md); Super EPIC: Improve Homepage Alert Banner Publishing Process #26991; Epic (Short Term): Home Page Banner Updates (Short Term Actions) #27852
- [x] POC for the banners client-side implementation #28515
- [ ] [FE] Migrate Homepage Banner to Drupal #25038 (Pending CMS Discussion)
- [ ] Implement Analytics Tracking - Dismissible VA.gov Alert Banner #28295
- [x] Homepage Banner Migration - Add support for banner types (e.g. warning/info/etc.) #28611
- [x] Homepage Banner Migration - Add support for max 3 banners in banners.drupal.liquid #28612
- [x] Homepage Banner Migration - Update isBannerVisible liquid filter to support trailing * and ! regex #28614
**--> Next Step** - Create tickets for solutioning post CMS discussion. 

### Homepage / Banner Requests
- [ ] June Home Page Link Requests from VA #26276
**--> Next Step** - Pending follow up from PO. 

### New VA.gov Mobile Header
- [ ] [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md)
- [ ] Analytics Feature Request for New Mobile Header #28225 (FU / Determine Path)
- [ ] [Discovery] Technical Analysis for New Mobile Header #28288
- [ ] Collaboration Cycle Kickoff [Public Websites, New VA.gov Mobile Header] #28784
**--> Next Step** - Follow up on Analytics Ticket, push CC Kickoff ticket this sprint. 

### Campaign Landing Page MVP 1.0
[EPIC] Campaign Landing Page 1.0 Features #25772
- [ ] [Campaign Landing Page Production Launch]- Veterans Experience Action Center #27515
- [ ] Analytics Process Hardened (Stakeholder Reporting)
**--> Next Step** - Follow up with VEO on publication of CLP-VEAC, work with analytics to add to DOMO dashboard for tracking. 

### Discovery (Research & Design)
- [ ] [Design] Search UI Consistency: Document Search Design Pattern for Design System #24597
- [ ] [Research] Draft research plan & convo guide: Harassment Reporting Tool (HRT) #26824 **(Backlog)**

### Redirect Requests
- [x] [FE] Redirect Request - Vet Center MVP pages #25885 (Waiting on "Greenlight" from Facilities team)
**--> Next Step -** @Dave wants to break up the ticket and release all but 4x facilities and place those on a backend ticket for future add.  PR is already been updated in support. 
- [x] Redirect Request [JULY 15] - Find a VA Form #26299 (Reopened- working with Kevin Reid to identify the teamsite issue). 
**--> Next Step -**@Jen Lee is following up with Kevin Reid, and is also casting a wider net to determine issue with Find VA Form Redirect issue. 

### Intake Request - Techical Debt
- [ ] [COGNITION]: Disability Calculator - Can we mention the expected data format in on-page instructions? #1045
- [x] [Bug] VA accordion web component focus/scroll issue #28506
- [ ] Accessibility Feedback for Staging Review | Language Assistance and Resources | #25592
- [x] Link TTY: 711 number in footer and right rail of hub landing pages #18151
- [ ] 508-defect-2 [HEADINGS]: Headings should be logically ordered on the VA.gov homepage #27976
- [ ] [MOTION/COGNITION]: Auto-scrolling problematic for users with motion sensitivity or cognitive considerations #6461
- [ ] [FE/Content] Explore and revisit Visual Regression Testing to aid in modifications to CMS templates and style #18869
- [ ] sitewide, CMS - 508-defect-2 [FOCUS MGMT]: Ensure focus moves when same page links are activated (IE11) #15244
- [ ] 508-defect-2, sitewide [FOCUS]: Mobile menu loses focus when expanded and collapsed #25661
- [ ] [FE] 508-defect-2 [SCREENREADER]: Search fields should have the landmark role="search" #26360
- [ ] 508-defect-2 [SCREENREADER]: Search fields should have the landmark role="search" #26360
- [ ] 508-defect-2 [FOCUS]: Back to top button's focus halo MUST be visible on Safari #25001
- [ ] Back to top component is not displayed in IE-11 #25103

### Future Sprint Efforts (Pull List - Backlog)

<details><summary>Collab Cycle Tracking Template</summary>

### 
# Collab Cycle Tasks
After copying this template into your new Sprint Priority issue, keep the Collab Cycle tasks needed for this sprint and delete the rest.
- [VSP Collaboration Cycle Image](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [VSP Collaboration Cycle Requirements/Info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)
- [Change Release Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/decision-tools/DRAFT_Change_Checklist.md)

## Define
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)

## Discover

- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
- [ ]  **[Discover] IA Request** - #(ticket)
### [Submit Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### [Privacy and security review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)
- [ ] Submit ticket for review: Use Privacy and Security Review template in va.gov-team-sensitive repository 
- [ ] Provide artifacts at least 48 hours prior to the review
- [ ] Schedule/hold Privacy and Security Review
- [ ] Complete any tickets that came out of Privacy/Security review (if any)

### [Submit Analytics **QA** request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### Release Plan
- [ ] Create UAT plan
- [UAT Template](www.google.com)*
- [UAT Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/UAT/profile-research-plan-UAT.md)
- [ ] Complete Release Plan 
- [Release Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)

#### QA
- QA Staging review scheduling: Have artifacts in and tag Tze 2 weeks in advance from the Staging Review. This makes it possible for Tze to get to it w/o being rushed. When you schedule the Staging review, also tag Tze in Slack.
- [ ] Create list of staging users
- [ ] Create list of use cases [see [Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)] and submit to Tze so he can create test cases/regression tests
- [ ] Create “Coverage for references report” OR a add a link to the Epic for the product you are releasing  

#### Accessibility
- [ ] Complete the [required accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Complete QA/Accessibility tickets that came out of Staging review prep (if any)

### Conduct Internal QA Session
It is beneficial to conduct an internal QA session prior to actual QA. This consists of the team allocating 1 hour to meet look for bugs and or issues with the product. This is beneficial because the engineers and designers have in-depth knowledge of potential problem areas that QA might not have the time/resources to look into.
- [ ] Internal QA has been conducted

#### List of issues coming out of internal QA session:
- [ ] Issue name #00000
- [ ] All issues that came from internal QA have been completed

### [Request Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Provide all required artifacts in the request
- [ ] Schedule/hold staging review
- [ ] Complete all IA feedback tickets
- [ ] Complete all Accessibility feedback tickets
- [ ] Complete all QA feedback tickets
- [ ] Complete all Content feedback tickets
- [ ] Complete all Design feedback tickets

### [Contact Center review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#contact-center-review)
- [ ] Create Product guide
      - [Product Guide example]()
- [ ] Create Product video
- [ ] Submit request for Contact Center Review
- [ ] Complete Contact Center Review

### Analytics follow up on Staging
- [ ] Analytics are complete
- [ ] Frontend has implemented analytics data layer changes
- [ ] Dashboards have been created and link directly to your OKR/KPI's
- [ ] Review dashboard(s) with Analytics team to ensure understanding of all metrics/calculations
- [ ] Dashboards are finalized/work correctly

### Preparing/Updating all necessary supporting documentation for your product
- [ ] API calls and dependent systems [Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account#api-calls-and-dependent-systems)
- [ ] Update product outline with updated release information and links to analytics dashboards [Product Outline Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)

#### Ex:(re-directs, changes to content, changes that affect other teams) 
- [ ] Create issues in Github for changes that will take place, add dates, and tag relevant people/teams (re-directs, content changes, UI changes, etc)
- [ ] Update dates/parties accordingly as launch approaches and dates are finalized

### UAT
- [ ] Conduct UAT Go/No-Go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/uat-go-nogo.md)
- [ ] UAT has been conducted
- [ ] Issues have been logged/added to the Release Plan. [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)
- [ ] Launch-Critical UAT issues have been resolved

### Phased Launch (depends on phases in your launch)*
- [ ] Conduct Launch Go/No-Go meeting
-  [Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/go-no-go-meeting-template.md)
- Invite your entire team, analytics, platform team members, etc
- [ ] Resolve any issues (if applicable)
- [ ] Continue with phased launch, resolving issues if they arise, monitoring analytics daily

#### Go-live to 100% of traffic
- [ ] Conduct Go-live go/no go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Launch%20go%20no-go.md)
- [ ] Resolve issues (if applicable)
- [ ] Launch to 100% of users

## Monitoring
- [ ] Monitor analytics daily to ensure there are no abnormalities/errors
- [ ] Resolve any issues (if applicable)

## Post Launch
- [ ] Fill in post-launch metrics in the Release Plan
- [ ] Remove old code (if applicable)

### [Full Accessibility and 508 Office Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#full-accessibility-and-508-office-audit)
- [ ] Request [Full 508/Accessibility Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)
- [ ] Complete required scans/tests
- [ ] Make required changes (if any)

### [Post Launch Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#post-launch-check-in)
- [ ] Update Release Plan with "post-launch questions" completed
- [ ] Schedule/Hold check-in
- [ ] Measure results against OKRs
- [ ] Prepare next steps and potential iterations if applicable

# Feedback from other teams

**Platform feedback:**
- The biggest blocker to a successful launch would be not implementing platform feedback earlier in the process. 
- It would be ideal to implement the feedback prior to the staging review. 
- More frequent communication of changes/issues via the slack channel would be beneficial.

**Accessibility feedback:**
- Include accessibility in design syncs, design-intent review, and anytime large changes are made.
- More frequent communication with Accessibility (ex: Biweekly accessibility meetings)
- For individual meeting/mini reviews use this [GH template](Enter link to template)
- Have an "Engineering intent review" and include accessibility (in addition to design intent review).

**PM Feedback:**
- Update Collaboration Tracker
- Add time estimates maybe
- how to roll this out
- put in epic format?

</details>

<details><summary>Kanban Board Template</summary>

### 
# Kanban Board
_Please select a ticket and include [WIP - [NAME]] next to the ticket that is being worked._  Pick up tickets by priority on the `To Do ` section to begin and move ticket through kanban workflow until `Done`. Please include resolution steps on tickets along with instructions if for some reason you are unable to complete the ticket during this sprint.  
Please tag <PM> on tickets when moved to **Done** section for validation and closeout.  Please connect if you have any questions or concerns in the interim.  Welcome to **VFS team** (for this sprint) we're excited to have the help.  

<details> 

<summary> TO DO </summary>

</details>

<details> 

<summary> ON-GOING </summary>

- [ ] [FE] <Discription> #174XX (WIP - Name)

</details>

<details> 

<summary> DONE </summary>

- [x] [FE]<Discription> #174XX (Validate - Name)

**Comment by brianalloyd** [comment]
Sprint 54 ended.
