### ISSUE TITLE
[DESIGN] VAMC page design for traveling mobile clinics

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28450]
## Issue Description
Following the discovery effort, it was recommended that only MMUs acting as traveling clinics should have dedicated VAMC pages. The information needed for Veterans is slightly different for this type of facility compared to standard brick and mortar locations and the design needs to be adapted for this purpose. 

**VAMC roll-outs are blocked for the subset of systems with this type of MMU, pending this iteration.**

---
## Tasks
Based on the [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-vha-mobile-redesign/discovery/research-findings.md), [synthesis and mockup mural](https://app.mural.co/t/vsa8243/m/vsa8243/1627038564401/bdd84c5da65e1000f7d3d2f2d365d03839a1466e?sender=michellemiddaugh9063):

- [ ] Determine the navigational flow for a Veteran viewing a health care system site to learn about the availability of services offered via mobile clinic 
- [ ] Create mobile first design specs for pages impacted in that flow (ie: event listing, event details, service accordions, etc)
- [ ] Call out important editorial considerations for collaboration with CMS

## Acceptance Criteria
- [ ] Mobile first design spec ready for front end development and CMS collaboration

**Comment by lildziner** [comment]
First pass design concepts that were presented in design intent can be found in this [mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1627038564401/bdd84c5da65e1000f7d3d2f2d365d03839a1466e?wid=0-1629379690376&outline=open).
