### ISSUE TITLE
[FE] My VA: Delete messaging-helpers.js if we can

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#28459]
Are we using the code in this file at all? We should delete anything the we can. https://github.com/department-of-veterans-affairs/vets-website/blob/a09f44760ec899895da61d7d098796871f7c9e89/src/applications/personalization/dashboard/tests/messaging-helpers.js

## Tasks
- [ ] Determine if this is needed at all
- [ ] If messaging-helpers.js are not needed, remove them
- [ ] If these are needed or we can't remove them, note as such in the ticket and close this ticket

## Acceptance Criteria
- [ ] messaging-helpers.js are removed (if determined they are not needed)

## Validation
**- Who can validate this ticket? (FE, BE, Design, PM)?** FE or BE dev
**- How can this work be validated?** confirm in code that messaging-helpers.js are removed

**Comment by tmitchellgcio** [comment]
Good to close. This is a necessary file
