### ISSUE TITLE
[MCP - Usability Recommendation] Referred charges discovery work

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#28468]
## Issue Description
When investigating the referred charges for a previous feedback ticket, we found that the work was much more complex than we thought and would require additional discovery and technical work with VA and Treasury SMEs. 

---
## Tasks
- [ ] Compile outstanding business process questions to be answered
- [ ] Get answers to outstanding questions asynch or synchronously
- [ ] Document findings in GH and attach here

## Acceptance Criteria
- [ ] Findings documented in GH and attached here

**Comment by denisecoveyduc** [comment]
@denisecoveyduc  sync with Jill on referred charges information.

**Comment by denisecoveyduc** [comment]
In discussions, during backlog refinement we have identified that this ticket is specifically related to debts that have been referred to treasury. In recent conversations with the lighthouse team this information is expected to be added tot he health API however @denisecoveyduc will connect with the DMC to verify this information can/should be shared in this way. For now I will close this ticket as we will revisit this as we explore how the user experience will change in light of the new information we are collecting from the corporate data warehouse (CDW). 

For UX team awareness we are seeking to get two pieces of information to be incorporated into the user experience. 

- **Payment information on medical copay–** (Understanding of when Veteran makes a payment (incremental or full) on medical copay
- **Status of a medical copay debt –** (Understanding when a debt has been suspended/ referred to treasury/ put on a repayment plan)
FYSA @mgleo @josephrlee  @charlottecesana @HeatherRienks @Tom-Davis
