### ISSUE TITLE
Lo-fi wireframe iterations for Doms and CLCs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28462]
## Issue Description
We began Lo-fi wireframes/designs for VAMC CLCs in #27810 and VAMC Doms in #27809. This issue is to iterate on those designs slightly. 

## Problems to solve
If we consider these facilities to be along the spectrum of care for a particular concern/diagnosis, how can we best represent the most relevant/meaningful information? 

For example, if a Veteran wants to know the options available for mental health, substance use or PTSD services, it might make sense to include the levels of care which are available at a system as part of the "Care we provide at VA health care system" area within a service accordion. 
- Outpatient services
- Residential services
- Inpatient services 

**Questions**

- How would a Veteran learn more about the residential or inpatient service options? 
  - Should we represent the Dom or CLC as a program? 
  - Service within another facility? 
  - Facility with a page of its own?
- What do Veterans need to know about residential or inpatient service options?
- What are the top tasks associated with Doms and CLCs?

Examples of CLCs and Doms which are not in VAST:
- VA Puget Sound Health Care System's Mental Health Residential Rehabilitation Program
  - not a dedicated location on the [modernized page](https://www.va.gov/puget-sound-health-care/locations/) yet has this [legacy page](https://www.pugetsound.va.gov/pressreleases/VA_Puget_Sound.asp)
- Pittsburgh's Compensated Work Therapy program is represented inside the service accordion

---
## Tasks
- [x] Evaluate the Program page option by reviewing example program pages, such as 
       - [Pittsburgh Surgery services](https://www.va.gov/pittsburgh-health-care/health-services/surgery-service/)
       - [Pittsburgh Intensive rehab program](https://www.va.gov/pittsburgh-health-care/programs/intensive-rehab-program/)
       - [Pittsburgh Interdisciplinary Pain Rehab program](https://www.va.gov/pittsburgh-health-care/programs/interdisciplinary-pain-rehabilitation-program/)
- [x] Evaluate the option of presenting a facility as a service, such as 
      - [Pittsburgh's Compensated Work Therapy program](https://www.va.gov/pittsburgh-health-care/health-services/)- presented inside the Vocational rehabilitation and employment program service accordion
      - [Detroit's extended care and rehabilitation accordion](https://www.va.gov/detroit-health-care/health-services/)
      - [Puget Sound health care's mental health page](https://www.va.gov/puget-sound-health-care/health-services/mental-health-care/)
- [ ] Evaluate the option of presenting a facility as a page, such as [Miles City](https://www.va.gov/montana-health-care/locations/miles-city-va-community-living-center/)
- [ ] Review the [Veteran Decision Aid](https://www.va.gov/GERIATRICS/docs/Veteran_Decision_Aid.pdf) 
- [x] Iterate on lo-fi wireframes for Doms and CLCs

## Acceptance Criteria
- [ ] Domiciliary lo-fi mockup is ready for review with Dave and Michelle (and Design intent to follow) and answers the following questions
      - What do Veterans need to know about this type of facility?
      - What are the top tasks for a Veteran learning about this type of facility?
      - What is the best content strategy for displaying this information?
- [ ] Community Living Center lo-fi mockup is ready for review with Dave and Michelle (and Design intent to follow) and answers the following questions
       - What do Veterans need to know about this type of facility?
       - What are the top tasks for a Veteran learning about this type of facility?
       - What is the best content strategy for displaying this information?

Updated wireframes are here: [link to UXPin](https://preview.uxpin.com/a2b38a92d039129e71f5589e314742891dcfbb08#/pages//simulate/sitemap?mode=i), for both desktop and mobile.

**Comment by nicko-amida** [comment]
@mmiddaugh I added the lofi wireframes and discussion notes to both [Domiciliary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/domiciliaries/discovery/DISCOVERY-FINDINGS.md) and [CLC](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/community-living-centers/discovery/CLC-DISCOVERY-FINDINGS.md) discovery repos.

**Comment by nicko-amida** [comment]
Updated wireframes are here: [link to UXPin](https://preview.uxpin.com/a2b38a92d039129e71f5589e314742891dcfbb08#/pages//simulate/sitemap?mode=i), for both desktop and mobile.
