### ISSUE TITLE
HLR 2.0: Change Rep name format

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#28477]
## Issue Description
Change the rep name format (I believe this means separating out first and last name).

---
## Tasks
- [ ] Create the page in Sketch
- [ ] Upload into Sketch 4 Teams

## Acceptance Criteria
- [ ] Design has been created and uploaded
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
