### ISSUE TITLE
Configure BID Production URL for 686 Pension Awards Service 

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#28470]
## Background
The production URL for the BID Pension service needs to be configured once we receive that information.

## Tasks
- [x] Generate the token for awards service
- [x] Test the production service in Postman (if possible)
- [x] Submit a PR to devops that includes the PROD url and token

## Acceptance Criteria
- [x] The BID pension service is configured in production
- [x] A PR has been requested for merging in the devops repo
