### ISSUE TITLE
HLR Design 2.0: Add SOC/SSOC Date field per Issue

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#28479]
## Issue Description
Add opt in per issue.

---
## Tasks
- [ ] Create the page in Sketch
- [ ] Upload into Sketch 4 Teams

## Acceptance Criteria
- [ ] Design has been created and uploaded
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Noteworthy comments from Robin on old ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/27907#issuecomment-892824332
