### ISSUE TITLE
HLR Design 2.0: Explicitly take in Rep phone# and email

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#28478]
## Issue Description
We need to add rep phone number and email to this portion of the design. Robin already has a head start on this.

---
## Tasks
- [x] Create the page in Sketch
- [x] Upload into Sketch 4 Teams

## Acceptance Criteria
- [x] Design has been created and uploaded
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
Design is created in Sketch and uploaded in Sketch teams. 
Ticket closed
