### ISSUE TITLE
HLR Design 2.0: Start sending in Veteran Contact Info

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#28480]
## Issue Description
Sounds like we are going to start sending contact information on the HLR form. Whether this means the exact same flow as NOD (update profile from form) or not is yet to be seen.

---
## Tasks
- [x] Create the page in Sketch
- [x] Upload into Sketch 4 Teams

## Acceptance Criteria
- [x] Design has been created and uploaded
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
Closing complete.
