### ISSUE TITLE
Add communication and marketing guidance to Product Development Checklist

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28499]
## Issue Description
During a recent Slack conversation with a VFS designer, it was recognized that the Product Development Checklist does not provide guidance and/or information to VFS teams regarding expectations for marketing a new product and creating a communication plan. This ticket will be to update the Product Development Checklist to include insights shared by Mickin Sahni, the VSA Product Lead.

```
Here are go-to strategies for getting things in front of Veterans:

- Top Recommendations (aka Best Bets) via Onsite Search (#va-search)
- Form Detail Page link to a new online app (probably not applicable to you) (#vsa-decision-tools)
- NEW(ish)! Resources & Support articles to folks better understand how to interact with VA.gov
- Typical IA work
^however, all of these require Veterans get into the funnel in the first place.

So other things you might do/people you might talk to:
- Contact Center (#vsp-contact-center-support) - they're the first line of support (and it's already a step in the Collab Cycle)
- Lines of Business - you're essentially asking about that, Liz, with the list of names you shared. Except it would be the AuthExp equivalent.
   - Are there stakeholders mentioned on the product doc for your initiative?
   - If not, Kevin H. would be an excellent person to ask who might be good conduits
- Impact Reviews - as you might know, these have been multi-purpose artifacts incl. for material shareable with stakeholders
   - I'll pass along to you
- 1-pager - I believe Martha Wilkes put this together for the chatbot. Definitely higher-level, but another artifact.
- Social (FB, Twitter, Reddit)/YouTube - Fairly straightforward. Maybe Contact Center :point_up::skin-tone-3: can point in the right direction?

```

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] VFS teams are aware that they should discuss marketing strategies with their Product Owner.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
communicating and marketing are items on the list. ask VFS teams to discuss this with their Product Owner. don't know if we want to include Mickin's suggestions as "platform sanctioned."

**Comment by jimuhh** [comment]
@shiragoodman, @rroueche  I've added a hed called "discoverable" under the "findable" hed. This is where I'm putting the marketing and publicity info. I just need a little more context on some of the text in this ticket.

**Comment by jimuhh** [comment]
Here are go-to strategies for getting things in front of Veterans:

> **Jim's questions in quotation callouts**

- Top Recommendations (aka Best Bets) via Onsite Search (#va-search)

> How does a VFS team go about getting their content featured this way?

- Form Detail Page link to a new online app (probably not applicable to you) (#vsa-decision-tools)
- NEW(ish)! Resources & Support articles to folks better understand how to interact with VA.gov

> **Same question as before.** How does a team go about submitting their product to these 

outlets?
- Typical IA work

> Not sure I understand the context of this

^however, all of these require Veterans get into the funnel in the first place.

So other things you might do/people you might talk to:
- Contact Center (#vsp-contact-center-support) - they're the first line of support (and it's already a step in the Collab Cycle)

> Given that this is being cited as primary means of publicity, I am moving it under the "discoverable" section

- Lines of Business - you're essentially asking about that, Liz, with the list of names you shared. Except it would be the AuthExp equivalent.
   - Are there stakeholders mentioned on the product doc for your initiative?
   - If not, Kevin H. would be an excellent person to ask who might be good conduits
- Impact Reviews - as you might know, these have been multi-purpose artifacts incl. for material shareable with stakeholders
   - I'll pass along to you
- 1-pager - I believe Martha Wilkes put this together for the chatbot. Definitely higher-level, but another artifact.
- Social (FB, Twitter, Reddit)/YouTube - Fairly straightforward. Maybe Contact Center :point_up::skin-tone-3: can point in the right direction?

**Comment by jimuhh** [comment]
I would be happy to take on the project of talking to the stakeholders and SMEs who know about this stuff and using what I learn to turn the marketing/publicity stuff into documentation. Right now the details need more explanation, IMO.

**Comment by shiragoodman** [comment]
@jimuhh thank you so much for this work. I should've specified with you before the work began that OCTO does not wish for Platform to really provide suggestions, recommendations and/or solutions for how to market the product to Veterans. If you look at the first comment on this ticket from August 10, I mentioned that we, "don't know if we want to include Mickin's suggestions as "platform sanctioned."" My guidance to you would be to add 1 item (possibly under a new category) suggesting teams sync with their Product Owner to discuss marketing strategies.

**Comment by jimuhh** [comment]
@shiragoodman -- if "discuss marketing strategies w/ product owner" is the only guidance we are offering, I can put that there now. LMK

**Comment by shiragoodman** [comment]
yes. for now, I think that will suffice. Thank you @jimuhh .

**Comment by jimuhh** [comment]
Added.

**Comment by jimuhh** [comment]
@peggygannon could you have a look at the Product Development Checklist Draft to proofread my additions? 

**They are:** 
### Supportable
-  **Feature toggles** are written into product code to enable easy review, testing and approval of functionality for a variety of platforms and stakeholders
### Findable
.  Your team’s Product Owner has investigated and addressed the product’s marketing and publicity needs.

**Comment by peggygannon** [comment]
Hi, @jimuhh thanks. I reviewed and the additions look good.

**Comment by jimuhh** [comment]
Published and closed. Thanks @peggygannon!
