### ISSUE TITLE
CHIP can write information to LoROTA

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#28495]
CHIP needs to create a claims token to get access to information that it wants - to write what it wants to write. 

CHIP needs to:
- [x] Create a claims token
- [x] Specify the validation parameters for future requests
- [x] Send and receive a token back
- [x] separate out the idea of basic and full scopes
- [x] write that full payload to LoROTA

**Task is done when**
Initiate a checkin and correct form for data can be manually verified in database.

**Notes:**
We treating write.full like read.full
Made an exception for CHIP in LoROTA to just need public key

**Comment by aschulhof** [comment]
Last 4 last name verification - In prod
