### ISSUE TITLE
Address Content Feedback from Staging Review 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#28491]
## Description

Address the feedback from the staging review
## Tasks

> this is a list of technical tasks that need for this ticket

- [x] [Remove Period from header](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28328)
- [x] [Fix casing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28327)
- [x] [Adjust Focus](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28326)

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature

**Comment by mdewey** [comment]
All feedback is addressed expect for the focus on the confirmation page in the PR #18286

**Comment by mdewey** [comment]
Working on updating focus management. See this thread for context: https://dsva.slack.com/archives/CBU0KDSB1/p1629212223074400

**Comment by mdewey** [comment]
All of these should be in staging.
