### ISSUE TITLE
[MCP] Identify if the dates we're receiving through the Liberty API matches the table's UI

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#28500]
## Issue Description
We're receiving multiple dates through the API payload, and it's unclear what the difference is between the dates and if they map to the table in the way we expect. 

[the mock API data](https://yf7yvyucfj.execute-api.us-gov-west-1.amazonaws.com/Prod/swagger/index.html) shows these date fields:

`"pS_STATEMENT_DATE": "string",`
 `"pS_STATEMENT_DATE_Output": "string",`
`"pS_PROCESS_DATE": "string",`
`"pS_PROCESS_DATE_Output": "string",` 

Under `details` there's more date fields: 
`"pD_DATE_POSTED": "string",`
`"pD_DATE_POSTED_Output": "string"`

We're in the process of outlining the charges that could display on a statement ([view on UXPin](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140826035/simulate/sitemap?mode=i)), and as part of that we want to display the charge date (transaction date) for each line item. We need to identify what the date fields we're receiving mean and if they match with our proposed table. 

We had a meeting with Michael and Ray to clarify these fields, but they were unsure. We're in the process of scheduling a meeting with SMEs identified in that meeting. 

---
## Tasks
- [ ] _Identify the difference between the date fields_
- [ ] _Ensure the date fields match the proposed UI_

## Acceptance Criteria
- [ ] _We've identified and documented what the date fields correlate to_
- [ ] _Collaboration between design and backend have verified whether or not the table's UI matches the data we're receiving_
- [ ] _If the data doesn't match, a ticket to update the design has been created and linked in this ticket_ 
---

**Comment by rileyorr** [comment]
As discussed during backlog grooming, this ticket is no longer applicable
