### ISSUE TITLE
[FE] Create Mock Multiple Appoinnment Page

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#28514]
## User Story

As a veteran, I should see a page that asks me to validate my identity

## Related Documentation

- [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=ceb2a543-2dec-40c8-9696-8aa50f7152ea)

## Description

Even though the finer details might change, we still need a page that displays to the user some sort of multiple appointment page

This ticket is for creating the page behind a feature toggle, that allows for a mocked multiple appointments to occur.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Create a new `multiple appointment page
- [x] Should display a list of appointments, one in each status that is in the mock-up. 
- [x] Behind the feature flip already created
- [x] Create mock API responses
- [x] Create user tests
- [x] Create e2e tests with updated feature flags
- [x] Add GA to the API calls
- [x] Update relevant documentations

## Acceptance Criteria

- [x] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
