### ISSUE TITLE
[FE] Create Mocked User Validation Page 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#28511]
## User Story

As a veteran, I should see a page that asks me to validate my identity

## Related Documentation

- [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=ceb2a543-2dec-40c8-9696-8aa50f7152ea)

## Description

Even though the finer details might change, we still need a page that displays to the user some sort of validating input fields. 

This ticket is for creating the page that behind a feature toggle, that allows for a mocked validation to occur.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Create a new `validate` page
- [ ] ~Add 2 input files on that page, 1 with masked numbers for ssn~
- [x] Behind the feature flip already created
- [ ] ~Create mock API responses~
- [ ] ~Create user tests~
- [x] Create e2e tests with updated feature flags
- [ ] ~Add GA to the API calls~
- [ ] Update relevant documentations

## Acceptance Criteria

- [x] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
I am moving some of the tasks out to other tickets, this ticket is should just be the routing and feature flip.
