### ISSUE TITLE
[Design] Sync with VAOS on Check-in Your Appointment Cards

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#28524]
# Description
Sync with VAOS on some appointment stylings

# Tasks
- [x] Check on the layout of our appointment cards compared to VAOS, especially the need for a clinic label and the size of clinic wording
- [x] Check with Lauren Ernest for realistic clinic names. I was told they have a list.
- [x] Look into VAOS disabled styling for Virtual appointments that are in the future. Ryan wasn't sure if this styling/state still existed in VAOS

# Acceptance Criteria
- [x] Message or meet with VAOS to get the answers to the above items
- [x] Update Sketch, Mural and UX Pin based upon answers

**Comment by kristenmcconnell** [comment]
Messaged Lauren Ernest about clinic name examples.

**Comment by kristenmcconnell** [comment]
Received [clinic list](https://docs.google.com/spreadsheets/d/1IVz2nq2aStBFzlz8znM_vmqjZ5AX24tePmJ_dR1wtuc/edit?usp=sharing) from Lauren and update Sketch/UX Pin.

**Comment by kristenmcconnell** [comment]
Reviewed [VAOS card design](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/oY57q80) and [appointment detail design](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/eKDzGxW), in order to address the feedback that our card designs should be in sync.

Due to the following reasons I believe the card designs should not exactly match each other:
1. Check-in is a mobile experience. We received feedback that the size of the body copy was too small on a mobile device, so we made time an H2 and clinic an H3 as a result. This differs from VAOS at this time and clinic information. I hope to continue to test with these styling changes, in order to see if the larger text is preferred for a truly mobile-centric experience.
2. There are also valid reasons for showing different content within the cards. In VAOS, dates are important, since it is a list of all appointments. Check-in is limited to one day, so time becomes the most important. We are aware there are some use cases for facility information and appointment type (virtual, etc), but clinics are the second most important information. Most appointments on any given day happen at just one facility. @jparker0425 We should probably talk through the need for facility information and other appointment types more to cover those edge cases.

For these reasons, I believe the cards for check-in and VAOs should remain different.

**Comment by kristenmcconnell** [comment]
I messaged Peter Russo on Slack about the disabled state for virtual appointments. I asked for an example of that styling and any pertinent information about that scenario.

**Comment by kristenmcconnell** [comment]
VAOS uses a disabled state for future telemedicine appointments. Information from Peter Russo:

Button disabled: [https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/52RWJlL#Inspector](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/52RWJlL#Inspector)
Button enabled: [https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/bgGKvJ4](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/bgGKvJ4)

**Comment by kristenmcconnell** [comment]
Setting up a meeting with Peter for early next week.

**Comment by kristenmcconnell** [comment]
For accessibility reasons, we aren't going to add a disabled button.

Comments in DSVA Slack supporting this:
- https://dsva.slack.com/archives/C8E985R32/p1614710575013700?thread_ts=1614705357.010600&cid=C8E985R32
- https://dsva.slack.com/archives/C01Q9PDPLE9/p1617888083018800?thread_ts=1617847190.018000&cid=C01Q9PDPLE9
- https://dsva.slack.com/archives/C0NGDDXME/p1617715094145600?thread_ts=1617676715.140000&cid=C0NGDDXME
