### ISSUE TITLE
[VAMC-Scaffolds]  Clone 2 copies each of the CLC and DOM pages for use in example systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28531]
## User Story 
As a Veteran Web user, I need a easier and more efficient site, so I can quickly get to my objective and complete my journey on the local VA.Gov/MC website.

## Goal
_Implement required VAMC-upgraded va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran web user_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Clonable Website](TBD - check with Stan)

## Tasks
_clone 2 copies of the following SOT
- [x] CLC Community Living Center
- [x] DOM Domiciliary 

## Acceptance Criteria
- [x] Validate attached to Program menu pages and this shows up on Menu
- [x] Validate that pages are ready to take data load information

**Comment by ltrombley** [comment]
Task #28531 - Clone 2 copies each of the CLC and DOM pages for use in example systems [BA] - is Complete and moved to Validate
