### ISSUE TITLE
[VAMC] Prepare Marion health care for Dual-state VISN-15 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28545]
## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed
**Tugboat Actions**
- [x] Rebuild and refresh Tugboat instance of System
- [x]  Publish all nodes for specific system
- [x]  Release content (Report any issues in release)
- [x]  View logs and resolve any broken links
**Facilities incldude:**
- [x] vha_657A5	Marion VA Medical Center
- [x] vha_657GJ	Evansville VA Clinic (Health Care Center)
- [x] vha_657GK	Mount Vernon VA Clinic
- [x] vha_657GL	Paducah VA Clinic
- [x] vha_657GM	Effingham VA Clinic
- [x] vha_657GO	Madisonville VA Clinic
- [x] vha_657GP	Owensboro VA Clinic
- [x] vha_657GQ	Vincennes VA Clinic
- [x] vha_657GR	Mayfield VA Clinic
- [x] vha_657GT	Carbondale VA Clinic
- [x] vha_657GU	Harrisburg VA Clinic
- [x] vha_657QD	Heartland Street VA Clinic

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system
- [x] Tugboat broken links have been resolved in Prod.cms.va.gov

**Comment by ltrombley** [comment]
Task #28545 - Prepare Marion health care for Dual-state VISN-15 [VAMC] - is Complete and moved to Validate.
