### ISSUE TITLE
[VAMC] Prepare Wichita health care for Dual-state VISN-15 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28548]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Tugboat](https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed
**Tugboat Actions**
- [x] Rebuild and refresh Tugboat instance of System
- [x]  Publish all nodes for specific system
- [x]  Release content (Report any issues in release)
- [x]  View logs and resolve any broken links
**Facilities incldude:**
- [x] vha_589A7	Robert J. Dole Department of Veterans Affairs Medical and Regional Office Center
- [x] vha_589G2	Dodge City VA Clinic
- [x] vha_589G3	Liberal VA Clinic
- [x] vha_589G4	Hays VA Clinic
- [x] vha_589G5	Parsons VA Clinic
- [x] vha_589G7	Hutchinson VA Clinic
- [x] vha_589GW	Salina VA Clinic
- [x] vha_589QB	Sedgwick County VA Clinic
- [x] vha_589QC	South Parklane VA Clinic
- [x] vha_589QD	Wichita VA Mobile Clinic

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system
- [x] Tugboat broken links have been resolved in Prod.cms.va.gov

**Comment by ltrombley** [comment]
Task #28548 - Prepare Wichita health care for Dual-state VISN-15 [VAMC] - is Complete and moved to Validate
