### ISSUE TITLE
[VAMC] Prepare St Louis health care for Dual-state VISN-15 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28547]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Tugboat](https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed
**Tugboat Actions**
- [x] Rebuild and refresh Tugboat instance of System
- [x]  Publish all nodes for specific system
- [x]  Release content (Report any issues in release)
- [x]  View logs and resolve any broken links
**Facilities incldude:**
- [x] vha_657	John Cochran Veterans Hospital
- [x] vha_657A0	St. Louis VA Medical Center-Jefferson Barracks
- [x] vha_657GA	St. Clair County VA Clinic
- [x] vha_657GB	St. Louis County VA Clinic
- [x] vha_657GD	St. Charles County VA Clinic
- [x] vha_657GS	Franklin County VA Clinic
- [x] vha_657GX	Washington Avenue VA Clinic
- [x] vha_657GY	Manchester Avenue VA Clinic
- [x] vha_657QA	Olive Street VA Clinic
- [ ] vha_657QB	Washington Boulevard VA Clinic (This clinic does not exist)
- [x] vha_657QE	Scott Air Force Base VA Clinic

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system
- [x] Tugboat broken links have been resolved in Prod.cms.va.gov

**Comment by ltrombley** [comment]
Task #28547 - Prepare St Louis health care for Dual-state VISN-15 [VAMC] - is Complete and moved to Validate

**Comment by ltrombley** [comment]
9/1/21:  Missing System/Facility Health Services for Jefferson Barracks have been added - System Published into Dual-state.
