### ISSUE TITLE
Vet Center Social Media Share Metadata

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#28559]
## Issue Description
As a Social Media Influencer I want to share a Vet Center link on social media (Twittter, Facebook) and have that share present a good UX via metadata use (OG/Twitter) so that my Veteran followers can easily understand and engage with that social media share.

Dependency on CMS audit of metatags, etc

---
## Tasks
- [ ] Twitter Metatags (Title, Description, Correct Share Image with size and dimension)
- [ ] OG Metatags (Title, Description, Correct Share Image with size and dimension)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Added to [Enhancements/optional features for Vet Centers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37529) and now closing this issue
