### ISSUE TITLE
[SPIKE] Cross team QA Improvements. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#28557]
## Description

As a cross-team effort, we are looking to iterate on our QA process and what does QA means to our team. This is a placeholder for the work I am doing. 

### Tasks

- [ ] Hold whiteboarding meeting
- [ ] Create Recommendations for process changes
- [ ] Present Recommendations to appropriate parties
