### ISSUE TITLE
Sync POA Desktop Version to Mobile Version

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28561]
## Background
The desktop version of this ticket needs to be synced with the mobile version (being used a source of truth)

## Considerations
(POA prototype: https://preview.uxpin.com/61c3ebf323d3662f44e38a8cbb28a7d326533703#/pages/140758443/simulate/sitemap)

## Tasks
- [x] Reconcile both
- [x] Make new screens as needed

## Acceptance Criteria
- [x] Both versions are the same
- [x] Share with team (or EBN channel)

**Comment by jason-gcio** [comment]
@sporeboy will be adding artifact link here soon
