### ISSUE TITLE
Readout of Rated Disabilities/View Dependents Usability Study

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#2857]
## Story
As an eBenefits team member I need to create a holistic presentation of the issues that came out of the Usability Study

## Task
- [x] Review notes, audio
- [x] Data analysis
- [x] Report findings of Usability testing of Rated Disabilities, View Dependents and Tools Page layout

## Acceptance Criteria
- [x] Create a presentation to include recommendations in long form of usability testing and key findings, PowerPoint (with pdf supplement) format is probably preferred
