### ISSUE TITLE
Remove community care provider selection flag

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#28572]
## Item Description
The Community Care Provider Selection (list page) is live and moving to sustainment.

## Tasks

- [x] Remove FE `va_online_scheduling_provider_selection` flag
- [x] Remove BE `va_online_scheduling_provider_selection` flag

## Acceptance Criteria

- [ ] No changes in experience

**Comment by LeKeve** [comment]
@laurenernest When the `va_online_scheduling_provider_selection` feature flag is off we display the single page cc preferences layout which I included a screenshot of below.

![Screen Shot 2021-08-13 at 12.06.32 PM.png](https://images.zenhubusercontent.com/5fb2c17a7bedf7598b0e96f2/d2f6f26c-27b2-427f-aa1f-372c59a13ba2)

Am I correct in understanding that we want to remove this layout entirely, remove the `va_online_scheduling_provider_selection` feature flag, and only display the new cc provider selection pages?

**Comment by LeKeve** [comment]
@laurenernest Per our conversation, we still want the single page cc preferences layout ([design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/community_care_flow.md#preferences-page)) to display when user is missing a residential address.

Otherwise, the default should be to display the provider selection page ([design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/community_care_flow.md#provider-selection-page-unreleased)).

**Comment by LeKeve** [comment]
Moving to validate so frontend states can be checked.

**Comment by laurenernest** [comment]
Both address and no address scenarios appear to be unaffected, and the toggle no longer appears in the flipper admin. closing ticket.
