### ISSUE TITLE
Remove Status Alert from Copay Overview Page

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28571]
## Issue Description

We learned that Treasury referral data is not currently being passed to us with the API so the status alert should be removed from the Copay Overview page.

![Medical Copays  Veterans Affairs 2021-08-10 12-23-27.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/4d11ff3f-6114-426d-bb1b-aeef417fbf14)

---
## Tasks
- [ ] Status alert component and styles should be removed
 - [ ] Remove links from Design System Documentation for code usage in [Experimental Design](https://design.va.gov/experimental-design/expandable-alert#code-reference)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
