### ISSUE TITLE
Update Full Accessibility & 508 Office Audit template and touchpoint document

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28573]
## Issue Description
The template specifies, "As part of this review, Platform will send your product to VA's 508 office for approval (as applicable)". VFS teams have been directed to send to VA's 508 office themselves. The template and touchpoint documents should be updated to reflect this.

- [x] Update Full accessibility template (see image below)

![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/7f8af28e-0e87-4c0c-8975-2c8469f9eabc)
The steps section is correct. Only the additional information section needs updating.

- [x] Update [Full Accessibility touchpoint doc](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
This is completed.
