### ISSUE TITLE
Create topline summary of results from VSO interviews

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#28589]
### Background
This topline summary is a high level, top-of-mind summary of trends found in research sessions. It is not the **final **result of working with the data discovered. The information in this document may change following a deeper review and analysis of the data gathered.

The goals of this document are to:

- Make sure everyone who observed the study is in alignment with the perceived findings
- Gain insight from team/stakeholder/designers and determine specific directions to pursue as we analyze the data
- Jump start synthesis by quickly organizing high level themes

### Considerations
User the revised VSA topline summary [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/topline-summary-template.md)

### Tasks
- [x] Review notes from sessions
- [x] Consolidate notes from attendees in matrix/Mural board/etc.
- [x] Draft topline summary for review

### Acceptance criteria
- [x] Topline summary complete and available to team

**Comment by candy-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/vso-discovery-interviews/vso-interviews-topline.md
