### ISSUE TITLE
Implement Sitewide Team content revisions to COE prototype

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#28586]
### Background
The COE feature is nearing the final rounds of content revision. The Sitewide content team has reviewed the UXPin prototype and suggested changes. The prototype needs to be updated so the LGY "front office" can make a final review of all copy.

### Considerations
- The LGY front office should be reviewing content for factual errors vs. style and plan-language phrasing

### Tasks
- [x] Review text changes from Sitewide Content team
- [x] Implement text revisions in COE prototype
- [x] Make team aware of revisions

### Acceptance criteria
- [x] The COE UXPin prototype are updated and ready for LGY review

**Comment by sporeboy** [comment]
First round of "final" content revisions in place: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140811192

**Comment by sporeboy** [comment]
Creating new states for dynamic intro screen. That work will be covered in a new GH issue.
