### ISSUE TITLE
[MCP] Add dispute content 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#28583]
## Issue Description
_We need to add content about requesting disputes for medical copay charges to the medical copay tool._

---
## Tasks
- [x] _Add a section about requesting dispute based on [this content page](https://www.va.gov/health-care/pay-copay-bill/dispute-charges/)_
- [x] _Notify Danielle in [the IA/content request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27780#issuecomment-896821680) that we've added an additional section with disputes_ 

## Acceptance Criteria
- [x] _The UXPin has been updated and linked in this ticket_
- [x] _A comment has been added to the IA/content request ticket_

**Comment by rileyorr** [comment]
Added a section on the balance detail page with the dispute content. [The prototype has been updated and can be found here.](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140772653/simulate/sitemap?mode=i)

I also added a comment on the dispute section of the prototype that will (hopefully!) notify Danielle via email, and commented about the new section in the content/IA ticket.
