### ISSUE TITLE
Conduct VSO interviews (21-22/a appoint rep feature)

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#28588]
## Background
Knowing more about how VSO's operate and what we can do to make their process easier.

## Tasks
- [x] Conduct interviews
- [x] Collect and post notes to Github

### Acceptance criteria
- [x] All interviews complete
- [x] Notes taken are posted to Github

**Comment by jason-gcio** [comment]
Great job on this Candy, thanks.
