### ISSUE TITLE
[FE] Profile, Notification Prefs: (Research Spike) Explore technical solution for redirecting users back to their task after making profile edits

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28584]
## Background
As noted in #26914 the ability to edit contact information in place (within Notification preferences feature) is not something we will pursue for MVP. However, the MVP does allow the user to easily navigate to the contact info section of profile to make updates to phone and email when needed. We need to come up with a light solution that helps redirect the user _back_ to the task of completing their notification preferences once they have updated their contact information, which they will often have to do in order to set their notification preferences.

Potential solutions/concepts include:
- track the user via cookie?
- `next` URL query parameter (see [Erik's note](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26914#issuecomment-896948395))

## Tasks
- [ ] Research potential technical solutions
- [ ] Document options here and discuss with Liz and AJ (and Kevin)
- [ ] Let Liz know when we have enough info on a technical solution so she can mockup some designs

**Comment by ajakabcin** [comment]
Closing this - not needed
