### ISSUE TITLE
Use Venafi to get certificates for .vfs.va.gov services

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#28594]
## Description
We need to get certificates for the services we run internally inside the VA network on the vfs.va.gov subdomain.
We should either create and use a wildcard certificate (*.vfs.va.gov) or a separate certificate for each service.
- Grafana
- Sentry
- Prometheus-<dev,staging,sandbox,prod,utility>
- Loki-<dev,staging,sandbox,prod,utility>
- Jenkins
- Argocd
- Argoworkflows
- maybe others?

## Background/context 
https://dsva.slack.com/archives/CJYRZK2HH/p1628097077076800

## Technical notes
Venafi is the system which we use to obtain certificates, we need to create and download certificates for the services from there.

---
## Tasks
- [x] Determine whether we can get a wildcard or need to get separate certificates
- [x] Request certificates
- [x] Download certificates once provisioned
- [x] Install certificates to load balancers or endpoints as needed

## Acceptance Criteria 
- [x] Certificates are provisioned and installed in load balancers or endpoints as needed
- [x] Browsing to https:// services is functional and presents no browser errors (assuming the VA cert is trusted)

**Comment by jbritt1** [comment]
Imported into ACM https://console.amazonaws-us-gov.com/acm/home?region=us-gov-west-1#/

**Comment by jbritt1** [comment]
Last bullet I think won't work because the VA internal certs still count as self-signed if I am not mistaken.

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/CJYRZK2HH/p1629214395411900 there is a way to get rid of the alerts about self-signed cert being used, but has to do on your own browser

**Comment by dginther** [comment]
Verified that this is done.
