### ISSUE TITLE
Authenticated Experience: Sprint 56 (9/8 - 9/21)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28591]
## Priorities

1. Notification Prefs: Complete build + internal testing
2. Prepare Notification Prefs for QA
3. My VA action items research readout
4. Profile general improvements 

PTO
- Lihan (9/8 -9/10)
- Tressa (9/8 - 9/10)
- Erik (9/16 - 9/17)
- Taylor (9/17)

## Notification Preferences
**PM**
- [x] Finish test case documentation #26223 
- [x] Submit test plan ticket for Notification Preferences QA prep #28042
- [x] Internal testing #29256
- [x] Submit Analytics Request (VSP collab cycle) #27171 

**Design**
- [x] Create resources and support page to support new notification preferences feature #22887
- [x] Internal testing #29256
- [x] Content ticket to review hint text for Rx tracking notification item #29810

**FE**
- [x] Implement recommendations for radio button spacing #29473 
- [x] Implement conditional display rules for Prescription shipment and tracking notification item #28982 
- [ ] Implement solution for redirecting users back to notification prefs #29542
- [x] #29773
- [x] Display hint text for Rx tracking conditionally #29879
- [x] Revisit hit areas for radio buttons #29814
- [x] Refactoring frontend filtering #29993 

## Profile

**Design**
- [x] Improve alert UX throughout profile #25820

**FE**
- [x] 508-defect-2 [AXE CORE]: Heading should not be focusable while within the mobile profile menu button #23254 
- [x] Implement revised design for clarifying contact email vs sign-in email #28425
- [x] Cannot re-edit contact info after making a no-op save #22114 
- [x] Modal is delayed in closing after remove contact info is confirmed #29992
 

## My VA redesign + Action Items Discovery

**Design/Research**
- [x]  508 Banner Issue #29068
- [x] #29639

**FE**
- [x] Hide "Education and training" if user has application in progress #26652 

## Backend
- [x] Caregiver team support
- [ ] Fix VA profile ADDRVAL111 DualAddressError #28396
- [x] Fix PII sanitizer variable mutation #29383

## General

**PM**
- [ ] [PM] Dependent User Role: Product outline for user role - dependent research #29752 

**Research/Design**
- [x] Auth Exp best practices research phase 2 #24974
