### ISSUE TITLE
Conduct Research Sessions: Search Design Concepts

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28598]
## Description 
- Research ticket to conduct research sessions with Veteran and caregiver participants

##  Associated Research Study 
- Search & Discovery: Design concept research for surfacing more search tools and search landing page
- [Research Materials Folder Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search/research/user-research/2021-Aug-research-study)

## Tasks 
- [x] Print conversation guide
- [x] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x] Conduct scheduled research sessions
- [x] Debrief research sessions w/team
- [x] Post debrief/updates on slack
- [x] Debrief research sessions into note-taking spreadsheet
- [x] Download recordings
- [x] Download notes from Perigean
- [x] Download final participant list from Perigean
- [x] Change display name of Perigean Zoom account back to what it was:  DSVA
- [x] Change profile photo setting in Perigean Zoom account
- [x] Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

**Comment by cindymerrill** [comment]
Done conducting research sessions. Will start data synthesis next week.
