### ISSUE TITLE
Add GA tracking events to Rated Disabilities

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#2859]
## User Story
As a member of eBenefits, I want meaningful insight into how veterans are using this page, so I can make data driven decisions about how to iterate and improve on what currently exists. 

## Considerations
- Ongoing discussion https://github.com/department-of-veterans-affairs/va.gov-team/issues/2072
- Once event names have been finalized, they will be added to the frontend.
- Once event are on staging, the analytics team will do QA to ensure events are firing properly. 

## Event Names:
1. `window.dataLayer.push({'event': 'disability-ratings-list-load-success'});`
2. `window.dataLayer.push({'event': 'disability-ratings-combined-load-success'});`
3. `window.dataLayer.push({'event': 'disability-ratings-list-load-failed', 'error-key': '500 internal error'});`
4. `window.dataLayer.push({'event': 'disability-ratings-list-load-failed', 'error-key': '401 no disabilities found'});`
5. `window.dataLayer.push({'event': 'disability-ratings-combined-load-failed', 'error-key': '500 internal error'});`
6. `window.dataLayer.push({'event': 'disability-combined-ratings-load-failed', 'error-key': '401 no combined rating found'});`
7. `window.dataLayer.push({'event': 'disability-navigation-check-claims'});`

## Acceptance Criteria
- [x] Events are added using `recordEvent` helper function.
- [x] Successful load for both total combined rating and disability list is recorded.
- [x] All load failed scenarios are properly recorded.

**Comment by nedierecel** [comment]
@micahchiang For the navigation tracking event, please see this modified event:

`window.dataLayer.push({'event': 'disability-navigation-check-claims'});`

Next Steps:
1. @micahchiang - Let us know when this is teed up in Staging. Let's also plan a short :15 debug session to walk you through our QA process. 
2. @jonwehausen For your visibility when it's QA time, the entire workspace changes are in "Stories 2072 and 2859 - Rated Disabilities".

**Comment by nedierecel** [comment]
@micahchiang As we QA, are the two success events mutually exclusive? 

When we build goal conversions in Google Analytics, we can use 1 or more events as the goal definition.

**Comment by micahchiang** [comment]
@nedierecel - they are mutually exclusive in the sense that they are two separate API calls, so one can fail while the other succeeds.

**Comment by micahchiang** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/11070

**Comment by nedierecel** [comment]
Thanks @micahchiang - we'll review when it is pushed to staging, and I'll send you a Slack to coordinate QA.

**Comment by nedierecel** [comment]
@micahchiang @jason-gcio I see this is closed, and I really appreciate your work on this. I was able to see the success events. Are there any test profiles that might simulate a load failure? 

Okay if I reopen to finish out the remaining GA tasks on my list? If not, I can also create a separate issue.
