### ISSUE TITLE
[Tech-Debt]  Remove Pittsburgh Webmaster e-mail, phone numbers, and other references from Contact us [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28595]
## Story
The Contact us page should be unique to the system page, so that information goes to the correct webmaster. or 

## Goal
Remove Pittsburgh references and information from VISN-4 and VISN-19 where the original template was used

## TASK
Review Contact Us Page for any references of Pittsburgh or in this case vhapth.  Contact 
- [x] Remove vhapthwebteam@va.gov from Contact page.  Contact PAO for each system and confirm their correct webmaster e-mail/Check GAL
**e.g., To report a technical issue or give us feedback about this site, email our web team at vhapthwebteam@va.gov.**
- [x] Quickly audit VISN-6 systems to see if the template was continued.

## Acceptance Criteria
- [ ] Contact page has either correct webmaster or full line removed from page.

**Comment by bcastoe** [comment]
#28595 - Remove Pittsburgh Webmaster e-mail, phone numbers, and other references from Contact us [BA] -  Completed and moved to validate; check VISN(s) 4, 19, 6 and also asked to check 16.
