### ISSUE TITLE
Authenticated Experience: Sprint 57 (9/22 - 10/5)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28592]
## Priorities

1. Welcome back Samara!
2. Prepare notification prefs for QA: resolve any remaining issues found internally
3. Get notification prefs through QA
4. Begin prep for notification prefs UAT
5. Define next steps with Action Items

PTO
- Liz (9/28 - 9/29)
- Taylor (9/24, 9/27)

## Notification Preferences
**PM**
- [x] QA go/no go #30163 
- [x] Start compiling staging and privacy review documentation #30343
- [x] Submit staging review request #30164

**Research & Design**
- [x] Prep materials for UAT #30165
- [ ] Begin compiling/executing accessibility tests for staging review #30341

**FE**
- [x] Implement solution for redirecting users back to notification prefs #29542
- [x] Improve focus management after user clicks on CTA in alert #29801
- [ ] Begin compiling/executing accessibility tests for staging review #30341
- [x] Make a11y updates to notification settings radio buttons #30512
- [x] Add name attributes to each radio button #30734
- [x] hide `hr` elements from screenreaders #30881
- [ ] Respond to QA findings (if applicable)

## Profile
**PM**
- [x] IA discussion about future of My VA and Profile #30205
- [ ] Create FE tickets for improving alert functionality #30276

**Research & Design**
- [x] Discovery around functionality that allows users to edit contact information without abandoning their task (Part 1) #26914
- [x] IA discussion about future of My VA and Profile #30205
- [ ] Work with PM to create FE tickets for improving alert functionality #30276
- [x] Update alert audit documentation #30458

**FE**
- [x] **(must be done asap at start of sprint)** Remove SMS checkbox on Profile in production ahead of notification prefs launch #30053
- [x] (A11y issue) Focus is lost on error messages #28953
- [x] Rename "status and disability" banner to "my information" #30202
- [x] Stop stripping address line 2 and line 3 #29744
- [x] Issues with delete contact info confirmation modal #30652

## Action Items

**PM**
- [x] Define next steps #30249
- [ ] Determine official name for this feature #30637

**Design/Research**
- [x] Define next steps #30249
- [x] Incorporate an alerts link into the IA/header #30615

 
## My VA

**PM**
- [ ] Follow up on 508 office request
- [x] IA discussion about future of My VA and Profile #30205

**Research & Design**
- [x]  IA discussion about future of My VA and Profile #30205

**FE**
- [x] A11y tickets
    - [x] "Use my VA health" opens in a new tab without warning the user #29043
    - [x] "Verify with ID.me" button should not repeat "ID.me" twice to screen reader users #29044
    - [x] Focus should go to the h1 Verify your identity when the LOA user uses the "Verify your identity" link #29046
    - [x] Disability rating description in disability and status region must be remediated #29070

## Backend
- [x] Identity team support
- [x] Fix VA profile ADDRVAL111 DualAddressError #28396

## General

**PM**
- [x] Dependent User Role: Product outline for user role - dependent research #29752
