### ISSUE TITLE
Create "landing page" layout for Check your COE screen

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#28593]
### Background
We need to create a landing page for this feature so that we can have a strong top of funnel experience into the feature and form.

### Considerations
Unauthenticated way to get into the "Your COE" landing page

### Tasks
- [x] Create a layout for Pub Web to get started on
- [ ] Open an intake ticket with the mas well

### Acceptance criteria
- [x] A layout is available
- [ ] An intake form has been started with Public Websites, if needed (separate ticket?)

**Comment by sporeboy** [comment]
Initial "Check your COE" landing page layout is here: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140810030/simulate/sitemap

**Comment by sporeboy** [comment]
Screen complete; content revisions in place: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140810030
