### ISSUE TITLE
Content update to health care priority groups page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28609]
## Issue Description
Stakeholder Tarsha Tremble requested an update to the [VA priority groups](https://www.va.gov/health-care/eligibility/priority-groups/) health care page for group 6:

![Screen Shot 2021-08-11 at 2.26.14 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8757c0f0-9458-4514-852b-5620c7a5c365)

## Tasks
- [x] Remove text from second bullet 
- [x] Review and publish
- [x] Alert stakeholder that change has been made

## Acceptance Criteria
- [x] Change is on live page

**Comment by RLHecht** [comment]
This work is complete. Moving to validate and will close after next deployment.

**Comment by RLHecht** [comment]
Closing ticket. Work complete.
