### ISSUE TITLE
Sentry - fix sentry_environmentproject table schema

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#28615]
## Description
Somehow the sentry_environmentproject table schema was thrown out of whack.  There should be a compound key on environment_id and project_id which does not exist.  This has caused the table to grow out of control and is causing adverse effects on sentry itself and the utility eks cluster.

Without the compound key in place,  the table has grown to over 35 million records.

![image](https://user-images.githubusercontent.com/76792875/129125331-6ddc70f4-6e34-4093-bb4a-8ab353351292.png)
![image](https://user-images.githubusercontent.com/76792875/129125367-1ab717a1-ba80-4261-b020-e2ba5a01913c.png)

## Background/context 
https://github.com/department-of-veterans-affairs/devops/issues/9741
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27032
https://forum.sentry.io/t/memory-usage-of-web-workers/14451 

## Technical notes
Query to select unique values from table
```
select distinct environment_id, project_id from sentry_environmentproject order by environment_id asc;
```

Query to remove all but the lowest id entry for a given combination of environment_id and project_id
```
delete
from sentry_environmentproject
where environment_id = x and project_id = x
and id != (select min(id) from sentry_environmentproject where environment_id = x and project_id = x)
```
Query to add unique index
```
CREATE UNIQUE INDEX sentry_environmentproject_project_id_29250c1307d3722b_uniq ON public.sentry_environmentproject USING btree (environment_id, project_id)
```

---
## Tasks
- [x] Remove DNS entry to sentry prior to doing work on the database
- [x] Kill all public connections and prevent further connections to database
- [x] Take snapshot before making modifications
- [x] Remove duplicates from table
- [x] Add unique key constraint
- [x] Re-enable public connections
- [x] Add DNS entry back to route53

## Acceptance Criteria 
- [x] sentry_environmentproject will no longer have 35 millionish entries and duplicate entries will not be possible

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
![image](https://user-images.githubusercontent.com/76792875/129130530-b75e753b-fb9a-4d0a-83a4-e0aef4e1e200.png)
