### ISSUE TITLE
[Documentation] EKS rolling update components

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#28620]
## Description
EKS rolling update is a script that runs on a schedule to check that worker nodes are using the latest ASG template as well as recycling any nodes that are out of date.  This needs to be documented in the event that any failures can be troubleshot by the team.

## Background/context 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27613
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25092

## Technical notes
https://github.com/department-of-veterans-affairs/devops/actions/workflows/packer-build-eks.yml
https://github.com/department-of-veterans-affairs/devops/actions/workflows/eks-rolling-update.yml
https://github.com/department-of-veterans-affairs/devops/blob/master/packer/eks-custom-ami
https://github.com/department-of-veterans-affairs/devops/tree/master/scripts/eks-rolling-update

---
## Tasks
- [x] Create confluence doc to explain components that make this work (packer, gha, eks rolling update)
- [x] Cover how to troubleshoot if rolling update fails on a cluster

## Acceptance Criteria 
- [x] team understands how this process works

**Comment by mleclerc00** [comment]
https://vfs.atlassian.net/wiki/spaces/VI/pages/1827897404/EKS+Rolling+Update
https://vfs.atlassian.net/wiki/spaces/VI/pages/1824588018/Packer

**Comment by jhouse-solvd** [comment]
This is done. Please see the documents linked in the previous comment. 

Closing.
