### ISSUE TITLE
Post Research Tasks: Search Design Concepts

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28627]
## Description 
- Research ticket to wrap up research study and associated documents/resources

##  Associated Research Study 
- Search & Discovery: Design concept research for surfacing more search tools and search landing page
- [Research Materials Folder Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search/research/user-research/2021-Aug-research-study)

## Tasks
- [x] Share research report with team, stakeholders, research, Shawna for feedback
- [x] Add participant characteristics into MVS checker (for marginalized groups)
- [x] Make short presentation from research report for Sprint Demo -- won't do b/c planning to talk from report in github, as I did for readout
- [ ] Make longer presentation for Design/Research/Content Mon mtg -- not planning to do b/c not of general VA interest
- [x] Present findings to team and stakeholders, discuss recommendations--date TBD
- [x] Revise report per report out discussions
- [x] Close out ticket once once completed
- [x] Post report on Github
- [x] Add link to Research History page
- [x] Delete recordings (including any shared with Denise, Sam, Megan in Keybase) -- WAIT until after recommendations discussions w/teams
- [x] Remove PII from notes and post on Github, along with any other synthesis documents

**Comment by cindymerrill** [comment]
Started post-research tasks

**Comment by cindymerrill** [comment]
Presented readout to team today from research findings doc in github. I'll probably do this again in a much shorter version for Sprint Demo on Tuesday. Can I take all 5 minutes to do this, @LindaLi123 @denisecoveyduc ?

**Comment by cindymerrill** [comment]
Drafted outline of sprint demo presentation for tomorrow. Plan to review session notes for PII and then post them on github tomorrow. Then I'll close this ticket. @LindaLi123
