### ISSUE TITLE
Research synthesis and reporting: Search Design Concepts

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28628]
## Description 
Synthesize research findings 

##  Associated Research Study 
- Search & Discovery: Design concept research for surfacing more search tools and search landing page
- [Research Materials Folder Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search/research/user-research/2021-Aug-research-study)

## Tasks 
- [x] Clean up notes spreadsheet 
- [x] Write topline summary and share out with team
- [x]  Do data analysis/synthesis of data collected from research  
- [x]  Write research report

**Comment by cindymerrill** [comment]
Cleaned up notes spreadsheet and drafted topline summary, which I shared with another researcher for review. Tomorrow I'll make any revisions needed and then post on #va-search.

**Comment by cindymerrill** [comment]
Here’s my [topline summary](url) of last week’s usability research: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/topline-summary.md.

Now I’m going to start working on the full research report…

**Comment by cindymerrill** [comment]
All done with the research report: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-findings.md

I'm going to close this ticket and move onto the post-research tasks ticket now.

@denisecoveyduc @LindaLi123 I'm now ready for you to schedule a readout anytime next week, although I'm currently busy with harassment tool interviews some of Mon-Wed. I currently have more availability on Thu-Fri.
