### ISSUE TITLE
[Design] Profile, Notification Prefs: Design solution for redirecting users back to their task after making contact info edits

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28636]
## Background
Once Erik and/or Taylor have explored technical options for solutions to redirect users back to their task (of setting their notification preferences) after updating their profile, we'll need to create a mockup for the design.

## Tasks
- [x] Create design
- [x] Review with team
- [x] Handoff to FE for implementation
- [x] AJ to create implementation ticket(s)

**Comment by andaleliz** [comment]
@ajakabcin I've come up with a solution that I reviewed with our devs and is achievable.  I just need to validate the copy with Danielle, which I'll do Thursday during office hours.

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/3dd7cae8-7cb3-4139-bd87-1d4817c06cb2)

- [Prototype link](https://preview.uxpin.com/6fa96dc222d3c59c67feba34a5cac98770462bd7#/pages/141512227/simulate/no-panels?mode=i) (go through the flow of signing yourself up for text notifications)
- Use the background only alert component with an icon
- When user clicks on an `add your [contact info]` link, it should deep link to that section in profile (I think it already does this)
- The success message should reflect the notification channel
> Update saved. Now you can sign up for [channel] notifications.

**Comment by ajakabcin** [comment]
Love this!

**Comment by ajakabcin** [comment]
@andaleliz I created #29542 as a placeholder to fill in with further details when we're ready!

**Comment by andaleliz** [comment]
@ajakabcin Danielle approved the content in the mock-up so we are good to go. One point I want to clarify:

Users should see this alert when they come from the notification settings page, including when they are coming from the variation they see when they have neither an email or mobile number in their profile.

**Comment by erikphansen** [comment]
@andaleliz I'm thinking that this CTA to go back to Notification Settings should appear if the user clicked on the "Update mobile phone" link in addition to the "add mobile phone" link. Do you agree? If so, the text in the CTA _might_ need to change. Let's try to discuss this tomorrow.

<img width="530" alt="Screen Shot 2021-09-21 at 4 37 29 PM" src="https://user-images.githubusercontent.com/20728956/134261650-7f58b853-6959-4cdd-9e5d-b8fb3fc82ec0.png">

**Comment by andaleliz** [comment]
@erikphansen you're right - seems like maybe "manage" should replace "sign up for".

**Comment by andaleliz** [comment]
@erikphansen Do you still want to discuss this further? I don't think we need to get content review/approval for that verbiage change, and we can just go ahead and make the update in the code.

**Comment by erikphansen** [comment]
@andaleliz nope I think I'm good to go!
