### ISSUE TITLE
[FSR] Verify Expense Calculations

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28643]
## Issue Description
Verify all expenses are being calculated correctly and passed in the FSR submission payload. It was also noticed during PROD UAT that some values are captured as floating point values and should be restricted to 2 decimal values.

---
## Tasks
- [ ] Verify all expenses are calculated correctly
- [ ] Format results to a fixed number of 2

## Acceptance Criteria
- [ ] Expenses are calculated correctly and passed to submission payload
- [ ] Values transmitted should be a fixed number of 2 decimal values

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
This was already raised as a risk previously but somehow errors for expense values were not captured so tagging ticket for future reference... [25242: FSR- Verify all input values](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/25242)
