### ISSUE TITLE
[VAMC] Full Production Go Live - Redirect Legacy Sites to new URL for all Systems in all VISNs [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28640]
## Story
As an editor I need to know of any additional final clean up items and barriers, and all tech-debt needs to be resolved, so MVP is present and/or I can clean them up prior to Go Live

## Goal
Prepare the site for Full Production, update tech-debt and record areas that need updating by the PAO.  Make recommendation to VHA for production, submit request for web approval, and redirect via Web Ops

## Task
**Prepare the following Systems for Full Production/Redirect from Legacy URL**
_
## Complete the following tasks for all systems listed above:
- [X] Review system completness, time in Dual-State, training has been completed by one team member for the system, and system pages.
- [X] Schedule sites either through request or through timing via dual-state and availability with the PAO. 
- [X] Propose schedult to VHA for approval 3 weeks in advance of the go live date.
- [X] Upon approval submit Web Authorization (email/confirm with VHA they are submitted so they can go in and approve.
- [X] Submit YourIT Incident using Incident portal. (Sent confirmation to VHA Digital media)
- [X] Confirm Facilities has listing to remove disallow from robot.txt file 6 days in advance
- [X] Submit Lighthouse API file Upload URL redirect for Lighthouse API
- [X] Once Web Operantions has completed archive of old site, Download and save Legacy web from Web Ops to VHA/VAMC SharePoint
- [X] Validate with CMS to remove scrape/ confirm CMS has scrape removed NLT day prior to redirect 
**Internal-Tech-Debt changes**
_Confirm and/or complete the following tasks:
- [X] Move COVID-19 vaccines page under Programs parent page, update URL, and confirm Menu is updated. 
- [X] Assure that "Programs" page is active and published. 	Clone if required, move under About VA System, menu disable, save as published
- [X] Assure that "Research" page is available and in menu (should be left disabled on menu and in draft unless system is using it)	Clone page if required, move under About VA System, menu disabled, save as Draft
- [X] Assure that "Doing business with us" page is available and in menu (should be left disabled on menu and in draft unless system is using it)	Clone page if required, move under Work with us, menu disabled, save as draft
- [X] Assure latest version of Suicide page is active. Update suicide page to match SOT (Currently Albany)
- [X] LGBTQ+	Move LGBT to LGBTQ+ in detail page, System Health Services, and Facility Health Services.  Confirm Staff proviles are updated as well.
- [X] Policies page.  Confirm VAMC System Policies Page is active as the published page.	Copy Policies source code to notepad, save as "Policies-Old" save as Archived (Keep in case records are lost) to be deleted later. Create new VAMC System Policies page, so URL will not have "Policies-0", associated to System and paste in original source code.
- [X] Update Facility Ops Status on VAMC Operating Status page.	Using the Facilities page as reference, make sure all facilities in Operating Status are listed.
- [X] Update and validate Menu.	Reconfirm Menu pages are all correctly aligned and in order. (Changes made)
- [X] Morning of redirect. Remove "Not website of record" Banner
- [X] Morning of redirect. Add COVID-19 Alert Banner

**Final**
- [X] Report discrepancies to VHA DM and PAO for resolution
- [X] Report and document any launch blockers

## Acceptance criteria
- [X] Recommendation sent to VHA digital media
- [X] All areas above are complete and/or reported for correction to PAO
- [X] Launch blockers are reported and system is removed from Go Live if blocker is not removed prior to cut over.
