### ISSUE TITLE
Add link to Isakson and Roe landing page to education page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28650]
## Issue Description
Stakeholder Tammy Hurley got a request to add a link to the Isakson and Roe landing page to the more information and resources section of the education hub landing page. While it doesn't need to go there, she is asking us to find a place on one of the education pages where we can add the link and the teaser text:

[Isakson and Roe Veterans Health Care and Benefits Improvement Act of 2020](https://benefits.va.gov/gibill/isaksonroe.asp) > Learn how the law’s provisions impact your GI Bill benefits.

## Tasks
- [ ] Determine what page to add link to
- [ ] Add link and teaser text to page
- [ ] Review and publish
- [ ] Alert stakeholder 

## Acceptance Criteria
- [ ] Isakson and Roe link is on an education page

**Comment by bethpottsVADEPO** [comment]
Update: I sent this note to Tammy Hurley on 9/8 but haven't heard back yet:

Instead of a link from the Education hub landing page, I’d like to propose the targeted placement of an informational alert on the Post-9/11 GI Bill page. This is what I’m thinking would work (to view this preview, you’ll need to be on the VA network): http://preview-prod.vfs.va.gov/preview?nodeId=935
Then we’ll need to update this page as well: https://www.va.gov/resources/gi-bill-wave-faqs/.
You can take a look at the text I reworked for the affected Q&A here in preview: http://preview-prod.vfs.va.gov/preview?nodeId=16481

**Comment by RLHecht** [comment]
Closing as this is a duplicate ticket. Work for this was completed in #29734
