### ISSUE TITLE
Add "select 1" to Veterans Crisis Line on Helpful VA phone numbers page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28661]
## Issue Description
We got a stakeholder request to add "Press 1" to any mentions of the Veterans Crisis Line on the [Helpful VA phone number](https://www.va.gov/resources/helpful-va-phone-numbers/) article. 
Note that we need to change it to "Select 1" per our style guide.

## Tasks
- [x] Add text to page
- [x] Review and publish
- [x] Alert stakeholder that change is live

## Acceptance Criteria
- [x] Select 1 is adding to VCL mentions on page

**Comment by RLHecht** [comment]
This page has been reviewed and published. Once live I'll alert stakeholders and close ticket.

**Comment by RLHecht** [comment]
Change is live. Closing ticket.
