### ISSUE TITLE
[Sentry Slack Integration] - Add a passthrough for slack to send the callback for the slack/sentry integration

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#28674]
## Description
In order to properly configure the Slack integration in Sentry, we need to enable slack to send a callback to sentry, to set up the slack app. This will require a rule in the dev revproxy, which should redirect from dev.va.gov/sentry-slack (or something similar) to the sentry callback URL.

## Background/context 
https://dsva.slack.com/archives/CJYRZK2HH/p1628097077076800

---
## Tasks
- [ ] Create a revproxy rule for the dev revproxy which sends traffic from a URL like dev.va.gov/sentry-slack to the callback URL expected by the Sentry/Slack integration
- [ ] Configure the rule to accept packets only from the slack.com domain if possible
- [ ] Determine if authentication is possible in this connection, so we do not expose that endpoint unprotected to the internet

## Acceptance Criteria 
- [ ] Sentry Slack integration is complete
- [ ] Sentry is able to send messages to Slack

**Comment by jhouse-solvd** [comment]
@ElijahLynn - please let us know if you intend to move forward with this or need any add'l support. Ops will have a follow up task to close an open proxy if this is no longer needed.

**Comment by mchelen-gov** [comment]
I believe this is OBE by Sentry -> DD -> Slack alerting, docs could use some more clarity tho https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting

**Comment by mleclerc00** [comment]
Closing this ticket since the CMS team has found an alternate path to notify on sentry events (sentry -> datadog -> pager duty).  The following PR removes the proxy opened through dev revproxy in light of these changes.

https://github.com/department-of-veterans-affairs/devops/pull/9959
