### ISSUE TITLE
Entry points work for housing COE form

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28677]
## Issue Description
When the housing COE form is launched, we need to add entry points based on Mikki's IA work. 

IA recommendations to work off of:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md

We need to confirm H1s and URLs before adding in the entry points and write any teaser text if necessary. 

## Tasks
- [x] Add tool to COE find a form page
- [x] Add COE application and static page to housing top nav
- [x] Remove check your appeal status from housing top nav
- [x] Add COE application and static page with teaser text to housing hub page 
- [x] Update check your VA claim status text
- [x] Add COE application and static page to housing left nav
- [x] Change order of top of housing left nav 
- [x] Change label for check your va claim status in housing left nav and change order
- [x] Change the location of the NADL teaser in the gray related information box on all the home loans pages so that it is last in the list of links/teasers. _(added this task on 11/16 based on stakeholder feedback)_

## Acceptance Criteria
- [x] All entry points work is complete

**Comment by RLHecht** [comment]
UX Pin with content that should be added to page once ready to implement: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312/simulate/sitemap

**Comment by bethpottsVADEPO** [comment]
@mnorthuis You saw that stakeholders want to change the static page H1, right? Making sure you have awareness. Not sure if you and I have talked about this yet, but the H1 doesn't usually change like this when we work on entry points from an existing unauth page...

**Comment by mnorthuis** [comment]
Are you referring to the change of "apply" to "request"?   We should probably chat about this one so I'm clear.  Thank you for the ping!

**Comment by RLHecht** [comment]
I'm moving this ticket to ready as we get closer to launching, so that these don't get forgotten.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I added the online application and new static page to the housing hub landing page and wanted you to review the language. I also updated the "Check your VA claim status" label and teaser text based on Mikki's IA doc.

**Comment by RLHecht** [comment]
This work is now all complete. Closing ticket
