### ISSUE TITLE
Create tickets for Login.gov MVP

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28686]
### High-level scope
1. Deal with user logging in
2. Dealing with SSOe. Don't touch Single Sign-on or cookie
3. Logout - Clear our own session & redirect to the FE if we need to.

### Stories
- [x] Update documentation of the entire auth flow of Login.gov.
- [x] Get rid of the trace and refactor the sso_post_form (research is needed). Clean up, verify if we need, remove the nonce for the trace
- [x] Clean up ial1_callback & ial2_callback (DRY up)
- [ ] Populate the rest of the user data after successful "login" UserIdentity model (example calling birth_date, gender, ssn, icn, mhv_icn will call a MPI lookup)
- [x] Remove v0 Sessions_Controller for auth
- [ ] Interface with the FE (with something in SessionsController whether its in v1 or v2). Current session management, need to split out. Login.gov should not interact with eAuth SSOe. Don't interact with the SAML.
- [x] Ensure logging out does not hit the SSOe Logout mechanism (eAuth)
- [x] Accounts table should not rely on ID.me (refactor) & remove Redis cache & Login.gov UUID is being stored & accounts table validation for Login.gov (Login.gov UUID confirm that it has an ICN, after sign in (subsequent) needs the mapp
ing for ICN (IAL2 call if we don't have it))
- [x] SSO cookie needs to be removed (refactor)
- [x] Conditionals for SSO/SSOe need to be removed
- [x] Creation of v2 Session Controller, add new route (click on the FE or v2/sessions/login => redirects to Login.gov)
- [x] If MPI changes (figure out reconcile when ICN changes, call MPI with the old ICN number should respond with new ICN.  Multiple ICNs, should there be a priority, resolving as many as possible). MPI should update the accounts table when called (storing entries we can look at ICN or EDIPI)
- [x] When they don't have an MPI entry and uses Login.gov flow. Make a call to MPI (IAL2) and when nothing is returned we need to create a record in MPI for that user.

```
Step 1. Figure it out
Step 2. Update the token for the add (eAuth has that ability)
Hard dependency to get additional permissions for that ability
What we need for the staging & production prototypes
```

- [x]  Add features toggle for Login.gov (FE) buttons
- [x]  FE - Button needs to be added to the modal, general refactoring
- [x]  FE - Replace ID.me verify with for the Login.gov Verify
- [x]  Remove reliance on ID.me UUID (Accounts Table, other places)
- [ ]  Create new Cognito test instances (Joe's list)

```
Login.gov apps (IAL1 & IAL2) - Test, Staging, Prod
Cognito (IAL1, IAL2) - Test, Staging, Prod
```

- [x] Deletion policy for the user data in Identity Pool (figure out)
- [x] Does MHV make MPI requests? Do they need all that stuff every time? (MHV migration/research)
- [x] Remove a lot of conditionals in codebase (from the SSO/SSOe)
- [x] Figure out the logging/monitoring (possibly production to figure out)
- [x] Reset/clearing the session
- [ ] If there's (User Identity refactoring to have a parser) have a subset of User Identity to add fields. Child class? Improve code quality. Don't need to invoke
- [x] Reconcile LOA & IAL how it's defined & how it's used. (Research differences because they're not one-to-one).
- [x] Refactor users sessions form (shoving the SAML headers into the User Identity and creating it from that & creates a session from that).
- [x] Figure out the weird redirects with Cognito
- [x] Log and account for metrics (start collecting data about everything, then drop off stats that aren't. Only for staging). *Verbose logging*
- [x] Refactor `statsd` login stuff to DataDog (conditional/flipper).
- [ ] Log Sentry stuff.
- [x] Fail hard when MPI is down (BE sends response to FE, FE shows MPI is down, etc.)

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
