### ISSUE TITLE
Missing Ch31 PDF's, and multiple submissions

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#28692]
# Problem 1: PDF's are not successfully being uploaded to VBMS and/or CMP (with one or more submissions)

# Problem 2: there are multiple submissions being made (sometimes PDF makes it & sometimes not)

### Error messages we are seeing
- pdf file does not exist
- rails html.erb file does not exist ???

### Questions
What happens when I am not a veteran and I fill out the 28-1900 and I don't have a VA file number (or an e-folder)?

What do the AWS/sentry logs look like for the timestamps that Lisa sent:

> 455 | 346 - Seattle |   | 2021-08-10 15:18:20 UTC | 28-1900 | 674
> 456 | 346 - Seattle |   | 2021-08-10 14:59:08 UTC | 28-1900 | 674
> 457 | 346 - Seattle |   | 2021-08-10 14:58:05 UTC | 28-1900 | 674
> 458 | 346 - Seattle |   | 2021-08-10 15:00:33 UTC | 28-1900 | 674
> 459 | 346 - Seattle |   | 2021-08-10 15:05:09 UTC | 28-1900 | 674
> 460 | 346 - Seattle |   | 2021-08-10 15:21:50 UTC | 28-1900 | 674

### Good tests to perform
- [ ] does VRE get an email when VBMS upload fails/errors
- [ ] delete the PDF and see what user sees
- [ ] delete the template and see what user sees

### Logging to do
- [x] remove logging when true
- [x] add PID
- [x] add 686 thing for Kathleen

### Post Mortem reverts/cleanup
- [ ] revert https://github.com/department-of-veterans-affairs/vets-api/pull/7643
- [ ] revert https://github.com/department-of-veterans-affairs/vets-api/pull/7596

## Sub-Issues
- [x] #29003
- [x] #29025
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/31882

# Issue description moved from https://github.com/department-of-veterans-affairs/va.gov-team/issues/31737 

## Issue
The stakeholder is indicating that multiple submissions are being sent to VBMS by the Veteran after Columbus Day.  Applications are going through and saving, but the Veteran is reattempting several times, possibly due to a prompt that the action has failed.

## Background
On Oct 14 and Oct 18, there were 3-4x increases in volume of submissions.  Usually they see about 3-500 per day (lower on weekends) and on those days there were 1,382 and 1,321.  Many of these are duplicates

## Considerations/Facts:
- We check if the Veteran has a Participant ID
  - If not, we send to Central Mail and continue on with sending out an email etc.
  - If yes, we attempt to send to VBMS
    - if that is successful, we continue on with sending out an email etc.
    - If sending to VBMS raises an exception, we send to Centralized Mail
      - Central Mail submission is a job that is sent off to the sidekiq queue
- The controller and action in discussion is: 
`V0::VeteranReadinessEmploymentClaimsController#create`
- No related code changes were released on either Oct 14th or 18th
- vets-api release diffs:
  - Oct 12 (when multiplicity went from 2% to 40%
    - [website](https://github.com/department-of-veterans-affairs/vets-website/compare/vets-website/v0.1.1902...33b5833ed7760027d1b27daf35682e83e03b5be8)
    - [api](https://github.com/department-of-veterans-affairs/vets-api/compare/vets-api/v0.0.987...b7018836eb8612a094d2e0b9d53304f8233a6504)

  - Oct 14 (multipalooza # 1)
    - website
    - api
  - Oct 18 (multipalooza # 2)
    - website
    - api

## Errors Found:
**Sentry**
On the backend, we see some VBMS::HTTP errors, some of which are:
- Gateway Timeouts
- Veteran File Number wasn’t found

On the frontend, we see Network Connection failed errors. http://sentry.vfs.va.gov/organizations/vsp/issues/34807/events/61289edc89ec4b599f084fa6266dae86/?end=2021-10-14T23%3A59%3A59&environment=production&project=4&start=2021-10-14T00%3A00%3A00&utc=true

## Metrics
**Grafana** 
- Oct 14th over 1,000 200’s
http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?viewPanel=12&orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Fveteran_readiness_employment_claims&var-frontend_app=All&from=1634184000000&to=1634270399000

- Oct 18th (Eastern Time, in order to match summary email):
http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?viewPanel=12&orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Fveteran_readiness_employment_claims&var-frontend_app=All&from=1634529600000&to=1634615999000
Higher than normal amount of requests

**Summary Emails**
On Oct 14 and Oct 18, there were 3-4x increases in volume of submissions.  Usually they see about 3-500 per day (lower on weekends) and on those days there were 1,382 and 1,321.  Many of these are duplicates.

## Assumptions:
VBMS is probably not down all day long (we try to send and if we get an exception, we send it over to CM)
We assume this is not systemic and that a Veteran is performing the reattempt.

## Theory
Response times for `POST v0/veteran_readiness_employment_claims` are taking over 60 seconds, causing the proxy to return a 504 to the website FE where the UI displays an error and the SUBMIT APPLICATION button is clickable again. 

### Time between `updated_at`'s on summary report for one PID:

<img width="1260" alt="Screen Shot 2021-10-27 at 9 40 09 PM" src="https://user-images.githubusercontent.com/1021154/139176862-054527c7-c5fa-4fca-a06b-fd27a7669bad.png">

### Response durations:

```
        < 10s   > 10s
10/18   26      889
10/19   323     361
10/20   394     12
10/21   183     493 
10/22   75      552
```
```
        < 30s   > 30s
10/18   32      883      
10/19   346     338
10/20   406     0
10/21   195     481 
10/22   92      535
```
## Proposed Solution
Move all external calls (VBMS upload, emailer) to background jobs.

## Solution Tasks
- [x] #32126
- [x] Create job to handle sending the PDF
- [x] refactor controller to enqueue job if claim saves, otherwise respond how we do now

## Acceptance Criteria
- [x] A path forward has been discovered
- [x] A solution has been implemented
- [x] The problem is gone

**Comment by jason-gcio** [comment]
Latest missing submissions:
PID 54696527, 10/3/2021, Salt Lake City, 20:56:16 UTC
PID 31283514, 10/3/2021, Salt Lake City, 21:50:53 UTC
PID 53923347, 11/3/21, Salt Lake City, 18:39:49 UTC
PID 42237572, 11/15/2021, no regional office / timestamp yet
