### ISSUE TITLE
Add vaccine boosters alert to COVID vaccine mini hub pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28696]
## Issue Description
We need to post an alert on our vaccine mini-hub with information about FDA approval on boosters.

Waiting for JTF approval but current text is:

**Update on vaccine boosters for certain people with weakened immune systems**
 
The FDA has authorized a third "booster" dose of the Pfizer-BioNTech or Moderna COVID-19 vaccine for specific groups of people with weakened immune systems.
We expect to start offering third doses to specific groups of people after we receive final CDC guidance. Please check back soon for more updates.

On the Spanish and Tagalog pages, we also need to add the following:

**Note:** This timely information is only available in English right now. We'll provide translated content as soon as we have it available.

---
## Tasks
- [x] Create alert in Drupal for mini-hub page (Selina)
- [x] Create alert in Drupal for Tagalog and Spanish mini-hub pages (Selina)
- [x] Alert translation team of upcoming work (Randi)
- [x] Review and publish (Randi)
- [x] Send translation team text for review (Randi)
- [x] Add translated text to Spanish page (Selina)
- [x] Add translated text to Tagalog page (Selina)
- [x] Review and publish translated alerts (Randi)
- [ ] Send translated text to volunteer team for final review

## Acceptance Criteria
- [ ] Alerts are live on 3 pages in English
- [ ] Translated alerts are live on pages

**Comment by RLHecht** [comment]
@lunascoop Can you add these alerts as drafts on the pages? You'll have to create a separate one for the Spanish/Tagalog version to add the note at the bottom. Thank you!

**Comment by RLHecht** [comment]
These alerts have been added and published. Thank you @lwalsh617 for the help!

**Comment by RLHecht** [comment]
Update: We removed the English version of the alerts on the Spanish and Tagalog pages since the pages are set for screen readers to only read in that language. We moved the disclaimer on both pages that was below the blue box and put it in the alert instead. When the translated copy comes back, we should update the alert and put the disclaimer as a note at the bottom of the alert.
