### ISSUE TITLE
EKS - scale back volume size for worker nodes

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#28707]
## Description
We had previously increased the eks worker node disk volume size due to Sentry being broken as a temporary band aid.  The sentry-web workers were crashing and throwing core dumps on a regular basis which would fill up the disk space.  This would then prevent any pods from working correctly on the given node.

Now that this is fixed and disk usage is back down to earth, we are safe to reduce this.

![image](https://user-images.githubusercontent.com/76792875/129385365-580cd1b0-1024-4031-bb40-6494a1a70c0c.png)

## Background/context 
https://dsva.slack.com/archives/CJYRZK2HH/p1628858568265500
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28615
https://github.com/department-of-veterans-affairs/devops/issues/9741

---
## Tasks
- [x] Reduce volume size in packer script
- [x] Run packer build GHA for all clusters
- [x] Run rolling update for all clusters
- [x] Clean up stale eks worker node volumes to free up aws space

## Acceptance Criteria 
- [x] Worker nodes on all clusters should be using the reduced volume size and old volumes deleted

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
![image](https://user-images.githubusercontent.com/76792875/129417678-80c3104c-5bc8-4df8-8e6a-1bd11433fc52.png)
![image](https://user-images.githubusercontent.com/76792875/129417738-be532d2b-9f9e-4529-ad63-d43551e22f7b.png)

back up to 30 TiB for AWS ebs space
