### ISSUE TITLE
View Dependents Formlett - Add successful submission messaging

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#28705]
## Description
On successful form submission, the user should be provided with the proper feedback notifying them of the submitted status. 

## Considerations
- should the form close and the notification present as a sibling to the dependents list? 
- how to keep track of dependent status across user session? 

## Tasks
- [x] implement designs for successful submission
- [x] submit PR into vets-website
- [x] update e2e test for this scenario

## Acceptance Criteria
- [x] e2e tests are updated
- [x] successful submission messaging is in place
- [x] A PR has been requested for merging

**Comment by sporeboy** [comment]
When the formlet was presented for design intent review, this was the success state: https://xd.adobe.com/view/d390050f-bc57-4550-a139-a57642c89f8c-86c3/screen/d2639cb1-1014-4916-ac7f-2a25a48e832e
