### ISSUE TITLE
[VAMC] Re-create Menu for all primary pages Walla Walla [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28710]
## Story
As a editor I need a fully represented menu map, so I can assure all pages are represented and have the correct bread crumb URL .

## Goal
Recreate the menu with new Walla Walla pages and URLS.  Menu was removed due to name change.

## TASK
Re associate all required pages to correct areas in Walla Walla after name change
- [x] All required parent sections are created
- [x] All required pages are represented under the correct parent
- [x] All Pages are enabled and disabled as recommended in menu process
- [x] Move all pages from Archive to Draft (With exception of Research and Doing Business with us)

## Acceptance
- [x] Full menu is created so System can now be published

**Comment by ltrombley** [comment]
PENDING:  Final Review & Tugboat process

**Comment by ltrombley** [comment]
Task #28710 - Re-create Menu for all primary pages Walla Walla [BA] - is Complete and moved to Validate
