### ISSUE TITLE
Determine what evidence the VA already has

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28713]
## Issue Description
During usability testing for 526, users were unclear what “evidence VA doesn’t already have” meant. Can we provide clarifying language? 

---
## Tasks
- [ ] We could check with Paul to get a list of things VA will have and use that list to develop new language/direction
- [ ] Does the VA get service history record automatically

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
