### ISSUE TITLE
Form 526EZ - Request for contact information 

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28716]
## Issue Description
During usability testing, we discovered that contact information was requested at the end
---
## Tasks
- [ ] Move request for contact information to the beginning, in accordance with current design standards. 

## Acceptance Criteria
- [ ] Contact information request moved. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
