### ISSUE TITLE
Login.gov MVP - Update documentation of Login.gov auth flow

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28719]
## Issue Description
When integrating the Login.gov Auth flow into vets-api the documentation and visual flowchart should be updated to reflect the setup.

---
## Tasks
- [ ] Update documentation throughout vets-api, va.gov-team, and vets-website* (if required)
- [ ] Provide flowchart of code grant flow

## Acceptance Criteria
- [ ] Documentation is created in repositories
- [ ] Documentation is additionally added to Confluence
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras @joeniquette this probably can be closed
