### ISSUE TITLE
Login.gov MVP - Create new SessionsController

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28727]
## Issue Description
Create new Sessions Controller (v2).  This should add new route (click on the FE or v2/sessions/login to redirect to Login.gov.)

---
## Tasks
- [ ] Creates v2 of SessionsController
- [ ] Add new routes

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
John to sync with Trevor.  Carries to 61.

**Comment by AGarcia-Clarity** [comment]
@nsoutouras @joeniquette this probably can be closed as it is superseded by the Sign in Service
