### ISSUE TITLE
Login.gov MVP - Refactor Accounts table

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28724]
## Issue Description
Refactor the Accounts Table to not rely on ID.me.  The Redis cache should also probably be removed.  We also need to update so that the Login.gov UUID is stored and do some table validation.

---
## Tasks
- [ ] Remove reliance on ID.me in the Accounts table
- [ ] Remove Redis cache
- [ ] Update Accounts table schema to add a Login.gov UUID
- [ ] Complete account table validation (confirm a created Login.gov UUID has an ICN); after subsequent sign-ins we need the mapping for ICN (IAL2 call if we don't have that information)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
