### ISSUE TITLE
Login.gov MVP - Remove v0 SessionsController

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28722]
## Issue Description
Because SSOe is at 100% inbound and outbound we can safely remove the `V0` SessionsController instance for auth.

---
## Tasks
- [ ] Remove v0 SessionsController

## Acceptance Criteria
- [ ] Only v1 SessionsController remains
- [ ] No impact to existing users
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Don't forget to remove all of the related feature toggles as well.

**Comment by nsoutouras** [comment]
Carries to 61.  Waiting for PR.
