### ISSUE TITLE
COVID-19 updates to FAQs and vaccine page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28754]
## Issue Description
We made a few content updates to a question in the FAQs and in a section of the vaccine page. These need to be added to the page as well as translated and updated on the chatbot. 

[https://app.zenhub.com/files/133843125/d4c713b8-2029-42ec-bc4e-f534f59e5515/download](https://app.zenhub.com/files/133843125/d4c713b8-2029-42ec-bc4e-f534f59e5515/download)

## Tasks
- [ ] Update English FAQs and vaccine pages (Selina)
- [ ] Review and publish (Randi)
- [ ] Send to translation team (Randi)
- [ ] Update chatbot (Selina)
- [ ] Input translated copy (Selina)
- [ ] Review and publish (Randi)
- [ ] Send to volunteer translators for final review (Randi)

## Acceptance Criteria
- [ ] Updated content is on English page
- [ ] Chatbot is updated
- [ ] Updated content is on Spanish and Tagalog pages

**Comment by RLHecht** [comment]
@lunascoop this is the ticket from the work we did last Friday. Can you please also update the chatbot to reflect these changes? Thanks!

**Comment by lunascoop** [comment]
Chatbot updates are live in production.

**Comment by RLHecht** [comment]
We didn't make any updates to the vaccine CLP. Do we want to add a question on boosters to the FAQs? @DanielleThierryUSDSVA  https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/

**Comment by RLHecht** [comment]
@lunascoop Here are the translations we've been waiting on for this. 

[https://app.zenhub.com/files/133843125/d5e1da50-be0e-4eee-b94d-3923e5e09b03/download](https://app.zenhub.com/files/133843125/d5e1da50-be0e-4eee-b94d-3923e5e09b03/download)

[https://app.zenhub.com/files/133843125/4b1add89-d8df-44ae-b57c-7cfc873ee886/download](https://app.zenhub.com/files/133843125/4b1add89-d8df-44ae-b57c-7cfc873ee886/download)

**Comment by RLHecht** [comment]
@lunascoop here's the tagalog
[13669 _COVID-19 contrent updates 08.11.21-2 Tagalog Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7156177/13669._COVID-19.contrent.updates.08.11.21-2.Tagalog.Final.docx)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Preguntas frecuentes sobre el coronavirus: http://preview-prod.vfs.va.gov/preview?nodeId=14580 (For the question Can I visit a Veteran in a VA health facility?, we need the last sentence of the For nursing homes, inpatient hospital stays, and other long-term care facilities: bullet point translated in Tagalog. The Spanish page is fine.
"We also have exceptions in place for Veterans who are in their last stage of life.")
- Mga karaniwang katanungan tungkol sa Coronavirus: http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by RLHecht** [comment]
These pages are now published. I'm sending the missing line of text to the translators as well.

**Comment by RLHecht** [comment]
@lunascoop Here is the missing line of text we were waiting on: [Uploading... 13741_Tagalog FAQs line of text for translation 91421 Final.docx]

**Comment by lunascoop** [comment]
@RLHecht replaced sentence in Tagalog page w/missing line of text.

Mga karaniwang katanungan tungkol sa Coronavirus: http://preview-prod.vfs.va.gov/preview?nodeId=16475

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published the page.
