### ISSUE TITLE
Login.gov MVP - Create record if missing MPI entry (login.gov flow)

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28756]
## Issue Description
When users don't have an entry in MPI and use the Login.gov auth flow. We should make a call to MPI (via IAL2 call) and if nothing is returned we need to create a record in MPI for that user.

Step 1. Figure out how to do the above
Step 2. Update the token for the add (eAuth has the ability currently, we need to duplicate it additionally)

**Dependency**
We need to get additional permissions for the ability to create MPI records.  What we need for the staging & production prototypes.

---
## Tasks
- [ ] Get additional permissions to create records in MPI
- [ ] Make a call to MPI (IAL2) after user authenticates with Login.gov
- [ ] Conditionally create a record if the IAL2 MPI call returns nothing otherwise send data back as normal
- [ ] Update the token for adding the record

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras this can be closed
