### ISSUE TITLE
Login.gov MVP - If MPI changes

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28755]
## Issue Description
If MPI changes (figure out out reconcile when ICN changes, call MPI with the old ICN number should respond with the new ICN.  Multiple ICNs, there should be a priority, resolving as many as possible.)

MPI should update the accounts table when called storing entries we can look at ICN or EDIPI with ICN being the priority.

---
## Tasks
- [ ] Create a priority system for ICNs when multiple ICNs are found 
- [ ] Reconcile when ICN changes (calling MPI with old ICN resolves new ICN number)
- [ ] Update accounts table with new / higher priority ICN

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
@AGarcia-Clarity Is this still relevant?

**Comment by AGarcia-Clarity** [comment]
@nsoutouras I think we can close it.  I think this was a part of the BE solution for the Accounts Table.  I'm going to close it for now.
