### ISSUE TITLE
Login.gov MVP - Refactor Sign In Modal for Login.gov

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28759]
## Issue Description
Work with Amanda to narrow down the design & implementation of the SignInModal.  Using feature toggles add the ability to authenticate with Login.gov

---
## Tasks
- [x] Update feature toggle usage on the frontend
- [x] Research and formulate Modal's design plan with Amanda
- [ ] Verify design with Design team & VSA Public websites (for design & content)
- [x] Add the Login.gov button with feature flag disabled for users
- [x] Confirm with VSP Identity backend engineers on the URL to point to for Login.gov
- [x] Complete accessibility testing through tabs, screen readers (with voiceover), magnification, etc. through both integration testing & manual testing
- [x] Update Sign In Modal unit and integration tests for Login.gov

## Acceptance Criteria
- [ ] I can see the Login.gov button when the feature flag `loginGov` is enabled in Flipper
- [ ] VSA Public websites & Design team have signed off on feature
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
MSI - Unblocked

**Comment by nsoutouras** [comment]
Stays open until Login.gov rollout.
