### ISSUE TITLE
Login.gov MVP - Remove reliance on ID.me UUID

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28761]
## Issue Description
Remove reliance on the ID.me UUID in the Accounts Table and other places across the vets-api codebase.

---
## Tasks
- [ ] Research/document all the places ID.me UUID are used
- [ ] Remove ID.me UUID from Accounts table
- [ ] Remove ID.me UUID (from researched places in the codebase)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras I'm pretty sure this work has already been completed by Trevor B.  This can be closed
