### ISSUE TITLE
Login.gov MVP - Logging & monitoring

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28765]
## Issue Description
Figure out the logging and monitoring mechanisms to be used for Login.gov.  It would be preferred if we could use a service agnostic appliance so we can drop in data anywhere (DataDog, Sentry, etc.)

---
## Tasks
- [ ] Figure out logging & monitoring mechanism
- [ ] TBD (update)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
