### ISSUE TITLE
Login.gov MVP - MHV migration & research

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28763]
## Issue Description
We need to determine if MHV makes a request to MPI.  We need to figure out how often and if they need everything inside the MPI call every time.

---
## Tasks
- [ ] Research and document how MHV (My HealtheVet) gets its data
- [ ] Formulate a plan for migration work (aka reduce MPI calls) 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
