### ISSUE TITLE
Create Oncall Playbook for Handling Alerting Canaries

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#28768]
## User Story

As the #oncall engineer, I need a playbook that tells me how to handle an alerting canary.

## Tasks
- [x] Discover where other oncall playbooks exist in Confluence
- [x] Create a draft of the canary alert playbook in that space
- [x] Ask for reviews of draft playbook from stakeholders
- [x] Publish finalized version of playbook

## Expected Behavior

A playbook is available in the internal-facing Confluence space giving the oncall engineer a step by step playbook for resolving an alerting canary.

## Acceptance Criteria

- [x] Oncall canary playbook published to Confluence

**Comment by pjhill** [comment]
@rjohnson2011 -- This looks great! Go ahead and publish, please!

**Comment by rjohnson2011** [comment]
Published!
