### ISSUE TITLE
Login.gov MVP - Research LOA and IAL

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28767]
## Issue Description
Research the differences between LOA (Level of Assurance) and IAL (Identity Assurance Level) as they are not one-to-one.  Document how it is defined and how it is used according to VA.gov, NIST, and Login.gov

---
## Tasks
- [ ] Determine the differences/similarities LOA and IAL
- [ ] Document differences/similarities of LOA and IAL

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras @joeniquette this probably can be closed
