### ISSUE TITLE
Login.gov MVP - Ensure fail hard when MPI is down

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28774]
## Issue Description
We want to fail hard when MPI is down.  The `vets-api` backend should send a response to the the frontend to inform users about MPI being down.

---
## Tasks
- [x] Backend sends a response when MPI is down
- [x] Frontend receives MPI down response and displays to user (will require VSA public facing websites approval for content)

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
