### ISSUE TITLE
Login.gov MVP - Refactor VSP Identity statsd

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28773]
## Issue Description
Refactor the `statsd` to accommodate the addition of Login.gov and removal of the V0 SessionController instance.  A feature flag should additionally be added for when the migration to DataDog (might require research)

---
## Tasks
- [ ] Research how DataDog collects metrics
- [ ] Add a feature flag to conditionally use statsd and DataDog
- [ ] Refactor the current `statsd` to add Login.gov & remove v0 instance

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
