### ISSUE TITLE
Search for MISSION act website references and links (Content Support)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28779]
## Issue Description
The MISSION Act [website](https://missionact.va.gov/) is being taken down the end of September. Sitewide Content needs to do an audit of pages where we link to it or make reference to it and then remove them.  Sitewide Content is requesting support from the PW team to find instances of MISSION Act in support of removal actions.

## Tasks
- [x] Public Websites devs to do a search of MISSION Act 
- [x] Communicate found results to content ISO removal of instances of links to MISSION Act page

## Acceptance Criteria
- [x] All MISSION Act references are identified ISO content team

**Comment by kelsonic** [comment]
Cross-referencing: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28079

**Comment by brianalloyd** [comment]
Validate, closing in support.  Thanks gents.
