### ISSUE TITLE
Login.gov MVP - Collect metrics (verbose logging)

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#28772]
## Issue Description
Log and account for metrics.  Initially we want to start collecting data about everything then slowly start removing metrics that aren't important to us.  This will mostly be verbose logging and only happen in the staging environment.

---
## Tasks
- [ ] Enable verbose logging for the Login.gov auth flow

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
