### ISSUE TITLE
[Design] Direct Deposit: create design/content for only allowed IDme accounts to access DD forms

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28794]
## Background
As reported in #28728 and #28729, we had to temporarily shut down direct deposit on VA.gov (read and write functionality) due to reports of incidents of fraud. We've come to learn that the vulnerability exists specifically with users who access dd through DS and MHV. The plan is to reactivate DD for users who use IDme, so we need to create some messaging explaining the situation.

## Tasks
- [ ] draft content outlining the situation
- [ ] review with content 
- [ ] create design/mockup with approved content 
- [ ] hand-off to FE for implementation

**Comment by andaleliz** [comment]
@lihanli, @tmitchellgcio and/or @erikphansen  - will people who log in via MHV or DSLog even be able to get to DD?

**Comment by erikphansen** [comment]
@andaleliz My initial thought was that Direct Deposit should be available in the nav since that would be the most logical place to tell them they need to sign in with ID.me to view and edit their DD info. But it's really up to you.

**Comment by andaleliz** [comment]
@erikphansen that makes sense to me, just wasn't sure if there was anything happening from a code perspective that would block people logging in via the other channels from even getting that far.

**Comment by erikphansen** [comment]
@andaleliz not yet. Right now we don't look at how they signed in, at all. That'll be new work.

And a note just for myself: we'll also need to make sure the FE doesn't even call the 2 direct deposit APIs unless they are signed in via ID.me.

**Comment by andaleliz** [comment]
[Submitted ticket for content review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28986)
