### ISSUE TITLE
[VAMC] Prepare North Arizona health care for Dual-state VISN-22 [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28795]
## STORY
As a web user I need to confirm all broken links, updates, and content has been updated prior to Dual-state publishing, so I can be assured the latest and best system input is loaded to Dual-State

## Resources
[Tugboat](https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Validate that each page:
- [x] Utilize Dual-State Prep sheet to walk through all possible fixes to include, but not limited to:
- [x]  Update any last minute changes provided by PAO and approved for input
- [x]  Confirm or resolve ACTIVE and true broken or redirected link, 
- [x]  Update pages specified in Content review with updated material (tech-debt)
- [x]  Validate there are no Additional detail pages or list page duplicates that have not been removed
**Tugboat Actions**
- [x] Rebuild and refresh Tugboat instance of System
- [x]  Publish all nodes for specific system
- [x]  Release content (Report any issues in release)
- [x]  View logs and resolve any broken links
**Facilities incldude:**
- [x] Bob Stump Department of Veterans Affairs Medical Center
- [x] Kingman VA Clinic
- [x] Flagstaff VA Clinic
- [x] Lake Havasu City VA Clinic
- [x] Anthem VA Clinic
- [x] Cottonwood VA Clinic
- [x] Chinle VA Clinic
- [x] Holbrook VA Clinic
- [x] Page VA Clinic
- [x] Tuba City VA Clinic
- [x] Polacca VA Clinic
- [x] Kayenta VA Clinic

## Acceptance Criteria
- [x] All pages in check list have been tested
- [x] All additional pages that are NOT duplicates have been added to list and have been checked
- [x] Updates suggested from Staging have been input into system
- [x] Tugboat broken links have been resolved in Prod.cms.va.gov

**Comment by EdwardBoehme05** [comment]
Story moved to Validate, pending CMS fix in Tugboat. After fix is implemented, will attempt to run again.

Lisa Trombley  8/24/21:
@Ed Boehme It looks like we're having the same issue as before.  I'll let CMS know.  You can move your story to Validate with a comment that it's Pending CMS fix in Tugboat, then try to run it again in the morning.  Thx!

Lisa Trombley  < 1 minute ago
@Ed Boehme CMS Ticket:  https://dsva.slack.com/archives/CDHBKAL9W/p1629840119093800      cc: @Stan Gardner
