### ISSUE TITLE
Post-pilot enhancement: update VA.gov Experience Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28793]
## Issue Description
In the [Staging Review pilot ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25763), Product Support identified a [series of enhancements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25762) that should be fixed prior to going live with the new process. This ticket will address updating the VA.gov Experience Standards for "component that isn't functioning" and "issues with invalid and incorrect links."

---
## Tasks
- [x] Add a standard OR modify a standard to address "component that isn't functioning."
- [x] Add a standard OR modify a standard to address "issues with invalid and incorrect links."
- [x] Ensure each modified or added standard has the following:
   - Category
   - Category Number
   - Standard (the expected behavior)
   - Issue (the problematic behavior)
   - Issue Number	
   - WCAG Reference (if applicable)
   - Impacted practice area (a11y, Content, Design, IA)
   - Severity
   - TestRail Test ID (if applicable)
   - TestRail Test ID Grouping (if applicable)
- [x] Document 2 new standards in this ticket (as detailed in comments below)
- [x] Contacting Meg, Martha, Ryan, Beth and Danielle (cc Rachael) on #vsp-collaboration-cycle channel and ask for their feedback/approval on the 2 new standards.
- [x] Once approved, add 2 new standards to [VA.gov Experience Standards google sheet](https://docs.google.com/spreadsheets/d/1IkIX7CgbFneFvlia1r9mYD8QU7uML5HWILkM7qsxizs/edit#gid=333168944)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
Issue #1:
Component that isn’t functioning (i.e. breadcrumb link didn’t work on check-in screens)
- the standards cover missing components and non-standard components, should they also cover the scenarios where a component is there, but it’s not working or not working correctly?
- Maybe if they are not working correctly they would be non-standard?
- The example I had was a breadcrumb that wasn’t working - maybe this should remain as an Other because its a QA issue?
- Another example would be if the left nav was not rendering the child pages accurately, this happens in VAMC world.  It’s the standard nav, but something isn’t functioning right, which could be a content issue or a nav issue.  So maybe the “non-standard” issue needs to cover “not functioning in a standard way” as well?

Issue #2:
Issues with invalid and incorrect links - not the labels, but the actual links - there isn’t a corresponding standard
- Broken links should be caught by QA, (I think that’s the case?) so that is different, but we may want to log those as well?
- Issues with link labels are captured in standards, so that is covered
- Links that take you to the wrong destination URL are not covered in a standard
- Links to anchor tags that don’t take you to the anchor are not covered in a standard
- A couple of options/thoughts:
   - This could possibly fit under user flow as a wayfinding/navigating issue - “All provided links in the user flow must be accurate and functional”.
   - Or you could change the “Link and button labels” category to just “Links and buttons” to more inclusive of the function of links/buttons, not just the labels.

**Comment by shiragoodman** [comment]
Issue # 1 - create new standard.
Design components and patterns in use are not functional.
Category - Components and pattern standards
Category Number - 04
Standard (the expected behavior)
Issue (the problematic behavior)
Issue Number - 12
WCAG Reference (if applicable) - N/A
Impacted practice area (a11y, Content, Design, IA) - all
Severity - LB
TestRail Test ID (if applicable) -N/A
TestRail Test ID Grouping (if applicable) - N/A

**Comment by shiragoodman** [comment]
a link or CTA did not take you to the intended destination. (wordsmith)
Category
Category Number
Standard (the expected behavior)
Issue (the problematic behavior)
Issue Number
WCAG Reference (if applicable)
Impacted practice area (a11y, Content, Design, IA) -IA, Content, A11y, Design
Severity - D (if the user is able to complete their task, Non LB)
TestRail Test ID (if applicable)
TestRail Test ID Grouping (if applicable)
