### ISSUE TITLE
Creating new page for COVID-19 vaccine additional dose

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28801]
## Issue Description
Now that the FDA has approved third doses of the COVID-19 vaccine for certain people with weakened immune systems, we are going to create a child page of the vaccine mini-hub to use for information and questions pertaining to additional doses. This page will also need to be translated and we will need to audit the main vaccine page for mentions of boosters and how long vaccines last. 

@mnorthuis will provide the new url for the child page and the 2 translated pages.

~~Here is the Word doc from Danielle, though the text may be changing after Tuesday's COVID call with Lauren:~~

~~[https://app.zenhub.com/files/133843125/39dde05f-c004-4f1c-a54d-7e792c84229d/download](https://app.zenhub.com/files/133843125/39dde05f-c004-4f1c-a54d-7e792c84229d/download)~~

**Here is the JTF approved copy to use:** [https://app.zenhub.com/files/133843125/e98275ca-5c28-4b94-8a54-10ee252ab9ff/download](https://app.zenhub.com/files/133843125/e98275ca-5c28-4b94-8a54-10ee252ab9ff/download)

---
## Tasks
- [x] Get JTF approval on content for new page
- [x] Send content to translators
- [x] Build out new page in Drupal 
- [x] Rework any content on main vaccine page that needs to be changed
- [x] Add links to new page where necessary
- [x] Build out Spanish page
- [x] Build out Tagalog page
- [x] Send live pages to volunteer translation team for final review

## Acceptance Criteria
- [x] New additional vaccine dose page is live

**Comment by RLHecht** [comment]
In combing through the vaccine mini-hub, the 2 questions that would need to be updated are **How many doses of a COVID-19 vaccine will I need to take? Will I need a booster dose?**

My recommendation is updating the first 2 sentences to:
The number of doses you’ll need will depend on the specific COVID-19 vaccine. The CDC now recommends a third vaccine dose for certain groups of people with weakened immune systems who received either the Pfizer-BioNTech or Moderna COVID-19 vaccine.
Get the latest updates on additional COVID-19 vaccine doses (link to new page)

The 2nd question is **How long will a vaccine protect me from COVID-19?**

My suggestion is changing the answer to the following: 
We won’t know how long protection will last until we have more data on how well the authorized COVID-19 vaccines work. The CDC now recommends a third vaccine dose for certain groups of people with weakened immune systems who received either the Pfizer-BioNTech or Moderna COVID-19 vaccine.
Get the latest updates on additional COVID-19 vaccine doses (link to new page)
For answers to more frequently asked questions about COVID-19 vaccines, go to the CDC website.

**Comment by mnorthuis** [comment]
### IA recommendations:

**Approach:**
- A child page of the existing Covid-19 vaccine page will be created (1 for each language) that will include information on BOTH the additional doses currently recommended for immunocompromised as well as booster shots.  The booster shot info will elude to more information coming.
- A combined page will allow us to capture all users regardless of the type of additional shot they are looking for without having to understand the difference. 
- The H1 and URL should include reference to both of these key terms:  "additional doses" and "booster shots"
- Although we do not have information on booster shots yet, we are leading with that term in the H1 and URL given it is 1) been approved for roll-out this fall and 2) the primary keyword used in SEO/by individuals looking for information on follow-up shots.
- Risk: this approach does not highlight the term "new target dose", however, that term has not yet been broadly utilized.  If this term becomes a buzz word, we can re-evaluate this page at that time and adjust if necessary.  

**URLs:**
www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/
www.va.gov/health-care/covid-19-vaccine-esp/booster-shots-and-additional-doses/
www.va.gov/health-care/covid-19-vaccine-tag/booster-shots-and-additional-doses/

**Entry Points:**
- Health care left nav
  - New page is a child of the existing vaccine page, there is a child page for each language
- Covid-19 vaccine page (https://www.va.gov/health-care/covid-19-vaccine/)
  - Include link to new child page in the alert about additional doses at top of page
  - Include reference info for those looking for additional doses or boosters in the blue box and link to new child page
  - Consider info and links about additional doses and boosters in the following sections: 
    - Who can now get a vaccine
    - Basic information about getting your vaccine at VA
    - Questions you may have about COVID-19 vaccines > Getting a Covid-19 vaccine
 - Coronavirus FAQ page (www.va.gov/coronavirus-veteran-frequently-asked-questions/)
   - Review for placement of info and link to differentiate availability and how to schedule for initial doses versus additional doses and boosters
 - Chatbot (www.va.gov/coronavirus-chatbot/)
   - Review for possible inclusion of questions related to who is eligible for additional doses and boosters and how to get them.

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here is the new page build out: preview-prod.vfs.va.gov/preview?nodeId=34054

Here's a preview of the vaccine page with new alert and changes: preview-prod.vfs.va.gov/preview?nodeId=11463

Here's the preview of the FAQs page with new question added: preview-prod.vfs.va.gov/preview?nodeId=3014

@lunascoop You can use the copy in the top of the ticket to update the chatbot. There's 1 new question to add and if those other 2 questions about how long the vaccine lasts and if there are boosters are in there, we need to update with the language we have in the word doc.

I'll send the approved copy to the translators now as well.

**Comment by RLHecht** [comment]
The new page was published as well as the updates to the FAQs and vaccine pages. And I sent the text to the translators.

**Comment by lunascoop** [comment]
Chatbot has been updated.

**Comment by RLHecht** [comment]
@lunascoop Here are Mateo's comments. Can you please update the pages with his changes?
[COVID Vaccine Online Records.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7188324/COVID.Vaccine.Online.Records.docx)

[VHA Translation COVID Vaccine Online Tagalog.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7188327/VHA.Translation.COVID.Vaccine.Online.Tagalog.docx)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. I think these pages were originally tracked in another ticket (#29572 )

Paano makuha ang iyong talaan ng bakuna para sa COVID-19 online: http://preview-prod.vfs.va.gov/preview?nodeId=35108

- Had to shorten title for meta title tag (perhaps we should let the translators know that the title has to be w/in a certain character limit)
- For step 4 of the 1st process list, I partially updated the translation of the first bullet, second sentence. The translation provided seems to have started mid-sentence. I'm unsure if that was intentional. Based on Google translate, adding "iyong" to the current sentence vs. the translation provided sounds closer to the English version.
- I'm unsure about the "More helpful information" translation. It seems the current version is closer to the one they provided. I did make the change though, but perhaps it should be confirmed.

Cómo obtener su historial de vacunas COVID-19 en línea: http://preview-prod.vfs.va.gov/preview?nodeId=35120

**Comment by RLHecht** [comment]
@lunascoop Here are Mateo's changes. 
[Addtional Doses_Boosters Tagalog.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213344/Addtional.Doses_Boosters.Tagalog.docx)

[trans-COVID092021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213351/trans-COVID092021.docx)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. The VHA translators also provided translations in #30174 so they are combined for the Spanish page (since the Spanish translation in your comment above is a bit outdated). I referred to Mateo's changes for the Tagalog page.

Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394
Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408

**Comment by RLHecht** [comment]
Thanks @lunascoop I've published both of these pages.

**Comment by RLHecht** [comment]
These pages are live with Mateo's changes and now complete. Closing ticket.
