### ISSUE TITLE
NOD: Minor bug fixes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28802]
## Description

Need to fix some minor issues/bugs in the NOD code

## Tasks

- [ ] Fix "go back" link. Change to `<Link>`
- [ ] Typo corrections

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
