### ISSUE TITLE
Change backend name for services dropdown box

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28825]
## Issue Description
Naming conventions for the community care provider service type dropdown made troubleshooting a recent PPMS outage and latency #28780 more difficult 

Current name: service
Requested name: `services raw` or `services text`

---
## Tasks
- [ ] Update name for community care provider service type dropdown on the backend only

## Acceptance Criteria
- [ ] Backend name for values in the community care provider service type dropdown is updated
- [ ] Front end display is unchanged

**Comment by mmiddaugh** [comment]
No longer needed
