### ISSUE TITLE
Editorial support for Vet Center operating status details

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28828]
## Issue Description
**Feature request from Jessica for Vet Centers:** As Vet Center leadership, I would like Vet Center editors to be able to select operating status details for my Vet Center from a predefined list so that I can ensure consistent messaging and so my editors can be more efficient. 

---
## Tasks
- [ ] TBD following discussion with CMS

## Acceptance Criteria
- [ ] Vet Center editors can select operating status details from a list of predefined choices
- [ ] List of available choices for operating status details are based on selected operating status

**Comment by mmiddaugh** [comment]
@davidconlon fyi

**Comment by mmiddaugh** [comment]
Added to [Enhancements/optional features for Vet Centers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37529) and now closing this issue
