### ISSUE TITLE
Remove "disallow" entries from Robots.txt file on August 18th

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28820]
## Issue description 
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
Remove the following system names from robot.txt file on August 18, 2021
- [ ] Hudson valley health care
Restore the following system names to the robot.txt file on August 18, 2021 (they did not go live as expected)
- [ ] Nebraska health care
- [ ] San Francisco health care

## Acceptance Criteria
 System names are removed from robot.txt file on August 5th
