### ISSUE TITLE
Claim Status Tool - Frontend Assessment - Phase 1

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28835]
## Issue Description
Assess frontend design of CST

---
## Tasks
- [x] Review frontend design and document design recommendations 

## Acceptance Criteria
- [x] Documentation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
We have created a design that shows the frontend in a new template layout. It can be found here:

https://www.sketch.com/s/64bb337a-e31f-4a21-a92f-d89b50cba668/a/4aAdenq
