### ISSUE TITLE
[RESEARCH] Emergency response flow (VAMC/Vet Center)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28831]
## Issue Description
As a Veteran, I need to know where to find services during an emergency so that I can continue my care or get the support I need. 

VHA Mobile units can be deployed as emergency response units for a variety of purposes, depending on the scenario. Examples: delivering primary care and mental health counseling in high visibility locations and non-clinical support such as food and showers. They can be staffed by VHA even when typically staffed by Mobile Vet Center and be deployed to other health systems or states as needed. 

Communicating MMU/MVC deployment after an emergency may not be done consistently on VA.gov, or at all.

## Questions
Where do Veterans expect to find information about available mobile services during an emergency?
Where does the operating status/situational update flow fit within the Veteran experience?

## Reference
- [Sample VAMC situation update/operating status page](https://www.va.gov/pittsburgh-health-care/operating-status/) 

---
## Tasks
- [ ] Review current process for operating status/situation update
- [ ] Design research plan to understand the communication options and flow during a VHA emergency response

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by mmiddaugh** [comment]
This will likely be revisited at some point. Closing until that time.
