### ISSUE TITLE
Add alert about fund exhaustion to VET TEC page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#28851]
## Issue Description
Stakeholder Tammy Hurley informed us that funds will be exhausted for the VET TEC program in a few weeks. We will need to put an alert on the page similar to what we have done in previous years. Here is the alert we ran last year:

![Screen Shot 2021-08-17 at 10.28.22 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4c6c0deb-f05c-4946-8d91-5f13d3a0bbb9)
 
Tammy will notify us when it is ready to be published. 

## Tasks
- [ ] Create alert for VET TEC page
- [ ] Publish alert on page
- [ ] Alert stakeholder that page is live
- [ ] Create new ticket for following up when alert should be removed

## Acceptance Criteria
- [ ] VET TEC funds alert is live on the page
