### ISSUE TITLE
Review Canaries and Identify Metrics for Synthetic Monitors

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#28852]
## Issue Description
As we complete our work on Synthetic monitors, we'd like to look at what metrics can and should be tracked in BigQuery

---
## Tasks
- [ ] Review all canaries that we have operating currently
- [ ] Discuss what metrics can/should be tracked in a dashboard that we create

## Acceptance Criteria
- [ ] We have a list of data and data sources that we want to track in BigQuery

**Comment by pjhill** [comment]
Unorganized ideas from just me --

- # of times a canary fails per day
- # of times a canary alerts per day
- Heat map for the time of day that the canary alerts
- # of times action is taken by oncall engineer to resolve canary
- # of times canary self-resolves

**Comment by rjohnson2011** [comment]
Solid ideas for the Canary alerts, especially tracking the frequency of 2x failures that would trigger PagerDuty.

I'm not sure how to answer the DataDog questions as I don't have access to the platform. Let me know if I should follow up with a team member who is authorized.

**Comment by rjohnson2011** [comment]
Consulted Ops regarding getting data from CloudWatch into Domo. Demian suggested using Domo's CloudWatch connector - https://www.domo.com/appstore/connector/amazon-cloudwatch-connector/overview 
Attempted this and got a permissions denied error. I created a ticket to get the necessary credentials to authorize the connector: https://github.com/department-of-veterans-affairs/va.gov-team/issues/29641

**Comment by JoeTice** [comment]
I'm going to move this to review - we'll use this ticket as reference, but the remainder of the SYnthetic Monitoring portion of QA Dashboards will happen under another initiative for Q4
