### ISSUE TITLE
Chapter 31 - Clear SIP data on form submission

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#28864]
## Description
A recent bug was discovered where some of our forms weren't properly clearing save in progress data on successful submission. This leads to an scenario where a user may return to the form introduction page, see they have a form in progress, click continue, and then experience a broken page. We need to make sure we're properly clearing save in progress data in vets-api after successful form submission.

## Considerations
- [example of needed call in chapter 36](https://github.com/department-of-veterans-affairs/vets-api/blob/01cd68147bf1b99ede386d1a8dd0e58ed881f480/app/controllers/v0/education_career_counseling_claims_controller.rb#L17)

## Tasks
- [ ] add method to clear data properly
- [ ] confirm on frontend sip data has been cleared
- [ ] PR has been submitted to vets-api

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by kathleencrawford** [comment]
Awesome job - thank you @micahchiang !
