### ISSUE TITLE
Veteran Surveys

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28869]
## Issue Description
Veteran Surveys will allow us to gather direct customer feedback

---
## Tasks
- [ ] Document where we want to put surveys

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
We heard from Lauren A. that surveys are not allowed on this contract due to privacy concerns. Closing ticket.
