### ISSUE TITLE
Post-pilot enhancement: Update DraftingTemplate for clarity and usability

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28861]
## Issue Description
In the [Staging Review pilot ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25763), Product Support identified a [series of enhancements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25762) that should be fixed prior to going live with the new process. This ticket will address updating the DraftingTemplate (the Google Sheets template that Collaboration Cycle reviewers use to document feedback) to address the following concerns:

1. Add "Do Not Edit" notifications to the tabs and/or first cell of the sheets that are not to be edited by reviewers
2. Add practice area next to point of contact in "Github Upload" tab
3. Remove instance number from "Supporting Guidance" link in "Github Upload" tab
4. Change "Supporting Guidance" heading to "VA.gov Experience Standards" in "Github Upload" tab

---
## Tasks
- [x] Add "Do Not Edit" notifications to the tabs and/or first cell of the sheets that are not to be edited by reviewers
- [x] Add practice area next to point of contact in "Github Upload" tab
- [x] Remove instance number from "Supporting Guidance" link in "Github Upload" tab
- [x] Change "Supporting Guidance" heading to "VA.gov Experience Standards" in "Github Upload" tab
- [x] Update template so all practice area labels associated with an issue are added (and not just the label from the individual who wrote the issue)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
