### ISSUE TITLE
Claim Status Tool Notification Dashboard

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28877]
## Issue Description
For CST, two APIs are used /v0/appeals and v0/evss_claims_async.  We need to develop a dashboard to indicate service availability so we know if our APIs are up and running

Utilized Grafana to create 2 new tracking dashboard for the two vets-api endpoints.

I also created a dashboard for HLRs creates since while I was in there.

I don't think datadog is ready for general use yet.

---
## Tasks
- [x] Tech discovery - development and implementation of availability dashboard (Grafana vs. Data Dog)

## Acceptance Criteria
- [x] Documentation on review and decision. Additional tickets created for implementation if needed. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Made an alert for the appeals status and will make one for the claims status later today http://grafana.vfs.va.gov/d/WxQ9lkUGz/claims-and-appeals-alerts?orgId=1&from=1630958096490&to=1631115414410
