### ISSUE TITLE
[FSR] Add SSN and fileNumber to Submission Payload

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28878]
## Issue Description
We are currently not passing `ssn` and `fileNumber` in the submission payload and should be added

```
  "personalIdentification": {
    "ssn": "string",
    "fileNumber": "string",
    "fsrReason": "string"
  }
```

---
## Tasks
- [ ] add `ssn` and `fileNumber` properties to transform.js

## Acceptance Criteria
- [ ] ssn and fileNumber properties should be added to submission payload
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
