### ISSUE TITLE
Phase 1 - Claim Status Tool Technical Discovery

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28870]
## Issue Description
As a Back-end engineer on the Claims & Appeals team, I need to become a SME of the current Claim Status API so that I can better understand backend systems and interdependencies. 

---
## Tasks
- [ ] Determine how to run CST locally (share with FE Engineer)
- [ ] Conduct audit of backend system, document technical product details/findings and areas in need of further research. 

## Acceptance Criteria
- [ ] Product technical aspects documented in Github
- [ ] New tickets created for follow-on tasks
---

**Comment by michelpmcdonald** [comment]
Used time in this ticket to research 526 - claim status tool code flow and to get them running locally:

Dev Notes Are here:

https://docs.google.com/document/d/1qLzsT5TuhE7CqPkDhVeSHrT4O08ZLO2ZouXqOgFxej0/edit?usp=sharing
