### ISSUE TITLE
NOD Documentation 

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28871]
## Issue Description
Notice of Disagreement post-mortem and why we made the decisions we did

---
## Tasks
- [ ] Document 

## Acceptance Criteria
- [ ] Documented and stored on GitHub
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
