### ISSUE TITLE
HLR: submit to v2 endpoint

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28879]
## Description

Once the HLR v2 API is done, hook up the front-end to submit to the proper versioned endpoint based on the v2 feature flag.

## Tasks

- [ ] Hook up FE to BE API
- [ ] Test sample submissions using test user 237 (v2 feature flag is set)
- [ ] Update tests 
- [ ] Proper error handling/messaging

## Definition of done

- [ ] FE submissions successful
- [ ] All tasks complete
