### ISSUE TITLE
Add Getter Method for `Vista Account Numbers` to User model

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#28888]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
In order to support the Healthcare Experience Team, a users's Vista Account Numbers, as derived from their GCID string, needs to be made available as a public-facing method on the User model.

Original conversation: https://dsva.slack.com/archives/CSFV4QTKN/p1628877184065100

---
## Tasks
- [x] Add new regex pattern to `gc_ids` to parse out VHA facility ids and vista account numbers as part of the `parse_xml_gcids` function
- [x] Save VHA facility ids and vista account numbers as key/value pairs to the user model
- [x] Make the VHA facility/vista account hash externally available in vets-api

## Acceptance Criteria
- [x] A user's Vista Account Numbers will be set upon login and available across vets-api
