### ISSUE TITLE
Get "Weblate" Up and Running In Dev EKS Cluster

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#28886]
## Description
An external team has requested a testing instance of a tool/service called "Weblate" for testing out some translation management.

## Background/context 
https://dsva.slack.com/archives/CBU0KDSB1/p1629227079096000

## Technical notes
Adam and team will need RBAC access to the dev eks cluster for this to really be feasible I would think in addition to the service being deployed there

---
## Tasks
- [x] Weblate service deployed to dev eks cluster
- [x] Requesting team has proper permissions to dig in and test functionality of Weblate service

## Acceptance Criteria 
- [x] Weblate service up and running on dev eks cluster and requesting team is able to access, test, etc.

**Comment by dginther** [comment]
Weblate is up and running in the dev EKS cluster.
It should be available behind the SOCKS proxy at https://weblate-dev.vfs.va.gov
The Postgres Database is an RDS database, and the Redis is an Elasticache redis.
I can provide the admin username and password via Keybase.

**Comment by dginther** [comment]
![Screen Shot 2021-08-20 at 8.58.33 AM.png](https://images.zenhubusercontent.com/5ce30eebaa8711267b95ebdf/2a249c2a-5f45-4a5a-a499-b139faf70fe1)

**Comment by jhouse-solvd** [comment]
@adamwhitlock1 and team are currently validating. 

We can re-open this issue (or create a new one) if add'l work or customization is needed. 

Closing.
