### ISSUE TITLE
CST: Use promise methods for API calls

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28893]
## Description

The Claim Status Tool is using an older method (callbacks) to perform API requests. The request still works, but logs a console warning ([related Sentry event](http://sentry.vfs.va.gov/organizations/vsp/issues/1343/?environment=production&project=4&query=url%3A%22https%3A%2F%2Fwww.va.gov%2Ftrack-claims%2Fyour-claims%22&statsPeriod=14d)).

- `the "success" callback has been deprecated, please use a promise chain instead`
- `the "error" callback has been deprecated, please use a promise chain instead`

## Tasks

- [ ] Switch API callbacks to promise methods
- [ ] Verify tests still pass

## Definition of done

- [ ] All tasks complete
