### ISSUE TITLE
Dueling Modals (Dep Ver vs SSO)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28897]
## Description
During usability testing we encountered a phenomenon where the modal for dependency verification would render at the same time as the modal for SSO, stacked behind it. The user wouldn't then be able to close the SSO modal, as interacting with it caused the dependency modal to close instead. 

## Considerations
- Could potentially be a z-index issue

## Steps to Reproduce
1. Log into staging, directly to the view dependents URL with a fresh user in incognito mode.
2. Notice that the SSO modal procs, then a few moments later, the dependency verification modal procs.

## Tasks
- Investigate what is causing the stacking, determine a solution

## Acceptance Criteria
- [x] Solution has been found, if it exists
- [x] Ticket for implementation created
- [x] or a solution has been implemented and a PR has been requested for merging (just in case)

**Comment by jason-gcio** [comment]
Is Modal stacking rare?
How often is SSO popping up?
Research dueling modals
