### ISSUE TITLE
HLR: Fix breadcrumb

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28896]
## Description

The Higher-Level Review breadcrumb includes "with VA Form 20‑0996", which should only be included on the introduction page not all subsequent pages.
 
![Screen Shot 2021-08-17 at 3 45 36 PM](https://user-images.githubusercontent.com/136959/129799802-5bc4381f-ff88-45a0-a56d-6347fbacbe72.png)

## Tasks

- [ ] Only include "with VA Form 20‑0996" on introduction page
- [ ] Add unit tests

## Definition of done

- [ ] All tasks done
- [ ] All tests pass
