### ISSUE TITLE
[Tiger Team] Develop artifacts that articulate the platform developer persona and development workflow

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28907]
## Description
Now that we've done some user story mapping sessions with FE/BE Tools developers, let's solidify that information into usable artifacts that articulate their persona and workflow. 

## Background/context 
[Mural board used during user story mapping sessions](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1628015418343/49a1b8efab1c140d58b501c003f57b4d6816bce3?sender=u571992d9c638e14bd70a1743)
(For more information, see parent epics) 

---
## Tasks
- [x] Platform developer persona artifact
  - [x] DevOps Engineer
  - [x] Backend Engineer 
  - [x] Frontend Engineer 
- [x] Development workflow artifact 
- [x] Upload artifacts where they can be shared

## Acceptance Criteria 
- [x] Persona and workflow artifacts are shared with Tiger Team

**Comment by jhouse-solvd** [comment]
See [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/1861648542/Developer+Personas) for persona artifacts. 

See [HERE](https://vfs.atlassian.net/l/c/S1vj0mLY) for Development workflow artifact

**Comment by jhouse-solvd** [comment]
This is done. Closing.
