### ISSUE TITLE
Details Page Section "How do I dispute my copay charges?"

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28908]
## Issue Description
Need to implement "How do I dispute my copay charges?" section content on the details page

![MCP Desktop - UXPin Preview 2021-08-18 12-47-52.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/63126002-e0ab-4a02-a060-85952df8bdb5)
---
## Tasks
- [ ] Create component to render section content

## Acceptance Criteria
- [ ]  Section "How do I dispute my copay charges?" should render on the details page
- [ ] Design should match [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140772652/simulate/sitemap?mode=i)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
