### ISSUE TITLE
[BE] Direct Deposit: Reactivate Direct Deposit in limited capacity

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28903]
## Background
As a result of reported incidents of fraud and investigating the route cause (traced back to access via DS or MHV), we can reactive Direct Deposit in a limited capacity.

## Tasks
- [ ] Allow full read / write for ID.me LOA3 / IAL2 accounts
- [ ] Allow redacted read (only limited account number) for all other LOA3 accounts, regardless of MFA status.
- [ ] Users with redacted read (only limited account number) should be presented with a message that indicates they can update their information with an identity proofed ID.me account or via phone?

**Comment by lihanli** [comment]
@KevinMHoffmanUSDS @codyreinold-usds is prefill also restricted to only loa3 id.me users?

**Comment by ajakabcin** [comment]
@lihanli from Kevin - yes prefill should be restricted but this will be discussed further in Monday 8/23's meeting. Thanks!
