### ISSUE TITLE
[Centralized Logging Documentation] Iterate on the Loki User Guide based on feedback from recent research readout

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28900]
## Description
With research collected from developers and feedback provided by stakeholders during a recent readout, we are ready to iterate on the Loki user guide. We aim to provide this updated user guide and publish it on the platform website before we make the solution live in production. 

## Background/context 
- [Link to the user guide](https://vfs.atlassian.net/wiki/spaces/OT/pages/619119010/Centralized+Logging+with+Loki+-+User+Guide) in the Ops Team confluence space - the "Loki Details for Platform Developers" needs to be broken out into its own doc 
- [Link to the user guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/78d939044b2636767d5be0a20521ce5c92fccee9/platform/logging/centralized-logging-user-guide.md) in GitHub va.gov-team repo
_Note: both of the above need to be deprecated in favor of a platform website version that can be shared publicly_ 
- [Link to Research Synthesis](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1409155105/Ops+Centralized+Logging+Research) performed by the Service Design team
- [Link to Research Readout](https://docs.google.com/presentation/d/1RRblJ1jXZZCLH6ywfhc8XKSyVNT_tp5mZQOYe6bk4Bs/edit#slide=id.ge74234cd4b_0_240) slide deck that summarizes key insights from the Service Design team's research
- [Link to the chat transcript](https://docs.google.com/document/d/1lKCMlOgP5zZarFl11z47-DvOjmkusKInzFH_wJZbIoQ/edit) from the readout meeting w/ stakeholders -- there are one or two great points in here!

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Break out the platform developer section into its own document - done; see [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/1891270657/Set+up+and+configure+Loki+as+a+platform+developer)
- [x] Update user guide based on key recommendations captured in the first comment on this issue
- [x] Publish the updated user guide on the on platform website (may need to ask Gretchen / Content & IA team for guidance on placement) 
- [x] Deprecate any older/previous versions and include links to the new platform website version created in the previous task
- [x] Share the platform website version of the user guide w/ developers prior to launch in production 

## Acceptance Criteria 
- [x] The updated user guide will be published and made available to developers

**Comment by jhouse-solvd** [comment]
_Taken directly from the research readout slide deck, these are the key recommendations for iterating on the doc that would help us hit a homerun:_ 

**The following updates to the user guide are recommended prior to launching Loki in production:**

- [ ] Provide an explanation or visual aid to help users know where to find their app logs.
- [ ] Remove the architectural diagram or move it further down the page - it didn’t help users understand what Loki is or what it does, so it wasn’t very helpful as an intro.
- [ ] Revamp the “What is Loki?” overview content to make it relevant for VFS developers by providing basic info about Loki (i.e., what are Loki logs? who is it for? what it can/can’t do)
- [ ] Note that comparing Loki to Prometheus was confusing for users who currently use Grafana for metrics/dashboards (those users expected to create dashboards from Loki data and/or to find Loki in the Dashboard section of Grafana).
- [ ] Provide a few specific examples to help VFS engineers get started with queries for vets-website or vets-api log data. 
- [ ] Provide a table of contents so users know what is covered in the guide and to help them jump to frequently used sections (this will be addressed automatically when the user guide is published in Confluence).

**When communicating with VFS customers about the launch of Centralized Logging with Loki:**
- [ ] Reiterate that Loki is replacing AWS Cloudwatch - the participants did not seem to know that Loki logs in Grafana will replace Cloudwatch and that logs will no longer be available in CloudWatch
- [ ]

**Comment by jhouse-solvd** [comment]
Okay, I've taken a solid pass and iterated on the guide up to the "Query and analyze Loki log data in Grafana". 

@dginther - it would be great if you could take on that next section and make use vets-api as an example (rather than nginx) as that will be more relevant to VFS developers. 

beyond that, we'll just need a Table of Contents which I believe will be handled addressed when we publish the doc to the platform website. Gretchen or Liani would be great resources for this part as there is a process for getting it published and making sure it's linked up in the right section(s). 

it would be wonderful to include a link to the the published user guide in the upcoming team of teams meeting on 9/21, but can be shared on 9/28 as a last resort.

**Comment by lianilychee** [comment]
hi hi!  Would someone on the Ops team kindly fill in this [content support request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=gmaciolek&labels=content-ia-team%2C+documentation-support&template=documentation-support-request.md)?  That way the context can be summarized and the request automatically added to our backlog :blob-thumbs-up:

**Comment by jhouse-solvd** [comment]
Updated and published on the platform website: https://depo-platform-documentation.scrollhelp.site/developer-docs/Centralized-Logging-with-Loki---User-Guide.619119010.html

Closing.
