### ISSUE TITLE
Update Domo How to training

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28919]
## Issue Description
We currently have a Domo "How to guide" on the Platform Website. VFS teams have requested in person training. How might we implement an easier how to for the Domo dashboards?

Based on our office hours, VFS teams are asking us to guide them through our content in both the How to guide and our data dictionaries (how do they use the dashboards and how do they read the data in the dashboards?)

[Video guide link](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/SDT/pages/1802993669/Outline%2BPlatform%2Btraining%2Bframework%2Bdraft&sa=D&source=editors&ust=1629307823303000&usg=AOvVaw2Hbo5gyccDpFvJLe_vPso3)

---
## Tasks
- [x] Talk through with Jonathan or Rebecca
- [x] Determine if a video, a syllabus w/visuals for an in person training, or both are the best paths forward
- [x] Deliver a video, syllabus w/visuals, or both (or none)
- [x] If any, link artifact to the Platform Website

## Acceptance Criteria
- [x] VFS teams can get trained on their Domo dashboards through different paths than reading the Platform Website documentation.

## Definition of Done
- [x] A training artifact (video, syllabus, etc.) is created. OR it's deemed unnecessary.

**Comment by chloedotbrown** [comment]
## Recommended training artifacts

- **Series of short training videos** (1-4 min) for particular parts of documentation that are frequently asked about in Slack and/or office hours. These would be embedded in the How-to documentation and may replace GIFs, since it would be redundant to have both (confirm embed strategy with Content & IA team). Shorter videos are more manageable for users to watch and easier to create/maintain.
- **Demo video for each standardized dashboard**, recorded either next time someone requests a general walk-thru during office hours or made separately without a live audience.

## Next steps

- [ ] Attend Content & IA office hours on Thursday 8/26 to discuss embed plan for videos once recorded, any advice from their perspective on video content.
- [ ] Record and edit series of short How-To videos.
- [ ] Record and edit dashboard demos.
- [ ] Communicate to Service Design team any gaps or revisions needed in their video guidance doc, so they can learn through this process as well.

**Comment by jennaouellet** [comment]
@bsmartin-ep I confirmed the tag is working as expected. The Start, Complete, Pause, and Progress captures are all occurring and the variables are being tracked. The simplified event structure makes sense to me as well.  

![image](https://user-images.githubusercontent.com/85642160/131204172-51ad9b8f-d988-44dc-9b21-85e823d8b036.png)

![image](https://user-images.githubusercontent.com/85642160/131204167-044f8adc-c9ac-427c-9fd1-72ff201848c4.png)

![image](https://user-images.githubusercontent.com/85642160/131204183-c1773998-def3-4295-9138-ed4945dc8564.png)

![image](https://user-images.githubusercontent.com/85642160/131204190-b9df0542-a540-4ef1-890d-722075ae18b0.png)

**Comment by bsmartin-ep** [comment]
Thanks @jennaouellet!

@chloedotbrown - GTM and GA changes have been published.  All fields are tucked into custom dimensions, so I would suggest a custom report like:

https://analytics.google.com/analytics/web/template?uid=hxNYgnZRSCq6DNjUEB1JMg

**Comment by chloedotbrown** [comment]
Awesome, thanks @jennaouellet and @bsmartin-ep ! What's the best way for us to add these custom dimensions to our [BQ - AooA Session Metrics](https://va-gov.domo.com/datasources/1058df91-451f-44e6-bf0d-f0eededf7235/details/overview) datasource on Domo?

In the meantime, how-to videos have been been recorded, captioned and embedded on the [Platform documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html).

**Comment by bsmartin-ep** [comment]
Sure thing @chloedotbrown.  The four video CDs have been added to the dataset...

![Screenshot from 2021-09-14 13-32-38](https://user-images.githubusercontent.com/62304138/133306125-1cfef71e-9292-44d1-9cf2-eb5a32ce0a98.png)

**Comment by chloedotbrown** [comment]
Huge thanks - I'll add to the AooA dash! Closing ticket.
