### ISSUE TITLE
VAOS dashboard - Non Standardized

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28916]
## Issue Description
Analytics is creating an edge case dashboard for VAOS. This dashboard doesn't fit into Content, Forms, or Search because of the complexity of the VAOS tool. 

---
## Tasks
- [x] Discovery
  - [x] Test funnel segments hypothesis
  - [ ] Technical discovery: How can we set this up on the data side
- [x] Build out mock up
  - [x] Document what card differences there may be between Forms and the new dashboard
  - [ ] Share with VAOS
- [ ] Create the DOMO datasources from BigQuery
- [ ] Build Cards
- [ ] Configure dashboard with those cards
- [ ] QA
- [ ] Share with VAOS again

## Acceptance Criteria
- [ ] VAOS can see data relevant to their product on Domo. Analytics can easily maintain this dashboard.

**Comment by chloedotbrown** [comment]
Know the BigQuery side of this work is still in development, but here's a[ mockup](https://docs.google.com/presentation/d/1yxPBhNIeDZ379bbYngHTw2OoxBsMMQ9AwcprIXeMPtM/edit?usp=sharing) of the VAOS edge case dashboard based on the Forms KPIs. I've used comments and very obvious boxes to call out questions about data or content (though mostly its data). I've also added FYIs on any meaningful design changes or places where ETLs will need to be replicated. Hoping this helps clarify next steps and/or raise potential other issues early!

Given that VAOS was _so_ similar to the logic of Forms (save for its funnel-challenges), it made more sense to use that as a model than looking for things in common with the GI Bill Comparison Tool or other edge cases. However, I do still think there might be an opportunity to develop a "Tools" KPI dashboard that could cover a couple of these non-standard products – they look like they could have more similarities.

**Comment by joanneesteban** [comment]
General VAOS notes from meeting with Lauren E on 9/21:

- Needs to look at the direct schedule flow.
- Needs different funnels for the different stakeholders.
- Community Care should always be separate
- Facility Selection, Clinic Selection, and the Calendar should always be represented
- Lauren E to send over steps on the user flow

Our next steps are...going back to the funnel drawing board!

**Comment by chloedotbrown** [comment]
Shared WIP version of [strategy writeup](https://vfs.atlassian.net/wiki/spaces/AT/pages/1940553992/WIP+-+VAOS+Possible+approaches+to+edge+case+dashboard) and [v2 of mockup ](https://docs.google.com/presentation/d/1fHh1fx10MKcNe4W5TAQpZ5x72i3AQ8FiAXZy2CtKNKg/edit?usp=sharing)with the rest of the Analytics team for feedback.

Once edits have been integrated, we'll need to discuss potential timeline for implementation, whether we need to wait for new Engineer, and decide when to share revised plan with Lauren for review.
