### ISSUE TITLE
[MCP] Use case: Veteran has medical copays referred to the Department of Treasury for collection

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#28914]
## Issue Description
This ticket is part of the epic where we will be creating mocks for each of our use cases for testing and engineering purposes.

**Use case:** Veteran has medical copays referred to the Department of Treasury for collection

---
## Tasks
- [ ] Create a design that reflects the use case above
- [ ] Upload to UXPin
- [ ] [Update GH design readme file](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/Debt%20Resolution/Medical_Copays/design/README.md)

## Acceptance Criteria
- [ ] Designs uploaded to UXPin
- [ ] GH design readme updated and linked in ticket

**Comment by rebeccawalsh** [comment]
Note: this work is planned but we're unsure if we'll be able to get this data. More investigation is needed.
