### ISSUE TITLE
HLR v2: Fix informal conference time selection

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28910]
## Description

I originally interpreted that Higher-Level Review v2 would allow more than one time slot choice. But discovered that only one informal conference time choice is allowed. The page, and submitted data needs to be updated to reflect this requirement.

## Tasks

- [ ] Update HLR informal conference times UI
- [ ] Update time schema
- [ ] Update submitted data
- [ ] Update tests

## Definition of done

- [ ] All tasks completed
- [ ] All test passing
