### ISSUE TITLE
[MCP] Use case: Veteran has a resolved/paid medical copay balance from one facility

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#28915]
## Issue Description
This ticket is part of the epic where we will be creating mocks for each of our use cases for testing and engineering purposes.

**Use case:** Veteran has a resolved/paid medical copay balance from one facility

---
## Tasks
- [x] Create a design that reflects the use case above
- [x] Upload to UXPin
- [ ] [Update GH design readme file](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/Debt%20Resolution/Medical_Copays/design/README.md)

## Acceptance Criteria
- [x] Designs uploaded to UXPin
- [x] GH design readme updated and linked in ticket

**Comment by rebeccawalsh** [comment]
Note: we're unsure if this data will be available to us.
