### ISSUE TITLE
[Discovery] Design Refactoring for Outreach & Events Hub

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28920]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)

## High Level User Story/ies
As a VA digital comms lead and user of the VA.gov CMS, I need new capabilities and features as a publisher in the Outreach & Events hub, so I can provide information more effectively to my Veteran and caretaker audience.

## Discovery
Review current UX and how might we make the Outreach Hub events calendar more personalized for users (e.g. find events by date, time, event type, etc.). This discovery ticket will be to capture design ideas as outlined in the "Product Outline" and to discuss UX on how to personalize the Outreach Hub experience.

## Tasks
- [x] Review current UX: [Link](https://www.va.gov/outreach-and-events/events/)
- [x] Make design recommendations on how to improve on UX 
- [x] Provide a sketch design or wireframe in order to PO/PM to visualize recommendations

**Comment by callen2563** [comment]
**Update on discovery / design research:**

Gov.uk - looks like some of their events are hosted by [eventbrite.com](https://www.eventbrite.co.uk/e/mhra-board-meeting-held-in-public-tickets-165779558121) Do we want to use a similar online tool?

[Link to appointment scheduler](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/p/50DC3685-35CE-4EE4-924C-73B1E444D4C5) mock ups by Peter Russo which we could leverage

Links Josh from accessibility provided: 
[Your CMS is an accessibility assistant](https://www.youtube.com/watch?v=zlinL3SCjic&t=30s)
[ATAG at a Glance](https://www.w3.org/WAI/standards-guidelines/atag/glance/)



I have gathered screen shots from Gov.UK, Meetup.com, Eventbrite.com, FB, Google and a few others and will be putting together some mock ups based on that design research for review.

**Comment by callen2563** [comment]
Initial home screen mock that incorporates a search bar, filter by date and time, type etc, includes optional image and reoccurring dates and times:

![OBH-mobile](https://user-images.githubusercontent.com/68560244/133518975-4d872e1d-61b1-45f5-bee3-673e40dae384.png)

**Comment by callen2563** [comment]
@brianalloyd as discussed yesterday I mocked up a version that shows only the filter component added to the Outreach events page for MVP:
![Outreach events - Desktop](https://user-images.githubusercontent.com/68560244/133821761-f273a929-3bd9-4bd9-8590-4a1840bc3c81.png)
![Outreach events - mobile](https://user-images.githubusercontent.com/68560244/133821824-9ad5fdbf-8614-479c-88f4-f42610794295.png)

**Comment by brianalloyd** [comment]
This is great @callen2563 love the visuals and will definitely help FE move to the next step.

**Comment by brianalloyd** [comment]
Closing this out based on discovery actions complete.  Looking forward to reviewing this in Sprint planning and moving this initiative forward.

**Comment by callen2563** [comment]
Adding notes quit from chat with Dave but will meeting on this again: 

- Add Filter with something like calendar picker instead of sort
- Add repeating events
- Remove search bar
