### ISSUE TITLE
Update the GTM implementation/QA request guide

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28938]
## Issue Description
There's often a back and forth between the Analytics team and VFS teams on requirements gathering for GTM requests. VFS PMs and POs need to know what's out of the box vs. custom defined.

---
## Tasks
- [ ] Audit current GTM request template
- [ ] Explore additional ways of VFS teams requesting GTM (like linking a Sheet/Excel to the Github template)
- [ ] Add question about application structure/architecture (Brian to edit this...) in the GTM request template
- [ ] Add check boxes for design system component usage in the GTM request template
- [ ] Add link to the Platform Website Getting Started page
- [ ] QA the issue template content
- [ ] Link [Data Dictionary](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28299) to Platform Website Getting Started page (@joanneesteban )

## Acceptance Criteria
- [ ] When a VFS team requests analytics tagging, Analytics doesn't need to request additional information and VFS teams can read documentation to understand what tags come out of the box vs. what they need to define.

## Definition of Done
- [ ] The GTM implementation/QA request template is updated. Platform Website getting started doc is updated.

**Comment by laurensimpson14** [comment]
@jennaouellet would this be the [Google Analytics Implementation or QA Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) template?

**Comment by jennaouellet** [comment]
@laurensimpson14 yes that's the template. From the few tickets I've worked on, I noticed that many of the fields are left blank by the requestor. I wonder if there's a way to clean up the template somehow while also ensuring all of the details we need make it in.

**Comment by laurensimpson14** [comment]
@jennaouellet I edited the template to slim it down & make it user friendly. Here's the first pass: https://github.com/department-of-veterans-affairs/va.gov-team/blob/28938---edit-GA-request-template/.github/ISSUE_TEMPLATE/analytics-implementation-and-qa-request-template.md

**Comment by jennaouellet** [comment]
@laurensimpson14 I think it looks great! I have no adjustments/ further suggestions but I did notice the link ' All items of checklist have been executed'  under Acceptance Crtieria 404s

**Comment by laurensimpson14** [comment]
Good catch! That link is left over from the initial ticket... I think I'll delete the whole bullet point. 

In the task list for this ticket Joanne suggested "Explore additional ways of VFS teams requesting GTM (like linking a Sheet/Excel to the Github template)". Do you think that's a good idea @jennaouellet? Or do you think this ticket template is clear enough? I'm worried that an additional sheet/attachment could get confusing for folks filling out this ticket.

**Comment by jennaouellet** [comment]
@laurensimpson14 I think the template is clear enough, I agree that adding another step in the ticket submission process would confuse people

**Comment by joanneesteban** [comment]
Thanks for working on this! It looks so much more succinct and easy to read! 💯 

### Some notes:
- I noticed these changes haven't been pushed to the [actual issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D). Was this on purpose?
- Asking for individual names: ask folks to use the `/support` tracker on the #vfs-platform-support channel so that we're not asking folks to put PII on the public Github
- We should probably change the assignees. We'd removed everyone except for myself so that it would be clearer who would work on a ticket when it came in, and I could get notified that we received a new ticket. 
- For `What interactions need to be tracked?` - try to point folks to not _just_ the Design System components documentation. You can also point to the larger [GA data dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html) so that they're not working from scratch.

**Comment by joanneesteban** [comment]
@laurensimpson14 this looks great! Very succinct. Assigning it to yourself works - y'all can update it in the future too; just make sure that someone is paying attention to the new tickets (even if that means no assignment, but seeing if new tickets are added to the board). The template updated on my end. Feel free to close it out.
