### ISSUE TITLE
Publish updated GTM implementation/QA guide

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28936]
## Issue Description
Once a VFS team begins implementing and QAing the dataLayer on their product, they should understand how to do GTM work on their own with minimal back and forth with the Platform Analtyics team.

This deals with the [Build user stories in the Analytics Experience map](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1623339995796/0beb77efcb6353dc3af5dbcf8212eea8ae0f6de4?sender=joanne5658).

[Current Github doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md)

---
## Tasks
- [x] Add content on where to go to see non-prod events and how VFS FE devs can QA the tags on their own
- [x] Audit Github for current GTM docs
- [x] Migrate relevant Github GTM docs
- [x] Update current GTM docs
- [x] QA content
- [x] QA with VFS FE devs (reach out to James for help with feedback)
- [x] Publish to Platform Website

## Acceptance Criteria
- [ ] VFS Frond End developers can read documentation on the Platform Website and understand how to implement and QA for GTM on Staging and Production, minimizing the back and forth between the Platform Analytics team and VFS teams.

## Definition of Done
- [ ] A Platform Website document with steps for Devs is completed and published.

**Comment by jennaouellet** [comment]
The GTM content from the current github documentation is already live in Confluence within the data dictionary. The QA section is in the WIP-Google Tag Manager Implementation & QA doc that has already been audited. Before publishing that one, we will need to add the information on non-prod events.

**Comment by laurensimpson14** [comment]
@jennaouellet I added in a little more info on how to see events in the staging environment. 

As far as events that are specifically non-prod, there aren't many. There is a variable called `Staging Only - Base Configuration`, and it's tied to 3 events that aren't in use: 
1. `Debug Event`: This is set to fire on the custom event `^debug.*`, however in GA it hasn't fired since last November (and even then it only fired twice)
2. `TEST STAGING ONLY - Profile Form Submit`: The trigger for this is paused, and I don't see any data from this event in GA for the past 5+ years
3. `TEST STAGING ONLY - Profile Saved - API Calls`: The trigger for this is also paused, and I don't see any data from this event in GA for the past 5+ years

I'll put in a tech debt ticket to remove these events 🔼

I've QA'd the rest of the doc and it looks great to me! @jennaouellet and @bsmartin-ep do you think it's ready for us to reach out to James for QA with VFS FE devs?

**Comment by joanneesteban** [comment]
Next steps: @jennaouellet @laurensimpson14 to link doc & reach out to James to support with VFS QA.

**Comment by laurensimpson14** [comment]
Update: This is out on scrollhelp now
