### ISSUE TITLE
Build mockup for VA.gov-wide "Numbers" dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28941]
## Issue Description
Build a mockup for the VA.gov-wide "Numbers" dashboard so that we can understand what a final dashboard might look like and get feedback from Chris.

Please feel free to use whichever tool to draw up a mockup. (like pen & paper)

---
## Tasks
- [x] Review selected metrics from technical discovery
- [x] Decide which chart designs work well for the metrics
- [x] Determine how to lay out metrics with the KPI framework, if possible
- [x] Create mockup

## Acceptance Criteria
- [x] We _can_ share our potential design with our main stakeholder to get feedback before spending time building a solution.

## Definition of Done
- [x] A static mock up is created

**Comment by joanneesteban** [comment]
Continuation of #28364

**Comment by chloedotbrown** [comment]
Hi @joanneesteban  – first round mockup of OCTODE Numbers report is [here](https://docs.google.com/presentation/d/1DaE_NdhC2Z6v0LHKcLQ2LShNH9ZF0kuW52AKIIfHJvE/edit?usp=sharing)! Was able to organize by our KPI framework categories and still have a pretty even distribution of the metrics you'd selected. As I mentioned on the discovery ticket, I've left anything that might be blocked and therefore omitted from the first iteration of this, but they should be able to fit in when/if they become available.

I'd love to get some feedback on this from you/the team and then do another iteration when I'm back, if there's time. But if we want to move this along while I'm out next week, feel free to share with VA stakeholders too!

**Comment by joanneesteban** [comment]
### General feedback
from 9/16 discussion

- Look into a highlights section
- Adding additional annotations to historical context, & include the original VA Numbers
- Feel free to reach out to the appropriate team owners of the data Analytics doesn't have in BQ yet

**Comment by chloedotbrown** [comment]
Closing this ticket, as work will continue (and be updated) on ticket #30700.
