### ISSUE TITLE
Configure React Routes by ID

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28948]
## Issue Description
Client routes are currently configured to a static copay detail page and should to be updated to render dynamic routes based on the copay debt id

![Medical Copays  Veterans Affairs 2021-08-19 09-05-47(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/a95c6db7-0384-4a3f-ae8e-0df32c4f7c41)
---
## Tasks
- [ ] Configure react router to accept copay debt ids

## Acceptance Criteria
- [ ] Users should be routed to the proper debt details page using the debt id
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
