### ISSUE TITLE
Announcements effort

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#28955]
# User story

As a Platform customer, I need to understand how to make easily findable announcements via the Platform website, so that customers know the changes my team has made.

# Tasks

- [ ] Socialize to teams that announcements guidance is coming
- [ ] Outline guidance (Gretchen)
- [ ] Write guidance (Amy)
- [ ] Socialize guidance to teams (Amy)
- [ ] Socialize to teams that have already published that they will need to modify prev announcements (joint)

# Acceptance criteria

- To come.

# Reference info

- To come.

**Comment by lianilychee** [comment]
8/19 Thurs:
- G will spend a little time today thinking, but first on deck is going to be IA effort

**Comment by lianilychee** [comment]
8/20 Fri:
- Gretchen did some comparative analysis, but decided Product Support's approach is good
- made a rough draft of the guidance to get the ball rolling

**Comment by lianilychee** [comment]
8/31 tues:
- gretchen will triage the list of tasks for today:
  - update the [example changelog](https://sandbox-platform-website.scrollhelp.site/test-space/August-2021.1846607919.html) I made (based of august changes from eng teams)

**Comment by lianilychee** [comment]
9/1 Weds:
- G: 
  - I made a little progress :D The example page is done (has yet to be shared out)
  - Currently trying to think of how to document the "how, why, and when" in a succinct way, since Announcements are another page type <-- not too far away on this!  Still shooting for finishing by end of week
  - Today, would like to have a draft on "how to use this page type"
