### ISSUE TITLE
Update Facility Locator COVID-19 intro text

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28951]
## Issue Description
Intro text above the search box on the Facility Locator pushes down the search fields, particularly on mobile. 
Based on analytics, we can also consolidate into a single link for COVID-19 info. 

---
## Tasks
- [ ] Edit current intro text to 

> Coronavirus update: Please call first to confirm services or ask about getting help by phone or video. We follow CDC guidelines for wearing masks at our facilities.
- [ ] Link "guidelines for wearing masks at our facilities" to https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#more-coronavirus-specific-conc

## Acceptance Criteria
- [ ] Facility Locator intro text "Find a VA location or in-network community care provider. For same-day care for minor illnesses or injuries, select Urgent care for facility type." is maintained, followed by new COVID-19 text specified above
- [ ] "guidelines for wearing masks at our facilities" links to https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#more-coronavirus-specific-conc
