### ISSUE TITLE
IA effort

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#28956]
# User story

As a Platform team member, I need to know how the new IA is structured, so that I can write/place the correct info in the correct place.

# Tasks

- [x] Determine when the IA will be simplified (all)
- Concurrently:
  - [x] Simplify IA (Gretchen)
    - Map old spaces to new ones.
    - Clean up any cruft.
- [x] Train Eng teams on Weds
- [x] Socialize to all teams that IA change is coming, Weds afternoon (Amy)
- [x] Socialize to teams that IA change has occurred (Amy)
- [ ] TBD - Modify guidance
  - to update screenshots, links, text (Amy)

# Acceptance criteria

- New "Organization" guidance has been socialized to Platform team authors.
- Platform team is aware of office hours.

# Reference info

- [Organization](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) guidance

**Comment by lianilychee** [comment]
8/19 Thurs:
- Will get the newsletter reviewed and out first, then will figure how much time each step takes

**Comment by lianilychee** [comment]
8/20 Fri:
- Amy and Gretchen will be syncing today
- Thoughts on how organization will be updated:
- Also, maybe sync w/ eng PMs to review the IA change guidance and announcement guidance
  -

**Comment by lianilychee** [comment]
8/23 Mon:
- Timeline
  - Tues - heads up announcement being drafted (Amy)
  - Weds night - make the IA change
  - Thurs - announce that the change has been made
  - EOS - guidance will be updated
- ^^ this timeline all depends on the new time that Liani will hunt out

**Comment by lianilychee** [comment]
8/24 Tues:
- Gretchen has been prepping for Weds w/ the Eng PMs by assembling a [prototype of the dev docs space in the sandbox](https://sandbox-platform-website.scrollhelp.site/test-space/)

**Comment by lianilychee** [comment]
Weds 8/25:
- Amy has the announcement and incorporated the comment G made
- Gretchen is prepping to present to the PMs
- other notes
  - Will be shelving change to dev docs naming and hierarchy, need more discovery work w eng teams first
  - maybe need to sync w FE T

**Comment by lianilychee** [comment]
tues 8/31:
- amy - to decide if the guidance descriptions will be modified or deleted
