### ISSUE TITLE
[FSR] Verify Income Values

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#28963]
## Issue Description
During UAT with the veteran it was noticed that a few of the values generated on the FSR PDF under SECTION II - INCOME are not being calculated correctly and need to be updated
- Field 24A net monthly income less expenses value is being calculated wrong
- Field 14D payroll deductions - "OTHER" should be field 14A federal, state and local income taxes
---
## Tasks
- [ ] Update SECTION II - INCOME values

## Acceptance Criteria
- [ ] SECTION II - INCOME should be calculated correctly
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
