### ISSUE TITLE
Add new American Indian question on the 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28973]
# Date ES can begin accepting new question: August 2022

## EPIC
[Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/American%20Indian%20question)

## High Level User Story/ies
As an American Indian or Alaska Native, I want to be able to specify that during enrollment on the 10-10EZ, in order to receive appropriate VA Health Care.

## Hypothesis or Bet
This is a new question being added on both the paper form and online.

## OKR
n/a

### What must be true in order for you to consider this epic complete? 
* **[Design for new question](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/jgWK7GD)**
* Question added to 10-10EZ
* ES accepts 10-10ez submissions with new American Indian question answered

Tickets to be created/groomed:
- [x] Feature turned on in Staging, Prod 
- [x] Collab Cycle request (PM)
- [x] Analytics (Collab Cycle + our team) 
  - [x] Update tags (Engs)
  - [x] Validate data flow (PM)
- [x] QA (Collab Cycle + our team)
  - [x] Generate use cases (Engs)
  - [x] Write test cases (QA)
- [x] Privacy and Security review ticket needed
- [x] Go/No-Go
  - [x] Logging
  - [x] Release plan complete
