### ISSUE TITLE
[SPIKE] Investigate and a speed test packages

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#28971]
## Description

We need to track the network speeds at our facilities. Investigate a solution

## Questions to Answer

- [ ] Is there a react plugging we can use? 
- [ ] Can we code something that does it?

## Tasks

- [ ] find and get a react package approved/used
- [ ] try a home made solution
- [ ] Create a prototype
- [ ] Update relevant documentations

## Acceptance Criteria

- [ ] Relativant documentation has been created
- [ ] Findings shared with the appropriate team members

**Comment by mdewey** [comment]
After digging some more here are the high-level details

I can track either a small file or the API successfully. 
Finding the actual network speed (like 100 Mbps)  is not possible with small files unless we really work hard to make multiple calls and download multiple files. 
I have an outstanding support request with the analytics of the best way to store/report this number once found. 

I am going to the parking lot until I find out where to report the ms/call (milliseconds per API call) so we can track it. 


slack link: https://dsva.slack.com/archives/CBU0KDSB1/p1629402733207100
