### ISSUE TITLE
Chapter 31 - Add VBMS as a downtime dependency

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#28976]
## Description
VR&E recently noticed that on rare occasions PDFs weren't being saved in VBMS ( < 2% ). This may be the result of VBMS downtime or service interruption. In order to notify users that their submission may fail due to downtime, we need to add VBMS as a downtime dependency for chapter 31.

## Considerations
- [VBMS entry in devops repo](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L535)
- [external services in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/6dce478e481ad53327f7e53ac68df8f19c75eff1/src/platform/monitoring/DowntimeNotification/config/externalServices.js#L6)
- [chp 31 downtime dependencies](https://github.com/department-of-veterans-affairs/vets-website/blob/bfe256a40e7e1252c8147607067e0fa9973c4452/src/applications/vre/28-1900/config/form.js#L36)

## Tasks
- [x] add VBMS to [chapter 31 downtime dependencies](https://github.com/department-of-veterans-affairs/vets-website/blob/bfe256a40e7e1252c8147607067e0fa9973c4452/src/applications/vre/28-1900/config/form.js#L36)

## Acceptance Criteria
- [x] above task has been completed
- [x] PR has been submitted
