### ISSUE TITLE
[FE] Remove floating feedback button 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#28972]
## Decription
We got a request to "disable floating feedback button (foresee / medallia) on all check-in pages"? 

## Tasks
 - [ ] Disable/remove feedback button

## Acceptance Criteria

- [ ] The button is no longer visible on pages
- [ ] The changes are in staging
- [ ] The changes are in production
- [ ] The appropriate teams have signed off.

**Comment by mdewey** [comment]
I was able to track down the team that owns the button and I am currently working with them to remove it from our pages.

Slack thread for context: https://dsva.slack.com/archives/C015PF52YFL/p1629397616003900
