### ISSUE TITLE
[PM, Design, FE] Direct Deposit: Determine long-term solution for restoring DD access 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28983]
## Background
Following the reported incidents of fraud with Direct Deposit users, functionality was restored in a limited capacity (see tickets linked below). We need to come up with an approach for restoring access long-term.

## Tasks
- [ ] Determine long term technical approach
- [ ] Determine what designs (if any) are needed
- [ ] Create new implementation tickets
