### ISSUE TITLE
Vets-Api logs no longer showing up in Grafana/Loki

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va.gov-team#29009]
## Description
We noticed some logs from a vets-api service of ours are no longer showing up in Grafana

## Background/context 
The service in question is `lib/vetext/service.rb`

## Technical notes
Steps to recreate:

1.  get a mobile access token through the va mobile app or https://va-mobile-cutter.herokuapp.com/ with user vets.gov.user+166@gmail.com
2. Hit the mobile push get preferences endpoint via this curl `curl --location --request GET 'https://staging-api.va.gov/mobile/v0/push/prefs/83F328B995B1F7E27F16281758736105' \
--header 'X-Key-Inflection: camel' \
--header 'Authorization: Bearer {token generated above}' \
--header 'Cookie: TS016f4012=0119a2687f54f670038230e67d0f5d9bba86c3c61495b43f9023e6f31b838bf90a8bbcb5f976a65ca8462ad6fb9c28d5c8fe5510f5' \
--data-raw ''`
3. Head to grafana and use this query, `{app="vets-api-server", filename=~".+json.log"} | regexp "(?P<time>\\d\\d:\\d\\d:\\d\\d) (?P<process_name>\\w+.\\d) \\s+ (\\|) (?P<json>.+)" | line_format "{{.json}}" | json
| payload_path=~"/mobile/v0/.*" 
|= "VEText"` in the staging env

It's expected that there should be a log corresponding with this statement from vets-api: `Rails.logger.info('VEText Push service get prefs method enter', endpoint_sid: endpoint_sid)` line 30 of the service referenced above. 

Additionally, I fired a sequence of requests to this endpoint:
Aug 18th 5:02 - 5:11 EST
One Get Prefs call per ~1min
10 requests to https://staging-api.va.gov/mobile/v0/push/prefs/83F328B995B1F7E27F16281758736105
No messages in Grafana

---
## Tasks
- [ ] Help us locate these messages or help us fix whatever caused them to go missing

## Acceptance Criteria 
- [ ] We should be able to see these logs somewhere (preferably grafana)

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by travis-newby** [comment]
This issue is impacting our ability to find and diagnose issues in staging. Is there anything we need to do to get some help on this?

**Comment by mchelen-gov** [comment]
code reference: https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/vetext/service.rb#L30

**Comment by mchelen-gov** [comment]
here is [a query](http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Staging)%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22,%20filename%3D~%5C%22.%2Bjson.log%5C%22%7D%20%7C%20regexp%20%5C%22(%3FP%3Ctime%3E%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd)%20(%3FP%3Cprocess_name%3E%5C%5C%5C%5Cw%2B.%5C%5C%5C%5Cd)%20%5C%5C%5C%5Cs%2B%20(%5C%5C%5C%5C%7C)%20(%3FP%3Cjson%3E.%2B)%5C%22%20%7C%20line_format%20%5C%22%7B%7B.json%7D%7D%5C%22%20%7C%20json%20%7C%20message%3D~%5C%22VEText.*%5C%22%22%7D,%7B%7D%5D) that will return these entries, it seems like `payload_path` might be missing for some reason?

**Comment by patrickvinograd** [comment]
payload_path probably gets added to the logging context/paylod for log messages coming from Rack or the controller layer, but it's not injected for every single invocation of `Rails.logger.info`. So yes, wrong query to find this. 

I did also have trouble finding the generic request-processing messages when I was debugging this with Jayson earlier, but per the support thread they seem to be queryable now. Maybe it was an exact-match vs. regex match issue...

**Comment by mchelen-gov** [comment]
ok cool, is anything else needed for this from Ops?

**Comment by jhouse-solvd** [comment]
@travis-newby / @patrickvinograd / @jperk51 

Did you end up getting the help that you needed? ie Can you now find the logs or specific information that you're looking for in? 

Especially now that we've enabled Loki in prod, we want to make sure we're addressing any issues or concerns that you may have.
