### ISSUE TITLE
QA New Translated Content URLs on Content dashboard

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#29005]
## Issue Description
As we roll out new products on our KPI dashboards, we need to make sure that our data is accurate and trustworthy.

This ticket is for Translated Content products owned by the Content & Localization VFS team. 

#### Related links

- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28340) with request
- [Request template](https://docs.google.com/spreadsheets/d/1pdKJTz9fuFGR64UXXbTe3Bu_tENFmh0MAmMBt9k-A3s/edit?usp=sharing) with new URLs
- [Content KPI dashboard](https://va-gov.domo.com/page/426422632)

---
## Tasks
- [x] Verify that data formats are correct
- [x] Confirm the data is what is expected (does the info collected measure what it's supposed to measure?)
- [x] Identify & document invalid values

## Acceptance Criteria
- [x] The production Translated Content KPI Dashboard in Domo has accurate and trustworthy data

**Comment by bsmartin-ep** [comment]
### QA

## Highlights

**regex:**
`www.va.gov/tagalog-wika-mapagkukunan-at-tulong/|www.va.gov/health-care/covid-19-vaccine-esp/|www.va.gov/asistencia-y-recursos-en-espanol/|www.va.gov/coronavirus-veteran-frequently-asked-questions-tag/|www.va.gov/resources/how-to-get-free-language-assistance-from-va/|www.va.gov/health-care/covid-19-vaccine-tag/|www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/|www.va.gov/tagalog-wika-mapagkukunan-at-tulong|www.va.gov/resources/how-to-get-free-language-assistance-from-va|www.va.gov/health-care/covid-19-vaccine-esp|www.va.gov/asistencia-y-recursos-en-espanol|www.va.gov/coronavirus-veteran-frequently-asked-questions-esp|www.va.gov/coronavirus-veteran-frequently-asked-questions-tag|www.va.gov/health-care/covid-19-vaccine-tag`

Chart title | Assets | Pass / Fail
-- | -- | --
Usage trends |   |  
Unique users |   |  
Unique pageviews |   |  
Avg. seconds to click |   |  
Avg. star ratings |   |  
Total clicks by device |   |

**Comment by chloedotbrown** [comment]
QA complete, closing ticket. Thanks all!
