### ISSUE TITLE
When VBMS is down, rescue and send to CMP

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#29003]
## Background
For a small percentage of Ch31 applications, they are not saving in VBMS so we need to ensure a way to preserve the generated PDF and try t ore-save them later when VBMS is able to take them.

## Supporting details
- Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/37277/events/b61d590548d34a24b8ab4f218a8182bd/?environment=production&project=3&statsPeriod=90d#exception

## Tasks
- [x] Investigate how best to store the PDFs after generation
- [x] Send the PDF'd applications to  Central Mail so they can be processed and saved in the Veterans eFolder
- [x] if user has no participant_id, send to CMP (may need to update this task?)

## Acceptance Criteria
- [x] PDFs are routed when they are not sending to VBMS
- [x] A PR has been requested for merging

**Comment by RudyOnRails** [comment]
@jason-gcio / @kathleencrawford , I know you two are busy, but wanted to get a quick confirmation from you (maybe I'll figure out the answer as I type my thoughts out - usually happens)...

I see in the code that when a user's `participant_id` is blank, we send to CMP, then also process through VRE (which attempts to upload to VBMS). Does that mean we should not attempt to send to VBMS at all if there is no PID present? And instead only upload to CMP and send the one-off email?

**Comment by jason-gcio** [comment]
Yea I think we are thinking that this might actually be a gate: if there is no PID, they don't even want the application.  I thought I remember them saying that last time.  This ticket talks about how if VBMS is down, route to CMP as a back up and note it in the one-off/summary email(s)
