### ISSUE TITLE
526: Add validation for anticipated separation date

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29013]
## Description

Add validation to `anticipatedSeparationDate` for title 10 activated guard/reservist. This date can’t be more than 180 days in the future.

## Tasks

- [ ] Add validation for date
- [ ] Add unit tests
- [ ] Update mock data (failing when submitting this data on staging)

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
