### ISSUE TITLE
NOD: Required address depends on homeless answer

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29015]
## Description

Lighthouse recently updated the Notice of Disagreement schema to only require an address if the Veteran answers that they are _not_ homeless. If homeless, the address will be optional.

## Tasks

- [ ] Move homeless question before contact info page
- [ ] Make address dynamically required if the Veteran reports that they are not homeless
- [ ] Update tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
