### ISSUE TITLE
[FSR] Map payroll deduction options data to the correct fields

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29010]
## Issue Description
All payroll deductions are captured into in a single group and placed in the "Other" category. Data values should be mapped to the appropriate fields. Refer to [form VA5655](https://www.va.gov/vaforms/va/pdf/va5655.pdf)

![VA Form 5655, Financial Status Report 2021-08-20 14-27-28(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/a966b270-d782-4100-ac24-341779cbc2b1)
---
## Tasks
Map the appropriate option data to the correct values listed below:
- [ ] Federal tax, State tax, Local tax -> Box 14A
- [ ] 401K, IRA and Pension -> Box 14B
- [ ] FICA (Social Security and Medicare) -> Box 14C
- [ ] All other deductions -> Box 14D

## Acceptance Criteria
- [ ] Payroll deductions data should be mapped to the appropriate fields. All values including the total deductions field 14E should be verified in the submit transformer
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
