### ISSUE TITLE
Adjust solo mailer so that recipient is notified that the application went to CMP

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#29025]
## Background
Now that we are sending to CMP if VBMS is down, we should adjust the one-off mailers so the recipients don't hunt for the application in VBMS.

## Tasks
- [x] adjust test(s)
- [x] adjust one-off mailer so that it signifies that the application has gone to CMP and not VBMS (so the RO doesn't waste time searching for it. Will probably need to adjust the mailer method to accept an additional argument to indicate if the app has gone to CMP.

## Acceptance Criteria
- [x] if PDF goes to CMP then communicate that in the solo mailer this way:
  - [x] when VBMS is down and there is a PID:
      > Submitted Application
      > Veteran’s PID: 1234567890 (routed to CMP)
      > Type of Form Submitted: 28-1900
      > Submitted Date:  09/01/2021
      > Sent from: VA.gov
      > Note: This is an automated message sent from an unmonitored email account.

  - [x] when there is no PID:
      > Submitted Application
      > Veteran’s PID: (routed to CMP)
      > Type of Form Submitted: 28-1900
      > Submitted Date:  09/01/2021
      > Sent from: VA.gov
      > Note: This is an automated message sent from an unmonitored email account.

- [x] A PR has been requested for merging
