### ISSUE TITLE
TUD - fix & update population Rake task

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#29023]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Currently the Rake task that populates the TUD account table is not functioning properly.

---
## Tasks
- [x] Determine why the Rake task isn't working and fix it.
- [x] Update the Rake task to overwrite existing accounts in the TUD account tables

## Acceptance Criteria
- [x] The Rake task will work again.
- [x] The Rake task will be able to be run on instances of vets-api that already have a populated test accounts table and update it.
