### ISSUE TITLE
[Offboarding] Add Yubi-keys in github bot accounts as an offboarding item

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#29039]
## Description
When an Operations person leaves, we should remove their access via Yubi-key to the github bot accounts (va-vfs-bot, va-vsp-bot, and va-bot)

---
## Tasks
- [x] Add an item (and perhaps accompanying instructions) to the offboarding template

## Acceptance Criteria 
- [x] Documentation is updated for the removal procedure
- [x] Item is added to offboarding checklist

---
### Reminders
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/CJYRZK2HH/p1631036588245500

**Comment by jbritt1** [comment]
Doc created: https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members

**Comment by jbritt1** [comment]
Added item to offboarding checklist: https://github.com/department-of-veterans-affairs/va.gov-team/commit/73fd4f704adc499ffc0f39c29cb99b667b049fd8

**Comment by dginther** [comment]
Looks good! Thanks JB!
