### ISSUE TITLE
[Kubernetes] Changes in a secret value do not trigger a fresh deployment of services utilizing those secrets

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#29036]
## Description
When a secret is changed in Parameter Store, it does not trigger a deployment of whatever pods are using that secret value.

This could lead to problems with services using old values for secrets.

Consider ways to resolve this issue, including
- Use versioned secrets, so that a change to the secret is a change to the manifest, thereby causing a deploy
- Use Argo Workflows to trigger a deploy when a change in SSM PS is detected? (might not be possible)

Also consider that we may not want to necessarily deploy the latest secret in all environments at the same time.

---
## Tasks
- [ ] 

## Acceptance Criteria 
- [ ] When a secret value is changed in SSM Parameter Store, a redeploy of the service/services using that secret happens

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Personally, I think the version pinning method is the lowest LOE that could get us closer to closing this sooner.
