### ISSUE TITLE
[Pomerium] Pomerium needs deployments in Staging and Prod

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#29038]
## Description
Pomerium needs to be deployed in the staging and prod VPCs

## Background/context 
Taylor did not finish deploying Pomerium across all the environments

---
## Tasks
- [ ] Deploy/configure Pomerium in staging and prod

## Acceptance Criteria 
- [ ] Pomerium is running in all VPCs

---
### Reminders
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Do we still want Pomerium?

**Comment by jbritt1** [comment]
No longer needed, closing.

**Comment by jbritt1** [comment]
@oseasmoran73 to close after relevant PRs are merged.

**Comment by oseasmoran73** [comment]
Pomerium and kubernetes-dashboard have been removed. Closing ticket
