### ISSUE TITLE
R&S Updates: GI Bill and other VA education benefit payment FAQs

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#29031]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/gi-bill-and-other-va-education-benefit-payments-faqs/):  

New intro:
Get answers to questions you may have about your GI Bill payments.

Add headers and rearrange the questions as follows:
How education payments work
  Followed by questions 3-5
Advance payment
  Add a new question -- What's an advance payment?, 
   followed by questions 1 and 2.
    (Leave the example where it is.)

**Keep reading this page to find out what information you'll need to have ready when using the calculator.**

Add "free financial planning services" under related information. (We have it as a text link, but that's easy to miss and it seems like a benefit that bears repeating.) 
Links to: https://benefits.va.gov/insurance/bfcs.asp

### Tasks

- [ ] DEPO to approve changes as described above, or edit (Beth)

- [ ] SC to make changes in Drupal (Laura)

- [ ] SC to QA and publish (Randi)

### Acceptance Criteria

- [ ] Updated page is live

**Comment by lwalsh617** [comment]
@RLHecht - Changes at the top of this ticket have been made and page is ready for your review. Thanks! 
http://preview-prod.vfs.va.gov/preview?nodeId=15640
