### ISSUE TITLE
Remove "disallow" entries from Robots.txt file on August 23rd 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29034]
## Issue description
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
Remove the following system names from robot.txt file prior to the go-live on on August 25, 2021

- [ ] Salisbury health care
- [ ] Salem health care
- [x] Houston health care
- [x] Pacific Islands health care

## Acceptance Criteria
System names are removed from robot.txt file on August 5th
