### ISSUE TITLE
[MCP] Create designs for reduced expected data for bill history table

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29047]
## Issue Description
We learned that the data being sent to us through the CCPC API is much more limited than expected, and we're still trying to figure out what those constraints are. In the meantime, we need to create designs that account for a much more limited dataset.

It's possible that we will only be receiving the data found on the most recent statement, so create designs that account for that.

---
## Tasks
- [ ] Design a new detail page depicting the most recent statement's data
- [ ] Design a new detail page that includes only the download links
- [ ] Upload to UXPin

## Acceptance Criteria
- [ ] (2) Designs uploaded to UXPin and linked in this ticket

**Comment by rebeccawalsh** [comment]
Zenhub duplicate
