### ISSUE TITLE
[Jsonnet tagging] Create Jsonnet function that applies tags to all resources

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#29042]
## Description
For easy tagging of EKS resources, we should consider adding a jsonnet function which adds tags to all resources that get created with jsonnet.

---
## Tasks
- [ ] Create Jsonnet function which can be included in resources to add the standard tags we use

## Acceptance Criteria 
- [ ] Resources created using Jsonnet have the appropriate tags applied when they are created.

---
### Reminders
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Since we are moving away from Jsonnet, can this be closed?

**Comment by ph-One** [comment]
I would say this is one that we can close.
