### ISSUE TITLE
[ArgoCD] ArgoCD and secrets

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#29040]
## Description
ArgoCD thinks that some services which update their own secrets are out of sync.
- Kubernetes Dashboard
- Pomerium

## Background/context 
Because these services modify their own secret values, ArgoCD sees them as out of sync with what is in the manifests repo. Taylor tried to add an annotation to ignore changes to this item but it doesn't seem to be working.

---
## Tasks
- [ ] Investigate the annotations required for this and see if it is a viable solution
- [ ] If the annotations will not work, we should provision these secrets from Parameter Store instead of allowing the applications to update the secrets themselves.

## Acceptance Criteria 
- [ ] Any applications which show as 'out of sync' in ArgoCD because they modify their own secrets no longer show as out of sync

---
### Reminders
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Could this perhaps also be solved if we went the route of version pinning secrets in application manifests for department-of-veterans-affairs/va.gov-team#29036?
