### ISSUE TITLE
BDD: Update supporting evidence content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29059]
## Description

Content updates to supporting evidence choices page (see screenshots)

<details><summary>Supporting evidence choices</summary>

<img width="592" alt="Screen Shot 2021-08-16 at 9 19 02 AM" src="https://user-images.githubusercontent.com/54544300/129570167-ebef49b6-9f9d-4875-ab10-d66496f307fb.png"></details>

<details><summary>Evidence types dropdown</summary>

<img width="627" alt="Screen Shot 2021-08-16 at 9 17 41 AM" src="https://user-images.githubusercontent.com/54544300/129570344-6def133c-47da-456a-82d3-4154994f69fc.png"></details>

## Tasks

- [ ] Update evidence choice page content
- [ ] Content matches design 

## Definition of done

- [ ] All tasks complete
- [ ] All test passing
