### ISSUE TITLE
FE-Tools S3 Bucket Permission

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#29060]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Some folks on FE-Tools team don't have access to buckets required. I am requesting access to these buckets for the following folks: @oseasmoran73 , @k80bowman , @ndsprinkle 

s3-buckets:
- [ ] dev-va-gov-assets
- [ ] vetsgov-website-builds-s3-upload
- [ ] apps.staging.va.gov
- [ ] apps.www.va.gov
- [ ] content.www.va.gov
- [ ] content.staging.va.gov
- [ ] content.dev.va.gov

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
Let's clarify the tasks here. We likely just need to add the FE Tools users to the correct IAM security groups in AWS and have them verify that they can access.

**Comment by oseasmoran73** [comment]
@omgitsbillryan Yeah we have access to them. I was not sure if @ndsprinkle had it, so I included it in the ticket above. But me and @k80bowman have access to it.

**Comment by omgitsbillryan** [comment]
Thanks for the timely response. The IAM group was already in place and already have some of the permissions you were looking for which made my job easy to just add some additional buckets to the list.
