### ISSUE TITLE
[Design] HRT- Introduction Page mockup (Final Draft)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#29064]
## Description 
_The Office of Resolution Management, Diversity and Inclusion (ORDMI) is the office in-charge VA Wide for processing complaints from Veterans and Employees for alleged Civil Rights Violations as well as for Harassment, Reasonable Accommodations, and other inappropriate behaviors while on a VA Site._

_In response to Section 5303 of the Deborah Sampson Act which is part of the Megabus Bill that was passed in January, and new congressional demands for action, a team of Presidential Innovation Fellows (PIFs) is scoping the feasibility of creating a secure, online reporting tool on VA.gov that would enable Veterans and VA employees to report alleged incidents about violations from Veterans and VA employees which occur while on a VA Site._

## Scope of Work
In support of the HRT initiative we'll need to build a "Harassment Reporting 5303" Introduction page as the home page for Veterans and Beneficiaries that are looking to access the Harassment reporting tool (HRT).  The content from this pace will be provided by the PIF/ORDMI team and we'll need to get that information vetted by our local content team for inclusion on the landing page.  
A similar page with content exists: VA OIG Web Page and Link to Report Wrongdoing - https://www.va.gov/oig/hotline/default.asp.  
Business Requirements are listed: [spectrum of workplace behaviors (version 2).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6703489/spectrum.of.workplace.behaviors.version.2.xlsx)
 

## Tasks 
- [ ] Incorporate feedback from 1st draft ticket [#26447](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26477)
- [ ] Ensure design is ally compliant and complies with VA.gov design system specifications 
- [ ] URL and Placement will be determined by PO/PM of PW Team

## Acceptable Criteria 
- [ ] Designs are completed in accordance with task identified above 
- [ ] Designs are approved via VSP Design Intent Review / Design System 
- [ ] Designs can be used by FE team to build our landing page

**Comment by brianalloyd** [comment]
Workflow completed, still pending a few items post legal review but will open a different ticket to account for those elements once ready to incorporate into the designs.
