### ISSUE TITLE
Claim Status Tool Label update

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29078]
## Issue Description
Fields incorrectly labeled

---
## Tasks
- [ ] Investigate where submission date is in the current design, assess feasibility of updating
- [ ] Submission date should be discharge (RAD) date

## Acceptance Criteria
- [ ] New design for submission date
---

**Comment by sortizsh** [comment]
@jacobworrell  can we bounce this back to product? It needs clarification in tasks. Eng couldn't find where the submission date is in current design.
