### ISSUE TITLE
Hi res image download rendered as a link without href

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29079]
## Issue Description
The content release was blocked on August 18 because of broken links caused by `<a href download>Download full size photo</a>`. The content editor checked the box for "high-resolution photo should be available for download by site visitors" although no high res image was available, Regardless, there is a front end defect where the link is rendered as a link with no href (even it was high res) 

Specific instances across Houston health care were fixed so the build could go out
- example:  `houston-health-care/staff-profiles/arnisha-carter` 

Reference [Slack thread](https://dsva.slack.com/archives/C0MQ281DJ/p1629314908133900)

![image](https://user-images.githubusercontent.com/55411834/130510691-79b69d58-0f71-4284-9577-33bacb5635ec.png)

### Dependencies
CMS needs to validate 
- availability of hi res image 
- that a link leads to an image 
   - needs to be done outside of content build (so build time performance isn't impacted)

## Goals
- [ ] If hi res is available **and** a link to the image is available **and** the link leads to an image, display link

## Dev Notes
```
image {
          alt
          title
          derivative(style: ORIGINAL) {
            url
            width
            height
          }
        }
```

---
## Tasks
- [ ] Discovery effort to determine how to confirm availability of hi res (does original always exist?)

Assuming discovery confirms validation
- [ ] If hi res is available **and ** a link to the image is available **and** the link leads to an image, display link
- [ ] Otherwise, do not render link

## Acceptance Criteria
- [ ] Links to download high res images are displayed only for images validated by CMS
- [ ] Rendered links include href

**Comment by mpelzsherman** [comment]
Confirmed in prod by temporarily enabling hi-res downloads on https://www.va.gov/erie-health-care/staff-profiles/john-a-gennaro/.
