### ISSUE TITLE
NOD: Set max combined issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29074]
## Description

When submitting a Notice of Disagreement to Lighthouse, the max number of issues is set to 100. Internally, we allow 100 new additions along with however many loaded issues are selected. This would cause more than 100 issues to be submitted. Add a max new issue limitation based on all selected issues.

## Tasks

- [ ] Add validation check for a max combined issue count of 100
- [ ] Update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
