### ISSUE TITLE
Claim Status Tool - Status Checking Alternative

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29086]
## Issue Description
Faster and easier status checking 

---
## Tasks
- [x] Develop language and messaging advising Veteran to use mobile app to check status. (This allows use of easier biometric login functionality)

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Conversation about when we actually should do this is located here:

https://dsva.slack.com/archives/C018V2JCWRJ/p1630419846035000

But the prelim design for this is done - will need to go through content as well.
