### ISSUE TITLE
Claim Status Tool - Decision Letters

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29083]
## Issue Description
Determine how to provide decision letters digitally.

---
## Tasks
- [ ] Follow up with Jim Adams on the eBenefits migration team. 
https://vsateams.invisionapp.com/console/share/SWYMSCCJ3ZD/600538153

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
So the point of this ticket is to see if we can simply link users to the disability rating tool or keep them within the va.gov ecosystem instead of linking them to ebenefits (as we currently do).

I spoke to Jim Adams of the ebenefits Migration Team and he said that there is still a documents list feature in ebenefits that has still not been migrated - which I believe would be valuable to users. The other things listed in the CTA (update personal info, get help filing claims) should all be on va.gov at this point.

So the next steps here are to determine if:

a. We want to preserve that link to ebenefits for the sake of the document list functionality,
b. Where we want to put the disability ratings tool on va.gov link, and
c. Where we drop the link to instruct users to update their personal info (if necessary)

**Comment by kevinstachura** [comment]
I believe we may be able to show the documents list link on the files tab in the CST, then we can remove the entire reference to ebenefits on the sidebar of the 'list' view in the CST (the landing page). Either way, we now have a direction on this and can begin to move forward on a solution, therefore satisfying this ticket.
