### ISSUE TITLE
Claim Status Tool - Incorporate decision letter data

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29082]
## Issue Description
As a Veteran, I would like to be able to see my decision letter in the Claim Status Tool. 

---
## Tasks
- [x] Research if we can incorporate decision letter data into Claim Status Tool

## Acceptance Criteria
- [x] Document what is possible and where we can display data.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
Initial discussions with designer:
https://dsva.slack.com/archives/C5AGLBNRK/p1639065613346800
Idea

Trying to find if-where we can grab a claim's decision letter:

https://adhoc.slack.com/archives/C01KFC934GJ/p1639492984032900?thread_ts=1638803468.025200&cid=C01KFC934GJ

https://dsva.slack.com/archives/CK466V65V/p1639492175003700

https://dsva.slack.com/archives/CE4304QPK/p1639417930279100

https://dsva.slack.com/archives/C8R3JS8BU/p1639418422069900

Some of the threads imply that decision letters might already be in the vets efolder.
Not sure at this point

**Comment by vhenry07** [comment]
Per discussion with EVSS: Pohlman, Michael <Michael.Pohlman@va.gov> - VBMS contact that can likely point us in the right direction 

Document type for rating decision - Rating Decision (e.g. VA Form 21-6796)	L137

**Comment by vhenry07** [comment]
Investigated on our end and awaiting feedback. Will create ticket for next steps.

**Comment by michelpmcdonald** [comment]
I researched this a little more by using the various efolder API and experimenting:

I found the decision letters, they are in the users efolder.

Lots of problems:
1.  **Generic name of "Notification Letter", and not all notification letters in the efolder are "Decision Letters"**, all of these are named "Notification Letter", but only 2 of them are actual Decision Letters:
```
2021-08-17: Intent to file, Notification Letter - "We received your intent to file on August 16, 2021.   You indicated you would like to file a claim for compensation...."
2021-08-20: User Action: Claim Submitted, claim.date field
2021-08-23: Notification Letter - "Thank you for submitting an application for VA benefits, which we received"
2021-08-26: Notification Letter - "We have requested copies of your private medical records from.."
2021-09-09: Decision Notification Letter - "Service connection for tinnitus is granted with an evaluation of 10 VeteransBenefits percent effective August 16, 2021."
                                  "A decision on entitlement to compensation for asthma is deferred."
2021-09-19: Notification Letter - "Gulf War New Presumptive Outreach Letter"
2021-10-20: Notification Letter - "We are still processing your application for compensation. We apologize for the delay."
2021-10-28  Decision Notification Letter - "Service connection for asthma is denied. "
```

2. **There is not a great way to tie "Notification Letters" to a specific claim.**  Nothing in the efolder file metadata(doc type, etc), not even in the letter pdf text itself, mention anything about claim ID or anything like that, at all.  I got the above list by looking at the claim and using the claims open "date" and "close" date.  That might kind of work, but if the vet has multiple open claims at the same time it's going to have to be a fuzzy match based on the claims issues i guess.  I'd have to parse the PDF and see what issues are mentioned.

3. **Parsing PDFs is not great, at all.**  PDFs really don't care about paragraphs and such, so, for example, in decision letters all the letter text and the left column generic boiler plate **text is mixed up**, so for example, here is some of the Decision Letters first page "text":
`VET USER                                                                     We have included with this letter: 1234 ROAD 5.                                                              1. Explanation of Payment                                                                                   2. Additional Benefits Anytown KS 30341                                                          3. Where to Send Your                                                                                   Correspondence                                                                                   4. VA Form 20-0998 We made a decision on your VA benefits.                                           5. Rating Decision                                                                                   6. Fraud Prevention Attachment Dear Vet:                                                                Contact information:                                                                                   Web: www.vets.gov This letter will guide you through the information you should know                Phone: 1-800-827-1000 and steps you may take now that VA has made a decision about your                 To send questions online: visit benefits.                                                                         https://iris.custhelp.com/                                                                                   Social Media: Your Benefit Information:                                                         Twitter: @VAVetBenefits ●   Service connection for asthma is denied.                                      Facebook: www.facebook.com/                                                                                   VeteransBenefits Your monthly entitlement amount is shown below:        `
