### ISSUE TITLE
Jenkins - update worker node sshd mac ciphers

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29081]
## Description
We have updated the mac ciphers deployed to all of our ec2 instances which is verified by the ansible check os job here http://jenkins.vfs.va.gov/job/utility/job/os-check-utility.  However, the jenkins worker nodes were not captured by this change which is causing the job to fail.

![image](https://user-images.githubusercontent.com/76792875/130511428-d6da7c7f-91da-4107-bbf2-c736967a42a5.png)

## Technical notes
Needed mac ciphers
``

---
## Tasks
- [ ] update sshd_config for jenkins worker nodes

## Acceptance Criteria 
- [ ] ansible os check no longer fails

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
[This job](http://jenkins.vfs.va.gov/job/builds/job/jenkins-worker/) runs and creates a Jenkins worker node AMI.
