### ISSUE TITLE
Unbound - add s3 permissions to IAM role

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29095]
## Description
Migrating from AmazonEC2RoleforSSM (soon to be deprecated) to AmazonSSMManagedInstanceCore, there are differences between them which broke access to the configurations needed to deploy unbound.

## Background/context 
- https://aws.amazon.com/blogs/mt/applying-managed-instance-policy-best-practices/
- https://github.com/department-of-veterans-affairs/terraform-aws-vsp-unbound/commit/7923192e000c5bb216d543ab47789ebecec79d60

---
## Tasks
- [x] restore s3 permissions to unbound role
- [x] redeploy unbound

## Acceptance Criteria 
- [x] internal VA dns works correctly

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Updated permissions and the unbound server now has access to the correct s3 bucket
