### ISSUE TITLE
Profiles without bios should not have html page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29096]
## Issue Description
Leadership and care coordinators use staff profile content type
- It makes sense to build a page for leadership staff because they have bios
- It does **_not_** makes sense to build a page for care coordinators because they do not have bios 

**Questions for the future**
- What to do with care coordinators who do have bios?
- What happens when staff member's role changes?
- What happens if staff member without a bio gets one? 

**Examples**
[Pittsburgh LGBT care coordinators](https://www.va.gov/pittsburgh-health-care/health-services/lgbt-veteran-care/)
[Kristen Lyons](https://www.va.gov/pittsburgh-health-care/staff-profiles/kristen-lyons/)
[Profile with bio](https://www.va.gov/pittsburgh-health-care/staff-profiles/kevin-p-amick/)

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/130519153-f1affacd-523a-4ffe-8379-3bc38ddaab0f.png)

![image](https://user-images.githubusercontent.com/55411834/130519238-82870d8d-1654-41d3-9353-12fc04084847.png)

</details>

---
## Tasks -5
- [x] If a staff profile has a bio, create html page
- [x] If no bio exists, do not create html page

**Separate story** -3 
- [x] Hyperlink staff member's name only if profile page exists (do this before removing pages)

## Acceptance Criteria
- [x] Only profiles with bios have published pages

**Comment by mpelzsherman** [comment]
Tugboat instance for validation: https://web-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov

Note for example: https://web-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov/pittsburgh-health-care/staff-profiles/kristen-lyons/ does not exist.
