### ISSUE TITLE
Synthesis for VA communication methods

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29105]
## Issue Description
New options for contacting the VA are becoming available and need to be added to the VAMC pages. Before we can determine the right experience for Veterans, we need to understand both the individual options and the landscape

Existing communication options: 
- Phone numbers
- Crisis Line (legislatively mandated, must remain)
- Mental health phone numbers (legislatively mandated, must remain)

VA health chat discovery #27686
Secure messaging discovery  #27687
VA health connect discovery #27688
Communication audit #29548 

---
## Tasks
Based on discovery efforts, consider the entire VAMC communication landscape and Veteran use cases and
- [x] Document outstanding questions
- [x] Develop basic Veteran journey map for communicating with the VAMC
- [x] Make recommendations for next steps related to the display for communication options on VAMC pages **and** Facility Locator, which may include Veteran research, mock-ups, info gathering

## Acceptance Criteria
- [ ] Use cases are understood
- [x] Recommendations for Veteran research and next steps

**Comment by lildziner** [comment]
**Synthesis lives in this [Communications Audit - Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/communication-audit-research-findings.md) markdown file**
