### ISSUE TITLE
[Research] Phase 2 Usability Synthesis 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#29109]
## User Story
- As a product team, we want to know the findings from the usability test. 

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/conversation-guide.md)

## Description
Analyzing the videos and notes from the research study on the Phase 2 of Check-in to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [ ] Do analysis

## Acceptance Criteria
- [x] Post synthesis documents to GitHUB
- [x] Write top-line summary

**Comment by kristenmcconnell** [comment]
Mural posted to GiHub. Skipping right to the report due to timing.
