### ISSUE TITLE
Fix link on Transfer Your Post-9/11 GI Bill Benefits

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#29113]
## Issue Description

This is a request from the Education Service to fix a broken link on the [Transfer Your Post-9/11 GI Bill Benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) page.

This link is broken - Transfer, change, or revoke a TOE

Please replace with https://milconnect.dmdc.osd.mil/milconnect/

---
## Tasks
- [ ] _Fix broken link (Selina)_
- [ ] -Review and approve changes (Beth)_
- [ ] _Publish page (Selina)_

## Acceptance Criteria
- [ ] _Fix is live in production_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@bethpottsVADEPO this fix is ready for review.

Transfer your Post-9/11 GI Bill benefits: http://preview-prod.vfs.va.gov/preview?nodeId=952
