### ISSUE TITLE
[Research] Phase 2 and 3 Check-in Usability Report 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#29110]
## User Story
- As a product team, we want to document and share the findings from the Phase 2 usability test. 

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/conversation-guide.md)

## Description
A research report detailing findings and design recommendations from the research study on the pre-MVP of Check-in.

##Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Create research reports/readout documents of findings

## Acceptance Criteria
- [x] Update the [research history](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md) document
- [x] Deal with recordings once analysis is complete
- [x] Create necessary issues/tickets that address findings in coordination with Corey
- [x] Schedule readout sessions with stakeholders, team, Demos, UX weekly(?)

**Comment by kristenmcconnell** [comment]
- Schedule Martinsburg readout at the same time. Message Naomi about both.

**Comment by kristenmcconnell** [comment]
WIP draft report: 
[https://app.zenhub.com/files/133843125/38654e43-fa3d-4243-8f65-367b636d23c8/download](https://app.zenhub.com/files/133843125/38654e43-fa3d-4243-8f65-367b636d23c8/download)

**Comment by kristenmcconnell** [comment]
Final research report on GitHub: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/research-findings.md

Information added to the research history file.
