### ISSUE TITLE
[Research] Martinsburg Site Visit (placeholder)

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#29111]
# Tasks
- [x] Travel to Martinsburg
- [x] Interview staff and Veterans based upon this [research plan and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/research-plan.md)
- [x] Take notes

# Acceptance Criteria
- [x] Type up notes and post to GitHub

**Comment by kristenmcconnell** [comment]
[Notes on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/session-notes.md). Report will be in another story.
