### ISSUE TITLE
Application Build Pipeline (CI) — Release build of only changed apps in vets-website PRs

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#29132]
## Problem Statement 
Currently, all VFS teams use the same shared code repository `vets-website` for frontend apps. Although the apps are separated within the repo, changes to one app must be built and deployed along with the entire site. This slows down development, and creates unnecessary risk and overhead for VFS teams. 

How might we enable PR builds to include only changed applications, as a step towards autonomous deploys?

## Hypothesis or Bet
* PR builds of only changed apps will allow VFS teams to work faster and improve developer experience. 
* PR builds of only changed apps will allow Platform to test the architecture fundamental to autonomous deploys before changing developer workflow, decreasing risk and developer disruption. 

## We will know we're done when... ("Definition of Done")
* [x] vets-website PRs build only changed applications (on allowlist)
* [x] Unit tests for only changed app builds include test isolation
* [x] Documentation is updated
* [ ] VFS teams are trained (NA)

## Known Blockers/Dependencies 
* Open question: Who to release this to? Does the scope of this work include releasing to all VFS teams, or only to a beta team?

## Projected Launch Date
* End of Nov 2021

### ... tested?

- [x] Usability test (#34402) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] ~Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)~
    * ~_List the existing product that this initiative fits within, or add a new product to this list._~
- [X] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [x] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] ~_(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)~

### ... measurable

- [X] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
- [X] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [x] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch.
- [x] Communications to VFS teams (using following VFS engineer questions as prompt) https://dsva.slack.com/archives/C5HP4GN3F/p1642789833024000?thread_ts=1637176642.141900&cid=C5HP4GN3F

### Documentation
* ~**`PRODUCT_NAME`**: _directory name used for your product documentation_~
* **Product Outline**: [App Deployment Platform product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/app-deployment-platform/product-outline.md)
* ~**README**: _link to VFS-facing README for your product_~
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: #34402
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: 
   * Platform Objective 2 (KR:  >=1 VFS team can deploy their frontend app code at any time during business hours without manual Platform intervention.)
   * vets-website PR pipeline speed
   * High level goals
      * Autonomy
      * Scalability
      * Move towards being tech agnostic
* **Release plan**: #34398

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by meganhkelley** [comment]
Note that some of these tickets are no longer within the scope of this initiative — epic was originally created to include releasing this functionality to dev and staging. Updated plan is to limit the scope of this to releasing this functionality in PRs.

**Comment by theodur** [comment]
Closing this epic out now that we've [released](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34398#issuecomment-1063449110) changed app builds in PRs ✅
