### ISSUE TITLE
Packer - job to clean up stale instances

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29139]
## Description
We currently have two packer jobs that run on a schedule or manually.  Either way, if a packer build fails the ec2 instance is not automatically terminated.  This can result in stale instances living in the utility the utility subnets.  We will want to implement something similar to this GHA (https://github.com/department-of-veterans-affairs/devops/actions/runs/1198662382) that cleans up Packer build nodes.

---
## Tasks
- [x] Create GHA to periodically clean any stale packer build instances

## Acceptance Criteria 
- [x] No lingering packer build instances will exist long term in the utility subnets

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Confirmed this script now cleans up any leftover packer build instances

**Comment by dginther** [comment]
boom!

**Comment by mleclerc00** [comment]
The query in the script itself was flawed as it would only capture a single instance from the list of results.  This resulted in a lot of stale runners running needlessly.  The change pushed 4 days ago fixes this issue.
