### ISSUE TITLE
VAMC health service "Available at these locations" list sort order

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29146]
## Issue Description
The "Available at these locations" list in a health service accordion doesn't seem to have a logical order - likely due to a bug and/or oversight.

![image](https://user-images.githubusercontent.com/55411834/130649944-529e59eb-be75-4a06-8c95-851d42c23b32.png)

### Expected behavior
The list should be ordered using the same logic as the Locations page
Main location(s) by alpha
Clinics by alpha

---
## Tasks
- [ ] Implement sort order logic from Locations page for  "Available at these locations" list in a health service accordion

## Acceptance Criteria
- [ ] Sort order within health services accordions is consistent with Locations page sort order logic
- [ ] VA clinic locations are listed first, followed by Doms and CLCs, followed by Mobile clinics 
- [ ] Facilities are listed alphabetically within a facility subtype

**Comment by stefaniefgray** [comment]
Link to page where this is happening: https://www.va.gov/houston-health-care/health-services/
