### ISSUE TITLE
[VAMC] Remove "disallow" entries from Robots.txt file ~August 25

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29153]
## Story
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
Remove the following system names from robot.txt file on/about August 25th
Redirect is scheduled on Wednesday September 1st

- [ ] Durham health care
- [ ] Central Iowa health care
- [ ] Hampton health care
- [ ] Fayetteville-Arkansas health care

## Acceptance Criteria
All System names are removed from robot.txt file on/about August 25th
