### ISSUE TITLE
[MCP] Use case: Veteran doesn't pay copays but pays for prescriptions 

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29169]
## Issue Description
This ticket is part of the epic where we will be creating mocks for each of our use cases for testing and engineering purposes.

**Use case:** Veteran doesn't pay copays but pays for prescriptions 

---
## Tasks
- [ ] Create a design that reflects the use case above
- [ ] Upload to UXPin
- [ ] [Update GH design readme file](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/Debt%20Resolution/Medical_Copays/design/README.md)

## Acceptance Criteria
- [ ] Designs uploaded to UXPin
- [ ] GH design readme updated and linked in ticket
