### ISSUE TITLE
Expose Endpoint: Update Profile

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#29163]
Dependency: Receiving the endpoints from Rob

- [ ] Create λ
- [ ] Attach to API gateway
- [ ] Call VEText group authentication endpoint with User DUZ, Station number, and application key
- [ ] Expose **UPDATE** endpoint in CHIP 

Will only update individual clinic. 

**Task is Done When:**
Endpoint is exposed and output is visible in postman

**Comment by katieroach** [comment]
@wamccarty - could you please update this story so that we can understand if this is completed or not?  Thanks!

**Comment by aschulhof** [comment]
Duplicate - https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/53
