### ISSUE TITLE
[MCP] Update detail charge table with mock data

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29167]
## Issue Description
We have requested mock data from the liberty team and we will need to update our design spec with accurate mock data. 

---
## Tasks
- [ ] Update the table with mock data
- [ ] Upload to UXPin
- [ ] Update spec

## Acceptance Criteria
- [ ] UXPin updated and linked in this ticket
- [ ] Spec updated and linked in this ticket

**Comment by rebeccawalsh** [comment]
Blocked until Mike M. or Logan Smith can provide the mock data.

**Comment by rileyorr** [comment]
Moving this to blocked until we can receive the payload

**Comment by rileyorr** [comment]
@LindaLi123 I'm moving this into the backlog since we're changing the MVP's direction and removing the table.

**Comment by rebeccawalsh** [comment]
@denisecoveyduc 

Riley and I talked about this ticket, and we think there's not quite enough groundwork for us to do this work. We have mockups of our original detail transaction table, but the mock data we have access to doesn't seem to support it.

Our options are to either:
- Populate the table with the mock data as it exists without transforming it (but this would be an accessibility and general usability fail because it's all caps and very difficult to read based on user feedback), OR
- Do more engineering work to work our way back from the original mockup [image attached]

We probably need to discuss engineering work to really accomplish anything for this ticket. If we were to just "do this ticket," it will probably be a huge waste of time because the data we have is already pretty bad (e.g. prescriptions being broken up on 3 lines)

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/6428e513-9f27-454b-b0d2-e76284ebb6a3)

**Comment by denisecoveyduc** [comment]
This is no longer an issue and has been resolved in current production experience.
