### ISSUE TITLE
Expose Endpoint: Delete Clinic Profile

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#29164]
Dependency: Receiving the endpoints from Rob

- [x] Create λ
- [x] Attach to API gateway
- [x] Call VEText group authentication endpoint with User DUZ, Station number, and application key
- [x] Expose **DELETE CLINIC** endpoint in CHIP 

**Task is Done When:**
Endpoint is exposed and output is visible in postman
