### ISSUE TITLE
Begin Piloting the use of the TUD

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#29205]
## Issue Description
As a member of the VSP Testing Tools Team, I need to have a good understanding of the new Test User Dashboard (TUD) and it's use cases in order to help test it's functionality in the pilot, as well as to prepare for future work expanding the TUD functionality.

---
## Tasks
- [x] Review documentation provided by the Identity Team - LINKS NEED TO BE ADDED HERE
- [x] Get a briefing/run-through from the Identity Team
- [x] Do some tests for searching for/finding/checking out/checking in test users, to ensure the TUD works as intended
- [ ] Begin supporting VFS team requests for acceptable test users
- [ ] Identify and log metrics of these requests

## Acceptance Criteria
- [x] We have 2 people up to speed on the use/support of the TUD
- [x] We have helped resolve 10 requests for test user credentials
- [ ] We have logged/documented our findings from those 10 tests

**Comment by JoeTice** [comment]
Documentation/metric related tasks are going to be moved to a Dashboard task for this tool

**Comment by pjhill** [comment]
Since metrics will be worked under another ticket this can be closed.
