### ISSUE TITLE
[VAMC] Publish Systems into Dual-State and place Temp Web Banner on Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#29204]
## STORY
As a web user I need to be able to see my system in a web format, so I can complete my training and then fix how each page appears in a published state. 

## Resources
[Tugboat](https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASK
Publish systems that have been prepped and run through Tugboat with the following actions
**VISN-15**
- [x] Poplar Bluff health care
- [x] Wichita health care
- [x] St. Louis health care
**VISN-9**
- [x] Lexington health care
- [x] Louisville health care
- [x] Memphis health care
- [x] Mountain Home health care
- [x] Tennessee Valley health care
**VISN-22**
- [x] Greater Los Angeles health care
- [ ] Loma Linda health care
- [ ] Long Beach health care
- [x] New Mexico health care
- [x] Northern Arizona health care
- [x] Phoenix health care
- [x] San Diego health care
- [x] Southern Arizona health care
