### ISSUE TITLE
Complete usability sessions for Dep Ver

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#29219]
### Background
The 21-686c/674 is ready for usability testing. Sessions will be scheduled over the course of the coming weeks.

Resources:
- [Usability research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/research-design/usability-testing-1/dependent-verifiy-usability-1-research-plan.md)
- [Usability conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/research-design/usability-testing-1/dependent-verifiy-usability-1-convo-guide.md)

### Tasks
- [x] Pilot
- [x] Kick-off usability study
- [x] Get usability sessions scheduled
- [x] Conduct usability sessions
- [ ] Capture findings in usability table (Stretch: separate ticket)
- [ ] Topline summary (Stretch: separate ticket)

### Acceptance 
- [x] Complete usability sessions
