### ISSUE TITLE
Adjust Helpless Child on FE for 686 (FE)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#29225]
## Background
The status of a child being able to self support needs to be discrete so the Veteran can assign two statuses as needed

## Considerations
- Screenshot/mock: https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/978172b0-e41d-4fdf-9c69-900043ad3e39/
- Start with some basic language that describes what this means and take to Content for validation
- Combine with https://github.com/department-of-veterans-affairs/va.gov-team/issues/29227

## Tasks
- [ ] Breakout the check box for helpless out of the list so that it gets answered regardless of the child type, and set it as a yes/no
- [ ] Share with content for better words (stretch)

## Acceptance Criteria
- [ ] A new question exists that is specific to the ability of the child to self support
- [ ] A PR has been requested for merging, or is ready for BE to say go
