### ISSUE TITLE
When adding a step-child, include parent/guardian (FE)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#29227]
## Background
When adding a step-child, we need to include their parent / guardian so that all the info that BGS requires is in place

## Considerations
- Will we need to do this as well for adopted?
- Combine with https://github.com/department-of-veterans-affairs/va.gov-team/issues/29225
- Mockup: https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/978172b0-e41d-4fdf-9c69-900043ad3e39

## Tasks
- [x] Include a field that asks for name, DOB, and SSN
- [x] Schema update (need conditional fields for these)

## Acceptance Criteria
- [x] Additional fields included
- [ ] A PR has been requested for merging, or when BE is good to go

**Comment by jason-gcio** [comment]
Final tasks to be completed in ticket #35141
