### ISSUE TITLE
Claim Status Tool - Status and Events Discovery

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#29220]
## Issue Description
Determine what statuses come into the CST - the backend systems they come from and have it documented what status (or event) shows for claims and appeals.

---
## Tasks
- [ ] Document what we get back from the backend systems (what HTML shows to the user)

## Acceptance Criteria
- [ ] Statuses and events are documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
We have a list of the statuses and events that come from the appeals side, located here:

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/utils/appeals-v2-helpers.jsx#L290

**Comment by kevinstachura** [comment]
This ticket will need to be moved into next sprint since we needed technical assistance to find the rest of the statuses and events, and both our FE and BE devs (that know most about this) were on vacation during this sprint.

**Comment by vhenry07** [comment]
Next phase ticket created. Closing.
