### ISSUE TITLE
**DECISION TOOLS SPRINT 55 PRIORITIES**

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#29221]
<hr>

## 🏖️ Sprint 55 Vacation/PTO/Holidays
- Labor Day - Sept 6
- Zach - 8/25 - 8/27  🚚 🏡 (8 working days)
- Cassandra - Sept 4
- Cindy - Sept 7

<hr>

### 1. FIND A VA FORM PDF DOWNLOAD INSTRUCTIONS, EPIC #26816
- [x] Cindy -  Present PDF research findings to team - next week. 
- [x] Marci - #28397 
- [ ] Marci - Schedule meeting for Cindy to present research findings to VA stakeholders - and who are the right people to involve???

<hr>

### 2. DISCHARGE UPGRADE WIZARD CONTENT UPDATES - EPIC #27212
- [x] (Marci) - Monitor for feedback from DoD following Margarete's meeting with military boards on 8/31
- [ ] (Marci) - Collab cycle issues for changes if we are still moving forward
- [ ] (Marci) - Content request for changes if we are still moving forward

<hr>

### 3. YELLOW RIBBON 
- [ ] Cassandra - #29244 

### 4. TECH DEBT (all Find a VA Form this sprint)
- [x] Zach - #26908 
- [x] Zach - #23641 
- [x] Zach - [NOTE - TITLE IS STORED IN CMS] #26905
- [x] Zach - #26903 
- [ ] Zach - [NOTE - NEED CONFIRMATION WE HAVE CORRECT LINKS]#12535 (stretch)

<hr>

### 5. SEARCH UI DOCUMENTATION
- [ ] Zach, Megan, Marci - #24597 

###  🗨️  Discussion Topics/Grooming 
- [ ] Well-groomed issues for Yellow Ribbon discussion
- [ ] Topic
- [ ] Topic
