### ISSUE TITLE
When adding a step-child, include parent/guardian (BE)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#29235]
## Background
When adding a step-child, we need to include their parent / guardian so that all the info that BGS requires is in place

## Considerations
- Will we need to do this as well for adopted?
- Details:
`VnpPtcpnt`
`VnpPerson`
`VnpPtcpntRlnshp`
Need marriage date in `VnpPtcpntRlnshp` stored in begin date
- Check to see what we are doing with the date currently (date child entered your household (wasn't populating on the PDF, even though it was a required field)
- Ask Linda: "how does the VNP table handle a potentially duplicate new person in the same proc?"
- The VA, via RBPS, doesn't have a great way of mapping the date for when compensation should start but its been determined that it needs to reflect when the step-child enters the household and is deemed a dependent.  The language can stay the same for now and be passed along as if it were a date of marriage, but it might not be.  We need to:
1. Create a marriage relationship within the submission itself
2. Use the `begin_date` [sic] field to map

## Tasks
- [x] Include fields that asks for Name, DOB, and SSN, (DOM?)
- [x] Schema update (need conditional fields for these)

## Acceptance Criteria
- [x] Fields for the new data is included in the payload
- [ ] A PR has been requested for merging, or when BE is good to go

**Comment by jason-gcio** [comment]
Need clarification from Linda
