### ISSUE TITLE
R&S Updates:  Managing your VA.gov profile

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#29231]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/managing-your-vagov-profile/):  

Rework article to better reflect what info you can manage in your profile and what you have to change in DEERS.

### Tasks

- [x] SC to draft new copy deck (Laura)

- [x] DEPO revise copy deck(Beth)

- [ ] SC to make changes in Drupal (Laura)

- [ ] SC to QA and publish (Randi)

### Acceptance Criteria

- [ ] Updated page is live

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
