### ISSUE TITLE
VA debt experience wizard rework and updates

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#29230]
## Epic Description

This epic will help us track the VA debt experience (debt portal, FSR, medical copay portal) rework

## Definition of done

The following tickets have been completed:

- [x] [[FSR] Update 'Make a payment' terminus for wizard](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/23204)
- [ ] [[MCP - Usability recommendation] Evaluate the current use of the wizard as a primary navigation solution](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27942)
- [ ] [[FSR] Update the wizard to the proper PDF download pattern](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27641)
- [ ] [[FSR] Wizard - Debt Dispute Content Improvements](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26025)
