### ISSUE TITLE
Adjust helpless child 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#29233]
## Background
The status of a child being able to self support needs to be discrete so the Veteran can assign two statuses as needed

## Considerations
- Screenshot
- vnp field is: `<vnpSruslyDsabldInd>?</vnpSruslyDsabldInd>` inside of `vnpPerson`

## Tasks
- [x] Breakout the check box for helpless out of the list so that it gets answered regardless of the child type, and set it as a **yes/no**
- [x] Update PDF (separate 3 points)

## Acceptance Criteria
- [x] A new question exists that is specific to the ability of the child to self support
- [x] PDF is updated
- [ ] A PR has been requested for merging, or is ready for BE to say go

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29227

**Comment by kathleencrawford** [comment]
PR created in draft mode...waiting on confirmation of test results from BGS.
