### ISSUE TITLE
526: Discover & fix missing `treatedDisabilityNames`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29246]
## Description

There is a bug where the `treatedDisabilityNames` are being stripped. In the in-progress form, the veteran has:

```
"treatedDisabilityNames": {
  "condition (words in parens)": true,
  "anothercondition": true
},
```

but in when it gets posted to `/v0/disability_compensation_form/submit_all_claim` I see `"treatedDisabilityNames": [],`

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/29120

## Tasks

- [ ] Determine reason values are stripped out from submission
- [ ] Fix bug so values _are_ submitted
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Pushing this work to the next sprint.
