### ISSUE TITLE
MCP - Add VBS Config in DevOps repo

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#29248]
## Issue Description
In order to keep our configuration secure we need to put config options in [DevOps](https://github.com/department-of-veterans-affairs/devops) repo so they are not located in a open source repo.

---
## Tasks
- [ ] Add VBS Config in DevOps repo

## Acceptance Criteria
- [ ] VBS config is merged in DevOps repo
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LinnJS** [comment]
Waiting on production config details for this ticket as well.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/devops/pull/9926) where this work is being done
