### ISSUE TITLE
[PM, Design] Notification Prefs: Internal testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29256]
## Background
In order to prepare for QA we want to conduct a round of internal testing of our test scenarios so we can catch any last minute/lingering issues.

[Test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md)

## Tasks
- [x] AJ and Liz to run through all test scenarios in staging
- [x] Document any issues found
- [x] AJ to create tickets to resolve as needed

**Comment by andaleliz** [comment]
@ajakabcin are we ready to do this, or do you still need to identify staging users? Happy to set up some time for us once we are ready to rock. 

IIRC you said you and Tressa spent about a 1/2 day doing this for My VA. If that's accurate, I think we'd only need an hour for this since it's far less complicated.

**Comment by andaleliz** [comment]
Oh wait, I just saw that there isn't a sprint assigned to this. Got confused because it's in the `current sprint` pipeline.

**Comment by ajakabcin** [comment]
You're correct! it should be in this sprint, my mistake on not updating the milestone. 

Also, agreed - we won't need nearly as much time. Do you want to set something up for Friday?

**Comment by andaleliz** [comment]
Yep! I sent something up for us.  

Should we add #26223 as a blocker to this? Otherwise I'm not sure how we will check off the first task on this ticket 🙃

**Comment by andaleliz** [comment]
I've checked out what I'm able to at this point and things look good so far. I added the FE ticket #28982 as a blocker since we can't test the first two test cases until this is done.
