### ISSUE TITLE
QA Feedback - Staging Review - GI Bill Comparison Tool

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#29257]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/28682
- Thanks for using TestRail! The test cases are laid out very clearly and easy to follow.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
-  On the `School Details` page, there are spaces missing before some parentheses. Spaces must be added to be consistent with the rest of the page.
<img width="981" alt="Screen Shot 2021-08-25 at 2 28 52 PM" src="https://user-images.githubusercontent.com/3535749/130856603-edb416c3-ef13-4e4e-a51d-929a91ef2412.png">

- Scrolling of the school comparison table is not smooth. This should be fixed for a better user experience.

https://user-images.githubusercontent.com/3535749/131012565-a0de7377-cb86-4227-b503-7bdf8e1f9f3e.mov

**Should:**
- The search autocomplete options do not disappear after clearing the search box. Determine if this is acceptable behavior.

https://user-images.githubusercontent.com/3535749/130856822-bc6500f0-6fac-4c89-a6fb-c11767f7448a.mov

- On the `School Details` page, CSS might need to be modified so that long school names do not come as close to the edge of the `School` box.
<img width="762" alt="Screen Shot 2021-08-25 at 2 40 39 PM" src="https://user-images.githubusercontent.com/3535749/130856931-69696e07-f4f6-4a23-944c-771079070a96.png">

**Consider:**
- None

**Comment by dneel-bah** [comment]
@ddzz FYSA: I made this issue an epic and created individual tickets for the feedback so they can be closed out individually.
