### ISSUE TITLE
Replace Jenkins Daily Deploy to Production with GitHub Actions

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#29253]
## Details 

The daily-deploy-production GitHub action scripts for vets-website and content-build have been thoroughly tested in dev. As part of the effort to move completely to GitHub actions, we need to switch these scripts so that they deploy to production.

## Tasks

- [ ] Uncomment production code (and comment out dev code) in the daily-deploy-production scripts in vets-website and content-build
- [ ] Turn off the schedule for the Jenkins daily auto-deploy
- [ ] Thoroughly verify that the GitHub action daily-deploy-production script successfully deploys to production

## Potential Issues

How to handle potential issues while testing the production deploy:
- For failures related to GHA configuration, manually trigger deploy via Jenkins
- For failures related to failing commit statuses, manually trigger deploy via GHA dispatch

**Comment by oseasmoran73** [comment]
Consolidating ticket into #24191 . Closing this ticket
