### ISSUE TITLE
Merge Current GHA CI Workflow PRs to Partially Replace Jenkins

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#29252]
## Details

After thorough testing, the open pull requests that add most of the continuous-integration workflow to GitHub actions should be merged. These additions currently exclude the archive, deploy, and review instance steps. Because of this, the entire Jenkins CI workflow should not be disabled, but rather all the parts excluding the 3 steps previously mentioned. 

Lastly, the daily-deploy-production GHA workflow should be reverted back to check the GHA build status. It is important to make sure this is timed properly so that the daily deploy checks the proper location for the build status.

## Tasks

- [x] Verify that the continuous-integration workflow is working properly for vets-website
- [x] Verify that the continuous-integration workflow is working properly for content-build
- [x] Verify that the on-demand persistent runners are working consistently for content-build
- [x] Merge all remaining continuous-integration GitHub action pull requests

**Comment by oseasmoran73** [comment]
Edited task to omit removal of Jenkins. Closing this ticket as #29254 is updated with more recent information. Rather than removing all tasks from Jenkins for dev & staging, will be broken up into iterations. See referenced ticket for more info.
