### ISSUE TITLE
Expose Endpoint: Delete Group Profile

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#29261]
- [ ] Create λ
- [ ] Attach to API gateway
- [ ] Call VEText group authentication endpoint with User DUZ, Station number, and application key
- [ ] Expose **DELETE GROUP** endpoint in CHIP

**Task is Done When:**
Endpoint is exposed and output is visible in postman
