### ISSUE TITLE
Content updates to Fry Scholarship and Yellow Ribbon pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29274]
## Issue Description
Stakeholder Tammy Hurley has requested updates to both the Fry Scholarship and Yellow Ribbon pages. We need to make plain language edits to the new content and publish. 

Here are the Fry Scholarship PL edits from Beth: 

[https://app.zenhub.com/files/133843125/556163c5-a8e8-4cef-80f7-bfc4a932e848/download](https://app.zenhub.com/files/133843125/556163c5-a8e8-4cef-80f7-bfc4a932e848/download)

## Tasks
- [x] Make plain language edits to Fry Scholarship page
- [x] Make plain language edits to Yellow Ribbon page
- [x] Update Fry Scholarship in Drupal
- [x] Update Yellow Ribbon in Drupal
- [x] Review and publish Fry Scholarship page
- [ ] Review and publish Yellow Ribbon page
- [ ] Notify stakeholders that pages are live

## Acceptance Criteria
- [ ] Changes to Fry Scholarship and Yellow Ribbon are live on the site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please attach here the Word doc I just slacked you--I'm having trouble attaching Word docs to tickets. And you can queue up these edits in drupal. Hold on publishing until we hear back from stakeholders with a thumbs up. Also, see my note to you in the comments. There's one bullet's worth of text that isn't approved yet.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I made some more edits and relinked two spots that had become unlinked when previous edits were added in the blue box. We may hear from Education Service with one more minor change and possibly a rewrite of the last accordion on the page, but we'll create a separate ticket for that if need be. I also notice a missing comma before one of the bolded "or"s if you want to make that one quick fix. Closing this work out since it's live now.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Per the last edit to come from stakeholders, I updated the note in the blue box with new edits (and I broke that huge paragraph into 2). Would you please proofread that text? 

Also, I noticed that the header in the blue box isn't appearing in "On this page" so I think you'll need to change that to an H2. Are we having this problem on all our pages that have blue boxes?

Then you can publish this.

**Comment by bethpottsVADEPO** [comment]
OK, @RLHecht I made one last edit from the stakeholder. Now you can publish.

**Comment by RLHecht** [comment]
I fixed the header sizes in the blue box and published the page.
