### ISSUE TITLE
[Monitoring] Get External Secrets working in Datadog

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29398]
## Description
Implement openmentrics integration for External Secrets pod in order to make sure the Datadog agents are scraping the /metrics endpoint and sending to Datadog.

## Technical notes
https://docs.datadoghq.com/agent/kubernetes/prometheus/#configuration-1 

---
## Tasks
- [x] add correct annotations to external secrets pod
- [x] Create basic dashboard for external secrets
- [x] Add simple alert to #devops-alerts to give us visibility into external secrets issues

## Acceptance Criteria 
- [x] metrics are received by Datadog
- [x] alert is configured
- [x] dashboard is created

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by dginther** [comment]
Looks good!
