### ISSUE TITLE
[Monitoring] Get Sentry metrics working in Datadog

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29397]
## Description
Implement openmentrics integration for Sentry pods (sentry-metrics) in order to make sure the Datadog agents are scraping the /metrics endpoint and sending to Datadog.

## Technical notes
https://docs.datadoghq.com/agent/kubernetes/prometheus/#configuration-1 

---
## Tasks
- [x] add correct annotations to sentry pod
- [x] Create basic dashboard for sentry
- [x] Add simple alert to #devops-alerts to give us visibility into sentry issues

## Acceptance Criteria 
- [x] metrics are received by Datadog
- [x] alert is configured
- [x] dashboard is created

**Comment by jhouse-solvd** [comment]
Checked it out. This looks good to go. 

Closing.
