### ISSUE TITLE
[MCP] Use case: Veteran is not copay required

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29393]
## Issue Description
This ticket is part of the epic where we will be creating mocks for each of our use cases for testing and engineering purposes.

**Use case:** Veteran is not copay required

---
## Tasks
- [x] Create a design that reflects the use case above
- [x] Upload to UXPin
- [x] [Update GH design readme file](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/Debt%20Resolution/Medical_Copays/design/README.md)

## Acceptance Criteria
- [x] Designs uploaded to UXPin
- [x] GH design readme updated and linked in ticket

**Comment by rileyorr** [comment]
We thought through this use case and came up with two possibilities:
- Veteran is not copay required and doesn't have any VPS for the past 24 months
- Veteran is not copay required and has an active balance for at least one facility 

---

The solution we came up with for each of those possibilities:
**Veteran is not copay required and doesn't have any VPS for the past 24 months**
They'll see the same error message for not having statements for the past 24 months ([UXPin](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141468842/simulate/sitemap?mode=i))

**Veteran is not copay required and has an active balance for at least one facility**
They'll see the default overview page that shows the card(s) with their balance(s) ([UXPin](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140669280/simulate/sitemap?mode=i)). We considered displaying an alert that they're no longer copay required, but isn't vital to display since it doesn't impact the active balances. We may revisit this when we work on the feature that displays priority groups.
