### ISSUE TITLE
526: Fix typo in schema

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29394]
## Description
In order to ensure that content is correct in our forms we need to update a typo found in `vets-json-schema` and `vets-api` - "Doctoral degre" (one "e").  A search in these folder should show the offenders.

## Tasks

- [x] Fix typo in `vets-api` files (x3) and bump `vets-json-schema` version
- [x] Fix typo in `vets-json-schema` files (x3)
- [x] bump `vets-json-schema` version in `vets-website`
- [x] Verify all tests passing

## Definition of done

- [x] All tasks complete
- [x] All test passing

**Comment by scottymeyers** [comment]
This also updates `vets-website` to use the new version.

**Comment by scottymeyers** [comment]
Just waiting on the `vets-website` pull request to be approved by all parties and this can be closed out.
