### ISSUE TITLE
[EKS/Datadog] - setup dns checks to vfs.va.gov on datadog node agents

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29402]
## Description
Set up DNS checks to be triggered from Datadog agents that live in EKS to test vfs.va.gov

## Background/context 
https://dsva.slack.com/archives/CJYRZK2HH/p1629930995096700

## Technical notes
https://github.com/DataDog/integrations-core/tree/master/dns_check
https://github.com/DataDog/integrations-core/blob/master/dns_check/datadog_checks/dns_check/data/conf.yaml.example#L33
https://github.com/DataDog/helm-charts/blob/718638749f2cceeec0bd09d9de2e86421976ee96/charts/datadog/values.yaml#L575-L578

---
## Tasks
- [ ] add dns_check to datadog helm chart confd config block
- [ ] redeploy datadog agent

## Acceptance Criteria 
- [ ] DNS checks are aggregated back to Datadog interface

**Comment by jhouse-solvd** [comment]
It looks like this is working. 

Closing.
