### ISSUE TITLE
DISCOVERY - forms library support for I18n - existing web components and beyond

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#29403]
## Issue Description
In building a sample POC app with support for spanish and tagalog languages, there may be base components of the forms system that need to be modified to accept all the parameters present in a multi-lingual system. For example the existing va-text-input web component doesn't have a way to override the `*Required` text to support a different language

## Tasks
- Document modifications to the web-components that would be needed to support I18n
- Document any other components and application pieces that would require i18n efforts

## Acceptance Criteria
- [x] Doc created for web-component requirements
- [x] Create PR or POC component edits where possible as an example of what would be needed.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by adamwhitlock1** [comment]
Documented basic needs here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/app-translation.md
