### ISSUE TITLE
[FSR] Submit Transformer Unit Test

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29413]
## Issue Description
Once payload submissions have been verified by the DMC we need to create a unit test for the submission payload transformer to ensure the correct data is passed

---
## Tasks
- [x] Create test for payload transformer

## Acceptance Criteria
- [x] Transformer test should be passing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
