### ISSUE TITLE
[MCP] Use case: Veteran has no history of medical copay bills

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#29426]
## Issue Description
This ticket is part of the epic where we will be creating mocks for each of our use cases for testing and engineering purposes.

**Use case:** Veteran has no history of medical copay bills
---
## Tasks
- [x] Create a design that reflects the use case above
- [x] Upload to UXPin
- [x] [Update GH design readme file](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/Debt%20Resolution/Medical_Copays/design/README.md)

## Acceptance Criteria
- [x] Designs uploaded to UXPin
- [x] GH design readme updated and linked in ticket
