### ISSUE TITLE
R&S Updates: How do I change my name in my DEERS record?

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#29423]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/how-do-i-change-my-name-in-my-deers-record/)

- On our Sitewide Content team call, we agreed that, once the changes to the **Managing your VA profile** article were live, we would add a link to it on this page under **Related information**: 

### Tasks

- [x] DEPO to approve changes as described above (Beth approved on a team call)

- [x] SC to make changes in Drupal (Laura)

- [x] SC to QA and publish (Randi)

### Acceptance Criteria

- [x] Updated page is live
