### ISSUE TITLE
Implement COE prototype content feedback

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#29435]
### Background
The COE policy team has provided feedback on the content of the COE prototype screens. Some light revisions to functional form elements are needed as well.

### Consideration
On-screen prototype functionality will be implemented in subsequent rounds. Prototype fixes will be static. 

### Tasks
- [x] Implement text changes across all COE screens
- [x] Implement a conditional text field for the "other" selection on all upload screens 

### Acceptance criteria
- [x] Prototype updated with content and ~~functional changes~~

**Comment by sporeboy** [comment]
All edits in place (I beleive): https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139055586

**Comment by sporeboy** [comment]
Functional fixes (e.g. accordions) are extensive, and will be addressed in a different issue.
