### ISSUE TITLE
attr_encrypted strategy to collect encrypted db attributes for parent and child classes

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#29446]
## Issue Description
The [current rake task solution](https://github.com/department-of-veterans-affairs/vets-api/pull/7552/files#diff-1e7f0bc7bd1066fb5eb28c290f276a28cefe57a55caaf5d408d4493ff38a2a34R29) uses `ApplicationRecord.descendants` to gather encrypted_attributes on existing models. 

I think there may be some redundancy in this approach because `ApplicationRecord.descendants` will collect child AND parent classes, duplicating the ActiveRecord saves. For example, we have a `SavedClaim` class and `SavedClaim::Ask < SavedClaim`. The current implementation will collect the parent SavedClaim records AND the child SavedClaim::Ask records.

We may want to refactor the logic to collect one or the other, otherwise we will save any (child) subclass record twice 

---
## Tasks
- [ ] Fact check the above statement
- [ ] Implement Solution based on above findings 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
We may want to collect ONLY the classes that have no descendants. E.g. All of the child classes or classes without child classes. If we ALSO collect the parent classes, we will be saving records twice. E.g. if we iterate over `SavedClaim::Pension` records, we will iterate over those same records again when iterating over the `SavedClaim` (parent) class. 

`ApplicationRecord.descendants.select{ |d| d.descendants.empty? }.map{ |d| d.name.constantize }`

**Comment by LindseySaari** [comment]
# Staging information:

I've done some benchmarking in the staging env. It appears that there are a few records that have an inheritance column that IS NOT a current subclass

`ApplicationRecord.descendants.select{ |d| !d.descendants.empty? }` # lists all parent classes


`
parent_models = [
  SavedClaim,
  CentralMailClaim,
  SavedClaim::EducationBenefits,
  SavedClaim::DisabilityCompensation,
  FormAttachment,
  BaseFacility,
  PersistentAttachment,
  AsyncTransaction::Base,
  AsyncTransaction::Vet360::Base,
  AsyncTransaction::VAProfile::Base
]
`

`
parent_models.each do |m|
  subclasses = m.descendants.collect{ |d| d.name }
  klass_record_count = m.where('#{m.inheritance_column} NOT IN (?)', subclasses).count

  puts '!#{m.name} - total records where type not a valid subclass: #{klass_record_count}'
end

`

## The above returned:

SavedClaim - total records where type not a valid subclass: 156
CentralMailClaim - total records where type not a valid subclass: 0
SavedClaim::EducationBenefits - total records where type not a valid subclass: 0
SavedClaim::DisabilityCompensation - total records where type not a valid subclass: 0
FormAttachment - total records where type not a valid subclass: 0
BaseFacility - total records where type not a valid subclass: 2455
PersistentAttachment - total records where type not a valid subclass: 0
AsyncTransaction::Base - total records where type not a valid subclass: 6
AsyncTransaction::Vet360::Base - total records where type not a valid subclass: 0
AsyncTransaction::VAProfile::Base - total records where type not a valid subclass: 0

**Comment by LindseySaari** [comment]
## Prod Benchmarking
The following are the number of prod records where the type (inheritance column) is not a valid subclass

SavedClaim - total records where type not a valid subclass: 11616
CentralMailClaim - total records where type not a valid subclass: 0
SavedClaim::EducationBenefits - total records where type not a valid subclass: 0
SavedClaim::DisabilityCompensation - total records where type not a valid subclass: 0
FormAttachment - total records where type not a valid subclass: 17052
PersistentAttachment - total records where type not a valid subclass: 0
AsyncTransaction::Base - total records where type not a valid subclass: 0
AsyncTransaction::Vet360::Base - total records where type not a valid subclass: 0
AsyncTransaction::VAProfile::Base - total records where type not a valid subclass: 0
