### ISSUE TITLE
[EXCEPTION] 674 Failure Mailer Error

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#29441]
## Background
The failure mailer for the 674 is sometimes failing with `ActiveJob::SerializationError Unsupported argument type: User`

## Considerations
Logging in Sentry: http://sentry.vfs.va.gov/organizations/vsp/issues/41332

## Tasks
- [x] Investigate the issue

## Acceptance Criteria
- [x] Establish a path forward
- [x] (STRETCH) implement a fix
- [ ] A PR has been requested for merging
