### ISSUE TITLE
Deploy plan for attr_encrypted key rotation

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#29445]
## Issue Description
When running the attr_encrypted key rotation in the dev environment, the rake task caused the CPU to spike and instances started to drop and cycle. 

The dev environment has much smaller instance types than the prod environment, but we want to be sure that running the rake task will not cause a similar issue in prod or staging. There are nearly 8 million production records that the rake task will need to resave/re-encrypt.

We also want to brainstorm a testing strategy. When deploying via git ref, if another change is merged to master, the new AMI will be deployed and overwrite any changes deployed via git ref. To avoid this issue, I reached out to the Operations team to detach an instance, but we may want to formalize this testing strategy. Other ideas are welcome as well. 

---
## Tasks
- [ ] Brainstorm testing strategy
- [ ] Research instance types and CPU load

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
[Running a GHA workflow on a schedule](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events)

**Comment by LindseySaari** [comment]
Helpful notes: See the[ aws parameter store injector](https://github.com/marketplace/actions/aws-parameter-store-injector)

**Comment by ericboehs** [comment]
Closing in favor of our (eventual) move to KMS.
