### ISSUE TITLE
Determine if Foreign Address Mappings Need Adjustment

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#29449]
## Background
In 686 launch QA, there were a few errors related to foreign addresses not mapping correctly, where the error indicated that the city could not be left blank

## Considerations
Not sure if this is an issue with schemas or VNP tables

## Tasks
- [ ] Check that the foreign addresses, when checked, maps correctly
- [ ] ...

## Acceptance Criteria
- [ ] Foreign addresses are mapping correctly
- [ ] A PR has been requested for merging, if needed

**Comment by jason-gcio** [comment]
Done!
https://github.com/department-of-veterans-affairs/vets-api/pulls?q=is%3Apr+foreign+address+is%3Aclosed
