### ISSUE TITLE
ActiveRecord::SubclassNotFound - STI data issues

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#29444]
## Issue Description
While testing the attr_encrypted key rotation in the dev and staging environments, a few instances of ActiveRecord::SubclassNotFound errors were found. 

`ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass errors for the SavedClaim records`

It seems that the type column is from a subclass the no longer exists. With Single Table Inheritance, the type column is used to saved the class name of child classes. Ex: `CentralMailClaim < SavedClaim`

Ex: run SavedClaim.first in the staging env to see the mentioned issue

It's most likely that we have old data in the type column and it needs to be updated/deleted OR maybe this table is not meant to use STI? 

More background information is needed

---
## Tasks
- [ ] Research child STI classes that may no longer exist
- [ ] Do we need the db record if the class no longer exists? 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
## Staging Findings: 

I ran the following: 
`subclasses = ApplicationRecord.descendants.collect{ |d| d.name }`
`SavedClaim.where("type NOT IN (?)", subclasses).count`

There are 156 records that have a type/subclass of something other than what's allowed

**Comment by LindseySaari** [comment]
Update:

I’ve narrowed down the STI issues with non existing types/subclasses of SavedClaim. There are two types in question: `SavedClaim::DisabilityCompensation::Form526IncreaseOnly` and `SavedClaim::EducationBenefits::VA1995s`

For the `SavedClaim::DisabilityCompensation::Form526IncreaseOnly` records, it looks like `SavedClaim::DisabilityCompensation` records were migrated [here](https://github.com/department-of-veterans-affairs/vets-api/pull/2593/files#diff-0f1b0208c79d97ef65a1049c67fc2ab70333e8eb2bf54ff0b8d04b0640b0aeeaR75-R81) to have the type of `SavedClaim::DisabilityCompensation::Form526IncreaseOnly`. Since the saved_claim table uses the type column for single table inheritance, and 'SavedClaim::DisabilityCompensation::Form526IncreaseOnly' is not a subclass of SavedClaim, this is throwing errors when trying to update SavedClaim records as part of the database key rotation efforts. The next step is to see if the increase only form class should be added in or if the data can be migrated in some way.

The `SavedClaim::EducationBenefits::VA1995s` was removed in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4886). I've asked in this vsa-education slack channel [here](https://dsva.slack.com/archives/CG6N59X40/p1630416820006800). Next step is to see if this data is stale/can be deleted or if we need to migrate it to another class.

**Comment by LindseySaari** [comment]
According to [Daniel Shawkey](https://dsva.slack.com/archives/CG6N59X40/p1630417803007000?thread_ts=1630416820.006800&cid=CG6N59X40), the VA1995s records can be deleted
