### ISSUE TITLE
Fix Military Address for 686 Submissions

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#29440]
## Background
When a 686 is submitted with a military address, the address does not get mapped properly when sent to BGS, which causes an error `city cannot be empty or nil`.

## Tasks
- [x] Determine how military address fields map to BGS address fields
- [x] Update the 686 submission to map the address fields correctly

## Acceptance Criteria
- [x] A 686 claim is successfully created for a Veteran with a military address
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
Changed the estimate from a 3 to a 5 because foreign addresses are also broken (not just military) and also because the bgs gem needed to be updated, which was not accounted for initially.

**Comment by RudyOnRails** [comment]
Linda confirmed the address tests from Friday had no error `City cannot be null`
