### ISSUE TITLE
[Kubernetes] Sentry - point test environment images to ECR

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29455]
## Description
The current deployment of sentry-test in eks is attempting to pull images from docker hub which is running into a rate-limiting issue and resulting in image pull errors.  Point this to our internal ECR to resolve said errors.

---
## Tasks
- [x] add configurations to values-sentry-test.yml
- [x] redeploy sentry-test 

## Acceptance Criteria 
- [x] sentry-test no longer has image pull errors

**Comment by dginther** [comment]
Looks good. Closing.
