### ISSUE TITLE
VAMC informational alerts settings are not honored by FE

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29459]
## Issue Description
Content editors use system wide alert options to specify which pages should display full width alerts. Currently, the front end does not seem to follow these settings. 

Setting: `Limit banner display to the home and operating status page(s)` - by default, if unchecked, banner should display on all pages for the selected VAMC system

### Current behavior
- alert displays only on the home page, regardless of setting

### Example:

Louisville health care (Kentucky, VISN 9)
alert : Website coming soon - not the official VA Louisville health care website
- setting: box to limit to home and operating status page **is _not_ checked**
- expected behavior: alert displays on all pages 
- FE: alert is displayed **on the home page only**

Relevant nodes: 
Louisville health care system node = 14991
Operating status node= 23274

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/131364911-456dee52-3b09-413e-a8e8-e765d6eaec91.png)

![image](https://user-images.githubusercontent.com/55411834/131366245-e1536589-966e-4444-823e-54bf41a798b5.png)

![image](https://user-images.githubusercontent.com/55411834/131366302-50bd5d75-b565-47d3-beeb-cff101527a20.png)

</details>

### Other information
- field = `AlertInheritanceSubpages` (this is not a new setting)
- settings apply at alert level -> different alerts at the same health care system can have separate settings
- Adrian on the CMS team confirmed that the field comes across with the correct value in the GraphQL explorer on prod (in this case for Popular Bluffs) 
- [Component](https://design.va.gov/components/alertboxes#full-width-alerts)
- Does not appear to be a regression from the recent work done to banners

<details>
<summary> Query </summary>

```
{
  nodeQuery(limit: 500, filter: {conditions: [{field: "status", value: "1", operator: EQUAL}, {field: "type", value: "full_width_banner_alert"}]}) {
    entities {
      ... on NodeFullWidthBannerAlert {
        title
        fieldBody {
          processed
        }
        entityId
        fieldAlertType
        fieldAlertDismissable
        fieldAlertFindFacilitiesCta
        fieldAlertOperatingStatusCta
        fieldAlertEmailUpdatesButton
        fieldAlertInheritanceSubpages
        fieldAdministration {
          entity {
            entityId
          }
        }
        fieldOperatingStatusSendemail
        fieldBannerAlertSituationinfo {
          processed
        }
        fieldSituationUpdates {
          entity {
            ... on ParagraphSituationUpdate {
              fieldWysiwyg {
                processed
              }
            }
          }
        }
        fieldBannerAlertVamcs {
          entity {
            ... on NodeVamcOperatingStatusAndAlerts {
              title
              entityUrl {
                path
              }
              fieldOffice {
                entity {
                  ... on NodeHealthCareRegionPage {
                    title
                    entityUrl {
                      path
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary> Screenshot of query</summary>

![image](https://user-images.githubusercontent.com/55411834/131370253-14b1654b-e74b-4a78-a7df-ac7add004517.png)

</details>

### Out of scope
- dismissable setting
- CMS team may change the field title and help text in the CMS to reflect the reality of how the field is being used and 
determine the best editor UX for the field, implement that, and change the field name if necessary to better communicate its purpose

---
## Tasks
- [ ] Investigate/correct how `fieldAlertInheritanceSubpages` setting impacts FE rendering of alerts
- [ ] Add/expand tests to cover

## Acceptance Criteria
- [ ] If box to limit to home and operating status page **is _not_ checked**(=`false`), the associated informational alert displays on all pages for the designated VAMC systems
- [ ] If box to limit to home and operating status page **is checked**, the associated informational alert displays on only the home and operating status pages for the designated VAMC systems
- [ ] Tests are present to cover this scenario

**Comment by mpelzsherman** [comment]
Confirmed alert is showing on https://www.va.gov/erie-health-care/news-releases/erie-vamc-hosts-veteran-town-hall/.

**Comment by mmiddaugh** [comment]
Doublechecked Louisville health care in CMS Prod - set to default (display on all pages). Working as expected. thank you!
